### ISSUE TITLE
gradio Model hub broken link 

### ISSUE THREAD

**Issue by 1Paws7** [gradio-app/gradio#100]
This is the broken link:--
![Screenshot (286)](https://user-images.githubusercontent.com/74103126/104949934-c86e8080-59e5-11eb-8530-7a9920884d84.png)

This is the repo on Model hub i m trying to see:--
![Screenshot (286)](https://user-images.githubusercontent.com/74103126/104949984-de7c4100-59e5-11eb-97b1-449f0281dc2a.png)

plz fix this broken link  In Model hub to github rep there is a Gradio interface for Identifying Skin Cancer but when i click on the github link it is broken and not redirecting me to the github repo , i want to quickly see and check that repo as i want to iterate fast by using gradio for my own classification model , so plz Can u Quickly fix that broken link or provide me the link of that repo ?

**Comment by aliabid94** [comment]
Fixed. THank you for pointing this out!
