### ISSUE TITLE
Add possibility to create asterisk mask for textbox

### ISSUE THREAD

**Issue by flacomalone** [gradio-app/gradio#10019]
- [X] I have searched to see if a similar issue already exists.

In some situations it might be handy to let a textbox (or maybe a different component to serve this purpose) specify a masked value shown in the display while typing its value. Something like showing asterisks (*************) instead of the real value. 

This could be good, for isntance, for applications where a secret field must be specified.

**Comment by abidlabs** [comment]
Hi @flacomalone this is already supported -- simply set `type="password"` in `gr.Textbox`!

**Comment by hellofinch** [comment]
@abidlabs hello, I meet some problem when I use textbox with password.
I use `gr.update()` to set a textbox's type to `password`. But it doesn't work. Here are some codes in my program.
```
service = gr.Dropdown(
    label="Service",
    choices=service_map.keys(),
    value="Google",
)
envs = []
for i in range(3):
    envs.append(
        gr.Textbox(
            visible=False,
            interactive=True,
            type='password'
        )
    )
def on_select_service(service, evt: gr.EventData):
    translator = service_map[service]
    _envs = []
    for i in range(4):
        _envs.append(gr.update(visible=False, value=""))
    for i, env in enumerate(translator.envs.items()):
        _envs[i] = gr.update(
            visible=True,
            label=env[0],
            value=ConfigManager.get_env_by_translatername(
                translator, env[0], env[1]
            ),
           type='passworkd'
        )
    _envs[-1] = gr.update(visible=translator.CustomPrompt)
    return _envs
service.select(
    on_select_service,
    service,
    envs,
)
```
