### ISSUE TITLE
Add `container` parameter to `gr.HTML` component

### ISSUE THREAD

**Issue by nuclearrockstone** [gradio-app/gradio#10010]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Because some components have no outer borders, the page is inconsistent
![image](https://github.com/user-attachments/assets/86cc3d97-3896-460d-97da-4d94409cb268)

**Describe the solution you'd like**  
I hope that when this type of component is initialized, I can choose whether to have the same appearance as other components.

**Additional context**  
Gradio is very powerful

**Comment by abidlabs** [comment]
Hi @nuclearrockstone we can add a `container` parameter to `gr.HTML` component to help achieve this. I've renamed the issue to reflect. Note that in the meantime, you can use `gr.Markdown`, which has such a parameter and also supports HTML

**Comment by yinsumirage** [comment]
Hi @abidlabs I've reproduced the issue and I'll finish this modification, just like in gr. Markdown.

**Comment by abidlabs** [comment]
@yinsumirage if you would like to open a pull request, go for it, we are happy to review!
