### ISSUE TITLE
I want to specify the resolution of the Webcam

### ISSUE THREAD

**Issue by Azunyan1111** [gradio-app/gradio#10027]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Currently the resolution is hardcoded.

gradio/js/image/shared/stream_utils.ts
```gradio/js/image/shared/stream_utils.ts
export async function get_video_stream(
	include_audio: boolean,
	video_source: HTMLVideoElement,
	device_id?: string
): Promise<MediaStream> {
	const size = {
		width: { ideal: 1920 },
		height: { ideal: 1440 }
	};
```

**Describe the solution you'd like**  
It would be great if you could specify the resolution.

```
gradio.Image(label="Input", sources="webcam",webcam_height=720,webcam_width=1280)
```

**Comment by yinsumirage** [comment]
i get it, i'll try for it.
