### ISSUE TITLE
LaTeX formulas are not displayed correctly

### ISSUE THREAD

**Issue by jason571** [gradio-app/gradio#10039]
### Describe the bug

![image](https://github.com/user-attachments/assets/a8d4a6ee-db42-4892-9eba-db08b8418601)
计算公式
分辨力 ( r )：
[
r = \frac{1}{\bar{U}} \times 100%
]
非线性度 ( \delta_1 )：
[
\delta_1 = \frac{\left| f_{f i}^2 - \overline{f_i^2} \right|_{\max}}{\bar{U}} \times 100%
]
滞后 ( \delta_2 )：
[
\delta_2 = \frac{\left| f_{p i}^2 - f_{r i}^2 \right|_{\max}}{\bar{U}} \times 100%
]

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

        # 右侧聊天界面
        with gr.Column(scale=20, min_width=900):
            chat_bot = gr.Chatbot(height=600)
            chat_bot.like(vote, None, None)
            chatbot_interface = gr.ChatInterface(
                fn=chatbot,
                chatbot = chat_bot,
                #textbox=gr.Textbox(placeholder="Ask me a yes or no question", container=True, scale=7),
                theme="soft",
                examples=["你是谁？", "test", "位移计性能参数以及计算公式弦式位移计性能参数以及计算公式","今天是几月几号？"],
                #multimodal=True,
                cache_examples=False
            )
```

### System Info

```shell
version 5.7
```

### Severity

I can work around it

**Comment by jason571** [comment]
stream output

**Comment by abidlabs** [comment]
Hi @jason571 can you please provide a self-contained code example with a description in English of the problem?

**Comment by jason571** [comment]
async def chatbot(user_input, chat_history):
    """stream output"""
    current_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    user_id = "user"
    mylogging.info(f"user: {user_id}")
    full_response = ""
    try:
        chatInterface = ChatInterfacePool.get_instance(user_id)
        t = time.time()
        async for item in chatInterface.run_astream_response(user_input):
            if 'data' in item and 'chunk' in item['data']:
                chunk = item["data"]["chunk"]
                # Ensure that chunk is an instance of AIMessageChunk and has content
                if chunk:
                    full_response += chunk.content
                    chat_history = full_response
                    yield chat_history

        coast_time = time.time() - t
        chatInterface.save_output_to_file(f'Assistant: {coast_time:.4f}s\n{full_response}')
    except Exception as e:
        mylogging.error(f"Error in chat function: {str(e)}")
        chat_history = f"user：{user_input}, ：{str(e)}"
    yield chat_history

**Comment by Qsy61** [comment]
请问这个问题解决了吗？ @jason571
