### ISSUE TITLE
HuggingFace webpage not showing properly

### ISSUE THREAD

**Issue by jaekookang** [gradio-app/gradio#1005]
### Describe the bug

Hello. I just found that the HugginFace website is not properly showing from the web browsers both Chrome and Safari at least from my Macbook (2022-04-15 Fri, KST 15:31 from Korea).

I was trying to use some of the Gradio demos under Spaces, but they are not showing up properly. 

Is this only temporary or should I try something else other than refreshing?

Thanks!

---
Here are the screenshots:

![Screen Shot 2022-04-15 at 3 27 14 PM](https://user-images.githubusercontent.com/18749927/163531217-32488616-991b-4761-a5d7-9f8cd61711c9.png)

![Screen Shot 2022-04-15 at 3 27 23 PM](https://user-images.githubusercontent.com/18749927/163531210-80dd8eaf-dff3-457b-b021-ad4521bd914b.png)

### Reproduction

https://huggingface.co/

### System Info

```shell
macOS Version 12.3.1
Chrome Version 100.0.4896.88 (Official Build) (x86_64)
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Thanks @jaekookang, we're on it! Should be fixed soon

**Comment by jaekookang** [comment]
It's fixed! Thanks!
