### ISSUE TITLE
Chatbot in chat_interface.py has fixed 200 height

### ISSUE THREAD

**Issue by myke11j** [gradio-app/gradio#10063]
### Describe the bug

I'm looking into chat_interface.py file and here (https://github.com/gradio-app/gradio/blob/main/gradio/chat_interface.py#L236) the line is 

```
height=200 if fill_height else None,
```

So if fill_height=True which is default, height of chatbox area will be just 200px. 
I don't know why it it like that and is there's any way to override it. For now I just made the change in the file directory on my local with

```
height=80vh if fill_height else None,
```

but obviously this can't be a solution for production.

So I would love to know if there's a correct way to do this because right now my chatbot text area takes half of screen.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
 with gr.Blocks() as demo:
        with gr.Row():
            with gr.Column(scale=2):
                gr.ChatInterface(
                    answer_fn
                )
            with gr.Column(scale=1):
               timestamp_text = gr.Text(f'Last synced at UTC {LAST_SYNCED}', label='Last sync timestamp')
```

### System Info

```shell
gradio==5.6.0
gradio_client==1.4.3
python=3.12
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Going to close this for now, but let us know if there's still an issue here @myke11j

**Comment by myke11j** [comment]
thanks @hannahblair, this works!
