### ISSUE TITLE
Add integer type for `gradio.Number`

### ISSUE THREAD

**Issue by joowon-dm-snu** [gradio-app/gradio#1007]
**Is your feature request related to a problem? Please describe.**

Code below raise `TypeError: can't multiply sequence by non-int of type 'float'`
```python
def main(n_samples):
    ...
    uc = model.get_learned_conditioning(n_samples * [""])
    ...

iface = gr.Interface(
    fn=main,
    inputs=[
        gr.inputs.Number(default=200),
    ]
    ...
```

For solving that issue, I needed to change `def main` like below 

```python
def main(n_samples):
    ...
    n_samples = int(n_samples)
    uc = model.get_learned_conditioning(n_samples * [""])
    ...
```

**Describe the solution you'd like**
```python
iface = gr.Interface(
    fn=main,
    inputs=[
        gr.inputs.Number(default=200, integer=True),
    ]
    ...
```

**Additional context**

**Comment by FarukOzderim** [comment]
Hello @joowon-dm-snu, thanks for reporting.
If you check the Number component, it supports float not int.

**Comment by abidlabs** [comment]
I think what @joowon-dm-snu is asking here is for us to have a parameter that automatically preprocesses the Number input into an integer. That's not a bad idea -- why did we close this?

**Comment by FarukOzderim** [comment]
Sorry my bad, misunderstood the issue.

I feel negative about this, what would happen when integer conversion is unsuccessful, throw an error?
Wouldn't it be better for user to convert to int when he/she is going to use it?

**Comment by joowon-dm-snu** [comment]
Issue was for feature-request not for error report :) Thanks @abidlabs .

@FarukOzderim is there any possibility that `float -> int` conversion throw error?
I needed to change `argparse.ArgumentParser()` styled [code](https://github.com/CompVis/latent-diffusion/blob/main/scripts/txt2img.py) to `gradio` and face this issue that I need to all integer parameters by using code below. 
```python
def foo(..., ddim_steps, n_iter, H, W, n_samples, ...):
    ...
    ddim_steps = int(ddim_steps)
    n_iter= int(n_iter)
    H= int(H)
    W = int(W)
    n_samples = int(n_samples)
    ...
```
I still fill this is pretty redundant and hope `gradio` provide more easier approach for this.
Anyway its just feature proposal so skip it if this is not appropriate for future implements :)

**Comment by FarukOzderim** [comment]
Thanks for the suggestion.

For example it can throw an error when it is converting 3.14 to integer

**Comment by abidlabs** [comment]
> For example it can throw an error when it is converting 3.14 to integer

No, casting a float to an int just takes the integer part and drops the decimal part, so for example:

```py
>>> int(3.14)
3
```

But in fact, we could even do this better by enforcing the integer constraint in the frontend. If the component is `Number(dtype="int")`, we prevent users from typing in the decimal point "." in the same way we prevent them from typing in letters right now. 

Opening this issue because even though we might not implement it immediately, it's a reasonable request and one we might consider down the road.

**Comment by joowon-dm-snu** [comment]
Thanks :)

**Comment by FarukOzderim** [comment]
Yeah that's correct lol :D,

Agreed, makes sense. @joowon-dm-snu  Thanks for the suggestion

> > For example it can throw an error when it is converting 3.14 to integer
> 
> No, casting a float to an int just takes the integer part and drops the decimal part, so for example:
> 
> ```python
> >>> int(3.14)
> 3
> ```
> 
> But in fact, we could even do this better by enforcing the integer constraint in the frontend. If the component is `Number(dtype="int")`, we prevent users from typing in the decimal point "." in the same way we prevent them from typing in letters right now.
> 
> Opening this issue because even though we might not implement it immediately, it's a reasonable request and one we might consider down the road.

**Comment by freddyaboulton** [comment]
Took a crack at it here: https://github.com/gradio-app/gradio/pull/1125
