### ISSUE TITLE
Use the `HF_TOKEN` env variable for `hf_token` of `gr.load`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#10074]
- [x] I have searched to see if a similar issue already exists.

Functions in the `huggingface_hub` library automatically uses `HF_TOKEN` for `token` when `token` is not specified and the environment variable exists, so I think it would be useful if the `hf_token` parameter in `gr.load` behaved in the same way.

**Comment by danigarciaoca** [comment]
Hi! I was trying to load my private repo by setting HF_TOKEN env and gr.load(), but it seems that it is not properly reading it. However, when hardcoding in hf_token argument it works. Any idea?

Many thanks!

python 3.10
gradio==5.24.0
gradio_client==1.8.0

**Comment by abidlabs** [comment]
Hi @danigarciaoca this is intentional for seucrity reasons, please see the docstring: https://www.gradio.app/docs/gradio/load#param-load-token

**Comment by danigarciaoca** [comment]
Thanks! I read the docs but I didn't get to understand: if the token is generated by the owner of the private repo (trusted or not), and you have to enter the token to be able to use this private repo, what's the security leak?

I mean, the doc says: "...as the token can be read by the Space you are loading"
 - No prob, no? the space I'm loading is the one that generated the token to access to it, so it is well-know for the Space itself

Maybe I'm missing something, but if I want:
- to access a private Space that is mine, I have to generate the HF_TOKEN that allows accessing it, so I generated the token and I already know it
- to access a private Space not owned by me, I have to previously know the HF_TOKEN that allows accessing to it, so I have the token and I already know it

So what's the possible leak?
