### ISSUE TITLE
Ability to resize input/output boxes 

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#101]
As requested by @BhavanJ, can we get more flexibility in the UI CSS? Mainly, can we enable control of the input/output sizing (width/height)? Sometimes images end up too small on the UI and are harder to see, so we can start with just the image component

**Comment by aliabid94** [comment]
You can now pass in any custom css (either as a file path or raw css) with the css= argument to the Interface object. See docs for more details.
