### ISSUE TITLE
Allow multiple example images to be displayed in the chatbot component

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#10106]
- [x] I have searched to see if a similar issue already exists.

When running the following code,
```py
import gradio as gr


def run(message, history):
    return "aaa"


demo = gr.ChatInterface(
    fn=run,
    examples=[
        [
            {
                "text": "Describe the imags.",
                "files": ["cats.jpg", "dogs.jpg"],
            },
        ],
    ],
    multimodal=True,
    type="messages",
    cache_examples=False,
)
demo.launch()
```
it's rendered like this but this is not desirable as users can't check the example images.
![](https://github.com/user-attachments/assets/e12b1927-e61c-4941-958d-2b3cbb86b7ec)

It seems that multiple images can be rendered when there's `additional_inputs` like this:
![](https://github.com/user-attachments/assets/8d52b86d-3f2d-4da6-85bc-93848f91e1c5)
```py
import gradio as gr


def run(message, history, temperature):
    return "aaa"


demo = gr.ChatInterface(
    fn=run,
    additional_inputs=[gr.Slider(minimum=0, maximum=2, step=0.1, value=0.7)],
    examples=[
        [
            {
                "text": "Describe the images.",
                "files": ["cats.jpg", "dogs.jpg"],
            },
            0.7,
        ],
    ],
    multimodal=True,
    type="messages",
    cache_examples=False,
)
demo.launch()
```

So I think it would be nice to be able to display multiple example images in the chat component as well.

If it's not possible for some reason, maybe it would be useful if there's an option to show examples at the bottom even when there's no `additional_inputs`.

**Comment by abidlabs** [comment]
Supported in 5.9.0!
