### ISSUE TITLE
[Regression] gr.Examples not working with image paths

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#10118]
### Describe the bug

On the latest Gradio (5.7.1), `gr.Examples` do not cache examples properly, at least in the context of the outputs being image paths.

The first image cached becomes the output of the results no matter what. Here is a minimal repro:
https://huggingface.co/spaces/multimodalart/repro-examples-single-file

```py
import gradio as gr

def generate(number):
    return f"{number}.png"

with gr.Blocks() as demo:
    slider = gr.Slider(minimum=1, maximum=3, value=1)
    button = gr.Button()
    image = gr.Image()
    examples = gr.Examples(
        examples=[[1], [2], [3]],
        inputs=[slider],
        outputs=image,
        fn=generate,
        cache_examples="lazy"
    )
    
demo.launch(ssr_mode=False)
```

If you click the examples the first time (when it's caching lazy) it works. But if you click it again for the 2nd time (once it's cached), all 3 examples will display the same output. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

```shell
gradio==5.7.1
```

### Severity

I can work around it

**Comment by apolinario** [comment]
I didn't trace exactly when the issue has started but on `5.5.0` it does not happen

**Comment by abidlabs** [comment]
Hmm I'll take a look thatnks @apolinario!
