### ISSUE TITLE
Configurable `print_exc` in `gr.Error`

### ISSUE THREAD

**Issue by cbensimon** [gradio-app/gradio#10136]
This would allow not printing stack traces for "expected" errors (while still using `gr.Error` in order to nicely display the error message in the UI). For instance in ZeroGPU, Spaces logs are full of "quota exceeded" stack traces that bring a lot of noise to the logs.

Example usage: `raise gr.Error("my error message", print_exc=False)` ==> won't print the exception in the logs

Relevant codebase pointer: https://github.com/gradio-app/gradio/blob/4984e847fa2575f9fb209c6b1b73a9003e79e564/gradio/routes.py#L1001

**Comment by abidlabs** [comment]
Makes sense. @cbensimon do you want to open a PR for this?

**Comment by obendidi** [comment]
+1, interested in this too, our logs get spammed with expected gradio errors

I can make a PR

**Comment by arnauddelaunay** [comment]
+1, would love to have this configuration available :pray:
