### ISSUE TITLE
@spaces.GPU will not load model

### ISSUE THREAD

**Issue by shorecodeorg** [gradio-app/gradio#10148]
### Describe the bug

After the 5.8.0 release, I can no longer load a model using gradio with zero gpu.

I have isolated the problem to likely be caused by the @spaces.GPU decorator, as the model will load without the decorator, although running on CPU.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

@spaces.GPU(duration=120)
def run_train(dataset_name, hub_id, api_key, num_epochs, batch_size, lr, grad):
    model = AutoModelForSeq2SeqLM.from_pretrained('google/t5-efficient-tiny-nh8', num_labels=2)
    #result = fine_tune_model(model, dataset_name, hub_id, api_key, num_epochs, batch_size, lr, grad)
    return result

try:    
    iface = gr.Interface(
        fn=run_train,
        inputs=[
            gr.Textbox(label="Dataset Name (e.g., 'imdb')"),
            gr.Textbox(label="HF hub to push to after training"),
            gr.Textbox(label="HF API token"),
            gr.Slider(minimum=1, maximum=10, value=3, label="Number of Epochs", step=1),
            gr.Slider(minimum=1, maximum=2000, value=1, label="Batch Size", step=1),
            gr.Slider(minimum=1, maximum=1000, value=1, label="Learning Rate (e-5)", step=1),
            gr.Slider(minimum=1, maximum=100, value=1, label="Gradient accumulation", step=1), 
        ],
        outputs="text",
        title="Fine-Tune Hugging Face Model",
        description="This interface allows you to fine-tune a Hugging Face model on a specified dataset."
    )
    '''
    iface = gr.Interface(
        fn=predict,
        inputs=[
            gr.Textbox(label="Query"),
        ],
        outputs="text",
        title="Fine-Tune Hugging Face Model",
        description="This interface allows you to test a fine-tune Hugging Face model."
    )
    '''
    # Launch the interface
    iface.launch()    

### Logs

```shell
An error occurred: Can't load the model for 'google/t5-efficient-tiny-nh8'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'google/t5-efficient-tiny-nh8' is the correct path to a directory containing a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack., TB: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3897, in from_pretrained
    ).start()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 118, in start
    assert not _current_process._config.get('daemon'), \
AssertionError: daemonic processes are not allowed to have children

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/app/app.py", line 17, in fine_tune_model
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name.strip(), num_labels=2)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3941, in from_pretrained
    raise EnvironmentError(
OSError: Can't load the model for 'google/t5-efficient-tiny-nh8'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'google/t5-efficient-tiny-nh8' is the correct path to a directory containing a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.
```

### System Info

```shell
Gradio 5.8.0
Gradio 5.7.1
Gradio 5.7.0
Gradio 5.0.1


All versions above have the same issue.
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @shorecodeorg can you please provided a correctly formatted code snippet or a link to a Space we can use to reproduce the issue?

**Comment by shorecodeorg** [comment]
https://huggingface.co/spaces/shorecode/gradio-3?logs=container

`import spaces
import gradio as gr
from transformers import Trainer, TrainingArguments, AutoTokenizer, AutoModelForSeq2SeqLM
from transformers import DataCollatorForSeq2Seq
from datasets import load_dataset, concatenate_datasets, load_from_disk
import traceback


import os
from huggingface_hub import login

@spaces.GPU
def fine_tune_model(model_name, dataset_name, hub_id, api_key, num_epochs, batch_size, lr, grad):
    try:
        #login(api_key.strip())
        # Load the model and tokenizer
        model = AutoModelForSeq2SeqLM.from_pretrained(model_name.strip(), num_labels=2)
        
    
        # Set training arguments
        training_args = TrainingArguments(
            output_dir='/data/results',
            eval_strategy="steps",  # Change this to steps
            save_strategy='steps',
            learning_rate=lr*0.00001,
            per_device_train_batch_size=int(batch_size),
            per_device_eval_batch_size=int(batch_size), 
            num_train_epochs=int(num_epochs),
            weight_decay=0.01,
            gradient_accumulation_steps=int(grad),
            max_grad_norm = 1.0, 
            load_best_model_at_end=True,
            metric_for_best_model="accuracy",
            greater_is_better=True,
            logging_dir='/data/logs',
            logging_steps=10,
            #push_to_hub=True,
            hub_model_id=hub_id.strip(),
            fp16=True,
            #lr_scheduler_type='cosine',
            save_steps=100,  # Save checkpoint every 500 steps
            save_total_limit=3, 
        )
        # Check if a checkpoint exists and load it
        max_length = 128
        # Load the dataset
        dataset = load_dataset(dataset_name.strip())
        tokenizer = AutoTokenizer.from_pretrained(model_name)
        # Tokenize the dataset
        def tokenize_function(examples):
            
            # Assuming 'text' is the input and 'target' is the expected output
            model_inputs = tokenizer(
                examples['text'], 
                max_length=max_length,  # Set to None for dynamic padding
                padding=True,     # Disable padding here, we will handle it later
                truncation=True,
            )
        
            # Setup the decoder input IDs (shifted right)
            labels = tokenizer(
                examples['target'], 
                max_length=max_length,  # Set to None for dynamic padding
                padding=True,     # Disable padding here, we will handle it later
                truncation=True,
                text_target=examples['target']  # Use text_target for target text
            )
        
            # Add labels to the model inputs
            model_inputs["labels"] = labels["input_ids"]
        
        
        tokenized_datasets = dataset.map(tokenize_function, batched=True)
        
        tokenized_datasets['train'].save_to_disk(f'/data/{hub_id.strip()}_train_dataset')
        tokenized_datasets['test'].save_to_disk(f'/data/{hub_id.strip()}_test_dataset')
    
        # Create Trainer
        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=tokenized_datasets['train'],
            eval_dataset=tokenized_datasets['test'],
            compute_metrics=compute_metrics,
            #callbacks=[LoggingCallback()], 
        )            

        # Fine-tune the model
        trainer.train()
        trainer.push_to_hub(commit_message="Training complete!")
    except Exception as e:
        return f"An error occurred: {str(e)}, TB: {traceback.format_exc()}"
    return 'DONE!'#model
'''
# Define Gradio interface
def predict(text):
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name.strip(), num_labels=2)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True)
    outputs = model(inputs)
    predictions = outputs.logits.argmax(dim=-1)
    return predictions.item()
'''
# Create Gradio interface
try:
    iface = gr.Interface(
        fn=fine_tune_model,
        inputs=[
            gr.Textbox(label="Model Name (e.g., 'google/t5-efficient-tiny-nh8')"),
            gr.Textbox(label="Dataset Name (e.g., 'imdb')"),
            gr.Textbox(label="HF hub to push to after training"),
            gr.Textbox(label="HF API token"),
            gr.Slider(minimum=1, maximum=10, value=3, label="Number of Epochs", step=1),
            gr.Slider(minimum=1, maximum=2000, value=1, label="Batch Size", step=1),
            gr.Slider(minimum=1, maximum=1000, value=1, label="Learning Rate (e-5)", step=1),
            gr.Slider(minimum=1, maximum=100, value=1, label="Gradient accumulation", step=1), 
        ],
        outputs="text",
        title="Fine-Tune Hugging Face Model",
        description="This interface allows you to fine-tune a Hugging Face model on a specified dataset."
    )
    '''
    iface = gr.Interface(
        fn=predict,
        inputs=[
            gr.Textbox(label="Query"),
        ],
        outputs="text",
        title="Fine-Tune Hugging Face Model",
        description="This interface allows you to test a fine-tune Hugging Face model."
    )
    '''
    # Launch the interface
    iface.launch()    
except Exception as e:
    print(f"An error occurred: {str(e)}, TB: {traceback.format_exc()}")`

**Comment by abidlabs** [comment]
cc @cbensimon @hysts for visibility

**Comment by abidlabs** [comment]
We took a brief look @shorecodeorg and our hunch is that this has to do with the training run, not loading the model. Loading the model works, even with the spaces decorator. Can you try removing the code related to training and see if that works for you? A more minimal repro would be helpful in isolating the issue.

**Comment by shorecodeorg** [comment]
My apologies, I gave the wrong URL

https://huggingface.co/spaces/shorecode/gradio-2

**Comment by shorecodeorg** [comment]
I have found a workaround, by loading a model config first, then by initializing the model using the config instead of the actual model repo (model = AutoModelForSeq2SeqLM.from_config(config))

https://huggingface.co/spaces/shorecode/gradio-3

**Comment by abidlabs** [comment]
Ok I'll go ahead and close this issue (as I don't think its gradio-related anyways) but let me cc @cbensimon and @hysts for visibility.
