### ISSUE TITLE
Feature request: `Code` component

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#1014]
An idea for a new `Code` Component, which supports:
* editable code (for inputs) or displayed code (for outputs)
* simple syntax highlighting for various common languages

Inspired by:
* https://huggingface.co/spaces/facebook/incoder-demo

![image](https://user-images.githubusercontent.com/1778297/163870230-ecbb8e74-2cc9-4f6d-ab36-b30228b7e670.png)

**Comment by abidlabs** [comment]
It would be really cool if something like this could be a community-contributed component. 

@pngwn I think we should invest some time writing up a tutorial on how to create components in Svelte + Python and submit them to the `gradio` library.

**Comment by Muhtasham** [comment]
Would be also great to have this for Blocks API, sth like gr.Code() or even gr.Textbox( ... style="code") , to make this input/output pairs bettter 

![Screenshot 2022-05-31 at 01 28 31](https://user-images.githubusercontent.com/20128202/171067890-1bab4a64-9bcc-460f-b8d6-3c8ca5427e19.png)

**Comment by julien-c** [comment]
On the hf.co Hub side we are investigating into migrating our Web editor to Codemirror, maybe this could be tackled at the same time
