### ISSUE TITLE
autofocus in multimodal chatbot takes focus away from textbox in additional_inputs

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#10144]
### Describe the bug

When `multimodal=True` is set, when I try to type something in the textbox in `additional_inputs` of `gr.ChatInterface`, the focus shifts to the main textbox right after pressing the first key. This doesn't happen with `multimodal=False`.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://huggingface.co/spaces/hysts-debug/multimodal-chat-autofocus
```python
import gradio as gr


def fn(message, history, system_prompt):
    return message


gr.ChatInterface(fn=fn, additional_inputs=[gr.Textbox()], multimodal=True).launch()
```

### Screenshot

https://github.com/user-attachments/assets/dee72406-0963-4f57-868a-09f9e9785acb

### System Info

```shell
gradio==5.8.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Looks like this is a problem with the autofocus parameter in `gr.MultimodalTextbox`, a simpler repro:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.MultimodalTextbox(autofocus=True, interactive=True)
    gr.Textbox()

demo.launch()
```

@dawoodkhan82 can you take a look?
