### ISSUE TITLE
image.no_webcam_support

### ISSUE THREAD

**Issue by geekplusaa** [gradio-app/gradio#10143]
### Describe the bug

input_image = gr.Image(type='pil', label='图像', sources=['webcam'], interactive=True, show_fullscreen_button=True)
这个代码部署在192.168.0.3服务器上面，我在192.168.0.5服务器访问项目 192.168.0.3:5019,然后点击摄像头报错image.no_webcam_support，这是为什么？该怎么修改

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```
input_image = gr.Image(type='pil', label='图像', sources=['webcam'], interactive=True, show_fullscreen_button=True)

### Screenshot

input_image = gr.Image(type='pil', label='图像', sources=['webcam'], interactive=True, show_fullscreen_button=True)

### Logs

```shell
input_image = gr.Image(type='pil', label='图像', sources=['webcam'], interactive=True, show_fullscreen_button=True)
```

### System Info

```shell
input_image = gr.Image(type='pil', label='图像', sources=['webcam'], interactive=True, show_fullscreen_button=True)
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @geekplusaa I'm closing this as this issue does not provide an English description nor a minimal standalone code repro. I can reopen if both are provided.
