### ISSUE TITLE
False positive: UserWarning: The value passed into gr.Dropdown() is not in the list of choices

### ISSUE THREAD

**Issue by JackismyShephard** [gradio-app/gradio#10152]
### Describe the bug

I have an event listener function which updates the choices of a dropdown component and sets its value to be one of the new valid choices, all in one return statement like this:

```python
new_choices = ...
return gr.Dropdown(choices = new_choices, value = new_choices[0])
```

 I am getting a false positive: `UserWarning: The value passed into gr.Dropdown() is not in the list of choices` in this case.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
new_choices = ...
return gr.Dropdown(choices = new_choices, value = new_choices[0])
```

### System Info

```shell
Windows 11
python 3.12
gradio 5.7.1
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Can you please provide a minimal code example for us to repro?

**Comment by abidlabs** [comment]
Going to close until we have a minimal repro

**Comment by JackismyShephard** [comment]
@abidlabs I might just add a repro later. Its not the biggest issue though so not a top priority for me 😄
