### ISSUE TITLE
gr.BrowserState first variable entry is not value, its default_value

### ISSUE THREAD

**Issue by robwsinnott** [gradio-app/gradio#10160]
### Describe the bug

One cannot replace gr.State with gr.BrowserState because assigning "value" causes an error, and the first entry is default_value.  This causes multiple headaches in replacing one with the other.  Having "default_value" be the first input also breaks the standard for of all other components.  

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

This doesn't work.  

```python
import gradio as gr
local_storage=gr.BrowserState(value="my Thing") 

```

### Screenshot

not relevant. 

### Logs

```shell
running gradio 5.8.0,
```

### System Info

```shell
running on Mac M2, 

Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 5.8.0
gradio_client version: 1.5.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 22.1.0
anyio: 3.7.1
audioop-lts is not installed.
fastapi: 0.115.6
ffmpy: 0.3.2
gradio-client==1.5.1 is not installed.
httpx: 0.27.0
huggingface-hub: 0.25.2
jinja2: 3.1.2
markupsafe: 2.0.1
numpy: 1.26.4
orjson: 3.10.5
packaging: 23.2
pandas: 2.2.3
pillow: 10.4.0
pydantic: 2.7.4
pydub: 0.25.1
python-multipart: 0.0.19
pyyaml: 6.0
ruff: 0.5.0
safehttpx: 0.1.6
semantic-version: 2.10.0
starlette: 0.41.3
tomlkit: 0.12.0
typer: 0.12.5
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.30.5
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.27.0
huggingface-hub: 0.25.2
packaging: 23.2
typing-extensions: 4.12.2
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @robwsinnott I'm not sure I understand the issue here. Is it just the name of the parameter is different between `gr.State` and `gr.BrowserState`? I don't think we'll make the change (for backwards-compatibility reasons) unless there's an actual bug here.
