### ISSUE TITLE
Is there a way to run gradio with python 3.6?

### ISSUE THREAD

**Issue by hn2** [gradio-app/gradio#1016]
I am usingp ython 3.6 for other applications. Is there a way to run gradio with this version?
Right now I am getting:
SyntaxError: future feature annotations is not defined
when trying to:
import gradio as gr

**Comment by abidlabs** [comment]
Nope unfortunately not as far as I know. We extensively use features that are only available in Python 3.7+

**Comment by simon-mo** [comment]
I just ran into this as well. Would it make sense to make it no longer pip installable? Ideally, we can add `python_requires` in `setup.py` to avoid pip installation.

https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires

Happy to send a PR, please lmk if this is the right approach from your point of view.

**Comment by abidlabs** [comment]
That sounds perfect @simon-mo and a PR would be much appreciated.
