### ISSUE TITLE
External networks are unable to connect to the Gradio application shared from my MacOS

### ISSUE THREAD

**Issue by shushuzhong** [gradio-app/gradio#10176]
### Describe the bug

When I launch a Gradio application on my Mac system using demo.launch(server_name='0.0.0.0', server_port=8899), it can only be accessed within the local network (LAN).  External networks are unable to connect to the application, even though the server is configured to bind to all interfaces (0.0.0.0). I do not encounter this issue when running the same Gradio application on a Windows system with identical configurations.

Steps to reproduce:

Launch the Gradio app on a Mac system with the above configuration.
Try accessing the app from an external network using the IP and port (e.g., http://<my_ip>:8899).
Observe that the connection fails.
Expected behavior: The Gradio application should be accessible from external networks when properly configured.

Additional details:

MacOS version: MacOS Sonoma 14.5
Gradio version: 5.3.0
Python version: 3.12

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
demo.launch(server_name='0.0.0.0', server_port=8899)

```

### Screenshot

![External networks](https://github.com/user-attachments/assets/8df8989a-ed0a-474c-922e-6ced88fbbb3c)
![LAN](https://github.com/user-attachments/assets/00f1cfbc-ab83-4754-a364-e049c6fc7114)

### Logs

```shell
/opt/miniconda3/bin/python3.12 /Users/zrf/Desktop/comment/cm_webui.py 
0
* Running on local URL:  http://0.0.0.0:8899

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
MacOS version: MacOS Sonoma 14.5
Gradio version: 5.3.0
Python version: 3.12
```

### Severity

Blocking usage of gradio

**Comment by shushuzhong** [comment]
Thankx. I've figured it out today. It indeed has nothing to do with the system. A combination of a public network IP and a port is required to enable access from external networks.

**Comment by tggagne** [comment]
@shushuzhong  wrote 
"A combination of a public network IP and a port is required to enable access from external networks."

So does that mean `launch(server_name='0.0.0.0', server_port=8899)` worked as is?

On my RHEL 10, a server running on 9090 is accessible on our network, but it's netstat looks like...
```
$ ss -tunlp | grep -E '9090|7860'
tcp   LISTEN 0      2048         0.0.0.0:7860       0.0.0.0:*    users:(("python3",pid=63958,fd=8))
tcp   LISTEN 0      4096               *:9090             *:*  
```
I can see the other listner shows *:9090 rather than gradio's 0.0.0.0:7860

So what did you change?
