### ISSUE TITLE
New event to trigger when a tab is in view, not necessarily explicitly selected by the user

### ISSUE THREAD

**Issue by anirbanbasu** [gradio-app/gradio#10177]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
While `gr.Tab` as the `select` event, it is only triggered when a user explicitly _selects_ the tab. What if the tab is selected by default and the user only has to select that tab in order to return to that tab after navigating away from it? Another event, such as `focus` or `default_selected` will be a good idea.

**Describe the solution you'd like**  
Support a new event for tabs that is triggered when the tab is in view, not necessarily because the user selected it.

**Additional context**  
To see what I mean, select the "Pydantic entity profiles" tab https://huggingface.co/spaces/anirbanbasu/gradio-experiments. By default, a sub-tab called "View (decorative)" is selected. However, this automatic selection does not trigger the `select` event on that tab. Thus the user will see something like this.

<img width="1975" alt="Screenshot 2024-12-11 at 16 27 26" src="https://github.com/user-attachments/assets/28ee7b8a-78a0-4a3b-ae65-1a7876ae8240">

Yet, if the user selects another sub-tab, e.g., "View (JSON)" and then selects "View (decorative)", the `select` event is triggered and the user gets to see something like the following.

<img width="1975" alt="Screenshot 2024-12-11 at 16 27 40" src="https://github.com/user-attachments/assets/f73fca00-fb11-452a-8334-f85c127110fa">

**Comment by abidlabs** [comment]
Thanks @anirbanbasu, I don't think we'll do this as events are meant to capture user interactions, not configuration states. Developers should handle initial component values by initializing the component's values appropriately not through events.

**Comment by anirbanbasu** [comment]
@abidlabs, thanks for your note. I understand your point about initial values but a tab can contain multiple visual elements, which is better initialised as a group with interdependencies between their initial values. Setting their initial values individually with checks for interdependencies can lead to very messy code.

Perhaps, the `load` event of `Blocks` is one place to trigger such initialisations? Although, for an visual interface with tabs, a single equivalent of the Javascript `onload` event will trigger unnecessary initialisations of elements that are not even visible, unless each such visibility (or tab selection) states are checked.

**Comment by anirbanbasu** [comment]
@abidlabs The following works, albeit the nested block inherits the theme from the main block, but should blocks be nested? I didn't add tabs to just focus on nested blocks.

See: https://www.gradio.app/playground?demo=Hello_World&code=aW1wb3J0IGdyYWRpbyBhcyBncgoKZGVmIHdlbGNvbWUobmFtZSk6CiAgICByZXR1cm4gZiJXZWxjb21lIHRvIEdyYWRpbywge25hbWV9ISBbVGhpcyBpcyBmcm9tIGluc2lkZSB0aGUgbWFpbiBibG9jay5dIgoKZGVmIG5lc3RlZF93ZWxjb21lKG5hbWUpOgogICAgcmV0dXJuIGYiV2VsY29tZSB0byBHcmFkaW8sIHtuYW1lfSEgW1RoaXMgaXMgZnJvbSBpbnNpZGUgdGhlIG5lc3RlZCBibG9jay5dIgoKd2l0aCBnci5CbG9ja3ModGhlbWU9Z3IudGhlbWVzLk1vbm9jaHJvbWUoKSkgYXMgZGVtbzoKICAgIGdyLk1hcmtkb3duKAogICAgIiIiCiAgICAjIEhlbGxvIFdvcmxkIQogICAgU3RhcnQgdHlwaW5nIGJlbG93IHRvIHNlZSB0aGUgb3V0cHV0LgogICAgIiIiKQogICAgaW5wX290aGVyID0gZ3IuVGV4dGJveChwbGFjZWhvbGRlcj0iVHlwZSBhIG1lc3NhZ2UuIikKICAgIHdpdGggZ3IuQmxvY2tzKHRoZW1lPWdyLnRoZW1lcy5PY2VhbigpKSBhcyBuZXN0ZWQ6CiAgICAgIHdpdGggZ3IuR3JvdXAoKToKICAgICAgICBnci5NYXJrZG93bigiV2UgYXJlIGluIGEgZ3JvdXAgaW4gYSBuZXN0ZWQgYmxvY2suIikKICAgICAgICBpbnAgPSBnci5UZXh0Ym94KHBsYWNlaG9sZGVyPSJXaGF0IGlzIHlvdXIgbmFtZT8iKQogICAgICAgIG91dCA9IGdyLlRleHRib3goKQogICAgICAgIGlucC5jaGFuZ2UobmVzdGVkX3dlbGNvbWUsIGlucCwgb3V0KQoKICAgIEBuZXN0ZWQubG9hZCgKICAgICAgb3V0cHV0cz1baW5wXQogICAgKQogICAgZGVmIG5lc3RlZF9ibG9ja19sb2FkKCk6CiAgICAgIHJldHVybiAiaW5pdGlhbCBoZWxsbyB3b3JsZCBtZXNzYWdlISIKICAgIGlucF9vdGhlci5jaGFuZ2Uod2VsY29tZSwgaW5wX290aGVyLCBvdXQpCgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgogICAgZGVtby5sYXVuY2goKQ%3D%3D&reqs=

```python
import gradio as gr

def welcome(name):
    return f"Welcome to Gradio, {name}! [This is from inside the main block.]"

def nested_welcome(name):
    return f"Welcome to Gradio, {name}! [This is from inside the nested block.]"

with gr.Blocks(theme=gr.themes.Monochrome()) as demo:
    gr.Markdown(
    """
    # Hello World!
    Start typing below to see the output.
    """)
    inp_other = gr.Textbox(placeholder="Type a message.")
    with gr.Blocks(theme=gr.themes.Ocean()) as nested:
      with gr.Group():
        gr.Markdown("We are in a group in a nested block.")
        inp = gr.Textbox(placeholder="What is your name?")
        out = gr.Textbox()
        inp.change(nested_welcome, inp, out)

    @nested.load(
      outputs=[inp]
    )
    def nested_block_load():
      return "initial hello world message!"
    inp_other.change(welcome, inp_other, out)

if __name__ == "__main__":
    demo.launch()
```

**Comment by abidlabs** [comment]
Blocks can be nested but any Blocks that are inside the main Blocks have their theme, custom css, etc. ignored.
