### ISSUE TITLE
How to use LinePlot to make the data displayed on the y-axis more detailed

### ISSUE THREAD

**Issue by CuteLuoXin** [gradio-app/gradio#10179]
### Describe the bug

![image](https://github.com/user-attachments/assets/eacb25db-0896-4ae0-a2d1-79fe0dfb4b94)
How to make the data displayed on the y-axis more detailed, and the height attribute does not seem to make the image elongated, only the white background elongated

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
  plot_spectra = gr.LinePlot(
      value=sp.get_spectra,
      x="波长",
      y="光强",
      color="光谱类型",
      y_lim=[0, 65535],
      color_map={"光源光谱": "red", "透射光谱": "green", "透暗光谱": "blue", "光暗光谱": "purple"},
      height=500,
      every=plot_timer
  )

```

### System Info

```shell
Neither the latest version of Gradio nor the previous version seems to work
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Going to close for now, but we can open with a proper repro
