### ISSUE TITLE
ValueError: Could not fetch api info for model

### ISSUE THREAD

**Issue by Pr0va1der** [gradio-app/gradio#10175]
### Describe the bug

I use the llamameta/Qwen2.5-Coder-32B-Instruct-Chat-Assistant model. Everything works when running in Kaggle, but as soon as I try to run the same code on my server (or my PC), an error pops up
```
Traceback (most recent call last):
  File "E:\repos\PycharmProjects\steamreviewai\main.py", line 21, in <module>
    client = Client("llamameta/Qwen2.5-Coder-32B-Instruct-Chat-Assistant")
  File "C:\Users\Pr0va1der\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio_client\client.py", line 171, in __init__
    self._info = self._get_api_info()
  File "C:\Users\Pr0va1der\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio_client\client.py", line 566, in _get_api_info
    raise ValueError(f"Could not fetch api info for {self.src}: {r.text}")
ValueError: Could not fetch api info for https://llamameta-qwen2-5-coder-32b-instruct-chat-assistant.hf.space: 

Process finished with exit code 1

```
Here is the code that is recommended to use on Hugging Face (I used it)

```
from gradio_client import Client

client = Client("llamameta/Qwen2.5-Coder-32B-Instruct-Chat-Assistant")
result = client.predict(
		message="Hello!!",
		system_message="You are Qwen, created by Alibaba Cloud. You are a helpful assistant.",
		max_tokens=18000,
		temperature=0.7,
		top_p=0.8,
		api_name="/chat"
)
print(result)
```
What is the problem? Maybe something is not installed on the device? I have installed all the pip packages that are required

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
from gradio_client import Client

client = Client("llamameta/Qwen2.5-Coder-32B-Instruct-Chat-Assistant")
result = client.predict(
		message="Hello!!",
		system_message="You are Qwen, created by Alibaba Cloud. You are a helpful assistant.",
		max_tokens=18000,
		temperature=0.7,
		top_p=0.8,
		api_name="/chat"
)
print(result)
```

### System Info

```shell
The latest version of the gradio-client from pip
python 3.10+
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @Pr0va1der I just ran your test code and it worked for me on my local device:

<img width="1177" alt="image" src="https://github.com/user-attachments/assets/2f121b0a-4a06-41a9-89a9-5b5ab21ca943" />

Could it be that your local PC is blocking network requests?

**Comment by Pr0va1der** [comment]
> Hi @Pr0va1der I just ran your test code and it worked for me on my local device:
> 
> <img width="1177" alt="image" src="https://github.com/user-attachments/assets/2f121b0a-4a06-41a9-89a9-5b5ab21ca943" />
> 
> Could it be that your local PC is blocking network requests?

I tried running the same code on my friend's server, and it magically worked. It also worked on the computer at my university, but it doesn't work on my PC and server. Perhaps it somehow depends on the hardware of the computer. 

My server does not block network requests, because the flask server and chatbots were successfully launched on this server.

**Comment by abidlabs** [comment]
That's very strange indeed. Can you try visiting this URL directly on your PC:

```
https://llamameta-qwen2-5-coder-32b-instruct-chat-assistant.hf.space
```

Does that load for you?

If there's anything else you can share that is unusual about your PC's setup, that would be helpful. Otherwise, we'll need to close this issue for lack of reproducibility.

**Comment by Pr0va1der** [comment]
@abidlabs Yes, the page is loading. I also checked the page loading and on my server, the page was available.

Yes, apparently I will close this issue, because I use another server on which everything works. Thanks for trying to solve my problem

**Comment by bulieme** [comment]
i have this same issue, i tried to load to https://huggingface.co/spaces/SmilingWolf/wd-tagger but got the same error:
![image](https://github.com/user-attachments/assets/0669b9fb-6aae-4e07-b33c-a7ae3bd540a5)

```python
Loaded as API: https://smilingwolf-wd-tagger.hf.space ✔
Traceback (most recent call last):
  File "C:\Users\MY\Desktop\files\test\test.py", line 3, in <module>
    client = Client("SmilingWolf/wd-tagger")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MY\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio_client\client.py", line 168, in __init__
    self._info = self._get_api_info()
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MY\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio_client\client.py", line 560, in _get_api_info
    raise ValueError(f"Could not fetch api info for {self.src}: {r.text}")
ValueError: Could not fetch api info for https://smilingwolf-wd-tagger.hf.space:
```

**Comment by Pr0va1der** [comment]
@bulieme The solution to the problem for me was to change the device. I have a hunch that it depends on the performance of the device, but I'm not sure (maybe it doesn't run on too weak computers). Try using Kaggle, or if you run it on the server, rent another machine

**Comment by QueryType** [comment]
> i have this same issue, i tried to load to https://huggingface.co/spaces/SmilingWolf/wd-tagger but got the same error: ![image](https://private-user-images.githubusercontent.com/53142287/396524350-0669b9fb-6aae-4e07-b33c-a7ae3bd540a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMDU4NjAsIm5iZiI6MTczNTAwNTU2MCwicGF0aCI6Ii81MzE0MjI4Ny8zOTY1MjQzNTAtMDY2OWI5ZmItNmFhZS00ZTA3LWIzM2MtYTdhZTNiZDU0MGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDAxNTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNjk4NTFkYzhkNTIzNmUxZTZmOGFjMzkxN2QyNGRkNDZmZmFiZjRiMjljOTYyNTU2NTBkN2U1NjY3ZGMyM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k5Oi_cUyIh8oqZGq7jbhzCrJgbEmbNrvpkKWn-jB3ns)
> 
> ```python
> Loaded as API: https://smilingwolf-wd-tagger.hf.space ✔
> Traceback (most recent call last):
>   File "C:\Users\MY\Desktop\files\test\test.py", line 3, in <module>
>     client = Client("SmilingWolf/wd-tagger")
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\MY\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio_client\client.py", line 168, in __init__
>     self._info = self._get_api_info()
>                  ^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\MY\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio_client\client.py", line 560, in _get_api_info
>     raise ValueError(f"Could not fetch api info for {self.src}: {r.text}")
> ValueError: Could not fetch api info for https://smilingwolf-wd-tagger.hf.space:
> ```
> 
> when i load it in my browser, https://smilingwolf-wd-tagger.hf.space/, it worked.. ![image](https://private-user-images.githubusercontent.com/53142287/396525102-60b81288-3009-4df6-8bcb-956d118e7f23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMDU4NjAsIm5iZiI6MTczNTAwNTU2MCwicGF0aCI6Ii81MzE0MjI4Ny8zOTY1MjUxMDItNjBiODEyODgtMzAwOS00ZGY2LThiY2ItOTU2ZDExOGU3ZjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDAxNTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZmEzMDQ3NWJjYzA2YjkwOTMwYzYzNGFlOWJkYjIyY2Y1MjJmYTYzMDdiZjM0ZTNkMWUzMGMwM2EzOTM2ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ViG2NMJDXzWgxDwu48IQaO9syGPSAqSSpctzxAsPQhM)

Same problem with me. Did you find a solution?

**Comment by QueryType** [comment]
Solved it! This happens when the app on the server is at a different gradio version than the gradio libraries on your local machine. I think, more so, between 4.x and 5.x versions. So you can either downgrade the version on either or upgrade. I upgraded on my local to latest 5.x ones and it worked.

**Comment by doschkinow** [comment]
I had the same issue, but after upgrading gradio on the client side to version 5.14.0, like the one used on the server ( I saw it in the build logs), it was resolved

**Comment by phucbienvan** [comment]
me too

**Comment by Moibe** [comment]
In my case it was the python version in the Dockerfile. To this date, the template from huggingface still has FROM python:3.9 but it no longer works with the latest gradio_client version (1.10.0), change Dockerfile to FROM python:3.13 fixed the problem.
