### ISSUE TITLE
Dropdown stops being clickable after 3.44

### ISSUE THREAD

**Issue by ysig** [gradio-app/gradio#10189]
### Describe the bug

Gradio components stops being clickable after version 3 (checked 4.44.1, 5.8.0). 
Not sure why but it's not the first time updates break things that worked in the past.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def print_name(message):
    return message

with gr.Blocks() as demo:
    message = gr.Dropdown(choices=['nyangi', 'neko'], label="Message")
    text = gr.Textbox()
    button.click(print_name, inputs=[message], outputs=[text])
    demo.launch(share=True)
```

### Logs

```shell
No error just not clickable... I'm opening it through a localhost proxy in vscode - should work/normally works.
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.44.1
gradio_client version: 1.3.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.2.0
fastapi: 0.115.6
ffmpy: 0.3.1
gradio-client==1.3.0 is not installed.
httpx: 0.26.0
huggingface-hub: 0.26.5
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.1
matplotlib: 3.8.2
numpy: 1.24.4
orjson: 3.9.13
packaging: 23.2
pandas: 2.1.4
pillow: 10.0.1
pydantic: 2.6.1
pydub: 0.25.1
python-multipart: 0.0.19
pyyaml: 6.0.1
ruff: 0.8.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.15.1
typing-extensions: 4.12.2
urllib3: 2.2.3
uvicorn: 0.27.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.26.0
huggingface-hub: 0.26.5
packaging: 23.2
typing-extensions: 4.12.2
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @ysig your code example is incomplete but a modified verison of your code:

```py
import gradio as gr

def print_name(message):
    return message

with gr.Blocks() as demo:
    message = gr.Dropdown(choices=['nyangi', 'neko'], label="Message")
    text = gr.Textbox()
    button = gr.Button()
    button.click(print_name, inputs=[message], outputs=[text])
    
demo.launch(share=True)
```

works fine for me:

https://github.com/user-attachments/assets/70dd6d39-aded-437c-9eb6-6285eabad1b8

**Comment by abidlabs** [comment]
Will close for now but can reopen with a suitable repro

**Comment by ysig** [comment]
Hi @abidlabs,

Thank you for your detailed and thoughtful response.

I now use your updated code. For exactly the same code:
- gradio-v3
https://github.com/user-attachments/assets/f0ba4302-d92a-44dc-9dcf-88a20322a767
(works perfectly)
- gradio-v4
https://github.com/user-attachments/assets/f3ad7f4d-8f69-470d-944e-ddb202603c06
(hangs)

Testing it on a PC will probably not look differently. It probably has to do with some security change that hangs when used through a server in my university. The point is to identify that and either setup something on my side so that later versions work or know what it is so I can talk with my security admin about it. 

Still it's strange that older versions work and newer not at all. It was a similar problem to shareable link that stopped working after 3.9/3.11 in proxyed servers.

P.S. of course I cannot create a reproduction of my university server.
