### ISSUE TITLE
The toolbar would be hidden in ImageMask, particularly with vertical images

### ISSUE THREAD

**Issue by ZhuLinsen** [gradio-app/gradio#10195]
### Describe the bug

The toolbar would be hidden when uploading a vertical diagram in ImageMask，Even in the latest version.

I have seen related issues below, but have not solve the issue.

https://github.com/gradio-app/gradio/issues/9305
https://github.com/gradio-app/gradio/pull/10037

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
    with gr.Row():
        image_mase = gr.ImageMask(
            label="Mask Image",
            type="pil",
            interactive=True,
            sources=["upload"],
            layers=False,
        )

demo.launch(
    server_name='0.0.0.0',
    server_port=65535,
)
```

### Screenshot

![image](https://github.com/user-attachments/assets/93395a12-a633-495b-a3f4-47c86fe0cbd7)

![image](https://github.com/user-attachments/assets/4a159044-4fab-4ce2-b410-c87ead1b69f1)
![image](https://github.com/user-attachments/assets/9011839a-0d44-48db-97a1-8715fcf59e22)

### System Info

```shell
I have tried different versions.

gradio                  5.8.0
gradio_client           1.5.1
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Thanks @ZhuLinsen I've reopened https://github.com/gradio-app/gradio/issues/9305, so let's use that issue to coordinate. Sorry about the inconvenience

cc @hannahblair @pngwn for visibility
