### ISSUE TITLE
在节点上使用 Gradio 报错 Connection errored out. 

### ISSUE THREAD

**Issue by renjie-liang** [gradio-app/gradio#10200]
### Describe the bug

我们学校的服务器使用 slrum管理集群，当我使用srun xxx --pty bash -i 申请一个GPU节点，在GPU节点里面运行gradio demo，能够显示界面，但是Connection Error.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def greet(name, intensity):
    return "Remote, " + name + "!" * int(intensity)
import gradio as gr

def greet(name):
    return f"Hello {name}!"

demo = gr.Interface(
    fn=greet,
    inputs=["text", "slider"],
    outputs=["text"],
)
demo.launch(share=True)

```

### Screenshot

<img width="626" alt="image" src="https://github.com/user-attachments/assets/9f2c0622-aa0e-4ecf-943a-d54fef4269c0" />

### System Info

```shell
gradio=5.8.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @renjie-liang we require all issues to be in English. From what I can tell, this issue has been reported before as well, so I'm going to close. Please take a look at existing closed issues and if none resolves the issue for you, please feel free to reopen the issue in English and provide a clear, step-by-step reproduction. Thanks!
