### ISSUE TITLE
Allow background image for gradio.inputs.Image source canvas

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#1020]
**Is your feature request related to a problem? Please describe.**
I would like to add a background-image to be drawn on top of with the canvas element

**Describe the solution you'd like**
I would want to be able to upload a picture and then draw on top of it for inpainting demos. This would return two elements: the uploaded image and the drawn mask.
![image](https://user-images.githubusercontent.com/788417/163977694-ed729288-c509-4efd-99e9-e18058fb6224.png)

**Additional context**
I am aware of the existence of `tool="editor"` however the canvas component is perfect for inpainting as is if only it was able to overlay the image. The editor enables way too many variables for a one dimensional inpainting endeavor and also doesn't return only a mask of edited things on top of the original image

**Comment by abidlabs** [comment]
This is now possible @apolinario, thanks to https://github.com/gradio-app/gradio/pull/1621! We'll release a new version to pypi soon, looking forward to your feedback!

Example code: https://github.com/gradio-app/gradio/blob/main/demo/blocks_mask/run.py
