### ISSUE TITLE
gr.Interface inputs/outputs type annoted for Sequence, but only list is supported

### ISSUE THREAD

**Issue by NiklasvonM** [gradio-app/gradio#10234]
### Describe the bug

The type annotation for the `inputs` and `outputs` parameters in `gr.Interface` is `str | Component | Sequence[str | Component] | None`. However, passing a non-list sequence such as a tuple results in a ValueError due to the `isinstance(inputs, (str, list, Component)` check.

I suggest replacing the `Sequence[str | Component]` type annotation with `list[str | Component]` or supporting other types of sequence.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

iface = gr.Interface(
    lambda x, y: "Hello World!", inputs=(gr.Textbox(), gr.Textbox()), outputs=gr.Textbox()
)
iface.launch()
```
Output: `TypeError: inputs must be a string, list, or Component, not (<gradio.components.textbox.Textbox object at ...>, <gradio.components.textbox.Textbox object at ...>)`

### System Info

```shell
Operating System: Windows
gradio version: 5.9.1    
gradio_client version: 1.5.2

------------------------------------------------
gradio dependencies in your environment:        

aiofiles: 23.2.1
anyio: 4.7.0
audioop-lts is not installed.
fastapi: 0.115.6
ffmpy: 0.5.0
gradio-client==1.5.2 is not installed.
httpx: 0.28.1
huggingface-hub: 0.27.0
jinja2: 3.1.4
markupsafe: 2.1.5
numpy: 2.2.0
orjson: 3.10.12
packaging: 24.2
pandas: 2.2.3
pillow: 11.0.0
pydantic: 2.10.4
pydub: 0.25.1
python-multipart: 0.0.20
pyyaml: 6.0.2
ruff: 0.8.4
safehttpx: 0.1.6
semantic-version: 2.10.0
starlette: 0.41.3
tomlkit: 0.13.2
typer: 0.15.1
typing-extensions: 4.12.2
urllib3: 2.2.3
uvicorn: 0.34.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.12.0
httpx: 0.28.1
huggingface-hub: 0.27.0
packaging: 24.2
typing-extensions: 4.12.2
websockets: 14.1
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks for pointing that out, @NiklasvonM. We need to use Sequence because it is a covariant type, which allows subclasses of Component to also be supported. This ensures flexibility in cases where custom component subclasses might be used. However, the current implementation's reliance on explicitly checking for list is inconsistent with this annotation. So we will change the check to use `Sequence` instead

**Comment by NiklasvonM** [comment]
I see, that makes sense. If you check for a `Sequence`, make sure that strings are not treated as sequences, even though a string is a `Sequence[str]`.
