### ISSUE TITLE
[Image] - Download button missing

### ISSUE THREAD

**Issue by elismasilva** [gradio-app/gradio#10230]
### Describe the bug

Guys, I noticed that the download button is not available in the image component, even when the "show_download_button" property is set to True. I don't know if the purpose of the download is to be available only in the gallery component, but since this property is in this component, I imagine it could be possible. In my use case, I'm generating a mask image that can be saved, so it's expected that only one image will be generated at a time. I'll work with the gallery component.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
with gr.Blocks() as app:   
    gallery = gr.Image(label="Image",  interactive=True, show_label=True, height=300, show_download_button=True, show_share_button=True)

app.launch(inbrowser=True)
```

### Screenshot

![image](https://github.com/user-attachments/assets/a68f0e38-2ccd-4b67-b452-86cd977fc643)

### Logs

```shell
N/A
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 5.9.1
gradio_client version: 1.5.2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.4.0
audioop-lts is not installed.
fastapi: 0.115.4
ffmpy: 0.4.0
gradio-client==1.5.2 is not installed.
httpx: 0.27.0
huggingface-hub: 0.25.2
jinja2: 3.1.3
markupsafe: 2.1.5
numpy: 1.26.3
orjson: 3.10.6
packaging: 24.1
pandas: 2.2.2
pillow: 11.0.0
pydantic: 2.8.2
pydub: 0.25.1
python-multipart: 0.0.19
pyyaml: 6.0.1
ruff: 0.5.6
safehttpx: 0.1.6
semantic-version: 2.10.0
starlette: 0.41.2
tomlkit: 0.12.0
typer: 0.12.3
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.30.5
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.27.0
huggingface-hub: 0.25.2
packaging: 24.1
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @elismasilva the download button is not shown when `interactive=True`. We'll update the docstring to reference that

**Comment by elismasilva** [comment]
Thank you, i did test and worked!

**Comment by elismasilva** [comment]
> Hi @elismasilva the download button is not shown when `interactive=True`. We'll update the docstring to reference that

but in docs you put " Only applies if interactive is True (e.g. if the component is used as an input)."  i think you want mean not True or interactive is False.

**Comment by abidlabs** [comment]
whoops thanks for the catch
