### ISSUE TITLE
Feature Request: Enhanced Chatbot Interface for Models with Reasoning Capabilities

### ISSUE THREAD

**Issue by AaronCoder** [gradio-app/gradio#10232]
- [x] I have searched to see if a similar issue already exists.
*Yes, there is no similar question here*

**Is your feature request related to a problem? Please describe.**

Currently, the `ChatbotInterface` component in Gradio primarily focuses on displaying the final output of language models. This is insufficient for models with reasoning capabilities like `gemini-2.0-flash-thinking-exp-1219`.  Currentlly, these models output both the reasoning process and the final answer in a single, undifferentiated text stream, making it difficult for users to quickly grasp the conclusion while still having access to the reasoning behind it.

**Describe the solution you'd like**

I propose enhancing the `ChatbotInterface` to support a structured display of models with reasoning capabilities. The key improvement is to display the reasoning process within a collapsible panel, similar to an `Accordion` panel. This allows users to focus on the final answer initially, but easily expand the panel to view the detailed reasoning steps when needed.

**Additional context**
Example using `gemini-2.0-flash-thinking-exp-1219

Imagine a user asks: "What is the capital of France?"

Current Display:

```
The user is asking for the capital city of France. I know this is a common piece of general knowledge. The answer is Paris.
Paris.
```

Proposed Enhanced Display (with reasoning shown, initially collapsed as an *accordion*):

```
Final Answer:
Paris.

[+ Show Reasoning]  (Clicking this expands the accordion panel below)

Reasoning:
1. The user is asking for the capital city of France. 
2. I know this is a common piece of general knowledge. 
3.  The answer is Paris.
```

This enhancement would significantly improve the usability of Gradio for showcasing and interacting with state-of-the-art language models, providing better explainability. I really hope the team can consider this and add support for mainstream reasoning models, thank you

**Comment by AaronCoder** [comment]
My bad，I can using metadata to show the reasoning steps

**Comment by freddyaboulton** [comment]
We're about to update the reasoning UI as well @AaronCoder ! See #10226

**Comment by AaronCoder** [comment]
Wow, thank you Freddy. I am particularly excited about the upcoming update to the reasoning UI. Nice job!
