### ISSUE TITLE
chatbot example not working?

### ISSUE THREAD

**Issue by HabermannR** [gradio-app/gradio#10244]
### Describe the bug

giving an example, and then clicking on it, should populate the chatbot, but nothing happens.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr
with gr.Blocks() as demo:
    chatbot = gr.Chatbot(examples=[{"text": "What is the capital of France?"}])
demo.launch()
```

### System Info

```shell
Gradio 5.9.1
Windows
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @HabermannR, you'll need to write a function to run when the `Chatbot`'s `.example_select()` event is triggered. If you're looking for an eaiser way to create a chat ui with Gradio, I'd recommend the `gr.ChatInterface` class: https://www.gradio.app/guides/creating-a-chatbot-fast

**Comment by HabermannR** [comment]
Thanks, was beginning to suspect something like that.

**Comment by HabermannR** [comment]
Do you mind changing the doc?
A list of example messages to display in the chatbot before any user/assistant messages are shown. Each example should be a dictionary with an optional "text" key representing the message that **should** be populated in the Chatbot when clicked
