### ISSUE TITLE
`ModuleNotFoundError: No module named 'gradio.test_data'` in colab notebook

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#1025]
### Describe the bug

I tested the latest version of the library (by releasing 2.9.0b from `main`) in colab and it throws this error:

```
[/usr/local/lib/python3.7/dist-packages/gradio/components.py](https://localhost:8080/#) in <module>()
     23 from gradio import processing_utils
     24 from gradio.blocks import Block
---> 25 from gradio.test_data import media_data
     26 
     27 

ModuleNotFoundError: No module named 'gradio.test_data'
```

### Reproduction

!pip install --quiet gradio==2.9.0b0

import gradio as gr

gr.Interface(lambda x:x, "textbox", "textbox").launch()

### System Info

```shell
2.9.0b
```

### Severity

blocker

**Comment by FarukOzderim** [comment]
Will investigate this issue further, it works perfectly fine when I import folder inside google colab.

https://user-images.githubusercontent.com/44067394/164151329-dcc1fdad-4d90-470e-8656-23caf99f2d1e.png

**Comment by FarukOzderim** [comment]
We could try importing test_data within __init__.
