### ISSUE TITLE
stop btn click event with cancels do NOT execute then

### ISSUE THREAD

**Issue by liaoweiguo** [gradio-app/gradio#10251]
### Describe the bug

I have a long RAG app, sometimes the llm loop output, I have a button to cancel, and then save the looped output, something like:

```python
        stop_btn.click(fn=None,inputs=None,cancels=[submit_event]).then(fn=store_chat,inputs=[chatbot])

```

but the store_chat never run

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
...

        stop_btn.click(fn=None,inputs=None,cancels=[submit_event, query_event]).then(fn=store_chat,inputs=[chatbot])
...
```

### System Info

```shell
macOS gradio 5.6.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @liaoweiguo would you kindly be able to try the latest version of Gradio (5.9.1)? If that doesn't work, can you please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by abidlabs** [comment]
Closing for now, but we can reopen if we have a standalone repro.
