### ISSUE TITLE
Freeze Panel

### ISSUE THREAD

**Issue by elismasilva** [gradio-app/gradio#10256]
Hi everyone, how are you? I would like to know if there is any way to create a frozen panel with some gradio component, similar to what we do in Excel, so that I can fix a section of components above and below as I scroll the main vertical scroll bar, the components below just scroll.

**Comment by abidlabs** [comment]
Hi @elismasilva this isn't supported natively in Gradio and is a bit too niche for us to add support via Python, but it should be possible to get this kind of effect with a little bit of custom CSS. Try something like this for example:

```py
import gradio as gr

css = """
.top-div {
    position: fixed;
    background-color: white;
    top: 0;
    left: 0;
    width: 100%;
    height: 250px;
    color: white;
    padding: 20px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.2);
    z-index: 1000;
}

.bottom-div {
    margin-top: 250px;
    padding: 20px;
    line-height: 1.6;
    font-family: Arial, sans-serif;
}
"""

with gr.Blocks(css=css) as demo:
    with gr.Row():
        with gr.Column(elem_classes="top-div"):
            gr.Textbox(label="Fixed 1")
            gr.Textbox(label="Fixed 2")
        with gr.Column(elem_classes="bottom-div"):
            gr.Textbox(label="Scrolling 1")
            gr.Textbox(label="Scrolling 2")
            gr.Textbox(label="Scrolling 3")
            gr.Textbox(label="Scrolling 4")
            gr.Textbox(label="Scrolling 5")
            gr.Textbox(label="Scrolling 6")
            gr.Textbox(label="Scrolling 7")
            gr.Textbox(label="Scrolling 8")
            gr.Textbox(label="Scrolling 9")
            gr.Textbox(label="Scrolling 10")
            

demo.launch()
```

**Comment by elismasilva** [comment]
Thanks! That's what I was looking for, but I think my interface is more complex than I thought, since I'm using Tabs and the content I want to freeze is inside the first tab_item. I tried applying the top-div to the main tab and the Process tab_item but it doesn't work because the scroll content is also inside the same tab. I think I'll need to make my own tab where I fix buttons at the top and control the visibility of elements.

Red is to be fixed, blue to scroll.
![image](https://github.com/user-attachments/assets/d45fa11a-6b57-43fc-a878-1359d12923e3)
