### ISSUE TITLE
Input and output `Image` components render image sizes differently

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#1031]
### Describe the bug

I built a simple `Interface` that takes an input image and simply returns it. However, I noticed that the input image component enforces a maximum height for the image component, whereas the output component does not seem to, leading to this strange-looking UI:

![image](https://user-images.githubusercontent.com/1778297/164074376-9ba38133-9fa4-4733-854f-73d83341cf3e.png)

### Reproduction

`gr.Interface(lambda x:x, "image", "image").launch()`

and pass in a tall image

### System Info

```shell
gradio==2.9.0b2
```

### Severity

annoyance

**Comment by abidlabs** [comment]
After some discussion with @AK391, not sure if this is as big of an issue as I thought it was. Users might actually prefer to have a nice large image output (they care more about that than the input image). 

What do you guys think @pngwn @gary149 @aliabid94?

Should we remove it from the 3.0 milestone?

**Comment by hpeiyan** [comment]
> I think it is okay that they are different but maybe we want to allow user to set a max-height? That is probably related to the CSS/ styling issues which we are still unpacking.

hey, do you know how to setting max-height in the lastest release? I'm confuse this difference.
