### ISSUE TITLE
Add button for download the output  generated image

### ISSUE THREAD

**Issue by kiashann** [gradio-app/gradio#1039]
Hi. How we can add button for download generated image output in app.py ? 
Is it possible with gr.outputs.File? How we can use that?
@BioGeek @julien-c

**Comment by abidlabs** [comment]
Hi @kiashann, thanks for asking the question. Yes, if you'd like for people to easily download the image file, I suggest passing the name of the file to gr.outputs.File, which will then create a downloadable link. This is how users typically create downloadable files, for example take a look here: https://huggingface.co/spaces/radames/dpt-depth-estimation-3d-obj

In terms of how the code would look, it would look like something like this:

```py
import gradio as gr

def your_function(input_text):  # I'm just assuming the input is text, it could be anything
  # implementation
  return img_file_path, img_file_path

gr.Interface(your_function, "text", ["image", "file"]).launch()
```

**Comment by abidlabs** [comment]
Feel free to ask follow up questions here, but closing as this does not look like an open issue, feel free to reopen if I'm wrong :)

**Comment by kiashann** [comment]
> Feel free to ask follow up questions here, but closing as this does not look like an open issue, feel free to reopen if I'm wrong :)

Thanks for you answer.
