### ISSUE TITLE
Block wrapper handling

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#1055]
~~Two~~Three main points here:

- [x] We are wrapping _almost_ every component with `Block` inside the component istelf. This is okay but there is a lot of repetition. It might be able to do this at the app level, when we render the components from the config. This would simplify the components a little but would require a little refactoring. One to investigate rather than implement blindly.
- [x] `Radio` and `CheckboxGroup` use a `fieldset` element as their wrapper rather than the `Block` component, because they are a collection of form elements that exist together. This results in some duplication of code/classes, however small, to get consistent styling. We could pass a prop to `Blocks` and use `svelte:element` to switch between a `div` and a `fieldset`.
- [ ] Related to the final point, the form components that use a fieldset should use a `legend` element for their 'title'/'label' for accessibility reasons.

**Comment by a8568730** [comment]
This issue seems completed and closed, but when I use gradio@5.49.0, the form components still use a span element for their 'title'/'label' , rather than legend element.  Does I misunderstand something?
