### ISSUE TITLE
Docs link does not work!

### ISSUE THREAD

**Issue by SamuelDevdas** [gradio-app/gradio#1061]
### Describe the bug

![gradio1](https://user-images.githubusercontent.com/84823680/164533666-ee0dba93-77cd-4356-b63a-9c6f200e0e01.PNG)
![gradio2](https://user-images.githubusercontent.com/84823680/164533774-11cf1863-9498-43de-b2c9-7210bac12780.PNG)

### Reproduction

https://github.com/gradio-app/gradio/blob/main/docs

### System Info

```shell
na
```

### Severity

critical

**Comment by abidlabs** [comment]
Thanks @SamuelDevdas. Ah yeah that's just a relative link / absolute link issue. We'll fix this as part of our revamp of docs. 

In the meantime, here's the link to the docs: https://gradio.app/docs

**Comment by SamuelDevdas** [comment]
Thanks! @abidlabs . Good Job!
