### ISSUE TITLE
Can I buy a public link for permanent hosting?

### ISSUE THREAD

**Issue by xishanhan** [gradio-app/gradio#1062]
Hi！Thanks for your wonderful work.
For some reason, my model can't be saved on huggingface, but I want a permanent public link like 'XXXXX.gradio.app', so can I buy it? I didn't find a place to buy it, so I'm asking here, looking forward to your reply.

**Comment by abidlabs** [comment]
Hi @xishanhan, unfortunately this is not something that we offer at this time. You can create both public and private Spaces for free on Hugging Face. 

If you are a company and need an on-premise version of Spaces, check out: https://huggingface.co/platform

**Comment by xishanhan** [comment]
Thanks for your reply!
