### ISSUE TITLE
UI doesn't render within Databricks notebook 

### ISSUE THREAD

**Issue by XinyuanHu** [gradio-app/gradio#1063]
### Describe the bug

When I run the most basic demo code: 

```
import gradio as gr


def greet(name):
    return "Hello " + name + "!!"


iface = gr.Interface(fn=greet, inputs="text", outputs="text")
iface.launch()
```

within Databricks environment, UI does not render, it shows "127.0.0.1 refused to connect."

It can render when it has share=True setting

not sure why local cannot display anything

### Reproduction

```
import gradio as gr


def greet(name):
    return "Hello " + name + "!!"


iface = gr.Interface(fn=greet, inputs="text", outputs="text")
iface.launch()
```

### Screenshot

<img width="933" alt="Screen Shot 2022-04-21 at 9 44 56 PM" src="https://user-images.githubusercontent.com/39036043/164580229-cf73e721-ef76-4fe0-99a4-fa0b1c675d41.png">

### System Info

```shell
V2.9.0
databricks community edition
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Hi @XinyuanHu,

Thanks for creating the issue. The problem seems to be that by default, Gradio runs your web app on localhost. Since Databricks notebooks are hosted on their servers, you cannot access the localhost directly. Thus, the web app is not visible to you. When you set `share=True`, it works because Gradio creates an SSH tunnel from their localhost to a public link allowing you to see the web app.

The same behavior actually happens in colab notebooks, but Gradio detects if it is running in a colab notebook and automatically sets `share=True` to solve this issue. We can do the same for Databricks notebooks.

**Comment by XinyuanHu** [comment]
Thanks for the quick turnaround! This makes sense. However, is there anyway to host the app privately? If ```share=True```is set, there might be security concerns.

**Comment by abidlabs** [comment]
Good questions @XinyuanHu. Because of how Databricks hosts notebooks, it's a little tricky. But there are two things you could try:

- Add authentication to your Gradio demo (by simply adding `auth=(username, password)` in the `launch()` function. This adds a layer of security to prevent unauthorized users from using the demo. See https://www.gradio.app/docs/#launch
- Only run locally, but use a different solution to create a public SSH tunnel (like ngrok) allowing you to view the demo on a different URL, if you feel that is more secure.

**Comment by miquelarisa** [comment]
When I run the most basic demo code in databricks:

````
import gradio as gr

def greet(name, intensity):
    return "Hello, " + name + "!" * int(intensity)


demo = gr.Interface(
    fn=greet,
    inputs=["text", "slider"],
    outputs=["text"],
)

demo.launch(share=True)
````

I recive the following message:
````
Running on local URL:  http://127.0.0.1:7861/

Could not create share link. Missing file: /local_disk0/.ephemeral_nfs/envs/pythonEnv-c217ea4c-1aaf-4281-acd8-1781670c57ec/lib/python3.10/site-packages/gradio/frpc_linux_amd64_v0.2. 

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps: 

1. Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
2. Rename the downloaded file to: frpc_linux_amd64_v0.2
3. Move the file to this location: /local_disk0/.ephemeral_nfs/envs/pythonEnv-c217ea4c-1aaf-4281-acd8-1781670c57ec/lib/python3.10/site-packages/gradio
````
And the app is not rendered.
![image](https://github.com/gradio-app/gradio/assets/97958627/026a1a0d-0e66-4677-b6f2-819a0d295cae)

I can't download the file mentioned and move it in this location. Which solution do I have?

**Comment by SagarBansal7** [comment]
@abidlabs I have followed similar steps as you mentioned above. I am working in Databricks environment and I have set share=True. However, I am getting the connection refused error. I am using a basic code as follows:

import gradio as gr
def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="textbox", outputs="textbox")
    
demo.launch(share=True)  

![image](https://github.com/gradio-app/gradio/assets/37155988/2438677b-3c20-442c-b680-698461558153)

**Comment by JUNNIEJUN** [comment]
> @abidlabs I have followed similar steps as you mentioned above. I am working in Databricks environment and I have set share=True. However, I am getting the connection refused error. I am using a basic code as follows:
> 
> import gradio as gr def greet(name): return "Hello " + name + "!"
> 
> demo = gr.Interface(fn=greet, inputs="textbox", outputs="textbox")
> 
> demo.launch(share=True)
> 
> ![image](https://private-user-images.githubusercontent.com/37155988/322542438-2438677b-3c20-442c-b680-698461558153.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjgzOTcsIm5iZiI6MTcxNTMyODA5NywicGF0aCI6Ii8zNzE1NTk4OC8zMjI1NDI0MzgtMjQzODY3N2ItM2MyMC00NDJjLWI2ODAtNjk4NDYxNTU4MTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA4MDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NzFhZDhhNzAzODFkYmZiNGQzMjRmNmU0ZjBkMGFlZWZmMmY0MzNhZDNkNTFjNjAxYzQ4YjA0NjgxNmU1M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LUnCu4UuKHa3jmLivWwgdHEUmmWVb54osOYUO-xJDQQ)

I have the totally the same problem. Did you solve it ?

**Comment by benhachy** [comment]
Hello,
Setting share=True did not resolve the issue for me. I also downloaded the frpc_linux_amd64 file, but the problem persists.
Are you aware of any solution ? 
Thanks

![image](https://github.com/user-attachments/assets/8a9e3bf3-2519-4c27-814b-0c085156358e)
