### ISSUE TITLE
[Blocks] Discrete Events or Actions

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1066]
Discrete Events or Actions that happen immediately within Frontend and do not communicate with Backend could improve UX. An example would be clearing the UI immediately with a Clear submit from user, without doing an API call to Backend.

Dropping some comments from a discussion with @pngwn below.

> I think pressing clear and waiting a few seconds would be a poor UX. But could wait in low priority as well.

> We would need to expand the architecture to allow the frontend to perform discreet actions that only affected the frontend but dictated by config. I think it might make sense to add something like that at some point but not a priority atm and needs some thought. 
> We would need to introduce a companion to trigger/ event callbacks that did not make an API request but could interact with state in some way. I think we'll need to revisit this post 3.0.

**Comment by abidlabs** [comment]
Closed via #1082
