### ISSUE TITLE
Add download link to video component

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1072]
### Describe the bug

Copy Video Link option on an output video component gives the video data as a very long string.

### Reproduction

Copy video link from an video output
![image](https://user-images.githubusercontent.com/44067394/164799734-5b10b707-d6ca-4e7f-8216-f3e67b0be4fd.png)

I used this space:
https://huggingface.co/spaces/ysharma/text-to-ner-to-image-to-video

### Screenshot

![image](https://user-images.githubusercontent.com/44067394/164799704-ba18c78e-93ad-45f5-be6f-54fc1c81b830.png)

### System Info

```shell
Hugging Face Spaces
```

### Severity

annoyance

**Comment by pngwn** [comment]
I don't think this is resolvable unless we either change how we handle generated video files (i.e. generate an actual file rather than a dataURI) or create a custom video player. I don't _think_ there is a way to over-ride the defaul behaviour of the download link (which will always down the source as it is). Can look into this more closely in the future.

**Comment by pngwn** [comment]
As a quicker fix, we could add a download link somewhere.

**Comment by abidlabs** [comment]
Renaming to reflect the proposed solution

**Comment by abidlabs** [comment]
We should also add a download link to the `Model3D component` so that people are able to download the file directly (right now, a lot of people use a separate File Component to do this)

**Comment by abidlabs** [comment]
> Copy Video Link option on an output video component gives the video data as a very long string.

Now that we've switched to serving files, this is no longer an issue so I'm closing this. 

> We should also add a download link to the Model3D component so that people are able to download the file directly (right now, a lot of people use a separate File Component to do this)

This has also been added, thanks @dawoodkhan82!
