### ISSUE TITLE
Enable multi-select on gradio.Dropdown

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#1076]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to have plenty of multi-select options and I also don't want to clutter the UI with a lot of checkboxes using `gr.inputs.CheckboxGroup` 

**Describe the solution you'd like**
Enabling a multi-select option on the `gradio.inputs.Dropdown` component can be an elegant way to keep multi-option selection concise but yet powerful and functional
<img width="727" alt="image" src="https://user-images.githubusercontent.com/788417/165058185-652d2d85-6c54-4dc9-884b-74962728531a.png">
Example implementation of such a feature

**Comment by abidlabs** [comment]
Great suggestion, thanks @apolinario!

**Comment by colelandolt33** [comment]
Hi @abidlabs , has there been any progress on implementing this feature?

**Comment by abidlabs** [comment]
Not yet! @dawoodkhan82 is this something you can take on? 

@colelandolt33 can you tell us a little more about your use case so that we can make sure that it is supported by our implementation of this feature?

**Comment by colelandolt33** [comment]
> @colelandolt33 can you tell us a little more about your use case so that we can make sure that it is supported by our implementation of this feature?

I'm working on an application where the user inputs a dataset and selects columns to be used in an analysis. Currently the only way to allow the user to select multiple columns is by using `gr.CheckboxGroup`, but when there are hundreds of columns, this isn't very user friendly. I'm looking for a dropdown menu where the user can make multiple selections, very similar to this [Streamlit widget](https://doc-multiselect.streamlitapp.com/). Ideally, the user could type to search for options.

**Comment by AmbiakaTT** [comment]
Any updates on the feature yet? It would be really really helpful for me. By the way, for a list of 100+ options, would using checkboxgroup be helpful

**Comment by abidlabs** [comment]
We haven't had a chance to look into this yet @AmbiakaTT. We'll update here when we have more to add

**Comment by wjizhong** [comment]
Any updates on the feature yet? It would be really really helpful for me. By the way, for a list of 100+ options, would using checkboxgroup be helpful

**Comment by abidlabs** [comment]
Hi @wjizhong not yet unfortunately. @aliabid94 or @dawoodkhan82 if you have the bandwidth to take a look at this next week, we're getting a lot of interest in this component.

**Comment by Ahanmr** [comment]
Hi, is this released in the latest version as such? I'd love to know since I'm interested in using the multi-input in dropdown function. Thank you!
