### ISSUE TITLE
allow_flagging="never" doesn't disable Flag Button

### ISSUE THREAD

**Issue by radames** [gradio-app/gradio#1086]
### Describe the bug

On version 2.9.0b8 `allow_flagging="never"` doesn't disable Flag button

### Reproduction

here is the simple test code

```python

import os
import requests
import gradio as gr


def classify_image(input):
  print(input)
  return ""

image = gr.Image()
label = gr.Image()

gr.Interface(
    fn=classify_image,
    inputs=image,
    outputs=label,
    allow_flagging="never",
    ).launch()

```

### Screenshot

<img width="843" alt="image" src="https://user-images.githubusercontent.com/102277/165190453-68d69f26-ba48-4311-9b4e-85e5ed3da456.png">

### System Info

```shell
Gradio==2.9.0b8
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Thanks @radames, will fix that soon!

**Comment by abidlabs** [comment]
Thanks @radames this fixed now, and the fix will be out as part of next beta release!
