### ISSUE TITLE
Article parameter not rendered on Interface beta 

### ISSUE THREAD

**Issue by radames** [gradio-app/gradio#1093]
### Describe the bug

I know with Blocks there's a different and better approach to build interactive and non-interactive elements (text, descriptions, etc). Are we going the be backwards compatible?  Right now working on `2.9.0b8` the property `article` is not rendered on the [`Interface Class`](https://github.com/gradio-app/gradio/blob/910db9959b478c620fbbee84112ec0f97d9655f5/gradio/interface.py#L511-L519)

### Reproduction

```python

input = gr.Image()
output = gr.Image()

gr.Interface(
    description="## Description",
    article="## Article",
    fn=classify_image,
    inputs=input,
    outputs=output,
    ).launch()

```

### System Info

```shell
Gradio 2.9.0b8
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Ahh it looks like we just missed this parameter when we were rewriting `Interface`. But no worries, it should be an easy fix. @aliabid94 would you be able to take a look?

**Comment by abidlabs** [comment]
Yes the goal is to be fully backwards compatible @radames!
