### ISSUE TITLE
search within dropdown choices 

### ISSUE THREAD

**Issue by chrisemezue** [gradio-app/gradio#1094]
**Is your feature request related to a problem? Please describe.**
I have a dropdown of 2000+ choices,  i do not think it will be wise making the user have to scroll through this whole list.  For example if a user has to choose from a list of countries.

**Describe the solution you'd like**
Using the list of countries example, as I press `N` I want the choices to be searched and the results starting with `N` (like Nigeria, Niger, Netherlands,...) to be displayed first.

**Comment by mazzma12** [comment]
Hi! it sounds really reasonable to me,  I also have the same request.

**Comment by abidlabs** [comment]
Closing in favor of https://github.com/gradio-app/gradio/issues/2970
