### ISSUE TITLE
F-string will cause syntax error under python 3.5

### ISSUE THREAD

**Issue by wtnan2003** [gradio-app/gradio#11]
https://github.com/gradio-app/gradio/blob/04e3036e6040e2545514bd5657dbc3e413c3f15b/gradio/interface.py#L194

**Comment by dawoodkhan82** [comment]
> https://github.com/gradio-app/gradio/blob/04e3036e6040e2545514bd5657dbc3e413c3f15b/gradio/interface.py#L194

Hey wtnan2003, I wanted to reach out to see if you would be willing to hop on a quick call with us. We wanted to talk to some users of Gradio-UI ad get your feedback.

**Comment by aliabd** [comment]
Thanks @wtnan2003 All f-strings are now compatible with Python 3 <3.5. Closing.
