### ISSUE TITLE
[blocks] unnested form components do not collapse

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#1103]
### Describe the bug

When form components are not nested in anything else they don't collapse as expected. This is because the adjacent form component detection is only run on children, not on top level components.

### Reproduction

```py
import gradio as gr

with gr.Blocks() as demo:
   txt = gr.Textbox()
   txt = gr.Textbox()
   num = gr.Number()
   check = gr.Checkbox()

demo.launch()
```

### Screenshot

Actual:
<img width="639" alt="Screenshot 2022-04-27 at 10 31 47" src="https://user-images.githubusercontent.com/12937446/165488493-cb465ad9-a3d2-4f7d-b876-d96f146bf287.png">

Expected:
<img width="639" alt="Screenshot 2022-04-27 at 10 33 23" src="https://user-images.githubusercontent.com/12937446/165488774-8a71df8c-e84a-4996-88b1-08e5d64321a3.png">

### System Info

```shell
`main`
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Looks like this is fixed now, thanks @pngwn!

![image](https://user-images.githubusercontent.com/1778297/178226423-afa09b1f-c5e3-41a7-8bc9-36f0fe05360e.png)
