### ISSUE TITLE
Accept async functions in `Interface`

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#1107]
Currently `gradio.Interface` takes in standard functions as part of the `fn` parameter. It would be helpful if it could also take in async functions (coroutines) for potential integrations with Ray Serve.

cc @dynamicwebpaige

**Comment by FarukOzderim** [comment]
This sound very good!
related, #727

**Comment by FarukOzderim** [comment]
lets continue this issue in 727

**Comment by abidlabs** [comment]
This is now in, fyi @dynamicwebpaige
