### ISSUE TITLE
Gradio blocks in Spaces and colab has duplicated first tab interface

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1114]
### Describe the bug

The interface of the first `TabItem` is duplicated 
![Screenshot from 2022-04-28 11-26-07](https://user-images.githubusercontent.com/7246357/165722084-d21ef38f-a72f-4112-abf9-3a8330dfd519.png)
 

### Reproduction

https://huggingface.co/spaces/osanseviero/tortoisse-tts

### System Info

```shell
Spaces
```

### Severity

critical

**Comment by abidlabs** [comment]
Should be fixed as well with `gradio==2.9b11`
