### ISSUE TITLE
Interfaces within block has Flag button

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1115]
### Describe the bug

I think Flagging is supposed to be disabled by default in spaces 
![Screenshot from 2022-04-28 11-26-07](https://user-images.githubusercontent.com/7246357/165722367-db10af1e-a795-4cd3-b7df-452fe4e830a7.png)

### Reproduction

https://huggingface.co/spaces/osanseviero/tortoisse-tts

### System Info

```shell
Spaces
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Should be fixed as well with `gradio==2.9b11`
