### ISSUE TITLE
GIF Recording is buggy after you strech Dataframe cant click stop button

### ISSUE THREAD

**Issue by MesumRaza** [gradio-app/gradio#113]
![image](https://user-images.githubusercontent.com/22402962/106257439-58aa9200-623e-11eb-8e84-219604726813.png)

**Comment by aliabid94** [comment]
Unable to reproduce. In the screenshot provided, the record button is still visible. Can you provide more detail?

**Comment by aliabid94** [comment]
Closing because unable to reproduce.
