### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'Interface'

### ISSUE THREAD

**Issue by sahuabinash** [gradio-app/gradio#1132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying the following in a Windows machine. Installed gradio using 'pip install gradio' to an environment and running the following code in Pycharm.

import gradio as gr
# from gradio import Interface

def greet(name):
    return "Hello " + name + "!!"

iface = gr.Interface(fn=greet,inputs="text",outputs="text")
iface.launch()

**Getting error** AttributeError: module 'gradio' has no attribute 'Interface'
I then tried the following and still getting error
# import gradio as gr
from gradio import Interface

def greet(name):
    return "Hello " + name + "!!"

iface = Interface(fn=greet,inputs="text",outputs="text")
iface.launch()

Error:
ImportError: cannot import name 'Interface' from 'gradio'

### Reproduction

import gradio as gr
# from gradio import Interface

def greet(name):
    return "Hello " + name + "!!"

iface = gr.Interface(fn=greet,inputs="text",outputs="text")
iface.launch()

### System Info

```shell
gradio: 2.9.4
Windows
```

### Severity

critical

**Comment by abidlabs** [comment]
This is usually caused by gradio not being installed correctly in the python environment.

Can you try `pip uninstall gradio` and then rerun `pip install gradio` and let us know if you are still seeing this?

Related: #613

**Comment by sahuabinash** [comment]
Hello. Thank you for looking into this issue. I re-installed, but that didn't solve. However, this is a new Python gotcha! My Python script name was - gradio.py. So when I was using import gradio as gr, it was importing but confusing with the file name. Changed the file name to gadio_learn.py and it works like a charm. Posting so that others don't waste time like I did....

**Comment by abidlabs** [comment]
Ah that makes sense, thank you for clarifying and adding the solution to the issue! Hopefully this will be helpful to anybody else who runs into the same problem

**Comment by madwichery** [comment]
Thank you very much! this really help

**Comment by yuban111** [comment]
your answer was very helpful to me  loveu

**Comment by champy44** [comment]
really helpful, after hours of installing and uninstalling turns out to be something so simple

**Comment by duongttr** [comment]
> Hello. Thank you for looking into this issue. I re-installed, but that didn't solve. However, this is a new Python gotcha! My Python script name was - gradio.py. So when I was using import gradio as gr, it was importing but confusing with the file name. Changed the file name to gadio_learn.py and it works like a charm. Posting so that others don't waste time like I did....

Haha, this reply saves my day. Thank you so much!

**Comment by Unitato** [comment]
i was running running into the same issue using python 3.7, upgrading the venv to 3.10 fixed the issue for me

**Comment by Abecid** [comment]
I was doing the same thing lol 

> Hello. Thank you for looking into this issue. I re-installed, but that didn't solve. However, this is a new Python gotcha! My Python script name was - gradio.py. So when I was using import gradio as gr, it was importing but confusing with the file name. Changed the file name to gadio_learn.py and it works like a charm. Posting so that others don't waste time like I did....

**Comment by inestyne** [comment]
Why do i keep naming things the same as the library i'm trying to test? :P

**Comment by vEduardovich** [comment]
> Hello. Thank you for looking into this issue. I re-installed, but that didn't solve. However, this is a new Python gotcha! My Python script name was - gradio.py. So when I was using import gradio as gr, it was importing but confusing with the file name. Changed the file name to gadio_learn.py and it works like a charm. Posting so that others don't waste time like I did....

you save me

**Comment by gem-kunal-garg** [comment]
> Hello. Thank you for looking into this issue. I re-installed, but that didn't solve. However, this is a new Python gotcha! My Python script name was - gradio.py. So when I was using import gradio as gr, it was importing but confusing with the file name. Changed the file name to gadio_learn.py and it works like a charm. Posting so that others don't waste time like I did....

Oops Same Mistake!!!

**Comment by rayros25** [comment]
I fell for one of the classic blunders...

**Comment by gorishababbar** [comment]
Ive done everything: installing lower versions of gradio, but nothing helped

**Comment by jdm4pku** [comment]
> Hello. Thank you for looking into this issue. I re-installed, but that didn't solve. However, this is a new Python gotcha! My Python script name was - gradio.py. So when I was using import gradio as gr, it was importing but confusing with the file name. Changed the file name to gadio_learn.py and it works like a charm. Posting so that others don't waste time like I did....

you saved me! Thank you!

**Comment by Sheltxn11** [comment]
Why do we commit the same thing😂

**Comment by ChellShort** [comment]
Really helpful, i stumbled into this issue two times, and I still do not learn this simple thing!
Haha

**Comment by JamesCHub** [comment]
You'll get errors like this and `gr has no method load_chat` if you install gradio on an unsupported (old) version of Python.   The installation appears to work and doesn't complain until you actually try to use it.
