### ISSUE TITLE
gradio.Image

### ISSUE THREAD

**Issue by moro23** [gradio-app/gradio#1133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

gr.Image on the getting started page returns an Attribute Error which isnt the same as the code on the github page. 

### Reproduction

demo = gr.Interface(sepia, gr.Image(shape=(200, 200)), "image")

### System Info

```shell
'2.9.4'
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Thank you @moro, you are 100% right. We should have waited until the 3.0 release before updating the getting started page. 

For now, if you'd like to use Gradio 3.0, try installing our pre-release `pip install gradio==2.9b23`. You'll find that the getting started page should work fine with this version of Gradio.

**Comment by abidlabs** [comment]
Closing this issue as it is discussed in #1129 (and all these issues should be resolved by end of next week!)
