### ISSUE TITLE
The Getting Started page is outdated 

### ISSUE THREAD

**Issue by adrien-turiot-maxa** [gradio-app/gradio#1139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Most of the examples in [the Getting Started page here](https://gradio.app/getting_started/) are outdated.
This seems to be the cause of these issues #1133 and #1129

It could be great to have a single source of truth to avoid this kind of issue. 

### Reproduction

For example the **Customizable Components** section:

- In the README [here](https://github.com/gradio-app/gradio#customizable-components):

```py
import gradio as gr


def greet(name):
    return "Hello " + name + "!"


iface = gr.Interface(
    fn=greet,
    inputs=gr.inputs.Textbox(lines=2, placeholder="Name Here..."),
    outputs="text",
)
iface.launch()
```

- in the web page [here](https://gradio.app/getting_started/#customizable-components):

```py
import gradio as gr


def greet(name):
    return "Hello " + name + "!"


demo = gr.Interface(
    fn=greet,
    inputs=gr.Textbox(lines=2, placeholder="Name Here..."),
    outputs="text",
)

if __name__ == "__main__":
    app, local_url, share_url = demo.launch()
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Thank you @adrien-turiot-maxa, you are 100% right. We should have waited until the 3.0 release before updating the getting started page. 

For now, if you'd like to use Gradio 3.0, try installing our pre-release `pip install gradio==2.9b23`. You'll find that the getting started page should work fine with this version of Gradio.

**Comment by abidlabs** [comment]
Closing this issue as it is discussed in #1129 (and all these issues should be resolved by end of next week!)
