### ISSUE TITLE
Time series with decimal numbers

### ISSUE THREAD

**Issue by mistycheney** [gradio-app/gradio#1141]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
It seems currently time series component only works with integer values.

**Describe the solution you'd like**  
Add support for decimal values.

**Additional context**

**Comment by pngwn** [comment]
Do you have some example data or a simple repro that, I could test this with?

**Comment by pngwn** [comment]
You can ignore this, I understand the problem now.
