### ISSUE TITLE
Problems with flagging_options parameter usage

### ISSUE THREAD

**Issue by Zengyf-CVer** [gradio-app/gradio#1150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have some problems using `flagging_options`, when I refer to https://gradio.app/docs/#o_carousel, there is only this description: `flagging_options (List[str]) - if provided, allows user to select from the list of options when flagging. Only applies if allow_flagging is "manual".` But I have no idea what exactly this parameter does? So I clicked on an example: https://colab.research.google.com/drive/1-e53lfdn59VJ7VTF0Ab1Lxme8Lvp0ohS#scrollTo=e200MmBU2aLT, which I found didn't work.

### Reproduction

https://colab.research.google.com/drive/1-e53lfdn59VJ7VTF0Ab1Lxme8Lvp0ohS#scrollTo=e200MmBU2aLT

![Image 1](https://user-images.githubusercontent.com/41098760/166452675-f837bc06-3f2c-40d6-a482-89fe04bbd14a.png)

### System Info

```shell
https://colab.research.google.com/drive/1-e53lfdn59VJ7VTF0Ab1Lxme8Lvp0ohS#scrollTo=e200MmBU2aLT
```

### Severity

annoyance

**Comment by abidlabs** [comment]
The purpose of `flagging_options` is to allow users to select a particular option as they flag a data. This could allow them to provide more information e.g. why a particular sample has a mistaken prediction

The demo is running fine for me, what error are you getting? Make sure to install `fpdf` in the colab notebook -- you can run `!pip install -q gradio fpdf` in the first cell

**Comment by Zengyf-CVer** [comment]
@abidlabs 
I found that `flagging_options` can only be logged in `log.csv`, which can be problematic for users who are not operating locally. Can you add some hints, such as text hints that the mark is saved in a certain path?

**Comment by Zengyf-CVer** [comment]
@abidlabs 
https://colab.research.google.com/drive/1-e53lfdn59VJ7VTF0Ab1Lxme8Lvp0ohS#scrollTo=e200MmBU2aLT
I found a theme color bug, when I set `theme="seafoam"`, the following situation occurs:

![Image 1](https://user-images.githubusercontent.com/41098760/166604577-1bc9aefc-1967-42c6-8580-6c2e0b9a25f5.png)

![Image 2](https://user-images.githubusercontent.com/41098760/166604582-2767505b-23fe-4187-8e81-ca88e959d268.png)

The color of the words will be very light, which affects the user experience.
