### ISSUE TITLE
Model 3D component not destroyed correctly (cached examples)

### ISSUE THREAD

**Issue by radames** [gradio-app/gradio#1160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Trying to upgrade the PIFu Space project to the latest `gradio==2.8b23` however the cached examples via the classical `Interface` don't seem to be functional well with `gr.Model3D` as compared to the previous `gr.outputs.Image3D` 
When switching between examples, the Model3D component doesn't clean up the state. I'm guessing this is the related to the component preprocess_example call.

### Reproduction

```shell
git clone https://huggingface.co/spaces/radames/PIFu-Clothed-Human-Digitization
pip install -r requirements.txt
pip install gradio==2.9b23
python PIFu/spaces.py 
```

### Screenshot

![image](https://user-images.githubusercontent.com/102277/166814423-fea74026-ad78-4ce0-823d-8655b8d3b582.png)

![image](https://user-images.githubusercontent.com/102277/166815285-64aadf07-0435-42f0-bd8d-8177d77251b7.png)

### System Info

```shell
gradio==2.9b23
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Hi @radames can you confirm that this issue is fixed on `graido==3.0b6`?

**Comment by radames** [comment]
hi @abidlabs @dawoodkhan82 confirm this is working great now! this space https://huggingface.co/spaces/radames/PIFu-Clothed-Human-Digitization. (note, however the File Component still has a problem with the cached files)

**Comment by dawoodkhan82** [comment]
> hi @abidlabs @dawoodkhan82 confirm this is working great now! this space https://huggingface.co/spaces/radames/PIFu-Clothed-Human-Digitization. (note, however the File Component still has a problem with the cached files)

Will take a look. Thanks @radames
