### ISSUE TITLE
Bugs on demo files?

### ISSUE THREAD

**Issue by MCDF31** [gradio-app/gradio#1163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While trying out the demo codes on Jupyter notebooks I got several errors. For example on the Dataframe example i get an error call saying "AttributeError: module 'gradio' has no attribute 'Dataframe'

### Reproduction

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import gradio as gr

def sales_projections(employee_data):
    sales_data = employee_data.iloc[:, 1:4].astype("int").to_numpy()
    regression_values = np.apply_along_axis(
        lambda row: np.array(np.poly1d(np.polyfit([0, 1, 2], row, 2))), 0, sales_data
    )
    projected_months = np.repeat(
        np.expand_dims(np.arange(3, 12), 0), len(sales_data), axis=0
    )
    projected_values = np.array(
        [
            month * month * regression[0] + month * regression[1] + regression[2]
            for month, regression in zip(projected_months, regression_values)
        ]
    )
    plt.plot(projected_values.T)
    plt.legend(employee_data["Name"])
    return employee_data, plt.gcf(), regression_values

demo = gr.Interface(
    sales_projections,
    gr.Dataframe(
        headers=["Name", "Jan Sales", "Feb Sales", "Mar Sales"],
        default=[["Jon", 12, 14, 18], ["Alice", 14, 17, 2], ["Sana", 8, 9.5, 12]],
    ),
    ["dataframe", "plot", "numpy"],
    description="Enter sales figures for employees to predict sales trajectory over year.",
)
if __name__ == "__main__":
    demo.launch()

### Screenshot

![Screen Shot 2022-05-05 at 2 22 14 PM](https://user-images.githubusercontent.com/34763646/166921939-f111d2fb-468e-405a-9ddb-8e8b1a79dcf0.png)

### System Info

```shell
Mac V 12.3.1 running on Jupyter Notebooks on Chrome
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Closing this issue as it is discussed in #1129 (and all these issues should be resolved by end of next week!)
