### ISSUE TITLE
Context management in TabbedInterface

### ISSUE THREAD

**Issue by nateraw** [gradio-app/gradio#1166]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Often times when you develop apps, you end up having `model` in the global context of your app. If you use the tabbed interface, it could end up leading to having many different models loaded into memory at once, causing OOM errors. I just experienced this on my macbook (I think?) while playing around with [this app](https://github.com/nateraw/gradio-guides).

**Describe the solution you'd like**  
I'm not entirely sure, but maybe we can discuss here. Perhaps there isn't even a feature to be made here, but rather we just need to come up with some usage patterns we can share with folks if they run into this issue was well. 

The idea, from a high level, is that you might want to clear up memory when you leave tabs, and load new models/tokenizers/etc when you enter a new tab. This can definitely just be done by the user on "submit", but I'm just curious if anybody has any idea how we could make this easier so folks wouldn't have to do it manually. Also, I don't know if this really is an issue for other people quite yet since the `TabbedInterface` is such a new feature.

**Comment by abidlabs** [comment]
Hmm the only thing I can think of then is to load the model when a tab is selected. This _is_ currently possible in Blocks, but it requires going below the `TabbedInterface` abstraction and instead creating tabs manually.

Something like (untested code):

```py
model = None

def load1():
  model = load_model1()

def load2():
  model = load_model1()

def predict(x):
   model.predict(x)

with gr.Blocks() as blocks:
  with gr.Tabs():
    with gr.TabItem() as t1:
      ...
    with gr.TabItem() as t2:
      ...
    
   t1.select(load1, [], [])   
   t2.select(load2, [], [])   

```

**Comment by pngwn** [comment]
As soon as you have more than 1 user, chances are you're gonna end up with multiple models in memory surely, even with this ondemand loading? 

I think this could also have an impact on end user performance if a user changes tab + submits very quickly.

**Comment by abidlabs** [comment]
Oh you're right @pngwn both of these problems exist with this approach

**Comment by nateraw** [comment]
Wow @pngwn I totally missed that issue 😅. My bad! Seems you'd just have to work around it in the code as @abidlabs. 

Thanks folks - closing this, as I don't think there's anything to do here.

**Comment by nateraw** [comment]
Leaving this closed, but just wanted to add a note here in case someone else comes across this/it comes up in the future...

You can actually use `gr.Interface.load` to get around this problem. Each app is still hosted separately, so you don't need to worry about running out of memory on the user-facing `TabbedInterface`, since its just iframes you're seeing.

```python
import gradio as gr

gr.TabbedInterface(
    interface_list=[
        gr.Interface.load('spaces/username/app_a'),
        gr.Interface.load('spaces/username/app_b'),
    ],
    tab_names=['App A', 'App B'],
).launch()
```

I'll play with this workflow and share a bit wider if I find it useful
