### ISSUE TITLE
Undocumented backwards incompatibility in version 2.9.4

### ISSUE THREAD

**Issue by eXceediDeaL** [gradio-app/gradio#1169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello, I found that the most recent version **2.9.4** of gradio probably introduces a small **breaking change**, which is not recorded in release notes: Adding optional parameter `file_path` in function `gradio.component.Component.save_flagged_file`.

Maybe recording this change in release notes helps to avoid user confusion during updating this version?

Kind regrads,

@eXceediDeaL

### Reproduction

This change could cause inconsistent signature if a subclass of `Component` overrides `save_flagged_file` method. For example,

```python
class SubComponent(Component):
  def save_flagged_file(
        self, dir: str, label: str, data: Any, encryption_key: bool
    ) -> Optional[str]:
    return super().save_flagged_file(dir, label, data, encryption_key)
```

### System Info

```shell
- Gradio: 2.9.4
- System: Ubuntu 20.04
```

### Severity

blocker

**Comment by abidlabs** [comment]
Thanks @eXceediDeaL, good catch! We can definitely amend the release notes, but we're actually just about to release Gradio 3.0, which overhauls `components.py` almost completely. We strongly encourage everyone to migrate 3.0, and as a result, I think in this case, I think it's sufficient to have this issue to notify the small number of users who might run into this issue about the breaking change.
