### ISSUE TITLE
Submodules don't get initialized in hosted deployment

### ISSUE THREAD

**Issue by potipot** [gradio-app/gradio#117]
When launching a hosted deployment from repo, the submodules used in my solution don't get cloned resulting in
```bash
NameError: name 'EffDetModel' is not defined
```

I guess a flag of `--recurse-submodules` is missing somewhere in the workflow.

**Comment by aliabd** [comment]
Thanks for opening this issue @potipot, @aliabid94 is looking into it and we'll have a fix soon

**Comment by abidlabs** [comment]
Should be fixed now @potipot! Thanks for bringing it to our attention.

**Comment by potipot** [comment]
Thanks a lot for your quick response!
