### ISSUE TITLE
HighlightText - copy whitespace

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#1176]

**Comment by abidlabs** [comment]
Unless I'm misunderstanding something, it looks like this issue has been resolved:

![Recording 2023-03-25 at 19 10 56](https://user-images.githubusercontent.com/1778297/227751456-8b321129-c6e8-4946-a8d6-0c148f635cae.gif)

**Comment by pngwn** [comment]
Looks good!

**Comment by abidlabs** [comment]
Thanks!
