### ISSUE TITLE
pkg_resources.UnknownExtra: markdown-it-py 0.5.8 has no such extra feature 'plugins'

### ISSUE THREAD

**Issue by Adeel-Intizar** [gradio-app/gradio#1189]
Hi, 
I am having issues importing the gradio, this issue never arouse before, can you help ?
![image](https://user-images.githubusercontent.com/56041154/167352318-b4b2bd66-d0fa-4d3b-bb8b-620b2bd3b6a1.png)

**Comment by abidlabs** [comment]
You're using a very old version of markdown-it-py it seems. Can you try updating it to the latest version?

`pip install markdown-it-py --upgrade`

**Comment by Adeel-Intizar** [comment]
Thank you
