### ISSUE TITLE
Accept non-wav files as input

### ISSUE THREAD

**Issue by piraka9011** [gradio-app/gradio#119]
Currently, the audio input supports only wav files using `scipy`.

Would be good to also support other audio files like mp3 using `librosa` or someother library.

**Comment by aliabd** [comment]
We're looking into this @piraka9011. 

For now, you can pass `type="file"` into the `Audio` class and it will return the input as a temporary file object. This will allow you to accept audio files in any format, but you will have to convert them to numpy or mfcc etc. More info in [our docs](https://gradio.app/docs#i_audio).

**Comment by aliabid94** [comment]
mp3 now supported. Thanks for pointing this out.
