### ISSUE TITLE
Interface with providing multiple functions

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While working on #1190, Interface taking multiple functions proved to be troublesome. And I encountered an error.

Why do we let user provide multiple functions to the Interface, they could just return multiple outputs from a single function?
Check [here](https://github.com/gradio-app/gradio/blob/9c1cef57f67694de29135fc6ea6f581572e7a324/gradio/interface.py#L113)
cc: @aliabid94 

### Reproduction

import gradio as gr

def hello(*args):
    return "Hello after 5 second"

gr.Interface([hello, hello], "text", ["text", "text"]).launch()

### Screenshot

![image](https://user-images.githubusercontent.com/44067394/167396403-25f48f9c-87a6-4b25-9629-9a22d500582f.png)

### System Info

```shell
main
```

### Severity

blocker

**Comment by abidlabs** [comment]
Closed via #1623
