### ISSUE TITLE
Better error message when format of `examples` is incompatible with `inputs` 

### ISSUE THREAD

**Issue by merveenoyan** [gradio-app/gradio#1194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello the greatest OS devs on 🌍 👋

I'm playing with the dataframe component and saw that examples are only passed as lists, so I converted the dataframe into list and managed to break the interface. It applies for any list. 
Broken interface looks like below:
![Ekran Resmi 2022-05-09 15 05 18](https://user-images.githubusercontent.com/53175384/167416036-ab3df9e9-9540-43b5-8aa8-7beb5b313cfa.png)
I removed the example and it worked as usual. 

### Reproduction

You can run this [kaggle notebook ](https://www.kaggle.com/code/unofficialmerve/notebookf190d598a4/edit)or simply doing:

```
import gradio as gr
df = gr.Dataframe(interactive=True, headers=["1","2","3"], type = "pandas")
outcome = gr.outputs.Dataframe(headers = ["Diabetes"])
iface = gr.Interface(inference_function, inputs = df, examples = [1,2,3,4,5,6,7,8],   outputs = outcome)
iface.launch(share=True, debug=True)
```
should work. 

### Logs

There's no logs even when I set `debug = True.`

### System Info

```shell
gradio==2.9b25
```

### Severity

annoyance

**Comment by abidlabs** [comment]
@merveenoyan not sure I understand the issue:

```py
import gradio as gr
df = gr.Dataframe(interactive=True, headers=["1","2","3"], type = "pandas")
outcome = gr.outputs.Dataframe(headers = ["Diabetes"])
iface = gr.Interface(inference_function, inputs = df, examples = [1,2,3,4,5,6,7,8],   outputs = outcome)
iface.launch(share=True, debug=True)
```

Here, the examples that are provided don't line up with the headers that were provided, so there should be an error that is thrown. What is the behavior that you were expecting?

**Comment by merveenoyan** [comment]
@abidlabs I'd rather have an error thrown, there's nothing that gives me a signal that this shouldn't be the way to create this Block. (like we do in interface)

**Comment by abidlabs** [comment]
Agreed, we should catch this in the backend and throw a better error message

**Comment by taimaruuu** [comment]
would love to help resolve this issue!

**Comment by t-vi** [comment]
Hi! I was about to file an issue about checking examples against the input spec in general (I got an impenetrable JS error on the browser console and no UI display when it happened to me), but I am unsure if this issue tracks this or if it is more specific. Any advice would be appreciated. Thank you!

**Comment by abidlabs** [comment]
@t-vi, thanks for bringing this up! We can adapt this issue to be more general, but it would be great if you can share the code that was erroring out for you as well so that we can make sure to address that use case.
