### ISSUE TITLE
Dataframe component overflowing from the tab

### ISSUE THREAD

**Issue by merveenoyan** [gradio-app/gradio#1196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Dataframe component overflows from the tab even if the page is 75 percent zoomed out.
<img width="394" alt="Ekran Resmi 2022-05-09 16 31 07" src="https://user-images.githubusercontent.com/53175384/167432643-93e46bd0-b761-48f3-bf17-ace5b142e53c.png">

### Reproduction

My code is below:

```
import gradio as gr
df = [i for i in range(8)]
def inference_function_xgb(df):
    print(df)
def inference_function_rfc(df):
    print(df)

outcome = gr.outputs.Textbox()

with gr.Blocks() as demo:
    
    with gr.Tabs():
        with gr.TabItem("XGBoost") as xgb:
            with gr.Row():
                df = gr.Dataframe(interactive=True, headers=[i for i in range(8)], type = "pandas")
                inference_run = gr.Button("Infer")
                inference_progress = gr.StatusTracker(cover_container=True)
                inference_run.click(
                    inference_function_xgb,
                    inputs=df,
                    outputs=outcome,
                    status_tracker=inference_progress,
                )
        with gr.TabItem("Random Forest Classifier") as rfc:
            with gr.Row():
                df = gr.Dataframe(interactive=True, headers=[i for i in range(8)], type = "pandas")
                inference_run = gr.Button("Infer")
                inference_progress = gr.StatusTracker(cover_container=True)
                inference_run.click(
                    inference_function_rfc,
                    inputs=df,
                    outputs=outcome,
                    status_tracker=inference_progress,
                )

if __name__ == "__main__":
    demo.launch()
```
it's dummified, but still reproduces the error :') 

### Screenshot

Posted above.

### Logs

```shell
App works just fine :')
```

### System Info

```shell
gradio==2.9b25
```

### Severity

annoyance

**Comment by merveenoyan** [comment]
pinging @pngwn here :)

**Comment by pngwn** [comment]
@merveenoyan Since you're playing around at the minute, I'm curious what do you expect `gr.Rows()` to do. Ignoring the ovbious bugs, does it lay things out as expected or would you expect something else?

**Comment by merveenoyan** [comment]
@pngwn yes I want them to look that way :)
Something really annoying was when I put the inference result between infer button and the dataframe and it got crushed and I can't see anything. I think ability to expand/toggle would be super nice!
<img width="1172" alt="Ekran Resmi 2022-05-09 16 43 58" src="https://user-images.githubusercontent.com/53175384/167435256-cbd0ad72-9c96-4023-ac21-a5d94c26d0fc.png">

**Comment by abidlabs** [comment]
Can confirm this is now fixed:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/1778297/167923168-16df6d68-029b-4c6a-8547-0f3a276fd0fd.png">

Thanks @pngwn and @merveenoyan!
