### ISSUE TITLE
Better icon / image for keyboard shortcuts for examples

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#120]
This doesn't look very nice:

![image](https://user-images.githubusercontent.com/1778297/108548796-efa0c200-72b1-11eb-9bf6-d3484450300d.png)

Can we replace with an image / icon, maybe like this:

![image](https://user-images.githubusercontent.com/1778297/108548922-19f27f80-72b2-11eb-97c3-e3f9f291f0cb.png)

**Comment by aliabid94** [comment]
Done.
