### ISSUE TITLE
Getting started, steps 2 and 3 (and possibly others) creates an error: module 'gradio' has no attribute 'xxx'

### ISSUE THREAD

**Issue by nganani** [gradio-app/gradio#1206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

should be `gr.inputs.Slider` (sample 3) or `gr.inputs.Textbox' (sample 2) and instead showing `gr.Slider` and 'gr.Textbox' respectively, causing an error. adding 'inputs' in between solves it - so easy fix, but your samples in the getting started should be updated

### Reproduction

very easy, just ran the samples in the getting started in a notebook or locally

### Screenshot

<img width="664" alt="image" src="https://user-images.githubusercontent.com/7979328/167690482-5195dc93-8546-4294-a50d-bea5f2fa0f34.png">

### System Info

```shell
gradio 2.9.4, mac OS or latest Chrome with google notebook
```

### Severity

blocker

**Comment by abidlabs** [comment]
Thanks for creating the issue @nganani. Should be fixed now with the release of `gradio==3.0.2`. All of our docs and library are now in sync.
