### ISSUE TITLE
Review fonts

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#1224]
- [ ] Choose between system and source sans pro
- [ ] Performance (loading, too many fonts)

**Comment by Tetsujinfr** [comment]
I have tried to downgrade to 2.9.4 and to many other earlier versions, but they all call cloudflare.com or googletagmanager.com etc.

The only version which was not calling external resources was like 0.8 or earlier even. But it did not render the demo code properly anyway.
A shame that you need an internet connection to render a web UI, but hopefully you guys can work around this, unless it is a conscious design decision to connect to external services as part of the UI.

But pls note that at this point, to run Gradio, you do not "just need python 3.7" .

**Comment by pngwn** [comment]
> A shame that you need an internet connection to render a web UI, but hopefully you guys can work around this, unless it is a conscious design decision to connect to external services as part of the UI.

There is an open issue for this which we will address as part of the current theming work. #1450 

It is a bit tricky due to how some assets are loaded in but we at least want gradio to _mostly_ work without an internet connection.

**Comment by abidlabs** [comment]
Closed via #9204
