### ISSUE TITLE
[blocks_flashcards] Row styles and conditional Row issues

### ISSUE THREAD

**Issue by radames** [gradio-app/gradio#1233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug
Conditional Rows are not working 

```python
            with gr.Row():
                front = gr.Textbox()
                answer_row = gr.Row(visible=False)
                with answer_row:
                    back = gr.Textbox()
            with gr.Row():
                new_btn = gr.Button("New Card")
                flip_btn = gr.Button("Flip Card")
                selected_card = gr.Variable()
                feedback_row = gr.Row(visible=False)
                with feedback_row:
                    correct_btn = gr.Button(
                        "Correct",
                        css={"background-color": "lightgreen", "color": "green"},
                    )
                    incorrect_btn = gr.Button(
                        "Incorrect", css={"background-color": "pink", "color": "red"}
                    )

```

### Reproduction

Test Notebook
https://colab.research.google.com/drive/16IWOGsPFXyVbybrqAEGUN6Oti5nP4XBs

Demo
https://github.com/gradio-app/gradio/blob/main/demo/blocks_flashcards/run.py

### Screenshot

**Buttons and rows overflow
Rows `visible=False` don't hide the row**
 
![image](https://user-images.githubusercontent.com/102277/168151641-ba692acf-557b-4943-bc46-bc159ef1da23.png)

**Small screens 
Additional padding left to  elements**

![image](https://user-images.githubusercontent.com/102277/168151938-daf594b4-a2f9-46bc-b6c9-df3edb5596a8.png)

### System Info

```shell
`gradio==3b1`
```

### Severity
blocker

**Comment by pngwn** [comment]
@aliabid94  Can you explain what this demo was meant to do layout-wise because I'm not entirely sure the intended layout is with all of the nested bits.

**Comment by radames** [comment]
@pngwn just added some screenshots. I'm not sure about the full demo intention, but the conditional rows definitely not working. The way I read is, after your response it enables the hidden Row. Is this api functional valid?   `gr.Row(visible=False)`

**Comment by pngwn** [comment]
It is part of the python interface but it doesn't actually work any more because of some style changes we made. The prop is passed but it doesn't actually have a frontend implementation. That would explain it.

Although there is clearly more than that is broken here.

**Comment by radames** [comment]
I see, @pngwn, I guess we can always offer that feature later and temp remove or leave a note on demos not ready @abidlabs what do you think?

**Comment by pngwn** [comment]
Will fix it in the morning.

**Comment by pngwn** [comment]
As well as all of the other broken things.
