### ISSUE TITLE
Smaller screen layout has collapsed rows 

### ISSUE THREAD

**Issue by radames** [gradio-app/gradio#1238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Since 5ba2e06e6971e946f2bdae0090b847056592a365 the rows are now collapsed on mobile. It might be something simple, and I'm sorry if you already know this issue @pngwn 

### Reproduction

https://github.com/gradio-app/gradio/tree/main/demo/blocks_layout

https://github.com/gradio-app/gradio/tree/main/demo/digit_classifier

### Screenshot

Examples:

Large screen
<img width="400" alt="image" src="https://user-images.githubusercontent.com/102277/168181281-fd2da459-55b9-42f1-96a8-ecaf3ae71309.png">
Small screen
<img width="400" alt="image" src="https://user-images.githubusercontent.com/102277/168181225-08b47791-05ea-4aa6-89d9-1421b38aee35.png">

Large screen
<img width="400" alt="image" src="https://user-images.githubusercontent.com/102277/168181260-ef7090c7-0b83-41c8-9e22-a1eda0ce02ad.png">
Small screen
<img width="400" alt="image" src="https://user-images.githubusercontent.com/102277/168181246-f337a2a2-51c7-465c-9059-bc8e1ca465b8.png">

### System Info

```shell
main branch
```

### Severity

annoyance

**Comment by pngwn** [comment]
Hmm, it must be a different change to the commit you mentioned. I don't think the affected components have any relationship to the changed ones. Will take a look, probably some flex change.
