### ISSUE TITLE
Implement `Carousel`

### ISSUE THREAD

**Issue by radames** [gradio-app/gradio#1240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Running demo  [demo/disease_report/run.py](https://github.com/gradio-app/gradio/blob/main/demo/disease_report/run.py)

I don’t see `gr.Carousel` working in any examples. I’ve also notice that the constructor is not accepting the positioned arguments vs the named argument
`gr.Carousel(["text", "image"], label="Disease")` vs valid `gr.Carousel(components=["text", "image"], label="Disease")` 

### Reproduction

https://colab.research.google.com/drive/1-7jB25j_tfl91zojMF4ujN5q6b1FaL9k?usp=sharing

  [demo/disease_report/run.py](https://github.com/gradio-app/gradio/blob/main/demo/disease_report/run.py)

### Screenshot

<img width="762" alt="image" src="https://user-images.githubusercontent.com/102277/168190256-a9b0a47f-6fcb-41a1-bd28-813acda1a3cf.png">

vs expected

<img width="974" alt="image" src="https://user-images.githubusercontent.com/102277/168190325-ae3f3137-1e1f-4a99-adbb-cbcc0bfbd3a6.png">

### System Info

```shell
gradio=3b1
```

### Severity

blocker

**Comment by pngwn** [comment]
Carousel is basically not implemented right now, or rather than frontend and backebnd have inconsistent implementations. Unsure how to procedd right now.

**Comment by abidlabs** [comment]
We will implement `Carousel` later on

**Comment by apolinario** [comment]
@abidlabs with 3.0b5 the lack of carousel broke `gr.Interface.load()` from a Spaces that used it and stayed in 2.x. I'd recommend to keep the backend at least - as even though using it broke, to load other interfaces it was working up until `3.0b2`

**Comment by abidlabs** [comment]
Now that the `Gallery` component supports both images and captions (which was the most common use case of the `Carousel`), I think we should officially deprecating this component. Thoughts @pngwn @aliabid94?

**Comment by aliabid94** [comment]
Sounds good to me. Can we get some analytics on its usage?

**Comment by abidlabs** [comment]
The `Carousel` component has been officially deprecated.
