### ISSUE TITLE
[fake_gan_complex] Markdown with Interface input (no Blocks) bug

### ISSUE THREAD

**Issue by radames** [gradio-app/gradio#1241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`gr.Markdown` component raises  `'requires_permissions'` when used inside `Interface`  inputs without  `Blocks`

https://colab.research.google.com/drive/1sU2aU61roXO0mxTyO2Dk2ObaRHtMuRId?usp=sharing

`AttributeError: 'Markdown' object has no attribute 'requires_permissions'` 

### Reproduction

https://colab.research.google.com/drive/1sU2aU61roXO0mxTyO2Dk2ObaRHtMuRId?usp=sharing

https://github.com/gradio-app/gradio/blob/main/demo/fake_gan_complex/run.py

```python


demo = gr.Interface(
    fn=fake_gan,
    inputs=[
        gr.Image(label="Initial Image (optional)"),
        gr.Markdown("**Parameters**"),
        gr.Slider(25, minimum=0, maximum=50, label="TV_scale (for smoothness)"),
        gr.Slider(25, minimum=0, maximum=50, label="Range_Scale (out of range RBG)"),
        gr.Number(label="Respacing"),
        gr.Markdown("**Parameters Two**"),
        gr.Slider(25, minimum=0, maximum=50, label="Range_Scale (out of range RBG)"),
        gr.Number(label="Respacing"),
        gr.Markdown("**Parameters Three**"),
        gr.Textbox(label="Respacing"),
    ],
    outputs=gr.Image(label="Generated Image"),
    title="FD-GAN",
    description="This is a fake demo of a GAN. In reality, the images are randomly chosen from Unsplash.",
)
```

vs no Markdown

```python

demo = gr.Interface(
    fn=fake_gan,
    inputs=[
        gr.Image(label="Initial Image (optional)"),
        gr.Slider(25, minimum=0, maximum=50, label="TV_scale (for smoothness)"),
        gr.Slider(25, minimum=0, maximum=50, label="Range_Scale (out of range RBG)"),
        gr.Number(label="Respacing"),
        gr.Slider(25, minimum=0, maximum=50, label="Range_Scale (out of range RBG)"),
        gr.Number(label="Respacing"),
        gr.Textbox(label="Respacing"),
    ],
    outputs=gr.Image(label="Generated Image"),
    title="FD-GAN",
    description="This is a fake demo of a GAN. In reality, the images are randomly chosen from Unsplash.",
)
```

### System Info

```shell
gradio=3b1
```

### Severity

blocker

**Comment by abidlabs** [comment]
Hi @radames, the `Markdown` component can't really be used in this way, because this would make the Markdown component an input and it would expect a corresponding function parameter. 

However, we _are_ thinking about adding a "gr.Section()" for the use case you are describing. This is discussed more in #938. cc @pngwn

**Comment by radames** [comment]
ok @abidlabs thank you, I'll adjust the demo

**Comment by abidlabs** [comment]
After internal discussion, reopening to allow Markdown to be a valid component (but we should still remove/adjust the demo)
