### ISSUE TITLE
Respect Hugging Face Theme On Spaces

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Gradio spaces does not respect/follow Hugging Face site theme

### Reproduction

go onto any space with 
- System Theme: dark
- HF theme: light

### Screenshot

![image](https://user-images.githubusercontent.com/44067394/168230349-1dcdd1bc-b553-44a9-973f-ce7ca8ca8734.png)
![image](https://user-images.githubusercontent.com/44067394/168230361-1454c886-7de0-4178-b1ae-c38d16624001.png)

### System Info

```shell
Spaces
```

### Severity

critical

**Comment by FarukOzderim** [comment]
I think it would be better to not let users experience this, adding it to 3.0 milestone in case we can cover this.

**Comment by pngwn** [comment]
This isn't something that can be addressed in Gradio, we are awaiting some changes on the hub. Everything on the gradio side has been done.
