### ISSUE TITLE
DataFrame pagination 

### ISSUE THREAD

**Issue by Zengyf-CVer** [gradio-app/gradio#1245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug
@pngwn 
I found out when working with DataFrame that the output cannot be paginated.

### Reproduction

```python
import gradio as gr
import pandas as pd
import plotly.express as px

def show_pens(alpha):
    df_pens = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv')
    print(df_pens)
    return df_pens.iloc[:5, :3]

iface = gr.Interface(
    fn=show_pens, 
    inputs=['text'],
    outputs=[gr.outputs.Dataframe()],
    description="Table of Palmer Penguins"
)

iface.launch()
```

Click submit and find that the form has no pagination:

![ksnip_20220513-193043](https://user-images.githubusercontent.com/41098760/168274615-c1b3b55c-bde9-4327-958c-8740bc45e87b.png)

### System Info

```shell
Ubuntu 20.04
Chrome
gradio 2.9.4
```

### Severity

annoyance

**Comment by freddyaboulton** [comment]
Closing in favor of #2209. Thank you @Zengyf-CVer will hopefully get this fixed soon!

**Comment by arielgamino** [comment]
Experiencing the same. Hope this gets implemented as max_rows and overflow_row_behaviour don't seem to be working as indicated in docs.

Here are my examples https://colab.research.google.com/drive/1gQDcFd-nUx4iZrhew_HGFGq6_cV32OnJ?usp=sharing

**Comment by freddyaboulton** [comment]
Thanks for letting us know @arielgamino ! Should have a fix out soon.

**Comment by wcde** [comment]
Still not fixed.

**Comment by failable** [comment]
Still not fixed.

**Comment by pngwn** [comment]
> Instead of `max_rows` (which has now been marked as deprecated), we've implemented a `height` parameter (by default, 500 pixels) which provides similar functionality. The Dataframe has been virtualized, meaning it should be much, much faster with large datasets.

Due to this change pagination is not necessary.
