### ISSUE TITLE
[outbreak_forecast] gr.Plot with type arg conflicts

### ISSUE THREAD

**Issue by radames** [gradio-app/gradio#1255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`gr.Plot` with type `type` argument conflicts with parent class arguments

```python

     55         """
     56         self.is_template = True
---> 57         super().__init__(type="plot", **kwargs)
     58 
     59 

TypeError: __init__() got multiple values for keyword argument 'type'

```

### Reproduction

https://colab.research.google.com/drive/1sGjsyLFlL-nFNjOCmDI1UlrQfBshuT-_#scrollTo=5ObWOsYqn13S

https://github.com/gradio-app/gradio/blob/main/demo/outbreak_forecast/run.py

```python
import gradio as gr

with gr.Blocks() as blocks:
  plt = gr.Plot(type="auto")

blocks.launch()
```

### System Info

```shell
gradio==3b2
```

### Severity

blocker

**Comment by abidlabs** [comment]
Thanks so much @radames, I removed this argument in the `website-dev` branch -- hopefully we can merge soon!

**Comment by abidlabs** [comment]
Fixed now!
