### ISSUE TITLE
Feature request - Copy output text to clipboard button

### ISSUE THREAD

**Issue by chittiman** [gradio-app/gradio#128]
I'm working on an app where the output is text.  Is it possible to add a button which will help to copy output text to clipboard

**Comment by aliabid94** [comment]
There isn't a direct way to do this now but one hacky way you could do this now is by adding an HTML output to your interface. As part of the HTML output, you add a button with onclick javascript to copy the text of the output div into the clipboard.

**Comment by abidlabs** [comment]
@chittiman here's an example of a repo using Gradio to do exactly this! https://github.com/joaopalmeiro/gradio-playground-app/blob/main/app.py
