### ISSUE TITLE
Documentation and sample notebook

### ISSUE THREAD

**Issue by harirajeev** [gradio-app/gradio#13]
Thank you for building this useful tool.

For below points from README 
**(1) identifying and correcting mislabelled data; 
(2) valuing each datapoint to automatically identify which data points should be labeled;****

Have you outsourced the code , if so could you please provide the details.
A sample notebook and documentation around it will be more helpful.

thanks again
Hari

**Comment by dawoodkhan82** [comment]
> Thank you for building this useful tool.
> 
> For below points from README
> **(1) identifying and correcting mislabelled data; (2) valuing each datapoint to automatically identify which data points should be labeled;****
> 
> Have you outsourced the code , if so could you please provide the details.
> A sample notebook and documentation around it will be more helpful.
> 
> thanks again
> Hari

Hey harirajeev, I wanted to reach out to see if you would be willing to hop on a quick call with us. We wanted to talk to some users of Gradio-UI ad get your feedback.

**Comment by abidlabs** [comment]
Outdated
