### ISSUE TITLE
3.0.1 Dataframe empty row

### ISSUE THREAD

**Issue by Zengyf-CVer** [gradio-app/gradio#1303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@pngwn 
I am using gradio 3.0.1 and found that there is a problem with blank rows in Dataframe output: when the data is less than 3 rows, there are blank rows, as shown in the figure.

### Reproduction

![ksnip_20220517-083436](https://user-images.githubusercontent.com/41098760/168704084-19c0509c-e575-4443-9e97-089315aab9a7.png)

![ksnip_20220517-083448](https://user-images.githubusercontent.com/41098760/168704105-482e8de0-a449-4c16-9ae5-f67f2d2cc0a6.png)

![ksnip_20220517-083504](https://user-images.githubusercontent.com/41098760/168704113-43d4e002-862e-4608-b69f-0bc9e1f941f2.png)

### System Info

```shell
gradio 3.0.1
ubuntu 20.04
chrome
```

### Severity

annoyance

**Comment by Zengyf-CVer** [comment]
@pngwn 
My project: https://huggingface.co/spaces/Zengyf-CVer/Gradio_YOLOv5_Det_v3
You can enter a picture with a picture of one object or two objects.

**Comment by pngwn** [comment]
Ah thanks.

**Comment by pngwn** [comment]
What is happening here is the dataframe is always respecting the `row_count` as a minimum. If you set row_count to `1` on the Dataframe it works as expected. Not sure what the best behaviour is here.

cc @abidlabs @aliabid94

**Comment by abidlabs** [comment]
This seems like reasonable behavior to me for the Dataframe to initialize with the stated number of rows. What we need to do is implement a "delete row / delete column" functionality to address these kinds of situations

**Comment by pngwn** [comment]
This specific case is about whether the rows should match what comes back from the predict function or if it should respect the row count in that case as well. As an output the dataframe wouldn't have add/ delete functionality. 

Input and outputs aren't significantly different so what makes sense for an input doesn't _always_ make sense for an output (although I'm not sure that is the case here) but we can modify the behaviour of static vs dynamic components.

**Comment by Zengyf-CVer** [comment]
When the output Dataframe defaults to 3 lines, it will make users think that there is an illusion of outputting empty lines.

**Comment by abidlabs** [comment]
> This specific case is about whether the rows should match what comes back from the predict function or if it should respect the row count in that case as well. As an output the dataframe wouldn't have add/ delete functionality.

Oh sorry I didn't read carefully. Going off of your comment @pngwn, what if we make the default # of rows be 0 or 1. We could do this for static dataframes only, but I don't see it being a problem for dynamic dataframes either (especially right now given that you can only add rows, not delete them).

**Comment by abidlabs** [comment]
(sorry accidentally closed)
