### ISSUE TITLE
Image editor did not show edit window

### ISSUE THREAD

**Issue by JefferyChiang** [gradio-app/gradio#1306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Thanks for the updates!
I tried the new version, I found that the Image edtior didnt behave like the old one.
The image editor did not show the edit window after I pressed the edit button, it used the 'select' method directly even if I set the tool='editor'.

### Reproduction

'import gradio as gr

def image_mod(image):
    return image.rotate(45)

demo = gr.Interface(image_mod, gr.Image(type="pil", tool='editor'), "image")

if __name__ == "__main__":
    demo.launch()'

### Screenshot

![image](https://user-images.githubusercontent.com/36859596/168768339-0f9916b2-23fe-4814-8cdd-da88326fe561.png)
![image](https://user-images.githubusercontent.com/36859596/168768421-645a3203-28e3-4f43-8b1a-9256228c9e49.png)

### System Info

```shell
Win10
python 3.7.7
gradio 3.0.1 from pypi
chrome
```

### Severity

annoyance

**Comment by pngwn** [comment]
Yeah, this is intentional. The old editor was causing many issues so we will be sticking with this behaviour until we get around to #466 (which will happen soon). For now, image editing will bve limited to cropping.
