### ISSUE TITLE
Auth not working 

### ISSUE THREAD

**Issue by alenma04** [gradio-app/gradio#131]
Hello,
When I am trying to secure my app by passing values to auth parameter in launch function.It seems to have no effect.

**Comment by abidlabs** [comment]
Tested and was able to reproduce. We're looking into it.

**Comment by aliabid94** [comment]
Fixed now as of 1.6.4. Thanks for pointing it out.

**Comment by ambat77** [comment]
Just checked and it worked. Awesome.
