### ISSUE TITLE
DataFrame label not showing

### ISSUE THREAD

**Issue by atben123** [gradio-app/gradio#1314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When creating a dataframe with a label, the label does not show:

`     gr.Dataframe(headers=["Mean","Min","Max","Std"], row_count=[1,'fixed'], col_count=[4,'fixed'], datatype="number", type="pandas", label = "testtt",show_label = True)`
<img width="242" alt="image" src="https://user-images.githubusercontent.com/105737531/168857762-0c43629f-8864-40c4-8d4f-1041f7ab4295.png">

### Reproduction

Create a DataFrame input with label

### System Info

```shell
Gradio 3.0.1
Python 3.9.7
Windows
```

### Severity

critical

**Comment by abidlabs** [comment]
Thanks for the catch @atben123!

@pngwn I think we can put a tiny dataframe icon and label above the dataframe similar to how we do it for images, video, and so on.

**Comment by abidlabs** [comment]
Fixed now, thanks for the issue @atben123. Should be out in the next release soon

**Comment by abidlabs** [comment]
Should be fixed now in `gradio==3.0.3`. Thanks for creating the issue @atben123!
