### ISSUE TITLE
Queue upstream when loading apps via gr.Interface.load()

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#1316]
If **app A** uses `gr.Interface.load()` to load an **app B** that contains a `your_app.launch(enable_queue=True)`, the queue does not get respected when the **app B** is executed from the **app A**. So if there are 3 **app A** users, and all trigger **app B** at the same time, **app B** runs 3x in parallel, regardless if `enable_queue` was set to `True` on **app B**.

This implies in two things:
1. Any person can bypass the **app B** queue by using **app A** 
2. The host machine of **app B** may OOM if multiple users are running it from **app A**, as no queue is in place

This can currently be mitigated by adding a `enable_queue=True` to **app A** however this two shortcomings:
1. **app A** developer has to have the goodwill to include the queuing function there (including using `gr.Interface.load()` privately via localhost - which can be an easy way to bypass any queue), if they don't, **app B** gets resource drained outside of their control
2. This makes **app A** inefficient. Suppose **app A** not only loads **app B** but also loads **apps C and D** with `gr.Interface.load()`. If `enable_queue` is on **app A**, now when you call apps B, C, D from it, they get into the same queue, even though each could have very different internal queues (this happens with [MindsEye Lite](https://huggingface.co/spaces/multimodalart/mindseye-lite))

Suggested solution: 
- Add the **app A** users that are calling **app B** to the same queue as native **app B** users

If that gets implemented make sure to de-register from **app B**'s queue the users that leave/give up on **app A** too, otherwise an infinite queue could arise

**Comment by apolinario** [comment]
@abidlabs, this may be important to include when bringing `gr.Interface.load()` to 3.x

**Comment by abidlabs** [comment]
Thanks for the catch and the heads up @apolinario! Will implement appropriately

**Comment by FarukOzderim** [comment]
We need to check if the loaded space is a queued space and create a ws connection from Backend.

**Comment by abidlabs** [comment]
Hi @apolinario, we are planning on making queuing on by default everywhere (#2215) -- and it already has been on by default on Spaces for quite some time. 

I'm wondering whether that makes this issue redundant as it basically is the second approach that you've mentioned (**App A** will have queuing on by default, whether or not the developer has the good will to do this). The other point about efficiency is still there, but I wonder whether that could be remedied in a different way -- for example by having separate queues for different events.

**Comment by apolinario** [comment]
Imo it doesn't make this issue redundant. I really think the ideal solution to this issue is passing the queue size downstream and sharing the queue between the main application and the loaded application. I don't know if that is possible but I feel otherwise this still makes `gr.Interface.load()` kind of unusable on high-load/large queue applications

The reason why making queuing default everywhere mitigates a bit but doesn't solve the issue, is that now the two queues (from app A and app B) are independent. So even if `app a` sends a request to `app b` one at a time (and not multiple in parallel as with queue off), people will still skip `app b`'s original queue. And more than that, as the queues are not shared, we can't control when the request from `app a` is coming to `app b`. So if app B is operating under maximum capacity and gets a job from `app a`, it would OOM (this happens quite a bit to MindsEye Lite even with queue on for both the loaded and the orchestrator apps)

**Comment by apolinario** [comment]
So for example, if I want to load the Stable Diffusion Spaces into another application "Stable Diffusion Captioner" (SDC) that first runs Stable Diffusion and then an image captioning model. 

If "Stable Diffusion Captioner" doesn't share the queue with the Stable Diffusion Spaces, even if it has a queue on its own turned o by default, the SDC user will skip everyone in the original Stable Diffusion queue when they execute the job. And, the worst part - if Stable Diffusion is executing a job at that moment, it would get the request in parallel, OOM and die.

The ideal scenario is that SDC when requests from Stable Diffusion Spaces gets their request as the last one in the original app queue.

**Comment by abidlabs** [comment]
Thanks for the detailed explanation @apolinario. That makes complete sense. The reason is that the SDC Space would be calling the `/api/predict` endpoint instead of the `/join/queue`. We'll fix this

**Comment by abidlabs** [comment]
Yes it does, so I think it should be possible in principle for the downstream app to know everything about the upstream queue
