### ISSUE TITLE
LaunchGradiofromSpaces doesn't work

### ISSUE THREAD

**Issue by jis478** [gradio-app/gradio#1320]
I've tried to use LaunchGradiofromSpaces  but it seems not working at the moment. Even this example (https://wandb.ai/akhaliq/jojogan/reports/JoJoGAN-One-Shot-Face-Stylization-with-W-B-and-Gradio---VmlldzoxNDMzNzgx) doesn't show the gradio panel.

**Comment by pngwn** [comment]
I'm pretty sure that page is running a much older version of Gradio. I'm not sure why that would have stopped working all of a sudden.

**Comment by jis478** [comment]
> I'm pretty sure that page is running a much older version of Gradio. I'm not sure why that would have stopped working all of a sudden.

I've created a space (assume that the latest version of Gradio is installed) with the default "hello" app code but LaunchGradiofromSpaces doesn't seem to work either.

**Comment by jis478** [comment]
Are there any updates on this bug?

**Comment by AK391** [comment]
also tested this, stopped working with 3.0, went back to 2.9.4 for jojogan but example images dont populate when clicked

**Comment by AK391** [comment]
@abidlabs also this is needed for a gradio demo to embed into a project page for this paper https://arxiv.org/abs/2205.12450

**Comment by AK391** [comment]
@jis478 this should be working with 3.0 spaces as well using the example here: https://gradio.app/using_hugging_face_integrations/#embedding-your-space-demo-on-other-websites

<iframe src="https://hf.space/embed/Gradio-Blocks/protGPT2_gradioFold/+" frameBorder="0" height="450" title="Gradio app" class="container p-0 flex-grow space-iframe" allow="accelerometer; ambient-light-sensor; autoplay; battery; camera; document-domain; encrypted-media; fullscreen; geolocation; gyroscope; layout-animations; legacy-image-formats; magnetometer; microphone; midi; oversized-images; payment; picture-in-picture; publickey-credentials-get; sync-xhr; usb; vr ; wake-lock; xr-spatial-tracking" sandbox="allow-forms allow-modals allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-downloads"></iframe>

**Comment by jis478** [comment]
Hi @AK391, with 3.0.9 the output image is over-sized when compared to the previous version.

![image](https://user-images.githubusercontent.com/19499513/171526414-27454c25-987e-4802-ae07-0313c0214ecc.png)

**Comment by pngwn** [comment]
@jis478 That is unrelated to this issue. Please file a new issue about the image component if there isn't one already.

Is the original issue resolved? Can you now embed gradio apps successfully with 3.x?

**Comment by FarukOzderim** [comment]
It seems the issue is resolved, closing
