### ISSUE TITLE
Linked colab notebook contains a typo

### ISSUE THREAD

**Issue by BioGeek** [gradio-app/gradio#1322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the paragraph ["Hello World" with Blocks](https://www.gradio.app/introduction_to_blocks/#hello-world-with-blocks) there is a link to a [Colab Notebook](https://colab.research.google.com/drive/1n_uB44G_uENGf0zroeVKgcytFQ-7UwZt?usp=sharing). If you run that example you get an `AttributeError: 'function' object has no attribute 'change'`. 

**Fix:**
In the Colab notebook, replace the line
```
    input.change(fn=update, 
```
with:
```
    inp.change(fn=update, 
```  

The code example in the ["Hello World" with Blocks](https://www.gradio.app/introduction_to_blocks/#hello-world-with-blocks) paragraph itself is correct.

### Reproduction

Run the Colab notebook.

### Screenshot

![blocks](https://user-images.githubusercontent.com/59344/168996546-78cd6e28-dbda-447d-8889-28bcc45d9d59.PNG)

### Logs

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-3a8c99523c6b> in <module>()
     16     out = gr.Textbox()
     17 
---> 18     input.change(fn=update, 
     19                  inputs=inp,
     20                  outputs=out)

AttributeError: 'function' object has no attribute 'change'
```

### System Info

```shell
Gradio: 3.0.2
browser: Google Chrome
```

### Severity

annoyance

**Comment by abidlabs** [comment]
This has been fixed, thanks so much @BioGeek!
