### ISSUE TITLE
Try It Code Snippets in Predict API Docs (Copy-Pasteable)

### ISSUE THREAD

**Issue by nbroad1881** [gradio-app/gradio#1325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The copy-paste code snippets in the "Try it (live demo)" section of the Predict API Docs are unusable because of the formatting.

Here are the python, curl, and js snippets copy-pasted (from https://hf.space/embed/akhaliq/FaceMesh/api)

(I deleted a lot of characters from the image string to make it easier to look at)
```python
import requests




r = requests.post(url='https://hf.space/embed/akhaliq/FaceMesh/+/api/predict/

',

 

json={"data":

 ["data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eH"

]})

r.json()
```

```sh
curl -X POST 

https://hf.space/embed/akhaliq/FaceMesh/+/api/predict/ -H 'Content-Type: application/json' -d '{"data": ["data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFh"

]}'
```

```javascript
fetch('https://hf.space/embed/akhaliq/FaceMesh/+/api/predict/', { method: "POST", body: JSON.stringify({"data":[ "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAIAAgADASIAAhEBAxEB/8QAHAAAAQUBAQEAAAAAAAAAAAAA"

]}), headers: { "Content-Type": "application/json" } }).then(function(response) { return response.json(); }).then(function(json_response){ console.log(json_response) })
```

### Reproduction

I copied from https://hf.space/embed/akhaliq/FaceMesh/api but I believe it is a problem on every single one.

### System Info

```shell
Mac Monterey 12.3 (M1), Chrome Version 101.0.4951.64 (Official Build) (arm64)
```

### Severity

annoyance

**Comment by abidlabs** [comment]
We removed the code snippets from the Predict API docs. So I'm just renaming this issue for us to bring it back, and we'll make sure that it can be copy-pasted correctly. Thanks @nbroad1881!

**Comment by abidlabs** [comment]
Moving to the documentation sprint to focus on bugs. @aliabid94 feel free to move back if you are already working on it!

**Comment by freddyaboulton** [comment]
My bad meant 3.x but thought it was not appropriate for docs milestone as that's focused on improvements to gradio.app as opposed to the api docs.

Feel free to move back if you disagree!

**Comment by abidlabs** [comment]
That's cool, moved to 3.x
