### ISSUE TITLE
Queueing [tracking and feedback]

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#1337]
We a few issues left regarding the new queue and it would be good to track them together. 

**Bugs**
- [ ] #2043
- [x] #1316
- [ ] #2019
- [x] #2114 
- [x] #2111 
- [x] #2096

**UI/UX improvements**
- [ ] #435 
- [ ] #2004
- [x] #1862 
- [x] #1984 
- [ ] #2075
- [ ] #2081 

**Faster inference for users** 
- [x] #1597
- [ ] #2001

**Testing and Documentation**
- [x] #1813
- [x] #1983
- [x] #2016

If you are a Gradio user, we'd love for you to try out the new queue, which is available in the latest version of Gradio (`gradio>=3.3`). Example Space with queue enabled: https://huggingface.co/spaces/farukozderim/test-new-queue  

**Share any feedback below!**

**Comment by FarukOzderim** [comment]
As we discussed this in the meeting, we shall cover all the use cases and bugs with a new clear design, related #572

**Comment by abidlabs** [comment]
Moving to the 3.x milestone since we are aiming to release 3.1 soon @FarukOzderim

**Comment by abidlabs** [comment]
Closing this tracking issue and milestone as we're not tackling the remaining issues "as a group". Will leave the individual issues open as we'll get around to solving them eventually.
