### ISSUE TITLE
Blocks API - Checkbox change does not trigger

### ISSUE THREAD

**Issue by andfanilo** [gradio-app/gradio#1353]
### Describe the bug

Can't get the `Checkbox.change` event to trigger 😕  did I read the documentation wrong?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

def update(checked):
    print("Updating component")
    return str(checked)

def main() -> gr.Blocks:
    demo = gr.Blocks()

    with demo:
        checkbox = gr.Checkbox(False)
        text_output = gr.Markdown("False")
        
        checkbox.change(
            update,
            checkbox,
            text_output,
        )

    return demo

if __name__ == "__main__":
    demo = main()
    demo.launch()
```

[Link to Demo Space](https://huggingface.co/spaces/Fanilo/gradio-sandbox)

### Screenshot

![test](https://user-images.githubusercontent.com/5351877/169658197-a2b95b03-8c2e-4bbc-8776-641988864d3f.gif)

### Logs

```shell
No logs in Python/JS
```

### System Info

```shell
Gradio 3.0.3
Windows
Firefox/Chrome latest stable
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Thanks @andfanilo, can reproduce this issue as well!

**Comment by cyyeh** [comment]
@abidlabs I am not sure if I solved the issue; anyway, I only changed one line of code in `Checkbox.svelte` from `bind:checked={value}` to `on:change={() => handle_change()}`)
