### ISSUE TITLE
Markdown visible=False is still visible

### ISSUE THREAD

**Issue by andfanilo** [gradio-app/gradio#1354]
### Describe the bug

`gr.Markdown("Text", visible=False)` still display on screen.

Wrapping it in `with gr.Group(visible=False)` does not help either 😕 

Ultimately I hope to be able to run a callback event like:

```python
def hide(checked: bool):
    return gr.Markdown.update(visible=not checked)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

def main() -> gr.Blocks:
    with gr.Blocks() as demo:
        gr.Markdown("I should be hidden :/", visible=False)

    return demo

if __name__ == "__main__":
    demo = main()
    demo.launch()
```

### Screenshot

![image](https://user-images.githubusercontent.com/5351877/169659373-0dc62b08-23cd-4102-894c-2a340fbd4adc.png)

### Logs

```shell
-
```

### System Info

```shell
Gradio 3.0.3
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thank you @andfanilo! Can reproduce the issue, and it seems to be affecting other components as well:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/1778297/169668219-e86f3a29-f310-4b8b-874c-00a05d1c1651.png">

@aliabid94 do you know about this?
