### ISSUE TITLE
Multiple inputs calling same function

### ISSUE THREAD

**Issue by sciai-ai** [gradio-app/gradio#1357]
Hi

I want to have multiple inputs (upload audio , record from mic) both of which result in a wav file that should then call the **same** function, say transcribe which only has one output called transcript. I don't see an example of this kind in the documentation.

I would like to have something along these lines with the option of having examples as well

<img width="545" alt="image" src="https://user-images.githubusercontent.com/52277510/169757460-3afdc194-7e2b-4287-b13e-438ac64b73d5.png">

**Comment by abidlabs** [comment]
Hi @sciai-ai. This is definitely possible and there are 2 options you could do here!

1) Is to create a `TabbedInterface` out of two individual Interfaces. So the process here would be to create a separate Interface for mic recording and a separate Interface for uploading an audio file and a user could select a tab to pick which Interface you want to use. See here for more info: https://gradio.app/docs/#combining_interfaces

2) To create a _single_ Interface which takes in _two inputs_: a mic recording and an audio file. Both of these inputs would be optional, and depending on which one a user passes in, you could some logic to process that audio file.

**Comment by abidlabs** [comment]
Closing, but feel free to ask any follow up questions!

**Comment by sciai-ai** [comment]
Thanks @abidlabs Is there any example I can follow for 2)
