### ISSUE TITLE
Add option for HTML `summary` for Box() and Group()

### ISSUE THREAD

**Issue by versae** [gradio-app/gradio#1358]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
When a demo has many options to tweak, it would be nice to be able to hide most of them by default.

**Describe the solution you'd like**  
It could can be easily done in HTML using `<details><summary>{label}<summary>...</details>`, which would make a nice new feature for `Box()` and `Group()`.

**Additional context**

**Comment by abidlabs** [comment]
Duplicate of #938, but I agree a very good idea!
