### ISSUE TITLE
Add component update to docs

### ISSUE THREAD

**Issue by duerrsimon** [gradio-app/gradio#1359]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
In workflows with multiple steps it might be necessary to make the user choose based on output for model 1 for subsequent models. 
Currently, the radio and dropdown fields only support changing the active value but not all the values. 

**Describe the solution you'd like**  
Like updating the textbox i'd like to be able to do the following:
```
import gradio as gr

def update(name):
    return [f'Hello {name}',f'Bye {name}', f'Good morning {name}' ]

demo = gr.Blocks()

with demo:
    inp = gr.Textbox(placeholder="What is your name?")
    out = gr.Radio(label="Greeting to use")
    
    inp.change(fn=update, 
               inputs=inp, 
               outputs=out)

demo.launch()
```

**Comment by abidlabs** [comment]
This is actually possible with `Blocks`! We still need to add documentation around it, but in your case, all you need to do is modify the return statement to use the special `.update()` method that every component defines, like this:

```py
 def update(name):
    return gr.Radio.update(choices=[f'Hello {name}',f'Bye {name}', f'Good morning {name}' ])

demo = gr.Blocks()

with demo:
    inp = gr.Textbox(placeholder="What is your name?")
    out = gr.Radio(choices=[], label="Greeting to use")
    
    inp.change(fn=update, 
               inputs=inp, 
               outputs=out)

demo.launch()
```

**Comment by duerrsimon** [comment]
Ah thanks. I tried this using `gr.radio.update(["test1", "test2"])` . Adding documentation for this would be good

**Comment by FarukOzderim** [comment]
Opening the issue until update is added to docs.

**Comment by freddyaboulton** [comment]
@abidlabs @FarukOzderim Does this issue track adding the `update` method for each component to the Docs page? 

We already added `gr.update` to the Docs page under "blocks utilities" and "Introduction to Blocks" already includes an "Updating Component Configurations" section. 

I think we should close unless we specifically want to add the `update` method for each component to the docs page.

**Comment by FarukOzderim** [comment]
It should stay open because we need to document Component.update as we have it in our library as well, even if we have it in the guides. Btw, IMO Component.update should be the suggested usage because it has autocompletion for the function parameters.
But no need to list each of them seperately, we can just show an example of it in gr.update and suggest using it since it will have parameter tracking/autocompletion.
