### ISSUE TITLE
Conversational interface processing behaviour improvements

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1360]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
No

**Describe the solution you'd like**  
If you see https://huggingface.co/spaces/Gradio-Blocks/RickandMorty-BlockParty and try it out, you can see two behaviours which are a bit unexpected to me:
* When you press enter, the input textbox also shows as loading with a queue and a timer. I would have expected that textbox to remain the same and only the chat component to change
* For a very nice experience (nice to have), instead of showing the classical loading state which removes all the chat from the screen while loading, you could have a spinner within the chat component that shows as loading. That way the experience is not broken into multiple parts

**Comment by abidlabs** [comment]
Great suggestions, fully agree!

**Comment by abidlabs** [comment]
Both of these issues are now fixed! Screenshot from the following code running on `main`:

```py
import gradio as gr
import time

def predict(input, history=[]):
    time.sleep(5)
    history = [(input, input)]
    response = [(input, input)]
    return response, history


with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    state = gr.State([])

    with gr.Row():
        txt = gr.Textbox(show_label=False, placeholder="Enter text and press enter").style(container=False)

    txt.submit(predict, [txt, state], [chatbot, state])

demo.launch()
```

<img width="589" alt="image" src="https://user-images.githubusercontent.com/1778297/218894492-829e5765-b430-4352-a9a5-0b9ca93ea13e.png">
