### ISSUE TITLE
Exclude inputs from examples

### ISSUE THREAD

**Issue by jbdel** [gradio-app/gradio#1362]
**Is your feature request related to a problem? Please describe.**  
By default _**examples**_ shows a columns for every input, even if they are empty
Even
`examples = [[i, None, None, None, None] for i in glob.glob("./images/*")]
`
or 
`examples = [[i] for i in glob.glob("./images/*")]
`
Still show empty columns for inputs at index 1,2,3 and 4

**Describe the solution you'd like**  
Sometimes we have multiple inputs, but just want examples of one input, say images. We don't want a example column for the input "how many images to generate" or "top_k" samples.

**Comment by abidlabs** [comment]
Makes sense, and shouldn't be too hard to support! @dawoodkhan82 would you be able to take a look at this as part of your examples fixes?

**Comment by sciai-ai** [comment]
A) from a ui standpoint it showed redundant inputs on the screen

B) these empty inputs actually correspond to gr.text or gr.slider abd have nothing to do with examples

**Comment by abidlabs** [comment]
It feels to me that both from a UI point of view and user intention, it would be better to exclude these inputs from showing up. The same thing was brought up in #1473

**Comment by jbdel** [comment]
> I actually think it should stay as it is, since it shows that input can or will be blank. That's an information users can make use of. ![image](https://user-images.githubusercontent.com/44067394/171200382-ca371084-e4c4-4380-8c3e-abb35dc42240.png)

I think its pretty straightforward for the user to infer that inputs will stay as it is if not mentioned in an example. Moreover, in your example, the inputs "max_length" or "num_return_sequence" will be indeed be blank, likely causing the model to crash or trigger error. 

Also, i'm not suggesting this to be the default behavior, just to add an 'exclude' option that the programmer could use.

**Comment by rnwang04** [comment]
In my case, I have two inputs : image and radio, and i just want to provide some images as examples.
But if I set the radio value to None, corresponding image can't be used and it's really inconvenient.
'exclude' option may help.
