### ISSUE TITLE
Dataframe allow Markdown or HTML content

### ISSUE THREAD

**Issue by radames** [gradio-app/gradio#1364]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**

Simple example here: https://huggingface.co/spaces/Gradio-Blocks/Leaderboard. Currently it's not possible to create hyperlinks inside a Dataframe table. I can see other use cases beyond `<a>` elements, maybe images or simple video previews?  I'm thinking that would be handy to preview rich content Dataframes outputs. I understand the performance issues with large tables, but I guess it needs lazy loading anyway.

**Comment by abidlabs** [comment]
+1!! This would be hugely useful

cc @pngwn for his thoughts
