### ISSUE TITLE
can't input Chinese in Dataframe

### ISSUE THREAD

**Issue by kev123456** [gradio-app/gradio#1366]
### Describe the bug

I can't input Chinese in Dataframe, but It works well in Textbox.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

v3.0.5

### System Info

```shell
v3.0.5 Ubuntu18 chrome 100.0.4896.127（正式版本） (x86_64)
```

### Severity

annoying

**Comment by abidlabs** [comment]
I tested this with some sample Chinese text (I think) and it's working for me. Can you let us know if you are still experiencing this issue with the latest version of `gradio`?

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Dataframe(interactive=True)
    
demo.launch()
```

<img width="675" alt="image" src="https://user-images.githubusercontent.com/1778297/178081000-7149d921-cf3b-4cbd-af7c-0ef17a3b974a.png">

**Comment by abidlabs** [comment]
Closing as this seems to work!
