### ISSUE TITLE
Add events section to docs

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1368]
- [X] I have searched to see if a similar issue already exists.

1. We do have list supported events within docs, however we do not have a doc for events. 
![image](https://user-images.githubusercontent.com/44067394/170059459-8a777768-4311-4d8d-8e5f-1689ce77e1e2.png)
- [ ] Shall we document a generic event or one example event like `change`?
- [ ] Shall we document every event [signature](https://github.com/gradio-app/gradio/blob/main/gradio/events.py), because they have different signatures?
- [ ] We could also explain what do event do, though they are quite self-explanatory with their names. 
- [ ] We could also create a matrix for components/events they support.
- [ ] Could link to the abstract classes for [events](https://github.com/gradio-app/gradio/blob/main/gradio/events.py) to explain their function signatures. 
- [ ] We could explain each abstract class and its signature in the docs as well. We could even create event-component matrix with these abstract classes. This would help community to add their own components or events.

- [ ] Alternatively we could just link from Blocks Docs to the Blocks Guide Events [section](https://gradio.app/introduction_to_blocks/#events). Though this guide is outdated and misses js within events.

WDYT @aliabd , @abidlabs?

**Comment by abidlabs** [comment]
5. Let's also make sure to document the `api_name` parameter for events

See internal discussion: https://huggingface.slack.com/archives/C02QZLG8GMN/p1658499632219329
