### ISSUE TITLE
macbook m1 chip support-incompatible architecture (have 'x86_64', need 'arm64e'))

### ISSUE THREAD

**Issue by bochuxt** [gradio-app/gradio#1369]
- [ ] I have searched to see if a similar issue already exists.
need support for macbook m1 chip

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**  
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Not found '_raw_ecb.cpython-39-darwin.so', Cannot load '_raw_ecb.abi3.so': cannot load library '/Users/conquer.io/miniconda3/envs/torch-m1/lib/python3.9/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so': dlopen(/Users/conquer.io/miniconda3/envs/torch-m1/lib/python3.9/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so, 0x0002): tried: '/Users/conquer.io/miniconda3/envs/torch-m1/lib/python3.9/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/Users/conquer.io/miniconda3/envs/torch-m1/lib/python3.9/site-packages/Crypto/Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')).  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Users/conquer.io/miniconda3/envs/torch-m1/lib/python3.9/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so', Not found '_raw_ecb.so'
(torch-m1) (⎈ |gke_dialsource-213300_us-east4_production:default)conquer.io@Conquerios-MBP pyapp % pip install "transformers[sentencepiece]"
Collecting transformers[sentencepiece]
  Downloading transformers-4.19.2-py3-none-any.whl (4.2 MB)
     |████████████████████████████████| 4.2 MB 1.6 MB/s 
Requirement already satisfied: requests in /Users/conquer.io/miniconda3/envs/torch-m1/lib/python3.9/site-packages (from transformers[sentencepiece]) (2.27.1)
Collecting filelock

------isssue

ERROR: Command errored out with exit status 1:
   command: /Users/conquer.io/miniconda3/envs/torch-m1/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/kf/tqry25hn19v0l1hj3x5c9fn00000gn/T/pip-install-2_bnj2o4/sentencepiece_f402ae9a3c80449bb1e3ceab05cab5bf/setup.py'"'"'; __file__='"'"'/private/var/folders/kf/tqry25hn19v0l1hj3x5c9fn00000gn/T/pip-install-2_bnj2o4/sentencepiece_f402ae9a3c80449bb1e3ceab05cab5bf/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/kf/tqry25hn19v0l1hj3x5c9fn00000gn/T/pip-wheel-rzzabt5r
       cwd: /private/var/folders/kf/tqry25hn19v0l1hj3x5c9fn00000gn/T/pip-install-2_bnj2o4/sentencepiece_f402ae9a3c80449bb1e3ceab05cab5bf/
  Complete output (138 lines):
  /Users/conquer.io/miniconda3/envs/torch-m1/lib/python3.9/site-packages/setuptools/dist.py:757: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(

**Comment by FarukOzderim** [comment]
Hey there, this is not related to the Gradio library but to its dependency, transformers library installation. You could search for how to install transformers library in. 
You could also try using python's pip instead of miniconda.

**Comment by abidlabs** [comment]
Thanks @bochuxt and @FarukOzderim, closing this issue. Feel free to reopen @bochuxt if you run into any issues installing gradio specifically on the macbook.

**Comment by radames** [comment]
hi @bochuxt just for context, I work on an M1 and I have no issues running the latest Gradio. Both using `arm64` or `x86_64` with `arch -x86_64`

**Comment by keunwoochoi** [comment]
hi @radames, you mean after manually installing `transformers`?
