### ISSUE TITLE
Cannot build gradio 

### ISSUE THREAD

**Issue by paulxiong** [gradio-app/gradio#1374]
### Describe the bug

I am trying to build gradio in ubuntu 20.04, I did:
> git clone https://github.com/gradio-app/gradio.git
> bash scripts/install_gradio.sh 
(above 2 were success.)
>  bash scripts/build_frontend.sh 
     ....
    > gradio-ui@0.0.1 build /home/bxiong/github-code/tmp/gradio/ui
    > pnpm build:local --filter @gradio/app --emptyOutDir
ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  not found: build:local
 ELIFECYCLE  Command failed with exit code 1.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

> git clone https://github.com/gradio-app/gradio.git
> bash scripts/install_gradio.sh 
>  bash scripts/build_frontend.sh 

### Screenshot

![image](https://user-images.githubusercontent.com/75286/170156793-d3f36460-149b-42d7-aa96-e388945db375.png)

### System Info

```shell
gradio 3.04
Ubuntu 20.04
```

### Severity

blocking all usage of gradio

**Comment by FarukOzderim** [comment]
thx for reporting @paulxiong , could you try
`npm install pnpm`

**Comment by abidlabs** [comment]
Picking up from discord, the issue here seems to be that you are using `pnpm` version 7. If you switch to `pnpm` version 6, it should work. Locally, I'm using `pnpm 6.30.1`.

See https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md as well

**Comment by paulxiong** [comment]
> Picking up from discord, the issue here seems to be that you are using `pnpm` version 7. If you switch to `pnpm` version 6, it should work. Locally, I'm using `pnpm 6.30.1`.
> 
> See https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md as well

[6.32.11 ](wget -qO- https://get.pnpm.io/install.sh | PNPM_VERSION=6.32.11 sh -) works, thank you.
