### ISSUE TITLE
Couple event triggers together

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1386]
- [X] I have searched to see if a similar issue already exists.

We might want to enable coupling event trigger together for ease of readibility within the code.
[Example ](https://huggingface.co/spaces/huggingface/library-metrics/blob/main/app.py)from @abidlabs:
```

    lib.change(get_plot, [lib, time], plt)
    time.change(get_plot, [lib, time], plt)    
    demo.load(get_plot, [lib, time], plt)    
```

My Suggestion:

```
create_events( [lib.change, time.change, demo.load], [lib,time], [plt] )
```

**Comment by abidlabs** [comment]
Upon further reflection, I think we should avoid creating another method and just let people use plain, readable Python for this:

```py
for event in [lib.change, time.change, demo.load]:
  event(get_plot, [lib, time], plt)
```

**Comment by FarukOzderim** [comment]
Agreed, but let's have an example demo for that.
