### ISSUE TITLE
Return type for empty input

### ISSUE THREAD

**Issue by datasith** [gradio-app/gradio#1388]
### No documentation exists for what specifically to return as an **output** when an interface's **input** is empty.

This normally wouldn't be a problem, except, when the `Clear` button is pressed, the function we defined for the interface is called. The question is then, what should we return in such case, which we can identify by inspecting the `input` and capturing the case where `type(input) == None`.

The `output` parameters allows for a few types, and in my case, I'm using a `dictionary` with labels (`string`) for the `key`'s and confidence scores as `value`'s. Naturally, I tried to return an empty dictionary `{}` in the case that the input was empty. This results in the error:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gradio/routes.py", line 280, in predict
    output = await app.blocks.process_api(body, username, session_state)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gradio/blocks.py", line 310, in process_api
    block.postprocess(prediction_value)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gradio/components.py", line 2650, in postprocess
    "label": sorted_pred[0][0],
IndexError: list index out of range
```

It took me a while to figure this one out, and I trust me that I tried various types of outputs, so I'm sharing in hopes that it's documented. Although this is specific to *image classification*, it might be true for other tasks as well.

```python
def classify_image_filepath(inp):
    if inp is None:
        return ''
    ...

interface = gr.Interface(fn=classify_image_filepath, 
                         ...
                         outputs=gr.Label(num_top_classes=6),
                         examples=samples)
```

Yes, that's it, we should just return an empty string. HTH!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Explained in the description of the bug.

### Screenshot

<img width="1646" alt="Screen Shot 2022-05-26 at 11 28 51 AM" src="https://user-images.githubusercontent.com/7302561/170552838-b3f23fdd-30df-4b46-8907-bb1d219c2d6a.png">

### System Info

```shell
gradio==3.0.5 

[Amazon EC2]
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
```

### Severity

annoying

**Comment by datasith** [comment]
hi @radames! thanks for the reference, they're indeed related. i found interesting that the `function` we specify for the `Interface` gets called on `clear`. one **humble** suggestion would be to handle that case separately? this is opposed to the current way where the `function` gets called with an empty `input`.

**Comment by abidlabs** [comment]
Thanks @datasith and @radames! 

There are two separate issues here:

1. Returning `{}` with an `Image` output (and logical equivalents for other output types) should clear the output. That's an easy fix I can make. (Right now, you can return `None` for every output component and it should clear it)

2. The clear button reruns the function. This should *not* happen.

In fact, I'm trying to reproduce the issue but unable to. For example, I ran:

```py
def classify_image_filepath(inp):
    return {"a": 0.1, "c": 0.1, "b": 0.1, "e": 0.1, "f": 0.1, "g": 0.1}

interface = gr.Interface(fn=classify_image_filepath, 
                         inputs=gr.Image(type="filepath"),
                         outputs=gr.Label(num_top_classes=6))

interface.launch()
```

and this behavior did not happen. By any chance, is `live=True` in your `Interface`? That's the only time it should happen

**Comment by datasith** [comment]
Thanks so much @abidlabs. You outlined the two issues very eloquently, no comments there. A small change to your code will reproduce the behavior. Remember we need to use `inp` for returning outputs of our inference, so we need to check if it is valid:

```python
def classify_image_filepath(inp):
    if inp is None:
        return {}
    return {"a": 0.1, "c": 0.1, "b": 0.1, "e": 0.1, "f": 0.1, "g": 0.1} # IRL a valid 'inp' is used here

interface = gr.Interface(fn=classify_image_filepath, 
                         inputs=gr.Image(type="filepath"),
                         outputs=gr.Label(num_top_classes=6))

interface.launch()
```

I \*think\* this occurs irrespective of `live=True`, doesn't it?

**Comment by abidlabs** [comment]
For me, this is only happens if `live=True`. Otherwise, I do not see issue (2).

We can fix issue (1) though pretty easily.

**Comment by datasith** [comment]
Thanks @abidlabs for the follow up. I've adjusted my code to indeed corroborate that this was observe with the `live=True` parameter on my end. I haven't had the chance to compare to the behavior without it, but I obviously trust your assessment on the mater.
