### ISSUE TITLE
Bring back API Docs

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#1390]
Bringing back API docs with support for both blocks and interfaces:

Backend changes:
- Adding an `api_name` parameter to event listeners. For blocks, only events with this parameter defined will be documented. For interfaces, the predict function will be documented. 
- Support the `/api/[api_name]` endpoint for events with `api_name` defined 
- Send a json with all the info required to document the endpoint to `/api/`
- Pull the documentation for components including type, samples, syntax etc from docstrings 

Frontend changes:
- Rebuild api_docs.html in svelte

**Comment by FarukOzderim** [comment]
I would like to strongly suggest using `Swagger/OpenAPI` standards that are builtin inside FastAPI, instead of building our own API docs from scratch. Which will directly make use of endpoints, validations and docstrings and you can make requests in the API page.

See [here](https://fastapi.tiangolo.com/tutorial/path-operation-configuration/?h=docs#description-from-docstring)
![image](https://user-images.githubusercontent.com/44067394/171016345-a7fc64d4-e4e3-417a-ba09-caadd2ec9b3a.png)

We can remove the endpoints we don't want to include in docs with `include_in_schema=False` flag.
`@app.get("/user", include_in_schema=False)`
![image](https://user-images.githubusercontent.com/44067394/171015678-211416b7-7f0c-4029-9b72-e1e26d79bfb0.png)
![image](https://user-images.githubusercontent.com/44067394/171015821-17896018-c22c-43fd-93e7-eb7fd3fd89ad.png)

Furthermore we can further extend the API docs, check [here](https://fastapi.tiangolo.com/advanced/extending-openapi/
)


We can document functions information related to that Blocks under the `predict` endpoint docs as well.

**Comment by FarukOzderim** [comment]
I think we should be able to generate docs for specific endpoints like `predict/fn_name` programatically, like FastAPI does. According to [1](https://fastapi.tiangolo.com/advanced/extending-openapi/#override-the-method) and [2](https://github.com/tiangolo/fastapi/blob/1876ebc77949a9a254909ec61ea0c09365169ec2/fastapi/openapi/utils.py#L388-L443). Not sure how easy it would be though, shouldn't be too hard, I think?

**Comment by FarukOzderim** [comment]
Regarding creating specific endpoints in the docs, I was able to create a minimal example like this:

![image](https://user-images.githubusercontent.com/44067394/171081629-86ca4ddb-8d01-4b37-9e9a-a68c3e0252b6.png)

```
import uvicorn
from fastapi import FastAPI
from typing import Any, Optional

from pydantic import BaseModel


class InputModel(BaseModel):
    id: int
    name: Optional[str] = None


class OutputModel(BaseModel):
    text: str


###
###

app = FastAPI()


@app.get("/login")
def login_page():
    return "Welcome"


def add_endpoints_to_app(app: FastAPI, endpoint, fn, input_model, output_model):
    @app.get(f"/predict/api/{endpoint}")
    def wrapped_fn(input: input_model) -> output_model:
        return fn(input)


def goodbye(*args):
    return "Good bye"


if __name__ == "__main__":
    add_endpoints_to_app(app, "goodbye", goodbye, InputModel, OutputModel)
    uvicorn.run(app)

```

**Comment by FarukOzderim** [comment]
There are 2 ways to do this with FastAPI/OpenAPI docs:

1. With predefined models(either provided by user, or defined inside the components)
import uvicorn
from fastapi import FastAPI
from typing import Any, Optional

from pydantic import BaseModel

import functools


class InputModel(BaseModel):
    id: int
    name: Optional[str] = None


class OutputModel(BaseModel):
    text: str


###
###

app = FastAPI()


@app.get("/login")
def login_page():
    return "Welcome"


def add_endpoints_to_app(app: FastAPI, endpoint, fn, input_model, output_model, summary="", description=""):
    @app.post(f"/predict/api/{endpoint}", response_model=output_model, summary=summary, description=description)
    @functools.wraps(fn)
    def wrapper(input: input_model) -> output_model:
        return fn(input)


def goodbye(text: str):
    return "Good bye"


if __name__ == "__main__":
    add_endpoints_to_app(app, "goodbye", goodbye, InputModel, OutputModel, summary="MVE", description="MVE description")
    uvicorn.run(app)
![image](https://user-images.githubusercontent.com/44067394/171851304-f2eeeddc-3004-455f-90e6-88d20d67f31b.png)

**Comment by FarukOzderim** [comment]
This is the Minimum Viable Example:

## With IO models provided
```

if __name__ == "__main__":
    add_endpoints_to_app(app, "goodbye", goodbye, InputModel, OutputModel, summary="MVE", description="MVE description")
    uvicorn.run(app)

```
![image](https://user-images.githubusercontent.com/44067394/171853021-a1b38d25-612f-443e-a569-a221ea402cc7.png)

## Without IO Models
Fetches input and output from function type_hints
```
if __name__ == "__main__":
    add_endpoints_to_app(app, "goodbye", goodbye, None, None, summary="MVE", description="MVE description")
    uvicorn.run(app)
```
![image](https://user-images.githubusercontent.com/44067394/171852933-91ad8463-7cd4-4f63-b959-73dce7855dfd.png)


```
import inspect
import typing

import uvicorn
from fastapi import FastAPI
from typing import Any, Optional

from pydantic import BaseModel

import functools


class InputModel(BaseModel):
    id: int
    name: Optional[str] = None


class OutputModel(BaseModel):
    text: str


###
###

app = FastAPI()


@app.get("/login")
def login_page():
    return "Welcome"


def add_endpoints_to_app(app: FastAPI, endpoint, fn, input_model=None, output_model=None, summary="", description=""):
    if output_model is None:
        fn_signature = typing.get_type_hints(fn)
        if 'return' in fn_signature.keys():
            output_model = fn_signature['return']

    if input_model is None:
        @app.post(f"/predict/api/{endpoint}", response_model=output_model, summary=summary, description=description)
        @functools.wraps(fn)
        def wrapper(input):
            return fn(input)
    else:
        @app.post(f"/predict/api/{endpoint}", response_model=output_model, summary=summary, description=description)
        def wrapper(input: input_model):
            return fn(input)


def goodbye(text: str) -> str:
    return "Good bye"
```
