### ISSUE TITLE
gradio 3.0.6 examples parameter bug

### ISSUE THREAD

**Issue by Zengyf-CVer** [gradio-app/gradio#1395]
### Describe the bug

@abidlabs 
Using the examples parameter in gradio 3.0.6 reports an error:

Code in README.md:
```python
import gradio as gr

def calculator(num1, operation, num2):
    if operation == "add":
        return num1 + num2
    elif operation == "subtract":
        return num1 - num2
    elif operation == "multiply":
        return num1 * num2
    elif operation == "divide":
        return num1 / num2


demo = gr.Interface(
    calculator,
    [gr.Number(4), gr.Radio(["add", "subtract", "multiply", "divide"]), "number"],
    "number",
    examples=[
        [5, "add", 3],
        [4, "divide", 2],
        [-4, "multiply", 2.5],
        [0, "subtract", 1.2],
    ],
    title="test calculator",
    description="heres a sample toy calculator. enjoy!",
    flagging_options=["this", "or", "that"],
)

if __name__ == "__main__":
    demo.launch()

```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

![ksnip_20220527-084305](https://user-images.githubusercontent.com/41098760/170606280-dd0ec067-d1e5-4cb4-97b2-e938e9312a99.png)

### System Info

```shell
gradio 3.0.6
ubuntu 20.04
chrome
```

### Severity

annoying

**Comment by hysts** [comment]
I encountered the same issue. Personally, I would choose the severity of `blocking upgrade to latest gradio version`.

**Comment by Zengyf-CVer** [comment]
@hysts 
gradio 3.0.9 solves this problem

**Comment by hysts** [comment]
@Zengyf-CVer Thanks!
