### ISSUE TITLE
Document pypi releases

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1396]
- [X] I have searched to see if a similar issue already exists.

We should document releasing and do it more frequently in cases like #1392.

**Comment by FarukOzderim** [comment]
> Agree with the sentiment, but is there an actual issue we can close here @FarukOzderim?
Sorry could not understand what you mean? 

I think we have automation for pypi releases now, we can document how to trigger it on notion and close this issue?

**Comment by abidlabs** [comment]
Oh I see what you mean now. The issue was unclear to me -- I thought you were saying we should add more documentation (release notes) for each of our releases.

**Comment by abidlabs** [comment]
Added steps here, thanks for the suggestion: https://github.com/gradio-app/gradio/wiki/How-to-deploy-Gradio-to-Pypi-using-GitHub-actions
