### ISSUE TITLE
Gradio Reload mode does not work with HF models

### ISSUE THREAD

**Issue by satpalsr** [gradio-app/gradio#1403]
### Describe the bug

I tested out the new Gadio reload mode in the colab notebook. It works fine for small python examples, but does not generate output with hugging face models. I am sharing a reproducible example with BERT.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

[Reproduce in Colab](https://colab.research.google.com/drive/1ljVJ5gLPOo3ZGHTuDx1UfG2IcPXewhxa?usp=sharing)

Install requirements
```
!pip install gradio
!pip install transformers
```
Code:
```
%load_ext gradio
%%blocks

import gradio as gr

import torch
from transformers import BertTokenizer, BertForQuestionAnswering

tokenizer = BertTokenizer.from_pretrained("deepset/bert-base-cased-squad2")
model = BertForQuestionAnswering.from_pretrained("deepset/bert-base-cased-squad2")

def ques_ans(question, text):

  inputs = tokenizer(question, text, return_tensors="pt")
  with torch.no_grad():
      outputs = model(**inputs)

  answer_start_index = outputs.start_logits.argmax()
  answer_end_index = outputs.end_logits.argmax()

  predict_answer_tokens = inputs.input_ids[0, answer_start_index : answer_end_index + 1]
  response = tokenizer.decode(predict_answer_tokens)
  
  return response

gr.Interface(ques_ans, inputs=["text", "text"], outputs="text")

# Example:
# question: What is the name?
# text: My name is James.

```

### System Info

```shell
Gradio version: 3.0.6
```

### Severity

serious, but I can work around it

**Comment by FarukOzderim** [comment]
Hmm, using HF models should not be affecting it, @abidlabs could there be some problems with colab reload?

**Comment by abidlabs** [comment]
Hi @satpalsr can confirm the issue. Let me look into it!
