### ISSUE TITLE
运行后立即被迫终止，终端输出了<IPython.lib.display.IFrame at

### ISSUE THREAD

**Issue by ixNeo** [gradio-app/gradio#1409]
### Describe the bug

<img width="400" alt="image" src="https://user-images.githubusercontent.com/29992953/170821160-04f4e98b-11fb-4a92-a69d-ac20dce539cb.png">

我怀疑是gradio和其他cv2等包冲突了，但不知道如何解决

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

无法创建链接，一旦运行就被迫终止

### System Info

```shell
gradio 2.6.2
电脑 mac
```

### Severity

blocking all usage of gradio

**Comment by FarukOzderim** [comment]
Let me provide the google translate version below.
Thx for the report @ixNeo, gradio's latest version is 3.0.7, I recommend you to update Gradio version. 
If you still meet with this problem can you also provide reproduction and logs? We are unable to find the problem with this report.

```

Describe the bug

image

I suspect that gradio is conflicting with other packages such as cv2, but I don't know how to solve it
Is there an existing issue for this?

    I have searched the existing issues

Reproduction

Failed to create link, forced to terminate once running
Screenshot

No response
Logs

No response
System Info

gradio 2.6.2
电脑 mac

Severity

blocking all usage of gradio

```
