### ISSUE TITLE
Defining inputs/outputs as str don't work with Blocks

### ISSUE THREAD

**Issue by satpalsr** [gradio-app/gradio#1418]
### Describe the bug

Using string for defining inputs/outputs does not work with Gradio Blocks.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

This does not work.
```
import gradio as gr

def predict(input):
  return input

demo = gr.Blocks()

with demo:
  input = "text"
  output = "text"

  button = gr.Button("Submit")
  button.click(predict, input, output)

demo.launch(debug=True)
```

To make this work:
```
input = gr.Textbox()
output = gr.Textbox()
```

### Logs

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-17148026eb84> in <module>()
     11 
     12   button = gr.Button("Submit")
---> 13   button.click(predict, inputs=input, outputs=output)
     14 
     15 demo.launch(debug=True)

2 frames
/usr/local/lib/python3.7/dist-packages/gradio/blocks.py in <listcomp>(.0)
    118                 "targets": [self._id] if not no_target else [],
    119                 "trigger": event_name,
--> 120                 "inputs": [block._id for block in inputs],
    121                 "outputs": [block._id for block in outputs],
    122                 "backend_fn": fn is not None,

AttributeError: 'str' object has no attribute '_id'
```

### System Info

```shell
3.0.9, Google Colab
```

### Severity

annoying

**Comment by pngwn** [comment]
This is by design, I've switched this to a feature request.

**Comment by FarukOzderim** [comment]
@satpalsr  We support shortcuts in Blocks with 

`gr.component("text")`

Check [here](https://github.com/gradio-app/gradio/blob/main/demo/blocks_component_shortcut/run.py)

**Comment by abidlabs** [comment]
Yes, the reason for this change @satpalsr is because you can define regular variables inside of a block context. So `input = "text"` could mean either the `"text"` component, or a variable called "text". We'd like to allow you to use regular Python syntax inside of a block context, so we've defaulted to the latter. If you need to get a component via its string shortcut, you can use the approach @FarukOzderim has suggested.
