### ISSUE TITLE
Add open source stack to homepage and readme

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1419]
- [X] I have searched to see if a similar issue already exists.

Having a list of our open source stack in our website and Github Readme would be very nice(with logos if possible), we would have both supported and given credits to those open source projects.

- [x] readme
- [ ] webpage

We could add each logo to the top of the README in this order and add in website either before or after Used by(except gradio logo)

- gradio
- huggingface
- python
- fastapi
- encode/uvicorn
- encode/httpx
- svelte
- vite
- pnpm
- tailwind

**Comment by abidlabs** [comment]
Looks like this is done now!

**Comment by FarukOzderim** [comment]
I don't think we have logos in the `webpage` yet

**Comment by freddyaboulton** [comment]
What's a good place to put the logos on the website? 

IMO the gradio.app landing page is not the best place.

Maybe we can add a section to the `Contributing.md` page about "Contribute to gradio by supporting the tools that power gradio" like in FastAPI

![image](https://user-images.githubusercontent.com/41651716/180834788-d44a8baf-4b63-4185-a667-7634ede0176f.png)


And then add the contributing.md page as a guide?

**Comment by FarukOzderim** [comment]
Hmm, landing page looks good to me. What is your concern about it Freddy?

It would sit below or above used by well imo.
<img width="1964" alt="image" src="https://user-images.githubusercontent.com/44067394/180835914-a7fdf17e-8f34-4ace-b179-9d151ee42fa0.png">

**Comment by FarukOzderim** [comment]
Btw I collected icons to the repo, we may make use of that.
https://github.com/gradio-app/gradio#open-source-stack

**Comment by freddyaboulton** [comment]
I think the landing page should be focused on convincing visitors to use gradio in as few words (and vertical space) as possible and I think the open source logos don't contribute to that.

If the goal of adding the open source stack is to give thanks to those maintainers and channel some of gradio's success to those libraries then I think we should find another place to do so. I think the contributing page could be a good place to do so.

**Comment by abidlabs** [comment]
> I think the landing page should be focused on convincing visitors to use gradio in as few words (and vertical space) as possible and I think the open source logos don't contribute to that.

Yup let's keep the landing page as focused as possible. We used to have a line of logos listing all of the libraries that Gradio interoperates well with (TensorFlow, PyTorch, HF). If anything, we can bring these logos back because they create a sense of familiarity for potential users of Gradio. I don't think there is much value in having the open-source stack logos on the website.

**Comment by freddyaboulton** [comment]
After discussing with the team we are going to close this out because we agree listing the open source stack on the readme is sufficient.
