### ISSUE TITLE
Update logo of the organization in Github

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1420]
- [X] I have searched to see if a similar issue already exists.

I had no access rights on this, this can be changed within settings in https://github.com/gradio-app, see 
https://docs.github.com/en/enterprise-server@3.4/organizations/organizing-members-into-teams/setting-your-teams-profile-picture

Old logo:
![image](https://user-images.githubusercontent.com/44067394/171026092-c5526f5e-a8c9-4b13-946a-ce7c03116b23.png)

New logo:
![image](https://user-images.githubusercontent.com/44067394/171026063-62269bd4-a580-4fe3-b889-82a0b24f13fd.png)

**Comment by abidlabs** [comment]
Updated. (To just the logo part, otherwise looks too small)
