### ISSUE TITLE
Interface Preview in Saved Notebooks

### ISSUE THREAD

**Issue by merveenoyan** [gradio-app/gradio#1429]
When I save a colab notebook or any notebook that has Gradio UI, below shows up instead of a preview of a UI. That would be nice to save a preview of UI even if it doesn't run. 
<img width="967" alt="Ekran Resmi 2022-05-31 14 38 11" src="https://user-images.githubusercontent.com/53175384/171175005-befafd20-86b3-4692-9310-9db444926e7a.png">
Also in kaggle I get below.
<img width="986" alt="Ekran Resmi 2022-05-31 14 39 01" src="https://user-images.githubusercontent.com/53175384/171175188-cf502189-5dcd-4882-9cc3-1cb0238243fc.png">

It's probably not high priority but a veeeery nice to have 🙂 
cc @osanseviero since we discussed it.

**Comment by FarukOzderim** [comment]
Hmm, it would be not that critical but nice to have. Can't think of a way on doing that immediately, do you guys have any idea on how to do it? @merveenoyan, @osanseviero, @abidlabs?

**Comment by merveenoyan** [comment]
I think it's good, given even if we want it to be adopted on Kaggle someone who comes across this for the first time will not be able to understand what it's used for (nor for Colab, so it causes loss in getting people on board sort of)

**Comment by radames** [comment]
curious @abidlabs, would be possible to run Gradio Interface inside the notebooks without the proxy?

**Comment by abidlabs** [comment]
Ah so without the ssh tunnel / public URL? We haven't been able to figure out how to expose the local host inside notebook environments without using the ssh tunnel / public URL. I'm pretty sure its impossible, but would love to be proven wrong if you have any ideas @radames

**Comment by FarukOzderim** [comment]
@abidlabs do you know why sharing is [default ](https://github.com/gradio-app/gradio/blob/7e796a3e171191a2a0a0ab48fe19b02cde0d9777/gradio/blocks.py#L636)in colab notebooks? Because it is more handy?

**Comment by abidlabs** [comment]
Because of the reason I mentioned above. Basically, the Interface runs locally on colab machine's port 7860, but that port is not exposed to users. We haven't been able to figure out how to expose the local host inside notebook environments without using the ssh tunnel / public URL / share=True.

**Comment by FarukOzderim** [comment]
What I actually meant was, we could have share off in Colab by default as well, like in local case.

**Comment by abidlabs** [comment]
Ah that was the default behavior initially, but then people would click on the localhost link expecting to see the Interface, and it was not visible. That's why we made it `share=True` on colab. We should probably make it so that people can turn `share=False` in colab if they want (currently it forces `share=True`), we have an upcoming contribution that will do this: #1371

**Comment by merveenoyan** [comment]
In Kaggle it currently looks like this for 72 hours thanks to sharing: 
![Ekran Resmi 2022-09-15 17 28 34](https://user-images.githubusercontent.com/53175384/190444928-c7b0e9a0-5058-41cc-abdc-6b26850b20be.png) (I haven't checked how it'll look after 72 hours so correct me if I'm wrong 😅)
I was wondering if we could put a preview of the interface after 72 hours, would this work? @freddyaboulton @abidlabs

**Comment by freddyaboulton** [comment]
This feels very niche and it's been quite stale now. But if someone wanted to open a PR for this it could be a nice QoL improvement for notebook users.
