### ISSUE TITLE
Distinguish between user-triggered events and gradio-triggered events

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1431]
### Describe the bug

Created a hacky blocks party space for fun, but did not work as intended, creates infinite recursion with events triggering each other. 
Question: Is there a way we can avoid this? @aliabid94, @pngwn 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/Gradio-Blocks/Hacky-Blocks-Party

### Screenshot

![image](https://user-images.githubusercontent.com/44067394/171199697-b09b0125-0549-4b4f-98c8-08b2d53de329.png)

### Logs

```shell
No logs
```

### System Info

```shell
spaces
```

### Severity

annoying

**Comment by pngwn** [comment]
What would you expect to happen here? It looks like you've explicitly coded the recursion in.

**Comment by FarukOzderim** [comment]
I actually didn't expect that the events were going to trigger each other. Thought changes other than the user made in the UI were not triggering the events.

**Comment by abidlabs** [comment]
I think we can close this issue now. We now support this for many components using `.select()` event trigger (which only fires if a user manually selects an option). We can also only fire an event if there's a programmatic change to a value using `.then()`. 

Haven't seen any real-world use cases of the kind of recursion described in the issue above. But even that can be achieved (albeit in a somewhat hacky way) using `cancels`: 

```py
import gradio as gr

with gr.Blocks() as demo:
    a = gr.Textbox()
    b = gr.Textbox()
    
    ev1 = a.change(lambda x:x, a, b)
    ev2 = b.change(lambda x:x, b, a)
    a.change(None, None, None, cancels=ev2)
    b.change(None, None, None, cancels=ev1)
    
demo.queue().launch()
```

**Comment by aliabid94** [comment]
This is not resolved, will fix now
