### ISSUE TITLE
Inconsistent design between file input component and file output component

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#1435]
### Describe the bug

The file component looks a little different when used as an input (top) or an output (bottom):

<img width="590" alt="image" src="https://user-images.githubusercontent.com/1778297/171311283-11679ad9-442d-4713-8bbc-da3d4ca23f2c.png">

We should unify the designs of the components -- I'm in favor of the input component design

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```py
import gradio as gr

with gr.Blocks() as demo:
    i = gr.File()
    o = gr.File()
    i.change(lambda x:x.name, i, o)
  
demo.launch()
```

### Logs

```shell
N/A
```

### System Info

```shell
gradio==3.0.9
```

### Severity

annoying

**Comment by satpalsr** [comment]
Hey @abidlabs , The input/output window size for an image is also quite different. ALso, the two images in the space here have different output sizes. The output size for the first image is quite large in my opinion. [Space example](https://huggingface.co/spaces/satpalsr/example-test)
