### ISSUE TITLE
Create Supported versions badge

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1438]
- [X] I have searched to see if a similar issue already e

Will be helpful for people to understand which versions they can use gradio with. Let's add supported versions to pypi and add a badge to readme like below. @abidlabs you have access to pypi right?
I think we currently support 3.7,3.8.3,9

![image](https://user-images.githubusercontent.com/44067394/171338338-0c1457d3-dce8-4dad-83f3-5b677fd0aef2.png)
https://github.com/tiangolo/fastapi

**Comment by abidlabs** [comment]
Sure sounds good!
