### ISSUE TITLE
 Logos/Brand-assets page

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1441]
- [X] I have searched to see if a similar issue already exists.

I think having a Logos/Brand-assets page would be quite beneficial for Gradio as well. Having a page in gradio.app/logos or gradio.app/brand-assets would help people to find HF logos, and add the logo to their projects or webpages, or make use of it. 

See
https://www.python.org/community/logos/

From @gary149:
>I like the idea of having a brand assets page, for journalists, users or else
    https://stripe.com/en-fr/newsroom/brand-assets

Some logos in slack:
https://huggingface.slack.com/archives/C02SPHC1KD1/p1653925822259319?thread_ts=1653925227.550799&cid=C02SPHC1KD1

Related Slack discussion thread:
https://huggingface.slack.com/archives/C01NW5NTBMF/p1654065092962689

We could even add Gradio tshirts and cups on the same page in the future as well :)

**Comment by aliabd** [comment]
Closed this issue as we have not received enough user requests for this

**Comment by pngwn** [comment]
We could potentially do this when we document the 'design system' which we will need to do when we are explaining how to make custom components that are consistent with the rest of a Gradio app.
