### ISSUE TITLE
Contact | Security Issue

### ISSUE THREAD

**Issue by wsmi22** [gradio-app/gradio#1445]
### Describe the bug

Dear Gradio contributors,

I've tried to contact you through the email found in your security policy, but got no response.
Please get back to me at: [vulnerability@mend.io](mailto:vulnerability@mend.io) or [miriam.iomin@mend.io](mailto:miriam.iomin@mend.io)
It's about a security issue found in your project.

Thanks,
Miriam

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

security issue

### Logs

```shell
security issue
```

### System Info

```shell
security issue
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Found your email -- will discuss through email. Thank you @wsmi22!
