### ISSUE TITLE
How put deployment ml model on server

### ISSUE THREAD

**Issue by nurkbts** [gradio-app/gradio#1462]
I want to integrate my deep learning model that I have created into a server and test it with client inputs. First of all, how can I deploy my model and how can I add this deploy to the server?

My goal: to make a server that hosts deep learning models.

**Comment by FarukOzderim** [comment]
Hello!

You can host your Gradio application anywhere(one option is Hugging Face Spaces), and use /api/predict/ endpoint, you can check the docs for that.

(cc: @aliabid94 for being sure)
