### ISSUE TITLE
The interface hangs when it returns several large videos

### ISSUE THREAD

**Issue by jaelgu** [gradio-app/gradio#1463]
### Describe the bug

Hi, this is my function & interface:

```
import gradio

def test(path):
    return path.split(',')

interface = gradio.Interface(test, 
                             inputs=gradio.Textbox(lines=1),
                             outputs=[gradio.Video(format='mp4') for _ in range(2)]
                            )


interface.launch(inline=True, share=True)
```

I use 2 video paths combining with `,`  as input. When each video is small (<1M), I can get proper results in interface. However, when videos are large (eg. 1M for each), then the system hangs forever (I've waited 500 secs).

So is there some memory limit by gradio?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See above.

### Logs

```shell
No error.
```

### System Info

```shell
gradio 3.0.9
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Hi @jaelgu closing due to lack of information. Please feel free to reopen if this is still an issue

**Comment by arnavmehta7** [comment]
He is right

**Comment by arnavmehta7** [comment]
I just had a code, which returns a image of around 4mb size while the input image size had been around 500kbs. The first image shows up perfectly, but all the others after the first, take around 2 minutes to be shown.
