### ISSUE TITLE
Changing tabs between TabbedInterface leads to seeing an interface twice

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1470]
### Describe the bug

I'm in a tabbed interface Space, the first tab being an input-less interface. I generate the bokeh map with it, then I switch to another tab. When I switch back, I see the map twice

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/osanseviero/hugging_eats

1. Click generate
2. Switch to second tab
3. Switch back to first tab

I now see the map twice

### Screenshot

![Screenshot from 2022-06-07 09-21-36](https://user-images.githubusercontent.com/7246357/172320313-386d213e-9845-482a-bba5-16437f15d9c5.png)

### Logs

```shell
Nothing of interest
```

### System Info

```shell
Chrome, 3.0.12
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
@abidlabs I think we should remove from the 3.1 milestone. The bokeh plots are broken and will not be fixed until version 3.0.0 is released (see discussion on https://github.com/gradio-app/gradio/pull/1609).

I am able to repro @osanseviero's problem on gradio version 3.0.12 but we won't be able to do anything about it until the new bokeh version is out.

**Comment by abidlabs** [comment]
Ah interesting, thoughts on printing a warning to `gradio` users to upgrade their bokeh to `3.0.0dev8` or higher if they use a bokeh plot?

**Comment by abidlabs** [comment]
I think we should close this issue because we need to reimplement support Bokeh plots anyways (#1942) and if we reimplement it correctly, this should not be a problem. What do you think @dawoodkhan82?

**Comment by dawoodkhan82** [comment]
> I think we should close this issue because we need to reimplement support for Bokeh plots anyways (#1942) and if we reimplement it correctly, this should not be a problem. What do you think @dawoodkhan82?

Yeah Agreed.
