### ISSUE TITLE
See docs for complete list not found

### ISSUE THREAD

**Issue by Keiku** [gradio-app/gradio#1471]
The following link in `README.md` cannot be found.

> Gradio includes more than 20 different components, most of which can be used as inputs or outputs. ([See docs for complete list](https://github.com/gradio-app/gradio/blob/main/docs))

<img src="https://user-images.githubusercontent.com/199433/172330196-45ce3fa5-f61a-409a-af22-df9fc30f961a.png" width="600px">

**Comment by aliabd** [comment]
Thanks for opening the issue @Keiku 

The correct link is [https://gradio.app/docs](https://gradio.app/docs)

Will fix the README

**Comment by Keiku** [comment]
Thank you for referring to the correct link. I will study about Gradio from now on.
