### ISSUE TITLE
can example only contain part of  the input?

### ISSUE THREAD

**Issue by rnwang04** [gradio-app/gradio#1473]
My inputs of gradio.interface contain a Image and a Radio.
But in examples, I only wnat to provide several images, and let user choose Radio option.

**Describe the solution you'd like**  
Is there any way to achieve it ?

**Comment by abidlabs** [comment]
Makes sense, thanks @rnwang04. We'll work on this, but closing the issue for now since it looks like to me that it is the same as #1362.
