### ISSUE TITLE
Changing the Size of Displayed Input or Output Images

### ISSUE THREAD

**Issue by rnwang04** [gradio-app/gradio#1474]
Hello, here I have a fn, which will return four outputs, and two of them are images. The output side of my screen cannot put down two complete output images at the same time.
I don't want to change the shape attribute of output Image, I just want the output image display smaller.

**Describe the solution you'd like**  
I wonder if there are any solution to modify the layout of output Image? For example, display the output image at a scale of 50% ？

**Comment by abidlabs** [comment]
Hi @rnwang04, thanks for the feature request. One way to do this would be to write your own `css` and pass it into the `css` parameter of the `Interface` class. This is discussed here: https://github.com/gradio-app/gradio/issues/287

However, we will also work on making this easier, without having to write custom css. Thanks!

**Comment by abidlabs** [comment]
Closing this issue as we are discussing a non-css approach in #1561. Thanks @rnwang04!
