### ISSUE TITLE
Live Stream Video in gradio  

### ISSUE THREAD

**Issue by tomriddle54** [gradio-app/gradio#1475]
Can we use streams like Mjpeg, rtsp, to do infrence?
For example getting feed from cctv camera as mjpeg and do inference on that video live is this possible ?

**Comment by abidlabs** [comment]
Hi @tomriddle54 good question. Can add some more details on how this would work? How would you input the mjpeg live into your browser? Would it be through a webcam-type device?

**Comment by tomriddle54** [comment]
Thanks for the replay @abidlabs  mjpeg stream is from the Cctv camera 
The plan is to display cctv feed on gradio as output
