### ISSUE TITLE
Gradio doesn't work with Heroku

### ISSUE THREAD

**Issue by voltek62** [gradio-app/gradio#148]
Hello, 

I followed your tutorial on Medium.

But I have a conflict with the new version of Gradio.
![Capture du 2021-04-17 12-45-56](https://user-images.githubusercontent.com/2698956/115110296-e9aa2300-9f7a-11eb-9086-60d3addd442c.png)

I tried to add a file runtime.txt to change my python version but no result.

You project is excellent and  I think Heroku + Gradio is an excellent solution.

Could you help me ?

**Comment by abidlabs** [comment]
Thanks @voltek62 we're looking into it and we'll get back to you as soon as we can!

**Comment by abidlabs** [comment]
Just wanted to give you a quick update -- I've been able to reproduce this issue. Am currently investigating it, will update you when I have a solution

**Comment by voltek62** [comment]
Thanks for the update, I hope you can find a solution.

**Comment by abidlabs** [comment]
Sorry for the delay @voltek62 but we ended up rewriting the gradio library to remove the conflicting dependencies. With the latest version of Gradio (1.7.7), the Heroku tutorial works! Thanks again
