### ISSUE TITLE
Bug when creating a Gradio application for models on the Hugging Face Hub

### ISSUE THREAD

**Issue by mfumanelli** [gradio-app/gradio#1481]
### Describe the bug

Hi, I am trying to create a very simple named entity recognition application from a model on the Hub of Hugging Face. Once the application is created it works for the first sentence that is entered, for subsequent examples two things happen (alternately):

- the application remains in buffering indefinitely
or:
- a prediction is indeed displayed but always on the first example entered.

I have tried searching but have not found any issues related to this problem. I will try to see if I can figure out what it is caused by, however, I would not want it to be a problem that I only experience. I have tried on both colab and my personal pc and on both places I encounter the bug. I also tried choosing different models, but nothing changed.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

demo = gr.Interface.load("huggingface/xlm-roberta-large-finetuned-conll03-english",
             title="Token Classification")
demo.launch(share=True)
```

### Screenshot

First sentence entered:
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/53374883/172471577-fd5bfd52-6a61-42d8-a306-8dbc28a29891.png">

Second sentence entered:
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/53374883/172471849-ca1d1e2d-b002-4f8e-9f03-983fb1ac8732.png">

### Logs

```shell
--
```

### System Info

```shell
Gradio==3.0.12
Python==3.7.13 on colab and 3.9.7 locally
SO==macOS Monterey
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Thanks @mfumanelli for raising the issue and @freddyaboulton for the quick diagnosis. Yes, this would probably explain it. We are also working on better error reporting in the frontend (#956)

cc @aliabid94

**Comment by mfumanelli** [comment]
Thanks @freddyaboulton ❤️ Perfect for improving error reporting in the front end, if you agree we can close the issue. Thanks @abidlabs 🌈

**Comment by abidlabs** [comment]
Yes sounds good, we'll work on the error reporting!
