### ISSUE TITLE
How can I provide examples in gr.Blocks() ? 

### ISSUE THREAD

**Issue by rnwang04** [gradio-app/gradio#1485]
When I use gr.Blocks() , I wonder how can I provide examples like gr.Interface ?

**Comment by abidlabs** [comment]
To see an example of how to use examples with Blocks, please check out this Space: https://huggingface.co/spaces/Gradio-Blocks/gen-code-comparer

We are working on making that possible more easily here: see #1156

**Comment by halqadasi** [comment]
> To see an example of how to use examples with Blocks, please check out this Space: https://huggingface.co/spaces/Gradio-Blocks/gen-code-comparer
> 
> We are working on making that possible more easily here: see #1156

The link does not work, I got this: 
```

Runtime error
Scheduling failure: not enough hardware capacity
```
