### ISSUE TITLE
CSS doesn't seem to be working in gradio 3.0.13

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#1487]
### Describe the bug

CSS doesn't seem to be working in gradio 3.0.13.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

gradio 3.0.13 https://huggingface.co/spaces/hysts/_sample_001
gradio 3.0.11 https://huggingface.co/spaces/hysts/_sample_002

### Logs

```shell
Running on local URL:  http://localhost:7860/

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
gradio 3.0.13
```

### Severity

annoying

**Comment by abidlabs** [comment]
Yup @pngwn this looks like it might be related to web components, since we introduced that in 3.0.12.
