### ISSUE TITLE
What is the right way of returning matplotlib figure

### ISSUE THREAD

**Issue by tirthajyoti** [gradio-app/gradio#149]
You have at least three type of code examples for returning a figure. Which one is to be followed?

```
plt.scatter(x,y)
return plt
```
- This one is highly suspicious. Returning the `plt` which is imported as a module?

```
plt.close()
return fig
```
- will this one return any data after closing the plot?

```
fig = plt.figure()
plt.scatter(x,y)
return fig
```
- this one seems to be the right one but have you tested it working because I am getting errors with a histogram. The function is running but not returning anything for a long time and therefore forced to kill at some point.

**Comment by abidlabs** [comment]
This is a good question @tirthajyoti, we'll consolidate and have a consistent way of returning a plt figure. Let us look into this and get back to you soon

**Comment by sambhugit** [comment]
"return plt" worked for me. I tried plt.figure() but I couldnt see any image.

**Comment by thelou1s** [comment]
> "return plt" worked for me. I tried plt.figure() but I couldnt see any image.

Hi, what do you mean by 'return plt', while my code is error. thx:


```
def plt_waveform(signal):
	plt.figure(1)
	plt.title("Signal Wave...")
	plt.plot(signal)
	# plt.show()
	return plt
```


```
/Users/luis/PycharmProjects/yamnet_test/test.py:146: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
1.00 [Sile], 0.00 [Spee], 0.00 [Musi], 
  plt.figure(1)
```

**Comment by freddyaboulton** [comment]
Seems like a warning and not an error @thelou1s. gradio will safely display the plot outside the main thread.
