### ISSUE TITLE
auth_message does not show on login page

### ISSUE THREAD

**Issue by dboshardy** [gradio-app/gradio#1491]
### Describe the bug

According to the docs, `auth_message` should "If provided, HTML message provided on login page."

However, when I add this when launching the app, nothing shows on the login page.  
```python
 demo.launch(auth_message="This is my custom auth message.", auth=('admin', '123'))
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Add `auth_message` as named param to `.launch()`

### Screenshot

<img width="842" alt="Screen Shot 2022-06-08 at 10 50 56 AM" src="https://user-images.githubusercontent.com/2131537/172661456-235b407f-fa4f-4ae6-9bd6-19369ce76ed8.png">

### Logs

```shell
Running on local URL:  http://127.0.0.1:7861/

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
gradio==3.0.9
Chrome
macOS Monterey 12.2.1
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks @dboshardy I think this broke in our 3.0 release. We'll work on bringing this back. 

cc @aliabid94
