### ISSUE TITLE
Add way to stop the the input stream when using gr.Image streaming.

### ISSUE THREAD

**Issue by nateraw** [gradio-app/gradio#1492]
**Is your feature request related to a problem? Please describe.**  
When using gr.Image for streaming like this:

```python
import gradio as gr

gr.Interface(lambda x: x, gr.Image(source='webcam', streaming=True), "image", live=True).launch()
```

There is no way to stop the app from running, it just keeps going until you close the tab.

**Describe the solution you'd like**  

It would be nice to hit a button to have the app stop streaming inputs, similar to how the audio streaming feature works.

**Comment by JefferyChiang** [comment]
#1323

**Comment by abidlabs** [comment]
Thanks for flagging the duplicate @JefferyChiang. Will close this issue and keep yours open until we can fix it!
