### ISSUE TITLE
Enable API docs link (view the api 🔧)

### ISSUE THREAD

**Issue by radames** [gradio-app/gradio#1495]
I'm sure you're working on the new fresh API Docs feature since it was re-enabled on the latest release.

Related to this discussion of [HF discuss](https://discuss.huggingface.co/t/get-the-view-api-link-to-show-up-at-the-bottom-of-my-page/18826), one person was missing the **View API** link on the bottom of Gradio App as before. I've guided them to the latest release and how to fetch the `POST` endpoint

<img width="451" alt="image" src="https://user-images.githubusercontent.com/102277/172692318-29e0df41-0c1f-44fc-82c1-50948d989445.png">

**Comment by abidlabs** [comment]
Thanks so much @radames -- just to confirm, the view api link should now be back as of the latest gradio release (3.0.13)!

(Please let me know if I misunderstood)

**Comment by radames** [comment]
hi @abidlabs you're totally right the view api button is enabled on 3.0.13 thanks
