### ISSUE TITLE
Flagging UX redesign

### ISSUE THREAD

**Issue by charlesfrye** [gradio-app/gradio#1496]
### Describe the bug

I love the flagging feature as a way to collect quick feedback from users about model behavior. It becomes even more useful when that feedback is non-binary and custom, as when using `flagging_options`. Serious model evaluation and retraining workflows require feedback of at least this granularity.

But it seems that in `gradio>=3`, the `flagging_options` parameter is not being respected. I originally ran into this on my own app, but I was able to recreate it for the calculator example in the [flagging guide](https://gradio.app/using_flagging/). See the reproduction section.

Specifically, the dropdown arrow does not appear on the "Flag" button, and so there is no way to select an option. Instead, the button behaves exactly as if the `flagging_options` argument is not set. The `flag` column still appears in the `log.csv`, but it is always empty.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Reproducing Colab Notebook: https://colab.research.google.com/drive/1Xf05scd6t-R20hP1tyLg7Q8IbWUCSegQ?usp=sharing

### On gradio website (or on Colab in gradio<3), we see the flagging options
![image](https://user-images.githubusercontent.com/10442975/172723851-b17325d1-8912-4db4-aab5-bf254422a378.png)

### Running on Colab (with gradio>=3), there are no flagging options
![image](https://user-images.githubusercontent.com/10442975/172722524-ec96c92a-0926-4fdc-bbbd-f82f46cd564a.png)

### Logs

```shell
/usr/local/lib/python3.7/dist-packages/gradio/deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
Running on public URL: https://58371.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces (https://huggingface.co/spaces)
```

### System Info

```shell
carefully checked in gradio `3.0.0` and `3.0.13`, observed in other 3.0.x versions
in Chrome Version 101.0.4951.64 (Official Build) (x86_64)
run on Colab and on a local Linux machine
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Thanks @charlesfrye, we need to bring flagging options back in!

**Comment by abidlabs** [comment]
@charlesfrye this is fixed in `main`. We'll release a version of `gradio` to pypi today or tomorrow that should have this in.

Note that we've changed the UI for flagging options a little bit. We think this is better, but let us know your thoughts!

**Comment by charlesfrye** [comment]
Thanks for the quick turn-around on the fix!

I really like that you've made it easier for users to flag outputs by adding buttons for the flagging options. My biggest concern is that promoting the flagging options to the top-level aesthetics of the interface (alongside the inputs and outputs) couples too many distinct things.

I think encouraging users to apply multiple flags is good. But the current design also makes it (too much) easier to apply the same flag multiple times. Additionally, the csvlogger writes the input file multiple times when the users applies multiple flags, though, which isn't ideal. Seems tough to know when the input is in fact the same, unless you're already hashing inputs/outputs.

Another thing to consider: this change couples the aesthetics of the output box and the content of the flagging. So if I make my flagging richer by adding more options, one of the core pieces of my application's aesthetics changes -- and not always for the better:

![image](https://user-images.githubusercontent.com/10442975/173933193-a8f11320-76df-4b0e-a8e0-7b5859db4e7c.png)

The same basic thing happens if I make the flagging options more verbose, as you might if you were using them to instruct/remind users what the purpose of the flag is. There's a lot less ambiguity in a sentence than in a word.
![image](https://user-images.githubusercontent.com/10442975/173933934-f7884755-7b3b-457c-9dbb-f1c858885132.png)

Finally, by making the flags top-level and simultaneously visible, you're encouraging users to make them uniform (e.g. all or no emojis, all adjectives) and by using "Flag _as_ flagopt" you're encouraging them to take a fairly limited verbal form (adjective or noun phrase). Since these are by default written to the log, that means you're linking the top-level aesthetics of the app to the contents of an internal-use database.

An option to pass a dictionary of `flagging_options` would be one nice escape hatch (type signature `Dict[InternalFlag, DisplayedFlag]`, where `InternalFlag` and `DisplayedFlag` are aliases for `str`). That is, the dictionary's keys are what ends up in e.g. the `flag` column of the CSVLogger output while the dictionary's values are what ends up displayed to users.

AFAICT, the flagging component is not visible on the `Interface` or on the output component after creation but before launch, but that provides another potential escape hatch.

**Comment by abidlabs** [comment]
Thanks for the detailed feedback @charlesfrye! What you're saying makes sense to me -- let me tag @aliabid94 for visibility

**Comment by charlesfrye** [comment]
One more nit: the flagging buttons don't change visibly on click (only on hover), so users don't have any indication that their click went through.

**Comment by abidlabs** [comment]
Let's reopen this issue so that we can manage it more easily

**Comment by aliabid94** [comment]
This a lot of amazing feedback @charlesfrye, thank you! Will work on a flagging redesign soon incorporating this.

**Comment by freddyaboulton** [comment]
Renamed the issue since the original bug was fixed and the discussion turned to how to improve the flagging UX. 

This issue feels larger in scope than what we're trying to prioritize for 3.2 but adding it to 3.2 so that someone can start brainstorming.
