### ISSUE TITLE
if examples are more than 1 pages, there 's selecting's bug

### ISSUE THREAD

**Issue by hpeiyan** [gradio-app/gradio#1505]
### Describe the bug

if examples are more than 1 pages , such as in 2nd page, after I select the one of them, there's still the result from the first page.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. examples more than one pages
2. select one of example in 2nd page or other page

### Logs

```shell
I have no catch the log
```

### System Info

```shell
gradio = 3.0.13
browser = google chrome
system: ubuntu20.0.4
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Fixed in `main`, thanks @aliabid94! We'll release a version of `gradio` to pypi today or tomorrow that should have this in.

**Comment by hpeiyan** [comment]
> Fixed in `main`, thanks @aliabid94! We'll release a version of `gradio` to pypi today or tomorrow that should have this in.

thanks for your reply.
