### ISSUE TITLE
Interpretation should support gallery component

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1534]
- [ ] I have searched to see if a similar issue already exists.

**Describe the solution you'd like**  
It would be nice if the interpretation mode supports the gallery component, as under the hood they are just images, we could potentially do the interpretation of each output image. WDYT?

**Comment by abidlabs** [comment]
That'd be pretty cool! We need to spend some time and fix up various things around interpretation but this can be one thing that we do as part of that.

**Comment by abidlabs** [comment]
Thinking about this some more, I'm not sure how this would work. Interpretation right now is supported for almost any input component, but **only** text/label output as those have the clearest notion of how to support interpretation. Given that Gallery is an output component only, I don't think it could support interpretation. (Even image output doesn't support interpretation right now)

**Comment by osanseviero** [comment]
Good point! Yes, I think we can proceed to close.
