### ISSUE TITLE
Strange image output behavior before inference when using example image 

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1537]
### Describe the bug

When using example image and selecting it, the output box changes before inference in a strange way.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Go to https://huggingface.co/spaces/keras-io/conv_autoencoder

1. First, output looks like a full block

<img width="1219" alt="Screen Shot 2022-06-10 at 4 51 41 PM" src="https://user-images.githubusercontent.com/7246357/173092149-58a89e92-658a-47aa-9058-d7063417aaa4.png">

2. Click example image
3. Now the output block is just a small horizontal block

<img width="1227" alt="Screen Shot 2022-06-10 at 4 52 19 PM" src="https://user-images.githubusercontent.com/7246357/173092284-3c51e9fd-91c4-4106-b651-28e00eee28fe.png">

This just happens when using example images

### Logs

```shell
-
```

### System Info

```shell
Gradio 3.0.12, Spaces
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks @osanseviero -- this has been solved actually and should be able to be fixed by upgrading to the latest `gradio` version. I've opened a PR for this: https://huggingface.co/spaces/keras-io/conv_autoencoder/discussions/1
