### ISSUE TITLE
Upscale/downscale example images to be consistent

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1539]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
At https://huggingface.co/spaces/keras-io/conv_autoencoder, the example images look tiny, but if clicked they look ok. Should we upscale here so all apps feel consistent?

**Comment by abidlabs** [comment]
Hmm interesting, it's probably because the original images are only 28x28. I think it's reasonable to upscale them -- wdyt @aliabid94?

**Comment by osanseviero** [comment]
Yes, it's because of the original size, but I think it would be nice to be consistent regardless of specific example size

**Comment by aliabid94** [comment]
Yep makes sense, will fix.
