### ISSUE TITLE
Plotly plots do not work with gradio>3.0.13

### ISSUE THREAD

**Issue by duerrsimon** [gradio-app/gradio#1544]
### Describe the bug

Plotly plots do not render anymore. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Standard example or even empty plot does not work and works unchanged in gradio 3.0.11

### Logs

```shell
`Uncaught (in promise) Error: DOM element provided is null or undefined
    getGraphDiv https://gradio.s3-us-west-2.amazonaws.com/3.0.13/assets/index.9a7d92ae.js:113
    newPlot https://gradio.s3-us-west-2.amazonaws.com/3.0.13/assets/index.9a7d92ae.js:113
    1 https://gradio.s3-us-west-2.amazonaws.com/3.0.13/assets/index.9a7d92ae.js:472
    flush https://gradio.s3-us-west-2.amazonaws.com/3.0.13/assets/index.e8a1a070.js:530`
```

### System Info

```shell
gradio 3.0.13 and upwards
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Thanks for the heads up Simon! @dawoodkhan82 can you look into this?
