### ISSUE TITLE
Request Image shows in full_width and specified Height.

### ISSUE THREAD

**Issue by hpeiyan** [gradio-app/gradio#1561]
- [ x ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

Image shows in full_width and specified Height.

**Describe the solution you'd like**  

Hope the feature can be code like below, after setting full_width and specified height, the image shows in specified height and auto put in the center.

```python
gr.Image().style(full_width=True, height=60)
```

**Additional context**  
there's Image's style feature that setting specified width and height, such as 
```python
components.Image(type="pil", label="image").style(height=260, width=300)
```
but, the image shows in left of container.

<img width="402" alt="image" src="https://user-images.githubusercontent.com/12880598/173490515-9fa1ae2c-12da-43b0-8aea-eddc417025d7.png">

**Comment by aliabid94** [comment]
Will take a look, thanks for opening.

**Comment by agn-7** [comment]
@hpeiyan 
Doesn't work:
```
AttributeError: 'Image' object has no attribute 'style'. Did you mean: 'scale'?
```
