### ISSUE TITLE
Document & Automate Website Deployment (Have website track `main`)

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1567]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
We need to automate website deployment just like pypi releases with github actions.
Optionally we should also document website deployment while we are doing this

**Comment by abidlabs** [comment]
Setting this to 3.1 milestone as this is blocking lots of other issues related to docs @aliabid94
