### ISSUE TITLE
Dropdown is disabled when created with blocks

### ISSUE THREAD

**Issue by rremani1990** [gradio-app/gradio#1569]
### Describe the bug

Hi,
Tried creating gradio app with blocks, Dropdown was disabled after launch.

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

```
import gradio as gr

demo = gr.Blocks()

with demo:
    with gr.Tabs():
        with gr.TabItem("Record Video"):
        
            with gr.Row():
                inp1=gr.inputs.Video(source="webcam",optional=False,label='Capture Video')
                inp2=gr.inputs.Video(source="webcam",optional=False,label='Capture Video')
            with gr.Row():
                subject_id = gr.inputs.Dropdown(["cat", "dog", "bird"])
    
        
demo.launch()
```

### Screenshot

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/102731859/173801150-712bc70e-479a-456e-a12b-7e0bb293bdf5.png">
<img width="915" alt="image" src="https://user-images.githubusercontent.com/102731859/173801336-8f571c6d-026e-457e-8269-192f5d4ecc4d.png">

### Logs

```shell
NA
```

### System Info

```shell
Browser: Chrome
Gradio Version: 3.0.17
```

### Severity

blocking all usage of gradio

**Comment by aliabid94** [comment]
Thanks for raising this issue. Once you make an event listener that takes the dropdown as an input, the dropdown will be activated. But I thought we removed disabled for elements by default, @pngwn? 
Will fix. For now, you can either use `gr.Dropdown(choices=[...], interactive=True)`, or just create an event listener that takes the dropdown as input.

**Comment by rremani1990** [comment]
@aliabid94 thanks, suggestion worked!

**Comment by abidlabs** [comment]
Btw @aliabid94 it looks some of the other form components are also not interactive by default: e.g. `Radio` and `Slider`

**Comment by pngwn** [comment]
This feels like a regression, I'm pretty sure we had this working fine a short while ago. Will investigate.
