### ISSUE TITLE
Example labels showing up as NaN when "Run all"

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#157]
![image](https://user-images.githubusercontent.com/1778297/115609872-b551a200-a2ad-11eb-8ea8-420264c20051.png)

**Comment by aliabid94** [comment]
Run all has been removed. Instead, precalculate all the outputs for the examples yourself and pass the outputs along with the inputs into the list for the examples keyword to quickly browse through example inputs and outputs.
