### ISSUE TITLE
Support modifying interactive in component update

### ISSUE THREAD

**Issue by ID56** [gradio-app/gradio#1574]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Right now a component can be created as _non-editable_ with the `interactive=False` argument. However, it is not possible to modify this interactivity later on at runtime.

We may want to use some behavior, where depending on certain conditions, a component (like Textbox, Number, Slider, etc) will be frozen / unfrozen.

At the moment, it is technically possible to do this if the visibility of the box is updated. Instead of freezing a component, we just make it not visible, and thus no one can interact with it. But disappearing components is perhaps not an ideal approach to this sort of problem.

**Describe the solution you'd like**  
Ideally, it would be great if the following was supported:

```python
SomeComponent.update(interactive=False) # or True
```

**Additional context**  
This feature will be helpful for implementing the third test of the [7 GUI Benchmark for Gradio](https://github.com/gradio-app/7guis-gradio), `Flight Booker`.

**Comment by abidlabs** [comment]
Fixed in `main`, will be out in `gradio==3.0.18` shortly!
