### ISSUE TITLE
How to use Gradio with MobileNet

### ISSUE THREAD

**Issue by uzair-ali10** [gradio-app/gradio#158]
This isn't an issue but a question
Hello I started using gradio today but however, I encountered an error while using it despite of trying to figure it out for many hours I decide to post it here.

I'm trying to use it with Mobile Net model but I have an issue app
I've attached the collab link below so pardon me if it is a noob question

[https://colab.research.google.com/drive/1zVgNQER2V39Lu_e8McxQaRPOlghgIVyB?usp=sharing](https://colab.research.google.com/drive/1zVgNQER2V39Lu_e8McxQaRPOlghgIVyB?usp=sharing)

**Comment by abidlabs** [comment]
Hi @uzair-ali10 welcome to gradio! The issue seems to be the `image = image.reshape((-1, 299, 299, 3))` line should be `image = image.reshape((-1, 224, 224, 3))` since that is the size of the input image for Mobile Net.
