### ISSUE TITLE
Add copy-paste buttons to code snippets on the view API page

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1581]
It's great to see that Gradio API Docs are back! I would like to share some feedback on the page
![Screenshot from 2022-06-16 10-28-32](https://user-images.githubusercontent.com/7246357/174027685-12626c20-aa3a-4c3d-aef5-2cba8e2e2c58.png)

* The title is the link of the embedded page, would it make sense to have a shorter link
* The full URL is a url? It looks like a link but clicking on it does not work
* The copy button says it copied but it doesn't copy (Ubuntu, Chrome)
* There is no code snippet to easily use this in curl or python (https://github.com/gradio-app/gradio/issues/1325) 
* Maybe this should link to a Gradio Guide on how to use this for people that might not fully know about this :)

**Comment by FarukOzderim** [comment]
There was an alternative API docs suggestion [here](https://github.com/gradio-app/gradio/issues/1390#issuecomment-1145901615), @osanseviero WDYT on how it compares to the current docs from UX perspective?

**Comment by pngwn** [comment]
I dont think it makes sense to reimplement the docs atm, these are all small improvements that we can easily add.

**Comment by abidlabs** [comment]
It looks like all of these are solved except for the ability to copy-paste the code snippets, so renaming the issue to reflect that

**Comment by abidlabs** [comment]
@aliabd could you take this on? Let's revamp the view API page this week
