### ISSUE TITLE
Updating values for Invisible DataFrames breaks the data

### ISSUE THREAD

**Issue by NimaBoscarino** [gradio-app/gradio#1583]
### Describe the bug

When an invisible DataFrame component (of all types: "pandas", "numpy", "array") is updated with new values, the resulting data frames downstream have an unexpected structure, where all the columns are squished into one column called "data".

Note that when the DataFrames are _initialized_ with the particular data (e.g. [in this colab](https://colab.research.google.com/drive/1vJokZnJi4aHNE976SyT8sZNDHHTUK3e0?usp=sharing)) both the visible and invisible DataFrames have correctly formatted data.

I've run into this since I'm trying to use an invisible DataFrame component to hold intermediate data for a multi-step app, and noticed that toggling the visibility of the DF component would break the app.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://colab.research.google.com/drive/1RGRt5gLljog82XeO4STVtmEIhdBR-lCv?usp=sharing

### Logs

```shell
No errors.
```

### System Info

```shell
Gradio 3.0.17, replicated on macOS 12.4 and Google Colab.
```

### Severity

serious, but I can work around it

**Comment by Ian-GL** [comment]
This issue has the same root cause as issue 1573 (since the invisible component was not rendered at all, the value wasn't formatted for the invisible component). The fix for it (#1576) has already been merged.

**Comment by abidlabs** [comment]
Yes, to reiterate @Ian-GL's point, I tried running both of the colab notebooks that you provided @NimaBoscarino and I got the same output using the latest version of gradio, `gradio==3.0.18`. 

@NimaBoscarino can you confirm that this issue has been fixed?

**Comment by NimaBoscarino** [comment]
Yup, works great! Looks like I should have just waited two hours for the release, and I should've checked the closed issues 😅 Closing this!
