### ISSUE TITLE
Gallery component doesn't display default images

### ISSUE THREAD

**Issue by NimaBoscarino** [gradio-app/gradio#1587]
### Describe the bug

The initial images passed as values to a Gallery component are not displayed, either in a Block or an Interface. If the Gallery values are updated, then the Gallery renders the images.

I dug back to previous commits and isolated it to this one (https://github.com/gradio-app/gradio/commit/74703898c636c4e2a233880feac3eb239b4f8a2b) 🤔 
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://colab.research.google.com/drive/1KEFsoOxWw_dp9w--fkh5lKITJgK4VRXK?usp=sharing

### Logs

```shell
N/A
```

### System Info

```shell
Gradio 3.0.18, macOS 12.4 and Google Colab
```

### Severity

annoying

**Comment by aliabid94** [comment]
Thanks for raising this. Will take a look.
