### ISSUE TITLE
Better UI for image selection by the cropper

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1591]
### Describe the bug

I go to https://huggingface.co/spaces/keras-io/Monocular-Depth-Estimation, I select one example image and click the pencil at top right to modify the image, but I don't see any way to use it. I can move a selector, but there is no confirmation button or anything. Is that expected?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See above

### Logs

```shell
-
```

### System Info

```shell
Gradio 3.0.13
```

### Severity

annoying

**Comment by aliabid94** [comment]
The submitted image will be the portion of the image selected by the cropper. Agreed this is unclear, and UX needs to be more intuitive.

**Comment by osanseviero** [comment]
I think in gradio <3 we edited the image and then click a :heavy_check_mark: to confirm it was edited
