### ISSUE TITLE
Queue bug with examples

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1592]
### Describe the bug

When I go to https://huggingface.co/spaces/keras-io/structured-data-classification, and I click the selected example at bottom, it shows a queue of 11/11 (it's super fast). Is it possible each element of the inputs is being updated at a time, and each of those is making a new inference call?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See above

### Logs

```shell
-
```

### System Info

```shell
Spaces, 3.0.11
```

### Severity

annoying

**Comment by FarukOzderim** [comment]
Looks like a visual bug to me because it jumps to 1 from 11 really fast.

**Comment by freddyaboulton** [comment]
The interface is live so when you click on an example, it will update every input component, and each one of those changes trigger a prediction. 

Maybe we can modify the front-end to not respect `live` for examples but sounds low priority. What do you think @aliabid94 @abidlabs ?

**Comment by freddyaboulton** [comment]
This issue is very stale and as described in the previous comment, this is actually the intended behavior. So will close!
