### ISSUE TITLE
Plot component is not cached with examples

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1594]
### Describe the bug

When caching an example, the plot component is not cached. See https://huggingface.co/spaces/keras-io/3D_CNN_Pneumonia/discussions/3

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Go to https://huggingface.co/spaces/keras-io/3D_CNN_Pneumonia and click the example. It does not show any plot in the second output. Note that clicking Submit (so forcing the inference) does show the output plot, so it's a caching issue

### Logs

```shell
-
```

### System Info

```shell
Gradio 3.0.11, Spaces
```

### Severity

serious, but I can work around it

**Comment by dawoodkhan82** [comment]
@osanseviero Will take a look

**Comment by abidlabs** [comment]
@dawoodkhan82 LGTM, the caching issue seems to have been fixed.

However, to confirm, bokeh plots are still broken? There was an issue about this I think but I can't find it now. Can we fix bokeh as well?
