### ISSUE TITLE
tqdm for Timer

### ISSUE THREAD

**Issue by Muhtasham** [gradio-app/gradio#1596]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Seems there is no timer feature component in Gradio 

**Describe the solution you'd like**  
Would be good to incorporate tqdm inside gradio to implement Timer from 7GUIs

**Additional context**  
https://github.com/gradio-app/7guis-gradio

**Comment by abidlabs** [comment]
Similar to #340 but will keep this issue open as a reminder to incorporate with `tqdm` if possible

**Comment by pngwn** [comment]
I'm not sure i follow this, for 7GUIs I think the timer would need to be on the frontend, not in a python API. How would adding a python timer library enable accurate realtime timers in the browser?

**Comment by abidlabs** [comment]
Closing in favor of #2683
