### ISSUE TITLE
Library Performance Improvements

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1598]
- [X] I have searched to see if a similar issue already exists.

First of all migrating to a [ASGI](https://asgi.readthedocs.io/en/latest/) framework has unlocked many potentials and improved performance. I would like to plan/list/track a few issues that will improve the library performance.

- #1547 allows to run async functions in sync scopes, enabling us to use async functions without any limitation
- #727 will support async functions in Blocks, which will make Gradio functions more performant with network calls and more flexible overall.
- #572 will move Queue to async threads instead of sync threads and remove the DB which will improve the queue performance a lot, and will enable auto-scaling on Spaces, which will enable Spaces to be very very fast. Also it will enable concurrency in the Queue and make use of websocket connections which will unlock more potentials with connecting and reconnecting to servers.
- #2052 move our http calls from being sync to async and background which will make launching the demo and loading other demos faster.

With these we will achieve being %100 possible async codebase and make use of ASGI potential.

- #1597 will enable us to process multiple inputs parallel in GPU, which will let Gradio to a higher potential with big ML Model.

Please let us know if you have any further ideas about performance 😸

**Comment by abidlabs** [comment]
At this point, I'm closing this tracking issue since there is only #2052 left
