### ISSUE TITLE
Side Nav bar for Quickstart Guide is bugged.

### ISSUE THREAD

**Issue by dawoodkhan82** [gradio-app/gradio#1601]
### Describe the bug

Clicking on some sections takes you to others and doesn't highlight the proper section of the nav bar.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://gradio.app/getting_started/#blocks-more-flexibility-and-control

Click through different sections int he side nav bar

### Logs

```shell
N/A
```

### System Info

```shell
N/A
```

### Severity

annoying

**Comment by abidlabs** [comment]
Nav bar removed for now
