### ISSUE TITLE
Gradio 3 does not allowing stacking multiple functions 

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1605]
### Describe the bug

As per https://discuss.huggingface.co/t/space-is-displaying-infinitely-loading-while-status-is-running/18603, Gradio <3 allowed something like

```py
model_iface = gr.Interface(
    fn=[your_function_1, your_function_2],
    inputs=gr.inputs.Textbox(),
    outputs=gr.outputs.Label(num_top_classes=10),
    examples=[["first example"],
              ["second example"]]
)
```
The logic above can be replicated in some sense with `gr.Parallel`, but this might confuse users that want to upgrade.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

-

### Logs

```shell
-
```

### System Info

```shell
3
```

### Severity

annoying

**Comment by osanseviero** [comment]
Note: I think this is likely very low impact so it might be ok :) I was just reporting it

**Comment by abidlabs** [comment]
Thanks @osanseviero you are completely right. This is actually one of the few things that we deprecated from Gradio 2 to 3 because it was rarely used and complicates the internal logic quite a bit. I'll add a deprecation notice.

**Comment by AlvinKimata** [comment]
You can try using the `TabbedInterface` class provided by Gradio. It takes in a list of interfaces as input and renders the interfaces in multiple tabs. For example: 

```python
app = gr.TabbedInterface(interface_list=[image_interface, video_interface], 
                         tab_names = ["Image inference", "Video inference"])

if __name__ == '__main__':
    app.launch()
```
