### ISSUE TITLE
Test_tunneling breaks async tests

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1616]
- [X] I have searched to see if a similar issue already exists.

As you can see in this [PR](https://github.com/gradio-app/gradio/pull/1595#issuecomment-1161898095) and this issue #572; after test_tunneling tests are run, async tests were running for forever. Not sure what causes it, and was not easy to investigate. After debugging for a while with @hibestil found out that it runs forever on this scope handle_async_request function. Solved the problem by @hibestil by renaming the test_tunneling, so that it is ran last.

![image](https://user-images.githubusercontent.com/44067394/174837029-02f366d6-4304-4531-aafa-3fa1adf0b77d.png)

Might be nice to investigate and solve this issue better in the future.

**Comment by Ian-GL** [comment]
Hey @FarukOzderim I've dig a bit into this and the problem is with the thread creation in the tunneling test. My theory is that the thread is being started but never stopped and that is interfering with the async tests.

I'm not very knowledgeable on how the tunneling works, why is the threading needed? If I change the test to this it no longer hangs on the util tests:

```
class TestTunneling(unittest.TestCase):
    def test_create_tunnel(self):
        response = requests.get(networking.GRADIO_API_SERVER)
        payload = response.json()[0]
        io = Interface(lambda x: x, "text", "text")
        _, path_to_local_server, _ = io.launch(prevent_thread_lock=True, share=False)
        _, localhost, port = path_to_local_server.split(":")
        # threading.Thread.start = mock.MagicMock(return_value=None)
        paramiko.SSHClient.connect = mock.MagicMock(return_value=None)
        tunneling.create_tunnel(payload, localhost, port)
        # threading.Thread.start.assert_called_once()
        paramiko.SSHClient.connect.assert_called_once()
        io.close()
```

Isn't the paramiko usage of the mock and the paramiko assertion enough?

**Comment by Ian-GL** [comment]
Also about the topic of threads in tests I found [these docs](https://pythonhosted.org/tl.testing/tl.testing-thread.html) which could provide options on how to solve this while keeping the threads

**Comment by FarukOzderim** [comment]
Thank you for looking into it @Ian-GL ❤️, I was OOO last week, will take a look today or tomorrow.

**Comment by FarukOzderim** [comment]
Since `threading.Thread.start` function is mocked, `threading.Thread.start = mock.MagicMock(return_value=None)`, it is actually not triggered. So we do not start a thread over here, we just check it being called. So what I think actually happens is, we mock `threading.Thread.start` but the mocking still hangs on different test files, and causes problems whenever a thread is started. That's why it is unsafe to mock a library call. Will check with an issue in the mock's repo.

Btw thx for finding the root cause, it was a problem that took hours of debugging several times in the past ❤️

**Comment by FarukOzderim** [comment]
Actually tested it out myself
![image](https://user-images.githubusercontent.com/44067394/177090771-d1463fa9-f2e7-4d2a-b3a5-0eee8efb0a9c.png)

import os
import unittest.mock as mock

os.environ["GRADIO_ANALYTICS_ENABLED"] = "False"

import math


test_1:
```
class TestTunneling:
    def test_mock(self):
        math.sqrt = mock.MagicMock(return_value=3)

    def test_sqrt(self):
        assert 3 == math.sqrt(3)

```

test_2:
```
import math

class TestTunneling:
    def test_sqrt(self):
        assert 3 == math.sqrt(3)

```

Result:
============================================================================================================== 3 passed, 1 warning in 0.07s ==============================================================================================================
