### ISSUE TITLE
dataframe display exceed the window size

### ISSUE THREAD

**Issue by YuchenZeng** [gradio-app/gradio#1618]
## Describe the problem

Hi, I want to display multiply columns at each row and I found that the Dataframe output will exceed the window size. And I have searched relative issues and I couldn't find any solutions to fix the dataframe output width.

## Additional context

Code:

```
import pandas as pd
import gradio as gr

def example_fn(text):
    d = {'c1': ["This is col 1"], 'c2': ["This is col 2"], 'c3': ["This is col 3"], 
         'c4': ["This is col 4"], 'c5': ["This is col 5"], 
         'c6': ["This is col 6"], 'c7': ["This is col 7"]}
    df = pd.DataFrame(data=d)
    return df

demo = gr.Interface(
    fn = example_fn,
    inputs = [gr.Textbox(label="Input", lines=3, )
             ],
    outputs = [gr.DataFrame()],
    title="Test",
    allow_flagging=False,
)

demo.launch()
```

Image:
<img width="921" alt="image" src="https://user-images.githubusercontent.com/25089434/174924561-74bdd527-f26d-4c5c-9de0-361e39a318eb.png">

Version:
python: 3.7.10
gradio: 3.0.11

**Comment by abidlabs** [comment]
Hi @YuchenZeng I believe this is the same issue as #1196, which we just fixed. Can you please try upgrading to gradio 3.0.20 and let us know if you still see the issue? If so, please feel free to reopen the issue

**Comment by YuchenZeng** [comment]
Hi @abidlabs , thanks, but this issue still exists. I created a simple demo to show 15 column and you can see the 15th column is not displayed. Is there any way to fix the width of the output bounding box? (https://huggingface.co/spaces/YuchenZeng/simple_demo)

**Comment by abidlabs** [comment]
Ah sorry about that, let's reopen the issue and we can take a look at it. cc @pngwn

**Comment by pngwn** [comment]
hmmmm.

**Comment by YuchenZeng** [comment]
Hi @abidlabs, I believed the problem is solved when we run the gradio locally, however, in huggingface space, the problem still exists. In this example, https://huggingface.co/spaces/YuchenZeng/simple_demo, if you click submit and scroll right, the interface cannot show 15th column properly.
