### ISSUE TITLE
Create contributor guide for creating new components

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1628]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
We should create a Guide around creating custom components. This is a nice starting [point](https://github.com/gradio-app/gradio/issues/1622#issuecomment-1163740284).

Adding it to 3.1 milestone, since I think it will naturally develop with #1622. Can remove the milestone if it does not catch up.
@pngwn you can take this on if you want to.

**Comment by pngwn** [comment]
I'm happy to oversee this one, regardless of whether I do it myself or it is contributed by the community.
