### ISSUE TITLE
It is too slow when I run my algorithm

### ISSUE THREAD

**Issue by theguardsgod** [gradio-app/gradio#163]
It needs to finish my algorithm for about 120 seconds. while it takes only 10 seconds if I start my algorithm in terminal

**Comment by abidlabs** [comment]
Hi @theguardsgod. It is likely this issue, which affects many libraries including Gradio and PyTorch that run from a different thread, and has been discussed before: https://github.com/gradio-app/gradio/issues/130.

Feel free to reopen the issue if this does not solve your issue
