### ISSUE TITLE
Video detection output 

### ISSUE THREAD

**Issue by MACHMR2010** [gradio-app/gradio#1630]
I want to create a gradio demo for yolov5 detection on video .... So it takes as input a video and as output video detected.... How Can I do it ??

**Comment by abidlabs** [comment]
Hi @MACHMR2010, `gradio` includes a `Video` component, which can be used both as an input and an output. So your could would basically look like this:

```py
import gradio as gr

gr.Interface(fn, "video", "video").launch()
```

Here, `fn` should be a function that takes in a string path to a video file and returns the string path to a new video file that you would look to render.

If you run into any bugs, you can create new issues with more specific information, thanks.
