### ISSUE TITLE
Gradio for detection model on video 

### ISSUE THREAD

**Issue by MACHMR2010** [gradio-app/gradio#1633]
I want to use model of detection on video ... I have this error
 
![errrooor.PNG](https://user-images.githubusercontent.com/106706409/175765108-a7d4c410-7e38-4035-a864-6e480c6ee85d.PNG)

How Can I fixe it ?

**Comment by abidlabs** [comment]
Hi @MACHMR2010, this seems like an indentation issue? Lines 9-11 should be indented. I don't see any issue here related to `gradio`.

Please use these issues specifically for errors related to Gradio.
