### ISSUE TITLE
Create Demos page in website that showcases key demos in one place

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1638]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Having all the components together in one place, where new users could play with them would seriously improve our Gradio demonstration.

**Describe the solution you'd like**  
Showcase The Kitchen Sink in Docs or Website

**Additional context**  
We do have all the components on the docs page, but they are sparse.
![image](https://user-images.githubusercontent.com/44067394/175803842-3e1d217f-da32-4cff-986f-fe7862c56052.png)

@aliabd @abidlabs @gary149 WDYT?

**Comment by abidlabs** [comment]
What do you guys think about creating a "Demos" page in our website that showcases our key demos (including the kitchen sink) in one place. 

For the v1, I'm thinking two columns, with the code on the left and the demo on the right. A row on the top allows the user to choose between different demos. 

For the v2 (when we support running `gradio` in the browser), this could be made into an interactive "playground" where users could edit the Python code for the demos and we would refresh the layout for a fun way to get started with gradio.

cc @pngwn @aliabd @aliabid94

**Comment by freddyaboulton** [comment]
Sounds like a good idea to me @abidlabs ! Maybe for v2 we can add links to the docs corresponding to each (or some of the) component/event used in the demo. That ways users can learn more about a feature after seeing it in an example.

**Comment by aliabd** [comment]
We already embed about 30 demos in the docs page (Try Examples windows), so it wouldn't take much to assemble them into a separate page. Though I'm not sure how useful that is for users. It reads to me that v1 is essentially already implemented, as you describe, in docs, except with the added benefit that demos are tagged by component/class. 

The interactive playground is a killer feature though. We've talked about it before and I think it would be great to add to the website

**Comment by abidlabs** [comment]
Yes definitely @aliabd. I don't think we need to create any new demos, but I think there is some value in having them accessible all in one place (and in an a logical order) so that people can quickly browse through different demos and get an intuition for how gradio works.

**Comment by freddyaboulton** [comment]
Idea from @pngwn, this could be a good opportunity to clean up the demos directory. Some of the discussion we've had:


> We have two types of demo: actual demos, that demonstrate some real world usage for gradio and demos that 'test' or showcase a specific feature (the former encompass the latter but the latter are solely focused on testing a feature, the predict function for these is frequently a simple identity function (sometimes a lambda). We could split these into two categories then we can have good demos/examples to point users to but still keep our focused demos for testing/ developing specific features.

> Also the names for the demos could be better. Would help when looking for a demo to test a specific feature.

> Yeah totally agree, was thinking we could go through the demos and have one 'feature demo' for each API like Tabs  and we can test all tab functionality in the one demo (with the simplest code possible) then when we add a new feature/ option to tabs, we can just add it to that demo (rather than creating a new one). They could all be named mostly after their components.

This isn't a hard requirement for closing this ticket but since we'll be identifying key demos as part of this issue, that could be a good opportunity to establish the different between "feature" and "test" demos.
