### ISSUE TITLE
Add information on how to install python test dependencies for M1 development

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1644]
- [x] I have searched to see if a similar issue already exists. 

Similar issue here https://github.com/gradio-app/gradio/issues/1369 but that was closed as there is no problem installing the gradio pip package on M1 mac. This issue is related to installing the test dependencies in M1 mac. 

**Is your feature request related to a problem? Please describe.**  
As a Gradio developer, I wish the contributing guide provided some information on how to fix some of the common problems that will arise when installing the test dependencies on an M1 mac, e.g. `tokenizers` does not publish a wheel for osx arm architectures. 

**Describe the solution you'd like**  
Update development guide to include information on how to install test dependencies on M1 mac. Alternatively can we remove some dependencies on `requirements.in`, e.g. `tensorflow` ? 

**Additional context**

**Comment by abidlabs** [comment]
I'm in favor of removing `tensorflow`! If `pytorch` is easier to run on M1, let's switch to that.

**Comment by FarukOzderim** [comment]
@hibestil had problems with test requirements as far as I know, he might help if he has solved them as well.
