### ISSUE TITLE
Create Github tag/release for every PyPi release

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1646]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As a gradio developer/user, I think it will be easier to identify the root cause of regressions between versions if there's a github repo tag and release for every gradio version on PyPi.

For example, in https://github.com/gradio-app/gradio/issues/1632 , it might help to travel back in time to version 3.0.12 in the repo since that's the last time the plotly plot worked as expected.

**Describe the solution you'd like**  
Create a github tag and release for every gradio PyPi release. Currently, there are tags only for "major" releases (2.9, 3.0, etc). 

**Additional context**

**Comment by Ian-GL** [comment]
I think also a changelog file could be an alternative to achieve the same goal.

**Comment by abidlabs** [comment]
Totally agreed. Would be great if we can automate this as part of the GitHub action: https://github.com/gradio-app/gradio/blob/main/.github/workflows/deploy-pypi.yml
