### ISSUE TITLE
Can't Build Website on M1

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1654]
### Describe the bug

When trying to build the website on an M1, I get the following errors trying to install python dependencies

```bash
#0 6.147 Processing orjson-3.7.5.tar.gz
#0 6.200 error: Couldn't find a setup script in /tmp/easy_install-xdiqoz9x/orjson-3.7.5.tar.gz
```

```bash
#0 142.0 error: charset-normalizer 2.1.0 is installed but charset-normalizer~=2.0.0 is required by {'requests'}
```

This may be tracked by the `live_website` branch so I'll close if that PR fixes the issue! Just filing so I don't forget to get back to this. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`docker-compose up` in the website dir in the main branch

### Logs

```shell
-
```

### System Info

```shell
Latest main
```

### Severity

annoying

**Comment by abidlabs** [comment]
Is this still an issue @freddyaboulton? You've been able to build the website locally, right?

**Comment by freddyaboulton** [comment]
Not with the demos via docker compose
