### ISSUE TITLE
Backwards compatibility in the external module

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1656]
The `TestLoadInterface::test_sentiment_model` unit test started to fail because the inference api returned a list of dicts as opposed to a list of list of dicts. Failure in circle ci [here](https://app.circleci.com/pipelines/github/gradio-app/gradio/4149/workflows/81e2bc7b-5b9c-4336-9b88-9d7e251817c1/jobs/4218?invite=true#step-114-202). 

This was an accidental change in the `transformers` library but I was chatting with @Narsil and that change may come in `transformers` 5.0. Don't have to change anything yet, but making a note so that we're not surprised.

**Comment by abidlabs** [comment]
Should we keep this issue open? I think let's close until there is an actual transformers release with different behavior?

**Comment by freddyaboulton** [comment]
Nuking it 😂
