### ISSUE TITLE
Improve interpretation output for functions that take more than one input

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1657]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
The interpretations feature works great for single  input interfaces (image, text) because it shows the user which region of the image, or words in the sentence, most contribute to the prediction.

However, when the function takes more than one input, the app will display the interpretation for each input independently. That's not very helpful to a user because it doesn't help them see which feature contributes the most to a given prediction. It is common (and expected) that data scientists working on tabular datasets build models that take more than one feature as input (and will therefore build a demo with more than input component).

For example, consider the demo with two numeric inputs:

```python
from gradio import Interface

def quadratic(num1: float, num2: float) -> float:
    return 3 * num1**2 + num2

iface = Interface(
            fn=quadratic,
            inputs=["number", "number"],
            outputs="number",
            interpretation="default",
        )
iface.launch()
```

I would expect the output of an "Interpretation" feature to make it clear that the first input contributes more to the output than the second input. For example, this could be a "operating expenses forecaster" demo and as a decision maker I should be able to quickly tell from the interpretation output that I need to cut down on the first feature value as opposed to the second.

However, it's not easy to tell that from the interpretation output. The shading is a bit darker for the first input but if I didn't know to look for that I think I would have missed it. Also, the interpretation output is not labeled so I could easily make a mistake reading this:

![image](https://user-images.githubusercontent.com/41651716/176288467-9e393789-af92-4b6f-9e13-630658e8acb6.png)

**Describe the solution you'd like**  
We should normalize the interpretation scores and present them side by side. 

The shap library does this with the concept of a force plot:
 
![image](https://user-images.githubusercontent.com/41651716/176288822-0f7c0682-ea3c-4ea0-b113-fd101ea2ad75.png)

But we could also do this by normalizing the scores ourselves and displaying them in a table

| Feature  | Score |
| ------------- | ------------- |
| Feature 0  | +500  |
| Feature 1  | -10  |

**Additional context**

**Comment by abidlabs** [comment]
I think we can close this issue given that interpretation is not really a priority for us or our community at the moment
