### ISSUE TITLE
Make it easier to reset components to their original state when the app first launches

### ISSUE THREAD

**Issue by katossky** [gradio-app/gradio#1672]
### Describe the bug

On occasions, one wants to set back a component back to initial state. In my situation, I have a 2-steps app, where one predicts a label for a text, then the second explains how the label got obtained. When the user clears the app or starts typing new content, I want to move the component back to the initial look (with the image).

1. Setting `value` back to `None` fails to do this and nothing happens.
2. I can trick the component with `value` set to empty list `[]`, but this removes the image and changes the size.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```{python}
demo = gr.Blocks()

with demo:
    text = gr.Textbox()
    submit_btn = gr.Button(value="Submit")
    explanation = gr.HighlightedText()
    samples = gr.Dataset(
        components = [text],
        samples = [["Example of a text. This should reset highlighted text but does not."]]
    )
    submit_btn.click(
      fn = lambda text: gr.HighlightedText.update(value=[("Fake output", 1)]), inputs=[text], outputs=[explanation]
    )
    samples.click(
      fn = lambda sample: gr.Textbox.update(value=sample[0]), inputs=[samples], outputs=[text]
    )
    samples.click(
      fn = lambda: gr.HighlightedText.update(value=None), inputs=[], outputs=[explanation]
    )

demo.launch()
```

### Screenshot

At launch :
<img width="1291" alt="Capture d’écran 2022-06-30 à 16 45 09" src="https://user-images.githubusercontent.com/13658517/176707211-b1d15bd1-2960-412a-be60-fad29d5ca433.png">
Resetting `value` to `None` (as in snippet) does not do anything.

If instead you reset `value` to `[]` :
<img width="1291" alt="Capture d’écran 2022-06-30 à 16 45 29" src="https://user-images.githubusercontent.com/13658517/176707171-4b6097ee-8de3-4142-8c28-f5570da0a119.png">

### Logs

```shell
[no error in the logs]
```

### System Info

```shell
Gradio 3.0.20
MacOs Monterey 12.4
Brave (Chromium 1.39.111)
```

### Severity

annoying

**Comment by katossky** [comment]
For `label` components I get the desired behaviour with `gr.Label.update(value={})`.

I guess that there is a conflict between `None` in the `update()` method meaning "do nothing" and `None` for value meaning "value not yet set".

**Comment by freddyaboulton** [comment]
@katossky Thank you so much for filing! 

Can you explain a bit more what the desired outcome of this ticket should be? I was able to repro that the highlighted text box changes size slightly when updating with `value=[]`. 

![reset_highlighted_text](https://user-images.githubusercontent.com/41651716/177425948-cdca4c11-9d78-4eb9-8fef-29ff12fc667f.gif)

Does that mean that if the highlighted text container didn't change size we could close this ticket?

Or is the problem that your use case is not documented properly and so knowing the "do nothing" value is not clear and requires trial and error?

**Comment by katossky** [comment]
The problem is the impossibility to get back to the original virgin state (with the logo). Imagine a "Reset" button. In any case, documentation would help :)

**Comment by freddyaboulton** [comment]
@katossky I think this does what you expect:

```python
import gradio as gr

demo = gr.Blocks()

with demo:
    text = gr.Textbox()
    submit_btn = gr.Button(value="Submit")
    explanation = gr.HighlightedText()
    samples = gr.Dataset(
        components =[text],
        samples=[["Example of a text. This should reset highlighted text but does not."]]
    )
    submit_btn.click(
      fn = lambda text: gr.HighlightedText.update(value=[("Fake output", 1)]), inputs=[text], outputs=[explanation]
    )
    samples.click(lambda sample: (gr.Textbox.update(value=sample[0]), None),
                  inputs=[samples],
                  outputs=[text, explanation], _js=f"""(sample) => [sample, null]\n""")

demo.launch()
```

![highlight_text_reset](https://user-images.githubusercontent.com/41651716/177627979-dbc960b1-4fc2-411a-acd6-45622684fa51.gif)

Regarding your comment about "Reset" button, gradio does offer that functionality in interfaces and blocks, although it's not well documented for blocks. Would the following also work for your use case?

```python
import gradio as gr

demo = gr.Blocks()

with demo:
    text = gr.Textbox()
    with gr.Row():
        submit_btn = gr.Button(value="Submit")
        reset = gr.Button(value="Reset")
    explanation = gr.HighlightedText()
    samples = gr.Dataset(
        components =[text],
        samples=[["Example of a text. This should reset highlighted text but does not."]]
    )
    submit_btn.click(
      fn = lambda text: gr.HighlightedText.update(value=[("Fake output", 1)]), inputs=[text], outputs=[explanation]
    )
    samples.click(lambda sample: gr.Textbox.update(value=sample[0]),
                  inputs=[samples],
                  outputs=[text])
    reset.click(None, inputs=[], outputs=[explanation], _js="() => (null)\n")

demo.launch()
```

![highlight_text_reset_button](https://user-images.githubusercontent.com/41651716/177630738-ea92b3ad-70c7-41a4-bf68-39d04aa774f0.gif)

I think we should close this issue in favor of the following:

1. Documenting the _js functionality of components in the docs as well as adding examples
2. Adding a clear button as a component to make it easier to use in the blocks api

What do you think?

**Comment by katossky** [comment]
That might do it, but as a user, I am rather using Gradio to abstract from JavaScript. Also, I am not sure whether exposing your inner code is the best idea on your part.

It feels more convenient to me to have in the `update()` method 1) a value for the "unset"/"void" case, that would be the same for all components, 2) a different value for "no change", also the same for all components (this is `None` currently)

**Comment by freddyaboulton** [comment]
Thank you for explaining @katossky ! I agree we should make resetting components to their "unset" state easier and without having to use javascript.
