### ISSUE TITLE
Add missing classes and functions to docs page

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1673]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As a gradio user, I can't find all the functionality gradio has to offer documented in the Docs page. 

For example, I can't find `gr.update` (https://github.com/gradio-app/gradio/issues/1647), the different flagging callbacks, and some components like `Interpretation` on the docs page. 

Some of these concepts, like the flagging callbacks, are covered in the guides but I think they should also be in the docs page. This will make it easier for developers and users to find all the public apis in one place as opposed to having to click through different guides and skim through the text to the part they need. 

**Describe the solution you'd like**  
Document all user-facing functionality on the Docs page. We may need to reorganize the Docs page too, like adding more subheadings beyond `Interface` and `Components`.

**Comment by freddyaboulton** [comment]
Adding the brainstorming tag cause this can definitely be fleshed out more.

**Comment by freddyaboulton** [comment]
TODO:

- [ ] Interpretation
- [ ] Flagging callbacks
- [ ] The `style` method of components
- [ ] https://github.com/gradio-app/gradio/issues/1743

**Comment by abidlabs** [comment]
Oh this shouldn't close just yet
