### ISSUE TITLE
Add a flagging callback to save json files to a hugging face dataset

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1676]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As a gradio user, I would like to save flagged instances as separate json files to a hugging face dataset.

@chrisemezue wrote this awesome [space](chrisjay/mnist-adversarial) but he had to use his own flagging function to save to a hf dataset to json because our callback only saves to a csv file. He needed to save to json so that it would work better with concurrent usage of his app.

As an aside, he also needed to do some custom work in the flagging callback on his app, but I think saving to json is a common enough need that should merit it's own class in the core library especially considering that it can help with multiple users.

**Describe the solution you'd like**  
A different flagging callback or an extension of the existing `HuggingFaceDatasetSaver` to save to json. 

**Additional context**

**Comment by chrisemezue** [comment]
With pleasurere!
