### ISSUE TITLE
app fails to run.  logs say hosted at https://0.0.0.0

### ISSUE THREAD

**Issue by cogsci2** [gradio-app/gradio#168]
![image](https://user-images.githubusercontent.com/66141096/117388527-c7336780-ae9f-11eb-84f9-e6074cdebaa6.png)

Please advise

**Comment by cogsci2** [comment]
It mysteriously works again without my intervention.

**Comment by abidlabs** [comment]
Hmm, please let us know if you run into this issue again!

**Comment by cogsci2** [comment]
This issue came up again.
Instead of showing me the interface, it's showing me the logs and the strange 0.0.0.0 ip error.

![image](https://user-images.githubusercontent.com/66141096/118225840-b1431b00-b43a-11eb-9b9a-fab71a28d1cc.png)

**Comment by cogsci2** [comment]
This is coming up intermittently.  What I've found is that if I refresh 4 or 5 times, the page comes up properly.  It's pretty random as to how many times I have to refresh the page tho.  @abidlabs
