### ISSUE TITLE
Getting Started nav bar is broken

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1682]
### Describe the bug

At https://gradio.app/getting_started, if you click flagging, at left it shows as if you were in another section. Same for the last 5-10 sections.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

-

### Logs

```shell
-
```

### System Info

```shell
-
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks @osanseviero. It looks like this was reported here as well: #1601, so closing to avoid duplication.

We'll get it fixed soon!
