### ISSUE TITLE
Download button does not respect the filepath returned by the function

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1689]
### Describe the bug

In the `zip_two_files` demo:

```python
import os
from zipfile import ZipFile

import gradio as gr


def zip_two_files(file1, file2):
    with ZipFile("tmp.zip", "w") as zipObj:
        zipObj.write(file1.name, "file1")
        zipObj.write(file2.name, "file2")
    return "tmp.zip"


demo = gr.Interface(
    zip_two_files,
    ["file", "file"],
    "file",
    examples=[
        [os.path.join(os.path.dirname(__file__),"files/titanic.csv"), 
         os.path.join(os.path.dirname(__file__),"files/titanic.csv")],
    ],
)

if __name__ == "__main__":
    demo.launch()
```

When you download the file, it is renamed `download.zip` by default on Chrome.

### Download version 3.0.22
![file_download_bug](https://user-images.githubusercontent.com/41651716/176975733-1acf0dc9-2d65-4ac0-a56a-8a35d06218a0.gif)

That's not the case on version 3.0.12. The file is called `tmp` because that's what the prediction function returns. You can see the same behavior on this space: https://huggingface.co/spaces/radames/dpt-depth-estimation-3d-obj Was this change intentional?

### Download version 3.0.12
![file_download_correct](https://user-images.githubusercontent.com/41651716/176975756-758d94a3-6686-473a-9d07-72af220172e9.gif)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run the `zip_two_files` demo on 3.0.22 and download the file.

### Logs

```shell
-
```

### System Info

```shell
3.0.22
```

### Severity

annoying

**Comment by AeroDEmi** [comment]
Thank you for addressing the bug @freddyaboulton. This came as my output is a mesh file (file.msh) and when I try to download the file it losses the .msh extension.

**Comment by freddyaboulton** [comment]
Thank you for bringing it to our attention!

**Comment by irfan-mekic** [comment]
Any updates on this?

**Comment by freddyaboulton** [comment]
@irfan-mekic Thanks for the follow-up! 

We were working on improving the docs the last two weeks. Next we're working on the 3.2 milestone which will focus on bug fixes. I've added this issue to that milestone so someone will take a look at this soon.

**Comment by abidlabs** [comment]
Reopening as this seems to have come back as a results of #1967
