### ISSUE TITLE
Allow users to set the title in the browser tab (the <head> <title>) for Interfaces

### ISSUE THREAD

**Issue by charlesfrye** [gradio-app/gradio#1691]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
When I share my app, I want the title bar to display the app name, rather than "Gradio", as it currently does.

Users in professional and other highly polished contexts, like me, want to control branding and style.

If I bring my own hosting I can control the URL and `Interface.launch` already includes a `favicon_path` (thanks!), but AFAICT the title can't be changed, except perhaps by writing custom css.

**Describe the solution you'd like** 

The "title" kwarg to an `Interface` sets the text in an h1 header at the top -- the simplest thing would be to duplicate that information in the `<head>` section's `<title>` element.

**Additional context**  
Here's a screenshot with the Gradio name in the title position:
![image](https://user-images.githubusercontent.com/10442975/176977847-dfc1d8d1-c413-4470-b981-12e49ef8c5ca.png)

**Comment by abidlabs** [comment]
Seems quite reasonable!
