### ISSUE TITLE
problem present image segmentation using gradio

### ISSUE THREAD

**Issue by mayayank95** [gradio-app/gradio#1693]
### Describe the bug

when upload an image using gradio:
webapp = gr.interface.Interface(fn=segment, inputs="image", outputs="image")
webapp.launch(debug=True)
the grdio make some preprocessing convert the original image
array([[ 0,  0,  0, ..., 26, 26, 27],
       [ 0,  0,  0, ..., 29, 29, 27],
       [ 0,  0,  0, ..., 27, 26, 24],
       ...,
       [17, 17, 15, ..., 11, 12, 11],
       [15, 13, 10, ..., 11, 11, 10],
       [12, 10,  8, ..., 11, 11, 10]], dtype=uint8)
to [[133 114 114 ... 255 255 255]
 [133 114 114 ... 255 255 255]
 [114  95 171 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
This means changing the image's scale such that the maximum value will be 255. but the transformation is not only multiple by constant. This transformation changes the input the segmentation model expects, and I fail to get the desired output. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

after installing the segmentation_models, need to restart the notebook to load the model.

https://github.com/mayayank95/gradio_bug

### Logs

```shell
The problem not in the log is the result of the function.
```

### System Info

```shell
3.0.22
```

### Severity

blocking all usage of gradio

**Comment by FarukOzderim** [comment]
This does not look like a bug but conflict of usage, but let's think over our preprocessing perspective @abidlabs and @aliabid94.

You could disable preprocessing with Blocks and defining specific events with `_preprocess` argument being false, see [docstrings](https://github.com/gradio-app/gradio/blob/8f89270f50782493257b1a643842903356d135a1/gradio/events.py#L84). We don't have events in the docs yet but hope this helps.

See [introduction to blocks](https://gradio.app/introduction_to_blocks/) as well

**Comment by mayayank95** [comment]
hi, thanks very much for the response.

I run the following code and get an error:

import numpy as np
import gradio as gr

demo = gr.Blocks()

def flip_text(x):
return x[::-1]

def flip_image(x):
# return np.fliplr(x)
return x.max()

with demo:
gr.Markdown("Flip text or image files using this demo.")
with gr.Tabs():
with gr.TabItem("Flip Image"):
with gr.Row():
image_input = gr.Image()
image_output = gr.Textbox()#gr.Image()
image_button = gr.Button("Flip")

image_button.click(flip_image, inputs=image_input, outputs=image_output,
_preprocess=False)

demo.launch()

I will happy if you can help me.

**Comment by mayayank95** [comment]
if I use the preprocess argument, the input to the function is a string,
how do I convert this to an image?

**Comment by FarukOzderim** [comment]
Hey there!

[This](https://github.com/gradio-app/gradio/blob/8f89270f50782493257b1a643842903356d135a1/gradio/components.py#L1443) is the preprocess function in the Image component. You can make use of that.

**Comment by abidlabs** [comment]
Hi @mayayank95 it's hard to know from this issue what the problem you are facing is. Can you please provide a minimal code example that is not working as expected. Please use the backticks (`) and properly format your code so that we can reproduce it easily. Please also attach the image you are using so that we can try it to see what is wrong.
