### ISSUE TITLE
Disable Preprocessing within Interface

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1707]
- [x] I have searched to see if a similar issue already exists.

We might have parameters to disable preprocessing or postprocessing in Interface, just like we do it events. See #1693 as well

**Comment by abidlabs** [comment]
Would it be sufficient to have a `"base64"` `type` for images, videos, audio, file, etc.? We were discussing that in the context of #1679 and that would allow us to do this without adding another parameter.

**Comment by FarukOzderim** [comment]
It looks like it would solve the main problem.

While we have preprocess disable parameter in events, we don't have it in Interface. And it can be OK as well, because we would like to forward any advanced use-cases to Blocks, right?

**Comment by abidlabs** [comment]
Exactly

**Comment by abidlabs** [comment]
So let's close this issue in favor of #1679
