### ISSUE TITLE
No URL info post when using Python script, until first try on http://localhost:7860/. Working fine on ipynb

### ISSUE THREAD

**Issue by marconi1964** [gradio-app/gradio#1708]
### Describe the bug

Gradio is a very great tool, so I can focus on ML algorithm and post on web without html knowledges. 

I tried it first on ipynb, it works well. Then tried it with Python script, so I can run the script in background, with the following CLI command.

`
$ nohup python3 mnist-demo.py >mnist-log.txt 2>mnist-err.txt &
`

But I could not find URL information in the log, like below, as I could on ipynb. Even, I was not sure if Gradio was working properly, as no message from the log. (no error, either). 
```
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://23476.gradio.app
```

I did find later that if I open local browser http://localhost:7860/ and try my ML program, it did show the URL info in the log after then. It did cause users, like me, some confusion. I have to try on local first, before I get the public URL to try on internet web app.

```
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://23476.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces (https://huggingface.co/spaces)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Python script running in background
`$ nohup python3 mnist-demo.py >mnist-log.txt 2>mnist-err.txt &`

#### part of mnist-demo.py, related to Gradio
``` part of mnist-demo.py, related to Gradio
# In[34]:

import gradio as gr

# In[35]:

def recognize_digit(img):
  img = img.reshape(1,784)
  prediction = model.predict(img).flatten()
  labels = list('0123456789')
  return {labels[i]: float(prediction[i]) for i in range(10)}

# In[37]:

demo = gr.Interface(fn=recognize_digit, inputs="sketchpad", outputs="label", title="Marconi's MNIST recognition").launch(share=True)
```

#### part of mnist-log.txt before I tried on http://localhost:8760/
```
Epoch 50/50
469/469 [==============================] - 3s 6ms/step - loss: 0.0015 - accuracy: 0.9913
313/313 [==============================] - 1s 3ms/step - loss: 0.0019 - accuracy: 0.9876
測試資料正確率 98.76%
313/313 [==============================] - 1s 2ms/step
神經網路判斷為: 3
313/313 [==============================] - 1s 3ms/step - loss: 0.0019 - accuracy: 0.9876
loss: 0.0019133613677695394
正確率 0.9876000285148621
```

#### part of mnist-log.txt after my first trial on http://localhost:8760/
```
Epoch 50/50
469/469 [==============================] - 3s 6ms/step - loss: 0.0015 - accuracy: 0.9913
313/313 [==============================] - 1s 3ms/step - loss: 0.0019 - accuracy: 0.9876
測試資料正確率 98.76%
313/313 [==============================] - 1s 2ms/step
神經網路判斷為: 3
313/313 [==============================] - 1s 3ms/step - loss: 0.0019 - accuracy: 0.9876
loss: 0.0019133613677695394
正確率 0.9876000285148621
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://49996.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces (https://huggingface.co/spaces)
1/1 [==============================] - 0s 92ms/step

```

### Screenshot

The log above the yellow line was before I tried on http://localhost:7860/, no URL info. 
The log below the yellow line was after my first trial on http://localhost:7860/, with URL info post.

![image](https://user-images.githubusercontent.com/7934435/177267151-f80e79db-fdbd-43fd-940a-299c9efd9092.png)

### Logs

```shell
No log with debug=True
```

### System Info

```shell
Gradio verion : 3.0.22
Linux : Linux 5.4.0-120-generic #136~18.04.1-Ubuntu SMP 
Microsoft Edge : Version 103.0.1264.44 (Official build) (64-bit)
```

### Severity

annoying

**Comment by FarukOzderim** [comment]
Hello @marconi1964, thx for the report.

I don't know what's the cause, but it does not look like it is related to Gradio, does it? Because we print out the url's when you directly run Gradio with python.

```
$ python run.py

Running on local URL:  http://127.0.0.1:7860/

```


Here's a solution for your case:

```
if __name__ == "__main__":
    app, local_url, share_url = demo.launch(prevent_thread_lock=True)
    print(f"local_url: {local_url}, share_url: {share_url}, FastAPI app: {app}")
```

**Comment by abidlabs** [comment]
Going to close, but feel free to reopen if you are still running into an issue @marconi1964
