### ISSUE TITLE
Dragging another image into a `gr.Image` doesn't work.

### ISSUE THREAD

**Issue by hollance** [gradio-app/gradio#1711]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

If the image well from a `gr.inputs.Image` is empty, then dragging an image into it works as expected. 

However, dragging another image into it afterwards will load that image into the browser window itself, not into the image well, thereby exiting the gradio app or opening the image into a new tab (depending on the browser).

**Describe the solution you'd like**  

The user needs to press the Clear button to remove the old image before the image well accepts a new image being dragged into it. That is unintuitive. It would be better if new drags were always accepted.

**Additional context**  

n/a

**Comment by FarukOzderim** [comment]
@pngwn there seems to be issues with Image component, could you take a look?

**Comment by abidlabs** [comment]
If there is already an image that's uploaded, I think it's reasonable to have the users clear the image before uploading again.

**Comment by hollance** [comment]
I feel that if I could drag an image into that control once, I should be able to do it twice. 

I'm used to using an operating system that lets you drag stuff everywhere (macOS), so having to click a Clear button to allow a new drag is totally unintuitive for me and I keep doing it wrong, even though I know I "should" press Clear first.

So from a UI perspective, I think the way it currently works is confusing and incomplete. For people who don't drag their images into things, it's probably fine. For drag-and-droppers like me, it feels like a "web UI" in the bad sense of the word. (By that I mean, if a native Mac app worked this way, it wouldn't get very good reviews.)

**Comment by hysts** [comment]
As a gradio user, I agree with @hollance. Recently, I've been using gradio to make CV related apps and trying out demo apps on Hugging Face Spaces, but I often forget to press the clear button before dropping another image. I find it tedious to have to press the button every time. I think there are many people who feel the same way.

**Comment by abidlabs** [comment]
Great feedback, thank you @hollance and @hysts! We'll look into it then!

**Comment by pngwn** [comment]
@hollance @hysts Do you think should be true for all image variants? Should as when sketching or masking over an image, not just when there is only a simple image input?

**Comment by hollance** [comment]
I feel if there is an option for uploading an image, drag-and-drop should work too. But if there is no option to upload anything, only drawing, then it seems unnecessary to add drag-and-drop.

**Comment by hysts** [comment]
Agreed.

**Comment by TinyForge** [comment]
This is no longer working in 4.36.0

**Comment by pngwn** [comment]
@TinyForge could you create a new issue with a reproduction please?
