### ISSUE TITLE
Miscellaneous formatting improvements to website after PR 1578

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1717]
- [x] I have searched to see if a similar issue already exists.

In the review of #1578, we noticed some miscellaneous things we'd like to improve about the new website design:

- [x] No sidebars in the guides

- [x] **kwargs in Series/Parallel is shown as required when it is not
![image](https://user-images.githubusercontent.com/41651716/177609864-f10d2acb-23de-4684-8436-118dabfd27c8.png)

- [x] No example Number/Text (other input component) in the docs
### Old website
![image](https://user-images.githubusercontent.com/41651716/177611117-ffa2f3d4-8665-49c3-a5a2-68924bad2471.png)
### Current website locally
![image](https://user-images.githubusercontent.com/41651716/177611177-ed6d26ec-93c1-470d-93b4-683a95eff201.png)

- [x] No example output HighlightedText component in the docs
### Old Website
![image](https://user-images.githubusercontent.com/41651716/177613303-d43b336e-624e-4f04-a149-3f63fec1f9d7.png)
### Current website locally
![image](https://user-images.githubusercontent.com/41651716/177613264-1310669d-e569-4b65-bf17-3179dbc62ac4.png)

- [x] Missing docstring descriptions for parameters of `Row`, `Column`
![image](https://user-images.githubusercontent.com/41651716/177613958-26b8caae-27ce-4eb8-8151-aa71ee1a7563.png)

- [x] Missing description for `color_map` in `Chatbot`
### Old website
![image](https://user-images.githubusercontent.com/41651716/177614151-c2aac094-96f6-470e-9db1-4850c5896351.png)
### Current website locally
![image](https://user-images.githubusercontent.com/41651716/177614111-d93b7ec7-044b-4cfd-b7ed-078176bd9c00.png)

- [x] The text on "Developing faster with reload mode" guide is not aligned
![image](https://user-images.githubusercontent.com/41651716/177614680-51f2fd4b-8e1c-4ff2-b46a-37cef73538bd.png)

**Comment by aliabd** [comment]
Thanks for putting this together @freddyaboulton, will start checking them off today. 

Just a note that all the embedded example components are currently missing on the docs (not just Textbox and HighlightedText). We removed them because we had hardcoded the config, and they wouldn't update if anything changed. I'm going to open a PR soon to launch and embed them the same way we do for demos.

**Comment by freddyaboulton** [comment]
Thats awesome @aliabd !

**Comment by aliabd** [comment]
@freddyaboulton let's remove the sidebar task from here (or check it off) as it's on hold right now and if we do bring them back we will likely try to redesign them
