### ISSUE TITLE
Expose Reset/Clear button as a component

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1719]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As a gradio user, I would like an easy way to add a clear button to a demo built with the blocks api. 

Right now, it's not clear how to reset components to their original states with blocks (see #1672). The right approach involves setting the `_js` parameter in a button update and that parameter is not documented anywhere. 

**Describe the solution you'd like**  
Add a `gr.Reset` component that is a short-hand for resetting a list of components to their original states. I think this demo adapted from #1672 showcases a possible api

```python
import gradio as gr

demo = gr.Blocks()

with demo:
    text = gr.Textbox()
    explanation = gr.HighlightedText()
    with gr.Row():
        submit_btn = gr.Button(value="Submit")
        reset = gr.Reset(components=[text, explanation])
    samples = gr.Dataset(
        components =[text],
        samples=[["Example of a text. This should reset highlighted text but does not."]]
    )
    submit_btn.click(
      fn = lambda text: gr.HighlightedText.update(value=[("Fake output", 1)]), inputs=[text], outputs=[explanation]
    )
    samples.click(lambda sample: gr.Textbox.update(value=sample[0]),
                  inputs=[samples],
                  outputs=[text])

demo.launch()
```

**Additional context**

**Comment by fffiloni** [comment]
Subscribed to be notified when gr.Reset() is released :)

**Comment by freddyaboulton** [comment]
I can pick this up after the bug bash sprint. Should be straight forward to do it on the backend.
