### ISSUE TITLE
100% single core utilization by server launch

### ISSUE THREAD

**Issue by usbhub** [gradio-app/gradio#172]
When running the server I noticed it was using 100% of one of my cores, I looked at the code and here: https://github.com/gradio-app/gradio/blob/7b7f455dcad12d975e0f170d1b3b2161c4987e22/gradio/interface.py#L353-L354 you are busy looping. I believe you can just put a time.sleep(1) like you have in some of the other loops.

**Comment by aliabid94** [comment]
@abidlabs can you post any update here?

**Comment by aliabid94** [comment]
Fixed now.
