### ISSUE TITLE
Internal Server Error when trying to log in

### ISSUE THREAD

**Issue by skoetje** [gradio-app/gradio#173]
Hello, whenever I try to login I get this error:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

It happens on multiple browsers, multiple accounts. Is there a server issue?

**Comment by abidlabs** [comment]
Hi @skoetje can you try now?

**Comment by skoetje** [comment]
Yes it works now, many thanks! What was the problem?

**Comment by abidlabs** [comment]
Thanks, we're migrating to a new infrastructure for Gradio Hosted, so I think you were just caught in an intermediate state. Our new infrastructure should be up next week!
