### ISSUE TITLE
Realtime Video?

### ISSUE THREAD

**Issue by ajaykrishnan23** [gradio-app/gradio#174]
Hi 
I had checked through the documentation regarding how I could use radio for real-time video analysis ie. open webcam, process frame by frame and display real-time webcam output side by side but could not find any. Is this feature yet to be implemented or am I missing out? 
It would be a great help if you could respond 
Thank you

**Comment by abidlabs** [comment]
Hi @ajaykrishnan23 this feature is yet to be implemented, but it's a great suggestion! We'll add it to our roadmap

**Comment by ajaykrishnan23** [comment]
Hi 
`gradio.Interface(fn=classify_image, live=True, inputs=gr.inputs.Image(source="webcam"), outputs=gr.outputs.Image()).launch()`
I looked into it and was able to use this instead. But It has been quite slow. Looking forward to the updates!
