### ISSUE TITLE
ColorPicker component does not appear in documentation

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1743]
### Describe the bug

The color picker component does not show up in the documentation. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Go to gradio.app/docs/

### Screenshot

![image](https://user-images.githubusercontent.com/41651716/178077152-e9d4401f-2e01-406c-b889-6069fcea7de7.png)

### Logs

```shell
-
```

### System Info

```shell
-
```

### Severity

annoying

**Comment by taimaruuu** [comment]
I'm new to helping on opensource projects but would love to help get this resolved.

**Comment by FarukOzderim** [comment]
@aliabd would you like to give directions to @taimaruuu a little bit?
