### ISSUE TITLE
Badly visible text in dark mode on HuggingFace

### ISSUE THREAD

**Issue by robinhad** [gradio-app/gradio#1746]
### Describe the bug

If you select dark mode on HuggingFace, text in `description` and `article` fields is not visible, because it's dark grey text on black background.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Can be observed here: [https://huggingface.co/spaces/robinhad/ukrainian-tts](https://huggingface.co/spaces/robinhad/ukrainian-tts)
1. Select dark mode on HF.
2. Use `gradio.Interface`
3. Input text into `description` or `article` fields.
4. See dark grey text on black background.

### Screenshot

![зображення](https://user-images.githubusercontent.com/5759207/178154182-9cd7f5a1-ef64-4c89-95b0-9a116ae4476c.png)

### Logs

```shell
-
```

### System Info

```shell
Latest Firefox, Edge.
Latest version of gradio on HF.
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Thank you for filing @robinhad ! For whoever picks this up, this seems related to #1725

**Comment by robinhad** [comment]
seems like on HuggingFace, dark theme doesn't implement `.dark .prose` and `.dark .prose a` css classes, so classes from white theme are active, but locally everything works fine

**Comment by robinhad** [comment]
@aliabid94 is fix deployed to huggingface? there is still grey text in black background

**Comment by aliabid94** [comment]
The way huggingface spaces works is that your gradio version is pinned to the version you used at launch (Unless you explicitly change it with the `sdk_version` line in the readme). So even if you restart your app, it will use the version of gradio used when you first made the space.

I made a pseudoclone of your repo, but set the gradio version to 3.1.7 here (https://huggingface.co/spaces/aliabid94/test_ukr). You can see it has been updated.

**Comment by BramVanroy** [comment]
Hi @aliabid94 thanks for working on this! I'll ping the HF team about this when you're done. 

I find some issues here with code and strong tags.

https://huggingface.co/spaces/evaluate-metric/accuracy

**Comment by robinhad** [comment]
@aliabid94 thank you
