### ISSUE TITLE
Use custom UI components in Gradio

### ISSUE THREAD

**Issue by jrabary** [gradio-app/gradio#1752]
For some use cases it may be interesting to develop custom UI components for Gradio. For example, build a demo or even an application for AI assisted Image annotation or for Active Learning which demands specific user inter-action that are not currently available in Gradio.

The challenge are:
- develop these custom UI components in a separate and independent repository and being able to inject them in a Gradio Application. Related issue have been open at #1743, one of the  proposed solution is to developed the component inside Gradio repo which we want to avoid. 
- add multiple inter-action with the backend (several UI action buttons that call different backend function)

We open this issue to discuss about the possible solutions the this problem.

**Comment by freddyaboulton** [comment]
@jrabary There's info on this post: https://discuss.huggingface.co/t/join-the-hugging-face-discord/11263

You basically just have to click on the invite link on that post. There are channels for all hugging face libraries (not just gradio) as well as seminars and study groups!
