### ISSUE TITLE
Allow changing Flag button text

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1764]
- [x] I have searched to see if a similar issue already exists.

Right now, the flagging options only allow to add "Flag as X", but I would like to change the "Flag" name to something entirely different. Is this a use case that could potentially be supported?

**Comment by freddyaboulton** [comment]
Seems reasonable to me @osanseviero ! 

Technically this should already be possible with the blocks api - once #1675 is done, it will be clearer how to do that - but I agree that we should make this easier for the interface api as well.
