### ISSUE TITLE
Background color (and app) does not extend to entire window in 3.0.24

### ISSUE THREAD

**Issue by charlesfrye** [gradio-app/gradio#1772]
### Describe the bug

Previously, a Gradio app in its own window took up the entire window vertically, with the "built with gradio" and other footer information at the bottom and the title at the top. Similarly, the app took up all horizontal space.

In 3.0.24, the app instead takes up all horizontal space but not all vertical space. In dark mode, this looks particularly bad, since the browser fills the rest of the space with a light background (see screenshots below).

The desired behavior is in all versions I've used up to 3.0.17 and in 3.0.21.

Looking at the styling, it appears that the `min-h-screen` class is not applied to the div that contains the app. Removing that class from the app's div in an earlier version gives the same undesired behavior.

While I would prefer the footer to return to its previous position, it would also be acceptable if the area that is currently filled with light color was instead filled with the same background color as the app.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I've uploaded images to Docker Hub for repro if desired.

You can run the server with `docker run -p$OPENPORT:11700 $image_name`

Repository on Docker Hub [here](https://hub.docker.com/repository/docker/fullstackdeeplearning/app-gradio).

Image with bug is tagged `3.0.24`, [here](https://hub.docker.com/layers/252509533/fullstackdeeplearning/app-gradio/3.0.24/images/sha256-7ae8611b5b7e0c156a4b8cf0406de9960026df3289ab5bb21a9e2937316ffd40).

Image without bug is tagged `3.0.21`, [here](https://hub.docker.com/layers/252517260/fullstackdeeplearning/app-gradio/3.0.21/images/sha256-7f63f60e046156bee47af7da16dfa4341e46a5a84e95f23559244dee930cfdb7?context=repo).

## 3.0.24 - not as desired

![image](https://user-images.githubusercontent.com/10442975/178624023-a8cbbdaa-d91d-4369-bd50-94c49bfc8ff3.png)

## 3.0.21 - as desired

![image](https://user-images.githubusercontent.com/10442975/178624659-8c89882f-e29e-4075-8539-ee48c95e6785.png)

## 3.0.21 without `min-h-screen` - not as desired

![image](https://user-images.githubusercontent.com/10442975/178625224-99228e54-fa5b-4865-960d-ab61d31e49fa.png)

### Logs

```shell
n/a
```

### System Info

```shell
server was gradio 3.0.24 and 3.0.21 running on (dockerized and bare metal) linux, client was a chrome browser running on OS X
```

### Severity

blocking upgrade to latest gradio version

**Comment by freddyaboulton** [comment]
Thank you so much for filing @charlesfrye !

Agree that this is a regression. We’ll take a look !
