### ISSUE TITLE
Why is gr.dataframe not found in official documentation?

### ISSUE THREAD

**Issue by tt0203** [gradio-app/gradio#1773]
Is the component description missing from the official documentation?
Also, is there a component that supports arrays directly?
Also, I used HuggingFece to build an API interface for uploading Excel files on gr.File. How to submit the body part?

I build the app address is: https://huggingface.co/spaces/changxin/pq

Also you can look at: https://hf.space/embed/changxin/pq/+

API address is: https://hf.space/embed/changxin/pq/+/api/df

Input Payload

{

"data": [

(List[Dict[name: str, data: str]]), // represents str, data: str]]): List of JSON objects with filename as 'name' property and base64 data as 'data' property of 'Select the Excel File' File that you want to read component

]

}
How do I build the body part of this post api?

**Comment by freddyaboulton** [comment]
Thanks for filing @tt0203 ! Yep, `Dataframe` should be a part of the documentation I'll make a note of this in #1673 .

Regarding the body of the post api, I think something alone these lines will work:


```python
import os
import requests
from gradio.processing_utils import encode_file_to_base64

data = encode_file_to_base64(filepath)

prediction = requests.post(url, json={"data": data, "name": filepath, "size": os.path.getsize(filepath)})
```

Can you explain your use case a bit more? Curious why you're trying to hit the api manually.
