### ISSUE TITLE
'gradio' has no attribute 'Examples'

### ISSUE THREAD

**Issue by duerrsimon** [gradio-app/gradio#1781]
### Describe the bug

I'm trying to use Examples as described here https://gradio.app/docs/#examples

I upgraded to latest gradio 3.0.24 using pip but this does not seem to work. 

I would urge you to version the documentation and the releases more carefully. This worked differently before but from the documentation it is not clear for which release of gradio this should be working. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr
gr.__version__
gr.Examples()

```

### Logs

```shell
AttributeError: module 'gradio' has no attribute 'Examples'
```

### System Info

```shell
3.0.24
```

### Severity

blocking upgrade to latest gradio version

**Comment by duerrsimon** [comment]
I think it is an absolute necessity to have the docs correspond to released versions and have old docs accessible. I am still on 3.0.11 because some stuff was still broken in newer releases. This is how any good open source software documentation works such as the one you linked but also https://matplotlib.org/stable/index.html and many others. 
If you cannot implement the switcher now I would at least add some kind of version indication somewhere to the header of the site like e.g seaborn does. 

Especially new developers will stop using gradio if docs don't match released software. This might be okay if the release is labeled beta or alpha or so but if I see release 3.0 I expect a stable api and docs that match the release. 

I'm closing this now because #1650  would fix this.

**Comment by freddyaboulton** [comment]
Yep I hear you! I'll try to get this done in our documentation milestone
