### ISSUE TITLE
UI local dev doesn't work as described in the documentation

### ISSUE THREAD

**Issue by jrabary** [gradio-app/gradio#1782]
### Describe the bug

We are not able to set up the local development environment for UI by following https://github.com/gradio-app/gradio/tree/main/ui 

- pnpm i works 
- pnpm dev failed by displaying an infinite

```
pnpm dev --filter @gradio/app "--filter" "@gradio/app" "--filter" "@gradio/app" "--filter" "@gradio/app" "--filter" 

"@gradio/app" "--filter" "@gradio/app" "--filter" "@gradio/app" "--filter" "@gradio/app" "--filter" "@gradio/app" "--filter" 
"@gradio/app" "--filter" "@gradio/app" "--filter" "@gradio/app" "--filter" "@gradio/app" "--filter" "@gradio/app" "--filter" 
"@gradio/app" "--filter" "@gradio/app" "--filter" "@gradio/app" "--filter" "@gradio/app" "--filter" "@gradio/app" "--filter" "@gradio/app" "--filter" "@gradio/app" "--filter" "@gradio/app" "--filter" "@gradio/app"
```

- pnpm build failed with

```
pnpm build:local --filter @gradio/app --emptyOutDir

 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  not found: build:local
 ELIFECYCLE  Command failed with exit code 1.
```

All of this from pristine clone of the master branch.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
git clone https://github.com/gradio-app/gradio.git
cd gradio/ui
pnpm dev
```

### Logs

```shell
None
```

### System Info

```shell
pnpm 7.2.1
node 18.3.0
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
@jrabary Thanks for filing! You need pnpm version 6: https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md#contributing-to-gradio 

I think that should fix your problem. Please let us know if not.

**Comment by jrabary** [comment]
Switching to pnpm@6.32.11 solve the problem. Thanks.
