### ISSUE TITLE
Consolidate logic for documenting classes and determining which demos to run on website

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1783]
Right now we determine which classes to document and which demos to run in two separate places. With `generate_documentation` we collect all classes tagged with `@document` and in `map_demos` we search through all python files looking for the `Demos:` tag. 

This issue proposes that we move the "identify which demos to run" logic to search documentation. 

> Makes sense to me. Something we could implement in the future that's even cleaner is to search all the documentation returned from `generate_documentation()` to check demos within the docstrings only.
> 
> _Originally posted by @aliabid94 in https://github.com/gradio-app/gradio/pull/1769#pullrequestreview-1036860824_

**Comment by aliabd** [comment]
Closing this issue because [PR 2281](https://github.com/gradio-app/gradio/pull/2281) removed` map_demos.py`. All demos in `/demos` are now uploaded to spaces. And `generate_documentation` is used for figuring out which to embed. (in `docs/__init__.py`)
