### ISSUE TITLE
Refactor tests to use pytest fixtures and plain asserts

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1784]
We should consider rewriting our tests to the pytest style (functions prefixed with `test_` and plain asserts) as opposed to using unittest.Testcase classes. Switching over to just plain functions and assets makes it really easy to use pytest's built in fixtures and makes it easy to integrate with community-built fixtures. Pytest fixtures can do everything we can do with `setUp` and `tearDown`.

Context:

I think this is a great reason to consider switching over to pytest fully. Pytest comes with a built in fixture called `capsys` that does this for you. 

This is how we can rewrite one of the tests here in this style:

```python
def test_integration_wandb(capsys):

    wandb.log = mock.MagicMock()
    wandb.Html = mock.MagicMock()
    demo = gr.Blocks()
    with demo:
        gr.Textbox("Hi there!")
    demo.integrate(wandb=wandb)

    text = capsys.readouterr()
    assert text.out.strip() == "The WandB integration requires you to `launch(share=True)` first."
    demo.share_url = "tmp"
    demo.integrate(wandb=wandb)
    wandb.log.assert_called_once()
```

Running `pytest test/test_blocks.py::test_integration_wandb` will work. I'll create an issue so that we don't forget and can continue discussing there.

_Originally posted by @freddyaboulton in https://github.com/gradio-app/gradio/pull/1776#discussion_r920252997_

**Comment by freddyaboulton** [comment]
@FarukOzderim Agreed that it's not high priority.

With this kind of issue, it may be best to use a gradual approach rather than all-or-nothing.

Rather than someone re-writting the entire test suite in a couple of days, it may be best to start writing new tests in the pytest style and encourage PR authors to do the same.

**Comment by FarukOzderim** [comment]
> @FarukOzderim Agreed that it's not high priority.
> 
> With this kind of issue, it may be best to use a gradual approach rather than all-or-nothing.
> 
> Rather than someone re-writting the entire test suite in a couple of days, it may be best to start writing new tests in the pytest style and encourage PR authors to do the same.

Totally agree, I actually have started to do it without mentioning it 😿, lets ping this out in slack as well. We can unittests to pytest style whenever we refactor a test as well.
