### ISSUE TITLE
Serving Voila via GradIO

### ISSUE THREAD

**Issue by samiit** [gradio-app/gradio#179]
Hi everyone,

I like the GradIO's message parsing interface that allows us to host and run the code at our end, and only allow a shareable link to the outside world.

I wanted to know whether I can serve my own Voilà instance of a notebook via GradIO? In this way we can go beyond the features that GradIO offers (that are quite extensive), and serve Apps with customized UI for prototyping.

Thanks,
Sam

**Comment by abidlabs** [comment]
Hi @samiit, for a use case like that, I suggest running your notebook locally and then using ngrok to make it accessible publicly. Look at: https://ngrok.com/

**Comment by samiit** [comment]
Salam/Namaste Abid

I was delighted to see your last year's PyData Riyadh talk after getting introduced to GradIO via Tanishq's talk on CycleGAN.

Thanks for your response and I will check out more on the link you shared.

Sam
