### ISSUE TITLE
gr.Parallel integration with Ray Serve

### ISSUE THREAD

**Issue by zcin** [gradio-app/gradio#1791]
### Context and Problems
Currently, gr.Parallel takes in multiple functions and displays the results simultaneously, but runs the user provided functions sequentially on the backend.

Proposal: an interface change in Gradio that allows it to plug into the parallelization framework `ray`. Users can use it on an opt-in basis. There are several options here. We recommend option 2.

## Option 1: Flag-based approach
The ray backend is turned on/off with a flag that the user passes into gr.Parallel or gr.Interface.

#### Pros
* Most natural to implement, easily opt-in UX
#### Cons
* Most intrusive to the gradio code base (can be alleviated with some sort of plugin system)
* Either have to import in the middle of the code, which is not pretty, or introduce Ray as a soft dependency of Gradio (for example, try import ray and enable this code path on flag; or do nothing).
### Usage
Previously:
```python
demo = gr.Parallel(io1, io2)
```
Now:
```python
demo = gr.Parallel(io1, io2, backend="ray")
```

### Pseudo-Code
Changes to `block.launch()`:
```python
import ray
from ray import serve
...
def launch(...):
   # Reroute to send request to model served on Ray Serve
   if self.backend == "ray":
       start ray cluster and ray serve backend
       for predict_fn in self.predict:
           deploy predict_fn as serve deployment
           new predict_fn = send request to serve deployment
```
Changes to `interface.run_prediction()`:
```python
def run_prediction(...):
   for predict_fn in self.predict:
       prediction = predict_fn()
 
   if self.backend == "ray":
       return ray.get(predictions)
   else:
       return predictions
```

## Option 2: Gradio supports standard Python interfaces
Integrate with asyncio.Future or concurrent.futures.Future in Gradio’s backend.
#### Pros
* Non-intrusive
* Gradio would only need to maintain integration with asyncio.Future or other standard Python objects. 
#### Cons
* gr.Interface will need to be changed into async
* User will need to start ray backend manually and explicitly “rayify” their gr.Interface
* (Can explore other options) Currently, serve deployments are made when instantiating gr.Parallel or gr.Interface, instead of at launch()
### Usage
Previously:
```python
demo = gr.Parallel(gr.Interface(greet, "text", "text")), gr.Interface(goodbye, "text", "text"))
demo.launch()
```
Now:
```python
serve_client = start_ray_backend()
demo = gr.Parallel(
   rayify_interface(serve_client, gr.Interface(greet, "text", "text")),
   rayify_interface(serve_client, gr.Interface(goodbye, "text", "text"))
)
demo.launch()
```

### Pseudo-code
```python
def rayify_interface(serve_client, io: gr.Interface, names=None):
   for predict_fn in io.predict:
       deploy predict_fn as serve deployment
       new predict_fn = wrap in asyncio.future(send request to serve deployment)
   io.predict = new predict_fn's
   return io
```
Code changes to `interface.run_prediction()`:
```python
async def run_prediction(...):
   for predict_fn in self.predict:
      prediction = predict_fn(*processed_input)
      ...
   for predictions that are asyncio.Futures:
      async_predictions = await asyncio.gather(*predictions)
   return async_predictions and sync_predictions
```

## Option 3: Explicit copy of interface class
An external, explicit ray.Interface that replaces gr.Interface. Essentially wraps gr.Interface that adds a ray backend (specifically overrides blocks.launch() and interface.run_prediction()).
#### Pros
* Easy for users to use
* Non-intrusive in Gradio codebase
#### Cons
* Hard to maintain across interface and version boundaries.
* Duplicate code. 
### Usage
Previously:
```python
demo = gr.Parallel(io1, io2)
```
Now:
```python
demo = ray.RayParallel(io1, io2)
```

### Pseudo-Code
```python
class RayParallel(gr.Parallel):
   def launch(self, *args, **kwargs):
      [same code as in Option 1]
      super().launch(*args, **kwargs)
   def run_prediction(self, *args, **kwargs):
      [same code as in Option 1]
```

**Comment by FarukOzderim** [comment]
Thanks for identifying this point @zcin, this definitely does not align with our async library.
We've actually wanting to refactor Interface for it to support async functions with #1212. I've created #1823 to follow Parallel being concurrent as well.

**Comment by FarukOzderim** [comment]
It seems I misunderstood the issue a little bit, it is not just about #1823 but a broader issue. Thanks to @abidlabs for the heads up.

**Comment by abidlabs** [comment]
Hi @zcin is there still interest in this from the Ray side? We haven't heard feature requests from our users on this front, so I suggest we can go ahead and close this.

**Comment by zcin** [comment]
Sounds good, we can close this for now, and revisit in the future if interest arises again!
