### ISSUE TITLE
Some website embedded demos not loading (or flaky)

### ISSUE THREAD

**Issue by aliabid94** [gradio-app/gradio#1792]
e.g. first demo in https://gradio.app/embedding_gradio_demos/

**Comment by abidlabs** [comment]
Working for me? Can you try clearing cache

<img width="960" alt="image" src="https://user-images.githubusercontent.com/1778297/179013800-ae56f5d2-b9d3-4600-ba42-98dd62a1cf94.png">

**Comment by abidlabs** [comment]
@aliabid94 @aliabd and I just synced on this issue. This JS error shows up in the console whenever demos don't work:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'classList')
    at unscoped_mount (index.6ae7de8d.js:8271:10)
    at index.6ae7de8d.js:8287:3
unscoped_mount @ index.6ae7de8d.js:8271
(anonymous) @ index.6ae7de8d.js:8287
```
