### ISSUE TITLE
Standardize return types in the backend

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1798]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As a gradio user and developer, I wish the return type of the predict route was more predictable.

Right now it is very flexible.

This is the return type:

```python
return {
    "data": output,
    "duration": duration,
    "average_duration": block_fn.total_runtime / block_fn.total_runs,
}
```

The problem is that `data` can be a list of pretty much anything: text, numbers, interpretation output, filepaths, dataframes, updates. 

This makes the return type unpredictable - which makes it hard to maintain the front-end and also may be putting a burden to our users who hit the api manually.

**Describe the solution you'd like**  
Standardize the return types of the `data` key in the return type.

This is a sketch of how it could go: 

```python
class Update(BaseModel):
    label: str
    show_label: bool
    visible: bool
    value: float | str | DataframeData
    minimum : float | None
   <more fields>

class PredictResponse(BaseModel):
   data: List[Update]
   duration: float
   average_duration: float
```

**Additional context**

**Comment by pngwn** [comment]
This is exactly what I had in mind @freddyaboulton.

**Comment by abidlabs** [comment]
To clarify, would we have a single `Update` class with all of the parameters across all components? Or would we have separate `Update`'s for each component?

**Comment by abidlabs** [comment]
Along similar lines, when the backend function returns an update, it can either be:
* a dictionary created by `gr.update()`
* a single value returned by the function

We should standardize this (convert everything to a dictionary) before being passed into the frontend

**Comment by freddyaboulton** [comment]
This got done in the v4 branch!
