### ISSUE TITLE
CheckboxGroup init parameter `value` is renamed as `default` 

### ISSUE THREAD

**Issue by kleinay** [gradio-app/gradio#1808]
### Describe the bug

Looking at the [docs](https://gradio.app/docs/#checkboxgroup) it seems that the parameter to set the initial selected items within a `CheckboxGroup` is `value`. This is also what I could see when looking at the [code at Github](https://github.com/gradio-app/gradio/blob/9b9477abd83d6827abee4a83f0e180b171a43ceb/gradio/components.py#L956), but de-facto, the parameter name is `default`.

This doesn't work:
```python
gr.inputs.CheckboxGroup(["option1", "option2"], value=["option1"])
```

But this does:
```python
gr.inputs.CheckboxGroup(["option1", "option2"], default=["option1"])
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
gr.inputs.CheckboxGroup(["option1", "option2"], value=["option1"])
```

### Logs

```shell
<ipython-input-33-6d96105f496b> in <module>()
----> 1 gr.inputs.CheckboxGroup(["list", "of", "options"], value=["list"])

TypeError: __init__() got an unexpected keyword argument 'value'
```

### System Info

```shell
gradio version = 3.0.26
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Thank you for filing @kleinay !

The gr.inputs and gr.outputs modules have been deprecated which is why they’re not reflected in the docs.

Can you try again with gr.CheckBoxGroup?

**Comment by freddyaboulton** [comment]
@kleinay Going to close as I think the issue was fixed by using `gr.CheckboxGroup`!
