### ISSUE TITLE
TUI Image Editor changes the image pixel values.

### ISSUE THREAD

**Issue by praeclarumjj3** [gradio-app/gradio#1810]
### Describe the bug

Hi, thanks for releasing the great gradio tool. This issue revolves around the TUI Image Editor used when we set the `tool='editor'` in the `gr.inputs.Image` component. 

**Setting**: We use the Image component (let's call it _IM_) with `tool=editor.` After uploading the image to  _IM_, we don't draw anything on the image. Instead, we click the edit option and save the image **without any drawing**. Now, if we compare the pixel values of the post-saving image to the original image, they don't match. I have attached a recording of the practical issue.

I am comparing the original image and the drawn-on image to compute the mask region for my inpainting demo. I use `gradio==2.9.4`.

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

I am attaching the files required to reproduce the demo. Execute the steps below:

- `pip install -r requirements.txt`
- `python extra.py`
- Upload the load same image to both input components.  
- Click on the edit option for the Mask Component. Save the Mask Image without any editing. 
- The hole is calculated using the pixel-wise difference between the Image and Mask.
- The `Image with Hole` does not resemble the original Image.

[extras.zip](https://github.com/gradio-app/gradio/files/9128256/extras.zip)

### Screenshot

https://user-images.githubusercontent.com/54928629/179417187-a0a56cc9-108f-442a-b4c8-2d84ee79fd9b.mp4

### Logs

```shell
N/A
```

### System Info

```shell
- Gradio Version: 2.9.4
- Operating System: Linux / macOS
- Browser: Google Chrome
```

### Severity

serious, but I can work around it

**Comment by pngwn** [comment]
We aren't using TUI any more, so this isn't valid.
