### ISSUE TITLE
Flag can not create an appropriate CSV file when a textbox / text has a comma  

### ISSUE THREAD

**Issue by kmkarakaya** [gradio-app/gradio#1811]
### Describe the bug

Flag can not create an appropriate CSV file when the interface have a textbox / text which includes a comma .
The CSV file columns are incorrectly created assuming the comma in the text box is a separator.
See the attached screenshots.

Thank you!
 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

kmkarakaya/Auto_Review_Generation_in_Turkish

### Screenshot

![image](https://user-images.githubusercontent.com/41159849/179424201-69235b8c-dcb1-4fd8-a9ad-88529d67d5b1.png)
![image](https://user-images.githubusercontent.com/41159849/179424304-7e14215f-6bd2-4f2b-b4d8-fdc376653b3d.png)
![image](https://user-images.githubusercontent.com/41159849/179424350-10e04b25-7fa0-4bba-bf1b-0bc24449bb4c.png)

### Logs

```shell
'Prompt'	'Generated Text'	'flag'	'username'	'timestamp'	
'Tatil iÃ§in rezervasyon yaptÄ±rdÄ±m'	'Tatil iÃ§in rezervasyon yaptÄ±rdÄ±m. Ä°ptal Edilen Tur	 tur ile tatil iÃ§in 3 ay sonra otel tur turu iptali iÃ§in 2 adet rezervasyon yaptÄ±m. 2 gÃ¼n Ã¶ncesinden tatil iptal edildi. Ancak iptal etmek istedik. Fakat Ã¼cret'	''	''	'2022-07-17 20:35:02.542229'
'Bir hafta Ã¶nce aldÄ±ÄŸÄ±m cep telefonu'	'Bir hafta Ã¶nce aldÄ±ÄŸÄ±m cep telefonu sÃ¼rekli meÅŸgul	 arama yapamÄ±yorum. HiÃ§bir cevap alamadÄ±m. MÃ¼ÅŸteri hizmetleri ile ilgili ne bir bilgi alamÄ±yorum. Ã‡aÄŸrÄ± merkezi de ne kadar mail yoluyla dÃ¶nÃ¼ÅŸ yapÄ±lmadÄ±. BÃ¶yle bir ÅŸey gÃ¶rmedim.'	''	''	'2022-07-17 20:36:11.325220'
'Tatil iÃ§in rezervasyon yaptÄ±rdÄ±m'	'Tatil iÃ§in rezervasyon yaptÄ±rdÄ±m. Tur''de Tur''a rezervasyon iÃ§in	 rezervasyon yaptÄ±rdÄ±k. Ä°ptal etmek iÃ§in. Tatil Tur aracÄ±lÄ±ÄŸÄ±yla tatil paketi almÄ±ÅŸtÄ±m. Bilet iptalini talep ediyorum. Para iadesi iÃ§in mÃ¼ÅŸteri hizmetleri ile ilgili'	''	''	'2022-07-17 20:36:49.922712'
'Bir hafta Ã¶nce aldÄ±ÄŸÄ±m cep telefonu'	'Bir hafta Ã¶nce aldÄ±ÄŸÄ±m cep telefonu. Telefonu	 telefon ve bir de arama yaptÄ±ÄŸÄ±mda bir telefon ile bir tÃ¼rlÃ¼ arama yapmÄ±yor. SÃ¼rekli arama ile iletiÅŸime geÃ§tiÄŸimde telefon da bir ÅŸekilde telefon numarasÄ±nÄ± aradÄ±m ve herhangi bir cevap verilmiyor'	''	''	'2022-07-17 20:37:21.197690'
'Bir hafta Ã¶nce aldÄ±ÄŸÄ±m cep telefonu'	'Bir hafta Ã¶nce aldÄ±ÄŸÄ±m cep telefonu telefonu. SipariÅŸ no:00''ye kadar hiÃ§bir ÅŸekilde bilgi vermiyor. Telefon ile ilgili hiÃ§bir ÅŸey bulamadÄ±m. Bir de telefon numarasÄ± ve telefon ile iletiÅŸime geÃ§tim. Ama hala bir'	''	''	'2022-07-17 20:44:30.668472'
```

### System Info

```shell
Spaces Gradio, Colab
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Ah great catch thanks @kmkarakaya, will take a look!

**Comment by abidlabs** [comment]
We've looked into this and realized that it has to do with how we currently sanitize data for entry into CSV files. It looks we will have to rewrite this sanitization logic.
