### ISSUE TITLE
requirements.txt not bundled on pypi

### ISSUE THREAD

**Issue by pbsds** [gradio-app/gradio#1812]
### Describe the bug

The pypi tarball does not include `requirements.txt`. This has become a problem since #1669 was merged.
The fix is likely much like #1706.

... While at it: it doesn't seem like `test/test_files/*` are included either.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```shell
$ curl 'https://files.pythonhosted.org/packages/90/5f/cd78734cb3cc0ce4decafc07fc7d06e55870d75e1ab14bf96cde412dd87c/gradio-3.0.26.tar.gz' | tar ztvf - | grep -E '(requirements.txt|test/test_files)' || echo "not found!"
not found!
```

### Logs

```shell
FileNotFoundError in setup.py regarding requirements.txt
```

### System Info

```shell
gradio version: 3.0.26
nixos: 22.05
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Thank you for filing @pbsds ! I can fix
