### ISSUE TITLE
Support pnpm versions > 6

### ISSUE THREAD

**Issue by chrisemezue** [gradio-app/gradio#1820]
### Describe the bug

this error is thrown
```
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  not found: build:local
 ELIFECYCLE  Command failed with exit code 1.
```
when i run `bash scripts/build_frontend.sh`
-  used `pnpm version 7.5.2` which i installed via `npm install -g pnpm`

According to @NimaBoscarino , the simple solution would be to go into `ui/package.json` and change the build script to say 		`"build": "pnpm --filter @gradio/app build:local --emptyOutDir",`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

.

### Logs

```shell
.
```

### System Info

```shell
.
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment]
Thanks for filing @chrisemezue ! 

Yep this is a known issue. The contributing guide explicitly asks to install pnpm version 6 so this issue feels more like an enhancement request to support newer versions of pnpm. I will rename/relabel as such!

**Comment by abidlabs** [comment]
@pngwn thoughts on this fix?
