### ISSUE TITLE
How to read from the uploaded files

### ISSUE THREAD

**Issue by endrol** [gradio-app/gradio#1824]
### Describe the bug

Thank you for checking this new-starter question. I am using gradio on huggingface and I want to upload multiple images. After checking https://gradio.app/docs/#gallery and https://gradio.app/docs/#file, https://issuemode.com/issues/gradio-app/gradio/87144996#answer-103420732, I decided to use `gr.FIle(file_count='multiple')`. 

But the uploaded file is has the type `<class 'tempfile._TemporaryFileWrapper'>` which I am not familiar with. Do you know how to read it with python and turn it into origin image format(PIL, nparray)? Or is there a different way to upload multiple images? 
Thank you.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

def process_files(files):
    file = ?

if __name__ == "__main__":
    demo = gr.Interface(
        process_files,
        inputs='files',
        outputs="label"
    )
    
    demo.launch()

```

### Screenshot

<img width="747" alt="image" src="https://user-images.githubusercontent.com/37173750/179708471-7285b8fe-eace-477e-bf17-3976d33f4007.png">

### Logs

```shell
>workspace/PaDim_demo/app_gradio.py(13)process_files()->None
-> pdb.set_trace()
(Pdb) files
[<tempfile._TemporaryFileWrapper object at 0x7f1b58b40220>, <tempfile._TemporaryFileWrapper object at 0x7f1b58b40400>, <tempfile._TemporaryFileWrapper object at 0x7f1b58bcb460>, <tempfile._TemporaryFileWrapper object at 0x7f1b58bcb5e0>, <tempfile._TemporaryFileWrapper object at 0x7f1b58bcb490>]
(Pdb) type(files[0])
<class 'tempfile._TemporaryFileWrapper'>
(Pdb)
```

### System Info

```shell
gr__version__ = 3.0.26
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @endrol thanks for trying out Gradio! The way to access the temporary files is to use the `.name` attribute for each of the `tempfile._TemporaryFileWrapper`. This gives you the full path to the files, which then you can pass into `PIL.Image.open()` or use however else you'd like.

Here's an example:
```py
import gradio as gr

def process_files(files):
    file_names = [f.name for f in files]
    return ",\n".join(file_names)

demo = gr.Interface(
    process_files,
    inputs='files',
    outputs="textbox"
)

demo.launch()
```

Produces:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/1778297/179829445-9301c0d1-5fc1-4d1b-a330-b0c20126ce39.png">
