### ISSUE TITLE
Resampling PIL

### ISSUE THREAD

**Issue by siriuslea** [gradio-app/gradio#1825]
### Describe the bug

Occurs on import of gradio, intermittently

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-5-7a3866d7148e>](https://localhost:8080/#) in <module>()
     16 os.system("pip install -q pytesseract")
     17 
---> 18 import gradio as gr
     19 import numpy as np
     20 #from transformers import LayoutLMv3Processor, LayoutLMv3ForTokenClassification

4 frames
[/usr/local/lib/python3.7/dist-packages/gradio/__init__.py](https://localhost:8080/#) in <module>()
      1 import pkgutil
      2 
----> 3 import gradio.components as components
      4 import gradio.inputs as inputs
      5 import gradio.outputs as outputs

[/usr/local/lib/python3.7/dist-packages/gradio/components.py](https://localhost:8080/#) in <module>()
     32 from markdown_it import MarkdownIt
     33 
---> 34 from gradio import media_data, processing_utils
     35 from gradio.blocks import Block
     36 from gradio.documentation import document, set_documentation_group

[/usr/local/lib/python3.7/dist-packages/gradio/processing_utils.py](https://localhost:8080/#) in <module>()
      9 import numpy as np
     10 import requests
---> 11 from PIL import Image, ImageOps
     12 
     13 from gradio import encryptor

[/usr/local/lib/python3.7/dist-packages/PIL/ImageOps.py](https://localhost:8080/#) in <module>()
    238 
    239 
--> 240 def contain(image, size, method=Image.Resampling.BICUBIC):
    241     """
    242     Returns a resized version of the image, set to the maximum width and height

[/usr/local/lib/python3.7/dist-packages/PIL/Image.py](https://localhost:8080/#) in __getattr__(name)
     59         deprecate("Image categories", 10, "is_animated", plural=True)
     60         return categories[name]
---> 61     elif name in ("NEAREST", "NONE"):
     62         deprecate(name, 10, "Resampling.NEAREST or Dither.NONE")
     63         return 0

AttributeError: module 'PIL.Image' has no attribute 'Resampling'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

executing import gradio as gr in google colab

### Logs

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-7a3866d7148e> in <module>()
     16 os.system("pip install -q pytesseract")
     17 
---> 18 import gradio as gr
     19 import numpy as np
     20 #from transformers import LayoutLMv3Processor, LayoutLMv3ForTokenClassification

4 frames
/usr/local/lib/python3.7/dist-packages/gradio/__init__.py in <module>()
      1 import pkgutil
      2 
----> 3 import gradio.components as components
      4 import gradio.inputs as inputs
      5 import gradio.outputs as outputs

/usr/local/lib/python3.7/dist-packages/gradio/components.py in <module>()
     32 from markdown_it import MarkdownIt
     33 
---> 34 from gradio import media_data, processing_utils
     35 from gradio.blocks import Block
     36 from gradio.documentation import document, set_documentation_group

/usr/local/lib/python3.7/dist-packages/gradio/processing_utils.py in <module>()
      9 import numpy as np
     10 import requests
---> 11 from PIL import Image, ImageOps
     12 
     13 from gradio import encryptor

/usr/local/lib/python3.7/dist-packages/PIL/ImageOps.py in <module>()
    238 
    239 
--> 240 def contain(image, size, method=Image.Resampling.BICUBIC):
    241     """
    242     Returns a resized version of the image, set to the maximum width and height

/usr/local/lib/python3.7/dist-packages/PIL/Image.py in __getattr__(name)
     59         deprecate("Image categories", 10, "is_animated", plural=True)
     60         return categories[name]
---> 61     elif name in ("NEAREST", "NONE"):
     62         deprecate(name, 10, "Resampling.NEAREST or Dither.NONE")
     63         return 0

AttributeError: module 'PIL.Image' has no attribute 'Resampling'
```

### System Info

```shell
Google colab
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Going to close the issue for now. @siriuslea if the bug is still present with the latest version of PIL, please feel free to reopen the issue with more details.
