### ISSUE TITLE
Error with Gradio Hosted

### ISSUE THREAD

**Issue by EdwardLevavasseur** [gradio-app/gradio#183]
Hi,

I've just subscribed to Gradio Hosted, and i'm trying to run gradio apps online.

I've tried launching an example app, but I get the following error message:

Step 9/9 : CMD [ "run-gradio.py" ]

 ---> Running in 754f2b07de25

 ---> 3f6c20b710c3

Successfully built 3f6c20b710c3

Successfully tagged edwardlevavasseurhome:latest

Launching image...
Starting container...
Unexpected error: An error occurred (InvalidNetworkInterfaceID.NotFound) when calling the DescribeNetworkInterfaces operation: The networkInterface ID 'eni-004531f11f8dcf27c' does not exist

Could you please tell me what is going wrong?

Thanking you in advance for your help.

Best Regards,

Edward Levavasseur

**Comment by abidlabs** [comment]
Thanks @EdwardLevavasseur we are looking into this.

**Comment by aliabid94** [comment]
The previous issue has been resolved for some time. Looking at the logs from https://gradio.app/g/EdwardLevavasseur/Home it seems that the runfile has not been specified correctly. Reopen if you have any other questions.
