### ISSUE TITLE
Link interpretation to events instead of Interface

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1831]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Currently interpretation is directly linked to Interface, however Blocks has a lot have Interpretation use-cases as well. We might link interpretation to events or event-functions but there is no clear structure in my mind, due to not having a lot familiarity with interpretation. Your input would be most welcome here @abidlabs @freddyaboulton.

We could(if it works)
1. Link interpretation to events or event-functions
2. Explicitly define interpretation as another event or such.

**Comment by FarukOzderim** [comment]
@freddyaboulton would you like to take this over as you have some experience with interpretation?

**Comment by freddyaboulton** [comment]
@FarukOzderim Yes for sure. We can discuss priority next week during the brainstorming session!

**Comment by FarukOzderim** [comment]
Sure 👍, imo it is medium priority, neither urgent nor unimportant. Can take a look when you have the bandwidth.

**Comment by abidlabs** [comment]
It looks like this is actually possible now, thanks @freddyaboulton for writing this Guide: https://gradio.app/custom-interpretations-with-blocks/
