### ISSUE TITLE
Gradio dataframe not taking 'date' datatype

### ISSUE THREAD

**Issue by mbjamil** [gradio-app/gradio#1833]
### Describe the bug

I am trying to output a dataframe which has datetime values, gradio is automatically converting it into 'seconds'. When I check gradio documentation on dataframes, it says to pass the 'date' as a 'datatype'.

But when i do it, i get the following error:

TypeError: __init__() got an unexpected keyword argument 'datatype'

documentation link: https://gradio.app/docs/#dataframe

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I am working on a company project, i cant share all the code. But i am doing something like this:

with demo:
    gr.Markdown(
        """
    # Welcome 
    """
    )
    list=[]
    for i in df['id'].unique():
        list.append(i)
    input = gr.Dropdown(list)
    btn = gr.Button("run")
    output = [gr.outputs.Dataframe(label='title1',datatype='date'),
                             gr.outputs.Dataframe(label='title2'),
                             gr.outputs.Dataframe(label='title3'),
                             gr.outputs.Dataframe(label='title4'),
                             gr.outputs.Dataframe(label='title5'),
                             gr.outputs.Dataframe(label='title6'),
                             gr.outputs.Dataframe(label='title7'),
                             gr.outputs.Dataframe(label='title8'),
                             gr.outputs.Dataframe(label='title9'),
                             gr.outputs.Dataframe(label='title10'),
                             gr.outputs.Dataframe(label='title11'),
                             gr.outputs.Dataframe(label='title12'),
                             gr.outputs.Dataframe(label='title13')]
    btn.click(fn=function, inputs=input, outputs=output)

demo.launch()

### Logs

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-91-c12e18d64ded> in <module>
     68     input = gr.Dropdown(list)
     69     btn = gr.Button("Submit")
---> 70     output = [gr.outputs.Dataframe(),]

TypeError: __init__() got an unexpected keyword argument 'datatype'
```

### System Info

```shell
Gradio version: 3.0.20
Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
@mbjamil glad we solved the original issue! I think the formatting of `How the actual time looks in the dataframe:` may have gotten messed up in the email. Do you mind sharing again?

**Comment by mbjamil** [comment]
i just attached the pictures again, thank you for such a quick response.

**Comment by freddyaboulton** [comment]
Got it, I see now! 

Thanks @mbjamil ! Let me look into it, this could be a bug!

**Comment by freddyaboulton** [comment]
Hi @mbjamil, can confirm this is a bug. I can reproduce with the following code

```python
import gradio as gr
import pandas as pd


def make_dataframe(n_periods):
    return pd.DataFrame({"date_1": pd.date_range("2021-01-01", periods=n_periods),
                         "date_2": pd.date_range("2022-02-15", periods=n_periods)})


gr.Interface(make_dataframe, 
             gr.Number(precision=0), 
             gr.Dataframe(datatype="date")).launch()
```

This is what I see:
![image](https://user-images.githubusercontent.com/41651716/179858168-708f2f4b-a029-4d7a-8aa5-e66c6692e0f7.png)


In the meantime, I recommend you convert your dates to strings in your dataframe if possible while we fix this. 

Doing that fixed my demo above:

![image](https://user-images.githubusercontent.com/41651716/179858333-f8cce854-00bd-416c-ab6e-0e1df3619ba4.png)


For whoever picks this up, this is a backend issue.

**Comment by mbjamil** [comment]
okay great, thank you. For now i took your advice and i see regular time intervals on my interface. Thank you.
