### ISSUE TITLE
Do not use gradio.inputs and gradio.outputs!

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1835]
Hi everyone!

The `gradio.inputs` and `gradio.outputs` modules have been deprecated. 

We don't recommend you use them on new apps although they are still in the library as of version 3.1.

From now on, you should use the components defined in the the gradio module. These are the components listed in the [docs](https://gradio.app/docs/#components).

The following table shows how transition to the recommended API, you just have to remove `.outputs.` or `.inputs.` from your code!

| Deprecated API  | Recommended API |
| ------------- | ------------- |
| gr.inputs.Image  | gr.Image  |
| gr.outputs.Label  | gr.Label  |

Thank you for using gradio and enjoy the fewer character you have to type now 😎

**Comment by abidlabs** [comment]
How long do we want to keep this issue open / pinned? I think we can actually close it (will not lose its pinned status) now

**Comment by Gangadharbhuvan** [comment]
what if my question takes a text input and the resulting out can be  wither a dataframe, image or an text, how to handle this.
