### ISSUE TITLE
Implement Variants for UI Components

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1844]
We should provide variants for common UI components to enable users to create more customized user interfaces. Example variants for the text box could be "warning", "error". 

> I think what would be preferable is a series of 'variants' for the textbox (which come with  a set of background + text colors) and then when we do theming, allow these variants to be 'themed' along with everything else. This way we can provide the ability to create 'stand out' boxes (for things like asides, warnings, errors, etc) but still ensure that they work with our existing design.
> 
> Where possible, I'd like us to control things like colors, spacing, etc via theming so that users don't need to put on a designer hat in order to create the UIs the want (other than for layouts) but can drop down and make those modification where necessary with themes.

_Originally posted by @pngwn in https://github.com/gradio-app/gradio/issues/1698#issuecomment-1175979199_

**Comment by abidlabs** [comment]
Is this still a relevant issue, given the new theming work? cc @pngwn
