### ISSUE TITLE
Help with Gradio filters:

### ISSUE THREAD

**Issue by mbjamil** [gradio-app/gradio#1846]
Hi team,

I want some help to 'filter' my dataframes data inside the gradio interface. Basically i want the user to be able to filter out data. I have a function where i want to show the user the option to filter on id1 and then get relevant id2 and other metadata frames.

How can i achieve this? what mistake am i making in my code?

Code below:
```py
def inv(id1,id2):
    action_id1 = 1_df[1_df['id1']==id1].iloc[:,2:]
    action_main = main_df2[main_df2['id2'] ==id2].iloc[:,2:]
    action_1= 1_df[1_df['id2'] ==id2].iloc[:,2:]
    action_2= 2_df[2_df['id2'] ==id2].iloc[:,2:]
    action_3= 3_df[3_df['id2'] ==id2].iloc[:,2:]
    action_4= 4_df[4_df['id2'] ==id2].iloc[:,2:]
    action_5= 5_df[5_df['id2'] ==id2].iloc[:,2:]
    action_6= 6_df[6_df['id2'] ==id2].iloc[:,2:]
    action_7= 7_df[7_df['id2'] ==id2].iloc[:,2:]
    action_8= 8_df[8_df['id2'] ==id2].iloc[:,2:]
    action_9= 9_df[9_df['id2'] ==id2].iloc[:,2:]
    action_10= 10_df[10_df['id2'] ==id2].iloc[:,2:]
    action_11= 11_df[11_df['id2'] ==id2].iloc[:,2:]
    action_12= 12_df[12_df['id2'] ==id2].iloc[:,2:]
    return (action_main,action_1, action_2, action_3, action_4, action_5, action_6,
           action_7, action_8, action_9, action_10, action_11, action_12)


demo = gr.Blocks(css="""
                    body {
                      background-color: #f9b734 !important
                    }""")



with demo:
    gr.Markdown(
        """
    # Welcome To Interface
    Please select id1 and then select id2
    """
    )
    id1_id=[]
    list_id=[]
    for i in 1_df['id1'].unique():
        id1_id.append(i)
    input1 = gr.Dropdown(id1_id)
    for j in main_df2['id2'].unique():
        list_id.append(j)
    input2 = gr.Dropdown(list_id)
    btn = gr.Button("Submit")
    output = [gr.Dataframe(),
                  gr.Dataframe(),
                  gr.Dataframe(),
                  gr.Dataframe(),
                  gr.Dataframe(),
                  gr.Dataframe(),
                  gr.Dataframe(),
                  gr.Dataframe(),
                  gr.Dataframe(),
                  gr.Dataframe(),
                  gr.Dataframe(),
                  gr.Dataframe(),
                  gr.Dataframe()]
    btn.click(fn=fn, inputs=[input1,input2], outputs=output)
    
demo.launch()
```
the problem with this approach is i am still seeing data for all the id2. I just want to show id2 for the relevant id1 which i select from a drop down. This is not an issue. I just need help.

**Comment by aliabid94** [comment]
Hey @mbjamil, glad you reached out. Your code is difficult to understand, and has quite a few bugs outside the gradio aspect of the code. Can you format the codeblock with three backticks \`\`\` so indentation is preserved?

Meanwhile, here's is a simple example of a demo involving filtering Dataframes:

```
import gradio as gr


def filter_records(records, gender):
    return records[records["gender"] == gender]


demo = gr.Interface(
    filter_records,
    [
        gr.Dataframe(
            headers=["name", "age", "gender"],
            datatype=["str", "number", "str"],
            row_count=5,
            col_count=(3, "fixed")
        ),
        gr.Dropdown(["M", "F", "O"]),
    ],
    "dataframe",
    description="Enter gender as 'M', 'F', or 'O' for other.",
)
demo.launch()
```

The user enters a dataframe, selects the gender to filter by, and receives an output dataframe filtered by the selected gender.

**Comment by mbjamil** [comment]
Hi Ali,

Thanks for getting back, I actually dumbed the code down for not making it obvious what i want to do. But let me write another snippet of code detailed with comments so that you guys can help me out. I really appreciate the help. Would get back

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mbjamil** [comment]
hey Ali,

I think the code which i copied here messed up the formatting, but i am going to copy the code and i am going to write very detailed comments:

so i have you can say 2 dataframes:

df1 (has columns id)
df2 (has column only one column id which is a concatenated field of 'id_name_age')

''' Gradio code below, the main purpose of the below code is to show a dataframe output from df2 where there is a match between df2['id'] and df1['id']. Basically the user should only see those ID's from df2 where there is an exact match of data content from df1.id with df2.id. ""

# writing a function fn which basicaly takes in input from id1 and id2 which the user will select from the interface.
def fn(id1,id2):
    df1[df1['id']==id1]
    action_main = df2[main_df2['id'] ==id2].iloc[:,2:]
    return (action_main)

demo = gr.Blocks(css="""
                    body {
                      background-color: #f9b739 !important
                    }""")

with demo:
    gr.Markdown(
        """
    # Welcome To Interface
    Please select id1 and then select id2
    """
    )
    list1_id=[]
    list2_id=[]
    # the below for loop runs to get the unique 'id's from dataframe1 and save them in list1_id.
    for i in df1['id'].unique():
        list1.append(i)
    input1 = gr.Dropdown(list1_id)
    # the below for loops runs to get the unique 'id's from dataframe2 and save them in list2_id.
    for j in df2['id'].unique():
        list2_id.append(j)
    input2 = gr.Dropdown(list2_id)
    # this btn is the field which the user will hit to get the relevant data.
    btn = gr.Button("Submit")

    # this is the output which is basically data from dataframe2 from function fn
    output = [gr.Dataframe()]
    btn.click(fn=fn, inputs=[input1,input2], outputs=output)
    
demo.launch()

Thanks again for helping me

**Comment by mbjamil** [comment]
hey Ali good news i got the underlying dataframe out and was able to filter the dataset. So the original question i think is answer. Now the question which i would really appreciate the help woul be in answering this:

for the 2 inputs, i actually want the input2 to get filtered from input1. I changed the below:

```
    list1_id=[]
    list2_id=[]
    # the below for loop runs to get the unique 'id's from dataframe1 and save them in list1_id.
    for i in df1['id'].unique():
        list1.append(i)
    input1 = gr.Dropdown(list1_id)
    # the below for loops runs to get the unique 'id's from dataframe2 and save them in list2_id.
    for j in df2['id'].unique():
        list2_id.append(j)
    input2 = gr.Dropdown(list2_id)
```

to 

```
#creating a dict which stores the lists below:
  dict = {"list1_id":[],"list2_id":[]}
  for i in df1['id'].unique():
        dict['list1_id'].append(i)
        for j in df2['id'].unique():
            if i in j:
                dict['list2_id'].append(j)
    input1 = gr.Dropdown(dict['list1_id'])
    input2 = gr.Dropdown(dict['list2_id'])
```

So these two inputs, any idea how can i see the results based on input1 entry and then input2 gets populated automatically. Apologies if this does not make any sense. Like for example. 

If df1 = [1,2,3]
and df2 = [1_bilal_15, 2_aisha_16, 3_zain_17].

on the backend output of the dataframe 'data' is being filtered. But the dropdown for input2 is not being limited to only one option based on the selection from input1.

I am very grateful for the help.

**Comment by freddyaboulton** [comment]
@mbjamil Take a look at the `blocks_update` [demo](https://github.com/gradio-app/gradio/blob/main/demo/blocks_update/run.py)

In particular, this code snippet

```python
    def filter_species(species):
        return gr.Dropdown.update(
            choices=species_map[species], value=species_map[species][1]
        ), gr.update(visible=True)

    species.change(filter_species, species, [animal, details_col])
```

When the species changes, the choice of animals listed in the drop down changes as well.
