### ISSUE TITLE
Allow to randomize the input in a slider component

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1849]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
For demos of generative models, the input seed/slider can have a huge effect. Something that would be very useful in the slider is if we could randomize the initial value of the slider for each user. E.g. by setting `value="random"` then every  time someone opens the app they get a different value in the slider. 

**Additional context**  
Internal discussion: https://huggingface.slack.com/archives/C03HBN1C8CW/p1658396924819859

**Comment by freddyaboulton** [comment]
@osanseviero This is already supported!

```python
import gradio as gr
import random

with gr.Blocks() as demo:
    slider = gr.Slider(0, 100)
    demo.load(lambda: gr.update(value=random.randrange(0, 100)), None, slider)

demo.launch()
```
![random_slider](https://user-images.githubusercontent.com/41651716/180235384-fbf55412-011a-45e1-8877-c17210d358b9.gif)

**Comment by osanseviero** [comment]
Very nice!

**Comment by osanseviero** [comment]
I think it could be useful to support this directly in the component as it could also be useful for Interfaces

**Comment by freddyaboulton** [comment]
@osanseviero You can also technically do this with interfaces! It's a bit non-standard though but shows how interfaces are just blocks:

```python
import gradio as gr
import random

slider = gr.Slider(0, 100)
interface = gr.Interface(lambda x: x, inputs=slider, outputs=slider)

def seed():
    return gr.update(value=random.randrange(0, 100))

with interface:
    interface.set_event_trigger("load", seed, None, slider, no_target=True)
    interface.launch()
```

Thoughts on exposing this through a prettier api (something like `interface.on_launch(function, inputs, outputs)`). 

I think that's more powerful and doesn't involve adding logic to the component for this specific use case.

**Comment by abidlabs** [comment]
> @osanseviero You can also technically do this with interfaces! It's a bit non-standard though but shows how interfaces are just blocks:

Wow I learned something today 😄

**Comment by abidlabs** [comment]
> I think that's more powerful and doesn't involve adding logic to the component for this specific use case.

The use case of seeds for GANs/image generation models is common enough to warrant a nice shorthand in my opinion
