### ISSUE TITLE
How to install Gradio 2.0 ?

### ISSUE THREAD

**Issue by LipsaBiswas** [gradio-app/gradio#185]
pip install gives me Gradio 1.7.7
How do i get Gradio 2.0?

**Comment by abidlabs** [comment]
We will be releasing Gradio 2.0 soon!

**Comment by LipsaBiswas** [comment]
How can I be notified?

**Comment by abidlabs** [comment]
We are planning to launching 2.0 on Monday, thanks :)

**Comment by LipsaBiswas** [comment]
Superb 👏👏
