### ISSUE TITLE
Authorization issues while deployment

### ISSUE THREAD

**Issue by LipsaBiswas** [gradio-app/gradio#186]
Hey ,
Why I am getting the following issue while deployment
"errorDetail":{"message":"denied: Your authorization token has expired. Reauthenticate and try again."},"error":"denied: Your authorization token has expired. Reauthenticate and try again."}

**Comment by LipsaBiswas** [comment]
@abidlabs , any input will be appreciated.
Its bit urgent

**Comment by aliabid94** [comment]
Taking a look

**Comment by aliabid94** [comment]
Sorry about that, yes there was an auth issue on our end. Fixed now, can you let us know if it works for you?

**Comment by LipsaBiswas** [comment]
No , @aliabid94 
![image](https://user-images.githubusercontent.com/22794542/119529279-94460a80-bd9f-11eb-8348-615dfac0c4ee.png)

**Comment by aliabid94** [comment]
Taking a look

**Comment by aliabid94** [comment]
Hey @LipsaBiswas I forked your repo at https://github.com/aliabid94/GradioSummaryComparer/ to fix one of the issues, your requirements file had a syntax error. However, when I tried launching it, the problem is that we provide 8GB of RAM per hosted model - your code loads too many large models into memory that it crashes. Can you try reducing the memory footprint of your code?

**Comment by LipsaBiswas** [comment]
@aliabid94 ,
Now for test purposes, I created an app with less memory footprint.
But getting authorization issue
![image](https://user-images.githubusercontent.com/22794542/119779064-dda07200-bee5-11eb-9989-27b5b8d60e0c.png)

**Comment by abidlabs** [comment]
Sorry, we're migrating to a new infrastructure so this might be the reason. We're looking into it!

**Comment by LipsaBiswas** [comment]
I understand!
Please keep me posted.

**Comment by LipsaBiswas** [comment]
@abidlabs ,
If I select one model at a time (radio button), will it be ok? Or there will be memory issues if a user selects one by one all options and clicks submit?
![image](https://user-images.githubusercontent.com/22794542/119798885-2b72a580-bef9-11eb-9997-f327cb93711e.png)

**Comment by AK391** [comment]
also get this message

**Comment by LipsaBiswas** [comment]
@abidlabs , any updates plz ?

**Comment by aliabid94** [comment]
Sorry forgot to respond here, yes the auth issue has been fixed. https://gradio.app/g/LipsaBiswas/GradioSummaryComparer.
As for memory, we allocate 8GB of RAM to each interface container - if you go over this limit, the container will crash and restart after a few minutes so just be mindful of that :)
Let us know if you have any other issues!
