### ISSUE TITLE
Issue with Example helper component when passing str path to directory of examples

### ISSUE THREAD

**Issue by shivalikasingh95** [gradio-app/gradio#1875]
Hi,

When I'm trying to pass a string path to the directory of samples to the "Example" helper component, I'm getting a file not found error as shown in the screenshot labelled "Error 1 colab screenshot" below.

I tried fixing the above error by fixing the path being passed to 'processing_utils.encode_file_to_base64()'  in line 1637 of gradio/components.py
However, after fixing that I was getting another error as shown in screenshot labelled "Error 2'. 

I was able to fix all the errors and get the desired output by commenting out lines 92-103 of gradio/examples.py as highlighted in screenshot labelled "Problem Fix".
Since, I'm new to gradio I'm not sure if this is the relevant fix. 

Please let me know if you guys are able to reproduce this issue and if the fix suggested on top is right. I'd be happy to submit a PR for the same. If there's an alternative fix that can be done for this issue, I'd be happy to take that up as well.

**Error 1 colab screenshot**:

![Screenshot from 2022-07-28 00-59-02](https://user-images.githubusercontent.com/73357305/181356237-ac72940d-918c-417e-991c-03f749c4aa72.png)

**Error 1 Stack trace:**
![Screenshot from 2022-07-25 07-53-47](https://user-images.githubusercontent.com/73357305/180681083-924c528f-0e45-4322-ac1f-dc766ae35356.png)

**Error 2:**
![Screenshot from 2022-07-25 08-37-31](https://user-images.githubusercontent.com/73357305/180691342-085c9b6c-c911-41a9-ad05-87884b381c35.png)

**Problem Fix:** Commenting lines 92-103 of gradio/examples.py 
![Screenshot from 2022-07-25 08-31-44](https://user-images.githubusercontent.com/73357305/180692228-f1de0d9d-080d-477d-ab14-7bd19ed48ad2.png)

**The following code snippet should help in reproducing Error 1:**

` import gradio as gr

  demo = gr.Blocks()
  input_image = gr.Image(type='filepath',label="Input Image", show_label=True)
  output_label = gr.Label(label="Model Output", show_label=True)
  
  with demo:
         gr.Examples("examples", [input_image], output_label) #where "examples" is path of directory containing sample images.
  
  demo.launch()`

**System Info:**
gradio version: 3.1.1
OS: Ubuntu 22.04 LTS
Browser: Chrome

**Comment by shivalikasingh95** [comment]
Hi any updates on this issue?

**Comment by abidlabs** [comment]
@shivalikasingh95 sorry for the delay, looking into this now

**Comment by shivalikasingh95** [comment]
Thanks @abidlabs for the update and adding a PR to fix this!
