### ISSUE TITLE
ANSI escape sequence isn't working on text output

### ISSUE THREAD

**Issue by sunnymoon-sultan** [gradio-app/gradio#1876]
I'm trying to build a image classifier and I wanted to have the results as colored plain text. But when I'm trying to output the colored text using the ANSI escape sequence. It's not working.It's giving me the output correctly but with the ANSI sequence itself.
![image](https://user-images.githubusercontent.com/75605506/180729828-5745a989-ae66-4482-8b64-1c8c80843881.png)

**Comment by sunnymoon-sultan** [comment]
> ANSI escape sequences don't work in html text inputs. Can you explain exactly what it is you are trying to achieve?

I'm trying to get the output text in colored format. Is there any way to do that in gradio?

**Comment by pngwn** [comment]
Do you have more information about the gradio app you are trying to build? Would one of our other components not work for this usecase such as [`HighlightedText`](https://gradio.app/docs/#highlightedtext-header) or [`Label`](https://gradio.app/docs/#label-header)?

**Comment by sunnymoon-sultan** [comment]
> Do you have more information about the gradio app you are trying to build? Would one of our other components not work for this usecase such as [`HighlightedText`](https://gradio.app/docs/#highlightedtext-header) or [`Label`](https://gradio.app/docs/#label-header)?

Yeah [`HighlightedText`](https://gradio.app/docs/#highlightedtext-header) worked for me. Thank you!

**Comment by sunnymoon-sultan** [comment]
> Do you have more information about the gradio app you are trying to build? Would one of our other components not work for this usecase such as [`HighlightedText`](https://gradio.app/docs/#highlightedtext-header) or [`Label`](https://gradio.app/docs/#label-header)?

OK. What I'm trying to achieve is that I want a specific word to be highlighted in my text output. Like in this output I want "DID YOU KNOW" to be colored in green.  How can I do that with   [`HighlightedText`](https://gradio.app/docs/#highlightedtext-header) ? 
![image](https://user-images.githubusercontent.com/75605506/181195150-d05e5c57-d0b4-4551-bc98-1edbc336935a.png)

**Comment by abidlabs** [comment]
Hi @sunnymoon-sultan, in terms of the larger point of supporting ANSI escape sequences, I feel that this is out of scope for the `Textbox` component. 

However, specifically for the question that you asked, it is possible through the use of the `color_map` parameter in `HighlightedText.style()` method.

Here's a quick example:

```py
import gradio as gr

def test(x):
    return [("Seems like it is", None), ("Bread", "category"), (". Did you know?", None)]

gr.Interface(test, "text", gr.HighlightedText().style(color_map={"category": "green"})).launch()
```

<img width="569" alt="image" src="https://user-images.githubusercontent.com/1778297/185482060-c938b5ff-72ea-412b-aae0-8e61f0a0cb5b.png">
