### ISSUE TITLE
Tables in gr.Markdown

### ISSUE THREAD

**Issue by zouharvi** [gradio-app/gradio#1886]
### Describe the bug

`gr.Markdown` does not seem to support tables, i.e. they are not rendered.

If it's intentional that markdown tables are not supported (in favour of Dataframes) then that's ok, but I did not find any usage note about this in the documentation.

The table in the example:

```
|a|b|c|
|-|-|-|
|x|y|z|
```

Should be rendered as:

|a|b|c|
|-|-|-|
|x|y|z|

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python3
import gradio as gr

interface = gr.Interface(
    fn=lambda x: x, inputs=None,
    outputs=gr.Markdown("""
        |a|b|c|
        |-|-|-|
        |x|y|z|
    """)
)
interface.launch()
```

### Screenshot

![image](https://user-images.githubusercontent.com/7661193/180955052-eeb3c1e5-6293-45ee-81a5-de2f366db2b7.png)

### Logs

```shell
No logs available.
```

### System Info

```shell
gradio 3.1.1, Fedora 36, Firefox 102.0
```

### Severity

annoying

**Comment by pngwn** [comment]
Tables are not supported by default in Markdown but we can probably support Github Flavoured markdown pretty easily.

**Comment by abidlabs** [comment]
Yup it looks like it tables can be enabled fairly easily in `MarkdownIt`, if someone wants to look into this: https://markdown-it-py.readthedocs.io/en/latest/plugins.html
