### ISSUE TITLE
Image example cannot be displayed properly

### ISSUE THREAD

**Issue by felixgao** [gradio-app/gradio#1895]
### Describe the bug

In my example I have two images that are showing as a broken image in the examples section of the app. 

When I click on the example images it is showing up correctly in the main input window

after inspecting the image in developer tools I don't think the path generated is correct. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
path = 'resources/docs/'
examples = [[f"{path}/business-license-4.jpeg", "Business License"], [f"{path}/business-license-5.jpeg", "Business License"]]


title = "🧱 Document"
description = f""" ℹ️ \n Test. """
article = Images"

css = ".output-image, .input-image {height: 40rem !important; width: 100% !important;}"
# css = "@media screen and (max-width: 600px) { .output_image, .input_image {height:20rem !important; width: 100% !important;} }"
# css = ".output_image, .input_image {height: 600px !important}"

css = ".image-preview {height: auto !important;}"

iface = gr.Interface(
    fn=process_image,
    inputs=gr.inputs.Image(type="pil"),
    outputs=gr.outputs.Image(type="pil", label="annotated image"),
    title=title,
    description=description,
    article=article,
    examples=examples,
    css=css,
    enable_queue=True,
)
iface.launch(debug=True)
```

### Screenshot

Right after launching 
![image](https://user-images.githubusercontent.com/1153820/181110454-42bb4dcc-20ae-469f-83d7-d9722942c43e.png)

Right after clicking on one of the example images
![image](https://user-images.githubusercontent.com/1153820/181110536-a06c72a3-dd9d-456f-bd75-28533d3767ae.png)

Inspecting the html of the example
![image](https://user-images.githubusercontent.com/1153820/181110834-2500acac-3294-4b63-8651-010a849056b3.png)

### Logs

```shell
gradio layoutparser/app.py

Launching in *reload mode* on: http://127.0.0.1:7860 (Press CTRL+C to quit)

Watching: '/Users/ggao/projects/layoutparser/.venv/lib/python3.9/site-packages/gradio', '/Users/ggao/projects/layoutparser/layoutparser'

Reusing dataset funsd (/Users/ggao/.cache/huggingface/datasets/nielsr___funsd/funsd/1.0.0/8b0472b536a2dcb975d59a4fb9d6fea4e6a1abe260b7fed6f75301e168cbe595)
/Users/ggao/projects/layoutparser/.venv/lib/python3.9/site-packages/gradio/deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
/Users/ggao/projects/layoutparser/.venv/lib/python3.9/site-packages/gradio/deprecation.py:40: UserWarning: `enable_queue` is deprecated in `Interface()`, please use it within `launch()` instead.
  warnings.warn(value)
Running on local URL:  http://127.0.0.1:7861/

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
gradio 3.1.1
osx 12.3.1
browsers: 
Brave Version 1.39.122 Chromium: 102.0.5005.115 (Official Build) (arm64)
Safari Version 15.4 (17613.1.17.1.13)
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment]
Hi @felixgao ! Thanks for filing.

Does the same problem happen on Chrome or Safari? Having trouble reproducing the error on my end.

**Comment by abidlabs** [comment]
Going to close the issue for now because of lack of response. @felixgao if the bug is still present, feel free to reopen the issue with more details.
