### ISSUE TITLE
Error when dealing with multiple requests, .launch(share=True), and gr.File

### ISSUE THREAD

**Issue by Warvito** [gradio-app/gradio#1902]
### Describe the bug

I am having problems serving an application when using share=True.
My application contains three gr.Video and one gr.File, and when I try it with several sessions at the same time (testing how it will behave with several people using it at the same time), if in one of them I click to download the file from the gr.File at the same time that my app uploads the videos for another request to the gr.Video, it will make the second request fails to display the videos (showing an error message in the gr.Video even without showing any error message in the terminal that I am running the app).
After this happens, all new requests from different sessions always fail to display the videos, showing the error message in the UI without raising any error in the terminal that I am running the app.
When running with share=False, I do not have this issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Logs

```shell
No message displayed
```

### System Info

```shell
gradio==3.1.1, Ubuntu 18.04.6 LTS, Google Chrome Version 96.0.4664.110 (Official Build) (64-bit)
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks for reporting this issue @Warvito, we'll take a look into it.

**Comment by abidlabs** [comment]
Taking another look at this, we'll need more information in order to investigate this. Can you please provide a code example that we can use to reproduce this behavior?

**Comment by abidlabs** [comment]
Going to close this until we have some code to reproduce. Please feel free to reopen with more info @Warvito. Thanks!
