### ISSUE TITLE
Add `.style()` for each component to the docs

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#1904]
In our section on styling, we say "Take a look at the [Docs](https://gradio.app/docs) to see all the styling options for each Component."

<img width="678" alt="image" src="https://user-images.githubusercontent.com/1778297/181617826-cf080125-63bf-47ca-ab7c-665ca50b15f2.png">

However, I don't see the documentation for `.style()` for each component just yet. Let's go ahead and add it in.

**Comment by HuangChiEn** [comment]
WoW ~ That's what i looking for !! 🚀
Last week I still followed the example and doc to write the CSS & pass it to each component by id.

For now, seems we have new choice ~
Is this appears in gradio>=1.3.0 version also ?
