### ISSUE TITLE
Request for streaming microphone input component

### ISSUE THREAD

**Issue by m-ali-awan** [gradio-app/gradio#191]
Once we record by microphone, I am not able to listen anything.
I am trying to have a real-time prediction with fastai trained model.

This is my code:
`
labels=learn.dls.vocab
def predict_audio(audio):
    at=AudioTensor.create(audio)
    pred,pred_idx,probs = learn.predict(at)
    return {labels[i]: float(probs[i]) for i in range(len(labels))}
`
`   
gr_interface = gr.Interface(fn=[
                                predict_audio], inputs=gr.inputs.Audio(source="microphone"),
                            outputs=gr.outputs.Label(num_top_classes=2),
                            title="Audio Classification:",
                            description='{}'.format(labels),
                            interpretation="default")
gr_interface.launch(debug=True)
`

Thanks for any help.

**Comment by aliabid94** [comment]
can you link or provide the code for the entire file? also which platform & browser?

**Comment by m-ali-awan** [comment]
Thanks, for replying.
I am using Colab pro, and fastai.
Please help me out to handle this:

`AssertionError: Expected an input of type in 
  - <class 'pandas.core.series.Series'>
  - <class 'str'>
  - <class 'fastaudio.core.signal.AudioTensor'>
 but got <class 'tempfile._TemporaryFileWrapper'>`

**Comment by m-ali-awan** [comment]
As if I use "numpy" mode, it returns weird shape (samples,2), which is not like librosa.load, nor torch.load.
So, how to properly have the input.

Thanks.

**Comment by m-ali-awan** [comment]
This is the colab notebook  link:

https://colab.research.google.com/drive/13fYBSQmuJpkwWVpRBbcav1pcs3gu_Dl3?usp=sharing

**Comment by m-ali-awan** [comment]
You can see the Gradio part:

Thanks a lot..

**Comment by m-ali-awan** [comment]
Also when using "numpy" mode:
numpy array may be as it is not normalized or due to some other reason;
It gives weird error:
  File "/usr/local/lib/python3.7/dist-packages/fastaudio/augment/signal.py", line 54, in _tfm_pad_signal
    c, x = sig.shape
ValueError: too many values to unpack (expected 2)

Kindly, help me out with this Audio Part.
Thanks a lot...

**Comment by m-ali-awan** [comment]
I have got the solution:

Actually for file model:
we have to grab the path by input_file.name,
Then specifically for fastai model do path=Path(str( input_file.name)), 
And then pass it to the learner.

**Comment by m-ali-awan** [comment]
But now, as for image in live feed we can have live inference, 
Can we not have live inference while recording. As of now, in live mode, we have to submit the recording and then inference starts, and then we have to record again.

Thanks for any help.

**Comment by aliabid94** [comment]
Taking a look

**Comment by m-ali-awan** [comment]
Thanks alot, will love to have this feature, so eagerly waiting.

Thanks again...

**Comment by aliabid94** [comment]
I see the error. Colab notebook is blocking permissions for the microphone - will try to see if there's some workaround. Meanwhile, you can click the External URL shown above the interface to load the Gradio interface in a new tab and the microphone should work.

**Comment by m-ali-awan** [comment]
Thanks alot, @aliabid94 ,
But microphone is working, but the problem is not in continuous manner, like a webcam feed.
Is there any way to do that?
Thanks a lot...

**Comment by aliabid94** [comment]
Sorry for the late response. Streaming audio is in the pipeline, will update you once that's available. Thanks!

**Comment by abidlabs** [comment]
This is closed as of #800! Thanks for the patience

**Comment by Jackiexiao** [comment]
@abidlabs hi, is it possible to use stream audio component for realtime text-to-speech or realtime voice conversion?

**Comment by abidlabs** [comment]
Hmm, I don't think that is currently possible. Feel free to open an issue with more details on what you'd like to see and we can work on it!
