### ISSUE TITLE
Passing Table as input

### ISSUE THREAD

**Issue by PhaneendraGunda** [gradio-app/gradio#192]
Hi,

I wanted to build a demo, which takes table as input and generate text summary as output. Any plans to add HTML as input to the gradio to represent the table ? Any suggestions are welcome.

**Comment by aliabid94** [comment]
Seems like the Dataframe input is what you're looking for. You can customize the headers - take a look at https://github.com/gradio-app/gradio/blob/master/demo/filter_records.py for an example.

**Comment by PhaneendraGunda** [comment]
Yes we can use Dataframe, but values are not displaying clearly when the DF has many headers. Any suggestions to make it looks cleanly ?

**Comment by PhaneendraGunda** [comment]
Can we pass default values to the Data Frame ? I couldn't find any option to pass the default data.

**Comment by abidlabs** [comment]
What do you mean by default values? Do you mean `examples`? You should be able to do that

**Comment by aliabid94** [comment]
You can pass default values using default= keyword argument for the Dataframe input. Pass any 2D array and it will be the default value of the dataframe.
