### ISSUE TITLE
Model3D component loads forever when used as input and cache_examples=False

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1924]
### Describe the bug

When using `Model3D` as input and `cache_examples=False`, the component loads forever after running the predict function.

@dawoodkhan82 Any idea what's happening?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import time
import gradio as gr
import os


def load_mesh(mesh_file_name):
    return mesh_file_name


demo = gr.Interface(
    fn=load_mesh,
    inputs=gr.Model3D(),
    outputs=gr.Model3D(clear_color=[0.0, 0.0, 0.0, 0.0],  label="3D Model"),
    examples=[
        ["files/Bunny.obj"],
        ["files/Duck.glb"],
        ["files/Fox.gltf"],
        ["files/face.obj"],
    ],
    cache_examples=False,
)

demo.launch()
```

### cache_examples=False
![model_3d_loading_screen](https://user-images.githubusercontent.com/41651716/182251429-05978017-2d6c-4486-b0dd-bd2734873e33.gif)

This isn't the case when `cache_examples=True`
### cache_examples=True
![image](https://user-images.githubusercontent.com/41651716/182251520-079f88eb-4a4c-4666-9f8c-beeb8793794c.png)

### Logs

```shell
-
```

### System Info

```shell
3.1.1
```

### Severity

annoying

**Comment by dawoodkhan82** [comment]
@freddyaboulton will take a look
