### ISSUE TITLE
Interface of the Web App is not clear as the input options are not properly aligned

### ISSUE THREAD

**Issue by nikhil-shah505** [gradio-app/gradio#193]
![gradio problem](https://user-images.githubusercontent.com/72156618/119557054-5526b200-bdbd-11eb-9793-e7918ff0ba0e.jpg)

**Comment by aliabid94** [comment]
Yikes, looks like a CSS bug on our part. Will update soon!

**Comment by aliabid94** [comment]
Fixed in 2.0.1. Thanks for pointing this out @nikhil-shah505 !

**Comment by nikhil-shah505** [comment]
Thanks, @aliabid94 for fixing this and building this amazing feature!!
