### ISSUE TITLE
Add testing to make sure share=True, iframe, and Spaces don't break on release

### ISSUE THREAD

**Issue by aliabid94** [gradio-app/gradio#1934]

**Comment by abidlabs** [comment]
What we need is a GitHub action that runs *after* the pypi package is deployed and programmatically tests:
* That `share=True` is working with the latest release
* That demos appears properly in iframes with the latest release

**Comment by freddyaboulton** [comment]
I think we should do a pre-release prior to the official release to make sure we don't publish a broken version.

**Comment by abidlabs** [comment]
Ah yeah that’s much better!
