### ISSUE TITLE
TabbedInterface will ignore all style setup of block api

### ISSUE THREAD

**Issue by HuangChiEn** [gradio-app/gradio#1941]
#### python version == 3.8.8

There are 2 way to setup the style of each component in the block API. 
1. Feed the CSS string in the block API and setup `elem_id` of component according to CSS template.
> ``` 
> # my code snippet
> css_def = '''
> #im_id {height: 30rem !important; width: 40% !important;}
> #txt_id {width: 40% !important;}
> #sld_id {width: 20% !important;}
> '''
> blk_cntr = gr.Blocks(css=css_def) 

2. call style method in the corresponding component
> `image_input = gr.Image(label="Uploaded image").style(height='24')`

However, all of aforementioned settings will be fail, while i further warp the block API into the TabbedInterface.

```
    def layout_func(blk_cntr):
        with blk_cntr:
            ... all of component i want to setup
            # e.g. Both not work while apply TabbedInterface...QQ
            # method 1.
            # image_input = gr.Image(label="Uploaded image", elem_id='im_id')
            # method 2.
            # image_input = gr.Image(label="Uploaded image").style(height='24')
            
    
    css_def = '''
    #im_id {height: 30rem !important; width: 40% !important;}
    #txt_id {width: 40% !important;}
    #sld_id {width: 20% !important;}
    blk_cntr = gr.Blocks(css=css_def) 
    layout_func(blk_cntr)
    ....
    # for convenience, i just use the same block API (blk_cntr) 
    demo = gr.TabbedInterface([blk_cntr, blk_cntr], ["Text-to-speech", "Speech-to-text"])
    demo.launch(share=True, enable_queue=True)
```

Any suggestion will be appreciated !!

**Comment by abidlabs** [comment]
Hi @HuangChiEn I'm looking into this. Would you be able to provide a complete code snippet? Will make it easier to reproduce

**Comment by abidlabs** [comment]
Hi @HuangChiEn, this should now be fixed due to #1951. Please take a look at https://github.com/gradio-app/gradio/pull/1951 for more information, but the summary is that you will have to pass in a `css` parameter to `TabbedInterface` with your desired css, like this:

```py
import gradio as gr

def test(text1):
    return [(text1, "good"), ("\n", None), (text1, "good")]

demo = gr.Interface(
    test,
    "text",
    gr.HighlightedText(elem_id="htext"),
)

def test(text1):
    return [(text1, "good"), ("\n", None), (text1, "good")]

demo2 = gr.Interface(
    test,
    "text",
    gr.HighlightedText(elem_id="htext2"),
)

gr.TabbedInterface([demo, demo2], css="#htext span {white-space: pre} #htext2 span {white-space: pre}").launch()
```

**Comment by HuangChiEn** [comment]
> Hi @HuangChiEn, this should now be fixed due to #1951. Please take a look at #1951 for more information, but the summary is that you will have to pass in a `css` parameter to `TabbedInterface` with your desired css, like this:
> 
> ```python
> import gradio as gr
> 
> def test(text1):
>     return [(text1, "good"), ("\n", None), (text1, "good")]
> 
> demo = gr.Interface(
>     test,
>     "text",
>     gr.HighlightedText(elem_id="htext"),
> )
> 
> def test(text1):
>     return [(text1, "good"), ("\n", None), (text1, "good")]
> 
> demo2 = gr.Interface(
>     test,
>     "text",
>     gr.HighlightedText(elem_id="htext2"),
> )
> 
> gr.TabbedInterface([demo, demo2], css="#htext span {white-space: pre} #htext2 span {white-space: pre}").launch()
> ```

Thanks for your quickly reply.
yes, I think this may be the solution in this case. However, the CSS argument is not supported in gradio==3.1.3 version.

![image](https://user-images.githubusercontent.com/52521165/183049918-f885a807-e1da-43cf-bfa3-e3b3150b7f9d.png)

**Comment by abidlabs** [comment]
Hi @HuangChiEn, you can install this by using the pre-release `3.1.4b`. (The actual release `3.1.4` should be out shortly as well)

**Comment by HuangChiEn** [comment]
> Hi @HuangChiEn, you can install this by using the pre-release `3.1.4b`. (The actual release `3.1.4` should be out shortly as well)

This new version (3.1.4b) works very well. Furthermore, it can be not only integrated Interface API but also used to layout the Block API !!
 
Thanks for this amazing work ~
