### ISSUE TITLE
Bokeh plots do not appear

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#1942]
### Describe the bug

When using the `Plot` component, bokeh plots do not appear at all.

This is documented here: #1632 

> Pictures cannot be generated in Bokeh mode.

And in this PR: #1609 

> The Bokeh plots are currently broken. The reason for this is that bokehJS internally uses getElementById to get the container of the plot and render it. Since Gradio UI is using the shadow DOM to render, this step fails.

> I have tried here a workaround where I added a new hidden div in the index.html file to use as a helper to render the plot, once it is rendered, then the content is appended to the actual div that should have the plot. This part is all working, unfortunately although I can see the div with the expected content, the plot is still not showing.

The PR was closed because it was an attempt to fix the problem using an older version of bokeh. We still need to find a solution using the latest version of bokeh.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://github.com/gradio-app/gradio/blob/main/demo/outbreak_forecast/run.py

### Logs

```shell
N/A
```

### System Info

```shell
3.1.3
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
cc @dawoodkhan82 @Ian-GL

**Comment by millermuttu** [comment]
Is this Bug resolved in the latest release 3.4.0?

**Comment by dawoodkhan82** [comment]
> Is this Bug resolved in the latest release 3.4.0?

Unfortunately not yet. It is on our radar though. Will update this issue when we do resolve this.

**Comment by abidlabs** [comment]
It looks like bokeh 3.0.3 is out, so it might be good to revisit this @dawoodkhan82

**Comment by dawoodkhan82** [comment]
Will revisit!

**Comment by giswqs** [comment]
I was trying to use bokeh maps. Got an error `TypeError: Model.to_json() missing 1 required positional argument: 'include_defaults'`


```python
import gradio as gr
import xyzservices.providers as xyz
from bokeh.plotting import figure
from bokeh.tile_providers import get_provider

def create_map(text):

    tile_provider = get_provider(xyz.OpenStreetMap.Mapnik)
    p = figure(x_range=(-2000000, 6000000), y_range=(-1000000, 7000000),
            x_axis_type="mercator", y_axis_type="mercator")
    p.add_tile(tile_provider)
    return p

demo = gr.Interface(
    fn=create_map,
    inputs='text',
    outputs=gr.Plot().style(),
)
demo.launch()
```

**Comment by freddyaboulton** [comment]
Will take a look @giswqs ! My guess is that the gradio library is using an outdated bokeh api that's not compatible with the bokeh version in your demo.

Mind sharing your bokeh version? As well as xyzservices? BTW what is that library?

**Comment by giswqs** [comment]
See the example at https://docs.bokeh.org/en/latest/docs/examples/topics/geo/tile_xyzservices.html

[xyzservices](https://github.com/geopandas/xyzservices) is a lightweight library providing a repository of available XYZ services offering raster basemap tiles. 

- gradio: 3.18.0
- bokeh: 2.4.3
- xyzservices: 2022.9.0

**Comment by freddyaboulton** [comment]
Thanks @giswqs ! So the issue about `to_json() missing 1 required positional argument` should be easy to fix but the problem about the UI not displaying the plots persists. What's more, looks like there's a big difference between bokeh 2.0 and bokeh 3.0. Might be hard to support both? If we had to choose one, would 3.0 be better?

**Comment by giswqs** [comment]
Yes, prefer bokeh 3.x.

**Comment by freddyaboulton** [comment]
@giswqs We support bokeh 2 and 3 in version 3.19.0!

**Comment by giswqs** [comment]
@freddyaboulton Awesome! I tried bokeh 3.x, and it works like a charm. Thank you very much. 

```python
import gradio as gr
import leafmap.bokehmap as leafmap

def test(x):
    m = leafmap.Map()
    m.add_basemap('OpenTopoMap')
    return m.figure

demo = gr.Interface(fn=test, inputs="text", outputs=gr.Plot())
demo.launch()
```
![Peek 2023-02-21 11-22](https://user-images.githubusercontent.com/5016453/220401713-5bf57365-7b16-492c-aaa1-fbacfe87b727.gif)
