### ISSUE TITLE
Textbox submit does not work on version 3.0.6

### ISSUE THREAD

**Issue by GDalforno** [gradio-app/gradio#1944]
### Describe the bug

I'm trying to send a message to the chatbot using the enter key, but it does not seem to work. Although in the version ```gradio==2.9b7``` it works just fine (as stated [here](https://github.com/gradio-app/gradio/issues/681)), when I moved to the most recent version (3.0.6) the submit method does not do anything. I appreciate if someone can check it out. Thank you.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import random

import gradio as gr

def chat(message, history=[]):
   
    resp = random.choice(["hi", "hello", "hey", "sup"])
    history.append((message, resp))
    return history, history


with gr.Blocks() as demo:
    state = gr.Variable(default_value=[])
    chatbot = gr.Chatbot()
    text = gr.Textbox(label="Your sentence here... (press enter to submit)", default_value="How are you?")
    
    text.submit(chat, [text, state], [chatbot, state])

gr.close_all()
demo.launch(server_name="0.0.0.0", server_port=7861)
```

### Screenshot

![Screenshot from 2022-08-03 08-54-59](https://user-images.githubusercontent.com/56834802/182601887-183b8f8f-de7f-4bd4-b03c-5441ef659a90.png)

### Logs

```shell
-
```

### System Info

```shell
gradio==3.0.6

NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Severity

serious, but I can work around it

**Comment by dawoodkhan82** [comment]
@GDalforno Thanks for reporting, I'll take a look at this issue.

**Comment by dawoodkhan82** [comment]
@GDalforno setting `max_lines=1` in the Textbox should enable submit on enter.

**Comment by dawoodkhan82** [comment]
@pngwn I'm assuming this is the expected behavior for the text box right? `{#if lines === 1 && max_lines === 1}` then we allow submit on enter.

**Comment by GDalforno** [comment]
@dawoodkhan82, ```max_lines``` indeed solved the problem, thank you! I will leave the complete code to build the chatbot interface using the enter key to send the message down below. Most examples I've found make use of the submit button which sometimes does not really embrace the whole chatbot experience, at least in my opinion.

```python
import random
import gradio as gr

def chat(message, history):
    history = history or []
    message = message.lower()
    if message.startswith("how many"):
        response = random.randint(1, 10)
    elif message.startswith("how"):
        response = random.choice(["Great", "Good", "Okay", "Bad"])
    elif message.startswith("where"):
        response = random.choice(["Here", "There", "Somewhere"])
    else:
        response = "I don't know"
    history.append((message, response))
    return history, history

def main():
    with gr.Blocks() as demo:
        gr.HTML("<center><h1 style='font-size:40px;'>Chatbot Demo</h1></center>")
        state = gr.Variable()
        chatbot = gr.Chatbot(color_map=("green", "pink")).style()
        text = gr.Textbox(label="", placeholder="How are you?", max_lines=1)
        text.submit(chat, [text, state], [chatbot, state])
        text.submit(lambda x: "", text, text)
    
    demo.launch(server_name="0.0.0.0", server_port=7861)

if __name__ == "__main__":
    gr.close_all()
    main()
```
