### ISSUE TITLE
Video with IP Camera URL source

### ISSUE THREAD

**Issue by mistycheney** [gradio-app/gradio#1947]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

I have an IP camera whose stream can be accessed from http://xxx.xx.xx.xxx/mjpg/video.mjpg. I try to use Gradio to take this stream rather than feed from webcam. 
From the doc it seems "value" argument is where I specify the URL.
I tried `gr.inputs.Video`, but it does not have the "value" argument.
I then tried `gr.components.Video`, but if I set value='http://xxx.xx.xx.xxx/mjpg/video.mjpg', it complains `FileNotFoundError: [Errno 2] No such file or directory: 'http://xxx.xx.xxx.xx/mjpg/video.mjpg'`

**Describe the solution you'd like**  

How can I make gradio use the IP camera stream?

**Comment by abidlabs** [comment]
Hi @mistycheney, this is a good question. I haven't worked with IP cameras before. Can you provide a valid URL that we can use for testing?

**Comment by abidlabs** [comment]
Going to close as we cannot investigate this without more details.
