### ISSUE TITLE
How to update unselected status of gradio.Radio

### ISSUE THREAD

**Issue by Mittag-tech** [gradio-app/gradio#1953]
# Overview
- I want to update gradio.Radio with unselected status.
- But, once selected, this status is not released even if ```gradio.Radio.update(value=None)``` is set.
- To avoid this issue, I wrote like folowing code. If there is another way, let me know.

# Code
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import gradio

def main():
    with gradio.Blocks() as front_page:
        with gradio.Row():
            with gradio.Column():
                input_file = gradio.File()
                input_image = gradio.Image()
                show_button = gradio.Button(value="image show")
            with gradio.Column():
                radio_button = gradio.Radio(choices=["horse", "cat"], value=None, interactive=True)
                result_box = gradio.Text()
        input_file.change(fn=reload_file, inputs=[input_file], outputs=[result_box, radio_button])
        show_button.click(fn=show_image, inputs=[input_file], outputs=[input_image, radio_button])
        radio_button.change(fn=greet_user, inputs=[input_file, radio_button], outputs=result_box)
    front_page.launch(server_name="0.0.0.0")

def reload_file(input_file):
    try:
        image_path = input_file.name
    except Exception:
        image_path = None
    finally:
        radio_button = gradio.Radio.update(choices=list(range(3)), value=2)
        return image_path, radio_button

def show_image(input_file):
    try:
        image_path = input_file.name
    except Exception:
        image_path = None
    finally:
        radio_button = gradio.Radio.update(choices=["horse", "cat"], value=None)
        return image_path, radio_button

def greet_user(input_file, radio_button):
    try:
        input_file.name
    except Exception as err:
        return f"{err}"
    else:
        return f"This is {radio_button}!"

if __name__ == "__main__":
    main()
```

# Movement
1. input image file to ```gradio.File()```
2. update ```gradio.Radio()```
    - ```choices```: ```["horse", "cat"]``` -> ```[0, 1, 2]```
    - ```value```: ```None``` -> ```2```
3. when click ```show image```, show image and update ```gradio.Radio()```
    - ```choices```: ```[0, 1, 2]``` -> ```["horse", "cat"]```
    - ```value```: ```2``` -> ```None```
        - In this case, ```gradio.Radio()``` is pre-selected ```2```, but ```["horse", "cat"]``` is not contained ```2```.

**Comment by abidlabs** [comment]
Hi @Mittag-tech, thanks for creating this issue. 

You should be able to "clear" the Radio button by settings its value to an empty list: `[]`. So `gradio.Radio.update(value=[])`

But I agree with you that setting its value to `None` should also work, so I'm going to leave this issue open until we implement that.

**Comment by freddyaboulton** [comment]
Similar issue here about how to reset components to their original state

https://github.com/gradio-app/gradio/issues/1672

**Comment by Mittag-tech** [comment]
Thank you for the answer and consideration, @abidlabs !
I hadn't tried ```value=[]```, so I try it.
I look forward to seeing the implementation !

**Comment by Mittag-tech** [comment]
I had missed this issue, thank you for sharing, @freddyaboulton .

**Comment by abidlabs** [comment]
Yup thanks for catching that @freddyaboulton. I think we can close this issue and leave open #1672 for the general case.
