### ISSUE TITLE
Add information about available video codecs

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#1970]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

The docstring of `gr.Video` only mentions about file extensions, but a video file must be encoded with specific codecs to be playable in browsers as written in [this issue comment](https://github.com/gradio-app/gradio/issues/1508#issuecomment-1154545730).
I've seen couple of times that people (including myself) fell into this pitfall and got confused why the video didn't play as expected. See [this comment](https://huggingface.co/spaces/Yuliang/ICON/discussions/6#62e8fd3e4210d3fe69eb3637) for example.

**Describe the solution you'd like**  
It'd be helpful if there was description about available video codecs in the docstring of `gr.Video`.

**Comment by abidlabs** [comment]
This is a great suggestion! @aliabid94 I know you've looked into video codecs in the past. Would you be up for adding it to the docs?

**Comment by freddyaboulton** [comment]
Is it in scope to automatically convert the video to a codec that's playable in the browser? Would fix issues like #1972
