### ISSUE TITLE
Feedbacks and bugs for the New Queue

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1974]
🔥  The new queue beta is released
1. You can try it out over [here](https://huggingface.co/spaces/farukozderim/test-new-queue) with a basic example
2. And try it via specifying gradio==3.1.4b5

Please share your feedback and bugs you find in this issue ❤️ 

Related: #1337, #572

**Comment by FarukOzderim** [comment]
1. Queue information does not show when the user loads the page.
2. Number of people inside the queue info does not get updated with time, which results with
3/3, 2/3, 1/3 instead of 3/3, 2/2, 1/1

**Comment by FarukOzderim** [comment]
4. This happened once locally and once at spaces. 

I open 4-5 tabs in browser and connect to demo page. When I click submit in one of the tabs, all tabs behaves like they are the same client and shows the same page and updates.
ie. the ones I did not click submit also behaves as submitted. And shows the same place in the queue.

**Comment by FarukOzderim** [comment]
5. It would be nice if we should send an estimation before processing_starts to

**Comment by abidlabs** [comment]
There's duplication between this issue and #1337, so I've revamped that issue and moved this discussion there.
