### ISSUE TITLE
Write Tests for Queueing

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1983]
**Is your feature request related to a problem? Please describe.**  
We need to write tests for the new event queue in the Frontend.

**Additional context**  
Websocket testing tooling is seems to not work well in Python, and we're unable to test it in Backend.

Testing a single event case and multiple events case would be nice.

**Comment by abidlabs** [comment]
We should write unit tests for `queueing.py` as well!

**Comment by hibestil** [comment]
@abidlabs I'd like to write unit tests for 'queueing.py' if it is still unassigned. Please let me know

**Comment by FarukOzderim** [comment]
@abidlabs due to limitations of tooling we cannot test functionality of the queue in Backend. That's why there needs to be queue functionality tests in Frontend IMO. If that is not possible, then some manual testing will be necessary, and spaces demos has queue activated by default, automatic spaces demo deployments will help 👍 

> Websocket testing tooling is seems to not work well in Python, and we're unable to test it in Backend.
