### ISSUE TITLE
Improve Queue ETA calculation via exponential weighted average

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1984]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Currently we take average of all the function events to calculate the average processing time. However as there are different functions inside each event, it would be more precise to calculate the average based on the fn_index.

**Comment by abidlabs** [comment]
We can do an [exponentially weighted average](https://medium.com/@dhartidhami/exponentially-weighted-averages-5de212b5be46), which is easy to calculate, space efficient, and adapts to the most recent samples

**Comment by abidlabs** [comment]
Just realized my comment doesn't make any sense. The proper thing to do here is to have different queues for different events AND then return an ETA based on that event's queue. Closing this issue in favor of #2216 for clarity
