### ISSUE TITLE
HTML block does not display spinner

### ISSUE THREAD

**Issue by duerrsimon** [gradio-app/gradio#1985]
### Describe the bug

Most blocks when they are used as output like Textbox display an orange spinner indicating that the model is running. 
For HTML blocks no such spinner is available which from a UX perspective is very confusing if the output is only HTML. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See https://huggingface.co/spaces/simonduerr/3dmol.js as demo

### Logs

```shell
UX bug
```

### System Info

```shell
using gradio 3.1.4
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks for pointing this out @duerrsimon. I can reproduce this issue with a simple example:

```py
import gradio as gr
import time

def test(x):
    time.sleep(5)
    return x

gr.Interface(test, "textbox", "html").launch()
```

@dawoodkhan82 would you be able to look into this and add the loading indicator to the `HTML` component?
