### ISSUE TITLE
Create guide for using Plot component

### ISSUE THREAD

**Issue by dawoodkhan82** [gradio-app/gradio#1993]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by abidlabs** [comment]
I this this was meant to be closed as part of #2402 @dawoodkhan82? It might potentially make sense to another Guide on Plots but we can probably close this for now, wdyt?
