### ISSUE TITLE
Adding image in markdown not working, gives broken image in the browser

### ISSUE THREAD

**Issue by millermuttu** [gradio-app/gradio#1997]
### Describe the bug

I wanted to add an image to the heading of the page and tried adding using markdown as follows

```
gr.Markdown("![image](z.png)")
```
but it fails to load the image and gives broken image thumbnail

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
gr.Markdown("![image](z.png)")
```

### Screenshot

![image](https://user-images.githubusercontent.com/30842362/184094619-f9eaf110-4d9d-4dd8-a060-4d828ce6654d.png)

### Logs

```shell
No logs
```

### System Info

```shell
Gradio version - 3.1.0
python version - 3.8
OS : Windows
Browser: Chrome
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @millermuttu thanks for raising the issue. This issue happens because the web app doesn't know how to resolve the path to the image that you provided. If you preface the image link with "file/" it should work.

Here's a working example for me:

```py
with gr.Blocks() as demo:
    gr.Markdown(
"""
# Hi
![](file/lion.jpg)
""")
    
demo.launch()
```

If you use URLs, it should also work just fine:

```py
with gr.Blocks() as demo:
    gr.Markdown(
"""
# Hi
![](https://i.picsum.photos/id/237/200/300.jpg?hmac=TmmQSbShHz9CdQm0NkEjx1Dyh_Y984R9LpNrpvH2D_U)
""")
    
demo.launch()
```

Let us know if this works for you!

**Comment by millermuttu** [comment]
Hi @abidlabs  I tied the solution you provided, still no luck, its still shows as broken image

**Comment by abidlabs** [comment]
Hi @millermuttu are you sure that the image is in the same directory as the Gradio file?

Here's a colab notebook that shows working examples of both of the approaches that I described: https://colab.research.google.com/drive/1rDrXnL8viMoTzUWZwa9rW6ItxAh5Kknc?usp=sharing

**Comment by millermuttu** [comment]
got it.. thanks @abidlabs

**Comment by nameless0704** [comment]
> Hi @millermuttu are you sure that the image is in the same directory as the Gradio file?
> 
> Here's a colab notebook that shows working examples of both of the approaches that I described: https://colab.research.google.com/drive/1rDrXnL8viMoTzUWZwa9rW6ItxAh5Kknc?usp=sharing

I'm having the same problem but it cannot correctly display in either colab or my PC project... Does that really work?

**Comment by kambleakash0** [comment]
same here @nameless0704

**Comment by abidlabs** [comment]
Hi @nameless0704 @kambleakash0 can you please provide the minimal code samples so that we can reproduce?

**Comment by larryyin** [comment]
Not working, either adding "file/" or not.

**Comment by kjappelbaum** [comment]
You need to add [`allowed_paths`](https://www.gradio.app/docs/interface#interface-launch) in never versions. 

For example

```
 app.launch(allowed_paths=["/tmp/"])
```

**Comment by niranjanakella** [comment]
For clarity the way I solved it is as follows:

Place the image in the same location as your Gradio app.py file. 
```
gr.Markdown("![](file/logo.png)")
app.launch(server_name="0.0.0.0", allowed_paths=["/"])
```
So here "/" tells the application to search for logo.png file at the interpreter directory level. That means, when you run `python3 app.py` your terminal path should be in the same location as the image. 

Eg:
```
~/Project
|---app_folder
    |---app.py
|---logo.png
```
Before running `python3 app.py` you should `cd ~/Project` and then `python3 app_folder/app.py`
