### ISSUE TITLE
API Docs Request URLs Are Broken

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1998]
### Describe the bug

https://hf.space/embed/farukozderim/test-new-queue/+/api/predict

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Go to this space and see the API Docs
https://huggingface.co/spaces/farukozderim/test-new-queue

### Screenshot

<img width="606" alt="image" src="https://user-images.githubusercontent.com/44067394/184132809-eb21d859-770b-49ac-aa5c-b679a6021886.png">

### Logs

```shell
*
```

### System Info

```shell
*
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
I don't quite understand. What's wrong here? Here's the page that I see when I click view API:

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/1778297/184465001-b8dad99f-e9de-4b11-91aa-30e2907e8cba.png">

**Comment by FarukOzderim** [comment]
Oh sry, let me make it more clear. There is an + in the url which makes it incorrect:

https://hf.space/embed/farukozderim/test-new-queue/+/api/predict

**Comment by abidlabs** [comment]
Actually, that "+" is supposed to be there. The reason is that the actual URL for the Space itself is:

https://hf.space/embed/farukozderim/test-new-queue/+

Which is embedded via an iframe into the original URL. 

You can confirm that this works by doing the following:

```py
import requests
r = requests.post("https://hf.space/embed/abidlabs/hello-world/+/api/predict", json={"data": ["hello"]})
r.json()

> {'data': ['Hello hello'],
> 'duration': 0.00018525123596191406,
> 'average_duration': 0.0001957416534423828}

```
