### ISSUE TITLE
Interpretation functionality not working 

### ISSUE THREAD

**Issue by jraza19** [gradio-app/gradio#200]
Hello!

I am using Gradio for a school project where our input is an image. I tried setting up the interpret functionality with the `interpretation="default"`, however, nothing happens! I then tried to replicate one of the examples in the repo here and I was still not able to get the interpret functionality to work. I see the "Interpret" button but nothing happens when you click on it. My team mate also tried testing this in a different virtual environment and even enabling all pop-ups with no luck.

Any ideas on why this might be happening? 

Thanks! Gradio is a really cool tool :)

Sincerely, 

Javairia

**Comment by abidlabs** [comment]
Thanks for bringing that to our attention @jraza19! We are looking into this. In the meantime, can you let us know if you use an older version of Gradio as well? (`pip install gradio==1.7.6`)

**Comment by jraza19** [comment]
@abidlabs - thank you for your prompt response. I can confirm that with `gradio==1.7.6` version, all functionality including the edit and interpret button is working!

**Comment by abidlabs** [comment]
Ok great, we're working on the patch for Gradio 2.0. Thanks again for bringing this to our attention!
