### ISSUE TITLE
Keep WS Connections Open After Processing

### ISSUE THREAD

**Issue by omerXfaruq** [gradio-app/gradio#2001]
**Is your feature request related to a problem? Please describe.**  
Currently ws connection is killed in frontend after the processing of the event is completed. We should keep the connection open for 5 or 10 additional minutes. Can make this configurable in the Python side as well.

**Additional context**  
Backend supports this right now, see [here](https://github.com/gradio-app/gradio/pull/1910#issuecomment-1200063893).

**Comment by abidlabs** [comment]
This reduces the overhead of having to create new websocket connections

**Comment by abidlabs** [comment]
This has been superseded by the SSE approach in https://github.com/gradio-app/gradio/pull/6556. Closing!
