### ISSUE TITLE
Send ETA before Processing in Queue

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#2004]
**Is your feature request related to a problem? Please describe.**  
Sending an estimation message while process is starting would create a better UX.

**Describe the solution you'd like**  
Currently we are sending a message when the process starts, so we could put the estimation inside it.
{"msg": "process_starts", **estimation}

**Comment by abidlabs** [comment]
I haven't heard this feature requested by users. I also think it's fine for users to have to click and engage with the Gradio UI, and then if the queue is too long, they can always leave. So I'm inclined to close the issue. WDYT @freddyaboulton @aliabid94 (or @FarukOzderim!)?

**Comment by FarukOzderim** [comment]
It is a very easy to add feature and also needed imo. It also lets you monitor the traffic on a space. 

Also think about complex spaces, user will spend some time and realize there is a very long queue.

**Comment by abidlabs** [comment]
I did some more digging through our issues and I found that this feature actually *has* been requested by users lol: https://github.com/gradio-app/gradio/issues/435

Let me close this issue and we can discuss over there
