### ISSUE TITLE
Gracefully Scaling Down on Spaces With the new Queue

### ISSUE THREAD

**Issue by omerXfaruq** [gradio-app/gradio#2019]
**Is your feature request related to a problem? Please describe.**  
Scaling up works alright however Scaling down is a pain point right now. When we tested scaling down, clients lost connection to the server and queue info stopped getting updated.  
<img width="758" alt="image" src="https://user-images.githubusercontent.com/44067394/184917082-34e16681-3b81-4b8c-bfd6-c4fe3706c5cc.png">

**Describe the solution you'd like**  
There are 3 ways we can solve this.
1. If autoscale can scale down(kill an instance) when queue-size==0 (easiest one) (Christophe Rannou will let us know about this)
2. Take a look at what Gradio do at the cancel signal(I think this is same as ctrl+c) and wait until to Queue to finish when we receive the signal.
3. Add timestamp to the each event and let client join into another queue whenever the ws connection is lost. And the server would put the event to a rank according to its timestamp 
(This would be useful if mobile connections' shaky internet connections will cause ws connection to get lost, might not ever happen as well)

I would prefer 1>3>2

**Comment by abidlabs** [comment]
I don't remember what this issue was about? Does anyone? Or should we close this?

**Comment by freddyaboulton** [comment]
Don't remember either

**Comment by abidlabs** [comment]
Ok let's go ahead and close this
