### ISSUE TITLE
Deploying Gradio app (using Blocks, not interface) on AWS

### ISSUE THREAD

**Issue by irfan-mekic** [gradio-app/gradio#2024]
I'm running into some issues with deploying a Gradio app on AWS, since it's not an interface but rather a block. I tried following the tutorial https://abidlabs.medium.com/quickly-deploying-gradio-on-aws-242af2374784, but I wasn't able to successfully replicate the process. Any help would be greatly appreciated!

**Comment by abidlabs** [comment]
Hi @irfan-mekic, thanks for creating this issue. What issue are you running into specifically when you try to deploy your `Blocks`?

**Comment by irfan-mekic** [comment]
I follow the guide regarding the network settings (pictured below), and I try to access the ip, and don't get a live dashboard back.

![image](https://user-images.githubusercontent.com/92335543/184988576-2b12ce67-3e0b-4a67-8290-d4809d14d216.png)

**Comment by irfan-mekic** [comment]
Im also deploying from inside a Docker container, as the ec2 instance is used by other members on my team. This is fine, correct?

**Comment by abidlabs** [comment]
It should definitely be possible to deploy from inside a docker container as long as the server name and port are set up correctly. 

I noticed while reading the Guide that there is 1 issue with it. The `server_name` parameter has been moved to `launch()`. Did you make that change? Also did you make sure to bind port 7860 in the docker to 7860 on the AWS machine?

**Comment by irfan-mekic** [comment]
Yes, I made the  regarding the `server_name` parameter. Ahh, I did not do the port binding. Let me attempt to do that to see if it fixes the issue

**Comment by irfan-mekic** [comment]
I'm also returning 'http://localhost:7860/' instead of 'http://0.0.0.0:7860/'

**Comment by irfan-mekic** [comment]
This has been resolved. In case anyone else finds it helpful, this is what I had to do (slightly) different from the guide to get it running. This assumes you're using a Docker container to run your Gradio app:

1. Inside the Dockerfile, you need to use the `EXPOSE` command to expose the Docker port you want connected to your ec2 instance
2. On your `docker run` command, you need to add the flag `-p DockerPort: EC2Port', where DockerPort is the same port as in the EXPOSE command in your Dockerfile (note, that the port in your EXPOSE command must be the same port in your launch() method...I recommend passing in an explicit value to server_port in launch()), and EC2Port is the port you want the app to be accessible on. So, if the DockerPort is 8080, but you want the app to be accessible on 80, you'd add `-p 8080:80'
3. Run your application as you normally would ("python app.py"), and ensure you correctly exit your container while it is still running.
4. You should now be able to access the Gradio app using the EC2 instances public IP DNS and the port. I found issues trying to use the public IP address instead of the public IP DNS. So, the link would look something like: "ec2-XX-XXX-XX-XX.us-west-2.compute.amazonaws.com:80"

**Comment by abidlabs** [comment]
Thank you so much @irfan-mekic for sharing the solution!
