### ISSUE TITLE
Text showing without breaks in result text! Also, slider isn't working.

### ISSUE THREAD

**Issue by swcrazyfan** [gradio-app/gradio#203]
I've been testing out my model through Google Colab, and suddenly all the UI I built with Gradio aren't working. HTML in the article doesn't work, the slider doesn't work, and the result text has no line breaks.

I had an older version of Gradio on my local computer, and that worked perfectly. What's going on? Is there an update on the way?

Thanks! Honestly, Gradio is great besides these bugs!

**Comment by abidlabs** [comment]
Thanks @swcrazyfan! We are looking into this issue right now, and should have a fix soon.. For now, you may want to install an older version of Gradio inside colab. (e.g. `!pip install gradio==1.7.6`)

**Comment by aliabid94** [comment]
Thanks for pointing these out! Fixed the slider and article HTML issues in gradio 2.0.1. Will fix the line breaks as well.

**Comment by swcrazyfan** [comment]
Thanks! I've installed the version you suggested. I'll wait on using the newest version until these bugs are worked out.

**Comment by aliabid94** [comment]
Line breaks fixed. Let us know if you see any other issues!
