### ISSUE TITLE
The sketch mode of gr.Image require more support.

### ISSUE THREAD

**Issue by HuangChiEn** [gradio-app/gradio#2030]
As the title described, I have tried to setup the `gr.Image(tool='sketch')` as follows :
![image](https://user-images.githubusercontent.com/52521165/185068036-cfca5049-2379-40a7-8b2b-271226d65a0a.png)

The web exactly supports the sketch-pen for us as follows : 
![image](https://user-images.githubusercontent.com/52521165/185068474-ce94feb9-322b-4131-b987-620fc2b37a89.png)

However, I believe someone discover the problem, the default sketch-pen **extremely bold** and the corresponding color is **transparency white**, which is barely visualize in the image.

Does it have any support for this method for adjusting the sketch-pen bold shape, such as `shape=(7, 7)` and the color picker of sketch-pen?

### What I have tried : 
I have tried the following setup for gr.Image
![image](https://user-images.githubusercontent.com/52521165/185069345-4158639e-b5c7-47bf-aa44-5277e06ed84f.png)
> As expected, it doesn't work. The sketch-pen is still extremely bold..

##### What worse
For the default setup of scratchpad mode ` image_mode="L", source="canvas", shape=(28, 28), invert_colors=True`, the shape can be adjusted by `shape=(7, 7)`.
![image](https://user-images.githubusercontent.com/52521165/185070561-42227244-12f1-42de-92b4-147fa1124718.png)

the setup code 
![image](https://user-images.githubusercontent.com/52521165/185070709-1f6c7db1-e980-4313-8cf1-edeaf67046e1.png)

Any suggestion and feedback will be appreciated!!

**Comment by pngwn** [comment]
The `shape` kwarg doesn't control the brush. However this is being worked on.

The weird scaling on the brush is a bug, the ability to resize it is a feature that we will be adding (as well as selecting an appropriate default size depending on the cavas size).

**Comment by HuangChiEn** [comment]
> 

thanks for your reply ~
then we look forward to the solution of it.
