### ISSUE TITLE
Support for more interesting/engaging loading indicators

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#2032]
For demos that go viral, it would be nice to allow the developer to set a more interesting loading indicator than just showing the ETA and queue position. 

Some ideas that we brainstormed:
* a simple game they could play
* an RL-powered game they could play / watch
* showing some other example inputs and outputs for the model
* a video about Gradio

**Comment by abidlabs** [comment]
I don't think this is too important and am inclined to close the issue unless there are any objections, cc @aliabid94 @freddyaboulton?

**Comment by freddyaboulton** [comment]
Yea I'm good with closing this
