### ISSUE TITLE
Client Error Handling

### ISSUE THREAD

**Issue by baishalidutta** [gradio-app/gradio#204]
There are many situations where you need to notify an error to the client. For example, input validation error.

In such scenario, it makes sense to introduce a specific type of exception that can be thrown programmatically and the exception message can then be easily shown on the Gradio Web Interface.

**Comment by abidlabs** [comment]
That's a great suggestion @baishalidutta! We'll add it to our roadmap

**Comment by abidlabs** [comment]
@dawoodkhan82 is working to pipe errors to the front end:

![image](https://user-images.githubusercontent.com/1778297/137427693-1b838d95-ff55-4f7b-ac26-519e9becbcd7.png)

**Comment by abidlabs** [comment]
This is now live in Gradio 2.4.0!

**Comment by irfan-mekic** [comment]
How exactly does this work? I haven't seen anything in the documentation that explains how to create the custom Error messages

**Comment by dawoodkhan82** [comment]
> How exactly does this work? I haven't seen anything in the documentation that explains how to create the custom Error messages

Hey @irfan-mekic, you can set `show_error` as True in the `launch()` method. This will allow any errors to be printed in the browser's console log. We don't currently support showing custom error messages on the interface itself, but that is something on our roadmap.

**Comment by irfan-mekic** [comment]
Got it. Thank you!

**Comment by Stihotvor** [comment]
Would be lovely to see some exception handling when using `click` method
