### ISSUE TITLE
Make it easier to work with streaming data

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2050]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
A data scientist might be interested in building a dashboard that pulls live data periodically. 

For example, every five minutes visualize the locations of the most popular tweets talking about Gradio. 
Every hour, refresh a plot showing our sales trend over the last quarter. 

**Describe the solution you'd like**  
Add an event trigger that sets a time delta when the page should be refreshed.

```python
with gr.Blocks() as demo:
    ....
    demo.refresh(fn=pull_data, inputs=[...], outputs=[...], on=gr.TimeDelta.Minutes * 5)
```

Open question: Build this for interfaces?

**Additional context**  
Might lead to interesting demos but not an immediate priority for Data Science milestone

**Comment by abidlabs** [comment]
I wonder if it would make sense to use the `streaming` parameter that we have for Image/Audio applied to other components, or to the demo as a whole?
