### ISSUE TITLE
Make it easier to export a demo defined in a notebook to spaces

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2051]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Imagine you're a data scientist and you just finished an analysis of a tabular data set on a jupyter notebook. 

You have some plots and maybe a machine learning model trained but the journey you took to get there is not straight line since your analysis took turns the more you learned about the dataset.

Let's say you wanted to share your results with your peers. Your options are:

* Upload the notebook github.
  * **PROS:** This is easy and quick. Github can display jupyter notebooks.
  * **CONS:** Not interactive! Hard to reproduce. All the parts you don't want to share are still there so they will be distracting.
* "Clean it up" and turn it into a python script.
  * **PROS**: All the parts you want to share are part of the script. 
  * **CONS:** Takes time. Also not interactive. Hard to reproduce and not suitable to non technical stakeholders.
* Turn it into a Gradio app.
  * **PROS:** This is interactive! Non technical users easily can see you work by going to a url.
  * **CONS:**: It still takes more time than uploading notebook to github! Users have to go through the "clean up" phase to turn their existing code into an app. 

I'm wondering if we can decrease the time it takes to go from notebook to gradio demo. Would we easily win over data scientists?

**Describe the solution you'd like**  
What if we defined a set of directives users can sprinkle into their notebook after their analysis is done. Once they do that, they just run `gradio convert analysis.ipynb` and they get `analysis.py` that's a working gradio demo. We can also add a command to automatically upload to the hub as well! `gradio upload analysis.ipynb` 

Example API:

<img width="823" alt="image" src="https://user-images.githubusercontent.com/41651716/185707865-046779bb-e0ae-4fa9-a756-1dfd0a306336.png">

Would get turned to 

```python
sales = pd.DataFrame({"date": pd.date_range("2022-01-01", periods=30),
                      "sales": list(range(30))})

with gr.Blocks() as demo:
    gr.Plot(value=sales.plot(x='date', y='sales'))
```

This is similar in spirit to nbdev: https://nbdev.fast.ai/02_Explanations/directives.html

There could be other solutions here. This idea has to be validated prior to implementing. You can already define a gradio demo inside a jupyter notebook but there might be value in speeding up the process. Thoughts @dawoodkhan82 @abidlabs ?

**Additional context**

**Comment by FarukOzderim** [comment]
I think this is a really strong way to convert a notebook to Gradio demo. However is there anything more than copying each cell into a file?

Also being able to create a space directly from colab links and files would be great!

**Comment by abidlabs** [comment]
Will think about it some more, very exciting!

**Comment by freddyaboulton** [comment]
This is basically quarto: https://quarto.org/. Let's see if it can build gradio demos!

**Comment by freddyaboulton** [comment]
After speaking with @merveenoyan @abidlabs @dawoodkhan82 @pngwn and @AK391 in person, we realized that it would really benefit colab and kaggle users if they could automatically export a demo defined in a notebook to an HF space.

This could also make it super easy to embed gradio demos in the docs of other libraries (typically built from markdown) and potentially make it easier to embed gradio demos in [quarto](https://quarto.org/) docs.

A potential API - define a jupyter magic command

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/41651716/200878040-422841af-1a74-4b5c-b462-49b90831a2cb.png">

Need to think about how to specify dependencies.

Renaming this issue to reflect the narrower scope.
