### ISSUE TITLE
When a video (w, h=608x1080) is input, the preview video becomes too large.

### ISSUE THREAD

**Issue by markdchoung** [gradio-app/gradio#2056]
**Is your feature request related to a problem? Please describe.**  
When a video (w, h=608x1080) is input, the preview video becomes too large.
I have to scroll down to watch the automatically up-scaled video, and it is uncomfortable.

**Describe the solution you'd like**  
It would be nice if the size of the video component window size is constant, even if a video (height is longer than width) is input.

**Additional context**  
Please let me know if there is workarounds to implement the fixed size of preview video component.

**Comment by zyx1213271098** [comment]
I had the same problem

**Comment by abidlabs** [comment]
Hi, @markdchoung @zyx1213271098 can you please provide a code example we can run to reproduce this issue?

**Comment by abidlabs** [comment]
Closing for lack of reproducible code.
