### ISSUE TITLE
Allow variation in stroke color, width, and opacity with Gradio sketch input

### ISSUE THREAD

**Issue by 1jsingh** [gradio-app/gradio#2060]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
The current "sketch" inputs do not allow variation in stroke color, width, and opacity. This compatibility would allow for deploying gradio apps for a range of user-scribble based image synthesis and editing applications.

**Describe the solution you'd like**  
Add support gradio sketch inputs to allow variation in stroke color, width and opacity.

**Additional context**  
Please refer to https://github.com/1jsingh/paint2pix for an example app deployed with streamlit-drawable-canvas which performs image editing and synthesis from coarse user-scribbles. It would be great to have gradio support similar drawing capabilities to allow for a range of interactive image editing applications.

**Comment by HuangChiEn** [comment]
add eyes on this issue.
Also similar issue #2030

**Comment by pngwn** [comment]
This is being worked on along with all other Sketch related issues currently.
