### ISSUE TITLE
Web component Embed changes title

### ISSUE THREAD

**Issue by duerrsimon** [gradio-app/gradio#2065]
### Describe the bug

I have Gradio app hosted on spaces embedded into an interactive manuscript and the Web component seems to overwrite the `<title>` set in the HTML document to "Gradio" which I don't want. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://lcbc-epfl.github.io/metal-site-prediction/

### Screenshot

![image](https://user-images.githubusercontent.com/16979577/186230891-cf702137-eb39-4cbf-8f17-6dff0e50b26b.png)

### Logs

```shell
NA
```

### System Info

```shell
The issue persists with https://gradio.s3-us-west-2.amazonaws.com/3.0.26/gradio.js
```

### Severity

annoying

**Comment by pngwn** [comment]
Yeah, this is bad. Should hopefully be a simple fix.
