### ISSUE TITLE
Plots are not displayed side by side when using blocks

### ISSUE THREAD

**Issue by GDalforno** [gradio-app/gradio#2068]
### Describe the bug

I am trying to display two plots side by side using blocks but just one of them is shown. I tried to decrease the plot size (I am using plotly btw), displaying them on 2 separate rows but nothing seemed to work. I tried with matplotlib and it works, but I do need it to work with plotly as well.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction
```python
import gradio as gr
import plotly.express as px

fig1 = px.bar(x=["a", "b", "c"], y=[1, 3, 2], width=400, height=400)
fig2 = px.bar(x=["d", "e", "f"], y=[2, 6, 4], width=400, height=400)
    
with gr.Blocks() as demo:
    with gr.Row():
        g1 = gr.Plot(fig1)
        #g2 = gr.Plot(fig2)
    with gr.Row():
        # g1 = gr.Plot(fig1)
        g2 = gr.Plot(fig2)

gr.close_all()
demo.launch(server_name="0.0.0.0", server_port=7861)
```
### Screenshot

![Screenshot from 2022-08-23 17-17-15](https://user-images.githubusercontent.com/56834802/186257561-1d882445-78e2-4bf2-8fd7-2802231c3902.png)

### Logs

```shell
None
```

### System Info

```shell
gradio==3.0.6
plotly==5.10.0

NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
@GDalforno I can't reproduce with gradio 3.1.7 and gradio 5.10.0!

![image](https://user-images.githubusercontent.com/41651716/186274528-8365a978-b096-4939-9cc8-32affdf01d37.png)

**Comment by GDalforno** [comment]
@freddyaboulton It worked in version 3.1.7 but the plots are not interactive anymore, as I move the mouse around the plot it does not show any information. Thank you.

**Comment by freddyaboulton** [comment]
Thanks for the follow up @GDalforno ! 

We're actively working on the interactivity as part of https://github.com/gradio-app/gradio/issues/1692 ! 

Should be fixed soon
