### ISSUE TITLE
Gradio Viral [tracking and feedback]

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#2071]
We'd like to make it easier to build viral machine learning and data science demos using Gradio, and are taking a number of steps to do that. This issue tracks these steps, and is also a call for the Gradio community for feedback: **please let us know by replying what we can do to help you build the next viral demo!** 

**Image demos**
- [ ] #1977 
- [ ] #1382 
- [x] #776
- [x] #936 (seeds for generative models)
- [ ] #1976 
- [x] #2103

**Video demos**
- [x] #1072

**Audio demos**
- [x] #2072

**HTML demos**
- [x] #1985

**General demos**
- [x] #938 
- [ ] #959
- [x] #2032
- [x] #340
- [x] #1162 
- [ ] #1078 
- [x] #2014

**Link users back to Gradio/Spaces**
- [x] #257 
- [ ] #1502

**Comment by apolinario** [comment]
Very cool collection of issues! I would still advocate for one more if we could make the UI/UX behave nicely - typeable fields on the slider: https://github.com/gradio-app/gradio/issues/936 - also I think this becoming commonplace UI nowadays that sliders have a typeable field too

E.g.: 
GPT-3 
![image](https://user-images.githubusercontent.com/788417/186866121-049124c9-7605-406e-b4c2-16e406127706.png)

Replicate
![image](https://user-images.githubusercontent.com/788417/186861661-ee26ecc8-5668-4da0-b8c2-aea4a32d34f5.png)

Without it, the current `seed` argument in the Stable Diffusion Spaces is essentially not useful right now as if you change the slider getting back to a specific value you want is almost impossible
![image](https://user-images.githubusercontent.com/788417/186860172-dcb9eddb-147b-45d1-a192-5b0c3ec483b5.png)

Maybe this means that the slider component isn't the most adequate there, but then we would need this other issue to support minimum and maximum values to the `gr.Number` component (here: https://github.com/gradio-app/gradio/issues/934) - and `randomize=True` support as well imo

**Comment by abidlabs** [comment]
Thanks for the suggestion for #936, agreee that it would be helpful for generative models. I think supporting min, max, and randomize for ‘Number’ is the way to go here (keeps the UI simple) @aliabid94

**Comment by altryne** [comment]
I've worked on the updated stable diffusion UI and I have so many comments. (Gradio is amazing btw, can't believe how fast interfaces can be built together) 

- Width properties! I had to hack together making the columns difference widths and would love a native solution for grid like widths. Flexbox supports this
![CleanShot 2022-08-27 at 10 26 21@2x](https://user-images.githubusercontent.com/463317/187039162-a8f41a4a-de48-476d-833a-d60aaba01efe.jpg)

- Add class_name property to all blocks, some of us know tailwind/css and would LOVE to be able to add this for UI composability
- Make ALL elements receive the click property, things like Gallery for example, I would love to receive an event that a user chose an image(usecase is, using this image in another tab for upscaling) 
- Copy to clipboard support. Right now it's Hacky via the _js function
- Maybe add Input as a separate variation of TextArea? By default the textArea is multiline, which forces a user to create interfaces with a button. Where as the standard on the web is, if you hit enter in any input in a form, the form submits. 
- Options to remove the border around a textArea. I really wanted to have a simple input + button aligned design and it wasn't possible as the border is being forced on the input
- Add the option to have a collapsable group. Can be hidden or shown by default and click will change if the contents are shown or hidden.

**Comment by abidlabs** [comment]
This is awesome @altryne thanks for all of the feedback! Several of these are already in the works :)

**Comment by abidlabs** [comment]
> Copy to clipboard support. Right now it's Hacky via the _js function

Quick clarification here: is this for copying images or text or something else?

**Comment by altryne** [comment]
@abidlabs I used it to copy images and text (for SD it was seeds, prompts etc')

**Comment by abidlabs** [comment]
Ok that makes sense. Also to clarify:

> Add class_name property to all blocks, some of us know tailwind/css and would LOVE to be able to add this for UI composability

Have you tried using element IDs? You can pass in an `elem_id` parameter to any `Component` or `Block` and it will allow you to target it via css. Docs: https://gradio.app/custom_CSS_and_JS/#the-elem_id-argument

**Comment by altryne** [comment]
Absolutey, I used IDs everywhere I could. 
Some elements don't receive them, which led to some hacks, but Classes could be useful as well if I want to apply the same class and style all my buttons for example in one way.

**Comment by osanseviero** [comment]
Very cool list of issues! I'm particularly excited about the following 3 in terms of virality
* https://github.com/gradio-app/gradio/issues/776 This enables interesting use cases for diffusion models and Reinforcement Learning
* https://github.com/gradio-app/gradio/issues/2032 
* https://github.com/gradio-app/gradio/issues/1502

**Comment by abidlabs** [comment]
Closing this tracking issue and milestone as we're not tackling the remaining issues "as a group". Will leave the individual issues open as we'll get around to solving them eventually.

**Comment by altryne** [comment]
Good times were had in this thread

**Comment by abidlabs** [comment]
Very true :D
