### ISSUE TITLE
Where is the CSS style file location while lunch the demo, and how could i locate the image resource by CSS url ?

### ISSUE THREAD

**Issue by HuangChiEn** [gradio-app/gradio#2074]
First, thanks for you'll release this amazing repo for fast building ML GUI.
I notice that customize CSS allow us insert arbitrary image as background. However, `{background-image: url(...) }` requires the user to indicate the source path. However, I have tried several combinations to locate the source path, which does did not work.
```
# suppose i have an image under /workspace/data/ex.jpg, the demo.py lunch the demo in /workspace folder
# what i have tried : 
css_def = " #exm_id { background-image: url('data/ex.jpg') }"  
#css_def = " #exm_id { background-image: url('/workspace/data/ex.jpg') }"  
#css_def = " #exm_id { background-image: url('/data/ex.jpg') }" 

demo = block(css=css_def)
with demo:
    ...

if __name__ == "__main__":
    # a bit complex setup..
    demo.lunch(server='0.0.0.0', port='4444')  # in docker
    # docker run -it -p 4444:5555 dkr_img bash
    #     and i have open the browser to view this demo website "xx.xx.xx.xx:5555" 
```

I wonder where is the CSS style file location, since most of path apply the relative path of CSS style file to locate the source image.

Any suggestion about CSS is also appreciated !!

**Comment by abidlabs** [comment]
Hi @HuangChiEn can you try putting the prefix “file/“ before the relative or absolute path to your image URL?

**Comment by abidlabs** [comment]
Here is a working example:

```py
import gradio as gr

with gr.Blocks(css="#t{background-image: url('file/lion.jpg') }") as demo:
    gr.Textbox(elem_id="t")

demo.launch()
```

Which produces this:

<img width="721" alt="image" src="https://user-images.githubusercontent.com/1778297/187062198-551d8d6d-9f78-4038-9a19-619d3f69d4f6.png">

I'll keep this issue open until we document this better

**Comment by HuangChiEn** [comment]
> Here is a working example:
> 
> ```python
> import gradio as gr
> 
> with gr.Blocks(css="#t{background-image: url('file/lion.jpg') }") as demo:
>     gr.Textbox(elem_id="t")
> 
> demo.launch()
> ```
> 
> Which produces this:
> 
> <img alt="image" width="721" src="https://user-images.githubusercontent.com/1778297/187062198-551d8d6d-9f78-4038-9a19-619d3f69d4f6.png">
> 
> I'll keep this issue open until we document this better

@abidlabs 
Thanks for your rapidly reply and the proposed solution exactly solve the problem, many thanks !! 

![image](https://user-images.githubusercontent.com/52521165/187103532-d1d21394-97c9-4211-9772-3f646f56e2a0.png)
