### ISSUE TITLE
Multi-tasking on mobile (iOS/Android) seems to silently remove user from the queue

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#2075]
### Describe the bug

If I am running a Gradio demo on Android (Galaxy Fold 3) and I do multi-tasking (leave the browser app and go to another app), when I go back to the browser the processing counter is still counting - however the queue never moves, which makes me think that I got de-registered from the queue but was not informed.

--

At least I think it should be shown to user they got de-registered (the execution was stopped) - though In an the ideal world a multi-tasking phone user would not get de-registered (I think?) - but I don't know if there's anything to differentiate a user that closed the tab - which we want to dequeue, from a user that is multi-tasking and may have the tab suspended

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run it on your Android phone

### Screenshot

![image](https://user-images.githubusercontent.com/788417/186379693-7313cf02-ab35-40a8-9c26-71158647bf55.png)

### Logs

```shell
No logs
```

### System Info

```shell
Stable Diffusion Spaces demo running on Galaxy Fold 3
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Now that we show an error if the connection is disconnected, we can close this issue, right @aliabid94 @apolinario?

**Comment by apolinario** [comment]
Imo ideally we would try to find ways to not disconnect the user in case they are multi-tasking on mobile. I wonder if the Page Visibility API or a "reconnect if they are back after x amount of time" would be avenues worth exploring. [Some more context for it](https://huggingface.slack.com/archives/C02QZLG8GMN/p1661757861712289?thread_ts=1661446477.396999&cid=C02QZLG8GMN) (internal)

**Comment by abidlabs** [comment]
Makes sense. I believe @aliabid94 looked into it, WDYT of the feasibility of this @aliabid94?

**Comment by aliabid94** [comment]
Yes it's possible and definitely needs to be done. Will require restructuring our queue system a bit. Will work on this very soon.

**Comment by abidlabs** [comment]
That makes it easier to test, thanks @apolinario!
