### ISSUE TITLE
run in public IP

### ISSUE THREAD

**Issue by johnfelipe** [gradio-app/gradio#208]
root@machineteacheble-ubuntu-s-8vcpu-16gb-nyc1-01:~/gradio/demo# python3 tax_calculator.py
	Running locally at: http://127.0.0.1:7860/
	To create a public link, set `share=True` in `launch()`.

How can run and view in my public ip hosted by digitalocean droplet
Tnks

**Comment by abidlabs** [comment]
Follow this guide, it's for AWS EC2 machines, but it should be essentially the same process: https://abidlabs.medium.com/quickly-deploying-gradio-on-aws-242af2374784

**Comment by abidlabs** [comment]
Closing, but feel free to open if you run into any issues.

**Comment by johnfelipe** [comment]
That works in digitalocean?

**Comment by abidlabs** [comment]
It should! Let me know if you run into any issues.

**Comment by johnfelipe** [comment]
For example gradio app for sketch is not working
And someones only works in localhost or 12.0.0.1, how can switch for public
IP?
