### ISSUE TITLE
Add support for `object-detection` pipeline in `transformers`

### ISSUE THREAD

**Issue by Ifeanyi55** [gradio-app/gradio#2085]
Hello,

I really want to first of all laud the awesome work you have done and are continuing to do with gradio. I have built a gradio interface for an image classification model before, but the build fails when I try to do the same for an object-detection model. My code is shown below:

```
from transformer import pipeline
import gradio as gr
model = pipeline("object-detection")
gr.Interface.from_pipeline(model).launch(share = True)
```
I even tried to wrap the code in a function, and use `gr.Interface(fn)` but the build still fails. It appears gradio doesn't yet support Huggingface's object-detection model. I thought I should bring this to your attention. Again, kudos for the very good work you are doing with gradio!

**Comment by abidlabs** [comment]
Hi @Ifeanyi55 thanks for bringing this to our attention. You're right, we should support this pipeline!

In the short term, we could wrap the object-detection pipeline into an image-to-image Interface. 

In the longer run, we might want to make dedicated object-detection/image-segmentation component.

cc @aliabid94 as this could lead to some nice popular demos!

**Comment by abidlabs** [comment]
This is now possible to implement because we have an `AnnotatedImage` component. However, we still need to convert the outputs of the object-detection pipeline in `transformers` to something that the `AnnotatedImage` component can take. 

This would be a great issue for a contributor who knows Python and transformers!

**Comment by abidlabs** [comment]
Relevant part of the codebase: https://github.com/gradio-app/gradio/blob/87f1c2b4ac7c685c43477215fa5b96b6cbeffa05/gradio/pipelines.py#L14

**Comment by debnath003** [comment]
Can you please assign this one for me? I am new to the open source contribution! @abidlabs  @Ifeanyi55

**Comment by venkatavamsidama** [comment]
@abidlabs @Ifeanyi55  i want to work on this issue , can u plz assign it to me

**Comment by abidlabs** [comment]
Hi @debnath003 @venkatavamsidama thanks for your interest! We don't formally assign issues to contributors. Feel free to open a PR for any open issue that does not have an existing PR and we are happy to review.

**Comment by cswamy** [comment]
Wanted to work on this idea but struggling to get the environment working in a VS Code dev container. What is the best place to ask for help?

**Comment by freddyaboulton** [comment]
The huggingface discord's "#gradio" channel is a good place to ask support questions @cswamy !
