### ISSUE TITLE
Skops integration

### ISSUE THREAD

**Issue by merveenoyan** [gradio-app/gradio#2090]
I would like a huggingface transformers-like integration for gradio where you can call the model from the Hub and build an interface in one line of code, like below:

`interface = gr.Interface.load("huggingface/scikit-learn/tabular-playground")`

What I have in mind is dataframe component in, dataframe component out UI.

Wanted to open discussion for requirements to have this and what to do (might be cool if you could somehow put links on to-do's for previous transformers integration). @freddyaboulton @abidlabs (might be interested)

The UI looks like this: https://huggingface.co/spaces/scikit-learn/tabular-playground (dataframe in, dataframe out)
However, I couldn't manage to pass examples like we used to do as list of lists, where in each inner list is a row (an example) I opened an issue (#2089 ).

We can automatically receive headers and example inputs from `config.json` files of skops repositories and construct dataframe component by passing those.

Also pinging @adrinjalali and @BenjaminBossan here.

**Comment by freddyaboulton** [comment]
Hey @merveenoyan thanks for filing!

We already have an issue open for this here! https://github.com/gradio-app/gradio/issues/2015 I'm going to close this out so we can consolidate discussion.

We don't have an official guide for how to integrate with the hub but the existing integrations are implemented in `external.py`. Are you planning on working on this? If so, assign yourself on #2015 !
