### ISSUE TITLE
Add add ability to add captions to image in a Gallery 

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#2091]
We have a feature request to be able to display some sort of label/caption for each image in a Gallery. Specifically the request is to: "display numbers in a gr.Gallery, to label images? e.g. in my [space](https://huggingface.co/spaces/sasha/PromptBook), I would like to have numbers alongside the grid to help people flag them"

I think this is a good idea as it takes on the most common use case of the `Carousel` component, which was to display images and text together, and we can properly deprecate that component.

**Comment by hwasiti** [comment]
This is a great addition to the gallery component. 
Can you consider adding an argument to make the labels visible/invisible? In some use cases it would be better to not cover the images with the labels and only show the label below the image when clicked and enlarged.
