### ISSUE TITLE
Disable progress animation

### ISSUE THREAD

**Issue by mjpost** [gradio-app/gradio#2093]
I am trying to write an app that provides streaming updates to a text box (real-time speech recognition). This results in a lot of flicker, since the progress animation shows at each update—often, multiple times per second. This effect can also be seen in your own demo on [this page](https://gradio.app/blocks_and_event_listeners/) (second example), where the event listener updates the output textbox every time the name is changed.

Is there a way to disable this progress animation?

I've looked all over for a solution to this problem, but can't find one anywhere.

**Comment by abidlabs** [comment]
Good point, @aliabid94 do you know if this is possible? You disabled the progress animation for streaming IIRC

**Comment by mjpost** [comment]
I understand if you can't support this internally (though I suspect others would like this, as well)—but can you advise how I might turn this off manually? It's unfortunately a deal-breaker for my use case...

**Comment by aliabid94** [comment]
The `show_progress` parameter of any event listener can be set to false to hide the progress. e.g. `btn.click(fn, input, out, show_progress=False)`

However in streaming, the progress animation is always hidden. E.g.

```
import gradio as gr
import time, random

def dummy(a):
    time.sleep(2)
    return str(random.randint(1,100))

with gr.Blocks() as demo:
    mic = gr.Audio(source="microphone")
    text = gr.Textbox()
    mic.stream(dummy, mic, text)

demo.launch()
```

^ this should not show any progress animation for you. What gradio version are you using?

**Comment by mjpost** [comment]
We're using 3.1.7, but were trying to use `gr.Interface` with text boxes (where `show_progress=False` flags fail). Thank you very much!

**Comment by aliabid94** [comment]
Can you share a skeleton of your Interface code? Even in Interface, when `streaming=True`, the animation should be hidden.

**Comment by mjpost** [comment]
We weren't using `streaming=True`. The demo is akin to your simple "Hello X" app I linked to above:

```python
import sys
import gradio as gr

from mtapi import get_translation

def display(text):
    return get_translation(text, target_lang="de")

gr.Interface(
    allow_flagging='never',
    fn=display, 
    inputs=[
        gr.Textbox(label="Input", interactive=True)
    ],
    outputs=[
        gr.Textbox(label="Output")
        
    ],
    live=True).launch()
```

If the latency of `display` is something above say 100ms, there is a lot of flicker.

**Comment by abidlabs** [comment]
Hi @mjpost sorry there was some confusion because we use "streaming" to mean something other than `live=True`. In your case, you could use this hack to disable the flicker:


```py
import time
import gradio as gr

def display(text):
    time.sleep(.1)
    return text

io = gr.Interface(
    allow_flagging='never',
    fn=display, 
    inputs=[ gr.Textbox(label="Input", interactive=True) ],
    outputs=[ gr.Textbox(label="Output") ],
    live=True)

io.dependencies[0]["show_progress"] = False

io.launch()
```

**Comment by dawoodkhan82** [comment]
Now `demo.dependencies[0]["show_progress"] = "hidden"` should work to solve this!

**Comment by MagdalenaPolacPXL** [comment]
It seems that the `dependencies` member variable was removed in `gradio@4.28.0` :(
