### ISSUE TITLE
Labels disappear when interpretation is clicked

### ISSUE THREAD

**Issue by nasskall** [gradio-app/gradio#2098]
### Describe the bug

Although the slider's label is visible at the beginning before changing values on slider and remains visible when values are changed to perform a classification task, when  I use the property intepretation="default" in the predict function the label of the slider is not shown on the html page

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr
import os
import pickle
import pandas as pd
import numpy as np

root_dir = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
root_dir = os.path.join(root_dir, 'saved_models')

slide_dictionary = {
    'Body temperature': {'minimum': 20, 'maximum': 42, 'value': 36, 'step': 0.1, 'parameter': 'temperature'},
    'Weight': {'minimum': 10, 'maximum': 200, 'value': 80, 'step': 1, 'parameter': 'weight'},
    'Diastolic pressure': {'minimum': 20, 'maximum': 180, 'value': 80, 'step': 10, 'parameter': 'diastolic'},
    'Systolic pressure': {'minimum': 40, 'maximum': 250, 'value': 120, 'step': 10, 'parameter': 'systolic'},
    'Age': {'minimum': 4, 'maximum': 105, 'value': 50, 'step': 1, 'parameter': 'age'},
    'SPO2': {'minimum': 70, 'maximum': 99, 'value': 98, 'step': 1, 'parameter': 'spo2'},
    'Hypertension': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1, 'parameter': 'pressure'},
    'Dosage': {'minimum': 0, 'maximum': 3, 'value': 0, 'step': 1, 'parameter': 'dosage'},
    'Days from last dose': {'minimum': 0, 'maximum': 500, 'value': 0, 'step': 1, 'parameter': 'last_dosage'},
    'Ill before': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1,
                                                 'parameter': 'ill_before'},
    'Hyperlipidemia': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1, 'parameter': 'lipidemia'},
    'COPD': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1, 'parameter': 'cpd'},
    'Heartrate': {'minimum': 65, 'maximum': 170, 'value': 85, 'step': 1, 'parameter': 'heartrate'},
    'Gender': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1, 'parameter': 'gender'},
    'Diabetes': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1, 'parameter': 'diabetes'},
    'Coronary': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1, 'parameter': 'coronary'},
    'Drugs': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1, 'parameter': 'drugs'},
    'Asthma': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1, 'parameter': 'asthma'},
    'Smoking': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1, 'parameter': 'smoking'},
    'Hepatitis': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1, 'parameter': 'hepatitis'},
    'Liver failure': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1, 'parameter': 'liver_failure'},
    'CKD': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1, 'parameter': 'ckd'},
    'AstraZeneca (Vaxzevria)': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1, 'parameter': 'astrazeneca'},
    'Johnson and Johnson': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1, 'parameter': 'jnj'},
    'Moderna': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1, 'parameter': 'moderna'},
    'Pfizer-BioNTech (COMIRNATY)': {'minimum': 0, 'maximum': 1, 'value': 0, 'step': 1, 'parameter': 'pfizer'}
}

def show_sliders(features, dah):
    # load the model from disk
    filename = os.path.join(root_dir, 'finalized_model' + str(dah) + '.sav')
    loaded_model = pickle.load(open(filename, 'rb'))

    def predict_patient(feature1=None, feature2=None, feature3=None, feature4=None,
                        feature5=None, feature6=None, feature7=None, feature8=None,
                        feature9=None, feature10=None, feature11=None, feature12=None,
                        feature13=None, feature14=None, feature15=None, feature16=None,
                        feature17=None, feature18=None, feature19=None, feature20=None,
                        feature21=None, feature22=None, feature23=None, feature24=None,
                        feature25=None, feature26=None, feature27=None, feature28=None):
        feature_dict = {}
        features_names = [feature1, feature2, feature3, feature4,
                          feature5, feature6, feature7, feature8,
                          feature9, feature10, feature11, feature12,
                          feature13, feature14, feature15, feature16,
                          feature17, feature18, feature19, feature20,
                          feature21, feature22, feature23, feature24,
                          feature25, feature26, feature27, feature28]
        for m in range(len(features)):
            feature_dict[sliders[m].label] = [features_names[m]]
        df = pd.DataFrame.from_dict(feature_dict)
        predict = loaded_model.predict_proba(df)[0]
        return {'MRC degree:' + str(loaded_model.classes_[i] + 1): predict[i].astype(np.float64) for i in range(2)}

    sliders = []
    variables = []
    for j, i in enumerate(features):
        sliders.append(
            gr.components.Slider(minimum=slide_dictionary.get(i)['minimum'], maximum=slide_dictionary.get(i)['maximum'],
                                 step=slide_dictionary.get(i)['step'], value=slide_dictionary.get(i)['value'], label=i))
        dynamic_variable = slide_dictionary.get(i)['parameter']
        variables.append(dynamic_variable)
        globals()[dynamic_variable] = sliders[j]

    gr.Interface(predict_patient, sliders, "label",
                 live=True, allow_flagging="never", interpretation="default").launch(debug=True)

### Screenshot

<img width="775" alt="Untitled1" src="https://user-images.githubusercontent.com/58705380/187033849-8c6ea98e-1c42-4175-84d0-bacfdf31a72d.png">
<img width="774" alt="Untitled2" src="https://user-images.githubusercontent.com/58705380/187033851-e3aa3ad5-1304-488d-b5c2-359a48640d5b.png">
<img width="762" alt="untitled3" src="https://user-images.githubusercontent.com/58705380/187033853-1c1c8864-9ad6-454c-ba71-a6b4c75430b5.png">
<img width="762" alt="untitled3" src="https://user-images.githubusercontent.com/58705380/187033863-1ff9bbdf-296f-4538-b113-608b4862476a.png">

### Logs

```shell
-
```

### System Info

```shell
3.1.5, Windows 10, All browsers
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks for the issue @nasskall! We'll look into this. @freddyaboulton maybe we can add to the DS milestone?
