### ISSUE TITLE
In Examples Component, if fn is provided and cache_examples=False, fn is never run

### ISSUE THREAD

**Issue by ankrgyl** [gradio-app/gradio#2101]
### Describe the bug

Reading the [docs](https://gradio.app/docs/#examples), I'd expect that if `cache_examples=False`, but `fn` is provided, then if the example is selected, the outputs are populated. However, this appears to only occur if `cache_examples=True`. Looking at the code, I believe this is caused by the fact that the `fn()` is called _only_ when there is a cache miss.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

This is a simplified version of the example from the docs. If you set `cache_examples=True`, then the "Output" is populated each time you click on an example. If you set `cache_examples=False`, then "Output" is not populated each time you click an example.

```
import gradio as gr
import os


def combine(a, b):
    return a + " " + b


def mirror(x):
    return x


with gr.Blocks() as demo:

    txt = gr.Textbox(label="Input", lines=2)
    txt_2 = gr.Textbox(label="Input 2")
    txt_3 = gr.Textbox(value="", label="Output")
    btn = gr.Button(value="Submit")
    btn.click(combine, inputs=[txt, txt_2], outputs=[txt_3])

    gr.Markdown("## Text Examples")
    gr.Examples(
        [["hi", "Adam"], ["hello", "Eve"]],
        [txt, txt_2],
        txt_3,
        combine,
        cache_examples=False,
    )

if __name__ == "__main__":
    demo.launch()
```

### Logs

```shell
N/A
```

### System Info

```shell
>>> gr.__version__
'3.1.7'
```
```


### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Interesting point. So just to make sure I understand clearly, your current workflow (with example caching disabled) is:

1. Click on a dataset example
2. Click the button to run the function
3. See the prediction in the output component

But you'd prefer to just:

1. Click on a dataset example to run the function
2. See the prediction in the output component

We can probably support this via an additional parameter (`attach_click` or something) in `Examples`.

**Comment by ankrgyl** [comment]
Yes that's right! I am working on a use case where I can't cache, but do want the auto updating behavior. As a new user (so please excuse my ignorance) I got confused that the behavior of the app changed based on my preference to cache or not.

**Comment by abidlabs** [comment]
Makes sense, thanks for confirming. And glad to have you as a user :)

Please keep the feedback coming!

**Comment by ankrgyl** [comment]
Very happy to! I appreciate your response.
