### ISSUE TITLE
Allow frontend method execution on Block.load event

### ISSUE THREAD

**Issue by codedealer** [gradio-app/gradio#2105]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
`Blocks.load()` instance method allows to run an arbitrary function upon loading the app but unlike every other event it does not allow `_js` argument to execute a js script on load which would be useful for instantiating classes that can be utilized later by other js callbacks in other events (like click, change and so on). This is despite the fact that [set_event_trigger](https://github.com/gradio-app/gradio/blob/4f0b8f9829e10f0fce44d8c66cb13e17a5e48100/gradio/blocks.py#L106) allows for js to be passed but [it is never passed down](https://github.com/gradio-app/gradio/blob/4f0b8f9829e10f0fce44d8c66cb13e17a5e48100/gradio/blocks.py#L781).

**Describe the solution you'd like**  
Change the signature of the `load` method similar to other events to allow _js argument
```
def load(
        self_or_cls,
        fn: Optional[Callable] = None,
        inputs: Optional[List[Component]] = None,
        outputs: Optional[List[Component]] = None,
        *,
        name: Optional[str] = None,
        src: Optional[str] = None,
        api_key: Optional[str] = None,
        alias: Optional[str] = None,
        _js: Optional[str] = None,
        **kwargs,
    )
```
Pass it down to `set_event_trigger`
```
self_or_cls.set_event_trigger(
                event_name="load", fn=fn, inputs=inputs, outputs=outputs, no_target=True, js=_js
            )
```

**Comment by abidlabs** [comment]
Thank you @codedealer! This makes a lot of sense. Would you be interested in opening a PR?

**Comment by codedealer** [comment]
Sure.

**Comment by krrishdholakia** [comment]
@abidlabs how do i trigger this on block load (not when a function is triggered but on initial block load)? i don't see this in documentation/examples - any help here would be appreciated.
