### ISSUE TITLE
 'Blocks' object has no attribute 'show_error' when running with "gradio app.py"

### ISSUE THREAD

**Issue by ankrgyl** [gradio-app/gradio#2106]
### Describe the bug

If something errors out in a block, it crashes trying to access `show_error` (which I believe exists on the `Interface` object).

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr
import os


def mirror(x):
    return x / 0


with gr.Blocks() as demo:
    txt = gr.Textbox(label="Input", lines=2)
    txt.change(mirror, txt, txt)

if __name__ == "__main__":
    demo.launch()
```

And then type anything in the box

### Logs

```shell
N/A
```

### System Info

```shell
>>> gradio.__version__
'3.1.7'
```
```


### Severity

annoying

**Comment by abidlabs** [comment]
I can't seem to reproduce this @ankrgyl. I only see the actual error itself, not the "'Blocks' object has no attribute 'show_error'" message you are describing. 

See here for colab notebook: https://colab.research.google.com/drive/1IfTH2y3-7EqgsBCz9BhjAvV2o4DWm9qI?usp=sharing

Note that in the colab, I added `debug=True` to print the errors in the colab notebook.

**Comment by ankrgyl** [comment]
Ah -- I see what the issue is. Locally, I was running the app with `gradio app.py`. If I run it with `python app.py`, I see the same "ERROR" block in the UI that shows in your repro.

**Comment by abidlabs** [comment]
Oh very interesting. Will investigate!

**Comment by freddyaboulton** [comment]
The issue is that `show_error` is defined in the `launch` method but reload mode doesn't call `launch`. 

The quick fix would be to define `show_error` on init but this may point at a redesign of reload mode so that functionality set in the `launch` method can be used in reload mode.
