### ISSUE TITLE
Gradio does not run locally

### ISSUE THREAD

**Issue by piegu** [gradio-app/gradio#211]
Hi,

I did install successfully gradio through `pip install gradio`.
Then, I ran the https://gradio.app/getting_started code.

But the 127.0.0.1 connection was not accepted.

Check this link to see a screen shot of the problem: https://github.com/piegu/language-models/blob/master/gradio.png

It looks like the tensorboard problem: https://stackoverflow.com/questions/40106949/unable-to-open-tensorboard-in-browser

**Comment by aliabid94** [comment]
Can you please expand on this?

**Comment by piegu** [comment]
Hello @aliabid94.
Sorry, I was too fast. I added informations about my problem. 
What do you think?

**Comment by aliabid94** [comment]
Hmm can you provide your operating system, gradio python version, and also try launching from outside a notebook?

**Comment by piegu** [comment]
Hello,
I found the solution. 

By default, the `server name` is got by `server_name=networking.LOCALHOST_NAME` in https://github.com/gradio-app/gradio/blob/master/gradio/interface.py#L71

In my case, it found `127.0.0.1` but as it did not work, I had to setup the `server_name` argument with its alias.

Instead of :
`iface = gr.Interface(fn=greet, inputs="text", outputs="text")`

I ran:
`iface = gr.Interface(fn=greet, inputs="text", outputs="text", server_name=my_alias_server_name)`

And it worked :-)

**Comment by aliabid94** [comment]
Glad to see you resolved this :)
