### ISSUE TITLE
PNG files aren't displayed while uploading

### ISSUE THREAD

**Issue by bottledmind** [gradio-app/gradio#2110]
### Describe the bug

PNG images aren't in All Supported Types, so, they aren't displayed by default. Have to look for them among non-image files with All Files option. No issues with processing, just uploading

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr
import numpy as np

def sepia(input_img):
    sepia_filter = np.array([
        [0.393, 0.769, 0.189],
        [0.349, 0.686, 0.168],
        [0.272, 0.534, 0.131]
    ])
    sepia_img = input_img.dot(sepia_filter.T)
    sepia_img /= sepia_img.max()
    return sepia_img

demo = gr.Interface(sepia, "image", "image")
demo.launch()

### Screenshot

Sorry for a photo, but for some reason ubuntu does not let me take a screenshot while this drop-down list is active  

![photo_2022-08-29_12-59-02](https://user-images.githubusercontent.com/60937565/187176762-1da43f67-256c-446d-b47a-1942421b5db7.jpg)

### Logs

```shell
No errors
```

### System Info

```shell
gradio-3.1.7
Ubuntu 20.04.4 LTS
Firefox
```

### Severity

serious, but I can work around it

**Comment by Ttl** [comment]
I have the same issue on Firefox on Ubuntu but Chrome works. The issue seems to be that "image/x-png" MIME type is not recognized. Changing it to "image/png" fixes the problem.

**Comment by aliabid94** [comment]
interesting, will take a look!

**Comment by thomas0809** [comment]
Similar issue here. On a MacBook, I cannot upload a PNG file. Dragging the PNG to the box is fine, though.
<img width="721" alt="image" src="https://user-images.githubusercontent.com/11373553/201383284-42075e81-b279-4a64-8140-0d1c44640fc9.png">
