### ISSUE TITLE
Colab hosted GradIO doesnt receive output and hangs if process is longer then 60 seconds

### ISSUE THREAD

**Issue by XmYx** [gradio-app/gradio#2111]
### Describe the bug

Using Colab - Stable Diffusion, gradio wont receive any output, and freeze up in browser (fine after reload, but output not returned)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://colab.research.google.com/drive/1cd35l21ewU0fwWEnPjY_th5YORmMfZCd?usp=sharing

or

https://colab.research.google.com/drive/1KeNq05lji7p-WDS2BL-86Z8Y9SluGng4

all using

https://github.com/hlky/stable-diffusion-webui

### Logs

```shell
will update, but no error received
```

### System Info

```shell
3.1.4, 3.1.6, 3.1.8b3

Colab

using environment.yaml from git repo above
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @XmYx yes this is a limitation with http requests. You can overcome this by enabling the queue. Here's how to do it in the latest version of Gradio: https://gradio.app/key_features/#queuing

**Comment by abidlabs** [comment]
Let me know if this works! We will soon enable queue by default so this should no longer be a problem (#2081)

**Comment by XmYx** [comment]
Yes, I have tried, with concurrency 1, 2, and 3, but in either case, gradio ui reports the loading bars, but no input is received by the server.

**Comment by XmYx** [comment]
Indeed, also got 

WebSocket connection to 'wss://xxxxx.gradio.app/queue/join' failed: 
(anonymous) @ index.eed6f04f.js:7785

: )

**Comment by abidlabs** [comment]
This should be fixed now @XmYx! Here's a colab that shows queuing + iterative outputs: https://colab.research.google.com/drive/1kBfWpPUAZ5EOvl9P4RR9EiqCT35urtQM?usp=sharing
