### ISSUE TITLE
Can't embed multiple spaces on the same page if spaces use different queue implementation

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2114]
### Describe the bug

Suppose you are trying to load two spaces on the same page, but one has gradio 3.1.3 (old queue) but one is 3.1.7 (new queue). 

If you load the 3.1.3 module, niether will work but not the 3.1.7 space. 

If you load the 3.1.7 module, the 3.1.3 space will not work

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Owl-Vit is a 3.1.3 gradio app, the other is 3.1.7

```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<script type="module"
src="https://gradio.s3-us-west-2.amazonaws.com/3.1.3/gradio.js">
</script>
<gradio-app space="adirik/OWL-ViT"></gradio-app>
<gradio-app space="gradio/xgboost-income-prediction-with-explainability"></gradio-app>
</body>
</html>
```

Open in your browser

### Loading 3.1.3 module

The Owl-Vit app is unresponsive (clicking examples does nothing. Can't upload an image).

![image](https://user-images.githubusercontent.com/41651716/187254580-42be7539-2617-4d59-bfc1-a87055563f32.png)

### Loading 3.1.7 module
The Owl Vit app will successfully load an example but can't do a prediction of a non-example input. The 3.1.7 app works

![image](https://user-images.githubusercontent.com/41651716/187255017-faccdf94-eebb-4c95-a6b2-17cd7d3f33e4.png)

### Logs

```shell
Loading the 3.1.3 module
POST https://hf.space/embed/gradio/xgboost-income-prediction-with-explainability/+/api/queue/push/ 404

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'scroll_to_output')
    at set_status (index.9ab970ad.js:6607:49)
    at $$self.$$.update (index.9ab970ad.js:6687:4)
    at update (index.9ab970ad.js:606:12)
    at flush (index.9ab970ad.js:577:13)


Loading the 3.1.7 module
WebSocket connection to 'wss://users/freddy/sources/scratch/embedding.html/queue/join'
```

### System Info

```shell
-
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Is this a solvable issue @pngwn @aliabid94? My understanding is that you can only import one version of the Gradio JS on a page, and that has to match the version of the Space that you are trying to embed.

**Comment by aliabid94** [comment]
hmm yeah, we don't support multiple versions of gradio in a page, because they both target the same elements. but we should have some sort of autodetection when loading from spaces, and using the correct js version for that space.

**Comment by abidlabs** [comment]
Should we close this issue? I don't think we can support multiple versions at the moment (and afaik users haven't asked for this)

**Comment by abidlabs** [comment]
Closing, feel free to reopen if you guys feel strongly otherwise
