### ISSUE TITLE
"HuggingFace" theme/mode

### ISSUE THREAD

**Issue by ankrgyl** [gradio-app/gradio#2116]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

When I publish my app to HuggingFace, it looks different than it does locally. Most notably there's the theme (dark locally and light on huggingface). I have searched around and see some references to a theme feature, and that it perhaps has been removed, but I haven't been able to get it to work locally.

**Describe the solution you'd like**  
Ideally something like `theme=huggingface` would reproduce what I see on the huggingface space that I publish to.

**Additional context**

**Comment by ankrgyl** [comment]
Looking around, I think this might be because my system settings are "dark" which Gradio respects locally but HuggingFace does not?

**Comment by freddyaboulton** [comment]
@ankrgyl Yea I think that's right. Right now, there is only one built-in theme that changes based on light vs dark mode but theming is an open issue. See #1488

**Comment by abidlabs** [comment]
Yes I've encountered this too @ankrgyl. Are there any other differences that you see?

**Comment by ankrgyl** [comment]
Not really. I discovered `?__theme=light` in the meantime and it looks pretty close to me.

**Comment by ankrgyl** [comment]
I will keep an eye out and post here if I see anything else though!

**Comment by abidlabs** [comment]
Sounds good, closing this issue in the meantime. Feel free to reopen if you find any bugs
