### ISSUE TITLE
Ability to pass elem_id to Examples

### ISSUE THREAD

**Issue by ankrgyl** [gradio-app/gradio#2117]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

I'm trying to write custom CSS for an examples gallery, but unlike other components, it does not accept an `elem_id` argument.

**Describe the solution you'd like**  
Ideally, I could pass in `elem_id` like I can with other components.

**Additional context**  
I'm able to work around this by just using the `gr-samples-table` class, so it's not urgent or blocking by any means.

**Comment by abidlabs** [comment]
Should be an easy fix, we'll get it in soon, thanks for the heads up @ankrgyl!

**Comment by ankrgyl** [comment]
Happy to post this as a separate issue, but kind of related, it'd be useful for our use case to be able to "scope" multiple components' CSS. E.g. pass an `elem_id` into `gr.Row()` and `gr.Column()`. Apologies as always if I'm missing something obvious!

**Comment by abidlabs** [comment]
It will be possible to apply CSS to `gr.Row()` and `gr.Column()` soon via #2097. Thanks!

**Comment by abidlabs** [comment]
Closing as #2097 has been merged in!

**Comment by abidlabs** [comment]
(and should be out on pypi in a day or two)
