### ISSUE TITLE
How to launch Gradio with a local Hugging Face model?

### ISSUE THREAD

**Issue by piegu** [gradio-app/gradio#212]
Hello,

I read the article [Using & Mixing Hugging Face Models with Gradio 2.0](https://huggingface.co/blog/gradio) that explains how to display in one line a Hugging Face (HF) model from the [HF model hub](https://huggingface.co/models) (ie, through API). 

Great but how to do the same thing with a Hugging Face model stored locally (ie, through a local path)?

(for example, a HF model for QA that I have finetuned on my server but did not upload to the HF model hub)

**Comment by abidlabs** [comment]
@piegu wrap a Python function around your Hugging Face model and then pass that that into the Gradio Interface class. The examples here should help: https://gradio.app/ml_examples
