### ISSUE TITLE
equal_height referenced in the docs but appears to be deprecated

### ISSUE THREAD

**Issue by ankrgyl** [gradio-app/gradio#2120]
### Describe the bug

This is not at all blocking, but I figured I'd post because I got a bit confused as a new user. The docs mention the `equal_height` parameter [here](https://gradio.app/controlling_layout/). But when I ran the app locally, I got a message that it's deprecated. If so, it'd be helpful to new users to remove it.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Simply add `equal_height=True` to a `gr.Row()` and run the app (happy to put together something more detailed if needed).

### Logs

```shell
venv/lib/python3.10/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'equal_height': True}
  warnings.warn(
```
```


### System Info

```shell
gradio>>> gradio.__version__
'3.1.7'
```
```


### Severity

annoying

**Comment by ankrgyl** [comment]
Similarly, `scale` is referenced for `Column` but does not seem to work ([link](https://gradio.app/docs/#button)):

```
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ankur/projects/transformers/spaces/docquery-redesign/./app.py", line 182, in <module>
    with gr.Column(scale=5):
TypeError: Column.__init__() got an unexpected keyword argument 'scale'
```

**Comment by naba89** [comment]
Well, this issue is still there on version 3.4.1

**Comment by abidlabs** [comment]
Thanks @naba89 you're right, these haven't been removed from the docs yet. @aliabid94 can you please update the docs to show how to do this properly now?
