### ISSUE TITLE
cmd + K doesn't work on lower resolutions of the docs site

### ISSUE THREAD

**Issue by altryne** [gradio-app/gradio#2121]
https://www.gradio.app/docs/interface

It's very helpful that you included cmd+k to search quick documentation, however, when using side by side in split mode with my actual code/website, the window is quite small for me, and the sidebar is not accessible nor does cmd+K works

**Describe the solution you'd like**  
cmd+k should work as a global shortcut thorughout the website, regardless of resolution or location (like on tailwind docs for example) 

**Additional context**  
Low priority but useful

**Comment by aliabd** [comment]
Thanks for the feedback @altryne we'll work on this

**Comment by DoBestMan** [comment]
Hi @aliabd, Shall I work on this issue? I noticed that you assigned it to yourself a while ago, but it's still open. Please let me know what you think.
