### ISSUE TITLE
Scheduled tasks and triggers

### ISSUE THREAD

**Issue by tt0203** [gradio-app/gradio#2122]
How to let gradio to implement timed execution of program script in huggingface?
For example, I want to send the model running results at 9 a.m. every day.

**Comment by abidlabs** [comment]
Hi @tt0203, just to be clear:

1. You currently have a demo running on Hugging Face Spaces
2. You want to query the model with an input every day at 9 AM and get the results?

If that's what you mean, you can write a script locally which uses a timer to make a post request to your Space's API (click the "view API" button at the bottom of your Gradio demo to see the API) and get the results.

**Comment by tt0203** [comment]
Is there any way to actively push the calculation results at the server?
For example, the server regularly sends the model calculation results to the designated mailbox.
It is still inconvenient on the local computer. It can only be realized when the local computer is turned on and running.

**Comment by abidlabs** [comment]
Got it. I think in theory it would be possible to keep a loop running when you click the submit button, and inside the loop, you would be able to check the time, perform a calculation, and then send a result. A code skeleton would be:

```py
def loop(x):
  while True:
     if some_condition_based_on_time: 
        perform_calculation()
        email_results()

gr.Interface(loop, "text", "text").launch()
```

However, the Spaces machines occasionally go down or are restarted, so this is not a foolproof method. I'll close this issue since this is out of scope of the Gradio library.

**Comment by abidlabs** [comment]
@tt0203 just FYI you may also want to track #2050 in case its helpful for your use case

**Comment by freddyaboulton** [comment]
@tt0203 We just released a guide on scheduling tasks from your gradio app

https://gradio.app/running_background_tasks/

**Comment by alx** [comment]
https://www.gradio.app/guides/running-background-tasks

@freddyaboulton url is 404, here is the correct link
