### ISSUE TITLE
When specifying examples with a filepath + csv file, the front-end can't display the example images

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2129]
### Describe the bug

When specifying examples with a filepath + csv file, the front-end can't display the example images.

The reason is that in the csv file, the paths are relative to the `image_log` directory. 

You could specify a full path in the csv file but the implementation of `Examples` [assumes](https://github.com/gradio-app/gradio/blob/main/gradio/examples.py#L171) the paths are relative. Some discussion about this [here](https://github.com/gradio-app/gradio/pull/1952#issuecomment-1207092844)

Basically, it seems the log directory must be in the same directory as the demo, which is confusing and not documented as far as I can tell.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Make the following demos to the `image_mod` demo

```python
import gradio as gr
import os


def image_mod(image):
    return image.rotate(45)


demo = gr.Interface(image_mod, gr.Image(type="pil"), "image",
                    flagging_options=["blurry", "incorrect", "other"],
                    examples=os.path.join(os.path.dirname(__file__), "../../test/test_files/images_log"))

if __name__ == "__main__":
    demo.launch()
```

### Screenshot

![image](https://user-images.githubusercontent.com/41651716/187537665-4adecd30-7dcb-4a40-a54c-a01ad8245b82.png)

### Logs

```shell
raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path /Users/freddy/sources/gradio/im/bus_copy.png does not exist.
```

### System Info

```shell
main
```

### Severity

serious, but I can work around it

**Comment by sachit-menon** [comment]
Hi, any update on this? It is doable but a bit of a pain to have to list every item in the directory individually every time.

**Comment by abidlabs** [comment]
This issue got buried @sachit-menon, but I'll take a look this week! Thanks for the reminder

**Comment by sachit-menon** [comment]
Thanks!
