### ISSUE TITLE
Edit options not appearing

### ISSUE THREAD

**Issue by tiwari93** [gradio-app/gradio#213]
Gradio seems to run perfectly till last week. But when I ran today, edit option, as well as screenshot option was not available. I tried running locally and on colab also but same issue. I tried changing gr.interface option manually for these too no success. Please help me on this.
![Capture](https://user-images.githubusercontent.com/49356997/120805401-64e38a80-c563-11eb-8004-b8829140e966.JPG)

**Comment by aliabid94** [comment]
Let me take a look to fix this. Meanwhile, you can try installing a version of gradio < 2.0.0, (such as  1.7.7) if you'd like to use the older version.

**Comment by tiwari93** [comment]
Thanks for the quick response. Many thanks for ur awesome work

**Comment by aliabid94** [comment]
Fixed as of 2.0.10. Let us know if you have any other issues.
