### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'State'

### ISSUE THREAD

**Issue by oconnoob** [gradio-app/gradio#2130]
### Describe the bug

When trying to use the `gr.State()` block, an error is thrown saying that no such attribute exists.

This must be a recent bug because a while ago the [hangman example in the quickstart](https://gradio.app/state_in_blocks/#session-state) was working fine but it does not seem to be any longer. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio

with gr.Blocks() as demo:
    s = gr.State()
```

### Logs

```shell
Traceback (most recent call last):
  File "C:\<FILEPATH>\app.py", line 99, in <module>
    gr.State([])
AttributeError: module 'gradio' has no attribute 'State'

Process finished with exit code 1
```

### System Info

```shell
Gradio Version 3.1.7
Win11
Chrome, Edge, Colab
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Ah this is a problem because the demos are using the latest version of Gradio on `main`, not the latest released version. This will be fixed when we release `gradio==3.2` today or tomorrow!

**Comment by abidlabs** [comment]
In the meantime, please replace `gr.State()` with `gr.Variable()` and it should work fine

**Comment by oconnoob** [comment]
Great, thanks for the quick response!
