### ISSUE TITLE
Variable's state leaked between sessions

### ISSUE THREAD

**Issue by ankrgyl** [gradio-app/gradio#2132]
### Describe the bug

We've observed that when our app is hosted on HuggingFace, a `gradio.Variable()` value is somehow getting leaked across sessions. My assumption is that a `Varaible()` is supposed to be isolated within a session.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

[Here](https://huggingface.co/spaces/impira/docquery/blob/67ef8151d95765a3ae43b37540f64fa26efb3ab8/app.py) is the code, the variable in question is `document`. When run locally, it's fine, but on huggingface spaces, state is bleeding across sessions.

This video walks through the repro, and shows the difference between the same code running locally vs. hosted on HF Spaces: https://www.loom.com/share/d820fb46fce24a4b9dcc6676fc4f0ab2. Feel free to play with the space here: https://huggingface.co/spaces/impira/docquery.

### Logs

```shell
N/A
```

### System Info

```shell
3.1.7 (running on HuggingFace Spaces)
```

### Severity

blocking all usage of gradio

**Comment by ankrgyl** [comment]
To clarify -- although I recorded this with two browser windows on the same machine, we observed this across two different users at Impira testing our space.

**Comment by abidlabs** [comment]
@ankrgyl thanks for raising this issue! A very strange and problematic bug, we'll look into it and figure out what's happening

**Comment by freddyaboulton** [comment]
@ankrgyl out of curiosity, can you try launching with enable_queue=False and see if the problem persists?

**Comment by ankrgyl** [comment]
Yes I'll try that now (it's rebuilding).

In the meantime, looking at the network tab, I noticed that this is the request that is sent (and ultimately generates the bad result).
<img width="573" alt="Screen Shot 2022-08-30 at 5 52 24 PM" src="https://user-images.githubusercontent.com/565363/187569230-f99357c7-77a2-4bb1-ae1c-f2505a9ffa30.png">

That middle `null` is suspiciously the `document` variable in the `inputs` for the task:

```
336     question.submit(
337         fn=process_question,
338         inputs=[question, document, model],
339         outputs=[image, output, output_text],
340     )
```

Just sharing in case it's a useful clue...

**Comment by ankrgyl** [comment]
That seems to have broken it completely (on hugging face, not locally): https://www.loom.com/share/6fa87104cf214069895b48ebf2a6f01e.

There appears to be something broken with Spaces right now, which I filed separately here: https://github.com/huggingface/transformers/issues/18826.

**Comment by ankrgyl** [comment]
The logs on the space have a lot of this:

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 248, in run_predict
    output = await app.blocks.process_api(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 641, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 545, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ankrgyl** [comment]
Oh cool. I tried the opposite of what you suggested -- setting `enable_queue=True` locally -- and confirmed that it now reproduces for me locally.

**Comment by freddyaboulton** [comment]
Yea must be something with the queue, which is enabled by default on spaces but not locally. Not sure what's up with https://github.com/huggingface/transformers/issues/18826 , I would try factory reboot of the space to see if that fixes it.

**Comment by ankrgyl** [comment]
Unfortunately that did not fix it.

**Comment by ankrgyl** [comment]
I was able to make a really simple repro:

```
$ cat app2.py
import gradio as gr

with gr.Blocks() as demo:
    document = gr.Variable()
    a = gr.Textbox()
    b = gr.Button()
    o = gr.Textbox()

    a.change(lambda x: x, inputs=[a], outputs=[document])
    b.click(lambda x: x + " foo", inputs=[document], outputs=[o])

if __name__ == "__main__":
    demo.launch(enable_queue=True)
```

If you run it with `python app2.py`, you'll observe the same behavior. Here's a video:

https://www.loom.com/share/60061b4dd79c48b8acaec34a47736bfc

**Comment by ankrgyl** [comment]
I took a look at the code and it looks like the `session_hash` is not being communicated from the client code to the backend in "queue" mode. I'm not an expert in the code, but I think the problem is here:

https://github.com/gradio-app/gradio/blob/main/ui/packages/app/src/api.ts#L146

```
144         switch (data.msg) {
145           case "send_data":
146             send_message(fn_index, payload);
147             break;
```

Specifically -- I think `send_message` needs to include the `session_hash`, so that the websocket can forward it along in `gradio/event_queue.py:process_event`.

**Comment by ankrgyl** [comment]
I'm sure there's a better fix than this, but I confirmed that the following fixes it for me locally:

```
ankur-m1:~/projects/gradio ankur$ git diff
diff --git a/ui/packages/app/src/api.ts b/ui/packages/app/src/api.ts
index d56e3da1..ad91229d 100644
--- a/ui/packages/app/src/api.ts
+++ b/ui/packages/app/src/api.ts
@@ -104,6 +104,7 @@ export const fn =
                        );

                        function send_message(fn: number, data: any) {
+                               data['session_hash'] = session_hash;
                                ws_map.get(fn).connection.send(JSON.stringify(data));
                        }
                        var ws_endpoint = api_endpoint === "api/" ? location.href : api_endpoint;
```

Part of the problem is that on the backend, the following code will always return true, because the `body` has an attribute named `session_hash`, even if it's `None`. The underlying problem is that (without the above patch), no session hash is passed to the server, and this code thinks the (missing) session hash is `None`. So every web browser session ends up "sharing" the `None` session.

```
232         async def run_predict(
233             body: PredictBody, username: str = Depends(get_current_user)
234         ):
235             if hasattr(body, "session_hash"):
236                 if body.session_hash not in app.state_holder:
237                     app.state_holder[body.session_hash] = {
238                         _id: deepcopy(getattr(block, "value", None))
239                         for _id, block in app.blocks.blocks.items()
240                         if getattr(block, "stateful", False)
241                     }
242                 session_state = app.state_holder[body.session_hash]
243             else:
```

**Comment by abidlabs** [comment]
Thank you for the detailed analysis @ankrgyl. Looking into this now and will try to get it fixed soon!

**Comment by brianfitzgerald** [comment]
I am still experiencing this on gradio 3.3, which you can see [here](https://huggingface.co/spaces/roborovski/Diffusle). Should this be fixed in master? Or is the fix still upcoming?

**Comment by abidlabs** [comment]
Hi Brian, it looks like this Space is running Gradio 3.2 as can be seen by
the sdk_version parameter here:
https://huggingface.co/spaces/roborovski/Diffusle/blob/main/README.md

If you update this to 3.3, it should work! But let us know if it does not
for any reason

**Comment by brianfitzgerald** [comment]
Thanks so much! I will bump the SDK version and see if that helps, I imagine it will.
