### ISSUE TITLE
Gallery is slow when images have different sizes

### ISSUE THREAD

**Issue by hwasiti** [gradio-app/gradio#2134]
When showing 9 images of the same size (let's say the same image) it would take ~1sec to show the grid of images. however, if the images are with different sizes it will take too much time to render them (~10sec). 

Is this normal? Where is the performance bottleneck exactly?

**Comment by freddyaboulton** [comment]
Hi @hwasiti ! Can you please share a reproducible code snippet?

**Comment by hwasiti** [comment]
Hey @freddyaboulton 
Turned out the upload speed of my own server is slow for the task. My home internet is 100/10 Mbit/s. So for a total of 20MB for the 9 images download of the images will take a while.
Closing...
