### ISSUE TITLE
When caching the output of a file component in examples, the filename is not respected

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2140]
### Describe the bug

Run Model3D with cache examples - you can do it with the version hosted on spaces here: https://huggingface.co/spaces/gradio-pr-deploys/pr-2128-all-demos

Click on an example and download the resulting file, you will see that the downloaded file does not have a complete name, e.g. `_home_user_app_gradio_cached_e (2)`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Stated above^

### Screenshot

![model_3d_download](https://user-images.githubusercontent.com/41651716/187721503-98fad3d1-6551-4491-9e0e-a42e1d08d5d4.gif)

### Logs

```shell
-
```

### System Info

```shell
-
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Out of curiosity, can you try right clicking "open link in a new tab" when you click on the "Download" link?

**Comment by freddyaboulton** [comment]
Interesting - then the file is just called `Download`. Just tried it on the space

**Comment by freddyaboulton** [comment]
At first I thought it had to do with the name of the file being too long - but I think it's reading from the example cache. Locally I modified `zip_two_files` to return a really long file name and the file name (and extension) was respected.

**Comment by abidlabs** [comment]
Getting the same behavior, very strange

**Comment by freddyaboulton** [comment]
Think I figured it out - it's the slashes in the file name when reading from the cache. I think we just need to make the file serializer add the `orig_name` field with the file name as opposed to the full path. Will put up a PR soon.
