### ISSUE TITLE
3.2 changes layout/sizes for components from previous versions

### ISSUE THREAD

**Issue by AK391** [gradio-app/gradio#2152]
### Describe the bug

observed in https://huggingface.co/spaces/PaddlePaddle/ERNIE-ViLG spaces the button component is now larger in 3.2 than in 3.1.7 after updating 
<img width="645" alt="Screen Shot 2022-08-31 at 11 58 08 PM" src="https://user-images.githubusercontent.com/81195143/187828675-181c6e8c-dc03-4633-b4b0-0dc90553d496.png">

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

see https://huggingface.co/spaces/PaddlePaddle/ERNIE-ViLG

### Logs

```shell
https://huggingface.co/spaces/PaddlePaddle/ERNIE-ViLG/logs/container
```

### System Info

```shell
Spaces
```

### Severity

annoying

**Comment by abidlabs** [comment]
Fixed now due to #2291, thanks for reporting @AK391!
