### ISSUE TITLE
Dropdown default not displaying and HTML not rendering (3.1.7 -> 3.2)

### ISSUE THREAD

**Issue by oconnoob** [gradio-app/gradio#2153]
### Describe the bug

I recently upgraded from gradio 3.1.7 to 3.2 in order to use the `Tab()` block component that was not working with 3.1.7.

After upgrading, an HTML element that is set visible/invisible with a button click is not rendering (although some space is made in the layout for it), and the default `value` for a `Dropdown()` is not showing up.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

[Repo link](https://github.com/AssemblyAI-Examples/audio-intelligence-dashboard.git)

### Logs

```shell
N/A
```

### System Info

```shell
Win11, Gradio 3.2, Edge/Chrome
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
@oconnoob This sounds like the same problem as #2154 and #2156 if the issue is caused by the `update` method on HTML component.

**Comment by pngwn** [comment]
Closing as duplicate of the issues mentioned above.
