### ISSUE TITLE
3.2's gr.update(visible=X) causes value to be reset

### ISSUE THREAD

**Issue by AUTOMATIC1111** [gradio-app/gradio#2154]
### Describe the bug

Every time I use gr.update(visible=X) on an element, its value becomes nothing. sliders get reset to zero, gr.Radio elements lose selection, ...

Here's how elements look in 3.2 after they are shown (they are invisible initially, and are shown when SD Upscale option is picked)  
![firefox_Ws0SSiTDv8](https://user-images.githubusercontent.com/20920490/187983431-ea61ea52-c115-457d-be45-fbca9aa39053.png)

Here's same with gradio downgraded to 3.1.5:
![firefox_49CiIPMs9c](https://user-images.githubusercontent.com/20920490/187983618-9aa7d3f0-ce00-438c-a324-7e8f413136e5.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://github.com/AUTOMATIC1111/stable-diffusion-webui

### Screenshot

see description

Also here is js error log for below
![firefox_CFKKtTSH6f](https://user-images.githubusercontent.com/20920490/187984064-835ef545-1a83-4a2f-8518-21fe46a406f2.png)

### Logs

```shell
no errors in python

same unrelated errors in javascript for both versions
```

### System Info

```shell
3.2 gradio, Windows 10, Firefox and Chrome
```

### Severity

blocking upgrade to latest gradio version

**Comment by freddyaboulton** [comment]
Hi @AUTOMATIC1111 Thanks for filing the bug.

I think I know what's happening. While we get a fix out, can you try the following workaround? Instead of using gr.update, return a dict with `{"visible": True, "__type__": "update"}` 

```python
import gradio as gr

with gr.Blocks() as demo:
    radio = gr.Radio(label="algorithm", choices=["a", "b", "c"], value="a")
    slider = gr.Slider(label="threshold", value=0, minimum=-1, maximum=1, visible=False, interactive=True)
    style = gr.Dropdown(label="style", choices=["modern", "classical", "cartoon"], value="modern", visible=False, interactive=True)

    def make_visible(algorithm):
        is_visible = algorithm == "c"
        return {slider: {"visible":is_visible, "__type__": "update"}, style: {"visible":is_visible, "__type__": "update"}}
    radio.change(make_visible, inputs=radio, outputs=[slider, style])

demo.launch()
```

**Comment by AUTOMATIC1111** [comment]
The workaround works, thanks.

**Comment by williamberrios** [comment]
Hi @freddyaboulton. Regarding your previous example, it seems that the demo is not working properly when you only output slider.
`import gradio as gr
with gr.Blocks() as demo:
    radio = gr.Radio(label="algorithm", choices=["a", "b", "c"], value="a")
    slider = gr.Slider(label="threshold", value=0, minimum=-1, maximum=1, visible=False, interactive=True)

    def make_visible(algorithm):
        is_visible = algorithm == "c"
        return {slider: {"visible":is_visible, "__type__": "update"}}
    radio.change(make_visible, inputs=radio, outputs=[slider])

demo.launch()`

**Comment by williamberrios** [comment]
``import gradio as gr

with gr.Blocks() as demo:
    radio = gr.Radio(label="algorithm", choices=["a", "b", "c"], value="a")
    slider = gr.Slider(label="threshold", value=0, minimum=-1, maximum=1, visible=False, interactive=True)

    def make_visible(algorithm):
        is_visible = algorithm == "c"
        return {slider: {"visible":is_visible, "__type__": "update"}}
    radio.change(make_visible, inputs=radio, outputs=[slider])

demo.launch(share = True)``
