### ISSUE TITLE
Auth not set when using reload mode

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2158]
### Describe the bug

When using reload mode, any of the features that you configure in the `launch` method will not be respected, including auth, queue, show_error.

That's expected because reload mode doesn't call the launch method but this may be confusing to users and maybe calls for a redesign of how reload mode works. 

I don't think this is a high priority issue though.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr
import os


def identity(x):
    return x[::-1]


with gr.Blocks() as demo:
    txt = gr.Textbox(label="Input", lines=2)
    output = gr.Textbox(label="Output", lines=2)
    txt.change(identity, txt, output)

if __name__ == "__main__":
    demo.launch(auth=[("admin", "admin")])
```

### Screenshot

![reload_mode_auth](https://user-images.githubusercontent.com/41651716/188007893-13957b1d-87d8-4444-8ccb-cb163d524b16.gif)

### Logs

```shell
-
```

### System Info

```shell
3.2
```

### Severity

annoying

**Comment by ErwannMillon** [comment]
Also, queues don't seem to work in reload mode 
ValueError("Need to enable queue to use generators.") when running `gradio app.py`
