### ISSUE TITLE
[Feature] Combine image and video components

### ISSUE THREAD

**Issue by AK391** [gradio-app/gradio#216]
would it be possible to combine the image and video components for input and output? I think it would be user friendly to not build separate interfaces for images and videos

**Comment by aliabid94** [comment]
I don't quite understand AK, can you explain?

**Comment by AK391** [comment]
@aliabid94 sure, so basically have one component (possibly image) that can handle both images and video, video would be treated as a sequence of images

**Comment by abidlabs** [comment]
Given the structure of the input components, I think this is best realized by including both image and video as 2 optional input components. Closing, but feel free to open @AK391 if you feel strongly otherwise.

**Comment by jhj0517** [comment]
Hi, thanks for all your work! 
I have a use case where my function looks like this:

```
def handle_media(media_file):
    if is_image(media_file):
        pass
    elif is_video(media_file):
        pass
```

Currently, my workaround is to place both the component and the write wrapper function for gradio:

```
def handle_media_gradio(image_file,
                        video_file):
    if image_file is not None:
        handle_media(image_file)
    elif video_file is not None:
        handle_media(video_file)
```

I'm not sure if this use case is common or not, but if such a component exists,
I wouldn't need to write another function for such a use case and would allow more separation between frontend and backend.
