### ISSUE TITLE
Potential BUG in video output (cannot pause)

### ISSUE THREAD

**Issue by MultiPath** [gradio-app/gradio#2172]
### Describe the bug

When using the latest gradio (3.2) to output video, it is not possible to pause the video. Whenever I click the pause button, the video will return to the start. I checked version 3.1 is ok

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr
import numpy as np
import imageio, tempfile


def example(video1, video2):
    fd, path =tempfile.mkstemp(suffix = '.mp4')
    with imageio.get_reader(video1) as v1, imageio.get_reader(video2) as v2, imageio.get_writer(path, fps=20) as writer:
        for img1, img2 in zip(v1, v2):
            img = np.concatenate([img1, img2], 1)
            writer.append_data(img)
    return path

demo = gr.Interface(fn=example, inputs=["video", "video"], outputs="video")
demo.launch()
```

### Logs

```shell
no log
```

### System Info

```shell
macos 13.0
python 3.9
Successfully installed gradio-3.2
```

### Severity

blocking upgrade to latest gradio version

**Comment by freddyaboulton** [comment]
I can reproduce with an even simpler demo:

```python
import gradio as gr


def example(video1):
    return video1

demo = gr.Interface(fn=example, inputs=["video"], outputs="video")
demo.launch()
```

In gradio 3.1.7 I can pause the video. The one difference I can think of between 3.1.7 and 3.2 is that before the front-end was serving base64 representation of the Video and now it's serving a file from the file system.  @aliabid94 @pngwn @dawoodkhan82 Could that be the reason? FYI @abidlabs

**Comment by abidlabs** [comment]
Very strange! Yeah the base64 versus the filepath must be responsible. @aliabid94 do you know why a file data source might not be pause-able?

**Comment by dawoodkhan82** [comment]
Not sure why this is happening, but I can take a look

**Comment by Warvito** [comment]
Not sure if this helps, but depending on the browser, I can pause the outputted video (with Gradio 3.3, on Firefox 103.0 (64-bit), the example from @freddyaboulton works, and on Google Chrome Version 103.0.5060.134, it doesn't work)

**Comment by dawoodkhan82** [comment]
After taking a look, seems like setting `currentTime` on an html video element on chrome doesn't work. But for some reasons works fine for a base64 source but not file path source. @pngwn 

more info: https://stackoverflow.com/questions/27964533/js-currenttime-for-html-video-tag-is-not-working-on-chrome
