### ISSUE TITLE
Package improperly includes test data and files

### ISSUE THREAD

**Issue by chris-morgan** [gradio-app/gradio#2183]
### Describe the bug

setup.py contains:

```python
    packages=["gradio", "gradio.test_data", "test.test_files"],
```

Because of this, installing gradio will give you modules `gradio.test_data` and `test.test_files`.

`test.test_files` should certainly not be included in the distribution under that path, and I don’t think either belong in the package at all.

You can start fixing this by removing their entries from `packages`:

```python
    packages=["gradio"],
```

… but this seems to still retain `gradio.test_data` (because of `include_package_data=True`, maybe), so you probably need to find some way of deliberately excluding it (I don’t know how off the top of my head; I’ve never done much in Python packaging).

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```console
$ curl -O https://files.pythonhosted.org/packages/c9/e6/805d819a7b25fcc104c5228103fc89991b21f6041103391f4922d370f540/gradio-3.2-py3-none-any.whl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5922k  100 5922k    0     0  1539k      0  0:00:03  0:00:03 --:--:-- 1539k

$ python -m wheel unpack gradio-3.2-py3-none-any.whl
Unpacking to: ./gradio-3.2...OK

$ ls gradio-3.2
gradio  gradio-3.2.dist-info  test

$ tree gradio-3.2
gradio-3.2
├── gradio
│   ├── __init__.py
│   ├── [… various more expected stuff omitted for brevity …]
│   ├── test_data
│   │   ├── __init__.py
│   │   ├── blocks_configs.py
│   │   ├── cheetah1.jpg
│   │   ├── cheetah2.jpg
│   │   ├── flagged_no_log
│   │   │   ├── a.txt
│   │   │   ├── b.txt
│   │   │   └── c.txt
│   │   ├── flagged_with_log
│   │   │   └── log.csv
│   │   ├── lion.jpg
│   │   ├── test_audio.wav
│   │   └── test_image.png
│   └── [… and more expected stuff omitted for brevity …]
├── gradio-3.2.dist-info
│   ├── LICENSE
│   ├── METADATA
│   ├── RECORD
│   ├── WHEEL
│   ├── entry_points.txt
│   └── top_level.txt
└── test
    └── test_files
        ├── Box.gltf
        ├── Fox.gltf
        ├── audio_sample.wav
        ├── bad_video_sample.mp4
        ├── bus.png
        ├── cheetah1.jpg
        ├── images
        │   ├── bus.png
        │   └── bus_copy.png
        ├── images_log
        │   ├── im
        │   │   ├── bus.png
        │   │   └── bus_copy.png
        │   └── log.csv
        ├── playable_but_bad_container.mkv
        ├── sample_file.pdf
        ├── test_label_json.json
        ├── video_sample.mp4
        ├── video_sample.ogg
        └── video_sample.webm

19 directories, 225 files
```

### Logs

```shell
N/A
```

### System Info

```shell
N/A
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @chris-morgan ! Some people actually depend on `test_data` being shipped to PyPi! (https://github.com/gradio-app/gradio/issues/1697) We used to not include it.

Going to close this.

**Comment by chris-morgan** [comment]
You’re misinterpreting #1697: it was saying that *if* you’re going to include `test.test_files`, it needs `gradio.test_data`—but did not judge whether `test.test_files` should be included or not. (“For completeness-sake, gradio should either include `gradio/test_data`, or omit `test` in its pypi releases.”)

I’m starting by saying that `test.test_files` is categorically wrong and should not be included under that name. You could move it to `gradio.test.test_files`, or you could scrap both together (which I think is the better course of action). But the status quo is, from a packaging conventions perspective, certainly a bug.
