### ISSUE TITLE
Audio examples not working in embeds

### ISSUE THREAD

**Issue by mustafalhamadsa** [gradio-app/gradio#2185]
### Describe the bug

Embed gradio does not play audio examples, as can be seen in https://tf2sa.com/music/AMM/ if you scroll down you would find an embed with that issue, given in huggingface spaces it works properly https://huggingface.co/spaces/TF2SA/AMM 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Make a gradio application, include an audio example, then embed the application.

```
<script type="module" src="https://gradio.s3-us-west-2.amazonaws.com/3.1.6/gradio.js"></script>
<gradio-app space="TF2SA/AMM"></gradio-app>
```

### Logs

```shell
None
```

### System Info

```shell
gradio==3.1.4
Edge
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
@mustafalhamadsa I believe the space is running gradio 3.2 (HF spaces will use the gradio version listed in the README not `requirements.txt`) and in your code snippet you're loading the 3.1.6 gradio javascript module. Can you make the versions  match and see if it fixes your problem?

**Comment by mustafalhamadsa** [comment]
Unfortunately even with both of them matched, the issue persisted.

![msedge_ZyvSEfwVl8](https://user-images.githubusercontent.com/100326225/188673511-397261c1-2588-4c94-a6dd-877f5939cee1.png)

![msedge_wTkjw7qmcw](https://user-images.githubusercontent.com/100326225/188673517-151a3d9e-dba2-4124-8072-002c5580f8a9.png)

**Comment by freddyaboulton** [comment]
And you set the version in the html to be 3.2?

```
<script type="module" src="https://gradio.s3-us-west-2.amazonaws.com/3.2/gradio.js"></script>
```

**Comment by mustafalhamadsa** [comment]
I never noticed the version in the html, that did the trick. thank you very much :)
