### ISSUE TITLE
Direct support for partial functions

### ISSUE THREAD

**Issue by Sreerag-ibtl** [gradio-app/gradio#2195]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Currently, partial functions can only be used when the object is patched with its __ name __ attribute. Support for partial functions enables one to use functions with more arguments than the number of input components specified.

**Describe the solution you'd like**  
I do not have a clear picture. But I found that [__ name __](https://github.com/gradio-app/gradio/blob/5360ea002ea79ca6016ff61842317f2227570015/gradio/interface.py#L291) is only available for function objects, not partial functions. Maybe that's the only blocking thing here.

**Additional context**  
I currently use a partial function by explicitly setting partial_function.__ name __.

**Comment by abidlabs** [comment]
Hi @Sreerag-ibtl can you please provide a full code example with partial functions so we can understand what you'd like to support?

**Comment by Sreerag-ibtl** [comment]
@abidlabs Here's a [colab](https://colab.research.google.com/drive/1Ilg-wRVcZKavM6uHicHvs2mMcxWUX8Tj?usp=sharing) notebook for your reference.
