### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zbw66** [gradio-app/gradio#2196]
### Describe the bug

If the input is a CSV file and the output is a CSV file as well, which component should I use if I want to display and save it to the specified path?    eg.Using Dataframe, you can only display but can not have  tips of save or download

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

...

### Logs

```shell
...
```

### System Info

```shell
ubuntu20.04
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @zbw66 ! 

You can output a separate `File` component that will let you download the csv file. Something like this should work

```python
demo = gr.Interface(
    fn=my_fn,
    inputs=gr.Dataframe(),
    outputs=[gr.Dataframe(), gr.File()],
)
```
