### ISSUE TITLE
unexpected network negotiations?

### ISSUE THREAD

**Issue by vseledkin** [gradio-app/gradio#22]
Simplest demo 

import gradio as gr
def greet(name):
  return "Hello " + name + "!"
gr.Interface(fn=greet, inputs="text", outputs="text").launch()

responds on submit button much faster if network connection is not available for app.
Why?

i. e. 
> python demo.py 
response time 1.26s

> sandbox-exec -f nonetwork.sb python demo.py
response time 0.014s

**Comment by dawoodkhan82** [comment]
This was because of analytics on usage of the interfaces being sent over the network. This has been moved to the background in the latest commit.
