### ISSUE TITLE
Can you realize the webcam in real time in the output component?

### ISSUE THREAD

**Issue by shliang0603** [gradio-app/gradio#220]
@abidlabs Hi, can you realize the webcam in real time in the output component? I think this feature is important for demonstration purposes. Thanks.

**Comment by abidlabs** [comment]
Thanks, we are working on this! Could you describe your use case a bit more? What kind of model are you demoing?

**Comment by abidlabs** [comment]
This is now possible with `gradio==3.0.2`. Please take a look at an example demo here: https://github.com/gradio-app/gradio/blob/main/demo/stream_frames/run.py
