### ISSUE TITLE
Replace `ValueError`s and other kinds of internal exceptions with `gr.Error()`s

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#2207]
We now support custom Gradio Errors (through the use of `gr.Error()`). These errors are much more prominent and have the advantage of being visible in colab notebooks even with `debug` not set to `True`. 

Should we replace all of the errors that Gradio can throw internally with such errors? For example, if a person tries to use a generator but does not have queue() enabled, they will see the following error: 

![image](https://user-images.githubusercontent.com/1778297/188999663-3099dc36-430c-4a55-ad49-7102bdae4ffe.png)

**Comment by abidlabs** [comment]
If a "queue full" error generates this kind of modal, then for consistency, we should do the same for "queue required for generator" and all of the other internal errors, yeah?

**Comment by aliabid94** [comment]
no, because "queue full" is a user facing error, not an internal error. It tells the user to try again.

**Comment by abidlabs** [comment]
Ah right, that makes sense! In that case, we can close this issue imo
