### ISSUE TITLE
max_rows/pagination does not seem to work

### ISSUE THREAD

**Issue by ankrgyl** [gradio-app/gradio#2209]
### Describe the bug

If you create a `DataFrame` with a certain number of `max_rows`, it still shows all of the original rows. I found https://github.com/gradio-app/gradio/issues/1201, which says they're not implemented, but both the code and documentation seem to suggest they are.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

with gr.Blocks() as demo:
    a = gr.DataFrame(headers=['a'], value=[[1]]*20, max_rows=1)

if __name__ == "__main__":
    demo.launch()
```

### Screenshot

![Screen Shot 2022-09-07 at 5 07 18 PM](https://user-images.githubusercontent.com/565363/189005893-f0dfe52d-2192-4316-bcb5-c035987dbbfe.png)

### Logs

```shell
N/A
```

### System Info

```shell
tried with 3.1.7 and 3.2
```

### Severity

serious, but I can work around it

**Comment by EmilyAlsentzer** [comment]
+1 I'm also experiencing this issue

**Comment by freddyaboulton** [comment]
@dawoodkhan82 Let's work together to fix this! 

@EmilyAlsentzer @ankrgyl Thanks for reporting - we'll try to get a fix out soon 😄

**Comment by arielgamino** [comment]
Experiencing the same. Hope this gets implemented as max_rows and overflow_row_behaviour don't seem to be working as indicated in docs.

Here are my examples https://colab.research.google.com/drive/1gQDcFd-nUx4iZrhew_HGFGq6_cV32OnJ?usp=sharing

**Comment by freddyaboulton** [comment]
Thanks for letting us know @arielgamino !

**Comment by GuillemGSubies** [comment]
Any updates here?

**Comment by HennethAnnun** [comment]
Would be great to have this fixed. Best wishes!

**Comment by saikrishna-punna** [comment]
is this not fixed yet? Is there a workaround?

**Comment by ltm920716** [comment]
hi @freddyaboulton,

Is there any plan to fix this problem for 'max_rows'?  Or add a 'overflow_col_behaviour' parameter？

Thanks！

**Comment by shon-cf** [comment]
is there any workaround meanwhile?

**Comment by tommasodelorenzo** [comment]
Interested as well. Any update?

**Comment by ronsamuel84629** [comment]
How can developers put something in documentation that is not working as stated. So much disappointing. Time to switch to streamlit or javascript framework

**Comment by hungngo32** [comment]
how can I get pandas dataframe from gr.Dataframe

**Comment by arian81** [comment]
@abidlabs I see that it has been removed from the milestone, is this issue fixed if not which release is it going to be fixed in ?

**Comment by abidlabs** [comment]
We discussed internally and there are a few things we need to consider to get the best pagination experience for `gr.Dataframe` (for example, does it load all the data to the frontend or does it lazy load the data? If lazy loading, how do other features like sorting work)? As a result, we've decided to put this off for now. We'll revisit in a few weeks.

**Comment by alfaki** [comment]
Thanks for the update! Is there a work around? Maybe by fixing the block length with scrolling similar to left and right scrolling and load all data

**Comment by abidlabs** [comment]
Instead of `max_rows` (which has now been marked as deprecated), we've implemented a `height` parameter (by default, 500 pixels) which provides similar functionality. The Dataframe has been virtualized, meaning it should be much, much faster with large datasets.
