### ISSUE TITLE
Have separate queues and ETAs for each event

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#2216]
Right now, all events are added to the same queue. However, a single Blocks might have some events that are much faster than others. Instead of queuing them in one queue, we should have separate queues for different events (we would need to have some mechanism for how to delegate workers to different queues). We should also then have separate ETAs for each queue.

**Comment by abidlabs** [comment]
I'm planning on implementing this using [Fair-share scheduling](https://en.wikipedia.org/wiki/Fair-share_scheduling), which means that the workers will basically rotate between events in a round-robin fashion, spending roughly an equal time on each event. 

So let's say there are 3 events: A, B, C. The `rotation_time` parameter (which is a single parameter for the entire Queue object) defines how long the workers spend on each event.

So let's say the queue looks like this: A, B, A, A, B, C, B, A, C, A, B and for simplicity assume one worker, and assume `rotation_time` is 5 seconds (a reasonable default I think). Let's say event A takes 0.5 seconds to compute (e.g. a "clear button" or some other quick event) event B takes 2 seconds (e.g. like a "flag" button), and event C takes 15 seconds (e.g. like an image generation). 

1. The worker will start by working on event A, complete that in 0.5 seconds, and then will proceed to the next event A, complete that in 0.5 seconds, and then eventually complete all of the event A's.
2. Then the worker will move to event B, complete that in 2 seconds, move to the next event B, then the next event B. After 3 event B's, then the worker will notice that more than 5 seconds have elapsed, and then 
3. Move to event C, and will complete that in 15 seconds. Since more than 5 seconds have elapsed, the worker will
4. Move back to event A. If no new event A's have arrived, the worker will move to event B

... and so on

If there are multiple workers, then each worker will independently proceed in this fashion.

**Comment by FarukOzderim** [comment]
This looks great ideally but I am not sure this is really needed in Gradio.

1. This will make Queue design more complex. I am not sure how easy it will be to context-switch in Python scope, and how efficient it'll be. And it will probably take a significant time to develop this feature.
2. Long duration events will have quite a lot of trouble finishing when there is a high traffic.
3. The queue location will not be respected like before.

Due to these reasons, I think it could be better to provide these 2 options instead.
1. Letting events bypass the queue(this is already supported, might need more documentation and marketing)
2. Allocating special thread slots to events, a thread that will just serve to a single event. (OS already does scheduling between threads and this will move the complexity to the OS instead of Gradio. Honestly, It feels unnecessary to implement a scheduling in Gradio when OS already schedules the threads.

**Comment by abidlabs** [comment]
Great to hear your feedback @FarukOzderim! I was actually thinking through this myself, and I came to the same conclusion. I don't think this will provide significant benefits that are worth the additional complexity of having separate queues for separate events (beyond letting events skip the queue altogether). 

I'll keep this issue open in case we do need it for #2218, but if it is possible to implement batching with a single queue, then will close this issue.

**Comment by fffiloni** [comment]
Yes ! This is a great idea, i was wondering if this was possible crafting my Whisper To Diffusion demo.

As i give the user the choice to check whisper outputs before sending it to SD, they are waiting too long for the previous client to finish their stable diffusion inference

you can experience it there: [Whisper to Stable Diffusion demo](https://huggingface.co/spaces/fffiloni/whisper-to-stable-diffusion)

**Comment by abidlabs** [comment]
@fffiloni I certainly see your point, but at this time, I think this would add too much complexity to the queue (and as it turns out, it is not needed for #2218), so I'm inclined to close the issue. My suggesiton would be to do the following instead:

* If your app has 2 kinds of events, one very fast and one very slow, simply skip the queue for the first event (by setting `queue=False` in the event handler)
* If your app has a "medium"-length event where skipping the queue may not be feasible, then a workaround would be to create a separate Space for your "medium"-length event. You can then call this Space in your main Space by using `gr.Interface.load()`, and thanks to #2294, the downstream app will respect the queue in the upstream app

**Comment by fxmarty** [comment]
Hello @abidlabs ,

Could you explicit

> If your app has 2 kinds of events, one very fast and one very slow, simply skip the queue for the first event (by setting queue=False in the event handler)

? I'm trying to have different queues for different buttons, but I did not manage to do it yet (except having several Gradio demos on the same page)
