### ISSUE TITLE
Accordion closes automatically if you click a button in it

### ISSUE THREAD

**Issue by SkyTNT** [gradio-app/gradio#2219]
### Describe the bug

If a Button in a default closed Accordion has click event and you open the Accordion then click the Button, the Accordion will close automatically.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

if __name__ == '__main__':
    app = gr.Blocks()

    with app:
        text = gr.TextArea()
        with gr.Accordion("Test", open=False):
            btn = gr.Button()
        btn.click(lambda x: x+"test", [text], [text])
    app.launch()
```

### Logs

```shell
no logs
```

### System Info

```shell
gradio3.3
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks @SkyTNT, confirming I can reproduce this issue. @aliabid94 would you be able to take a look?

**Comment by aliabid94** [comment]
oh yikes, will take a look!
