### ISSUE TITLE
function is not working inside gradio

### ISSUE THREAD

**Issue by rahul-art** [gradio-app/gradio#222]
infer() function in this code is working fine outside gradio but not inside gradio
https://colab.research.google.com/drive/1TZtyF4qfhqLDwYMRRsufv48B-dh-ZI9z?usp=sharing

**Comment by aliabid94** [comment]
Taking a look.

**Comment by aliabid94** [comment]
How long does your function take? If it takes multiple minutes, it likely may be the result of a network timeout. We are working on a workaround for this.

**Comment by aliabid94** [comment]
Closing due to lack of response. Feel free to reopen.
