### ISSUE TITLE
Can you please add an Open source License ?

### ISSUE THREAD

**Issue by shaktisd** [gradio-app/gradio#223]
Can you please add an Open source License  under which people can use this software ?

**Comment by shaktisd** [comment]
![image](https://user-images.githubusercontent.com/2882134/122425457-201d1200-cfad-11eb-9b98-b6f255974333.png)

**Comment by aliabid94** [comment]
The apache license is visible here: https://github.com/gradio-app/gradio/blob/master/LICENSE

**Comment by shaktisd** [comment]
@aliabid94 , actually somehow it is not visible in pypi.org due to which third party 
Scanning tools reject it saying there is no license in the binary .  Example have a look at this on left side you can see BSD license . https://pypi.org/project/pandas/
