### ISSUE TITLE
Share a single Gradio port for all Gradio apps running on a single machine

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#2233]
Right now, when multiple Gradio apps are launched from a single machine, they all use separate ports (starting from port `7860` and increasing sequentially). This is resource-intensive if people launch multiple Gradio apps (especially if people are working in jupyter/colab notebooks where re-running cells is very common, and currently a new port is used for each Gradio instance).  

The idea here is to have a single Gradio port (by default `7860`) that all Gradio apps on a single instance use. Each Gradio app will have a landing URL in the form of `localhost:7860/<hash>`, and have its own API URL in the form of `localhost:7860/<hash>/api`. 

Advantages of this approach:
* Scalability: this will **reduce the number of connections that are made to our share servers**. The way `launch(share=True)` works is that SSH tunnel is created between a local port and a port on the Gradio API server. When someone is running e.g. a colab notebook, every time they rerun a cell, a new connection is made because a new local port is being used to run the Gradio app. This way, all Gradio apps from a single machine will utilize a single local port and a **single port on the Gradio API server**
* Easier frontend development: right now, an annoyance is that frontend web development port only works if the local app is running on port 7860. Based on this approach, all frontend apps will be running on port 7860
* Security through obfuscation: Shared Gradio app URLs will be harder to guess since they are not simply NUMBER.gradio.app, which could be useful when people don't want others to stumble upon their Gradio apps
* Consistency: many other programs that create local web servers also operate similarly (e.g. Spark): on a single port that support multiple apps  
* Speed: it should be faster to launch multiple Gradio apps since we don't need to launch new web servers each time.

**Comment by aliabid94** [comment]
I like it. Few questions.
- Does spark also use hashes to distinguish between multiple apps?
- When you relaunch an app, will you get the same hash?
- There is also the question of the frontend dev mode knowing the correct hash to connect to.
- didn't quite follow how this affects the share URL logic. if uou launch multiple apps, and only share=True some of them, is it easy to share just those endpoints?

**Comment by aliabid94** [comment]
Can you see other approaches that libraries have used? How does streamlit handle multiple apps?

>When you relaunch an app, will you get the same hash?
>> Not necessarily, do you think that this is important? Currently, you don't always get the same local port back when you relaunch a Gradio app (especially in jupyter notebooks when the old Gradio app never stops running)

This would be a real "nice to have", I was wondering with this refactoring if it would be easier to do this.

**Comment by abidlabs** [comment]
> Can you see other approaches that libraries have used? How does streamlit handle multiple apps?

Streamlit starts with 8501 and increments from there (8502, 8503). The closest analogue to what I'm proposing that I'm aware of is the jupyter notebook server, which runs on port 8888, but you can have multiple notebooks/kernels running simultaneously. They all just have different paths after the `localhost:8888/path_to_notebook1`, `localhost:8888/path_to_notebook2`, etc. 

>>> When you relaunch an app, will you get the same hash?

>> Not necessarily, do you think that this is important? Currently, you don't always get the same local port back when you relaunch a Gradio app (especially in jupyter notebooks when the old Gradio app never stops running)

> This would be a real "nice to have", I was wondering with this refactoring if it would be easier to do this.

I have an idea for how this could be implemented. Basically you would pre-generate a bunch of hashes and use them sequentially. When an app closes, it releases the hash, and if you were to relaunch, you could take the same hash as before.

**Comment by pngwn** [comment]
Would this have any implications for non localhost domains? For example would the share links become subpaths on a parent domain? Would it still be a single domain per machine just not per 'app'?

I guess my worry is if we end up with longer urls for everyone which may negatively impact UX.

**Comment by abidlabs** [comment]
Yes, so the share links would become subpaths, but the parent domain would be unique to a single machine. So it would be something like this.

1. You create your first Gradio app in a colab notebook: the URL is: `1234.gradio.app/3443dab`
2. You create your second Gradio app in a colab notebook: the URL is: `1234.gradio.app/f32dks3s`
3. You open a new colab notebook and run a Gradio app: the URL is: `32442.gradio.app/f32dks3s`

**Comment by pngwn** [comment]
I feel like I should put this here, although I don't really know how to articulate it but this feels off in general, like it feels like we're pushing our problems onto the user with confusing URLs and adding more complexity to our tooling to discover the correct 'hashes' for various apps.

Is it not possible to solve this at the infrastructure level? If this problem mostly manifests itself on colabs with many app then we could just have a special case for colab since the embedded app is the most important thing there, the longer URL wouldn't be much of an issue.

**Comment by dawoodkhan82** [comment]
What if 7860 port is taken by another application by chance. Should we still have the ability to increment to the next available port?

**Comment by abidlabs** [comment]
> Is it not possible to solve this at the infrastructure level? Alternatively, if this problem mostly manifests itself on colabs with many app then we could just have a special case for colab since the embedded app is the most important thing there, the longer URL wouldn't be much of an issue.

The fundamental problem in colab is that it *requires* setting up SSH tunnels (using `share=True`) because Colab does not allow us to access internal localhost ports. So the question is simply how do we create these tunnels in a scalable way now that our colab usage has gone way up? I think this change (running all Gradio apps from a single port) should have been how we did things from the start for all of the advantages mentioned earlier (not just the scalability problem), but there might be other solutions to this as well. And IMO the advantages outweigh the disadvantage of longer URLs, but again, open to other ideas?

> What if 7860 port is taken by another application by chance. Should we still have the ability to increment to the next available port?

Yes, we'll keep this feature

**Comment by aliabid94** [comment]
I have the same feeling as @pngwn that this seems to be adding complexity without solving core problems, and adding a new problem, which is knowing what URL your app will launch with. Going by bullet point of supposed advantages:

Scalability: Not solving the core issue. We should kill connections that are no longer being used to reduce load on the share server.
Easier frontend development: Not solving the core issue. We should immediately free up a port once a server is killed, the root problem is that gradio clings to port 7860 well after it's been killed for some reason. 
Security through obfuscation: On the other hand, we're exposing all gradio apps, even ones that aren't set to share=True
Consistency: Doesn't seem to be the case this is common.
Speed: What is the loading time of the webserver?

**Comment by abidlabs** [comment]
Ok that's fair, I think we can investigate other approaches to scaling up shared Gradio apps before pursuing this path.

**Comment by abidlabs** [comment]
After internal discussion, we've decided to pursue other ways to increase the capacity of our share servers. Thanks all for the feedback!
