### ISSUE TITLE
Lazy load images with `gr.Gallery` or `gr.Image`

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#2236]
**Is your feature request related to a problem? Please describe.**  
Currently if you use a lot of `gr.Gallery` or `gr.Image` components with the `value` filled in, the app pre-loads all images before actually loading the Gradio demo or application

![image](https://user-images.githubusercontent.com/788417/189625756-ec934c5c-0da6-4cbe-af49-66bdb21f6a4e.png)

**Describe the solution you'd like**  
Add a setting to allow for lazy loading the images when possible, e.g.:
`gr.Gallery(value=["https://a.co/1.jpg","https://a.co/2.jpg"], lazy=True)`. Maybe a way is using `loading="lazy"` to the HTML `<img>` tag or any other lazy loading method that make more sense for Gradio of course

**Comment by aliabid94** [comment]
Yesss, we need to do this for sure. Will take a look!

**Comment by TashaSkyUp** [comment]
add lazy loading to tabs as well?
