### ISSUE TITLE
Add license='Apache License 2.0 in setup.py

### ISSUE THREAD

**Issue by shaktisd** [gradio-app/gradio#224]
Looks like license key value is missing from setup.py due to which it is not visible in pypi.org
Add following bold marked line **license='Apache License 2.0',** in setup.py

packages=['gradio'],    
**license='Apache License 2.0',** # Add This Line
keywords=['machine learning', 'visualization', 'reproducibility'],

**Comment by aliabid94** [comment]
Done. Thank you!

**Comment by shaktisd** [comment]
Thanks @aliabid94 . LIcense is now visible on pypi.org
