### ISSUE TITLE
Numbers have collisions, need a bit more security

### ISSUE THREAD

**Issue by salamanders** [gradio-app/gradio#2255]
### Describe the bug

My redirect failed to start.  I didn't know this.  So when I loaded the https://17380.gradio.app link, I got someone else's app.

This feels sketchy, like it is too easy to try numbers at random.  Could it have some sort of checksum digits in the url so they can't be blind-guessed?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Start anything with share=True

### Logs

```shell
N/A
```

### System Info

```shell
ubuntu-server
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @salamanders thanks for creating this issue. Fully agree -- we'll work on improving this

**Comment by abidlabs** [comment]
Hi @salamanders we just pushed a change to how our links are generated so this issue should now be fixed across all versions of Gradio. I would appreciate if you can try it out and let us know if it works for you

**Comment by abidlabs** [comment]
Seems like everything is working so let me go ahead and close
