### ISSUE TITLE
local URL  cant open

### ISSUE THREAD

**Issue by zbw66** [gradio-app/gradio#2258]
### Describe the bug

cant Running on local URL,:ERR_CONNECTION_REFUSED

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

.launch()

### Logs

```shell
.
```

### System Info

```shell
gradio == 3.2
```

### Severity

annoying

**Comment by zbw66** [comment]
ps:codes are edited in Container. I try to use .launch(server_name='0.0.0.0',server_port=7888) but the local URL still cant running

**Comment by abidlabs** [comment]
Hi @zbw66, please provide a full code example so that we can reproduce this issue. Also, did you search the closed issues for "docker" as there are a number of people who have asked similar questions and have found solutions.

**Comment by zbw66** [comment]
Hi @abidlabs:
      thanks for your reply, this problem was solved ,the reason is probably that i tested in docker image,when i deleted server_port=7888( .launch(server_name='0.0.0.0')  ), the local URL can succwssful running, i dont know why,
      NOW ,i have a new problew,  when i  combine Gradio with Flask,  the setting of Network Port seems to conflict.How should the Net Port be set or what are they relationship

**Comment by abidlabs** [comment]
Hi @zbw66 without a full code example, we can't do much to help. I'll close this issue and point you this resource, which might help (though it's designed for fastapi, not flask): https://gradio.app/sharing_your_app/#mounting-within-another-fastapi-app
