### ISSUE TITLE
Trying the simple example on the website gets me error: No module named 'fsspec.asyn'

### ISSUE THREAD

**Issue by Zaniyar** [gradio-app/gradio#2268]
Hi, 
```

import gradio as gr
def sketch_recognition(img):
    pass

gr.Interface(fn=sketch_recognition, inputs="sketchpad", outputs="label").launch()

```

I installed gradio and fsspec; after running the script I get the error: 

 
> ...
>    import fsspec.asyn
> ModuleNotFoundError: No module named 'fsspec.asyn'

fsspec.asyn itself is not a module, and fsspec is installed.

**Comment by freddyaboulton** [comment]
@Zaniyar Can you try `pip install fsspec --upgrade` I'm on `2022.7.1` and gradio works for me.

**Comment by Zaniyar** [comment]
> @Zaniyar Can you try `pip install fsspec --upgrade` I'm on `2022.7.1` and gradio works for me.

ok with pip install it worked - conda install didn't work for me. thx
