### ISSUE TITLE
css not getting applied

### ISSUE THREAD

**Issue by erfanhamdi** [gradio-app/gradio#2270]
Hi 

I am trying to change the background color using CSS on gradio blocks but it doesn't change the output.
here is my code:
```python
import gradio as gr
from utils import inference_data_gen

def change_AR(shape):
    if shape == "rectangular":
        return gr.update(visible=True)
    else:
        return gr.update(visible=False)

with gr.Blocks(css="body {background-color: red} #shape {height: 92px}") as demo:
    with gr.Row():
        shape = gr.Radio(["rectangular", "circular", "triangular"], label="Shape", value="rectangular", elem_id="shape")
        out_file = gr.File(label = "Lift Data")
    with gr.Row():
        AR = gr.Number(1, label = "AR")
        Re = gr.Number(50, label = "Re")
        n_samples = gr.Number(value = 100, label = "Number of Samples")
    with gr.Row():
        kappa = gr.Slider(minimum = 0, maximum = 0.5, value = 0.2, label = "kappa")
    with gr.Row():
        submit_btn = gr.Button(label = "Submit")
    shape.change(fn = change_AR, inputs = shape, outputs = AR)
    submit_btn.click(fn = inference_data_gen, inputs = [shape, AR, Re, kappa, n_samples], outputs = [out_file])
```
There is another problem with setting height by elem_id to radio inputs too:
<img width="1340" alt="Screen Shot 2022-09-15 at 12 54 45 PM" src="https://user-images.githubusercontent.com/30288548/190354176-c36cf57d-3672-4929-8bfb-5a1dd105d8f4.png">

The background changes in Huggingface card but remains the same when I am trying to embed it on another webpage

**Comment by freddyaboulton** [comment]
@erfanhamdi Can you try setting `.gradio-container` instead?

There's a relevant discord discussion here: https://discord.com/channels/879548962464493619/1014577879121657896/1019329352741179444

And github discussion here: https://github.com/gradio-app/gradio/discussions/2202

**Comment by abidlabs** [comment]
We should update the documentation to reference the `.gradio-container`:
* here: https://gradio.app/key_features/#styling
* and here: https://gradio.app/custom_CSS_and_JS/

**Comment by erfanhamdi** [comment]
> @erfanhamdi Can you try setting `.gradio-container` instead?
> 
> There's a relevant discord discussion here: https://discord.com/channels/879548962464493619/1014577879121657896/1019329352741179444
> 
> And github discussion here: #2202

thanks that made it work

**Comment by freddyaboulton** [comment]
Great to hear @erfanhamdi !! As @abidlabs mentioned, we're going to update our docs since they don't reflect the correct way to apply css anymore. Thank you for helping us notice 😄

**Comment by freddyaboulton** [comment]
Submit a PR and we'd be happy to review 😄
