### ISSUE TITLE
Gradio Interface doesn't work in Kaggle

### ISSUE THREAD

**Issue by merveenoyan** [gradio-app/gradio#2272]
### Describe the bug

I don't know if it's a bug or if it's known but the interfaces I could previously load with Kaggle don't work anymore. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://www.kaggle.com/code/unofficialmerve/notebook91e833ce83

### Screenshot
(It says the port refuses to connect)
![Ekran Resmi 2022-09-15 17 17 13](https://user-images.githubusercontent.com/53175384/190442203-90e79d2a-930f-4d64-b2b2-4710062cc209.png)

### Logs

```shell
No logs despite I set debug=True
```

### System Info

```shell
python 3.7.12
gradio==3.3
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Can you try with `share=True` ?

**Comment by merveenoyan** [comment]
Thanks a lot, it works now!

**Comment by abidlabs** [comment]
@freddyaboulton maybe we can detect if we are running on Kaggle and set `share=True` automatically like we do in colab?

**Comment by freddyaboulton** [comment]
@abidlabs Absolutely! I thought the same
