### ISSUE TITLE
Add "Run in Colab" Links to demos on the website Demos Page

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2278]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
It would help transition gradio users into gradio developers if they could easily run the demos hosted on our website on colab.

**Describe the solution you'd like**  
Add `Run in Colab` links to all the demos on the website.

**Comment by aliabd** [comment]
Great suggestion @freddyaboulton, I'll also add these for the demos on Docs.
