### ISSUE TITLE
`concurrency_count` broke on 3.3	

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#2282]
### Describe the bug

`concurrency_count` is not working on version 3.3. It adds persons to the queue instead of executing the queue in parallel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Any execution with `concurrency_count` don't run in parallel on 3.3. It works on 3.1.7 and 3.2

### Logs

```shell
No logs
```

### System Info

```shell
3.3+
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Yikes, we'll take a look. Is there a Space you can point me to make reproducing faster?

**Comment by apolinario** [comment]
Because it is broken, I have not let it on any live Spaces, but I think you can reproduce very minimally by setting just taking any demo and adding the `concurrency_count`, the requests still run in sequence

I made a Space with a minimal demo just to exemplify: https://huggingface.co/spaces/multimodalart/saymyname

**Comment by freddyaboulton** [comment]
I think I know what the problem is. Thank you @apolinario!
