### ISSUE TITLE
CheckboxGroup as output ignores new choices

### ISSUE THREAD

**Issue by stevenhillis** [gradio-app/gradio#2285]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I have a CheckboxGroup. I instantiate it with four choices. Based on user interactions, I would like to add a fifth choice.

**Describe the solution you'd like**  
When a CheckboxGroup is acting as an output component, I would like the strings in the list it consumes which are not in the CheckboxGroup's choices to be added. 

**Additional context**  
The docs for CheckboxGroup say this:
As output: expects a {List[str]}, each element of which becomes a checked checkbox.
This is not true today; only elements already existing as choices become checked checkboxes. New elements are ignored. 

Minimal demo:
```
import gradio as gr
choices = ['One', 'Two', 'Three', 'Four']

def update_choices():
    return choices + ['Five']

def main():
    with gr.Blocks() as demo:
        cbg = gr.CheckboxGroup(choices=choices, value=[])
        button = gr.Button('Intended to check existing choices and add a new, checked choice')
        button.click(update_choices, inputs=[], outputs=[cbg])

    demo.launch()

if __name__ == '__main__':
    main()
```

**Comment by abidlabs** [comment]
Hi @stevenhillis thanks for creating this issue and providing the example. This is actually the same underlying issue as https://github.com/gradio-app/gradio/issues/1566. We will work on getting a fix for this!

**Comment by freddyaboulton** [comment]
Going to close this out as it's a duplicate!

**Comment by xvxieweilai** [comment]
import gradio as gr

choices = ['One', 'Two', 'Three', 'Four']


def update_choices():
    global choices
    if 'Five' not in choices:
        choices += ['Five']
    return gr.CheckboxGroup.update(choices=choices, value=choices)


def main():
    with gr.Blocks() as demo:
        cbg = gr.CheckboxGroup(choices=choices, value=[])
        button = gr.Button('Intended to check existing choices and add a new, checked choice')
        button.click(update_choices, inputs=[], outputs=[cbg])

    demo.launch()


if __name__ == '__main__':
    main()
