### ISSUE TITLE
images rotated

### ISSUE THREAD

**Issue by krrishdholakia** [gradio-app/gradio#2287]
### Describe the bug

When I upload an image on my iphone it gets rotated vs. uploading the same image on desktop. 

I assume this might have something to do with the iphone image upload being HEIC. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/krrishD/suitify_v1

### Logs

```shell
no debug output for this
```

### System Info

```shell
Using gradio on my iphone
```

### Severity

serious, I can't work around it

**Comment by abidlabs** [comment]
I've noticed this issue before, it seems to be a general problem with image uploading systems. @dawoodkhan82 would you be able to take a look at this?

**Comment by lsternlicht** [comment]
I only run into this issue when I select the "Take Photo or Video" option:
![image](https://user-images.githubusercontent.com/128432/194161130-ffbc72d8-82c6-4ff9-a05d-b900a5431972.png)

**Comment by freddyaboulton** [comment]
This doesn't happen to me when uploading via an image component

![IMG_90E4581EA15E-1](https://user-images.githubusercontent.com/41651716/214410239-ff7bdc11-3749-4010-b93e-ec6939684d36.jpeg)


But it does happen to me when using UploadButton + Chatbot in https://huggingface.co/spaces/ysharma/InstructPix2Pix_Chatbot

![IMG_4496](https://user-images.githubusercontent.com/41651716/214412808-57942eb3-62c0-495f-ac61-6e91bcff4891.jpg)

**Comment by lakshman111** [comment]
Reproduced here: https://www.loom.com/share/d62c8614873f4294b6169fa637976b97

This is the space I used in the loom (its public): https://huggingface.co/spaces/lakshman111/imageprocessingdebugging

The space just echos the user's image back to them, and it comes back horizontal when I used an iPhone and took a vertical image.

@freddyaboulton it looks like the issue isn't happening on upload, but rather happening during pre or post processing

**Comment by freddyaboulton** [comment]
@lakshman111 thanks for putting together a reproducer! It helped. I think I know the problem.

Can you try with this space? 

https://huggingface.co/spaces/freddyaboulton/imageprocessingdebugging

**Comment by lakshman111** [comment]
@freddyaboulton tried your space using both: "Take Photo" and "Photo Library" using a vertically taken photo and both no longer rotate the output (works as expected).  Thank you!

**Comment by lakshman111** [comment]
@freddyaboulton I'm trying to pull this fix into my project.  I can see that Pypi hasn't updated since Jan 30th (https://pypi.org/project/gradio/#history), and this issue was fixed on Jan 31st.  Do you know how/when this change will show up in Pypi?

**Comment by freddyaboulton** [comment]
Next release will probably be next week. 

I built a wheel from my PR and uploaded it here: https://gradio-builds.s3.amazonaws.com/image-rotate-fix/attempt-2/gradio-3.17.0-py3-none-any.whl

It's basically version 3.17.0 + the bugfix so hopefully that will work for you until we do the next release!

**Comment by 1049451037** [comment]
Same problem in gradio 4.x.

**Comment by freddyaboulton** [comment]
Going to take a look

**Comment by Theivaprakasham** [comment]
@freddyaboulton The issue is seen again now in version Gradio v5 (gradio==5.28.0, gradio_client==1.10.0). The images are rotated only when you upload bulk images with gr.File(file_types=["image"], file_count="multiple", label="Upload Images"). However, individual image upload is working correctly with gr.Image(type="pil", label="Upload Image").
