### ISSUE TITLE
h11 dependency clamped?

### ISSUE THREAD

**Issue by colemickens** [gradio-app/gradio#2289]
Hi,

Why is the h11 dependency clamped? We have h11 at v13 already and I'd prefer to not have to duplicate it just for this package if I can help it.

Thanks!

**Comment by abidlabs** [comment]
@aliabid94 do you know if this is still necessary to clamp?

**Comment by abidlabs** [comment]
Ok I checked, and it's clamped because `gradio` has `httpx` as a dependence, which has `httpcore` as a dependency, which itself requires "h11>=0.11,<0.13", see here: https://github.com/encode/httpcore/blob/master/setup.py

I'll close this issue, but let us know if we can help in any other way!

**Comment by theLastOfCats** [comment]
Looks like it fixed

https://github.com/encode/httpcore/commit/4cf288e0007cb73561b9020af9228f076ba2a94e
