### ISSUE TITLE
Error using Audio Interface  on Colab

### ISSUE THREAD

**Issue by harveenchadha** [gradio-app/gradio#229]
Hi,

I am trying to record voice from microphone on colab. But when I try to record this is what I am shown.

Screen:

<img width="1574" alt="Screenshot 2021-06-24 at 1 49 04 AM" src="https://user-images.githubusercontent.com/30959215/123162964-d5106c80-d48e-11eb-888a-9bc124b78ab0.png">

When I click on record:

<img width="1570" alt="Screenshot 2021-06-24 at 1 49 57 AM" src="https://user-images.githubusercontent.com/30959215/123162953-d2157c00-d48e-11eb-84c8-995c22e794e8.png">

I am shown a player with controls. When I click on submit a empty file is passed on to the model.

How to enable microphone on colab so that this whole setup runs smoothly?

**Comment by aliabid94** [comment]
Hey @harveenchadha can you click on the external link URL and see if the audio works there? It may be that colab is blocking permissions to the microphone.

**Comment by harveenchadha** [comment]
Hi,

The screenshots are from an external link URL only. If you can please pass on an example that works with microphone on colab , that would be helpful!

**Comment by aliabid94** [comment]
https://colab.research.google.com/drive/1ck92ZiiVuMb1pZoIY9YbmhAG0YDyMpx3?usp=sharing

**Comment by aliabid94** [comment]
Notice that it doesn't work in colab but does work in the external URL

**Comment by harveenchadha** [comment]
Doesn't works in external URL
<img width="1454" alt="Screenshot 2021-07-01 at 11 38 32 AM" src="https://user-images.githubusercontent.com/30959215/124074330-f65df380-da60-11eb-99f8-c01ded5c9257.png">

**Comment by aliabid94** [comment]
Interesting. Is it possible you've blocked microphone access? Can you see the console error logs (right-click -> inspector -> console) and paste the errors here?

**Comment by harveenchadha** [comment]
Microphone is already enabled. See this screenshot, mic is working for google translate in another tab.

<img width="1792" alt="Screenshot 2021-07-01 at 10 21 17 PM" src="https://user-images.githubusercontent.com/30959215/124161193-bdeb0380-daba-11eb-8654-58a52b193054.png">

**Comment by aliabid94** [comment]
Sorry for the late response - it seems like colab blocks iframe access to the microphone :/ You would have to click on the external URL to use the interface launched through Colab.
