### ISSUE TITLE
is audio support as input output

### ISSUE THREAD

**Issue by ak9250** [gradio-app/gradio#23]
checking the docs is audio data types supported for input and output for models?

**Comment by abidlabs** [comment]
We do support audio as input. The interface is called `Microphone`. Output audio coming soon. What kind of model are you building that's audio to audio?

https://gradio.app/docs

**Comment by rcox771** [comment]
bumping for interest in signals. @abidlabs , one could conceivably use this library for demonstrating audio denoising tasks, separation of different speakers from one audio recording, selectively damping certain noise sources - like the kind of models used in some commercial webconferencing applications, and a whole lot more. Interpolating vocal styles and inflections, text-to-speech applications, mixing the qualities of instruments together to make new sounds, filtering audio to look for certain sounds and playing that back to the user - like if you're a biologist trying to collect or model the sounds of certain animals (bats, whales, birds, etc) for study.

-Russ

**Comment by abidlabs** [comment]
We should have this fixed soon!

**Comment by abidlabs** [comment]
With the latest version of `gradio 1.1.0`, we now support audio inputs and outputs. Thanks for the suggestion!

**Comment by m-ali-awan** [comment]
Audio, with microphone is not working.After recording, when I play, it is silent.
Please, help me out with this.
Thanks
