### ISSUE TITLE
resnet18 demo not working. Shows following error message

### ISSUE THREAD

**Issue by gchetty** [gradio-app/gradio#230]
HTTPError                                 Traceback (most recent call last)
<ipython-input-7-9cda5a84a77f> in <module>()
----> 1 model = torch.hub.load('pytorch/vision:v0.6.0', 'resnet18', pretrained=True).eval()
      2 
      3 response = requests.get("https://git.io/JJkYN")
      4 labels = response.text.split("\n")

8 frames
/usr/lib/python3.7/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: rate limit exceeded

**Comment by aliabid94** [comment]
Seems like an issue with PyTorch Hub right now. Presumably will resolve itself soon, if not, we'll load the model from another repository.

**Comment by AK391** [comment]
@gchetty I was having a similar issue, using torch==1.8.0 resolved it, can you try that

**Comment by AK391** [comment]
@gchetty also see https://github.com/pytorch/vision/issues/4156#issuecomment-875336621

**Comment by abidlabs** [comment]
Closing because this is not a gradio issue. Thanks everyone for helping!
