### ISSUE TITLE
`copy to clipboard` is not working

### ISSUE THREAD

**Issue by secsilm** [gradio-app/gradio#2311]
### Describe the bug

`copy to clipboard` is not working when `output="json"`. Click it and no response.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

demo = gr.Interface(lambda name: {"output": f"Hello {name}!"}, inputs="text", outputs='json')

if __name__ == "__main__":
    demo.launch(server_name='0.0.0.0', debug=True)
```

### Screenshot

![image](https://user-images.githubusercontent.com/8894643/191458063-3b786c4f-cace-4324-bb92-6b782145d79e.png)

### Logs

```shell
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
```

### System Info

- Gradio version: 3.3.1
- OS: Ubuntu 18.04
- Browser: Chrome 105.0.5195.102

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks @secsilm can confirm the issue! @dawoodkhan82 would you be able to take a look at this?

**Comment by freddyaboulton** [comment]
If you remove `server_name` it works 🤔

**Comment by freddyaboulton** [comment]
Chrome automatically blocks access to the clipboard since the site is not secure:

![image](https://user-images.githubusercontent.com/41651716/191551867-c83e9797-588f-4254-b8eb-20340a704d7a.png)

**Comment by abidlabs** [comment]
Ah interesting, it also doesn't work inside iframes (e.g. inside of a jupyter notebook). 

It seems like we should be able to fix that: https://stackoverflow.com/questions/61401384/can-text-within-an-iframe-be-copied-to-clipboard

**Comment by ihmily** [comment]
> If you remove `server_name` it works 🤔

It works! Thank you very much.
