### ISSUE TITLE
Change brush size on `sketch` tool for images

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#2312]
**Is your feature request related to a problem? Please describe.**  
I can't change the brush size 

**Describe the solution you'd like**  
Being able to change the brush size

**Additional context**  
I know the `color-sketch` is on the making, but I don't want color, just drawing a simple mask but changing the brush size. Maybe the brush size chooser from `color-sketch` could be ported back to `sketch`?

**Comment by pngwn** [comment]
Will try to add this in the current PR.

**Comment by pngwn** [comment]
@apolinario I've added this as part of #2144.
