### ISSUE TITLE
Dynamically draw a mask on an image with an editable `sketch` component

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#2314]
**Is your feature request related to a problem? Please describe.**  
New cool text-based inpainting tools are being released
![image](https://user-images.githubusercontent.com/788417/191554194-1485dbaf-fcd6-449a-9a5d-4ce916785f18.png)

This works by typing a word, then using some computer vision technique to find the concept you typed the word for in the image and automatically drawing the mask. 

However, once this mask is "found", I can't further iterate it on Gradio (e.g.: adjusting fine details), as one can't load a pre-made mask into a `gr.Image` with `sketch`

**Describe the solution you'd like**  
I would like to be able to input to the `gr.Image` component a mask png that then would be converted into the drawable masking UI with those parts already filled in, so the user could further modify

**Comment by apolinario** [comment]
Here's a video example of how this could work:
https://user-images.githubusercontent.com/788417/191570986-52d1e519-0374-4cad-b267-c215c312e5ee.mp4

**Comment by alexamy** [comment]
This is a cool feature to support, especially for [interactive segmentation](https://lama-cleaner-docs.vercel.app/features/Interactive_segmentation) case.

**Comment by vidit98** [comment]
This would be a cool feature to add. If we can initialize mask in `sketch` using a predefined mask and ask user to refine it, would be really useful
