### ISSUE TITLE
Multiple tests failed when in the current master

### ISSUE THREAD

**Issue by adamryczkowski** [gradio-app/gradio#2323]
### Describe the bug

I want to write a pull request. I want to get initial CI checks are passing before requesting a review. Unfortunately I get multiple tests  failed even when checking against an upstream sources without my modifications.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Install Ubuntu 20.04
2. Install python 3.10 from deadsnakes PPA
3. Install node 16 `curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -`
4. `sudo apt install -y nodejs`
5. `curl -fsSL https://get.pnpm.io/install.sh | sh -`
6. clone the gradio git repository
7. make a virtualenv `python3.10 -m venv venv`
8. `. venv/bin/activate`
9. `bash scripts/install_gradio.sh`
10. `bash scripts/build_frontend.sh`
11. `bash scripts/install_test_requirements.sh`
12. `bash scripts/create_test_requirements.sh`
13. `bash scripts/run_all_tests.sh`

### Logs

```shell
https://pastebin.pl/view/21860e8b
```

### System Info

```shell
gradio master, commit `581fbabe07383fe50231c9053d3a40ba9c395b83`
Python 3.10.7
Ubuntu 20.04 64bit
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Hi @adamryczkowski, thanks for the interest in making a PR! It looks like the main issue is that ffmpeg is not installed in your ubuntu environment. Can you try installing it with `sudo apt install ffmpeg`?

**Comment by freddyaboulton** [comment]
Note that there are some unit tests that make external requests to the huggingface model hub and those can sometimes fail due to rate limits or (infrequent) outages of models on the hub.

The tests that can sometimes fail for reasons unrelated to your change are marked flaky and you can filter them out from your runs like so:

`pytest -k "not flaky" test`

**Comment by adamryczkowski** [comment]
Yep, installing `ffmpeg` did the trick. Thank you!
