### ISSUE TITLE
Gallery - Adding a label under each image

### ISSUE THREAD

**Issue by Pfaeff** [gradio-app/gradio#2327]
It would be nice if it were possible to add some additional information to the images in the gallery. 

Being able to return a list of tuples of image and string and having those strings displayed as labels under the images would be a great start.

**Comment by pngwn** [comment]
Duplicate of #2091.

Are there any features other than labels you think the gallery should have, or can this be closed?

**Comment by Pfaeff** [comment]
Weird that I couldn't find that issue. Yes, this can be closed. Sorry for the inconvenience.

**Comment by abidlabs** [comment]
Thanks @Pfaeff! Let us know if we can help in any other way
