### ISSUE TITLE
Unable to adjust height/width of image output in spaces

### ISSUE THREAD

**Issue by nickmuchi87** [gradio-app/gradio#2331]
### Describe the bug

I have an gr.Image component where I am rendering an image located in the images folder in this space: https://huggingface.co/spaces/nickmuchi/Plant-Health-Classifier

Using the code below:

`gr.Image('images/Healthy.png',label = 'Healthy',type='pil').style(width='5',height='5') `

the image is pretty much taking the whole screen size. Tried all different sizes variables.

on a mobile phone it renders as expected but not on desktop.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/nickmuchi/Plant-Health-Classifier

### Logs

```shell
No errors in Python logs, just ignores the code
```

### System Info

```shell
Default versions in HuggingFace spaces
```

### Severity

annoying

**Comment by fffiloni** [comment]
You can give your component an ID, then use CSS to tweak width and height :)

`gr.Image( value = 'images/Healthy.png', label = 'Healthy', type = 'pil', elem_id="healthy_img" )`

then set you CSS as usual: 

```
my_css = """
    #healthy_img { 
        width: 500px; 
        height: 500px; 
   } 
```

and don't forget to call your css variable as argument in your gr.Interface() method like so :
`demo = gr.Blocks(css=my_css)`

**Comment by abidlabs** [comment]
Thanks @nickmuchi87, the arguments to the `width` and `height` parameters should be floats, not strings. Something like this works for me:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Image("lion.jpg").style(width=120)

demo.launch()
```

the approach @fffiloni suggested should also work.

**Comment by nickmuchi87** [comment]
awesome, that worked, Last question is, how would I center the image as it is left aligned?

**Comment by abidlabs** [comment]
I took a closer look at this Space, and since this is just a static image, what I actually recommend here is that you actually just use the HTML component for this. 

In other words, replace this line:
```py
gr.Image('images/Healthy.png',label = 'Healthy').style(width=250,height=250)
```
with 
```py
gr.HTML('<center><img src="file/images/Healthy.png" width=250px height=250px></center>')
```

I'll go ahead and close the issue since the original problem is solved.
