### ISSUE TITLE
How to create multiple apps

### ISSUE THREAD

**Issue by yuanjie-ai** [gradio-app/gradio#2334]
How to create multiple apps

**Comment by abidlabs** [comment]
Hi @yuanjie-ai, it sounds like you have a general question --> please head over to our [Forums](https://discuss.huggingface.co/c/gradio/26) or [Discord](https://t.co/JKepTfXraQ) for general questions. These GitHub issues are designed for detailed bug reports that include code for reproducibility or detailed feature requests.

We're happy to help with more general questions on the Forum or Discord, though we'll need more explanation of what you mean by "create multiple apps"
