### ISSUE TITLE
Gradio fails to render thumbnails when image directory path is specified

### ISSUE THREAD

**Issue by neerajprad** [gradio-app/gradio#2335]
### Describe the bug

When I instantiate the Interface class with `examples={directory path}` (this is one of the options given in the documentation for the [Interface](https://gradio.app/docs/#interface-header) class) for an image classification model, the app fails to generate the thumbnail images for the examples. (See screenshot)

Clicking on the blank thumbnail still correctly loads the example. I checked that replacing this with a list to the absolute path for each of the example images works as expected. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Relevant commit: [99c4e70901c27da87e3313902128fb629e31278d](https://huggingface.co/spaces/neerajprad/leaf-classifier-demo/commit/99c4e70901c27da87e3313902128fb629e31278d)

### Screenshot

<img width="832" alt="Screen Shot 2022-09-25 at 4 41 35 PM" src="https://user-images.githubusercontent.com/1762463/192187911-14d1b40d-56af-4497-b5c3-a9b414e38dbd.png">

### Logs

```shell
N/A
```

### System Info

```shell
App running on Huggingface Spaces
Browser: Chrome
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @neerajprad ! Thanks for filing this. I think I know what's happening - the examples component is not loading the full path to the file. This is similar to https://github.com/gradio-app/gradio/issues/2129 but I it's an actually a different case.

**Comment by neerajprad** [comment]
> This is similar to https://github.com/gradio-app/gradio/issues/2129 but I it's an actually a different case.

Ahh..I missed that. Feel free to close/merge the issues if you think the fix is the same for both. Thanks for taking a look.

**Comment by evanlesmez** [comment]
I still see this with gradio 3.33.1

**Comment by evanlesmez** [comment]
The problem seems to stem from using images from a path with a different parent directory

**Comment by wywywywy** [comment]
> The problem seems to stem from using images from a path with a different path of parents

Sorry can you explain what you mean by this please? @evanlesmez

**Comment by evanlesmez** [comment]
> > The problem seems to stem from using images from a path with a different path of parents
> 
> Sorry can you explain what you mean by this please? @evanlesmez

Sorry I should have been more clear and included more information at the time. I do remember seeing blank thumbnails. Not sure if it was because of relative path or not but I can see now that in a project with sample images I provided an absolute path for examples.

**Comment by xiexh20** [comment]
Same issue here at hugging face demo: https://huggingface.co/spaces/xiexh20/HDM-interaction-recon

Strange thing is when I run this locally on my workstation, it shows the thumbnail correctly.

**Comment by xiexh20** [comment]
Thank you for your swift reply. 
Unfortunately the problem still persist, I renamed all files at this commit: https://huggingface.co/spaces/xiexh20/HDM-interaction-recon/commit/198dde715733ac84db6a6d1efeaf9762b1bc1d82 
It still does not show thumbnail. Similar to before, in my own workstation, it works well. 
The gradio version at my workstation is 4.20.1, which should be the same to the one installed automatically at hugging face.
