### ISSUE TITLE
Gradio .change() KeyError when multiple outputs.

### ISSUE THREAD

**Issue by chengyjonathan** [gradio-app/gradio#2336]
### Describe the bug

If I understand the documentation correctly, I should be able to use a list of output components for the .change() method. 

So an input change from one component can affect the behavior of multiple components. 

It works if I just set one output, but breaks for multiple.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
some_radio_feature.change(
                    fn=some_func
                    inputs=some_radio_feature,
                    outputs=[component_one, component_two, component_three
)
```

### Logs

```shell
Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/stable-diffusion/lib/python3.8/site-packages/gradio/routes.py", line 259, in run_predict
    output = await app.blocks.process_api(
  File "/home/ubuntu/.conda/envs/stable-diffusion/lib/python3.8/site-packages/gradio/blocks.py", line 691, in process_api
    predictions = self.postprocess_data(fn_index, predictions, state)
  File "/home/ubuntu/.conda/envs/stable-diffusion/lib/python3.8/site-packages/gradio/blocks.py", line 642, in postprocess_data
    prediction_value = predictions[i]
KeyError: 0
```

### System Info

```shell
gradio 3.2
```

### Severity

annoying

**Comment by chengyjonathan** [comment]
Nvm, found the tutorial where dictionary output is required to impact multiple components! My bad! :D

**Comment by freddyaboulton** [comment]
No problem @chengyjonathan ! Glad you figured it out.
