### ISSUE TITLE
Dataset not support Markdown components - no warnings or docs

### ISSUE THREAD

**Issue by DeXtmL** [gradio-app/gradio#2349]
### Describe the bug

The Dataset component doesn't support components other than Text, otherwise the render fails

Consider this example:

```
def test(data):
    print(data)
with gradio.BLocks() as demo:
  d = gr.Dataset(components=["markdown","text", "text"], samples=[["contentA","contentB","contentC"]], headers=["C1","C2","C3"], label="bug report")
  d.click(fn=test, inputs=d, outputs=None)
demo.launch()
```

This is the output UI:
![a](https://user-images.githubusercontent.com/13725477/192568345-efa38b6e-aebc-46fd-9499-be78defb99d2.jpg)
When click on it, the data passed is correct, but the render is completely shifted.

Expectation:
1. Gradio should work as the doc described.
2. If the feature is not supported atm, Gradio should issue a warning message

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run this code, and observe the result
```
import gradio as gr

def test(data):
    print(data)
with gradio.BLocks() as demo:
  d = gr.Dataset(components=["markdown","text", "text"], samples=[["contentA","contentB","contentC"]], headers=["C1","C2","C3"], label="bug report")
  d.click(fn=test, inputs=d, outputs=None)
demo.launch()
```

### Screenshot

![a](https://user-images.githubusercontent.com/13725477/192568345-efa38b6e-aebc-46fd-9499-be78defb99d2.jpg)

### Logs

```shell
None
```

### System Info

```shell
Gradio 3.3
Windows 11
Edge and Chrome latest version
```

### Severity

serious, but I can work around it

**Comment by DeXtmL** [comment]
@freddyaboulton On a quick test, the HighlightedText and Button also does not work with Dataset. Also I'm not sure how to embed Slider, as you mentioned, into a Dataset; giving a float or str as its initial value (in "samples" property) raises an AttributeError.  Some example codes are rather welcome. 
 Thanks!

**Comment by abidlabs** [comment]
I'll take a look at this!
