### ISSUE TITLE
Gradio Hosted App is not working

### ISSUE THREAD

**Issue by nimanpra** [gradio-app/gradio#235]
![image](https://user-images.githubusercontent.com/13941762/124173567-da8e3800-dac8-11eb-9223-a33f34e6e024.png)
One of my associates trying to use the app, but its stops in the middle with an error icon on the top right hand-corner. I tried it with my PC and it worked but took 1000+ seconds. This only took 100-350 seconds max before. My associate tried it on an iPad, and to test I also tried it on Iphone and I also got this. I have attached the screenshots for all.

Will you be able to check and let us know? Thanks

![image](https://user-images.githubusercontent.com/13941762/124173834-33f66700-dac9-11eb-9cf3-9ad84404183a.png)

**Comment by abidlabs** [comment]
Thanks for bringing this to our attention, @nimanpra. We'll take a look to see what the underlying cause is.

**Comment by abidlabs** [comment]
Sorry, is this still an issue @nimanpra? If so, can you send me a link to your Gradio Hosted interface?

**Comment by abidlabs** [comment]
Closing for lack of response
