### ISSUE TITLE
Capture image id when using gradio `Gallery`

### ISSUE THREAD

**Issue by OrkhanHI** [gradio-app/gradio#2352]
I am building the UI with Gallery of images and want to compare two images when they are selected by the user. Once the user clicks on  the image I want to capture the `image_id` and retrieve it from the list of the images by value, same goes for the second one. 

**Describe the solution you'd like**  
Get two image IDs and capture their value to run through the model and get output as selected two images and show the score.

**Comment by abidlabs** [comment]
Hi @OrkhanHI to clarify, are there two different Galleries, or one Gallery where you'd like to select 2 different images within the Gallery?

**Comment by fffiloni** [comment]
I think what you are asking for is gr.Gallery() as input, from which you could select two images then compare them through the model. Unfortunately, the Gallery component does not accept input, according to the Docs.

What you could do instead is: 

from your own html gallery list, select 2 images (with javascript for example), and then send them through the Gradio API routed to the Gradio app where you'd set 2 images components as inputs.

Tell me if it does make sense :)

**Comment by abidlabs** [comment]
Agreed with @fffiloni. If you are looking for a single Gallery in which two inputs can be selected, that is currently not possible with `gradio` and seems out of scope for this component. It would be possible to built something custom with html/javascript as @fffiloni suggested if you are familiar with frontend development.

If you are looking for two Gallery components, and you select one image from each component, that could be something we add support for (in that case, please follow this issue: #1976)
