### ISSUE TITLE
[theming] implement internal theming architecture in the  frontend (architecture)

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#2353]
As part of the theming work we need to refactor how style values are set across the application.

**Stop using tailwind classes**

Currently we use `tailwind` classes directly and while this does provide a very consistent look and feel across the applications it doesn't not really give us the theming capabilities we need. Tailwind itself doesn't not exclusively use CSS variables, so direct manipulation of those values is not really possible. Tailwind _does_ have some support for theming but it doesn't really cover all of our usecases and the APIs themselves are pretty annoying to work with. I haven't looked inot this too closely but I think tailwind requires a rebuild for new themes to be added (at least in order to get full theming functionality), we want to apply themes at runtime.

**Still use tailwind as a base**

Despite the above issues, tailwind actually comes with a sensible set of defaults that are pretty well thought out. It would be a shame to lose this work (that is already done for us).

Luckily tailwind actually ships its default theme values as an npm package that can be imported and used as values. So we can use these base values as part of our base theme, we just need to pull our the values directly and save them as CSS variables which we can then use across the applications. While we will lose some nice things that tailwind brings, we still benefit from tailwind as a rough design system.

**Bring order to our components**

At the minute gradio's styling is pretty difficult to reason about and some patterns have started to creep in that are quite difficult to maintain. We have some global tailwind overrides/ custom definitions that a contributor won't know about unless they read all of the source code. We are using utility classes in certain cases but their use is difficult to track, difficult to maintain, and inconsistently used. Some of these issues are just due to the nature of CSS as a global untyped language that cascades throughout the document but we can improve matters by being consistent in how we apply CSS and documenting our practices. We also have odd bits of CSS inside the components themselves.

Given this context, we have a few options available to us. 
1. We could go all in with the use of utility styles and use CSS variables to set the values of properties within these styles.  This would be quite a lot of work, as we would essentially need to remap all tailwind styles to our own custom CSS variables. However, this would be a pretty easy to use + customisable system. It would also allow us to make certain values/ properties unthemeable, which would make the user-facing theming system pretty robust.
2. Colocate all styles inside components, and use css variables directly. This would make individual components very easy to reason about, as all styling for that component would be clearly defined within the component itself, it would also make occasional overrides simple as well (we sometimes need to use specific CSS values or style values that aren't covered by tailwind). The values used within the component would be consistent due to the use of CSS variables but there would be no guarantees of consistency in how those values are actually used. This approach would also make our total CSS larger, although due to code splitting, this isn't a huge concern.

There is also a kind of middle-ground, that is a variation on 1. That is we define custom utility classes for anything we want to be themable and use CSS variables to define the values (that for the default theme would pull from tailwind's theme values). Then for anything that we do not want to be themeable, we can fallback to tailwind utility classes. I need to explore this a little more but _i think_ this will gives us the consistency and theming we need, while also giving us some safety in excluding certain things from being themed.

While this approach has benefits both for general maintenance and community contributions, I also have half and eye on custom components. Creating a sensible framework that is easy for users to apply to their own components is important, and I feel like well documented utility classes would be a good way to do that. I feel that raw CSS variables would place too much burden on custom component authors to implement their CSS variables (and variable handling logic) perfectly in order to avoid strange breakages.

---

CSS variables themselves will need a sensible structure that isn't _too_ difficult to understand but some complexity will be necessary as we need the ability to decouple raw values (like `primary-color`) from 'semantic' values (like `button-primary-bg`). This is important because a user may want to overwrite the background colour of primary buttons, with completely removing the base colour that would be used throughout the application. I'll need to spend some time thinking about what these foundational and semantic values might include. 

Regarding things we _do_ and _don't_ want to be themeable, I'll be taking a pass over that shortly and documenting below for more discussion.

**Comment by aliabid94** [comment]
Thanks for the write-up @pngwn! I like the middle ground idea, where we use tailwind for anything we don't want themeable. 

Can we have the themes (and maybe styles too) to use the tailwind classes too via "@apply" though? e.g.
```html
<button class="rounded primary-bg {get_class(style.bg_color)}"></button>
```
and the themes be defined in tailwind as:
```css
[theme="default"] .primary-bg {
  @apply bg-orange-200 dark:bg-orange-700;
}
[theme="cool"] .primary-bg {
  @apply bg-purple-200 dark:bg-purple-700;
}
```
and we could maybe have `.style()` also use tailwind classes, e.g.
```js
function get_class(styles) {
  class_list = []
  if (styles.bg_color === "red") {
    class_list.append("bg-red-700")
  }
}
```

**Comment by pngwn** [comment]
I think the reason I would prefer css variable over tailwind classes is mainly because we can always avoid css specificity issues as css variables essentially swap out for one another when you redefine them and we can be very explicit about that. Classes always have the potential to cause specificity clashes which we will need to manage. We have hit this problem pretty frequently and need to use the `!` syntax quite a bit. There are also some values that are pretty annoying to define with classes as you have to do a lot of string wrangling, rather than just passing simple values into css vars. 

Svelte also has first class support for css variables which makes them easier to work with. 

The final reason is that I don't want our API to be the tailwind API as we would have to change our documentation and version accordingly every time something changes in tailwind. Likewise, users would be limited to the tailwind's 'design system' which I think is too limiting for a theme system or 'customisation' effort.

**Comment by pngwn** [comment]
Another issue with using classes directly is we could only change the value globally rather than for a specific  instance of a component. Regardless of what we surface to users, this architecture is as much to solve our problems as anything and we need the ability to tweak things on a relatively granular level.
