### ISSUE TITLE
[theming] design + implement sharing workflow (sharing)

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#2356]
Detail to follow.

Notes:
- once a user has created a theme, how can we allow them to share that theme
- once a user is _aware_ of another users shared theme, how can they use it.
- imo, the sharing part offers the greatest opportunity for gradio to raise the bar in terns of making sharing and reusing themes as seamless as possible. Other solutions in the wild are clunky and full of technical barriers.
- Its gonna require some infra.

**Comment by abidlabs** [comment]
Closed via #3428, thanks @freddyaboulton!
