### ISSUE TITLE
Optional Image input or default value for image?

### ISSUE THREAD

**Issue by mfrashad** [gradio-app/gradio#236]
I am making a GAN interface for image editing where user can enter a seed value or upload an image. However, I cannot submit unless the image input is filled. I can work around this on other types of input by setting a default value. But since there is no default option in Image input. I cannot make it optional.

Is there a way to make the Image input optional?

**Comment by abidlabs** [comment]
Sorry for the late reply @mfrashad, this is a great suggestion. We currently support optional outputs but not inputs. We'll work on supporting optional inputs.

**Comment by aliabid94** [comment]
Optional inputs are supported as of 2.2.15, use the optional= kwarg . Let us know if you have any other issues.
