### ISSUE TITLE
Feature request: API Introspection

### ISSUE THREAD

**Issue by leszekhanusz** [gradio-app/gradio#2364]
Making an external frontend integrating with a gradio interface using the API can be really difficult if the gradio API is constantly changing.

Please provide a way to detect the inputs and outputs of a gradio API (it's too bad the interface is not made using GraphQL or we would be able to use [introspection](https://graphql.org/learn/introspection/))

Context: I'm currently writing a [GUI](https://github.com/leszekhanusz/diffusion-ui) for a gradio interface and the gradio interface is constantly changing, breaking the API in the process.
I would like to programmatically send a request to the API to detect the different functions, fn_id, inputs and outputs of the interface, the default input values, min, max, type of input, etc...

**Comment by freddyaboulton** [comment]
Hi @leszekhanusz ! 

Is the api page at the bottom of the gradio front end in line with what you expect?

![image](https://user-images.githubusercontent.com/41651716/192896272-4f6567ee-a392-422b-a3a1-7c5c07ce8895.png)

If pass the `api_name` parameter when you define your events, you will see the api route docs

![image](https://user-images.githubusercontent.com/41651716/192896564-4adefb39-8a64-46b1-a167-e7c18c547d08.png)

**Comment by leszekhanusz** [comment]
Yes, but I want to access it programmatically

**Comment by leszekhanusz** [comment]
I've looked into this a bit more and in fact this already exists!
All the info is there in the `/config` path!

This should definitely get a mention in the docs!

**Comment by pngwn** [comment]
Two interesting points here:
- We could make introspection of this kind simpler and surface it better in the docs.
- We should stop breaking the API.

The API does go through a little churn atm, I do think we want to stabilise that in the future but I don't think we'll be able to do that until we make some more breaking changes (which we try to minimise). This will probably require a major version bump, so we can overhaul the signatures to be more robust to future changes.

The first point is something we can definitely do.

I'd like to leave this issue open so this concern doesn't fall off our radar but I'll open a new issue to document this feature (and maybe) clean up the API before we make it public.

**Comment by abidlabs** [comment]
Once we have programmatic introspection, let's disable the FastAPI `/docs` route. It adds no additional value and is kind of confusing since it exposes so many unused routes: 

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/1778297/223266731-a30f35e7-a0d3-4892-93de-a22a0e70517d.png">

**Comment by freddyaboulton** [comment]
Yes makes sense @abidlabs !
