### ISSUE TITLE
Issue with the huggingface theme

### ISSUE THREAD

**Issue by stanreb** [gradio-app/gradio#237]
Hello, 
Is there a way to show the % probabilities on top of the bar plot output, using the huggingface theme ? 
The probability figures appear to be there as it is possible to select and copy-paste them, but they are invisible. 
I couldn't find a way to solve this by searching in the source code of Gradio functions. 
Thanks for your help. 
Best

**Comment by julien-c** [comment]
tagging @gary149 and @cbensimon for visibility!

**Comment by aliabid94** [comment]
Sorry for the delay in addressing this. The huggingface theme hides the confidence levels as shown by the css [in huggingface.scsss here](https://github.com/gradio-app/gradio/blob/7f433f1371a7d435973670a2d0af873893f17e0a/frontend/src/themes/huggingface.scss#L385).

To change the css, the best way is to pass the css= kwarg to the Interface and overwrite this rule. For example:

```python3
import gr as gr

gr.Interface(..., theme="huggingface", css=".confidence {color: black !important}")
```

Let us know if you have any other questions!
