### ISSUE TITLE
New typeable slider doesn't respect the `minimum` and `maximum` values

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#2371]
### Describe the bug

Typable sliders are amazing! However they are currently not respecting the minimum and maximum values of the slider. It works for clicking the arrow, but if the user types, they can type an arbitrary number

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

![image](https://user-images.githubusercontent.com/788417/193131281-33b8d7fb-ba92-475d-bc4b-042895dbb82a.png)

Any slider with `maximum` or `minimum` values can have that abused by typing a value outside of the intended range. This is the [example](https://huggingface.co/spaces/lambdalabs/text-to-pokemon) where the range should be 1-4. 5 would make it OOM

### Logs

```shell
No logs
```

### System Info

```shell
Gradio==3.4
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Good catch @apolinario! @dawoodkhan82 would you be able to take a look?
