### ISSUE TITLE
Link in gr.components.Dataframe

### ISSUE THREAD

**Issue by Muennighoff** [gradio-app/gradio#2375]
Is it possible to have a link in a dataframe without converting the dataframe to HTML? If not then this would be a feat request 😁

For example for [here](https://huggingface.co/spaces/gradio/leaderboard), would it be possible to have the Blocks Party Leaderboard names link to the spaces?

Turning the row into html via e.g. 

```python
link = "https://huggingface.co/" + model_name
f'<a target="_blank" href="{link}">{model_name_show}</a>'
```

does only work when the DF is also converted to HTML, which is incompatible with `gr.components.Dataframe` 🥲

<img width="1295" alt="Screenshot 2022-09-30 at 09 28 56" src="https://user-images.githubusercontent.com/62820084/193215415-acbaf7f0-dd30-4a9e-9810-042580dc71e1.png">

**Comment by pngwn** [comment]
The dataframe should support html as a datatype, you can see an example in [this demo](https://github.com/gradio-app/gradio/blob/main/demo/blocks_outputs/run.py#L67-L89). Is this what you are looking for?

Or is the part you are saying is incompatible? Do you have an example of this, it should work.

**Comment by Muennighoff** [comment]
Was missing `datatype="markdown"` - working now, thanks!
