### ISSUE TITLE
[Series] can't launch a series with combination of classic interface and blocks interface ?

### ISSUE THREAD

**Issue by fffiloni** [gradio-app/gradio#2377]
### Describe the bug

If we load 2 interfaces, one is made by the classical Interface() method, the other one is made by Blocks, 

Series interface won't launch.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

def do_one(text):
    return text

def do_two(text):
   return f"{text} hello"
   
iface = gr.Interface(do_one, inputs=gr.Textbox(), outputs=gr.Textbox())

iface2 = gr.Blocks()

with iface2:
   text = gr.Textbox()
   out_text = gr.Textbox()
   btn = gr.Button().click(do_two, inputs=text, outputs=out_text)

demo = gr.Series(iface, iface2)

if __name__ == "__main__":
   demo.launch() 

```

### Logs

```shell
/home/user/.local/lib/python3.8/site-packages/gradio/interface.py:328: UserWarning: Currently, only the 'default' theme is supported.
  warnings.warn("Currently, only the 'default' theme is supported.")
Traceback (most recent call last):
  File "app.py", line 18, in <module>
    demo = gr.Series(iface, iface2)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/mix.py", line 111, in __init__
    connected_fn.__name__ = " => ".join([io.__name__ for io in interfaces])
  File "/home/user/.local/lib/python3.8/site-packages/gradio/mix.py", line 111, in <listcomp>
    connected_fn.__name__ = " => ".join([io.__name__ for io in interfaces])
AttributeError: 'Blocks' object has no attribute '__name__'
```

### System Info

```shell
Gradio version: 3.4 | Running of HuggingFace Spaces
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hey @fffiloni ! Yea Series is not expected to support a mix of blocks and interfaces. The docs make it clear that it should only be interfaces so I'm inclined to close this.  

Blocks can have many functions so the default `fn_index=0` used for the Blocks.__call__ method may not be appropriate for all use cases. In my opinion, it'd be best if the developer uses their domain knowledge to choose how they are combined. You can do something like this:

```python
def new_predict(input):
    return interface_app(blocks_app(input, fn_index=2))

gr.Interface(new_predict, ......).launch()
```

Let me know if I'm misunderstanding!

**Comment by fffiloni** [comment]
Thank you @freddyaboulton 🙏

What do mean by ˋinterface_app` and ˋblocks_app` in the new_predict method ?

**Comment by freddyaboulton** [comment]
@fffiloni My bad for using confusing terminology. By `interface_app` I mean an app defined via interface, e.g. `gr.Interface(...)` and by `blocks_app` I meant an app defined via Blocks `gr.Blocks() as demo:`
