### ISSUE TITLE
New Highlighted code component that can beautify code outputs 

### ISSUE THREAD

**Issue by fffiloni** [gradio-app/gradio#2381]
- [ *] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Not really, but could be annoying: code output (e.g. from Codegeex demo) is not highlighted and make it hard to read and spot any errors or bad code generation.

**Describe the solution you'd like**  
A gr.HighlightCode() component, able to highlight generated code output, regarding the language given also in output:
For example : 

`outputs=gr.HighlightedCode(value="result.txt", lang="Python")`

or why not:

`outputs=gr.Textbox( value="generated_code", lines=42, type=["code", "Python"] )`

**Additional context**  
Context: [CodegeeX demo on Huggingface](https://huggingface.co/spaces/THUDM/CodeGeeX)

outputs not highlighted for the moment:
<img width="1553" alt="Capture d’écran 2022-10-03 à 09 26 54" src="https://user-images.githubusercontent.com/7447007/193522567-dd86b732-c03b-4754-9417-c4d6ed899547.png">

What could be better: 
![highlighting-code-example](https://user-images.githubusercontent.com/7447007/193522668-71088267-3750-4f30-be70-60708ca0386e.png)

Many libraries can help implement this new component, here's a few examples :
[Top 5 : Best code syntax highlighter javascript plugins](https://ourcodeworld.com/articles/read/140/top-5-best-code-syntax-highlighter-javascript-plugins#:~:text=SHJS%20is%20a%20JavaScript%20script,written%20in%20many%20different%20languages.)

**Comment by abidlabs** [comment]
Duplicate of https://github.com/gradio-app/gradio/issues/1014?

**Comment by fffiloni** [comment]
Oh yes sorry 😅

i’ll close this one but the CodegeeX demo is a good and recent example that could benefit such a component 🙏

**Comment by abidlabs** [comment]
Definitely @fffiloni! Feel free to add CodegeeX as a motivating issue in #1014
