### ISSUE TITLE
Remote Jupyter notebook not accessible at the non-localhost IP address

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#2382]
### Describe the bug

It seems that Gradio does not work with remote Jupyter notebook. See https://github.com/gradio-app/gradio/pull/2324 for more context

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

To reproduce the problem:

1. Provision a headless computer in your local LAN, e.g. at the address 192.168.0.5, on the `eth0` interface.
2. In that computer install python and then jupyterlab and gradio. 
3. Launch the jupyter lab in that computer using `jupyter lab --ip=0.0.0.0` and copy the access URL
4. Go to the workstation connected to the same lan, i.e. to the 192.168.0.0/24 network
5. Access the Jupyter lab from that workstation using e.g. https://192.168.0.5:8888/... 
6. In the Jupyter lab, type in the gradio demo, e.g.
```
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
```
7. Launch the gradio, by using `demo.launch(server_name=192.168.0.5)`. You will not be able to see the image, because the internal flask server is configured to use the `lo` network interface, so it is not listening on the external one (`eth0`).

### Logs

```shell
N/A
```

### System Info

```shell
Latest gradio version
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Hi @adamryczkowski, is this still an issue? Is there a simpler repro you can provide (e.g. running on a colab notebook) which we can use to understand the issue? Thanks

**Comment by adamryczkowski** [comment]
I don't know. I ceased to use Gradio, (partially because of the fact that issue was deemed unsupported, preventing Gradio use in my setup).

**Comment by abidlabs** [comment]
Sorry we couldn't figure it out @adamryczkowski. I'm going to close this issue, if you or anyone else experiences this using Gradio, we'll give it another try.

**Comment by AnasLahmar** [comment]
I find the same issue when I use Jupyter Lab from RunPod ("Cloud Computing Platform").

This is my code:
![image](https://github.com/gradio-app/gradio/assets/99441751/a0337e2d-903a-456d-999c-5f83a6210eb6)
It works in my VS Code/Google Colab, but in Jupyter Lab in RunPod, they show me this:
![image](https://github.com/gradio-app/gradio/assets/99441751/d22cf00b-1a63-4019-b495-2836f0c4118d)
