### ISSUE TITLE
img src not show

### ISSUE THREAD

**Issue by loboere** [gradio-app/gradio#2388]
### Describe the bug

i want to load an image from a url and display it in gradio but nothing happens, what am i doing wrong?

load_imagen.html
```

 
<canvas id="mycanvas" width=512 height=512  tabindex="0"></canvas>
 
<script>
 
var canvas = document.querySelector('canvas')
var ctx = canvas.getContext('2d')
canvas.width = 512;
canvas.height = 512;

 
var img = new Image();
img.crossOrigin=null;
//img.src = "data:image/%s;charset=utf-8;base64,%s";
 img.src =" https://www.cuerpomente.com/medio/2022/07/13/flores-simbolismo-espiritualidad_09ff3f15_1200x1200.jpg"
console.log(img)

img.onload = function() {
  ctx.lineWidth=10
  ctx.drawImage(img, 0, 0,512, 512);
 
  
};


 
 

</script>
```

def load_html():
 
    with open("/content/load_imagen.html", encoding="utf8") as f:
        body = f.read()
        
 
 

```
def test(x):
    x = load_html()
    return f"""<iframe id="sdinfframe" style="width: 100%; height: 700px" name="result" allow="midi; geolocation; microphone; camera; 
    display-capture; encrypted-media;" sandbox="allow-modals allow-forms 
    allow-scripts allow-same-origin allow-popups 
    allow-top-navigation-by-user-activation allow-downloads" allowfullscreen="" 
    allowpaymentrequest="" frameborder="0" srcdoc='{x}'></iframe>"""
```

```
import gradio as gr
def update(name):
    return f"Welcome to Gradio, {name}!"

with gr.Blocks() as demo:
    gr.HTML(test(0),visible=True )
 
demo.launch( )
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

-

### Logs

```shell
-
```

### System Info

```shell
google colab gpu t4
```

### Severity

annoying

**Comment by fffiloni** [comment]
what if you try with a simple approach : 

`gr.HTML('<img src="your_img_url" />')`

**Comment by abidlabs** [comment]
Hi @loboere there's a lot going on in the code example and it's not formatted in a way that's easy to understand. Can you please provide a minimal example that has this bug? 

You should be able to reference image URLs like how @fffiloni described above.

**Comment by abidlabs** [comment]
Is still an issue @loboere? If not, I’ll close
