### ISSUE TITLE
Audio not playing till the end

### ISSUE THREAD

**Issue by Pranjalya** [gradio-app/gradio#2389]
### Describe the bug

While inferencing from any model which outputs audio, the Audio player starts playing, but stop 1 second before the end. It is replicated in almost all the different Gradio instances I have made.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just create a Gradio app which outputs audio with the latest Gradio version.

### Logs

```shell
No errors in the logs.
```

### System Info

```shell
Gradio Version - 3.4
OS - Ubuntu 20.04
```

### Severity

blocking upgrade to latest gradio version

**Comment by freddyaboulton** [comment]
Hi @Pranjalya ! I think I see what you're talking about but is it the case that there is audio "missing" from the file? 

When recording from my microphone, the audio component properly records all of my speech. If you run the `audio_debugger` demo in the repo, the audio played in the gradio ui matches the audio I get when I play `cantina.wav` with my computer's default audio player.

**Comment by fffiloni** [comment]
I think there is a problem related to iOS recording, and maybe the audio record output from iOS. 

What make me think of this hint, is that while trying the [Whisper to Stable Diffusion](https://huggingface.co/spaces/fffiloni/whisper-to-stable-diffusion)  space ( supafast now thanks to @freddyaboulton ;) ) from iOS, Whisper is always off and returns default output such as « thank you » or « bye » 

Sometimes it also returns only the beginning of the audio, like « a dog that … », while i said « a dog wearing sunglasses »

Would be interesting to investigate how gradio is handling audio record coming from smartphones devices :)

**Comment by freddyaboulton** [comment]
Glad to hear it's fixed for you @Pranjalya ! Let us know if you run into any other issues!
