### ISSUE TITLE
How to only "clear" one of inputs but keep other inputs then "Submit"

### ISSUE THREAD

**Issue by Johnson-yue** [gradio-app/gradio#239]
Hi, thank you for your Best-App, but when use it, I have some advices 

In my usage,  I have 3 "files" for input, and 2 "images" for output
I want to only clear one of input  but keep other input, then submit,  how should I do ?

**Comment by AK391** [comment]
@Johnson-yue what is your use case here, all fields currently have to be populated for the front end to respond, optional input components are in the works

**Comment by Johnson-yue** [comment]
My case is， I have 3 inputs like [ text, image1,  image2]  and outputs is only [imageO1].  
So, I want to only change image1 to image3  and not change others, new inputs is [text, image3, image2]

**Comment by abidlabs** [comment]
This is something that we are going to be able to handle immediately since it would require a UI refresh. 
Closing for now.
