### ISSUE TITLE
I can't upload image in colab

### ISSUE THREAD

**Issue by loboere** [gradio-app/gradio#2390]
### Describe the bug

the image bar appears but I can't upload and drag and drop any image

![image](https://user-images.githubusercontent.com/15265895/194371001-7ef8c5f2-7a29-4f7e-9afc-77be3de48f44.png)

```
import gradio as gr
def update(name):
    return f"Welcome to Gradio, {name}!"

with gr.Blocks() as demo:
    gr.Markdown("Start typing below and then click **Run** to see the output.")
    gr.Image(type="pil")
 
         
demo.launch()
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr
def update(name):
    return f"Welcome to Gradio, {name}!"

with gr.Blocks() as demo:
    gr.Markdown("Start typing below and then click **Run** to see the output.")
    gr.Image(type="pil")
    
         
demo.launch()
```

 

 

```shell
-
```

### System Info

```shell
colab t4
```

### Severity

blocking all usage of gradio

**Comment by fffiloni** [comment]
Hello @loboere ! 

To be able to upload an image, you need to specify the source as "upload" like this:
 
`gr.Image(source="upload", type="pil")`

That's it !

**Comment by pngwn** [comment]
@abidlabs @aliabid94 isn't this supposed to be the default for an interactive image component?

**Comment by fffiloni** [comment]
@pngwn yes, regarding to Docs, source is set to "upload" by default, and it's working fine with me (i'm using gradio 3.4 on HF)
Tested on Chrome and Firefox. 

But maybe it's a Colab related bug, or related to the Browser ?

**Comment by freddyaboulton** [comment]
Yea "click to upload" works fine but "drag and drop" does not work for me - 

![image_upload_colab](https://user-images.githubusercontent.com/41651716/193851400-b0b361c8-9dd1-4aa6-be86-6afe5ca64edd.gif)

![colab_drag_and_drop](https://user-images.githubusercontent.com/41651716/193851646-adb51c39-dba9-45a6-85a4-4d7879a9dc20.gif)

I think this is a colab issue that could be out of our control - I can drag and drop when running on a jupyter notebook and in an embedded demo as well. 

@loboere Does "click to upload" work for you?

**Comment by pngwn** [comment]
I'll look at this.

**Comment by snknitin** [comment]
set `interactive=True` in `gr.Image(type="pil",interactive=True)`

**Comment by loboere** [comment]
I don't know if this is necessary, but it seems like a button is needed, if I assign gr.Image to the button input, gr.Image is enabled for upload and drag and drop.
The button has an input, a function and an output, the input would be the image and the output would be a textbox.

example:
```
import gradio as gr
import io
import base64
from PIL import Image
 
def upload_func(image ):
            pil = image.convert("RGBA")
            w, h = pil.size
    
            out_buffer = io.BytesIO()
            pil.save(out_buffer, format="PNG")
            out_buffer.seek(0)
            base64_bytes = base64.b64encode(out_buffer.read())
            base64_str = base64_bytes.decode("ascii")
            return (
              gr.update(  value=base64_str),
              
            )
 


with gr.Blocks() as demo:
  button=gr.Button("upload")
  upload_output = gr.Textbox(visible=True, elem_id="upload", label="0")
  img_input=gr.Image(type="pil")
  button.click(fn=upload_func, inputs= img_input , outputs= upload_output)
   
         
demo.launch()
```

**Comment by freddyaboulton** [comment]
I still cannot repro this . Can we close @pngwn @loboere ?

![upload_image_colab](https://user-images.githubusercontent.com/41651716/215900442-cc3ba597-48af-4bd3-a779-667d7885e580.gif)

**Comment by pngwn** [comment]
I no longer have any idea what this issues is actually about. It seems like people are talking about different things?

I've confirmed the original issue is definitely working in colab now. If anyone has any other issues please open a new issue with a full reproduction.

**Comment by luvwinnie** [comment]
is there any way to solve the problem of drag and drop in colab?
