### ISSUE TITLE
[FEAT] Addition of new guide for Components

### ISSUE THREAD

**Issue by lucifertrj** [gradio-app/gradio#2393]
Gradio Docs doesn't contain the guide for components:

Documentation mentions:

Step-by-step Guides
No guides yet, [contribute](https://github.com/gradio-app/gradio/tree/main/guides) a guide about Number/Checkbox.

I could like to contribute to building a guide that uses Number and Checkbox.

**Comment by abidlabs** [comment]
Hi @lucifertrj we'd certainly welcome a contributed Guide! 

* Please take a look at the contributing guidelines which will allow you to run Gradio and build the website locally: https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md
* You'd create a new Markdown guide in this folder and open a PR: https://github.com/gradio-app/gradio/tree/main/guides/5)other_tutorials

What do you have in mind for the content of your Guide? Can you share an outline here?

**Comment by abidlabs** [comment]
Hi @lucifertrj are you still interested in contributing this guide?

**Comment by lucifertrj** [comment]
@abidlabs Yes I am

**Comment by abidlabs** [comment]
Hi @lucifertrj would love to you to be able to contribute the Guide. Would you be able to an outline of what you have in mind? Otherwise, I'll go ahead and close this issue for lack of activity
