### ISSUE TITLE
How to deploy gradio app on heroku

### ISSUE THREAD

**Issue by TechyNilesh** [gradio-app/gradio#24]
Hello I want to know the devlopment process of gradio model on cloud server like heroku.

Its same like flask and streamlit or need some diffrent approach??

**Comment by abidlabs** [comment]
Let me confirm what you mean: you want to host your interface with a permanent URL on Heroku?

**Comment by TechyNilesh** [comment]
Yes I want to host with permanent domain on heroku.
I deployed flask and streamlit app but facing issues on gradio.

So can you please provide the guideline?

**Comment by abidlabs** [comment]
Got it, that sounds great! We'll see if we can put together a guide for
deployment on Heroku

**Comment by leungi** [comment]
On a similar note, we'd like to deploy via Docker as well; it'll open up many deployment options!

Though the app launches internally, somehow the outside world doesn't see it.

Note that the `/app` contains the gradio `app.py`.

#### Sample Dockerfile
```
FROM python:3.7

RUN pip install gradio 

COPY . /app

WORKDIR /app

EXPOSE 7860

CMD ["python", "app.py"]
```

#### app.py
```
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

def main():
    gr.Interface(fn=greet, inputs="text", outputs="text").launch()

if __name__ == '__main__':
	main()
```

**Comment by abidlabs** [comment]
For `Docker`, please try the passing in `server_name="0.0.0.0"` in your `Interface` object. So your `main()` would look like:

```
def main()
    gr.Interface(fn=greet, inputs="text", outputs="text", server_name="0.0.0.0").launch()
```

[Here's an explanation](https://pythonspeed.com/articles/docker-connection-refused/) for why you should use 0.0.0.0 inside of a Docker container to bind ports successfully.

**Comment by leungi** [comment]
Thanks for the prompt solution and reference doc @aliabd!

Glad to add gradio to our deployment options 🙏 for the work.

**Comment by abidlabs** [comment]
Turns out you can easily upload Gradio apps to Heroku. Here's a step-by-step tutorial @TechyNilesh: https://medium.com/@abidlabs/how-to-deploy-a-machine-learning-ui-on-heroku-in-5-steps-b8cd3c9208e6

**Comment by subhamChakraborty23** [comment]
nice article,thanks for sharing.
