### ISSUE TITLE
multiprocessing deactivates upon multiple calls 

### ISSUE THREAD

**Issue by YashenTaher** [gradio-app/gradio#2404]
### Describe the bug

My gradio page consists of a simple file upload and results to the right of it. User uploads a file and some of its text is extracted which is then fed into >50 different models (binary classifiers). The classification predictions of those models are then outputted as the results. I optimized the runtime of the model predictions  ten fold by having the models run their predictions in parallel rather than iteratively. However, if the user then removes the file they selected from the file drop box and uploads a new document. I receive the following warning message in console and runtime is significantly slower....but still faster than iterative.

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

 If you try doing this again, it becomes even more slower. Around the mark of the 4th file reupload it becomes slower than the pure iterative approach

Yes i have tried setting TOKENIZERS_PARALLELISM to true but that only hides the warning message. The performance slowdown is still there.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import concurrent.futures

with concurrent.futures.ProcessPoolExecuter() as executer:
      results=[executer.submit(my_optimized_predict_function,(text_extracted,model)) for model in models_list]

### Logs

```shell
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
```

### System Info

```shell
windows 
gradio version 3.1.6
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @YashenTaher can you please share the code to your demo (or a minimal example with this issue) so that we can reproduce?

**Comment by abidlabs** [comment]
Hi @YashenTaher I'm going to close this as we do not have enough details to reproduce. Feel free to reopen with more details.
