### ISSUE TITLE
Return both new value and a gr.update via dict?

### ISSUE THREAD

**Issue by vzakharov** [gradio-app/gradio#2406]
Hi, so gradio makes it possible to return values from an event_listener as a dict.

Say, I have a dropdown and I want to update both its current value and the list of available options. I understand that I can do it via a list, e.g.

```
dropdown = gr.Dropdown(choices=["hello", "world"], value="hello", lavel="Dropdown")

def update_list():
  return [
    gr.update(choices=["goodbye", "blue", "sky"]),
    "sky"
  ]

gr.Button('Update the list').click(update_list, inputs=[], outputs=[dropdown, dropdown])
```

But how do I do it if I want the update_list to return a dict? My guess is I can’t, but maybe I’m missing something?

If I’m correct, is there any other way to make it possible, e.g. by chaining the `click` listeners, e.g.
```
gr.Button('Update the list').click(update_list_choices, inputs=[], outputs=dropdown).click(update_list_value, inputs=[], outputs=dropdown)
```
?

Thanks in advance!

**Comment by pngwn** [comment]
You should be able to do:

```python
Gr.update(
  choices=[...],
  value=new_value
)

Can you give this a try and see if it works for you?

**Comment by abidlabs** [comment]
Hi @vzakharov were you able to get this to work in the @pngwn suggested?

**Comment by vzakharov** [comment]
Sorry, I've been traveling and couldn't give it a try, but I guess it would work! Do I understand it right that I can also use gr.update for dicts, e.g.
```
return {
  some_list: gr.update(choices=['a','b','c'], value='a'),
  some_other_list: gr.update(choices=['e','f','g'], value='e')
}
```
?

**Comment by abidlabs** [comment]
Yes, something like this should work:

```py
import gradio as gr


def test():
    return {t1: gr.update(visible=True, value="hi"), t2: gr.update(visible=True, value="hello")}


with gr.Blocks() as demo:
    t1 = gr.Textbox()
    t2 = gr.Textbox()
    t3 = gr.Textbox()
    btn = gr.Button()
    btn.click(test, None, [t1, t2, t3])

demo.launch()
```

**Comment by abidlabs** [comment]
Going to go ahead and close this as the above solution works for me. @vzakharov feel free to reopen if it doesn't work for you!

**Comment by vzakharov** [comment]
> Going to go ahead and close this as the above solution works for me. @vzakharov feel free to reopen if it doesn't work for you!

It does, and sorry for not closing it earlier!
