### ISSUE TITLE
UI (Blocks?) loaded event

### ISSUE THREAD

**Issue by vzakharov** [gradio-app/gradio#2408]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I would like to load input values from localStorage (or a local file) once the app is loaded.

**Describe the solution you'd like**  
I could use the _js parameter (for localStorage) or a simple fn if there were a "Blocks.load" or a similar event handler.

**Additional context**  
I think this could be useful for a variety of other use cases, too.

**Comment by pngwn** [comment]
Can you explain a little more about the usecase please? Why do you need to load the values from localstorage rather than from the server? IS this so you can persist the state locally on a per user basis?

**Comment by abidlabs** [comment]
By the way @vzakharov, there is exactly such as a `Blocks.load()` method which accepts a `_js` parameter. Here's example usage:

```py
import gradio as gr

with gr.Blocks() as demo:
    demo.load(_js="alert('hi')")
    
demo.launch()
```

It seems that we haven't documented this method, so we'll go ahead and add it to the documentation.

**Comment by vzakharov** [comment]
@pngwn, right, loading it from the server is an option too. One way or another it seems to need a Blocks.load event, which I’m very happy actually exists 🙂 (thanks @abidlabs!)
