### ISSUE TITLE
Installation stuck

### ISSUE THREAD

**Issue by ozdennis** [gradio-app/gradio#2411]
![image](https://user-images.githubusercontent.com/115283714/194609840-c67ac694-0e35-459a-b877-845708006d2d.png)

try clear slate. sometimes got trough and got this error.
sometimes i'm stuck like this

![image](https://user-images.githubusercontent.com/115283714/194610699-2cdd9806-93ef-45f8-890c-866c67e57804.png)

the cmd not taking any resource, no progress and can't even CTRL+C to cancel. i have to close it. 

is there anyone willing to help? i'm new to github didn't notice i'm posting on gradio.. can't delete.. ><

**Comment by abidlabs** [comment]
>new to github didn't notice i'm posting on gradio.. can't delete..

Hi @ozdennis yes it looks like this issue should be posted on the Stable Diffusion Web UI repo, I think you are using this one: https://github.com/AUTOMATIC1111/stable-diffusion-webui

I'll go ahead and close this issue.
