### ISSUE TITLE
A high-level `gr.Panel()` abstraction for data science dashboards

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#2414]
## Why?

To make it much easier for data scientists to get started with `gradio` to build dashboards.

## What?

A single-line, high-level abstraction that covers lots of data science use cases, similar to `gr.Interface()` for machine learning workflows.

Why isn't `gr.Interface()` good for dashboards? 
* Dashboards typically *display* data, often without the need for users to interactively provide inputs
* Dashboards usually consist of multiple "panels" arranged in some way
* Dashboard panels usually refresh as the database gets populated with new entries
* Dashboard panels are usually populated by running some sort of SQL query on some data source (wrapping the SQL in Python is annoying)

## How?

A `gr.Panel()` class that accepts three arguments:
* String SQL query or Python function
* The "input" data source (path to a csv / database URL)
* The "output" format, which could be "table" or "plot" or even just "number" (this needs to fleshed out more)

Some optional parameters could be:
* How often to refresh (building on top of the `run_every` parameter that @freddyaboulton is working on)
* The flavor of SQL

Usage might look something like this:

```py
gr.Panel("SELECT CustomerName, City FROM Customers;", DB_URL, "table").launch()
```

```py
gr.Panel("SELECT AVG(amount) as avg_amount FROM sale;", DB_URL, "number").launch()
```

```py
with gr.Blocks() as demo:
  with gr.Row():
    gr.Panel("SELECT AVG(amount) as avg_amount FROM sale;", DB_URL, "number", label="Average sales")
    gr.Panel("SELECT MAX(amount) as max_amount FROM sale;", DB_URL, "number", label="Max sales")
    gr.Panel("SELECT MIN(amount) as min_amount FROM sale;", DB_URL, "number", label="Min sales")
```

This could become by far the easiest way to run queries against a database in Python!

**Comment by abidlabs** [comment]
Thoughts on this kind of workflow for data scientists @freddyaboulton @dawoodkhan82 @rajshah4 @aliabid94?

**Comment by pngwn** [comment]
How do we authenticate with the DB? In the case of static content like a CSV it isn't a huge issue but no one is leaving their databases open, especially when dealing with private internal data which is probably the most common usecase for dashboards.

**Comment by freddyaboulton** [comment]
Thanks for filing @abidlabs ! 

I was thinking about this when I was writing https://gradio.app/connecting_to_a_database/ but connecting to the database is the easy part and I think we should leave that part up to the developer. There's a lot of database drivers out there and for each db there are multiple drivers. I don't think gradio should have an opinion on how data is fetched from databases. In keeping with the Interface analogy, the interface doesn't have an opinion on which ML framework you use - it lets you handle that in your predict function.

I do think there may be value in speeding up the process of going from "data fetched from database" to plot. In that database guide I wrote, I spent the bulk of the time making sure the plot looked right and the labels weren't cut-off etc.

**Comment by pngwn** [comment]
I'm personally a little confused as to how something so little configurability can solve dashboarding usecases. Most dashboarding tools come with a collosal number of options around how the data is visualised and how it can be filtered/ queried within the UI.

**Comment by abidlabs** [comment]
> How do we authenticate with the DB? In the case of static content like a CSV it isn't a huge issue but no one is leaving their databases open, especially when dealing with private internal data which is probably the most common usecase for dashboards.

I've seen this [included in the DB connection URL](https://stackoverflow.com/questions/33854118/how-do-i-specify-the-password-in-the-mysql-connection-url), which is in this format: `mysql://<username>:<password>@<host>:<port>/<db_name>`.

**Comment by abidlabs** [comment]
> I was thinking about this when I was writing https://gradio.app/connecting_to_a_database/ but connecting to the database is the easy part and I think we should leave that part up to the developer. There's a lot of database types out there and for each db there are multiple drivers. I don't think gradio should have an opinion on how data is fetched from databases. In keeping with the Interface analogy, the interface doesn't have an opinion on which ML framework you use - it lets you handle that in your predict function.

I definitely agree we should be agnostic to the underlying database type, but I wonder if we can improve on the database drivers. Whenever I've worked with these database drivers in the past, it's been an absolute headache. Having to define a database connection, a cursor, etc. seems unnecessarily complex in order to get simple queries, but perhaps I'm missing something

**Comment by abidlabs** [comment]
> collosal number of options around how the data is visualised and how it can be filtered/ queried within the UI.

This output (#3) is the part that I'm most unsure about!

**Comment by pngwn** [comment]
Would it be worth figuring out how we might build this with blocks and see what is missing etc while we discuss API and sensible abstractions and defaults?

**Comment by abidlabs** [comment]
> Would it be worth figuring out how we might build this with blocks and see what is missing etc while we discuss API and sensible abstractions and defaults?

100% agreed. Let's build some dashboards with Blocks first!

**Comment by abidlabs** [comment]
Perhaps better to do some more brainstorming internally before creating this issue. Let me close for now.
