### ISSUE TITLE
Website docs performance needs serious improvement

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#2416]
Right now the website loads very poorly, mostly because of all the embedded interfaces, but it needs serious optimization as it affects the workflow of users who quickly want to answer a question. 

![194618587-ccebf8c2-20dc-4f66-9d3c-65c39f51b2e9](https://user-images.githubusercontent.com/9021060/194643278-eadbcffb-a2f1-40ac-abbc-599eed734342.jpeg)

**Comment by pngwn** [comment]
I think we should fix some of this in Gradio itself because other users will suffer some of this pain too (although we are embedding more demos than most).

**Comment by aliabd** [comment]
Will close this issue as the changes from #2730 and re-enabling text compression have really improved the score. 

<img width="362" alt="Screen Shot 2023-01-03 at 6 38 55 PM" src="https://user-images.githubusercontent.com/9021060/210400937-237a12e7-bbb1-464d-bd39-2fa30bdc8a81.png">

Could still be better, and it likely will once we split the docs into smaller pages, etc. Will revisit this after that.
