### ISSUE TITLE
TypeError: Can't instantiate abstract class Carousel with abstract methods deserialize, serialize

### ISSUE THREAD

**Issue by joytianya** [gradio-app/gradio#2417]
### Describe the bug

https://huggingface.co/spaces/marcelcastrobr/CLIP-image-search/blob/main/app.py

outputs=gr.outputs.Carousel(gr.outputs.Image(type="pil"))

error:
TypeError: Can't instantiate abstract class Carousel with abstract methods deserialize, serialize

what is the problem?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/marcelcastrobr/CLIP-image-search/blob/main/app.py

### Logs

```shell
TypeError: Can't instantiate abstract class Carousel with abstract methods deserialize, serialize
```

### System Info

```shell
3.4.1
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @joytianya the `Carousel` class is basically deprecated (see #1252). We'll formally deprecate it soon. 

What kind of data were you showing in the `Carousel`? If it was images, please consider using the `Gallery` component instead.

**Comment by joytianya** [comment]
yes, it was images, thank you~
 and for Gallery， can it be displayed in pagination?

**Comment by joytianya** [comment]
ok,  Is there any way to support the pagination?
