### ISSUE TITLE
use next generation lossless image formats

### ISSUE THREAD

**Issue by HookedBehemoth** [gradio-app/gradio#2418]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
For users hosting gradio for other users, bandwidth usage can be costly.

**Describe the solution you'd like**
Serving images in better lossless image formats like webp, avif and jpegxl would result in a significant drop in bandwidth usage (~20-30%). These saving could be increased significantly by allowing lossy compression (>80%), but users might want to download the lossless version of an image they liked.

**Additional context**  
I just tested this on 3.4.1. webp is already supported by pillow and I used pillow-avif-plugin for avif. As mentioned in https://github.com/python-pillow/Pillow/issues/4247, there is JXLPy too, which I didn't test.
All of those use exif which requires a small bit more work to embed metadata.

**Comment by abidlabs** [comment]
Thanks for the suggestion @HookedBehemoth! Let me tag @pngwn as I don't know that much about these lossless image formats, but I think it would be reasonable to provide this as an option in which to output images. We do something similar in the `Video` component, where we accept a `format` keyword, and the video is converted to that format. If you'd like to propose a PR to do something similar for the `Image` component, we'd be happy to take a look.

**Comment by dineshdharme** [comment]
Just to add to that. Can we have .webp image input format for Gradio ? Just to explain a usecase. 
In this app, https://huggingface.co/spaces/fffiloni/img-to-music , we can submit images but only in .jpeg and .png format.
I can't use .webp image format. I wanted to try out images from lexica.art website as input into this app.
But lexica.art allows a user to download images in .webp format only. So this is a bummer.
As a workaround, we can use chrome extension to save images in desired format.
But from a user perspective, it would be better to have .webp images support natively in gradio.

Thanks.

**Comment by pngwn** [comment]
This should be possible, the only downside to outputting some of the modern formats is that you often can't open them in whatever default tool you use to view images (preview in mac) but i think it is a good option to have (and probably a good default). Inputs should be simpler, but the onus is on the app author to ensure whatever image processing library or model they are using can handle that image format and may need converting before being processed further.

Will take care of this soon.
