### ISSUE TITLE
Large input files freeze/crash the interface

### ISSUE THREAD

**Issue by ValentinKoch** [gradio-app/gradio#2421]
### Describe the bug

Hi, In my usecase a user uploads a rather large file (300-500mb) and it freezes the app for several seconds which makes for a very bad user experience. It happens after selecting a large file to a gradio File block. It freezes again when pressing a button that processes this data. Is there a way to circumvent this behaviour? It is running locally, as far as a I know are those sizes not supported anyway non-locally right? Currently am hosting my app on AWS. Would be cool if you could fix this behaviour, very much appreciated :)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction
```
def test():
    return

with gr.Blocks() as demo:
    inp = gr.File(label="Input")
    vis_out=gr.File(label="output")
    with gr.Row():
        btn = gr.Button("Run")
    btn.click(fn=test, inputs=[inp], outputs=[vis_out])
demo.launch() 
```
Then just add a large file as the input.

### Logs

```shell
no logs
```

### System Info

```shell
gradio v 3.4.0, occurs with different os on which the app is hosted,e.g. linux and mac 
also across browsers, chrome takes a long time, mozilla even crashes
```

### Severity

serious, but I can work around it

**Comment by pngwn** [comment]
Could you give some more info about what you'd like to do with these large files when you have them? How we handle the files that are loaded by users dictates what you can do with it. 

I haven't looked into this too much but I'm guessing that this is happening because we load the file into memory, in full. If the file were bigger 1GB+ it would probably consistently crash the browser.

**Comment by ValentinKoch** [comment]
Also it takes very long until this file is uploaded, not sure if this is related. The demo i am doing will be used in a clinical study and speed really matters. Would be awesome if you could help me out there :) would be also happy to promote gradio in some way!

**Comment by pngwn** [comment]
In this case we can (probably) chunk/ stream the data from the client without needing to store the whole thing in memory at any point. This would resolve the browser issues. I think it would still take a while to upload but maybe something else is going on that is slowing that down too. 

The challenge is figuring out when to hold things in memory and when not to. There are only circumstance in which _not_ holding things in memory makes sense, from gradio's point of view.

**Comment by ValentinKoch** [comment]
any feedback on this @pngwn ?

**Comment by ValentinKoch** [comment]
or @abidlabs ? would be very much appreciated

**Comment by ValentinKoch** [comment]
I worked around that and the fact that I cant upload files larger than 500mb by creating my own upload to aws s3 via html, but it took me quite a while.. fixing this would be a major upgrade!

**Comment by anton-l** [comment]
+1 to the request! Tried implementing a model uploader with `gradio.File`, but it unsurprisingly crashes the app when uploading 5GB model checkpoints :sweat_smile:

**Comment by abidlabs** [comment]
Yes I think we should probably stream any file if it is uploaded using `gr.File`. For the other components (e.g. Videos), it might be helpful to store in memory, but I think we don't need to do that for the File component

**Comment by ValentinKoch** [comment]
Is there anything done to fix this issue? Would help also many of my lab members as we usually deal with larger amounts of data. Would be also really desirable for you if gradio was the way to go to showcase scientific applications I guess :) Right now that workaround im using is too complicated as that I could recommend it to anyone.. @abidlabs

**Comment by abidlabs** [comment]
We've started to look into this, but it's been tricky to figure out how to solve this. Can you share the workaround you've used @ValentinKoch -- might give us some ideas

**Comment by ValentinKoch** [comment]
Hi @abidlabs ,
happy to share although I dont know if its useful for you. How I handle it now is that I create an upload html form where people can upload to an external server (in my case AWS S3). I save the filename on the client side as a gradio State and make sure its unique (hash/timestamp e.g.). After it has uploaded the user has to interact (press a run button), together with the unique filename we can download and processes the file from the AWS server. I catch errors that appear if file is not yet uploaded and users does an action.

**Comment by abidlabs** [comment]
Can confirm that this is still an issue in `3.17.1` with a very simple demo:

```py
def test(x):
    return x.name
    
with gr.Blocks() as demo:
    inp = gr.File(label="Input")
    vis_out=gr.File(label="output")
    with gr.Row():
        btn = gr.Button("Run")
    btn.click(fn=test, inputs=[inp], outputs=[vis_out])

demo.launch() 
```

**Comment by alvindaiyan** [comment]
I don't think the issue is resolved, prefer to upload file to other service directly, e.g. AWS s3. Can we have a toggle option to disable the default upload behavior for the File upload?

**Comment by abidlabs** [comment]
@alvindaiyan this seems out of scope for a core Gradio component. But we are working on a way to create customizable components, and this could be a good use case for that.
