### ISSUE TITLE
Programmatically run performance tests on queue

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2422]
As part of debugging why the queue is getting stuck (e.g. #2374 #2399 #2420 ) we've been running a benchmark script that tests how long the queue takes to process 1000 requests in a space that has image, audio, video, and text components.

We should enable devs to run these tests programmatically from github actions. Might be good to get in the habit of running these tests whenever we test a new queue implementation or when we do a new release.

**Comment by abidlabs** [comment]
Thinking about adding this as a non-required test (since it can be long-running)

**Comment by freddyaboulton** [comment]
Agreed about it not being required!

I think reporting the average latency (with some other summary statistics maybe) for the branch compared to main would suffice. And we can decide whether or not it passes.

Something like this maybe:

Component | Main | PR | 
--------------|-------|-----|
Video| 10.2 | 10.3 |
Audio | 9.8 | 9.9|
........|......|....|
