### ISSUE TITLE
iOS 16 keyboard lag when inputting text after generating

### ISSUE THREAD

**Issue by Vanceagher** [gradio-app/gradio#2424]
Whenever I use a Gradio interface on my iPhone the input box for text lags my keyboard but this only happens after generating something, and reloading the page fixes it. I am not sure what might be causing this, it has happened on HuggingFace and even my own hosted interfaces and I have not seen anyone else mention this.

**Comment by abidlabs** [comment]
Hi @Vanceagher, indeed we haven't heard this feedback before. Can you provide a link to a Space where you're experiencing this? Also which iOS version?

**Comment by Vanceagher** [comment]
I cannot at the moment as I am using an interface that is being hosted on
my personal computer but I will try to find the issue somewhere on
HuggingFace and send it when I find it. I am on iOS 16.0.2 and using Safari.

**Comment by pngwn** [comment]
A sample repo that we can run locally would also be a good reproduction. Doesn't have to be a space.

**Comment by Vanceagher** [comment]
The repo I am using and noticed the Gradient lag in is Stable Diffusion
WebUI
https://github.com/AUTOMATIC1111/stable-diffusion-webui

**Comment by abidlabs** [comment]
Going to close this. @Vanceagher feel free to reopen if you have a minimal example we can run locally or a Space you can link to. Thank you!
