### ISSUE TITLE
Mask object is not returned for an image with color-sketch=True

### ISSUE THREAD

**Issue by PouriaRouzrokh** [gradio-app/gradio#2425]
### Describe the bug

Hi.

According to the docs for the "image" component, a {dict} with keys `image` and `mask` should be passed as the input of the component if the "sketch" tool is selected. Naturally, the users should expect the same behavior when the "color-sketch" tool is selected, but the component only returns a single image object instead of a dictionary. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

input_img = gr.Image(tool='color-sketch', type='numpy', label='Input image', source='upload').style(height=240)

### Logs

```shell
input_img = gr.Image(tool='color-sketch', type='numpy', label='Input image', source='upload').style(height=240)
```

### System Info

```shell
3.4.1
```

### Severity

blocking all usage of gradio

**Comment by pngwn** [comment]
This isn't a bug, it is by design. We found that the most common usecase for color sketches was not as a separate image and mask but as a single composite image. 

What is your usecase?

**Comment by PouriaRouzrokh** [comment]
> This isn't a bug, it is by design. We found that the most common usecase for color sketches was not as a separate image and mask but as a single composite image.
> 
> What is your usecase?

Thank you for your quick reply. Well, our team has developed an inpainting algorithm which receives an input image, and a multi-channel mask. As the mask is multi-channel, then we need to feed it separately than the original image (like how the sketch tool work in gradio); yet this is not possible with the color-sketch tool.

**Comment by pngwn** [comment]
Do you need each channel as a separate image or just a single image will all masks?

**Comment by KIMGEONUNG** [comment]
I also strongly need the feature @PouriaRouzrokh described. In my case, there is an two use case

The first one is the user-guided colorization task. In this case, the mask should be four channel image, i.e., RGB + alpha. RGB is for colors painted and alpha for the pixels painted. 
<img src=https://user-images.githubusercontent.com/32098205/206690320-d56def7a-dd61-4279-a2ab-ccf57300f708.png width=300>

The second is the semantic image generation. In this case, separated color channels should be needed. 
<img src=https://user-images.githubusercontent.com/32098205/206688598-4edd451c-cb9b-4278-afff-1ca607aafd8e.png width=400>

I hope the feature would be added to Gradio.

**Comment by pngwn** [comment]
This is pretty easy to implement but unfortunately would be a breaking change, so we will need to discuss the best approach. 

@abidlabs This is the thing we told ourselves not to worry about when we were designing the API :D

**Comment by universewill** [comment]
> This is pretty easy to implement but unfortunately would be a breaking change, so we will need to discuss the best approach.
> 
> @abidlabs This is the thing we told ourselves not to worry about when we were designing the API :D

Hi, how is it going now? i also need this feature.

**Comment by abidlabs** [comment]
Hi @universewill because this is a breaking change, we'll need to implement it in 4.0, which is likely a few months out

**Comment by Vrroom** [comment]
Hi @abidlabs, let's say I want to make this change in my fork of gradio. How would I go about doing it? 

Looking forward to hearing from you. Thanks a lot for this lovely library!

**Comment by Ra1Nik** [comment]
Hi @abidlabs, I was looking into this recently as I am really in a need for this feature, so I was thinking about a workaround: saving the image locally when uploaded to the platform.

`def upload_fn(image):
    # save the image locally
    return

with gr.Blocks() as x:
    a = gr.ImagePaint()
    a.upload(upload_fn, a)`

but doing that no objects are passed to the `upload_fn`. I guess because the images is only passed to the component after a button is clicked. Is there a workaround to this? Like a way to click a hidden button when uploading the image? Thanks!
