### ISSUE TITLE
How to use gr.Carousel and gradio.mount_gradio_app

### ISSUE THREAD

**Issue by tt0203** [gradio-app/gradio#2426]
I can't find any example about gr.Carousel in https://gradio.app/docs/
When I read the documentation about the component, I found it.
https://github.com/gradio-app/gradio/blob/main/gradio/components.py
else,gradio.mount_gradio_app
About Routing Settings,I found that the official example cannot be run in the huggingface.
https://huggingface.co/spaces/changxin/test2/blob/main/app.py

**Comment by freddyaboulton** [comment]
Hi @tt0203 ! The Carousel component is deprecated. We will remove it shortly 

 I can't open that `app.py` file you shared. You need to serve your app on port 7860 to host a gradio app on HF spaces though.
