### ISSUE TITLE
node editor

### ISSUE THREAD

**Issue by Ehplodor** [gradio-app/gradio#2429]
**Is your feature request related to a problem? Please describe.**  
There is no "node editor" in gradio.

**Describe the solution you'd like**  
A Blender-like node editor please. That would be useful in creating and sharing new user-defined pipelines

**Additional context**  
Thank you

**Comment by abidlabs** [comment]
Hi @Ehplodor I'm not familiar with Blender or a "node editor". Can you please provide a more detailed description of what you'd like to be able to do with Gradio?

**Comment by pngwn** [comment]
Flow charty kind of thing: 

![](https://blenderartists.org/uploads/default/original/4X/3/6/7/367730d8ebf527d9832845f6ec971738aaa73bf9.png)

**Comment by Ehplodor** [comment]
Thank you @pngwn for the screen capture.

Blender node editor : https://docs.blender.org/manual/en/2.79/editors/node_editor/introduction.html

See also https://github.com/paceholder/nodeeditor for a similar although different implementation of node edition (leaning more toward computations in the examples) 

More for programming & machine learning : https://nodered.org/

**Comment by abidlabs** [comment]
So just to understand, you're proposing a no-code UI to assemble Gradio apps?

**Comment by Ehplodor** [comment]
> So just to understand, @Ehplodor you're proposing a no-code UI to assemble Gradio apps? 

I believe you nailed it better than I could explain 👍 sorry I'm nonnative english speaker.

And such "pipeline" could be encapsulated and shared between users and itself integrated into a higher level pipeline. This would be killer feature IMHO.

Context : I Discovered gradio a few weeks ago thanks to the amazing repositories available using gradio. Lacking easily shareable user-defined gradio pipelines IMHO. That would help artists but non programmers share their knowledge and experience reproducibly and easily.

**Comment by pngwn** [comment]
Oh, I thought this was a component request. 

This is definitely something we have discussed internally but obviously requires a lot of work.

More prior art:
- https://nodes.io/
- https://docs.unrealengine.com/5.0/en-US/blueprints-visual-scripting-in-unreal-engine/

**Comment by Ehplodor** [comment]
A relevant promising (IMHO) current project based on Stable Diffusion : https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/2028

**Comment by devbrones** [comment]
Maybe this could be accomplished using Litegraph.js? I'm trying to embed this very functionality into a gradio app that i am building for a client, what i have managed to do so far is have a custom html block that has a canvas, then i am injecting the litegraph js/css using fastapi. Then what i plan on doing is editing the functionality of litegraph that can get all nodes as json to pass it to a custom endpoint defined in fastapi. would be a lot better however with this functionality built into gradio however ;)

Maybe something like [Svelvet](https://www.svelvet.io/) could be integrated?

**Comment by abidlabs** [comment]
I think this would be a great case for a custom component!

we've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. 

Here's an example of a Gradio custom component: https://github.com/PhyscalX/gradio-image-prompter -- it lets you upload images and process points or draw boxes on top of the image.

If you'd like to create your own, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.
