### ISSUE TITLE
Better messaging/UI for a broken embedded demo

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#2432]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Currently if an embedded gradio demo is broken it will just not show up at all on the page. Which is a bit jarring and confusing for users of the page. for example: 

![Screen Shot 2022-10-11 at 2 32 39 PM](https://user-images.githubusercontent.com/9021060/195202522-367fb1d2-6668-493e-abf4-dca2d2404317.png)

**Describe the solution you'd like**  
When the demo is broken or can't embed, etc, it should display some sort of message indicating that. This can easily be done for the website but should be done on the library side so that it works everywhere gradio demos are embedded.

**Comment by pngwn** [comment]
We need handle errors better in order to do this (i think) because we need to know _when_ to show such a message. related to #2441

**Comment by abidlabs** [comment]
Potentially related: https://github.com/gradio-app/gradio/issues/1957
