### ISSUE TITLE
Can you support the default text or image in textbox and gallery?

### ISSUE THREAD

**Issue by joytianya** [gradio-app/gradio#2439]
I want to fill in the default text or images in the Gradio APP. Does the current interface support this implementation? If not, can you support it?

**Comment by abidlabs** [comment]
Hi @joytianya, as a larger remark, for specific questions like this, [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [Discord](https://t.co/JKepTfXraQ) is a more suitable venue, as GitHub issues is for bugs and feature requests. 

To answer your question, yes it is possible. For example, you could do something like:

```py
gr.Interface(lambda x:x, gr.Textbox("Default Value"), gr.Textbox())
```
