### ISSUE TITLE
Various performance issues

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#2442]
### Describe the bug

Some frontend perf issue are seriously degrading the gradio experience. Problems range from things just being a bit massive to infra that needs improving and other stuff. 

This is pretty bad, some of it is very hard to workaround.

Bit of a dump, will cleanup later, might split into other issue but want to track for now.

### infra
- Serve assets via CDN
- compress assets

### lib

- lazy load gradio (load when on screen)
- lazy load language definitions
- reduce dependency size for certain components
- lazy load component variants (image editor vs static image viewer)

Get metrics to a reasonable place

## Prevent regressions

- bundle size metrics/ regressions.
- image snapshots (styling refactor for theming)
- performance testing to measure change
  - small, medium, large demo apps, lighthouse testing
  - measure change over time/ deviation from standard
  - use gradio docs as benchmark, if we can get that good then we can have some confidence

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

every gradio app

### Screenshot

no

### Logs

```shell
no
```

### System Info

```shell
stop asking me questions
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @pngwn can we revisit this issue? Are these still issues in the library? It would be good to create individual issues, and classify them as bugs/enhancements as needed

**Comment by freddyaboulton** [comment]
Just gonna close cause I think this is fixed by SSR 😉 If not, let's open a new issue with more specific criteria!

**Comment by pngwn** [comment]
Mostly although there are a few other things we need to do. I'll open new issues for those though.
