### ISSUE TITLE
return ValueError instead of raise ValueError in convert_component_list_to_dict ?

### ISSUE THREAD

**Issue by vzakharov** [gradio-app/gradio#2443]
### Describe the bug

I’m not much aware of how this code works, but it seems like “raise” would make more sense here rather than “return”? Esp. given that it is used just below in the elif part?

![image](https://user-images.githubusercontent.com/188197/195418366-7189487d-c123-4374-b66d-b0a5185ab176.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

n/a

### Logs

```shell
n/a
```

### System Info

```shell
n/a
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @vzakharov you are right! Nice catch -- would you like to open a PR to fix this?

**Comment by vzakharov** [comment]
> Hi @vzakharov you are right! Nice catch -- would you like to open a PR to fix this?

Just did. It’s embarrassing, but it’s my first PR ever (I’ve only ever written code alone), so sorry if I messed something up! (And I think I did, skipping all the details requested when submitting it.)

**Comment by abidlabs** [comment]
Woohoo! Congrats on your first PR :)

It looks great, I just added a line in our changelog to credit you with the changes. The only thing I might have done differently is add a new test to our test suite to ensure that your change doesn't accidentally get reverted in the future. But it's not too critical for a small fix like this. All of the other tests in the test suite pass so you're good there!
