### ISSUE TITLE
[Feature question] Can my model output a set of intervals (or sliders)?

### ISSUE THREAD

**Issue by swamiviv** [gradio-app/gradio#2446]
I have a ML model that outputs an image + interval of values on the real line given an input image. For eg: If X is an input, the output might be (Y, [-0.5, 0.5]), where Y is another image.

Is there a way to visualize this output as an image-slider combo in gradio ?

The expected output is then that the user gets the control of the slider, and when they interact with it, the output Y changes accordingly (based on another predict function, for instance)

Is there already a way to do this? Any tutorial link or even a pseudocode on how to set this up will be appreciated.

**Comment by abidlabs** [comment]
Hmm interesting. Currently, we don't support "ranges", we only have individual sliders. 

What about using two sliders, one to represent the "min" and the other to represent the "max"? If either of them change, it would be possible to trigger a rerun of the output.

**Comment by fffiloni** [comment]
@swamiviv would you take time to draw a schema about what you do expect as an output ? 

I tried to figure out what you described, but i think a sketch ✍️ could be a good starter point to think about your need :)

**Comment by swamiviv** [comment]
Hi @fffiloni and @abidlabs ! thanks for a quick response and sorry about the delay on my side. I am attaching a schema here:

![slider_output_schema](https://user-images.githubusercontent.com/6654072/195623572-744fad36-c5db-4aaa-81c9-7aa0c09c1ede.png)

1. Given an image, f1 outputs several ranges, I am representing each by a slider. 
2. The user then "interacts" with the slider, essentially picking some values they care about. 
3. This set of picked values are then output to another predictor, that outputs an image.
4. The user can then optionally change the slider values to see how the image changes.
5. The interaction in step (2) is optional, since f1 outputs a fixed value for each slider, which will be used by default, in the absence of any interaction.

Please let me know if something is unclear!

**Comment by fffiloni** [comment]
Thank you @swamiviv now i understand much better ! 

Let me think about it when i have time, but what i would recommend is that each time the slider value change, you can then call the gradio API to generate a new iteration. 

I think your needs goes beyond the purpose of what gradio can be useful for. 

You have to think out of the box, on how to use gradio, and gradio apis in particular, to create an interface that can benefits from the gradio tools :) 

I think @abidlabs will follow me on this, and if you need help to build a proto, please ask for further hints ;)

**Comment by abidlabs** [comment]
Hi @swamiviv this is pretty much possible except for the fact that we don't accept ranges in Slider, so you'd have to have separate Sliders for minimum and maximum. Here's a simple example to get you going:

```py
import gradio as gr

def generate_from_image(im):
    return im, 1, 5

def generate_from_image_and_sliders(im, mn, mx):
    return im

with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column():
            im = gr.Image()
            btn = gr.Button()
        with gr.Column():
            im2 = gr.Image()
            mn = gr.Slider(label="Minimum")
            mx = gr.Slider(label="Maximum")
            
        btn.click(generate_from_image, im, [im2, mn, mx])
        mn.change(generate_from_image_and_sliders, [im, mn, mx], im2)
        mx.change(generate_from_image_and_sliders, [im, mn, mx], im2)

demo.launch()
```

which produces this:

<img width="578" alt="image" src="https://user-images.githubusercontent.com/1778297/195771927-d3321c19-6cc8-4768-93e5-4848622945dd.png">

**Comment by abidlabs** [comment]
Feel free to close if this answers your question or let us know if we can help in any other way!

**Comment by swamiviv** [comment]
This is super helpful! Definitely answers my question. I am going to try it for my application and I will close this comment once I am able to get a working prototype. If I hit a roadblock, I will post subsequent queries in this thread. Thanks!

**Comment by abidlabs** [comment]
Hi @swamiviv I'd like to close this issue while you look into getting a working prototype since we can't work on this in the meantime. But feel free to reopen if you have other related questions!

**Comment by crypdick** [comment]
There is a custom RangeSlider implemented here: https://github.com/freddyaboulton/gradio-range-slider(commenting here since this issue is the top Google result)

**Comment by freddyaboulton** [comment]
Thanks @crypdick !
