### ISSUE TITLE
Image within dataframe 

### ISSUE THREAD

**Issue by yuanqing-wang** [gradio-app/gradio#2451]
- [x ] I have searched to see if a similar issue already exists.

Greetings, 

Would it be possible to display images within dataframe? For example, if one entires a url in one column and the other column would be the corresponding image?

Many thanks,

**Comment by abidlabs** [comment]
Hi @yuanqing-wang, yes this is supported by setting the `datatype` parameter of the `gr.Dataframe()` component. If you set it to `markdown`, you can embed images using standard markdown notation. 

Here is an example:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Dataframe([["abc", "some *italicized* content", "![](file=lion.jpg)"]], datatype="markdown")
    
demo.launch()
```

which produces the following:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/1778297/195483638-47670d92-31b1-4700-b629-d9ae71c5b46b.png">

Feel free to close the issue if this answers your question, or ask about anything else!

**Comment by yuanqing-wang** [comment]
this looks great. thanks so much!
