### ISSUE TITLE
Does gradio support xml output ?

### ISSUE THREAD

**Issue by jyotiyadav94** [gradio-app/gradio#2458]
I was looking through the gradio documentation I couldn't find an example for XML output for radio 
I ould like to know if it supports XML based output

**Comment by pngwn** [comment]
> Does gradio support xml output ?

Not directly, no. Although it may be possible to do something more custom to get it working.

Just so we have the necessary context, can you explain your use-case in more detail please?

**Comment by abidlabs** [comment]
Going to close for lack of followup. @jyotiyadav94 please feel free to reopen if you have a specific bug or feature request
