### ISSUE TITLE
Audio play is silent on iOS

### ISSUE THREAD

**Issue by drscotthawley** [gradio-app/gradio#246]
Hi, this is more of a feature request than a bug: it would be great if your audio demos worked on iOS! 🙏🥺  
iOS requires a little bit of extra code (user authentication request) in order for audio to be heard. 

Currently your audio demos, e.g. https://gradio.app/hub/AK391/neural-waveshaping-synthesis, are silent when I press the play button on iOS (Safari or Chrome).

This is a common problem that affects lots of websites. Here’s a thread discussing this: https://stackoverflow.com/questions/31776548/why-cant-javascript-play-audio-files-on-iphone-safari.  This “feature” was intended by Apple to prevent auto-play, but it ends up affecting even sites like yours where the user presses a play button.

It should be pretty simple to fix, since having the user press play could be the user interaction as far as Apple’s requirements are concerned. But
I’m not sure which part of your code needs to be modified, which is why I’ve created an Issue rather than a Pull Request. ;-)

**Comment by aliabid94** [comment]
Taking a look, thanks for pointing this out.
