### ISSUE TITLE
No docs sidebar on mobile makes them really difficult to navigate 

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#2464]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
The docs are very difficult to use on mobile because there is no navigation menu. 

**Describe the solution you'd like**  
A way to pop the menu on and off as needed without cluttering the space. 

**Additional context**  
Cool example of docs that do that well: https://vitejs.dev/guide/

**Comment by abidlabs** [comment]
Recently struggled with this 😅
