### ISSUE TITLE
Custom css doesn't seem to do anything

### ISSUE THREAD

**Issue by skoetje** [gradio-app/gradio#247]
I'm trying to run the app with a custom css, but when launching it seems it ignores the css. Also when I create a non-working template I don't see any error at all. Is this expected behavior? When I check interface.py I also don't see the css being used anywhere in the launch function. Do you have a working example somewhere that I can check out? Kind regards

**Comment by aliabid94** [comment]
Please update to gradio>=2.2.1, there was a bugfix relating to css in that version. Then you can pass any css. You may need to use !important in case your css clashes with the theme.

Here's an example:

```python3
import gradio as gr
def greet(name):
  return "Hello " + name + "!!"
iface = gr.Interface(fn=greet, 
  inputs="text", 
  outputs="text", css="""
body {
  background-color: red
}
.input_text input {
  background-color: green !important;
}
""")
iface.launch()```

**Comment by skoetje** [comment]
The upgrade helped, thanks! Now the code in interface.py makes a lot more sense as well.
