### ISSUE TITLE
Using the "x" button opens file load dialog automatically.

### ISSUE THREAD

**Issue by mezotaken** [gradio-app/gradio#2476]
### Describe the bug

User clicks "x" button on loaded image -> Element is cleared, then load dialog pops up, the usual one for this ui element when clicked while it is empty. 
If this dialog is cancelled then the element can be used as usual, else it becomes impossible to load any image until after page reload. Drag&Drop use fixes it though. Obviously this dialog shouldnt open in the first place.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

It may be reproduced right on your own demo page under section "An Image example": https://gradio.app/getting_started/#an-image-example
But it originated here: [stable-diffusion-webui/2963](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2963)
It definitely happened somewhere in transition from gradio 3.4.1 to gradio 3.5.

### Screenshot

![GIF 17 10 2022 21-16-34](https://user-images.githubusercontent.com/32306715/196253349-b2194efd-28e8-4246-a509-3a61d6e41fb5.gif)

### Logs

Sadly, there were no errors logged when stable-diffusion-webui mentioned in reproduction was launched by me with --gradio-debug argument. This argument is used as a value for a wrapper call of gradio.Interface.launch().

### System Info

```shell
Gradio 3.5, Windows 10, Google Chrome
Gradio 3.5, Windows 11, Firefox
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Can confirm the problem! @dawoodkhan82 would you be able to take a look?
