### ISSUE TITLE
Expose `js` parameter and add it to documentation

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#2479]
Currently, all `gradio.Blocks` event triggers include a special `_js` parameter that is used within the library for things like the Clear button in a `gradio.Interface`. We don't really have any docs around it since it is not intended for public use. However, there is growing interest in using it (for example, e.g. it allows #2173), so I think we should rename it to `js` and expose it as a regular parameter. 

I remember we had punted some discussion like:
* Do we really want users writing javascript functions as strings in Python or can we provide a better DX?
* What should the method signature of the javascript function be? @pngwn had some thoughts here

**Comment by freddyaboulton** [comment]
This got done by @dawoodkhan82 in the v4 branch!
