### ISSUE TITLE
Opening Gradio inside jupyter notebook which his hosted in a docker container

### ISSUE THREAD

**Issue by Mcprasad** [gradio-app/gradio#248]
I have a Jupyter notebook hosted in a docker container - which is used to run my data science workloads. I would like to use gradio locally inside that jupyter notebook.. 

To expose gradio locally inside the container - I am setting the server_address as 0.0.0.0 according to the documentation.  I am able to view gradio UI in the local host but it does not open up inside jupyter.. 

any suggestions ?

![image](https://user-images.githubusercontent.com/19703489/127023478-a4114628-fc1c-4f7c-b4a6-f7569c9e8b88.png)

but if i explicitly try top open it in a browser by overriding 0.0.0.0 to local host it works.. i would like to open it right inside jupyter inside the docker container..

**Comment by Mcprasad** [comment]
![image](https://user-images.githubusercontent.com/19703489/127023433-19700313-6f38-483b-8649-aa9da54684ff.png)

**Comment by abidlabs** [comment]
Hmm. Can you try setting `server_address` to be `localhost` and see what happens?

**Comment by Mcprasad** [comment]
@abidlabs - Yes, i tried that too.. same error.. any suggestions ?

**Comment by abidlabs** [comment]
Unfortunately, I can't seem to reproduce this on my end. When I test it on a hosted jupyter notebook, I observe the following behavior:

- If port forwarding is set up correctly in docker container, then the interface appears in the notebook
- If port forwarding is not set up, then the interface doesn't appear in line or in a new tab. 

In the 2nd case, you can still see the interface inline by setting `share=True`. Perhaps try that with a simple function to see if that solves your issue? If your model is too sensitive to set public sharing, you can set up a username/password by using the `auth` parameter in the `Interface` class. Or you can try [Gradio Private](https://gradio.app/introducing-private), in which case, we set up a secure on-premise version of Gradio for you.

**Comment by aliabid94** [comment]
Closing due to lack of response. Feel free to reopen @Mcprasad
