### ISSUE TITLE
Make render() return self

### ISSUE THREAD

**Issue by vzakharov** [gradio-app/gradio#2484]
Not a big deal, but when I create an output before rendering it as described [here](https://www.gradio.app/controlling_layout/#defining-and-rendering-components-separately), it would be handy if I could chain further event handlers with it, e.g.

```
input = gr.Textbox(label='Enter something')

# ...

with gr.Blocks() as ui:
  input.render().change(
    # ...
  )
```

Currently `render` does not seem to return any value, so it wouldn’t be that much of a hassle to add `return self` in the end.

**Comment by Raul9595** [comment]
Hi, can I take this up?

**Comment by abidlabs** [comment]
Hi @Raul9595 sure thing! Let us know if you have any questions as you contribute
