### ISSUE TITLE
misuse display_file_name to fill the "download" attribute in template

### ISSUE THREAD

**Issue by mxi-box** [gradio-app/gradio#2485]
### Describe the bug

The _download_ attribute of _a_ element is used to provide browser with the filename. However the _display_file_name_ called here will truncate the filename longer than 30 characters, which caused broken name suffix.

A workaround is using shorter file name.

https://github.com/gradio-app/gradio/blob/f79a76ca8f6e081310c01c7cd8b2b3c13eb0c0b0/ui/packages/file/src/File.svelte#L35
https://github.com/gradio-app/gradio/blob/f79a76ca8f6e081310c01c7cd8b2b3c13eb0c0b0/ui/packages/file/src/utils.ts#L18

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I found this bug in stable diffusion webui [https://github.com/AUTOMATIC1111/stable-diffusion-webui](url)

You will get a broken download button below when you click 'Save'.

`<a href="file=C:\Users\mxi\AppData\Local\Temp\tmp8osefq6r\01002-428395022-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxbejzd3ty.webp" download="01002-428395022-xxxxxxxxxxxxxx..." class="text-indigo-600 hover:underline dark:text-indigo-300">Download</a>`

### Screenshot

![Screenshot 2022-10-18 205932](https://user-images.githubusercontent.com/35442369/196444635-5c75ead2-cd5d-4efb-acb9-036b519d5d33.png)
![Screenshot 2022-10-18 205949](https://user-images.githubusercontent.com/35442369/196444656-988451b7-7c2a-4b94-a23e-e9e0cad469ef.png)

### Logs

```shell
No logs here.
```

### System Info

```shell
gradio 3.5
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Thanks for letting us know @mxi-box. @dawoodkhan82 would you be able to take a look into this?

**Comment by abidlabs** [comment]
It looks like this is fixed now, so I'll go ahead and close this. 

To test:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.File("long file name....")
    
demo.launch()
```
