### ISSUE TITLE
Docs on status tracking?

### ISSUE THREAD

**Issue by vzakharov** [gradio-app/gradio#2489]
I must be dumb, but I can’t find any info on how to use status tracking, neither in the Docs nor in Getting Started. Can you please point me to the right place?

**Comment by abidlabs** [comment]
When you say status tracking, do you mean the `StatusTracker` component or a more general concept?

**Comment by vzakharov** [comment]
> When you say status tracking, do you mean the `StatusTracker` component or a more general concept?

Yes, so I have a button that, say, makes a generation. I want the user to see that the generation is in progress. (Currently, the UI just stays the same while the model is running.) I see that, for example, `button.click()` has a parameter called `status_tracker`. I’m assuming that’s what I need, but I’m not sure.

**Comment by vzakharov** [comment]
> Doesn't the output component show the loading indicator?

Oh, my output is of the `{ generation_box: gr.update( visible = True ) }` kind, so I’m assuming I’m not seeing it because it’s not visible until the generation is finished.

I will add a separate component for indication, but, just out of curiosity, what is the `status_tracker` parameter meant to do?

**Comment by abidlabs** [comment]
Got it, makes sense. Sooo I actually think the `status_tracker` parameter has been deprecated, but @aliabid94 should be able to confirm

**Comment by vzakharov** [comment]
I see. Have you seen `stable-diffusion-webui`? When the generation is
running, there is a progress bar showing the completion percentage. How do
they make this possible?

**Comment by vzakharov** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui

**Comment by aliabid94** [comment]
So by default, the status-tracker will be shown on all output components of a function. If those outputs are hidden until the completion of the method, I suppose you wouldn't see any progress animation. Working on the ability to have a page-level animation as well that you can use instead, will keep you updated.

**Comment by vzakharov** [comment]
So basically the status_tracker parameter points to the component that
should show the progress animation, right?

Do you have any clues to as to how stable-diffusion-webui enables more
detailed status tracking (with percentage, ETA & stuff)?

**Comment by abidlabs** [comment]
Good question @vzakharov. It looks like there is a lot of custom [css](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/737eb28faca8be2bb996ee0930ec77d1f7ebd939/modules/ui.py#L310) & [logic](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/737eb28faca8be2bb996ee0930ec77d1f7ebd939/modules/ui.py#L291) to make that happen. 

Definitely not something that is supported out of the box with `gradio`, but something we have been thinking about. You can see and follow the original issue here: #340 

I think we can close this issue @vzakharov?

**Comment by abidlabs** [comment]
Closing as I believe the issue has been clarified above
