### ISSUE TITLE
Add support for images in chatbot component

### ISSUE THREAD

**Issue by dawoodkhan82** [gradio-app/gradio#2498]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
To support the multimodal project, the demo requires support for something like the image below.

<img width="606" alt="Capture d’écran 2022-10-19 à 11 05 07 AM" src="https://user-images.githubusercontent.com/12725292/196763541-aa6a06a5-ec50-41d3-9505-6ca9f80f71bd.png">

**Describe the solution you'd like**  
Add support for markdown in chatbot

**Additional context**

**Comment by abidlabs** [comment]
Cool! I suggest we support Markdown more generally?

**Comment by abidlabs** [comment]
Cool, yeah probably makes sense that people want to input an image more easily then typing out the Markdown for it

**Comment by cmccomb** [comment]
Markdown support for the chatbot component would be AWESOME!
