### ISSUE TITLE
Placeholder broken?

### ISSUE THREAD

**Issue by flo-joe** [gradio-app/gradio#251]
The placeholder option is not working for me. The text never displays in the text input. I'm not seeing it as an attribute when I inspect the HTML element.

I'm using the latest version at the moment (2.2.6). I tried multiple machines with same result. I even tried using a basic example provided in the README file and it also fails there.

**Comment by aliabid94** [comment]
Thanks for pointing this out! just fixed this - can you try again with 2.2.7?

**Comment by flo-joe** [comment]
Works great now! Thanks for the quick fix!!!

**Comment by flo-joe** [comment]
Fixed in 2.2.7
