### ISSUE TITLE
How to hide gradio-flag

### ISSUE THREAD

**Issue by yuanjie-ai** [gradio-app/gradio#2510]
![image](https://user-images.githubusercontent.com/20265321/197183333-198f490a-e368-4e0b-832f-0504e703b849.png)

**Comment by abidlabs** [comment]
It looks like you mean the footer. You can do this by supplying custom CSS to the `css` parameter in `gradio.Blocks()` or `gradio.Interface()`. Something like: `footer{display:none !important}` should work.

**Comment by Franck-Dernoncourt** [comment]
Example based on abidlabs' answer:

```
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text", css="footer{display:none !important}")

demo.launch()
```

**Comment by bitsnaps** [comment]
> It looks like you are asking about hiding the footer. You can do this by supplying custom CSS to the `css` parameter in `gradio.Blocks()` or `gradio.Interface()`. Something like: `footer{display:none !important}` should work.

This will hide the copyright footer, not the button at the moment (current version), the flag button has the id:`#component-11` at run time rendering which can be hidden using the same way.

**Comment by chunhunghan** [comment]
> > It looks like you are asking about hiding the footer. You can do this by supplying custom CSS to the `css` parameter in `gradio.Blocks()` or `gradio.Interface()`. Something like: `footer{display:none !important}` should work.
> 
> This will hide the copyright footer, not the button at the moment (current version), the flag button has the id:`#component-11` at run time rendering which can be hidden using the same way, but I don't think this is the best way to do that anyway.

@bitsnaps  You can use https://www.gradio.app/guides/using-flagging gradio.Interface(allow_flagging="never")

**Comment by FarmerJohnLYH** [comment]
demo.close()
demo = gr.Interface(fn=greet, inputs='text', outputs='text', 
                    flagging_options=[], # 设置为空
                    css="footer{display:none !important}")
demo.launch()
