### ISSUE TITLE
Taking folder as input

### ISSUE THREAD

**Issue by konam20513** [gradio-app/gradio#2515]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I could not find an option to input the images folder for bulk image identification to get their statistics.

**Describe the solution you'd like**  
Adding taking folder as an input option.

**Comment by abidlabs** [comment]
Hi @konam20513, in order to do upload a directory of images, please use the `File` component with `file_count` set to `directory`. Read more about the `File` component here: https://gradio.app/docs/#file

**Comment by hiyyg** [comment]
@freddyaboulton Thanks. But this will upload all files under the folder. What I want is just getting the path without uploading any files. Is there any way to achieve that?

**Comment by abidlabs** [comment]
Hi @hiyyg that is not currently possible, but we may end up creating a new component for this: see #3681. Feel free to add to that issue so that we can ensure that your use case is covered

**Comment by abidlabs** [comment]
Hi @hiyyg that is not currently possible, but we may end up creating a new component for this: see #3681. Feel free to add to that issue so that we can ensure that your use case is covered.

**Comment by henryruhs** [comment]
@abidlabs I suggest we break down File to FileUpload and FileDialog and DirectoryDialog. FileDialog and DirectoryDialog do not create temporary files and can be use as a Entrypoint for Image and Video.

**Comment by J4BEZ** [comment]
@joystay Wow, this is just what I want!!
First of all, Thank you very much for sharing your great code🙇‍♂️🙇‍♂️

But I found a very small problem that I can't afford,
So I like to ask a favor for this.
 
When I launch with share=True argument and access the public link generated from gradio in the client desktop

when I click the button 'Browse' on the client,
the file select manager UI appear in server(where I ran gradio) not in client(where I access the generated public link)

How can we solve this

Thanks for reading this comment, and hope you have a peaceful-day🙌🙌

**Comment by joytsay** [comment]
yes @J4BEZ this is server side, 
if you want it as client side you have to wait for gradio to add it,
which i think they are reluctant to, 
i read somewhere that web apps have security issues if you allow this ; )

**Comment by J4BEZ** [comment]
@joytsay Oh.. I see😥😥

until gradio team adds a way dir path on client side,
It would be good to find another creative way for me😥

I appreciate for your thoughtful consideration😊
Hope you had a peaceful day🙌🙌

**Comment by sanmilano** [comment]
I'm using a Gradio app that has this feature where you can select a folder and instead of writing the path into an input text field. Is there any component available for this or does this project use a custom component made by them? The app is Kohya SS
![image](https://github.com/gradio-app/gradio/assets/617568/5449248d-9cd7-43b9-8060-2b1add94375e)

**Comment by GrunCrow** [comment]
> I'm using a Gradio app that has this feature where you can select a folder and instead of writing the path into an input text field. Is there any component available for this or does this project use a custom component made by them? The app is Kohya SS ![image](https://private-user-images.githubusercontent.com/617568/306686397-5449248d-9cd7-43b9-8060-2b1add94375e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDkyMTIsIm5iZiI6MTcyMTIwODkxMiwicGF0aCI6Ii82MTc1NjgvMzA2Njg2Mzk3LTU0NDkyNDhkLTljZDctNDNiOS04MDYwLTJiMWFkZDk0Mzc1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QwOTM1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjk2YmY1NzliNTI1NWExZjA2MmI5Zjk2YWNjNjAzZTYyYzM2YzFlY2VlY2Q5ZTE5OGJiNjBkMWYwYmZmM2FmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5aDxnBGfwmkekA8OSNTvySLOmGx6cFYOSEzqSUUZrZk)

Did you find out anything aboyt that?

**Comment by MalumaDev** [comment]
```
from tkinter import Tk, filedialog
import gradio as gr

def get_folder_path(folder_path: str = "") -> str:
    """
    Opens a folder dialog to select a folder, allowing the user to navigate and choose a folder.
    If no folder is selected, returns the initially provided folder path or an empty string if not provided.
    This function is conditioned to skip the folder dialog on macOS or if specific environment variables are present,
    indicating a possible automated environment where a dialog cannot be displayed.

    Parameters:
    - folder_path (str): The initial folder path or an empty string by default. Used as the fallback if no folder is selected.

    Returns:
    - str: The path of the folder selected by the user, or the initial `folder_path` if no selection is made.

    Raises:
    - TypeError: If `folder_path` is not a string.
    - EnvironmentError: If there's an issue accessing environment variables.
    - RuntimeError: If there's an issue initializing the folder dialog.

    Note:
    - The function checks the `ENV_EXCLUSION` list against environment variables to determine if the folder dialog should be skipped, aiming to prevent its appearance during automated operations.
    - The dialog will also be skipped on macOS (`sys.platform != "darwin"`) as a specific behavior adjustment.
    """
    # Validate parameter type
    if not isinstance(folder_path, str):
        raise TypeError("folder_path must be a string")

    try:
        root = Tk()
        root.withdraw()
        root.wm_attributes("-topmost", 1)
        selected_folder = filedialog.askdirectory(initialdir=folder_path or ".")
        root.destroy()
        return selected_folder or folder_path
    except Exception as e:
        raise RuntimeError(f"Error initializing folder dialog: {e}") from e


def create_folder_ui(path="./"):
    with gr.Row():
        text_box = gr.Textbox(
            label="path",
            info="Path",
            lines=1,
            value=path,
        )
        button = gr.Button(value="\U0001f5c0", inputs=text_box, min_width=24)

        button.click(
            lambda: get_folder_path(text_box.value),
            outputs=[text_box],
        )

    return text_box, button
```

**Comment by EndlessBingo** [comment]
@MalumaDev Your answer is the best!
