### ISSUE TITLE
`Audio.change` event handler does not seem to work

### ISSUE THREAD

**Issue by vzakharov** [gradio-app/gradio#2518]
### Describe the bug

I have a `gr.Audio` component that displays a WAV file. When that audio is changed, I want to change a `gr.Plot` component that displays its waveform. It works separately:
![image](https://user-images.githubusercontent.com/188197/197757974-ffc03180-b4b7-4cc5-9a50-b4b0a6fa98f5.png)

However, in this case the Audio and the Plot are calculated at the same time when the sample changes, which might take longer than just calculating the Audio. So I decided to only calculate the waveform after the Audio itself is changed. 

So I made this code:
```python
      def audio_change(audio):

        print(f'New audio: {audio}')
        # (further processing)
      
      UI.generated_audio.change(
        inputs = UI.generated_audio,
        outputs = UI.audio_waveform,
        fn = audio_change
      )
```

The code doesn’t work, and the “New audio” message is not logged.

I double-checked the developer console to make the audio changes. It does, both the filename and the audio itself (another question btw is what would be the input of the `audio_change` function, the filename or the numpy array? not relevant at this point though):

![3f6c05e7a8c1069e2ef69bb3bdfab536](https://user-images.githubusercontent.com/188197/197758812-2b08c18f-5b20-4ee7-b2c3-3dd659a317f9.gif)

I was wondering if maybe Audio.change event was never actually used/tested, so it doesn’t work at all?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
# Sample python code to see if Audio.change event handler works
import gradio as gr

with gr.Blocks() as ui:
  mic_input = gr.Audio()
  text_output = gr.Textbox()

  mic_input.change(
    inputs = mic_input,
    outputs = text_output,
    fn = lambda x: f'Audio changed to {x}'
  )
  
ui.launch()
```

### Logs

```shell
C:\Python39\lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\gradio\routes.py", line 298, in run_predict
    output = await app.blocks.process_api(
  File "C:\Python39\lib\site-packages\gradio\blocks.py", line 787, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Python39\lib\site-packages\gradio\blocks.py", line 682, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\Python39\lib\site-packages\gradio\components.py", line 1828, in preprocess
    sample_rate, data = processing_utils.audio_from_file(
  File "C:\Python39\lib\site-packages\gradio\processing_utils.py", line 204, in audio_from_file
    data = np.array(audio.get_array_of_samples())
UnboundLocalError: local variable 'audio' referenced before assignment
```

### System Info

```shell
gradio 3.6, Win 10, Chrome
```

### Severity

serious, but I can work around it

**Comment by vzakharov** [comment]
Apparently, no audio is loaded in line 193 of `processing_utils.py`, and, as the error is other than FileNotFoundError, it does not raise any exception and continues execution. This begs the question of why the audio is not loaded, but that’s beyond my capabilities to investigate.

```python
def audio_from_file(filename, crop_min=0, crop_max=100):
    try:
        audio = AudioSegment.from_file(filename)
    except FileNotFoundError as e:
        error_message = str(e)
        if "ffprobe" in error_message:
            print(
                "Please install `ffmpeg` in your system to use non-WAV audio file formats."
            )
    if crop_min != 0 or crop_max != 100:
        audio_start = len(audio) * crop_min / 100
        audio_end = len(audio) * crop_max / 100
        audio = audio[audio_start:audio_end]
    data = np.array(audio.get_array_of_samples())
    if audio.channels > 1:
        data = data.reshape(-1, audio.channels)
    return audio.frame_rate, data
```

**Comment by freddyaboulton** [comment]
Hi @vzakharov ! I was able to run the reproducer you shared

![audio_change](https://user-images.githubusercontent.com/41651716/199049860-b04b2995-2032-45ff-9f9d-1545cf2e709a.gif)

Do you have ffmpeg installed?

**Comment by abidlabs** [comment]
Going to close this. @vzakharov please let reopen this issue if you still have this issue even with ffmpeg.
