### ISSUE TITLE
Avoid needing to cast audio file to `int16` for `Audio` component

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#2522]
It seems that some audio files cannot be passed natively into the `Audio` component -- rather they need to be cast into `int16` before they can be played. E.g. this does not work:

```py
import gradio as gr
from datasets import load_dataset

speech_commands = load_dataset("speech_commands", "v0.02", split="test")

def generate_audio():
    example = speech_commands.shuffle()[0]
    audio = example["audio"]
    return audio["sampling_rate"], audio["array"]
    

demo = gr.Interface(fn=generate_audio, inputs=None, outputs="audio")
demo.launch()
```

whereas this does:

```py
import IPython.display as ipd

ipd.Audio(audio["array"], rate=audio["sampling_rate"])
```

Relevant internal discussion: https://huggingface.slack.com/archives/C02QZLG8GMN/p1666702652619089

**Comment by abidlabs** [comment]
Thanks for the catch @freddyaboulton!

**Comment by eervin123** [comment]
I'm not sure but it looks like this same thing is happening with `int32` formats. I'm getting the following warnings.

UserWarning: Trying to convert audio automatically from int32 to 16-bit int format.
  warnings.warn(warning.format(data.dtype))
  
  This is working, it is currently just a warning.

**Comment by Ram-Pasupula** [comment]
I am getting the below error for int8 format.

Audio data cannot be converted automatically from int8 to 16-bit int format.
