### ISSUE TITLE
Use the api_name when calling an app like a function

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2523]
- [ ] I have searched to see if a similar issue already exists.

Properly using a space like an api requires knowing the `fn_index`. If you're a downstream consumer of an app, you may not know the `fn_index` and the fn_index can change if the upstream app is refactored.

**Describe the solution you'd like**  
Would be nice to be able to do something like 

```python
demo = gr.Blocks.load("path-to-demo")
output = demo(input, api_name="prediction-route")
```

Where "prediction-route" is the api_name given to the event in the upstream space.

**Additional context**

**Comment by pngwn** [comment]
isn't this already supported via events? It is down to the app author to expose that on a per event basis rather than the consumer. When `loading`, the 'loader' shouldn't be impacting this, unless I'm misunderstanding this issue.

**Comment by freddyaboulton** [comment]
If you're hitting the api via curl or something, you can use `api_name` in the route. 

But if you load the space into python, you have to pass in the fn_index, not the api_name.
