### ISSUE TITLE
Blur events can't be batched

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2524]
### Describe the bug

The blur event does not have the batch keyword argument:

https://github.com/gradio-app/gradio/blob/main/gradio/events.py#L610

We should make sure they can be batched like any other event!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

-

### Screenshot

-

### Logs

```shell
-
```

### System Info

```shell
-
```

### Severity

annoying

**Comment by abidlabs** [comment]
There really should be a way for us to provide the same set of parameters to all of the event functions without having to duplicate the code and docs... hmm

**Comment by abidlabs** [comment]
Anyways looks like this is now fixed
