### ISSUE TITLE
Please add an option -> pass text to gallery image alt attribute

### ISSUE THREAD

**Issue by camenduru** [gradio-app/gradio#2536]
https://github.com/gradio-app/gradio/blob/5a090de94a31533667d7d7d0c080a90104744b9e/ui/packages/app/src/components/Gallery/Gallery.svelte#L193

```
def get_images(jpg_path):
    images = []
    for jpg_image in os.listdir(f"{jpg_path}"):
      try:
        images.append((f"{jpg_path}\\{jpg_image}", f"{jpg_image}"))
      except Exception as e:
        print(f"{jpg_path}\\{jpg_image}", e)
    return images
```

```
gallery = gr.Gallery(label=gallery_label, show_label=True, elem_id=f"ats-gallery-{prompt_path}-{jpg_path}").style(grid=[5], height="auto")
btn.click(get_images, txt, gallery)
```

I can pass image label like this ` images.append((f"{jpg_path}\\{jpg_image}", f"{jpg_image}"))` but not image alt please add an option and I think img alt is super important for data science and seo "thank you for coming to my ted talk" 👏👏👏

full code here https://github.com/camenduru/stable-diffusion-webui-artists-to-study

**Comment by pngwn** [comment]
The label should have been added as the alt text as part of that PR. It was in one context but we missed the other. I don't think there is a need to pass any additional information down, the caption is a good alt text for the gallery images.
