### ISSUE TITLE
Unable to set python version

### ISSUE THREAD

**Issue by chhaviarora95** [gradio-app/gradio#254]
The code launches fine locally, but when trying to host permanently the python version and architecture is different.

How do I set the python version and also set it to 32-bit architecture?

**Comment by aliabid94** [comment]
On Gradio hosted? Sorry, the infrastructure there is not user configurable - it always uses python3.7. There are no current plans to change that.

**Comment by chhaviarora95** [comment]
Hi! My model was trained on a 32-bit arch and the hosted app doesn't work on generating predictions for it. 

I am able to generate a temporary link and it works perfectly fine. 

Considering, there isn't a functionality to choose 32-bit while getting hosted app set up - could I please get a refund? 

I wasn't able to use the hosted app for the lack of this functionality and would appreciate it if someone could help me with a refund. Thank you so much!

**Comment by aliabd** [comment]
@chhaviarora95,  Sorry you couldn't get your hosted app working. We've cancelled your subscription and processed a refund. 

If you'd like an alternative to hosted consider using [spaces](https://huggingface.co/spaces) or [self hosting](https://abidlabs.medium.com/quickly-deploying-gradio-on-aws-242af2374784).
