### ISSUE TITLE
Socket exception: An existing connection was forcibly closed by the remote host (10054)

### ISSUE THREAD

**Issue by Adeel-Intizar** [gradio-app/gradio#2553]
Hi, 
the public link was working just find until it just threw an exception and closed the public url while private url is still running the app,
is this a bug or am I doing something wrong,
Thanks
![image](https://user-images.githubusercontent.com/56041154/198284600-68adeee7-6244-4b53-9602-4a8e1e6d20cd.png)

**Comment by freddyaboulton** [comment]
Hi @Adeel-Intizar ! Thanks for filing. It's possible the socket was closed due to high load on the server. We're working on making this service more reliable and secure in #2396 which should be merged shortly!

**Comment by abidlabs** [comment]
Hi @Adeel-Intizar! We've now officially merged in https://github.com/gradio-app/gradio/pull/2509, which should increase the file capacity of our share servers. We'll be releasing on pypi shortly but if you'd like to try it out, you can install a beta version: `pip install gradio==3.12.0b7`
