### ISSUE TITLE
Load examples when Interface/Block is loaded unless examples are passed

### ISSUE THREAD

**Issue by merveenoyan** [gradio-app/gradio#2554]
When we load a gradio Interface from huggingface, the examples aren't loaded. I know this is intended behavior but maybe on top of it retrieving the example files when loading the Interface or Block would be good when they're loaded from a Space, _unless_ the user passes the examples parameter explicitly. WDYT? Also pinging @sayakpaul & @osanseviero

**Comment by sayakpaul** [comment]
Even after passing examples, they did not show up in this Space (which uses multiple Spaces):

https://huggingface.co/spaces/sayakpaul/maxim-spaces

**Comment by freddyaboulton** [comment]
Lol so it looks like we manually make the examples dataset invisible when loading from spaces 😬 

```python
    def streamline_config(config: dict) -> dict:
        """Streamlines the blocks config dictionary to fix components that don't render correctly."""
        # TODO(abidlabs): Need a better way to fix relative paths in dataset component
        for c, component in enumerate(config["components"]):
            if component["type"] == "dataset":
                config["components"][c]["props"]["visible"] = False
        return config
```

I think we should first fix the problem that @sayakpaul brings up about `Interface.load` not respecting the `examples` argument even when the examples are local. Later we can try to figure out a way to load examples from the upstream space.

**Comment by sayakpaul** [comment]
Thanks!

**Comment by abidlabs** [comment]
Haha yea that's my bad. Left that as a future TODO but didn't get a chance to come back to it. @freddyaboulton I can take this if you haven't started yet

**Comment by sayakpaul** [comment]
@abidlabs has this been prodded yet? I still don't see the examples here: https://huggingface.co/spaces/sayakpaul/maxim-spaces.

**Comment by abidlabs** [comment]
Hey @sayakpaul can you update the sdk_version in the readme on your Space to 3.9.1?

**Comment by sayakpaul** [comment]
Just did! I didn't update the other spaces `maxim-spaces` shelters, though. 

Works perfectly.
