### ISSUE TITLE
When loading another space using load, allow accessing private demos

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#2557]
The `api_key` is already a valid parameter (used for the Inference API integration). It would be great if this could be used to access private spaces as well :)

**Comment by abidlabs** [comment]
Definitely would be good to support this. @XciD if you could kindly share a usage example of how to use the Hub token to access Private Spaces, we can integrate this into the library itself.

**Comment by XciD** [comment]
@abidlabs you need to send the auth token link auth header:
`Authorization: Bearer hf_token`

**Comment by abidlabs** [comment]
Thanks got it @XciD!
