### ISSUE TITLE
Let user decide if they want a HTML loading animation 

### ISSUE THREAD

**Issue by ValentinKoch** [gradio-app/gradio#2559]
- [x ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
In gradio v 3.7, html elements also have the loading animation added. As I am rendering the html interactively depending on the input of a Slider, this makes for a very bad user experience as instead of a steady output as previously, now there is always a loading screen appearing for a very brief moment. As it is I cant use gradio v 3.7.

**Describe the solution you'd like**  
Please add a flag to the HTML element where you can choose if a loading animation should be played. Might make sense for different elements as well, as interactively rendering could also occur on images or sth else.

**Additional context**

**Comment by abidlabs** [comment]
Hi @ValentinKoch thanks for raising the question. It is possible to disable the loading animation by setting `show_progress=False` in the event trigger. Here's a simple example:

```py
import gradio as gr
import time

def test(x):
    time.sleep(1)
    return x

with gr.Blocks() as demo:
    slider = gr.Slider()
    html = gr.HTML()
    slider.change(test, slider, html, show_progress=False)
    
demo.launch()
```

Let us know if you have further questions!

**Comment by ValentinKoch** [comment]
Thanks a lot for getting back and sorry for the wrongfully created issue, works great :)
