### ISSUE TITLE
Setting value of CheckboxGroup to an integer causes an infinite loading loop.

### ISSUE THREAD

**Issue by taesiri** [gradio-app/gradio#2562]
### Describe the bug

Hello,

Setting `value`  of a `ChecboxGroup` to an integer prevents the demo from loading.

That's all!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Minimal code to reproduce

```
import gradio as gr

def dummy(values):
    return "OK"

demo = gr.Interface(
    dummy, [gr.CheckboxGroup(["checkbox 1", "checkbox 2", "checkbox 3"], value=0)], "text"
)

if __name__ == "__main__":
    demo.launch()
```

### Screenshot

![loading](https://user-images.githubusercontent.com/588431/198682860-e9d09b93-56b2-40a9-bddb-5e2536855a96.png)

### Logs

```shell
There is no crash, so I am ignoring this one.
```

### System Info

```shell
Gradio: `3.7`
Windows: Version 10.0.19044.2130
Happens on both Firefox and Chrome
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @taesiri ! 

Thanks for filing.

The problem is that `value` has to be a list of strings and each string has to be a a valid possible choice. I think this should fix your problem:

```python
import gradio as gr

def dummy(values):
    return "OK"

demo = gr.Interface(
    dummy, [gr.CheckboxGroup(["checkbox 1", "checkbox 2", "checkbox 3"], value=["checkbox 1"])], "text"
)

if __name__ == "__main__":
    demo.launch()

**Comment by freddyaboulton** [comment]
The front-end crashes with 
```
Uncaught (in promise) TypeError: t[0].includes is not a function
    at Object.c (CheckboxGroup.svelte:40:20)
    at Object.c (CheckboxGroup.svelte:32:4)
    at Nt (index.f3976d0d.js:4:5230)
    at Object.c (CheckboxGroup.svelte:35:22)
    at Object.c (Block.svelte:44:8)
    at Object.c (Block.svelte:44:8)
    at Nt (index.f3976d0d.js:4:5230)
    at Object.c (CheckboxGroup.svelte:24:58)
    at Nt (index.f3976d0d.js:4:5230)
    at Object.c (index.f3976d0d.js:34:30855)
```

But I think a more helpful error should be raised prior to the demo launching.

**Comment by taesiri** [comment]
Thank you for your help @freddyaboulton 

My expectation is that the demo should load fine without crashing or looping. Keep in mind that this will not happen if the `value` is set to a string, which is **not** among the options.
