### ISSUE TITLE
IFrame embed demo permission error with Microphone  

### ISSUE THREAD

**Issue by titu1994** [gradio-app/gradio#2565]
### Describe the bug

With Gradio 3.7 (possibly even older gradio versions), an Iframe embedded gradio demo does not ask for microphone permission from the browser (chrome), and so it errors out. File upload still works for audio. 

Site: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/intro.html

Space: https://huggingface.co/spaces/smajumdar/nemo_multilingual_language_id

If the solution is to try gradio js library, I can try that.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Site: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/intro.html

Src for Site: (you'll need to view the rst file to see the .. raw: html section)

https://github.com/NVIDIA/NeMo/blob/main/docs/source/asr/intro.rst

### Screenshot

![Screenshot_20221029-111259](https://user-images.githubusercontent.com/3048602/198846801-fe469861-1b7e-46da-b89b-9b4cc1333cfa.jpg)

### Logs

```shell
No error in the actual HF Space, or local run. 

Only on the Iframe embedded demo in a site.
```

### System Info

```shell
Gradio 3.7
```

### Severity

annoying

**Comment by pngwn** [comment]
Hello. I'm afraid this is one of the issues with using the iframe, you need to grant the iframe explicit permissions when you create it. We generally recommend using the web component embed where possible.

In this case could you try changing your iFrame HTML to the following, this should fix it:

```html
<iframe src="https://hf.space/embed/smajumdar/nemo_multilingual_language_id/+"
  allow: "microphone;"
  width="100%" 
  class="gradio-asr"
></iframe>
```

Depending on the components used, different ones will require different permissions, which makes it challenging to create and general purpose embed snippet. I'll see if there is a way we could generate the correct iFrame snippet (with the correct permissions) dynamically, depending on the components used.

**Comment by pngwn** [comment]
#3070
