### ISSUE TITLE
Direct link to specific example in Gradio interface

### ISSUE THREAD

**Issue by abhigoku10** [gradio-app/gradio#257]
@abidlabs @julien-c  thanks for open-sourcing this wonder app  , i want to use gradio for object detection models can you please share some reference how to do it so that i can implement the same for my custom architecture. Thanks in adavance

**Comment by AK391** [comment]
@abhigoku10 you can check out yolov5
gradio hub: https://gradio.app/hub/AK391/yolov5
repo: https://github.com/AK391/yolov5/blob/master/utils/gradio/demo.py

is that similar to what you are looking to do?

**Comment by abhigoku10** [comment]
@thanks for the reference yes this is similar to what i am looking for , but in this the model is loaded to torch.hub , i wanted to custom model deployment  and can we pass videos as input

**Comment by AK391** [comment]
@abhigoku10 yes you can load a custom model as well without using torch hub 
see this example https://github.com/AK391/vits/blob/main/gradiodemo.py

**Comment by abhigoku10** [comment]
@AK391  thanks for the reference , i have other queries 
1. Can we have mouse event features on the uploaded image like clicking /drawing line 
2. Can we change the background colors of the selections , format of the text 
Thanks for the support

**Comment by AK391** [comment]
@abhigoku10 

1. there is a image editor, can access by clicking edit in the image component area to draw lines on the image
2. Not sure about this, can you clarify about the use case
3. This should be added by gradio
4. Is this from the yolov5 demo?
5. You can have multiple input components like image and video but both would have to be populated currently for the demo to run

**Comment by abhigoku10** [comment]
@AK391  thanks for the response 
1. in the image edit we have a drawing line but can we get the coordinate of the start and end points of the mouse event?
2. the whole theme of gradio is orange / green/ blue can we change it to custom colors 
3. currently this feature is not getting added for the custom inference which i have 
4. yup this is from yolov5 demo 
5. I shall explain more " currently in all the demo case we have i have seen either we option to load image or video using gr.inputs.Image or gr.inputs.Video  but if i want to give the option to the user to select which ever he wants how to do it ?? becuase currently i am getting like this below 
6. 
![image](https://user-images.githubusercontent.com/22094053/129601853-977e08a8-cdf9-4b94-8188-9847b103d936.png)

**Comment by AK391** [comment]
@abhigoku10 
regarding 6. see https://github.com/gradio-app/gradio/issues/236
optional input components are in the works
currently user would have to populate both the fields for the front end to respond
One option could be for the user to upload a video and then process the first frame of the video if the user is looking to process an image or process the entire video otherwise.

**Comment by abhigoku10** [comment]
@AK391  thanks for the response , but i shall wait since optional inputs are in progress . can you please respond for 1-4 points ??

**Comment by AK391** [comment]
@abhigoku10 for 1. not sure will look into it
2. see https://gradio.app/docs, css (str) - custom css or path to custom css file to use with interface.
3. do you have a link to the inferface or a screenshot of what you are seeing, should be enabled by default if you have a example image loaded for the interface
4. see above

**Comment by abhigoku10** [comment]
@AK391  Thanks for teh response 
3. please find the screeshot of the image 
 
![image](https://user-images.githubusercontent.com/22094053/129781437-e6c424b9-5252-4bf5-945d-1f79538081ce.png)

6. can the input radios by default be disabled and enabled only when clicked
7. Given a set of images in the examples can i come to knw what image will the user choose in the given list ??

**Comment by AK391** [comment]
@abhigoku10 3. and 4 can you try pip install gradio==1.7.0 the gallery view is showing for that version

**Comment by AK391** [comment]
@abhigoku10 
6. https://gradio.app/docs#i_radio , the default value does not seem to be optional default (str) - default value.
7. Not that i know of

**Comment by abhigoku10** [comment]
@AK391  thanks for the response 
3 and 4 are working on gradio == 1.7.0 so is it disabled at gradio 2.2.0??
6. checked with that it's not working if used radio button by default first one is disabled

**Comment by AK391** [comment]
@abhigoku10 
3 and 4, yes it is not available in 2.2.0
6. ok I tried testing this as well, for 1.7, default is not a option but for 2.2 it does select the first string in your list of choices for the radio button

**Comment by abhigoku10** [comment]
@AK391 
can we have 3,4 feature for 2.2.0 as well it will good from user perspective

**Comment by abidlabs** [comment]
To clarify, the main thing left here is for us to have a direct link to a specific example so that it preloaded when someone visits the link. E.g. `http://127.0.0.1:7861/#1` loads the first example. We used to have this @aliabid94 and I think it is a useful feature. Can we bring it back?

**Comment by abidlabs** [comment]
This could be expanded to being able to generate a direct link to any specific input that a user tries, which could help in shareability, especially for non-text or non-image demos.

**Comment by abidlabs** [comment]
I'm going to close this in favor of #2269, which is a more general version of this issue and has more relevant context
