### ISSUE TITLE
Plotly plot too zoomed in

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2574]
### Describe the bug

If you run the live_dashboard demo, the sine curve plot is too zoomed in.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run the `live_dashboard` demo in the repo

### Screenshot

![image](https://user-images.githubusercontent.com/41651716/199059495-d9d568a4-724a-47c4-9af1-e8c17ee928aa.png)

### Logs

```shell
-
```

### System Info

```shell
main
```

### Severity

annoying

**Comment by abidlabs** [comment]
Nicely closed
