### ISSUE TITLE
How to adjust output image size within a Block?

### ISSUE THREAD

**Issue by MHX1203** [gradio-app/gradio#2581]
I have create a block, contain threee image, and a dropdown box. and i bind this block with fastapi so that i can use router.

```python
image_app = gr.mount_gradio_app(app, self.image_block, path="/image")
```
I used run my app with this command.
```shell
uvicorn demo:image_app
```

but the preview output size is not i want, i hope the image output size is same with input.
![image](https://user-images.githubusercontent.com/30517250/199149818-4691a961-140d-4402-986c-2dd1c0cda03a.png)

how can i do this.

thanks.

**Comment by abidlabs** [comment]
Hi @MHX1203,

Perhaps the easiest way would be to set the height of the output `Image` components manually in your gradio app. Here's a basic example with an image-image interface, but the same principle :

```py
import gradio as gr

demo = gr.Interface(lambda x:x, gr.Image(), gr.Image().style(height=242))

demo.launch()
```

For more open-ended questions like this, please check out our [Discord](https://t.co/JKepTfXraQ) as GitHub issues is specifically for bug reports and feature requests.
