### ISSUE TITLE
Add copy to clipboard button to other input types

### ISSUE THREAD

**Issue by armancohan** [gradio-app/gradio#2585]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
The only input type that shows the copy to clipboard button is JSON. 

**Describe the solution you'd like**  
It would be great if users can optionally show this button for other input types such as gr.TextBox as well.

<img src="https://user-images.githubusercontent.com/6425112/199174802-25e484c6-ddeb-446d-b1de-07f6842758c8.png" width="300" />

**Comment by abidlabs** [comment]
Thanks for the suggestion @armancohan. My feeling though is that this button is not too crucial for the other components since it is easy enough to select the contents of a Textbox, or right click to copy an image and the presence of such a button would clutter the UI

**Comment by thomas0809** [comment]
Hi,

I also would like to have this feature, as the content of the Textbook may be very long.

**Comment by abidlabs** [comment]
👍 ok perhaps it's worth adding the `Textbox` component, as well as the upcoming `Code` component, WDYT @pngwn?

**Comment by trojblue** [comment]
I'm looking for this feature as well, really useful for text outputs.

**Comment by pngwn** [comment]
We could add it as an option to the components it makes sense for but might not be a great default?

**Comment by abidlabs** [comment]
Sounds good. Fwiw since I originally commented on this issue, I have changed my mind -- I do think it would be quite useful for demos where someone is generating lots of text (e.g. speech-to-text demos)

**Comment by pngwn** [comment]
Might be useful as part of a UI toolkit used for building custom components too. This is a pretty simple issues, we just need to figure out what components to add the feature to + the api.

**Comment by semantium** [comment]
Seconding.

**Comment by JVincentG** [comment]
also looking forward on copy to clipboard on a textbox

**Comment by abidlabs** [comment]
Hi folks! The `Textbox` component will support a copy button via a configurable parameter. Please see #3452 for more details. The PR has been merged, so the option is available if you download from `main`, or you can wait until the next release to pypi, which should be in the next day or two
