### ISSUE TITLE
Loading Private Spaces via `gr.Interface.load()` doesn't work for certain components

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#2601]
### Describe the bug

As part of reviewing #2594, we noticed that if you `gr.Interface.load()` a Private Space (even if you provide an API token), it does't work for certain components, specifically:

* `Model3D` component doesn't show up correctly in the input
* `Dataframe` component preview doesn't show up in the `Dataset`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```py
import gradio as gr

gr.Interface.load("spaces/gradio/test-loading-examples-private").launch()
```

### Logs

```shell
CORS stuff in the js console
```

### System Info

```shell
3.8
```

### Severity

annoying

**Comment by abidlabs** [comment]
Looking into this, it seems like there is an issue with Spaces blocking CORS access for private Spaces. Have asked the Spaces team if it's possible to change this: https://huggingface.slack.com/archives/C048K60MPNF/p1674081005834629

**Comment by abidlabs** [comment]
Update: @XciD is working on a fix to allow CORS here: https://github.com/huggingface/spaces-app-manager/pull/544, thanks @XciD <3

**Comment by abidlabs** [comment]
So the Spaces side is fixed, as can be seen by running the following:

```js
var url = "https://gradio-test-loading-examples-private.hf.space/file=/tmp/tmpnt7v9r32/Bunnyc7iy75is.obj";
var bearer_token = ... // your HF token
var bearer = 'Bearer ' + bearer_token;
fetch(url, {
        method: 'GET',
        headers: {
            'Authorization': bearer,
        }
    }).then(responseJson => {
        console.log(responseJson)
    })
```

But now we just need to pass along the bearer token when making the fetch requests

**Comment by XciD** [comment]
One last thing, doing this in front end will expose the api token to users

**Comment by abidlabs** [comment]
I can't see any way around this. The best thing might be to just print a warning if someone does `gr.Interface.load()` on a Private Space saying that some components may not work properly when loading private Spaces. Thoughts @freddyaboulton @aliabid94 @XciD?

**Comment by freddyaboulton** [comment]
Can we download the files from the upstream private space on the backend (where the token is safe) ?
