### ISSUE TITLE
allow_flagging="auto" not working on hugging face

### ISSUE THREAD

**Issue by jbpolle** [gradio-app/gradio#2603]
### Describe the bug

Hello,

First of all thanks for this great library, really easy to use, well documented and useful.

Regarding the bug, it seems that the allow_flagging="auto" feature doesn't work. I am using it with flagging_callback type HuggingFaceDatasetSaver.
If I change to "manual" mode, the data are correctly saved in the dataset. My understanding of the doc is that in auto mode data would be saved automatically after each inference? 
Doc says: "auto: users will not see a button to flag, but every sample will be flagged automatically."

I am using gradio 3.9

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Created a space here:
https://huggingface.co/spaces/Jean-Baptiste/test_gradio

As expected there is no flagging buttons, but after inference no data are saved in the HF dataset

### Logs

```shell
/home/user/.local/lib/python3.8/site-packages/gradio/interface.py:330: UserWarning: Currently, only the 'default' theme is supported.
  warnings.warn("Currently, only the 'default' theme is supported.")
/home/user/.local/lib/python3.8/site-packages/huggingface_hub/hf_api.py:101: FutureWarning: `name` and `organization` input arguments are deprecated and will be removed in v0.10. Pass `repo_id` instead.
  warnings.warn(
Cloning https://huggingface.co/datasets/Jean-Baptiste/crowdsourced-calculator-demo into local empty directory.
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
Gradio 3.9
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Sorry about this @jbpolle ! Yes this is a bug we'll look into.
