### ISSUE TITLE
More detailed reporting of `ValueError: Returned component ... not specified as output of function.`

### ISSUE THREAD

**Issue by vzakharov** [gradio-app/gradio#2621]
- [x] I have searched to see if a similar issue already exists.

Currently only the type of component (e.g. `Dropdown`) is specified, which makes it very hard to debug and find out which specific component/handler is causing the issue.

Maybe you could add the component label to the log message?

**Comment by abidlabs** [comment]
Hi @vzakharov thanks, I think this would be a nice QoL improvement for developers, and wouldn't cause any issues since every `IOComponent` has the `label` attribute. 

Would you like to open a PR for this issue?

**Comment by vzakharov** [comment]
Can’t at the moment but I might get back to it if no one else does in the meantime.

**Comment by venkatavamsidama** [comment]
i want to work on this issue , can u plz assign it to me

**Comment by abidlabs** [comment]
Hi @venkatavamsidama thanks for your interest! We don't formally assign issues to contributors. Feel free to open a PR for any open issue that does not have an existing PR and we are happy to review.

**Comment by freddyaboulton** [comment]
The warning now returns the name of the function and the expected/actual values returned so I will close.
