### ISSUE TITLE
Import Gradio fsspec error 

### ISSUE THREAD

**Issue by tompellegrini** [gradio-app/gradio#2626]
### Describe the bug

I did a simple "pip install Gradio"

Then in Jupyter notebooks a ran the code: import gradio as gr

I received the error message I copied in the Logs section below. 

I tried searching online for solutions, but none referred to Gradio and they all implied I needed to install earlier versions of fsspec. I tried to do that and nothing worked.

I also scrolled through all 239 open issues here and couldn't find anything that seemed relevant. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr

### Logs

```shell
ImportError                               Traceback (most recent call last)
<ipython-input-13-43eca54f7d45> in <module>
----> 1 import gradio as gr

~\anaconda3\lib\site-packages\gradio\__init__.py in <module>
      1 import pkgutil
      2 
----> 3 import gradio.components as components
      4 import gradio.inputs as inputs
      5 import gradio.outputs as outputs

~\anaconda3\lib\site-packages\gradio\components.py in <module>
     29 from markdown_it import MarkdownIt
     30 
---> 31 from gradio import media_data, processing_utils, utils
     32 from gradio.blocks import Block
     33 from gradio.documentation import document, set_documentation_group

~\anaconda3\lib\site-packages\gradio\processing_utils.py in <module>
     18 from PIL import Image, ImageOps, PngImagePlugin
     19 
---> 20 from gradio import encryptor, utils
     21 
     22 with warnings.catch_warnings():

~\anaconda3\lib\site-packages\gradio\utils.py in <module>
     32 
     33 import aiohttp
---> 34 import fsspec.asyn
     35 import httpx
     36 import requests

~\anaconda3\lib\site-packages\fsspec\asyn.py in <module>
     14 from .exceptions import FSTimeoutError
     15 from .spec import AbstractBufferedFile, AbstractFileSystem
---> 16 from .utils import is_exception, other_paths
     17 
     18 private = re.compile("_[^_]")

ImportError: cannot import name 'is_exception' from 'fsspec.utils' (C:\Users\tompe\anaconda3\lib\site-packages\fsspec\utils.py)

def is_cat(x): return x[0].isupper()
```

### System Info

```shell
gradio-3.9
```

### Severity

blocking all usage of gradio

**Comment by freddyaboulton** [comment]
Hi @tompellegrini ! What fsspec do you have installed? Can you try `pip install fsspec --upgrade`

**Comment by freddyaboulton** [comment]
What version of `fsspec` do you have?

**Comment by tompellegrini** [comment]
Version: 2022.10.0+15.g4a67229

**Comment by tompellegrini** [comment]
That might make sense. Although I tried installing earlier versions and either that or another similiar fsspec error popped up. 

What version would you recommend?

**Comment by freddyaboulton** [comment]
> pip install fsspec==2022.10.0

That command will install the latest (version 2022.10.0) and everything seems to work ok for me. 

Before I was on `2022.7.1` and it worked well for me too. Let me know if either of these versions doesn't work for you please!

**Comment by tompellegrini** [comment]
OK. I did a pip uninstall fsspec and then copied your command in. It worked! Thanks!!

**Comment by freddyaboulton** [comment]
Great to hear @tompellegrini !

**Comment by nateraw** [comment]
Hey @freddyaboulton can we pin the version of `fsspec` in `requirements.txt`? This dep comes installed on some cloud servers (notably, Lambda Cloud) and every time I install gradio I run into this issue which is quite annoying 😅

**Comment by abidlabs** [comment]
Yep we can do that, perhaps `fsspec>=2022.7.1`. @nateraw can you check if `fsspec==2022.7.1` works for you? Would like to go with an earlier version to give people more options in the case of dependency conflicts
