### ISSUE TITLE
Improvements to Label for Dashboarding

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2629]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As discussed today in our workshop, the gr.Number component does not work great for dashboarding uses where you want to display a number.

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/41651716/200894524-8612c9d2-ddb5-41f9-95db-8bb8bed3f57b.png">

@abidlabs suggested using the Label component instead of a number and it works much better!

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/41651716/200896004-47fbf4e7-a80f-4d31-afb3-57f39fa12c67.png">

However there some improvements we can make (detailed below)

**Describe the solution you'd like**  

- Be able to set a color for the Label's Box. That way developers can use it to create "Alert" boxes for metrics.
Something like 

```python
return gr.Label.update(value=100, color="#FF0000")
```

**Additional context**

**Comment by abidlabs** [comment]
Very nice!

Maybe it would be cool if the box color parameter could accept a function based on the value. E.g. something like this:

```py
def shade(val):
  if val==0:
     return "green"
  else:
     return "#FF0000"

gr.Label(box_color=shade)
```

That way as the label changes, the box color is automatically updated
