### ISSUE TITLE
Have Spaces logo inside embedded demo

### ISSUE THREAD

**Issue by merveenoyan** [gradio-app/gradio#2631]
In embedded demos there's only logo of Gradio, it would be nice to have Spaces somewhere next to it? WDYT? @NimaBoscarino (since we discussed it together and it's their idea)
@abidlabs @pngwn

**Comment by abidlabs** [comment]
Hey @merveenoyan as discussed, this should be covered as part of #1957, and feel free to add more comments there, thank you!
