### ISSUE TITLE
Signal only works in main thread

### ISSUE THREAD

**Issue by jannisborn** [gradio-app/gradio#2637]
### Describe the bug

Thanks for building and maintaining this amazing tool!

I observe that gradio does not integrate nearly with signal from the python SL. It seems that the code executed in the `fn` passed to the `gr.Interface` class is delegated to a sub-thread while the app is executed from the main thread.

This can cause problems with python signalers which expect to run from the main thread. I added a single line to one of the example demos to show this problem.

The app launches successfully, but when the signal code is executed it raises. This issue might seem minor but it can become really prohibitive since the code executed inside the `fn` can be complex and beyond the control of the developer building the gradio app.

Note that Streamlit has similar issues (see [here](https://github.com/streamlit/streamlit/issues?q=signal+only+works+in+main+thread+)) which can be solved in some cases with daemon threads (see [here](https://github.com/streamlit/streamlit/issues/1792)), however I tried that for gradio, but it did not work

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```py
import gradio as gr
import signal

def greet(Name, is_morning, temperature):
    salutation = "Good morning" if is_morning else "Good evening"
    signal.signal(signal.SIGALRM, 20)
    greeting = f"{salutation} {name}. It is {temperature} degrees today"
    celsius = (temperature - 32) * 5 / 9
    return greeting, round(celsius, 2)

demo = gr.Interface(
    fn=greet,
    inputs=["text", "checkbox", gr.Slider(0, 100)],
    outputs=["text", "number"],
)
demo.launch()
```

### Logs

```shell
Traceback (most recent call last):
  File "/Users/jab/miniconda3/envs/gt4sd/lib/python3.8/site-packages/gradio/routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "/Users/jab/miniconda3/envs/gt4sd/lib/python3.8/site-packages/gradio/blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/Users/jab/miniconda3/envs/gt4sd/lib/python3.8/site-packages/gradio/blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/jab/miniconda3/envs/gt4sd/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/jab/miniconda3/envs/gt4sd/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/jab/miniconda3/envs/gt4sd/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "<ipython-input-13-259bfd7d09aa>", line 6, in greet
    signal.signal(signal.SIGALRM, 20)
  File "/Users/jab/miniconda3/envs/gt4sd/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```
```


### System Info

```shell
gradio 3.9
Python 3.8
MacOS
```

### Severity

blocking all usage of gradio

**Comment by freddyaboulton** [comment]
This would be true of any python webserver no?

```python
import fastapi
import signal
app = fastapi.FastAPI()


@app.get("/")
def get_temperature():
    signal.signal(signal.SIGALRM, 20)
    return 36
```

Run `uvicorn signal_fastapi:app`

```
INFO:     Started server process [9693]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:49652 - "GET / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
    signal.signal(signal.SIGALRM, 20)
  File "/Users/freddy/miniconda3/envs/gradio/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

Can you elaborate a bit more on your use case @jannisborn ! Maybe there's another way to accomplish what you are trying to do!

**Comment by abidlabs** [comment]
Going to close this. @jannisborn please let reopen this issue with more details if you have a feature request we can help with.

**Comment by jannisborn** [comment]
HI @freddyaboulton,
Thanks for the reply. You're right, I wasnt aware this is a general limitation of python webapps, so it's clearly beyond the scope of this repo.

I refactored my code quite a bit to avoid the use of `signal`. it's a bit of a pity, `signal` only works in main thread and python lacks methods with comparable control for subthreads (packages like `threading` exist but they dont work as smoothly and easily). Anyways, thanks a lot for the quick feedback on this and thanks again for the great library!

**Comment by thiswillbeyourgithub** [comment]
If anyone is having issues I made a wrapper using threading to implement a timeout. If your call is computationaly expensive this might be a bad idea but in my case I sometimes had function that never returned and had to stop the gradio script entirely.

```
import threading

def timeout(limit=60):
    "simple wrapper to add a timeout that raises an exception if taking too long"
    def decorator(func):
        def wrapper(*args, **kwargs):
            result = []
            def appender(*args, **kwargs):
                result.append(func(*args, **kwargs))
            thread = threading.Thread(
                    target=appender,
                    args=args,
                    kwargs=kwargs)
            thread.start()
            thread.join(timeout=limit)
            if thread.is_alive():
                raise Exception(f"Reached timeout for {func} after {limit}s")
            else:
                return result[0]
        return wrapper
    return decorator
```
