### ISSUE TITLE
Multiple input types

### ISSUE THREAD

**Issue by NielsRogge** [gradio-app/gradio#264]
I've made a Gradio demo for LayoutLMv2: https://huggingface.co/spaces/nielsr/LayoutLMv2-FUNSD

The model can annotate document images. It accepts both images and PDF documents (both should just be turned into a PIL image). 

How can I support both "image" or "file" as input? In other words, there are multiple input types possible.

Also, is there a way to make the output bigger?

**Comment by NielsRogge** [comment]
Hmm I meant _either_ a PIL image _or_ a file, not both.

And in terms of making the output bigger, it's not possible to show it on a bigger scale?

**Comment by AK391** [comment]
@NielsRogge could try converting pdf to a image and then use the type=file for the image input component or just the file input component type would handle both images and pdfs 

for showing the output on a bigger scale you can try css in the inferface like this

iface = gr.Interface(fn=process_image, 
                     inputs=gr.inputs.Image(type="pil"), 
                     outputs=gr.outputs.Image(type="pil", label="annotated image"),
                     title=title,
                     description=description,
                     article=article,
                     examples=examples,
                     css=".output_image {height: 600px !important}")
iface.launch(debug=True)

**Comment by abidlabs** [comment]
Just to add to that, another option would be using "optional inputs", which we just introduced in `gradio 2.2.15`. @aliabid94 can you provide an example?

**Comment by AK391** [comment]
@abidlabs added that to a demo, for the image input component uses
inputs=gr.inputs.Image(type="pil", optional=True)

**Comment by NielsRogge** [comment]
Thanks @AK391. Regarding making the output bigger, that worked, thanks. How can I make the input also bigger?

I tried this:

`.output_image, .input_image {height: 50rem; width: 100%;} `

But that didn't seem to work.

**Comment by abidlabs** [comment]
Closing, since this seems to be fixed! Thanks
