### ISSUE TITLE
Bug when gr.Image changes

### ISSUE THREAD

**Issue by Radhe-0** [gradio-app/gradio#2642]
### Describe the bug

I'm making a chat that changes the images with each response from the bot and I found some kind of bug, I don't know if I'm doing it wrong or if there really is a bug, since I don't see any error. This is something that should not happen, because in the first answers the image changes normally, but then it does not change anymore after answering several times.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

first we choose 3 images and place them where they go respectively in the code below. After we generate some responses, you'll notice that after a few responses, it won't change the image anymore for some reason, when it should. Is there an alternative? I need that functionality.

```python
import gradio as gr
from random import choice

responses = ['Hello', 'Hi', 'Greetings']
img = ['image 1 here','image 3 here','image 4 here']
last_img = []

def chat(input, history=[]):
    response = choice(responses)
    last_img.append(response)
    history.append((input, response))
    return history
    
def change_image():
    if last_img[-1] == 'Hello':
        return img[0]
    if last_img[-1] == 'Hi':
        return img[1]
    if last_img[-1] == 'Greetings':
        return img[2]


with gr.Blocks() as demo:
    with gr.Row():

        with gr.Column(scale=1):
            chat_interface = gr.Chatbot(show_label=False).style(color_map=('Teal','HotPink'))
            input = gr.Textbox(label=' ',placeholder='write a message...',show_label=False)

            with gr.Row():
                send_button = gr.Button('Send').style()
                send_button.click(fn=chat, inputs=input, outputs=chat_interface)

        with gr.Column(scale=1):
            image_here = gr.Image('image 1 here',show_label=False)
            chat_interface.change(change_image,inputs=[],outputs=image_here,show_progress=False,batch=False)

demo.launch(share=True, debug=True)

```

### Logs

**no errors appear, it just doesn't work as it should apparently.**

### System Info

```shell
3.9.1,google colab,Brave(browser)
```

### Severity

annoying

**Comment by Radhe-0** [comment]
Please answer 😓

**Comment by Radhe-0** [comment]
Please answer  😓

**Comment by abidlabs** [comment]
Hi @Radhe-0 I'm not able to reproduce the issue. When I ran your code, I was able to continue changing the image. Here is a screencast:

![59172c0d-00e2-41eb-ba1e-a99b8d31ef2e](https://user-images.githubusercontent.com/1778297/203466922-1ecb59cc-faf0-4c10-8317-4bdfde545f5a.gif)

The only differences that I can think of are:
* I'm running on the latest version of `gradio` (3.10.1)
* I'm using different images
* I set `share=False`, `debug=False` in `launch()`
