### ISSUE TITLE
Providing js function on load not working 

### ISSUE THREAD

**Issue by krrishdholakia** [gradio-app/gradio#2643]
### Describe the bug

I'm running this code in a google colab: 

```
import gradio as gr 

js_function = "() => {console.log('hello world');}"

demo = gr.Interface.load(<space_name>, _js=js_function)
demo.launch(share=True, debug=True)
```

but when i check console log, i don't see the 'hello world' output 
<img width="719" alt="Screen Shot 2022-11-12 at 5 54 51 PM" src="https://user-images.githubusercontent.com/17561003/201501802-f77cb1a3-244b-4fa8-9374-ee9aade8c55d.png">

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr 

js_function = "() => {console.log('hello world');}"

demo = gr.Interface.load(<space_name>, _js=js_function)
demo.launch(share=True, debug=True)

### Logs

```shell
Fetching Space from: https://huggingface.co/spaces/krrishD/stacktrace-QA
Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
Running on public URL: https://2731fee4462d846a.gradio.app

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
```

### System Info

```shell
gradio version: 3.9.1
```

### Severity

blocking all usage of gradio

**Comment by krrishdholakia** [comment]
cc: @abidlabs

**Comment by abidlabs** [comment]
Apologies for the delay @krrishdholakia. The reason that this is happening is that the `.load()` method is overloaded. When used as a class method, it loads a Space. When used as an instance method, it attaches an event listener to the load. You will need to use these two separately. In addition, event listeners can only be assigned with a `gr.Blocks()` context. 

The correct usage would be like this, which I've tested and correctly runs the js function:

```py
import gradio as gr 

js_function = "() => {console.log('hello world');}"

with gr.Blocks() as demo:
    gr.Interface.load("spaces/abidlabs/calc")
    demo.load(_js=js_function)

demo.launch()
```
