### ISSUE TITLE
Update canvas value from code

### ISSUE THREAD

**Issue by vvvm23** [gradio-app/gradio#2649]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I am trying to use a segmentation mask in the first stage of my gradio app. I want to be able to edit this mask further using canvas controls in order to make small adjustments.

**Describe the solution you'd like**  
Image with `source=canvas` should use `value` as its default value, rather than simply defaulting to a white background.

**Additional context**  
I am trying to create a Gradio demo that combines stable diffusion inpainting with a segmentation mask for easy mask generation. The segmentation isn't perfect, so I'd like to be able to make small adjustments using the canvas tools.

Below is my current UI. I'd like to be able to draw on the "Diffusion Mask" component.

![image](https://user-images.githubusercontent.com/44398246/201783522-c5f5d7f9-cbc9-4a2c-bb0c-9ba8f49e6854.png)

Thanks :)

**Comment by pngwn** [comment]
I though you could do this, will check and get back to you.

Just to clarify, you want to set an image as the starting background image to the sketch tool?

**Comment by vvvm23** [comment]
Yes, to be precise:
- I click "Compute Masks"
- A segmentation model is run and masks stored as a hidden state
- When changing the sliders or checkboxes the "Diffusion Mask" image is updated using `gr.Image.update(value=new_mask)` 
- I'd like to then be able to make small adjustments using the canvas tool.

But calling update like this doesn't seem to work.
