### ISSUE TITLE
Changing from video input example while video is playing breaks

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#2651]
### Describe the bug

In https://huggingface.co/spaces/sayakpaul/video-classification-ucf101-subset, I can easily switch between examples. If I select example 1, click play, and then switch to another example while it's running, it will break as I won't be able to play the video. Clicking pause/play does not seem to work

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Check out https://huggingface.co/spaces/sayakpaul/video-classification-ucf101-subset

### Logs

```shell
-
```

### System Info

```shell
Chrome, Mac OS, running in https://huggingface.co/spaces/sayakpaul/video-classification-ucf101-subset
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment]
From the console

```
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
```
