### ISSUE TITLE
Is it reasonable to allow some retries if connection failed

### ISSUE THREAD

**Issue by Litchilitchy** [gradio-app/gradio#2657]
- [x] I have searched to see if a similar issue already exists.
Existed issue: https://github.com/gradio-app/gradio/issues/1193

Hi I have used `.launch()` method and everything works fine. However when I use `.launch(shared=True, server_name="0.0.0.0")` the app fails so easily. The error is always `Failed to connect to ec2.gradio.app:22 (some other detailed message)`

I checked a few existed related issue and almost all of them say this is connection issue due to network quality. However, I checked source code and found the related code [here](https://github.com/gradio-app/gradio/blob/4149d0082288786239d3e96604ed5967464e2b4c/gradio/tunneling.py#L71)

I wonder is it reasonable to allow a few retries here to make it harder to fail?

**Comment by abidlabs** [comment]
Hi @Litchilitchy we're replacing our entire tunneling approach as part of #2509 so let's see if that fixes the issue. If not, happy to take a suggestion there

**Comment by abidlabs** [comment]
Hi @Litchilitchy, we've officially merged in officially merged in #2509, which should should replace the problematic code altogether. We'll be releasing on pypi shortly but if you'd like to try it out, you can install a beta version: `pip install gradio==3.12.0b7`
