### ISSUE TITLE
Scroll bars on dataframes

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2666]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
If your gradio demo displays a dataframe with many rows or columns, all of the dataframe will be displayed at once and users have to scroll all the way down the page to see their data.

![dataframe_long](https://user-images.githubusercontent.com/41651716/202559043-f02fbd8f-a7a2-48a5-a5de-0cfca4042f1a.gif)

**Describe the solution you'd like**  
Keep the dataframe a fixed size but add a scroll bar to the right hand side and bottom of the dataframe. That way the scroll bar doesn't increase the size of the entire page.

**Additional context**

**Comment by abidlabs** [comment]
I suppose pagination for dataframes (as suggested here: #1245) would be the alternative

**Comment by freddyaboulton** [comment]
I think we can support both? To me, pagination means you have to click on a separate button to take you to the next "page" of the dataframe, which may not be desired for some cases and it's not mutually exclusive with scroll bars?

**Comment by liuheng2cqupt** [comment]
Does the latest version (3.28) already support pagination or scroll?  why mine doesn't work?

**Comment by abidlabs** [comment]
Hi @liuheng2cqupt no we haven’t implemented this yet, it’s still an open issue

**Comment by mazzma12** [comment]
An horizontal scrollbar would make sense as well, since it's hard to visualize dataframe > 10 columns

**Comment by pseudotensor** [comment]
Yes, it's an issue, the page gets very long, so I only do head.  But columns have no scroll, so a hacky way is to drag the mouse over the page to get it to move right and left.

![image](https://github.com/gradio-app/gradio/assets/2249614/1204819c-7c6f-4c75-91f1-43684a388c5f)

**Comment by gvlachos-au** [comment]
FYI as a temporary workaround you can try the following CSS solution (works in Firefox AFAIK) - also make sure to update `3-38-0` to the version of gradio you are using:

.gradio-container-3-38-0 .table-wrap {
  overflow-x: auto !important;
  overflow-y: auto !important;
  scrollbar-width: thin !important;
}

**Comment by pseudotensor** [comment]
Hmm, I tried that but actually opposite happened, I lost the vertical scroll bar and still don't have horizontal scroll bar.

![image](https://github.com/gradio-app/gradio/assets/2249614/383d114c-7b72-41af-b020-7716bde75f4f)
