### ISSUE TITLE
Be able to update accordion label from backend

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2668]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Would be nice if developers could update the accordion label from the backend. 

Example use case,

You have a drop down with dataset names on the left hand side and information about the dataset in different accordion components. You'd like the accordion title to reflect the current dataset selected.

For example, in the UI below, it might be nice if instead of "Dataset Description" it read "<dataset-name> description" or "Label Distribution for <dataset-name>"

![image](https://user-images.githubusercontent.com/41651716/202575495-d494a43b-01ab-4d61-a877-c6552a0b7a82.png)

**Describe the solution you'd like**  
```python
gr.Accordion.update(label=<new-label>)
```

**Additional context**

**Comment by apolinario** [comment]
Additionally, would be great to also be able to update the status of the accordion (expanded or not) via the backend
