### ISSUE TITLE
Examples don't show up when loading from an existing Space

### ISSUE THREAD

**Issue by sayakpaul** [gradio-app/gradio#2672]
### Describe the bug

If I do:

```py
gr.Interface.load(
    "spaces/eugenesiow/remove-bg",
     examples=[["deepmind.jpg"]]
).launch()
```

where `deepmind.jpg` was retrieved as -

```
wget -q https://pbs.twimg.com/profile_images/691700243809718272/z7XZUARB_400x400.jpg -O deepmind.jpg
```

the example doesn't show up.

I am trying this on Colab. I have added `debug=True` in `launch()` and logs do not contain any errors or anything that might be useful for the issue. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Stated above. 

### Logs

```shell
No descriptive logs either.
```

### System Info

```shell
Colab
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @sayakpaul what version of gradio are you using?

**Comment by sayakpaul** [comment]
3.10.1

**Comment by abidlabs** [comment]
Hi @sayakpaul, yes this is the same issue as https://github.com/gradio-app/gradio/issues/2671. You can see the suggestion @freddyaboulton provided there, and we'll provide a warning to make this clearer for users in the future.
