### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by SkyTNT** [gradio-app/gradio#2681]
### Describe the bug

`Audio.preprocess` will throw error If the file name of input audio is too long.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Name an audio file `水本ゆかりです｡私､こんなかわいい服は初めて着ました…｡なんだかうれしくって､楽しいです｡歌いたくなる気分って､初めてです｡これがｱｲﾄﾞﾙってことなのかもしれませんね!7046dya9`  and put it into 
any Audio component in [https://huggingface.co/spaces/skytnt/moe-tts](https://huggingface.co/spaces/skytnt/moe-tts)

### Logs

```shell
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 980, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 891, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/home/user/.local/lib/python3.8/site-packages/gradio/components.py", line 1842, in preprocess
    file_obj = processing_utils.decode_base64_to_file(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 277, in decode_base64_to_file
    file_obj = tempfile.NamedTemporaryFile(
  File "/usr/local/lib/python3.8/tempfile.py", line 540, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/local/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 36] File name too long: '/tmp/水本ゆかりです｡私､こんなかわいい服は初めて着ました…｡なんだかうれしくって､楽しいです｡歌いたくなる気分って､初めてです｡これがｱｲﾄﾞﾙってことなのかもしれませんね!7046dya9.wav'
```

### System Info

```shell
gradio3.9, space [https://huggingface.co/spaces/skytnt/moe-tts](https://huggingface.co/spaces/skytnt/moe-tts)
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @SkyTNT the limitations of file

**Comment by abidlabs** [comment]
Hi @SkyTNT it looks like the original filename is quite long here which is causing an issue when the temporary file is created. Would it be possible to shorten the original filename before you put it into the `Audio` component?

**Comment by SkyTNT** [comment]
Users don't konw that they need to shorten filename because they can't see the error logs.

Just like creating temporary file in `postprocess`, I think we don't need to use original filename as prefix for temporary file.

**Comment by abidlabs** [comment]
> Users don't konw that they need to shorten filename because they can't see the error logs.

That's a good point! I think there might be some identifiability benefit to using the same or similar name as the prefix for the temporary file, but we can check to see if the filename is too long for the particular OS and shorten it if needed. 

If you are open to making a PR, happy to review!
