### ISSUE TITLE
`gr.Markdown` not displaying images from Imgur

### ISSUE THREAD

**Issue by vscv** [gradio-app/gradio#2682]
```gr.Markdown("""![Imgur](https://imgur.com/qdpQnUk.jpg)""") # not work```

**Comment by abidlabs** [comment]
Thanks @vscv. This is actually a known problem with imgur, where they do restrict access to images from a 127.0.0.1 referer. See here for example; https://stackoverflow.com/questions/43895390/imgur-images-returning-403

You can get around this by changing your `server_name` to be `localhost` instead, like this:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Markdown("""![Imgur](https://imgur.com/qdpQnUk.jpg)""")

demo.launch(server_name="localhost")
```

**Comment by vscv** [comment]
Thanks for the help @abidlabs. Imgur works fine now.  However,  when I try to display the local image like the following:

```
import gradio as gr

with gr.Blocks() as demo:
    gr.Markdown("""![local img]("flow_sample_001.jpg")""") # not work
    gr.HTML("<img src='flow_sample_001.jpg'>")                   # not work

    gr.HTML("<img src='https://www.cuerpomente.com/medio/2022/07/13/flores-simbolismo-espiritualidad_09ff3f15_1200x1200.jpg' width='330' />") # work good!

demo.launch(server_name="localhost")
```

**Comment by abidlabs** [comment]
For local images, you should preface the path with `file=`. So you can try:

```py
    gr.Markdown("""![local img]("/file=flow_sample_001.jpg")""") # not work
    gr.HTML("<img src='/file=flow_sample_001.jpg'>")                   # not work

```

**Comment by lawlietsoul** [comment]
For the newer version, you need to add "allowed_paths" to make Gradio having access to local storage

> demo.launch(allowed_paths=["./"])

**Comment by xiaoajie738** [comment]
> For the newer version, you need to add "allowed_paths" to make Gradio having access to local storage
> 
> > demo.launch(allowed_paths=["./"])

Indeed, thank you for sharing.

**Comment by wozwdaqian** [comment]
it work for me.
`import gradio as gr

with gr.Blocks() as demo:
    gr.Markdown(
"""
# Hi
![11](/file=imgs/0.png)
""")
    
demo.launch(allowed_paths=['./'])
`

gradio==4.29.0
