### ISSUE TITLE
Allow for a tqdm and custom ETA as opposed to the native one in Gradio

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#2683]
- [x] I have searched to see if a similar issue already exists.
(I don't think it is the same as https://github.com/gradio-app/gradio/issues/1596, but if it is feel free to close)

**Is your feature request related to a problem? Please describe.**  
Gradio automatic calculation of progress and estimation is a great approximation based on previous runs. However, it doesn't work if: 
- It is the first run
- Different runs have different times (applications with user-defined settings)

`tqdm` already solves this problem by providing a per-iteration estimation and is widely used

**Describe the solution you'd like**  
I would like for users to have a possibility that, in output fields, the user could choose *not* to use the native estimated time, but rather choose to use the tqdm estimation from within whatever loop in their processing function they choose
![image](https://user-images.githubusercontent.com/788417/204126602-c2dee5e2-c090-4e7a-b1b8-88bc777074dd.png)

**Additional context**  
If there's more than one task inside of a function (multiple loops), there could be counters like: 
`task 1/3: iteration 2/10 [00:01<00:07,  1.12it/s]`

**Comment by abidlabs** [comment]
This is possible with the new progress bar, thanks @aliabid94!
