### ISSUE TITLE
Make gr.Error `position: Fixed` in an iframe

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#2687]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Currently gr.Error is on the top-right. However if your application scrolls down, the user can never read what error it was unless they scroll back up
![image](https://user-images.githubusercontent.com/788417/203115423-55e97884-fb17-4e5b-86ff-0f0a28a9f721.png)

**Describe the solution you'd like**  
Have `gr.Error` to have a `position: Fixed` or analogous to show on the top-right regardless of scroll

**Comment by abidlabs** [comment]
Makes sense, thanks for the nice suggestion @apolinario!

**Comment by abidlabs** [comment]
Hmm interesting I just tested this out and for me, locally the `gr.Error()` appears in a fixed position. However, when embedded in Spaces, it does not appear in fixed place.

This seems like a limitation of iframes, according to https://stackoverflow.com/questions/9578364/absolute-position-elements-within-iframe
> An element within an iFrame cannot be positioned relative to an element in the parent document. iFrames and their parent windows don't share resources such as CSS (and therefore also don't share CSS rules). There is no pure CSS way to accomplish this.

cc-ing @pngwn, do you know if this is doable?

Here's my code to reproduce:

```py
import gradio as gr
import time

def func(x):
    time.sleep(2)
    raise gr.Error("abc")
    return x
    
md = "a<br>"*40

with gr.Blocks() as demo:
    a = gr.Markdown(md)
    b = gr.Textbox()
    demo.load(func, a, b)

demo.launch()
```

**Comment by pngwn** [comment]
Sorry, missed this. This isn't possible because of how the iFrame is resized/ scrolled as far a I'm aware but we may be able to improve it somewhat by scrolling to the correct location if there is an error.

**Comment by pngwn** [comment]
We can discuss this today but this is really problematic and the fixes are not satisfactory. I'll be testing a few ideas but testing them might be tedious.
