### ISSUE TITLE
[Feature] Combine "upload", "webcam" and "canvas" sources into a "dynamic" source for image

### ISSUE THREAD

**Issue by LESSSE** [gradio-app/gradio#269]
I would like to provide only one interface and be able to both use the webcam and upload images. 

I suppose is not hard to add a small box to input.Image widget that would allow users to dynamically choose what they want: to use "upload", "webcam" or "canvas".

**Comment by abidlabs** [comment]
This is a cool idea! We'll look into it.

In the meantime, you could create multiple inputs (one webcam, one upload, one canvas) and make them all optional! Depending on which one the user uses, you could pass that into your function and make predictions appropriately.
