### ISSUE TITLE
Allow for limiting file extensions with `gr.File` 

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#2697]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I would like to let users only upload files from specific extensions with the `gr.File` component

**Describe the solution you'd like**  
An `allowed_extensions` or equivalent parameter that lets me pass a list of extensions that are allowed. A more sophisticated version of this could also allow for smartly automagically specifying file types (image, audio, video, etc)

**Comment by abidlabs** [comment]
Good news, @dawoodkhan82 just added this as part of #2591! It supports passing in a list of file_types, which can be "image", "audio", "video", or "text"

It's out on `main`, will be out on pypi sometime this week!
