### ISSUE TITLE
Output Image size is resized

### ISSUE THREAD

**Issue by ArjunPukale** [gradio-app/gradio#27]
If my output is Image then the outputted Image size is not that of the size generated by the function.
for eg :
The function just rotates the image 180 degree but the output image is resized and cropped!!!
![image](https://user-images.githubusercontent.com/49120008/87460561-ae18ac00-c62a-11ea-87b6-e8577cb2fa8c.png)

**Comment by abidlabs** [comment]
Thanks for opening the issue. Yes, I believe this documented in #14, which we are addressing. Let me go ahead and close this for now. Please reopen if it's a different issue. Thanks.
