### ISSUE TITLE
use css framework in html output

### ISSUE THREAD

**Issue by chschock** [gradio-app/gradio#270]
I'm wondering if there is a easy change that allows using an 'arbitrary' css framework like bootstrap, semantic, bulma or uikit in an html tag, including it with `<link>` and `<script>` tags. It seems to work with the css parts of the frameworks, but components don't function, as the js imports don't work. Is it React that overrides something? One does see the correct rendering of such components for a fraction of a second before the layout breaks.
Is there a simple change that would allow to use css frameworks fully? I don't mean for interactive elements to call the serving app, just for 'static' css components that require js, like tabs, modals, accordeons...

**Comment by abidlabs** [comment]
Tagging @aliabid94 here

**Comment by abidlabs** [comment]
I'm pretty sure this is doable. Take a look at this example that uses Bootstrap, for example: https://huggingface.co/spaces/microsoft/unispeech-speaker-verification/blob/main/app.py

Feel free to reopen if this does not work for you!
