### ISSUE TITLE
Embed private repo apps

### ISSUE THREAD

**Issue by kenndanielso** [gradio-app/gradio#2703]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I can't embed private repo Gradio apps. Leaving it as a public app attracts bots and is expensive to host since I use external APIs that I get charged for.

**Describe the solution you'd like**  
A way to embed private Gradio apps on external web pages or apps.

**Additional context**  
N/A

**Comment by abidlabs** [comment]
Thanks for creating this issue @kenndanielso. However, this is related Spaces, not the `gradio` library. Would you be able to open a discussion here? https://discuss.huggingface.co/c/spaces/24
