### ISSUE TITLE
Recording Audio and Video from webcam simultaneously

### ISSUE THREAD

**Issue by MandarGogate** [gradio-app/gradio#2704]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I want to build a demo for machine learning model that processes Audio-Visual data from webcam. The current Video component records from webcam without audio. 

**Describe the solution you'd like**  
Since the Video component uses MediaRecorder API it can record audio and video simultaneously.

**Comment by MandarGogate** [comment]
I managed to update the Webcam.svelte to fix this. You can have a look at [https://github.com/MandarGogate/gradio/commit/2d291e7f311192899e01b5f82133905ce1dace67](https://github.com/MandarGogate/gradio/commit/2d291e7f311192899e01b5f82133905ce1dace67). I tested this on Safari, Chrome and Firefox.

**Comment by abidlabs** [comment]
Great, thanks so much @MandarGogate! Would you be able to open a PR and happy to review it?
