### ISSUE TITLE
Documentation page doesn't distinguish methods with the same name for anchor link

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#2712]
### Describe the bug

If I'm navigating in the demos page and I click a method that has the same name as a method of another class, it ends up sending me to the first one with the same name.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://user-images.githubusercontent.com/788417/203535481-4cf68817-889b-44b7-b3c6-1f03906449c2.mp4

### Logs

```shell
No logs
```

### System Info

```shell
Not applicable
```

### Severity

annoying

**Comment by aliabd** [comment]
Thanks @apolinario for flagging this. Just fixed and deployed to the website. Note that it will only work on [/docs/main](https://gradio.app/docs/main/) for now, as the main docs page reflects latest from pip and only updates when a new version is released, but all the ids are fixed now and won't clash.  

https://user-images.githubusercontent.com/9021060/203636945-3e169e0b-0c5b-4e30-b64b-89c20bee1423.mov
