### ISSUE TITLE
Examples throws error in external site (ie. through onload) 

### ISSUE THREAD

**Issue by krrishdholakia** [gradio-app/gradio#2716]
### Describe the bug

the gradio examples function throws an error when you use the space in an external site. 

I have a site consuming my huggingface space. When i try using the example in the hf space, it works fine. But when i try using it in the website, it throws an error. 

<img width="1597" alt="Screen Shot 2022-11-23 at 10 04 37 PM" src="https://user-images.githubusercontent.com/17561003/203706404-38d1e03e-84c9-402b-a2a4-aee168c2b7a1.png">
![Uploading Screen Shot 2022-11-23 at 10.04.55 PM.png…]()

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Link to hf space - https://huggingface.co/spaces/krrishD/stacktrace-QA

Link to website consuming space - https://sinfulvibrantexponents.krrishdholakia.repl.co/

### Logs

```shell
Uncaught (in promise) API Error
```

### System Info

```shell
3.11.0
```

### Severity

blocking all usage of gradio

**Comment by krrishdholakia** [comment]
cc: @abidlabs

**Comment by abidlabs** [comment]
I’m OOO this week, but happy to take a look next week!

**Comment by aliabd** [comment]
Hey @krrishdholakia

* The version of gradio that the space is using is not `3.11.0`, it's `3.4.1`. Can you update it to `3.11.0`? Go to the README.md file in the space and change the `sdk_version` to:
```
sdk_version: 3.11.0
```
* The version of the `gradio.js` module you're loading in the repl isn't `3.11.0`, it's `3.9.1`. Replace the script in the header with:
```
<script type="module" src="https://gradio.s3-us-west-2.amazonaws.com/3.11.0/gradio.js">
</script>
```

That should fix it, but let me know if it doesn't.
