### ISSUE TITLE
Allow making dataframes static/non-editable

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#2720]
- [ ] I have searched to see if a similar issue already exists.

For Spaces such as https://huggingface.co/spaces/ysharma/Playground_AI_Exploration, the user is showcasing a dataframe, so it's not useful to be able to add rows and columns. Instead, the user should only be able to read the dataframe

**Comment by aliabd** [comment]
This can be done by setting `interactive=False` in `gradio.Dataframe()`. I duplicated the space to show this [here](https://huggingface.co/spaces/aliabd/non-interactive-dataframe).

**Comment by abidlabs** [comment]
@osanseviero feel free to reopen with more details if @aliabd's answer doesn't work for you!

(cc @yvrjsharma)

**Comment by piegu** [comment]
Hi,

I raised an [issue ](https://github.com/gradio-app/gradio/issues/2975) as `interactive = True` does not work in an output `gr.Dataframe()` (at least, with the last gradio version).
