### ISSUE TITLE
No result in opera browser

### ISSUE THREAD

**Issue by doevent** [gradio-app/gradio#2723]
### Describe the bug

Not showing images results on huggingface: "Internal Server Error" in Opera browser

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/stabilityai/stable-diffusion

### Screenshot

![image](https://user-images.githubusercontent.com/61069711/204034355-6afa82f2-4f84-4764-8747-0cd41c530950.png)

### Logs

```shell
None
```

### System Info

```shell
Gradio: 3.11.0
Opera browser: 92xxxxx, 93xxxxx
```

### Severity

serious, but I can work around it

**Comment by aliabd** [comment]
Hey @doevent I'm unable to reproduce this. It's running fine for me on Opera `v93.0.4585.21`. May have been a specific issue with the space when you tried it. Are you still seeing the error? 

![Screen Shot 2022-11-26 at 9 31 43 AM](https://user-images.githubusercontent.com/9021060/204101531-f856c68e-a549-45f7-9595-b751748c2df5.png)

**Comment by doevent** [comment]
> Hey @doevent I'm unable to reproduce this. It's running fine for me on Opera `v93.0.4585.21`. May have been a specific issue with the space when you tried it. Are you still seeing the error?

Opera Version (private window): `93.0.4585.21`
Os Windows Version: `10 21H2`

![image](https://user-images.githubusercontent.com/61069711/204117815-ae49c0d9-e309-4f30-83a1-8bfde44b4b5e.png)

I am using chrome browser. It works in this browser.

**Comment by abidlabs** [comment]
Will go ahead and close for lack of repoduction.
