### ISSUE TITLE
can gradio support sanic framework for better IO performance?

### ISSUE THREAD

**Issue by cailiang9** [gradio-app/gradio#2724]
fastapi is slow http://klen.github.io/py-frameworks-bench/
![image](https://user-images.githubusercontent.com/3636844/204081982-6c91ca2e-8b63-49b6-ade4-0f93e3d57b48.png)

**Comment by pngwn** [comment]
Can you provide more context for this request? What performance problems are you currently experiencing with Gradio? Could you provide a reproduction of this issue?

FastAPI forms part of the public Gradio API and changing it would be a breaking change. It would also require a reasonable amount of effort and it isn't clear to me that the performance improvements from another framework would have a marked effect for most of our users. 

Going to close this issue as we are almost definitely not going to swap out FastAPI in the near future but feel free to provide any additional context as requested above.
