### ISSUE TITLE
No timeout for version_check's requests

### ISSUE THREAD

**Issue by yujiehecs** [gradio-app/gradio#2726]
### Describe the bug

By default, `utils.version_check()` is called every time when an Interface is instantiated, as in https://github.com/gradio-app/gradio/blob/1c244cc34281086eb15b233db6f923c0cfe238e3/gradio/interface.py#L406

However, the `requests.get()` call within `version_check()` does not have timeout config, as in
https://github.com/gradio-app/gradio/blob/5e148c3752a3534378a9b99f1cc64ad347112468/gradio/utils.py#L57 

This leads to forever waiting time when in certain environment, external network connection is disabled.

There was an issue https://github.com/gradio-app/gradio/issues/2052 that might resolve this problem by converting the http call to be async. But it was not directly fix this 'bug'?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Not sure how to share the exact setting, but I'm attaching an screenshot after I run
`pyinstrument app.py`
during which, it took ~ 5 minutes to launch the application, where `app.py` is my own toy app that includes `TabbedInterface.launch`.

### Screenshot

<img width="1114" alt="pyinstrument" src="https://user-images.githubusercontent.com/101376653/204113177-2da05674-10b1-486f-aba2-90bae13ca90c.png">

### Logs

```shell
N/A
```

### System Info

```shell
gradio==3.11.0
MaxOS M1
Chrome
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Thanks @yujiehecs for spotting this! Can confirm the problem -- would you be able to able to make a PR to add a timeout? We'd be happy to review it

**Comment by yujiehecs** [comment]
@abidlabs Created a small PR https://github.com/gradio-app/gradio/pull/2729 to fix it.

> First-time contributors need a maintainer to approve running workflows
Thus the PR check is still pending. Please let me know if a short description in CHANGELOG's bug fix section is required.
