### ISSUE TITLE
Adding "code" component

### ISSUE THREAD

**Issue by fefespn** [gradio-app/gradio#2728]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I got little bit frustrated when trying to output a code (e.g. Python code) as a text component, 
while it's sufficient, I think having a "code component" or textbox component with "code" type would be more
convenient to read (or maybe write as input).

**Describe the solution you'd like**  

I believe if there is an output display component of a code (like editors code, colorful) would be very nice feature and
will add the value to work more conveniently with code I/O.

**Additional context**
this two examples:
<img width="589" alt="Screen Shot 2022-11-27 at 15 00 33" src="https://user-images.githubusercontent.com/21076243/204136559-d267c66c-0520-401a-befa-5211aaddabf5.png">
<img width="359" alt="Screen Shot 2022-11-27 at 15 00 52" src="https://user-images.githubusercontent.com/21076243/204136578-e4a33bb3-48a3-4a14-87cd-dcb60b113b25.png">

**Comment by freddyaboulton** [comment]
Hi @fefespn thanks for filing! Totally agree that this would be a useful feature to add. We already have an issue open for this #1014 and I believe @pngwn sketched out an implementation a couple of weeks ago!
