### ISSUE TITLE
`gr.File` transfers the same file to a different temp folder every time it is executed

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#2732]
### Describe the bug

(Not sure if a bug, feel free to re-tag this is a feature request) 

I have a `gr.File` component that should display a 5GB file, this component is constantly mounted/unmounted as the application is loaded or refreshed 

Everytime the component is mounted the file is transferred to a new temporary folder/file like `/tmp/tmpyesjr1q0/diffusers_model4x4bg8ew.tar`

So not rarely I have this issue
```
OSError: [Errno 28] No space left on device: 'diffusers_model.tar' -> '/tmp/tmpyesjr1q0/diffusers_model4x4bg8ew.tar'
```
And I have to manually go and clean up the `/tmp/` folder

I'm not sure how best to solve this issue, however I would suggest a workaround that actually I wish it existed:
- Have a prop to serve the file from where it currently lives (without a need transfer it to `tmp`). Specifically for Spaces that have a file structure of `https://<space-url>/file/the-file-I-want.tar` if I could just show the real path on the `gr.File` component instead of `tmp` shenanigans

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

No applicable 

### Logs

```shell
No logs
```

### System Info

```shell
Gradio == 3.11
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Hey @apolinario thanks for creating the issue. Will take a look this week!

**Comment by abidlabs** [comment]
@apolinario are you using the `gr.File()` to display the output of a function, or to only display a fixed file? It would be great if you can share more code so that I can understand how you are using it

**Comment by apolinario** [comment]
I'm using it to display a fixed file that is created by a function. Sorry the code is a bit convoluted but it is the Dreambooth Training Space: https://huggingface.co/spaces/multimodalart/dreambooth-training

I have a `gr.File()` that showcases the generated tar file of the model & the converted ckpt. They can be outputs of the function but not always. And they regardless live in the folder structure anyway, so copying it to a temp folder sounds a bit of an extra- step
