### ISSUE TITLE
Fixes to the View API page

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#2733]
@osanseviero caught some issues with the view API page:

1. For audio, the example shows .wav  but the docstring says // represents audio data as base64 string of 'audio' Audio

![image](https://user-images.githubusercontent.com/1778297/204324582-e0ef95ab-42c9-487e-9f15-4312460e03a5.png)

2. I clicked try it out and it errored out, which was kinda expected to me, but there is not much info on the error here. Do we want to expose the error?

(Note: 1-2 are probably the case with the other file-based components as well)

3. The indentation here seems off

![image](https://user-images.githubusercontent.com/1778297/204324730-2e53aef3-9e59-4e9e-8307-a6ae4605f6d5.png)

4. And for the code snippets, some syntax highlighting would be a nice to have

![image](https://user-images.githubusercontent.com/1778297/204324827-b17e0eb3-f612-47d4-940b-fe7c2ae28dc6.png)

To reproduce: https://huggingface.co/spaces/jerpint/babelfish

**Comment by abidlabs** [comment]
@aliabid94 it looks like the API docs for `Audio` output are incorrect. Would be good to review all of the file components since they have similar payloads

See this discussion: https://github.com/gradio-app/gradio/discussions/2739

**Comment by abidlabs** [comment]
cc @aliabd would you be able to take this one as well?

**Comment by aliabd** [comment]
Yes @abidlabs sure
