### ISSUE TITLE
iframe content can't be loaded when deployed on Huggingface

### ISSUE THREAD

**Issue by phosseini** [gradio-app/gradio#2734]
### Describe the bug

I've included an `iframe` tag on my page where the content will be generated by calling a URL with a parameter (I call the URL with one parameter, it generates some content, and I want to show that content in my app). When I run my app locally, the content is loaded successfully. But when I deploy my app on Huggingface space, the content does not appear and all I see is just an empty placeholder with nothing (it looks like my app does create the `iframe` tag but it cannot load and show the content from the URL even though it can when run locally).

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr


def get_content(my_input):
    the_url = "http://sorry-can't-share-the-url={}".format(my_input)
    c = """<iframe src="{}" style="width:100%; height:400px;"></iframe>""".format(the_url)
    return c

with gr.Blocks() as demo:
    an_string_input = 'something'
    with gr.Row():
        show_content_btn = gr.Button("Show my content")
    my_output = gr.HTML()
    show_content_btn.click(fn=get_content, inputs=an_string_input, outputs=my_output)

demo.launch()
```

### Logs

```shell
There is no log
```

### System Info

```shell
Python 3.9
Gradio 3.5
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks for creating the issue @phosseini. Does this happen only with your own URL or with generally any URL? Perhaps you can find and another example URL that has the same problem that you could share with us so that we can reproduce. Thanks!

**Comment by abidlabs** [comment]
Will go ahead and close for lack of reproduction.

**Comment by phosseini** [comment]
> Thanks for creating the issue @phosseini. Does this happen only with your own URL or with generally any URL? Perhaps you can find and another example URL that has the same problem that you could share with us so that we can reproduce. Thanks!

Thanks for the follow-up and sorry for the late reply. Just tested with some other examples and it looks like it does work for other URLs (some websites/URLs do not allow access even locally). So it's just a URL issue, not a Gradio issue.

**Comment by abidlabs** [comment]
Good to hear, thanks for letting us know!
