### ISSUE TITLE
static assets does not load, making the whole site blank when `iface.launch(share=False)`

### ISSUE THREAD

**Issue by vaasu** [gradio-app/gradio#274]
This was discovered while running the code from Getting Started. 
Steps to reproduce:
1 - on a fresh install of Ubuntu, 
2 - `pip install gradio`
3 - `python3 main.py` with code from simple script in Getting started, 

```
import gradio as gr

def greet(name):
  return "Hello " + name + "!"

iface = gr.Interface(
  fn=greet, 
  inputs=gr.inputs.Textbox(lines=2, placeholder="Name Here..."), 
  outputs="text")
iface.launch()
```

Expected:
1 - Webpage loaded with similar interface from Getting started guide.

Actual output:
1 - Blank white screen

- Diving deeper into the code, the pip install does not install static assets to the `gradio/frontend` folder in `site-packages`
- only two files exist there, `asset-manifest.json` and `index.html`
- When `iface.launch()` is invoked without parameter (implicit share=False) , it executes [this line](https://github.com/gradio-app/gradio/blob/19d5a5cc3127933bbfe41ad62f9df1697de5e27d/gradio/networking.py#L140) which attempts to take non existing static assets from local folder as opposed to AWS.

**Comment by aliabid94** [comment]
Yikes, taking a look. What gradio version?

**Comment by vaasu** [comment]
latest, 2.3.2 . Thanks. 2.3.1 also have the same problem.

**Comment by aliabid94** [comment]
I see it. Just pushed 2.3.3 with fix.

**Comment by aliabid94** [comment]
Thanks for bringing to our attention!
