### ISSUE TITLE
"Duplicate Space" & "Share to Community" buttons

### ISSUE THREAD

**Issue by gary149** [gradio-app/gradio#2749]
Implement the button directly in Gradio API.
`gr.ShareButton` by @merveenoyan could work well 👍 

![image](https://user-images.githubusercontent.com/3841370/204886429-01bfb364-52bf-4207-9aaf-f31f4473f62a.png)

**Comment by abidlabs** [comment]
Thanks for the suggestion @gary149! Similar to #2269, we need to figure out the right way to share Gradio outputs in a general way.

**Comment by merveenoyan** [comment]
I was wondering about whether to enable an option to share the output when creating the Interface or Blocks. If we know the app is launched from Spaces (which I don't know if it's the case) we could enable sharing the output button by default.

**Comment by julien-c** [comment]
i would also support integrating it into Gradio

**Comment by gary149** [comment]
I've been thinking about it a bit more and I think it makes sense to expand the issue to "Expose some Spaces options inside Gradio", I think it will really improve DX and UX.

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/3841370/214537151-f53ed99e-3e08-4990-a9bb-0a3395882e02.png">

**Comment by abidlabs** [comment]
cc @dawoodkhan82 @aliabid94 something to think about after the bug bashing sprint!

**Comment by yvrjsharma** [comment]
This feature implementation can help us drive a good amount of growth cc: @AK391 @abidlabs
