### ISSUE TITLE
Microphone input is not working

### ISSUE THREAD

**Issue by deepak242424** [gradio-app/gradio#275]
I am trying to create a demo on my laptop. It should record a file from Microphone and plot the spectrogram for it. When I am trying to record via microphone it just stopped immediately and hence nothing gets recorded.

I am using Macbook and trying to run the demo locally on the laptop. I am using gradio==2.3.0.

```
def spectrogram(audio):
    sr, data = audio
    if len(data.shape) == 2:
        data = np.mean(data, axis=0)
    frequencies, times, spectrogram_data = signal.spectrogram(data, sr, window="hamming")
    plt.pcolormesh(times, frequencies, np.log10(spectrogram_data))
    return plt


iface = gr.Interface(spectrogram, "microphone", "plot")

iface.test_launch()
if __name__ == "__main__":
    iface.launch()
```

**Comment by aliabid94** [comment]
Taking a look. Seems like another user reported something similar.

**Comment by aliabid94** [comment]
Did your browser prompt you for microphone access?

**Comment by deepak242424** [comment]
Yes, it asked. And allowed the permission.

**Comment by aliabid94** [comment]
Can you provide browser and OS? Also can you see if https://12885.gradio.app works for you? Just launched your code with share=True.

**Comment by deepak242424** [comment]
I am using Mac Big Sur v11.5.2. I tried both on Google-Chrome and Safari but it didn't work.

I tried the link shared by you, it is also not working for me. I can see the record button but as soon as I am clicking it, empty file is getting submitted.

**Comment by aliabid94** [comment]
Interesting, will test on a Mac and get back to you.

**Comment by deepak242424** [comment]
Thanks. Meanwhile can you please let me know on which OS it is working for you?

**Comment by aliabid94** [comment]
It works on Windows 10 chrome for me.

**Comment by aliabid94** [comment]
Was able to reproduce on Mac. Fixing now.

**Comment by aliabid94** [comment]
Can you try with Gradio 2.3.4?

**Comment by deepak242424** [comment]
After installing v2.3.4 I am able to record the voice on Mac, but the spectrogram is coming empty. I am trying to tun the code mentioned in my first comment.

**Comment by abidlabs** [comment]
Can you please try the following code and let us know if it works for you? If so, then it's not an issue with `gradio` but perhaps with `signal.spectrogram`?

```
def identity(audio):
    sr, data = audio
    return (sr, data)

iface = gr.Interface(spectrogram, "microphone", "audio")
iface.launch()
```

If this does not return the original recorded file, then please reopen and we'll do more testing on Macs.
