### ISSUE TITLE
Refactor `gr.Blocks.load()` in 4.0

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#2754]
`gr.Blocks.load()` is both a class method and an instance method, which is confusing. We should refactor this in 4.0. 

Here's a proposal:
* Deprecate `gr.Blocks.load()` and `gr.Interface.load()`
* Instead of the class method, define a `gr.load()` that can be used to load any Space whether it be Blocks/Interface, or a model
* For the event trigger, define an instance method `Blocks.page_load()`

**Comment by aliabd** [comment]
+1 to this, I was confused myself.

**Comment by freddyaboulton** [comment]
This is already done on `v4` but `Blocks.load` is now an instance method and only defines load events. No `page_load` was added.
