### ISSUE TITLE
Microphone stops working after pressing the clear button.

### ISSUE THREAD

**Issue by harveenchadha** [gradio-app/gradio#276]
What is the issue?
Microphone stops working after pressing the clear button

How to replicate this issue?
Go to this [space](https://huggingface.co/spaces/Harveenchadha/wav2vec2-vakyansh-hindi)

1. Press record and submit
2. Output will come. Now press on clear button.
3. Click on record again.

You will see recording will stop automatically.

Any fixes for this?

**Comment by aliabid94** [comment]
Taking a look.

**Comment by aliabid94** [comment]
Hmm it worked fine for me actually on initial test, will debug harder. Can you provide OS and browser version?

**Comment by aliabid94** [comment]
Was able to reproduce on Mac. Fixing now.

**Comment by harveenchadha** [comment]
OS: Ubuntu.
Browser: Chrome Version 92.0.4515.107 

Same behaviour I can observe in mac as well.

**Comment by abidlabs** [comment]
Should be fixed. If not, please let us know and reopen this. Thanks @harveenchadha!
