### ISSUE TITLE
Opening of multidimensional files

### ISSUE THREAD

**Issue by callum-jpg** [gradio-app/gradio#2765]
### Describe the bug

I have been finding that when trying to load multidimensional (3D) images (for example 15, 256, 256 in z, x, y) that the z dimension is dropped. This has been observed in tiff files, even when `gr.File(type="binary")` is used.

When the same array is stored as a `.npy`, the array shape is maintained. 

I would have expected for files that have been loaded as type binary using `gr.File` to not be changed on loading.

Is there any trick that I'm missing to get this to work?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Create multidimensional arrays locally:
```
import skimage

arr = skimage.data.binary_blobs(50, n_dim=3)

skimage.io.imsave("ndim_array.tiff", arr)
np.save("ndim_array.npy", arr)
```

Run app and either load `.tiff` with the skimage line or `.npy` with the np.load line. 

Outside of gradio, both loading functions return a numpy array with shape (50, 50, 50).
```
import gradio as gr
import skimage
import numpy as np
import io

def process_array(image_path):
    # For loading .tiff
    # arr = skimage.io.imread(io.BytesIO(image_path))

    # For loading .npy
    arr = np.load(io.BytesIO(image_path))

    return arr.shape

inp = [
    gr.File(type="binary"),
]

output = [
    gr.outputs.Textbox()
]

demo = gr.Interface(
    fn=process_array, 
    inputs=inp, 
    outputs=output,
    )

demo.launch()
```

### Logs

```shell
NA
```

### System Info

```shell
gradio==3.12.0 with Python 3.9 running inside a jupyter-notebook
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @callum-jpg !

I see the problem with `bytes` but it doesn't happen when you use a regular File component:

```python
import gradio as gr
import skimage
import numpy as np
import io

def process_array(image_path):
    # For loading .tiff
    arr = skimage.io.imread(image_path.name)

    # For loading .npy
    #arr = np.load(io.BytesIO(image_path))

    return arr.shape

inp = [
    gr.File(),
]

output = [
    gr.Textbox()
]

demo = gr.Interface(
    fn=process_array, 
    inputs=inp, 
    outputs=output,
    )

demo.launch()
```

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/41651716/205754317-898644db-d623-4f6f-a405-d3ef41e05855.png">

**Comment by callum-jpg** [comment]
That's superb, thank you so much @freddyaboulton
