### ISSUE TITLE
Allow pasting in `gr.Image` component

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#2770]
- [x] I have searched to see if a similar issue already exists.

**Describe the solution you'd like**  
I would like to have an image in my clipboard and be able to paste it in the `gr.Image` component

**Comment by abidlabs** [comment]
Thanks @apolinario, agreed this would be quite nice. We had some discussion in this issue: https://github.com/gradio-app/gradio/issues/735. I'll close this issue, feel free to add any suggestions onto that issue!
