### ISSUE TITLE
📂 File Browser component

### ISSUE THREAD

**Issue by camenduru** [gradio-app/gradio#2771]
**Is your feature request related to a problem? Please describe.**  
🤗 has no file browser when we use gradio in 🤗 we don't have native gradio file browser like gallery 

**Describe the solution you'd like**  
simple file browser upload download maybe search features

**Additional context**  
Colab
![Screenshot 2022-12-05 212855f](https://user-images.githubusercontent.com/54370274/206260827-23490e08-d361-42ac-8128-d1d200166d50.jpg)

Kaggle
![Screenshot 2022-12-05 213111](https://user-images.githubusercontent.com/54370274/206260664-89733f5c-6ac5-4d8e-abb2-59d733e8094c.jpg)

**Comment by abidlabs** [comment]
Interesting, can you elaborate a little more on the use case here? I assume that this would allow you to preview files that are uploaded on the Space itself. What kind of files do you want to upload/download from Spaces as opposed to from the user's computer?

**Comment by camenduru** [comment]
Hi @abidlabs 👋 I am working on this https://huggingface.co/spaces/camenduru/webui I will use 📁 File Browser component for Textual Inversion and Dreambooth Training, user will upload images .jpg or .png from user's computer in to a folder after training done user will download .ckpt and .pt files from folder to user's computer.

**Comment by camenduru** [comment]
@aliabid94 how user browse and download files when training done? Please build a simple 📁 File Browser component 🤗 needs a simple input output gradio can give 🤗 this fundamental need also you can combine 📁 File Browser with simple text editor 🎉

**Comment by camenduru** [comment]
@aliabid94 after your question, it looks like this feature request will stay here untouched for months 😋 if you don't want to build please tell me I will close the issue and I will found an other solution

**Comment by camenduru** [comment]
@aliabid94 thank you for the super cool 📁 File Browser ❤

**Comment by abidlabs** [comment]
Let's keep this open until the FileBrowser is released :)
