### ISSUE TITLE
Markdown support in `Chatbot` "breaks" older code

### ISSUE THREAD

**Issue by johnPertoft** [gradio-app/gradio#2775]
### Describe the bug

Gradio 3.12 added markdown support for the `Chatbot` component which is very useful but is not backwards compatible for functions making use of the chat history passed in.

In `gradio<3.12` the history passed in looks like
```
[('hello!', "I don't know")]
```

In `gradio>=3.12` the history passed in looks like
```
[('<p>hello!</p>\n', "<p>I don't know</p>\n")]
```

Probably not a big deal, and is easy to handle on the user side, but could silently reduce performance of a language model for example.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Run the chatbot demo app in `gradio<3.12` and `gradio>=3.12`
- Compare the history passed in to your function

### Logs

```shell
n/a
```

### System Info

```shell
- Gradio 3.12.0
- Ubuntu 22.04
```

### Severity

annoying

**Comment by dawoodkhan82** [comment]
@abidlabs should the postprocess return the message and response strings if no markdown is found?

**Comment by abidlabs** [comment]
@dawoodkhan82 we could just strip the `<p>` tags and `\n` from the final result -- I think it won't change how it renders and will make it truly backwards compatible. Thoughts?

**Comment by dchichkov** [comment]
It seems that the issue is still there, for different tags.  For example, Chatbot silently replaces ` characters surrounding the code block with <code> tag. 

Here's an example that can reproduce this:
`
import gradio as gr

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()

    def respond(message, chat_history):
        bot_message = "`some code`"
        chat_history.append((message, bot_message))
        print(chat_history)
        return "", chat_history

    msg.submit(respond, [msg, chatbot], [msg, chatbot])

demo.launch()
`

**Comment by abidlabs** [comment]
Hi @dchichkov are you using the latest version of `gradio`? If so, would you please be able to create a new issue, along with a repro we can take a look at?

**Comment by dchichkov** [comment]
@abidlabs   Thanks, looks like I was on an unlucky version 3.28.3 with that issue.  It's no longer there in the 3.33.1.
