### ISSUE TITLE
Upload filetypes of specified extensions.

### ISSUE THREAD

**Issue by davidbernat** [gradio-app/gradio#2776]
I would like my application to use a proprietary text file format using a non-standard extension. The text file is still a simple text file, and the non-standard extension is used internally by my software to specify an expected formatting of the text. To my knowledge, `UploadFile` and `File` do not allow specifying what extensions to accept, only to specific from an internally represented list of text file extensions using the `file_types['text']` parameter. Is this accurate? If so, I request the feature. Thank you.

**Comment by abidlabs** [comment]
Thanks for the suggestion @davidbernat, agreed that this would be good to have.
