### ISSUE TITLE
UploadFile() fails for files with zero size (such as those created by touch)

### ISSUE THREAD

**Issue by davidbernat** [gradio-app/gradio#2778]
### Describe the bug

Create an empty file using command line: `touch document.txt`
Uploading this file via `UploadFile()` fails. 
Gradio expects to derive its extension from its header, when fallback to its filename extension is sufficient.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See above.

### Screenshot

<img width="489" alt="Screenshot 2022-12-08 at 10 31 20 AM" src="https://user-images.githubusercontent.com/5396131/206488820-940c1148-59b9-4b74-b331-0e9cc6798223.png">
<img width="727" alt="Screenshot 2022-12-08 at 10 31 35 AM" src="https://user-images.githubusercontent.com/5396131/206488871-c94b648f-b177-4593-916f-467c9d0fa293.png">

### Logs

```shell
N/A
```

### System Info

```shell
N/A
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks for reporting this bug @davidbernat, we'll look into it!
