### ISSUE TITLE
Internal server error at sign up

### ISSUE THREAD

**Issue by nathanshammah** [gradio-app/gradio#278]
This is an issue encountered on the website, so I am not sure it fits in here. 

If I try to sign up on https://gradio.app/ with my Github account details (username + 2FA), there is an internal server error, which reads: 
```
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
I believe the details are correct. If I try to click on "Sign In" again, I am redirected to the same url with no option to update the login information.

**Comment by aliabid94** [comment]
There does seem to be some issue with our infra. Taking a look!

**Comment by aliabid94** [comment]
Can you try again? I believe there was an infra issue that I've resolved.

**Comment by nathanshammah** [comment]
It now works, thank you @aliabid94.
