### ISSUE TITLE
Add preset color schemes for gradio plots

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2780]
> We'll probably want to update the color schemes for visualisations in the future with a few pre-baked options for users. Data-viz colour schemes have some specific requirements/ demands that fall outside of typical 'design' issues. We can address that (and the duplication) later.

_Originally posted by @pngwn in https://github.com/gradio-app/gradio/pull/2764#discussion_r1043436605_

**Comment by pngwn** [comment]
Some examples of different types of palette can be found here: https://carbondesignsystem.com/data-visualization/color-palettes/

I'll try to find some more resources to guide us as well. We need to consider color blindness etc when choosing good defaults.

**Comment by aliabid94** [comment]
As of #8550, matches gr.themes for Altair plots. Still should do some matching for plotly.

**Comment by abidlabs** [comment]
This is great! I don't think we want to do this for plotly/matplotlib/bokeh since people generate the plots using those libraries outside of gradio and then gradio simply displays them (we wouldn't want to change the color on the users) -- but it makes sense for our native plot components
