### ISSUE TITLE
Switch (or hot swap) demos dynamically (without breaking down server)?

### ISSUE THREAD

**Issue by davidbernat** [gradio-app/gradio#2787]
Question: I have two entirely independently composed GUIs. Each of them work as expected. I would like to offer the user the option to switch back and forth between these GUIs from within the GUI. This question is not about refactoring, such that situating the two GUIs each in their own tab, etc., is not an answer to this question. 

`gui.launch()` initiates the creation of a GUI and creation of a URL/port for accessing the GUI. 
Is there an equivalent of `gui1.switch(gui2)`?

My understanding that `gui1.launch()` then `gui1.close()` then `gui2.launch()` is a system-level operation (breaks down a gui, breaks down a server, restarts a server, etc; with several seconds of latency) and not a user-design operation (hot swapping guis which have both been pre-loaded).

Is this feature available? 

Thank you.

**Comment by abidlabs** [comment]
Hey @davidbernat it may be possible to achieve this behavior by doing something like this:

```py
import gradio as gr

io1 = gr.Interface(lambda x:x, "textbox", "textbox")
io2 = gr.Interface(lambda x:x, "image", "image")

io1.launch()
```

To switch over to `io2`, you can do this:

```py
io1.get_config_file = io2.get_config_file
io1.launch()
```

Now when you run `io1.launch()`, you'll notice that it runs a lot faster since it doesn't break down the server, it uses the existing server. This admittedly is a hack and we can't guarantee its future-proof-ness, but I think it should work for you

**Comment by davidbernat** [comment]
Yo @abidlabs: I have not tried this yet, and not knowing anything about the behind the surface implementation, but because the components are different, this appears to be the solution to the effective ask of this thread. You are telling me that the GUIs can be rendered directly from the config file, and that the config file render it higher enough in the stack (than the server, etc) that the replacement (re-render) of the GUI is much (much) faster.  This would be a wonderful feature improvement. I am working on a suite of apps that are already five or six deep and the render time of the entire server at boot is already slowing to several half-dozen seconds, and soon will be more than tab-switching for browsing alone can handle: I would prefer to only load the tabs necessary for the context of the application the user has chosen, and that is the hot swapping problem this feature improvement would solve. This also provides a feature improvement to the discussion ongoing in #7290 (Google Authentication re: Firebase) because this solution allows keeping from the unauthorized user the layout of the application they begin to access when they are authorized. Happy to share my code if you would like to take a look at some of what I have implemented in my previous repositories re: #7290.

**Comment by davidbernat** [comment]
@abidlabs: I am not yet able to get the suggested approach to work in my environment. In this example, the application consists of a selector (from which one of six model categories can be chosen, each with its own GUI) and, underneath the selector is the GUI for the specific model category in the selector. Once the selector chooses its next model category to use, the hot swap function is called. It is here that I am confused about what syntax can be used to appropriately persist the category_gui variable, and also the proper syntax for closing and relaunching the gui. 

<img width="1055" alt="Screenshot 2022-12-13 at 7 33 31 PM" src="https://user-images.githubusercontent.com/5396131/207475470-18b4d8f6-1b4a-4a4d-acf6-d7205a8ba6ab.png">

**Comment by abidlabs** [comment]
Ah sorry I didn't realize that you wanted to choose the guis from within a Gradio app as well. I thought you wanted to hot-swap from outside the Gradio app, like in a jupyter notebook. So just to be clear, you'd like to have a Dropdown, and based on the value selected in the dropdown, you'd like to show one of various different GUIs? 

If that's the case, then I recommend changing the visibility of a `gr.Row()` containing each GUI. Here's an example:

```py
import gradio as gr

io1 = gr.Interface(lambda x:x, "textbox", "textbox")
io2 = gr.Interface(lambda x:x, "image", "image")

def show_row(value):
    if value=="Interface 1":
        return (gr.update(visible=True), gr.update(visible=False))  
    if value=="Interface 2":
        return (gr.update(visible=False), gr.update(visible=True))
    return (gr.update(visible=False), gr.update(visible=False))

with gr.Blocks() as demo:
    d = gr.Dropdown(["Interface 1", "Interface 2"])
    with gr.Row(visible=False) as r1:
        io1.render()
    with gr.Row(visible=False) as r2:
        io2.render()
    d.change(show_row, d, [r1, r2])
    
demo.launch()
```

Here's what it looks like:

![Recording 2022-12-13 at 20 03 07](https://user-images.githubusercontent.com/1778297/207487026-8597009e-05be-427c-a891-e138ed9cabe5.gif)

Side note: for future reference, better to have these discussions in the GitHub Discussion forum or in Discord (as this is not a bug or feature request). Thanks!

**Comment by davidbernat** [comment]
I will move the discussion to the Discord. Your solution works. But my effort for hotswap is to minimize the amount that needs to be rendered at any one time. Rendering six applications takes about ten seconds. Presumably I can write the config file to disk and load. But presumably twenty to one hundred elements is not the idea use case for the software at this time. :-)
