### ISSUE TITLE
Freeing GUI port more quickly after closing server? 

### ISSUE THREAD

**Issue by davidbernat** [gradio-app/gradio#2788]
During debugging sessions, where I will load a server, make a change to the code, then reload the software again, I notice that the port usually stays open for minutes at a time, even after using `gui.close()` and `gui.close_all()`. This prevents the user from relaunching the gui (unless a system level cli command is used to close the port, etc). Is there a way to configure the gui to ensure rapid closing of the port, or to force the ports to close?

**Comment by freddyaboulton** [comment]
Hi @davidbernat ! Are you using reload mode? https://gradio.app/developing_faster_with_reload_mode/

If you do `gradio app.py` instead of `python app.py` the app will automatically relaunch when you make changes to the app.py file.

**Comment by davidbernat** [comment]
@freddyaboulton: I have looked closer at your recommendation of the command line tool `gradio app.py`. While this indeed does seem like a wonderful command line tool for developing the GUI, the question I have is about developing the production environment in which the GUI sits. In other words, the GUI is one process in a subsystem that includes a backend server to handle data requests from the GUI. Lots of these systems require development. In each case, the GUI needs to be shut down and restarted when the backend server and other tools are modified (see below). It does not seem clear to me that the intended use case of `gradio app.py` is to be executed as a subprocess (see below); nor that doing so would solve the problem of slow times between breakdown of the GUI and starting of the GUI server. Can you comment? Thanks. 
<img width="799" alt="Screenshot 2022-12-12 at 7 50 43 AM" src="https://user-images.githubusercontent.com/5396131/207050024-2b9d110e-23f1-4bdc-81c5-66ef8ec9bd09.png">

**Comment by freddyaboulton** [comment]
Hi @davidbernat ! Yea `gradio app.py` is not production grade. That's for quickly iterating on a gradio app by leveraging the underlying starlette server's automatic reload feature.

Let me make sure I understand - You have a gradio demo in which your event handles make requests to another server running on your machine, correct? 

In that case, if your event handlers are communicating via REST to `api_app` why do you need to restart the gradio app when you make a change to the external process? You should be able to just restart the `api_app` independent of gradio and the gradio event handlers will use the "latest" `api_app`.

**Comment by freddyaboulton** [comment]
> What you are saying is to refactor the code for the backend app to look for an existing copy of the GUI and to not launch a second copy if one exists.

Yea I think that would work in your case! The server start/shutdown is determined by uvicorn (the server that runs gradio) not sure how we can speed that up on the gradio side.

**Comment by abidlabs** [comment]
Can we go ahead and close this issue @davidbernat?

**Comment by davidbernat** [comment]
Quick question for users: this workflow requires the backend service to "check whether a Gradio GUI service is running [on a specific port and host] and [running a particular configuration file, whether an up-to-date iteration, or associated with one application rather than another]. Does Gradio have service methods for confirming either of those, rather than using, for instance Python system level tools to check whether the port that Gradio is occupied or not?

**Comment by abidlabs** [comment]
Gradio doesn't keep track of all of the running GUIs. However, if you have handles for all of the running GUIs, you can get the port by doing `gui.server_port` and the host by doing `gui.server_name`

**Comment by abidlabs** [comment]
I hope that answers your question @davidbernat. Feel free to reopen if it doesn't and there's a feature you are requesting.
