### ISSUE TITLE
forced audio normalization on audio output

### ISSUE THREAD

**Issue by babua** [gradio-app/gradio#2789]
- [x ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
In [this](https://github.com/gradio-app/gradio/blob/a580a93510a440e24d999adf7ff4a29861d4ddeb/gradio/processing_utils.py#L228) line, audio is normalized by peak silently if converting from float to wav. 

At first glance this is a sane thing to do. However if your algorithm is playing around with loudness at all, it will mean that you will never hear the results on the output. Because practically, most audio processing libraries and algorithms work with float format (e.g. librosa), and the most browser-compatible format to render audio is int16 -- which is also Gradio's defaut. 

I realize this has an impact (if minor) on most user's UX, and is an opinionated choice. Anyway I've patched it on my local and I just wanted to make you aware of the issue. 

**Describe the solution you'd like**  
Apply normalization only if values exist in wav larger than 1, because as long as all values are within [-1,1], scaling by 32767 in the next line will not fail. Audio will not be as loud as it possibly can in general, but it will reflect the actual model/processing output and users can just turn up their volume too. 

```
    if data.dtype in [np.float64, np.float32, np.float16]:
        warnings.warn(warning.format(data.dtype))
        if np.abs(data).max() > 1:
            data = data / np.abs(data).max()
        data = data * 32767
        data = data.astype(np.int16)
```

Another potential solution, with a little bit or refactoring is to add "normalize by amplitude" as a parameter to `gr.Audio()` that's default `True`.

**Comment by abidlabs** [comment]
Thanks for the suggestion @babua, we'll look into it!

**Comment by osanseviero** [comment]
Hi there! I actually had this same issue today. I think it might be worth mentioning in the docs that the audio is normalized to avoid confusion.
