### ISSUE TITLE
Allow overriding  the 5000 data rows limit for for altair visualizations

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2797]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Altair will throw an error if the dataframe has more than 5000 rows: https://altair-viz.github.io/user_guide/faq.html#maxrowserror-how-can-i-plot-large-datasets

I think this limitation is reasonable as every row of the dataset gets mapped to a mark on the chart and visualizing more than 5000 points on a scatterplot, for example, will probably not look good anyways.

That being said, we should decide what should happen when someone inevitably passes more than 5000 rows to our visualization components. 

Options include:

- suppress altair error and proceed anyways
- raise informative error from gradio

**Describe the solution you'd like**  

**Additional context**

**Comment by abidlabs** [comment]
Similar to Altair itself, I think we should raise an error explaining that a very large webpage will be created but also give users a simple way to override if they know what they're doing

**Comment by venkatavamsidama** [comment]
Handling the Altair limitation on the number of rows in a dataframe is indeed important. Given the options you've mentioned, I'd suggest incorporating a combination of both to provide flexibility to users.
1)Suppress Altair Error and Proceed
2)Suppress Altair Error and Proceed

**Comment by freddyaboulton** [comment]
I think you may have mistyped @venkatavamsidama.You said the same thing twice 😅
