### ISSUE TITLE
Add information on hosting fee

### ISSUE THREAD

**Issue by nathanshammah** [gradio-app/gradio#280]
Right now, the only part I can read about the hosting service is on
https://gradio.app/hosted, which is visible only by having logged in already, 
```
Please add billing information to enable hosting models on Gradio. There is a $7 charge per month to host models on Gradio.
```

The same sentence is also present on https://gradio.app/introducing-hosted (visible to anyone), under the "Why Hosted?
" blurb and "How does hosted work?" at "Step 3 - Create a Gradio Account".

1. It would be better to make this information stand out more in the page. 
2. The message could be a bit more precise on the technical details of the offer (how much space? how many models / repo are included? etc)
3. It could be better from a (first-time) user perspective to find a page on the website, dedicated to the pay options, possibly referenced in the top menu,  with subscription information. A table could compare free vs hosted vs private subscription models. 

Great project, hope this feedback is useful.

**Comment by abidlabs** [comment]
Closing as a redesign of the website is in the works

**Comment by nathanshammah** [comment]
Thanks for the feedback, keep it up!
