### ISSUE TITLE
Colab without share=True - 403 Error

### ISSUE THREAD

**Issue by amrrs** [gradio-app/gradio#2800]
### Describe the bug

I never could get the Gradio on Colab (without the external gradio link) work. Whenever the argument `share=True` wasn't passed, on Colab I always ended up getting 403 error. 

I searched with 403 and I couldn't find a similar error.  

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run the latest Gradio on Colab and launch it without `share=True` 

### Logs

```shell
It's the Colab Tunneling related error (not necessarily Gradio error)
```

### System Info

```shell
Latest Gradio
Google Colab (Linux)
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @amrrs can you share an example of what code you were trying to run in Colab that wasn't working?

**Comment by amrrs** [comment]
For ease Screenshot:
![image](https://user-images.githubusercontent.com/5347322/207130834-39f7c825-ccbb-4d04-93af-fccd04958c17.png)

**Comment by abidlabs** [comment]
So strange, works for me: 
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/1778297/207136317-a0963e44-7c27-4bdc-a356-520c8c7b5052.png">

Would you be able to open up the inspector and tell us more about the 403 error if there is more info?

**Comment by amrrs** [comment]
Thanks for letting me know. I figured out the problem. It's the AdBlocker on my Brave browser. When the Ad blocker is disabled, it works fine. If the Adblocker is enabled I get 403. I'll close this issue now.

**Comment by DavidD003** [comment]
I had this same issue, same resolution. Thanks so much for sharing!!
