### ISSUE TITLE
Can output=gr.File() accept a base64 encoded uri (RFC 2397)? 

### ISSUE THREAD

**Issue by davidbernat** [gradio-app/gradio#2803]
The dynamics of `gr.File()` are giving me trouble. Formally, the `gr.File()` object is expected to receive a path to a local filename. However, my GUI uses a backend service to present images, and presenting the an [RFC 2397](https://www.rfc-editor.org/rfc/rfc2397) (`data:image/png,base:etc...`) or a URL to a static resource would be simpler. The URL approach is not supported (GUI throws an error that the URL is a file not found) and the URI approach is not accepted either (a XY error of the 'filename' being too long).

**Comment by abidlabs** [comment]
The `gr.File()` component requires a file with a standard file name. Could you save the base64 representation to a file? Gradio includes a utility function to do that: `gr.processing_utils.decode_base64_to_file()`

**Comment by davidbernat** [comment]
@abidlabs: I can save a file to a local disk. I prefer to use `NamedTemporaryFiles(delete=True)` to ensure garbage collection, whereby the files are removed at the end of the user session. But `NamedTemporaryFiles(delete=True)` seems to incur two problems: the garbage collection seems to require I build a session-persisting class object to hold scope until an appropriate time to delete the files (which I am happy to build) and that each call to the input-output functions seems to change the location of the temporary file since input-output functions receive a `TemporaryFileWrapper`. I have seen several tickets on the these troubles but unable to find a 'the definitive way' in any of the component docs. :-)

**Comment by abidlabs** [comment]
> each call to the input-output functions seems to change the location of the temporary file since input-output functions receive a TemporaryFileWrapper. I have seen several tickets on the these troubles but unable to find a 'the definitive way' in any of the component docs.

This will be solved soon!

**Comment by davidbernat** [comment]
Excellent. Until then, you recommend using persisting local temporary files. Regarding the scope problem, there are no solutions unless a garbage breakdown context manager is used ... the previous temporary files could be deleted whenever an associated Gradio component is updated or changed.

**Comment by abidlabs** [comment]
Yes unfortunately I don't think there is a good solution for the persistence issue because there is no way to know that a Gradio app has finished running and it is safe to garbage-collect

**Comment by abidlabs** [comment]
Will close this issue, please follow #2758 to know when the temp file issue is resolved
