### ISSUE TITLE
Proper way to obtain Element() builder type? 

### ISSUE THREAD

**Issue by davidbernat** [gradio-app/gradio#2809]
### Describe the bug

To dynamically handle inbound json data, and properly reformat these for Gradio elements, I need to identify the type of a Gradio element. I noticed that elements do not consistently have the `.type` attribute. Also, in some places in my code, I have found that `gr.Files().type == 'files'` and other places `gr.Files().type == 'file'`. In my production code the function returns the former, yet in my reproduction code it returns the latter.

<img width="729" alt="Screenshot 2022-12-13 at 8 10 05 PM" src="https://user-images.githubusercontent.com/5396131/207480278-0410ced7-018d-47bb-88df-1ee72bcb7c25.png">

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See above.

### Logs

```shell
N/A
```

### System Info

```shell
Version: 3.12.0
MacBook 2020; Ventura 13.0.1
```

### Severity

annoying

**Comment by abidlabs** [comment]
> To dynamically handle inbound json data

By this, do you mean when you use the gradio demo via the API? If so, is this the same as this issue: https://github.com/gradio-app/gradio/issues/2364?

**Comment by abidlabs** [comment]
Lmk @davidbernat if this is a separate issue or if we can go ahead and close.

**Comment by davidbernat** [comment]
@abidlabs Please give me a day or two. I will notify you. Thanks. Appreciated.

**Comment by abidlabs** [comment]
Hi @davidbernat I'm going to go ahead and close this issue so that we can have a clearer picture of the open issues. Feel free to reopen with more details as needed, thanks
