### ISSUE TITLE
Javascript methods double-wrapping returns

### ISSUE THREAD

**Issue by d8ahazard** [gradio-app/gradio#2815]
### Describe the bug

When creating a .click() listener for a gr.button, if the listener has both a _js method and a fn, it seems as if the returns from the _js are sometimes created as a list within a list, so when the .predict function is run, an indexerror is thrown because the actual values are all within the first element of inputs, which is the actual list of values.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://github.com/d8ahazard/brokegradio

Clone the repo, install reqs if necessary, run "run.py". Click the button at the top.

### Screenshot

![image](https://user-images.githubusercontent.com/1633844/207687612-4093e192-bcc0-4ebb-9cd8-3441a33fbd3d.png)

### Logs

```shell
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "E:\dev\eff_gradio\venv\lib\site-packages\gradio\routes.py", line 301, in run_predict
    output = await app.blocks.process_api(
  File "E:\dev\eff_gradio\venv\lib\site-packages\gradio\blocks.py", line 1005, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\dev\eff_gradio\venv\lib\site-packages\gradio\blocks.py", line 915, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range
```

### System Info

```shell
Gradio version: 3.13.0 - 3.9.0
Windows 11
Python 3.10
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks for creating this issue @d8ahazard! We'll investigate
