### ISSUE TITLE
Changing from video example while playing makes new videos unplayable

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#2844]
### Describe the bug

A bit easier to understand with reproduction section

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Go to https://huggingface.co/spaces/anzorq/riffusion-demo
2. Click one example
3. Click play in the video
4. While the video is playing, change to another example

At this point, the video button is as if it were running and there's no way for me to play it.

### Logs

```shell
None
```

### System Info

```shell
Spaces, Chrome,3.13.2
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks @osanseviero. Same as #2651, no?

**Comment by osanseviero** [comment]
That's right :) I knew there was some report somewhere. Closing as this is a duplicate!
