### ISSUE TITLE
push Gradio elem_id value into its rendered HTML 

### ISSUE THREAD

**Issue by davidbernat** [gradio-app/gradio#2845]
Gradio components render their HTML. These components are provided an `id="component-[NUMBER]"` where `[NUMBER]` is the sequential number the Gradio system assigns each element when they are rendered. While this number is accessible in the Python configuration file for each element, some of these elements have explicitly assigned `elem_id` values. It would be more accessible to match up HTML from Python code where these values propagated forward into the HTML: if not setting the `id` value of its corresponding `<div></div>` itself, then as an attribute `elem_id` to those `<div></div>` elements. Thoughts? Thanks!

**Comment by abidlabs** [comment]
Isn't that already the case? If you set the `elem_id` property of a component, the div corresponding to that component is assigned that as the `id`. If this isn't happening for you, then it's most likely a bug -- please feel free to share a code example (both the Python and the rendered HTML would be helpful)

**Comment by pngwn** [comment]
If an explicit `elem_id` is not being set then it is expected that the values are not stable (could change either across gradio versions or as the app is modified). Explicitly setting `elem_id` will give stable ids. If the latter isn't the case then that is a bug, but the former not giving stable ids is expected.

**Comment by abidlabs** [comment]
Just as in the other issue, @davidbernat I'm going to go ahead and close this so that we can have a clearer picture of the open issues. Feel free to reopen with more details as needed, thanks
