### ISSUE TITLE
16bits images

### ISSUE THREAD

**Issue by RAHoebe** [gradio-app/gradio#2849]
### Describe the bug

![nuclei](https://user-images.githubusercontent.com/46439648/208461527-b09c1957-1250-401d-8de7-05ccb8a555aa.png)

I try to load an 16 bits grayscale image with:

demo = gr.Interface(
    query_image, 
    inputs=[gr.Image()], 
    outputs="image",
    title="Nuclei Demo",
    examples=[["nuclei.png"]]
)

This however returns an 8-bits image with all values equal to 255.

I need to be able to read the 16 bits images for my project.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

def query_image(img):
    print(imgpath)

demo = gr.Interface(
    query_image, 
    inputs=[gr.Image()], 
    outputs="image",
    title="Nuclei Demo",
    examples=[["nuclei.png"]]
)

### Logs

```shell
no logs
```

### System Info

```shell
v3.14.0
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @RAHoebe, thanks for opening this issue. Based on [this StackOverflow answer](https://stackoverflow.com/a/57627715/5209347), I'd recommend that you use Gradio to preprocess the image as a PIL image, and then convert it to numpy from within the `query_image` function. The code might look something like this:

```py
def query_image(img):
  im = np.array(img).astype("uint16")
  ...

demo = gr.Interface(
  query_image,
  inputs=[gr.Image(type="pil")],
  outputs="image",
  title="Nuclei Demo",
  examples=[["nuclei.png"]]
)


```

**Comment by RAHoebe** [comment]
Hi, I tried this already (and now again) in different ways. It does not work. Also the option "filepath" saves a temporary  file with only 255's

**Comment by abidlabs** [comment]
Hmm can you please provide more details -- what do you mean by it does not work?

**Comment by RAHoebe** [comment]
im = np.array(img).astype("uint16")  does not help. The 16 bits image (example in first post) gives only 255's back.

**Comment by abidlabs** [comment]
Hi @RAHoebe I tried a few different things, and what worked for me was doing this `Image.fromarray(np.array(Image.open("nuclei.png")).astype("uint16"))`:

```py
import gradio as gr
import numpy as np

def query_image(img):
  im = Image.fromarray(np.array(Image.open("test.png")).astype("uint16"))
  return im

demo = gr.Interface(
  query_image,
  inputs=[gr.Image(type="pil")],
  outputs="image",
  title="Nuclei Demo",
  examples=[["nuclei.png"]]
).launch()
```

Here's how it looks:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/1778297/209574738-7ae44d92-9000-420c-9a6b-9ccbb929f1c6.png">

If this works for you, we can close this issue. Otherwise, please let us know if it doesn't work

**Comment by abidlabs** [comment]
I'll go ahead and close this @RAHoebe. If it doesn't work for you, please feel free to reopen with more details!

**Comment by lvZic** [comment]
@abidlabs not work. 
the pil image returned by gr.Interface is RGB format, which means has 'uint8' format.
