### ISSUE TITLE
Pickle is unable to load a SHAP explainer object

### ISSUE THREAD

**Issue by johnkuangwork** [gradio-app/gradio#285]
Hi, I am trying to load a SHAP explainer object but failed to launch gradio hosting. But there is no issue run and launch on local juypterlab...

explainer = pickle.load(file), seems unable to run...any ideas? thank you!!!

Error message:
----------------------------------------------------------------------------------------------------------------------------------
  | Starting container...
  | public: http://54.185.190.133:7860/
  | IPython could not be loaded!
  | Trying to unpickle estimator DecisionTreeClassifier from version 0.24.2 when using version 1.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
  | https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  | Trying to unpickle estimator RandomForestClassifier from version 0.24.2 when using version 1.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
  | https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  | Traceback (most recent call last):
  | File &#34;Online V1.py&#34;, line 39, in &lt;module&gt;
  | explainer = pickle.load(file)
  | File &#34;/usr/local/lib/python3.7/site-packages/numba/core/serialize.py&#34;, line 97, in _unpickle__CustomPickled
  | ctor, states = loads(serialized)
  | TypeError: code() takes at most 15 arguments (16 given)

</body>
</html>

**Comment by abidlabs** [comment]
It looks like this is an issue with different version of Python (see this for example: https://github.com/RedisGears/redisgears-py/issues/13). Gradio Hosted runs Python 3.7, so if you can make sure the explainer was pickled on a system running Python 3.7, it should work.
