### ISSUE TITLE
[docs] more examples button height too large in firefox

### ISSUE THREAD

**Issue by pi43r** [gradio-app/gradio#2850]
### Describe the bug

Hey,
not quite sure why `h-2/4`  is behaving differently in firefox 108.0.1 for me, but the buttons is extremely large and breaks the flow of the page to become unreadable in some instances. Using `h-auto` behaves as expected, but I haven't done a proper evaluation.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

First occurance for me on firefox: https://gradio.app/docs/#blocks-header 

### Screenshot

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/3011806/208561260-c109ca6a-1987-4a1e-95cc-6b4602cf318b.png">

### Logs

```shell
no logs needed
```

### System Info

```shell
MacOS monterey, firefox 108.0.1
```

### Severity

annoying

**Comment by abidlabs** [comment]
@aliabd assigning this the docs/website label

**Comment by pi43r** [comment]
I don't see any change in the css, but it seems to be fixed for me (at least on firefox on my linux machine)

I will close this, if nobody else is experiencing this issue.
