### ISSUE TITLE
Split the `Interface` class into separate classes for the different kinds of Interfaces

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#2851]
Right now, the `Interface` class is very convoluted with many if conditions, etc. because we create slightly different layouts depending on if the Interface is:

* standard interface
* input-only interface
* output-only interface
* a "united" interface where the input is the output

We should refactor this code to have separate classes for each of these types to make the code easier to maintain and understand.

**Comment by freddyaboulton** [comment]
This is an internal refactoring right? 

There will still only be one `Interface` class but internally it will delegate to `OutputOnlyInterface`, `StandardInterface`, etc?

**Comment by abidlabs** [comment]
Yes exactly, this won't be a user-facing change
