### ISSUE TITLE
CheckboxGroup individual visibility or have event handler modify choices on front-end

### ISSUE THREAD

**Issue by Gerschel** [gradio-app/gradio#2854]
- [✔️ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
A niche problem. It's more of an order of operations issue. I pull a list of items to include from a json file. My script is ran in two different scenarios where most but not all options apply.
I can work around it. This is a nice to have but not necessary.

**Describe the solution you'd like**  
Send an update back to CheckboxGroup with visible as a list to match each checkbox in the group. It could either match by name or a list with a length of items in CheckboxGroup with bools.  
The other option, is to have choices be changed in the front-end like how dropdown's allow it.

**Additional context**  

Is an option on this page:

![image](https://user-images.githubusercontent.com/9631031/208628612-8b3e8b6a-32fa-4617-a2a3-25a3b70cef52.png)

Is not an option on this page:

![image](https://user-images.githubusercontent.com/9631031/208628851-046494a1-d81c-4e42-9539-8e609ed94f5f.png)

**Comment by qqubb** [comment]
I'm seeing the following error from the above code:

`AttributeError: type object 'CheckboxGroup' has no attribute 'update'`
