### ISSUE TITLE
Check demo notebooks fails with gradio_cached_examples

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#2862]
### Describe the bug

https://github.com/gradio-app/gradio/pull/2860#issuecomment-1359935508

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

N/A

### Logs

```shell
N/A
```

### System Info

```shell
N/A
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
This is a special case of this imo: https://github.com/gradio-app/gradio/issues/2756

**Comment by aliabd** [comment]
Oh true, completely missed that issue. Do you want me to take it? Can add it to website-priority milestone if so

**Comment by abidlabs** [comment]
Just going through the issues. Let me close this and @aliabd can you assign @2756 to yourself?
