### ISSUE TITLE
queue=True does not work if default_enabled=False

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2863]
### Describe the bug

I have a demo with two events. One with `queue=False` and one with `queue=True`. 

I set `default_enabled=False` in `queue`. 

The event with `queue=True` does not complete. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:

    with gr.Row():
        name = gr.Textbox(label="name")
        greeting = gr.Textbox(label="greeting")
        greet = gr.Button(value="Greet")
    with gr.Row():
        num = gr.Number()
        num_2 = gr.Number()
        double = gr.Button(value="Double")
    
    greet.click(lambda s: f"Hello, {s}!", inputs=name, outputs=greeting, queue=False)
    double.click(lambda s: s * 2, inputs=num, outputs=num_2, queue=True)

demo.queue(default_enabled=False).launch()
```

### Screenshot

![image](https://user-images.githubusercontent.com/41651716/208738875-0b9a4918-fcbd-47d3-9b06-59bd87904d98.png)

### Logs

```shell
-
```

### System Info

```shell
main
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
This is expected, right? If no queue is set up, then you cannot assign `queue=True` in any event listener. That being said, it shouldn't fail silently, but raise an error

**Comment by freddyaboulton** [comment]
@abidlabs The queue is set up via the `queue` method in my repro, no?

I think the "bug" here is the `default_enabled` parameter. The docstring says, 

> If True, all event listeners will use queueing by default.

Which to me implies that only those events with `queue=True` or `queue=None` will be queued. However, it actually controls whether or not the queue is started which I don't think is the intended behavior? 

Can we deprecate `default_enabled`?

**Comment by abidlabs** [comment]
Ah sorry I missed that. Yeah the `default_enabled` parameter is confusing. Would be in favor of deprecating that in 4.0. I don't think the case of setting up queuing but having it disabled by default makes much sense. Would you agree @aliabid94?

**Comment by freddyaboulton** [comment]
Thoughts on:

-  set default value to `None` of `default_enabled`
- Raise a warning if `default_enabled` is not `None`
- Modify `queue` so that `default_enabled` has no effect

And we can remove it in 4.0 entirely. That way we can close this out, imo.

**Comment by abidlabs** [comment]
Seems reasonable to me!

**Comment by TashaSkyUp** [comment]
@abidlabs I need the queue to be off by default and turned on for specific events. Please advise.

**Comment by freddyaboulton** [comment]
Hi @TashaSkyUp !

All the events have a queue parameter which can be either set to True or False to determine if that event should be queued.

I think you’ll have to manually specify which events should not be on the queue this way!
