### ISSUE TITLE
apply gr.Box border compacting to nested rows and columns 

### ISSUE THREAD

**Issue by aliabid94** [gradio-app/gradio#2865]
I see users using `gr.Box` to remove internal padding with nested Rows and Columns, e.g. 
<img width="473" alt="Screen Shot 2022-12-20 at 3 27 13 PM" src="https://user-images.githubusercontent.com/7870876/208770236-8e2f4fcd-33e7-4f6d-a97d-1bc2305134e6.png">

The border-rounding get glitchy with nested rows and columns as seen above

**Comment by abidlabs** [comment]
This has been fixed as part of the `gr.Group` changes, thanks @aliabid94
