### ISSUE TITLE
request to add clear button in Tab blocks as well

### ISSUE THREAD

**Issue by pavanpraneeth** [gradio-app/gradio#2869]
when we use tabs blocks and launchit , there is no clear button Please tell me any way to add it or please add the feature

**Comment by abidlabs** [comment]
Hi @pavanpraneeth, please add more details explaining the feature request. A code example would be helpful. thanks

**Comment by pavanpraneeth** [comment]
Ok so when u normally launch the gradio without using any blocks , a simple one there is a clear button coming which will clear all inputs if we want. But when we use some blocks , none of the block has clear button. 
If this is not clear please say me how to create clear button which will clear all input fields like a reset button

**Comment by abidlabs** [comment]
Appreciate the clarification @pavanpraneeth. I agree this would be a nice button to expose. We have an open issue for this here: #1719 -- let me go ahead and close this one. Feel free to chime in on #1719 issue
