### ISSUE TITLE
CSS code not showing background image in Gradio app

### ISSUE THREAD

**Issue by RubensZimbres** [gradio-app/gradio#2873]
### Describe the bug

The css code added to the demo does not show the background image in the app. Also, I tried in Markdown and does not work either. This problem was reported at Hugging Face forum, but not solved: https://discuss.huggingface.co/t/add-background-image/16381

I also tried with a file locally and also with a file hosted in a public Google Drive folder. Neither of them work.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I'm using as an app for matching job seekers and job vacancies for a client.

```
def predict(text):
    campos=str(text).lower()
    query=np.sum([model.user_model(tf.constant(campos.split()[i])) for i in range(0,len(campos.split()))],axis=0)
    neighbors, distances = searcher.search_batched([query])
    xx = df.iloc[neighbors[0],:].nome_vaga
    return xx
```

```
demo = gr.Interface(fn=predict, inputs=gr.inputs.Textbox(label='CANDIDATE COMPETENCES - Click *Clear* before adding input'), outputs=gr.outputs.Textbox(label='SUGGESTED VACANCIES'),css='body{background-image:url("https://drive.google.com/file/d/1IH467kY7b8kOBBkV_GO46pRxtbyFTw0v");}').launch(share=False)  
```

### Screenshot

![gradio](https://user-images.githubusercontent.com/20270054/208950302-79dadbc2-940e-4f23-bb54-ee5b0f0a319e.png)

### Logs

```shell
/home/anaconda3/lib/python3.9/site-packages/gradio/inputs.py:26: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
/home/anaconda3/lib/python3.9/site-packages/gradio/deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
/home/anaconda3/lib/python3.9/site-packages/gradio/deprecation.py:40: UserWarning: `numeric` parameter is deprecated, and it has no effect
  warnings.warn(value)
/home/anaconda3/lib/python3.9/site-packages/gradio/outputs.py:21: UserWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components
  warnings.warn(
Running on local URL:  http://127.0.0.1:7910

To create a public link, set `share=True` in `launch()`.
```
```


### System Info

```shell
gr.__version__
'3.14.0'

I'm running the app in Ubuntu 22.04, Google Chrome Version 107.0.5304.121 (Official Build) (64-bit). Code was developed in VS Code inside an anaconda environment running on Python 3.9.7.
```

### Severity

annoying

**Comment by pngwn** [comment]
I think we could solve this via the new theming system that is being implemented as it will be more reliable than pure css. We will need to solve the core issue, which seems to be paths not working as expected. I'll take a look at this soon.

**Comment by pngwn** [comment]
Okay the problem actually seems to be google drive rather than gradio. The default link you are using is a link to the gdrive 'viewer' web app. You need to manipulate the link a little to get the desired results.

Use this url instead: `https://drive.google.com/uc?export=view&id={file-id}`

the `file-id` here is the long string after `https://drive.google.com/file/d/`.

Can you see if that solves the problem for you?

**Comment by RubensZimbres** [comment]
Nope, I tried with Google Drive (public image) and also uploaded the file to Google Cloud Storage, public access/link and does not work either testing locally or in a public link for the app.

**Comment by RubensZimbres** [comment]
I solved it. The correct code is `div { background` instead of `body { background` plus your path fix suggestion:

```
demo = gr.Interface(fn=predict, inputs=gr.inputs.Textbox(label='CANDIDATE COMPETENCES - Click *Clear* before adding input'), \
    outputs=gr.outputs.Textbox(label='SUGGESTED VACANCIES'),\
        css='div {background-image: url("https://drive.google.com/uc?export=view&id=1IH467kY7b8kOBBkV_GO46pRxtbyFTw0v")}').launch(share=False)   
```
