### ISSUE TITLE
Ablity to pick more than 1 flag item - feature request

### ISSUE THREAD

**Issue by johnyquest7** [gradio-app/gradio#288]
It would be great if we could select more than 1 flag item.
For example flags could be
- Correct diagnosis
- Wrong diagnosis
- Correct description
- Wrong description

then the user should be able to chose multiple combinations for 1 image like correct diagnosis and correct description. 
This will help in research setting while validating a model.

**Comment by abidlabs** [comment]
Thanks for the feedback @johnyquest7! We'll have to see if we can implement this in a way that does break how flagging options are currently implemented. In the meantime, what about the options being:
- "Correct diagnosis and description"
- "Correct diagnosis only"
- "Correct description only"
- "Incorrect diagnosis and description"
