### ISSUE TITLE
title argument for `TabbedInterface` 

### ISSUE THREAD

**Issue by MohamedAliRashad** [gradio-app/gradio#2882]
If `TabbedInterface` is an interface like others it needs a title and description like `Interface`

**Comment by abidlabs** [comment]
Thanks for the suggestion @MohamedAliRashad. Would you be interested in working on a PR for this?

**Comment by MohamedAliRashad** [comment]
@abidlabs I started a PR for this, any suggestions would be appreciated

**Comment by abidlabs** [comment]
Added my suggestion to the PR here: #2888
