### ISSUE TITLE
Frontend: Dev mode broken if demo has a plot

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2892]
> @freddyaboulton The addition of the altair plots broke dev mode (when using `PLOT`),I should have caught this when the PR went in but I only tested the build. In future we should make sure we don't break dev mode when we merge PRs if possible.

> For now `Plot` just won't work in dev mode (I don't have a fix right now, it will require a bit more work), i have fixed the build now though, so I'll push that with the rest of the changes soon.

_Originally posted by @pngwn in https://github.com/gradio-app/gradio/issues/2840#issuecomment-1366007358_

To close:
`pnpm dev` should be able to run a demo with a plot component

**Comment by abidlabs** [comment]
Just tested and this is not an issue anymore:

<img width="1376" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/743df38a-aa8d-451b-b8e9-0c12d7443bb6">

**Comment by freddyaboulton** [comment]
Sweet
