### ISSUE TITLE
a video component for handling YouTube videos?

### ISSUE THREAD

**Issue by davidbernat** [gradio-app/gradio#2894]
The `gr.Video()` component works using local filenames or urls. But what is the expected use case for embedded video platforms like Youtube? YouTube is protective of its video access urls, as far as I understand this. What has the community been doing?

For example, the `youtube_dl` package does provide urls to the direct video codec files, and using those urls does successfully render the video file from the Chrome URL bar. These do not work (as successfully) in Gradio components. 

```
url = "https://www.youtube.com/watch?v=akHOzLoAMYk"
import youtube_dl
with youtube_dl.YoutubeDL() as ydl:
    info = ydl.extract_info(url, download=False)

import gradio as gr
with gr.Blocks() as gui:
    gr.Video(value=info['formats'][0]['url'])
```

I searched the Gradio issues and found no instances of `YouTube`.

To clarify: the difficulty of using the video-file url of `youtube_dl` is that YouTube throttles its download speeds. (Here you can see a 2MB video file took 30 seconds.) Appropriate solution is to create an HTML frame, or some equivalent. But that does not answer the question of accessing the data. 

<img width="614" alt="Screenshot 2022-12-27 at 4 16 40 PM" src="https://user-images.githubusercontent.com/5396131/209723246-b7256ce0-991d-41aa-a538-8e9889d11480.png">

**Comment by abidlabs** [comment]
I don't think we'll create a native component for YouTube videos (although users might be interested in creating custom components, when do that down the line). The best solution I would say is to embed the YT video, which works pretty well for me:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/1778297/209738963-c36404c6-e047-4964-971d-2d129002aa53.png">


The code here is: 

```py
import gradio as gr

embed_html = '<iframe width="560" height="315" src="https://www.youtube.com/embed/EngW7tLk6R8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'

with gr.Blocks() as demo:
    gr.HTML(embed_html)
    
demo.launch()
```

**Comment by davidbernat** [comment]
🙏 @abidlabs 

1. There is no implicit way to access the audio or video from within the `gr.HTML` element than the direct urls from e.g. `youtube_dl`, is that correct? That does not seem quite accurate, but I do not know video platforms well enough yet.
2. At the current time, user created Components must be added to the official Gradio repository to be used at all, and this is still not open access. Is this still true, and do you have a mailing list to follow for technical updates? 
3. My life is better knowing that video exists. Thank you.

**Comment by abidlabs** [comment]
@davidbernat 

1. Yes, that is correct 
2. Correct, but we will provide support for custom components that do not need to be added to the Gradio repo in next several months. Probably best the follow the [Twitter account](https://twitter.com/Gradio) or [join our Discord](https://t.co/JKepTfXraQ) for now
3. :)

Will go ahead and close since that seems to answer the question, but feel free to reopen if not!

**Comment by dwipper** [comment]
On first try above embed approach didn't work by copying the URL of the video from Youtube. But after Googling "Embed Youtube Video", there was a mention to right-click on the video and get the embed code from there. Using that code, it worked.
