### ISSUE TITLE
Improvements to color-sketch UX

### ISSUE THREAD

**Issue by Alchete** [gradio-app/gradio#2903]
Hi all, we're using color-sketch in the Automatic1111 webui and while it's powerful, it would be great to see some enhancements to make the user experience more fluid.

Without re-thinking the entire color-sketch UI, here are some ideas that would be great to see either on the existing UI or a next-gen one:

- Catch key events inside color-sketch, to enable some of the following features
- Add hotkeys "[" and "]" to decrease and increase the size of the brush by 1 point, respectively.  (These hotkeys align with Photoshop)
- Add hotkey "x" to invert the brush.  (again aligns with Photoshop).  This will toggle between painting and removing.  Here the brush would change color from black to white.
- Add mousewheel "zoom to cursor" (aka Google Maps zoom) when the color-sketch UI has active focus (I can provide the algorithm if needed)
- Add a slider for "Opacity", to allow the user to turn down the visual opacity so they can see what's behind their brush strokes

**Comment by abidlabs** [comment]
Closing as it looks like these have been replaced with individual issues (#3279, #3278, #3281), which is even better, thanks @Alchete!
