### ISSUE TITLE
ColorPicker.change; When output is blank or empty list, using _js, `Uncaught (in promise) ... undefined (reading 'forEach'`

### ISSUE THREAD

**Issue by Gerschel** [gradio-app/gradio#2907]
### Describe the bug

I have what I need working. But this one took me some time to figure out. Partially because the documentation says you would handle no outputs with an empty list.

Using the `change` event handler for colorpicker:
I haven't tested this on other components, this could be expected behavior because the use case is low. But I figure I'd report it anyways so there's a record for others to use for debugging their code in case it happens to them.  

If you are not needing the `fn` parameter, you would set it to None, or maybe add a lambda: print() for debugging. Whether or not you are using the function parameter.  
If you don't need an output, because you are using the `_js` parameter to manipulate something else on the front-end; it's set to an empty list.  You will get an error in the browser, because it tries to iterate through the outputs parameter with a forEach, and the parameter was not used.    

A workaround for others that may read this.  
Create a component you intend to keep hidden, it will need to be rendered still. I used a gr.Text component  
Put this in your output, because even if you don't return anything from the javascript function, there's always a return, and something need to catch it, and the forEach needs something in it's array.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks(analytics_enabled=False, css="") as demo:
    colorpicker = gr.ColorPicker(
    )
    text = gr.Text()

    colorpicker.change(
        fn = None,
        _js="(x) => { console.log(x) }",
        inputs= colorpicker,
        outputs=[]
    )


demo.launch(server_port=8888)
```

### Screenshot

![image](https://user-images.githubusercontent.com/9631031/210032917-a071a36d-4331-4f3b-9d5e-751bc1e33ae0.png)

![image](https://user-images.githubusercontent.com/9631031/210033321-aca8fbf3-6422-4a36-936d-f74d0b181dbd.png)

### Logs

```shell
index.73c7a9d5.js:55 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach') at tt (index.73c7a9d5.js:55:2421)
tt	@	index.73c7a9d5.js:55
Promise.then (async)		
(anonymous)	@	index.73c7a9d5.js:55
(anonymous)	@	index.73c7a9d5.js:4
Kn	@	index.73c7a9d5.js:4
w	@	ColorPicker.svelte:20
(anonymous)	@	index.73c7a9d5.js:4
(anonymous)	@	index.73c7a9d5.js:4
c	@	ColorPicker.svelte:22
W.s.$$.update	@	ColorPicker.svelte:14
Ii	@	index.73c7a9d5.js:4
be	@	index.73c7a9d5.js:4
onVisualColorChange_	@	unknown
onColorSelectionRingUpdate_	@	unknown
updateColor	@	unknown
onPositionChange_	@	unknown
set	@	unknown
moveTo	@	unknown
moveColorSelectionRingTo_	@	unknown
pointerDown	@	unknown
onColorWellMouseDown_	@	unknown
Promise.then (async)		
fe	@	index.73c7a9d5.js:4
zi	@	index.73c7a9d5.js:4
(anonymous)	@	index.73c7a9d5.js:4
k	@	index.73c7a9d5.js:34
i	@	index.73c7a9d5.js:34
(anonymous)	@	index.73c7a9d5.js:4
i	@	ColorPicker.svelte:20
r	@	ColorPicker.svelte:28
(anonymous)	@	index.73c7a9d5.js:4
a	@	ColorPicker.svelte:22
onVisualColorChange_	@	unknown
onColorSelectionRingUpdate_	@	unknown
updateColor	@	unknown
onPositionChange_	@	unknown
set	@	unknown
moveTo	@	unknown
moveColorSelectionRingTo_	@	unknown
pointerDown	@	unknown
onColorWellMouseDown_	@	unknown
```

### System Info

```shell
3.9
```

### Severity

annoying

**Comment by abidlabs** [comment]
This is actually expected behavior. The `_js` event handler is a little weird (which is why we've kept this as an internal parameter for now), but it expects the function to return a value for every input and output. 

We should come up with a more intuitive API, but we can do it as part of this issue: https://github.com/gradio-app/gradio/issues/2479
