### ISSUE TITLE
how to auto update the state for busy error

### ISSUE THREAD

**Issue by ltm920716** [gradio-app/gradio#2909]
hello，
I use the queue() function in my application，and set ’max_size=2‘，
it will alert the error ’This application is too busy....‘ as bellow:
![image](https://user-images.githubusercontent.com/12007227/210049136-933d2236-1ac8-491e-8d37-b4eeaac3b290.png)
but the page state does not update automatic， so I must refresh the page manually，so if there is a way to auto update the page state？

Thanks！

**Comment by abidlabs** [comment]
Hi @ltm920716, for general questions, please [use our Discord](https://t.co/JKepTfXraQ) or [GitHub Discussions](https://github.com/gradio-app/gradio/discussions). Only use GitHub issues if you find a bug in the Gradio codebase or if you have a feature request.
