### ISSUE TITLE
missed setup.py when run "bash script/install_gradio.sh"

### ISSUE THREAD

**Issue by paulxiong** [gradio-app/gradio#2912]
### Describe the bug

I am trying to build Gradio from source code.  Following the instruction of CONTRIBUTING.md, 
```
_ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /mnt/gradio-3/gradio
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)_

```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

git clone https://github.com/gradio-app/gradio.git
cd gradio 
bash script/install_gradio.sh

### Screenshot

![image](https://user-images.githubusercontent.com/75286/210156819-052a5d10-d040-4c84-892d-a7bf49820eb9.png)

### Logs

```shell
_ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /mnt/gradio-3/gradio
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)_
```

### System Info

```shell
Gradio version: 1.15.0
Ubuntu 20.04
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Hi @paulxiong it looks like you might be using an older version of `pip` or `setuptools`. Can you upgrade both to the latest version and then try again? 

See here: https://stackoverflow.com/a/69711730/5209347

**Comment by paulxiong** [comment]
problem solved after upgrade setuptools to 65.7.0. thanks.

**Comment by paulxiong** [comment]
problem solved after upgraded setuptools to 65.7.0. thanks.

**Comment by abidlabs** [comment]
Thanks for letting us know @paulxiong!

**Comment by pangyuteng** [comment]
@abidlabs  been going through some gradio's github issues, kudos for being so responsive.

--

for those following [custom-components-in-five-minutes](https://www.gradio.app/guides/custom-components-in-five-minutes), freshly installed node will likely also complain about not knowing what `python` is, SO ppl suggest installing (python/crate-alias and gcc)[https://stackoverflow.com/a/69776021/868736] (?).
```
python3 -m pip install --upgrade pip
pip install setuptools --upgrade
sudo apt install python3 python-is-python3 gcc
```
