### ISSUE TITLE
[dx] generating notebooks doesn't skip gitignored files

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#2913]
### Describe the bug

When running `python generate_notebooks.py` from `/demo/` the script doesn't skip all gitignored files which led to some very confusing failures for me.

It does have a list of files to skip but it doesn't ignore `config.json` files that we sometimes generate for tests and it doesn't seem to skip the cached examples folder that is sometimes present (forgotten what it is called). Although we could explicitly ignore these files/ folders, it would be better if we could just use the `.gitignore` list because there are all kinds of weird log + debug files that can end up in various folders.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

-

### Screenshot

-

### Logs

```shell
-
```

### System Info

```shell
-
```

### Severity

annoying

**Comment by abidlabs** [comment]
This is the same issue as https://github.com/gradio-app/gradio/issues/2756? It should be fixed now though thanks to a recent fix by @aliabd. Have you merged in the latest from `main`?

**Comment by aliabd** [comment]
yeah @pngwn, all gitignored files should be getting skipped now. if it's not working properly still let me know

**Comment by pngwn** [comment]
Ah. This was prior to merging main will check and close.

**Comment by pngwn** [comment]
Ah. This was prior to merging main will check and close.

**Comment by abidlabs** [comment]
We can close this yeah @pngwn?
