### ISSUE TITLE
Gradio Blocks Config Dev Mode as Environment Variable

### ISSUE THREAD

**Issue by stikkireddy** [gradio-app/gradio#2917]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As someone deploying gradio apps that are using blocks, I do not want to modify code to enable and disable development mode. It would be great if it can be configured by an environment variable or some other manner other than modifying code.

**Describe the solution you'd like**  
Something like GRADIO_DEV_MODE=false option if you want dev mode to be default and backwards compatible. 

Ideally i want to do something like 
`GRADIO_DEV_MODE=false uvicorn --host 0.0.0.0 --port 9999 my_app:demo.app`

**Additional context**  
Trying to have a better configuration based solution around the solutions offered in #2427

**Comment by abidlabs** [comment]
Good suggestion, thanks @stikkireddy! I think this would indeed improve the DX, would you be open to making a PR for this?

**Comment by stikkireddy** [comment]
@abidlabs any suggestions sure i can make a stab at this would you be comfortable with `GRADIO_DEV_MODE` to be used as the env variable?

**Comment by abidlabs** [comment]
Yes that seems reasonable to me, as it parallels `GRADIO_SERVER_PORT` and `GRADIO_NUM_PORTS` in `networking.py`

**Comment by abidlabs** [comment]
Hi @stikkireddy just out of curiosity, did you get a chance to work on this?

**Comment by stikkireddy** [comment]
hey sorry i was swamped with day to day. @abidlabs I will be able to make the PR tomorrow if that still works.

**Comment by abidlabs** [comment]
Sure @stikkireddy not a problem at all!

**Comment by abidlabs** [comment]
Friendly nudge @stikkireddy :)

**Comment by abidlabs** [comment]
Hi @stikkireddy as we haven't really heard a lot of demand for this issue, I'll go ahead and close it. If you're interested in making a PR at some point, feel free to reference this closed issue. Thanks!
