### ISSUE TITLE
Gradio launch( share=True ) Not working !!!

### ISSUE THREAD

**Issue by kareemgamalmahmoud** [gradio-app/gradio#2918]
### Describe the bug

When I tried the official Colab notebook with this setup :  

`gradio.Interface(fn=greet, inputs="text", outputs="text").launch(share=True)`

The cell works without issuing any public link.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

[GRADIO: Hello World.ipynb ](https://colab.research.google.com/drive/18ODkJvyxHutTN0P5APWyGFO_xwNcgHDZ?usp=sharing)

### Screenshot

![image](https://user-images.githubusercontent.com/51359449/210287882-dc06d725-5497-4590-b8c2-f0e99f1e88b9.png)

### Logs

```shell
No Logs
```

### System Info

```shell
Google Colab env.
```

### Severity

annoying

**Comment by adilrahman** [comment]
I am also facing this issue 
alternative solution:- you can launch that in local env by setting share=False then you can use this command for port forwarding `!npx localtunnel --port <your-local-port>`

**Comment by pazkero** [comment]
By the way, forcing a downgrade to Gradio 3.9 still works ─ It seems only Gradio 3.13+ are broken.

**Comment by sjstone2838** [comment]
I am also experiencing this issue, trying to run gradio in a databricks notebook
<img width="748" alt="image" src="https://user-images.githubusercontent.com/14966742/210307709-42d03cae-01c9-4472-8a69-3fda69e885c4.png">

**Comment by pazkero** [comment]
Related/Useful: 

> [tsukimiya](https://github.com/tsukimiya) commented [16 hours ago](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6210#issuecomment-1368980238)
> This seems to be a gradio problem.
> gradio changed the network method in 3.13, but probably due to a fault, it can no longer get the URL from the connection and freezes at this location.
> 
> https://github.com/gradio-app/gradio/blob/58b1a074ba342fe01445290d680a70c9304a9de1/gradio/tunneling.py#L93-L97
...
> gradio connects to the host:port described in https://api.gradio.app/v2/tunnel-request and gets the URL ( (hash).gradio.live ) to use.
> However, there has been no response from this host since about 2023-01-02 06:20:00 (UTC), and the URL cannot be obtained.

**Comment by ShadeRedeye** [comment]
i use,stable-diffusion in paperspace and looks like in latest ver(or maybe in 3.10-latest),it make interface got hang,and some image can't use functionally (such result,send to img2img etc),i try rollback to 3.9 and everything is work again

**Comment by abidlabs** [comment]
Hi @ShadeRedeye, if you can create a small demo with what is not working (along with any error longs), that would be helpful for us to understand the issue

**Comment by ShadeRedeye** [comment]
@abidlabs hmm creating small demo seems difficult for me,but i can give you link to a demo stable-diffusion-webui that i use in paperspace 

here : 
https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/blob/master/StableDiffusionUI_Voldemort_paperspace.ipynb

based some issue,it said in the latest ver,gradio can't proxy file larger than 2mb when web-UI share to internet (AKA set Share=true).
https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/issues/49

when using ngrok will goin fix issue,it also make having problem,bcoz paperspace didn't like tunneling proxy like that.

what i can to make it normal again,is when i reverting gradio ver to 3.9

**Comment by wchao1115** [comment]
Hey @abidlabs , I also run into this issue with 3.16.2. It only gives out local URL despite setting `demo.launch(share=True)`. You should be able to run my repro hosted in replit: https://replit.com/@metarooster/Model-UI#modui.py. The launch call is literally the last line in the source file. Please advise.

**Comment by SondosBsharat** [comment]
Hey, I don't know if any one of you faced this issue or not, actually the demo.launch() command keeps running for more than one hour and it did not finish, is this normal? and I need to wait more? or there is an issue somewhere? 
Note: my model is not that heavy

**Comment by Kefan-pauline** [comment]
I still encountered this behavior with gradio==3.38.0 in a remote notebook that is different from colab, kaggle, sagemaker etc.

The following code
```
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
demo.launch(share=True)
```
outputs only `Running on local URL:  http://127.0.0.1:7860/`, and the kernel keeps busy. If I terminate the kernel manually, I got

> KeyboardInterrupt                         Traceback (most recent call last)
> Cell In [34], line 1
> ----> 1 demo.launch(share=True) 
> 
> File /usr/local/lib/python3.8/dist-packages/gradio/blocks.py:1932, in Blocks.launch(self, inline, inbrowser, share, debug, enable_queue, max_threads, auth, auth_message, prevent_thread_lock, show_error, server_name, server_port, show_tips, height, width, encrypt, favicon_path, ssl_keyfile, ssl_certfile, ssl_keyfile_password, ssl_verify, quiet, show_api, file_directories, allowed_paths, blocked_paths, root_path, _frontend, app_kwargs)
>    1930 try:
>    1931     if self.share_url is None:
> -> 1932         self.share_url = networking.setup_tunnel(
>    1933             self.server_name, self.server_port, self.share_token
>    1934         )
>    1935     print(strings.en["SHARE_LINK_DISPLAY"].format(self.share_url))
>    1936     if not (quiet):
> 
> File /usr/local/lib/python3.8/dist-packages/gradio/networking.py:190, in setup_tunnel(local_host, local_port, share_token)
>     186     remote_host, remote_port = payload["host"], int(payload["port"])
>     187     tunnel = Tunnel(
>     188         remote_host, remote_port, local_host, local_port, share_token
>     189     )
> --> 190     address = tunnel.start_tunnel()
>     191     return address
>     192 except Exception as e:
> 
> File /usr/local/lib/python3.8/dist-packages/gradio/tunneling.py:59, in Tunnel.start_tunnel(self)
>      57 def start_tunnel(self) -> str:
>      58     self.download_binary()
> ---> 59     self.url = self._start_tunnel(BINARY_PATH)
>      60     return self.url
> 
> File /usr/local/lib/python3.8/dist-packages/gradio/tunneling.py:95, in Tunnel._start_tunnel(self, binary)
>      93 if self.proc.stdout is None:
>      94     continue
> ---> 95 line = self.proc.stdout.readline()
>      96 line = line.decode("utf-8")
>      97 if "start proxy success" in line:
> 
> KeyboardInterrupt: 

Any idea how can I display the gradio interface in the notebook? @abidlabs Thanks a lot!
