### ISSUE TITLE
Cannot queue with encryption or authentication enabled.

### ISSUE THREAD

**Issue by johnyquest7** [gradio-app/gradio#293]
Unable to queue when authentication is enabled.

**Comment by abidlabs** [comment]
How significant is this use case @johnyquest7? Queueing is designed for public demos with high traffic (e.g. on Space), while I envision authentication essentially for private demos with lower traffic.

**Comment by johnyquest7** [comment]
Not a priority now. Thanks for looking into this.

**Comment by xxWeiDG** [comment]
> Thanks for letting us know @johnyquest7!

Hi Does queue support auth now?

**Comment by freddyaboulton** [comment]
Yes fixed in #2611
