### ISSUE TITLE
cannot render a html file which use echarts.js

### ISSUE THREAD

**Issue by haowuliao** [gradio-app/gradio#2935]
### Describe the bug

I want to the output render html which use echarts.js to show a graph, but the graph cannot appear.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

the python code below：

import gradio as gr

def text_analysis(text):
    html = (
        ""
        + """<!DOCTYPE html>\n\n<html>\n\n<head>\n\n    <meta charset="UTF-8">\n\n    <title>Awesome-pyecharts</title>\n\n            <script type="text/javascript" src="https://assets.pyecharts.org/assets/v5/echarts.min.js"></script>\n\n\n\n</head>\n\n<body >\n\n    <div id="e8a41f256d8046879dbbb3e6e7cbb307" class="chart-container" style="width:2000px; height:1000px; "></div>\n\n    <script>\n\n        var chart_e8a41f256d8046879dbbb3e6e7cbb307 = echarts.init(\n\n            document.getElementById(\'e8a41f256d8046879dbbb3e6e7cbb307\'), \'white\', {renderer: \'canvas\'});\n\n        var option_e8a41f256d8046879dbbb3e6e7cbb307 = {\n\n    "animation": true,\n\n    "animationThreshold": 2000,\n\n    "animationDuration": 1000,\n\n    "animationEasing": "cubicOut",\n\n    "animationDelay": 0,\n\n    "animationDurationUpdate": 300,\n\n    "animationEasingUpdate": "cubicOut",\n\n    "animationDelayUpdate": 0,\n\n    "aria": {\n\n        "enabled": false\n\n    },\n\n    "color": [\n\n        "#5470c6",\n\n        "#91cc75",\n\n        "#fac858",\n\n        "#ee6666",\n\n        "#73c0de",\n\n        "#3ba272",\n\n        "#fc8452",\n\n        "#9a60b4",\n\n        "#ea7ccc"\n\n    ],\n\n    "series": [\n\n        {\n\n            "type": "graph",\n\n            "layout": "force",\n\n            "symbolSize": 10,\n\n            "circular": {\n\n                "rotateLabel": false\n\n            },\n\n            "force": {\n\n                "repulsion": 4000,\n\n                "edgeLength": 50,\n\n                "gravity": 0.2\n\n            },\n\n            "label": {\n\n                "show": true,\n\n                "margin": 8\n\n            },\n\n            "lineStyle": {\n\n                "show": true,\n\n                "width": 1,\n\n                "opacity": 1,\n\n                "curveness": 0,\n\n                "type": "solid"\n\n            },\n\n            "roam": true,\n\n            "draggable": false,\n\n            "focusNodeAdjacency": true,\n\n            "data": [\n\n                {\n\n                    "name": "\\u4eba\\u5458\\uff1a\\u674eXX",\n\n                    "symbolSize": 100\n\n                },\n\n                {\n\n                    "name": "\\u624b\\u673a\\uff1a188821211212\\uff0c\\u7f6e\\u4fe1\\u5206\\u6570\\uff1a0.9",\n\n                    "symbolSize": 60\n\n                },\n\n                {\n\n                    "name": "\\u624b\\u673a\\uff1a19121112211112\\uff0c\\u7f6e\\u4fe1\\u5206\\u6570\\uff1a0.8",\n\n                    "symbolSize": 60\n\n                },\n\n                {\n\n                    "name": "\\u673a\\u52a8\\u8f66\\u724c\\u53f7\\uff1a\\u6d59ASUSS99,\\u7f6e\\u4fe1\\u5206\\u6570\\uff1a0.96",\n\n                    "symbolSize": 60\n\n                },\n\n                {\n\n                    "name": "\\u623f\\u4ea7\\uff1a\\u6d59\\u6c5f\\u7701\\u676d\\u5dde\\u5e02\\u8427\\u5c71\\u533a\\u767d\\u9a6c\\u8857\\u9053\\u65b0\\u6865\\u8def129\\u53f7\\u98ce\\u82b1\\u96ea\\u6708\\u5c0f\\u533a1\\u680b1\\u5355\\u5143101\\u5ba4\\uff0c\\u7f6e\\u4fe1\\u5206\\u6570\\uff1a0.8",\n\n                    "symbolSize": 60\n\n                },\n\n                {\n\n                    "name": "mac:HHUUHG77121GV, \\u7f6e\\u4fe1\\u5206\\u6570\\uff1a0.77",\n\n                    "symbolSize": 60\n\n                },\n\n                {\n\n                    "name": "\\u94f6\\u884c\\u5361\\u53f7\\uff1a71219992911212211\\uff0c\\u7f6e\\u4fe1\\u5206\\u6570\\uff1a0.88",\n\n                    "symbolSize": 60\n\n                },\n\n                {\n\n                    "name": "\\u5fae\\u4fe1\\u53f7\\uff1a121sjjs, \\u7f6e\\u4fe1\\u5206\\u6570\\uff1a0.98",\n\n                    "symbolSize": 60\n\n                }\n\n            ],\n\n            "edgeLabel": {\n\n                "show": false,\n\n                "margin": 8\n\n            },\n\n            "edgeSymbol": [\n\n                null,\n\n                null\n\n            ],\n\n            "edgeSymbolSize": 10,\n\n            "links": [\n\n                {\n\n                    "source": "\\u4eba\\u5458\\uff1a\\u674eXX",\n\n                    "target": "\\u624b\\u673a\\uff1a188821211212\\uff0c\\u7f6e\\u4fe1\\u5206\\u6570\\uff1a0.9"\n\n                },\n\n                {\n\n                    "source": "\\u4eba\\u5458\\uff1a\\u674eXX",\n\n                    "target": "\\u624b\\u673a\\uff1a19121112211112\\uff0c\\u7f6e\\u4fe1\\u5206\\u6570\\uff1a0.8"\n\n                },\n\n                {\n\n                    "source": "\\u4eba\\u5458\\uff1a\\u674eXX",\n\n                    "target": "\\u673a\\u52a8\\u8f66\\u724c\\u53f7\\uff1a\\u6d59ASUSS99,\\u7f6e\\u4fe1\\u5206\\u6570\\uff1a0.96"\n\n                },\n\n                {\n\n                    "source": "\\u4eba\\u5458\\uff1a\\u674eXX",\n\n                    "target": "\\u623f\\u4ea7\\uff1a\\u6d59\\u6c5f\\u7701\\u676d\\u5dde\\u5e02\\u8427\\u5c71\\u533a\\u767d\\u9a6c\\u8857\\u9053\\u65b0\\u6865\\u8def129\\u53f7\\u98ce\\u82b1\\u96ea\\u6708\\u5c0f\\u533a1\\u680b1\\u5355\\u5143101\\u5ba4\\uff0c\\u7f6e\\u4fe1\\u5206\\u6570\\uff1a0.8"\n\n                },\n\n                {\n\n                    "source": "\\u4eba\\u5458\\uff1a\\u674eXX",\n\n                    "target": "mac:HHUUHG77121GV, \\u7f6e\\u4fe1\\u5206\\u6570\\uff1a0.77"\n\n                },\n\n                {\n\n                    "source": "\\u4eba\\u5458\\uff1a\\u674eXX",\n\n                    "target": "\\u94f6\\u884c\\u5361\\u53f7\\uff1a71219992911212211\\uff0c\\u7f6e\\u4fe1\\u5206\\u6570\\uff1a0.88"\n\n                },\n\n                {\n\n                    "source": "\\u4eba\\u5458\\uff1a\\u674eXX",\n\n                    "target": "\\u5fae\\u4fe1\\u53f7\\uff1a121sjjs, \\u7f6e\\u4fe1\\u5206\\u6570\\uff1a0.98"\n\n                }\n\n            ]\n\n        }\n\n    ],\n\n    "legend": [\n\n        {\n\n            "data": [],\n\n            "selected": {},\n\n            "show": true,\n\n            "padding": 5,\n\n            "itemGap": 10,\n\n            "itemWidth": 25,\n\n            "itemHeight": 14,\n\n            "backgroundColor": "transparent",\n\n            "borderColor": "#ccc",\n\n            "borderWidth": 1,\n\n            "borderRadius": 0,\n\n            "pageButtonItemGap": 5,\n\n            "pageButtonPosition": "end",\n\n            "pageFormatter": "{current}/{total}",\n\n            "pageIconColor": "#2f4554",\n\n            "pageIconInactiveColor": "#aaa",\n\n            "pageIconSize": 15,\n\n            "animationDurationUpdate": 800,\n\n            "selector": false,\n\n            "selectorPosition": "auto",\n\n            "selectorItemGap": 7,\n\n            "selectorButtonGap": 10\n\n        }\n\n    ],\n\n    "tooltip": {\n\n        "show": true,\n\n        "trigger": "item",\n\n        "triggerOn": "mousemove|click",\n\n        "axisPointer": {\n\n            "type": "line"\n\n        },\n\n        "showContent": true,\n\n        "alwaysShowContent": false,\n\n        "showDelay": 0,\n\n        "hideDelay": 100,\n\n        "enterable": false,\n\n        "confine": false,\n\n        "appendToBody": false,\n\n        "transitionDuration": 0.4,\n\n        "textStyle": {\n\n            "fontSize": 14\n\n        },\n\n        "borderWidth": 0,\n\n        "padding": 5,\n\n        "order": "seriesAsc"\n\n    },\n\n    "title": [\n\n        {\n\n            "show": true,\n\n            "text": "Idmapping\\u68c0\\u7d22\\u7ed3\\u679c\\u5c55\\u793a",\n\n            "target": "blank",\n\n            "subtarget": "blank",\n\n            "padding": 5,\n\n            "itemGap": 10,\n\n            "textAlign": "auto",\n\n            "textVerticalAlign": "auto",\n\n            "triggerEvent": false\n\n        }\n\n    ]\n\n};\n\n        chart_e8a41f256d8046879dbbb3e6e7cbb307.setOption(option_e8a41f256d8046879dbbb3e6e7cbb307);\n\n    </script>\n\n</body>\n\n</html>"""
        + ""
    )

    return f"""<iframe style="width: 100%; height: 480px" srcdoc='{html}'></iframe>"""

demo = gr.Interface(
    text_analysis,
    gr.Textbox(placeholder="Enter sentence here..."),
    "html",
    examples=[
        ["What a beautiful morning for a walk!"],
        ["It was the best of times, it was the worst of times."],
    ],
)

demo.launch(share=True, debug=True)

### Screenshot

![image](https://user-images.githubusercontent.com/21007668/210715646-ddbeabfe-0e58-495b-a9ab-774ad5fc61b3.png)

### Logs

```shell
nothing
```

### System Info

```shell
3.15.0, windows, chrome
```

### Severity

annoying

**Comment by aliabid94** [comment]
Taking a look

**Comment by aliabid94** [comment]
Your standalone HTML does not work on its own. Furthermore, you use single quotes in the HTML, and also use single quotes in the `srcdoc='{html}'` attribute, which conflict. You must remove the single quotes in the python. Working example below. Btw would encourage you to use the native Plot components that are part of the gradio library instead of importing a third party, as they will be better supported. 

```python
import gradio as gr


def text_analysis(text):
    html = """
<head>
  <title>Awesome-pyecharts</title>
  <script src="https://cdn.jsdelivr.net/npm/echarts@5.4.1/dist/echarts.min.js"></script>
</head>

<body>
  <div id="main" style="width: 600px;height:400px;"></div>
  <script>
    var myChart = echarts.init(document.getElementById("main"));

    var option = {
      title: {
        text: "ECharts"
      },
      tooltip: {},
      legend: {
        data: ["销量"]
      },
      xAxis: {
        data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
      },
      yAxis: {},
      series: [{
        name: "销量",
        type: "bar",
        data: [5, 20, 36, 10, 10, 20]
      }]
    };

    myChart.setOption(option);
  </script>
</body>
"""
    return f"""<iframe style="width: 100%; height: 480px" srcdoc='{html}'></iframe>"""


demo = gr.Interface(
    text_analysis,
    gr.Textbox(placeholder="Enter sentence here..."),
    "html",
    examples=[
        ["What a beautiful morning for a walk!"],
        ["It was the best of times, it was the worst of times."],
    ],
)

demo.launch()

```

Closing this issue for now, feel free to ask any follow up questions!

**Comment by 17818587795** [comment]
Replace the html string as follows, and the image editing cannot be displayed
```
    html = """
<head>
  <meta charset="UTF-8">
  <link type="text/css" href="https://uicdn.toast.com/tui-color-picker/v2.2.6/tui-color-picker.css" rel="stylesheet">
  <link rel="stylesheet" href="https://uicdn.toast.com/tui-image-editor/latest/tui-image-editor.css">
  <style>
    html,
    body {
      height: 100%;
      margin: 0;
    }
  </style>
</head>

<body>

  <div id="tui-image-editor-container"></div>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.6.0/fabric.js"></script>
  <script type="text/javascript" src="https://uicdn.toast.com/tui.code-snippet/v1.5.0/tui-code-snippet.min.js"></script>
  <script type="text/javascript" src="https://uicdn.toast.com/tui-color-picker/v2.2.6/tui-color-picker.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.3/FileSaver.min.js"></script> 
  <script src="https://uicdn.toast.com/tui-image-editor/latest/tui-image-editor.js"></script>
  <script>
    var imageEditor = new tui.ImageEditor('#tui-image-editor-container', {
      includeUI: {
        initMenu: 'filter',
        menuBarPosition: 'left'
      },
      cssMaxWidth: 700,
      cssMaxHeight: 500,
      usageStatistics: false
    });
  </script>
</body>
"""
```

**Comment by gi2wzh** [comment]
I want to display bar, code like this: 
```
import gradio as gr
from pyecharts.charts import Bar
from pyecharts import options as opts

# 使用gradio创建一个简单的界面并嵌入上面的HTML文件
def show_chart():
    # 创建一个简单的pyecharts图表
    bar = (
        Bar()
        .add_xaxis(["A", "B", "C", "D"])
        .add_yaxis("Counts", [5, 20, 36, 10])
        .set_global_opts(title_opts=opts.TitleOpts(title="Simple Bar Chart", subtitle="using pyecharts"))
    )

    # 将图表保存为HTML文件
    html = bar.render_embed()
    print(html)

    return f"""<iframe style="width: 100%; height: 480px" srcdoc='{html}'></iframe>"""
  
iface = gr.Interface(fn=show_chart, inputs=[], outputs="html", live=True)
iface.launch(debug=True)
```
but it can't work, do you know why ?

**Comment by ruhuansanmei** [comment]
> @aliabid94 want to display bar, code like this:
> 
> ```
> import gradio as gr
> from pyecharts.charts import Bar
> from pyecharts import options as opts
> 
> 
> def show_chart():
>     bar = (
>         Bar()
>         .add_xaxis(["A", "B", "C", "D"])
>         .add_yaxis("Counts", [5, 20, 36, 10])
>         .set_global_opts(title_opts=opts.TitleOpts(title="Simple Bar Chart", subtitle="using pyecharts"))
>     )
> 
>     html = bar.render_embed()
>     print(html)
> 
>     return f"""<iframe style="width: 100%; height: 480px" srcdoc='{html}'></iframe>"""
>   
> iface = gr.Interface(fn=show_chart, inputs=[], outputs="html", live=True)
> iface.launch(debug=True)
> ```
> 
> but it can't work, do you know why ?
https://github.com/ruhuansanmei/gradio_echarts_example
I wrote one custom component example, think that it can help you

**Comment by ruhuansanmei** [comment]
> > @aliabid94 want to display bar, code like this:
> > ```
> > import gradio as gr
> > from pyecharts.charts import Bar
> > from pyecharts import options as opts
> > 
> > 
> > def show_chart():
> >     bar = (
> >         Bar()
> >         .add_xaxis(["A", "B", "C", "D"])
> >         .add_yaxis("Counts", [5, 20, 36, 10])
> >         .set_global_opts(title_opts=opts.TitleOpts(title="Simple Bar Chart", subtitle="using pyecharts"))
> >     )
> > 
> >     html = bar.render_embed()
> >     print(html)
> > 
> >     return f"""<iframe style="width: 100%; height: 480px" srcdoc='{html}'></iframe>"""
> >   
> > iface = gr.Interface(fn=show_chart, inputs=[], outputs="html", live=True)
> > iface.launch(debug=True)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but it can't work, do you know why ?
> > https://github.com/ruhuansanmei/gradio_echarts_example
> > I wrote one custom component example, think that it can help you
just see example: https://gradio-echarts.lihu666.com/
