### ISSUE TITLE
gr.Dropdown.change event not triggering for version 3.16.0

### ISSUE THREAD

**Issue by wfng92** [gradio-app/gradio#2941]
### Describe the bug

`gr.Dropdown.change` event no longer works once I updated the environment to version 3.16.0.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

You can easily reproduce this by testing the `blocks_multiple_event_triggers` and `blocks_update` demos at [pr-2933-all-demos](https://huggingface.co/spaces/gradio-pr-deploys/pr-2933-all-demos)

### Logs

```shell
no
```

### System Info

```shell
3.16.0.
Windows and Linux
Firefox and Chrome
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Hi @wfng92 thanks for reporting the issue. Can confirm the problem, we'll work on a fix!
