### ISSUE TITLE
Typo in template

### ISSUE THREAD

**Issue by fjenett** [gradio-app/gradio#2943]
### Describe the bug

Line says `{{ config | toorjson }}` … should probably be `{{ config | tojson }}`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://github.com/gradio-app/gradio/blob/c126e62970cf8bab13e7a9001217a32573abd9d0/ui/packages/app/build_plugins.ts#L14

### Logs

```shell
Not needed
```

### System Info

```shell
Current Gradio at b3dc6f55
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @fjenett thanks for flagging this, but `toorjson` actually refers to this custom jinja filter: https://github.com/gradio-app/gradio/blob/b3dc6f557494929ba50465426fff4dc5daa0063f/gradio/routes.py#L75 which uses `orjson` to serialize a dictionary instead of `json` as it can handle numpy arrays, etc. Thanks!

**Comment by fjenett** [comment]
Ohmy, that is embarrassing. I did search the code base … Sorry. Thanks for looking into it.

Interestingly i ran into `toorjson` only because i received a JS error for that line in the compiled version of the frontend (local installation, running on the frontend dev server).

<img width="630" alt="Screenshot 2023-01-07 at 20 03 09" src="https://user-images.githubusercontent.com/59608/211166545-7654d025-e29a-42f7-bebc-383e0dd9dc11.png">
<img width="479" alt="Screenshot 2023-01-07 at 20 02 53" src="https://user-images.githubusercontent.com/59608/211166546-95715d1f-699b-443e-b068-b70912b8bcde.png">

Since i did not find anything instantly it tricked me into thinking it was a typo.

**Comment by abidlabs** [comment]
No problem, yes the fact that that raises an error in dev mode is a different issue which we should probably fix! Thanks for the reminder
