### ISSUE TITLE
gr.skip() does not work for many components, like button or dataframe

### ISSUE THREAD

**Issue by aliabid94** [gradio-app/gradio#2947]
### Describe the bug

gr.skip() does not work for many components, like button or dataframe

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

return {btn: gr.skip()}

### Logs

```shell
N/A
```

### System Info

```shell
N/A
```

### Severity

annoying

**Comment by abidlabs** [comment]
Can't reproduce this. For example, this works:

```py
import gradio as gr

with gr.Blocks() as demo:
    b0 = gr.Button()
    b1 = gr.Button()
    b2 = gr.Button("Click me")
    
    b2.click(lambda : {b0: "Changed", b1: gr.skip()}, None, [b0, b1])
    
demo.launch()
```

Has this been resolved, or am I missing something?

**Comment by aliabid94** [comment]
Oh yeah I fixed this, was a problem only if highlighted component was a component bc it had no default value, not an issue now.
