### ISSUE TITLE
Cannot load image captioning models

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2956]
### Describe the bug

The following will error

```python
import gradio as gr
gr.Interface.load("models/nlpconnect/vit-gpt2-image-captioning").launch()
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
ValueError: Unsupported pipeline type: image-to-text
```

### Logs

```shell
-
```

### System Info

```shell
latest/3.16.1
```

### Severity

annoying

**Comment by abidlabs** [comment]
We should add this pipeline, thanks for flagging @freddyaboulton
