### ISSUE TITLE
🔔 Browser Notification

### ISSUE THREAD

**Issue by camenduru** [gradio-app/gradio#2959]
Some calculations take too much time and the user no longer looks at the browser I want to notify the user 

Example:
![Screenshot 2023-01-08 192735](https://user-images.githubusercontent.com/54370274/211207916-1d9bd392-76ec-4b26-ab31-9806007982a5.jpg)

From ChatGPT 😋

Browser notifications can be used for a variety of purposes. Some common uses include:

- Alerting users to new content or updates on a website: For example, a news site might use browser notifications to alert users to breaking news stories or updates to articles they have previously viewed.
- Reminding users about upcoming events or tasks: For example, a calendar app might use browser notifications to remind users about upcoming appointments or deadlines.
- Prompting users to take some action: For example, a website might use browser notifications to encourage users to sign up for a newsletter or complete a survey.
- Providing users with real-time updates: For example, a sports website might use browser notifications to alert users to live scores or updates from games they are following.
- Displaying alerts or warning messages: For example, a security website might use browser notifications to alert users to potential threats or vulnerabilities on their computer.
- Displaying promotional messages or special offers: For example, an e-commerce website might use browser notifications to promote sales or special deals to users.

**Comment by julien-c** [comment]
Hi @camenduru 👋

When running inside Spaces, what would you think of us providing a way for users to be notified over their huggingface email? (we've been thinking about something like this)

**Comment by camenduru** [comment]
Hi @julien-c 👋 like this:
https://web.dev/notifications/
https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API
https://www.w3.org/TR/push-api/
from https://stackoverflow.com/questions/33687298/how-to-send-push-notification-to-web-browser

**Comment by julien-c** [comment]
oh i know what Web notifications are.

As a user, personally i prefer email notifications though (seems like they're a "superset" of the others in terms of feature space)

**Comment by camenduru** [comment]
maybe we can make an email notification system with a user permission feature. the space asks for email permission and the user grants permission, the space sends an API call to the mail server. The mail server then checks if the permission is valid before sending the email maybe like this 🤔

**Comment by camenduru** [comment]
but if space sends a lot of mail over 🤗 mail server, 🤗mail server gets flagged as spam by some mail providers (gmail, hotmail, etc.) because it sends a lot of mail. 😲 If you ask me, I wouldn't let a dev send mail through my mail server hehe maybe the dev can enter their mail server information in an API call 🤔

**Comment by Seedmanc** [comment]
I'd prefer a browser notification, emails are outdated at least, and I'm not launching jobs that would take hours to finish to rely on email. In the timeframe of minutes notifications are the solution.
