### ISSUE TITLE
Interpretation is not updating the input text visual

### ISSUE THREAD

**Issue by yaogee** [gradio-app/gradio#2960]
### Describe the bug

The interpretation in 3.161 is not updating the input text visual. The function hook is called but no updates. There is also a bug related to examples. Some extra text are appended in the text field after clicking on the example.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://gradio.app/demos/ under "Sentiment Analysis"

### Screenshot

![image](https://user-images.githubusercontent.com/26838074/211235648-43e4bda4-7e50-49e1-8edc-8e4115610b75.png)

### Logs

```shell
No logs
```

### System Info

```shell
3.16.1
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Hmm thanks for flagging the issue @yaogee, we'll take a look!
