### ISSUE TITLE
Add ability to append additional classes to html element when creating a component

### ISSUE THREAD

**Issue by Gerschel** [gradio-app/gradio#2962]
- [✔️  ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

Styling a component, or targeting with javascript. Element ID's should be unique, but I can target groups
that have the same (html) class. I don't have access to append custom classes when creating the component.  
This means, that I have to write a rule for each element id, instead of a single rule for those that match by class.

**Describe the solution you'd like**  
Similar to `elem_id`, but appends to class list that's autogenerated
```python
gr.Component(elem_class = "my-class")
```
Or maybe
```python
gr.Component(elem_class = ["my-first-class", "my-second-class"])
```

**Comment by aliabid94** [comment]
I'll take this
