### ISSUE TITLE
Always Queueing, websockets by default

### ISSUE THREAD

**Issue by aliabid94** [gradio-app/gradio#2969]
Many features - such as: "every", generating functions, and progress bars - are only supported when websockets are enabled. Websockets are tied to the queue() functionality right now. It is confusing to users that the queue needs to be enabled for what seem like unrelated features. I want to remove any difference between using websocket and REST API other than the difference in protocol. This will lead to:

1. Features equivalent between REST API and websocket (no "need to enable queue for this feature" anymore)
2. Websocket will become default protocol, unless in Colab
3. Singular mechanism of handling request (via Queue) should simplify codebase. This means REST API receives queue estimation and rank updates also now.
4. No more timeout limit for REST API, because after X seconds, REST API will switch to long polling. 

REST API will be converted to polling style by receiving a token. Whenever it receives any update, if it is not accompanied with a {"msg": "process_complete"}, it will poll again with the same token to check for more updates. Backend will also send token back early to prevent timeouts (e.g. send after 40 seconds, so the client will pol again at every 40 seconds) with a "progress_pending" message. By default, REST API will only return "process_completed" and "progress_pending" messages (ignoring "estimations" and other messages we currently send with websockets) so any users using the REST API currently should be backwards compatible, other than the "progress_pending" (which would have timed out and not worked anyway). The frontend end however will request all messages, so it will receive queue rank and estimation messages as well.

**Comment by freddyaboulton** [comment]
Good points @aliabid94 ! 

To enable the polling, we would have to store the intermediate request outputs somewhere right? (Preferably not the server to maintain the stateless REST principle) 

Have you started to think about that?

**Comment by aliabid94** [comment]
It would all be stored in the queue. The queue is always used now. The REST API would simply put the event in queue, and for 40 seconds periodically check the queue for completion. If it is not done, returns a code 102 pending request with the event token.

**Comment by aliabid94** [comment]
I can't think of anyway that we wouldn't have to temporarily store output data, let me know if you have a suggestion

**Comment by freddyaboulton** [comment]
@aliabid94 I think we would need an external database or something? 

I don’t think storing session data on the server is a good idea. It breaks REST principles and it will be harder to scale the app via replication. For example, you can imagine a user submits a request and gets sent to replica A and the intermediate result is stored there. On the second request (after 40 seconds or something) the same user could be sent to replica B which doesn’t have their result. We’d have to synchronize the outputs across replicas ourselves which would be difficult .

**Comment by freddyaboulton** [comment]
I think it’s fine if some features are websocket only but we should allow them to work when the queue is not enabled. I agree that queuing and using web sockets are different things. 

Perhaps we should rework this issue to just tackle that problem? And add a proper websocket client while we’re at it (#2516 ) to enable users to connect via websocket easily and not have to know internal implementation details of our messages, etc.

**Comment by aliabid94** [comment]
I think we shouldn't have websocket only features, because some environments (like colab) don't support websockets, and we shouldn't remove features as a result of that. It is a bad developer experience if some features only work in some environments IMO, and right now that feature set is growing.  
I understand what your saying about REST principles but here's what I'm thinking. These principles about statelessness and scalabilty are relevant in production use-cases with high traffic. In those cases (a minority with gradio), users should use the default websocket mode. The main purpose of supporting REST is to support environments like colab and also allow users to perform simple API calls. I think it's okay to break some REST principles to make this happen. 
(#2516 websocket client issue is a separate issue btw, right? Agree we should add support at some point but doesn't solve this problem)

**Comment by freddyaboulton** [comment]
All of those websocket driven features are enabled in colab via the `share` link that's automatically created no? So I don't think it's the case that colab has a different feature set than non-colab.

And if users want to perform simple api calls, the `get` and `post` requests of the server are open even if the queue is enabled so they can use that if they'd prefer. Of course, some events like `every` and generators cannot be completed via a single request but technically the user can just send another request with the same session hash to get the next iteration (basically what this [while-loop](https://github.com/gradio-app/gradio/blob/main/gradio/queueing.py#L351) in the queue does). We can add a client/python api that would make this easier for users.

I agree we can make websocket the default communication protocol now. What if we make the queue enabled by default and have large default values for `concurrency_count` and `max_size`? That way, by default, the app will behave kind of like a non-queue enabled app does now (e.g. handle lots of requests concurrently) but users will not need to manually enable the queue to use the websocket enabled features. Users can then tune `concurrency_count` and `max_size` to their app's needs (or disable the queue if they have a very simple app that does not need two way communication between client and server).

**Comment by aliabid94** [comment]
Okay I'm convinced. Let's make websocket and queue default, and set default concurrency of 40. I think we should discourage using the REST API. For the view API page, we can either switch to showing code with websockets, or a custom gradio client.

My concern with a custom gradio client - should it be part of the gradio library? Seems like overkill to download the whole library when it should be only a few lines of websocket code to query the API. Wdyt?

**Comment by freddyaboulton** [comment]
I think the client code will be tightly coupled with the broader library code cause the websocket messages are defined in the broader library. Maybe we can publish the client as a separate package?

**Comment by Seedmanc** [comment]
Please no, whenever I enable queue together with debug in colab I'm unable to stop gradio properly so every time I relaunch it stack up the queue and I have to restart the whole notebook.

**Comment by freddyaboulton** [comment]
Wonder if this would help @Seedmanc https://github.com/gradio-app/gradio/pull/3022

**Comment by freddyaboulton** [comment]
This got done in the v4 branch except we now use sse!
