### ISSUE TITLE
interactive = True does not work in output gr.Dataframe()

### ISSUE THREAD

**Issue by piegu** [gradio-app/gradio#2975]
### Describe the bug

Hi,

I want to be able to update the content of my Dataframe in the gradio output.
I use the argument `interactive = True` as indicated in the [doc](https://www.gradio.app/docs/#dataframe) but it does not work.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

# !pip install gradio
import gradio as gr

def filter_records(records, gender):
    return records[records["gender"] == gender]

demo = gr.Interface(
    filter_records,
    [
        gr.Dataframe(
            headers=["name", "age", "gender"],
            datatype=["str", "number", "str"],
            row_count=5,
            col_count=(3, "fixed")
        ),
        gr.Dropdown(["M", "F", "O"]),
    ],
    gr.Dataframe(
        headers=["name", "age", "gender"],
        datatype=["str", "number", "str"],
        col_count=(3, "fixed"),
        interactive=True
        ),
    description="Enter gender as 'M', 'F', or 'O' for other.",
)

if __name__ == "__main__":
    demo.launch()

### Logs

```shell
There is no logs.
```

### System Info

```shell
Last version of gradio
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment]
Thank you @piegu! Will look into it

**Comment by freddyaboulton** [comment]
@abidlabs Looks like we force the output components to be non-interactive: https://github.com/gradio-app/gradio/blame/main/gradio/interface.py#L273 . Can we relax that?

@piegu In the meantime, if you would like to edit the resulting dataframe, I think you can do so with the lower-level Blocks API.

**Comment by piegu** [comment]
Hi,

First of all, the gradio documentation indicates that it is possible to modify an output dataframe with the balise `interactive`. I guess the gradio team thought that was a good idea, right? ;-)

Secondly, I want to manually enrich the output dataframe with tags identifying the dataframe's content (the output dataframe will contain text extracted by OCR from a PDF). 

At last, I will need to export the csv of this updated dataframe.

Great if you can allow the interaction with an output dataframe. Thank you.

**Comment by abidlabs** [comment]
Thanks @piegu, appreciate your reasoning. 

Yes, we provide an `interactive` parameter that is designed to be used with the `gr.Blocks` API, which is a more flexible alternative to the `gr.Interface`. In your case, I think you might actually need to use `gr.Blocks` because you want to export the CSV of the updated dataframe anyways, which means a single input/output workflow (which is what `gr.Interface` is designed for may not be sufficient for your needs). Let me share a quick MVP for what this could look like for you

**Comment by abidlabs** [comment]
Here's an MVP:

```py
import gradio as gr

def mock_ocr(f):
    return [[1, 2, 3], [4, 5, 6]]

def export_csv(d):
    d.to_csv("output.csv")
    return gr.File.update(value="output.csv", visible=True)

with gr.Blocks() as demo:
    with gr.Row():
        file = gr.File(label="PDF file", file_types=[".pdf"])
        dataframe = gr.Dataframe()
        
        with gr.Column():
            button = gr.Button("Export")
            csv = gr.File(interactive=False, visible=False)
            
            
    file.change(mock_ocr, file, dataframe)
    button.click(export_csv, dataframe, csv)
        
demo.launch()
```

Which looks something like this:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/1778297/212939455-37841821-942e-481f-9f7c-5efe95b4ba1e.png">

You'll notice that you don't need to set `interactive` manually as gradio figures out that the dataframe should be interactive as it is the input to another function. Here's more on Blocks: https://gradio.app/quickstart/#blocks-more-flexibility-and-control

**Comment by piegu** [comment]
Thank you @abidlabs.

I just tested your MVP and it works (I will have to update it in order to visualize the pdf pages).

Another point, is it possible to change the cell type of the output dataframe to drop-down list? (my use case is to manually classify the content of my dataframe from a list of balises as header, title, etc.)

**Comment by abidlabs** [comment]
Glad to hear that it works. I'll go ahead and close this issue.

> Another point, is it possible to change the cell type of the output dataframe to drop-down list? (my use case is to manually classify the content of my dataframe from a list of tags as header, title, etc.)

Good question. Although this been requested before (#2006), this is not currently possible. You can follow the issue if you'd like to receive updates!

**Comment by sorenwacker** [comment]
The dataframe should be downloadable right from the table.

**Comment by benjamrio** [comment]
> Here's an MVP:
> 
> ```python
> import gradio as gr
> 
> def mock_ocr(f):
>     return [[1, 2, 3], [4, 5, 6]]
> 
> def export_csv(d):
>     d.to_csv("output.csv")
>     return gr.File.update(value="output.csv", visible=True)
> 
> with gr.Blocks() as demo:
>     with gr.Row():
>         file = gr.File(label="PDF file", file_types=[".pdf"])
>         dataframe = gr.Dataframe()
>         
>         with gr.Column():
>             button = gr.Button("Export")
>             csv = gr.File(interactive=False, visible=False)
>             
>             
>     file.change(mock_ocr, file, dataframe)
>     button.click(export_csv, dataframe, csv)
>         
> demo.launch()
> ```
> 
> Which looks something like this:
> 
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/1778297/212939455-37841821-942e-481f-9f7c-5efe95b4ba1e.png">
> 
> You'll notice that you don't need to set `interactive` manually as gradio figures out that the dataframe should be interactive as it is the input to another function. Here's more on Blocks: https://gradio.app/quickstart/#blocks-more-flexibility-and-control

I think `gr.File.update(value="output.csv", visible=True)` should be replaced by `gr.File(value="output.csv", visible=True)`

**Comment by young-hun-jo** [comment]
@benjamrio Thanks for your answer. I tried to [this](https://github.com/gradio-app/gradio/issues/2975#issuecomment-1385602531), but it don't work for me. Error is `File` component has no longer `update` attribute. But your answer is work for me. Thank you again!
