### ISSUE TITLE
gr.Dataframe() as output will cause tuple no _id problem

### ISSUE THREAD

**Issue by JingxinLee** [gradio-app/gradio#2976]
### Describe the bug

```
def combine_bleu(file1, file2):
    file1_data = pd.read_csv(file1.name, encoding='utf8', sep='\t', header=0, usecols=['style', 'inputs', 'outputs'])
    file2_data = pd.read_csv(file2.name, encoding='utf8', sep='\t', header=0, usecols=['model_outputs'])
    assert len(file1_data) == len(file2_data)
    merged_file_data = pd.concat([file1_data, file2_data], axis=1)


    # 新建score4s DataFrame
    model_bleu4_df = pd.DataFrame(score4s)

    # 将bleu4这一列加上
    merged_file_data['bleu4'] = model_bleu4_df
    merged_data_df = pd.DataFrame(merged_file_data)
    final_bleu4_score = 0.9

    return merged_data_df, final_bleu4_score

with gr.Blocks() as evaluate_gradio:
    with gr.Row():
        file1 = gr.File(label='Please upload test csv')
        file2 = gr.File(label='Please upload your csv')
    with gr.Row():
        output1 = gr.Dataframe(), 
    with gr.Row():
        output2 = gr.Textbox(label='The output number is:')
    with gr.Row():
        evaluate_btn = gr.Button('evaluate')
        evaluate_btn.click(fn=combine_bleu, inputs=[file1, file2], outputs=[output1, output2])

```

Traceback (most recent call last):
  File "/root/tst/source/evaluate_gr.py", line 123, in <module>
    evaluate_btn.click(fn=combine_bleu, inputs=[file1, file2], outputs=[output1, output2])
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/events.py", line 145, in click
    dep = self.set_event_trigger(
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 227, in set_event_trigger
    "outputs": [block._id for block in outputs],
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 227, in <listcomp>
    "outputs": [block._id for block in outputs],
AttributeError: 'tuple' object has no attribute '_id'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

before

### Logs

```shell
no
```

### System Info

```shell
linux latest gradio
```

### Severity

annoying

**Comment by JingxinLee** [comment]
output1[0] solove the problem

**Comment by dipam0111** [comment]
> output1[0] solove the problem

where did you put `output1[0]` I have the same error, I am trying to print a new df everytime with gr.Dataframe based on document_id

**Comment by freddyaboulton** [comment]
There's a typo in your code @JingxinLee !

Change `output1 = gr.Dataframe(),` to `output1 = gr.Dataframe()`. The trailing comma makes it a tuple
