### ISSUE TITLE
not able to load custom yolov5 classification weight

### ISSUE THREAD

**Issue by akashAD98** [gradio-app/gradio#2978]
### Describe the bug

i tried to load custom trained classification model using yolov5-classification & passed weight in this code, I'm getting this error

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import requests

import gradio as gr
import torch
from timm import create_model
from timm.data import resolve_data_config
from timm.data.transforms_factory import create_transform

#IMAGENET_1k_URL = "/content/classes.txt"
LABELS = "/content/classes.txt"
# requests.get(IMAGENET_1k_URL).text.strip().split('\n')

model = create_model('/content/drive/MyDrive/yolov5/runs/train-cls/exp9/weights/best.pt', pretrained=False)

transform = create_transform(
    **resolve_data_config({}, model=model)
)
model.eval()

def predict_fn(img):
    img = img.convert('RGB')
    img = transform(img).unsqueeze(0)

    with torch.no_grad():
        out = model(img)
    
    probabilites = torch.nn.functional.softmax(out[0], dim=0)

    values, indices = torch.topk(probabilites, k=3)

    return {LABELS[i]: v.item() for i, v in zip(indices, values)}

gr.Interface(predict_fn, gr.inputs.Image(type='pil'), outputs='label').launch()


```

### Screenshot

<img width="687" alt="image" src="https://user-images.githubusercontent.com/62583018/212314284-af043800-513b-4238-9053-48e4198d9feb.png">

### Logs

```shell
im getting this error
```

### System Info

```shell
google collab
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @akashAD98 ! 

Seems to be an error coming from timm and not gradio. Maybe there was an error uploading the mode weights to colab?

I will close as this does not seem to be a gradio issue. Thank you!

**Comment by akashAD98** [comment]
Can you attach example of loading custom pytroch classification weight,
without using timm want to do

**Comment by akashAD98** [comment]
@freddyaboulton please provide an example of loading.pt weight & IDK why are you closing without solving my issue,

there's no issue for model losing
