### ISSUE TITLE
queue() 404 when Nginx forward to 2 Gradio app on 2 ports on the same machine

### ISSUE THREAD

**Issue by kaiyaointel** [gradio-app/gradio#2979]
### Describe the bug

Hi,

I'm launching 2 Gradio apps, one on my machine's ```localhost:7860``` port and one on ```localhost:7861``` port.

Then I use Nginx on my machine listening to ```80``` port and forward ```app1``` and ```app2``` substring to those 2 Gradio apps.

Let's say my machine IP is ```11.22.33.44```. This way theoretically ```11.22.33.44/app1``` should direct to my 1st app, and ```11.22.33.44/app2``` should direct to my 2nd app.

I found out that one of them can work perfectly fine, but the other one of them (the one that's launched the latter) will fail to execute. **The static html UI is there (works fine), but when I click the button (like "Submit"), it pops out the red Error, and said "connection refused"** Then I looked into the log.

The error log in Nginx log is like:
```
... "GET /app2/queue/join HTTP/1.1" 404 22 "-" ...
```
It looks like the ```queue``` API is not working fine.

Then I tried to remove ```queue()``` in the latter one, magically, both apps in ```11.22.33.44/app1``` and ```11.22.33.44/app2``` works fine. 

So it means that when both of my Gradio app uses ```demo.queue().launch()```, the latter one will fail to execute.

So it seems like, with Nginx forwarding requests, Gradio's ```queue``` API somehow does not work properly when launching multiple Gradio apps on multiple ports on the same machine, or at least it's somehow not compatible. Although removing ```queue()``` is a workaround, it willrequire disabling functionalities like ```Progress()``` which seems not a best solution.

Any idea to solve this issue? Much appreciated.

My Nginx config is like this:
```
...
    server {
        listen       80;
        server_name  localhost;
        location /app1/ {
            proxy_pass http://127.0.0.1:7860/;
        }
        location /app2/ {
            proxy_pass http://127.0.0.1:7861/;
        }
    ...
...
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

described in main text

### Logs

```shell
... "GET /app2/queue/join HTTP/1.1" 404 22 "-" ...
```

### System Info

```shell
Linux
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Hi @kaiyaointel thanks for opening this issue. To help us debug this, can you let us know what happens when you use the apps directly from localhost. In other words, when you launch both apps with queuing enabled and then go to `http://127.0.0.1:7861/` and run the Gradio app, does it work, or do you see the same "connection refused" error?

**Comment by kaiyaointel** [comment]
> Hi @kaiyaointel thanks for opening this issue. To help us debug this, can you let us know what happens when you use the apps directly from localhost. In other words, when you launch both apps with queuing enabled and then go to `http://127.0.0.1:7861/` and run the Gradio app, does it work, or do you see the same "connection refused" error?

When directly opening `http://127.0.0.1:7861/`, it does work finely with no error.

**Comment by abidlabs** [comment]
Thanks for letting us know @kaiyaointel. 

If the localhost links are working, then this sounds like an issue with nginx and websockets then, not the gradio library (when you enable queuing, Gradio uses websockets instead of http requests). I'll go ahead and close this issue, but I did do some digging around, it looks like you might have to add a bit more to your nginx conf to make sure that the websockets are proxied correctly. Read here for example: https://www.nginx.com/blog/websocket-nginx/

**Comment by aghand0ur** [comment]
Hello @abidlabs 
I am also not able to reach gradio behind nginx

```
IP******* - - [22/Feb/2023:16:09:20 +0200] "GET /media/icon_hu52dd3e5556c522baf9becdcf638c15e3_312801_32x32_fill_lanczos_center_3.png HTTP/1.1" 404 22 "-" "python-requests/2.26.0"
IP******* - - [22/Feb/2023:16:09:20 +0200] "GET / HTTP/1.1" 301 178 "-" "python-requests/2.26.0"
IP******* - - [22/Feb/2023:16:09:20 +0200] "GET /media/icon_hu52dd3e5556c522baf9becdcf638c15e3_312801_180x180_fill_lanczos_center_3.png HTTP/1.1" 404 22 "-" "python-requests/2.26.0"
IP******* - - [22/Feb/2023:16:09:20 +0200] "GET /media/icon_hu52dd3e5556c522baf9becdcf638c15e3_312801_32x32_fill_lanczos_center_3.png HTTP/1.1" 404 22 "-" "python-requests/2.26.0"
IP******* - - [22/Feb/2023:16:09:20 +0200] "GET / HTTP/1.1" 301 178 "-" "python-requests/2.26.0"
```

any insight?

**Comment by m4oc** [comment]
I solved the problem by configuring the nginx proxy for websockets in the path /queue

```
location / {
        proxy_pass http://127.0.0.1:7861;
    }
```

    #Websocket configuration
    location /queue/ {
      proxy_pass "http://127.0.0.1:7861/queue/";
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

**Comment by shao-shuai** [comment]
> I solved the problem by configuring the nginx proxy for websockets in the path /queue
> 
> ```
> location / {
>         proxy_pass http://127.0.0.1:7861;
>     }
> ```
> 
> ```
> #Websocket configuration
> location /queue/ {
>   proxy_pass "http://127.0.0.1:7861/queue/";
>   proxy_http_version 1.1;
>   proxy_set_header Upgrade $http_upgrade;
>   proxy_set_header Connection "upgrade";
> }
> ```

This works for me, thanks Marco!
