### ISSUE TITLE
`gradio.Gallery` loses selection when updated

### ISSUE THREAD

**Issue by AUTOMATIC1111** [gradio-app/gradio#2984]
### Describe the bug

In Gallery, you can select an image to show it at larger resolution. In gradio 3.3, when gallery is updated from python, and images are replaced with new ones, the selection is not lost, and you still get to view the newly added image at full resolution. In 3.4 and later, this ability is lost, gallery just shows the whole set of images at small resolution. This behavior is a definite degradation for anyone who used gradio for image generation before 3.4. I have a large amount of javascript to try and patch it up, and it doesn't always work, and it also introduces some other problems like sometimes losing focus from selected textarea.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import random
import time

import gradio as gr
from PIL import Image

with gr.Blocks(analytics_enabled=False) as demo:
    go = gr.Button('Go', variant="primary")
    gallery = gr.Gallery().style(grid=12)

    def create_images():
        a = Image.new("RGB", (512, 512), "red")
        b = Image.new("RGB", (512, 512), "green")
        c = Image.new("RGB", (512, 512), "blue")

        res = [a, b, c]
        random.shuffle(res)
        return res

    go.click(
        fn=create_images,
        inputs=[],
        outputs=[gallery],
    )

demo.launch(share=False)
```

### Screenshot

![firefox_2ysB48DiBU](https://user-images.githubusercontent.com/20920490/212525147-b2f72707-d1c0-4f1f-87f5-8a51cde40fcb.png)

### Logs

```shell
none
```

### System Info

```shell
Windows 10, python 3.10.6
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Thanks for creating the issue @AUTOMATIC1111, we'll take a look!

**Comment by anugrahakbarp** [comment]
> Thanks for creating the issue @AUTOMATIC1111, we'll take a look!

hi @abidlabs can you please take a look for my issues too [here](https://github.com/gradio-app/gradio/issues/2983)

Thank you in advance :)
