### ISSUE TITLE
Including auth arg in launch() makes external link redirect to localhost

### ISSUE THREAD

**Issue by kondela** [gradio-app/gradio#299]
Basically the title.

I tried out `.launch(auth=('some_name', 'some_password'), share=True)`, terminal prints out
```
Running locally at: http://127.0.0.1:7860/
This share link will expire in 72 hours. If you need a permanent link, visit: https://gradio.app/introducing-hosted
Running on External URL: https://54123.gradio.app
Interface loading below...
<IPython.lib.display.IFrame object at 0x7f7666795040>
```

However, `https://54123.gradio.app` redirects to `http://localhost:54123/login?next=%2F`.

Works with `.launch(share=True)`

**Comment by abidlabs** [comment]
Thanks, @aliabid94 is taking a look at this!

**Comment by aliabid94** [comment]
Fixed now. Let us know if you have any other issues!
