### ISSUE TITLE
API Request skipping behavior

### ISSUE THREAD

**Issue by junkoran** [gradio-app/gradio#3007]
- [ v ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Hi, i'm developing an app that mainly will be accessed through API request. and for the browser access, it will be a demo page. 
It is cool that API requests can skip browser queue, but i found that this behavior also occurs in the API queue, something like this : 
![image](https://user-images.githubusercontent.com/119563413/213107892-b9bd7635-eb48-4595-b072-1a13747c4b20.png)
I set 1 for concurrency_count and max_threads, i made 10 API requests (3s interval), but as soon as the worker is free the latest request (client 9) takes it

**Describe the solution you'd like**  
How to make it to be something like first in first out? 

**Additional context**  
Something like this 
![image](https://user-images.githubusercontent.com/119563413/213109851-515e3ca3-c79b-4512-bd52-7525aaad75e6.png)

Thanks in advance! :)

**Comment by abidlabs** [comment]
Hi @junkoran great question: so currently, if you use the HTTP POST endpoint, the queue will not be respected. We are currently working on a way to make it easy to respect the queue when connecting via API (#2516). One question: from your app, are you making requests to the API in Python or JS?

**Comment by junkoran** [comment]
Hi @abidlabs, thanks for the response! 
I'm making requests with Python. For more details, I host my app locally and expose it with ngrok

**Comment by abidlabs** [comment]
Ok if you are using Python, then instead of using the API, you can actually load the Space and use it as a function directly using `gr.Blocks.load()`. If you do it this, the queue is automatically respected. Here's some more information: https://gradio.app/using-blocks-like-functions/

I'll go ahead and close this issue since this should solve the problem!
