### ISSUE TITLE
Build Website on PRs

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#3021]
- [ ] I have searched to see if a similar issue already exists.

Could be a duplicate but I can't find it if so

**Is your feature request related to a problem? Please describe.**  
Now that spaces support Docker images, I wonder if we can deploy the website for a PR on HF Spaces.

We don't have to use Spaces, but I think deploying the website on PRs will be useful for reviewing changes to docs!

**Comment by abidlabs** [comment]
We now do this!
