### ISSUE TITLE
Session State example code on the official document doesn’t work

### ISSUE THREAD

**Issue by petrov826** [gradio-app/gradio#3031]
### Describe the bug

Hello. I found a bug in the official document.
The “Session State” section in https://gradio.app/interface-state, there’s a sample code below.

```python
import random
import gradio as gr

def chat(message, history):
    history = history or []
    message = message.lower()
    if message.startswith("how many"):
        response = random.randint(1, 10)
    elif message.startswith("how"):
        response = random.choice(["Great", "Good", "Okay", "Bad"])
    elif message.startswith("where"):
        response = random.choice(["Here", "There", "Somewhere"])
    else:
        response = "I don't know"
    history.append((message, response))
    return history, history

chatbot = gr.Chatbot().style(color_map=("green", "pink"))
demo = gr.Interface(
    chat,
    ["text", "state"],
    [chatbot, "state"],
    allow_flagging="never",
)
demo.launch()
```

This works fine for most cases. However, when I ask “How many cats do you have?” to this chatbot, it throws an error like below.

```
…
  File "/Users/petrov/opt/anaconda3/envs/gradio/lib/python3.10/site-packages/markdown_it/main.py", line 250, in parse
    raise TypeError(f"Input data should be a string, not {type(src)}")
TypeError: Input data should be a string, not <class 'int'>
```

I guess this is because of “response = random.randint(1, 10)” at line 8. Only this line returns `int` and others return `str`. Guessing from the error text, `gr.Chatbot` only accepts `str`, right?

If I’m correct, please modify the line to “response = str(random.randint(1, 10))” or something. 

Thanks in advance🤗

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Ask the chatbot in the [official document ](https://gradio.app/interface-state/#session-state) "How many cats do you have?”

### Screenshot

<img width="1275" alt="gradio_document_bug" src="https://user-images.githubusercontent.com/26062262/213664916-8b452db9-2288-420c-8d01-ecba4816791f.png">

### Logs

```shell
Traceback (most recent call last):
  File "/Users/petrov/opt/anaconda3/envs/gradio/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/petrov/opt/anaconda3/envs/gradio/lib/python3.10/site-packages/gradio/blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/petrov/opt/anaconda3/envs/gradio/lib/python3.10/site-packages/gradio/blocks.py", line 956, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/Users/petrov/opt/anaconda3/envs/gradio/lib/python3.10/site-packages/gradio/components.py", line 3908, in postprocess
    y[i] = (self.md.render(message), self.md.render(response))
  File "/Users/petrov/opt/anaconda3/envs/gradio/lib/python3.10/site-packages/markdown_it/main.py", line 267, in render
    return self.renderer.render(self.parse(src, env), self.options, env)
  File "/Users/petrov/opt/anaconda3/envs/gradio/lib/python3.10/site-packages/markdown_it/main.py", line 250, in parse
    raise TypeError(f"Input data should be a string, not {type(src)}")
TypeError: Input data should be a string, not <class 'int'>
```

### System Info

```shell
I ran the same code on my environment and encountered the same error.


>>> gradio.__version__
'3.16.2'
```
```


### Severity

annoying

**Comment by abidlabs** [comment]
Nice catch @petrov826! Would you be willing to make a PR to update this demo? The code for the demo lives here: https://github.com/gradio-app/gradio/blob/main/demo/chatbot_demo/run.py

Thanks!

**Comment by petrov826** [comment]
@abidlabs You're welcome! I made a PR https://github.com/gradio-app/gradio/pull/3039.

**Comment by petrov826** [comment]
Pull request https://github.com/gradio-app/gradio/pull/3039 successfully merged and closed🤗

@abidlabs I would like to have the [document](https://gradio.app/interface-state/) corrected as well, who should I ask?

**Comment by abidlabs** [comment]
It will automatically be updated when the website rebuilds!

**Comment by abidlabs** [comment]
Thanks for the contribution @petrov826!
