### ISSUE TITLE
command not found: gradio

### ISSUE THREAD

**Issue by xianbaoqian** [gradio-app/gradio#3033]
### Describe the bug

Tried to reproduce this auto-reload feature: https://gradio.app/developing-faster-with-reload-mode/
but I'm unable to find the "gradio" command in the PATH

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

$ python3 -m venv env
$ source env/bin/active
$ pip3 install gradio
$ gradio app.py
zsh: command not found: gradio

### Logs

```shell
zsh: command not found: gradio
```

### System Info

```shell
MacOS M1
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Could someone with a Mac look into this issue? On Windows this works for me. cc @dawoodkhan82 @freddyaboulton

**Comment by freddyaboulton** [comment]
Works for me!

My guess is that `env/bin` is not in your `PATH` @xianbaoqian ?

**Comment by xianbaoqian** [comment]
Thanks for checking @freddyaboulton ! You're right. The binary is in the env/bin folder. My virtualenv configuration seems to be the weird one. Closing this bug.
