### ISSUE TITLE
Text output doesn't return on longer jobs (2+ minutes)

### ISSUE THREAD

**Issue by CMobley7** [gradio-app/gradio#3038]
### Describe the bug

I wrote a demo using gradio which clips longer video into shorter ones, transcribes them, saves the videos and transcriptions to an output directory, and then outputs "Finished!" to text or textbox. However, I only got "Finished!" to show up in the gradio text output field when I used the smallest Whisper model (ASR) and only clipped out a 1-minute section of the video. This took about 16 seconds. If I try the same inputs but use the small Whisper model instead, it will take about 2 minutes, and "Finished!" won't show up in the gradio text output field. If I use debug==True in launch and print "Finished!" prior to the return I'll see this in the colab output, but the text output of the gradio text output field will just continue to show an increasing time.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction
```
import gradio as gr
import time

def output_clips_and_srts(filenames):
    """Output clips and srts for input video"""
    # Convert inputs to lists
    filenames = list(filenames.split(";"))
    # Get video clip and transcibe
    for i, filename in enumerate(filenames):
        time.sleep(120)
    text = "Finished!"
    print(text)
    return text


inputs = [
    gr.Textbox(
        type="text",
        placeholder="filename_1;filename_2;filename_3",
        label="Filenames",
    ),
]

outputs = [gr.Text()]

demo = gr.Interface(fn=output_clips_and_srts, inputs=inputs, outputs=outputs, allow_flagging="never")

demo.launch(share=True)
```
### Screenshot

![Screenshot 2023-01-20 at 5 41 40 PM](https://user-images.githubusercontent.com/10121829/213818126-107b73b6-91a0-40fd-8625-b78082bde6aa.png)

### Logs

```shell
N/A
```

### System Info

```shell
gradio==3.16.2, Google Colab
```

### Severity

annoying

**Comment by abidlabs** [comment]
Does this only happen on colab or locally as well?

**Comment by CMobley7** [comment]
@abidlabs, it appears to happen on only Google Colab. Is there anything I can do to fix it? I don't want my non-technical users to have to install python and dependencies on their laptops.

**Comment by freddyaboulton** [comment]
Hi @CMobley7, if the request is expected to take longer than a minute, please enable the queue with `demo.queue().launch(...)`. That will use websockets by default and prevent 60 second timeouts that browsers impose on HTTP requests.

I use that on your demo on colab and I repeatedly get the expected output:

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/41651716/214092194-15e5f33c-c1b5-4f14-8642-06473a22686c.png">

For more info on queueing, consult the guide [here](https://gradio.app/key-features/#queuing) and don't hesitate to reach out!

**Comment by CMobley7** [comment]
Thanks! That appears to have worked. I ran into a queue error the first time I ran it, but that disappeared when I tried again.

**Comment by rscherl** [comment]
Thanks. But this doesn't seem to help on Sagemaker SL.
