### ISSUE TITLE
Tabs selected attribute not working if manually change tab

### ISSUE THREAD

**Issue by tomchang25** [gradio-app/gradio#3040]
### Describe the bug

Tabs won't dispatch change event or change selected if you have clicked tab manually.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Code: 
```
import gradio as gr

with gr.Blocks() as demo:
    with gr.Tabs(visible=True, selected="t1") as tabs1:
        state = gr.State("t1")
        with gr.Tab("T0", id="t0") as t0:
            gr.Textbox("0")
        with gr.Tab("T1", id="t1") as t1:
            gr.Textbox("1")
        with gr.Tab("T2", id="t2") as t2:
            gr.Textbox("2")

    btn = gr.Button()

    def btn_click(state):
        print("TEST", state)

        state = "t2"
        # return [gr.update(selected="t2"), gr.update(value="t2")]
        return [gr.update(selected=state), state]

    btn.click(fn=btn_click, inputs=state, outputs=[tabs1, state])

```

First, click button, tabs work fine and change the selected tab to t2.
Second, click t0 or t1 tab, tabs work fine and change the selected tab to t0, t1.
Finally, click button, tabs not working.

After 5 minutes surfing source code. I'm sure it's cause by

ui/packages/tabs/src/Tabs.svelte

```
# ui/packages/tabs/src/Tabs.svelte
...
	function change_tab(id: object | string | number) {
		$selected_tab = id;
		dispatch("change");
	}

	$: selected !== null && change_tab(selected);
...
```

change_tab is triggered by manually click tab, but it didn't change selected value at the same time.
and this will fix this issue.

```
# ui/packages/tabs/src/Tabs.svelte
...

	function change_tab(id: object | string | number) {
		selected = id
		$selected_tab = id;
		dispatch("change");
	}

	$: selected !== null && change_tab(selected);
...
```

### Logs

```shell
No error.
```

### System Info

```shell
3.16.1
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Would you like to open a PR @tomchang25 ? Thanks for looking into this!
