### ISSUE TITLE
`gr.File` with `file_types="image"` breaks front-end rendering

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#3043]
### Describe the bug

If a `gr.File` contains the `file_types="image"` the front-end never renders due to a `Uncaught (in promise) TypeError: i.map is not a function` in the browser console
![image](https://user-images.githubusercontent.com/788417/214070991-eee5efef-2861-4aad-9568-e901e903f639.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```py
import gradio as gr
with gr.Blocks() as demo:
    gr.File(label="Test", file_count="multiple", interactive=True, file_types="image") 

demo.launch()
```
https://huggingface.co/spaces/multimodalart/grFileBug

### Logs

```shell
FileUpload.svelte:49 Uncaught (in promise) TypeError: i.map is not a function
    at Ce (FileUpload.svelte:49:27)
    at Pt (index.4395ab38.js:4:6005)
    at new Ee (FileUpload.svelte:60:30)
    at Array.Me (File.svelte:57:16)
    at Array.Se (File.svelte:40:16)
    at jn (index.4395ab38.js:1:1425)
    at _n (index.4395ab38.js:76:13914)
    at Wc (index.4395ab38.js:76:14690)
    at Pt (index.4395ab38.js:4:6206)
    at new Zc (index.4395ab38.js:76:16107)
```
### System Info

```shell
gradio==3.16.2
```

### Severity

blocking upgrade to latest gradio version

**Comment by apolinario** [comment]
That works! Somehow I had old code that did not use a list and it used to work - so that broke on 3.16.x - but as a list it did work!

**Comment by freddyaboulton** [comment]
Glad it works! Will put up a PR to check that `file_types` is a list and raise an error to prevent front-end crashing
