### ISSUE TITLE
Infinite loop when on cascade update if JSON type component in cascade

### ISSUE THREAD

**Issue by Norbiox** [gradio-app/gradio#3056]
### Describe the bug

Hi everyone,
I've tried to achieve cascade of updating component  using `change` event. However if one of components in cascade is of type JSON then this field is constantly updated with no sign of ever stopping. I think it's a bug because if I change this field to Text type everything works as expected. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
#!/usr/bin/env python3
import gradio as gr

def returns_dict(value):
    return {"key": value}

with gr.Blocks() as demo:
    with gr.Row():
        field1 = gr.Text(interactive=True)
        field2 = gr.JSON()
        field3 = gr.Text()

    field1.change(fn=returns_dict, inputs=field1, outputs=field2)
    field2.change(fn=returns_dict, inputs=field2, outputs=field3)

if __name__ == "__main__":
    demo.launch()
```

### Logs

```shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

(I set `debug=True` in `launch` method but that's all I got)
```

### System Info

```shell
Gradio: 3.16.2
Python: 3.10.9
System: ArcoLinux with kernel 6.1.5-arch2-1
```

### Severity

serious, but I can work around it

**Comment by aliabid94** [comment]
Looking into this, thanks for reporting!
