### ISSUE TITLE
gradio.Request worked？There's no example where I can run it successfully！/(ㄒoㄒ)/~~

### ISSUE THREAD

**Issue by JLWLL** [gradio-app/gradio#3063]
### Describe the bug

I have read your usage document, where request is what I need, in this [document](https://gradio.app/docs/#request), there is only a simple example, I want to know if there is a request header component when someone visits my gradio instance?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

My problem is with the project currently in use.
THE [webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui)
I wants to add gradio.Request in this project ,but the method in practice is not the same as the method in the documentation.
`import gradio as gr
def echo(name, request: gr.Request):
    print("Request headers dictionary:", request.headers)
    print("IP address:", request.client.host)
    return name
io = gr.Interface(echo, "textbox", "textbox").launch()`
![image](https://user-images.githubusercontent.com/86763551/214779665-78a140f5-5438-41e3-a637-cef8c4234cae.png)
[U can see here](https://gradio.app/docs/#request)

How can I using it in  [webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui)

I didn`t` find that gr.Interface in webui.
The code is:
`with gr.Blocks(analytics_enabled=False) as txt2img_interface:`
and
`interfaces = [(txt2img_interface, "txt2img", "txt2img")]
with gr.Tabs(elem_id="tabs") as tabs:
     for interface, label, ifid in interfaces:
         with gr.TabItem(label, id=ifid, elem_id='tab_' + ifid):
             interface.render()`
Where can I add Request when interface bulid like this?Maybe add in `gr.Blocks(analytics_enabled=False) as txt2img_interface`?
There is no mention of how such cases are handled. Is this allowed or wrong?

`(*>﹏<*)′The documentation for request is too small, please add more examples of use in the [document](https://gradio.app/docs/#request)

### Logs

```shell
None
```

### System Info

```shell
3.16
```

### Severity

annoying

**Comment by JLWLL** [comment]
![image](https://user-images.githubusercontent.com/86763551/214845783-888b131f-a24f-46f8-9d8f-5af90c9660a7.png)
Did gr.Request work in Example like this?

**Comment by blacksino** [comment]
你好 ，请问你这个问题解决了么，我这边也没法很好的使用这个gr.request
