### ISSUE TITLE
Better error messaging for spaces created with the Deploy button from a model repo

### ISSUE THREAD

**Issue by sayakpaul** [gradio-app/gradio#3064]
- [x] I have searched to see if a similar issue already exists.

Does it make sense to have the following (for Spaces deployed directly from a model page using the deploy option)?

* Better error messaging when the model is loading in the space instead of a plain "Error"? One can check the logs to verify this, but many users might prefer the former option.

**Comment by abidlabs** [comment]
Closed via #3194!
