### ISSUE TITLE
Video change event not trigger if the value is changed by gr.update()

### ISSUE THREAD

**Issue by tomchang25** [gradio-app/gradio#3069]
### Describe the bug

Video change event not trigger if the value is changed by gr.update()

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Follow this [demo](https://github.com/tomchang25/gradio/blob/video-change/demo/video_change/run.py)

There are three set of experiment, Textbox, Video and Image.
The value of each components are changed by other components. For example.

Textbox1 change value to Textbox2
Radio1 change value to Video
Radio2 change value to Image

Each change event will trigger a print function to show event is work or not.
The result show every components working good except Video.

### Screenshot

(Video change events can only triggered by manually remove and upload video)
![image](https://user-images.githubusercontent.com/31534748/215109508-f505e2e9-95d9-4b47-b498-a9d171de6635.png)

### Logs

```shell
no error code.
```

### System Info

```shell
3.16.2
```

### Severity

annoying

**Comment by tomchang25** [comment]
Update: File have a same issue.

**Comment by tomchang25** [comment]
I found out that the video component was not implemented on:change callback for some reason.
I'll deal with this and request PR recently.

**Comment by abidlabs** [comment]
Thanks @tomchang25!

**Comment by abidlabs** [comment]
Closed via #3098 thanks @tomchang25!
