### ISSUE TITLE
Document iframe permissions

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#3070]
When embedding via an iFrame, you need to enable various permissions on that iFrame (`<iFrame allow="permisions_here..." />`). However, which permissions are needed depends entirely on what the component it and what mode that component is running in.

- Do we even want to document this? Our general advice for embedding is to use the web component. None of these issues are present when using the web components, they are specific to iFrames.
- If we do want to document it then where should we do so? I think the based place would actually be the embed snippet on the space itself. It should dynamically have the correct permissions.
- We could also document on the docs or in a giude.

If we do decide to document this in any way we need to figure out what permissions are needed for what component and for what variants or modes of those components.

It does feel like quite a lot of work for something that I am no convinced we should really be encouraging anyway.

**Comment by abidlabs** [comment]
What we've done in some of the Guides which use iframes is to simply ask for every possible browser permission: 

```html
<iframe src="https://osanseviero-helsinki-translation-en-es.hf.space" frameBorder="0" height="450" title="Gradio app" class="container p-0 flex-grow space-iframe" allow="accelerometer; ambient-light-sensor; autoplay; battery; camera; document-domain; encrypted-media; fullscreen; geolocation; gyroscope; layout-animations; legacy-image-formats; magnetometer; microphone; midi; oversized-images; payment; picture-in-picture; publickey-credentials-get; sync-xhr; usb; vr ; wake-lock; xr-spatial-tracking" sandbox="allow-forms allow-modals allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-downloads"></iframe>
```

This doesn't seem to cause any issues (like the browser doesn't ask for unnecessary notification). Perhaps we can trim this down a little bit to remove the unnecessary permissions and then simply suggest this approach in the Guide for users?

**Comment by cowanAI** [comment]
this worked for you still today?

**Comment by abidlabs** [comment]
Hi @cowanAI can you share the iframe embedding code that you tried and what behavior you experienced?

**Comment by cowanAI** [comment]
Hello @abidlabs I used the same code you posted above to embed on an editor x website, the app loads perfectly but when you try to record it will go to error, mostly due to a cross domain policy, I spent 7 hours today trying to fix it and nothing, tried like 10 different html codes from different sources, they all load the app, but the microphone won't record or it won't pop that google chrome gray window that asks the user to grant permission to record, also to note that all of this while the app is shared publicly, but we havent hosted it permanently yet on hugging faces

**Comment by cowanAI** [comment]
sorry to bother here @abidlabs , is this still up to date? "https://abidlabs.medium.com/quickly-deploying-gradio-on-aws-242af2374784" ? I'm trying to launch a EC2 Instance, this would be my last question

**Comment by abidlabs** [comment]
Hi @cowanAI that guide is pretty old although I quickly skimmed it and everything should continue to work. Let us know if you run into any issues.

**Comment by cowanAI** [comment]
@abidlabs I liked the speed that Im getting in hugging face, is there any way to make my space public there without sharing my code?

**Comment by abidlabs** [comment]
Officially, no. But there's an interesting workaround you could do:

1. Create a private Space with your real code 
2. Then create a public Space, with the following code:

```py
import gradio as gr

gr.load(path, src="spaces", hf_token=os.getenv("HF_TOKEN"))
```

where:

* `path` is the name of your private Space (e.g. "abidlabs/image_generator")
* `HF_TOKEN` is a secret in your Space with your HF token

This will basically create a public Space that acts as a proxy to your private Space -- you'll be able to embed the demo without any of the code being revealed.

**Comment by cowanAI** [comment]
Mmmm it works in visual code studio but for some reason in gradio it says "Space failed to start. Exit code: 1. Reason: Traceback (most recent call last): File "app.py", line 4, in <module> gr.load("cowan/Alicja", src="spaces", hf_token=os.getenv("HF_TOKEN")) AttributeError: module 'gradio' has no attribute 'load'" will keep trying thanks so much

**Comment by cowanAI** [comment]
@abidlabs 
Mmmm it works in visual code studio but for some reason in gradio it says "Space failed to start. Exit code: 1. Reason: Traceback (most recent call last): File "app.py", line 4, in gr.load("cowan/Alicja", src="spaces", hf_token=os.getenv("HF_TOKEN")) AttributeError: module 'gradio' has no attribute 'load'" will keep trying thanks so much

**Comment by cowanAI** [comment]
@abidlabs 
@abidlabs
Mmmm it works perfectly from visual code studio but for some reason in hugging spaces the same code  says "Space failed to start. Exit code: 1. Reason: Traceback (most recent call last): AttributeError: module 'gradio' has no attribute 'load'" will keep trying thanks so much

**Comment by abidlabs** [comment]
Ah that’s because you’re using an older version of Gradio in the space. You can change it in the README.md to the latest version

**Comment by cowanAI** [comment]
unfortunately it doesnt work, I really spent 4 hours trying at least 100 variables "Runtime error
Space failed to start. Exit code: 0. Reason:
Container logs:" at the end following your exact same indication interestingly it returns errors but with zero logs about why the error is happening

**Comment by cowanAI** [comment]
@abidlabs actually now the log says "bfqgm 2023-04-01T22:30:40.627Z Loaded as API:" it means that it loaded the space but I get the error

**Comment by abidlabs** [comment]
Can you link to the public Space?

**Comment by cowanAI** [comment]
@abidlabs of course! "https://huggingface.co/spaces/cowan/alicjademo"

**Comment by abidlabs** [comment]
Hi @cowanAI I don't see any Space when I visit that link. Are you sure the link is correct?
