### ISSUE TITLE
Textbox component not correctly hidden

### ISSUE THREAD

**Issue by pangbo13** [gradio-app/gradio#3071]
### Describe the bug

I attempted to hide the Textbox component by setting its `visible` property to False, but it leaves a blank box as shown in the third box in the following image.

![image](https://user-images.githubusercontent.com/51732678/215153418-3839ee57-ddb0-4539-a4bc-4451319e963c.png)

![ezgif-5-a23d7101c9](https://user-images.githubusercontent.com/51732678/215153167-8114e265-c521-44f9-a055-09fd248cfce8.gif)

I believe the Textbox should behave like other components, being completely hidden, for example, the DropDown can be completely hidden.

![ezgif-5-d9da89522d](https://user-images.githubusercontent.com/51732678/215155396-daed517e-0e6b-4f37-8b44-8d5e59ac152a.gif)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Here is the code
```
import gradio as gr

def hide_fn():
    return gr.Textbox.update(visible=False)

def show_fn():
    return gr.Textbox.update(visible=True)

with gr.Blocks() as demo:
    with gr.Row():
        hide = gr.Button(value="Hide")
        show = gr.Button(value="Show")
        textbox = gr.Textbox(label="Textbox",interactive=True)

    hide.click(fn=hide_fn,outputs=[textbox])
    show.click(fn=show_fn,outputs=[textbox])

demo.launch(debug=True)
```

There is also a simpler way to reproduce this issue：

```
import gradio as gr
with gr.Blocks() as demo:
    with gr.Row():
        button = gr.Button(value="Do Nothing")
        textbox1 = gr.Textbox(label="Textbox1",visible=False)
demo.launch(debug=True)
```
![image](https://user-images.githubusercontent.com/51732678/215157489-64914012-292f-4bab-ae80-2855912a7587.png)

### Screenshot

![ezgif-5-a23d7101c9](https://user-images.githubusercontent.com/51732678/215153167-8114e265-c521-44f9-a055-09fd248cfce8.gif)

![image](https://user-images.githubusercontent.com/51732678/215157513-3cd5f3b2-a752-44d2-b748-4d71cfb46ecd.png)

### Logs

I don't think the log provides any meaningful information.

```shell
Running on local URL:  http://127.0.0.1:7870

To create a public link, set `share=True` in `launch()`.

Keyboard interruption in main thread... closing server.
```

No error from Chrome Devtools.

### System Info

```shell
gradio 3.16.2
Windows 10 Version 22H2 (Build 19045.2486)
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32

Google Chrome 109.0.5414.119
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @pangbo13 I can't reproduce this on the latest version of the code on `main`. It seems that we've fixed this as part of #2840. Feel free to try the code on `main`  ([instructions to do so are at the top here](https://gradio.app/docs/main/)) and reopen the issue if it is not fixed.

We should release to pypi sometime in the next couple of days.
