### ISSUE TITLE
Download Button for video or Image output

### ISSUE THREAD

**Issue by vijishmadhavan** [gradio-app/gradio#3072]
Is there a option to have download button below Image or video output?

Please help!

**Comment by abidlabs** [comment]
Hi @vijishmadhavan I would suggest using the `File` component as a secondary output under the image/video to be able to download the file more easily. Here's a very simple example:

```py
def identity(x):
    return x, x

gr.Interface(
    identity, 
    gr.Image(type="filepath"), 
    [gr.Image(), gr.File()]
).launch()
```
