### ISSUE TITLE
Filter out files based on file_types when choosing the `directory` option

### ISSUE THREAD

**Issue by Dsantra92** [gradio-app/gradio#3077]
- [x] I have searched to see if a similar issue already exists.

Currently `gr.File(file_count="multiple", file_types=["image"])` checks if the file is an image before uploading. I was hoping for a similar behavior for `gr.File(file_count="directory", file_types=["image"])` where using the `file_types` option with `directory` should selective upload files with matching types. 

With the current implementation, mentioning `file_types` with `file_count=directory` doesn't have effect.

**Comment by freddyaboulton** [comment]
To be sure, `gr.File(file_count="multiple", file_types=["image"])` works as expected though, right? It only let's you upload images.

**Comment by Dsantra92** [comment]
> To be sure, `gr.File(file_count="multiple", file_types=["image"])` works as expected though, right? It only let's you upload images.

Yes, it works as expected.

**Comment by abidlabs** [comment]
It feels quite niche to me to support filtering file types when a directory is uploaded. Perhaps we should just have a warning displayed if someone uses `file_types` with file_count="directory". @dawoodkhan82 @freddyaboulton thoughts?

**Comment by ROBERT-MCDOWELL** [comment]
@abidlabs 
ok so does it mean that if directory is selected the user can upload whatever files?
also if I set the component dynamicall from "single" to "directory", I have not way to remove the warning saying "file_types" is ignoredd... 
if multiple files can be filtered, the directory option should too to avoid upload abuse. 
make a condition that only the files allowed weill be in the list.....

**Comment by abidlabs** [comment]
cc @dawoodkhan82

**Comment by ROBERT-MCDOWELL** [comment]
would you like I open a new issue on this subject?
to see "E:\Z______MYDATA\DEV\PYTHON\ebook2audiobook\python_env\Lib\site-packages\gradio\components\file.py:113: UserWarning: The `file_types` parameter is ignored when `file_count` is 'directory'.
  warnings.warn(" everytime we select 'directory' as file_count is frustrating... 
to not filter like multiple files and not limit the total size of uploads is going to create a massive security breach through gradio application IMHO....

**Comment by ROBERT-MCDOWELL** [comment]
kk
