### ISSUE TITLE
Enter Chinese in the DataFrame component，..

### ISSUE THREAD

**Issue by WangJ970316** [gradio-app/gradio#3083]
### Describe the bug

https://user-images.githubusercontent.com/48046091/215408060-c4699e01-d9db-4b24-8d59-0bab5baf25eb.mov

When I enter Chinese in the DataFrame component, each keyboard entry will be retained in the text box, but I haven't completed the entry yet.
When I enter the contents of headers, there is no such problem

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

As shown in the video

### Logs

```shell
As shown in the video
```

### System Info

```shell
As shown in the video
```

### Severity

annoying

**Comment by xianbaoqian** [comment]
I think this might be related to the handling of this event. https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event

**Comment by WangJ970316** [comment]
> I think this might be related to the handling of this event. https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event

I read the content of the problem carefully, but I still don't know how to solve the problem in the video

**Comment by aliabid94** [comment]
Fixed! Should be in the next release of gradio.

**Comment by xianbaoqian** [comment]
Thanks @aliabid94 !
