### ISSUE TITLE
Adding new event handlers outside the original `gr.Blocks` scope

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3085]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I know this is a stretch, but having this feature would be useful

Due to the way the stable-diffusion-webui is architected, extensions have their own `gr.Blocks` context separate from the script `gr.Blocks`. What I want to do is create some components in the script blocks and then connect event handlers to them that use elements in the extensions blocks as outputs. Something like this:

```python

# Script part
with gr.Blocks():
   script_component = gr.Slider("Script slider", value = 1, minimum = 0, maximum = 10)
   extension_affecting_button = gr.Button("Change extension slider")

# Extension tab
with gr.Blocks():
   script_affecting_button = gr.Button("Change script slider")
   script_affecting_button.click(lambda: 5, inputs=[], outputs=[script_component])
   extension_component = gr.Slider("Extension slider", value = 1, minimum = 0, maximum = 10)
   extension_affecting_button.click(lambda: 5, inputs=[], outputs=[extension_component])
```

Last time I tried `script_affecting_button` works but `extension_affecting_button` does not, it seems you can't register new event handlers once the `gr.Blocks` scope is exited. This makes sense because `script_affecting_button` is still in the second `gr.Blocks` when the `click()` handler is registered

I request this because rearchitecting webui to work within a single `gr.Blocks` context is probably infeasible, there are already way too many extensions out there to make such a breaking change easily

The thing I want to do with this is have a dropdown and a "copy this value to other dropdown" button on both the script and extension tabs, right now it works but only in one direction

**Describe the solution you'd like**  
I would like `extension_affecting_button` to work, same as with `script_affecting_button`

**Additional context**

**Comment by abidlabs** [comment]
Hi @space-nuko thanks for raising this question. It is possible to nest Blocks inside other Blocks. So you could do something like the following, which works for me:

```py
import gradio as gr

with gr.Blocks() as demo:
    
    # Script part
    with gr.Blocks():
       script_component = gr.Slider(label="Script slider", value = 1, minimum = 0, maximum = 10)
       extension_affecting_button = gr.Button("Change extension slider")

    # Extension tab
    with gr.Blocks():
       script_affecting_button = gr.Button("Change script slider")
       script_affecting_button.click(lambda: 5, inputs=[], outputs=[script_component])
       extension_component = gr.Slider(label="Extension slider", value = 1, minimum = 0, maximum = 10)
       extension_affecting_button.click(lambda: 5, inputs=[], outputs=[extension_component])
        
demo.launch()
``` 

Would this work for you?

**Comment by abidlabs** [comment]
Closing as this should hopefully solve the issue!
