### ISSUE TITLE
gr.Blocks() makes everything super slow

### ISSUE THREAD

**Issue by xianbaoqian** [gradio-app/gradio#3086]
### Describe the bug

https://user-images.githubusercontent.com/38108242/215495495-10efda90-3b9f-4daf-8f02-a1ca99304a95.mov

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction
```
%%blocks 

import gradio as gr

# This is slow???
with gr.Blocks() as demo:
    gr.Markdown("# Upload a model/data repo to HF!!!")
    file_path = gr.Textbox(placeholder="URL to the zip file")
    repo_path = gr.Textbox(placeholder="repo name, example: USERNAME/REPO")
    repo_type = gr.Dropdown(["dataset", "model"])
    out = gr.Textbox()
```

### Logs

```shell
None
```

### System Info

```shell
JupyterNotebook
Mac M1
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment]
Hi @xianbaoqian ! If you are using `%%blocks` , then `gr.Blocks()` is already created under the hood and you do not need a second context. I think the creation of that second context is what's causing the additional latency.

**Comment by xianbaoqian** [comment]
Thanks @freddyaboulton  That explains things :-) Do you think that there will be a case for nested blocks in the app? If not maybe it's a good idea to add a warning when blocks are nested to help users like me - basically copying the code from tutorial and paste that into %%blocks magic and hoping it work the best. And it did work but just slow, that's where some of the confusion comes from :-)

**Comment by abidlabs** [comment]
Hi @xianbaoqian interestingly, there are cases for nested Blocks so we wouldn't want to show that warning. I think in this case, we'd just ask users to consult the documentation for the %%blocks here, which describes the usage here: https://gradio.app/developing-faster-with-reload-mode/#jupyter-notebook-magic

**Comment by Seedmanc** [comment]
I still don't get how to use %%blocks and at the same time pass parameters which are usually supplied by the .Blocks() or .queue()/.launch() commands. If those are omitted in this mode, then how?

**Comment by xianbaoqian** [comment]
Hi @Seedmanc  I ended up doing the following in the notebook, and it has been awesome.

import gradio as gr

try: 
    demo = demo.clear()
except:
    demo = gr.Blocks()

with demo:
    bla

demo.launch(quiet=True) # so that it doesn't block

**Comment by 3cham** [comment]
Hi @abidlabs, @xianbaoqian: I have the same issue, but not in notebook but as a single web app. My app hash only 5 components defined within a Block and it takes about 12 seconds to start up, no db initialization or something heavy. Which I think too slow. Do you have any suggestions, what might help improving the startup time? Many thanks!
