### ISSUE TITLE
gradio audio input error

### ISSUE THREAD

**Issue by vijishmadhavan** [gradio-app/gradio#3094]
gr.inputs.Audio(type="file")

ValueError: Invalid value for parameter `type`: file. Please choose from one of: ['numpy', 'filepath']

Why Iam getting this error, gr.inputs.Audio(type="file") this is allowed right?

**Comment by aliabid94** [comment]
Seems like we did not deprecate this cleanly, for now please use `gr.Audio(type="filepath")` rather than `gr.inputs.Audio(type="file")`

**Comment by aliabid94** [comment]
Are you running an existing file from somewhere?

**Comment by abidlabs** [comment]
Given that `gr.inputs.Audio` has been deprecated for almost a year, it's safe to require users to migrate to `gr.Audio`
