### ISSUE TITLE
File as inputs

### ISSUE THREAD

**Issue by pykeras** [gradio-app/gradio#31]
Hi, thanks for the great work
wonder if there is any way to select a TXT/CSV file as input ?

**Comment by aliabd** [comment]
Hey @pykeras, thanks for opening the issue. There's no way to do that right now, but it's in our roadmap. We'll follow up here with you when we push that functionality. 

What is the use case you have in mind?

**Comment by pykeras** [comment]
> Hey @pykeras, thanks for opening the issue. There's no way to do that right now, but it's in our roadmap. We'll follow up here with you when we push that functionality.
> 
> What is the use case you have in mind?

thanks for the reply,
doing some NLP tasks (Q&A - NER) sometimes there are lots of data, so having them as a batch is a good thing, the client sends this as CSV/TXT file.

**Comment by abidlabs** [comment]
With the latest version of `gradio 1.1.0`, we now support arbitrary file inputs. Thanks for the suggestion!
