### ISSUE TITLE
Passing a default value to `Dropdown`

### ISSUE THREAD

**Issue by merveenoyan** [gradio-app/gradio#3103]
### Describe the bug

One of our contributors reported they can’t pass value parameter to Dropdown in latest version of gradio, as it shoots
```
9 demo_inputs = [                                                                            │
│ ❱  50 │   gr.inputs.Dropdown(                                                                    │
│    51 │   │   label="Model",                                                                     │
│    52 │   │   choices=data_scraping(model_url_list()),                                           │
│    53 │   │   value="Tune-A-Video-library/a-man-is-surfing"                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: __init__() got an unexpected keyword argument 'value'
```
then I looked at documentation and it takes value, and we looked at source code and it says it takes default ? (I’m confused😕 ) What is the way to pass a default value to Dropdown?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Provided above.

### Logs

```shell
Provided above.
```

### System Info

```shell
3.17.0
```

### Severity

annoying

**Comment by merveenoyan** [comment]
Maybe ping @dawoodkhan82 or @freddyaboulton

**Comment by freddyaboulton** [comment]
Hmm this demo has `value` for Dropdown and it works: https://github.com/gradio-app/gradio/blob/main/demo/blocks_multiple_event_triggers/run.py

**Comment by freddyaboulton** [comment]
Ah, `gr.inputs.Dropdown` is deprecated and it's just kept for backwards compatibility. It has a slightly different signature than gr.Dropdown and so that's probably where the confusion is coming from.

**Comment by merveenoyan** [comment]
ah I didn't pay attention to that! 🤦‍♀️ Thanks!

**Comment by freddyaboulton** [comment]
Anytime!!
