### ISSUE TITLE
In v3.17.0, Gallery can't show a grid of images!

### ISSUE THREAD

**Issue by myhz0606** [gradio-app/gradio#3105]
### Describe the bug

Gallery can not show a grid of Images, though set ` gr.Gallery(label="Generated images", show_label=False, elem_id="my_gallery").style(grid=6)` .
Version of 3.16.0 didn't have this problem.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import os
import random
import requests
from PIL import Image 
 
import gradio as gr
 
 
def fake_gan(*args):
    images = [
        (random.choice(
            [
                "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
                "https://images.unsplash.com/photo-1554151228-14d9def656e4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=386&q=80",
                "https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8aHVtYW4lMjBmYWNlfGVufDB8fDB8fA%3D%3D&w=1000&q=80",
                "https://images.unsplash.com/photo-1546456073-92b9f0a8d413?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
                "https://images.unsplash.com/photo-1601412436009-d964bd02edbc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80",
            ]
        ), f"label {i}")
        for i in range(10)
    ]
    return images
 
 
with gr.Blocks() as demo:
    with gr.Column():
        with gr.Row():
            text = gr.Textbox(
                label="Enter your prompt",
                show_label=False,
                max_lines=1,
                placeholder="Enter your prompt",
            ).style(
                container=False,
            )
            btn = gr.Button("Generate image").style()
        gallery = gr.Gallery(label="Generated images", show_label=False, elem_id="my_gallery") gr.Gallery(label="Generated images", show_label=False, elem_id="my_gallery").style(grid=6)
        btn.click(fake_gan, None, gallery)
 
if __name__ == "__main__":
    demo.launch(enable_queue=False, server_name='0.0.0.0', share=False, server_port=7777)

### Screenshot

<img width="1691" alt="Screenshot 2023-02-01 at 08 47 35" src="https://user-images.githubusercontent.com/46910628/215917849-d8c5f9b9-5a25-454e-87a9-3374c99bdcfe.png">

### Logs

```shell
Running on local URL:  http://0.0.0.0:7777

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
Gradio version: '3.17.0'
system version: Ubuntu 20.04.3 LTS
Browser: Google
```

### Severity

annoying

**Comment by abidlabs** [comment]
Lookig into this, thanks @myhz0606 for bringing this to our attention

**Comment by pngwn** [comment]
I think this will be theming, will take a look.
