### ISSUE TITLE
Support session state across multiple pages or page refresh (e.g. with LocalStorage)

### ISSUE THREAD

**Issue by hshen14** [gradio-app/gradio#3106]
Right now, the session state is either global shared between users or local within a page. We are seeing the needs to support session state across multiple pages.

E.g., we host a service on Hugging Face spaces, and we ask users to login with token first before using the spaces. The ideal case is users just need to login once but use the spaces multiple time without further login (even the page is refreshed, or multiple pages requires login status).

**Comment by decent-engineer-decent-datascientist** [comment]
@abidlabs is this something that's on the roadmap?

**Comment by abidlabs** [comment]
We’re planning on tackling it but probably not anytime soon as we have competing priorities at the moment

**Comment by oaksharks** [comment]
Hi, abidlabs, Is there a workaround to keep chat histroy in `gr.Chatbot` after refreshing a page?

**Comment by decent-engineer-decent-datascientist** [comment]
@abidlabs ^ that is my use case as well; curious what your recommended workaround is.

**Comment by abidlabs** [comment]
Hi folks! It is possible to use localstorage by using custom javascript for now. Here's a gradio app that does this: https://huggingface.co/spaces/radames/gradio_window_localStorage

**Comment by oaksharks** [comment]
Hi @abidlabs,
How can I find the session data associated with the page after the user refreshes it using the above configuration?
I mean, although it can store data, how can i find previous `gr. State`?

**Comment by deckar01** [comment]
It would be nice to persist this on the back end so that authenticated sessions synchronize across devices also. I suspect that would be simpler to implement, and I think it can be worked around with some helper utilities now. (I will assume in memory session persistence, because adding gracefully upgrading an old states adds significant complexity, ala db migrations).

```py
import gradio as gr
class Session:
    foo = ''
    bar = ''

with gr.Blocks() as demo:
    foo_txt = gr.Textbox()
    bar_txt = gr.Textbox()
    save(Session, demo, foo=foo_txt, bar=bar_txt)

demo.launch(auth=[("a", "1"), ("b", "2")])

**Comment by deckar01** [comment]
It would be nice to persist this on the backend so that authenticated sessions synchronize across devices also. I suspect this is actually simpler to implement. (I will assume in-memory persistence, because db-like schema migrations add significant complexity.)

Here is my current workaround:

```py
import gradio as gr
from helper import persist

with gr.Blocks() as demo:
    foo_txt = persist(gr.Textbox())
    bar_txt = persist(gr.Textbox())

demo.launch(auth=[("a", "1"), ("b", "2")])
```

<details><summary>helper.py</summary>

```py
from gradio.context import Context
from gradio import Request


def persist(component):
    sessions = {}

    def resume_session(request: Request):
        return sessions.get(request.username, component.value)

    def update_session(value, request: Request):
        sessions[request.username] = value

    Context.block.load(resume_session, outputs=component)
    component.change(update_session, inputs=[component])

    return component
```

</details>

I suppose this could be encapsulated in gradio for the slightly sweeter `gr.Textbox(persist=True)` syntax. A complete solution should probably also detect the auth type and choose the session key accordingly.

**Comment by arian81** [comment]
@abidlabs Hey is there any update on this? I think persisting sessions would be a very useful feature and I see this issue is from a year ago.

**Comment by abidlabs** [comment]
I agree, cc @aliabid94 perhaps if he has bandwidth.

**Comment by kerthcet** [comment]
+1 to see this happen.

**Comment by Moibe** [comment]
> Hi folks! It is possible to use localstorage by using custom javascript for now. Here's a gradio app that does this: https://huggingface.co/spaces/radames/gradio_window_localStorage

It is a good example on how to set storage, but not on how to get storage. In the sample it gets the localStorage variable but never use it within the code. The results that the app display come directly from the input fields and not from the localStorage. For someone that is not an expert like me, it would have been very useful that this code also examples on how to retrieve the localStorage not just setting it.

**Comment by JackismyShephard** [comment]
> It would be nice to persist this on the backend so that authenticated sessions synchronize across devices also. I suspect this is actually simpler to implement. (I will assume in-memory persistence, because db-like schema migrations add significant complexity.)
> 
> Here is my current workaround:
> 
> ```python
> import gradio as gr
> from helper import persist
> 
> with gr.Blocks() as demo:
>     foo_txt = persist(gr.Textbox())
>     bar_txt = persist(gr.Textbox())
> 
> demo.launch(auth=[("a", "1"), ("b", "2")])
> ```
> 
> helper.py
> ```python
> from gradio.context import Context
> from gradio import Request
> 
> 
> def persist(component):
>     sessions = {}
> 
>     def resume_session(value, request: Request):
>         return sessions.get(request.username, value)
> 
>     def update_session(value, request: Request):
>         sessions[request.username] = value
> 
>     Context.root_block.load(resume_session, inputs=[component], outputs=component)
>     component.change(update_session, inputs=[component])
> 
>     return component
> ```
> 
> I suppose this could be encapsulated in gradio for the slightly sweeter `gr.Textbox(persist=True)` syntax. A complete solution should probably also detect the auth type and choose the session key accordingly. It is also possible to use request cookies for the session ID so that the UX feels like LocalStorage for anonymous users.

This is a really neat solution and in my opinion preferable to using localstorage. The only problem is that it does not work with accordions as they have no associated `change` function

**Comment by xinyii** [comment]
I have implemented the functions of reading and writing localStorage and saving chat history. https://huggingface.co/spaces/YiXinCoding/gradio-chat-history

**Comment by abidlabs** [comment]
That is so cool @xinyii!

**Comment by Ketzemot** [comment]
@xinyii and @abidlabs  could you please share your code that you used to create your gradio apps? That would be really great.

**Comment by ROBERT-MCDOWELL** [comment]
@Ketzemot 
click on files at the gradio app page!
