### ISSUE TITLE
Is it possible to only load the file once and keep it for live demo?

### ISSUE THREAD

**Issue by MultiPath** [gradio-app/gradio#311]
Hi,

I am building some demo with live=True. I take an optional input of uploading a file. However, I found that, when the file is uploaded, it will be constantly re-uploaded and save to different places when I change other inputs (like slider, textbox).

Is there any way to stop this? Also, it is also fixed when the file is selected. There seems no way to choose to upload a different file except for clear everything.

**Comment by abidlabs** [comment]
@aliabid94 this is a good point. We shouldn't reupload the file if it has not changed. Thanks for bringing this to our attention @MultiPath.

**Comment by abidlabs** [comment]
I think this is something we can facilitate with Blocks

**Comment by abidlabs** [comment]
Hi @MultiPath, thanks for opening up this issue. We have just beta released Blocks, which is a low-level API that can be used to build very customizable web apps in Python. You can try it by `pip install gradio==2.9b7`. 

We are still working on the documentation for Blocks, but here is a commented code snippet with a mock function that achieves what you are trying to do:

```py
import gradio as gr

# Create a "blocks" demo
demo = gr.Blocks()
 
# Everything inside the "with" becomes part of this demo
with demo:
    # Create a file input component and a button
    file_input = gr.File()
    btn = gr.Button("Upload File")
    
    # This "Variable" will hold the value of the file in the backend so it doesn't get passed back and forth
    file = gr.Variable(default_value=None)
    
    # This sends the file from the file input into the file to store it    
    btn.click(lambda x:x, file_input, file)
    
    # A mock function that simply returns the value of the slider. If a file is uploaded, it adds to that the length of the filepath.
    def fn_that_takes_optional_file(slider_value, file_path):
        if file_path is None:
            return slider_value
        else:
            return slider_value + len(file_path.name)

    # creates a slider (input) and number (output)        
    slider = gr.Slider(minimum=0, maximum=10)
    number_output = gr.Number()

    # whenever the slider changes, run the above function
    slider.change(fn_that_takes_optional_file, [slider, file], number_output)
    
demo.launch()
```
