### ISSUE TITLE
Display downloaded image from url as input ("not output")

### ISSUE THREAD

**Issue by vijishmadhavan** [gradio-app/gradio#3113]
I wanted to use random images downloaded from url's to be used as input. I understand that using it as input is possible, but i want it to be displayed(not as "output"). This input is then send to model to generate output.

**Comment by abidlabs** [comment]
Hi @vijishmadhavan, I'm not sure I understand the question. If you'd like to use text URL strings as inputs, you can use the `gr.Textbox` input. For general questions like this that are not feature requests or bugs, please use https://github.com/gradio-app/gradio/discussions or our Discord: https://t.co/JKepTfXraQ
