### ISSUE TITLE
504 Gateway Timeout on Hugging Face space when inference via API call

### ISSUE THREAD

**Issue by kvyb** [gradio-app/gradio#3114]
### Describe the bug

Whenever I launch inference on my space via post request to the API, after 60s I get a timeout.

I added queueing as specified in the docs, but it makes no difference 

`transcribe_btn.click(run_all, [file_url_in, selected_source_lang, selected_whisper_model, number_speakers], [transcription_df, system_info, video], queue=True, api_name="transcribe")`

and 

`demo.queue().launch(auth=[('admin','admin')], share=False, debug=True)
`
After the post request, the inference is run, but the API does not get the result since it's long timed out by then.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/kvyb/Transcribe-and-Diarise 

Go to the above link, login with: admin; admin. Press "use via API". Try to make a POST for login and then POST for "transcribe" via an API client like Postman. The Inference will launch, but the "transcribe" POST call will time out in a minute 

### Logs

```shell
POST /run/transcribe HTTP/1.1
Authorization: Bearer ************
Content-Type: application/json
User-Agent: PostmanRuntime/7.30.1
Accept: */*
Host: kvyb-transcribe-and-diarise.hf.space
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 111
Cookie: access-token=zoXdvaXEX6kp9fyPEl1dng; session-space-cookie=4c5c1de9c726c95e3bc04e212a67c508
 
{
"data": [
"https://litter.catbox.moe/w4l0fn.mp4",
"ru",
"base",
2
]
}
 
HTTP/1.1 504 Gateway Time-out
Server: awselb/2.0
Date: Thu, 02 Feb 2023 07:32:30 GMT
Content-Type: text/html
Content-Length: 132
Connection: keep-alive
 
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
```

### System Info

```shell
Hugging Face Gradio
```

### Severity

serious, but I can work around it

**Comment by kvyb** [comment]
Seems to be a HF issue, since hosting via "share" on gradio.app works fine.

**Comment by abidlabs** [comment]
If you use a Space via an API call, currently queuing is not supported and requests will time out after 60 seconds. This is a limitation of the HTTP protocol. We are going to be working on adding websocket support to the API which should allow longer inference times! (See #2516)
