### ISSUE TITLE
Reach gradio app deployed on nginx server 

### ISSUE THREAD

**Issue by samirsalman** [gradio-app/gradio#312]
Hi, how can I reach my gradio app deployed on my own nginx webserver?

**Comment by abidlabs** [comment]
Please see this guide: https://abidlabs.medium.com/quickly-deploying-gradio-on-aws-242af2374784

Does that help? If not, please reopen with more details on what you are seeking.

**Comment by samirsalman** [comment]
Sorry, I try to be more clear, the real issue is to change the gradio app base path, because on my server I can't use "/" like base path.

**Comment by abidlabs** [comment]
Typically the way to do this is to run the Gradio app on some port, and then write an nginx rule to expose that port with any path you want.
