### ISSUE TITLE
New

### ISSUE THREAD

**Issue by Caoxokhuyen** [gradio-app/gradio#3131]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by abidlabs** [comment]
Hi @Caoxokhuyen it looks like there's no issue mentioned above, so let me go ahead and close.

**Comment by Caoxokhuyen** [comment]
Tôi viết nhầm 🤷
