### ISSUE TITLE
Allow markdown in the `label` parameter

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#3143]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
For some situations, for example asking for a token, would be helpful to include a link to where to grab the token I would like to allow markdown for the `label` parameter of the components

**Describe the solution you'd like**  
Allow markdown in the `label` parameter

**Additional context**  
For example this
<img width="317" alt="image" src="https://user-images.githubusercontent.com/788417/217311642-7e749bef-0d25-4c65-9d61-051b482ccacd.png">

Could become this: 
<img width="285" alt="image" src="https://user-images.githubusercontent.com/788417/217311900-24818a4f-de24-4680-ab20-ab36837e0c97.png">

**Comment by abidlabs** [comment]
Interesting suggestion @apolinario. I see the value of it. We use the `label` internally for various things (e.g. the column header for flagging) so one idea would be to keep the `label` parameter a simple string but add support for inline Markdown when we add "descriptions" for parameters (#959) -- cc @aliabid94

**Comment by apolinario** [comment]
Makes sense that this may live in #959 , although I thought of this as a way to potentially streamline things and keep the UI simple (as the description adds more vertical height or complexity to the UI). But I understand that the `label` has uses where markdown doesn't make sense and I think `descriptions` are a fair enough solution

**Comment by abidlabs** [comment]
Let's do that then, I'll close this issue and move the suggestion to #959

**Comment by jamie0725** [comment]
Hi @abidlabs, is markdown supported for parameters like "label" or "description" now?

**Comment by abidlabs** [comment]
No it is not -- just text
