### ISSUE TITLE
Checkbox change event won't be triggered for javascript

### ISSUE THREAD

**Issue by butaixianran** [gradio-app/gradio#3161]
### Describe the bug

So, when setting checkbox's value with a button's click event, checkbox can trigger its change event at python side.

**But at javascript side**, I listened on checkbox's `change`, `input` and `submit` events, none of them is triggered. 

**So, when setting checkbox's value with another component's event, is there a way to let javascript side can know this checkbox is changed? If checkbox can not do this, then which component can be used as a bridge like this?**

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Already described above.

### Logs

```shell
No need in this case
```

### System Info

```shell
Gradio 3.18, Windows 11
```

### Severity

annoying

**Comment by pngwn** [comment]
Smae as #3159. This is expected behaviour.

Do this in your JS:

```js
el.checked = true
el.dispatchEvent(new Event('change'))
```

**Comment by butaixianran** [comment]
Have you read this issue clearly?

I need to trigger it at python side, but listened on javascript side, not from javascript side.

Your code above is triggered at javascript side. That's not what I need here.

**Comment by pngwn** [comment]
Issues can be reopened, it isn't the end of the world. But all issues should come with a clear reproduction before they can considered a bug.

Regardless, this kind of custom JS isn't supported. The HTML + JS is an internal implementation detail and provided 'as is'. What you are trying to do is not supported by the library and is not a bug.

If you would like to share exactly what you are trying to do more broadly (with code examples) either in a GitHub discussion or on discord we can try to suggest an alternative approach that doesn't rely on this kind of custom javascript.

**Comment by butaixianran** [comment]
Here is a common thought for this, if this project uses 2 different tech at server side and client side, then this project should build a way to let them can communicate from both side, right?

Chrome extension is a pure javascript thing, but it also build a msg way to let background js can communicate with in-page js. Because that's a common need. 

Once javascript and python can communicate with each other in this project, then developers can handle almost anything without worry python component's function or performance.

What I'm dong here, is using a textbox to store data for both side, then try to use a checkbox's change event for notification, let the other side know there is some new data for you, in this textbox now.

Although mine is a small project, but let client and server side can have a way to send msg to each other is a very useful and common need.

**Comment by pngwn** [comment]
If you are writing a lot of custom javascript, have you considered using Gradio as an API and building your own UI?

**Comment by butaixianran** [comment]
Thanks for your advice, I'm doing this based on other people's project, which already finished a lot UI tasks. So, I won't have to do it from zero.

The good part of gradio is it can finish most simple UI tasks very fast. But for left complex or performance sensitive UI tasks, javascript is better.

So, the fastest way will always be using gradio and js together. That means msg between js and python from both sides is needed.

That's also what gradio wanted, right? To be a super fast choice to get UI tasks done.
