### ISSUE TITLE
add max_lines in JSON component

### ISSUE THREAD

**Issue by xu-song** [gradio-app/gradio#3172]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

JSON Component is not good with long json string.

**Comment by abidlabs** [comment]
Hi @xu-song can you please provide a full code example where the JSON component doesn't look good with a long json string?

**Comment by xu-song** [comment]
long json string can not be show in one page,
![image](https://user-images.githubusercontent.com/13825126/218239169-5242397f-e28a-4512-9dbe-a3b2191e4e96.png)

code: https://huggingface.co/spaces/eson/bert-perplexity/blob/main/app.py
demo: https://huggingface.co/spaces/eson/bert-perplexity

**Comment by abidlabs** [comment]
Thanks @xu-song for the code example. So just to clarify, you'd like to set a maximum height and scrollbars, correct?

**Comment by xu-song** [comment]
yes

**Comment by abidlabs** [comment]
Hi @xu-song I would recommend using a little bit of css to accomplish this. Here's some example code:

```py
import gradio as gr

json_output = [{"token": "abc", "probability": 0.5} for i in range(10)]
css = "#json-container {height: 400px; overflow: auto !important}"

gr.Interface(lambda x: json_output, "textbox", gr.JSON(elem_id="json-container"), css=css).launch()
```

which produces this:

<img width="962" alt="image" src="https://user-images.githubusercontent.com/1778297/218546169-9d309bc9-f565-4659-bcda-3a30f33216b4.png">

I'll go ahead and close this issue, but feel free to reopen if this doesn't solve your issue!

**Comment by xu-song** [comment]
thanks
