### ISSUE TITLE
Persist through refreshes

### ISSUE THREAD

**Issue by GJBoth** [gradio-app/gradio#3173]
I'm using Gradio to build a simple web GUI for an application managing some devices. It's been wonderful, but the main issue holding me up right now is that gradio doesn't keep its state through refreshes. 

As a workaround, I've tried putting all the values in a separate python object, and have everything initialized from this object. The theory being that the interface would reset, but not the object. However, it still seems to reinitialize this object every time I refresh the page. 

I understand this is a pretty big feature request, so I'd be happy to have some workaround; some way that my state object doesn't get reinitialized every time I refresh. Thanks!

**Comment by freddyaboulton** [comment]
Hello @GJBoth !

Have you tried serializing the state you care about to a file (like json) or database like SQLite? 

That would persist through refreshes. You can use Blocks.load to load the state on page refresh.

If you’re expecting multiple concurrent users you’d need to make sure to serialize the state of each user separately .

**Comment by GJBoth** [comment]
Hi @freddyaboulton 
Thanks for the quick response and the suggestion. I've been toying with such an idea - basically write the state to file and have it reloaded at init... but wouldn't constantly writing these things to desk sink performance? (Although this is only for one user so it's a relatively simple set-up.) Is there not some other way to have the object persist?

**Comment by freddyaboulton** [comment]
If it's really only for one user, I think your first approach of using a python object in memory will work. May need to access it within your function with `global` though.

**Comment by abidlabs** [comment]
Agree with @freddyaboulton's suggestion. You can simply define a Python object outside of your function and then reference it inside the function. That object will be shared across all users, across all sessions. You can read more about that here: https://gradio.app/interface-state/#global-state

**Comment by GJBoth** [comment]
@freddyaboulton @abidlabs It doesn't work in my case - whenever I close and reopen the page, it resets. Basically my code looks like something like this:

```
state = State(number=0)

with gr.Blocks() as demo:
   number = gr.Number(value=state.number)..
   number.change(state.change, number, None) # state.change internally saves number

demo.queue()
demo.launch()
```

When I refresh the page or close and reopen, it always resets the value to the initial value of the class (but it definitely set it internally in state), not the value last given by the number input. That's slightly unexpected... any idea why? In the meantime I can do with pickling, but constantly saving isn't ideal...

**Comment by abidlabs** [comment]
Hi @GJBoth,

`gr.State()` is used for session state, where you *do* want the state to reset when the page is refreshed. For what you are describing, you should just use a regular Python variable, like this:

```py
state = 0

def update_state(num):
   state = num


with gr.Blocks() as demo:
   number = gr.Number(value=state.number)..
   number.change(update_state, number, None) # state.change internally saves number

demo.launch()
```

**Comment by GJBoth** [comment]
Sorry for the confusion - `State` isn't the `gradio.State`, just a python class containing the state. In any case, even with your example when I update the number and then refresh the page it resets to zero! Is that expected behaviour?

**Comment by abidlabs** [comment]
Ah interesting, you're right. There were two issues:

(1) I forgot the `global`
(2) By setting `gr.Number(value=state)`, we hardcode the default value of the `Number` component to the be initial value of the `state` variable. Instead, we can add an event that happens on page load that sets the value of the `Number` component to the be *current* value of `state`. 

Here's how the code looks:

```py
import gradio as gr

state = 0

def update_state(num):
    global state
    state = num


with gr.Blocks() as demo:
    number = gr.Number()
    number.change(update_state, number, None)    
    demo.load(lambda :state, None, number)
    
demo.launch()
```

Here, you can see it working on Spaces: https://huggingface.co/spaces/abidlabs/global-state-test

**Comment by abidlabs** [comment]
> Your comment about values being hardcoded made me think - why not just use a lambda function for the value, which should be called every time the app is initialized? This snippet works exactly as I'd expect:

Yes, that's even nicer! 

> Would it be a good idea to add this to the documentation? Or even, is this desired behaviour? It seems slightly inconsistent with lambda being called everytime the app is refreshed?

Given that this is pretty niche, I don't think we need to change the behavior, but I do think we should add the fact that you can pass functions in as the default values of components to the docs. I couldn't find it myself.

**Comment by Kilig947** [comment]
``> Thanks, it now works! I think I found an even nicer solution. Your comment about values being hardcoded made me think - why not just use a lambda function for the value, which should be called every time the app is initialized? This snippet works exactly as I'd expect:
> 
> ```
> import gradio as gr
> 
> state = 0
> 
> def update_state(num):
>     global state
>     state = num
> 
> 
> with gr.Blocks() as demo:
>     number = gr.Number(value=lambda: state)
>     number.change(update_state, number, None)    
> demo.launch()
> ```
> 
> Especially when having a lot of parameters this is nicer I think. Thanks a lot for the help! I didn't get this part from the documentation but it seems to me quite important:
> 
> > By setting gr.Number(value=state), we hardcode the default value of the Number component to the be initial value of the state variable.
> 
> Would it be a good idea to add this to the documentation? Or even, is this desired behaviour? It seems slightly inconsistent with lambda being called everytime the app is refreshed?

Why is my chabot conversation log not being passed on????
![image](https://github.com/gradio-app/gradio/assets/46100050/321d8f59-43da-45d8-9f2f-2280b92f9282)

`            self.demo.load(fn=func_box.refresh_load_data, inputs=[self.chatbot, self.history, self.pro_fp_state], outputs=[self.pro_func_prompt, self.pro_fp_state, self.chatbot,  self.history, ])
`

`def refresh_load_data(chat, history, prompt):
    is_all = toolbox.get_conf('prompt_list')[0]['key'][0]
    data = prompt_retrieval(is_all=[is_all])
    prompt.samples = data
    return prompt.update(samples=data, visible=True), prompt, chat, history`

**Comment by Kilig947** [comment]
> ``> Thanks, it now works! I think I found an even nicer solution. Your comment about values being hardcoded made me think - why not just use a lambda function for the value, which should be called every time the app is initialized? This snippet works exactly as I'd expect:
> 
> > ```
> > import gradio as gr
> > 
> > state = 0
> > 
> > def update_state(num):
> >     global state
> >     state = num
> > 
> > 
> > with gr.Blocks() as demo:
> >     number = gr.Number(value=lambda: state)
> >     number.change(update_state, number, None)    
> > demo.launch()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Especially when having a lot of parameters this is nicer I think. Thanks a lot for the help! I didn't get this part from the documentation but it seems to me quite important:
> > > By setting gr.Number(value=state), we hardcode the default value of the Number component to the be initial value of the state variable.
> > 
> > 
> > Would it be a good idea to add this to the documentation? Or even, is this desired behaviour? It seems slightly inconsistent with lambda being called everytime the app is refreshed?
> 
> I want to keep the previous conversation records every time the page is refreshed, but I passed self.chatbot and self.history components to this method according to self.demo.load(), the actual debug saw that it was indeed empty, is this method passed after all the data is refreshed?
> 
> ![image](https://user-images.githubusercontent.com/46100050/246619728-321d8f59-43da-45d8-9f2f-2280b92f9282.png)
> 
> ` self.demo.load(fn=func_box.refresh_load_data, inputs=[self.chatbot, self.history, self.pro_fp_state], outputs=[self.pro_func_prompt, self.pro_fp_state, self.chatbot, self.history, ])`
> 
> `def refresh_load_data(chat, history, prompt): is_all = toolbox.get_conf('prompt_list')[0]['key'][0] data = prompt_retrieval(is_all=[is_all]) prompt.samples = data return prompt.update(samples=data, visible=True), prompt, chat, history`


I checked the preprocess and postprocess parameters in the load() function and preprocess=False will process the component data as None, while postprocess=False still returns [] 😭😭😭😭😭.  @abidlabs 
`
            preprocess: Instance Method - If False, will not run preprocessing of component data before running 'fn' (e.g. leaving it as a base64 string if this method is called with the `Image` component).
            postprocess: Instance Method - If False, will not run postprocessing of component data before returning 'fn' output to the browser.
            every: Instance Method - Run this event 'every' number of seconds. Interpreted in seconds. Queue must be enabled.
        Example:
`

**Comment by drscotthawley** [comment]
@freddyaboulton @abidlabs : I'm late to this thread but for clarification on a similar question: What if we're not using HuggingFace Spaces?  Is there still something like `.load()` that we can use?  

The docs  say 
> Class method: loads a demo from a Hugging Face Spaces repo and creates it locally and returns a block instance. Warning: this method will be deprecated. Use the equivalent `gradio.load()` instead.
...but perhaps this dependence on Spaces has been removed?

**Comment by drscotthawley** [comment]
^^^ Oooo, @Kilig947's solution is working super for me too, even for multiple users across multiple browser types!  Curious about my question above but low priority now.
