### ISSUE TITLE
Altair example in docs broken

### ISSUE THREAD

**Issue by cakiki** [gradio-app/gradio#3175]
### Describe the bug

I don't know if this is related to this: https://github.com/gradio-app/gradio/issues/2892

Altair demo in the docs seems to be broken (When clicking on `Try Examples` here: https://gradio.app/docs/#plot). It puts me in a queue of 174 (Assuming this is the amount of times this was tried.) @osanseviero gets an error directly.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

e.g.: https://gradio.app/docs/#plot -> try examples -> altair -> heatmap

### Screenshot

![image](https://user-images.githubusercontent.com/3664563/218126249-50cbf4c1-b4da-4003-862c-b5bc54de186e.png)

### Logs

```shell
N/A
```

### System Info

```shell
Gradio docs
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment]
Thanks for filing @cakiki !

The version on the space is working properly after a factory reboot

![altair_plot_demo](https://user-images.githubusercontent.com/41651716/218135230-a9d9a76d-cbfa-437b-8843-e25750e45965.gif)

but the embedded demo on the website is not

![altair_plot_demo_website](https://user-images.githubusercontent.com/41651716/218135654-2eccb617-5deb-4d78-8d37-cb6546a89754.gif)

cc @aliabd

**Comment by freddyaboulton** [comment]
Adding to the weirdness, the plot does finish generating but the UI is still stuck displaying the status tracker for some reason

![altair_plot_demo](https://user-images.githubusercontent.com/41651716/218149395-f81c1e27-6289-4d33-9de7-cb44b04d93a0.gif)

**Comment by freddyaboulton** [comment]
Going to close this as this is just a special case of #3187 . Thanks for bringing this to our attention @cakiki !
