### ISSUE TITLE
Some embedded demos on the docs not appearing

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#3176]
### Describe the bug

Took a look through the docs page today and noticed some things that were not working as expected:

1. Gallery images are not loaded properly

![image](https://user-images.githubusercontent.com/41651716/218139364-98eecaed-dd10-4acd-b146-88a9e9bf93b2.png)

![image](https://user-images.githubusercontent.com/41651716/218139443-1102e630-7bfd-4422-978a-37345ff223e0.png)

2. Audio is not playable. Only for input though? 🤔 

![image](https://user-images.githubusercontent.com/41651716/218139815-98861e9d-1932-4c35-808b-1386100840bc.png)

3. Model3D is not viewable unless clicking on cached examples
![model_3d_docs](https://user-images.githubusercontent.com/41651716/218140376-4bb166c2-75f7-41aa-a0da-7d966519b8a0.gif)

4. Same thing for video as model3d
![video_docs](https://user-images.githubusercontent.com/41651716/218140979-e896898f-3ce9-4ab7-a148-dfe3a39bddaa.gif)

5. Titanic survival and chatbot_demo don't load
![image](https://user-images.githubusercontent.com/41651716/218141305-d6e08d87-fd29-43eb-9448-781bb868f35d.png)

![image](https://user-images.githubusercontent.com/41651716/218141809-4e804e18-806d-4d69-84a9-4f9d0ef12a8d.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

-

### Screenshot

-

### Logs

```shell
-
```

### System Info

```shell
Checked the main and 3.18.0 version of the docs
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
The file issue should be fixed in 1 - 4. Don't know what's going on with some demos not showing up though.

**Comment by aliabd** [comment]
All 5 of the issues you listed @freddyaboulton have been resolved on the website, so will close this issue.
