### ISSUE TITLE
Default input labels incorrect when Interface `fn` is a class method

### ISSUE THREAD

**Issue by haydenedelson** [gradio-app/gradio#3178]
### Describe the bug

Hey team, small bug:

When the `fn` parameter in `gr.Interface` is set to a class method, the default input labels include the `self` parameter. For example:

I want to demo an ML model. Here's what my demo script looks like:
```
class DemoModel():
  def __init__(self, args):
    self.model = Model(args)
  
  def get_prediction(self, image1, image2):
    return self.model.predict([image1, image2])


demo_model = DemoModel(args)
demo = gr.Interface(fn=demo_model.get_prediction,
                    inputs=[gr.Image(source='upload', mirror_webcam=False),
                            gr.Image(source='upload', mirror_webcam=False)],
                    outputs="label")

demo.launch()
```

Here's what the demo interface looks like:
<img width="1514" alt="Screen Shot 2023-02-10 at 10 08 13 AM" src="https://user-images.githubusercontent.com/59719221/218165573-7d1903fd-7cfe-46ba-8882-341c48db5e78.png">

So the default input labels shown here are `self` and `image1`. The demo/function still seems to be working correctly, so this is strictly a comment on the default labeling in the UI. I know we can overwrite these labels anyway, so this is not a big issue, but would you be able to fix it so that the default labels would be `image1` and `image2` in this case?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Here's just a simple working example to illustrate the issue:

```
import gradio as gr
import cv2
import numpy as np

class DemoModel():
    def __init__(self, size):
        self.size = size

    def compare(self, image1, image2):
        img1 = cv2.resize(image1, (self.size, self.size), interpolation=cv2.INTER_LINEAR)
        img2 = cv2.resize(image2, (self.size, self.size), interpolation=cv2.INTER_LINEAR)
        distance = np.linalg.norm(img1 - img2)
        return repr({"distance": distance})


demo_model = DemoModel(100)
demo = gr.Interface(fn=demo_model.compare,
                    inputs=[gr.Image(source='upload', mirror_webcam=False),
                            gr.Image(source='upload', mirror_webcam=False)],
                    outputs="label",
                    examples=[])

demo.launch()
```

### Logs

```shell
N/A
```

### System Info

```shell
Python version = 3.8.5
Gradio version = 3.17.1
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks for creating this issue @haydenedelson, we'll take a look!
