### ISSUE TITLE
Screenshot Button is not working

### ISSUE THREAD

**Issue by Adeel-Intizar** [gradio-app/gradio#318]
Hi,
I built the GAN UI with Gradio, but the Screenshot button is not working, neither in Colab nor in the external URL, but Flag button is working just fine, is this a bug ? can you help me with this ?
Thank you

**Comment by abidlabs** [comment]
Can confirm that I able to reproduce this issue. Basically, it looks like:
* the Screenshot button works locally
* but it doesn't do anything when you open the URL generated by `share=True`
(This is true across different interface types). For example, I tested an image classification network

**Comment by abidlabs** [comment]
Closing as we have just eliminated the screenshot button in the latest version of Gradio on `master`. We'll be releasing to pypi next week.
