### ISSUE TITLE
Performance of docs page is really slow

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3181]
### Describe the bug

Every time I try to go to https://www.gradio.app/docs it takes at least 30 seconds for the page to unfreeze just so I can look up some method signatures. I'd guess it's all the interactive examples on the page trying to load at once but 90% of the time I don't care about any of the examples and just want to verify an argument that can be passed to a gradio component. It's kinda stressful every time I realize I need to find out how to do something in gradio

And just to be sure my machine is top-spec, I have a Ryzen 8-core processor and a 3090

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Go to https://www.gradio.app/docs

### Logs

```shell
N/A
```

### System Info

```shell
Windows Server 2022, Google Chrome Version 108.0.5359.99
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Thanks @space-nuko ! We're planning on rewriting the entire website to avoid having to load all the demos at once on page loads.

**Comment by pngwn** [comment]
@space-nuko Is this still the case? We recently made some changes to gradio that significantly improved performance, could you test again and let us know if things have improved?

**Comment by space-nuko** [comment]
Yeah it's definitely better than it was before, still stutters a bit for ~3 seconds every time I scroll past an example. It would be nice if the examples loaded only if you clicked on them. But this is much better than before

**Comment by pngwn** [comment]
Making more improvements atm, so will keep this open to track. Thanks!

**Comment by abidlabs** [comment]
Should be a lot faster now, thanks to the Sveltekit migration! Thanks @aliabd and to @space-nuko for creating this issue in the first place
