### ISSUE TITLE
Limit choices for `gr.Dropdown` multiselect 

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#3184]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I would like to limit to a certain number of choices for the multiselect option

**Describe the solution you'd like**  
I would like to limit the user to choose only a fixed amount of options out of all, so say a `maximumChoices` parameter that can be set to a value and then users can only select up to that amount of options.

**Comment by apolinario** [comment]
An odd additional request: 
If we implement something like a `maximumChoices` parameter, please have it start with `1`. It sounds weird and more logical that if `multiselect` == `True`, a `maximumChoices` parameter should start `>=2`, but this would be a way to allow for users to use the searchable UI of `multiselect` even if they only need 1 option

An alternative is a `searchable` param to be set to `True` even if `multiselect` is `False`

**Comment by abidlabs** [comment]
Makes sense to me! cc @dawoodkhan82

**Comment by freddyaboulton** [comment]
When we implement this, I think we should just make the "regular" Dropdown an alias for multiselect with maximum_choices=1 and that way all dropdowns will be searchable.

**Comment by abidlabs** [comment]
I like that (and agree that the regular `Dropdown` should be searchable) but the only issue might be that the Dropdown passes in the selected value as a string, whereas if `multiselect=True`, the selected values are always passed in as a list

**Comment by dawoodkhan82** [comment]
Makes sense. I'm sure I can make it so that the regular dropdown uses the `Multiselect` UI but still returns a string, so it won't be a breaking change.
