### ISSUE TITLE
🚨 timeout problem

### ISSUE THREAD

**Issue by camenduru** [gradio-app/gradio#3185]
### Describe the bug

working
```py 
import gradio as gr
def fun():
    start_time = time.time()
    while time.time() - start_time < 59:
        pass
    msg = "This is sample markdown message"
    return msg
with gr.Blocks() as demo:
    b1 =gr.Button()
    text_out = gr.Textbox()
    b1.click(fun, [], [text_out])
demo.launch(debug=True, share=True, inline=False)
```
not working 

```py 
import gradio as gr
def fun():
    start_time = time.time()
    while time.time() - start_time < 61:
        pass
    msg = "This is sample markdown message"
    return msg
with gr.Blocks() as demo:
    b1 =gr.Button()
    text_out = gr.Textbox()
    b1.click(fun, [], [text_out])
demo.launch(debug=True, share=True, inline=False)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

colab

### Logs

```shell
no log
```

### System Info

```shell
3.18.0
```

### Severity

blocking all usage of gradio

**Comment by camenduru** [comment]
`inline=True` working maybe you should send more wake-up signal over websocket idk how 60 seconds default timeout

**Comment by camenduru** [comment]
`inline=True` working maybe we should send more wake-up signal over websocket idk how maybe 60 seconds default timeout for gradio.live

**Comment by camenduru** [comment]
it is working 🥳 thanks @abidlabs ❤

**Comment by FurkanGozukara** [comment]
> demo.queue().launch(debug=True, share=True, inline=False)

when i enable queue i almost get immediately time out on runpod

when not enabled it works but this time i get timeout when it takes longer than 1 minute?
