### ISSUE TITLE
Question and Answering

### ISSUE THREAD

**Issue by jocelynbaduria** [gradio-app/gradio#319]
Hi 
I wanted to use your function for my homework but I have problem implementing it to colab notebook. Im getting error to show the answer. Also the Answer Textbox is not properly showing.This is the screenshot of the result. Kindly help. Thank you.

![Screen Shot 2021-10-27 at 3 27 04 PM](https://user-images.githubusercontent.com/62075076/139156509-9ba6fe72-d37b-4cd3-875d-2f58187486b4.png)

gradio demo sample
`import gradio as gr
from bert import QA
model = QA('bert-large-uncased-whole-word-masking-finetuned-squad')
def qa_func(context, question):
    return model.predict(context, question)["answer"]
gr.Interface(qa_func,
    [
        gr.inputs.Textbox(lines=7, label="Context"),
        gr.inputs.Textbox(label="Question"),
    ],
    gr.outputs.Textbox(label="Answer")).launch()`

My sample function for implementation
`import` gradio as gr
# from bert import QA
from transformers import BertTokenizer
from transformers import BertForQuestionAnswering
tokenizer = BertTokenizer.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')
model = BertForQuestionAnswering.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')
# model = QA('bert-large-uncased-whole-word-masking-finetuned-squad')
def answer_question(bert_abstract, answer_text):
    return model.predict(bert_abstract, question)["answer_text"]
gr.Interface(answer_question,
    [
        gr.inputs.Textbox(lines=7, label="Context",),
        gr.inputs.Textbox(label="Question"),
    ],
    gr.outputs.Textbox(label="Answer")).launch()`

**Comment by abidlabs** [comment]
The problem here seems to be related to the underlying `BertForQuestionAnswering` model, not `gradio`. The model doesn't have a `predict()` function. I would look into the library and see what the right method to call is.

**Comment by jocelynbaduria** [comment]
> The problem here seems to be related to the underlying `BertForQuestionAnswering` model, not `gradio`. The model doesn't have a `predict()` function. I would look into the library and see what the right method to call is.

@abidlabs Thank you for the clarifications.
