### ISSUE TITLE
"Remove all" action on Dropdown with multipleselect does not call any event

### ISSUE THREAD

**Issue by scado1** [gradio-app/gradio#3192]
### Describe the bug

I am using blocks for building app, and have a dropdown menu with multiselect and have an invisible button.

Later,  change method on dropdown `selected_result` is called, checking if any value was selected and if it is true button's visibility is updated to `True`

While removing options one at a time it works fine: if menu is empty button became invisible as it is supposed to.
However,<b> if I am clicking on "remove all" button stays visible and change event is not triggered.</b>

Tried with and without queueing. 

In browser console "remove all" action does not create a web socket.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr


def check_selected_options(selected_elements):
    return gr.Button.update(visible=bool(selected_elements))


with gr.Blocks() as demo:
    gr.Markdown("# CV Analysis demo")
    with gr.Accordion("User's evaluation"):
        with gr.Row():
            selected_result = gr.Dropdown(
                ["OK", "weird/unknown symbols", "shifted dates", "shifted text fragments", "Other problems"],
                multiselect=True,
                label="OCR results scoring buttons",
            )
            comment = (gr.Textbox(lines=6, placeholder="Place for additional comments (Optional)..."),)

    btn_save_evaluation = gr.Button(value="Save score to DB", variant="primary", visible=False)

    selected_result.change(check_selected_options, selected_result, btn_save_evaluation)

if __name__ == "__main__":
    gr.close_all()
    demo.queue()
    demo.launch(server_name="0.0.0.0", server_port=8000, debug=True)
```

### Screenshot

[Screencast from 14-02-23 15:45:22.webm](https://user-images.githubusercontent.com/46383438/218771645-c0c63fdb-66e8-428a-819a-19d36b31cdc3.webm)

### Logs

```shell
I do not have logs
```

### System Info

```shell
gradio: 3.16.2
os: Fedora Linux 36
Browser: checked on Brave, Chrome and Firefox
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Thanks @scado1 !

I think it makes sense for the change event to be triggered with the clear all button. Should be a quick fix.

**Comment by scado1** [comment]
Great, thanks! :D
