### ISSUE TITLE
Weird interaction between Accordion and Tab

### ISSUE THREAD

**Issue by wfng92** [gradio-app/gradio#3198]
### Describe the bug

Given a `gr.Accordion` component with multiple `gr.Tab` components, the content of the contained `gr.Tab` components is not showing when you close and open back the `gr.Accordion` component (only applicable after clicking on any Tab component other than the first one). As a result, users need to manually click the `gr.Tab` component again to see the underlying content. This affects user experience.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Given the following code:

```python
import gradio as gr

with gr.Blocks() as demo:
    with gr.Accordion('Accordion', open=False):
        with gr.Tab('Tab1'):
            text1 = gr.Textbox('text1')
        with gr.Tab('Tab2'):
            text2 = gr.Textbox('text2')
        with gr.Tab('Tab3'):
            text3 = gr.Textbox('text3')

demo.launch()
```

Reproduction steps:
1. Click on the second or third Tab
2. Close the accordion
3. Open the accordion (notice that there are no content showing)

Desired interaction:
1. Click on the third tab
2. Close the accordion
3. Open the accordion (UI will show the content of the third tab)

### Screenshot

![image](https://user-images.githubusercontent.com/43742196/218932661-8d435990-4710-427a-b1db-9f842e9732c3.png)

No content is showing on opening of a closed `gr.Accordion`. By right, should show the content of the last selected `gr.Tab`.

### Logs

```shell
N/A
```

### System Info

```shell
Gradio version: '3.18.0'
Browser: Firefox and Chrome
```

### Severity

annoying

**Comment by abidlabs** [comment]
Can confirm the weird behavior, we'll look into it @wfng92!

**Comment by space-nuko** [comment]
Still an issue as of 3.23.0, some users of webui have experienced it in for example https://github.com/Mikubill/sd-webui-controlnet

**Comment by anapnoe** [comment]
also if I have inside tab a list of some items and I scroll to the middle if re-trigger the tab it will start from top not from the last position ideally  `scrollTop` property should also be restored
