### ISSUE TITLE
Support of *.tiff files

### ISSUE THREAD

**Issue by eragon12391** [gradio-app/gradio#32]
In the Image interface in the Input, can you provide support for 'tiff files'

**Comment by aliabd** [comment]
Thanks for opening an issue @eragon12391. 

@aliabid94 can you take a look at this?

**Comment by abidlabs** [comment]
@eragon12391 can you tell us a little more about your use case? It will help us design the UI if we have a sense of what kind of models you are interested in building UIs for

**Comment by tmabraham** [comment]
@abidlabs I don't need anything special in terms of UI, just need to be able to upload *.tif files. Does the TOAST UI image editor you guys have not support *.tif files?

**Comment by rcox771** [comment]
it looks like scikit-image is already a requirement and scikit-image does support loading of tiff files, but tiff files are often used as a special case of image file that has support for storing stacked images. I've most often run into [tiffs doing satellite imagery work with rasters](https://automating-gis-processes.github.io/CSC18/lessons/L6/reading), where the data can have multiple channels, but also a dimension for each band/sensor (vegetation spectra, emissions), and of course your normal WxH. If you look at [scikit-image's current imread function](https://scikit-image.org/docs/0.15.x/api/skimage.external.tifffile.html#imread), you'll see that it expects a "key" for the image in the stack you want. Some of the examples they give have images that are

- (5, 3, 301, 219) == (band, channel, height, width) == BCHW
- (2, 3, 4, 301, 219) or NBCHW I'm guessing?

Point is - tiffs are weird exceptions that probably need some thinking to integrate and display properly. I think what @abidlabs was getting at was "if we load in tiff files that have more than one image stored, how do we display those while helping with your use case?"

I assume there probably won't be a one-size-fits-all approach for displaying tiff files short of assuming the best case as a single-band-single-image tiff file with channels being one of the standard (null or 1 for grayscale, 3 for rgb/bgr/hsv etc, or 4 for rgba) and the regular HxW.

The alternative would require some design choices in laying out all the other images and bands in a tilegrid, or some fancy js to stack and toggle between them probably.
![image](https://user-images.githubusercontent.com/13604961/89871579-dbe30900-db74-11ea-8148-8c319a113e85.png)

I hope that helps @tmabraham @abidlabs @aliabid94

**Comment by dawoodkhan82** [comment]
@eragon12391 This is a feature we will add support. I'll update this issue when we do.

**Comment by luisoala** [comment]
hi @dawoodkhan82 thanks for the effort. i have a similar issues. is there any update or workaround for .tif/.tiff files?

**Comment by MichaelSNelson** [comment]
Bumping this as I am interested in using .tif files from research. RGB would be a start, as multichannel would likely be challenging :)

**Comment by abidlabs** [comment]
Reopening this issue. Perhaps we can tackle as part of #466. cc @pngwn

**Comment by aghand0ur** [comment]
Hello @pngwn @abidlabs 
I am using gradio for an earth observation application:
http://geoai.cnrs.edu.lb/urbanmodels/

Users are trying to upload tiff images with no luck.
It would be extremely helpful to provide support for this format (widely used in the remote sensing community) as part of #466.

**Comment by abidlabs** [comment]
Probably not in core, I think it's a good example of a community component, e.g. along the lines of #2031

**Comment by aghand0ur** [comment]
As a quick workaround, would it be possible for the time being to upload tiff files and pass it to the model without displaying it?
The user needs to download the output and display it locally or might use some tiff browser plugins such as:
https://github.com/my-codeworks/tiff-viewer-extension

**Comment by pngwn** [comment]
I'd expect that to already work. Will test and get back to you.

**Comment by aghand0ur** [comment]
@abidlabs right, but it would be cumbersome to let the users choose between using the `gr.Image`  or the  `gr.File` components. I expect it might create some confusions for users.
This is why I suggested the following:

> As a quick workaround, would it be possible for the time being to upload tiff files and pass it to the model without displaying it? The user needs to download the output and display it locally or might use some tiff browser plugins such as: https://github.com/my-codeworks/tiff-viewer-extension

**Comment by aghand0ur** [comment]
> I'd expect that to already work. Will test and get back to you.

any update from your side @pngwn ?

**Comment by aghand0ur** [comment]
> I'd expect that to already work. Will test and get back to you.

@pngwn @aliabid94 @abidlabs did you get the chance to test this issue?

**Comment by jaycecd** [comment]
> I'd expect that to already work. Will test and get back to you.我希望这已经起作用了。将进行测试并回复您。

Hi, any progress on this issue?

**Comment by a-parida12** [comment]
Is there a way I can use the output of a cutom image converter that can be used to generate the preview for the tiff or any other image format as part of the gr.Image input box?

**Comment by henryruhs** [comment]
@abidlabs In my opinion this issue could be closed as `tiff` is not a web format.

How to implement support in case you really need that:

1. Upload via `gradio.File`
1. Transform to JPG
1. Show in `gradio.Image`
1. Perform your operations on the source of `gradio.File`
1. Update the JPG and refresh `gradio.Image`

**Comment by abidlabs** [comment]
Hi @henryruhs that's a good workaround. I'm leaving this open because we are about to release custom components, and the logic you described could be encapsulated in a custom component for simplicity

**Comment by jaycecd** [comment]
> @abidlabs In my opinion this issue could be closed as `tiff` is not a web format.
> 
> How to implement support in case you really need that:
> 
> 1. Upload via `gradio.File`
> 2. Transform to JPG
> 3. Show in `gradio.Image`
> 4. Perform your operations on the source of `gradio.File`
> 5. Update the JPG and refresh `gradio.Image`



Nice solution, but this approach doesn't record the user actions with the image, such as drawing masks on the image.
@henryruhs

**Comment by abidlabs** [comment]
Hi! We've now made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

* A "Rich Textbox" that [allows you to write bold/italics/colored text](https://huggingface.co/spaces/abidlabs/gradio_rich_textbox)
* A "Folium Map Viewer" component that [allows you to use interactive maps](https://huggingface.co/spaces/freddyaboulton/gradio_folium)

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. **In particular, its very fast if you want to build off an existing component**. We've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help if you'd like to put together a custom component for this issue

**Comment by jaycecd** [comment]
Has anyone implemented a custom component?

**Comment by freddyaboulton** [comment]
Not yet as far as I'm aware! Please go ahead and let us know if you run into issues @jaycecd

**Comment by Atif-Anwer** [comment]
I was able to make a .tif preview interface for Gradio using rasterio and PIL. A MWE is given below for anyone who is stuck in a similar issue:

```
import gradio as gr
import numpy as np
import rasterio
from PIL import Image


def get_file_content(file):
	with rasterio.open(file) as src:
		# Read the image data
		image_data = src.read()
		image = Image.fromarray((image_data[0] * 255).astype(np.uint8))
	return (gr.Image(value=image, type="pil"))


with gr.Blocks() as demo:
	gr.Markdown("# Preview Images:")
	with gr.Group(visible=True):
		with gr.Row(visible=True):
			preview = gr.FileExplorer( scale      = 1,
						  glob        = "*.tif",
						  value       = ["./"],
						  file_count  = "single",
						  root_dir    = "./",
						  elem_id     = "file",
						  every= 1,
						  interactive=True
						)

			image = gr.Image(type="pil")
	preview.change(get_file_content, preview, image)

demo.launch(allowed_paths=["./"])
```

**Comment by NiklasvonM** [comment]
> Has anyone implemented a custom component?

I recently created [gradio-tiff](https://github.com/NiklasvonM/Gradio-TIFF/).

**Comment by Atif-Anwer** [comment]
> > Has anyone implemented a custom component?
> 
> I recently created [gradio-tiff](https://github.com/NiklasvonM/Gradio-TIFF/).

Nice! But it would be great if you can actually do a PR on the Gradio component instead of maintaining a separate plugin? From my experience, that causes issues once its not being actively maintained and Gradio pushes out feature-breaking updates rendering the custom plugin useless :( (Has happened to me before).

**Comment by NiklasvonM** [comment]
> > > Has anyone implemented a custom component?
> > 
> > 
> > I recently created [gradio-tiff](https://github.com/NiklasvonM/Gradio-TIFF/).
> 
> Nice! But it would be great if you can actually do a PR on the Gradio component instead of maintaining a separate plugin? From my experience, that causes issues once its not being actively maintained and Gradio pushes out feature-breaking updates rendering the custom plugin useless :( (Has happened to me before).

Thanks for the suggestion. However, @abidlabs stated above that they do not plan to include TIFF support in the core library. That is why I built this as a custom component, following their recommendation. I'll stick to this solution as long as the stance of the maintainers doesn't change.
