### ISSUE TITLE
Add user feedback when flagging is done 

### ISSUE THREAD

**Issue by merveenoyan** [gradio-app/gradio#3201]
I think with loading Interfaces with flagging options allows people to set labelling for active learning loops and is very useful.
It would be nice to give user feedback saying "Your flag is logged!" after user clicks flag by default, as of now, nothing happens and people feel like their inputs aren't logged.
See here: https://huggingface.co/spaces/deprem-ml/ner-active-learning

**Comment by freddyaboulton** [comment]
How/where should the notification be displayed? I'm thinking it looks like the `gr.Error` but it's green and has a friendly message, like this:

![image](https://user-images.githubusercontent.com/41651716/219106243-fd7a4503-51a9-4a78-bd7b-ecb8cd3473b7.png)
 
Maybe this can be a general component that can be leveraged with gr.Blocks as well.

**Comment by merveenoyan** [comment]
@freddyaboulton It could either change color of the button or can be a progress bar on the button or output if it works.

**Comment by dvsrepo** [comment]
Hi, I'm Dani from Argilla, congratulations for such a great tool. This enhancement is highly relevant for us too. I was thinking also about not allowing users to click twice on the same button, but I understand the logic will get more involved, and we could maybe get around by keeping some state inside the ArgillaCallback not to log multiple times the same feedback 

We're going to be using more and more Gradio Apps for collecting human feedback with Argilla. It's a great integration for both public crowd-sourcing efforts like @merveenoyan's amazing project and less open use cases where one can use Gradio+Argilla to iterate on data and models.

Let us know if we can help!

**Comment by abidlabs** [comment]
Hi all, and welcome @dvsrepo! 

What about the Flag Button becoming disabled while the function is running and then becoming enabled again when the flagging is complete? We could make that the default behavior in a `gr.Interface`, as that's the UI I think most users would expect?

**Comment by dvsrepo** [comment]
Sounds great to me! Would the user be notified that the flag info was successfully submitted/saved too, as discussed above?

**Comment by abidlabs** [comment]
I wonder if that is necessary? It feels like a more complex design whereas I think the button becoming disabled and then enabled might be sufficient to provide the user with visual feedback that the flagging is complete

**Comment by dvsrepo** [comment]
thanks @abidlabs ! Yes, I agree that it might be sufficient visual feedback with the button becoming disabled. Thanks so much! Let me know if I can help to test once you plan to include this! 🙌

**Comment by abidlabs** [comment]
@merveenoyan @dvsrepo if you have any feedback about the proposed solution in #3289, please let us know in the PR!

**Comment by dvsrepo** [comment]
Apologies I completely missed this!! Thanks so much for tacking it
