### ISSUE TITLE
Gradio hangs when submitting relatively long videos (~10 seconds) from webcam.

### ISSUE THREAD

**Issue by Anwarvic** [gradio-app/gradio#3208]
### Describe the bug

Hey team!

At the current moment, I'm trying to show-case my DeepLearning model which works on video input. And i noticed that whenever I record a relatively long video (around 10 seconds) and press "submit", there is a higher probability that Gradio will get stuck and I don't get the output video. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

iface = gr.Interface(
    fn=lambda x: x,
    inputs=[
        gr.components.Video(
            source="webcam", include_audio=True, mirror_webcam=False
        ),
    ],
    outputs=[
        gr.components.Video(
            source="upload", include_audio=True
        )
    ],
    allow_flagging="never",
    
)
iface.launch(debug=True, show_error=True)
```

Record a relatively-long video (~10 seconds) and press "submit"... you might try this a few times.

### Screenshot

The following is a screenshot of me recording a 16-seconds video and never getting any response back.

![image](https://user-images.githubusercontent.com/15960959/219195341-8b7419f4-880b-467d-85aa-810bd3d08938.png)

### Logs

```shell
-
```

### System Info

- I'm using `Gradio==3.17.0`.
- Issue has nothing to do with Operating System, it occurs also on GoogleColab.
- I tracked this issue down till I get to this line [starlette/requests.py#L221](https://github.com/encode/starlette/blob/master/starlette/requests.py#L221). This is where the response gets stuck !

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Thanks @Anwarvic for flagging this. @aliabid94 I think a similar approach to #3191 should fix this as well

**Comment by Anwarvic** [comment]
Thanks @abidlabs for the amazing support!!

It seems that this issue is similar to #3038 . The issue was resolved once I changed `iface.launch()` to `iface.queue().launch()`. I would really appreciate it if you would tell me why 😄. 

I'm gonna close this issue for now. Thanks!

**Comment by abidlabs** [comment]
The reason is likely that the total inference time with the longer webcam videos > 60 seconds, after which regular http requests time out. That's why we you end up needing to use websockets via `queue()` instead, as described here: https://gradio.app/key-features/#queuing
