### ISSUE TITLE
Limit the duration of the recorded video

### ISSUE THREAD

**Issue by Anwarvic** [gradio-app/gradio#3213]
- [x] I have searched to see if a similar issue already exists.

## Problem
Right now, I'm building an application where the user records a video and pass the video to my model. The preprocessing pipeline for my model increases exponentially. The maximum duration of the recorded video is x seconds. So, I would love to limit the record duration.

## Suggested Solution
I think there should be an argument called `max_duration` at the `gradio.componnents.Video` class signature where the develop can set the maximum duration for recording. And on the frontend side, you set the maximum Once this duration is met, the recording should stop automatically.

A log message saying "You have exceeded the maximum time for recording" is a plus.

**Comment by abidlabs** [comment]
Hi @Anwarvic this is a good suggestion. We do have an existing issue for it here: #428, so I'll close this one. Feel free to chime in on that issue, thanks!
