### ISSUE TITLE
Publish CDN assets on PR commits

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#3215]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**
  
It would be nice if we published the CDN assets on PR commits so that we can publicly test embedding demos on PRs. 

**Describe the solution you'd like**  
modify the publish to hub gh action to upload the CDN assets as well. To a different s3 bucket than we use for production.
Would also be cool to comment on the PR with the url of a publicly accessible html file that has some demos loaded. 

**Additional context**

**Comment by pngwn** [comment]
@hannahblair took care of this!
