### ISSUE TITLE
several demos on home page fail

### ISSUE THREAD

**Issue by discdiver** [gradio-app/gradio#323]
The image segmentation and question answering demos on the home page error with no helpful error message. See attached screenshot.

<img width="1009" alt="Screen Shot 2021-10-29 at 2 09 53 PM" src="https://user-images.githubusercontent.com/7703961/139483231-fc6d7f50-79f8-4506-993d-07efcc693544.png">

**Comment by abidlabs** [comment]
Thanks for catching this @discdiver -- @aliabid94 is actually rewriting the entire website and so these should be fixed as part of that process.
