### ISSUE TITLE
Ensure self-hosted gradio apps can be embedded

### ISSUE THREAD

**Issue by lvelvee** [gradio-app/gradio#3232]
### Describe the bug

ditto

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
<gradio-app src="http://127.0.0.1:7680/app1/"></gradio-app>
```

```
WebSocket connection to 'ws://127.0.0.1:7680/static/index.htmlqueue/join' failed: 
```

### Logs

```shell
ditto
```

### System Info

```shell
...
```

### Severity

annoying

**Comment by abidlabs** [comment]
This should be solved in `gradio==3.20.1` ([see PR for more details](https://github.com/gradio-app/gradio/pull/3367)). Closing now, thanks @lvelvee
