### ISSUE TITLE
UserWarning: Currently, only the 'default' theme is supported.

### ISSUE THREAD

**Issue by cwfparsonson** [gradio-app/gradio#3240]
### Describe the bug

In examples online I can see that people are using different themes with `gradio`. However, when I try this (and also in the documentation), I get the warning `UserWarning: Currently, only the 'default' theme is supported.`.

Is there some way that people are getting passed this `UserWarning` so that they can use different `gradio` themes?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Set `theme=darkdefault` when launching.

### Logs

```shell
UserWarning: Currently, only the 'default' theme is supported.
```

### System Info

```shell
`gradio==3.18.0`
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @cwfparsonson we deprecated theming as part of the 3.0 launch, but are going to bring it back soon. You can follow along this issue to be notified when we release! https://github.com/gradio-app/gradio/issues/2354
