### ISSUE TITLE
UI crashes in `gr.Image` with `tool="color-sketch"` and a pre-loaded image

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#3248]
### Describe the bug

Running the following code
```py
#Create a black image
img = Image.new("RGB", (512, 512), (0, 0, 0))
img.save("image.png", "PNG")
#Pre-load the black image in the component
gr.Image(value="image.png", interactive=True, tool="color-sketch")
```
Crashes the UI
<img width="635" alt="image" src="https://user-images.githubusercontent.com/788417/220176049-977ac494-1587-41a8-aafb-b2a961131925.png">

### Reproduction

Here's a colab with an example: https://colab.research.google.com/drive/1Gp5pp51P14B0tM331dS7476-Oqe-Bi04

### System Info

```shell
3.19.0
```

### Severity

serious, but I can work around it

**Comment by apolinario** [comment]
The UI equally crashes if I do something like: 
```py
def update_image():
  return gr.update(value="image.png")

image = gr.Image(interactive=True, tool="color-sketch")
# ... 
demo.load(update_image, inputs=[], outputs=image)
```

And given that the `source="canvas"` can only initialize with a white canvas, I'm currently failing to see any way to initialise a `color-sketch` with a black image to be drawn on top

**Comment by pngwn** [comment]
This is due to a resize loop, the canvas gets too big and eventually crashes. Surprised it isn't happening when uploading an image though.
