### ISSUE TITLE
custom interface return

### ISSUE THREAD

**Issue by FanYe14** [gradio-app/gradio#3251]
- [ yes] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
i`d like custom interface return data

**Describe the solution you'd like**  
I want to use both the page and API functions of gradio. I need to modify the API interface return data format, but after I modify it, the data of the page cannot be displayed. At the same time, it is also a problem to transfer the data of the user-defined interface to the return interface
**Additional context**  
![return_data](https://user-images.githubusercontent.com/54200208/220239556-0336ce57-4d74-4780-847d-38fb41e18a38.png)
![url](https://user-images.githubusercontent.com/54200208/220239561-b44089af-fa8a-4725-9341-fd68ec20cac5.png)
![function](https://user-images.githubusercontent.com/54200208/220239815-e9563bc9-c113-4995-bd10-8c9f0026f4e4.png)

**Comment by abidlabs** [comment]
Hi @FanYe14 thanks for creating this issue, but we need a lot more information in order to reproduce and potentially address this bug. When you say the following, what do you mean exactly? Can you please provide a full, minimal code example that we can use to reproduce the issue? 

> I need to modify the API interface return data format, but after I modify it, the data of the page cannot be displayed. At the same time, it is also a problem to transfer the data of the user-defined interface to the return interface

**Comment by FanYe14** [comment]
> Hi @FanYe14 thanks for creating this issue, but we need a lot more information in order to reproduce and potentially address this bug. When you say the following, what do you mean exactly? Can you please provide a full, minimal code example that we can use to reproduce the issue?
> 
> > I need to modify the API interface return data format, but after I modify it, the data of the page cannot be displayed. At the same time, it is also a problem to transfer the data of the user-defined interface to the return interface
The data format returned by the interface is not what I want, so I want to customize the data returned by the interface.
In file blocks.py function: process_api, p1 & p2
![code1](https://user-images.githubusercontent.com/54200208/220331359-be0c5a53-b0ec-49ea-9c92-01a72daea4aa.png)
![code2](https://user-images.githubusercontent.com/54200208/220331366-39d093af-c9e1-4626-826d-f4358e37e8bc.png)
But the output has no data
![code3](https://user-images.githubusercontent.com/54200208/220331710-53006bb8-532a-40c8-b11c-9df993e25a1b.png)
I read a lot of related source code. I don't know how to make corresponding changes, so I want to ask for help
I see a lot of input and output data processing, but I feel I have nowhere to start

**Comment by abidlabs** [comment]
> need to modify the API interface return data format

Why do you need to modify the API interface return format? It sounds like you're modifying the library locally but we can't necessarily guarantee this would work at all.

**Comment by FanYe14** [comment]
> > need to modify the API interface return data format
> 
> Why do you need to modify the API interface return format? It sounds like you're modifying the library locally but we can't necessarily guarantee this would work at all.
![fucntion2](https://user-images.githubusercontent.com/54200208/220498715-1ab0b8c4-bf01-4689-8e3e-8044486e7aef.png)

We want to use both interface and interface functions at the same time, so the data format returned by the interface wants to use the format we need. The interface and API generated by using gradio. Interface() use the same interface: routes.predict(), so our current thinking is not appropriate. I should describe our needs clearly. Can you provide other ideas?

**Comment by abidlabs** [comment]
Hi @FanYe14 I'm sorry I really don't understand the issue that you are describing. Instead of screenshots, can you provide me with a minimal working code example that I can test? Otherwise, I don't think we can reproduce.

**Comment by abidlabs** [comment]
Closing for lack of repro
