### ISSUE TITLE
Ensure self-hosted gradio apps can be embedded via custom element

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#3253]
### Describe the bug

Self-hosted gradio apps cannot be embedded using the web component. they should be embeddable the same as spaces.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

todo

### Screenshot

todo

### Logs

```shell
-
```

### System Info

```shell
-
```

### Severity

annoying

**Comment by pngwn** [comment]
Ah interesting

**Comment by abidlabs** [comment]
Closing this in favor of the user-reported #3232
