### ISSUE TITLE
hyperlinks in output

### ISSUE THREAD

**Issue by amirtha17** [gradio-app/gradio#3255]
is there any method in gradio where we can convert a dataframe's column to hyperlink, where dataframe is the gradio output

or when we convert a dataframe to to_html as html object, how to display that html object table as output in gradio, with the link

**Comment by abidlabs** [comment]
Hi @amirtha17, thanks for creating the issue but for general questions, please use [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or our [Discord](https://t.co/JKepTfXraQ).
