### ISSUE TITLE
Be able to access current username from application

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#3259]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
When using gradio's authentication, it would be awesome if I could know which user is logged in to my app to tailor my app's behavior to that user.

Examples:
- Displaying greeting messages
- Creating an admin panel for a gradio app

**Describe the solution you'd like**  
Maybe this could be exposed in `gr.Request` ?

**Additional context**  

Discord discussion here: https://discord.com/channels/879548962464493619/1077391349617262713/1077391349617262713

**Comment by abidlabs** [comment]
Do the fastapi request headers contain the logged in username? Unless I'm mistaken, they don't have this info @lvelvee

**Comment by KataiKi** [comment]
It doesn't. It keeps the access-token, but not the username used during authentication.

**Comment by abidlabs** [comment]
I agree with @freddyaboulton we can add it as a separate field to the `gr.Request` headers

**Comment by KataiKi** [comment]
If the username is in Headers, would that still be accessible while loading the UI immediately after logging in?  If the username is made to be part of UI, for example, it wouldn't be useful to wait until the user hits Submit before we can read headers.

**Comment by abidlabs** [comment]
Interesting, good point @KataiKi. Can you elaborate on your use case a bit more -- how are you planning on using the username if it's before the submit button?

**Comment by KataiKi** [comment]
The simplest case would just be to have the name displayed somewhere on the UI, like on the top bar somewhere. If I want to load a profile based on the user (profile picture, email, etc), that would be important as well.  If I wanted to display that user's previous settings, I would need to know which user I'm talking to when the user logs in but before they make any submissions.

**Comment by freddyaboulton** [comment]
> If the username is in Headers, would that still be accessible while loading the UI immediately after logging in?

@KataiKi Yes, I think so, you can just pass the request to the `load` event.

```python
import gradio as gr

def create_greeting(request: gr.Request):
    return gr.Markdown.update(value=f"Thanks for connecting from: {request.client}")

with gr.Blocks() as demo:
    user_ip = gr.Markdown(value="Not logged in")

    demo.load(create_greeting, inputs=None, outputs=user_ip)

demo.launch(auth=("admin", "admin"))
```

**Comment by inewlife** [comment]
How to get user info in js function

**Comment by freddyaboulton** [comment]
> It does not use Gradio's authentication so not sure how to do that
You would have to use the built-in gradio authentication or the `LoginButton`

> How to get user info in js function

I think you can store the username in an invisble textbox component and then pass the textbox component to the js function.
