### ISSUE TITLE
Better DX when developing Gradio locally

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#3264]
It is currently really annoying to develop Gradio locally. We have all kinds of different commands you need to run just to see a demo and writing some custom code to test something is annoying, you have to create a new demo or use an existing one (and if you are me, you just forget to change the file back and end up committing it).

Would be good to make this better somehow. Have some, ideas will test.

**Comment by pngwn** [comment]
For myself when i come to this:

- https://github.com/gradio-app/gradio/issues/2686
- https://github.com/gradio-app/gradio/issues/3163#issuecomment-1433757381
- https://github.com/gradio-app/gradio/issues/3204#issuecomment-1436120158

**Comment by abidlabs** [comment]
Sounds like this is complete? Will close but feel free to reopen if I'm mistaken @pngwn
