### ISSUE TITLE
[frontend] Refactor components

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#3268]
Components in the frontend are a bit confusing right now which makes component loading + adding new components tricky: 

- we have two of everything and they are inconsistent. 
- some contain the block wrapper, some don't.
- some have their own statustracker/ loader, some don't.
- probably more
- component loading requires quite a bit of work
- props/event APIs are inconsistent

needs addressing.

Has implications for custom components #1432 

**The work**

Going to break this into a few pieces:

- [x] #3360
- [x] #3361
- [x] lazy load component variants (interactive, static, preview) this might make more sense as part of #3261

**Comment by abidlabs** [comment]
All the items are done here I believe so closing
