### ISSUE TITLE
Video example upload fails

### ISSUE THREAD

**Issue by jaekookang** [gradio-app/gradio#327]
Hi, I'm playing with Gradio to deploy my custom applications and found this framework really easy and useful.

I just encountered an issue about making video files as examples. I was replicating a CLIP-based video text query search following this: [https://twitter.com/ak92501/status/1421246864649773058?s=20](https://twitter.com/ak92501/status/1421246864649773058?s=20). 

I made video files (mp4) as examples that exist in the server, but I found that it is not loaded properly when I click on the example on the browser. It shows 404 error instead.

Here is the part of the code:
<img width="741" alt="code" src="https://user-images.githubusercontent.com/18749927/139605534-77c1288e-71e0-4d88-9a5b-513aa914d2dd.png">

Here is the HTML page:
![app](https://user-images.githubusercontent.com/18749927/139605538-af07d651-d3b5-4250-88f8-f15664912081.png)

Error message:
![err](https://user-images.githubusercontent.com/18749927/139605539-a6e1cf26-6ced-4ee0-8b1d-1d19a5ec478d.png)

Could you tell me if there is anything I missed?

Thanks

**Comment by aliabid94** [comment]
Can you share the structure of the directory, especially 
- where is the python file located
- where are the videos located
- where are you running the command to launch your python file

**Comment by jaekookang** [comment]
- The python file (`gradio_videosearch.py`) is located at the top level.
- Video files are located under `videos` folder.
- I'm launching my python file from the remote server.

<img width="250" alt="app" src="https://user-images.githubusercontent.com/18749927/139773170-62e43021-9650-40c3-8a8a-d94506e28ace.png">

While checking my code based on your comment, I found that I didn't add square brackets around the text inputs, which caused the error. After adding those brackets around text inputs, now video examples are properly loaded.

I guess I wasn't aware of the proper usage of parameter settings for `examples` keyword for `gr.Interface`, which was my fault.

Anyway, it's now working. Thank you @aliabid94.

<img width="902" alt="example" src="https://user-images.githubusercontent.com/18749927/139773343-7d6f3543-979b-4167-878c-02cad65123a8.png">

**Comment by abidlabs** [comment]
@aliabid94 is this the expected behavior? Why does @jaekookang need to put brackets around the text examples?

**Comment by aliabid94** [comment]
Hmm that’s unexpected, I’ll take a look

**Comment by abidlabs** [comment]
I tried to reproduce this issue, but wasn't able to @jaekookang. When I wrote the code below (to mirror yours), everything worked fine. Can you see if the issue resolved with the latest version of `gradio==2.4.2`?

![image](https://user-images.githubusercontent.com/1778297/140374835-2d8baa40-ef03-467f-8dda-496c8e545d59.png)

**Comment by jaekookang** [comment]
I see. The Gradio version that I used was 2.4.1. Maybe I should upgrade and re-try. For the time being, the double brackets around texts worked for me.
