### ISSUE TITLE
Global variable changes not reflected in Examples object in Gradio

### ISSUE THREAD

**Issue by dino1729** [gradio-app/gradio#3271]
### Describe the bug

I am trying to update the examples in a Gradio Examples object based on the value of a global variable, but the changes are not being reflected in the Gradio interface. Specifically, when I change the global variable and update the Examples object with the new examples, the interface still shows the old examples and does not update.

Steps to Reproduce:
1. Define a global variable and a function that returns examples based on the value of the global variable.
2. Initialize a Gradio Examples object with the initial examples returned by the function.
3. Launch the Gradio interface with the Examples object.
4. Update the global variable (via a function call on button click) and update the Examples object with the new examples.
5. Observe that the examples in the Gradio interface do not change.

Expected Result:
When the global variable is updated and the Examples object is updated with the new examples, the examples in the Gradio interface should also update to reflect the new examples.

Actual Result:
The examples in the Gradio interface do not change and continue to show the old examples.

Code Snippet:
gr.Examples(label="Example Queries", inputs=query, examples=example_queries)

Tried but doesn't work:
def updateexamples_component():
    example_queries = example_generator()
    return gr.Examples.update(examples=example_queries)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://github.com/dino1729/gpt_index/blob/dcb25d336c5628bd4128d4f40052b0139ebb6106/webinterface/gradioui.py

### Logs

```shell
I am unable to find the logs
```

### System Info

```shell
3.18.0, macOS, Brave Browser
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @dino1729 ! Thanks for filing the issue.

I think I know the issue. The `Examples` object loads examples from it's own [state](https://github.com/gradio-app/gradio/blob/main/gradio/helpers.py#L248) which is why updating the examples in your app will not be reflected.

However, you can roll-your-own examples for your use case by using `gr.Dataset`. In fact, `gr.Examples` is just a wrapper over `gr.Dataset`. With the following code, I am able to set the examples to reflect the state of the global variable.

```python
import gradio as gr
import random

samples = [["What is your name?"], ["Where are you from?"]]

def get_new_examples():
    if random.random() > 0.5:
        return [["What is your favorite food?"], ["How old are you?"]]
    else:
        return [["Where do you live?"]]


def update_examples():
    global samples
    samples = get_new_examples()
    return gr.Dataset.update(samples=samples)

def print_samples():
    global samples
    return {"samples": samples}

def load_example(example_id):
    global samples
    return samples[example_id][0]


with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column():
            question = gr.Textbox(label="question")
            examples = gr.Dataset(samples=samples, components=[question], type="index")
            generate = gr.Button(value="Generate examples")
        with gr.Column():
            global_state = gr.JSON(value={"samples": samples}, label="global variable")

        examples.click(load_example, inputs=[examples], outputs=[question])        
        generate.click(update_examples, inputs=None, outputs=[examples])
        generate.click(print_samples, inputs=None, outputs=[global_state])

demo.launch()
```

![updating_examples](https://user-images.githubusercontent.com/41651716/220705490-c7696217-e1f1-4336-8518-bf55084ec1ef.gif)


Given that `Examples` is meant to be a helper class, I'm not sure we should extend it to enable updating the examples. What do you think @abidlabs ?

**Comment by gitgithan** [comment]
In Dataset, what's the difference between samples and components? Looks like both provide data, or one can be inferred from another.

What are the edits required to make the Dataset look like Examples?
I'm using images and Dataset shows a vertical list of big images instead of like Examples where it's a grid of small images of fixed height. 

Generally I wish there was a guide on how the default high level Interface can be coded using Blocks api. I struggled very long before figuring out how to clear images in Blocks like using a clear button in the Interface api

**Comment by abidlabs** [comment]
> Given that Examples is meant to be a helper class, I'm not sure we should extend it to enable updating the examples. What do you think @abidlabs ?

Makes sense to me, @freddyaboulton. I think the workaround you've provided is pretty convenient (perhaps we should document it as a gist), and avoids having to worry about things like caching examples that can change. 

> Generally I wish there was a guide on how the default high level Interface can be coded using Blocks api. I struggled very long before figuring out how to clear images in Blocks like using a clear button in the Interface api

This is a great subbestion @gitgithan, happy to put this together. Would you like to create a separate issue for this and we can discuss there?

**Comment by freddyaboulton** [comment]
Sounds good - will close this out and add this example to the gist tracking issue! Let's open another issue for discussing building an interface with `gr.Blocks`!

**Comment by abidlabs** [comment]
Thanks @freddyaboulton and @dino1729! Will go ahead and close this issue

**Comment by ambiSk** [comment]
I want random dataset in each session, so I was thinking of using `gradio.State`, where on each session, `gradio.State` will contain new and random data, but how can I pass the data from `gradio.State` to `gradio.Dataset`

**Comment by abidlabs** [comment]
Hi @ambiSk just FYI if you pass in a _function_ as the initial value of any component, then it is rerun every time the page loads, and you can use that to set a random initial value for a component -- no need to use `gr.State`

**Comment by ambiSk** [comment]
Hey @abidlabs ,
Here's the code for my gradio app:
```
import gradio as gr
import numpy as np
data = np.random.randint(1, 100, size=100)

def load_data(example):
    return example[0]

def load_session_data():
    return np.random.choice(data, 10).reshape(-1,1).tolist()

with gr.Blocks() as iface:
    # sample = gr.State(value = None)    
    txt = gr.Textbox()
    ex = gr.Dataset(components=[txt], label="N/A", samples= load_session_data(), visible=True)
    ex.select(load_data, [ex], txt)

if __name__ == '__main__':
    iface.launch(server_name='0.0.0.0', server_port=9093)
```
And here's the output, both are two sessions and one loaded in incognito just not read cached cookies if produced by gradio:
![image](https://github.com/gradio-app/gradio/assets/89968892/b6d531ed-a517-4a0a-83d5-9af6210a43bc)

**Comment by abidlabs** [comment]
Ah okay it looks like `gr.Dataset` doesn't work with passing functions in. 

But you could potentially use a different component, like `gr.Dataframe`. Here's your updated code:

```py
```
