### ISSUE TITLE
Add a "viewable" opacity slider/setting to allow better viewing of the content under the Image sketch mask

### ISSUE THREAD

**Issue by Alchete** [gradio-app/gradio#3281]
In Image sketch the mask is currently applied at 100% opacity, which obscures the image content under the mask.  This makes it difficult to delineate the image content from the mask.

This is a request to add an option to adjust the "viewable" opacity of the mask so the user can adjust this parameter.

A possible implementation would be another button/slider for the "viewable opacity" in the Image sketch and other applicable components.

**Comment by abidlabs** [comment]
@pngwn I think we should remove this from the 3.x milestone given that we will likely rework the Image component as part of 4.0 or early 4.x

**Comment by abidlabs** [comment]
Closed via #4979
