### ISSUE TITLE
Infinite loop when adding print, but only to specific functions

### ISSUE THREAD

**Issue by gitgithan** [gradio-app/gradio#3290]
### Describe the bug

Below example is tweaked from https://gradio.app/docs/#update Try Examples -> blocks_update (middle of 3 tabs).

When `def func` has print, on first use, after clicking a radio, my console prints `idx []` forever. 
After ctrl+c to stop, and running the file again, it straightaway prints idx [] forever, as if ctrl+c didn't kill an infinite loop, and starting the file connected back to that loop. 
If this is true, I would like to learn how the "connecting back to undead threads" work in gradio and generally.

Is there some side thread executing some infinite loop? (i'm guessing based on the phrase `main thread` from  `^CKeyboard interruption in main thread... closing server.`). 

So ctrl+c and re-run doesn't fix the infinite print. The only way ctrl+c and re-run starts server normally is after I select something from the dropdown. How is this behaviour related to previous observations?

Removing the print in `def func` starts the server normally.

So i was thinking is it any print statement causes infinite loop because i definitely printed elsewhere successfully. 
To test that, I added a print in `def update_dropdown`and it works normally on all interactions. Only strange thing now is the txt output shows [] on my first dropdown click, subsequent dropdown clicks successfullly transfer a,b values to the textbox.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

with gr.Blocks() as demo:       
    species = gr.Radio(label="Animal Class", choices=["Mammal", "Fish", "Bird"])
    dropdown = gr.Dropdown(choices=[])  
    txt = gr.Textbox()
    
    def update_dropdown(value):
        # print(value)
        return gr.update(choices=list(range(1,value+1)))
                
    def func(idx):
        # print('idx',idx)
        return idx
    
    def filter_species(species):
        return gr.update(choices=['a','b'])
    
    species.change(filter_species, species, dropdown)
    dropdown.change(func, inputs=dropdown,outputs=txt)
        
if __name__ == "__main__":
    demo.launch()
```

### Logs

```shell
N.A.
```

### System Info

```shell
Python 3.8.12 (default, Dec  8 2021, 11:22:00) 
[Clang 12.0.5 (clang-1205.0.22.11)] 
Gradio version 3.19.1
MacOS Big Sur version 11.3
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
I think the bug here is because setting `choices=[]` in python, means the front-end gets an empty javscript array and they're technically different objects so the function on `dropdown.change` keeps getting triggered.
