### ISSUE TITLE
CORS error for get request from Javascript client side

### ISSUE THREAD

**Issue by tehfailsafe** [gradio-app/gradio#3294]
### Describe the bug

I have been working on a node version of my app, where the fetch to the API happens on server, specifically a deno edge function from Supabase. It works well. When I try to migrate the same fetch to the client side of javascript (so I can get realtime updates, some other benefits to UX) I hit the lovely CORS erorr.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

let res = await fetch(${this.server}/sdapi/v1/txt2img, {
method: "POST",
headers: {
"Content-Type": "application/json",
},
body: JSON.stringify({
prompt: dreamlike art portrait ${prompt},
negative:
"too many fingers, multiple people, two heads, two people, disfured body, blood, gore, violence, NSFW, naked, nude, sexy, innapropriate",
steps: steps,
batch_size: batch_size,
cfg_scale: cfg_scale,
width: 512,
height: 512,
restore_faces: restore_faces,
sampler_index: "Euler a",
}),
});

### Logs

```shell
Access to fetch at 'https://4fbbafb495b20a685c.gradio.app/sdapi/v1/txt2img' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

### System Info

```shell
Windows10, Chrome
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment]
Hi @tehfailsafe ! Can you share the gradio demo you're encountering this problem with? Is this with AUTO1111 sd web ui?

**Comment by tehfailsafe** [comment]
This is with the Auto1111 WebUI, yes. However it is using a build from December, before the change to the gradio URL scheme. If I use a current version it also has this error, but randomly disconnects instead of lasting 72 hours.

**Comment by abidlabs** [comment]
Hi @tehfailsafe I believe we did not use to enable CORS. We do now, so this shouldn't be a problem if you are using the latest version of `gradio`. Please see my similar answer to https://github.com/gradio-app/gradio/issues/4094
