### ISSUE TITLE
Request for streaming audio from a remote server

### ISSUE THREAD

**Issue by arjunbansal** [gradio-app/gradio#3299]
- [x] I have searched to see if a similar issue already exists.
related: #1775 

Is there a way to stream audio from a remote source such as when using [Amazon Polly](https://docs.aws.amazon.com/polly/latest/dg/example-html-app.html) or [Eleven Labs](https://api.elevenlabs.io/docs#/text-to-speech/Text_to_speech_v1_text_to_speech__voice_id__stream_post)?

There are currently ways to download a full audio file and play it via `gr.Audio` or an HTML embed, but in streaming demos/applications (real time translation, chatbots) it would be useful to be able to play sound from a streaming remote server rather than waiting to download the whole file.

**Comment by abidlabs** [comment]
Thanks for your question @arjunbansal. Yes, this should be possible. It kind of depends on your streaming setup, but you could write a generator function and keep `yield`-ing the output audio file to an `Audio` output component.

By the way, for general questions like this (that are not feature requests or bug reports), please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)

**Comment by arjunbansal** [comment]
Thanks, I have some follow up questions which I will continue [here](https://github.com/gradio-app/gradio/discussions/3316).

**Comment by snarb** [comment]
@arjunbansal  did you find solution? yield-ing fil names with sleep hangs the UI during sleep  @abidlabs  maybe you can help
