### ISSUE TITLE
continuous output

### ISSUE THREAD

**Issue by AlDrAkU** [gradio-app/gradio#33]
When run in a jupyternotebook the launch of the interface floods the cell with printing 
 "{'title': None, 'description': None, 'thumbnail': None, 'input_interface': [<gradio.inputs.Sketchpad object at 0x0000025F74CC0688>], 'output_interface': [<gradio.outputs.Label object at 0x0000025F74CC07C8>]}"

**Comment by aliabd** [comment]
Fixed. This will stop happening when we update the library, will let you know when we do, or you can clone the repo.

**Comment by abidlabs** [comment]
Gradio version 1.0.4 has been released, which solves this issue.
