### ISSUE TITLE
Additional menu for docs

### ISSUE THREAD

**Issue by gitgithan** [gradio-app/gradio#3301]
### Describe the bug

~~Change, Stream, Change (again) section in Image docs.~~ #3309

There is some space on right panel. Can there be a floating window that stays at the same place as user scrolls down, but with a content page that has different methods highlighted to show where the user is now? 
![image](https://user-images.githubusercontent.com/29853829/221100897-3317bb3f-84b4-4240-9c8c-d09a133c3a33.png)

Because the whole docs is a single scroll, numerous times I didn't realize I already scrolled past and was reading methods of another component. Also when I already selected the component from left panel, doing ctrl+f to find a method would jump me to some other component unknowingly. This caused significant confusion when I first learned slider and was trying to set the `step` but spent time debugging when `precision` (didn't know ctrl+f jumped me to Number) wasn't making slider give integers (slider did not respond/error on the unknown `precision` parameter.

How are the docs generated? I can't find them in the source.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

NA

### Logs

```shell
NA
```

### System Info

```shell
NA
```

### Severity

annoying

**Comment by pngwn** [comment]
This issue create both a feature request and a bug, I've created a new issue for the bug: #3309

Will update the title of this post.

**Comment by abidlabs** [comment]
This now exists, thanks for the suggestion @gitgithan 

<img width="1373" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/ab1c0584-e551-401e-8f98-7341095d2cb0">
