### ISSUE TITLE
https://gradio.app/controlling-layout/#variable-number-of-outputs broken interaction

### ISSUE THREAD

**Issue by gitgithan** [gradio-app/gradio#3302]
### Describe the bug

Adjusting the slider from default 10 to any other value causes Connection errored out.
Seems like the intended behaviour is to show the textboxes reducing.

Where are these docs demos running?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

NA

### Logs

```shell
NA
```

### System Info

```shell
NA
```

### Severity

annoying

**Comment by pngwn** [comment]
Do you have a reproduction for this issue please?

**Comment by gitgithan** [comment]
![image](https://user-images.githubusercontent.com/29853829/221178429-043d8622-f5eb-479a-a2ab-0f988aba31af.png)

![image](https://user-images.githubusercontent.com/29853829/221178544-ce935f19-1929-49d2-9785-76081c635c46.png)

I tested on firefox and its fine. Maybe there is something in my chrome that's blocking the websocket
