### ISSUE TITLE
Sketchpad cannot be updated by passing numpy array

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#3305]
### Describe the bug

It seems that when an image is passed to `gr.Image(tool='sketch')`, the image component is changed only on the first time and is ignored on the second time.

https://user-images.githubusercontent.com/25161192/221089586-b4dacae2-638b-43cb-89d9-c1fbd3aceda3.mp4

The expected behavior is that when the clear button is pressed, the canvas will be a blank image the second time as well.
It's also expected that when the run button is pressed the second time, it won't cause error, but I guess this will be automatically fixed once the first issue is fixed.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/hysts-debug/gradio-issue-3305

### Logs

```shell
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1022, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 914, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/home/user/.local/lib/python3.8/site-packages/gradio/components.py", line 1488, in preprocess
    assert isinstance(x, dict)
AssertionError
```

### System Info

```shell
gradio==3.19.1
```

### Severity

annoying

**Comment by abidlabs** [comment]
Can confirm that this is still an issue on `main` (cc @pngwn)

**Comment by pngwn** [comment]
![](https://media.giphy.com/media/53pyDH7JhT3bsPfNTu/giphy-downsized.gif)
