### ISSUE TITLE
Cannot update Image source?

### ISSUE THREAD

**Issue by gitgithan** [gradio-app/gradio#3306]
### Describe the bug

Are all parameters of components updatable with gr.update?

```
upload_webcam = gr.Radio(choices=['upload','webcam'])
upload_webcam.change(lambda selection: gr.Image.update(source=selection), inputs=upload_webcam, outputs=gr.Image())
```            

I get `TypeError: update() got an unexpected keyword argument 'source'` after clicking any of the radio options.

I'm not clear what's the purpose of streaming=True parameter in blocks api because the docs talk about `If True when used in a `live` interface` which i think only applies to Interface api but not blocks? How is `live=True` emulated in blocks api?

Also unclear is difference/dependencies between streaming=True, and the eventlistener image.stream. 
How do you trigger a image.stream event? (for both Interface api and Blocks api) 

As a workaround i tried to use the pattern here (https://huggingface.co/spaces/abidlabs/mic_or_file/blob/main/app.py)
by defining both elements and toggling visibility. 
However I could not dynamically update the input source of a event listener based on a radio selection? 
It seems that the input component for a event listener is evaluated once only, so later when I update a global variable refering to that input component, the event listener never sees the update and still gets input from the old source?

Another workaround was to have 2 event listeners too and do visibility tricks on the 2 buttons the event listeners are tied to, each with input tied to it's own image source (1 webcam, 1 upload). However this is unsustainable because any new event listener I add would have to have 2 image input versions that to users is the same thing when they click the same button (which is actually 2 different buttons with different event listeners).

My final workaround is to have upload always visible, then webcam hidden/showing by checkbox, then have webcam mirror to upload component on change, so with or without webcam component the upload component is there.

I was hoping to edit event_listener properties directly, so printed event_listener.items() and saw
```
{'targets': [10], 'trigger': 'click', 'inputs': [4], 'outputs': [7], 'backend_fn': True, 'js': None, 'queue': None, 'api_name': None, 'scroll_to_output': False, 'show_progress': True, 'every': None, 'batch': False, 'max_batch_size': 4, 'cancels': []}
```
What are these list of integers (eg. 10, 4, 7)? Are they foreign keys to objects (inputs, outputs, user_functions) stored elsewhere?

By the way i tried gr.update on streaming too and got similar `unexpected keyword argument` error. Not intending to do anything with it since don't understand, just trying

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

with gr.Blocks() as demo:
    cam = gr.Image(source="webcam")
    upload_webcam = gr.Radio(choices=['upload','webcam'])
    upload_webcam.change(lambda selection: gr.Image.update(source=selection), inputs=upload_webcam, outputs=cam)    
    
demo.launch()
```

### Logs

```shell
Traceback (most recent call last):
  File "/Users/hanqi/code/ahrefs/.venv/lib/python3.8/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/hanqi/code/ahrefs/.venv/lib/python3.8/site-packages/gradio/blocks.py", line 1024, in process_api
    result = await self.call_function(
  File "/Users/hanqi/code/ahrefs/.venv/lib/python3.8/site-packages/gradio/blocks.py", line 836, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/hanqi/code/ahrefs/.venv/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/hanqi/code/ahrefs/.venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/hanqi/code/ahrefs/.venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "stream.py", line 6, in <lambda>
    upload_webcam.change(lambda selection: gr.Image.update(source=selection), inputs=upload_webcam, outputs=cam)
TypeError: update() got an unexpected keyword argument 'source'
```
```


### System Info

```shell
Python 3.8.12 (default, Dec  8 2021, 11:22:00) 
[Clang 12.0.5 (clang-1205.0.22.11)] 
Gradio version 3.19.1
MacOS Big Sur version 11.3
```

### Severity

annoying

**Comment by pngwn** [comment]
It is not currently possible to update the `source` attribute of an Image.

**Comment by missionfloyd** [comment]
It can be updated by passing the attributes directly instead of using `gr.update()`.

E.g., `{"source": "webcam", "__type__": "update"}`
This is what [`gr.update()`](https://github.com/gradio-app/gradio/blob/ceb5853480ae23eef4f4ec1e5a481b00764fea2c/gradio/components.py#L1661-L1678) would send it, if it were supported. It seems to work fine; I can toggle between `webcam` and `upload`, and turn `mirror_webcam` on or off.

https://github.com/Mikubill/sd-webui-controlnet/blob/241c05f8c9d3c5abe637187e3c4bb46f17447029/scripts/controlnet.py#L202-L210
