### ISSUE TITLE
BarPlot d

### ISSUE THREAD

**Issue by pkmnjourney** [gradio-app/gradio#3308]
### Describe the bug

```AttributeError: module 'gradio' has no attribute 'BarPlot'```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```output = gradio.BarPlot()```

### Screenshot

![image](https://user-images.githubusercontent.com/38611352/221125120-23a7af9b-ea17-4271-a82a-106983b0d1f9.png)

### Logs

```shell
no output from debug
```

### System Info

```shell
3.16.2, Windows 10, Chrome
```

### Severity

annoying

**Comment by pngwn** [comment]
You'll need to upgrade Gradio from version `3.16.2` to `3.19.x` which is when `BarPlot` was added.
