### ISSUE TITLE
Markdown component introducing a lot of white space

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#3313]
### Describe the bug

Compare 3.19.1 to `main`

## 3.19.1

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/41651716/221236693-04a2b97a-7b4f-48da-90da-7eb39e27ecae.png">

## main
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/41651716/221236749-0a64cde3-3273-4979-8765-16c86920c118.png">

```python
import gradio as gr

with gr.Blocks() as demo:
    gr.Markdown("# Hello!")

demo.launch()
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

^

### Logs

```shell
-
```

### System Info

```shell
-
```

### Severity

annoying

**Comment by pngwn** [comment]
that is a lot of whitespace

**Comment by abidlabs** [comment]
Yup affecting `gr.Interface()` too, we should fix this before release:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/1778297/221368389-727172c0-a5d9-46f2-9e58-8487b20ea9c8.png">

**Comment by pngwn** [comment]
Okay its a flex thing.
