### ISSUE TITLE
Document in the config if the block function is a generator and if it runs forever

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#3314]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Needed for the several clients as discussed in this thread: https://huggingface.slack.com/archives/C02SPHC1KD1/p1677190325992569

**Describe the solution you'd like**  

**Additional context**

**Comment by pngwn** [comment]
We actually already track `every` i think, it is just other generating functions. Maybe we can combine them in the config. Although it would be good to know if they run forever or have a finite number of runs, if we have that info. It might also be good to know if a prediction is the last one, although i don't think that is essential.

**Comment by freddyaboulton** [comment]
> Although it would be good to know if they run forever or have a finite number of runs, if we have that info.

Yea I was thinking of adding two fields to the dependency config

1. `continuous`: True if runs forever.
2. `generator`: True if its is a generating function.

1 implies 2 but not the other way around.

**Comment by pngwn** [comment]
Would we remove `every` in this case? I think those names are better. Or we could add a `types` field with the function type(s). Either a list or an 'object'. Some degree of namespacing might be nice

**Comment by pngwn** [comment]
I guess we can't remove anything as that might be breaking.

**Comment by freddyaboulton** [comment]
I like the suggestion to use `types` field! Let's not remove every for the reason you mentioned and I think it's good to know the expected frequency anyways.
