### ISSUE TITLE
height='auto' for gr.Gallery clashes with scale=2 for gr.Column

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#3317]
### Describe the bug

makes galleries non interactive

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

a

### Screenshot

a

### Logs

```shell
a
```

### System Info

```shell
a
```

### Severity

annoying

**Comment by abidlabs** [comment]
Is this still an issue @pngwn? Would be good to add a repro

**Comment by abidlabs** [comment]
Or close if this is no longer a concern :)

**Comment by pngwn** [comment]
Sorry, I haven't had time to repro yet. Was reported to me by someone else. Will repro when i get the chance.
