### ISSUE TITLE
3.16.0 introduced breaking change for Dropdown

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#3319]
### Describe the bug

The addition of the multiselect option to `Dropdown` introduced a breaking change for the Dropdown components output signature. The default case when there is no value (for example, an optional dropdown that a user does not interact with before submitting) is now an array (list on the python side) instead of an empty string. This means checks like `dropdown == ""` etc will now be False rather than True.

I think it is fine if users select an option and _then_ select nothing.

This is the offending line: https://github.com/gradio-app/gradio/pull/2871/files#diff-f0b03055e354ad5f6f0c4c006adba9a9fe60a07ca1790b75e20cd0b69737ede8R11

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Above.

### Screenshot

-

### Logs

```shell
-
```

### System Info

```shell
-
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Wouldn't it make sense to have the default be `""` if `multiselect=False` and be `[]` if `multiselect=True`?

**Comment by pngwn** [comment]
Yeah, thats what it should be and brings it back to the previous behaviour.

We can consider aligning the types in 4.0.
