### ISSUE TITLE
gr.Column(variant='compact') is not compact, default variant is compact?

### ISSUE THREAD

**Issue by gitgithan** [gradio-app/gradio#3322]
### Describe the bug

The variant setting seems to be swapped between compact and default.

And why does `panel` look the same as `compact` (refering to the no gap one that needs "default" to show) but just shifted down? Is text element unable to show the difference? Docs implies `default` has no rounded corners by explicitly mentioning corners for `compact` and `panel`, but the screenshot shows `default` does have rounded corners.

It's not in the code and screenshot but i checked variant='default' and giving no argument is the same visually.

On a more complex code, adding `variant='compact'` to `with gr.Column():` causes my app to get stuck at loading... with the gradio icon?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr


with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column(variant='compact'):
            gr.Textbox('one')
            gr.Textbox('two')
        with gr.Column():
            gr.Textbox('three')
            gr.Textbox('four')
        with gr.Column(variant='panel'):
            gr.Textbox('five')
            gr.Textbox('six')

    
demo.launch()
```

### Screenshot

![image](https://user-images.githubusercontent.com/29853829/221392289-68105971-2e11-4811-9097-0c5e5d92141c.png)

### Logs

```shell
NA
```

### System Info

```shell
NA
```

### Severity

annoying

**Comment by abidlabs** [comment]
Looks like this is fixed now! 

<img width="1276" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/ccaad2dd-9997-43e1-bdaf-39cfdc0c28a4">
