### ISSUE TITLE
[Bug] Changes from calling gr.update on a Dataset component is not reflected when calling Dataset.click.

### ISSUE THREAD

**Issue by Aldo-Aditiya** [gradio-app/gradio#3323]
### Describe the bug

For context, my current UI is as below:
![Screen Shot 2023-02-26 at 18 56 10](https://user-images.githubusercontent.com/22410385/221406296-547c431c-c378-4bf7-be3d-61e1b4966b43.png)

1. The first row is for uploading multiple image files. After I clicked on the "Upload" button I will pass the uploaded images to: (1) The gallery component on the right column, and (2) the Dataset component in the second row.

2. In the second row, if I click on a dataset, I expect it to show up in the image output on the right column.

In the first row, passing the image data to the Dataset component is done by calling gr.update(samples=...) as an output to the Dataset component. In the second row, passing the dataset image to the image component on the right is done by calling Dataset.click on the specific Dataset instance.

Problem is, even after updating the samples, Dataset.click uses the old samples. Below is what happens when I click on the first image:
![Screen Shot 2023-02-26 at 18 48 06](https://user-images.githubusercontent.com/22410385/221406507-fade57c2-afb1-4d56-8f34-cb78dc457553.png)

And if I click on the other image, an error pops up:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1022, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 914, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/usr/local/lib/python3.10/site-packages/gradio/components.py", line 5369, in preprocess
    return self.samples[x]
IndexError: list index out of range
```

Am I doing something wrong?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

def input_func_1(files):
    return [f.name for f in files], gr.update(samples=[[f.name] for f in files])
    # return [f.name for f in files], [[f.name] for f in files]

def input_func_2(img):
    return img[0]

# Non Rendered Object Definition
out_2 = gr.Image().style(height=256, width=256)
ds_2 = gr.Dataset(components=[gr.Image(visible=False)],
                        label="Arrangement",
                        samples=[["1.jpeg"]])

with gr.Blocks() as demo:
    # File Upload Component
    gr.Markdown("### Upload Images")
    with gr.Row():
        with gr.Column():
            f = gr.File(file_count='multiple', file_types=['images'])
            btn_f = gr.Button("Upload")
        out_f = gr.Gallery().style(grid=[3], height="256")
        btn_f.click(fn=input_func_1, inputs=f, outputs=[out_f, ds_2])

    # Dynamic Dataset Component
    gr.Markdown("### Select Arrangements")
    with gr.Row():
        ds_2.click(
                    fn=input_func_2,
                    inputs=ds_2,
                    outputs=out_2
                )
        ds_2.render()
        out_2.render()

demo.launch()
```

### Logs

```shell
-
```

### System Info

```shell
3.19.1, Ubuntu, Brave
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @Aldo-Aditiya thanks for creating this issue. There's an existing issue that covers this (#2143), so I'll close. It's a bit of a tricky problem, but we'll work on a fix.
