### ISSUE TITLE
Misc feedback on Spaces gr.Interface.load integration

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#3325]
### Describe the bug

When using 

```
space = gr.Interface.load("spaces/stabilityai/stable-diffusion-1")
```

I would like to be able to run inference, but doing 

```
space("Astronaut in Space")
```

gives the following error

```
AssertionError: <class 'gradio.components.Dataset'> Component with id 66 not a valid input component.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Code above

### Logs

```shell
AssertionError                            Traceback (most recent call last)
<ipython-input-13-dc152f715cd2> in <module>
----> 1 space("Astronaut in Space")

1 frames
/usr/local/lib/python3.8/dist-packages/gradio/blocks.py in serialize_data(self, fn_index, inputs)
    876         for i, input_id in enumerate(dependency["inputs"]):
    877             block = self.blocks[input_id]
--> 878             assert isinstance(
    879                 block, components.IOComponent
    880             ), f"{block.__class__} Component with id {input_id} not a valid input component."

AssertionError: <class 'gradio.components.Dataset'> Component with id 66 not a valid input component.
```

### System Info

```shell
Colab, 3.19
```

### Severity

annoying

**Comment by osanseviero** [comment]
Usager for Spaces with tabs is unclear. How should I do inference for a Space such as https://huggingface.co/spaces/multimodalart/mindseye-lite?

**Comment by abidlabs** [comment]
Thanks @osanseviero! 

> Usager for Spaces with tabs is unclear. How should I do inference for a Space such as https://huggingface.co/spaces/multimodalart/mindseye-lite?

Usually, you'd click on the View API link at the bottom of the page, and it would tell you the syntax on how to use each inference function as an API. In this case, this Space is using an older version of Gradio where this does not show. 

Here's an example Space I just put together: https://huggingface.co/spaces/abidlabs/tabs-api

As far as the first issue regarding `stabilityai/stable-diffusion-1`, let me take a look at what's happening there.

**Comment by abidlabs** [comment]
I looked into the first issue and the problem is that by default `gr.Interface.load()` uses the first API endpoint. In this case, the first API endpoint corresponds to the examples, not to the prediction function. It will work if you do:

```py
space("Astronaut in Space", fn_index=2)
```

We'll try to make this easier using the Python client (#2516)
