### ISSUE TITLE
File.upload returns an empty file in 3.19.1

### ISSUE THREAD

**Issue by oobabooga** [gradio-app/gradio#3328]
### Describe the bug

If I create a `gr.File` object with `type='binary'` and attach a `upload` event to it, the returned file is empty if I upload a .zip file.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr
import time

def f(file):
    print(file)

with gr.Blocks() as interface:
    x = gr.File(type="binary")
    x.upload(f, x, None)

interface.queue()
interface.launch(debug=True)
```

Launch this interface and try to upload a .zip file. The following will be printed:

```
b''
```

Meaning that the temporary file created by gradio is empty.

### Logs

```shell
No errors.
```

### System Info

```shell
gradio==3.19.1
Linux
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
@aliabid94 maybe this broke as part of the large file issue?

**Comment by fkhan0520** [comment]
Hey @oobabooga I wasn't able to reproduce with the provided code on gradio==3.19.1. Are you able to share the zip file this fails with?

**Comment by oobabooga** [comment]
Sure, here is an example of .zip file that generates `b''` for the sample code above:

https://files.catbox.moe/as41my.zip

**Comment by abidlabs** [comment]
Was able to reproduce, thanks @oobabooga -- working on a fix
