### ISSUE TITLE
Iterative output example does not work

### ISSUE THREAD

**Issue by zhxgj** [gradio-app/gradio#3330]
### Describe the bug

Cannot run the iterative output example. Getting an error "Expecting value: line 1 column 1 (char 0)"

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

**Python env**

```
python3.8 -m venv venv && . venv/bin/activate
pip install gradio==3.19.1
```

**Script**

```
import gradio as gr
import time
import numpy as np

# define core fn, which returns a generator {steps} times before returning the image
def fake_diffusion(steps):
    for _ in range(steps):
        time.sleep(1)
        image = np.random.random((600, 600, 3))
        yield image
    image = "https://gradio-builds.s3.amazonaws.com/diffusion_image/cute_dog.jpg"
    yield image


demo = gr.Interface(fake_diffusion, inputs=gr.Slider(1, 10, 3), outputs="image")

# define queue - required for generators
demo.queue()

demo.launch(share=True)
```

### Screenshot

![image](https://user-images.githubusercontent.com/25310735/221480002-6482e549-9115-4306-b3e8-cda1d1e77041.png)

### Logs

```shell
No stack track of the error is printed, even if enabling debug=True
```

### System Info

```shell
python 3.8.6
gradio==3.19.1
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @zhxgj I can't reproduce the issue. See here: https://colab.research.google.com/drive/1yZvSZQTjbgFC6BKVHCB2BhXvm-xxCnit?usp=sharing -- working fine for me in Colab

**Comment by zhxgj** [comment]
Sorry my fault. The demo failed due to my network and proxy configuration. It is not a bug.

**Comment by tianyil1** [comment]
I also met this issue. How to solve if running in a server with the proxy.

**Comment by smamindl** [comment]
> Hi @zhxgj I can't reproduce the issue. See here: https://colab.research.google.com/drive/1yZvSZQTjbgFC6BKVHCB2BhXvm-xxCnit?usp=sharing -- working fine for me in Colab

Hi, the demo does not work for long time, I am trying for 1000 steps and it stopped at 169.
<img width="1329" alt="image" src="https://github.com/gradio-app/gradio/assets/106691906/eaede883-8c86-4034-af19-c3a95c1d5d88">

**Comment by smamindl** [comment]
> Hi @zhxgj I can't reproduce the issue. See here: https://colab.research.google.com/drive/1yZvSZQTjbgFC6BKVHCB2BhXvm-xxCnit?usp=sharing -- working fine for me in Colab

It does not function on cloud.
