### ISSUE TITLE
frpc_linux_amd64 Cannot connect to 35.165.217.216:7000: i/o timeout

### ISSUE THREAD

**Issue by ThanapatSornsrivichai** [gradio-app/gradio#3332]
### Describe the bug

I was able to use the command. As workaround for issue #3060 for automatic1111 webui.
frpc_linux_amd64 http -n $RANDOM -l 7860 -i 127.0.0.1 --uc --sd random --ue --server_addr 35.165.217.216:7000 --disable_log_color
Until yesterday the share link crash and now I couldn't connect to 35.165.217.216 anymore
Is there any changes?

Logs
2023/02/27 17:53:07 [W] [service.go:132] login to server failed: dial tcp 35.165.217.216:7000: i/o timeout
dial tcp 35.165.217.216:7000: i/o timeout

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1.Start webui 
2. Running local host http://127.0.0.1:7860/
3. Use command ./frpc_linux_amd64 http -n $RANDOM -l 7860 -i 127.0.0.1 --uc --sd random --ue --server_addr 35.165.217.216:7000 --disable_log_color | to open a tunnel with gradio
4. Got the error

### Logs

```shell
2023/02/27 17:53:07 [W] [service.go:132] login to server failed: dial tcp 35.165.217.216:7000: i/o timeout
dial tcp 35.165.217.216:7000: i/o timeout
```

### System Info

```shell
3.16.2 , Ubuntu 24.04.2, firefox
```

### Severity

blocking all usage of gradio

**Comment by ThanapatSornsrivichai** [comment]
Please at least make version 3.16.2 support frpc-gradio-0.2 since Automatic1111 webui user cannot upgrade to 3.19.1 without breaking the UI.

**Comment by abidlabs** [comment]
Hi @ThanapatSornsrivichai please replace the IP address `35.165.217.216:7000` with `44.237.78.176:7000` and it should work. As mentioned, this is a workaround so we can't really guarantee support for this feature going forward.

**Comment by beautyhansonboy** [comment]
I also encountered this problem on the Linux system. How can I solve it. 
2024/01/10 09:46:34 [W] [service.go:132] login to server failed: dial tcp 44.237.78.176:7000: connect: connection refused

**Comment by JanoutV** [comment]
Hello,

Can someone explain what the `rpc_darwin_amd64_v0.2 http -n NuxexRfpukWI43zDELgGR2EBnYu5i33lmFL-hWHMsfE -l 7860 -i 127.0.0.1 --uc --sd random --ue --server_addr 44.237.78.176:7000 --disable_log_color` command does and why it needs to reach out to an external IP `44.237.78.176:7000`. This suspicious activity makes this binary marked on [VirusTotal](https://www.virustotal.com/gui/file/6d3bd9f7e92e82fe557ba1d223bdd25317fbc296173a829601926526263c6092/relations) as malicious. Could you please explain what are you trying to do here?

**Comment by withyou1771** [comment]
same problem

**Comment by Zzbo-Zasper** [comment]
> I also encountered this problem on the Linux system. How can I solve it. 2024/01/10 09:46:34 [W] [service.go:132] login to server failed: dial tcp 44.237.78.176:7000: connect: connection refused

Have you solved this problem?

**Comment by sandy-ssdut** [comment]
> same problem. login to server failed: dial tcp 44.237.78.176:7000: i/o timeout gradio 4.44.0

Same problem, Have you solved it?

**Comment by tanhao-call** [comment]
> > same problem. login to server failed: dial tcp 44.237.78.176:7000: i/o timeout gradio 4.44.0
> 
> Same problem, Have you solved it?

have you solved it?
