### ISSUE TITLE
Button 'variant' changes the button size

### ISSUE THREAD

**Issue by Alchete** [gradio-app/gradio#3337]
### Describe the bug

Using the button "variant" parameter to emulate a ToggleButton, seems to radically change the size of the button -- perhaps ignoring the button's original placement constraints(?).

(I do notice that the row code in the larger UI contains the following constraint:
with gr.Row().style(**equal_height=False**):

This is being attempted from within the Automatic1111 UI, so some of that code is provided below for context as well.

Essentially this is for a "lock aspect ratio" button that will change both its icon and "color" when toggled.

As to the issue behavior, once the button becomes "larger", it always remains at that size.  

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

To reproduce
```
lock_symbol = '\U0001F512' # 🔒
unlock_symbol = '\U0001F513' # 🔓

lock_aspect_btn = ToolButton(value=unlock_symbol, elem_id="txt2img_lock_aspect_btn")
lock_aspect_btn.click(toggle_aspect_ratio, inputs=[lock_aspect_btn, width, height], outputs=lock_aspect_btn)

    def toggle_aspect_ratio(btn, width, height):
        if btn == unlock_symbol:
            return gr.update(value = lock_symbol, variant="primary")
        else:
            return gr.update(value = unlock_symbol, variant="secondary")
```

UI BUILDER CODE FOR CONTEXT (part of larger UI)
```
        with gr.Row().style(equal_height=False):
            with gr.Column(variant='compact', elem_id="txt2img_settings"):
                for category in ordered_ui_categories():
                    if category == "sampler":
                        steps, sampler_index = create_sampler_and_steps_selection(samplers, "txt2img")

                    elif category == "dimensions":
                        with FormRow():
                            with gr.Column(elem_id="txt2img_column_size", scale=4):
                                width = gr.Slider(minimum=64, maximum=2048, step=8, label="Width", value=512, elem_id="txt2img_width")
                                height = gr.Slider(minimum=64, maximum=2048, step=8, label="Height", value=512, elem_id="txt2img_height")

                            lock_aspect_btn = ToolButton(value=unlock_symbol, elem_id="txt2img_lock_aspect_btn")
                            res_switch_btn = ToolButton(value=switch_values_symbol, elem_id="txt2img_res_switch_btn")

                            if opts.dimensions_and_batch_together:
                                with gr.Column(elem_id="txt2img_column_batch", scale=1):
                                    batch_count = gr.Slider(minimum=1, step=1, label='Batch count', value=1, elem_id="txt2img_batch_count")
                                    batch_size = gr.Slider(minimum=1, maximum=8, step=1, label='Batch size', value=1, elem_id="txt2img_batch_size")
```

### Screenshot

![image](https://user-images.githubusercontent.com/4705189/221631161-c8b1add8-f6c6-48a0-ad31-f731232464ef.png)
![image](https://user-images.githubusercontent.com/4705189/221631178-a195d6b9-f325-4e52-8049-0282bdd1ce30.png)

### Logs

```shell
N/A
```

### System Info

```shell
gradio-3.16.2
Chrome / Windows 10
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Thanks @Alchete for creating this issue.

Related discussion: https://github.com/gradio-app/gradio/discussions/3333

**Comment by pngwn** [comment]
That's a very big button.

**Comment by abidlabs** [comment]
I can't seem to reproduce this with a simple example @Alchete, like this:

```py
import gradio as gr

def toggle_aspect_ratio(btn):
    if btn == "run":
        return gr.update(value = "lock", variant="primary")
    else:
        return gr.update(value = "run", variant="secondary")

with gr.Blocks() as demo:
    with gr.Row().style(equal_height=False):
        a = gr.Button()
        b = gr.Button("run")
        b.click(toggle_aspect_ratio, b, b)
        
demo.launch()
```

I wonder if any of the custom css in the web ui is causing this behavior. Do you see this behavior happen even if the variant is not updated? I.e. if the `toggle_aspect_ratio()` function looks like this:

```py
    def toggle_aspect_ratio(btn, width, height):
        if btn == unlock_symbol:
            return gr.update(value = lock_symbol)
        else:
            return gr.update(value = unlock_symbol)

```

**Comment by Alchete** [comment]
Hi @abidlabs yes, I just verified that it works as expected when the 'variant' parameter isn't passed.  

```
    def toggle_aspect_ratio(btn, width, height, aspect_ratio):
        if btn == unlock_symbol:
            aspect_ratio = width/height
            # return [gr.update(value = lock_symbol, variant="primary"), aspect_ratio]
            return [gr.update(value = lock_symbol), aspect_ratio]
        else:
            # return [gr.update(value = unlock_symbol, variant="secondary"), aspect_ratio]
            return [gr.update(value = unlock_symbol), aspect_ratio]
```

Are you trying it with an icon or just by changing the text name of the button?

Maybe add these to the demo just to rule out an issue with the icon?

```
lock_symbol = '\U0001F512' # 🔒
unlock_symbol = '\U0001F513' # 🔓

```

**Comment by Alchete** [comment]
I was able to modify your test case to almost match the Automatic1111 UI, however, something in A1111 is shrinking the buttons to their smallest size, as you may notice from my screenshots above.

In the test case reproduction, nothing is shrinking the buttons, so they already fill the available space and don't show the behavior.

![image](https://user-images.githubusercontent.com/4705189/221738008-4bf0bea7-0273-409c-81e6-6fc3748d5bb6.png)

It's not apparent to me what's shrinking all buttons to their minimum size in A1111.

```
import gradio as gr

lock_symbol = '\U0001F512' # 🔒
unlock_symbol = '\U0001F513' # 🔓
switch_values_symbol = '\U000021C5' # ⇅

class FormRow(gr.Row, gr.components.FormComponent):
    """Same as gr.Row but fits inside gradio forms"""

    def get_block_name(self):
        return "row"

class ToolButton(gr.Button, gr.components.FormComponent):
    """Small button with single emoji as text, fits inside gradio forms"""

    def __init__(self, **kwargs):
        super().__init__(variant="tool", **kwargs)

    def get_block_name(self):
        return "button"

def toggle_aspect_ratio(btn):
    if btn == unlock_symbol:
        return gr.update(value = lock_symbol, variant="primary")
    else:
        return gr.update(value = unlock_symbol, variant="secondary")

with gr.Blocks() as demo:
    with gr.Row().style(equal_height=False):
        with gr.Column(variant='compact', elem_id="txt2img_settings"):
            with FormRow():
                with gr.Column(elem_id="txt2img_column_size", scale=4):
                    width = gr.Slider(minimum=64, maximum=2048, step=8, label="Width", value=512, elem_id="txt2img_width")
                    height = gr.Slider(minimum=64, maximum=2048, step=8, label="Height", value=512, elem_id="txt2img_height")

                b = ToolButton(value=unlock_symbol)
                a = ToolButton(value=switch_values_symbol)

                with gr.Column(elem_id="txt2img_column_batch", scale=1):
                    width = gr.Slider(minimum=64, maximum=2048, step=8, label="Width", value=512, elem_id="txt2img_width")
                    height = gr.Slider(minimum=64, maximum=2048, step=8, label="Height", value=512, elem_id="txt2img_height")

    b.click(toggle_aspect_ratio, b, b)
        
demo.launch()
```

**Comment by abidlabs** [comment]
Thanks for sharing this @Alchete -- sounds like there is almost certainly some custom css in play here. If you are able to inspect the element and see what custom css is being applied to the buttons, you could than pass that css in using the `css` argument to `gr.Blocks()`. Otherwise, I don't see a way that we'll be able to reproduce this in a manner that we can fix it.

**Comment by missionfloyd** [comment]
Here's what's making the buttons small.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8/style.css#L649-L657

Setting variant to primary sets the class to `gr-button-primary`. So, the solution is to apply the above rules to your button.
```css
#txt2img_lock_aspect_btn {
    margin: 0.6em 0em 0.55em 0;
    max-width: 2.5em;
    min-width: 2.5em !important;
    height: 2.4em;
}
```

**Comment by abidlabs** [comment]
Thanks @missionfloyd!
