### ISSUE TITLE
Chatbot rendering image broken when file name has space in it

### ISSUE THREAD

**Issue by dawoodkhan82** [gradio-app/gradio#3339]
### Describe the bug

When running `chatbot_multimodal` demo, and uploading an image with spaces in the file name, the image does not render in the chatbot.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`chatbot_multimodal` demo

### Logs

```shell
N/A
```

### System Info

```shell
3.19.1
```

### Severity

annoying

**Comment by dawoodkhan82** [comment]
The markdown parser `markdown-it` doesn't support links with spaces (https://github.com/markdown-it/markdown-it/issues/147). It doesn't recognize it as a link.

**Comment by abidlabs** [comment]
Very intriguing. Does URL encoding the space (converting it to "%20") work?

**Comment by dawoodkhan82** [comment]
@abidlabs the dev can add `image.name = image.name.replace(" ", "%20")`. I guess we can add this in the postprocessing for the chatbot. But I'm wondering how I can determine the message being passed in the `postprocess` of chatbot is an image url vs text.

**Comment by abidlabs** [comment]
Cool that’s good to know, yeah I think we’d have to do some regex to figure out that it’s an image file path in Markdown’s image format. ChatGPT is pretty good at regex btw!

**Comment by dawoodkhan82** [comment]
Seems like this change fixed this issue (https://github.com/gradio-app/gradio/pull/3370/files#diff-82459fb7cccafabf1195b5a189b3bdef828616963ca2ff3b8dfafc5e64f8a487R14-R22)

**Comment by abidlabs** [comment]
I can't reproduce this issue anymore on `main` either @dawoodkhan82, can you?

**Comment by dawoodkhan82** [comment]
It's actually because we're replacing spaces in the demo code `history = history + [(f"![](/file={quote(image.name)})", "Cool pic!")]`. I'll push a fix for this issue in the postprocessing.
