### ISSUE TITLE
Fix padding for chatbot image + text in same chat bubble

### ISSUE THREAD

**Issue by dawoodkhan82** [gradio-app/gradio#3340]
### Describe the bug

The chat bubble when showing both text and an image  is awkward because of no padding.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`chatbot_multimodal` demo

### Logs

```shell
N/A
```

### System Info

```shell
3.19.1
```

### Severity

annoying

**Comment by abidlabs** [comment]
Looks like this is fixed now: 

<img width="684" alt="image" src="https://user-images.githubusercontent.com/1778297/223490556-640c0364-a39a-4737-9923-3c5d660b7421.png">

Feel free to reopen @dawoodkhan82 if I'm mistaken!
