### ISSUE TITLE
css file path has to be absolute but relative is expected to work 

### ISSUE THREAD

**Issue by gitgithan** [gradio-app/gradio#3346]
### Describe the bug

```
import gradio as gr

inline_css = """
.gradio-container {
    background-color:red}
    """

import os 

# with gr.Blocks(css=inline_css) as demo: # works
# with gr.Blocks(css="test_css.css") as demo: # doesn't work
with gr.Blocks(css=os.getcwd()+"/test_css.css") as demo: # works
    demo.launch()
```
I was expecting the 2nd version directly using `test_css.css` to work. 
css file has benefits over inline string such as ide support for clicking colors so i see no reason to use the string unless it's really short

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Create `test_css.css` at same level as gradio `app.py`  storing the string value (without quotes) of `inline_css` 

```
import gradio as gr

inline_css = """
.gradio-container {
    background-color:red}
    """

import os 

# with gr.Blocks(css=inline_css) as demo: # works
# with gr.Blocks(css="test_css.css") as demo: # doesn't work
with gr.Blocks(css=os.getcwd()+"/test_css.css") as demo: # works
    demo.launch()
 ```

### Logs

```shell
NA
```

### System Info

```shell
NA
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks for creating this issue @gitgithan. I can't reproduce this on the latest version of `gradio`, as you can see in this Colab notebook (screenshot below): https://colab.research.google.com/drive/1vkvar5QAK_Bmar2GHtZLmrucY9mRuFMY?usp=sharing

<img width="985" alt="image" src="https://user-images.githubusercontent.com/1778297/223229999-6a2ac043-1e9b-4c20-857c-323508676cbc.png">

Can you see if this is still an issue for you on `gradio==3.20.1` and if so, share a Colab rerproduction?

**Comment by gitgithan** [comment]
I verify your example works, and can't reproduce this issue, both on colab and on my full app (meaning it's suddenly working), so I guess can close this.
