### ISSUE TITLE
Add sorted BarPlot feature

### ISSUE THREAD

**Issue by pkmnjourney** [gradio-app/gradio#3350]
**Is your feature request related to a problem? Please describe.**  
A clear and concise description of what the problem is. Ex. I'm always frustrated when Currently the `BarPlot` component takes in a `dataframe`, and sorts it by the defined `x` value. In my case the `x` value is a class name while the `y` value is a number.

**Describe the solution you'd like**  
I would like the `BarPlot` to sort from greatest to smallest based on the `y` value rather than the `x`.

**Comment by freddyaboulton** [comment]
Great suggestion @pkmnjourney ! Would you be interested in opening a PR to contribute this feature?

**Comment by pkmnjourney** [comment]
> Great suggestion @pkmnjourney ! Would you be interested in opening a PR to contribute this feature?

**Comment by pkmnjourney** [comment]
> Great suggestion @pkmnjourney ! Would you be interested in opening a PR to contribute this feature?

Yes of course, which branch should i pull from?

**Comment by freddyaboulton** [comment]
@pkmnjourney You can branch off the latest main!

Here is the contributing guide for new contributors: https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md. We're working on making it more effective/clearer so don't hesitate to ask questions and offer improvements on the guide.

**Comment by freddyaboulton** [comment]
Hi @pkmnjourney ! Are you still interested in helping us add this new feature?

**Comment by pkmnjourney** [comment]
Yes, apologies for the late development but I wasn’t able to get my hands on an ubuntu machine so I wasn’t able to run the bash scripts for the gradio requirements.

**Comment by freddyaboulton** [comment]
Are you on a windows machine?

**Comment by Chaitanya134** [comment]
Hey @freddyaboulton,
Since no one was working on this issue actively and I wanted to start contributing to this repo. I thought of addressing the issue on my own.

**Changes Made:**
Added sorting functionality to the chart rendering process.
Introduced two new arguments: `sort_by` and `reverse` to the `BarPlot` class, allowing users to specify the sorting axis and order.

New Arguments and Expected Behavior:

```
sort_by (Literal["x", "y"] | None = None):
    - Specifies` the sorting axis as either "x" or "y."
    - If set to None, no sorting is applied.
```
```
reverse (bool = False):
    - If True, the data will be sorted in descending order (from largest to smallest values).
    - If False (the default), the data will be sorted in ascending order (from smallest to largest values).
```
Do you think these additions are fine, and should I proceed with committing these changes to the repository?

Looking forward to your input!

**Comment by freddyaboulton** [comment]
Hi @Chaitanya134 ! Yes, thank you for the interest and the contribution. If you open a PR, I will review it.
