### ISSUE TITLE
Automated end-to-end testing of frontend/backed on PR commits

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#3354]
From discussing with @pngwn 

>  Yea agreed we shouldn't spin up a separate backend for to test a single feature. On board with your suggestion of spinning up one server with one demo (or demos) running that should enable us to test most of the api in an end-to-end fashion. Happy to take that on by extending the `slider-release` test to cover more of the api. I think it will help make gradio more stable by catching unintended regressions prior to release.

_Originally posted by @freddyaboulton in https://github.com/gradio-app/gradio/issues/3353#issuecomment-1450739864_

**Comment by abidlabs** [comment]
What was this issue about? Just adding more e2e tests? @dawoodkhan82 @freddyaboulton do you remember?

**Comment by freddyaboulton** [comment]
We can close as this was tracking setting up the e2e tests as we currently have them - one server that launches lots of demos and we test most of the public api
