### ISSUE TITLE
Chatbot css height of inner chat pane does not work

### ISSUE THREAD

**Issue by ffahmed** [gradio-app/gradio#3357]
### Describe the bug

Hi there, 

I tried to apply height in Chatbot like following. Although I was able to change the height, but the inner pane (where the text and image comes in) still has default height and appears with scroller. How do I make the inner pane bigger. Check the image attached. I want to make the inner pane bigger so I can view the image and the text together. How do I do it.

Current code
with gr.Blocks(css="#chatbot {height:600px}") as demo:
    chatbot = gr.Chatbot(elem_id="chatbot")

Resulting Chatbot:
![image](https://user-images.githubusercontent.com/16159711/222351173-862340a6-1d9e-4812-9165-59c7b4d33dd5.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr

def add_text(state, text):
    state = state + [(text, text + "?")]
    return state, state

def add_image(state, image):
    state = state + [(f"![](/file={image.name})", "Cool pic!")]
    return state, state

with gr.Blocks(css="#chatbot {height:600px}") as demo:
    chatbot = gr.Chatbot(elem_id="chatbot")
    state = gr.State([])

    with gr.Row():
        with gr.Column(scale=0.85):
            txt = gr.Textbox(show_label=False, placeholder="Enter text and press enter, or upload an image").style(container=False)
        with gr.Column(scale=0.15, min_width=0):
            btn = gr.UploadButton("🖼️", file_types=["image"])

    txt.submit(add_text, [state, txt], [state, chatbot])
    txt.submit(lambda :"", None, txt)
    btn.upload(add_image, [state, btn], [state, chatbot])

demo.launch(debug=True, server_name="0.0.0.0")

### Screenshot

![image](https://user-images.githubusercontent.com/16159711/222351744-508686c0-37ca-40b9-befc-9640cd81b477.png)

### Logs

```shell
None. All visual
```

### System Info

```shell
gradio==3.17.1, Ubuntu 18.04.6 LTS, Chrome
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Thanks for creating this issue @ffahmed but as mentioned in #3356, for general questions like this (that are not feature requests or bug reports), please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)

**Comment by YanshekWoo** [comment]
> ### Describe the bug
> Hi there,
> 
> I tried to apply height in Chatbot like following. Although I was able to change the height, but the inner pane (where the text and image comes in) still has default height and appears with scroller. How do I make the inner pane bigger. Check the image attached. I want to make the inner pane bigger so I can view the image and the text together. How do I do it.
> 
> Current code with gr.Blocks(css="#chatbot {height:600px}") as demo: chatbot = gr.Chatbot(elem_id="chatbot")
> 
> Resulting Chatbot: ![image](https://user-images.githubusercontent.com/16159711/222351173-862340a6-1d9e-4812-9165-59c7b4d33dd5.png)
> 
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Reproduction
> import gradio as gr
> 
> def add_text(state, text): state = state + [(text, text + "?")] return state, state
> 
> def add_image(state, image): state = state + [(f"![](/file=%7Bimage.name%7D)", "Cool pic!")] return state, state
> 
> with gr.Blocks(css="#chatbot {height:600px}") as demo: chatbot = gr.Chatbot(elem_id="chatbot") state = gr.State([])
> 
> ```
> with gr.Row():
>     with gr.Column(scale=0.85):
>         txt = gr.Textbox(show_label=False, placeholder="Enter text and press enter, or upload an image").style(container=False)
>     with gr.Column(scale=0.15, min_width=0):
>         btn = gr.UploadButton("🖼️", file_types=["image"])
> 
> txt.submit(add_text, [state, txt], [state, chatbot])
> txt.submit(lambda :"", None, txt)
> btn.upload(add_image, [state, btn], [state, chatbot])
> ```
> 
> demo.launch(debug=True, server_name="0.0.0.0")
> 
> ### Screenshot
> ![image](https://user-images.githubusercontent.com/16159711/222351744-508686c0-37ca-40b9-befc-9640cd81b477.png)
> 
> ### Logs
> ```shell
> None. All visual
> ```
> 
> ### System Info
> ```shell
> gradio==3.17.1, Ubuntu 18.04.6 LTS, Chrome
> ```
> 
> ### Severity
> blocking upgrade to latest gradio version

hello, I would like to know if the issue still exists and if there are any possible solutions.
