### ISSUE TITLE
Multiple group dataframe data input?

### ISSUE THREAD

**Issue by Smile-L-up** [gradio-app/gradio#3359]
Hello, I would like to ask if multiple groups of dataframe data input is currently supported? If so, what should I do?

**Comment by abidlabs** [comment]
Hi @Smile-L-up, for general questions like this (that are not feature requests or bug reports), please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB). Please provide additional details as well as it's a little unclear to me what the question is (I'll close this issue)
