### ISSUE TITLE
Does share=True work with docker on macbook m1?

### ISSUE THREAD

**Issue by yyihuan** [gradio-app/gradio#3378]
# Description
I am using gradio in docker and expect to provide public network access using launch(share=True). However, on the macbook m1, docker does not support host mode. This is preventing share from being enabled and here is the output
```shell
Running on local URL:  http://0.0.0.0:80

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app
```
I've tried mapping port 22 but it didn't work.
# What I expect to get help with
I would appreciate some help in solving this problem including but not limited to
* What way should I start docker
* How the share function works and what ports and protocols it uses
* A ready-made docker-compose.yml

**Comment by abidlabs** [comment]
Hi @yyihuan thanks for raising this issue. This sounds like a general question and not a feature requests or bug report, so please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)

**Comment by sophieDataroots** [comment]
Seems to have something to do with https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6210#issuecomment-1369004135
