### ISSUE TITLE
You can't upload an image for sketch in 3.20.0

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#3381]
### Describe the bug

It's hard to recognize the sketchpad boundary when using gradio 3.20.0.

https://user-images.githubusercontent.com/25161192/222938887-bdfaefeb-ef6e-41c4-97db-0e7640ddb60f.mp4

It was shown like this when using gradio 3.19.1.
![](https://user-images.githubusercontent.com/25161192/222938917-43ae592e-afcc-4f3f-9758-6b32d6213c50.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/hysts-debug/gradio-issue-3381

[Here](https://huggingface.co/spaces/hysts-debug/gradio-issue-3305) is a Space with the same code using gradio 3.19.1.

### Logs

```shell
none
```

### System Info

```shell
gradio==3.20.0
```

### Severity

annoying

**Comment by pngwn** [comment]
Renaming this issue. It's much worse than that, you can't upload an image at all.
