### ISSUE TITLE
Improve UX by letting files upload after submit button is clicked

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#3382]
Several users have brought up this concern:

> So after the Files component fix related to the large files and base64, the component now displays when the files are being uploaded. That cool, but before the fix you could press the submit button immediately after selecting files and the processing would automatically start after uploading finishes. Now you have to wait, otherwise accessing the non-uploaded files gives errors.

> One could block the launch button until the upload completion now that the interactive option is introduced, but that's bad UX, the user will have to wait twice, instead of just launching the uploading and processing together and going for tea or something, if the processing job is long.

_Originally posted by @Seedmanc in https://github.com/gradio-app/gradio/discussions/3379_

**Comment by freddyaboulton** [comment]
This basically the same problem as https://github.com/gradio-app/gradio/issues/2718 and #3435, no?

**Comment by pseudotensor** [comment]
@abidlabs The upload progress is sketchy.  There's a non-trivial delay before it shows processing, even for a large file.  Usually I only see processing near end, not during upload.

In addition, the user can click upload again while there is upload going.  It should be blockable, or at least clear if one can upload another file.  From what I've seen, upload another file removes original one, so not sure why ever wouldn't be blocked.

**Comment by freddyaboulton** [comment]
Events can no longer be triggered while files are being uploaded as of version 5.x so will close!
