### ISSUE TITLE
gradio.app/changelog/ has a weird appearance

### ISSUE THREAD

**Issue by yannickfunk** [gradio-app/gradio#3393]
### Describe the bug

Bullet points in https://gradio.app/changelog/ seem to bee arranged in columns instead of rows

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Open https://gradio.app/changelog/

### Screenshot

![image](https://user-images.githubusercontent.com/44268911/223222836-79e03cb5-43fb-4b4a-a422-aa41545a94d6.png)

### Logs

```shell
-
```

### System Info

```shell
Windows 11, Chrome Version 110.0.5481.178 (Official Build) (64-bit)
```

### Severity

annoying

**Comment by pngwn** [comment]
It is part of a new endeavour to innovate in UI + UX design as well as ML applications. This is the first of many experiments designed to push us forward.

**Comment by pngwn** [comment]
jk it's a bug. 

cc @aliabd
