### ISSUE TITLE
How can I Redirect user in gradio

### ISSUE THREAD

**Issue by zinoubm** [gradio-app/gradio#3395]
Beeing able to redirect a user to another url is really useful and sometimes it's mandatory, I need to redirect my users to the google oauth url provided by the api. I didn't found this functionality in gradio, but I think its possible since gradio uses fastApi under the hood. While the team discuss the ability to add this feature can any one give a work around for now?

**Comment by abidlabs** [comment]
Hi @zinoubm you might be interested in this: https://gradio.app/sharing-your-app/#mounting-within-another-fastapi-app

Basically, Gradio could be part of a larger FastAPI app. You could have other routes that handle authentication and then route to Gradio once the user has been authenticated

Does this address your use case?

**Comment by zinoubm** [comment]
Man, You are the best

**Comment by abidlabs** [comment]
Happy to help, shall we close this issue?

**Comment by zinoubm** [comment]
Yes, sure.
