### ISSUE TITLE
Does the current input interface support video input?

### ISSUE THREAD

**Issue by a849173140** [gradio-app/gradio#34]
My model is a video based classification model, Gradio is currently supported?
One more little question, how do I set up POST?

**Comment by abidlabs** [comment]
Currently, we don't have video as an input interface, but we are working on setting that up. Can you tell us more about your use case?

As far as your second question, I'm not sure what you mean. Can you elaborate some more?

**Comment by a849173140** [comment]
> e
Thanks for your reply

My model is about the behavior detection of the person in the video, input the video and output whether the video contains the behavior.

About the second question, I mean that the default port is currently 7860 after deployment,  how can I modify it.

**Comment by abidlabs** [comment]
Great, we'll let you know once we support video. 

As far as the port, you can simply pass in the `server_port` parameter when you create the `Interface` object

**Comment by a849173140** [comment]
Ok, I see. Thank you very much.
