### ISSUE TITLE
Progress bar component

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#340]
@aliabid94 I think this is a great suggestion! It would be nice if people can provide their own status updates at different parts of the code. Perhaps this could be possible as you revamp the queuing mechanism?

### Discussed in https://github.com/gradio-app/gradio/discussions/339

<div type='discussions-op-text'>

<sup>Originally posted by **abnerLing** November  8, 2021</sup>
I have an app that takes a video input then extracts audio to run speech-to-text inference. I was wondering if there is a way to display the progress of the video upload? For example, using Hugging Face ([https://huggingface.co/spaces/abnerh/video-to-subs](https://huggingface.co/spaces/abnerh/video-to-subs)) or a shared link will just show a timer but I want the user to see how long the upload time takes.

Thanks</div>

**Comment by xiaol** [comment]
Hi,  i use a image as a inference input, this would be very smooth for user experience.how can i help this to be done?

**Comment by apolinario** [comment]
+1 for this. Now that we have iterative outputs, should be great to have a progress bar component, if it were integrated with tqdm automagically even better as so many implementations already use it to give progress bar estimation.

I think this could come together with this issue for doing the same thing but with the native progress bar embeded into the output components: https://github.com/gradio-app/gradio/issues/2683

**Comment by fcakyon** [comment]
Any updates on the component? It would make things mush smoother :)

**Comment by abidlabs** [comment]
We have a WIP in #2750, let us know if you have any thoughts on it! Aiming to merge in next week
