### ISSUE TITLE
Block requests not coming from host domain

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#3400]
We've gotten some requests from users to block API requests that are not originating from the UI or from the host domain. When we launch the Gradio clients, it's likely these requests may increase as more people learn about using Gradio-as-an-API. 

We should provide an option for users of Gradio to disable API requests altogether if they would like.

**Comment by pngwn** [comment]
This is a relatively fragile solution, so we shouldn't position it as a security feature. It is very easy to spoof.

**Comment by freddyaboulton** [comment]
Isn’t this what api_open=False does?

**Comment by pngwn** [comment]
Do they want the api open, but only to them or just closed in general?

**Comment by abidlabs** [comment]
`api_open=False` still allows you to make requests via websockets. The main purpose of `api_open` is to prevent people from skipping the queue. But what if a developer wants to stop API requests altogether? As @pngwn pointed out, I don't think we can provide a foolproof solution since hosts can be spoofed, but something that at least puts up a barrier to entry would be nice. This is particularly important since we are about to release clients which will make connecting via websockets much easier. And people who have paid for upgraded Spaces may not want their Spaces being used in this way. 

Relevant international conversation: https://huggingface.slack.com/archives/C02136Y252P/p1666455972870769?thread_ts=1666447456.974249&cid=C02136Y252P

I've also heard this request externally. Here's one example (from a user who reached out via email):

> I don’t want anyone to be able to access my App programmatically. Is there at least any way to differentiate HTTP requests that come from the frontend from those that come from calling the endpoints directly? If so, I could incorporate some logic at application level to filter out those requests that are programmatic. I don’t want to enable queuing in my app because web sockets are not compatible with my web server.

**Comment by freddyaboulton** [comment]
> I don't think we can provide a foolproof solution since hosts can be spoofed, but something that at least puts up a barrier to entry would be nice. 

What if we create the concept of api keys for gradio apps? That way the app author has control over who can use their app programmatically and it's more foolproof than checking the host field of the request.

**Comment by freddyaboulton** [comment]
Let me know what you think about this:

We add a `set_api_keys` method to `Blocks` that lets app authors set a list of valid api keys.

We can add a util method to generate these keys for them but it's on them to store and manage their keys.

When deploying to spaces, they can read from environment variables.

```
with gr.Blocks() as demo:
    ....

demo.set_api_keys([os.environ["API_KEY_1"], os.environ["API_KEY_2"]]).launch()
```

We should also modify `Blocks` to automatically generate an api key for the front end.

**Comment by abidlabs** [comment]
It's not clear to me what advantage this would provide if we still have to send the API keys to the frontend so that it can make requests to the backend. A dedicated person could still just read the API keys in the frontend and then use that to create API requests themselves. It also feels like we might be expanding the API too much for a relatively niche case (whereas I was thinking a simple boolean parameter to restrict requests to same-hosts)

**Comment by pngwn** [comment]
Anything that restricts based on host will also break embeds btw.

**Comment by abidlabs** [comment]
Closing as rate limiting on public Spaces should mitigate this issue
