### ISSUE TITLE
Use immutable container types for method parameters

### ISSUE THREAD

**Issue by zellski** [gradio-app/gradio#3419]
### Describe the bug

Types like `List` and `Set` are [invariant](https://mypy.readthedocs.io/en/stable/generics.html#variance-of-generic-types), meaning a method like:
```
    def change(
        self,
        fn: Callable | None,
        inputs: Component | List[Component] | Set[Component] | None = None,
        ...
```
can't be called the way you'd generally expect with e.g. a `List[gr.Textbox]` for `inputs` (or, to be more precise, such calls don't pass static type checking.)

A more intuitive signature would use the abstract, immutable types (which exist largely for this purpose) that have covariant behaviour – we'd use `Sequence` instead of `List`, `Mapping` instead of `Dict`, `AbstractSet` instead of `Set`, and so on.

It matters much less for return types (though it can obviously be nice to signal immutability in cases where the caller shouldn't be mutating the internals of returned collections).

This should be close to a a drop-in replacement. Is it on anybody's radar? I could possibly put together a PR, if there's interest.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

This example snippet fails type-checking:
```
    inputs = [gr.Number()]
    outputs = [gr.Text()]
    inputs[0].change(fn=lambda n: f"The number is #{n}", inputs=inputs, outputs=outputs)
```

Pyre's output:
```
Incompatible parameter type [6]: In call `gr.events.Changeable.change`, for argument `inputs`, expected `Union[None, List[Component], Set[Component], Component]` but got `List[Number]`.
Incompatible parameter type [6]: In call `gr.events.Changeable.change`, for argument `outputs`, expected `Union[None, List[Component], Component]` but got `List[Textbox]`.
```

### Logs

```shell
N/A, not a runtime error
```

### System Info

```shell
>>> gradio.__version__
'3.19.1'
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks @zellski, I was trying to figure this out when we added typing to the codebase but couldn't fully wrap my head around covariant types. We would definitely want to fix this issue, so a PR for this would be much appreciated.

**Comment by abidlabs** [comment]
Hi @zellski are you still interested in opening a PR for this?

**Comment by zellski** [comment]
@abidlabs I am, as time allows – but admittedly that's a tad scarce these days & I can't make any promises. If anyone else is chomping at the bit to get it, let them!

**Comment by abidlabs** [comment]
No problem,  thanks @zellski!

**Comment by zellski** [comment]
I fear there is a related issue in [this recent commit](https://github.com/gradio-app/gradio/commit/95bf08b2e29448f64e1e892200a014310ffc6d76#diff-0dd827ecd796f1d09e48052f6f80c1c9cf519eb940595994c65744ca40b0ae6aR926-R930), where the `issubclass()` method is called to test if `parameter_types.get(name, int)` is an `EventData`.

When method arguments are generic types like `Sequence`, this fails (because the first argument to `issubclass()` must be a proper class) and I'm forced to declare my methods with concrete parameter types, like `list[str]`.

I suspect in this case there's a pretty simple fix, extending the subclass-checking logic a bit. I can write up a new issue for it if you like, and while I'm loathe to continue to overpromise and underdeliver perhaps I could also take a pass at fixing it.

**Comment by abidlabs** [comment]
That would definitely be appreciated — I’m a little confused what the underlying problem is, so if you can create the issue explaining your proposed solution is, I may work on this myself next week

**Comment by failable** [comment]
Any news?
