### ISSUE TITLE
Refactor `components.py` to simplify the creation of new components

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#3438]
Ahead of custom components, it would be good to simplify the process of creating new component classes. Many opportunities for simplification:

- [x]  Remove `IOComponent.add_interactive_to_config` from `.update()`
- [x]  On that note, can we remove `.update()` altogether since its almost a duplicate of `get_config()`?
- [x]  On that note, can we remove `get_config()` since it basically just returns all of the constructor parameters. Should be a simpler way to do this
- [x]  Can we get rid of `generate_sample()`
- [x]  Should we remove interpretation (!!!)? It seems like almost no one uses it and causes significant complexity in the code base
- [x]  Make it easier for users to figure out which serialization class to mix in
- [x]  Should we break up each component into separate python file? So it would mirror the structure in the frontend
- [x]  Why do we have `Component` and `IOComponent` as separate classes -- does this distinction still make sense?
- [ ]  Clarify what it means to be used as an input component vs. output component. Technically any component, like the Chatbot, can also be used as an input component
- [x]  Having to explicitly call the parent methods `IOComponent.` is not ideal
- [x]  Can we get rid of `.style()`, and make every parameter part of the constructor? That way we don't have to worry about updating style parameters separately too
- [x] Simplify tempfile creation

Definitely a 4.0 thing

**Comment by space-nuko** [comment]
> Why do we have Component and IOComponent as separate classes -- does this distinction still make sense?

I have actually run into a case where this distinction is important, I needed to pass a dynamic list of components into an input field, but I wasn't able to tell which ones were valid for use with inputs. Without being able to do `isinstance(component, IOComponent)` I would have gotten the error "Component is not a valid input component"

If these classes are merged then there should still be a way to programmatically tell if a component can be used for input/output

**Comment by abidlabs** [comment]
Thanks @space-nuko, that's a good point. Would you be able to share a code snippet or link to the Space? It would be helpful to have some more context as we think about this point.

**Comment by space-nuko** [comment]
Actual code where I needed to this was

https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/a441b6fb1d5376cc946f4c25f5229284a577cd0c/modules/generation_parameters_copypaste.py#L142

**Comment by freddyaboulton** [comment]
Most have been checked off! Closing!!
