### ISSUE TITLE
Option to add path to the url

### ISSUE THREAD

**Issue by claree007** [gradio-app/gradio#344]
When the app is launched locally, it opens at http://localhost:7860. I would like to have an option to add a path to the url. So if I specify "myapp" as the custom path, the app should launch at http://localhost:7860/myapp and for "myapp/gradio", the app should launch at http://localhost:7860/myapp/gradio.

The need for this that the server on which our gradio app will be deployed has got rules where only urls starting with whitelisted paths are allowed. For example, if "myapp" is in the whitelisted paths, then urls like http://server-ip:port/myapp and http://server-ip:port/myapp/foobar will work but http://server-ip:port/somethingelse will not go through.

**Comment by abidlabs** [comment]
Looking into this!

**Comment by abidlabs** [comment]
Working on this now as part of #440!

**Comment by abidlabs** [comment]
After looking into this some more, I think it's going to be a fair bit of effort since we will have to modify every single route in `app.py` to take a base URL prefix, along with every template that we use. Given that this seems to be a very niche use case (correct me if I'm wrong), we will push off for now. But PRs are welcome!

**Comment by claree007** [comment]
I agree that only a handlful of the users might need this feature. Sure, I will open a PR for this.

**Comment by abidlabs** [comment]
Thank you!

**Comment by abidlabs** [comment]
Any updates on this @claree007?

**Comment by claree007** [comment]
I found a way of doing what I wanted using voila. I put my gradio app inside a notebook and opened it using voila which has an option to configure the path where the UI is displayed.

**Comment by abidlabs** [comment]
Interesting, thanks for letting us know @claree007!

**Comment by MrNocTV** [comment]
> After looking into this some more, I think it's going to be a fair bit of effort since we will have to modify every single route in `app.py` to take a base URL prefix, along with every template that we use. Given that this seems to be a very niche use case (correct me if I'm wrong), we will push off for now. But PRs are welcome!

I think it's not that simple. I cant deploy gradio app on a K8S environment simply because the ingress path not working. 
Because the app always starts on path `/`, if I have a path in my url , let say `abc.com/myapp`and route to the service, it will return `404`. If I rewrite the path to `/`, it just wont work because I need a lot of ingress with different path. You get my point?

**Comment by abidlabs** [comment]
I see -- let's open this up as a feature request

**Comment by bottledmind** [comment]
Hey everyone.
Any progress here?

**Comment by abidlabs** [comment]
Not yet @bottledmind, internally we've deprioritized this issue for now but would welcome any PRs for this issue.

**Comment by abidlabs** [comment]
Hi folks! I took a dive into FastAPI and it turns out that it is actually possible to serve your Gradio app  on a custom path quite easily using FastAPI's `mount()` method. Here's a little demo I put together:

```py
"""
How to launch your Gradio app on a custom path, in this case localhost:8000/gradio

Run this from the terminal as you would normally start a FastAPI app: `uvicorn run:app`
and navigate to http://localhost:8000/gradio in your browser.
"""
from fastapi import FastAPI
import gradio as gr

CUSTOM_PATH = "/gradio"

app = FastAPI()

@app.get("/")
def read_main():
    return {"message": "This is your main app"}

io = gr.Interface(lambda x: "Hello, " + x + "!", "textbox", "textbox")
gradio_app = gr.routes.App.create_app(io)

app.mount(CUSTOM_PATH, gradio_app)
```

This serves the Gradio app on `http://localhost:8000/gradio` and even allows you to create a Gradio app within another FastAPI app.

**Comment by kumar045** [comment]
I want to restrict the access like only login user can access http://localhost:8000/gradio
How to do that in fastapi lets assume I have stored user id in user session variable of logged user

**Comment by lee101** [comment]
Getting some issues with that mount(CUSTOM_PATH, gradio_app) approach when it comes to serving audio files

the /file=/tmp/tmpebfha1b8.wav route is as an example actually at `otherdomain.co/mountpoint/file=/tmp/tmpebfha1b8.wav `
so i need to tell the gradio app about the mountpoint/otherdomain that its running on

**Comment by lee101** [comment]
To add some context to that i'm wanting to have the gradio html etc served from a cheap instance on mysite.com and actually send requests to say api.mysite.com/mountpoint/predict where the actual slow ml/inference is running all by itself and if that goes down the gradio will still be rendered from another fastapi app running on mysite.com that is running on cheap hardware

**Comment by lee101** [comment]
As a temporary solution to this i just redirected to the file route where i run the api server e.g. 

```
@app.get("/file{file_path:path}")
async def file(file_path: str, request: Request):
    # redirect to "api." and gradio_tts
    current_url = request.url
    if "localhost" in current_url.hostname or "127." in current_url.hostname:
        return RedirectResponse(url="http://localhost:8000/gradio_tts/file" + str(file_path))
    return RedirectResponse(url="https://api.text-generator.io/gradio_tts/file" + str(file_path))
```
pretty hack and there's maybe some other routes i would need to do that with but that works for my use case atleast
In that example the gradio app is running somewhere else at gradio_tts (localhost:8000 or api.text-generator.io) and i just redirect to it to squash that bug for now but would be good for it to be configurable in the app where its base host/path is.

I havn't looked deeply into how you protect it but also that file route seems conceptually insecure (but that's another thing)

**Comment by oreshytko** [comment]
Why is the issue closed?

**Comment by OkarinLi** [comment]
> I want to restrict the access like only login user can access http://localhost:8000/gradio
> 
> How to do that in fastapi lets assume I have stored user id in user session variable of logged user
Do you find any solution for this？

**Comment by RuiNov1st** [comment]
> I want to restrict the access like only login user can access http://localhost:8000/gradio How to do that in fastapi lets assume I have stored user id in user session variable of logged user

I'm curious about this issue as well. Have you got any idea about that?

**Comment by aghand0ur** [comment]
Hello @abidlabs, 

Based on the below issue, is there any option to run gradio on custom path without using FastAPI?
https://discord.com/channels/879548962464493619/1188792663370104934/1188792663370104934

**Comment by streamnsight** [comment]
for those who are just looking to set the root URL, for example when using ingress by path, just use the `root_path` param in the launch method to define the path to the app.
