### ISSUE TITLE
How to route audio output as base64-encoded string in API

### ISSUE THREAD

**Issue by liliest** [gradio-app/gradio#3440]
### Describe the bug

How to get base64 string for audio in response object to Gradio app that outputs audio?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Hi you guys,

Thanks for everything you do at Gradio, it's a wonderful project.

Let's say my app function is this:
```python
def generate_tone(note, octave, duration):
    sr = 48000
    a4_freq, tones_from_a4 = 440, 12 * (octave - 4) + (note - 9)
    frequency = a4_freq * 2 ** (tones_from_a4 / 12)
    duration = int(duration)
    audio = np.linspace(0, duration, duration * sr)
    audio = (20000 * np.sin(audio * (2 * np.pi * frequency))).astype(np.int16)
    return sr, audio
```

And let's say I launch the app like so:
```python
demo = gr.Interface(
    generate_tone,
    [
        gr.Dropdown(notes, type="index"),
        gr.Slider(4, 6, step=1),
        gr.Textbox(value=1, label="Duration in seconds"),
    ],
    "audio",
)

demo.launch(share=True)
```

According to the 'Use as API' page, the response object should look like this:
```
{
  "data": [
    { name: string; data: string }, // represents audio data as base64 string of 'output' audio component
  ],
  "duration": (float) // number of seconds to run function call
}
```

But in actuality it returns something more like this:

```
{'data': [{'name': '/tmp/tmpgscmw_qs.wav', 'data': None, 'is_file': True}],
 'is_generating': False,
 'duration': 0.06265091896057129,
 'average_duration': 0.7020081281661987}
```

Is there a canonical way to get it to return the base64 string instead of this cached temp file on the app-server side of things?

Thanks you guys!

### Logs

```shell
NA
```

### System Info

```shell
This is on '3.19.1', Ubuntu
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
I looked into this and it seems like the API docs are wrong here. They've been fixed in the latest version of gradio, so if you upgrade to `gradio==3.20.1`, you see this:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/1778297/224493614-4b328869-c90e-4692-bf59-d915aef8bd8a.png">

So from the client side, you can access the temporary file by doing `{URL}/file={name}` (and then convert it to base64 if needed). We stopped using base64 because serialization can be quite slow for large files.

Does that answer the issue?

**Comment by liliest** [comment]
Hi!

Can you access the temporary file in the same way in 3.19.1?

So, for example:

```python
wav, sr = sf.read("{gradioURL}/file=/tmp/tmpgscmw_qs.wav")
```
Trying to do yields me a system error.

My private HF Space boots with 3.19.1

**Comment by abidlabs** [comment]
Yes, the same format should work with `3.19.1` (although it is also possible to update the gradio version from your Space's README file). 

Hmm does `sf.read` support URLs? You might have to download the file first

**Comment by liliest** [comment]
Ah I see, thank you. 

Is there a preferable way of sending a file in the API response itself? Downloading from remote adds quite a bit of overhead.

**Comment by abidlabs** [comment]
> My workaround might just be to return the base64-encoded file and use the "text" output via Gradio :)

This should work. We'll likely add a `base64` output format for the file-based components in the future (#2392) so I'll go ahead and close this issue
