### ISSUE TITLE
When "allow_flagging" = auto, allow saving output as well

### ISSUE THREAD

**Issue by lakshman111** [gradio-app/gradio#3441]
- [yes] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
When "allow_flagging" = "auto", every input the user submits is automatically flagged (https://www.gradio.app/docs/#dataset).  Outputs are not flagged.  However, I need outputs to be flagged as well, similar to how inputs and outputs are flagged when "allow_flagging" = "manual".

**Describe the solution you'd like**  
When "allow_flagging" = "auto", allow outputs to be flagged as well so that they can also be auto saved along with the inputs to a Hugging Face dataset (similar to the behavior when "allow_flagging" = "manual").

**Additional context**  
My usecase is that I'd like to be able to see all input and output images, so that I can make sure the model is outputting quality results.

**Comment by Reekomer** [comment]
Is there anyone working on this issue? I also would like to be able to save inputs/outputs when flagging auto.

**Comment by lakshman111** [comment]
@Reekomer I ended up just adding an API call as a part of my function to upload.io to store both the input and the output.  May switch that storage to Supabase though!

**Comment by abidlabs** [comment]
We should fix this, this should now be possible by re-writing the flagging function to first wait until the prediction is complete and then use `.then()` to do the flagging. Will mark this open for contributors!

**Comment by davidberenstein1957** [comment]
I will work on this.

**Comment by davidberenstein1957** [comment]
@abidlabs I believe this should be an easy fix. I also missed the docs w.r.t. creating custom components so I added this BaseFlaggingCallback to the docs too.

**Comment by aperikleous** [comment]
@abidlabs Is there still a plan to add this feature? My use case requires constant flagging of both input and output, so this functionality would be really helpful.

**Comment by abidlabs** [comment]
Yes its on the roadmap to get this fixed, but we haven't had a chance yet. It may take us some time -- if anyone has bandwidth to fix this, we are happy to review a PR
