### ISSUE TITLE
Multi-language support 

### ISSUE THREAD

**Issue by wenmengzhou** [gradio-app/gradio#3442]
- [Y] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
To develop a gradio app which enbales developer configure different language and support user to choose the language the prefer to diplay the font component

**Describe the solution you'd like**  
Maybe give a language chosen selection-box for user,  and for developer, allow them to configure multi-language info in config files

**Additional context**

**Comment by abidlabs** [comment]
We are planning on adding automatic i18n to strings built into Gradio (#1078). In terms of developers providing different strings to users from different locales, please take a look at this issue to see how that's doable right now: #2465
