### ISSUE TITLE
Json component doesn't respect `show_label`

### ISSUE THREAD

**Issue by braisedpork95** [gradio-app/gradio#3445]
### Describe the bug

The label covers part of the output content. Neither `show_label` nor `container` flag works.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

gr.Interface(
    lambda name: {'name': name},
    'text',
    gr.Json(label="json", show_label=False).style(container=True),
    allow_flagging="never",
).launch()
```

### Screenshot

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/46232992/224528045-2cc5ea36-795e-4048-9359-60062f0781aa.png">

### Logs

```shell
No response
```

### System Info

```shell
gradio==3.20.1
```

### Severity

annoying

**Comment by abidlabs** [comment]
@braisedpork95 we've fixed this issue in the latest version of `gradio` ([instructions for using here](https://gradio.app/docs/main/)), and we'll likely release to pypi early next week. Here's how it looks:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/1778297/224563320-576eec39-5c94-41a5-89d5-fe317dbe5783.png">

However, it seems like it still does not respect the `show_label` parameter so I've renamed the issue to reflect that
