### ISSUE TITLE
gradio.HTML CAN NOT load my javascript

### ISSUE THREAD

**Issue by JLWLL** [gradio-app/gradio#3446]
### Describe the bug

I use gradio.HTML('xxx.html') to load html.The script in this file can not be load.Please look at this example.
![image](https://user-images.githubusercontent.com/86763551/224535739-24962374-06ee-470d-97ef-a37983b89eda.png)
If U click this button.
Console will show:
![image](https://user-images.githubusercontent.com/86763551/224535854-2347955a-da1f-4e39-b896-7cf0bde07cc9.png)
So how can I load my JS?
Thanks for help!
I know can use gr.button(_js).
But if I wants to let it work when the web show.How do I implement this feature？
Such as:
`(function { alert('show web site'); })`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`test.html`
<button id="btn_test" onclick="click_test()">BUTTON</button>

<script>
    function click_test() {
        alert('click');
    }
</script>

`run.py`
test= shared.html("test.html")
gr.HTML(test, elem_id="test")

### Logs

```shell
None
```

### System Info

```shell
gradio==3.16.2
```

### Severity

blocking all usage of gradio

**Comment by ParisNeo** [comment]
Same problem here!

**Comment by bradley-pearson6597** [comment]
Is there a solution for this?

**Comment by pngwn** [comment]
This is expected behaviour. When HTML is inserted into a page the browser does not evaluate the script inside of script tags.

Instead do this:

```html
<button id="my_btn">Hello</button>
```

```py
html = html_file_contents

with gr.Blocks() as demo:
  gr.HTML(html)

demo.load(_js="""
const button = document.querySelector("#my_btn");
button.addEventListener("click", e => {
  alert("Clicked")
})
""")
```

**Comment by hxu296** [comment]
> This is expected behaviour. When HTML is inserted into a page the browser does not evaluate the script inside of script tags.
> 
> Instead do this:
> 
> ```
> <button id="my_btn">Hello</button>
> ```
> 
> ```python
> html = html_file_contents
> 
> with gr.Blocks() as demo:
>   gr.HTML(html)
> 
> demo.load(_js="""
> const button = document.querySelector("#my_btn");
> button.addEventListener("click", e => {
>   alert("Clicked")
> })
> """)
> ```

I appreciate the suggested approach, but unfortunately, I encountered a series of errors while trying it:

1. The `demo.load` function did not work outside of the Blocks context: I received the following error message: `AttributeError: load() and other events can only be called within a Blocks context.` Therefore, I placed it as the last line within the Blocks context.
2. Next, I encountered `Blocks.svelte:line_num SyntaxError: Unexpected token 'const'`. I suspected this might be due to the JavaScript version, so I tried using `var` instead, but that didn't work either.
3. To avoid declaring variables altogether, I used the following code. However, I came across a confusing error: `TypeError: document.addEventListener(...) is not a function`
```
document.addEventListener("DOMContentLoaded", function(event) {
    document.querySelectorAll(".block").forEach(function(block) {
    ...
    }
}
```

Could someone provide further assistance, please?

**Comment by bradley-pearson6597** [comment]
@hxu296 @JLWLL @ParisNeo 

Here's a solution that I've managed to find. Hope it helps!

```python

html = '''
<button id="my_btn" onclick="click_text()">Hello</button>
'''

script = '''
function test(){
    let script = document.createElement('script');
    script.innerHTML = "function click_text(){alert('click')}";
    document.head.appendChild(script);   
}


'''

with gr.Blocks() as block:
    gr.HTML(html)
    block.load(_js = script)
    
    
block.launch(debug=True, 
            share=False)

block.close()
```

**Comment by pngwn** [comment]
Yes sorry the code needs to be wrapped in a function, my mistake:

```py
html = html_file_contents

with gr.Blocks() as demo:
  gr.HTML(html)

demo.load(_js="""
function my_func() {
  const button = document.querySelector("#my_btn");
  button.addEventListener("click", e => {
    alert("Clicked")
  })
}
""")
```

**Comment by abidlabs** [comment]
Closing as this seems to have been solved, thanks @pngwn!

**Comment by hxu296** [comment]
It seems that people has gathered around this issue for adding custom JS to gradio. I can volunteer to make a PR for the [Blocks.load documentation](https://gradio.app/docs/#blocks-load) to reflect the solution @pngwn provided. Do you think this is a good idea? @abidlabs

**Comment by ParisNeo** [comment]
> It seems that people have gathered around this issue for adding custom JS to gradio. I can volunteer to make a PR to update the usage example is [Blocks.load documentation](https://gradio.app/docs/#blocks-load) to reflect the solution @pngwn provided. Do you think this is a good idea? @abidlabs

Good idea

**Comment by maxrossi** [comment]
OK but what if I want to reference external js script? (like <script src=...>)

**Comment by pngwn** [comment]
In 4.0 this parameter is named `js` with no underscore.

**Comment by wdlm520** [comment]
> OK but what if I want to reference external js script? (like <script src=...>)

head = f"""
<script async src="https://www.googletagmanager.com/gtag/js?id={google_analytics_tracking_id}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){{dataLayer.push(arguments);}}
  gtag('js', new Date());
  gtag('config', '{google_analytics_tracking_id}');
</script>
"""

with gr.Blocks(head=head) as demo:
    ...demo code...

**Comment by starascendin** [comment]
> > OK but what if I want to reference external js script? (like <script src=...>)
> 
> head = f"""
> 
> <script async src="https://www.googletagmanager.com/gtag/js?id={google_analytics_tracking_id}"></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){{dataLayer.push(arguments);}} gtag('js', new Date()); gtag('config', '{google_analytics_tracking_id}'); </script>
> """
> 
> with gr.Blocks(head=head) as demo: ...demo code...

can confirm this is working code :)

**Comment by thomasblanchard21** [comment]
I'm having the same issues as it seems that my js is not running in the html so I've tried the above solutions but still get no result. I implemented the same simple code that creates an alert when clicking the "hello" button:

`
import gradio as gr

html = "<button id='my_btn'>Hello</button>"

with gr.Blocks() as demo:
    gr.HTML(html)
    demo.load(js="""
        function my_func() {
            const button = document.querySelector("#my_btn");
            button.addEventListener("click", e => {
                alert("Clicked")
            })
        }
    """)

demo.launch()
`

I've tried some variations but still don't get it to work. If anyone has a clue, please let me know!

**Comment by ewwink** [comment]
for gradio 4.44 and maybe version 5.xx the `load()` need async code and call it like this
```
with gradio.Blocks() as block:
    block.load(None, None, None, js="""async () => {console.log('Hello')}""")
```

**Comment by pngwn** [comment]
That shouldn't be a requirement.

**Comment by Sebls** [comment]
For Gradio 5.21.0, adding the script as a head parameter for gradio.Blocks() works for me:

HTML file contents:

`<button id="my_btn">Hello</button>`

Gradio App File:

```
html = html_file_contents

script = """
const button = document.querySelector("#my_btn");
button.addEventListener("click", e => {
  alert("Clicked")
})
"""

with gr.Blocks(head=script) as demo:
  gr.HTML(html)
```

**Comment by redstoneleo** [comment]
even this didn't work in the latest version 
```

import gradio as gr

# Define a complete function in the page JS
page_js = """
<script>
function sayHello() {
    document.querySelector('button').innerText = 'Hello';
}
<script>
"""

with gr.Blocks(head=page_js) as demo:
    btn = gr.Button("Click Me")

    # Call the function you defined above
    btn.click(
    fn=None,
    inputs=[],
    outputs=None,
    js="(() => { sayHello(); })()"
)


demo.launch()
```

**Comment by neptotech** [comment]
> for gradio 4.44 and maybe version 5.xx the `load()` need async code and call it like this
> 
> ```
> with gradio.Blocks() as block:
>     block.load(None, None, None, js="""async () => {console.log('Hello')}""")
> ```

works
