### ISSUE TITLE
Port forwarding service down?

### ISSUE THREAD

**Issue by janmaltel** [gradio-app/gradio#3449]
### Describe the bug

Hey, I cannot access my app anymore through the `gradio.live` URL, created through `.launch(share=True)`. Is the server maybe down?

Specifically, I use [oobabooga/text-generation-webui](https://github.com/oobabooga/text-generation-webui) with
`python server.py --share --model opt-1.3b`

The output is
```
Loading opt-1.3b...
Loaded the model in 13.94 seconds.
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://[XXX].gradio.live/
```
so the app itself seems to be working (and also the gradio.live link worked yesterday!) but if I now go to the public URL I get a 504 Gateway Time-Out error. Thanks for any help!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See issue description.

### Logs

```shell
See issue description.
```

### System Info

```shell
SageMaker Studio with `ml.g4dn.xlarge` instance.
```

### Severity

blocking all usage of gradio

**Comment by scarbain** [comment]
I have the same problem : ReadTimeout: HTTPSConnectionPool(host='XXX.gradio.live', port=443): Read timed out. (read timeout=3)

**Comment by ckorherr** [comment]
also have the same problem

**Comment by Inoki1852** [comment]
Same.

**Comment by ckorherr** [comment]
Its working again!

**Comment by freddyaboulton** [comment]
@abidlabs Restarted the sharing server! Thanks for letting us know about the problem 🤗

**Comment by ShadeRedeye** [comment]
i got this problem too

**Comment by abidlabs** [comment]
Should be fixed @ShadeRedeye
