### ISSUE TITLE
Plot text doesn't render in dark mode

### ISSUE THREAD

**Issue by Goshujinsama** [gradio-app/gradio#3469]
### Describe the bug

When displaying an Altair plot, none of the text renders when using the dark theme. This can be seen clearly on the plot samples running on colab: 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://colab.research.google.com/github/gradio-app/gradio/blob/main/demo/altair_plot/run.ipynb

### Screenshot

<img width="634" alt="image" src="https://user-images.githubusercontent.com/2509024/225220669-9b4b0aaa-3299-445b-92c4-f8051d910fce.png">

### Logs

```shell
N/A
```

### System Info

```shell
Chrome
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Thanks @Goshujinsama ! Will take care of this
