### ISSUE TITLE
Examples don't respect darkmode when embedding

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#3485]
### Describe the bug

The text in the examples table for the calculator demo is black as opposed to white when embedding in dark mode

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```html
<script
	type="module"
	src="https://gradio.s3-us-west-2.amazonaws.com/3.21.0/gradio.js"
></script>

<div>
    <gradio-app space="gradio/calculator"></gradio-app>
</div>
```

In dark mode

### Screenshot

![image](https://user-images.githubusercontent.com/41651716/225751299-6cc40ddc-fd72-47e3-bd13-7d21ab0f29ca.png)

### Logs

```shell
-
```

### System Info

```shell
3.21.0, main
```

### Severity

annoying

**Comment by pngwn** [comment]
I can't reproduce with `3.22.x` or with `main`.

If this is still present can you provide full repro steps?

- The exact file you are running (is that snippet you posted complete?)
- How you are running the file (over a server, or just running the index.html)
- OS
- Browser

<img width="1795" alt="Screenshot 2023-03-21 at 13 25 31" src="https://user-images.githubusercontent.com/12937446/226619761-fe242a7b-b4b5-46d4-bada-5398f5d06877.png">

**Comment by freddyaboulton** [comment]
I just tried again with 3.23.0 and I still see the dark text for examples 🤔 

This is the entire html page which I open on Chrome (`Version 111.0.5563.64 (Official Build) (arm64)`) on Mac OS

```html
<script
	type="module"
	src="https://gradio.s3-us-west-2.amazonaws.com/3.23.0/gradio.js"
></script>

<div>
    <gradio-app space="gradio/calculator"></gradio-app>
</div>
```

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/41651716/226648062-d60a9ab6-9bb1-47e8-9d65-a58d9eecc8e1.png">

On `System Prefereces` for Mac, I have it set to `Dark`

**Comment by omarih33** [comment]
I have the same issue, except it occurs on mobile.

Desktop is dark/default? Mobile is light

**Comment by freddyaboulton** [comment]
Issue was resolved for me by adding a DOCTYPE and html tags (thanks @pngwn !)

```html
<!DOCTYPE html>
<html lang="en">
<script
	type="module"
	src="https://gradio.s3-us-west-2.amazonaws.com/3.23.0/gradio.js"
></script>

<div>
    <gradio-app space="gradio/calculator"></gradio-app>
</div>
</html>
```

Can you check if this fixes it for you @omarih33 ?

**Comment by abidlabs** [comment]
Lol I had the exact same experience for this other issue: #3486
