### ISSUE TITLE
Space name in embedding frame slightly vertically misaligned

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#3486]
### Describe the bug

The name of the Space (here: `gradio/calculator`) is slightly vertically misaligned in the embedding frame:

![image](https://user-images.githubusercontent.com/1778297/225753041-0ecd5f13-7381-415a-8a80-2dee4b9f52cf.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```html
<script
	type="module"
	src="https://gradio.s3-us-west-2.amazonaws.com/3.20.1/gradio.js"
></script>

<div>
    <gradio-app space="gradio/native_plots"></gradio-app>
    <gradio-app space="gradio/calculator"></gradio-app>
    <gradio-app space="gradio/video_component"></gradio-app>
</div>
```

### Logs

```shell
N/A
```

### System Info

```shell
Gradio 3.20.1
```

### Severity

annoying

**Comment by pngwn** [comment]
I'm not seeing this behaviour. What browser + OS?

**Comment by abidlabs** [comment]
I'm seeing it on Windows with Chrome or Edge.

All I do is run:

```html
<script
	type="module"
	src="https://gradio.s3-us-west-2.amazonaws.com/3.22.1/gradio.js"
></script>

<gradio-app space="gradio/hello_world"></gradio-app>
```

<img width="570" alt="image" src="https://user-images.githubusercontent.com/1778297/226450247-00ebb192-1979-4648-aa71-d57065825389.png">


Issue persists even after a hard refresh. What's weird is that I don't see this issue when I visit the website, even after a hard refresh: 

<img width="860" alt="image" src="https://user-images.githubusercontent.com/1778297/226450349-d0e49ce4-0e87-436f-8a8d-e3c768747e05.png">

**Comment by abidlabs** [comment]
Oh wow, did not know that! Thanks for the explanation @pngwn. Can confirm that adding the doctype fixed it for me. Closing
