### ISSUE TITLE
mount_gradio_app error

### ISSUE THREAD

**Issue by wuyuliyu** [gradio-app/gradio#3490]
### Describe the bug

![image](https://user-images.githubusercontent.com/19159821/225829725-86cf3269-c178-4586-8e81-aeec940b8345.png)
3.21：Unable to display properly.3.20： ok

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import uvicorn as u
from fastapi import FastAPI
import gradio as gr
app = FastAPI()
@app.get("/")
def read_main():
    return {"message": "This is your main app"}
io = gr.Interface(lambda x: "Hello, " + x + "!", "textbox", "textbox")
app = gr.mount_gradio_app(app, io, path="/gradio")
if __name__ == '__main__':
    u.run(app, host="127.0.0.1", port=8000)

### Screenshot

3.21：Unable to display properly.3.20： ok

### Logs

```shell
没有
```

### System Info

```shell
3.21
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Hi @wuyuliyu sorry about this -- we've fixed the issue in #3482.  We'll be releasing a new version of Gradio to Pypi in the next day or so
