### ISSUE TITLE
does gradio provide component for webrtc client?

### ISSUE THREAD

**Issue by chrjxj** [gradio-app/gradio#3491]
does gradio provide component for webrtc client?

**Comment by abidlabs** [comment]
Hi @chrjxj for general questions like this (that are not feature requests or bug reports), please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)

**Comment by freddyaboulton** [comment]
There is now a custom component for WebRTC streaming. Still under development but video in/out and audio-out are covered.

https://github.com/freddyaboulton/gradio-webrtc
