### ISSUE TITLE
Node js support for the JS client

### ISSUE THREAD

**Issue by jakiestfu** [gradio-app/gradio#3495]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I would like to be able to leverage the gradio client in my nodejs server to run inference on a private gradio api.

**Describe the solution you'd like**  
* Add [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch)
* Add [isomorphic-ws](https://www.npmjs.com/package/isomorphic-ws)
* Allow the client to pass a bearer token to be used in the headers of subsequent fetch requests and websocket connections

**Additional context**  
I've made these changes to the gradio client locally and it works like a charm. If ya'll are interested, I can pose a PR.

**Comment by abidlabs** [comment]
Thanks @jakiestfu for creating this issue, cc-ing @pngwn -- does this relate to the Gradio JS client you've been working on?

**Comment by jakiestfu** [comment]
In some ways there is a little bit of overlap with #3404 which I can support as well with my pull request.

**Comment by pngwn** [comment]
We don't want any PRs against the client just yet. Any changes would have no impact as the library is not released yet. We'll consider this use-case as we prepare for release.

Renaming the issue for clarity.

**Comment by jakiestfu** [comment]
Thats unfortunate to hear, @pngwn but I understand. Is there a timeline for release of the client?

**Comment by abidlabs** [comment]
[As described here](https://www.gradio.app/guides/getting-started-with-the-js-client#installation), all you should need to do is:

```
https://www.gradio.app/guides/getting-started-with-the-js-client#installation
```

**Comment by ms502040** [comment]
Is there any gradio client working without browser? I need pure nodejs implementation too. thx.

**Comment by pngwn** [comment]
@logesh2496 You need to update your node version to 18+. However there is another issue affecting the javascript gradio client in 4.0. This will be addressed shortly.

**Comment by jpaquim** [comment]
@pngwn any news on this issue? I'm getting errors when trying to run the client in Node.js (standard SvelteKit application, in a form action endpoint), I assume this is the issue you previously mentioned? `ReferenceError: EventSource is not defined` I guess I can try a polyfill for EventSource, but I'm not sure I won't run into other issues later on.

**Comment by AXLShorts** [comment]
Any development on this issue?

**Comment by pngwn** [comment]
There is a PR open for this atm. Should be released soon!
