### ISSUE TITLE
Could not create share link, please check your internet connection.

### ISSUE THREAD

**Issue by ProGamerGov** [gradio-app/gradio#3498]
### Describe the bug

Gradio cannot connect to the internet in a Google Cloud Compute instance

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I spun up a cloud instance like I have done many times in the past, and it's failing to create the internet lin.

### Logs

```shell
(base) user@instance-1:~/stable-diffusion-webui$ /home/user/stable-diffusion-webui/venv/bin/python3 webui.py --share --gradio-auth username8008:password --xformers
Loading weights [4711ff4dd2] from /home/user/stable-diffusion-webui/models/Stable-diffusion/v2-1_768-nonema-pruned.ckpt
Creating model from config: /home/user/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/configs/stable-diffusion/v2-inference-v.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 18.4s (load weights from disk: 12.6s, find config: 1.2s, create model: 0.2s, apply weights to model: 1.2s, apply half(): 0.4s, load VAE: 2.1s, move model to device: 0.7s).
Running on local URL:  http://127.0.0.1:7860

Could not create share link, please check your internet connection.
Startup time: 31.5s (import gradio: 2.7s, import ldm: 1.1s, other imports: 3.9s, setup codeformer: 0.2s, load scripts: 0.4s, load SD checkpoint: 18.4s, create ui: 0.2s, gradio launch: 4.5s).
```

### System Info

```shell
Gradio version: '3.16.2'
```

### Severity

blocking all usage of gradio

**Comment by freddyaboulton** [comment]
Hi @ProGamerGov ! Did this just happen? The share server went down for a couple of minutes earlier today and I want to make sure that wasn't the cause of your problem.

**Comment by ProGamerGov** [comment]
@freddyaboulton Its been happening for just over an hour now. I checked your status site and it says the server is up and running, but I'm still getting the error.

**Comment by ProGamerGov** [comment]
I just tried a simple script using gradio, and it worked:

```
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
    
demo.launch(share=True)
```

So, maybe the issue somehow lies with the [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui)

**Comment by exportio** [comment]
First time using Gradio, got this message.  The local link works.

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app

Full output

C:\Python37\lib\site-packages\gradio\inputs.py:28: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  "Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components",
C:\Python37\lib\site-packages\gradio\deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
C:\Python37\lib\site-packages\gradio\deprecation.py:40: UserWarning: `numeric` parameter is deprecated, and it has no effect
  warnings.warn(value)
C:\Python37\lib\site-packages\gradio\outputs.py:23: UserWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components
  "Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components",
C:\Python37\lib\site-packages\gradio\blocks.py:500: UserWarning: Theme should be a class loaded from gradio.themes
  warnings.warn("Theme should be a class loaded from gradio.themes")

**Comment by abidlabs** [comment]
Hi @exportio are you also using the Automatic1111 Web UI or is it with a different Gradio app? If it's with a different Gradio app, can you share the code to reproduce?

**Comment by erbill** [comment]
I am also having the same error while status page of Gradio shows servers are up. 

My code is this one;

from gpt_index import SimpleDirectoryReader, GPTListIndex, GPTSimpleVectorIndex, LLMPredictor, PromptHelper,ServiceContext
from langchain import OpenAI
import gradio as gr
import sys
import os

os.environ["OPENAI_API_KEY"] = 'XXXXXX'

def construct_index(directory_path):
    max_input_size = 4096
    num_outputs = 512
    max_chunk_overlap = 20
    chunk_size_limit = 600

    prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)

    llm_predictor = LLMPredictor(llm=OpenAI(temperature=0.7, model_name="text-davinci-003", max_tokens=num_outputs))

    documents = SimpleDirectoryReader(directory_path).load_data()

    index = GPTSimpleVectorIndex.from_documents(documents)

    index.save_to_disk('index.json')

    return index

def chatbot(input_text):
    index = GPTSimpleVectorIndex.load_from_disk('index.json')
    response = index.query(input_text, response_mode="compact")
    return response.response

iface = gr.Interface(fn=chatbot,
                     inputs=gr.inputs.Textbox(lines=7, label="Enter your text"),
                     outputs="text",
                     title="Custom-trained AI Chatbot")

index = construct_index("docs")
iface.launch(share=True)





And I get a local address but Could not create share link error. 

Can it be due to Windows 11 blocking something behind?

**Comment by pengzhiliang** [comment]
When I test the following code in the latest version (3.27), it doesn't generate the public url.
```python
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
    
demo.launch(share=True)
```
But on an older version, like 3.9, it works.

**Comment by freddyaboulton** [comment]
Hi @pengzhiliang ! There was an issue with the share links that has now been resolved!

**Comment by ishaan000** [comment]
I am still getting the same error! No links

**Comment by Egunjobi-Tunde** [comment]
Could not create share link. Please check your internet connection or our status page: https://status.gradio.app./ 
.
Has anyone found a solution to this?

**Comment by shaotiancai** [comment]
> Found a workaround. Force downgrade to 3.8 ...3.9, and the public link will show. There is something wrong/bug with the latest version of Gradio.

so great!  When I reduce the gradio version to 3.9, it can run on public URL.

**Comment by leoregino** [comment]
I had the same issue and by downgraded to 3.9 it worked like a charm

**Comment by airoura163** [comment]
gradio                  3.38.0
gradio_client           0.2.10

In my opinion, frpc_linux_amd64_v0.2 is an intranet penetration plug-in, check if the file frpc_linux_amd64_v0.2 has the executable permission, if not , run chmod +x frpc_linux_amd64_v0.2 to make it executable.
in my case, in docker environment:

`chmod +x /usr/local/lib/python3.8/dist-packages/gradio/frpc_linux_amd64_v0.2`

finally , it works.

**Comment by steven-kid** [comment]
I downgrade the gradio version to 3.9, and it works magically!🧐SOMEONE SHOULD FIX IT LOL

**Comment by DylanQiao** [comment]
> 

works for me , thx!

**Comment by MuazAshraf** [comment]
Getting this error:
Running on local URL:  http://127.0.0.1:7860

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.

Also please ensure that your antivirus or firewall is not blocking the binary file located at: /home/mojo/miniforge3/envs/textgen/lib/python3.10/site-packages/gradio/frpc_linux_aarch64_v0.2

I also tried simple gradio app to check but same 
also I tried with niginx
sudo nano /etc/nginx/sites-available/default
server {
    listen 80;
    server_name: 209.73.86.100;
location / {
        proxy_pass http://localhost:7860;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
In browser I get This site can’t be reached
127.0.0.1 refused to connect.

**Comment by MuazAshraf** [comment]
> Found a workaround. Force downgrade to 3.8 ...3.9, and the public link will show. There is something wrong/bug with the latest version of Gradio.

I downgrade the gradio version to 3.8 but when I run python server.py
I get these error:
  File "/home/mojo/text-generation-webui/server.py", line 35, in <module>
    from modules import chat, loaders, presets, shared, training, ui, utils
  File "/home/mojo/text-generation-webui/modules/chat.py", line 17, in <module>
    from modules.text_generation import (
  File "/home/mojo/text-generation-webui/modules/text_generation.py", line 22, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "/home/mojo/text-generation-webui/modules/models.py", line 23, in <module>
    from modules.models_settings import infer_loader
  File "/home/mojo/text-generation-webui/modules/models_settings.py", line 6, in <module>
    from modules import loaders, shared, ui
  File "/home/mojo/text-generation-webui/modules/ui.py", line 25, in <module>
    theme = gr.themes.Default(
AttributeError: module 'gradio' has no attribute 'themes'

**Comment by zhangsdly** [comment]
pip install gevent and it works
`pip install gevent==22.10.2`

**Comment by ts-eng** [comment]
> gradio 3.38.0 gradio_client 0.2.10
> 
> In my opinion, frpc_linux_amd64_v0.2 is an intranet penetration plug-in, check if the file frpc_linux_amd64_v0.2 has the executable permission, if not , run chmod +x frpc_linux_amd64_v0.2 to make it executable. in my case, in docker environment:
> 
> `chmod +x /usr/local/lib/python3.8/dist-packages/gradio/frpc_linux_amd64_v0.2`
> 
> finally , it works.

Works for me too! No need to downgrade gradio version!!!

**Comment by KelleyYin** [comment]
> gradio 3.38.0 gradio_client 0.2.10
> 
> In my opinion, frpc_linux_amd64_v0.2 is an intranet penetration plug-in, check if the file frpc_linux_amd64_v0.2 has the executable permission, if not , run chmod +x frpc_linux_amd64_v0.2 to make it executable. in my case, in docker environment:
> 
> `chmod +x /usr/local/lib/python3.8/dist-packages/gradio/frpc_linux_amd64_v0.2`
> 
> finally , it works.

Works for me ! 
Very Thanks !

**Comment by CaptainDoubleYou** [comment]
I started having this issue few days ago. No matter what I do I still get the same message. Windows 11 user with Python 3.10.6
I tried v1.5.2 and 1.6.0 of stable diffusion webui and I still get the same message. It just came out of nowhere. Can you help me?
I deleted venv folder and re did it and still I get the same error message.

**Comment by BurrowsWang** [comment]
> gradio 3.38.0 gradio_client 0.2.10
> 
> In my opinion, frpc_linux_amd64_v0.2 is an intranet penetration plug-in, check if the file frpc_linux_amd64_v0.2 has the executable permission, if not , run chmod +x frpc_linux_amd64_v0.2 to make it executable. in my case, in docker environment:
> 
> `chmod +x /usr/local/lib/python3.8/dist-packages/gradio/frpc_linux_amd64_v0.2`
> 
> finally , it works.

didn't work for me.

offline docker container
ubuntu 18.04
cuda 11.7 cudnn 8.5
python 3.10.9
pytorch 2.0.0

**Comment by YoucanBaby** [comment]
> chmod +x

Thanks a lot.
It works for me!!!!

**Comment by Sowhat007** [comment]
> gradio 3.38.0 gradio_client 0.2.10
> 
> In my opinion, frpc_linux_amd64_v0.2 is an intranet penetration plug-in, check if the file frpc_linux_amd64_v0.2 has the executable permission, if not , run chmod +x frpc_linux_amd64_v0.2 to make it executable. in my case, in docker environment:
> 
> `chmod +x /usr/local/lib/python3.8/dist-packages/gradio/frpc_linux_amd64_v0.2`
> 
> finally , it works.

worked for me, huge thanks!

**Comment by hoooooli** [comment]
![1704359155983](https://github.com/gradio-app/gradio/assets/62542244/ba415f72-83b4-4d7b-a4ad-2a6e6ffc24c5)
我完美解决了这个问题，按照提示与命令来就可以。

**Comment by GlucoseNacl** [comment]
> gradio 3.38.0 gradio_client 0.2.10
> 
> In my opinion, frpc_linux_amd64_v0.2 is an intranet penetration plug-in, check if the file frpc_linux_amd64_v0.2 has the executable permission, if not , run chmod +x frpc_linux_amd64_v0.2 to make it executable. in my case, in docker environment:
> 
> `chmod +x /usr/local/lib/python3.8/dist-packages/gradio/frpc_linux_amd64_v0.2`
> 
> finally , it works.

bro you are a fking genius!

**Comment by Rizzlas** [comment]
> pip install gevent and it works `pip install gevent==22.10.2`

Thank man , I was blocked for a day , find ur message , worked like a charm ! 
Thanks again

**Comment by ZayIsAllYouNeed** [comment]
> gradio 3.38.0 gradio_client 0.2.10
> 
> In my opinion, frpc_linux_amd64_v0.2 is an intranet penetration plug-in, check if the file frpc_linux_amd64_v0.2 has the executable permission, if not , run chmod +x frpc_linux_amd64_v0.2 to make it executable. in my case, in docker environment:
> 
> `chmod +x /usr/local/lib/python3.8/dist-packages/gradio/frpc_linux_amd64_v0.2`
> 
> finally , it works.

it works for me, thx!

**Comment by rattle99** [comment]
> chmod +x /usr/local/lib/python3.8/dist-packages/gradio/frpc_linux_amd64_v0.2

I think this won't work when you have gradio in a virtual environment.

**Comment by vish01** [comment]
I was having this issue on my Windows machine as well. Turns out my security guard was blocking it from creating an external server. Disabling it temporarily worked for me.

**Comment by avocardio** [comment]
> I was having this issue on my Windows machine as well. Turns out my security guard was blocking it from creating an external server. Disabling it temporarily worked for me.

What exactly did you do? Am also on win11

**Comment by Heather95** [comment]
> I was having this issue on my Windows machine as well. Turns out my security guard was blocking it from creating an external server. Disabling it temporarily worked for me.

That fixed it for me, thank you!!

> What exactly did you do? Am also on win11

- Press Windows key > Search for "Windows Security" > Open
- Press the button on "app and browser control"
- Expand the potentially unwanted app.
- Go to Actions > Allow on device
- Done! @avocardio

**Comment by Xingeqwd** [comment]
> gradio 3.38.0 gradio_client 0.2.10
> 
> In my opinion, frpc_linux_amd64_v0.2 is an intranet penetration plug-in, check if the file frpc_linux_amd64_v0.2 has the executable permission, if not , run chmod +x frpc_linux_amd64_v0.2 to make it executable. in my case, in docker environment:
> 
> `chmod +x /usr/local/lib/python3.8/dist-packages/gradio/frpc_linux_amd64_v0.2`
> 
> finally , it works.

magic man! very nice worked

**Comment by wuyw** [comment]
> > gradio 3.38.0 gradio_client 0.2.10
> > In my opinion, frpc_linux_amd64_v0.2 is an intranet penetration plug-in, check if the file frpc_linux_amd64_v0.2 has the executable permission, if not , run chmod +x frpc_linux_amd64_v0.2 to make it executable. in my case, in docker environment:
> > `chmod +x /usr/local/lib/python3.8/dist-packages/gradio/frpc_linux_amd64_v0.2`
> > finally , it works.
> 
> Works for me too! No need to downgrade gradio version!!!
works for me too!

**Comment by abalib** [comment]
> demo.launch(share=False, server_name='0.0.0.0', server_port=7860)

This works for me.  URL must start with http not https

**Comment by mcphuong1** [comment]
> pip install gevent==22.10.2

This work, Thanks bro!!! <3

**Comment by JW-Yuan** [comment]
I've tried 3 ways and didn't work for me:
`chmod +x .cache/huggingface/gradio/frpc/frpc_linux_amd64_v0.3`
`pip install gevent==22.10.2`
`demo.launch(share=False, server_name='0.0.0.0', server_port=7860)`

My script is:
```
import gradio as gr

def chat_fn(message, history):
    answer = "Your message is:" + message
    return answer
demo = gr.ChatInterface(
    fn=chat_fn,
    type="messages",
)
demo.launch(share = True)
```

and I tried it on a remote server, not locally.

**Comment by Xingeqwd** [comment]
> I've tried 3 ways and didn't work for me: `chmod +x .cache/huggingface/gradio/frpc/frpc_linux_amd64_v0.3` `pip install gevent==22.10.2` `demo.launch(share=False, server_name='0.0.0.0', server_port=7860)`
> 
> My script is:
> 
> ```
> import gradio as gr
> 
> def chat_fn(message, history):
>     answer = "Your message is:" + message
>     return answer
> demo = gr.ChatInterface(
>     fn=chat_fn,
>     type="messages",
> )
> demo.launch(share = True)
> ```
> 
> and I tried it on a remote server, not locally.

try to execute 
export no_proxy=localhost,127.0.0.1,192.168.1.1(for example, put your ip here on 192.168.1.1)
before execute python script (for linux)

**Comment by Skyyang0919** [comment]
> 我尝试了三种方法但都没有用： `chmod +x .cache/huggingface/gradio/frpc/frpc_linux_amd64_v0.3` `pip install gevent==22.10.2` `demo.launch(share=False, server_name='0.0.0.0', server_port=7860)`
> 
> 我的脚本是：
> 
> ```
> import gradio as gr
> 
> def chat_fn(message, history):
>     answer = "Your message is:" + message
>     return answer
> demo = gr.ChatInterface(
>     fn=chat_fn,
>     type="messages",
> )
> demo.launch(share = True)
> ```
> 
> 我在远程服务器上尝试过，而不是在本地。

me too
