### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'then'

### ISSUE THREAD

**Issue by arditobryan** [gradio-app/gradio#3501]
### Describe the bug

I am trying to recreate a chatbot using the following tutorial on the official documentation:
https://gradio.app/creating-a-chatbot/#introduction

I am getting the following error:
AttributeError: 'dict' object has no attribute 'then'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.Button("Clear")

    def user(user_message, history):
        return "", history + [[user_message, None]]

    def bot(history):
        bot_message = random.choice(["Yes", "No"])
        history[-1][1] = bot_message
        time.sleep(1)
        return history

    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        bot, chatbot, chatbot
    )
    clear.click(lambda: None, None, chatbot, queue=False)

demo.launch()

### Screenshot

_No response_

### Logs

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
d:\_projects\_personal\Projects_work\230318_Ibrahim\gradio_gpt3.ipynb Cell 1 in 1
     16         time.sleep(1)
     17         return history
---> 19     msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
     20         bot, chatbot, chatbot
     21     )
     22     clear.click(lambda: None, None, chatbot, queue=False)
     24 demo.launch()

AttributeError: 'dict' object has no attribute 'then'
```

### System Info

```shell
gradio==3.21.0
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @arditobryan are you sure you are using `gradio==3.21.0`? The `submit()` function used to return dictionaries before `3.21.0` but now returns an object that supports the `.then()` method. 

You can see a fully working example here: https://colab.research.google.com/drive/1DdHjfqPSDICUWuPUP2j32M2lFFyxbQj2#scrollTo=GHeGttNzJ6OK

**Comment by abidlabs** [comment]
Will close since I'm pretty sure that this is a versioning issue @arditobryan but feel free to reopen if this continues to be an issue even after you upgrade to the latest version of gradio. Thanks!
