### ISSUE TITLE
Failed to access localhost when set to share=False under WSL2

### ISSUE THREAD

**Issue by Starlento** [gradio-app/gradio#3512]
### Describe the bug

gradio == 3.18.0, Under WSL2:
set share=False, it outputs `ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True.`.
But set share=True. It successfully runs on `127.0.0.1:7860` and `.gradio.live`.
I also checked `jupyter notebook` with the same environment, it works.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

``` python
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
    
demo.launch(share=False)
```

### Logs

```shell
Traceback (most recent call last):
  File "/mnt/d/open_source_linux/text-generation-webui/demo.py", line 8, in <module>
    demo.launch(share=False)
  File "/home/starlento/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1444, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True.
```

### System Info

```shell
3.18.0
Win11, wsl2 Ubuntu22.04
```

### Severity

annoying

**Comment by Starlento** [comment]
I found it is caused by a proxy setting which I recently changed V2RAY setting from China mainland blacklist to global.
But it is still werid that it is trying to acess the proxy when share=False.
In other words, if jupyter notebook can work, gradio should work as well... And when share=True can post to localhost, share=False cannot is also werid.

**Comment by abidlabs** [comment]
Hi @Starlento circling back to this -- is this still an issue with the latest version of Gradio (3.27)?

**Comment by abidlabs** [comment]
Closing for lack of follow up
