### ISSUE TITLE
Allow setting `share=True` with an environment variable

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#3513]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

People sometimes ask how to run a gradio demo that is running on HF Spaces in Google Colab. When running a gradio demo script on Colab, we need to set `.launch(share=True)`, but it's a bit bothersome to open `app.py` and modify it. I think it would be easier if we could do something like
```bash
GRADIO_SHARE=True python app.py
```

**Comment by abidlabs** [comment]
Technically you don't need to set `share=True` anymore. Unless queuing is involved (in which case, `share=True` is set automatically). Am I misunderstanding something?

**Comment by hysts** [comment]
Oh, I see. I was thinking of opening this issue a few weeks ago and just did, but it's already been solved while I forgot about it. Thanks!

**Comment by abidlabs** [comment]
No worries, thanks!

**Comment by hysts** [comment]
@abidlabs Sorry, but I actually don't understand what you mean. I ran the following on Google Colab, and it seems that we still need to specify `share=True` with `gradio==3.22.1`. Is it not the way to launch an app on Colab? And is there a way to use it without modifying the `app.py`?
```
!git clone https://huggingface.co/spaces/hysts-debug/gradio-issue-3513
%cd gradio-issue-3513
!pip install -q -r requirements.txt
!python app.py
```
![](https://user-images.githubusercontent.com/25161192/226221249-4d768edd-3205-4c73-9b1f-a95a7c12c502.png)

**Comment by abidlabs** [comment]
If you click on the localhost link it should now work, even in Colab

**Comment by hysts** [comment]
It doesn't seem to work for me. But so, is it an issue of my local environment, then?

![](https://user-images.githubusercontent.com/25161192/226221951-49bbf3d3-4c90-49a6-b158-4377f5fba28f.png)

**Comment by abidlabs** [comment]
Hmm let me take a look

**Comment by abidlabs** [comment]
Can you try running a simple gradio app like:

```py
import gradio as gr

gr.Interface(lambda x:x, "textbox", "textbox").launch()
```

and see if that works for you on Colab with localhost?

**Comment by abidlabs** [comment]
Ok so if I copy-paste your code directly into Colab:

```py
#!/usr/bin/env python

import gradio as gr

with gr.Blocks() as demo:
    text = gr.Text()
demo.queue(api_open=False).launch()
```

But it looks like when you run `!python app.py`, it doesn't detect that it's in a Colab environment so it doesn't create the share link

**Comment by hysts** [comment]
Ohh, I see! So, we should launch the app by doing `import app` in a cell, instead of doing `!python app.py`.

![](https://user-images.githubusercontent.com/25161192/226222381-d06240b8-edf0-4926-a804-e6603542e9d6.png)

It's kind of unexpected way to do it, but it seems working. Thanks!

**Comment by abidlabs** [comment]
Oh cool, I was going to suggest we add in an environmental variable to manually force a Colab environment, but if this working for you, then we can stick with this solution.
