### ISSUE TITLE
"issubclass() arg 1 must be a class" error appears when using input parameters with Optional type hint

### ISSUE THREAD

**Issue by dbalabka** [gradio-app/gradio#3514]
### Describe the bug

I'm getting an error `issubclass() arg 1 must be a class` when using Optional typing in the target function. The problem started appearing with version `3.21.0`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Steps to reproduce:
1. Install gradio `3.21.0`
2. Target function with the following type hints:
```
def transcribe(
        language: Optional[str] = 'auto',
):
```
3. Run gradio application

AR:
```
  File ".../app.py", line 67, in <module>
    allow_flagging='never',
  File ".../.venv/lib/python3.7/site-packages/gradio/interface.py", line 463, in __init__
    self.attach_submit_events(submit_btn, stop_btn)
  File ".../.venv/lib/python3.7/site-packages/gradio/interface.py", line 624, in attach_submit_events
    postprocess=not (self.api_mode),
  File ".../.venv/lib/python3.7/site-packages/gradio/events.py", line 147, in __call__
    trigger_only_on_success=self.trigger_only_on_success,
  File ".../.venv/lib/python3.7/site-packages/gradio/blocks.py", line 190, in set_event_trigger
    check_function_inputs_match(fn, inputs, inputs_as_dict)
  File ".../.venv/lib/python3.7/site-packages/gradio/utils.py", line 943, in check_function_inputs_match
    if not is_special_typed_parameter(name):
  File ".../.venv/lib/python3.7/site-packages/gradio/utils.py", line 932, in is_special_typed_parameter
    is_event_data = issubclass(parameter_types.get(name, int), EventData)
TypeError: issubclass() arg 1 must be a class
```

The problem is that the first parameter for `issubclass` is `typing.Union[str, NoneType]`

### Logs

_Stacktrace is attached in the reproduction steps._

### System Info

```shell
Gradio 3.21.0, Python 3.7
```

### Severity

serious, but I can work around it by removing annotations

**Comment by hnsywangxin** [comment]
change version can solve it

**Comment by doevent** [comment]
> @hnsywangxin , I didn't try to downgrade the version. The simpler way was to remove type annotations.

Same, removing the annotations solved.

**Comment by roy-pstr** [comment]
I'm having the same problem. It is a more generic problem than you described.

For me it happens with the following code:

```
def from_raw(raw_pdf: Union[str, bytes]) -> str:
...

pdf_file.upload(from_raw, inputs=[file], outputs=[text])
```

It seems like gradio events can not handle type annotations with the `fn` arguments.

This should be fixed.

**Comment by JonathanLehner** [comment]
annoying

**Comment by JonathanLehner** [comment]
thanks for your advice, removing type annotations fixed it for me too

**Comment by freddyaboulton** [comment]
Will take a look and get a fix out this week!

**Comment by roca77** [comment]
I am still running into the same issue:

> `File "/home/ytraore/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/utils.py", line 861, in is_special_typed_parameter

    is_event_data = issubclass(parameter_types.get(name, int), EventData)`

**Comment by gruberdev** [comment]
> I am still running into the same issue:
> 
> ```
> File "/home/ytraore/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/utils.py", line 861, in is_special_typed_parameter
> is_event_data = issubclass(parameter_types.get(name, int), EventData)
> ```

Try using Gradio 3.29.0, this issue persisted until Gradio 3.28.3, but since upgrading to the latest version I doid not have problems anymore.

**Comment by abidlabs** [comment]
@steysie I believe this PR should fix it: https://github.com/gradio-app/gradio/pull/4228

Feel free to try it out (`pip install https://github.com/gradio-app/gradio/issues/https://gradio-builds.s3.amazonaws.com/8ed82ac2fdc0597e91eb3403fa08f1c0c6049550/gradio-3.30.0-py3-none-any.whl`) and let us know if it works for you
