### ISSUE TITLE
`gr.Dropdown`'s default size is much too small

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3530]
### Describe the bug

Before newer versions of Gradio I could fit dozens of items on the screen with `gr.Dropdown`, now it seems the default only permits 3 items on the screen at a time

I'm wondering if this should be configurable? Of course I can use user CSS but it comes out as an autogenerated Svelte class (`ul.options.svelte-1setfeu`) so I don't know if it's going to break with newer Gradio versions or not, plus I want to apply the style to all dropdowns so `elem_id` is of limited usefulness here

Old:

<img width="238" alt="2023-03-19 23_53_34-Stable Diffusion - Chromium" src="https://user-images.githubusercontent.com/24979496/226242716-f849c9ac-c6ea-4fc6-9456-5ed983d0793e.png">

New:

<img width="215" alt="2023-03-19 23_51_16-Stable Diffusion - Chromium" src="https://user-images.githubusercontent.com/24979496/226242727-60fcb522-cfd6-47bc-88b5-9cd61f79731c.png">

New with `--size-96` instead of `--size-32`:

<img width="227" alt="2023-03-19 23_51_32-Stable Diffusion - Chromium" src="https://user-images.githubusercontent.com/24979496/226242748-42cdf4c9-0f0a-4d53-9009-5185e71c6b8c.png">

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Add `gr.Dropdown` with a lot of elements

### Logs

```shell
N/A
```

### System Info

```shell
Gradio 3.22.1, Windows, Chromium
```

### Severity

annoying

**Comment by aliabid94** [comment]
on it, thanks

**Comment by umarbutler** [comment]
@aliabid94 Is it possible to limit the number of items shown in a dropdown? I have the reverse problem, too many items being shown, I'd like to limit to a number I can specify.
