### ISSUE TITLE
`gr.Chatbot` does not display code blocks correctly

### ISSUE THREAD

**Issue by FrankWhh** [gradio-app/gradio#3531]
### Describe the bug

I just use gr.chatbot component to service as chat demo，and i find that it can keep code string style.
the markdown_it.renderInline remove the ‘\n’.
https://github.com/gradio-app/gradio/blob/8ec2b0b98a2501850112e63818d1e4ec36fcb71c/gradio/components.py#L4152

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://github.com/gradio-app/gradio/blob/8ec2b0b98a2501850112e63818d1e4ec36fcb71c/gradio/components.py#L4152

### Logs

```shell
it's logic error
```

### System Info

```shell
gradio==3.20.1
```

### Severity

annoying

**Comment by aliabid94** [comment]
on it

**Comment by FrankWhh** [comment]
it show like this:

python def quick_sort(arr): if len(arr) <= 1: return arr else: pivot = arr[0] left = [] right = [] for i in range(1, len(arr)): if arr[i] < pivot: left.append(arr[i]) else: right.append(arr[i]) return quick_sort(left) + [pivot] + quick_sort(right)

**Comment by tonny008** [comment]
`gradio==3.22.1`
```python
self.md.renderInline("test \n\n test") 
```
produces:
test<br>\n<br>\ntest

if the chat history having a line break, it will keep adding <br>s as the conversation goes on

**Comment by FrankWhh** [comment]
“I initially thought that this function (self.md.renderInline) caused this problem. but with Textbox component，python code display ok. It seems that the difference between them causes this. 
**chatbot:**
`<code>python def quick_sort(arr):     if len(arr) &lt;= 1:         return arr     else:         pivot = arr[0]         left = []         right = []         for i in range(1, len(arr)):             if arr[i] &lt; pivot:                 left.append(arr[i])             else:                 right.append(arr[i])         return quick_sort(left) + [pivot] + quick_sort(right) </code>`
**textbox:**
```
<code>def quicksort(arr):
    if len(arr) &lt;= 1:
        return arr
    else:
        pivot = arr[0]
        left = []
        right = []
        for i in range(1, len(arr)):
            if arr[i] &lt; pivot:
                left.append(arr[i])
            else:
                right.append(arr[i])
        return quicksort(left) + [pivot] + quicksort(right)
</code>
```

**Comment by FrankWhh** [comment]
Maybe the cause is UI

**Comment by tonny008** [comment]
```python
self.md.renderInline("```\ntest \n\n test\n```") 
```
produces:
```
"<code>test    test</code>"
```

**Comment by FrankWhh** [comment]
yeah. Indent is essential for Python！Skip `self.md.renderInline`, display still abnormal.

**Comment by tonny008** [comment]
i changed renderInline to render, anyway i want to render full feature markdown in chatbot

**Comment by remiliacn** [comment]
+1 for full feature markdown in chatbot.

**Comment by FrankWhh** [comment]
yeah, I also want this. But haven't you meet "code format display abnormal" probelm  in chatbot?

**Comment by tonny008** [comment]
nope. 

if you use render, it will include block element in md. all code will included in <pre>. don't forget to apply 'prose' css to chatbot. elem_classses="prose"

no syntax highlight though.

***
i think better to keep the md render at client side. thus when use chatbot both as input and output, the value will always be markdown. currently if you output md to chatbot you will get rendered html when you use it in input

**Comment by FrankWhh** [comment]
I find a solution to fix this. Let result returns from LLM firstly get parse.
`def parse_codeblock(text):
    lines = text.split("\n")
    for i, line in enumerate(lines):
        if "```" in line:
            if line != "```":
                lines[i] = f'<pre><code class="{lines[i][3:]}">'
            else:
                lines[i] = '</code></pre>'
        else:
            if i > 0:
                lines[i] = "<br/>" + line.replace("<", "&lt;").replace(">", "&gt;")
    return "".join(lines)`

**Comment by FrankWhh** [comment]
I find a solution to fix this. Let result returns from LLM firstly get parse.
```
def parse_codeblock(text):
    lines = text.split("\n")
    for i, line in enumerate(lines):
        if "```" in line:
            if line != "```":
                lines[i] = f'<pre><code class="{lines[i][3:]}">'
            else:
                lines[i] = '</code></pre>'
        else:
            if i > 0:
                lines[i] = "<br/>" + line.replace("<", "&lt;").replace(">", "&gt;")
    return "".join(lines)
```

**Comment by atodniAr** [comment]
> I find a solution to fix this. Let result returns from LLM firstly get parse.

In my case this workaround fix both the code block issue and strange <br> self incremental issue.

**Comment by LZY-the-boys** [comment]
it cannot handle the `__init__` ， which will be changed to **init**

**Comment by markwsac** [comment]
+1 for this in chatbot.

**Comment by markwsac** [comment]
Fastchat has patch of this issue - https://github.com/lm-sys/FastChat/blob/main/fastchat/serve/gradio_patch.py

**Comment by dawoodkhan82** [comment]
@FrankWhh Can you confirm this pr #3816 fixes your issue?

**Comment by txy6666yr** [comment]
@abidlabs  sir，this bug didn't fixed ....
---------------------
gradio-4.4.0 
gradio-client-0.7.0
----------------------
code:
```
def test():
    print(gr.__version__)
    with gr.Blocks() as demo:
        chatbot = gr.Chatbot()
        msg = gr.Textbox()
        # clear = gr.ClearButton([msg, chatbot])

        def respond(message, chat_history):
            bot_message = '''
```python
def bubble_sort(arr):
    n = len(arr)
    # 遍历数组
    for i in range(n):
        # 遍历每个元素，判断是否比下一个元素大，如果是则交换
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
        # 如果在一次遍历中没有交换元素，说明数组已经排序完成，可以提前结束
        if i == n-1:
            break
    return arr

# 测试
arr = [64, 34, 25, 12, 22, 11, 90]
print("原数组：", arr)
bubble_sort(arr)
print("排序后的数组：", arr)
```
'''
            chat_history.append((message, bot_message))
            time.sleep(2)
            return "", chat_history

        msg.submit(respond, [msg, chatbot], [msg, chatbot])
    demo.launch()
```
output：
```python def bubble_sort(arr): n = len(arr) # 遍历数组 for i in range(n): # 遍历每个元素，判断是否比下一个元素大，如果是则交换 for j in range(0, n-i-1): if arr[j] > arr[j+1]: arr[j], arr[j+1] = arr[j+1], arr[j] # 如果在一次遍历中没有交换元素，说明数组已经排序完成，可以提前结束 if i == n-1: break return arr

测试
arr = [64, 34, 25, 12, 22, 11, 90] print("原数组：", arr) bubble_sort(arr) print("排序后的数组：", arr) ```
