### ISSUE TITLE
`gr.Dropdown` doesn't close when clicked on twice

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3532]
### Describe the bug

Unlike with Gradio 3.16 I can't click on a `gr.Dropdown` twice to toggle it on and off, it always remains open until I click outside the dropdown

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Create `gr.Dropdown`
2. Click the dropdown twice

### Logs

```shell
N/A
```

### System Info

```shell
Gradio 3.22.1, Windows, Chromium
```

### Severity

annoying

**Comment by aliabid94** [comment]
taking this

**Comment by aliabid94** [comment]
Tackled most of your dropdown issues @space-nuko in https://github.com/gradio-app/gradio/pull/3549. Demo GIF there, lemme know if it looks good!
Appreciate all the issues and contributions btw, would love to chat more on how you've been using gradio and what could be better @space-nuko, if you have time please do message me at aliabid94@gmail.com.
