### ISSUE TITLE
`gr.Dropdown` can cause X overflow/ugly scrollbars

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3533]
### Describe the bug

Unlike old versions of Gradio the new dropdown can cause X overflow even though it's kinda pointless to scroll in the X direction

<img width="179" alt="2023-03-20 00_08_41-Stable Diffusion - Chromium" src="https://user-images.githubusercontent.com/24979496/226245133-21e67635-95b4-456b-b887-c37e7975c1d2.png">

Compare with the old version, even when squeezed the width of the list adjusts itself so all the items are visible:

<img width="126" alt="2023-03-20 00_10_26-Stable Diffusion - Chromium" src="https://user-images.githubusercontent.com/24979496/226245287-2257e820-3125-4b4a-9d7b-c782d7456e1e.png">

Same happens when the list is closed, the old version just cuts off the text while the new version's text can overflow the box in some cases:

<img width="184" alt="2023-03-20 00_12_59-Stable Diffusion - Chromium" src="https://user-images.githubusercontent.com/24979496/226245566-9958679a-5adb-42fb-999c-d9c957cd413b.png">

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Create `gr.Dropdown` with elements having large names
2. Reduce width of the browser window so the names overflow

### Logs

```shell
N/A
```

### System Info

```shell
3.22.1, Windows, Chromium
```

### Severity

annoying

**Comment by aliabid94** [comment]
looking into this, thanks @space-nuko!

**Comment by space-nuko** [comment]
Think this is still an issue as of `3.23.0`:

```
#!/usr/bin/env python

import gradio as gr

with gr.Blocks() as demo:
    with gr.Row():
        for _ in range(5):
            gr.Dropdown(choices=["foobarbaz" * 10] * 10)

demo.queue(concurrency_count=20).launch(server_port=9876)
```

3.23.0:
<img width="228" alt="2023-03-21 18_35_59-Gradio - Chromium" src="https://user-images.githubusercontent.com/24979496/226757636-2313e3e3-e885-4765-b1c5-56f56b4bcbfe.png">

3.16.2:
<img width="490" alt="2023-03-21 18_39_10-Gradio - Chromium" src="https://user-images.githubusercontent.com/24979496/226757658-48f34059-46d4-4a53-a67c-0ec4854cdf40.png">

**Comment by space-nuko** [comment]
Could this CSS be integrated? https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8959

**Comment by space-nuko** [comment]
Also look https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8955

**Comment by abidlabs** [comment]
cc @aliabid94
