### ISSUE TITLE
When I upload a video , It didn't show 

### ISSUE THREAD

**Issue by 459737087** [gradio-app/gradio#3537]
### Describe the bug

it only show the predict video,

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr
import os
# import torch
import cv2

def mirror(x):
    return x

    
with gr.Blocks() as demo:
    with gr.Row():
        vi = gr.Video()
        vi_2 = gr.Video()
    
    btn = gr.Button(value="预测视频")
    btn.click(mirror, inputs=[vi], outputs=[vi_2])

if __name__ == "__main__":
    demo.launch()
    ```

### Screenshot

![image](https://user-images.githubusercontent.com/54131759/226283667-2f77abf0-8050-4972-aa6f-bfbac72205bd.png)

### Logs

```shell
no error
```

### System Info

```shell
gradio 3.20.0
ubuntu 20.0
python 3.8.0
tensorflow 2.8
```

### Severity

annoying

**Comment by pngwn** [comment]
Can you attach the video you uploaded as well please?

**Comment by 459737087** [comment]
https://user-images.githubusercontent.com/54131759/226537155-8e9d7027-eb63-411e-a556-7aed30384461.mov



@pngwn

**Comment by freddyaboulton** [comment]
Can you convert the video to `mp4` and try again? I don't think the html video player supports .mov files: https://www.geeksforgeeks.org/what-are-different-video-formats-supported-by-browsers-in-html/

**Comment by abidlabs** [comment]
Thanks, it looks like that was the issue. Closing this issue now. @459737087 feel free to reopen if you still think that there is a Gradio issue here.

**Comment by yangli-lab** [comment]
I meet the same question, and the video I uploaded is `.mp4` format. Have you solved the problem @459737087 ? Thanks a lot.

**Comment by BupyeongHealer** [comment]
Hi, all and @yangli-lab,
It seems that I'm having trouble uploading a video with the .mp4 extension in 1920x1080 resolution. 
Instead of the video, only a black screen appears. 
Do you know how to resolve this issue?

**Comment by curieuxjy** [comment]
I had the same issue with `1280 × 720` resolution mp4 video! If there is any solution, let me help.

**Comment by hlnull** [comment]
I met the same problem and solved it by following this article.

> https://rockyshikoku.medium.com/use-h264-codec-with-cv2-videowriter-e00145ded181

Step1:
```
pip uninstall opencv-python
sudo apt install build-essential cmake git python3-dev python3-numpy \
libavcodec-dev libavformat-dev libswscale-dev \
libgstreamer-plugins-base1.0-dev \
libgstreamer1.0-dev libgtk-3-dev \
libpng-dev libjpeg-dev libopenexr-dev libtiff-dev libwebp-dev \
libopencv-dev x264 libx264-dev libssl-dev ffmpeg
```

step2:
```
python -m pip install --no-binary opencv-python opencv-python
```

**Comment by scotgopal** [comment]
> I met the same problem and solved it by following this article.
> 
> > https://rockyshikoku.medium.com/use-h264-codec-with-cv2-videowriter-e00145ded181
> 
> Step1:
> 
> ```
> pip uninstall opencv-python
> ```
> 
> step2:
> 
> ```
> sudo apt install build-essential cmake git python3-dev python3-numpy \
> libavcodec-dev libavformat-dev libswscale-dev \
> libgstreamer-plugins-base1.0-dev \
> libgstreamer1.0-dev libgtk-3-dev \
> libpng-dev libjpeg-dev libopenexr-dev libtiff-dev libwebp-dev \
> libopencv-dev x264 libx264-dev libssl-dev ffmpeg
> ```
> 
> step3:
> 
> ```
> python -m pip install --no-binary opencv-python opencv-python
> ```

Haven't tested this solution, but I would like to offer an alternative that worked for me.

`sudo apt install ffmpeg`

Having this tool available, made gradio able to render the video. I presume there is a functionality under the hood of gradio.Video that automatically does the conversion of .mp4 videos from `mp4v` to `h264`.
