### ISSUE TITLE
Embedding an app with authentication does not work

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#3546]
>  @aliabid94 Like I said before, this works great locally!
> 
> However, I noticed that embedding with auth doesn't work as of this PR of 3.22.1. You can test with 
> 
> ```html
> 
> <script
> 	type="module"
> 	src="https://gradio.s3-us-west-2.amazonaws.com/3.22.1/gradio.js"
> ></script>
> 
> 
> <div>
>     <gradio-app space="gradio/hello_login"></gradio-app>
> </div>
> ```
> 
> It's trying to fetch the config, but it can't since it's not authenticated, hence the error.
> 
> ![image](https://user-images.githubusercontent.com/41651716/226422663-ffbf3d55-3c10-4a99-9bb1-89a9136c3149.png)
> 
> Fine with me if we decide to tackle that in a separate PR but we should fix prior to next release cc @pngwn

_Originally posted by @freddyaboulton in https://github.com/gradio-app/gradio/issues/3529#issuecomment-1476668921_

**Comment by KMFODA** [comment]
Hey @freddyaboulton. Was wondering if anyone from the gradio team was planning on working on this anytime soon? When I embed my gradio space in my website with Authentication the screen never goes beyond the login screen. When I enter the correct username and password and click log in the app just refreshes back to the log in screnn.

**Comment by abidlabs** [comment]
Hi @KMFODA have you tried embedding with iframes? I believe they should support authentication: https://gradio.app/sharing-your-app/#embedding-with-iframes

**Comment by KMFODA** [comment]
Hey, apologies for the delayed response. Embedding with iframe does fix this. Thanks!

**Comment by RTae** [comment]
Any updated ? my team also face this issue

**Comment by freddyaboulton** [comment]
Have you tried embedding with an iframe @RTae ?

**Comment by RTae** [comment]
@freddyaboulton Yeah, I already tried it, and it had the same result. Iframe couldn't pass my access token into file CSS and JS file path when it accessed this file, which caused **401**

**Comment by freddyaboulton** [comment]
I don't think this is possible due to the cookie-based authentication used. Will close since I don't think we will change our simple auth mechanism.
