### ISSUE TITLE
Allow event handlers to send user-specified progress updates

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3547]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
The default progress bar when a component is changing doesn't seem very helpful as it just appears to be a default CSS transition. It would be better if the backend could send its own progress updates through the websocket so the progress updates more precisely.

For example:
- Showing the number of files scanned
- Displaying progress "phases" like: loading weights from disk, deserializing, reading metadata, etc.

**Describe the solution you'd like**  
Event handlers can send progress updates targeting one of their input components somehow

**Additional context**  
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8651

**Comment by abidlabs** [comment]
Thanks @space-nuko -- have you seen `gr.Progress`? It allows you to create a custom Progress bar for exactly these use cases: https://gradio.app/key-features/#progress-bars

Among other things, it supports displaying custom text for different phases as well as the ability to bind to tqdm inside of your function. More documentation: https://gradio.app/docs/#progress

I'll close this issue as I'm pretty sure this should work for you, but feel free to reopen if I'm missing something!
