### ISSUE TITLE
Can't focus `gr.Code` if there's extra space after empty code lines

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3551]
### Describe the bug

I can't click on the extra space not covered by the code lines with `gr.Code` to focus it, I have to click within the area delineated by the blue rectangle instead

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
#!/usr/bin/env python

import gradio as gr


with gr.Blocks() as demo:
    with gr.Row():
        gr.Textbox("Focus me", interactive=True)
    with gr.Row():
        gr.Code("a = 42", language="python", interactive=True)
        gr.HTML("test<br>" * 40)


demo.queue().launch(server_port=9876)
```

### Screenshot

<img width="864" alt="2023-03-20 17_15_15-Stable Diffusion — Firefox Developer Edition" src="https://user-images.githubusercontent.com/24979496/226468155-91faa640-bf9d-42b4-b7ce-d2c9f08cda3a.png">

### Logs

```shell
N/A
```

### System Info

```shell
4.22.1, Windows, Firefox Nightly
```

### Severity

annoying

**Comment by abidlabs** [comment]
Sorry having a little trouble understanding this issue @space-nuko. Can you attach a code snippet or a GIF to help understand what the issue is? For what it's worth, I tried running this:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Code("""
    def print(x):
      pass
      
      
      
    """, interactive=True)
    
demo.launch()
```

And I'm not having any issue focusing on the `gr.Code` component: 

<img width="609" alt="image" src="https://user-images.githubusercontent.com/1778297/226484269-77fca5f4-dc6a-4772-a1b7-2d817c3e02f1.png">

**Comment by space-nuko** [comment]
Added a demo, the problem happens when you have two columns with a very tall height, `gr.Code` has a lot of blank space

**Comment by abidlabs** [comment]
Oh I see the issue now. For future reference:

![image](https://user-images.githubusercontent.com/1778297/227567112-592fdd9b-1fbd-475d-a368-300f11a2c095.png)
