### ISSUE TITLE
Strip extra indentation / blank lines in `gr.Code.postprocess()`

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#3552]
When people pass in a Python block string into the value of `gr.Code`, it often includes extra indentation or blank lines. We should strip this, similar to how we do for `Markdown`, etc. 

Came up while reviewing #3550

> The code is showing up with extra indentation, as well as an empty line at the top: 

<img width="386" alt="image" src="https://user-images.githubusercontent.com/1778297/226476219-5c5e6c9c-216c-47ef-b5cc-1b2244c93325.png">

**Comment by abidlabs** [comment]
Yup @freddyaboulton I created an issue for that here: #3467

**Comment by freddyaboulton** [comment]
Thanks for linking that issue - completely missed it! Glad I didn't file a new issue 😄

**Comment by abidlabs** [comment]
Haha yea no problem!
