### ISSUE TITLE
Document `gr.State()` deepcopying its argument

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3558]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I didn't expect `gr.State()` to run `deepcopy` on the argument you pass to its constructor. I initially found this out from compiling a flamegraph for this extension and noticing a large spike in the constructor, where an entire Gradio component was passed to `gr.State`. But just the `elem_id` of the component was used later when it was passed to the event handler, it seems this was unintentional/unnecessary

https://github.com/Mikubill/sd-webui-controlnet/pull/644

Should this be documented anywhere? And should it be necessary to `deepcopy` the argument in the first place?

**Comment by abidlabs** [comment]
The reason we do this is because if, say, a list is passed in as the initial value of `gr.State`, and the state is modified by one user, we wouldn't want that to affect the `gr.State` of other users. Agreed that this should be documented.
