### ISSUE TITLE
Remaining blockers for Python client

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#3565]
From #3300, here are the remaining TODOs for the Gradio Python client:

**Necessary**

- [x] add a changelog for the client library -- @abidlabs 
- [x] add to view API page -- @aliabd 
- [x] Files should be uploaded via /upload -- @freddyaboulton 
- [x] Add a Guide for using the python client -- @abidlabs & @aliabd 
- [ ] rate limit public Spaces, and display a meaningful error when rate limited (ideally saying something like you can duplicate this Space and make it private to avoid being rate limited)
- [x] add documentation for this on the website (@aliabd)
- [x] add support for iterators -- right now iterators return a meaningless update as a result @freddyaboulton 
- [x] add a way to get the status of a job @freddyaboulton 
- [x] add ability to inspect and quick get an idea of how to use each of the API endpoints for a given gradio app, including unnamed endpoints
- [x] add more tests @freddyaboulton 
- [x] add to the changelog
- [x] clarify that callbacks are executed sequentially
- [x] Session management / a method to reset session
- [x] add new version release GH action
- [x] add analytics
- [x] Document that the HF token is pulled if you are logged in via HF CLI
- [x] `__repr__` returns error
- ~Support passing in images as numpy arrays / pil images (note: I don't think we should do this in the client)~ 
- ~Paths to files / images are confusing. Can we display them instead?~ 
- [x] "/predict" instead of "predict"
- [x] we shouldn't assume fn_index=0

**Comment by abidlabs** [comment]
Thank you so much @freddyaboulton!

**Comment by freddyaboulton** [comment]
We should add a CHANGELOG for the clients, no?

**Comment by abidlabs** [comment]
👍 sounds good, added to the list

**Comment by pngwn** [comment]
JS client already has one, fully automated: https://github.com/gradio-app/gradio/blob/8eec0541b281c1adb968b8100c0d7d16d7eab1a2/client/js/CHANGELOG.md

**Comment by freddyaboulton** [comment]
@abidlabs Is support for spaces with auth on the roadmap?

**Comment by abidlabs** [comment]
Yes let's create a separate issue for that and the other nice-to-haves because they are not blockers to launch (I can create the issues)

**Comment by abidlabs** [comment]
Everything except rate limiting is complete, congrats everyone 🥳

Will close since rate limiting is a moon-landing issue, not a gradio issue

**Comment by justinzyw** [comment]
> @abidlabs Is support for spaces with auth on the roadmap?

+1
