### ISSUE TITLE
`UploadButton()` doesn't pass a data URL to javascript anymore

### ISSUE THREAD

**Issue by missionfloyd** [gradio-app/gradio#3569]
### Describe the bug

In 3.16.2, when passing the value of an `UploadButton()` to javascript, the `data` property contained a base64 data URL. Now, `data` is empty and the file is passed as a blob instead.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction
```python
import gradio as gr

with gr.Blocks() as demo:
    uploadBtn = gr.UploadButton(type="image")
    uploadBtn.upload(fn=None, inputs=uploadBtn, outputs=None, _js='(file) => { console.log(file) }')

demo.launch()
```

### Logs

```json
{
    "name": "C:\\Users\\Chris\\AppData\\Local\\Temp\\tmpukdy1gkw\\10825650cc978a8d84da872d6e88b92dd091d87a\\001.JPG",
    "size": 274762,
    "data": "",
    "blob": {},
    "orig_name": "001.JPG",
    "is_file": true
}
```

### System Info

```shell
Gradio 3.32
Windows 10
Edge 111.0.1661.44
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @missionfloyd ! 

Yes, this is intended. Base64 representation didn't scale well for large files so we upload files to the server and pass the filepath in the front-end now.
