### ISSUE TITLE
Screenshot doesn't capture the whole page if it exceeds the standard limit

### ISSUE THREAD

**Issue by shubham-goel-zefr** [gradio-app/gradio#357]
If the vertical length of the app is greater than the standard display size, the screenshot button only captures what's currently in frame. I'm not sure if it's by design, but a) either it should capture the whole page b) provide an option to select the current portion/whole page.

**Comment by abidlabs** [comment]
Thanks for bringing this to our attention, Shubham. Can you include an example screenshot so we know what behavior you're experiencing?

**Comment by abidlabs** [comment]
Closing as we have just eliminated the screenshot button in the latest version of Gradio on `master`. We'll be releasing to pypi next week.
