### ISSUE TITLE
Support generator functions as `fn` in `gr.Example`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#3570]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

When using `gr.Examples` with `cache_examples=True`, it will run the function specified with `fn=`, but it doesn't support generator functions.
I know there's a pretty simple workaround. We can just prepare a function that returns the last element of the generator function we want to apply and pass it to `fn` instead of the original generator function.
```python
def process_example(args):
    for x in generator_fn(args):
        pass
    return x
```

But the gradio feature to support generator functions as usual run callback is mainly for slow processes that can return intermediate results, and people want to cache examples for slow processes. So, I think it makes a lot sense to support it on gradio side.

**Comment by hysts** [comment]
@abidlabs Thanks for the reply. I'm not sure if I follow what you mean.
I think it's just a bug on users' side to set an infinite generator for `fn` in `gr.Examples` with `cache_examples=True`. If users want to use infinite generator with `gr.Examples` for some reasons, they simply shouldn't set `cache_examples=True` because pre-computing examples and caching their results doesn't make sense for infinite generator.
To make it easier for users to notice it, maybe gradio can just show log messages that tell the start and end of each pre-computation of examples. With such logs, users can notice that something went wrong while processing the first example and that their function didn't terminate.
Also, I think users set `fn` and `cache_examples=True` at the very last stage of their development and probably they'll use the same function they used for the normal run. So, if they accidentally set infinite generator, they would have noticed it beforehand when they tested their function for the normal run.

**Comment by abidlabs** [comment]
Got it, that makes sense. I think we can provide a reasonable UI around this. Will take a look next week
