### ISSUE TITLE
Queue improvements for async job management

### ISSUE THREAD

**Issue by aliabid94** [gradio-app/gradio#3571]
Discussion to allow users to track queues, such that jobs can be accessed, based on discussion with @space-nuko. This will allow users to use gradio for task scheduling, which is a common use case in ML, esp. training. 

There are existing attempts to create something like this: [https://github.com/Kryptortio/SDAtom-WebUi-us](https://github.com/Kryptortio/SDAtom-WebUi-us), and [https://github.com/cmdr2/stable-diffusion-ui#task-queue](https://github.com/cmdr2/stable-diffusion-ui#task-queue). 

Code below is a suggested API to allow users to create custom queues, add to these queues, show jobs updated every second, with the ability to cancel selected jobs.

```python
with gr.Blocks() as finetune_stable_diffusion_demo:
  imgs = gr.File()
  btn = gr.Button("Finetune")
  queue_info = gr.Dataframe(label="Jobs")
  output_weights = gr.File(label="Finetuned Weights")
  selected_job_index = gr.State()
  cancel_btn = gr.Button("Cancel Job")

  finetune_queue = gr.Queue()
  
  def finetune(imgs):
    ...
  btn.click(finetune, imgs, None, queue=finetune_queue, multiple_pending=True) 
  # we set the queue, and allow the button to trigger multiple pending jobs without blocking

  def get_queue_data():
    return finetune_queue.jobs
  demo.load(get_queue_data, None, queue_info, every=1)
  # we update queue information every second

  def select_job(selection: gr.SelectData):
    job_index = selection.index[0]
    job = finetune_queue.jobs[job_index]
    job_output = job.output[0] if job.status == "complete" else None
    return job_output, job_index
  queue_info.select(select_job, None, [output_weights, selected_job_index])
  # we show weights of completed jobs, and keep track of the selected job

  def cancel_job(job_index):
    finetune_queue.cancel(job_index)
  cancel_btn.click(cancel_job, selected_job_index, None)
```

**Comment by space-nuko** [comment]
A few questions:

- Is `gr.Queue` supposed to be a blocks component or a special helper like `gr.Progress`? For the "Finetune" button it's used as an input component but in the `cancel_job` handler it's not, it's used as a nonlocal
- Queues must be able to accept different shapes of arguments, and dispatch them to the correct handler. This is a hard requirement for me. In webui there's txt2img and img2img, it wouldn't make sense to maintain two queues for each, and even with current Gradio I enqueue both at the same time (it seems like one handler will wait for the other currently). So for me it would make sense to have an API similar to registering an event handler, that specifies what arguments are sent and the destination handler

```python
queue.dispatch(fn=txt2img, id="txt2img", inputs=[t2i_prompt, t2i_width, t2i_height], outputs=[t2i_gallery])
```

And maybe you'd return the key `"txt2img"` from the `select` callback to put the results in the correct bucket

- Custom rendering for what jobs are in the queue. I have no idea how this could be accomplished, but I'd like to be able to see the prompt/size formatted correctly in the queue UI. Plus for jobs like img2img, there is an initial image passed too, so the UI should be able to render it sanely

**Comment by abidlabs** [comment]
Going to close as I don't think we plan to include this in core cc @aliabid94
