### ISSUE TITLE
Why Iam getting this error? Error code: 501

### ISSUE THREAD

**Issue by vijishmadhavan** [gradio-app/gradio#359]
Error response
Error code: 501

Message: Unsupported method ('POST').

Error code explanation: HTTPStatus.NOT_IMPLEMENTED - Server does not support this operation.

**Comment by samuel-lunii** [comment]
I am getting the exact same error when trying to host a new repo, at the `https://gradio.app/dockerize` stage...
@vijishmadhavan how did you get this error ?

**Comment by abidlabs** [comment]
Yes, can you please explain where and when you're getting this error?

**Comment by samuel-lunii** [comment]
@abidlabs 
In my case it happens right after I click on the "launch" button from the [https://gradio.app/hosted-launch](https://gradio.app/hosted-launch) page

**Comment by abidlabs** [comment]
Thanks @samuel-lunii. Looking into it. In the meantime, I highly recommend checking out Hugging Face Spaces (https://huggingface.co/spaces), which lets you host Gradio apps just like Gradio Hosted, and is now the preferred hosting solution we recommend.

**Comment by samuel-lunii** [comment]
@abidlabs 
Sorry for posting this here, but i did not find another way to contact you. I'm trying to find an invoice for the 7$ payment I made on Gradio. Can you help ?

**Comment by abidlabs** [comment]
Sure can you email support@gradio.app with the email address that you used?

**Comment by aliabd** [comment]
Hey @samuel-lunii and @vijishmadhavan, we have deprecated Gradio Hosted and notified customers. Existing interfaces will only remain live until December 31st, 2021 but no new interfaces can be created. All December payments were refunded (may take a few days to process) and all subscriptions were canceled. We highly encourage you to use Huggingface Spaces instead, a great and free resource for permanent hosting of your Gradio demos. More info on spaces [here](https://huggingface.co/blog/gradio-spaces) and [here](https://huggingface.co/docs/hub/spaces). 

I will close this issue, but if you have any questions feel free to add a comment.

**Comment by aliabd** [comment]
Note: we have also refunded payments made in November.
