### ISSUE TITLE
Gradio creates a lot of empty temporary folders on each run

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3592]
### Describe the bug

Described in https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8752#issuecomment-1481020332, every time a Gradio app is launched it creates multiple temporary folders, and a lot of them remain empty. This is somewhat important because a lot of webui users want to inspect intermediate outputs and it's hard to sift through dozens of temporary folders.

Even if there needs to be an autogenerated temp folder each startup, would be better to cut down on the number of temporary folders introduced

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just run a Gradio app with a large number of components and watch how many temporary folders are added

### Logs

```shell
N/A
```

### System Info

```shell
3.23.0, Windows, Chrome
```

### Severity

annoying

**Comment by abidlabs** [comment]
Interesting. Empty folders should not be created -- I'll take a look at this

**Comment by freddyaboulton** [comment]
Hi @space-nuko !

Is this still an issue in the latest gradio release? All the files created by gradio should now be located in `tempfile.gettempdir() / "gradio"` by default and any subdirectories are created when postprocessing of a component is run, e.g. Gallery.postprocess, Video.postprocess. I can't see the empty directories created on launch!

If there is a repro we can run outside the sd web ui, that would be much appreciated!
