### ISSUE TITLE
Invalid return value from `_js` function can hang entire app if `.queue()` is used

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3593]
### Describe the bug

If `.queue()` is used and a `_js` function returns a wrong type of input argument to an event handler (single value instead of a list), the entire Gradio app hangs

On the other hand if `.queue()` is omitted I at least get an error in the UI/logs with the status code `422 (Unprocessable Entity)`, and the response contains the message `value is not a valid list`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try the same code with and without `.queue()`

```python
#!/usr/bin/env python

import gradio as gr

with gr.Blocks() as demo:
    with gr.Row():
        textbox1 = gr.Textbox(value="test1", label="Input 1")
        textbox4 = gr.Textbox(value="test2", label="Input 2")
    with gr.Row():
        btn = gr.Button("Click Me")
    with gr.Row():
        textbox2 = gr.Textbox(label='Result 1')
        textbox3 = gr.Textbox(label='Result 2')

    def ppr(st1, st2):
        print("GET: " + str(st1) + " " + str(st2))
        return st1, st2

    js = "() => { console.log('js', arguments); return '1'; }"
    btn.click(fn=ppr, _js=js, inputs=[textbox1, textbox4], outputs=[textbox2, textbox3])


demo.queue().launch(server_port=9876)
# demo.launch(server_port=9876)
```

### Logs

```shell
(without .queue())

POST http://localhost:9876/run/predict 422 (Unprocessable Entity)

{"detail":[{"loc":["body","data"],"msg":"value is not a valid list","type":"type_error.list"}]}
```

### System Info

```shell
3.23.0, Windows, Chrome
```

### Severity

annoying

**Comment by abidlabs** [comment]
Can confirm that the behavior no longer happens with the new queue. Thanks @space-nuko for filing the original issue
