### ISSUE TITLE
Interface.launch(server_name='0.0.0.0') is not working

### ISSUE THREAD

**Issue by luoxuan-cs** [gradio-app/gradio#3598]
### Describe the bug

def main():
    gr.Interface(
        fn=chatgpt,
        inputs=[
            gr.inputs.Textbox(lines=2, placeholder="Enter your question here:"),
        ],
        outputs=[gr.outputs.Textbox()],
    ).launch(server_name='0.0.0.0')

if __name__ == '__main__':
	main()

gradio server_name='0.0.0.0' is not working. I have already checked the firewall (port 7860 is available and not blocked by the firewall), but I still cannot connect this web service through ip:7860 on a browser. For instance: http://77.666.555.444:7860 triggered HTTP ERROR 503.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
def main():
    gr.Interface(
        fn=chatgpt,
        inputs=[
            gr.inputs.Textbox(lines=2, placeholder="Enter your question here:"),
        ],
        outputs=[gr.outputs.Textbox()],
    ).launch(server_name='0.0.0.0')

if __name__ == '__main__':
	main()
```

### Logs

```shell
It works well on local server. But cannot connect to the application use its external ip.
```

### System Info

```shell
ubuntu 20.04
gradio 3.22.1
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
I cannot reproduce this @luoxuan-cs !

http://34.228.57.137:7860/

```python
import gradio as gr

def main():
    gr.Interface(
            fn=lambda x: x,
        inputs=[
            gr.inputs.Textbox(lines=2, placeholder="Enter your question here:"),
        ],
        outputs=[gr.outputs.Textbox()],
    ).launch(server_name='0.0.0.0')

if __name__ == '__main__':
    main()
```

<img width="1483" alt="image" src="https://user-images.githubusercontent.com/41651716/227381168-be9b3162-caf2-4919-aa1f-692d035cea04.png">

**Comment by luoxuan-cs** [comment]
Thanks for your help. I realize that I forgot to do NAT forwarding, and the network issue triggered this problem.

**Comment by freddyaboulton** [comment]
Great to hear you figured it out @luoxuan-cs !
