### ISSUE TITLE
`gr.File` component does not display many files nicely

### ISSUE THREAD

**Issue by duerrsimon** [gradio-app/gradio#3606]
### Describe the bug

I built a Gradio app for github app that is used to add files to an automated pull request. 
I'd like to preserve the names of the files. 
This works for few files but sometimes when submitting many files random strings are attached to the file names. This should be handled consistently.

In addition if many files are uploaded the component does not look nice:
![image](https://user-images.githubusercontent.com/16979577/227574469-56eea531-b78e-4f5a-a9a1-b2331ab7aa4c.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/simonduerr/bioicons-submission

### Screenshot

![image](https://user-images.githubusercontent.com/16979577/227572652-de5be6cb-1a71-454f-9099-056b4739880c.png)

### Logs

```shell
--
```

### System Info

```shell
Latest Gradio
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @duerrsimon ! In your example, what are the original names and what are the transformed names?

**Comment by duerrsimon** [comment]
Sorry for not being clear enough. For the first example it should be just the normal name of the file:
`anemone_egg.svg` instead of `anemone_egg08uifet6.svg` 
It probably gets added somewhere when the temporary files are created by the upload widget.

**Comment by abidlabs** [comment]
Hi @duerrsimon I can't reproduce the file name issue. I tried a simple demo that just lists the filenames of uploaded files and they all show up correctly for me:

```py
import gradio as gr
import os

with gr.Blocks() as demo:
    f = gr.File(file_count="multiple")
    j = gr.JSON() 
    f.upload(lambda files:[os.path.basename(fo.name) for fo in files], f, j)

demo.launch()
```

I wonder if something else is happening, like maybe the same file is getting uploaded twice and so it's forced to rename? If you can repro with a simpler demo, that would be very helpful

**Comment by duerrsimon** [comment]
I can't reproduce it using your minimal example as well (even when uploading the same files multiple times) or uploading 100 files at the same time so I investigated some more. 

Here is a minimal example: https://huggingface.co/spaces/simonduerr/repro-files
 
Upload many files and then hit the button before they are all uploaded and then the names will be like I described. (I was on a slow train connection yesterday so that's why it happend I guess). If your connection is to fast you can enable throttled connection Chrome Dev Tools to simulate.
![image](https://user-images.githubusercontent.com/16979577/227715172-2155915d-3044-4561-941e-650962bd8d84.png)

![image](https://user-images.githubusercontent.com/16979577/227715184-a9258e0a-3fea-4603-af31-8baaae063234.png)

I guess the best fix for this would be to not allow the click event to execute before all uploads have finished.

**Comment by abidlabs** [comment]
Ah interesting. Okay in that case, we are looking at this issue here: #3382. We can focus this issue on the other problem that you raised, which is that the file component does not display many files nice. But actually, I can't repro that either:

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/1778297/227751182-a357267d-64a7-4451-a586-9b9dcea9cae3.png">

Even with a bunch of files, they show up properly. Maybe you can share a screencast so we can see how this is happening?

**Comment by duerrsimon** [comment]
Seems to only happen in the iframe embed (This is embedded in a Nuxt App and so using the web component embed is a little more difficult). 
See screencast for a reproduction: https://monosnap.com/file/kGXdcn3KKcPKCuD6xGRGwoLRsPgH4i
The page is live at https://bioicons.com/submit/ 

For the other issue, I guess I should pin to an older version of gradio. From what I understand from the linked thread this is a recent change, no?

**Comment by abidlabs** [comment]
Ah I see. I'm not super familiar with Next JS apps, but it looks like you can handle import javascript and web components: https://nextjs.org/docs/basic-features/script

I'd recommend trying that because we strongly recommend web components over iframes. 

> For the other issue, I guess I should pin to an older version of gradio. From what I understand from the linked thread this is a recent change, no?

Yeah 3.18 or older should work

**Comment by duerrsimon** [comment]
I know that web component is preferable but NuxtJS =/= NextJS and vue/Nuxt use the same synthax as web components for their component system so one has to implement a loader for the webcomponent which I didn't have time to look into yet. 

Closing this issue now since the iframe behavior probably does not need a fix and the other issue is being worked on.
