### ISSUE TITLE
Is it possible to change the language of the interface? Or edit it manually

### ISSUE THREAD

**Issue by DavidZha1994** [gradio-app/gradio#361]

**Comment by abidlabs** [comment]
This is something that's been on our radar for a while (see "https://github.com/gradio-app/gradio/blob/abidlabs/strings/gradio/strings.py" which was created to support internationalization), and our `title` and `description` parameters are fully user-specified so they can easily be in a different language.

That being said, what parts of the interface would you like to change to a different language? Would you able to help us translate the words?

**Comment by DavidZha1994** [comment]
Sure, that wouldn't be a problem. for now, i just want to translate some basic stuff on GUI like clear, submit, screenshot flag etc.

**Comment by dawoodkhan82** [comment]
> Sure, that wouldn't be a problem. for now, i just want to translate some basic stuff on GUI like clear, submit, screenshot flag etc.

We added support for internationalization. Can you help us add support for your language by providing translations in a new file here? (https://github.com/gradio-app/gradio/tree/master/ui/packages/app/public/lang)

**Comment by esraa-abdelmaksoud** [comment]
> > Sure, that wouldn't be a problem. for now, i just want to translate some basic stuff on GUI like clear, submit, screenshot flag etc.
> 
> We added support for internationalization. Can you help us add support for your language by providing translations in a new file here? (https://github.com/gradio-app/gradio/tree/master/ui/packages/app/public/lang)

@dawoodkhan82 The link is broken. Please provide the new link if possible. I'll be happy to provide the Arabic translation if needed.

**Comment by freddyaboulton** [comment]
Please try this link @esraa-abdelmaksoud ! 

https://github.com/gradio-app/gradio/tree/main/js/app/src/lang
