### ISSUE TITLE
Setting label=None for gr.Textbox gives "textfield" text in UI instead of nothing

### ISSUE THREAD

**Issue by hithereai** [gradio-app/gradio#3616]
### Describe the bug

Consider this line of code:

`settings_path = gr.Textbox(value="deforum_settings.txt", elem_id='deforum_settings_path', label=None)`

It should show the textbox without any label above it, as label is set to None (which is also the default, according to your docs). 

However, actual interface looks like this:

![image](https://user-images.githubusercontent.com/121192995/227711095-0725bc60-8621-4661-a529-e9571603b445.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`settings_path = gr.Textbox(value="deforum_settings.txt", elem_id='deforum_settings_path', label=None)`

### Logs

```shell
Getting no errors at all.
```

### System Info

```shell
Gradio 3.23.0  on automatic1111 webui. Windows 11 22h2, Brave browser.
```

### Severity

annoying

**Comment by abidlabs** [comment]
Will look into this! For now try setting label to be an empty string: “”

**Comment by abidlabs** [comment]
Yeah so this is the expected behavior. When the `label` is set to `None`, it is automatically rendered as "Textbox". In order for no label to show up, you should either set `show_label=False`, which also hides the space, or set `label=""` as suggested above (if you want to keep the whitepsace)
