### ISSUE TITLE
Android browser,Microphone recording did not respond

### ISSUE THREAD

**Issue by monkeycc** [gradio-app/gradio#3617]
### Describe the bug

Android  13

Android browser
Microphone permission on

Microphone recording did not respond

Android browser  Compatibility issues ??

https://www.myquark.cn/
https://umcdn.uc.cn/download/36734/quark/kk@store_guanwang_ot/QuarkBrowser_V6.2.2.246_android_pf3300_(zh-cn)_release_(Build230322233837-arm32).apk

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://gradio.app/demos/

### Screenshot

https://user-images.githubusercontent.com/6490927/227717359-f34e4afc-71b5-4629-b09b-f1573b4050cb.mp4

### Logs

```shell
....
```

### System Info

```shell
....
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @monkeycc this very much looks like microphone permissions issues. Can you please confirm (by visiting https://mictests.com/ for example) that microphone permissions are enabled?

**Comment by monkeycc** [comment]
Can't

Looks like there's a problem with the browser


Although the browser has been granted microphone permissions
But there was no prompt

give up
