### ISSUE TITLE
How can I convert this Gradio file upload code into folder path taking one?

### ISSUE THREAD

**Issue by FurkanGozukara** [gradio-app/gradio#3619]
There is this gradio code that allows you to upload images. I prefer entering folder path as a text input.

It works but instead of this one, I want to convert it into a directory path taking one

      reference_imgs = gr.UploadButton(label="Upload Guide Frames", file_types = ['.png','.jpg','.jpeg'], live=True, file_count = "multiple") 

I tried below one but it didn't work

    reference_imgs = gr.inputs.FilePicker(label="Select folder with Guide Frames", type="folder")

**Comment by abidlabs** [comment]
Responded in Discussions

**Comment by concrete13377** [comment]
Would you be so kind as to share the link for the answer here?
