### ISSUE TITLE
Cannot interact with the component using `every`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#3626]
### Describe the bug

When using `every`, it seems users cannot interact with the component. It's not possible to scroll in `gr.Text` or to download image in `gr.Image`. 

https://user-images.githubusercontent.com/25161192/227764518-75bd7c9b-3ea2-4a9a-9e05-02c9eb08ebd8.mp4

This might be an expected behavior, but it would be more useful if we could interact with the components that are using `every`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr
import PIL.Image


def read_log() -> str:
    with open('log.txt') as f:
        log = f.read().strip()
    return log


def read_image() -> PIL.Image.Image:
    return PIL.Image.open('tiger.jpg')


with gr.Blocks() as demo:
    with gr.Row():
        gr.Text(label='without every', value=read_log(), lines=5, max_lines=5)
        gr.Text(label='with every',
                value=read_log,
                lines=5,
                max_lines=5,
                every=1)
    with gr.Row():
        gr.Image(label='without every', value=read_image(), type='filepath')
        gr.Image(label='with every',
                 value=read_image,
                 type='filepath',
                 every=1)

demo.queue(api_open=False).launch()
```

https://huggingface.co/spaces/hysts-debug/gradio-issue-3626

### Logs

```shell
none
```

### System Info

```shell
gradio==3.23.0
```

### Severity

annoying

**Comment by abidlabs** [comment]
Very strange, thanks for flagging this @hysts!

**Comment by abidlabs** [comment]
I can't reproduce this @hysts. Can you see if it's still an issue in the latest version of `gradio`? Here's what I happens when I run that code locally:

**Comment by hysts** [comment]
@abidlabs Thanks. Looks like it works fine with `gradio==3.36.1`. I'll close this issue.
