### ISSUE TITLE
`.select` doesn't return the last result when selected consecutively while processing

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#3627]
### Describe the bug

I think this should always return the index of the last selected item.

https://user-images.githubusercontent.com/25161192/227767732-22159b62-1a00-44c5-b6c8-95b6788a2a68.mp4

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import pathlib

import gradio as gr

paths = [path.as_posix() for path in sorted(pathlib.Path('images').glob('*'))]


def fn(data: gr.SelectData) -> int:
    return data.index


with gr.Blocks() as demo:
    images = gr.Gallery(value=paths).style(grid=3)
    selected = gr.Text(label='selected index')
    images.select(fn=fn, outputs=selected)
demo.queue(api_open=False).launch()
```

https://huggingface.co/spaces/hysts-debug/gradio-issue-3627

### Logs

```shell
none
```

### System Info

```shell
gradio==3.23.0
```

### Severity

annoying

**Comment by abidlabs** [comment]
The root of this issue is actually the same as #1954. Let me rename that issue and reference this issue as a specific case

Solution is to change how we submit events to make sure the final event is always sent. This is a slight breaking change so we'll do it as part of the 4.0 migration
