### ISSUE TITLE
Allow Webcam stream to be stopped/resume programmatically 

### ISSUE THREAD

**Issue by radames** [gradio-app/gradio#3642]
As for privacy concerns, it would be useful to enable the webcam stream to be stopped and resumed programmatically. For instance, in the code below, when a user accesses the app, the webcam stream permission would be requested right away, rather than only upon tab activation. Moreover, if the user switches from the webcam tab to the file tab, the webcam remains active.

**Ideas**:

* Allow the webcam stream to be stopped and resumed programmatically.
* Destroy the webcam component when the tab is inactive and remount it when the tab becomes active again.
* Once issue #3306  is resolved, users might be able to update the source dynamically, and the webcam stream will automatically stop and resume as they change the source, e.g., source="webcam" => source="file" => source="webcam".

Code example:

```python
import gradio as gr

with gr.Blocks() as demo:
    with gr.Tab("File"):
        with gr.Row():
          with gr.Column():
            image = gr.Image(label="Input Image")
            run = gr.Button("Run")
          with gr.Column():
            output = gr.Image(label="Input Image")
    with gr.Tab("File"):
        with gr.Row():
          with gr.Column():
            image = gr.Image(label="Input Image", source="webcam")
            run = gr.Button("Run")
          with gr.Column():
            output = gr.Image(label="Input Image")
  
demo.launch()
```

https://colab.research.google.com/drive/1PHohs4lgt-Ty4SHK1ZGdpHwmWadvZXAY

**Comment by pngwn** [comment]
> Destroy the webcam component when the tab is inactive and remount it when the tab becomes active again.

This is what we should be doing really but requires some internal changes. It should be addressed soon though.

**Comment by innat-asj** [comment]
Any update on this? Or, any workaround with the current APIs?

**Comment by taoari** [comment]
Hope to see an update on this.
