### ISSUE TITLE
start app break wheile I change launch server_name from "127.0.0.1"  to "0.0.0.0" (server_name "127.0.0.1" can work)

### ISSUE THREAD

**Issue by done520** [gradio-app/gradio#3652]
### Describe the bug

code as fllows：

import gradio as gr

def test_micro(path2audio):
    return path2audio

if __name__ == '__main__':
    demo = gr.Interface(fn=test_micro,
                        inputs=gr.components.Audio(source="microphone", type="filepath", label="Speaker"),
                        outputs="text")
    demo.launch(server_port=7860, server_name="0.0.0.0", debug=True, share=True)

"errors" as fllows:
File "/home/user/anaconda3/base/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=7860): Max retries exceeded with url: /startup-events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fde73b926d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

"errors" as fllows:
File "/home/user/anaconda3/base/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=7860): Max retries exceeded with url: /startup-events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fde73b926d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

### Logs

```shell
"errors" as fllows:
File "/home/user/anaconda3/base/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=7860): Max retries exceeded with url: /startup-events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fde73b926d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

### System Info

```shell
"errors" as fllows:
File "/home/user/anaconda3/base/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=7860): Max retries exceeded with url: /startup-events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fde73b926d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @done520 this issue is not clear. The code sample you've provided is not sufficient to reproduce the problem. It sounds like you simply don't have `0.0.0.0` accessible in your environment, e.g. you are running on Windows. If you can create a reproducible Colab notebook for us to look at, we're happy to do so. Otherwise, we'll have to close this issue for a lack of repro.

**Comment by abidlabs** [comment]
Closing for lack of followup -- please feel free to reopen with a repro
