### ISSUE TITLE
Theme problem. Gradio doesn't render correctly

### ISSUE THREAD

**Issue by JavierVLAB** [gradio-app/gradio#3662]
### Describe the bug

I'm using Gradio in a FastAPI server, but the app doesn't look right. In chrome, I can see the error in the dev tools. The error is that theme.css doesn't found.

I fix this error downgrading to Gradio=3.20.0

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I can't provide my code, but this is almost the same

```
from fastapi import FastAPI
import gradio as gr

CPATH = "/gradio"

app = FastAPI()

io = gr.Interface(lambda x: "Hello, " + x + "!", "textbox", "textbox")
gradio_app = gr.routes.App.create_app(io)

app.mount(PATH, gradio_app)
```

### Screenshot

screnshot gradio > 3.20.0
![image](https://user-images.githubusercontent.com/1854994/228177894-59b38ca2-1b35-4717-bce1-0f7960642cee.png)

screenshot gradio = 3.20.0
![image](https://user-images.githubusercontent.com/1854994/228177600-9333f0b5-9f5d-46c8-afc9-c0e5f5905e35.png)

### Logs

```shell
INFO:     127.0.0.1:55906 - "GET /theme.css HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:55905 - "GET /app_id HTTP/1.1" 404 Not Found
```

### System Info

```shell
gradio > 3.20.0, Windows, Chrome
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Hi @JavierVLAB we fixed this issue in 3.22, with this PR: #3482. Can you please try upgrading to the latest version (`3.23.0`) and see if it resolves the problem?

**Comment by abidlabs** [comment]
So the recommended way to mount a Gradio app is to use ` gr.mount_gradio_app` like this:

```py
import gradio as gr
from fastapi import FastAPI

io = gr.Interface(lambda x: "Hello, " + x + "!", "textbox", "textbox")

app = FastAPI()

@app.get("/")
def read_main():
    return {"message": "This is your main app"}

gradio_app = gr.mount_gradio_app(app, io, path='/mypath') 
```

Then, you'd run, for example,

`uvicorn test:gradio_app --port 7888`


Can you see if this works for you? It's working fine on my end

**Comment by abidlabs** [comment]
Awesome, thanks for letting us know!
