### ISSUE TITLE
Docs working_with_ml page examples don't match code

### ISSUE THREAD

**Issue by discdiver** [gradio-app/gradio#367]
Several of the examples don't go with the code on the working_with_ml webpage. For example, see the screenshot below:

<img width="983" alt="Screen Shot 2021-11-15 at 9 04 37 PM" src="https://user-images.githubusercontent.com/7703961/141882751-05ca27bb-2848-4afb-8c3e-b2faf76682c8.png">

**Comment by abidlabs** [comment]
Thanks for creating an issue @discdiver, we are actually revamping the website and fixing this. @aliabid94

**Comment by abidlabs** [comment]
The demos have been removed and we will be updating the examples & corresponding colab notebooks. Thanks!
