### ISSUE TITLE
Huge empty space in `gr.Tab()`

### ISSUE THREAD

**Issue by oobabooga** [gradio-app/gradio#3670]
### Describe the bug

The simple tabbed layout with two columns below has a large empty area in `gradio==3.23.0`.

This empty area did not exist in `3.16.0`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks(analytics_enabled=False) as interface:
    with gr.Row():
        with gr.Tab('Chat history'):
            with gr.Row():
                with gr.Column():
                    gr.Markdown('Upload')
                    upload_chat_history = gr.File(type='binary', file_types=['.json', '.txt'])
                with gr.Column():
                    gr.Markdown('Download')
                    download = gr.File()
                    download_button = gr.Button(value='Click me')

interface.launch()
```

### 3.23.0:

![3 23 0](https://user-images.githubusercontent.com/112222186/228311003-d068ab5d-83cc-4d8c-b408-05b4f44a4780.png)

### 3.16.0:

![3 16 0](https://user-images.githubusercontent.com/112222186/228311007-e86f6b9f-dc6a-4e5a-8231-019cc3de9ce0.png)

### Logs

```shell
--
```

### System Info

```shell
gradio==3.23.0
```

### Severity

annoying

**Comment by oobabooga** [comment]
I fixed it with this change

```css
div.svelte-15lo0d8 {
  flex-wrap: nowrap;
}
```

This is the result:

![fixed](https://user-images.githubusercontent.com/112222186/229922856-44f3bf2d-c8b3-490f-a284-7feb846bce0c.png)

cc @abidlabs

**Comment by abidlabs** [comment]
Thanks @oobabooga! cc @aliabid94 @dawoodkhan82 can we make this change into a PR?

**Comment by oobabooga** [comment]
I have just noticed that this change causes an overflow in the flex layout on mobile devices. So it's not the best solution

![overflow](https://user-images.githubusercontent.com/112222186/229924902-d03448db-07f4-4c93-8f71-27e01f9d28e1.png)

**Comment by abidlabs** [comment]
Ah thanks @oobabooga, we'll look into it on our end too but let us know if you find something that works consistently.
