### ISSUE TITLE
Use webkit scrollbars

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3676]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
One of the webui users posted a version of `gr.Dropdown` with better-looking scrollbars, maybe it should be the default

**Describe the solution you'd like**  
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9105

**Additional context**

**Comment by missionfloyd** [comment]
Should be noted that it doesn't work on firefox.
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

**Comment by abidlabs** [comment]
GIven that it doesn't work on firefox plus it's a pretty minor UI change, I'm inclined to close this @space-nuko.
