### ISSUE TITLE
Additional `Chatbot` Markdown Support

### ISSUE THREAD

**Issue by abetlen** [gradio-app/gradio#3680]
Hi there,

First I gotta say thank you for the awesome library, definitely speeds up my ml prototyping process a lot!

I was wondering if it's possible to extend the limited markdown support for the `Chatbot` block to include some additional expected features like headings, lists and tables. I'm trying to display structured data (list of query results for example) in the `Chatbot` body but currently this is quite difficult to do without support for tables and proper headings to seperate sections of the interface.

**Comment by jrowen** [comment]
It looks like `Chatbot` should support html tables (https://github.com/gradio-app/gradio/blob/main/gradio/utils.py#L1010), but the two lines below prevent the table from rendering correctly (https://github.com/gradio-app/gradio/blob/main/gradio/components.py#L4597-L4598):

    chat_message = chat_message.replace("\n", "<br>")
    return self.md.renderInline(chat_message) 

If I replace them with the following, the table renders as expected:

    return self.md.render(chat_message)

**Comment by abidlabs** [comment]
Hi @jrowen we have a WIP PR that, among other things, does this: https://github.com/gradio-app/gradio/pull/4048/files

Would you be able to see if this PR works for you (in adding support for tables, etc.)?

**Comment by jrowen** [comment]
I'd be happy to test. What are the steps I need to follow to install via PR?  The following doesn't seem to be sufficient (seeing a 500 error):

    pip install git+https://github.com/gradio-app/gradio.git@chatbot-code-highlight

**Comment by abidlabs** [comment]
@jrowen can you try `pip install https://gradio-builds.s3.amazonaws.com/7fddac232b2f6f652890dd5689d5d7313da27267/gradio-3.28.1-py3-none-any.whl`?

**Comment by jrowen** [comment]
Looks good so far.  

It would be useful to include more plugins or allow users to specify which plugins to use.  For example, I'd like to use `emoji_plugin` and need to override the class to load:

```
from gradio import Chatbot as grChatbot
from mdit_py_emoji import emoji_plugin

class Chatbot(grChatbot):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.md = self.md.use(emoji_plugin)
```

**Comment by abidlabs** [comment]
Thanks @jrowen we've released the PR in `3.28.3` so it should be easier to use. Adding support for additional plugins is not a cool idea, we'll consider it!

**Comment by abidlabs** [comment]
Good discussion on adding support for tables here as well: https://github.com/gradio-app/gradio/issues/4062

**Comment by xyfZzz** [comment]
> Looks good so far.
> 
> It would be useful to include more plugins or allow users to specify which plugins to use. For example, I'd like to use `emoji_plugin` and need to override the class to load:
> 
> ```
> from gradio import Chatbot as grChatbot
> from mdit_py_emoji import emoji_plugin
> 
> class Chatbot(grChatbot):
> 
>     def __init__(self, *args, **kwargs):
>         super().__init__(*args, **kwargs)
>         self.md = self.md.use(emoji_plugin)
> ```

But raises this error：AttributeError: 'Chatbot' object has no attribute 'md'

How to use emoji_plugin correctly?
