### ISSUE TITLE
Select a folder and then just get the filenames from that folder as a list

### ISSUE THREAD

**Issue by FurkanGozukara** [gradio-app/gradio#3681]
We have a script that allow users upload files

But we are requesting a feature that we can give path and it can read all files from given folder path

`  reference_imgs = gr.UploadButton(label="Upload Guide Frames", file_types = ['.png','.jpg','.jpeg'], live=True, file_count = "directory") `

So this above code will be modified to a textbox input that takes folder path to read all files from that path

In this case images

Thank you

**Comment by joytsay** [comment]
I made something similiar with tkinter:
[  #2515#issuecomment-1676824284](https://github.com/gradio-app/gradio/issues/2515#issuecomment-1676824284)

**Comment by henryruhs** [comment]
@FurkanGozukara I suggest we break down File to FileUpload and FileDialog and DirectoryDialog. FileDialog and DirectoryDialog do not create temporary files and can be use as a Entrypoint for Image, Video or Textbox but without coupling.

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara I suggest we break down `File` to `FileUpload` and `FileDialog` and `DirectoryDialog`. `FileDialog` and `DirectoryDialog` do not create temporary files and can be use as a Entrypoint for Image, Video or Textbox but without coupling.

i am not gradio expert but thanks for suggestions 

gradio really need to fine tune an LLM and release it for questions

**Comment by C0untFloyd** [comment]
@abidlabs 
Is this still being worked on? I don't think a new component is even needed, just a flag to avoid copying the temporary files around and instead use the files from a local folder. This could be even bound to the global share option on server launch.

**Comment by henryruhs** [comment]
Flags or modes telling a component to behave different are a **bad design pattern** to avoid at all cost.

I rather wait 2 -3 more months for a clean solution. One component, one task is the better approach on long term.

Take a look into `gradio.Image`. It does literally everything: being a WebcamStream, ImageEditor, ImageUpload and simple Image display component. Without even know the code, I know this needs refactoring.

**Comment by C0untFloyd** [comment]
I generally agree and fully when it comes to the Image Component, which tries hard to be everything. But for the File Component this isn't another extension or different usage, it's just about how the input data is prepared/used. It's a boolean choice only, act locally or not, there's almost no possibility for bad design. Just my 2 cents, let's leave it to the gradio devs, they might know best.

PS: of course splitting and separating different user dialogs into separate components would be better design, I just don't think it's really necessary for the temp file processing.

**Comment by henryruhs** [comment]
@abidlabs Sorry for adding more noise, but this is a very crucial feature that we need asap.

**Comment by abidlabs** [comment]
Hi @henryruhs we have a work-in-progress PR that may address this: https://github.com/gradio-app/gradio/pull/5672

**Comment by henryruhs** [comment]
That is neat but we don't need a file explorer - we need a entrypoint for handling mixed media such as images / video so we can use a FileBrowse() and then load Image() or Video().

That is the actual usecase at FaceFusion and some of the roop forks.

**Comment by abidlabs** [comment]
Hmm I see -- what could potentially work for you is a FileExplorer that also lets you select a file for further processing. I'm not sure yet if we can squeeze that in the same PR, but we'll look into it.

**Comment by henryruhs** [comment]
@abidlabs Thanks for taking action, I know you have a tons of open issues.

**Comment by henryruhs** [comment]
@abidlabs @pngwn As much as I love the FileExplorer, it is not a FileDialog and therefore cannot be used to have a drag and drop area for images and videos.

What @FurkanGozukara and @joytsay described in the first 2 comments has nothing in common with that FileExplorer. That being said, please reopen this issue.

**Comment by pngwn** [comment]
I don't really understand this request. 

Is the idea that the component would give you the actual path from the users file system? I assume this for gradio apps that only run locally?

**Comment by henryruhs** [comment]
Does it matter if they run local or remote? It about browsing the local files and select them.

At the moment I have to use a gradio.File() as a entry point for a drop-area that supports both images and video. This creates the temp files 2 times.

Example: https://github.com/facefusion/facefusion/blob/master/facefusion/uis/components/target.py#L16-L44

**Comment by pngwn** [comment]
Yes. Because the server doesn't have access the local file system of the user that is 'uploading'. So I do not know what you would want to do with those paths, they would basically be useless because the files could not be accessed. 

They could be access if the users machine is also where the gradio server is running, and only in that instance. 

However, all of this is moot, because the browser does not have access to the location of a file that a user uploads for security reasons. Even if you use the new file system API, that information is not available.

**Comment by pngwn** [comment]
The only way we could make this work without creating temp files is if we had an option to pass a Blob back, rather than a file path.

**Comment by henryruhs** [comment]
You are right, I was mixing local and remote a bit too much. Does it make sense to open a new issue?

**Comment by henryruhs** [comment]
@pngwn Here we go: https://github.com/gradio-app/gradio/issues/5809

**Comment by pngwn** [comment]
Thanks!
