### ISSUE TITLE
Some example Spaces in docs are broken

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3683]
### Describe the bug

Here are two I found so far:

https://huggingface.co/spaces/gradio/sentence_builder_main
https://huggingface.co/spaces/gradio/titanic_survival_main

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Go to https://www.gradio.app/docs/main/#dropdown
2. Try the examples

### Logs

```shell
Runtime error
Space failed to start. Exit code: 1
Container logs:
```

### System Info

```shell
N/A
```

### Severity

annoying

**Comment by abidlabs** [comment]
cc @aliabd
