### ISSUE TITLE
Chatbot automatically add empty line

### ISSUE THREAD

**Issue by XiPotatonium** [gradio-app/gradio#3684]
### Describe the bug

Each time chatbot is updated, a new line break are automatically added to old multi-line messages.
It seems that a new `<br>` is added before `\n`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

It can be reproduced in gradio demo.
https://gradio.app/creating-a-chatbot/
I also encounter this bug with my installed gradio 3.23.0

### Screenshot

![QQ截图20230329141020](https://user-images.githubusercontent.com/8765462/228442436-32bebd89-8d09-4b0c-bea2-579698ac37f3.png)

### Logs

```shell
N/A
```

### System Info

```shell
gradio==3.23.0
```

### Severity

annoying

**Comment by abidlabs** [comment]
Can reproduce, we'll take a look! cc @dawoodkhan82

**Comment by enbacoo** [comment]
I have the same problem~

**Comment by HaoHoo** [comment]
Hoops I just want to add an issue for this... Same problem when I try to chatbot for GPT

**Comment by abidlabs** [comment]
Hi folks! Sorry about that, we've fixed this issue in #3717 and a made a new release (gradio==3.24.1) which should be out soon with the fixes.
