### ISSUE TITLE
refresh the mardown or other component directly

### ISSUE THREAD

**Issue by ablozhou** [gradio-app/gradio#3687]
- [ *] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

I need to check a login state from url parameter.  if has authenticated, the markdown display the user's phone number. else the user can't use the gradio element.

if user does not login in, it should report error or display the auth login screen.
if user has logined in,  the Markdown display phone number.
the url like: https://host/?token=abcd

```
def auth(user,passwd):
  # Todo: check if token is ok, then silently refresh markdown text to display user info and return true 
  # else display the login UI.
  # check login and return True or false

with block:
  #...read url param token and get user info of phone number.

  m = gr.Markdown(f"""<h1><center>{title}-{phone}</center></h1>""")

block.launch(auth=auth, ...)

```

**Additional context**  
1. some global auth check function, to avoid not login usage.
2. some convenient method to update UI component's value.

**Comment by abidlabs** [comment]
Hi @ablozhou to pick up the conversation from #3665, once you are logged in, you can define a function to use the user's name however you want. You could look up their username in a database and change a Markdown component's displayed value at launch. Something like this:

```py
def update_markdown(r: gr.Request):
   username = r.username
   phone= lookup(username)
   return f"""<h1><center>{phone}</center></h1>"""

with gr.Blocks() as demo:
   m = gr.Markdown()
   demo.load(update_markdown, None, m)   # runs when page launches
```

By the way, for general questions like this (that are not feature requests or bug reports), please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
