### ISSUE TITLE
Image webcam input improvements

### ISSUE THREAD

**Issue by DominicPalaczky** [gradio-app/gradio#3689]
- [Yes] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
A problem I have encountered when building a Gradio demo is that the webcam input option is pretty lackluster. When I take a photo, the quality of the photo is lower than expected. There is no obvious option to select which camera to use when multiple cameras are on the device. The combination of these problems means the models I demo underperform.

**Describe the solution you'd like**  
I would like the option to select which camera to use within the gradio demo.
I would like an option off changing the video stream quality when building the demo

**Additional context**

**Comment by abidlabs** [comment]
Thanks for the suggestions @DominicPalaczky! Seems reasonable to me

**Comment by abidlabs** [comment]
Closing in favor of #4252 as it is more general
