### ISSUE TITLE
Docs: Embed page and API page are outdated

### ISSUE THREAD

**Issue by duerrsimon** [gradio-app/gradio#3697]
### Describe the bug

The follwing sections of the docs are outdated:

https://gradio.app/sharing-your-app/#embedding-hosted-spaces
does not mention "run with docker" but is linked from the modal when one clicks on "run with docker" in a space
![image](https://user-images.githubusercontent.com/16979577/228671962-cd111d7f-dfce-44d7-b30d-c62f6c0fc2ea.png)

https://gradio.app/sharing-your-app/#api-page
The text mentions the "view api" which is not shown in the embedded app.
![image](https://user-images.githubusercontent.com/16979577/228672091-bf44b22a-a3ac-4bb2-81be-47103618e029.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

see above

### Logs

```shell
see above
```

### System Info

```shell
see above
```

### Severity

annoying

**Comment by aliabd** [comment]
Thanks @duerrsimon, will fix both of these.
