### ISSUE TITLE
Keybinds don't work in `gr.Dropdown` if more than one item with same value is selected

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3703]
### Describe the bug

[output.webm](https://user-images.githubusercontent.com/24979496/228722424-f4864dec-1ade-475e-893c-f4ed3372975f.webm)

Stems from the fact that `gr.Dropdown` doesn't keep track of selected index, only selected value

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Create `gr.Dropdown` with a few same elements
2. Open dropdown, select one of the same elements
3. Try to use arrow keys

### Logs

```shell
N/A
```

### System Info

```shell
Gradio 3.23.0, Windows, Chrome
```

### Severity

annoying

**Comment by abidlabs** [comment]
@space-nuko what is the use case for having a dropdown with multiple choices with the same name?

**Comment by space-nuko** [comment]
It's possible a user could have a model named the same on their hard drive in two different folders, but the dropdown only shows the name of the file. And the dropdown is sorted by full path instead of name.

**Comment by abidlabs** [comment]
Ok but in the case that you described, if the Dropdown only shows the base name of a file and multiple files share the same name, there's going to be an issue when a user actually calls the function itself. There's an ambiguity here -- which of the two files should be selected? In general, I think this is always going to be this ambiguity when the `Dropdown` consists of two choices that are the same, so I do *not* think that we should not encourage this behavior. I think we should just raise a warning if a Dropdown with multiple choices with the same name are provided and then deduplicate the choice list. WDYT @space-nuko @dawoodkhan82 @aliabid94?

**Comment by abidlabs** [comment]
This would only work if `type="index"`, correct?

**Comment by abidlabs** [comment]
I'm going to close this issue and just implement this as part of #3019
