### ISSUE TITLE
chatbot thumb up down

### ISSUE THREAD

**Issue by jiacheng-ye** [gradio-app/gradio#3707]
Is there a way to add thumb up & down in the chatbot to measure the correctness of each response?

**Comment by freddyaboulton** [comment]
Hi @jiacheng-ye ! In the meantime you can add separate buttons for thumbs up and down. See this demo for inspiration: https://chat.lmsys.org/

**Comment by jiacheng-ye** [comment]
Thanks for your suggestion!
