### ISSUE TITLE
BUG: DataFrame output cannot handle null values

### ISSUE THREAD

**Issue by discdiver** [gradio-app/gradio#371]
#### Result:
pandas DataFrame doesn't display if more than 10 cells are to be shown initially

#### Expectation: 
The DataFrame will be displayed

#### Versions:
gradio 2.2.15
Python 3.9.6

#### Reproducible Example

```
import gradio as gr
import pandas as pd
import plotly.express as px

def show_pens(alpha):
    df_pens = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv')
    print(df_pens)
    return df_pens.iloc[:5, :3]

iface = gr.Interface(
    fn=show_pens, 
    inputs=['text'],
    outputs=[gr.outputs.Dataframe()],
    description="Table of Palmer Penguins"
)

iface.launch()
```

### Screenshot of failing output
<img width="1312" alt="Screen Shot 2021-11-16 at 7 59 47 AM" src="https://user-images.githubusercontent.com/7703961/141990015-616ed983-0c78-4b2c-9b35-9b031d7ec735.png">

### Console error screenshot

<img width="544" alt="Screen Shot 2021-11-16 at 8 05 56 AM" src="https://user-images.githubusercontent.com/7703961/141990591-d00b6bcd-7492-4628-ad40-47264e638f2a.png">

### Working example

Change the return statement to  ` return df_pens.iloc[:3, :3]`

### Screenshot of working output

<img width="1286" alt="Screen Shot 2021-11-16 at 8 00 24 AM" src="https://user-images.githubusercontent.com/7703961/141990208-e9d1e011-c9e4-4117-a4ce-15f4099975b7.png">

**Comment by abidlabs** [comment]
Interesting, @aliabid94 can you look into this?

**Comment by aliabid94** [comment]
WIll take a look, thanks @discdiver

**Comment by aliabid94** [comment]
Ah seems like there is null value in the dataframe that's throwing the rendered off - its not related to size of output. See image:
![image](https://user-images.githubusercontent.com/7870876/143135531-a15f4b70-3c00-4cf2-9de2-d98a3992926d.png)
 
Fixing the null value issue now.

**Comment by discdiver** [comment]
Thanks. Yep, there are a few nulls. So gradio can't display DataFrames with
null values? If that's the case, probably worth adding to the docs.

FWIW, there's probably a fix as that's not an issue on Streamlit.

**Comment by aliabid94** [comment]
Yes there's a fix in the works, will be in the next release. Will update here when it's in.

**Comment by discdiver** [comment]
Thanks!
