### ISSUE TITLE
How to hide dancing squares and reduce CPU consumption?

### ISSUE THREAD

**Issue by nickkolok** [gradio-app/gradio#3711]
- [yes] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

Due to performance reasons, is it possible to to disable The Dance Of The Squares:
![image](https://user-images.githubusercontent.com/5008131/228901829-6e30108d-2e51-4480-8d6f-9aa0c1d974e4.png)
![image](https://user-images.githubusercontent.com/5008131/228902008-a46c3954-eb6b-435d-bcec-ff0581ab40ad.png)
and also to lower the `processing` update frequency rate? Ideally, it should update once in a second or two - and not ten times a second as it does now!

It looks cute, modern and cool when you have one tab with a task that completes in seconds. But if you have a thin client... with old hardware... and dozen of tabs with a couple pf `Galleries` on each queuing... And you also want to do something on this machine while the tabs are working... It turns out into a kind of struggle, doesn't it?

So, any hack and trick that reduces memory and CPU consumption will be highly appreciated! I'm looking for additional parameters of `gr.Interface(...).launch` as well as css tricks and any other approaches.

**Describe the solution you'd like**  

**Additional context**  
I've tried this hack: `io.dependencies[0]["show_progress"] = False` from here: #2093 , and it works. But it disables the progress display completely; however, I still need the text `queue x/y` and the time estimation.

**Comment by jrhe** [comment]
@nickkolok - I know the AUTOMATIC1111/stable-diffusion-webui has done some hacks around this. I don't have time to dig them out right now but maybe you can start by looking at how the command line flag mentioned in the docs here works: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#loading

**Comment by abidlabs** [comment]
Hi @nickkolok it may be possible to do so with custom css / js, although we can't guarantee that this will work across all Gradio versions going forward. For example, something like this to hide the dancing squares svg works for me:

```py
import gradio as gr
import time

def slow(x):
    time.sleep(100)
    return x

with gr.Blocks(css="#textbox2 svg {display: none !important}") as demo:
    t = gr.Textbox()
    t2 = gr.Textbox(elem_id="textbox2")
    t.change(slow, t, t2)

demo.launch()
```

For a global solution, I would encourage you to take a look at what automatic1111 has done (thanks for the pointer @jrhe). At this point, I don't think we'd reduce the processing update frequency either or make it a custom parameter. But hopefully removing the dancing squares should help.

**Comment by nickkolok** [comment]
Thank you very much!
Also, to remove the rectangular progress bar (that updates about 10 times a second via CSS transform), I used smth like that:
```css
#output_container_0 div.eta-bar {
    display: none !important; transform: none !important;
}
```
where `output_container_0` is id of the element.

Just for reference for those who might be searching for the same thing :)

**Comment by abidlabs** [comment]
Thanks @nickkolok!
