### ISSUE TITLE
Remaining TODOs for JS client

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#3712]
Blockers for launch
- [x] Refactor API to allow access to job (for cancellation / status) and make it similar to the Python API
- [x] Add the equivalent of `.view_api()` to the JS client
- [x] Add both browser JS and node JS APIs to the "use via API" modal (should we to put both? I think so because installation is different and serialization is different, i.e. the Node client should send files while the JS client should base64)
- [x] Add ability to duplicate a Space for private use
- [x] Write a Guide / readme, analogous to https://gradio.app/getting-started-with-the-python-client/

**Comment by abidlabs** [comment]
The browser / node part makes sense. Glad to know that the usage is similar, we can just stick to a single JS entry then -- cc @aliabd 

> I don't think duplication should be in the client libraries, that feels out of scope for something that is really just for making API usage easier. That is space/repo management and should be done with hub libraries (the js hub library doesn't handle duplication right now but it would be easy to add).

I think it's fine as long as we include documentation and guidance on how to do this. I think this is a really important use case I think and right now, I wouldn't know really know how to do it with the huggingface_hub js library

**Comment by pngwn** [comment]
That's cool. Duplication is easy to add so I'll do that. The JS hub library doesn't support this but there is an API for it.

**Comment by freddyaboulton** [comment]
We can close right @pngwn @abidlabs ?

**Comment by abidlabs** [comment]
Yup, this is complete!
