### ISSUE TITLE
websocket connection failed if auth is enabled

### ISSUE THREAD

**Issue by datayes-liyuan1** [gradio-app/gradio#3716]
### Describe the bug

Hello all!
Gadio is awesome to help me build a website ASAP. 
Here's my case:
`import gradio as gr`

`def create_greeting(request: gr.Request):`
`    return gr.Markdown.update(value=f"Thanks for logging in, {request.username}")`

`with gr.Blocks() as demo:`
`    user_ip = gr.Markdown(value="Not logged in")`

`    demo.load(create_greeting, inputs=None, outputs=user_ip)`

`demo.queue(max_size=20, concurrency_count=20).launch(share=False, server_name='0.0.0.0', auth=('admin', 'admin'),`
`                                                     auth_message='Please enter your cloud gateway(datayes.com) account')`

'0.0.0.0' is set to expose the website in local network. 
If I access the server using 'http://localhost:7860', then it is perfect.
However, if 'http://10.20.102.132:7860/' is used, then there's an error.

![企业微信截图_16802308765244](https://user-images.githubusercontent.com/129239406/229010400-1ed23b9a-db00-49a8-87df-51e2182b39f7.png)

The browser console says: WebSocket connection to 'ws://10.20.102.132:7860/queue/join' failed: 

Moreover, if I disable the auth feature, then it works! 

`import gradio as gr`

`def create_greeting(request: gr.Request):`
`    return gr.Markdown.update(value=f"Thanks for logging in, {request.username}")`

`with gr.Blocks() as demo:`
`    user_ip = gr.Markdown(value="Not logged in")`

`    demo.load(create_greeting, inputs=None, outputs=user_ip)`

`demo.queue(max_size=20, concurrency_count=20).launch(share=False, server_name='0.0.0.0')`

Could anyone help me?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See description

### Logs

```shell
See description
```

### System Info

```shell
Gradio version: 3.23.0
System version: Windows 11
Browser version: Chrome 92.0.4515.131
```

### Severity

annoying

**Comment by datayes-liyuan1** [comment]
Note that the bug is still there after gradio is updated to 3.24.0

**Comment by Xuwznln** [comment]
The js script from Gradio seems not support non-https links. With auth enabled, you can use the share link to access, which is https, OR, make a ssl certificate and deploy behind nginx.

**Comment by luki28** [comment]
I also have this problem when running Automatic1111 behind Nginx as soon as I put Authelia in front of it for authentication. The issue is not present with earlier versions of gradio (tested Automatic1111 with gradio 3.16.2, which works fine with Authelia).

**Comment by freddyaboulton** [comment]
@pngwn @aliabid94 FYI I think this may be caused by the js client?

**Comment by wenwenyu** [comment]
Temporarily change the [routes.py](https://github.com/gradio-app/gradio/blob/da7d1df585790a1223c577f536fc9ae0ff88b9f1/gradio/routes.py#L170) file to `access-token-unsecure` made it work if '0.0.0.0' is set to expose.

before
`token = websocket.cookies.get("access-token")`
after
`token = websocket.cookies.get("access-token-unsecure")`

**Comment by datayes-liyuan1** [comment]
> Temporarily change the [routes.py](https://github.com/gradio-app/gradio/blob/da7d1df585790a1223c577f536fc9ae0ff88b9f1/gradio/routes.py#L170) file to `access-token-unsecure` made it work if '0.0.0.0' is set to expose.
> 
> before `token = websocket.cookies.get("access-token")` after `token = websocket.cookies.get("access-token-unsecure")`

Temporarily it works! Thanks very much!

**Comment by freddyaboulton** [comment]
Thanks for hunting this down for us @wenwenyu ! Fill open a PR for this

**Comment by ericbellet** [comment]
So let me see if I understand the error:

The problem that the Gradio server had a timeout of 1 minute for responding is due a limitation of HTTP protocol, right? 

So I have to expose my Gradio server in HTTPS, someone has an example? I have an ngnix server running in HTTPS but I don't know how to expose the Gradio server via HTTPS.

I tried to used the demo.queue() option but I got the error [websocket connection failed if auth is enabled](https://github.com/gradio-app/gradio/issues/3716#top)

Then I tried this:
How we should do this change with the current version of Gradio?
token = websocket.cookies.get("access-token-unsecure")

But in the current Gradio version the code is different and I don't know what to change.

**Comment by freddyaboulton** [comment]
Hi @ericbellet ! Please follow this guide on how to launch gradio with nginx -  https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx

I cannot reproduce the problem of the queue not working with authentication. Please make sure you're running the latest version of gradio. If you're still having problems, please file a minimal reproducible example in a new issue so that we can take a look!

**Comment by ericbellet** [comment]
> Hi @ericbellet ! Please follow this guide on how to launch gradio with nginx - https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx
> 
> I cannot reproduce the problem of the queue not working with authentication. Please make sure you're running the latest version of gradio. If you're still having problems, please file a minimal reproducible example in a new issue so that we can take a look!

Thanks, I'm using the latest version of Gradio gradio==3.35.2

To reproduce an error in local I don't have problem, the problem is inside a docker container in a EC2 instance where I have the Gradio server running with Ngnix and HTTP.  This is the code:

`import gradio as gr

class UI():

    def __init__(self):
      self.chat = Chatbot()
        
    def query(self, input_text):
            return self.chat.query(input_text)
        except Exception as e:
            return str(e) 
      
    def theme_conf(self):
        self.theme = gr.themes.Base(
            primary_hue=gr.themes.Color(c100="#bfdbfe", c200="#bfdbfe", c300="#93c5fd", c400="#60a5fa", c50="#E2F8F2", c500="#3b82f6", c600="#2563eb", c700="#1d4ed8", c800="#1e40af", c900="#1e3a8a", c950="#1d3660"),
        )

    def login_validation(self, username, password):
        if username in self.users and self.users[username] == password:
            self.username = username
            return True
        else:
            return False

    def launch(self):

        with gr.Blocks(theme=self.theme, title='TheCXLab Chat', 
                       css="footer {visibility: hidden}") as demo:
            chatbot = gr.Chatbot(label='The Chat')
            msg = gr.Textbox(show_label=False, max_lines=100)
            clear = gr.Button("Clear chat", variant="secondary")
            send = gr.Button("Send message", variant="primary")

            def user(user_message, history):
                return "", history + [[user_message, None]]

            def bot(history):
                bot_message = self.query(history[-1][0])
                history[-1][1] = bot_message
                time.sleep(1)
                return history

            msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
                bot, chatbot, chatbot
            )
            clear.click(lambda: None, None, chatbot, queue=False)
            send.click(user, [msg, chatbot], [msg, chatbot], queue=False).then(
                bot, chatbot, chatbot
            )
        demo.queue()launch(server_name='0.0.0.0', debug=True, auth=self.login_validation, show_error=True)

if __name__ == "__main__":
    UI().launch()`

I got this error in the console of the browser:

> index.js:462 WebSocket connection to 'wss://mywebsite.com/queue/join' failed:

**Comment by ericbellet** [comment]
I tried without auth:
`demo.queue()launch(server_name='0.0.0.0', debug=True, show_error=True`)

I got the same error:

`index.js:462 WebSocket connection to 'wss://chat.myweb.com/queue/join' failed: `
