### ISSUE TITLE
gradio.app website down

### ISSUE THREAD

**Issue by discdiver** [gradio-app/gradio#372]
gradio.app website down: 502 bad gateway error

Screenshot:
<img width="753" alt="Screen Shot 2021-11-16 at 8 04 31 AM" src="https://user-images.githubusercontent.com/7703961/141991241-20a58cfb-e814-4440-8576-2c8ed79f4106.png">

Location: Eastern US

Has been that way for at least 15 minutes. Was up last night.

**Comment by acrastt** [comment]
> Thanks for flagging this -- website should be up now

I still had the issue.
