### ISSUE TITLE
Document how to stream messages in `gr.Chatbot`

### ISSUE THREAD

**Issue by wlike** [gradio-app/gradio#3725]
Using version 3.18.0, the result of Chatbot is as follows:

<img width="1130" alt="企业微信截图_16787956948437" src="https://user-images.githubusercontent.com/6084282/225004655-8dc43f89-2c2c-4e46-ac61-4a25957f3dc0.png">

Using the latest version 3.21.0, the result of Chatbot is as follows:

<img width="1130" alt="企业微信截图_16787955851029" src="https://user-images.githubusercontent.com/6084282/225004836-4ee94733-beac-4400-93c1-1d0aeeed00ab.png">

The result of the latest version is worse than that of version 3.18.0.
With version 3.18.0, the request/question is right-aligned, and the response/answer is left-aligned. But with version 3.21.0, they are all left-aligned, which I think is not quite common and beautiful.

Besides, whether the chatbot component can support streaming display?

**Comment by abidlabs** [comment]
Hi @wlike yes we've updated the UI for the `Chatbot` component because for longer responses, having them both left-aligned significantly increases readability. Nevertheless, if you'd like to get the right-alignment, you may be able to do this via custom CSS. Here's an example:

```py
import gradio as gr

css = """
#chatbot .user {
    text-align: right
}
"""

with gr.Blocks(css=css) as demo:
    gr.Chatbot([
            ("Hello, chatbot", "Hi there"),
            ("How are you?", "I'm fine")
    ], elem_id="chatbot")
    
demo.launch()
```

<img width="578" alt="image" src="https://user-images.githubusercontent.com/1778297/229307503-78baa667-fd6f-43a6-bea8-2feaafb7b3a4.png">

The caveat is that custom CSS is not guaranteed to work across Gradio versions, as the DOM elements sometimes change names, etc. although we try not to do that too often.

**Comment by abidlabs** [comment]
In terms of supporting streaming, yes that is totally possible. Instead of a regular function, you use a generator and `yield` your chatbot messages in a loop. Here's an example: 

I think this is something we should document, so renaming this issue to reflect that.

**Comment by wlike** [comment]
> Hi @wlike yes we've updated the UI for the `Chatbot` component because for longer responses, having them both left-aligned significantly increases readability. Nevertheless, if you'd like to get the right-alignment, you may be able to do this via custom CSS. Here's an example:
> 
> ```python
> import gradio as gr
> 
> css = """
> #chatbot .user {
>     text-align: right
> }
> """
> 
> with gr.Blocks(css=css) as demo:
>     gr.Chatbot([
>             ("Hello, chatbot", "Hi there"),
>             ("How are you?", "I'm fine")
>     ], elem_id="chatbot")
>     
> demo.launch()
> ```
> 
> <img alt="image" width="578" src="https://user-images.githubusercontent.com/1778297/229307503-78baa667-fd6f-43a6-bea8-2feaafb7b3a4.png">
> 
> The caveat is that custom CSS is not guaranteed to work across Gradio versions, as the DOM elements sometimes change names, etc. although we try not to do that too often.

@abidlabs Thanks for your suggestion. But is it possible to adaptive resize the background according to the text length, instead of filling the whole line all the time?

**Comment by abidlabs** [comment]
> @abidlabs Thanks for your suggestion. But is it possible to adaptive resize the background according to the text length, instead of filling the whole line all the time?

This might be possible with some custom CSS as well, but I'm not sure exactly what that would require. 

We've added docs on streaming messages here: https://gradio.app/creating-a-chatbot/#add-streaming-to-your-chatbot so I'll go ahead and close this issue

**Comment by ericbellet** [comment]
How can adapt this Gradio code for using the callback FinalStreamingStdOutCallbackHandler?


`import gradio as gr
import time
from langchain.agents import load_tools, initialize_agent, AgentType
from langchain.chat_models import ChatOpenAI
from langchain.callbacks.streaming_stdout_final_only import FinalStreamingStdOutCallbackHandler
from dotenv import load_dotenv


def myfun(input):
    llm = ChatOpenAI(temperature=0, streaming=True, callbacks=[FinalStreamingStdOutCallbackHandler()])
    tools = load_tools(["wikipedia"], llm=llm)
    agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, memverbose=False)
    return agent.run("Who was Napoleon?")


with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.Button("Clear")

    def user(user_message, history):
        return "", history + [[user_message, None]]

    def bot(history):
        bot_message = myfun(input=history[-1][0])
        history[-1][1] = ""
        for character in bot_message:
            history[-1][1] += str(character)
            time.sleep(0.03)
            yield history

    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        bot, chatbot, chatbot
    )
    clear.click(lambda: None, None, chatbot, queue=False)
    
demo.queue()
demo.launch()`

**Comment by evanbrociner** [comment]
@ericbellet did you ever figure this out?

**Comment by Castolus** [comment]
> Hi @wlike yes we've updated the UI for the `Chatbot` component because for longer responses, having them both left-aligned significantly increases readability. Nevertheless, if you'd like to get the right-alignment, you may be able to do this via custom CSS. Here's an example:
> 
> ```python
> import gradio as gr
> 
> css = """
> #chatbot .user {
>     text-align: right
> }
> """
> 
> with gr.Blocks(css=css) as demo:
>     gr.Chatbot([
>             ("Hello, chatbot", "Hi there"),
>             ("How are you?", "I'm fine")
>     ], elem_id="chatbot")
>     
> demo.launch()
> ```
> 
> <img alt="image" width="578" src="https://user-images.githubusercontent.com/1778297/229307503-78baa667-fd6f-43a6-bea8-2feaafb7b3a4.png">
> 
> The caveat is that custom CSS is not guaranteed to work across Gradio versions, as the DOM elements sometimes change names, etc. although we try not to do that too often.

Hi @abidlabs. I know it may be out of context, but i don´t want to open a new query on GH. I´m implementing a history for the chatbot, where questions anda answers are registerded in JSON as a Tuple. So far i´ve achieved it, but i can´t  find the way to show the conversation on the chatbot. Could you give me a hint? here the code:

                    chatbot = gr.Chatbot(
                        label=label_text,
                        show_copy_button=True,
                        elem_id="chatbot",
                        render=False,
                        avatar_images=(None, AVATAR_BOT),
                    )

                    additional_inputs = [mode, upload_button, run_mode, cancel_auto, question_button]
                    if settings().ui.show_system_prompt:
                        additional_inputs.insert(2, system_prompt_input)

                    _ = gr.ChatInterface(
                        self._chat,
                        chatbot=chatbot,
                        additional_inputs=additional_inputs,
                    )
                    
   That "question_button" on additional_inputs is the click to any of the questions of the history bar, which is so defined:
   
           ) as blocks:
            with gr.Row():
                gr.HTML(f"<div class='logo'/><img src={logo_svg} alt=cimGPT></div")

            with gr.Row(equal_height=False):
                with gr.Column(scale=3):
                    with gr.Column(elem_classes="history-scroll"):
                        chat_history = self.load_history_from_file()
                        for i, conv in enumerate(chat_history):
                            question_button = gr.components.Button(
                                f"{conv[0]}",
                                visible=True
                            )
                            question_button.click(
                                self.show_conversation,
                                inputs=gr.State(i)
                            )
   For now, i have "manual" solution which is not nice. I click on the conversation, then i click on "submit" and it shows the answer on the chatbot. The question is not shown because the Message bar is empty when i click on "submit". I know i´m close, but also a bit desperate since i cannot find a way to achieve it. If you have an idea, i´d be more than thankfull.

KR,
Javier
