### ISSUE TITLE
Can't use argparse in reload mode

### ISSUE THREAD

**Issue by LZY-the-boys** [gradio-app/gradio#3726]
### Describe the bug

When I use argparse in reload mode, it cause errors, for example:
```
import gradio as gr
import argparse
with gr.Blocks() as demo:
    gr.Markdown("# Greetings from Gradio!")
    inp = gr.Textbox(placeholder="What is your name?")
    out = gr.Textbox()

    inp.change(fn=lambda x: f"Welcome, {x}!", 
               inputs=inp, 
               outputs=out)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--a", type=str, default="decapoda-research/llama-7b-hf")
    parser.add_argument("--b", type=str, default="./lora-Vicuna/checkpoint-3000")
    parser.add_argument("--c", type=int, default=1)
    parser.add_argument("--e", type=int, default=1)
    parser.add_argument("--d", type=int, default=1)
    args, unknown = parser.parse_known_args()
    demo.launch()
```

When I launch it using `gradio tmp.py --a 1` ， it throws 
```
ERROR:    Error loading ASGI app. Attribute "--a.app" not found in module "tmp".
```
It seems that it interpet `--a 1` to "--a.app" . I don't find any description in documents

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

above code 

### Logs

```shell
ERROR:    Error loading ASGI app. Attribute "--a.app" not found in module "tmp".
```

### System Info

```shell
linux
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @LZY-the-boys ! Thanks for filing.

I don't think we'll be able to support this use case. What `gradio` command does is delegate to uvicorn's run-in-reload mode, which imports the `app` object from your file, so the part in the `if __name__ == '__main__'` clause will not be run. Also, uvicorn's command line does not support arbitrary extra arguments ([docs](https://www.uvicorn.org/#usage)).

What I suggest you do is load those variables via an environment variable or from a config file!

**Comment by LZY-the-boys** [comment]
OK, thanks for help
