### ISSUE TITLE
Something went wrong Connection errored out.

### ISSUE THREAD

**Issue by ttjygbtj** [gradio-app/gradio#3727]
### Describe the bug

启动程序后，能打开页面正常显示，上传文档后无法发送请求
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/66538098/229296702-36166ed4-d077-4ee8-9af3-d263b3039dc5.png">

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Reproduction

<img width="802" alt="image" src="https://user-images.githubusercontent.com/66538098/229297216-9ac29b00-8e58-4477-b3a7-45cffa78678a.png">
<img width="789" alt="image" src="https://user-images.githubusercontent.com/66538098/229297248-7fd2c292-d3a4-4c46-9aa0-34218917f130.png">

### Logs

```shell
控制台报错[Error] WebSocket connection to 'ws://localhost:62694/queue/join' failed: There was a bad response from the server. (x4)
```

### System Info

```shell
gradio:3.24.1
ProductName:macOS
ProductVersion:13.3
BuildVersion:22E252
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @ttjygbtj there isn't enough information here for us to address this issue. Please provide step-by-step instructions with code examples (not just screenshots) so that we can reproduce the issue.

**Comment by ttjygbtj** [comment]
### Describe the bug

启动程序后，能打开页面正常显示，但是上传文档或者发送提问法会出错“Something went wrong Connection errored out.”


### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Reproduction

按照正常步骤：
git clone https://github.com/binary-husky/chatgpt_academic.git
cd chatgpt_academic
python -m pip install -r requirements.txt 
python main.py

config.py的配置是：
USE_PROXY = True

### Screenshot

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/66538098/229296702-36166ed4-d077-4ee8-9af3-d263b3039dc5.png">
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/66538098/229327959-e8d3857d-9495-4c28-8a3f-cf1a8d294248.png">

### Logs

```shell
控制台报错[Error] WebSocket connection to 'ws://localhost:62694/queue/join' failed: There was a bad response from the server. (x4)
```


### System Info

```shell
gradio:3.24.1
ProductName:macOS
ProductVersion:13.3
BuildVersion:22E252
```


### Severity

annoying

**Comment by DSXiangLi** [comment]
when I process the file for a long time, same error occured. In the log I can see the function is still running, while in the front end, the output file block is showing error.

**Comment by Imaybehatemyself** [comment]
i think this is happening across hugging face and other gradio projects

(please someone fix this im probably boutta die)

**Comment by zzz-zyq** [comment]
I also encountered the same problem, it seems that when the backend runs for too long, the front-end will encounter this error. I haven't found a solution yet.

**Comment by Cominclip** [comment]
try to install gradio==4.42.0
