### ISSUE TITLE
How do I create upload button for doc/pdf/ csv in the blocks. we have documentation around input text but not uploading single file

### ISSUE THREAD

**Issue by pearl04** [gradio-app/gradio#3729]
- [ ] I have searched to see if a similar issue already exists.
Yes, already done that , cant find anything

**Is your feature request related to a problem? Please describe.**  
A clear and concise description of what the problem is.
I have been trying to create upload button for doc/pdf/ csv inside the gr.blocks , but getting lots of errors and there is no documentation around that. 

**Describe the solution you'd like**  
A documentation/code of how we can add a doc/pdf/csv upload button and launch it using gr.blocks

**Additional context**  
[Testing on docx data - Jupyter Notebook.pdf](https://github.com/gradio-app/gradio/files/11130975/Testing.on.docx.data.-.Jupyter.Notebook.pdf)

Yes, I have my current code, attaching that for reference.

**Comment by abidlabs** [comment]
Hi @pearl04 have you tried:

```py
gr.UploadButton(file_types=[".pdf",".csv",".doc"])
```

**Comment by pearl04** [comment]
Yeah I tried that :( 

Nothing is getting picked up . Could you please guide me whats wrong in my code please . So just reiterating codes I am using below (context is create a chatbot interface , that picks up say doc file and you can ask questions from it )

```
from pathlib import Path
from llama_index import download_loader
DocxReader = download_loader("DocxReader")
loader = DocxReader()
```

```
#build chatbot function to create index
def build_the_bot(input_text):
    documents = loader.load_data(file=Path(input_text))
    global index
    service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)
    index = GPTSimpleVectorIndex.from_documents(documents, service_context=service_context)
    return('Index saved successful!!!')

```

```
#preserve chat history and create response
def chat(chat_history, user_input):
    bot_response = index.query(user_input)
      #print(bot_response)
    response = ""
    for letter in ''.join(bot_response.response): #[bot_response[i:i+1] for i in range(0, len(bot_response), 1)]:
        response += letter + ""
        yield chat_history + [(user_input, response)]

```
        

```
#created block, added inout uploader button 
def upload_file(files):
    file_paths = [file.name for file in files]
    return file_paths
with gr.Blocks() as demo:
    gr.Markdown('# Q&A Bot with OpenAI Models')
    with gr.Tab("Input Text Document"):
        file_output = gr.File()
        upload_button=gr.UploadButton(file_types=[".pdf",".csv",".docx"])
        upload_button.upload(upload_file, upload_button, file_output)
        text_output = gr.Textbox()
        text_button = gr.Button("Build the Bot!!!")
        text_button.click(build_the_bot, file_output, text_output)
    with gr.Tab("Knowledge Bot"):
        chatbot = gr.Chatbot()
        message = gr.Textbox ("What is this document about?")
        message.submit(chat, [chatbot, message], chatbot)
demo.queue().launch(debug = True)

```

**Comment by pearl04** [comment]
hey @abidlabs , any suggestions/ thoughts please. Thank you :)

**Comment by pearl04** [comment]
I changed the code a bit , but still upload isnt working. Maybe the output path isnt getting fetched properly while creating index. Tried downgrading gradio to  3.24.1 version  and i am using jupyter notebook FYI. 

<img width="1341" alt="Screenshot 2023-04-04 at 18 39 09" src="https://user-images.githubusercontent.com/30389441/230116160-019ccf04-7d98-4035-9e45-396c9af87a4e.png">

@freddyaboulton , @yvrjsharma FYI

**Comment by yvrjsharma** [comment]
It seems that in versions after 3.18.0, the uploadbutton.upload() is not working properly on a colab/notebook. This doesn't seem to be the case for Spaces. I tried with 3.24.1 on Spaces and it works perfectly fine for me.

**Comment by freddyaboulton** [comment]
Colab is probably blocking the `upload` route cc @aliabid94

**Comment by abidlabs** [comment]
Interesting, is there a minimal code sample I can try @yvrjsharma?

**Comment by yvrjsharma** [comment]
Sure, this is what I used. With versions above 3.18.0, like 3.19.0, 3.19.1 etc the upload button doesn't seem to pick up the files. -
```
!pip install gradio==3.18.0 --q
!pip show gradio

import gradio as gr

def upload_file(files):
    print("here")
    file_paths = [file.name for file in files]
    return file_paths

with gr.Blocks() as demo:
    file_output = gr.File()
    upload_button = gr.UploadButton("Click to Upload a File", file_types=["image", "video"], file_count="multiple")
    upload_button.upload(upload_file, upload_button, file_output)

demo.launch(debug=True)
```

**Comment by yvrjsharma** [comment]
https://user-images.githubusercontent.com/48665385/230173488-e6076ce3-ce14-4c09-a565-5abc199df48e.mp4
