### ISSUE TITLE
Disable submit when the inference is in progress

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#373]
### Discussed in https://github.com/gradio-app/gradio/discussions/369

<div type='discussions-op-text'>

<sup>Originally posted by **harveenchadha** November 16, 2021</sup>
Hi,

I think the submit button should be disabled once the inference is in progress to disallow multiple clicks at once. Also is it possible to show a much bigger progress bar either as a pop up which says "Loading result"?</div>

**Comment by aliabid94** [comment]
It is already the case you cannot click the submit button while an inference is in progress. Can you confirm you are using the latest version @harveenchadha

**Comment by abidlabs** [comment]
Closing. Feel free to reopen if this is an issue for you in the latest version of gradio, @harveenchadha. Thanks!

**Comment by kambleakash0** [comment]
Hey @abidlabs, does Gradio have something like this for when a file upload is in progress?

**Comment by abidlabs** [comment]
Hi @kambleakash0 not yet, but we have an issue for that here: #3382
