### ISSUE TITLE
Better documentation for custom css

### ISSUE THREAD

**Issue by AscendantAI-Robbie** [gradio-app/gradio#3745]
### Describe the bug

The simple demo from the "The elem_id amd elem_classes Arguments", (amd should be updated to and I'm guessing), does not actually set the font size. It allocates space for the font size but the text itself is still the same size.

Setting the gradio container to fill the width does not work unless marked as important.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
with gr.Blocks(css="#warning {background-color: red} .feedback {font-size: 74px} .gradio-container {max-width: none;") as demo:
    box1 = gr.Textbox(value="Good Job", elem_classes="feedback")
    box2 = gr.Textbox(value="Failure", elem_id="warning", elem_classes="feedback")
demo.launch()
```

```
with gr.Blocks(css="#warning {background-color: red} .feedback {font-size: 74px} .gradio-container {max-width: none  !important;") as demo:
    box1 = gr.Textbox(value="Good Job", elem_classes="feedback")
    box2 = gr.Textbox(value="Failure", elem_id="warning", elem_classes="feedback")
demo.launch()
```

### Screenshot

![Screenshot 2023-04-03 at 19-54-30 Gradio](https://user-images.githubusercontent.com/48957936/229666365-53d509ce-07c1-4688-9903-640d3bbdb9a4.png)
![Screenshot 2023-04-03 at 19-52-43 Gradio](https://user-images.githubusercontent.com/48957936/229666391-ff3fc9f7-968d-4bc0-8314-09b651d3ec9d.png)

### Logs

```shell
There are no logs since this doesn't crash. It just doesn't work.
```

### System Info

```shell
python=3.10.6
gradio=3.24.1
Windows10 localhost
Firefox
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Hi @AscendantAI-Robbie thanks for pointing this out. Yes, for `elem_classes`, you may need to add `!important` as occasionally css rules can conflict. I'm not sure why the font size is not being updated, we'll check on that. I think we should improve the documentation in this section @aliabid94 in several ways:

* document the fact that you may need to use `!important` with `elem_classes`
* fix the font-size issue
* and generally discourage the use of `elem_classes` and `elem_id` because it may not work across gradio versions (unlike theming)

**Comment by nativexie** [comment]
> Hi @AscendantAI-Robbie thanks for pointing this out. Yes, for `elem_classes`, you may need to add `!important` as occasionally css rules can conflict. I'm not sure why the font size is not being updated, we'll check on that. I think we should improve the [documentation in this section](https://gradio.app/custom-CSS-and-JS/) @aliabid94 in several ways:
> 
> * document the fact that you may need to use `!important` with `elem_classes`
> * fix the font-size issue
> * and generally discourage the use of `elem_classes` and `elem_id` because it may not work across gradio versions (unlike theming)

how to use `!important` with `elem_classes` ? I tried variy ways, but it still doesn't work ?

**Comment by abidlabs** [comment]
Hi @nativexie can you share your code?
