### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Woisek** [gradio-app/gradio#3749]
### Describe the bug

I'm not absolutely sure, if this is here the right place (please tell me where to put it otherwise), but it's getting now so unbelievable annoying, I have to tell somewhere since no one seems to care about it.

I'm an [Automatic1111 User ](https://github.com/AUTOMATIC1111/stable-diffusion-webui), A1111 uses Gradio as plattform.
Since months now, it is not possible that Gradio creates directories if needed.
In A1111 there is an option to define a directory for temporay files. In my case this is defined like so: T:\systemp\sd-temp-files\
Now, the folder T:\systemp\ is existing. But the folder sd-temp-files will be deleted to remove those temp files. The problme now is: This sd-temp-files folder **is not been created if not existing**. So, every other function/extension that want to use this, get's an error -> FileNotFoundError: [Errno 2] No such file or directory: 'T:\\systemp\\sd-temp-files\\tmpdycp6gra.png'

So it's an giant urge to tell Gradio it should create directories if they are setup in the settings.

I sincerely hope that someone can finally fix this, thanks.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use A1111

### Logs

```shell
Traceback (most recent call last):███████████████████████████████████████████████████| 110/110 [02:21<00:00,  2.52s/it]
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 3954, in postprocess
    file = processing_utils.save_pil_to_file(img)
  File "I:\Super SD 2.0\stable-diffusion-webui\modules\ui_tempdir.py", line 52, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "F:\Programme\Python310\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "F:\Programme\Python310\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "F:\Programme\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'T:\\systemp\\sd-temp-files\\tmpdycp6gra.png'
```

### System Info

```shell
v3.23, Win10, Firefox
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Hi @Woisek, I'm sorry to hear about the trouble that this has caused you! In theory, we should be able to make a change to the `save_pil_to_file` function to ensure that the directory exists before saving an image to that directory. However, this has two limitations:

(1) There may be other functions that are used in Automatic1111 webui or its extensions to save images, and this wouldn't necessarily fix those
(2) And, the bigger problem, is that Automatic1111 webui is pinned to a Gradio version so even if we were to release a fix, it wouldn't get applied to the webui until much later

The more appropriate place to make this fix is in Automatic1111 because, as you mentioned, 

> In A1111 there is an option to define a directory for temporay files.

When you specify the temporary directory, the webui should create that directory if it does not exist. I wonder if you could modify the code yourself locally to do this change? It's only a matter of adding this line in the appropriate place:

```py
import os
path = ...
os.makedirs(path, exist_ok=True)
```

Finally, I'll mention that if you know the directory ahead of time (e.g. it's *always* `T:\systemp\sd-temp-files\`), then you can simply run this before you launch the webui:

```py
import os
path = 'T:\systemp\sd-temp-files\' 
os.makedirs(path, exist_ok=True)
```

**Comment by abidlabs** [comment]
As a result, I'll close this issue as not planned. But feel free to respond here and we'll try to help however we can!

**Comment by abidlabs** [comment]
>When you specify the temporary directory, the webui should create that directory if it does not exist. I wonder if you could modify the code yourself locally to do this change? It's only a matter of adding this line in the appropriate place:

This would be in the Automatic1111 webui repo, not in Gradio. (Because the webui repo uses a pinned version of Gradio, I don't think any changes in the Gradio repo directly would be reflected in the webui)

**Comment by Woisek** [comment]
Ah, ok ... what a bummer ... :(
So I have to rely on A1111 to make the change ... and if this is going to happen, who knows ...
Thanks anyway to clearify.

**Comment by abidlabs** [comment]
Well you could make the change to your local version of automatic1111, you don't need to wait until it's merged into the repo.

**Comment by Woisek** [comment]
Yes, but like before, I don't know into which file I have to dig into to change it ... :/
I'm a programmer, but I don't know anything about Gradio, WebUI or Python ... &)

**Comment by leetesla** [comment]
I solved the problem just by creating the missing directory.

**Comment by ibadmore** [comment]
@leetesla what was the directory that you created? having the same issue

**Comment by flydragonle** [comment]
File "C:\Program Files\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\gradio\\tmpd7wl1wwv.png'

**Comment by AlanZhou2022** [comment]
the same problem also happens when I use ultimate SD upscale to optimize my picture, and I cannot save the modified picture (FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/rl/9htrh67s3fd7z1c4kvy5kttw0000gn/T/gradio/tmpgv1ug2um.png'), also don't know how to solve the problem.

**Comment by AlanZhou2022** [comment]
the same problem occurred when I used ultimate SD upscale to optimize my picture, and I cannot save the modified picture (FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/rl/9htrh67s3fd7z1c4kvy5kttw0000gn/T/gradio/tmpgv1ug2um.png'), I also don't know how to solve the problem.

**Comment by leetesla** [comment]
> the same problem occurred when I used ultimate SD upscale to optimize my picture, and I cannot save the modified picture (FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/rl/9htrh67s3fd7z1c4kvy5kttw0000gn/T/gradio/tmpgv1ug2um.png'), I also don't know how to solve the problem.

According to the error message, the directory **/var/folders/rl/9htrh67s3fd7z1c4kvy5kttw0000gn/T/gradio** does not exist. To solve this problem, you need to create it manually.

**Comment by AlanZhou2022** [comment]
Thanks, but the problem still not be solved.


---------------- 

----------原邮件信息----------
发件人："chrise" ***@***.***>
收件人："gradio-app/gradio" ***@***.***>
抄送人："Alan Zhou" ***@***.***>, "Comment" ***@***.***>
主题：Re: [gradio-app/gradio] FileNotFoundError: [Errno 2] No such file ordirectory (Issue #3749)
发送时间：2023-07-29 18:50:54

 > the same problem occurred when I used ultimate SD upscale to optimize my picture, and I cannot save the modified picture (FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/rl/9htrh67s3fd7z1c4kvy5kttw0000gn/T/gradio/tmpgv1ug2um.png'), I also don't know how to solve the problem.

According to the error message, the directory **/var/folders/rl/9htrh67s3fd7z1c4kvy5kttw0000gn/T/gradio** does not exist. To solve this problem, you need to create it manually.

**Comment by iridescentdaisyz** [comment]
hi Alan, is this issue solved? I also encounter this isse using sadtalker on sdwebui (mac version), when I generate videos, it pop error02  FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/mg/4y5bf81527s9gh0g4g_rsp8h0000gn/T/gradio/tmpfwq057tb.png'

I tried creating a gradio folder, but it doesn't fix the error.

just wondering how do you deal with it and what is your workaround?

thanks!

**Comment by iridescentdaisyz** [comment]
> File "C:\Program Files\Python310\lib\tempfile.py", line 256, in _mkstemp_inner fd = _os.open(file, flags, 0o600) FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\ADMINI~1\AppData\Local\Temp\gradio\tmpd7wl1wwv.png'

do you have a solution for this?
thx

**Comment by leetesla** [comment]
@iridescentdaisyz 
1. create the non-existing directory, which according to the error message you provided is "C:\Users\ADMINI~1\AppData\Local\Temp\gradio\".
2. if the error still exists, copy an image to the directory you just created and rename it to the name which according to the error message you provided is "tmpd7wl1wwv.png".

**Comment by AlanZhou2022** [comment]
> hi Alan, is this issue solved? I also encounter this isse using sadtalker on sdwebui (mac version), when I generate videos, it pop error02 FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/mg/4y5bf81527s9gh0g4g_rsp8h0000gn/T/gradio/tmpfwq057tb.png'
> 
> I tried creating a gradio folder, but it doesn't fix the error.
> 
> just wondering how do you deal with it and what is your workaround?
> 
> thanks!

still not solved, probably ultimate SD upscale is not  compatible with MacBook, and I choose to use the default SD upscale, not to use ultimate SD upscale. Just too many bugs for Stable diffusion running on Mac, Controlnet doesn't work either, just hope the developers to solve the problems as soon as possible.

**Comment by iridescentdaisyz** [comment]
> 

tried this, not working - -
