### ISSUE TITLE
App not launching

### ISSUE THREAD

**Issue by FisayoN** [gradio-app/gradio#375]
Hello Team, i am trying to launch my first gradio model yet for some reason it keeps saying cannot implement and giving me error messages and i don't know how to rectify this. Please help

**Comment by FisayoN** [comment]
Also, i was charged for this transaction and i never got anything done. it is really unfair

**Comment by aliabid94** [comment]
Really sorry to hear that FisayoN. Would love to help you out to see where the error happened or give you a refund. Can you provide details on what you uploaded and the error you got?

Btw, we are directing users to use huggingface.co/spaces instead gradio hosted because they provide better infrastructure and are completely free.

**Comment by FisayoN** [comment]
i was trying the image classifier example as taught by dataprofessor and for some reason i kept getting errors

**Comment by FisayoN** [comment]
the error message was that the launch could not be implemented

**Comment by aliabid94** [comment]
Taking a look.

**Comment by aliabd** [comment]
Hey @FisayoN, we have deprecated Gradio Hosted and notified customers. Existing interfaces will only remain live until December 31st, 2021 but no new interfaces can be created. All December and November payments were refunded (may take a few days to process) and all subscriptions were canceled. We highly encourage you to use Huggingface Spaces instead, a great and free resource for permanent hosting of your Gradio demos. More info on spaces [here](https://huggingface.co/blog/gradio-spaces) and [here](https://huggingface.co/docs/hub/spaces).

I will close this issue, but if you have any questions feel free to add a comment.
