### ISSUE TITLE
remove history on clicking button in gradio app

### ISSUE THREAD

**Issue by markwsac** [gradio-app/gradio#3750]
I am trying to remove history when clear button is clicked. In the code below, history is not shown in the app when clear button is clicked but it saves at backend and when I click on submit button again, it shows prior history as well.

```
def cc(input, history):
    history = history or []
    s = list(sum(history, ()))
    s.append(input)
    inp = ' '.join(s)
    output = chat(inp)
    history.append((input, output))
    return history, history
    
with gr.Blocks() as demo:
    gr.Markdown("""<h1><center>ChatGPT</center></h1>""")
    chatbot = gr.Chatbot()
    message = gr.Textbox(placeholder=prompt)
    state = gr.State()
    with gr.Row():
        submit = gr.Button("Submit")
        clear = gr.Button("Clear")
    clear.click(lambda: None, None, chatbot, queue=False)
    submit.click(cc, inputs=[message, state], outputs=[chatbot, state])

demo.launch(inbrowser=True, debug=True)

```

**Comment by abidlabs** [comment]
Hi @markwsac, you'll need to make a small change to the `clear.click` line to also set the state to `None`, like this:

```py
    clear.click(lambda: (None, None), None, [chatbot, state], queue=False)
```

That should fix it. But by the way, for general questions like this (that are not feature requests or bug reports), please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
