### ISSUE TITLE
`lines` parameter in `Textbox` doesn't apply consisently over multiple updates of the component value

### ISSUE THREAD

**Issue by ola13** [gradio-app/gradio#3751]
### Describe the bug

I have a `Textbox` component that hosts varied-length text so I set initial lines number to something very high:

```
text = gr.Textbox(visible=False, label="Datapoint", lines=500)
```

However after updating the `value` of the component multiple times I see that sometimes the initial `lines` value is not observed.

Setting `max_lines` parameter as suggested by @dawoodkhan82 seems to help.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Here's the full app where reproduction can be observed (note though that it's under active development so might change) https://huggingface.co/spaces/HuggingFaceGECLM/dataset_explorer/blob/main/app.py#L154

### Logs

```shell
n/a
```

### System Info

```shell
Gradio version: 3.23.0
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Hi @ola13 I believe this issue has been resolved in 3.24. Would you please try upgrading the gradio version in your README file and see if that fixes the issue?

**Comment by ola13** [comment]
Hey @abidlabs it seems it is resolved indeed!

**Comment by abidlabs** [comment]
Glad to hear it! Closing this issue
