### ISSUE TITLE
Dropdown select options are cut off by container if overflow is hidden.

### ISSUE THREAD

**Issue by CurtisDS** [gradio-app/gradio#3756]
### Describe the bug

The dropdown is in a tab, the tab has overflow set to hidden and when you open the dialog the options get cut off because they are in the DOM at the same level as the dropdown.

![image](https://user-images.githubusercontent.com/20732674/229901581-c7a2e4aa-bfe2-4c9d-be4b-3128b934dedb.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Step 1: go to https://huggingface.co/spaces/gradio/dropdown_component
Step 2: Inspect element and set the containing div to overflow:hidden
Step 3: open the dropdown

![image](https://user-images.githubusercontent.com/20732674/229905462-6e2b6ec1-6a09-4f13-8aeb-ad831023b380.png)

The options are cut off

### Logs

```shell
No errors
```

### System Info

```shell
gradio: 3.23.0
```

### Severity

annoying

**Comment by abidlabs** [comment]
It doesn't look like this is an issue in the latest version of `gradio` -- @CurtisDS can you confirm?

Here's the repro I tried:

```py
import gradio as gr

with gr.Blocks() as demo:
    with gr.Tab("Test"):
        gr.Dropdown(["abc", "def", "ghi"])
        
demo.launch()
```

**Comment by abidlabs** [comment]
Will close for now, please let us know if this is still an issue in the latest version of `gradio` and we can reopen. Thanks!

**Comment by CurtisDS** [comment]
It looks like it is no longer an issue 👍
