### ISSUE TITLE
`cancels` not literally canceling running function 

### ISSUE THREAD

**Issue by markwsac** [gradio-app/gradio#3758]
### Describe the bug

The option `cancels` is canceling running function but it saves the result in history. It should be the running function to be canceled along with its result in history when `stop` button is clicked.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`demo.queue().launch(inbrowser=True, debug=True)
`

### Logs

```shell
No error
```

### System Info

```shell
Gradio Version : 3.24.1
OS : Windows
Browser : Chrome
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @markwsac, `cancels` only cancels functions that have not yet run (or generators that are iterating). But functions that have started running continue running in the background.

**Comment by markwsac** [comment]
thanks for your prompt response. Is there any workaround to cancel already started running function?

**Comment by abidlabs** [comment]
Not as far as I know -- if the function has already started, there's no general way that we cancel it cleanly (e.g. without producing intermediate results that could affect downstream interactions with the Gradio app) so we don't support that feature. But in your case, what you could do is do some cleanup of the history when the `.stop()` button is clicked to clean up partial results from the history. For example, you could set a flag to determine if the `ChatGPT()` function has completed successfully and if not, remove the last message from the history. Lmk if that makes sense

**Comment by markwsac** [comment]
Thank you. I am a bit new to gradio, would be a great help if you guide me how to clean up partial results from the history when a button is clicked.
