### ISSUE TITLE
gr.File's orig_name is equal to name, instead of being just the original file name

### ISSUE THREAD

**Issue by hithereai** [gradio-app/gradio#3766]
### Describe the bug

Before the latest gradio changes doing file.orig_name would give you just the file name, as in "some_video.mp4", where name would give you full absolute path to the temp file location, e.g c:/users/appdata/temp/dajkjfowfwasf_some_video.mp4". 

Now, with gradio 3.23, I started having a weird bug, and after some testing this is the issue:

`{'file': <_io.BufferedRandom name='C:\\Users\\jklgj\\AppData\\Local\\Temp\\tmpho0xcpu1'>, 'name': 'C:\\Users\\jklgj\\AppData\\Local\\Temp\\e13f8f9131d4524f28b36e03fd952e3b2f46f05c\\5c0f51c8-3359-44fd-9701-a6be986271c9_Mediump5lxi7ic_FILM_x200.mp4', 'delete': False, '_closer': <tempfile._TemporaryFileCloser object at 0x000001E58DEB5F90>, 'orig_name': 'C:\\Users\\jklgj\\AppData\\Local\\Temp\\tmpa7lqopna\\0b1e47e57440c517aa8b1cea4b755b8ca0c4a4d5\\5c0f51c8-3359-44fd-9701-a6be986271c9_Mediump5lxi7ic_FILM_x200.mp4'}`

Note how name and orig_name are both full abs paths. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Upload an mp4 using gr.File, print its name and orig_name; They should be different, but they are not. 

### Logs

```shell
No logs available.
```

### System Info

```shell
Gradio 3.23.0, Auto1111 webui, Deforum extension, windows 11 22h2, rtx 4090.
```

### Severity

serious, but I can workaround it.

**Comment by abidlabs** [comment]
Thanks @hithereai! We'll look into it.

**Comment by hithereai** [comment]
> Thanks @hithereai! Filenames are supposed to be preserved so there is no need for `.orig_name` but it looks like in your case, they are not being preserved. We'll look into it.

After some more testing, your old version changed the original file name upon uploading using the gr.File UI, so we needed to have orig_name to really get access to the original file name.

However, with gradio 3.23 you make a new folder for each file, and preserve the original file name, so I can easily access it. 

So it's not a major issue, but I believe lots of people used orig_name, which is now ruined 👯 

Thanks for looking into it!

**Comment by abidlabs** [comment]
> After some more testing, your old version changed the original file name upon uploading using the gr.File UI, so we needed to have orig_name to really get access to the original file name.

> However, with gradio 3.23 you make a new folder for each file, and preserve the original file name, so I can easily access it.

Exactly! 

> So it's not a major issue, but I believe lots of people used orig_name, which is now ruined 👯

For backwards compatibility, we can set this to the base name, but yeah hopefully not as important now

**Comment by abidlabs** [comment]
Revisiting this, I think we can close this issue as the breakage seems to have not caused widespread issues, and there's a better solution, which is to use the file name of the file directly
