### ISSUE TITLE
Unspecified files are adding in gr.File()

### ISSUE THREAD

**Issue by yesdeepakmittal** [gradio-app/gradio#3767]
### Describe the bug

I have specified only `.png`, `.pdf`, `.jpg`, and `.jpeg` format files to be uploaded or dragged-n-dropped. 

![image](https://user-images.githubusercontent.com/50262096/230112394-195f70ad-6e78-4f5a-9a86-a972d21b2279.png)

But users are able to upload other file formats also by changing the file type or by dragging-n-dropping unspecified files. 

![image](https://user-images.githubusercontent.com/50262096/230112214-c407d3dc-21e0-412a-b6be-0d4ce5f3f1db.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
gr.File(file_count="single", file_types=[".pdf", ".png",'.jpg','.jpeg'],type = 'binary',show_label = False)
```

### Logs

```shell
it is generic
```

### System Info

```shell
gradio==3.24.1
OS = Windows
Browser = Google Chrome
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @yesdeepakmittal browsers can't really force users to upload files of a given type, they merely treat the filetypes as suggestions as you've pointed out. If it's super important to validate the filetype, you can do this as part of your function in the backend.

Source: https://stackoverflow.com/questions/4328947/limit-file-format-when-using-input-type-file
