### ISSUE TITLE
Publish UI components to npm?

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3768]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
The base Gradio components are surprisingly competent when used in a separate Svelte project. However I had to do some path hackery to import them with `npm`

- Adding `gradio` as a git submodule to my project
- Creating a new `pnpm` workspace in my project's root so the `workspace:` specifiers in `package.json` worked
- Running `pollen` and manually copying its output into `node_modules/@gradio/theme/src`
- Adding in `gradio`'s default theme CSS to my application's page

But after that they work fine, and are very simple to drop in. With Svelte it seems like a lot of the current UI frameworks either lack important elements or are too hard to style, it would be nice to reuse Gradio's components since they're so well abstracted

**Describe the solution you'd like**  
Just publish the `ui` packages on NPM versioned against gradio's current version. No expectation that Gradio create an entire UI design paradigm or cater to the interests of UI designers outside of its needs, only having the packages installable from NPM is enough

**Additional context**  
N/A

**Comment by abidlabs** [comment]
We do publish the js components now! Although they are not very easy to use, will work on that later
