### ISSUE TITLE
Assign names and avatars in `gr.Chatbot`

### ISSUE THREAD

**Issue by markwsac** [gradio-app/gradio#3769]
It would be great if we can assign names to characters in Chatbot. For e.g. "Human" before each prompt. "AI" before each response. I have read documentation and couldn't find any way to do this.

**Comment by abidlabs** [comment]
+1, and perhaps small avatars as well?

**Comment by markwsac** [comment]
that would be great

**Comment by 90bird90** [comment]
How to adjust the initial width of the textbox of the chatbot Although it is of course self-adaptive, the initial size is really large

**Comment by CynthiaChuang** [comment]
It seems to only support avatar display without the ability to specify a name？

**Comment by efaraneda** [comment]
@markwsac @abidlabs Not the ideal solution, but works for me! You can try playing around adding some HTML right before every answer like this:

<img width="494" alt="image" src="https://github.com/gradio-app/gradio/assets/71103961/ec287ad2-6e67-4fe5-9617-7140bb46c41e">

And then, you can set a dynamic variable to capture the user's name as an input!

**Comment by chigkim** [comment]
Hi, Is there any progress on assigning custom names for user and bot?

**Comment by abidlabs** [comment]
Not yet, we are working on other things at the moment, but are open to reviewing PRs around this
