### ISSUE TITLE
when i launch a model

### ISSUE THREAD

**Issue by byeolkady** [gradio-app/gradio#377]
when i launch a model I got a this error meassage
------
error response
Error code: 501

Message: Unsupported method ('POST').

Error code explanation: HTTPStatus.NOT_IMPLEMENTED - Server does not support this operation.
------
what can i do?

**Comment by aliabid94** [comment]
Interesting. Can you provide the gradio version and if possible, the source code?

**Comment by abidlabs** [comment]
Thanks @byeolkady for bringing up this issue. @aliabid94 looks like there are a bunch of related issues (see #375 for example)?

**Comment by abidlabs** [comment]
@byeolkady is this using the `gradio` library, or when you try to upload your model on Gradio Hosted?

**Comment by byeolkady** [comment]
@aliabid94 this error appear when I try to upload my model on Gradio Hosted!

**Comment by aliabd** [comment]
Hey @byeolkady, we have deprecated Gradio Hosted and notified customers. Existing interfaces will only remain live until December 31st, 2021 but no new interfaces can be created. All December and November payments were refunded (may take a few days to process) and all subscriptions were canceled. We highly encourage you to use Huggingface Spaces instead, a great and free resource for permanent hosting of your Gradio demos. More info on spaces [here](https://huggingface.co/blog/gradio-spaces) and [here](https://huggingface.co/docs/hub/spaces).

I will close this issue, but if you have any questions feel free to add a comment.
