### ISSUE TITLE
Change the options of gr.Radio through the options of gr.Radio

### ISSUE THREAD

**Issue by gG8Fkpxq** [gradio-app/gradio#3773]
- [✔️] I have searched to see if a similar issue already exists.

First, select an option in radio1, and then call change_options: Change the options for radio1 and radio2. By printing, it can be seen that the options have changed, but in reality, they have not.

```Python
import gradio as gr


with gr.Blocks() as demo:
    options1 = ["Option 1", "Option 2", "Option 3"]
    options2 = ["Option 4", "Option 5", "Option 6"]
    
    radio1 = gr.Radio(options1, label="Select an option")
    radio2 = gr.Radio(options2, label="Select an option")
    def change_options(selected_option):
        print(radio1.choices) # ["Option 1", "Option 2", "Option 3"]
        print(radio2.choices) # ["Option 4", "Option 5", "Option 6"]
        radio2.choices = options1  # ["Option 4", "Option 5", "Option 6"] -> ["Option 1", "Option 2", "Option 3"]
        radio1.choices = options2  # ["Option 1", "Option 2", "Option 3"] -> ["Option 4", "Option 5", "Option 6"]
        print(radio1.choices)  # ["Option 4", "Option 5", "Option 6"]
        print(radio2.choices)  # ["Option 1", "Option 2", "Option 3"]
        

    text = gr.Textbox()

    radio1.change(fn=change_options, inputs=radio1)
    radio2.change(fn=lambda c:c, inputs=radio2, outputs=text)

demo.launch(server_name="0.0.0.0", server_port=7860)
```

**Comment by abidlabs** [comment]
Hi @gG8Fkpxq `radio.choices` will give you the original choices that the radio button was instantiated with. If you need to update the choices and reference these updates values somewhere, I'd recommend saving the updated choices to a session state variable and reading from there. Here's some more documentation: https://gradio.app/state-in-blocks/

**Comment by freddyaboulton** [comment]
Hi @XueChengYang  - the problem is that when `type='index'`, the gradio will index the list used at event creation. Not setting `type='index'` will fix that error. We're thinking of letting the backend store the entire app state but that would be a big change so we might not do that right away.

**Comment by huyppppppp** [comment]
> * [✔️] I have searched to see if a similar issue already exists.
> 
> First, select an option in radio1, and then call change_options: Change the options for radio1 and radio2. By printing, it can be seen that the options have changed, but in reality, they have not.
> 
> ```python
> import gradio as gr
> 
> 
> with gr.Blocks() as demo:
>     options1 = ["Option 1", "Option 2", "Option 3"]
>     options2 = ["Option 4", "Option 5", "Option 6"]
>     
>     radio1 = gr.Radio(options1, label="Select an option")
>     radio2 = gr.Radio(options2, label="Select an option")
>     def change_options(selected_option):
>         print(radio1.choices) # ["Option 1", "Option 2", "Option 3"]
>         print(radio2.choices) # ["Option 4", "Option 5", "Option 6"]
>         radio2.choices = options1  # ["Option 4", "Option 5", "Option 6"] -> ["Option 1", "Option 2", "Option 3"]
>         radio1.choices = options2  # ["Option 1", "Option 2", "Option 3"] -> ["Option 4", "Option 5", "Option 6"]
>         print(radio1.choices)  # ["Option 4", "Option 5", "Option 6"]
>         print(radio2.choices)  # ["Option 1", "Option 2", "Option 3"]
>         
> 
>     text = gr.Textbox()
> 
>     radio1.change(fn=change_options, inputs=radio1)
>     radio2.change(fn=lambda c:c, inputs=radio2, outputs=text)
> 
> demo.launch(server_name="0.0.0.0", server_port=7860)
> ```

I have the same question with you, have you solved it ?

**Comment by Jeru2023** [comment]
Try to return the entire components instead of the choices param, this is my code, a bit redundant tough but it's working.
``` 
def update_target(datasets):
    print(datasets)
    return gr.Radio(datasets, label="Datasets", info="Select datasets to check the result.")

dataset_name_list = DatasetEnum.get_name_list()
datasets = gr.CheckboxGroup(dataset_name_list, label="Datasets", info="Select datasets to evaluate")

target = gr.Radio([], label="Datasets", info="Select datasets to check the result.")

datasets.change(update_target, datasets, target)
```

**Comment by Mon-ius** [comment]
any best practice so far?
