### ISSUE TITLE
404 error on "Try it out" API submission

### ISSUE THREAD

**Issue by morganLapin** [gradio-app/gradio#3774]
### Describe the bug

After clicking "Use via API" at the bottom of Gradio interfaces, when I click "Try it out" below the "Input payload" section, the request goes 404.
It is because the request goes to ${root}**//**run/predict instead of ${root}/run/predict.

It can be fixed here:
https://github.com/gradio-app/gradio/blob/main/js/app/src/api_docs/ApiDocs.svelte#L75
By replacing ${root}/run by ${root}run
since trailing slash at the end of ${root} is added if not already there a few lines before.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Click on "Try it out" below Input payload section of API component.

### Logs

```shell
404 error
```

### System Info

```shell
latest version
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @morganLapin thanks for raising this issue. We're aware of this issue and will be fixing it soon! cc @aliabd
