### ISSUE TITLE
How to enable chatbot in gradio to send multiple responses? for example i have 3 functions, I want chatbot to send the response for 1st function as soon as it passes through that function instead of waiting for all the 3 functions to process and send the output of all the 3 functions all at once.

### ISSUE THREAD

**Issue by faustinaSelvadeepa** [gradio-app/gradio#3775]
- [*] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by abidlabs** [comment]
Hi @faustinaSelvadeepa, for general questions like this (that are not feature requests or bug reports), please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)

**Comment by sumitsahoo** [comment]
I am also looking for similar solution but yet to find any :(
