### ISSUE TITLE
Have all file based components upload their data rather than covert to base64

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#3779]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
We have an `/upload` route that lets components upload their data and store as files in the backend rather than submitting the data as base64 in the post request to `/predict`. Currently only the File and `UploadButton` components use this.

**Describe the solution you'd like**  
For 4.0, we should consider having all file based components upload their data via `upload` so that all components can naturally scale to larger file sizes. It would also make the handling of files for community based components easier.

**Additional context**  
We'll need to have a consistent UI to designate that a file is being uploaded

**Comment by henryruhs** [comment]
May I suggest to introduce `type='filepath'` to `gradio.FIle` and `gradio.Video`? This might solve most of the issues, where `gradio.Video` could render just the first frame of the video to have a preview.

**Comment by freddyaboulton** [comment]
This is done in `v4` branch except for Image which @pngwn is handling!

**Comment by SamridhiVaid** [comment]
Hi. I have the exact same issue. I am using the latest version of Gradio. Everyitme I record a longer audio more than 5 minutes. I have to wait a long time. And then the POST /gradio/upload HTTP/1.1" 200 OK starts. I fi submit the audio before this, I get an error.

**Comment by SamridhiVaid** [comment]
@freddyaboulton I have the exact same issue. I am using the latest version of Gradio (mention version). When I record a longer audio, let's say more than 5 minutes. I have to wait a long time before the processing is complete and the POST `/gradio/upload HTTP/1.1` request shows in the network tab (I assume it is the time it takes to load). I need to submit the audio to do some further processing. But if I do that before this request begins, it fails. 

How can I either speed it up or show the loading state?
