### ISSUE TITLE
Dockerizing

### ISSUE THREAD

**Issue by Shahin-rmz** [gradio-app/gradio#378]
Hello,
thanks for providing comprehensive solution for web.
A question, is there any documentation for deploying Gradio on docker?
Perforable a docker-compose file which data scientists can easily deploy their works.
Thanks

**Comment by abidlabs** [comment]
There currently isn't a tutorial, but you're right, this would be a good addition, so we'll try to put something together. Thanks @Shahin-rmz!

**Comment by Shahin-rmz** [comment]
All good.
I will try my best to make a docker compose and a short documentation for deploying Gradio on docker after 26th of this month, and send you a PR so users can enjoy Gradio even more.
Best

**Comment by abidlabs** [comment]
Thanks @Shahin-rmz! Let us know if you got a chance to put together some documentation. Would be happy to promote and share

**Comment by Shahin-rmz** [comment]
sure, I am working on it with a friend of mine, who is pure devops engineer. I'm gonna make it <one command all done> so the ML users of Gradio just do it with docker compose up -d. and finish.
it may take a bit but worth it ;)

**Comment by mahzy** [comment]
Hey, any luck getting Gradio to work with Docker ?

**Comment by abidlabs** [comment]
Any updated here @Shahin-rmz? Perhaps would make sense to create a discussion around this once you are ready, since it's not really an issue. https://github.com/gradio-app/gradio/discussions
