### ISSUE TITLE
To enable MathJax in Chatbot

### ISSUE THREAD

**Issue by binary-husky** [gradio-app/gradio#3785]
- [check] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Not a problem

**Describe the solution you'd like**  
Allowing MathJax-like equations like `https://svelte.dev/repl/ebd12dbf04574b2bb40003cc8a4299b0?version=3.14.1`

**Additional context**  
None

**Comment by abidlabs** [comment]
Hi @binary-husky, we allow equations in the Chatbot via LaTeX. For example:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Chatbot([("What is the most beautiful equation?", "It is: $e^{i \pi} = 1$")])
    
demo.launch()
```

<img width="613" alt="image" src="https://user-images.githubusercontent.com/1778297/230570337-9f84b2f4-8cb8-41b8-80a3-684f343f595e.png">

I don't think we'll support two different ways of displaying mathematical notation

**Comment by binary-husky** [comment]
Thanks!
Is it LaTeX render related to the default `gr.Chatbot.postprocess` (I think i override it)?  Where can I find related code about it?

**Comment by binary-husky** [comment]
found `gradio/components.py`
