### ISSUE TITLE
Gradio timesout when Deployed on Heroku

### ISSUE THREAD

**Issue by cowanAI** [gradio-app/gradio#3789]
### Describe the bug

As we all know open ai API calls have been deteorating lately due to server overload or who knows, unfortunately Heroku has a 30 second router limit that will crash the gradio app, my app is pretty much not commercial anymore due to this crashing, is it possible to send a whitespace like this https://spin.atomicobject.com/2018/05/15/extending-heroku-timeout-node/ on gradio or simply run a background task in redis which is the only option heroku supports i believe? What would be the most practical workaround for this?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

the problem is the long waiting time for the api call.

### Logs

```shell
H12 Error in heroku
```

### System Info

```shell
latest gradio version, Heroku
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @cowanAI I believe it should be possible to do this via a iterative outputs. You can basically `yield` stuff from the client until you have a final result. Check out https://gradio.app/key-features/#iterative-outputs for more info

By the way, for general questions like this (that are not feature requests or bug reports), please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
