### ISSUE TITLE
UploadButton returns the wrong path

### ISSUE THREAD

**Issue by AscendantAI-Robbie** [gradio-app/gradio#3790]
### Describe the bug

The wrong path is returned with and without preprocess enabled. With preprocess enabled, the path defaults to some system temporary directory. Without preprocess enabled, a dictionary is returned without enough information to derive the location of the image.

1. These options should return the same types
2. The correct absolute path should be returned

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run the UploadButton documentation

```
import gradio as gr

def upload_file(files):
    file_paths = [file.name for file in files]
    return file_paths

with gr.Blocks() as demo:
    file_output = gr.File()
    upload_button = gr.UploadButton("Click to Upload a File", file_types=["image", "video"], file_count="multiple")
    upload_button.upload(upload_file, upload_button, file_output)
demo.launch()
```

### Logs

```shell
N/A
```

### System Info

```shell
Website documentation and

Windows10
Python3.10.6
gradio=3.24.1
```

### Severity

blocking all usage of gradio

**Comment by xujipm** [comment]
Even the official example also has this bug, upload the file and then download it again becomes a 0k file
https://gradio.app/docs/#uploadbutton

**Comment by abidlabs** [comment]
Hi @xujipm @AscendantAI-Robbie we have a fix of this in the works in #3782

**Comment by xujipm** [comment]
> 

If I need to use this upload function urgently now, how should I operate it?

**Comment by xujipm** [comment]
> Hi @xujipm @AscendantAI-Robbie we have a fix of this in the works in #3782

If I need to use this upload function urgently now, how should I operate it?

**Comment by freddyaboulton** [comment]
I belive #3782 fixes the issue @xujipm  - at least in the repro you shared.

Install this version of gradio (built from the PR) and see if it works for you! 

https://gradio-builds.s3.amazonaws.com/1e6a98be6765b957b4972a14be7bffb212ac1b04/gradio-3.24.1-py3-none-any.whl
 

<br class="Apple-interchange-newline">

**Comment by AscendantAI-Robbie** [comment]
This has not exactly been fixed in gradio3.25.0. The file gets uploaded to C:\Users\user\AppData\Local\Temp\randomfolder along with a temp file on each click.

There are several problems with this:
1. If the user clears there temporary folder, this data is no longer accessible
2. Applications should have control over their data. This means that most applications will end up copying the image into their own data management system. This results in duplicate images and a storage leak that relies on the application user periodically deleting their temporary data.

**Comment by abidlabs** [comment]
Hi @AscendantAI-Robbie, I believe issue #3597 is referring to the points you've raised. We'll tackle that soon

**Comment by xujipm** [comment]
I have update to gradio3.25.0  but also got a wrong ptah

Had the same problem on this version
https://gradio-builds.s3.amazonaws.com/1e6a98be6765b957b4972a14be7bffb212ac1b04/gradio-3.24.1-py3-none-any.whl


```
import gradio as gr
import os

def uploadf(file):
    print(file.name)
    fdir = 'uploads'
    if not os.path.exists(fdir):
        os.makedirs(fdir)
    with open(os.path.join(fdir, file.name), 'wb') as f:
        with open(file.name, 'rb') as file:
            f.write(file.read())
    return file.name


with gr.Blocks() as demo:
    fbtn = gr.File()
    result = gr.Text("Result")

    fbtn.upload(uploadf,fbtn,result)

demo.launch()
    
```
![image](https://user-images.githubusercontent.com/3202911/231635868-f97c418e-4b93-419b-a13a-60c486879197.png)

**Comment by abidlabs** [comment]
Hi @xujipm sorry can you explain what the issue you are facing is?

**Comment by xujipm** [comment]
> Hi @xujipm sorry can you explain what the issue you are facing is?

I upload a file on the web page, the path of the image returned by the upload network request is correct, and the file can be found in that path, but in the python script, the path returned by the upload method cannot find the file, so the code cannot obtain the image I uploaded document

**Comment by abidlabs** [comment]
Ok going to reopen this issue and we'll take another look at it

**Comment by xujipm** [comment]
> Ok going to reopen this issue and we'll take another look at it

I'm very sorry, there is a bug in my code, this issue can be closed

```
with open(os.path.join(fdir, file.name), 'wb')  as f
```
`os.path.join(fdir, file.name)`  return  `file.name`  So the content of the temp folder is overwritten to 0kb

there should be changed to
```
with open(os.path.join(fdir,  Path(file.name).name), 'wb')  as f
```

**Comment by abidlabs** [comment]
Ok good to know!
