### ISSUE TITLE
Gallery grid ignores grid values above 12

### ISSUE THREAD

**Issue by AscendantAI-Robbie** [gradio-app/gradio#3792]
### Describe the bug

the Gallery grid ignores grid values above 12. If it is a matter of minimum image size it should allow for a horizontal scrollbar. Some images are needed to be columned aligned in the case of a compare matrix. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```py
import gradio as gr
from PIL import Image

image = Image.new(mode='RGB', size=(1024, 1024))
with gr.Blocks() as demo:
    gr.Gallery(value=[image] * 24).style(grid=12)
    gr.Gallery(value=[image] * 26).style(grid=13)
demo.launch()
```

### Logs

```shell
N/A
```

### System Info

```shell
Windows10
firefox
python3.6.10
gradio==3.24.1
localhost
```

### Severity

serious, but I can work around it

**Comment by AscendantAI-Robbie** [comment]
It would also be nice if the number of columns could be updated within a callback function by using something like Gallery.update. Unless there is another method that I am unaware of the number of columns as always static.

**Comment by abidlabs** [comment]
Hi @AscendantAI-Robbie in the latest version of `gradio`, `gr.Gallery()` does support updating the `columns` parameter. 

Looking into the other issue of maximum columns now

**Comment by abidlabs** [comment]
I just confirmed that your example now works as expected. I updated your example to use the latest syntax for the `gr.Gallery()` component:

```py
import gradio as gr
from PIL import Image

image = Image.new(mode='RGB', size=(1024, 1024))
with gr.Blocks() as demo:
    gr.Gallery(value=[image] * 26, columns=13)
demo.launch()
```

And ran it, and you can see the 13 columns and horizontal scrollbars as expected. Please upgrade to the latest version of `gradio` and if it does not work for you, let us know and we can reopen this issue.
