### ISSUE TITLE
Gradio does not work without internet, especially for Chatbot.

### ISSUE THREAD

**Issue by Juenjie** [gradio-app/gradio#3796]
I have installed gradio 3.24.1, which is the new version. However, I find that gradio asks me connect to the internet when I use the gr.chatbot class. I do not have the access of internet on my local cluster, does that mean I have to choose a different package instead of gradio? When will the new version without internet connection be released?

**Comment by abidlabs** [comment]
Hi @Juenjie, this is a duplicate of #1450. Closing
