### ISSUE TITLE
i cant get the URI 

### ISSUE THREAD

**Issue by gdeepakdeepuml** [gradio-app/gradio#38]
i just tried running hello (which is in docs) with gradio but i cant see anything in URI 

it just shows Running locally at: http://127.0.0.1:7868/

but if i open the link nothing will be there ..! help me

**Comment by abidlabs** [comment]
Can you tell us more about what operating system you're using, and where you're running this (in other words, is it a regular python script. jupyter notebook, or colab notebook)?

**Comment by abidlabs** [comment]
Also, try navigating to http://localhost:7868/ and see if that shows anything

**Comment by gdeepakdeepuml** [comment]
i am using elementry os(Linux based OS ) and i am using kaggle environment(kaggle notebooks) to run the program . program runs without any error but i cant see the output properly. that gives me as 

Running locally at: http://127.0.0.1:7868/

and it gave me a blank page where it is supposed to open the output in the running environment but it shows me `127.0.0.1 refused to connect.` ...  

and i tried navigating to http://localhost:7868/ it shows me as `This site can’t be reached`
help me ..

**Comment by abidlabs** [comment]
Oh I see, can you try setting `share=True` inside `launch()`?

**Comment by abidlabs** [comment]
This should be fixed now!
