### ISSUE TITLE
Numeric value does not show in Slider (when still and during moving) when theme set to "darkdefault"

### ISSUE THREAD

**Issue by ZakiaSalod** [gradio-app/gradio#380]
![gradio_slider_issue_in_darkdefault_theme](https://user-images.githubusercontent.com/17802823/142416604-4f6467fc-7538-4b22-a511-8f883e43605d.png)

**Comment by abidlabs** [comment]
Thanks so much @ZakiaSalod, we should be able to fix this pretty easily. @aliabid94 or @aliabd can you take this?

**Comment by ZakiaSalod** [comment]
Thanks, @abidlabs. 

I was going to show a demo of a program created with Gradio and was wanting to use the darkdefault theme. However, I changed it currently to be "darkhuggingface". Let me know once this is resolved and deployed to production? If it's on time, then I can change the theme back. 

Thanks a lot. Much appreciated.

**Comment by abidlabs** [comment]
I don't think this is an issue anymore. But our `dark` theme seems to be broken in a different way:

![image](https://user-images.githubusercontent.com/1778297/151447720-222dabb5-8895-4e14-bffa-517ccdaabf0d.png)

**Comment by abidlabs** [comment]
Fixed now, thanks to #652!
