### ISSUE TITLE
Allow users to set upload limits 

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#3801]
Let users set upload limits to prevent too many large files from being uploaded to the server. This is especially relevant as we release the client as programmatically uploaded files could take up a lot of space on the servers. 

This could be a `max_file_size` parameter to `launch()`

**Comment by vagxrth** [comment]
Hey, @abidlabs I would like to contribute to this issue, but I request a brief description beforehand. What I conclude is the parameter will act as a configurable setting which will enable the user to specify the maximum allowable size for the uploaded files.

**Comment by vagxrth** [comment]
Thank you for the explanation, can I work on the issue?

**Comment by PinkDraconian** [comment]
Hi @abidlabs,

You referenced this issue in my report on Huntr. Could you please review the report there, as it is not the same issue as referenced here. Feel free to ask any further questions on the report to clear up the confusion.

**Comment by abidlabs** [comment]
Closing in favor of https://github.com/gradio-app/gradio/issues/7825
