### ISSUE TITLE
Add status callbacks to the python client

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#3802]
Add status callbacks so that users can call a function every time there's a status update. We can add a `status_callbacks` parameter to `.submit()`, similar to the `result_callbacks` parameter

**Comment by Preetraj2002** [comment]
assign me this task i would like to work on it

**Comment by abidlabs** [comment]
Hi @Preetraj2002 we don't assign tasks formally, but you're welcome to open a PR and we can review!

**Comment by freddyaboulton** [comment]
Please target the v4 branch instead of main as the client is already going through a significant refactor :)

**Comment by freddyaboulton** [comment]
This is pretty niche and we haven't heard any user requests for this since launching the client so will close.
