### ISSUE TITLE
Let Clients connect to Spaces with Gradio auth

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#3805]
Right now, the Python Client can't connect to Spaces or other hosted apps with auth enabled. Let's enable that

**Comment by justinzyw** [comment]
looking forward to the release of this function

**Comment by tomsoderlund** [comment]
Following this, also interested

**Comment by freddyaboulton** [comment]
This got done in gradio 4.0 by @aliabid94. Closing!

**Comment by wujohns** [comment]
so...how to use it

**Comment by ggoonnzzaallo** [comment]
Hey @aliabid94 , would you mind sharing your implementation?

**Comment by PawKanarek** [comment]
@ggoonnzzaallo do you know how to implement client with authentication? CC @aliabid94
