### ISSUE TITLE
Can we create menu or navbar in gradio app.

### ISSUE THREAD

**Issue by prasadkumar0590** [gradio-app/gradio#3806]
### Describe the bug

Can we create menu or navbar in gradio app.  We require multiple pages in single app. Is this feature available in gradio.

Your help will be appreciated

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

no

### Logs

```shell
no logs
```

### System Info

```shell
latest version of gradio
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @prasadkumar0590 we support tabs, which can you check out here: https://gradio.app/docs/#tab

We also have an open issue to support multiple pages here: #2654. If tabs don't suffice for your case, please chime in on that issue with an explanation of what feature you are looking for.

**Comment by 1lint** [comment]
@prasadkumar0590 One option is to mount multiple gradio apps onto a single FastAPI object, treating each mounted gradio app/route as a page within the entire FastAPI app. Here's a barebone example creating 2 gradio app pages, it can be easily extended to as many pages as you need:

```
from fastapi import FastAPI
from fastapi.responses import HTMLResponse
import gradio as gr

app = FastAPI()

HELLO_ROUTE = "/hello"
GOODBYE_ROUTE = "/goodbye"
iframe_dimensions = "height=300px width=1000px"

index_html = f'''
<h1>Put header here</h1>

<h3>
You can mount multiple gradio apps on a single FastAPI object for a multi-page app.
However if you mount a gradio app downstream of another gradio app, the downstream
apps will be stuck loading. 
</h3>

<h3>
So in particular if you mount a gradio app at the index route "/", then all your 
other mounted gradio apps will be stuck loading. But don't worry, you can still embed
your downstream gradio apps into the index route using iframes like I do here. In fact,
you probably want to do this anyway since its your index page, which you want to detail 
more fully with a jinja template. 
For a full example, you can see my <a href=https://yfu.one/>generative avatar webapp</a>
</h3>

<div>
<iframe src={HELLO_ROUTE} {iframe_dimensions}></iframe>
</div>

<div>
<iframe src={GOODBYE_ROUTE} {iframe_dimensions}></iframe>
</div>

'''

@app.get("/", response_class=HTMLResponse)
def index():
    return index_html


hello_app = gr.Interface(lambda x: "Hello, " + x + "!", "textbox", "textbox")
goodbye_app = gr.Interface(lambda x: "Goodbye, " + x + "!", "textbox", "textbox")


app = gr.mount_gradio_app(app, hello_app, path=HELLO_ROUTE)
app = gr.mount_gradio_app(app, goodbye_app, path=GOODBYE_ROUTE)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app)
```

Another advantage of this framework is that you can also embed multiple, distinct gradio apps onto a single page, like I do for the index route in the example above. This is also what I use for generative avatar webapp https://yfu.one/, where I embed multiple apps into the index route. 
An important caveat is to not mount gradio apps onto a route downstream of another gradio app, or else the downstream apps will be disabled. However you can always embed the downstream apps into an upstream route.
