### ISSUE TITLE
Better customisation of chatbot's message

### ISSUE THREAD

**Issue by wojteke** [gradio-app/gradio#3813]
I would love to have the ability to override the messages used in the chatbot.

In my current use case, I would like to add a button next to the model response so that I can execute the generated code.

I admit that I'm new to this library and maybe my request is already possible. If that's the case, can you please tell me how to achieve this? I couldn't find anything about it in other issues or documentation.

**Comment by abidlabs** [comment]
Hi @wojteke it's not strictly possible to add a button next to the model response. However, you could have a button underneath the chatbot that is designed to execute code from the Chatbot response. You could even add the ability to "select" a message. Here's an example:

```py
import gradio as gr

value = [("Write some code", """
```python
print("hello")
```
"""), (
    "More code","""
```python
for i in range(10):
    print("hello")
```
"""    
)]

def save_selected_message(msg: gr.SelectData):
    return msg.value, gr.Button.update(interactive=True)

def mock_run_code(code):
    return f"pretending to run code...: {code}", gr.Button.update(interactive=False)

with gr.Blocks() as demo:
    message_selected = gr.State()
    c = gr.Chatbot(value=value)
    b = gr.Button(interactive=False)
    t = gr.Textbox()
    c.select(save_selected_message, None, [message_selected, b])
    b.click(mock_run_code, message_selected, [t, b])
   
demo.launch()
```

Which produces this:

![Recording 2023-04-11 at 01 16 13](https://user-images.githubusercontent.com/1778297/231099183-b3d7496c-3dc1-47dc-b022-5d491493b665.gif)

As an aside, you may be interested in following #3816

**Comment by wojteke** [comment]
Well, I haven't thought about that 😄
Thanks for the quick response!
