### ISSUE TITLE
Can't submit textbox on Firefox Nightly (Android)

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3814]
### Describe the bug

As the title says, pressing the enter button on Android doesn't submit a textbox, but indents the text instead.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Press return on Android in a textbox 

### Logs

```shell
N/A
```

### System Info

```shell
3.23.0, Android, Firefox Nightly
```

### Severity

annoying

**Comment by abidlabs** [comment]
Can you link to a demo that you're trying out @space-nuko for ease of reproduction?

**Comment by space-nuko** [comment]
Don't have a computer at the moment but it's a `gr.Textbox` with a `submit` handler

**Comment by abidlabs** [comment]
Hi @space-nuko I tested the latest version of `gradio` on a Samsung Galaxy S10 running Firefox, and I can't reproduce the issue:

Code:

```py
import gradio as gr

with gr.Blocks() as demo:
    t1 = gr.Textbox()
    t2 = gr.Textbox()
    
    t1.submit(lambda x:x, t1, t2)
    
demo.launch(share=True)
```

<img width="850" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/794338b0-4420-49e9-a63c-c3978ba8ac56">

**Comment by freddyaboulton** [comment]
What service is that @abidlabs ? 👀

**Comment by abidlabs** [comment]
Browser Stack (https://www.browserstack.com/guide/mobile-web-testing) -- great UI, sadly a limited free trial

**Comment by abidlabs** [comment]
Will close for now until we have a repro
