### ISSUE TITLE
Back button doesn't close drop-down on Android 

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3815]
### Describe the bug

As the title says, I feel like it should because you can press escape to exit the drop-down on a desktop 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Open a drop-down
2. Press back

### Logs

```shell
N/A
```

### System Info

```shell
3.23.0, Android, Firefox Nightly
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created. Could you let us know if this is still an issue in the latest version of Gradio (pip install --upgrade gradio)? Thanks!

**Comment by abidlabs** [comment]
Will go ahead and close this for now. Can reopen if needed
