### ISSUE TITLE
Imposibility to update Gradio examples

### ISSUE THREAD

**Issue by stefanoscotta** [gradio-app/gradio#3817]
- [ X] I have searched to see if a similar issue already exists.

Hi everybody, I searched but i did not find anything of this kind. I am trying to develop a demo in which it would be nice if according tot the selection of a date from a dropdown the interface update the possible example to use in the next steps as input. 

I wrote the code as done when i update other kind of block but the following error appears. "AttributeError: 'Examples' object has no attribute '_id' ".

I think it would be nice to make possible to update also the examples. Anyone has already a solution?

**Comment by abidlabs** [comment]
Hi @stefanoscotta this limitation is actually part of a larger issue that we'll tackle here: #1566 (feel free to chime in here with your use case)

As a temporary workaround, you may try out the suggestion in this discussion: https://github.com/gradio-app/gradio/discussions/3169

**Comment by jingedawang** [comment]
Encountered the same error when trying to set the value of Example component when blocks are loaded.
