### ISSUE TITLE
Can't upload to different file type like "dicom" to ai engine via gradio

### ISSUE THREAD

**Issue by omer1academic** [gradio-app/gradio#3818]
I just started to use gradio because of i need to create web demo. My engine works with medical image files(dicom or  nifti). I need to upload the file with gradio web. After that engine will give result segmented image. 
Best regards.

**Comment by abidlabs** [comment]
Hi @omer1academic please provide a full code example of what you are trying to and what the issue is. This issue does not have sufficient details for us understand what the bug or feature request is.
