### ISSUE TITLE
microphone input is not working

### ISSUE THREAD

**Issue by xinkez** [gradio-app/gradio#3819]
### Describe the bug

I setup the gradio app with public address. When I use safari to open the url, it doesn't prompt me for microphone access. However, when I setup the gradio app with local address, it works properly. What's the problem? Thank you in advance.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I setup the gradio app with public address. 
I use safari to open the url, it doesn't prompt me for microphone access. 

### Logs

```shell
None
```

### System Info

```shell
Ubuntu 20.04
gradio 3.25.0
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
I cannot reproduce @xinkez . Could it be a setting in your local safari browser?

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/41651716/231252420-0bdbda8d-6965-4070-893b-e2e6f3fc2faf.png">

**Comment by xinkez** [comment]
@freddyaboulton 
When I set "server.launch(share=True)", I use this url (https://1a9b77cb89ac33f546.gradio.live), and it is ok. 
However, when I set "server.launch(server_name="0.0.0.0")", I use my own public url (for example, http://101.40.163.105:7860), it doesn't prompt me for microphone access.

**Comment by abidlabs** [comment]
Hi @xinkez this is not a Gradio issue but it's actually due to the fact that modern browsers block microphone access in http environments. We have an existing issue to provide clearer error messages when this happens: https://github.com/gradio-app/gradio/issues/2551

cc @aliabid94 maybe you can take a look as part of the audio work
