### ISSUE TITLE
Method url_ok check is not reaching host if server_name is 0.0.0.0

### ISSUE THREAD

**Issue by cansik** [gradio-app/gradio#382]
In the documentation it is mentioned that it is possible to set the `server_name` to `0.0.0.0` to host it on any network interface (LAN):
> server_name (str) - to make app accessible on local network set to "0.0.0.0".

This is problematic, because the server URL for the local flask server is generated with the `server_name`. Which means `path_to_local_server` is set to `http://0.0.0.0:7860/`. Later, the `url_ok()` method checks if this URL is reachable and if not, creates a public proxy for the server. And because [http://0.0.0.0:7860/](http://0.0.0.0:7860/) is not a reachable IP address (at least under Windows), this won't work.

Maybe it makes sense to check if the local Flask server is bound to `0.0.0.0` and replace it with `localhost` (which still is not a very nice solution, but for now fixes it for me):

```python
path_to_local_server = "http://{}:{}/".format(server_name, port)

if server_name == "0.0.0.0":
    path_to_local_server = path_to_local_server.replace(server_name, "localhost")
```

**Comment by abidlabs** [comment]
Interesting... let me look into this. Thanks for the suggestion @cansik

**Comment by abidlabs** [comment]
Looking into this issue (sorry for the delay @cansik). I have a question -- why are you setting the server name to "0.0.0.0" exactly? Doesn't your code work if you just leave it as "localhost"?

**Comment by cansik** [comment]
As far as I know, the server name in gradio defines the local network-interface the server is listening on. So if it is localhost, only `127.0.0.1` is a valid IP to reach the sever. To bind to all network-interfaces, it is common (as well in flask) to bind to `0.0.0.0`. This allows me to reach the server over all ip addresses (`127.0.0.1`, `192.168.1.30`, whater-public-ip, ..) that are assigned to my network interfaces. This is not a valid ip address, but it is a valid host address ([wiki/0.0.0.0](https://en.wikipedia.org/wiki/0.0.0.0)).

So, we are allowed to bind to a server to `0.0.0.0`, but on some host systems (Windows), this "ip" can not be reached because it is not valid, leading to the explained problem in the issue.

**Comment by abidlabs** [comment]
That makes sense! So we should handle `0.0.0.0` as a special case. Let me patch this

**Comment by cansik** [comment]
I could create a PR if you want, maybe it makes sense to handle other special addresses as well. This one is only for IPv4 interfaces.

**Comment by abidlabs** [comment]
Sure, that would be great! I've started working on some related issues in the `abidlabs/url` branch, including some refactoring that may impact this. If you would kindly check out that branch and then create your own new branch from that, then it would make it easy to merge everything back in.

**Comment by abidlabs** [comment]
Thanks @cansik for the fix!
