### ISSUE TITLE
Cannot host public repository on Gradio 

### ISSUE THREAD

**Issue by baishalidutta** [gradio-app/gradio#383]
I am trying to host my GitHub repository on Gradio but it is encountering `405 Not Allowed` after clicking on the `Launch` button.

![1](https://user-images.githubusercontent.com/76659596/142757381-18f738d4-e606-4f34-b378-319429dc4d34.png)
![2](https://user-images.githubusercontent.com/76659596/142757384-d8663f38-ee4d-4eed-af48-84fee62c0f51.png)

**Comment by abidlabs** [comment]
We are running into some issues with Gradio Hosted. In the meantime, I suggest looking into Hugging Face Spaces as the preferred way to host your Gradio applications: https://huggingface.co/spaces

**Comment by aliabd** [comment]
Hey @baishalidutta, we have deprecated Gradio Hosted and notified customers. Existing interfaces will only remain live until December 31st, 2021 but no new interfaces can be created. All December payments were refunded (may take a few days to process) and all subscriptions were canceled. We highly encourage you to use Huggingface Spaces instead, a great and free resource for permanent hosting of your Gradio demos. More info on spaces [here](https://huggingface.co/blog/gradio-spaces) and [here](https://huggingface.co/docs/hub/spaces). 

I will close this issue, but if you have any questions feel free to add a comment.

**Comment by aliabd** [comment]
Note: we have also refunded payments made in November.
