### ISSUE TITLE
[DOCS] gr and gradio is used interchangebly

### ISSUE THREAD

**Issue by duerrsimon** [gradio-app/gradio#3832]
### Describe the bug

There are plenty of examples on https://gradio.app/docs/#block-layouts where `gr` and `gradio` are mixed. 

E.g

```
with gradio.Accordion("See Details"):
    gr.Markdown("lorem ipsum")
```

I think the examples should always use `gr` and the command documentation the full name `gradio` for consistency and being friendly to newbies.
![image](https://user-images.githubusercontent.com/16979577/231428048-9c14ee53-9ee8-4d9b-abe0-6a938dd4ed09.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://gradio.app/docs/#block-layouts

### Logs

```shell
NA
```

### System Info

```shell
NA
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks @duerrsimon -- would you be open to making a PR for this?

**Comment by duerrsimon** [comment]
Happy to do so. In the interest of consistency I will change all the examples. I tried looking in PEP but there is no good guide on  conventions for abbreviated imports. But I think if the package has a commonly used alias the full name is never used (e.g with numpy as np).  Is there any example where you want to stay with dual use of `gradio` and `gr`?

E.g this one 
![image](https://user-images.githubusercontent.com/16979577/232513651-a0795c86-391f-4447-8b63-5a02b7daf6f1.png)
