### ISSUE TITLE
Minor bugs in the audio timeslice

### ISSUE THREAD

**Issue by tomchang25** [gradio-app/gradio#3838]
### Describe the bug

1. Audio name changes to "audio" after editing timeslice
2. Audio timeslice does not reset when clearing and re-uploading audio

As these are just minor bugs and not very urgent. I will fix them over the weekend and create a PR.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Default
![Default](https://user-images.githubusercontent.com/31534748/231763606-97af1a65-6319-4344-8f2f-db0b15a264f8.png)
2. After editing timeslice (name changes to "audio")
![After editing timeslice](https://user-images.githubusercontent.com/31534748/231763861-4547f3b2-9859-4b32-9c16-0445b0fda48f.png)
3. Clear and re-upload audio (name remains "1min" and slice not reset)
![2023-04-13 204205](https://user-images.githubusercontent.com/31534748/231764128-43416d3c-ac46-4bf2-9255-0deb2bcd5e96.png)

### Logs

```shell
Not exist
```

### System Info

```shell
gradio v3.25.1b2
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks @tomchang25!

**Comment by abidlabs** [comment]
Hi @tomchang25 would you still be interested in solving these bugs?

**Comment by abidlabs** [comment]
Both should be fixed now, I believe, thanks to @hannahblair's refactor.
