### ISSUE TITLE
Issue with indentation in code field with streaming

### ISSUE THREAD

**Issue by lvwerra** [gradio-app/gradio#3839]
### Describe the bug

When adding text to a code field with a generator the indentation seems to be only invoked/displayed when the current block is de-indented. This is a bit weird since the whole block jumps only after the end of the current indentation block and if the block is not finished at all is displayed wrong.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Created a small demo of the bug: https://huggingface.co/spaces/lvwerra/code-indent-bug

### Screenshot

![Screenshot 2023-04-13 at 14 58 45](https://user-images.githubusercontent.com/8264887/231766046-b1953af9-2627-4b74-9204-c71193ab35ae.png)
![Screenshot 2023-04-13 at 14 58 26](https://user-images.githubusercontent.com/8264887/231766058-b224e455-e4a5-40b2-8f4f-9d0fb699c17a.png)

### Logs

```shell
7zfmz 2023-04-13T12:53:21.301Z Running on local URL:  http://0.0.0.0:7860
7zfmz 2023-04-13T12:53:21.301Z 
7zfmz 2023-04-13T12:53:21.301Z To create a public link, set `share=True` in `launch()`.
```
```


### System Info

```shell
Using `sdk_version: 3.24.1` on Spaces and see it on both Chrome and Safari
```

### Severity

annoying

**Comment by loubnabnl** [comment]
any updates on this issue? We're having it frequently in a code demo when asking for function completions and wanting to stop at the `eos_token` (so there's no completion to trigger indentation)
