### ISSUE TITLE
No way to modify default values in the API

### ISSUE THREAD

**Issue by invoxiaglo** [gradio-app/gradio#384]
Hello,

I went through the doc and did not find a way to modify the default values in the API. The API part does not even appear in the doc.
The default value is "Hello World" for any string input. I would like to be able to set the value.

![Screenshot 2021-11-22 at 10 58 26](https://user-images.githubusercontent.com/80348491/142841223-0799143d-c638-4774-a67b-e0a75bf4094f.png)

Thanks !

**Comment by abidlabs** [comment]
We don't currently support this. The purpose of the API is just to show an example so we just populate a string input with a fixed string. Can you explain why changing this would be helpful for your use case and we can look into supporting this?

**Comment by invoxiaglo** [comment]
In the API, there is also a Post button that makes it possible to try a request. For my use case, the input cannot be any string, it must be for instance a correct identifier. A user trying the Post button will receive an Error because the default values are not a correct input. Furthermore, it would be more comprehensible for a user to have values that makes him understand what are the different inputs instead of "Hello World".

**Comment by abidlabs** [comment]
That makes sense. Would it solve your issue if we implemented the following:
* If `examples` are provided, the API should pull from them
* Otherwise, default values like `hello world` are used

In other words, in your interface, are you providing examples?

**Comment by invoxiaglo** [comment]
Yes it would be great. I think it is the expected behaviour that for instance the first example is used as the default values in the API.

**Comment by aliabd** [comment]
@invoxiaglo we fixed this in https://github.com/gradio-app/gradio/pull/355 thanks for the suggestion! 

The live demo will now pull from examples first before trying the gradio defined inputs.
