### ISSUE TITLE
Poor SEO on Gradio docs

### ISSUE THREAD

**Issue by jrhe** [gradio-app/gradio#3840]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
When trying to look up Gradio methods/classes in a Google search, the docs rarely show. If the docs do show as a result it is to the page itself rather than the relevant section. This makes it annoying to look up general usage of the library.

**Describe the solution you'd like**  
I'm not an SEO expert so don't really know what's causing this issue. The guides show up fine but not the main documentation pages. @aliabd did some SEO improvements on pages of the guides, so perhaps they have an idea what the issue is.

**Additional context**  
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/4038905/231778136-55f5def0-cfbc-42ba-8a54-29d02adf1d6e.png">

**Comment by abidlabs** [comment]
This is now fixed, after we broke up components into their own pages: 

<img width="1266" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/0909ab8e-07cb-403f-8a3a-5de8be92614c">
