### ISSUE TITLE
[feat req] Make progress bar compatible with generators

### ISSUE THREAD

**Issue by sanchit-gandhi** [gradio-app/gradio#3841]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

Gradio's progress bar feature gives super nice tqdm-style progress bars when iterating over python objects (e.g. https://gradio.app/key-features/#progress-bars). However, these bars don't display when the object is a _generator_, e.g. modifying the example given on the docs to use a generator object:

```python
import gradio as gr
import time
from tqdm import tqdm

def simple_generator(word):
    for letter in word:
        yield letter

def slowly_reverse(word, progress=gr.Progress()):
    progress(0, desc="Starting")
    time.sleep(1)
    progress(0.05)
    new_string = ""
    word_generator = simple_generator(word)
    for letter in progress.tqdm(word_generator, total=len(word), desc="Reversing"):
        time.sleep(0.25)
        new_string = letter + new_string
    return new_string

demo = gr.Interface(slowly_reverse, gr.Text(), gr.Text())

if __name__ == "__main__":
    demo.queue(concurrency_count=10).launch()
```

Now doesn't display the progress bar, even if the `total=...` argument is provided to the generator (which usually allows tqdm to show a progress bar for a generator).

**Describe the solution you'd like**  
Would be super nice if generators were compatible with Gradio's progress bar in the same way iterating over other Python objects is.

**Additional context**  
Current workaround is a hack where we give a dummy list to Gradio's progress bar:

```python
import gradio as gr
import time
from tqdm import tqdm

def simple_generator(word):
    for letter in word:
        yield letter

def slowly_reverse(word, progress=gr.Progress(track_tqdm=True)):
    progress(0, desc="Starting")
    time.sleep(1)
    progress(0.05)
    new_string = ""
    word_generator = simple_generator(word)
    num_batches = len(word)
    for letter, _ in zip(word_generator, tqdm(range(num_batches), desc="Reversing")):  # hack: iterate over our generator and progress bar at the same time, but only use our generator batches
        time.sleep(0.25)
        new_string = letter + new_string
    return new_string

demo = gr.Interface(slowly_reverse, gr.Text(), gr.Text())

if __name__ == "__main__":
    demo.queue(concurrency_count=10).launch()
```

**Comment by abidlabs** [comment]
Looks like a bug to me, thanks for reporting @sanchit-gandhi!

**Comment by SinclairHudson** [comment]
@sanchit-gandhi thanks for that workaround! I'm also hoping this bug gets addressed soon.
