### ISSUE TITLE
Should Chatbot component enforce strict turn-taking?

### ISSUE THREAD

**Issue by anentropic** [gradio-app/gradio#3847]
### Describe the bug

If the purpose of the chatbot is to generate a reply to each user input then it is a problem if the component allows the user to submit multiple messages before any reply is generated, and it only replies to the first message

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just type and enter quickly in the demo at https://gradio.app/docs/#chatbot

### Screenshot

![Screenshot 2023-04-13 at 22 21 58](https://user-images.githubusercontent.com/147840/231885775-a3801a17-3ca1-43c8-9851-aa59eaf9f651.png)

### Logs

```shell
n/a
```

### System Info

```shell
whatever the docs are using
```

### Severity

annoying

**Comment by anentropic** [comment]
apologies, I am completely new to Gradio and just finding my way (it's great though!)

Is there a way to disable the submit action from being re-triggered until after the `then` clause has executed?

by toggling the `interactive` property on the button?

**Comment by abidlabs** [comment]
Hi @anentropic, welcome to Gradio! Yes, as @pngwn mentioned the `Chatbot` component is agnostic to the function used to populate it. It's meant to handle a variety of use cases, including those in which a user might want to submit multiple messages in a row.

But yes, it's definitely possible to achieve what you are asking. What you'd do is to return `gr.update(interactive=False)` from your first function, corresponding to the button output, and then return `gr.update(interactive=True)` from the second function that executes after the `.then()`. 

I think we should document this in the Chatbot Guide, so adding the `docs` label to this issue. https://gradio.app/creating-a-chatbot/

**Comment by anentropic** [comment]
I am lost in all the implicitness... how do I return `gr.update(interactive=False)` while also returning the `""` to clear the input box and `history + [[user_message, None]]` to append a new message to the chat history?

**Comment by anentropic** [comment]
`.then()` isn't really documented anywhere?

**Comment by anentropic** [comment]
By guessing random things I got it working with this code:

```python
    def user(user_message, history):
        return gr.update(value="", interactive=False), history + [(user_message, None)]

    def bot(_, history):
        bot_message = random.choice(["Yes", "No"])
        history[-1][1] = bot_message
        time.sleep(1)
        return gr.update(interactive=True), history

    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        bot, [msg, chatbot], [msg, chatbot]
    )
```

**Comment by abidlabs** [comment]
Sorry about the vague response @anentropic. Agree, will document this better next week

**Comment by abidlabs** [comment]
Improved the docs for Chatbot. Please see the updated guide @anentropic: https://gradio.app/creating-a-chatbot/
