### ISSUE TITLE
Hello word demo raises exception

### ISSUE THREAD

**Issue by jean-david-ruvini** [gradio-app/gradio#3848]
### Describe the bug

Running this code in a Jupyter notebook:

import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")

demo.launch()

Raises the following exception:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 6
      3 def greet(name):
      4     return "Hello " + name + "!"
----> 6 demo = gr.Interface(fn=greet, inputs="text", outputs="text")
      8 demo.launch()   

File ~/Library/Python/3.9/lib/python/site-packages/gradio/interface.py:457, in Interface.__init__(self, fn, inputs, outputs, examples, cache_examples, examples_per_page, live, interpretation, num_shap, title, description, article, thumbnail, theme, css, allow_flagging, flagging_options, flagging_dir, flagging_callback, analytics_enabled, batch, max_batch_size, _api_mode, **kwargs)
    455     self.attach_flagging_events(flag_btns, clear_btn)
    456     self.render_examples()
--> 457     self.render_article()
    459 self.config = self.get_config_file()

File ~/Library/Python/3.9/lib/python/site-packages/gradio/blocks.py:1285, in Blocks.__exit__(self, *args)
   1283 else:
   1284     self.parent.children.extend(self.children)
-> 1285 self.config = self.get_config_file()
   1286 self.app = routes.App.create_app(self)
   1287 self.progress_tracking = any(block_fn.tracks_progress for block_fn in self.fns)

File ~/Library/Python/3.9/lib/python/site-packages/gradio/blocks.py:1261, in Blocks.get_config_file(self)
   1258         assert isinstance(block, serializing.Serializable)
   1259         block_config["serializer"] = serializer
   1260         block_config["info"] = {
-> 1261             "input": list(block.input_api_info()),  # type: ignore
   1262             "output": list(block.output_api_info()),  # type: ignore
   1263         }
   1264     config["components"].append(block_config)
   1265 config["dependencies"] = self.dependencies

AttributeError: 'Textbox' object has no attribute 'input_api_info'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")

demo.launch()

### Logs

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 6
      3 def greet(name):
      4     return "Hello " + name + "!"
----> 6 demo = gr.Interface(fn=greet, inputs="text", outputs="text")
      8 demo.launch()   

File ~/Library/Python/3.9/lib/python/site-packages/gradio/interface.py:457, in Interface.__init__(self, fn, inputs, outputs, examples, cache_examples, examples_per_page, live, interpretation, num_shap, title, description, article, thumbnail, theme, css, allow_flagging, flagging_options, flagging_dir, flagging_callback, analytics_enabled, batch, max_batch_size, _api_mode, **kwargs)
    455     self.attach_flagging_events(flag_btns, clear_btn)
    456     self.render_examples()
--> 457     self.render_article()
    459 self.config = self.get_config_file()

File ~/Library/Python/3.9/lib/python/site-packages/gradio/blocks.py:1285, in Blocks.__exit__(self, *args)
   1283 else:
   1284     self.parent.children.extend(self.children)
-> 1285 self.config = self.get_config_file()
   1286 self.app = routes.App.create_app(self)
   1287 self.progress_tracking = any(block_fn.tracks_progress for block_fn in self.fns)

File ~/Library/Python/3.9/lib/python/site-packages/gradio/blocks.py:1261, in Blocks.get_config_file(self)
   1258         assert isinstance(block, serializing.Serializable)
   1259         block_config["serializer"] = serializer
   1260         block_config["info"] = {
-> 1261             "input": list(block.input_api_info()),  # type: ignore
   1262             "output": list(block.output_api_info()),  # type: ignore
   1263         }
   1264     config["components"].append(block_config)
   1265 config["dependencies"] = self.dependencies

AttributeError: 'Textbox' object has no attribute 'input_api_info'
```

### System Info

```shell
Python 3.9.6
MacOs 13.2 (22D49)
Gradio 3.25.0

jupyter --version             
Selected Jupyter core packages...
IPython          : 8.12.0
ipykernel        : 6.22.0
ipywidgets       : 8.0.6
jupyter_client   : 8.1.0
jupyter_core     : 5.3.0
jupyter_server   : 2.5.0
jupyterlab       : 3.6.3
nbclient         : 0.7.3
nbconvert        : 7.3.1
nbformat         : 5.8.0
notebook         : 6.5.4
qtconsole        : not installed
traitlets        : 5.9.0
```

### Severity

blocking all usage of gradio

**Comment by freddyaboulton** [comment]
Hi @jean-david-ruvini - can you install `gradio_client==0.1.0` please? This looks like it's caused by a bug in `gradio_client=0.1.1` (we have removed that version from pypi).

**Comment by jean-david-ruvini** [comment]
Thanks @freddyaboulton. Uninstalling gradio_client==0.1.1 and installing gradio_client=0.1.1 worked!

**Comment by freddyaboulton** [comment]
I'm glad!! Let us know if you run into any other trouble - happy to help.
