### ISSUE TITLE
feedback for Chatbot response 

### ISSUE THREAD

**Issue by djaym7** [gradio-app/gradio#3849]
Please add like/dislike (or user's choice) to chatbot's responses, I searched but couldn’t find any way to do this on gradio. It'd be very useful. 

It could be sent back to the bot function like 

def bot (history,feeback) : 
OR
in the history tuple as :
[(user_text, bot_text, feedback), (user_text,bot_text,feedback) ... ]

feedback could be int or float ..

**Comment by hujghc** [comment]
I have the same problem.  I can't find out how to use it . is it available now? @abidlabs
