### ISSUE TITLE
Merge Video and Audio to the new component

### ISSUE THREAD

**Issue by tomchang25** [gradio-app/gradio#3855]
- [x] I have searched to see if a similar issue already exists.

I've noticed that the Video and Audio components share many common functions, but their updates are not synchronized, which has resulted in some features missing in both components. 
For instance:

Video is missing:

- Time slice

Audio is missing:

- Upload, playable, stop events
- Style support
- Value and old value check
- Subtitle (although it's not necessary since I don't think anyone will use it, even for podcasts)

The most important issue is that when we need to add new features or fix bugs, we often have to repeat the same code twice. 
For example, when I fixed the base64 issue, the audio code was basically a copy and paste of the video version.

Solution:

Create a new component, such as Media.
For backward compatibility, we can move the video and audio components to the template of Media.

**Comment by abidlabs** [comment]
We've made some modifications to each of these components, so they've diverged even more. It doesn't make sense for them to be a single component anymore. Note that video now supports time slicing though!
