### ISSUE TITLE
Updating `DataFrame` will invoke an unexpected `select` event

### ISSUE THREAD

**Issue by yiyuezhuo** [gradio-app/gradio#3856]
### Describe the bug

Once DataFrame's `select` is invoked once, updating to the `DataFrame` will invoke an unexpected `select` event.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import pandas as pd
import gradio as gr

df = pd.DataFrame([{"a":1, "b":2}, {"a":2, "b":3}])

with gr.Blocks() as demo:
    gr_df = gr.DataFrame(df)
    
    button = gr.Button("Update DataFrame")
    
    def select(evt:gr.EventData):
        print("select")
    def click():
        df.iloc[0]["a"] += 1
        return df
        
    gr_df.select(select, [], [])
    button.click(click, [], [gr_df])

demo.launch()
```

- Select a cell in the DataFrame and a `select` is shown.
- Click the button, but `select` is also shown unexpectedly.

PS: If DataFrame has never been selected, the updating will not invoke the `select` event, as expectedly. If the updating just return the identical value, the `select` is not invoked as well.

### Screenshot

https://user-images.githubusercontent.com/12798270/232085043-0ff4fe69-0c94-4887-b51d-ac42ddf5e3db.mp4

### Logs

```shell
No Error but the behavior is not expected.
```

### System Info

```shell
3.25.1b1
Windows
Edge 112.0.1722.39
```

### Severity

serious, but I can work around it

**Comment by yiyuezhuo** [comment]
Looks like that it's due to variable `selected` is not reset to "unselected state":

```javascript
	$: {
		if (selected !== false) {
			const loc = selected.split("-");
			const row = parseInt(loc[0]);
			const col = parseInt(loc[1]);
			dispatch("select", { index: [row, col], value: data[row][col].value });
		}
	}
```

**Comment by abidlabs** [comment]
Thanks @yiyuezhuo for creating this issue and finding the problem. Would you be able to create a PR to fix this? We're happy to review
