### ISSUE TITLE
Config route on Colab Demos 

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#3867]
### Describe the bug

If you launch a demo without share=True, use via api page says root is is a googleusercontent link (eg https://zqg7t4nonic-496ff2e9c6d22116-7860-colab.googleusercontent.com/) and that link returns an error with the client

```
ValueError: Could not get Gradio config from: https://zqg7t4nonic-496ff2e9c6d22116-7860-colab.googleusercontent.com/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Launch a demo on colab without share=True, then click use via api button and try one of the code snippets. 

### Logs

```shell
ValueError: Could not get Gradio config from: https://zqg7t4nonic-496ff2e9c6d22116-7860-colab.googleusercontent.com/
```

### System Info

```shell
gradio v3.27.0 
gradio_client v0.1.3
```

### Severity

annoying

**Comment by abidlabs** [comment]
Closing as launching Gradio in Colab now requires setting share=True
