### ISSUE TITLE
/info route breaks for entire app if certain components are present (interpretation, annotatedimage)

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#3868]
### Describe the bug

Some of the demos don't have the /info route, which is breaking the use via api page. example:

https://colab.research.google.com/github/gradio-app/gradio/blob/main/demo/sentiment_analysis/run.ipynb

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Click use via api button on this colab's demo: 

https://colab.research.google.com/github/gradio-app/gradio/blob/main/demo/sentiment_analysis/run.ipynb

### Logs

```shell
Failed to load resource: the server responded with a status of 500 ()       /info:1
```

### System Info

```shell
gradio v3.27.0 
gradio-client v0.1.3
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
For the sentiment classification demo, the problem is caused by the interpretation component cc @abidlabs 


![image](https://user-images.githubusercontent.com/41651716/232520725-f2b486d3-8eca-45e9-a199-40d291942c2f.png)

**Comment by abidlabs** [comment]
Ahhh interpretation strikes again. Starting to agree with @aliabid94 that we should nuke it in 4.0

But yeah this should be an easy fix -- can take of it

**Comment by segments-tobias** [comment]
Does the new `AnnotatedImage` component also break the API page?
It's not working for my demo: [https://huggingface.co/spaces/segments/panoptic-segment-anything](https://huggingface.co/spaces/segments/panoptic-segment-anything)

**Comment by abidlabs** [comment]
Thanks @segments-tobias! No need to create a new issue, I'll tackle both issues in the same PR
