### ISSUE TITLE
Add translation to simplified Chinese

### ISSUE THREAD

**Issue by songw** [gradio-app/gradio#3870]
### Describe the bug

<img width="755" alt="image" src="https://user-images.githubusercontent.com/1639828/232230911-598fa9f6-a2d5-4cf7-ac0e-6a1044d5eb9c.png">
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/1639828/232230916-13e404aa-07b6-4e2f-8d1a-c9b797f21323.png">

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="image", outputs="text")
    
if __name__ == "__main__":
    demo.launch()

### Logs

```shell
<img width="755" alt="image" src="https://user-images.githubusercontent.com/1639828/232230911-598fa9f6-a2d5-4cf7-ac0e-6a1044d5eb9c.png">
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/1639828/232230916-13e404aa-07b6-4e2f-8d1a-c9b797f21323.png">
```

### System Info

```shell
gradio version:3.27.0
operation system:macos
browser:chrome
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @songw the reason for this behavior is that we do not have the translation in simplified Chinese here: https://github.com/gradio-app/gradio/tree/main/js/app/src/lang

If you would like to contribute a PR to add the translations for simplified Chinese (I believe the language code is zh-chs), then the translations would show up and we'd appreciate it! You can take a look at some of the other files, like `zh-cn.json` to see what words need to be translated.

**Comment by songw** [comment]
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/1639828/232358575-a71f454d-0f6d-4674-adcf-9603e50e3379.png">
I think the reason is the file name is not correct, the file name should be 
<img width="755" alt="image" src="https://user-images.githubusercontent.com/1639828/232358738-e0bcc162-e7c1-4e47-85e1-daa73677e325.png">
