### ISSUE TITLE
Unreliable change() event listener

### ISSUE THREAD

**Issue by ThereforeGames** [gradio-app/gradio#3876]
### Describe the bug

Hi,

I have noticed that the `change()` event quite often fails to capture the latest input, perhaps because a previous `change()` event is ongoing.

This is particularly likely to occur if you are quick with your actions, for example when a fast typer encounters a textbox field.

EDIT: As a possible workaround, it seems I can more reliably capture the value of a textbox via the `blur()` event. I'm not sure if this is a viable solution for other elements, however.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try the "Hello World!" demo on the following page:

https://gradio.app/blocks-and-event-listeners/#:~:text=Event%20listeners%20define%20the%20data,the%20Button%20greet_btn%20is%20clicked.

### Screenshot

Video evidence:

https://user-images.githubusercontent.com/95403634/232262594-4ca92e3b-1f24-49ad-a92c-990d3f34d47b.mp4

### Logs

```shell
N/A
```

### System Info

```shell
Gradio.app demo (presumably latest version?), Windows 11, Brave browser
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Hi @ThereforeGames, thanks for creating this issue. I believe this is the same issue as #1954. I'll go ahead and close this issue, but we'll take a look at #1954 as part of our 4.0 release.
