### ISSUE TITLE
Is it possible to have an interface/method that can trigger to clear the audio input. 

### ISSUE THREAD

**Issue by Kulbear** [gradio-app/gradio#3877]
The audio component always start as shown
![image](https://user-images.githubusercontent.com/14886380/232273222-4b4d40a5-dc1f-44e5-b454-e01ea1c39eb5.png)

When we finish recording it turned to sth like this
![image](https://user-images.githubusercontent.com/14886380/232273211-20a91b8f-1b3f-4c94-912d-174488fd598e.png)

By looking at the documentation, I did find `clear` function, which is trigger when we remove the audio by clicking the cross (remove) button
![image](https://user-images.githubusercontent.com/14886380/232273295-f73653b1-e5ec-4265-bba6-f37aa7c28595.png)

However, would it be possible to trigger the remove audio action with other interface, like a button shown here

![image](https://user-images.githubusercontent.com/14886380/232273327-350dd202-72fc-4755-bb23-8cdea684fcc2.png)

**Comment by abidlabs** [comment]
Hi @Kulbear yes it is possible. Simply return `None` from a function that is triggered by that button. Here's an example:

```py
with gr.Blocks() as demo:
    audio = gr.Audio(source="microphone", interactive=True)
    btn = gr.Button("Clear")
    
    btn.click(lambda :None, None, audio)

demo.launch()
```

By the way, for general questions like this (that are not feature requests or bug reports), please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
