### ISSUE TITLE
Provide a way to disable a call from `gradio_client`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#3879]
- [x] I have searched to see if a similar issue already exists.

Sometimes, there's a need to disable certain functionalities in the public Space so as not to slow down the demo etc.. Until now, it's been possible to do so by setting `interactive=False` to the button to execute the function in the shared Space. But `Client` can call such functions as well, and it would be nice if Space developers could specify certain functions not to be called from `Client`.

**Comment by hysts** [comment]
> Is this something that would not be taken care of by rate limiting?

No, I don't think it'd be taken care of by rate limiting. The use case I have in mind here is to completely disable the use of certain functions, not to limit the frequency of call.
Here is an example:
![](https://user-images.githubusercontent.com/25161192/232639098-94191da8-ea72-40b1-8671-071606ca4606.png)
https://huggingface.co/spaces/hysts/ControlNet-v1-1/blob/a6606310e0d8d7b007ff4b9975e4ed0e0de01a06/app.py#L105-L120
In the case of this Space, I want to provide a feature to change the base model only when they run the Space in their own local environment, Colab or duplicated Space, not in this public Space.
It's fun to try out other base models than SD 1.5, so I want to make it possible, but changing base model will slow down the demo due to the loading time (and download time if the model was used for the first time). So, I'd like to disallow changing the base model in this public Space using the environment variable, but allow it in other environments.

> I'm wary of letting users who make Spaces disable too many features from their Gradio demo, which would deteriorate the experience for developers who are seeking to use those features via API.

Yes, I agree that there's a concern on that point. But I guess people wouldn't bother to disable functions with no reasons and it would be OK if the default behavior was to allow API calls.

**Comment by abidlabs** [comment]
Makes sense. Okay how we tackle this along with #3780 by doing the following. The `api_name` in the event listeners can take the following values:

* `None` (default): in which case, the API name is assigned the name of the function
* a `str`: in which case, this becomes the API name
* `False`: in which the API is hidden and is not callable from the client

I actually don't think we need to wait until 4.0 to make these changes, if anyone would like to take it on!

**Comment by hysts** [comment]
This has been addressed in https://github.com/gradio-app/gradio/pull/4683
