### ISSUE TITLE
Video input with webcam source not working on iPhone

### ISSUE THREAD

**Issue by nateraw** [gradio-app/gradio#388]
Webcam video inputs work fine on my macbook and android device, but seem to be broken on iPhone. When you go to click record, you see a still frame of yourself, and then it goes back to saying "click here to record" without showing any video.

**Comment by abidlabs** [comment]
@aliabid94 is looking into this. iPhone browser does weird things with video and audio.

**Comment by nateraw** [comment]
This issue is resolved now - thanks folks
