### ISSUE TITLE
Chatbot Docs slow due to demos

### ISSUE THREAD

**Issue by jakob-bjorner** [gradio-app/gradio#3882]
- [x] I have searched to see if a similar issue already exists. 

Problem:
While trying to read the docs for chatbot there are too many demos I believe, which causes the page to load quite slowly. 

Proposed solution:
This could be changed by making the demos linked or having a start demo button which triggers the element to load after being clicked. And prior to this the demo could be visible in a gif which illustrates the concept being described.

**Comment by abidlabs** [comment]
Hi @jakob-bjorner thanks for your feedback! I'll take a look and see if there's anything we can do to speed this up.

**Comment by abidlabs** [comment]
Hi @jakob-bjorner I took a look and there's not much we can do. We already lazy load the embedded demos so they should only load once you reach that section of the page. 

I'm also not seeing it load particularly slowly to any other Guide that we have:

https://gradio.app/creating-a-chatbot/
<img width="495" alt="image" src="https://user-images.githubusercontent.com/1778297/232825812-f58b9d54-3f9e-4811-865b-0a2c177b31cf.png">


https://gradio.app/sharing-your-app/ (with only 1 embedded demo)
<img width="518" alt="image" src="https://user-images.githubusercontent.com/1778297/232825852-aae0b1a8-c293-4f26-a3d7-cf8efae55a37.png">


So while we are working on general improvements to improve the docs (#3181), I don't think we'll do anything specific for the Chatbot Guides page.
