### ISSUE TITLE
Translate option fo the Interface

### ISSUE THREAD

**Issue by Shadhil-Imcapsule** [gradio-app/gradio#3884]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Currently i can create gradio apps which is ig better than other ui built for AI purposes. But i don't see any option to change language of gradio interface from english to some other language. 
**Describe the solution you'd like**  
Could you provide me a solution to change the interface language if their is any at the present. If not, can you improvise gradio including this feature.

**Additional context**

**Comment by abidlabs** [comment]
Hi @Shadhil-Imcapsule we have a couple of existing issues related to internationalizing the Gradio interface. Please see #1078 for built-in internationalization or #2465 for user-defined internationalization and feel free to chime into those issues.
