### ISSUE TITLE
can't open the URL with the gradio launch 

### ISSUE THREAD

**Issue by ucas010** [gradio-app/gradio#3888]
### Describe the bug

hi,dear

code
```
demo = gr.Interface(
    fn=infer,
    inputs=[gr.inputs.Image(type="pil")],
    outputs=gr.outputs.Image(type='numpy'),
    title= "")
demo.queue(concurrency_count=80, max_size=100).launch(max_threads=150,share=True,inbrowser=True,server_name="123.45.67.89",server_port=8001)
```
but I can't open http://123.45.67.89:8001 in cellphone,
so could you pls help me ?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

...

### Logs

```shell
...
```

### System Info

```shell
>>> import gradio
>>> gradio.__version__
'3.27.0'
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @ucas010 there is very little information in this issue to go off with, so I'm going to close this issue for lack of information. Please feel free to edit and re-open if you can add step-by-step methods to reproduce this issue, ideally in a reproducible environment such as a Colab notebook. But in case it helps, the `server_name` should be the *local* IP address of the server in which you want to run Gradio. It is usually `127.0.0.1` or `0.0.0.0`.
