### ISSUE TITLE
button problem

### ISSUE THREAD

**Issue by Tikquuss** [gradio-app/gradio#39]
I have my classifier that takes text and returns either 0 or 1.
But when I run gradio as described below, I don't have a button to submit the text.    
```
def predict(txt):
    vec = text_prepare(txt)
    return clf(vec) # 0 or 1


inputs = gr.inputs.Textbox(placeholder="Your text", label = "Text", lines=10)
label = gr.outputs.Label(label="Acceptability")

gr.Interface(fn = predict, inputs = inputs, outputs = label).launch()
```

**Comment by aliabd** [comment]
I'm unable to reproduce this. Can you share more details? 

This is what I see when I run your code: 

<img width="1044" alt="Screen Shot 2020-08-05 at 9 00 17 AM" src="https://user-images.githubusercontent.com/9021060/89435884-5554a480-d6fa-11ea-8b70-8983019f03aa.png">

Can you post a screenshot or share the console errors?

**Comment by aliabd** [comment]
@Tikquuss Please confirm if this is still an issue

**Comment by Tikquuss** [comment]
After thinking about it I found that my clf function had an implicit bug.
Thank you @aliabd .

**Comment by Tikquuss** [comment]
I'm working on text classification. Since gradio does not allow to submit documents, I made a django application allowing users not only to submit their text in a text area, but also to submit it through documents (pdf, docx, txt, md).
Since I don't own the application (it belongs to the company I work for), I can't provide a link here; but it works pretty much like [google translate](https://translate.google.com/?hl=fr) and [deepL](https://www.deepl.com/translator).
I'd like to add this feature to gradio, and I need your help.
