### ISSUE TITLE
crashing while analysing its own failure

### ISSUE THREAD

**Issue by AkiDuino** [gradio-app/gradio#3913]
### Describe the bug

hi, i had a prob: given a weathermap, it tells me about that and the interface, and sends me a nice foto of similar weather (road between trees on a hill in winter) .. thats ok.
i asked for how would the map look like in summer .. and it told me good enough.
then i asked why it had send me that picture, and it told me because i asked for the summer map.
time is floating here ;-)
i corrected it, and it .. said .. ok, your right
i asked if it can generate pictures of if it gets them from internet .. 
- as an ai model i do not have the ability .. - AGAIN AGAIN AGAIN AGAIN .. 
i would say thats an crash ;-)

andi

the screenshots are not really needed .. 
but its funny, even if this shows the inability to work correctly. :-/

![Chrome Legacy Window 19 04 2023 201445](https://user-images.githubusercontent.com/61632661/233167418-7fc532dc-5884-4208-948c-f5c25218eb78.jpg)
![Chrome Legacy Window 19 04 2023 201719](https://user-images.githubusercontent.com/61632661/233167425-32956784-40aa-4b01-b6a5-5f3eb763e842.jpg)
![Chrome Legacy Window 19 04 2023 201724](https://user-images.githubusercontent.com/61632661/233167431-a6a7de96-5ee7-4c9b-a657-30e88581f957.jpg)
![Chrome Legacy Window 19 04 2023 201908](https://user-images.githubusercontent.com/61632661/233167433-7a3aebca-9a59-4e37-ad48-b461b1a1b781.jpg)
![Chrome Legacy Window 19 04 2023 202041](https://user-images.githubusercontent.com/61632661/233167437-0c47037e-afca-4fae-a217-0da40c20913b.jpg)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

easy

### Logs

```shell
no
```

### System Info

```shell
not pc related
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment]
Hi @AkiDuino ! This does not seem to be a problem with gradio but rather the underlying model in that demo.

I'm going to close this. Feel free to reopen if we're misunderstanding.
