### ISSUE TITLE
How to fix "loading..." issue when accessing website after upgrading to version 3.27.0 of nginx deployed in docker with route mapping?

### ISSUE THREAD

**Issue by highroom** [gradio-app/gradio#3915]
### Describe the bug

I deployed ngnix in docker, did route mapping, and mapped the long path to 127.0.0.1:7860. When I was using version 3.17, I could access the website normally. Recently, after upgrading to version 3.27.0, it always shows "loading..." when accessing the website. I have tried changing browsers and refreshing, but it didn't work. Have any friends encountered this situation, and how to solve it? Please give me some suggestions.Thanks!

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Reproduction

use this code test
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text",server_name="0.0.0.0")
    
demo.launch(debug=True)

### Logs

```shell
gradio.Interface.launch(debug=True)
no other output
```

### System Info

```shell
ubuntu
```

### Severity

annoying

**Comment by fredhu21** [comment]
I suggest you downgrade to versoin 3.10

or you can try use direct access, new verson of gradio dose not support nginx path route, it only supports access via direct domain name or ip address. say http://youdomain.com   <--- can't support any extra path appended

**Comment by highroom** [comment]
> I suggest you downgrade to versoin 3.10我建议你降级到 versoin 3.10
> 
> or you can try use direct access, new verson of gradio dose not support nginx path route, it only supports access via direct domain name or ip address. say http://youdomain.com <--- can't support any extra path appended或者你可以尝试使用直接访问，gradio新版本不支持nginx路径路由，它只支持通过直接域名或ip地址访问。说 http://youdomain.com <--- 不支持附加的任何额外路径

thanks, i will try it.
