### ISSUE TITLE
gradio's image component and example component 

### ISSUE THREAD

**Issue by KajiMaCN** [gradio-app/gradio#3918]
- [* ] I have searched to see if a similar issue already exists.
I want to use gradio's image component to implement a feature: clicking on an image will automatically fill the image control without an image fill, how can I do this?
![image](https://user-images.githubusercontent.com/28567261/233317129-20c0bb52-df37-44e0-b082-e5c99b1c8edd.png)

**Is your feature request related to a problem? Please describe.**  
No.

**Describe the solution you'd like**  
I want to use gradio's image component to implement a feature: clicking on an image will automatically fill the image control without an image fill.

**Additional context**  
None.

**Comment by pngwn** [comment]
Could you elaborate a little? What is an image fill and what is a control image?

**Comment by KajiMaCN** [comment]
> Could you elaborate a little? What is an image fill and what is a control image?

Certainly. What I mean is that I now have three components, Image Component 1, Image Component 2 and the Examples component. I want to implement that when I click on one of the images in the Examples component, the image fills Image component 1 and when I click on the second image the image fills Image component 2. When both Image component 1 and Image component 2 are filled with images, delete one of the images in the Image component and click on the image in the Examples component again and it automatically fills the Image component without the image in the Image component that is not filled with images.

**Comment by KajiMaCN** [comment]
> Could you elaborate a little? What is an image fill and what is a control image?

At the moment I can only create two Examples components to fill them into Image Component 1 and Image Component 2 respectively.
```
gr.Examples(
                    examples=examples_img,
                    inputs=contrast_inputs_img1,
                    outputs=contrast_text_output,
                    fn=engine.contrast_infer,
                    cache_examples=False,
                    examples_per_page=6,
                )
                gr.Examples(
                    examples=examples_img,
                    inputs=contrast_inputs_img2,
                    outputs=contrast_text_output,
                    fn=engine.contrast_infer,
                    cache_examples=False,
                    examples_per_page=6,
                )
```

**Comment by KajiMaCN** [comment]
I want to use only one Examples component, click on an image in the Examples component and the clicked image will be automatically filled into the empty image component.

**Comment by abidlabs** [comment]
This is a very custom use case that isn't really possible with `gr.Examples`. You could try to hack it yourself by adding a `.click()` event to the `dataset` object within the `gr.Examples` (which you can access by doing `examples.dataset`) @KajiMaCN but this is definitely not something we'd support out of the box.
