### ISSUE TITLE
How to achieve the output image of graphics, and when the user clicks, the pop-up window zooms in and displays it

### ISSUE THREAD

**Issue by zhenzi0322** [gradio-app/gradio#3919]
How to achieve the output image of graphics, and when the user clicks, the pop-up window zooms in and displays it.

**Comment by missionfloyd** [comment]
Like this?
https://gradio.app/docs/#gallery

**Comment by abidlabs** [comment]
Hi @zhenzi0322 for general questions like this (that are not feature requests or bug reports), please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
