### ISSUE TITLE
Webcam edge case (submit then snapshot)

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#392]
Clicking submit (nothing happens) + snapshot + submit does not work even if a picture was actually taken.

Take for example https://huggingface.co/spaces/osanseviero/AnimeGANv2-webcam

**Comment by abidlabs** [comment]
I’ve been confused by this behavior as well. @aliabid94 can we fix this?

**Comment by abidlabs** [comment]
FYI @aliabid94 same thing happens with microphone. If you click submit before clicking the record button to stop recording, you can't submit even after you click the record button

**Comment by abidlabs** [comment]
Still an issue as of the latest version of Gradio (2.7.0). @dawoodkhan82

**Comment by abidlabs** [comment]
This issue no longer happens as described, which is great. HOWEVER, it is still possible to click the submit button before clicking the camera icon, which causes the interface to get submitted. We shouldn't allow this unless the webcam is optional.

**Comment by abidlabs** [comment]
Seems like this is fixed in the latest version of the webcam. Thanks!
