### ISSUE TITLE
Showing an empty page when deploy on CentOS

### ISSUE THREAD

**Issue by 1945083536** [gradio-app/gradio#3922]
### Describe the bug

I develop an application with gradio, I deployed it on windows and ubuntu and it works fine.
but when i deploy it on CentOS, i met some trouble. The service started successfully but there is an empty when I open the  URL.
I checked the page source and confirmed it contains code. I checked the console and found some error message shown below:
http://(my IP and Port)/assets/index-c2d87ffc.js   (net::ERR_ABORTED 404 (Not Found))

I tried to open the URL of js above, it can opened correctly.

could you please give me any suggestions? 

I have searched and found https://github.com/gradio-app/gradio/issues/1221 very similar with my thread, but it no effect when I change the other version.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. deploy any gradio app on centos
2. start it.
3. open URL

### Screenshot

![image](https://user-images.githubusercontent.com/13993532/233339000-b8a1907d-45ca-4db8-88df-02b02829fbb0.png)

### Logs

```shell
sorry, it have no output.
```

### System Info

```shell
Gradio:  3.26.0   3.27.0

OS:
  CentOS Linux release 8.5.2111
  NAME="CentOS Linux"
  VERSION="8"
  ID="centos"
  ID_LIKE="rhel fedora"
  VERSION_ID="8"
  PLATFORM_ID="platform:el8"
  PRETTY_NAME="CentOS Linux 8"
  ANSI_COLOR="0;31"
  CPE_NAME="cpe:/o:centos:centos:8"
  HOME_URL="https://centos.org/"
  BUG_REPORT_URL="https://bugs.centos.org/"
  CENTOS_MANTISBT_PROJECT="CentOS-8"
  CENTOS_MANTISBT_PROJECT_VERSION="8"
  CentOS Linux release 8.5.2111
  CentOS Linux release 8.5.2111
Browser: Chrome 112.0.5615.87
```

### Severity

blocking all usage of gradio

**Comment by 1945083536** [comment]
I found it displayed correctly by other browser or other machine. 
It looks my browser issues.

**Comment by freddyaboulton** [comment]
I'm glad you figured this out @1945083536 !
