### ISSUE TITLE
Gradio is inexplicably slow on some devices

### ISSUE THREAD

**Issue by Xiaobonor** [gradio-app/gradio#3926]
### Describe the bug

My website currently uses FastAPI and Gradio integration, but I found some problems. When I use my own computer to set up the server, I have no problem with my own connection and the loading speed is very fast; but when I use GCP to set up, The loading speed of some devices is abnormally slow, and some are very fast. And this problem only occurs in Gradio, when I return to the FastAPI webpage, all devices are normal again.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

--- Skip import and FastAPI ---

url_params = gr.JSON({}, visible=False, label="URL Params")
with gr.Blocks(css=customCSS, theme=small_and_beautiful_theme) as demo:

    # ! 提示未登入
    url_params.render()
    notlogn_warn = gr.HTML("""
    <center><h2>您的登入憑證已失效, 請點擊<a href="https://betterchat.onlluin.com:80/TryAcessKeyLogin" rel="noopener noreferrer" target="_blank">此處</a>來返回登入</h2></center>
    """, visible=False)
    #

    tokens = gr.State("")
    promptTemplates = gr.State(load_template(get_template_names(plain=True)[0], mode=2))
    user_question = gr.State("")
    user_api_key = gr.State(my_api_key)
    current_model = gr.State(create_new_model)
    
    # def parse_URL_params(url_params):
    #     if 'accesstoken' in url_params:
    #         token = url_params['accesstoken']
    #         print("用戶訪問許可:")
    #         print(token)
    #     return {
    #         tokens: token
    #     }

    with gr.Row():
        gr.HTML(CHUANHU_TITLE, elem_id="app_title")
        status_display = gr.Markdown("[通知] 若您每次載入都耗時非常久 代表您的網路不穩定, 請嘗試更換網路.", elem_id="status_display")

    # with gr.Row(elem_id="float_display"):
    #     user_info = gr.Markdown(value="getting user info...", elem_id="user_info")

    #     # https://github.com/gradio-app/gradio/pull/3296
    #     def create_greeting(request: gr.Request):
    #         if hasattr(request, "username") and request.username: # is not None or is not ""
    #             logging.info(f"Get User Name: {request.username}")
    #             return gr.Markdown.update(value=f"User: {request.username}"), request.username
    #         else:
    #             return gr.Markdown.update(value=f"User: default", visible=False), ""
    #     demo.load(create_greeting, inputs=None, outputs=[user_info, user_name])

    with gr.Row().style(equal_height=True):
        with gr.Column(scale=5):
            with gr.Row():
                chatbot = gr.Chatbot(elem_id="chuanhu_chatbot").style(height="100%")
            with gr.Row():
                with gr.Column(min_width=225, scale=12):
                    user_input = gr.Textbox(
                        elem_id="user_input_tb",
                        show_label=False, placeholder=i18n("在这里输入")
                    ).style(container=False)
                with gr.Column(min_width=42, scale=1):
                    submitBtn = gr.Button(value="", variant="primary",interactive =True,  elem_id="submit_btn")
                    cancelBtn = gr.Button(value="", variant="secondary", visible=False, elem_id="cancel_btn")
            with gr.Row():
                emptyBtn = gr.Button(
                    i18n("🧹 新的對話 "),
                )
                retryBtn = gr.Button(i18n("🔄 重新生成"))
                delFirstBtn = gr.Button(i18n("🗑️ 删除最旧对话"))
                delLastBtn = gr.Button(i18n("🗑️ 删除最新对话"))

        with gr.Column():
            with gr.Column(min_width=50, scale=1):
                with gr.Tab(label=i18n("模型")):
                    keyTxt = gr.Textbox(
                        show_label=True,
                        placeholder=f"OpenAI API-key...",
                        value=hide_middle_chars(user_api_key.value),
                        type="password",
                        visible=not HIDE_MY_KEY,
                        interactive=False,
                        label="API-Key",
                    )
                    # if multi_api_key:
                    #     usageTxt = gr.Markdown(i18n("多账号模式已开启，无需输入key，可直接开始对话"), elem_id="usage_display", elem_classes="insert_block")
                    # else:
                    usageTxt = gr.Markdown(i18n("**发送消息** 或 **提交key** 以显示额度"), elem_id="usage_display", elem_classes="insert_block")

                    model_select_dropdown = gr.Dropdown(
                        label=i18n("选择模型"), choices=MODELS, multiselect=False, value=MODELS[DEFAULT_MODEL], interactive=True
                    )
                    lora_select_dropdown = gr.Dropdown(
                        label=i18n("选择LoRA模型"), choices=[], multiselect=False, interactive=True, visible=False
                    )
                    with gr.Row():
                        use_streaming_checkbox = gr.Checkbox(
                            label=i18n("实时传输回答"), value=True, visible=ENABLE_STREAMING_OPTION
                        )
                        image_generation_checkbox = gr.Checkbox(label="圖片生成功能", value=False)
                        use_websearch_checkbox = gr.Checkbox(label=i18n("使用在线搜索"), value=False)
                    language_select_dropdown = gr.Dropdown(
                        label=i18n("选择回复语言（针对搜索&索引功能）"),
                        choices=REPLY_LANGUAGES,
                        multiselect=False,
                        value=REPLY_LANGUAGES[0],
                    )
                    index_files = gr.Files(label=i18n("上传索引文件"), type="file")
                    two_column = gr.Checkbox(label=i18n("双栏pdf"), value=advance_docs["pdf"].get("two_column", False))
                    # TODO: 公式ocr
                    # formula_ocr = gr.Checkbox(label=i18n("识别公式"), value=advance_docs["pdf"].get("formula_ocr", False))

                with gr.Tab(label="Prompt"):
                    systemPromptTxt = gr.Textbox(
                        show_label=True,
                        placeholder=i18n("在这里输入System Prompt..."),
                        label="System prompt",
                        value=INITIAL_SYSTEM_PROMPT,
                        lines=10,
                    ).style(container=False)
                    with gr.Accordion(label=i18n("加载Prompt模板"), open=True):
                        with gr.Column():
                            with gr.Row():
                                with gr.Column(scale=6):
                                    templateFileSelectDropdown = gr.Dropdown(
                                        label=i18n("选择Prompt模板集合文件"),
                                        choices=get_template_names(plain=True),
                                        multiselect=False,
                                        value=get_template_names(plain=True)[0],
                                    ).style(container=False)
                                with gr.Column(scale=1):
                                    templateRefreshBtn = gr.Button(i18n("🔄 刷新"))
                            with gr.Row():
                                with gr.Column():
                                    templateSelectDropdown = gr.Dropdown(
                                        label=i18n("从Prompt模板中加载"),
                                        choices=load_template(
                                            get_template_names(plain=True)[0], mode=1
                                        ),
                                        multiselect=False,
                                    ).style(container=False)

                with gr.Tab(label=i18n("保存/加载")):
                    with gr.Accordion(label=i18n("保存/加载对话历史记录"), open=True):
                        with gr.Column():
                            with gr.Row():
                                with gr.Column(scale=6):
                                    historyFileSelectDropdown = gr.Dropdown(
                                        label=i18n("从列表中加载对话"),
                                        choices=get_history_names(plain=True),
                                        multiselect=False,
                                        value=get_history_names(plain=True)[0],
                                    )
                                with gr.Column(scale=1):
                                    historyRefreshBtn = gr.Button(i18n("🔄 刷新"))
                            with gr.Row():
                                with gr.Column(scale=6):
                                    saveFileName = gr.Textbox(
                                        show_label=True,
                                        placeholder=i18n("设置文件名: 默认为.json，可选为.md"),
                                        label=i18n("设置保存文件名"),
                                        value=i18n("对话历史记录"),
                                    ).style(container=True)
                                with gr.Column(scale=1):
                                    saveHistoryBtn = gr.Button(i18n("💾 保存对话"))
                                    exportMarkdownBtn = gr.Button(i18n("📝 导出为Markdown"))
                                    gr.Markdown(i18n("默认保存于history文件夹"))
                            with gr.Row():
                                with gr.Column():
                                    downloadFile = gr.File(interactive=True)

                with gr.Tab(label="設定"):
                    gr.Markdown(i18n("# ⚠️ 請謹慎調整 ⚠️\n\n如果你不清楚這是什麼, 請不要隨意亂動"))

                    gr.HTML(APPEARANCE_SWITCHER, elem_classes="insert_block")
                    with gr.Accordion(i18n("参数調整"), open=False):
                        temperature_slider = gr.Slider(
                            minimum=-0,
                            maximum=2.0,
                            value=1.0,
                            step=0.1,
                            interactive=True,
                            label="temperature",
                        )
                        top_p_slider = gr.Slider(
                            minimum=-0,
                            maximum=1.0,
                            value=1.0,
                            step=0.05,
                            interactive=True,
                            label="top-p",
                        )
                        n_choices_slider = gr.Slider(
                            minimum=1,
                            maximum=10,
                            value=1,
                            step=1,
                            interactive=True,
                            label="n choices",
                        )
                        # stop_sequence_txt = gr.Textbox(
                        #     show_label=True,
                        #     placeholder=i18n("在这里输入停止符，用英文逗号隔开..."),
                        #     label="stop",
                        #     value="",
                        #     lines=1,
                        # )
                        max_context_length_slider = gr.Slider(
                            minimum=1,
                            maximum=32768,
                            value=2000,
                            step=1,
                            interactive=True,
                            label="max context",
                        )
                        max_generation_slider = gr.Slider(
                            minimum=1,
                            maximum=32768,
                            value=1000,
                            step=1,
                            interactive=True,
                            label="max generations",
                        )
                        presence_penalty_slider = gr.Slider(
                            minimum=-2.0,
                            maximum=2.0,
                            value=0.0,
                            step=0.01,
                            interactive=True,
                            label="presence penalty",
                        )
                        frequency_penalty_slider = gr.Slider(
                            minimum=-2.0,
                            maximum=2.0,
                            value=0.0,
                            step=0.01,
                            interactive=True,
                            label="frequency penalty",
                        )
                        # logit_bias_txt = gr.Textbox(
                        #     show_label=True,
                        #     placeholder=f"word:likelihood",
                        #     label="logit bias",
                        #     value="",
                        #     lines=1,
                        # )
                        # user_identifier_txt = gr.Textbox(
                        #     show_label=True,
                        #     placeholder=i18n("用于定位滥用行为"),
                        #     label=i18n("用户名"),
                        #     value=user_name.value,
                        #     lines=1,
                        # )

                    userlogut = gr.Button("🚪 登出帳號")
                    usersetting = gr.Button("🌐 帳號設定(未開放)" , interactive=False)
                    usettobuy = gr.Button("💳 升級帳號(未開放)" , interactive=False)

                    # with gr.Accordion(i18n("网络设置"), open=False):
                    #     # 优先展示自定义的api_host
                    #     apihostTxt = gr.Textbox(
                    #         show_label=True,
                    #         placeholder=i18n("在这里输入API-Host..."),
                    #         label="API-Host",
                    #         value=config.api_host or shared.API_HOST,
                    #         lines=1,
                    #     )
                    #     changeAPIURLBtn = gr.Button(i18n("🔄 切换API地址"))
                    #     proxyTxt = gr.Textbox(
                    #         show_label=True,
                    #         placeholder=i18n("在这里输入代理地址..."),
                    #         label=i18n("代理地址（示例：https://127.0.0.1:10809）"),
                    #         value="",
                    #         lines=2,
                    #     )
                    #     changeProxyBtn = gr.Button(i18n("🔄 设置代理地址"))
                    #     default_btn = gr.Button(i18n("🔙 恢复默认设置"))

    def echos(url_params, request: gr.Request):
        token = url_params.get('accesstoken')

        if token:
            print("用戶訪問許可:")
            print(token)
            if request:
                print("IP address:", request.client.host)
                print("User name:", request.username)

            with sqlite3.connect('accesstoken.db') as tokedb:
                cursor = tokedb.execute("SELECT * FROM users WHERE accesstoken=?", (token,))
                row = cursor.fetchone()

                if not row:
                    return disable_interactivity("您目前的 Tokens 已耗盡 (無法繼續使用,請購買Tokens)")

                tokedb.execute("DELETE FROM users WHERE accesstoken=?", (token,))
                tokedb.commit()

            with sqlite3.connect('data.db') as conn:
                cursor = conn.execute("SELECT * FROM users WHERE ip=?", (token,))
                row = cursor.fetchone()

                if not row:
                    return disable_interactivity("無法成功獲取登入訊息")

                tokens = row[3]

                if tokens <= 0:
                    return disable_interactivity("您目前的 Tokens 已耗盡 (暫時無法繼續使用)")

            return enable_interactivity("發送消息 來顯示您剩餘的 Tokens 數")
        else:
            return disable_interactivity("無法成功獲取登入訊息")

    def disable_interactivity(message):
        return (
            gr.Button.update(interactive=False),
            gr.Button.update(interactive=False),
            gr.Button.update(interactive=False),
            gr.Button.update(interactive=False),
            gr.Button.update(interactive=False),
            gr.Button.update(interactive=False),
            gr.Button.update(interactive=False),
            gr.Button.update(interactive=False),
            gr.Button.update(interactive=False),
            gr.Textbox.update(interactive=False),
            gr.File.update(interactive=False),
            gr.File.update(interactive=False),
            gr.HTML.update("""<meta http-equiv="refresh" content="0;url=https://betterchat.onlluin.com:80/TryAcessKeyLogin">"""),
            gr.Markdown.update(f"**{message}**")
        )

    def enable_interactivity(message):
        return (
            gr.Button.update(interactive=True),
            gr.Button.update(interactive=True),
            gr.Button.update(interactive=True),
            gr.Button.update(interactive=True),
            gr.Button.update(interactive=True),
            gr.Button.update(interactive=True),
            gr.Button.update(interactive=True),
            gr.Button.update(interactive=True),
            gr.Button.update(interactive=True),
            gr.Textbox.update(interactive=True),
            gr.File.update(interactive=True),
            gr.File.update(interactive=True),
            gr.HTML.update(visible=False),
            gr.Markdown.update(f"**{message}**")
        )

    demo.load(
            fn=echos,
            inputs=[url_params],
            outputs=[submitBtn, emptyBtn, retryBtn, delFirstBtn, 
                    delLastBtn , templateRefreshBtn, historyRefreshBtn, 
                    saveHistoryBtn,exportMarkdownBtn,user_input, index_files, downloadFile, notlogn_warn, usageTxt],
            show_progress=True,
            _js=get_window_url_params
        )
    

    demo.load(
            fn=get_history_names,
            inputs=[gr.State(False), url_params],
            outputs=[historyFileSelectDropdown],
            _js=get_window_url_params3
        )

    gr.Markdown(CHUANHU_DESCRIPTION, elem_id="description")
    chatgpt_predict_args = dict(
        fn=predict,
        inputs=[
            current_model,
            user_question,
            chatbot,
            use_streaming_checkbox,
            use_websearch_checkbox,
            image_generation_checkbox,
            index_files,
            language_select_dropdown,
        ],
        outputs=[chatbot, status_display],
        show_progress=True,
    )

    start_outputing_args = dict(
        fn=start_outputing,
        inputs=[],
        outputs=[submitBtn, cancelBtn],
        show_progress=False,
    )

    end_outputing_args = dict(
        fn=end_outputing, inputs=[url_params], outputs=[submitBtn, cancelBtn, usageTxt, user_input, retryBtn], _js=get_window_url_params, show_progress=False
    )

    # reset_textbox_args = dict(
    #     fn=reset_textbox, inputs=[], outputs=[user_input]
    # )

    transfer_input_args = dict(
        fn=transfer_input, inputs=[user_input], outputs=[user_question, user_input, submitBtn, cancelBtn], show_progress=False
    )

    get_usage_args = dict(
        fn=billing_info, inputs=[current_model], outputs=[usageTxt], show_progress=False
    )

    load_history_from_file_args = dict(
        fn=load_chat_history,
        inputs=[current_model, historyFileSelectDropdown, chatbot, url_params],
        outputs=[saveFileName, systemPromptTxt, chatbot],
        _js=get_window_url_params2
    )

    # user

    def _gologout():
        return gr.HTML.update("""<meta http-equiv="refresh" content="0;url=https://betterchat.onlluin.com:80/logout">""")

    gologout = dict(
        fn=_gologout, inputs=[], outputs=[notlogn_warn]
    )

    def _gohomepage():
        return gr.HTML.update("""<meta http-equiv="refresh" content="0;url=https://betterchat.onlluin.com:80/">""")

    gohomepage = dict(
        fn=_gohomepage, inputs=[], outputs=[notlogn_warn]
    )

    usersetting.click(**gohomepage)
    userlogut.click(**gologout)

    # Chatbot
    cancelBtn.click(interrupt, [current_model], [])

    user_input.submit(**transfer_input_args).then(**chatgpt_predict_args).then(**end_outputing_args)
    user_input.submit(**get_usage_args)
            

    submitBtn.click(**transfer_input_args).then(**chatgpt_predict_args).then(**end_outputing_args)
    submitBtn.click(**get_usage_args)

    index_files.change(handle_file_upload, [current_model, index_files, chatbot], [index_files, chatbot, status_display])

    emptyBtn.click(
        reset,
        inputs=[current_model],
        outputs=[chatbot, status_display],
        show_progress=True,
    )

    retryBtn.click(**start_outputing_args).then(
        retry,
        [
            current_model,
            chatbot,
            use_streaming_checkbox,
            use_websearch_checkbox,
            image_generation_checkbox,
            index_files,
            language_select_dropdown,
        ],
        [chatbot, status_display],
        show_progress=True,
    ).then(**end_outputing_args)
    retryBtn.click(**get_usage_args)

    delFirstBtn.click(
        delete_first_conversation,
        [current_model],
        [status_display],
    )

    delLastBtn.click(
        delete_last_conversation,
        [current_model, chatbot],
        [chatbot, status_display],
        show_progress=False
    )

    two_column.change(update_doc_config, [two_column], None)

    # LLM Models
    keyTxt.change(set_key, [current_model, keyTxt], [user_api_key, status_display]).then(**get_usage_args)
    keyTxt.submit(**get_usage_args)
    model_select_dropdown.change(get_model, [model_select_dropdown, lora_select_dropdown, user_api_key, temperature_slider, top_p_slider, systemPromptTxt], [current_model, status_display, lora_select_dropdown], show_progress=True)
    lora_select_dropdown.change(get_model, [model_select_dropdown, lora_select_dropdown, user_api_key, temperature_slider, top_p_slider, systemPromptTxt], [current_model, status_display], show_progress=True)

    # Template
    systemPromptTxt.change(set_system_prompt, [current_model, systemPromptTxt], None)
    templateRefreshBtn.click(get_template_names, None, [templateFileSelectDropdown])
    templateFileSelectDropdown.change(
        load_template,
        [templateFileSelectDropdown],
        [promptTemplates, templateSelectDropdown],
        show_progress=True,
    )
    templateSelectDropdown.change(
        get_template_content,
        [promptTemplates, templateSelectDropdown, systemPromptTxt],
        [systemPromptTxt],
        show_progress=True,
    )

    # S&L
    saveHistoryBtn.click(
        save_chat_history,
        [current_model, saveFileName, chatbot, url_params],
        downloadFile,
        show_progress=True,
        _js=get_window_url_params2
    )
    
    saveHistoryBtn.click(get_history_names, [gr.State(False), url_params], [historyFileSelectDropdown], _js=get_window_url_params3)
    exportMarkdownBtn.click(
        export_markdown,
        [current_model, saveFileName, chatbot, url_params],
        downloadFile,
        show_progress=True,
        _js=get_window_url_params2
    )
    historyRefreshBtn.click(get_history_names, [gr.State(False), url_params], [historyFileSelectDropdown], _js=get_window_url_params3)
    historyFileSelectDropdown.change(**load_history_from_file_args)
    downloadFile.change(**load_history_from_file_args)

    # Advanced
    max_context_length_slider.change(set_token_upper_limit, [current_model, max_context_length_slider], None)
    temperature_slider.change(set_temperature, [current_model, temperature_slider], None)
    top_p_slider.change(set_top_p, [current_model, top_p_slider], None)
    n_choices_slider.change(set_n_choices, [current_model, n_choices_slider], None)
    # stop_sequence_txt.change(set_stop_sequence, [current_model, stop_sequence_txt], None)
    max_generation_slider.change(set_max_tokens, [current_model, max_generation_slider], None)
    presence_penalty_slider.change(set_presence_penalty, [current_model, presence_penalty_slider], None)
    frequency_penalty_slider.change(set_frequency_penalty, [current_model, frequency_penalty_slider], None)
    # logit_bias_txt.change(set_logit_bias, [current_model, logit_bias_txt], None)
    # user_identifier_txt.change(set_user_identifier, [current_model, user_identifier_txt], None)

    # default_btn.click(
    #     reset_default, [], [apihostTxt, proxyTxt, status_display], show_progress=True
    # )
    # changeAPIURLBtn.click(
    #     change_api_host,
    #     [apihostTxt],
    #     [status_display],
    #     show_progress=True,
    # )
    # changeProxyBtn.click(
    #     change_proxy,
    #     [proxyTxt],
    #     [status_display],
    #     show_progress=True,
    # )

import uvicorn

# 默认开启本地服务器，默认可以直接从IP访问，默认不创建公开分享链接
demo.title = i18n("BetterChat 🚀")
demo.share = True
gradio_app = gr.mount_gradio_app(app, demo.queue(concurrency_count=1000000), "/gradio")
uvicorn.run(gradio_app, host="0.0.0.0", port=80,
        ssl_keyfile="private.key",
        ssl_certfile="certificate.crt",
        ssl_ca_certs="ca_bundle.crt",
        )

### Screenshot

on my phone:

https://cdn.discordapp.com/attachments/1035533433545441372/1098775677907517530/Screen_Recording_20230421_090202_Chrome.mp4

on my PC:

https://cdn.discordapp.com/attachments/1035533433545441372/1098775760896008312/2023-04-21_09-01-31.mp4

### Logs

```shell
*
```

### System Info

```shell
aiohttp==3.8.4
Authlib==1.2.0
click==8.1.3
colorama==0.4.6
commentjson==0.9.0
duckduckgo_search==2.8.5
fastapi==0.95.1
gradio==3.27.0
gradio_client==0.1.3
itsdangerous==2.1.2
langchain==0.0.144
llama_index==0.5.13
lmflow==0.0.1.dev0
Markdown==3.4.3
mdtex2html==1.2.0
openai==0.27.2
pandas==1.5.3
pdfplumber==0.9.0
Pillow==9.4.0
Pygments==2.14.0
PyPDF2==3.0.1
pypinyin==0.48.0
Requests==2.28.2
starlette==0.26.1
tiktoken==0.3.3
torch==2.0.0
tqdm==4.64.1
transformers==4.28.1
urllib3==1.26.14
uvicorn==0.21.1
```

### Severity

annoying

**Comment by Nancis1130** [comment]
I also have the same problem. Have you solved it?

**Comment by space-nuko** [comment]
I would also like to report issues with performance on bad network (my connection was SSH tunneled internationally). I'd get infinite loading bars on some components with no way to reset the state of the UI except refreshing the page (meaning I lose all my settings). And the backend still works if I do that so I think there should be a "panic button" option to reset the frontend state if things break. That or an actual timeout on component loading progress if a connection times out maybe made configurable by seconds. The performance issues made gradio practically unusable for me on my phone

**Comment by abidlabs** [comment]
Unfortunately, we're having a very hard time reproducing this problem in a similar environment. Any hosted permanent links we can examine would help

**Comment by abidlabs** [comment]
Closing for lack of followup -- please feel free to reopen if anyone could provide us a clear repro.
