### ISSUE TITLE
cannot use uploadbutton to upload same file twice

### ISSUE THREAD

**Issue by RubanSeven** [gradio-app/gradio#3928]
### Describe the bug

I Want to use uploadbutton to upload same file twice. But, failed.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

def image_upload(image, history):
    return history + [((image.name,), "")]

image_btn = gr.UploadButton(
                        label=‘image', file_types=['image']
                    ).style(full_width=False, size='sm', container=False)

image_btn.upload(image_upload, inputs=[image_btn, chatbot], outputs=[chatbot])

### Logs

```shell
debug=False
```

### System Info

```shell
3.27.0
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
The upload event is not being triggered @dawoodkhan82 @aliabid94.

It's noticeable in the `chatbot_multimodal` demo as the image is not added to the chat since the upload event is not triggered.

**Comment by dawoodkhan82** [comment]
Will take a look
