### ISSUE TITLE
Add Online Learning

### ISSUE THREAD

**Issue by NouamaneTazi** [gradio-app/gradio#393]
Add a 'Correct' button that would allow the user to correct the output and save it to a database. So that the app owner can retrain the model on these instances later on.

**Comment by abidlabs** [comment]
Can you please provide more info on your use case? What kind of model / inputs / outputs do you have in mind?

**Comment by NouamaneTazi** [comment]
Hello! I'm thinking about a text generation example, where after the user gets his input, besides being able to Flag the answer, they can also 'Correct' it.
I'm working on an example for my huggingface space https://huggingface.co/spaces/nouamanetazi/cover-letter-generator . 
I'm hoping for it to be my first contribution if it works 😁

**Comment by abidlabs** [comment]
That makes sense. Have you looked into `flagging_options` parameter in the `Interface` class. It allows you to pass in different choices that someone can select when they click flag. If this is not sufficient for you, please let me know and we'll try to support your use case.

**Comment by abidlabs** [comment]
Going to close because I think `flagging_options` usually is sufficient for these use cases. @NouamaneTazi let me know if this is not the case for you.
