### ISSUE TITLE
Can not integrate a Gradio demo to a W&B dashboard

### ISSUE THREAD

**Issue by efsansokmen** [gradio-app/gradio#3933]
### Describe the bug

Hi,
I am trying to integrate a Gradio demo to a W&B dashboard while I was running a python script from a docker container hosted by a HF space. I have found through [this link](https://gradio.app/Gradio-and-Wandb-Integration/) that it is as easy as:
`demo.integrate(wandb=wandb)`
given a `demo.launch(share=True)` exists prior to that.
However, I got this error:
```
Traceback (most recent call last):
  File "app.py", line 279, in <module>
    demo.queue().launch(share=True) #api_open=True, concurrency_count=1
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/gradio/blocks.py", line 1539, in launch
    raise RuntimeError("Share is not supported when you are in Spaces")
RuntimeError: Share is not supported when you are in Spaces
```
I also tried removing 'share=True' from launch(), but then it opens the browser with the Gradio app and freezes, without any error or so. 

This is the output:
`initializing model parallel with size 1
initializing ddp with size 1
initializing pipeline with size 1
Loading
in 14.72 seconds
cache from '/home/user/app/gradio_cached_examples/18' directory. If method or examples have changed since last caching, delete this folder to clear cache.
cache from '/home/user/app/gradio_cached_examples/34' directory. If method or examples have changed since last caching, delete this folder to clear cache.
on local URL:  http://0.0.0.0:7860/
create a public link, set `share=True` in `launch()`.`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

# I run llama-adapter Space with my dataset mounted in /home/user/app/datasets/. My local dataset is stored in /home/user/datasets. I use a virtual machine on Google Cloud Platform.

docker run -it --gpus 0 -p 7860:7860 -v /home/user/datasets/:/home/user/app/datasets/ registry.hf.space/csuhan-llama-adapter:latest

### Screenshot

![Screenshot 2023-04-21 155341](https://user-images.githubusercontent.com/128058426/233654203-6157a696-e68e-4426-90bd-acda441e6abe.png)
![Screenshot 2023-04-21 154724](https://user-images.githubusercontent.com/128058426/233654215-8108d851-0fa1-41f1-9de9-4a7a94d51103.png)

### Logs

```shell
user@19b3a850f36e:~/app$ python app.py 
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 2
wandb: You chose 'Use an existing W&B account'
wandb: You can find your API key in your browser here: https://wandb.mlops.ingka.com/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit: 
wandb: Appending key for wandb.mlops.ingka.com to your netrc file: /home/user/.netrc
wandb: Currently logged in as: efsan-sokmen (digital-ethics-responsible-ai). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.15.0
wandb: Run data is saved locally in /home/user/app/wandb/run-20230421_170541-1esrrrqx
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run fresh-cloud-9
wandb: ⭐️ View project at https://wandb.mlops.ingka.com/digital-ethics-responsible-ai/hej-gpt
wandb: 🚀 View run at https://wandb.mlops.ingka.com/digital-ethics-responsible-ai/hej-gpt/runs/1esrrrqx
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Loading
Loaded in 13.97 seconds
Using cache from '/home/user/app/gradio_cached_examples/18' directory. If method or examples have changed since last caching, delete this folder to clear cache.
Using cache from '/home/user/app/gradio_cached_examples/34' directory. If method or examples have changed since last caching, delete this folder to clear cache.
Running on local URL:  http://0.0.0.0:7860
Traceback (most recent call last):
  File "app.py", line 287, in <module>
    demo.queue(api_open=True, concurrency_count=2).launch(debug=True, share=True)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/gradio/blocks.py", line 1539, in launch
    raise RuntimeError("Share is not supported when you are in Spaces")
RuntimeError: Share is not supported when you are in Spaces
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 🚀 View run fresh-cloud-9 at: https://wandb.mlops.ingka.com/digital-ethics-responsible-ai/hej-gpt/runs/1esrrrqx
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 1 other file(s)
wandb: Find logs at: ./wandb/run-20230421_170541-1esrrrqx/logs
```

### System Info

```shell
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Hi @efsansokmen instead of using the `.integrate()` method, I'd recommend just that you create a panel directly:

```py
wandb.Html(f'<iframe src={src} frameBorder="0"></iframe>')
```

Here `src` should be the URL of the iframe running inside the Space. E.g. something like: `https://hysts-sd-xl.hf.space/`
