### ISSUE TITLE
The content of the Gradio widget has returned to its original state after refreshing the page.

### ISSUE THREAD

**Issue by bitxinyu** [gradio-app/gradio#3936]
### Describe the bug

Hi，In my project, I used a `CheckboxgGoup` widget to delete multiple models. When deleting, I used `update` to update the content of the widget. The models were indeed deleted. Everything looks good. But when I refresh the page, the names of the deleted models appear again in the widget. Here is my code.
```python
import gradio as gr

class ModelManager:
    def __init__(self):
        self.model_name_2_config = {"openai_1": "xxx", "openai_2": "xx"}
    @property
    def model_list(self):
        return list(self.model_name_2_config.keys())

    def delete_model(self, name):
        self.model_name_2_config.pop(name)

model_manager = ModelManager()

with gr.Blocks() as demo:
    gr.Markdown("Delete Models")

    def delete_model_button_click(want_delete_models):
        for i in want_delete_models:
            model_manager.delete_model(i)
        return gr.update(choices=model_manager.model_list, value=[])

    want_delete_models = gr.CheckboxGroup(choices=model_manager.model_list, label='Delete Models', )
    delete_model_button = gr.Button('Delete Model')

    delete_model_button.click(fn=delete_model_button_click, inputs=want_delete_models, outputs=want_delete_models)
demo.launch()
```

![image](https://user-images.githubusercontent.com/11964010/233673546-a71fa740-8057-4018-91f6-d4e9205bb6b7.png)
After I deleted openai_2 and refreshed the page, it reappeared.

After my testing, if `model_manager.model_list` returns a new object. This bug will occur.
Here is my test code
```python
import gradio as gr

class ModelManager:
    def __init__(self):
        self.model_name_2_config = {"openai_1": "xxx", "openai_2": "xx"}
        self.model_name_list = ["openai_1", "openai_2"]
    @property
    def model_list(self):
        # return self.model_name_list
        return list(self.model_name_list)

    def delete_model(self, name):
        self.model_name_2_config.pop(name)

    def delete_model2(self, name):
        self.model_name_list.remove(name)
        
model_manager = ModelManager()

with gr.Blocks() as demo:
    gr.Markdown("Delete Models")
    def delete_model_button_click(want_delete_models):
        for i in want_delete_models:
            model_manager.delete_model2(i)
        return gr.update(choices=model_manager.model_list, value=[])

    want_delete_models = gr.CheckboxGroup(choices=model_manager.model_list, label='Delete Models', )
    delete_model_button = gr.Button('Delete Model')

    delete_model_button.click(fn=delete_model_button_click, inputs=want_delete_models, outputs=want_delete_models)
demo.launch()
```
In this code snippet, the bug will also occur.

However, if you comment out `return list(self.model_name_list)` and  uncomment `return self.model_name_list`  , the bug will disappear.
It seems that after refreshing the page, 'choices' still points to the old 'model_manager.model_list' address.
Is a bug or a feature?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

see above

### Logs

```shell
no
```

### System Info

```shell
gradio： 3.27.0
macos version: 13.2.1
chrome: 111.0.5563.146
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment]
Hi @bitxinyu !

Yes this is working as intended. The starting values of components are stored in the config (go to `<url>/config`), and the config is created once when the app is first launched. So that's why it always shows the initial model names.

One thing you can do is set the value to be a function, I think something like `value=lambda: model_manager.model_list` will work.

However, note that using global variables for state will introduce some problems if more than one person is using the app at the same time. Using a `gr.State` (https://gradio.app/interface-state/) is usually the recommended approach.

**Comment by bitxinyu** [comment]
> Hi @bitxinyu !
> 
> Yes this is working as intended. The starting values of components are stored in the config (go to `<url>/config`), and the config is created once when the app is first launched. So that's why it always shows the initial model names.
> 
> One thing you can do is set the value to be a function, I think something like `value=lambda: model_manager.model_list` will work.
> 
> However, note that using global variables for state will introduce some problems if more than one person is using the app at the same time. Using a `gr.State` (https://gradio.app/interface-state/) is usually the recommended approach.

I have seen the use of lambda to assign a value in other issues, but in CheckboxGroup, I am not concerned about the value, but the choices. When I use choices=lambda: model_manager.model_list, Gradio tells me `TypeError: 'function' object is not subscriptable`
