### ISSUE TITLE
REST API not working anymore?

### ISSUE THREAD

**Issue by Ivanho92** [gradio-app/gradio#3937]
### Describe the bug

Dear Gradio Team,

I recently deployed a machine learning app with the help of your library. You can find it live on https://huggingface.co/spaces/ivanho92/training. However, I have trouble consuming the API that should have been automatically generated when this app was built.

I have tried several different requests through Postman, but I keep getting a "404 Not Found" error. I've followed the instructions in the documentation and have double-checked the endpoint URL, but I still can't get it to work.

Here's an example of a postman request I have tried:
![image](https://user-images.githubusercontent.com/51017707/233689178-ca9297d5-d5d9-4ace-a10d-c08873f2cf29.png)

I noticed that in a previous related tutorial video (https://youtu.be/F4tvM4Vb3A0?t=3729), the REST API seemed to be working fine, so I'm not sure what I'm doing wrong.

Could you please help me figure out what's going on? I would greatly appreciate any assistance you can provide.

Thank you very much for your help.

Best regards,
Ivan

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Build any ML app with Gradio
2. Try consuming its API through Postman

### Logs

```shell
I don't have specific errors on the console. Just a 404 Not Found in Postman.
```

### System Info

```shell
I am not sure it's relevant here.
```

### Severity

blocking all usage of gradio

**Comment by freddyaboulton** [comment]
Hi @Ivanho92 !

The right route is `/api/predict` not `/predict`! Also, in order to properly send an image, you need to convert it to base64 ahead of time.

<img width="750" alt="image" src="https://user-images.githubusercontent.com/41651716/233712861-cf02bdb9-6e4d-484e-9c20-79b0a2160d99.png">

We recently released the python client library to make this easier!

https://gradio.app/getting-started-with-the-python-client/

**Comment by yosun** [comment]
@freddyaboulton  does this still work - i keep getting this error `{"detail":"This API endpoint does not accept direct HTTP POST requests. Please join the queue to use this API."}`

**Comment by freddyaboulton** [comment]
Hi @yosun ! You can use the `/queue/join` API route but that's not really supported (see [here](https://github.com/gradio-app/gradio/issues/4932#issuecomment-1793639325)).

The preferred way to use gradio applications programmatically is via the clients: https://www.gradio.app/guides/getting-started-with-the-python-client

**Comment by yosun** [comment]
> Hi @yosun ! You can use the `/queue/join` API route but that's not really supported (see [here](https://github.com/gradio-app/gradio/issues/4932#issuecomment-1793639325)).
> 
> The preferred way to use gradio applications programmatically is via the clients: https://www.gradio.app/guides/getting-started-with-the-python-client

What if you're using a stack that the python client does not support?
