### ISSUE TITLE
Adding drawing on webcam image

### ISSUE THREAD

**Issue by blre6** [gradio-app/gradio#3938]
Hi,

I’m trying to display a live video stream from the webcam while adding a rectangle on the image, using Blocks.

So this is what I have:

Def draw(im):
cv2.rectangle(im,(50,50), (200,200), (0, 255, 255), 2)
return im

with gr.Blocks() as demo:
inp = gr.Image(source=“webcam”, shape=(250,250), streaming=True)
out = gr.Image(label=‘Out-Calibration’, )
inp.change(draw, inp, out)

This works and does what I expect it to do, but the output image is flickering, which is annoying.

Am I doing something wrong here? is there a better way to do this?

Thanks!
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by abidlabs** [comment]
cc @aliabid94 can we improve the experience here?

**Comment by blre6** [comment]
Can we capture the image  at intervals, such as every second? When I set streaming=True, the refresh frequency is so fast that I can't see the result clearly, then I enter the interface of processing. I saw an issue with refresh_rate, which I thought would solve my problem, but I didn't find this parameter.

**Comment by blre6** [comment]
@abidlabs

**Comment by abidlabs** [comment]
I don't think that's possible at the moment, but let me cc @aliabid94 who may know more

**Comment by blre6** [comment]
#692

**Comment by blre6** [comment]
#692

**Comment by dchichkov** [comment]
Can we have a hook to preprocess the original webcam image before displaying?  

I'm suspecting that in many cases there is no need to display the original webcam image, only the one post-processed one is of interest.  And the original webcam image is consuming the space.

**Comment by blre6** [comment]
I solved the problem.When I set it to show_progress=False, the screen no longer flickers. Thanks for the answer

**Comment by blre6** [comment]
> inp.change(people, inp, [out,peo_count], show_progress=False)
When I set it to show_progress=False, the screen no longer **flickers**
@abidlabs  Thanks for your answer. I solved the problem

**Comment by abidlabs** [comment]
Thanks for providing the solution @blre6!
