### ISSUE TITLE
Best way to protect private files from being accessed by `http://localhost:port/file=/path/to/file.txt` ?

### ISSUE THREAD

**Issue by binary-husky** [gradio-app/gradio#3939]
If there are sensitive scripts/data under gradio project that I want to forbid access from browser (and any other possible method), 
e.g. a txt file under the project folder, what is the best way prevent such access?

![image](https://user-images.githubusercontent.com/96192199/233781427-5107b6e3-1cc3-4993-b109-4586c79bf262.png)

I have tried to search issues but have not find anything related (maybe I not using the right words to search them)

**Comment by abidlabs** [comment]
Hi @binary-husky currently it is not possible blacklist files, but this is certainly something we can consider adding.
