### ISSUE TITLE
Nginx Reverse Proxy Configuration for Transmitting Image Data with Gradio

### ISSUE THREAD

**Issue by xaswq** [gradio-app/gradio#3941]
### Describe the bug

Hello Gradio team,

I am trying to set up a Gradio application behind an Nginx reverse proxy. The application is running locally on port 1234, and I have successfully configured Nginx to proxy requests to this port. However, I am encountering an issue when trying to transmit image data through the reverse proxy. The error message I receive is:

`Something went wrong
Unexpected token '<', "<html> <h"... is not valid JSON
`

![image](https://user-images.githubusercontent.com/85377380/233796373-9d594732-03a0-49b3-90f1-1bbfac9b5963.png)

Here's my Nginx configuration for the reverse proxy:

```
location / {
    proxy_pass http://localhost:1234;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_cache_bypass $http_upgrade;
    proxy_read_timeout 86400;
    proxy_redirect off;

    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
    add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
    add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
}


```

I have also added the --server_name "test.docscanner.top" option to my Gradio app's launch configuration.

The Gradio app works fine when accessed directly on port 1234, but the error occurs when trying to access it through the Nginx reverse proxy.

Could you please provide some guidance on how to properly configure Gradio and Nginx to support transmitting image data through a reverse proxy? Any assistance would be greatly appreciated.

Thank you!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

http://test.docscanner.top/

### Screenshot

![image](https://user-images.githubusercontent.com/85377380/233796500-e3033a8d-6d45-4f50-9e90-40db923d6a61.png)

### Logs

```shell
`Something went wrong
Unexpected token '<', "<html> <h"... is not valid JSON
`
```

### System Info

```shell
>>> gradio.__version__
'3.27.0'
```

### Severity

blocking all usage of gradio

**Comment by xaswq** [comment]
Issue resolved - it was likely caused by browser cache.

**Comment by abidlabs** [comment]
Cool thanks for letting us know!

**Comment by xaswq** [comment]
Hey everyone, I just wanted to share a solution I found for an issue I encountered while using Nginx as a reverse proxy. By default, the configuration limits the file upload size to 1MB. To resolve this issue, simply modify the "client_max_body_size" parameter to your desired value. I hope this helps anyone else who might be facing a similar problem. Cheers!
