### ISSUE TITLE
Build error in vite

### ISSUE THREAD

**Issue by meerfrau** [gradio-app/gradio#3946]
### Describe the bug

I'm trying to build gradio under ArchLinux with [this recipe](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-gradio), but adapted to git master. Unluckily the builds fails with both [vite](https://github.com/vitejs/vite)-4.2.1 and 4.3.1:

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`sh ./scripts/build_frontend.sh`

### Logs

```shell
> @gradio/client@0.0.1 bundle ./gradio/client/js
> vite build --ssr

failed to load config from ./gradio/client/js/vite.config.js
error during build:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite' imported from ./gradio/client/js/vite.config.js.timestamp-1682266128970.mjs
Did you mean to import vite/index.cjs?
```
```


### System Info

```shell
git master, Linux
```

### Severity

annoying

**Comment by abidlabs** [comment]
Closing as there is no repro. Feel free to reopen if there is a simple repro.

**Comment by meerfrau** [comment]
` sed -i "s/frozen/no-frozen/g" ./scripts/build_frontend.sh` fixed the issue

**Comment by abidlabs** [comment]
Thanks @meerfrau for reporting the fix!
