### ISSUE TITLE
Change the default behavior to block https requests to Gradio API

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#3947]
With the release of the Python and JS clients, which are the preferred way to connect to Gradio apps (as they respect the queue), we should change the default behavior of Gradio apps to block requests via https (which do not respect the queue).

[As discussed internally](https://huggingface.slack.com/archives/C02QZLG8GMN/p1682289623198869?thread_ts=1682241813.575959&cid=C02QZLG8GMN), we should make this change in 4.0.

**Comment by freddyaboulton** [comment]
To make sure I understand, this is only to `/api/predict` correct?

So this can be closed if we set `api_open=False` by default?

**Comment by ToviHe** [comment]
> > So this can be closed if we set api_open=False by default?
> 
> Yup!

Hello, I would like to ask, is the function of view=api enabled by default in gradio? I found out that I'm on 127.0.0.1:7860? view=api opens the api documentation. Can I set show_api = false if I don't want to enable this feature?

**Comment by abidlabs** [comment]
Closed in `v4` branch!
