### ISSUE TITLE
Always hosted on public URL

### ISSUE THREAD

**Issue by mr-wombat** [gradio-app/gradio#395]
Hello,

I am currently trying to implement my first UI with gradio, and it seems like I can not get it to work on localhost.

 My code is rather trivial:

```python
iface = gr.Interface(
    predict_parameters,
    inputs=[
        gr.inputs.Number(label="A [µm; tol=0.01]", default=60.0),
        gr.inputs.Slider(0, 200, step=10, default=0, label="B [°C]"),
        # ...
    ],
    outputs=gr.outputs.Dataframe(),
    title="Title",
    description="...",
    allow_flagging=False,
    analytics_enabled=False
)
iface.launch(share=False)
```
This code is in a file main.py (no main function or anything)

When I run this code, I get:
```
python3 main.py 
Running on public URL: https://[...].gradio.app

This share link will expire in 72 hours. To get longer links, send an email to: support@gradio.app
```

In fact, I can reach the UI on `http://localhost:7860/` but it is very important to me that the UI is _not_ shared. Is there any setting I am missing, or is the `share` option in the `launch` ignored? 

**Version**: gradio 2.4.6
**Minimal example**: The same output is produced when running the first code in the [quick start guide](https://github.com/gradio-app/gradio#quick-start)   

Thanks!

**Comment by abidlabs** [comment]
Hi @mr-wombat, thanks for opening this issue! Where are you running this code? Is this running on a server where the localhost is not accessible? In which case, `gradio` by default creates a public link

**Comment by mr-wombat** [comment]
Hi, thanks for looking into this. I run it on my local machine in a python script (no jupyter etc.)
I assume localhost is accessible if I can access the website through the localhost url? 
Is there any debug output I can provide?

**Comment by abidlabs** [comment]
Hi @mr-wombat I'm looking into this issue (sorry for the delay!). Can you do me a favor and run the basic quick-start script: 

```python
import gradio as gr

def greet(name):
  return "Hello " + name + "!!"

iface = gr.Interface(fn=greet, inputs="text", outputs="text")
iface.launch()
```

Does this also cause a public link to be created?

**Comment by abidlabs** [comment]
Can you please tell me what happens when you run the following code? 

```python
import requests
r = requests.head("http://127.0.0.1:7860/")
print(r.status_code)
```

Instead of `7860`, you may need to put the port that shows up where the gradio app is running locally

**Comment by mr-wombat** [comment]
Sorry, I did not get a notification about your last comment. 

I ran the code after I started the gradio app (running on 7860). The returning status code is: **503**

**Comment by abidlabs** [comment]
@mr-wombat we are rewriting the backend of Gradio completely using Starlette/FastAPI (see #440) and will release it this week. Perhaps this will fix your issue -- otherwise, perhaps we can get on a quick debugging call together.

**Comment by abidlabs** [comment]
Hi @mr-wombat can you try again with the latest version of Gradio, which uses Starlette/FastAPI and see if you still observe the issue?

**Comment by abidlabs** [comment]
Will close for now since I cannot reproduce this. If you're still seeing this issue, please feel free to reopen and would love to solve this. Perhaps we can get on a quick zoom call to debug together.

**Comment by qzhkbgjpyx-byte** [comment]
python noguchi_resonance_mobile.py
