### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by guochaoqun** [gradio-app/gradio#3954]
I want to modify the name of the submit button in the interface, for example, change "submit" to "go". I have searched through documents and various resources but have not found how to do it. Is it possible to achieve this? If not, is there any interface that can provide this function?

**Comment by abidlabs** [comment]
Hi @guochaoqun, for general questions like this (that are not feature requests or bug reports), please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
