### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by jaekookang** [gradio-app/gradio#396]
Hi, I was wondering if I can specify a custom SSL certificate file to my Gradio app as in the regular Flask app so that I can use my own domain with https. Is it possible to do so in the Gradio app?

**Comment by abidlabs** [comment]
Hmm if you are deploying a web application with a "real certificate" you would probably obtain the certificate and set it via nginx to the port where the gradio app is running. You shouldn't need to make any changes to the flask application, right? 

E.g. the steps listed here: https://blog.miguelgrinberg.com/post/running-your-flask-application-over-https

**Comment by jaekookang** [comment]
I'm not an expert on building web applications, but previously I've added SSL certificate files as a part of the Flask app such as below when I needed microphone access:
```python
app = Flask(__name__)

# ---- SSL (due to microphone access)
import ssl
context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER) 
context.load_cert_chain('ssl_cert/certificate.crt', 'ssl_cert/private.key')

# ...

if __name__ == '__main__':
    app.run(ssl_context=context)
```

I haven't tried setting the certificate via nginx to the port where the gradio app is running. I will try this method following the link that you attached.

Thank you

**Comment by abidlabs** [comment]
Sounds good, thanks for following up. Please let us know if you run into any issues.

**Comment by Chiragkathuria** [comment]
Hi Abid , I tried setting up gradio with gunicorn but its not working fine . 
As gradio get start on next port to binded one in unicorn
![Screenshot 2021-12-08 at 7 07 10 PM](https://user-images.githubusercontent.com/26459463/1
![Screenshot 2021-12-08 at 7 08 19 PM](https://user-images.githubusercontent.com/26459463/145217826-2c8f7920-f851-44c0-9637-5d48d2de876b.png)
45217655-a7031863-0302-45f9-9d97-b33c3febeae9.png)
 command, gradio is not coming up with binding port.
Please help , just look on screenshots as I shared , As gunicorn is binding on 8443 but gradio which is configured for 8443 start itself at 8444 so pls help on this ..

**Comment by Chiragkathuria** [comment]
Also my gradio instance is taking almost around 8 minute to start web instance , can u pls help me how to resolve that too ?

Thanks

**Comment by abidlabs** [comment]
Does this address your issue @Chiragkathuria? https://abidlabs.medium.com/quickly-deploying-gradio-on-aws-242af2374784
