### ISSUE TITLE
Can't get return when using distributed model inference

### ISSUE THREAD

**Issue by edwardelric1202** [gradio-app/gradio#3964]
### Describe the bug

Hi, when I tried to wrap a distributed llm inference demo with gradio, it occurred this problem.
My **generate** function receives a text input, and operate distributed inference on 4 gpus, finally return the generated text by llm. It works well when test, but as I tried to wrap it with gradio like below, the function just not give correct return and blocked:
iface = gr.Interface(
    fn=**generate**,
    inputs=gr.Textbox(lines=5, label="Input Text"),
    outputs=gr.Textbox(lines=5, label="Generated Text"),
    title="LLM",
    description="Type your text with [gMASK] to fill in the blanks!",
)
if torch.distributed.get_rank() == 0:
     iface.launch(share=True, debug=True, server_name='0.0.0.0', server_port=8000)

I used torch.distributed to make distributed inference. How to solve this problem?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

maybe a common question for distributed inference

### Logs

```shell
no logs
```

### System Info

```shell
gradio 3.27.0
torch 1.13.0+cu117
```

### Severity

annoying

**Comment by Emanuele97x** [comment]
following

**Comment by abidlabs** [comment]
To be honest, I don't follow the issue. Can you provide a correctly formatted, minimal code example? Along with the expected output vs. what you are seeing?

**Comment by Emanuele97x** [comment]
I think the more general question is, how gradio should be used with model parallel/distributed processing? I didn't find any clarification on this on the docs. It is not clear if it's supported, or there are workarounds to make it work

**Comment by abidlabs** [comment]
Hi @Emanuele97x can you provide a concrete example of what you mean with model parallelism / distributed processing? Generally, `gradio` should work fine as long as there is a single function that you are running, even if internally the function distributes its inference over multiple inferences and gathers the result?

**Comment by abidlabs** [comment]
Will close for now, but down to reopen with a full code example.

**Comment by Emanuele97x** [comment]
Solved, thanks a lot! Basically I needed to run two jobs, one for hosting the model and generation with MP and the other one for hosting the demo. I don't know if it can be done in a single script where the demo is hosted only on rank 0. But I found this workaround easier!

**Comment by abidlabs** [comment]
Ok great to hear thanks
