### ISSUE TITLE
Add video input length cropping feature

### ISSUE THREAD

**Issue by fffiloni** [gradio-app/gradio#3969]
✅ I have searched to see if a similar issue already exists.

add the `gradio.Audio()` component feature that allows to crop the file duration (in & out) to the `gradio.Video()` component too
plus the possibility to set a maximum length value allowed for the cropped area

![image_d___ios](https://user-images.githubusercontent.com/7447007/234309050-acd075b1-06ae-4e19-a585-8a27613a3aeb.jpeg)

**Additional context**  
we have a lot of demos involving video input already, and i guess more coming soon
people often abuse by dropping large videos and occupy the queue for too long
with this feature we could easily set limits, and allow user to choose wich part of the video they want to use in inference

**Comment by abidlabs** [comment]
Nice. Related: #428, though not the same as here the request for a UI to select regions of the video as well

**Comment by pngwn** [comment]
We should go for a UX similar to this (same for audio):

![vidtrim](https://user-images.githubusercontent.com/12937446/236469254-14b98fe7-3ac1-4791-99e5-98f2c0584f10.png)

**Comment by henryruhs** [comment]
Having a `gradio.RangeSlider()` does indeed make more sense to me as most people display frame by frame in their custom preview anyway.

![grafik](https://github.com/gradio-app/gradio/assets/1835397/e7cc056f-d4b8-4f82-98ac-ee970086ecc0)

We at roop are currently using 3 Sliders... not ideal
