### ISSUE TITLE
Font visibility changes across different devices and looks  "off"

### ISSUE THREAD

**Issue by cowanAI** [gradio-app/gradio#3974]
### Describe the bug

Font visibility changes across different devices and looks turned off.

Users report is hard to read, is there any documentation to have a consistent user experience?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

ui = gr.Interface(
    fn=transcribe, 
    theme='gradio/soft',
    inputs=[
        gr.Audio(source="microphone", type="filepath", label="Upload audio"),
        gr.Textbox(label="Or chat here:"),
        
    ],
    outputs=gr.Textbox(label="Alicja AI:"),
    title="Introducing Alicja AI: World's First AI-Powered Nurse",
    description="Transcribe, Summarize and fill out any medical PDF document instantly",
    #allow_flagging=('never'),
    examples=[    ["Medical_Transcriber.mp3", "Medical transcriber: Alicja, please summarize the patient visit and auto-fill the “X” form."],
    ["Medical_Writing.mp3", "Medical writing: Hey Alicja, can you help me organize my thoughts for this research paper?"],
    ["Clinical_Trials.mp3", "Clinical trials: Alicja, what is the recommended sample size for this clinical trial and can you help me analyze the results?"],
    ["Language_Translation.mp3", "Language translation: Alicja, can you help me translate what this patient is saying into English?"],
    ["Medical_Research.mp3", "Medical research: Hey Alicja, can you help me find some relevant literature for this research question?"],
    ["Patient_Education.mp3", "Patient education: Alicja, can you explain this medical condition to my patient in simple terms?"],
],
    css="footer {visibility: hidden}",
    allow_flagging=('never'),
)

ui.queue(concurrency_count=2)
app = gr.mount_gradio_app(app, ui, path=CUSTOM_PATH)

### Screenshot

![PHOTO-2023-04-25-22-24-20](https://user-images.githubusercontent.com/128092052/234396401-4c44c394-391c-497c-87bb-fa46a65038e8.jpg)
<img width="680" alt="Screenshot 2023-04-25 at 10 24 17 PM" src="https://user-images.githubusercontent.com/128092052/234396418-2b343a2f-1736-49db-9e24-85bb08bffbd8.png">

### Logs

```shell
no errors, just cosmetic that makes text visibility hard to read.
```

### System Info

```shell
latest
```

### Severity

annoying

**Comment by cowanAI** [comment]
Also, same issue occurs in Safari regardless of the device, this issue does not occur in Google Chrome Desktop, it seems like an Apple related issue.

**Comment by cowanAI** [comment]
@abidlabs same in the public gradio website, here is barely noticeable but in dark mode my users complained about it 
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/128092052/234825634-6d76ed16-cba9-4e7a-a8d3-351aa39040ee.png">

**Comment by abidlabs** [comment]
Sorry just to understand the issue better, you're saying the font color is off for Gradio apps using the Safari browser? It's not clear to me from the screenshot you posted. Is it just the output textbox font color?

**Comment by cowanAI** [comment]
Yes @abidlabs , the output text is turned off and also the buttons but it only happens in safari, also the clipboard option doesnt work in google chrome but I think that's a current bug in google chrome, the clipboard works fine in safari though. Unfortunately this is critical only in dark mode themes like mine.
![IMG_3340](https://user-images.githubusercontent.com/128092052/234993760-1e423df6-e70f-469d-9b7e-492145a28778.PNG)

**Comment by abidlabs** [comment]
Ok yeah I can reproduce this actually on my iPhone, cc @aliabid94

**Comment by cowanAI** [comment]
Thanks again for helping on this
