### ISSUE TITLE
only support ip/domain access;  can't be accessed with any path appended

### ISSUE THREAD

**Issue by fredhu21** [gradio-app/gradio#3977]
### Describe the bug

Hi, the latest gradio version(3.27.0) assumed that users deploy and access it via domain.
say http://mydomain.com

But if we have a L7 LB and route my path to the realserver,  say http://mydomain.com/gradio it won't work.

because 

1. the frontend javascript code hardcoded fetch mydomain.com/theme.css, other than mydomain.com/gradio/theme.css
2. the frontend js code hardcoded post mydomain.com/run/predict, other than mydomain.com/gradio/run/predict

when downgrade to gradio-3.10.0, the above two problems solved automatedly.
So, I am sure that's a bug.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

deploy gradio, and use an nginx LB forward any path (other than '/')  to the real gradio server

say http://mydoamin.com/gradio

### Logs

```shell
that 's totaly frontend js bug, the backend service is all right.
```

### System Info

```shell
3.27.0
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @fredhu21 thanks for creating this issue. We have an existing issue #3472, please chime into that issue and we'll work on resolving this soon. Thanks!
