### ISSUE TITLE
[Feature request] Max audio/video file size

### ISSUE THREAD

**Issue by sanchit-gandhi** [gradio-app/gradio#3988]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Usually we want to limit the max size of audio/video files in gradio applications to keep the queue fair (i.e. we don't want one user to use all the resources by transcribing 1000 hours worth of audio!). Currently, the easiest way of doing this is by checking the file size of the uploaded audio in the app function, and erroring out if it's too large (e.g. [app.py#L131-L136](https://github.com/sanchit-gandhi/whisper-jax/blob/7159222d7ec994153a527f0220cd58ea8f4c7546/app/app.py#L131-L136)).

However, super long audio/video files can flood the `/tmp` directory. It would be great if there was a max filesize on the `gr.Inputs` class so that we could limit the upload of super large files.

**Describe the solution you'd like**  
An argument `max_filesize` in the Audio/Video inputs components that defaults to `None` (no limit) but is configurable.

**Comment by abidlabs** [comment]
Thanks @sanchit-gandhi yes makes sense. I think this we'll add this via a combination of #3801 and #3779. Will close this issue, but feel free to reopen in case I'm missing something.
