### ISSUE TITLE
Gradio doesn't automatically create a shareable link in sagemaker

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#399]
The `url_ok()` method needs some work since there are a bunch of open issues about it and it doesn't create a shareable link in Sagemaker notebooks:

![image](https://user-images.githubusercontent.com/1778297/145524558-ea3d4389-9ec5-4772-bec2-833ed01377df.png)

**Comment by cri5Castro** [comment]
Hello I replicated this error today in gradio version 3.1.2
inline doesn't work and also the shareable link 
<img width="983" alt="Captura de Pantalla 2022-08-01 a la(s) 22 16 47" src="https://user-images.githubusercontent.com/11454650/182284468-59f8f80d-32b1-439d-971d-12c83311cfe6.png">
<img width="1007" alt="Captura de Pantalla 2022-08-01 a la(s) 22 17 19" src="https://user-images.githubusercontent.com/11454650/182284473-0ae5d9bc-11df-4387-b483-beebd3bca604.png">

**Comment by hamkasatria** [comment]
hello. I get same error today. gradio cant share links in gradio version 3.15.0

![image](https://user-images.githubusercontent.com/48576063/210221393-65dab1ff-158d-42dc-8c36-6499df1f7194.png)
