### ISSUE TITLE
The UI of the web page does not display properly

### ISSUE THREAD

**Issue by WheatJH** [gradio-app/gradio#3997]
### Describe the bug

When i launch MiniGPT-4 in Linux, the web ui does not display properly, but i found that the web ui can display properly on my local computer. And when i click the submit button, it get wrong that 【Unexpected end of JSON input】
The version of gradio is 3.23.0. The server network environment is limited to the company's intranet.
How can i fix this problem?
the following photo is i test the hello program

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr
  
def greet(name):
    return "Hello " + name + "!"

if __name__ == "__main__":
    demo = gr.Interface(fn=greet, inputs="text", outputs="text")

    demo.launch(server_name="0.0.0.0", server_port=7860)

### Screenshot

![image](https://user-images.githubusercontent.com/37017099/235030336-c08c1780-c6b9-499e-bd3f-d1442cb1b41e.png)

### Logs

```shell
no log
```

### System Info

```shell
Linux, gradio==3.23.0
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @WheatJH we don't get this issue when running on Linux in general. Can you try upgrading to the latest version of Gradio and seeing if the issue persists?

**Comment by WheatJH** [comment]
ok, i will try it, but the same hello code, i can display properly when gradio is 3.16.2

**Comment by WheatJH** [comment]
> Hi @WheatJH we don't get this issue when running on Linux in general. Can you try upgrading to the latest version of Gradio and seeing if the issue persists?

i upgrade the gradio to 3.28.0, now the web is only show Loading. This issue also occurred when I was using the version of Gradio is 3.24.1
![image](https://user-images.githubusercontent.com/37017099/235034823-efc3b38e-0685-42cc-9498-d0d01feb2613.png)

**Comment by abidlabs** [comment]
Hi @WheatJH is there any way you can provide us a code example that we can run in a reproducible environment, such as a Colab notebook?

**Comment by abidlabs** [comment]
Closing for lack of followup, but feel free to reopen if you are able to provide us a simple repro
