### ISSUE TITLE
Audio output does not show in a screenshot

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#400]
I get proper output in the demo, but when clicking screenshot the image I get shows empty output field.

Example from https://huggingface.co/spaces/akhaliq/ESPnet2-TTS
![screenshot (3)](https://user-images.githubusercontent.com/7246357/145596647-1514ecaf-476b-42f8-bd78-5bd96044d191.png)

**Comment by osanseviero** [comment]
FYI similar thing happens with the inputs (see https://huggingface.co/spaces/microsoft/unispeech-speaker-verification)

**Comment by abidlabs** [comment]
Closing as we have just eliminated the screenshot button in the latest version of Gradio on `master`. We'll be releasing to pypi next week.
