### ISSUE TITLE
Allow `gr.Chatbot` to fill all height of rest of space

### ISSUE THREAD

**Issue by liaoweiguo** [gradio-app/gradio#4001]
- [ * ] I have searched to see if a similar issue already exists.

I can use
`chatbot = gr.Chatbot(elem_id="chatbot").style(height=600)`

but it can not adapt to diff screen size

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by dawoodkhan82** [comment]
If you remove setting a specific height, it will dynamically resize the chatbot to fit screen sizes. Try `chatbot = gr.Chatbot(elem_id="chatbot")` without adding style

**Comment by liaoweiguo** [comment]
> If you remove setting a specific height, it will dynamically resize the chatbot to fit screen sizes. Try `chatbot = gr.Chatbot(elem_id="chatbot")` without adding style


I donot thing so. There is a gap between components and footer

like this
![截图 2023-04-28 18-28-55](https://user-images.githubusercontent.com/22187224/235124271-b012c539-daaf-4ec8-b481-04cf560c4a6e.png)

**Comment by abidlabs** [comment]
I get the same behavior as @liaoweiguo -- it looks like there's a fixed height even if no height is specified @dawoodkhan82

**Comment by liaoweiguo** [comment]
any hints?

**Comment by dawoodkhan82** [comment]
@bent-verbiage @liaoweiguo can you check if this pr fixes your issue? #4041

**Comment by aliabid94** [comment]
We currently do not support a concept of an element taking up the "remaining vertical space". Can you explain the scenario where this is helpful?

Your best bet would be using custom CSS. For example
```python
CSS ="""
.contain { display: flex; flex-direction: column; }
#component-0 { height: 100%; }
#chatbot { flex-grow: 1; }
"""

with gr.Blocks(css=CSS) as demo:
    chatbot = gr.Chatbot(elem_id="chatbot")
    msg = gr.Textbox()
    clear = gr.Button("Clear")
```
allows the chatbot to expand to fill the "remaining vertical space", though it may expand if there are more messages.

**Comment by joedavis** [comment]
> We currently do not support a concept of an element taking up the "remaining vertical space". Can you explain the scenario where this is helpful?

How about accessibility? When the chatbot window grows, other elements can end up moving around, until eventually it settles at a fixed size taking up most of the screen anyway.

It's possible to minimize this motion by setting a fixed large size for the chatbot window, but obviously that doesn't take into account different screen sizes.

There's a reason that most desktop and mobile OSes have options to reduce motion.

**Comment by jsjolund** [comment]
@aliabid94: Thanks for the code.

I modified your CSS to make the ChatBot demo with buttons automatically fill the height of the viewport:

```python
CSS ="""
.contain { display: flex; flex-direction: column; }
.gradio-container { height: 100vh !important; }
#component-0 { height: 100%; }
#chatbot { flex-grow: 1; overflow: auto;}
"""

with gr.Blocks(css=CSS) as demo:
    chatbot = gr.Chatbot(elem_id="chatbot")
    msg = gr.Textbox()
    clear = gr.Button("Clear")
```

You can still scroll through the conversation like with the fixed size chat window.

**Comment by abidlabs** [comment]
Thanks @jsjolund and @aliabid94. Since we don't have the concept of letting components take up the full vertical space in `gradio`, we will defer to the CSS solutions provided here as a workaround.

**Comment by Chrosea** [comment]
> @aliabid94: Thanks for the code.
> 
> I modified your CSS to make the ChatBot demo with buttons automatically fill the height of the viewport:
> 
> ```python
> CSS ="""
> .contain { display: flex; flex-direction: column; }
> .gradio-container { height: 100vh !important; }
> #component-0 { height: 100%; }
> #chatbot { flex-grow: 1; overflow: auto;}
> """
> 
> with gr.Blocks(css=CSS) as demo:
>     chatbot = gr.Chatbot(elem_id="chatbot")
>     msg = gr.Textbox()
>     clear = gr.Button("Clear")
> ```
> 
> You can still scroll through the conversation like with the fixed size chat window.

```.gradio-container { height: 100vh !important; }``` will lock the size at 100vh with no scroll bar, when the control panels expand over 100vh, the chat message will no longer appear.  Maybe remove this line?

**Comment by abidlabs** [comment]
We decided to offer a built-in solution for this. PR here: https://github.com/gradio-app/gradio/pull/7278

**Comment by GuokaiLiu** [comment]
Thanks for the above code. I tried to use `gr.Tabs` and `gr.Tab` with `gr.Chatbot`, the second code failed to fill all the height of the rest of the space. How to deal with it? Many thanks.


```python
import gradio as gr

CSS = """
.contain { display: flex; flex-direction: column; }
.gradio-container { height: 100vh !important; }
#component-0 { height: 100%; }
#chatbot { flex-grow: 1; overflow: auto;}
"""

with gr.Blocks(css=CSS) as demo:
    with gr.Tabs():
        with gr.Tab('abc'):
            chatbot = gr.Chatbot(elem_id="chatbot")
            msg = gr.Textbox()
            clear = gr.Button("Clear")

demo.launch(inbrowser=True)
```

![image](https://github.com/user-attachments/assets/d95aa116-fb7b-4b1e-8e40-f256fe605784)


```python
import gradio as gr

CSS = """
.contain { display: flex; flex-direction: column; }
.gradio-container { height: 100vh !important; }
#component-0 { height: 100%; }
#chatbot { flex-grow: 1; overflow: auto;}
"""

with gr.Blocks(css=CSS) as demo:
    chatbot = gr.Chatbot(elem_id="chatbot")
    msg = gr.Textbox()
    clear = gr.Button("Clear")

demo.launch(inbrowser=True)
```

![image](https://github.com/user-attachments/assets/21fb85b5-e214-4d78-b858-db91a2a0d661)

**Comment by anton-b** [comment]
Since adding additional css didn't help, followed the comment in the chatbot code:
```
height: The height of the component, specified in pixels if a number is passed, or in CSS units if a string is passed. If messages exceed the height, the component will scroll.
            
```  
```
    with gr.Blocks() as cb:
        chatbot = gr.Chatbot(type="messages",
                             label="LoanerAI",
                             height="85vh",
                             # scale=1,
                             elem_id="chatbot",
                             autoscroll=True)
```

**Comment by jgbeta** [comment]
> Since adding additional css didn't help, followed the comment in the chatbot code:
> 
> ```
> height: The height of the component, specified in pixels if a number is passed, or in CSS units if a string is passed. If messages exceed the height, the component will scroll.
>             
> ```
> 
> ```
>     with gr.Blocks() as cb:
>         chatbot = gr.Chatbot(type="messages",
>                              label="LoanerAI",
>                              height="85vh",
>                              # scale=1,
>                              elem_id="chatbot",
>                              autoscroll=True)
> ```

This did the trick for me!
Thanks.
