### ISSUE TITLE
the outputs could be string with URL ? 

### ISSUE THREAD

**Issue by ucas010** [gradio-app/gradio#4006]
- I have searched to see if a similar issue already exists.
the outputs are strings, and it can be clicked then link to the web,
such as the down

[just an example](just.an.example)

could you please help me ?

**Comment by freddyaboulton** [comment]
Hi @ucas010 ! 

Yes, should be possible with either a gr.Markdown() or gr.HTML() component!

Here is an example with markdown

```python
import gradio as gr

with gr.Blocks() as demo:
    link = gr.Markdown()
    but = gr.Button(value="Get Link")
    but.click(lambda: "[click me](https://github.com/gradio-app/gradio)", 
              inputs=None, outputs=link)

demo.launch()
```

Going to close since this doesn't appear to be a bug report or feature request!
