### ISSUE TITLE
Code component not showing properly

### ISSUE THREAD

**Issue by taoisu** [gradio-app/gradio#4008]
### Describe the bug

I'm using gradio 3.28.0, simply having a code component in my app I observed this:

![image](https://user-images.githubusercontent.com/30015018/235221414-1df23f0f-d4fa-439b-80d2-f7633153f0b1.png)

I'm wondering if this is a bug (seem to be) or did I mis-configured the component.

Here's my code:
```python
                with gr.Row():
                    with gr.Column():
                        code_target = gr.Dropdown(
                            choices=["Fott"],
                            info="Convert to which format",
                            value="",
                            interactive=True,
                            label="Convert to",
                        )
                    with gr.Column():
                        cvt_target = gr.Dropdown(
                            choices=["Fott"],
                            info="Convert to which format",
                            value="Fott",
                            interactive=True,
                            label="Convert to",
                        )
                        cvt_code = gr.Code(
                            language="python",
                            label="Conversion Code",
                            lines=12,
                            interactive=True,
                        )
                        cvt_button = gr.Button("Convert")
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use the code above.

### Screenshot

![image](https://user-images.githubusercontent.com/30015018/235221501-0fdea636-28d8-4041-88a0-ebb4c9a44c68.png)

### Logs

```shell
This is a UI issue, no stacktraces.
```

### System Info

```shell
3.28.0

Ubuntu 18.04
```

### Severity

annoying

**Comment by taoisu** [comment]
By bug I mean this part:

![image](https://user-images.githubusercontent.com/30015018/235221695-358aa55b-812c-4744-ad3e-13fe54cc139b.png)

**Comment by abidlabs** [comment]
Definitely looks like a UI bug, thanks for reporting @taoisu!
