### ISSUE TITLE
AWS Sagemaker | Create chatbot demo with out public URL

### ISSUE THREAD

**Issue by Rajesh4AI** [gradio-app/gradio#4013]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by abidlabs** [comment]
Hi @Rajesh4AI unfortunately, it's not possible to create any Gradio demo on hosted Sagemaker notebooks as they are not running locally. So even if you set `share=False`, the localhost server on Sagemaker will not be accessible to you locally. That's why creating a share link is necessary.
