### ISSUE TITLE
`AnnotatedImage` component doesn't display small images correctly

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#4014]
### Describe the bug

I was recently trying to use the `AnnotatedImage` component, and I found that it doesn't render images of certain sizes correctly. For example, if I try with a 128 x 128 image, here is the result:

<img width="971" alt="image" src="https://user-images.githubusercontent.com/1778297/235286582-e877d9f4-1e08-4cea-bd40-ca1d77c69f05.png">

If I try with a 256 x 256 image, here is the result:

<img width="981" alt="image" src="https://user-images.githubusercontent.com/1778297/235286603-33a47199-2682-48f7-b53d-f9d300aeff5b.png">

In my case, if the images are above 600px by 600px (I haven't found the exact threshold), they seem to show up fine:

<img width="979" alt="image" src="https://user-images.githubusercontent.com/1778297/235286650-5e9b8e2c-61a8-4a1a-bff8-0162d944f2cd.png">

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Easiest way to reproduce is to set the shape of the input image, like this:

```py
import gradio as gr

img = gr.Image(shape=(128, 128))
img_section = gr.AnnotatedImage()


def mask(img_):
    top_left_corner = [0, 0, 20, 20]
    random_mask = np.random.randint(0, 2, img_.shape[:2])
    return (img_, [(top_left_corner, "left corner"), (random_mask, "random")])

interface = gr.Interface(mask, img, img_section)

interface.launch(debug=True)
```

### Logs

```shell
N/A
```

### System Info

```shell
gradio==3.28.1
```

### Severity

serious, but I can work around it

**Comment by seokhee516** [comment]
The issue does not occur in 3.27.0 version

**Comment by JohnPPinto** [comment]
I have faced the same issue when my images are of a small size, this issue is still present in the latest version 3.29.0. 
If you want to solve this issue you can use the ```gradio.AnnotatedImage.style(···)```,  add the height and width of the training size you used for training the model, and for color_map an empty dict works fine eg. {"": ""}.

**Comment by abidlabs** [comment]
Strange, I can't seem to reproduce this anymore. Here's what I ran:

```py
import gradio as gr
import numpy as np

img = gr.Image(shape=(64, 64))
img_section = gr.AnnotatedImage()


def mask(img_):
    top_left_corner = [0, 0, 20, 20]
    random_mask = np.random.randint(0, 2, img_.shape[:2])
    return (img_, [(top_left_corner, "left corner"), (random_mask, "random")])

interface = gr.Interface(mask, img, img_section)

interface.launch()
```

Even with a 64x64 image, I get expected outputs:

<img width="771" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/b14b4a12-29c8-4a25-8fa7-bdaa81cc782c">
