### ISSUE TITLE
Mobile text box color is different & unvisible

### ISSUE THREAD

**Issue by edchengg** [gradio-app/gradio#4017]
### Describe the bug

I tried to set the color of text box on mobile to white and background to gray. It looks ok on laptop and different color appears on my phone.

The text color is not visible when user using a phone.

My current workaround is just to set the background color into black. But you can see the color differences between input and output text box.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Check space at https://huggingface.co/spaces/ychenNLP/just4fun

Copy paste this youtube link to the box and click submit:
https://youtube.com/shorts/xPuIpiOSRLA?feature=share

### Screenshot

![Image from iOS](https://user-images.githubusercontent.com/20430102/235327061-428b84ed-fc64-4032-90d8-2efee615436e.png)

### Logs

```shell
No log
```

### System Info

```shell
No need
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Hi @edchengg i believe we just fixed this issue. Can you try upgrading the Space (using the README file) to 3.28.1?

**Comment by edchengg** [comment]
Perfect! this works. Thanks a lot.
