### ISSUE TITLE
Bug: uploaded the pdf file but the temporarily file is empty when file_counter is 'multiple'

### ISSUE THREAD

**Issue by luojunhui1** [gradio-app/gradio#4019]
### Describe the bug

i tried to use `UploadButton` to upload pdf file and use `PyMuPDF` to analyze it, but it seems it didn't work when i upload the pdf file. i have tried to change the parameter `file_types` from `file` to `.pdf`(reference #3729) but it didn't work, when i changed the `file_counter` from `mutilple` to `single`, it worked well

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr
import fitz

def run_file(files):
    
    for file in files:
        print(f"{file.name}")
        file_suffix = file.name.split('.')[-1]
        file_dir = None

        if str(file_suffix).lower() == "pdf":
            print(f"pdf : {file.name}")
            doc = fitz.open(file.name)
            print(doc.page_count)

if __name__ == "__main__":
    with gr.Blocks(mode="demo") as demo:
        btn = gr.UploadButton("📁", file_types=[".pdf"],  file_count="multiple")
    
        btn.upload(run_file, [btn], [], show_progress = True)  
    demo.queue().launch(debug=True)

### Screenshot

![image](https://user-images.githubusercontent.com/41661108/235357440-f22bbbc7-292a-4f86-8bf1-07bb9c3112df.png)

### Logs

```shell
(Innovation) D:\Code\Project\AutoSolutionDoc>python test.py
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
C:\Users\LUOJUN~1\AppData\Local\Temp\input_doc8p1to8xa.pdf
pdf : C:\Users\LUOJUN~1\AppData\Local\Temp\input_doc8p1to8xa.pdf
Traceback (most recent call last):
  File "D:\software\miniconda\envs\Innovation\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\software\miniconda\envs\Innovation\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\software\miniconda\envs\Innovation\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\software\miniconda\envs\Innovation\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\software\miniconda\envs\Innovation\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\software\miniconda\envs\Innovation\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Code\Project\AutoSolutionDoc\test.py", line 13, in run_file
    doc = fitz.open(file.name)
  File "D:\software\miniconda\envs\Innovation\lib\site-packages\fitz\fitz.py", line 3959, in __init__
    raise EmptyFileError(msg)
fitz.fitz.EmptyFileError: cannot open empty document
```

### System Info

```shell
3.23.0, windows10, Microsoft Edge 112.0.1722.64
```

### Severity

serious, but I can work around it

**Comment by luojunhui1** [comment]
`import gradio as gr
import fitz

def run_file(files):
    for file in files:
        print(f"{file.name}")
        file_suffix = file.name.split('.')[-1]
        if str(file_suffix).lower() == "pdf":
            print(f"pdf : {file.name}")
            doc = fitz.open(file.name)
            print(doc.page_count)

if __name__ == "__main__":
    with gr.Blocks(mode="demo") as demo:
        btn = gr.UploadButton("📁", file_types=[".pdf"],  file_count="multiple")
        btn.upload(run_file, [btn], [], show_progress = True)  
    demo.queue().launch(debug=True)`

**Comment by freddyaboulton** [comment]
Hi @luojunhui1 ! Are you changing your code between the `file_count="multiple"` and `file_count="single"` cases?

If it's a single file, your event handler will receive a single temporary file object as opposed to a list of them. This modification should handle both cases.

```python
def run_file(files):

    if not isinstance(files, list):
        files = [files]

    for file in files:
        print(f"{file.name}")
        file_suffix = file.name.split('.')[-1]
        file_dir = None

        if str(file_suffix).lower() == "pdf":
            print(f"pdf : {file.name}")
            doc = fitz.open(file.name)
            print(doc.page_count)
```

**Comment by abidlabs** [comment]
@freddyaboulton's fix works for me, so closing for lack of followup. @luojunhui1 feel free to reopen if this does not work for you. Thanks!
