### ISSUE TITLE
Text Continuation inplace (with colors)

### ISSUE THREAD

**Issue by MohamedAliRashad** [gradio-app/gradio#4023]
Is there a way to make an effect similar to this where a user writes some words and the language model continues the text and the output is written in the same textarea with a different color ?

![Screenshot from 2023-05-01 10-10-47](https://user-images.githubusercontent.com/26205298/235421074-fbf1638b-d872-4f32-b04d-c19488d0f44e.png)

**Comment by abidlabs** [comment]
Thanks for the question @MohamedAliRashad, this currently isn't possible with the `gr.Textbox` although it is a requested feature (see https://github.com/gradio-app/gradio/issues/2303). You could try creating this effect yourself using the much more customizable `gr.HTML` component.
