### ISSUE TITLE
Stop event handler not triggered for audio

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#4026]
### Describe the bug

The `stop` event handle is not triggered for audio

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

def stop_streaming():
    print("Streaming has stopped")

if __name__ == "__main__":

    with gr.Blocks() as demo:

        stream_input = gr.Audio(source="microphone")
        stream_input.stop(stop_streaming)

    demo.queue().launch(share=False,  debug=False)
```

### Screenshot

"Streaming has stopped" is not printed to the console.

![image](https://user-images.githubusercontent.com/41651716/235471015-e9f03d52-0187-4c14-a768-35480545550a.png)

### Logs

```shell
-
```

### System Info

```shell
3.28.1
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment]
Should check all the `Playable` events (stop, pause, play) work as well!

**Comment by pngwn** [comment]
I don't think we have ever emitted a `stop` event when the webcam recording is stopped. I think those events are only triggered by the player. 

We may want to consider separate events for start and stop recording because they are different to simply stopping an existing media track.

**Comment by freddyaboulton** [comment]
What's the difference between `stop` and `pause` events (both defined on Playable event class)?

**Comment by caffeinism** [comment]
I'm using a very inefficient method to catch stops, is there any chance this could be improved?

**Comment by prasanth-ntu** [comment]
> I'm using a very inefficient method to catch stops, is there any chance this could be improved?

@caffeinism Could you share the code sample for how you have the workaround to catch stops? Thanks!
