### ISSUE TITLE
Pass in preprocessing/postprocessing functions when user defines appropriate type hints

### ISSUE THREAD

**Issue by 1lint** [gradio-app/gradio#4028]
- [check] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Would like better interface for accessing preprocessing/postprocessing functions

**Describe the solution you'd like**  
Could you implement an option to pass preprocess/postprocess functions when function defines appropriate type hint like you do for the gr.Request? For example it would be really nice to have something like the following:

```
import gradio as gr

def echo(
        name,
        request: gr.Request, 
        preprocess: gr.components.Component.preprocess, 
        postprocess: gr.components.Component.postprocess,
    ):

    print("Request headers dictionary:", request.headers)
    print("IP address:", request.client.host)

    myfunc = lambda input_name: f"{input_name} has IP address: {request.client.host}"

    preprocessed_input = preprocess(name)
    
    function_output = myfunc(preprocessed_input)

    postprocessed_output = postprocess(function_output)

    return postprocessed_output

io = gr.Interface(echo, "textbox", "textbox").launch()
```

When a function signature has the appropriate preprocess/postprocess types, then automatic preprocess/postprocess should be implicitly disabled.

I think this would be a good way to give the user the flexibility to add complexity/control over the gradio app. The feature could be useful for users to log/examine the data as it is processed by the app, and modify the data at each step as needed.

**Comment by abidlabs** [comment]
Hmm I can see how this might be helpful in customizing the way data is processed at each step, but this seems rather complex (and niche) to me. It also would need to somehow work with multiple input types, each of which can have their own preprocessing and postprocessing (and in some cases, you might want to keep the default preprocessing, while in other cases you might want to disable it). 

Given the complexity of this use case, I'd suggest that you use the `gr.Blocks()` API, which includes the ability to disable the preprocessing or postprocessing for each event handler by using the `preprocess` and `postprocess` parameters. I appreciate you creating this issue but I'll go ahead and close it as the `gr.Blocks()` approach is more appropriate.

**Comment by 1lint** [comment]
Okay thanks for considering/taking a look. I am using the blocks API and ended up importing processing utils from the gradio codebase after disabling the preprocessing for my image component
