### ISSUE TITLE
Safari buttons were not fixed

### ISSUE THREAD

**Issue by cowanAI** [gradio-app/gradio#4034]
### Describe the bug

output text was fixed but not the button that look "off"

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Same issue discussed as before

### Screenshot

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/128092052/235597474-09d2f52c-3e40-460c-9cab-dedf7813836f.png">

### Logs

```shell
no logs
```

### System Info

```shell
3.28.1, safari
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hmm @aliabid94 can you investigate? @cowanAI can you provide a full code example we can use to reproduce?

**Comment by cowanAI** [comment]
for sure: 

"ui = gr.Interface(
    fn=transcribe, 
    theme='gradio/soft',
    inputs=[
        gr.Audio(source="microphone", type="filepath", label="Upload audio"),
        gr.Textbox(label="Or chat here:"),
        
    ],
    outputs=gr.Textbox(interactive=True,label="Alicja AI:").style(show_copy_button=True),
    #allow_flagging=('never'),
    examples=[    ["Medical_Transcriber.mp3", "Medical transcriber: Alicja, please summarize the patient visit and auto-fill the “X” form."],
    ["Medical_Writing.mp3", "Medical writing: Hey Alicja, can you help me organize my thoughts for this research paper?"],
    ["Clinical_Trials.mp3", "Clinical trials: Alicja, what is the recommended sample size for this clinical trial and can you help me analyze the results?"],
    ["Language_Translation.mp3", "Language translation: Alicja, can you help me translate what this patient is saying into English?"],
    ["Medical_Research.mp3", "Medical research: Hey Alicja, can you help me find some relevant literature for this research question?"],
    ["Patient_Education.mp3", "Patient education: Alicja, can you explain this medical condition to my patient in simple terms?"],
],
    css="footer {visibility: hidden}",
    allow_flagging=('never'),
)



ui.queue(concurrency_count=2)
app = gr.mount_gradio_app(app, ui, path=CUSTOM_PATH)"

I think maybe it's because the bug was fixed for Safari mobile but not Safari Desktop maybe?

**Comment by cowanAI** [comment]
ui = gr.Interface(
    fn=transcribe, 
    theme='gradio/soft',
    inputs=[
        gr.Audio(source="microphone", type="filepath", label="Upload audio"),
        gr.Textbox(label="Or chat here:"),
        
    ],
    outputs=gr.Textbox(interactive=True,label="Alicja AI:").style(show_copy_button=True),
    #allow_flagging=('never'),
    examples=[    ["Medical_Transcriber.mp3", "Medical transcriber: Alicja, please summarize the patient visit and auto-fill the “X” form."],
    ["Medical_Writing.mp3", "Medical writing: Hey Alicja, can you help me organize my thoughts for this research paper?"],
    ["Clinical_Trials.mp3", "Clinical trials: Alicja, what is the recommended sample size for this clinical trial and can you help me analyze the results?"],
    ["Language_Translation.mp3", "Language translation: Alicja, can you help me translate what this patient is saying into English?"],
    ["Medical_Research.mp3", "Medical research: Hey Alicja, can you help me find some relevant literature for this research question?"],
    ["Patient_Education.mp3", "Patient education: Alicja, can you explain this medical condition to my patient in simple terms?"],
],
    css="footer {visibility: hidden}",
    allow_flagging=('never'),
)



ui.queue(concurrency_count=2)
app = gr.mount_gradio_app(app, ui, path=CUSTOM_PATH)

**Comment by abidlabs** [comment]
> I think maybe it's because the bug was fixed for Safari mobile but not Safari Desktop maybe?

That's possible. Would you be able to check and see if that's the case? It would help us narrow down the possible culprit.

Also, which version of Safari Desktop are you using?

**Comment by cowanAI** [comment]
sure, doing right now and the version is Version 16.3 (18614.4.6.1.6) @abidlabs

**Comment by cowanAI** [comment]
@abidlabs used it on my phone and the issue is across all devices, but the text got fixed thanks for that

**Comment by cowanAI** [comment]
also tried it on google chrome mobile and it doesnt seem to be only a safari issue, it seems more like an apple related issue, although it doesnt work also on safari desktop the buttons

**Comment by cowanAI** [comment]
the desktop version looks 😍 though, but yes unfortunately the mobile just doesnt look good the buttons are "off"

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/128092052/235675894-bf318dda-c69b-4134-af0c-1d024960a132.png">

**Comment by aliabid94** [comment]
Ah I see, so I fixed the soft theme in the library, but you're loading the soft theme from the theme from the online theme store. I need to update the theme online, but I'd recommend you use the theme from the library, e.g.
```python
theme = gr.themes.Soft()
```
this way you don't need to load the theme from the internet, so it will be faster.

**Comment by aliabid94** [comment]
seems like a couples labelsare actually still grayed out actually, looking into it

**Comment by aliabid94** [comment]
Ok I fixed the grayed out labels in https://github.com/gradio-app/gradio/pull/4070, I've also already pushed the the theme hub so that should work well now.

**Comment by abidlabs** [comment]
@cowanAI I just checked on the branch on Safari Mobile and it's working well for me. You will need to redeploy yes, and you might even need to wait until we release on pypi (or install gradio from main by following the instructions here: https://gradio.app/docs/main)
