### ISSUE TITLE
chatbot does not diaplay table correctly

### ISSUE THREAD

**Issue by Tam678** [gradio-app/gradio#4062]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**  

![微信图片_20230504213254](https://user-images.githubusercontent.com/62238209/236221432-b2cd48ed-6ade-44c1-982c-fa10d857ed63.jpg)

**Comment by Tam678** [comment]
btw, gradio==3.16.2

**Comment by abidlabs** [comment]
@Tam678 can you see if the latest version of gradio (`gradio==3.28.3`) displays tables correctly for you? Would appreciate if you can share a screenshot on the latest version

**Comment by Tam678** [comment]
![微信截图_20230505111813](https://user-images.githubusercontent.com/62238209/236370990-4b2b8b86-b68b-4c67-b229-c4f77d52573c.png)
the table of gradio 3.28.3 is show as this pics,
but i want the table show as below:
 
![微信截图_20230505112050](https://user-images.githubusercontent.com/62238209/236371454-6e27ee3b-e450-4409-94b5-c71d7415326c.png)

**Comment by abidlabs** [comment]
I think this an important feature request — @dawoodkhan82  can you take a look?

**Comment by abidlabs** [comment]
Let me close this in favor of the broader issue here: https://github.com/gradio-app/gradio/issues/3680

**Comment by jrowen** [comment]
I believe you can already customize the css.  Define the chatbot with something like `Chatbot([], elem_id="chatbot")`, reference a css file using `gr.Blocks(css='static/md.css')`, and then define the desired style in your css file:

```
#chatbot table {
    border: 1px solid;
    border-collapse: collapse;
    text-align: center;
    vertical-align: middle;
}

#chatbot table th {
    border: 1px solid;
    padding: 4px;
}

#chatbot table td {
    border: 1px solid;
    padding: 4px;
}
```

**Comment by junxu-ai** [comment]
specify the LLM parameter shall work. 
e.g., 

from pandasai.llm import OpenAI

llm = OpenAI(api_token="sk-xxxx")
pandas_ai = SmartDataframe("lti.csv", config={"llm": llm})
