### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'ssl_keyfile_password'

### ISSUE THREAD

**Issue by silvacarl2** [gradio-app/gradio#4065]
### Describe the bug

I am running my server.py filee from the command line.

No matter what I do, I get this error: TypeError: __init__() got an unexpected keyword argument 'ssl_keyfile_password'

I am just testing for now, how do I disable this?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://github.com/oobabooga/text-generation-webui

then:

python server.py --model-menu --load-in-8bit

### Screenshot

Loaded the model in 13.94 seconds.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/silvacarl/Desktop/oobabooga_linux/text-generation-webui/server.py:927 in <module>          │
│                                                                                                  │
│   924 │   │   })                                                                                 │
│   925 │                                                                                          │
│   926 │   # Launch the web UI                                                                    │
│ ❱ 927 │   create_interface()                                                                     │
│   928 │   while True:                                                                            │
│   929 │   │   time.sleep(0.5)                                                                    │
│   930 │   │   if shared.need_restart:                                                            │
│                                                                                                  │
│ /home/silvacarl/Desktop/oobabooga_linux/text-generation-webui/server.py:852 in create_interface  │
│                                                                                                  │
│   849 │   if shared.args.listen:                                                                 │
│   850 │   │   shared.gradio['interface'].launch(prevent_thread_lock=True, share=shared.args.sh   │
│   851 │   else:                                                                                  │
│ ❱ 852 │   │   shared.gradio['interface'].launch(prevent_thread_lock=True, share=shared.args.sh   │
│   853                                                                                            │
│   854                                                                                            │
│   855 if __name__ == "__main__":                                                                 │
│                                                                                                  │
│ /home/silvacarl/.local/lib/python3.8/site-packages/gradio/blocks.py:1718 in launch               │
│                                                                                                  │
│   1715 │   │   │   │   │   "Rerunning server... use `close()` to stop if you need to change `la  │
│   1716 │   │   │   │   )                                                                         │
│   1717 │   │   else:                                                                             │
│ ❱ 1718 │   │   │   server_name, server_port, local_url, app, server = networking.start_server(   │
│   1719 │   │   │   │   self,                                                                     │
│   1720 │   │   │   │   server_name,                                                              │
│   1721 │   │   │   │   server_port,                                                              │
│                                                                                                  │
│ /home/silvacarl/.local/lib/python3.8/site-packages/gradio/networking.py:150 in start_server      │
│                                                                                                  │
│   147 │                                                                                          │
│   148 │   if blocks.save_to is not None:  # Used for selenium tests                              │
│   149 │   │   blocks.save_to["port"] = port                                                      │
│ ❱ 150 │   config = uvicorn.Config(                                                               │
│   151 │   │   app=app,                                                                           │
│   152 │   │   port=port,                                                                         │
│   153 │   │   host=host,                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: __init__() got an unexpected keyword argument 'ssl_keyfile_password'

### Logs

```shell
Loaded the model in 13.94 seconds.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/silvacarl/Desktop/oobabooga_linux/text-generation-webui/server.py:927 in <module>          │
│                                                                                                  │
│   924 │   │   })                                                                                 │
│   925 │                                                                                          │
│   926 │   # Launch the web UI                                                                    │
│ ❱ 927 │   create_interface()                                                                     │
│   928 │   while True:                                                                            │
│   929 │   │   time.sleep(0.5)                                                                    │
│   930 │   │   if shared.need_restart:                                                            │
│                                                                                                  │
│ /home/silvacarl/Desktop/oobabooga_linux/text-generation-webui/server.py:852 in create_interface  │
│                                                                                                  │
│   849 │   if shared.args.listen:                                                                 │
│   850 │   │   shared.gradio['interface'].launch(prevent_thread_lock=True, share=shared.args.sh   │
│   851 │   else:                                                                                  │
│ ❱ 852 │   │   shared.gradio['interface'].launch(prevent_thread_lock=True, share=shared.args.sh   │
│   853                                                                                            │
│   854                                                                                            │
│   855 if __name__ == "__main__":                                                                 │
│                                                                                                  │
│ /home/silvacarl/.local/lib/python3.8/site-packages/gradio/blocks.py:1718 in launch               │
│                                                                                                  │
│   1715 │   │   │   │   │   "Rerunning server... use `close()` to stop if you need to change `la  │
│   1716 │   │   │   │   )                                                                         │
│   1717 │   │   else:                                                                             │
│ ❱ 1718 │   │   │   server_name, server_port, local_url, app, server = networking.start_server(   │
│   1719 │   │   │   │   self,                                                                     │
│   1720 │   │   │   │   server_name,                                                              │
│   1721 │   │   │   │   server_port,                                                              │
│                                                                                                  │
│ /home/silvacarl/.local/lib/python3.8/site-packages/gradio/networking.py:150 in start_server      │
│                                                                                                  │
│   147 │                                                                                          │
│   148 │   if blocks.save_to is not None:  # Used for selenium tests                              │
│   149 │   │   blocks.save_to["port"] = port                                                      │
│ ❱ 150 │   config = uvicorn.Config(                                                               │
│   151 │   │   app=app,                                                                           │
│   152 │   │   port=port,                                                                         │
│   153 │   │   host=host,                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: __init__() got an unexpected keyword argument 'ssl_keyfile_password'
```

### System Info

```shell
Latest gradio, Ubuntu 20.04
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
It seems like you might be using an older version of uvicorn. Can you try upgrading to the newest version: `pip install uvicorn --upgrade`?

**Comment by abidlabs** [comment]
I'm quite confident this should fix your issue @silvacarl2 so I'll go ahead and close this issue. But please do let us know and feel free to reopen the issue if this doesn't fix.

**Comment by abidlabs** [comment]
Actually I think we should update the required version of `uvicorn` in `gradio` to prevent this from happening. Will get a PR out

**Comment by silvacarl2** [comment]
thx will check this out now.
