### ISSUE TITLE
3.28.3: Gradio has no attribute "Blocks" 

### ISSUE THREAD

**Issue by drscotthawley** [gradio-app/gradio#4074]
### Describe the bug

Posted this on Discord first:

Hi I just updated gradio and haven't changed my code, which uses Blocks.  But I'm being told: 

```python
    with gr.Blocks(title=kwargs['title'], css=css_code, theme=gr.themes.Base()) as demo:
AttributeError: module 'gradio' has no attribute 'Blocks'
```

What's going on here? Is Blocks suddenly broken in 3.28.3? 

For now, I've downgraded to 3.28.1 and the error has gone away. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try using Blocks in 3.28.3.  

### Screenshot

I mean, the Traceback message pretty much says it all. 

### Logs

```shell
See above
```

### System Info

```shell
3.28.3, CentOS, never even got to the browser because it wouldn't run. 

3.28.1 works. Haven't tried 3.28.2
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Hi @drscotthawley you can see `gradio==3.28.3` working just fine here: https://colab.research.google.com/drive/13b59LdJtjr0RymyP4bgFe63zsTcpGUrm?usp=sharing

This error usually just means that `gradio` wasn't installed successfully for some reason. Can you try uninstalling and reinstalling?

**Comment by drscotthawley** [comment]
@abidlabs Thank you!  Uninstall & reinstall worked!
