### ISSUE TITLE
Updating the value of `Dropdown` don't invoke `change` event

### ISSUE THREAD

**Issue by iRedBean** [gradio-app/gradio#4076]
### Describe the bug

Updating the value of `Dropdown` don't invoke `change` event.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
    txt = gr.Textbox()
    value = gr.Dropdown(choices=['A', 'B', 'C'])
    btn = gr.Button()

    value.change(fn=lambda x: x, inputs=value, outputs=txt)
    btn.click(fn=lambda: 'C', outputs=value)

demo.launch()
```

### Screenshot

https://user-images.githubusercontent.com/34592555/236448195-58d42c81-e14b-48a5-bc8e-6985107cf25e.mp4

### Logs

```shell
No error logs
```

### System Info

```shell
Gradio 3.28.3
Win10
Chrome 112.0.5615.49
```

### Severity

blocking upgrade to latest gradio version

**Comment by pngwn** [comment]
I think this is because of how the `change` trigger is implemented in some components. I would guess that this problem is present for some other components too.

**Comment by iRedBean** [comment]
Thanks for the reply, but this problem does not exist in Gradio 3.27.0, it seems a new bug introduced after 3.28.0.

**Comment by pngwn** [comment]
Interesting. Will take a look as soon as I can!
