### ISSUE TITLE
Gradio on Google Colab cell iframe returns Error 404 on certain device/browser/connection

### ISSUE THREAD

**Issue by etherealxx** [gradio-app/gradio#4077]
### Describe the bug

I don't know how to word it correctly, but gradio is able to be run through colab iframe like this, right? (the example are from [gradio hello world example](https://colab.research.google.com/github/gradio-app/gradio/blob/main/demo/hello_world/run.ipynb#scrollTo=2.8891853944186117e%2B38))
![image](https://user-images.githubusercontent.com/64251396/236488421-e31036a1-bc38-4f83-b2b8-fa317eb39524.png)

But on some device/browser, it refuses to work
![image](https://user-images.githubusercontent.com/64251396/236489130-68d3d782-c051-47cf-9041-2233a1b78284.png)
<img src="https://user-images.githubusercontent.com/64251396/236491179-84273c58-e6d1-4eb7-a02c-dbaa36ba0c21.png" width="200"><br/>

i don't know what was the problem. I was able to replicate it using [Bromite browser](https://github.com/bromite/bromite) on android, it does work fine on chrome on android (latest version) and chrome on desktop though.

But apparently some people also experienced this with the latest chrome browser on desktop, which is weird.

Keep in mind that using public url works as expected, but that isn't the point of this issue.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://colab.research.google.com/github/gradio-app/gradio/blob/main/demo/hello_world/run.ipynb

Or in my case, https://colab.research.google.com/github/etherealxx/volatile-concentration-localux-colab/blob/main/volatile_concentration_localux_colab.ipynb#scrollTo=HRLSD-HXLRNk

### Screenshot

This is the expected result
![image](https://user-images.githubusercontent.com/64251396/236483386-702da183-3e2a-4c74-8ee2-23fd653940f7.png)

But some of people have this instead
![image](https://user-images.githubusercontent.com/64251396/236483525-986b1bfb-fd7f-4ce8-95ff-a4d348daceb5.png)

### Logs

```shell
There's no log at all since the gradio UI itself doesn't even launched
```

### System Info

```shell
Gradio 3.28.3
gradio client 0.1.4

My PC (No problem were found): Windows 11, Google Chrome browser (Latest)

My Phone: Android 10, Google Chrome browser (works as expected, latest version), Bromite browser (doesn't work, [latest stable version](https://github.com/bromite/bromite/releases/tag/108.0.5359.156)
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Thanks for the detailed bug report @etherealxx. I checked on various versions of Chrome on Windows Desktop and they all worked fine. Under the hood, Gradio on Colab uses service workers, which might not be supported by Bromite. To see if this is a gradio issue or a Bromite issue, can you try seeing if Tensorboard opens successfully in a Colab notebook for you using Bromite?

You can follow these quick steps to start a Tensorboard in Colab: https://kuanhoong.medium.com/how-to-use-tensorboard-with-google-colab-43f7cf061fe4

**Comment by etherealxx** [comment]
Yes it is confirmed that tensorboard also doesn't shows up in Bromite.
![Screenshot_2023-05-06-10-58-21-225_org.bromite.bromite.jpg](https://user-images.githubusercontent.com/64251396/236598633-d7046986-e2af-419f-9525-405b85c882af.jpg)

But that's understandable since Bromite stable haven't been updated since December '22, and i am okay since i can just use chrome on Android anyway.

What i can't seem to understand is how several other people reported to me (not via github issue) that this also happen with them, on Chrome for PC. I've contacted some of them and they might also post their problem here, so i think I'll wait.

**Comment by etherealxx** [comment]
Okay so someone figured out it was because of blocked cookies https://github.com/etherealxx/volatile-concentration-localux-colab/issues/1#issuecomment-1537143712. Allowing the cookies would fix the problem.

I don't know why some people's browser blocked this cookies while others don't, but **i think this should be addressed somewhere in the gradio documentation**, in case someone else have the same problem.

Also quick note, i was able to fix the problem on Bromite by manually allowing cookies. Is it safe or not i'm not quite sure.
<img src="https://user-images.githubusercontent.com/64251396/236655714-561a2201-b8c8-4cc6-b3ff-ae42d58bc270.jpg" width="200"><img src="https://user-images.githubusercontent.com/64251396/236655721-4e944956-d9a0-4e74-a690-b212791e0ac4.jpg" width="200"><br/>

**Comment by abidlabs** [comment]
Oh wow, that's good to know! Surprised that this hasn't popped up before. Will add to this PR: https://github.com/gradio-app/gradio/pull/4086
