### ISSUE TITLE
Gradio Audio Playback not working on Safari Desktop after recorded (Universal error)

### ISSUE THREAD

**Issue by Alanp777** [gradio-app/gradio#4085]
### Describe the bug

https://huggingface.co/spaces/WXM2000/audio_to_text_Chinese

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/WXM2000/audio_to_text_Chinese

### Logs

```shell
https://huggingface.co/spaces/WXM2000/audio_to_text_Chinese
```

### System Info

```shell
all versions
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks @Alanp777 for creating this issue. Is it the same as https://github.com/gradio-app/gradio/issues/2987?

**Comment by Alanp777** [comment]
yes @abidlabs , do you know if it's possible to add an audio download button to the gradio interface? that would be my last question, thanks so much

**Comment by abidlabs** [comment]
Not at the moment, but that's something we can consider adding in the future. Please feel free to make a new issue about that, and I'll close this one. We'll work on getting #2987 fixed

**Comment by Alanp777** [comment]
@abidlabs Just so your users know, just figured you can right click on Mozilla and Chrome and save the audio file, maybe there could be a way around Safari, haven't figured on mobile yet, thanks

**Comment by abidlabs** [comment]
Good to know! Feel free to create a separate issue with this explanation, and we can definitely add it (similar to what we have for the `Image` and `Video` components)
