### ISSUE TITLE
Download button for `gr.Audio` component

### ISSUE THREAD

**Issue by Alanp777** [gradio-app/gradio#4087]
### Describe the bug

currently I can right click on Mozilla firefox and chrome and download or "save the file as" would love to have a dedicated button to download the audio files

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Anywhere

### Logs

```shell
Anywhere
```

### System Info

```shell
latest
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks @Alanp777! Linking to the relevant discussion in https://github.com/gradio-app/gradio/issues/4085 as well

**Comment by AmanSal1** [comment]
is this issue solved ?
