### ISSUE TITLE
Way to change favicon *during execution* to show "in progress" 

### ISSUE THREAD

**Issue by drscotthawley** [gradio-app/gradio#4089]
# Feature Request: 
- [ x] I have searched to see if a similar issue already exists.
Similar issue https://github.com/gradio-app/gradio/issues/385 discussed static change of the favicon. 

What I'd like to do --- and so far have been unable to get it working myself via JavaScript -- is to have the possibility for the favicon to *change* during execution of inference, and then change back (to "normal") when output is supplied - i.e. a favicon to show that the run is "in progress" 

**Is your feature request related to a problem? Please describe.**  
The only "problem" is that if I"m running multiple instances of my demo in different tabs, I'd love to be able to see just from the tab favicon which runs are still going and which ones have finished.  Currently I have to manually click the tabs to see which ones have finished.   It would just be nice to have the favicon show me. :-) 

Or even if I"m not doing multiple runs, I may be working in other browser tabs during the minute or more it takes for my inference run(s) to complete, so it'd be cool to have the visual queue of having a favicon change state, notifying me that I now have output ready to view. 

**Describe the solution you'd like**  
Either documentation to help us know how to add the appropriate Javascript, so that we can attach an event handler to our output so that it toggles the favicon whenever the output changes state, 

...or....

Even better:  You let users supply *two* favicons!  One for "normal" and one for "in progress" :-)    (and please make sure it works with Blocks, not just with Interface!)

**Additional context**  
I tried attaching some javascript output to the `.change()` for one of my outputs using code from [this StackOverflow post](https://stackoverflow.com/a/2995536/4259243), but... I don't really know what I'm doing when it comes to Javascript and it didn't have any effect.

**Comment by abidlabs** [comment]
Hi @drscotthawley thanks for filing this issue and sorry for the late response here. This is a bit niche for us to include in the core gradio library, but you could achieve something like this using the `js` parameter in Gradio events.

Basically you'd write a function in JS to change the favicon, something like this:

```js
function changeFavicon(url) {
    // Find the existing favicon element
    var favicon = document.querySelector('link[rel="shortcut icon"]') || document.createElement('link');
    favicon.type = 'image/x-icon';
    favicon.rel = 'shortcut icon';
    favicon.href = url;

    // Replace or append the new favicon to <head>
    var head = document.querySelector('head');
    var oldFavicon = head.querySelector('link[rel="shortcut icon"]');
    if (oldFavicon) {
        head.removeChild(oldFavicon);
    }
    head.appendChild(favicon);
}

// Usage
changeFavicon('path_to_new_favicon.ico');
```

And then you could call it from your event using the `js` parameter. You could also use `.then()` to chain a series of events together. Hope this helps!
