### ISSUE TITLE
Extremely slow generation in chatbot in some cases

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#4092]
### Describe the bug

https://github.com/h2oai/h2ogpt/issues/54

For some inputs, when gradio needs to process the chat input and output, the time it takes to go through that processing is exceeding long.  E.g. can be 1 character every few seconds!

This is for two reasons:

1) The processing is very slow single core operation and on long inputs takes too long
2) The chat interface requires pushing through to chatbot the full content every update when doing streaming, leading to an O(N^2) problem.  This is fine in general, that streaming is dynamic and so any processing is dynamic, but for long inputs it reveals that the first problem (1) becomes too expensive.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://github.com/h2oai/h2ogpt/issues/54 shows examples.  E.g. when doing URLs, math, markdown leads to major slowdown if input into chatbot is large.

Key to reproduction is to copy-paste long and non-trivial text, so gradio thinks it needs to go through the markdown and other post-processing.

I identified the exact place is always in _postprocess_chat_messages, e.g.: https://github.com/h2oai/h2ogpt/issues/54#issuecomment-1515516527

I hacked a work-around: https://github.com/h2oai/h2ogpt/issues/54#issuecomment-1515520308

But it ends up now always showing even basic new lines so had to avoid the work-around.

So I have no work-around.

### Logs

```shell
NA
```

### System Info

```shell
gradio==3.27.0
gradio_client==0.1.3


Severity levels shown don't apply. It does not block all usage, but when it happens it makes for a horrible UX.
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks @pseudotensor for flagging this! cc @aliabid94 who has been looking into this
