### ISSUE TITLE
Block api cannot be called from same host due to CORS policy

### ISSUE THREAD

**Issue by Banbury** [gradio-app/gradio#4094]
### Describe the bug

Calling a Gradio api from the browser on the same host as the server fails with CORS errrors.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:7861/api/generate. (Reason: CORS request did not succeed).
```

There really needs to be an option to configure the CORS headers.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

test.py
```python
import gradio as gr

def generate():
    return "Hello World!"

with gr.Blocks(analytics_enabled=False) as app:
    pbGenerate = gr.Button("Generate")
    pbGenerate.click(fn=generate, api_name="generate")


app.launch(server_name="0.0.0.0")
```
index.html
```html
<!DOCTYPE html>
<body>
    <script lang="javascript">
        fetch("http://localhost:7861/api/generate", {
            method: "post",
            headers: {
                'Content-Type': 'application/json'
            },          
            body: "{}"
        }).then(res => {
            return res.json()
        });
    </script>
</body>
```

Execute the Python file and host the HTML on a local server. 
Opening the HTML file in a browser will result in the above error message.

### Logs

```shell
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:7861/api/generate. (Reason: CORS request did not succeed).
```
```


### System Info

```shell
Gradio 3.24.0
Windows 11
Firefox (should happen in any modern browser)
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @Banbury on the latest version of `gradio`, I do not see a CORS issue, but instead a 422 error because the gradio app isn't set up correctly or the POST request has not been made correctly. To fix this:

1. Upgrade to the latest version of `gradio`
2. Try this `test.py`:

```py
import gradio as gr

def generate(x):
    return "Hello " + x + "!"

with gr.Blocks(analytics_enabled=False) as app:
    pbGenerate = gr.Textbox()
    pbGenerate.submit(fn=generate, inputs=pbGenerate, outputs=pbGenerate, api_name="generate")

app.launch()
```

3. Try this `index.html`:

```html
<!DOCTYPE html>
<body>
    <script lang="javascript">
        fetch("http://localhost:7860/api/generate", {
            method: "post",
            headers: {
                'Content-Type': 'application/json'
            },          
            body: JSON.stringify({"data": ["Abubakar"]})
        }).then(res => {
            console.log(res.json())
        });
    </script>
</body>
```

**Comment by bxclib2** [comment]
> Hi @Banbury on the latest version of `gradio`, I do not see a CORS issue, but instead a 422 error because the gradio app isn't set up correctly or the POST request has not been made correctly. To fix this:
> 
>     1. Upgrade to the latest version of `gradio`
> 
>     2. Try this `test.py`:
> 
> 
> ```python
> import gradio as gr
> 
> def generate(x):
>     return "Hello " + x + "!"
> 
> with gr.Blocks(analytics_enabled=False) as app:
>     pbGenerate = gr.Textbox()
>     pbGenerate.submit(fn=generate, inputs=pbGenerate, outputs=pbGenerate, api_name="generate")
> 
> app.launch()
> ```
> 
>     3. Try this `index.html`:
> 
> 
> ```
> <!DOCTYPE html>
> <body>
>     <script lang="javascript">
>         fetch("http://localhost:7860/api/generate", {
>             method: "post",
>             headers: {
>                 'Content-Type': 'application/json'
>             },          
>             body: JSON.stringify({"data": ["Abubakar"]})
>         }).then(res => {
>             console.log(res.json())
>         });
>     </script>
> </body>
> ```
> 
> Should work for you.

Hi, I meet the same bug. The bug only exists in firefox. Have you tested the firefox browser? The gradio client does not work
