### ISSUE TITLE
Ability to disable pull-to-refresh on mobile

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#4097]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I have been bitten by accidental pull-to-refresh too many times to count when using webui on mobile. Since refreshing the page means loosing a ton of settings it's exceptionally frustrating. And I've no real use cases for pull-to-refresh for gradio apps specifically (though I do use it elsewhere, so turning it off in my browser wouldn't be as helpful)

**Describe the solution you'd like**  
I would prefer the ability to toggle some CSS that specifies `overscroll-behavior-y: contain;` to turn it off

**Comment by abidlabs** [comment]
Hi @space-nuko just to clarify the issue, you are able to fix this behavior with the custom CSS you've specified? But you're asking if   this could be a built-in parameter to gradio?

**Comment by space-nuko** [comment]
Yes in case it's helpful to others

**Comment by abidlabs** [comment]
This seems to be a case where using custom css is the right thing to do, instead of hiding under a thin abstraction. The custom css applies to the whole page so its unlikely to break if the gradio DOM changes and its a single line of css.
