### ISSUE TITLE
Webcam bug on gradiohub

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#41]
Received a bug request on: https://www.gradio.app/hub/hub-emotion-recognition

![image](https://user-images.githubusercontent.com/1778297/89214797-16551080-d58d-11ea-8e6b-6f8911d369ba.png)

**Comment by FORTFANOP** [comment]
I'm facing the same error.

A dialogue box pops up showing the  following:

Webcam.js Error: No width and/or height for webcam.  Please call set() first, or attach to a visible element.


After that another error pops up:

Webcam.js Error: Webcam is not loaded yet

Please help.

**Comment by abidlabs** [comment]
Should be fixed now
