### ISSUE TITLE
Can I place more that 4 Column in 1 Row?

### ISSUE THREAD

**Issue by LZY-the-boys** [gradio-app/gradio#4101]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
![image](https://user-images.githubusercontent.com/72137647/236790123-1075d28c-bf74-4569-85ef-0e56576941b2.png)

**Example Code**
```
import gradio as gr

max_textboxes = 10

def variable_outputs(k):
    k = int(k)
    return [gr.Textbox.update(visible=True)]*k + [gr.Textbox.update(visible=False)]*(max_textboxes-k)

with gr.Blocks() as demo:
    s = gr.Slider(1, max_textboxes, value=max_textboxes, step=1, label="How many textboxes to show:")
    textboxes = []
    with gr.Row():
        for i in range(max_textboxes):
            with gr.Column():
                t = gr.Textbox(f"Textbox {i}")
            textboxes.append(t)

    s.change(variable_outputs, s, textboxes)

if __name__ == "__main__":
   demo.launch(share=0,server_port=8081)
```  

**Additional context**

**Comment by abidlabs** [comment]
Hi @LZY-the-boys yes it's possible. The reason you are seeing this is because by default, a `gr.Column()` has a `min_width` of `320px`. If you reduce this, you should be able to fit more columns in your screen.
