### ISSUE TITLE
Authentication does not work on colab

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#4103]
### Describe the bug

Launching a demo with auth on colab does not show the demo.

Adding a share link will let you access the demo but it still will not display in the notebook.

My guess is colab is restricting access to the `login` route.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Launch a gradio demo on colab with auth:

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/41651716/236823581-5ad1042b-22eb-49f0-8230-8e2d4a9ce9a3.png">

### Logs

```shell
-
```

### System Info

```shell
gradio: 3.28.3
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
This may be niche. Just noting it because I tried to demo auth on colab and got unintuitive behavior.

**Comment by abidlabs** [comment]
Looks like this is no longer an issue: we automatically create share links on Colab + auth shows up in the embedded demo:

<img width="1354" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/076efd7f-a068-4478-baf5-5d9f937a40b8">

and confirmed that the demo works as expected:

<img width="1386" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/e73f41be-2f5e-4c52-be63-b85e5bec6a16">
