### ISSUE TITLE
Stable Diffusion Why is it so error-prone? 

### ISSUE THREAD

**Issue by dsst14** [gradio-app/gradio#4108]
Stable Diffusion Why is it so error-prone? please fix it properly  While using it, an error suddenly occurs, and even if you set "All pictures are gone", it is not fixed even if you sign up. Please correct me.
![bandicam 2023-05-09 04-03-19-650](https://user-images.githubusercontent.com/126126906/236910069-ab818e57-4e71-4b43-a26a-61d8ded90b64.jpg)

**Comment by abidlabs** [comment]
Hi @dsst14 this issue does not have any details for us to reproduce. If you see a gradio-specific issue, please create a small reproducible example for us. Otherwise, if this is related to the Automatic1111 web ui, please open an issue in that repo. Thanks!
