### ISSUE TITLE
API endpoint for health check

### ISSUE THREAD

**Issue by decent-engineer-decent-datascientist** [gradio-app/gradio#4110]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
When deploying a gradio app on prem, it would be nice to be able to check for the health of the server. Right now we check to see if the deployment loads up when pinged, but this is a bit costly and very non-standard.

**Describe the solution you'd like**  
A component that is accessible via api endpoint that when faced with a GET request, gives a short summary on server stats. If stats are too much, even just a "I'm up" response would suffice.

If there is already a way to do this, please excuse my ignorance; any pointers would be welcome.

**Comment by freddyaboulton** [comment]
Hi @decent-engineer-decent-datascientist (love the handle), what if you send a request to the `/config` route? If the status code is 200 the server is up.

**Comment by freddyaboulton** [comment]
For info related to the queue specifically, the route is `/queue/status`!

We originally didn't intend for these routes to be user facing (mainly just used by the client running in the browser) but we may consider documenting them as I've heard more people be interested in them. cc @abidlabs @aliabd 

I think you can build your own route to measure memory consumption by mounting your gradio app as a subapp of another FastAPI app that has the route you need. Info to do that here: https://gradio.app/sharing-your-app/#mounting-within-another-fastapi-app

Will close for now. Thanks @decent-engineer-decent-datascientist !
