### ISSUE TITLE
 Gradio is unable to fetch a file from the specified path because it is not within the working directory of the Gradio app or it is not a temporary file created by the app.

### ISSUE THREAD

**Issue by wzgrx** [gradio-app/gradio#4118]
### Describe the bug

The image after running is cracked and the preview image cannot be seen

{"error":"HTTPException","detail":"File cannot be fetched: D:/File/fl/2023-05-09/00004-1710112629.png. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.","body":"","errors":"(403, 'File cannot be fetched: D:/File/fl/2023-05-09/00004-1710112629.png. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.')"}

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

96c17a7470a2dffdc3cc0fd5f9e9b45510a4d3c6

### Screenshot

![Snipaste_2023-05-09_16-23-51](https://user-images.githubusercontent.com/39661556/237038500-fd2f2b03-7cc6-4ee0-8508-8d7ea61d7388.png)

### Logs

```shell
{"error":"HTTPException","detail":"File cannot be fetched: D:/File/新建文件夹/2023-05-09/00004-1710112629.png. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.","body":"","errors":"(403, 'File cannot be fetched: D:/File/新建文件夹/2023-05-09/00004-1710112629.png. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.')"}
```

### System Info

```shell
gradio: 3.28.1
Win11
edge
```

### Severity

annoying

**Comment by wzgrx** [comment]
In the stable differentiation web ui https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/879ed5422c85ddcd6b67c0fa865829439c44a4dc
Problems with the version

**Comment by freddyaboulton** [comment]
Hi @wzgrx ! That's intended behavior. There's an `allowed_paths` argument to `gr.Blocks()`, e.g. `gr.Blocks(allowed_paths=['D:/File/fl/']`, that will allow the server to serve apps from directories not created by it.

**Comment by wzgrx** [comment]
> 嗨！这是预期的行为。例如，有一个参数将允许服务器从不是由它创建的目录中提供应用程序。`allowed_paths``gr.Blocks()``gr.Blocks(allowed_paths=['D:/File/fl/']`

Okay, it has been fixed. Thank you for your reply

**Comment by yiya1989** [comment]
now allowed_paths moves to launch
```
app.queue(max_size=50).launch(
            allowed_paths=["D:/File"],
)
```
