### ISSUE TITLE
gr.Image() with color-sketch

### ISSUE THREAD

**Issue by ParityError** [gradio-app/gradio#4120]
### Describe the bug

When attempting to use "**color-sketch**" with `gr.Image()` I get the following error:
```
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
Using `gr.ImageMask()` works, although I'm attempting to a draw color mask on top of an image and return output as only the color mask without the original image (like "sketch" works).

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
gr.Interface(
    lambda x: [x["mask"], x["image"]],
    gr.Image(source="upload", tool="color-sketch"),
    [gr.Image(), gr.Image()],
)
```

### Screenshot

![desired mask](https://github.com/gradio-app/gradio/assets/36368048/08f18806-b7c0-46a9-8799-e171cd0c6b0e)

### Logs

```shell
none
```

### System Info

```shell
3.26.0, macOS, any
```

### Severity

annoying

**Comment by pngwn** [comment]
This isn't a bug but is by design (I think). We do have plans to change this in a future version but it will be a breaking change.

(will check we don't already have an issue for this)

**Comment by ParityError** [comment]
@pngwn, I guess this is somewhat similar of a request:

https://github.com/gradio-app/gradio/issues/2425
