### ISSUE TITLE
Gradio disrupted my theme across all my users :(

### ISSUE THREAD

**Issue by Alanp777** [gradio-app/gradio#4121]
### Describe the bug

Just woke up and redeployed an instance and got all my theme completely changed, now the brand of my app looks completely different to what Im advertising

.venv/lib/python3.11/site-packages/gradio/blocks.py:636: UserWarning: Cannot load gradio/soft. Caught Exception: The space gradio/soft does not exist
  warnings.warn(f"Cannot load {theme}. Caught Exception: {str(e)}")

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

.venv/lib/python3.11/site-packages/gradio/blocks.py:636: UserWarning: Cannot load gradio/soft. Caught Exception: The space gradio/soft does not exist
  warnings.warn(f"Cannot load {theme}. Caught Exception: {str(e)}")

### Screenshot

.venv/lib/python3.11/site-packages/gradio/blocks.py:636: UserWarning: Cannot load gradio/soft. Caught Exception: The space gradio/soft does not exist
  warnings.warn(f"Cannot load {theme}. Caught Exception: {str(e)}")

### Logs

```shell
.venv/lib/python3.11/site-packages/gradio/blocks.py:636: UserWarning: Cannot load gradio/soft. Caught Exception: The space gradio/soft does not exist
  warnings.warn(f"Cannot load {theme}. Caught Exception: {str(e)}")
```

### System Info

```shell
.venv/lib/python3.11/site-packages/gradio/blocks.py:636: UserWarning: Cannot load gradio/soft. Caught Exception: The space gradio/soft does not exist
  warnings.warn(f"Cannot load {theme}. Caught Exception: {str(e)}")
```

### Severity

annoying

**Comment by Alanp777** [comment]
This is how I been loading my code for 2 months and it doesnt work anymore:

ui = gr.Interface(
    fn=transcribe, 
    theme='gradio/soft',

**Comment by Alanp777** [comment]
augh i found the issue, now you have to append the specific version as well 'gradio/soft@0.0.3' glad I was able to troubleshoot this quickly, is there anywhere I have to read updates about this? or is this like the wild west, it really caught me off by surprise

**Comment by freddyaboulton** [comment]
Hi @Alanp777 ! Some themes are hosted on the hub and the hub went down earlier today. I think that may have also played a part? Can you check if you still need to append `0.0.3`? The soft theme comes built into gradio so you can also use `gr.themes.Soft()`. Will close since the issue seems to have resolved itself.

**Comment by Alanp777** [comment]
thank you for this response @freddyaboulton by any chance do know of any documentation regarding streaming the text by the open AI API?

I read your documentation about it and it says to only replace return by yield and also to make it a generator, but i also read that you can simply turn stream=true in the open ai parameters? i really watched every tutorial on earth and even this guy that compared all similar platforms like gradio could not make it stream "https://www.youtube.com/watch?v=B05Be7y6oqg" by any chance could you help on this? I promise to not bother again, i contribute to the community with my findings as well, thank you
