### ISSUE TITLE
Examples on Use via API are not serialized 

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#4122]
### Describe the bug

All of the example inputs seem to show the non-serialized (JS) example inputs, not the Python example inputs

![image (1)](https://github.com/gradio-app/gradio/assets/9021060/4fa3862d-df05-4c1b-9a78-5bd75ff76a18)

 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

run a demo on main and look at the info route 

### Logs

```shell
N/A
```

### System Info

```shell
gradio v3.28.4b0
```

### Severity

annoying

**Comment by abidlabs** [comment]
I synced with @freddyaboulton and can confirm that this issue is now fixed on `main`. The only thing that needs to be done is that booleans need to be converted from javascript to python. Simple enough such that we can hardcode it for now

**Comment by abidlabs** [comment]
Fixed now, thanks @aliabd!
