### ISSUE TITLE
Demos on Colab have high latency

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#4124]
### Describe the bug

When running a very simple interface with a dummy inference function, I'm seeing that the entire request takes a few seconds to complete. Locally and on Spaces, it runs sub < 0.5 seconds.

This is likely a colab issue - no share link is created for this demo - but noting here so that we can be aware of the problem and ask colab for help.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run this demo on colab

```python
def classify_image(image):
    return {"dog": 0.9, "cat": 0.1}

# Write 1 line of Python to create a simple GUI
gr.Interface(
    fn=classify_image, 
    inputs="image", 
    outputs="label",
).launch()
```

### Screenshot

![slow_colab](https://github.com/gradio-app/gradio/assets/41651716/10548ad7-746f-4798-ad54-0a33aff17a85)

### Logs

```shell
-
```

### System Info

```shell
3.28.3
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Yea when hosted on colab and accessed via share link, the request cycle is much faster (sub 1 second).

![fast_share_link](https://github.com/gradio-app/gradio/assets/41651716/50f90622-5063-42c5-81b1-df464778f2e1)

**Comment by abidlabs** [comment]
Haha nice example

**Comment by abidlabs** [comment]
Closing as creating a share link is now required on Colab
