### ISSUE TITLE
Change behavior of `JSONSerializable` from returning a file to just returning the dict/list  

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#4129]
Currently `JSONSerializable` components such as the `Chatbot`, `Label`, and `JSON`, return a path to a JSON file, which is annoying to work with. E.g. see issue #4081

We should change the serialization format to simply return the appropriate Python object (a list or a dict, depending on the JSON). 

This would technically be a breaking change in the API so let's do it in 4.0

**Comment by zolero** [comment]
When does this get's implemented since it's pretty unusable to work with using more advanced infrastructures. This file serving mechanism with passing data in it's core is pretty unstable. This is not the first time we keep running into this issue, also with file uploads, audio parsing, etc...

**Comment by abidlabs** [comment]
Hi @zolero can you elaborate a little more how this is affecting you -- are you using the Gradio client, or is it something else?

**Comment by zolero** [comment]
> Hi @zolero can you elaborate a little more how this is affecting you -- are you using the Gradio client, or is it something else?

Excuse me I've misunderstood this issue. I've run into the same error message but not the same use-case. Ignore my previous comment. It's resolved.

**Comment by freddyaboulton** [comment]
Done in `v4` branch thanks to the data_model!
