### ISSUE TITLE
"Hers" missing in gender list

### ISSUE THREAD

**Issue by Ontopic** [gradio-app/gradio#413]
Is this on purpose? Would love to hear hear the reasoning, since "his" is in the male list. If just slipped through, maybe better to fix in the example.

**Comment by abidlabs** [comment]
Thanks @Ontopic. Not on purpose no. Would you like to make a PR to update the code?

**Comment by Lucifer0x17** [comment]
Can you elaborate lil more on the issue? I would like to work on the issue.

**Comment by abidlabs** [comment]
Thanks @Lucifer0x17 it looks like @fiordiconio put a fix through already. But if you are interested, you can take a look at the other couple of "good first issues"

**Comment by Lucifer0x17** [comment]
Okay I will look into other issues. Thank you so much :).
