### ISSUE TITLE
Username field in the flag report is blank

### ISSUE THREAD

**Issue by gsachdev-adeptia** [gradio-app/gradio#4134]
### Describe the bug

The flag log file created from Gradio is having username column but value is empty. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

#login function
def same_auth(username, password):
    return username == password

#setup gradio interface
iface = gr.Interface(fn=chatbot,
                    inputs=gr.components.Textbox(lines=7, label="Enter your text"),
                    outputs="text",
                   title="testing", allow_flagging="manual",flagging_options=["correct","wrong","ambiguous"])

#launch gradio
iface.launch(share=True ,auth=same_auth)

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/12921808/c2888a2b-0985-43f1-9979-61eee5b6d009)

### Logs

```shell
NA
```

### System Info

```shell
Gradio Version 3.29.0,Operation System - Windows 10 Pro, Browser - Chrome  112.0.5615.138
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks @gsachdev-adeptia for reporting! This is indeed broken, though we have a fix here: #4135

**Comment by abidlabs** [comment]
The fix is on `main` if you'd like to test it out.

**Comment by gsachdev-adeptia** [comment]
I uninstall the gradio and installed it from the main branch as you indicated. Still not seeing any value filed in for the username in the flagged file. Do I need to do anything additional to have that written in the flagged file?

**Comment by abidlabs** [comment]
I tested with this code and it's working for me on `main`:

```py
import gradio as gr
#login function
def same_auth(username, password):
    return username == password

#setup gradio interface
iface = gr.Interface(fn=lambda x:x,
    inputs=gr.components.Textbox(lines=7, label="Enter your text"),
    outputs="text",
    title="testing", allow_flagging="manual",flagging_options=["correct","wrong","ambiguous"])

#launch gradio
iface.launch(auth=same_auth)
```

Can you try it and see if it works for you?

**Comment by gsachdev-adeptia** [comment]
I am still getting blank user name. Is the below pip to get from main branch correct
pip install https://gradio-main-build.s3.amazonaws.com/2cf13a1c698afed7f4418bc705902fa7868c6890/gradio-3.29.0-py3-none-any.whl

I suggest the above link is not correct.

**Comment by abidlabs** [comment]
Please try:
```
pip install https://gradio-main-build.s3.amazonaws.com/ccdaac1395238eb9c11dacb5710e78de19c1c70e/gradio-3.29.0-py3-none-any.whl
```

**Comment by gsachdev-adeptia** [comment]
It works now. I validated. Thanks for the quick fix.

**Comment by spaceman-cb** [comment]
@RNBharath One year later, I suspect you've already sorted this out, but I was running into a similar problem today.

For anyone encountering this problem in the future, it looks like you need to explicitly pass the username/request to CSVLogger, similar to the code below:

```
flagger = gr.CSVLogger()

def flag(
    component_field_1,
    component_field_2,
    request: gr.Request  # <-- IMPORTANT
):
    flagger.flag(
        [component_field_1, component_field_2], 
        username=request.username  # <-- IMPORTANT
)

with gr.Blocks() as demo:

    # UI goes here

    flagger.setup( # components # )
    component_1.click(
        flag,    # <-- IMPORTANT
        # components go here
    )
```

@abidlabs, when following the [documentation](https://www.gradio.app/guides/using-flagging) for the first time, it's very easy to just copy & paste `btn.click(lambda *args: callback.flag(list(args)) ...` from the example code at the bottom without realizing the need to pass the username as well. Explaining this there may save future developers some trouble.

Hope this helps!
