### ISSUE TITLE
Will gradio_client support setting timeout while calling Client.submit

### ISSUE THREAD

**Issue by 7ippo** [gradio-app/gradio#4137]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I found that in some special cases, Client.submitting does not trigger result_callbacks. We need to use the Client asynchronously, so we want to set the job's timeout when submitting, and callback some default parameters to the passed-in result_callbacks method when the job times out.

Alternatively, we can periodically check `job.done()` to determine if it has timed out, but what should we do if it does time out? According to the documentation, it seems that we cannot cancel a task that has already started, and it may trigger my callback method again after a long time. What should I do in this situation?

**Comment by abidlabs** [comment]
Hi @7ippo thanks for opening this issue, but for general questions like this (that are not feature requests or bug reports), please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
