### ISSUE TITLE
Equation rendering in Chatbot doesn't properly escape $ char

### ISSUE THREAD

**Issue by jerpint** [gradio-app/gradio#4143]
### Describe the bug

When using the `gr.Chatbot` UI, escaping the `$` sign works in unexpected ways and is inconsistent.

This is partly due to how the chatbot component always parses the UI every time a new message gets sent.

We would expect that `\$VAR` always escapes the dollar sign, and doesn't consider it for an equation, but that is not the observed behaviour. When sending multiple messages, the escaped $ is no longer escaped. See video: In the first messgae, everything is good, but after the second message, it gets all messed up:

https://github.com/gradio-app/gradio/assets/18450628/dffff0c2-958d-4f65-9af4-5dd06a1c0ba7

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Simply reproduce with the text from the video in any Chatbot UI

https://github.com/gradio-app/gradio/assets/18450628/dffff0c2-958d-4f65-9af4-5dd06a1c0ba7

### Screenshot

https://github.com/gradio-app/gradio/assets/18450628/dffff0c2-958d-4f65-9af4-5dd06a1c0ba7

### Logs

```shell
No error
```

### System Info

```shell
gradio version: 3.29.0
python: 3.10.11
macOS
```

### Severity

annoying

**Comment by jerpint** [comment]
For anyone looking for a workaround to disable equation rendering (for now), add this top your `app.py`:

```
from markdown_it import MarkdownIt
from mdit_py_plugins.footnote.index import footnote_plugin
from gradio.utils import highlight_code

def get_markdown_parser() -> MarkdownIt:
    """Modified method of https://github.com/gradio-app/gradio/blob/main/gradio/utils.py#L42

    Removes the dollarmath_plugin to render Latex equations.
    """
    md = (
        MarkdownIt(
            "js-default",
            {
                "linkify": True,
                "typographer": True,
                "html": True,
                "highlight": highlight_code,
            },
        )
        # .use(dollarmath_plugin, renderer=tex2svg, allow_digits=False)
        .use(footnote_plugin)
        .enable("table")
    )

    # Add target="_blank" to all links. Taken from MarkdownIt docs: https://github.com/executablebooks/markdown-it-py/blob/master/docs/architecture.md
    def render_blank_link(self, tokens, idx, options, env):
        tokens[idx].attrSet("target", "_blank")
        return self.renderToken(tokens, idx, options, env)

    md.add_render_rule("link_open", render_blank_link)

    return md



with block:
    with gr.Row():
        gr.Markdown("<h3><center>Buster 🤖: A Question-Answering Bot for your documentation</center></h3>")

    chatbot = gr.Chatbot()
    chatbot.md = get_markdown_parser()  # Workaround to disable latex rendering
```

**Comment by abidlabs** [comment]
Thanks @jerpint. cc @dawoodkhan82 @pngwn this would be solved if we rendered everything, including LaTeX, in the frontend.
