### ISSUE TITLE
Frontend freezes up when running demo.load with regular interval refresh 

### ISSUE THREAD

**Issue by 1lint** [gradio-app/gradio#4145]
### Describe the bug

Running a demo with the `load(..., every=refresh_interval)` method causes the frontend to freeze with orange boxes. I have a minimal reproduction below, but the app I am trying to make is a multiplayer tic tac toe game based on https://gradio.app/blocks-and-event-listeners/#gathering-event-data, where multiple players can connect from separate browser sessions and share a common game state.

Ideally I want to push an event to every player to refresh their frontends each time a single player makes a move, but I didn't find a way to do that (if this is possible please let me know!). 
The next option is to regularly refresh the frontend at regular intervals, so that players have their frontend display synced with the global game state without having to manually refresh the page. This is what I'm trying to here but instead its freezing the frontend completely. 
Getting this to work would be really useful for making apps like a chat server where multiple people can interact with a LLM in a social setting, such as multiplayer AI dungeon

btw I have a game running on my [hf space](https://huggingface.co/spaces/lint/multitac) if anyone is up for a round (but you have to manually refresh to check if someone else has made a move)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```

import gradio as gr
# tested for gradio versions 3.28.3, 3.29.0
import numpy as np

board_state = np.full((3, 3), "")
event_log = [""]

def refresh_display():
    return board_state, "\n".join(event_log)

with gr.Blocks(analytics_enabled=False) as demo:
    events = gr.Textbox(interactive=False, label="Turn")
    board = gr.Dataframe(interactive=False, type="array")

    # this works normally
    #demo.load(refresh_display, [], [board, events]) 

    # this causes gradio frontend to freeze with orange borders on my machine
    demo.load(refresh_display, [], [board, events], every=10) 

demo.queue()
demo.launch()
```

### Screenshot

<img width="1526" alt="frozen_orange_boxes" src="https://github.com/gradio-app/gradio/assets/105617163/12337685-8f62-476e-acfd-5eef62bd687d">

### Logs

```shell
N/A, bug causes frontend to freeze without error message
```

### System Info

```shell
gradio versions 3.29.0, 3.28.3
I run gradio on WSL2 and access frontend with Chrome on Windows
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment]
Hi @1lint ! Thanks for filing. I cannot reproduce this version 3.30.0. I cannot type in the grid or textbox with your code but I am able to by setting `interactive=True`.

<img width="903" alt="Screenshot 2023-05-16 at 1 56 33 PM" src="https://github.com/gradio-app/gradio/assets/41651716/98bc6b20-117e-4e5c-a9a2-dbfc17e4a2b2">

**Comment by 1lint** [comment]
Hey thanks for taking a look @freddyaboulton ! that's a good catch I should've set interactive=True for the test code. But it's still causing the same issue for me even when I set interactive=True on gradio 3.30. This is my code now

```
import gradio as gr
# tested for gradio 3.30
import numpy as np

board_state = np.full((3, 3), "")
event_log = [""]

def refresh_display():
    return board_state, "\n".join(event_log)

with gr.Blocks() as demo:
    events = gr.Textbox(interactive=True, label="Turn")
    board = gr.Dataframe(interactive=True, type="array")

    # this works normally
    #demo.load(refresh_display, [], [board, events]) 

    # this causes gradio frontend to freeze with orange borders on my machine
    demo.load(refresh_display, [], [board, events], every=10) 

demo.queue()
demo.launch()
```

I also get the same result running the test in a gradio 3.30 HF space https://huggingface.co/spaces/lint/test to make sure it wasn't something unique to my environment

**Comment by freddyaboulton** [comment]
Hi @1lint ! Can you set `show_progress=False` like this `demo.load(refresh_display, [], [board, events], every=10, show_progress=False)`

**Comment by freddyaboulton** [comment]
Cool - no rush!

**Comment by 1lint** [comment]
@freddyaboulton that worked, thanks!! now the grid can be modified and the load event runs every 10 seconds
