### ISSUE TITLE
Use same type across single and multiple file_count cases in File

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#4151]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As we've developed the clients, we found it hard to provide accurate type info for the File component across the single and multiple file cases.

This is because the the file serializer technically accepts both list and single item inputs, but the file component only accepts one or the other. 

We've also seen issues (#4019) where users are confused that the data their function handler receives changes across the two cases.

**Describe the solution you'd like**  
Use a list across the single and multiple file_count cases. 

**Additional context**

**Comment by Ali7040** [comment]
Hello,

I would like to express my interest in working on the issue at hand and kindly request to be assigned to it. I believe I can contribute positively towards resolving the problem and would greatly appreciate the opportunity to do so.

Looking forward to actively participating in the open source community and making a meaningful impact.

**Comment by freddyaboulton** [comment]
Hi @Ali7040 !

this would technically be a breaking change so we don’t want to work on it right now.

If there is another issue that catches your attention, we would be happy for you to work on it!

**Comment by freddyaboulton** [comment]
This is done via the `data_model` concept in `v4`. If `type="multiple"` the api_info will use a list. If `single` it will not!.
