### ISSUE TITLE
Gradio Dropdown paramters allow_custom_values not working 

### ISSUE THREAD

**Issue by LucasJ1906** [gradio-app/gradio#4154]
### Describe the bug

Using the paramter "allow_custom_values " in a gradio.Dropdown lead to a warning : 

`UserWarning: You have unused kwarg parameters in Dropdown, please remove them: {'allow_custom_values': True}`

Morever the the feature seems not wokings, since it is not possible to enter new value even when the parameter is a True. 

You can reproduce the issue here : 
[https://colab.research.google.com/github/gradio-app/gradio/blob/main/demo/sentence_builder/run.ipynb#scrollTo=2.8891853944186117e%2B38](https://colab.research.google.com/github/gradio-app/gradio/blob/main/demo/sentence_builder/run.ipynb#scrollTo=2.8891853944186117e%2B38)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://colab.research.google.com/github/gradio-app/gradio/blob/main/demo/sentence_builder/run.ipynb#scrollTo=2.8891853944186117e%2B38

### Logs

```shell
`UserWarning: You have unused kwarg parameters in Dropdown, please remove them: {'allow_custom_values': True}`
```

### System Info

```shell
last version of gradio installed with pip, test on a google colab and on desktop running wsl in venv.
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @LucasJ1906, the parameter name is actually: "allow_custom_value" (singular)
