### ISSUE TITLE
Image component collapses with source-'webcam' and tool='color-sketch' after v3.24.0

### ISSUE THREAD

**Issue by yvrjsharma** [gradio-app/gradio#4159]
### Describe the bug

The image component collapses on itself when one uses the source as 'webcam and the tool as 'color-sketch.' This works as expected until the Gradio version 3.24.0 (as you can see from my sample video file attached), but not after that.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
!pip uninstall gradio

!pip install gradio==3.24.0 

import gradio as gr
import numpy as np

def flip(im):
  if im is not None:
    return np.flipud(im) 
  else:
    return gr.update(value=None)

demo = gr.Blocks()

with demo:
  with gr.Row():
      with gr.Column():
        camera = gr.Image(source="webcam", tool="color-sketch")
        
        with gr.Row():
          btn = gr.Button("flip")
          btn2 = gr.Button("clear")
      with gr.Column():
        image = gr.Image()
  
  btn.click(fn=flip, inputs=[camera], outputs=[image])
  camera.change(fn=flip, inputs=[camera], outputs=[image])
  btn2.click(lambda :gr.update(value=None), [], camera)
  btn2.click(lambda :gr.update(value=None), [], image)

  gr.Examples([
      ["/content/cat1.jpg"],
       ["/content/dog1.jpg"]], 
       inputs=camera,)

demo.launch(share=True, height=1000) 
```

### Screenshot

https://github.com/gradio-app/gradio/assets/48665385/5f4b4a3b-ca5f-456b-a3ec-c646dd009862

### Logs

```shell
No error log is produced when the Image component collapses.
```

### System Info

```shell
Please note that I have tried this myself only on Google Colab.
```

### Severity

annoying

**Comment by pngwn** [comment]
This is bad. Will pick it up soon.

**Comment by pngwn** [comment]
I've removed this from the 3.x milestone as we discussed.

**Comment by metal3d** [comment]
Actually it's the case even without "tool" too. When I capture the image, the component collapse. If I force the heigh afterward (via devtools in browser) the image appears.

**Comment by metal3d** [comment]
Oh... removing the "overflow: hidden" on the component div is OK

**Comment by metal3d** [comment]
Added this CSS:
```css
div.block:has(.image-container) {
  min-height: 2em;
}
```

Fixed the problem
