### ISSUE TITLE
 Issue with real-time retrieval of state object value in submit click event

### ISSUE THREAD

**Issue by RuSignalFlag** [gradio-app/gradio#4169]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I'm trying to build a chatbot application using Gradio. In this application, I want to dynamically call different callback functions in the submit click event based on the value of the 'stream' checkbox. However, I'm facing an issue where I can't retrieve the real-time value of the 'stream' checkbox in the submit click event. It always returns the initial value instead of the updated value.

To address this issue, I attempted to instantiate the 'stream' checkbox as a state object and update its value whenever the checkbox value changes. I then planned to use the value of the state object to determine which callback function to call in the submit click event. However, this approach didn't work either. The retrieved value in the submit click event remained the initial value, even though it had been changed.

I would appreciate if someone could shed light on the cause of this problem and provide a solution. Thank you.
**Describe the solution you'd like**  
I want to dynamically call different callback functions in the submit click event based on the value of the 'stream' checkbox.

**Additional context**  
Code Example:
def update_stream_state(stream):
    stream_state.value = stream
    print(stream_state.value)
    print(stream_state)
 
with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    with gr.Row():
        with gr.Column(scale=4):
            with gr.Column(scale=12):
                user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=15).style(container=False)
            with gr.Column(min_width=32, scale=1):
                submitBtn = gr.Button("Submit", variant="primary")
         with gr.Column(scale=1):
                 stream = gr.inputs.Checkbox(label="stream", default=False)
    history = gr.State([])
    stream_state = gr.State(False)
    stream.change(update_stream_state, inputs=[stream])
    submitBtn.click(**chat_stream if stream_state.value else chat**, [user_input, chatbot, max_length, top_p, temperature, history, conversation_turn], [chatbot, history], show_progress=True)
    submitBtn.click(reset_user_input, [], [user_input])

**Comment by abidlabs** [comment]
Hi @RuSignalFlag thanks for creating the issue, could you please share your code in with proper Markdown formatting so that we can run it on our end?

**Comment by RuSignalFlag** [comment]
@abidlabs Sure! Here is a code example.

```
import gradio as gr


def chat(user_input, chatbot):
    print("The call function is chat which should be called when stream_state is False")
    print("The function has been called and the stream_state value is: " + str(stream_state.value)+ "\n")

def chat_stream(user_input, chatbot):
    print("The call function is chat_stream which should be called when stream_state is True")
    print("The function has been called and the stream_state value is: " + str(stream_state.value)+ "\n")

def update_stream_state(stream):
    stream_state.value = stream
    print("The stream state has been updated: " + str(stream_state.value)+ "\n")

with gr.Blocks() as demo:

    chatbot = gr.Chatbot()
    with gr.Row():
        with gr.Column(scale=4):
            with gr.Column(scale=12):
                user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=15).style(
                    container=False)
            with gr.Column(min_width=32, scale=1):
                submitBtn = gr.Button("Submit", variant="primary")
        with gr.Column(scale=1):
            stream = gr.inputs.Checkbox(label="stream", default=False)

    stream_state = gr.State(False)

    stream.change(update_stream_state, inputs=[stream])

    submitBtn.click(chat_stream if stream_state.value else chat, [user_input, chatbot], [chatbot],show_progress=True)
    
demo.queue().launch(share=False, inbrowser=True)
```

The most important thing in this is within the submit click event. 
I want to control which callback function should be invoked by the updated real value of stream_state. However, it doesn't work as expected. Regardless of whether the value of stream_state is changed or not, the value obtained in the submit click event handler is always the initial value. I'm not sure if there's any issue in implementing this logic within the Gradio framework as I don't have experience in this aspect. Below is a screenshot of the console output during my testing.

<img width="518" alt="1683867205368" src="https://github.com/gradio-app/gradio/assets/78648337/6bc28ce5-8946-45b9-a78c-ea44187cefd4">

**Comment by freddyaboulton** [comment]
Hi @RuSignalFlag !

To access the current value of a component or state in an app, you need to pass it as input to your event handler function. Accessing .value will not show the latest value.

Also in `update_stream_state` you should `return` the new value of the state.

I don't think you need a state variable though, you can do what you originally intended (determine which function to call depending value of the 'stream' checkbox) by passing the `stream` checkbox as an input to the event handler function.

Something like this should work:

```python
def chat_handler(stream, user_input, chatbot):
    if stream:
        return chat_stream(user_input, chatbot)
    else:
        return chat(user_input, chatbot)

submitBtn.click(chat_handler, [stream, user_input, chatbot], [chatbot], show_progress=True)
```

**Comment by abidlabs** [comment]
+1 to @freddyaboulton's answer. As this is not a feature request or bug report, I'll close this issue
