### ISSUE TITLE
Markdown Formatting In gr.Dataset Lost After Update

### ISSUE THREAD

**Issue by jeffthebear** [gradio-app/gradio#4171]
### Describe the bug

We start with a `gr.Dataset` with the `components=['markdown']` and `samples` set but after an event that updates the samples in the dataset the display looks like it lost the markdown formatting and is formatted as if `components=['text']`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr

data = [['hello\n**md**']]

def btn_click():
  return [['changed to\n**not md**']]

with gr.Blocks() as demo:
  with gr.Row():
    dataset = gr.Dataset(components=['markdown'], type='index', samples=data, label='Results')
    btn = gr.Button("btn")

  btn.click(fn=btn_click, inputs=[], outputs=[dataset])

demo.launch()

### Screenshot

<img width="505" alt="before_click" src="https://github.com/gradio-app/gradio/assets/1319326/db08f10d-0d61-42aa-bfe3-b19dfe54c3e9">
<img width="505" alt="after_click" src="https://github.com/gradio-app/gradio/assets/1319326/3dbf84b7-e5af-4075-9024-8b5ec14cad43">

### Logs

```shell
No error in stacktrace, it is seen in the UI.
```

### System Info

```shell
gradio: 3.29.0
os: MAC OS 13.3.1
browser: Chrome Version 113.0.5672.63
```

### Severity

annoying

**Comment by abidlabs** [comment]
Same as #4509. I'll close this issue as that one has an easier to follow repro.
