### ISSUE TITLE
More documentation is needed on how to use `gradio_client` with multi-turn dialogue with history

### ISSUE THREAD

**Issue by lychees** [gradio-app/gradio#4175]
- [x] I have searched to see if a similar issue already exists.

I am trying to use ChatGLM with gradio_client to do some research, but soon found that it doesn't support multi-turn dialogue like the original app. Below is my implementation:

```
def predict(input, history=None):
    if history is None:
        history = []
 
    client = Client('https://multimodalart-chatglm-6b.hf.space/')
    with open(client.predict(input, fn_index=0)) as f: 
        text = process_text(f.read())
        output = json.loads(text)[0]
        history += [output]
        return history, history
```

Since we remove state from the API recently, [4107](https://github.com/gradio-app/gradio/pull/4107), I thought it could be impossible to support multi-turn dialogue, is that true?

**Comment by abidlabs** [comment]
I think we can document this better, so I'll reframe this issue around that
