### ISSUE TITLE
Interactive value not respected for interface output component

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#4183]
### Describe the bug

Setting an output textbox as interactive does not make it interactive

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs=gr.Textbox(interactive=True))
demo.launch()
```

You can work around this by setting `interactive=True` from a `gr.update`

### Screenshot

![interactive_textbox](https://github.com/gradio-app/gradio/assets/41651716/00307ab0-3e95-4270-9069-a75d5753084a)

### Logs

```shell
-
```

### System Info

```shell
3.29.0
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
This is expected behavior as we force all outputs to be non-interactive. Are there use cases where this is not desired?

**Comment by freddyaboulton** [comment]
Someone asked on discord about this. 

I think it’s fine if gr.Textbox() is none interactive but feels weird that gr.Textbox(interactive=True) is ignored.

there’s a workaround so this is low priority for me.

**Comment by yvrjsharma** [comment]
I'd feel the same. After setting interactive=True, one would expect an element to act that way.

**Comment by pngwn** [comment]
Yeah this should be the behaviour. non-inputs are `interactive=False` by default but we should always be respecting explicit kwargs.

**Comment by abidlabs** [comment]
Sounds good, we have a nice use case for this here: https://github.com/gradio-app/gradio/issues/4327

PR open: https://github.com/gradio-app/gradio/pull/4356
