### ISSUE TITLE
[Suggestions] Don't autofind a port when a port is user specified

### ISSUE THREAD

**Issue by Narsil** [gradio-app/gradio#419]
**Is your feature request related to a problem? Please describe.**

When using `iface = gr.Interface(.., server_port=5000)` if port `5000` is already used it will use port `5001` instead.

**Describe the solution you'd like**

If it could crash instead that would be better saying the port is already used.

**Additional context**
This was an issue when reloading regularly the gradio app and reloading pages on the browser

**Comment by abidlabs** [comment]
Makes sense, we'll fix it!
