### ISSUE TITLE
Folder/bulk upload as input (or zip upload); Encryption of upload

### ISSUE THREAD

**Issue by maximilianpfau** [gradio-app/gradio#42]
Dear Abubakar Abid,

thank you for your great work.

Two questions:

1. Is there an upload option for multiple files (drag-and-drop) or a complete folder (native or zipped) planned?

The application would be an XML-export of volumetric image data (i.e., multiple *.tiff files and an XML file with the meta data).

2. Is the upload secure (i.e., 128-bit SSL encryption) or will this be implemented in future versions?

Many thanks,
Maximilian

**Comment by abidlabs** [comment]
Hi Maximilian, thank you for the feature suggestion. We are planning on building out a bulk upload feature, though it is somewhat down the product roadmap. Would you be open to a short conversation where we discuss your specific use case? It would help us build out the feature better. Shoot me an email at: team@gradio.app

**Comment by maximilianpfau** [comment]
Thank you. I have just sent you an email!
