### ISSUE TITLE
Document that `gr.Chatbot()` can be used as an input component

### ISSUE THREAD

**Issue by sahil-lalani** [gradio-app/gradio#4209]
I'm trying to build a chatbot app with authentication and want to add a feature where whenever the user starts a new conversation, the old conversation is saved so the user can look back at previous conversations

I was trying to see if chat history can be passed to gr.Chatbot, but this isn't the case as the gr.Chatbot component does not accept input. I'm wondering if this feature can be added for increased functionality.

**Comment by abidlabs** [comment]
Hi @sahil-lalani good question! So you _can_ actually pass in history to the `gr.Chatbot` component. The docs for the `Chatbot` component need to be updated to show how to pass in inputs, but here's an example that illustrates your use case:

```py
import gradio as gr
import random

def respond(message, chat_history):
    bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
    chat_history.append((message, bot_message))
    return "", chat_history

with gr.Blocks() as demo:
    saved_chat = gr.State()
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    with gr.Row():
        clear = gr.Button("Save & Clear")
        load = gr.Button("Load")
    
    msg.submit(respond, [msg, chatbot], [msg, chatbot])
    clear.click(lambda x: (x, None), chatbot, [saved_chat, chatbot])
    load.click(lambda x:x, saved_chat, chatbot)
    
demo.launch()
```

**Comment by abidlabs** [comment]
I'll reframe this issue to be about fixing up the documentation for `gr.Chatbot`

**Comment by sahil-lalani** [comment]
Thanks so much for your help, currently attempting to modify your solution for my exact needs. I'm assuming that only states can be passed into the chatbot and not lists or strings, correct? I've tried passing in lists but they don't seem to be working, so I just wanted to clarify. Thanks.

**Comment by AltayYuzeir** [comment]
Hello, I am new to the Gradio platform. I am wondering if it is possible to extract the prompts and responses from State, save the chat history as json, or csv, and later upload said json/csv during new session, pass it on to the State and restore the past conversation? I came up with a system where I use global data frame, where each prompt and response is saved in 2 columns, and the user can download it with button press using link, but the Reload, Undo and Clear buttons are not impacting the data frame. I cannot wrap my head around the State and how to extract data from the 2 parts - prompts and responses or pass data to them. I am working with the build-in ChatInterface. Maybe I need the more flexible Blocks with Chatbot?
```python
def random_response(message, chat_history):
    bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
    #chat_history.append((message, bot_message))
    global df
    df.loc[len(df)+1] = [message, bot_message]
    df.to_csv("conversation.csv", index=False)
    return bot_message
```
