### ISSUE TITLE
Dropdown is not properly updated when changing the reference.

### ISSUE THREAD

**Issue by Symbiomatrix** [gradio-app/gradio#4210]
### Describe the bug

When a dropdown's choice list is updated using gr.update(choices = newlist), attempting to access any new items (or at least every new item beyond the first addition, for some inexplicable reason) will cause a valueerror as if it does not exist.
It seems that if a global variable is maintained and updated, new items will be just fine.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

#items = ["Item 1", "Item 2", "Item 3"]
items = ["Item 1"]

def add_item():
    global items
    new_item = f'Item {len(items) + 1}'
    items.append(new_item)
    items = items.copy() # SEE NOTE
    return gr.update(choices = items)

def print_item(item):
    print("Selected", item)

with gr.Blocks() as demo:
    with gr.Row():
        dropd = gr.Dropdown(label="Dynamic dropdown", choices = items, type="index")
    with gr.Row():
        btnadd = gr.Button(value = 'Add item')
    with gr.Row():
        btnprt = gr.Button(value = 'Print item')
    btnadd.click(fn = add_item, inputs = [], outputs = [dropd])
    btnprt.click(fn = print_item, inputs = [dropd], outputs = [])

if __name__ == "__main__":
    demo.launch()
```

1) Press "add item" twice or more.
2) Select item 3+.
3) Press print.
4) Error.
5) Items 1/2 will print index correctly.

If "SEE NOTE" line is commented, I'm getting no error for any number of items.

### Logs

```shell
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\gradio\routes.py", line 338, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Python38\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Python38\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\Python38\lib\site-packages\gradio\components.py", line 1282, in preprocess
    return self.choices.index(x)
ValueError: 'Item X' is not in list
```

### System Info

```shell
Gradio = '3.16.2'
OS = Windows 10
Browser = Chrome
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @Symbiomatrix you are correct. This is actually a larger bug that we are planning on fixing in 4.0, as it will require some significant changes. If you'd like to ensure that this use case is covered, please chime into this issue: https://github.com/gradio-app/gradio/issues/1566
