### ISSUE TITLE
ImportError: cannot import name 'themes' from partially initialized module 'gradio'

### ISSUE THREAD

**Issue by BlacKnightZer0** [gradio-app/gradio#4213]
### Describe the bug

I've been trying to get Oobabooga Text Generation WebUI working, but I encountered this problem at the end of the process. I have already tried to update gradio to the latest version using "pip install -U gradio" , but the problem is unchanged. Below is the traceback code that is generated when I try to run the start_windows.bat file in the Oobabooga folder. If this is a bug I should pose to the Oobabooga developer instead, please tell me so, however, it seems to me that the problem lies with gradio being only partially initialized.

INFO:Gradio HTTP request redirected to localhost :)
Traceback (most recent call last):
  File "C:\Users\danie\Downloads\oobabooga_windows\text-generation-webui\server.py", line 21, in <module>
    import gradio as gr
  File "C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\components.py", line 53, in <module>
    from gradio.blocks import Block, BlockContext
  File "C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 25, in <module>
    from gradio import (
ImportError: cannot import name 'themes' from partially initialized module 'gradio' (most likely due to a circular import) (C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\__init__.py)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

@echo off

cd /D "%~dp0"

echo "%CD%"| findstr /C:" " >nul && echo This script relies on Miniconda which can not be silently installed under a path with spaces. && goto end

set PATH=%PATH%;%SystemRoot%\system32

@rem fix failed install when installing to a separate drive
set TMP=%cd%\installer_files
set TEMP=%cd%\installer_files

@rem config
set INSTALL_DIR=%cd%\installer_files
set CONDA_ROOT_PREFIX=%cd%\installer_files\conda
set INSTALL_ENV_DIR=%cd%\installer_files\env
set MINICONDA_DOWNLOAD_URL=https://repo.anaconda.com/miniconda/Miniconda3-py310_23.1.0-1-Windows-x86_64.exe
set conda_exists=F

@rem figure out whether git and conda needs to be installed
call "%CONDA_ROOT_PREFIX%\_conda.exe" --version >nul 2>&1
if "%ERRORLEVEL%" EQU "0" set conda_exists=T

@rem (if necessary) install git and conda into a contained environment
@rem download conda
if "%conda_exists%" == "F" (
	echo Downloading Miniconda from %MINICONDA_DOWNLOAD_URL% to %INSTALL_DIR%\miniconda_installer.exe

	mkdir "%INSTALL_DIR%"
	call curl -Lk "%MINICONDA_DOWNLOAD_URL%" > "%INSTALL_DIR%\miniconda_installer.exe" || ( echo. && echo Miniconda failed to download. && goto end )

	echo Installing Miniconda to %CONDA_ROOT_PREFIX%
	start /wait "" "%INSTALL_DIR%\miniconda_installer.exe" /InstallationType=JustMe /NoShortcuts=1 /AddToPath=0 /RegisterPython=0 /NoRegistry=1 /S /D=%CONDA_ROOT_PREFIX%

	@rem test the conda binary
	echo Miniconda version:
	call "%CONDA_ROOT_PREFIX%\_conda.exe" --version || ( echo. && echo Miniconda not found. && goto end )
)

@rem create the installer env
if not exist "%INSTALL_ENV_DIR%" (
  echo Packages to install: %PACKAGES_TO_INSTALL%
  call "%CONDA_ROOT_PREFIX%\_conda.exe" create --no-shortcuts -y -k --prefix "%INSTALL_ENV_DIR%" python=3.10 || ( echo. && echo Conda environment creation failed. && goto end )
)

@rem check if conda environment was actually created
if not exist "%INSTALL_ENV_DIR%\python.exe" ( echo. && echo Conda environment is empty. && goto end )

@rem activate installer env
call "%CONDA_ROOT_PREFIX%\condabin\conda.bat" activate "%INSTALL_ENV_DIR%" || ( echo. && echo Miniconda hook not found. && goto end )

@rem setup installer env
call python webui.py

echo.
echo Done!

:end
pause

### Screenshot

![Screenshot 2023-05-14 223452](https://github.com/gradio-app/gradio/assets/133618052/47370df7-257c-4f1c-826e-1c8ab384656e)

### Logs

```shell
INFO:Gradio HTTP request redirected to localhost :)
Traceback (most recent call last):
  File "C:\Users\danie\Downloads\oobabooga_windows\text-generation-webui\server.py", line 21, in <module>
    import gradio as gr
  File "C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\components.py", line 53, in <module>
    from gradio.blocks import Block, BlockContext
  File "C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 25, in <module>
    from gradio import (
ImportError: cannot import name 'themes' from partially initialized module 'gradio' (most likely due to a circular import) (C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio\__init__.py)
```

### System Info

```shell
Gradio version v3.30.0
Windows 11
Mozilla Firefox
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @BlacKnightZer0 does this happen even if you create a regular Gradio app? E.g. if you open up Python and enter in:

```py
import gradio as gr

gr.Interface(lambda x:x, "textbox", "textbox").launch()
```

**Comment by BlacKnightZer0** [comment]
No, it doesn't happen when I create a regular Gradio app. I pasted in the code you provided and this is the result:

Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gradio as gr
>>>
>>> gr.Interface(lambda x:x, "textbox", "textbox").launch()
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by abidlabs** [comment]
Then it looks like this is an issue with the Oobabooga Text Generation WebUI, no? I would suggest opening an issue there unless you are able to create a minimal example where this fails with a generic Gradio app

**Comment by BlacKnightZer0** [comment]
Okay, thank you. But if you could answer one more question for me please, do you know what it means by a "circular import"? On this line specifically:

ImportError: cannot import name 'themes' from partially initialized module 'gradio' (most likely due to a circular import) (C:\Users\danie\Downloads\oobabooga_windows\installer_files\env\lib\site-packages\gradio_init_.py)

**Comment by abidlabs** [comment]
Circular import basically means that there's two files both importing each other. It looks like this "gradio_init.py" is trying to import themes before it imports gradio or something like that
