### ISSUE TITLE
gr.Image show Image can flash all the time

### ISSUE THREAD

**Issue by futureflsl** [gradio-app/gradio#4214]
### Describe the bug

gr.Image show Image can flash all the time

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

image_input = gr.Image(source='webcam')
image_output = gr.Image()
camera_in.change(deal_frame, inputs=camera_in, outputs=camera_output)
def deal_frame(im):
    cv2.putText(im, 'this is a test', (25, 25), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 0, 0), 3)
    return im

### Screenshot

![360截图20230515143302925](https://github.com/gradio-app/gradio/assets/23259315/5b726119-fcc3-4887-9465-d073a8d53166)

### Logs

```shell
demo.queue(concurrency_count=5).launch(server_port=5200, share=False)
```

### System Info

```shell
win10 x64
gradio==3.12.0
```

### Severity

annoying

**Comment by abidlabs** [comment]
This is the same as #3938, I believe. Please add your case to that issue so that we can ensure that we close both

**Comment by blre6** [comment]
you can set show_progress=False. 

> camera_in.change（deal_frame， inputs=camera_in， outputs=camera_output,show_progress=False）

This turns off loading animations and the picture no longer flickers
