### ISSUE TITLE
Safari wont play audio files on gradio but record them (based on Safari Developer tools feedback)

### ISSUE THREAD

**Issue by Alanp777** [gradio-app/gradio#4224]
### Describe the bug

Try running any gradio app and playback some audio, from the developer tools it shows "The resource was requested insecurely" and it wont allow the playback but it will allow the recording though

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Any gradio app

### Screenshot

<img width="1440" alt="image" src="https://github.com/gradio-app/gradio/assets/132757923/91d89b68-c782-4c04-a642-f205bda83c62">

### Logs

```shell
as shown on the logs from developer tools in SAFARI
```

### System Info

```shell
Safari latest version
```

### Severity

annoying

**Comment by abidlabs** [comment]
I believe this might be the same as #2987?

**Comment by abidlabs** [comment]
Ok in that case, let's close this issue. Feel free to chime into the other issue with these details
