### ISSUE TITLE
Getting-Started Doc "Using State" paragraph doesn't use CSS from code

### ISSUE THREAD

**Issue by mandubian** [gradio-app/gradio#423]
In https://gradio.app/getting_started/, paragraph about "Using State" doesn't use CSS and renders badly.

**To Reproduce**
1. Go to https://gradio.app/getting_started/
2. Scroll down to "Using State"

Code should be 
```
    html = """<div class="chatbox">"""
    for user_msg, resp_msg in stances:
        html += f"""<div class="user_msg">{user_msg}</div>"""
        html += f"""<div class="resp_msg">{resp_msg}</div>"""
    html += "</div>"
```

**Comment by abidlabs** [comment]
Thanks @mandubian! @aliabid94 is the website not running from the latest version on `master`? Because the code here: https://github.com/gradio-app/gradio/blob/master/demo/chatbot/run.py looks fine.

**Comment by abidlabs** [comment]
Discussed and it seems it's because <html> code doesn't render correctly inside the <code> tags. Can someone look into this?

**Comment by abidlabs** [comment]
It also is out of date given how we do state now

**Comment by abidlabs** [comment]
Fixed now. Thanks @mandubian!
