### ISSUE TITLE
When an event updates a dropdown, the associated event is not triggered

### ISSUE THREAD

**Issue by oobabooga** [gradio-app/gradio#4239]
### Describe the bug

If a dropdown has a `dropdown.change` event attached to it and another event updates the dropdown, `dropdown.change` is not triggered.

This happens in `gradio==3.30.0` but not `gradio==3.25.0`. It prevents me from updating to the latest version as my UI depends heavily on these chained events.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr
import time

with gr.Blocks() as interface:
    dropdown = gr.Dropdown(choices=["Anna", "Christine", "Phoebe"])
    btn = gr.Button("Trigger!")

    btn.click(lambda: "Phoebe", None, dropdown)
    dropdown.change(lambda x: print(x), dropdown, None)

interface.queue()
interface.launch()
```

Launch the interface above and click on "Trigger!". The name "Phoebe" should be printed in the terminal.

### Logs

```shell
No errors are printed
```

### System Info

```shell
gradio==0.30.0, Linux
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Hi @oobabooga interesting we did we have this issue, but it should have been fixed in `gradio==3.30.0`. Let me look into it

**Comment by abidlabs** [comment]
Ok you're right, it's broken on 3.30 but it's fixed on `main`. We'll do a release soon.

Colab showing it's fixed on main: https://colab.research.google.com/drive/13jh2SzYxU04J4NnvlPGUCYKW2WGXd254?usp=sharing

**Comment by oobabooga** [comment]
Thank you!!
