### ISSUE TITLE
Gradio queue function not work at windows 2019 server powershell

### ISSUE THREAD

**Issue by tianlichunhong** [gradio-app/gradio#4243]
### Describe the bug

show erro in the web page. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr
import sys
class Logger:
    def __init__(self, filename):
        self.terminal = sys.stdout
        self.log = open(filename, "w")

    def write(self, message):
        self.terminal.write(message)
        self.log.write(message)

    def flush(self):
        self.terminal.flush()
        self.log.flush()

    def isatty(self):
        return False
sys.stdout = Logger("output.log")
def test(x):
    print("This is a test")
    print(f"Your function is running with input {x}...")
    return x

def read_logs():
    sys.stdout.flush()
    with open("output.log", "r") as f:
        return f.read()
with gr.Blocks() as demo:
    with gr.Row():
        input = gr.Textbox()
        output = gr.Textbox()
    btn = gr.Button("Run")
    btn.click(test, input, output)

    logs = gr.Textbox()
    demo.load(read_logs, None, logs, every=1)

demo.queue().launch()

### Logs

```shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Task exception was never retrieved
future: <Task finished name='74u3hieboyy_1' coro=<Queue.process_events() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py:343> exception=ValueError('[<gradio.queueing.Event object at 0x000001BD29154610>] is not in list')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 432, in process_events
    self.active_jobs[self.active_jobs.index(events)] = None
ValueError: [<gradio.queueing.Event object at 0x000001BD29154610>] is not in list
```

### System Info

```shell
Windows 2019 powershell
```

### Severity

annoying

**Comment by tianlichunhong** [comment]
not only this code not work, any code with demo.queue() does not work. without  demo.queue(), it works fine.

**Comment by freddyaboulton** [comment]
Hi @tianlichunhong ! What version of gradio are you using?

**Comment by abidlabs** [comment]
I'll go ahead and close this for lack of follow up. But if you are able to provide a clear repro @tianlichunhong, feel free to reopen

**Comment by tianlichunhong** [comment]
sorry for late reply. I mean set windows proxy is like that:
![img_589cc490d7dd5](https://github.com/gradio-app/gradio/assets/13270039/7d2b2323-3ba8-4494-86d3-0337ac746d7f)

When I set the proxy, and in my python, use demo.queue() , and run gradio. it can run, but input text, and summit, then after about 10s, show the error.
When I remove the proxy for windows. All run fine.

**Comment by abidlabs** [comment]
Thanks @tianlichunhong I'll reopen so that we can take a look at this

**Comment by abidlabs** [comment]
Hi @tianlichunhong I don't think we can solve this on our end. Probably the Windows LAN proxy you are using does not support websockets. Sometimes, there are proxies that don't support websockets for "security reasons": https://stackoverflow.com/questions/9612690/websockets-and-a-proxy
