### ISSUE TITLE
button clickable during action click already did, no way to block, user ends up clicking madly and breaking things.

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#4245]
### Describe the bug

Related to https://github.com/gradio-app/gradio/issues/3382

But in this case, just any button, like submit any clickable button never changes state.  If the task is non-trivial that is performed and takes time, like processing documents, then the user ends up clicking that button over and over again.  This ends up queuing a bunch of redundant tasks.

Adding the button to the output of its own click has no effect, but that works for text boxes when entering text.  So I'm just asking for buttons to behave the same way as text boxes so one cannot re-click over and over because there's no feedback.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just click any button and have it sleep for a while, then you'll see no idea what is going on from UI perspective.  So user will probably click many times.  That ends up queuing many tasks and that is totally unexpected.   Just due to poor UI UX.

Severity is marked as blocking all usage, since for the purpose of clicking to do any non-trivial task, the behavior is not possible to work with.

I know of no workaround, but wish there was.  Please tell me!

### Logs

```shell
NA
```

### System Info

```shell
Successfully installed gradio-3.31.0 gradio_client-0.2.5
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @pseudotensor I can't reproduce this issue. If you have a button and click on it multiple times, Gradio only launches a single event. This is the case with _all_ Gradio events right now. 

You can use this code to test:

```py
import gradio as gr
import time

def test(x):
    print("entered fn")
    time.sleep(5)
    return x

with gr.Blocks() as demo:
    t1 = gr.Textbox()
    t2 = gr.Textbox()
    btn = gr.Button()
    
    t1.submit(test, t1, t2)
    btn.click(test, t1, t2)
    
demo.queue().launch()
```

Whether I do the t1.submit() event or I do the btn.click() event, the "entered fn" line only gets printed once even if I  trigger the event multiple times. Am I missing something?

**Comment by abidlabs** [comment]
Will close for now, until we have clarity here
