### ISSUE TITLE
parallel or multiprocessing events support?

### ISSUE THREAD

**Issue by okideal** [gradio-app/gradio#4248]
- [x] I have searched to see if a similar issue already exists.

I expect gradio to be used for processing of data in format of rows. Currently I'm linking a button **click** to all row interactions function **func**, but when debug I found that **func** is executed in a particular sequential order, is there any way to make all **func** executions in parallel and set the maximum number of parallelism?

**Additional context**  
demo part
```python
with ... as demo():
    ...
    for i in range(row_counts):
        button.click(partial(func, row_idx=idx)
```
with some sample code above, I expect that the gradio could run the func in parallel when I click the button

Thanks in advance

**Comment by freddyaboulton** [comment]
Hi @okideal - gradio will execute all the events asynchronously by default. The only exception is if you have the queue enabled with `concurrency_count=1`. 

So if you are using the queue, make sure you do `demo.queue(concurrency_count=<desired-number>).launch(....)`

**Comment by abidlabs** [comment]
That should answer the question. By the way, in the future, for general questions like this (that are not feature requests or bug reports), please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
