### ISSUE TITLE
Allow switching between webcams

### ISSUE THREAD

**Issue by tczhanglele** [gradio-app/gradio#4252]
how to switch webcam if i have two?

**Comment by pngwn** [comment]
Currently you need to do this in your browser settings, there isn't a way to control this from within gradio. There is an open PR to support to support the front facing camera on mobile, but we don't have any support for choosing arbitrary cameras.

Will look into this.

**Comment by tczhanglele** [comment]
thanks, now how to use rear camera on mobile?
