### ISSUE TITLE
Debug via PyCharm

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#4253]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
[Derek](https://huggingface.co/derek-thomas) likes debugging via PyCharm and gradio does not work nicely with PyCharm (need to repro). In contrast, streamlit works very well with PyCharm.

Filing this as nice-to-have for 4.0.

**Describe the solution you'd like**  

**Additional context**

**Comment by caopulan** [comment]
Is there anything updated? Debugging by pycharm is really a important feature for us.

**Comment by freddyaboulton** [comment]
Hi @caopulan !

I filed this issue based on some feedback but I didn't actually test whether it works. I think this currently works. In the attached video I am able to set a breakpoint via pycharm and run it in "Debug" mode by right clicking on the file and selecting the debug option.

Can you please confirm?

https://github.com/gradio-app/gradio/assets/41651716/42410531-e2d2-4421-b70b-54e338c1a95d

**Comment by freddyaboulton** [comment]
I just tested that this works with reload mode. You have to add a new run configuration to PyCharm. I'm attaching my run configuration here but you need to change the `Script Path` to point to where the gradio command is installed (`which gradio` in the command line) as well as the `Working Directory` to be the directory where you are running the script from (your project root).

<img width="728" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/acf830be-7c47-4446-8905-3a08cdc93193">

gradio.run.xml
```
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="gradio" type="PythonConfigurationType" factoryName="Python">
    <module name="gradio" />
    <option name="INTERPRETER_OPTIONS" value="" />
    <option name="PARENT_ENVS" value="true" />
    <option name="SDK_HOME" value="$USER_HOME$/miniconda3/envs/gradio-dev/bin/python" />
    <option name="WORKING_DIRECTORY" value="$PROJECT_DIR$" />
    <option name="IS_MODULE_SDK" value="false" />
    <option name="ADD_CONTENT_ROOTS" value="true" />
    <option name="ADD_SOURCE_ROOTS" value="true" />
    <option name="SCRIPT_NAME" value="$USER_HOME$/miniconda3/envs/gradio-dev/bin/gradio" />
    <option name="PARAMETERS" value="$FilePathRelativeToProjectRoot$" />
    <option name="SHOW_COMMAND_LINE" value="false" />
    <option name="EMULATE_TERMINAL" value="false" />
    <option name="MODULE_MODE" value="false" />
    <option name="REDIRECT_INPUT" value="false" />
    <option name="INPUT_FILE" value="" />
    <method v="2" />
  </configuration>
</component>
```

Reload mode and breakpoints are respected!

**Comment by dwipper** [comment]
@freddyaboulton I'm trying to set up PyCharm, and the debugger isn't working. It just shows the "Running on local" message and doesn't seem to run the code or stop at the breakpoint I set:
![image](https://github.com/gradio-app/gradio/assets/140648761/f19b0003-ef90-42e4-b8ca-f5a4e056175b)

Here's my config file. It doesn't have a Script Path option:
![image](https://github.com/gradio-app/gradio/assets/140648761/69d1eb34-6203-49d8-96dd-20c8aef465a6)
