### ISSUE TITLE
Links in dark mode are a bit hard to read

### ISSUE THREAD

**Issue by merveenoyan** [gradio-app/gradio#4261]
- [x] I have searched to see if a similar issue already exists.

This very popular Space: https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard has links inside dataframe but they're very hard to read, it would be better to increase brightness and decrease saturation of link colors in base theme. WDYT? See below. 
<img width="723" alt="Screenshot 2023-05-18 at 08 43 37" src="https://github.com/gradio-app/gradio/assets/53175384/2e93ddb8-d6a2-42bb-a3d8-0cda849cb367">

**Comment by abidlabs** [comment]
Agreed. I think they should be the same color as the links in the Markdown above

**Comment by abidlabs** [comment]
It looks like the issue has since been fixed @merveenoyan:

https://huggingfaceh4-open-llm-leaderboard.hf.space/?__theme=dark

<img width="1313" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/da4ec8e6-c5bf-4c68-99c4-7f0d3d1ab9c6">
