### ISSUE TITLE
gradio.Error() broken with queue enabled

### ISSUE THREAD

**Issue by CuriousDolphin** [gradio-app/gradio#4263]
### Describe the bug

Hi, error raised by gr.Error() are not displayed into popup and this cause infinite loading of output block.

In 3.30 it was working fine.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

just go in the demo page and see infinite loading when you try to divide by 0.
https://gradio.app/docs/#error

### Logs

```shell
""
```

### System Info

```shell
3.31, docker debian
```

### Severity

annoying

**Comment by frandominguezl** [comment]
It's true that the example is broken, I noticed it today when checking the docs, but it actually works locally even with v3.31.0

**Comment by freddyaboulton** [comment]
The issue arises when the demo is embedded. Which is why it happens on the docs but not locally

Repro by opening this file

```html
<!DOCTYPE html>
<html lang="en">
<script
	type="module"
	src="https://gradio.s3-us-west-2.amazonaws.com/3.31.0/gradio.js"
></script>

<div>
    <gradio-app space="gradio/calculator"></gradio-app>
</div>
</html>
```



![error_embed](https://github.com/gradio-app/gradio/assets/41651716/fd0d42ac-341e-4bd5-a0e3-9ef3e2af9709)

The backend is completing the request so maybe it's the js client.
<img width="477" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/a38999aa-ce00-43e4-ba6f-2b3b4371ba0d">

**Comment by pngwn** [comment]
This isn't actually a difference between embedded vs local. It is queue vs not queue. The `gradio/calculator` demo works locally because the queue isn't enabled but it doesn't work on spaces because spaces enables the queue by default.

**Comment by freddyaboulton** [comment]
Nice

**Comment by alexcumplido** [comment]
Hi, I'm using 3.31.0 version. I see a fix was merged on #4273 but the behaviour when queue is enabled.
The error shows on the terminal but not in the client side.

`
def handle_text(text):
    if len(text) > 10:
        raise gr.Error("Max text length is 10 characters")

    return text

with gr.Blocks() as demo:
    input = gr.TextArea()
    output = gr.TextArea()
    gr.Button().click(fn=handle_text, inputs=input, outputs=output) 
demo.queue()
demo.launch()`

**Comment by pngwn** [comment]
I'll take a look at this.

**Comment by abidlabs** [comment]
I can't reproduce either on the latest version of `gradio` @pngwn @alexcumplido 

Here's a Colab notebook where it works as expected: https://colab.research.google.com/drive/13ZfaKcpGBHZUUG49SYKbYx8VmhfEjfWO?usp=sharing

**Comment by pngwn** [comment]
No worries! Glad everything is working for you now.

**Comment by luyuhua** [comment]
gradio=3.35.2 have same problem.
when reduced 3.40.0,it's fine.

**Comment by 3DAlgoLab** [comment]
From version 4, this problem happsens again. After downgrading it to 3.40, it fixed.

**Comment by pngwn** [comment]
@3DAlgoLab Do you have a reproduction?

**Comment by 3DAlgoLab** [comment]
As I modified `queuing.py` for temporal measure, it resolved. But I don't know whether it is a right way.    
![Pasted image 20231109130629](https://github.com/gradio-app/gradio/assets/83936830/f55d2d8a-5cf3-4167-97d9-a80fdb3a0187)

**Comment by howardwu1** [comment]
Getting this error on v4 and v5 as well. Does anyone have a workaround to at least do a system exit after raising the error?

edit: figured out a workaround using try finally
