### ISSUE TITLE
Latex Support in Chatbot

### ISSUE THREAD

**Issue by dawoodkhan82** [gradio-app/gradio#4266]
### Describe the bug

https://github.com/gradio-app/gradio/pull/4150#issuecomment-1550214131

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://github.com/gradio-app/gradio/pull/4150#issuecomment-1550214131

### Logs

```shell
N/A
```

### System Info

```shell
N/A
```

### Severity

annoying

**Comment by abidlabs** [comment]
Related: #4244, #4075
