### ISSUE TITLE
Refactor hashing function logic into free functions

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#4270]
IOComponent has some methods for hashing/creating files that could be refactored into standalone functions

> The hashing functions should probably be moved into free functions in e.g. `utils.py` (or a new `hashing.py`) as they do not use `self` for anything.

_Originally posted by @akx in https://github.com/gradio-app/gradio/pull/4256#discussion_r1197851834_

**Comment by smeet07** [comment]
Could you list the methods that need to be refactored?

**Comment by freddyaboulton** [comment]
Hi @smeet07 ! They start with `hash_` and are defined in IOComponent. If you're interested I would wait until #4256 is merged.

**Comment by smeet07** [comment]
alright Ill start working on a pr once #4256 is merged

**Comment by varshneydevansh** [comment]
is this still pending? @freddyaboulton

**Comment by DarhkVoyd** [comment]
@freddyaboulton @abidlabs  Is this issue still active? How can I get started?

**Comment by freddyaboulton** [comment]
Hi @DarhkVoyd ! We're planning on refactoring a lot of the file saving logic ahead of the 4.0 release so I would not recommend picking up this issue. I will remove the label to reflect that.

**Comment by abidlabs** [comment]
This is now complete, the hashing functions live in `processing_utils.py`
