### ISSUE TITLE
`/favicon.ico` route returns `403`

### ISSUE THREAD

**Issue by catboxanon** [gradio-app/gradio#4274]
### Describe the bug

Gradio seems to currently return `403` for the [`/favicon.ico` route](https://github.com/gradio-app/gradio/blob/7145327058a8152045c7f14bda64832e2bc5913b/gradio/routes.py#L283-L289). I think it may have something to do with the usage of [`safe_join`](https://github.com/gradio-app/gradio/blob/7145327058a8152045c7f14bda64832e2bc5913b/gradio/routes.py#L274-L275). This also seems to happen regardless of Python venv location, or even when attempting to manually add the file location via `allowed_paths`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1.
```python
import gradio as gr

with gr.Blocks() as demo:
    pass

demo.launch()
```

2. Visit http://127.0.0.1:7860/favicon.ico
3. Page returns `403`, `{"detail":"Forbidden"}`

### Logs

```shell
N/A
```

### System Info

```shell
Gradio v3.31.0, Windows 11, Firefox
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
I cannot reproduce @catboxanon 

<img width="558" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/38a04aaf-8c62-4f63-84c1-7c341d4496b5">

**Comment by abidlabs** [comment]
Can confirm the issue on Windows. I think the fix should look a bit different, since the favicon is obtained through a different route:

```py
        @app.get("/favicon.ico")
        async def favicon():
```

Anyways, we'll look into it, thanks for reporting
