### ISSUE TITLE
"cancels=" not working when in multi "then" scenario

### ISSUE THREAD

**Issue by mabodofutk** [gradio-app/gradio#4276]
### Describe the bug

I found if there're multiple "then" in the event, the "cancels=" won't work, see code below.

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

```python
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.Button("Clear")
    stop = gr.Button("Stop")

    def user(user_message, history):
        return "", history + [[user_message, None]]

    def bot(history):
        bot_message = random.choice(["How are you?"*10, "I love you"*10, "I'm very hungry"*10])
        history[-1][1] = ""
        for character in bot_message:
            history[-1][1] += character
            # history += [(None, character)]
            time.sleep(0.05)
            yield history

    # stop will working
    submit_event = msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        bot, chatbot, chatbot)
    # stop won't working
    submit_event = msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        bot, chatbot, chatbot).then(bot, chatbot, chatbot)
    stop.click(None, None, None, cancels=[submit_event], queue=False)
    clear.click(lambda: None, None, chatbot, queue=False)

demo.queue()
demo.launch()
```

### Logs

```shell
Every is normal except "stop" button will not work
```

### System Info

```shell
3.24.1
linux ubuntu 20.04
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment]
Hi @mabodofutk !

The chain of `.then`s only returns the final event in the chain. So the cancel button is only cancelling the second generation not the first.

If you want the button to cancel both, you'd have to split them up:

```python
submit_event = msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(bot, chatbot, chatbot)
other_event = submit_event.then(bot, chatbot, chatbot)
stop.click(None, None, None, cancels=[submit_event, other_event], queue=False)
```

**Comment by mabodofutk** [comment]
@freddyaboulton thanks for the explanation, very helpful

**Comment by abidlabs** [comment]
Thanks @freddyaboulton! I'll go ahead and close this issue since there's no action item

**Comment by mabodofutk** [comment]
> Hi @mabodofutk !
> 
> The chain of `.then`s only returns the final event in the chain. So the cancel button is only cancelling the second generation not the first.
> 
> If you want the button to cancel both, you'd have to split them up:
> 
> ```python
> submit_event = msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(bot, chatbot, chatbot)
> other_event = submit_event.then(bot, chatbot, chatbot)
> stop.click(None, None, None, cancels=[submit_event, other_event], queue=False)
> ```

@freddyaboulton hello, I have changed the original code accordingly. However, although the "stop" button is functioning, if I submit a new message, the chatbot will start from where it stopped rather than establish a new submit event. Can you further clarify this? Thanks a lot
