### ISSUE TITLE
Stuck On Loading

### ISSUE THREAD

**Issue by H9990HH969** [gradio-app/gradio#4279]
### Describe the bug

I deployed a WebUI service offline. The new version of gradio(3.31.0 or 3.27.0) will always be stuck in the loading interface, but the old version of gradio(3.12.0) can be used normally.   
![1684491592895](https://github.com/gradio-app/gradio/assets/133352113/58a0a27b-9219-4e99-a2f0-20229a585046)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://github.com/THUDM/ChatGLM-6B

### Logs

```shell
![1684491818693](https://github.com/gradio-app/gradio/assets/133352113/05bc63a4-5bdb-497e-acdf-c9194dcbbe15)
```

### System Info

```shell
gradio(3.31.0) ,windows server2008 r2 enterprise,  Google Chrome 91.0.4472.106 (64)
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Is there anything in the console @H9990HH969 ?

**Comment by abidlabs** [comment]
This is expected behavior since Gradio doesn't currently work offline. See #1450

**Comment by junchen1992** [comment]
@H9990HH969 You may try `pip install gradio-offline`.

**Comment by mychina75** [comment]
> @H9990HH969 You may try `pip install gradio-offline`.

are there install package for "gradio-offline" ?
