### ISSUE TITLE
Impossible to add values to dropdown inside gr.block when initialized

### ISSUE THREAD

**Issue by tr31zh** [gradio-app/gradio#4280]
### Describe the bug

Cannot add values to Dropdown when following conditions:
- Dropdown is in side gr.Block
- Dropdown is multiselect
- Dropdown has been created with selected value(s)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr

with gr.Blocks() as gr_training_zoo:
    tst = gr.Dropdown(
        ["ran", "swam", "ate", "slept"],
        value=[],
        multiselect=True,
        label="Not initialized",
        info="Changes allowed",
    )
    gr.Dropdown(
        ["ran", "swam", "ate", "slept"],
        value="swam",
        multiselect=True,
        label="Initialized",
        info="Only value removal allowed, no adding",
    )

gr_training_zoo.launch()

### Logs

```shell
No logs
```

### System Info

```shell
gradio-3.31.0 gradio-client-0.2.5
chrome Version 113.0.5672.92
python 3.10.11
mac os 13.0 (22A380)
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Hi @tr31zh interesting... you can fix this by adding `interactive=True` to the `gr.Dropdown()`, but I'm not sure why the error happens in the first place. Will investigate.

Here's the workaround for now:

```py
import gradio as gr

with gr.Blocks() as gr_training_zoo:
    tst = gr.Dropdown(
        ["ran", "swam", "ate", "slept"],
        value=[],
        multiselect=True,
        label="Not initialized",
        info="Changes allowed",
        interactive=True
    )
    gr.Dropdown(
        ["ran", "swam", "ate", "slept"],
        value="swam",
        multiselect=True,
        label="Initialized",
        info="Only value removal allowed, no adding",
        interactive=True
    )

gr_training_zoo.launch()
```
