### ISSUE TITLE
Gradio 3.31.0 not available on Mac/Darwin

### ISSUE THREAD

**Issue by vladmandic** [gradio-app/gradio#4288]
### Describe the bug

seems that gradio 3.31.0 is not available for apple mac platform??
this is a major issue as gradio is supposed to be cross-platform.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`pip install gradio==3.31.0`

> ERROR: Could not find a version that satisfies the requirement gradio==3.31.0 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 
>...
> 3.25.1b2, 3.26.0, 3.27.0, 3.28.0, 3.28.1, 3.28.2, 3.28.3, 3.28.4b0, 3.29.0, 3.30.0)
> ERROR: No matching distribution found for gradio==3.31.0

### Logs

```shell
N/A
```

### System Info

```shell
python 3.10.11 on Darwin
```

### Severity

blocking all usage of gradio

**Comment by freddyaboulton** [comment]
That's odd - the wheel for gradio is platform agnostic! I am in an M1 mac and have not problem installing gradio with pip.

<img width="1280" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/5f5cea9c-da2a-4aa2-8944-6c7376dd0d7d">

**Comment by freddyaboulton** [comment]
Could be! - version 3.31.0 does show up for me with pip index

**Comment by vladmandic** [comment]
> Could be! - version 3.31.0 does show up for me with pip index

yeah, thats the problem. it doesn't seem available in some locations.

for me at home it works (with mac specific or without):
> pip index versions gradio --platform=darwin
> Available versions: 3.31.0, 3.30.0 ...

**Comment by abidlabs** [comment]
Hi @vladmandic could this be the issue? https://pypi.org/help/#tls-deprecation

**Comment by abidlabs** [comment]
Oh nvm it looks like it was something else. I'll go ahead and close this issue.

**Comment by vladmandic** [comment]
wait, why close? i said it works for me at home, but i have tons of users who report it doesn't work?!

**Comment by abidlabs** [comment]
Hmm happy to try to debug this with you, but this is almost certainly not a gradio issue. If it's affecting other users as well, a couple of ideas:

1. Maybe the TLS issue I linked to above
2. What happens if you / other users run `pip cache purge`

**Comment by TaoismDeepLake** [comment]
> Hmm happy to try to debug this with you, but this is almost certainly not a gradio issue. If it's affecting other users as well, a couple of ideas:
> 
> 1. Maybe the TLS issue I linked to above
> 2. What happens if you / other users run `pip cache purge` before running the `pip install gradio==3.31.0`

No, it does not work and I am on windows.

**Comment by TaoismDeepLake** [comment]
> > Hmm happy to try to debug this with you, but this is almost certainly not a gradio issue. If it's affecting other users as well, a couple of ideas:
> > 
> > 1. Maybe the TLS issue I linked to above
> > 2. What happens if you / other users run `pip cache purge` before running the `pip install gradio==3.31.0`
> 
> No, it does not work and I am on windows.

I am in China and used to use a mirror for pip. Killing the mirror worked.
