### ISSUE TITLE
Gradio not displaying correctly highlights function in dark mode

### ISSUE THREAD

**Issue by Alanp777** [gradio-app/gradio#4294]
### Describe the bug

https://huggingface.co/spaces/mohdelgaar/Clinical_Decisions?embed=true
<img width="579" alt="Screenshot 2023-05-20 at 10 14 46 PM" src="https://github.com/gradio-app/gradio/assets/132757923/833f1bb8-d57a-4856-aefa-50284fe2a2fc">

<img width="550" alt="Screenshot 2023-05-20 at 10 15 20 PM" src="https://github.com/gradio-app/gradio/assets/132757923/8256eaa3-e546-4b1d-a15f-13a20a35b686">

Attached is the code sample of a space in gradio but all gradios interfarces wont work in dark mode, the font turns both white and black and the user has a hard time reading the output.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

provided code and screenshots

### Screenshot

provided

### Logs

```shell
provided
```

### System Info

```shell
provided
```

### Severity

annoying

**Comment by Alanp777** [comment]
helloo @abidlabs just to see if you had  10 seconds to check this? if this is not a priority I will understand but this hurts the ability of my users to read properly the highlighted text, thanks so much!

**Comment by abidlabs** [comment]
Hi @Alanp777 we'll take a look at it, but it might be a while before our team can fix this. If you would like to open a PR, we're happy to review.

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created. Could you let us know if this is still an issue in the latest version of Gradio (pip install --upgrade gradio)? Thanks!

**Comment by abidlabs** [comment]
Will go ahead and close this for now. Can reopen if needed
