### ISSUE TITLE
Is there a feature to disable the preview mode in the gallery? 

### ISSUE THREAD

**Issue by sunnyark** [gradio-app/gradio#4298]
- [* ] I have searched to see if a similar issue already exists.

Is there a feature to disable the preview mode in the gallery? I am using the gallery as a substitute for an image list, but it becomes inconvenient when it automatically switches to preview mode upon selection. I would like to turn off the preview mode.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by abidlabs** [comment]
Thanks @sunnyark for the issue. However, this looks like a duplicate of #3763 so I’ll close it
