### ISSUE TITLE
"Running events consecutively" docs example doesn't show what is described

### ISSUE THREAD

**Issue by anentropic** [gradio-app/gradio#4301]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

https://gradio.app/blocks-and-event-listeners/#running-events-consecutively

> You can also run events consecutively by using the `then` method of an event listener. This will run an event after the previous event has finished running. This is useful for running events that update components in multiple steps.
>
> For example, in the chatbot example below, we first update the chatbot with the user message immediately, and then update the chatbot with the computer response after a simulated delay.

This sounds like there is a `then` method which allows to trigger another event after the one currently being handled.

But the example code doesn't show any use of `then`.

Eventually I found the answer indirectly on this page: https://gradio.app/creating-a-chatbot/

Again it says things like:

> we now _chain_ two event events with `.then()`

despite the fact that the example doesn't show any calls to a `then` method

But what the example code _does_ show is using a generator function, i.e. `yield` instead of `return`. And I've found that this does allow returning multiple consecutive updates from a single event handler call.

AFAICT this isn't mentioned anywhere else in the main docs, e.g.
- https://gradio.app/docs/
- https://gradio.app/blocks-and-event-listeners/

**Comment by anentropic** [comment]
a small correction to above...

the code here https://gradio.app/creating-a-chatbot/#add-streaming-to-your-chatbot actually _does_ show use of `then` method:

```python
    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        bot, chatbot, chatbot
    )
```

But the "Running events consecutively" docs say they do, but don't.

**Comment by anentropic** [comment]
🤔 💡   ...so the `yield` is actually an additional undocumented feature and not part of running events consecutively

**Comment by abidlabs** [comment]
This is fixed in the original docs. The `yield` functionality is described here: https://www.gradio.app/guides/key-features#iterative-outputs
