### ISSUE TITLE
Label.change event re-triggers itself

### ISSUE THREAD

**Issue by anentropic** [gradio-app/gradio#4309]
### Describe the bug

The `Label.change` event fires when its value did not change

In fact the completion of handling the `change` event seems to re-trigger the `change` event

(I encountered this while trying to use a hidden Label as a workaround for `State` objects have no change event https://github.com/gradio-app/gradio/issues/2107)

Issue may be specific to the `Label` component, if I substitute a hidden `Textbox` the issue does not happen

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

def set_label(val):
    print("set_label")
    return f"> {val}"

def on_change(val):
    print(f"on_change: {val}")

with gr.Blocks() as demo:
    inp = gr.Textbox(label="Set label")
    label = gr.Label("", visible=False)

    inp.submit(set_label, [inp], [label])

    label.change(on_change, [label], None)

demo.launch(debug=True)
```

### Screenshot

The code above gets stuck in a loop

![Screenshot 2023-05-22 at 16 56 26](https://github.com/gradio-app/gradio/assets/147840/515dc2ac-fee3-4c98-947a-59cff3e3285f)

it seems like the change event re-triggers itself

### Logs

```shell
n/a
```

### System Info

```shell
gradio 3.32.0
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Thanks @anentropic - will take a look!
