### ISSUE TITLE
Sanitize feature of Marked breaking HTML additions to markdown on gr.Chatbot()

### ISSUE THREAD

**Issue by decent-engineer-decent-datascientist** [gradio-app/gradio#4316]
### Describe the bug

The new improved markdown support for gr.Chatbot() is wonderful, but enabling the "sanitize" option on Marked has broken existing implementations that leveraged HTML to enhance chatbot capabilities.

For example, we have a deployed QA+Search chatbot that returned answers and relevant sources like so (using gradio 3.29.0):
![image](https://github.com/gradio-app/gradio/assets/77806775/28be2016-a8c2-447b-93be-bff3b9ddcdc6)

However, using the latest version, this is what is produced. 
<img width="993" alt="Screenshot 2023-05-22 at 12 45 40 PM" src="https://github.com/gradio-app/gradio/assets/77806775/d40de9dd-c487-4980-99fa-9c33bfa058a0">

We're assuming the "sanitize" option in marked (this line https://github.com/gradio-app/gradio/blob/38607c9967ba6421a9b53c1fd9c94c29e4338365/js/chatbot/src/ChatBot.svelte#L42) is causing this "issue".

Could we get the ability to disable this sanitization? I understand wanting it on by default.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Can write one up if needed, but seem straightforward enough.

### Logs

```shell
N/A
```

### System Info

```shell
Gradio 3.32.0
```

### Severity

annoying

**Comment by abidlabs** [comment]
For now, I actually think we should just set `sanitize=False` to prevent any breaking changes. WDYT @dawoodkhan82?

**Comment by decent-engineer-decent-datascientist** [comment]
Personally would very much like to see this disabled, if only so we could catch up to the latest gradio in our deployment. Another thing to note is that Marked contributors themselves discourage the use/existence of sanitize:
https://github.com/markedjs/marked/discussions/1232

**Comment by cowanAI** [comment]
still it looks like a mess 
<img width="328" alt="Screenshot 2023-05-28 at 9 45 34 AM" src="https://github.com/gradio-app/gradio/assets/128092052/977fadb6-1410-4ba5-8199-e4748af6326a">

**Comment by abidlabs** [comment]
This is pretty high-priority, let's add to 3.x milestone @dawoodkhan82

**Comment by dawoodkhan82** [comment]
@decent-engineer-decent-datascientist can you test #4360 to see if it fixes your issue.

**Comment by lsqingfeng** [comment]
when I use html in chatbot , I use a input radio ,but I cant get which is checked.

**Comment by Fusseldieb** [comment]
Disabling sanitization can lead to XSS. With the limited scope of a Gradio app this is pretty "rare", but still.
Better yet would be a list of allowed HTML selectors.

What it could look like:
`allowed_selectors=["strong","#mydiv", "img['bot']"]`
