### ISSUE TITLE
Weird Looping Behavior on Windows10 only

### ISSUE THREAD

**Issue by x-CK-x** [gradio-app/gradio#4326]
### Describe the bug

I've tested on both linux & windows and I'm only getting this issue on windows. It loops when calling functions from instantiated objects from other local files with the respective classes.

It loops any code in the main script with the defined components.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://github.com/x-CK-x/Dataset-Curation-Tool/wiki

Either downloading any data and/or trying to run inference with the captioning model creates this looping behavior with code in the webui.py script.

I did try upgrading it to gradio==3.32.0, but on windows10 the issue persists
the issue is OS related using gradio, but the loop behavior specifically happens when a function is called from a previously instantiated object in the webui.py.
- so with the batch_downloader class, running the download button
- as well as the the auto_tag class, running the interrogate button

### Logs

```shell
n/a, no error/s or warning/s
```

### System Info

```shell
3.29.0 but I also tested with 3.32.0
Windows10 (looping issue present) but with Ubuntu no issues
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @x-CK-x can you provide a simpler repro than running the entire webui? A simpler code snippet that we could run the reproduce the looping behavior you describe?

**Comment by x-CK-x** [comment]
windows doesn't have a ``fork`` sys-command like linux. 
I wouldn't have found out this issue, but someone pointed it out: https://github.com/x-CK-x/Dataset-Curation-Tool/issues/4

the only solution is when designing around a UI with gradio, to wrap everything in a function and any initialization functions get called in the __main__ == name, otherwise anyone is prone to this happening.
