### ISSUE TITLE
Flagging support Textbox

### ISSUE THREAD

**Issue by Shengqiang-Li** [gradio-app/gradio#4327]
I have used gradio to build a web to test my tts model. I want to use a Textbox to record more detailed information of the badcase then  use flagging button to save the recorded information to a log.csv file.

**Comment by abidlabs** [comment]
Hi @Shengqiang-Li you can create an empty textbox and use it to add additional data, which will be saved when the data point is flagged. Something like this:

```py
import gradio as gr

textbox = gr.Textbox(label="Flag data")

with gr.Blocks() as demo:
    interface = gr.Interface(lambda x:(x, None), "image", ["image", textbox])
    demo.load(lambda: textbox.update(interactive=True), None, textbox)

demo.launch()
```

This will be even easier when #4356 is merged. Then you'd be able to do just this:

```py
import gradio as gr

textbox = gr.Textbox(label="Flag data", interactive=True)
gr.Interface(lambda x:(x, None), "image", ["image", textbox]).launch()
```
