### ISSUE TITLE
Button values wrong, borrowed from others [after others clicked]

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#4329]
### Describe the bug

I have odd problem.  I have 5 tabs, two of which are Chats and Data Source.  If I start to click on buttons in Chats, then go to Data Source tab, some of the buttons are now same value as in  Chat, for no good reason.  Happens very quickly.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Requires no GPU etc, just bare bones:
* Checkout https://github.com/h2oai/h2ogpt/pull/163/commits/05bdeb13852a0391020d5aba92ae07acf7ecdd9d
* Setup python 3.10 env
* `pip install -r requirements.txt`
* `pip install -r requirements_optional_langchain.txt`
* Run: `python generate.py --share=False --score_model=None --langchain_mode=MyData`
* Unzip: [chats.zip](https://github.com/gradio-app/gradio/files/11551308/chats.zip)
* Upload all chat_*.json files in Chat Tab in upload box
* Then click on import chats from upload
* Then click on Data Source Tab
* SEE that one of the buttons now says "Import Chats from Upload"

### Screenshot

BAD:
![image](https://github.com/gradio-app/gradio/assets/2249614/97e5a604-cd68-40d9-9107-b5da19180e97)

ORIGINAL:
![image](https://github.com/gradio-app/gradio/assets/2249614/79867300-facb-40d8-9183-18f6f7ede636)

See how one button (after those other clicks) is now wrong in BAD version.

### Logs

```shell
NA
```

### System Info

```shell
gradio==3.31.0
gradio_client==0.2.5
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @pseudotensor would you be able to try to provide a simpler repro? Ideally a standalone code snippet we could use to test our fix? Thanks!

**Comment by abidlabs** [comment]
Closing -- please feel free to reopen with a simpler repro
