### ISSUE TITLE
model3d style function is empty,  and can't control the size of model3d manually

### ISSUE THREAD

**Issue by shinetzh** [gradio-app/gradio#4330]
can not manual control the size of model3d

**Comment by shinetzh** [comment]
can not manual control the size of model3d

**Comment by abidlabs** [comment]
Hi @shinetzh can you please provide example code we can use to reproduce and explain what you expect vs. what the code is producing?

**Comment by andreped** [comment]
If @shinetzh does not have a simple use case, I recently made a post at the forum regarding this (see [here](https://discuss.huggingface.co/t/change-size-and-alignment-of-annotatedimage-and-model3d-widgets/41305)).

More information can be found from the link (see [here](https://huggingface.co/spaces/andreped/livermask) to see the space directly), as well as a link to the source code and deployed app on spaces.

In summary I am attempting to place a 2D and 3D viewer side-by-side, and I do not see a simple way when using `gradio.Blocks` to place these side by side such that they are center aligned within respective boxes and scaled identally in size, which would make the demo app look much nicer. I believe this is the same issue as what @shinetzh has.

<img width="1541" alt="Screenshot 2023-05-29 at 13 23 21" src="https://github.com/gradio-app/gradio/assets/29090665/40e1bab9-67d7-4923-a230-0da84f5d60ec">

**Comment by radames** [comment]
simple bug snippet
```python
css="""
#model-out {
  height: 512px;
}
#model-in {
  height: 512px;
}
"""
with gr.Blocks(css=css) as demo:
  with gr.Row():
    with gr.Column():
      inp = gr.Model3D(elem_id="model-in")
      btn = gr.Button("Hello")
    with gr.Column():
      out = gr.Model3D(elem_id="model-out")
```
expected 

```python
with gr.Blocks(css=css) as demo:
  with gr.Row():
    with gr.Column():
      inp = gr.Model3D().style(height=512)
      btn = gr.Button("Hllo")
    with gr.Column():
      out = gr.Model3D().style(height=512)
```
here is a notebook demo
https://colab.research.google.com/drive/1_IVwRLB5G5hu5Zdh3XzR2n1gzuYSxB9E

**Comment by andreped** [comment]
Worked wonders, @radames! Cheers.

To address alignment, I just needed to add `margin: auto` to the css.
In my case I was using an `AnnotatedImage` as 2D viewer and `Model3D` as 3D viewer. Here is the final result:

![Screenshot 2023-06-02 at 09 15 48](https://github.com/gradio-app/gradio/assets/29090665/8be4b01d-07b4-442f-a076-de55eee3cedd)

**Comment by abidlabs** [comment]
Thanks @radames! We'll keep this issue open so that we can fix this later on.

**Comment by abidlabs** [comment]
I believe the issue is that the `gr.Model3D` component doesn't have parameters that allow setting the width and the height of the component (like some of our other components such as `Image` do). We shouldn't require users to use custom css for [the reasons mentioned at the top of this page](https://www.gradio.app/guides/custom-CSS-and-JS).

That being said, this is more of an enhancement than a bug, so feel free to recategorize @hannahblair
