### ISSUE TITLE
The type checking of EventListenerMethod does not support BlockContext

### ISSUE THREAD

**Issue by kaze-mio** [gradio-app/gradio#4331]
### Describe the bug

The type annotations for inputs and outputs parameters in EventListenerMethod are as follows:
```python
inputs: Component | list[Component] | set[Component] | None = None,
outputs: Component | list[Component] | None = None,
```
It only supports Component types but not BlockContext (e.g. Row, Column) types.
It may be helpful to add type annotations for BlockContext types. :)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just pass BlockContext variables as inputs / outputs parameters to an event method (e.g. button.click) and the type checking will fail.

### Logs

```shell
None
```

### System Info

```shell
None
```

### Severity

annoying

**Comment by kaze-mio** [comment]
a specific case as an example:
I would like to update the visibility of a Row / Column by clicking a button. Therefore, it is necessary to pass the Row / Column as an output parameter to the button.click function, but it cannot pass the type check.
```python
with gr.Blocks() as main_interface:
    with gr.Row() as row:
        gr.Textbox()
    enable_button = gr.Button(value="Enable")
    enable_button.click(
        fn=lambda: gr.Row.update(visible=True), inputs=None, outputs=row
    )
    disable_button = gr.Button(value="Disable")
    disable_button.click(
        fn=lambda: gr.Row.update(visible=False), inputs=None, outputs=row
    )
```

**Comment by abidlabs** [comment]
This has been fixed!
