### ISSUE TITLE
Gradio remains stuck in "Loading" phase in LAN configuration (not connected to the Internet)

### ISSUE THREAD

**Issue by musiscient** [gradio-app/gradio#4332]
### Describe the bug

Gradio remains stuck in "Loading" phase in LAN configuration (not connected to the Internet) if I clean all images and cached files from my different test browsers (Chrome, Firefox, Opera, Brave), even with localhost:7860,

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

# I'm running the basic script of the "(Getting Started) - Quick Start" of Gradio :
#
import gradio as gr
print(gr.__version__)

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(
    fn=greet,
    inputs=gr.Textbox(lines=2, placeholder="Name Here..."),
    outputs="text",
)
demo.launch(debug=True) 

-----
- It works perfectly as long as the computer is connected to the internet.

- I disconnect from the internet to connect to a LAN, or disconnect completely.

Gradio is then still accessible by Chrome or other browsers.

But : 
If I clean up the cached images and files of my different browsers, 
and, as long as I am not connected to the internet, either because I am connected to a LAN not connected to the internet, or because the computer is completely disconnected from all external links, (RJ45 and Wifi disconnected) so, even in localhost:7860, the Gradio web page remains blocked in the loading phase. Impossible to reach the content of the Gradio web page.

I tested this, because I installed Automatic1111 on Ubuntu Server 22.04 to run inside a LAN outside the internet, (with argument --listen) and the same phenomenon occurs. Once the images and cached files of the browsers have been cleaned up following an internet connection to connect in LAN configuration, access to Gradio pages remains blocked in the "loading" situation. Impossible to access the Gradio interface pages.

Thank you for any indications to allow the use and access of Gradio via a LAN not connected to the Internet.

Cheers

-----

### Screenshot

![Capture d’écran du 2023-05-24 18-22-50](https://github.com/gradio-app/gradio/assets/17192687/2533d942-83bf-4ee2-8580-aa8d7a31ba0e)

### Logs

```shell
# from terminal :
/home/ia/anaconda3/envs/Gradio_studies/bin/python /home/ia/anaconda3/envs/Gradio_studies/ia_python_code/greet.py 
3.32.0
Running on local URL:  http://127.0.0.1:7860
```

### System Info

```shell
Gradio = 3.32.0
OS (es) :
- Ubuntu 20.04
- Ubuntu Server 22.04, in a Conda environment or not

- test browsers (Chrome, Firefox, Opera, Brave)
```

### Severity

annoying

**Comment by futureflsl** [comment]
I just have this problem,And I cannot solve it ,but I install gradio==3.12.0,it work well,but old version api may be not same with newer version.

**Comment by akx** [comment]
For one, you may have better luck if you set the `GRADIO_ANALYTICS_ENABLED` environment variable to `false`, so Gradio doesn't request Google Tag Manager assets, as it does by default.

The root cause seems to be that Gradio awaits forever for Google Fonts to load:

![Screenshot 2023-05-25 at 9 44 34](https://github.com/gradio-app/gradio/assets/58669/681c0efc-2027-4218-b4fc-4774f77ef3eb)

For a workaround, you could set your Gradio app [to use a theme](https://gradio.app/docs/#themes) that doesn't use external fonts, but that's not very workable in the long run – not to mention [using Google Fonts is not GDPR compliant](https://meetanshi.com/blog/google-fonts-gdpr-compliant/) (so this ties to #4226).

**Comment by musiscient** [comment]
Thanks a lot for your indications **akx**, I was able to implement the following workaround, which may help others before a more stable integration....

in the file /site_packages/gradio/themes/utils/fonts.py

comment request to: https://fonts.googleapis.com/

from : 

```
class GoogleFont(Font):
    def __init__(self, name: str, weights: Iterable[int] = (400, 600)):
        self.name = name
        self.weights = weights

    def stylesheet(self) -> str:
        return f'https://fonts.googleapis.com/css2?family={self.name.replace(" ", "+")}:wght@{";".join(str(weight) for weight in self.weights)}&display=swap'

```
to :
``
```
class` GoogleFont(Font):
    def __init__(self, name: str, weights: Iterable[int] = (400, 600)):
        self.name = name
        self.weights = weights

    def stylesheet(self) -> str:
        pass
        #return f'https://fonts.googleapis.com/css2?family={self.name.replace(" ", "+")}:wght@{";".join(str(weight) for weight in self.weights)}&display=swap'
```
              
And now AUtomaticA1111 (and any gradio app) are getting accessible on a LAN not connected to the Internet.

Should I declare the ticket solved or is this an issue that has yet to be resolved definitively?

Thanks again!

**Comment by akx** [comment]
@musiscient Well, editing the gradio source itself is not recommended - you should probably just instantiate your custom theme that doesn't use `GoogleFont`s. I think @aliabid94 wrote the theme stuff, he can probably help you out with the best approach.

**Comment by musiscient** [comment]
Thank you for your wise advice, @akx, I check this.

**Comment by mychina75** [comment]
> Thanks a lot for your indications **akx**, I was able to implement the following workaround, which may help others before a more stable integration....
> 
> in the file /site_packages/gradio/themes/utils/fonts.py
> 
> comment request to: https://fonts.googleapis.com/
> 
> from :
> 
> ```
> class GoogleFont(Font):
>     def __init__(self, name: str, weights: Iterable[int] = (400, 600)):
>         self.name = name
>         self.weights = weights
> 
>     def stylesheet(self) -> str:
>         return f'https://fonts.googleapis.com/css2?family={self.name.replace(" ", "+")}:wght@{";".join(str(weight) for weight in self.weights)}&display=swap'
> ```
> 
> to : ``
> 
> ```
> class` GoogleFont(Font):
>     def __init__(self, name: str, weights: Iterable[int] = (400, 600)):
>         self.name = name
>         self.weights = weights
> 
>     def stylesheet(self) -> str:
>         pass
>         #return f'https://fonts.googleapis.com/css2?family={self.name.replace(" ", "+")}:wght@{";".join(str(weight) for weight in self.weights)}&display=swap'
> ```
> 
> And now AUtomaticA1111 (and any gradio app) are getting accessible on a LAN not connected to the Internet.
> 
> Should I declare the ticket solved or is this an issue that has yet to be resolved definitively?
> 
> Thanks again!

Solved my problem. Great!

**Comment by violet17** [comment]
> Contributor

How to fix it if I want to use google fonts without change gradio source code?
