### ISSUE TITLE
Blocks .queue when mounted on FastAPI timeouts

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [gradio-app/gradio#4340]
### Describe the bug

Hi There :wave: 

Thanks a lot for the fantastic framework, I am trying to use gradio inside fastAPI, I've basically the same setup as this [similar issue](https://github.com/gradio-app/gradio/issues/2292)

```python
...
with gr.Blocks(
    css="""#col_container {width: 700px; margin-left: auto; margin-right: auto;}
                #chatbot {height: 400px; overflow: auto;}"""
) as demo:
    ....
    with gr.Column(elem_id="col_container"):
        chatbot = gr.Chatbot()
        with gr.Column():
            message = gr.Textbox(label="chat input")
            message.submit(
                message_handler,
                [chat, message, chatbot, messages],
                [chat, message, chatbot, messages],
                queue=True,
            )

    @app.get("/", response_class=HTMLResponse)
    async def home(request: Request):
        return templates.TemplateResponse(
            "home.html", {"request": request, "videos": []})

    demo.queue()

    gradio_app = gr.routes.App.create_app(demo)
    app.mount("/gradio", gradio_app)


```

I need to `demo.queue` since I am using a generator to stream generated words to the chatbot UI. The main issue now is that the frontend just hang and it looks like is not able to get the replies back from the queue - not really sure what is going on :sweat: 

Thanks a lot 

Fra

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Not really sure in this case

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/15908060/3eb0831a-63bf-408f-be6c-3f82da898f47)

### Logs

```shell
There are no logs, just the logs from `uvicorn main:app` showing I guess some sort of pings


INFO:     127.0.0.1:60748 - "GET /app_id HTTP/1.1" 200 OK
INFO:     127.0.0.1:60748 - "GET /app_id HTTP/1.1" 200 OK
INFO:     127.0.0.1:60748 - "GET /app_id HTTP/1.1" 200 OK
INFO:     127.0.0.1:60748 - "GET /app_id HTTP/1.1" 200 OK
INFO:     127.0.0.1:60748 - "GET /app_id HTTP/1.1" 200 OK
```

### System Info

```shell
Chrome, Ubuntu 22.04, gradio==3.32.0
```

### Severity

serious, but I can work around it

**Comment by Po-Kai** [comment]
Thank you, @freddyaboulton . It helped me, but when I add a path prefix, it doesn't seem to work with the gradio_client. I discovered that the problem lies in obtaining the incorrect endpoint, whereas it works fine on the web page.

**Comment by freddyaboulton** [comment]
Hi @Po-Kai - can you post a minimal reproducer? What version of gradio are you using?

**Comment by Po-Kai** [comment]
There is my minimal reproducer:

**Server code (test.py)**
```python3
from fastapi import FastAPI
import gradio as gr


def greet(name):
    return "Hello " + name + "!"


gradio_app = gr.Interface(
    fn=greet,
    inputs=gr.Textbox(lines=2, placeholder="Name Here..."),
    outputs="text",
)


app = FastAPI()
app = gr.mount_gradio_app(app, gradio_app, path="/gradio")
```

***Client code (client.py)***
```python3
from gradio_client import Client

client = Client("http://localhost:8000/gradio")

print(client.view_api())
```

***Run server script***
```bash
uvicorn test:app
```

***Log on server***
```
...
INFO:     127.0.0.1:40180 - "GET /config HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:40186 - "GET /gradio HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:40186 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:40202 - "GET /info HTTP/1.1" 404 Not Found
```

***Error log on client***
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[2], line 3
      1 client = Client("http://localhost:8000/gradio")
----> 3 print(client.view_api())

...

ValueError: Could not fetch api info for http://localhost:8000/gradio
```


*** Requirements ***
```
fastapi==0.95.2
gradio==3.33.1
uvicorn==0.22.0
```

Thank you for your help @freddyaboulton !

**Comment by abidlabs** [comment]
Thanks for the nice and helpful repro @Po-Kai, the bug should now be fixed on `main` and soon will be released to pypi.
