### ISSUE TITLE
`root_path` of launch does not work as expected

### ISSUE THREAD

**Issue by RussellLuo** [gradio-app/gradio#4352]
### Describe the bug

Per the docs of [launch](https://gradio.app/docs/#interface-launch-header):

> The root path (or "mount point") of the application, if it's not served from the root ("/") of the domain. Often used when the application is behind a reverse proxy that forwards requests to the application. For example, if the application is served at "https://example.com/myapp", the `root_path` should be set to "/myapp".

Related comments from a previous issue: https://github.com/gradio-app/gradio/issues/4291#issuecomment-1558773454.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Given the following code:

```python
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")

if __name__ == "__main__":
    demo.launch(root_path="/myapp")
```

Run the demo:

```
python3 demo.py 
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
```

Then access the demo from http://127.0.0.1:7861/myapp.

### Screenshot

<img width="335" alt="image" src="https://github.com/gradio-app/gradio/assets/5109942/6f890def-5f58-4cdf-bd69-2371a0b4ed17">

### Logs

```shell
No extra logs.
```

### System Info

```shell
Gradio 3.30.0
python 3.9.12
macOS
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @RussellLuo there's some confusion here. The `root_path` parameter is set if your Gradio application is *already* running on `https://example.com/myapp` due to some reverse proxy (like nginx). Then, you set `root_path` to `myapp` so that everything works properly. We'll document this better when we write this Guide: #3260 

It looks like what you want is to mount your Gradio application, within another FastAPI, see: https://gradio.app/sharing-your-app/#mounting-within-another-fastapi-app

**Comment by RussellLuo** [comment]
@abidlabs Thanks for you reply!

I have managed to serve my Gradio application by using [the strategy](https://gradio.app/sharing-your-app/#mounting-within-another-fastapi-app) you mentioned above. However, **it seemed that everything worked out well even if no `root_path` was specified**. So I thought `root_path` was a thing equivalent to mounting Gradio application within another FastAPI.

**Comment by ahmedelgammal** [comment]
I have the same error. I am trying to mount a gadio app as described, something like https://example.com/myapp using nginx reverse proxy. I get that error when I use root_path="/myapp" in the block.launch call. the response from the server is {"detail":"Not Found"}. I have no problem if I mount the app to the root.

**Comment by abidlabs** [comment]
Hi @ahmedelgammal have you taken a look at this guide here? https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx

**Comment by ahmedelgammal** [comment]
@abidlabs yes, I implemented that exactly, except that I am using blocks. This works as expected without the root_path. Once I add the root_path, the app doesn't work, even on the local server.
