### ISSUE TITLE
Add interactive plots within gr.Chatbot

### ISSUE THREAD

**Issue by Gabriel-Macias** [gradio-app/gradio#4355]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
No.

**Describe the solution you'd like**  
I'm currently looking into building a chat application that is able to show certain plots to users based on their requests and was wondering if is possible to embed other gradio components such as `gr.Plot` or some way to include interactive plots made via `plotly` or `bokeh` within the chatbox as opposed to including a separate `gr.Plot` component to display them outside of the chat. My current solution only considers inserting static images in the chatbot via hyperlinks.

**Comment by abidlabs** [comment]
Hi @Gabriel-Macias this is an interesting idea, but probably not one we'll support in the core library soon as it would require a significant refactoring of `gr.Chatbot`. I do see the value of it down the line, so let's keep this issue open

**Comment by trivikramak** [comment]
Hi @abidlabs, Is there any update on the timeline or priority of this feature/enhancement?

**Comment by abidlabs** [comment]
Not yet -- I think this will require quite a bit of work unfortunately. cc @dawoodkhan82

**Comment by liwalayouni** [comment]
Hi @abidlabs any chance this feature could be implemented? I see a lot of value having it part of Gradio capabilities!

**Comment by freddyaboulton** [comment]
I think this could be an interesting custom component!

**Comment by andreped** [comment]
This would be of interest to me as well. We are able to do this in Streamlit without any additional libraries.

Does anyone know of a custom `gr.Chatbot` widget, which offers support for adding "any" gradio component such as `gr.Dataframe` or `gr.Code` inside a chat bubble?

**Comment by liwalayouni** [comment]
@freddyaboulton any snippet code you can share on how we can integrate `plotly` graphs in `gr.Chatbot`?

**Comment by freddyaboulton** [comment]
Hi @liwalayouni ! I'm not sure what the general solution looks like because there is no standard format for an LLM to specify a plot. For the plot case, I think you can handle this in the prediction function.

Parse the LLM output for a plot, save it to an image and then embed the image using html. Something like this `<img src='/file={image}' />` where `image` is the image path.

**Comment by liwalayouni** [comment]
Hey @freddyaboulton assuming the LLM generated the chart and we have a Ploly Figure Object. The ask was how to plot it as interactive in the `gr.chatbot`.
i.e can `gr.Chatbot` integrates a subcomponent like `gr.Plot`?

**Comment by freddyaboulton** [comment]
No built-in support. For now, I think you need to embed as an image or if you want interactivity, saving to html and embedding as an iframe in the response may work (have not tried) 

https://plotly.com/python/interactive-html-export/

**Comment by freddyaboulton** [comment]
It is now possible to display a `gr.Plot` in a chatbot message! See the `demo/chatbot_core_components` demo in the repository.
