### ISSUE TITLE
An error happened when upload a directory more than 1000 files

### ISSUE THREAD

**Issue by Arrkwen** [gradio-app/gradio#4361]
### Describe the bug

it receive an error when I upload a directory with more 1000 pictures.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr

def upload_file(files):
    file_paths = [file.name for file in files]
    return file_paths

with gr.Blocks() as demo:
    full_images = gr.Gallery(
                    label="full images", show_label=True, elem_id="full_images",info="上传全图测试目录"
                        ).style(columns=[10])
    full_button = gr.UploadButton("Upload", file_count="directory")
    full_button.upload(upload_file, full_button, full_images, scroll_to_output=True)

if __name__ == "__main__":
    ip = "0.0.0.0"
    port = 18091
    demo.queue()
    demo.launch(server_name=ip, server_port=port)

### Logs

```shell
file without key: name
```

### System Info

```shell
gradio: 3.30, linux
```

### Severity

annoying

**Comment by 3rd-Musketeer** [comment]
Same problem. Suggest to support batched input.
