### ISSUE TITLE
UploadButton cannot be made non-interactive

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#4364]
### Describe the bug

The UploadButton can be made non-interactive but I can imagine a use case where this is desired: While a function is running prevent the user from uploading another file.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`gr.UploadButton(interactive=False)` will still let you upload a file

### Logs

```shell
-
```

### System Info

```shell
Latest main
```

### Severity

annoying

**Comment by abidlabs** [comment]
As discussed via Slack DM, I'd like to give this a shot @pngwn
