### ISSUE TITLE
Does it support modifying the cache /tmp directory

### ISSUE THREAD

**Issue by 17818587795** [gradio-app/gradio#4373]
### Describe the bug

The default /tmp directory space is too small, which often leads to space overflow. Is there a way to modify the default cache directory

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

None

### Logs

```shell
None
```

### System Info

```shell
3.31.0
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @17818587795 ! You can control the directory that’s used with the GRADIO_TEMP_DIR environment variable

**Comment by 17818587795** [comment]
Thank you very much. Setting environment variables is effective！
