### ISSUE TITLE
Curl API Request responses with {“error”:”This app has no endpoint /api/predict/.”} 

### ISSUE THREAD

**Issue by JonasJustus** [gradio-app/gradio#4375]
### Describe the bug

I am using a simple gradio structure:

`import gradio as gr
with gr.Blocks() as demo:
		  with gr.Row():
		    with gr.Column(scale=1, min_width=600): 
....
demo.launch()
`

The App shows me the Use via API Button

curl call I use:
`curl -X POST -H “Content-Type: application/json” -d “{"data":["Hello"]}” http://127.0.0.1:7860/api/predict`

and I get this error:
{“error”:“This app has no endpoint /api/predict/.”}

Is this a bug or do I do something wrong?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr
import random
import time

        

		with gr.Blocks() as demo:
		  with gr.Row():
		    with gr.Column(scale=1, min_width=600):
		            chatbot = gr.Chatbot()
		            msg = gr.Textbox()
		            clear = gr.Button("Clear")

		    def user(user_message, history):
		        return "", history + [[user_message, None]]

		    def bot(history):
		        bot_message = random.choice(["Yes", "No"])
		        history[-1][1] = bot_message
		        time.sleep(1)
		        return history

		    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
		        bot, chatbot, chatbot
		    )
		    clear.click(lambda: None, None, chatbot, queue=False)

		demo.launch()
		return self.prefix + " " + text

### Logs

```shell
shows no logs
```

### System Info

```shell
gradio 2.3.0
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @JonasJustus ! 

If you want your app to have an api route named "/predict" you need to specify it manually. Otherwise you need to use fn_index in the request body.

```python
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column(scale=1, min_width=600):
                chatbot = gr.Chatbot()
                msg = gr.Textbox()
                clear = gr.Button("Clear")


    def user(user_message, history):
        return "", history + [[user_message, None]]

    def bot(history):
        bot_message = random.choice(["Yes", "No"])
        history[-1][1] = bot_message
        time.sleep(1)
        return history

    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        bot, chatbot, chatbot, api_name="predict"
    )
    clear.click(lambda: None, None, chatbot, queue=False)

demo.launch(debug=True)
```

Also, since I assume you want the chatbot response, you need to change the data you send in the request body to be a list of lists. The first element of each sublist is the user message and the second element is the bot response.

```bash
curl -X POST -H "Content-Type:application/json" -d '{"data": [[["Hello", null]]]}' http://127.0.0.1:7860/api/predict
```

<img width="860" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/7989f7da-75e1-4d2a-aaa3-f0ec2d16760e">
