### ISSUE TITLE
Enable show_api and auth from outside launch

### ISSUE THREAD

**Issue by vivekam101** [gradio-app/gradio#4376]
Is there a way we can enable show_api and auth outside launch. We have some difficulty in using launch function as it mounted in fastapi

**Comment by abidlabs** [comment]
Hi @vivekam101 you cannot use Gradio's auth parameter if you are mounting within a fastapi app. However, you could use FastAPI's built-in auth instead. See: https://fastapi.tiangolo.com/tutorial/security/

If you have further questions like this (that are not feature requests or bug reports), please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)

**Comment by vivekam101** [comment]
Thanks. what about exposing it as api.. show_api bit
