### ISSUE TITLE
Error While Installing Setup.py

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#438]
**Describe the bug**
I get an installation error from setup.py, how do you install the requirements?
I think having a requirements file for development would be great for incoming contributors. I suggest piptools compile with requirements.ini, [reference](https://github.com/FarukOzderim/Telegram-Bot-Python-FastAPI/blob/master/requirements.in), https://pypi.org/project/pip-tools/.

**To Reproduce**
- Create a virtual environment
`virtualenv .venv`
- Activate the environment
`source .venv/bin/activate`
- Install the setup.py
`python setup.py install 
`

**Error**
```
  File "/var/folders/mm/6125292542725z88cyz29z000000gn/T/easy_install-q5pciu51/pandas-1.3.5/setup.py", line 18, in <module>
    'numpy',
ModuleNotFoundError: No module named 'numpy'

```

**Device information (please complete the following information):**
 - OS: Macos
 - [Gradio 2.6.2](https://github.com/gradio-app/gradio/commit/d9f302ab82140ea783dc93e2eafe9257839746ef)  

cc: @abidlabs

**Comment by abidlabs** [comment]
Hmm I’ll look into this but what happens when you clone the repo and run: “pip install -e .”

**Comment by FarukOzderim** [comment]
Yeah it worked wonderfully 😅, thanks.
Though development side requirements could still be chosen as you could use linter and formatters in that requirements.
```
pip install -e .

.....
Successfully uninstalled gradio-2.6.2
  Running setup.py develop for gradio

```

**Comment by abidlabs** [comment]
I'll leave this open because we should clarify in our contributing docs how to set up `gradio` locally for development.

**Comment by abidlabs** [comment]
Done thanks for the feedback @FarukOzderim
