### ISSUE TITLE
Can I include custom javascript?

### ISSUE THREAD

**Issue by thuwyh** [gradio-app/gradio#4384]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I want to show the content length of a Textbox. I tried the `change` and `input` API, but the experience is not good.

**Describe the solution you'd like**  
It would be great if I can add a custom js code to the page.

**Additional context**  
None

**Comment by abidlabs** [comment]
Hi @thuwyh I believe #2137 is the same issue, so I'll go ahead and close this. You can also see the existing workaround in #2137.
