### ISSUE TITLE
Feature request: Save request as an attribute in blocks.py's call_function

### ISSUE THREAD

**Issue by hughjk** [gradio-app/gradio#4401]
Description: I would greatly appreciate it if the request could be saved as an attribute in the blocks.py's call_function. This would be important for me, as it would make it easier to know who recently made a request when handling button functions.

That's all you need
![image](https://github.com/gradio-app/gradio/assets/15278107/e72da17f-1ebb-40e5-af6f-b3aa63364901)

**Comment by freddyaboulton** [comment]
Hi @hughjk ! Why not just pass the request to your event handler function and store it wherever you want?

https://gradio.app/docs/#request

**Comment by abidlabs** [comment]
Closing for lack of follow-up, @hughjk please take a look at @freddyaboulton's suggestion and feel free to respond with more details if it doesn't address your issue
