### ISSUE TITLE
How can I get the ip of people using my link?

### ISSUE THREAD

**Issue by mkw18** [gradio-app/gradio#4410]
- [x] I have searched to see if a similar issue already exists.

Hello! I'm running gradio on huggingface, and I want to prevent frequent request from the same ip. I wonder how could I get the ip of other people using my app? Thanks a lot!

**Comment by abidlabs** [comment]
Hi @mkw18 please take a look at the `gr.Request` object (https://gradio.app/sharing-your-app/#accessing-the-network-request-directly), which should allow you to access the IP address of your users.

**Comment by neverho0d** [comment]
How to get gr.Request working with gr.ChatInterface? Adding gr.Request parameter to the callable causes error.

**Comment by abidlabs** [comment]
Ah yeah this is not supported yet @neverho0d. I'll create an issue
