### ISSUE TITLE
A better color chooser in the Image editor

### ISSUE THREAD

**Issue by allo-** [gradio-app/gradio#4412]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I have yet to see a good color picker in a browser. Many are complicated to use and lack features that are common in even basic paint programs. Firefox, for example, suggests a predefined set of colors and requires more clicks to choose a custom color, in Chromium picking a color from the screen doesn't seem to work, and I miss having a palette of recently used colors and maybe a handpicked palette of favorite colors like common graphics programs use.

Especially when using tools like inpaint-sketch in stable diffusion UIs, it would also be useful to have the custom palette/recently used colors available with one click, or possibly next to the drawing area with zero clicks, so you can just choose the color you used before.

**Describe the solution you'd like**  
There are many Javascript libraries for color pickers that do not depend on the browser implementation and look the same across browsers and platforms. Probably some can be easily integrated.

The best would probably be a palette of about 16 colors in a row/column next to the image area, a pick color from image button, a choose color button that opens a good color picker, and some space for a custom palette or a recent colors area.

**Additional context**  
Select a color with Firefox:
- Click the color icon
- Click on the currently used color
- Click the "Custom" plus button
- Choose your color

Choose a different color:
- Do the same
- Even though the dialog looks like you should now have two colors under the "Custom" section, only the second color is listed there (maybe a Firefox bug, an not yet implemented feature, or a bug in the way gradio opens the colorchooser?)
- Switching between only two colors is a lot of work if you don't rely on the preset colors.

Select a color with Chromium:
- Click the color icon
- Click the current color
- A hanging dialog opens, which does not stay open when you do other things
- You can choose the color directly, but the Pick Color from Screen feature picks NAN for the red channel (A Chromium bug?)

Choosing a color with a QtWebengine browser (probably the best at the moment)
- Click the color icon
- Click on the color
- The Qt color picker dialog opens with the features you know from graphics programs like a custom palette, HSV color picker, palette, screen color picker, numeric inputs.
- Choosing a color from the screen doesn't work for working with the Inpaint image, as the dialog is modal and thus the browser window is darkened when the dialog is open.
- Workaround: As you can select colors from other windows, you could open the current image in an additional second window and select the colors from there.

**Comment by abidlabs** [comment]
Hi @allo- I'm not sure I fully understand this issue. Are you suggesting a new component or modifications to the `gr.ColorPicker`?

**Comment by allo-** [comment]
@abidlabs I am not completely sure what grColorPicker does. I am a user of projects that have gradio UIs and I think when I want improvements for UI widgets, I need to ask gradio to implement them and then the other projects can use them or may automatically use them when they update the dependency.

I attached a screenshot what widget I mean.
![grafik](https://github.com/gradio-app/gradio/assets/1482341/ac45b04b-8875-4876-8012-2e074849706f)

**Comment by abidlabs** [comment]
Hey! We've now made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

* A "Rich Textbox" that [allows you to write bold/italics/colored text](https://huggingface.co/spaces/abidlabs/gradio_rich_textbox)
* A "Folium Map Viewer" component that [allows you to use interactive maps](https://huggingface.co/spaces/freddyaboulton/gradio_folium)

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. **In particular, its very fast if you want to build off an existing component**. We've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help. Hopefully this will help address this issue.

**Comment by allo-** [comment]
Are you interested in integrating a new color chooser if there is a component that has a good cross-browser user experience or would this be something that should be implemented downstream projects?

**Comment by allo-** [comment]
What javascript color pickers cannot integrate is picking a color from the screen. But in most cases the important part would be picking a color from a gradio drawing canvas.

Do you have a idea how hard it would be to integrate this with an available color picker component?  
Or maybe the drawing canvas should have two buttons, one to open the colorpicker for choosing colors and one to get an eyedropper that sets the pen color and the selected color in the colorpicker component.

**Comment by abidlabs** [comment]
Sorry @allo- re-reading this issue again, I realized I misunderstood it. I thought this was referring to `gr.ColorPicker`, but you're actually referring to the color chooser in the image editor. We're redesigning the image editor from scratch and should have something out in the next few days. After that, if you're still facing issues, we'd be open to a PR that improves the cross-browser compatibility

**Comment by abidlabs** [comment]
Renamed and relabeled the issue

**Comment by allo-** [comment]
Do you aim for a integrated color chooser or do you want you stick to the html5 input element?

**Comment by allo-** [comment]
When working on the image editor, you may have a look at that issue: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9536

I have no idea if it's gradio or how the webui uses it, but I still have to clear the image area one time and send the image to the editor again before I can start using it.

**Comment by abidlabs** [comment]
cc @pngwn

**Comment by abidlabs** [comment]
Yes as @hannahblair said, we've included a redesigned color chooser in the `gr.ImageEditor` component. Please let us know if you still have concerns.

**Comment by allo-** [comment]
I guess I wait with testing until some downstream projects include it, but it looks like one of the widgets I was thinking of.
I think this implements what I wished. If there would be any problems with the color picker I'll open a new bug.
Thanks for your work on improving the image editor!
