### ISSUE TITLE
Chatbot: limit width of chat bubbles to be the size of the messages

### ISSUE THREAD

**Issue by lucasjinreal** [gradio-app/gradio#4420]
Is there a way to add max width constraints to bubbles containing the messages?

![image](https://github.com/gradio-app/gradio/assets/21303438/8af56935-acf5-4a76-94fa-0e295a8292c5)

**Comment by abidlabs** [comment]
Hi @lucasjinreal what do you mean by bubbles? Can you please provide example code to repro and explain what you are getting vs. what you are expecting?

**Comment by lucasjinreal** [comment]
@abidlabs  Hello, its about ChatBot UI component.

1. As you can see, the bubbles in both incoming and outcoming are have a large free space：

![image](https://github.com/gradio-app/gradio/assets/21303438/4d1b1d1b-12e6-4ece-82b5-63ffdb295909)

Would it better to make it fit automatically to content just like iMessages?

2. My bottom have a TextBox and a Button, how can I make it align vertically?

**Comment by abidlabs** [comment]
Thanks for the clarification, @lucasjinreal I've renamed the issue to reflect #1, it's something we'll think about!

**Comment by lucasjinreal** [comment]
@abidlabs thank u.

I just find a repo using gradio made it, do u know what code they possible use? (nevertheless you are the creator of gradio!)

<img width="1162" alt="261efb275be94aec0368d4af46ed364" src="https://github.com/gradio-app/gradio/assets/21303438/0f610d48-a947-44d3-ba4d-05958283bfd2">

as you can see, their incoming bubble of mine, is limited width

**Comment by abidlabs** [comment]
You can see their code here: https://huggingface.co/spaces/project-baize/chat-with-baize/blob/main/app.py

**Comment by 1ittlesnow** [comment]
`
with gr.Blocks(
        title="Chat with Open Large Language Models",
        theme=gr.themes.Base(),
        css=block_css,
    ) as demo:
`
When you create Blocks, there is a block_css. Ctrl click it. 
Change 'block_css'. 
Add [data-testid = "bot"] and [data-testid = "user"]. 
The property 'max_width' is its limit width of chat bubbles.


`block_css = (
    code_highlight_css
    + """
pre {
    white-space: pre-wrap;       /* Since CSS 2.1 */
    white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
    white-space: -pre-wrap;      /* Opera 4-6 */
    white-space: -o-pre-wrap;    /* Opera 7 */
    word-wrap: break-word;       /* Internet Explorer 5.5+ */
}
#notice_markdown th {
    display: none;
}
#notice_markdown td {
    padding-top: 8px;
    padding-bottom: 8px;
}
#leaderboard_markdown td {
    padding-top: 8px;
    padding-bottom: 8px;
}
"""
)`

`
block_css = (
    code_highlight_css
    + """
pre {
    white-space: pre-wrap;       /* Since CSS 2.1 */
    white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
    white-space: -pre-wrap;      /* Opera 4-6 */
    white-space: -o-pre-wrap;    /* Opera 7 */
    word-wrap: break-word;       /* Internet Explorer 5.5+ */
}
#notice_markdown th {
    display: none;
}
#notice_markdown td {
    padding-top: 8px;
    padding-bottom: 8px;
}
#leaderboard_markdown td {
    padding-top: 8px;
    padding-bottom: 8px;
}
[data-testid = "bot"] {
    max-width: 75%;
    width: auto !important;
    border-bottom-left-radius: 0 !important;
}
[data-testid = "user"] {
    max-width: 75%;
    width: auto !important;
    border-bottom-right-radius: 0 !important;
}
"""
)`

**Comment by abidlabs** [comment]
Thanks @1ittlesnow for the custom css.

We may add it at some point as an option within the chatbot but not a priority right now since there's a workaround. (cc @dawoodkhan82)

**Comment by dawoodkhan82** [comment]
@abidlabs @1ittlesnow We might not add an option to adjust the chat bubble width. But one this we are considering is allowing devs to choose from a few select chatbot styles. One of these styles would include a chatbot where the bubbles are only as wide as the message (along with other style changes).

**Comment by abidlabs** [comment]
Just brainstorming here, but wouldn't it be better to have separate parameters for these options in case someone wants to stick to the default style but have limited-width bubbles?

**Comment by dawoodkhan82** [comment]
Since removing the `style()` method, we would have to add this as a param to the `init` of chatbot or maybe as a theme var? But not completely convinced we want to expose changing things like height/width to devs. Thoughts @pngwn?

**Comment by austinmw** [comment]
Would look nicer IMO if the chat bubbles only extended to the width of the message (from the left or right, depending on user/bot)

**Comment by Keldos-Li** [comment]
> I just find a repo using gradio made it, do u know what code they possible use? (nevertheless you are the creator of gradio!)
> 
> <img alt="261efb275be94aec0368d4af46ed364" width="1162" src="https://user-images.githubusercontent.com/21303438/243894456-0f610d48-a947-44d3-ba4d-05958283bfd2.png">
> as you can see, their incoming bubble of mine, is limited width


Apologize for following up on comments under an issue that hasn't seen new progress for quite some time. However, in fact, as shown in this image, Baize used the code from our [ChuanhuChat](https://github.com/GaiZhenbiao/ChuanhuChatGPT) project to build this demo:

<img width="1194" alt="image" src="https://github.com/gradio-app/gradio/assets/23137268/0b80fae9-33cf-4cb6-882f-66006d80fcc6">

@lucasjinreal You can review our project code here: https://github.com/GaiZhenbiao/ChuanhuChatGPT
