### ISSUE TITLE
Can I automatically add line numbers when inputting using gr.DataFrame

### ISSUE THREAD

**Issue by Annnnnnnnnnnnn** [gradio-app/gradio#4423]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by pngwn** [comment]
I think this is a feature request to add a 'number' column to rows.

**Comment by abidlabs** [comment]
Duplicate of #5054 -- I'll close this one as that one is a little clearer imo
