### ISSUE TITLE
Dollar signs automatically render latex - can happen unintentionally

### ISSUE THREAD

**Issue by aliabid94** [gradio-app/gradio#4428]
Should figure out a better way to explicitly render latex in Chatbot/Markdown, currently can easily happen accidentally

**Comment by freddyaboulton** [comment]
Didn’t this get fixed by https://github.com/gradio-app/gradio/issues/4143

**Comment by pseudotensor** [comment]
How do I disable latex processing for now?  It's very intrusive, and my main use case never involves latex.

**Comment by pseudotensor** [comment]
Found: https://github.com/gradio-app/gradio/issues/4143#issuecomment-1542315064

**Comment by abidlabs** [comment]
A simpler solution would be to just have a flag that enables/disables LaTeX. Not as fully featured, but would probably be a simpler DX. cc @dawoodkhan82
