### ISSUE TITLE
Encountered errors with the queue feature during remote deployment.

### ISSUE THREAD

**Issue by BursonHandsom** [gradio-app/gradio#4432]
### Describe the bug

When deploying sd-webui remotely on platforms like Alibaba Cloud or Colab, whether using the -share option or setting up external access with ngrok, I frequently encounter errors. Upon checking the console, I find that the issues are related to the queue/join functionality. Is there a good solution to resolve this problem? One approach in sd-webui is to address it by adding the --no-gradio-queue flag, but I want to retain the queue feature.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

When deploying sd-webui remotely on platforms like Alibaba Cloud or Colab, whether using the -share option or setting up external access with ngrok, I frequently encounter errors. Upon checking the console, I find that the issues are related to the queue/join functionality. Is there a good solution to resolve this problem? One approach in sd-webui is to address it by adding the --no-gradio-queue flag, but I want to retain the queue feature.

### Logs

```shell
When deploying sd-webui remotely on platforms like Alibaba Cloud or Colab, whether using the -share option or setting up external access with ngrok, I frequently encounter errors. Upon checking the console, I find that the issues are related to the queue/join functionality. Is there a good solution to resolve this problem? One approach in sd-webui is to address it by adding the --no-gradio-queue flag, but I want to retain the queue feature.
```

### System Info

```shell
When deploying sd-webui remotely on platforms like Alibaba Cloud or Colab, whether using the -share option or setting up external access with ngrok, I frequently encounter errors. Upon checking the console, I find that the issues are related to the queue/join functionality. Is there a good solution to resolve this problem? One approach in sd-webui is to address it by adding the --no-gradio-queue flag, but I want to retain the queue feature.
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @BursonHandsom we'd need to have a simper repro than the entire SD Web UI for us to tackle this problem. Can you please see if it's possible to reproduce this problem with a smaller Gradio app and share the code with us?

**Comment by abidlabs** [comment]
Closing -- please feel free to reopen with a simpler repro
