### ISSUE TITLE
Some pictures of car

### ISSUE THREAD

**Issue by RAJ140385** [gradio-app/gradio#4448]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by freddyaboulton** [comment]
Hi @RAJ140385 please don’t spam the issues board with nonsensical issues.

**Comment by pngwn** [comment]
Can you please explain what the problem is in more detail?
