### ISSUE TITLE
There's misunderstanding in https://gradio.app/quickstart/  image example

### ISSUE THREAD

**Issue by Sicolas-Flamel** [gradio-app/gradio#4450]
### Describe the bug

<img width="488" alt="image" src="https://github.com/gradio-app/gradio/assets/76936556/281949e2-63a7-4e07-b9e0-bfd97fd390b4">
gr.Image(type="filepath", shape=...) leads to a misunderstanding.
Actually, type is not a necessary keyword like shape. it should appear there. 
Becasue I tryied gr.Image(type=r"filepath", shape=...) and gr.Image(type=r"filepath", shape=...), but not automately upload the picture. 

And I use gr.Image("filepath", shape=...) . It works.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://gradio.app/quickstart/#an-image-example

### Screenshot

<img width="1068" alt="image" src="https://github.com/gradio-app/gradio/assets/76936556/3461e283-264a-484a-83c4-eb96e7a6e91d">
<img width="1000" alt="image" src="https://github.com/gradio-app/gradio/assets/76936556/06fae262-ad40-4c0a-9d4f-500f330cb291">
<img width="1075" alt="image" src="https://github.com/gradio-app/gradio/assets/76936556/c31f3145-329a-4152-93b0-cef38cc5b940">

### Logs

```shell
demo = gr.Interface(sepia, gr.Image(type = "/Users/fang/Images/帐篷.jpeg", shape=(200, 200)), "image")
without debug = True:
/var/folders/_j/k_blb4kx6yqc867dzljr4fw80000gn/T/ipykernel_12025/1604121107.py:11: UserWarning: You have unused kwarg parameters in Image, please remove them: {'filepath': '/Users/fang/Images/帐篷.jpeg'}
  
with debug = True:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[42], line 11
      8     sepia_img /= sepia_img.max()
      9     return sepia_img
---> 11 demo = gr.Interface(sepia, gr.Image(type = "/Users/fang/Images/帐篷.jpeg", shape=(200, 200)), "image")
     12 demo.launch(debug = True)

File ~/anaconda3/lib/python3.10/site-packages/gradio/components.py:1710, in Image.__init__(self, value, shape, image_mode, invert_colors, source, tool, type, label, every, show_label, interactive, visible, streaming, elem_id, elem_classes, mirror_webcam, brush_radius, **kwargs)
   1708 valid_types = ["numpy", "pil", "filepath"]
   1709 if type not in valid_types:
-> 1710     raise ValueError(
   1711         f"Invalid value for parameter `type`: {type}. Please choose from one of: {valid_types}"
   1712     )
   1713 self.type = type
   1714 self.shape = shape

ValueError: Invalid value for parameter `type`: /Users/fang/Images/帐篷.jpeg. Please choose from one of: ['numpy', 'pil', 'filepath']
```

### System Info

```shell
'3.32.0', MacBook Pro M1, Google browser
```

### Severity

annoying

**Comment by abidlabs** [comment]
Closing for lack of followup
