### ISSUE TITLE
TabbedInterface throws a warning.

### ISSUE THREAD

**Issue by ophiryaniv-ts** [gradio-app/gradio#4462]
Hey all, 
First of all great project...

 Thank

### Describe the bug

Combining two Interfaces with TabbedInterface throws a warning:
`gradio/blocks.py:722: UserWarning: api_name predict already exists, using predict_1`

It can be seen in the example: https://gradio.app/docs/#tabbedinterface-header

Does it has a solution? 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction
```

import gradio as gr

title = "GPT-J-6B"

tts_examples = [
    "I love learning machine learning",
    "How do you do?",
]

tts_demo = gr.load(
    "huggingface/facebook/fastspeech2-en-ljspeech",
    title=None,
    examples=tts_examples,
    description="Give me something to say!",
)

stt_demo = gr.load(
    "huggingface/facebook/wav2vec2-base-960h",
    title=None,
    inputs="mic",
    description="Let me try to guess what you're saying!",
)

demo = gr.TabbedInterface([tts_demo, stt_demo], ["Text-to-speech", "Speech-to-text"])

if __name__ == "__main__":
    demo.launch()

```

### Logs

```shell
gradio/blocks.py:722: UserWarning: api_name predict already exists, using predict_1
```

### System Info

```shell
gradio                    3.23.0
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @ophiryaniv-ts thats expected. All interfaces have an “api_name” of predict so that you can query them programmatically. All api names have to be unique so when two interfaces are combined, gradio will automatically change the api_name of one of them. 

Nothing to worry about here 😊 if you want to suppress this warning I think you can follow what’s done in this thread: https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings

will close for now. Thank you!

**Comment by ophiryaniv-ts** [comment]
Hey @freddyaboulton thank for replying...

Yes, I thought it maybe something like that.

I thought maybe it will be helpful to be able to change the Interface api_name's, so we can avoid the name duplication without a warning...

'gr.Interface(..., api_name=tab1)'

What do you think of that?

**Comment by mangiucugna** [comment]
@freddyaboulton sorry for hijacking a closed thread but with the latest gradio is see this warning and I tried to change the method to a name that cannot possibly be clashing.

```
/.venv/lib/python3.11/site-packages/gradio/blocks.py:8
89: UserWarning: api_name tele_tubbies already exists, using tele_tubbies_1
  warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
```

Is there an issue already open? Should I open a new one or this one needs to be reopened?

**Comment by freddyaboulton** [comment]
No worries at all. Please open a new issue with the code @mangiucugna ! Will help us prioritize it better.
