### ISSUE TITLE
Download images in iterative mode

### ISSUE THREAD

**Issue by noamelata** [gradio-app/gradio#4464]
**Is your feature request related to a problem? Please describe.**  
When generating an image with a iterative interface (generator function that yields images) the images can only be saved once the generator has finished or is stopped.

**Describe the solution you'd like**  
Would it be possible to enable downloading of the image while waiting for the next item to be yielded, or to add a "pause" and "continue" buttons that would enable stopping the iteration and resuming it?

Thank you!

**Comment by abidlabs** [comment]
Thanks @noamelata. Using the download button in the top right corner, its possible to download individual images as they iterate, e.g. try this snippet:

```py
import gradio as gr
import time

def test(x):
    yield "cat.jpg"
    time.sleep(4)
    yield "cheetah.jpg"
    time.sleep(4)
    yield "cat.jpg"


gr.Interface(test, "textbox", "image").launch()
```

You can also use the `gr.Gallery` component if you'd like to see all of the images together.
