### ISSUE TITLE
I think we need to add process-related identifiers to the routing addresses of FastAPI in Gradio.

### ISSUE THREAD

**Issue by sanbuphy** [gradio-app/gradio#4478]
- [ √] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
None

**Describe the solution you'd like**  
None

**Additional context**  

I would like to implement multiple Gradio services within a single domain IP in Gradio, but I found that the routing addresses are fixed in FastAPI. Even if I use Nginx for port forwarding, the requests will still go to a certain routing service under the same IP domain instead of targeting particular processes, which results in newly opened Gradio requests being directed to previously opened Gradio services, making it impossible to open multiple Gradio services on a single machine. I have tried using share=True, but it is temporary and uses Gradio's official proxy server, while I want to host it on my own server. Are there any other methods or solutions? Thank you.

**Comment by abidlabs** [comment]
Hi @sanbuphy it's possible to set up multiple Gradio apps on the same machine. See this related issue for more details: https://github.com/gradio-app/gradio/issues/2979

I'll go ahead and close this issue, but if you feel like there's still a bug or feature request here, please feel free to provide more details including code and/or nginx conf that you've tried.
