### ISSUE TITLE
How to add TailWindCSS to Gradio?

### ISSUE THREAD

**Issue by manel00** [gradio-app/gradio#4479]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
TailwindCSS does not work

**Describe the solution you'd like**  
May I know if could be in the future? because gr.HTML can represent HTML but would be nice to show some bootstrap or tailwind

Thank you so much! very interesting library

**Comment by abidlabs** [comment]
Hi @manel00, for general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). Please also provide more details on what you've tried and what the result has been vs. what you expected. (I'll close this issue)
