### ISSUE TITLE
add app_kwargs to mount_gradio_app

### ISSUE THREAD

**Issue by charlesfrye** [gradio-app/gradio#4488]
- [x] I have searched to see if a similar issue already exists.

I like the interoperability with FastAPI and related tooling (eg OpenAPI, #4054), and I'd love to be able to take full advantage of it when using `mount_gradio_app`.

Specifically, I want to be able to configure the final FastAPI app by passing `app_kwargs`, as you can when using `Blocks.launch` (#4282).

From some quick testing, [in-lining the code from `mount_gradio_app`](https://github.com/gradio-app/gradio/blob/3383d8872bcc01774759e0e25332c031eb53fc30/gradio/routes.py#L809-L821) and just adding in some `app_kwargs` to the `App.create_app` call just works.

Happy to implement this in a PR! Just let me know it's wanted and if there's anything in the repo I can look at for how to test the changes.

**Comment by abidlabs** [comment]
Hi @charlesfrye makes sense to me, please feel welcome to open a PR!
