### ISSUE TITLE
About enabling the use of websocket functionality in queue.

### ISSUE THREAD

**Issue by bobshen0721** [gradio-app/gradio#4489]
### Describe the bug

First of all, my environment is in a corporate setting, with the network located behind a firewall.

My requirements are:
I want to implement a Websocket feature, to allow other computers within the local network to use the webpage I created.
I want to implement a webpage with websocket functionality, that is, the output text can appear character by character.

The problems I encountered are:
The webpage can be successfully created, but the data does not appear. I have tested the same code on my home computer and it works normally, so my initial suspicion is a proxy or firewall issue. However, the corporate environment does not allow turning off the proxy and firewall. I asked the network administrator and he doesn't know how to set it up. I wonder what network segments or port need to be unblocked?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr
import time

def text_generator(input_text):
    for i in range(10):
        yield f"{input_text} {i}"
        time.sleep(1)

iface = gr.Interface(fn=text_generator, inputs='text', outputs='text')
iface.queue()
iface.launch(server_name='0.0.0.0',server_port=8000)

### Screenshot

The following is the error message generated when I open the webpage.

![Issue](https://github.com/gradio-app/gradio/assets/63269732/f80cd27d-f451-412a-b92e-44ac32d55de4)

### Logs

```shell
Error message

ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.
```

### System Info

```shell
gradio version: 3.33.1
os:win 11 Enterprise Edition
Chrome 114.0.5735.110
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @bobshen0721 ! Not sure how best to help you since it will be hard for us to reproduce this. Do gradio apps without the queue work behind your firewall? The queue uses the `/queue/join` route - maybe you can ask your system administrator to allow websocket connections on that route. 

Since this isn't an issue with the gradio library itself, let's move this to the github discussions page or discord. Will close for now.

**Comment by bobshen0721** [comment]
Hello @freddyaboulton , the program can run normally without the queue. However, if the queue is enabled, it doesn't work.
