### ISSUE TITLE
Web Browser crush down when I make Image canvas as input and output in same time

### ISSUE THREAD

**Issue by C00pe2** [gradio-app/gradio#4492]
### Describe the bug

you can see  I use image2 as [click button]'s input, also I use it as [paste button]'s output.
Interesting, that action will make my computer running slow when I open the gradio webUI and Click the [paste button] ,the program even will cursh down.
I think this action maybe lead to the frequent interaction between frontend and backend，that process will cause computer crush down.
I'm not sure is it the real reason, so i came here to see if there are anyone have met that problem.
By the way, I want to solve this problem because I want to use it in prompt point in SAM model .

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

my demo is under below:
```py
import gradio as gr

def image_show(image):
    return image, image, image

def image_none(image):
    return None

with gr.Blocks() as demo:
    image1 = gr.Image(source="upload",label="input_image")
    image2 = gr.Image(label="show_image1", tool="color-sketch", brush_radius=40)
    image3 = gr.Image(label="show_image2", tool="color-sketch", brush_radius=40)
    image4 = gr.Image(label="show_image3", tool="color-sketch", brush_radius=40)
    clip = gr.Button("click here")
    paste = gr.Button("paste")
    clip.click(image_none, inputs=image2, outputs=None)
    paste.click(image_show, inputs=image1, outputs=[image2,image3,image4])

demo.launch()
```

### Logs

```shell
No
```

### System Info

```shell
gradio 3.28.0
```

### Severity

annoying

**Comment by abidlabs** [comment]
Can confirm this is still an issue in the latest version of `gradio`. 

Might be related: https://github.com/gradio-app/gradio/issues/4159

**Comment by C00pe2** [comment]
> Can confirm this is still an issue in the latest version of `gradio`.
> 
> Might be related: #4159

Thanks for your replying!
