### ISSUE TITLE
Websocket connection failed when run behind nginx

### ISSUE THREAD

**Issue by bangpradyumna** [gradio-app/gradio#4493]
### Describe the bug

Hello, 
I have 3 gradio apps, all running behind nginx using supervisor. The other 2 are working fine but the third - a chat app with a chatbot is giving error. One difference is that in this app I am using the queue()

`demo.queue().launch(server_name="0.0.0.0", server_port=8002, debug=True, show_api=False, root_path="/chat")`

Error in devtools console : 
`WebSocket connection to 'wss://<ip>/chat/queue/join' failed`

Screenshot :
![image](https://github.com/gradio-app/gradio/assets/6296142/5632f956-6853-48d8-b26e-5ff21628bf1f)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`demo.queue().launch(server_name="0.0.0.0", server_port=8002, debug=True, show_api=False, root_path="/chat")`

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/6296142/bf865a3c-7c76-4de3-bc6e-71f60eb00f1b)

### Logs

```shell
`WebSocket connection to 'wss://<ip>/chat/queue/join' failed`
```

### System Info

```shell
'3.34.0', Ubuntu 20.04, Chrome
```

### Severity

blocking all usage of gradio

**Comment by bangpradyumna** [comment]
Adding the following to my Nginx config location block solved the issue :
`  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";`

**Comment by timiil** [comment]
the link seems 404 ... 

> Hi @bangpradyumna thanks for sharing your solution. That approach is exactly what is described here: https://gradio.app/running-gradio-on-your-web-server-with-nginx/

**Comment by tristanreid** [comment]
Updated link:  https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx
