### ISSUE TITLE
Output images are downloaded to the current directory when using `gradio_client` for `gr.Gallery`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#4494]
### Describe the bug

Not sure if this is a bug or as intended, but `gradio_client.Client` saves output images of `gr.Gallery` in a directory under the current directory, while files are downloaded to a directory under `/tmp` for `gr.Audio`, `gr.Model3D`, and `gr.Video`, and `gr.Image` is downloaded to `/tmp`.

I don't like this behavior because it clutters my working directory and because it's not easy to delete generated directories as they have random names generated by `uuid.uuid4()`.

It would be nice if the outputs of `gr.Gallery` are also downloaded to a directory under `/tmp`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
from gradio_client import Client

client = Client('stabilityai/stable-diffusion')
out = client.predict('an astronaut riding a horse', '', 9, fn_index=1)
```

### Logs

```shell
n/a
```

### System Info

```shell
gradio==3.34.0
gradio_client==0.2.6
```

### Severity

annoying

**Comment by abidlabs** [comment]
Looks like a bug indeed!

**Comment by abidlabs** [comment]
This is why the working directory gets cluttered when running the pytests locally as well, which has been annoying me for a while. Will fix!
