### ISSUE TITLE
Allow specifying the download directory for `gradio_client.Client`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#4495]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

Related to https://github.com/gradio-app/gradio/issues/4494

Files under `/tmp` will be deleted, so we need to move them if we want to keep them. It would be useful if it was possible to specify download directory.

**Comment by freddyaboulton** [comment]
Makes sense @hysts !
