### ISSUE TITLE
Cut off chatbot responses

### ISSUE THREAD

**Issue by austinmw** [gradio-app/gradio#4499]
### Describe the bug

Hi, responses in my chatbot window are cut off intermittently.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Here's the app code:

```python
with gr.Blocks() as demo:
    gr.Markdown("# SageMaker Docs Chat 🤗")
    gr.Markdown("### Ask me question about Amazon SageMaker!")

    chatbot = gr.Chatbot(label="Chat history")
    message = gr.Textbox(label="Ask me a question!")
    clear = gr.Button("Clear")

    def user(user_message, chat_history):
        return gr.update(value="", interactive=False), chat_history + [[user_message, None]]

    def bot(chat_history):
        user_message = chat_history[-1][0]
        llm_response = qa({"question": user_message})
        bot_message = llm_response["answer"]
        chat_history[-1][1] = ""
        for character in bot_message:
            chat_history[-1][1] += character
            time.sleep(0.005)
            yield chat_history

    response = message.submit(user, [message, chatbot], [message, chatbot], queue=False).then(
        bot, chatbot, chatbot
    )
    response.then(lambda: gr.update(interactive=True), None, [message], queue=False)
    clear.click(load_chain, None, chatbot, queue=False)  # reset qa when clicked

demo.queue()
demo.launch()
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/12224358/540bd19d-c464-4f03-ad61-59006d1856a1)

### Logs

```shell
No errors.
```

### System Info

```shell
- Gradio v3.34.0
- Edge browser
- Amazon Linux 2
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Hi @austinmw in order for us to figure out what the issue is, we'll need to know what those messages are that are causing the Chatbot bubbles to collapse. Can you inspect element to see what the messages are? It would be great if you can provide us a repro that doesn't depend on the external function `qa`.

**Comment by austinmw** [comment]
Hi, thanks for your response. I will try to create a much more basic repro. Currently the `qa` object is a langchain `ConversationalRetrievalChain` which uses SageMaker endpoints, so I can't easily share it as is.

**Comment by austinmw** [comment]
Ah, while checking out your suggestion I found that this happens because the bot sometimes returns only "\n". I guess this is not a bug after all, thanks!
