### ISSUE TITLE
[Blocks] Need for multiple separate interfaces

### ISSUE THREAD

**Issue by ejohb** [gradio-app/gradio#450]
**Is your feature request related to a problem? Please describe.**

I need to host a model that takes one of two inputs (e.g. text _or_ an image, but not both). Because the inputs are so different, they each need their own data types, outputs, examples, pull-downs, etc.

I don't seem to be able to achieve this in a non-hacky way. I've tried using `gr.Parallel` but that requires unified input types. 

Plus using a single, two-input interface/function means all the examples and their arguments, etc. get run together, one of the outputs is always empty, and it's just confusing to use.

**Describe the solution you'd like**

Ideally there would be some kind of `gr.Stack` or `gr.Sequence` container object that would simply stack two separate interfaces, or display them in a tabbed interface, etc.

**Comment by abidlabs** [comment]
Hi @ejohb thanks for creating this issue. Your use case makes a lot of sense. We do have "stacked" interfaces on our roadmap towards the end of January, so we'll keep you updated on this. 

In the meantime, the best workaround I would suggest is to have two inputs to your function, an image and a textbox, but for the `gr.inputs.Image`, set the `optional` parameter to `True`. Then, in your function, you can check if the image parameter is None, or if the textbox is empty, and handle the two cases accordingly 

(cc @aliabd)

**Comment by ejohb** [comment]
> Hi @ejohb thanks for creating this issue. Your use case makes a lot of sense. We do have "stacked" interfaces on our roadmap towards the end of January, so we'll keep you updated on this.
> 
> In the meantime, the best workaround I would suggest is to have two inputs to your function, an image and a textbox, but for the `gr.inputs.Image`, set the `optional` parameter to `True`. Then, in your function, you can check if the image parameter is None, or if the textbox is empty, and handle the two cases accordingly
> 
> (cc @aliabd)

Wonderful. Thanks very much for your reply.

**Comment by abidlabs** [comment]
I'm actually going to keep this open until we ship the feature :)

**Comment by JuanCarlosMartinezSevilla** [comment]
Hi everyone! 

I'm currently trying to use Gradio in a project and I'm facing the same problem, I can't launch different interfaces in the same page, without reloading with F5. 

I guess for me the solution will be to add something like an event (on_click) and depending the component clicked launch the wanted interface, inside the same page. Or something like the "live" feature that updates the output when a change is made but with the interfaces visibility.

My use case will be perfect if I could load dynamically different interfaces in the same page. Imagine the user can choose in a first step between a data augmentation function or training a model. When he selects the option he wants the interface related to that functionality should load. Also could be interesting being able to call from the main interface others and from the ones called launch more (nesting interfaces).

This is my point, from what I've read in this issue you guys are working hard to add this feature to Gradio, hope it's sooner than later.

Thank you very much,
Juan Carlos.

**Comment by abidlabs** [comment]
Thanks @JuanCarlosMartinezSevilla we are aiming to get a beta out in the next week and will respond here to let you know as well as on [our discord](https://discord.com/invite/feTf9x3ZSB). Thanks so much for the detailed explanation!

**Comment by abidlabs** [comment]
Hi @ejohb and @JuanCarlosMartinezSevilla, thanks for opening up this issue. We have just beta released `TabbedInterface`, which allows you to combine related demos together. You can try it by `pip install gradio==2.9b7`. 

Here is how you use it (the example is kind of silly, but hopefully it conveys the point):

```py
import gradio as gr

io1 = gr.Interface(
    lambda x, y, z: "sax.wav",
    [
        gr.Slider(label="pitch"),
        gr.Slider(label="loudness"),
        gr.Audio(label="base audio file (optional)"),
    ],
    gr.Audio(),
)

io2 = gr.Interface(
    lambda x, y, z: "flute.wav",
    [
        gr.Slider(label="pitch"),
        gr.Slider(label="loudness"),
        gr.Audio(label="base audio file (optional)"),
    ],
    gr.Audio(),
)

gr.TabbedInterface(
    [io1, io2], ["Saxophone", "Flute"]
).launch()
```

Screenshot (with 4 tabs instead of 2 but the same idea):
![image](https://user-images.githubusercontent.com/1778297/164308303-33c91a71-3b38-4a52-b57a-405b9786c10b.png)

Full example here: https://github.com/gradio-app/gradio/blob/main/demo/blocks_neural_instrument_coding/run.py

**Comment by ejohb** [comment]
> Hi @ejohb and @JuanCarlosMartinezSevilla, thanks for opening up this issue. We have just beta released `TabbedInterface`, 
> Full example here: https://github.com/gradio-app/gradio/blob/main/demo/blocks_neural_instrument_coding/run.py

What great service. Thank you so much!

**Comment by JuanCarlosMartinezSevilla** [comment]
Oh wow!!! I recieved this email and didnt notice!!! What a great job you guys are doing, its amazing!!! Thank you so much.

PS: As a comment, yesterday I was using Gradio @abidlabs and when the Google Colab theme is set to dark this is how it looks...

![image](https://user-images.githubusercontent.com/97530443/166949171-6043b372-33eb-4ea5-8af4-2d816407c78e.png)
