### ISSUE TITLE
Hold music while waiting for model to respond

### ISSUE THREAD

**Issue by lakshman111** [gradio-app/gradio#4502]
**Is your feature request related to a problem? Please describe.**  
After a user calls a model, there is usually a wait time with a "Loading" animation.

**Describe the solution you'd like**  
It would be nice if we could add "hold music" while the user was waiting for the response.

**Additional context**

**Comment by abidlabs** [comment]
Hi @lakshman111 you could do something like this by playing an audio file using the `_js` parameter in an event trigger, then running your function, and then stopping the music. You can read more about how to use `.then()` here: https://gradio.app/blocks-and-event-listeners/#running-events-consecutively

This is too niche to build into the library so I'll go ahead and close this issue.

**Comment by freddyaboulton** [comment]
Hi @lakshman111 ! This might be possible without _js with the new autoplay #4453 for audio (you can show/hide an audio when a prediction is submitted/completed).

**Comment by abidlabs** [comment]
@freddyaboulton's suggestion's even better!
