### ISSUE TITLE
[`gr.Dropdown`] Options with whitespace in name leads to invalid query selector 

### ISSUE THREAD

**Issue by xenova** [gradio-app/gradio#4503]
### Describe the bug

When testing out this HF space: https://huggingface.co/spaces/facebook/MMS, I selected a language from the dropdown, and when attempting to select another language, it throws an error: `Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': 'li[data-value="abi: Abidji "]' is not a valid selector. (DropdownOptions.svelte:19)`

Similar to https://github.com/gradio-app/gradio/issues/4292

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Go to https://huggingface.co/spaces/facebook/MMS
2. Select a language from the dropdown
3. Select another language from the dropdown. This will throw the error.

### Screenshot

The dropdown becomes empty:
![image](https://github.com/gradio-app/gradio/assets/26504141/567660a3-4855-4d3a-b92a-3367de130ea9)

And this error is logged in the console:
![image](https://github.com/gradio-app/gradio/assets/26504141/f57fab91-75dc-4825-b669-e46f85973798)

### Logs

```shell
Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': 'li[data-value="abi: Abidji "]' is not a valid selector.
    at Je.t.$$.update (https://facebook-mms.hf.space/assets/index-315bc3fa.js:1:3366)
    at Dr (https://facebook-mms.hf.space/assets/index-607392ea.js:4:1833)
    at lr (https://facebook-mms.hf.space/assets/index-607392ea.js:4:1548)
```

### System Info

```shell
Latest version of chrome, and whichever version of gradio that is shipped with HF spaces.
```

### Severity

serious, but I can work around it

**Comment by lcrh** [comment]
Similar to https://github.com/gradio-app/gradio/issues/4292

**Comment by pngwn** [comment]
The issue here is the whitsepace i think. @radames had a similar issue. This issue is basically the same as #4292 in that there are invalid characters.

We could escape those character but we shouldn't be using `document. querySelector` in a svelte component at all. The fix is to refactor the component not to use that.

cc @hannahblair @dawoodkhan82
