### ISSUE TITLE
Timeout after 60seconds even with queue()

### ISSUE THREAD

**Issue by Taeuk-Jang** [gradio-app/gradio#4504]
### Describe the bug

So whatever I do, if the function call takes longer than 60 seconds, it breaks down.
I tried all the related solutions posted in the issues including demo.queue().
I even tired enable_queue in launch method.
But none worked out for me.

Similar to others, I get the error in the web:

Something went wrong
Unexpected token '<', "<html> <h"... is not valid JSON

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
def add_text(history, text):
    global query
    query = text
    
    print(query)
    time.sleep(65)
    chat_response = f'What you said is : {query}'    
    print(chat_response)
               
    return history + [(text, chat_response)], ""

with gr.Blocks() as demo:
    state = gr.State([])
    chatbot = gr.Chatbot().style(height=500)   
    
    message = gr.Textbox(show_label=False, placeholder="Enter text and press enter",).style(container=False) 
    message.submit(add_text, [chatbot, message], [chatbot, message], queue=False)
demo.queue()
demo.launch(share=True, debug = True, inline= False, )
```

### Logs

```shell
No error output
```

### System Info

```shell
I tested on gradio verion 3.34, 3.32, 3.18. None worked.
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @Taeuk-Jang , you need to set `queue=True` in 

```
message.submit(add_text, [chatbot, message], [chatbot, message], queue=False)
```

otherwise the queue is disabled for that event!
