### ISSUE TITLE
Visible attribute has no effect on gradio.Group()

### ISSUE THREAD

**Issue by lcrh** [gradio-app/gradio#4505]
### Describe the bug

This is the same issue as in https://github.com/gradio-app/gradio/issues/2246, which was fixed and seems to have regressed as of 3.34.0.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See the repro in https://github.com/gradio-app/gradio/issues/2246

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/14020730/8aba39e1-9550-4bfb-970f-ff36fe660fd2)

### Logs

```shell
Running on local URL:  http://127.0.0.1:7861
Running on local URL:  http://127.0.0.1:7861
Running on public URL: https://4b374dd45cea09ab90.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
```

### System Info

```shell
3.34.0, Windows, Chrome Version 114.0.5735.110 (Official Build) (64-bit)
```

### Severity

serious, but I can work around it

**Comment by apolinario** [comment]
This issue seems to have regressed on `3.36.1`
