### ISSUE TITLE
latex processing too greedy for chatbot interface

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#4506]
### Describe the bug

```
The RWA for March 31, 2023, is $1,243,787. This is calculated by multiplying the total RWAs at March 31, 2023, by the minimum ratio required to avoid restrictions on capital distributions and discretionary bonus payments. The minimum ratio required to avoid restrictions on capital distributions and discretionary bonus payments is 8.0%. Therefore, the RWA for March 31, 2023, is $1,243,787 multiplied by 8.0%, which equals $102,347.
```
gets turned into:

![image](https://github.com/gradio-app/gradio/assets/2249614/dbf47739-b9d7-4058-ae08-845aba56dd78)

See this all the time when there are $ in text.  How do I prevent this?  Do I need to escape every $?  Or should gradio be less greedy?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

As above

### Screenshot

As above

### Logs

```shell
As above
```

### System Info

```shell
gradio==3.34.0
gradio_client==0.2.6
jon@pseudotensor:~/h2
```

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks @pseudotensor, agreed. Same issue as #4428 so I'll close

**Comment by pseudotensor** [comment]
How do I work-around?  It's really bad.

**Comment by pseudotensor** [comment]
That didn't work.  I converted it to `\\$` or `\$` and it still did same thing.  I ended up using a small dollar sign replacement for now.
