### ISSUE TITLE
Copy button not working in code blocks for chatbot

### ISSUE THREAD

**Issue by dawoodkhan82** [gradio-app/gradio#4514]
### Describe the bug

![image](https://github.com/gradio-app/gradio/assets/12725292/c39c841a-0707-4e4b-abce-e462ffa0fb9f)

Copy button is not rendered, instead leaves white space.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

code = """
```python
def greet(x):
    return "hello, " + x```
"""

message = [(
    "write a python program",
    code
)]

with gr.Blocks() as demo:
    gr.Chatbot(message)
    
demo.launch()
```

### Logs

```shell
N/A
```

### System Info

```shell
N/A
```

### Severity

annoying

**Comment by dawoodkhan82** [comment]
mentioned here https://github.com/gradio-app/gradio/pull/4491/#issuecomment-1589243150

**Comment by abidlabs** [comment]
Thanks @dawoodkhan82 I'm going to add this to 3.x as this is pretty important (and we need to get this fixed before doing a release)
