### ISSUE TITLE
devcontainer postCreateCommand fails

### ISSUE THREAD

**Issue by charlesfrye** [gradio-app/gradio#4520]
### Describe the bug

Thanks for offering a devcontainer! Made it much easier to do my first PR.

But the postCreateCommand failed for me, which made my onboarding rougher than it needed to be.

The troublesome code is [here](https://github.com/gradio-app/gradio/blob/d65512cb3a91e2c5b6abf70b52f56a51195c47e7/.devcontainer/devcontainer.json#L34).

One issue was that the second step in the command is just `scripts/install_test_requirements.sh` instead of `bash scripts/install_test_requirements.sh` -- unlike the other two steps, which are prefixed with `bash`. So you get a perms error.

Additionally, the smallest Codespace on GitHub fails with an OOM error when running the final step. I believe the workaround is to set some configuration in GitHub Codespaces to make sure you developers always get the right instance type, but I'm not sure.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Create a new Codespace and wait for the postCreateCommand to run. It errors out with a permissions failure when installing test requirements. Run `bash scripts/install_test_requirements.sh` to resolve.

Then try running `bash scripts/build_frontend.sh` and observe an OOM failure if you are in the smallest Codespace instance (2-core, 4GB RAM). Specifically, its a system exit code 143, which a cursory Google search suggests is called by containers when they hit the memory limits imposed by the host OS.

### Logs

```shell
Sorry, forgot to screenshot or copy. Should be easy to repro with Codespaces though!
```

### System Info

```shell
devcontainer on GitHub CodeSpaces
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment]
Thanks for reporting @charlesfrye ! Will take a look soon
