### ISSUE TITLE
Avatar in Chatbot or displaying USER/CHATBOT Name

### ISSUE THREAD

**Issue by eshaanagarwal** [gradio-app/gradio#4535]
Hi i was making a chatbot powered by a LLM. I would be using the gr.ChatBot for this.
 I want to add avatars for USER and BOT ( even something like displaying the name would also work) and I also want to display the time taken to respond to that query. I can get the time taken that isn't an issue but how do i format the text for user or bot so that shows the time.
Is there any feature available for this. If it is , can you pls point it to me. Thanks

**Comment by eshaanagarwal** [comment]
> Since markdown (and html) is supported in the messages, you could just add that formatting to your responses as a header?
> 
> Poor quick example:
> 
> ### ![BOT logo](https://camo.githubusercontent.com/62838bf121c482fd1cc42d45e4438c1f2428087303ed879f69e6ed28c3cc8207/68747470733a2f2f67726164696f2e6170702f6173736574732f67726164696f2e737667). I AM BOT
> Hello this is BOT
> 
> > 01-01-22 01:01:01
> 
> markdown "code"
> 
> ```
> ### ![BOT logo](https://gradio.app/assets/gradio.svg).  I AM BOT 
> 
> Hello this is BOT
> 
> > 01-01-22 01:01:01
> ```

Hey i wanted to reduce the font of time taken to response etc. I dont think that part of markdown is supported yet. Can you help me with that ?

**Comment by eshaanagarwal** [comment]
> I'd just switch to HTML; then you can set the text weight to your liking. (and can get fancy with your time, etc)

so i can simply pass that too as a string and it parses > How can we do that ?

**Comment by eshaanagarwal** [comment]
Also the avatars arent coming like what you said.
<img width="843" alt="image" src="https://github.com/gradio-app/gradio/assets/78371148/68f22032-ea60-4b28-9c74-d82e321254eb">

**Comment by abidlabs** [comment]
Hi @eshaanagarwal, we have a related issue: #3769. For general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
