### ISSUE TITLE
The demo can not properly shows on public url

### ISSUE THREAD

**Issue by littlecay** [gradio-app/gradio#4545]
### Describe the bug

I ran a deeplearning net work and wraped it in gradio. I can run the demo though local url. However, when I share the public url to others, they failed to open it. The situation is discribed below:

On a chrome browser, I can open the url and manipulate the demo correctly, but if I reload the page, the page will disappear--only a blank page shown. And on a edge browser, I can only get a blank page, never reach the demo. But on a firefox browser, I can always success, no matter how I refresh the page.

No added warnings and errors even infos shows on the server comand line.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://e71fb48f07d16529.gradio.app/

### Screenshot

Just a blank screen

### Logs

```shell
no logs added shows on the server cmd line
```

### System Info

```shell
Gradio = 3.11.0 server on ubuntu20.04
```

### Severity

annoying

**Comment by abidlabs** [comment]
Will close for lack of follow up

**Comment by littlecay** [comment]
> Hi @littlecay the share link is down. Instead, can you share the code used to create the demo so that we can run it ourselves and see if we are able to create a share link?
> 
> Furthermore, you are using a much older version of gradio -- can you please try again with the latest version of `gradio`?

sorry for my late replying. https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/contrib/SegmentAnything/scripts/amg_paddle.py
this is the script I used which contains the gradio. I checked the code and do not see anything abnormal.
BTW, I located in China, mainland. will this affect my usage of gradio public url?
