### ISSUE TITLE
audio.stop_recording, how can the audio itself be used as input to the function in this event?

### ISSUE THREAD

**Issue by Nancis1130** [gradio-app/gradio#4547]
I need to establish an event that occurs when recording is stopped, and the input for the event is the recorded audio.
When I do this, the function does not get input, the input is None.

```
def test(ori):
    print(ori)
    return 'hi'
    
with gr.Blocks() as demo:
    with gr.Row():
        audio = gr.Audio(source='microphone', label='请输入语音', scale=1)
        text = gr.Textbox(scale=2.5)
        sub = gr.Button('submit', scale=0.5)
    audio.stop_recording(test, inputs = audio, outputs = text)

if __name__ == "__main__":
    demo.launch()

```

**Comment by Nancis1130** [comment]
My version is 3.25.0.
What I want to achieve is that when I click the "stop Recording" button, the recorded audio can automatically serve as input to a certain function. 
If the method "audio.stop_recording" is incorrect, please point it out! I really need this, thank you!

**Comment by freddyaboulton** [comment]
Hi @Nancis1130 ! You can use `.change` event in the meantime but I believe the `stop_recording` event should work as you describe so will look into it. cc @pngwn

**Comment by pngwn** [comment]
This seems odd to me because, if I'm understanding, the function is executed (so the event is working) but the input is incorrect. 

But all of our events work pretty much the same as far as I understand. 

Will try to repro.

**Comment by Nancis1130** [comment]
> Hi @Nancis1130 ! You can use `.change` event in the meantime but I believe the `stop_recording` event should work as you describe so will look into it. cc @pngwn

This method worked, I really appreciate it!

**Comment by Nancis1130** [comment]
> This seems odd to me because, if I'm understanding, the function is executed (so the event is working) but the input is incorrect.
> 
> But all of our events work pretty much the same as far as I understand.
> 
> Will try to repro.

Thank you for your reply. I started the HTTP service using a remote server IP and port number. I'm not sure if this is the cause of the problem.
Additionally, when using the chatbot component, I referred to the [chatbot_streaming](https://huggingface.co/spaces/gradio/chatbot_streaming). However, I found that when I tested locally, the chatbot could stream full output, while when I started the service on a remote server, it could only output one or a few characters.
I have been using Gradio for a short period of time, so I'm sorry if I need to open a new issue to raise this issue.
When the service is local:
![VUXG}DTV J)_OUZCUD0V_W7](https://github.com/gradio-app/gradio/assets/68219213/5c91c670-4370-4012-b3ff-da96b14d1410)
When the service on a remote server:
![PEKN36D)D37~65~NPC H4EN](https://github.com/gradio-app/gradio/assets/68219213/39173eae-1e17-4c94-b35a-349aaa0afbd3)

My code:
```
import gradio as gr

def test(question, history):
    bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
    history[-1][1] = ""
    for char in bot_message:
        history[-1][1] += char
        yield history
with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    with gr.Row(elem_id="output-container"):
        audio = gr.Audio(source='microphone', type='filepath', scale=1)
        text = gr.Textbox(lines = 2, scale=3)
        sub = gr.Button('submit', scale=1)
    audio.change(asr, audio, text)

    response = sub.click(user, [text, chatbot], [text, chatbot], queue=False).then(
         gpt, [text, chatbot], chatbot
     )
    response.then(lambda: gr.update(interactive=True), None, [text], queue=False)

demo.queue().launch()
```

**Comment by abidlabs** [comment]
Hi @Nancis1130 for the chatbot issue, yes please create a new issue, but please first confirm that it is broken on the latest version of gradio (3.35.2)

**Comment by Nancis1130** [comment]
> Hi @Nancis1130 for the chatbot issue, yes please create a new issue, but please first confirm that it is broken on the latest version of gradio (3.35.2)
Thank you for your reply. Version 3.25.2 solves the problem.

**Comment by Nancis1130** [comment]
> Hi @Nancis1130 for the chatbot issue, yes please create a new issue, but please first confirm that it is broken on the latest version of gradio (3.35.2)

Thank you for your reply. Version 3.25.2 solves the problem.
