### ISSUE TITLE
autoplay not working when providing new files inside function

### ISSUE THREAD

**Issue by theoclark** [gradio-app/gradio#4549]
### Describe the bug

Autoplay doesn't work when multiple calls are made, even though the underlying audio file has changed. 

In the example below, when the button is pressed for the first time the first file will autoplay. However, autoplay does not work for the second file when the button is pressed the second time.

I want to create a streaming audio output so that, when new audio is received, it is automatically played. Without this being fixed I can't see a way around it.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

audio_files = [path1, path2]
idx = 0

def output():
    global idx
    file = audio_files[idx]
    idx += 1
    return file

with gr.Blocks() as demo:
    audio = gr.Audio(type="filepath", label="Audio", visible=False, autoplay=True)
    button = gr.Button(value="play")
    button.click(output, outputs=[audio])
    
demo.launch()
```

### Logs

```shell
There is no error log - the audio still plays when you press it manually.

Looking through the code, I suspect this function is the culprit: https://github.com/gradio-app/gradio/blob/ec8af6c0937a3223532779d5f1dd50312674a307/js/audio/src/Audio.svelte#L264
```

### System Info

```shell
3.35.2
```

### Severity

blocking all usage of gradio

**Comment by pngwn** [comment]
Thanks for the report! Will take a look.
