### ISSUE TITLE
Dropdown is cleared on focus

### ISSUE THREAD

**Issue by missionfloyd** [gradio-app/gradio#4555]
### Describe the bug

When clicking or otherwise focusing a dropdown with `allow_custom_value=True`, the current value is cleared and is not restored when focus is lost.

Only seems to affect the frontend, the value is not updated unless another is selected or entered. Leaving it blank causes it to return the previous value.

Ideally, the value shouldn't be cleared at all (with `allow_custom_value=True` anyway). We're unable to edit the value without having to enter it again.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

demo = gr.Interface(lambda x: x, inputs=gr.Dropdown(choices=["A", "B", "C"], allow_custom_value=True), outputs="text")
demo.launch()
```

### Logs

```shell
n/a
```

### System Info

```shell
Gradio 3.35.2
Python 3.10.11
Windows 10
Edge 114.0.1823.51
```

### Severity

annoying

**Comment by Muhtasham** [comment]
Also Dropdown with long strings breaks down and doesn't let choose other values

**Comment by abidlabs** [comment]
Hi @Muhtasham can you create a new issue if your issue is not already covered by #4503 or #4292
