### ISSUE TITLE
Measure time

### ISSUE THREAD

**Issue by ndvbd** [gradio-app/gradio#4559]
How can I set Gradio to show the query time in the UI?

**Comment by abidlabs** [comment]
Hi @ndvbd Gradio already shows this. Can you share reproducible code that we can run in which Gradio is not showing the runtime?

**Comment by ndvbd** [comment]
It shows a running counter during computation, but after the result the time disappears. For you the time stays?

**Comment by abidlabs** [comment]
Hi @ndvbd thanks for clarifying. For simplicity, we do not show the time after the function has finished running. If needed, you can manually include this output by calculating the runtime of your function, returning this value, and adding a `gr.Number()` to display it. Here's a quick example:

```py
import gradio as gr
import time

def your_function(x):
    start_time = time.time()
    time.sleep(3) # replace this
    run_time = time.time() - start_time
    return x, run_time

gr.Interface(your_function, "textbox", ["textbox", gr.Number(label="Runtime")]).launch()
```

**Comment by mspronesti** [comment]
Hi @abidlabs, is there a way to freeze the running time in the UI exactly where it was without adding additional textboxes/recomputing it?
