### ISSUE TITLE
Microphone input is not working in google colab

### ISSUE THREAD

**Issue by rohitashwa1907** [gradio-app/gradio#456]
I am trying to create a demo on google colab. It should record a file from Microphone and and generate the transcription  When I click the record button it starts recording but after that I am not getting any output. I am able to get the output if I upload a recorded audio but not when using microphone. I am using gradio==2.7.0
![screenshot](https://user-images.githubusercontent.com/46031058/149326959-4778459b-60f0-4053-bb4d-1d0abe06155e.png)

```

def transcript(audio_f):


  sr, data = audio_f
  
  # model input
  input_values = processor(data , sampling_rate=16000, return_tensors="pt").input_values.cuda()
  
  # inference
  model.eval()
  with torch.no_grad():
    logits = model(input_values.cuda()).logits

  # decoding predicted ids
  predicted_ids = torch.argmax(logits, dim =-1)
  transcription = processor.batch_decode(predicted_ids)

  return transcription


gradio_ui = gr.Interface(
    fn= transcript,
    title="Speech-to-Text with HuggingFace+Wav2Vec2",
    description="Record an audio clip, and let AI do the hard work of transcribing",
    inputs= gr.inputs.Audio(label="Record Using Mic", type="numpy", source="microphone"),
    outputs=gr.outputs.Textbox(label="Auto-Transcript"),
)



gradio_ui.launch(auth= ('rohit', 'Rohit'), debug=True)

```

**Comment by rohitashwa1907** [comment]
I am already using the external url given in colab output cell. I even tried i n my own system, the microphone doesn't send any input to he model.

**Comment by abidlabs** [comment]
That's weird. Does this code work for you in google colab?

```python
import gradio as gr
import numpy as np

def reverse_audio(audio):
    sr, data = audio
    return (sr, np.flipud(data))

iface = gr.Interface(reverse_audio, "microphone", "audio")

iface.launch(auth=("a", "b"), debug=True)
```

**Comment by abidlabs** [comment]
Or try running this colab directly: https://colab.research.google.com/drive/1Ol-Z4x6j5auCRXxJflMX6EDBYx5oFRe0#scrollTo=e200MmBU2aLT

**Comment by rohitashwa1907** [comment]
I tried this code in colab and my local system as well, but it's not working. It seems for some reason it's not even calling the given function. There is no error in the console as well.

![pic1](https://user-images.githubusercontent.com/46031058/149380093-a46db831-8446-4770-9879-6f46acbaec99.png)
![pic2](https://user-images.githubusercontent.com/46031058/149380168-0ef88a78-bb1d-4f10-8c42-7145f72324d4.png)

**Comment by rohitashwa1907** [comment]
Hey the problem is solved now. Closing the issue.

**Comment by abidlabs** [comment]
Did it get fixed by itself? Or did you do something to fix it? So we know for the future

**Comment by rohitashwa1907** [comment]
Sorry for the late response. There was some problem with the mic input in chrome. It was a so silly of me to raise an issue without trying it on other browser. I will be more careful next time. Thanks for your time.
