### ISSUE TITLE
TypeError when using gr.outputs.File

### ISSUE THREAD

**Issue by dachi920** [gradio-app/gradio#4560]
### Describe the bug

I encountered a TypeError when using the gr.outputs.File component in my code. The error message is as follows:

TypeError: File.__init__() got an unexpected keyword argument 'type'

I have confirmed that I am using the latest version of the gradio library (3.35.2). Here is the relevant code that causes the error:

outputs = [gr.outputs.File(label='Transcripts text file', type="file")]

Could you please help me resolve this issue? Thank you.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr
import whisper
import os
from pathlib import Path
import torch

# 毎回 whisper model をダウンロードすると時間かかるので
# ２回目以降で使いまわせるようにハンドリング
def load_whisper_model(model_name):
    model_dir = Path("whisper_models")
    model_path = model_dir / f"{model_name}.pt"

    if not model_path.exists():
        os.makedirs(model_dir, exist_ok=True)
        model = whisper.load_model(model_name)
        torch.save(model, model_path)
    else:
        model = torch.load(model_path)

    return model

model = load_whisper_model("medium")

# テキストを生成し、指定フォーマットに整形して出力する関数
def create_textfile(video_name, sr, timelag):
    # 動画からテキスト抽出結果を得る。
    results = model.transcribe(video_name, verbose=False, language="ja")

    # 出力用の文字列を初期化する。
    output_str = ""

    for index, _dict in enumerate(results["segments"]):

        start_time = _dict["start"]
        end_time = _dict["end"]

        # タイムラグ分だけシフトさせる。
        start_time += timelag
        end_time += timelag

        # 秒単位の開始時刻・終了時刻を計算する。
        s_h, e_h = int(start_time // (60 * 60)), int(end_time // (60 * 60))
        s_m, e_m = int(start_time // 60) % 60, int(end_time // 60) % 60
        s_s, e_s = start_time % 60, end_time % 60

        # インデックスとタイムコード、テキストを出力用文字列に追加する。
        output_str += f"{index + 1}\n{s_h:02d}:{s_m:02d}:{s_s:06.3f} --> {e_h:02d}:{e_m:02d}:{e_s:06.3f}\n{_dict['text']}。"

        # 句点がある場合は改行して次の行へ移動する。
        if "。" in _dict["text"]:
            output_str += "\n\n"

        # テキストファイルに出力する。
        with open("transcribe.docx", mode="w") as f:
            f.write(output_str)

        return "transcribe.docx"

# web の UI
css = """
.gradio-container {
	font-family : 'IBM Plex Sans', sans-serif;
}

.container {
	max-width :730px;
	margin:auto;
	padding-top :1.5rem;
}

#gallery {
	min-height                :22rem;
	margin-bottom             :15px;
	margin-left               :auto; 
	margin-right              :auto; 
	border-bottom-right-radius:.5rem !important ;
	border-bottom-left-radius :.5rem !important ;
}
#gallery>div>.h-full {
	min-height:20rem
}
"""

block = gr.Blocks(css=css)

with block:
    gr.Markdown("subtitle generator")
    with gr.Group():
        with gr.Box():
            with gr.Row(mobile_collapse=False, equal_height=True):
                # テキスト出力フォーマットを指定するためのオプション
                format_options = ["Microsoft Word (docx)"]

                segment_length_slider = gr.Slider(
                    minimum=0.1,
                    maximum=2,
                    label="segment length ratio",
                    value=1)

                timelag_slider = gr.Number(value=0, label="time lag (second)")

                text_button = gr.Button("transcribe").style(
                    margin=False,
                    rounded=(True, True, True, True),
                    background_color="#ff2e63",
                    color="white")

        video = gr.Audio(source="upload", type="filepath", interactive=True)

        transcribe_options_box = gr.Box()

        # 出力用フォーマットを選択するコンポーネント
    transcribe_format_radio = gr.Radio(format_options,
                                       label="Select the output format of transcripts text file.",
                                       default=format_options[0], group_id=None)

    # 出力ボタンを押したときに実行される関数。
    def transcribe_func(video_name, sr, timelag, output_format):
        if output_format == "Microsoft Word (docx)":
            create_textfile(video_name, sr, timelag)

# コンポーネントをブロックに追加する。
transcribe_options_box.add(transcribe_format_radio)

# 入出力データの設定
inputs = [video, segment_length_slider, timelag_slider]

outputs = [gr.outputs.File(label='Transcripts text file', type="file")]

# 出力ボタン
text_button.click(transcribe_func, inputs=inputs + [transcribe_format_radio],
                  outputs=outputs)

block.queue(default_enabled=False).launch(debug=True)

### Logs

```shell
outputs = [gr.outputs.File(label='Transcripts text file', type="file")]
TypeError: File.__init__() got an unexpected keyword argument 'type'
```

### System Info

```shell
gradioライブラリのバージョンは、最新の3.35.2でした
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @dachi920 your issue is very hard to follow as it's a mixture of code and text in English and Chinese (I think). You are also using outdated syntax: please use `gr.File()` instead of `gr.outputs.File()`. I think that should solve the issue -- if not, feel free to respond more clearly.
