### ISSUE TITLE
root_path  not work

### ISSUE THREAD

**Issue by H9990HH969** [gradio-app/gradio#4562]
### Describe the bug

I have a main domain, so the gradio web should be under it, but the root_path is not working.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

![mmexport1687168766768](https://github.com/gradio-app/gradio/assets/133352113/a222f0e3-6bc4-4121-904f-9ecf3fce9b4f)
![mmexport1687168770938](https://github.com/gradio-app/gradio/assets/133352113/d41d4d36-fb16-46a1-b612-08c4fa65920f)
![mmexport1687168814063](https://github.com/gradio-app/gradio/assets/133352113/3a989683-532f-4003-ba25-0b925b3a556d)

### Logs

```shell
no
```

### System Info

```shell
chrome
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @H9990HH969 please provide a simple example with code that we can use to reproduce this issue.

**Comment by H9990HH969** [comment]
Hi abidlabs, this is the original file, and I made certain modifications based on this file. Besides,this program is deployed on the intranet.
![image](https://github.com/gradio-app/gradio/assets/133352113/8f80580e-f412-4674-a8b7-a43d128438a5)

https://github.com/THUDM/ChatGLM-6B/blob/main/web_demo.py

> Hi @H9990HH969 please provide a simple example with code that we can use to reproduce this issue.

**Comment by abidlabs** [comment]
Are you running the latest version of gradio? 3.35.2?

**Comment by H9990HH969** [comment]
gradio-3.31.0

**Comment by H9990HH969** [comment]
Besides, using fastapi  I can successfully change the path of the API. like: localhost:7860/api
![mmexport1687230220849](https://github.com/gradio-app/gradio/assets/133352113/cc890db8-ac34-4144-8433-8619d3929283)
![mmexport1687230224270](https://github.com/gradio-app/gradio/assets/133352113/d4bc663a-3452-4f3d-b025-50fab5345221)



> Hi @H9990HH969 please provide a simple example with code that we can use to reproduce this issue.

**Comment by H9990HH969** [comment]
Mount_gradio_app is working!
![1687243608291](https://github.com/gradio-app/gradio/assets/133352113/83730808-0096-47d5-a455-d95891f3200f)
