### ISSUE TITLE
Gradio 3.35.2 breaks compatibility due to missing components

### ISSUE THREAD

**Issue by vladmandic** [gradio-app/gradio#4564]
### Describe the bug

Gradio 3.35.2 does not define some components that were previsouly available  
This is most likely due to changes in #4487  

Currently using Gradio 3.32.0 where such components are available  
This is blocking any possible upgrades  

Impact is to app ecosystem with 20k+ user installs

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr
Form = gr.components.Form
FormComponent = gr.components.FormComponent
```

### Logs

```shell
AttributeError: module 'gradio.components' has no attribute 'Form'
AttributeError: module 'gradio.components' has no attribute 'FormComponent'
```

### System Info

```shell
Gradio 3.35.2
Chrome 114
Windows 11
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Hi @vladmandic thanks for the catch. We'll restore these for backwards compatibility, even though these classes are meant to be used internally. To understand better, what are you using these classes for?

**Comment by vladmandic** [comment]
To create custom gradio components that work well with forms.
Example: <https://github.com/vladmandic/automatic/blob/master/modules/ui_components.py>

Even if code is not what it should be, its used by tons of 3rd party extensions and change would have to be done on massive scale - basically locking app down forever to old version of gradio.

**Comment by abidlabs** [comment]
Fair enough
