### ISSUE TITLE
Theme builder stopped working

### ISSUE THREAD

**Issue by cowanAI** [gradio-app/gradio#4565]
### Describe the bug

It wont load any theme, the buttons also stopped working as shown below:

<img width="1343" alt="image" src="https://github.com/gradio-app/gradio/assets/128092052/417e3adf-410d-475f-833d-1e138b3404c8">

https://huggingface.co/spaces/gradio/theme_builder

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/gradio/theme_builder

### Screenshot

https://huggingface.co/spaces/gradio/theme_builder

### Logs

```shell
https://huggingface.co/spaces/gradio/theme_builder
```

### System Info

```shell
https://huggingface.co/spaces/gradio/theme_builder
```

### Severity

annoying

**Comment by pngwn** [comment]
This is specific to the theme builder. The config is so large that the `/info` endpoint payload is over 500MB. Other _very_ complex apps would have a similar issue. I don't think many apps are affected by this right now (although the theme builder is an 'official' which makes this annoying).

I think we need to rethink the `info` and configs in general, if we want to avoid this issue.

**Comment by abidlabs** [comment]
I have an idea for a fix here, let me try something
