### ISSUE TITLE
How to correctly output matplotlib FuncAnimation as html?

### ISSUE THREAD

**Issue by patel-zeel** [gradio-app/gradio#457]
I am trying to create an animation (interactive) with gradio and matplotlib. Below is the code.

```
import gradio as gr
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from matplotlib import rc
import numpy as np

rc("animation", html="jshtml")


def animate(n_samples):
    fig, ax = plt.subplots()

    def inp(i):
        ax.cla()
        samples = np.random.rand(int(n_samples), 2)
        ax.scatter(samples[:, 0], samples[:, 1])

    anim = FuncAnimation(fig, func=inp, frames=range(10))
    # anim.save("test.mp4")
    return anim.to_jshtml()


iface = gr.Interface(fn=animate, inputs="number", outputs="html")
iface.launch()
```

Locally saved video looks like following

https://user-images.githubusercontent.com/59758528/149406565-ef0b1e18-1b50-4103-b5ce-a7204390d0d4.mp4

Gradio interface looks like the following
![screenshot](https://user-images.githubusercontent.com/59758528/149406673-f4b2f9ab-55d4-4fc3-b1e3-04c8575a8101.png)

Is there a workaround to make this work correctly?

**Comment by abidlabs** [comment]
What about using the `Video` output interface? See https://gradio.app/docs/#o_video

**Comment by patel-zeel** [comment]
Thanks for your suggestion @abidlabs. Can you please help me with a minimum working example? Currently, `video` output works if I save the animation as `.mp4` file. This method does not work with "hugging face spaces". My attempt is [here](https://huggingface.co/spaces/Zeel/QBC).

**Comment by abidlabs** [comment]
```python
import gradio as gr
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from matplotlib import rc
import numpy as np

rc("animation", html="jshtml")


def animate(n_samples):
    fig, ax = plt.subplots()

    def inp(i):
        ax.cla()
        samples = np.random.rand(int(n_samples), 2)
        ax.scatter(samples[:, 0], samples[:, 1])

    anim = FuncAnimation(fig, func=inp, frames=range(10))
    anim.save("test.mp4")
    return "test.mp4"

video = gradio.outputs.Video(self, type='mp4')

iface = gr.Interface(fn=animate, inputs="number", outputs=video)
iface.launch()
```

**Comment by patel-zeel** [comment]
I tried this and it fails on "hugging face spaces". Space is [here](https://huggingface.co/spaces/Zeel/QBC).

**Comment by abidlabs** [comment]
Closing because it looks like the issue has been solved or no longer a relevant question. 

If that's not the case, feel free to reopen with more details @patel-zeel
