### ISSUE TITLE
Using pyvis HTML output in Gradio's Output 

### ISSUE THREAD

**Issue by zhaoqf123** [gradio-app/gradio#4574]
### Describe the bug

When using the output html of pyvis package on graph data, gr cannot display the results. The resulting html itself can be opened by the browser.

One can reproduce the results with the code below.

Not sure whether this issue is related: [link](https://github.com/gradio-app/gradio/issues/3389)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr
from pyvis.network import Network
import networkx as nx
nx_graph = nx.cycle_graph(10)
nx_graph.nodes[1]['title'] = 'Number 1'
nx_graph.nodes[1]['group'] = 1
nx_graph.nodes[3]['title'] = 'I belong to a different group!'
nx_graph.nodes[3]['group'] = 10
nx_graph.add_node(20, size=20, title='couple', group=2)
nx_graph.add_node(21, size=15, title='couple', group=2)
nx_graph.add_edge(20, 21, weight=5)
nx_graph.add_node(25, size=25, label='lonely', title='lonely node', group=3)

# graph above refer to: https://pyvis.readthedocs.io/en/latest/tutorial.html#networkx-integration

# nt_notebook = Network('500px', '500px', notebook=True, cdn_resources='remote')
# populates the nodes and edges data structures
# nt_notebook.from_nx(nx_graph)
# nt_notebook.show('nx.html')


def needs_analysis():
    nt = Network()
    nt.from_nx(nx_graph)
    html = nt.generate_html()
    return html


demo = gr.Interface(
    needs_analysis,
    inputs=None,
    outputs=gr.outputs.HTML(),
    title="pyvis_in_gradio",
    allow_flagging='never'
)

demo.launch()
```

### Logs

```shell
Empty output when clicking the `generate` button.
```

### System Info

```shell
3.35.2, Mac Os 13.4, chrome
```

### Severity

annoying

**Comment by zhaoqf123** [comment]
#3389

**Comment by zhaoqf123** [comment]
I have tried this [workaround](https://github.com/gradio-app/gradio/issues/3180#issuecomment-1429886105), but still not working ...

**Comment by duerrsimon** [comment]
Here is a working example: https://huggingface.co/spaces/simonduerr/pyvisdemo 
You need to replace single quotes with double quotes.

**Comment by zhaoqf123** [comment]
> Here is a working example: https://huggingface.co/spaces/simonduerr/pyvisdemo You need to replace single quotes with double quotes.

@duerrsimon Thank you very very much. I just tried, and it works!

**Comment by abidlabs** [comment]
Thanks @duerrsimon!
