### ISSUE TITLE
how can I use https local URL

### ISSUE THREAD

**Issue by byeolkady** [gradio-app/gradio#458]
I am using URL in the form of "http://localhost:port".
I want to use https URL (http://localhost:port). How can I use  https URL?! 
My web page operates in the form of https.

**Comment by abidlabs** [comment]
There are lots of guides online about setting up HTTPS for localhost. E.g. https://dev.to/rajshirolkar/fastapi-over-https-for-development-on-windows-2p7d

Did you try these and run into any issue? If so, please feel free to reopen with a detailed description of the bug.

**Comment by byeolkady** [comment]
What you mean is that if we use both fastapi,  Uvicorn, and gradio, I can create a web page of gradio using https? (not meaning public link)

**Comment by anamtaamin** [comment]
> There are lots of guides online about setting up HTTPS for localhost. E.g. https://dev.to/rajshirolkar/fastapi-over-https-for-development-on-windows-2p7d
> 
> Did you try these and run into any issue? If so, please feel free to reopen with a detailed description of the bug.



> There are lots of guides online about setting up HTTPS for localhost. E.g. https://dev.to/rajshirolkar/fastapi-over-https-for-development-on-windows-2p7d
> 
> Did you try these and run into any issue? If so, please feel free to reopen with a detailed description of the bug.

Hi, I am trying to run on localhost and port. I went through the shared link but I have problems with downloading chocolatey. Is there any way that I just put 'localhost:5000/' and it opens up..?

**Comment by abidlabs** [comment]
Do you need https @anamtaamin?

**Comment by anamtaamin** [comment]
> Do you need https @anamtaamin?

yes, like flask has its own server so does gradio, I want both of them to work on 'https://localhost:5000/'
