### ISSUE TITLE
Questions about automatic playback of gradio.video

### ISSUE THREAD

**Issue by gengyang12345** [gradio-app/gradio#4588]
### Describe the bug

I set autoplay=True，but when I open the interface, the video cannot be played automatically. Is there any solution? this is code：

import gradio as gr
def video_identity(video):
    return video

with gr.Blocks() as demo:
    video = "C:/Users/yang.geng/Desktop/1.mp4"
    out = gr.Video(autoplay=True,label="数字人",value=video_identity(video))
    # out.update(value=video_identity(video), autoplay=True,interactive=False)
demo.launch()

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio as gr
def video_identity(video):
    return video

with gr.Blocks() as demo:
    video = "C:/Users/yang.geng/Desktop/1.mp4"
    out = gr.Video(autoplay=True,label="数字人",value=video_identity(video))
    # out.update(value=video_identity(video), autoplay=True,interactive=False)
demo.launch()

### System Info

```shell
gradio==3.35.2
Windows
google
```

### Severity

I can work around it

**Comment by gengyang12345** [comment]
import gradio as gr

def video_identity(video):
    return video

with gr.Blocks() as demo:
    gr.Markdown(
        """
        # 欢迎使用虚拟人机交互系统 
        """)
    video = "C:/Users/yang.geng/Desktop/1.mp4"
    out = gr.Video(autoplay=True,label="数字人",value=video_identity(video))
    # out.update(value=video_identity(video), autoplay=True,interactive=False)
demo.launch()

**Comment by gengyang12345** [comment]
import gradio as gr
def video_identity(video):
    return video

with gr.Blocks() as demo:
    video = "C:/Users/yang.geng/Desktop/1.mp4"
    out = gr.Video(autoplay=True,label="数字人",value=video_identity(video))
    # out.update(value=video_identity(video), autoplay=True,interactive=False)
demo.launch()

**Comment by abidlabs** [comment]
Hi @gengyang12345, this is not a Gradio issue. Most browsers prevent browsers from being auto-played upon page load. In order to use `autoplay`, you'll need to make this video be the output of a Gradio event. This should be indicated in the docs for this parameter, so I'll change the label here to reflect that
