### ISSUE TITLE
update supports updating the elem_id or elem_classes of a component

### ISSUE THREAD

**Issue by Kilig947** [gradio-app/gradio#4590]
- [ 1] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
css code 
```
@keyframes highlight {
  0%, 100% {
    border: 2px solid transparent;
  }
  50% {
    border-color: yellow;
  }
}

#highlight_update {
  animation-name: highlight;
  animation-duration: 0.75s;
  animation-iteration-count: 3;
}
```
python code 
```
with gr.Blocks(css=theme.custom_css) as demo:
        with column:
            with gr.Column(elem_id='examples_col') as examples_column:
                gr.Markdown('# Get Started Quickly')
                with gr.Row():
                    hide_components = gr.Textbox(visible=False)
                    guidance_example = gr.Examples(examples=[[Noo.update(visible=False), gr.State('412211'), '123123124124', submit3.update(elem_id='highlight_update')]],
                                                   inputs=[Noo, i_say, hide_components, submit3],
                                                   label='基础对话'
                                                   )
                    guidance_plugins = gr.Examples(examples=[[Noo.update(visible=False), gr.State('41241241'), '123123124124'], []],
                                                   inputs=[Noo, i_say, hide_components],
                                                   label='插件功能',
                                                   )
                    guidance_settings = gr.Examples(examples=[[Noo.update(visible=False), '123123', '123123124124'], []],
                                                   inputs=[Noo, i_say, hide_components],
                                                   label='更多设置',
                                                   )
```

I would like to implement that when I click on the case corresponding to Examples, some buttons will be highlighted to indicate that the user should click here, please ask why update(elem_id='xxxxx') is not supported.

**Comment by Kilig947** [comment]
![image](https://github.com/gradio-app/gradio/assets/46100050/0b7613e8-1409-4121-9c05-d919cc5b566c)

After trying to change the source code, I was able to achieve what I wanted

Hope to develop this soon

**Comment by abidlabs** [comment]
Thanks @Kilig947, we'll probably tackle this when we improve `.update()` as part of #4359. I'll leave this open to make sure we fix this.

**Comment by pngwn** [comment]
I don't think we want to 'fix' this. User shouldn't be dynamically updating IDs, they should persist for the lifetime of the app. Changing IDs at runtime is likely to cause all kinds of unexpected behaviour, especially with CSS.

That said, we should allow updating the class names that are applied to the element.

**Comment by abidlabs** [comment]
Hi @Kilig947 would you like to open a PR to allow updating the `elem_classes` of a component?

**Comment by Kilig947** [comment]
> Hi @Kilig947 would you like to open a PR to allow updating the `elem_classes` of a component?

https://github.com/gradio-app/gradio/pull/4789. 

Sure, I can open a PR to allow updating the elem_classes of a component.

**Comment by abidlabs** [comment]
Yes it was!
