### ISSUE TITLE
All connection attempts failed 问题

### ISSUE THREAD

**Issue by Xuerrui** [gradio-app/gradio#4592]
### Describe the bug

mycode is
```
import gradio as gr
from time import sleep
def greet(name):
    for i in range(10):
        sleep(1)
        name = "xu"+str(i)
        yield "Hello " + name + "!"
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text", title=" App")
app = gr.mount_gradio_app(app, demo.queue(), path="/gradio")
```
it's a fastapi program.
when i click submit, I found "All connection attempts failed", after a lot time debug. 
oh, it is because my port number was occupied.
so, if you have the same issue，maybe you can change your fastapi port. YES

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr
from time import sleep
from fastapi import FastAPI
app = FastAPI(openapi_url="")
def greet(name):
    for i in range(10):
        sleep(1)
        name = "xu"+str(i)
        yield "Hello " + name + "!"
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text", title=" App")

# io = gr.Interface(greet, "textbox", "textbox")
app = gr.mount_gradio_app(app, demo.queue(), path="/gradio")
```
it`s a tiny demo.

### System Info

```shell
(1)gradio  3.34.0 (2)ubuntu (3)edge
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Sounds like you were able to solve the issue by using a different port @Xuerrui, so I'll go ahead and close this
