### ISSUE TITLE
HIgh latency issue with demo

### ISSUE THREAD

**Issue by BhavanJ** [gradio-app/gradio#46]
Hi Gradio team, this is fantastic work.

I am noticing a huge latency difference. My ML model takes around 5 seconds to run when called in python without the demo. But when I measure the latency of the same function when called through the hosted demo it takes around 15 seconds for the same exact input. And this 15 seconds doesn't include the I/O latency of demo. This is very strange. Any thoughts why this could be happening?

Thanks,
Bhavan

**Comment by vseledkin** [comment]
can be related https://github.com/gradio-app/gradio/issues/22

**Comment by abidlabs** [comment]
Hi @vseledkin @BhavanJ did you see this issue with `share=True` and using a `xxxxx.gradio.app` link? Or locally?

**Comment by abidlabs** [comment]
I am not able to reproduce locally, and only see this issue when we upload large samples (> 1 MB) on the public link. We will put a warning in such cases
