### ISSUE TITLE
The directory containing the gradio python file should not be served by default.

### ISSUE THREAD

**Issue by aeciorc** [gradio-app/gradio#4609]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Currently, the default behaviour for the app is to serve any files in the directory of the Gradio script. This is in the docs and is not considered a bug or a vulnerability, but I think it's problematic for a few reasons:

1. Users want to share their app, but not necessarily the code. Gradio is used not only for open-source projects, but also to share and get feedback on MVPs, research projects, work projects, etc. Even for open-source models, people might want to  protect their checkpoints and datasets. Giving access to the project directory by default might catch them by surprise, which brings me to my next point.

2. Is the default behaviour expected by most users? I'm not sure it is. Academic or non-technical users might not know or think about this at all, while developers expect a backend to serve the files they explicitly asked it to serve (definitely not the backend code itself.)

3. It's not crazy to assume that some users, especially beginners, will put gradio files not in a project folder, but in a higher directory in their system, like ~/Documents, ~/Downloads, or even worse, the home directory. With the current behaviour, this could cause them a lot of problems.

**Describe the solution you'd like**  
The solution is simple: don't serve the script directory files by default. Raw outputs are always fine, and Gradio already handles filepath outputs with tempfiles. This is good enough for 99% of use cases.

If a request is made for a file that's not accessible, an error log can link to the section of the documentation about allowed_paths.

**Additional context**

**Comment by abidlabs** [comment]
Hi @aeciorc thanks for creating the detailed issue. Agreed I've been thinking we should do something about this, perhaps 4.0 is a good time to make this change, we'll look into it!

In the meantime, you can use the `blocked_paths` parameter in `launch()` to block specific directories or files.

**Comment by aeciorc** [comment]
Sounds good @abidlabs. I can give this a shot if you need a hand.

**Comment by abidlabs** [comment]
Thanks @aeciorc it needs some thinking through I think. The reason is that we allow serving files from the working directory because it allows users to conveniently serve example files or include default values. For example:

```py
with gr.Blocks():
  gr.Image("lion.jpg")
```

or 

```py
gr.Interface(lambda x:x, "image", "image", examples=["lion.jpg"])
```

We'd need to make sure these use cases are not disrupted. I think it is possible by copying over the referenced files to the temporary directory and serving from there. We may already do this for some components but we'd need to make sure all of the components handle this correctly.

**Comment by aeciorc** [comment]
That makes sense @abidlabs. For initial values, we could change `IOComponent.get_load_fn_and_initial_value` to call `IOComponent.make_temp_copy_if_needed` on the value if it's not callable, else wrap it with a function that does that to the output. 

For the interface `examples` case, and for outputs in general, my naive approach was to just wrap the Interface `fn` argument to do the same, but I realized someone could trick a text component into returning a path to gain access to a file. So I think it's better to do this at the component level when the value is updated, this way we can check if the component type is "filepath".  Thoughts?

Ideally, we should still check if a path is in the directory or in the allowed_path (and not in the blocked_paths) before making a temp copy, but I haven't looked into this part of the codebase to know if it's possible.

**Comment by abidlabs** [comment]
Fixed in `v4` branch!
