### ISSUE TITLE
Getting this error (ValueError: The current space is in the invalid state: RUNTIME_ERROR. Please contact the owner to fix this.) when trying to use the ImageCaptioningTool

### ISSUE THREAD

**Issue by naila03** [gradio-app/gradio#4610]
### Describe the bug

Something is going wrong with the gradio client when using the ImageCaptioningTool and it looks like the current state is INVALID RUNTIME. I was trying to run the code for the ImageCaptioningTool on this page: https://gradio.app/gradio-and-llm-agents/

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

from langchain.agents import initialize_agent
from langchain.llms import OpenAI
from gradio_tools import (StableDiffusionTool, ImageCaptioningTool, StableDiffusionPromptGeneratorTool,
                          TextToVideoTool)

from langchain.memory import ConversationBufferMemory

llm = OpenAI(temperature=0)
memory = ConversationBufferMemory(memory_key="chat_history")
tools = [StableDiffusionTool().langchain, ImageCaptioningTool().langchain,
         StableDiffusionPromptGeneratorTool().langchain, TextToVideoTool().langchain]

agent = initialize_agent(tools, llm, memory=memory, agent="conversational-react-description", verbose=True)
output = agent.run(input=("Please create a photo of a dog riding a skateboard "
                          "but improve my prompt prior to using an image generator."
                          "Please caption the generated image and create a video for it using the improved prompt."))

### Screenshot

![Screenshot from 2023-06-21 12-15-45](https://github.com/gradio-app/gradio/assets/104375200/f738e1b0-152f-409d-9087-b89aa9460a58)

### Logs

```shell
Cell In[5], line 15
     13 llm = OpenAI(temperature=0)
     14 memory = ConversationBufferMemory(memory_key="chat_history")
---> 15 tools = [StableDiffusionTool().langchain, ImageCaptioningTool().langchain,
     16          StableDiffusionPromptGeneratorTool().langchain, TextToVideoTool().langchain]
     19 agent = initialize_agent(tools, llm, memory=memory, agent="conversational-react-description", verbose=True)
     20 output = agent.run(input=("Please create a photo of a dog riding a skateboard "
     21                           "but improve my prompt prior to using an image generator."
     22                           "Please caption the generated image and create a video for it using the improved prompt."))

File /opt/conda/lib/python3.10/site-packages/gradio_tools/tools/image_captioning.py:28, in ImageCaptioningTool.__init__(self, name, description, src, hf_token, duplicate)
     16 def __init__(
     17     self,
     18     name="ImageCaptioner",
   (...)
     26     duplicate=True,
     27 ) -> None:
---> 28     super().__init__(name, description, src, hf_token, duplicate)

File /opt/conda/lib/python3.10/site-packages/gradio_tools/tools/gradio_tool.py:36, in GradioTool.__init__(self, name, description, src, hf_token, duplicate)
     34 else:
     35     self.src = src
---> 36     self.client = grc.Client(self.src, hf_token=hf_token)
     37 self.description += (
     38     "If the output is the string QUEUE_FULL you "
     39     "should try this action again and never stop until you "
     40     "don't see this message."
     41 )
     42 self._block = None

File /opt/conda/lib/python3.10/site-packages/gradio_client/client.py:114, in Client.__init__(self, src, hf_token, max_workers, serialize, output_dir, verbose)
    112         pass
    113 if state in utils.INVALID_RUNTIME:
--> 114     raise ValueError(
    115         f"The current space is in the invalid state: {state}. "
    116         "Please contact the owner to fix this."
    117     )
    118 if self.verbose:
    119     print(f"Loaded as API: {self.src} ✔")

ValueError: The current space is in the invalid state: RUNTIME_ERROR. Please contact the owner to fix this.
```

### System Info

```shell
Version: 3.35.2 (latest)
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @naila03 ! Thanks for reporting! Looking into this now!!

**Comment by freddyaboulton** [comment]
@naila03 - the space is back up now https://huggingface.co/spaces/gradio-client-demos/BLIP-2

![image](https://github.com/gradio-app/gradio/assets/41651716/0f65f23d-ebfd-4d61-9738-d63029ed4733)

**Comment by alphaveneno** [comment]
**Getting a similar error today:**

ValueError: The current space is in the invalid state: RUNTIME_ERROR. Please contact the owner to fix this.

**... with example code taken from _https://python.langchain.com/v0.2/docs/integrations/tools/gradio_tools/_:**

from gradio_tools.tools import StableDiffusionTool
from PIL import Image
from IPython.display import display

local_file_path = StableDiffusionTool().langchain.run(
    "Please create a photo of a dog riding a skateboard"
)
print(local_file_path)
im = Image.open(local_file_path)
display(im)

screenshot of traceback:

![screen](https://github.com/user-attachments/assets/16a78899-5e30-44e6-9a3a-b104c3827aad)

**Link to _https://huggingface.co/spaces/gradio-client-demos/BLIP-2_ shows a runtime error:**

![screen2](https://github.com/user-attachments/assets/79cff106-b207-41d8-b745-f2c647aa1948)
