### ISSUE TITLE
I have an additional question about https. 

### ISSUE THREAD

**Issue by byeolkady** [gradio-app/gradio#462]
I asked a question about https before. Then you recommended using fastapi and uvicorn. (https://github.com/gradio-app/gradio/issues/458)
But I wonder if this can be applied to the gradio. Can you give me an example?

**Comment by abidlabs** [comment]
Sorry I don't know what you mean by, "But I wonder if this can be applied to the radio"

**Comment by byeolkady** [comment]
My meaning means to apply to gradio. For example, when I run a gradio, I receive two links. One is local and the other is public. In the case of local, you receive a link through http, and I wonder if you can receive the link through https.
![image](https://user-images.githubusercontent.com/46770780/149848326-15395b29-2a04-4edf-a557-a75b158b8e4a.png)

**Comment by abidlabs** [comment]
Got it. So yes, while I have not ever tried to get localhost running with https, I do think it should be possible. 

If you follow this guide, you should be able to set up https locally on any port you want: https://dev.to/rajshirolkar/fastapi-over-https-for-development-on-windows-2p7d

And then if you run gradio from that port, you should be able to open up the link with https.

(The reason I sent the article about `fastapi` is that we are switching our backend server to be `fastapi` as of the next release of Gradio, so it should work if you follow the article)

**Comment by byeolkady** [comment]
Yes, thank you for your answer.

**Comment by abidlabs** [comment]
Great, thanks for asking! Closing this issue then
