### ISSUE TITLE
KeyError: 13 in analytics.py

### ISSUE THREAD

**Issue by dachi920** [gradio-app/gradio#4642]
### Describe the bug

I encountered a KeyError: 13 error while using the Gradio library. The error occurred in the analytics.py file on line 126. Here is the full error message:

File "C:\Users\●●●\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\analytics.py", line 126, in <listcomp>
    str(blocks.blocks[y]) for y in x["outputs"]
KeyError: 13

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio as gr
import whisper
import os
from pathlib import Path
import torch

# 毎回 whisper model をダウンロードすると時間かかるので
# ２回目以降で使いまわせるようにハンドリング
def load_whisper_model(model_name):
    model_dir = Path("whisper_models")
    model_path = model_dir / f"{model_name}.pt"

    if not model_path.exists():
        os.makedirs(model_dir, exist_ok=True)
        model = whisper.load_model(model_name)
        torch.save(model, model_path)
    else:
        model = torch.load(model_path)

    return model

model = load_whisper_model("medium")

# テキストを生成し、指定フォーマットに整形して出力する関数
def create_textfile(video_name, sr, timelag) -> object:
    # 動画からテキスト抽出結果を得る。
    results = model.transcribe(video_name, verbose=False, language="ja")

    # 出力用の文字列を初期化する。
    output_str = ""

    for index, _dict in enumerate(results["segments"]):
        start_time = _dict["start"]
        end_time = _dict["end"]

        # タイムラグ分だけシフトさせる。
        start_time += timelag
        end_time += timelag

        # 秒単位の開始時刻・終了時刻を計算する。
        s_h, e_h = int(start_time // (60 * 60)), int(end_time // (60 * 60))
        s_m, e_m = int(start_time // 60) % 60, int(end_time // 60) % 60
        s_s, e_s = start_time % 60, end_time % 60

        # インデックスとタイムコード、テキストを出力用文字列に追加する。
        output_str += f"{index + 1}\n{s_h:02d}:{s_m:02d}:{s_s:06.3f} --> {e_h:02d}:{e_m:02d}:{e_s:06.3f}\n{_dict['text']}。"

        # 句点がある場合は改行して次の行へ移動する。
        if "。" in _dict["text"]:
            output_str += "\n\n"

    # テキストファイルに出力する。
    with open("transcribe.docx", mode="w") as f:
        f.write(output_str)

    return "transcribe.docx"

# web の UI
css = """
.gradio-container {
	font-family : 'IBM Plex Sans', sans-serif;
}

.container {
	max-width :730px;
	margin:auto;
	padding-top :1.5rem;
}

#gallery {
	min-height                :22rem;
	margin-bottom             :15px;
	margin-left               :auto; 
	margin-right              :auto; 
	border-bottom-right-radius:.5rem !important ;
	border-bottom-left-radius :.5rem !important ;
}
#gallery>div>.h-full {
	min-height:20rem
}
"""

block = gr.Blocks(css=css)

with block:
    gr.Markdown("subtitle generator")
    with gr.Group():
        with gr.Box():
            with gr.Row(mobile_collapse=False, equal_height=True):
                # テキスト出力フォーマットを指定するためのオプション
                format_options = ["Microsoft Word (docx)"]

                segment_length_slider = gr.Slider(
                    minimum=0.1,
                    maximum=2,
                    label="segment length ratio",
                    value=1)

                timelag_slider = gr.Number(value=0, label="time lag (second)")

                text_button = gr.Button("transcribe").style(
                    margin=False,
                    rounded=(True, True, True, True),
                    background_color="#ff2e63",
                    color="white")

        video = gr.Audio(source="upload", type="filepath", interactive=True)

        transcribe_options_box = gr.Box()

        # 出力用フォーマットを選択するコンポーネント
    transcribe_format_radio = gr.Radio(format_options,
                                       label="Select the output format of "
                                             "transcripts text file.",
                                       default=format_options[0], group_id=None)

    # 出力ボタンを押したときに実行される関数。
    def transcribe_func(video_name, sr, timelag, output_format):
        if output_format == "Microsoft Word (docx)":
            create_textfile(video_name, sr, timelag)

# コンポーネントをブロックに追加する。
transcribe_options_box.add(transcribe_format_radio)

# 入出力データの設定
inputs = [video, segment_length_slider, timelag_slider]

outputs = [gr.outputs.File(label='Transcripts text file')]

# 出力ボタン
with block:
    # ...
    text_button.click(transcribe_func,
                      inputs=inputs + [transcribe_format_radio],
                      outputs=outputs)

block.queue(default_enabled=False).launch(debug=True)

### System Info

```shell
gradio ライブラリの最新バージョンは、3.35.2 です
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @dachi920 or @arian81 can you provide a well-formatted and self-contained code example we can use to reproduce this issue?

**Comment by arian81** [comment]
well the issue is after I restarted my jupyter kernel the problem is resolved  ? I don't have specific way of reproducing the bug yet. The problem being in the analytics module doesn't help much with finding what the issue is.

**Comment by arian81** [comment]
the code takes a really long time to establish connection to the gradio servers to provision a new instance so there might be an issue with your backend ?

**Comment by arian81** [comment]
> Hi @dachi920 or @arian81 can you provide a well-formatted and self-contained code example we can use to reproduce this issue?

ok now i'm getting the error and the number has increased. Could it be because I have created too many share instances?

**Comment by WSH032** [comment]
Hi, @abidlabs 
I guess I know why.
Check here: https://colab.research.google.com/drive/1xi6oVNAuzqbU7tB44UMLe-297mGD46fP?usp=sharing
![BDPF)E1%Q120H MZ3HDW6LN](https://github.com/gradio-app/gradio/assets/126865849/33d6cac0-b15c-48b0-bae5-3e1826bb4ed3)

---

![0U 96P56H$AE3N64I F HJ4](https://github.com/gradio-app/gradio/assets/126865849/2e54df69-943d-4f36-b6ea-106aa56305aa)
