### ISSUE TITLE
App crashes without error message. 

### ISSUE THREAD

**Issue by 42694647426** [gradio-app/gradio#4649]
### Describe the bug

I'm using the queue and a generator to get the live speech recognition. But, after I ran the gradio application, the app sometimes stops generating output without any error message and it is also not possible to close it properly with crtl+c. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
# use the speechsdk to get live recognizing speech and yied the output to application 

import azure.cognitiveservices.speech as speechsdk 
self.speech_recognizer = speechsdk.SpeechRecognizer(
            speech_config=self.speech_config)
 self.speech_recognizer.recognizing.connect(self.recognizing_cb)

# Can't exit function or speech_recognizer will go out of scope and be destroyed while running.
 while not self.done:
            yield f"{self.transcript} {self.detected_speech}"

# for the gradio application 
with gr.Blocks() as demo:
    transcript = gr.Textbox(label="Transcription", lines=5)
demo.queue(concurrency_count=5)
demo.launch(enable_queue=True, show_error=True, debug=True)
```

### Screenshot

There is no any error message. 

### System Info

```shell
Name: gradio
Version: 3.28.3

OS:
Device name	XXX
Processor	Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz   1.90 GHz
Installed RAM	32.0 GB (31.8 GB usable)
System type	64-bit operating system, x64-based processor

Edition	Windows 11 Enterprise
Version	22H2
Installed on	‎2023-‎05-‎05
OS build	22621.1848
Experience	Windows Feature Experience Pack 1000.22642.1000.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @42694647426 this is not a self-contained repro as it depends on external libraries. If you have a repro that we can run on our machines, we will be able to debug this issue. In the meantime, I'm closing this issue.
