### ISSUE TITLE
How to change the text color in textbox

### ISSUE THREAD

**Issue by 42694647426** [gradio-app/gradio#4652]
How to change the text color in gr.Textbox?

I have searched online and tried gr.Textbox(label="Text").style(color="red")

but it is giving this warning: 
UserWarning: You have unused kwarg parameters in Textbox

I also tried the css, but if I add the elemid="id" and css=#id: {color: red} is also not working.

Can you please advise how to change the text color in a text box?

Thanks

**Comment by jackeldestripat** [comment]
## Change color of `textarea`, follow these steps:

1. Use element IDs like below. Replace `<textbox_id>` with the actual name of your elements:

```python
with gr.Textbox(value="Good Job", elem_id="textbox_id")
```

2. Define CSS styles with a unique ID.

Code example:

```python
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

with gr.Blocks(css="#textbox_id textarea {color: red}") as demo:
    name =  gr.Textbox(value="Good Job", elem_id="textbox_id")
    output = gr.Textbox(label="Output Box")
    greet_btn = gr.Button("Greet")
    greet_btn.click(fn=greet, inputs=name, outputs=output, api_name="greet")

demo.launch()
```

**Note:** Replace `<textbox_id>` with the actual ID you want to use for your `Textarea` element.

**Comment by 42694647426** [comment]
> ## Change color of `textarea`, follow these steps:
> 1. Use element IDs like below. Replace `<textbox_id>` with the actual name of your elements:
> 
> ```python
> with gr.Textbox(value="Good Job", elem_id="textbox_id")
> ```
> 
> 2. Define CSS styles with a unique ID.
> 
> Code example:
> 
> ```python
> import gradio as gr
> 
> def greet(name):
>     return "Hello " + name + "!"
> 
> with gr.Blocks(css="#textbox_id textarea {color: red}") as demo:
>     name =  gr.Textbox(value="Good Job", elem_id="textbox_id")
>     output = gr.Textbox(label="Output Box")
>     greet_btn = gr.Button("Greet")
>     greet_btn.click(fn=greet, inputs=name, outputs=output, api_name="greet")
> 
> demo.launch()
> ```
> 
> **Note:** Replace `<textbox_id>` with the actual ID you want to use for your `Textarea` element.

Hi, thank you so much for your help! Can you please help me with this issue? #4649 it is bothering me for a long time.
