### ISSUE TITLE
Problems Drawing Masks in UI for Automatic1111/ControlNet

### ISSUE THREAD

**Issue by Vendaciousness** [gradio-app/gradio#4653]
### Describe the bug

This is basically the same function, so I'll put them together.  I was referred here from the Automatic1111 repo. These are both functionality issues that make work more difficult, but do not produce errors, so if I'm mislabeling them, please let me know and I'll reformat my issue.

This regards the use of the mask drawing tool present in both versions of Auto11, as well as the ControlNet UI in both:

1). ~~User cannot~~ It is very difficult to paint the top right corner of the image in the Inpainting tab, as well as ControlNet's UI, because drawing gets disabled when the user moves the cursor over the tools in the upper right corner of the window, even though the left mouse button is being held down (a solid indication the user wants to continue adding to the mask with the brush). This means that the only way to get the top right of the image (like when pseudo-text is generated there) is to make the cursor as large as possible, then manage to move the cursor in-between a space of about 25 pixels, to get above the undo, erase and close icons. I thought it was impossible, but found it's just exceedingly hard to do, especially with a sensitive mouse. 

A similar function also makes drawing any mask at the edges extra difficult, because moving the cursor outside the image bounds disables the brush as well, even though the UI is coded to keep the brush inside the image window and even when the user is still holding down the left mouse button, indicating the desire to continue adding to the mask.  This means the user must start their strokes from a 'safe' area of the image, then move towards the edge where they want to draw, until eventually, they get it all.  This results in more of the image being masked that is desired.

This issue has been present since I started using Automatic1111/Vlad's automatic 5 months ago.  If there is a logo/watermark/text in the upper right corner of an image I otherwise like, I'll often paste it into PhotoShop or another editor in order to fix that area of the image.

If the devs have seen Photopea.com, that is the sort of masking UI I dream of seeing in gradio, so that production artists such as myself will be able to remain in it, rather than rely on outside tools.

![image](https://github.com/AUTOMATIC1111/stable-diffusion-webui/assets/127359965/5aa7f88d-f750-40a5-8d14-27868bea7dd5)

### What should have happened?

Drawing (holding the left mouse button and dragging the cursor over the top right corner should automatically disable all of the controls in the top right corner of the inpainting area.

### Commit where the problem happens

Version: b80fcca9 Thu Jun 22 13:05:26 2023 -0400

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

Nvidia GPUs (RTX 20 above)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
None (using Vlad's Automatic WebUI), but it has this in the console:
 scaled dot product cross attention optimization (without memory efficient attention)
So probably --opt-sdp-no-mem-attention
```

### List of extensions

[sd_web_ui_preset_utils](https://github.com/Gerschel/sd_web_ui_preset_utils.git)

### Console logs

```Shell
Using VENV: G:\Code\automatic\venv
12:50:07-531794 INFO     Starting SD.Next
12:50:07-536794 INFO     Python 3.10.9 on Windows
12:50:07-575995 INFO     Version: b80fcca9 Thu Jun 22 13:05:26 2023 -0400
12:50:07-932626 INFO     nVidia CUDA toolkit detected
12:50:09-577927 INFO     Torch 2.0.1+cu118
12:50:09-601928 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
12:50:09-604927 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 10240
                         Arch (8, 6) Cores 68
12:50:09-702928 WARNING  Modified files: ['=2.12.0']
12:50:09-738928 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris',
                         'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'sd-webui-model-converter',
                         'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR']
12:50:09-746927 INFO     Enabled extensions: ['Config-Presets',
                         'deforum-for-automatic1111-webui',
                         'sd_web_ui_preset_utils']
12:50:09-750927 INFO     Verifying requirements
12:50:09-765935 INFO     Verifying packages
12:50:09-767928 INFO     Installing repositories
12:50:12-400928 INFO     Installing submodules
12:50:13-937928 INFO     Updating submodules
12:50:39-921927 INFO     Extensions enabled: ['a1111-sd-webui-lycoris',
                         'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'sd-webui-model-converter',
                         'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR',
                         'Config-Presets', 'deforum-for-automatic1111-webui',
                         'sd_web_ui_preset_utils']
12:50:39-925927 INFO     Updating Wiki
12:50:40-467928 INFO     Extension preload: 0.0s
                         G:\Code\automatic\extensions-builtin
12:50:40-469928 INFO     Extension preload: 0.0s G:\Code\automatic\extensions
12:50:40-483927 INFO     Server arguments: []
No module 'xformers'. Proceeding without it.
12:50:47-009928 INFO     Libraries loaded
12:50:47-014928 INFO     Using data path: G:\Code\automatic
12:50:47-019928 INFO     Available VAEs:
                         G:\Code\stable-diffusion-webui\models\VAE 6
12:50:47-032928 INFO     Available models:
                         G:\Code\stable-diffusion-webui\models\Stable-diffusion
                         23
12:50:50-199927 INFO     ControlNet v1.1.224
ControlNet v1.1.224
ControlNet preprocessor location: G:\Code\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
12:50:50-474927 INFO     ControlNet v1.1.224
ControlNet v1.1.224
Image Browser: ImageReward is not installed, cannot be used.
12:50:51-688928 INFO     Libraries loaded
Libraries loaded
12:50:52-257928 INFO     Loading UI theme: name=sudeepshouche/minimalist
                         style=Auto
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860
12:50:55-364928 INFO     Local URL: http://127.0.0.1:7860/
12:50:55-366928 INFO     Initializing middleware
Loading weights: G:\Code\stable-diffusion-webui\models\Stable-diffusion\aZovy…
12:50:56-894927 INFO     Setting Torch parameters: dtype=torch.float16
                         vae=torch.float16 unet=torch.float16
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights: G:\Code\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-…
12:51:00-792290 INFO     Applying scaled dot product cross attention
                         optimization (without memory efficient attention)
12:51:00-831290 INFO     Embeddings: loaded=6 skipped=0
12:51:00-840290 INFO     Model loaded in 4.5s (load=0.5s config=0.1s
                         create=0.4s apply=1.2s channels=0.6s vae=1.1s
                         move=0.7s)
12:51:01-128559 INFO     Model load finished: {'ram': {'used': 6.53, 'total':
                         63.93}, 'gpu': {'used': 3.19, 'total': 10.0},
                         'retries': 0, 'oom': 0} cached=0
12:51:01-455606 INFO     Startup time: 21.0s (torch=3.7s gradio=1.1s
                         libraries=1.7s codeformer=0.1s gfpgan=0.1s
                         scripts=4.7s onchange=0.4s ui=2.8s launch=0.3s
                         app-started=0.7s checkpoint=5.4s)
100%|████████████████████████████████████████████| 9/9 [00:04<00:00,  2.15it/s]
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

1. Open Automatic1111 WebUI on any platform, using any browser.
2. Go to Image2Image tab. 
3. Click on the Inpaint tab, below the the prompt fields.
4. Upload an image to inpaint.
5. Attempt to draw a mask to inpaint the top right corner of the image, even with the largest brush size.

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/127359965/8bcf6b0d-f123-44d0-b256-429a7eb4f299)

### Logs

```shell
No errors in console.
```

### System Info

```shell
Not relevant, but Version: 3.32.0
```

### Severity

I can work around it

**Comment by missionfloyd** [comment]
Here's a demo. Try to draw in the upper-right corner.
```python
import gradio as gr

demo = gr.Interface(lambda x: x, inputs=gr.Image(tool="sketch", source="canvas"), outputs="image")
demo.launch()
```

**Comment by Vendaciousness** [comment]
Where do I put this code?

**Comment by missionfloyd** [comment]
It's for the gradio devs, so they can recreate the issue.
