### ISSUE TITLE
Chatbot does not show PDF file

### ISSUE THREAD

**Issue by taoari** [gradio-app/gradio#4667]
### Describe the bug

For gr.Chatbot(), If the response is a PDF (or other) file, the chatbot does not show anything.

```python
import gradio as gr

with gr.Blocks() as demo:
    gr.Chatbot([
        (None, ("https://upload.wikimedia.org/wikipedia/commons/5/53/Sheba1.JPG",)), 
        (None, ("https://upload.wikimedia.org/wikipedia/commons/2/28/Caldhu.wav",)), 
        (None, ("https://www.africau.edu/images/default/sample.pdf",)), 
        (None, ("https://raw.githubusercontent.com/alecjacobson/common-3d-test-models/master/data/stanford-bunny.obj",)),
        (None, ("https://raw.githubusercontent.com/gradio-app/gradio/main/package.json",)), 
        (None, ("https://raw.githubusercontent.com/gradio-app/gradio/main/render_readme.py",)), 
    ]).style(height=1000)

demo.launch()
```

![image](https://github.com/gradio-app/gradio/assets/3815006/38cf5666-4755-4f94-957b-77602e92df67)

For the `gr.File()` widget, it actually shows the file name, file size, and download button. Can the chatbot at least do the same?

![image](https://github.com/gradio-app/gradio/assets/3815006/a7366379-4cba-459d-aef1-9c00372796a5)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

See above.

### Screenshot

See above

### System Info

```shell
gradio                        3.35.2
windows 11
google chrome
```

### Severity

Blocking usage of gradio

**Comment by dawoodkhan82** [comment]
@taoari At the moment, chatbot supports images, audio, and video file types. You can provide your files as links as part of a regular chatbot message and the links will show up

**Comment by abidlabs** [comment]
I think it'd be good to add general file support to chatbots -- we don't need the preview, but at least we could have the basic file info. WDYT @dawoodkhan82?
