### ISSUE TITLE
UI: scroll to top when clicking on "Use via API"

### ISSUE THREAD

**Issue by gary149** [gradio-app/gradio#4682]
That would be quite useful (as often the content is hidden):

<img width="341" alt="image" src="https://github.com/gradio-app/gradio/assets/3841370/b4a5272b-6905-4484-a7b0-bb3ef6f60ad2">

**Comment by abidlabs** [comment]
Scrolling to the top is frustratingly difficult in an iframe, but cc @pngwn as he is looking into it in the context of error modals
