### ISSUE TITLE
leakage of yields meant for different users

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#4697]
### Describe the bug

https://github.com/h2oai/h2ogpt/issues/346

I can't see how anything I'd do using gradio would cause one user to see another users output.  If I had user hash, I could at least log, but I guess I don't have access:  https://github.com/gradio-app/gradio/discussions/3900

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

This is quite serious, so I'll try to repro using spam attack from multiple parallel client calls to check consistency.  But if you guys have any ideas how this is possible, let me know.

The only special thing about h2oGPT is it's using threads for streaming and queues, but the only asyncio stuff is gradio.

Also notice in this case, there are no local torch LLMs, just remote endpoints.  So it's quite a clean setup.  The only other special thing is we are using gradio to talk to the Hugging Face text-generation server via python client.

So I suppose it's possible the TGI server messed up things as well.

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/2249614/f8237510-8261-4313-8d47-538108e1ac75)

The top-left is the problem.  From our logging, 2 users were nearby in time.  One asking about jokes, the other asking about summarizing some stories.  The user got the wrong response.

### System Info

```shell
gradio==3.35.2
gradio_client==0.2.7
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Thanks @pseudotensor for creating this issue. We'd appreciate if you could try to reproduce this with a simpler example. I don't have any obvious ideas how this could be an issue on Gradio's side. However, please take a look in case any of these issues might apply:

* https://github.com/gradio-app/gradio/issues/4558
* https://github.com/gradio-app/gradio/issues/3824

**Comment by abidlabs** [comment]
Closing until we have a repro, thanks!
