### ISSUE TITLE
Better error if `theme.css` cannot be found

### ISSUE THREAD

**Issue by LianShuaiLong** [gradio-app/gradio#4704]
### Describe the bug

The ui is in a mess
![image](https://github.com/gradio-app/gradio/assets/23699530/eb8e1fb9-d758-4aad-a6ba-6f04621264c9)
while the public url is perfect:
![image](https://github.com/gradio-app/gradio/assets/23699530/5a12e937-176d-4cab-b6dc-3b4a6c6f4a4b)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

lauch a gradio demo based on gradio blocks

### System Info

```shell
gradio==3.35.2
```

### Severity

I can work around it

**Comment by LianShuaiLong** [comment]
> How are you mounting the app on the `draggan` subpath @LianShuaiLong ?

Here are how i build my object:
1. install gradio by "pip install gradio"
2. build "draggan" application with app = gradio.Blocks()
3. configure ngix
4. launch the app through "app.launch(share=True,server_name='0.0.0.0')"
here is the python file: https://github.com/XingangPan/DragGAN/blob/main/visualizer_drag_gradio.py

**Comment by freddyaboulton** [comment]
Did you follow this guide for the nginx configuration? https://gradio.app/running-gradio-on-your-web-server-with-nginx/

**Comment by abidlabs** [comment]
@aliabid94 I think we should display a better error, perhaps linking to this Guide, if `theme.css` cannot be found, instead of the UI just collapsing. Could we do that?

**Comment by LianShuaiLong** [comment]
> ```shell
> 3.35.2
> ```
it does work ,thanks
