### ISSUE TITLE
Telemetry appears to break the app

### ISSUE THREAD

**Issue by rsxdalv** [gradio-app/gradio#4719]
### Describe the bug

---> 20 demo2.launch(
     21     enable_queue=True,
     22 )

File [c:\Users\admin\Desktop\one-click-installers-tts-main\installer_files\env\lib\site-packages\gradio\blocks.py:1964](file:///C:/Users/admin/Desktop/one-click-installers-tts-main/installer_files/env/lib/site-packages/gradio/blocks.py:1964), in Blocks.launch(self, inline, inbrowser, share, debug, enable_queue, max_threads, auth, auth_message, prevent_thread_lock, show_error, server_name, server_port, show_tips, height, width, encrypt, favicon_path, ssl_keyfile, ssl_certfile, ssl_keyfile_password, ssl_verify, quiet, show_api, file_directories, allowed_paths, blocked_paths, root_path, _frontend, app_kwargs)
   1951 if getattr(self, "analytics_enabled", False):
   1952     data = {
   1953         "launch_method": "browser" if inbrowser else "inline",
   1954         "is_google_colab": self.is_colab,
   (...)
   1962         "mode": self.mode,
   1963     }
-> 1964     analytics.launched_analytics(self, data)
   1966 utils.show_tip(self)
   1968 # Block main thread if debug==True

File [c:\Users\admin\Desktop\one-click-installers-tts-main\installer_files\env\lib\site-packages\gradio\analytics.py:122](file:///C:/Users/admin/Desktop/one-click-installers-tts-main/installer_files/env/lib/site-packages/gradio/analytics.py:122), in launched_analytics(blocks, data)
    115 for x in blocks.dependencies:
    116     targets_telemetry = targets_telemetry + [
    117         # Sometimes the target can be the Blocks object itself, so we need to check if its in blocks.blocks
    118         str(blocks.blocks[y])
    119         for y in x["targets"]
    120         if y in blocks.blocks
    121     ]
--> 122     inputs_telemetry = inputs_telemetry + [
    123         str(blocks.blocks[y]) for y in x["inputs"]
    124     ]
    125     outputs_telemetry = outputs_telemetry + [
    126         str(blocks.blocks[y]) for y in x["outputs"]
    127     ]
    128 additional_data = {
    129     "version": GRADIO_VERSION,
    130     "is_kaggle": blocks.is_kaggle,
   (...)
    145     "events": [str(x["trigger"]) for x in blocks.dependencies],
    146 }

File [c:\Users\admin\Desktop\one-click-installers-tts-main\installer_files\env\lib\site-packages\gradio\analytics.py:123](file:///C:/Users/admin/Desktop/one-click-installers-tts-main/installer_files/env/lib/site-packages/gradio/analytics.py:123), in (.0)
    115 for x in blocks.dependencies:
    116     targets_telemetry = targets_telemetry + [
    117         # Sometimes the target can be the Blocks object itself, so we need to check if its in blocks.blocks
    118         str(blocks.blocks[y])
    119         for y in x["targets"]
    120         if y in blocks.blocks
    121     ]
    122     inputs_telemetry = inputs_telemetry + [
--> 123         str(blocks.blocks[y]) for y in x["inputs"]
    124     ]
    125     outputs_telemetry = outputs_telemetry + [
    126         str(blocks.blocks[y]) for y in x["outputs"]
    127     ]
    128 additional_data = {
    129     "version": GRADIO_VERSION,
    130     "is_kaggle": blocks.is_kaggle,
   (...)
    145     "events": [str(x["trigger"]) for x in blocks.dependencies],
    146 }

KeyError: 1

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

It's part of a larger codebase. I cannot provide a minimal example.

### System Info

```shell
Name: gradio
Version: 3.35.2
Summary: Python library for easily interacting with trained machine learning models
Home-page:
Author:
Author-email: Abubakar Abid <team@gradio.app>, Ali Abid <team@gradio.app>, Ali Abdalla <team@gradio.app>, Dawood Khan <team@gradio.app>, Ahsen Khaliq <team@gradio.app>, Pete Allen <team@gradio.app>, Ömer Faruk Özdemir <team@gradio.app>
License:
Location: c:\users\admin\desktop\one-click-installers-tts-main\installer_files\env\lib\site-packages
Requires: aiofiles, aiohttp, altair, fastapi, ffmpy, gradio-client, httpx, huggingface-hub, jinja2, markdown-it-py, markupsafe, matplotlib, 
mdit-py-plugins, numpy, orjson, pandas, pillow, pydantic, pydub, pygments, python-multipart, pyyaml, requests, semantic-version, uvicorn, websockets
Required-by:
```

### Severity

I can work around it

**Comment by rsxdalv** [comment]
Workaround - gr.Blocks(... analytics_enabled=False ...)

**Comment by freddyaboulton** [comment]
Does this happen every time you launch the demo @rsxdalv ?

**Comment by rsxdalv** [comment]
I have a jupyter notebook that I use, and there it happens 100% of the time, when I run it in my project it works.
I tried a couple of minimal examples but they all pass, only the integration fails for now. The code I'm working with is as such:

```python
import gradio as gr
from src.history_tab.main import history_tab

if __name__ == "__main__":
    with gr.Blocks() as demo:
        history_tab(
            register_use_as_history_button=lambda x, y: None,
        )
        
    demo.launch()
```

**Comment by abidlabs** [comment]
We're seeing this error quite a bit, I think we can make the analytics code more fault tolerant, but if you have an example (even if it spans multiple files), that'll be helpful @rsxdalv

**Comment by abidlabs** [comment]
Related issue: https://github.com/gradio-app/gradio/issues/4642

I'll take a look into this
