### ISSUE TITLE
Make output components not editable if they are being updated

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#4733]
The show_progress functionality is nice.  However, for radio, text boxes, etc. the options don't seem to be best.

* "full" totally hides the underlying content, leading to UI/UX confusion when the elements disappear entirely during progress.
* "minimal" still allows one to click on the element, which is also confusing UX-wise since we are updating that element's values perhaps, and we don't want the user to yet again try to switch to something
* "hidden" leaves the original text in the textbox visible until there is completion, which is confusing UX-wise since it's editable while it's being updated.

One could add more .then() steps like to make a radio or text box interactive=False and then use "minimal", but this ends up being some ugly code.  I wonder if it's easy for gradio team to implement this directly?  So new option would be:

* "non_interactive": Element would be clearly visible, so no odd context switches, and it would  not be changable, so no UX confusions.  It would be like when interactive=False, a bit dim and not changable/clickable/etc.

I think this would make the most sense in many situations.  Thanks!

**Comment by abidlabs** [comment]
Good point, why are output components even editable if they are being updated? I think we should just make them non-interactive while the function is running. We can make this change as part of 4.0 along with the work we're doing in #1592  and #1954

cc @dawoodkhan82

**Comment by pseudotensor** [comment]
I'm not sure you can just always make them non-interactive.  The element can queue a next action, which is allowable even if I don't use things that way.

I think it has to be an option.

**Comment by abidlabs** [comment]
It is allowable, but should it be? I think it would usually be better to have two separate components if one needs a component to be both an input and output at the same time

I'll try to think of some concrete use cases to see if this would be too much of a breaking change

**Comment by pseudotensor** [comment]
@abidlabs Do you know of a temporary hack to work-around this so every output becomes non-interactive?  Just don't want to write so much code to do the switch-a-roo myself :)  Thanks!

**Comment by abidlabs** [comment]
Good question @pseudotensor, I don't think there's a simple hack unfortunately. You'd have to do add `.update(interactive=False)` to your function return and do a `.then()` to set the interactivity to True. We have done this within the Gradio code base itself in a couple of places so afaik there's no workaround

**Comment by abidlabs** [comment]
Fixed in `v4`!

**Comment by abidlabs** [comment]
Btw @pseudotensor we are planning on reverting this behavior as it introduced a lot of undesired behavior. For example, a dropdown whose choices were being updated would lose focus when it became static, and so you would not be able to dynamically update a dropdown's choices 

https://github.com/gradio-app/gradio/pull/7410/files
