### ISSUE TITLE
Gradio Architecture

### ISSUE THREAD

**Issue by jeromeku** [gradio-app/gradio#4736]
Not so much a feature request -- more elucidation of Gradio app architecture:

When using the `gradio.Blocks()` interface to create an app, when are the app components injected into the frontend template (i.e., `share.html` or `index.html`)?

Trying to understand how Python communicates with JS / Svelte to create the interactive frontend.  Digging into the source code, calling the `launch` method of a `blocks` object creates a `FastAPI` app that serves a gradio template as the homepage which has a placeholder tag `gradio-app` for hydration with the actual components.

However, having trouble identifying where the serialization of Python components to JS/Svelte components is happening within the codebase and when the template is being populated with these components.

**Comment by abidlabs** [comment]
Hi @jeromeku for general questions like this (that are not feature requests or bug reports), better to ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)

**Comment by pngwn** [comment]
We'll try to document some of this more in the future but the serialised app isn't really injected into the template (wel it is in one case but that is just an optimisation). 

The front end and backend are almost completely decoupled and instead rely on a simple contract. The python library generates a config for each components as well as a 'layout', detailing where each component sits in the tree. This information, along with some other metadata, is available in the `/config` route for the grading server. 

This JSON is taken by the front end and rendered into a tree of _actual_ components. That users interact with. 

The config also contains what we call 'dependencies'. This links actions (such as clicks), input components, and output components with specific functions in the backend. This gives us enough information to hook up the rest. We add these actions as listeners on the front end. When an action is triggered we collect the data from the correct input component(s) and then send it to the backend where it is routed to the correct function. When the data comes back, we pass that output data to the correct output component(s). This functionality is all handled either via  or al post requests or a web socket connection. 

This is obviously quite high level but explains some of the inner workings. Like I say, I'm hopeful we can document this a little better in the future. We will be refactoring some of the code in a short while and that seems like a good time to do so. 

If you have any questions or would like to know some of the specifics please let me know and I'll do my best to answer or I'll ping someone who can help.
