### ISSUE TITLE
`gr.Radio` and `gr.CheckboxGroup` choices display text.

### ISSUE THREAD

**Issue by taoari** [gradio-app/gradio#4754]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

Usually for the `gr.Radio` and `gr.CheckboxGroup`, the choices are  different for the program to process and UI display to the user. For example, in a program, it might be easier to have choices named like ["openai_completion", "openai_chat"], but it would be great to have the UI display as ["OpenAI (Completion)", "OpenAI (Chat)"].

**Describe the solution you'd like**  

 It would be great if there could be an additional argument 
 e.g. `choices_display` for  `gr.Radio` and `gr.CheckboxGroup` that can be used specifically for UI display.

**Additional context**

**Comment by abidlabs** [comment]
Similar to #3019, we should probably tackle them together
