### ISSUE TITLE
Gradio stream chatbot not working on AWS ECS

### ISSUE THREAD

**Issue by arditobryan** [gradio-app/gradio#4760]
### Describe the bug

Hi, I am running a gradio inside a fastapi instance, all containerized in docker.
In local, everything works perfectly.

However, on ECS: the code breaks when calling the function named bot:
it seems that the generator does not work and yield does not return a value

Does ECS have problem with queue(), perhaps? That is the only thing I can be thinking of
Thank you

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
def create_block(base_url):    

    def user(user_message, history):
        if user_message == '':
            user_message = 'Introduce yourself'
        return "", [['a', 'b']]                                     #up to here it works
        # return "", history + [[user_message, None]]

    def bot(history, consultant_name):                              ###NOT WORKING
        yield [['v1', 'v2']]                                        #on ECS, it keeps returning [['a', 'b']], and this function is ignored

    with gr.Blocks() as block:
        base_url = gr.Variable(value=base_url)
        consultant_name = gr.Variable(value='abc')
        
        chatbot = gr.Chatbot()
        msg = gr.Textbox()
        msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(bot, [chatbot, consultant_name], chatbot)
        # clear.click(lambda: None, None, chatbot, queue=False)

    return block.queue()

app = gr.mount_gradio_app(app, create_block(base_url=base_url), path="/") 

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)
```

### System Info

```shell
gradio==3.30.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @arditobryan nothing immediately pops out at me, but here are some ideas you could try:
* Upgrade to the latest version of `gradio`
* Ensure that ECS supports websockets (`.queue()` uses websocket protocol to communicate under the hood)
* Ensure that the version of Python is at least 3.8

**Comment by arditobryan** [comment]
Thank you @abidlabs 
If I can ask:

if I am correct, the right link to run the app now would be moved to wss://... (gradio app endpoint)
Is there any code that needs to be added to fastpi/gradio for it to happen? 
The load balancer is showing an empty page on that url, so I am assuming the base code may need some changes.

Thank you

**Comment by arditobryan** [comment]
made it work! Let me outline the instructions, in case any encounters the same issue (please correct me, if I am wrong):
When queue() is called in gradio (to allow some features like real-time writing for a chatbot), gradio uses websocket.
Even if I am running gradio on fastapi, gradio opens websocket on path /queue/join automatically, I do not need to add anything in my code.
This means that when I am running my instance on http://127.0.0.1:5000, for example, there is a websocket which has been reserved by gradio at ws://127.0.0.1/queue/join
Now, ECS (connected with an application load balancer) will run my container on PORT 443 https://www.example.com. This means that for my gradio queue() to run, it will also need a wss://www.example.com/queue/join (wss because it is a protected connection). This can be activated on the AWS ALB only by:
- Activating stickiness on ALB target group listener
- Have a load balancer listened on both port 80 and port 443 (otherwise, strangely, it won't work)

**Comment by abidlabs** [comment]
Thank you @arditobryan for providing the solution!

**Comment by mocsharp** [comment]
Hi @arditobryan How did you activate stickiness with ALB? I am seeing an error where a `LambdaTarget` does not support `stickiness.lb_cookie.duration_seconds`.  Any help would be greatly appreciated. Thanks!
