### ISSUE TITLE
Iterative image updating fails on some devices

### ISSUE THREAD

**Issue by htoyryla** [gradio-app/gradio#4761]
### Describe the bug

App should display image using iterative updates while the image is being generated in a diffusion process, but on some devices (iMac 2017, iPad) the updates stop prematurely and the page needs to be refreshed to recover. Server works ok all the time and there are no error messages anywhere.  The queue and other clients continue to work correctly.

See minimal example. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Code to reproduce. 

Press Go to start, progress should process incremental up to 99/100 while images of noise are displayed.

Works on many devices but on some gets stuck. Looks like the passing of the init_image to run() is essential, therefore the example does so even if in this minimal code the image is ignored.

```

import torch
from torchvision import transforms
import torchvision.transforms.functional as TF
from PIL import Image

import gradio as gr

import time
       
transform = transforms.Compose([transforms.Resize((768, 768)), transforms.ToTensor()]) 

tensor_to_pil = transforms.ToPILImage()

# diffusion run to be run by each user instance

def diffusion_run(progress):
    
    progress(0)

    # get initial noise (mixed with init image if present)
    
    for i in range(0,100):

        with torch.no_grad():
            x = torch.zeros(1,3,768,768).normal_(0,1)
            
            x -= x.min()
            x /= x.max()

            imout_raw = tensor_to_pil(x[0])  
                      
            imout = tensor_to_pil(1 - x[0])
            
            print(i)
            
            time.sleep(1)
            
            progress(float(i) / 100)
        
            yield imout, imout_raw, str(i)+"/"+str(100)
            
# gradio UI           
      
with gr.Blocks() as demo:
    
    imo = gr.State(Image.new('RGB', (768, 768)))
    
    with gr.Row():
        with gr.Column(min_width = 80):
            html = '<div style="font-size: 36px; color:#666666;">#urdiffusion</div><br>'+  \
            '<div style="font-size: 12px; color:#666666;">experimental single user version</div>' + \
            '<div style="font-size: 20px; color:#666666;">by @htoyryla 2023</div>'
            logo = gr.HTML(html)
        with gr.Column():
            text_input = gr.Textbox(label="Prompt")
            textw = gr.Slider(minimum=0., maximum=100., value=10., label="Text weight")
        with gr.Column():
            skip = gr.Slider(minimum=0, maximum=100, value=10, label="Skip")
            mul = gr.Slider(minimum=0., maximum=1., value=1., label="Noise level")
            weak = gr.Slider(minimum=0., maximum=1., value=0., label="Softness")
        init_image = gr.Image()
        with gr.Column():
            text_button = gr.Button("Go")
            process_status = gr.Textbox(label="Generation status")
        
    with gr.Row():    
        image_output_raw = gr.Image(label="generated")
        image_output = gr.Image(label="postprocessed")
    
    
    # function to run diffusion based on current settings    
    # passing im as an argument here appears to cause the problem
 
    def run(im):
        
        process_status.value = "Processing..."
        for im, imr, i in diffusion_run(progress=gr.Progress()):
            #print(i)
            imo = imr
            yield im, imr, str(i)     
            
    # buttons to trigger diffusion and post processing        
             
    text_button.click(queue=True, fn=run, inputs=[init_image], outputs=[image_output, image_output_raw, process_status])
    

demo.queue(concurrency_count=1)
demo.launch(server_name = "0.0.0.0")

```

### Logs

```shell
There are no errors displayed or logged.
```

### System Info

```shell
gradio                    3.35.2 

Problem occurs on

iPad 7. gen. iPadOS 16.5.1 using Safari and Google Chrome
iMac 27" 2017 macOS 12.6.1 using Safari and Firefox

It does not happen using

Mac mini M1 2020 running macOS 12.6.6
Ubuntu 20.04 with Firefox
Macbook Pro M1 2020, macOS 12.6.3 with Safari

Server running on Ubuntu 20.04

All devices in the same LAN.
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @htoyryla that's super weird. This is going to be a hard one for us to fix since we can't easily test on those devices. I'm going to mark this as a wont-fix unfortunately. If you are able to reproduce this on a more common device or are able to find any sort of errors in the terminal or in the javascript console, then we can give this another look.

**Comment by htoyryla** [comment]
I would like to investigate further what is really happening, and possibly to find a workaround, but can't see how to do that. From what happens, it seems to me that the browser side continues to wait further updates from the server, but the server has already moved on to handle the next task from the queue. As far I as see, I have no way of monitoring the communication between the two. As it is now, can't use this on the iPads (as they are already running the newest OS). 

I wonder if there is timing issue here. Don't really know how gradio works under the hood, being more familiar with doing separate server + api + a javascript client.
