### ISSUE TITLE
gr.JSON with gr.State

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [gradio-app/gradio#4768]
- [x ] I have searched to see if a similar issue already exists.

I'd be awesome to have a way to update a gr.JSON based on a gr.State, currently

```python
def on_sync_button_click():
    return { "foo" : "baa"}

current_data = gr.State(initial_data)
gr.JSON(current_data.value)
sync_button = gr.Button("Sync")
sync_button.click(on_sync_button_click, [], [current_data])
```
Does not update the UI

I think this is due to the fact that I need to do `.value` to render it and that is not tracked maybe

Thanks a lot

Fra

**Comment by abidlabs** [comment]
Hi @FrancescoSaverioZuppichini this is already supported. I can't really make out what your example is doing, but here's a quick example I put together:

```py
import gradio as gr

with gr.Blocks() as demo:
    with gr.Row():
        textbox = gr.Textbox()
        state = gr.State()
        json = gr.JSON()
    
    s = gr.Button("Store Textbox -> State")
    l = gr.Button("Load State -> JSON")
    
    s.click(lambda x:x, textbox, state)
    l.click(lambda x:x, state, json)
    
demo.launch()
```

<img width="772" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/6f4006c9-2808-4ef7-ad13-c141724b773d">

**Comment by FrancescoSaverioZuppichini** [comment]
I'd like to display a `gr.State` inside a `gr.JSON`. Maybe this example makes more sense

```python
import gradio as gr

def handler():
    return { "foo" : "b"}

initial_data = {"foo": "a"}

with gr.Blocks() as demo:
    current_data = gr.State(initial_data)
    gr.JSON(current_data)
    button = gr.Button("update")
    button.click(handler, [], [current_data])
```

Which results in 

![Uploading Screenshot 2023-07-03 at 15.49.10.png…]()

If I change it to .value, I can see it but it doesn't update if I click the button

<img width="1275" alt="Screenshot 2023-07-03 at 15 49 34" src="https://github.com/gradio-app/gradio/assets/15908060/f68d6e6b-c23f-4b9a-b0d6-33bb70579abf">

So if I understood, I should just use the json 

```python
import gradio as gr

def handler():
    return { "foo" : "b"}

initial_data = {"foo": "a"}

with gr.Blocks() as demo:
    # current_data = gr.State(initial_data)
    current_data = gr.JSON(initial_data)
    button = gr.Button("update")
    button.click(handler, [], [current_data])
```

Thanks a lot, apologies for the noob question. I really like `gr.State` but I think I am maybe overusing 😓

**Comment by abidlabs** [comment]
Yes, you can just use the json directly, is there any reason this doesn't work for you?

**Comment by FrancescoSaverioZuppichini** [comment]
> Yes, you can just use the json directly, is there any reason this doesn't work for you?

directly with the JSON works perfectly, thanks again
