### ISSUE TITLE
Missing Development Requirements

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#477]
**Describe the bug**
The repo is missing development requirements, and there are failing requirements for testing.

**To Reproduce**
- `virtualenv .venv`
- `source .venv/bin/activate`
- `pip install -e .`
- `python -m unittest`

**Screenshots**
While running the unittests there are missing requirements that are not included in **setup.py** ie:
```
    assert jinja2 is not None, "jinja2 must be installed to use Jinja2Templates"
AssertionError: jinja2 must be installed to use Jinja2Templates
```

**Device information (please complete the following information):**
 - OS: macos
 - Gradio version [e.g. 2.7.1]  

**Additional context**
I think defining development requirements via `requirements.txt` would be nice.

**Comment by abidlabs** [comment]
Some quick points:
* The Python requirements for the `gradio` library are listed in `setup.py`. To avoid duplicating, I don't think there is a need for a `requirements.txt`
* For testing, we do need additional requirements as you pointed out. Right now, they are manually listed in `.circleci/config.yml`.
* I agree with you that we should have a better place where we define these. What about creating a `test/requirements.txt` file?

**Comment by FarukOzderim** [comment]
OK then, let's continue with adding additional requirements to the `test/requirements.txt`.
