### ISSUE TITLE
Gradio, Whisper Transcribe loading then times out 

### ISSUE THREAD

**Issue by FusionMediatest** [gradio-app/gradio#4775]
### Describe the bug

Hi, so I have written the code for a transcribe to be able to happen. And basically, it will load for around 5 seconds and then it will come up with this error "Something went wrong Connection errored out" I was wondering if anyone can advise me on what to do. Listed below is my current code:

import traceback
from gradio import Interface, Audio, Textbox
from moviepy.editor import AudioFileClip
import whisper

def transcribe_audio(audio_file):
    try:
        audio_clip = AudioFileClip(audio_file)
        audio_array = audio_clip.to_soundarray()
        model = whisper.load_model("base")
        result = model.transcribe(audio_array)
        return result("text")
    except Exception as e:
        traceback.print_exc()
        return "An error occurred during transcription."

def main():
    audio_input = Audio(source="upload", type="filepath")
    output_text = Textbox()

    demo = Interface(fn=transcribe_audio, inputs=audio_input, outputs=output_text,
                     title="Fusion Media", description="Upload an audio file")

    demo.launch()

if __name__ == '__main__':
    main()

<img width="616" alt="Screenshot 2023-07-03 at 21 33 55" src="https://github.com/gradio-app/gradio/assets/138528309/17ef8185-7d4f-4322-86e2-acfc20994f42">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import traceback
from gradio import Interface, Audio, Textbox
from moviepy.editor import AudioFileClip
import whisper

def transcribe_audio(audio_file):
    try:
        audio_clip = AudioFileClip(audio_file)
        audio_array = audio_clip.to_soundarray()
        model = whisper.load_model("base")
        result = model.transcribe(audio_array)
        return result("text")
    except Exception as e:
        traceback.print_exc()
        return "An error occurred during transcription."

def main():
    audio_input = Audio(source="upload", type="filepath")
    output_text = Textbox()

    demo = Interface(fn=transcribe_audio, inputs=audio_input, outputs=output_text,
                     title="Fusion Media", description="Upload an audio file")

    demo.launch()

if __name__ == '__main__':
    main()

### System Info

```shell
Version: 3.35.2
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
I don't see any obvious issues. Can you try enabling queue? You can do this by replacing `demo.launch()` with `demo.queue().launch()`

We do not have details in this issue to reproduce. For example:
1. Have you tried running the `transcribe_audio` function directly? Does it work?
2. The code here is formatted very strangely, please use the triple backdashes markdown formatting so that we can run this code
3. Does a simpler Gradio app work for you? Please share the code for the simplest Gradio app that isn't work for you

**Comment by abidlabs** [comment]
Will close for now, we can reopen with a suitable repro
