### ISSUE TITLE
Chatbot show empty message bubble when there is a ':' in text.

### ISSUE THREAD

**Issue by 1ittlesnow** [gradio-app/gradio#4780]
### Describe the bug

When yield `chatbot = [['What is your name?','A: my name is A']]`  to gr.Chatbot.
Chatbot doesn't show text, but a empty message bubble.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

yield `chatbot = [['What is your name?','A: my name is A']]`  to gr.Chatbot

### System Info

```shell
Server is on linux. Web is on Windows.
```

### Severity

I can work around it

**Comment by arian81** [comment]
Your issue can't be replicated. I tired your code and it works fine on my end. What gradio version are you using ?
![image](https://github.com/gradio-app/gradio/assets/35879206/07f9bd29-f5a3-4f87-95f4-bb354f6ac5e1)

**Comment by abidlabs** [comment]
Thanks for checking @arian81.

@1ittlesnow can you provide a full self-contained code example we can use to repro the issue please?

**Comment by abidlabs** [comment]
Will close for lack of follow up
