### ISSUE TITLE
Add CI Checks and Actions About Backend Formatting

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#479]
Now that we have the Python codebase nicely formatted, let's maintain that by adding pre-commits for formatting and other relevant checks (perhaps a warning if large files are being committed, etc.)

**Comment by FarukOzderim** [comment]
Related issue: #470

**Comment by FarukOzderim** [comment]
I suggest we use these libraries for formatting

    ```
Black for code reformatting
    isort for sorting imports
    Mypy for static type checking
    Pylint for generic static checking of code
    Flake8 for style guide enforcement

```

**Comment by abidlabs** [comment]
Looks like we can close this @FarukOzderim?

**Comment by FarukOzderim** [comment]
Oh, I was just using github projects done button, It seems I need to close it as well, is it not automatic though @pngwn @abidlabs?

**Comment by abidlabs** [comment]
Yup it looks like Projects doesn't support that, but it does have the following 2 automations:

![image](https://user-images.githubusercontent.com/1778297/154273656-cad5fb22-9ccc-4e66-bffc-bfb9d7874120.png)

![image](https://user-images.githubusercontent.com/1778297/154273726-416cdbc9-5380-4a4f-9fcc-682d0dac6134.png)
