### ISSUE TITLE
Changing `File` value programmatically doesn't trigger `.change()` event

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#4799]
### Describe the bug

If the value of the File component is changed programmatically, it doesn't trigger the `.change()` event. 

Similar to #4378 but different underlying problem as far as I can tell

See example below:

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```py
import gradio as gr

def testa():
    print("a change called")
    return 

def testb():
    print("b change called")
    return 


with gr.Blocks() as demo:
    a = gr.File()
    b = gr.File()
    c = gr.File()
    
    a.change(lambda x:x.name, a, b)
    a.change(testa, None, None)
    b.change(lambda x:x.name, b, c)
    b.change(testb, None, None)
    
demo.launch()
```

### System Info

```shell
3.35.2
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Think I have a fix

**Comment by abidlabs** [comment]
Thanks @freddyaboulton!
