### ISSUE TITLE
Problems using chatbot

### ISSUE THREAD

**Issue by xxWeiDG** [gradio-app/gradio#4802]
### Describe the bug

When I use chatbot to display the data returned by my model, "##" is the glyph I set. The "##" at the beginning of the data cannot be displayed but the "##" in the data can be displayed normally.
such as
The data returned by the model is ##12345678##123456
Chatbot can only display 12345678##123456

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

``def main(): 

     demo.queue().launch(server_name='0.0.0.0',server_port=7711, share=False, inbrowser=True)  

 

def postprocess(self, y): 

    if y is None: 

        return [] 

    for i, (message, response) in enumerate(y): 

        y[i] = ( 

            None if message is None else mdtex2html.convert((message)), 

            None if response is None else mdtex2html.convert(response), 

        ) 

    return y 

 

gr.Chatbot.postprocess = postprocess 

 

 

 

def parse_text(text): 

    """copy from https://github.com/GaiZhenbiao/ChuanhuChatGPT/""" 

    lines = text.split("\n") 

    lines = [line for line in lines if line != ""] 

    count = 0 

    for i, line in enumerate(lines): 

        if "```" in line: 

            count += 1 

            items = line.split('`') 

            if count % 2 == 1: 

                lines[i] = f'<pre><code class="language-{items[-1]}">' 

            else: 

                lines[i] = f'<br></code></pre>' 

        else: 

            if i > 0: 

                if count % 2 == 1: 

                    line = line.replace("`", "\`") 

                    line = line.replace("<", "&lt;") 

                    line = line.replace(">", "&gt;") 

                    line = line.replace(" ", "&nbsp;") 

                    line = line.replace("*", "&ast;") 

                    line = line.replace("_", "&lowbar;") 

                    line = line.replace("-", "&#45;") 

                    line = line.replace(".", "&#46;") 

                    line = line.replace("!", "&#33;") 

                    line = line.replace("(", "&#40;") 

                    line = line.replace(")", "&#41;") 

                    line = line.replace("$", "&#36;") 

                lines[i] = "<br>"+line 

    text = "".join(lines) 

    return text 

 

 

def predictwebui(user_instruction, user_input, chatbot, temperature, top_p,top_k_number,num_beams_number,length_penalty_number): 

    chatbot.append((parse_text(user_instruction+user_input), "")) 

    re = '' 

    for response in predict(user_instruction, user_input, temperature, top_p,top_k_number,num_beams_number,length_penalty_number): 

        #print("@@@"+response+"@@@") 

        re=re+response 

        chatbot[-1] = (parse_text(user_instruction+user_input), parse_text(re)) 

        #print(chatbot[-1])      

        yield chatbot 

 

 

def reset_user_input(): 

    return gr.update(value='') 

 

def reset_user_instruction(): 

    return gr.update(value='') 

 

def reset_state(): 

    return [], [] 

 

 

with gr.Blocks() as demo: 

    gr.HTML("""<h1 align="center">CPPE Chat</h1>""") 

 

    chatbot = gr.Chatbot() 

    print("创建chatbot") 

    with gr.Row(): 

        with gr.Column(scale=4): 

            with gr.Column(scale=7): 

                user_instruction = gr.Textbox(show_label=False, placeholder="Input instruction...", lines=1).style( 

                    container=False) 

                user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=6).style( 

                    container=False) 

                 

            with gr.Column(min_width=32, scale=1): 

                submitBtn = gr.Button("Submit", variant="primary") 

        with gr.Column(scale=1): 

            emptyBtn = gr.Button("Clear History") 

            #max_length = gr.Slider(0, 4096, value=2048, step=1.0, label="Maximum length", interactive=True) 

            top_p = gr.Slider(0, 1, value=0.7, step=0.01, label="Top P", interactive=True) 

            top_k_number = gr.inputs.Number(default=40, label="top_k:") 

            num_beams_number = gr.inputs.Number(default=1, label="num_beams:") 

            length_penalty_number = gr.inputs.Number(default=0, label="length_penalty:") 

            temperature = gr.Slider(0, 1, value=0.95, step=0.01, label="Temperature", interactive=True) 

 

    history = gr.State([]) 

 

    #submitBtn.click(predict, [user_input, chatbot, max_length, top_p, temperature, history], [chatbot, history],show_progress=True) 

    submitBtn.click(predictwebui, [user_instruction, user_input, chatbot, temperature, top_p,top_k_number,num_beams_number,length_penalty_number], [chatbot]) 

    # submitBtn.click(reset_user_input, [], [user_input])#自动清空输入框 

    # submitBtn.click(reset_user_instruction, [], [user_instruction])#自动清空输入框/ 

 

 

    emptyBtn.click(reset_state, outputs=[chatbot, history], show_progress=True) 

 

 

 

if __name__ == "__main__": 

 

    main() 

     ``

### System Info

```shell
gradio 3.28.3When I use chatbot to display the data returned by my model, "##" is the glyph I set. The "##" at the beginning of the data cannot be displayed but the "##" in the data can be displayed normally.
such as
The data returned by the model is ##12345678##123456
Chatbot can only display 12345678##123456
```

### Severity

I can work around it

**Comment by dawoodkhan82** [comment]
@xxWeiDG The chatbot is most likely recognizing `##` as markdown. You should be able to escape it by adding a backslash `\##`. Soon I'll add an option to disable markdown.

**Comment by xxWeiDG** [comment]
> @xxWeiDG The chatbot is most likely recognizing `##` as markdown. You should be able to escape it by adding a backslash `\##`. Soon I'll add an option to disable markdown.

OK,thank you!!!
