### ISSUE TITLE
Detect textbox focus

### ISSUE THREAD

**Issue by arian81** [gradio-app/gradio#4817]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I need to detect when a user clicks in the textbox field. 

**Describe the solution you'd like**  
create a new event trigger for textboxes that shows when the user has clicked to type in the textbox.

**Additional context**  
This is a very common trigger in JavaScript applications and I'm very surprised it doesn't already exist in gradio.

**Comment by abidlabs** [comment]
Yep seems reasonable to me to add a `.focus()` event to `gr.Textbox()` and `gr.Number()`. PRs are welcome

**Comment by JodyZ0203** [comment]
Would it be possible for me to work on this? If so, I would like to pick this one up. Thanks!

**Comment by abidlabs** [comment]
Hi @JodyZ0203 yes thanks! We're happy to review your PR

**Comment by JodyZ0203** [comment]
Hi @abidlabs, I have created a PR that adds the focus event. Thanks!
