### ISSUE TITLE
`gr.DuplicateButton` appears even when run in a local environment

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#4825]
### Describe the bug

Though the [documentation of DuplicateButton](https://www.gradio.app/docs/duplicatebutton#description) says that it appears only on HF Spaces, it actually appears even when run in a local environment.
![](https://github.com/gradio-app/gradio/assets/25161192/84fd6713-9c78-4725-9ab2-d0b87a0400b9)

I can workaround by adding `visible=os.getenv('SYSTEM') == 'spaces'`, but I guess it's supposed to work without doing this.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
    gr.DuplicateButton()
demo.queue().launch()
```

### Screenshot

![](https://github.com/gradio-app/gradio/assets/25161192/cca0b877-7357-4aee-8f9c-733f123c07eb)

### System Info

```shell
gradio==3.36.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
It's the documentation that needs to be updated. We decided to show the button even when running locally (but it would not have any effect) to avoid surprises when uploading to Spaces
