### ISSUE TITLE
How to change the loading spinner animation and text?

### ISSUE THREAD

**Issue by jaxusaras** [gradio-app/gradio#4827]

**Comment by abidlabs** [comment]
Hi @jaxusaras can you elaborate on what you are requesting? There are not enough details here

**Comment by jaxusaras** [comment]
![Screenshot (174)](https://github.com/gradio-app/gradio/assets/137917192/e1b4d1ad-1e49-4e05-ae2e-3fb3bb10cd42)
this loading how to change the logo

**Comment by abidlabs** [comment]
Not possible through the Python API. I'm pretty sure it's possible through [custom CSS](https://www.gradio.app/guides/custom-CSS-and-JS). By the way, for general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
