### ISSUE TITLE
Row equal_height seems to be a new default that broke existing layout code.

### ISSUE THREAD

**Issue by rsxdalv** [gradio-app/gradio#4843]
### Describe the bug

The new version made changes to equal height defaults for gr.Row(), so many layouts broke. 

New: gradio==3.35.2
Old: gradio==3.33.1

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr


def ui():
    with gr.Tab("Tab"), gr.Row():
        with gr.Column():
            gr.Markdown(
                """
            00000000000000000000000000000000000000000000000
            0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
            """
            )
            gr.Dropdown(
                choices=[
                    "0000000000000000000000000000000000000000000000000000000000000",
                    "0000000000000000000000000000000000000000000000000000000000000000",
                    "0000000000000000000000000000000000000000000000000000000000000000000",
                ],
                value="0000000000000000000000000000000000000000000000000000000000000",
                interactive=True,
            )

            gr.Audio(
                type="filepath",
                source="upload",
                interactive=True,
            )

            gr.Checkbox(value=True)

            gr.Button(variant="primary")

        with gr.Column():
            gr.Markdown(":")
            gr.Textbox(interactive=False)

            gr.Audio()

            gr.Button(
                value="Use as history", variant="secondary"
            )


if __name__ == "__main__":
    with gr.Blocks() as demo:
        ui()
    demo.launch()
```

### Screenshot

![127 0 0 1_7862_](https://github.com/gradio-app/gradio/assets/6757283/566c913c-fdf3-4f40-9ef6-e47c7d70b7ee)

### System Info

```shell
gradio==3.35.2
# gradio==3.33.1
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @rsxdalv is this still an issue in the latest version of `gradio` (4.9.0 currently)?

**Comment by rsxdalv** [comment]
> Hi @rsxdalv is this still an issue in the latest version of `gradio` (4.9.0 currently)?

Haven't tested. If I ever do upgrade I will come back and comment, but it seems unlikely. Hence, we could close this unless there are other interested parties.

**Comment by abidlabs** [comment]
OK from my testing of an adapted version of your code, I don't see the issue, so I'll go ahead and close.

**Comment by rsxdalv** [comment]
Thanks for testing it out and fixing it!
