### ISSUE TITLE
Sweep: Write unit test for checkbox component

### ISSUE THREAD

**Issue by hannahblair** [gradio-app/gradio#4853]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
We need a unit test for the Checkbox component. 

**Describe the solution you'd like**  
Add a unit test like `Textbox.test.ts` for the Checkbox component, which is found in `js/app/src/components/Checkbox/Checkbox.svelte`

**Comment by freddyaboulton** [comment]
Should we close @hannahblair ?

**Comment by wwzeng1** [comment]
Hey @freddyaboulton @hannahblair, we had an outage this morning which I just fixed. Appreciate you taking the time to try Sweep. 

I also modified Sweep to only make a new PR if the issue comment is prefixed with "Sweep: " (Apologies for the spam @freddyaboulton)
