### ISSUE TITLE
Gradio Client should list out acceptable options for Radio/Dropdown/CheckboxGroup

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#4858]
### Describe the bug

If the Gradio app contains a Radio/Dropdown/CheckboxGroup component, the Clients should provide the list of valid options (maybe the first 5 options, so it doesn't get too verbose). It also should not assume the options are strings, as they can be numbers as well. Right now, for example, the Client assumes that [this Space](https://fffiloni-video-frame-interpolation.hf.space/) requires a string for the Radio button parameter where it actually requires a number:

<img width="905" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/de17225c-722d-40d1-95e3-28271f011d60">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

See above

### System Info

```shell
3.36
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Tricky thing is that the valid options for these components can change at any time. I think this will be blocked until we store the session config on the backend. But we'll have to educate users that some of the view_api info can be outdated at any time.

**Comment by abidlabs** [comment]
This is now the case:

<img width="526" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/354c9fbd-1c33-4340-a943-f229a6a930f7">

They reflect the valid options when the Gradio app is first initialized, but I think that's reasonable.
