### ISSUE TITLE
Auto scroll to bottom in components 

### ISSUE THREAD

**Issue by yvrjsharma** [gradio-app/gradio#4862]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Textbox doesn't scroll to the bottom or the latest line if we use it to populate real-time data. This behavior is consistent with Markdown and HTML components too.

**Describe the solution you'd like**  
If I am populating my logs in a textbox (/markdown/html), having the component automatically scroll to the latest line will be useful. This is similar to how it happens in a Chatbot. The Chatbot component scrolls to the newest message.

**Additional context**  
https://github.com/gradio-app/gradio/assets/48665385/dd11b36c-489b-46ff-9a0e-4167b0f00cc3

**Comment by abidlabs** [comment]
Would probably solve this as well: https://github.com/gradio-app/gradio/issues/4044

**Comment by SpenserCai** [comment]
I think you can use Interval to do that
```python
gr.Textbox(lines=25, readonly=True, elem_id="idxx")
start_jscode = """
                function() {
                    if (window.iidxx) {
                        window.clearInterval(window.iidxx);
                    }
                    var dividxx = document.getElementById('idxx');
                    var textarea = dividxx.querySelector('textarea');
                    window.iidxx = window.setInterval(function() {
                        textarea.scrollTop = textarea.scrollHeight;
                    }, 500);
                    
                }
"""
start_button = gr.Button("Start")
start_button.click(inputs=[....],outputs=[....],fn=start_bot,_js=start_jscode)
```

**Comment by Node-imapsalient11** [comment]
https://transvestite72.github.io/shooter/



See this answer for details
