### ISSUE TITLE
/info call being made to base instead of path setup using mount_gradio_app

### ISSUE THREAD

**Issue by khilnani** [gradio-app/gradio#4867]
### Describe the bug

When i follow the example code at https://www.gradio.app/docs/mount_gradio_app to run a Gradio app on a path, the call for `/info` is not being made relative to the path but is being made to the base

Call for `info` is being made to `/info` instead of `/gradio/info` and returns 404 Not Found.
Manually calling `/gradio/info` seems to return the correct info

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

python3 -m pip install gradio==3.36.1 uvicorn
OR
python3 -m pip install gradio==3.36.1 pydantic==1.10.1 

Code for `run.py` from https://www.gradio.app/docs/mount_gradio_app 
```
from fastapi import FastAPI
import gradio as gr
app = FastAPI()
@app.get("/")
def read_main():
    return {"message": "This is your main app"}
io = gr.Interface(lambda x: "Hello, " + x + "!", "textbox", "textbox")
app = gr.mount_gradio_app(app, io, path="/gradio")
# Then run `uvicorn run:app` from the terminal and navigate to http://localhost:8000/gradio.
```

Run app using: `uvicorn run:app`

### Logs

```shell
INFO:     127.0.0.1:63596 - "GET /info HTTP/1.1" 404 Not Found
```
```


### System Info

```shell
gradio==3.36.1
OR
gradio==3.36.1 pydantic==1.10.1
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
I can't reproduce @khilnani ! The console nor network tab shows anything about not being able to fetch the info route. The info route is fetched when clicking the `View Api` link in the bottom.

![info_route](https://github.com/gradio-app/gradio/assets/41651716/fadf4c8c-c410-4035-b79e-a07076ccdf03)

**Comment by abidlabs** [comment]
Will close for lack of repro

**Comment by khilnani** [comment]
Its inconsistent, will make a video of the issue and create a new ticket and reference this one

**Comment by khilnani** [comment]
Created a new ticket #4928  with additional detail
