### ISSUE TITLE
Stop audio recording after certain time.

### ISSUE THREAD

**Issue by Sreerag-ibtl** [gradio-app/gradio#4872]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I would like to have the audio recording from the microphone to be stopped after a specific time has passed since the record button is pressed. This will help me give the user a gamified experience which otherwise won't work well for my use case.

**Describe the solution you'd like**  
I would like to have a feature where I can provide the time duration after which the audio recording is automatically stopped.

**Additional context**  
It would be helpful if any workaround be suggested if this is a difficult feature to implement.

**Comment by abidlabs** [comment]
Sounds like a special case of #428 so I'll close this issue. But cc @hannahblair, this would be good to tackle as part of the component cleanup
