### ISSUE TITLE
let fn work with a function returning a generator

### ISSUE THREAD

**Issue by codemee** [gradio-app/gradio#4875]
- [X] I have searched to see if a similar issue already exists.

It seems that the fn only work with a generator function but not a function returning a generator. Is there any reason  to differentiate a generator function with a function returning a generator?

Thanks for any help.

**Comment by abidlabs** [comment]
Hi @codemee yes those are two separate things and break the convention that the function or generator's return type should match the output components. Instead of supplying `your_function_that_returns_a_generator`, simply supply `your_function_that_returns_a_generator()` and it should work fine.
