### ISSUE TITLE
Uploading big files stuck

### ISSUE THREAD

**Issue by xiao12mm** [gradio-app/gradio#4883]
When I upload a small file, it has 1.7K, it is uploaded in an instant, when I upload a large file, it has 500M, I wait for ten minutes, but not finished uploading, I guess it is stuck, which setting can increase the timeout time? Or is it a bug?

**Comment by abidlabs** [comment]
Hi @xiao12mm can you please provide the code for your Gradio app so that we can reproduce? I'm going to close this for now, please follow the bug report template
