### ISSUE TITLE
Output Image is not shown in the output placeholder

### ISSUE THREAD

**Issue by ai-fast-track** [gradio-app/gradio#49]
First of all, thank you very much for building such an awesome and easy-to-use app.

I'm trying to use gradio for our Object Detection Framework. Everything works smoothly except the output image is not shown in the output placeholder. I can see it in the debug output in the Colab notebook. Here is my notebook, and some screenshots. 

Thank you in advance for your help.

NB: https://colab.research.google.com/drive/1Xi5F5ddJIcgilHIG4bnk3tcGcx10FYP0?usp=sharing

![image](https://user-images.githubusercontent.com/59614262/91764415-44863a00-eba5-11ea-8de6-ee3602079a5c.png)

As you might notice, my output is PIL Image:
```
Output Image:  (432, 288) <class 'PIL.Image.Image'>
<Figure size 432x288 with 0 Axes>
```
![image](https://user-images.githubusercontent.com/59614262/91764497-68498000-eba5-11ea-8d50-8d7f4d5367fc.png)

**Comment by abidlabs** [comment]
Thank you for bringing this to our attention, we're taking a look at it!

**Comment by dawoodkhan82** [comment]
@ai-fast-track I'm having trouble reproducing this issue. Also having issues importing the mantisshrimp library from your colab notebook. Any idea how I can fix that?

**Comment by dawoodkhan82** [comment]
@ai-fast-track Closing issue for now. Please let me know if this still persists.

**Comment by atejap05** [comment]
Someone else has an example of how can I use gradio for object detection?
I've been tried to output an image with preds bboxes, but I went bad.

**Comment by abhigoku10** [comment]
@ai-fast-track @atejap05  where you able to to use gradio for object detection can you share the reference so that i can do it for different example Thanks in advance
