### ISSUE TITLE
ImageMask can not be updated

### ISSUE THREAD

**Issue by taoari** [gradio-app/gradio#4907]
### Describe the bug

ImageMask can not be updated. ImageMask returns a dict of 'image' and 'mask', however, this dictionary can not update the ImageMask component itself. See the following code, if the Image is not empty, an error will occur.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python

import gradio as gr

def bot(image, msg):
    return image, msg

with gr.Blocks() as demo:
    image = gr.ImageMask(type='pil', interactive=True)
    msg = gr.Textbox(show_label=False,
        placeholder="Enter text and press ENTER", container=False)
    msg.submit(bot, [image, msg], [image, msg])
    
demo.launch()
```

### System Info

```shell
(1) gradio 3.36.1 (2) Windows 11
```

### Severity

Blocking usage of gradio

**Comment by Ra1Nik** [comment]
Are there any updates on this?

**Comment by JalinWang** [comment]
I found where the bug comes from but have no idea about how to fix it.

![image](https://github.com/gradio-app/gradio/assets/20621784/d8fb7582-4e33-41b7-b66d-d6f8ffbe2be0)

During `postprocess`, the dict returned by `ImageMask` is processed by the function of `Image` which takes a PIL.Image
