### ISSUE TITLE
How to remove the empty space in the left and right?

### ISSUE THREAD

**Issue by krNeko9t** [gradio-app/gradio#4909]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
the web page gradio build have way much empty space in the left and right, can we have some control of it? sorry for the simple question but i could'find it online.

**Describe the solution you'd like**  
like:
```python
with gr.Blocks(margin="no margin"):
...
```

**Additional context**

**Comment by abidlabs** [comment]
Thanks @hannahblair I'll close this as custom css should suffice and I don't think we'll make it a parameter in Blocks.

**Comment by ardha27** [comment]
i do the same on gradio 5.4.0 but it only affect the left margin

**Comment by AlbertoParravicini** [comment]
For gradio 5.38 (and earlier versions, I suppose), you can now use `fill_height` and `fill_width`.
```
with gr.Blocks(fill_height=True, fill_width=True) as demo:
   ...
```
