### ISSUE TITLE
In this example, I suggest adding a copy button at the red marked section.

### ISSUE THREAD

**Issue by gaiyaa** [gradio-app/gradio#4911]
![image](https://github.com/gradio-app/gradio/assets/14996979/be06f06c-412b-43aa-b0b9-ff16852b873b)
In this example, I suggest adding a copy button at the red marked section.

**Comment by abidlabs** [comment]
Thanks @gaiyaa for the suggestion, we already include copy buttons for code, I don't think we'll do it for every chat message as that would clutter the UI too much.

**Comment by pseudotensor** [comment]
@abidlabs If it's a user choice to how to setup the chatbot, then there's no clutter issue since it's under user control.

**Comment by abidlabs** [comment]
That's true, let me play around with the PR a bit
