### ISSUE TITLE
Better messaging to indicate that the client returns filepaths on your local computer

### ISSUE THREAD

**Issue by hoalarious** [gradio-app/gradio#4917]
### Describe the bug

API returns wrong filepath for audio file

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

In a Kaggle notebook:
`!pip install gradio==3.36.1`
```
import gradio as gr

def something_function(inp):
    return "/kaggle/input/dataset/output.mp3"

demo = gr.Interface(fn=something_function, inputs="audio", outputs="audio")
demo.launch(debug=True, share=True)
```

In a Colab notebook
`!pip install gradio_client==0.2.9`

```
import gradio as gr
from gradio_client import Client

def resolve_gradio_filepath(share_url, filepath):
    return f'{share_url}/file={filepath}'

share_url = 'https://b61c53#######85d48.gradio.live'

client = Client(share_url)
result = client.predict(
        'input.mp3',	# str representing input in 'inp' Audio component
        api_name="/predict"
)
print(result)
print(resolve_gradio_filepath(share_url, result))
```

### Screenshot

API returns:
/tmp/gradio/2ec306c7b672def5ea91249481954dce0e87e551/output.mp3

Going to:
https://b61c53ca2d08285d48.gradio.live/file=/tmp/gradio/2ec306c7b672def5ea91249481954dce0e87e551/output.mp3

Leads to response of file not found.

In the Kaggle notebook we can see that none of the tmp folders match the hash from the filepath.

One of these folders contain the uploaded audio file and the other is the output audio file. 

![image](https://github.com/gradio-app/gradio/assets/16618954/394f6952-57ea-4d1a-9326-5589e88aa402)

The hash in the filepath returned by the API is incorrect.

### System Info

```shell
Kaggle notebook running:
gradio==3.36.1

Google colab running:
gradio_client==0.2.9
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @hoalarious - that /tmp/ file is created in the machine you made the API request from, not the machine running the demo. So it should be in the colab machine.

**Comment by hoalarious** [comment]
Hi @freddyaboulton, thanks for the quick response. I did indeed check the /tmp/file on the server and it is showing a different hash.

The Kaggle notebook is the API server.

Hosting the API on my own machine also gives a different filepath but slightly different.

It returns:
/tmp/gradio/7ed01d89a28ecf5bdc7f231be075cf44e409de65/file=C:\Users\micro\AppData\Local\Temp\gradio\29ad3fb050266e939a61bc7a579bf1782489d281\output.wav

Which also doesn't quite work but at least it contains the correct filepath information and would work if I used:
https://5ce80#######a3d0.gradio.live/file=C:\Users\micro\AppData\Local\Temp\gradio\29ad3fb050266e939a61bc7a579bf1782489d281\output.wav

**Comment by hoalarious** [comment]
@freddyaboulton Ah silly me. I misread what you wrote. The file is already downloaded by the gradio client. Sorry for wasting your time.

**Comment by hoalarious** [comment]
Actually it might be helpful to someone else if we added some clarification in Return types of the automatically generated API documentation. 

Apologies if this isn't the correct way to do it. Should I open a new feature request instead? I Just thought perhaps the return type in the API could say:
# str representing local filepath where audio output has been downloaded.

Original:
# str representing output in 'output' Audio component

**Comment by abidlabs** [comment]
I agree @hoalarious about the messaging -- and we've heard this same question again -- I'll just reopen this issue and re-title it
