### ISSUE TITLE
DropDown Fetaure Issue

### ISSUE THREAD

**Issue by EdemGold** [gradio-app/gradio#492]
**Describe the bug**
When I make use of the dropdown component in the radio it does not return a GUI, it gives an empty output

**To Reproduce**
#Initalizing Gradio App
app_description = "This model transforms the tone of the text, from formal to informal, from Active to Passive. Choose your option from the drop-down."
app_title = "Tone Transfer"

app = gr.Interface(func,[gr.inputs.Dropdown("Casual-To-Formal","Formal-to-Casual","Active-to-passive","Passive-to-Active")],"text",description=app_description, title=app_title)

app.launch()

**Screenshots**

**Device information (please complete the following information):**
 - OS: [e.g. Windows or iOS]
 - Gradio version [e.g. 2.5.1]  

**Additional context**

**Comment by abidlabs** [comment]
Thanks so much, for reporting this @EdemGold. Confirming I can reproduce this as well (see [colab notebook](https://colab.research.google.com/drive/1oqcd9pnMOFfS_s0AN_macQPwzmOMmrml#scrollTo=bHArg1AuETfd))

I get a `TypeError: this.props.choices.map is not a function` error in the console.

@dawoodkhan82 or @aliabd can you take a look?

**Comment by abidlabs** [comment]
Thanks, this is now fixed on master. We'll push to pypi next week!
