### ISSUE TITLE
multiple users conflict

### ISSUE THREAD

**Issue by thinkyang88** [gradio-app/gradio#4920]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
When the gradio program is used by multiple people at the same time, the relevant input will overwrite the previous input. How to solve the problem of multi-person use or limit the use of a single person.

**Comment by abidlabs** [comment]
Hi @thinkyang88 can you please provide a code repro? This shouldn't be happening -- please take a look at this Guide for more info: https://www.gradio.app/guides/interface-state

**Comment by abidlabs** [comment]
Will close for now, until we have clarity
