### ISSUE TITLE
Automatically create a LLM plugin from a gradio app

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#4925]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
The gradio-tools library showed that there is interest in using gradio apps as tools for LLMs. I'd like to take one of the experiments I was working on in that library and bring it to the `gradio_client` library to maximize usage and impact: **automatically creating LLM plugins from gradio apps.**

My proposal is the following:

Add a `deploy_plugin` method from a `gradio_client.Client` instance with the following signature:
```python
    def deploy_plugin(self,
        api_names: List[str],
        org_name: str | None = None,
        version: str = "v1",
        hf_token: str | None = None,
        private: bool = True,
        email: str | None = None,
        llm: Literal["chatgpt"] = "chatgpt"):
```
Note: `email` is needed by ChatGPT plugins. 

Under the hood - this will create a new space that serves the necessary metadata needed for ChatGPT to recognize the space as a ChatGPT plugin. Right now I'm mentioning ChatGPT because that's the LLM with the most mature plugin ecosystem that I know of but it should be possible to support other LLMs (e.g. [huggingchat](https://twitter.com/victormustar/status/1676950419048902658?s=20) when they allow plugins). The `llm` argument will make that configuration possible.

Then users can do the following once there is a space they want to deploy as a plugin:

```python
client = grc.Client("freddyaboulton/video-creator")
client.deploy_plugin(api_names=['/generate'], private=False)
```

We can even make this a configuration parameter to `gradio deploy`, e.g.

```bash
gradio deploy-plugin freddyaboulton/video-creator --api-names generate  --private false
```

The benefits of doing this approach:
- Users interested in using gradio as plugins pay for their own compute. I also thought about modifying `gradio` core so that all gradio apps can be plugins but that may spam spaces with automated calls that will degrade the experience of users using the UI. There has been concern about this in the past with just the current `gradio_client`
- ChatGPT plugins timeout after 60 seconds so this will incentivize users to duplicate spaces to keep runtime low
- Create an ecosystem of plugins on the hub. The hub can be the place to share/discover plugins. We can create a gallery space to showcase the plugins created by the community.

**Comment by abidlabs** [comment]
Super cool @freddyaboulton! So the idea is that this will create a new Space for that user?

**Comment by abidlabs** [comment]
This is awesome, I'm a big fan of the duplication + deployment approach -- we can use the same approach to deploying Gradio apps to other platforms as well.

```py
    def deploy_discord(self,
        api_names: List[str],
        discord_token: str
        org_name: str | None = None,
        version: str = "v1",
        hf_token: str | None = None,
        private: bool = True):
```

and 

```
gradio deploy-discord freddyaboulton/chat
```
