### ISSUE TITLE
Why do most requests use absolute paths? This results in an error when using the secondary directory reverse proxy.

### ISSUE THREAD

**Issue by viyiviyi** [gradio-app/gradio#4929]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Why do most requests use absolute paths? This results in an error when using the secondary directory reverse proxy.

**Describe the solution you'd like**  
I wanted to reverse proxy an application created by gradio, but only in the secondary directory, and as a result most of the requests originated from the absolute path, which did not work.

**Comment by abidlabs** [comment]
Hi @viyiviyi there aren't enough details in this question. Please provide sample code and explain which absolute paths you are referring to

**Comment by viyiviyi** [comment]
I'm sorry，I'm not sure about the problem right now.
