### ISSUE TITLE
The component cancels parameter is not valid in some scenarios.

### ISSUE THREAD

**Issue by Kilig947** [gradio-app/gradio#4930]
### Describe the bug

When the component has two queued tasks, using cancels to cancel the task while the first task is running only cancels the last task, and the dialog is still in progress

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
with gr.Blocks() as demo:   # 绘制一个块对象，在此基础上可以使用Row、Column、Tab、Box等等布局元素
    gr.Markdown(f"<h1 align=\"center\">我是Bolcks</h1>")
    with gr.Row():
        with gr.Column(scale=100):    # 组件绘制在布局元素下，则会根据布局元素的规定展示
            gr.Markdown('# 这里是列1')
            chatbot = gr.Chatbot().style(height=400)
            status = gr.Markdown()

        with gr.Column(scale=50):
            gr.Markdown('# 这里是列2')
            i_say = gr.Textbox().style(show_copy_button=True)
            submit = gr.Button(value='一次性对话', variant='primary')
            submit2 = gr.Button(value='流式对话', variant='stop')
            Noo = gr.Button(value='停止事件任务')

    def chat_plain_(x, y):
        return gr.update(), y.append(['TEST', 'Done'])

    def chat_steam_(x, y):
        for i in range(20):
            time.sleep(1)
            yield gr.update(), y.append(['TEST', i])


    # 注册函数，只能在Bolock上下文中注册
    # fn=要注册的函数， input=组件传输数据给函数接收的数据， outputs=接收函数处理后返回数据的组件
    cancel_handles = []
    cancel_handles.append(submit.click(fn=chat_steam_, inputs=[i_say, chatbot], outputs=[status, chatbot]))
    cancel_handles.append(submit2.click(fn=chat_steam_, inputs=[i_say, chatbot], outputs=[status, chatbot]).then(
        fn=chat_steam_, inputs=[i_say, chatbot], outputs=[status, chatbot]).then(
        fn=chat_plain_, inputs=[i_say, chatbot], outputs=[status, chatbot]
    ))
    Noo.click(fn=None, inputs=None, outputs=None, cancels=cancel_handles)
    
demo.queue(concurrency_count=100).launch(server_name="0.0.0.0", server_port=7699)
```

When [submit] is started and [Noo] stop is clicked, the task can be stopped normally, but if [submit2] is started and [Noo] stop is clicked, the task still continues to run.

### System Info

```shell
3.33.1
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @Kilig947 ! This looks a lot like https://github.com/gradio-app/gradio/issues/4276

basically you have to split up the .then statements in order to cancel every single event

**Comment by Kilig947** [comment]
> 



> 嗨！这看起来很像#4276
> 
> 基本上你必须拆分.then语句才能取消每个事件



> Hi @Kilig947 ! This looks a lot like #4276
> 
> basically you have to split up the .then statements in order to cancel every single event

`    
cancel_handles = []
    click_handles = submit.click(fn=chat_steam_, inputs=[i_say, chatbot], outputs=[status, chatbot])
    cancel_handles.append(click_handles)
    click_handles_2 = submit2.click(fn=chat_steam_, inputs=[i_say, chatbot], outputs=[status, chatbot])
    cancel_handles.append(click_handles_2.then(fn=chat_steam_, inputs=[i_say, chatbot], outputs=[status, chatbot]))
    cancel_handles.append(click_handles_2.then(fn=chat_plain_, inputs=[i_say, chatbot], outputs=[status, chatbot]))
`
I split the two then, but still can't fully pause the dialog event
![2023-07-16 13 44 59](https://github.com/gradio-app/gradio/assets/46100050/c7b361a5-9205-4bd1-b2d8-3e9b10b80998)

**Comment by abidlabs** [comment]
Can you provide the full updated code example you are running @Kilig947?

**Comment by Kilig947** [comment]
> Can you provide the full updated code example you are running @Kilig947?

```
# Make some cosmetic color adjustments
from comm_tools.theme import adjust_theme, custom_css
with gr.Blocks() as demo: # Draw a block object on which you can use Row, Column, Tab, Box and other layout elements.
    gr.Markdown(f"<h1 align=\"center\">I am Bolcks</h1>")
    with gr.Row(): with gr.Column(scale="center\">I am Bolcks</h1>")
        with gr.Column(scale=100): # If the component is drawn under a layout element, it will be displayed according to the layout element's rules.
            gr.Markdown('# Here is column 1')
            chatbot = gr.Chatbot().style(height=400)
            status = gr.Markdown()

        with gr.Column(scale=50):: gr.Markdown('# Here's column 1'): gr.Chatbot = gr.
            gr.Markdown('# Here is column 2')
            i_say = gr.Textbox().style(show_copy_button=True)
            submit = gr.Button(value='One-time conversation', variant='primary')
            submit2 = gr.Button(value='Streaming dialog', variant='stop')
            Noo = gr.Button(value='Stop event task')

    def chat_plain_(x, y).
        return gr.update(), y.append(['TEST', 'Done'])

    def chat_steam_(x, y).
        for i in range(20): time.sleep(1)
            time.sleep(1)
            yield gr.update(), y.append(['TEST', i])


    # Register the function, only in the Bolock context
    # fn=function to register, input=component transmits data to function to receive, outputs=component receives data returned by function after processing
    cancel_handles = []
    click_handles = submit.click(fn=chat_steam_, inputs=[i_say, chatbot], outputs=[status, chatbot])
    cancel_handles.append(click_handles)
    click_handles_2 = submit2.click(fn=chat_steam_, inputs=[i_say, chatbot], outputs=[status, chatbot])
    cancel_handles.append(click_handles_2.then(fn=chat_steam_, inputs=[i_say, chatbot], outputs=[status, chatbot]))
    cancel_handles.append(click_handles_2.then(fn=chat_plain_, inputs=[i_say, chatbot], outputs=[status, chatbot]))

    Noo.click(fn=None, inputs=None, outputs=None, cancels=cancel_handles)

demo.queue(concurrency_count=100).launch(server_name="0.0.0.0", server_port=7699)

Translated with www.DeepL.com/Translator (free version)
```
The full code is above，[submit2]The event cannot be canceled

**Comment by freddyaboulton** [comment]
@Kilig947 - I think it will be fixed if you add `click_handles_2` to `cancel_handles`

**Comment by Kilig947** [comment]
> @Kilig947 - I think it will be fixed if you add to `click_handles_2``cancel_handles`

    cancel_handles = []
    cancel_handles2 = []
    click_handles = submit.click(fn=chat_steam_, inputs=[i_say, chatbot], outputs=[status, chatbot])
    cancel_handles.append(click_handles)
    click_handles_2 = submit2.click(fn=chat_steam_, inputs=[i_say, chatbot], outputs=[status, chatbot])
    cancel_handles.append(click_handles_2.then(fn=chat_steam_, inputs=[i_say, chatbot], outputs=[status, chatbot]))
    cancel_handles2.append(click_handles_2.then(fn=chat_plain_, inputs=[i_say, chatbot], outputs=[status, chatbot]))

    Noo.click(fn=None, inputs=None, outputs=None, cancels=cancel_handles).then(fn=None, inputs=None, outputs=None, cancels=cancel_handles2)
    # Noo.click(fn=None, inputs=None, outputs=None, cancels=cancel_handles2)

I can't cancel the progress of a running task even if I change it this way

**Comment by abidlabs** [comment]
Hi @Kilig947 I tried to run your example, but there are unfortunately numerous syntax errors happening. Can you please provide correctly formatted code and ensure that it runs?

**Comment by abidlabs** [comment]
Will close for now, please share a reproducible example and we can reopen. Thanks!
