### ISSUE TITLE
Copying image from gr.Image() to gr.ImagePaint() breaks the webpage if browser scaling is not 100%

### ISSUE THREAD

**Issue by AUTOMATIC1111** [gradio-app/gradio#4931]
### Describe the bug

Copying image from `gr.Image()` to `gr.ImagePaint()` breaks the webpage if browser scaling is not 100%.

To trigger this error, run code from reproduction section, set browser scaling to >100% (ctrl + mouse wheel up), put an image into the left image component, and press the button. The image will be copied to the right image component, but the page will become extremely unresponsive and whatever is drawn on canvas will be moving in relation to image.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks(analytics_enabled=False) as demo:

    with gr.Row():
        src = gr.Image()
        dst = gr.ImagePaint()

    button_test = gr.Button('Copy')

    button_test.click(fn=lambda x: x, inputs=[src], outputs=[dst])

demo.launch(share=False)
```

### Screenshot

![firefox_lkW2c6CF3W](https://github.com/gradio-app/gradio/assets/20920490/bce4a2cc-68d6-4b8f-9a14-395a221ec82d)

### Logs

```shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

### System Info

gradio: 3.36.1, 3.32.0
OS: Windows 10
Python 3.10.6
Browser: Firefox 115.0.2 (64-bit), Chrome 114.0.5735.199 (Official Build) (64-bit)

### Severity

I can not work around it

**Comment by daswer123** [comment]
I should add that scaling in Windows other than 100% also causes the same problem
