### ISSUE TITLE
422 Error when click button

### ISSUE THREAD

**Issue by NIL-zhuang** [gradio-app/gradio#4936]
### Describe the bug

when I run the simple demo, it gives me 422 bug while my backend shows no error info even turned `debug=True`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

use the source code below
```python
import gradio as gr


def generate(text:str):
    print(text)
    return "output"

with gr.Blocks() as demo:
    input = gr.Textbox(label="input")
    output = gr.Textbox(label="output")
    btn = gr.Button("go")
    btn.click(
        generate,
        inputs=[input],
        outputs=[output]
    )
demo.launch(debug=True)
```

### Screenshot

<img width="1492" alt="image" src="https://github.com/gradio-app/gradio/assets/46214362/511ada2c-1e13-480c-b03b-e314e079c62c">

### System Info

```shell
gradio 3.23.0
macOS 13.4.1
google chrome browser
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Where are you running this code (is it in a Colab notebook or python terminal, etc.)? Can you also try with the latest version of gradio?

**Comment by NIL-zhuang** [comment]
> Where are you running this code (is it in a Colab notebook or python terminal, etc.)? Can you also try with the latest version of gradio?

Thanks! It works well when I upgrade gradio into v 3.36.1 with pypi.
Please consider updating conda-forge to catch up with the latest version, in case anyone meet the same problem.

**Comment by abidlabs** [comment]
Thanks @NIL-zhuang

**Comment by 21wang12** [comment]
Facing same problem when install the default version under conda environment with pip.
Fix this problem by specify the version of gradio when using pip.
```bash
pip install gradio==3.36.1
```
