### ISSUE TITLE
Adjust Output Label Classes Font size?

### ISSUE THREAD

**Issue by dummynov1** [gradio-app/gradio#494]
I have plugged in my TensorFlow Bert Multi Class classifier predict function on Gradio.
But, since the Class Labels are long, they get truncated while showing Label Confidence score Bars graph.
Is there a way to resize the label font or to add word wrap for long Class labels ?

**Device information:**
 - OS: Windows 10
 - Browser : chrome
 - Gradio version :2.7.5

**Comment by abidlabs** [comment]
Yes, you can provide custom `css` to resize the label fonts. Here is some sample code:

```python
import gradio as gr

def func(x):
  return {"a long label": 0.3, "another even longer label": 0.6}

app = gr.Interface(func, "text", "label", css=".label{font-size:0.6rem !important}")

app.launch()
```

which produces this:

![image](https://user-images.githubusercontent.com/1778297/151112587-ee0924f1-b00f-43c8-ba41-51e6cdcd41f3.png)

You can see it working in [this colab](https://colab.research.google.com/drive/1qVTcYXCtIE5riB1TzV2AZxhd3KwTESoY?usp=sharing):

**Comment by dummynov1** [comment]
> Yes, you can provide custom `css` to resize the label fonts. Here is some sample code:
> 
> ```python
> import gradio as gr
> 
> def func(x):
>   return {"a long label": 0.3, "another even longer label": 0.6}
> 
> app = gr.Interface(func, "text", "label", css=".label{font-size:0.6rem !important}")
> 
> app.launch()
> ```
> 
> which produces this:
> 
> ![image](https://user-images.githubusercontent.com/1778297/151112587-ee0924f1-b00f-43c8-ba41-51e6cdcd41f3.png)
> 
> You can see it working in [this colab](https://colab.research.google.com/drive/1qVTcYXCtIE5riB1TzV2AZxhd3KwTESoY?usp=sharing):

Thanks for the prompt response. Will definitely try the css way.
