### ISSUE TITLE
docker file 缺少scipy依赖

### ISSUE THREAD

**Issue by ACoolOctober** [gradio-app/gradio#4945]
### Describe the bug

使用docker方式部署时 出现依赖缺失
![1689608501903](https://github.com/gradio-app/gradio/assets/61481593/0a9dfbdf-a6f1-4d1c-9721-c0d7581d255d)
需要在依赖配置中加上 再创建镜像才行
![image](https://github.com/gradio-app/gradio/assets/61481593/f401acad-f844-4d22-858c-3c0a7bfcd0a9)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Traceback (most recent call last):
  File "/gpt/main.py", line 236, in <module>
    main()
  File "/gpt/main.py", line 192, in main
    from crazy_functions.live_audio.audio_io import RealtimeAudioDistribution
  File "/gpt/crazy_functions/live_audio/audio_io.py", line 2, in <module>
    from scipy import interpolate
ModuleNotFoundError: No module named 'scipy'

### System Info

```shell
Traceback (most recent call last):
  File "/gpt/main.py", line 236, in <module>
    main()
  File "/gpt/main.py", line 192, in main
    from crazy_functions.live_audio.audio_io import RealtimeAudioDistribution
  File "/gpt/crazy_functions/live_audio/audio_io.py", line 2, in <module>
    from scipy import interpolate
ModuleNotFoundError: No module named 'scipy'
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @ACoolOctober sorry we can't really parse this. Can you please create an issue in English so that our team is able to understand it? From the limited information I'm able to gather, this does not look like a problem with `gradio` so I'll close.
