### ISSUE TITLE
Optional image input not working in gradio 2.7.x. 

### ISSUE THREAD

**Issue by miquelferrarons** [gradio-app/gradio#495]
**Describe the bug**
'optional' argument to the Image input does not seem to have any effect. The interface doesn't work if no image is selected.

**To Reproduce**

1. Run this code snippet with gradio version 2.7.5.2 (latest at the moment of testing)
```
import gradio
gradio.Interface(
    fn=lambda text,image:f"text: {text}, image: {image}",
    inputs=[
        gradio.inputs.Textbox(default=None),  # text query
        gradio.inputs.Image(optional=True),   # image picker
    ],
    outputs=["text"]
).launch(share=False, server_name="localhost")
```
2. Try to launch the query without an image input
3. Click submit
4. Check the error in the console

**Screenshots**
![image](https://user-images.githubusercontent.com/5260456/151164953-5a26368c-ff4a-448f-bec3-b9005594b92f.png)

**Device information (please complete the following information):**
 - OS: [Ubuntu 20.04.1 LTS]
 - Browser [chrome, firefox]
 - Gradio version 2.5.7.2

**Additional context**

**Comment by miquelferrarons** [comment]
Seems to work on gradio version 2.6.0

**Comment by abidlabs** [comment]
Thanks @miquelferrarons! Confirming I can [reproduce this issue](https://colab.research.google.com/drive/16tybkmmUyBV0eGx4SvKLtLS53wEWjgRC?usp=sharing). Will look into this asap

**Comment by abidlabs** [comment]
This is now fixed on `master`. We'll push to pypi next week!

**Comment by miquelferrarons** [comment]
Great, thanks !
