### ISSUE TITLE
Minor error in the `langchain` sample code of `gr.ChatInterface`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#4955]
### Describe the bug

Maybe it would be better to change this
```python
from langchain.chat_models import ChatOpenAI
from langchain.schema import AIMessage, HumanMessage
import openai
import gradio as gr

openai.api_key = os.getenv("OPENAI_API_KEY")

llm = ChatOpenAI(temperature=1.0, model='gpt-3.5-turbo-0613')

def predict(message, history):
    history_langchain_format = []
    for human, ai in history:
        history_langchain_format.append(HumanMessage(content=human))
        history_langchain_format.append(AIMessage(content=ai))
    history_langchain_format.append(HumanMessage(content=message))
    gpt_response = chat(history_langchain_format)
    return gpt_response.content

gr.ChatInterface(predict).launch() 
```
to this
```python
import os

import gradio as gr
from langchain.chat_models import ChatOpenAI
from langchain.schema import AIMessage, HumanMessage

chat = ChatOpenAI(temperature=1.0,
                  model='gpt-3.5-turbo-0613',
                  openai_api_key=os.getenv('OPENAI_API_KEY'))


def predict(message, history):
    history_langchain_format = []
    for human, ai in history:
        history_langchain_format.append(HumanMessage(content=human))
        history_langchain_format.append(AIMessage(content=ai))
    history_langchain_format.append(HumanMessage(content=message))
    gpt_response = chat(history_langchain_format)
    return gpt_response.content


gr.ChatInterface(predict).launch(debug=True)
```

At least, `llm` should be changed to `chat` (or `chat` should be changed to `llm`).

Other than that, `ChatOpenAI` seems to check if `OPENAI_API_KEY` exists and `openai.api_key = os.getenv("OPENAI_API_KEY")` does nothing.
When `OPENAI_API_KEY` is provided, the app works without `openai.api_key = os.getenv("OPENAI_API_KEY")`.
And without setting `OPENAI_API_KEY`, even when doing `openai.api_key='sk-xxxxx'`, it doesn't work.
So, it seems we have to set `OPENAI_API_KEY` environment variable or pass `openai_api_key` to `ChatOpenAI`.

In my suggested change, actually, `openai_api_key=os.getenv('OPENAI_API_KEY')` is redundant, so it might be better to add comment to set the `OPENAI_API_KEY` environment variable instead.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

-

### System Info

```shell
-
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @hysts for catching this! Will update the docs
