### ISSUE TITLE
ChatInterface title does not look good in dark mode when embedded

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#4964]
### Describe the bug

<img width="883" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/d4451e45-80da-4b3f-bb2e-3e5e1bb4d9c5">

Visit: https://huggingface.co/blog/llama2 and set your system preferences to "dark"

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

-

### Screenshot

-

### Logs

```shell
-
```

### System Info

```shell
-
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
CSS conflict happening? The underlying frame doesn't have this problem: https://ysharma-explore-llamav2-with-tgi.hf.space/?__theme=dark

**Comment by freddyaboulton** [comment]
I think this is an issue only when embedding in the hugging face blog. Unclear if the issue is the CSS in the huggingface blog or if we could improve our embedded component.
