### ISSUE TITLE
Progress bar down on. 

### ISSUE THREAD

**Issue by Nehc** [gradio-app/gradio#4980]
### Describe the bug

In all the options that I tried, the progress is updated on ~50%, after which an error is displayed on the element itself, while there are no errors in the console and the process continues. I'm running the app in a docker container if that matters.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr
from time import sleep
from tqdm import trange 

def mirror(input_file,progress=gr.Progress(track_tqdm=True)):
    res = input_file.name
    for i in trange(100):
        sleep(.1)
    return res 

with gr.Blocks() as demo:
    with gr.Row():
        file = gr.File(file_types=['.pdf'], label="File")
    with gr.Row():
        test_btn = gr.Button("Test")
    
    test_btn.click(fn=mirror, inputs=[file], outputs=[file], api_name='test')

#demo.launch(debug=True)
if __name__ == "__main__":
    demo.queue(concurrency_count=1).launch(show_error=True,debug=True)
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/8426195/03955c1f-d63b-45d5-bf05-85d3a05bf842)

### Logs

```shell
That's the problem, that there are no errors - neither in the docker console, nor in the browser console. In colab, this code works without errors.
```

### System Info

```shell
Gradio last, FROM ubuntu:latest, Chrome, Edge, Opera...
```

### Severity

I can work around it

**Comment by magejosh** [comment]
Same bug, but different application. Running it on windows 10, with share=true
No errors in console, and the script functions as expected, except for the Error over the output. But in the outputs dir, the correct file is created, after that error in the UI pops up. 

Error
Unexpected token '<', "<html> <h"... is not valid JSON

Flashes on the ui as a kind of Popup flag on top right, then Same red error over output block.

**Comment by freddyaboulton** [comment]
I can't repro @magejosh 

![tqdm_repro](https://github.com/gradio-app/gradio/assets/41651716/16fbfc35-6dd3-41bb-8d81-6e714b3bc56d)

What version of tqdm are you using? Does the same error occur if you run the app outside of a gradio container?

**Comment by abidlabs** [comment]
Could not reproduce either on my end. Will close for now, please let us know if this is still an issue in the latest version of `gradio` and we can reopen. Thanks!
