### ISSUE TITLE
Minor type in chatbot docs

### ISSUE THREAD

**Issue by bsa0322** [gradio-app/gradio#4983]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
There is a typo in the source code of[ the chatbot tutorial document (section : Customizing your chatbot)](https://www.gradio.app/guides/creating-a-chatbot-fast#customizing-your-chatbot)

**Describe the solution you'd like**  
I think the docs code should be changed to the following code.
```python
import gradio as gr


def yes_man(message, history):
    if message.endswith("?"):
        return "Yes"
    else:
        return "Ask me anything!"


gr.ChatInterface(
    yes_man,
    chatbot=gr.Chatbot(height=300),
    textbox=gr.Textbox(placeholder="Ask me a yes or no question"),
    title="Yes Man",
    description="Ask Yes Man any question",
    theme="soft",
    examples=["Hello", "Am I cool?", "Are tomatoes vegetables?"],
    cache_examples=True,
    retry_btn=None,
    undo_btn="Delete Previous",
    clear_btn="Clear",
).launch()

```

**Additional context**  
None.

**Comment by abidlabs** [comment]
Thanks @bsa0322! Opened a PR here: https://github.com/gradio-app/gradio/pull/4984
