### ISSUE TITLE
How to set response time limit?

### ISSUE THREAD

**Issue by zioncheng** [gradio-app/gradio#50]
Hi, thanks for this fantastic work.
I noticed that there will be an error in the output if my wrap function spent too much time (like > 2mins).
Is there any way to loose the response time limitation?
(my wrap function like this : 
def POC_input(input1):
    time.sleep(135)
    check=True
    return [{"UnitTest":str(check)}, {"UnitTest_msg":'test'}]
Much thanks.

**Comment by dawoodkhan82** [comment]
@zioncheng When using the public link (share=True) the limit will be 60 seconds and we are going to be working on extending that soon. I'll update you on this issue when we do.
