### ISSUE TITLE
Issues related to the sketchpad component

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#501]
**Describe the bug**
The new sketchpad component is great and it is not plagued by some of the issues we had with the previous sketchpad (see #429). However, I experienced a few issues with it:

1. The "Clear" button underneath the inputs does not clear the sketchpad
2. The sketchpad cursor is very thin, which means the input that is submitted might not capture the input very well. (See this image which just outputs the input, and barely gets the digit). I suggest having a thicker cursor by default or allow users to vary the thickness.
3. Can we replace "undo" and "clear" button with symbols instead? It would be more consistent with our UI. For example, the symbols for the image input editor or the camera for capturing the webcam.

![image](https://user-images.githubusercontent.com/1778297/151445000-939bd96d-c484-49c8-8f72-de6fcf0b4b06.png)

**To Reproduce**
```
import gradio as gr
gr.Interface(lambda x:x, "sketchpad", "image").launch() 
```

**Comment by pngwn** [comment]
1 & 3 are simple fixes.

Curious about 2, why is the output text not the same as the input? Can you elaborate on what you mean by the cursor being thin? I don't quite follow.

**Comment by abidlabs** [comment]
Regarding #2, what happens is that the sketchpad input is preprocessed to a (by default) 28x28 array [1]. If the cursor is too thin, then the pixel value in any particular spot will be grayed out because it is the average of a thin black area amidst a white background. If the cursor was thicker, then the entire pixel in the grid of 28x28 would considered "black" and so it would be rendered properly.

**As a separate (and more important) issue**, it seems like the image that is sent back from the sketchpad input component now inverts things so that the "white" background is now returns as 0s while the black drawing is returned as 1s. This is the opposite of our previous behavior, which would return the white background as 1s while the black drawing would be returned as 0s. (This can be controlled by the `invert_colors` parameter). We should reverse the pixel values so that they do not break existing code.

[1] The reason 28x28 is chosen is because the most famous handwritten dataset in machine learning is MNIST, which consists of 28x28 images.

**Comment by pngwn** [comment]
Ah okay this makes sense. 

Regarding `invert_colors` i don't think that is being sent at all which is probably causing this issue (I didn't know it existed). Should be a quick fix.

**Comment by abidlabs** [comment]
You don't need to do anything in the frontend with regards to the `invert_colors` parameter. The image gets inverted in the backend. The frontend just needs to send the image back with 1s as the background and 0s as the sketch.

**Comment by pngwn** [comment]
As far as I'm aware we are sending back a raw png as binary data, i didn't know that anything had changed in this regard, which is why I'm a bit confused about this one.

**Comment by abidlabs** [comment]
Ahh interesting, I realize what the issue is. It used to be that the image would be returned as black-on-white. Now it's being returned as black-on-**transparent**. We use the `PIL` image module to convert the image to an RGB image, which renders transparent as black. I think the easiest way to fix this would be treat the background as white instead of transparent. Is that doable?

**Comment by pngwn** [comment]
Ah. Yeah I think should be simple enough.

**Comment by pngwn** [comment]
Would the sketch tool ever need to generate colour images for other purposes? I'm not sure what other applications it may have?

**Comment by abidlabs** [comment]
I have not seen any models that take color sketching as inputs.

**Comment by pngwn** [comment]
@abidlabs Should all be working now, I did test this prior to merging but would be good if you could double check. Especially the stroke thickness issue.
