### ISSUE TITLE
acquire parameter from url： demo.queue().launch vs demo.launch()

### ISSUE THREAD

**Issue by Arrkwen** [gradio-app/gradio#5015]
Thank you for this excellent project, which has greatly facilitate to display  the project. Unfortunately, I encountered the following problem. When I want to provide some additional parameters, such as "id_token", to the backend processing through the service’s URL, the behavior of demo.queue().launch() and demo.lunch() is inconsistent, which makes it difficult for me to use the queue method to obtain the parameter token. Here is an example of reproduction.

```
import gradio as gr
import re

def parseToken(url):
    matchObj = re.match( r'.*id_token=(.*)', url, re.M)
    if matchObj is None:
        raise gr.Error("token param is empty!")
    path =  matchObj.group(1)
    index = path.find('&')
    if index == -1:
        token = path
    else:
        token = path[:index]
    return token
    print("token:",token)

def reverse(text, request: gr.Request):
    token = parseToken(request.headers['referer'])
    auth(token)
    return text[::-1]

def auth(token):
    if token != access_key:
        raise gr.Error("invalid token!")

with gr.Blocks() as demo:
    button = gr.Button(value="Reverse")
    button.click(reverse, gr.Textbox(), gr.Textbox())

port = 18000
access_key="123"

demo.launch(server_port=port)
# demo.queue().launch(server_port=port)
```
firstly,  run the server and access"http://127.0.0.1:18000/?id_token=123",  than input numer "123", lastly, click "reverse".  it works well, but if you rerun the server after replace the "demo.launch(server_port=port)"  by " demo.queue().launch(server_port=port)".
```
# demo.launch(server_port=port)
demo.queue().launch(server_port=port)
```
an error happend, KeyError: 'referer', headers object no "referer" attribution. 

Can you modify the code to support  the headers parameter lists are consistent between them?

**Comment by abidlabs** [comment]
It is now possible to get the query parameters using the `query_params` attribute of `gr.Request`, thanks to #5681
