### ISSUE TITLE
Llm leaderboard perf issues 

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#5018]
### Describe the bug

creating an issue so I don’t forget. 

https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard/discussions/123#64bff947b878d31de52fc1b0

Pretty sure I know what the worst offenders are but needs investigating regardless. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Asd

### System Info

```shell
Spaces
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Much better now, thanks @pngwn!
