### ISSUE TITLE
Issue related to input image editor

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#502]
**Describe the bug**
It looks like our Toast UI image editor is completely broken:

![image](https://user-images.githubusercontent.com/1778297/151446006-b63b594f-0dd4-45ed-937f-ff1b7d773878.png)

**To Reproduce**
import gradio as gr

gr.Interface(lambda x:x, "image", "image").launch()

**Comment by pngwn** [comment]
I've had some difficulties reproducing this, it isn't present running the demos again dev. I'll test the prod output later and see if I can figure this one out.

**Comment by pngwn** [comment]
I think this is probably resolved with the new `ui` dir + build tools. We should focus making that the published version rather than fixing this in `frontend` when it will be discarded shortly.

**Comment by abidlabs** [comment]
Yup it looks like it's fixed, thanks!
