### ISSUE TITLE
Whether to allow customization of the landing page, or to override the number of controls and registration functions on the landing page

### ISSUE THREAD

**Issue by Kilig947** [gradio-app/gradio#5020]
- [ - ] I have searched to see if a similar issue exists.

**Is your feature request related to an issue? Please describe. 
self.demo.queue(concurrency_count=CONCURRENT_COUNT).launch( After enabling auth, the login page only receives username and password two parameters, because the company requires to send a request to log in successfully need to verify again Google Authenticato

**Describe the solution you want  
Rewrite the controls and the number of parameters received on the Login page, add a CAPTCHA input box, or use the Allow customization of the Login page.

**Comment by abidlabs** [comment]
Hi @Kilig947 this is out-of-scope for our humble login page. However, you could create a custom login page and mount it, along with Gradio, in a larger FastAPI page. There's discussion of that here: https://github.com/gradio-app/gradio/issues/2790
