### ISSUE TITLE
distinguish between different user for public app

### ISSUE THREAD

**Issue by eastonsuo** [gradio-app/gradio#5021]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
 Is there a way for distingushing different users when a gradio app is opened for public

**Describe the solution you'd like**  

Is it possible for every component to get cookie from frontend, and can be accessed from gradio program?
something like:
```
def hello(text, cookie):
    use_cookie()
    return text
```

**Comment by abidlabs** [comment]
Hi @eastonsuo you can access the network request directly, as described here: https://www.gradio.app/guides/sharing-your-app#accessing-the-network-request-directly

From the network request, you can get the IP address or cookies -- does this work?

**Comment by abidlabs** [comment]
Closing for lack of follow up. We can reopen if this does not suffice.
