### ISSUE TITLE
Error "Server disconnected without sending a response"

### ISSUE THREAD

**Issue by DanielleChasonAporia** [gradio-app/gradio#5022]
### Describe the bug

I have a gradio application. 
Everything is working when I'm running the application locally.
I used **google cloud** in order to implement Identity-Aware Proxy (**IAP**) which is a security mechanism used to control access to web applications. In order to that I had to define a load balancer that have a domain. 
If I'm using the domain to get access to my application, whenever I try to run something I get the following error:
![image](https://github.com/gradio-app/gradio/assets/136222727/4c24804d-51f3-4214-95f8-b26be247c97d)

If someone encountered this error before and knows why it happens, I'll be happy to hear.
Thanks!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

I used this guide: https://cloud.google.com/load-balancing/docs/https/setting-up-reg-ext-https-lb

### System Info

```shell
Gradio version: 3.34.0
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Did you enable the queue @DanielleChasonAporia ?

**Comment by DanielleChasonAporia** [comment]
@freddyaboulton yes

**Comment by abidlabs** [comment]
Hi @DanielleChasonAporia this is going to be pretty tricky to debug because of the specific cloud infra involved. Can you try deploying a regular `FastAPI` app and see if it works?

**Comment by abidlabs** [comment]
Closing for lack of follow up. We can reopen this potentially if we get more details to allow us to debug this.
