### ISSUE TITLE
Create an executable file so users can just install the application to use it.

### ISSUE THREAD

**Issue by CreaperLost** [gradio-app/gradio#5026]
Hi,

I am looking into creating a DEMO, I would love if we could build the gradio app into an executable file that we could potentially give to users to try.

So instead of connecting to an ENDPOINT, they install the gradio built application and run from there.

This should be good especially if we want to allow non-experts to use it on local computers.

**Comment by abidlabs** [comment]
I think this would be quite valuable and would solve #2257 as well. Let me close this issue and move the discussion there @CreaperLost
