### ISSUE TITLE
gr.Blocks 读取外部css文件失败

### ISSUE THREAD

**Issue by qifuxiao** [gradio-app/gradio#5027]
### Describe the bug

当使用外部css文件修改展示样式的时候，查看官方文档：https://www.gradio.app/guides/custom-CSS-and-JS  说明如下：
If you’d like to reference external files in your css, preface the file path (which can be a relative or absolute path) with , for example:"file="

with gr.Blocks(css='file=example/style.css') as demo:

css文件未能成功加载，查看源码：
if css is not None and os.path.exists(css):
            
            with open(css) as css_file:
                self.css = css_file.read()
当判断文件是否存在时，由于带有"file=" 导致返回False，没能读取css文件

直接删掉file=  还是报错：
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 11:
illegal multibyte sequence

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

解决方案：
自己手动修改了源码：
if css is not None and os.path.exists(css):
            with open(css, 'r', encoding='utf-8') as css_file:
                self.css = css_file.read()
            # with open(css) as css_file:
            #     self.css = css_file.read()
        else:
            self.css = css

### System Info

```shell
gradio environment
Gradio Environment Information:
Operating System:  Windows


gradio version:  3.38.0

gradio Dependencies:
  aiofiles: 23.1.0
  aiohttp: 3.8.4
  altair: 5.0.1
  fastapi: 0.100.0
  ffmpy: 0.3.1
  gradio-client: 0.2.10
  httpx: 0.24.1
  huggingface-hub: 0.14.1
  jinja2: 3.1.2
  markdown-it-py: 2.2.0
  markupsafe: 2.1.1
  matplotlib: 3.6.2
  mdit-py-plugins: 0.3.3
  numpy: 1.23.5
  orjson: 3.9.2
  packaging: 23.0
  pandas: 1.5.2
  pillow: 8.4.0
  pydantic: 2.0.3
  pydub: 0.25.1
  python-multipart: 0.0.6
  pyyaml: 6.0
  requests: 2.24.0
  semantic-version: 2.10.0
  typing-extensions: 4.7.1
  uvicorn: 0.23.1
  websockets: 11.0.3


gradio_client version:  0.2.10

gradio_client Dependencies:
  fsspec: 2023.5.0
  httpx: 0.24.1
  huggingface-hub: 0.14.1
  packaging: 23.0
  requests: 2.24.0
  typing-extensions: 4.7.1
  websockets: 11.0.3
```

### Severity

I can work around it

**Comment by aliabid94** [comment]
Can you post your gradio file and your CSS file? The error seems to imply that the CSS file is not encoded like a standard text file.

**Comment by qifuxiao** [comment]
有两个问题：
第一个问题，外部CSS文件加载问题：with gr.Blocks(css='file=example/style.css') as demo:这里的css参数是传“file="+文件path，还是直接传文件path？如果传“file="+文件path，源码中判断文件是否存在会返回False，导致无法加载CSS文件。但是当我在端口服务中查询文件的时候，又必须使用“file="+文件path才可以查看到文件，如截图：
![image](https://github.com/gradio-app/gradio/assets/51008934/ceb29e43-3d8e-46a3-9bb9-e6b80adb27f9)
![image](https://github.com/gradio-app/gradio/assets/51008934/d7606c7f-46cc-4384-aff1-532b19ad3f05)

第二个问题，当我用我自己的方式加载了css文件，但是读取css内容的时候，出现了encoded的问题，我对源码做了上述修改成功运行，以下是我的文件结构和内容：
![image](https://github.com/gradio-app/gradio/assets/51008934/305b6b1d-98f6-43c1-be73-7ae3edb3c3d6)


`/* 添加自定义样式到 gradio.AnnotatedImage 组件 */
.gr-animated-image {
    object-fit: cover;
    border: 1px solid red;
    box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
}
.styled-text {
    font-size: 18px; /* 修改字体大小为18像素 */
    background-color: #f0f0f0; /* 修改背景色为浅灰色 */
    padding: 10px; /* 可选：添加内边距以增加文本与容器边缘的间隔 */
}
#warning {background-color: #FFCCCB} 
.feedback textarea {font-size: 24px !important}`

![image](https://github.com/gradio-app/gradio/assets/51008934/588f586f-0a06-423d-97a3-2c08e9c3a927)

**Comment by qifuxiao** [comment]
我已经解决了这个问题，问题一：当我在window下启动服务的时候会报错找不到文件，但是当我放在Linux运行是正常的；问题二：我的css文件中包含中文注释，导致encoding问题。
非常抱歉，给你造成了麻烦，这不是一个bug，是我个人问题。
谢谢

**Comment by qifuxiao** [comment]
这不是一个bug
