### ISSUE TITLE
Gradio Highlittext method not working

### ISSUE THREAD

**Issue by rajeunoia** [gradio-app/gradio#5029]
### Describe the bug

I am using, 
gradio==3.39.0
gradio_client==0.3.0
i get following error , 
gradio with ner events fails with this error, highlighted_text.py", line 162, in postprocess (text[entity[“start”] : entity[“end”]], entity[“entity”]) keyerror: ‘entity’

I think the issue is with the key "entity" where output of the model is giving "entity_group"

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Code that i have tried, which calls highlight in output
```
demo = gr.Interface(fn=ner,
                    inputs=[gr.Textbox(label="Text to find entities", lines=2)],
                    outputs=["highlight"],
                    title="NER with dslim/bert-base-NER",
                    description="Find entities using the `dslim/bert-base-NER` model under the hood!",
                    allow_flagging="never",
                    #Here we introduce a new tag, examples, easy to use examples for your application
                    examples=["My name is Andrew and I live in California", "My name is Poli and work at HuggingFace"])
demo.launch(share=True, server_port=7862)
```

Code in 162 line of highlighted_text.py
```
list_format.append(
                        (text[entity["start"] : entity["end"]], entity["entity"])
                    )
```

### Logs

```shell
gradio with ner events fails with this error, highlighted_text.py", line 162, in postprocess (text[entity[“start”] : entity[“end”]], entity[“entity”]) keyerror: ‘entity’
not the complete error log
```

### System Info

```shell
MacBook Pro , M1 chip
```

### Severity

I can work around it

**Comment by rajeunoia** [comment]
My code is from the latest short course on Deeplearning.ai

def get_completion(inputs,
parameters=None,ENDPOINT_URL=HF_API_SUMMARY_BASE):
    headers = {
      "Authorization": f"Bearer {hf_api_key}",
      "Content-Type": "application/json"
    }
    data = { "inputs": inputs }
    if parameters is not None:
        data.update({"parameters": parameters})
    response = requests.request("POST",
                                ENDPOINT_URL, headers=headers,
                                data=json.dumps(data)
                               )
    return json.loads(response.content.decode("utf-8"))

import gradio as gr
API_URL = "https://api-inference.huggingface.co/models/dslim/bert-base-NER"
text = "My name is Andrew, I'm building DeepLearningAI and I live in
California"
get_completion(text, parameters=None, ENDPOINT_URL= API_URL)

Output:

[{'entity_group': 'PER',
  'score': 0.9990624785423279,
  'word': 'Andrew',
  'start': 11,
  'end': 17},
 {'entity_group': 'ORG',
  'score': 0.896050214767456,
  'word': 'DeepLearningAI',
  'start': 32,
  'end': 46},
 {'entity_group': 'LOC',
  'score': 0.999692440032959,
  'word': 'California',
  'start': 61,
  'end': 71}]

**Comment by abidlabs** [comment]
Ok I can reproduce this with the slightly modified code below. It looks like the Inference API returns `entity_group` instead of `entity`:

```py
import requests, json

def get_completion(inputs, parameters, ENDPOINT_URL):
    data = { "inputs": inputs }
    if parameters is not None:
        data.update({"parameters": parameters})
    response = requests.request("POST",
                                ENDPOINT_URL, 
                                data=json.dumps(data)
                               )
    return json.loads(response.content.decode("utf-8"))

API_URL = "https://api-inference.huggingface.co/models/dslim/bert-base-NER"
text = "My name is Andrew, I'm building DeepLearningAI and I live in California"
get_completion(text, parameters=None, ENDPOINT_URL= API_URL)
```
