### ISSUE TITLE
Degraded microphone input on different devices

### ISSUE THREAD

**Issue by Charlottecuc** [gradio-app/gradio#503]
**Describe the bug**
When testing on iPhone, the microphone input can reach the original device sample rate (not degraded).
When testing on Android devices and laptops, the sample rate of the microphone input is usually 16k hertz, and sometimes 8k hertz (which is largely degraded, because if you test the micrphone with other recorder Apps on these devices,  the sample rate can reach 44k hertz).
Question:
How to reach the original device sample rate when testing on Android devices?

**To Reproduce**
1. Get the local link, and open it on an Android phone (on a local network)
2. Start recording
3. Check the sample rate of input audio file

**Device information (please complete the following information):**
 - OS: Android
 - Browser: Chrome
 - Gradio version:2.7.0

**Comment by abidlabs** [comment]
Hmm very strange. @dawoodkhan82 @aliabid94 is this something that we can fix on Gradio's side or is this a browser issue?

**Comment by abidlabs** [comment]
Hi @Charlottecuc if you don't mind, we'll close this issue as it doesn't seem to be something related to Gradio. 

If you do find that it is Gradio-related, feel free to reopen. Thanks!
