### ISSUE TITLE
Feature Request: Allow Passing Token via URL Parameter

### ISSUE THREAD

**Issue by WangShixian1** [gradio-app/gradio#5031]
Feature Request: Allow Passing Token via URL Parameter

Problem Description:
Currently, I'm facing an issue when sharing demos with the Gradio app using the URL parameter to pass a token (?token=xxx) to the server. The token server cannot receive the token when it's passed as a parameter through the URL.
such as <gradio-app src="https://abidlabs-pytorch-image-classifier.hf.space/?id_token=xxx"></gradio-app>

Proposed Solution:
I would like to request a feature that enables the server to receive the token when it's passed via the URL parameter. For example, I expect the server to handle the <gradio-app src="https://abidlabs-pytorch-image-classifier.hf.space/?id_token=xxx"></gradio-app> and successfully retrieve the token value.

Additional Context:
This feature will significantly enhance the usability of the Gradio app and improve the overall user experience. It would be great to have a solution to this issue as soon as possible. Thank you for considering this enhancement!

**Comment by abidlabs** [comment]
Hi @WangShixian1 it sounds like this is the same issue as: https://github.com/gradio-app/gradio/issues/5015

I'll go ahead and close this as it is a duplicate, but feel free to respond if I've missed something.

**Comment by WangShixian1** [comment]
hi@abidlabs  thanks your advice .but it not work .i use <grodio-app></gradio-app> show demo i want try src='https://qweqwe.com/?id_token=xxx' but in python i can't get the token parmes

**Comment by WangShixian1** [comment]
hi@abidlabs  thanks your advice .but it not work .i use <grodio-app></gradio-app> show demo i want try src='https://qweqwe.com/?id_token=xxx' but in python i can't get the token parmes

**Comment by WangShixian1** [comment]
hi@abidlabs  thanks your advice .but it not work .i use \<grodio-app></gradio-app> show demo i want try src='https://qweqwe.com/?id_token=xxx' but in python i can't get the token parmes

**Comment by WangShixian1** [comment]
hi@abidlabs  thanks your advice .but it not work .i use <grodio-app></gradio-app> show demo i want try src='https://qweqwe.com/?id_token=xxx' but in python i can't get the token parmes
![image](https://github.com/gradio-app/gradio/assets/109021486/1881568d-19fc-46b1-a287-154b6f524dca)
