### ISSUE TITLE
Event Listeners for Tabs/Accordians/Examples

### ISSUE THREAD

**Issue by rlee900** [gradio-app/gradio#5036]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I have a Gradio App mounted using FastAPI and have Google authentication to protect the endpoint. The Gradio App answers user questions. I would like to be able to display historical questions stored in a database that were previously asked by the user without having to click a button to generate the history. I thought of using tabs or accordians to display this info or having examples generated from the historical data. However, there is no event listener for tabs/accordians/examples.

**Describe the solution you'd like**  
Event listeners for tabs, accordians, and examples so that a function can be called when a tab/accordian is clicked. For examples, I would like a function to be called on load to generate user customized examples. 

**Additional context**  
N/A

**Comment by abidlabs** [comment]
Hi @rlee900, the `gr.Tab()` supports a `.select()` event that gets triggered when it is selected. 

The `gr.Examples()` is actually just a wrapper over a `gr.Dataset()`, and the underlying dataset can be accessed using the example's `.dataset`. And `gr.Dataset()` supports a `.click()` event. 

Does this work for you?

**Comment by abidlabs** [comment]
Closing for lack of follow up. We can reopen if this does not suffice.

**Comment by rlee900** [comment]
> Hi @rlee900, the `gr.Tab()` supports a `.select()` event that gets triggered when it is selected.
> 
> The `gr.Examples()` is actually just a wrapper over a `gr.Dataset()`, and the underlying dataset can be accessed using the example's `.dataset`. And `gr.Dataset()` supports a `.click()` event.
> 
> Does this work for you?

Yes, that works for me. Thanks!

**Comment by JackismyShephard** [comment]
I could really use an event listener for accordions. Is that possible?
