### ISSUE TITLE
How to dynamically  create Tabs?

### ISSUE THREAD

**Issue by thisjam** [gradio-app/gradio#5040]
- [x] I have searched to see if a similar issue already exists.

i want to click a button then create a Tabs on the page.

**Comment by abidlabs** [comment]
Hi @thisjam this is not currently supported. 

We're currently discussing dynamic components in https://github.com/gradio-app/gradio/issues/4689. Can you please describe your use case a bit in that issue so that we can try to support it?

**Comment by abidlabs** [comment]
I'll close this issue in the meantime

**Comment by thisjam** [comment]
> Hi @thisjam this is not currently supported.
> 
> We're currently discussing dynamic components in #4689. Can you please describe your use case a bit in that issue so that we can try to support it?

When will we be able to manipulate DOM nodes, add elements, delete elements, and immediately display them on the page like JavaScript?

**Comment by woutervanranst** [comment]
this comes close https://www.gradio.app/guides/controlling-layout#variable-number-of-outputs
