### ISSUE TITLE
Interpretation functionality does not work when passing second argument in inputs

### ISSUE THREAD

**Issue by arielgamino** [gradio-app/gradio#505]
**Describe the bug**
I have created an interpretation function and I am testing if it's something we can use. When I pass a second argument to the inputs in gr.Interface, it does not work any longer.  If one of the second arguments is a class like gr.inputs.CheckboxGroup, when the interpret button gets clicked, the page just goes blank.

**To Reproduce**
1. Passing a "checkbox" as second argument (see first screenshot):

``
iface = gr.Interface(fn=greet,
                     inputs=[
                        gr.inputs.Textbox(lines=10, placeholder="Text or URL Here..."),
                        "checkbox"                         
                     ],
                     outputs="text", interpretation=interpret_simple)
``

2. Passing an object, as second argument (see second screenshot):

``
iface = gr.Interface(fn=greet,
                     inputs=[
                        gr.inputs.Textbox(lines=10, placeholder="Text or URL Here..."),
                        gr.inputs.CheckboxGroup(["Option1", "Option2", "Option3"], default=["Option1"]),
                     ],
                     outputs="text", interpretation=interpret_simple)
iface.launch()
``

**Screenshots**
1. Calling gr.Interface with one argument in inputs (it works): 
![Works](https://raw.githubusercontent.com/arielgamino/githubpages/93b2b7c5285ad7eb2ce50680f6a55f719057506f/gradio_works.png)
2. Calling gr.Interface with two arguments in inputs (it comes back but does not highlight), second argument "checkbox":
![Does not work](https://raw.githubusercontent.com/arielgamino/githubpages/main/gradio_interpret_does_not_work.png)

3. Calling gr.Interface with two arguments in inputs (page is blank), second argument gr.inputs.CheckboxGroup:
![Does not work](https://github.com/arielgamino/githubpages/raw/main/gradio_blank.png)

**Device information (please complete the following information):**
 - Google Collab or jupyter notebook (Mac)

**Additional context**
The function that is called it's a pretty simple one to test the interpretation. Here example of the greet and interpret_simple function:

def greet(name, some_value):
    """Dummy function to pass to gradio"""
    return "Hello " + name + "!!"

def interpret_simple(text, some_value):
    """Interpretation function - label some words"""    
    group1_words = ['myocarditis', 'hyperuricemia']
    group2_words = ['sepsis']
    interpretation = []
    for word in re.split('( )', text):
        score = 0
        token = word.lower()
        if (token in group1_words):
            score = 1          
        elif (token in group2_words):
            score = -0.5
        interpretation.append((word, score))
    return interpretation

**Comment by abidlabs** [comment]
Interesting, I'll take a look. Thanks @arielgamino for creating this issue

**Comment by abidlabs** [comment]
Hi @arielgamino, if you have multiple inputs, Gradio expects the custom interpretation function to return an interpretation for each input. You can return `None` to skip a particular input.

So the fix here would be to replace the last line of `def interpret_simple(text, some_value):` with:
`return interpretation, None`

This works for me on Colab:

![image](https://user-images.githubusercontent.com/1778297/152555027-b356a47d-b8b1-4a4d-8f97-f437af95c5be.png)
