### ISSUE TITLE
question

### ISSUE THREAD

**Issue by langlibaipiao** [gradio-app/gradio#5051]
I ran a dialog model locally that uses gradio, which is displayed on the web page, and now I want to integrate it into the front end page. Is there any way to do that

**Comment by abidlabs** [comment]
Hi @langlibaipiao, for general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
