### ISSUE TITLE
Sweep: strip username before login and add a unit test within `test_post_login`

### ISSUE THREAD

**Issue by leolaf** [gradio-app/gradio#5056]
- [x] I have searched to see if a similar issue already exists.

It seems that spaces are kept at the beginning and at the end of the username's Textbox on login page.
It is more of a user-end problem when happening but since most sites work like this I thought it would be great to implement it in gradio.

Would it be possible to strip the username in the login route in the script `gradio/routes.py` ?
 
Sorry if it is not considered a feature request, but i didn't knew if this behavior was a bug or on purpose.

Thank you !

**Comment by wwzeng1** [comment]
@abidlabs I'm going to create a separate issue, we currently read all of the non-bot issue comments so this may be noisy. Thanks for trying Sweep!

**Comment by wwzeng1** [comment]
https://github.com/gradio-app/gradio/pull/5104/files Here's the PR!

**Comment by abidlabs** [comment]
Closed by #5104
