### ISSUE TITLE
SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by phosseini** [gradio-app/gradio#506]
**Describe the bug**
I'm simply running the example code in the readme. I properly installed gradio and I see the following error:
```
Traceback (most recent call last):
  File "/Users/my_username/PycharmProjects/my_project/src/home.py", line 1, in <module>
    import gradio as gr
  File "/Users/my_username/anaconda3/envs/my_env/lib/python3.6/site-packages/gradio/__init__.py", line 3, in <module>
    from gradio.app import get_state, set_state
  File "/Users/my_username/anaconda3/envs/my_env/lib/python3.6/site-packages/gradio/app.py", line 3
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**To Reproduce**
1. Install gradio using `pip install gradio`
2. Run the first example in readme

**Device information (please complete the following information):**
 - OS: macOS Monterey 12.1
 - Gradio version: 2.7.5.2

**Comment by abidlabs** [comment]
Which version of Python are you using? Gradio requires `Python 3.7+`.

https://stackoverflow.com/questions/52889746/cant-import-annotations-from-future

**Comment by phosseini** [comment]
@abidlabs Thanks, I had python 3.6 installed, just upgraded the python and now it's working.

**Comment by abidlabs** [comment]
Great. I've added system requirements to the README. Thanks for letting us know!

**Comment by bilalghanem** [comment]
I had the same error, and I downgraded Gradio to `2.5.2` version and it worked.

**Comment by goclm** [comment]
I had python 3.9.0 installed,The same error occurred.

import gradio.components as_conmponents
File "D:\yololkaiyuan\原开放项目-开源2\dist lmain\gradiocomponentsl_init_.py', 1ine 1, in <module>from gradio.components.annotated_ image import AnnotatedImage
Fiie "D:lyolo kaiyuan\原开放项目-开源2\dist (main lgradio components lannotated_image. y"'，1ine 3from_future_import annotations
SyntaxError: future feature annotations is not defined
