### ISSUE TITLE
Enter key along with submit button 

### ISSUE THREAD

**Issue by kartiksonaghela** [gradio-app/gradio#5065]
block = gr.Blocks(css="footer {visibility: hidden}")

with block:
    gr.Markdown("""<h1><center>Question GPT</center></h1>
    """)
    chatbot = gr.Chatbot()#.style(width=600)
    message = gr.Textbox(label='Query')#.style(width=600)
    state = gr.State()
    submit = gr.Button("Submit")
    submit.click(chatgpt_clone,inputs=[message,state], outputs=[chatbot,state])
    submit.click(lambda x: gr.update(value=''),[state], [message], queue=False)
block.launch(debug = True)

I have submit button which on click performs a task i want the same functionality with enter key (from keyboard) that a submit button does and also after using enter key i want my text box to get clear. Is it possible to do in gradio.                                                   
Thankyou

**Comment by freddyaboulton** [comment]
Yes it is possible @kartiksonaghela 

You can use `textbox.submit` to trigger the event when the enter key is pressed: https://www.gradio.app/docs/textbox

You can use `.then` to clear the textbox subsequently. https://www.gradio.app/guides/blocks-and-event-listeners#running-events-consecutively

For general questions like this, it's better to ask in [discord](https://discord.gg/hugging-face-879548962464493619) (#gradio-questions channel) or github discussions.

**Comment by jz746** [comment]
hhhh
hhh

**Comment by jz746** [comment]
hi
