### ISSUE TITLE
when use yield, The output time interval must be <=10s, otherwise stdout: 'AsyncRequest' object has no attribute '_json_response_data'

### ISSUE THREAD

**Issue by wrydeveloper** [gradio-app/gradio#5069]
### Describe the bug

eq:
```python
def handle1(text):
    yield "first output"
    time.sleep(9)
    print("after 9s, print it")
    yield "first output and second output"
    time.sleep(10)
    print("after 10s, print it")
    yield "first output and second output and third output"
    print("last output")


if __name__ == "__main__":
    demo = gr.Interface(fn=handle1, inputs='text', outputs='text')
    demo.queue()
    demo.launch(server_name='0.0.0.0', server_port=7864)
``` 

than we run,

web screenshot:
<img width="1649" alt="image" src="https://github.com/gradio-app/gradio/assets/34156951/ca35ad2d-b87c-4924-9c15-93a402a9452a">

ok, only "first output and second output" but not "first output and second output and third output"

terminal screenshot:
![image](https://github.com/gradio-app/gradio/assets/34156951/ed62de5c-5806-4d10-9088-a85a80405807)

'AsyncRequest' object has no attribute '_json_response_data'
look like a expection, but without stack info.
and miss "last output".

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
def handle1(text):
    yield "first output"
    time.sleep(9)
    print("after 9s, print it")
    yield "first output and second output"
    time.sleep(10)
    print("after 10s, print it")
    yield "first output and second output and third output"
    print("last output")


if __name__ == "__main__":
    demo = gr.Interface(fn=handle1, inputs='text', outputs='text')
    demo.queue()
    demo.launch(server_name='0.0.0.0', server_port=7864)
``` 

### Logs

```shell
Running on local URL:  http://0.0.0.0:7864

To create a public link, set `share=True` in `launch()`.
after 9s, print it
'AsyncRequest' object has no attribute '_json_response_data'
after 10s, print it
```

### System Info

```shell
gradio==3.39.0
```

### Severity

I can work around it

**Comment by wrydeveloper** [comment]
sos, my leader will kill me

**Comment by wrydeveloper** [comment]
@freddyaboulton please

**Comment by wrydeveloper** [comment]
i try again in Ubuntu 20.04, amazing, it work, 
<img width="1659" alt="image" src="https://github.com/gradio-app/gradio/assets/34156951/f420dba1-9618-4828-9139-e184e27c938f">
![image](https://github.com/gradio-app/gradio/assets/34156951/02ae45fc-fb3b-4b1b-b3b0-ac60344202b6)

i guess.... mac and gradio is not a good choice...

**Comment by freddyaboulton** [comment]
I use a Mac so that’s not true :thinking:
