### ISSUE TITLE
Add .then, .success to component docs

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#5072]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
The `.then`,  and `.success` events are only listed in the guides but not in the docs. We should list them in the docs.

**Describe the solution you'd like**  
I think we could just add them to the `@document` decorator so that they show up along all other the events for the components.

**Additional context**

**Comment by freddyaboulton** [comment]
If you go to any event on the docs page, there will be a table with all the supported events.

https://www.gradio.app/docs/audio

However, `then` and `success` are not listed even though there are valid events for all components. Not sure the right technical approach but maybe @aliabd can explain.

**Comment by sabir-sayyed** [comment]
This table..? if yes please provide the link where i can get more info on .then and .success to add that into the table

<img width="613" alt="image" src="https://github.com/gradio-app/gradio/assets/137613597/f721a4c4-8da7-4b0d-851c-73ecec2bc1da">

**Comment by abidlabs** [comment]
It would be good to include the forthcoming `.on()` in the docs as well. Quoting from #5639:

> By the way, it would be good to include .on() in the docs, perhaps along with .then() and .success() (we can tackle this in https://github.com/gradio-app/gradio/issues/5072). In particular, the second usage example where the trigger is the change event of the input components could be not obvious (though I do think its handy).
