### ISSUE TITLE
Able to alter the authentication page.

### ISSUE THREAD

**Issue by rukeshpaudel** [gradio-app/gradio#5073]
- I have searched to see if a similar issue already exists. I found none.

**Solution Proposal**  
A way to alter the contents of the authentication page. 
We could also add email or other fields in the authentication page.

**Comment by abidlabs** [comment]
Hi @rukeshpaudel I believe this is out-of-scope for our humble login page. However, you could create a custom login page and mount it, along with Gradio, in a larger FastAPI page. There's discussion of that here: https://github.com/gradio-app/gradio/issues/2790

**Comment by abidlabs** [comment]
Yeah will close this for now, as I feel this is out of scope for `gradio`. Thanks
