### ISSUE TITLE
The chatbot component automatically converts <iframe> code to <span class="svelte-15hifvz"></span>.

### ISSUE THREAD

**Issue by Kilig947** [gradio-app/gradio#5078]
### Describe the bug

After upgrading to the new version, it is not possible to inline a web page in the Chatbot component dialog, I was able to display it normally in version 3.32.0

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

将下面的HTML代码提交给Chatbot组件 <iframe width="100%" height="500px" frameborder="0" src="{html_file}"></iframe>

### Screenshot

new version
![image](https://github.com/gradio-app/gradio/assets/46100050/2a8b50c5-7ce0-4a84-9054-fe3160a453a1)

old version
![image](https://github.com/gradio-app/gradio/assets/46100050/4a383399-d8c2-4460-808b-c26544fc353f)

### System Info

```shell
> pip list | grep gradio
gradio                   3.39.0

MacBook M1
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @Kilig947 can you please provide a self-contained example with code that we can use to reproduce this issue?

**Comment by Kilig947** [comment]
> 嗨，您能否提供一个包含代码的独立示例，我们可以用来重现此问题？

`
with gr.Blocks() as demo:   # 绘制一个块对象，在此基础上可以使用Row、Column、Tab、Box等等布局元素
    gr.Markdown(f"<h1 align=\"center\">我是Bolcks</h1>")
    with gr.Row():
        with gr.Column(scale=100):    # 组件绘制在布局元素下，则会根据布局元素的规定展示
            gr.Markdown('# 这里是列1')
            with gr.Tab(label='12312312'):
                chatbot = gr.Chatbot()
                status = gr.Markdown()

        with gr.Column(scale=50):
            gr.Markdown('# 这里是列2')
            i_say = gr.Textbox()
            submit = gr.Button(value='一次性对话', variant='primary')
            submit2 = gr.Button(value='流式对话', variant='stop')
            Noo = gr.Button(value='停止事件任务')

    # 这个函数可以存任何地方，任何python文件，只要注册函数能正常引用即可
    def respond_2(say, chat_bot):
        import random
        # 从预定义的回复中随机选择一个
        bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
        # 将用户的输入和机器人的回复添加到聊天记录中
        chat_bot.append((say, bot_message))
        return "我要开始胡说了", chat_bot

    # 注册函数，只能在Bolock上下文中注册
    # fn=要注册的函数， input=组件传输数据给函数接收的数据， outputs=接收函数处理后返回数据的组件
    cancel_handles = []
    cancel_handles2 = []
    ff = submit.click(fn=respond_2, inputs=[i_say, chatbot], outputs=[status, chatbot])

demo.queue(concurrency_count=100).launch(server_port=7699)
`
In gradio 3.93.0 version you can copy <iframe width="100%" height="500px" frameborder="0 " src="http://google.com"></iframe> into the TextBox input box, and then click "", you can find that the Use does not display the inline Page
Go back to version 3.32.0, it will display google's inline web page normally in use.

**Comment by Kilig947** [comment]
> > 嗨，您能否提供一个包含代码的独立示例，我们可以用来重现此问题？
> 
> ```
> with gr.Blocks() as demo:   # 绘制一个块对象，在此基础上可以使用Row、Column、Tab、Box等等布局元素
>     gr.Markdown(f"<h1 align=\"center\">我是Bolcks</h1>")
>     with gr.Row():
>         with gr.Column(scale=100):    # 组件绘制在布局元素下，则会根据布局元素的规定展示
>             gr.Markdown('# 这里是列1')
>             with gr.Tab(label='12312312'):
>                 chatbot = gr.Chatbot()
>                 status = gr.Markdown()
> 
>         with gr.Column(scale=50):
>             gr.Markdown('# 这里是列2')
>             i_say = gr.Textbox()
>             submit = gr.Button(value='一次性对话', variant='primary')
>             submit2 = gr.Button(value='流式对话', variant='stop')
>             Noo = gr.Button(value='停止事件任务')
> 
>     # 这个函数可以存任何地方，任何python文件，只要注册函数能正常引用即可
>     def respond_2(say, chat_bot):
>         import random
>         # 从预定义的回复中随机选择一个
>         bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
>         # 将用户的输入和机器人的回复添加到聊天记录中
>         chat_bot.append((say, bot_message))
>         return "我要开始胡说了", chat_bot
> 
>     # 注册函数，只能在Bolock上下文中注册
>     # fn=要注册的函数， input=组件传输数据给函数接收的数据， outputs=接收函数处理后返回数据的组件
>     cancel_handles = []
>     cancel_handles2 = []
>     ff = submit.click(fn=respond_2, inputs=[i_say, chatbot], outputs=[status, chatbot])
> 
> demo.queue(concurrency_count=100).launch(server_port=7699)
> ```
> 
> In gradio 3.93.0 version you can copy <iframe width="100%" height="500px" frameborder="0 " src="http://google.com"></iframe> into the TextBox input box, and then click "", you can find that the Use does not display the inline Page Go back to version 3.32.0, it will display google's inline web page normally in use.

Additionally, in version 3.32.0, the gr.Chatbot.postprocess = format_io submitted to chatbot was rewritten by me,so if needed, add the following code
```
import markdown
gr.Chatbot.postprocess = format_io
def format_io(self, y):
    """
    将输入和输出解析为HTML格式
    """
    if y is None or y == []:
        return []
    i_ask, gpt_reply = y[-1]
    y[-1] = (
        # None if i_ask is None else markdown.markdown(i_ask, extensions=['fenced_code', 'tables']),
        None if i_ask is None else markdown.markdown(i_ask, extensions=['fenced_code', 'codehilite', 'tables', 'sane_lists']),
        None if gpt_reply is None else markdown.markdown(i_ask, extensions=['fenced_code', 'codehilite', 'tables', 'sane_lists'])
    )
    return y

```

**Comment by abidlabs** [comment]
I think we do do some html sanitization -- @dawoodkhan82 can you take a look at this?

**Comment by Kilig947** [comment]
> I think we do do some html sanitization -- @dawoodkhan82 can you take a look at this?

@dawoodkhan82  Is there a plan to fix this? Or is there anything else I can do to inline a web page in a dialog? Not being able to inline a web page is very disruptive to my multimodal application!

**Comment by dawoodkhan82** [comment]
@Kilig947 we sanitize the chatbot message to prevent vulnerabilities. Maybe we can add an option to turn off html sanitization.
