### ISSUE TITLE
Is that anyway can get the path of the `gr.Examples` when it be set to gr.Image?

### ISSUE THREAD

**Issue by sanbuphy** [gradio-app/gradio#5079]
- [√ ] I have searched to see if a similar issue already exists.

Hi! I want to use a list of images to be the examples. But when i use `gr.Image` to set the `inputs` param , I can't get the path name of the image. How can I get the image path name ? Thank you very much ！

**Comment by abidlabs** [comment]
Hi @sanbuphy, for general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). Please also provide more details and a code example as the question is not clear to me. (I'll close this issue)
