### ISSUE TITLE
Chatbot custom text highlight

### ISSUE THREAD

**Issue by austinmw** [gradio-app/gradio#5087]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I'd like to be able to display named entity recognition in a chatbot message.

**Describe the solution you'd like**  
I'd like to be able to highlight specific words. For example if I have an ML model that identifies all proper nouns, I'd like to highlight them in green.

**Additional context**  
To do this do I need custom HTML in the chat message?

**Comment by abidlabs** [comment]
Hi @austinmw yes the `gr.Chatbot` supports Markdown, which is a superset of HTML. So you can create this in HTML and pass it as a message for the `gr.Chatbot`. We won't support arbitrary components in Gradio chatbots at the moment, so this is the best approach as of now. However, we're working on making it possible for Gradio users to create their own custom components -- meaning that you'll be able to take an existing Gradio component and clone it, modify the backend or the frontend, and use it in your Gradio apps. This might help solve this use case!

By the way, for general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
