### ISSUE TITLE
support heartbeat when not using browser and a background task is running

### ISSUE THREAD

**Issue by eastonsuo** [gradio-app/gradio#5089]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
When I run a background task such as a model training , which will consume a lot of time.  I may leave browser and wait for a while , the connection between brower and gradio server will disconnected and an ERROR will appear in browser.

**Describe the solution you'd like**  
Is there a way for sending a signal such as a heartbeat to backend using gradio config?

**Comment by abidlabs** [comment]
Have you enabled queuing @eastonsuo? If so, this shouldn't be happening. Would be great if you can share some sample code that times out for you (and let us know roughly how long it takes to timeout)

**Comment by eastonsuo** [comment]
> Have you enabled queuing @eastonsuo? If so, this shouldn't be happening. Would be great if you can share some sample code that times out for you (and let us know roughly how long it takes to timeout)

thx, the ws connection is heartbeat

**Comment by abidlabs** [comment]
Ok sounds good, will close this then.
