### ISSUE TITLE
GUI is broken and NOT working

### ISSUE THREAD

**Issue by yoon28** [gradio-app/gradio#5091]
### Describe the bug

I wrote a simple Gradio app but it was not working.
I attached the code I ran in below.
Also, I attached the generated GUI which is broken and ugly.
The button "Greet" is not working. Nothing was appeared in "Output Box".
I used chrome browser.

gradio v3.39.0
gradio_client v0.3.0.
Ubuntu 22.04.2 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Here is the code I used.

```
import gradio as gr

gr.close_all()

def greet(name):
    print(name)
    return "Hello " + name + "!"

with gr.Blocks() as demo:
    name = gr.Textbox(label="Name")
    output = gr.Textbox(label="Output Box")
    greet_btn = gr.Button("Greet")
    greet_btn.click(fn=greet, inputs=name, outputs=output)

demo.launch(server_name="0.0.0.0", server_port=8001)
```

### Screenshot

Here is the generated GUI on chrome browser.

![image](https://github.com/gradio-app/gradio/assets/7078947/d69c9567-c6cb-4f9f-ae9e-b0332670d105)

### System Info

```shell
gradio v3.39.0
gradio_client v0.3.0.
Ubuntu 22.04.2
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @yoon28 I can't reproduce this issue -- please see this Colab notebook, which is also running on Linux with the same gradio version: https://colab.research.google.com/drive/1y_Lr33TUxuOQkUuffZU0tSvbdUwLlPXC?usp=sharing

Is there anything specifically that might be happening in your environment? I would also try `pip uninstall gradio` and reinstalling `pip install gradio`

**Comment by yoon28** [comment]
I ran the code with root privilege.
Here is my environment. [link](https://hub.docker.com/layers/yoon28/codeserver-miniforge/4.11-23.1/images/sha256-4096d89d699d134a22dd23f22274a024725e440c291f7c2a562e81307ee8ba66?context=repo)
Do you have any idea?
I spent two days to solve this problem but I can't.

**Comment by abidlabs** [comment]
Nothing obvious sticks out to me @yoon28, sorry. Will close for lack of reproducibility. If you are isolate what might be different in your environment and share that with us, happy to reopen.
