### ISSUE TITLE
Sweep: Strip the user's username before login in routes.py. Add a unit test for this within test_post_login

### ISSUE THREAD

**Issue by wwzeng1** [gradio-app/gradio#5100]
It seems that spaces are kept at the beginning and at the end of the username's Textbox on login page.

Can you strip the username in the login route in the script gradio/routes.py?
We also need to add a unit test within test_post_login

**Comment by kevinlu1248** [comment]
sweep: Retry

**Comment by wwzeng1** [comment]
Sweep: retry

**Comment by abidlabs** [comment]
Hi @wwzeng1 thanks for creating this issue and I'll accept this PR for now, but for Sweep to be practical for us, we'll need for it to understand GitHub issues as they naturally occur including conversation history between maintainers and users.

**Comment by wwzeng1** [comment]
Make a lot of sense. We'll implement that feature for you today, where multiple messages will be condensed as the input to Sweep. I'll email you when that's complete!
