### ISSUE TITLE
Web sockets disconnects when launching gradio behind a NAT gateway in AWS

### ISSUE THREAD

**Issue by cowanAI** [gradio-app/gradio#5101]
### Describe the bug

Here are the logs: 
<img width="1161" alt="Screenshot 2023-08-04 at 6 50 50 PM" src="https://github.com/gradio-app/gradio/assets/128092052/1ed36afd-38f3-4b10-a781-4d07b74ef14f">

Currently running the app in a private VPC and using Nat Gateway.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

It's hard to reproduce due to the complex architecture, but is 100% the NAT gateway because the issue goes away when I make the ec2 instances public, the app actually works, but I will get randomly disconnected.

### System Info

```shell
Latest gradio version
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @cowanAI can you see if this is still an issue in 4.x? We've switched from using websockets to server-side-events

**Comment by abidlabs** [comment]
Closing for lack of followup
