### ISSUE TITLE
Feature Request: Inversible Chat Order

### ISSUE THREAD

**Issue by raymondtri** [gradio-app/gradio#5102]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Not necessarily, but it is frustrating in a long chat needing to scroll all the way up to get to the input interface again.

**Describe the solution you'd like**  
I would like to be able to configure gradio to prepend chat replies instead of appending them so that the most recent reply from the AI is on the top and scrolling becomes less necessary.

**Additional context**  
I can't think of any additional context to provide. It would be awesome if we could get this:
- Input field
- Reply 3
- Query 3
- Reply 2
- Query 2
- Reply 1
- Query 1

Instead of this
- Input field
- Query 1
- Reply 1
- Query 2
- Reply 2
- Query 3
- Reply 3

**Comment by abidlabs** [comment]
Hi @raymondtri why not just put the textbox underneath the Chatbot? That's what's done in Gradio's default `ChatInterface` class

**Comment by abidlabs** [comment]
Will close for lack of follow up. Happy to reopen if needed.

**Comment by upmangaurav** [comment]
Hi @raymondtri Were you able to work something out for this issue?

@abidlabs We are using Gradio to show Search results which necessitates textbox at the top, followed by results in chronological order (as mentioned by OP). 

Currently I need to scroll all the way up after results are displayed.
