### ISSUE TITLE
Audio streaming is not working properly

### ISSUE THREAD

**Issue by snarb** [gradio-app/gradio#5110]
### Describe the bug

I am having the same goal as i https://github.com/gradio-app/gradio/issues/3299 to make stream audio works. This could be from remote server or from several local wav files (when first is processed second is generated). 

I have checked this solution:    [yield-ing the output audio file to an Audio output component. ](https://gradio.app/key-features/#iterative-outputs) it is not working properly,
```
def transcribe(audio)
    flist = ['33056526426.wav', '65074181139.wav']
    for i in range(2):
        if i > 0:
            time.sleep(2)
         yield flist[i]
```

Not working and hangs UI thread during sleep. With single file works properly.

 Example from this one [https://github.com/gradio-app/gradio/issues/1775](https://github.com/gradio-app/gradio/issues/1775) is also looks like not working properly _gradio/demo/stream_audio/run.py_.  or doesn't looks like supports real time playback, it is not clear how to stream audio when microphone is not triggering _add_to_stream_, and how to trigger output audio stream update from some background thread that is making processing. It would be so nice to have some working example .

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

1) ```
def transcribe(audio)
    flist = ['33056526426.wav', '65074181139.wav']
    for i in range(2):
        if i > 0:
            time.sleep(2)
     yield flist[i]
```
2)```
import gradio as gr
import numpy as np
import time

def add_to_stream(audio, instream):
    time.sleep(1)
    if audio is None:
        return gr.update(), instream
    if instream is None:
        ret = audio
    else:
        ret = (audio[0], np.concatenate((instream[1], audio[1])))
    return ret, ret


with gr.Blocks() as demo:
    inp = gr.Audio(source="microphone")
    out = gr.Audio()
    stream = gr.State()
    clear = gr.Button("Clear")

    inp.stream(add_to_stream, [inp, stream], [out, stream])
    clear.click(lambda: [None, None, None], None, [inp, out, stream])


if __name__ == "__main__":
    demo.launch()
```

### System Info

```shell
any
```

### Severity

Blocking usage of gradio

**Comment by aliabid94** [comment]
Working on this, will update soon
