### ISSUE TITLE
I want to add logo Image on top left Corner can you please provide a sample code for it.

### ISSUE THREAD

**Issue by yhammadmufin** [gradio-app/gradio#5113]
I want to add logo Image on top left Corner can you please provide a sample code for it.

**Comment by yhammadmufin** [comment]
@JaySmithWpg @kashif @dsully @akx

**Comment by abidlabs** [comment]
Hi @yhammadmufin, for general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
