### ISSUE TITLE
Add support for async fn to `ChatInterface` 

### ISSUE THREAD

**Issue by ZeusFSX** [gradio-app/gradio#5115]
### Describe the bug

I tried to mount the async function to ChatInterface and got the error. Please take a look at the logs included below.
If you have suggestions on how I can implement the Chat Interface with the async function, I'd like to read them.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

I used the FastApi interface to mount the application
```
async def gradio_app_for_bi(message: str, history: list[list[str]]) -> str:
    ....

chatbot = gr.ChatInterface(fn=gradio_app_for_bi, title="Business Demo")
app = gr.mount_gradio_app(app, chatbot, path="/gradio")
```

### Logs

```shell
ValueError: Invalid message for Chatbot component: <coroutine object gradio_app_for_bi at 0x16ed689e0>
```

### System Info

```shell
Gradio Environment Information:
Operating System:  Darwin


gradio version:  3.39.0

gradio Dependencies:
  aiofiles: 23.1.0
  aiohttp: 3.8.4
  altair: 5.0.1
  fastapi: 0.100.1
  ffmpy: 0.3.0
  gradio-client: 0.3.0
  httpx: 0.24.1
  huggingface-hub: 0.16.4
  jinja2: 3.1.2
  markdown-it-py: 2.2.0
  markupsafe: 2.1.3
  matplotlib: 3.7.2
  mdit-py-plugins: 0.3.3
  numpy: 1.25.1
  orjson: 3.9.2
  packaging: 23.1
  pandas: 2.0.3
  pillow: 10.0.0
  pydantic: 1.10.11
  pydub: 0.25.1
  python-multipart: 0.0.6
  pyyaml: 6.0
  requests: 2.31.0
  semantic-version: 2.10.0
  typing-extensions: 4.5.0
  uvicorn: 0.22.0
  websockets: 11.0.3


gradio_client version:  0.3.0

gradio_client Dependencies:
  fsspec: 2023.6.0
  httpx: 0.24.1
  huggingface-hub: 0.16.4
  packaging: 23.1
  requests: 2.31.0
  typing-extensions: 4.5.0
  websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @ZeusFSX not at the moment, that's on my list of todos. Will take a look at this soon.

**Comment by Leumastai** [comment]
Checking in if this has been implemeted?

**Comment by abidlabs** [comment]
Yes you can check by doing:

```py
import gradio as gr

async def echo(message, history):
    return message

gr.ChatInterface(echo).launch()
```

on the latest version of gradio

**Comment by davidshen84** [comment]
Hi all,

Sorry to bring up this old thread. The latest doc: https://www.gradio.app/docs/gradio/chatinterface#param-chatinterface-fn, still doesn't mention if `async` callbacks are supported.

Is it an officially support feature, or it just happens to behavior this way and nobody knows why?

I want to integrate LangChan's async streaming API, so I will need a callback like this:

```python
async def get_llm_streaming_response(message: str, hist: list) -> AsyncGenerator[str]:
  ...
  yield response
```

Would this work with the ChatInterface's callback?
