### ISSUE TITLE
Multiprocessing Support

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#513]
**Describe the solution you'd like**
We could take advantage of [multiprocessing](https://pypi.org/project/multiprocessing/) while running the ML models in the background. This would decrease the burden on the cpu core that server works on.

**Comment by FarukOzderim** [comment]
Related information about spaces machines.

![image](https://user-images.githubusercontent.com/44067394/155494826-375c4288-9e66-4f04-b169-d61565bd079a.png)

**Comment by FarukOzderim** [comment]
This is found to be unnecessary with the latest information. It seems that ML libraries are already utilizing multi core while working in CPU. Thanks @cbensimon for the information 🤲!

A related test and screenshot can be found below, as I tested it for fastapi/starlette threadpool as well.

![image](https://user-images.githubusercontent.com/44067394/157302697-95fde461-62c0-43ba-bfb7-2a0c00fb5b97.png)

```
import tensorflow as tf
from fastapi import FastAPI
import uvicorn
import numpy as np
import time
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

app = FastAPI()


# run function in threadpool
@app.get("/tensorflow")
def tensorflow():
    begin = time.time()

    random_matrix = np.random.rand(10 ** 4, 10 ** 4)
    for i in range(10 ** 3):
        multiplication = tf.multiply(random_matrix, random_matrix)
    end = time.time()
    return f"Duration: {round(end - begin)} seconds"


uvicorn.run(app, port=5000)
```

**Comment by abidlabs** [comment]
Very good to know, thanks @FarukOzderim and @cbensimon!
