### ISSUE TITLE
gradio video player: time numbers under 10 are not displayed properly as :01

### ISSUE THREAD

**Issue by fffiloni** [gradio-app/gradio#5132]
### Describe the bug

:bug: I spotted a bug on the gradio video player: time numbers under 10 are not displayed properly as :01 (see video sample)
https://github.com/gradio-app/gradio/assets/7447007/52d5818f-ca4f-4cd7-ada1-c48fbe059c91

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

I spotted it while testing the UniVTG demo : https://huggingface.co/spaces/KevinQHLin/UniVTG

### System Info

```shell
gradio 3.39.0 on HF Spaces
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
The weird thing is that we're just using the default HTML `<video>` player... this isn't a gradio bug as far as I can tell, right @hannahblair @dawoodkhan82?
