### ISSUE TITLE
post-login action

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#5138]
- [x] I have searched to see if a similar issue already exists.

After using auth login, I'd like to update the UI for the user, but currently I'd require them click something after login to do that.  It would be nicer if there was a post-login action (like login.then()) so we could take arbitrary actions after a login event.

**Comment by pseudotensor** [comment]
Correct, this is not an app launch level event but a per-user level login event to make UI updated for that specific user.

**Comment by abidlabs** [comment]
Events that are defined via `Blocks.load()` actually _do_ happen per user (or rather per browser session), but you wouldn't be able to get the username in such an event

**Comment by pseudotensor** [comment]
Do Blocks.load() allow accepting gr.Requests so login is known that way?

**Comment by abidlabs** [comment]
It does accept `gr.Request()` but since the user will not be logged in when the page loads so it won't allow to get the username (username will be `None`)

**Comment by pseudotensor** [comment]
I see, so Blocks.load() occurs during page loading, but before login user/pass is accepted.

**Comment by abidlabs** [comment]
Oh actually I was wrong, it occurs after the login, so you should be able to use it! Here's an example:

```py
import gradio as gr

def test(request: gr.Request):
    return "Welcome, " + request.username

with gr.Blocks() as demo:
    t = gr.Textbox()
    demo.load(test, None, t)
    
demo.launch(auth=("a", "a"))
```

**Comment by pseudotensor** [comment]
Cool.  Does it allow for .then() behavior?  That is, I need to get request state stuff, and then pass along to another function.  I think I can merge them if required, but just curious.

**Comment by abidlabs** [comment]
It should :)

I'll go ahead and close this issue.

**Comment by pseudotensor** [comment]
Awesome, works, thanks!
