### ISSUE TITLE
How do I know if Gradio server is Up and healthy? Are there any health end points?

### ISSUE THREAD

**Issue by smamindl** [gradio-app/gradio#5139]
I have searched to see if a similar issue already exists.

Hi @abidlabs  , I am facing issues with an object detection video streaming meaning it freezes at some point while runs fine locally. I want to check the health status of Gradio if it is up and running. Are there any health end points in gradio? I could not find any. Can anyone help? Thanks.

**Comment by abidlabs** [comment]
Hi @smamindl please take a look at this: https://github.com/gradio-app/gradio/issues/4110

Should answer your question so I'll close this issue.

**Comment by smamindl** [comment]
> #4110

Thank you @abidlabs
