### ISSUE TITLE
How to set the size of gr.Radio

### ISSUE THREAD

**Issue by violet17** [gradio-app/gradio#5148]
I have 8 radiobuttons in my app, but I can't find the way to set the size of gr.Radio to make them looks in two columns and each column is left aglinment.
Thanks.
![image](https://github.com/gradio-app/gradio/assets/4042800/e22bf70e-f490-46fb-b6b6-8fa2dbb1ac9b)
In the image above,  the second column is not left aglinment, whick looks out of order.

Can you share the way to set the size of gr.Radio?

**Comment by abidlabs** [comment]
Hi @violet17 this isn't possible unfortunately with the `gr.Radio` component. We're not likely to implement this functionality in `gr.Radio`, but we are opening up support for custom, community-designed components. I'll leave this and mark it as a "new component" label, as it could fit in that category.

**Comment by violet17** [comment]
Hi @abidlabs  Thank you very much for you reponse. It would be better if we have more choices for the UI setting.

**Comment by violet17** [comment]
@hannahblair  Thank you very much!!! It really helps a lot!!!
