### ISSUE TITLE
Error streaming gr.ChatInterface in cloud environments

### ISSUE THREAD

**Issue by tkreuder** [gradio-app/gradio#5150]
### Describe the bug

I am trying to deploy gradio ChatInterface to a cloud server. Streaming only works locally, but not on a server like google cloud run or fly.io. Without streaming it works like a charm no matter if running in the cloud or locally. 

I get:

`rs.complete return_value=(b'HTTP/1.1', 301, b'Moved Permanently', [(b'location', b'https://xxx/gradio-chat/reset'), (b'server', b'Fly/49bc237b (2023-08-04)'), (b'via', b'1.1 fly.io'), (b'fly-request-id', b'01H7D1XF5K3Q4JZE58PD9739WM-ams'), (b'content-length', b'0'), (b'date', b'Wed, 09 Aug 2023 11:46:34 GMT')])`

Which leads to gradio Interface error:  `Expecting value: line 1 column 1 (char 0)` , because content-length is zero due to redirect.

It can be circumvented with e.g. `CMD ["uvicorn", "app.main:app", "--log-level", "debug", "--host", "0.0.0.0", "--port", "8080", "--forwarded-allow-ips", "*"]`, but this is of course a security risk. Besides this leads to strange chat output issues, where the result is flickering and text gets duplicated.

Enabling authentication also leads to issues with streaming, when enabled like so:
``` 
...
with gr.Blocks() as chat_demo:
  chat_demo.auth = [(settings.GRADIO_USERNAME, settings.GRADIO_PASSWORD)]
  chat_demo.auth_message = "Please login to use this demo"
...
``` 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

``` 
from fastapi import FastAPI
import gradio as gr
import time

app = FastAPI()

def slow_echo(message, history):
    for i in range(len(message)):
        time.sleep(0.3)
        yield "You typed: " + message[: i+1]
        
with gr.Blocks() as chat_demo:
  chat_demo.queue()
  gr.ChatInterface(slow_echo)
     
app = gr.mount_gradio_app(app, chat_demo, path="/")
``` 

### Screenshot

<img width="1670" alt="Screenshot 2023-08-09 at 14 33 41" src="https://github.com/gradio-app/gradio/assets/385110/7b04dd1d-8891-45be-8a45-eeca467d299a">

### System Info

```shell
Gradio Environment Information:
Operating System:  Darwin


gradio version:  3.39.0

gradio Dependencies:
  aiofiles: 23.1.0
  aiohttp: 3.8.5
  altair: 5.0.1
  fastapi: 0.101.0
  ffmpy: 0.3.1
  gradio-client: 0.3.0
  httpx: 0.23.3
  huggingface-hub: 0.16.4
  jinja2: 3.1.2
  markdown-it-py: 2.2.0
  markupsafe: 2.1.3
  matplotlib: 3.7.2
  mdit-py-plugins: 0.3.3
  numpy: 1.25.2
  orjson: 3.9.4
  packaging: 23.1
  pandas: 2.0.3
  pillow: 10.0.0
  pydantic: 1.10.11
  pydub: 0.25.1
  python-multipart: 0.0.6
  pyyaml: 6.0.1
  requests: 2.31.0
  semantic-version: 2.10.0
  typing-extensions: 4.7.1
  uvicorn: 0.21.1
  websockets: 11.0.3


gradio_client version:  0.3.0

gradio_client Dependencies:
  fsspec: 2023.6.0
  httpx: 0.23.3
  huggingface-hub: 0.16.4
  packaging: 23.1
  requests: 2.31.0
  typing-extensions: 4.7.1
  websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by swapnil3597** [comment]
@tkreuder, Facing same issue, did you find any solution for this?

**Comment by freddyaboulton** [comment]
The main difference between streaming and not streaming is that the streaming happens over a websocket connection. So make sure websockets are open on your cloud server. The client will try to connect via `/queue/join`

**Comment by swapnil3597** [comment]
> The main difference between streaming and not streaming is that the streaming happens over a websocket connection. So make sure websockets are open on your cloud server. The client will try to connect via `/queue/join`

Hi @freddyaboulton, the streaming is happening fine when performing gradio.launch(), but with gradio.launch() I'm unable to provide custom url route.

In order to provide custom url route we are using `gr.mount_gradio_app` with fastapi. How to ensure if websockets are open?

**Comment by freddyaboulton** [comment]
> How to ensure if websockets are open?

It depends on the cloud hosting provider you are using. 

I just deployed your repro to https://gradio-chat-stream.onrender.com/ using render and it worked out of the box.


![chatinterface_stream_deploy](https://github.com/gradio-app/gradio/assets/41651716/d05b2173-09b0-41b8-acf6-20b108e4ef2d)

**Comment by tkreuder** [comment]
Back from vacation. 
So i tried it with gcloud and fly.io, which support websockets out of the box. What should i configure @freddyaboulton ?

Has somebody achieved it with one of those providers already?

**Comment by tkreuder** [comment]
> It can be circumvented with e.g. `CMD ["uvicorn", "app.main:app", "--log-level", "debug", "--host", "0.0.0.0", "--port", "8080", "--forwarded-allow-ips", "*"]`, but this is of course a security risk. 
you can do this @swapnil3597 , but it is insecure to deploy your app like this.

**Comment by freddyaboulton** [comment]
This is my uvicorn command @tkreuder 

```
uvicorn app:app --host 0.0.0.0 --port 10000
```

This is the full repo that's being deployed: https://github.com/freddyaboulton/gradio-sub-app/tree/main

**Comment by rmkraus** [comment]
I'm running into this same issue. In our case, We have Gradio that is hosting itself with HTTP. This is behind a Layer 7 proxy that is hosting HTTPS. What is most interesting is that we get the same log messages whether we access Gradio through the proxy or if we go directly to Gradio and bypass the proxy.

```
[1] Oct 19 19:36:48 [   INFO] - uvicorn.error - ('172.18.0.1', 44364) - "WebSocket /queue/join" [accepted]
[1] Oct 19 19:36:48 [   INFO] - uvicorn.error - connection open
[1] Oct 19 19:36:48 [   INFO] - httpx - HTTP Request: POST http://PUBLIC_URL.EXAMPLE.com/content/converse/api/predict "HTTP/1.1 301 Moved Permanently"
[1] Oct 19 19:36:48 [   INFO] - uvicorn.error - connection closed
[1] Oct 19 19:36:48 [   INFO] - httpx - HTTP Request: POST http://PUBLIC_URL.EXAMPLE.com/content/converse/reset "HTTP/1.1 301 Moved Permanently"
```

So even when we bypass the proxy, it appears as if Gradio tries to hit itself using its public URL, but with only HTTP. If is getting a redirect requesting it to upgrade to HTTPS and seemingly not handling this.

**Comment by abidlabs** [comment]
Hi folks, can you see if this is still an issue in 4.x? We've switched from using websockets to server-side-events

**Comment by abidlabs** [comment]
Closing for lack of followup. We can reopen if we hear more details.
