### ISSUE TITLE
Can not show cropped image correctly

### ISSUE THREAD

**Issue by li-chengkun** [gradio-app/gradio#5152]
### Describe the bug

When I crop image in input "Image" component, it seems can not show the cropped image correctly. 
Just like the below image shows. The output is just shows the what we submmitted, but we can see the output get right result, but the input Image component can not show the cropped image.
![image](https://github.com/gradio-app/gradio/assets/48325263/ee4e150b-3d46-4c06-beb6-ed3382b84acf)

And when I click the input "Image" component, now it shows cropped image correctly! But after clicking the submit button, the output is the original image!
![image](https://github.com/gradio-app/gradio/assets/48325263/93bbf3e4-3320-4264-a2f8-7040a0457210)
So is there anyone can help me resolve this problem?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
def f(image):
    print(image)
    return image

interface = gr.Interface(
    fn=f,
    inputs=gr.Image(type="filepath", source='upload', tool="select"),
    outputs = gr.Image(type="filepath", label=None),
    title="Image Search",
)
interface.launch()

interface.close()
```

### System Info

```shell
Gradio==3.39.0
OS: Ubuntu 20.04
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Sorry @li-chengkun yes it's broken right now. We'll fix the cropper as part of #5055

**Comment by li-chengkun** [comment]
Thank you for the reply. And i find it performs well in lower version, like 3.15.0. But the lower versions don't have components I want. So I would greatly appreciate it if you could fix this problem

**Comment by henryruhs** [comment]
@abidlabs as there is another issue, you might close this one due "duplicate".

**Comment by abidlabs** [comment]
@henryruhs what's the duplicate issue?
