### ISSUE TITLE
HFDatasetSaver format is not compatible with datasets

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#5155]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Our HFDatasetSaver is able to properly save the flagged data to HF. See [example](https://huggingface.co/datasets/freddyaboulton/new_saving_json_3)

However, over the last couple of days I've noticed the last couple of issues:

- If `separate_dirs=False`, the dataset can't be loaded by `datasets` lib at all. See [example](https://huggingface.co/datasets/freddyaboulton/new_saving_csv_9). The dataset preview fails completely.
- If `separate_dirs=True`, the datasets library is not able to correctly infer the types of Image and Audio features. This means there is also no preview for these kinds of features.
- The `datasets_info.json` file has no effect. The right thing to do is to update the README.md, see [example](https://huggingface.co/datasets/freddyaboulton/new_saving_json_8/blob/main/README.md)
- Even if we correctly add the type info in the README, the datasets library has trouble finding the image files to open with PIL. See image below. We may have to restructure the data directory.
<img width="686" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/2bf269d7-ca61-4fe1-8bba-3d8eb4ede33e">

@Wauplin can assist us. He has some knowledge on the right directory format.

**Comment by Wauplin** [comment]
Also worth mentioning the new [`CommitScheduler`](https://huggingface.co/docs/huggingface_hub/v0.16.3/en/package_reference/hf_api#huggingface_hub.CommitScheduler) implemented in `huggingface_hub` to deal with regular uploads. [I've also set up a demo Space ](https://huggingface.co/spaces/Wauplin/space_to_dataset_saver) to showcase how to save data to a dataset in the correct format (as jsonl, csv, images or custom parquet).

**Comment by freddyaboulton** [comment]
Yea maybe the new approach can be to just have csv/jsonl local flagging callbacks and then optionally back them up to a HF dataset

**Comment by abidlabs** [comment]
Closing as `HFDatasetSaver` is no longer part of the codebase!
