### ISSUE TITLE
Streaming Audio Output latency / gap issues

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#5160]
### Describe the bug

I'm running `stream_audio_output` and when I run with a file shorter than 3 seconds, no audio gets streamed to the output component. If I use a file with more than 3 seconds, the output skips the first three seconds.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
from pydub import AudioSegment

def stream_audio(audio_file):
    audio = AudioSegment.from_mp3(audio_file)
    i = 0
    chunk_size = 3000
    
    while chunk_size*i < len(audio):
        chunk = audio[chunk_size*i:chunk_size*(i+1)]
        i += 1
        if chunk:
            file = f"/tmp/{i}.mp3"
            chunk.export(file, format="mp3")            
            yield file
        
demo = gr.Interface(
    fn=stream_audio,
    inputs=gr.Audio(type="filepath", label="Audio file to stream"),
    outputs=gr.Audio(autoplay=True, streaming=True),
)

if __name__ == "__main__":
    demo.queue().launch()
```

with this file, 8 out of the first three seconds play. The first three seconds are missing.
https://github.com/gradio-app/gradio/assets/41651716/48415057-f79c-4557-bea8-11779b9f2f03

<img width="1731" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/dfe4e492-bb73-4b0c-a170-bfb595a1968c">

With cantina.wav, no audio is streamed
<img width="1615" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/4c8bbecf-5a1c-4fc0-b5ab-a92f364caa4c">

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 3.39.0
gradio_client version: 0.3.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
aiohttp: 3.8.5
altair: 4.2.0
fastapi: 0.87.0
ffmpy: 0.3.1
gradio-client==0.3.0 is not installed.
httpx: 0.23.0
huggingface-hub: 0.14.0
importlib-resources: 6.0.1
jinja2: 3.1.2
markdown-it-py: 2.2.0
markupsafe: 2.1.1
matplotlib: 3.7.2
mdit-py-plugins: 0.3.3
numpy: 1.21.6
orjson: 3.9.4
packaging: 22.0
pandas: 1.3.5
pillow: 9.2.0
pydantic: 1.9.1
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.28.1
semantic-version: 2.10.0
typer: 0.9.0
typing-extensions: 4.3.0
uvicorn: 0.23.2
websockets: 11.0.3


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.23.0
huggingface-hub: 0.14.0
packaging: 22.0
requests: 2.28.1
typing-extensions: 4.3.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by ylacombe** [comment]
I've also noticed a few bumps each time one song ends and another begins. This is probably because there is some latency when a new file is played.

I wonder if there are ways to read audio directly as a byte stream, so as to have more flexibility in audio playback.

If that can be of some help, I'm referring to [some code] (https://github.com/ylacombe/streaming_bark/blob/main/client_side.py) I wrote to test an AI model generating audio where I used `pyaudio` to play the stream directly instead of going through an intermediate mp3 file.


```python
import pyaudio

# Audio settings
FORMAT = pyaudio.paFloat32 #paInt16
CHANNELS = 1
RATE = 24000
CHUNK_SIZE = 8192

# Create PyAudio audio output stream
audio = pyaudio.PyAudio()
stream = audio.open(
    format=FORMAT,
    channels=CHANNELS,
    rate=RATE,
    output=True,
    frames_per_buffer=CHUNK_SIZE
)

SILENCE = chr(0)*CHUNK_SIZE*2 


while True:    
    try:
        audio_data = ...# Receive audio stream from generator
        
        
        print("audio", len(audio_data))

        # generation is too slow so silence
        if audio_data == "":
            print("silence")
            audio_data = SILENCE
        stream.write(audio_data)
        
    except:
        break

# Clean up
stream.stop_stream()
stream.close()
audio.terminate()
```

**Comment by aliabid94** [comment]
yeah letting users return bytes seems like the best approach here. Will try that.
@ylacombe are you saying it's better to return explicit chunks of silence instead of letting a StreamingResponse hang?

**Comment by ylacombe** [comment]
From my experience, if the generation of chunks of audio is slower than actually playing the chunks, you get horrible outputs (with weird white noises when nothing is playing), so you might want to figure out a strategy for that case.
Imo playing small audio silence could be good, but tbh you should try before first (or maybe leave the choice to send blank audio stream to the user)
