### ISSUE TITLE
Request for Adding Logout Functionality

### ISSUE THREAD

**Issue by Buddies-as-you-know** [gradio-app/gradio#5163]
- [x] I have searched to see if a similar issue already exists.
Is your feature request related to a problem? Please describe.
I often find it inconvenient when using Gradio that there isn't a way to log out from the system once I'm done using it. This creates a potential security risk, especially when using shared computers or public networks.

**Describe the solution you'd like**
I would appreciate it if a logout functionality could be implemented in Gradio. This would allow users to securely log out after they have finished using the platform, ensuring that their sensitive information and session data are properly cleared.

**Additional context**
It would be helpful if the logout option could be easily accessible from the user interface, perhaps in the form of a profile or account settings menu. This feature would enhance the overall user experience and provide an added layer of security to the application. Screenshots or mockups demonstrating the proposed logout feature's placement and design might be beneficial for consideration.

**Comment by ODENSUKI** [comment]
Hello.
Any progress on this issue?

**Comment by yosephinestwn** [comment]
> Hi, Modifing the routes.py file in gradio adding the following code , makes the logout button work.
> 
> ```
> @app.get("/logout")
>         def logout():
>             response = RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
>             response.delete_cookie(key=f"access-token-{app.cookie_id}")
>             response.delete_cookie(key=f"access-token-unsecure-{app.cookie_id}")
>             return response
> ```
> 
> Wonder if theres anyway to do that from main app withou modifing gradio files.

This solution does not work for me. The current user is still logged in if the button is clicked. Is there anything that you do (e.g. to the event listener of the logout button) other than only modifying the routes.py?

**Comment by cpatrickalves** [comment]
> Hi, Modifing the routes.py file in gradio adding the following code , makes the logout button work.
> 
> ```
> @app.get("/logout")
>         def logout():
>             response = RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
>             response.delete_cookie(key=f"access-token-{app.cookie_id}")
>             response.delete_cookie(key=f"access-token-unsecure-{app.cookie_id}")
>             return response
> ```
> 
> Wonder if theres anyway to do that from main app withou modifing gradio files.

This solution also did not work for me. 
Does anyone have any other solution?
