### ISSUE TITLE
Model3D: allow setting initial camera position

### ISSUE THREAD

**Issue by mbahri** [gradio-app/gradio#5167]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Some 3D assets are not oriented in a convenient way for the default camera settings in Babylon.js, resulting in the need to rotate them manually for visualization.

**Describe the solution you'd like**  
it would be convenient to be able to set the initial camera rotation (or full position) when the viewer loads.
```
# Example API
gr.Model3D(alpha=<longitudinal rotation>, beta=< latitudinal rotation>, radius=None)
```

**Additional context**  
https://doc.babylonjs.com/features/featuresDeepDive/scene/fastBuildWorld#create-default-camera-or-light
https://doc.babylonjs.com/features/featuresDeepDive/cameras/camera_introduction#arc-rotate-camera

**Comment by mbahri** [comment]
I can try but I'll need approval from my employer before contributing the change here.

A quick attempt at hardcoding the angles in Svelte worked for setting the viewing angle for Model3D components used as outputs, but not for the preview of assets uploaded as inputs.

I also need to fix the passing of parameters from the Python component to the actual JS component. I'll have another look tomorrow but it wasn't immediately clear to me how the wrappers mentioned in https://www.gradio.app/guides/creating-a-new-component (`js/app/src/components/Model3D/index.ts`) are forwarding arguments from the Python constructor.

I tried adding an `alpha` param. in Python and adding `export let alpha: number = 180;` to `js/model3D/static/Model3D.svelte` but that didn't work.

**Comment by mbahri** [comment]
PR submitted: https://github.com/gradio-app/gradio/pull/5266

**Comment by A-pril** [comment]
Hello~I wanna know if  I can get the real-time camera pose since I use it as a input to my model. Thanks a lot!

**Comment by fabienbaradel** [comment]
@marcnotenboom did you find a way to solve this ? I am facing the same issue

**Comment by marcnotenboom** [comment]
> @marcnotenboom did you find a way to solve this ? I am facing the same issue

I moved away from it and am using Three.js now
