### ISSUE TITLE
Audio streaming still not working properly with latest fixes

### ISSUE THREAD

**Issue by snarb** [gradio-app/gradio#5168]
### Describe the bug

I have tested Audio streaming with latest changes  Live audio streaming output https://github.com/gradio-app/gradio/pull/5077. I have make a build from the repository.  demo\stream_audio_out is working. But still there are couple of issues:
1) 
```
import gradio as gr
from pydub import AudioSegment

def stream_audio(audio_file):
    for i in range(3):
        print(i)
        yield r'Recording.mp3'

demo = gr.Interface(
    fn=stream_audio,
    inputs=gr.Audio(type="filepath", label="Audio file to stream"),
    outputs=gr.Audio(autoplay=True, streaming=True),
)

if __name__ == "__main__":
    demo.queue().launch()

```

It will play/stream the Recording.mp3 2 times instead of 3.

2) 
```
import gradio as gr
from pydub import AudioSegment

def stream_audio(audio_file):
    for i in range(3):
        print(i)
        yield r'Recording.wav'

demo = gr.Interface(
    fn=stream_audio,
    inputs=gr.Audio(type="filepath", label="Audio file to stream"),
    outputs=gr.Audio(autoplay=True, streaming=True),
)

if __name__ == "__main__":
    demo.queue().launch()

```
Wav files are played only single time. Looks like streaming is broken for them.

3) audio file that is passed inside the stream audio is a cropped version of the file we chose with 100 ms step. Don't know is it by design or not. More looks like a bug for me because _streaming_ is not set to _True_ for the inputs.

4) For a list of mp3 files looks like it skips the first one.
@aliabid94

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

run the code

### System Info

```shell
windows 10
```

### Severity

Can find workaround

**Comment by freddyaboulton** [comment]
Seems related to #5160

**Comment by aliabid94** [comment]
looking into this
