### ISSUE TITLE
The assert statement should not be used to validate input data in production code

### ISSUE THREAD

**Issue by whitphx** [gradio-app/gradio#5169]
For example,
https://github.com/gradio-app/gradio/blob/80be7a1ca44c0adef1668367b2cf36b65e52e576/gradio/external.py#L98-L100

Reasons are explained in detail in the following pages:
* https://snyk.io/blog/the-dangers-of-assert-in-python/
  > Assert should only be used for testing and debugging — not in production environments. Because assert statements only run when the __debug__ variable is set to True, a Python interpreter can disable them.
* https://www.pluralsight.com/guides/asserts-assert-downside-defensive-programming-in-python
  > Use asserts sparingly and for things you assume are never supposed to occur.

**Comment by harry-urek** [comment]
Hey I wanna work on this issue 

I'm thinking of replacing assert statements with and if statement
like for example
```
assert (
        src.lower() in factory_methods
    ), f"parameter: src must be one of {factory_methods.keys()}"
```

with 

```
if src.lower() not in factory_methods:
        raise InvalidSourceError(
            f"parameter: src must be one of {factory_methods.keys()}"
        )
```
Feel free to correct me as I'm still in my Sophomore year of college .

**Comment by abidlabs** [comment]
That's exactly right @harry-urek! 

Just a note, you don't have to create new kinds of exceptions in every situation. For example, here it would be fine just to raise a `ValueError`. You should consider creating a new exception when there's a very Gradio-specific error happening (e.g. the `DuplicateBlockError`) or when the existing Python exceptions don't cover your use case (e.g. the `TooManyRequestsError`). 

Looking forward to your PR!
