### ISSUE TITLE
Multi user dialog in `gr.Chatbot`

### ISSUE THREAD

**Issue by MikeDean2367** [gradio-app/gradio#5181]
- [√] I have searched to see if a similar issue already exists.

Does Gradio support the dialogue output of multiple people, just like the group function of telegram?
(Refers to the output of the UI interface)

**Comment by abidlabs** [comment]
Hi @MikeDean2367 not at the moment -- this would likely involve creating a new component so I've tagged it as such. Can you elaborate a little more on your use case?

**Comment by MikeDean2367** [comment]
OK. Normally, when I input a sentence, gradio's chatbot will return me a sentence (that is, a bubble for the user, and a bubble for reply). But now I may need to input a sentence, and the chatbot can reply me with multiple sentences (that is, a bubble for the user, and multiple bubbles for reply)

**Comment by abidlabs** [comment]
Ah okay yeah you can already achieve that by just outputting `None` for the user message in those cases. 

Here's an example:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Chatbot([
        ("What are some popular foods?", "Here are some popular foods"),
        (None, "Pizza"),
        (None, "Pepperoni"),
    ])
            
demo.launch()
```

<img width="834" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/c21f8278-281c-46aa-8800-57fd029f8714">

**Comment by MikeDean2367** [comment]
OK. Thanks!

**Comment by anotherdoesnm** [comment]
wait, issue are closed but multi-user chat are not implemented?
