### ISSUE TITLE
Gradio.Dataframe: Expose an option to hide the "Add Row" button

### ISSUE THREAD

**Issue by Bengt** [gradio-app/gradio#5182]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

I want to fill a Gradio dataframe with the output of my machine learning model. For that purpose, it does not make sense for users to extend the table by themselves, so I would like to get rid of the "Add Row" button. I can make the "Add Column" button disappear by specifying a `header` and limiting the columns (`col_count=(5, 'fixed')`). However, as my model creates a varying number of rows, I cannot hide the "Add Row" button that way. If I try limiting the number of rows, the table is truncated in cases where my models produces more entries.

**Describe the solution you'd like**  

I would like to hide the "Add Row" button explicitly via an instantiation parameter in `Gradio.Dataframe`. For example `hide_add_row` could be set to `True` in order to hide the button.

**Additional context**  

My current workaround is to hide the button using CSS like so:

```css
div > div > div.controls-wrap > span > button {
    display: none !important;
}
```

That feels sketchy since there are few CSS classes and thus, this might match other elements, too.

**Comment by freddyaboulton** [comment]
Hi @Bengt !

When https://github.com/gradio-app/gradio/pull/5183 is merged, you can return `gr.Dataframe.update(value=<predictions>, row_count=(<predictions>.shape[0], "fixed"))`

**Comment by Bengt** [comment]
hi @freddyaboulton!

Thanks for taking this one on. I am looking forward to migrating to this solution.

**Comment by abidlabs** [comment]
Hi @Bengt #5236 just wondering do you need to be able to edit the dataframe values? If not, you can always set `interactive=False` which hides the buttons.

**Comment by Bengt** [comment]
@abidlabs thanks for the hint. Yes, maming the dataset non-interactive works now for hiding the buttons, but I was also affected by #5236.

**Comment by abidlabs** [comment]
Try this for now:

```
pip install https://gradio-builds.s3.amazonaws.com/f351c78e9cd467f6b8e2af50bbc437279d486722/gradio-3.40.1-py3-none-any.whl
```

**Comment by Bengt** [comment]
No, sorry. That version still shows the add row button for me:

![image](https://github.com/gradio-app/gradio/assets/11575/955f6c59-a775-45c9-a804-92bcc46bde4b)

**Comment by pngwn** [comment]
@Bengt Are you still getting this with the latest version? It should have been fixed now.

**Comment by abidlabs** [comment]
Confirmed this is no longer broken. Thanks all!
