### ISSUE TITLE
KeyError: 'type' when gr.blocks() run in hugging face

### ISSUE THREAD

**Issue by HaoHoo** [gradio-app/gradio#5198]
### Describe the bug

The code is OK in the hugging face app before and one day shows an error about gr.blocks() like the below:

Traceback (most recent call last):
  File "/home/user/app/app.py", line 41, in <module>
    with gr.Blocks() as page:
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1200, in __exit__
    self.config = self.get_config_file()
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1176, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
  File "/home/user/.local/lib/python3.10/site-packages/gradio_client/serializing.py", line 41, in input_api_info
    types = api_info.get("serialized_input", [api_info["info"]["type"]] * 2)  # type: ignore
KeyError: 'type'

I've tried to install the newest version of the Gradio library but the error still exist.  And the same code locally running on my VS Code is OK.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Access the hugging face site:
https://huggingface.co/spaces/haohoo/Azure-OpenAI-QuickDemo

### Logs

```shell
setting the debug in launch() but can't get the log from hugging face build.

Container logs:

Failed to retrieve error logs: Failed to initialize stream (code 404)
```

### System Info

```shell
log from hugging face container build:

--> RUN pip install --no-cache-dir         gradio==3.24.1
CACHED
--> RUN pip install --no-cache-dir pip==22.3.1 &&     pip install --no-cache-dir         datasets         "huggingface-hub>=0.12.1" "protobuf<4" "click<8.1" "pydantic~=1.0"
CACHED
--> RUN apt-get update && apt-get install -y 	git 	git-lfs 	ffmpeg 	libsm6 	libxext6 	cmake 	libgl1-mesa-glx 	&& rm -rf /var/lib/apt/lists/* 	&& git lfs install
CACHED
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @HaoHoo - opened a PR to your space to fix this. https://huggingface.co/spaces/haohoo/Azure-OpenAI-QuickDemo/discussions/1

**Comment by HaoHoo** [comment]
Thank you and I‘ve merged the request file to the App. I need to study gradio_client for Python now.
