### ISSUE TITLE
show_api = false didn't work

### ISSUE THREAD

**Issue by ToviHe** [gradio-app/gradio#5203]
### Describe the bug

I wrote an interactive interface for Gradio, and found that when adding `?view=api` to the suffix of the interactive link, you can view the API information of the current Gradio application. **I don’t want to display this API information**. You can get it from the official website [https://www.gradio.app/guides/sharing-your-app](url) by setting `show_api = false` worked, but ultimately didn't work。

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

`import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
    
demo.launch(server_port=7861,show_api=False)  `

### Screenshot

<img width="1389" alt="image" src="https://github.com/gradio-app/gradio/assets/109323790/4dbf7917-12e4-4b44-a8fb-5ba591b5af98">

<img width="707" alt="image" src="https://github.com/gradio-app/gradio/assets/109323790/3af59a39-5990-4d49-9376-5925f03450d8">

### System Info

```shell
gradio                    3.39.0
gradio_client             0.3.0
```

### Severity

Blocking usage of gradio

**Comment by ToviHe** [comment]
How can I not display the API information of my gradio? This function is for customers, we don't want customers to directly access our interface, which is very important

**Comment by freddyaboulton** [comment]
Hi @ToviHe, if you are using the `gr.Blocks()` api, whenever you define an event you can pass `api_name=False` to hide that route from the api info page. It's currently not possible to do that with `gr.Interface` but we can fix that.

**Comment by ToviHe** [comment]
> I think what @ToviHe is saying here is that even when we set `show_api=False`, one can access the API page using the query parameter:
> 
> ```
> http://127.0.0.1:7892/?view=api
> ```
> 
> We should fix this bug. (@freddyaboulton agreed we should also provide a way to disable the API endpoint for Interface but I think that's separate from @ToviHe is asking)

Thank you both, I set  `api_name=False` to `gr.Blocks()` locally by using the method recommended by @freddyaboulton , and it seems that the API can no longer be displayed.
<img width="1382" alt="image" src="https://github.com/gradio-app/gradio/assets/109323790/373f3640-0d21-4bef-88f1-f15579a3050a">
By the way, what version will the `show_api=False` function be fixed in? Thanks
