### ISSUE TITLE
Converting the website demos tab into an interactive playground

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#5214]
Embed the demos on the demos tab of the website using [gradio lite](https://www.npmjs.com/package/@gradio/lite) so that changes to the code show up in the demo. Will not work on all the demos but we can expand as we fix issues with the library. Ideally will eventually serve as a tutorial playground on the website.

**Comment by abidlabs** [comment]
Amazing that we have this now! https://www.gradio.app/playground
