### ISSUE TITLE
Gradio not deploying my nested application file to hugging face

### ISSUE THREAD

**Issue by deepak0405** [gradio-app/gradio#5225]
### Describe the bug

I am trying to update my gradio app in hugging face by specifying a different custom app file.

I am using the command

 gradio deploy --app-file ./interview/app.py
 
to deploy the app.

But my hugging face space is not able to find the application file. Even though it is present in the nested directory. How can I fix this issue ?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

1. Create an space with the app.py file.
2. Delete the hugging face space.
3. Create a new space specifying the new app.py file.

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/25735175/97d6b41d-fe4e-49ed-b55a-ef305e2bc2de)
![image](https://github.com/gradio-app/gradio/assets/25735175/66189d96-1d36-4d06-9460-da1ebb856e2c)

### System Info

```shell
gradio version:  3.39.0
```

### Severity

I can work around it

**Comment by pngwn** [comment]
Can you show the contents of your `README.md` please?

**Comment by pngwn** [comment]
Its okay I found it:

```markdown
title: Code_Round
app_file: app.py
sdk: gradio
sdk_version: 3.39.0
```

@freddyaboulton @aliabid94 @abidlabs 

It seems that we aren't writing the correct app file path to the `README.md` when generating the artifacts.

**Comment by deepak0405** [comment]
Thanks for such a quick response!

I have manually changed the readme and it works fine now

**Comment by freddyaboulton** [comment]
Thanks @pngwn ! Should be a quick fix

**Comment by abidlabs** [comment]
Just confirmed that this is no longer an issue, thanks folks!
