### ISSUE TITLE
Dynamically mount a Gradio `Block` from within a FastAPI function

### ISSUE THREAD

**Issue by Bojun-Feng** [gradio-app/gradio#5228]
### Describe the bug

Description: When launched dynamically as a sub app via FastAPI, queued Gradio application loads successfully but is not interactive.

The same issue is discussed in [this HuggingFace Post](https://discuss.huggingface.co/t/dynamically-mount-a-gradio-block-from-within-a-fastapi-function/48983), but it is not addressed as of the creation of this issue.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Minimal reproduction:

1. Create file named `fastapi_gradio.py` with the following content:
<details><summary>See Code</summary>

```
from fastapi import APIRouter, FastAPI, HTTPException, Request
import uvicorn

app = FastAPI()

@app.get('/test')
def balabala():
    import gradio as gr

    with gr.Blocks() as demo:
        chatbot = gr.Chatbot()
        msg = gr.Textbox()
        clear = gr.Button("Clear")

        def user(user_message, history):
            return "", history + [[user_message, None]]

        def bot(history):
            bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
            history[-1][1] = ""
            for character in bot_message:
                history[-1][1] += character
                time.sleep(0.05)
                yield history

        msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
            bot, chatbot, chatbot
        )
        clear.click(lambda: None, None, chatbot, queue=False)

    global app 
    demo.queue()
    app = gr.mount_gradio_app(app, demo, f'/gradio')
```
</details>

2. Open a terminal window and run `uvicorn fastapi_gradio:app` in the same directory as `fastapi_gradio.py`
<details open><summary>Expected Output</summary>

```
INFO:     Started server process [49857]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```
</details>

4.  Keep track of the endpoint (in the above example it is `http://127.0.0.1:8000`) and run `curl [endpoint]/test` (e.g. `curl http://127.0.0.1:8000/test`) in a new terminal window.

6. Finally, open `[endpoint]/gradio` (e.g. `http://127.0.0.1:8000/gradio`) in your web browser and there should be a broken chatbot. There are no errors but the chatbot simply does not respond.

### System Info

```shell
Gradio Environment Information:
Operating System:  Darwin


gradio version:  3.39.0

gradio Dependencies:
  aiofiles: 22.1.0
  aiohttp: 3.8.3
  altair: 5.0.1
  fastapi: 0.100.0
  ffmpy: 0.3.0
  gradio-client: 0.3.0
  httpx: 0.24.1
  huggingface-hub: 0.15.1
  jinja2: 3.1.2
  markdown-it-py: 2.2.0
  markupsafe: 2.1.1
  matplotlib: 3.7.1
  mdit-py-plugins: 0.3.0
  numpy: 1.24.3
  orjson: 3.9.2
  packaging: 23.0
  pandas: 1.5.3
  pillow: 9.4.0
  pydantic: 1.10.12
  pydub: 0.25.1
  python-multipart: 0.0.6
  pyyaml: 6.0
  requests: 2.29.0
  semantic-version: 2.10.0
  typing-extensions: 4.6.3
  uvicorn: 0.22.0
  websockets: 11.0.3


gradio_client version:  0.3.0

gradio_client Dependencies:
  fsspec: 2023.4.0
  httpx: 0.24.1
  huggingface-hub: 0.15.1
  packaging: 23.0
  requests: 2.29.0
  typing-extensions: 4.6.3
  websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by NickyDark1** [comment]
work, but how to protect the router?

**Comment by freddyaboulton** [comment]
Going to close!
