### ISSUE TITLE
new DataFrame are interactive even if shouldn't be

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#5236]
### Describe the bug

Ever since upgrading to gradio==3.40.1 from gradio==3.39.0, dataframes shows add row/column and one can change the dataframe, even though interactive=False

Related issues:
https://github.com/gradio-app/gradio/issues/5182
https://github.com/gradio-app/gradio/pull/5183

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr


def filter_records(records, gender):
    return records[records["gender"] == gender]


demo = gr.Interface(
    filter_records,
    [
        gr.Dataframe(
            headers=["name", "age", "gender"],
            datatype=["str", "number", "str"],
            row_count=5,
            col_count=3,
            interactive=False,
        ),
        gr.Dropdown(["M", "F", "O"]),
    ],
    "dataframe",
    description="Enter gender as 'M', 'F', or 'O' for other.",
)

if __name__ == "__main__":
    demo.launch()

```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/2249614/c2ba8a56-3d6c-4545-b4c8-426a52a5fa6d)

In https://github.com/gradio-app/gradio/issues/5237 you can see how in 3.39.0 the add row-column thing is not present, there is no way to change the frame in the UI as is correct when interactive=False

### System Info

```shell
gradio 3.40.1

I work around by downgrading gradio back to 3.39.0
```

### Severity

I can work around it

**Comment by pseudotensor** [comment]
Also, it used to just listen to the column names, not have to pass separate "headers" which is hassle.

**Comment by abidlabs** [comment]
Interesting, will take a look.

**Comment by abidlabs** [comment]
Unfortunate regression, but can confirm that this is now fixed on `main`: 

<img width="763" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/836150dc-b14b-4ff8-9d53-c8ebd8a33602">

I'll add some visual tests in a separate PR
