### ISSUE TITLE
insert image in gradio next to a text.

### ISSUE THREAD

**Issue by AbubakrChan** [gradio-app/gradio#5239]
Here is a the part of code of mine:

with gr.Blocks() as app2:
    gr.HTML("img src="image link" alt="A beautiful landscape")    #("<>" left intentionally)
.....................

output:
![image](https://github.com/gradio-app/gradio/assets/89600478/6fcd84a9-0e7d-4d06-b7b1-127efc0060d5)

How can i make these images display?

Thanks

**Comment by abidlabs** [comment]
Hi @AbubakrChan, for general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)

**Comment by umarbutler** [comment]
+1

**Comment by umarbutler** [comment]
@abidlabs Can we reopen this. This should have been a feature request.

**Comment by abidlabs** [comment]
If the question is how do you do display image next to text in `gr.HTML()`, that is not a feature request, but rather a question of how to do something like that in HTML/CSS, you can do many different approaches, such as:

```html
<div style="display: flex; align-items: center;">
  <img src="image.jpg" alt="Description" style="width: 100px; height: auto; margin-right: 10px;">
  <p>Your text goes here.</p>
</div>

```

**Comment by umarbutler** [comment]
That’s the solution I used, however, I think it should be a feature request @abidlabs. It’s a pretty common need, ie, have your logo next to the title of the demo, to justify creating it.

**Comment by abidlabs** [comment]
Ah I see, feel free to create a separate issue outlining the feature request.
