### ISSUE TITLE
gr.CheckboxGroup.update(choices=..) not working as expected

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#5251]
### Describe the bug

This only happens on main and I believe it's because of the recent tuple addition in #5232

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr 

choices = ["First Choice", "Second Choice", "Third Choice"]
with gr.Blocks() as demo:
    chx = gr.CheckboxGroup(choices=choices, interactive=True)
    btn = gr.Button(value="Select All")
    btn.click(lambda: gr.CheckboxGroup.update(choices=["first", "second"]), None, chx)

demo.launch()
```

### Screenshot

After clicking the button

<img width="1301" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/874fd613-1e22-4dfe-b788-83269f22b3b3">

### System Info

```shell
main
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
ah yeah okay I know the issue -- thanks for flagging @freddyaboulton

**Comment by Ritvik19** [comment]
I'm getting:

AttributeError: type object 'CheckboxGroup' has no attribute 'update'
