### ISSUE TITLE
Be able to add tips to our docs

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#5269]
- [ ] I have searched to see if a similar issue already exists.

The HF libraries have really useful warning sections in their docs that are really easy for users to see.

Example:
<img width="951" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/9d29f47a-6646-48bb-ac69-d047f937e1f5">

The way this works is by adding <Tip warning={true}> to the docs. See [here](https://github.com/huggingface/huggingface_hub/blame/main/docs/source/guides/search.md#L80). This gets converted to a svelte component.

Would be really cool to have that in our docs and guides as well.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by aliabd** [comment]
I like this a lot. Do you think it makes sense to add this as a key in the docstrings? (Similar to `Demos: hello_world`) and if a warning is added to the docstrings it shows up like this? 

<img width="1293" alt="Screen Shot 2023-08-18 at 11 43 17 PM" src="https://github.com/gradio-app/gradio/assets/9021060/c7e56b27-1565-4f2a-aa36-eb48f9c1f7e2">

**Comment by freddyaboulton** [comment]
I think that it would work for docstrings! I think we need some sort of special syntax for the guides?, e.g. "```warning", because the warning could be displayed anywhere throughout the content. If that's the case, we should use the same for both the guides and the docstrings.

**Comment by abidlabs** [comment]
I see this as more useful than guides (where it helps highlight important bits in the overall text) than docstrings imo. Much simpler to create a new syntax for guides too.

**Comment by freddyaboulton** [comment]
Done by @aliabd in the v4 branch!

**Comment by freddyaboulton** [comment]
![local_trace_viewer](https://github.com/gradio-app/gradio/assets/41651716/31ed5fa8-e1d9-43a0-9757-469905678683)
