### ISSUE TITLE
Progress - refresh/change  text with each update

### ISSUE THREAD

**Issue by C0untFloyd** [gradio-app/gradio#5272]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

Gradio Progress allows wrapping tqdm which is great! However there's no way to have the description text change with each update, not even with the standard gradio progress I assume. This is possible in tqdm in multiple ways, either using set_postfix or set_description with refresh. 

**Describe the solution you'd like**  

Just the ability to dynamically change the progress text

**Additional context**  

Context: I'm displaying VRAM allocation and frames per second each frame processed.

**Comment by abidlabs** [comment]
This is possible @C0untFloyd using the `desc` parameter of `gr.Progress`. Please see here: https://www.gradio.app/docs/progress

**Comment by C0untFloyd** [comment]
Thank you for answering, I take it it's only possible by directly using gr.Progress but not with the tqdm wrapper then?

**Comment by abidlabs** [comment]
I haven't tested with the tqdm wrapper -- can you please provide the code snippet that you've been testing?

**Comment by C0untFloyd** [comment]
This is passing through multiple .py files and functions meaning it's too complex to show. However I worked around it by displaying just basic steps in the gradio progress and detailed infos in the console output. Thanks for trying to help, this can be closed then.
