### ISSUE TITLE
Missing docstring for `HighlightedText.color_map`

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#5277]
### Describe the bug

Missing a docstring here: https://www.gradio.app/docs/highlightedtext

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://www.gradio.app/docs/highlightedtext

### System Info

```shell
N/A
```

### Severity

I can work around it

**Comment by aliabd** [comment]
@abidlabs is this still an issue? Can't tell

**Comment by abidlabs** [comment]
Yes, there's no docstring for `color_map` here:

<img width="903" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/8b0f98aa-b85c-4d42-84c3-c8d036db3e98">
