### ISSUE TITLE
Password authentication does not work!

### ISSUE THREAD

**Issue by p0mad** [gradio-app/gradio#5278]
### Describe the bug

Hi, I'm using Collab to test the Gradio

after 
using auth parameter in demo.launch()
the login page appears, but after putting correct user and pass into the login page, it takes a few seconds after white screen and it then gets back to the same login page!

No matter how many times you try, but it wont login!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Authentication
Password-protected app
You may wish to put an authentication page in front of your app to limit who can open your app. With the auth= keyword argument in the launch() method, you can provide a tuple with a username and password, or a list of acceptable username/password tuples; Here’s an example that provides password-based authentication for a single user named “admin”:

demo.launch(auth=("admin", "pass1234"))
For more complex authentication handling, you can even pass a function that takes a username and password as arguments, and returns True to allow authentication, False otherwise. This can be used for, among other things, making requests to 3rd-party authentication services.

    text_button.click(flip_text, inputs=text_input, outputs=text_output)
    image_button.click(flip_image, inputs=text_input, outputs=image_output)

demo.launch(auth=("admin", "pass1234"))

### System Info

```shell
I'm using google collab
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @p0mad thanks -- we already have this issue here: https://github.com/gradio-app/gradio/issues/4103, please follow that issue for updates.
