### ISSUE TITLE
Unable to remove orange border around  block.load() using show_progress=False

### ISSUE THREAD

**Issue by zoedesimone** [gradio-app/gradio#5282]
### Describe the bug

When loading blocks, show_progress=False does not hide the orange border around the component. Would apprecieate any css workaround to hide the orange border in the meantime, if possible. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
with gr.Blocks().queue() as left_gallery:
  gallery_img_left = gr.Gallery(
              label="Generated images", show_label=False, elem_id="gallery"
          ).style(columns=[5], rows=[1], object_fit='scale-down', height="auto")

  left_gallery.load(fn=load_imgs_baseline, inputs= None, outputs=gallery_img_left,
                show_progress=False, every=10)

left_gallery.launch(debug = False)
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/56321398/bc9754e7-4623-44bd-9616-71843d69671e)

### System Info

```shell
pip installing gradio in colab on 8/21/23
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @zoedesimone please see this duplicate issue: https://github.com/gradio-app/gradio/issues/4838 including a css workaround

**Comment by zoedesimone** [comment]
thanks! workaround works. let me know when it's fixed in the gradio component itself.
