### ISSUE TITLE
Is it possible to modify the gr.Interface API to add more components and set their listener functions?

### ISSUE THREAD

**Issue by HaozheZhao** [gradio-app/gradio#5287]
- [√ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Is it possible to modify the gr.Interface API to add more components and set their listener functions? I am currently launching a demo using Gradio, but I have encountered a problem. I need to upload multiple images and select some of them to display in the gallery component. I want to achieve this by using the select function. However, I am unable to modify the action listener function when using the gr.Interface API. Creating my own gr.Block from scratch seems like an excessive amount of effort.

**Describe the solution you'd like**  
So i wonder is it possible to modify the  gr.Interface api to add more components and set their listener function?

**Comment by abidlabs** [comment]
Hi @HaozheZhao we generally recommend the Blocks API for something like this. Note that you can also put an `Interface` inside of a `Blocks` if you are making additions to an Interface. Here's a simple example for illustrative purposes:

```py
import gradio as gr

def show_selected(s: gr.SelectData):
    return s.index

with gr.Blocks() as demo:
    image = gr.Image(render=False)
    gallery = gr.Gallery(render=False)
    
    with gr.Row():
        gr.Interface(lambda x: [x, x, x], image, gallery)
        textbox = gr.Textbox()
        
    gallery.select(show_selected, None, textbox)
demo.launch()
```

By the way, for general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
