### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'Info'

### ISSUE THREAD

**Issue by so2liu** [gradio-app/gradio#5288]
### Describe the bug

I want to give user a message. In document there are helpers about Info, Warning, Error, but in lib there is only Error.

### Have you searched existing issues?  🔎

- [X] #5291

### Reproduction

```
import gradio as gr


def load_model(name: str):
   gr.Info("Loading model...")

with gr.Blocks() as FastUI:
    model_name = gr.Textbox(lines=1, label="Model Name")
    load_model_output = gr.Textbox()
    load_model_btn = gr.Button("Load Model")
    load_model_btn.click(load_model, inputs=model_name)

FastUI.launch()
```

### System Info

```shell
gradio                                            3.35.2
```

### Severity

Blocking usage of gradio

**Comment by so2liu** [comment]
it works, sorry it's my bad

**Comment by shubhankg-nd** [comment]
How can i achieve the same gradio app mounted on FASTAPI?
Sample problem question here: https://stackoverflow.com/questions/77192757/gradio-pop-up-display-on-success
