### ISSUE TITLE
Sliders are static when value is not used

### ISSUE THREAD

**Issue by pcschreiber1** [gradio-app/gradio#5293]
### Describe the bug

Using gradio.Blocks() slider components are static when their values are not being used. If this is a desired feature it should be explained in the Docs.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```Python
import gradio as gr

def func(slider_1, slider_2):
    return slider_1 * 5 + slider_2

with gr.Blocks() as demo:
    slider = gr.Slider(minimum=-10.2, maximum=15, label="Random Slider (Static)", randomize=True)
    slider_1 = gr.Slider(value=101, minimum=100, maximum=200, label="Random Slider (Input 1)")
    slider_2 = gr.Slider(minimum=10, maximum=23.2, label="Random Slider (Input 2)", randomize=True)
    slider_3 = gr.Slider(value=1, label="Non random slider")
    btn = gr.Button("Run")
    btn.click(func, inputs=[slider_1, slider_2], outputs=gr.Number())

demo.launch()
```

Now, here the fourth slider is no longer static
```Python
import gradio as gr

def func(slider_1, slider_2, slider_3):
    return slider_1 * 5 + slider_2 - slider_3

with gr.Blocks() as demo:
    slider = gr.Slider(minimum=-10.2, maximum=15, label="Random Slider (Static)", randomize=True)
    slider_1 = gr.Slider(value=101, minimum=100, maximum=200, label="Random Slider (Input 1)")
    slider_2 = gr.Slider(minimum=10, maximum=23.2, label="Random Slider (Input 2)", randomize=True)
    slider_3 = gr.Slider(value=1, label="Non random slider")
    btn = gr.Button("Run")
    btn.click(func, inputs=[slider_1, slider_2, slider_3], outputs=gr.Number())

demo.launch()
```

### Screenshot

As you can see, the first and last slider are static.

![image](https://github.com/gradio-app/gradio/assets/82368796/9ee3301c-6b78-4a81-8067-7b28e4c45e4f)

Here, with the second code snippet, the fourth slider is active

![image](https://github.com/gradio-app/gradio/assets/82368796/72edb9cf-6e81-4d1f-9831-3df0c1411129)

### System Info

```shell
Chrome, WSL2
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @pcschreiber1 !

Yes that is by design. Components are not assumed to be interactive, unless they are used as inputs in an event. You can always override this by setting the `interactive` parameter yourself.

This is explained here: https://www.gradio.app/guides/blocks-and-event-listeners#event-listeners-and-interactivity

**Comment by pcschreiber1** [comment]
I see, thank's a lot for the super quick response and the great package! :)
