### ISSUE TITLE
Image display is slow

### ISSUE THREAD

**Issue by ydshieh** [gradio-app/gradio#5294]
### Describe the bug

With a very simple demo of just showing the selected image in another Image component, each time it takes > 2 seconds  to switch of image displaying.

I am testing with running the demo on a GCP VM + view results lcoally.

The 3 images are of size in the scale of `1024 x 768`

See `Reproduction` section.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

[Colab](https://colab.research.google.com/drive/1cUMAlcxBbZZUgGXkDREJPGrqGrApAyHA?usp=sharing)

(running on Colab)
```bash
!pip install -q gradio 

!wget https://huggingface.co/spaces/ydshieh/Kosmos-2/resolve/main/images/man_ball.png
!wget https://huggingface.co/spaces/ydshieh/Kosmos-2/resolve/main/images/snowman.png
!wget https://huggingface.co/spaces/ydshieh/Kosmos-2/resolve/main/images/two_dogs.jpg
```

demo
```python
import gradio as gr

def main():

    def generate_predictions(image_input, text_input):
        return image_input

    with gr.Blocks(title="Kosmos-2", theme=gr.themes.Base()).queue() as demo:

        with gr.Row():
            with gr.Column():
                image_input = gr.Image(type="pil", label="Test Image")
                run_button = gr.Button(label="Run", visible=True)

            with gr.Column():
                image_output = gr.Image(type="pil")

        with gr.Row():
            with gr.Column():
                gr.Examples(examples=[
                    ["two_dogs.jpg"],
                    ["snowman.png"],
                    ["man_ball.png"],
                ], inputs=[image_input]
            )

        run_button.click(fn=generate_predictions,
            inputs=[image_input],
            outputs=[image_output],
        )

    demo.launch(share=True)

if __name__ == "__main__":
    main()
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 3.40.1
gradio_client version: 0.4.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
aiohttp: 3.8.5
altair: 4.2.2
fastapi: 0.101.1
ffmpy: 0.3.1
gradio-client: 0.4.0
httpx: 0.24.1
huggingface-hub: 0.16.4
importlib-resources: 6.0.1
jinja2: 3.1.2
markdown-it-py: 2.2.0
markupsafe: 2.1.3
matplotlib: 3.7.1
mdit-py-plugins: 0.3.3
numpy: 1.23.5
orjson: 3.9.5
packaging: 23.1
pandas: 1.5.3
pillow: 9.4.0
pydantic: 2.2.0
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.7.1
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.24.1
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Otherwise I can't reproduce this issue just running this code locally:

```py
import gradio as gr


def generate_predictions(image_input, text_input):
    return image_input

with gr.Blocks(title="Kosmos-2", theme=gr.themes.Base()).queue() as demo:

    with gr.Row():
        with gr.Column():
            image_input = gr.Image(type="pil", label="Test Image")
            run_button = gr.Button(label="Run", visible=True)

        with gr.Column():
            image_output = gr.Image(type="pil")

    with gr.Row():
        with gr.Column():
            gr.Examples(examples=[
                ["cheetah.jpg"],
            ], inputs=[image_input]
        )

    run_button.click(fn=generate_predictions,
        inputs=[image_input],
        outputs=[image_output],
    )

demo.launch()
```

**Comment by ydshieh** [comment]
Yes, I intend to test the case like I am a user of a demo on Spaces, so I am running the demo on GCP + VM with `share=True` and viewing the results on my local machine.

For a Spaces demo, I have to set `share=False`, but the result is like the one from the setting mentioned above.

**Comment by ydshieh** [comment]
Just to provide my motivation: Suppose I have a `HighlightedText` and an image showing their bounding boxes:
<img src="https://github.com/gradio-app/gradio/assets/2521628/9416b438-2ba9-4549-8b89-8a2ca10573f6" width=50% height=50%>
<img width="548" alt="Screenshot 2023-08-23 075425xxx" src="https://github.com/gradio-app/gradio/assets/2521628/0f873059-8d8c-4694-8de4-dc8aa86774cf">

It would be nice to click one of the highlighted span and showing its bounding boxes but not other, like

<img src="https://github.com/gradio-app/gradio/assets/2521628/254f0f1e-e5bc-487f-b208-05d4e44487aa" width=50% height=50%>
<img src="https://github.com/gradio-app/gradio/assets/2521628/6e039696-ef70-4ee5-aef6-e83c2b230df8" width=50% height=50%>
<img src="https://github.com/gradio-app/gradio/assets/2521628/3fe26b45-d354-430f-9372-56370ea31612" width=50% height=50%>
<img src="https://github.com/gradio-app/gradio/assets/2521628/be49f277-1364-42ec-9c45-799b62e8487b" width=50% height=50%>

However, it would be better if this switch could be as fast as possible.

**Comment by abidlabs** [comment]
@ydshieh I would not use `share=True` to simulate a HF Spaces environment. The reason being that the Gradio share server is handling 1000s of TCP connections at the same time. 

Why not just test on Spaces directly? I built a simple Space here: https://huggingface.co/spaces/abidlabs/test-image-simple

and it runs for me in about ~0.5 seconds. We might be able to shave off a little more when we avoid the base64 serialization, but I don't think we can get much faster than that.

**Comment by ydshieh** [comment]
Thanks for a simple Spaces demo. On my [Kosmos-2](https://huggingface.co/spaces/ydshieh/Kosmos-2) demo, I see things a bit slower, but it's likely I am chaining some events (click a highlighted span + check if select is changed + display new image if necessary), so it becomes slower than this simple demo.

I am going to close this issue. thanks again!.
