### ISSUE TITLE
Add support for `gr.Request` and other special typed parameters to `gr.ChatInterface`

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#5297]
Currently, doing something like:

```py
import gradio as gr

def example(x, y, request: gr.Request):
    print(request)
    return x

gr.ChatInterface(example).launch()
```

does not work and in fact raises an error. We should add support, as requested here: https://github.com/gradio-app/gradio/issues/4410#issuecomment-1688927278

**Comment by DarhkVoyd** [comment]
@abidlabs Kindly assign this issue to me, I would like to help with this. Any suggestion or pointers to where I should start?

**Comment by abidlabs** [comment]
Hi @DarhkVoyd we don't formally assign issues to contributors, feel free to open PRs for any issues that don't already have PRs. 

In terms of where to start, I'd recommend looking at the error when you run the example above. You'll see it points to this part of the codebase:

https://github.com/gradio-app/gradio/blob/6b8c8afd981fea984da568e9a0bd8bfc2a9c06c4/gradio/chat_interface.py#L403

The problem is that the `_submit_fn` doesn't get the `gr.Request`. We should add a parameter to `_submit_fn` that is typed as `gr.Request` and then pass it into `self.fn` if it has such a typed parameter.

**Comment by davies-w** [comment]
I need this ASAP please!
