### ISSUE TITLE
Interfaces not showing inline in colab notebook

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#53]
When I run the demo notebook (https://colab.research.google.com/drive/1BAw8QGFNqeKf1V0E3TLCzWyV6NM_qv_i?authuser=1#scrollTo=od6vQzqDGKoJ) here in colab notebook, I often get this issue:

![image](https://user-images.githubusercontent.com/1778297/93512181-8de6c100-f8e9-11ea-8bfa-c6da99a7fa0d.png)

**Comment by samarth70** [comment]
Yes, I also faced the same issue.

**Comment by samarth70** [comment]
Found it! Use the Colab snippet.

display.Javascript to execute JavaScript from Python
It got resolved for me.
