### ISSUE TITLE
Audio component not recording from microphone

### ISSUE THREAD

**Issue by KushRJ** [gradio-app/gradio#5301]
### Describe the bug

I am using the audio component in this format:
inputs=gr.Audio(source="microphone", type="filepath", label="Record Audio"),

But I am unable to record any file via my microphone, as the 'Stop Recording' button doesn't work after I start recording. 

Versions:
gradio==3.40.0
gradio_client==0.4.0
Python 3.10.6

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Please fix this ASAP as I am unable to record audio input

### Screenshot

How do I fix this?

### Logs

```shell
No Logs
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 3.40.0
gradio_client version: 0.4.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.1.0
aiohttp: 3.8.4
altair: 5.0.1
fastapi: 0.100.1
ffmpy: 0.3.1
gradio-client: 0.4.0
httpx: 0.13.3
huggingface-hub: 0.16.4
importlib-resources: 6.0.0
jinja2: 3.1.2
markdown-it-py: 2.2.0
markupsafe: 2.1.3
matplotlib: 3.7.2
mdit-py-plugins: 0.3.3
numpy: 1.24.3
orjson: 3.9.2
packaging: 22.0
pandas: 2.0.3
pillow: 9.5.0
pydantic: 1.10.11
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.7.1
uvicorn: 0.15.0
websockets: 10.4
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.13.3
huggingface-hub: 0.16.4
packaging: 22.0
requests: 2.31.0
typing-extensions: 4.7.1
websockets: 10.4
```

### Severity

Blocking usage of gradio

**Comment by KushRJ** [comment]
@hysts My code:

`demo = gr.Interface(fn=transcribe,
                    inputs=gr.Audio(source="microphone", type="filepath", label="Record Audio"),
                    outputs=gr.Textbox(label="Transcription"))
                    
  demo.queue().launch(share=True, server_port = 5008, server_name='0.0.0.0')`
  

https://github.com/gradio-app/gradio/assets/29791487/6f5a10cd-7bfa-4b24-86d1-129b5dd6765e


  Screen recording of the app where its visible that microphone is not recording attached (I have used the Audio component in the same way it is used in the huggingface space attached by you).

**Comment by hysts** [comment]
Hmm, it works fine for me.

https://github.com/gradio-app/gradio/assets/25161192/3932e8c5-3f66-466b-a281-06fa9df69e0f

Maybe it has something to do with your browser or OS.

**Comment by KushRJ** [comment]
I am using Brave Browser and a Linux system. Is there any explicit environment variable I need to set for Gradio to use the microphone (the tab doesn't ask for permission to use the microphone, so I thought it has access to the same by default.)

**Comment by abidlabs** [comment]
@KushRJ could it be this issue? https://github.com/gradio-app/gradio/issues/2551

**Comment by abidlabs** [comment]
Will close for lack of followup -- and instead add #2551 to the milestone and tracking issue.
