### ISSUE TITLE
Change image size using html in ChatBot bubble not work.

### ISSUE THREAD

**Issue by MrGreyfun** [gradio-app/gradio#5322]
### Describe the bug

In my case, the default image size in the message bubble of ChatBot is too small. I tried to enlarge the image, but there is not parameters for that setting. I then tried to use html to show and resize the image. But no matter how I set the `height` attribute, it just not work, and the `width` attribute can only widen the image a little bit. 

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

Please see the screenshot.

### Screenshot

![1](https://github.com/gradio-app/gradio/assets/72959013/68016f52-33fb-4933-8191-fe1956216159)
![2](https://github.com/gradio-app/gradio/assets/72959013/65f559c7-13d4-4bb7-a41d-03a478b73469)

### System Info

```shell
Windows 10
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @MrGreyfun there is a `max-width` and a `max-height` applied to these images. If you'd like to change the width of the images, you'd have to set these to none. Here's an example:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Chatbot([
        ("Regular image", "<img src='/file=cheetah.jpg'></img>"),
        ("Big image", "<img src='/file=cheetah.jpg' style='width: 600px; max-width:none; max-height:none'></img>"),
    ])
    
demo.launch()
```

**Comment by ApoorvFrontera** [comment]
@abidlabs Hey. I am not able to get this working. The picture is not rendered at all when I use the above format.

![image](https://github.com/gradio-app/gradio/assets/158158088/a4fe4aad-3817-4e49-a250-d5ed5029dd68)

 I am currently using this format to show the images. How can I modify the image size inside the chatbot in the following snippet?

```
import gradio as gr

with gr.Blocks() as demo:
    gr.Chatbot(value=[
        ["Regular image", ( "./image_repo/instruction_card/tooth-brushing.png", None)],
    ],
    )
    
demo.launch()
```
