### ISSUE TITLE
Checkbox select handler crashes

### ISSUE THREAD

**Issue by C0untFloyd** [gradio-app/gradio#5327]
### Describe the bug

Gradio v3.41.0 is crashing when a select handler is attached to a checkbox. This didn't happen with 3.38.0 and earlier
The same happened in v3.40.x with dropdown select handlers which seems to be fixed though.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

`# within bigger blocks layout`
`chk_det_size = gr.Checkbox(label="Use default Det-Size", value=True, elem_id='default_det_size', interactive=True)`

`# later setting the handler`
`chk_det_size.select(fn=on_option_changed)`

`# on_option_changed is never reached instead the error below is happening`

### Logs

```shell
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\v0idr\miniconda3\envs\roop-unleashed\Lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\v0idr\miniconda3\envs\roop-unleashed\Lib\site-packages\gradio\blocks.py", line 1435, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\v0idr\miniconda3\envs\roop-unleashed\Lib\site-packages\gradio\blocks.py", line 1091, in call_function
    processed_input, progress_index, _ = special_args(
                                         ^^^^^^^^^^^^^
  File "C:\Users\v0idr\miniconda3\envs\roop-unleashed\Lib\site-packages\gradio\helpers.py", line 769, in special_args
    inputs.insert(i, type_hint(event_data.target, event_data._data))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\v0idr\miniconda3\envs\roop-unleashed\Lib\site-packages\gradio\events.py", line 337, in __init__
    self.index: int | tuple[int, int] = data["index"]
                                        ~~~~^^^^^^^^^
```

### System Info

```shell
Windows 10
Python 3.11.4
Gradio v3.41.0
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @C0untFloyd ! I can't repro this on 3.41.1 (got released a couple of hours ago).

```python
import gradio as gr 

with gr.Blocks() as demo:
    chx = gr.Checkbox()
    text = gr.Textbox()
    chx.select(lambda s: s, chx, text)

demo.launch()
```

![checkbox_select](https://github.com/gradio-app/gradio/assets/41651716/8c4d914b-aa20-4334-8aff-68c7af6ec542)

**Comment by C0untFloyd** [comment]
Still crashing with 3.41.1, your example works though. I did some debugging and it seems to be caused by using gr.SelectData in the handling function:

```
def on_option_changed(evt: gr.SelectData):
    attribname = evt.target.elem_id
    if isinstance(evt.target, gr.Checkbox):
        if hasattr(roop.globals, attribname):
            setattr(roop.globals, attribname, evt.selected)
            return
    elif isinstance(evt.target, gr.Dropdown):
        if hasattr(roop.globals, attribname):
            setattr(roop.globals, attribname, evt.value)
            return
    raise gr.Error(f'Unhandled Setting for {evt.target}')
```

Called from
chk_det_size.select(fn=on_option_changed)

**Comment by freddyaboulton** [comment]
Ok I think I see the issue! Thanks @C0untFloyd
