### ISSUE TITLE
Normalizing label output

### ISSUE THREAD

**Issue by yusyel** [gradio-app/gradio#5335]
### Describe the bug

I'm using same function for prediction. One of predictions look like in screenshoot.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
def predict(img):
    img = preprocess_image(img)
    pred = model.predict(img)
    print(pred)
    pred = np.round(np.squeeze(pred).astype(float),5)
    print(pred)
    return dict(zip(class_names, pred))
```

pred func.

### Screenshot

![a](https://github.com/gradio-app/gradio/assets/25446622/5af28e57-0030-45fd-8f6a-a77c3f5b2882)

### Logs

```shell
[[ 2.385442  -3.9095798  3.484814  -4.6832724 -5.055411  -1.1809365
  -3.0611944 -2.108893  -5.3167543  6.1814203]]
[ 2.38544 -3.90958  3.48481 -4.68327 -5.05541 -1.18094 -3.06119 -2.10889
 -5.31675  6.18142]
```

### System Info

```shell
Huggingface space and local space using latest gradio 3.41.0.
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
I think gradio should actually stay out of the way here and simply display the data the user returns from the label. You can scale this yourself with a logsumexp!
