### ISSUE TITLE
Gradio API generated example calls not commented correctly

### ISSUE THREAD

**Issue by taoari** [gradio-app/gradio#5336]
### Describe the bug

For example, the following is auto-generated as an example for gradio API call. However, the code is not directly runnable, one has to manually comment out the following two lines

```
in 'Temperature' Slider component
in 'Max new tokens' Slider component
```

In order to run. It would be great if the generated examples APIs are directly runnable.

```python
from gradio_client import Client

client = Client("http://localhost:7860/")
result = client.predict(
				"Howdy!",	# str in 'parameter_18' Textbox component
				"Auto",	# str in 'Chat engine' Radio component
				0,	# int | float (numeric value between 0 and 1)
								in 'Temperature' Slider component
				0,	# int | float (numeric value between 0 and 1024)
								in 'Max new tokens' Slider component
				api_name="/chat"
)
print(result)
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import random
import gradio as gr

def random_response(message, history):
    return random.choice(["Yes", "No"])

params = [gr.Slider(minimum=0, maximum=1, value=0.7, step=0.1, interactive=True, label="Temperature",
            info="Lower temperator for determined output; hight temperate for randomness"),
    gr.Slider(minimum=0, maximum=1024, value=512, step=64, interactive=True, label="Max new tokens"),]
demo = gr.ChatInterface(random_response, additional_inputs=params)

if __name__ == "__main__":
    demo.launch()

### Screenshot

<img width="1123" alt="Screenshot 2023-08-24 at 4 03 18 PM" src="https://github.com/gradio-app/gradio/assets/3815006/4465f8d1-bcc7-414d-9829-d5cee29c7671">

### System Info

```shell
Windows 11
gradio                  3.41.1
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Good point @taoari! I see this as well.

@aliabd can you take this one?

**Comment by abidlabs** [comment]
Fixed now, thanks @aliabd!
