### ISSUE TITLE
Gradio Microphone Error when sending file to backend

### ISSUE THREAD

**Issue by huks0** [gradio-app/gradio#5338]
### Describe the bug

When using the microphone component as suggested in the [Speech Recognition](https://www.gradio.app/guides/real-time-speech-recognition) Tutorial of Gradio, I do run into the following error.

The WAV-Upload works fine and is similar implemented. So I do not understand where the problem is caused. The error kind of looks like that the body passed from the microphone to the backend is empty, even though its not empty when uploading a file. Any paramters missing? Any Suggestions? Appreciate it a lot!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
def start_gradio_app():
    microphone = gr.components.Audio(source="microphone", type="filepath", format="wav", show_download_button=True)
    wav_input = gr.components.Audio(source="upload", type="filepath")

    demo = gr.Interface(
        fn=transcribe,
        inputs=[wav_input, microphone],
        outputs=gr.outputs.Textbox(label="Processing Result JSON"))

```

### Logs

```shell
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/app-root/lib64/python3.9/site-packages/gradio/blocks.py", line 1030, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/opt/app-root/lib64/python3.9/site-packages/gradio/blocks.py", line 922, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/opt/app-root/lib64/python3.9/site-packages/gradio/components.py", line 2087, in preprocess
    sample_rate, data = processing_utils.audio_from_file(
  File "/opt/app-root/lib64/python3.9/site-packages/gradio/processing_utils.py", line 200, in audio_from_file
    audio = AudioSegment.from_file(filename)
  File "/opt/app-root/lib64/python3.9/site-packages/pydub/audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "/opt/app-root/lib64/python3.9/site-packages/pydub/utils.py", line 279, in mediainfo_json
    info = json.loads(output)
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
```


### System Info

```shell
gradio is 3.20.1
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Does the problem persist if you upgrade your gradio version?

**Comment by aminrabinia** [comment]
I have the same problem. I tried different versions of gradio but no improvement

**Comment by abidlabs** [comment]
Hi @aminrabinia @huks0 can you share the audio file that you used as well as try running in a Google Colab notebook and sharing that with us? We can't repro this on our end.

**Comment by aminrabinia** [comment]
I was in queue mode (which is needed for Progress and chatbot streaming). It worked fine in my local but in docker container running on GCP it kept giving me   
`Expecting value: line 1 column 1 (char 0)` 
with no more context. 
I had to roll back and remove the queuing.

**Comment by abidlabs** [comment]
@aminrabinia your issue seems to be the same as: https://github.com/gradio-app/gradio/issues/5145 -- which we haven't had a chance to look into just yet, apologies.

@huks0 as we haven't had a full repro, I'll close this issue.
