### ISSUE TITLE
Gradio API kwargs support

### ISSUE THREAD

**Issue by taoari** [gradio-app/gradio#5344]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

Current gradio API only supports positional arguments, it can become unmanaged if there are a lot of parameters for complex applications.  It would be great if kwargs would be supported. 

For example, the following code 

```python
import random
import gradio as gr

def random_response(message, history):
    return random.choice(["Yes", "No"])

params = [gr.Slider(minimum=0, maximum=1, value=0.7, step=0.1, interactive=True, label="Temperature",
            info="Lower temperator for determined output; hight temperate for randomness"),
    gr.Slider(minimum=0, maximum=1024, value=512, step=64, interactive=True, label="Max new tokens"),]
demo = gr.ChatInterface(random_response, additional_inputs=params)

if __name__ == "__main__":
    demo.launch()
```

generates the following API:

![](https://user-images.githubusercontent.com/3815006/263124397-4465f8d1-bcc7-414d-9829-d5cee29c7671.png)

It would be great if the API can have kwargs support:

```python
from gradio_client import Client

client = Client("http://localhost:7860/")
result = client.predict(
				message="Howdy!",	# str in 'Message' Textbox component
				temperature=0.7,	# int | float (numeric value between 0 and 1)
								in 'Temperature' Slider component
				max_new_tokens=512,	# int | float (numeric value between 0 and 1024)
								in 'Max new tokens' Slider component
				api_name="/chat"
)
print(result)
```

First, the API function kwargs names are generated from "label"; Second, the default values are generated from "value".

**Describe the solution you'd like**  

See above.

**Additional context**

**Comment by abidlabs** [comment]
Related issue: https://github.com/gradio-app/gradio/issues/5049

**Comment by abidlabs** [comment]
Hi @taoari this is a great suggestion and we're working on this in #7732. The PR is currently a WIP but feel free to try it out and share any feedback that you have on the PR as it'll help us make the Client more useful. Thanks!
