### ISSUE TITLE
Gradio LangChain streaming Example

### ISSUE THREAD

**Issue by taoari** [gradio-app/gradio#5345]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

It would be great if there could be a gradio langchain example with streaming support.

There is an example in the Guide: https://www.gradio.app/guides/creating-a-chatbot-fast#a-langchain-example for LangChain, but there is no streaming support. LangChain supports streaming in a callback way (https://python.langchain.com/docs/modules/model_io/models/chat/streaming), but the official example only streams to stdout. How can we stream langchain LLM to Gradio Chatbot messages?

**Describe the solution you'd like**  

A gradio langchain example with streaming support is provoided in https://www.gradio.app/guides/creating-a-chatbot-fast#a-langchain-example.

**Additional context**

**Comment by abidlabs** [comment]
Yeah this is popular enough that we could consider adding this. @yvrjsharma would you like to take this on?

**Comment by Saigenix** [comment]
Can I do this?

**Comment by abidlabs** [comment]
Go for it @Saigenix! We'd welcome a contribution

**Comment by Saigenix** [comment]
> Go for it @Saigenix! We'd welcome a contribution

hello, I don't have a paid openai account which's why I can't able to check its working or not Can you checkout this code? 

## A `langchain` example with streaming support

This will be same as above example with extra streaming support.
Some Chat models provide a streaming response. This means that instead of waiting for the entire response to be returned, you can start processing it as soon as it's available. This is useful if you want to display the response to the user as it's being generated, or if you want to process the response as it's being generated.

```python

from langchain.chat_models import ChatOpenAI
from langchain.schema import (
    HumanMessage,AIMessage
)
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
import gradio as gr


#  os.envrion["OPENAI_API_KEY"] = ""  # Replace with your key

def predict(message, history):
    history_langchain_format = []
    for human, ai in history:
        history_langchain_format.append(HumanMessage(content=human))
        history_langchain_format.append(AIMessage(content=ai))
    history_langchain_format.append(HumanMessage(content=message))
    gpt_response = ChatOpenAI(streaming=True, callbacks=[StreamingStdOutCallbackHandler()], temperature=0,openai_api_key="...")
    resp = gpt_response(history_langchain_format)
    return resp.content

gr.ChatInterface(predict).launch()

```

**Comment by taoari** [comment]
@Saigenix This does not work. For Gradio streaming, the predict function should be a generator function. The complex part is that LangChain does not return a generator even with streaming=True.

**Comment by Saigenix** [comment]
> @Saigenix This does not work. For Gradio streaming, the predict function should be a generator function. The complex part is that LangChain does not return a generator even with streaming=True. 

wait i will try another way

**Comment by Saigenix** [comment]
> @Saigenix This does not work. For Gradio streaming, the predict function should be a generator function. The complex part is that LangChain does not return a generator even with streaming=True.

hey I tried with this 
```python 
# Callbacks support token-wise streaming
class StreamingStdOutCallbackHandler(BaseCallbackHandler):
    def __init__(self,initial_text=""):
        self.text=initial_text
        
    def on_llm_new_token(self, token: str, **kwargs) -> None:
        # "/" is a marker to show difference 
        # you don't need it 
        self.text+=token+"/" 
```
Do you know any way to update chatbox content when the ` on_llm_new_token()` function gets called

**Comment by taoari** [comment]
@Saigenix i do not know simple ways to achieve this. I see examples using subprocess or websocket,  the codes are quite difficult to understand. So I am wondering if this can be implemented. In langchain, there are streamlit and stdout callback functions. langchain streaming works for both stdout and streamlit, do not know why langchain does not have one gradio callback function bulitin. Is this really hard to implement?

**Comment by Saigenix** [comment]
@taoari yes This will be much easier if they provide callback function for gradio

**Comment by yy306525121** [comment]
> did

it's very helpful

**Comment by jason-trinidad** [comment]
This should now be possible using LC's `Chain.stream()` function. E.g. for a chatbot:

```
from operator import itemgetter
import os

from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain.memory import ConversationBufferMemory
from langchain.schema.runnable import RunnableLambda, RunnablePassthrough

# Initialize chat model
llm = ChatOpenAI(openai_api_key=os.environ["OPENAI_API_KEY"])

# Define a prompt template
template = """You are a helpful AI assistant. You give specialized advice on travel.
"""

chat_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", template),
        MessagesPlaceholder(variable_name="history"),
        ("human", "{input}"),
    ]
)

# Create conversation history store
memory = ConversationBufferMemory(memory_key="history", return_messages=True)

# Initialize chain
# chain = LLMChain(
#     llm=llm,
#     prompt=chat_prompt,
#     # verbose=True,
#     memory=memory,
# )
chain = (
    RunnablePassthrough.assign(
        history=RunnableLambda(memory.load_memory_variables) | itemgetter("history")
    )
    | chat_prompt
    | llm
)


def stream_response(input, history):
    if input is not None:
        # ChatInterface struggles with rendering stream
        for response in chain.stream({"input": input}):
            print(response.content)
            yield response.content


# UI
import gradio as gr

gr.ChatInterface(stream_response).queue().launch()
```

From the print statement, you can see that the response is being generated correctly. Unfortunately, `ChatInterface` fails to display the results:

<img width="769" alt="Screenshot 2023-12-08 at 2 14 24 PM" src="https://github.com/gradio-app/gradio/assets/11757224/28533a8d-a30e-4448-a1a3-cf0491a07f88">

Does anyone know why this might be?

**Comment by yvrjsharma** [comment]
I can debug this more deeply at my end, but have you already tried setting `debug=True` in `launch()` to look at the log what error it is showing?

**Comment by jason-trinidad** [comment]
Hi @yvrjsharma - thanks for the response. Just tried `debug=True`. I see no error:

<img width="732" alt="Screenshot 2023-12-11 at 9 35 25 AM" src="https://github.com/gradio-app/gradio/assets/11757224/02bb49f1-b482-4629-b319-b8e1275e2d1e">

I also tried stepping through each generation. I see now that each word is replacing the previous word, instead of adding to it. E.g.

<img width="770" alt="Screenshot 2023-12-11 at 9 41 31 AM" src="https://github.com/gradio-app/gradio/assets/11757224/6a385214-e5cb-4dd0-bc72-e2dd80564c9e">

This seems to happen in Chrome and Safari. Thoughts?

**Comment by jason-trinidad** [comment]
Ah I misunderstood the implementation. That works for me! Thank you 😁

**Comment by HamaWhiteGG** [comment]
Thanks @bent-verbiage , I finish it without memory store.

```python
import os

from langchain_openai import ChatOpenAI
from langchain.schema import AIMessage, HumanMessage
import gradio as gr

os.environ["OPENAI_API_KEY"] = "sk-xxx"

# Initialize chat model
llm = ChatOpenAI(temperature=0.7, model='gpt-4', streaming=True)


def stream_response(message, history):
    print(f"Input: {message}. History: {history}\n")

    history_langchain_format = []
    for human, ai in history:
        history_langchain_format.append(HumanMessage(content=human))
        history_langchain_format.append(AIMessage(content=ai))

    if message is not None:
        history_langchain_format.append(HumanMessage(content=message))
        partial_message = ""
        for response in llm.stream(history_langchain_format):
            partial_message += response.content
            yield partial_message


iface = gr.ChatInterface(
    stream_response,
    textbox=gr.Textbox(placeholder="Message ChatGPT...", container=False, scale=7),
)

iface.launch(share=True)

```

**Comment by YashaswiniIppili** [comment]
How can I simulate streaming output response in my code ?

```
import logging
import sys
import torch
import requests
import subprocess
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, ServiceContext
from llama_index.llms.huggingface import HuggingFaceLLM
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from llama_index.legacy.embeddings.langchain import LangchainEmbedding
from llama_index.core.prompts.prompts import SimpleInputPrompt


logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

# Open the left folder icon menu and create a folder named sample and upload documents (pdfs)
documents = SimpleDirectoryReader("/content/G2").load_data()
system_prompt = "You are a Q&A assistant. Your goal is to answer questions as accurately as possible based on the instructions and context provided."
query_wrapper_prompt = SimpleInputPrompt("<|USER|>{query_str}<|ASSISTANT|>")
import torch

llm = HuggingFaceLLM(
    context_window=4096,
    max_new_tokens=256,
    generate_kwargs={"temperature": 0.0, "do_sample": False},
    system_prompt=system_prompt,
    query_wrapper_prompt=query_wrapper_prompt,
    tokenizer_name="meta-llama/Llama-2-7b-chat-hf",
    model_name="meta-llama/Llama-2-7b-chat-hf",
    device_map="auto",
    model_kwargs={"torch_dtype": torch.float16 , "load_in_8bit":True}
)

embed_model = LangchainEmbedding(
    HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")
)

service_context = ServiceContext.from_defaults(
    chunk_size=1024,
    llm=llm,
    embed_model=embed_model
)

index = VectorStoreIndex.from_documents(documents, service_context=service_context)

import gradio as gr

# Define your query_index function here
def query_index(query, history):
      query_engine = index.as_query_engine()
      response = query_engine.query(query)
      return str(response)

demo = gr.ChatInterface(
    fn=query_index,
    title="G2Bot"
)

# Launch the Gradio Chat Interface
demo.launch(debug=True)
```

Would love help asap, thank you in advance.

**Comment by abidlabs** [comment]
I looked into this, but the langchain docs offer so many different ways to stream LLMs that I'm not sure what the best example to add to our docs. I'd recommend just using the openai streaming example and modifying as necessary: https://www.gradio.app/guides/creating-a-chatbot-fast#a-streaming-example-using-openai

If someone has concrete issues getting this to work, its best to ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)

**Comment by brycepg** [comment]
Hello! I made a template for streaming with langchain+langgraph in gradio: [link](https://github.com/brycepg/gradio-langgraph-template)

**Comment by yvrjsharma** [comment]
This is great, thanks for sharing with the larger community @brycepg !
