### ISSUE TITLE
Display intermediate work (e.g. LLM agent thought process) inside Chatbot messages 

### ISSUE THREAD

**Issue by taoari** [gradio-app/gradio#5346]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

Agent becomes a popular topic for LLM. An agent usually has a thought process and does some intermediate work. It would be great if gr.Chatbot could adopt to display those processes.

E.g. OpenAI code interpreter "Show work"

 
<img width="593" alt="Screenshot 2023-08-25 at 11 08 44 AM" src="https://github.com/gradio-app/gradio/assets/3815006/45949405-2129-4b09-aecf-8f08f13a6dfc">

E.g. LangChain Agent "Thought process"

https://python.langchain.com/docs/integrations/callbacks/streamlit

<img width="841" alt="Screenshot 2023-08-25 at 11 04 45 AM" src="https://github.com/gradio-app/gradio/assets/3815006/3e02cf03-a7b8-49b1-abea-61f015eaf7c4">

**Describe the solution you'd like**  

Something similar to OpenAI code interpreter "Show work" or LangChain Agent "Thought process" (streamlit) is supported by gr.Chatbot.

**Additional context**

**Comment by abidlabs** [comment]
Thanks for creating these issues @taoari 

cc @dawoodkhan82 -- I don't think we add this to the component cleanup sprint, but I went ahead and added to the tracking issue: https://github.com/gradio-app/gradio/issues/4800

**Comment by TheoLvs** [comment]
Hello ! Any news on this feature ? With the rise of agents, it would be incredible <3

**Comment by freddyaboulton** [comment]
Hi @TheoLvs - I have a prototype working as a custom component. Will coordinate with the team on how to upstream to core.

**Comment by freddyaboulton** [comment]
This is now supported in the chatbot natively!
