### ISSUE TITLE
Easier Session State

### ISSUE THREAD

**Issue by taoari** [gradio-app/gradio#5349]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

For Global State (shared across all users), it is easy to use as a global variable. However, for Session State, it is much cumbersome to use, According to https://www.gradio.app/guides/interface-state#session-state, one needs three steps to use a session state. Is it possible to simplify the use of the session state?

**Describe the solution you'd like**  

A possible way to update session state would be like:

```python
global_state = {}
session_state = gr.State({})

def callback(...):
    global_state['input'] = 'Hello Global' # shared accross users
    session_state['input'] = 'Hello Session' # not shared across users
```

**Additional context**

**Comment by abidlabs** [comment]
Hi @taoari we're discussion ways potential ideas to improve state in this issue: https://github.com/gradio-app/gradio/issues/4689

Would you mind adding to the discussion there so that we have it all in one place? I'll go ahead and close this issue
