### ISSUE TITLE
new lines in `gr.Markdown`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#5356]
### Describe the bug

Not sure if this is a bug or just a breaking change, but the way `gr.Markdown` handles line breaks seems to have been changed in `gradio==3.41.x`.

Consecutive lines in markdown are often rendered as one long line unless there is blank line in it. GitHub renders markdown that way, and also it was the way `gr.Markdown` rendered markdown with `gradio==3.40.1`.
But now with `gradio==3.41.2`, consecutive lines are rendered as separate lines. Is this an intentional change or a bug?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

markdown = """
The quick brown fox jumps over the lazy dog. The quick brown fox jumps over
the lazy dog.

The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog.

The quick brown fox jumps over the lazy dog. The quick brown fox jumps over\
the lazy dog.
"""

with gr.Blocks() as demo:
    gr.Markdown(markdown)
demo.queue().launch()
```

https://huggingface.co/spaces/hysts-debug/markdown-new-line-gradio-3-40-1
https://huggingface.co/spaces/hysts-debug/markdown-new-line

### Screenshot

`gradio==3.40.1`
![](https://github.com/gradio-app/gradio/assets/25161192/d83d408b-27d5-40af-a290-1702c4f8ae16)

`gradio==3.41.2`
![](https://github.com/gradio-app/gradio/assets/25161192/a558547b-4c35-449e-b827-e778248bfc1c)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 3.41.2
gradio_client version: 0.5.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.0.1
fastapi: 0.103.0
ffmpy: 0.3.1
gradio-client==0.5.0 is not installed.
httpx: 0.24.1
huggingface-hub: 0.16.4
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.2
numpy: 1.25.2
orjson: 3.9.5
packaging: 23.1
pandas: 2.0.3
pillow: 10.0.0
pydantic: 1.10.12
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.7.1
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.24.1
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by pngwn** [comment]
This was intentional in order to make it consistent with our other uses of markdown in gradio. 

This consistent with how markdown behaves in GitHub comments but in rendered file. 

If we change this settings we'll need to change it for everything.

**Comment by hysts** [comment]
Thanks. I see. Yeah, GitHub renders lines in comments in separate lines, but GitHub renders consecutive lines in `README.md` etc. in one line, and VS Code also renders markdown in the same way.

I feel like there are pros and cons to both, so maybe it would be nice to have an optional argument in `gr.Markdown` to switch how to render lines.

**Comment by abidlabs** [comment]
I think its better not too add too many parameters to `gr.Markdown()`. Since there's a very easy workaround, I'd prefer marking this as a breaking change and moving on.

**Comment by abidlabs** [comment]
Oh sorry I misunderstood. I thought the change went the other way around -- we no longer respected single line breaks, so my suggestion would have been to just add a line break. This is a bit more annoying to deal with and I agree not the typical way I've seen Markdown rendered. I think its reasonable to add a flag to control this behavior, particularly for `gr.Markdown()` since its a component dedicated to rendering Markdown (whereas for `gr.Chatbot` for example we can be more opinionated with how we deal with Markdown)

Thanks for clarifying @hysts
