### ISSUE TITLE
Chatbot display avatar_images when message is None

### ISSUE THREAD

**Issue by PenutChen** [gradio-app/gradio#5357]
### Describe the bug

In my case, I need to display a welcome message at the beginning, so the first messages in the chat history will be `[None, "Welcome!"]`. However, the chatbot displays avatar images when the message is `None`. I'm wondering if this is configurable?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
    gr.Chatbot(
        [[None, "Welcome!"]],
        # Continuous responses are also strange.
        # [["Welcome!", None], ["Resp 1", None], ["Resp 2", None]],
        avatar_images=["assets/icon.png", "assets/user.png"],
        height=550
    )
demo.launch()
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/94501378/6bd8c90f-4032-4b42-bea1-979e5868f3d0)
![image](https://github.com/gradio-app/gradio/assets/94501378/453ae666-08ff-4974-b172-9767fb33b0c4)

### System Info

```shell
gradio==3.41.2
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Ah yeah we should fix this, cc @dawoodkhan82

**Comment by dawoodkhan82** [comment]
@Saigenix thanks for reporting, will fix!

**Comment by Saigenix** [comment]
> @Saigenix thanks for reporting, will fix!

hello, @dawoodkhan82 If You have any other issue similar to this Please Tag me, I will be happy to contribute

**Comment by PrashantSaikia** [comment]
@abidlabs How do I prevent the welcome message from interfering with the chat history processing? Details [here](https://github.com/gradio-app/gradio/issues/7925).
