### ISSUE TITLE
When I run `gradio deploy` from the command line, nothing happens. There is no output, and no error message.

### ISSUE THREAD

**Issue by jdevesa10** [gradio-app/gradio#5359]
### Describe the bug

**Describe the bug**
When I run `gradio deploy` from the command line, nothing happens. There is no output, and no error message.

**To Reproduce**
1. Run `gradio deploy` from the command line
2. Observe that there is no output or error message

**Expected behavior**
I expected to see some output indicating the status of the deployment, or an error message if something went wrong.

**Screenshots**

**Desktop (please complete the following information):**
- OS: [e.g. Windows 10]
- Browser [e.g. Chrome]

**Additional context**
I have an account with Hugging Face Spaces, and I have the latest version of Gradio installed.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

**To Reproduce**
1. Run `gradio deploy` from the command line
2. Observe that there is no output or error message

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/45880996/ce5d9b0f-bc8b-4924-b1b4-1dc22b729f84)

### System Info

```shell
**Desktop (please complete the following information):**
- OS:  Windows 10
- Browser  Chrome
- Version Nearly up to date! Relaunch Chrome to finish updating.
Version 115.0.5790.171 (Official Build) (64-bit)
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @jdevesa10 ! Can you run `gradio environment` so we can see the relevant package versions? I can't reproduce this

**Comment by jdevesa10** [comment]
[requirements.txt](https://github.com/gradio-app/gradio/files/12455442/requirements.txt)
Thank you for your prompt response. I have attached the requirements.txt file which contains all the installed packages in my environment. I hope this will help you in reproducing the issue. Please let me know if you need any more information from my end.

Thank you for your support

**Comment by jdevesa10** [comment]
C:\Users\jdeve>pip show gradio
Name: gradio
Version: 3.41.2
Summary: Python library for easily interacting with trained machine learning models
Home-page:
Author:
Author-email: Abubakar Abid <team@gradio.app>, Ali Abid <team@gradio.app>, Ali Abdalla <team@gradio.app>, Dawood Khan <team@gradio.app>, Ahsen Khaliq <team@gradio.app>, Pete Allen <team@gradio.app>, Ömer Faruk Özdemir <team@gradio.app>
License:
Location: C:\Users\jdeve\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: aiofiles, altair, fastapi, ffmpy, gradio-client, httpx, huggingface-hub, importlib-resources, jinja2, markupsafe, matplotlib, numpy, orjson, packaging, pandas, pillow, pydantic, pydub, python-multipart, pyyaml, requests, semantic-version, typing-extensions, uvicorn, websockets
Required-by:

C:\Users\jdeve>
C:\Users\jdeve>

**Comment by jdevesa10** [comment]
Freddy , thank you so much.

**Comment by yvrjsharma** [comment]
I am unable to repro this. 
I tested this on Windows with v3.42.0 and I was able to proceed ahead after `gradio deploy`.

**Comment by jdevesa10** [comment]
Yuvraj, thank you so much.

**Comment by jdevesa10** [comment]
Abubakar, thank you.
