### ISSUE TITLE
_js is not controlled by ``every'' argument 

### ISSUE THREAD

**Issue by chenjoya** [gradio-app/gradio#5365]
### Describe the bug

I am not sure if it is a bug. I find _js is not controlled by every argument: 

```python
with gr.Blocks() as app:
    dummy = gr.JSON({}, visible=False)
    app.load(fn=lambda x:print(x), every=1, inputs=[dummy], _js="() => Math.random()")
app.queue()
app.launch(server_port=8899, debug=True, share=True)
```

If we run this, every time we get the same number 
```
0.14488436985087927
0.14488436985087927
0.14488436985087927
0.14488436985087927
0.14488436985087927
0.14488436985087927
0.14488436985087927
```

But I need maybe continuously js random value. Is there any method to run js code and control by every=1?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Follow the code in **Describe the bug**.

### System Info

```shell
gradio==3.41.2
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @chenjoya this is intentional, the `js` function is supposed to run once, before the main function is run, which is controlled by the `every` parameter. But we should document this more clearly

**Comment by chenjoya** [comment]
Thank you so much! ;) 

Do you have elegant implementation method to achieve the streaming functionality, ie if there is a video playing in js, how to get its current time and streamingly output in a chatbot box? We recently want to show such a model. 

I implemented one by a json dictionary to receive the metadata of the video, and use .change method to refresh chatbox. But it may not be optimal.

Wish you merry Christmas in advance!
