### ISSUE TITLE
Gallery: content refresh doesn't reemit select()

### ISSUE THREAD

**Issue by mbahri** [gradio-app/gradio#5367]
### Describe the bug

Since PR https://github.com/gradio-app/gradio/pull/3061 when the content of a gallery is refreshed, and the user had selected an item at an index `i` that also exists in the new content, image `i` remains selected.

The problem is that events triggered by selecting an image in the gallery (such as applying processing on it) aren't refreshed when the images change.

This is breaking for applications that use that sort of workflow.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr
import numpy as np
from PIL import Image


def make_image(state):
    colors = ['red', 'blue']

    new_content = [np.asarray(Image.new("RGB", (512, 512), colors[state['color_ix']]))]
    state['gallery_content'] = new_content
    return new_content


def average_color(state, evt: gr.SelectData):
    image_np = state['gallery_content'][evt.index]
    r, g, b = image_np.mean(axis=(0, 1)).astype(int)
    return f"#{r:02x}{g:02x}{b:02x}"


def refresh_gallery_content(state):
    state['color_ix'] = (state['color_ix'] + 1) % 2
    return make_image(state)


with gr.Blocks() as demo:
    state = gr.State({'color_ix': 0, 'gallery_content': []})
    gallery = gr.Gallery()
    toggle_button = gr.Button("Refresh gallery content")
    color_picker_out = gr.ColorPicker(value="#ffffff", label='Average color in the image', interactive=False)

    toggle_button.click(refresh_gallery_content, [state], [gallery])
    gallery.select(average_color, [state], color_picker_out)
```

### Screenshot

https://github.com/gradio-app/gradio/assets/5632341/9b76993f-6b3b-46de-a114-5255778421bf

### System Info

```shell
➜ gradio environment
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 3.41.2
gradio_client version: 0.5.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.0.1
fastapi: 0.101.1
ffmpy: 0.3.1
gradio-client==0.5.0 is not installed.
httpx: 0.24.1
huggingface-hub: 0.16.4
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.2
numpy: 1.25.2
orjson: 3.9.4
packaging: 23.1
pandas: 2.0.3
pillow: 10.0.0
pydantic: 2.1.1
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.7.1
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.24.1
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by mbahri** [comment]
I'll submit a PR for this

**Comment by abidlabs** [comment]
Agree with @freddyaboulton here. What would be handy is to add a change() event for Gallery that would be emitted if the values in Gallery change for any reason. We have an open issue for that here: https://github.com/gradio-app/gradio/issues/2123, if you're interested in contributing a PR @mbahri

**Comment by abidlabs** [comment]
> A change() event listener would solve this and more, that sounds good. In the example above I could keep the index of the selected image in the state, check if it exists in the new gallery content, and call the same processing as for select(). It's a bit more work for the user but allows more to be done.

Yup that should work!

> Would you be open to having select() be re-emitted on content change as a configurable option?

At this point, I think it would be better to avoid adding it an as an option to keep the API simple and avoid parameter bloat.

**Comment by abidlabs** [comment]
Btw are you still interested in implementing this @mbahri?
