### ISSUE TITLE
How can I add thumbnail with my title?

### ISSUE THREAD

**Issue by harishgawade1999** [gradio-app/gradio#5374]
## **I'm using following code. but it doesn't showing anything in the output.** 

import gradio as gr
demo = gr.Interface(
    fn = credit_run,
    inputs = [
        gr.Slider(label="Person Age(In Years)", minimum=18, maximum=90, step=1),
        gr.Number(label="Person Income(per month)"),
        gr.Radio(['MORTGAGE', 'OTHER','OWN', 'RENT'],label="Home Ownership Status"),
        gr.Slider(label="Pererson Emp Length(In Years)", minimum=0, maximum=60, step=1),
        gr.Radio(['DEBTCONSOLIDATION', 'EDUCATION', 'HOMEIMPROVEMENT', 'MEDICAL', 'PERSONAL', 'VENTURE'],label="Credit Intent"),
        gr.Radio(['A','B', 'C', 'D', 'E','F', 'G'],label="Type Of Credit"),
        gr.Number(label="Loan Amount"),
        gr.Number(label="Loan Interest Rate"),
        gr.Radio(['N', 'Y'],label="Person Defaulted in History"),
        gr.Number(label="Person's Credit History Length"),
             ],
    outputs = gr.Radio(['Low risk of defaulting', 'High risk of defaulting']),
    title = "Non Payment credit risk",
    examples = [[23,25000,'RENT',2,'EDUCATION','A',30000,8.9,'N',6],
                [34,50000,'OWN',1,'MEDICAL','B',60000,10.65,'N',3],
                [42,30000,"MORTGAGE",12,'HOMEIMPROVEMENT','C',800000,7.9,'Y',8],
                [42,20000,"MORTGAGE",10,'PERSONAL','F',100000,15.25,'Y',5]],
    theme=gr.themes.Soft(),
    thumbnail= "https://github.com/harishgawade1999/Playstore-App-Review-Analysis-/blob/main/Non_payment_logo.png"
)

demo.launch(share = True,debug=True)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

For More information you can find an app and code here:- "https://huggingface.co/spaces/harish199/Non_Payment_Credit_Risk_Automation"

### Screenshot

<img width="955" alt="Screenshot 2023-08-30 105601" src="https://github.com/gradio-app/gradio/assets/88233990/b3c6380d-4402-475c-93a5-bb8a3b673964">

### Logs

```shell
Gradio is not showing any kind of error.
```

### System Info

```shell
OS- windows 11
fsspec: 2023.6.0
httpx: 0.24.1
huggingface-hub: 0.16.4
packaging: 21.3
requests: 2.28.1
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by taoli-ax** [comment]
How to use favicon_path  in gr.blocks

> Hi @harishgawade1999 the thumbnail parameter is not supported in `gr.Interface` anymore. You can instead pass in the favicon path using the `favicon_path` parameter. Please consult the Gradio docs: https://www.gradio.app/docs/interface

**Comment by abidlabs** [comment]
The same way -- `favicon_path` parameter is passed to `launch()` which works with `gr.Blocks()` as well
