### ISSUE TITLE
Add LaTeX support for Markdown in `description` and `article`

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#538]
**Is your feature request related to a problem? Please describe.**
Right now, we can't easily add mathematical notation to the description and article. 

**Describe the solution you'd like**
Ideally, if any math is passed between $ signs, it should get rendered into LaTeX. Several libraries exist to do this, particularly KaTeX: https://katex.org/

**Comment by lvwerra** [comment]
This would be a great feature - especially for metrics we would like to display the formula's to calculate them.

**Comment by mishig25** [comment]
for reference, we are already using katex [here](https://github.com/huggingface/doc-builder/blob/b648e065ff4f0d391d6a063e6a91f27e541ef4fb/kit/preprocess.js#L5) in doc-buidler for rendering latex in docs.

please let me know if you have any questions regarding parsing or katex :)
