### ISSUE TITLE
Provide a way to set noindex nofollow in the head section of a gradio app

### ISSUE THREAD

**Issue by bent-verbiage** [gradio-app/gradio#5380]
- [ X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As confirmed with one of the Gradio devs, there is currently no way to set head `meta elements` like `noindex` or `nofollow`. Nor is it possible to control the robots.txt file, except for setting share=True in launch. 

**Describe the solution you'd like**  
Provide a way to set meta elements like `<meta name="robots" content="noindex, nofollow">. Perhaps the most logical way to do this would be similar to adding an HTML block. Or alternatively, as parameters on the launch function.

**Additional context**  
Control over search engine indexing is important when gradio apps are integrated into websites and other applications.

**Comment by abidlabs** [comment]
Hi @bent-verbiage we are pretty heads down working on 4.0 so we probably won't be able to get to it until the end of the year or early next year. That being said, contributions are welcome and we are happy to review PRs as they come in!

**Comment by abidlabs** [comment]
Hi @bent-verbiage this has me thinking -- could you mount your Gradio app within a larger FastAPI app? That way you could set the `/robots.txt` route yourself. 

Instructions to do that are here: https://www.gradio.app/guides/sharing-your-app#mounting-within-another-fast-api-app

**Comment by freddyaboulton** [comment]
Have you tried @abidlabs 's suggestion @bent-verbiage ?

**Comment by abidlabs** [comment]
Will close for now for lack of followup, but can reopen if needed.

**Comment by abidlabs** [comment]
Ok I'll keep this issue open so that we can revisit it at a future time, though we will advise users to follow this path in the near future

**Comment by abidlabs** [comment]
Hi @bent-verbiage this should now be possible in Gradio 4.0. In Gradio 4.0, you can set the `head` parameter in `Blocks` that lets you include arbitrary JavaScript or other tags in the <𝚑𝚎𝚊𝚍> section of your Gradio app!

E.g. 

```py
ga_script = """
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DNJN1PF3CS"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'G-XXXXXXX');
</script>
"""

with gr.Blocks(head=ga_script):
  ...

```

**Comment by abidlabs** [comment]
Thanks @bent-verbiage, your feedback is invaluable! Just FYI, Gradio 4.0 does have some breaking changes, see here: https://github.com/gradio-app/gradio/issues/6339

**Comment by abidlabs** [comment]
I believe so yes, @dawoodkhan82 could you confirm?

**Comment by dawoodkhan82** [comment]
Yes, the `head` param works fine for me. Also here is a [guide](https://www.gradio.app/guides/custom-CSS-and-JS) with more details. Can you try other examples on this guide (towards the end of the guide) and see if they work for you. If not, there may be a bug.

**Comment by dawoodkhan82** [comment]
> Would it make sense if you'd add the head param to the gr.ChatInterface() as well?

Makes sense to me, @bent-verbiage can you create an issue for this?
