### ISSUE TITLE
Inputs component with  _js don’t match fn parameter

### ISSUE THREAD

**Issue by luoweb** [gradio-app/gradio#5385]
- [ ] I have searched to see if a similar issue already exists.

I need js just modified partial input value with js, like chatbot component, I just change the pormpt input, and cannot pass state and chabot to js

**Comment by abidlabs** [comment]
Hi @luoweb there isn't a lot of information in this issue, but I believe this is a duplicate of https://github.com/gradio-app/gradio/issues/3525. I'll close this -- please feel free to follow that issue or respond here if I'm mistaken.
