### ISSUE TITLE
Authenticated access via gradio_client API and curl

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#5398]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

Either via gradio_client or CURL, I don't see documentation or understand how to reach even a simplified api_name.

**Describe the solution you'd like**  

Documentation or feature to allow authentication (i.e.gradio's normal auth way) via API.

**Additional context**  

With curl, no matter various attempts to use `curl -u` or headers way, (https://stackoverflow.com/questions/25969196/how-to-define-the-basic-http-authentication-using-curl-correctly) I just get:

```
Not authenticated
```

With gradio client I just get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio_client/client.py", line 133, in __init__
    for fn_index, dependency in enumerate(self.config["dependencies"])
KeyError: 'dependencies'
```

**Comment by abidlabs** [comment]
This is not currently possible, but we have an open issue here: https://github.com/gradio-app/gradio/issues/3805
