### ISSUE TITLE
Scale parameter not working on upload audio widget

### ISSUE THREAD

**Issue by cowanAI** [gradio-app/gradio#5406]
### Describe the bug

The upload audio widget looks too big compared to my microphone widget, so tried using scaling to reduce the height of the of the upload widget but it didnt work

<img width="649" alt="image" src="https://github.com/gradio-app/gradio/assets/128092052/53de3f66-80b3-4371-93d3-31d79a5a7131">

Used the code as suggested on the documentation:

gr.Audio(source="upload", label="Instant Transcriber: Upload MP3 Audio (optional)", type="filepath",scale=0.3) ,

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

gr.Audio(source="upload", label="Instant Transcriber: Upload MP3 Audio (optional)", type="filepath",scale=0.3) ,

### Screenshot

<img width="652" alt="image" src="https://github.com/gradio-app/gradio/assets/128092052/cfc4de00-4c94-4669-829b-3b10d3e203e2">

### System Info

```shell
latest gradio version
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @cowanAI -- the `scale` parameter is designed to adjust the relative width of components, not the height. There isn't a way to adjust the height at the moment, but in fact, we are planning on redesigning the `Audio` component altogether and merge the audio upload with the mic recording, so I'll go ahead and close this issue as "not planned".

See: https://github.com/gradio-app/gradio/issues/5321
