### ISSUE TITLE
Unresponsive UI in Automatic1111 Stable Diffusion

### ISSUE THREAD

**Issue by delafer** [gradio-app/gradio#5420]
### Describe the bug

I'am testing preview / dev SD 1.6 version with latest changes with new / upcoming python 3.11 version.
All works fine, I haven't noticed any critical compatibility problems with a new python until yesterday (05.09.2023)
Everything worked perfectly with python 3.11 and torch 2.1 until...  I have merged and pulled a latest changes and have tried to start SD again and noticed that UI becomes unresponsive, if I try to select something in comobox (e.G. to load a model) or trying to click on any tab. 
Strangely enough, sometimes it worked, but most of the time it would freeze UI completely and I see something like 
_Uncaught (in promise) TypeError: a is null (   h Dropdown.svelte:48 )_
I have tried both latest FF and Chrome, cleaned cache, have tried to downgrade Gradio to 3.40.2
Have also tried to start in not only on Win 10 PC, but also with Linux (Arch linux)
I have even rolled back latest changes in code, deactivated cache, etc. -> nothing helps.
I think that's the UI / Gradio problem, because browser doesn't send any websocket or http/https requests even If i try to click on comboboxes or tabs and it simply freezes. I haven't seen also any errors in backend log... 
It's quite strange behaviour... and you could blame it on problems with the 3.11 python, but it was still working yesterday with the same 3.11 python version. It's a very strange problem.
most likely dep.manager updated in background some of the libraries yesterday - I suspect gradio or dependencies it's pulling and something in it is broken right now...

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Automatic111 SD v1.6 with 3.11.4 python on both windows and linux (arch linux) OS'es, doesn't work with both latest FF and Chrome

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/5951449/72e8a5bf-e461-4e6d-965b-19bafed10a2c)
![image](https://github.com/gradio-app/gradio/assets/5951449/8f71d6ef-a9f0-4644-b653-e5f0f3166ddf)

### Logs

```shell
Uncaught TypeError: gradioApp().body is null
    <anonymous> http://localhost:7860/file=javascript/imageviewer.js?1693858823.734346:254
    EventListener.handleEvent* http://localhost:7860/file=javascript/imageviewer.js?1693858823.734346:186
Uncaught (in promise) TypeError: a is null
    h Dropdown.svelte:48
    K Dropdown.svelte:47
    update Dropdown.svelte:42


h Dropdown.svelte:48
    K Dropdown.svelte:47
    update Dropdown.svelte:42
    Zi scheduler.js:115
    Bo scheduler.js:79
    promise callback*To scheduler.js:20
    ea Component.js:79
    ctx Component.js:127
    qe Blocks-b3881047.js:45
    x Blocks-b3881047.js:45
    y index.js:584
    y index.js:584
    onmessage index.js:547
    J index.js:503
    promise callback*J index.js:410
    ce Blocks-b3881047.js:45
    we Blocks-b3881047.js:45
    promise callback*we Blocks-b3881047.js:45
    t Blocks-b3881047.js:45
    t Blocks-b3881047.js:45
    dispatch Blocks-b3881047.js:12
    w StaticButton.svelte:39
    Ec lifecycle.js:181
    Ec lifecycle.js:181
    L Button.svelte:16
    selectCheckpoint ui.js:325
    onclick (index):1
```

### System Info

```shell
latest gradio: 3.41.2
anaconda python 3.11.4 (I know it's not officially supported, but it's worked a few days ago)
Automatic111 SD v1.6 with Pytorch 2.1 DEV/nighly
```

### Severity

Blocking usage of gradio

**Comment by delafer** [comment]
![image](https://github.com/gradio-app/gradio/assets/5951449/c47dcd64-43f5-4254-aea8-7a06e791ad95)

**Comment by abidlabs** [comment]
Thanks @delafer given the complexity of the Automatic1111 WebUI, we ask users to see if they can reproduce the issue in a simpler Gradio app (in which case it's definitely a Gradio issue) or whether it might be something specific to Automatic1111.

Are you able to provide us a simpler repro we can use to investigate and test a fix?

**Comment by delafer** [comment]
> Thanks @delafer given the complexity of the Automatic1111 WebUI, we ask users to see if they can reproduce the issue in a simpler Gradio app (in which case it's definitely a Gradio issue) or whether it might be something specific to Automatic1111.
> 
> Are you able to provide us a simpler repro we can use to investigate and test a fix?

thanks, good idea, sounds logical. sadly I haven't had any experience with gradio until recently, but I will try to use your official repository and run a test gradio application from this repo and report back.
P.S. and yeah... I naively hoped a little bit that you would see the error and immediately say - ah it's obvious and trivial, everything is clear - we know what the problem is :-)

**Comment by delafer** [comment]
yeah... simple example app with combo's works fluently...  which doesn't surprise me... there's a deeper compatibility issue here.

**Comment by abidlabs** [comment]
Hi @delafer no totally fine to link to other GH projects, but we'll need a simpler repro for us to be able to investigate. I'm going to close this issue for now, but if you are able to identify a simpler repro, we can definitely reopen.
