### ISSUE TITLE
Use Start/Stop button to record live audio using Gradio app

### ISSUE THREAD

**Issue by IshanRattan** [gradio-app/gradio#5425]
Hi All,

I need help with a problem. I want to add a button in my Gradio app to start/stop audio recording. Basically, what I am trying to do is place a button on the UI. When a user clicks on the this button(let’s say “Speak”), then audio recoding starts and the button text changes to “Stop”. When user clicks on the button again(which now says “Stop”) then audio recording stops.

I want something like this:

![1](https://github.com/gradio-app/gradio/assets/47667268/bef72b6c-c97b-44b4-b1cd-a04ccd4ff281)

**Comment by abidlabs** [comment]
Hi @IshanRattan why not just use the default button built into the `gr.Audio(source="microphone")`?

**Comment by IshanRattan** [comment]
Hi @abidlabs , I need to hide the built in button and use one custom button to trigger multiple actions further, so a single button which changes its label on click and also starts recording would solve these challenges for me.

**Comment by IshanRattan** [comment]
Thanks but this doesn't solve the original problem of triggering .start_recording(). Thanks a lot for your effort though! Lastly, please do think of providing a customisable button for start/stop audio recording(in future releases). I'm sure it will help many other users.

**Comment by IshanRattan** [comment]
Working solution to the original prob: 

```

import gradio as gr


def click_js():
    return """function audioRecord() {
    var xPathRes = document.evaluate ('//*[@id="audio"]//button', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null); 
    xPathRes.singleNodeValue.click();}"""


def action(btn):
    """Changes button text on click"""
    if btn == 'Speak': return 'Stop'
    else: return 'Speak'


def check_btn(btn):
    """Checks for correct button text before invoking transcribe()"""
    if btn == 'Speak': pass
    else: raise Exception('Recording...')


def transcribe():
    return 'Success'


with gr.Blocks() as demo:
    msg = gr.Textbox()
    audioBox = gr.Audio(label="Audio", source="microphone", type="filepath", elem_id='audio')

    with gr.Row():
        audio_btn = gr.Button('Speak')
        clear = gr.Button("Clear")

    audio_btn.click(fn=action, inputs=audio_btn, outputs=audio_btn).\
              then(fn=lambda: None, _js=click_js()).\
              then(fn=check_btn, inputs=audio_btn).\
              success(fn=transcribe, outputs=msg)

    clear.click(lambda: None, None, msg, queue=False)

demo.queue().launch(debug=True)
```
