### ISSUE TITLE
a `gr.DownloadButton` that lets you download a file with a button click

### ISSUE THREAD

**Issue by hyer** [gradio-app/gradio#5426]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Is possible to directly download file with a button click, rather using the `gr.File` component. Directly download will be more intuitive, and using the gr. File requires two operations.

**Describe the solution you'd like**  
I don't want to add the `gr.File` component on my app's UI. I'd like to download a file (eg: image) from a http url or local path with a button click.

**Comment by abidlabs** [comment]
Hi @hyer we don't have a `gr.DownloadButton` component -- we could create a component like this in the future. The other possibility would be to use the `link` attribute of the `gr.Button()` to point to the filepath. Something like this:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Button(link="/file=cheetah.jpg")
    
demo.launch()
```

**Comment by cowanAI** [comment]
@abidlabs could you do this code: 

On interface too? import gradio as gr

with gr.Blocks() as demo:
    gr.Button(link="/file=cheetah.jpg")
    
demo.launch() thanks for your help on this.

**Comment by abidlabs** [comment]
Not sure I understand the question @cowanAI can you explain what you mean?

**Comment by cowanAI** [comment]
Let’s say I make a gradio interface not blocks, and then add a microphone
component to it, can we use the link button to download the audio in that
way?

**Comment by abidlabs** [comment]
Ah yeah it should be possible I think. Let's say your filepath is `filepath` You can return a `gr.Button.update(link="file/=" + filepath)` from your function

**Comment by hyer** [comment]
> 

Thanks. However, this is viewable only in the browser, not the usual way of saving to local disk. Look forward to seeing the `gr.DownloadButton` component soon

**Comment by abidlabs** [comment]
Hi @pcschreiber1 -- which version of gradio are you using?

**Comment by pcschreiber1** [comment]
Thank you for the quick reply @abidlabs , I'm using gradio 4.7.1

**Comment by abidlabs** [comment]
In Gradio 4.x, files your local system are not exposed by default, so you'll need to explicitly allow the specific file or directory. E.g. 

```py
import gradio as gr

with gr.Blocks() as demo:
...
    
demo.launch(allowed_paths=["file/material/test.txt"])
```

or you could do a containing folder as well, like:

```py
import gradio as gr

with gr.Blocks() as demo:
...
    
demo.launch(allowed_paths=["file/"])
```

**Comment by pcschreiber1** [comment]
@abidlabs the problem unfortunately persists for me:
```
import gradio as gr

with gr.Blocks() as demo:
    gr.Button("Download", link="/file=material/test.txt")
    
demo.launch(allowed_paths=["file/"])
```

I updated now to gradio 4.8.0 and tried `file/material/test.txt` and `/file=material/test.txt`  but both lead to the same error :/

Thank you for your super fast responses though!!!

**Comment by abidlabs** [comment]
Oh sorry I wasn't reading clearly, it should be:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Button("Download", link="/file=material/test.txt")
    
demo.launch(allowed_paths=["material/"])
```

**Comment by y33-j3T** [comment]
@abidlabs On the side, may I know if the same file system is shared by multiple users? If I were to implement the download button such that when it's pressed, generates a CSV specific to the user (eg. `df.to_csv("downloads/test.csv"`) and downloads it, could it lead to users downloading each other's file instead of their own when there are >1 users are using the app at the same time?

**Comment by abhinav-vimal13** [comment]
how to download multiple files?

**Comment by abidlabs** [comment]
@abhinav-vimal13 right now, you would display the with a `gr.File()` and that would let you download the files.

**Comment by Matloob-20** [comment]
Hey @abidlabs .Is there a solution to download the image and save it to a local directory?

**Comment by abidlabs** [comment]
The `gr.DownloadButton` should let you do exactly that, does it not? There's also a download icon in the top right corner of the `gr.Image` component itself

**Comment by Ifeanyi55** [comment]
What if I want to download the output of an LLM as a text file from my Gradio app, how can I achieve that?

**Comment by abidlabs** [comment]
@Ifeanyi55 you can write to a file and then pass that file into `gr.DownloadButton` -- we are looking into a native download for the `gr.Chatbot`

**Comment by srishino** [comment]
Hi @abidlabs - I am trying to download the output from LLM as a text file using the gr.DownloadButton. But getting an error- AttributeError: module 'gradio' has no attribute 'DownloadButton'. I am writing the output and returning the file and passing it to thegr.DownloadButton. Please let me know how to proceed. thanks

**Comment by freddyaboulton** [comment]
> But getting an error- AttributeError: module 'gradio' has no attribute 'DownloadButton'.

Maybe you're using an old version of gradio?

**Comment by srishino** [comment]
Hi @freddyaboulton , correct i was using an older version. But on trying with the latest version, it is unable to read an audio file. So i am working on speech to text and i need to download the text file. Was getting this error with new 4.37 version of gradio
-  TypeError: expected str, bytes or os.PathLike object, not tuple

**Comment by freddyaboulton** [comment]
Hi @srishino - yes pass just a string corresponding to the filepath you want to download - not a tuple used to display as a file in the chatbot. 

For general questions/bugs that are not gradio issues please post on the hugging face discord on the #gradio-questions channel! https://discord.gg/6fbYVE3e

**Comment by srishino** [comment]
sure @freddyaboulton, thanks.
