### ISSUE TITLE
我现在有多个模型和6张3090，但是我想通过网页动态的切换模型，请问有什么方法？

### ISSUE THREAD

**Issue by bank010** [gradio-app/gradio#5428]
有的模型需要占用4张卡，有的只要一张即可，当我运行大模型的时候，GPU显然已经不足，我目前是通过根据Pid找到对应进程，然后给kill，但是我该怎么通过gradio去加载模型并且部署到fastapi上呢？

**Comment by freddyaboulton** [comment]
Hi @bank010 ! Can you please create a new issue in english? Thank you

**Comment by bank010** [comment]
> do you seriously think it's okay to create a ticket in Chinese and everyone should understand what you want?

@korvin2000 @freddyaboulton  #5437 hello,I posted a new issue,Thank you!
