### ISSUE TITLE
I now have multiple models and 6 pieces of 3090, but I want to switch models dynamically through the web, what is the method?

### ISSUE THREAD

**Issue by bank010** [gradio-app/gradio#5437]
Some models need to occupy 4 cards, some only need one card, when I run a large model, the GPU is obviously insufficient, I currently find the corresponding process according to the Pid, and then kill, but how do I load the model through gradio and deploy it to fastapi?

Flexible model switching like Stable Diffusion-webUI

**Comment by abidlabs** [comment]
Hi @bank010, for general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
