### ISSUE TITLE
Improvements for "Use via API" Section in Autogenerated Docs and JS Client Guide

### ISSUE THREAD

**Issue by Muhtasham** [gradio-app/gradio#5439]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Yes, I encountered errors while using the JavaScript client with`gr.ChatInterface`, following the examples in the autogenerated "Use via API" section and the [JavaScript Client Getting Started Guide](https://www.gradio.app/guides/getting-started-with-the-js-client). The main issues are:

The "Use via API" section in the autogenerated documentation provides an incomplete example, which doesn't demonstrate how to handle interfaces requiring multiple inputs, leading to errors during implementation.

which give this example:
``` javascript
const result = await app.predict("/chat", [		
				"Howdy!", // string  in 'parameter_6' Textbox component
	]);
```

Also the [JavaScript Client Getting Started Guide](https://www.gradio.app/guides/getting-started-with-the-js-client) lacks detailed examples and formatted code blocks, hindering a smooth implementation process.

During implementation, I encountered the following error which indicates a mismatch in the number of inputs expected and provided:

Steps to Reproduce

In the autogenerated documentation, the "Use via API" section provides an example that leads to errors when the interface requires multiple inputs (please replace with the exact URL of your Gradio app’s autogenerated docs):
```bash 
ValueError: An event handler (_api_stream_fn) didn't receive enough input values (needed: 2, got: 1). 
Check if the event handler calls a Javascript function, and make sure its return value is correct.    
Wanted inputs: [textbox, state]
Received inputs: ["Howdy!"]
```

**Describe the solution you'd like**  
I would like to see the following improvements:

1.Revise the "Use via API" section in the autogenerated documentation to include a comprehensive example showcasing how to pass multiple inputs to the `predict` function, e.g.:
 ``` javascript
  
    const result = await app.predict("/chat", [
        "Howdy!", // string in 'textbox' component
        null,     // value for 'state' component (replace with appropriate value)
    ]);
```

2.Enhance the [JavaScript Client Getting Started Guide](https://www.gradio.app/guides/getting-started-with-the-js-client) with:
Formatted code blocks for better readability.
Detailed examples covering various use cases including handling of multiple inputs and different types of input components.

**Additional context**  
Improving the documentation with comprehensive examples and formatted code blocks can significantly aid developers, especially those new to Gradio JavaScript client, in avoiding common pitfalls and in successfully integrating Gradio interfaces into their web applications. @abidlabs

**Comment by knockkk** [comment]
Is there currently a solution to this problem? What is the 'state' parameter?

**Comment by abidlabs** [comment]
This should be fixed now! Let us know if you still encounter any issues @Muhtasham
