### ISSUE TITLE
Layout Error in Chrome and Edge

### ISSUE THREAD

**Issue by ZedFu** [gradio-app/gradio#5440]
### Describe the bug

I am a beginner of Gradio, I write Gradio codes to show 5\*5 images with 5\*5  Checkboxes.  
```
with gr.Blocks() as demo:
    image_list = []
    checkbox_list = []
    for a in range(5):
        with gr.Row():
            for b in range(5):
                with gr.Column():
                    image_list.append(gr.Image(label='{}_{}'.format(a,b),show_download_button=False))
                    checkbox_list.append(gr.Checkbox(label='{}_{}'.format(a,b)))

    with gr.Row():
        btn_start = gr.Button('Start')
        btn_prev = gr.Button('Prev')
        btn_next = gr.Button('Next')
        btn_clear = gr.ClearButton(components=checkbox_list)
        btn_save = gr.Button('Save')
```
This code layout error in Chrome and Edge, But  layout right in Pale Moon.
I'm not sure if it's Gradio's problem or Chrome's? How can I achieve the effect under Pale Moon in Chrome?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
with gr.Blocks() as demo:
    image_list = []
    checkbox_list = []
    for a in range(5):
        with gr.Row():
            for b in range(5):
                with gr.Column():
                    image_list.append(gr.Image(label='{}_{}'.format(a,b),show_download_button=False))
                    checkbox_list.append(gr.Checkbox(label='{}_{}'.format(a,b)))

    with gr.Row():
        btn_start = gr.Button('Start')
        btn_prev = gr.Button('Prev')
        btn_next = gr.Button('Next')
        btn_clear = gr.ClearButton(components=checkbox_list)
        btn_save = gr.Button('Save')
```

### Screenshot

This is the effect under Pale Moon
<img width="470" alt="PaleMoon" src="https://github.com/gradio-app/gradio/assets/43996254/c17e3fcd-ee9b-4cea-ab24-13d304d7866a">
This is the effect under Chrome and Edge
<img width="426" alt="Chrome" src="https://github.com/gradio-app/gradio/assets/43996254/968605ec-3100-45d1-b33b-ffaa65b5869b">

### System Info

```shell
Both Windows 10, Gradio 3.40.1 and Manjaro, Gradio have an error!
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @ZedFu the reason is a `gr.Column()` has a minimum width, which is forcing the final image / checkbox to wrap over to the next line. If you'd like you can adjust the `min_width` parameter in `gr.Column()` like this:

```py
with gr.Blocks() as demo:
    image_list = []
    checkbox_list = []
    for a in range(5):
        with gr.Row():
            for b in range(5):
                with gr.Column(min_width=0):
                    image_list.append(gr.Image(label='{}_{}'.format(a,b),show_download_button=False))
                    checkbox_list.append(gr.Checkbox(label='{}_{}'.format(a,b)))

    with gr.Row():
        btn_start = gr.Button('Start')
        btn_prev = gr.Button('Prev')
        btn_next = gr.Button('Next')
        btn_clear = gr.ClearButton(components=checkbox_list)
        btn_save = gr.Button('Save')
        
demo.launch()
```

By the way, for general questions like this (that are not feature requests or bug reports), it is better to ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). Thanks!
