### ISSUE TITLE
Add "How to Install Gradio" in the docs page or Quickstart guide

### ISSUE THREAD

**Issue by zabihshaik** [gradio-app/gradio#5444]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I wanted to Install gradio in my laptop(OS: Windows 10). As per the quickstart guide, it is showing to just write `pip install gradio` . I tried that, but after installing many packages, got an error:(screenshot attached)

![gradio pip error](https://github.com/gradio-app/gradio/assets/91183455/dc608e06-606a-49bf-9c56-e870ec858f18)

**Describe the solution you'd like**  
I would like to see a "How to install guide" on the guides page or the quickstart guide page. Like, if the Windows users are facing this issue, or is it common for all. I saw a solution for the same error in the Streamlit app website, as they have a specific guide/instructions to install Streamlit in the virtual environment. Searched in the Gradio Website to see the same, but couldn't find it. I really want to install gradio and work on a ML Project. 

**Additional context**  
I would like to share the screenshot of the Streamlit installation page if it's allowed to.

![streamlit-installation-pic](https://github.com/gradio-app/gradio/assets/91183455/40382259-22ff-4469-80c1-c71b0ddf22bd)

![streamlit-installation-steps-1](https://github.com/gradio-app/gradio/assets/91183455/4d1c7a09-9f34-4927-9dc5-08853ddef5f5)

![streamlit-installation-steps](https://github.com/gradio-app/gradio/assets/91183455/47cc012f-7231-48e3-9f33-999b2c38e35d)

**Comment by freddyaboulton** [comment]
Would be interested in writing that guide @zabihshaik ?

**Comment by zabihshaik** [comment]
Hey @freddyaboulton ! Thanks for the prompt response 👍
  
I would love to write the guide. But, I am in the middle of a Project. And writing this guide would take some time. But, I can start on it right away. It's just that, I have to try it first on my Windows Laptop (will try similar to Streamlit installation docs), and if that works, will complete the guide and raise PR. Is it fine with you?

Also, I can only write the guide for Windows as I do not have Mac to do the same & write for MacOS.

I also have one more question with you: Is there any officially-supported environment manager on Windows for Gradio? (Like Anaconda Navigator for Streamlit).

Thanks in advance.
