### ISSUE TITLE
Clicking on a tab with a `gr.DataFrame` causes the page to scroll to where the DataFrame is

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#5448]
### Describe the bug

![Recording 2023-09-07 at 15 07 35](https://github.com/gradio-app/gradio/assets/1778297/5b199976-024f-453c-b77c-9b7ee965dc78)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Visit https://huggingface.co/spaces/gradio-pr-deploys/pr-5446-all-demos and click on the "kitchen_sink" tab

### System Info

```shell
gradio 3.43
```

### Severity

I can work around it

**Comment by pngwn** [comment]
You spend a bit of dedicated time on a component and their egos just explode and they start getting ideas above their station. Despicable.
