### ISSUE TITLE
Gradio launch does not show public url

### ISSUE THREAD

**Issue by sylee96** [gradio-app/gradio#5450]
### Describe the bug

I'm using gradio with the 'share=True' argument in gradio/blocks.launch(), but it seems that a public URL is not being generated. While debugging step by step, I suspect that the issue might be in the 'gradio/tunneling.py' file within the '_start_tunnel' function

```
if self.proc.stdout is None:
    continue
line = self.proc.stdout.readline()
line = line.decode("utf-8")
if "start proxy success" in line:
    result = re.search("start proxy success: (.+)\n", line)
    if result is None:
        raise ValueError("Could not create share URL")
    else:
        url = result.group(1)
```

It appears that there might be a problem with the code snippet above. I also noticed that someone suggested downgrading gradio to version 3.9 in another issue, but even after doing so, the issue persists.

Could you please provide guidance on how to resolve this issue? Your assistance would be greatly appreciated.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")

demo.launch(share=True)
```

### Screenshot

<img width="1273" alt="image" src="https://github.com/gradio-app/gradio/assets/77087144/d436db9b-c0a5-4a7a-8059-920c4762c32b">

### Logs

```shell
Launching Web UI with arguments: --xformers --listen --share
Loading weights [5493a0ec49] from /data/stable-diffusion-webui/models/Stable-diffusion/stable-diffusion-models/abyssorangemix3AOM3_aom3a1b.safetensors
Creating model from config: /data/stable-diffusion-webui/configs/v1-inference.yaml
Running on local URL:  http://0.0.0.0:7860
Applying attention optimization: xformers... done.
Model loaded in 6.9s (load weights from disk: 0.9s, create model: 1.0s, apply weights to model: 4.6s, calculate empty prompt: 0.3s).
```

### System Info

```shell
gradio version = 3.41.2
```

### Severity

Blocking usage of gradio

**Comment by admalekar** [comment]
I am not able to reproduce the issue. Are you using automatic1111 stable diffusion webui?
I am getting public link in automatic1111 stable diffusion webui and with the reproduction steps as well.
Can you try to update the webui to version 1.6?
