### ISSUE TITLE
how to programmely trigger a update for a component , likely change the value of the Video component.

### ISSUE THREAD

**Issue by zhangbo2008** [gradio-app/gradio#5451]
### Describe the bug

it seems like only method is set the update as a funciton's return value.  and put it to a Button.click(). how to programmely apply? i dont want to click the button by hand, i wanna control it by the code .

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

1111111111111

### System Info

```shell
111111111
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @zhangbo2008, for general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
