### ISSUE TITLE
at the bottom of the space; Use via API,hide

### ISSUE THREAD

**Issue by icelandno1** [gradio-app/gradio#5455]
- [ ] I have searched to see if a similar issue already exists.
At the bottom of the generated page, there are always things like "Use via API" and "Built with Gradio", is there a way to hide them? I've tested the "show_api=False" approach before but it doesn't work, hopefully I can get an answer. I'm looking for an answer to this question.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**  
Add any other context or screenshots about the feature request here

![image](https://github.com/gradio-app/gradio/assets/10095997/c208c305-9e35-4673-bdfe-466a5ef09b00)

**Comment by abidlabs** [comment]
Hi @icelandno1 you can use custom css to customize the footer. See this issue: https://github.com/gradio-app/gradio/issues/2510

**Comment by icelandno1** [comment]
@abidlabs thank you very much, I'll try it
