### ISSUE TITLE
Scrolling horizontally on a dataframe moves the column more than the title bar

### ISSUE THREAD

**Issue by clefourrier** [gradio-app/gradio#5458]
### Describe the bug

![image](https://github.com/gradio-app/gradio/assets/22726840/0ea13211-aade-41d9-a660-d88a63d8b555)
Fun bug in the latest release: if you display a dataframe on a screen which is smaller than it, it adds a scroll bar which works fine, but scrolls the columns past their titles/more than the titles.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Display the Open LLM Leaderboard on desktop with a window smaller than the DF, scroll laterally

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 3.43.2
gradio_client version: 0.5.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.1.0
altair: 4.2.2
fastapi: 0.95.1
ffmpy: 0.3.0
gradio-client==0.5.0 is not installed.
httpx: 0.24.0
huggingface-hub: 0.16.4
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.2
matplotlib: 3.7.1
numpy: 1.24.2
orjson: 3.8.10
packaging: 23.1
pandas: 2.0.0
pillow: 9.5.0
pydantic: 1.10.7
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.28.2
semantic-version: 2.10.0
typing-extensions: 4.5.0
uvicorn: 0.21.1
websockets: 11.0.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.4.0
httpx: 0.24.0
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.28.2
typing-extensions: 4.5.0
websockets: 11.0.1
```

### Severity

I can work around it

**Comment by clefourrier** [comment]
@pngwn

**Comment by abidlabs** [comment]
This problem, which I believe is related, seems to have returned as well: the dataframe always has scroll bars, even for small dataframes because the width of the dataframe is just a tad bit wider than the container:

<img width="1427" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/737a8430-477d-4f39-9164-5f54538fc9f1">

To reproduce, run `demo/matrix_transpose/run.py`

**Comment by abidlabs** [comment]
I'm having a hard time reproducing the original issue @clefourrier. I tried adjusting the original leaderboard: https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard

![Recording 2023-09-12 at 12 39 54](https://github.com/gradio-app/gradio/assets/1778297/826e932d-5b15-4bfc-b699-f6c1021bdcd9)

Everything seems to be working fine. Am I missing something? Or did this get fixed already?

**Comment by clefourrier** [comment]
Still does it on my machine (Ubuntu 20.04.6 LTS, Mozilla Firefox 117.0).
First using first the scroll trackpad shortcuts, then actually moving the slide bar.
  
https://github.com/gradio-app/gradio/assets/22726840/243d9846-7010-45c2-a77c-bd329ed97121

**Comment by abidlabs** [comment]
@clefourrier can you see if this is still an issue in the latest version of gradio? `3.45.1`

**Comment by clefourrier** [comment]
Just tried it, not fixed :(

**Comment by ThiloteE** [comment]
I have the same problem, which I reported at https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard/discussions/363. I use Mozilla Firefox 119.0.1 on Windows, if that helps.

**Comment by tomaarsen** [comment]
I am encountering the same issue on [MTEB](https://huggingface.co/spaces/mteb/leaderboard) on Firefox web - it's quite frustrating.

**Comment by clefourrier** [comment]
Yep it makes navigating big tables quite hard tbh

**Comment by severo** [comment]
+1. On MacOS, with Gradio 4: it works well with Chrome (first part of the video), but the misalignment is huge with Firefox (second part)


https://github.com/gradio-app/gradio/assets/1676121/37627777-f232-461c-8d8a-33cd044895ae
