### ISSUE TITLE
`@gradio/client` options parameter is not optional

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#5461]
### Describe the bug

> When you use gradio client in ts, const gradioApp = await client("https://mishig-embeddings-similarity.hf.space/")  (which is what’s suggested in the docs), gives you an error An argument for 'options' was not provided. So I had to provide empty options const gradioApp = await client("https://mishig-embeddings-similarity.hf.space/", {})

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

When you use gradio client in ts, const gradioApp = await client("https://mishig-embeddings-similarity.hf.space/")  (which is what’s suggested in the docs), gives you an error An argument for 'options' was not provided. So I had to provide empty options const gradioApp = await client("https://mishig-embeddings-similarity.hf.space/", {})

Need to make this optional.

### Screenshot

-

### Logs

```shell
-
```

### System Info

```shell
-
```

### Severity

I can work around it

**Comment by shwethabm** [comment]
Can I work on this issue?

**Comment by abidlabs** [comment]
Go for it @shwethabm! Looking forward to reviewing your PR
