### ISSUE TITLE
The using of Gradio reload method under VScode venv virtual environment. 

### ISSUE THREAD

**Issue by zhangweikun69** [gradio-app/gradio#5464]
**What this issue looks like:**
- in vscode & using venv virtual environment.
- run gradio gradioServer.py
- return: 
    Traceback (most recent call last):
      File "Path\to\my\project\gradioServer.py", line 1, in <module>
        import gradio as gr
    ModuleNotFoundError: No module named 'gradio'
    (All dependencies are installed in the venv virtual env, but still can't find modules by using "gradio gradioServer.py")

**Describe the solution you'd like**  
The problem is because the subprocess.Popen method automatically use system Python interpreter Path when creating a subprocess

Lib/site-packages/gradio/reload.py:

```
def main():
    
    # default execution pattern to start the server and watch changes
    filename, path, watch_dirs, demo_name = _setup_config()
 
    args = sys.argv[1:]
    extra_args = args[1:] if len(args) == 1 or args[1].startswith("--") else args[2:]

    popen = subprocess.Popen(
        ["python", path] + extra_args,
        env=dict(
            os.environ,
            GRADIO_WATCH_DIRS=",".join(watch_dirs),
            GRADIO_WATCH_FILE=filename,
            GRADIO_WATCH_DEMO_NAME=demo_name,
        ),
    )

    popen.wait()
```

How to Solve: Add "shell = True" to enable the current virtual environment variables by running through shell.
(OR simply replace "python" by your python interpreter path, mine is: "F:\...\venv\Scripts\python.exe")
correction：
```
popen = subprocess.Popen(
        ["python", path] + extra_args, shell=True,
        env=dict(
            os.environ,
            GRADIO_WATCH_DIRS=",".join(watch_dirs),
            GRADIO_WATCH_FILE=filename,
            GRADIO_WATCH_DEMO_NAME=demo_name,
        ),
    )
```

I'm not sure this is common error, but it did happen to me, and here is the solution.

**Comment by jbccc** [comment]
I encountered the same difficulty and setting `shell=True` indeed solved the problem.

**Comment by freddyaboulton** [comment]
Thanks for the feedback @zhangweikun69 and @jbccc . I think we can provide the full path to the current python executable instead of using shell=True. Will look into this.

**Comment by freddyaboulton** [comment]
Closed in v4 branch!
