### ISSUE TITLE
Dropdown "search" leads to odd pop-ups, making it difficult to use -- allow disable "search" mode

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#5465]
### Describe the bug

The dropdown allows one to enter text and that filters down the options.  But most of the time, with say less than 10 entries, this search option is highly distracting and leads to bad behaviors.  The x on right is a hassle to avoid and is confusing UX wise.

Please:
* Allow disable of entering arbitrary text.  In most cases there is no need for this
* Allow disable of overall x on right that's next to drop down.  Too easy to hit x instead of drop-down, and for few entries the overall x is not useful since one can just deselect each.
* Allow list of items selected to be hidden, often no need to see that list if it has impact on UI via change etc

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr


demo = gr.Blocks()
with demo:

   visible_models = gr.Dropdown(['A', 'B', 'C'],
                                 label="Visible Models",
                                 value=['A', 'B'],
                                 interactive=True,
                                 multiselect=True,
                                 )

demo.launch()
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/2249614/82f02861-ebd9-498d-92d1-ab7a0aac5abd)

E.g. chrome keeps trying to see if I need a password there (redacted/chopped to avoid sharing my emails).  This is just because some other random gradio textbox had a password I told it to remember.

![image](https://github.com/gradio-app/gradio/assets/2249614/d39bcabc-597b-46a3-bd94-f44a8c562153)

### Logs

```shell
I can't really work around it, these lead to very poor UX but I can't avoid needing multiselect.
```

### System Info

```shell
gradio==3.41.0
gradio_client==0.3.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
> Allow disable of entering arbitrary text. In most cases there is no need for this
> Allow disable of overall x on right that's next to drop down. Too easy to hit x instead of drop-down, and for few entries the overall x is not useful since one can just deselect each.
> Allow list of items selected to be hidden, often no need to see that list if it has impact on UI via change etc

I'm in favor of adding a parameter "typeable" that toggles the first behavior off and on, in cases where users don't want the typing/filtering behavior.

Personally think the 2nd and 3rd ones are too niche to make parameters, and we don't necessarily want to expose parameters for everything. We are working hard on custom components that allow the community to create components if they really need this level of customization. cc @dawoodkhan82 as well

**Comment by pseudotensor** [comment]
Thanks.  The problem with the "list of items to be hidden" one is that if one selects (say) 100 items, then those 100 items will fill-up the UI.  It makes the UI unusable.

That's a common problem.  Upload has same issue.  When upload (say) 100 things, suddenly the UI explodes in size.

![image](https://github.com/gradio-app/gradio/assets/2249614/e69c2a1a-efff-47cf-a5d7-052cfd99c858)

**Comment by abidlabs** [comment]
Perfect thanks @hannahblair. I agree -- for the small tweaks, we can use custom css, and then we can add a parameter for the larger change in making the dropdown typeable/not typeable.

Btw @pseudotensor you might also be interested in this PR: , which allows you to provide shorter names that are displayed in the UI, but keep the full values to send to the backend:

**Comment by pseudotensor** [comment]
@hannahblair Thanks!  Any CSS that would make the main select non-interactive in sense of allowing text entry?
