### ISSUE TITLE
 How about setting server_name to '0.0.0.0' in the gradio.Blocks method?

### ISSUE THREAD

**Issue by heiheiheibj** [gradio-app/gradio#5466]
### Describe the bug

I want  setting server_name to '0.0.0.0'

/home/ubuntu/facefusion/facefusion/uis/core.py:47: GradioDeprecationWarning: `server_name` is deprecated in `Interface()`, please use it within `launch()` instead.
  with gradio.Blocks(theme = get_theme(), title = metadata.get('name') + ' ' + metadata.get('version'),server_name='0.0.0.0') as ui:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

def launch() -> None:
        with gradio.Blocks(theme = get_theme(), title = metadata.get('name') + ' ' + metadata.get('version'),server_name='0.0.0.0') as ui:
                for ui_layout in facefusion.globals.ui_layouts:
                        ui_layout_module = load_ui_layout_module(ui_layout)
                        if ui_layout_module.pre_render():
                                ui_layout_module.render()
                                ui_layout_module.listen()

        for ui_layout in facefusion.globals.ui_layouts:
                ui_layout_module = load_ui_layout_module(ui_layout)
                ui_layout_module.run(ui)

### System Info

```shell
gradio 3.41.2
thanks
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @heiheiheibj - what would be the purpose of making this change? You can set the server_name in the launch method as the warning states.

**Comment by abidlabs** [comment]
Closing for lack of follow up
