### ISSUE TITLE
Use the InferenceClient in external.py

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#5483]
- [ ] I have searched to see if a similar issue already exists.

As of release 0.17.0, the huggingface python client's [InferenceClient](https://huggingface.co/docs/huggingface_hub/package_reference/inference_client) class supports all tasks available in the inference api. We currently use the `requests` module to construct the request manually. We should use the InferenceClient going forward.

Need to remember to set a lower bound on version 0.17.0 in the requirements file.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by abidlabs** [comment]
See internal discussion regarding implementation: https://huggingface.slack.com/archives/C048K60MPNF/p1695147970790289?thread_ts=1691597514.943479&cid=C048K60MPNF
