### ISSUE TITLE
Mention that audio is normalized when converting to wav in docs

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#5484]
Hi there! I actually had this same issue today. I think it might be worth mentioning in the docs that the audio is normalized to avoid confusion.

_Originally posted by @osanseviero in https://github.com/gradio-app/gradio/issues/2789#issuecomment-1712868841_

**Comment by Ifeanyi55** [comment]
I think that is a great idea!

**Comment by abidlabs** [comment]
Feel free to open a PR if you are interested @Ifeanyi55!

**Comment by Ifeanyi55** [comment]
I will do so
