### ISSUE TITLE
Make it easier to get URL query parameters in a Gradio app

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#5485]
Right now, the way to get URL query parameters from within a Gradio app is quite hacky -- e.g. see https://huggingface.co/spaces/radames/gradio-url-params?test=%22dsds%22&value=23231

It would be nice if we could get the URL query parameters from the `gr.Request` object

**Comment by DarhkVoyd** [comment]
I'm eager to help with this, so please let me know how I can get started. Thanks!

**Comment by DarhkVoyd** [comment]
@abidlabs can I help with this?

**Comment by abidlabs** [comment]
Hi @DarhkVoyd yes definitely -- let's get your other PR over the finish line first and then I can give some pointers.

**Comment by DarhkVoyd** [comment]
@abidlabs can I help with this now?

**Comment by abidlabs** [comment]
Yes, a good place to start would be to look at the implementation of the `gr.Request` class and see what would be needed to add the URL query parameters to it. Let me know if you have specific questions!

**Comment by DarhkVoyd** [comment]
@abidlabs I have created a PR, kindly review.

**Comment by abidlabs** [comment]
The way I'd suggest implementing this:

1. Currently we make requests from the frontend to the backend in these two places:

https://github.com/gradio-app/gradio/blob/26fef8c7f85a006c7e25cdbed1792df19c512d02/client/js/src/client.ts#L442

(if queuing is disabled)

and 

https://github.com/gradio-app/gradio/blob/26fef8c7f85a006c7e25cdbed1792df19c512d02/client/js/src/client.ts#L510

(if queuing is enabled)

- As you can see, no query parameters are included in these requests. We should copy the query parameters from the page's URL and into both of these requests

Then, the `gr.Request` object (which is just a wrapper over the FastAPI Request object), should automatically contain the `query_params`

**Comment by DarhkVoyd** [comment]
@abidlabs hey, I have made necessary changes and it works locally. Should I create a PR?

**Comment by abidlabs** [comment]
Yes please @DarhkVoyd!
