### ISSUE TITLE
Remove version.txt from gradio python packages

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#5489]
- [x] I have searched to see if a similar issue already exists.

Right now, we have a `version.txt` for each python package in the repo. This is used for hatch, our build tool, to know the right version for the build. We also have a package.json file that stores the same version number as `version.txt`. I believe that's used by changesets.

We should just use the package.json. Should be possible to configure hatch to read from the json file via a regex pattern (https://hatch.pypa.io/latest/version/#configuration).

This is a good first issue, but we need to make sure with @pngwn that this doesn't break the changesets release (which I believe modifies the `version.txt` file).

**Describe the solution you'd like**  

**Additional context**

**Comment by pngwn** [comment]
We will need to remove the logic that creates/ updates the txt file but it only writes it for the python build process. So shouldn't be an issue.

**Comment by DarhkVoyd** [comment]
I'm a newcomer to the project and I'd like to work on this issue.
I'm eager to help with this, so please let me know how I can get started. Thanks!

**Comment by pngwn** [comment]
Hi @DarhkVoyd! Thanks for showing interest.

This issue requires a couple of steps:

- Remove the `version.txt` files in `/gradio` and `/client/python/gradio_client`
- Update the `tool.hatch.version` section of the `pyproject.toml` in the root of the repo and in `/client/python` to point the path to the `package.json` files instead. The `gradio `package.json is in `gradio/package.json` and the `gradio_client` one is in `client/python/gradio_client/package.json`.
- Update the `pattern` regex in each `pyproject.toml` to match the  version in the `package.json` (let us know if you need some help with this). The version in the package.json is stored like `"version": "1.1.1"` although the number could be anything and it isn't the only text in that file.
- The versioning logic is located [here](https://github.com/gradio-app/gradio/blob/main/pyproject.toml#L44-L46) for `gradio` and [here](https://github.com/gradio-app/gradio/blob/main/client/python/pyproject.toml#L40-L42) fro `gradio_client`. The `package.json` for `gradio` is [here](https://github.com/gradio-app/gradio/blob/main/gradio/package.json) and for `gradio_client` is [here](https://github.com/gradio-app/gradio/blob/main/client/python/gradio_client/package.json).
- Remove the logic that writes the version in `package.json` to `version.txt`. This logic is here: https://github.com/gradio-app/gradio/blob/main/.changeset/fix_changelogs.cjs#L84-L87

Let us know if we can help in anyway, feel free to open a draft PR for us to look at if you get stuck. I think the trickiest part will be the regex.

**Comment by DarhkVoyd** [comment]
@pngwn I had some prior experience with regex, I came up with this, kindly review if this is valid:
```toml
[tool.hatch.version]
path = "gradio/package.json"
pattern = ".*\"version\":\\s*\"([^\"]+)\""
```

**Comment by pngwn** [comment]
@DarhkVoyd This works for me with one small tweak, it needs a named group `version` that captures the actual version.

So this:

```
pattern = ".*\"version\":\\s*\"(?P<version>[^\"]+)\""
```

**Comment by pngwn** [comment]
You can check if it is collecting the version correctly by running `hatch version`

**Comment by DarhkVoyd** [comment]
@pngwn I have ran into problems running scripts from Contribution guide, terminal gives error ``` python: command not found ``` but I do have python3 installed. Kindly help me out.

**Comment by DarhkVoyd** [comment]
@pngwn this piece of code [here](https://github.com/gradio-app/gradio/blob/main/client/python/gradio_client/utils.py#L61) throws an error after the changes. 
Also, I have trouble running contributing guide scripts, terminal throws error ``` python: command not found ```, even tried setting alias for python3 to python. Kindly help me out.

**Comment by pngwn** [comment]
@freddyaboulton @abidlabs Do you know of another way to grab the `__version__`? Can we load in the package.json instead?

@DarhkVoyd Do you run `python` via `python3`? If so, you could change the scripts in your branch so they run `python3` instead of `python`.

**Comment by DarhkVoyd** [comment]
@pngwn Yes, I do run python code via ```python3```. I am confused that isn't ```python``` command for python2, also setting python alias for python3 runs other code on my machine though ```python``` now but throws error on project's scripts. For now, I have changed the scripts to use python3 instead, that how I found out about the error discussed above but is there a permanent solution on my end?

**Comment by DarhkVoyd** [comment]
@pngwn 
So, a lot of files used, 
```python
(pkgutil.get_data(__name__, "version.txt") or b"").decode("ascii").strip()
```
to extract the version, which lead to multiple similar errors after making the changes and deleting the version.txt files. I have currently replaced all of them with the discussed solution above and running tests using ```bash scripts/run_all_tests.sh```. 

Is this a valid solution and should I continue this approach or not?

**Comment by DarhkVoyd** [comment]
@pngwn I have opened the PR, kindly review.
