### ISSUE TITLE
Code font is tiny

### ISSUE THREAD

**Issue by aliabid94** [gradio-app/gradio#5490]
### Describe the bug

The font for some code snippets (but not others) is tiny

<img width="646" alt="Screen Shot 2023-09-11 at 4 26 40 PM" src="https://github.com/gradio-app/gradio/assets/7870876/bc305890-93e0-4374-b8a9-40e24d92ad6d">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://www.gradio.app/guides/key-features

### System Info

```shell
chrome
```

### Severity

I can work around it

**Comment by pngwn** [comment]
I think the typography is different between the docs and guides.
