### ISSUE TITLE
"Use via API" image broken on sharing your app guide

### ISSUE THREAD

**Issue by aliabid94** [gradio-app/gradio#5493]
### Describe the bug

<img width="724" alt="Screen Shot 2023-09-11 at 4 41 43 PM" src="https://github.com/gradio-app/gradio/assets/7870876/53463c3f-528f-4b30-a8bc-3279b836cd8d">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://www.gradio.app/guides/sharing-your-app

### System Info

```shell
chrome
```

### Severity

I can work around it

**Comment by reginareynolds** [comment]
Mind if I tackle this?

**Comment by freddyaboulton** [comment]
Yes go for it @reginareynolds

**Comment by reginareynolds** [comment]
This has actually already been addressed, it would seem. The page no longer shows the issue.

**Comment by freddyaboulton** [comment]
Thanks for checking @reginareynolds !!!
