### ISSUE TITLE
Figure out why Falcon space crashing with 1005 websocket error 

### ISSUE THREAD

**Issue by aliabid94** [gradio-app/gradio#5495]
see discussion here: https://huggingface.slack.com/archives/C02QZLG8GMN/p1694479837319959?thread_ts=1694415259.146919&cid=C02QZLG8GMN

**Comment by abidlabs** [comment]
It looks like its [an issue with the endpoint](https://huggingface.slack.com/archives/C05PZ9K0L6R/p1695630665514589?thread_ts=1695630514.261869&cid=C05PZ9K0L6R), not a gradio issue. I'll close this.
