### ISSUE TITLE
Webcam image input not compatible with 'live' interface

### ISSUE THREAD

**Issue by its-dron** [gradio-app/gradio#55]
I wanted to run a real-time classification task on webcam video, rather than selected frames. The API seems like it should allow this by just setting `live=True` in the interface with a webcam input, but the resulting UI still uses the "click to snap" interface. 

Code snippet:
```python
def classify_image(inp):
    return model.predict(inp)

image = gr.inputs.Image(label="Input Image", source="webcam")
label = gr.outputs.Label(num_top_classes=k)

gr.Interface(fn=classify_image, live=True, inputs=image, outputs=label).launch()
```

Using gradio 1.1.9 on python 3.7

**Comment by aliabid94** [comment]
This has been fixed

**Comment by iatharva** [comment]
But  UI still uses the "click to snap" interface. Are you sure the issue is fixed @aliabd?
