### ISSUE TITLE
Copy-Paste Formatting Issues with Chatbot Text

### ISSUE THREAD

**Issue by huni0103** [gradio-app/gradio#5513]
### Describe the bug

Hi there.

I would like to make an additional suggestion regarding Chatbot Copy.
In the Chatbot, I am replacing "<" , ">" with ">", "<", etc. to display "<" , ">".
However, when I copy the Chatbot text, the "" is also being copied.
I only want "<" and ">" to be copied as they appear in the Chatbot.

Furthermore, I'm representing newlines as "
", but when I copy the Chatbot text, it's copying them as "
" even though they are displayed as "\n" in the Chatbot.

Is there any way to address the issues mentioned above?

We might not be able to use the Copy & Paste feature in the Chatbot until the issues mentioned above are resolved. 😔

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

The result of clicking the Copy button for the screenshot below.
![image](https://github.com/gradio-app/gradio/assets/120710184/2518b841-af19-4edf-b613-3a6ba607876b)

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/120710184/fb34cfa4-30a1-4c6c-b7a2-2868b2af5380)

### System Info

```shell
gradio == 3.42.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @huni0103 just to make sure we understand the issue, can you provide a code snippet we can use to reproduce? It seems that some information was lost in the GitHub markdown processing? You an provide a code snippet like this:

```py
with gr.Blocks() as demo:
   gr.Chatbot(...)
```

**Comment by huni0103** [comment]
Hi @abidlabs.
I apologize in advance for my shortcomings English proficiency.

I would like to express my gratitude for your quick response to the issue. Due to internal security concerns, we cannot share our entire codebase. However, we can provide you with reproducible code and the tested text values.

You've added backslashes(\) before the "<" and ">" symbols in the input text to ensure they are displayed correctly in the ChatBot. Without the backslashes, they seem to be interpreted as HTML tags and do not display correctly in the ChatBot.

Additionally, to ensure proper line breaks in the ChatBot output, you've replaced newline characters (\n) with <br/>.

I would like the Copy button to produce output in the same way it appears to the user in the ChatBot. Specifically, I want "<br/>" to be copied as line breaks, and I prefer not to include the backslash before "<" and ">" symbols. 
It would be preferable for users to be able to copy the text exactly as it appears in the ChatBot.

The input text value used for testing is as follows:
```
Hi Test
one1 <Color2>
<Color3> two2
<Color4> three3
```

```
import gradio as gr
import re
def test(text, state_chatbot):
    print(text)
    print(state_chatbot)
    result = text
    text = text.replace("<", "\<")
    text = text.replace(">", "\>")
    # result = result.replace("<", "\<")
    # result = result.replace(">", "\>")

    text = re.sub(r"\r\n|\r|\n", "<br/>", text)
    # result = re.sub(r"\r\n|\r|\n", "<br/>", result)
    state_chatbot = state_chatbot + [[text, result]]
    return "", state_chatbot, state_chatbot


with gr.Blocks(
    title="Test Web",
) as demo:
    gr.Title = (f"Test Web",)
    with gr.Tab("Chat Translate", elem_id="main"):
        state_chatbot = gr.State([])
        with gr.Row():
            chatbot = gr.Chatbot(
                value=[],
                elem_id="chatbot",
                show_copy_button=True,
                sanitize_html=True,
            )
        with gr.Row():
            text = gr.Textbox(
                show_label=False,
                placeholder="Send a message...",
                lines=2,
                max_lines=20,
                container=True,
                scale=12,
            )

        text.submit(
            test,
            [
                text,
                state_chatbot,
            ],
            [text, state_chatbot, chatbot],
        )

demo.queue(concurrency_count=30, api_open=False)
demo.launch(
    debug=False,
    share=False,
    server_name="127.0.0.1",
    max_threads=500,
    show_api=False,
)
```

![image](https://github.com/gradio-app/gradio/assets/120710184/99fc2051-d3df-4fbf-8dd6-178c7e82b54b)
![image](https://github.com/gradio-app/gradio/assets/120710184/8161cc24-6a45-427d-9114-8df2006bf350)

**Comment by abidlabs** [comment]
The problem really here is that you've had to format your text in a strange way to avoid it being rendered as HTML/Markdown. If we disabled that, then you could just use regular strings without having to make the regex substitution and they would be copied correctly. 

@dawoodkhan82 what do you think about adding a parameter to `gr.Chatbot` that sets whether we treat the text as Markdown or not? This came up earlier in Discord as well, although we suggested a workaround ([internal link](https://huggingface.slack.com/archives/C02QNREU24S/p1694539244120889)).

**Comment by abidlabs** [comment]
Hi @huni0103 this issue is now fixed as we have a way to disabled markdown rendering in a chatbot using the `render_markdown=False` parameter. In your case, you'll also want to disable the html sanitization. 

Here's an example showing how it would work:

```py
import gradio as gr

long_msg = """
Hi **Test**

one1 <Color2>

<Color3> two2
<Color4> three3
"""

with gr.Blocks() as demo:
    gr.Chatbot(
        [[long_msg, long_msg]],
        height=550,
        render_markdown=False,
        sanitize_html=False,
        show_copy_button=True,
    )
demo.launch()
```

This is out on main, we'll probably do a release next week but if you want to try it out, I'd suggest installing from `main`: You can install gradio from main by following the instructions here: https://gradio.app/docs/main
