### ISSUE TITLE
API Related Issue

### ISSUE THREAD

**Issue by samarth70** [gradio-app/gradio#552]
The post request shows Internal Server error when default example is given on interface. Otherwise post request works.How can it be fixed?

**Comment by abidlabs** [comment]
Sorry I don't understand the issue. Can you please provide a code example and more details on what is not working?

**Comment by samarth70** [comment]
This is model's payload and response.
![image](https://user-images.githubusercontent.com/44370096/152912413-f0609497-a7a8-491b-9476-2d29e607d3f8.png)

This is when a default input is given .According to this the api is working.
![image](https://user-images.githubusercontent.com/44370096/152912606-216f9ee6-44d0-4c01-9316-f0df4bef7692.png)
 

**But** when I add my custom inputs as examples in interface.It shows Internal Server error.
![image](https://user-images.githubusercontent.com/44370096/152912868-622687fe-9be6-4c27-a55c-f25f3bc2e374.png)

**Comment by abidlabs** [comment]
@aliabd can you look into this?
