### ISSUE TITLE
Allow table column widths to be specified

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#5520]
- [x] I have searched to see if a similar issue already exists.

(I think I raised this internally a few month ago, but it looks like I didn't open an issue.)

**Is your feature request related to a problem? Please describe.**  

Table columns sometimes become too wide and it degrades UX. For example, in [this Space](https://huggingface.co/spaces/hysts/daily-papers), the title column is too wide and it makes some columns out of the view. (There's the upvotes column on the right.)

![](https://github.com/gradio-app/gradio/assets/25161192/1aa56b9e-4dcf-41b4-9e5e-335c4b74bb6a)

Also, in the case of [this Space](https://huggingface.co/spaces/ICCV2023/ICCV2023-papers), I needed to use `gr.HTML` instead to avoid the UX degradation.

![](https://github.com/gradio-app/gradio/assets/25161192/06c6461a-a780-4308-88b1-6ec570cd8bd3)

Currently, `gr.Dataframe` has some nice features, like sorting column and scrolling, so I feel like it would be better to use `gr.Dataframe` to show tables in general, but this UX degradation is sometimes so bad that I have to choose `gr.HTML`.

It would be nice to be able to specify the column width of `gr.Dataframe`.

**Comment by abidlabs** [comment]
Maybe we could provide width scales that serve as ratios for the columns -- we'll consider this, thanks @hysts
