### ISSUE TITLE
.clear event listener doesn't work on audio component

### ISSUE THREAD

**Issue by fffiloni** [gradio-app/gradio#5522]
### Describe the bug

The clear event listener that is supposed to be triggered when the user clears the component (e.g. image or audio) using the X button for the component, doesn't work for the Audio component.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

I have crafted a demo about that bug here : https://huggingface.co/spaces/fffiloni/gradio-bug-clear-event

### Logs

```shell
no logs
```

### System Info

```shell
gradio versions : 3.42.0 —› 3.44.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @fffiloni -- we'll get this fixed. cc @hannahblair
