### ISSUE TITLE
I want to change the background image of my gr.Blocks, following the documents but failed

### ISSUE THREAD

**Issue by maceygo** [gradio-app/gradio#5539]
### Describe the bug

with gr.Blocks(css=".gradio-container {background: url(file='/mnt/langchain-ChatGLM/img/201102142152-9-1200.jpg') !important}") as demo:

I use this code to custom css for my block , but it doesn't work.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

with gr.Blocks(css=".gradio-container {background: url(file='/mnt/langchain-ChatGLM/img/201102142152-9-1200.jpg') !important}") as demo:

### System Info

```shell
None
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @maceygo you are missing the backslash before and the quote around `/file`. It should be something like this:

```py
with gr.Blocks(css=".gradio-container {background: url('/file=cheetah.jpg')}") as demo:
    gr.Textbox()
    
demo.launch()
```

Thanks -- by the way, for general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
