### ISSUE TITLE
API to Huggingface leaderboard

### ISSUE THREAD

**Issue by smartserviceproperty** [gradio-app/gradio#5542]
### Describe the bug

It looks like the API have been updated because did works for 6 days ago. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

This code did works
client = Client("https://huggingfaceh4-open-llm-leaderboard.hf.space/")
result = client.predict()
print(result)

I did also use your example. None of them works
ValueError: This Gradio app might have multiple endpoints. Please specify an `api_name` or `fn_index`

### System Info

```shell
I did both install and upgrade several times to be sure.
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @smartserviceproperty as the error indicates, the LLM Leaderboard has multiple API endpoints corresponding to the different functionalities (e.g. searching, submitting for evaluation). To use a particular endpoint, you must specify the `fn_index`. To see the different options, you can do:

```py
from gradio_client import Client

client = Client("https://huggingfaceh4-open-llm-leaderboard.hf.space/")
client.view_api()
```

If there's an API endpoint that is no longer available, then this should be brought up in the Discussion page of the Space -- you can see that here: https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard/discussions?status=open&type=discussion

Thanks, I'll go ahead and close this issue as there isn't a bug with `gradio` or a feature request.
