### ISSUE TITLE
Doc improvements for gr.Error, gr.Warning, and gr.Info

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#5567]
- [x] I have searched to see if a similar issue already exists

As a new user, I struggle a bit what's the difference in the usage between the three of them

Some general points
* `gr.Info` has no info/description https://www.gradio.app/docs/info 
* `gr.Warning` could have an example
* It's not super clear that `gr.Error` must be raised, while the other two just called

Would it make sense to unify them on the same page? (or have them sequentially in the navbar?)
Internal thread: https://huggingface.slack.com/archives/C02QZLG8GMN/p1694724286144969

**Comment by abidlabs** [comment]
Agreed! Thanks for creating the issue @osanseviero
