### ISSUE TITLE
Gradio cannot generate public url

### ISSUE THREAD

**Issue by Carringbrinks** [gradio-app/gradio#5570]
### Describe the bug

share is set to True, but nothing happens after the code runs to the local url.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

![image](https://github.com/gradio-app/gradio/assets/61037413/bfba2d76-3c6f-4679-8ddc-0ce87cd15251)

import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
    
if __name__ == "__main__":
    demo.launch(share=True)   

### System Info

```shell
yes
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @Carringbrinks this is often due to an antivirus blocking a specific binary file from being downloaded. Please take a look at this issue: https://github.com/gradio-app/gradio/issues/3677 and try the suggestions there. If that doesn't solve your issue, please feel free to chime in there.

**Comment by Carringbrinks** [comment]
What is the domain name of this specific binary software?

**Comment by abidlabs** [comment]
https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_darwin_arm64

See this PR for more details: https://github.com/gradio-app/gradio/pull/4773

**Comment by Carringbrinks** [comment]
![image](https://github.com/gradio-app/gradio/assets/61037413/6ce20bfa-ee3d-4114-b17a-6bdd17fe8ff7)
There is this file under my gradio file. You may not understand what I mean. The problem I have is starting the gradio service. When I set share=True, only a local url was returned to me, but I The code is running on a Linux server, so I want to pass the public url test, but after the local url appears in the program, there is no response, so I have no way to investigate the cause.
