### ISSUE TITLE
A gradio demo app has error 

### ISSUE THREAD

**Issue by wadeok** [gradio-app/gradio#5572]
### Describe the bug

I copy and paste the code from this demo: https://github.com/gradio-app/gradio/blob/main/demo/cancel_events/run.py, then launch it, when I click the `Run Expensive Calculation` button, after about 5s, the output widget become error:
![img_v2_d5ca8cb7-b541-4800-921f-bcc525c2a87g](https://github.com/gradio-app/gradio/assets/138575543/b0da077e-30bd-40b5-8af9-c966314b7fdb)
BTW, how to debug the gradio app error, even though I set `debug=True` in `demo.launch()`, here still not print traceback.
@abidlabs 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

run the code from: https://github.com/gradio-app/gradio/blob/main/demo/cancel_events/run.py, and click the `Run Expensive Calculation` button

### System Info

```shell
windows 10
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @wadeok ! I cannot reproduce the issue. What version of gradio are you running? Can you run `gradio environment` and share the results?

**Comment by wadeok** [comment]
Hi @freddyaboulton , I found I can not execute `gradio environment` because my gradio version is 3.32.0, then I upgrade to 3.34.3, everything is OK now ~
