### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by p0mad** [gradio-app/gradio#5580]
### Describe the bug

Traceback (most recent call last):
File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 523, in run_predict
output = await app.get_blocks().process_api(
self.call_function(
.to_thread.run_sync(
(

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Hi,
I'm using Gradio with Blocks to call an APIendpoint!

the endpoint takes for a while ( at most 10 secs) to respond in output ... but i guess gradio wont wait until then!

its the NLP processing task and it works for less that 5 secs but not more!

### System Info

```shell
I'm using gradio 3.42.0
on win 10 and the API endpoint is also Win 10!
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @p0mad can you share the link to the Space or deployed Gradio app as well as the code you are using to call the API endpoint? We'll need a minimal reproducible example to investigate this issue

**Comment by abidlabs** [comment]
Will close for now -- we can reopen with a self-contained repro.
