### ISSUE TITLE
regression in showing pandas dataframes -- chopped and force wrapped

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#5592]
### Describe the bug

Regression in showing pandas dataframes -- chopped and force wrapped

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr

demo = gr.Blocks()

with demo:
    import pandas as pd
    df0 = pd.read_csv('df0.csv')
    langchain_mode_path_text = gr.Dataframe(value=df0,
                                            visible=True,
                                            label='LangChain Mode-Path',
                                            show_label=False,
                                            interactive=False)
demo.queue()
demo.launch()
```

[df0.csv](https://github.com/gradio-app/gradio/files/12654055/df0.csv)

Only seen after going from gradio==3.41.0 to gradio==3.44.3

Also, there seems to be some unnecessary animation of the dataframe, showing it shrink into place, while before it just shows up nicely at once.

### Screenshot

gradio==3.44.3

![image](https://github.com/gradio-app/gradio/assets/2249614/e5458a4f-346c-4ee7-9e65-a4908b58bc3b)

gradio==3.41.0:

![image](https://github.com/gradio-app/gradio/assets/2249614/7a0ce523-6376-4d51-8e06-9dcd16483e8c)

### System Info

```shell
gradio==3.44.3
gradio_client==0.5.0
```

### Severity

Not quite Blocking usage of gradio, just can't upgrade to this version until fixed since too noticeable visual bug.

**Comment by abidlabs** [comment]
Thanks @pseudotensor -- yes we're looking into this here: https://github.com/gradio-app/gradio/issues/5458#issuecomment-1712313516, but let's keep this issue open for visibility. We'll get this fixed soon!
