### ISSUE TITLE
Stop Recording Button not working when change demo.launch("server_name: "xxx.xxx.xxx.xxx)

### ISSUE THREAD

**Issue by engperini** [gradio-app/gradio#5594]
### Describe the bug

I bring here a small code to show my issue.  I'm running 
the app in Raspberry Pi OS 64bit and the clients are in my local network, like my laptop and smartphone. First I only got access the app with the laptop and smartphone if the server_name will the server physical address, example server_name:"192.168.16.109" its my raspberry pi address. So, I need to use it. 

The issue is, when I use server_name, the button of Stop Recording not work (even if I access it locally neither remotes clients.  I have tested a bigger code, all other functions worked well, but Stop Recording not. 

Not Work - test
![notwork](https://github.com/gradio-app/gradio/assets/117356668/ce5cf781-454a-412e-80db-fcc8ae55628a)

Work - test
![worked](https://github.com/gradio-app/gradio/assets/117356668/f2e1bf00-5913-4c24-9c18-1a29b2458acd)

As you can see at the third image below, my full demo app is working but the Stop Recording , do not.  I took the last screenshot on a client side . 

![full_not work](https://github.com/gradio-app/gradio/assets/117356668/c6659dbf-c20e-4f6e-8162-3789ebd9334c)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
#test-audio
import gradio as gr

def test(audiotest):
    print(audiotest)
    return 'it worked'
    
with gr.Blocks() as demo:
    with gr.Row():
        audio = gr.Audio(source='microphone', type="filepath")
        text = gr.Textbox()
    audio.stop_recording(test, inputs = audio, outputs = text)

if __name__ == "__main__":
    demo.launch(server_name="192.168.16.109", server_port=7860)
```

### Screenshot

Not Work - test
![notwork](https://github.com/gradio-app/gradio/assets/117356668/ce5cf781-454a-412e-80db-fcc8ae55628a)

Work - test
![worked](https://github.com/gradio-app/gradio/assets/117356668/f2e1bf00-5913-4c24-9c18-1a29b2458acd)

As you can see at the third image below, my full demo app is working but the Stop Recording , do not.  I took the last screenshot on a client side . 

![full_not work](https://github.com/gradio-app/gradio/assets/117356668/c6659dbf-c20e-4f6e-8162-3789ebd9334c)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 3.44.3
gradio_client version: 0.5.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.0.1
fastapi: 0.99.1
ffmpy: 0.3.1
gradio-client==0.5.0 is not installed.
httpx: 0.24.1
huggingface-hub: 0.17.1
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.24.3
orjson: 3.9.7
packaging: 23.1
pandas: 2.0.3
pillow: 9.5.0
pydantic: 1.10.12
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.5.0
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.9.0
httpx: 0.24.1
huggingface-hub: 0.17.1
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.5.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @engperini thanks for creating this issue. The cause of this issue is that most browsers prevent recording from a microphone unless you have HTTPS certificates installed, with the exception of localhost. That's why your demo is running fine on localhost but not on the other IP address. 

To fix this issue, please install a SSL certificate on your machine. You can find previous discussions regarding that here: https://github.com/gradio-app/gradio/issues/563

Admittedly, this bug is pretty opaque and we have an existing issue to make the error clearer: https://github.com/gradio-app/gradio/issues/2551

**Comment by abidlabs** [comment]
cc @hannahblair

**Comment by engperini** [comment]
Thank you! It worked as #2551 solution:
`openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365 -nodes` on project folder

I also make [mkcert](https://github.com/FiloSottile/mkcert) but the first one is much easier. For anyone who wants to make it in Raspberry Pi OS 64:

`
#install Go https://golang.org/dl/  I choose arm64 to Raspiberry Pi Os 64b

mkdir ~/src && cd ~/src
wget https://go.dev/dl/go1.21.1.linux-arm64.tar.gz
sudo tar -C /usr/local -xzf go1.21.1.linux-arm64.tar.gz
rm go1.21.1.linux-arm64.tar.gz

sudo nano ~/.profile
#add it at the end of the file
PATH=$PATH:/usr/local/go/bin
GOPATH=$HOME/go
#crtl x - save

source ~/.profile
go version

#util here - go installed, now build the mkcert

git clone --recurse-submodules https://github.com/FiloSottile/mkcert.git
cd mkcert
GOARM=7 GOOS=linux GOARCH=arm go build -o "mkcert-$(git describe --tags)-linux-arm7"

#rename mkcert-<version>-linux-arm7
mv mkcert-v1.4.4-linux-arm7 mkcert

sudo apt update && sudo apt upgrade -y
sudo apt install libnss3-tools
sudo install mkcert /usr/local/bin

#return to your directory
cd
mkcert

#this is the result
pi@raspberrypi:~ $ mkcert
Usage of mkcert:

        $ mkcert -install
        Install the local CA in the system trust store.

        $ mkcert example.org
        Generate "example.org.pem" and "example.org-key.pem".

        $ mkcert example.com myapp.dev localhost 127.0.0.1 ::1
        Generate "example.com+4.pem" and "example.com+4-key.pem".

        $ mkcert "*.example.it"
        Generate "_wildcard.example.it.pem" and "_wildcard.example.it-key.pem".

        $ mkcert -uninstall
        Uninstall the local CA (but do not delete it).`

**Comment by abidlabs** [comment]
Great thanks @engperini for providing the walkthrough!
