### ISSUE TITLE
POST request timeout

### ISSUE THREAD

**Issue by shpower** [gradio-app/gradio#5597]
- [yes ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
The POST request timeout is 1 min. I would like to increase it to 5 or even 10 minutes.

**Describe the solution you'd like**  
Please provide me a parameter in Chatbot's list of parameters or a place where I can modify it automatically in your app after I will download it through pip.

**Comment by freddyaboulton** [comment]
Hi @shpower - to get around the timeout enable the queue in your demo, e.g. `demo.queue().launch()`. More info here: https://www.gradio.app/guides/key-features#queuing

**Comment by shpower** [comment]
Hi,
Thank you.
 I read that and implemented the queue. However, I do not want to disable the timeout, I want to enlarge the timeout, for example, to a 5 seconds.

**Comment by freddyaboulton** [comment]
Can you explain more? A 5 second request is timing out with the queue? Please share a minimal reproducible example and we can take a look!
