### ISSUE TITLE
File uploading fails when file is small

### ISSUE THREAD

**Issue by kamalkraj** [gradio-app/gradio#56]
```python
import gradio as gr
import pandas as pd

def predict(file_obj,Question):
    df = pd.read_csv(file_obj.name,dtype=str)
    return df

def main():
    io = gr.Interface(predict, ["file",gr.inputs.Textbox(placeholder="Enter Question here...")], "dataframe")
    io.launch()

if __name__ == "__main__":
    main()
```
The file is not uploaded properly when the file size is small. I checked the temp file, it is empty.
You can use the code above to reproduce the issue. 
Attached sample file as zip. Unzip before uploading
[tapas.zip](https://github.com/gradio-app/gradio/files/5255453/tapas.zip)

**Comment by dawoodkhan82** [comment]
@kamalkraj fixed with latest commit.

**Comment by kamalkraj** [comment]
@dawoodkhan82 
I installed the gradio using setup.py
<img width="1680" alt="Screenshot 2020-10-08 at 6 40 59 PM" src="https://user-images.githubusercontent.com/17096858/95463030-e9124d80-0995-11eb-9014-ce3f6d70a889.png">

New error

**Comment by dawoodkhan82** [comment]
@kamalkraj works for me after using `python setup.py install`. Make sure you uninstall first.

![Screen Shot 2020-10-08 at 9 18 31 AM](https://user-images.githubusercontent.com/12725292/95463906-5945b280-0947-11eb-83de-b15b5b5b6b21.png)
