### ISSUE TITLE
Can not update DropdownList.

### ISSUE THREAD

**Issue by tlqiao** [gradio-app/gradio#5600]
### Describe the bug

Hi,
I want to implement a feature, include two dropdown list, after choose the first dropdown list value, then can update second dropdown list choices.

**Here is my code.**

def get_api_url_by_server(server_name):
    with MongoDBManager("speedtest") as db_manager:
        api_url_list = db_manager.get_apiUrl_by_server(server_name=server_name)
    return api_url_list

with gr.Blocks() as single_api:
    server_list = update_server_list()
    with gr.Row():
        gr.Button(value="Get API Details")
        server_dropdown = gr.Dropdown(
            choices=server_list, label="Server List")
        api_url_list_dropdown = gr.Dropdown(
            choices=api_url_list, label="API Url List")
        method_list = gr.Dropdown(
            choices=api_method_list, label="API Methods")
        def update_api_url_list(server_name):
            list = get_api_url_by_server(server_name)
            return api_url_list_dropdown.update(choices=list)
        server_dropdown.select(update_api_url_list, inputs=server_dropdown,
                               outputs=api_url_list_dropdown)

When I launch the app, the second dropdown list "api_url_list_dropdown" can not choose value, it is read only. the screenshot as below.
<img width="1078" alt="image" src="https://github.com/gradio-app/gradio/assets/16421412/3331b477-2f58-4e57-933b-15ffb7c68219">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Put the above code in VS code, launch the app, can reproduce it.

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 3.44.3
gradio_client version: 0.5.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.1.0
altair: 4.2.2
fastapi: 0.99.1
ffmpy: 0.3.0
gradio-client==0.5.0 is not installed.
httpx: 0.24.0
huggingface-hub: 0.14.1
importlib-resources: 5.12.0
jinja2: 3.1.2
markupsafe: 2.1.1
matplotlib: 3.7.1
numpy: 1.24.0
orjson: 3.8.11
packaging: 23.0
pandas: 2.0.1
pillow: 9.5.0
pydantic: 1.10.7
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.28.2
semantic-version: 2.10.0
typing-extensions: 4.5.0
uvicorn: 0.22.0
websockets: 11.0.2
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.4.0
httpx: 0.24.0
huggingface-hub: 0.14.1
packaging: 23.0
requests: 2.28.2
typing-extensions: 4.5.0
websockets: 11.0.2
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @tlqiao when I tried running your code, I got a `name 'update_server_list' is not defined` error. Please provide a complete example we can use to reproduce this issue. 

The issue you are facing might be resolved by setting `interactive=True` in the `api_url_list_dropdown()` Dropdown component.

**Comment by tlqiao** [comment]
Thanks @abidlabs, I set interactive=True in the api_url_list_dropdown() Dropdown component, it works well.

**Comment by abidlabs** [comment]
Glad to hear it!
