### ISSUE TITLE
custom error message appears cropped

### ISSUE THREAD

**Issue by cowanAI** [gradio-app/gradio#5603]
### Describe the bug

<img width="479" alt="image" src="https://github.com/gradio-app/gradio/assets/128092052/8fe407aa-21d0-433a-b02f-483102574c80">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

<img width="479" alt="image" src="https://github.com/gradio-app/gradio/assets/128092052/45e29e62-71fd-42fd-a360-6f269805e60e">

### Screenshot

<img width="479" alt="image" src="https://github.com/gradio-app/gradio/assets/128092052/f30f47d6-a05f-4b14-9a4e-c84072e24f76">

### Logs

```shell
latest gradio version
```

### System Info

```shell
latest gradio version
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @cowanAI can you please provide a repro?

**Comment by abidlabs** [comment]
Will close for now -- can reopen once we have a repro.

**Comment by cowanAI** [comment]
for sure @abidlabs I don't think it's a big issue right now, I think what is happening it's simply an overflow when you add a lot of text like in my case, maybe you could try adding a long error text and you will find the same, but not a big issue, also, do you still guys plan in creating the export pdf file function? thanks for your help!
