### ISSUE TITLE
unix socket support

### ISSUE THREAD

**Issue by cyberb** [gradio-app/gradio#5606]
Is it possible to support unix sockets?
Uvicorn seems to support it.
I need it for self hosting platform (https://github.com/syncloud/platform) where multiple apps run behind a single nginx and it is easier to control backend apps based on files versus ports.

**Comment by abidlabs** [comment]
Hi @cyberb can you elaborate a bit more -- what would supporting unix sockets entail?

Just fyi we have a guide on setting up gradio apps behind nginx here: https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx

**Comment by cyberb** [comment]
I mean when running nginx (or any other reverse proxy) in front of an unknown combination of web apps (installed by user) it is easier to proxy backends by unix socket file paths like this:
```
proxy_pass      http://unix:/var/snap/$app/common/web.socket: ;
```

Instead of assigning ports per app which may result in a conflict.

I understand it is a specific use case but I think having such an option is a useful thing.

I am actually doing this for https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/master so I can add it to Syncloud app store.

I can actually try to prepare PR if you want.

**Comment by abidlabs** [comment]
Thanks for explaining and for offering to make the PR @cyberb! Before you do the work, what changes would be needed to implement this in `gradio`? It sounds like a parameter in `.launch()` analogous to `server_port` or `server_name` would be needed. What internal changes would need to be done?

**Comment by cyberb** [comment]
form what I can see uvicorn.Config
https://github.com/gradio-app/gradio/blob/88d43bd124792d216da445adef932a2b02f5f416/gradio/networking.py#L182
supports additional parameter called uds
https://github.com/encode/uvicorn/blob/8a8b7adf275e1edfc1cc6fa7486a6159f13c3c17/uvicorn/config.py#L201

so yes, something like uds or server_unix_socket if provided should override server_host and server_port.
Also thins like port availability checks should also become conditional.
https://github.com/gradio-app/gradio/blob/88d43bd124792d216da445adef932a2b02f5f416/gradio/networking.py#L167

I was planning to test this on stable-diffusion app first, just wanted to make sure it does not exist already.

**Comment by abidlabs** [comment]
On further thought, I think this is quite niche, and we wouldn't want to expose every uvicorn argument as parameters in gradio. Instead, a different approach might be to mount Gradio within a larger FastAPI instance which can be launched on a unix socket. Would this work? 

Instructions for that here: https://www.gradio.app/docs/mount_gradio_app

cc @freddyaboulton @aliabid94 feel free to chime in if you disagree

**Comment by abidlabs** [comment]
Closing for lack of follow up -- if you do get a chance to try, let us know if this doesn't work @cyberb.

**Comment by cyberb** [comment]
I was experimenting a bit with the idea of just setting host to "/path/to/socket" idea so I do not have to change public api or client app in any way.

Some changes are done on this fork: https://github.com/cyberb/gradio/commits/main

It almost works but one of the issues now is that websocket client is none on this line and it throws:

https://github.com/gradio-app/gradio/blob/46334780dbbb7e83f31971d45a7047ee156a0578/gradio/queueing.py#L359

Error "'NoneType' object has no attribute 'host'"

**Comment by cyberb** [comment]
looks like latest main branch does not use http to call internal api which I think should fix this issue, will upgrade sd-webui from gradio 3.41.2 to 3.42.2 (hopefully it does break anything)
https://github.com/gradio-app/gradio/pull/5165

**Comment by cyberb** [comment]
ok it finally works: https://github.com/gradio-app/gradio/pull/5883

**Comment by abidlabs** [comment]
As discussed in #5883, this is out of scope of Gradio. Please see here for a workaround: https://github.com/gradio-app/gradio/pull/5883#issuecomment-1846242300
