### ISSUE TITLE
Ensure `elem_id` is only used once in a component

### ISSUE THREAD

**Issue by hannahblair** [gradio-app/gradio#5607]
### Describe the bug

We're currently using `elem_id` multiple times in a few components - see HTML and Markdown. It's being assigned to both the Blocks element and the html tag of the component itself. We should only be using `elem_id` once to ensure that the `id` is unique to a entire page, per best practices. 

This is a bug as users may be applying logic/styling to the wrong component right now. However, it's also a breaking change depending on the logic in place in users' demos currently, so this change should be made in 4.0. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

n/a

### System Info

```shell
n/a
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Ah nice catch!
