### ISSUE TITLE
GRADIO LIVE HELP

### ISSUE THREAD

**Issue by aynur1lololkk** [gradio-app/gradio#5622]
### Describe the bug

gradio.live is not working, it says on the official website: No interface is running right now. When will it be fixed?
![GRADIO](https://github.com/gradio-app/gradio/assets/145508660/1ca305c4-4468-4d0e-9a74-84a958c7516b)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

![image](https://github.com/gradio-app/gradio/assets/145508660/eeacfdaf-602f-4bd1-9190-e6368dd7cea0)

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/145508660/b5472467-d443-4e5d-a5c8-696b0a656049)

### System Info

```shell
gradio.Interface(fn, inputs, outputs, ···)
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @aynur1lololkk that is the expected behavior. gradio.live is not a website -- it hosts public gradio interfaces created by users at random subdomains: `xxxxxxxxxx.gradio.live`. 

What are you trying to accomplish?

**Comment by Tarunnagpal7** [comment]
Hello @aynur1lololkk its public host its free for 48 hours to operate by users at random subdomans , where the system is created for gradio if the connection error occurs then its diconnected then its show that "NO INTERFACE IS AVAILABLE" . If anyone wants no disruption than they takes premium.

**Comment by Tarunnagpal7** [comment]
How can I help you ??

**Comment by abidlabs** [comment]
Closing for lack of follow up
