### ISSUE TITLE
Update `LoginButton` / `LogoutButton` style

### ISSUE THREAD

**Issue by Wauplin** [gradio-app/gradio#5628]
Would be nice to update the style of `LoginButton` and `LogoutButton` to match the official HF badge for those (see [badges](https://huggingface.co/datasets/huggingface/badges#sign-in-with-hugging-face)).

AFAIK buttons cannot be simple images so let's use some CSS to have the same layout. I have made some experiments and I'm able to reproduce it in a local demo. It would be nice to have those directly included in Gradio instead of relying on custom CSS. @abidlabs I can open a PR to implement this but I'd need a bit of context on how CSS works in Gradio :grimacing: (I'm no CSS/Svelte expert btw, I just googled it ^^).

Here is the custom CSS I'm currently using. I use the buttons both in a gr.Row and outside of a gr.Row as it changes the default width of the buttons (which we should fix in this issue).

```py
import gradio as gr

CSS = """
@media (prefers-color-scheme: light) {
  #oauth-button {
    background: #000000;
    color: #FFFFFF;
  }
}

@media (prefers-color-scheme: dark) {
  #oauth-button {
    background: #FFFFFF;
    color: #000000;
  }
}

#oauth-button {
    border-radius: 50vh;
    height: 50px;
    min-width: max-content;
}
"""

with gr.Blocks(css=CSS) as demo:
    gr.Markdown("# Within `gr.Row`")
    with gr.Row():
        gr.LoginButton(elem_id="oauth-button")
        gr.LogoutButton(elem_id="oauth-button")

    gr.Markdown("# Outside `gr.Row`")
    gr.LoginButton(elem_id="oauth-button")
    gr.LogoutButton(elem_id="oauth-button")


demo.launch()
```

Which looks like this:

![image](https://github.com/gradio-app/gradio/assets/11801849/42ab42ca-9269-437e-a30d-bddaaf811f6b)

and 

![image](https://github.com/gradio-app/gradio/assets/11801849/e484e6fc-853a-4ab4-8bbc-90c2acf63c77)

cc @julien-c

**Comment by Wauplin** [comment]
As suggested by @apolinario on [slack](https://huggingface.slack.com/archives/C02136Y252P/p1695210555084969?thread_ts=1694700569.169089&cid=C02136Y252P) (private link), we should also add this styling to the `gr.DuplicateButton` so that HF buttons are branded the same way.

**Comment by julien-c** [comment]
> AFAIK buttons cannot be simple images

but maybe that's the simplest way to do this no? allow SVG buttons in gr.Button?

**Comment by Wauplin** [comment]
> but maybe that's the simplest way to do this no? allow SVG buttons in gr.Button?

The advantage of CSS is that we can update the text content when the user is logged in from `"Sign in with HF"` to `"Signed in as Wauplin"` and disable it.

**Comment by abidlabs** [comment]
Question -- do we want the buttons to look the same across different themes? Or should we stylize the buttons based on the theme like we do with regular buttons?

**Comment by Wauplin** [comment]
I would say "we want the buttons to look the same across different themes" (for branding) but I'm not very well aware of all the aspects of theming.

**Comment by abidlabs** [comment]
As it relates to the buttons, the themes set the **border radius of the buttons** as well as the **colors** in light and dark mode. It seems like here, both are fixed so we wouldn't want them to adjust based on the theme. 

In that case, maybe we can add an internal parameter `_type` to the `gr.Button()` that is set by `gr.LoginButton` / `gr.Logoutbutton` and that overrides the css styles like what @Wauplin has suggested. @hannahblair do you want to take this?

**Comment by Ifeanyi55** [comment]
Personally, I would prefer that the buttons style change according to theme. I feel that will add some flair to gradio apps and give the developer different style options. But if implementing that will be hard, then we can do it in the way suggested by @Wauplin

**Comment by Wauplin** [comment]
Friendly ping on this issue. Is there any decision on the direction to take? Having a coherent style for login/logout buttons would be very nice :pray:

**Comment by pngwn** [comment]
The downside to SVG as the whole thing is not only text customisation but i18n. 

I'll have a play shortly and see what it feels like with the brand styling. I do have some reservations due to the border radius differences.

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/9254
