### ISSUE TITLE
Cannot display outputs when reusing cached examples

### ISSUE THREAD

**Issue by aaronng91** [gradio-app/gradio#5634]
### Describe the bug

When using Examples and setting cache_examples=True, the inputs/outputs load fine when you start app for the first time. However, if you reload the app which reads from the same cache, the outputs no longer load. No examples or methods have changed.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr

def combine(a, b):
    return a + " " + b

with gr.Blocks() as demo:
    txt = gr.Textbox(label="Input", lines=2)
    txt_2 = gr.Textbox(label="Input 2")
    txt_3 = gr.Textbox(value="", label="Output")
    btn = gr.Button(value="Submit")
    btn.click(combine, inputs=[txt, txt_2], outputs=[txt_3])
    
    gr.Markdown("## Text Examples")
    gr.Examples(
        [["hi", "Adam"], ["hello", "Eve"]],
        [txt, txt_2],
        txt_3,
        combine,
        cache_examples=True,
    )

if __name__ == "__main__":
    demo.launch()
```

### Screenshot

Output loads fine when initializing cache for the first time
![Screenshot 2023-09-20 at 17 18 18](https://github.com/gradio-app/gradio/assets/8050514/91414b6e-f97d-41c5-be8a-14774bd2dcb3)

Output no longer loads when reusing the same cache
![Screenshot 2023-09-20 at 17 17 57](https://github.com/gradio-app/gradio/assets/8050514/3c337792-a2ed-4262-951e-30e5c97dd36f)

### Logs

Logs when initializing cache for the first time
```
Caching examples at: '/home/aaronn/git/test/gradio_cached_examples/6'
Caching example 1/2
Caching example 2/2
Caching complete

Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
```

Logs when reusing cache
```
Using cache from '/home/aaronn/git/test/gradio_cached_examples/6' directory. If method or examples have changed since last caching, delete this folder to clear cache.

Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
gradio==3.41.2
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Thanks @aaronng91 - I can reproduce.
