### ISSUE TITLE
Dropdown choices not updating based on global variable

### ISSUE THREAD

**Issue by shimizust** [gradio-app/gradio#5640]
### Describe the bug

I have a use case where the choices in the Dropdown can change over time for all users.

It appears that when the gradio app is first launched, the dropdown choices are permanently set. Even if I make the `choices` parameter refer to a global variable, and update the global variable, it does not reflect on subsequent loads.

I think some possible solutions could be:
- Allow passing a callable to the Dropdown `choices` parameter, which would be run on app load to get the most updated values (ideal)
- Have the Dropdown choices updated when referencing a global variable

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Here's a minimal example of the issue. The dropdown references a global variable for choices. A user can add new choices, but on refreshing the page, the dropdown shows the original choices, even though global_choices has been modified.

```
import gradio as gr

global_choices = ["a", "b", "c"]

def update_dropdown(textbox_value):
  global global_choices
  global_choices.append(textbox_value)
  return gr.update(choices=global_choices)

with gr.Blocks() as demo:
  dropdown = gr.Dropdown(choices=global_choices, label="Letters", interactive=True)
  textbox = gr.Textbox(label="New Dropdown Choice")
  button = gr.Button(value="Add Dropdown Choice")

  button.click(fn=update_dropdown, inputs=[textbox], outputs=[dropdown])

demo.launch()
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 3.44.4
gradio_client version: 0.5.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.1
fastapi: 0.103.1
ffmpy: 0.3.1
gradio-client==0.5.1 is not installed.
httpx: 0.25.0
huggingface-hub: 0.17.2
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.26.0
orjson: 3.9.7
packaging: 23.1
pandas: 2.1.1
pillow: 10.0.1
pydantic: 2.3.0
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.8.0
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.9.1
httpx: 0.25.0
huggingface-hub: 0.17.2
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @shimizust thanks for creating this issue. Here's how I would do this:

1. First of all, you don't need to use global variables. Any variable defined outside of the function you pass into a gradio event listener is shared across all users.

2. When the Gradio app first loads, you use the `gr.Blocks.load()` event to update the choices of the Dropdown. 

Here's how it looks:

```py
import gradio as gr

global_choices = ["a", "b", "c"]

def update_dropdown(textbox_value):
    global_choices.append(textbox_value)
    return gr.Textbox(choices=global_choices)

def get_latest_choices():
    return gr.Textbox(choices=global_choices)

with gr.Blocks() as demo:
    dropdown = gr.Dropdown(choices=global_choices, label="Letters", interactive=True)
    textbox = gr.Textbox(label="New Dropdown Choice")
    button = gr.Button(value="Add Dropdown Choice")
    
    button.click(fn=update_dropdown, inputs=[textbox], outputs=[dropdown])

    demo.load(get_latest_choices, inputs=None, outputs=[dropdown])

demo.launch()
```

Notice that I'm returning `gr.Textbox` instead of `gr.Textbox.update()`. This is the new preferred syntax as of the next release of `gradio`. If you would like to use this syntax, please install gradio from main by following the instructions here: https://gradio.app/docs/main. If you are using an older version of `gradio`, please use `gr.Textbox.update()` -- it should still work (although I didn't test it this way).

**Comment by shimizust** [comment]
@abidlabs Thanks! I didn't realize there was an on-load event handler, this is exactly what I want.
