### ISSUE TITLE
Background image is cut off when using `gr.Image(tool='sketch')`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#5645]
### Describe the bug

I'm using `gr.Image(tool='sketch')` in my [ViTMatte Space](https://huggingface.co/spaces/hysts/ViTMatte) to let people draw a trimap, but the background image doesn't seem to be properly fit into the sketch region, and the right side is cut off. Due to this, the drawing feature of this app doesn't work as intended.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://huggingface.co/spaces/hysts-debug/sketch-cut-off

```python
import gradio as gr

with gr.Blocks() as demo:
    image1 = gr.Image(width=400, height=400, interactive=True)
    image2 = gr.Image(width=400, height=400, interactive=True, tool="sketch")

    gr.Examples(examples=[["images/bulb_rgb.png", "images/bulb_rgb.png"]], inputs=[image1, image2])

if __name__ == "__main__":
    demo.queue().launch()
```

### Screenshot

![](https://github.com/gradio-app/gradio/assets/25161192/a4b22691-50f0-40d5-8d1f-9909191cfe1e)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 3.44.4
gradio_client version: 0.5.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.1
fastapi: 0.103.1
ffmpy: 0.3.1
gradio-client==0.5.1 is not installed.
httpx: 0.25.0
huggingface-hub: 0.16.4
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.25.2
orjson: 3.9.7
packaging: 23.1
pandas: 2.0.3
pillow: 10.0.1
pydantic: 1.10.12
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.7.1
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.25.0
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by adityush007** [comment]
Please assign me this issue. I would like to work on it.

**Comment by abidlabs** [comment]
Hi @adityush007 I don't recommend working on this issue as we are currently redesigning the Image component from scratch. Please instead take a look at an issue we've designated as good for contributors: https://github.com/gradio-app/gradio/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
