### ISSUE TITLE
Chatbot Component chat_history bug

### ISSUE THREAD

**Issue by shpower** [gradio-app/gradio#5656]
### Describe the bug

Hi,

When I type two paragraph, or just letters, such as an input like:
"ppppppp
p
p

ppppppppppppp"

in the chatbot component message box I got only "pppppppppp pppppppp"  and not the otiginal message. 

How can I fix that? It mainly bothers me when I must send two seperate paragraphs in the same message.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

the example in the description.

### System Info

```shell
>>> gr.__version__
'3.44.3'
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @shpower can you provide a code example we can use to reproduce?

**Comment by shpower** [comment]
![WhatsApp Image 2023-09-22 at 19 33 32](https://github.com/gradio-app/gradio/assets/6441745/ab702de0-676a-4ae4-8fc5-aabeb1c8e733)
![WhatsApp Image 2023-09-22 at 19 32 26](https://github.com/gradio-app/gradio/assets/6441745/3b5c80ea-5414-4cf4-8e37-471d7f1adc6a)
![WhatsApp Image 2023-09-22 at 19 34 50](https://github.com/gradio-app/gradio/assets/6441745/58a140a0-a09a-4f80-9820-b04d2cf2d0db)

here are the files with the input at first image you can see that several p\n are not translated to writing in next line.

**Comment by abidlabs** [comment]
Hi @shpower its hard to tell what's happening from the screenshots. Could you please put together a minimal working example and provide us the code so that we can use to test?

**Comment by shpower** [comment]
this is the code from your site: https://www.gradio.app/docs/chatbot

import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.ClearButton([msg, chatbot])

    def respond(message, chat_history):
        bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
        chat_history.append((message, bot_message))
        time.sleep(2)
        return "", chat_history

    msg.submit(respond, [msg, chatbot], [msg, chatbot])

if __name__ == "__main__":
    demo.launch()


run it. input: like described in the photos above. 
you will see the bug

**Comment by abidlabs** [comment]
Hi @shpower thanks for the question. This is actually because by default, `gr.Chatbot` renders Markdown, and in the standard Markdown spec, single new lines are ignored, but double new lines are not. 

If you'd like to not render Markdown, and just use regular strings, you can set `enable_markdown=False` in `gr.Chatbot`.

**Comment by shpower** [comment]
I don't see any parameter such as enable_markdown. Could you please provide a code example?

**Comment by abidlabs** [comment]
Hi @shpower you'll need to install from `main` as we haven't released on pypi just yet. You can install gradio from main by following the instructions here: https://gradio.app/docs/main

**Comment by shpower** [comment]
Why should I install from main? Is it a new feature?

**Comment by abidlabs** [comment]
Yes, its a new feature. Sorry the correct link is: https://www.gradio.app/main/docs/interface

**Comment by abidlabs** [comment]
Ok we'll probably do a release to pypi in the next couple of days!

**Comment by shpower** [comment]
Could you please inform me about the release? This is very urgent for me.

**Comment by abidlabs** [comment]
Please follow this PR: https://github.com/gradio-app/gradio/pull/5596. When it is merged in, the release process will be triggered. Thanks
