### ISSUE TITLE
I want Exmaples to work on chatbot, but this doesn't work

### ISSUE THREAD

**Issue by xxWeiDG** [gradio-app/gradio#5657]
### Describe the bug

I want Exmaples to work on chatbot, but it cannot be used and an error is generated.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

For example, this code cannot use Examples normally.
`examples = gr.Examples(examples=["I went to the supermarket yesterday.", "Helen is a good swimmer."],
                           inputs=[chatbot])`

### Screenshot

![微信图片_20230922113042](https://github.com/gradio-app/gradio/assets/140797957/c926b2df-7897-4f76-9180-371f5d0809e3)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 3.44.3
gradio_client version: 0.5.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 4.2.2
fastapi: 0.94.0
ffmpy: 0.3.0
gradio-client==0.5.0 is not installed.
httpx: 0.24.1
huggingface-hub: 0.16.2
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.2
matplotlib: 3.7.1
numpy: 1.23.3
orjson: 3.8.7
packaging: 23.0
pandas: 1.5.3
pillow: 9.4.0
pydantic: 1.10.6
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.28.2
semantic-version: 2.10.0
typing-extensions: 4.4.0
uvicorn: 0.21.1
websockets: 10.4
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.3.0
httpx: 0.24.1
huggingface-hub: 0.16.2
packaging: 23.0
requests: 2.28.2
typing-extensions: 4.4.0
websockets: 10.4
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @xxWeiDG can you try:

```py
examples = gr.Examples(examples=[("I went to the supermarket yesterday.", None), ("Helen is a good swimmer.", None)], inputs=[chatbot])
```

**Comment by xxWeiDG** [comment]
> Hi @xxWeiDG can you try:
> 
> ```python
> examples = gr.Examples(examples=[("I went to the supermarket yesterday.", None), ("Helen is a good swimmer.", None)], inputs=[chatbot])
> ```
> 
> By the way, for general questions like this (that are not feature requests or bug reports), it's preferred that you ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB).

thank you ,I used the wrong code
