### ISSUE TITLE
Can we get request Headers or request username when initialize `gr.Chatbot()` with `value`?

### ISSUE THREAD

**Issue by coyh01** [gradio-app/gradio#5658]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

I want to display users' chat history after they log in, but it seems that I can't get `request.username` when initializing `gr.Chatbot`

```py
import gradio as gr

def init_value():
    # I want to get username from gr.Request, and return the chat history of this user
    return [
        ["First question", "First reply"],
        ["Second question", "Second reply"],
    ]

with gr.Blocks() as demo:
    chatbot = gr.Chatbot(value=init_value)

demo.launch(auth=("user1", "passwd01"))

```

**Describe the solution you'd like**  

Can we achieve this feature like the [issue](https://github.com/gradio-app/gradio/issues/2379#issuecomment-1270842002)?

    Some ideas on the user-facing API:
    
    We add a pass_request parameter to all event triggers and the Interface constructor that, if set to True, passes the FastAPI Request as the final argument to the function.
    So something like:
    
    def generate(prompt, request):
       return im
    
    btn.click(generate, text, image, pass_request=True)

**Additional context**

**Comment by freddyaboulton** [comment]
HI @coyh01 - you can add a load event to have the request passed in

```python
import gradio as gr

def init_value(req: gr.Request):
    # I want to get username from gr.Request, and return the chat history of this user
    return [
        ["First question", "First reply"],
        ["Second question", "Second reply"],
    ]

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    demo.load(init_value, None, chatbot)

demo.launch(auth=("user1", "passwd01"))
```

**Comment by abidlabs** [comment]
Thanks @freddyaboulton and @coyh01 -- I'll close this issue. Let us know if this doesn't work for you @coyh01.

**Comment by coyh01** [comment]
Thanks! That's what I am seeking.
