### ISSUE TITLE
How to use gradio_client with gr.Blocks (Chatbot component)

### ISSUE THREAD

**Issue by derek5965** [gradio-app/gradio#5659]
### Describe the bug

Traceback (most recent call last):
  File "D:\Program Files\Python311\Lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\gradio\blocks.py", line 1390, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\gradio\blocks.py", line 1216, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "D:\Program Files\Python311\Lib\site-packages\gradio\blocks.py", line 1203, in validate_inputs
    raise ValueError(
ValueError: An event handler (bot) didn't receive enough input values (needed: 2, got: 1).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [state, chatbot]
Received inputs:
    ["Hello"]

#5108

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://github.com/MrGreyfun/Local-Code-Interpreter/blob/main/src/web_ui.py

When I want to connect to this gradio application using the client, I cannot pass parameters

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/145663982/7087dba1-a32f-4fa2-82d4-d4dec210e1a5)
![image](https://github.com/gradio-app/gradio/assets/145663982/8a5c7084-5229-464c-8665-eaf7ce65b052)
![image](https://github.com/gradio-app/gradio/assets/145663982/b2ff5e70-948a-41a5-8f8f-1a0da1d20d2c)

### System Info

```shell
None
```

### Severity

I can work around it

**Comment by derek5965** [comment]
![image](https://github.com/gradio-app/gradio/assets/145663982/cbad2202-b2dc-4cec-9ea9-e32107f03898)

**Comment by abidlabs** [comment]
Hi @derek5965 its hard to tell what's happening from the screenshots. Could you please put together a minimal working example and provide us the code so that we can use to test?

Also, please make sure you are using the latest versions of `gradio` and `gradio_client`

**Comment by derek5965** [comment]
I am using an open source project (Gradio application) using Python client according to the usage of the page, but I have been reporting errors and accessing from the page is always normal

![image](https://github.com/gradio-app/gradio/assets/145663982/c25fe5fe-e950-4405-9f20-4b9e42f67422)
The key is how to pass this parameter?

**Comment by zhengxiang5965** [comment]
![image](https://github.com/gradio-app/gradio/assets/31379313/f1afc814-4a83-411c-9f28-5688dd081249)
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.Button("Clear")

    def user(user_message, history):
        return "", history + [[user_message, None]]

    def bot(history):
        bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
        history[-1][1] = ""
        for character in bot_message:
            history[-1][1] += character
            time.sleep(0.05)
            yield history

    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        bot, chatbot, chatbot
    )
    clear.click(lambda: None, None, chatbot, queue=False)
    
demo.queue()
demo.launch(server_name="0.0.0.0")

![image](https://github.com/gradio-app/gradio/assets/31379313/6a238725-10f8-4f24-8d72-57973974b18b)
@abidlabs 
For example, for a simple demo on the official website, calling the "Use via API" method will result in an error

**Comment by abidlabs** [comment]
Hi @derek5965 currently, in order to the Chatbot via API, you have to pass in the history as a json file. 

Here's an example:

* First write the history as a json file:

```py
import json

with open('file.json', 'w') as f:
    json.dump([("Hi, how are you?", "I'm good thanks")], f, indent=4)
```

* Then pass it into the Chatbot via API:

```py
from gradio_client import Client

client = Client("http://127.0.0.1:7864/")
result = client.predict(
    "Howdy!",
    "file.json",
    fn_index=0
)
print(result)
```

But a much easier solution would be to use Gradio's high-level ChatInterface abstraction. You can read about that here: https://www.gradio.app/guides/creating-a-chatbot-fast

**Comment by zhengxiang5965** [comment]
> Hi @derek5965 currently, in order to the Chatbot via API, you have to pass in the history as a json file.
> 
> Here's an example:
> 
> * First write the history as a json file:
> 
> ```python
> import json
> 
> with open('file.json', 'w') as f:
>     json.dump([("Hi, how are you?", "I'm good thanks")], f, indent=4)
> ```
> 
> * Then pass it into the Chatbot via API:
> 
> ```python
> from gradio_client import Client
> 
> client = Client("http://127.0.0.1:7864/")
> result = client.predict(
>     "Howdy!",
>     "file.json",
>     fn_index=0
> )
> print(result)
> ```
> 
> But a much easier solution would be to use Gradio's high-level ChatInterface abstraction. You can read about that here: https://www.gradio.app/guides/creating-a-chatbot-fast

Can "ChatInterface" support uploading files?
