### ISSUE TITLE
Add changing location of additional inputs for ChatInterface

### ISSUE THREAD

**Issue by OleksandrKorovii** [gradio-app/gradio#5661]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I faced the problem when I needed additional input before the ChatBot block, because when additional inputs are located at the bottom it is not user-friendly,  and sometimes the user couldn't add additional variables because couldn't find them.

**Describe the solution you'd like**  
Can you add functionality for example how to locate the additional inputs? Or share the example if it could be done already. 

**Additional context**

**Comment by abidlabs** [comment]
Hi @OleksandrKorovii this is already possible! You can see this in the 2nd example in https://www.gradio.app/guides/creating-a-chatbot-fast#additional-inputs

I'm reproducing the relevant code below:

```py
import gradio as gr
import time

def echo(message, history, system_prompt, tokens):
    response = f"System prompt: {system_prompt}\n Message: {message}."
    for i in range(min(len(response), int(tokens))):
        time.sleep(0.05)
        yield response[: i+1]

with gr.Blocks() as demo:
    system_prompt = gr.Textbox("You are helpful AI.", label="System Prompt")
    slider = gr.Slider(10, 100, render=False)

    gr.ChatInterface(
        echo, additional_inputs=[system_prompt, slider]
    )

demo.queue().launch()

```
