### ISSUE TITLE
apps with `gr.Examples`  unexpected behaviour with `gr.load` 

### ISSUE THREAD

**Issue by utatane-kio** [gradio-app/gradio#5666]
### Describe the bug

When loading apps with `gr.load` that has `gr.Examples` component, the loaded app has unexpected components (same as the examples). 
Also, examples which are tied to a radio button is shown as null in the table of Examples. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

original app
```
import gradio as gr

with gr.Blocks() as demo:
    txt1 = gr.Textbox(label="input1")
    txt2 = gr.Textbox(label="input2")
    radio1 = gr.Radio(choices=["1", "2"], label="radio1")
    example = gr.Examples([["a", "b", "1"]], [txt1, txt2, radio1])

demo.launch(debug=True)
```

### Screenshot

![スクリーンショット 2023-09-23 17 37 51](https://github.com/gradio-app/gradio/assets/115803278/0001fb26-8acf-4997-a515-a0a0b2591e6c)

### System Info

```shell
gradio==3.44.4
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Can reproduce! Thanks @utatane-kio we'll take a look at this
