### ISSUE TITLE
Using your chatbot via an API，Can you provide a Python client example?

### ISSUE THREAD

**Issue by derek5965** [gradio-app/gradio#5676]
### Describe the bug

![image](https://github.com/gradio-app/gradio/assets/145663982/cc3be07d-e9bb-45c8-882c-fd6730b74fbb)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

None

### System Info

```shell
None
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @derek5965 I answered your question here: https://github.com/gradio-app/gradio/issues/5659#issuecomment-1734186921

For future reference, we appreciate if you don't create multiple issues for the same question, thanks.
