### ISSUE TITLE
Video does not have browser-compatible container or codec. Converting to mp4

### ISSUE THREAD

**Issue by AK51** [gradio-app/gradio#5689]
### Describe the bug

I have install ffmpeg and sudo apt install ubuntu-restricted-extras

May I know how to solve this problem? Thx
```
anaconda3/lib/python3.9/site-packages/gradio/components/video.py:334: UserWarning: Video does not have browser-compatible container or codec. Converting to mp4
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://github.com/hkchengrex/Tracking-Anything-with-DEVA/issues/25

### System Info

```shell
Ubuntu 22.04
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @AK51 this isn't exactly a Gradio issue. Some [video formats / codecs are not playable in the browser](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs). In some cases, Gradio is able to convert the video in the backend to a format that can be played in the browser, in which case you'll see the warning displayed. 

By the way, for general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
