### ISSUE TITLE
.success() method

### ISSUE THREAD

**Issue by shpower** [gradio-app/gradio#5691]
- [ ] I have searched to see if a similar issue already exists. yes

**Is your feature request related to a problem? Please describe.**  
A clear and concise description of what the problem is. I understand the .then() method described in here: https://www.gradio.app/guides/blocks-and-event-listeners. However, I don't understand what I need to do in order to fail the event from activating another event. In the source above you mention the .success() method. However there is no documentation for .then() and .success() methods and I would like to know whether I can actively fail the next event by using .success() method.

**Describe the solution you'd like**  
A code that demonstrates how to use the .success() method so the following events won't be executed.

**Comment by freddyaboulton** [comment]
Hi @shpower ! Please take a look at this demo to see how `success` is used. It's the same syntax as then.

We will add this method to the documentation soon.

https://huggingface.co/spaces/gradio/blocks_chained_events

**Comment by shpower** [comment]
Hi, thanks.
However, in the examples you provided there is only one way to stop the .success() by raising an error. I don't want to raise an error and stop the whole program, I just want to stop the next execution in the .success() method. I tried return False, but that doesn't work.
