### ISSUE TITLE
Dataframe: Extra Scroll Bars in latest version

### ISSUE THREAD

**Issue by Bengt** [gradio-app/gradio#5694]
### Describe the bug

Previously, Dataframes would not have scroll bars when embedded in a colum:

![Screenshot from 2023-09-26 16-38-40](https://github.com/gradio-app/gradio/assets/11575/6130b2ee-0394-4e9c-bd73-c852eba63f71)

Recently, scroll bars appeared in the same circumstances:

![Screenshot from 2023-09-26 16-38-49](https://github.com/gradio-app/gradio/assets/11575/8af8673e-54de-4001-a47e-c4031aacb51e)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Here is a version of my application using an older gradio library, which does not produce scroll bars:

https://huggingface.co/spaces/Bengt0/BirdNET-Annotator

Here is version of my application using the current gradio library, which produces extra scroll bars:

https://huggingface.co/spaces/XPRIZE-Brazilian-Team/Bengt-BirdNET-Annotator

### System Info

```shell
Both applications are running in Docker on Hugging Face.
```

### Severity

I can work around it by just ignoring the scrollbars. Still, they might be distracting to my users.

**Comment by pngwn** [comment]
This was fixed in #5616 and should be released soon.

**Comment by Bengt** [comment]
Thanks for the information. Looking forward to rolling out this fix!
