### ISSUE TITLE
Tabs.update(selected=x) returns constructor error

### ISSUE THREAD

**Issue by ghotinggoad** [gradio-app/gradio#5707]
### Describe the bug

This is my code
def change_tab():
    return gr.Tabs.update(selected=4)

 with gr.Tabs(selected=settings["default_tab_on_launch"]) as tabs:
            with gr.Tab(label="settings", id=3) as settings_tab:
                    settings_tab_save_button = gr.Button(value="save settings")
                    settings_tab_save_button.click(fn=change_tab, inputs=None, outputs=tabs)

This is the error I get when I try to update the tabs

Traceback (most recent call last):
  File "C:\Users\home\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\routes.py", line 517, in predict
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\home\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\route_utils.py", line 216, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\home\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1564, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\home\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1434, in postprocess_data
    args = self.blocks[output_id].constructor_args.copy()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Tabs' object has no attribute 'constructor_args'

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

def change_tab():
    return gr.Tabs.update(selected=4)

 with gr.Tabs(selected=settings["default_tab_on_launch"]) as tabs:
            with gr.Tab(label="settings", id=3) as settings_tab:
                    settings_tab_save_button = gr.Button(value="save settings")
                    settings_tab_save_button.click(fn=change_tab, inputs=None, outputs=tabs)

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\home\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\routes.py", line 517, in predict
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\home\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\route_utils.py", line 216, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\home\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1564, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\home\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1434, in postprocess_data
    args = self.blocks[output_id].constructor_args.copy()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Tabs' object has no attribute 'constructor_args'
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 3.45.1
gradio_client version: 0.5.2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.1.0
altair: 5.0.1
fastapi: 0.88.0
ffmpy: 0.3.1
gradio-client==0.5.2 is not installed.
httpx: 0.24.1
huggingface-hub: 0.16.4
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.2
numpy: 1.25.2
orjson: 3.9.4
packaging: 23.1
pandas: 2.0.3
pillow: 10.0.0
pydantic: 1.10.12
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.7.1
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.24.1
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Can reproduce with this:

```py
import gradio as gr

with gr.Blocks() as demo:
    button = gr.Button()
    
    def change_tab():
        return gr.Tabs.update(selected=1)

    with gr.Tabs() as tabs:
        with gr.Tab("a"):
            pass
        with gr.Tab("b"):
            pass
        
    button.click(change_tab, None, tabs)
    
    
demo.launch()
```

Taking a look
