### ISSUE TITLE
Redesign the Queue

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#572]
There were some errors related to the queueing when tests were divided into subfolders, #551 .

get_status function for the queue had some bugs which can be seen [here](https://app.circleci.com/pipelines/github/gradio-app/gradio/1444/workflows/c0992a04-a11f-48a1-a211-593202beb8ea/jobs/1445).

Furthermore @aliabd's local machine were giving errors because queue was starting from the index -1.

After the order of the test subfolders were changed another error has appeared like [this](https://app.circleci.com/pipelines/github/gradio-app/gradio/1471/workflows/75a8420e-9e7a-4674-a1db-be61bffc192c/jobs/1472).

Building on top of these I would suggest we move queueing from the database to a list variable, which would accelerate things as database accesses slow us down.

**Comment by abidlabs** [comment]
Makes sense, if we can avoid file-based databases, it would probably simplify things. @aliabid94 can you add your thoughts here? Why did we use a file database for something as simple as just keeping a queue?

**Comment by FarukOzderim** [comment]
Comment about queueing from @cbensimon, we shall take this into account while refactoring queueing.

```
I agree (even if the experience is slightly degraded when the processing is really fast (<< 1s) because the queue only refreshes every second)

In future Gradio versions, I think that we should make the queue totally transparent to the developer / user (by improving the internals of the backend in a way or another, whether using WebSockets, or Server Side Events, or any other technique)
To me the queue is an implementation detail and we shouldn't make the developer responsible for making this decision.
```

**Comment by cbensimon** [comment]
> Makes sense, if we can avoid file-based databases, it would probably simplify things. @aliabid94 can you add your thoughts here? Why did we use a file database for something as simple as just keeping a queue?

Totally agree, I don't think that a DB was needed for the queue

**Comment by FarukOzderim** [comment]
We should also think of communication of queuing with autoscaling. We will probably collaborate with @cbensimon 🤗

**Comment by FarukOzderim** [comment]
I feel like this could stay in low priority as it could need some effort, dropping the milestone.

**Comment by pngwn** [comment]
I do think websockets would be the way to go in the future for the queue. I think this was discussed briefly somewhere (may have been on slack).

**Comment by FarukOzderim** [comment]
There was a nice feature suggestion from @ronvoluted.

Let's have a endpoint to get queue information from the Gradio server in the new design.

**Comment by aliabid94** [comment]
I think an in-memory queue makes sense, and with that we need to make it so the backend does not receive the data for actual function until it is the client's turn in line. What I mean is, client gets their ticket for position in queue, then they poll status until it is their turn, then when it's their turn they submit the data for the actual function. That way we don't have to store, for example, 1000 images in memory if it's an Image input function with 1000 users in queue. We only keep the data in memory for the single client's data being processed at that time.

**Comment by FarukOzderim** [comment]
This is the final design I came up with after several discussions and feedbacks from the team. Will create a template in Backend according to this, thx a lot to @cbensimon for his contributions.

![image](https://user-images.githubusercontent.com/44067394/172466063-57708995-44a2-4ad5-8024-e08afa239936.png)

**Comment by apolinario** [comment]
this is looking really good - can't comment much on the backend logic but a bit on the 'user' side: 

![image](https://user-images.githubusercontent.com/788417/172489838-ddf8cc0d-c97e-44e3-ac04-31ed23281b4d.png)
Does this make sense for blocks? On Blocks different buttons/actions could take a very different time - could it be the case it makes more sense that for Blocks each 'action' has it's own queue timing?

Also, would how would this process deal with blocks that load other blocks? My intuition is that it should inherit the queue of the loaded block instead of starting a new one of itself (as I describe here: https://github.com/gradio-app/gradio/issues/1316

**Comment by FarukOzderim** [comment]
Thx for the contribution @apolinario!

> 1. On Blocks different buttons/actions could take a very different time - could it be the case it makes more sense that for Blocks each 'action' has it's own queue timing?
Well the triggers that go into queue use the same queue, so ETA generation needs to look at the average of all jobs.
> 2. Also, would how would this process deal with blocks that load other blocks? My intuition is that it should inherit the queue of the loaded block instead of starting a new one of itself (as I describe here: https://github.com/gradio-app/gradio/issues/1316
Since load uses another space under the hood, this design is not relevant to `load` at all. This design will only work when there is a server with queue enabled.

**Comment by FarukOzderim** [comment]
After a day I realized that I did not think much about the `load` for a demo.

With websocket commed queueing there are 2 problems.
1. Will we enable `/api/predict` endpoint? If so it will bypass the queue?
2. How will `load` send requests to another demo?

Their proposed solutions are the same.
Solution a:
  Bypass the queue
Solution b:
  Add the request to the queue without a websocket communication
Solution c:
  Disable HTTP requests for queued demos

**Comment by apolinario** [comment]
> Well the triggers that go into queue use the same queue, so ETA generation needs to look at the average of all jobs.
Got it. I was just thinking of the scenario where  there are two very different tasks on the same Blocks environment

Let's say a Blocks interface has a language model and a text-to-image model. The language model takes 0.3s to generate a prompt for you, and the text-to-image model 50s to generate the image. 

Now the average is a 25.15s queue. So, when generating your prompt you'd see an ETA of 25.15 to generate the prompt (which you almost dont see because it will get completed instantly) and a 25.15 ETA to generate the image which will definetly be off because it takes longer. That's why I was thinking of potentially each 'action' or 'trigger' on a blocks interface to have it's own context-based ETA

**Comment by FarukOzderim** [comment]
> > Well the triggers that go into queue use the same queue, so ETA generation needs to look at the average of all jobs.
> 
> Got it. I was just thinking of the scenario where there are two very different tasks on the same Blocks environment
> 
> Let's say a Blocks interface has a language model and a text-to-image model. The language model takes 0.3s to generate a prompt for you, and the text-to-image model 50s to generate the image.
> 
> Now the average is a 25.15s queue. So, when generating your prompt you'd see an ETA of 25.15 to generate the prompt (which you almost dont see because it will get completed instantly) and a 25.15 ETA to generate the image which will definetly be off because it takes longer. That's why I was thinking of potentially each 'action' or 'trigger' on a blocks interface to have it's own context-based ETA

We actually have a parameter for events to bypass the queue, so rather than creating several queues and making the design too complex, it is much more easier to bypass the queue, [see](https://github.com/gradio-app/gradio/blob/b2cd4c12070a49dfe341bac90b8da7f372868c9f/gradio/events.py#L19). Events are not properly documented yet so it will be in the docs later.

**Comment by apolinario** [comment]
Got it! For the example I gave it makes sense. Now, I still can see a use-case where one action takes 30 seconds and the other takes 1 minute for a Block where one would still want a queue for both but each one would have very different ETAs

My Spaces, MindsEye Lite is an example: https://huggingface.co/spaces/multimodalart/mindseye-lite
There you can run Latent Diffusion (takes about 30s to generate an image) and Guided Diffusion can take 60-90s; I would like a queue in both but sharing the queue timing doesn't make as much sense to me (ignoring for a second the other issue which is this one https://github.com/gradio-app/gradio/issues/1316)

**Comment by abidlabs** [comment]
Moving to the 3.x milestone since we are aiming to release 3.1 soon @FarukOzderim

**Comment by FarukOzderim** [comment]
This was completed with several PRs, it is currently in beta release, will close the issue. We can file new issues related to specific features.
