### ISSUE TITLE
ChatInterface chatbot value clears

### ISSUE THREAD

**Issue by austinmw** [gradio-app/gradio#5723]
### Describe the bug

Hi, I've defined a chatbot like this:

```python
 chatbot = Chatbot(label="Chatbot", value=initial_message)
demo = gr.ChatInterface(chat_handler.echo, chatbot=chatbot)
```

My expectation was that when I hit the 'clear' button, the initial_message should get repopulated, however it actually gets cleared. Would it make more sense to maintain the initial message value upon clearing?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
 chatbot = Chatbot(label="Chatbot", value=initial_message)
demo = gr.ChatInterface(chat_handler.echo, chatbot=chatbot)
```

### System Info

```shell
Latest version
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @austinmw the "Clear" button in Gradio consistently clears the output -- its not a reset button. The same behavior is in `gr.Interface` for example:

```py
import gradio as gr

gr.Interface(lambda x:x, gr.Textbox("hello"), "textbox").launch()
```

If you'd like to override this behavior, though, you could actually pass in your own `clear_btn` and attach any desired events to it. Here's an example:

```py
import gradio as gr

with gr.Blocks() as demo:
    textbox = gr.Textbox("Default value", render=False, scale=7)
    chatbot = gr.Chatbot(render=False)
    clear_btn = gr.Button("Clear", render=False)
    clear_btn.click(lambda :"Default value", None, textbox)
    gr.ChatInterface(lambda x,y:x, textbox=textbox, clear_btn=clear_btn, chatbot=chatbot)
    
demo.launch()
```
