### ISSUE TITLE
gr.Row() don't work when i use `test = gr.Tab()  ;   with test : `

### ISSUE THREAD

**Issue by sanbuphy** [gradio-app/gradio#5728]
### Describe the bug

Hello, I found something interesting while adjusting the layout. When I put the 'tab' variable outside and use it to render, I couldn't successfully change the layout. However, when I directly put the 'tab' variable inside, I can successfully change the layout. I would like to ask if this should be considered a bug. Thank you.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

can't work: (The reason why I need to do this is because I want to use the callback function of 'select' on 'tab')
```python
  tab_1 = gr.Tab('test1')
  tab_2 = gr.Tab('test2')
  with gr.Row():
      with tab_1 :
          button1 = gr.Button()
      with tab_2 :
         button2 = gr.Button()
      button3 = gr.Button()
```

it work:
```python
  with gr.Row():
      with gr.Tab('test1'):
          button1 = gr.Button()
      with gr.Tab('test2'):
         button2 = gr.Button()
      button3 = gr.Button()
```

### System Info

```shell
lastest version 
ubuntu 20.04
python3.10
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @sanbuphy you can use `as`, like this:

```py
  with gr.Row():
      with gr.Tab('test1') as tab1:
          button1 = gr.Button()
      with gr.Tab('test2') as tab2:
         button2 = gr.Button()
      button3 = gr.Button()
```

**Comment by sanbuphy** [comment]
> Hi @sanbuphy you can use `as`, like this:
> 
> ```python
>   with gr.Row():
>       with gr.Tab('test1') as tab1:
>           button1 = gr.Button()
>       with gr.Tab('test2') as tab2:
>          button2 = gr.Button()
>       button3 = gr.Button()
> ```

Thanks , get it
