### ISSUE TITLE
Using webbrowser in gradio

### ISSUE THREAD

**Issue by almightyGOSU** [gradio-app/gradio#5730]
### Describe the bug

Unable to use [webbrowser](https://docs.python.org/3/library/webbrowser.html) inside gradio

I am trying to open a new tab to display a file, but the webbrowser's open function does not work inside gradio?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
webbrowser.open(local_file_path
```

### System Info

```shell
Gradio 3.40.1
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @almightyGOSU! Can you please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by henryruhs** [comment]
I would consider this a non issue.

**Comment by abidlabs** [comment]
Closing for lack of repro

**Comment by almightyGOSU** [comment]
> Calling this in python will attempt to open a new browser on the server. Whether this works or not is moot because that browser would not be accessible by the user.
> 
> It might worker locally under certain circumstances but that is all.

You are right!
