### ISSUE TITLE
Deprecated Warning for gr.update() Despite Using New Update Format

### ISSUE THREAD

**Issue by chaofanqw** [gradio-app/gradio#5746]
### Describe the bug

When using the recommended update format for Gradio, such as gr.Markdown() or gr.Dataframe(), from a callback function, a warning message is mistakenly displayed. The warning indicates that the usage of gr.update() is deprecated, even though the deprecated method was not used.

**Steps to Reproduce:**
Create a callback function that returns using the new format, for instance, return gr.Markdown("Updated Content").
Observe the warning message in the console or terminal indicating the use of the deprecated gr.update() method.

**Expected Behavior:**
No warning should be displayed when using the new update format as recommended.

**Actual Behavior:**
A warning message regarding the deprecated gr.update() method is displayed, even though the new format was used.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr
import logging


def update():
    return {dataframe: gr.Dataframe([[4, 5, 6]], headers=["a", "b", "c"])}


logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

with gr.Blocks() as demo:
    markdown = gr.Markdown("## Hello world!")
    dataframe = gr.Dataframe([[1, 2, 3], [4, 5, 6]], headers=["a", "b", "c"])

    button = gr.Button(value="Click me!")
    button.click(update, outputs=[dataframe])

demo.launch()
```

### Logs

```shell
lib/python3.10/site-packages/gradio/helpers.py:818: UserWarning: Using the update method is deprecated. Simply return a new object instead, e.g. `return gr.Textbox(...)` instead of `return gr.update(...)
  warnings.warn(
```

### System Info

```shell
gradio==3.45.2
python=3.10
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Can reproduce! We'll take a look.

cc @aliabid94

**Comment by dalalvarun** [comment]
Warning is not shown when you return gr.Dataframe as follows:

`import gradio as gr
import logging


def update():
    return gr.Dataframe([[4, 5, 6]], headers=["a", "b", "c"])


logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

with gr.Blocks() as demo:
    markdown = gr.Markdown("## Hello world!")
    dataframe = gr.Dataframe([[1, 2, 3], [4, 5, 6]], headers=["a", "b", "c"])

    button = gr.Button(value="Click me!")
    button.click(update, outputs=[dataframe])

demo.launch()`

Probably happens because you are returing a dict.
Is this expected? Or should I dig further?

**Comment by chaofanqw** [comment]
It will be good to fix, in case the way to process a returned dictionary differs from returning an obj resulting in inconsistent source code. Also, it can be annoying when we need to debug the code with different logging levels, e.g., llama-index, when we set the logging level to DEBUG or INFO. Thanks.

**Comment by henryruhs** [comment]
@abidlabs Sorry, I have still warnings with Gradio 3.46.1

```
/home/henry/PycharmProjects/facefusion/venv/lib/python3.10/site-packages/gradio/helpers.py:818: UserWarning: Using the update method is deprecated. Simply return a new object instead, e.g. `return gr.Textbox(...)` instead of `return gr.update(...)
  warnings.warn(
/home/henry/PycharmProjects/facefusion/venv/lib/python3.10/site-packages/gradio/components/gallery.py:139: UserWarning: Using the update method is deprecated. Simply return a new object instead, e.g. `return gr.Gallery(...)` instead of `return gr.Gallery.update(...)`.
  warnings.warn(
/home/henry/PycharmProjects/facefusion/venv/lib/python3.10/site-packages/gradio/components/image.py:193: UserWarning: Using the update method is deprecated. Simply return a new object instead, e.g. `return gr.Image(...)` instead of `return gr.Image.update(...)`.
  warnings.warn(
```

**Comment by abidlabs** [comment]
@henryruhs are you returning `return gr.Textbox` or `return gr.Textbox.update()`.

If you are doing the latter, then yes warnings will be emitted as that approach is deprecated (although we support it for backwards-compatibility). I'd recommend switching to the latter. 

If you are doing the former, and still getting warnings, please provide a self-contained snippet of code that we can use to reproduce. Thanks!

**Comment by henryruhs** [comment]
Nope, I use `gradio.update()` everywhere in my code.

**Comment by abidlabs** [comment]
So that's what it is then -- `gradio.update()` needs to be converted to returning a component instead.

**Comment by henryruhs** [comment]
Okay, sorry that I did not get this. Hehe...

**Comment by chaofanqw** [comment]
The error appears again when only returning parts of the components

```python
import gradio


def change_language():
    return {markdown: gradio.Markdown("Hello **World 2!**")}


with gradio.Blocks() as demo:
    markdown = gradio.Markdown("Hello **World!**")
    btn = gradio.Button("Click me!")

    btn.click(change_language, outputs=[markdown, btn])

demo.queue().launch()
```

Warning
```
gradio/components/button.py:89: UserWarning: Using the update method is deprecated. Simply return a new object instead, e.g. `return gr.Button(...)` instead of `return gr.Button.update(...)`.
  warnings.warn(
```

**Comment by henryruhs** [comment]
@abidlabs Sorry for the offtopic, is there a way for proper typing? I guess there is nothing exposes like a ImageUpdate?

```
def update(file: IO[Any]) -> ImageUpdate:
	if file and is_image(file.name):
		return gradio.Image.update(value = file.name)
	return gradio.Image.update(value = None)
```

**Comment by abidlabs** [comment]
Interesting, I thought I handled that case. Reopening
