### ISSUE TITLE
gradio/client in next js application 

### ISSUE THREAD

**Issue by rojitdhakal** [gradio-app/gradio#5747]
### Describe the bug

I am using gradio/client in next application  for  hosted Gradio space but it shows error 
Module not found: Can't resolve 'net'

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

 
import { client } from "@gradio/client";
const app = await  client("https://sanchit-gandhi-whisper-large-v2.hf.space/",{});
		
    try {
      const result = await app.predict("/predict", [
        audioFile,    // blob in 'inputs' Audio component
        "translate",  // string in 'Task' Radio component
      ]);
      console.log(result);
    } catch (error) {
      console.error("An error occurred:", error);
    }

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/114090313/c2bc3c51-e36d-45ae-95dd-683c88acfe5c)

### System Info

```shell
yes
```

### Severity

I can work around it

**Comment by pngwn** [comment]
Please provide some system information so we can debug this.

**Comment by rojitdhakal** [comment]
I am using Next  JS for frontend application and the api is hosted in gradio space , i want to access api of gradio space using  the gradio client  js , the above issue arises . i am using pnpm as package manager.

**Comment by rojitdhakal** [comment]
System Info:-
OS-window
pnpm version-7.23.0
gradio/client version-0.4.1
node version-v16.15.0

**Comment by pngwn** [comment]
The gradio JavaScript client requires node 18 or above. Could you upgrade your node version and see if the issue persists?

**Comment by cantonalex** [comment]
how did you solve it @rojitdhakal

**Comment by 404Nikhil** [comment]
facing this same error @rojitdhakal what's the solution
