### ISSUE TITLE
Gallery selection should clear if item has been updated

### ISSUE THREAD

**Issue by sunnyark** [gradio-app/gradio#5748]
- [ *] I have searched to see if a similar issue already exists.

Hello! 
I have a suggestion regarding the use of select event listeners in Gradio's gallery. When one item in the gallery is selected, and then the gallery's content is changed to something else, the previously selected item remains selected, and no select event is triggered for that item. I would appreciate it if the selected item is cleared when the gallery's content is updated.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by pngwn** [comment]
Would you expect the selected event to be fired again with an empty value?

**Comment by sunnyark** [comment]
@pngwn When a specific item within the gallery is selected, the 'selected' event is triggered. However, if you subsequently change an item within the gallery and then select the item that was previously chosen, the 'selected' event does not fire. In this case, I would like the 'selected' event to occur as expected even in this scenario.

**Comment by abidlabs** [comment]
Hi @sunnyark the `.select()` event should not be triggered when the value of the `Gallery` component is changed -- only when a user selects images. 

In your case, the proper workflow would be (1) to attach a `.change()` event to Gallery, and then (2) read the selected image of Gallery (if there is one) to trigger your event. Unfortunately, we still need to implement the functionality for both of these steps. Both are open issues that we'll address soon:

* https://github.com/gradio-app/gradio/issues/2123
* https://github.com/gradio-app/gradio/issues/5123

So we can go ahead and close this issue.

**Comment by sunnyark** [comment]
@abidlabs I don't want the select trigger to be activated when the component's value changes. The issue is that after the select trigger has been fired, it should not be triggered again from the previous location where it was triggered when the component's value is changed. This is because the component does not recognize that its value has been changed and still thinks the previous value is selected.

**Comment by abidlabs** [comment]
Oh sorry misunderstood the issue -- we'll look into it

**Comment by abidlabs** [comment]
Can you provide us some code we can use to reproduce this issue?

**Comment by sunnyark** [comment]
@abidlabs 
[https://github.com/sunnyark/civitai-shortcut/blob/main/scripts/civitai_manager_libs/sc_browser_page.py](url)

In the ongoing project, the gallery is being heavily utilized, and we are currently developing an extension for stable diffusion. It's difficult to send only a part of it, so I will provide a link to the key section. This section displays a list of models and is implemented using a gallery, located on the left side

Additionally, the following section is also available for reference.
[https://github.com/sunnyark/civitai-shortcut/issues/86](url)

**Comment by henryruhs** [comment]
I have this problem with FaceFusion as well.

Our gallery to select reference faces keeps the selection after rendering new Gallery content with new faces for the current frame. What is even worse, you cannot trigger the chance event on this already preselected item.

Therefore high priority from our side.

**Comment by abidlabs** [comment]
I'm having a hard time reproducing this. Here's my code:

```py
import gradio as gr

im1 = "cat.jpg"
im2 = "cheetah.jpg"

def select_fn(data: gr.SelectData):
    return data.index, data.value

with gr.Blocks() as demo:
    g = gr.Gallery([im1]*2)
    b = gr.Button()
    t = gr.Textbox()
    
    b.click(lambda : gr.Gallery([im2]*2), None, g)
    g.select(select_fn, None, t)
    
demo.launch()
```

![Recording 2023-10-07 at 00 35 08](https://github.com/gradio-app/gradio/assets/1778297/2192ae20-3ea1-4ea3-a4ae-d0a96c8949d0)


When I update the contents of the Gallery, there's no more selected image anymore and when I click on the image again, a new selection event is fired with the updated data (you'll notice that "cat.jpg" changes to "cheetah.jpg" in the textbox).

Am I missing something, or has this been fixed on `main`? @sunnyark or @henryruhs can you check on `main`? You can install gradio from main by following the instructions here: https://www.gradio.app/main/docs/interface

**Comment by sunnyark** [comment]
@abidlabs It seems that the code you provided works as expected when I tested it. Could it have been an issue with the version of Gradio I was using? The version provided by stable diffusion is 3.41.2.

**Comment by sunnyark** [comment]
@abidlabs After testing the code you provided in extension format, I found that in version 3.41, it goes beyond the index value, but the value itself appears as None. It doesn't seem different from my code, but the clearing process is still not working in my code. Here is what I made using the code you provided as an extension in the stable diffusion format.
```

import os
import gradio as gr

from modules import script_callbacks

im1 = "card-no-preview.png"
im2 = "nsfw-no-preview.png"

def select_fn(data: gr.SelectData):
    util.printD(data.index)
    util.printD(data.value)
    
    return data.index, data.value

def test_ui():
    with gr.Blocks() as demo:
        g = gr.Gallery(show_label=False, columns=2, height="auto", object_fit=setting.gallery_thumbnail_image_style, allow_preview=False, value=[im1]*2)
        b = gr.Button()
        t = gr.Textbox()
        
        b.click(lambda : gr.update(value=[im2]*2), None, g, show_progress=False)
        g.select(select_fn, None, t) 
        
def on_ui_tabs():
    # init
    init_civitai_shortcut()

    with gr.Blocks() as civitai_shortcut:
        test_ui()
        
    return (civitai_shortcut, "Civitai Shortcut", "civitai_shortcut"),


script_callbacks.on_ui_tabs(on_ui_tabs)
```

**Comment by abidlabs** [comment]
Hi @sunnyark that is definitely possible that this bug existed on an older version of `gradio` but has now been fixed. Unfortunately, there's no way to fix this bug retroactively in older versions of gradio, the only solution would be to upgrade the version of `gradio`.

**Comment by abidlabs** [comment]
I'll go ahead and close this issue unless y'all find the bug in the current version of gradio. If that's the case, please let me know
