### ISSUE TITLE
Don't scroll to top upon error

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#5749]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
If you get an `gr.Error` such as https://huggingface.co/spaces/AP123/IllusionDiffusion when the queue is full , you automatically get scrolled to the top and shown the error. For mobile, this means I need to scroll to the submit button again.

**Describe the solution you'd like**  
The error should be displayed where I am rather than change my position.

**Comment by pngwn** [comment]
We actually implemented this intentionally for spaces but I have another idea.

**Comment by pngwn** [comment]
I actually don't know if it will work in hindsight.

My idea was to use position absolute and update the `top` property based upon the scroll position of the page. But i think the scroll position actually lives on the iframe, not our page.

We may be able to access the scroll position of the iframe but I'm not sure.

**Comment by abidlabs** [comment]
We investigated this quite a bit in the 5.0 release and couldn't find a way to implement this that works on Spaces. I think we should go ahead and close this since its a pretty minor inconvenience that should rarely happen
