### ISSUE TITLE
A request for updating contribution documents

### ISSUE THREAD

**Issue by binary-husky** [gradio-app/gradio#5756]
I find that some dev documents such as `guides/08_other-tutorials/creating-a-new-component.md` are outdated, some files mentioned in this tutorial no longer exist (such as component.py).

Are there any alternative documents?

**Comment by abidlabs** [comment]
Thanks @binary-husky -- we'll definitely update the contributing docs soon. We have an open issue for that here: https://github.com/gradio-app/gradio/issues/3247 so let me close this one
