### ISSUE TITLE
Gradio links expire after just a couple of hours

### ISSUE THREAD

**Issue by MysticDaedra** [gradio-app/gradio#5757]
### Describe the bug

This has happened twice to me now today. The links say they are supposed to work for 72 hours, but instead they get reset or cancelled (not sure which and I'm at work, can't access the hosting device at the moment) after only a couple. 

I'm using ExpressVPN on the hosting device for additional security, it has crossed my mind that the VPN might be causing the issue somehow.

Console shows no errors at all, let alone errors related to Gradio.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Using SD.next (Stable Diffusion), the connection times out during normal use after about the 2 hour mark.

### System Info

```shell
Windows 10 Professional 64-bit, Ryzen 7 5700X, 32GB RAM, RTX 3070 8GB. Running SD.next.
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @MysticDaedra thanks for letting us know! Would you be able to use this issue to discuss? https://github.com/gradio-app/gradio/issues/3677 -- that way we can consolidate various issues and troubleshoot together
