### ISSUE TITLE
Lazy load gradio interfaces used in the guides.

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#576]
The guides and homepage being slowed due to the size of the gradio app bundle, this would partly be addressed by the planned performance improvements for gradio apps but there is no need for us to be prematurely loading in large chunks of javascript when they are below the fold. We can lazy load these interfaces improving load performance, without impact UX.

What I'm not 100% on right now, is whether it makes sense to lazy load the interface on the home page. It would improvement performance considerably but a delay in rendering those interfaces could be detrimental to the user experience. I'll look into this more closely.

**Comment by abidlabs** [comment]
Looks like we can close this @pngwn?
