### ISSUE TITLE
Model3D is rendered as see through/pixelated

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#5765]
### Describe the bug

I was laying around with Model3D component demo on spaces (as well as locally). After clicking on some of the examples, the file is rendered as a see through object with some of its polygons noticeable. 

This is printed in the console:
`[.WebGL-0x11001a67a00] GL_INVALID_OPERATION: Must have element array buffer bound.`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

![model3d_woes](https://github.com/gradio-app/gradio/assets/41651716/5c896453-50a1-4605-b029-9c40d251c78d)

### System Info

```shell
3.45.2 on spaces and locally

Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 3.45.0b10
gradio_client version: 0.5.3

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 4.2.0
fastapi: 0.101.0
ffmpy: 0.3.1
gradio-client==0.6.0-beta.1 is not installed.
httpx: 0.23.0
huggingface-hub: 0.17.0rc0
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.1
matplotlib: 3.7.2
numpy: 1.21.6
orjson: 3.9.4
packaging: 22.0
pandas: 1.3.5
pillow: 9.2.0
pydantic: 2.4.0
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.28.1
semantic-version: 2.10.0
typer: 0.9.0
typing-extensions: 4.7.1
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.23.0
huggingface-hub: 0.17.0rc0
packaging: 22.0
requests: 2.28.1
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by miikkuu** [comment]
should i go for it? or are you gonna pull?

**Comment by freddyaboulton** [comment]
Go for it @miikkuu !

**Comment by freddyaboulton** [comment]
Hi @miikkuu ! I would first make sure this issue still exists. @hannahblair made some changes to the Model3D component that maybe fixed this. If the problem persists, I would look at `js/model3d` directory. We use babylon js to render 3d assets so it's probably due to that.

**Comment by CedricGuillemet** [comment]
I'm a Babylon.js core maintainer. I'll take a look and see if I can repro with 4.2.2. I guess it's been fixed in more recent versions. I'll test version 7+ as well.

**Comment by abidlabs** [comment]
Thanks @CedricGuillemet! I took a look to see if the issue persists on the latest version of `gradio`, and I can no longer reproduce it. So I wouldn't worry about it. For reference, we currently use:

> "babylonjs": "^5.57.1"
