### ISSUE TITLE
disable inline status messages for outputs that are also inputs

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#5773]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Some component instances are both inputs and outputs, if there is an error this can result in the component being unusable as an input (and essentially discarding the existing state, as you need to clear/reset/reload). 

**Describe the solution you'd like**  
If a component instance is both and output and an input then it would be nice if inline status message were either hidden or dismissable by default.

We have the toast message, so I don't think the inline error/ status is strictly necessary. The same is also true for the loading status (the chatbot had this issue).

cc @apolinario

**Comment by abidlabs** [comment]
Going to close this in favor of the duplicate https://github.com/gradio-app/gradio/issues/6700 (which although is later, has a full repro)
