### ISSUE TITLE
Nits on the Getting Started page

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#5778]
- [x] I have searched to see if a similar issue already exists.

There are too many separate concepts in the "Sharing Your App" section of the getting started guide.

<img width="1568" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/866b6aa6-5260-466c-bdaa-220e779dcfd4">

My Recommendation:
* `Mounting within another...` should be under the `Sharing Your App` Header
* Pull `Authentication` into another section and include `Password Protected...` and `OAuth` into that section
* `Accessing the Network Request` feels pretty random here. Maybe move to `Key Features`?
* `Security` should pulled out into its own section.
* `Api Usage` should be pulled out into its own section.

**Comment by reginareynolds** [comment]
I can take this one.

**Comment by abidlabs** [comment]
Thanks that'd be great @reginareynolds, looking forward to your PR!

**Comment by reginareynolds** [comment]
This is going to sound like a silly question, but where did the website folder go? According to the [Contributing](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md#-structure-of-the-repository) document, it's supposed to be in the root directory, but it's not. Did it get moved to the _website folder in the js directory?

**Comment by abidlabs** [comment]
Hi @reginareynolds oh wow good catch! Yes, the website is now located at `/js/_website`. Would you like to open a PR to fix our contributing guide first?

Thanks so much!

**Comment by Luwa-Tech** [comment]
Hi @abidlabs  is this issue still open.

**Comment by freddyaboulton** [comment]
Yea @Luwa-Tech ! If you'd like to open a PR, please feel free

**Comment by debrupf2946** [comment]
@freddyaboulton I want to work on the issue, I will be opening a  PR by today
