### ISSUE TITLE
Fix of root_path change works fine but not when I do queue

### ISSUE THREAD

**Issue by ahmedxomar101** [gradio-app/gradio#5779]
### Describe the bug

There were a lot of threads about routing the gradio app to a custom path using the root_path argument and nginx.

Here is my settings:

1. Gradio
    ```
    demo.launch(
        server_name='127.0.0.1', server_port=9000,
        root_path="/app",
    )
    ```
2. Nginx
    ```
    location /app/ {
                proxy_pass http://127.0.0.1:9000/;
            }
    ```

And this works fine thanks to bug fix. But once I use a queue:
```
demo.queue(concurrency_count=2).launch(
    server_name='127.0.0.1', server_port=9000,
    root_path="/app",
)
```
I get the following error:
![Untitled](https://github.com/gradio-app/gradio/assets/44009418/27d50551-675f-42a7-b0f0-43764467a102)

And I don't recieve any error messages in my terminal.

When I inspected the network in the dev tools I found this error:
![image](https://github.com/gradio-app/gradio/assets/44009418/67b978d2-5c90-49c3-a786-f989e4d1f562)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
demo.queue(concurrency_count=2).launch(
    server_name='127.0.0.1', server_port=9000,
    root_path="/app",
)
```

### System Info

```shell
The latest version of gradio 3.46.0 released 17 hours ago, made different issues so I downgraded to 3.44.4
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Thanks @ahmedxomar101 I believe there was a mistake -- we are reverting the change and trying a different approach in this PR: https://github.com/gradio-app/gradio/pull/5776

Feel free to follow that PR to stay tuned on updates

**Comment by abidlabs** [comment]
Could you try installing `pip install https://gradio-builds.s3.amazonaws.com/83b7a8ebc352a790fa25ee509753ad29647c8ae9/gradio-3.46.0-py3-none-any.whl` (its the version of gradio directly from that branch) and see if it resolves the issue for you?

**Comment by ahmedxomar101** [comment]
I still have same issue. The app works fine on the custom path without the queue and I get the same error with the queue. 

Also worth mentioning with this version, the gr.inputs.Textbox is not rendered somehow 
![image](https://github.com/gradio-app/gradio/assets/44009418/79111cd3-e495-4ce1-a127-d8cdffc457f2)
but since I have examples I managed to submit one of them for testing.

**Comment by abidlabs** [comment]
That's very strange -- could you share the code for your gradio app (or another minimal working example) so that we can reproduce?

**Comment by ahmedxomar101** [comment]
Hello @abidlabs,
Any news about this bug? I want to use the queue especially since the app running in one of the tabs takes more than one minute to get the output and in the browser, I get the timeout error. I checked for solutions and found that I have to use a queue.

If I can use queues in other circumstances let me know and I can adapt my app. For example, if I have to not use a tabbed interface or so. Thank you very much.

**Comment by abidlabs** [comment]
We'll take a look as soon as we can! Sorry we haven't had a chance yet to investigate

**Comment by joppichristian** [comment]
Hello @abidlabs ,
Any news about this bug?

Thanks

**Comment by abidlabs** [comment]
Hi @joppichristian @ahmedxomar101 can you please check if this is still an issue in the latest version of Gradio (4.7.1 currently)? We've changed the way that we implement the queue (to use server-side events instead of websockets) and the Gradio queue is enabled by default in all Gradio apps. Can you let us know if you are still seeing this issue?

**Comment by abidlabs** [comment]
Closing for lack of follow up
