### ISSUE TITLE
Specify Example Caching Directory

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#5781]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Would be great to specify the directory gradio uses to cache examples. This would allow developers to save the cache to persistent storage on HF Spaces.

**Describe the solution you'd like**  
Support specifying the cached directory via environment variable and a parameter in the examples class.

**Additional context**

**Comment by SrijanSahaySrivastava** [comment]
Heya, could you please elaborate your request. I'm interested on working on this but need some guidance. thank you <3

**Comment by henryruhs** [comment]
@freddyaboulton Why is this request towards examples only? I think Gradio is using Python's `tempfile` module. You can actual specifiy the directory via ENV if this is what you are looking for.

> On Windows modify the TEMP environment variable, while on Unix based operating systems, alter the TMPDIR instead.

**Comment by freddyaboulton** [comment]
For files created during the application's lifetime, users can determine the directory where those files are created via `GRADIO_TEMP_DIR` variable. That can't be done for examples. They always get cached to `gradio_cached_examples` in the directory where the python launch command was called from.

**Comment by Ashhar-24** [comment]
Hello @freddyaboulton, I would love to work on this issue actively, but I am not able to understand what is required to be done.
And like from which folder am I supposed to work on, I'm not able to understand.
Kindly guide me through.
Thanks :)
