### ISSUE TITLE
Pause autoscrolling if a user scrolls up in a `gr.Chatbot` and resume autoscrolling if they go all the way down

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#5785]
- [x] I have searched to see if a similar issue already exists.

It would be awesome if `gr.Chatbot` supported this feature of `gr.Textbox`: #5652 .

**Comment by aliabid94** [comment]
This is already this case, no? Maybe it wasn't when the issue was opened. Can you clarify @hysts

**Comment by hysts** [comment]
Yeah, this was fixed long ago. I'll close this. Thanks!
