### ISSUE TITLE
A relaunch() Method for Easier Interface Restart in Gradio

### ISSUE THREAD

**Issue by chaofanqw** [gradio-app/gradio#5791]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Currently, there's no straightforward method to relaunch the Gradio interface with modified parameters, like changing language settings. While I can use the multiprocess package from Python to achieve a similar effect, it would be much more efficient and user-friendly to have this capability natively within Gradio. I have tested gradio xx.py but it is not able to take other parameters and will not terminate the current interface.

**Describe the solution you'd like**  
I'd like a method, perhaps named `relaunch()`, to be introduced in the Gradio library. This function should allow the Gradio interface to be restarted based on saved or modified settings, such as language preferences or other parameters.

Example desired usage: 
```python
demo.relaunch()
```

Using this function, the Gradio interface could be relaunched, for instance, with different language settings without needing to use external multiprocessing tools.

**Additional context**  
Below is my current workaround, where I utilize the `multiprocessing` package to recreate the Gradio interface:

```python
import gradio as gr
from multiprocessing import Process, Manager
import time
import logging


def reload(interface_val):
    language_code = json.load(open('language.json'))['language']
    language_code = 'en' if language_code == 'zh' else 'zh'
    json.dump({'language': language_code}, open('language.json', 'w'))

    interface_val['reset_status'] = True


def create_demo(my_demo, interface_val):
    language_code = json.load(open('language.json'))['language']
    with my_demo:
        if language_code == 'zh':
            gr.Markdown("# 你好！")
        else:
            gr.Markdown("# Greetings!")

        btn = gr.Button(value="Change Language")
        btn.click(lambda: reload(interface_val))


def create_interface(interface_generator, interface_val):
    my_demo = gr.Blocks()
    interface_generator(my_demo, interface_val)
    my_demo.launch()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    interface_val = Manager().dict()
    interface_val['reset_status'] = False

    ui_thread = Process(target=create_interface, args=(create_demo, interface_val))
    ui_thread.start()

    while True:
        if interface_val['reset_status']:
            if ui_thread.is_alive():
                ui_thread.terminate()
                ui_thread.join(timeout=1)

            ui_thread.close()
            ui_thread = Process(target=create_interface, args=(create_demo, interface_val))
            ui_thread.start()

            interface_val['reset_status'] = False

        time.sleep(1)
```

As seen from the code above, having a simpler method to relaunch the interface would greatly streamline the process and provide a better user experience.

**Comment by pngwn** [comment]
Could you provide more details on why the `gradio xx.py` command doesn't work for you?

**Comment by chaofanqw** [comment]
The cli instead, reruns the code and starts the new port, which is a bit hard to maintain when I need to do reverse port forwarding.

The sample code is 
```python
def change_language():
    language = json.load(open('language.json'))['language']
    if language == 'zh':
        json.dump({'language': 'en'}, open('language.json', 'w'))
    else:
        json.dump({'language': 'zh'}, open('language.json', 'w'))

    os.system("gradio test.py")


with gr.Blocks() as demo:
    language = json.load(open('language.json'))['language']
    if language == 'zh':
        gr.Markdown("# 你好！")
    else:
        gr.Markdown("# Hello!")

    btn = gr.Button(value="Submit")
    btn.click(change_language)

if __name__ == '__main__':
    demo.launch()
```

The outcome is 
```
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
Watching: 'xxxx/lib/python3.10/site-packages/gradio', 'xxx'

Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.
```

**Comment by abidlabs** [comment]
Hi @chaofanqw can't you just call `demo.launch()` again and the Gradio app will relaunch on the same port?

**Comment by chaofanqw** [comment]
For my side, the interface is not rendered again when I call demo.launch() again

text.py
```python
import gradio as gr


def reload():
    language_code = json.load(open('language.json'))['language']
    language_code = 'en' if language_code == 'zh' else 'zh'
    json.dump({'language': language_code}, open('language.json', 'w'))

    demo.launch()


with gr.Blocks() as demo:
    language_code = json.load(open('language.json'))['language']
    if language_code == 'zh':
        gr.Markdown("# 你好！")
    else:
        gr.Markdown("# Greetings!")

    btn = gr.Button(value="Change Language")
    btn.click(reload)

demo.launch()
```

language.json
```json
{
  "language": "zh"
}
```

The interface will be the same with refreshing
![Screenshot 2023-10-04 195914](https://github.com/gradio-app/gradio/assets/44720017/112b222c-5b52-4c0f-ae01-70d4ba623a07)

**Comment by abidlabs** [comment]
Oh I see, so you want to refresh the UI by clicking on a particular button. For something like this, it wouldn't make sense to have a command like `demo.relaunch()` since this would be called once, outside of the Gradio app. 

Right now, you'll need to refresh the UI manually, with something like this:

```py
import gradio as gr


def reload():
    language_code = json.load(open('language.json'))['language']
    language_code = 'en' if language_code == 'zh' else 'zh'
    json.dump({'language': language_code}, open('language.json', 'w'))
    if language_code == 'zh':
        return gr.Markdown("# 你好！")
    else:
        return gr.Markdown("# Greetings!") 


with gr.Blocks() as demo:
    m = gr.Markdown("# Greetings!") 
    btn = gr.Button(value="Change Language")
    btn.click(reload, None, m)

demo.launch()
```

I understand that this can be come cumbersome with complex gradio apps. We are brainstorming more "stateful" flows -- in which you can update a single state variable and then have many UI changes get triggered as a result. Feel free to chime into that issue here: https://github.com/gradio-app/gradio/issues/2570

**Comment by mouadenna** [comment]
> Hi @chaofanqw can't you just call `demo.launch()` again and the Gradio app will relaunch on the same port?
```

demo.launch()
demo.close()
chatbot.launch()
```
i think in this case we need a reload to display the chatbot

**Comment by Alzok** [comment]
Make a file stop.sh like that for windows : 
#!/bin/bash
PORT=7860

# Récupération dynamique du PID du processus écoutant sur le port 7860
PID=$(/c/Windows/System32/netstat.exe -ano | /c/Windows/System32/findstr.exe :$PORT | awk '{print $5}' | head -n1 | tr -d '\r')

if [ -n "$PID" ]; then
    echo "Tuer le processus sur le port $PORT (PID: $PID)..."
    /c/Windows/System32/taskkill.exe //F //PID "$PID"
    echo "Processus terminé."
else
    echo "Aucun processus trouvé sur le port $PORT."
fi
