### ISSUE TITLE
Calling gradio app.py -> ModuleNotFoundError: No module named 'gradio' 

### ISSUE THREAD

**Issue by kagenihisomi** [gradio-app/gradio#5804]
### Describe the bug

I can load Gradio App through python app.py but not through gradio app.py

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

This loads the Gradio Application
```
python app.py
```
but, this has the following error 
```
gradio app.py
```
ModuleNotFoundError: No module named 'gradio' 

Running the following in a python shell also causes the same issue
```
from gradio.cli import cli
import sys
sys.argv[1:] = ["app.py"]
cli()
```
ModuleNotFoundError: No module named 'gradio'

My base python installation is pyenv-win, which I suspect is the issue but not sure

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 3.46.0
gradio_client version: 0.5.3

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.1
fastapi: 0.103.2
ffmpy: 0.3.1
gradio-client==0.5.3 is not installed.
httpx: 0.25.0
huggingface-hub: 0.17.3
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.3
numpy: 1.24.4
orjson: 3.9.7
packaging: 23.2
pandas: 2.0.3
pillow: 10.0.1
pydantic: 2.4.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.8.0
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.9.2
httpx: 0.25.0
huggingface-hub: 0.17.3
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @kagenihisomi I can't reproduce this. Can you try uninstalling and reinstalling gradio? Can you also ensure there's no file named gradio in that directory?

**Comment by kagenihisomi** [comment]
Yes, there's no file named gradio in workspace

**Comment by abidlabs** [comment]
Hi @kagenihisomi as we're not able to reproduce this issue, we'll have to close. Let us know if you are able to provide more details that help us repro this

**Comment by abidlabs** [comment]
Actually, looking at this error:

> ModuleNotFoundError: No module named 'gradio'

It sounds like you might be running `gradio app.py` inside of Python shell, instead of the Windows terminal. Is that the case?

**Comment by NameMeLeo** [comment]
For someone in 2024 face this issue multipart is newly renamed as python_multipart, so you might want to use pip install python-multipart==0.0.12 to handle this issue.

![image](https://github.com/user-attachments/assets/ab567bd6-15fc-4a69-a090-2f3fe3ce302f)
