### ISSUE TITLE
Gradio.Image is broken

### ISSUE THREAD

**Issue by henryruhs** [gradio-app/gradio#5805]
### Describe the bug

For some reason, the img tag is now wrapped within a button for no good reason.

![grafik](https://github.com/gradio-app/gradio/assets/1835397/d840a0de-34f6-4ce4-bd13-4d1c0a26f1e8)

1. Breaks the border-radius
1. Adds unwanted spacing at the bottom
1. Breaks `object-fit: contain;` sometimes

### Before, using Gradio 3.44.3

![grafik](https://github.com/gradio-app/gradio/assets/1835397/7de8d635-fabc-4656-8e08-e2c39e0b26b5)

### After, using Gradio 3.46.1

![grafik](https://github.com/gradio-app/gradio/assets/1835397/1cb3857a-f4ab-4740-9648-460f43e5c598)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

I can just tell you to use the master of FaceFusion and update gradio. Opening the both versions in a browser tab and switch between them - you will instantly recognize the bugs.

### Screenshot

FireFox and Chrome on MacOS. I guess caused by higher DPI.

![grafik](https://github.com/gradio-app/gradio/assets/1835397/0a672b0d-a9b3-4b6b-9499-192f8f5249c4)

### System Info

```shell
FireFox 118
```

### Severity

Blocking usage of gradio

**Comment by henryruhs** [comment]
> General speaking, we have a quality problem, cannot upgrade since 3.35.x as of bugs like that. In one version the Gallery thumbnail was super huge. How can something like this make it into a release?

**Comment by pngwn** [comment]
3.35.x is an excellent version. One of the best!

**Comment by henryruhs** [comment]
@pngwn Well, I love to update once this bug is fixed.

**Comment by henryruhs** [comment]
Ugly workaround for the moment:

```css
:root:root:root button:not([class])
{
	border-radius: 0.375rem;
	float: left;
	overflow: hidden;
}
```

**Comment by THEGAMECHANGER416** [comment]
@abidlabs I would like to help on this issue, I agree that we need to remove the button tag thats all.
I can work on this issue if needed.
Thanks

**Comment by abidlabs** [comment]
Agreed -- let's close this issue.
