### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by Gracetoh** [gradio-app/gradio#5818]
### Describe the bug

ReadTimeout: HTTPSConnectionPool(host='9258c49871fe21e887.gradio.live', port=443): Read timed out. (read timeout=3)

was able to run the code yesterday but unable to do so today... error message popped up

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

# Define the Gradio interface
audio_input = gr.inputs.Audio(label="Upload Audio", type="filepath")
model_dropdown = gr.Dropdown(list(model_options.keys()), label="Select Model")
output_audio = gr.outputs.Audio(label="Enhanced Audio", type="filepath")

iface = gr.Interface(
    fn=process_audio,
    inputs=[audio_input, model_dropdown],
    outputs=[output_audio]
)

iface.launch(share=True)

### System Info

```shell
this is my gradio version: 3.45.1
```

### Severity

Blocking usage of gradio

**Comment by laphang** [comment]
I had the same issue just now (also was working yesterday), it seems like share links servers are down atm.

https://status.gradio.app/
https://status.gradio.app/793595809

**Comment by Gracetoh** [comment]
thanks so much!

**Comment by henryruhs** [comment]
@Gracetoh I think you can close this issue.
