### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'python'

### ISSUE THREAD

**Issue by flashzzz** [gradio-app/gradio#5823]
### Describe the bug

When running gradio app in reload mode, the following FileNotFound error is thrown. This is because of the subprocess called in gradio/reload.py
It should be python3 instead of python.
I'm on MacBook Pro 
MacOS Sonoma 14.0
<img width="1111" alt="image" src="https://github.com/gradio-app/gradio/assets/73419491/4dc6cc46-a69d-4158-97eb-e334cc7a5825">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

I only have python3 and not python2.
Also 'python' is aliased to python3 path.

### Screenshot

<img width="1111" alt="image" src="https://github.com/gradio-app/gradio/assets/73419491/741e26ed-d18b-4a74-90a2-25f0fc24ec0c">

### System Info

```shell
gradio==3.42.0
macOS==Sonoma 14.0
```

### Severity

I can work around it

**Comment by flashzzz** [comment]
A simple workaround is to change `python` to `python3` in gradio/reload.py file

**Comment by henryruhs** [comment]
This is not a Gradio issue...

**Comment by pngwn** [comment]
@flashzzz that will simply break it for people who have installed python3 as python.

**Comment by pngwn** [comment]
It isn't a gradual issue but we can make the experience better here. In the mean time you can alias python3 to python.

**Comment by flashzzz** [comment]
@pngwn I already have python as alias for python3, but for some reason it didn’t work, so I modified the reload.py. Thank you for your replies :)
