### ISSUE TITLE
Flash of unstyled content at initial load

### ISSUE THREAD

**Issue by whitphx** [gradio-app/gradio#5825]
### Describe the bug

Looks like loading CSS file is not finished before the frontend app connects the backend and starts running.

https://github.com/gradio-app/gradio/assets/3135397/3f26371b-04d6-4cda-8ca2-af3062e0a306

This screenshot was recorded on https://www.gradio.app/docs/audio

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Access https://www.gradio.app/docs/audio

### System Info

```shell
Gradio 3.47.1 (the embedded space info)
```

### Severity

I can work around it

**Comment by henryruhs** [comment]
Yes, something must be off with their website - it loads the theme.css 3 times

![grafik](https://github.com/gradio-app/gradio/assets/1835397/3a4de0ce-7f7b-4993-ba91-a51a7a70d37d)

**Comment by abidlabs** [comment]
@aliabd could you take a look?

**Comment by whitphx** [comment]
In addition to the docs pages' file serving,
it seems also a problem that Vite's FOUC prevention is not working at the application level? @pngwn

**Comment by abidlabs** [comment]
Closed via #8220
