### ISSUE TITLE
Investigate UploadFile Optimization

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#5829]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
The UploadRoute uses `FileUpload` which under the hood uses a `SpooledTemporaryFile` [link](https://fastapi.tiangolo.com/tutorial/request-files/?h=upload#__tabbed_3_3). This will write the file to disk if its larger than a certain size. We then iterate over the file and write it to a separate location.

So we're writing the file twice. I wonder if we can just copy the file to a new location? Or iterate through the bytes of the file without having to write it to disk.

**Describe the solution you'd like**  

**Additional context**

**Comment by henryruhs** [comment]
I think a hash dict could be an option. Good issue, I thought about this recently.

**Comment by freddyaboulton** [comment]
This is done in the v4 branch!
