### ISSUE TITLE
Write more huggingface guides/blogs related to Gradio

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#583]
Anchor link text should include relevant key words.

**Comment by aliabd** [comment]
There are no real opportunities I could find for further cross linking in the huggingface blog. So will change this issue to focus on writing more content related to gradio there, as the last blog post I could find related to Gradio was the 3.0 launch in May 2022

**Comment by abidlabs** [comment]
I think we should close this for now. We can potentially write some blog posts but as it stands this issue is not really actionable. Feel free to reopen @pngwn @aliabd if you disagree
