### ISSUE TITLE
Clean up the code related to `root` and `root_url`

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#5830]
All the code to resolve URL paths correctly with `root` and `root_url` has gotten quite messy. 

It would be good to clean this up. In particular, now that replicas [use subdirectories instead of subdomains](https://huggingface.slack.com/archives/C048K60MPNF/p1696569642166729), we can revert most of the changes we made in PRs #5776 and instead just use the same logic we use for the regular fastapi root path.

For clarity, we should also rename `root_url` to `remote_url` or something.

**Comment by HeetVekariya** [comment]
I would like to work on this issue.
As i am new to this repo, can you please locate the files that is to be refactored ?

**Comment by abidlabs** [comment]
Hi @HeetVekariya this isn't an issue I'd suggest if you are new to the repo, as there is some internal discussion and context that is important. Instead, I'd suggest picking one of the issues from this list: https://github.com/gradio-app/gradio/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by abidlabs** [comment]
Let's rename `root_url` to `_remote_url` to designate it as an internal parameter in the component classes

**Comment by abidlabs** [comment]
Also see [this internal discussion](https://huggingface.slack.com/archives/C02SPHC1KD1/p1697823622462199?thread_ts=1697724198.460679&cid=C02SPHC1KD1)

**Comment by abidlabs** [comment]
Closed on `v4`!
