### ISSUE TITLE
How to set the window size of gr.Examples？

### ISSUE THREAD

**Issue by konioy** [gradio-app/gradio#5834]
I want to make the window of gr.Examples larger so that I can see the content of the video more clearly.
What should I do?

**Comment by yvrjsharma** [comment]
This is not currently possible imo however, cc: @hannahblair @abidlabs 
Also, a better place for such queries and support would be our Discord server - https://discord.com/channels/879548962464493619/1025174734427656283

**Comment by abidlabs** [comment]
Hi @konioy -- you could probably use [Custom CSS](https://www.gradio.app/guides/custom-CSS-and-JS) to set the height of the video element. But as @yvrjsharma mentioned, for general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
