### ISSUE TITLE
how to solve the warrning "UserWarning: `width` is deprecated in `Interface()`, please use it within `launch()` instead."

### ISSUE THREAD

**Issue by falibabaei** [gradio-app/gradio#5846]
Hi, 

I have the following piece of code that takes my API input and converts it to the Gradio input. The user uses the GUI and sends a request to my API to make a prediction. The output is either a json file or a pdf file with a plot.

'''
with gr.Blocks() as demo:
        gr.Markdown("RNA Contact prediction with deep learning.")

        with gr.Tab("simple prediction"):
            gr_inp, _, _ = utils.api2gr_inputs(
                api_inp, metadata, advanced=False
            )
            output = gr.Plot(width=300, height=300)
            b2 = gr.Button("submit")
        b2.click(api_call_pdf_output, inputs=gr_inp, outputs=output)

        with gr.Tab("advanced prediction"):
            gr_inp, _, _ = utils.api2gr_inputs(
                api_inp, metadata, advanced=True
            )
            with gr.Tab(label="get prediction as json file"):
                output1 = gr.JSON(label="output")
                b1 = gr.Button("Submit")
            b1.click(api_call, inputs=gr_inp, outputs=output1)

            with gr.Tab(label="Plot RNA contact map from prediction"):
                output = gr.Plot(width=300, height=300)
                b1 = gr.Button("Submit")

            b1.click(
                api_call_pdf_output, inputs=gr_inp, outputs=output
            )

    demo.launch(
        share=False,
        show_error=True,
        server_name=GRADIO_SERVER,
        server_port=ui_port,
    )
 

I want to have a square plot, but I have received the following warning
GUI_plotly/launch.py:156: UserWarning: `width` is deprecated in `Interface()`, please use it within `launch()` instead.
  api_call_pdf_output, inputs=gr_inp1, outputs=gr.Plot(width=300, height=300)
GUI_plotly/launch.py:156: UserWarning: `height` is deprecated in `Interface()`, please use it within `launch()` instead.
  api_call_pdf_output, inputs=gr_inp1, outputs=gr.Plot(width=300, height=300)
how to solve these warning

**Comment by abidlabs** [comment]
Hi @falibabaei the warning is misleading. The actual issue is that `gr.Plot` doesn't take a width or height parameter.

Instead, you should set the height of your plotly plot before returning it from your function. Gradio should render it with the same width and height.

You can see how to set the height/width of a plotly plot here: https://plotly.com/python/setting-graph-size/
