### ISSUE TITLE
When gr.Blocks.queue is set to True, gr.Request.request is None

### ISSUE THREAD

**Issue by coolboyqu** [gradio-app/gradio#5856]
### Describe the bug

I have just started working with FastAPI and may encounter some naive issues, please forgive me. The problem is as follows: I want to create a login interface that passes username through session (I know Blocks comes with login function, but I want to separate login function from application), but when I set queue to True, gr.Request.request is None, and when queue is set to False, session can be correctly obtained through gr.Request.request. I don't know what the problem is right now. Can you help me solve it? Thank you very much.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import time
import gradio as gr
import uvicorn
from fastapi import FastAPI, Request, Form
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from fastapi.responses import RedirectResponse
from starlette.middleware.sessions import SessionMiddleware

app = FastAPI()
app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="templates")
app.add_middleware(SessionMiddleware, secret_key="!secret")

@app.get("/")
def login_form(request: Request):
    return templates.TemplateResponse("login.html", {"request": request})

@app.post("/login")
def login(request: Request, username: str = Form(...), password: str = Form(...)):
    request.session.update({"user": username})
    if username == 'admin' and password == 'admin':
        response = RedirectResponse(url="/admin", status_code=303)
        return response
    else:
        return {"Login": "Failed"}

def init_web(req: gr.Request):
    print(req.request)

with gr.Blocks() as admin:
    gr.Button("test")
    admin.load(
        fn=init_web,
        inputs=None,
        outputs=None,
        queue=True,
        show_progress=False,
    )
admin.queue(concurrency_count=3)

app = gr.mount_gradio_app(app, admin, path="/admin")

if __name__ == '__main__':
    uvicorn.run(
        app='test:app',
        host="0.0.0.0",
        port=8000,
        workers=4,
        reload=True)

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/36916120/7137bce8-3070-423b-bc97-917ffa399df9)

### Logs

```shell
None
```

### System Info

```shell
gradio-3.47.1
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Were you able to figure out the solution @coolboyqu?

**Comment by coolboyqu** [comment]
> Were you able to figure out the solution @coolboyqu?

Yes, it has been resolved. It's strange that I used pycharm to debug my code, and gr.Request did not prompt for the 'session', but it does exist. Now I can read the 'user' that I passed in using gr.Request.session, but gr.Request.request is still 'None'

**Comment by dedeswim** [comment]
Hi!

I would need to access `request.request` in my Gradio app with queueing enabled, but it happens to be `None` as described above. Is this an intended behaviour? Is there another way to access the FastAPI request?
