### ISSUE TITLE
Please do not remove gr.update()

### ISSUE THREAD

**Issue by oobabooga** [gradio-app/gradio#5863]
After updating from gradio 3.33 to 3.47, I noticed that the `gr.update` method has been deprecated.

I would like to request that this parameter remains part of gradio. Here are some of its use cases:

1) Hiding an showing elements using events:

```
lambda: gr.update(visible=True), None, my_element
```

2) Making elements interactive or not:

```
lambda: gr.update(interactive=False), None, my_element
```

3) Updating the list of choices for a dropdown and the selected value:

```
lambda x: gr.update(choices=get_available_characters(), value=x), character_name, character_menu
```

For complex applications with many components, redeclaring the component each time one of its attributes needs to be updated becomes a major inconvenience.

**Comment by abidlabs** [comment]
Just to confirm, you'd like for us to keep `gr.update()` but are fine with deprecating the specific component.update methods (since they're easy to replace with just the component themselves)?

Seems reasonable to me, cc @aliabid94 wdyt?

**Comment by oobabooga** [comment]
Yes, that is correct. I think I have never used a `component.update()` method, but I use `gr.update()` very extensively. For some examples, see:

https://github.com/oobabooga/text-generation-webui/blob/f63361568c476ff4b2414a06027bc22e6123941f/modules/ui_chat.py#L238

**Comment by henryruhs** [comment]
I disagree, it was the right decision to get rid of any update() method as it just returns a dict and is not typesafe.

**Comment by aliabid94** [comment]
> For complex applications with many components, redeclaring the component each time one of its attributes needs to be updated becomes a major inconvenience

@oobabooga the way that updating works now is that you only set the values of the arguments that are going to be updated in the returned component, you don't have to redeclare the other properties of the component. So now, `return gr.Dropdown(visible=False)` and `return gr.update(visible=False)` have **exactly** the same behaviour - the former though also provides type hints. Isn't this strictly better?

You would have to change `gr.update` to the name of the component class that is being updated, that's all

**Comment by oobabooga** [comment]
Thanks for the clarification @aliabid94. That's better, but imo there is still a loss in removing `gr.update()`. Take it for instance here:

https://github.com/oobabooga/text-generation-webui/blob/main/modules/ui.py#L180

This function is used to update all elements in the interface, and `gr.update()` is key for that.

The syntax is also very readable - `gr.update(visible=False)` is more readable than `gr.Dropdown(visible=False)`.

If the `gr.update()` definition takes just a few lines in the Gradio codebase, I would vote for keeping it.

**Comment by henryruhs** [comment]
> The syntax is also very readable - gr.update(visible=False) is more readable than gr.Dropdown(visible=False)

You don't use typing in Python, right?

**Comment by oobabooga** [comment]
Python is a dynamically typed language.

**Comment by henryruhs** [comment]
What a nonsense comment, like that whole issue.

**Comment by abidlabs** [comment]
@henryruhs please do not comment disrespectfully on other people's issues in this manner. Generally, the Gradio repo is a place where we want to have productive and kind conversations. Feedback is always appreciated, but being kind, empathetic, and respectful when giving it is also important. Don't forget there are people at the other side of the screen. If we see these kinds of comments from you, we'll have no choice but to block you from the repo.

**Comment by abidlabs** [comment]
Regarding the matter at hand, thanks for explaining @oobabooga. We'll discuss internally and come up with a plan.

**Comment by henryruhs** [comment]
@abidlabs Fair enough! I have indeed a lack of respect towards developers using ANY, but asking a project that size to undo a API improvement just because of the own preferences... Well, that is what I call being disrespect towards others.

**Comment by abidlabs** [comment]
We're happy to consider such requests, if there's a reason or use case for them. @oobabooga has clearly provided several reasons.

**Comment by aliabid94** [comment]
I think the best compromise would be to add all the kwargs of gr.IOComponent() to gr.update (interactive, visible, elem_id, etc.), so that type hinting is still provided for these arguments.

**Comment by abidlabs** [comment]
I have a PR open here: https://github.com/gradio-app/gradio/pull/5890 would appreciate your feedback @aliabid94 and @oobabooga

**Comment by abidlabs** [comment]
On a related note @oobabooga we have a gradio-partners channel on discord where we will be discussing api changes, upcoming releases, etc. with gradio power users. Would you be interested in joining?
