### ISSUE TITLE
Could not create share link. Please check your internet connection

### ISSUE THREAD

**Issue by QJShan** [gradio-app/gradio#5865]
### Describe the bug

I downloaded the frpc_windows_amd64 file as required and placed it in the specified directory, but the shared link still cannot be opened.
![image](https://github.com/gradio-app/gradio/assets/131762142/93951f55-1995-4863-bb5e-ef62b0ff7e86)
![Uploading image.png…]()

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")

demo.launch(share=True)

### System Info

```shell
gradio 3.47.1
gradio_client 0.6.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @QJShan could you use this issue to discuss: #3677? We'll take a look at this as soon as we can
