### ISSUE TITLE
Could not load example

### ISSUE THREAD

**Issue by pipixin321** [gradio-app/gradio#5867]
### Describe the bug

When I run the following toy example from a local URL, it fails to load into the input box after clicking on Example,
when I type input text and submit, I could not get the output.
```
import gradio as gr

def print_text(text):
    print(text)

if __name__ == "__main__":
    examples = ['Hello', 'Hi', 'How are you']
    demo = gr.Interface(print_text, 
                        inputs='text', 
                        outputs ='text', 
                        examples=examples,
                        cache_examples=False,
                        description="print_test",
                        )
    
    demo.launch(share=False)
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

There are no erro or warning in terminal

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/66454973/f46cdad9-0c7e-4b91-b747-cdedf716bd68)

### System Info

```shell
Environments:
Linux
python 3.7
gradio-3.33.1
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
I think your safest bet would be to upgrade to the latest version of gradio @pipixin321 ! 

If you need to use 3.33.1 please make sure `gradio_client==0.2.5` is installed and pip pydantic to version 1 (`pip install pydantic=1.*`.

Also python 3.7 has officially reached end of life. I would recommend you upgrade to python 3.8 or higher!
