### ISSUE TITLE
Show user's imformation after login (use auth=... option)

### ISSUE THREAD

**Issue by stevenweish** [gradio-app/gradio#5870]
How can I know the users' session information after I login by the auth way? I'v tried many ways and looked for  many documents, I got none result.

**Comment by freddyaboulton** [comment]
Please see this code snippet @stevenweish !

https://github.com/gradio-app/gradio/pull/3296#issue-1597149898

**Comment by stevenweish** [comment]
Thanks a lot!

**Comment by peeter2** [comment]
I need to get the authenticated user email. Is that possible?

**Comment by freddyaboulton** [comment]
Nice @Fusseldieb !

**Comment by saaspeter** [comment]
Hi everyone: 

My code is from: [https://www.gradio.app/guides/creating-a-custom-chatbot-with-blocks](https://www.gradio.app/guides/creating-a-custom-chatbot-with-blocks) , like below:

It is very common to get current session user in bot function, but bot function cannot get Request parameter, I don't know how to get session information in bot function.  Does anyone know this? Thanks!
