### ISSUE TITLE
How can I find a compent by elem_id?

### ISSUE THREAD

**Issue by stevenweish** [gradio-app/gradio#5882]
I want to hid a component after login,how to find a component by elem_id?

**Comment by abidlabs** [comment]
Hi @stevenweish, your question is not super clear. Can you include a code snippet and more details on what you are trying to achieve? Regardless, for general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
