### ISSUE TITLE
How to get chatbot responses when using Gradio Client library

### ISSUE THREAD

**Issue by bhavishpahwa** [gradio-app/gradio#5887]
### Describe the bug

When using gradio client library to call an event(submit) which returns chatbot component as output I usualy get a path to a temporary json file in return where the file gets saved on my Mac. How can I get chatbot responses while querying an HF space in the input json file whose path I am sending to the space.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction
Sample code for a chatbot component app with named api for getting chatbot responses:-
```
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.ClearButton([msg, chatbot])

    def respond(message, chat_history):
        bot_message = sample_function(message)
        chat_history.append((message, bot_message))
        time.sleep(2)
        return "", chat_history

    msg.submit(respond, [msg, chatbot], [msg, chatbot], api_name= 'sample_api')

if __name__ == "__main__":
    demo.launch()
```
Sample Code for the Gradio Client script which tries to hit the 'sample_api' which is a named api:-

```
from gradio_client import Client

if __name__ == "__main__":
    client = Client(src=MyHuggingFaceSpace)
    
    print(client.predict(
    "Sample message",'chatbot.json'
    api_name="/sample_api",))
 
```   
Output of the Gradio Client Code:
```

('', '/var/folders/x4/xm31m0q105l3sxqwng3zg8t40000gq/T/tmpi8aiywf5.json')
```

### System Info

```shell
Latest Version of Gradio
```

### Severity

Blocking usage of gradio

**Comment by bhavishpahwa** [comment]
Hi @abidlabs I think the result json generated is getting saved at as a tempfile because currently there is no save_dir being passed to the function here:- https://github.com/gradio-app/gradio/blob/main/client/python/gradio_client/serializing.py#L489 and here it gets stored as tempfile instead :- https://github.com/gradio-app/gradio/blob/e70805d54cc792452545f5d8eccc1aa0212a4695/client/python/gradio_client/utils.py#L480 

When I try to send a save_dir argument through the predict function it gives an error.
<img width="619" alt="Screenshot 2023-10-12 at 9 17 21 PM" src="https://github.com/gradio-app/gradio/assets/108733252/8beafb59-795a-49aa-ac96-8c00d8b5c6e1">

How can I send the save_dir value through the client.predict function?

**Comment by abidlabs** [comment]
Hi @bhavishpahwa, you might find this useful: https://github.com/gradio-app/gradio/issues/5659#issuecomment-1734186921

For general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)

**Comment by bhavishpahwa** [comment]
Thanks for the reply @abidlabs, sure will keep in mind to post on discord from next time. Btw as far as I read the respective comment, saving the chat history result in the same json file from which one is reading the current history being sent through the api is not possible right now?

**Comment by abidlabs** [comment]
That's current, the json file is created as a temporary file automatically and you cannot specify the location of the temporary file.
