### ISSUE TITLE
Flagging Error when using mounted apps through FastAPI

### ISSUE THREAD

**Issue by Theehawau** [gradio-app/gradio#5892]
### Describe the bug

Hello, 

I'm trying to use the real time speech recognition sample from an existing FastAPI project. However when the fag button is clicked it raises an error: _Error while flagging: 'dict' object has no attribute 'startswith'_

gradio version: 3.47.1

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

    import gradio as gr
    from transformers import pipeline
    import numpy as np
    from fastapi import FastAPI
    from fastapi.responses import HTMLResponse
    
    app = FastAPI()
    transcriber = pipeline("automatic-speech-recognition", model="openai/whisper-base.en")
    
    REAL_ROUTE = "/realtime"

    def transcribe(stream, new_chunk):
        sr, y = new_chunk
        y = y.astype(np.float32)
        y /= np.max(np.abs(y))

    if stream is not None:
        stream = np.concatenate([stream, y])
    else:
        stream = y
    return stream, transcriber({"sampling_rate": sr, "raw": stream})["text"]

    real_demo = gr.Interface(
        transcribe,
        ["state", gr.Audio(source="microphone", streaming=True)],
        ["state", gr.Textbox(label="Transcription", interactive=True)],
        live=True,
    )
    index_html = f'''
    <!DOCTYPE html>
    <html lang="en">
    <body>
        
    </body>
    </html>
    '''
    @app.get("/", response_class=HTMLResponse)
    def index():
        return None

    app = gr.mount_gradio_app(app, real_demo, path=REAL_ROUTE)
    if __name__ == "__main__":
        import uvicorn
        uvicorn.run(app)

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/51090736/2bcdce4d-2c95-4e9a-94a8-6e4f9c4ddc1d)

### System Info

```shell
gradio version: 3.47.1
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
I'm not sure if flagging works with `live=True` when gradip is not mounted in another FastAPI app.

**Comment by Theehawau** [comment]
Any ideas? I'm trying to implement a real time speech recognition within a block so I can pass a then function when the user stops recording?

**Comment by freddyaboulton** [comment]
Thanks @Theehawau ! I encourage you to share your code so that others who stumble upon this issue know how to solve it!
