### ISSUE TITLE
Add separate `styler` parameter for `gr.Dataframe`

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#5895]
Relevant discussion:

Do you think it make more sense to make the styling a function that is part of the dataframe component? E.g.

```python
import pandas as pd 
import gradio as gr

df = pd.DataFrame({"A" : [14, 4, 5, 4, 1], 
				"B" : [5, 2, 54, 3, 2], 
				"C" : [20, 20, 7, 3, 8], 
				"D" : [14, 3, 6, 2, 6], 
				"E" : [23, 45, 64, 32, 23]}) 


def highlight_max(df):
  return df.style.highlight_max(color = 'lightgreen', axis = 0)

with gr.Blocks() as demo:
    gr.Dataframe(df, styler=highlight_max)
    
demo.launch()
```

And

```python
import pandas as pd 
import gradio as gr

df = pd.DataFrame({"A" : [14, 4, 5, 4, 1], 
				"B" : [5, 2, 54, 3, 2], 
				"C" : [20, 20, 7, 3, 8], 
				"D" : [14, 3, 6, 2, 6], 
				"E" : [23, 45, 64, 32, 23]}) 

def highlight_cols(df): 
	df.loc[:, :] = 'color: purple'
	df[['B', 'C', 'E']] = 'color: green'
	return df 

with gr.Blocks() as demo:
    gr.Dataframe(df, styler=highlight_cols)
```

This will be cleaner in cases where dataframe is an output of a function, so the function code doesn't get polluted with styling code, and decouples content from styling. E.g.

Currently:

```python
import pandas as pd
import numpy as np
import gradio as gr

with gr.Blocks() as demo:
  df = pd.Dataframe()
  random = gr.Button("Randomize")
  
  def randomize():
    new_df = pd.DataFrame(np.random.rand(5, 5))
    new_df.loc[:, :] = 'color: purple'
    new_df[['B', 'C', 'E']] = 'color: green'
    return new_df

  random.click(randomize, None, df)
```

versus decoupled:

```python
import pandas as pd
import numpy as np
import gradio as gr

with gr.Blocks() as demo:
  def style(df):
    df.loc[:, :] = 'color: purple'
    df[['B', 'C', 'E']] = 'color: green'
    return df

  df = pd.Dataframe(styler=style)
  random = gr.Button("Randomize")
  
  def randomize():
    return np.random.rand(5, 5)

  random.click(randomize, None, df)
```

So the styler would be run automatically in postprocessing

_Originally posted by @aliabid94 in https://github.com/gradio-app/gradio/issues/5877#issuecomment-1760411277_

**Comment by freddyaboulton** [comment]
I'm not sure we need the extra api. If your styling is encapsulated in a separate function, you can call it from your event handler. Also, what if the styling you want to apply depends on the inputs of the event? I don't think defining the styler before the event runs would work. 

So I don't think we should get rid of applying the style from the event. I guess we can add the extra arg, but don't really think we're gaining that much.

**Comment by abidlabs** [comment]
Yeah upon thinking about it some more, I agree with @freddyaboulton, closing
