### ISSUE TITLE
index.js:794 WebSocket connection to 'wss://c7w1u34dvofi2l-7861.proxy.runpod.net/queue/join' failed: 

### ISSUE THREAD

**Issue by FurkanGozukara** [gradio-app/gradio#5896]
**This is the error I am getting when running on RunPod and connecting via proxy Port**

**When I use --share with same gradio app it works**

**When I don't use queue it works via proxy port** 

**It works on Windows**

![image](https://github.com/gradio-app/gradio/assets/19240467/d06faa79-148b-4f06-97cd-b91c9dcd1531)

**Comment by abidlabs** [comment]
Hi @FurkanGozukara can you see if this is still an issue in 4.x? We've switched from using websockets to server-side-events

**Comment by FurkanGozukara** [comment]
> Hi @FurkanGozukara can you see if this is still an issue in 4.x? We've switched from using websockets to server-side-events

thank you so much

I just did test and for 427 i didn't timeout on runpod
