### ISSUE TITLE
favicon_path doesn't work

### ISSUE THREAD

**Issue by konioy** [gradio-app/gradio#5900]
### Describe the bug

favicon_path doesn't work
No error reported
version==3.23.0 and

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio as gr

gr.Interface(
    fn=lambda x:x,
    inputs="text",
    outputs="text",
).launch(
    favicon_path="favicon.ico",
)

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/24238694/ad27271f-594d-4a57-b3c4-7e225fcfab98)

### Logs

```shell
no
```

### System Info

```shell
gradio  3.47.1 and 3.23.0
Ubuntu 20.04
Chrome
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @konjoy, can you do a [hard refresh](https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache#:~:text=Chrome%20and%20Mac%3A,click%20the%20'R'%20key.)? The favicon should then show up. I confirmed in the latest version of `gradio` (3.47.1). If it does not, please let us know and we can reopen the issue.

**Comment by zlemonj** [comment]
favicon_path doesn't work
gradio==4.8.0
Chrome
 I have searched and found no existing issues

**Comment by konioy** [comment]
hard refresh : ctrl+F5

**Comment by i-am-mike-davis** [comment]
@abidlabs I'm having the same issue. Hard Refresh (CTRL + F5) does not fix on version 3.50.2

**Comment by abidlabs** [comment]
Could you try upgrading to the latest version of Gradio? 4.9.0?

**Comment by young-hun-jo** [comment]
@abidlabs  this feature is not working now.. how to solve this issue?

**Comment by yvrjsharma** [comment]
On version 4.16.0, I am able to use the favicon feature without any issues. I am using Google Colab. You may want to upgrade to this latest version.

**Comment by sk8boi** [comment]
The same problem, and I’m sure it’s not a picture or path problem.

**Comment by ghgr** [comment]
If you're using docker, try restarting the container. It worked for me

**Comment by umarbutler** [comment]
+1
