### ISSUE TITLE
lineplot demo python can not be executed normally

### ISSUE THREAD

**Issue by Shelliemayinforest** [gradio-app/gradio#5903]
### Describe the bug

Hi there,
I copy the code of lineplot example "live_dashboard"
![image](https://github.com/gradio-app/gradio/assets/95324821/687d71ff-caf5-4624-be3d-301bdff86075)
but when I run in my dev env, it reports an error .
![image](https://github.com/gradio-app/gradio/assets/95324821/50e17a04-3c23-4d58-8249-437fac513af3)

![image](https://github.com/gradio-app/gradio/assets/95324821/d499d23e-bf73-425f-841d-65d03fb6614b)

could you please tell me where the problem is ?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import math

import pandas as pd

import gradio as gr
import datetime
import numpy as np

def get_time():
    return datetime.datetime.now()

plot_end = 2 * math.pi

def get_plot(period=1):
    global plot_end
    x = np.arange(plot_end - 2 * math.pi, plot_end, 0.02)
    y = np.sin(2 * math.pi * period * x)
    update = gr.LinePlot(
        value=pd.DataFrame({"x": x, "y": y}),
        x="x",
        y="y",
        title="Plot (updates every second)",
        width=600,
        height=350,
    )
    plot_end += 2 * math.pi
    if plot_end > 1000:
        plot_end = 2 * math.pi
    return update

with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column():
            c_time2 = gr.Textbox(label="Current Time refreshed every second")
            gr.Textbox(
                "Change the value of the slider to automatically update the plot",
                label="",
            )
            period = gr.Slider(
                label="Period of plot", value=1, minimum=0, maximum=10, step=1
            )
            plot = gr.LinePlot(show_label=False)
        with gr.Column():
            name = gr.Textbox(label="Enter your name")
            greeting = gr.Textbox(label="Greeting")
            button = gr.Button(value="Greet")
            button.click(lambda s: f"Hello {s}", name, greeting)

    demo.load(lambda: datetime.datetime.now(), None, c_time2, every=1)
    dep = demo.load(get_plot, None, plot, every=1)
    period.change(get_plot, period, plot, every=1, cancels=[dep])

if __name__ == "__main__":
    demo.queue().launch()

### System Info

```shell
python 3.9
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @Shelliemayinforest which version of gradio are you running?

**Comment by abidlabs** [comment]
Closing for lack of followup, but I'd suggest upgrading to Gradio 4.0 to see if that fixes it!
