### ISSUE TITLE
Slow chatbot streaming in UI for single element just because many other static elements

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#5914]
### Describe the bug

In h2oGPT I noticed slow rendering in UI vs. back end for chatbot yield of LLM generation.  I narrowed it down to the number of static unused elements that are present when generating even if all those elements are not involved.

It probably depends upon the details of which elements for exactly how slow, but in my case the UI cannot sustain a streaming rate of more than 100 tokens/sec even if backend can.  I easily see the backend finish twice as soon as UI even for only a single line of about 100 characters.

However, I cannot fully reproduce this total extreme situation, but I can still give the same effect with a simpler code.  This code requires more elements than I have and only shows a difference in BE and UI for a smaller lag of order 0.001-0.003.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Enter into top textbox 0.003 (feel free to vary to repro on your own system) for short delay.  See how print finishes long before UI finishes.

To see it fast again, just change n_elements=1 or something small.

```
import gradio as gr
import time


def bot(msg, history):
    history = [[None, None]]
    history[-1][0] = "Tell a very long kid's story about birds"
    response = ' Once upon a time, in a land far, far away, there was a magical kingdom filled with all sorts of birds. Here, the birds were not just ordinary birds, but rather magical creatures with special powers and abilities.\nIn this kingdom, there lived a little bird named Chirpy, who was known for his beautiful singing voice. Chirpy loved to sing and would sing all day long, entertaining'
    response += response + response
    response += response + response
    response += response + response
    response_words = response.split(' ')
    history[-1][1] = ""
    t0 = time.time()
    for word in response_words:
        history[-1][1] += word + ' '
        time.sleep(float(msg))
        yield msg, history
        print('%s %s' % (time.time() - t0, history), flush=True)


with gr.Blocks() as demo:
    chatbot = gr.Chatbot(
        [],
    )
    msg = gr.Textbox()
    clear = gr.ClearButton([msg, chatbot])
    msg.submit(bot, [msg, chatbot], [msg, chatbot])

    n_elements = 300
    for i in range(n_elements):
        msg2 = gr.Textbox()
        butn2 = gr.Button()


demo.queue()
if __name__ == "__main__":
    demo.launch()
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/2249614/4653df12-281e-4dee-bfa9-4a2ac5edcc7d)

### System Info

```shell
gradio==3.47.1
gradio_client==0.6.0
```

Other notes:  I notice chrome uses 100% of a core during this time.  But none of the other elements are slow.

### Severity

I cannot work around it, but it is only a blocker for a very good UX of streaming.

**Comment by abidlabs** [comment]
Thanks @pseudotensor we'll take a look into this

**Comment by pseudotensor** [comment]
I looked at this again since I'm back on gradio 3 and this is one of the few flaws with gradio 3.  I see same effect of slowness in firefox and chrome, so it's not that.

When streaming is occurring, in chrome dev tools mode, I see it's using the media streaming url to some streaming endpoint.    Seems ok.

However, this has nothing to do with a back end problem.  While streaming in UI after backend is long done, I can kill the backend and the UI continues to the end.  So it's all buffered on the UI side.

I also isolated more what causes it.  No particular type of element seems to cause it, but I have many tabs and elements, and in particular it *only* gets slow once I go to the other tabs and the other elements are first rendered.  If I only sit at the "chat" tab it stays fast, but as soon as I go to my "expert" tab (and click nothing) and go back to chat tab, things are slow.

The expert tab has some stuff, but it's not crazy:

![image](https://github.com/gradio-app/gradio/assets/2249614/22880e9a-71b0-470a-9e31-f2a2ac5a2e54)

**Comment by pseudotensor** [comment]
Any update?  I gave full repro.

**Comment by pseudotensor** [comment]
@abidlabs any update?

**Comment by abidlabs** [comment]
No updates yet, but @aliabid94 will be looking into performance and this issue more specifically soon.

**Comment by pseudotensor** [comment]
@abidlabs Thanks.  I'm looking forward to being able to try/use gradio 4 again.  Stuck on 3.

**Comment by pseudotensor** [comment]
Any update?

**Comment by aliabid94** [comment]
Ah yes this should be fixed! Should've been tagged in PR 7084.

**Comment by aliabid94** [comment]
PR #7084 (which is in the latest pip) will stop the freezing, while #7084 (still open) should improve overall performance too

**Comment by aliabid94** [comment]
I'm going to close this for now as performance should be pretty reasonable rn, though when @pngwn makes the UI re-render improvements, we should see further improvements
