### ISSUE TITLE
Invalid Notebook error in most of the run.ipynb files in gradio/demo/<any_folder> in GitHub

### ISSUE THREAD

**Issue by Archit-Kohli** [gradio-app/gradio#5916]
### Describe the bug

None of the notebooks named run.ipynb in any of the demos are visible in GitHub, this is because of an error in the cell id's that are not strings. There is a simple fix to make all the cell id's a string and that makes them visible.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Open any of the run.ipynb files in any folder in gradio/demo/ from GitHub, it will show an Invalid notebook error

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/118905854/b907a084-69a6-4ee8-a69e-c2b4b162ee6f)

### System Info

```shell
I am just running it in the GitHub website on
Chrome Browser Version 117.0.5938.152 (Official Build) (64-bit)
```

### Severity

I can work around it

**Comment by THEGAMECHANGER416** [comment]
I would like to work on this issue

**Comment by Archit-Kohli** [comment]
It is an easy fix, I would also like to work on it with @THEGAMECHANGER416. @pngwn please assign this issue to us both if possible

**Comment by pngwn** [comment]
Feel free to take it. We don't need to assign.

**Comment by Archit-Kohli** [comment]
on it 🫡
