### ISSUE TITLE
built multiple endpoints on gradio mounted on fast api but documentation not showing it

### ISSUE THREAD

**Issue by cowanAI** [gradio-app/gradio#5920]
### Describe the bug

built multiple endpoints on gradio mounted on fast api but documentation not showing it. I'm curious to see if I did something wrong, really tried to search all documentation but could not find anything about it.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Simply create 2 endpoints on top of gradio/fast api only one will show

### System Info

```shell
latest
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @cowanAI could you please provide a complete example we can use to reproduce? And show the output you are seeing vs what you expect to see?

**Comment by cowanAI** [comment]
hello @abidlabs , as always quite appreciate your help in everything, just a 10 seconds questions, is gradio capable of accepting callbacks via fastapi endpoints? that is my current main issue, if I need to wait it's ok, just wanted to verify this information. THANKS!

**Comment by abidlabs** [comment]
Hi @cowanAI I'm not sure what you mean by accepting callbacks via fastapi endpoints. Can you give a code example of what you are trying to do? For general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
