### ISSUE TITLE
gr.Chatbot component download conversation screenshot

### ISSUE THREAD

**Issue by cceyda** [gradio-app/gradio#5923]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
it is hard to share chat history now if it is more than one page.

**Describe the solution you'd like**  
button that would download a screenshot of the whole convo.

**Comment by congchan** [comment]
Hi, may I suggest to support **copy** the whole conversation history as well?

**Comment by freddyaboulton** [comment]
Hi all! Copying the entire history is possible via `show_copy_all_button` but the conversation may only contain text iirc. 

Downloading the conversation can be implemented in gr.Blocks. You can pass the chatbot component value into a function that saves it to disk and then returns that to a gr.DownloadButton component.
