### ISSUE TITLE
SelectData index [None, None] when using image.select event handler with interactive False 

### ISSUE THREAD

**Issue by jreg-mrl** [gradio-app/gradio#5945]
### Describe the bug

I've been using the gradio Image component to display a Pillow image (type="pil"). I then manually handle user clicks to draw shapes on the image using the Pillow ImageDraw.Draw method, before then updating the image in gradio. I realise there are sketch/canvas options for Image but this felt more flexible for my use case.

Since updating to a newer version of gradio, this is no longer possible without making the Image interactive, which adds buttons for edit and clear that I don't need.

The issue is with the SelectData event having _data.index as [None, None] instead of the actual clicked location, as shown in the reproduction.

I realise it's only a minor issue that I should be able to workaround, but thought I'd let you know as it's a deprecation from previous functionality as far as I can tell.

Thanks for all your work on the library, it's a really straightforward and useful project!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

With python 3.10 and gradio 3.48.0, the following should print _dict.index as [None, None].

```import gradio as gr
from PIL import Image
import urllib.request


def input_handler(evt: gr.SelectData):
    print(evt.__dict__)


with gr.Blocks(title="Demo App") as demo:
    urllib.request.urlretrieve(
        "https://gradio-image-classification.hf.space/file=/home/user/app/cheetah.jpg",
        "cheetah_temp.jpg",
    )

    with Image.open("cheetah_temp.jpg") as img:
        image = gr.Image(img, type="pil")

        image.select(input_handler)


if __name__ == "__main__":
    demo.launch()
```

If you change `image = gr.Image(img, type="pil")` to `image = gr.Image(img, type="pil", interactive=True)`, the clicked pixel location in the image will be shown instead.

Finally, if you instead use gradio 3.38.0, both versions should show the pixel location correctly.

### System Info

```shell
Windows 10
Python 3.10
Gradio 3.38.0 (Working) / Gradio 3.48.0 (Not Working)
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @jreg-mrl for letting us know about this regression. We'll take a look!

**Comment by sanbuphy** [comment]
> . We'll take a look!

I meet the same question on gradio 3.48.0

**Comment by jjshoots** [comment]
Facing this same issue as well, subscribed for future updates.

**Comment by olyashok** [comment]
same issue here

**Comment by Shengguang-Zhou** [comment]
Have this been solved? Or should we downgrade to lower version temporary?

**Comment by olyashok** [comment]
No it was not solved.

Kind regards
Alex
________________________________

**Comment by jreg-mrl** [comment]
Thanks for sorting this, works great again now :)

**Comment by thomascatlee** [comment]
gradio 4.44.0 has the same problem, if Image is input，
![image](https://github.com/user-attachments/assets/469a76fd-3531-4cb2-9e15-11e8e778db5e)

then the select event didn't work; 
and set interactive=False, the select event come back.
![image](https://github.com/user-attachments/assets/e2ce1609-9de8-4ae8-9160-c146e2edddf0)
