### ISSUE TITLE
How to make gr.Video take a video from directory directly

### ISSUE THREAD

**Issue by FurkanGozukara** [gradio-app/gradio#5951]
I am using https://github.com/williamyang1991/Rerender_A_Video/tree/main/webUI.py

It uses below code to get video. This is not an issue when you run the app locally but when you run it on a remote server like RunPod it is an huge issue

The code has so many dependencies to  input_path = gr.Video so i couldn't make it take file path

Somehow can we give optionally path of a file instead of selecting it?

```
       input_path = gr.Video(label='Input Video',
                                  source='upload',
                                  format='mp4',
                                  visible=True)
```

![image](https://github.com/gradio-app/gradio/assets/19240467/90dbb83d-c42c-4113-b4fa-b063df7fd814)

give file path in below selection

![image](https://github.com/gradio-app/gradio/assets/19240467/779617c5-bd36-455c-9ae3-04ebd43ac1c0)

**Comment by abidlabs** [comment]
I don't understand the issue -- when you click on the Video upload area, you get to select a video filepath. What are you trying to do that this does not suffice?

**Comment by FurkanGozukara** [comment]
> I don't understand the issue -- when you click on the Video upload area, you get to select a video filepath. What are you trying to do that this does not suffice?

Hello. On RunPod we can't select the video. RunPod is like AWS. 

So we need to give file path instead of selecting it from local computer

**Comment by abidlabs** [comment]
I see -- so the Gradio app is running on Runpod, and the video assets are stored on Runpod itself as well?

**Comment by FurkanGozukara** [comment]
> I see -- so the Gradio app is running on Runpod, and the video assets are stored on Runpod itself as well?

yes

Because upload through gradio share is being too slow

**Comment by abidlabs** [comment]
Does Runpod have a local filesystem? I wonder if you could use the new `FileExplorer` component for this

**Comment by FurkanGozukara** [comment]
> Does Runpod have a local filesystem? I wonder if you could use the new `FileExplorer` component for this

which is the minimum gradio for that? I tried but it wasnt supported with the app version

we use runpod with jupyter lab working great

such as

/workspace/video1.mp4 -  file path

**Comment by abidlabs** [comment]
I'd suggest upgrading to Gradio 4.0, can you see if that fixes it?

**Comment by FurkanGozukara** [comment]
> I'd suggest upgrading to Gradio 4.0, can you see if that fixes it?

Actually gradio 4.0 just broken one of the working app at the 3.5 last version :)

**Comment by abidlabs** [comment]
Hi @FurkanGozukara did you give this a shot with Gradio 4.0? We're happy to help you migrate your app to Gradio 4.x.

**Comment by abidlabs** [comment]
Closing for now, but please let us know if this error persists into 4.0

**Comment by FurkanGozukara** [comment]
> Hi @FurkanGozukara did you give this a shot with Gradio 4.0? We're happy to help you migrate your app to Gradio 4.x.

thank you so much

i will try. do you have any place where we can ask about latest gradio version?

GPT-4 is usually way way behind

for example today it told me to use gr.Directory and there is no such thing

**Comment by abidlabs** [comment]
This could be interesting: https://twitter.com/nicolas_ouporov/status/1722293094752628986 -- other than our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB).

**Comment by FurkanGozukara** [comment]
> This could be interesting: https://twitter.com/nicolas_ouporov/status/1722293094752628986 -- other than our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB).

thank you so much
