### ISSUE TITLE
Validate timeseries inputs

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#596]
**Is your feature request related to a problem? Please describe.**
When the CSV passed to a TimeSeries input does not match the expected format, no validation is performed and no user feedback is provided.

**Describe the solution you'd like**
We should perform some validation on the CSV when it passed in to ensure it matches the expected format. Currently the TimeSeries component will fail silently but even if it didn't we do not have a mechanism to provided user feedback.

But we can do better than simply reactively validating, we know the expected format ahead of time. We should present this information in the 'file upload' box, so user know what format is expected by the TimeSeries component. This may also be true of other 'data inputs', I'll take a look at those and see where else we can improve the UX.

**Comment by pngwn** [comment]
I think this component needs simplifying a little as well. Would be a good time to do it. 

When I find time I'd like to go through all components and look at validation + error handling. We definitely have a number of blank spots in this regard. Another good one to sync with Victor on, re: redesign.

**Comment by abidlabs** [comment]
Our plan it to deprecate the TimeSeries component in 4.0 (ideally we can do this gracefully substituting in its place the LinePlot component) so this issue can be closed. I'll create a separate issue for the deprecation
