### ISSUE TITLE
Progress bar for ChatInterface/Chatbot

### ISSUE THREAD

**Issue by saksenaapurva** [gradio-app/gradio#5967]
- [ ] I have searched to see if a similar issue already exists.
This issue does not already exist

**Is your feature request related to a problem? Please describe.**  
Currently I am unable to get exact estimates of chatbot response when I use ChatInterface. I tried using gr.Progress, but it looks like the gr.Progress is not integrated with ChatInterface or Chatbots. Can we add this functionality? Currently, I am using ChatInterface.

**Describe the solution you'd like**  
It will be great to have gr.Progress automatically integrated with the ChatInterface

**Comment by saksenaapurva** [comment]
Hi @abidlabs @aliabd , wondering if there is a way I can solve this issue? Any help is appreciated. Thanks so much!

**Comment by abidlabs** [comment]
Hi @saksenaapurva what code did you try? Can you share a snippet so that we can reproduce this?

**Comment by abidlabs** [comment]
Closing for lack of follow up

**Comment by saksenaapurva** [comment]
Hi @abidlabs , here is a screenshot of what I mean. The progress timer does not correctly indicate how long the operation should take
<img width="267" alt="Screenshot 2024-01-22 at 2 12 21 PM" src="https://github.com/gradio-app/gradio/assets/20067580/61b9a9fb-a58f-403a-9678-61517fae17da">
<img width="1589" alt="Screenshot 2024-01-22 at 2 21 06 PM" src="https://github.com/gradio-app/gradio/assets/20067580/36c87c56-0218-40a4-a38b-002dd3f18b85">
