### ISSUE TITLE
Gallery full images are not shown correctly on Firefox

### ISSUE THREAD

**Issue by AndrewMead10** [gradio-app/gradio#5971]
### Describe the bug

When selecting an image from a gallery, the image is not centered, and the other images behind it are not hidden either, as seen on the demo galleries in the documentation.
![Selection_001](https://github.com/gradio-app/gradio/assets/55472544/4642ec5e-28e0-47de-b8e2-ad2d159871d1)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Both exmaples on the doc page for gallery https://www.gradio.app/docs/gallery

### System Info

```shell
latest version/ version on the website
```

### Severity

I can work around it

**Comment by AndrewMead10** [comment]
Ubuntu 22 and firefox

**Comment by kkuczkowska** [comment]
I have a similar problem working on Ubuntu 22 and Firefox. With my demo working locally, preview of gallery picture is small and on the left, not centered, as shown on screenshot below.
![image](https://github.com/gradio-app/gradio/assets/23055693/97228137-65c3-4e0d-aec7-870ad4d9de41)

When sharing my demo (still running from my local Ubuntu), I had a client running it on Windows using Opera and preview was working correctly - meaning the previewed image was big and centered, as shown below.

![image](https://github.com/gradio-app/gradio/assets/23055693/46384715-a13d-40c4-acf0-964cbdc3f9dc)

**Comment by Harryoung** [comment]
I meet the same problem on windows! Is  there a solution? 🥲

**Comment by pink-red** [comment]
> ### Reproduction
> 
> Both exmaples on the doc page for gallery https://www.gradio.app/docs/gallery

I have the same problem on Arch Linux in Firefox 121.0.1, both with latest version of Gradio installed locally and with the doc page.

> ### Severity
> 
> I can work around it

@AndrewMead10, could you please share the workaround?

**Comment by pink-red** [comment]
In fact, 3.48.0 is the last version without the bug. In 4.0.0 the bug is present.

**Comment by AndrewMead10** [comment]
> @AndrewMead10, could you please share the workaround?

I just ended up using windows, no easy fix i could find for linux

**Comment by pink-red** [comment]
Found a simple workaround:

```python
with gr.Blocks(css=".preview { width: 100%; }") as demo:
    ...
```
