### ISSUE TITLE
Stuck in processing forever when using queue()

### ISSUE THREAD

**Issue by jamie0725** [gradio-app/gradio#5974]
### Describe the bug

I have a demo that segments an image with a large model, and for some reason, I have to run it on CPU, making the generation lasts > 60s.

I know I need to use .queue() to keep the connection alive in this situation. But, after enabling the queue, the progress bar is stuck in "processing" forever, even after my function already returns the generated image (as shown in the image below).

<img width="1552" alt="image" src="https://github.com/gradio-app/gradio/assets/27820994/b304729a-95a9-4450-a825-a9981ed330f0">

Can anyone help me fix the problem I encountered, thanks!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

My code is as below, I use fastapi to serve the demo:

```python
def model_segment_image(np_image, mask_history):
    LogUtil.info("model image segmentation: {}".format(np_image.shape))
    time.sleep(120) # <- minimum reproducible code, as long as it takes longer than 60s to return
    segment_img_path = "some image.png"
    return segment_img_path, mask_history

def get_blocks():
    with gr.Blocks() as demo:
        with gr.Tab():
            with gr.Row():
                mask_history = gr.State([])
                segment_img_input = gr.Image(label="Source Image").style(height=500)
                segment_img_output = gr.Image(label="Segmented Image").style(height=500)
            segment_button = gr.Button("Segment")
            segment_button.click(
                model_segment_image,
                inputs=[segment_img_input, mask_history],
                outputs=[segment_img_output, mask_history],
                queue=True,
            )
    demo.queue()
    return demo

app = FastAPI()
app.include_router(whoami_router.router)
app = gr.mount_gradio_app(app, image_io, path="/v1/image")
```

### Screenshot

<img width="1428" alt="image" src="https://github.com/gradio-app/gradio/assets/27820994/83c7d8d4-cddc-4dcf-ba0c-1e2602062406">

As can be seen from the container log above, for some reason the reset API is invoked immediately after 60s despite that the queue is enabled.

### System Info

```shell
Google GKE Container
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Is this using the latest version of `gradio`?

**Comment by jamie0725** [comment]
> Is this using the latest version of `gradio`?

we use the gradio version `3.34.0`

**Comment by jamie0725** [comment]
> Could you try upgrading to 3.49?

Sure, I will try now.

**Comment by fivelittlec** [comment]
@abidlabs However, when we try to upgrade gradio version to 3.49, we encounter Pandas dependency problem that `Pandas requires version '3.1.2' or newer of 'jinja2'.` The version of jinja2 we currently installed is 3.0.1, if we upgrade to 3.1.2, we would face another error that `module 'jinja2' has no attribute 'contextfunction'`. Can you give us some advices? Thank you!

**Comment by freddyaboulton** [comment]
What version of pandas do you have installed? I have 1.5.2 and everything is working for me.

**Comment by jamie0725** [comment]
Seems like updating gradio solves the problem, so I'm closing the issue for now, thanks~
