### ISSUE TITLE
video and subtitle error

### ISSUE THREAD

**Issue by RichardQin1** [gradio-app/gradio#5977]
I am a beginner in Python.

Use gradio implement video player.

i have my video file and srt file.
```python
    video = "myvideo.mp4"
    sub = "videosub.srt"
    gr.Video(value=video, valabel="Video") #is ok
    tup1 = (video, sub)
    gr.Video(value=tup1, valabel="Video") #Expected type 'str | None', got 'tuple[str, str]' instead 
```

i dont understand Parameters indicate：
value: A path or URL for the default value that Video component is going to take. Can also be a tuple consisting of (video filepath, subtitle filepath). If a subtitle file is provided, it should be of type .srt or .vtt. Or can be callable, in which case the function will be called whenever the app loads to set the initial value of the component.

value: str
        | Path
        | tuple[str | Path, str | Path | None]
        | Callable
        | None = None,
        *,

why not？
help me , thanks

**Comment by RichardQin1** [comment]
python version = Python 3.11.5
gradio= 3.47.1

**Comment by abidlabs** [comment]
Hi @RichardQin1 I don't understand the question here. Can you please explain what you are asking in more detail?

**Comment by abidlabs** [comment]
Closing for now, we could reopen once we have more details.
