### ISSUE TITLE
ensure example snapshot the component props + pass them to components

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#5991]
### Describe the bug

Two things are true

- certain examples only make sense with certain props
- component props can change at anytime

to make sure stuff doesn't get funky we need to snapshot the component props at initialisation when generating examples. we also need to pass those props into the component to make sure the component is in the correct state to render that particular set of examples.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

its up there

### System Info

```shell
all systems
```

### Severity

I can work around it

**Comment by pngwn** [comment]
there are more than two true things, but the above two things are also true

**Comment by abidlabs** [comment]
This has been fixed by #6014, thanks @pngwn
