### ISSUE TITLE
certain input does not show up correctly

### ISSUE THREAD

**Issue by shelper** [gradio-app/gradio#5994]
### Describe the bug

when specifying inputs for gradio interface, some input does not show up as expected.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

I am using python 3.10.10, on windows 10, with gradio 3.50.0

```python
# this one works fine
import gradio as gr

def func(num, text):
    return f"{num} {text}"

interface = gr.Interface(
    fn=func,
    inputs=[
        gr.inputs.Number(),
        "text",
    ],
    outputs="text",
)

interface.launch(share=False)
```

now if i remove text argument, then the num input  is also gone
```python
# this one no number input
import gradio as gr

def func(num):
    return f"{num}"

interface = gr.Interface(
    fn=func,
    inputs=[
        gr.inputs.Number(),
    ],
    outputs="text",
)

interface.launch(share=False)
```

but if i use "number" instead of `gr.inputs.Number(), then it works again
```python
# this one number input shows up correctly
import gradio as gr

def func(num):
    return f"{num}"

interface = gr.Interface(
    fn=func,
    inputs=[
        "number"
    ],
    outputs="text",
)

interface.launch(share=False)
```

### System Info

```shell
python 3.10.10, on windows 10, with gradio 3.50.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @shelper the `gr.inputs` syntax is deprecated. Please use `gr.Number` instead.
