### ISSUE TITLE
Check package version

### ISSUE THREAD

**Issue by badbye** [gradio-app/gradio#6]
The latest version is 0.7.8, however https://gradio.app/api/pkg-version returns 0.5.0.
BTW, for some reason, the link is unstable to access from China. 
So I suggest using a more stable API, or not even check the version if it is not updated in time automatically.

**Comment by dawoodkhan82** [comment]
Commented out the PKG version check for now.

**Comment by soumya997** [comment]
@dawoodkhan82 How to check the version of gradio?
I used 
```
import gradio as gr
print(gr.__version__)
```
and its giving me this error,what to do?
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-26174f9c9e3b> in <module>()
      1 
      2 
----> 3 print(gr.__version__)

AttributeError: module 'gradio' has no attribute '__version__'
```

**Comment by dawoodkhan82** [comment]
fixed with the latest commit
