### ISSUE TITLE
Output image not in full size

### ISSUE THREAD

**Issue by samarth70** [gradio-app/gradio#60]
Trying to resize the image of the output . But can't figure it out.

**Comment by AK391** [comment]
@MultiPath do you mean resizing the output image component, you can try doing that with css in the interface https://gradio.app/docs#interface

**Comment by hpeiyan** [comment]
> 

hi, there. how about more than two ouputs in gradio. I found it's faild in the ouputs which contains text and image.

**Comment by MichaelSNelson** [comment]
Thanks @hpeiyan, that is probably why it was failing to make any changes for me as well. I had only tried with a dual image+text output so I had not caught that it was broken for such outputs.

**Comment by abidlabs** [comment]
@hpeiyan @MichaelSNelson can you please share an example with code of what's not working for you? We need more information to be able to address this

**Comment by MichaelSNelson** [comment]
Thanks for the response, I am only just starting to play with DL and all the rest, so it is entirely possible I misunderstood something in the link above.
https://huggingface.co/spaces/imagescientist/zebrafishtest1/tree/main
My app.py is included there - are you able to access it to see the code?

Changing the figsize in matplotlib also did not seem to impact the final image size. It may be that the better option is to create three separate images and attempt to place them in the right order in the interface?

**Comment by abidlabs** [comment]
If you have 3 output images, perhaps you could try using the `Gallery` component, which accepts a list of images? https://gradio.app/docs/#gallery
