### ISSUE TITLE
The file name and suffix cannot be specified when downloading the output of an audio component after processing.

### ISSUE THREAD

**Issue by Isuxiz** [gradio-app/gradio#6006]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
The file name and extension name cannot be specified when downloading the output of an audio component after processing. It will always use `audio` as file name (without extension name suffix).

**Describe the solution you'd like**  
Give developer a way to set filename, or provide configuration items to change the default behavior of users clicking the download button, opening a dialog box to determine the name of downloaded wav file.
Furthermore, it would be great if a universal and easy-to-use `DownloadButton` component could be provided.

**Additional context**  
None.

**Comment by abidlabs** [comment]
We now support this using the `format` parameter in `gr.Audio`!
