### ISSUE TITLE
Playground shows really messy error while you edit

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#6024]
### Describe the bug

If in the process of editing a demo in the playground, the demo is not valid python code, you get a really ugly stacktrace and error in the demo.

Maybe we should add a "save" to the playground and/or clean up the error on the gradio-lite side

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

<img width="1582" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/a5f386e6-2e54-4063-b5b4-f93b4dc82301">

### System Info

```shell
latest
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Not sure when but it looks like this was fixed!

<img width="1307" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/1d4cd072-8ef8-4903-ac52-118d13555237">

cc @whitphx @aliabd
