### ISSUE TITLE
[Docs] Anchor Links don't work on Chrome/Safari

### ISSUE THREAD

**Issue by radames** [gradio-app/gradio#6029]
### Describe the bug

Links to Gradio docs with anchors do not scroll to the desired location upon initial loading. A second refresh is necessary for the anchor name to load properly and the window to scroll to the correct anchor.

Example:
https://www.gradio.app/guides/sharing-your-app#accessing-the-network-request-directly

https://github.com/gradio-app/gradio/assets/102277/9566385f-d2b3-42a2-bd63-119d78b15244

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Click on this link and watch if the page takes you the anchor (Chrome/Safari) it works on Firefox 🤔

https://www.gradio.app/guides/sharing-your-app#accessing-the-network-request-directly

### System Info

```shell
Chrome/Safari
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Should be fixed now!
