### ISSUE TITLE
Add `--share` option to Gradio cli

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#6030]
- [x] I have searched to see if a similar issue already exists.

Currently, we need to edit `app.py` to launch it with a share link, but it would be nice to have an option to easily launch Gradio app with a share link, like `gradio app.py --share`.

We discussed this internally. ([Slack](https://huggingface.slack.com/archives/C02QZLG8GMN/p1697741774938339?thread_ts=1697649917.447829&cid=C02QZLG8GMN))

**Comment by freddyaboulton** [comment]
Hi @hysts - I think we shouldn't increase the API footprint of the CLI further. You can use `GRADIO_SHARE` environment variable if you don't want to modify the source code.
