### ISSUE TITLE
Gradio ChatBot component capitalizes each new word  

### ISSUE THREAD

**Issue by Alssndr0** [gradio-app/gradio#6035]
### Describe the bug

All of a sudden I see all my words capitalized in the gr.chatbot component, both when I submit the question and when I receive an answer. 
I am working with the latest Gradio version.  
Has anyone experienced the same issue? 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```  # update the chat interface before generating the answer
    def update_chat(self, user_message, history):
        return "", history + [[user_message, None]]
```

That is how I am updating my interface. 

### System Info

```shell
gradio 3.50.2
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @Alssndr0 I can't reproduce this locally or on the [Gradio Playground](https://www.gradio.app/playground). You can try running the Chatbot demos at the bottom of the Playground: https://www.gradio.app/playground -- they work fine for me.

**Comment by Alssndr0** [comment]
This is very odd, because in the Gradio Playground that code works, but in my browser(s) this is the behavior I am getting:
![image](https://github.com/gradio-app/gradio/assets/74568322/993c95d6-a4e6-41e7-90ea-68131ecac666)

**Comment by Alssndr0** [comment]
Found the issue, it was my CSS, sorry and thanks for your help!
