### ISSUE TITLE
gradio discord link is invalid. please update it.

### ISSUE THREAD

**Issue by pandya6988** [gradio-app/gradio#604]
page: https://www.gradio.app/docs/#o_image

**Comment by abidlabs** [comment]
Thanks @pandya6988, confirming that the link https://discord.gg/Vuujh8wt no longer works in the navbar. @aliabd can we update with a permanent link?

**Comment by aliabd** [comment]
Added the correct link to the website, which is [this one](https://discord.gg/feTf9x3ZSB), but it might take a bit to reload. Thanks @pandya6988
