### ISSUE TITLE
Chatbot Message box doesn't automatically expand when I paste in multi-line text

### ISSUE THREAD

**Issue by vgoklani** [gradio-app/gradio#6047]
### Describe the bug

Go to this URL:

    https://www.gradio.app/guides/creating-a-chatbot-fast

Paste in multi-line text into textbox:

    For years, as NASA struggled to build the designated successor to the Hubble Space Telescope, I came to think of the Webb as a problem child, ever-delayed, swallowing dollars that could have gone to other telescopes and space missions.

    The telescope was not named for some sky-breaking astronomer. Rather it carried the name of a bureaucrat, the former NASA Administrator James Webb, who oversaw the Apollo program to land on the Moon but also tolerated the purging of gay and lesbian people when he was a high official at the State Department. It was an infrared telescope, which would give astrophysicists a new angle on what was going on out there, but I didn’t think it could have the impact Hubble had.

The text-box does NOT expand, which makes it very difficult to use.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Please see above

### System Info

```shell
Running in Chrome
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @vgoklani the `gr.ChatInterface` intentionally has an opinionated UI/UX, including the fact that the input textbox is only a single line. 

If you wanted, you could pass in your own textbox to customize the UI. Here's an example that might work better for you.

```py
import gradio as gr

def echo(message, history):
    return message

gr.ChatInterface(echo, submit_btn=None, textbox=gr.Textbox(lines=4)).launch()
```

If you need even more customization, I'd recommend building a Chatbot UI out of `gr.Blocks` as described here: https://www.gradio.app/guides/creating-a-custom-chatbot-with-blocks
