### ISSUE TITLE
Add timeout functionality to `gradio_client.Client`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#6049]
- [x] I have searched to see if a similar issue already exists.

When calling an API of a Space via `gradio_client`, it could take quite long to get the result, so I think it would be nice to be able to set timeout.
For example, the response will be slow in the following cases:
- The Space is being built.
- The queue is too long.
- The Space is in a broken state and stuck, though it's not down.

**Comment by abidlabs** [comment]
Hi @hysts, just to clarify, are you talking about a timeout when you first create a `Client` object, or do you mean when you submit a prediction?

**Comment by hysts** [comment]
Sorry, I wasn't clear. Actually, I was thinking of both. I think the first point is about creating a `Client` object and the rest two are about calling `.predict`.

Regarding the first point, it could take up to 30 minutes to build a Space, so it would be nice to be able to set timeout for creating a `Client` object too.
https://github.com/gradio-app/gradio/blob/8241f9a7bd034256aabb9efa9acb9e36216557ac/client/python/gradio_client/client.py#L109-L114



For more context, I was fixing [this Space](https://huggingface.co/spaces/merve/comparing-captioning-models), and it was creating a `Client` object every time it tried to call it:
```python
def generate_caption_instructblip(image):
    client = Client('RamAnanth1/InstructBLIP')
    result = client.predict(image, 'Describe the image', 1, #min length
                   250, #max length
                   5, #beam size 
                   1, #length penalty
                   1, #rep penalty
                   0.9, #top p
                   'Beam search', fn_index=1)
    return result
```
I think the author of this Space did this because the Spaces it's calling might be down or in sleep when this Space is started, but they could be back up again when users run this Space.

Maybe it would be useful to be able to create a `Client` object in a lazy manner.

**Comment by MohamedAliRashad** [comment]
@abidlabs I keep getting different errors with `httpx` because of timing out

**Comment by kyrylogy** [comment]
> @abidlabs I keep getting different errors with `httpx` because of timing out

dd you manage to solve it?

**Comment by djaym7** [comment]
+1 on this
