### ISSUE TITLE
The `max_lines` parameter in `gr.Textbox` does not work if `container=False`

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#6056]
### Describe the bug

A strange error, but I was building a demo when I noticed that the `max_lines` parameter has no effect if `container=False` in `gr.Textbox()`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```py
with gr.Blocks() as demo:
    gr.Textbox(max_lines=4, container=False)
    
demo.launch()
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 3.50.2
gradio_client version: 0.6.1
```

### Severity

I can work around it

**Comment by yvrjsharma** [comment]
Thanks @abidlabs for creating this issue.
I have also observed that the Textbox behaves differently when the container parameter is set to True or False. When set to 'True', the Textbox expands as more lines of text are entered into it. However, when set to 'False', the number of lines becomes fixed and the user has to scroll through the content to read everything.

**Comment by abidlabs** [comment]
Just to confirm, I think we're saying the same thing -- `max_lines` becomes set to the number of `lines` when `container=False`.
