### ISSUE TITLE
Timeout Error after 40 seconds

### ISSUE THREAD

**Issue by patricklenert** [gradio-app/gradio#6057]
### Describe the bug

Hello,

My ML Model (GPT 4 API) takes a long time to process a chat question **and I always get a timeout error after exactly 40 seconds**. After reading the documentation I thought this is exactly why "queue()" exists, but for me it has no effect.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
def chatbot(input_text, *args, **kwargs):
    storage_context = StorageContext.from_defaults(persist_dir="storage")
    index = load_index_from_storage(storage_context, index_id="index")
    query_engine = index.as_query_engine(response_mode="compact")
    response = query_engine.query(input_text + " (Also give me an example), make the answer extremely detailed")
    yield response.response

interface = gr.ChatInterface(
    chatbot,
    chatbot=gr.Chatbot(height=600),
    textbox=gr.Textbox(placeholder="Ask a question", container=False, scale=7),
    theme="default",
    cache_examples=False,
    retry_btn=None,
    submit_btn=None,
    undo_btn=None,
    clear_btn=None,
)

interface.queue()
interface.launch(enable_queue=True)
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/1641188/61b40631-fc0a-448b-9454-cd524f9f1f92)

### System Info

```shell
Python 3.9
Gradio 3.50.1
Windows 10


fsspec: 2023.9.2
httpx: 0.25.0
huggingface-hub: 0.18.0
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @patricklenert can you tell us a bit more about the environment you are running Gradio on? Is it a regular Python terminal, a jupyter notebook, a remote server, or something else?

**Comment by patricklenert** [comment]
@abidlabs Yes, a regular python terminal in Pycharm on Windows 10. I think its no issue with uvicorn because uvicorn usually times out after 60 seconds but here the gradio error modal comes after exactly 40 seconds. For short questions I get the answer displayed as expected.

**Comment by patricklenert** [comment]
@abidlabs Also, if you have a blog post about how I deploy a gradio app to streamlit, then please share it with me :) 
If I do .launch(share=True) I always get an error message, on Mac and Windows.

**Comment by abidlabs** [comment]
Hi @patricklenert can you see if this is still an issue in the latest version of `gradio` (4.0.2)?

**Comment by abidlabs** [comment]
Closing for lack of followup

**Comment by oliverangelil** [comment]
@patricklenert did you resolve this issue? Am experiencing the same...

**Comment by freddyaboulton** [comment]
Can you share a minimal reproducer using the latest gradio version? Maybe it's related to a gradio networking dependency like httpx or starlette so doing a fresh install might fix the problem.

**Comment by vincent-aduuna** [comment]
Hi @freddyaboulton following up on @oliverangelil. 

I have been able to reproduce in this simpleified app below. The call to stream LLM response chunks has been replaced with a simulated `time.sleep(1)`.



fastapi entrypoint `main.py`
```python
from fastapi import FastAPI
import gradio as gr

# All other imports and complex logic hidden for reproducer

# Simple reproducer app
from gradio_app import app as simulated_gradio_app

app = FastAPI()

@app.get("/")
async def root():
    return {"message": "Gradio Hanging Reproducer API"}

app = gr.mount_gradio_app(app, simulated_gradio_app, path="/chat")
```

gradio_app.py
```python
import time
import io

import gradio as gr
# from agents.ai_agent.langchain_orchestrator import create_essay_orchestrator
from PIL import Image

# Create the multi-agent orchestrator
# orchestrator = create_essay_orchestrator()


def chat_with_graph(message, history):
    """Process essay writing requests through the multi-agent system."""
    # initial_state = orchestrator.create_initial_state(message)
    response = ""
    final_state = None

    for chunk in range(65):
        time.sleep(1)  # Simulate processing delay
        agent, state = "str", {} 
        final_state = {"final_essay": f"Final essay part {chunk}"}

        # Stream messages from the state, this does nothing for now
        messages = state.get("messages", [])
        if messages:
            latest_message = messages[-1]
            if isinstance(latest_message, dict):
                content = latest_message.get("content", "")
                response += f"**{agent.upper()}:** {content}\n\n"
                yield response

    # Add final essay when complete
    if final_state:
        final_essay = final_state.get("final_essay")
        if final_essay:
            response += f"**Final Essay:**\n\n{final_essay}\n"
            yield response


app = gr.ChatInterface(
    chat_with_graph,
    type="messages",
    flagging_mode="manual",
    flagging_options=["Like", "Spam", "Inappropriate", "Other"],
    save_history=True,
)
if __name__ == "__main__":
    demo.launch()

```

requirements.txt
```text
gradio==5.27.1
fastapi[standard]>=0.115.12
uvicorn>=0.34.0
```


Dockerfile
```
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
```

It processes for about ~60 seconds then the interface shows Error `Connection errored out`

[This is the link to the actual files in the repository](https://github.com/Ishangoai/AIMS_course/blob/development/src/students/example/agents/ai_agent/llm_gradio.py)

**Comment by oliverangelil** [comment]
@freddyaboulton if it helps, @vincent-aduuna and I can jump on a call with you to demo the issue
