### ISSUE TITLE
Getting error with image reshaping when trying Gradio for the first time with a deep learning Model. 

### ISSUE THREAD

**Issue by abdoul-Aziz-shara** [gradio-app/gradio#606]
This is actually my first time trying Gradio with an ML model and I have been getting this error: 

**Code:** 
 #create a function to make predictions
#return a dictionary of labels and probabilities
def Normal_or_Pneumonia(img):
    img = img.reshape( -1, 180, 180,3 )
    prediction = model.predict(img).tolist()[0]
    CLASS_NAMES = ["NORMAL", "PNEUMONIA"]
    return {CLASS_NAMES[i]: prediction[i] for i in range(2)}

#set the user uploaded image as the input array
#match same shape as the input shape in the model
im = gradio.inputs.Image(shape=(180, 180), image_mode='L', invert_colors=False, source="upload")
#setup the interface
iface = gr.Interface(
    fn = Normal_or_Pneumonia, 
    inputs = im, 
    outputs = gradio.outputs.Label(),
)
iface.launch(share=True , debug = True)

**Error:** 

File "/usr/local/lib/python3.7/dist-packages/gradio/interface.py", line 487, in run_prediction
    prediction = predict_fn(*processed_input)
  File "<ipython-input-28-0868f9fb3690>", line 4, in Normal_or_Pneumonia
    img = img.reshape( -1, 180, 180,3 )
ValueError: cannot reshape array of size 32400 into shape (180,180,3)

**Comment by abidlabs** [comment]
It looks like the error is that you are using `image_mode='L'`, which loads the image as a black-and-white image. If you remove this parameter, I think it should work.

**Comment by abidlabs** [comment]
Do you mind if we close this @abdoul-Aziz-shara unless you are still running into other issues?

**Comment by abdoul-Aziz-shara** [comment]
Sure, It works.  Thanks, @abidlabs

**Comment by abidlabs** [comment]
Awesome!
