### ISSUE TITLE
Import Gradio Error

### ISSUE THREAD

**Issue by msinankhan** [gradio-app/gradio#6068]
### Describe the bug

While importing gradio, the import fails with the following error:

```
ImportError                               Traceback (most recent call last)
[<ipython-input-34-a0bc40815626>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import gradio as gr
      2 def chat(message, history):
      3     res=qa_with_sources(message)['answer']
      4     return res
      5 gr.ChatInterface(fn=chat).launch()

10 frames
[/usr/local/lib/python3.10/dist-packages/fastapi/exceptions.py](https://localhost:8080/#) in <module>
      4 from starlette.exceptions import HTTPException as StarletteHTTPException
      5 from starlette.exceptions import WebSocketException as StarletteWebSocketException
----> 6 from typing_extensions import Annotated, Doc  # type: ignore [attr-defined]
      7 
      8 

**ImportError: cannot import name 'Doc' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)**

```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio as gr 

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/91521519/2c635f14-1a72-4ec3-80b2-3c7131862224)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 3.50.2
gradio_client version: 0.6.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 4.2.2
fastapi: 0.104.0
ffmpy: 0.3.1
gradio-client==0.6.1 is not installed.
httpx: 0.25.0
huggingface-hub: 0.18.0
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.1
numpy: 1.23.5
orjson: 3.9.9
packaging: 23.2
pandas: 1.5.3
pillow: 9.4.0
pydantic: 1.10.13
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.8.0
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.25.0
huggingface-hub: 0.18.0
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by dattle257** [comment]
same issue

**Comment by henrii1** [comment]
I'm having the exact same issue. i even tried to install typing-extensions==4.6.0 but gradio uninstalled it and installed 4.8.0 and then failed to import because it isn't compactible with 4.8.0

**Comment by hi019** [comment]
Probably caused by this: https://github.com/tiangolo/fastapi/discussions/10476

**Comment by freddyaboulton** [comment]
This is an issue with colab - one of the dependencies that comes with colab (tf-probability) does not allow typing_extensions > 4.6. Looks like it has been fixed but maybe not deployed yet. https://github.com/tensorflow/probability/commit/53c4dc670dae4fc974a5e11f49b17dc0bb659ab0

I would try uninstalling tensorflow-probability, downgrading to fastapi 0.100.0 or restarting the colab kernel and trying again. 

Gonna close since its not a gradio issue and I cannot reproduce as of 2023-11-07!

<img width="1292" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/a5d7a80d-151a-4a57-a9f5-ee22dd24e661">

**Comment by rajindermath** [comment]
Replacing **gr.inputs** with **gr.components** and restarting the 
**Colaboratory** runtime helped me to get rid of the problem.
