### ISSUE TITLE
Input Larger Than ~22Mb Filesize Images Will Not Load on Auto1111 & vladmandic repos

### ISSUE THREAD

**Issue by YourFriendlyNeighborhoodMONKE** [gradio-app/gradio#6081]
### Describe the bug

Larger than roughtly 22 Megabyte filesize PNG image on img2img or inpainting window seems to fail every time

A year old version of Auto1111 fails
Current up to date freshly pulled Auto1111 fails
Current up to date freshly cloned vladmandic fork fails

I have not triangulated the exact file size to determine exact number, but it is somewhere between 22-24Mb
The filesize where images stop loding seems to be very consistent and very exact

This makes me suspect that there is some kind of coded upper filesize limit on Gradio itself

The issue is NOT about image pixel dimensions! - This is easy to prove by heavily compressing large JPG files
(For pixel dimensions there is about 89 Megapixel limit in the Auto1111 code that can be changed by changing the value it calculates to consider it being a potential DOS attack)

The issue seems to be Gradio related rather than Auto1111 and I would like others to try reproduce the issue

I do not get any error messages on the server

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Resize any image, say, larger than 7000x7000 pixels and save to PNG format without compression

You should now have an image with filesize roughly sitting at 25 megabytes if you didn't compress it

Load this image into Gradio application, specifically in my case into Auto1111 img2img or inpainting input window

### System Info

```shell
Running gradio environment gives error:
ERROR:    Error loading ASGI app. Could not import module "environment".


C:\Users\username\miniconda3\lib\site-packages\gradio
version.txt says:
3.35.2
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
My guess is that it's because Images are currently representad as base64. gradio will serve an image file starting in version 4. Hoping that fixes this when Auto1111 upgrades to version 4.

**Comment by YourFriendlyNeighborhoodMONKE** [comment]
> My guess is that it's because Images are currently representad as base64. gradio will serve an image file starting in version 4. Hoping that fixes this when Auto1111 upgrades to version 4.

Interesting...

I'm assuming you meant 3.4

Could someone with both gradio versions verify this?

**Comment by abidlabs** [comment]
Hi @YourFriendlyNeighborhoodMONKE actually @freddyaboulton was referring to Gradio 4.0, which was just released. It solved a similar issue here: https://github.com/gradio-app/gradio/issues/5424, so I'm guessing this is solved as well. 

Would you be able to see if this is still an issue on the latest version of Gradio 4.0.2, and if so, we can reopen this issue.
