### ISSUE TITLE
Streaming Textbox

### ISSUE THREAD

**Issue by zhuofan-16** [gradio-app/gradio#6085]
- [X] I have searched to see if a similar issue already exists.

Will it be possible for us to stream textbox? Sometime, we are doing things like text summarization, we dont need a chatbot ui just need the textbox to show the content. Will be nice if we can stream it.

**Comment by abidlabs** [comment]
Can you explain a bit more what you mean by this @zhuofan-16?

> we dont need a chatbot ui just need the textbox to show the content

What code are you trying right now?

**Comment by zhuofan-16** [comment]
> Can you explain a bit more what you mean by this @zhuofan-16?
> 
> > we dont need a chatbot ui just need the textbox to show the content
> 
> What code are you trying right now?

As in we need to render and stream the llm response in a textbox

![image](https://github.com/gradio-app/gradio/assets/59607914/8419f4c2-90a6-4f1c-a81e-ec4266337164)

^ Something like this

**Comment by zhuofan-16** [comment]
I tried using the yield method but it just seems to output <generator method XXXXXXX > in the output textbox

**Comment by abidlabs** [comment]
Hi @zhuofan-16 yes this is possible. Any Gradio component, including Textbox, works with `yield`. For example:

```py
import time
import gradio as gr

def test(message):
    for i in range(len(message)):
        time.sleep(0.3)
        yield message[: i + 1]

gr.Interface(test, "textbox", "textbox").launch()
```

**Comment by matthiasmfr** [comment]
this should be documented somewhere. for me, it. was not deductible from the current documentation

**Comment by abidlabs** [comment]
Hi @matthiasmfr please see https://www.gradio.app/guides/key-features#streaming-outputs

**Comment by matthiasmfr** [comment]
Yeah but you don’t see that if you’re reading the API docs for the components. You assume everyone reads this “key features” first which is not reasonable imho. Like, the functionality of a specific thing should be mentioned on the api page of the thing and not in the QuickStart. Just my opinion.

**Comment by julien-c** [comment]
i just used this awesome feature btw. Found it quite intuitive TBH!

**Comment by zhjunqin** [comment]
> Hi @zhuofan-16 yes this is possible. Any Gradio component, including Textbox, works with `yield`. For example:
> 
> ```python
> import time
> import gradio as gr
> 
> def test(message):
>     for i in range(len(message)):
>         time.sleep(0.3)
>         yield message[: i + 1]
> 
> gr.Interface(test, "textbox", "textbox").launch()
> ```

how to do this with gr.Textbox?
