### ISSUE TITLE
Emitting Audio events while using a generator

### ISSUE THREAD

**Issue by gorkemgoknar** [gradio-app/gradio#6088]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Gradio can emit audio stop/pause/end events after function call ended, but issue is it cannot emit signals if function is a generator.
This affects streaming examples.

**Describe the solution you'd like**  
When audio is yielded (either bytestream or file) instead of function return, gradio should be able to catch its events 

**Additional context**  
We have a streaming Text to speech example on below space. Here for a workaround for user experience we can send chunks as file (or byte stream fine)
https://huggingface.co/spaces/coqui/xtts-streaming

But on a case with a LLM chatbot (example below), only possible solution I could find waiting audio to complete by calculating its length and sleep.. this is actually wasting resources as if I could get the audio stopped event I can continute on next audio
https://huggingface.co/spaces/coqui/voice-chat-with-mistral

A possible solution I find is using a queue system and background scheduler so LLM can work on background and once first sentence is in generate speeches and append to a linked list (dequeu) , although works fine for first inference, having issues due to OOM as I need to check audio each time using an event (every=5) but again that causes OOM issues after a time

**Comment by gorkemgoknar** [comment]
Solved my problem via setting intractive False, streaming True for Audio , and also directly feeding bytestream.

Solution is reflected on this space: https://huggingface.co/spaces/coqui/voice-chat-with-mistral

```
        audio = gr.Audio(
            value=None,
            label="Generated audio response",
            streaming=True,
            autoplay=True,
            interactive=False,
            show_label=True,
        )
```

**Comment by abidlabs** [comment]
Sounds good, thanks for letting us know @gorkemgoknar! Is this issue good to close?

**Comment by abidlabs** [comment]
Will go ahead and close
