### ISSUE TITLE
Not working with Google Colab

### ISSUE THREAD

**Issue by BenjaminMiddleton** [gradio-app/gradio#6090]
### Describe the bug

It installs but it won't import gradio. This is the error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-42-43eca54f7d45>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import gradio as gr

6 frames
[/usr/local/lib/python3.10/dist-packages/gradio/__init__.py](https://localhost:8080/#) in <module>
      1 import json
      2 
----> 3 import gradio.components as components
      4 import gradio.inputs as inputs
      5 import gradio.outputs as outputs

[/usr/local/lib/python3.10/dist-packages/gradio/components/__init__.py](https://localhost:8080/#) in <module>
----> 1 from gradio.components.annotated_image import AnnotatedImage
      2 from gradio.components.audio import Audio
      3 from gradio.components.bar_plot import BarPlot
      4 from gradio.components.base import (
      5     Column,

[/usr/local/lib/python3.10/dist-packages/gradio/components/annotated_image.py](https://localhost:8080/#) in <module>
      7 
      8 import numpy as np
----> 9 from gradio_client.documentation import document, set_documentation_group
     10 from gradio_client.serializing import JSONSerializable
     11 from PIL import Image as _Image  # using _ to minimize namespace pollution

[/usr/local/lib/python3.10/dist-packages/gradio_client/__init__.py](https://localhost:8080/#) in <module>
----> 1 from gradio_client.client import Client
      2 from gradio_client.utils import __version__
      3 
      4 __all__ = [
      5     "Client",

[/usr/local/lib/python3.10/dist-packages/gradio_client/client.py](https://localhost:8080/#) in <module>
     30 from packaging import version
     31 
---> 32 from gradio_client import serializing, utils
     33 from gradio_client.documentation import document, set_documentation_group
     34 from gradio_client.exceptions import SerializationSetupError

[/usr/local/lib/python3.10/dist-packages/gradio_client/serializing.py](https://localhost:8080/#) in <module>
     10 
     11 from gradio_client import media_data, utils
---> 12 from gradio_client.data_classes import FileData
     13 
     14 with open(Path(__file__).parent / "types.json") as f:

[/usr/local/lib/python3.10/dist-packages/gradio_client/data_classes.py](https://localhost:8080/#) in <module>
      3 from typing import TypedDict
      4 
----> 5 from typing_extensions import NotRequired
      6 
      7 

ImportError: cannot import name 'NotRequired' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```import gradio as gr```

### System Info

```shell
macOS Catalina and Windows 10
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Which version of `gradio` did you install @BenjaminMiddleton? It works for me here: https://colab.research.google.com/drive/10XHiSdbOI3x0OLjJiWyoWWkKHWjdKcB5?usp=sharing

Can you share your Colab notebook?

**Comment by BenjaminMiddleton** [comment]
I have just tried your notebook and the import works but it does still return the following error during install:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires kaleido, which is not installed.
tensorflow-probability 0.22.0 requires typing-extensions<4.6.0, but you have typing-extensions 4.8.0 which is incompatible.

**Comment by BenjaminMiddleton** [comment]
I can share my notebook. I am trying to install gradio at the bottom.

https://colab.research.google.com/drive/1quhqvcGTfwEOz_k8xIYpLqyL_hyIIodc?usp=sharing

**Comment by mcaferulker** [comment]
I've also run into the issue when I tried to import gradio in Colab.

```python
!pip -q install gradio
import gradio as gr
```
```python
ImportError                               Traceback (most recent call last)

[/usr/local/lib/python3.10/dist-packages/fastapi/exceptions.py](https://localhost:8080/#) in <module>
      4 from starlette.exceptions import HTTPException as StarletteHTTPException
      5 from starlette.exceptions import WebSocketException as StarletteWebSocketException
----> 6 from typing_extensions import Annotated, Doc  # type: ignore [attr-defined]
      7 
      8 

ImportError: cannot import name 'Doc' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)
```
So I've tried different verisons of `typing-extensions` and `gradio`. Apparently `gradio v3.50.2` (currently lastest version) is bugged.  Version 3.45.0 worked for me. Maybe your problem is related to its version. You can try `!pip -q install gradio==3.45.0`

**Comment by abidlabs** [comment]
Interesting, we'll look into this. It might get resolved when [we release 4.0 next Tuesday](https://www.youtube.com/watch?v=5MgmKBCOpvU&ab_channel=HuggingFace)

**Comment by freddyaboulton** [comment]
@mcaferulker I think you need to upgrade typing_extensions if you have the latest fastapi version installed

**Comment by mcaferulker** [comment]
@freddyaboulton I thought so, too. I upgraded to the latest version. I also tried a few different versions of `typing-extensions`. It didn't work until I changed the `gradio` version.

**Comment by abidlabs** [comment]
The errors are happening because Colab automatically installs tensorflow-probability which pins to an older version of typing_extensions, while fastapi (and thus gradio) requires a newer version

It looks like tensorflow-probability fixed this a few weeks ago: https://github.com/tensorflow/probability/commit/53c4dc670dae4fc974a5e11f49b17dc0bb659ab0

Colab needs to update their version of the package, which they'll hopefully do soon. In the meantime, I'll close this issue.

**Comment by not-lain** [comment]
i don't know why i just got this error, but for those working in colab try using 
```
!pip install fastapi==0.104.1 typing_extensions==4.8.0 gradio==3.41.0

```
or use the older version 
```
!pip install gradio==3.47.1
```
ok, after careful investigation, it turns out like @abidlabs mentioned, the source of this error is `tensorflow-probability` 
i'm going to leave my solution for those future lurkers out there. 
if you're reading this, happy coding everyone 💚

**Comment by abhigarg** [comment]
> i don't know why i just got this error, but for those working in colab try using
> 
> ```
> !pip install fastapi==0.104.1 typing_extensions==4.8.0 gradio==3.41.0
> ```
> 
> or use the older version
> 
> ```
> !pip install gradio==3.47.1
> ```
> 
> ok, after careful investigation, it turns out like @abidlabs mentioned, the source of this error is `tensorflow-probability` i'm going to leave my solution for those future lurkers out there. if you're reading this, happy coding everyone 💚

The first solution with fastapi and typing_extensions worked for me.  Thanks a lot
