### ISSUE TITLE
The dropdown list does not show the other values when setting the default value

### ISSUE THREAD

**Issue by ForwardForward** [gradio-app/gradio#6103]
### Describe the bug

How can I set a default value in the dropdown list, but still be able to select the other values?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

I have code:

import gradio as gr

my_list = ["World", "Gradio", "World2", "abc ", "You"]

with gr.Blocks() as demo:
    drop1 = gr.Dropdown(choices=my_list, label="simple", value=my_list[0])

demo.launch()

### Screenshot

![2023-10-26_15-48-38](https://github.com/gradio-app/gradio/assets/20382599/1386c264-f4dc-4a5a-b2d5-30f3b91add3e)

### System Info

```shell
Win 11
Gradio                    3.50.2

```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @ForwardForward! Providing a `value` makes a component non-interactive by default, [as described in the docs](https://www.gradio.app/guides/blocks-and-event-listeners#event-listeners-and-interactivity). But you can change this by setting `interactive=True` explicitly, like this:

```py
import gradio as gr

my_list = ["World", "Gradio", "World2", "abc ", "You"]

with gr.Blocks() as demo:
    drop1 = gr.Dropdown(choices=my_list, label="simple", value=my_list[0], interactive=True)

demo.launch()
```
