### ISSUE TITLE
Syntax highlighted input Textbox

### ISSUE THREAD

**Issue by maxrossi** [gradio-app/gradio#6106]
Hello,
I would like to create an input Texbox that highlights text inserted in curly braces, like a HighlightedText component but for user input

Maybe this is already planned for next releases?

**Comment by abidlabs** [comment]
Hi @maxrossi, this isn't something that is planned for release, but we have just released Custom Components in Gradio 4.0 -- meaning that you can take an existing Gradio component and clone it, modify the backend or the frontend, and use it in your Gradio apps. Here's how to get started: https://www.gradio.app/guides/five-minute-guide

This should hopefully help solve this use case!
