### ISSUE TITLE
Broken Emojis

### ISSUE THREAD

**Issue by Muennighoff** [gradio-app/gradio#6109]
### Describe the bug

Since updating to the latest gradio several emojis are broken see https://huggingface.co/spaces/mteb/leaderboard

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Run https://huggingface.co/spaces/mteb/leaderboard

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/62820084/75d750e7-4aaa-430c-bca9-7855c6d9e764)

### System Info

```shell
https://huggingface.co/spaces/mteb/leaderboard/blob/main/requirements.txt
```

### Severity

I can work around it

**Comment by Muennighoff** [comment]
> Hey @Muennighoff! I've just tested this in Firefox on Chrome 118 on Mac and Chrome 119 on Windows 11. Can you confirm if this is still an issue you're seeing?

I fixed it by moving the emojis outside of the bold markers. I.e. `**text**👍👍` works but `**text👍👍**` does not on my side

**Comment by abidlabs** [comment]
It seems like it might be an underlying issue with marked.js, which we use to render Markdown? https://github.com/markedjs/marked/issues/233 

Are we good to close this @Muennighoff?

**Comment by Muennighoff** [comment]
Sure
