### ISSUE TITLE
Auth broken in spaces but not locally

### ISSUE THREAD

**Issue by jamesredd** [gradio-app/gradio#6110]
### Describe the bug

When I run my app locally, it renders as I’d expect, and I’m able to log in via setting the env variable.
![Screen Shot 2023-10-26 at 12 35 30 PM](https://github.com/gradio-app/gradio/assets/9854858/cf086f8e-971b-4f0f-a3a8-45b81a9e62d4)

However, when I upload this exact same code to spaces, it looks like this, and I’m unable to log in:
![Screen Shot 2023-10-26 at 12 36 11 PM](https://github.com/gradio-app/gradio/assets/9854858/9f1fe881-876f-4db8-a6e9-0984d96bac69)

Occurs on both Chrome and Safari.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Simply add auth to launch, and then observe behavior when running locally and on spaces. 

### Screenshot

![Screen Shot 2023-10-26 at 12 36 11 PM](https://github.com/gradio-app/gradio/assets/9854858/47173815-b04f-4e40-af8c-7cd7d4aa7530)

### Logs

```shell
No logs present
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 3.50.2
gradio_client version: 0.6.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.103.2
ffmpy: 0.3.1
gradio-client==0.6.1 is not installed.
httpx: 0.25.0
huggingface-hub: 0.16.4
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.2
numpy: 1.25.2
orjson: 3.9.7
packaging: 23.1
pandas: 2.1.0
pillow: 10.0.0
pydantic: 2.4.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.7.1
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.9.0
httpx: 0.25.0
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

Blocking my use of Gradio

**Comment by dwipper** [comment]
@jamesredd I had the same issue: https://github.com/gradio-app/gradio/issues/5932 . See the URL to load in your Spaces requirements.txt . Unfortunately, it's broken again in 4.0.2....but loading the referenced version should work until they fix it.

**Comment by abidlabs** [comment]
Ah just seeing this. I reopened #5932 so let's use that issue while we investigate
