### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'Interface'

### ISSUE THREAD

**Issue by zxy2020** [gradio-app/gradio#613]
**Describe the bug**
when  I run the "hello world" code  copied by the 'getting  started'  ,  I got this erors.

**To Reproduce**
run the code

> 
> import gradio as gr
> 
> def greet(name):
>     return "Hello " + name + "!!"
> 
> iface = gr.Interface(fn=greet, inputs="text", outputs="text")
> iface.launch() 

**Device information (please complete the following information):**
 - OS: windows10 and Linux
 - Gradio version  2.7.5.2  or  2.6.0

**Additional context**
Package            Version
------------------ ---------
aiohttp            3.8.1
aiosignal          1.2.0
analytics-python   1.4.0
anyio              3.5.0
asgiref            3.5.0
async-timeout      4.0.2
asynctest          0.13.0
attrs              21.4.0
backoff            1.10.0
bcrypt             3.2.0
certifi            2021.10.8
cffi               1.15.0
charset-normalizer 2.0.12
click              8.0.3
cryptography       36.0.1
cycler             0.11.0
fastapi            0.73.0
ffmpy              0.3.0
Flask              2.0.3
Flask-CacheBuster  1.0.0
Flask-Cors         3.0.10
Flask-Login        0.5.0
fonttools          4.29.1
frozenlist         1.3.0
gradio             2.6.0
h11                0.13.0
idna               3.3
importlib-metadata 4.11.0
itsdangerous       2.0.1
Jinja2             3.0.3
kiwisolver         1.3.2
markdown2          2.4.2
MarkupSafe         2.0.1
matplotlib         3.5.1
monotonic          1.6
multidict          6.0.2
numpy              1.21.5
opencv-python      4.5.5.62
packaging          21.3
pandas             1.3.5
paramiko           2.9.2
Pillow             9.0.1
pip                21.2.2
pycparser          2.21
pycryptodome       3.14.1
pydantic           1.9.0
pydub              0.25.1
PyNaCl             1.5.0
pyparsing          3.0.7
python-dateutil    2.8.2
python-multipart   0.0.5
pytz               2021.3
requests           2.27.1
setuptools         58.0.4
six                1.16.0
sniffio            1.2.0
starlette          0.17.1
typing_extensions  4.1.1
urllib3            1.26.8
uvicorn            0.17.4
Werkzeug           2.0.3
wheel              0.37.1
yarl               1.7.2
zipp               3.7.0

**Comment by abidlabs** [comment]
This usually means that `gradio` was not successfully installed. Can you try uninstalling and reinstalling? 

For example, see here where it works: https://colab.research.google.com/drive/1WTMg51DaEQRny7x3QKaaMOIk1bFkcTeG?usp=sharing

**Comment by zxy2020** [comment]
您好，邮件已收到。曾星宇

**Comment by abidlabs** [comment]
Do you mind if we close this @zxy2020 as this should not be an issue if `gradio` is reinstalled correctly?

**Comment by abidlabs** [comment]
Closing, feel free to reopen with more details. Thanks!
