### ISSUE TITLE
Can model3D show the camera pose in every frame?

### ISSUE THREAD

**Issue by A-pril** [gradio-app/gradio#6145]
Hello~Great work! 
But our model just need use the camera's pose as input, so how can I get the real-time camera pose please?
If there were this feature, I'll be grateful.
Thanks a lot!

**Comment by abidlabs** [comment]
Hi @A-pril can you elaborate on what you mean in a little more detail?

**Comment by A-pril** [comment]
> Hi @A-pril can you elaborate on what you mean in a little more detail?

Thanks for your reply! I just use the model3D component to load my glb file and we can use this component to drag pr rotate our model, right? And I hope I can get the angle of rotation, I guess maybe it's controlled by the camera_position? So how can I get the real-time camera_position? Could you provide any interface?

**Comment by freddyaboulton** [comment]
Tagging @hannahblair and @dawoodkhan82 the resident model3d experts

**Comment by dawoodkhan82** [comment]
@A-pril The `model3D` component does not currently return the camera position (it only allows you to set the initial camera position). Although this might be something we can consider adding in the future!

You can however create a `model3D` custom component and add this functionality to your component. Follow our guide for creating a custom component [here](https://www.gradio.app/guides/five-minute-guide).

**Comment by abidlabs** [comment]
I'll go ahead and close this issue since we are not planning to include this in the core Gradio library. But happy to help if you are interested in making this a custom Gradio component (feel free to ask questions in this issue).
