### ISSUE TITLE
Selectable component, like Dropdown, cannot change the select index when update it

### ISSUE THREAD

**Issue by IcyTide** [gradio-app/gradio#6178]
### Describe the bug

When i update Dropdown with gr.update(choices, value), the selected index in it won't change, and lead to cannot select specific option unless after select another option.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

dropdown_a = gr.Dropdown(choices=[1, 2, 3])
dropdown_b = gr.Dropdown(choices=[4, 5, 6])

def dropdown_a_func():
    return gr.update(choices=[7, 8, 9], value=9)
dropdown_a.change(dropdown_a_func, outputs=dropdown_b)

If you select 5 in dropdown_b firstly, which means select index 1(start from 0)
Then select random option in dropdown_a to trigger update function

Reselect dropdown_b, you will find that cannot select 8 in dropdown_b.

### System Info

```shell
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.1
fastapi: 0.95.1
ffmpy: 0.3.1
gradio-client==0.6.1 is not installed.
httpx: 0.25.0
huggingface-hub: 0.16.4
importlib-resources: 6.1.0
jinja2: 2.11.3
markupsafe: 2.0.1
matplotlib: 3.4.3
numpy: 1.22.4
orjson: 3.9.7
packaging: 21.3
pandas: 1.3.4
pillow: 10.0.1
pydantic: 1.10.11
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.26.0
semantic-version: 2.10.0
typing-extensions: 4.7.1
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.25.0
huggingface-hub: 0.16.4
packaging: 21.3
requests: 2.26.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @IcyTide is this still an issue in the latest version of Gradio?

**Comment by abidlabs** [comment]
Closing for lack of followup -- we can reopen if we have a full repro.
