### ISSUE TITLE
When flagging with CSVLogger(), directories are made also for components that should not trigger it (Ex. textual components)

### ISSUE THREAD

**Issue by EgonFerri** [gradio-app/gradio#6196]
### Describe the bug

The 4.x update caused an unexpected behavior (I suspect due to some changes in Components internals).

When flagging with CSVLogger(), repositories are generated for each component (also for those that don't need it).
The repositories should be generated only for the components that require additional files (ex. images, video, audio). For those components, the repositories are correctly generated.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr


def greet(name):
    return "Hello " + name + "!"


demo = gr.Interface(fn=greet, inputs="text", outputs="text", flagging_dir='flagged')

if __name__ == "__main__":
    demo.launch()

```

When flagging, directories `name` and `output` are generated. 
In the CSV, by the way, the values are correctly saved.

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/43636749/c37acad2-e9bd-4fac-b36c-323630fa700b)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.0.2
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.1
fastapi: 0.103.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.0
huggingface-hub: 0.17.2
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.26.1
orjson: 3.9.7
packaging: 23.1
pandas: 2.1.0
pillow: 10.1.0
pydantic: 2.3.0
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.9.1
httpx: 0.25.0
huggingface-hub: 0.17.2
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by EgonFerri** [comment]
I think I found the cause of the bug.

Folders for each component are generated in `flagging.py`, at row 169.

```python
        csv_data = []
        for idx, (component, sample) in enumerate(zip(self.components, flag_data)):
            save_dir = Path(
                flagging_dir
            ) / client_utils.strip_invalid_filename_characters(
                getattr(component, "label", None) or f"component {idx}"
            )
            save_dir.mkdir(exist_ok=True)
            if utils.is_update(sample):
                csv_data.append(str(sample))
            else:
                csv_data.append(
                    component.flag(sample, flag_dir=save_dir)
                    if sample is not None
                    else ""
                )
``` 

Then the folder is used only if the component's flag method needs it. 

For example in `Image\ component: 

```python
    def flag(self, payload: Any, flag_dir: str | Path = "") -> str:
        """
        Write the component's value to a format that can be stored in a csv or jsonl format for flagging.
        """
        if self.data_model:
            payload = self.data_model.from_json(payload)
            return payload.copy_to_dir(flag_dir).model_dump_json()
        return payload
```

I believe it's okay to pass always `save_dir` to `component.flag`, but at least the `save_dir.mkdir(exist_ok=True)` should be moved inside `flag` method of each component that actually uses it. 

@abidlabs what do you think? If it makes sense, I can work a pull request that fixes this.

**Comment by abidlabs** [comment]
Hey @EgonFerri thanks for catching this bug, upon initial inspection, I think you're right! Would be happy to review your PR
