### ISSUE TITLE
Radio bug

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#6198]
### Describe the bug

Reported on discord. 

Is there a new bug in radio choices after the update? I had my demo code in Colab, which included some radio “yes/no” choices. However, today when I started the runtime and ran the app again in Colab, I couldn’t choose “all yes” or “all no”! When I tried to do so, the previous answer disappeared. Now, I wrote a sample code to test if it remains or not, and I see the same results. Here is the sample code:

```py
import gradio as gr

with gr.Blocks() as demo:
  with gr.Row():
      with gr.Column():
        Drug = gr.Radio(["Yes","No"])
        Family = gr.Radio(["Yes","No"])
  if __name__ == "__main__":
      demo.queue()
      demo.launch()
```
When I click “yes” for the first box and then do the same for the second radio, the first answer gets removed! Would you please help me with this problem?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```py
import gradio as gr

with gr.Blocks() as demo:
  with gr.Row():
      with gr.Column():
        Drug = gr.Radio(["Yes","No"])
        Family = gr.Radio(["Yes","No"])
  if __name__ == "__main__":
      demo.queue()
      demo.launch()
```

### System Info

```shell
4.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hmm this is not good. I looked into it, but I'm actually not sure what the issue is. Will leave this for someone who knows more Svelte than me

**Comment by chaofanqw** [comment]
faced the same bug for the 4.0.2, code for reproducing the error:

```python
import gradio

with gradio.Blocks() as demo:
    radio_1 = gradio.Radio(choices=['a', 'b'], value='a', interactive=True)
    radio_2 = gradio.Radio(choices=['a', 'b'], value='a', interactive=True)

demo.launch()
```
