### ISSUE TITLE
[Gradio 4] Drag and drop is not working for `gr.Video` and `gr.Audio`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#6202]
### Describe the bug

It's possible to click the area to upload a video, but drag & drop doesn't seem to work.

https://github.com/gradio-app/gradio/assets/25161192/a117d8f5-dadc-4970-882c-074a04d50625

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```py
import gradio as gr

gr.Interface(fn=lambda x: x, inputs="video", outputs="video").launch()
```

### System Info

```shell
gradio==4.0.2
```

### Severity

I can work around it

**Comment by hysts** [comment]
Drag and drop doesn't work for `gr.Audio` too.

**Comment by pandazzh2020** [comment]
me too
