### ISSUE TITLE
Add simple versions of Audio, Video, Image Components

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#6217]
- [x] I have searched to see if a similar issue already exists.

Make it easier to template off a video, audio, or image component by simplifying the feature set.

No editing or trimming.
Just upload and display static video or audio.
Drag and drop supported.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by abidlabs** [comment]
We've done this via the Simple* components now, closing!
