### ISSUE TITLE
Add ability to block” event listeners (e.g. file uploads, submit button)

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#6219]
From the 4.0 tracking issue. Turned it into an issue in the 4.x milestone

**Comment by vidthehuman** [comment]
I am uploading the  video everything fine  when i am  using local url  but when  i am  using public url  video uploading getting taking time and my code  is  running in backend why this happening so i ma using gradio 4.21.0 and when i am using the version 3.50 then getting connection error

**Comment by abidlabs** [comment]
or just make the event pending until the upload etc. is ready

**Comment by abidlabs** [comment]
Closed via #9253
