### ISSUE TITLE
Chatbot like/dislike not displaying even when like event is set

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#6230]
The like/dislike event won't show up

```python
import gradio as gr
import random

def vote(tmp, index_state, data: gr.LikeData):
    value_new = data.value
    index_new = data.index
    if len(index_state) == 0 :
        index_state.append(index_new)
    else:
        if index_new in index_state:
            return "Your feedback is already saved", index_state
        else:
            index_state.append(index_new)
    return str(data.value) + ";" + str(data.index)+";"+ str(data.liked)+";"+str(index_state), index_state

with gr.Blocks() as demo:
    tmp = gr.Textbox(visible=True, value="")
    chatbot = gr.Chatbot(layout='panel')
    msg = gr.Textbox()
    clear = gr.ClearButton([msg, chatbot])
    index_state = gr.State(value=[])
    
    def respond(message, chat_history):
        bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
        chat_history.append((message, bot_message))
        return "", chat_history

    msg.submit(respond, [msg, chatbot], [msg, chatbot])
    chatbot.like(vote, [tmp, index_state], [tmp, index_state])

demo.launch()
```

<img width="1277" alt="image" src="https://github.com/gradio-app/gradio/assets/121886414/f6e80293-87ae-4ace-9ec4-1ba10f417efb">

Would be great to have this built in the ChatInterface

_Originally posted by @surajspass in https://github.com/gradio-app/gradio/issues/5871#issuecomment-1789159931_

**Comment by sajjadmosaheb** [comment]
how can I add a like/dislike function to Chatinterface?
this is possible with blocks but I can't add to a Chatinterface.

import gradio as gr

def greet(history, input):
    return history + [(input, "Hello, " + input)]

def vote(data: gr.LikeData):
    if data.liked:
        print("You upvoted this response: " + data.value)
    else:
        print("You downvoted this response: " + data.value)
    

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    textbox = gr.Textbox()
    textbox.submit(greet, [chatbot, textbox], [chatbot])
    chatbot.like(vote, None, None)  # Adding this line causes the like/dislike icons to appear in your chatbot
    
demo.launch()
