### ISSUE TITLE
focused & unfocused/blurred event listeners for Code components

### ISSUE THREAD

**Issue by rsr23** [gradio-app/gradio#6233]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
the `gradio.Textbox.focus(fn, ···)` and `gradio.Textbox.blur(fn, ···)` event listeners are great for textbox Components.
But similar event listeners are not available for Code components.

**Describe the solution you'd like**  
Event listeners like `gradio.Code.focus(fn, ···)` and `gradio.Code.blur(fn, ···)`

**Additional context**  
None

**Comment by abidlabs** [comment]
Thanks @rsr23! Would you like to open a PR for this?

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/6323
