### ISSUE TITLE
Make UploadText expose text as a prop that can be set by developers

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#6237]
- [ ] I have searched to see if a similar issue already exists.

Was building a PDF uploader and I'd like the upload text to read `Upload your PDF here` but I can't because UploadText only takes one of a few options. The closest one is `file` but that's too generic for my case.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by pngwn** [comment]
I actually kind of added this up in a pretty terrible way: https://github.com/gradio-app/gradio/blob/main/js/atoms/src/UploadText.svelte#L6

The `message` prop is fine, we just need to improve how we handle things when it is passed in.

**Comment by freddyaboulton** [comment]
Yea agreed - I don't think I want this text to display even if message is passed in https://github.com/gradio-app/gradio/blob/185f9aa15687fa07eb3e3c946410fe959b709d16/js/atoms/src/UploadText.svelte#L22C1-L22C33

**Comment by pngwn** [comment]
Yeah. I agree.

**Comment by freddyaboulton** [comment]
Not a priority atm
