### ISSUE TITLE
Switch from black and isort to ruff formatter

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#6238]
The ruff formatter is apparently much faster: https://x.com/charliermarsh/status/1716861072374657497?s=20, and would allow us to reduce the number of tools we use in our CI

**Comment by DarhkVoyd** [comment]
@abidlabs Hey, should I pick this up?

**Comment by abidlabs** [comment]
Hi @DarhkVoyd yes thank you, happy to review the PR!
