### ISSUE TITLE
Gradio.Dataframe does no longer properly pass values updated in the GUI when used as input from version 4

### ISSUE THREAD

**Issue by Rjdrenth** [gradio-app/gradio#6252]
### Describe the bug

When running the [filter records example](https://www.gradio.app/docs/dataframe) code in `3.50.2` the records are filtered based on gender-entries a user made in the webpage and based on the selected gender in the dropdown. These records are displayed in the output dataframe as expected.

However, in gradio version `4.0.2` the values that are entered in the webpage are not properly passed to the backend. Thus, no output is visible in the output dataframe.

Changing the `filter_records(..)` to include a print-statement shows that the values from the GUI are not reaching the backend:
```
def filter_records(records, gender):
    print(records)
    return records[records["gender"] == gender]
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

1. Install gradio version `4.0.2`
2. Add the code from the [filter records example](https://www.gradio.app/docs/dataframe) to a file `df_example.py`
3. Run `python df_example.py`
4. Optionally add the print-statement as mentioned before
5. Enter values in the interface and press `Submit`
6. Observe that the output dataframe stays empty

### Logs

```shell
No (error) logs given
```

### System Info

```shell
gradio environment
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.0.2
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.0
huggingface-hub: 0.18.0
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.1
matplotlib: 3.7.0
numpy: 1.23.5
orjson: 3.9.10
packaging: 22.0
pandas: 1.5.3
pillow: 9.4.0
pydantic: 2.4.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.28.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.0
huggingface-hub: 0.18.0
packaging: 22.0
requests: 2.28.1
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Taking a look
