### ISSUE TITLE
Table Cell does not fold text with underscore

### ISSUE THREAD

**Issue by Muennighoff** [gradio-app/gradio#6253]
### Describe the bug

<img width="947" alt="Screenshot 2023-11-02 at 8 20 15 AM" src="https://github.com/gradio-app/gradio/assets/62820084/1258b7ac-43a4-431a-ab8c-6d33eb6a1c14">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Run https://huggingface.co/spaces/mteb/leaderboard

### System Info

```shell
https://huggingface.co/spaces/mteb/leaderboard
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
I'm pretty sure this has been fixed on more recent versions of gradio. Can you try upgrading the leaderboard to gradio 4.0.2?
