### ISSUE TITLE
Locally Available Logout Functionality 

### ISSUE THREAD

**Issue by Solomin0** [gradio-app/gradio#6259]
- [x] I have searched to see if a similar issue already exists.
https://github.com/gradio-app/gradio/issues/5163
I checked this issue but it is not what I need. 

**Is your feature request related to a problem? Please describe.**  

I am not using Huggingface account management for my users as my business REQUIRES a fully local managed account so the current gradio.Logoutbutton() does nothing for me. My users need a way to log out of the app aside from manually opening the browser storage and clearing the cookies which is what we are doing now. 

**Describe the solution you'd like**  
I would like some sort of Logout functionality to allow the user's authentication cookie to be cleared when a button is clicked or the tab is closed. Making the user manually clear cookies to log out when not using Huggingface is not ideal and provides  a poor user experience. If this is out of scope for Gradio's normal use case any workaround or point in a direction would be much appreciated. 

Direct cookie management would be very useful and allow me to move forward in having more direct control of my logged in sessions similarly to what this person is requesting.  
https://discuss.huggingface.co/t/how-to-set-a-cookie-with-gradio/59973

Thanks.

**Comment by abidlabs** [comment]
Thanks @Solomin0! This is something we can look into, but we already have an issue for this here: https://github.com/gradio-app/gradio/issues/5163 so I'll go ahead and close this as a duplicate
