### ISSUE TITLE
Make CI checks required even though they don't have to run for every commit

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#6264]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I remember @pngwn saying he had an idea for how to do this 😄 Filing this so we don't forget and to jog his memory.

**Describe the solution you'd like**  

**Additional context**

**Comment by pngwn** [comment]
i haven't forgotten! It annoys me every day!

**Comment by abidlabs** [comment]
This is now done, thank youuuuuuuu @pngwn
