### ISSUE TITLE
tag releases on github

### ISSUE THREAD

**Issue by lizelive** [gradio-app/gradio#6265]
### Describe the bug

As an active user of your library, I have noticed that while you regularly update the library and add new features, these updates are not always reflected with tags in the GitHub repository. This makes it difficult to track changes, especially when trying to understand the differences between versions or when debugging issues that may arise.

Tagging releases is a common practice that provides several benefits:

1. Ease of use: It allows users to easily check out specific versions of the codebase without having to search through commit messages.
2. Better tracking: It helps in tracking the changes between different versions of the software.
3. Reproducibility: It aids in ensuring reproducibility, as users can reference specific versions of your library in their projects.
4. By tagging each new release, you would greatly improve the user experience and make it easier for us to keep up with your excellent work.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

compare the [github release](https://github.com/gradio-app/gradio/releases) to the [pypi](https://pypi.org/project/gradio/) 

### System Info

https://github.com/NixOS/nixpkgs/blob/0cbe9f69c234a7700596e943bfae7ef27a31b735/pkgs/development/python-modules/gradio/default.nix#L62C1-L62C59

### Severity

I can work around it

**Comment by pngwn** [comment]
Yep, I'm aware of this. It slipped under the radar when we change our release process. I'll be adding them back very shortly!

**Comment by abidlabs** [comment]
@pngwn I think this still needs to be done, right?

**Comment by ayan4m1** [comment]
@pngwn Hey, I am also blocked trying to keep a fork up to date because of the lack of tags, is there any chance they can at least be retroactively tagged when it does happen?

**Comment by pngwn** [comment]
Yeah I'm still need to do this, should be done soon.  

@ayan4m1 I'll try to to tag previous versions too!

**Comment by pngwn** [comment]
@ayan4m1 The repo is now comprehensively tagged and should stay that way: https://github.com/gradio-app/gradio/tags

**Comment by ayan4m1** [comment]
@pngwn Thank you very much!

**Comment by pngwn** [comment]
@ayan4m1 no worries!
