### ISSUE TITLE
Local Image Reference in gr.HTML()

### ISSUE THREAD

**Issue by bp-twinkl** [gradio-app/gradio#6281]
### Describe the bug

Previously I was able to reference local images using `gr.HTML("<img  src='file/image.png' alt='image One'>")`. However this no longer works with gradio version 4.0.2.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

`gr.HTML("<img  src='file/image.png' alt='image One'>")`

### System Info

```shell
gradio version: 4.0.2
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @bp-twinkl good question! For security reasons, we've changed which files are served by default. Now, files in your working directory are no longer automatically exposed to users using your Gradio app. Instead, you can expose which files are available to users of your app using the `allowed_paths` parameter in `launch()`. 

So you could do:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.HTML("<img src='file/image.png' alt='image One'>")
    
demo.launch(allowed_paths=["image.png"])
```

or if you want to expose all files in your working directory (not recommended if you plan to share your app with others, but would give you the same behavior as before):

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.HTML("<img src='file/image.png' alt='image One'>")
    
demo.launch(allowed_paths=["."])
```

**Comment by antonionieto** [comment]
Hey @abidlabs! Just saw your last comment and that was really useful. I didn't notice that change in the Gradio 4.X release. 

I am also getting that issue, but in my case I'm using `gr.mount_gradio_app()`, so I don't use `launch()` at all. Any ideas on how I could serve the images using `gr.mount_gradio_app()`? 

Thanks in advance!
