### ISSUE TITLE
URL query parameters with queue is broken

### ISSUE THREAD

**Issue by radames** [gradio-app/gradio#6283]
### Describe the bug

Since this PR we were able to get the query params via `gr.request`, however some new bug was introduce and on version `4.0.2`. If you disable the queue the request comes with expected query data

https://github.com/gradio-app/gradio/issues/5485

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

The workaround is to disable the queue

```python
import gradio as gr

def echo(params):
    print(params)
    return params

def get_params(request: gr.Request):
  params = request.query_params
  ip = request.client.host
  return {"params": params, 
          "ip": ip}

  
with gr.Blocks() as demo:
  url_params = gr.State()
  text_in = gr.Textbox()
  text_out = gr.JSON()
  btn = gr.Button()
  btn.click(echo, inputs=[url_params], outputs=[text_out])
  demo.load(get_params, None, url_params, queue=True)
  #demo.load(get_params, None, url_params, queue=False)

demo.launch()
```

### System Info

```shell
Gradio 4.0.2
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Looks like there was a regression, will take a look!
