### ISSUE TITLE
Allow Vertical dragability for Chatbot Component. 

### ISSUE THREAD

**Issue by Solomin0** [gradio-app/gradio#6286]
- [x] I have searched to see if a similar issue already exists.

Currently if not managed properly it can be a pain to retain enough space vertically for the Chatbot component. By allowing users to expand it client side, we can provide a better user experience allowing them to set how much of the chat they would like to see.

It would be nice to be able to resize the Chatbot component by dragging the corner potentially with some flag to allow/disallow the resizing within the constructor. The same functionality as gr.Textbox currently has is what I am looking for. I think this would also provide more congruence between components allowing all front facing text fields to be resizeable.  

I am aware of the height property but specifically setting a static size in pixels isn't very flexible/dynamic and would require the user to set some height value slider as a work around. 

This issue is in a similar vein but I believe is different enough to warrant a separate topic.  
https://github.com/gradio-app/gradio/issues/4001

It was closed but no changes were made to any files that I could see with the only solution being a pure css implementation. 
https://github.com/gradio-app/gradio/pull/4040 

Thanks.

**Comment by abidlabs** [comment]
Hi @Solomin0 I think this is quite similar to #4966 -- would you care to comment on that issue so that we can find a solution that works for these cases?
