### ISSUE TITLE
gr.Theme.from_hub error

### ISSUE THREAD

**Issue by shpower** [gradio-app/gradio#6298]
### Describe the bug

 my_theme=gr.Theme.from_hub('xiaobaiyuan/theme_brief@>=1.0.0,<2.0.0')
   
When I run this line I got this error: raise ValueError(f"{space_info.id} is not a valid gradio-theme space!")
gradio version: 4.1.1

Very urgent! 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio as gr

my_theme=gr.Theme.from_hub('xiaobaiyuan/theme_brief@>=1.0.0,<2.0.0')

### System Info

```shell
gradio version: 4.1.1
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hmm looks like this might be an issue with the `huggingface_hub` library not parsing tags correctly, I'll push a temporary fix and then create an issue there. cc @Wauplin
