### ISSUE TITLE
textbox cannot reforcus after submit

### ISSUE THREAD

**Issue by Da-Capo** [gradio-app/gradio#6303]
### Describe the bug

https://www.gradio.app/docs/chatbot#demos
this textbox cannot reforcus after submit at gradio 4
gradio3 can reforcus to textbox

### Have you searched existing issues?  🔎

- [ ] I have searched and found no existing issues

### Reproduction

1

### System Info

```shell
1
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @Da-Capo can you please provide a repro? I don't see the issue you are describing with this demo:

```py
import gradio as gr

def echo(message, history):
    return message

demo = gr.ChatInterface(fn=echo, examples=["hello", "hola", "merhaba"], title="Echo Bot")
demo.launch()
```

on 4.0

**Comment by Da-Capo** [comment]
https://github.com/gradio-app/gradio/assets/10624004/57bcfde8-522a-49fc-a994-22f5b0ccfcf5

In this video, left is 3.42  right is 4.1.1

in 3.42 i can continue edit the textbox after submit,
but in 4.1.1 i need another click to focus it.

It means that each chat requires an additional click.

**Comment by congchan** [comment]
I faced the same issue, any progress on it?
