### ISSUE TITLE
Provide a setting for public spaces to hide the Files tab

### ISSUE THREAD

**Issue by dwipper** [gradio-app/gradio#6306]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Since our company has patent-pending process patents, we don't want the code in our app made public. We have implemented the suggested public -> private space approach using gr.load in the public space. While it works in certain circumstances in 3.50.2, it's now broken in 4.1.1. There are other limitations, especially when using auth=, since the username doesn't get passed to the private space. We have also seen that the a .load in the private space throws an error (#5927)

**Describe the solution you'd like**  
I would suggest that the Space -> Settings have a switch (similar to Public/Private switch) that turns off the "Files" tab in the UI. That way we could have a Public space, with auth= turned on, but not expose our code to the general public. It should also not be possible to duplicate the space or clone the repo.

**Additional context**  
None

**Comment by abidlabs** [comment]
Thanks @dwipper. Since this is actually a question regarding Spaces and not the Gradio library, here would be a better place to ask it: https://discuss.huggingface.co/c/spaces/24
