### ISSUE TITLE
Autoplaying audio through HTML doesnt work properly when using yield

### ISSUE THREAD

**Issue by gibsonhu123** [gradio-app/gradio#6334]
### Describe the bug

when streaming to HTML via async function via yield, it does not play all the audio, only the last yield.

This was working in 3.9 but not in 4.0. What has changed in the way HTML is rendered?

I have added an example of this problem

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
async def audio_to_html():
       audio_file = 'test.mp3'
       count = 2
       while count>0:
           with open(audio_file, 'rb') as audio_bytes:
                audio = base64.b64encode(audio_bytes.read()).decode("utf-8")
                html_str = f'<audio src="data:audio/mpeg;base64,{audio}" controls autoplay></audio>'
                yield html_str
           
           time.sleep(5)
           count=count-1

btn = gr.Button("Submit",variant="primary")
html = gr.HTML(visible=False)

e1 = btn.click(audio_to_html,inputs=[], outputs=[html])
           
```

### System Info

```shell
4.0.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @gibsonhu123 why not just return `yield` the audio file directly using a `gr.Audio` component?

**Comment by abidlabs** [comment]
Closing for lack of followup -- we can reopen if we have more info.
