### ISSUE TITLE
Use `gr.Error` for errors in `gr.Audio`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#6335]
- [x] I have searched to see if a similar issue already exists.

Would it be possible to catch `Exception` and re-raise it as `gr.Error`?

I was checking the recently added `min_length` and `max_length` of `gr.Audio` with code like this:
```py
import gradio as gr

gr.Interface(fn=lambda x: x, inputs=gr.Audio(min_length=5, max_length=60), outputs=gr.Audio()).queue().launch()
```
and realized that it raises `ValueError` in `.preprocess()` when one feeds an audio that is too short/long. https://github.com/gradio-app/gradio/blob/f1409f95ed39c5565bed6a601e41f94e30196a57/gradio/components/audio.py#L181-L188

But the problem is that the error is only shown in your terminal. In the case of HF Spaces, users except for the owner of the Space cannot see the log, and it makes it hard for them to understand why they get errors.

This reminds me that I wished `ValueError`, `RuntimeError` etc. would be shown as `gr.Error` many times in the past. I've mentioned `gr.Audio` as an example above, but more generally, I think it would be nice if all errors were caught and re-raised as `gr.Error`.

**Comment by abidlabs** [comment]
Thanks @hysts! I agree -- let's change these `ValueError` to `gr.Error` -- I thought we had already made that change actually @hannahblair?

In terms of raising all errors to the frontend, we wouldn't want to do that by default because it might expose sensitive bits of the code for the gradio app to users, but if you are certain you want to do that, you can set `show_error=True` in `launch()`

**Comment by hysts** [comment]
Oh, I wasn't aware of the `show_error` argument. Thanks!

**Comment by abidlabs** [comment]
This should be fixed in 4.2.0!

**Comment by hysts** [comment]
@abidlabs @hannahblair 
Looks like it's still raising `ValueError`.
https://github.com/gradio-app/gradio/blob/1751f14c1b26c72c0fcc6ba4c69c060c7a199e5d/gradio/components/audio.py#L118-L136

**Comment by abidlabs** [comment]
Hey @hysts, these are developer-facing errors (e.g. something is wrong with the code itself) so they should just raise a ValueError which would be shown to the developer at runtime. 

The user-facing `gr.Error` should only be raised if a user does something invalid in the Gradio app, like uploads a file that is too long. 

OK to close this issue?

**Comment by hysts** [comment]
@abidlabs Ah, so sorry. Yeah, I know. Somehow I linked completely different piece of code. 😇 
I meant this: https://github.com/gradio-app/gradio/blob/1751f14c1b26c72c0fcc6ba4c69c060c7a199e5d/gradio/components/audio.py#L183-L190
