### ISSUE TITLE
Page hangs when `sources` for `gr.Image` is provided as a string instead of a list

### ISSUE THREAD

**Issue by quillbit** [gradio-app/gradio#6337]
### Describe the bug

When I launch the program, I try to open the page using my browser, but the page keeps loading. I opened the browser developer tools and found the console output:
```
Uncaught (in promise) TypeError: sources.sort is not a function
    at $$self.$$.update (ImageUploader.svelte:68:30)
    at init (svelte.js:3246:5)
    at new ImageUploader (ImageUploader.svelte:101:26)
    at Array.create_default_slot_1 (Index.svelte:149:21)
    at create_slot (svelte.js:165:23)
    at create_dynamic_element (index.js:73:1)
    at create_fragment$1 (Block.svelte:22:11)
    at init (svelte.js:3250:34)
    at new Block (Block.svelte:18:52)
    at Array.create_else_block (Index-0f548159.js:50:10)
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### System Info

```shell
gradio >= 4.1.1
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @quillbit can you provide a more detailed reproduction? What page are you opening?

**Comment by quillbit** [comment]
> 嗨，你能提供更详细的复制品吗？您正在打开哪个页面？

![1](https://github.com/gradio-app/gradio/assets/130726845/45221c2d-a0cc-432a-9806-c10bf9ca39a6)

**Comment by abidlabs** [comment]
What is the code for this Gradio app? We need a minimal code example that we can use to reproduce the issue above. See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by quillbit** [comment]
> 这个 Gradio 应用程序的代码是什么？我们需要一个最小的代码示例，我们可以使用它来重现上述问题。请参见：https://stackoverflow.com/help/minimal-reproducible-example

ok this is my sample code：
```python
import gradio as gr

def test(image_file: str):
    return image_file

with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column():
            with gr.Row():
                inputs_image = gr.Image(image_mode="RGB", sources="upload", type="filepath")
            with gr.Row():
                btn = gr.Button(variant="primary")

        with gr.Column():
            with gr.Row():
                outputs_image = gr.Image(type="pil")
        
    btn.click(fn=test, inputs=[inputs_image], outputs=[outputs_image])


demo.queue().launch(inbrowser=True, server_name="0.0.0.0")
```

**Comment by abidlabs** [comment]
The `sources` parameter needs to accept a list: `["upload"]` in your case.

```py
import gradio as gr

def test(image_file: str):
    return image_file

with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column():
            with gr.Row():
                inputs_image = gr.Image(image_mode="RGB", sources=["upload"], type="filepath")
            with gr.Row():
                btn = gr.Button(variant="primary")

        with gr.Column():
            with gr.Row():
                outputs_image = gr.Image(type="pil")
        
    btn.click(fn=test, inputs=[inputs_image], outputs=[outputs_image])


demo.queue().launch(inbrowser=True, server_name="0.0.0.0")

```

cc @pngwn we should accept and cast strings for better DX like we do in Audio, Video

**Comment by quillbit** [comment]
> The `sources` parameter needs to accept a list: `["upload"]` in your case.
> 
> ```python
> import gradio as gr
> 
> def test(image_file: str):
>     return image_file
> 
> with gr.Blocks() as demo:
>     with gr.Row():
>         with gr.Column():
>             with gr.Row():
>                 inputs_image = gr.Image(image_mode="RGB", sources=["upload"], type="filepath")
>             with gr.Row():
>                 btn = gr.Button(variant="primary")
> 
>         with gr.Column():
>             with gr.Row():
>                 outputs_image = gr.Image(type="pil")
>         
>     btn.click(fn=test, inputs=[inputs_image], outputs=[outputs_image])
> 
> 
> demo.queue().launch(inbrowser=True, server_name="0.0.0.0")
> ```
> 
> cc @pngwn we should accept and cast strings for better DX like we do in Audio, Video

Thank you for your patient answer, it is now available

**Comment by abidlabs** [comment]
Thanks for confirming @quillbit. I'll reopen this so that we can make the fix in `gr.Image` as well
