### ISSUE TITLE
Describe the documentation of `waveform_options` of `gr.Audio` in more detail

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#6338]
- [x] I have searched to see if a similar issue already exists.

It'd be nice if `waveform_options` of `gr.Audio` is documented in more detail.

`waveform_color` and `waveform_progress_color` are obvious, so it's OK, but I feel the documentation of `show_controls` and `skip_length` is insufficient.

I tried setting `show_controls`, but I'm not sure what this is for. Apparently, the default value is `False`, but it appears a bit weird to me if set `True`. I wonder what's the expected use case of this option.

![](https://github.com/gradio-app/gradio/assets/25161192/59264c72-563f-4e6f-9bbd-49711918613e)

Also, I don't know what `skip_length` does. I tried some values but couldn't figure out what was changed.

**Comment by NewEpoch2020** [comment]
I have the same confusion

**Comment by thiswillbeyourgithub** [comment]
I have the same confusion and would like to add that I really miss the feature to disable edit in audio. In version prio to 4.0 we could use `show_edit_button=False` per #5149

All those buttons are cluttering my screen (I use multiple audio components)
