### ISSUE TITLE
Place tow(maybe multiple?) chatbot in single row

### ISSUE THREAD

**Issue by HHHHHANS** [gradio-app/gradio#6340]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
There is scenary that i want to type same question to different LLMs and show answers to relevant chatbot.
In order to show answer in user friendly way, place these chatbots vertically might be better than horizontal placement

**Describe the solution you'd like**  
support described layout with this kind of coding:
```
with gr.Blocks() as demo:
    with gr.Column():
        chatbot1 = gr.Chatbot()
    with gr.Column():
        chatbot2 = gr.Chatbot()
```

Thx for reading.

**Comment by abidlabs** [comment]
Hi @HHHHHANS if you want to place them horizontally next to each other, you can do:

```py
with gr.Blocks() as demo:
    with gr.Row():
        chatbot1 = gr.Chatbot()
        chatbot2 = gr.Chatbot()

```
