### ISSUE TITLE
Pull  move_resource_to_block_cache out of `as_example` and into the `Dataset` class

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#6346]
- [ ] I have searched to see if a similar issue already exists.

When I was building my PDF viewer component, I struggled to get files to show up for my component in the Example preview.
I kept getting 403.

I then realized I was supposed to add an `as_example` method to move any files passed to the `Dataset` into the cache.

We should move this responsibility from the component to the `Dataset` class so that others don't struggle with this.

**Additional context**

**Comment by abidlabs** [comment]
Yes that makes sense. The only thing is how to tell in the `gr.Dataset` if you are working with file versus a non-file string

**Comment by abidlabs** [comment]
This is now fixed thanks to https://github.com/gradio-app/gradio/pull/6933
