### ISSUE TITLE
gradio cc dev does not pick up changes to `Example.svelte`

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#6348]
### Describe the bug

When I was developing my custom component, I noticed that the dev server was not picking up changes to the `Example.svelte` file.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

* Clone this space: https://huggingface.co/spaces/freddyaboulton/gradio_pdf
* cd into `src`
* `gradio cc dev`
* Modify the `Example.svelte` file. It won't be reflected in the app. Even after refreshing.

### Screenshot

![example_not_dev](https://github.com/gradio-app/gradio/assets/41651716/9b1f7e9a-3d66-4e8d-acf9-e6d1623c95cf)

### System Info

```shell
❯ gradio environment
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.1.1
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.0
huggingface-hub: 0.17.3
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.26.1
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.2
pillow: 10.0.1
pydantic: 2.4.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.0
huggingface-hub: 0.17.3
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by pngwn** [comment]
After starting the app in dev mode could you go into the browser console and type:

```
window.__GRADIO__CC__
```

And tell me what it shows?

**Comment by freddyaboulton** [comment]
@pngwn 

<img width="585" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/a6da7f30-4201-4472-bc3c-eb29fe3b1466">

**Comment by pngwn** [comment]
Hmm, i wonder where it is even getting the example from. If you delete your `dist` and run the dev server, does it error? I'm guessing it is picking up the built file via the custom component end point.

Either way the dev server isn't detecting the `Example` here for some reason.

**Comment by pngwn** [comment]
This is embarassing.

**Comment by freddyaboulton** [comment]
In this case, I think its using the version of the `Example.svelte` I previously built. If I remove `termplates` and `dist` it uses the standard fallback as far as I can tell!

<img width="1591" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/94ec8a43-f136-4138-a983-7f060cade03f">

**Comment by pngwn** [comment]
Typo here: https://github.com/gradio-app/gradio/blob/main/js/preview/src/dev.ts#L126

We should remove the type on the `exports` so it looks like this:

```ts
const exports = {
  component: pkg.exports["."] as string,
  exmaple: pkg.exports["./example"] as string
} as const;
```

then this line () will error:

```
const example = exports.exmaple
```

**Comment by freddyaboulton** [comment]
mmmm x-maple 🍁
