### ISSUE TITLE
Incompatibility between `gradio 3.x` and `@gradio/client 0.7.2`

### ISSUE THREAD

**Issue by gibiee** [gradio-app/gradio#6353]
### Describe the bug

I am testing API request in Node.js with @gradio/client.

I found the incompatibility between `gradio 3.x` and `@gradio/client 0.7.2`

In detail, if I write `demo.queue()` with gradio 3.x, I can't receive API output with `@gradio/client 0.7.2`.
The API request will be disappeared.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

**demo_sleep.py (gradio 3.x)**
```py
import gradio as gr
import time

def click_button() :
    time.sleep(10)
    return 'DONE'

with gr.Blocks() as demo:     
    input_text = gr.Textbox(label='input')
    button = gr.Button(value='Run')
    output_text = gr.Textbox(label='output')
    
    button.click(fn=click_button, outputs=output_text, api_name='sleep')

demo.queue(concurrency_count=1)
demo.launch()
```

**test_sleep.js (@gradio/client 0.7.2)**
```js
import { client } from "@gradio/client";
import { createRequire } from "module";
const require = createRequire(import.meta.url);
global.EventSource = require('eventsource');

const app = await client("http://127.0.0.1:7860/");
const result = await app.predict("/sleep", []);
console.log(result.data);
```
(I opened a issue #6352 about EventSource.)

Then, run the code by `node test_sleep.js` in the command.

I can't receive any output after running test_sleep.js. (The API request doesn't arrive at gradio demo.)
But, if I remove `demo.queue(concurrency_count=1)` in code, I can get the API output.

Interestingly, `@gradio/client 0.4.2` code can receive the API output even with `demo.queue()`

**test_sleep.js (@gradio/client 0.4.2)**
```js
import { client } from "@gradio/client";

const app = await client("http://127.0.0.1:7860/");
const result = await app.predict("/sleep", []);
console.log(result.data);
```

### System Info

```shell
gradio 3.50.2
@gradio/client 0.7.2
```

### Severity

I can work around it

**Comment by gibiee** [comment]
Version compatibility seems to be poor.
I found another bug between `gradio 4.x` and `@gradio/client 0.4.2`.

```
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 403
    at ClientRequest.<anonymous> (file:///C:/source/gradio_test/nodejs_client0.4.2/node_modules/@gradio/client/dist/wrapper-6f348d45.js:2813:7)
    at ClientRequest.emit (node:events:514:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at Socket.socketOnData (node:_http_client:535:22)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Readable.push (node:internal/streams/readable:286:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (file:///C:/source/gradio_test/nodejs_client0.4.2/node_modules/@gradio/client/dist/wrapper-6f348d45.js:2895:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.9.0
```

In this case, it works fine in `@gradio/client 0.7.2`.

**Comment by freddyaboulton** [comment]
I think this incompatibility is expected since the latest version of the client was shipped to support version 4. Since we made the python client compatible with 3.x, I think we can do the same for the js client. @pngwn @aliabid94

**Comment by pngwn** [comment]
I don't love the idea. It will result in a lot of unneeded code been shipped to everyone (and included in every gradio app). 

There is a version available that works with the older gradio apps, why not just use that? We can't support everything forever (nor should we imo).

**Comment by gibiee** [comment]
@freddyaboulton @pngwn 
Thank you for your comments.

I also think that solving version compatibility is too much work. Just, I hope that others don't repeat my mistakes. I spent a lot of time trying to figure out the cause. Because error message doesn't inform about version compatibility.

I will close this issue.

**Comment by pngwn** [comment]
Gonna reopen for discussion. Either we improve compatibility or we provide better messaging. It should easy to throw a helpful warning.

**Comment by pngwn** [comment]
Confirm support for 3.x for 1.x clients. cc @abidlabs

**Comment by abidlabs** [comment]
This issue is quite stale, going to go ahead and close it
