### ISSUE TITLE
Custom Components CLI improvements

### ISSUE THREAD

**Issue by duerrsimon** [gradio-app/gradio#6354]
- [x] I have searched to see if a similar issue already exists.

**Following features are still missing**  

- [x] `gradio cc publish` deployment to pypi doesn't support accounts with 2FA
- [ ] `gradio cc create` should not actually create the folder if the template isn't found
- [ ]  `pyproject.toml` could also set a few more inputs based on CLI. In oarticular the `[project]` part

```
[project]
--
  | name = "gradio_molecule3d"
  | version = "0.0.1"  # set each time cc publish is called
  | description = "Molecule3D custom component to visualize pdb or sdf files" # gradio cc create
  | readme = "README.md"
  | license = "MIT" # gradio cc create
  | requires-python = ">=3.8" # gradio cc create
  | authors = [{ name = "Simon Dürr", email = "dev@simonduerr.eu" }] # gradio cc create
  | keywords = [
  | "machine learning",
  | "reproducibility",
  | "visualization",
  | "gradio",
  | "gradio custom component",
  | "gradio-template-File",
  | "protein"
  | ] # gradio cc create
```

**Comment by freddyaboulton** [comment]
Thanks @duerrsimon ! I like the idea of optionally setting more config via the cli.

BTW `publish` already supports accounts with 2fa. Use the username `__token__`  and the password is your API key. Will make this clearer.
