### ISSUE TITLE
gr.Image(tool=...) removed in 4.0?

### ISSUE THREAD

**Issue by stefanengelmann** [gradio-app/gradio#6355]
### Describe the bug

I cannot see anywhere in your list of breaking changes that you should have removed the gr.Image(tool=..) functionality which allows you to sketch on images, but this functionality seems to have disappeared completely in version 4.0 without any warning?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Not relevant

### System Info

```shell
Not relevant
```

### Severity

Blocking usage of gradio

**Comment by stefanengelmann** [comment]
This also means that some of your demos are broken, e.g., the Pictionary App: https://huggingface.co/spaces/gradio/pictionary

**Comment by stefanengelmann** [comment]
That might very well be the case, but I am raising this issue to get a clarification on whether this is an intentional change (and if yes, why?), or not, since it is not listed as a breaking change although it is obviously breaking things

**Comment by pngwn** [comment]
We don't quite have time to get the new ImageEditor into 4.0 but you can follow that work here https://github.com/gradio-app/gradio/pull/6169

The ImageEditor is being completely rewritten and should be released over the next few days. 

This should be listed on the 4.0 breaking changes. I'll check that.

**Comment by 0xSynapse** [comment]
@abidlabs still not able to see the tool param in gr.Image in latest docs.

Am I missing something?

**Comment by abidlabs** [comment]
Hi @0xSynapse please use `gr.ImageEditor` instead!

**Comment by 0xSynapse** [comment]
Thanks, @abidlabs, I am experimenting with gradio for a clean, simple but efficient UI for OpenCV DNN, and ended up with a detailed blog about that at **LearnOpenCV** - [Integrating Gradio with OpenCV DNN](https://learnopencv.com/integrating-gradio-with-opencv-dnn/).

Maybe we can add it to the Huggingface Docs for [Using OpenCV in Spaces](https://huggingface.co/docs/hub/en/spaces-using-opencv) and add the spaces demo to the template. You can check out the space [here](https://huggingface.co/spaces/ankanxopencv/Gradio-with-OpenCV-DNN).

Thanks for the re-tweet as well.

Ankan
