### ISSUE TITLE
Ability to return no update from a function

### ISSUE THREAD

**Issue by v-g-v** [gradio-app/gradio#6357]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Would be nice to have an ability to completely avoid output component update. For example there is a function which is triggered periodically via `every=` and there is no need in update / re-render the output component if some condition is met (e.g. if the text is not changed, do not trigger update / re-render).

The example use case:
```
import time
import gradio as gr

def _update_text(text):
    text = str(time.time())
    # if some condition is met, do not update output at all (no re-rendering)
    return text

def main():
    demo = gr.Blocks()
    with gr.Blocks() as demo:
        textbox = gr.Textbox(lines=2, label="timestamp")
        demo.load(_update_text, inputs=[textbox], outputs=[textbox], every=1)
    
    demo.launch()

if __name__ == "__main__":
    main()
```

**Describe the solution you'd like**  
Ability to avoid output component update completely.

**Comment by abidlabs** [comment]
Hi @v-g-v thanks for creating this issue! You can achieve this by returning a `gr.Textbox()` from your function. 

Here's example code:

```py
import gradio as gr
import time

def _update_text(text):
    seconds = int(time.time())
    if seconds % 2 == 0:
      return gr.Textbox()
    return seconds

with gr.Blocks() as demo:
    textbox = gr.Textbox(lines=2, label="timestamp")
    demo.load(_update_text, inputs=[textbox], outputs=[textbox], every=1)

if __name__ == "__main__":
  demo.launch()
```

And you can see it running (only updating the odd numbers in the Textbox) [in the Gradio Playground here](https://www.gradio.app/playground?demo=Hello_World&code=aW1wb3J0IGdyYWRpbyBhcyBncgppbXBvcnQgdGltZQoKZGVmIF91cGRhdGVfdGV4dCh0ZXh0KToKICAgIHNlY29uZHMgPSBpbnQodGltZS50aW1lKCkpCiAgICBpZiBzZWNvbmRzICUgMiA9PSAwOgogICAgICByZXR1cm4gZ3IuVGV4dGJveCgpCiAgICByZXR1cm4gc2Vjb25kcwoKd2l0aCBnci5CbG9ja3MoKSBhcyBkZW1vOgogICAgdGV4dGJveCA9IGdyLlRleHRib3gobGluZXM9MiwgbGFiZWw9InRpbWVzdGFtcCIpCiAgICBkZW1vLmxvYWQoX3VwZGF0ZV90ZXh0LCBpbnB1dHM9W3RleHRib3hdLCBvdXRwdXRzPVt0ZXh0Ym94XSwgZXZlcnk9MSkKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgZGVtby5xdWV1ZSgpLmxhdW5jaCgp)
