### ISSUE TITLE
[Blocks] implement core architecture to support blocks (frontend)

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#636]
Rough notes/ checklist that I'm working through:

- [ ] Single internal API for blocks and interfaces to reduce code duplication + maintenance (this is being worked on in the backend to make it simpler, I'lld do something temporary on the FE if i get to it first to allow this).
- [ ] Treat all components exactly the same and render them recursively, including layout components such as tabs/rows. May require changes to JSON config will patch on the FE until changes are synced.
- [ ] Figure out internal state storage mechanism. State provided by user vs state required by components vs state sent to the API. Sometimes these are the same, sometimes they aren't.
- [ ] Mechanism for listening to and attaching triggers to events.
- [ ] Ensure components are entirely decoupled form the app. They should know nothing about gradio and deal with simple inputs + outputs (via events). 
- [ ] Define a consistent even interface for simplicity (probably start with `change` but could add a `save` or `click` event). At some point it might make sense to offer complete flexibility here but we'll start with the basics.

**Comment by abidlabs** [comment]
Closed via #807
