### ISSUE TITLE
Programatically Set choices on launch for Radio Buttons

### ISSUE THREAD

**Issue by Solomin0** [gradio-app/gradio#6362]
- [X] I have searched to see if a similar issue already exists.

Currently you are not able to set the choices by a function on startup like how it is possible to set gr.Value with the callable. 

Would it be possible to allow the choices to be passed a callable as well in order to load options from some other source? 

Currently I am able to work around using blocks.load  to populate the choices on startup but it seems clunky that you can set the value with a callable but not the actual choices the same way.

**Comment by abidlabs** [comment]
Hi @Solomin0 thanks for creating the issue. I'll let other Gradio maintainers chime in if they disagree, but I don't think we'll support using functions to assign parameters other than `value`, as it introduces additional complexities / places where bugs could be introduced, where a workaround already exists.

Typically, we prefer that there only be a single way to to achieve something in Gradio, and in this case, using `gr.Blocks.load` is the clearer approach. Using functions to assign `value` is somewhat of a special case (not sure if it was a good idea tbh) but its at least much more common that assigning other parameters.

**Comment by Solomin0** [comment]
Gotcha no worries then. I was under the impression that using gr.Blocks.load was a workaround, if that is the intended way then I'm happy to keep going with those signals.
