### ISSUE TITLE
Documentation for older versions

### ISSUE THREAD

**Issue by BramVanroy** [gradio-app/gradio#6365]
It seems that documentation is only available for the most recent stable version as well as `main` but historical documentation is not there on https://www.gradio.app/docs/interface. Would be great if people who are stuck on older versions could also find the docs somewhere.

**Comment by abidlabs** [comment]
Agreed, @aliabd is looking into this

**Comment by aliabd** [comment]
Thanks for opening the issue @BramVanroy, will add support for 3.x this week.
