### ISSUE TITLE
Implement variable widths for `blocks.Column` 

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#637]
* Backend has a `gr.Column` class but as far as I can tell, it has no effect
* `gr.Column` could take in an argument to assign column widths.

Sample code:
```python
	with gr.Column(flex=1):	
		with gr.Row():
			xray_scan = gr.inputs.Image()
			xray_results = gr.outputs.JSON()
		xray_run = gr.Button("Run")
		xray_run.click(xray_model, inputs=xray_scan, outputs=xray_results)

	with gr.Column(flex=2):
		with gr.Row():
			ct_scan = gr.inputs.Image()
			ct_results = gr.outputs.JSON()
		ct_run = gr.Button("Run")
		ct_run.click(ct_model, inputs=ct_scan, outputs=ct_results)
```

**Comment by pngwn** [comment]
@abidlabs Can you elaborate on what the argument would do exactly? Would it be optional? If so what would the default be?

**Comment by abidlabs** [comment]
Was thinking it could assign the relative width of the columns. So with the example above, the first column would take up 1/3 of the screen, while the second column would take up 2/3 of the screen. My understanding is that it is similar to the `flex` property in CSS though I may be wrong about that.

**Comment by abidlabs** [comment]
Just checked and it looks like we can use `gr.Column()`. But it doesn't look like it supports variable widths yet. Definitely not a big priority, so leaving as a `blocks` issue and renaming this issue

**Comment by abidlabs** [comment]
Also see #1029

**Comment by abidlabs** [comment]
This is being discussed in #1162 so closing this issue
