### ISSUE TITLE
Make CheckboxGroup a valid Chatbot component so bot could reply via CheckboxGroup in conversation

### ISSUE THREAD

**Issue by makermotion** [gradio-app/gradio#6372]
I would like to control the conversation sometimes via multiple choice answers by the bot based on some processing of the last input from user. But there is no native solution as far as I can see.

I would like the CheckboxGroup to be a valid Chatbot component so user can chose the options that chatbot suggests based on the some processing of the last/recent conversation.

**Comment by abidlabs** [comment]
Hi @makermotion this is a great suggestion, we're working on making the Chatbot component more flexible. cc @dawoodkhan82

**Comment by liwalayouni** [comment]
I see a lot of value on implementing this feature. please keep us posted
