### ISSUE TITLE
Audio autoplay

### ISSUE THREAD

**Issue by yusifabasovv** [gradio-app/gradio#6375]
### Describe the bug

```py
clear = gr.Button("Clear")
    with gr.Row():
        input_ = [gr.Text(interactive=True, autofocus=True)]

        output_ = [gr.Audio(format="mp3", autoplay=True)]


    clear.click(lambda: None, None, output_[0], queue=False)
    input_[0].submit(get_completion, inputs=input_, outputs=output_)
```

My gradio code is like this. Audio class has autoplay open, when I try to submit another text or clear the audio box, voice is played. I want audio box to be cleared when I submit new text

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

`clear = gr.Button("Clear")
    with gr.Row():
        input_ = [gr.Text(interactive=True, autofocus=True)]

        output_ = [gr.Audio(format="mp3", autoplay=True)]

        #input_[0].change(clear_audio_on_new_input, [], output_)
    clear.click(lambda: None, None, output_[0], queue=False)
    input_[0].submit(get_completion, inputs=input_, outputs=output_)`

### System Info

```shell
3.43.2
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @yusifabasovv I don't quite understand the issue from your description. I built a self-contained example from your code here:

```py
import gradio as gr

def get_completion(x):
    return "cantina.wav"

with gr.Blocks() as demo:
    clear = gr.Button("Clear")
    input = gr.Text(interactive=True, autofocus=True)
    output = gr.Audio(format="mp3", autoplay=True)


    clear.click(lambda: None, None, output)
    input.submit(get_completion, inputs=input, outputs=output)
    
demo.launch()
```

Where "cantina.wav" is just a random audio file in my working directory. What behavior are you observing, and what behavior are you expecting? Also I'd advise you to upgrade to Gradio 4.2.0 or the latest version of Gradio please.

**Comment by yusifabasovv** [comment]
> Hi @yusifabasovv I don't quite understand the issue from your description. I built a self-contained example from your code here:
> 
> ```python
> import gradio as gr
> 
> def get_completion(x):
>     return "cantina.wav"
> 
> with gr.Blocks() as demo:
>     clear = gr.Button("Clear")
>     input = gr.Text(interactive=True, autofocus=True)
>     output = gr.Audio(format="mp3", autoplay=True)
> 
> 
>     clear.click(lambda: None, None, output)
>     input.submit(get_completion, inputs=input, outputs=output)
>     
> demo.launch()
> ```
> 
> Where "cantina.wav" is just a random audio file in my working directory. What behavior are you observing, and what behavior are you expecting? Also I'd advise you to upgrade to Gradio 4.2.0 or the latest version of Gradio please.

The problem is if autoplay is true, clicking clear button plays the audio. The same thing happens when text.submit button is clicked by enter. Imagine the app where user writes the text, press enter and get audio as an output which is then automatically played. When user input another text and press enter, the audio in the audio box play again while new audio file are processed.

**Comment by abidlabs** [comment]
> The problem is if autoplay is true, clicking clear button plays the audio

Hmm I don't see this behavior in the example that I shared. Can you confirm if this is still an issue for you in Gradio 4.2.0?

**Comment by yusifabasovv** [comment]
I upgraded to latest (4.2.0) version and the problem was vanished. Thanks a lot!

**Comment by abidlabs** [comment]
Awesome! Hopefully the audio component looks a bit nicer too :)
