### ISSUE TITLE
use gradio api with other language and endpoint rejecting post requests

### ISSUE THREAD

**Issue by denizsincar29** [gradio-app/gradio#6377]
### Describe the bug

Hello. Is the python and js only choice to communicate with gradio apps? I hoped to be able to send a very simple post or get request and get the result, well, no success:
I got the result about impossibility to send post request. But what kind of communications does the gradio client do? Well, we are not only restricted with this 2 languages only, we have go, rust, java...
I don't even know why this problem is still not opened on the internet.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

{"detail":"This API endpoint does not accept direct HTTP POST requests. Please join the queue to use this API."}
my request:
url: "https://sangmin-openai-tts.hf.space/--replicas/tfqbk/api/tts"
content-type application/json
json payload:
```json
{
        "data": [input_text, "tts-1-1106", selected_voice]
    }
```

### System Info

```shell
well, i am not running gradio, i am trying to post request.
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @denizsincar29 you can see an example of how to connect using curl here: https://github.com/gradio-app/gradio/issues/4932#issuecomment-1793639325, although the formatting the requests is much easier if you use the Python or JS clients. We are open to supporting community-built Clients in other languages as well!

**Comment by hamzafarooq** [comment]
@abidlabs , can you please help me understand the syntax for using postman? I have been deploying using hf - testing through postman is extremely vital

previously: api/predict would work, what can I use now or is there a change that needs to be done to the code?

**Comment by cansik** [comment]
@abidlabs It's really necessary to write a guide on how to call the API from other languages (as also mentioned in https://github.com/gradio-app/gradio/issues/4932). At least a basic example for each datatype would be good (not every example).

Pre 4.0, it was possible to upload an image by using it's base64 data string, but with 4.0 I can't make it work. The image block always wan't a path, which I can't supply (because it's a base64 string).  Could you give me a hint?

**Comment by jalle007** [comment]
So you build API which doesnt work using STANDARD http protocol and POSTMAN.

What stupid ridiculous approach is that ?

**Comment by abidlabs** [comment]
@jalle007 we don't tolerate abusive behavior here, and I have blocked you as a result. For anyone else reading this thread, we actually do provide a cURL-compatible API now: https://www.gradio.app/guides/querying-gradio-apps-with-curl
