### ISSUE TITLE
[Blocks] Move all block-related imports under `gradio.blocks`

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#638]
Goal being to avoid having to write `gr.` in front of every component? 

Leading to much more readable code:

```python
from gradio import inputs, outputs
from gradio.blocks import *

with Blocks() as blocks:
	Markdown("""
	# Detect Disease From Scan
	With this model you can lorem ipsum
	- ipsum 1
	- ipsum 2
	""")
	disease = inputs.CheckboxGroup(["Covid", "Malaria", "Lung Cancer"], 
                          label="Disease to Scan For")

	with Tab("X-ray"):	
		with Row():
			xray_scan = inputs.Image()
			xray_results = outputs.JSON()
		xray_run = Button("Run")
		xray_run.click(xray_model, inputs=xray_scan, outputs=xray_results)

	with Tab("CT Scan"):
		with Row():
			ct_scan = inputs.Image()
			ct_results = outputs.JSON()
		ct_run = Button("Run")
		ct_run.click(ct_model, inputs=ct_scan, outputs=ct_results)
		
	overall_probability = outputs.Textbox()

	blocks.launch()
```

**Comment by abidlabs** [comment]
On a somewhat related note, in my mind `Block` should be singular (as in, "let me build a Gradio Block for this model" analogously to "let me build a Gradio Interface for this model"). Can we rename classes so that we write:

```python
with Block() as block:
...
block.launch()
```

instead of 

```python
with Blocks() as blocks:
...
blocks.launch()
```

Wdyt?

**Comment by FarukOzderim** [comment]
> Goal being to avoid having to write `gr.` in front of every component?
> 
> Leading to much more readable code:
> 
> ```python
> from gradio import inputs, outputs
> from gradio.blocks import *
> 
> with Blocks() as blocks:
> 	Markdown("""
> 	# Detect Disease From Scan
> 	With this model you can lorem ipsum
> 	- ipsum 1
> 	- ipsum 2
> 	""")
> 	disease = inputs.CheckboxGroup(["Covid", "Malaria", "Lung Cancer"], 
>                           label="Disease to Scan For")
> 
> 	with Tab("X-ray"):	
> 		with Row():
> 			xray_scan = inputs.Image()
> 			xray_results = outputs.JSON()
> 		xray_run = Button("Run")
> 		xray_run.click(xray_model, inputs=xray_scan, outputs=xray_results)
> 
> 	with Tab("CT Scan"):
> 		with Row():
> 			ct_scan = inputs.Image()
> 			ct_results = outputs.JSON()
> 		ct_run = Button("Run")
> 		ct_run.click(ct_model, inputs=ct_scan, outputs=ct_results)
> 		
> 	overall_probability = outputs.Textbox()
> 
> 	blocks.launch()
> ```

This is actually the case, if you check `__init__.py` you can see
`from gradio.blocks import Blocks, Column, Row, Tab`

But instead of implicit imports, explicit imports are better.
`from gradio import Blocks, Column, Row, Tab`
or
`from gradio.blocks import Blocks, Column, Row, Tab`

**Comment by FarukOzderim** [comment]
> On a somewhat related note, in my mind `Block` should be singular (as in, "let me build a Gradio Block for this model" analogously to "let me build a Gradio Interface for this model"). Can we rename classes so that we write:
> 
> ```python
> with Block() as block:
> ...
> block.launch()
> ```
> 
> instead of
> 
> ```python
> with Blocks() as blocks:
> ...
> blocks.launch()
> ```
> 
> Wdyt?

I am not sure about this, when I hear Gradio Blocks I understand a page is created with blocks(block being a tab or component). So naming feels legit to me. We are not building a block but we are building a page with blocks.

CCing all the team, @aliabd @pngwn @aliabid94 @AK391
