### ISSUE TITLE
A component disappears when you select an example input

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#6389]
### Describe the bug

The code worked fine with `gradio==3.50.2`, but not with `gradio==4.2.0`.
This doesn't seem to occur if I don't update the UI with the dropdown menu.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

reproduction Space: https://huggingface.co/spaces/hysts-debug/gradio-4-component-disappears-when-selecting-example

```python
import gradio as gr


def update_ui(task):
    return (
        gr.update(visible=task == "text"),
        gr.update(visible=task == "image"),
        gr.update(visible=task == "text"),
        gr.update(visible=task == "image"),
    )


with gr.Blocks() as demo:
    tasks = gr.Dropdown(choices=["text", "image"], value="text")
    text = gr.Textbox()
    image = gr.Image(height=400, visible=False)

    with gr.Row() as text_examples:
        gr.Examples(examples=["a", "b"], inputs=text)
    with gr.Row(visible=False) as image_examples:
        gr.Examples(examples=["dogs.jpg"], inputs=image)

    tasks.change(
        fn=update_ui,
        inputs=tasks,
        outputs=[
            text,
            image,
            text_examples,
            image_examples,
        ],
    )


if __name__ == "__main__":
    demo.queue().launch()
```

### Screenshot

https://github.com/gradio-app/gradio/assets/25161192/e41799f7-f820-4d9a-98b3-f418e07c3a2e

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.2.0
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.1
huggingface-hub: 0.18.0
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.1
numpy: 1.26.1
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.2
pillow: 10.1.0
pydantic: 2.4.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.1
huggingface-hub: 0.18.0
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Ah so this is actually an intentional change that we made in 4.0, which is that the component attributes revert to the attributes with which you constructed the component when you click on an example. In this case, you constructed `gr.Image` with `visible=False`, so when you click on an image example, `visible=False` gets set on the `gr.Image` component. The reason that we made that change was a user could change the properties of a component and then click on an example, which would no longer make sense for that component. For example, if you originally constructed a Dropdown with `multiselect=False`, and then updated it to set `multiselect=True`, the original examples would no longer work.

This is something that we should document a bit better, but otherwise there's no bug here. Here's a fix for your case:

```py
import gradio as gr


def update_ui(task):
    return (
        gr.update(visible=task == "text"),
        gr.update(visible=task == "image")
    )


with gr.Blocks() as demo:
    tasks = gr.Dropdown(choices=["text", "image"], value="text")

    with gr.Column() as text_examples:
        text = gr.Textbox()
        gr.Examples(examples=["a", "b"], inputs=text)
    with gr.Column(visible=False) as image_examples:
        image = gr.Image(height=400)
        gr.Examples(examples=["cat.jpg"], inputs=image)

    tasks.change(
        fn=update_ui,
        inputs=tasks,
        outputs=[
            text_examples,
            image_examples,
        ],
    )


if __name__ == "__main__":
    demo.queue().launch()

```

**Comment by hysts** [comment]
Ah, I see. Thanks for the explanation!
Well, it works for this simplified sample code, but it seems I need to do some significant refactoring to make my actual app work properly with gradio 4.x. Maybe I'll just stop using `visible`, split the app into small apps and use tabs instead. I wish I didn't have to do this to migrate to 4.x, but I guess it can't be helped.

**Comment by abidlabs** [comment]
Ah yeah sorry this is indeed a breaking change but one that we should stick to imo
