### ISSUE TITLE
`api_name` is set in `gr.Examples` if not specified

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#6391]
### Describe the bug

![](https://github.com/gradio-app/gradio/assets/25161192/e8958c85-89b0-495a-a28c-2db5203a1754)

The documentation of `gradio==4.2.0` says that its default is `False` and the code indeed seems so.
https://github.com/gradio-app/gradio/blob/9d6d72f44370c45d9e213421a5586c25c5789278/gradio/helpers.py#L106

But if one doesn't specify `api_name`, the endpoint is exposed with a name `/load_example`.

Weird thing is that the endpoint is not exposed if one explicitly set `api_name=False` though its default is `False`.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```py
import gradio as gr


with gr.Blocks() as demo:
    text = gr.Textbox()

    gr.Examples(examples=["a", "b"], inputs=text)
    gr.Examples(examples=["c", 'd'], inputs=text)


if __name__ == "__main__":
    demo.queue().launch()
```
When running this code, the log and the API documentation show like this:
```
/home/ubuntu/.virtualenvs/py31011/lib/python3.10/site-packages/gradio/blocks.py:890: UserWarning: api_name load_example already exists, using load_example_1
  warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`
```

![](https://github.com/gradio-app/gradio/assets/25161192/820e0f1b-ce4b-40fe-85db-cda793be0707)

On the other hand, if I run the following, it doesn't.
```py
import gradio as gr


with gr.Blocks() as demo:
    text = gr.Textbox()

    gr.Examples(examples=["a", "b"], inputs=text, api_name=False)
    gr.Examples(examples=["c", 'd'], inputs=text, api_name=False)


if __name__ == "__main__":
    demo.queue().launch()
```

### System Info

```shell
gradio==4.2.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
As an aside, we should document that if `api_name` is `False`, then downstream users cannot use that endpoint including users who may `gr.load()` that Space
