### ISSUE TITLE
Allow users to deploy to Spaces directly from the Gradio app webpage

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#6392]
It would be really integration between Gradio <> Spaces, if there was an option in the footer that allowed users to "deploy the app to Spaces" from the UI. (we already have some of the functionality implemented in the `gradio deploy` CLI command). Of course, this should not show if the app is already running on Spaces.

**Comment by abidlabs** [comment]
And perhaps to GitHub as well, cc @AK391

**Comment by freddyaboulton** [comment]
The playground is adding this feature

**Comment by abidlabs** [comment]
Yes, although it would be a nice separate feature, if you could do it from the Gradio app itself

**Comment by abidlabs** [comment]
I was thinking about including this as part of https://github.com/gradio-app/gradio/pull/10254, but actually I don't think it makes much sense since the user of the Gradio app may not be the developer. If the developer wants to deploy, they can just run `gradio deploy` so it feels redundant.
