### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by eta1232002** [gradio-app/gradio#6394]
### Describe the bug

I used the queue() , but I still get timeout after 70 seconds .. With enabled debugging, the output appears in the colab but does not appear in gradio output.. pls resolve this issue urgently

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

gr.Interface(
    title = 'Speech Recognition Gradio Web UI',
    fn=speech2txt,
    inputs="text", outputs="text",
     live=True).queue().launch(share=True,debug=True)

### System Info

```shell
yes

! pip install gradio -q
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
What version of gradio are you using? Please upgrade to the latest version of Gradio and also share the audio that you are trying as well.

**Comment by eta1232002** [comment]
I am using the last version of gradio.

This is the video I try to transcribe and it takes around 90 secs
https://www.youtube.com/watch?v=LrkFYGRVJYE

**Comment by eta1232002** [comment]
I am waiting your reply urgently

**Comment by gibiee** [comment]
I tried to reproduce this problem in Colab.
```
!pip install gradio -q

# Python 3.10.12
# gradio==4.3.0
# gradio_client==0.7.0
```

I ran the code below in Colab.
```py
import gradio as gr

def wait(input_text) :
    print(f"INPUT : {input_text}")

    total = 0
    for i in range(1000000000) :
        total  += i
    
    output = f"{total} with {input_text}"
    print(f"OUTPUT : {output}")
    return output

gr.Interface(title='TEST', fn=wait, inputs="text", outputs="text", live=True).queue().launch(share=True, debug=True)
```
(Why use `live=True`? Even if I enter "abc", only "a" is entered.)

If I run `def wait()` function alone, it takes about 145~150 seconds.
But, when I run the code, there is a bug that the same input is queued repeatedly. The process in demo never ends.
Here's a screenshot.
![repeat](https://github.com/gradio-app/gradio/assets/37574274/41595b0c-fcc6-4624-ab92-3ada753b85cf)

**Comment by gibiee** [comment]
@eta1232002 
For now, you can solve the problem by `!pip install -q gradio==3.50.2`

![solved](https://github.com/gradio-app/gradio/assets/37574274/82a6cca1-f936-404a-9259-cb7ea8b5e349)

**Comment by eta1232002** [comment]
@gibiee Thanks for your effort, it works on gradio==3.50.2
