### ISSUE TITLE
Components visibility

### ISSUE THREAD

**Issue by himanshu2721** [gradio-app/gradio#6400]
### Describe the bug

Components is not getting hidden. I am able to see the components for 10 second and then it is changing to hello world

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```py
import gradio as gr
import time

with gr.Blocks() as demo:
    markdown = gr.HTML("""<div>View Site</div>""", visible=True, show_label=False)
    new_btn = gr.Button("Generate Website", elem_id="gen-button")

def make_visible():
    markdown.visible = not markdown.visible
    time.sleep(10)
    return "hello world"

new_btn.click(make_visible, outputs=[markdown])

demo.launch(server_name="0.0.0.0", server_port=7861)
```

With the above code , what I want is on clicking button first it hide the markdown and then return the output. But it is directly returning output 

### System Info

```shell
Gradio V4.1.2
```

### Severity

I can work around it

**Comment by gibiee** [comment]
@himanshu2721 
I think you should use `.then()` method. The function can be processed step by step.

```py
# Python 3.10.12
# gradio==4.4.0

import gradio as gr
import time

def step1() :
    return gr.update(visible=False)

def step2() :
    time.sleep(10)
    return gr.update(value="hello world", visible=True)
    
with gr.Blocks() as demo :
    markdown = gr.HTML("""
                        View Site
                        """, visible=True, show_label=False)
    
    new_btn = gr.Button("Generate Website", elem_id="gen-button")
    new_btn.click(step1, outputs=[markdown]).then(step2, outputs=[markdown])
  
demo.launch(debug=True)
```

But, you should be aware that the progress bar displayed on the component cannot be seen.

**Comment by abidlabs** [comment]
Indeed @gibiee's answer is the recommended approach. Thanks @gibiee!
