### ISSUE TITLE
Gradio blocks throws a warning on duplicated method when a duplication is impossible

### ISSUE THREAD

**Issue by mangiucugna** [gradio-app/gradio#6404]
### Describe the bug

When I run my app, I get a (non-blocking) warning:
```
[..]/.venv/lib/python3.11/site-packages/gradio/blocks.py:889: UserWarning: api_name teletubbies already exists, using teletubbies_1
  warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
```

Relates to #4462

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr

def teletubbies():
    return ""

with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column(scale=2):    
            msg = gr.Textbox(label="Type here")
            submit_button = gr.Button("Send")
        msg.submit(teletubbies)
        submit_button.click(teletubbies)

if __name__ == "__main__":
    demo.launch()
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.2.0
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.1
fastapi: 0.103.2
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.0
huggingface-hub: 0.17.3
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.26.0
orjson: 3.9.7
packaging: 23.2
pandas: 2.1.1
pillow: 10.1.0
pydantic: 2.4.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.23.2
websockets: 10.4
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.9.2
httpx: 0.25.0
huggingface-hub: 0.17.3
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 10.4
```

### Severity

I can work around it

**Comment by sbarman-mi9** [comment]
Try the following:

`gr.on([msg.submit, submit_button.click], teletubbies)`


For multiple events that refer to same handler, gr.on works, which also removes that userwarning.

**Comment by mangiucugna** [comment]
ok yes, `gr.on()` doesn't throw a warning.
However from a devex perspective:

- It's unclear to me why I wouldn't be able to use the old syntax that worked in gradio3, I am calling the same function and I might want to call it with different parameters for input and output
- The warning could offer an hint that this might be the reason why, because right now it looks like someone is declaring the same function twice

**Comment by freddyaboulton** [comment]
In gradio 4.0, the `api_name` of an event is automatically inferred from the python function name. So `msg.submit(teletubbies)`, creates an api route called `/api/run/teletubbies`. If you use the same function in another event, gradio will automatically append a suffix to keep the api routes unique.

If you want to avoid the warning, set an `api_name` for the other event, e.g. `submit_button.click(teletubbies, api_name="foo")`. You don't need to use `gr.on.

**Comment by mangiucugna** [comment]
ok, maybe this should be added in the migration guide from 3 to 4? I checked to see if I missed it, it's indeed in the changelog but it was not highlighted in the migration, I presume because it's not a breaking change but an harmless warning.

Anyways I will close the issue as now I am just giving advices :)
