### ISSUE TITLE
Migration Issue 3.x.x to 4: Updating component properties from focus event of gr.Textbox makes it non-editable/selectable

### ISSUE THREAD

**Issue by sbarman-mi9** [gradio-app/gradio#6410]
### Describe the bug

Please see the code example and video. It seems a disabled replica of Textbox is overlayed which makes it non editable/selectable.  This isn't an issue with 3.42.0.

In general, I have observed inconsistent component update behaviors in others such as Sliders, Radio, Audio, Video but I couldn't record them.

Thanks.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr

def do_something():
    # change label of textbox on focus
    return gr.update(label='Changed Label of Textbox')

with gr.Blocks() as demo:
    txtbox = gr.Textbox(interactive=True, placeholder="Enter text", autofocus=False, lines=8)

    txtbox.focus(do_something, None, [txtbox], show_progress="hidden")

demo.launch(server_name="0.0.0.0", server_port=7860)
```

Here, updating the component properties of Textbox such as `label` makes it non-editable.

### Screenshot

https://github.com/gradio-app/gradio/assets/14152255/009a7e0d-b89f-49ae-b1eb-4962bee1daa3

### System Info

```shell
------------------------------
Operating System: Linux
gradio version: 4.2.0
gradio_client version: 0.7.0

------------------------------------------------

pyrhon==3.10
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Thanks @sbarman-mi9 for creating this and the other regression issues, we'll take a look!

**Comment by abidlabs** [comment]
Ok so what's happening here is that in Gradio 4.0, we set output components to be non-interactive while they are being updated. So:

1. The textbox.focus() triggers the do_something() method
2. While do_something() is executing, the textbox.focus() becomes non-interactive, which causes it to lose focus
3. After do_something() is finished, the textbox becomes interactive again, but the textbox has lost focus
4. Clicking on the textbox again triggers 1-3 again

So this is a bit of an edge case. The only solution I can think of would be to capture which element is in focus before a function is called and then restore focus after the function has finished running, but without triggering any `.focus()` events. Alternatively, if an element is in focus, we don't make it non-interactive in the first place. The latter seems simpler to implement. Curious for your thoughts @dawoodkhan82 @aliabid94 @hannahblair @pngwn

**Comment by dawoodkhan82** [comment]
I think if an element is in focus, it's perfectly logical to keep it interactive.

**Comment by abidlabs** [comment]
Sounds good to me

**Comment by dwipper** [comment]
@abidlabs Regarding the comment above "then restore focus after the function....." I have been searching around for an answer to this. Can you provide an example of how to set the focus to a component like a Textbox on a layout? I've seen how to do it with gr.Tabs(selected=) but have not been able to find out how to do this for other components.

**Comment by abidlabs** [comment]
Hi @dwipper setting focus programmatically is not possible through Gradio's Python API. I believe it should be possible with some custom `js`. You'd select the element's ID and do `.focus()`. Have you tried that?

**Comment by dwipper** [comment]
@abidlabs I've tried it with the below, and hit the wall after many hours and many permutations. While the value of the Textbox get set, the cursor does not get focused on the field. From the DOM docs, seems like it should work, but doesn't.

```
import gradio as gr

focus_js = """
    function setCmptFocus() {
        console.log("Run JS");
        var textBox = document.getElementById('text_input');
        if (textBox) {
            console.log("select focus");
            textBox.focus();
            textBox.value="test";
            return textBox.value
        }
    }
"""
with gr.Blocks() as demo:
    input_tbox = gr.Textbox(label="Input", interactive=True, elem_id='text_input', lines=1, max_lines=1)
    output_tbox = gr.Textbox(label="Output", elem_id='text_output', lines=1, max_lines=1)
    clear_btn = gr.Button(value='Clear')
    clear_btn.click(fn=None, inputs=None, outputs=[input_tbox], js=focus_js)

demo.launch(debug=True)
```
