### ISSUE TITLE
Hide `api_name` of `gr.Examples` from API docs and suppress warning for automatic renaming

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#6417]
- [x] I have searched to see if a similar issue already exists.

[internal discussion](https://huggingface.slack.com/archives/C02QZLG8GMN/p1699938988789999)

It would be nice if `api_name` of `gr.Examples` was hidden from the API docs or at least listed after all other APIs, and if the warning were suppressed for `api_name` of `gr.Examples`.

I understand from #6391 that it's used by `gr.load`, but if it's not directly used by `gradio_client`, it just clutters the API docs. Also the warnings due to automatic renaming is annoying.
```
/home/ubuntu/.virtualenvs/py31011/lib/python3.10/site-packages/gradio/blocks.py:949: UserWarning: api_name load_example already exists, using load_example_1
  warnings.warn(
/home/ubuntu/.virtualenvs/py31011/lib/python3.10/site-packages/gradio/blocks.py:949: UserWarning: api_name load_example already exists, using load_example_2
  warnings.warn(
/home/ubuntu/.virtualenvs/py31011/lib/python3.10/site-packages/gradio/blocks.py:949: UserWarning: api_name load_example already exists, using load_example_3
  warnings.warn(
/home/ubuntu/.virtualenvs/py31011/lib/python3.10/site-packages/gradio/blocks.py:949: UserWarning: api_name load_example already exists, using load_example_4
  warnings.warn(
```

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/6424
