### ISSUE TITLE
Latex rendering of currency($) and inline equations

### ISSUE THREAD

**Issue by sbarman-mi9** [gradio-app/gradio#6421]
### Describe the bug

I have been facing an issue in rendering currency `$` and inline equation `($...$)` in gr.Chatbot. It also exists in markdown component. Any text in between $ and $ is rendered as latex, so if we have both currency and inline equation such as:

`The sum of $3000 and $3000 is 6000. Example equation is $e=mc^2$`

katex.js (or whatever !) renders `$3000 and $3000` as `3000and3000` (stripping off currency symbol $). We cannot selectively turn on/off latex rendering when we have to render both currency and inline equation.

A temporary solution is to convert all equations as block equations ($$), but the readability isn't quite there. I was hoping if you have any suggestion.

 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr


with gr.Blocks() as demo:
    mkd = gr.Markdown("""
        The sum of $3000 and $3000 is 6000. Example equation is $e=mc^2$ .
    """,
    latex_delimiters=[
                    { "left": "$", "right": "$", "display": False }
                ]
    )


demo.launch(server_name="0.0.0.0", server_port=7860)
```

### Screenshot

<img width="482" alt="image" src="https://github.com/gradio-app/gradio/assets/14152255/5ef5e461-27db-424f-999e-06a0c250d2c2">

### System Info

```shell
------------------------------
Operating System: Linux
gradio version: 4.2.0
gradio_client version: 0.7.0

------------------------------------------------

python==3.10
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @sbarman-mi9, you have control over the delimiters through the `latex_delimiters` parameter, as you know, but short of that, there's no way for Gradio or Katex to know which set of `$`-signs should be rendered as LaTeX and which ones should be ignored. One potential solution is that you could use `$$` to designate the LaTeX equations, but still render them inline. This would look like this:

```py
import gradio as gr


with gr.Blocks() as demo:
    mkd = gr.Markdown("""
        The sum of $3000 and $3000 is 6000. Example equation is $$e=mc^2$$ .
    """,
    latex_delimiters=[
                    { "left": "$$", "right": "$$", "display": False }
                ]
    )


demo.launch()
```

Which renders:

<img width="459" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/0874a317-e665-4e24-a22c-bb5cad545c77">

Hope that helps!
