### ISSUE TITLE
gr.Blocks head argument not working as intended

### ISSUE THREAD

**Issue by jonathanasdf** [gradio-app/gradio#6426]
Looking at the html source for the gradio app and testing this a bit more, it seems like only the first script tag from the head is being applied

```
"""
head = """
<script>console.log('hello')</script>
<script>console.log('world')</script>
"""
with gr.Blocks(head=head):
```

![image](https://github.com/gradio-app/gradio/assets/511073/f19f7b8a-a1fc-4161-ac8c-27039cdc8d71)

Additionally, in this case it seems like the script tag is added to the head section after the page already loads, so it never gets executed? The console output is empty.

_Originally posted by @jonathanasdf in https://github.com/gradio-app/gradio/issues/5954#issuecomment-1811749402_

**Comment by abidlabs** [comment]
cc @dawoodkhan82
