### ISSUE TITLE
`gr.Examples` does not work with multiple inputs

### ISSUE THREAD

**Issue by nicolas-dufour** [gradio-app/gradio#6429]
- [ X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
When using gr.Example, one example can only be mapped to a single component
**Describe the solution you'd like**  
It would be great that when clicking an input, multiple component input could be filled with the same data

When having a list of examples (and not a list of list), we can't use multiple components as inputs. It fails with error on the type of the examples list.

**Comment by pngwn** [comment]
Could you share some example code? This should be possible.

**Comment by abidlabs** [comment]
I just confirmed that `gr.Examples` does work with multiple inputs in the latest version of `gradio` @nicolas-dufour -- you can see an example here: https://github.com/gradio-app/gradio/blob/main/demo/calculator_blocks/run.py

**Comment by nicolas-dufour** [comment]
Hey @abidlabs ,
Sorry if my message wasn't well explained but it's not the same use case. Here each example has the same length than the number of inputs component. What i would find useful is the following:

```python
    examples = gr.Examples(examples=["prompt_1", "prompt_2", "prompt_3"
                           inputs=[text_box_1, text_box_2]
                           )
```
such as that when i click on prompt_1 both text_box_1, text_box_2 components get filled with text: prompt_1. And from my test this isn't working.

**Comment by abidlabs** [comment]
Hi @nicolas-dufour yes you will need to do:

```py
examples = gr.Examples(examples=[["prompt_1", "prompt_1"], ["prompt_2", "prompt_2"], ["prompt_3", "prompt_3"]
                           inputs=[text_box_1, text_box_2]
                           )
```

That works, right?

**Comment by nicolas-dufour** [comment]
The problem is that then it visually look like this:
![image](https://github.com/gradio-app/gradio/assets/33259879/4222648a-bfeb-44ff-b2e5-e5609774232f)
where as i would like it to keep the same style as before:
![image](https://github.com/gradio-app/gradio/assets/33259879/54f5de09-57d6-4970-a8e9-f094db07ce11)

**Comment by abidlabs** [comment]
Ah yeah that's not something we support at the moment. This is actually a special case of https://github.com/gradio-app/gradio/issues/4268, so I'll go ahead and close this issue. Please follow that issue for updates
