### ISSUE TITLE
AudioButton

### ISSUE THREAD

**Issue by taoari** [gradio-app/gradio#6438]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

While there is already a gr.Audio. However, it is too large. It would be good if there could be a gr.AudioButton, similar to gr.UploadButton, so that it can be put in a single line with gr.TextBox. This is helpful for model LLM apps with audio input.

**Describe the solution you'd like**  

The following is a screenshot from Google. Something like that, a voice input button can be included.

<img width="630" alt="Screenshot 2023-11-15 at 10 16 09 AM" src="https://github.com/gradio-app/gradio/assets/3815006/9ab50140-24e8-482a-b4e3-bd53ebfa7911">

**Additional context**

**Comment by freddyaboulton** [comment]
This is a great candidate for a custom component!

I actually built something like this (not exactly like the UI shown) during the gradio 4.0 beta. It places an upload button next to a text box and sends the data together. 

https://huggingface.co/spaces/freddyaboulton/gradio_textwithattachments

Im actually planning on making this component compatible with the latest gradio 4.0 version this week. 

Stay tuned but in the meantime try to build this yourself!

**Comment by taoari** [comment]
@freddyaboulton Thank you! I just checked with your link, it is actually textbox + uploadbutton. I am expecting an audiobutton for this issue, so that something like textbox + audiobutton + uploadbutton can be achieved. You mentioned that you are working on this component, not sure if you mean "textbox + uploadbutton" or "audiobutton".

**Comment by abidlabs** [comment]
@freddyaboulton is working on the textbox + uploadbutton. 

Would you be interested in making an "audiobutton" @taoari? Let us know if that's the case and we're happy to provide suggestions!

**Comment by abidlabs** [comment]
I'll go ahead and close this issue since we are not planning to include this in the core Gradio library. But happy to help if you are interested in making this a custom Gradio component (feel free to ask questions in this issue).
