### ISSUE TITLE
Button click to open form

### ISSUE THREAD

**Issue by rmuhawieh** [gradio-app/gradio#6440]
### Describe the bug

I am trying to have it so that clicking a button opens a login form, but I continue to get the error 'Textbox has no attribute 'is_rendered'' even though I am only using gr.button and gr.button.click. Is there any reason why this is happening?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```py
import gradio as gr
import itertools
import json
from collections.abc import Iterable
from pathlib import Path
from typing import Any, TextIO


from fastapi import FastAPI
from gradio.themes.utils.colors import slate  # type: ignore

def hello_world(input):
    return('Hello' + input)

def test():
    print('hi')
    demo=gr.Interface(fn=hello_world, inputs="text", outputs="text")
    demo.launch(auth=('user', 'password'))


with gr.Blocks(
    theme=gr.themes.Soft(primary_hue=slate),
    css=".logo { "
    "display:flex;"
    "background-color: #C7BAFF;"
    "height: 80px;"
    "border-radius: 8px;"
    "align-content: center;"
    "justify-content: center;"
    "align-items: center;"
    "}"
    ".logo img { height: 25% }",
) as blocks:
    with gr.Blocks(), gr.Row():
        gr.HTML(f"<div class='logo'/><h1> privateGPT </h1></div")
        sign_in=gr.components.Button(value="Admin Sign-In", size="lg", variant='secondary', scale=0.1)
        sign_in.click(test)


def mount_in_app(app: FastAPI) -> None:
    blocks.queue()
    gr.mount_gradio_app(app, blocks, path=settings.ui.path)


if __name__ == "__main__":
    blocks.queue()
    blocks.launch(debug=False, show_api=False, auth=('user', 'password'))
```

### System Info

```shell
Not sure
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @rmuhawieh you cannot run `demo.launch()` inside of a function and trigger that from an event. The `demo.launch()` must only happen at the end of your Gradio app. 

It sounds like what you're trying to do is to have a logout/login functionality that is triggered when you click on a button.

The way I would implement this is to have two separate Gradio apps, one as a "welcome screen" of sorts with the login button. When you click on the login button, it should take you to the second Gradio app, which has the authentication form. Both apps should mounted inside of a larger FastAPI app, like you have here. 

In order to direct users to the second Gradio app when they click the button, you should use the `link` parameter of `gr.Button()` and put the URL of the second Gradio app as the link. 

Hopefully that helps! If you have further questions about this (that are not feature requests or bug reports), it is better to ask in [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)

**Comment by rmuhawieh** [comment]
Thanks for the response. Sorry I'm not able to utilize discord so I have to follow-up on here.
Here I tried to do as you said, which is create another app, and when the button is clicked, it sends us to this newly created app. But, when clicking on this button, it sends me to where the app with a JSON message saying 'detail: Not found'. Can you assist me on this issue, because I'm not understanding why the second app isn't showing. Thanks

with gr.Blocks(
    theme=gr.themes.Soft(primary_hue=slate),
    css=".logo { "
    "display:flex;"
    "background-color: #C7BAFF;"
    "height: 80px;"
    "border-radius: 8px;"
    "align-content: center;"
    "justify-content: center;"
    "align-items: center;"
    "}"
    ".logo img { height: 25% }",
) as blocks:
    with gr.Blocks(), gr.Row():
        gr.HTML(f"<div class='logo'/><img src={logo_svg} alt=PrivateGPT></div")
        sign_in=gr.components.Button(link='/admin', value="Admin Sign-In", size="lg", variant='secondary', scale=0.1)

    with gr.Row():
        with gr.Column(scale=3, variant="compact"):
            mode = gr.Radio(
                ["Query Documents", "LLM Chat", "Context Chunks"],
                label="Mode",
                value="Query Documents",
                render=False
            )
            upload_button = gr.components.UploadButton(
                "Upload a File",
                type="file",
                file_count="single",
                size="sm",
                render=False
            )
            ingested_dataset = gr.List(
                _uploaded_file_list,
                headers=["File name"],
                label="Ingested Files",
                interactive=False,
                render=False,  # Rendered under the button
            )
            upload_button.upload(
                _upload_file, inputs=upload_button, outputs=ingested_dataset
            )
            ingested_dataset.render()
        with gr.Column(scale=7):
            chatbot = gr.ChatInterface(
                _chat,
                chatbot=gr.Chatbot(
                    label=f"LLM: {settings.llm.mode}",
                    show_copy_button=True,
                    render=False,
                    avatar_images=(
                        None,
                        "https://lh3.googleusercontent.com/drive-viewer/AK7aPa"
                        "AicXck0k68nsscyfKrb18o9ak3BSaWM_Qzm338cKoQlw72Bp0UKN84"
                        "IFZjXjZApY01mtnUXDeL4qzwhkALoe_53AhwCg=s2560",
                    ),
                ),
                additional_inputs=[mode, upload_button],
            )

with gr.Blocks(
    theme=gr.themes.Soft(primary_hue=slate),
    css=".logo { "
    "display:flex;"
    "background-color: #C7BAFF;"
    "height: 80px;"
    "border-radius: 8px;"
    "align-content: center;"
    "justify-content: center;"
    "align-items: center;"
    "}"
    ".logo img { height: 25% }",
) as blocks_admin:
    with gr.Blocks(), gr.Row():
        gr.HTML(f"<div class='logo'/><img src={logo_svg} alt=PrivateGPT></div")
        

    with gr.Row():
        with gr.Column(scale=3, variant="compact"):
            mode = gr.Radio(
                ["Query Documents", "LLM Chat", "Context Chunks"],
                label="Mode",
                value="Query Documents",
                render=True
            )
            upload_button = gr.components.UploadButton(
                "Upload a File",
                type="file",
                file_count="single",
                size="sm",
                render=True
            )
            ingested_dataset = gr.List(
                _uploaded_file_list,
                headers=["File name"],
                label="Ingested Files",
                interactive=False,
                render=False,  # Rendered under the button
            )
            upload_button.upload(
                _upload_file, inputs=upload_button, outputs=ingested_dataset
            )
            ingested_dataset.render()
        with gr.Column(scale=7):
            chatbot = gr.ChatInterface(
                _chat,
                chatbot=gr.Chatbot(
                    label=f"LLM: {settings.llm.mode}",
                    show_copy_button=True,
                    render=False,
                    avatar_images=(
                        None,
                        "https://lh3.googleusercontent.com/drive-viewer/AK7aPa"
                        "AicXck0k68nsscyfKrb18o9ak3BSaWM_Qzm338cKoQlw72Bp0UKN84"
                        "IFZjXjZApY01mtnUXDeL4qzwhkALoe_53AhwCg=s2560",
                    ),
                ),
                additional_inputs=[mode, upload_button],
            )


def mount_in_app(app: FastAPI) -> None:
    blocks.queue()
    blocks_admin.queue()
    gr.mount_gradio_app(app, blocks, path=settings.ui.path)
    gr.mount_gradio_app(app, blocks_admin, path='/admin')


if __name__ == "__main__":
    blocks.queue()
    blocks.launch(debug=False, show_api=False, auth=('user', 'password'))
