### ISSUE TITLE
Auto-reload feature detects changes in various site-packages libraries, causing downstream errors

### ISSUE THREAD

**Issue by andrewrreed** [gradio-app/gradio#6443]
### Describe the bug

When using gradio with auto-reload feature, when I save a change to the app, gradio picks up random changes to specific site-packages libraries. When you then reload the gradio UI via the browser, and try to run the app, it causes backend errors.

See this thread for more details:
https://huggingface.slack.com/archives/C02QZLG8GMN/p1700090155291309?thread_ts=1700003389.105129&cid=C02QZLG8GMN

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

See this thread:
https://huggingface.slack.com/archives/C02QZLG8GMN/p1700090155291309?thread_ts=1700003389.105129&cid=C02QZLG8GMN

### System Info

```shell
gradio==4.3.0
python==3.10.11
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Please use `if gr.NO_RELOAD` as described here: https://www.gradio.app/docs/gradio/no-reload to overcome this issue
