### ISSUE TITLE
upgrade from 3.45.1 to 4.3,  with error event_trigger() got an unexpected keyword argument '_js'

### ISSUE THREAD

**Issue by luoweb** [gradio-app/gradio#6444]
### Describe the bug

upgrade from 3.45.1 to 4.3,  with error event_trigger() got an unexpected keyword argument '_js'

2023-11-16T08:31:44.723963+0800 INFO Starting ChatApp...
Traceback (most recent call last):
  File "/Users/block/code/blockai/app_chat.py", line 1348, in <module>
    chatapp.load(_js=APP_ENV_JS_CONFIG)
TypeError: EventListener._setup.<locals>.event_trigger() got an unexpected keyword argument '_js'
(grapp430) block@192 blockai % 

how to solved the problem?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

with gr.Blocks(
    title="Test",
    analytics_enabled=False,
    css=app_csslib.css,
    theme=gr.themes.Monochrome(
        primary_hue=gr.themes.colors.red, secondary_hue=gr.themes.colors.pink
    ),
) as chatapp:

chatapp.load(_js="() => { console.log('reproduction')")

### System Info

```shell
Mac OS 13
```

### Severity

I can work around it

**Comment by pngwn** [comment]
That argument has been renamed to just `js` (no underscore). Could you remove the underscore and see if that works for you?

**Comment by luoweb** [comment]
> That argument has been renamed to just `js` (no underscore). Could you remove the underscore and see if that works for you?

problem solved, thanks
