### ISSUE TITLE
no microphone found , how to solve this ? 

### ISSUE THREAD

**Issue by maceygo** [gradio-app/gradio#6446]
### Describe the bug

The browser page shows no microphone found , but sometimes it works normally. I couldn't find the reason . 
my gradio version is 4.3.0
my code is 
**audio_input = gr.Audio(sources="microphone",type='filepath')**

I have installed ffmpeg and other packages

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

audio_input = gr.Audio(sources="microphone",type='filepath')

### System Info

```shell
gradio 4.3.0
```

### Severity

Blocking usage of gradio

**Comment by maceygo** [comment]
Screenshot 
<img width="258" alt="截屏2023-11-16 11 02 45" src="https://github.com/gradio-app/gradio/assets/81661992/b068bbcd-ed3c-412d-aeed-f3dae23a7b0d">

**Comment by abidlabs** [comment]
Hi @maceygo this usually means that your browser doesn't have permissions to use the microphones. Sometimes browsers block microphone permissions, particularly if you are running http instead of https. Can you provide any more info to help us diagnose the issue?

**Comment by Jalen-Zhong** [comment]
> Hi @maceygo this usually means that your browser doesn't have permissions to use the microphones. Sometimes browsers block microphone permissions, particularly if you are running http instead of https. Can you provide any more info to help us diagnose the issue?

Hi abidlabs,
      I meet the same issuse. I set `demo.launch(server_name="0.0.0.0")` for another computer to visit my web. But the micro is not available. Of course it is normal on my own computer. Any suggestion for me to solve it?

**Comment by zengqingfu1442** [comment]
If its chrome, u can reference this blog https://www.jianshu.com/p/db50f4003ad1 .
