### ISSUE TITLE
Interface.load fails

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#6458]
### Describe the bug

When using `gr.Interface.load` to build a demo based on a model repo, it fails.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://huggingface.co/spaces/AhmedMagdy7/Jiabin99-GraphGPT-7B-mix-all as an example or just running `gr.Interface.load("huggingface/gpt2").launch()` (which is in the docs https://www.gradio.app/guides/advanced-interface-features)

### Logs

```shell
AttributeError: 'Dependency' object has no attribute 'launch'
```
```


### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.3.0
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 4.2.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.1
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.1
numpy: 1.23.5
orjson: 3.9.10
packaging: 23.2
pandas: 1.5.3
pillow: 9.4.0
pydantic: 2.5.1
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.25.1
huggingface-hub: 0.19.4
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by pngwn** [comment]
This changed in 4.0, please check the breaking changes.

**Comment by osanseviero** [comment]
This was the documented method in https://www.gradio.app/guides/advanced-interface-features

**Comment by SurAyush** [comment]
us gr.load() instead

demo = gr.load(
    "openai-community/gpt2",
    src="huggingface",
    inputs=gr.Textbox(lines=5, label="Input Text"),
    title=title,
    description=description,
    article=article,
)

demo.launch()

this works great

**Comment by BoyuHu** [comment]
@SurAyush it really helps!!! Thank you!
