### ISSUE TITLE
flag option is not working for "state" feature

### ISSUE THREAD

**Issue by yesdeepakmittal** [gradio-app/gradio#646]
I want to apply flag feature on **[Using State](https://gradio.app/getting_started/#using-state)** example but it is not working

**Comment by abidlabs** [comment]
Thanks @yesdeepakmittal for reporting this! Can you give us a quick code snippet of what you've tried? It will help us look into it.

**Comment by yesdeepakmittal** [comment]
I used the same example which is mentioned in the documentation. Just commented out the `allow_flagging="never"` line

```python
import random

import gradio as gr


def chat(message, history):
    history = history or []
    if message.startswith("How many"):
        response = random.randint(1, 10)
    elif message.startswith("How"):
        response = random.choice(["Great", "Good", "Okay", "Bad"])
    elif message.startswith("Where"):
        response = random.choice(["Here", "There", "Somewhere"])
    else:
        response = "I don't know"
    history.append((message, response))
    html = "<div class='chatbot'>"
    for user_msg, resp_msg in history:
        html += f"<div class='user_msg'>{user_msg}</div>"
        html += f"<div class='resp_msg'>{resp_msg}</div>"
    html += "</div>"
    return html, history


iface = gr.Interface(
    chat,
    ["text", "state"],
    ["html", "state"],
    css="""
    .chatbox {display:flex;flex-direction:column}
    .user_msg, .resp_msg {padding:4px;margin-bottom:4px;border-radius:4px;width:80%}
    .user_msg {background-color:cornflowerblue;color:white;align-self:start}
    .resp_msg {background-color:lightgray;align-self:self-end}
""",
    allow_screenshot=False,
    # allow_flagging="never",
)
iface.launch()
```

**Comment by abidlabs** [comment]
The problem actually seems to be much bigger. It seems like flagging is completely broken from the frontend for *all* interfaces. For example, flagging does not work for me for this Interface:

```python
gr.Interface(lambda x:x, "text", "text").launch()
```

I think the backend is fine, just that nothing happens at all when you click the flagging button in the frontend. @aliabid94 is this something you can take a look at?

**Comment by abidlabs** [comment]
As part of housecleaning, I'll go ahead and close this issue. Feel free to reopen if you are still experiencing this @yesdeepakmittal.
