### ISSUE TITLE
Support updates on gr.Group components

### ISSUE THREAD

**Issue by austin-snps** [gradio-app/gradio#6466]
[X] I have searched to see if a similar issue already exists.
I have searched issues and documentations.

**Is your feature request related to a problem? Please describe.**  
A simplified version of my problem would be the following.
I used gr.Group() to create a group of relevant elements, and would like to update its layout when a user checked a checkbox.

Example code:
```python 
with gr.Group() as group_components:
    gr.Textbox(label=f'Output 1')
    gr.Textbox(label=f'Output 2')

action_checkbox = gr.Checkbox("Change layout")
```

The layout should be changed to something else when `action_checkbox` is clicked.
What I would like to write in the code is like:

```python 
def _update_group_components(check_box_value):
    with gr.Group() as new_group_components:
        gr.Textbox(label=f'Output 1')
        gr.Textbox(label=f'Output 2')

    return new_group_components
```
and use the following to update the layout as in normal components (e.g. gr.Textbox, gr.Checkbox, that are not gr.Group components)
```python 
action_checkbox.click(
    fn=_update_group_components,
    inputs=action_checkbox,
    outputs=group_components,
)
```

**Describe the solution you'd like**  
One solution I could think of is to define a custom component similar to normal components (gr.Textbox, gr.Button, etc.).
However, with the unique structure of gr.Group and its definition, things become tricky and seem not doable at the best of my knowledge.

**Additional context**  
This is my first time posting, so I apologize if this post does not conform to any of the community guidelines. 
Please let me know and I will modify the post immediately.

**Comment by gibiee** [comment]
Would you like to check the code below? It works in Colab.

```py
# Python 3.10.12
# gradio==4.4.0

import gradio as gr

def change_group(check_value):
    if check_value : 
        return [gr.update(visible=False), gr.update(visible=True)]
    else :
        return [gr.update(visible=True), gr.update(visible=False)]

with gr.Blocks() as demo :
    with gr.Group(visible=True) as old_group:
        gr.Textbox(label='Old 1')
        gr.Textbox(label='Old 2')

    with gr.Group(visible=False) as new_group:
        gr.Textbox(label='New 1')
        gr.Textbox(label='New 2')

    action_checkbox = gr.Checkbox(label="Change layout", value=False)
    action_checkbox.input(fn=change_group, inputs=[action_checkbox], outputs=[old_group, new_group])

demo.launch(debug=True)
```

**Comment by austin-snps** [comment]
Hi [gibiee](https://github.com/gibiee)!
Thank you so much for your reply! I've tested the code, and it works under `gradio==3.50.2`, but not `3.34.0`.

However, what I was requesting or what I was asking is actually more complicated.
In a more general scenario, let's say I will have layouts (group of components) that are contingent on users' input.
```python 
with gr.Group() as group_components:
    gr.Textbox(label='Default textbox')

options_checkbox = gr.CheckboxGroup(choices=['a', 'b', 'c', 'd'])
```
Based on the checked box in `options_checkbox`, I will create different numbers of gr.Textbox components.
Would I still be able to update the layout via visibility? 
This is the case where I think having a more generalized update method would be more flexible and helpful, like this:
```python
def _update_group_components(checkbox_values):
    with gr.Group() as new_group_components:
        for choice in checkbox_values:
            gr.Textbox(label=f'textbox for {choice}')

    return new_group_components

options_checkbox .click(
    fn=_update_group_components,
    inputs=options_checkbox,
    outputs=group_components,
)
```

What do you think? Thanks!

**Comment by gibiee** [comment]
@austin-snps 
First, the example you mentioned can be resolved with the code below.

```py
# Python 3.10.12
# gradio==4.4.1

import gradio as gr

def _update_group_components(checkbox_values) :
    update_info = [gr.update(visible=False)] * 4
    for checked in checkbox_values :
        update_info[checked] = gr.update(visible=True)
    return update_info

with gr.Blocks() as demo :
    with gr.Group() as group_components :
        text1 = gr.Textbox(label='Default textbox 1')
        text2 = gr.Textbox(label='Default textbox 2')
        text3 = gr.Textbox(label='Default textbox 3')
        text4 = gr.Textbox(label='Default textbox 4')

    options_checkbox = gr.CheckboxGroup(choices=['a', 'b', 'c', 'd'], type='index', value=['a','b','c','d'])
    options_checkbox.input(fn=_update_group_components,
                           inputs=options_checkbox,
                           outputs=[text1, text2, text3, text4])

demo.launch(debug=True)
```

Is there a reason you need to change elements by groups? Or could you please provide such an example?

**Comment by gibiee** [comment]
Perhaps, it might be impossible to modify the UI dynamically.
- https://discuss.huggingface.co/t/is-it-possible-to-change-the-interface-with-a-button/45021
- https://www.gradio.app/guides/controlling-layout#variable-number-of-outputs

**Comment by abidlabs** [comment]
Hi folks! Yes currently not possible to update the UI to this level dynamically. However, we're working on something like this in this proposal: https://github.com/gradio-app/gradio/issues/4689

@austin-snps could you post the example you're interested in supporting in that issue? It will help us as we design this feature.

**Comment by austin-snps** [comment]
Hi @gibiee and @abidlabs 

Yes, of course we can use gr.update() to update visibility by creating candidate components beforehand.
Still, you are not able to adjust the layout or other settings dynamically by this approach, since the spatial relationship of components are determined at the time of creation. 
This is the reason why I think a dynamic update with customizable functions can be much more flexible when scenarios are getting complicated.
For example, 
(1) You may want to organize the selected components in grids where each row has two components
(2) You may want to create different components (instead of only textboxes) based on the combinations of the selected options. If the number of combinations become very large, pre-creating components become infeasible and inefficient, and creating components during runtime may be a better option.

In case (1), let's say we have options `'a', 'b', 'c', 'd'`, and they are created by 
```python
with gr.Row():
    gr.Textbox('Textbox a', visible=False)
    gr.Textbox('Textbox b', visible=False)
with gr.Row():
    gr.Textbox('Textbox c', visible=False)
    gr.Textbox('Textbox d', visible=False)
```
If 'a' and 'd' are selected, it should become
```
---------
| a | d |
---------
```
and then when 'c' is further selected ('a', 'c', and 'd' are selected), it should become
```
---------
| a | d |
---------
| c |   |
---------
```
Finally, when 'd' is disselected, it should become
```
---------
| a | c |
---------
```
