### ISSUE TITLE
Filebrowser is not compatible with Python < 3.10

### ISSUE THREAD

**Issue by goncaloalves** [gradio-app/gradio#6469]
### Describe the bug

The prerequisites for gradio are python 3.8+, however Filebrowser is onlycompatible with Python 3.10 and above.

That is because  on: 
File "/root/work/venv/lib64/python3.9/site-packages/gradio/components/file_explorer.py", line 193

there is the following line:
files += glob_func(result, recursive=True, root_dir=self.root)  # type: ignore

glob only started to accept the root_dir argument in python 3.10

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

use the filebrowser in an app with python 3.10.

Should return:
TypeError: glob() got an unexpected keyword argument 'root_dir'

### System Info

```shell
gradio==4.4.0
python==3.9.15
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @goncaloalves you're right! We do have an existing issue for this though, so I'll mark this closed as a duplicate: https://github.com/gradio-app/gradio/issues/5907
