### ISSUE TITLE
Running inference by tensor parallelizing the model on 8 devices ; how do I launch gradio app then and make sure that the interface fn executes on all ranks to get the final output

### ISSUE THREAD

**Issue by puneeshkhanna** [gradio-app/gradio#6479]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by puneeshkhanna** [comment]
Just to further add , I do the launch only on rank 0 device but I want the inputs and model forward call to be executed on all tensor parallel ranks hosting the full model.

**Comment by abidlabs** [comment]
Hi @puneeshkhanna, for general questions like this (that are not feature requests or bug reports), please ask in [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
