### ISSUE TITLE
Add display time and screen location params to gr.info, gr.error, gr.warning

### ISSUE THREAD

**Issue by dwipper** [gradio-app/gradio#6480]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
These pop-ups are great, but in some situations it would be a better user experience if the message cleared sooner and/or stayed longer. It would also be helpful to be able to control where on the screen message pops open.

**Describe the solution you'd like**  
1. Provide a time parameter in seconds that would control the amount of time the message is displayed.
2. Have a param provides the ability to position the message on the screen. Maybe allow a combination of top, middle, bottom, left, right, center. And/or potentially provide a control name reference, and have the message pop near that control. Would be great for field validation messages.

**Additional context**

**Comment by Gauntlet173** [comment]
Is there a hack to set the timeout to infinite in the meantime? I have some long-running things that throw errors for the users and the helpful information is gone when they come back to it.

**Comment by abidlabs** [comment]
@freddyaboulton this potentially related to your idea about controlling visibility of gr.Error

**Comment by dwipper** [comment]
@freddyaboulton Rocks!
