### ISSUE TITLE
Unclear documentation for concurrency_limit and/or missing from events

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#6485]
### Describe the bug

The doc strings say:
```
            concurrency_count: Deprecated and has no effect. Set the concurrency_limit directly on event listeners e.g. btn.click(fn, ..., concurrency_limit=10) or gr.Interface(concurrency_limit=10). If necessary, the total number of workers can be configured via `max_threads` in launch().
```

i.e. some button click can pass as another optional arg `concurrency_limit=10`

However, this never works, things like button click and textbox submit (which one would want to control) have no such argument.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

I only see concurrency_limit for blocks and interface.  Internally "events" are marked as having the arg, but I have no way to access them and that's not consistent with the deprecation example.

I looked online through all docs and can't find a single example of btn.click() with concurrency_limit or any other use except interface.

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/2249614/5cff3f33-c139-43a0-87f3-c676513e0f1e)

### System Info

```shell
gradio==4.4.1
gradio_client==0.7.0
```

### Severity

Blocking usage of gradio

**Comment by pseudotensor** [comment]
The docs for button click show the concurrency_limit as doc string says:

https://www.gradio.app/docs/button


![image](https://github.com/gradio-app/gradio/assets/2249614/0f8ace04-40ab-4031-88d0-16768a47e4fa)


but they just don't really exist!?

**Comment by abidlabs** [comment]
Hi @pseudotensor I don't understand what you mean by "but they just don't really exist!?" The `concurrency_limit` parameter should exist for every event listener. 

For example, if you run:

```py
import gradio as gr

with gr.Blocks() as demo:
    btn = gr.Button()
    text = gr.Textbox()
    
    btn.click(lambda :"Hello", None, text, concurrency_limit=10)
    
demo.launch()
```

This should work. Does it not work for you? What error do you see?

**Comment by abidlabs** [comment]
Closing as we don't have details to reproduce this, but we can reopen once we do.

**Comment by pseudotensor** [comment]
It works but tools like pycharm do not recognize the kwarg, so show up like this:

![image](https://github.com/gradio-app/gradio/assets/2249614/aa304ad8-9727-4c2f-9b6a-f7c8eedf2a6b)

and when I check on the list of args, it doesn't appear:

![image](https://github.com/gradio-app/gradio/assets/2249614/e6582846-220b-4977-96d0-5ebb5d8487e9)


So this is not pretty.

**Comment by abidlabs** [comment]
Interesting, reopening so that we can look into it. Thanks for the report!
