### ISSUE TITLE
[BUG] gradio.Image module, the method upload not work

### ISSUE THREAD

**Issue by Southpika** [gradio-app/gradio#6495]
### Describe the bug

<img width="1326" alt="image" src="https://github.com/gradio-app/gradio/assets/122620817/8dc8ffdb-75a8-4860-8cab-7960a33cbc75">
When I use gradio.Image, and set the `upload` method, but when I upload images, it does not work. 
When I use gradio.File `upload` works and when I use  gradio.Image, other method also works e.g `change`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
def img_ans(pth):
    print(pth)
    return pth

with gr.Blocks() as demo:
    imgs=gr.Image(type='filepath')
    answer_box = gr.Textbox(label='ANSWER')

    imgs.upload(img_ans,
                inputs = imgs,
                outputs = answer_box)

demo.launch()
```

### System Info

```shell
gradio version:4.2.0

device:MacbookPro M2
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @Southpika this has been fixed in the latest version of gradio -- please upgrade to `4.4.1`. Thanks!
