### ISSUE TITLE
 The gr.HTML change listener does not work when the HTML is changed by JavaScript.

### ISSUE THREAD

**Issue by myhz0606** [gradio-app/gradio#6496]
### Describe the bug

When I integrate the Gradio HTML component with JavaScript, I noticed that the HTML change listener does not work even though the HTML source code is modified by JS. I haven't found a solution for this situation. Can you help me? 
Thanks a lot!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio as gr

html = """

    <!doctype html>
    <style>
        .image_box{
            margin: auto;
            overflow: hidden;
        }
        .image_box .image-container{
            position: relative;
            width: 224px;
            height:240px;
            border: 1px solid gray;
            float: left;
            justify-content:center;
            margin-left: 10;
        }
        .image_box .image-container img {
            display: block;          
            max-height: 200px; 
            max-width: 200px;
            top: 20px;
            bottom: 20px;
            left: 12px;
            right: 12px;
            margin: auto;
            border-bottom: 1px dashed gray;

        }
        .image_box .image-container p {
            font-family: 'Times New Roman';
            text-align: center;
            font-size: xx-small;
            overflow: hidden;
            display: -webkit-box;
            -webkit-line-clamp: 3;
            -webkit-box-orient: vertical;
        }

        .image_box div .image-overlay {
            position: absolute;
            top: 8px;
            left: 8px;
            width: 208px;
            height: 224px;
            background: rgba(0, 0, 0, 0.5);
            display: none;
        }

        .image_box div.selected .image-overlay {
            display: block;
        }

        .image_box .image-container .image-overlay-content {
            position: absolute;
            top: 16px;
            left: 16px;
            width: 208px;
            height: 224px;
            color: white;
        }

    </style>
    <div class="image_box"><hr>
    <div class="image-container" onclick="toggleImageSelection(this)">
        <img src="http://www.marketingtool.online/en/face-generator/img/faces/avatar-116b5e92936b766b7fdfc242649337f7.jpg">    
        <p> 
            <span style="font-weight: bold; color: #3399">avatar-116b5e92936b766b7fdfc242649337f7.jpg</span> 
        </p>
        <div class="image-overlay">
            <div class="image-overlay-content">
                Selected
            </div>
        </div>  
    </div>
    </hr>

</div>
"""

scripts_ori = """
async () => {
   // set testFn() function on globalThis, so you html onlclick can access it
    globalThis.testFn = () => {
      document.getElementById('demo').innerHTML = "Hello"
    }
}
"""

scripts = """  
async () => {
    globalThis.toggleImageSelection = (container) => {
        container.classList.toggle('selected');
    }
}
"""

def update_html(html):
    print("hello")
    return html

with gr.Blocks() as demo:   
    input_mic = gr.HTML(html)
    demo.load(None, None, None, _js=scripts)
    input_mic.change(fn=update_html, inputs=[input_mic], outputs=[input_mic])

if __name__ == "__main__":   
    demo.launch(server_name='0.0.0.0', server_port=12345)

### Screenshot

<img width="1363" alt="Xnip2023-11-20_17-10-20" src="https://github.com/gradio-app/gradio/assets/46910628/1e580311-ca04-4df8-a9f6-cbf408fa69d7">

### Logs

```shell
Running on local URL:  http://0.0.0.0:12345

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
gradio == 3.34.0 
gradio-client == 0.2.6
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Can you try with the latest version of gradio? Gradio 4.4.1?

**Comment by myhz0606** [comment]
> Can you try with the latest version of gradio? Gradio 4.4.1?

Yes, I have tried the latest version of Gradio (v4.5.0), and I am also experiencing this issue.

**Comment by dereklll** [comment]
> How can you around it?

**Comment by abidlabs** [comment]
Thanks @pngwn for addressing this!
