### ISSUE TITLE
[Bug]:No module named 'gradio.floating'

### ISSUE THREAD

**Issue by Daydream0929** [gradio-app/gradio#6498]
### Describe the bug

Python3.11 gradio
ModuleNotFoundError: No module named 'gradio.floating'
but Python3.9 No Error
I don't know why

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio.floating

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/61659904/e60b0bdf-ab95-427d-b5b3-2c8508bc602e)

### System Info

```shell
gradio 3.32.6 
python 3.9
MacOS
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @Daydream0929 I can't reproduce this error. Can you try uninstalling gradio and installing a recent version of gradio, such as `4.4.1`?

**Comment by abidlabs** [comment]
Closing as this module does not actually exist
