### ISSUE TITLE
[BUG] Flag save all output Images under the same name (ver 1.2.4)

### ISSUE THREAD

**Issue by jiayiliu** [gradio-app/gradio#65]
When multiple output Images present, the Flag will save all images under the same name.
Test code to reproduce the bug:

```
import gradio as gr
import numpy as np

def show(x):
    return np.zeros((20,20,3)), np.ones((40,40,3))

io = gr.Interface(show, gr.inputs.Slider(4, 6, step=1), [gr.outputs.Image(label='o1'), gr.outputs.Image(label='o2')])
io.launch()
```

Expected behavior:
Images should have prefix name as their label names.

**Comment by keerthana-ceg** [comment]
I have some issue with flagging, Im having a function that takes text query and results the list of document-ids, when using allow_flagging=True in interface, only the input gets saved the output is not being saved to flagged/logs.csv path.
Below is the code:
 
`def get_search_results(search_type, query, size=30, dense_field_name='tokenized_text_embedding'):
    results = search_query(et, size, query, dense_field_name)
    return results

if __name__ == "__main__":
    iface = gr.Interface(fn = get_search_results,
                         inputs = gr.inputs.Textbox(placeholder='Enter the Search query here.....', lines=7),
                         outputs = "number",
                         layout='vertical',
                         allow_screenshot=False,
                         allow_flagging=True)
    iface.launch(inbrowser=True)`

**Comment by aliabd** [comment]
I was able to reproduce this @keerthana-ceg, I will follow up here with the fix soon.

**Comment by JonasVerbickas** [comment]
Did you manage to fix it?
