### ISSUE TITLE
Indicator in UI showing whether it's running on CPU/GPU/TPU

### ISSUE THREAD

**Issue by josephrocca** [gradio-app/gradio#650]
**Is your feature request related to a problem? Please describe.**
Speaking mostly from the perspective of an end-user of Gradio apps on Huggingface, I'm often interesting in knowing the approximate inference speed of the demos that I see, but that requires knowing what hardware the model is running on.

**Describe the solution you'd like**
It would be great to see an icon that shows what type of device the model is running on. Even better if it were possible to hover over the icon to see more details (e.g. the GPU model, if it's running on a GPU).

**Comment by abidlabs** [comment]
That's a very nice suggestion. I can see that being quite helpful, will see what we can do!

**Comment by innat** [comment]
@abidlabs by default, which accelerator is used in the gradio app? Is it CPU or GPU? Are both provided? If so, can end-user choose? Usually, a simple model does not require GPU inference but a bigger model does.

**Comment by abidlabs** [comment]
@innat the Gradio app uses whatever hardware you write your Python code to use. So when you are running locally, that could be CPU or GPU (or TPU or anything else). On Hugging Face Spaces, the default in CPU.

**Comment by abidlabs** [comment]
Thinking about this some more, the appropriate place to put this would actually be on Hugging Face Spaces, not on Gradio. I've opened an issue in the internal Spaces repo. Thanks @josephrocca for creating the issue!
