### ISSUE TITLE
Loading a private space on huggingface from a public one

### ISSUE THREAD

**Issue by nehalelkaref** [gradio-app/gradio#6509]
### Describe the bug

Hi everyone,
I was trying out `gr.load()` to load a private space through a public space.
The interface is loaded fine, however when I try to retrieve any output I get an error. I'll provide a screenshot of the logs I got on hf.
Just for the record, `gr.load()` works fine when both spaces are public but I'm hoping someone can provide me a with a fix because I need my original space to remain private for a use case.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

I'll supply the code for the **private repo** since I was testing with a dummy example

```
import gradio as gr

def greet(text):
  return text
   
with gr.Blocks() as demo:
  input = gr.TextArea()
  output = gr.TextArea()
  gr.Button().click(fn=greet, inputs=input, outputs=output)

demo.launch(debug=True)
```

The code for the public repo is

```
import gradio as gr
import os


space_key = os.environ.get('read_token')
iface = gr.load(name="user/space_name", hf_token=space_key, src='spaces')
iface.launch(show_api=False)
```

### Screenshot

<img width="924" alt="Screenshot 2023-11-19 at 23 08 58" src="https://github.com/gradio-app/gradio/assets/16616024/56207d26-ff95-4168-afa1-fe2877bf9e89">

<img width="823" alt="Screenshot 2023-11-19 at 23 07 58" src="https://github.com/gradio-app/gradio/assets/16616024/836f99fe-0ca1-4393-98a1-580b00eb458b">

### System Info

```shell
I used the standard version of Gradio 4.4.1
I believe I tried out other versions as 3.35 and 3.30.
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Thanks @nehalelkaref looks like this is the same as https://github.com/gradio-app/gradio/issues/5927, so I'll close this as a duplicate but we'll look into this!
