### ISSUE TITLE
[Question]How to close the demo after demo.launch()?

### ISSUE THREAD

**Issue by ustccs548** [gradio-app/gradio#6522]
I'm new to using gradio.
I want to implement a function where I can press the button five times and then go back to my program and continue running.
It means that after I press the button five times, the demo can be closed. But now I do not know how to close the demo after demo.launch().

**Comment by freddyaboulton** [comment]
Hi @ustccs548 ! You can call `demo.close()` after the button is pressed a total of five times. Our discord server is the best place to ask questions like this: https://discord.gg/hugging-face-879548962464493619

**Comment by ustccs548** [comment]
> Hi @ustccs548 ! You can call `demo.close()` after the button is pressed a total of five times. Our discord server is the best place to ask questions like this: https://discord.gg/hugging-face-879548962464493619
>Thank you for your answer, I want to know how to call demo.close() after demo.launch(). I tried to call demo.close() when the button is clicked by the function of gr.button.click(...).But it failed. Or can you give a reference of demo.close()?
