### ISSUE TITLE
Adjust width / height of image preview in the Image Component?

### ISSUE THREAD

**Issue by Adeel-Intizar** [gradio-app/gradio#654]
Hello, 
How can i adjust the width / height of image input in the browser instead of jupyter notebook?

Thank you

**Comment by abidlabs** [comment]
Thanks @Adeel-Intizar for creating this issue. Would you kindly add more details about what you are looking to achieve?

**Comment by Adeel-Intizar** [comment]
I created an interface of an object detection model, but the size of input and output image in the browser is small (height especially), so i was wondering if gradio supports the feature where i can increase / decrease the width/height of the input image size in the browser, i know it supports it in jupyter

**Comment by abidlabs** [comment]
Ah got it. Can you try setting `layout="vertical"` in the `Interface()` class.?

So like: `gr.Interface(... , layout="vertical").launch()`

It will make the input and output both full width. Can you let me know if that helps?

**Comment by Adeel-Intizar** [comment]
sure, I'll check it

**Comment by Adeel-Intizar** [comment]
yes, it sets the with to the fullscreen, but what i actually want to do is increase the height in horizontal layout

**Comment by Adeel-Intizar** [comment]
waiting for this feature... Thanks

**Comment by abidlabs** [comment]
Is this something we can facilitate in Blocks?

**Comment by Adeel-Intizar** [comment]
there is already an option for width and height in gr.Interface().launch(width=..., height=...), but currently it works for only jupyter notebooks, it'd be best if it can be effective in browsers as well

**Comment by rhjohnstone** [comment]
Should this solution still work? It has no effect on my app.

**Comment by abidlabs** [comment]
cc @aliabid94 @pngwn is this still the right way to solve this issue in 3.0?

**Comment by hpeiyan** [comment]
> cc @aliabid94 @pngwn is this still the right way to solve this issue in 3.0?

It's not work in 3.0.11 or 3.0.13 version

**Comment by hpeiyan** [comment]
> 

have you solved this problem?

**Comment by hpeiyan** [comment]
> Should this solution still work? It has no effect on my app.

have you solved this problem?

**Comment by Maxlinn** [comment]
For those who still concerned about the image size of the gallery, i come across one request to shrink the preview images inside the gallery, becuase the inputs are in low resolution, by default gradio stretch them to higher resolution and causes them to blur.

I tried `gallery.style(height="64px")` but i does nothing, also `"64", 64` has no effect.

Finally i found a workaround, that is, set the gallery's `elem_id` to form a css selector, and pass handwritten css to `gr.Blocks(css: str)`.

For example, i want a gallery's preview to be 64px.
```python
css = '''
div#gallery_64 div.grid {
    height: 64px;
    width: 180px;
}

<!-- this makes the gallery's height to shrink -->
div#gallery_64 > div:nth-child(3) {
    min-height: 172px !important;
}

<!-- this makes the gallery's height to shrink when you click one image to view it bigger -->
div#gallery_64 > div:nth-child(4) {
    min-height: 172px !important;
}
'''

with gr.Blocks(css=css) as demo:
    gallery_64 = gr.Gallery(label="64", elem_id="gallery_64").style(grid=(1, 4))
```

Those number of pixels are guessed by inpection, i wonder if there is a graceful way to do it.

**Comment by acupofespresso** [comment]
Refer  https://huggingface.co/spaces/runwayml/stable-diffusion-inpainting/blob/main/app.py

css='''
#image_upload{min-height:400px}
#image_upload [data-testid="image"], #image_upload [data-testid="image"] > div{min-height: 400px}
'''

image_blocks = gr.Blocks(css=css)

image = gr.Image(source='upload', tool='sketch', elem_id="image_upload", type="pil", label="Upload").style(height=400)

**Comment by msealander** [comment]
`gr.Image()` no longer seems to have a `.style()` method
