### ISSUE TITLE
ImageEditor component as an output

### ISSUE THREAD

**Issue by jcampbell05** [gradio-app/gradio#6544]
- [x] I have searched to see if a similar issue already exists.

**Describe the solution you'd like**  

The new ImageEditor is great but it cannot be used as an output, in our case we would love the ability in particular to use it's ability to display layers. So we could output the different steps our AI is doing since our pipeline is focused on enhancing images.

We could of course build our own component to handle this, but it would be great to at least have something out of the box we can use rather than have to do the whole thing.

**Additional context**

**Comment by pngwn** [comment]
It can be used as an output as far as I'm aware. Do you have a reproduction that shows the issue?

**Comment by jcampbell05** [comment]
> It can be used as an output as far as I'm aware. Do you have a reproduction that shows the issue?

Looked into this. And the documentation firstly doesn't really document any of the stuff mentioned in the PRs and when trying to use it as an output it complains about what I'm returning as it tries to look for a "layers" key

Returning the output like this doesn't seem to help either
```
{
                original: {
                    'background': original_image,
                    'layers': []
                },
                enhanced: {
                    'background': enhanced_image,
                    'layers': []
                },
            }
```

**Comment by pngwn** [comment]
The signature should be:

```python
{
  "background": Image,
  "layers": [ Image, Image ]
}
```

**Comment by jcampbell05** [comment]
> ```python
> {
>   "background": Image,
>   "layers": [ Image, Image ]
> }
> ```

But that has to be nested within the key for the name of the field, right ? Or does it just read the same key ? Meaning you can't have more than one instance
