### ISSUE TITLE
default URL

### ISSUE THREAD

**Issue by Jun-Howie** [gradio-app/gradio#6552]
### Describe the bug

Hello author, I want the default URL to be 127.0.0.1:7680/appdemo when webui starts. I haven't found any parameters that can refer to/appdemo. What should I do

### Have you searched existing issues?  🔎

- [ ] I have searched and found no existing issues

### Reproduction

```
shared.gradio_root.launch(
    inbrowser=args_manager.args.auto_launch,
    server_name=args_manager.args.listen,
    server_port=args_manager.args.port,
    share=args_manager.args.share,
    auth=check_auth if args_manager.args.share and auth_enabled else None,
    blocked_paths=[constants.AUTH_FILENAME]
)
```

### System Info

```shell
Windows10 
Gradio =3.41.2
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @Jun-Howie if you have a question regarding a webui that is built with Gradio, it is better to ask on the repo associated with the webui. If you're asking generally about serving Gradio apps on non-root paths, please read this: https://www.gradio.app/docs/mount_gradio_app

**Comment by Jun-Howie** [comment]
@abidlabs Thank you very much. I am trying the method in this document
