### ISSUE TITLE
Trimming audio changes the sample rate

### ISSUE THREAD

**Issue by mhrice** [gradio-app/gradio#6567]
### Describe the bug

When using the trimming feature on an uploaded audio file, the sample rate is changed to 8 kHz for a 44.1 kHz file. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import librosa
import gradio as gr
def ui(launch_kwargs):
  x = gr.Audio(label="audio", type="filepath")
  ...
  button.click(run, inputs=[x])
def run(audio):
  x, sr = librosa.load(audio, mono=False, sr=None)
  print(sr)
```
When I upload a 44.1 kHz mp3 file and click the button, this function prints "44100"
After trimming and clicking the button, it prints "8000"

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.7.1
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.1
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.3
pillow: 10.1.0
pydantic: 2.5.1
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.1
huggingface-hub: 0.19.4
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by tsukumijima** [comment]
@hannahblair 
I have also encountered this strange problem. I am in the process of doing so, but will report the results of my investigation.
The audio trimming function is implemented on the JavaScript (Svelte) side by sourcing the AudioBuffer obtained from WaveSurfer.js.
However, if the sample rate is not specified when WaveSurfer.js is initialized, the AudioBuffer held internally by WaveSurfer.js will be 8000Hz (which has no effect on playback, which is annoying). By the way, the sample rate supported by browsers seems to be 8000Hz.
https://github.com/katspaugh/wavesurfer.js/blob/main/src/wavesurfer.ts#L62
Specifying the correct sample rate when initializing WaveSurfer.js should fix this problem.

**Comment by tsukumijima** [comment]
@hannahblair 
Thanks for the reply.
I thought about writing a PR, but I'm having trouble figuring out how to get the sample rate of the source beforehand and how to implement it from an internal design standpoint, so I'll leave the fix to you.

In my environment, as a workaround, I have forcibly rewritten Gradio's JS dist with the following code and confirmed that it can be saved as 44100 Hz.

```python
    index_js_path = Path(gradio.__file__).parent / 'templates/frontend/assets/index-84ec2915.js'
    with open(index_js_path, 'r') as f:
        index_js = f.read()
    index_js = index_js.replace('sampleRate: 8000,', 'sampleRate: 44100,')
    with open(index_js_path, 'w') as f:
        f.write(index_js)
```

In addition, a newly discovered problem seems to be that audio that is about to be cracked may experience clipping (a momentary unpleasant noise) after trimming.

There may be a problem with the implementation of the trimming process or the WAV export process.
For your reference, I have attached a wav file that crackles when trimming (after being able to save at 44100Hz).
[0001_この電車は中央線快速八王子行きです。.wav.zip](https://github.com/gradio-app/gradio/files/13659854/0001_.wav.zip)

**Comment by tsukumijima** [comment]
As for the clipped audio, it seems to be caused by not respecting the volume of the original audio and raising the volume above the original.
By respecting the volume of the original audio and trimming it, you can avoid audio clipping (unpleasant noise).

**Comment by tsukumijima** [comment]
@hannahblair 
Upon further investigation, it seems that the problem is caused by WaveSurfer.js normalizing the audio when it loads it.
Including the sample rate issue, I think it would be better to include a process to decode the audio directly on the Gradio side to get the audio buffer, instead of getting the audio buffer from WaveSurfer.js.
https://github.com/katspaugh/wavesurfer.js/blob/main/src/decoder.ts#L8-L25

**Comment by tsukumijima** [comment]
Upon further investigation, I found that fetching data directly with fetch() and retrieving the AudioBuffer from decodeAudioData() also causes clipping, as does retrieving the AudioBuffer from WaveSurfer.js.
This may be a problem with the Web Audio API itself.

**Comment by tsukumijima** [comment]
@hannahblair 
In the end, the clipping was caused by improper processing of PCM data write in audioBufferToWav().
Created pull request. I'm not sure if this is good code for Gradio, so I'll leave it to you to decide whether you want to merge it as is or make another revised commit for reference.
https://github.com/gradio-app/gradio/pull/6826

**Comment by kexul** [comment]
Is this fixed? I'm still facing this issue with gradio 4.19.1.

**Comment by EmreOzkose** [comment]
same issue when recording microphone. Is there any update?
