### ISSUE TITLE
Unable to build gradio frontend for local development

### ISSUE THREAD

**Issue by cswamy** [gradio-app/gradio#6579]
### Describe the bug

Been trying to build frontend with instructions in `CONTRIBUTING.md` but keep getting the error below. 

`ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @gradio/app@1.14.0 build: vite build --mode production --emptyOutDir "--emptyOutDir"
Command failed with signal "SIGABRT"
sh: line 1: 65398 Abort trap: 6           pnpm --filter @gradio/app build --emptyOutDir
 ELIFECYCLE  Command failed with exit code 134.`

Tried the troubleshooting steps mentioned in `CONTRIBUTING.md` with `rm -rf node_modules/` and `rm pnpm-lock.yaml` but then get error 

`ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @gradio/theme@0.2.0 generate: pollen -c src/pollen.config.cjs
spawn ENOENT
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
 ELIFECYCLE  Command failed with exit code 1.`

I am using venv on mac with following versions:
Python `3.9.6`
Node: `v16.17.0`
pnpm: `8.8.0`

Looks like similar issue was raised with 2300 but there was no clear resolution.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

`git clone https://github.com/gradio-app/gradio.git`
`cd gradio`
`python -m venv venv`
`source venv/bin/activate`
`bash scripts/install_gradio.sh`
`bash scripts/build_frontend.sh`

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.7.1
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.2
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.3
pillow: 10.1.0
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.2
huggingface-hub: 0.19.4
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by cswamy** [comment]
I was finally able to build the frontend locally. I am not sure why this worked and considering similar issue was seen in `#2300`, will leave the issue open. Please feel free to close if this is not broadly useful.

How I got it to work (using VSCode):
1. Follow steps outlined in the `Reproduction` section above
2. Open local repo in VSCode and open the `package.json` file
3. Click on `build` under `scripts`. Hovering on `build` again shows option to `Debug Script`. Click this
4. In the debug window, you will notice that script will pause at `Paused before out of memory exception`. I stepped into this step a few times and then disconnected debug mode
5. Terminal will continue to display updates. Once done, you might have to reconnect to venv using `source venv/bin/activate`
6. Create an `app.py` file under root as outlined in `CONTRIBUTING.md` and run with `gradio app.py`
7. App will now be available on local server

**Comment by abidlabs** [comment]
Thanks @cswamy! I'll go ahead and close now
