### ISSUE TITLE
Slider & Number fields increasingly reports incorrect values above 9007199254740992

### ISSUE THREAD

**Issue by magicfixeseverything** [gradio-app/gradio#6581]
### Describe the bug

I don't see this reported as an open bug, but this person saw this error in March 2023:
https://discuss.huggingface.co/t/floating-point-precision-in-gr-slider/34616

Try entering a number like 890238189411846221 into the slider or a number field. Even if you then change the values using the up and down arrows in the slider input field, it won't match it in "On release". I noticed this error when entering a seed. If you were to enter a seed into Automatic1111 for example, for some seeds it uses a value close to it rather than the seed you entered. That makes all the difference in the world. It fails after number 9007199254740992. This also applies to the number field.

I guess this is a general issue with things:
https://www.google.com/search?q=9007199254740992+error

Enter a seed like:
890238189411846221

And you get:
890238189411846300

I was initially going to say this is an issue you can work around, but not actually. It submits the wrong value in the form. Enter "890238189411846221" and the output is "890238189411846300". You simply can't use some numbers greater than 9007199254740992. If you want an app to allow numbers that high, you can't use the slider or number fields.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```import gradio as gr

def identity(x, state):
    state += 1
    return x, state, state

with gr.Blocks() as demo:
    gr.Markdown("Try entering a number like 890238189411846221 into the slider. Even if you then change the values using the up and down arrows in the slider input field, it won't match it in \"On release\". I noticed this error when entering a seed. If you were to enter a seed into Automatic1111 for example, for some seeds it uses a value close to it rather than the seed you entered. That makes all the difference in the world. It fails after number 9007199254740992.")
    slider = gr.Slider(0, 999999999999999999, step=1)
    state = gr.State(value=0)
    with gr.Row():
        number = gr.Number(label="On release")
        number2 = gr.Number(label="Number of events fired")
    slider.release(identity, inputs=[slider, state], outputs=[number, state, number2], api_name="predict")

if __name__ == "__main__":
    print("here")
    demo.launch()
    print(demo.server_port)```

### Screenshot

_No response_

### Logs

_No response_

### System Info

```shell
gradio environment
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.5.0
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.1
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.3
pillow: 10.1.0
pydantic: 2.5.1
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.1
huggingface-hub: 0.19.4
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @magicfixeseverything yes this is indeed an issue. Its actually related to this other issue here: https://github.com/gradio-app/gradio/issues/5354. I'll mark this as a duplicate, please follow that issue for updates
