### ISSUE TITLE
Press the button once, corresponding to multiple times

### ISSUE THREAD

**Issue by Zilong01** [gradio-app/gradio#6583]
### Describe the bug

A button was defined and a function was bound using 'click'. When I click this button, it will trigger this function multiple times.
How to prevent buttons from being continuously pressed？

I try to figure it out by add ‘queue’ and 'every', but it seems to make it run once per second instead of only run once.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

fankui_btn = gr.Button("submit fankui") 
fankui_btn.click(fn=fankui, inputs=[sender, ask_question_content,fankui_type_radio, fankui_text, output], outputs=None, queue=True, every=1.0)

### System Info

```shell
gradio==3.50.2
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @Zilong01 if I understand your question correctly, you'd like to disable the button after it has been clicked? You can do that by return `gr.Button(interactive=False)` from your function and setting that same button as one of the outputs of your function. Something like this:

```py
import gradio as gr

def example_fn():
    return gr.Button(interactive=False)

with gr.Blocks() as demo:
    btn = gr.Button("abc")
    btn.click(example_fn, None, btn)
    
demo.launch()
```

**Comment by Zilong01** [comment]
It's not like that. Clicking a button will execute the function multiple times, which will result in an error. Is there a setting that allows buttons to be clicked only once within 1 second (or other optional time period) to prevent frequent function calls due to continuous clicks.

**Comment by abidlabs** [comment]
Hi @Zilong01 if you are using Gradio 4.x, then it is possible to do this by setting the `trigger_mode` of the `click()`. If you set it to `once`, which is actually the default in Gradio 4.x, then you will not see this issue, since a user can only run the function once. I think that should solve your issue.

I'm going to reopen this since we don't really talk about this in the guides and it is not documented in the event listeners in the docs page. cc @aliabd @dawoodkhan82

**Comment by Zilong01** [comment]
> Hi @Zilong01 if you are using Gradio 4.x, then it is possible to do this by setting the `trigger_mode` of the `click()`. If you set it to `once`, which is actually the default in Gradio 4.x, then you will not see this issue, since a user can only run the function once. I think that should solve your issue.
> 
> I'm going to reopen this since we don't really talk about this in the guides and it is not documented in the event listeners in the docs page. cc @aliabd @dawoodkhan82

Thank you. But in fact, I hope users can click this button multiple times, but I don't want them to click continuously in a short period of time (possibly due to uncontrollable continuous clicks caused by the mouse [hardware] or browser [software])

**Comment by Zilong01** [comment]
> Hi @Zilong01 if you are using Gradio 4.x, then it is possible to do this by setting the `trigger_mode` of the `click()`. If you set it to `once`, which is actually the default in Gradio 4.x, then you will not see this issue, since a user can only run the function once. I think that should solve your issue.
> 
> I'm going to reopen this since we don't really talk about this in the guides and it is not documented in the event listeners in the docs page. cc @aliabd @dawoodkhan82

Thank you. But in fact, I hope users can click this button multiple times, but I don't want them to click continuously in a short period of time (possibly due to uncontrollable continuous clicks caused by the mouse [hardware] or browser [software])

**Comment by abidlabs** [comment]
Just to clarify, this *does* allow the user to click the button again, but only after the function has finished running. 

If you still want to do a manual approach where you disable the button e.g. for 1 second, then you could attach another event listener that disables your button for 1 second, like this:

```py
import gradio as gr
import time

def main_fn():
    ...

def disable_fn():
   time.sleep(1)
   return gr.Button(interactive=True)

with gr.Blocks() as demo:
    btn = gr.Button("abc")
    btn.click(main_fn, ...)
    btn.click(lambda :gr.Button(interactive=False), None, btn).then(enable_btn, None, btn)
    
demo.launch()
```

**Comment by Zilong01** [comment]
> Just to clarify, this _does_ allow the user to click the button again, but only after the function has finished running.
> 
> If you still want to do a manual approach where you disable the button e.g. for 1 second, then you could attach another event listener that disables your button for 1 second, like this:
> 
> ```python
> import gradio as gr
> import time
> 
> def main_fn():
>     ...
> 
> def disable_fn():
>    time.sleep(1)
>    return gr.Button(interactive=True)
> 
> with gr.Blocks() as demo:
>     btn = gr.Button("abc")
>     btn.click(main_fn, ...)
>     btn.click(lambda :gr.Button(interactive=False), None, btn).then(enable_btn, None, btn)
>     
> demo.launch()
> ```

Thank you for your ideas. I think I have solved this problem. After each button is clicked, disable it first, then perform the corresponding action on the button, and finally restore the button to usable.
this is a demo code:
```python

def disable_btn_fn():
    return gr.Button(interactive=False)
def enable_btn_fn():
    return gr.Button(interactive=True)

abtn.click(disable_btn_fn, None, abtn).then(fn=some_fn, inputs=[A, B], outputs=C, concurrency_limit=1, trigger_mode="once").then(enable_btn_fn, None, abtn)

```
