### ISSUE TITLE
How to set the button to only be clicked once within a certain period of time？

### ISSUE THREAD

**Issue by Zilong01** [gradio-app/gradio#6586]
### Describe the bug

Clicking a button will execute the function multiple times, which will result in an error. Is there a setting that allows buttons to be clicked only once within 1 second (or other optional time period) to prevent frequent function calls due to continuous clicks.

I called the function to write to the database in the function bound by the button. Now I find that every time I click the button, 3-4 write operations will continue to be triggered, but I only click the button once. How to set up to discard extra clicks (even though I only clicked once in actual operation)? Please note that I still need to make the next request in a few seconds.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
def fankui(userid, ask_text, type, fankui_text, ans):
    # execute sql 
    
    # prompt
    gr.Info("execute success")
    return 

fankui_btn = gr.Button("submit") 
fankui_btn.click(fn=fankui, inputs=[sender, ask_question_content,fankui_type_radio, fankui_text, output], outputs=fankui_btn, queue=True, every=1.0)
```

### System Info

```shell
gradio==3.50.2
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @Zilong01 please do not create multiple issues for the same problem. We can reopen the original issue if needed.
