### ISSUE TITLE
Connection errored out.

### ISSUE THREAD

**Issue by xiao1ongbao** [gradio-app/gradio#6591]
### Describe the bug

longer processing time using interface in a docker build. works fine locally. is there any recent changes? is there a gradio version I can revert back to?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

longer processing time using interface

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 3.48.0
gradio_client version: 0.6.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.6.1 is not installed.
httpx: 0.25.1
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.3
pillow: 10.1.0
pydantic: 2.5.1
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.1
huggingface-hub: 0.19.4
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @xiao1ongbao there's no repro so I can't really reproduce. I would suggest upgrading to the latest version of Gradio, 4.7.1. 

I'll close this issue for now. But if you provide a minimal code example that we can use to reproduce the issue, we can reopen the issue. See: https://stackoverflow.com/help/minimal-reproducible-example
