### ISSUE TITLE
Could not create share link. Missing file: C:\Users\chenc\PycharmProjects\pythonProject\venv\lib\site-packages\gradio\frpc_windows_amd64_v0.2.

### ISSUE THREAD

**Issue by ccl-private** [gradio-app/gradio#6594]
### Describe the bug

the file is in the path, but it is still called Missing file.
![image](https://github.com/gradio-app/gradio/assets/36214675/f7ab5f9d-c623-4bfc-9744-9228de802d80)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

# Create a Gradio interface
iface = gr.Interface(
    fn=segment_and_replace_bg,  # Function to be called for segmentation and background replacement
    inputs=[
        gr.Image(label="Input Image"),
        gr.ColorPicker(label="Background Color", value="#FFFFFF")  # Default is white
    ],
    outputs=gr.Image(),  # Output component for segmented image with replaced background
    live=False  # Disable live updates
)

# Launch the Gradio interface
iface.launch(share=True)

### System Info

```shell
windows 11
gradio 4.7.1
```

### Severity

I can work around it

**Comment by yichuan1998** [comment]
请问解决了吗

**Comment by abidlabs** [comment]
Hi @ccl-private please use this issue so that we can consolidate all of the discussions in one area: https://github.com/gradio-app/gradio/issues/3677
