### ISSUE TITLE
Add Copy response to the ChatInterface()

### ISSUE THREAD

**Issue by gwhale** [gradio-app/gradio#6599]
https://www.gradio.app/docs/chatinterface

The chatinterface solution is great for chat flow but it actually doesn't allow for the easy copying of text in the chat in the UI or even selecting of text. This is a feature that is required for many use cases.

**Comment by abidlabs** [comment]
Hi @gwhale you can customize the `gr.Chatbot` that is used in your `gr.ChatInterface` by passing in an instance of `gr.Chatbot` as the `chatbot` argument. This means you can set `show_copy_button=True` if you'd like! Here's an example:

```py
import gradio as gr

chatbot = gr.Chatbot(show_copy_button=True)

gr.ChatInterface(lambda message, history: message, chatbot=chatbot).launch()
```

which produces this:

```
import gradio as gr

chatbot = gr.Chatbot(show_copy_button=True)

gr.ChatInterface(lambda message, history: message, chatbot=chatbot).launch()
```
