### ISSUE TITLE
in a gr.Blocks, the maximum number of columns that want to appear side-by-side is four. How to overcome this?

### ISSUE THREAD

**Issue by thesoulpole** [gradio-app/gradio#6600]
### Describe the bug

When I want to have 5 columns side by side, only 4 appear even on a wide screen/monitor. the 5th wraps and displays below the first four. I see no indication in the docs that this is intentional, nor how to force them to not wrap. Code, screenshot below

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio as gr

def update_images(choice):
    image_urls = ["https://bi.im-g.pl/im/3f/0a/1d/z30453567NWCR.jpg?timestamp=1701200309942khlona" for _ in range(6)]
    return image_urls

with gr.Blocks() as demo1:
    with gr.Row():
        for i in range(5):
            with gr.Column():
                dropdown = gr.Dropdown(label=f"Column {i+1}", choices=["Option 1", "Option 2", "Option 3"])
                images = [gr.Image() for _ in range(6)]
                dropdown.change(update_images, inputs=[dropdown], outputs=images)

demo1.launch()

### Screenshot

<img width="1072" alt="image" src="https://github.com/gradio-app/gradio/assets/28165922/0c98021f-8116-4474-9afc-ecb937907c87">

![image](https://github.com/gradio-app/gradio/assets/28165922/e95cbc30-db6e-47c6-be46-5d9f516d3951)

### System Info

```shell
am using gradio 4.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @thesoulpole, that's because `gr.Column()` has a `min_width` of 320 pixels by default. You can change this by setting in your own `min_width` or even setting it to 0 when you instantiate your [`gr.Column`](https://www.gradio.app/docs/column).

So instead of 

```py
with gr.Column():
```

you could do:


```py
with gr.Column(min_width=200):
```

Just keep in mind, that this may result in your UI looking rather tight on mobile devices.

**Comment by abidlabs** [comment]
Not by default, but you may be able do this using custom CSS, as described here: https://www.gradio.app/guides/custom-CSS-and-JS

By the way, for general questions like this (that are not feature requests or bug reports), please ask in our [our Discord](http://discord.gg/feTf9x3ZSB).
