### ISSUE TITLE
in gradio 4 server/UI, return of gr component update is ignored for all but one component

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#6608]
### Describe the bug

return of gr component does not update the value of all components

I can work around specific issue, but I cannot tell how extensive the issue is.  Might be quite bad in general.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    chatbot2 = gr.Chatbot()
    chatbot3 = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.Button("Clear")

    def user(user_message, history):
        return "", history + [[user_message, None]]

    def bot(history):
        bot_message = ' '.join(['a'] * 100000)
        history[-1][1] = bot_message
        yield history, history, history

    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        fn=bot, inputs=chatbot, outputs=[chatbot, chatbot2, chatbot3], api_name='bot',
    )
    def clear_func():
        return tuple([gr.Chatbot(value=[])]*3)
    clear.click(fn=clear_func, outputs=[chatbot, chatbot2, chatbot3], api_name='clear')

demo.queue()
demo.launch()
```

submit some text, then hit clear.  Only first chatbot clears.

I can work-around by doing instead:
```
return tuple([[])]*3)
```
i.e. avoid gr.Chatbot().

This used to work for gradio 3.

### System Info

```shell
gradio==4.7.1
gradio_client==0.7.0
```

### Severity

I can work around it

**Comment by pseudotensor** [comment]
This is still blocking my upgrade to gradio 4.  I really tried hard to make all the gradio 4 changes, and I had to go back due to this.  Please fix!  Thanks.

**Comment by abidlabs** [comment]
Hi @pseudotensor we will take a look at this issue, but in the meantime, have you seen my suggested workaround above? Its a quick fix which seems to work

**Comment by pseudotensor** [comment]
Hi, the work around is not general enough.  I have like 4000 lines of gradio code and I cannot be sure the extent to which things are affected and I wouldn't want to do a short-term work around when probably the problem is more extensive than the simple case I shared.

**Comment by abidlabs** [comment]
Fair enough, we'll look into it!
