### ISSUE TITLE
gradio 4 UI locks up when components become active with generators

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#6609]
### Describe the bug

In gradio 4 only, for objects like chatbot, once streaming some response, can't navigate anywhere to any other tabs or scroll the scroll bar of the chat window.  Everything gets stuck in UI when the component or backend is busy.

Absolutely no problems in gradio 3 with this.  Never seen before until using gradio 4

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Working on repro.  Doesn't happen in simplest case of fake streaming.

Happens in h2oGPT, e.g. when doing chatbot, and zephyr is streaming in background in some transformers streaming thread.  Even when nothing being updated in the chatbot text window (say some prompting is off and nothing yielded) still everything locks up in UI.  Can't scroll, click other tabs, etc.

Might be related to this in gradio 3: https://github.com/gradio-app/gradio/issues/6100 and maybe https://github.com/gradio-app/gradio/issues/5914

But this problem is super persistent and reproducible and much worse in terms of not being able to go anywhere.

### Screenshot

You can see me clicking on tabs, can't reach until the chatbot generation is complete.  Even though really nothing is yielded, just the fact that a generator is going is enough to cause issue.

https://github.com/gradio-app/gradio/assets/2249614/b9212c7b-3cf9-4e4c-9d24-9d69a3387ce7

### System Info

```shell
gradio==4.7.1
gradio_client==0.7.0
```

### Severity

Blocking usage of gradio

**Comment by pseudotensor** [comment]
Here's video of the above after entering "Who are you?" and changing to `max_new_tokens=900,` to avoid unrelated problems.

There are many issues:
* Within few seconds, UI locks up.  Scroll, clicking the other tab, etc. all fail to work.  streaming no longer updates, even though if I add a print to gradio code I can see it working.
* A bit later, the gradio server also hangs while streaming
* Right after the gradio server hangs, the web browser complains about hanging



https://github.com/gradio-app/gradio/assets/2249614/ad0156be-b66b-42c2-b966-b9417856d312

**Comment by pseudotensor** [comment]
If one does `max_new_tokens=100,` to avoid too much output, then the UI freezes, but eventually recovers like in the h2oGPT case.

**Comment by pseudotensor** [comment]
My guess is that this is a worsened version of https://github.com/gradio-app/gradio/issues/5914 .  That is, the https://github.com/gradio-app/gradio/issues/5914 issue does not exactly reproduce without some more extreme setup compared to h2oGPT.  Some various component selections in h2oGPT make it particular more sensitive to these hanging issues for whatever reason.  But the repros given in this and the other issue should be enough to understand the problems and fix it generally without needing an exact apples-apples repro with what happens in h2oGPT.  It makes using h2oGPT a very bad UX.

**Comment by pseudotensor** [comment]
If the accumulation of entirely new messages is too much, perhaps it's possible to add true streaming to gradio, like audio is done, where only new chunks are passed back instead of the entire history each yield.

Still, I don't think it's alot of info and shouldn't kill the UI code, but it would be alot more efficient if gradio handled the appending of new chunks on the UI side instead of getting the full history on every  update.

**Comment by pseudotensor** [comment]
Also, just FYI, I confirmed that gradio3.50.2 works flawlessly with this repro and has no issues.

```
conda create -n gradio3
conda activate gradio3
conda install python=3.10
export PIP_EXTRA_INDEX_URL="https://download.pytorch.org/whl/cu118"
pip install gradio==3.50.2 transformers torch
python test.py
```

Never hangs, the UI keeps up with the server without any lag, etc.  gradio 3 isn't perfect as the other 2 issues show, but this is much much worse.

**Comment by aliabid94** [comment]
Taking a look!

**Comment by pseudotensor** [comment]
Any update?  I gave full repro.

**Comment by pseudotensor** [comment]
This is still blocking my upgrade to gradio 4.  I really tried hard to make all the gradio 4 changes, and I had to go back due to this.  Please fix!  Thanks.

**Comment by pseudotensor** [comment]
gradio 3 is by far superior here and gradio4 can't be used for any real streaming.  When can this be fixed?  Still repros on latest gradio.

**Comment by pseudotensor** [comment]
@aliabid94 any progress?

**Comment by aliabid94** [comment]
Sorry I didn't get back earlier, had been working on some other bugs. Taking a look now, will have an update today

**Comment by aliabid94** [comment]
In your reproduction code, it seems like the output is an unreasonably large amount of characters per second, which is causing issues. I modified the bot msg code to be as follows:
```
    def bot(history):
        import time
        message = history[-1][0]
        history[-1][1] = ''
        i = 0
        for msg in predict(message, history):
            i += 1
            len_history = sum([len(usr_msg) + len(bot_msg) for usr_msg, bot_msg in history])
            print("out", i, time.time(), len_history)
            history[-1][1] += msg
            yield history
```

And within seconds there were millions of characters of text generated. I'll keep looking into performance issues but I think there's some bug with the way you are generating and appending content. If I take your code and modify it as such:
```
import gradio as gr
from threading import Thread
import time

def predict(message, history):
    partial_message  = ""
    for new_token in ["Hello, world!"] * 1000:
        time.sleep(0.01)
        if new_token != '<':
            # partial_message += new_token
            yield new_token


with gr.Blocks() as demo:
    with gr.Tab("Chat"):
        chatbot = gr.Chatbot()
        msg = gr.Textbox()
        clear = gr.Button("Clear")
    with gr.Tab("Other"):
        msg2 = gr.Textbox()

    def user(user_message, history):
        return "", history + [[user_message, None]]

    def bot(history):
        message = history[-1][0]
        history[-1][1] = ''
        for msg in predict(message, history):
            history[-1][1] += msg
            yield history

    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        fn=bot, inputs=chatbot, outputs=chatbot, api_name='bot',
    )
    clear.click(lambda: None, None, chatbot, api_name='clear')

demo.queue()
demo.launch()
```

It works fine, where the prediction function is generating several hundred tokens per second.

**Comment by pseudotensor** [comment]
@aliabid94 The repro code is just a way to give you a reproduction of the same issue I see that has no such excessive text.

The key is that gradio 3 works fine, but gradio 4 does not.  Please check again and consider what the purpose of the repro code is.
