### ISSUE TITLE
Updating the ImageEditor brush color with `gr.update` does not work

### ISSUE THREAD

**Issue by stefanengelmann** [gradio-app/gradio#6611]
### Describe the bug

When values of gr.ImageEditor() are updated, e.g. changing the default brush color (see reproduction example), the entire component is reset, which I assume is not intended

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

    import gradio as gr
    
    with gr.Blocks() as demo:
        img = gr.ImageEditor(brush=gr.components.image_editor.Brush(default_color=("rgb(50, 200, 200)"),color_mode="fixed"),interactive=True)
    
        change_color = gr.Button(
                    value='Change color',
        )
    
        change_color.click(
            fn=lambda: gr.update(brush=gr.components.image_editor.Brush(default_color=("rgb(200, 200, 50)"))),
            inputs=None,
            outputs=img
            )

    demo.launch(height=1024)

### System Info

```shell
gradio 4.7.1
```

### Severity

Blocking usage of gradio

**Comment by pngwn** [comment]
I may have fixed this at some point but will double check.

**Comment by pngwn** [comment]
I checked this and it is no longer the case but the brush color isn't actually updating. So I'll edit the title.
