### ISSUE TITLE
`.upload` function executes immediately, not respecting the queue

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#6612]
### Describe the bug

When the `.upload()` method of components such as `gr.Image()` is called, its events don't respect the queue/the `default_concurrency_limit()` preference and execute the actions immediately 

This is a regression from Gradio 3.x (noticed the issue updating a Space from 3.x to 4.x)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

I've set up a minimal reproduction Space here: https://huggingface.co/spaces/multimodalart/replicate
Code:
```py
import gradio as gr
import time
def update(name):
    time.sleep(25)
    return f"Welcome to Gradio!"

def test():
    return("test")

with gr.Blocks() as demo:
    gr.Markdown("Start typing below and then click **Run** to see the output.")
    with gr.Row():
        inp = gr.Image()
        out = gr.Textbox()
        out_test = gr.Textbox()
    btn = gr.Button("Run")
    inp.upload(fn=test, outputs=out_test)
    btn.click(fn=update, inputs=inp, outputs=out)

demo.queue(default_concurrency_limit=1)
demo.launch()
```

To get the (un)desired behavior, you can first hit "run", while running, you can swap the image. Now, the `.upload()` is triggered, and executes its actions immediately, as opposed to waiting in queue until the update() function is finished. Here's a video of the behavior

https://github.com/gradio-app/gradio/assets/788417/a1bb88cc-b6d6-41cc-a611-80a6b4b92f87

You can see that the `update` function runs, even though my `default_concurrency_limit` is `1`. 
If I explicitly set `queue=False` or `concurrency_limit=None` in the `.upload()` it still does not respect the queue and runs in parallel. 

### System Info

```shell
`gradio==4.7.1`
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
This is actually the expected behavior in 4.x. Each event runs in it's own concurrency group and `default_concurrency_limit` controls the number of events that run concurrently in each group. 

In order to place events in the same concurrency group, you can use the concurrency_id parameter.

```python
import gradio as gr
import time
def update(name):
    time.sleep(25)
    return f"Welcome to Gradio!"

def test():
    return("test")

with gr.Blocks() as demo:
    gr.Markdown("Start typing below and then click **Run** to see the output.")
    with gr.Row():
        inp = gr.Image()
        out = gr.Textbox()
        out_test = gr.Textbox()
    btn = gr.Button("Run")
    inp.upload(fn=test, outputs=out_test, concurrency_id="fn")
    btn.click(fn=update, inputs=inp, outputs=out, concurrency_id="fn")

demo.queue(default_concurrency_limit=1)
demo.launch()
```
![concurrency_id](https://github.com/gradio-app/gradio/assets/41651716/4d482681-f7f8-43aa-bb62-90b0d4ec7f4f)


Going to cc @aliabid94 and @abidlabs for their thoughts.

**Comment by abidlabs** [comment]
Yup that looks like the expected behavior to me 👍

**Comment by apolinario** [comment]
That is a big breaking change of how the queue works from `3.x` and to me that is not clear in the docs that "concurrency groups" were a thing. What counts as a concurrency group? 

Also I had an understanding that `default_concurrency_limit` should have behaved similarly to the old `concurrency_count` exactly so you don't need to set one param per event - so the fact that it is not per event, but "per group" is new to me, and circles back to the main question of what counts as a group.
