### ISSUE TITLE
dom.js:238 Uncaught (in promise) DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#6613]
### Describe the bug

Just normal use, but sometimes just hangs with no backend reason, pure UI issue it seems.

The UI processing progress freezes and UI entirely gets stuck.  Shows the Uncaught exception.  Does that help?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

unsure as of yet.

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/2249614/91c0fdd7-cab1-4b74-9f04-b217947bd81c)

### System Info

```shell
gradio==3.50.2
gradio_client==0.6.1
```

### Severity

Blocking usage of gradio

**Comment by pseudotensor** [comment]
https://stackoverflow.com/questions/55523406/how-to-solve-uncaught-in-promise-domexception-error

Maybe bug in svelte?

**Comment by pseudotensor** [comment]
Same failure in both chrome and firefox.

**Comment by zldrobit** [comment]
Maybe you could downgrade `gradio` to 3.40 or 3.41 according to https://github.com/gradio-app/gradio/issues/4922#issuecomment-1736572096.

**Comment by pseudotensor** [comment]
Maybe, thanks for link.  However, I'm hoping to upgrade to latest gradio 4 after they put in various critical to crucial fixes.

**Comment by pseudotensor** [comment]
Closing since I assume priority is gradio4.  I hope my gradio4 issues with full repro can be fixed.
