### ISSUE TITLE
`gr.Examples` cannot display 2 images with proper layout

### ISSUE THREAD

**Issue by Vincentqyw** [gradio-app/gradio#6620]
### Describe the bug

Hi, I'm using the `gr.Examples` function from gradio==3.35.2 to display two images of different sizes, and they can be aligned properly as shown in the image below.

![image](https://github.com/gradio-app/gradio/assets/18531182/84749026-59a1-4f49-9815-5d8c6196c8b9)

However, when I upgrade gradio to 4.7.1, the images are displayed as shown in the image below. They are not aligned well within the table and exceed the table's boundaries. Could you please advise on how to address this issue? Thank you for your response.

![image](https://github.com/gradio-app/gradio/assets/18531182/823a936d-3f93-4ff5-804b-5584cf52cf7b)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Code snippet is:

https://github.com/Vincentqyw/image-matching-webui/blob/963beb9192c228abe428d192091e423861aad1bf/app.py#L211-L221
``` python
gr.Examples(
    examples=gen_examples(),
    inputs=inputs,
    outputs=[],
    fn=run_matching,
    cache_examples=False,
    label=(
        "Examples (click one of the images below to Run"
        " Match)"
    ),
)
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.7.1
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.1.0
altair: 5.0.1
fastapi: 0.104.1
ffmpy: 0.3.0
gradio-client==0.7.0 is not installed.
httpx: 0.24.1
huggingface-hub: 0.15.1
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.1
numpy: 1.23.5
orjson: 3.9.1
packaging: 23.1
pandas: 2.0.3
pillow: 9.4.0
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.22.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.24.1
huggingface-hub: 0.15.1
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @Vincentqyw this should be fixed on `main` and will be out on the next release (4.8.0) soon!
