### ISSUE TITLE
A button component cannot be displayed within a Dataframe.

### ISSUE THREAD

**Issue by Zilong01** [gradio-app/gradio#6621]
### Describe the bug

I want to build a table now, where there are several buttons in the last few columns. When the button is pressed, it will trigger the corresponding operation (based on the information of the current row). I tried to put `gr. Button` in the input of the data frame, but the only text displayed on the interface was the 'Button' text, not a button that could be pressed. How can I place a button on each row of a table?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
record_dataframe = gr.DataFrame(
            label="record", 
            headers=["a", "b", "c", "d", "e", "f"],
            column_widths=["12%", "20%", "20%", "8%", "30%", "10%"])

# select data in database , and return a list. 
def select_fankui(userid):
    
    records = db_select_fankui_record(userid)

    records, question_content_list = fankuiresult_btn(records) # This function turns the last element of the list into a Gr.Button

    return records, gr.Dropdown(choices=question_content_list, visible=True)

select_fankui_btn.click(fn=select_fankui, inputs=[sender], outputs=[record_dataframe, fankui_id_dropdown]) # put data into dataframe
       
       
```

### Screenshot

![bug1](https://github.com/gradio-app/gradio/assets/60741121/5f08cb4f-d018-410c-ae54-57e64eb1f4a1)

### System Info

```shell
gradio==4.7.1
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @Zilong01 this is not something that is supported. It is probably out of scope of a regular `gr.Dataframe`, but it could be an interesting custom component, as mentioned here: https://github.com/gradio-app/gradio/issues/2006
