### ISSUE TITLE
The `interactive` parameter in `gr.FileExplorer` has no effect. It should either be correctly documented or the feature should be added

### ISSUE THREAD

**Issue by rrfaria** [gradio-app/gradio#6627]
- [X] I have searched to see if a similar issue already exists.

### Is your feature request related to a problem? 

 interactive -  if True, will allow users to upload a file; if False, can only be used to display files. If not provided, this is inferred based on whether the component is used as an input or output.

This functionality apparently does nothing. I used like this:

```python
gr.FileExplorer(root='./voices', height=400, interactive=True, label="voices available", file_count="multiple", glob="**/*.*", ignore_glob="*.db,")
```

Either it should be documented correctly, or the ability to upload files should be added:

This functionality could be like google colab file explorer, enabling users to handle their files without need direct access to server.
And also could allow see empty folders on root folder I defined

![image](https://github.com/gradio-app/gradio/assets/11916455/747cf85c-5000-4b46-b5fe-92046f654641)

**Comment by pngwn** [comment]
I'm torn on this, making it part of the component would be a much slicker UI/ UX for users but also we need to sensible defaults so users don't accidentally give everyone access to the machine. This can technically be accomplished without adding these features to the FileExplorer but the UI/UX won't be as nice.

**Comment by rrfaria** [comment]
@pngwn I believe root param may handle access to files. the way it is today it only depends on the developer make a mistake giving access to wrong path. Adding buttom to upload file only for root folder defined on param and give an option to limit extension types may protect mistakes.
