### ISSUE TITLE
cannot return GGUF stream with CTransformers into gr.Chatbot object

### ISSUE THREAD

**Issue by fabiomatricardi** [gradio-app/gradio#6628]
### Describe the bug

Ctransformers stream with gr.ChatInterface is working fine. When I try to create a more complex GUI using gr.Blocks and gr.Chatbot the stream with `yield` throw an error 
`raise TypeError(
TypeError: Expected a list of lists or list of tuples. Received: That`
Is there anything wrong with the return of the generation function? 
From the docs it seems that if there is a `yield` it is automatically recognized as output of the function, with no need to be declared with a `return` statement

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

###load the model
modelfile = "model/harborwater-open-llama-3b-v2-wizard-evol-instuct-v2-196k-Q8_0.gguf"
conf = AutoConfig(Config(temperature=0.3, repetition_penalty=repetitionpenalty, batch_size=64,
                max_new_tokens=1024, context_length=contextlength))
model = AutoModelForCausalLM.from_pretrained(modelfile,
                                        model_type="llama",config = conf)
###Generation function
def predict(message, history):
    history_transformer_format = history + [[message, ""]]
    messages = "".join(["".join(["\n### HUMAN:\n"+item[0], "\n\n### RESPONSE:\n"+item[1]])  #curr_system_message +
                for item in history_transformer_format])
    partial_message = ""
    for chunk in model(messages, temperature = 0.3, repetition_penalty = 1.15, max_new_tokens=2048, stream=True):
        if len(chunk) != 0:
            partial_message = partial_message + chunk
            yield partial_message
####Gradio section
with gr.Blocks(theme='xiaobaiyuan/theme_brief') as demo: 
    with gr.Row():
        with gr.Column(scale=4):
            chatbot = gr.Chatbot()
            msg = gr.Textbox()
            msg.submit(predict, [msg, chatbot], [chatbot], queue=False).then(lambda: None, None, msg, queue=False)
if __name__ == "__main__":
    demo.launch(inbrowser=True)

### Screenshot

<img width="1399" alt="Screenshot 2023-12-03 alle 08 25 56" src="https://github.com/gradio-app/gradio/assets/23034543/8717746f-912b-43bf-b97e-9407f8afa5ff">

### Logs

```shell
(venv) ➜  ZZ_ZephyrPG python chat_TinyLlamaPG.py
loading model...
Model loaded in 0:00:01.318979
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

### HUMAN:
hi

### RESPONSE:

Traceback (most recent call last):
  File "/Volumes/VMdisks/ZZ_ZephyrPG/venv/lib/python3.10/site-packages/gradio/routes.py", line 569, in predict
    output = await route_utils.call_process_api(
  File "/Volumes/VMdisks/ZZ_ZephyrPG/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Volumes/VMdisks/ZZ_ZephyrPG/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1531, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Volumes/VMdisks/ZZ_ZephyrPG/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1420, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/Volumes/VMdisks/ZZ_ZephyrPG/venv/lib/python3.10/site-packages/gradio/components/chatbot.py", line 204, in postprocess
    raise TypeError(
TypeError: Expected a list of lists or list of tuples. Received: Hi

### HUMAN:
cheers

### RESPONSE:
```

### System Info

```shell
Running on MAC Intel, Python 3.10
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.4.1
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.1
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.3
pillow: 10.1.0
pydantic: 2.5.1
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.1
huggingface-hub: 0.19.4
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @fabiomatricardi ! To populate a chatbot, you need to yield the entire history as a list of tuples. Please see the demos here: https://www.gradio.app/docs/chatbot#demos and https://www.gradio.app/guides/creating-a-custom-chatbot-with-blocks#add-streaming-to-your-chatbot

**Comment by fxmarty** [comment]
@freddyaboulton This does not align well with transformers working with list of Dict: https://huggingface.co/docs/transformers/chat_templating#templates-for-chat-models

**Comment by freddyaboulton** [comment]
Yea we've discussed allowing the OpenAI conversation format for the `gr.Chatbot`. I think that's on the roadmap.

cc @dawoodkhan82 @abidlabs

**Comment by dawoodkhan82** [comment]
@freddyaboulton @fabiomatricardi yeah here's the open issue [here](https://github.com/gradio-app/gradio/issues/7118)

**Comment by fxmarty** [comment]
To bypass the issue using a `gr.State` is an option:

```python
import gradio as gr
import random
import time

from huggingface_hub import InferenceClient
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-8B-Instruct")

client = InferenceClient(model="http://0.0.0.0:8080")

SYSTEM_COMMAND = {"role": "system", "content": "You are a knowledgeable assistant trained to provide accurate and helpful information. Please respond to the user's queries promptly and politely."}

IGNORED_TOKENS = {None, "<|start_header_id|>", "<|end_header_id|>", "<|eot_id|>", "<|reserved_special_token"}
STOP_TOKENS = ["<|start_header_id|>", "<|end_header_id|>", "<|eot_id|>", "<|reserved_special_token"]

with gr.Blocks() as demo:
    tfs_history = gr.State([SYSTEM_COMMAND])
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.Button("Clear")

    def user(user_message, history, dict_history):
        data = {"role": "user", "content": user_message}
        dict_history.append(data)
        return "", history + [[user_message, None]], dict_history

    def bot(history, dict_history):
        history[-1][1] = ""
        response = {"role": "assistant", "content": ""}
        start_tokenize = time.perf_counter()
        text_input = tokenizer.apply_chat_template(dict_history, tokenize=False, add_generation_prompt=True)
        end_tokenize = time.perf_counter()

        try:
            for token in client.text_generation(prompt=text_input, max_new_tokens=100, stop_sequences=STOP_TOKENS, stream=True):
                if token not in IGNORED_TOKENS:
                    history[-1][1] += token
                    response["content"] += token
                yield history
        finally:
            dict_history.append(response)

    msg.submit(
        user,
        inputs=[msg, chatbot, tfs_history],
        outputs=[msg, chatbot, tfs_history],
        queue=False).then(
            bot,
            [chatbot, tfs_history],
            chatbot
    )
    clear.click(lambda: None, None, chatbot, queue=False)

demo.queue()
demo.launch()
```
