### ISSUE TITLE
Support helper classes in the docs

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#6633]
No way currently to surface helper classes (for example: brush in ImageEditor) in the docs. Docs only show methods and event listeners. Will need to be added to the jsons/documentation.py logic

Related: https://github.com/gradio-app/gradio/issues/6634

**Comment by abidlabs** [comment]
This is now supported, e.g. https://www.gradio.app/docs/gradio/imageeditor#helper-classes
