### ISSUE TITLE
Could not resolve host: huggingface.co

### ISSUE THREAD

**Issue by mattiashallberg** [gradio-app/gradio#6640]
### Describe the bug

On a few Monday mornings, I have observed that I am unable to update my Huggingface Space due to the below error:

`git clone` has been updated in upstream Git to have comparable
speeds to `git lfs clone`.
Cloning into '.'...
fatal: unable to access 'https://huggingface.co/datasets/m********g/T********Dataset/': Could not resolve host: huggingface.co
Error(s) during clone:
`git clone` failed: exit status 128

I am working Japanese time zone and after a few hours, i.e. later in the day, the error disappears. 
Is there a system job running at this time preventing me to deploy a change? I have tried both to Restart Space and Factory Rebuild, but to no avail. 
The code has not been changed much compared to a day before.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

This might be related to this issue: https://discuss.huggingface.co/t/space-doesnt-start/63669

Steps to reproduce:
1. Create a space app using a dataset on huggingface.co
2. Make an update to the code

### Logs

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/huggingface_hub/repository.py", line 686, in clone_from
    run_subprocess(
  File "/home/user/.local/lib/python3.10/site-packages/huggingface_hub/utils/_subprocess.py", line 83, in run_subprocess
    return subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'lfs', 'clone', 'https://user:hf_**********************************@huggingface.co/datasets/m********g/T********Dataset', '.']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/app/app.py", line 28, in <module>
    repo = Repository(
  File "/home/user/.local/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 128, in inner_f
    return f(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/huggingface_hub/repository.py", line 533, in __init__
    self.clone_from(repo_url=clone_from)
  File "/home/user/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/huggingface_hub/repository.py", line 726, in clone_from
    raise EnvironmentError(exc.stderr)
OSError: WARNING: `git lfs clone` is deprecated and will not be updated
          with new flags from `git clone`

`git clone` has been updated in upstream Git to have comparable
speeds to `git lfs clone`.
Cloning into '.'...
fatal: unable to access 'https://huggingface.co/datasets/m********g/T********tDataset/': Could not resolve host: huggingface.co
Error(s) during clone:
`git clone` failed: exit status 128

### System Info

```shell
gradio sdk_version: 4.3.0
huggingface_hub: 0.19.2
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @mattiashallberg ! I am going to close this as it's not a gradio issue. Will ping someone who works on spaces infrastructure so they can explain what's happening if they can.

**Comment by freddyaboulton** [comment]
Can you share the code you're using?

**Comment by mattiashallberg** [comment]
Thanks for looking into this @freddyaboulton .

Here is the piece of code causing the build error.
I am using this in order to persist the 'likes' on Huggingface with details.

`
DATASET_REPO_URL = "https://huggingface.co/datasets/m*******g/T*****t"
DATA_FILENAME = "output_log.csv"
DATA_FILE = os.path.join("data", DATA_FILENAME)
HF_TOKEN = os.environ['HF_TOKEN']

repo = Repository(
    local_dir="data",
    clone_from=DATASET_REPO_URL,
    use_auth_token=HF_TOKEN
  )
  
def push_log_to_outputfile(log_message: str):
    try:
        with open(DATA_FILE, "a") as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=["message", "time"])
        writer.writerow({"message": log_message, "time": str(datetime.now())})
    commit_url = repo.push_to_hub()
    print("\nWrite to file succeeded\n", commit_url)
    except IOError as e:
        print(f"An IOError occurred: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
`

I got it to work again by creating a new Gradio Space, so there is nothing wrong with the code itself.
