### ISSUE TITLE
Root_path is not working as expected 

### ISSUE THREAD

**Issue by podkd7226** [gradio-app/gradio#6641]
### Describe the bug

I'm using AWS EC2 and miniconda on it. 

I just followed the manual "https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx" 
and basic setting like that. 

My bug is like this.
When I open it with root path 
Then the app did not well working. 
If I open it without root path, then it is working well 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

with gr.Blocks() as demo:
      chatbot = gr.Chatbot(
             [],
          elem_id="chatbot",
             bubble_full_width=False,
          avatar_images=(("https://raw.githubusercontent.com/podkd7226/privacy/main/chathuman1_1.png"),
                         ("https://raw.githubusercontent.com/podkd7226/privacy/main/robot3_1.png")),
      )

      with gr.Row():
          txt = gr.Textbox(
              scale=4,
              show_label=False,
              placeholder="Enter text and press enter, or upload an image",
              container=False,
          )
          btn = gr.UploadButton("📁", file_types=["image", "video", "audio"])
  
      txt_msg = txt.submit(add_text, [chatbot, txt], [chatbot, txt], queue=False).then(
          bot, chatbot, chatbot, api_name="bot_response"
      )
      txt_msg.then(lambda: gr.Textbox(interactive=True), None, [txt], queue=False)
      file_msg = btn.upload(add_file, [chatbot, btn], [chatbot], queue=False).then(
          bot, chatbot, chatbot
      )

  if __name__ == '__main__':
      demo.queue()
      # demo.launch(root_path = "/gradio-demo")
      demo.launch()

### Screenshot

Gradio code
![image](https://github.com/gradio-app/gradio/assets/129777574/41b92310-c5ae-4c80-a5b0-6f49e4fc3c9f)

with root_path 
![image](https://github.com/gradio-app/gradio/assets/129777574/294b0949-c74f-4610-879a-01231524ee11)

without rootpath
![image](https://github.com/gradio-app/gradio/assets/129777574/27609b27-6293-4c2f-a455-dbb08ac114c3)

### System Info

```shell
my gradio version is 4.7.1
```

### Severity

I can work around it

**Comment by zzchust** [comment]
how do you solve it
