### ISSUE TITLE
Go through the docs and update references to the queue

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#6643]
Many sections regarding queueing are now outdated or simply unnecessary with the release of Gradio 4.x.

For example, in https://www.gradio.app/guides/key-features:

> Supplying a generator into Gradio requires you to enable queuing in the underlying Interface or Blocks (see the queuing section above).

Since queuing is enabled by default, this is not necessary. We should go through the guides and update references to the queue

**Comment by freddyaboulton** [comment]
We also still mention websockets. We should explain the new concurrency behavior and how to control it (default_concurrency_limit, concurrency_id, etc)

<img width="1096" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/47f8bd81-e56f-483d-8342-e0893837332f">

**Comment by abidlabs** [comment]
> We should explain the new concurrency behavior and how to control it (default_concurrency_limit, concurrency_id, etc)

I mention it a little bit here: https://github.com/gradio-app/gradio/pull/6673 but I agree it deserves its own place in the earlier guides
