### ISSUE TITLE
Run full CI on community-contributed PRs

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#6656]
We're getting community-contributed PRs on a regular basis. However, currently, the following CI actions do not run, which prevent us from fully validating the PRs before merging:

* Build PR Artifacts
* gradio-ui / deploy_to_vercel

It would be great if we could run these CI actions as well

**Comment by pngwn** [comment]
Will do this as part of #6264.

**Comment by abidlabs** [comment]
This is even more important now that we set the HF Token via an environment variable. As a result, the flaky backend tests (for the gradio and gradio_client libraries) fails for contributed PRs

**Comment by pngwn** [comment]
Cool, will take care of it this week then.

**Comment by abidlabs** [comment]
This is now closed, thanks a million @pngwn!
