### ISSUE TITLE
gradio-client can not return large image (1024x1024), but can do in small image(512x512)

### ISSUE THREAD

**Issue by yizhangliu** [gradio-app/gradio#6662]
### Describe the bug

    client = Client(src='generateImages')
    prompt = 'Sunrise at sea'
    guidance = 0.3
    steps = 4
    seed = 12345
    num_images_per_prompt = 1
    job = client.submit(prompt, guidance, steps, seed, num_images_per_prompt, api_name="/predict")
    while not job.done():
        time.sleep(0.1)

    print(job.outputs())

it return (image size 1024x1024 in server):     []

when I set image size 512x512 in server, it can return image.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

above descripe

### System Info

```shell
Gradio==4.8.0 in Centos and windows
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Is there a stacktrace from the client you can share? Does the server show an error in the logs? If you can share some sample code for the gradio app you're calling via client, it would make this easier to fix!

**Comment by yizhangliu** [comment]
Sorry, it's my problem. I will close this issue.

**Comment by freddyaboulton** [comment]
Thanks @yizhangliu !
