### ISSUE TITLE
Gradio Number field taking string input as well

### ISSUE THREAD

**Issue by yesdeepakmittal** [gradio-app/gradio#667]
By default Gradio takes float value in `gradio.inputs.Number()` and it does not allow us to enter string characters into the field. But if we enter a number and then try to enter the string, it accepts it as well. 

![image](https://user-images.githubusercontent.com/50262096/154704363-2c76f10a-c830-4e32-9135-f9bce7dc7f82.png)

---

Please consider this documentation example: 
![image](https://user-images.githubusercontent.com/50262096/154704573-0ef15383-e1cf-476d-9ff7-bc68c34a090a.png)

Please tell me how to enforce this condition to allow numbers only?

--- 

Another example
![image](https://user-images.githubusercontent.com/50262096/154705284-23e3faf9-85d7-4c2a-a8dc-28d231a56e07.png)

**Comment by abidlabs** [comment]
@yesdeepakmittal can you see if this is still an issue in the latest version of Gradio, `gradio==2.8.1`? I can't reproduce in colab, it may have gotten fixed as part of these updates.

**Comment by yesdeepakmittal** [comment]
Other characters stopped entering but `e` is still entering. If it is for an exponential digit, when we start writing numbers into the field and enter `e`, it removes all the numbers previously entered. 

![image](https://user-images.githubusercontent.com/50262096/154784048-796a7587-1576-4494-a9a1-6aefff56f39c.png)

**Comment by abidlabs** [comment]
That's weird, thanks for catching this and pointing it out. We'll fix this

**Comment by FarukOzderim** [comment]
I confirm this error.

**Code snippet:**
`
import gradio as gr

def func(number):
  return f"str {number}"


iface = gr.Interface(fn=func, inputs=gr.inputs.Number(), outputs="text")
iface.launch(debug=True)
`

**Traceback:**

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 216, in predict
    app.interface.process, raw_input
  File "/usr/local/lib/python3.7/dist-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.7/dist-packages/anyio/to_thread.py", line 29, in run_sync
    limiter=limiter)
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.7/dist-packages/gradio/interface.py", line 555, in process
    for i, input_component in enumerate(self.input_components)
  File "/usr/local/lib/python3.7/dist-packages/gradio/interface.py", line 555, in <listcomp>
    for i, input_component in enumerate(self.input_components)
  File "/usr/local/lib/python3.7/dist-packages/gradio/inputs.py", line 295, in preprocess
    return float(x)
TypeError: float() argument must be a string or a number, not 'NoneType'
`

**Comment by FarukOzderim** [comment]
@pngwn @aliabid94 shall we prevent the incorrect input usage at frontend, I feel like it would be better that way.

**Comment by pngwn** [comment]
Yeah this is a problem on the frontend.
