### ISSUE TITLE
Document @server

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#6674]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
The `@server` decorator used in FileExplorer is not documented anywhere

**Describe the solution you'd like**  

**Additional context**

**Comment by abidlabs** [comment]
Only needed for custom components, so I'll close this and add to: https://github.com/gradio-app/gradio/issues/6324
