### ISSUE TITLE
Dynamically Hiding based on radio button on_selected()

### ISSUE THREAD

**Issue by SutirthaChakraborty** [gradio-app/gradio#6675]
- [x] I have searched to see if a similar issue already exists.
 

<img width="1591" alt="image" src="https://github.com/gradio-app/gradio/assets/47362033/b82c7712-f85e-4d48-9230-c367c404f836">

**Comment by abidlabs** [comment]
Hi @SutirthaChakraborty what is the bug or feature request? There's no explanation or code provided

**Comment by abidlabs** [comment]
Sure, the gist of it as that you should return `gr.Audio(visible=False)` for any audio component you'd like to hide. You can read more about it here: https://www.gradio.app/guides/controlling-layout#visibility

For general questions like this (that are not feature requests or bug reports), please ask in [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
