### ISSUE TITLE
Dynamically Create Gradio Group in Blocks

### ISSUE THREAD

**Issue by fakerybakery** [gradio-app/gradio#6678]
Hi,
Is there any way to create a new Gradio Group in Blocks when a user clicks a button and to allow the user to delete it?
For example, can I allow the user to press a button to add an input field and dropdown and press another button to delete it?
Thank you!

**Comment by dwipper** [comment]
@fakerybakery According to this, it doesn't appear to be possible at this time:  https://discuss.huggingface.co/t/is-it-possible-to-change-the-interface-with-a-button/45021

**Comment by abidlabs** [comment]
Not yet, but we're working on supporting something like this. Please follow this issue for updates: https://github.com/gradio-app/gradio/issues/4689
