### ISSUE TITLE
omit null values in config

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#669]
Do not send null values in the config.

**Comment by FarukOzderim** [comment]
To remember what was it about, is it the issue where `None` values in the config cause problem for frontend. Is it solvable in frontend or do we need to remove `None` values from config?

cc: @aliabid94 @pngwn

**Comment by abidlabs** [comment]
I think this was saying that if any component property is `None`, it should not be included in the config, instead of it being passed in as "null"
