### ISSUE TITLE
how to delete or hidden the page of use gradio default footer container

### ISSUE THREAD

**Issue by zlemonj** [gradio-app/gradio#6696]
### Describe the bug

![image](https://github.com/gradio-app/gradio/assets/22006815/2761ac31-0c36-4360-9018-bea4d367f268)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
the latest version
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @zlemonj if you really, really want to remove the footer, you can do so with custom css. Example:

```py
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(
    fn=greet,
    inputs="text",
    outputs="text",
    css="footer {visibility: hidden}"
)
demo.launch()
```

you can also pass `css` into `Blocks`. See https://stackoverflow.com/questions/72960397/gradio-remove-the-tagline for mor einfo

**Comment by ketsapiwiq** [comment]
If you have another footer, you can also do:
```
footer:has(.built-with) {
  display: none !important;
}
```

**Comment by FBR65** [comment]
This does't work in Gradio 5

**Comment by dev3py** [comment]
How can we hide it in gradio 5
