### ISSUE TITLE
Allow users to close error tag and get back to the component

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#6700]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Sometimes the same component is an input and an output. If something errors out, the component gets in a state of error and you can't fix it because it was also the input. 

Another scenario where this happens is in case there's an error in a `.upload` from a `gr.Image` component for example: maybe the cropping errored out, or you uploaded an invalid image. But now the component is broken and you can't "close" the error to try again with a different image. 

**Describe the solution you'd like**  
Allow users to "close" the `Error` state of components when they error out, revealing what was underneath

**Comment by apolinario** [comment]
Minimal reproduction
```py
import gradio as gr

def crop_image(image):
  #Simulate error with cropping or the uploaded image
  raise gr.Error("Test")

with gr.Blocks() as demo:
    image = gr.Image(label="Name")
    image.upload(fn=crop_image, inputs=image, outputs=image)
  
if __name__ == "__main__":
    demo.launch()
```

This will render the upload component useless

https://github.com/gradio-app/gradio/assets/788417/84350a73-2008-4c19-b186-16e26b5014da

(Playground video but the same happens in 4.x) 

I think a `x` button to close the error and reveal the component behind would be enough

**Comment by freddyaboulton** [comment]
![max_file_size_upload](https://github.com/gradio-app/gradio/assets/41651716/7547330c-a082-4901-a291-3f150a197e45)
