### ISSUE TITLE
Running a program using `Gradio` could result in the loss of some static resources.

### ISSUE THREAD

**Issue by Zilong01** [gradio-app/gradio#6705]
### Describe the bug

If running in the 'graphic' mode(`gradio gradio_web.py`), the page in the root directory will display normally, and the same interface in the root directory will also be displayed in the/a/directory. If the nginx configuration in the root directory is commented out, the/a/directory will load incorrectly. If using ` python gradio_web. py ` runs normally.
I checked the error cause through F12, and it is possible that there was an error in requesting the `config` file (Request file for ip: port/config). Starting a program that is not in the root directory using gradio will result in a not found error, and multiple interfaces will only load the config file in the root directory.
Although it can be resolved by using Python to execute code, I still want to know what caused it and is it related to my configuration?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
# some code, Provide services in the /a directory

demo.launch(server_name='0.0.0.0',
                    server_port=11112, 
                    show_api=False,
                    share=False,
                    root_path="/a",
                    inbrowser=False)
```

# another python file. Provide services in the root directory

```python
demo.launch(server_name='0.0.0.0',
                    server_port=11111, 
                    show_api=False,
                    share=False,
                    inbrowser=False)
```
This is the configuration of my nginx
```nginx.conf
	location /a/ {
	    proxy_pass http://localhost:11112/;        
	}
        location / {
            proxy_pass http://localhost:11111/;       
        }
```

### System Info

```shell
gradio==4.7.1
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @Zilong01 I'm sorry I'm having a hard time understanding the issue here -- can you describe the problem in more detail?

**Comment by abidlabs** [comment]
Closing for lack of follow up.
