### ISSUE TITLE
Ability to remove individual files from `gr.File()` component

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#6708]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Currently the `gr.File()` component, once you upload files you can only remove all files at once
<img width="328" alt="image" src="https://github.com/gradio-app/gradio/assets/788417/a2853d35-3eef-402c-849e-254fd91d6bbf">

**Describe the solution you'd like**  
I'd like to be able to individually remove each uploaded file.

**Additional context**  
If uploaded something wrong by accident is very frustrating to remove all to reupload the correct ones.

**Comment by abidlabs** [comment]
Makes sense, this would be a nice addition
