### ISSUE TITLE
Long response is not shown and replacing previous shown response

### ISSUE THREAD

**Issue by ihgumilar** [gradio-app/gradio#6721]
- [ ] I have searched to see if a similar issue already exists.
Yes, I asked in discord as well

**Is your feature request related to a problem? Please describe.**  
I am streaming my response in vs code is fine. However, when I stream it using gradio, it only shows short response (it stops showing the response but still streaming it actually, because I can see from the button is not turning to submit yet). It replaces the previous response.

**Describe the solution you'd like**  
I would like to stream fully my response and create automatic scrolling if it is a bit long instead of replace the previous response that has been shown.

**Additional context**  
![image](https://github.com/gradio-app/gradio/assets/49016400/c1b86c59-f631-4289-b032-2dbc085a79ac)

gradio==4.8.0
gradio_client==0.7.1

**Comment by abidlabs** [comment]
Hi @ihgumilar this behavior is unexpected. Can you please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by abidlabs** [comment]
Closing for lack of follow up
