### ISSUE TITLE
Download buttons do not work inside iframes

### ISSUE THREAD

**Issue by whitphx** [gradio-app/gradio#6722]
### Describe the bug

Download buttons on components do not work when the app is embedded in an iframe.
Try to use the download buttons on the output image of [this example](https://www.gradio.app/docs/examples) or the output video of [this example](https://www.gradio.app/docs/video).

The reason seems to be same as #6486 where `<a download="...">` does not work for different origins, while the embedded app has a different origin from the parent page.

Introducing the same trick as #6486 to all the download buttons would be one solution.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Written above.

### System Info

```shell
Current HEAD is 9a5811df9218b622af59ba243a937a9c36ba00f9
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @whitphx the links are broken, could you please let us know if this is still an issue?

**Comment by whitphx** [comment]
We can close this issue, as it's now working just like Gallery's download button #6486 , where the target file is opened in a new tab instead of downloading it but it's a reasonable fallback as https://github.com/gradio-app/gradio/pull/6487/files#diff-d792e1eef741ee0fde858c703c8f67a0cd1121f8ae5c0d1c579b4f02f3221475R174-R179

btw, now you can try the example in https://www.gradio.app/docs/gradio/video.
Plz show the page in a narrow window to access the embedded Space-based demo as the Lite-based demo is used for wider screens.

**Comment by abidlabs** [comment]
Great thanks for confirming @whitphx!
