### ISSUE TITLE
Idea: add a always_btn parameter to the gradio.interface

### ISSUE THREAD

**Issue by maxencry** [gradio-app/gradio#6723]
Idea: add an always_btn parameter to the gradio.interface
So:
live = True and always_btn = False: interface should automatically rerun if any of the inputs change
live = False and always_btn = False: only a Submit button
live = True and always_btn = True: interface should automatically rerun if any of the inputs change AND when the button Submit is pressed

**Comment by abidlabs** [comment]
Hi @maxencry thanks for the suggestion. But we are not planning on significantly changing the `gr.Interface()`, which is a high-level abstraction over `gr.Blocks()`. If you would like to customize the look or behavior of a `gr.Interface()`, I'd kindly refer you to the `gr.Blocks()` API, which is a lower-level API that lets you control all events individually: https://www.gradio.app/docs/blocks

With `Blocks`, it would be very straightforward to trigger your function with a button, or if any of the inputs change.
