### ISSUE TITLE
Stop External Thread w/ Cancel Button

### ISSUE THREAD

**Issue by fakerybakery** [gradio-app/gradio#6724]
Hi,
I'm looking at [this demo](https://github.com/gradio-app/gradio/blob/main/demo/cancel_events/run.py). I have a Gradio app that will start a new thread, and I'd like a cancel button to stop the external thread as well.

My code:
```python
def generate_text(text):
    thread = Thread(target=model.generate, kwargs=generation_kwargs)
    thread.start()
    for out in streamer:
        yield out
[...]
generate = gen.click(generate_text[...])
stop.click(None, inputs=None, outputs=None, cancels=[generate])
```
Thank you in advance!

**Comment by freddyaboulton** [comment]
I'm not sure if gradio can know which threads are spawned from a running process dynamically. 

Maybe you can do this yourself, something like

```python

running_thread = gr.State()
def generate_text(text):
    thread = Thread(target=model.generate, kwargs=generation_kwargs)
    thread.start()
    for out in streamer:
        yield out, thread

generate = gen.click(generate_text, ..., outputs=[textbox, running_thread])
stop.click(None, inputs=None, outputs=None, cancels=[generate]).then(lambda t: t.join(timeout=1), inputs=running_thread, outputs=None)
```

**Comment by fakerybakery** [comment]
OK, thank you so much! I'll try that!

**Comment by fakerybakery** [comment]
One thing - is it possible to have multiple threads running at the same time to take advantage of Gradio's amazing queuing functions?

**Comment by freddyaboulton** [comment]
Thanks! Let us know if it works! Yes you should be able to spawn a thread from each event and have the events run concurrently.

**Comment by yimin-demo** [comment]
> I'm not sure if gradio can know which threads are spawned from a running process dynamically.
> 
> Maybe you can do this yourself, something like
> 
> ```python
> running_thread = gr.State()
> def generate_text(text):
>     thread = Thread(target=model.generate, kwargs=generation_kwargs)
>     thread.start()
>     for out in streamer:
>         yield out, thread
> 
> generate = gen.click(generate_text, ..., outputs=[textbox, running_thread])
> stop.click(None, inputs=None, outputs=None, cancels=[generate]).then(lambda t: t.join(timeout=1), inputs=running_thread, outputs=None)
> ```

Hi @freddyaboulton , what does `gr.State()` do here? I am reading the doc, but it is still not clear to me.

**Comment by freddyaboulton** [comment]
It lets you share data between events in the same session without using global variables, which would be shared across all sessions. In this case, what we want to share is the thread started in `generate_text`

**Comment by abidlabs** [comment]
Here's some more information about `gr.State` -- https://www.gradio.app/guides/state-in-blocks

I'll go ahead and close this issue as its neither a bug nor a feature request.

**Comment by fakerybakery** [comment]
> I'm not sure if gradio can know which threads are spawned from a running process dynamically.
> 
> Maybe you can do this yourself, something like
> 
> ```python
> running_thread = gr.State()
> def generate_text(text):
>     thread = Thread(target=model.generate, kwargs=generation_kwargs)
>     thread.start()
>     for out in streamer:
>         yield out, thread
> 
> generate = gen.click(generate_text, ..., outputs=[textbox, running_thread])
> stop.click(None, inputs=None, outputs=None, cancels=[generate]).then(lambda t: t.join(timeout=1), inputs=running_thread, outputs=None)
> ```

Hi, I'm a bit confused - is it possible to have multiple threads running at the same time?

**Comment by freddyaboulton** [comment]
Hi @fakerybakery !

Yes it should be possible. What problem are you running into? Note that if you click the generate button while there is a generation happening in your session, gradio will block the second click from going through. If you want to disable that, set `trigger_mode="multiple"` in the `gen.click` event.

**Comment by yzy1996** [comment]
Could you please give a small demo for stopping `print` in the following snippet:

```python
import gradio as gr
import time

def foo():
    for i in range(300):
        print(i)
        time.sleep(0.5)

with gr.Blocks() as block:
    start_btn = gr.Button("start")
    stop_btn = gr.Button("stop")

    click_event = start_btn.click(fn=foo, inputs=None, outputs=None)
    stop_btn.click(fn=None, inputs=None, outputs=None, cancels=[click_event])
    
block.queue().launch()
```

**Comment by freddyaboulton** [comment]
Hi @yzy1996 - the cancel button can't cancel functions that are already running. If you rewrite your function as a generator, gradio will be able to cancel it

```python
import gradio as gr
import time

def foo():
    for i in range(300):
        yield i
        time.sleep(0.5)

with gr.Blocks() as block:
    start_btn = gr.Button("start")
    stop_btn = gr.Button("stop")
    counter = gr.Number()
    click_event = start_btn.click(fn=foo, inputs=None, outputs=[counter])
    stop_btn.click(fn=None, inputs=None, outputs=None, cancels=[click_event])
    
block.queue().launch()

**Comment by yzy1996** [comment]
Thank you @freddyaboulton - I have mastered this usage. However, I have some long-running model inference programs, I would like to interrupt the running program and restart, is there any other good idea?

**Comment by freddyaboulton** [comment]
Hi @yzy1996 ! I don't think there is a way to do this with gradio at the moment. Will think about this.

**Comment by JackismyShephard** [comment]
> Hi @yzy1996 ! I don't think there is a way to do this with gradio at the moment. Will think about this.

This is a feature I am sorely missing as well
