### ISSUE TITLE
gr.on() without triggers is broken: IndexError

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [gradio-app/gradio#6730]
### Describe the bug

A per the doc [of this page](https://www.gradio.app/guides/blocks-and-event-listeners) : `If you do not specify any triggers, the function will automatically bind to the change event of all input components. `
I think my example show that this is broken.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
    with gr.Column():
        b = gr.Button("click me")

    gr.on(
            triggers=[b.click],  # commenting this line breaks the code
            fn=lambda: print("working"),
            )
demo.launch()
```

### Logs

```shell
If I comment the `triggers` line I get the following error:

Traceback (most recent call last):
  File "/home/USER/test.py", line 7, in <module>
    gr.on(
  File "/home/USER/.local/lib/python3.9/site-packages/gradio/events.py", line 421, in on
    dep, dep_index = Context.root_block.set_event_trigger(
  File "/home/USER/.local/lib/python3.9/site-packages/gradio/blocks.py", line 897, in set_event_trigger
    if _targets[0][1] == "change" and trigger_mode is None:
IndexError: list index out of range
```
```


### System Info

```shell
python version 3.9.18
gradio==4.8.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Can confirm the issue -- cc @aliabid94 can you take this one?

**Comment by cswamy** [comment]
Hi @aliabid94 took a crack at this and fix is working with both demo mentioned in issue and the example on linked [doc](https://www.gradio.app/guides/blocks-and-event-listeners).

Please have a look and let me know if any issues.

**Comment by thiswillbeyourgithub** [comment]
Hi, so indeed with the one line fix gradio doesn't crash. But I still don't get the `lambda : print('working')` to execute. I tried a bunch of variation and other components and still no luck.

Re reading the doc, can you confirm me that the `gr.on` syntax with no triggers listens to all events and not just `.change` events? If it only listens to change events then I think the doc whould emphasize this, for example by calling it `.change()` instead of "change" with no backticks.

**Comment by aliabid94** [comment]
Taking a look! sorry for the delay

**Comment by aliabid94** [comment]
Oh this is a misunderstanding. To be more explicit: If you do not specify any triggers, the function will automatically bind to the change event of all input components **of the event listener**, not all input components in the entire app! You haven't specified any inputs to gr.on, which causes an error.

To show how this works:
```python
import gradio as gr

with gr.Blocks() as demo:
    with gr.Column():
        b = gr.Button("click me")
        t = gr.Textbox(label="Text Box")

    gr.on(
            inputs=t,
            triggers=[b.click],
            fn=lambda _: print("working"),
            )
    
demo.launch()
```
In the above app, the listener is triggered the button click. If I comment out the trigger:
```python
import gradio as gr

with gr.Blocks() as demo:
    with gr.Column():
        b = gr.Button("click me")
        t = gr.Textbox(label="Text Box")

    gr.on(
            inputs=t,
            # triggers=[b.click],
            fn=lambda _: print("working"),
            )
    
demo.launch()
```
Now the function prints "working" on any change to t. Does that make sense?

**Comment by thiswillbeyourgithub** [comment]
**Ohhhhhhhhhhhhhhhhhhhhhhhh**

That makes a ton of sense! Thank you so much for taking the time!

Okay so:
1. thanks for fixing the crash with your one liner.
2. I think the docs is not clear about this.

**Comment by abidlabs** [comment]
@thiswillbeyourgithub feel free to open a PR to fix this in the docs if you feel that this is unclear! I'll go ahead and close this issue to help us focus on other issues at the moment.
