### ISSUE TITLE
svelte max-width property should be 100% instead of 1024px

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [gradio-app/gradio#6732]
### Describe the bug

I notice that the max-width of the svelte app seems to be 1024px. I think it should be 100% as it renders much more nicely especially on mobile.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

css = """
.app.svelte-1kyws56.svelte-1kyws56 { max-width: 100%; }
"""


with gr.Blocks(css=css) as demo:
    with gr.Column():
        b = gr.Button("click me")
demo.launch()

```

### System Info

```shell
gradio==4.8.0
python 3.9.10
```

### Severity

I can work around it

**Comment by pngwn** [comment]
I don't think is the correct approach as the screen will be very wide on large screens.

Do you have a screenshot showing the mobile improvements?

cc @hannahblair

**Comment by thiswillbeyourgithub** [comment]
On my computer with 100% : 
![image](https://github.com/gradio-app/gradio/assets/26625900/96c6a285-987f-4dc6-af25-a57480c747cc)

On my computer with default value:
![image](https://github.com/gradio-app/gradio/assets/26625900/294955c1-704f-41a2-97ce-71566594c5ff)

On my tablet with default value:
![image](https://github.com/gradio-app/gradio/assets/26625900/5683e0cb-2eb2-45c7-a643-ea93baa565d3)

On my tablet with 100%:
![image](https://github.com/gradio-app/gradio/assets/26625900/2b033345-471d-4a31-bcb6-2a1af4f7e6e0)


The difference does not seem much but I'm building a pretty complicated UI and losing 25% of the width for no reason is actually problematic, it's squeezing my audio components, making the buttons hard to click etc.

I agree that 100% can be an issue for some screens but a middle ground seems better. Something a bit more adaptative that takes into account vertical screens for example. Or simply using an optionnal argument for the screen width?

**Comment by thiswillbeyourgithub** [comment]
Currently on gradio 4.11 and I think this has gotten worse. My css workaround does not seem to work anymore and I'm stuck with the app appearing "zoomed out" on mobile.

What kind of arguments do you recommend for block.launch()?
