### ISSUE TITLE
JS client does not send `queue/join` request to correct origin when server behind a proxy

### ISSUE THREAD

**Issue by nxphi47** [gradio-app/gradio#6739]
### Describe the bug

I'm working on a remote server. I have upgrade gradio from 3.50.2 to 4.8, as well as **Create a new environment and fresh install gradio**. Now, the demo does not respond back, and have been waiting for the response indefinitely.

I have also tried other demo types as well, but the simplest one fails to work, see below for code and screenshot.

It works find on macbook. But on the remote server, only version 3.50.2 works. but I need the new features of 4.xx versions.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
    
if __name__ == "__main__":
    demo.launch(show_api=False)   
```

### Screenshot

<img width="1527" alt="Screenshot 2023-12-11 at 1 50 25 PM" src="https://github.com/gradio-app/gradio/assets/19323568/f8944eb9-2565-47c7-8c71-ff73c5e42493">

### Logs

```shell
There is no logs
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.8.0
gradio_client version: 0.7.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.1 is not installed.
httpx: 0.25.2
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.1
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.4
pillow: 10.0.1
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.2
huggingface-hub: 0.19.4
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by nxphi47** [comment]
### How to switch back to websockets?

I found the reason is that Gradio try to use SSE, which in the JS client (gradio/client/js/src/client.ts) try call `/queue/join/...`. However, our remote server is not accessible by IP address, but accessible via a proxy, e.g: `abc.com/proxy/1234`.

When calling `/queue/join/...`, the client call `abc.com/queue/join` instead of `abc.com/proxy/1234/queue/join`, leading to 403 error.

<img width="492" alt="Screenshot 2023-12-12 at 10 07 42 AM" src="https://github.com/gradio-app/gradio/assets/19323568/cc3860c3-2a08-44c3-88fd-1f7c60db4ade">

### Alternatively, how to implement the new UI for `gr.Audio`, `gr.Image`, `gr.Video` to version 3.50.2

If cannot solve problem above, I would prefer to have a way to apply new UI for these components to version 3.50.2.

**Comment by freddyaboulton** [comment]
Looks like it is a bug in the js client then. Will rename the issue - thanks @nxphi47
