### ISSUE TITLE
Webcam icon not showing after 4.8.0 update.

### ISSUE THREAD

**Issue by yht0** [gradio-app/gradio#6741]
### Describe the bug

Either I'm missing something but after 4.8.0 update, the webcam icon went missing on all my python modules. 
I'm using gr.Interface btw not gr.Blocks

After 4.8.0 Update:
![Screenshot 2023-12-11 165600](https://github.com/gradio-app/gradio/assets/148779795/b9e3295d-b6c0-476a-98e8-10e15dfa3be4)

Before
![Screenshot 2023-12-11 165512](https://github.com/gradio-app/gradio/assets/148779795/24af7377-ca41-4ed0-aca1-1b2997ab0eaf)

I had to downgrade to get the icons back. Either something is wrong with my code or nobody else is noticing it's broken?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.7.1 (this is after the downgrade)
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.2
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.22.0
orjson: 3.9.10
packaging: 23.2
pandas: 1.5.3
pillow: 10.1.0
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.2
huggingface-hub: 0.19.4
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by yht0** [comment]
So on the https://www.gradio.app/playground, using the "Sepia Filter" sample code as an example, the preview on the playground doesn't show the webcam + upload icon row while if i run it on my own local machine (gradio version 4.7.1), it still shows the icon, and I prefer this a whole lot. 
![Screenshot 2023-12-11 171836](https://github.com/gradio-app/gradio/assets/148779795/e55c6a59-fea4-4bf1-b75f-f61b4f80da2a)
(left is 4.7.1, right is 4.8.0)

**Comment by abidlabs** [comment]
Closing for lack of follow up. We can reopen if this is still an issue in the latest version of `gradio`
