### ISSUE TITLE
A Space loaded with `gr.load()` is not functional

### ISSUE THREAD

**Issue by vitaliy-sharandin** [gradio-app/gradio#6744]
### Describe the bug

While embedding the private space into the public one, UI is transitioned, but is completely unfunctional, although the private space by itself works perfectly. Dropdowns can't be clicked, buttons don't do anything, one can only fill a text field successfully. Also, no error log is shown.
I am embedding space as I currently don't want to share my code, hence private space load from public space.

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import os

HF_TOKEN = os.environ["HF_TOKEN"]

css = """
.column-frame {
    border: 2px solid #AAA;
    border-radius: 10px;
    padding: 10px;
    margin: 10px;
}
"""

with gr.Blocks(theme=gr.themes.Soft(),css=css) as demo:
    gr.load("private_space_path", src="spaces", hf_token=HF_TOKEN)

demo.launch(debug=True)
```

### System Info

```shell
gradio=4.8.0
env=Hugging Face Spaces
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @vitaliy-sharandin do you see any errors in the logs?

**Comment by vitaliy-sharandin** [comment]
As I've written before, no error logs are shown, it just silently doesn't work, there are dropdowns/video upload/buttons failing and from what I've seen in the HF forums, some users experienced troubles with data in loading spaces as well. Again, when private one works fine. Here is my public space, you can see for yourself.

I've also tried switching my public space to GPU configuration as private one requires it, still no success. Should this be done at all or it's ok to use CPU config in public space while private is GPU dependent?

https://huggingface.co/spaces/vitaliy-sharandin/Video_translation_with_speaker_diarization_and_voice_cloning

**Comment by abidlabs** [comment]
Thanks @vitaliy-sharandin. The public Space does not need a GPU, it calls the private one via API. I'll take a look!

**Comment by vitaliy-sharandin** [comment]
Thanks, @abidlabs, also, please let me know in this thread when you finish looking at project so that I turn off the private space, as GPU is eating money away.

**Comment by abidlabs** [comment]
Oh please don't keep the GPU running. I would at least set the sleep time to a small amount, like 5 minutes (you can do this in the settings).

**Comment by vitaliy-sharandin** [comment]
I understand, but before when the private space was asleep, the public one threw exception about inaccessibility, strange, now it's showing ui for some reason. Now the private is asleep, tell me if you'd need it up.

**Comment by abidlabs** [comment]
@vitaliy-sharandin could I ask you to test something -- does this issue persist if you make your private Space public? I understand that you may not want to make your full private Space public, but if you could try with a similar Space, that would help us figure out if the issue specifically happens with private Spaces, or with `gr.load()` generally.

If its the latter (happening with `gr.load()` generally), then I think I know the issue

**Comment by vitaliy-sharandin** [comment]
Yes, the issue persists when you load public space as well.

**Comment by abidlabs** [comment]
Cool thanks for letting us know. Will work on a fix

**Comment by vitaliy-sharandin** [comment]
@abidlabs Thanks for fixing the issue. Could you either create an official release or tell me how to update Spaces gradio version from repository main branch?

**Comment by abidlabs** [comment]
We just released `gradio==4.12`, this should hopefully fix everything! If not, please do let us know

**Comment by vitaliy-sharandin** [comment]
Outstanding, I installed 4.12, yet it doesn't quite work. In private space for some reason the webcam and microphone permissions are now required to use video upload and after factory rebuilding the public one, I get error:
```
Fetching Space from: https://huggingface.co/spaces/vitaliy-sharandin/Video_translation_with_speaker_diarization_and_voice_cloning_private
Loaded as API: https://vitaliy-sharandin-video-translation-with-speaker-9440214.hf.space ✔
Traceback (most recent call last):
  File "/home/user/app/app.py", line 16, in <module>
    gr.load("vitaliy-sharandin/Video_translation_with_speaker_diarization_and_voice_cloning_private", src="spaces", hf_token=HF_TOKEN)
  File "/home/user/.local/lib/python3.10/site-packages/gradio/external.py", line 72, in load
    return load_blocks_from_repo(
  File "/home/user/.local/lib/python3.10/site-packages/gradio/external.py", line 111, in load_blocks_from_repo
    blocks: gradio.Blocks = factory_methods[src](name, hf_token, alias, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/gradio/external.py", line 527, in from_spaces
    return from_spaces_blocks(space=space_name, hf_token=hf_token)
  File "/home/user/.local/lib/python3.10/site-packages/gradio/external.py", line 546, in from_spaces_blocks
    return gradio.Blocks.from_config(client.config, predict_fns, client.src)
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 731, in from_config
    targets = [
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 733, in <listcomp>
    original_mapping[
KeyError: None
```

**Comment by abidlabs** [comment]
Hmm strange indeed. We’ll keep looking into this.

tagging @hannahblair for the permissions issue

**Comment by vitaliy-sharandin** [comment]
Thanks, and happy holidays!

**Comment by abidlabs** [comment]
Hi @vitaliy-sharandin sorry for the late response. I've been able to partially reproduce this issue. I'm going to keep looking into it to see what the underlying issue is.

**Comment by leonchen417** [comment]
Hey team, I'm having the similar issue  with gradio version in requirements.txt being
`gradio[oauth]==4.14.0; python_version >= '3.8'`

my HF space: https://huggingface.co/spaces/leonchen417/test_public_space
my HF logs: 
```
Fetching Space from: https://huggingface.co/spaces/leonchen417/test_private_space
Loaded as API: https://leonchen417-test-private-space.hf.space ✔
Traceback (most recent call last):
  File "/home/user/app/app.py", line 8, in <module>
    gr.load("leonchen417/test_private_space", hf_token=hf_token,  src="spaces")
  File "/home/user/.local/lib/python3.10/site-packages/gradio/external.py", line 72, in load
    return load_blocks_from_repo(
  File "/home/user/.local/lib/python3.10/site-packages/gradio/external.py", line 111, in load_blocks_from_repo
    blocks: gradio.Blocks = factory_methods[src](name, hf_token, alias, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/gradio/external.py", line 527, in from_spaces
    return from_spaces_blocks(space=space_name, hf_token=hf_token)
  File "/home/user/.local/lib/python3.10/site-packages/gradio/external.py", line 546, in from_spaces_blocks
    return gradio.Blocks.from_config(client.config, predict_fns, client.src)
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 731, in from_config
    targets = [
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 733, in <listcomp>
    original_mapping[
KeyError: None
```
should I try a different gradio version ?

**Comment by abidlabs** [comment]
Working on this!

**Comment by Aillian** [comment]
is this issue solved? i'm having he same issue and unable to interact with my public space

**Comment by Aillian** [comment]
I found a temporary solution, it's working for me...

Instead of this:
```
import gradio as gr

with gr.Blocks() as app:
    gr.load("your/private_space", hf_token="yourHfToken", src="spaces")

app.queue().launch()
```

Do this:
```
import gradio as gr

app = gr.load("your/private_space", hf_token="yourHfToken", src="spaces")

app.queue().launch()
```

So basically do not have your app in a `gr.Blocks()` component.

**Comment by freddyaboulton** [comment]
@Aillian I think you would have to call `render`:

```python
import gradio as gr

with gr.Blocks() as app:
    gr.load("your/private_space", hf_token="yourHfToken", src="spaces").render()

app.queue().launch()
```

See #7996
