### ISSUE TITLE
ImageEditor doesn't work with `examples`

### ISSUE THREAD

**Issue by whitphx** [gradio-app/gradio#6752]
### Describe the bug

* [Bug] Examples with `ImageEditor` don't display images as the attached screenshots.
* [Feature Request] The data structure required for `ImageEditor`'s examples is not intuitive and not documented. 
    * It should be documented.
    * and/or more intuitive format should be allowed. For example, allowing the same data as `Image` and use it as the `background` data.
* [Feature Request] All the keys of the example data are required and an error occurs if any key is missing. Missed keys should be treated as `None` for convenience.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

This script is expected to be run at the root dir of the gradio repo due to the file path.

```python
import os
import gradio as gr


def identity(input):
    return input["background"]

demo = gr.Interface(
    fn=identity,
    inputs=gr.ImageEditor(),
    outputs="image",
    examples=[
        [
            {
                "background": os.path.join(os.path.dirname(__file__), "demo/kitchen_sink/files/lion.jpg"),
                "layers": [],
                "composite": None,
            }
        ]
    ]
)

demo.launch()
```

### Screenshot

![CleanShot 2023-12-11 at 19 09 30@2x](https://github.com/gradio-app/gradio/assets/3135397/f4bab5be-0071-42b9-a198-fd75b961ab43)

![CleanShot 2023-12-11 at 19 09 37@2x](https://github.com/gradio-app/gradio/assets/3135397/1fe6fa28-2fbf-4714-a456-cde76c8f5283)
The input and output are working, so the passed data structure should not be wrong. Looks like just the example component is not displaying the data properly.

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.8.0
gradio_client version: 0.7.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.1.0
altair: 4.2.2
fastapi: 0.104.1
ffmpy: 0.3.0
gradio-client==0.7.1 is not installed.
httpx: 0.24.0
huggingface-hub: 0.14.1
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.2
matplotlib: 3.7.1
numpy: 1.24.3
orjson: 3.8.11
packaging: 23.1
pandas: 2.0.1
pillow: 9.5.0
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.30.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.22.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.4.0
httpx: 0.24.0
huggingface-hub: 0.14.1
packaging: 23.1
requests: 2.30.0
typing-extensions: 4.8.0
websockets: 11.0.2
```

### Severity

I can work around it

**Comment by pngwn** [comment]
The Image Editor example only uses the composite as the actual example, we should probably document this but i don't think we want to change it because that would be more confusing to users (having two different interfaces). The reason we split the `Image` and `ImageEditor` is so we could have these different interfaces.

**Comment by pngwn** [comment]
I _think_ the only required key is the `composite` key but I'd need to check that.

**Comment by j2l** [comment]
May I ask how to install the 4.8 version locally to test ImageEditor?

**Comment by freddyaboulton** [comment]
The latest version is 4.9 and you can install it with `pip install gradio==4.9.0`!

**Comment by abidlabs** [comment]
I'll take care of this in: https://github.com/gradio-app/gradio/pull/6799

So you'll be able to do things like:

```py
import gradio as gr
from PIL import Image
import numpy as np

with gr.Blocks() as demo:
    gr.ImageEditor(value="https://people.sc.fsu.edu/~jburkardt/data/png/dragon.png", interactive=True)

demo.launch()
```

```py
import gradio as gr
from PIL import Image
import numpy as np

im = { 
  "background": "https://people.sc.fsu.edu/~jburkardt/data/png/dragon.png",
  "layers" : [],  
  "composite": None
}

demo = gr.Interface(lambda x:x, gr.ImageEditor(), gr.ImageEditor(), examples=[im])

demo.launch()
```

or even just:

```py
import gradio as gr
from PIL import Image
import numpy as np

im = { 
  "background": "https://people.sc.fsu.edu/~jburkardt/data/png/dragon.png",
  "layers" : [],  
  "composite": None
}

demo = gr.Interface(lambda x:x, gr.ImageEditor(), gr.ImageEditor(), examples=[im])

demo.launch()
```

**Comment by j2l** [comment]
Thanks @freddyaboulton updated now.
@abidlabs the first example doesn't work for me, I m' getting an error:
```
 gradio app.py
Watching: '/home/pm/.local/lib/python3.10/site-packages/gradio', 
'/home/pm/Documents/github/gradio_sveltekit/gradio', 
'/home/pm/Documents/github/gradio_sveltekit/gradio'

Traceback (most recent call last):
  File "/home/pm/Documents/github/gradio_sveltekit/gradio/app.py", line 7, in <module>
    gr.ImageEditor(value="https://people.sc.fsu.edu/~jburkardt/data/png/dragon.png", interactive=True)
  File "/home/pm/.local/lib/python3.10/site-packages/gradio/component_meta.py", line 155, in wrapper
    return fn(self, **kwargs)
  File "/home/pm/.local/lib/python3.10/site-packages/gradio/components/image_editor.py", line 180, in __init__
    super().__init__(
  File "/home/pm/.local/lib/python3.10/site-packages/gradio/component_meta.py", line 155, in wrapper
    return fn(self, **kwargs)
  File "/home/pm/.local/lib/python3.10/site-packages/gradio/components/base.py", line 200, in __init__
    initial_value = self.postprocess(initial_value)
  File "/home/pm/.local/lib/python3.10/site-packages/gradio/components/image_editor.py", line 271, in postprocess
    if y["layers"]
TypeError: string indices must be integers
```

**Comment by abidlabs** [comment]
Hi @j2l we haven't released the fix yet. Are you installing Gradio from the PR branch? 

You can do that by doing:

```py
pip install https://gradio-builds.s3.amazonaws.com/182b3c083996044fe20fc12013e2b0dabe28a5af/gradio-4.9.1-py3-none-any.whl
```

**Comment by j2l** [comment]
Thank you @abidlabs! It's working now
