### ISSUE TITLE
Upgrade the PDF component to use pdfjs express: it supports annotations and more!

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [gradio-app/gradio#6760]
Hi!

I noticed the [documents page explaining how to create a custom PDF component](https://www.gradio.app/guides/pdf-component-example#step-2-frontend-modify-javascript-dependencies) that uses pdfjs.

Recently I heard about [pdfjs Express](https://pdfjs.express/) which was made to be easily [integrated into svelta](https://pdfjs.express/documentation/get-started/svelte) and supports annotation and many more things. [Here's their demo page](https://pdfjs.express/demo)

I think it could enable a lot of use case of "live" pdf reading.

**Comment by abidlabs** [comment]
Thanks @thiswillbeyourgithub! As this is just an example (as opposed to a core component that we are maintaining in the `gradio` library), we won't necessarily change it. But please feel free to create your own custom PDF component using the pdfjs, and we are happy to help share it and include it in our upcoming custom components gallery!

**Comment by freddyaboulton** [comment]
Hi @thiswillbeyourgithub - please feel free to open a PR to the github repo here https://github.com/freddyaboulton/gradio-pdf

**Comment by thiswillbeyourgithub** [comment]
Oh thanks! I don't know why but for the life of me I couldn't find the repo to gradio_pdf. The links from pypi redirected me here and github search sucks!

Unfortunately I don't know js so I won't know what I'm doing :/ so no chance of a PR from me.
