### ISSUE TITLE
[OAuth] Respect query parameters when redirecting after login

### ISSUE THREAD

**Issue by Wauplin** [gradio-app/gradio#6769]
At the moment, a user that logs in is then redirected to `/`. It would be nice to be able to provide a certain `__state` query parameter and respect it in the `/login` and `/callback` calls. The Space creator can then get this query param using `gr.Request` and decide what to do with it (typically resume the workflow where it stopped). 

cc @apolinario who suggested it [on slack](https://huggingface.slack.com/archives/C02QZLG8GMN/p1702463919095659?thread_ts=1702456246.887489&cid=C02QZLG8GMN) (private).

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/issues/6769
