### ISSUE TITLE
The `getting-started-with-the-js-client` guide has incorrect information

### ISSUE THREAD

**Issue by j2l** [gradio-app/gradio#6771]
Edit:

The guide here (https://www.gradio.app/guides/getting-started-with-the-js-client) is wrong. `view_info()` should be `view_api()`.

---

### Describe the bug

trying the JS client in sveltekit.
Tried on +page.svelte and +page.server.js in a `load` function on the server. Same error.
Any idea?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import { client } from "@gradio/client";
    import { onMount } from "svelte";
    onMount(async()=>{
const app = await client("abidlabs/whisper");
const app_info = await app.view_info();
        console.log(app_info);
}
```
also tried in +page.server.js

### System Info

```shell
ubuntu 22.04
node v18.17.1
"@gradio/client": "^0.9.0"
npm 9.6.7
```

### Severity

Blocking usage of gradio

**Comment by pngwn** [comment]
This method is named `view_api()`.

**Comment by j2l** [comment]
Thanks @pngwn 
I guess doc is wrong https://www.gradio.app/guides/getting-started-with-the-js-client

**Comment by pngwn** [comment]
Ah thanks for surfacing that. I'll rename the issue.

**Comment by pngwn** [comment]
(PRs welcome!)

**Comment by j2l** [comment]
Not sure where the doc is on github. A branch? or another proejct?

**Comment by j2l** [comment]
BTW, all examples through the JS client fail, and return:
```
{
  type: 'status',
  endpoint: '/predict',
  fn_index: 0,
  time: 2023-12-13T14:45:54.721Z,
  queue: true,
  message: null,
  stage: 'error',
  code: undefined,
  success: false
}
```

**Comment by j2l** [comment]
I found the doc, forked and PRed: https://github.com/gradio-app/gradio/pull/6773
