### ISSUE TITLE
Disable automatic matching of input and output sizes

### ISSUE THREAD

**Issue by labdalla** [gradio-app/gradio#68]
Could there be an option to disable the input and output interfaces being automatically the same size? For example, when there are many UI components in the output interface, and not as many in the input interface, the input interface is still forced to be the same size as the output interface. Is there an option to disable that, if the user desired?

Currently what happens:
<img width="1022" alt="Screen Shot 2020-10-10 at 9 37 25 PM" src="https://user-images.githubusercontent.com/6474811/95661500-df0b5e80-0afd-11eb-892f-40b0a79dc4a2.png">

What I'm requesting:
<img width="1034" alt="Screen Shot 2020-10-10 at 9 37 52 PM" src="https://user-images.githubusercontent.com/6474811/95661509-ea5e8a00-0afd-11eb-8d43-dd39f12dc03b.png">

**Comment by abidlabs** [comment]
Closed with 1.4.0
