### ISSUE TITLE
[Blocks] Allowing users to adapt the parameters of one component based on another component

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#680]
A VERY common request. Here is the original discussion post:

> My interface is taking 2 inputs from the user. One using **Slider** & another using **Dropdown**. I want to change the options of dropdown depending upon the value selected using Slider. Then both of these values will be input to the calling function. How can I implement that functionality?

_Originally posted by @yesdeepakmittal in https://github.com/gradio-app/gradio/discussions/679_

**Comment by abidlabs** [comment]
The way it might look for the user:

```python
from gradio.blocks import *

def dropdown_values(val):
    if val < 50:
       return ["fail", "repeat"]
    else:
       return ["succeed", "repeat"]
  
def fn(val, action):
     return "Your score is {} and you decided to {}".format(val, action)


with Blocks() as block:

  s = Slider(0, 100)
  d = Dropdown([]) 
  t = Textbox()

  s.select(fn=dropdown_values, outputs=d)
  d.select(fn=fn, inputs=[s, d], outputs=t)

  block.launch()
```

Basically every component (e.g. the Dropdown) should be able to be treated as an input or output

**Comment by FarukOzderim** [comment]
I think this should not be in our priority, this should be in the 2nd next release :)

**Comment by pngwn** [comment]
@abidlabs is this the same as #736 ?

**Comment by abidlabs** [comment]
Yes it is, let me close this one. Thanks
