### ISSUE TITLE
Problem with Dataset in an Interface when pressing the clear button

### ISSUE THREAD

**Issue by uvsq22201695** [gradio-app/gradio#6807]
### Describe the bug

To be able to realize the bug, copy the code provided and run it. Once on the web page, perform these actions:

1. Enter a name (this is an example) in the TextBox
2. Press the “Submit” button, the Dataset updates.
3. Press the “Clear” button

The Dataset and Textbox will not be deleted. No more actions will be possible (for example, changing the value in Textbox and clicking again on "submit" will not change the dataset).

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def greet(name):
    return [["Hello " + name + "!"]]


demo = gr.Interface(fn=greet, inputs=gr.Textbox(), outputs=gr.Dataset(components=["text"], samples=[]))

demo.launch(debug=True)
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.9.0
gradio_client version: 0.7.2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.105.0
ffmpy: 0.3.1
gradio-client==0.7.2 is not installed.
httpx: 0.25.2
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.4
pillow: 10.1.0
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.25.2
huggingface-hub: 0.19.4
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Interesting, perhaps the clear functionality is not supported by `gr.Dataset`

**Comment by uvsq22201695** [comment]
I think I understand. The clear functionality returns None, however ``gr.Dataset`` does not take None as a value which causes the problem. If None is returned to ``gr.Dataset``, it should eventually be converted into an empty list: [ ]
