### ISSUE TITLE
Improving user experiencer in chatbot v2.8.1

### ISSUE THREAD

**Issue by kingabzpro** [gradio-app/gradio#681]
**Is your feature request related to a problem? Please describe.**
1.  can you make `enter` to send the message? 
2. can you clear the text from input after pressing `submit` button?

![image](https://user-images.githubusercontent.com/36753484/154811779-78f2e934-5613-4aa0-8cb8-5e66f06e8a32.png)

**Describe the solution you'd like**
Just like Hugging Face API interface for conversation models:

![image](https://user-images.githubusercontent.com/36753484/154811802-1157ba72-d837-4a33-a6c9-72abad04e0a1.png)

**Additional context**
These features will make chatting experience smoother.

**Comment by FarukOzderim** [comment]
What are your thoughts on this issue @pngwn and @aliabid94, would we redesign the Chatbot component?

**Comment by abidlabs** [comment]
I think this is an example of a whole Interface, not a single component. We can show @kingabzpro how to create something like this in Blocks, and maybe consider adding a high-level abstraction `ChatbotInterface` in the future

**Comment by abidlabs** [comment]
Hi @kingabzpro, thanks again for opening up this issue. We have just beta released Blocks, which is a low-level API that can be used to build very customizable web apps in Python. You can try it by `pip install gradio==2.9b7` (same as in your other issue) or setting `gradio==2.9b7` in your `requirements.txt` file in Spaces.

To build a chatbot like what you have described, you could build it out of blocks like this:

```py
import gradio as gr

with gr.Blocks():
    chatbot = gr.Chatbot()
    text = gr.Textbox(label="Your sentence here... (press enter to submit)")
    state = gr.Variable(default_value=[])
    text.submit(predict, [text, state], [chatbot, state])    

blocks.launch()
```

We also considered creating a `ChatbotInterface` that offers a convenient abstraction for people who don't want to deal with the Blocks API. If this sounds interested, we would welcome a PR from you!

**Comment by abidlabs** [comment]
Of course, you also need to define a `predict()` function, which could be like this:

```py
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-medium")
model = AutoModelForCausalLM.from_pretrained("microsoft/DialoGPT-medium")

def predict(input, history=[]):
    # tokenize the new input sentence
    new_user_input_ids = tokenizer.encode(input + tokenizer.eos_token, return_tensors='pt')

    # append the new user input tokens to the chat history
    bot_input_ids = torch.cat([torch.LongTensor(history), new_user_input_ids], dim=-1)

    # generate a response 
    history = model.generate(bot_input_ids, max_length=1000, pad_token_id=tokenizer.eos_token_id).tolist()

    # convert the tokens to text, and then split the responses into the right format
    response = tokenizer.decode(history[0]).split("<|endoftext|>")
    response = [(response[i], response[i+1]) for i in range(0, len(response)-1, 2)]  # convert to tuples of list
    return response, history
```

**Comment by abidlabs** [comment]
Closing, but let us know if you have any questions!

**Comment by jjmachan** [comment]
I had a follow-up question about this. I'm using the block API and pretty happy with that but I can't seem to figure out how to clear the text after TextBox.submit() has run. How would I do that?

**Comment by abidlabs** [comment]
All you have to do is add:

```
textbox.submit(lambda :"", None, textbox)
```

Take a look at this Guide as a reference: https://gradio.app/creating-a-chatbot/

**Comment by liouxy** [comment]
> Of course, you also need to define a `predict()` function, which could be like this:
> 
> ```python
> from transformers import AutoModelForCausalLM, AutoTokenizer
> import torch
> 
> tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-medium")
> model = AutoModelForCausalLM.from_pretrained("microsoft/DialoGPT-medium")
> 
> def predict(input, history=[]):
>     # tokenize the new input sentence
>     new_user_input_ids = tokenizer.encode(input + tokenizer.eos_token, return_tensors='pt')
> 
>     # append the new user input tokens to the chat history
>     bot_input_ids = torch.cat([torch.LongTensor(history), new_user_input_ids], dim=-1)
> 
>     # generate a response 
>     history = model.generate(bot_input_ids, max_length=1000, pad_token_id=tokenizer.eos_token_id).tolist()
> 
>     # convert the tokens to text, and then split the responses into the right format
>     response = tokenizer.decode(history[0]).split("<|endoftext|>")
>     response = [(response[i], response[i+1]) for i in range(0, len(response)-1, 2)]  # convert to tuples of list
>     return response, history
> ```

I have tried this code, but I got the error:
```python 
bot_input_ids = torch.cat([torch.LongTensor(history), new_user_input_ids], dim=-1)
TypeError: new(): data must be a sequence (got NoneType)```

I am not very familiar with the development of gradio. Could you help me see where I need to make modifications? Thank!
