### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'Box'

### ISSUE THREAD

**Issue by adaaaaaa** [gradio-app/gradio#6815]
### Describe the bug

python server.py                                                                                                                                                                     ─╯
2023-12-17 12:54:21 INFO:Loading the extension "gallery"...
Traceback (most recent call last):
  File "/data/text-generation-webui/server.py", line 249, in <module>
    create_interface()
  File "/data/text-generation-webui/server.py", line 131, in create_interface
    ui_model_menu.create_ui()  # Model tab
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/text-generation-webui/modules/ui_model_menu.py", line 77, in create_ui
    with gr.Box():
         ^^^^^^
AttributeError: module 'gradio' has no attribute 'Box'

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
gr.Box()
```

### System Info

```shell
gradio 4.10.0

```

### Severity

Blocking usage of gradio

**Comment by onuralpszr** [comment]
@adaaaaaa with version 4.0.0 they removed it 

https://www.gradio.app/changelog#4-0-0

![image](https://github.com/gradio-app/gradio/assets/1688848/7f773cbe-b80d-4e3a-b8af-4ddc1fc36036)

**Comment by pngwn** [comment]
Yes, `gr.Box` no longer exists. You should be able to achieve the same goal with `gr.Group`.

**Comment by ColomboEnterprise** [comment]
How i can fix the problem? When i us pinokio every 2nd app got this probelm

**Comment by koplenov** [comment]
Have these guys even heard anything about backwards compatibility? :/

**Comment by koplenov** [comment]
> We follow semver

If it worked, this issue wouldn't exist :')

I ran into the fact that you were moving furniture at the moment when I was rolling back to past commits of one project - the authors didn't commit versions and it just broke the application

It's ridiculous

check VerLess https://mol.hyoo.ru/#!section=docs/=19222d_hpubim

**Comment by koplenov** [comment]
> It was removed in a major version. If there were no breaking changes it would have been a minor.

No, you just created and maintain a class of problems - outdated tutorials, nailing applications to library versions

No need to make life difficult for users :/

**Comment by Subhan-Zaheer** [comment]
What's the alternate to `gr.Variable` as it is removed.

**Comment by rsxdalv** [comment]
> Yes, `gr.Box` no longer exists. You should be able to achieve the same goal with `gr.Group`.

Recommendation to those unaware - gr.Group looks completely different and will break your styling, prefer using gr.Row or gr.Column and inspecting what the result looks like.
