### ISSUE TITLE
SECURITY issue - contact requested

### ISSUE THREAD

**Issue by nvn1729** [gradio-app/gradio#6816]
### Describe the bug

I have a couple of issues to report, but my email to team@gradio.app last week bounced though with this error:

```
We're writing to let you know that the group you tried to contact (team) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/gradio.app/bin/topic.py?topic=25838

Thanks,
```

Can you please provide me a different contact or enable Github vulnerability reporting? Thanks!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
N/A
```

### Severity

I can work around it

**Comment by pngwn** [comment]
Could you email `gradio-team@huggingface.co` with the details please. Apologies for the inconvenience!
