### ISSUE TITLE
Flag options and screenshots is not working with v2.8.1

### ISSUE THREAD

**Issue by kingabzpro** [gradio-app/gradio#682]
**Describe the bug**
Flag button is showing but without dropdown option and screenshot is not even showing. 

**To Reproduce**
I have use these options 👇

```python
def main():
	iface = gr.Interface(
	                     gen, 
	                     gr.inputs.Image(shape=(640,480),type='numpy'), 
	                     "image", 
	                     title = title, 
	                     flagging_options=["incorrect", "worst","ambiguous"], 
	                     allow_flagging = "manual",
	                     flagging_callback=hf_writer,
	                     description = description, 
	                     article = article, 
	                     examples = examples, 
	                     theme ="peach",
	                     thumbnail=thumbnail, 
	                     allow_screenshot=True
	                     )

	iface.launch(enable_queue=True)

if __name__ == '__main__':
	main()
```
Here is the project: https://huggingface.co/spaces/kingabzpro/savtadepth where I have enabled both custom flag options and screen shot in `app/savta_app.py` file. 

**Screenshots**
![image](https://user-images.githubusercontent.com/36753484/154812094-ee094e03-1211-49a6-96ab-eced1dd7af0e.png)

**Device information (please complete the following information):**
 - OS: HF Spaces
 - Browser: Edge
 - Gradio version: 2.8.1

**Comment by abidlabs** [comment]
Just FYI we intentionally deprecated the screenshot button because it was quite buggy and hard to support all of the edge cases.

But the flagging options should be supported, it's weird that they are not.

**Comment by abidlabs** [comment]
Should be fixed now @kingabzpro with the latest version on `master`. Feel free to build from source if you need it immediately, but we will be releasing a version out on pypi within the next couple of days.
