### ISSUE TITLE
Sketch Doesn't work after sending a single image to ImageEditor

### ISSUE THREAD

**Issue by missionfloyd** [gradio-app/gradio#6822]
### Describe the bug

When using the image editor as an output, sending it a single image (e.g., from a `gr.Image()`) results in the sketch function not working.

It works on any new layers added, but not layer 1.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

These work
```python
import gradio as gr

demo = gr.Interface(lambda x: x, inputs=gr.ImageEditor(type="pil"), outputs=gr.ImageEditor(type="pil", interactive=True))
demo.launch()
```
```python
import gradio as gr
from PIL import Image

demo = gr.Interface(
    lambda x: {"background": x, "layers": [Image.new("RGBA", x.size, (0, 0, 0, 0))], "composite": None},
    inputs=gr.Image(type="pil"),
    outputs=gr.ImageEditor(type="pil",interactive=True)
)

demo.launch()
```

This doesn't
```python
import gradio as gr

demo = gr.Interface(lambda x: x, inputs=gr.Image(type="pil"), outputs=gr.ImageEditor(type="pil", interactive=True))
demo.launch()
```

### Logs

```shell
No python or javascript errors
```

### System Info

```shell
Windows 10
Python 3.10.11
Gradio 4.10.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Can you elaborate what you mean by sketch doesn't work? I think I can repro this issue, but just want to be sure.

**Comment by missionfloyd** [comment]
https://github.com/gradio-app/gradio/assets/4073789/2ad1c03e-ec01-4c6c-8402-ab3fc89a6c4d

It's actually behaving a little differently here. Before, I couldn't draw on it at all.

**Comment by chenin-wang** [comment]
I have also encountered this bug. @abidlabs

**Comment by chenin-wang** [comment]
couldn't draw on layer1 at all, but layer2 is ok

**Comment by C0untFloyd** [comment]
Same issue here. You can draw on it but the calculated dimensions/offsets for drawing seem to very wrong. Is this actively being worked on? I can't work around it...

**Comment by abidlabs** [comment]
This is on our radar, but maybe will take a few weeks for us to get to as we have a lot of other issues we're tackling as well. We are happy to review any PRs if you'd like to contribute this fix.

**Comment by missionfloyd** [comment]
@C0untFloyd It works if you put it in a dict first.
```python
import gradio as gr
from PIL import Image

demo = gr.Interface(
    lambda x: {"background": x, "layers": [Image.new("RGBA", x.size, (0, 0, 0, 0))], "composite": None},
    inputs=gr.Image(type="pil"),
    outputs=gr.ImageEditor(type="pil",interactive=True)
)

demo.launch()
```
