### ISSUE TITLE
Option to delete cache from previous interface launches.

### ISSUE THREAD

**Issue by NeusZimmer** [gradio-app/gradio#6834]
- [x] I have searched to see if a similar issue already exists.

Is a request for a feature, a gradio created app stores some of the generated outputs under the user temp directory, to serve them to the user, leading to store a lot of temp files from previous launches, i saw it leading for a couple of thousands dir&files claiming unnecessary storage from the user filesystem

It will be great to provide an option to delete the gradio cache during every new launch, also maybe to be able to define the cache dir.

**Comment by abidlabs** [comment]
Hi @NeusZimmer thanks for creating this issue! Agreed we need to provide this. I'll close this issue only because there's a duplicate here: https://github.com/gradio-app/gradio/issues/3950

**Comment by abidlabs** [comment]
No problem!
