### ISSUE TITLE
Lite: Gallery component doesn't show images

### ISSUE THREAD

**Issue by pshashk** [gradio-app/gradio#6836]
### Describe the bug

Gallery component doesn't show images in Gradio Lite.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```html
<html>
  <head>
    <script type="module" crossorigin src="https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.css" />
  </head>
  <body>
    <gradio-lite>
    import gradio as gr    
    import numpy as np

    def gen_noise():
      return [np.random.randint(0, 256, size=(8,8,3), dtype=np.uint8) for _ in range(3)]
    
    with gr.Blocks() as demo:
        gallery = gr.Gallery()
        btn = gr.Button()
        btn.click(gen_noise, None, gallery)
    
    demo.launch()
    </gradio-lite>
  </body>
</html>
```

### Screenshot

<img width="772" alt="image" src="https://github.com/gradio-app/gradio/assets/10852024/a00a6098-e949-4ec1-8f22-3f8be20d9f19">

### System Info

```shell
Gradio lite 0.4.3
```

### Severity

Blocking usage of gradio

**Comment by whitphx** [comment]
This should be fixed in the next Lite release, thanks!
