### ISSUE TITLE
Lite: Can't load example image from URL

### ISSUE THREAD

**Issue by pshashk** [gradio-app/gradio#6837]
### Describe the bug

When specifying example image via URL the application doesn't load with the following error:
```Failed to establish a new connection: [Errno 50] Protocol not available ```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```html
<html>
  <head>
    <script type="module" crossorigin src="https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.css" />
  </head>
  <body>
    <gradio-lite>
    import gradio as gr    
    
    gr.Interface(lambda x:x, "image", "image", examples=[["https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg"]]).launch()
    </gradio-lite>
  </body>
</html>
```

### System Info

```shell
Gradio Lite: 0.4.3
```

### Severity

Blocking usage of gradio

**Comment by whitphx** [comment]
Thank you for reporting this.
WIll work on it.

---

Dev note:
The reason is a normal HTTP accessor is still used here even in the Wasm mode. It must be switched to a Pyodide-compatible method.
https://github.com/gradio-app/gradio/blob/160e3895805a45030a5e051f6bec2d399e354ad1/gradio/processing_utils.py#L193

**Comment by whitphx** [comment]
Let me introduce a workaround for such use cases.
The example app is [this](https://huggingface.co/spaces/whitphx/gradio-lite-transformers-js-object-detection), so plz see [its source code](https://huggingface.co/spaces/whitphx/gradio-lite-transformers-js-object-detection/blob/main/index.html), where
* the example file is downloaded to the file system by the `<gradio-file>` tag like `<gradio-file name="cats.jpg" url="https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/cats.jpg" />`
* then specify the downloaded file path in the `examples` option as below
```python
demo = gr.Interface(
    # ...
    examples=[
        ["cats.jpg"]
    ]
)
```

**Comment by whitphx** [comment]
One possible option is to replace `httpx` with another Wasm-compatible HTTP library, such as `urllib3`.
Seems that the `gradio` package uses only simple methods of `httpx`, so it looks easy to switch to another library.

Ref: https://github.com/gradio-app/gradio/issues/5245

**Comment by whitphx** [comment]
Anyway, `urllib3` is already installed as a dependency of `huggingface_hub`.

**Comment by whitphx** [comment]
Reopen due to #7729
