### ISSUE TITLE
body_background_fill not work in iphone and ipad

### ISSUE THREAD

**Issue by ccl-private** [gradio-app/gradio#6848]
### Describe the bug

body_background_fill not work in iphone and ipad. It works will in windows and andriod.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

gradio theme with body background image

### System Info

```shell
ios 17
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @ccl-private can you please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by abidlabs** [comment]
Closing for lack of follow up.
