### ISSUE TITLE
`gr.Plot` is rendered smaller in a hidden `gr.Tab`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#6850]
### Describe the bug

When `gr.Plot` is placed in `gr.Tab`, the graph is rendered smaller than expected in the second tab compared to the first tab even though the figures are the same.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

repro Space: https://huggingface.co/spaces/hysts-debug/gradio-plot-render-in-tab

```python
import gradio as gr
import numpy as np
import pandas as pd
import plotly.express as px

np.random.seed(0)

df = pd.DataFrame({"x": np.arange(100), "y": np.random.normal(size=100).cumsum()})
fig = px.line(df, x="x", y="y")

with gr.Blocks() as demo:
    with gr.Tabs():
        with gr.Tab(label="a"):
            gr.Plot(value=fig)
        with gr.Tab(label="b"):
            gr.Plot(value=fig)

if __name__ == "__main__":
    demo.queue().launch()
```

### Screenshot

https://github.com/gradio-app/gradio/assets/25161192/8514591a-8643-4117-97b1-60a57409c315

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.11.0
gradio_client version: 0.7.3

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.105.0
ffmpy: 0.3.1
gradio-client==0.7.3 is not installed.
httpx: 0.25.2
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.4
pillow: 10.1.0
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.2
huggingface-hub: 0.19.4
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by olex17** [comment]
The bug still exists.

**Reproduction**

https://60183a44723f473d61.gradio.live/

**System info**

Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 5.33.0
gradio_client version: 1.10.2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.3.0
audioop-lts is not installed.
fastapi: 0.115.12
ffmpy: 0.6.0
gradio-client: 1.10.2
groovy: 0.1.2
httpx: 0.26.0
huggingface-hub: 0.30.2
jinja2: 3.1.3
markupsafe: 2.1.5
numpy: 1.23.5
orjson: 3.9.15
packaging: 23.2
pandas: 2.3.0
pillow: 10.2.0
pydantic: 2.6.4
pydub: 0.25.1
python-multipart: 0.0.20
pyyaml: 6.0.2
ruff: 0.11.13
safehttpx: 0.1.6
semantic-version: 2.10.0
starlette: 0.46.2
tomlkit: 0.12.1
typer: 0.16.0
typing-extensions: 4.10.0
urllib3: 2.4.0
uvicorn: 0.28.0
mcp is not installed.
pydantic: 2.6.4
authlib is not installed.
itsdangerous: 2.1.2


gradio_client dependencies in your environment:

fsspec: 2024.9.0
httpx: 0.26.0
huggingface-hub: 0.30.2
packaging: 23.2
typing-extensions: 4.10.0
websockets: 11.0.3
