### ISSUE TITLE
Can not unselect image in the Gallery on the gradio 3.50.2

### ISSUE THREAD

**Issue by kofwin0000** [gradio-app/gradio#6851]
### Describe the bug

I'm building a image list base on Gallery, user can select and delete image in the Gallery compoment,
when i try to delete or update new image list to the Gallery. Gallery's select status doesn't change to unselect.
I try to output gr.update(value=new_images_list, selected_index=None) to Gallary, not work.
My gallary setting is gr.Gallery(label="my_label", allow_preview=False).
How to clear the select status in the Gallary?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

selected_image = gr.State()
index_state = gr.State()

# ERROR: If i have been select index 0 image before. After update the list. I can't select index 0 image in the new image list again.
def on_gallery_select(selected_image,evt: gr.SelectData):
    # collect the selected image path to state, like:
    # selected_image = 'image1.png'
    selected_image = 'image1.png'
    return selected_image


def update_gallery():
    # collect image path into new image list, like:
    # new_image_list = ['image1.png','image2.png']
    new_image_list = []

    # ERROR: If i have been select index 0 image before. After update the list. I can't select index 0 image in the new image list again.
    return gr.update(value=new_image_list, selected_index=None)

image_gallery = gr.Gallery(allow_preview=False)
image_gallery.select(fn=on_gallery_select, inputs=[selected_image], outputs=[selected_image])

update_gallery_btn = gr.Button("Flash Gallery")
update_gallery_btn.click(fn=update_gallery, inputs=None, outputs=image_gallery)

```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 3.50.2
gradio_client version: 0.6.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.6.1 is not installed.
httpx: 0.25.2
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.3
pillow: 10.1.0
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @kofwin0000 is this an issue in the latest version of gradio? (4.11.0)? I believe we've already squashed this bug

**Comment by kofwin0000** [comment]
> Hi @kofwin0000 is this an issue in the latest version of gradio? (4.11.0)? I believe we've already squashed this bug

No, it's happend in the version of gradio (3.50.2). I haven't try to use gradio 4.

**Comment by abidlabs** [comment]
Hi @kofwin0000 could you please upgrade to Gradio 4.11.0 and see if the issue persists? We're only actively supporting bug fixes and feature requests in Gradio 4.x.

**Comment by kofwin0000** [comment]
非常遗憾，我的项目已经在 gradio 3.50.2 上面做了许多开发。由于时间紧迫，暂时不打算将 gradio 升级到4.x。

**Comment by kofwin0000** [comment]
> Hi @kofwin0000 could you please upgrade to Gradio 4.11.0 and see if the issue persists? We're only actively supporting bug fixes and feature requests in Gradio 4.x.

Unfortunately, my project has done a lot of work on gradio 3.50.2. Due to time constraints, we do not plan to upgrade gradio to 4.x at this time.

**Comment by abidlabs** [comment]
That’s fair @kofwin0000 but in that case I’ll need to close this issue given that we are only updating Gradio 4.x. Please let me know if you find this issue if you try the latest version of Gradio and we can reopen.
