### ISSUE TITLE
Dropdown doesn't retain value if choice name is changed

### ISSUE THREAD

**Issue by Donkie** [gradio-app/gradio#6853]
### Describe the bug

I need to update the names of choices in the dropdown, which I do using the gr.update. The choices change name correctly, but the already selected value in the dropdown is not retained, despite the value in tuple is unchanged.

I have also tried changing the gr.update to also include `value="IdA"` but that doesn't help.

I expect the dropdown to automatically update the name of the selected item, without it becoming gray.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
from dataclasses import dataclass

import gradio as gr

@dataclass
class Data:
    """Some data."""

    name: str
    key: str

my_data: list[Data] = [Data("Choice A", "IdA"), Data("Choice B", "IdB")]

def tb_edit(current_choice: str, new_name: str):
    for item in my_data:
        if item.key == current_choice:
            item.name = new_name

def update_choices():
    return gr.update(choices=[(c.name, c.key) for c in my_data])

with gr.Blocks() as blocks:
    dd = gr.Dropdown(choices=[(c.name, c.key) for c in my_data])
    tb = gr.Textbox(label="Edit Name")
    tb.submit(
        tb_edit,
        inputs=[dd, tb],
    ).then(
        update_choices,
        outputs=[dd],
    )

blocks.launch()
```

### Screenshot

[Screencast from 2023-12-20 11:40:13.webm](https://github.com/gradio-app/gradio/assets/2332094/5e10237a-d3e6-4f83-a75f-8afe0779c890)

### Logs

```shell
No errors.
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.11.0
gradio_client version: 0.7.3

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.3 is not installed.
httpx: 0.25.1
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.1
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.3
pillow: 10.1.0
pydantic: 2.5.1
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.1
huggingface-hub: 0.19.4
packaging: 23.2
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by byteconcepts** [comment]
Same here.

And btw:
My dropdown used in blocks does not show a (selected) value on initialisation.
Not from a function, not from an array and also not from a string, directly given as... 
   value="My initial selection"

Also tried it in firefox and chrome - Same.

**Comment by michaelgrewal** [comment]
I'm also having this issue.

I spent the last few hours trying to figure it out but really glad I came across this thread.
