### ISSUE TITLE
Add a way to disable the warning for a long queue

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#6857]
- [x] I have searched to see if a similar issue already exists.

[internal thread](https://huggingface.slack.com/archives/C02QZLG8GMN/p1703039430161869)

Currently, when the queue of a Space is long, a warning that says "There is a long queue of requests pending. Duplicate this Space to skip." will be shown as `gr.Warning`. But this is not always the desirable behavior because duplicating it may not work, for example it doesn't work if the Space is calling an API. So it would be nice to be able to disable the warning.

![](https://github.com/gradio-app/gradio/assets/25161192/8802955f-4db7-4225-83eb-7c8579e72c26)

(I think it would be nice to be able to change the message and when/whether it's shown as well.)

**Comment by freddyaboulton** [comment]
Going to close as this issue is very low priority and I don't think it warrants another parameter in `launch`.

**Comment by TonyAssi** [comment]
I would also like to have to this functionality.
