### ISSUE TITLE
Is there a way to show clickable url links in Textbox label?

### ISSUE THREAD

**Issue by cryoco** [gradio-app/gradio#6861]
- [x] I have searched to see if a similar issue already exists.

**Comment by abidlabs** [comment]
Hi @cryoco no this is not possible. You could potentially use `gr.Markdown()` for this. By the way, for general questions like this (that are not feature requests or bug reports), please ask in [our Discord](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
