### ISSUE TITLE
gr.Video output showing empty 

### ISSUE THREAD

**Issue by yadavj2008** [gradio-app/gradio#6872]
### Describe the bug

**Problem statment:**
Trying to use gradio Video feature to allow apps to capture video from webcam, when clicking on record and submit video button a function process_video() get trigger, this function takes video as input and process further, looks like the gr.Video is not sending the video bytes to the function, hence, function call return None every time.

**Expected behaviour:**

The user should be able to capture gr.Video output and pass it to the function

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr


def video_flip(video):
    if video is None:
        print("No Video")
    return video


iface = gr.Interface(video_flip, gr.Video(sources="webcam"), "playable_video")

iface.launch(share=False, debug=True)
```

### System Info

```shell
gradio                           4.11.0
gradio_client                    0.7.3

OS: MacOS
Notebook: Colab
```

### Severity

Blocking usage of gradio

**Comment by yadavj2008** [comment]
Hi @abidlabs Can you please help on this?. Thanks

**Comment by abidlabs** [comment]
I can repro this issue, we'll take a look!

**Comment by yadavj2008** [comment]
Hi @dawoodkhan82 thanks a lot for fixing this video issue, I just tested the PR changes and it looks like the video output is working for gr.Interface but not for gr.Blocks. Can you please check and see if there is any issue with block or I'm doing something wrong?.

**Comment by abidlabs** [comment]
Hi @yadavj2008 can you provide a code snippet with gr.Blocks that is not working for you?

**Comment by yadavj2008** [comment]
Hi @abidlabs,
I noticed that the issue was in my application was due to the longer video rendering time, i did a quick test using below sample code and it seems that Gradio is taking approx 1 min to render a 2secs video. Is there any way to optimise the performance?.

```
import gradio as gr

def video_flip(video):
    if video is None:
        print("No Video")
    return video

with gr.Blocks() as demo:
      with gr.Row():
        video_in = gr.Video(sources="webcam",format="mp4",include_audio=True)
        video_out = gr.Video(show_label=False)
        submit = gr.Button("Submit")
        submit.click(fn=video_flip, inputs=video_in, outputs=video_out)

demo.launch(share=False, debug=True)

```

**Comment by yadavj2008** [comment]
Any further update on this?. Also, looks like the patch only works when I have "share=False"

**Comment by abidlabs** [comment]
We have a work-in-progress PR: #6905. Once the PR is merged in, we'll do a patch release to get it out. Sorry its taking a while!

**Comment by yadavj2008** [comment]
Hi @abidlabs , @dawoodkhan82, Thanks a lot for the merging the fix. I just compiled the latest gradio code from main branch, looks like webcam recording working only if I use share=false not with share=true. Do I need to make any config changes in the code to make it work for public links?.

**Comment by abidlabs** [comment]
Installing from main doesn’t support share=True but we’ll release a version to pypi soon, probably early next week
