### ISSUE TITLE
Unable to important gradio

### ISSUE THREAD

**Issue by MayaAmelieSeale** [gradio-app/gradio#6879]
### Describe the bug

Unable to import gradio. keep getting error "cannot import name 'TypeAliasType' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)" - despite trying every solution on internet. restarted runtime many times.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-43-bed51628844d>](https://localhost:8080/#) in <cell line: 7>()
      5 
      6 
----> 7 import gradio as gr
      8 
      9 def greet(name):

18 frames
[/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_core_utils.py](https://localhost:8080/#) in <module>
     14 from pydantic_core import CoreSchema, core_schema
     15 from pydantic_core import validate_core_schema as _validate_core_schema
---> 16 from typing_extensions import TypeAliasType, TypeGuard, get_args, get_origin
     17 
     18 from . import _repr

ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)

### Screenshot

<img width="1382" alt="Screen Shot 2023-12-24 at 1 21 31 AM" src="https://github.com/gradio-app/gradio/assets/140470683/09aa24d9-9d19-48c5-be7d-a9b7045b7559">

### System Info

```shell
gradio 4.12, google colab, python 3.10.12
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Yes, as @yadavj2008 said, you probably need to restart the Colab session after installing Gradio. The reason is that Gradio requires `typing_extension>=4.6.0`. This is included in Gradio's requirements, but Colab probably comes with an older version of `typing_extension` by default. You could alternatively put the Gradio installation step as the first cell of your Colab notebook.
