### ISSUE TITLE
UI issue while adding Gemini API using Gradio. ChatInterface

### ISSUE THREAD

**Issue by Soumya95** [gradio-app/gradio#6881]
### Describe the bug

I have created a very basic gradio based UI for integrating Gemini API. The following is the code snippet :

```
from google.cloud import aiplatform
import vertexai
from vertexai.preview.generative_models import GenerativeModel, Part
import gradio as gr

def generate(prompt, chat_history):
    print(prompt)
    chat_history = chat_history or [];
    model = GenerativeModel("gemini-pro")
    if prompt :
        response = model.generate_content(
            prompt,
            generation_config={
                "max_output_tokens": 2048,
                "temperature": 0.9,
                "top_p":1
            },
            stream=False,
        )

    output = response.candidates[0].content.parts[0].text
    if not chat_history:
        return output
    return chat_history.append((prompt, output))

iface = gr.ChatInterface(generate)


if __name__ == "__main__":
    iface.launch()

```

I am using the new functionality provided by *Gradio : ChatInterface* https://www.gradio.app/docs/chatinterface . Now the problem is the chat history is showing the user input (/prompt) twice in the Chat interface. As per the documentation, I have returning the chat_history.append((prompt, output)) as it was mentioned as follows :

> the function to wrap the chat interface around. Should accept two parameters: a string input message and list of two-element lists of the form [[user_message, bot_message], ...] representing the chat history, and return a string response. 

Can you tell me where I am doing wrong ?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
from google.cloud import aiplatform
import vertexai
from vertexai.preview.generative_models import GenerativeModel, Part
import gradio as gr

def generate(prompt, chat_history):
    print(prompt)
    chat_history = chat_history or [];
    model = GenerativeModel("gemini-pro")
    if prompt :
        response = model.generate_content(
            prompt,
            generation_config={
                "max_output_tokens": 2048,
                "temperature": 0.9,
                "top_p":1
            },
            stream=False,
        )

    output = response.candidates[0].content.parts[0].text
    if not chat_history:
        return output
    return chat_history.append((prompt, output))

iface = gr.ChatInterface(generate)


if __name__ == "__main__":
    iface.launch()

```

### Screenshot

![Screenshot 2023-12-26 at 9 30 28 AM](https://github.com/gradio-app/gradio/assets/12010944/bf725b72-2f24-4a82-9c3e-60223dc6e669)

### System Info

```shell
4.11.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @Soumya95 when you are using the `ChatInterface` abstraction, you don't need to worry about returning a tuple, instead just return a string response from your function, as mentioned here: https://www.gradio.app/guides/creating-a-chatbot-fast#defining-a-chat-function

So I think if you modify your function like this:

```py
from google.cloud import aiplatform
import vertexai
from vertexai.preview.generative_models import GenerativeModel, Part
import gradio as gr

def generate(prompt, chat_history):
    print(prompt)
    chat_history = chat_history or [];
    model = GenerativeModel("gemini-pro")
    if prompt :
        response = model.generate_content(
            prompt,
            generation_config={
                "max_output_tokens": 2048,
                "temperature": 0.9,
                "top_p":1
            },
            stream=False,
        )

    output = response.candidates[0].content.parts[0].text
    return output

iface = gr.ChatInterface(generate)


if __name__ == "__main__":
    iface.launch()
```

it should work

**Comment by scheung38** [comment]
@abidlabs : In last example why is chat_history not used?
