### ISSUE TITLE
Drag and Drop not working for gradio.File when using a specific file_types like `.txt`

### ISSUE THREAD

**Issue by apmoore1** [gradio-app/gradio#6888]
### Describe the bug

The drag and drop feature is not working for [gradio.File](https://www.gradio.app/docs/file) when using a specific `file_types` like `.txt` or `.pdf` (other file types not explored) BUT will work if you specify a broader file type like `text`.

In the reproduction code if you replace `.txt` with `text` the drag and drop feature will work.

This drag and drop feature also appears not to be working on the [Pull Request `zip_files` tab demo](https://huggingface.co/spaces/gradio-pr-deploys/pr-6887-all-demos) which might be due to the same issue of specifying files types that have a `.` in them (taken from the [demo code on line 15](https://huggingface.co/spaces/gradio-pr-deploys/pr-6779-all-demos/blob/main/demos/zip_files/run.py#L15)):
``` python
gr.File(file_count="multiple", file_types=["text", ".json", ".csv"])
```

I have tested this on Mac and Ubuntu (22.04.3 LTS). I have provided the system information for the Mac, but can also provide it for Ubuntu if needed.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
 
 
def print_uploaded_file(file_path: str) -> None:
    with open(file_path, 'r', encoding='utf-8') as fp:
        gr.Info(fp.read())
 
 
with gr.Blocks() as demo:
    file_uploader = gr.File(file_count='single', type='filepath',
                            file_types=['.txt'])
    file_uploader.upload(print_uploaded_file, inputs=[file_uploader])
 
demo.launch(debug=True, share=False)
```

### System Info

```shell
Running this on an Apple Mac Air (M1) Processor in a Conda environment version 23.10.0, platform: osx-arm64.
Running Python version: 3.10.13

Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.12.0
gradio_client version: 0.8.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.105.0
ffmpy: 0.3.1
gradio-client==0.8.0 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.1
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.4
pillow: 10.1.0
pydantic: 2.5.3
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.25.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.26.0
huggingface-hub: 0.20.1
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by yvrjsharma** [comment]
I think it should be `file_types=['text']` in your repro. I am able to use the drag and drop feature correctly with this change in your provided code.

**Comment by abidlabs** [comment]
cc @dawoodkhan82

**Comment by dawoodkhan82** [comment]
Will take a look
