### ISSUE TITLE
Invalid non-printable ASCII character in URL

### ISSUE THREAD

**Issue by ulinnuhaha** [gradio-app/gradio#6889]
### Describe the bug

get this message error "Invalid non-printable ASCII character in URL" when running Gradio interface using miniconda

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/28559238/1910a922-e1c5-4e47-8d48-381015ef2b3e)

### System Info

```shell
gradio>=3.18.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @ulinnuhaha we'll need more info to reproduce this issue. Does this happen for you in the latest version of Gradio? And in a reproducible environment such as Colab notebook?

**Comment by abidlabs** [comment]
Closing for lack of follow up. We can reopen with a repro
