### ISSUE TITLE
Include a mechanism to capture query parameters when the application is being built

### ISSUE THREAD

**Issue by Onturenio** [gradio-app/gradio#6891]
I'd like to be able to adapt my application based on some query parameters. The idea is to capture some `language` keyword in the query and use it to translate various UI elements like buttons and so.

The functionality I need is close to [`gr.Request`](https://www.gradio.app/docs/request). However, this mechanism allows you to get query parameters when a gradio element is triggered. I need to have these parameters when the application is being built within a `gr.Block` environment. I have been trying to figure out if there is a way to get this infro using `gr.Request` but I think it is not currently possible.

Perhaps more generally, it would be nice to have some sort of _initialisation trigger_. That you can use to setup your application when the server responds to the query from the client. This would allow the developers to reboot and setup the application each time a new session is established.

**Comment by abidlabs** [comment]
Hi @Onturenio you can trigger an event using the `Blocks.load()` event, which fires as soon as the Gradio app is opened in a browser. This event also has access to `gr.Request()`. 

Something like this:

```py
def startup_func(request: gr.Request):
  ...

with gr.Blocks() as demo:
  ...
  demo.load(startup_func, None, None)
```

I think that should do what you need, if not please feel free to respond and I can reopen this issue.

**Comment by Onturenio** [comment]
Thanks, I had missed that functionality.

There is still a small caveat. I use this mechanism to translate the labels etc. of my application. I set it to english by default within the `Block` construct, and then use the `load` method to update a bunch of elements based on the query.

The problem is that this second loading takes about 1 second, so the application is shown in english, and then changed to other language. It's OK but this jump doesn't look very professional. Is there an implemented mechanism to avoid this step? I think not, but I'm not sure.

Thanks!

**Comment by abidlabs** [comment]
Thanks @Onturenio currently, I don't have a good workaround to avoid the loading time. We do have this exact functionality on the roadmap: https://github.com/gradio-app/gradio/issues/2465, but it will probably be a few months out

cc @hannahblair
