### ISSUE TITLE
Could not create share link in a docker container embedded in an Internet-restricted environment.

### ISSUE THREAD

**Issue by NanPhi** [gradio-app/gradio#6895]
### Describe the bug

I am in a Internet-restricted environment where some websites like huggingface.co or google.com are not accessible while other websites are available. I installed gradio in a docker container. When I ran the tutorial as below, it will output Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python

import gradio as gr
def greet(name):
    return "Hello"+name+"!"
demo = gr.Interface(fn=greet, inputs="text", outputs="text")
demo.launch(share=True)

```

### Logs

```shell
Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.
```

### System Info

```shell
host environment: 
     Distributor ID:	    Ubuntu
     Description:	    Ubuntu 20.04.6 LTS
     Release:	            20.04
     Codename:	            focal
docker version:
     Version:               20.10.21
     API version:           1.41
     Go version:            go1.18.1
     Git commit:            20.10.21-0ubuntu1~20.04.2
     Built:                 Thu Apr 27 05:56:19 2023
     OS/Arch:               linux/amd64
     Context:               default
     Experimental:          true
gradio environment:
     Operating System:      Linux
     gradio version:        3.50.2
     gradio_client version: 0.6.1
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @NanPhi that's correct, you need to be able to access huggingface.co as well as gradio.live in order to create a share link. We'll post a comprehensive tutorial on what's needed for share links soon https://github.com/gradio-app/gradio/issues/5083
