### ISSUE TITLE
🙋 Community Feedback on Blocks

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#690]
#### What is Blocks?

Blocks allows you to build web-based demos in a flexible way using the `gradio` library. Blocks is a more low-level and flexible alternative to the core `Interface` class. Specifically, Blocks support:
* grouping together related demos using Tabs
* flexible positioning of components using Columns, Rows, etc. and the ability to add explanatory Markdown or Text at any point
* flexible data flows (e.g. any number of input and output components can be displayed on screen, and functions can define data flow between any subset of inputs and outputs)
* flexible event triggers (e.g. button clicks, element changes, etc.)

Here's an example Block:

![Recording 2022-02-22 at 11 54 03](https://user-images.githubusercontent.com/1778297/155180109-d84ecc00-b3f8-4282-b103-4918aac931ad.gif)
 
If you've used Gradio before, you'll find that Blocks still allows you to build web apps:
* entirely in Python
* using the standard Python interpreter, which means it will run in Jupyter notebooks, colab notebooks, or any Python IDE

#### Getting Started with Blocks
* Blocks is just released with Gradio 3.0. Check here for the announcement. 
* To use it, please install the latest release of Gradio: `pip install gradio`
* TODO: Add [Blocks Introduction Guide Link]

You can also use Blocks in Spaces! See an example [here](https://huggingface.co/spaces/aliabd/blocks-image-audio).

----------

#### *Giving feedback*: In the comments below, we'd love to hear from you:

* Did Blocks allow you to build something cool? Share a screenshot or a link to a Blocks Demo!
* Does Blocks *not* support your use case? Let us know too so that we can support it!
* Did you find anything confusing or hard within the syntax or usage of Blocks? Let's improve it together!

**Comment by nateraw** [comment]
Really looking forward to this feature! In colab, I'm running into an issue. [Here's a notebook.](https://gist.github.com/nateraw/147d1bd360263022ac3639ddd961fec0)

`AttributeError: 'Blocks' object has no attribute 'requires_permissions'`

Looks like some env variable I'm supposed to set/isn't set properly?

**Comment by abidlabs** [comment]
Hi folks! I just built a `Block` to plot projectile trajectories when a user specifies the speed and angle of the projectile. 

**Screenshot**

![image](https://user-images.githubusercontent.com/1778297/155348930-bbe7977b-f6d0-4261-9772-34bbe6367067.png)

**Code**

```python
import gradio as gr
import matplotlib.pyplot as plt
import numpy as np


def plot(v, a):
    g = 9.81
    theta = a/180*3.14
    tmax = ((2 * v) * np.sin(theta)) / g
    timemat = tmax*np.linspace(0,1,40)[:,None]

    x = ((v * timemat) * np.cos(theta))
    y = ((v * timemat) * np.sin(theta)) - ((0.5 * g) * (timemat ** 2))
    
    fig = plt.figure()
    plt.scatter(x=x, y=y, marker='.')
    plt.xlim(0, 100)
    plt.ylim(0, 60)
    return fig

block = gr.Blocks()

with block:
    gr.Markdown("Let's do some kinematics! Choose the speed and angle to see the trajectory.")
    
    with gr.Row():
        speed = gr.inputs.Slider(1, 30, default=25, label="Speed")
        angle = gr.inputs.Slider(0, 90, default=45, label="Angle")
    output = gr.outputs.Image(type="plot")
    btn = gr.Button("Run")
    btn.click(plot, [speed, angle], output)

block.launch()
```

**Feedback**
* Very quick and easy to put together a demo for this. I like how the output plot is hidden until the button is clicked
* The labels don't appear next to the sliders like I expected (#704)
* The plot output looks kind of ugly with the gray background (#711). It would be nicer if it was wider or the width could be adjusted
* Is it possible to adjust the width/color/style of the run button?
* I would actually prefer if the run button didn't have to come at all, and instead, the demo refreshed any time I changed the sliders (#723) 

I have created feature request issues for some points of feedback above

**Comment by aliabd** [comment]
Built a `block` that can convert text to either audio or an image, depending on user's choice. 

**Demo**
<img width="1227" alt="Screen Shot 2022-02-24 at 5 13 54 PM" src="https://user-images.githubusercontent.com/9021060/155530719-c6edaccc-2633-412e-871f-302257a98f87.png">

**Code**
```python
import gradio as gr

fastspeech = gr.Interface.load("huggingface/facebook/fastspeech2-en-ljspeech")
clip = gr.Interface.load("spaces/DrishtiSharma/Text-to-Image-search-using-CLIP")


def text2speech(text):
    return fastspeech(text)


def text2image(text):
    image = clip(text)[0]
    return gr.processing_utils.decode_base64_to_image(image)


block = gr.Blocks()

with block:
    text = gr.inputs.Textbox(placeholder="Try writing something..")

    with gr.Column():
        with gr.Row():
            get_audio = gr.Button("generate audio")
            get_image = gr.Button("generate image")
        with gr.Row():
            speech = gr.outputs.Audio()
            image = gr.outputs.Image()


    get_audio.click(text2speech, inputs=text, outputs=speech)
    get_image.click(text2image, inputs=text, outputs=image)

block.launch()
```

**Feedback**
A few issues I faced with this and other demos:
* Markdown doesn’t seem to actually render markdown. Am I missing something? https://github.com/gradio-app/gradio/issues/729
* State (with Chatbot) throws an error https://github.com/gradio-app/gradio/issues/730
* Can we get string shortcuts for components like in `Interface`? https://github.com/gradio-app/gradio/issues/731
* Is there a way to remove the need for a button and mimic `live=True` behavior? Documented by @abidlabs in https://github.com/gradio-app/gradio/issues/723
* The output has no loading feedback. https://github.com/gradio-app/gradio/issues/732
* label not showing. Documented by @abidlabs in https://github.com/gradio-app/gradio/issues/704
* I would like to build a workflow where the output of a model is the input of another. but I can't pass `gr.outputs.<etc>` as an input to something 
* Can we build a component for examples? 
* I would like to build a conditional workflow based on output/selected input. something like a radio input "pick one of these options" and based on choice show them one of two inputs (and run one of two functions)

**Comment by FarukOzderim** [comment]
Regarding the last example the output is changing its position and size, it looks nice and well, however the positioning was not defined like that in the code.

- Generate image
![image](https://user-images.githubusercontent.com/44067394/155566884-0d6c4398-f137-4b72-a526-9c5901f208c6.png)

- Then generate audio

![image](https://user-images.githubusercontent.com/44067394/155566977-43f3ac59-b050-410a-b8db-25cfbbb811a8.png)

**Comment by nateraw** [comment]
Have there been any discussions about an interface list as opposed to the context manager/blocks solution?

I think this sort of thing reads a bit better. It would sacrifice "shared" components from the blocks, but it would make it easier to define inputs/outputs via the shortcuts as opposed to having to define each input class instance explicitly.


```python=
interface_a = gr.Interface(
    fn_a,
    inputs='sketchpad',
    outputs='label',
    title='Pictionary App'
)

interface_b = gr.Interface(
    fn_b,
    inputs='text',
    outputs='image',
    title="Text to Image App"
)

# InterfaceList does not exist, just an idea
gr.InterfaceList([interface_a, interface_b]).launch()
```

**Comment by abidlabs** [comment]
This is a really nice suggestion @nateraw. As a broader point, do you find that the `blocks` syntax is difficult to use? Or is it more that you feel that that this use case (of combining interfaces together) is common and should be easier to write?

If it's the second, then we have an idea that I'd like your feedback on. A `block`-ish of doing what you want could potentially look like this:

```python
interface_a = gr.Interface(
    fn_a,
    inputs='sketchpad',
    outputs='label',
)

interface_b = gr.Interface(
    fn_b,
    inputs='text',
    outputs='image',
)

with block as Blocks():
  with Tab("Pictionary"):
    interface_a
  with Tab("Text to Image"):
    interface_b

  block.launch()
```

What do you think about this syntax? Is it intuitive for you? I've proposed that we should support this in #640

**Comment by nateraw** [comment]
I found having to do 2 nested `with`s to be not so intuitive. This is just one opinion from one person though!

The `blocks` syntax reminds me of the column/row management experience in streamlit, which I find for the most part to be confusing, and I see most folks (non-power users) just not using it - and if they do, the code is hard to read imho.

At the end of the day, if the point/driving force behind this feature is to allow folks to have more than one interface in one hosted gradio app, I think we should make it as easy as possible to do just that.

Would really love some other community members to weigh in on this, so we can see what they think. 😄

**Comment by JuanCarlosMartinezSevilla** [comment]
I'm not sure if I am understanding blocks the right way, but what I feel users want is a way to dinamically load the different inputs from others. For example if you want to have 2 functionalities in the interface you can just put a gr.input.Radio and then depending and what you have clicked... load other gr.input components. 

In my case I would also love to see some way to reload individual components like in this case (see the image) . I've selected the class Staff and when I submit, I would love to be able to reload the component without the option Staff. Beware I am using Gradio as an input for different configurations to execute a model.

If you have any doubt about my use case you can reply me. Thank you for reading!

![ModelInterface](https://user-images.githubusercontent.com/97530443/155696961-e24ff06e-4cac-483f-bbb2-10de575d1370.png)

**Comment by aliabd** [comment]
@chuachinhon the simplest way to get spaces to use the right version is to include these 2 lines at the top of app.py
```python
import os
os.system('pip install gradio==2.8.0b20')
```
That being said, this current beta version doesn't work on spaces. We're woking on an update that will soon. 

In the meantime, would love to hear more of your thoughts. Does this setup work for what you want? Aside from grouping apps together, is there another flow you'd like to support? Any other feedback? :)

**Comment by aliabd** [comment]
@JuanCarlosMartinezSevilla thanks for the feedback! Yes, these are all cases we'd like to support, so thanks for documenting them. For clarity will list them here:
* Loading inputs based on user choice (also see https://github.com/gradio-app/gradio/issues/738)
* Using examples as a component and positioning on the screen (also see https://github.com/gradio-app/gradio/issues/737)
* Modify components after an event. Can you open an issue for this so we can track it separately? Use this link to create the issue: https://github.com/gradio-app/gradio/issues/new?assignees=&labels=&template=feature_request.md&title=[Blocks]

**Comment by aliabd** [comment]
@nateraw thanks for the feedback! let's continue the conversation on https://github.com/gradio-app/gradio/issues/640

**Comment by aliabd** [comment]
@chuachinhon we've updated the beta to `v2.8.0b22` and it works on spaces now! You can see an example [here](https://huggingface.co/spaces/aliabd/blocks-image-audio).

**Comment by chuachinhon** [comment]
> @chuachinhon we've updated the beta to `v2.8.0b22` and it works on spaces now! You can see an example [here](https://huggingface.co/spaces/aliabd/blocks-image-audio).

Nice! Will try it out in a bit

**Comment by abidlabs** [comment]
Inspired by @simoninithomas, I created an interface that shows 2 chatbots side by side and allows a user to talk with either one. Putting a basic placeholder together was actually super easy and lots of fun:

**Demo**

![image](https://user-images.githubusercontent.com/1778297/155837365-46e441d7-8114-493f-9d66-7b8c388f2be1.png)


**Code**
```python
import gradio as gr
import random

history1 = []
history2 = []

def chatbot1(text):
    history1.append((text, "Why?"))
    return history1

def chatbot2(text):
    history2.append((text, "I don't understand"))
    return history2

block = gr.Blocks()

with block:
    gr.Markdown("Talk to either of these chatbots:")
    
    with gr.Row():
        display1 = gr.outputs.Chatbot()
        display2 = gr.outputs.Chatbot()

    with gr.Row():
        text1 = gr.inputs.Textbox()
        text2 = gr.inputs.Textbox()

    with gr.Row():
        button1 = gr.Button(label="Chat")
        button2 = gr.Button(label="Chat")
    
    button1.click(chatbot1, text1, display1)
    button2.click(chatbot2, text2, display2)
        
block.launch()
```

**Feedback**

1. Regarding the layout, it would have been a little cleaner if I could use 2 columns instead of 3 rows. (#637)
2. I had no idea how to use state with Blocks. The code above shares the history across all users, which is not good if you are sharing this Block with multiple people (created a new issue: #743)
3. It would be easier if I could recycle my old Gradio Interface chatbot code, which I had already written, as part of this Block. (#640)

Combining issues 1-3 together, here's how I'd like for the code to look for my Block:

```python
 block = gr.Blocks()

with block:
    gr.Markdown("Talk to either of these chatbots:")
    
    with gr.Column():
      gr.Interface(chat1, ["text", "state"], ["chatbot", "state"], layout="vertical")
    with gr.Column():
      gr.Interface(chat2, ["text", "state"], ["chatbot", "state"], layout="vertical")
        
block.launch()
```

Other points of feedback:
* The `Chatbot` output interface should support a color map argument (similar to `HighlightedText`)
* It would be nice if the textbox cleared after you click submit. Perhaps this could be a parameter in the `Textbox` component?
* The fact that outputs are "hidden" before they are outputted to, can cause some confusion. So for example, this is how the demo looks before you chat with either bot:

![image](https://user-images.githubusercontent.com/1778297/155837303-4d74b2a1-0bdd-4883-9ce1-2c67f4dd91e0.png)

And this is how it looks after you chat with just the first one:

![image](https://user-images.githubusercontent.com/1778297/155837315-d191bfc1-dc2f-4a65-b85f-bd62ba22bdb8.png)

Perhaps we _should_ show the output components by default?

**Comment by chuachinhon** [comment]
Hi @abidlabs and team: 2 quick questions on using Parallel and Series with Blocks. I've deployed a new demo on Spaces so it'll be easier to see what I mean: https://huggingface.co/spaces/chinhon/headlines_blocks_parallel_series

For Parallel: 
- is there a way to "stack" the outputs on top of each other in 2 different windows, like gr.Interface?
- I've tried to work around it, but current version of Block seems to display the Parallel outputs in columns or as a list. See attached screen grabs.
![blocks_parallel](https://user-images.githubusercontent.com/47172028/156123885-61cd8cb1-da04-495d-b33a-0c4fe59f9bcb.png)
![blocks_parallel2](https://user-images.githubusercontent.com/47172028/156123905-8caece7f-5d07-4064-9f9d-636bacd34b4f.png)

For Parallel and Series:
- would performance slow significantly by combining Parallel and Series under the hood of one app via Block? I've not tested the run times exhaustively, and the app seems to run ok so far on Spaces.

Overall, I'd say Blocks still works for me mostly as an organisatonal tool to put similar apps together. I've tried out a few version using blocks to combine different inputs and processing functions, but found myself bogged down with unnecessary complexities after a while - which detracts from the main draw of Gradio, in my view. 

But that's just me/my use case. Others might have better use cases for the other features.

**Comment by Lastly** [comment]
I have tried out blocks now and have a few pieces of feedback. I found it easy to use and was able to make my desired layout quickly with one button outputting to multiple tabs with different views. Building an interface with rows/columns is intuitive to me, very HTML-like. I prefer the control compared to the previous 'magic' of the standard interface. I think this new UI type will be useful for multi-step processes and for making more app-like complex demos. Having this as a more advanced option is perfect, with the standard Gradio UI as default. 

Areas to improve:
- It seems that the default dark theme is not supported (text stays black)
- With added layout customization, supporting custom CSS is very much desired 🙏 
- Input elements should not change in size relative to the output (add flex-shrink: 0)
- Output elements should have a min and max width to keep styles clean

**Comment by Lastly** [comment]
I would love to see step-gating implemented in blocks as well. For example, a multi-stage demo could have tabs 'Step 1', 'Step 2', etc. To make this user-friendly the inputs (tabs, buttons, text inputs) should ensure that step 1 is completed before letting the user engage with step 2.

This could be done accomplished by an enable/disable option `if step1: step2.enable()` or by a requires argument `step2.click(requires=step1, ....)`.

**Comment by prakharrathi25** [comment]
Hi, 

I am trying to build an application which would hide components based on other components. So, for example there can be a checkbox which lets me decide which components I want to show at a time. Here is what the logic looks like. 

```python 
if checkbox1 == True: 
    show_text_input("Name?")
	show_text_input("Age?") 

if checkbox2 == True: 
    show_text_input("Company Name?")
	show_text_input("Job Title?")
```

checkbox1 components should not interfere with checkbox2 components. For ML, I can use one section for model training, one for inference and one for model re-training. I don't know if I was articulate enough but this is basically my use case. Is there I can do something like this in Gradio?

**Comment by abidlabs** [comment]
Thanks for the feedback @Lastly and @prakharrathi25! I have created an issue around the step-gating / visibility issue that you guys have mentioned: #784

**Comment by Lobe-n** [comment]
Hi,
I wanted to test out the events that were implemented with the new [release](https://github.com/gradio-app/gradio/releases/tag/v2.9.0), by replacing the line `btn.click()`  in this [example](https://github.com/gradio-app/gradio/issues/690#issuecomment-1048900369) with either
`
block.change(plot, [speed, angle], output)
`
`
row.change(plot, [speed, angle], output)` where `row=gr.Row()` that contains the sliders
or
`
speed.change(plot, [speed, angle], output)
`
but could't get it to work, i.e. the plot does not appear when/after I drag the sliders. Should this be doable already or are the events not yet finished?

**Comment by abidlabs** [comment]
Hi @Lobe-n! Thanks for checking. This isn't out in the public release yet, but we are hoping to get it out soon. If you'd like to get a head start, try this: `pip install gradio==2.7.0b70` and let me know how it goes!

**Comment by Lobe-n** [comment]
Thank you @abidlabs,
I can see how this is still in beta ^^ but yes, with this build the interface updated when using the sliders although the interface lags a bit while/after dragging the slider, looking forward to the release of more blocks features :)

**Comment by brenden-connors** [comment]
Hello! Really enjoying working with Gradio!

I am curious about using themes with blocks, perhaps I am not understanding correctly. If I am trying to apply a theme like 'dark-peach' to the entire demo, how do I go about doing that? For example the following demo applies the theme to the output only, and the rest seems to lose the original styling.

`import gradio as gr

demo = gr.Blocks()
demo.theme = 'dark-peach'
with demo:
    
    with gr.Row():
        t1 = gr.inputs.Textbox()
        t2 = gr.outputs.Textbox()
    b1 = gr.Button('run')
        

    
    b1.click(lambda x:x, t1, t2)
demo.launch()`

**Comment by abidlabs** [comment]
Great question @brenden-connors! We are still working on themes with `Blocks`. We are planning on launching with a `default` and a `dark` theme next week, but then adding more themes over time. Right now, you won't find themes working correctly, but eventually something like `gr.Blocks(theme="dark-peach")` should work! cc @pngwn

**Comment by pngwn** [comment]
Every theme will have a light and dark mode. This will be toggleable by the user but, by default, respect system preferences.

So in this case you would just select (`theme=peach`) and both light and dark variants of that theme will be available to users of the app.

**Comment by brendenconnors** [comment]
I thought I would share my example using Blocks in gradio version 2.9b23.
This use case would be for time series like data. My "model" here would be to predict the sentiment of a user's next tweet given their last 4 tweets sentiment, with timestamps. 

This interface results in 8 total inputs for the user which can be a lot. For model exploration, it may be better for the user to actually grab a real input sequence and perturb that existing sequence to see how the output changes. This sort of random button fill when there are many outputs was much easier than I imagined and am very happy with how it turned out. Great work!

```#This is using gradio version '2.9b23'
import gradio as gr
import numpy as np

sentiment = ['positive', 'negative', 'neutral']
timestamp = list(range(50))
test_data = [[(np.random.choice(timestamp), np.random.choice(sentiment)) for _ in range(0,4)] for _ in range(0, 10)]

demo = gr.Blocks()
with demo:

    with gr.Tabs():
        with gr.TabItem('Thee Tab'):
            gen = gr.Button('Grab Real Sequence')
            with gr.Row():
                t1_1 = gr.inputs.Number(label="Timestamp")
                t1_2 = gr.components.Dropdown(choices = ['positive','neutral', 'negative'], label="Sentiment")
                t3 = gr.outputs.Textbox(label="output")
            with gr.Row():
                t2_1 = gr.inputs.Number(label="")
                t2_2 = gr.components.Dropdown(choices = ['positive','neutral', 'negative'])
            with gr.Row():
                t3_1 = gr.inputs.Number(label="")
                t3_2 = gr.components.Dropdown(choices = ['positive','neutral', 'negative'])
            with gr.Row():
                t4_1 = gr.inputs.Number(label="")
                t4_2 = gr.components.Dropdown(choices = ['positive','neutral', 'negative'])
            with gr.Row():
                b1 = gr.Button('run')
                b2 = gr.Button('save output')
        with gr.TabItem("fun tab"):
            gr.Markdown("this tab is for fun purposes only")

    def predict_sentiment(t1_1, t1_2, t2_1, t2_2, t3_1, t3_2, t4_1, t4_2):
        return np.random.choice(sentiment)
    b1.click(predict_sentiment, [t1_1, t1_2, t2_1, t2_2, t3_1, t3_2, t4_1, t4_2], t3)

    def fn():
        idx = np.random.choice(range(len(test_data)))
        sample = test_data[idx]
        return sample[0][0], sample[0][1], sample[1][0], sample[1][1], sample[2][0], sample[2][1], sample[3][0], sample[3][1]
    gen.click(fn,inputs=[] ,outputs = [t1_1, t1_2, t2_1, t2_2, t3_1, t3_2, t4_1, t4_2])
demo.launch()
```


https://user-images.githubusercontent.com/60792362/166969432-99d2877c-2b7b-4bd9-9826-c48d86a4f7b4.mp4

**Comment by abidlabs** [comment]
Awesome, thanks for sharing @brenden-connors. 

One thing I noticed in this example is that our components seem to have rounded corners at the top left and bottom right, but not on the other two corners. Is this intentional @pngwn @gary149? It prevents the components from stacking nicely

**Comment by pngwn** [comment]
@abidlabs looks broken, will take a look.

**Comment by falibabaei** [comment]
I am using GUI to create a UI for my deepaas api. The problem is that I can not change the theme of the GUI. My code is

    class Seafoam(Base):
        pass
 
    seafoam = Seafoam()    
    with gr.Blocks( theme=seafoam ) as demo:

        gr.Markdown(
        """
         # RNA Contact Map Generator
        """
     ) 
        

        def clear_output():
                output.value = ""  
        def filter_timestamp(head_task):
            
            return gr.Dropdown.update(
                choices=models_dict['backbone_frozen_timestamp'][head_task.strip().replace('"', '')], #FIXME this is just the model on the cloud not on system
                value=models_dict['backbone_frozen_timestamp'][head_task.strip().replace('"', '')][0]
            )

        def filter_xgb_timestamp(head_task):
            return gr.Dropdown.update(
                choices=models_dict['XGB_timestamp'][head_task.strip().replace('"', '')], #FIXME this is just the model on the cloud not on system
                value=models_dict['XGB_timestamp'][head_task.strip().replace('"', '')][0]
            )
        
        with gr.Row():
            with gr.Column():
                gr_inp, inp_names, inp_types=utils_gr.api2gr_inputs(api_inp)

       

                head_task=gr_inp[2]
                timestamp=gr_inp[3]    
                XGB_timestamp=gr_inp[5]          
# update XGB Timestamp dropdown when Head Task changes
                head_task.change(filter_timestamp, head_task,   timestamp)
                head_task.change(filter_xgb_timestamp, head_task,  XGB_timestamp)
      #  accept.change(hide_accept)

            with gr.Column():
                      
                 with gr.Tab(label = "get prediction of the RNA contact map"):
                    with gr.Row():
                      with gr.Column():
                          b1 = gr.Button("Submit")
                      with gr.Column():
                       b2=gr.Button("Clear Output")
                    with gr.Row():  
         
                         output=gr.outputs.JSON(label='output')
                 b1.click(api_call, inputs=gr_inp, outputs=output )
                 b2.click(clear_output,  outputs=output )

                 with gr.Tab(label = "Plot RNA contact map from prediction"):
                   with gr.Row(): 
                     with gr.Column():
                         b1 = gr.Button("Submit")
                     with gr.Column():
                          b2=gr.Button("Clear Output")
                   with gr.Row():  
                         output=gr.outputs.Image('pil',label='output')
                 b1.click(api_call_pdf_output, inputs=gr_inp, outputs=output )
                 b2.click(clear_output,  outputs=output )    
        
    demo.launch(share=True)

But nothing changed after I put theme in the block

**Comment by freddyaboulton** [comment]
What version of gradio are you using @falibabaei ?

**Comment by falibabaei** [comment]
gr.__version__
'3.18.0'

**Comment by falibabaei** [comment]
Thank you for your fast reply. I upgraded it to the version that you mentioned but I have the same issue. Everything is white and gray  gr.__version__
'3.23.0'

**Comment by freddyaboulton** [comment]
Your seafoam theme is inheriting from Base, which is quite bare. 

Can you try with a more distinct theme, like gr.themes.Monochrome, or load one of theme themes from the community: https://huggingface.co/spaces/gradio/theme-gallery
