### ISSUE TITLE
Opening Gradio inside jupyter notebook which his hosted in a docker container

### ISSUE THREAD

**Issue by bstottle** [gradio-app/gradio#6903]
### Describe the bug

Revisiting #248, but that bug seems to reference the old Interface functionality, not Blocks and %load_ext gradio.

I'm running the docker with -p 7860:7860.  Neither with or without --shared seems to affect the behavior.  I don't see a way to set the server ip/port (as a beginner, but looking at [ipython_ext.py](https://github.com/gradio-app/gradio/blob/main/gradio/ipython_ext.py)).  Any suggestions?

@abidlabs - It looks like you wrote most of the relevant code.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
%load_ext gradio

import gradio as gr

%%blocks --share

def chat_with_model(user_input):
    # model_response = local_llm(user_input)
    model_response = "Interesting"
    return model_response

with gr.Blocks() as demo:
    gr.Markdown("## Chat with AI Model")
    with gr.Row():
        input_text = gr.Textbox(label="Your message")
        submit_button = gr.Button("Send")
    output_text = gr.Textbox(label="AI Response", interactive=False)

    # When the button is clicked, call the chat_with_model function
    submit_button.click(chat_with_model, inputs=input_text, outputs=output_text)
```

### Screenshot

<img width="854" alt="Screenshot 2023-12-28 at 4 24 59 PM" src="https://github.com/gradio-app/gradio/assets/130258976/a487959a-9fbe-4446-ab94-863a8b2b0bae">

### Logs

```shell
launch is hidden, not sure how to set debug.
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.12.0
gradio_client version: 0.8.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.108.0
ffmpy: 0.3.1
gradio-client==0.8.0 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.1
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.4
pillow: 10.1.0
pydantic: 2.5.3
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.25.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.26.0
huggingface-hub: 0.20.1
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by bstottle** [comment]
An update on this.  In my docker I originally installed gradio as root, then created a venv as a user.  With gradio not able to download/install (fonts IIRC) into the root installation, neither shared nor non-shared UIs would run in the notebook.

If I install gradio as the non-root user, I can at least run using `%%blocks --share`, but `%%blocks` without --share still fails.  I can reproduce this with the default jupyter notebook

```
> docker run -p 10001:8888 -e JUPYTER_DOCKER_STACKS_QUIET= quay.io/jupyter/base-notebook`
```

```
!pip install gradio
!pip install --upgrade jupyter ipywidgets
```

```
%load_ext gradio
```

```
%%blocks

def chat_with_model(user_input):
    # model_response = local_llm(user_input)
    model_response = "Interesting"
    return model_response

with gr.Blocks() as demo:
    gr.Markdown("## Chat with AI Model")
    with gr.Row():
        input_text = gr.Textbox(label="Your message")
        submit_button = gr.Button("Send")
    output_text = gr.Textbox(label="AI Response", interactive=False)

    # When the button is clicked, call the chat_with_model function
    submit_button.click(chat_with_model, inputs=input_text, outputs=output_text)
```

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but can reopen if the issue continues to persist in the latest version of Gradio
