### ISSUE TITLE
Gradio-client example script error

### ISSUE THREAD

**Issue by younesbelkada** [gradio-app/gradio#6906]
### Describe the bug

Hi there!
I want to use this app: https://huggingface.co/spaces/ybelkada/blip-dlai-api as an API, according to the code snippet shared on the bottom of the Space, I tried:

```python
from gradio_client import Client

client = Client("https://ybelkada-blip-dlai-api.hf.space/--replicas/izcv3/")
result = client.predict(
    "https://storage.googleapis.com/sfr-vision-language-research/BLIP/demo.jpg",
    api_name="/predict",
)
print(result)
```

And I get the following traceback: 

```bash
File "/home/younes_huggingface_co/miniconda3/envs/fix-test/lib/python3.9/site-packages/gradio_client/client.py", line 965, in _inner
    predictions = _predict(*data)
  File "/home/younes_huggingface_co/miniconda3/envs/fix-test/lib/python3.9/site-packages/gradio_client/client.py", line 1005, in _predict
    raise ValueError(result["error"])
ValueError: None
```

The app is pretty much straightforward and holds in few lines:

```python
import gradio as gr
from transformers import pipeline

pipe = pipeline("image-to-text", model="Salesforce/blip-image-captioning-base")

def launch(input):
    out = pipe(input)
    return out[0]['generated_text']

iface = gr.Interface(launch, inputs="text", outputs="text")
iface.launch()
```

I am using the latest `gradio` and `gradio_client` from Pypi 

cc @aliabd 

Similar issue: https://github.com/gradio-app/gradio/issues/3986 but did not find anything relevant, I tried to replace `predict` by `submit`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

On the app side

```python
import gradio as gr
from transformers import pipeline

pipe = pipeline("image-to-text", model="Salesforce/blip-image-captioning-base")

def launch(input):
    out = pipe(input)
    return out[0]['generated_text']

iface = gr.Interface(launch, inputs="text", outputs="text")
iface.launch()
```

Then on another script:

```python
from gradio_client import Client

client = Client("https://ybelkada-blip-dlai-api.hf.space/--replicas/izcv3/")
result = client.predict(
    "https://storage.googleapis.com/sfr-vision-language-research/BLIP/demo.jpg",
    api_name="/predict",
)
print(result)
```

### System Info

```shell
Google colab
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @younesbelkada !

I just restarted the space and tried with the latest versions of `gradio` and `gradio_client` and it's working.

<img width="716" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/0ad1cf0b-b649-49bd-90d1-3e9311402b81">


I will close for now. Let us know if we can help in any way.
