### ISSUE TITLE
Ability to use multiple input sources

### ISSUE THREAD

**Issue by yadavj2008** [gradio-app/gradio#6908]
- [ ] I have searched to see if a similar issue already exists.
Yes

**Is your feature request related to a problem? Please describe.**  
I have use case where I want to use audio to record the user instruction, at the same time I also want to capture the image or video from the user web browser camera. Looks like there is no way currently to use both in parallel. 

**Describe the solution you'd like**  
User ability to use audio recording via microphone and image/video capture via camera at the same time. 
Let me know if there is any workaround for this?.

**Additional context**  
n/a

**Comment by abidlabs** [comment]
Hi @yadavj2008 in `gr.Video()`, you can set `include_audio=True`, which records the audio as well as the video.
