### ISSUE TITLE
Allow for more UI control on `gr.Interface()` by allowing `gr.Accordion()` to work with it

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#6926]
**Is your feature request related to a problem? Please describe.**  
While `gr.Blocks()` is great and versatile, it also increases the complexity of the app. `gr.Interface()` is simple and allow for streamlined creations, however it has little versatility/compositionally for the layout. While I understand the trade-off between them is exactly that, I think may still be potential for `gr.Interface()` to keep its simplicity while giving a slight bit of control to the user on the design. 

**Describe the solution you'd like**  
To me, the quickest win for the spirit of this issue would be to allow `gr.Accordion()` to work with `gr.Interface()`. I believe allowing people to have a `gr.Interface()` with an `Advanced Settings` accordion that could be collapsed could increase dramatically the scope of `gr.Interface()` as people can expose a very simple UI and leave some parameters available only in the accordion without trading off the simplicity of the interface with user control (and without having to migrate to `gr.Blocks()` just to add an accordion on a very simple UI) 

I've faced it myself here: https://huggingface.co/spaces/multimodalart/Ip-Adapter-FaceID

**Comment by abidlabs** [comment]
Thanks @apolinario, what if we were to support something like this:

```py
gr.Interface(
  fn=...,
  inputs=[
    "textbox",
    gr.Accordion(components=[
      "image",
      "audio"
    ])
  ],
  outputs=...
)

```

**Comment by apolinario** [comment]
Cool API design IMO!
