### ISSUE TITLE
Either have `gr.Files()` to display images in a grid, or have `gr.Gallery()` to allow uploads

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#6927]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I would like to visually see my multiple images when I upload them, currently it looks like this: 
<img width="1249" alt="image" src="https://github.com/gradio-app/gradio/assets/788417/59ca462b-8412-4484-9769-92cd996467b5">
It would be cooler for the app if I could see the before/after visually

**Describe the solution you'd like**  
Either have an option for when `gr.Files()` is of type `file_types="image"`, display them in a gallery. Or to allow `gr.Gallery()` to work as an input component and show the multi-uploaded images as a gallery.

**Comment by pngwn** [comment]
I think it makes more sense to use Gallery, otherwise we'll need to support all kinds of media in the `File` which was never the intention.

Going to close this issues and reopen this: https://github.com/gradio-app/gradio/issues/1379
