### ISSUE TITLE
`gr.update(value=[])` for `gr.File()` does not clear it

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#6929]
### Describe the bug

If you return a `gr.update(value=[])` or `gr.File(value=[])` it does not clear and get back to the state where you can upload a file, but rather gets on a state where the component is empty and you still need to click the close button to clear

![image](https://github.com/gradio-app/gradio/assets/788417/9b3e9d80-b104-4d6d-a656-ac506406c52a)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def clear_files():
    return gr.update(value=[], interactive=True)

with gr.Blocks() as demo:
    files = gr.Files()
    clear = gr.Button()
    clear.click(fn=clear_files, outputs=files)
```
(this is jus a minimal repro, my use-case is more complex, hence I can't use `gr.ClearButton()` 

### System Info

```shell
gradio==4.12.0
```

### Severity

I can work around it

**Comment by pngwn** [comment]
You should be able to clear it if you set that value to `None`.
