### ISSUE TITLE
The JS client should use the API names by default instead of fn_index to make the API mapping more stable

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#6934]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

A common problem I have is that I have many users using the gradio app, but when I update the app, all their instances are ruined because of API changes.  E.g. the fn_index maps to the wrong named index, so the UI ends up accessing the wrong thing.  This can fail, or even worse not fail and be just wrong.

**Describe the solution you'd like**  

I'd like the API to be more stable, and based upon the name and not some random number due to ordering of gradio elements initialized.  That way, if server adds some random button, it won't ruin everything upon restart for active users in their browser or for clients already loaded working via API.

**Additional context**  

I thought about ways to at least notify the user to refresh the browser, but I think a more stable API mapping is much better and actually solves the problem of minor changes breaking everything without need for refresh.

**Comment by abidlabs** [comment]
Hi @pseudotensor can you provide a code snippet to illustrate what you mean? You can already specify an `api_name` for any event listener

**Comment by pseudotensor** [comment]
I don't think a code snippet helps.  I'll use pseudocode instead if it's not clear.

Server Up First time:
Code has:
Click1
Click2
Click3

Then if UI or API is connected, gradio maps names to fn_index and it'll be like a fixed API mapping of Click1->0, Click2->1, Click3->2.  However, suppose I add a  new button in middle:

Server Up Later after Restart:
Code has:
Click1
Click4
Click2
Click3

Then fn_index will not map to same events.

This causes problems for UI (even though Click123 would have been fine if accessed by name) and API.  The UI literally tries to access Click4 for fn_index=1, which leads to all sorts of confusing error messages, or worse no errors but wrong results.  The API has same issue.

**Comment by abidlabs** [comment]
Ah you mean users who are using the app and in the middle of their session, the code for the Gradio app is updated? I don’t think there is any robust way to preserve endpoints across sessions but we can potentially force a refresh if the the underlying app has changed

**Comment by pseudotensor** [comment]
A forced-refresh would lose session hash persistence, which is also undesired.  What I was proposing is to stop using a numbered index and just always use the given name (or auto-generated name).  That way things persist across server restarts.

**Comment by abidlabs** [comment]
Makes sense, let me rename this issue to make it a little clearer. We are planning on revisiting the js client in the next month or two.

**Comment by pseudotensor** [comment]
Why just the JS client?

**Comment by abidlabs** [comment]
@hannahblair going to move this over to the js client milestone. I think its a good issue -- not sure if we need to do it in 1.0 or whether its doable without a breaking change

**Comment by abidlabs** [comment]
let's go ahead and close this as it basically only matters if someone is building a Gradio app and pushing out updates to a live website and users are using it on the live website and users haven't refreshed their page
