### ISSUE TITLE
Is there a direct or indirect way to get the shared screen interface

### ISSUE THREAD

**Issue by XiaohuJoshua** [gradio-app/gradio#6935]
- [y] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I wonder if there is a direct or indirect way to get the shared screen interface.

**Comment by abidlabs** [comment]
Hi @XiaohuJoshua this issue is not clear, and by the way, for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
