### ISSUE TITLE
Cannot load example for files.

### ISSUE THREAD

**Issue by lukewys** [gradio-app/gradio#694]
**Describe the bug**
In current version, gradio.inputs.File accepts input as:

`File accepts the List of JSON objects with filename as 'name' property and base64 data as 'data' property as type List[Dict[name: str, data: str]]`

However, for example files, it somehow does not work, probably because the example files only provide an str filepath.

**To Reproduce**
In colab demos (https://colab.research.google.com/drive/18abcC7R4NtzA-CcsI1QoJ4ZTuvBvccdY) under https://gradio.app/docs/#i_file, the file input UI will crash after clicked on example files:

before:

![image](https://user-images.githubusercontent.com/28220671/155012004-1d72c770-0500-4cfa-9f98-3f93bd349caa.png)

After:

![image](https://user-images.githubusercontent.com/28220671/155012043-f3ef9879-53d7-479d-8a62-84e0d07c5386.png)

A similar problem can be found here: https://huggingface.co/spaces/lukewys/midi-ddsp, as you click on example mid file, the upload frame ("drop file here or upload") crashes.

**Comment by abidlabs** [comment]
Thanks for reporting this issue @lukewys. Can confirm that I can reproduce this with the code below. We'll fix it soon!

```python
from zipfile import ZipFile

import gradio as gr


def zip_two_files(file1, file2):
    with ZipFile("tmp.zip", "w") as zipObj:
        zipObj.write(file1.name, "file1")
        zipObj.write(file2.name, "file2")
    return "tmp.zip"


iface = gr.Interface(
    zip_two_files,
    ["file", "file"],
    "file",
    examples=[
        ["files/titanic.csv", "files/titanic.csv"],
    ],
)

iface.launch()

```

**Comment by abidlabs** [comment]
Should be fixed now by #714!

**Comment by lukewys** [comment]
Oh, I see, I need to wait until 2.9.0 comes out. Huge thanks for fixing the bug

**Comment by abidlabs** [comment]
Feel free to [install Gradio from `master`](https://github.com/gradio-app/gradio/blob/master/CONTRIBUTING.md) if you need it immediately, but we should be releasing a version out on pypi within the next day or so.

**Comment by lukewys** [comment]
Huge thanks!
