### ISSUE TITLE
(Reload mode) RuntimeError: Caught handled exception, but response already started

### ISSUE THREAD

**Issue by kavincsekaran** [gradio-app/gradio#6950]
### Describe the bug

Getting a runtime error after upgrading to Gradio 4.0 when app is launched in reload mode and encounter any error.

What is happening:
1. Launch app in reload mode.
2. Open app in browser
3. Have any error in the code.
4. Fix error in code.
5. App reloads in browser
6. Have any interactive component like a button and interact with the app by clicking the button.
7. Get the runtime error.

Cannot use the app until the app is relaunched.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Working code with an interactive component. Save as app.py:
```python
import gradio as gr

def sum_nums(n1, n2, n3):
    return n1+n2+n3

with gr.Blocks() as demo:
    with gr.Row():
        gr.HTML("""<h1 style = "text-align:center">Reproducing Bug</h1>""")

    with gr.Row():
        num1 = gr.Number(label="Number 1", value = 0.0)
        num2 = gr.Number(label="Number 2", value = 0.0)
        num3 = gr.Number(label="Number 3", value = 0.0)

    with gr.Row():
        sum = gr.Textbox(label = "Sum", value = 0.0)
        calc_bttn = gr.Button(value="Calculate sum")
        calc_bttn.click(sum_nums, [num1, num2, num3], sum)
        


if __name__ == "__main__":
    demo.launch()
```
1) Launch app in reload mode: ```gradio app.py```
2) Open app in browser
3) Comment out a line of code to trigger an error: ```#sum = gr.Textbox(label = "Sum", value = 0.0)```
4) Uncomment the line of code to have a working code: ```sum = gr.Textbox(label = "Sum", value = 0.0)```
5) Enter input for "Number 1", "Number 2", "Number 3" and press the "Calculate sum" button.
6) Error in browser and console

![Screenshot 2024-01-03 231343](https://github.com/gradio-app/gradio/assets/2325146/632938aa-79c4-449a-bb4d-72a45f6a3c22)
![Screenshot 2024-01-04 000659](https://github.com/gradio-app/gradio/assets/2325146/6ea6372c-96ed-4924-8087-15ae529defb2)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.11.0
gradio_client version: 0.7.3

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.1
fastapi: 0.103.2
ffmpy: 0.3.1
gradio-client==0.7.3 is not installed.
httpx: 0.25.0
huggingface-hub: 0.19.4
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.26.0
orjson: 3.9.7
packaging: 23.1
pandas: 2.1.1
pillow: 10.0.1
pydantic: 2.4.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.23.2
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.9.2
httpx: 0.25.0
huggingface-hub: 0.19.4
packaging: 23.1
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by aghand0ur** [comment]
I tried the simple example presented in the docs here:
https://www.gradio.app/guides/developing-faster-with-reload-mode

and I got the following error:
`gradio run.py my_demo.`

![image](https://github.com/gradio-app/gradio/assets/14883982/eefc7636-15f2-457a-b5b2-265a5a9e230f)

Is the documentation up-to-date?

**Comment by abidlabs** [comment]
@aghand0ur please remove the trailing "." --> just `gradio run.py my_demo`
