### ISSUE TITLE
Multiple Files input not working

### ISSUE THREAD

**Issue by arturcuringa** [gradio-app/gradio#697]
Using `gr.inputs.File(file_count="multiple", label=None)` for multiple files input results in the interface allowing only one file and not processing it correctly.

**To Reproduce**
1. Set gr.inputs.File(file_count="multiple", label=None)
2. Start the gradio server 
3. Drag and drop multiple files on the file box/Manually Select a file
4. See that the files are not attached

**Device information:**
 - OS: Ubuntu 20.04
 - Browser Firefox, Chrome
 - gradio==2.8.1

**Additional context**
This issue does not occurs in version 2.7.5

**Comment by abidlabs** [comment]
Thanks @arturcuringa. Can confirm I can reproduce the problem. We'll fix it soon!

**Comment by abidlabs** [comment]
Should be fixed now by #714!
