### ISSUE TITLE
FileData() argument after ** must be a mapping, not list

### ISSUE THREAD

**Issue by duerrsimon** [gradio-app/gradio#6972]
### Describe the bug

For the Molecule3D component I'm developing I get the error `FileData() argument after ** must be a mapping, not list` if I set a value to the component (e.g "demo/1pga.pdb") in the app.py file. 

This error appears if I use gr.Interface but not blocks.

Already pinged @pngwn about this but @abidlabs asked me to create an issue here.

Might be related to #6873  

Curiously, if I don't set a default value and load a PDB file using the fetch button (e.g using "1pga" in the input) I get a different error. `RuntimeError: Caught handled exception, but response already started.`

Would love to get this component up and running and in the hands of users. 

For the upload via the textbox I simply emulate a file upload. Maybe that's where the error is at least for the second issue.
 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Everything is here: https://huggingface.co/spaces/simonduerr/gradio_molecule3d

These are the two different examples with blocks and interface
```
#doesn't work
demoInterface = gr.Interface(
    predict,
    Molecule3D(label="Molecule3D", reps=reps),  # interactive version of your component
    Molecule3D(),  # static version of your component
)
demoInterface.launch()

#works
with gr.Blocks() as demo:
    with gr.Row():
        inp = Molecule3D("1pga.pdb",label="Molecule3D", reps=reps)
        out = Molecule3D(label="Molecule3D", reps=reps)
    btn = gr.Button("Predict")
    btn.click(predict, inputs=inp, outputs=out)
demo.launch()

```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.13.0
gradio_client version: 0.8.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.1
fastapi: 0.103.1
ffmpy: 0.3.1
gradio-client==0.8.0 is not installed.
httpx: 0.25.0
huggingface-hub: 0.20.2
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.26.0
orjson: 3.9.7
packaging: 23.1
pandas: 2.1.1
pillow: 10.0.1
pydantic: 2.4.1
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.23.2
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.9.2
httpx: 0.25.0
huggingface-hub: 0.20.2
packaging: 23.1
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @duerrsimon !

> I get the error FileData() argument after ** must be a mapping, not list if I set a value to the component (e.g "demo/1pga.pdb") in the app.py file.

I can't repro that. The code I'm running is below. I just cloned your space, installed, built, and ran the demo in app.py. Let me know what I'm misunderstanding!

```python

import gradio as gr
from gradio_molecule3d import Molecule3D

import os

example = Molecule3D().example_inputs()


reps =    [
    {
      "model": 0,
      "chain": "",
      "resname": "",
      "style": "cartoon",
      "color": "whiteCarbon",
      "residue_range": "",
      "around": 0,
      "byres": False,
      "visible": False,
    },
  ]

def predict(x):
    print("predict function", x)
    return x

#doesn't work
demoInterface = gr.Interface(
    predict,
    Molecule3D("1pga.pdb", label="Molecule3D", reps=reps),  # interactive version of your component
    Molecule3D(),  # static version of your component
    #examples=[[example]],  # uncomment this line to view the "example version" of your component
)

#works
with gr.Blocks() as demo:
    with gr.Row():
        inp = Molecule3D("1pga.pdb",label="Molecule3D", reps=reps)
        out = Molecule3D(label="Molecule3D", reps=reps)
    btn = gr.Button("Predict")
    btn.click(predict, inputs=inp, outputs=out)

#demo.launch()

demoInterface.launch()
```

<img width="1264" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/367dd5f3-348b-4a6f-977f-0c28a742af00">

**Comment by duerrsimon** [comment]
The error happens if you click submit. 

With gr.Blocks the uploaded file then also shows up in the output component. 
With gr.Interface I get the error mentioned above.

**Comment by freddyaboulton** [comment]
Hi @duerrsimon ! We just released gradio 4.20.1 and I can not reproduce the `gr.Interface` issue even after hitting the submit button.

Can you please see if the problem is fixed for you?

![Image](https://github.com/gradio-app/gradio/assets/41651716/3ca53a81-b8fd-412a-9237-58add147842b)

**Comment by duerrsimon** [comment]
It still doesn't work for me unfortunately if one deletes the default file and uses the FileRetrieval.svelte component that emulates the upload function. The issue must be related to this but but since gradio js client doesn't really have documentation I didn't really find out what exactly I have to do to fix it. 

FileRetrieval basically fetches the file locally and then emulates the upload by constructing the file_data object and sending the file as blob to the backend via @client https://huggingface.co/spaces/simonduerr/gradio_molecule3d/blob/947fcf90ef1352e65d10a097c2c741aa0d0513a6/src/frontend/shared/FileRetrieval.svelte#L88 

Do you have a working example how to upload custom files via the client? I should be able to figure things out then.

**Comment by freddyaboulton** [comment]
Hi @duerrsimon ! I modified your component's space and opened a PR here: https://huggingface.co/spaces/simonduerr/gradio_molecule3d/discussions/1#65f4a375de5e636ca2e575ec

You were close, it's just that you needed to convert the fetched blob to a `File` (so that the uploaded file preserves the name) and instantiate a `FileData` from the new `File`.

Yes we're reworking the client and it's documentation and we should make sure to document how uploads happen more clearly.
