### ISSUE TITLE
Add scrollbar to Textbox component?

### ISSUE THREAD

**Issue by jjshoots** [gradio-app/gradio#6977]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
For long chunks of text inside the `Textbox` component, scrolling from one end to the other can take a lot of time.

**Describe the solution you'd like**  
Would be great if the textbox can have a scrollbar added.

**Comment by dawoodkhan82** [comment]
@jjshoots The textbox should already have scrolling enabled when the text exceeds the height of the textbox. Do you mean an actually visible bar that can be clicked and dragged? That is dependent on your browser, and should be visible if you hover over the scroll bar area. Let me know if I'm misunderstanding your issue.

**Comment by jjshoots** [comment]
Thought I commented on this, turned out Github just stashed my response.

Yep, I mean just a visible bar on the textbox that can be clicked and dragged. It's not visible on Brave 1.61.116 and various versions of Safari and Chrome too. Strangely enough, when using [this example] when running on localhost doesn't seem to worok either.

**Comment by yiya1989** [comment]
> @jjshoots The textbox should already have scrolling enabled when the text exceeds the height of the textbox. Do you mean an actually visible bar that can be clicked and dragged? That is dependent on your browser, and should be visible if you hover over the scroll bar area. Let me know if I'm misunderstanding your issue.

I have the same question. I want to show a  vertical scrollbar on the right. Like bellow, as this issue says. 
[Add a scrollbar to notebook/default textboxes, improve chat scrollbar style](https://github.com/oobabooga/text-generation-webui/pull/3403)


![image](https://github.com/gradio-app/gradio/assets/3204394/6d119d9c-3786-45e2-8fc6-dd5b35f48270)

**Comment by umarbutler** [comment]
+1
