### ISSUE TITLE
Dead links to documentation in the website  guides

### ISSUE THREAD

**Issue by tomjorquera** [gradio-app/gradio#6984]
### Describe the bug

In the guides, there are multiple dead links to the documentation. 

For example, at the end of https://www.gradio.app/guides/state-in-blocks, there is the following content :

```
Learn more about State in the [docs](https://gradio.app/docs#state).
```

But this link does not exist, so the browser is redirected to https://www.gradio.app/docs/interface.

The correct link is actually https://gradio.app/docs/state

Also, some guides refer to https://gradio.app/guides/quickstart/#blocks-more-flexibility-and-control, where I think the correct link should be https://gradio.app/blocks-and-event-listeners (or possibly https://gradio.app/guides/blocks-and-event-listeners).

I saw in the git logs that the website was converted to sveltekit in August, maybe the routes changed at this time?

Maybe the simplest fix would be to update the links. I can provide a PR with the changes.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

1. Go to https://www.gradio.app/guides/state-in-blocks
2. Click on the link mentionned in "Learn more about State in the [docs](https://gradio.app/docs#state)"

:smile: 

### System Info

```shell
Not applicable, issue concerns the website
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @tomjorquera for catching these. A PR would be much appreciated!

**Comment by tomjorquera** [comment]
@abidlabs here you go :wink:
