### ISSUE TITLE
Gradio does not print share URL when running with `nohup`

### ISSUE THREAD

**Issue by danielvarga** [gradio-app/gradio#6986]
### Describe the bug

I'm running a standard gradio app with iface.launch(share=True). I'm running app.py with nohup. Unlike the regular command-line run, the nohup run does not emit the line `Running on public URL: https://****.gradio.live`. This line only appears in the log after I have terminated the process. How to access this information while it's still valuable?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr

def greet(name, intensity):
    return "Hello " * intensity + name + "!"

demo = gr.Interface(
    fn=greet,
    inputs=["text", "slider"],
    outputs=["text"],
)

demo.launch(share=True)
```

```nohup python app.py &```

### System Info

```shell
gradio @ file:///home/conda/feedstock_root/build_artifacts/gradio_1679384519199/work
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @danielvarga can you try adding `prevent_thread_lock=True` in `launch()` to see if that fixes the issue?

**Comment by danielvarga** [comment]
@abidlabs it didn't help, it made the app terminate after a short time, both with and without using nohup.

**Comment by Jeremy-ttt** [comment]
I fixed it using`nohup python -u app.py &`
reference:[https://stackoverflow.com/questions/25674613/python-nohup-out-dont-show-print-statement](url)

**Comment by abidlabs** [comment]
Ah great thanks @Jeremy-ttt!
