### ISSUE TITLE
Dataframe in a webview breaks on Mac in another tab

### ISSUE THREAD

**Issue by Josef-Haupt** [gradio-app/gradio#6990]
### Describe the bug

Hi! I am creating a GUI for an application which will be deployed cross plattform. To make it look like an app I'm using [`pywebview`](https://pywebview.flowrl.com/), which has been working fine one my machine (win10).
Currently I'm trying to make it work on Mac also.
The only problem is that the dataframe only works in the first tab (see example).
No matter what contents I try to serve, nothing will be displayed in the DF in the second tab.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import webview

with gr.Blocks(analytics_enabled=False) as demo:
    with gr.Tab("First"):
        gr.Matrix(headers=["h1", "h2"])
    with gr.Tab("Second"):
        gr.Matrix(headers=["h1", "h2"])

url = demo.queue(api_open=False).launch(prevent_thread_lock=True)[1]

webview.create_window("foo", url)
webview.start(private_mode=False)
```

### Screenshot

<img width="912" alt="Screenshot 2024-01-10 at 15 37 03" src="https://github.com/gradio-app/gradio/assets/35149496/5e2c6615-6675-45a0-ae92-648308620bb0">
<img width="912" alt="Screenshot 2024-01-10 at 15 38 57" src="https://github.com/gradio-app/gradio/assets/35149496/41a05f4e-d531-412f-8be7-c7532baa413c">

### System Info

```shell
gradio: 4.13.0
gradio_client: 0.8.0
pywebview: 4.4.1
OS: Sonoma 14.2.1
```

### Severity

Blocking usage of gradio

**Comment by Josef-Haupt** [comment]
Pretty sure they are going to say the same thing.
Pywebview only uses the platforms native GUI, which is cocoa on macOS, to create the webview basically a Safari lite.

**Comment by abidlabs** [comment]
Got it. I think this is outside the scope of Gradio right now, but we do have an open request to be able to build desktop apps with Gradio: https://github.com/gradio-app/gradio/issues/2257

Its a bit far down in the roadmap, but feel free to follow that issue for an officially-supported solution to build desktop apps
