### ISSUE TITLE
Interface not visible on Windows 10 (Chrome Browser)

### ISSUE THREAD

**Issue by saratrajput** [gradio-app/gradio#700]
**Describe the bug**
While testing a simple gradio app on Windows 10 with Chrome browser, the interface launches without error, but it is not visible either in the Jupyter Notebook or in the local URL.

**To Reproduce**
1. Open a Jupyter Lab session and run the following code:

```
import gradio as gr

def hello_world(name):
    return "Hello..." + name + "!!"

interface = gr.Interface(fn=hello_world, inputs='text', outputs="text")
interface.launch()
```

**Screenshots**

![image](https://user-images.githubusercontent.com/29677848/155040714-849100eb-9f5e-4f2e-8640-6541c1f3dd66.png)

**Device information (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Gradio version: 2.8.2
 - Python: 3.7

**Additional context**

**Comment by abidlabs** [comment]
Can you try installing `gradio==2.8.1` and see if you have the same issue?

`pip install gradio==2.8.1`

**Comment by saratrajput** [comment]
Yes, ```gradio==2.8.1``` has the same issue as well.
I tested with Firefox browser and it also has the same issue.

**Comment by abidlabs** [comment]
Can you [open up the console log](https://balsamiq.com/support/faqs/browserconsole/#:~:text=Google%20Chrome,-To%20open%20the&text=You%20can%20also%20use%20Option,or%20in%20a%20new%20window.) in the inspector and tell us what errors you see?

**Comment by saratrajput** [comment]
![image](https://user-images.githubusercontent.com/29677848/155042877-0eecb9a4-91ee-46fd-93e7-ad7e65356981.png)
![image](https://user-images.githubusercontent.com/29677848/155042961-e0930a4d-a71b-415c-8763-e64711bf2342.png)

```
1902.cebcb09d0dbbb83…cb09d0dbbb83ac5d2:2 $ref: keywords ignored in schema at path "#/properties/codeCellConfig"
1902.cebcb09d0dbbb83…cb09d0dbbb83ac5d2:2 $ref: keywords ignored in schema at path "#/properties/markdownCellConfig"
1902.cebcb09d0dbbb83…cb09d0dbbb83ac5d2:2 $ref: keywords ignored in schema at path "#/properties/rawCellConfig"
1902.cebcb09d0dbbb83…cb09d0dbbb83ac5d2:2 $ref: keywords ignored in schema at path "#/properties/codeCellConfig"
1902.cebcb09d0dbbb83…cb09d0dbbb83ac5d2:2 $ref: keywords ignored in schema at path "#/properties/markdownCellConfig"
1902.cebcb09d0dbbb83…cb09d0dbbb83ac5d2:2 $ref: keywords ignored in schema at path "#/properties/rawCellConfig"
jlab_core.0adf13f767…f13f7678b3af0da97:2 TypeError: Cannot read properties of undefined (reading 'widgets')
    at Object.p [as generate] (static/lab/jlab_core…b3af0da97:2:1108305)
    at ae.onUpdateRequest (static/lab/jlab_core…b3af0da97:2:1112280)
    at ae.e.processMessage (static/lab/jlab_core…b3af0da97:2:1439394)
    at b (static/lab/jlab_core…b3af0da97:2:1406135)
    at t (static/lab/jlab_core…b3af0da97:2:1404706)
    at y (static/lab/jlab_core…b3af0da97:2:1406390)
index.6e77b405.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
vendor.3e20f013.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/main.ce65c51….js.map?v=ce65c51…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/4151.fd7ca59….js.map?v=fd7ca59…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/911.0c08f04….js.map?v=0c08f04…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/6700.9bfbe77….js.map?v=9bfbe77…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/126.1e2fb99….js.map?v=1e2fb99…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/1902.cebcb09….js.map?v=cebcb09…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/4155.784ca17….js.map?v=784ca17…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/1033.890eeae….js.map?v=890eeae…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/4570.53adcb6….js.map?v=53adcb6…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/2719.e5ff90b….js.map?v=e5ff90b…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/7294.f71c288….js.map?v=f71c288…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/1036.b407e23….js.map?v=b407e23…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/714.d38baae….js.map?v=d38baae…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/7084.cb32d66….js.map?v=cb32d66…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/7755.d506a1d….js.map?v=d506a1d…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/9473.ac8fe4a….js.map?v=ac8fe4a…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/9761.6a67038….js.map?v=6a67038…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/1057.a060854….js.map?v=a060854…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/3935.4159b02….js.map?v=4159b02…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/3029.8636761….js.map?v=8636761…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/7024.d34685e….js.map?v=d34685e…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/4429.c4f083e….js.map?v=c4f083e…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/1249.39ca2df….js.map?v=39ca2df…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/1358.9ab4f57….js.map?v=9ab4f57…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/3496.ecb0e7f….js.map?v=ecb0e7f…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/7796.d14a6b9….js.map?v=d14a6b9…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/3502.c915d99….js.map?v=c915d99…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/6080.39703b8….js.map?v=39703b8…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/4631.96a143e….js.map?v=96a143e…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/807.6a2e483….js.map?v=6a2e483…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/jlab_core.0adf13f….js.map?v=0adf13f…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
﻿```

**Comment by saratrajput** [comment]
Tried the first few [solutions](https://stackoverflow.com/questions/61339968/error-message-devtools-failed-to-load-sourcemap-could-not-load-content-for-chr) for the above error ```DevTools failed to load source map: Could not load content for```, but it doesn't help.

**Comment by CatChenal** [comment]
@saratrajput It could be a jupyter lab issue. Have you tried on [colab](https://colab.research.google.com/drive/18ODkJvyxHutTN0P5APWyGFO_xwNcgHDZ?usp=sharing)?

**Comment by abidlabs** [comment]
Hi @saratrajput were you able to figure this out? Unfortunately, despite our best efforts, we can't replicate this issue. Please let us know if you see the same issue on colab and if possible share the colab with us. Otherwise, we will need to close the issue since we can't reproduce it

**Comment by AstraliteHeart** [comment]
I've experienced the same issue and this comment seems to describe what is going on well https://bugs.python.org/issue43975, I can also confirm the registry fix works (but you may need to clear the cache).

**Comment by Kp2442** [comment]
Setting share = True fixed the problem for me.

**Comment by nikky4D** [comment]
Is there a fix for this as I am also getting this error with the first example on gradio's page. 

With share=True, the error goes away. However, I would like to use a local address and not need a public one. 

I cannot do the HKEY modification of the registry, but I was able to find a workaround for my jupyter notebook here: [https://stackoverflow.com/questions/60136106/tensorboard-is-showing-a-blank-page-refused-to-execute-script-from-http-loca?noredirect=1&lq=1]
It is temporary and only for my environment so will have to be done for every new environment I think.

**Comment by KarimElsayad247** [comment]
The described in the forum post linked by @AstraliteHeart did work. I'll put it here in clear steps.

[Disclaimer]  Modifying the registry improperly can result in Windows becoming corrupted. You should only attempt these directions if you have your data backed up and are willing to risk creating additional problems. You should also back up the Windows registry. 

If you're not comfortable with modifying registry keys, you can also create a system restore point. Overall, be careful and don't modify the wrong keys.

Steps:

1. Open the "registry editor" program. Search for "Registry Editor" using windows search, or use the shortcut "Windows key + r" and type "regedit" in the box that open.
2. Navigate to the location `Computer\HKEY_CLASSES_ROOT\.js`
3. You should see some registry keys. I had [.default, Content Type, Perceived Type]. under `Data` column, value for Content Type was `text/plain`
4. Double click "Content Type" and change contents of "Value Data" to "application/javascript", and press ok
![image](https://user-images.githubusercontent.com/43252094/174300999-a831bb64-d56b-4578-9dad-193a18dae040.png)

6. If your Gradio app is still running, make sure to shut it down, the reopen it.
7. launch the gradio app. It should now be working.

**Comment by datalifenyc** [comment]
> Setting share = True fixed the problem for me.

It's interesting that `share = True` resolves the local URL.

**Comment by neilmahaseth** [comment]
Incorrect Mime Type for javascript file being sent by gradio server on Windows 10. Adding share = True fixes it.

**Comment by neilmahaseth** [comment]
To reproduce it you can try installing it on Windows 10 Build Number 19044.1889 using miniconda environment installed using pip using  gradio-3.1.7-py3-none-any.whl   - python=3.8.5 - pip=20.3

Or you can simply try installing this fork of stable diffusion https://github.com/basujindal/stable-diffusion on Windows 10 

Let me know if you need more information.

**Comment by TropComplique** [comment]
I have the same problem: gradio interface is not visible in a jupyter notebook.
I run jupyterlab on a remote debian server and then use jupyterlab through safari browser.

I use `jupyterlab==3.6.1` and `gradio==3.19.1`.

Adding share=True to `launch` fixes the problem. But I don't want to make my demos public.

**Comment by abidlabs** [comment]
Hi @TropComplique the basic reason this is happening is that when you run jupyter on a remote server, Gradio starts running on port 7860 (by default) on that remote server. *However*, you can't view it in your browser because that port has not been forwarded to your local machine. There are two solutions that I can think of:

* Use SSH forwarding to forward the port that Gradio is running to a port on to your local machine (again by default, Gradio starts running on 7860, then 7861, etc.) and then open that local port in your browser, and Gradio should show up
* Continue using `share=True`, but add some authentication to prevent unauthorized users of your demo, see https://gradio.app/sharing-your-app/#authentication

**Comment by TropComplique** [comment]
Hi @abidlabs. Thank you for help. It works!

Using SSH with flag `-L 7860:localhost:7860` fixes the problem.

**Comment by abidlabs** [comment]
Awesome, thanks for sharing the command.

**Comment by jan-gerritsen** [comment]
Changing 0.0.0.0 to localhost in generate.py worked for me

**Comment by ericfrachonlabrie-ai** [comment]
Depends of your local and group policies, it can be your firewall stopping as he see it as a threat. You can disable (temporary) by modifying the GPO (must have admin access) then you disable your windows firewall BEHAVIOR MONITORING. When using the local url many times with many attempt, Windows Defender just block your access and even if your Admin.
IF you already have admin, then just go to : Setting /Firewall & Network/    <--- then uncheck local protection. I put you at risk tho, that's why suggesting by GPO and specify your local url and the port used.
