### ISSUE TITLE
secure Gradio via FastAPI with external authentication

### ISSUE THREAD

**Issue by jayadnure** [gradio-app/gradio#7005]
### Describe the bug

We are trying to secure Gradeo application via FastAPI by having secure authentication in place. The routes defined by FastAPI are secured but when trying to access the mounted Gradeo application via a route it does not take authentication into consideration.
How can we impose strict authentication on accessing the Gradeo resource via fastapi.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

from fastapi import FastAPI,Request
import gradio as gr
from gradio_ui import demo
import uvicorn
from sap import xssec
from cfenv import AppEnv
from starlette.middleware.sessions import SessionMiddleware
from starlette.responses import HTMLResponse, RedirectResponse

app = FastAPI()
env = AppEnv()
uaa_service = env.get_service(name='gradiouaa').credentials

@app.get('/')
async def root(request: Request):
    print(request.headers)
    if 'authorization' not in request.headers:
         return 'not authenticated', 403
    access_token = request.headers.get('authorization')[7:]
    security_context = xssec.create_security_context(access_token, uaa_service)
    isAuthorized = security_context.check_scope('openid')
    if not isAuthorized:
         return 'not authenticated', 403
    return 'Gradio app is running at /gradio', 200
    
app = gr.mount_gradio_app(app, demo, path='/gradio')

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=port)

### System Info

```shell
gradio version
4.13.0

FastApi
0.108.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
@jayadnure if you'd like to test this feature, I have a PR ready here: https://github.com/gradio-app/gradio/pull/7557

You can install this Gradio from this PR by doing: 

```bash
pip install !pip install -q https://gradio-builds.s3.amazonaws.com/abf7bda7be2e2375e09514fde0ea8c86491900af/gradio-4.19.2-py3-none-any.whl
```

And you can add e.g. Google OAuth to your Gradio app like this:

```py
import os
from authlib.integrations.starlette_client import OAuth, OAuthError
from fastapi import FastAPI, Depends, Request
from starlette.config import Config
from starlette.responses import RedirectResponse
from starlette.middleware.sessions import SessionMiddleware
import uvicorn
import gradio as gr

app = FastAPI()

# OAuth settings
GOOGLE_CLIENT_ID = "..."
GOOGLE_CLIENT_SECRET = "..."
SECRET_KEY = "..."

# Set up OAuth
config_data = {'GOOGLE_CLIENT_ID': GOOGLE_CLIENT_ID, 'GOOGLE_CLIENT_SECRET': GOOGLE_CLIENT_SECRET}
starlette_config = Config(environ=config_data)
oauth = OAuth(starlette_config)
oauth.register(
    name='google',
    server_metadata_url='https://accounts.google.com/.well-known/openid-configuration',
    client_kwargs={'scope': 'openid email profile'},
)

SECRET_KEY = os.environ.get('SECRET_KEY') or "a_very_secret_key"
app.add_middleware(SessionMiddleware, secret_key=SECRET_KEY)

# Dependency to get the current user
def get_user(request: Request):
    user = request.session.get('user')
    if user:
        return user['name']
    return None

@app.get('/')
def public(user: dict = Depends(get_user)):
    if user:
        return RedirectResponse(url='/gradio')
    else:
        return RedirectResponse(url='/login-demo')

@app.route('/logout')
async def logout(request: Request):
    request.session.pop('user', None)
    return RedirectResponse(url='/')

@app.route('/login')
async def login(request: Request):
    redirect_uri = request.url_for('auth')
    return await oauth.google.authorize_redirect(request, redirect_uri)

@app.route('/auth')
async def auth(request: Request):
    try:
        access_token = await oauth.google.authorize_access_token(request)
    except OAuthError:
        return RedirectResponse(url='/')
    request.session['user'] = dict(access_token)["userinfo"]
    return RedirectResponse(url='/')

with gr.Blocks() as login_demo:
    gr.Button("Login", link="/login")

app = gr.mount_gradio_app(app, login_demo, path="/login-demo")

def greet(request: gr.Request):
    return f"Welcome to Gradio, {request.username}"

with gr.Blocks() as main_demo:
    m = gr.Markdown("Welcome to Gradio!")
    gr.Button("Logout", link="/logout")
    main_demo.load(greet, None, m)

app = gr.mount_gradio_app(app, main_demo, path="/gradio", auth_dependency=get_user)


if __name__ == '__main__':
    uvicorn.run(app)

```
