### ISSUE TITLE
Allow gr.File with type="binary" to completely omit saving a file to hard drive/store directly to memory

### ISSUE THREAD

**Issue by Wwilcz2** [gradio-app/gradio#7009]
Currently gr.File still creates an uploaded file in temporary folder. My case is due to security reasons I would like to store the file in memory only, even on rented environments (where mounting file systems is not possible).

**Comment by abidlabs** [comment]
Can you provide a repro for us to investigate?

**Comment by abidlabs** [comment]
Closing for lack of follow up
