### ISSUE TITLE
File Uploading Issue

### ISSUE THREAD

**Issue by samarth70** [gradio-app/gradio#701]
Hi, I am unable to take examples and use them as input. Though if I upload the file manually the app is working fine.

Link to the app- https://huggingface.co/spaces/Sa-m/manifesto

Error-
![image](https://user-images.githubusercontent.com/44370096/155064876-7bdc4ecf-2d4e-4097-91bd-e4e3f861e152.png)

**Comment by abidlabs** [comment]
Thanks @samarth70. This is most likely the same issue as #694, which we are working on resolving soon!
