### ISSUE TITLE
Drag and drop doesn't work (neither on Safari or Chrome)

### ISSUE THREAD

**Issue by ngaudemet** [gradio-app/gradio#7010]
### Describe the bug

The File Component (or Image, or Audio, etc.) proposes to upload a file or to "drop It". But the "drop" functionality doesn't work (is "drop" for "drag and drop" ? doesn't work) -> it should work, or it shouldn't propose it at all (which could reduce the size of the File / Audio / Image, etc.  box, which are uselessly huge when they are empty in my opinion :-)
congrats for the great work and thanks 

It was supposed to be fixed in issue "Fixes Drag and Drop for Upload #6525" in gradio==4.9.1
<img width="643" alt="image" src="https://github.com/gradio-app/gradio/assets/126974970/65b754bf-e6d3-481f-b9d1-72c4cd06ff3c">
but the truth is I didn't see any fix, it doesn't work, and I'am on gradio 4.12.0.

the weird thing is that is pushes a warning when I try to drop a file that is not compatible (exemple : a pdf for an audio file). but when the file is compatible, it doesn't drop anything

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

file = gr.File(
                label="upload a file",
                file_count="single",
                file_types=[".pdf", ".docx", ".pptx", ".doc", ".ppt"],
            )

### Screenshot

<img width="253" alt="image" src="https://github.com/gradio-app/gradio/assets/126974970/d4583f4f-e895-43a8-a3c9-b3a0875c3865">

### System Info

```shell
gradio==4.12.0
```

### Severity

I can work around it

**Comment by dawoodkhan82** [comment]
@ngaudemet I think this open PR fixes this issue. https://github.com/gradio-app/gradio/pull/6982

**Comment by ngaudemet** [comment]
that would be great, thanks @dawoodkhan82
