### ISSUE TITLE
Has anyone encountered an error during packaging operation？？

### ISSUE THREAD

**Issue by wisesoftym** [gradio-app/gradio#7012]
### Describe the bug

![err](https://github.com/gradio-app/gradio/assets/9667232/aec42a14-edd6-4dbb-9b15-0aca1ef010e0)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
Window10
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @wisesoftym !

I will close this due to lack of information on the ticket. Please include the gradio version and script you are running at the minimum. Using `gradio environment` to populate the System Info would be great too.

**Comment by wisesoftym** [comment]
![image](https://github.com/gradio-app/gradio/assets/9667232/eada81b6-bc03-490d-8632-939f546a6feb)
Here is gradio env！

**Comment by wisesoftym** [comment]
> Hi @wisesoftym !
> 
> I will close this due to lack of information on the ticket. Please include the gradio version and script you are running at the minimum. Using `gradio environment` to populate the System Info would be great too.

![image](https://github.com/gradio-app/gradio/assets/9667232/beb22d27-8455-4982-8fc6-6082c0beec6d)

**Comment by wisesoftym** [comment]
> > Hi @wisesoftym !
> > I will close this due to lack of information on the ticket. Please include the gradio version and script you are running at the minimum. Using `gradio environment` to populate the System Info would be great too.
> 
> ![image](https://private-user-images.githubusercontent.com/9667232/297626186-beb22d27-8455-4982-8fc6-6082c0beec6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTU2MjQsIm5iZiI6MTcwNTU1NTMyNCwicGF0aCI6Ii85NjY3MjMyLzI5NzYyNjE4Ni1iZWIyMmQyNy04NDU1LTQ5ODItOGZjNi02MDgyYzBiZWVjNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMDUyMjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTk1ODAxZDZmODY3NDhmMzg2Njc5OGUyZmI4YmJmNGU2MGJiZWYzNTE5NjZlMDJkYzU4OWJlYjc1ZTg4MmJiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CuFQmRD6r71K4AyLw6o5khHhjdN_k5jhnKBmzmNAPQM)

I used pyinstaller to package and generate exe, but ran an error message.
