### ISSUE TITLE
uploaded video can't show successful 

### ISSUE THREAD

**Issue by Bryannnnn-Pan** [gradio-app/gradio#7014]
### Describe the bug

after  video uploaded,the video  can't show successful 
before upload
<img width="1547" alt="image" src="https://github.com/gradio-app/gradio/assets/63450421/4eb5180e-2aa2-4d93-a657-db8146eff98b">
after
<img width="1519" alt="image" src="https://github.com/gradio-app/gradio/assets/63450421/62618381-02a5-4aee-a15d-255f88f5c4be">
 code:
<img width="413" alt="image" src="https://github.com/gradio-app/gradio/assets/63450421/1381b1e0-786f-4ab0-b251-5fcc390c298b">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as iface:

    with gr.Row():  
            video_input = gr.Video()

```

### Screenshot

before upload
<img width="1547" alt="image" src="https://github.com/gradio-app/gradio/assets/63450421/4eb5180e-2aa2-4d93-a657-db8146eff98b">
after
<img width="1519" alt="image" src="https://github.com/gradio-app/gradio/assets/63450421/62618381-02a5-4aee-a15d-255f88f5c4be">

### Logs

```shell
no errors
```

### System Info

```shell
no logs
```

### Severity

Blocking usage of gradio

**Comment by yadavj2008** [comment]
Hi @Bryannnnn-Pan It works for me with your sample code, I'm using gradio 4.14.0 version.
Can you share debug logs?

**Comment by Bryannnnn-Pan** [comment]
您好，您的邮件我已经收到！将尽快给您回复！

**Comment by freddyaboulton** [comment]
Hi @Bryannnnn-Pan ! Going to close until we get more information. We haven't been able to reproduce!
