### ISSUE TITLE
Chatbox (still) has broken text selection in Safari

### ISSUE THREAD

**Issue by tomjorquera** [gradio-app/gradio#7017]
# Description

Users on Safari reported that partial text selection (aka trying to select text from the middle) does not work on messages in the Chatbox component.

One of the users, using Safari version 17.1, has confirmed the issue is reproducible on the official documentation widget at the end of https://www.gradio.app/docs/chatinterface

Looking at closed issues, it seems very related to #6256

PR #6316 fixed that issue by adding the CSS property `user-select="text"` to Chatbox messages. But according to https://developer.mozilla.org/en-US/docs/Web/CSS/user-select#browser_compatibility Safari requires the vendor prefix `-webkit-`.

I suspect this is the source of the problem.

## Additional info

I tried to add this property as custom CSS as a workaround, but for some reason it did not appear on the elements when inspecting them in the browser.

What I tried:

```python

css = """
.message button {
    -webkit-user-select="text";
}
"""
with gr.Blocks(css=css):
    ...

```

(I checked adding other properties, such as turning the text blue, which worked fine)

## More additional info

One user reported that adding the property `-webkit-user-select="text"` manually from the browser by editing the CSS locally *did not* solve the issue, but that `-webkit-user-select="all"` did. Not sure what to do with this information however :sweat_smile: 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

The issue can be reproduced using Safari and the code from the ChatInterface guide

```python
import gradio as gr

def echo(message, history):
    return message

demo = gr.ChatInterface(fn=echo, examples=["hello", "hola", "merhaba"], title="Echo Bot")
demo.launch()

```

### System Info

```shell
Don't have it on hand right now sorry (may update) if needed, but tested with the latest release.

Also observed on the version used for the doc interactive widgets.
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio
