### ISSUE TITLE
No output image when using webcam streaming input  

### ISSUE THREAD

**Issue by nassimberrada** [gradio-app/gradio#7021]
### Describe the bug

Hi! 

I am trying to build a demo that uses the webcam as input feed to perform real-time image editing. Unfortunately, I don't seem to get any output despite the webcam input stream working properly. I am getting the same behavior whether using the example snippet in the doc:

```
demo = gr.Interface(
    fn=flip,
    inputs=gr.Image(sources=["webcam"], streaming=True),
    outputs=gr.Image(),
    live=True
    )
demo.launch(share=True)
```
or the no-loading solution proposed in one of the threads as follows:
```
with gr.Blocks() as demo:
    with gr.Row():
        input_img = gr.Image(sources=["webcam"])
        output_img = gr.Image()
        input_img.stream(flip, input_img, output_img)
demo.launch(share=True)
```
I am encountering this issue when running on a standard google colab instance, both on the Ipython embedded application and the shared link. The issue doesn't seem related to browser settings as I experienced this on different browsers but this seems to work when running locally (albeit very slowly).

The attached screenshot shows a black screen on the input side but this is just due to my camera being covered, I can confirm the input feed is working properly.

Would love to get any pointers to solve this, thanks! 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python

import gradio as gr
import numpy as np

def flip(im):
    return np.flipud(im)

# No loading 

with gr.Blocks() as demo:
    with gr.Row():
        input_img = gr.Image(sources=["webcam"])
        output_img = gr.Image()
        input_img.stream(flip, input_img, output_img)
demo.launch(share=True)

# Or standard streaming
demo = gr.Interface(
    fn=flip,
    inputs=gr.Image(sources=["webcam"], streaming=True),
    outputs=gr.Image(),
    live=True
    )
demo.launch(share=True)
```

### Screenshot

![gradio_issue](https://github.com/gradio-app/gradio/assets/112006029/a9f76693-abb0-42ab-8ba1-a2f639378504)

### Logs

```shell
No error
```

### System Info

```shell
Gradio version 4.14.0
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
I can repro the problem when using the `Interface` code snippet but blocks.

**Comment by HubHop** [comment]
same here

**Comment by donnadulcinea** [comment]
Not sure this is related, but I am unable to use gradio webcam at all. With any version matrix of gradio and python.
Getting

`Webcam.svelte:49 Uncaught (in promise) DOMException: Could not start video source`

From my chrome console inspector.

It worked well until few weeks ago.

**Comment by freddyaboulton** [comment]
@donnadulcinea does your browser have access to the webcam?

**Comment by donnadulcinea** [comment]
> @donnadulcinea does your browser have access to the webcam?

Yes, I can use Google meet and any other program plus I tried with online cam tools checkup.
The McAfee Antivirus blocks gradio when Share=True (I saw this is a known issue). So I removed it.
 I allow the camera when asked and it's allowed, not other errors.

**Comment by abhishekkr** [comment]
I was facing same issue.. but got resolved.

In my case, I enabled Camera Access when permission was asked.. but that just started showing my input stream & output feed was blank.
I did some print-debugging and realized `preprocessing(..)` in *gradio/components/image.py* was itself receiving `None`.

So after trying few different bits.. just to double check, I opened **Site Settings** from Chrome's address bar. For some reason it still had `Camera` set to `Allow (ask)` although right on tab it showed an enabed radio button for it.

I enabled it from **Site Settings** and my output feed started working.

**Comment by abhishekkr** [comment]
@nassimberrada I was trying in Incognito mode; may be my issue was due to that.

**Comment by aqibsaeed** [comment]
I am facing the same issue with Gradio 4.19.1. I tried it running in COLAB and locally on different browsers but output window is empty. 

```
demo = gr.Interface(
    fn=process,
    inputs=gr.Image(sources=["webcam"], streaming=True),
    outputs=gr.Image(type="pil"),
    live=True,
   allow_flagging="never"
    )
demo.launch(share=True)
```

**Comment by freddyaboulton** [comment]
I am not able to reproduce @aqibsaeed - are there any error messages in the browser console? Can you share a minimal reproducer? (The implementation of the process function)

**Comment by aqibsaeed** [comment]
@freddyaboulton. Please see the following, may be I have missed some thing here.

```
import gradio as gr

def fn_image(image):
    return image

webcam_interface = gr.Interface(
    fn_image,
    inputs=[
        gr.Image(sources=["webcam"], streaming=True),
    ],
    outputs=gr.Image(type="pil"),
    live=True,
    title="Webcam",
    allow_flagging="never"
)

if __name__ == "__main__":
    webcam_interface.launch()

```

**Comment by aqibsaeed** [comment]
@freddyaboulton any thoughts on this? Thanks in advance.

**Comment by freddyaboulton** [comment]
Hi @aqibsaeed ! I see an output image though the demo is slow because of the latency caused by going from your laptop to the share server and to colab.

<img width="1419" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/2dc2a787-2ac6-4c65-963f-1d18d3a94785">

**Comment by aqibsaeed** [comment]
Strange, it's not working for me in colab/locally! Which version of gradio is it?

**Comment by xbodx** [comment]
Does not work with the version of gradio 4.19.2, but works with the version of gradio 3.50.2

https://github.com/gradio-app/gradio/assets/22348021/79110f62-e166-48a2-8726-9e26231fc558

`import gradio as gr
import numpy as np


def flip(im):
    logging.info(datetime.now())
    return np.flipud(im)

with gr.Blocks() as demo:
    with gr.Row():
        inp = gr.Image(source="webcam", streaming=True)
        out = gr.Image()
        inp.change(flip, inp, out)

if __name__ == "__main__":
    demo.queue().launch()`
