### ISSUE TITLE
Custom Components dev server not working beause of Local Import

### ISSUE THREAD

**Issue by aersam** [gradio-app/gradio#7025]
### Describe the bug

Hi there

I just tried creating a component, start that dev server and get stuff running. However I cannot open the page in the browser, since it's blocking an import to a local file, which seems to be generated by Gradio:

```javascript
  window.__GRADIO__CC__ = {"618eac12c5f429bf7bd0d99e13fa7e11": {
			example: () => import("C:/Projects/Playground/SQLGenerator.AI/aceeditor/frontend/Example.svelte"),

			component: () => import("C:/Projects/Playground/SQLGenerator.AI/aceeditor/frontend")
			},
```

This cannot work, of course, since the Browser will block such requests. Did I setup something wrong? 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```shell
gradio cc create AceEditor --template SimpleTextbox 
cd .\aceeditor
gradio cc dev
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/5270024/202f3122-e007-438e-bcae-ad6f62ab54d5)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.13.0
gradio_client version: 0.8.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.108.0
ffmpy: 0.3.1
gradio-client==0.8.0 is not installed.
httpx: 0.25.2
huggingface-hub: 0.20.2
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.3
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.4
pillow: 10.2.0
pydantic: 2.5.3
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.25.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.25.2
huggingface-hub: 0.20.2
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @aersam ! You didn't do anything wrong - I've seen the same problem on windows too. Problem is not present in OSX or Ubuntu.

**Comment by kingandrewsolomon** [comment]
How did you work around it? I can't seem to get gradio to import my custom component.

**Comment by aersam** [comment]
I could not make it work...

**Comment by arav-agarwal2** [comment]
Can someone on the poetry team comment on what could cause this issue?

I'm trying to build my first custom component using WSL2, as that's my main development environment, and I am just running into a whole host of errors with it. 

I hoped that I could build the component, and then run the server, but after the dev server breaks, I'm unable to launch a standard Gradio app that **doesn't** have the component at all.

I'm happy to provide deeper repro if needed however the team wants to handle it - but some clarification on what would help would help us help the team out. If you all know, some insight as to what the cause is would be helpful.

**Comment by freddyaboulton** [comment]
Hi @arav-agarwal2 ! Hard to know what the issue is without the repro steps. Can you please share them?
