### ISSUE TITLE
Including custom component returns 404 for style.css

### ISSUE THREAD

**Issue by redevined** [gradio-app/gradio#7026]
### Describe the bug

I'm creating a custom component for displaying information about generic jobs/tasks.
While developing with `gradio cc dev`, the component behaves correctly, but as soon as I import and use the component in another Gradio app, the frontend hangs on the loading screen, and the network tab shows a 404 for style.css. My component does not include a manually created style.css, so I figured it is an auto-generated file.

_EDIT:_ This issue also occurs for a brand new custom component templating `SimpleTextbox`, code below is adjusted accordingly.

Funnily enough, I do have another custom component, with which I don't experience the described issue.

The issue seems related to https://github.com/gradio-app/gradio/issues/6748, however I am not running my application behind a proxy.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

1. Create custom component with `gradio cc create JobOverview --template SimpleTextbox`
2. Build custom component `gradio cc build`
3. Create new venv and install wheel with pip
4. Write app.py:
```python
import gradio as gr
from gradio_joboverview import JobOverview

with gr.Blocks() as demo:
    jobs = JobOverview()

demo.launch()
```
5. Launch `gradio app.py`

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/7523239/9d86dd2e-a491-4136-b41e-182338892d1d)
![image](https://github.com/gradio-app/gradio/assets/7523239/527edcdd-a3a5-4c9d-b2e0-9951b0f3c531)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.14.0
gradio_client version: 0.8.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.109.0
ffmpy: 0.3.1
gradio-client==0.8.0 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.2
importlib-resources: 6.1.1
jinja2: 3.1.3
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.3
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.4
pillow: 10.2.0
pydantic: 2.5.3
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.25.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.26.0
huggingface-hub: 0.20.2
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @redevined ! 

So you're saying that running `python app.py` in a file that uses your `JobOverview` component does not work? Did you run `gradio cc build` before running the `app.py` file?

**Comment by redevined** [comment]
Update: the issue seems to relate to the `SimpleTextbox` template. I tried creating a brand new component `MySimpleTextbox`, and observed the same problem. When creating another new component `MyGallery` from the `Gallery` template, using `MyGallery` in the app works just fine.

**Comment by freddyaboulton** [comment]
Hi @redevined ! Just wondering, if you install your custom component `gradio cc install` manually are the `template` folders created?

**Comment by redevined** [comment]
Ok, so here's what I found out through some additional digging:

The problem seems to occur when developing the custom component and the actual app in the same venv. In order to do `pip install dist/gradio_mysimpletextbox-0.0.1-py3-none-any.whl`, I have to do `pip uninstall gradio_mysimpletextbox` first, because Gradio installs the package in dev mode. This has me locked in some back and forth, because I have to uninstall and install the package again, each time I make changes to `MySimpleTextbox`.

After doing `pip uninstall gradio_mysimpletextbox`, `gradio cc build` completes successfully, but does _not create the template folders_. If I don't uninstall the wheel again before doing `gradio cc build`, I get node errors:
```
| 📦 Building package in debug                                                                                                                      │
│ 🔢 Package will use version 0.0.1 defined in pyproject.toml file. Set --bump-version to automatically bump the version number.                    │
│ 🎨 Building frontend                                                                                                                              │
│ 🟥 Build failed!                                                                                                                                  │
│ node:fs:453                                                                                                                                       │
│     return binding.readFileUtf8(path, stringToFlags(options.flag));                                                                               │
│                    ^                                                                                                                              │
│                                                                                                                                                   │
│ Error: ENOENT: no such file or directory, open '.../lib/python3.11/frontend/package.json'                      │
│     at Module.readFileSync (node:fs:453:20)
[...]
```

Simple fix is two use separate venvs for developing the custom component and the app.

**Comment by freddyaboulton** [comment]
Hi @redevined ! 

I'm glad you found a workaround but it doesn't sound ideal. I'd like to fix it for you but I don't know how to recreate the problem.

Here's what I did.

1. Created a venv and activated it. All subsequent cli commands are run from within this env.
2. Installed gradio 4.14.0
3. Created a component, e.g. `gradio cc create MyTB --template SimpleTextbox`
4. Run `gradio cc dev` and make some modifications to the demo
5. Run `gradio cc build`
6. Add an application file `app.py` that uses my custom component
7. Run `python app.py`.
8. The page loads correctly and the app works as expected.

is your process in any way different from mine? Note that you don't need to install the wheel after `gradio cc build` in order to run an app using your custom component.

I wonder if you can share a github or HF space repo with your code and the exact steps to reproduce? 

Thanks

**Comment by redevined** [comment]
Inserting `pip uninstall gradio_simpletextbox` between steps 4 and 5 should reproduce my issue.

Biggest difference in our processes is us using [Poetry](https://python-poetry.org/) for dependency management. Right now, in order build out Poetry project, we are installing other local dependencies from wheels, as we do with our custom component. That's why, in our Docker container and in other dev's setup, the component is not installed into the venv off the bat.

However, our issue seems to be heavily dependent on our development setup, and not something many users will run into.
Therefore I think we can close this.

**Comment by timothyjlaurent** [comment]
Ug -- this is biting me, I have a CC that works but can't use it
