### ISSUE TITLE
401 unauthorized to download image generated by API

### ISSUE THREAD

**Issue by ThomasCosyn** [gradio-app/gradio#7028]
### Describe the bug

Dear developers,
I developed a gradio application that generates images. I want to call this application by API. I added the authentication (username/password) setting to my application so that it secures the API.
When I call the API, the job generating the image is triggered, the image is generated and stored into temporary storage
However I cannot download it and get a 401 unauthorized error message :

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
with gr.Blocks() as app:
 # the code of my app

app.launch(
    server_name="0.0.0.0",
    server_port=8000,
    show_error=True,
    auth=[Constant.META_AGENT_USERNAME, Constant.META_AGENT_PASSWORD]
)
```

### Logs

```shell
httpx.HTTPStatusError: Client error '401 Unauthorized' for url '[https://imager-dev-clone.azurewebsites.net/file=/tmp/gradio/97a782f30edc171229ff6d7a77a579490bcf6644/generated_00.pngse2024-01-16T113A413A30Zsigd0os9FjoUjAIhbFCNcjy7DbORH4QOPg2BHLrpld98gS83Dske2024-01-19T093A053A18Zskoide52d5ed7-0657-4f62-bc12-7e5dbb260a96sksbskt2024-01-12T093A053A18Zsktid33e01921-4d'] For more information check: [https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401]
```

### System Info

```shell
gradio 4.12.0
gradio-client 0.8.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @ThomasCosyn can you please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by abidlabs** [comment]
Closing for lack of repro for now (can reopen if we have a repro)

**Comment by djaym7** [comment]
this was client cashing, 
repro:

start sevice :gr.launch()

c = Client(auth) 

stop sevice : stop the process
start sevice :gr.launch()

c.predict(auth) -- this will throw 401 unauthorized


Solution:



start sevice :gr.launch()

c = Client(auth) 

stop sevice : stop the process
start sevice :gr.launch()
c = Client(auth)  #reload client

c.predict(auth) -- no  401 unauthorized error
