### ISSUE TITLE
Guide on embedding Gradio demos

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#703]
From one of our power users:

> Hi Abid, wondering if there's documentation on how Gradio apps hosted on Spaces can be embedded on websites like Medium, or something you create on SquareSpace. I've seen embedding mentioned a few times, but haven't been able to find clear examples. Or is this feature not fully ready yet? Thanks and appreciate you and your team's work

**Comment by freddyaboulton** [comment]
@abidlabs this is done right? https://github.com/gradio-app/gradio/pull/1468 . Waiting on the website to update but I think we can close.

**Comment by abidlabs** [comment]
Yup!
