### ISSUE TITLE
A parameter for Textbox so it must have input

### ISSUE THREAD

**Issue by michaelgrewal** [gradio-app/gradio#7031]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Yes, I only want to submit from a gr.Textbox if and only if there is text inside of it. It shouldn't allow empty textbox submit with ENTER.

**Describe the solution you'd like**  
gr.Textbox should not submit if there is no text inside and user presses ENTER.

**Additional context**  
When using other popular chatbots like OpenAI ChatGPT, the ENTER key will add a new line when the textbox is empty. Other chatbots will do nothing if user presses ENTER and textbox is empty. Only when there is some text inside, then ENTER will submit.

This feature can be extended further by adding parameters for type checking.

**Comment by freddyaboulton** [comment]
Hi @michaelgrewal !

I think this is a special case of this issue #2718 so I will close . @dawoodkhan82 is working on #2718 soon!
