### ISSUE TITLE
Lite: Desktop app bundler

### ISSUE THREAD

**Issue by whitphx** [gradio-app/gradio#7032]
Gradio-lite runs entirely on web browsers, so it can be packaged into a desktop app executable by using something like Electron or Tauri.

Related issues:
* https://github.com/gradio-app/gradio/issues/6990
* https://github.com/gradio-app/gradio/issues/6954
* https://github.com/gradio-app/gradio/issues/2257

Ref:
stlite (Wasm Streamlit) has a desktop app bundler which uses Electron: https://github.com/whitphx/stlite/tree/main/packages/desktop

**Comment by trivikramak** [comment]
Any updates on this?

**Comment by rahulmr** [comment]
This is super cool, please update about the progress

**Comment by borisalmonacid** [comment]
> @trivikramak Hi, Sorry but we came to think this task had a lower priority because Gradio's major use cases are machine learning apps but most ML libraries are still not available on Pyodide or Gradio-Lite so the desktop ver. won't cover its major use cases at this moment, unlike Streamlit/stlite.
> 
> We would appreciate it if there are any suggestions/insights on how you and other users can use the Gradio-Lite desktop app bundler that helps this discussion. Thanks!

any update???
