### ISSUE TITLE
Lite: image and gallery output widgets make spurious GET requests if image is larger than some size

### ISSUE THREAD

**Issue by fcole** [gradio-app/gradio#7036]
### Describe the bug

For interface functions that have an output image or gallery, there seems to be some threshold of image size that changes the behavior and introduces a bug in gradio-lite. If the image is too large, spurious GET requests will be issued that look like:

GET https://www.gradio.app/file=/tmp/gradio/0915498aa2aeabbf1780f517e0941334dae69ed5/image.png 404 (Not Found)

Oddly, the image is eventually displayed correctly, it just takes an extra second and a broken image icon appearing temporarily. 

The bug can be reproduced in the playground (https://www.gradio.app/playground).

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import numpy as np

def get_an_image(name):
  return np.random.rand(3,512,512,3) # This line causes the bug
  # return np.random.rand(3,100,100,3) # This line does not cause the bug

demo = gr.Interface(fn=get_an_image, inputs="textbox", outputs="gallery")
    
if __name__ == "__main__":
  demo.launch()

```

### Screenshot

<img width="1304" alt="image" src="https://github.com/gradio-app/gradio/assets/508398/b9b44635-635a-48d9-867e-83567068ab90">

### System Info

```shell
Running the gradio playground.
```

### Severity

I can work around it

**Comment by stefanengelmann** [comment]
![Recording 2024-05-08 at 14 20 51](https://github.com/gradio-app/gradio/assets/85350891/7140d4d2-9dab-410c-bd70-c467046353ec)
I have this issue when running the example hosted on a browser (I am using Chrome) and regardless of the size of the image

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio
