### ISSUE TITLE
share=True Failed to generate a shared link

### ISSUE THREAD

**Issue by sp1128** [gradio-app/gradio#7057]
### Describe the bug

An error occurred after opening the share: The share link could not be created. Missing files :C: \ Users \ 1 PycharmProjects \ pythonProject \ venv \ lib \ site-packages \ gradio \ FRpc_windows_AMd64_v2.0. Then follow the prompts to complete the file, run again still report this error.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/95538256/48e6ad3d-8401-44c3-ad19-0f73278db614)
![image](https://github.com/gradio-app/gradio/assets/95538256/6ddfb5fd-7c1e-45ad-b719-e93cc4c23a6c)

### System Info

```shell
gradio=4.14.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @sp1128  can you please use this issue to report all share link related issues? https://github.com/gradio-app/gradio/issues/3677
