### ISSUE TITLE
Gradio redesign

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#706]
This is a tracking issue for the upcoming gradio redesign. More details to follow.

_(in no particular order)_

- Redesign individual components
- Implement redesign
   - pre-req: separate components out into independent entities and untangle business logic (in progress). 
- Design/ redesign/ improve UX of complex components (uploads/ image/ audio)
- Redesign gradio website using new components + implement
   - pre-req: tooling that allows us to use  components on the site
   
@gary149 @abidlabs @aliabd @aliabid94 @dawoodkhan82

**Comment by abidlabs** [comment]
@pngwn I think we can close this issue as we have more detailed issues that have superseded this one?
