### ISSUE TITLE
How to create different conversations like ChatGPT UI

### ISSUE THREAD

**Issue by scheung38** [gradio-app/gradio#7064]
Is it using Tab or TabInterface?

If using one of the above, then how do we dynamically label different conversation titles just like ChatGPT UI, or it is intelligent enough to self assign chat title for each conversation tab?

**Comment by abidlabs** [comment]
Hi @scheung38 Gradio only provides the building blocks for the user interface. For something like this:

> enough to self assign chat title for each conversation tab

you'd have to use a LLM yourself. 

If you'd like to use a pre-built GUI that includes things like conversation management, I'd recommend checking out the UI for HuggingChat, which is open-source: https://huggingface.co/spaces/huggingchat/chat-ui/tree/main
