### ISSUE TITLE
CI: all PRs from forks fail CI (comment-spaces-start; Vercel)

### ISSUE THREAD

**Issue by akx** [gradio-app/gradio#7065]
#### comment-pr

PRs from forks fail to build since `secrets.COMMENT_TOKEN` is not available to builds from forks, so the `gh_token` input to [`actions/comment-pr`](https://github.com/gradio-app/github/tree/main/actions/comment-pr) fails:

```
Run gradio-app/github/actions/comment-pr@main
/home/runner/work/_actions/gradio-app/github/main/actions/comment-pr/dist/index.cjs:2127
    throw new Error("Parameter token or opts.auth is required");
```

This seems to have been added in https://github.com/gradio-app/gradio/pull/5092.

Maybe the `comment-pr` action should have an option to just skip doing anything in this case.

#### vercel

Vercel credentials aren't available for forks either.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Fork the repository and make a PR.

### System Info

```shell
GitHub Actions.
```

### Severity

I can work around it, but it's rather annoying to try to contribute to Gradio since you need to manually check whether your PRs are legitimately failing or if it's just a misconfigured CI workflow.

**Comment by abidlabs** [comment]
Thanks @akx! Agreed totally, I'll close this as we have an existing issue for this: https://github.com/gradio-app/gradio/issues/6656
