### ISSUE TITLE
Option to create events programmatically 

### ISSUE THREAD

**Issue by arian81** [gradio-app/gradio#7072]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Not being able to call events programmatically. i.e When I have started recording audio there's no way to stop recording audio programmatically without user interaction. A useful application of this would be for Real time speech detection application where you want to pass the transcribed data to a different function.

**Describe the solution you'd like**  
At current moment you can only detect events and even if the user presses the stop button you wouldn't know if the audio has been fully transcribed yet. if there's option to cause a recording stop event programmatically then you could detect when there's no more transcription and then call the stop instead of user doing that. 

**Additional context**  
This might be a very hard feature to implement I just thought maybe it's a feature other people would have use for as well. If there's already a way of doing what I described here I would definitely appreciate your comments.

**Comment by abidlabs** [comment]
Interesting, this would be a pretty big new API so I wonder if we can think of a way to facilitate the use case you described with the existing Gradio feature set:

> A useful application of this would be for Real time speech detection application where you want to pass the transcribed data to a different function.

**Comment by chrisk414** [comment]
I also would like to call ui event programmatically. 
One use case would be, simulating users inputs. This can be used in many situations, for example, automatizing user tests by calling "click", "submit" and etc.

**Comment by abidlabs** [comment]
@chrisk414 for user tests you can consider using the Python client: https://www.gradio.app/guides/getting-started-with-the-python-client

Cc @dawoodkhan82 with regards to the audio use case

**Comment by abidlabs** [comment]
Hi @arian81 this is now possible on the `5.0-dev` branch as we've added a `recording` prop in the `gr.Audio` component that can be set by events. See: https://github.com/gradio-app/gradio/pull/9419
