### ISSUE TITLE
Public URL not working when share=True

### ISSUE THREAD

**Issue by GhostlyScript** [gradio-app/gradio#7079]
### Describe the bug

A script that previously ran fine on public URL is giving a 504 Gateway Time-out error today.

This is the public URL which Gradio is reporting that my UI is running on:  edit: removed my link as this issue is resolved

However loading that page gives error 504 Gateway Time-out

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### Screenshot

edit: removed terminal screenshot with details
![504 timeout](https://github.com/gradio-app/gradio/assets/139256353/ed97cf01-f852-4cb6-a119-7d9989aa5e02)

### System Info

```shell
Windows 10
Gradio installed and I was able to successfully share the same script a few days ago
Edit: Tested on both latest version of gradio 4.15.0 and on 4.13.0 and get same result.  504 Gateway timeout.
```

### Severity

Blocking usage of gradio

**Comment by Banovvv** [comment]
I get the same using a Colab notebook. It started happening about an hour or so ago.

**Comment by GhostlyScript** [comment]
Live page is working again now thank you to whoever fixed it
