### ISSUE TITLE
gr.Tabs(selected=X) doesn't work as intended when launching

### ISSUE THREAD

**Issue by EngMarchG** [gradio-app/gradio#7085]
### Describe the bug

In the latest version 4.15.0 when starting launching a gr.Block() with Tabs and TabItems, gradio doesn't properly select the correct startup tab. It worked before and in the previous version 4.14.0, so I don't get why it isn't working now. However, functions that switch the tabs later work normally, the problem is only when launching it. I've attached a simple example below.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

# Main Layout of the GUI
with gr.Blocks() as demo:
    with gr.Tabs(selected=1) as tabs:
        # Tab 1
        with gr.Tab("Tab 1", id=0):
            gr.Textbox("You are in Tab 1")

        # Tab 2
        with gr.Tab("Tab 2", id=1):
            gr.Textbox("You are in Tab 2")

        # Tab 3
        with gr.Tab("Tab 3", id=2):
            gr.Textbox("You are in Tab 3")

# Launch the tabs
demo.launch()

```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.15.0
gradio_client version: 0.8.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.8.1 is not installed.
httpx: 0.25.1
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.3
pillow: 10.1.0
pydantic: 2.5.1
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
ruff: 0.1.14
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.1
huggingface-hub: 0.19.4
packaging: 23.2
typing-extensions: 4.8.0
websockets: 10.4
```

### Severity

I can work around it

**Comment by EngMarchG** [comment]
Thanks for the update. I don't think I'm testing it out properly, since when i update with pip: pip install -U git+https://github.com/gradio-app/gradio.git it is sucessful. However, the problem still persists. 
Likewise, installing it directly from the repository doesn't work, since I need to build the front-end with the bash file.

**Comment by abidlabs** [comment]
Hi @EngMarchG can you try installing it like this:

`pip install https://gradio-builds.s3.amazonaws.com/88d899e9633ff04400de7866d25005aa925a2ad9/gradio-4.15.0-py3-none-any.whl`

**Comment by EngMarchG** [comment]
Thank you! I tried it that way and indeed the bug is fixed now with the latest commit.
