### ISSUE TITLE
gradio client streaming eating too much CPU waiting

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#7086]
### Describe the bug

client eating 100% core waiting for server response

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

In client.py's job class in the __next__ while waiting for a response, it loops without any sleep at all and rams against a single core.  Should add some minimal sleep here.

```python
        while True:
            with self.communicator.lock:
                if len(self.communicator.job.outputs) == self._counter + 1:
                    o = self.communicator.job.outputs[self._counter]
                    self._counter += 1
                    return o
                if self.communicator.job.latest_status.code == Status.FINISHED:
                    raise StopIteration()

```

### System Info

```shell
gradio 3.52.0 or 4.15.0


```

### Severity

My only work-around is to change the gradio code itself to add the sleep.

**Comment by abidlabs** [comment]
Ah thanks @pseudotensor! Would you like to open a PR? Happy to review this week

**Comment by pseudotensor** [comment]
Sure, another issue is that this gets caught in an infinite loop if there is an early exception.
