### ISSUE TITLE
File path of the uploaded image doesn't show to the textbox after predicted.

### ISSUE THREAD

**Issue by Ohmmyomemy** [gradio-app/gradio#7096]

**Comment by abidlabs** [comment]
Hi @Ohmmyomemy there is no repro or even a description of this issue so I'm closing. Thanks.

**Comment by Ohmmyomemy** [comment]
> Hi @Ohmmyomemy there is no repro or even a description of this issue so I'm closing. Thanks.

Sry for the technical issues. i will upload the issues again. Thank you for you attention
