### ISSUE TITLE
Custom Components: README.md doesn't match settings

### ISSUE THREAD

**Issue by LennardZuendorf** [gradio-app/gradio#7105]
### Describe the bug

I've been playing around with the custom components and noticed a simple error:

When setting up a component, you ask, i.e., for a license, but when uploading to Huggingface Spaces, the license in the README is not set correctly. Also, the README information from the component README isn't copied, which seems counterintuitive to me...

I'm aware that the src code is not necessarily included in a spaces demo, but still, I think if it is, the readme should be the same or copied with i.e. a little disclaimer as such "# Component Readme". This is kind of a mix between bug and feature request. Hope that's still fine.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction
Create a custom component, set up a license, and then publish it on Huggingface Hub. I have an MIT license, but in the configuration of the space you set up for Apache 2.0, 

Also, upon inspecting the README, you'll see the content between the top-level README in spaces and the README of the custom component doesn't match.

To see the issue, you can check out the [spaces ](https://huggingface.co/spaces/LennardZuendorf/gradio_iframe/tree/main).

### Screenshot

(Sorry for the light mode; I'm currently testing other stuff. My eyes are also suffering ^^)

#### Huggingface Spaces README.md
![Huggingface Spaces README.md](https://github.com/gradio-app/gradio/assets/72448991/3ca21085-1c5c-46f3-8d27-eef2c5ffb733)

#### Component pyproject.toml
![pyproject.toml](https://github.com/gradio-app/gradio/assets/72448991/03656184-16ac-446f-825b-1c6174f39e73)

#### Component README.md
![component README.md (in src)](https://github.com/gradio-app/gradio/assets/72448991/b4120769-2756-40d5-996d-bb4a824a9156)

### System Info

```shell
Name: gradio
Version: 4.7.1
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
We're not gonna include the license in the space metadata because it has to match a set of pre-defined keywords (https://huggingface.co/docs/hub/en/repositories-licenses) and I don't want the deployed space to error in case of a typo. 

We're going to make it so that the repo readme and the space readme are the same file so users will be able to add the license themselves as well as make any other changes.
