### ISSUE TITLE
copy button on Safari Textbox doesn't work

### ISSUE THREAD

**Issue by ngaudemet** [gradio-app/gradio#7122]
### Describe the bug

it is impossible to have a copy button on safari gr.Textbox. it works well on edge and chrome, but not at all on Safari (iPhone and Desktop, version 17.2.1)

there is a closed issue on a similar topic : Safari buttons were not fixed #4034
but the issue is closed and it seems it is not fixed anymore (maybe due to a new Safari version?)

their is another non blocking issue with the copy button : when I have a copy button on a component (exemple Chatbot), in Safari but also in Chrome, sometimes the copy button doesn't work and we need to copy the content by selecting the text with the trackpad and then click on "Command C".

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

                   prompt_text = gr.components.Textbox(
                        value=f"{"test 19"}",
                        max_lines=2,
                        label=f"{"test 19"}",
                        interactive=False,
                        show_copy_button=True,
                        visible=True,
                    )

### Screenshot

<img width="1229" alt="image" src="https://github.com/gradio-app/gradio/assets/126974970/07b704c3-309f-48d9-85e4-fc72979c253a">

### Logs

```shell
their is no error in the logs even with debug=True
```

### System Info

```shell
gradio==4.15.0
gradio-client==0.8.1
Mac Safari Version 17.2.1 (on Desktop)
iOS Version 17.2.1 (on iPhone)
```

### Severity

I can work around it but it would be much better to have it work

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio
