### ISSUE TITLE
Multiple Image Upload

### ISSUE THREAD

**Issue by mangsshinde** [gradio-app/gradio#713]
Dear Abubakar Abid,

thank you for your great work.

I have one question. I am looking to build a simple UI to extract embeddings of multiple image file. Just wanted to know if there is any way to upload a folder containing images. If not, then is there any other workaround i.e. uploading a zip file for the image folder.

**Comment by abidlabs** [comment]
Thanks for your question @mangsshinde. Yes it is possible! You can do:

```python
gradio.inputs.File(file_count="multiple")
```
to select multiple files

Or even
```python
gradio.inputs.File(file_count="directory")
```
to select a directory

In both cases, the list of files that are uploaded are passed as a list to the function.

**Comment by piovis2023** [comment]
can yuo add additional files? if so- how?
