### ISSUE TITLE
Unable to upload pictures on iPhone mobile device

### ISSUE THREAD

**Issue by aiise117** [gradio-app/gradio#7137]
### Describe the bug

Clicking the image upload button opens the folder by default instead of the album library. Unable to recognize image formats in the folder directory, and also unable to click to upload them. I hope you will take note of this issue
![IMG_2066](https://github.com/gradio-app/gradio/assets/114309081/d227ff40-bc70-4667-8ed4-572ffd1fbfce)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### Screenshot

![IMG_2063](https://github.com/gradio-app/gradio/assets/114309081/0b94476d-26e5-404c-b2fb-254512d33775)
![IMG_2064](https://github.com/gradio-app/gradio/assets/114309081/98342a2b-7ae8-4e57-955d-00b9c1a1d090)
![IMG_2065](https://github.com/gradio-app/gradio/assets/114309081/829e6408-5dc6-4392-8d08-dfcb63a36cd4)
![IMG_2066](https://github.com/gradio-app/gradio/assets/114309081/b31c0d36-1f0b-4c46-ae52-378fc60cfd35)

### System Info

```shell
Yes
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @aiise117 ! 

The reason that the photo album doesn't open might be because the demo is using `gr.File` instead of `gr.Image`. Will investigate why images in your files are not allowed to be uploaded.
