### ISSUE TITLE
stop_btn not working on gr.ChatInterface

### ISSUE THREAD

**Issue by rnelson4-chwy** [gradio-app/gradio#7143]
### Describe the bug

According to the documentation, the stop_btn should "replace the submit_btn when the submit_btn or retry_btn is clicked and response is streaming. Clicking on the stop_btn will halt the chatbot response. If set to None, stop button functionality does not appear in the chatbot. If a Button object, that button will be used as the stop button.". However, there no stop button appears after clicking the submit button, even if you rename the stop_btn, it never appears. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
Name: gradio
Version: 4.15.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @rnelson4-chwy the stop button only appears if you stream responses. Here's an example showing it working:

```py
import time
import gradio as gr

def slow_echo(message, history):
    for i in range(len(message)):
        time.sleep(0.5)
        yield "You typed: " + message[: i+1]

demo = gr.ChatInterface(slow_echo).queue()

if __name__ == "__main__":
    demo.launch()

```

This works for me on `main` -- can you confirm if it works for you?

**Comment by abidlabs** [comment]
Ok great, I'll close this issue then!
