### ISSUE TITLE
Updating the root parameter in the fileexplorer component does not change the front-end display of the file directory.

### ISSUE THREAD

**Issue by lifeisgoodcdj** [gradio-app/gradio#7149]
### Describe the bug

The gr.fileexplorer() object changes the root parameter when used as a callback function, but it does not actually change the root directory of the component for file searches.
I want to know how to change the root directory of gr.fileexplorer()  

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as app:
    objFileExplorer = gr.FileExplorer(root="/home/file_path1/", show_label=True, height=400, interactive=True)
    objButtonClear = gr.Button("clear")

    @objButtonClear.click(inputs=[objFileExplorer], outputs=[objFileExplorer])
    def fnButtonClearClick(listSelectedFiles):
        print(listSelectedFiles)
        return gr.update(root="/home/file_path2/", value="", show_label=True, height=600, interactive=False)

if __name__ == "__main__":
    app.queue().launch(server_name='0.0.0.0',
                       server_port=40123,
                       share=False,
                       debug=True,
                       max_threads=2,
                       )

```

### System Info

```shell
gradio==4.4.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @lifeisgoodcdj is this still an issue in the latest version of Gradio (4.15.0)? I believe we’ve fixed it

**Comment by lifeisgoodcdj** [comment]
The issue still exists. I have tried the 4.15.0 version of gradio, but I still cannot update or switch directories actually

**Comment by abidlabs** [comment]
cc @aliabid94

**Comment by liucw2012** [comment]
i also need to update root dir ~

**Comment by freddyaboulton** [comment]
Hi @lifeisgoodcdj - the `root` parameter is deprecated for the FileExplorer. If you use `root_dir` in both the definition of `objFileExplorer` and `gr.update` it should work. If you want to use `root`, you can return a new instance of `gr.FileExplorer` in your update function. 

Going to close as this seems like a corner case with a deprecated API and fixing would require adding some component specific logic to the app-level postprocessing which would not be ideal for maintainability.
