### ISSUE TITLE
Response content longer than Content-Length

### ISSUE THREAD

**Issue by Zengyf-CVer** [gradio-app/gradio#7155]
### Describe the bug

When I uploaded this large image, the error "Response content longer than Content-Length" occurred. The following is my demo code and error message. Download address of this picture: https://github.com/Zengyf-CVer/imgs/blob/main/P0017.png

![image](https://github.com/gradio-app/gradio/assets/41098760/761c14e3-d280-4af0-b5e8-3c9df5e522a8)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr


def a(img):
    return img


with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column():
            with gr.Row():
                input_img = gr.Image()
            with gr.Row():
                btn = gr.Button(value="submit")
        with gr.Column():
            with gr.Row():
                output_img = gr.Image()

    btn.click(fn=a, inputs=[input_img], outputs=[output_img])

demo.launch(inbrowser=True)

```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/41098760/c2d539e7-6e13-4d7d-9b0e-3761f964e640)

### System Info

```shell
gradio 4.15.0
Python 3.8.18
win10
```

### Severity

I can work around it

**Comment by arian81** [comment]
I've seen this error when recording audio as well.

**Comment by freddyaboulton** [comment]
Hi @Zengyf-CVer ! Does this happen every time you try to submit that image? Does it only happen on windows? I can't repro with gradio 4.18.0

<img width="1323" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/5771e47d-639a-40b3-a65d-f475f869e47d">

**Comment by abidlabs** [comment]
Closing for lack of follow up. We can reopen if we get some more details needed to reproduce.

**Comment by Zengyf-CVer** [comment]
I tried the latest version of Gradio 4.21.0 and no such problem occurred. I guess it is a problem with version 4.15.0.
