### ISSUE TITLE
Second "Multiple Data Flows" demo is broken

### ISSUE THREAD

**Issue by kmulka-bloomberg** [gradio-app/gradio#7164]
### Describe the bug

The second demo under "Multiple Data Flows" is broken.

Here's the section of the guide:
https://www.gradio.app/guides/blocks-and-event-listeners#multiple-data-flows

Here's the demo in Spaces:
https://huggingface.co/spaces/gradio/blocks_speech_text_sentiment

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

This is a problem with a demo here:
https://huggingface.co/spaces/gradio/blocks_speech_text_sentiment

### Screenshot

![Screenshot 2024-01-25 at 3 56 04 PM](https://github.com/gradio-app/gradio/assets/118509387/608a6d91-d21c-42bf-af3e-d94ff425d0a2)

### System Info

```shell
version 4.15.0 of the guides
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Fixed thanks @kmulka-bloomberg
