### ISSUE TITLE
Custom CSS-and-JS doesn't work, when demo launched in a gr.TabbedInterface

### ISSUE THREAD

**Issue by abhishekkr** [gradio-app/gradio#7171]
### Describe the bug

Custom CSS & JS doesn't come into effect if the Interface is launched by making it a part of TabbedInterface.
Adding `debug=True` doesn't show any errors either. Nor any error logs shown on Browser Console.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr


css = """
#warning {background-color: #FFCCCB}
.feedback textarea {font-size: 24px !important}
"""

with gr.Blocks(css=css) as demo:
    box1 = gr.Textbox(value="Good Job", elem_classes="feedback")
    box2 = gr.Textbox(value="Failure", elem_id="warning", elem_classes="feedback")

gr.TabbedInterface(
    [demo],
    ["demo"]
).launch(debug=True)
```

### Screenshot

![Screenshot from 2024-01-26 18-02-00](https://github.com/gradio-app/gradio/assets/32578/05746957-c584-4700-acbe-0ca21a35bde9)

### Logs

```shell
None
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.15.0

Browser: Google Chrome
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @abhishekkr this is expected behavior, as TabbedInterface does not preserve css, themes, etc. since they can conflict between the different demos. you need to provide the custom css as the `css` argument to `TabbedInterface` itself. I think we should clarify this so I'll rewrite the docs for this.
