### ISSUE TITLE
`HH:MM:SS` time code in `gr.Audio`

### ISSUE THREAD

**Issue by jjshoots** [gradio-app/gradio#7179]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
When using the `gr.Audio` feature, for audio files over 1 hour, the timestamp is shown as `MM:SS`, so if the audio track is 1 hour and 15 minutes long, it shows 75:00. Would it be possible for this to be shown as `HH:MM:SS` instead?

**Describe the solution you'd like**  
Show timecode in `gr.Audio` as `HH:MM:SS`.

**Comment by abidlabs** [comment]
I agree that would look a bit nicer. Would you be able to open a PR to fix this? I think we'd need to make changes here:

https://github.com/gradio-app/gradio/blob/d548202d2b5bd8a99e3ebc5bf56820b0282ce0f5/js/video/shared/VideoControls.svelte#L27

and

https://github.com/gradio-app/gradio/blob/ded5256c4a39a84155b9c3d7f4e8e7060d798186/js/audio/recorder/AudioRecorder.svelte#L64

**Comment by arian81** [comment]
@abidlabs I can work on this if @jjshoots doesn't want to

**Comment by abidlabs** [comment]
Go for it @arian81! Thanks

**Comment by jjshoots** [comment]
@arian81 Are you still tackling this? I can do it if need be within the next couple days.

**Comment by arian81** [comment]
> @arian81 Are you still tackling this? I can do it if need be within the next couple days.

I was working on it because I couldn't get the video player time to change format but I think it's because it's using the browser's built in player. I pushed the changes I had.
