### ISSUE TITLE
Default `value` of `CheckboxGroup` is not `None` in 4.16.0

### ISSUE THREAD

**Issue by snakeninny** [gradio-app/gradio#7185]
### Describe the bug

`gr.CheckboxGroup(choices=[random.randint(1, 10) for _ in range(6)], value=None, interactive=True)` should be the same to `gr.CheckboxGroup(choices=[random.randint(1, 10) for _ in range(6)], interactive=True)`, but they're not, as you can see the 2 videos

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction
```
import gradio as gr
import random

with gr.Blocks() as demo:
    button = gr.Button(value="Randomize")
    checkbox_group = gr.CheckboxGroup()

    # button.click(fn=lambda: gr.CheckboxGroup(choices=[random.randint(1, 10) for _ in range(6)], value=None, interactive=True), outputs=[checkbox_group])
    button.click(fn=lambda: gr.CheckboxGroup(choices=[random.randint(1, 10) for _ in range(6)], interactive=True), outputs=[checkbox_group])

if __name__ == "__main__":
    demo.launch()
```
### Screenshot

Correct w/ `value=None`:

https://github.com/gradio-app/gradio/assets/641869/bb34d31a-56ec-4cd8-9996-71250d2a2de1

Incorrect w/o `value=None`:

https://github.com/gradio-app/gradio/assets/641869/3e953563-c6a2-43bf-836a-94d8e39feb97

### Logs

```shell
None
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.16.0
gradio_client version: 0.8.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.1.0
altair: 4.2.2
fastapi: 0.109.0
ffmpy: 0.3.0
gradio-client==0.8.1 is not installed.
httpx: 0.23.3
huggingface-hub: 0.20.2
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.2
matplotlib: 3.7.1
numpy: 1.24.2
orjson: 3.8.7
packaging: 23.0
pandas: 1.5.3
pillow: 9.4.0
pydantic: 2.5.3
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
ruff: 0.1.14
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.20.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.23.3
huggingface-hub: 0.20.2
packaging: 23.0
typing-extensions: 4.9.0
websockets: 10.4
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
That's weird. Was this working in older versions of gradio?

**Comment by snakeninny** [comment]
> That's weird. Was this working in older versions of gradio?

Tested on 4.14.0 and 4.15.0, works in 14, not since 15

**Comment by abidlabs** [comment]
I looked into this, and this is actually the correct behavior. When you return a `gr.CheckboxGroup()` from an event listener, you are updated the properties that are included in the constructor, and _only_ those properties. So in this case, since you don't explicitly update the `value`, the previously-selected value will remain.
