### ISSUE TITLE
Idea: let developers to control interactivity of all components within a tab, row, etc.

### ISSUE THREAD

**Issue by yarnabrina** [gradio-app/gradio#7188]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
After the recent introduction of `interactive` argument in `gradio.Tab`, if `interactive=False` is set user can not navigate to that page. This is happening for me with both `4.15` and `4.16`. But when I set `interactive=False`, I may want to mean all components (textbox, button, etc.) in that to be non-interactive and not in the sense that that tab can not even be navigated to.

**Describe the solution you'd like**
For `interactive=False`, the developer may mean any of the following things:

1. users should not be able to navigate to that tab -> current behaviour
2. users can navigate, but can not interact with any content of that tab -> an easier alternative to set interactive for all elements by setting just once

If `gradio.Tab` exposes a new boolean argument `can_navigate`, which has the default value of `False` to keep current behaviour of option 1 above, developers can set it to `True` to get option 2 behaviour.

**Additional context**  
Operating System: Ubuntu 22.04 (WSL 2 on Windows 11)
Python: 3.10
Gradio: 4.16

**Note**
1. With both `4.15` and `4.16`, I could not reproduce #7090 on my system as @dwipper mentioned. So, I am not sure if it's related to any OS/browser stuff.
2. I think `gradio.Row` or `gradio.Group` also do not have an `interactive` argument to easily set the interactiveness of all components inside them. That may also be of use.

**Comment by abidlabs** [comment]
Hi @yarnabrina thanks for the feature suggestion, but this would be quite a departure from our current api where setting `interactive=False` means that a specific component is disabled. I'll leave this issue open so that we can potentially brainstorm other ways to achieve setting all of the components within a particular layout disabled/enabled.

**Comment by yarnabrina** [comment]
Hi @abidlabs, thanks for considering the feature request. My request is coming from the point of view of a data scientist with no frontend knowledge using Gradio to create a quick UI demos.

Since most of the demos I create have rows or groups with specific components in it, it's very intuitive for me to think them as sort of parent-child hierarchy, and inheritance of properties by default seems intuitive.

I understand that there may be cases where this may possibly lead to complicated choices. Assuming this idea is implemented, will a developer be able to deactivate all but one component of a tab (or row/group)? For example, by first deactivating the tab/row/group and activating that component itself? Or this sort of thing can not be supported?

**Comment by abidlabs** [comment]
@yarnabrina can you give us an example (either screenshot or example code) of such a UI demo?

**Comment by yarnabrina** [comment]
@abidlabs Sure, you can find the code [here](https://github.com/yarnabrina/query-package-documentation/blob/dev/src/gui.py).

Here's a screenshot from the last tab:

![image](https://github.com/gradio-app/gradio/assets/39331844/9d315a44-99ec-4eca-ab7e-6f088eae97e4)

Here, I'll prefer to make left or right column in the second row non-interactive depending on the choice user made in the first row. If user choose to use a ctransformers compatible model, they won't configure the task type in the left column. If they does, it has no effect, so I think it's better to disable that option. On the other hand, if they want to use a standard transformers-compatible model, right column options are not useful in that case.

Now I can achieve this by updating all the components one by one, but that seems more of a hassle as they are logically grouped so it is intuitive to me to attempt to disable/enable them together. I could also have used the `visible` argument, but I want the users to know what are the different choices for different types of models, I want to show both set always.

![image](https://github.com/gradio-app/gradio/assets/39331844/58b71003-dd60-46e9-a6d3-ec7ef4ef8194)

Similarly, in this case all 3 options are relevant only for `MMR` is used, and only the first option for `SIMILARITY`.

---

(I am quite new to Gradio, only started after your Pydata Global session, so if you see I am misusing something or some feature already exists but I am missing, please let me know.)

**Comment by abidlabs** [comment]
Got it! Yes what you're describing is not currently possible, but we could potentially expose a way to do it. Right now, I'd suggest setting the whole column visible/invisible, but as you've indicated, you'd prefer not to do that.

**Comment by abidlabs** [comment]
I was thinking about this recently @yarnabrina and this *is* actually possible due to the fact that every layout has the `.children` attribute which lists all of the blocks that are its children. Because there exists a workaround, we're unlikely to extend the official Gradio api.

Here's some sample code that shows what you are trying to achieve (may need to be adapted to your use case e.g. to make it recursive)

```py
import gradio as gr

def make_all_invisible(num_components):
    def invisible():
        return [gr.update(visible=False)]*num_components
    return invisible

with gr.Blocks() as demo:
    with gr.Row() as r:
        t = gr.Audio()
        i = gr.Image()
        
    btn = gr.Button()
    btn.click(make_all_invisible(len(r.children)), None, r.children)
    
demo.launch()
```

**Comment by yarnabrina** [comment]
Hi @abidlabs, this is very nice, I'll try it right away. Thank you.

However, if I may make a request, is it possible to update Gradio documentation with these? As of now, it does not have any detailed API reference pages (e.g. what you can make with Sphinx), so I did not find any reference to `gradio.update` or `children` attribute anywhere (not even after searching in the Docs page) on https://www.gradio.app/.

**Comment by abidlabs** [comment]
Yes that's a good idea, cc-ing @aliabd for his thoughts
