### ISSUE TITLE
Paste from clipboard does not work

### ISSUE THREAD

**Issue by omerXfaruq** [gradio-app/gradio#7194]
### Describe the bug

Pasting from clipboard does not work.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Try this [space](https://huggingface.co/spaces/HuggingFaceM4/screenshot2html)

### Logs

```shell
Uncaught (in promise) TypeError: navigator.clipboard.read is not a function
    paste_clipboard Upload.svelte:46
    handle_select_source ImageUploader.svelte:89
    handle_select_source SelectSource.svelte:20
    click_handler_3 SelectSource.svelte:58
Upload.svelte:46:17
Uncaught TypeError: navigator.clipboard.read is not a function
    paste_clipboard Upload.svelte:46
12 Upload.svelte:46:17
    paste_clipboard Upload.svelte:46
```

### System Info

```shell
firefox
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
I get a different error on chrome - I wonder if they're the same. Looks like an iframe permission issue

<img width="923" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/5c12dcac-97ce-43c7-b38a-956441ec371a">

**Comment by abidlabs** [comment]
👋 @omerXfaruq

**Comment by abidlabs** [comment]
This is actually an issue with Spaces and not Gradio (can confirm by testing locally), so I've created [a PR for Space (internal link)](https://github.com/huggingface/moon-landing/pull/8792/files). I'll go ahead and close this issue.
