### ISSUE TITLE
Inconsistent ImageEditor behaviour once modified serverside

### ISSUE THREAD

**Issue by deepbeepmeep** [gradio-app/gradio#7200]
### Describe the bug

- Upload a picture in ImageEditor
- Draw some pattern A on Layer 1
- Press the button "Load" to change ONLY its background on the server
  - > first issue:  the pattern on layer 1 may have disappeared
- Draw some pattern B on Layer 1
- Press the button "Nop" that requires the ImageEditor value but does nothing
 -> second issue:  pattern B is replaced by pattern A in the Web browser altough it seems on the server side we do receive pattern B

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```py
import gradio as gr
import time
from PIL import Image

def changeimage(im):
    im['background']= Image.open("cheetah.jpg") #assumed to be in the current directory
    return im

def donothing(im):
    return None

with gr.Blocks() as demo:
    im = gr.ImageEditor(
        type="pil",
        image_mode = 'RGBA' , crop_size= [502,343],
    )
    btn = gr.Button("Load")
    nop = gr.Button("Nop")

    btn.click(
      fn=changeimage, 
      inputs=[im], 
      outputs=[im] 
      )

    nop.click(
      fn=donothing, 
      inputs=[im], 
      outputs=[] 
      )

if __name__ == "__main__":
    demo.launch(debug=True, share=False )
```

### System Info

```shell
------------------------------
Operating System: Linux
gradio version: 4.16.0
gradio_client version: 0.8.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.109.0
ffmpy: 0.3.1
gradio-client==0.8.1 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.2
importlib-resources: 6.1.1
jinja2: 3.1.3
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.24.1
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.4
pillow: 9.4.0
pydantic: 2.5.3
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
ruff: 0.1.14
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.26.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.26.0
huggingface-hub: 0.20.2
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio
