### ISSUE TITLE
Azure signed url's not working consistently for video

### ISSUE THREAD

**Issue by matthew-stewart-satalia** [gradio-app/gradio#7204]
### Describe the bug

I'm using sas url for video's stored in cloud storage accessible via http url. 

This worked fine prior to latest version. 

Now I consistently get the below txt file response:

<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:...
Time:2024-01-29T12:36:54.3735378Z</Message><AuthenticationErrorDetail>Signature fields not well formed.</AuthenticationErrorDetail></Error>

If I click retry enough times the video then renders and loads.

When the video doesn't load, I'm still able to get the value of url and pass it to downstream components in my app and they work, so the url is not the problem. The url includes the token generated by my app. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

cloud_video_files = [url1,...]

def populate_video(video_url: str):
   ... some validation to ensure url is live // CloudPath.is_file()
   return video_url

with gr.Blocks() as app:
   choice =  gr.Dropdown(choices=cloud_video_files)
   video = gr.Video()
   choice.input(fn=lambda dropdown: populate_video(dropdown), inputs=[choice], outputs=[video]
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/129737551/974dc1ab-6063-4562-91e0-d94ed7f38943)
![image](https://github.com/gradio-app/gradio/assets/129737551/3c524eba-f892-4d98-8a32-1f4816dfd926)

### System Info

```shell
------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.8.1 is not installed.
httpx: 0.25.2
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 1.5.3
pillow: 10.1.0
pydantic: 2.4.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
ruff: 0.1.14
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.2
huggingface-hub: 0.19.4
packaging: 23.2
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @matthew-stewart-satalia can you please check if the latest version of `gradio` (4.21) still has this issue? We made some fixes to how Gradio works behind proxies which may have solved this issue
