### ISSUE TITLE
Static rendering of UI components when using pure Svelte

### ISSUE THREAD

**Issue by franz101** [gradio-app/gradio#7209]
Is it possible to just use the components without gradio lite?
Using @sveltejs/adapter-static and prerendering?

**Comment by abidlabs** [comment]
Hi @franz101 can you elaborate a little more on what you mean? You'd like to use the Gradio Svelte components by themselves in a standalone Svelte app? If you could elaborate a little more, we can provide guidance on how to use.

cc @aliabd as he's working on related documentation

**Comment by franz101** [comment]
Thamks for you lightning fast response
 Need the table component in the gradio design but plain html (prerendered/SSR)

**Comment by abidlabs** [comment]
Sorry @franz101 I still don't quite follow. Can you share a potential code snippet of what you're hoping to do?

**Comment by abidlabs** [comment]
I'm going to close for now, but if the idea is to document how to do use Gradio components as standalone Svelte components, we are working on that.
