### ISSUE TITLE
Gradio based mobile apps ??

### ISSUE THREAD

**Issue by arian81** [gradio-app/gradio#7210]
- [x] I have searched to see if a similar issue already exists.

So I found this library that enables mobile apps using svelte.
I thought maybe it can be utilized to some extent to create gradio based mobile apps.

https://svelte-native.technology/

**Comment by abidlabs** [comment]
Thanks @arian81, if we did go this route, it'd probably be using a bundler like electron/tauri. Feel free to add your thoughts on this issue here: https://github.com/gradio-app/gradio/issues/7032
