### ISSUE TITLE
How to clear Image input or Video input manually when a submit textbox submited？

### ISSUE THREAD

**Issue by lucasjinreal** [gradio-app/gradio#7211]
How to clear Image input or Video input manually when a submit textbox submited？

**Comment by hrrbay** [comment]
You could simply add the image as an output of the listener and return None to it.
 ```
import gradio as gr
examples = ["https://www.vangoghmuseum.nl/asset/download/s0195V1962"]
demo = gr.Blocks()
with demo:
    im = gr.Image(height=240, interactive=True)
    text = gr.Textbox()
    gr.Examples(examples, inputs=im)
    text.submit(fn=(lambda x: None), inputs=[text], outputs=[im])
demo.launch()

```

**Comment by freddyaboulton** [comment]
Yes @hrrbay 's suggestion is the correct approach! Thanks @hrrbay .

Going to close as this is not a gradio issue. In the future, please ask general questions like this on the hugging face discord (#gradio-questions channel).

https://discord.gg/hugging-face-879548962464493619
