### ISSUE TITLE
Gradio File component not functioning correctly for 'single' file count.

### ISSUE THREAD

**Issue by yvrjsharma** [gradio-app/gradio#7212]
### Describe the bug

When `file_count` is set to `'single'` (the default), the file component does not work properly. However, setting `file_count='multiple'` seems to resolve this issue. Please refer the attached video for more information on the issue.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def dummy(file_objs):
  files = [f for f in file_objs]
  return files

with gr.Blocks() as demo:
  with gr.Row():
    fl = gr.File(file_count='single')
    tb = gr.TextArea()
  gr.Button().click(dummy, fl, tb)

demo.launch()
```

### Screenshot

https://github.com/gradio-app/gradio/assets/48665385/b8a7d28e-06ee-4d41-862a-91c473fcbe15

### System Info

```shell
Using Gradio on Google Colab
Version: 4.16.0
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Thanks for filing @yvrjsharma - I think I know the issue

**Comment by abidlabs** [comment]
Yikes good catch @yvrjsharma
