### ISSUE TITLE
Custom component feedback

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#7213]
When I was building my custom component I ran into a number of issues. Dumping here as feedback while we figure out what action to take (if any). The component I was working on was bootstrapped back in prerelease so some of these issues may not be present any more. I will be building a new component this week and will check. 

- tooling / configuration 
  - if the `project.readme` isn't set correctly you get a weird error about long description. 
  - I didn't have `gradio` in my dependencies field. 
  - gradio cc publish failed catastrophically when trying to find the latest versions of the wheel in CI meaning I had to publish manually. (Will make reproduction and file an issue)
- runtime
  - some small css bugs. We should all build some stuff to make sure various internal components work correctly when used in different contexts
  - the static / interactive flipping causes many issues. Created a separate issue for this. 
  - custom status tracker was trickier than I expected, might have just been the above issue complicating things though. The props are definitely a bit weird, I think we could clean this up. 
  - I still have no idea what all of our CSS variables are, it is really difficult to figure out what to use. 
  - I don't know what all of our components are (especially atoms) and it isn't obvious how to use them. 

Other than two obvious bugs (that there are issues for) I think some of these have been resolved in recent versions or are simply a case of improving the docs. 

All that said, it still cool how we have the whole workflow pretty self contained. And other than a few specific issues things worked really nicely. A little more refinement and documentation and this will be really slick I think.

**Comment by freddyaboulton** [comment]
Nice issue @pngwn. The issues around the tooling are already fixed in 4.15 except the issue you saw with publish. Agreed we can make the documentation/discover of CSS and our components much better.
