### ISSUE TITLE
Refactor `@gradio/client`

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#7215]
This issue is not about bugs. It may fix or uncover some or make new ones less likely but it doesn't replace those bug issues which also need to be fixed. 

The JavaScript client has become a bit messy over time and has a lot of inert code that we no longer need. It was never a picture of elegance but increasing demands have definitely made things worse. 

**main issues**

It's a giant factory function with closures on closures.

- This makes reasoning about the code pretty challenging, especially tracing values throughout the app, there is no semantic distinction between types of variables and I'm pretty sure there is a bunch of shadowing going on which makes things worse. 
- This complicates the api. There is a good reason for it being a factory but there are better patterns for our purposes. 

It's really quite a big file

- Really very big in js terms. I don't mind it myself but it is very intimidating for contributors who are used to js patterns of short files. 

There is no meaningful rationale behind what is a utility and what isn't. And there is also some inconsistency around what is inside the factory and what is outside. 

There are no tests. 

- this is bad and wrong and causes many many issues. 

**proposal**

- convert to a class
- remove dead code
- clean up utils/ helpers and figure out where is the best place for them. 
- write tests (without fixing every bug/ issue)

The reason I think a class makes sense here is for a few reasons:

- we can make it even more consistent with the python client
- the client is inherently stateful, classes make managing state nicer. 
- classes have some pretty strong separation for complex cases. Distinguishing local function/ block state vs instance state is much easier. Static/ private / instance fields and methods offer nice flexibility while giving us solid structure. 
- Classes can be extended. This will allow us to define things like a `fetch` method. When a consumer wants to bring their own fetch implementation (gradio wasm) they can extend the class and override the method. 

Thoughts?

**Comment by pngwn** [comment]
@hannahblair 

The usage I was talking about for gradio lite.

The class would look something like this:

```ts
class Client {
  constructor() {
    ...
  }
  
  fetch(...args) {
    return fetch(...args)
  }
  
  EventSource(...args) {
    return new EventSource(...args)
  }
}
```

Then `@gradio/lite` could do this:

```ts
import { Client } from '@gradio/client';

class WasmClient extends Client {
  fetch(...args) {
    return magical_wasm_fetch(...args)
  }

  EventSource(...args) {
    return magical_wasm_eventsource(...args)
  }
}
```

You can see this in principle in this stackblitz demo: https://stackblitz.com/edit/stackblitz-starters-v5f9oj?file=index.js

Createing an instance of the first prints its own `method_two` (`Base`) but the second (which extend the original and overwrites it) prints _its_ own `method_two` (`Two`), even though it is called from the original class that it extends.

So we can do the same for the above code, except with `fetch` and `EventSource`.

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/7646 🥳
