### ISSUE TITLE
gr. Model3D cannot be displayed

### ISSUE THREAD

**Issue by axjing** [gradio-app/gradio#7216]
### Describe the bug

The content is not displayed, and the following conditions occur:

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import os
def load_mesh(mesh_file_name):
    return mesh_file_name
demo = gr.Interface(
    fn=load_mesh,
    inputs=gr.Model3D(),
    outputs=gr.Model3D(
            clear_color=[0.0, 0.0, 0.0, 0.0],  label="3D Model"),
)
if __name__ == "__main__":
    demo.launch()
```

### Screenshot

![20240130175418](https://github.com/gradio-app/gradio/assets/34448205/1e7881ea-c550-4d5f-88d1-02ce72b8eb98)

### System Info

```shell
gradio                    4.15.0
gradio_client             0.8.1
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @axjing ! The file did not upload properly. Can you share any output from the browser console please? My guess is that there is an error being displayed there.

**Comment by axjing** [comment]
> Hi @axjing ! The file did not upload properly. Can you share any output from the browser console please? My guess is that there is an error being displayed there.

I found it unstable, open the computer today, run the program can be previewed, but if you change to another obj file, there will be a problem that it can't be displayed, but sometimes it can succeed. The browser's console error log is here
![Uploading 0240131093330.png…]()

**Comment by axjing** [comment]
> Hi @axjing ! The file did not upload properly. Can you share any output from the browser console please? My guess is that there is an error being displayed there.

I found it unstable, open the computer today, run the program can be previewed, but if you change to another obj file, there will be a problem that it can't be displayed, but sometimes it can succeed. The browser's console error log is here
![0240131093330](https://github.com/gradio-app/gradio/assets/34448205/980bcc5e-4b86-4786-8acc-97b2323c8689)

**Comment by abidlabs** [comment]
Is it a .nii file? That is not supported in the `Model3D` component. Supported formats are: (.obj, .glb, .stl, or .gltf)

**Comment by axjing** [comment]
> Is it a .nii file? That is not supported in the `Model3D` component. Supported formats are: (.obj, .glb, .stl, or .gltf)

I found the cause of the problem. It has something to do with what you said. My file suffix is ​​"xxx.nii.obj". If this doesn't work, just change it to xxx.obj. There can't be more than one in the middle when naming the file" .". Thank you, the problem has been solved
