### ISSUE TITLE
Image Streaming does not work

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#7223]
### Describe the bug

The stream_frames demo does not work locally or on spaces

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Check out the demo on spaces: https://huggingface.co/spaces/gradio/stream_frames

### Screenshot

<img width="1601" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/4627470a-ee1c-444b-8ecc-3ef644692f4a">

### Logs

```shell
No console or server logs. I think the event is just not being triggered.
```

### System Info

```shell
4.15.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
What I'm seeing is the status indicator getting in the way of viewing the output. Just to clarify @freddyaboulton are you seeing the same thing?

https://github.com/gradio-app/gradio/assets/1778297/73cd3cf0-2e67-417e-a459-623455c801d7

We fixed this issue before (cc @aliabid94) it seems like a regression indeed?

**Comment by freddyaboulton** [comment]
On chrome I'm seeing something different - it looks like the page is not even accessing my webcam but it's maybe because my permissions are messed up. On safari I see the same behavior as you.

<img width="1715" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/eaa6dcb2-cff2-420d-8519-2bdfed3ae637">

**Comment by freddyaboulton** [comment]
Actually, this is a duplicate of https://github.com/gradio-app/gradio/issues/7021 so I will close! Added the same labels to that issue for visibility
