### ISSUE TITLE
Running Gradio with Multiple Gunicorn Workers breaks gr.State() usage

### ISSUE THREAD

**Issue by asobh-ep** [gradio-app/gradio#7224]
### Describe the bug

I'm running Gradio inside of a FastAPI app run using Gunicorn with multiple Uvicorn workers and have some simple code to upload a pdf, then I split that into individual PNGs, and provide a viewer with a gr.State() handling which page I'm looking at.

- When I run this code with a single Uvicorn worker, it works fine. 
- When I use 2+ workers, it is clear that the gr.State() for the current page is sometimes getting pulled from one of the workers that did not do the initial processing. When this happens the gr.State() shows the initial value (i.e. it jumps back to page 1, and the pages I'm looking at don't show up). If I wait and keep clicking through my pages, sometimes I pick up the original worker and my state and pages start showing up again.

The reason for running the app this way is that I want multiple workers for my FastAPI app, in addition to running Gradio inside of it. I'm aware Gradio has some nifty stuff under the hood to handle its own multi-threading and such.

Side note:
A similar issue is also present if I use a single worker, but then deploy multiple pods in a kuberenetes cluster. There isn't a way to keep a certain session connected to a specific worker, so I start picking up varied states even though I'm still using gradio in a single browser.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Start command:
```
gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:3000 --access-logfile - --workers 2 --timeout 60
```

Calling gradio inside the fastapi app:
```
import gradio as gr
from gradio_landing import GradioLanding
app = gr.mount_gradio_app(app, GradioLanding, path="/main")
```

This is not verbatim code, but pretty close to what I'm running (much simplified for the sake of example):
```
with gr.Blocks(css=css) as GradioLanding:
    current_pg = gr.State(0)
    def browse_forward(i):
        if i != 10:
            i += 1
        return i+1, i
    def browse_backward(i):
            if i != 0:
                i -= 1
            return i+1, i
    text_box = gr.Textbox(1)
    previous_image.click(browse_backward, [current_pg], [text_box, current_pg])
    next_image.click(browse_forward, [current_pg], [text_box, current_pg])
```

### System Info

```shell
gradio==4.11.0
fastapi==0.109.0
gunicorn==21.2.0
uvicorn==0.23.2
```

### Severity

I can work around it

**Comment by savvaki** [comment]
@asobh-ep  I am also getting this issue. Have you perhaps found a way to work around this?

**Comment by freddyaboulton** [comment]
In the past, we've recommended to horizontally scale out gradio applications with nginx with sticky sessions. I guess you could have the fastapi app with multiple workers and then have a single gradio application running separately.
The fastapi app would then route the requests to gradio.

**Comment by abidlabs** [comment]
Will go ahead and close after @freddyaboulton's suggestion!
