### ISSUE TITLE
Output flickering in stream mode

### ISSUE THREAD

**Issue by qianhuiliu** [gradio-app/gradio#7230]
### Describe the bug

Hello,
I'm working on a streaming wake word detection demo. The model listens to speech and outputs the results for each new chunk. According to my following code, after getting the result of the chunk, the output text box will refresh and display the result (specific wake-up word or "deactivated"). Since our processing time is real-time, the text box refreshes very quickly causing constant flickering. I want the textbox to refresh when the wake word is detected. If the result is "deactivated", the textbox doesn't refresh.

Could someone help me please? Very appreciated.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import torch
import torchaudio 
import torchaudio.functional as F
from real_time_kws import wakeup_word

kws_gsc = wakeup_word()

def detection(stream, new_chunk):
    kws_gsc.reset_all()


    y, sr = torchaudio.load(new_chunk)

    result = kws_gsc.forward(y)
    if len(result)>0:
            txt = f'Activated: {result}.'
            return stream,txt
    return stream,"Deactivated."

inputs = [
    gr.Audio(sources="microphone", type="filepath", label='Input audio', streaming=True),
    gr.Radio(['wake-up word'], label='model')
]

outputs = gr.Textbox(placeholder="Results Here...",label="Detected word")

demo = gr.Interface(detection, 
                    ["state", gr.Audio(sources="microphone", type="filepath", label='Input audio', streaming=True)],
                    ["state", gr.Textbox(placeholder="Results Here...",label="Detected word")],
                    live=True
                    )
demo.launch()

```

### Screenshot

https://github.com/gradio-app/gradio/assets/34836415/ab711eff-ce8b-46a5-9dc4-50c4f1973350

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.7.1
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.2
huggingface-hub: 0.19.4
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.1
matplotlib: 3.8.1
numpy: 1.22.4
orjson: 3.9.10
packaging: 21.3
pandas: 2.1.0
pillow: 9.1.1
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.27.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.2
huggingface-hub: 0.19.4
packaging: 21.3
requests: 2.27.1
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @qianhuiliu. cc @freddyaboulton @aliabid94 I thought streaming inputs caused the output to not flicker, did we have a regression?

**Comment by qianhuiliu** [comment]
@abidlabs @freddyaboulton  Thank you very much for update. As in my application, the audio input need to be always-on, and the output is expected to be refresh based on the result. I wonder can this update #7228 satisfy my application?

**Comment by freddyaboulton** [comment]
#7228 will remove the output flicker so it should satisfy your application. No other changes to audio are being made.
