### ISSUE TITLE
Gallery Postprocessing Blocks the Demo

### ISSUE THREAD

**Issue by omerXfaruq** [gradio-app/gradio#7241]
### Describe the bug

When the function returns the list, gradio takes a very long time to render/postprocess the images. And meanwhile all other operations on other clients' actions are blocked (image upload, example tries).

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://huggingface.co/spaces/omerXfaruq/FindYourTwins

Use advanced section with max number of images and try to use the demo from another tab at the same time.

### Screenshot

Blocked image upload on other client:

![image](https://github.com/gradio-app/gradio/assets/44067394/b0f48079-41df-40e7-873a-8804e442ee6f)

### Logs

execution of the function takes 1 second, hence I'm sure that 20-30 seconds of blocking is caused by postprocessing.

Finished embedding: 1706744955.7943506
Finished fetching images: 1706744955.9093854
Finished creating list: 1706744956.575465

```shell
        async def find_similar_faces(image, count):
            inputs = extractor(images=image, return_tensors="pt")
            outputs = model(**inputs)
            embed = outputs.last_hidden_state[0][0]
            import time
            print(f"Finished embedding: {time.time()}")
            result = await index.query(
                vector=embed.tolist(), top_k=max(1, min(MAX_K, int(count)))
            )
            print(f"Finished fetching images: {time.time()}")
            images = [dataset["train"][int(vector.id)]["image"] for vector in result]
            print(f"Finished creating list: {time.time()}")
            return images
```

### System Info

```shell
gradio version: 4.16.0
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hey @omerXfaruq ! Are `extractor` and `model` coroutines? Since they come from transformers, I think they're normal functions that would block the event loop. I think you need to run those in a separate thread or rework the function so that it's not a coroutine.

I would test that out by duplicating your space but I don't have upstash api keys.

**Comment by omerXfaruq** [comment]
> Hey @omerXfaruq ! Are `extractor` and `model` coroutines? Since they come from transformers, I think they're normal functions that would block the event loop. I think you need to run those in a separate thread or rework the function so that it's not a coroutine.
> 
> I would test that out by duplicating your space but I don't have upstash api keys.

Hello,

The extractor and model don't take a long time, please check the timestamps I've shared in logs.

Hmm, for duplicating the space you can check this blog post on how to create an index.
But I think it's related to postprocessing.

**Comment by omerXfaruq** [comment]
the same thing happens with his example as well:
```
import gradio as gr

def get(image):
  return [image] * 100

gr.Interface(get, gr.Image(type="pil"), gr.Gallery()).launch()
```

**Comment by freddyaboulton** [comment]
Ah ok - thanks for explaining! The gallery postprocess has to save the PIL images to disk. We call the postprocess within a co-routine so if there are many images to save that could block the event loop.

**Comment by omerXfaruq** [comment]
hey @freddyaboulton!

is it possible to run it in-memory? or bypass writing to disk?

or run postprocess in the threadpool?

right now it's causing a full blocking on the demo and making UX terrible. can we find a easy-fast fix to it?
