### ISSUE TITLE
`gr.Image` (and other file-based components) should follow URL redirects

### ISSUE THREAD

**Issue by whitphx** [gradio-app/gradio#7247]
- [x] I have searched to see if a similar issue already exists.

`gr.Examples` can accept URLs as media file examples.
Redirects on these URLs should be followed.

For example, when the example refers to a file hosted on Hugging Face Hub as below,
HF Hub redirects the URL to the actual CDN URL, and currently Gradio doesn't follow it and the image file is not loaded into the examples properly.

Example:
```python
import gradio as gr


def fn(image):
    ...
    return image

demo = gr.Interface(
    fn=fn,
    inputs="image",
    outputs="image",
    examples=[
        ["https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/bread_small.png"],
    ],
)

demo.launch()
```

**Comment by abidlabs** [comment]
This is actually a problem with `gr.Image()` itself, not just examples. E.g. see

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Image("https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/bread_small.png")
    
demo.launch()
```
