### ISSUE TITLE
Not able to use Chatbot as a custom component template

### ISSUE THREAD

**Issue by hannahblair** [gradio-app/gradio#7255]
### Describe the bug

 Chatbot doesn't seem to work as a custom component template. 

<img width="760" alt="Screenshot 2024-02-01 at 11 26 56" src="https://github.com/gradio-app/gradio/assets/15165908/edd19407-111a-42e3-b8df-2886b4d1ebf3">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

n/a

### System Info

```shell
4.16.0
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
@hannahblair - can you post the contents of `window.__GRADIO__CC__` from the console as well as the full repro steps. Typically this error means that the component is not installed (or we weren't able to find it in your system). The contents of `__GRADIO__CC__` should help us figure out what's happening.
