### ISSUE TITLE
gr.ImageEditor brush drawing at wrong position with gr.Examples 

### ISSUE THREAD

**Issue by hrrbay** [gradio-app/gradio#7258]
### Describe the bug

When using gr.Examples to input images to ImageEditor, the brush draws at the wrong position for Layer 1. After drawing, the results snaps to a different (wrong) position with a different brush width. This seems to only happen when using more than one example. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
examples = ["https://www.vangoghmuseum.nl/asset/download/s0195V1962", "https://www.vangoghmuseum.nl/asset/download/s0195V1962"]

demo = gr.Blocks()
with demo:
    im_editor = gr.ImageEditor(
        sources=["upload"],
        brush=gr.Brush(colors=["#000000"]),
        label="Upload image and draw a mask",
        interactive=True)

    gr.Examples(examples, inputs=im_editor)
demo.launch()


```

### While drawing

![2024-02-01_12-43-09_screenshot](https://github.com/gradio-app/gradio/assets/30429644/983f0445-d24a-4e9d-b13d-131586641a7f)

### After releasing the mouse
![2024-02-01_12-43-13_screenshot](https://github.com/gradio-app/gradio/assets/30429644/f8b4f5a6-0cc0-4644-bdf5-37f5238c0e45)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.16.0
gradio_client version: 0.8.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.108.0
ffmpy: 0.3.1
gradio-client==0.8.1 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.2
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.3
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.4
pillow: 10.2.0
pydantic: 2.5.3
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
ruff: 0.1.15
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.25.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.26.0
huggingface-hub: 0.20.2
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3



```

**Note**: gradio_client and tomlkit *are installed* according to `pip list`

### Severity

Blocking usage of gradio

**Comment by exx8** [comment]
I might be facing the same issue:
[Screencast from 23-02-24 20:18:51.webm](https://github.com/gradio-app/gradio/assets/8540180/aad3c5d3-cbc9-4f2e-8d02-127c5ce14812)

**Comment by gibiee** [comment]
In `gradio==4.22.0`, I have a same problem.
