### ISSUE TITLE
Public link expires prematurely

### ISSUE THREAD

**Issue by soon-yau** [gradio-app/gradio#7267]
### Describe the bug

1. My server is in London, UK, and the public link was working reasonably well back in November/December 2023, lasting up to 3 days as expected. But now the link often break prematurely, sometimes within just a hour after launching. 
2. The other problem that may be related. My app runs some neural network  processing after clicking a button, and will return images into gallery. In around the same timeframe as (1), the gallery timeout showing error after less than 10 seconds. Before, the process could last for 30 seconds without throwing errors.

I don't think I have change any of gradio code or version, wonder if this might have to do with your server/network?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
block = gr.Blocks().queue()
with block:
    with gr.Row():
        gr.Markdown("Testing")
  
block.launch(server_name='0.0.0.0', share=True)
```

### System Info

```shell
gradio==3.38.1
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
@soon-yau can you use this pinned issue to comment on share link-related issues please? https://github.com/gradio-app/gradio/issues/3677 

We'll try to address them all together
