### ISSUE TITLE
ImageEditor Fail to work

### ISSUE THREAD

**Issue by zxczx** [gradio-app/gradio#7280]
### Describe the bug

ImageEditor 无法使用，展示不正常。今天刚刚出现，之前使用没问题。

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio as gr
import time

def sleep(im):
    time.sleep(5)
    return [im["background"], im["layers"][0], im["layers"][1], im["composite"]]

with gr.Blocks() as demo:
    im = gr.ImageEditor(
        type="pil",
        crop_size="1:1",
    )

    with gr.Group():
        with gr.Row():
            im_out_1 = gr.Image(type="pil")
            im_out_2 = gr.Image(type="pil")
            im_out_3 = gr.Image(type="pil")
            im_out_4 = gr.Image(type="pil")

    btn = gr.Button()
    im.change(sleep, outputs=[im_out_1, im_out_2, im_out_3, im_out_4], inputs=im)

if __name__ == "__main__":
    demo.launch()

### Screenshot

<img width="1271" alt="q" src="https://github.com/gradio-app/gradio/assets/19947823/2481f5dd-f525-4ae0-ac12-99b71907012e">

### System Info

```shell
4.16.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @zxczx can you please explain the issue in English to members of our team can understand?

**Comment by zxczx** [comment]
> 你好@zxczx您能用英语向我们团队成员解释一下这个问题吗？

<img width="1045" alt="企业微信截图_ffbf64a7-eab6-41a9-8cf2-9fb166144ece" src="https://github.com/gradio-app/gradio/assets/19947823/1ab475f0-7114-4692-9f34-39e5c6a0869d">

No toolbar is displayed, no image can be uploaded. This situation occurred on February 2, and it could be used normally before。

**Comment by zxczx** [comment]
> Hi @zxczx can you please explain the issue in English to members of our team can understand?

It's back to normal
