### ISSUE TITLE
Dataset fails to click after load

### ISSUE THREAD

**Issue by aka7774** [gradio-app/gradio#7282]
### Describe the bug

After updating dataset in fn outputs, old content is retrieved when clicking.
If there are too many or too few rows, an error occurs.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def select(c):
    return c[0] + ' selected.'

def load():
    return [['aaa'],['bbb'],['ccc']]

with gr.Blocks() as demo:
    title = gr.Markdown('# dataset fails to click after load')
    info = gr.Markdown()
    col = gr.Textbox()
    load_button = gr.Button(value='load another dataset')
    ds = gr.Dataset(components=[col], samples=[['xxx'],['yyy']])

    ds.click(
        fn=select,
        inputs=[ds],
        outputs=[info]
    )
    load_button.click(
        fn=load,
        outputs=[ds],
    )

demo.launch()
```

1. Click "load another dataset"
2. Click any Example

- aaa => xxx
- bbb => yyy
- ccc => ERROR

### System Info

```shell
gradio 4.16.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Related: https://github.com/gradio-app/gradio/issues/6807, https://github.com/gradio-app/gradio/issues/5042

**Comment by aka7774** [comment]
Not fixed in 4.22.0.
Maybe the cache needs to be updated, but I don't know how to implement it correctly.

**Comment by aka7774** [comment]
In my usage, the following code avoided the bug.

```python
def load():
    global ds
    ds.samples = [['aaa'],['bbb'],['ccc']]
    return ds.samples
```

**Comment by aka7774** [comment]
My pull request did not support multi-user.
I have no motivation to make my app multi-user compatible because it is preferable to have all users share the latest state of my app.
Please be careful if you refer to the above code.
