### ISSUE TITLE
[Blocks] `gr.Markdown` doesn't render markdown

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#729]
### Describe the bug

`gr.Markdown` only renders text, not markdown.

### Reproduction

```python
import gradio as gr

block = gr.Blocks()

with block:
    gr.Markdown("This text is normal")

    gr.Markdown("# This is not a header")

    gr.Markdown("""
    ## This is not a header
    """)

    gr.Markdown("""
    this isn't a [link](https://gradio.app)
    """)


block.launch()
```
<img width="253" alt="Screen Shot 2022-02-24 at 5 36 00 PM" src="https://user-images.githubusercontent.com/9021060/155534767-4df3e2c2-fa5b-4547-84a8-873f849c32c3.png">

### System Info

```shell
Using gradio v2.8.0b20
```

### Severity

annoyance

**Comment by abidlabs** [comment]
I experienced the same issue, it's not just you!

**Comment by Leumastai** [comment]
No response to this for a more than a year!!!
