### ISSUE TITLE
Login landing page Customization/expandability

### ISSUE THREAD

**Issue by Solomin0** [gradio-app/gradio#7291]
- [ X ] I have searched to see if a similar issue already exists.

Currently self hosting gradio user accounts and authentication. Our best option is to manually send them to a different page (potentially another gradio instance) to create a new account. Having some way to link to that page via a button or add some more customizability would be greatly appreciated. 

Currently you can tell the user the address to create a login but theres no way to embed a link in the auth_message as it doesnt render as html. You could have the user start on the account creation page but being able to have a single landing point on the login page would be ideal. 

There does not seem to be an elegant solution currently available in gradio to achieve this. 

Thanks for the hard work guys.

**Comment by abidlabs** [comment]
If the `auth_message` parameter supported Markdown/HTML, would this issue be resolved? If so, that's definitely doable.

**Comment by Solomin0** [comment]
> If the `auth_message` parameter supported Markdown/HTML, would this issue be resolved? If so, that's definitely doable.

Sounds good to me. Btw the current docs say auth message is HTML but it appears to just be a raw string not rendering anything. 
Thanks.

**Comment by abidlabs** [comment]
Yep this is actually a bug, but should be an easy fix

**Comment by dwipper** [comment]
@Solomin0 I built a login/account create/password reset flow using Gradio. It's part of my main app. I created the various "forms" under specific gr.Row()s, and then show and hide the rows depending on the user interactions. It has the advantage of being able to have consistent CSS styling with the rest of the app, and full control over error checking, field validation, etc.

![image](https://github.com/gradio-app/gradio/assets/140648761/7dd90de2-12df-41cc-8dd3-96f60abdb0d8)
![image](https://github.com/gradio-app/gradio/assets/140648761/f178de9d-3371-46e2-9ca4-7435ef299f1c)
![image](https://github.com/gradio-app/gradio/assets/140648761/dc0d9642-5607-48da-b155-8f9a6008da69)

**Comment by Solomin0** [comment]
> @Solomin0 I built a login/account create/password reset flow using Gradio. It's part of my main app. I created the various "forms" under specific gr.Row()s, and then show and hide the rows depending on the user interactions. It has the advantage of being able to have consistent CSS styling with the rest of the app, and full control over error checking, field validation, etc.
> 
> ![image](https://private-user-images.githubusercontent.com/140648761/302142520-7dd90de2-12df-41cc-8dd3-96f60abdb0d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTQ1ODAsIm5iZiI6MTcwODAxNDI4MCwicGF0aCI6Ii8xNDA2NDg3NjEvMzAyMTQyNTIwLTdkZDkwZGUyLTEyZGYtNDFjYy04ZGQzLTk2ZjYwYWJkYjBkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxNjI0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzRjNjIyN2IzZmVlNWMyNTRiMThkYzYwZTk1OWIyYjg4NzBhZTZkZjM2Y2Q3ZjFjYjhmZmU3MTdkNTJlNTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n--tTHJt_o7bewYhaMYugNXdc9ipBr5Il6qXvE0tRQg) ![image](https://private-user-images.githubusercontent.com/140648761/302142538-f178de9d-3371-46e2-9ca4-7435ef299f1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTQ1ODAsIm5iZiI6MTcwODAxNDI4MCwicGF0aCI6Ii8xNDA2NDg3NjEvMzAyMTQyNTM4LWYxNzhkZTlkLTMzNzEtNDZlMi05Y2E0LTc0MzVlZjI5OWYxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxNjI0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDZiM2MwZGNkODMyYjU3YzBmODFhYWUwNmMwNTAxZDc4NTdkOGM2NzIxMWNhN2U0YzllZjYxODgwN2IxMTQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XFVBZkv3c538tEyYPxLnVS1boFxyU5RTZ0a2WBlOXrg) ![image](https://private-user-images.githubusercontent.com/140648761/302142551-dc0d9642-5607-48da-b155-8f9a6008da69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTQ1ODAsIm5iZiI6MTcwODAxNDI4MCwicGF0aCI6Ii8xNDA2NDg3NjEvMzAyMTQyNTUxLWRjMGQ5NjQyLTU2MDctNDhkYS1iMTU1LThmOWE2MDA4ZGE2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxNjI0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWE2YTg3NmNlMGYwMjI1NjBjYTQ0YzhlZjMyMWY5N2M3NWM0NTczZWIzNDJmODkxMzkxZTVhMmNjNWEwZGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4-XtRR4Elg5SJGz58Ma89jDtIb2lOYfODTTnAfqnx00)

@dwipper  Would you be able to share any of the blocks code you used to make this? I can hook up the signals and sort it out but having a starting point of all that would help a lot.

**Comment by Solomin0** [comment]
@abidlabs  do you know would this approach still allow me to utilize gr.State values? because it is a "fake" login all hosted on the same page wouldnt all users be within the same session? If i were to do this within a seperate gradio app and make the login button point to my main I think that might work but I dont really know how I could pass the login info between web sessions like that. Advice for how to approach this would be appreciated.

**Comment by dwipper** [comment]
@Solomin0 I'll see if I can extract the structure of what I built. I haven't seen any problems with multiple users logging into the site and any sort of data/state overlap.  From what I can tell, each user has their own "instance" of the page (maybe not the correct technical term for that? @abidlabs ).

**Comment by ARusterholz-edu** [comment]
I'm having some trouble with a gradio HuggingFace space that uses the auth page to pass a username and API token from a third party service. 

How can I store each user's token and username in a dict that is tied to the user's login session? 

My first solution was using a form of request.username to get a unique session, but this seemed to only be working when the user was logged in to HF. I then tried to get the user's IP but it seems like gr.Request is not available at time of login, I was not able to pass (request : gr.Request) while in the authentication step. The login page would succesfully take the credentials but would never load the app, it would get stuck. 

I think I need to be using gr.State() with the token and username but the documentation on it's utilization has been a bit confusing. An example of using it to store log in details passed through the builtin Auth page would be a big help.
