### ISSUE TITLE
Antivirus software in Windows 11

### ISSUE THREAD

**Issue by Tejas9019** [gradio-app/gradio#7296]
### Describe the bug

Hello,
As i am facing problem with antivirus software. This many days my gradio app was working fine but today i gotta up an error of OSerror  when i went to this specific path i have not found frpc or which should i add to white list i upgraded gradio also...latest version is 4.16 what to do...

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### Screenshot

![Screenshot 2024-02-03 132009](https://github.com/gradio-app/gradio/assets/89508089/920cb323-1b92-4418-8659-6871d3773f2b)

### Logs

```shell
OSError: [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software: 'C:\\Users\\Astra Management\\AppData\\Roaming\\Python\\Python311\\site-packages\\gradio\\frpc_windows_amd64_v0.2'
```

### System Info

```shell
Gradio version -- 4.16
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @Tejas9019 !

Please see the workarounds in this issue https://github.com/gradio-app/gradio/issues/3677 and report back if they don't fix your problem. In the meantime I will close this.

**Comment by abidlabs** [comment]
Can you try installing `gradio` like this:

```py
pip install https://gradio-pypi-previews.s3.amazonaws.com/4814351d6866e31cdff70ebd87823e6fa10dcf2b/gradio-5.23.3-py3-none-any.whl
```

and see if it resolves the issue for you?
