### ISSUE TITLE
How can i change the items of dropdown By javascript

### ISSUE THREAD

**Issue by mengjiteam** [gradio-app/gradio#7297]
- [ ] I have searched to see if a similar issue already exists.
I want to select one item wich is exsit in my dropdown by javascript,but i don`t known how to do it. Please give me some demo,Thanks!!

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by abidlabs** [comment]
Hi @mengjiteam can you provide more context on what you're trying to do and what you've tried? Also, for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
