### ISSUE TITLE
[Custom Components]`gradio cc publish` run failed when the project name contains hyphens

### ISSUE THREAD

**Issue by Col0ring** [gradio-app/gradio#7306]
### Describe the bug

gradio 4.16.0 is not working, but 4.15.0 works.

maybe it's because of the following code in`cli/commands/compoents/publish.py`

![image](https://github.com/gradio-app/gradio/assets/47329987/6cf44539-1688-4c27-90b4-6eaf20623645)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

create a custom component project named `gradio-foo`, then run `gradio cc build`  and `gradio cc publish`.

### System Info

```shell
gradio 4.16.0
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Thank you @Col0ring ! This has been fixed by #7229 and will be released soon!
