### ISSUE TITLE
Support SQL in gr.Code

### ISSUE THREAD

**Issue by aersam** [gradio-app/gradio#7316]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I'd like gr.Code to support SQL.

**Describe the solution you'd like**  
Seems like the Code Editor is based on codemirror which does support SQL: https://github.com/gradio-app/gradio/blob/main/js/code/shared/language.ts https://www.npmjs.com/package/@codemirror/lang-sql

I could try doing a PR

**Additional context**

**Comment by freddyaboulton** [comment]
Hi @aersam ! Please open a PR for this. Would be happy to review!

**Comment by aersam** [comment]
> Hi @aersam ! Please open a PR for this. Would be happy to review!

PR is here, however some check fails, I'm not sure why
