### ISSUE TITLE
Share links are down

### ISSUE THREAD

**Issue by GhostlyScript** [gradio-app/gradio#7318]
### Describe the bug

No share links working in the last hour

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

To reproduce launch your app with share=True

### Screenshot

![sharelinkdown](https://github.com/gradio-app/gradio/assets/139256353/acf4de30-728e-4ed2-8156-753f69f41f46)

### System Info

```shell
All systems are affected.
```

### Severity

Blocking usage of gradio

**Comment by EasyMad82** [comment]
yes, confirmed also here,, do we have ETA for this issue ?
Thanks

**Comment by joker2663** [comment]
I think hugging Face should kick out their useless employees.

**Comment by joker2663** [comment]
Hugging face is going to shut down gradio share link permanently. it's better to look for alternative.

**Comment by gongouveia** [comment]
@joker2663 What is the source?

**Comment by gongouveia** [comment]
@joker2663 So, there is no Source....

**Comment by GhostlyScript** [comment]
Shared links now appear to be restored after being down for about 6 or 7 hours today.
