### ISSUE TITLE
[Blocks] Output has no loading feedback

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#732]
Currently while an event is processing there's no feedback to the user. I find myself often clicking the button again thinking I hadn't clicked it

https://user-images.githubusercontent.com/9021060/155542388-5f89cf4a-5c54-4aa0-a6d3-cb554c51443a.mov

We should add the loading gif from `Interface` somewhere

**Comment by abidlabs** [comment]
Strongly agreed. This would be helpful so it would (1) confirm that I have indeed clicked the button (2) the function is still running and hasn't timed out.

Some questions:

* I'm not sure where it should go? (Footer maybe, which we don't currently have in Blocks)
* Should it show the timer and/or queue status?

**Comment by FarukOzderim** [comment]
This should be high priority.

**Comment by FarukOzderim** [comment]
We could share feedback about steps of the pipeline or blocks as well. Just got a feedback like this from @osanseviero 
```
As a concrete example, let's imagine that your predict function calls pipeline A (translate), then pipeline B (summarize), and finally pipeline C (translate back). Instead of just the estimated duration, it would be interesting if developers could have some mechanism to say "Translating..." and then "Summarize...", etc
```

**Comment by pngwn** [comment]
Blocked until redesign is finalised. Will sync with Victor on this one.
