### ISSUE TITLE
Server Down

### ISSUE THREAD

**Issue by joker2663** [gradio-app/gradio#7321]
### Describe the bug

Gradio share Links down for more than 2 hours. it seems you gus have no idea about it until someone inform you. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

visit gradio.live

### Screenshot

no

### Logs

```shell
no
```

### System Info

```shell
no
```

### Severity

Blocking usage of gradio

**Comment by EasyMad82** [comment]
exactly... I pay a service for the hardware to run on.. two hours wasted now..

**Comment by freddyaboulton** [comment]
Hi all, I believe everything is working now. We will continue to monitor the situation.

<img width="1077" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/31b85358-9ca0-4eae-9d93-7f8c966bf82a">
