### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by hilaltekgozz** [gradio-app/gradio#7324]
### Describe the bug

out of no where the public url of my gradio app isn't reachable and there is a raised error 504 Gateway Time-out when trying to access it

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

gradio == 4.9.0

### Screenshot

<img width="980" alt="image" src="https://github.com/gradio-app/gradio/assets/144463019/8856de66-fd98-4341-b60d-d6a452a83be9">

### System Info

```shell
gradio environment
```

### Severity

I can work around it

**Comment by EasyMad82** [comment]
was reported few hours ago.. still waiting.. .

**Comment by GhostlyScript** [comment]
Yes this site says all shared links have been down for 4.5 hours now but no response from Gradio anywhere I can see: https://status.gradio.app/793595809

**Comment by joker2663** [comment]
Hugging face is going to shut down gradio share link permanently. it's better to move on to alternative.

**Comment by EasyMad82** [comment]
@abidlabs can you please have a look what going on with this ????? everyone is not able to run GRADIO since 6 hours now...

**Comment by gongouveia** [comment]
In an open issue, a gentelamn is saying that gradio is deactivating gradio share links... does anyone have any more info?
@abidlabs @EasyMad82 @GhostlyScript

**Comment by gongouveia** [comment]
Gradio share links is now operational 🤗 
@ALTdeveloper @EasyMad82 @hilaltekgozz

**Comment by freddyaboulton** [comment]
Hi all! We had an outage the last couple of hours but everything should be working now. We will continue to monitor the situation of course.

<img width="1077" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/d5c29569-91c6-4cb0-9194-38178cd5e618">

**Comment by alexeygridnev** [comment]
Just to let you know that I am facing this exact error as of right now (17 June 2024, 08:27 CET).

**Comment by alexeygridnev** [comment]
@nguyenhoanganh2002 no, I supposed we have to wait to get it fixed on Huggingface's side.

**Comment by PrayushiFaldu** [comment]
@alexeygridnev I am also facing the same issue.

**Comment by alexeygridnev** [comment]
Update: seems to be resolved now

**Comment by privet1mir** [comment]
@alexeygridnev still happening(

**Comment by inmnin** [comment]
@alexeygridnev still happening(

**Comment by Ayoub-fox** [comment]
@gongouveia the server is down now and I really need it for my app submission any news on when the setuation might be resolved ?

**Comment by MohamedAliRashad** [comment]
Gradio has been down for 2 hrs now
![Image](https://github.com/user-attachments/assets/484addcc-bb1e-49ef-9fb8-66d377b0e2a1)

**Comment by Zaidsk** [comment]
> Gradio has been down for 2 hrs now ![Image](https://github.com/user-attachments/assets/484addcc-bb1e-49ef-9fb8-66d377b0e2a1)

Thanks for the update.

**Comment by HaithemH** [comment]
504 Gateway Time-out
Again guys!

**Comment by abidlabs** [comment]
Should be fixed now!

**Comment by zhuzhugogo21** [comment]
504 Gateway Time-out again.
