### ISSUE TITLE
New streaming replace stuff breaks API  use of chatbots

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#7347]
### Describe the bug

Recently new feature to tell UI what to append/replace leaves API calls broken.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Standard API calls to chatbot now give (for 2nd+ responses only, which is also hassle since keeps varying):

```
[['replace', [], 'reponse']]
```

I'm not even sure the impact of how easy it is to use what is passed back.  is the response still all there?  Do I have to do some operations now to  consume the API result?

Is there a way to disable that for API calls?  I don't want to disable for UI, but it's the same chatbot object used for both UI and API.

### System Info

```shell
gradio 4.17.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Can you clarify how you're using this via API? Are you using the Clients?

**Comment by pseudotensor** [comment]
Sorry, will make repro.

**Comment by pseudotensor** [comment]
Having trouble reproducing in isolated case.  Yes, using client to talk to server, both are same gradio/client versions.  For some reason 2nd+ response always has that replace stuff.      I looked into code, and I see where it's supposed to be processed in utils.py, but client seems to be skipping it.

But with the asyn stuff hard to debug and I can't tell why external isolated cases don't do it.

**Comment by pseudotensor** [comment]
Ah, it's using sse_v1 instead of sse_v2  Then it never does that processing.

While the client starts with sse_v2, the endpoint specifically says its sse_v1 for the text box that I'm streaming out of.  Why is that?  And why would server communicate the diffs if client or endpoint cannot handle?

**Comment by pseudotensor** [comment]
Ok, user error on my part.  I'll close, but I think it's odd that sse_v1 is supported but won't work with the diff stuff, but if that's understood then all ok.

**Comment by abidlabs** [comment]
Yes sse_v1 is for apps running an older version of Gradio (which wouldn't diff the stream anyways)
