### ISSUE TITLE
Tool Tips for components

### ISSUE THREAD

**Issue by dwipper** [gradio-app/gradio#7351]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
While the info= param on the various components is helpful, if a lot of text explanation is need for the user, it would be great to be able to configure a tool tip on the component.

**Describe the solution you'd like**  
Have a tool_tip= param on the various components that would take text and/or HTML. If a tool tip is defined, an "i" icon would show up next to component label. Clicking on the icon would pop up a modal window with the content.

**Additional context**

**Comment by abidlabs** [comment]
Hi @dwipper thanks for the feature request. We've debated tooltips before and decided against including them in the core library, see here: https://github.com/gradio-app/gradio/issues/4278#issuecomment-1555908459

If you are inclined, you could create a custom component for this :)
