### ISSUE TITLE
[Blocks] Input/Output Component Limitation

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#736]
I would like to build a workflow where the output of a model is the input of another (two interfaces in series), but I can't pass `gr.outputs.<etc>` as an input to something (`submit.click(predict, inputs=gr.outputs.<etc>, outputs=predictions)`)

This is a major limitation. Flow I want is:
 
* User submits first input
* model returns first output 
* second model returns second output using first output as input 

Note that not all outputs can be inputs

**Comment by FarukOzderim** [comment]
This should be high priority, will look into this.

**Comment by FarukOzderim** [comment]
@aliabd can you share the example you are working on if it is easy to find?

I am trying to create an example for this and see the error we getç

**Comment by FarukOzderim** [comment]
It seems we need to edit output components for this to work, and it feels like it would be more efficient if we combine Inputs and Outputs to Components while we are at it?
WDYT? @aliabid94 @abidlabs @pngwn

**Comment by abidlabs** [comment]
Copying over from #680. The way it might look for the user:

```python
from gradio.blocks import *

def dropdown_values(val):
    if val < 50:
       return ["fail", "repeat"]
    else:
       return ["succeed", "repeat"]
  
def fn(val, action):
     return "Your score is {} and you decided to {}".format(val, action)


with Blocks() as block:

  s = Slider(0, 100)
  d = Dropdown([]) 
  t = Textbox()

  s.select(fn=dropdown_values, outputs=d)
  d.select(fn=fn, inputs=[s, d], outputs=t)

  block.launch()
```

Basically every component (e.g. the Dropdown) should be able to be treated as an input or output

**Comment by pngwn** [comment]
I've opened a new issue to cover the final example which is subtely, but significantly, different from the initial usecase. #807 addresses this one.
