### ISSUE TITLE
Support ply format in `gr.Model3D`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#7363]
- [x] I have searched to see if a similar issue already exists.

I think `.ply` is a widely used format for 3D models and it would be nice if it was possible to directly visualize `.ply` files in `gr.Model3D` without the need to convert the format using other libraries like `trimesh`.

**Comment by abidlabs** [comment]
We just added .ply support in https://github.com/gradio-app/gradio/pull/7406 (they are rendered as Gaussian splats) so I'll go ahead and close this issue (as based on [internal discussion](https://huggingface.slack.com/archives/C03JMRM52C9/p1707764459456419), it seems that the Gaussian splat use case is by far the more common one).
