### ISSUE TITLE
shortgpt error when running the code

### ISSUE THREAD

**Issue by Jinyoung3** [gradio-app/gradio#7364]
### Describe the bug

Traceback (most recent call last):
  File "/app/./runShortGPT.py", line 1, in <module>
    from gui.gui_gradio import ShortGptUI
  File "/app/gui/gui_gradio.py", line 1, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.11/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.11/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/usr/local/lib/python3.11/site-packages/gradio/components/annotated_image.py", line 8, in <module>
    from gradio_client.documentation import document, set_documentation_group
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation' (/usr/local/lib/python3.11/site-packages/gradio_client/documentation.py)

this is what I get and I do not know how to fix the issue

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
e
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @Jinyoung3 can you please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by Jinyoung3** [comment]
yea the code is here:  https://github.com/RayVentura/ShortGPT
you need to create a file called ".env" and put in your openai key and elevenlabs API key and when you run
docker build -t short_gpt_docker:latest . and then 
docker run -p 31415:31415 --env-file .env short_gpt_docker:latest
I get that error.

**Comment by abidlabs** [comment]
Ok so what happened is that we released a more recent version of `gradio_client` that is incompatible with your version of gradio. And this is using a really old version of `gradio` that we don't really support anymore.  

But I think you should be able to get it to work again by pinning the `gradio_client` to an older version. I've opened a PR here that should work I believe: https://github.com/RayVentura/ShortGPT/pull/129

**Comment by abidlabs** [comment]
Will close for now but don't hesitate to reach back out on this thread with any questions or issues.

**Comment by Jinyoung3** [comment]
wait so which version should I use? I don't know what a PR is

**Comment by Jinyoung3** [comment]
Traceback (most recent call last):
  File "/app/./runShortGPT.py", line 1, in <module>
    from gui.gui_gradio import ShortGptUI
  File "/app/gui/gui_gradio.py", line 3, in <module>
    from gui.content_automation_ui import GradioContentAutomationUI
  File "/app/gui/content_automation_ui.py", line 3, in <module>
    from gui.ui_tab_short_automation import ShortAutomationUI
  File "/app/gui/ui_tab_short_automation.py", line 6, in <module>
    from gui.asset_components import AssetComponentsUtils
  File "/app/gui/asset_components.py", line 8, in <module>
    from shortGPT.config.api_db import ApiKeyManager
  File "/app/shortGPT/config/__init__.py", line 1, in <module>
    from . import config
  File "/app/shortGPT/config/config.py", line 1, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml' this is what I get now

**Comment by abidlabs** [comment]
Sorry I meant you have to do this:

`pip install gradio_client==0.2.10`

And it looks like you need `yaml` as well so please do:

`pip install pyyaml`

**Comment by Jinyoung3** [comment]
So I keep what I have and just run the commands u told me to do?

**Comment by Jinyoung3** [comment]
also those didn't work. Do you think the error is coming from shortGPT?

**Comment by abidlabs** [comment]
Yes it seems that their requirements.txt file might be out of date. I’d recommend opening an issue on their repo

**Comment by Jinyoung3** [comment]
ffmpeg
ffmpeg-python
python-dotenv
gradio_client==0.2.10
gradio==3.38.0
openai==1.10.0
tiktoken
tinydb
tinymongo
proglog
yt-dlp
torch
torchaudio
### whisper timestamped 
whisper-timestamped
protobuf==3.20.3
pillow==9.0.0
moviepy==1.0.3
progress
questionary
edge-tts
TTS==0.22.0
 even after changing to this I get error do you know why?
