### ISSUE TITLE
httpx.InvalidURL: Invalid non-printable ASCII character in URL

### ISSUE THREAD

**Issue by YuryYakhno** [gradio-app/gradio#7370]
### Describe the bug

# Overview

When `Interface` object is created with `article` parameter set to some multiline text, this causes exception at the moment of object creation:
```text
Traceback (most recent call last):
  File "demo.py", line 102, in <module>
    gr_io = gr.Interface(
  File ".venv/lib/python3.10/site-packages/gradio/interface.py", line 300, in __init__
    article = utils.readme_to_html(article)
  File ".venv/lib/python3.10/site-packages/gradio/utils.py", line 292, in readme_to_html
    response = httpx.get(article, timeout=3)
  File ".venv/lib/python3.10/site-packages/httpx/_api.py", line 196, in get
    return request(
  File ".venv/lib/python3.10/site-packages/httpx/_api.py", line 104, in request
    return client.request(
  File ".venv/lib/python3.10/site-packages/httpx/_client.py", line 815, in request
    request = self.build_request(
  File ".venv/lib/python3.10/site-packages/httpx/_client.py", line 347, in build_request
    url = self._merge_url(url)
  File ".venv/lib/python3.10/site-packages/httpx/_client.py", line 377, in _merge_url
    merge_url = URL(url)
  File ".venv/lib/python3.10/site-packages/httpx/_urls.py", line 115, in __init__
    self._uri_reference = urlparse(url, **kwargs)
  File ".venv/lib/python3.10/site-packages/httpx/_urlparse.py", line 160, in urlparse
    raise InvalidURL("Invalid non-printable ASCII character in URL")
httpx.InvalidURL: Invalid non-printable ASCII character in URL
```

It looks like the same problem was mentioned in #6889.

# Possible Reason

1. New version of `httpx` package [does not support](https://github.com/encode/httpx/discussions/2676) ASCII non-printable characters in URL. `\n` in multiline text is also ASCII non-printable character.
1. It looks like code of [readme_to_html() function](https://github.com/gradio-app/gradio/blob/2244059cdbacb713530a3b760205c5464c05491c/gradio/utils.py#L290) uses `httpx.get()` function improperly - for link validation instead of sending `GET` request.

# Proposed Fix

Validate link with suitable package, like [validators](https://validators.readthedocs.io/en/latest/#module-validators.url), or with regular expression. If link is valid, then send `GET` request by `httpx`.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

gr_io = gr.Interface(
    fn=some_func(),
    inputs=[some_input],
    outputs=[some_output],
    description="# Description\n\nText",  # <= this works
    article="# Article\n\nText",  # <= this produces exception on creation
)
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.16.0
gradio_client version: 0.8.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.109.0
ffmpy: 0.3.1
gradio-client==0.8.1 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.3
importlib-resources: 6.1.1
jinja2: 3.1.3
markupsafe: 2.1.4
matplotlib: 3.8.2
numpy: 1.26.3
orjson: 3.9.12
packaging: 23.2
pandas: 2.2.0
pillow: 10.2.0
pydantic: 2.6.0
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
ruff: 0.1.14
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.27.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.26.0
huggingface-hub: 0.20.3
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Would you like to submit a PR to fix this @YuryYakhno ?

**Comment by YuryYakhno** [comment]
I will try to find time in the nearest days. Which solution would you prefer:
* add extra dependency on `validators` package, just because of [one function](https://validators.readthedocs.io/en/latest/#module-validators.url)
* use regular expression from `re` Python module, like, for example, [here](https://github.com/django/django/blob/stable/1.3.x/django/core/validators.py#L45)

**Comment by abidlabs** [comment]
Thanks @YuryYakhno I would suggest avoiding adding another dependency!
