### ISSUE TITLE
Setting Dropdown value to an updated (but valid) choice produces warning

### ISSUE THREAD

**Issue by DRomatzki** [gradio-app/gradio#7382]
### Describe the bug

# The bug is as follows
#A dropdown object is filled with a list
# a hidden Textbox is filled with a string variable of the first list item in the dropbox to carry over the variable. It is also filled if the dropdown selects another variable from the list. One could use a statev. I use a hidden textbox.
# When this process is reversed the warning message appears. Even converting the textbox. value to string does not help.
# A warning is given that the new string transferred from the textbox is not in the dropdown list
# "UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: Option 1 or set allow_custom_value=True."
#When printing out the type of the textbox and the dropdown, both are 'str'.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

# Define choices for the dropdown
my_choices = ["Option 1", "Option 2", "Option 3"]


def select_first_value(dummy_var):
  # This function sets the first value found in the sub_dirs Dropdown
  selected_dropdown=dummy_var
  #print("selected_sub_dir:", selected_sub_dir)
  return selected_dropdown 

def Update_variable_textbox(dropdown_list):
  # A dummy textbox is used to pass variables between events.
  # This function updates the dummy textbox. One can also use the State gradio option
  selected_list_item=dropdown_list
  return selected_list_item 

def update_Dropdown_choices():
  # This function updates the choices of a Dropdown object
  d2 = gr.Dropdown(my_choices)
  return d2

with gr.Blocks() as iface:
   
    # Create and populate Dropdown  
    dropdown_list = gr.Dropdown(label="list", choices=[],interactive=True)
    # Create dummy hidden textbox to transfer variables globally
    dummy_var=gr.Textbox(value="", visible=True)
    #button to start all
    my_btn=gr.Button(value="Start")

    my_btn.click(update_Dropdown_choices,None,dropdown_list)
    dummy_var.change(select_first_value,dummy_var,dropdown_list)

    # If a different value is selected update dummy textbox: sub_dirs_first_choice
    dropdown_list.change(Update_variable_textbox,dropdown_list,dummy_var)



iface.launch()

```

### Logs

```shell
NO Logs
```

### System Info

```shell
Linux mint 21.2, Visual Studio. Python 10, conda, 
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.16.0
gradio_client version: 0.8.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.109.0
ffmpy: 0.3.1
gradio-client==0.8.1 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.3
importlib-resources: 6.1.1
jinja2: 3.1.3
markupsafe: 2.1.4
matplotlib: 3.8.2
numpy: 1.26.3
orjson: 3.9.12
packaging: 23.2
pandas: 2.2.0
pillow: 10.2.0
pydantic: 2.5.3
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
ruff: 0.1.14
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.27.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.26.0
huggingface-hub: 0.20.3
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
I've been wracking my brains over this issue @DRomatzki. Providing a simpler repro as I continue to look into it:

```py
import gradio as gr

# Define choices for the dropdown
my_choices = ["Option 1", "Option 2", "Option 3"]


def update_dropdown_choices():
  d2 = gr.Dropdown(choices=my_choices)
  print(d2.choices)
  return d2

with gr.Blocks() as iface:
    dropdown = gr.Dropdown(label="list", choices=[], interactive=True)
    textbox = gr.Textbox(value="")

    textbox.submit(lambda x:x, textbox, dropdown)
    dropdown.change(lambda x:x, dropdown, textbox)

    iface.load(update_dropdown_choices, None, dropdown)


iface.launch()
```

**Comment by mirix** [comment]
Hey, I am finding this issue on gradio-5.5.0 and gradio-5.6.0.

This happens regardless of whether I set a value or not:

`UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include:`

With the original dropdown list, the first value on the list is chosen by default or any other value can be set as long as interactive=True.

However, when the dropdown list is dynamically updated, `dropdown.py:226` always gives the warning and no default value is selected.

**Comment by abidlabs** [comment]
@mirix if you are still seeing this issue in 5.6.0, please open a new issue with a minimal repro

**Comment by mirix** [comment]
OK, I have got it. I was calling a function that updated just the choices list. Now I realise I need to update the entire component. Thanks!
