### ISSUE TITLE
No module named 'pymongo'

### ISSUE THREAD

**Issue by deema-A** [gradio-app/gradio#7386]
### Describe the bug

I was trying to save the users' responses to a database. Got No module named 'pymongo'

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi
```

### System Info

```shell
Python 3.11.5
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @deema-A can you please share a bit more, what Gradio app are you trying to run?

**Comment by abidlabs** [comment]
Closing for lack of follow up -- can reopen if needed.
