### ISSUE TITLE
With gradio==4.18.0, only get loading screen for server for remote connections going through nginx

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#7391]
### Describe the bug

With gradio==4.18.0, only get loading screen for server for remote connections

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

No repro yet, but it works locally, but not when using nginx on remote server.

It happens each time I switch back and forth.  So something new broke nginx/proxy use in gradio 4.18.0.

For gradio 4.18.0, using non-ngnix name, just raw ip/port, works fine.  So definitely proxy issue that wasn't there in 4.17.0.

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/2249614/7f88162b-7c90-4fd4-ad96-a98906113a31)

### System Info

```shell
gradio==4.18.0 gradio_client=0.10.0


For exact same code, just switching back to gradio==4.17.0 gradio_client=0.9.0 and no issues.
```

### Severity

Blocking usage of gradio

**Comment by pseudotensor** [comment]
Plausible breaking changes: https://github.com/gradio-app/gradio/pull/7374  

FYI @abidlabs

**Comment by pseudotensor** [comment]
Related of course, but not same issue: https://github.com/gradio-app/gradio/issues/6920

Would be good if both related issues were fixed.  I'm back to gradio 3.50.2 again because of this particular regression.

**Comment by abidlabs** [comment]
Hmm yes it would be great if you could share a repro with the nginx config as well please @pseudotensor

**Comment by pseudotensor** [comment]
Dev console in bad 4.18.0 case:

```
index.js:1181 Mixed Content: The page at 'https://xxxx.ai/' was loaded over HTTPS, but requested an insecure resource 'http://xxxx.ai/info'. This request has been blocked; the content must be served over HTTPS.
view_api @ index.js:1181
config_success @ index.js:441
(anonymous) @ index.js:481
await in (anonymous) (async)
client2 @ index.js:403
(anonymous) @ Index.svelte:254
run @ svelte.js:41
(anonymous) @ svelte.js:3149
flush @ svelte.js:2108
init @ svelte.js:3266
Index @ Index.svelte:357
connectedCallback @ main.ts:109
await in connectedCallback (async)
create_custom_element @ main.ts:211
(anonymous) @ main.ts:214
index.js:443 Could not get api details: Failed to fetch
config_success @ index.js:443
await in config_success (async)
(anonymous) @ index.js:481
await in (anonymous) (async)
client2 @ index.js:403
(anonymous) @ Index.svelte:254
run @ svelte.js:41
(anonymous) @ svelte.js:3149
flush @ svelte.js:2108
init @ svelte.js:3266
Index @ Index.svelte:357
connectedCallback @ main.ts:109
await in connectedCallback (async)
create_custom_element @ main.ts:211
(anonymous) @ main.ts:214
css.ts:18 Mixed Content: The page at 'https://xxxx.ai/' was loaded over HTTPS, but requested an insecure stylesheet 'http://xxxx.ai/theme.css'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ css.ts:18
mount_css @ css.ts:12
mount_custom_css @ Index.svelte:139
(anonymous) @ Index.svelte:267
await in (anonymous) (async)
run @ svelte.js:41
(anonymous) @ svelte.js:3149
flush @ svelte.js:2108
init @ svelte.js:3266
Index @ Index.svelte:357
connectedCallback @ main.ts:109
await in connectedCallback (async)
create_custom_element @ main.ts:211
(anonymous) @ main.ts:214
css.ts:15 Unable to preload CSS for http://xxxx.ai/theme.css
(anonymous) @ css.ts:15
error (async)
(anonymous) @ css.ts:14
mount_css @ css.ts:12
mount_custom_css @ Index.svelte:139
(anonymous) @ Index.svelte:267
await in (anonymous) (async)
run @ svelte.js:41
(anonymous) @ svelte.js:3149
flush @ svelte.js:2108
init @ svelte.js:3266
Index @ Index.svelte:357
connectedCallback @ main.ts:109
await in connectedCallback (async)
create_custom_element @ main.ts:211
(anonymous) @ main.ts:214
Toast.svelte:8 TypeError: ((intermediate value) || (intermediate value)) is not a function
    at load_component (Toast.svelte:8:27)
    at Blocks.svelte:284:15
    at Array.forEach (<anonymous>)
    at prepare_components (Blocks.svelte:228:14)
    at $$self.$$.update (Blocks.svelte:157:25)
    at init (svelte.js:3246:5)
    at new Blocks (Blocks.svelte:707:31)
    at Array.create_if_block_1 (Index.svelte:425:26)
    at Object.p (Index.svelte:373:102)
    at update_slot_base (svelte.js:203:8)
load_component @ Toast.svelte:8
(anonymous) @ Blocks.svelte:284
prepare_components @ Blocks.svelte:228
$$self.$$.update @ Blocks.svelte:157
init @ svelte.js:3246
Blocks @ Blocks.svelte:707
create_if_block_1 @ Index.svelte:425
p @ Index.svelte:373
update_slot_base @ svelte.js:203
p @ Embed.svelte:27
update @ svelte.js:2128
flush @ svelte.js:2088
Promise.then (async)
schedule_update @ svelte.js:2029
make_dirty @ svelte.js:3183
(anonymous) @ svelte.js:3241
get_blocks @ Index.svelte:308
await in get_blocks (async)
load_demo @ Index.svelte:317
$$self.$$.update @ Index.svelte:303
update @ svelte.js:2124
flush @ svelte.js:2088
Promise.then (async)
schedule_update @ svelte.js:2029
make_dirty @ svelte.js:3183
(anonymous) @ svelte.js:3241
(anonymous) @ Index.svelte:254
await in (anonymous) (async)
run @ svelte.js:41
(anonymous) @ svelte.js:3149
flush @ svelte.js:2108
init @ svelte.js:3266
Index @ Index.svelte:357
connectedCallback @ main.ts:109
await in connectedCallback (async)
create_custom_element @ main.ts:211
(anonymous) @ main.ts:214
Toast.svelte:8 Mixed Content: The page at 'https://xxxx.ai/' was loaded over HTTPS, but requested an insecure stylesheet 'http://xxxx.ai/custom_component/9c14b63825390c62b904cb0c1cded6bf/component/style.css'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ Toast.svelte:8
load_css @ Toast.svelte:8
load_component @ Toast.svelte:8
(anonymous) @ Blocks.svelte:284
prepare_components @ Blocks.svelte:228
$$self.$$.update @ Blocks.svelte:157
init @ svelte.js:3246
Blocks @ Blocks.svelte:707
create_if_block_1 @ Index.svelte:425
p @ Index.svelte:373
update_slot_base @ svelte.js:203
p @ Embed.svelte:27
update @ svelte.js:2128
flush @ svelte.js:2088
Promise.then (async)
schedule_update @ svelte.js:2029
make_dirty @ svelte.js:3183
(anonymous) @ svelte.js:3241
get_blocks @ Index.svelte:308
await in get_blocks (async)
load_demo @ Index.svelte:317
$$self.$$.update @ Index.svelte:303
update @ svelte.js:2124
flush @ svelte.js:2088
Promise.then (async)
schedule_update @ svelte.js:2029
make_dirty @ svelte.js:3183
(anonymous) @ svelte.js:3241
(anonymous) @ Index.svelte:254
await in (anonymous) (async)
run @ svelte.js:41
(anonymous) @ svelte.js:3149
flush @ svelte.js:2108
init @ svelte.js:3266
Index @ Index.svelte:357
connectedCallback @ main.ts:109
await in connectedCallback (async)
create_custom_element @ main.ts:211
(anonymous) @ main.ts:214
Toast.svelte:8 failed to load: pdf
load_component @ Toast.svelte:8
await in load_component (async)
(anonymous) @ Blocks.svelte:284
prepare_components @ Blocks.svelte:228
$$self.$$.update @ Blocks.svelte:157
init @ svelte.js:3246
Blocks @ Blocks.svelte:707
create_if_block_1 @ Index.svelte:425
p @ Index.svelte:373
update_slot_base @ svelte.js:203
p @ Embed.svelte:27
update @ svelte.js:2128
flush @ svelte.js:2088
Promise.then (async)
schedule_update @ svelte.js:2029
make_dirty @ svelte.js:3183
(anonymous) @ svelte.js:3241
get_blocks @ Index.svelte:308
await in get_blocks (async)
load_demo @ Index.svelte:317
$$self.$$.update @ Index.svelte:303
update @ svelte.js:2124
flush @ svelte.js:2088
Promise.then (async)
schedule_update @ svelte.js:2029
make_dirty @ svelte.js:3183
(anonymous) @ svelte.js:3241
(anonymous) @ Index.svelte:254
await in (anonymous) (async)
run @ svelte.js:41
(anonymous) @ svelte.js:3149
flush @ svelte.js:2108
init @ svelte.js:3266
Index @ Index.svelte:357
connectedCallback @ main.ts:109
await in connectedCallback (async)
create_custom_element @ main.ts:211
(anonymous) @ main.ts:214
Toast.svelte:8 undefined
load_component @ Toast.svelte:8
await in load_component (async)
(anonymous) @ Blocks.svelte:284
prepare_components @ Blocks.svelte:228
$$self.$$.update @ Blocks.svelte:157
init @ svelte.js:3246
Blocks @ Blocks.svelte:707
create_if_block_1 @ Index.svelte:425
p @ Index.svelte:373
update_slot_base @ svelte.js:203
p @ Embed.svelte:27
update @ svelte.js:2128
flush @ svelte.js:2088
Promise.then (async)
schedule_update @ svelte.js:2029
make_dirty @ svelte.js:3183
(anonymous) @ svelte.js:3241
get_blocks @ Index.svelte:308
await in get_blocks (async)
load_demo @ Index.svelte:317
$$self.$$.update @ Index.svelte:303
update @ svelte.js:2124
flush @ svelte.js:2088
Promise.then (async)
schedule_update @ svelte.js:2029
make_dirty @ svelte.js:3183
(anonymous) @ svelte.js:3241
(anonymous) @ Index.svelte:254
await in (anonymous) (async)
run @ svelte.js:41
(anonymous) @ svelte.js:3149
flush @ svelte.js:2108
init @ svelte.js:3266
Index @ Index.svelte:357
connectedCallback @ main.ts:109
await in connectedCallback (async)
create_custom_element @ main.ts:211
(anonymous) @ main.ts:214
xxxx.ai/:1 Uncaught (in promise) undefined
```

I can't just share screenshot since it has private information.  So I've redacted the text above for DNS to xxxx.ai.

**Comment by abidlabs** [comment]
Ah interesting, I thought I fixed this issue. Can you possibly share the code for the Gradio app as well?

**Comment by pseudotensor** [comment]
I think any gradio app will do it, let me launch a trivial one.

**Comment by pseudotensor** [comment]
The full app I'm launching is h2oGPT.  This one doesn't behave the same, but still behaves badly:

```
File Edit Options Buffers Tools Python Help                                                                                                                                                                                                                          
import os
os.environ['GRADIO_SERVER_PORT'] = '14001'

import gradio as gr
import random
import time


with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.ClearButton([msg, chatbot])

    def respond(message, chat_history):
        bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
        chat_history.append((message, bot_message))
        time.sleep(2)
        return "", chat_history

    msg.submit(respond, [msg, chatbot], [msg, chatbot])

if __name__ == "__main__":
    demo.launch(share=False, server_name='0.0.0.0')
```

![image](https://github.com/gradio-app/gradio/assets/2249614/d6199f9d-3fcd-444e-9a04-7664c0415be0)


```
index.js:1181 Mixed Content: The page at 'https://xxxx.ai/' was loaded over HTTPS, but requested an insecure resource 'http://xxxx.ai/info'. This request has been blocked; the content must be served over HTTPS.
view_api @ index.js:1181
config_success @ index.js:441
(anonymous) @ index.js:481
await in (anonymous) (async)
client2 @ index.js:403
(anonymous) @ Index.svelte:254
run @ svelte.js:41
(anonymous) @ svelte.js:3149
flush @ svelte.js:2108
init @ svelte.js:3266
Index @ Index.svelte:357
connectedCallback @ main.ts:109
await in connectedCallback (async)
create_custom_element @ main.ts:211
(anonymous) @ main.ts:214
index.js:443 Could not get api details: Failed to fetch
config_success @ index.js:443
await in config_success (async)
(anonymous) @ index.js:481
await in (anonymous) (async)
client2 @ index.js:403
(anonymous) @ Index.svelte:254
run @ svelte.js:41
(anonymous) @ svelte.js:3149
flush @ svelte.js:2108
init @ svelte.js:3266
Index @ Index.svelte:357
connectedCallback @ main.ts:109
await in connectedCallback (async)
create_custom_element @ main.ts:211
(anonymous) @ main.ts:214
css.ts:18 Mixed Content: The page at 'https://xxxx.ai/' was loaded over HTTPS, but requested an insecure stylesheet 'http://xxxx.ai/theme.css'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ css.ts:18
mount_css @ css.ts:12
mount_custom_css @ Index.svelte:139
(anonymous) @ Index.svelte:267
await in (anonymous) (async)
run @ svelte.js:41
(anonymous) @ svelte.js:3149
flush @ svelte.js:2108
init @ svelte.js:3266
Index @ Index.svelte:357
connectedCallback @ main.ts:109
await in connectedCallback (async)
create_custom_element @ main.ts:211
(anonymous) @ main.ts:214
css.ts:15 Unable to preload CSS for http://xxxx.ai/theme.css
```

I can see if there's a specific extra thing in h2oGPT that makes it even worse.


Note that direct port access to that simple gradio app is still good like h2oGPT is good:

![image](https://github.com/gradio-app/gradio/assets/2249614/ef5cf76c-be9a-4f9c-8706-7015c3a96e5e)

Nothing appears in dev console for this direct port access.

**Comment by FurkanGozukara** [comment]
we also have issue with runpod proxy

css is being blocked

gradio==4.18.0
gradio_client==0.10.0

![image](https://github.com/gradio-app/gradio/assets/19240467/494621b2-c2b6-480d-bbdf-30b287575bbf)

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara are you open to sharing your runpod url if its a public url?

i am starting right now 1 sec

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara are you open to sharing your runpod url if its a public url?

here proxy : https://t9c8iyut3dt8yg-7861.proxy.runpod.net/
here gradio live : https://8bfe9f6fd4c28a4072.gradio.live/

**Comment by FurkanGozukara** [comment]
@abidlabs 
here proxy : https://t9c8iyut3dt8yg-7861.proxy.runpod.net/
here gradio live : https://8bfe9f6fd4c28a4072.gradio.live/

**Comment by pseudotensor** [comment]
@abidlabs We setup a nginx case for you as well.  The config is:

```
server {
    listen 13001;
    server_name gpt-gradio.h2o.ai;

    location / {
        proxy_pass http://52.0.25.199:14051/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_http_version 1.1;
    }
}
```

Raw system is at: http://52.0.25.199:14051/
proxy DNS is https://gpt-gradio.h2o.ai/

Raw shows:

![image](https://github.com/gradio-app/gradio/assets/2249614/cba3d32b-b942-40e9-9cfb-114443b603a0)

![image](https://github.com/gradio-app/gradio/assets/2249614/a5a20b66-56e7-4486-b6e7-28dc11cbb310)

**Comment by abidlabs** [comment]
Thank you @pseudotensor and @FurkanGozukara! Looking into this

**Comment by abidlabs** [comment]
I think I know the problem, setting up my own nginx server to test

**Comment by abidlabs** [comment]
@pseudotensor it looks like the site is down, would you be able to restart please?

**Comment by pseudotensor** [comment]
It's back, thanks!

**Comment by FurkanGozukara** [comment]
> @pseudotensor it looks like the site is down, would you be able to restart please?

I left it open like 1 day yesterday :/ it burns money on runpod haha

if you are here reply me i will open again

**Comment by abidlabs** [comment]
Nw @FurkanGozukara I'm working off of the logs from @pseudotensor's for now. I'll open a PR for you guys to try soon

**Comment by abidlabs** [comment]
@FurkanGozukara @pseudotensor could you please try installing this version of `gradio` and seeing if it resolves the issue?

pip install https://gradio-builds.s3.amazonaws.com/9b8810ff9af4d9a50032752af09cefcf2ef7a7ac/gradio-4.18.0-py3-none-any.whl

**Comment by pseudotensor** [comment]
Yup, that works!

![image](https://github.com/gradio-app/gradio/assets/2249614/cc7b732a-772a-4dfe-9d19-0e53d417eec3)


I can try full h2oGPT app too.

**Comment by abidlabs** [comment]
That'd be great! Let me know if you see any issues

**Comment by pseudotensor** [comment]
Yup, seems all good now for 4.18.0 build that you shared.

![image](https://github.com/gradio-app/gradio/assets/2249614/c93f680e-3115-4c93-ae62-091d62ebc079)

**Comment by pseudotensor** [comment]
I played around with a few things and don't notice any issues.  So probably back to 4.17.0 behavior, thanks!

**Comment by abidlabs** [comment]
Amazing, thanks for confirming!

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara @pseudotensor could you please try installing this version of `gradio` and seeing if it resolves the issue?
> 
> ```
> pip install https://gradio-builds.s3.amazonaws.com/9b8810ff9af4d9a50032752af09cefcf2ef7a7ac/gradio-4.18.0-py3-none-any.whl
> ```

hello. I just tested and still same error for me :/

![image](https://github.com/gradio-app/gradio/assets/19240467/3b17996e-db80-47e0-bfea-9add182448b5)

**Comment by abidlabs** [comment]
Can you please try with `gradio==4.19.0` -- we just released

**Comment by FurkanGozukara** [comment]
> Can you please try with `gradio==4.19.0` -- we just released

hello i just tested same

here you can test running on rtx 4090 please let me know if you are available

https://eneoz4xloaxllz-7861.proxy.runpod.net/

**Comment by abidlabs** [comment]
The problem seems to be that the Runpod Proxy isn't passing along the headers properly. 

I see this request in the logs:

<img width="597" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/2b4120c7-1180-405a-a0d1-2c9058107d42">

So its trying to get the theme from "https://localhost:7860/". I can also confirm this by going to:

https://eneoz4xloaxllz-7861.proxy.runpod.net/config

and looking at the bottom most part of the dict, where it says that "root": "https://localhost:7860/"

So this tells me two things:

* The"x-forwarded-proto" header is being set correctly, since https is being used
* The "host" header is not being set, because it should reflect the public url instead of localhost

Do you know if its possible to configure the Runpod Proxy @FurkanGozukara? You'd want to set it up like this:

```
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
```

(if its nginx)

or 

```
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "http"
```

if its apache

**Comment by FurkanGozukara** [comment]
@abidlabs I will forward this to them. can i close pod now?

**Comment by FurkanGozukara** [comment]
> Yes sure thanks @FurkanGozukara!

hello again. they made the changes but still same error

here can you test?

https://eneoz4xloaxllz-3001.proxy.runpod.net/

**Comment by abidlabs** [comment]
The host header is still not being set correctly as far as I can tell. You can check by going to: https://eneoz4xloaxllz-3001.proxy.runpod.net/config and looking at the root. This is directly the `fastapi.request.url`, which should match the url of the page `https://eneoz4xloaxllz-3001.proxy.runpod.net`, not some IP address

**Comment by FurkanGozukara** [comment]
> The host header is still not being set correctly as far as I can tell. You can check by going to: https://eneoz4xloaxllz-3001.proxy.runpod.net/config and looking at the root. This is directly the `fastapi.request.url`, which should match the url of the page `https://eneoz4xloaxllz-3001.proxy.runpod.net`, not some IP address

thanks forwarding right now

**Comment by grumpyp** [comment]
I have similar issues working with privateGPT

https://github.com/imartinez/privateGPT/issues/1623

**Comment by pseudotensor** [comment]
@abidlabs Actually I still have issues with this.  gr.Audio playing gets stuck and doesn't play, and then never goes to stop/pause mode after clicking play.  However, this only happens for the indirect nginx DNS not the direct port.

So should re-open this issue.

**Comment by abidlabs** [comment]
Ok let me reopen so that we can figure this out -- so the only issues you are seeing are with `gr.Audio` @pseudotensor?

**Comment by abidlabs** [comment]
Oh noticed that you opened a separate issue with more details -- will close this

**Comment by pseudotensor** [comment]
Ya sorry, related to this issue, ok to only look at new one, but I guess seems systemic problem.
