### ISSUE TITLE
[Blocks] Support dark mode in the browser

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#741]
Blocks currently doesn't support dark mode, as can be seen by Space: https://huggingface.co/spaces/chinhon/multilingual_headline_writer

(screenshot below)

![image](https://user-images.githubusercontent.com/1778297/155834531-f5bf2fe1-a98a-4062-96d3-628b2e2361b3.png)

**Comment by pngwn** [comment]
adding from #1041 :

- [ ] Use css variables for theming
- [ ] Each theme should work in light and dark?

**Comment by gary149** [comment]
> * s variables for theming
> * [ ]  Each theme should work in light and dark?

Yes I think that makes sense.

**Comment by BramVanroy** [comment]
@abidlabs  Has this been fixed? I still see many illegible text due to dark text + dark background in [HF spaces](https://huggingface.co/spaces/evaluate-metric/chrf).

![image](https://user-images.githubusercontent.com/2779410/218997469-f5aa42f1-f764-4923-ac56-e0aaa61d26cc.png)

**Comment by abidlabs** [comment]
Yes, the Gradio version in the Space is very old (3.0.2) -- it just needs to be updated: https://huggingface.co/spaces/evaluate-metric/chrf/blob/main/README.md

**Comment by gitgithan** [comment]
Does blocks support dark themes currently?

I see from https://twitter.com/abidlabs/status/1444105826558414850?lang=en interface has many themes but 
```
import gradio as gr


with gr.Blocks(theme='darkdefault') as demo:
    with gr.Row():
        with gr.Column():
            gr.Textbox('one')
            gr.Textbox('two')
    
demo.launch()
``` 
doesn't seem to do anything.

I'm looking for an easy way to force the dark theme for users on system level light mode

**Comment by pngwn** [comment]
We recommend against it but you could add a `.dark` class to the gradio-container which should be easily targetable with js. This will enable dark mode.

**Comment by pngwn** [comment]
We won't be adding official APIs for this because it isn't something we want to encourage.

**Comment by pngwn** [comment]
But to clarify, dark and light mode are not separate themes. They are contained within a single theme and switch depending on user preferences.

**Comment by davies-w** [comment]
I just don't understand how to make this Dark by default?

**Comment by freddyaboulton** [comment]
Hi @davies-w - we don't recommend enabling dark mode by default (accessibility reasons).

But the code snipper shared by @gitgithan or this [suggestion](https://github.com/gradio-app/gradio/issues/741#issuecomment-1445439241)  by @pngwn should work.

**Comment by davies-w** [comment]
funnily enough I really dislike dark-modes (despite growing up on VT-100s), but for the chatbot app I had, dark looks way better than light (at least to me). Someone on Discord helped me out - the issue was the standard monkey patching example didn't work with ChatInterface, but someone figured it out.

**Comment by FurkanGozukara** [comment]
how do we enable dark theme i can't find

there are demos but no source code
