### ISSUE TITLE
Lazy cache examples

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#7424]
Instead of caching the examples before the Gradio app is launched, there should be a way to lazily cache the examples, i.e. cache them when after they are first processed. This has several advantages, as @apolinario pointed out:

* App becomes instantly available
* Would cut the startup time of Spaces with cache, as caching examples is the thing that takes the most time in startup of Spaces
* With ZeroGPU, when a GPU isn’t available, it errors out while caching examples

We can make this another option for the `cache_examples` parameter (the string "lazy") and maybe make this the default behavior on Spaces. 

See also: [internal discussion](https://huggingface.slack.com/archives/C02QZLG8GMN/p1707843648515889)

cc @radames @cbensimon as well

**Comment by shubhamofbce** [comment]
@abidlabs I am interested in working on this, I saw the code and I need to make changes in the `Examples class in helpers.py`. I just can't understand what you mean by `cache them when after they are first processed`, like what is the meaning of processed here? I will be thankful if you can answer this or connect me with someone who can help me understand this.

**Comment by abidlabs** [comment]
> @abidlabs could you clarify cache them after they are first processed? Is it about caching only when examples are run by the user and not during the startup in lazy mode?

Yes exactly!
