### ISSUE TITLE
Allows to update intermidate input component

### ISSUE THREAD

**Issue by realliyifei** [gradio-app/gradio#7427]
I want to do a multi-staged input component. For example, I first let the user input the radio value, then change the choices of dropdown depending on the radio value, and finally generate the contents by the selected choices in the dropdown.

[Updating Component Configurations](https://www.gradio.app/guides/blocks-and-event-listeners#updating-component-configurations) seems to not work for the intermediate input component; it only works on output component.

```
def change_textbox(choice):
    return gr.Dropdown(label=f"Select a paper {choice}", choices=['test3', 'test4']) 
    
with gr.Blocks() as demo:
    radio = gr.Radio(
        ["short", "long", "none"], label="What kind of essay would you like to write?"
    )
    text = gr.Dropdown(label="Select a paper 1", choices=['test1', 'test2']) 
    radio.change(fn=change_textbox, inputs=radio, outputs=text)
```

**Comment by abidlabs** [comment]
Hi @realliyifei the problem was that the `gr.Dropdown` was not set to be interactive. You can fix that like this:

```py
def change_textbox(choice):
    return gr.Dropdown(label=f"Select a paper {choice}", choices=['test3', 'test4']) 
    
with gr.Blocks() as demo:
    radio = gr.Radio(
        ["short", "long", "none"], label="What kind of essay would you like to write?"
    )
    text = gr.Dropdown(label="Select a paper 1", choices=['test1', 'test2'], interactive=True) 
    radio.change(fn=change_textbox, inputs=radio, outputs=text)
    
demo.launch()
```
