### ISSUE TITLE
[Blocks] Add support for State

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#743]
We have a State component but I don't know how to use it in Blocks or if we have support for it. 

For example, if I want to build a chatbot in Blocks, here's an example without using state. However, this would not work if the model is sent to multiple people since the history variables are shared across users:

```python
import gradio as gr
import random

history1 = []
history2 = []

def chatbot1(text):
    history1.append((text, "Why?"))
    return history1

def chatbot2(text):
    history2.append((text, "I don't understand"))
    return history2

block = gr.Blocks()

with block:
    gr.Markdown("Talk to either of these chatbots:")
    
    with gr.Row():
        display1 = gr.outputs.Chatbot()
        display2 = gr.outputs.Chatbot()

    with gr.Row():
        text1 = gr.inputs.Textbox()
        text2 = gr.inputs.Textbox()

    with gr.Row():
        button1 = gr.Button(label="Chat")
        button2 = gr.Button(label="Chat")
    
    button1.click(chatbot1, text1, display1)
    button2.click(chatbot2, text2, display2)
        
block.launch()
```

**Comment by nateraw** [comment]
Also just came across this one when trying to add a tab for the [chatbot Guide](https://gradio.app/creating_a_chatbot/)

**Comment by FarukOzderim** [comment]
When I look into #590 I don't see `State `component being edited, it seems something is affecting `State`. 
@aliabid94 do you have any idea about what may be causing this?
