### ISSUE TITLE
The `Chatbot` output interface should support a color map argument (similar to `HighlightedText`)

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#744]
Among other things, this would be useful if you have multiple chatbots in one demo:

![image](https://user-images.githubusercontent.com/1778297/155837396-1c4ff526-7618-4aaa-b962-0a8c4f303a01.png)

**Comment by pngwn** [comment]
Do you mean it should support custom colors for user/ bot? The color map actually highlights certain pieces of text iirc, would we want that kind of functionality too?

**Comment by abidlabs** [comment]
Sorry my issue was quite abbreviated and unclear. I mean the former: different colors for the user / bot (with the current gold / white being the default)

**Comment by Hv2025426** [comment]
##fdgfdgfd
