### ISSUE TITLE
Use `uv` in our CI workflows to speed them up 

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#7442]
Just tested installing `gradio` in a fresh virtual environment:

`pip`: 30 seconds
`uv`: 8 seconds (note this is after `uv` itself has been installed via `pip` which took a few seconds)

See more: https://github.com/astral-sh/uv. `uv` already supports editable installs and local installs so it should work for our CI

tldr: We should replace `pip install` with `uv pip install` in our CI workflows.

**Comment by abidlabs** [comment]
See comments on PR^

**Comment by pngwn** [comment]
Adding a note for clarity: We are leaving this issue open for visibility but we don’t plan to do this work anytime soon and  PRs addressing it will likely be closed without merging until uv is a little more mature.
