### ISSUE TITLE
Persistent error messages (disappears before you read them) 

### ISSUE THREAD

**Issue by Tradunsky** [gradio-app/gradio#7445]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Right now, the error detail is displayed as a limited-in-time popup and disappears. This makes it difficult to understand what happened for long-running requests, as people keep the tab open and can return to it after a while to find out there was an error, but it is unclear what exactly the error was.
<img width="605" alt="image" src="https://github.com/gradio-app/gradio/assets/4522842/8968ec40-407f-44ba-a3f4-14d689aad8af">

**Describe the solution you'd like**  
Maybe a quick config of the error message to be shown forever?

using the `Interface` class is not straightforward to workaround this with a custom error dedicated Textbox.

**Additional context**

**Comment by kmulka-bloomberg** [comment]
I'd also like a message to be shown in the text areas in the case of an error.

**Comment by freddyaboulton** [comment]
Yes this is now possible if you set `duration=None` in the `gr.Error`, `gr.Info`, `gr.Warning` constructor!

**Comment by Tradunsky** [comment]
Thank you!
