### ISSUE TITLE
Upgrading 4.8.0 to 4.9.0 output images are too large

### ISSUE THREAD

**Issue by jhogsett** [gradio-app/gradio#7448]
### Describe the bug

When I switch from version 4.8.0 to 4.9.0 my output images no longer scale down to fit in the Image control but instead display at an uncomfortably large size.  

Edit: with 4.19.0 and `interactive=True` added to the output images, this is no longer a problem.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
"""I'm just loading a 288x512 pixel animated GIF into an output-only Image control, but it displays in the UI at 716x1273 pixlels
Per Chrome:
Rendered size:	716 × 1273 px
Rendered aspect ratio:	716∶1273
Intrinsic size:	288 × 512 px
Intrinsic aspect ratio:	9∶16
"""
preview_image702 = gr.Image(sources=["upload"], type="filepath",
                        label="Split Frame Preview", height=512, width=720)
```

### System Info

```shell
The same happens also with 4.19.0. I have checked versions and determined the change occurs with version 4.9.0.
```

### Severity

Can work around issue

**Comment by abidlabs** [comment]
Hi @jhogsett would you be able to share a link to the image you're trying?

**Comment by jhogsett** [comment]
@abidlabs 
> Hi @jhogsett would you be able to share a link to the image you're trying?

Here is an example one: 
![thumbnail 000-136](https://github.com/gradio-app/gradio/assets/825994/dc416178-a78e-48eb-bcf2-29783c592ba2)


This shows how the gif appears in the same codebase, with 4.8.0 at the top and 4.9.0 at the bottom:
![Screenshot 2024-02-16 111449](https://github.com/gradio-app/gradio/assets/825994/68b8c482-9a0a-4495-a9c4-4b5fb8d501b6)


Chrome shows these dimensions for them:

Rendered size:	716 × 510 px
Rendered aspect ratio:	358∶255
Intrinsic size:	288 × 512 px
Intrinsic aspect ratio:	9∶16

Rendered size:	716 × 1273 px
Rendered aspect ratio:	716∶1273
Intrinsic size:	288 × 512 px
Intrinsic aspect ratio:	9∶16


I've tried a few things to coerce the images to resize like in earlier versions but haven't come up with a way yet. I see the same issue in later versions too including 4.19.0.

Thanks!

**Comment by abidlabs** [comment]
Is it only with GIFs or other images as well?

**Comment by jhogsett** [comment]
> Is it only with GIFs or other images as well?

@abidlabs it happens also with PNG files. I have another Image instance on a different tab that displays PNG images and with the update they are blown up in the same way. It's particularly noticeable with portrait images. It is as if a "fit" isn't happening after the update.

**Comment by abidlabs** [comment]
Thanks @jhogsett could you please provide a minimal code example that we can use to reproduce the issue above?

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by modestasgrz** [comment]
The issue persists. The toolbar disappears after image is uploaded. This is ImageMask object. But the toolbar dissapears only when bigger scale image is uploaded. If the scale is more fitting into frame, then toolbar stays. I upload the video recording illustrating the issue.

Uploading Screen Recording 2024-11-09 at 11.29.09.mp4…

**Comment by modestasgrz** [comment]
https://github.com/user-attachments/assets/47462981-ada0-4d9d-b183-b8d63a374a6b
