### ISSUE TITLE
Dataframe Component examples are not working

### ISSUE THREAD

**Issue by amanturate** [gradio-app/gradio#745]
### Describe the bug

Examples paramter for Dataframe component is not showing up in the app. Even for tax calculator app in the docs page is not showing dataframe examples.

### Reproduction

https://colab.research.google.com/drive/1DV1J45I-pkbwPEh0e6xVOkPgtLaXn3Zx

### Screenshot

![image](https://user-images.githubusercontent.com/15848774/155851875-dc3312ce-6d5c-4c65-8c64-87663a554083.png)

### System Info

```shell
2.8.5
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Can confirm the issue, thanks for bringing it to our attention @amanturate! 

Is this something you can look into @dawoodkhan82?

**Comment by lvwerra** [comment]
Maybe this is related to this: Although the examples are displayed with the latest version it seems that clicking on an example does not fill the Dataframe (the other input components are updated). I get this behaviour with the Tax example as well. If this is an unrelated issue I can open a separate issue.

**Comment by abidlabs** [comment]
Can you speak to this @pngwn?

**Comment by pngwn** [comment]
Will look into it.

**Comment by lvwerra** [comment]
Here's another demo of that bug in case it helps: https://huggingface.co/spaces/lvwerra/metric_demo
