### ISSUE TITLE
Deactivate event listeners when Textbox contains an empty string

### ISSUE THREAD

**Issue by Onturenio** [gradio-app/gradio#7456]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I have a chatbot application where the user introduces text in a Textbox and sends it by pressing a Button. I want to avoid that the user is able to send empty strings to the chatbot.

**Describe the solution you'd like**  
I would like to be able to disable the event listener in the Button, or its interactivity, based on the emptiness of a Textbox, so the button is deactivated unless the user has introduced some text in the Textbox.

**Additional context**  
I have crafter a minimal example that _almost_ achieves the desired behaviour. It basically updates the Button based on the `input` listener of a Textbox. The problem is that in every letter the user inputs, the button keeps blinking, as it is being updated every time. Perhaps, I'd like to update the button just when the state of the Textbox goes from empty to non-empty, or perhaps to disable the event listener.

This is the closest I have gone to achieve the desired behaviour.

```python
import gradio as gr

def user(query, chat_history):
    chat_history.append([query, None])
    return "", chat_history

def bot(chat_history):
    chat_history[-1] = [chat_history[-1][0], "reply"]
    return chat_history

def active_button(btn_send, input_box):
    if input_box == "":
        return gr.Button(interactive=False)
    else:
        return gr.Button(interactive=True)

with gr.Blocks() as demo:
    with gr.Column():
        chatbot = gr.Chatbot()
        with gr.Row():
            input_box = gr.Textbox(
                scale=12,
                show_label=False,
                placeholder="Ask me something...",
                container=False,
                elem_classes="borde",
            )
            btn_send = gr.Button(
                scale=1,
                min_width=10,
                value="Send",
                variant="primary",
            )

    # update button after input from user
    input_box.input(
        active_button,
        [btn_send, input_box],
        [btn_send],
    )

    btn_send.click(
        user,
        [input_box, chatbot],
        [input_box, chatbot],
        queue=False,
    ).then(
        bot,
        [chatbot],
        [chatbot],
    )

demo.queue()
demo.launch()
```

**Comment by abidlabs** [comment]
Hi @Onturenio can you try this demo on the latest version of `gradio==4.19`? I think the behavior is exactly how you describe

**Comment by Onturenio** [comment]
It does work, thank you. But I'm not sure how it works now. I had `gradio==4.13`. I didn't see anything related to this in the changelog.

I'd like to understand a bit better how this works now because I have a very similar issue related to the event listener of the like buttons in chatbot leading to blinking chat messages when the function being called by the event returns the chat history without changes. But I guess I'll raise a different issue not to mess the discussion.

**Comment by abidlabs** [comment]
Hi @Onturenio thanks for the question. The change responsible is actually this PR: https://github.com/gradio-app/gradio/pull/7410

We used to disable output components while the function was pending, but we've now disabled that.

In terms of your other question, can you consider setting `show_progress="hidden"` in the chatbot related event
