### ISSUE TITLE
regression on gr.File, can't upload files from an iPhone anymore

### ISSUE THREAD

**Issue by ngaudemet** [gradio-app/gradio#7471]
### Describe the bug

thanks for the tremendous work on gradio !

in gradio 4.19.1 (probably since 4.18.0 file enhancement https://github.com/gradio-app/gradio/pull/7299), I can't upload files on iPhone anymore.

In gradio 4.17.0, I could upload from iPhone (in precising specific types). Now it doesn't work anymore

issue #4021 was similar but fixed 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

files = gr.File(
            label="load_file",
            file_count="multiple",
            file_types=[
                ".csv",
                ".txt",
                ".json",
                ".xlsx",
                ".docx",
                ".pdf",
                ".jpg",
                ".png",
                ".pptx",
            ],
            visible=True,
        )

### Screenshot

![IMG_9375](https://github.com/gradio-app/gradio/assets/126974970/9f5bf89c-69b6-47e3-8f9f-2599de3982ea)

### System Info

```shell
gradio==4.19.1
```

### Severity

I can work around it (in staying with 4.17.0)

**Comment by abidlabs** [comment]
cc @dawoodkhan82

**Comment by dawoodkhan82** [comment]
@ngaudemet seems like this is actually fixed on main. So should be working in the next release.
