### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'output'

### ISSUE THREAD

**Issue by Panda903** [gradio-app/gradio#7472]
### Describe the bug

AttributeError: module 'gradio' has no attribute 'output'

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

def recognize_digit(img):
    img = img.reshape(1, 28, 28)
    prediction = model.predict(img).tolist()[0]
    return {str(i): prediction[i] for i in range(10)}

label = gr.output.Label(num_top_classes=4)
interface = gr.Interface(
    fn=recognize_digit, 
    inputs='sketchpad', 
    outputs=label, 
    live=True,
    title='Digit Recognizer'
)

### System Info

```shell
Gradio version: 4.19.1
```

**Comment by KanataTsutsui** [comment]
It's a just version problem so please try this.
pip install gradio==3.50

**Comment by heisenberg3376** [comment]
You just have to remove '.output' part from 'gr,output.label'. This is changed in Newer Versions.
