### ISSUE TITLE
Could not create share link

### ISSUE THREAD

**Issue by pariskang** [gradio-app/gradio#7474]
### Describe the bug

I struggled to use gradio to show llm demo, but an error comes, can u help me to resolve it? Thanks.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

(chatglm) root@15-0-0-62:~/chatglm.cpp/examples# python3 web_demo.py -m ../baichuan13btcm0-ggml.bin
Running on local URL:  http://127.0.0.1:7861

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.19.1
gradio_client version: 0.10.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.109.2
ffmpy: 0.3.2
gradio-client==0.10.0 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.3
importlib-resources: 6.1.1
jinja2: 3.1.3
markupsafe: 2.1.4
matplotlib: 3.8.3
numpy: 1.26.3
orjson: 3.9.14
packaging: 23.2
pandas: 2.2.0
pillow: 10.2.0
pydantic: 2.6.1
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.2.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.27.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.26.0
huggingface-hub: 0.20.3
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @pariskang sorry that you are experiencing issues with the share links. We will investigate these issues around share links, but ask that you use this open issue so that we have all of the related threads in one issue: https://github.com/gradio-app/gradio/issues/3677

**Comment by almeida85** [comment]
Hello,
I am having the same problem. I've tried everything in #3498 (except [)](https://github.com/gradio-app/gradio/issues/3498#issuecomment-2269790303) but nothing seems to work.
Moreover, when I downloaded the file in the `opt/anaconda3/envs/ppi-affinity-server/lib/python3.13/site-packages/gradio/`, renamed it to `frpc_linux_amd64_v0.3`, and run the app, the file is deleted (weird).

Any help will be appreciated.

**Comment by abidlabs** [comment]
Most likely your antivirus is deleting it. Not sure what we can do here but we’ll look into it
