### ISSUE TITLE
Cancel events by returning None without updating the application

### ISSUE THREAD

**Issue by Onturenio** [gradio-app/gradio#7479]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I have an application where the events in some elements change the state of others. For instance when the text in a Textbox is empty the "send button" becomes inactive and viceversa. Or when the user likes a chatbot response, it replies with "Thanks". I have crafted a minimal example below that showcases both features.

But in many cases the event actually must not do anything. For instance, if the string is already non empty, the function to update the Textbox does not need to make it interactive over and over. Or If the user tries to like/dislike the automatic first interaction, the bot must ignore this trivial feedback. This is done in my application, **and as far as I know, this is the way to do it**, by updating the element and returning it as part of the output of the event function.

The problem is that gradio is not just "doing nothing". In some cases there is some weird blinking or similar artifacts when the update takes place. I already noted that in [this closed issue](https://github.com/gradio-app/gradio/issues/7456). But even if it does not produce any visible artifact, these trivial updates create many GET petitions under the hood that overload the server. You can see them by inspecting the application for instance with the developers tool in Chrome.

**Describe the solution you'd like**  
I think a possible solution to this would be to be able to cancel the event whatsoever. This could be communicated to the application by returning `None` in the element to be updated. If `None` is received, do not do anything to the element. This, I guess, would get rid of the visible artifacts but also the unwanted request under the hood.

Does this make sense?

**Additional context** 

This minimal application showcases the two problems with "trivial do-nothing events"

```python
import gradio as gr

def user(query, chat_history):
    chat_history.append([query, None])
    return "", chat_history

def bot(chat_history):
    chat_history[-1] = [chat_history[-1][0], "reply"]
    return chat_history

def active_button(btn_send, input_box):
    if input_box == "":
        return gr.Button(interactive=False)
    else:
        return gr.Button(interactive=True)

def vote(chat_history):
    if len(chat_history) > 1:
        chat_history.append([None, "Thank you!"])
    return chat_history

with gr.Blocks() as demo:
    with gr.Column():
        chatbot = gr.Chatbot(
            [[None, "Hello! How can I help you today?"]]
        )
        with gr.Row():
            input_box = gr.Textbox(
                scale=12,
                show_label=False,
                placeholder="Ask me something...",
                container=False,
                elem_classes="borde",
            )
            btn_send = gr.Button(
                scale=1,
                min_width=10,
                value="Send",
                variant="primary",
            )

    # update button after input from user
    input_box.input(
        active_button,
        [btn_send, input_box],
        [btn_send],
    )

    # send user input to chatbot
    btn_send.click(
        user,
        [input_box, chatbot],
        [input_box, chatbot],
        queue=False,
    ).then(
        bot,
        [chatbot],
        [chatbot],
    )

    # react to user feedback
    chatbot.like(
        vote,
        [chatbot],
        [chatbot],
    )

demo.queue()
demo.launch()
```

**Comment by abidlabs** [comment]
Hi @Onturenio great question. Returning `None` from a function already has a particular behavior, which is that the output components value is made empty. However, one can achieve what you're describing by simply returning the component itself. Furthermore, you can use `show_progress="hidden"` to avoid showing any UI changes during the event. 

Here's an example which illustrates the difference:

```py
import gradio as gr

with gr.Blocks() as demo:
    b1 = gr.Button("Set to None")
    b2 = gr.Button("Don't do anything")
    t = gr.Textbox(interactive=True)
    
    b1.click(lambda :None, None, t)
    b2.click(lambda :gr.Textbox(), None, t, show_progress="hidden")
    
demo.launch()
```

Is this essentially what you're describing? If so, I think we should document this explicitly in the Guides. But let us know if there's still a separate feature request.

**Comment by Onturenio** [comment]
Hi @abidlabs . Thanks for the reply. No, what I describe is not exactly what you propose.

The `show_progress="hidden"` flag does not fully work for the `Chatbot` class. If you try my example, when you click on the like buttons, the application shows for some time the dots that indicate that the interface is being updated. It is so fast that it is difficult to take a screenshot, but it is slow enough to be noticeable and an unpolished user experience.

But this is not really the main problem. The main problem is that regardless of the visible changes in the UI, every event creates under the hood petitions that overload the server. What I'd like is to have a mechanism to avoid such petitions whatsoever. I'd like to have a mechanism from within the function handling the event to behave as if the event had not been raised. In my example above, every time I type a character in the `Textbox` an event (and a corresponding server petition) is being raised. I'd like to be able to tell from the function "if the text is non empty, just do nothing. But returning the same object is not the same as doing nothing.

I wasn't aware of the behaviour of `None` when it is the output for a Gradio element. But the fact is that you can already get this by returning an empty string, or an empty list... What I propose would enrich the semantics of returning `None`.

**Comment by abidlabs** [comment]
Hi @Onturenio that actually isn't possible since we need to start running the function so that it can check "if the text is non empty, just do nothing". So since the function needs to start running, you'll see the UI flicker and the server event. There's a workaround for the UI flicker that I described on a similar issue here: https://github.com/gradio-app/gradio/issues/7494#issuecomment-1955461700

Please take a look and see if that helps. I don't think there's another solution so I'll close this issue, but happy to keep discussing if this does not work for you

**Comment by elismasilva** [comment]
@Onturenio i was facing a similar problem where i needed load a profile saved on .json file to fill values on interface, but on load when i dont have the Default.json file on folder i was getting error when the event try to update fields and i desired cancel this event on this situation. So what i did:

``` python
#encapsulate the event on a dict
event = {"fn": my_func : "inputs": inputs, "outputs": outputs}

#on app.load
app.load(**event if last_profile is not None else {})
```

So event is only triggered when i have file profile, and nothing happen in interface. For my scenario its works.
