### ISSUE TITLE
Document: how to display different content based on the login information

### ISSUE THREAD

**Issue by jason9777** [gradio-app/gradio#7481]
My gradio program has a dropdown component that needs to display different results based on the user's information. How do I implement this?

For example,

Login information: "Company no.1", this component shows: "[1.pt, 2.pt]"
Login information: "Company no.2", this component shows: "[3.pt, 4.pt]"

**Comment by abidlabs** [comment]
Hi @jason9777 you can do this by accessing the network request as described here: https://www.gradio.app/guides/sharing-your-app#accessing-the-network-request-directly

The `gr.Request` object contains an attribute `.username` which can be used to do different things in your function depending on the username. 

We don't have great docs on this, so I'll reframe this as a docs issue. cc @aliabd

**Comment by jason9777** [comment]
Yes, thanks for your reply, 
I can get the username through gr.Request.username.
The main thing I don't understand is how to display the Dropdown component differently for each user when they open the page.
Since it seems that the Dropdown component was given an initial list when the gradio program was launched, the Dropdown component will be the same when everyone opens the page, and there is no way to dynamically update the Dropdown content. The Dropdown content can only be updated using gr.update by selecting or clicking another component

**Comment by abidlabs** [comment]
Hi @jason9777 sure, you can use the `.load()` event on the `Blocks` object for this. Here's a quick example:

```py
import gradio as gr

def update_choices(request: gr.Request):
    return gr.Dropdown(choices=[f"Hi, {request.username}", f"Hello, {request.username}"])


with gr.Blocks() as demo:
    d = gr.Dropdown(interactive=True)
    demo.load(update_choices, None, d)

demo.launch(auth=("a", "b"))
```

**Comment by jason9777** [comment]
Hello, after I ran this simple example, an error occurred. The error message is as follows.

Running on local URL:  http://127.0.0.1:7860
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\web_test\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\ProgramData\anaconda3\envs\web_test\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "D:\ProgramData\anaconda3\envs\web_test\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "D:\ProgramData\anaconda3\envs\web_test\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  ……
  File "D:\ProgramData\anaconda3\envs\web_test\lib\site-packages\fastapi\encoders.py", line 148, in jsonable_encoder
    if isinstance(obj, classes_tuple):
  File "D:\ProgramData\anaconda3\envs\web_test\lib\abc.py", line 119, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison

**Comment by jason9777** [comment]
I think I have found the problem, and I can modify the code as follows to make it work.
```
import gradio as gr

def update_choices(request: gr.Request):
    return gr.update(choices=[f"Hi, {request.username}", f"Hello, {request.username}"])


with gr.Blocks() as demo:
    d = gr.Dropdown(interactive=True)
    demo.load(update_choices, None, [d])

demo.launch(auth=("a", "b"))
```
