### ISSUE TITLE
Reduce processed image display/downloading overhead

### ISSUE THREAD

**Issue by smikhai1** [gradio-app/gradio#7486]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
In the Gradio library, processed images are saved in the PNG format by default, as observed in the `save_img_array_to_cache` and `save_pil_to_cache` functions within `gradio.processing_utils` module. This behavior results in significantly larger file sizes compared to the JPEG format: specifically, for 4K images, the PNG files are approximately 10 times larger than their JPEG counterparts. This leads to increased download and displaying times for the front end, adding unnecessary overhead to the user experience.
 
**Describe the solution you'd like**  
To enhance flexibility and efficiency, it would be beneficial to allow users to select the file format for saving images in the Gradio cache. This could be implemented by introducing an additional parameter, such as format, to the constructors of all image-related components. 

As an example, in my application I manually modified the default behavior of the aforementioned functions to save images in JPEG format, which significantly improved the results' delivery time and saved extra 10 seconds
  
**Additional context**

**Comment by freddyaboulton** [comment]
Do you want to open a PR for this @smikhai1 ? I think we can add an `img_format` argument to gr.Image that controls the format the image is saved in when it's a numpy array or PIL image. cc @abidlabs

**Comment by abidlabs** [comment]
Agreed. The name of parameter could be just `format` since we're already working with the `gr.Image` component and to mirror the similar `format` parameter in `gr.Video`

**Comment by freddyaboulton** [comment]
We should preserve the file format used during upload if possible see #7657

**Comment by dfl** [comment]
I need my dang exif metadata please ;(
https://github.com/dfl/gradio/commit/5f2db34537f0938761129dbd403ff02a7c8ed204

**Comment by dfl** [comment]
apologies I wasn't able to run the test suite locally 🙇‍♂️
had a bunch of dependency issues on my mac

**Comment by freddyaboulton** [comment]
Hi @dfl ! Yea someone can get it over the finish line. Thanks for the PR again.
