### ISSUE TITLE
[enhancement]: Add `gr.Success()`

### ISSUE THREAD

**Issue by Paillat-dev** [gradio-app/gradio#7489]
For reference: #4319 

Add `gr.Success()` similar to `gr.Info()` and `gr.Warning()`. This could be useful for small success messages, ex. to state that a file upload was successful. I do not think that the answer given in #4319 is still pertinent given the continously growing and wider usage of gradio. Furthermore this does not *seem* like a complex change, nor a breaking one.

**Comment by freddyaboulton** [comment]
Thank you for filing @Paillat-dev ! As of gradio 5.0, you can now set a title for an `Info` message so you can set it to `Succes` if you'd like. Don't think we'd implement this class into gradio core.

**Comment by abidlabs** [comment]
Reopening in light of https://github.com/gradio-app/gradio/pull/10262, which does a nice implementation imo

**Comment by Paillat-dev** [comment]
yaaaaay 🎉
