### ISSUE TITLE
Changing the camera on Image or ImageEditor does not actually change anything

### ISSUE THREAD

**Issue by elockquence** [gradio-app/gradio#7493]
### Describe the bug

When using gr.Image or gr.ImageEditor elements, one has the option to input images with WebCam as the source. 
Once selected this mode, a camera icon appears with a selector on the right side. (first image) This selector allows one to select different cameras but the selector does not seem to change cams at all.  

I've checked It is not a problem of the browser by connecting different cams, trying in different devices (computer and android mobilephone) and playing with website permissions. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

1. Use a device with two or more cams. A smartphone with back and frontal cam will do.
2. Go directly to: [image_component_space](https://huggingface.co/spaces/gradio/image_component)

Or try the Image component on a gradio space yoursef:

```python
import gradio as gr

with gr.Blocks() as demo:
    gr.Image()

demo.launch()
```
3. Select the webcam icon and try to change the cam with the selector on the right-hand side of the camera icon that has just showed up. 

4. If I'm right, this will will not change among cam inputs. 

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/57753185/8dc8ee96-5770-4032-bf08-08b853e9b404)

![image](https://github.com/gradio-app/gradio/assets/57753185/137d2eaf-b3a6-4fe3-8547-6a1aa9d353e9)

### System Info

```shell
sdk: gradio
sdk_version: 4.18.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
@hannahblair would you be able to look into this?

**Comment by nitinss17** [comment]
Hello @pngwn any update on this fix?

We really need this feature to utilise the higher resolution back camera on Android phone from web browser. Request to look into it. Thank you

**Comment by elockquence** [comment]
Hi @nitinss17, I've managed to sort out the problem by injecting a js in the head html of gr.Blocks. By doing so, I've forced the default mode to be the back camera. I hope this helps you. 

This is: 

```python
(...) 
def js_to_prefere_the_back_camera_of_mobilephones():
    custom_html = """
    <script>
    const originalGetUserMedia = navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);
    
    navigator.mediaDevices.getUserMedia = (constraints) => {
      if (!constraints.video.facingMode) {
        constraints.video.facingMode = {ideal: "environment"};
      }
      return originalGetUserMedia(constraints);
    };
    </script>
    """
    return custom_html

(...)

with gr.Blocks(title=title, head=js_to_prefere_the_back_camera_of_mobilephones()) as demo_app:
    with gr.Column():
(...)
```

However, It is still not possible to change the camera. @hannahblair

**Comment by nitinss17** [comment]
Amazing! @elockquence 
your script works as hacky solution at least for now. 
Thanks bud
