### ISSUE TITLE
Access gr.Request with Blocks API

### ISSUE THREAD

**Issue by mrpep** [gradio-app/gradio#7496]
I'm trying to get the IP of users to put limits on usage. I found this functionality is available through the gr.Request class, but it seems the feature can only be used when using gr.Interface.

I would like to be able to access request metadata from gr.Blocks API.

**Comment by abidlabs** [comment]
Hi @mrpep I just confirmed that `gr.Request` works with `gr.Blocks` as well. Here's a quick example:

```py
import gradio as gr

def echo(text, request: gr.Request):
    if request:
        print("Request headers dictionary:", request.headers)
        print("IP address:", request.client.host)
        print("Query parameters:", dict(request.query_params))
    return text


with gr.Blocks() as demo:
    t1 = gr.Textbox()
    t2 = gr.Textbox()
    t1.submit(echo, t1, t2)

demo.launch()
```

Please confirm that you're on the latest veresion of `gradio` (4.19.1) and let us know more details if you're still running into issues.
