### ISSUE TITLE
Unable to transmit large image (>1 MB)

### ISSUE THREAD

**Issue by BhavanJ** [gradio-app/gradio#75]
Hi all,

First of all very nice work. I would like to mention that the image input component doesn't seem to allow one to transmit large images (> 1MB or so) to the machine running the demo. It simply displays in red, "error" at the top right of the image input on the web demo, and I don't get any data or messages on the machine hosting the demo. Can you please look into this?

Thanks,
Bhavan

**Comment by abidlabs** [comment]
Thanks @BhavanJ, your feedback helps a lot! To help us diagnose this, can you tell us whether this was through a public link (xxxx.gradio.app), or was this with `gradio` running locally?

**Comment by BhavanJ** [comment]
Thanks @abidlabs for getting back on this. It was through gradio running locally.

**Comment by BhavanJ** [comment]
Were you able to check on this?

**Comment by abidlabs** [comment]
Sorry for the delay, @aliabid94 is looking into it right. Ali, can you let us know what you found?

**Comment by aliabid94** [comment]
@BhavanJ I haven't been able to reproduce this, even with very large images. Can you confirm you are running the latest version of Gradio? If you can provide more information about the images that are failing, such as extension type or even a link to the image, and if you could provide the browser console error message, that would help us pursue the solution

**Comment by BhavanJ** [comment]
@aliabid94 Thanks for getting back. I figured out the issue, sorry it was not issue with Gradio. It was happening because, I was using nginx as a web server for load-balancing and nginx had a file size limit. I had to update that limit to fix the issue. Appreciate your help on this.
