### ISSUE TITLE
A Grid Output to Show a Grid of Images, etc.

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#750]
One request we've heard from the past is to easily show a grid of (e.g. 4 by 2) images.

These are often the outputs of a GAN or some other image synthesis algorithm.

Right now, we tell users to convert their images to PIL and then stack them together manually, which is a pain.

Could we define a `Grid` output component analogous to `Carousel` that makes this a lot easier?

**Comment by pngwn** [comment]
This feels related to #778.

If we can figure out how to spread the output of a fn across components, we could let the user decide how to display those components without layouting components perhaps: grid, list, row, etc.

**Comment by abidlabs** [comment]
The `Gallery` component achieves this since a grid of images is the use case I had in mind. Feel free to reopen @pngwn with more details if you have something else in mind.
