### ISSUE TITLE
Scrollbar component is disabled in gr.Files when "height" parameter is set

### ISSUE THREAD

**Issue by vernikouskaya** [gradio-app/gradio#7500]
Hi, I constantly update gradio, but since version 4.15 I used for the first time there is no scrollbar component appearing in gr.Files if the "height" parameter is set. This is my code line:
files_input = gr.Files(file_types=['image'], type='filepath', height=256, interactive=True)
I would really appreciate any help!

_Originally posted by @vernikouskaya in https://github.com/gradio-app/gradio/issues/5221#issuecomment-1954098253_

**Comment by dawoodkhan82** [comment]
@abidlabs yup, will take a look.

**Comment by vernikouskaya** [comment]
Thank you! It works now!

**Comment by park12sj** [comment]
@dawoodkhan82 
Hello, I think there is the same phenomenon in gallery component, can you check it?
