### ISSUE TITLE
setting gr.Brush property "colors" doesn't update color of the brush tool in gr.ImageEditor component

### ISSUE THREAD

**Issue by vernikouskaya** [gradio-app/gradio#7501]
### Describe the bug

Hi, I am using current version of gradio 4.19.1 and I am trying to change the opacity of the gr.Brush in gr.ImageEditor component. For that I use parameter "colors" and set the value to Hex red with opacity 50% "#FF000080". This works for updating the color in the color palette, however when using the brush tool on the image, the color of the painting remains the default one from the library. I would really appreciate any help!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```
image_editor = gr.ImageEditor(crop_size="1:1", sources='upload', show_download_button=True, brush=gr.Brush(colors=["#FF000080"]))

### Screenshot

![brush_issue](https://github.com/gradio-app/gradio/assets/60062956/4602ae2f-9e3c-4073-93d5-dc9abe5826ed)

### System Info

```shell
version 4.19.1
```

### Severity

I can work around it

**Comment by pngwn** [comment]
@vernikouskaya are you specifically wanting to change the opacity rather than the color?

Opacity is not currently supported when drawing but we do plan to add it.

There is an issue for this here: https://github.com/gradio-app/gradio/issues/5644

**Comment by vernikouskaya** [comment]
yes, I tried to change the opacity via #FF000080" color code, but in the meanwhile I already find a way how to change the opacity programmatically by setting the layer forth channel respectively

**Comment by pngwn** [comment]
I'll close this issue in favour of the other one. We will get to this soon.
