### ISSUE TITLE
gr.ImageEditor is constantly updating when value component is set programmatically

### ISSUE THREAD

**Issue by vernikouskaya** [gradio-app/gradio#7502]
### Describe the bug

Hi, I am trying to fill the gr.ImageEditor component programmatically with the following numpy arrays
```python
pictures = {
        "background": np.dstack((bg, bg, bg, image_bg)).astype(np.uint8),
        ["layers"][0]: [np.dstack((red_layer, mask_layer, mask_layer, red_opacity_layer))], # red + opacity = 0.5
        "composite": np.dstack((composite_0, composite_1, composite_1, image_bg)).astype(np.uint8)  # red
    }
```
within function ```predict_image(x)``` which get image as a numpy array and make prediction on it (obtaining segmentation mask ```y```). Then I perform some manipulations on both image and mask and try to fill the gr.ImageEditor value.
Then  on ``` image_editor.change()``` I want to save only mask layers when user performs some changes.
When I use ```time.sleep(5)```, the ImageEditor tries to update each 5 sec and display correct background image with the mask overlayed as layer on it. Sometimes I even can manage to draw or erase on the displayed layer within the next 5 sec before it starts again to display an original image (the updated image sometimes can be even saved within this 5 sec). But another time the time is just elapsing and image constantly is trying to load, however, without success. Without ```time.sleep(5)``` the performance is even worth.
Normally at some time I get an error message, that image file (layer or background) in TEMP directory cannot be identified.
Unfortunately I cannot work around this issue, it blocks my application. I would really appreciate any help!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import os
import cv2
import numpy as np
import tensorflow as tf
from keras.models import load_model
import time

def split_img(im, fname):
    time.sleep(5)
    abspath = os.path.abspath(__file__)
    dname = os.path.dirname(abspath)
    os.chdir(dname)

    image = np.zeros([256, 256])
    pics = np.dstack((image, image, image, image)).astype(np.uint8)
    for i in range(len(im["layers"])):
        pic_res = cv2.resize(im["layers"][i], (256, 256), interpolation=cv2.INTER_NEAREST)
        pics += pic_res
    im_to_save = cv2.cvtColor(pics, cv2.COLOR_BGR2GRAY)
    norm_image = cv2.normalize(im_to_save, None, alpha=0, beta=255, norm_type=cv2.NORM_MINMAX,
                               dtype=cv2.CV_32F)
    img_to_save = norm_image.astype(np.uint8)
    file_name = fname.rsplit('.png')[0] + '_predicted.png'
    cv2.imwrite(file_name, img_to_save)

def predict_image(x):
    abspath = os.path.abspath(__file__)
    dname = os.path.dirname(abspath)
    os.chdir(dname)
    section = []
    model = load_model('model.h5', compile=False)
    x = np.array(x)
    x_new = cv2.resize(x, (256, 256), interpolation=cv2.INTER_NEAREST)
    x_new_ = np.expand_dims(x_new, axis=2)
    x_test = np.expand_dims(x_new_, axis=0)

    x_test = x_test.astype('float32')
    x_test /= 255
    y_pred = model.predict(x_test)
    y_predict = np.argmax(y_pred, axis=3)
    y = np.squeeze(y_predict, axis=0)
    norm_image = cv2.normalize(y, None, alpha=0, beta=255, norm_type=cv2.NORM_MINMAX,
                  dtype=cv2.CV_32F)
    im_prediction_scaled = norm_image.astype(np.uint8)
    norm_image_gray = cv2.normalize(y, None, alpha=0, beta=127, norm_type=cv2.NORM_MINMAX,
                               dtype=cv2.CV_32F)
    im_prediction_scaled_gray = norm_image_gray.astype(np.uint8)

    section.append((y, 'tongue'))
    image=np.empty([256,256])
    mask = np.zeros([256, 256]).astype(np.uint8)
    image.fill(255)

    #resize pictures 2 times
    bg = cv2.resize(x_new, (512, 512), interpolation=cv2.INTER_NEAREST)
    image_bg = cv2.resize(image, (512, 512), interpolation=cv2.INTER_NEAREST)
    mask_layer = np.zeros([512, 512]).astype(np.uint8)
    red_layer = cv2.resize(im_prediction_scaled, (512, 512), interpolation=cv2.INTER_NEAREST)
    red_opacity_layer = cv2.resize(im_prediction_scaled_gray, (512, 512), interpolation=cv2.INTER_NEAREST)
    composite_0 = cv2.resize(np.clip(x_new + norm_image, None, 255.0), (512, 512), interpolation=cv2.INTER_NEAREST)
    composite_1 = cv2.resize(np.clip(x_new - norm_image, 0.0, None), (512, 512), interpolation=cv2.INTER_NEAREST)
    pictures = {
        "background": np.dstack((bg, bg, bg, image_bg)).astype(np.uint8),
        ["layers"][0]: [np.dstack((red_layer, mask_layer, mask_layer, red_opacity_layer))], # red + opacity = 0.5
        "composite": np.dstack((composite_0, composite_1, composite_1, image_bg)).astype(np.uint8)  # red

    }

    time.sleep(5)
    return [(x_new, section), pictures]

with gr.Blocks() as demo:
    gr.Markdown("...")
    with gr.Tab("..."):
        with gr.Column():
            with gr.Row():
               with gr.Row():
                    with gr.Column():
                        ###
                    with gr.Column():
                        image_input = gr.Image(image_mode='L', width=256, height=256, label='MRI Image', sources='upload')
                        image_output = gr.AnnotatedImage(width=256, height=256)
               image_editor = gr.ImageEditor(crop_size="1:1", sources='upload', show_download_button=True, brush=gr.Brush(colors=["#FF000080"])) #rrggbbaa (FF0000=red, 80=50%) #sources='upload', type='pil'

        segment_button = gr.Button("...", visible=False)

    with gr.Accordion("Saved to"):
        markdown = gr.Markdown("...")

    segment_button.click(predict_image, inputs=image_input, outputs=[image_output, image_editor])
    image_editor.change(split_img, inputs=[image_editor, markdown])


if __name__ == '__main__':
    demo.launch()
```

### Screenshot

![ImageEditor](https://github.com/gradio-app/gradio/assets/60062956/653b0a30-95ab-4230-af33-85af58ccca47)
![ImageEditor_2](https://github.com/gradio-app/gradio/assets/60062956/e95cd355-a3d1-476a-89aa-109c53ded4c0)

### Logs

```shell
Traceback (most recent call last):
  File "D:\CNN_PROJECTS\Test\venv\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\CNN_PROJECTS\Test\venv\lib\site-packages\gradio\route_utils.py", line 233, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\CNN_PROJECTS\Test\venv\lib\site-packages\gradio\blocks.py", line 1604, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "D:\CNN_PROJECTS\Test\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\CNN_PROJECTS\Test\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "D:\CNN_PROJECTS\Test\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\CNN_PROJECTS\Test\venv\lib\site-packages\gradio\blocks.py", line 1335, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "D:\CNN_PROJECTS\Test\venv\lib\site-packages\gradio\components\image_editor.py", line 258, in preprocess
    [self.convert_and_format_image(layer) for layer in payload.layers]
  File "D:\CNN_PROJECTS\Test\venv\lib\site-packages\gradio\components\image_editor.py", line 258, in <listcomp>
    [self.convert_and_format_image(layer) for layer in payload.layers]
  File "D:\CNN_PROJECTS\Test\venv\lib\site-packages\gradio\components\image_editor.py", line 220, in convert_and_format_image
    im = PIL.Image.open(file.path)
  File "D:\CNN_PROJECTS\Test\venv\lib\site-packages\PIL\Image.py", line 3309, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'C:\\Users\\...\\AppData\\Local\\Temp\\gradio\\2ef81740504d54f6521d0fe306e8bc9a326c91cd\\layer_0.png'
```

### System Info

```shell
version 4.19.1
```

### Severity

Blocking usage of gradio

**Comment by delestro** [comment]
I guess I'm facing the same issue.

If I pass `value=None` and load an image using the GUI, everything works fine.

But my need is to give the component directly an image.
Something like this:

```
img_empty = np.random.randint(0, 256, (256, 256, 3)).astype("uint8")
input_dict = {
    "background": img_empty,
    "layers": None,
    "composite": None,
}
```

The image is initially displayed, but looks like the component is refreshing all the time and is not usable.

For example, to check `change`:
```
img_editor.change(fn=self.debug, inputs=None, outputs=None)
```

With the `debug` function:
```
def debug(self):
      print(".", end="")
```

Starts printing dots very quickly when the dictionary with the image is passed as value to the `ImageEditor`. No dots are printed when the image is loaded using the GUI (when using `value=None`)

**Comment by delestro** [comment]
[Screencast from 2024-02-27 12:45:51.webm](https://github.com/gradio-app/gradio/assets/10151863/c56b7ee6-c880-4321-8d85-342a8a8cbdb5)

I'm adding here a screen recording of the strange behavior.

This is only possible without the `img_editor.change(fn=self.debug, inputs=None, outputs=None)`. 
In case it is there, the brush cannot draw on the canvas.

**Comment by vernikouskaya** [comment]
I add my screen recordings also here (with time.sleep() and w/o)

https://github.com/gradio-app/gradio/assets/60062956/08dde9b7-5871-46ac-92fc-129e47151e2f


https://github.com/gradio-app/gradio/assets/60062956/20b2de97-6a59-42ee-9c04-3a6979c8c3e8

**Comment by pngwn** [comment]
@vernikouskaya I am struggling to reproduce this.

Could you confirm your gradio version again?

Also if possible could you create a simple gradio app that reproduces this issue on your machine (without the keras/ tensorflow + inference parts)? That way I can be sure we are both seeing the same thing. Don't worry if the code snippet is long, i just need to see the whole thing but without any heavy inference.

**Comment by vernikouskaya** [comment]
I have installed version 4.26.0 via:
```python
pip install https://gradio-builds.s3.amazonaws.com/9ec511147eaa33b46c162037640b4c2b13dda642/gradio-4.26.0-py3-none-any.whl
```

I will do a small app for this issue

**Comment by pngwn** [comment]
Ah. Can you try 4.27.0 instead? That should contain the fixes.

**Comment by vernikouskaya** [comment]
yes, I also tried this

**Comment by pngwn** [comment]
Ah ok. In that case a simple reproduction would be great.

**Comment by pngwn** [comment]
Hmm. Interesting. Do you have a way that I can run the problematic version with meras inference, including any model files etc?

**Comment by vernikouskaya** [comment]
yes sure, I can provide you model file and test image, as well as my python code. Would you give me your email adress?

**Comment by vernikouskaya** [comment]
I am really sorry, but I found what caused the looping, it works now! I put in inputs and in outputs of the image_editor.change() the same image_editor instance. I removed it from the outputs and it works as intended. Thank you so much!!!

**Comment by delestro** [comment]
Just to add to the thread, my issue was also solved with the latest upgrade. Thank you so much for your work there! :clap:
