### ISSUE TITLE
Flaky functional tests

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#7504]
There are a few functional tests that are flaking on almost every PR:

*     js/app/test/file_explorer_component_events.spec.ts:91:1 › File Explorer selects all children when top level directory is selected. 
*     js/app/test/blocks_essay.spec.ts:35:1 › updates backend correctly 

I'll try to catch the other ones and add to this issue

**Comment by freddyaboulton** [comment]
For the file explorer test, I don't think we should be relying on an SSE message to be sent, e.g. ` page.waitForEvent("response"` and instead we should be checking that something visible on the page updated. It's probably not causing the flake but it may cause other issues in the future.

**Comment by pngwn** [comment]
`streaming_echo` is also flaking locally.

**Comment by pngwn** [comment]
My fix didn't work.

**Comment by abidlabs** [comment]
Closing, let's instead tackle the flaky funcitonal tests when we see them, we don't need a dedicated issue
