### ISSUE TITLE
Constant error in gradio app (colab) with prompt pipeline

### ISSUE THREAD

**Issue by boby97** [gradio-app/gradio#7506]
### Describe the bug

The functions works, since when i ask colab to get_response("..."), it gives response from the model. 

But when i want to show it in gradio: 

```
import gradio as gr

gr.close_all()
gr.ChatInterface(get_response).launch(debug=True)
```

It gives me the error: 

`TypeError: response() takes 1 positional argument but 2 were given`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
def get_response(prompt: str) -> None:
    """
    Generate a response from the model.

    Parameters:
        prompt (str): The user's input/question for the model.

    Returns:
        None: Prints the model's response.
    """
    sequences = llama_pipeline(
        prompt,
        do_sample=True,
        top_k=10,
        num_return_sequences=1,
        eos_token_id=tokenizer.eos_token_id,
        max_length=75,
    )
    print("Chatbot:", sequences[0]['generated_text'])

```

### Screenshot

<img width="1271" alt="Screenshot 2024-02-22 at 00 19 47" src="https://github.com/gradio-app/gradio/assets/155005674/5c0a1241-dd97-492f-932a-e7b08c4dd2f3">

### System Info

```shell
Gradio 4.19.1
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @boby97 I don't see enough details here to fully understand the issue. However, I should point out that the function you pass into `gr.ChatInterface`, should take in two parameters, a string input and a list history consisting of the previous conversations. Please see more details here: https://www.gradio.app/guides/creating-a-chatbot-fast

**Comment by abidlabs** [comment]
Hi @boby97 in your code, you need to return the sequence, not just print it. So you should do:

```py
def get_response(prompt: str) -> None:
    """
    Generate a response from the model.

    Parameters:
        prompt (str): The user's input/question for the model.

    Returns:
        None: Prints the model's response.
    """
    sequences = model_pipeline(
        prompt,
        do_sample=True,
        top_k=10,
        num_return_sequences=1,
        eos_token_id=tokenizer.eos_token_id,
        max_length=75,
    )
    return sequences[0]['generated_text']

```
