### ISSUE TITLE
Show progress for uploads in `gr.UploadButton`

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#7515]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

In uploading documents, say 300MB, it might take 52 seconds just for upload stage, and the gradio UI element for gr.File() shows no progress for this stage of pure upload.

To a user it looks like nothing happened, so they want to try again or just abandon the application due to mistrust.

**Describe the solution you'd like**  

With gradio being more heavily used for documents, audio, video, seems upload progress should be added.

**Additional context**  

Progress in other elements is reasonable.

**Comment by abidlabs** [comment]
Thanks @pseudotensor can you clarify? The `gr.File` component does indeed show a progress bar to indicate upload progress:

<img width="615" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/722ab19b-4ca5-473f-9b0f-ca8272bb1fd6">

**Comment by pseudotensor** [comment]
Sorry, I meant `gr.UploadButton` instead of `gr.File`.  I can make basic example.

**Comment by abidlabs** [comment]
Ah sure no need. We'll need to think about the UI for `gr.UploadButton`

**Comment by abidlabs** [comment]
cc @dawoodkhan82 @hannahblair for ideas

**Comment by pseudotensor** [comment]
Just use the upload button demo: https://www.gradio.app/docs/uploadbutton#demos

Then upload some large object (if local to gradio, choose large enough to mimic real network).  E.g. locally I can upload 31GB core file, and never see any information for long time while gradio is at 100% CPU usage.

Secondarily, unsure why upload uses so much CPU.

You'll see in app UI that nothing happens for very long time.

![image](https://github.com/gradio-app/gradio/assets/2249614/a719e5fb-d24b-4e12-ab38-6f423e8e3d20)

**Comment by abidlabs** [comment]
Agreed, we should have a better UI for this

**Comment by pseudotensor** [comment]
FYI I was confused because the UI shows "File" still, but it's really the button.  Naively I wonder why progress in gr.File isn't same here, but I'm sure there is a reason.

It would also be good to show not just progress as in which file is being managed,but % progress for each file, since if one larger file just showing the file being uploaded feels like not enough.  Could be more useful.

**Comment by Solomin0** [comment]
I have been able to address this by adding a progress bar within my status textbox. 
Not super complicated and will only work for easily segment able files but would an approach like this work until a full implementation @pseudotensor 
![image](https://github.com/gradio-app/gradio/assets/37559666/2b83f995-a3f6-4e20-aecb-0ce1b56723e2)

**Comment by pseudotensor** [comment]
@Solomin0 I think in your case it is not the upload that you are showing progress for, but the "upload" into the system by pages etc.  This issue is talking about the original upload of the file itself into the app, like what is in your "Select files for upload" already.

**Comment by M1TR** [comment]
> Thanks @pseudotensor can you clarify? The `gr.File` component does indeed show a progress bar to indicate upload progress:
> 
> <img alt="image" width="615" src="https://private-user-images.githubusercontent.com/1778297/307193103-722ab19b-4ca5-473f-9b0f-ca8272bb1fd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjE0ODIsIm5iZiI6MTcxMjI2MTE4MiwicGF0aCI6Ii8xNzc4Mjk3LzMwNzE5MzEwMy03MjJhYjE5Yi00Y2E1LTQ3M2YtOWIwZi1jYTgyNzJiYjFmZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMjAwNjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGYyOWIxYTRlODlkNWI5MTEyMDljNjg3MGUzZjdmOGRiN2Q0OTc1YzBkZDMyOGRmZDA2YjU2YjVkYjY5MGFjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lWT0hS8LdUCwL0TBgSQMeNg0MXfFsYkWR9PcIkZvX38">

I'm sorry but I don't see this progress bar when using `gr.File`. I'm on version `4.25.0`

**Comment by M1TR** [comment]
@pseudotensor Hello, was this issue resolved? Can you please share if you were able to achieve the progress bar for the upload duration?
