### ISSUE TITLE
Memory management for State

### ISSUE THREAD

**Issue by aliabid94** [gradio-app/gradio#7517]
Right now, the amount of memory used for gr.State and hard disk used for files uploaded increases in an unbounded manner. If an app has a large amount of traffic, we will hit an OOM or OOD error. We need to manage memory and disk space used and delete data for older sessions to avoid this issue.

**Comment by abidlabs** [comment]
See: https://github.com/gradio-app/gradio/pull/7447 for disk space (it doesn't cover memory though)
