### ISSUE TITLE
There are regression for root_path after 4.19.0

### ISSUE THREAD

**Issue by futurestandard** [gradio-app/gradio#7520]
### Describe the bug

it seems root_path setting is ignored.
4.18.0 is fine, but 4.19.0/1/2 have broken display

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import time
import numpy as np
import cv2

def saveimg(im):
    #print(im["layers"][0])
    background=im["background"]
    composite=im["composite"]
    background=cv2.cvtColor(background, cv2.COLOR_BGR2RGB )
    composite=cv2.cvtColor(composite, cv2.COLOR_BGR2RGB )
    cv2.imwrite("layers0.png",im["layers"][0])
    cv2.imwrite("background.png",background)
    cv2.imwrite("composite.png",composite)
    return gr.ImageMask(value=im,height=600), background

def loadimg(im):
    layers0=cv2.imread("layers0.png",-1)
    background=cv2.imread("background.png")
    composite=cv2.imread("composite.png")
    #layers0=cv2.cvtColor(layers0, cv2.COLOR_RGB2BGR, cv2.IMREAD_UNCHANGED )
    background=cv2.cvtColor(background, cv2.COLOR_RGB2BGR )
    composite=cv2.cvtColor(composite, cv2.COLOR_RGB2BGR )
    
    im["layers"][0]=layers0
    im["background"]=background
    im["composite"]=composite
    return gr.ImageMask(value=im,height=600), background

def upim(im_in,im):
    print(type(im_in))
    height, width, channels = im_in.shape[:3]
    im["background"]=im_in
    im["layers"][0]=np.zeros((height, width, 4), np.uint8)
    #im["layers"][1]=None

    print(f" shape:{im_in.shape}, ndim:{im_in.ndim}, size:{im_in.size}")
    return gr.ImageMask(value=im,height=600)
def getmask(im):
    im.save("i.png")
    #dst = Image.new('RGBA', (im.width + o_img.width, im.height))
    
with gr.Blocks() as demo:
    with gr.Tab("カウント"):
        with gr.Row():
            with gr.Column():
                im_in = gr.Image(sources="upload")
                uploadbtn = gr.Button("image upload")
            with gr.Column():    
                with gr.Row():
                    im = gr.ImageMask(height=600)
                with gr.Row():
                    savebtn = gr.Button("save")
                    loadbtn = gr.Button("load")
                with gr.Accordion():
                    with gr.Row():
                        im2 = gr.Image(height=600)
            uploadbtn.click(upim,[im_in,im],[im])
            savebtn.click(saveimg, outputs=[im, im2], inputs=im)
            
            loadbtn.click(loadimg, outputs=[im, im2], inputs=im)
    with gr.Tab("症例一覧"):
        with gr.Row():
            im3 = gr.Image(height=600)

if __name__ == "__main__":
    demo.queue()
    demo.launch(server_name="0.0.0.0",server_port=8044, root_path="/8044")

```

### Screenshot

![スクリーンショット 2024-02-23 175828](https://github.com/gradio-app/gradio/assets/14213791/34c11788-2605-4a49-9f51-9977392224e9)
![スクリーンショット 2024-02-23 175802](https://github.com/gradio-app/gradio/assets/14213791/47747aae-7483-4452-aa07-368f5cb89f01)

### System Info

```shell
gradio environment
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.19.0
gradio_client version: 0.10.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.108.0
ffmpy: 0.3.1
gradio-client==0.10.0 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.1
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.1
pandas: 2.1.4
pillow: 10.1.0
pydantic: 2.5.3
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.2.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.25.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.26.0
huggingface-hub: 0.20.1
packaging: 23.1
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Yes probably.

@futurestandard can you please share any errors you see in the console logs?

And can you also please share what the setup for your web server is? Are you running your web application behind a proxy like nginx? If so, have you set up your nginx configuration according to this guide: https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx

**Comment by futurestandard** [comment]
thanks for your reply.
I think location value apply twice for URL.

my nginx configration
`events{}
http{
	server{
		client_max_body_size 0;
		listen 80;
		server_name deb-ms7b98-j816387602;
		proxy_set_header    Host    $host;
		proxy_set_header    X-Real-IP    $remote_addr;
		proxy_set_header    X-Forwarded-Host       $host;
		proxy_set_header    X-Forwarded-Server    $host;
		proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
		location /8044/ {
			proxy_pass http://127.0.0.1:8044/;
			proxy_buffering off;
			proxy_redirect off;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_set_header Host $host;
		}`
![スクリーンショット 2024-02-28 013313](https://github.com/gradio-app/gradio/assets/14213791/d9fd6c9c-337a-403d-9a92-32f9c5dfe0d5)

**Comment by futurestandard** [comment]
of course
here

![スクリーンショット 2024-02-28 173901](https://github.com/gradio-app/gradio/assets/14213791/fa1bb6b9-3f02-4e6b-8229-91b0e5ed3386)

**Comment by infwinston** [comment]
+1, we also encounter this issue.

**Comment by abidlabs** [comment]
Thanks @infwinston can you please share a repro as well, along with the nginx configuration you are using? Will be looking into this issue this week

**Comment by abidlabs** [comment]
@futurestandard I'm trying to reproduce this issue but having a hard time doing it. I'll share more details shortly. But in the meantime, can you please try with the latest version of `gradio==4.20.x` and let me know if the issue persists?

**Comment by abidlabs** [comment]
I tried to reproduce this by running a Gradio app behind an nginx proxy. Here is my code and configuration, which I tried to match as closely to yours as possible:

```
server {
    listen 80;
    server_name example.com www.example.com;  # Change this to your domain name

    location /8044/ {  # Change this if you'd like to server your Gradio app on a different path
        proxy_pass http://127.0.0.1:8044/; # Change this if your Gradio app will be running on a different port
        proxy_buffering off;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
```

```py
import gradio as gr

gr.Interface(lambda x:x, "image", "image").launch(server_port=8044, root_path="/8044")
```

But as you can see, the Gradio app runs fine: http://35.85.61.147/8044/

@futurestandard @infwinston do you see any differences between what I posted and what code/configuration you are running? And please check with the latest version of `gradio` (currently 4.20.1)

**Comment by infwinston** [comment]
@abidlabs I tried 4.20.1 with the below nginx config, but still met the same issue. And with the exact same setting, `gradio==4.18` works.
```
server {
                listen 80;
                location /9096/ {
                        # proxy_pass http://websocket_test/;
                        proxy_pass http://localhost:9096/;
                        # limit_conn perip 5;  # connections per IP
                        proxy_set_header Host $host;  # set the Host header for the upstream server
                        proxy_set_header X-Real-IP $remote_addr;  # set the client IP address as the real IP for the upstream server
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # set the client IP addresses in the X-Forwarded-For header
                        proxy_http_version 1.1;  # use HTTP version 1.1 for upstream communication
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "Upgrade";  # set the Connection header to Upgrade to enable WebSocket communication
                }
        }

```
<img width="1529" alt="image" src="https://github.com/gradio-app/gradio/assets/1206058/302bad67-9956-41be-9c56-c8459a6b1c47">
