### ISSUE TITLE
Vulnerability at authentication

### ISSUE THREAD

**Issue by rook1337** [gradio-app/gradio#7530]
### Describe the bug

hello team,
For more information, please check here: https://huntr.com/bounties/9142de52-ff10-41e8-b097-b7471e6cfe58/

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Please check huntr.dev

### System Info

```shell
Linux
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Will respond on huntr
