### ISSUE TITLE
Doc strings say auth_message says can be HTML, but only renders as string

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#7535]
### Describe the bug

Doc strings say auth_message says can be HTML, but only renders as string

```
auth_message: If provided, HTML message provided on login page.
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.ClearButton([msg, chatbot])

    def respond(message, chat_history):
        bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
        chat_history.append((message, bot_message))
        time.sleep(2)
        return "", chat_history

    msg.submit(respond, [msg, chatbot], [msg, chatbot])

if __name__ == "__main__":
    demo.launch(auth_message='<img src="models/meta.png" alt="Italian Trulli">', auth=[('foo', 'foo')])

```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/2249614/fe0bd066-476c-41d9-9923-c745a9b17f68)

### System Info

```shell
gradio 4.19.1

I've tried many other html things, always shows up as text.

I'd like it to respect html so I can show an image like above or with `<svg_id`.

I don't know way to work around except don't use HTML.
```

### Severity

Blocking usage of gradio

**Comment by pseudotensor** [comment]
I guess issue is Login.svelte that has a big block for login and the auth message is inside this `<p class="auth">{auth_message}</p>`

**Comment by pseudotensor** [comment]
Kinda related to: https://github.com/gradio-app/gradio/issues/7291

However, the solution proposed there is not good.  The reason why I decided to start using auth was because of attackers spamming /upload endpoint, and only auth protects against from such a direct trivial attack leading to actual uploads.  Similar for API list etc.

**Comment by abidlabs** [comment]
Yup @pseudotensor do you want to open a quick PR for this? Happy to review

**Comment by abidlabs** [comment]
Np we'll take a look, it should be a quick fix
