### ISSUE TITLE
Wen i change the value of dropdown by Javascript,it does not work

### ISSUE THREAD

**Issue by mengjiteam** [gradio-app/gradio#7542]
### Describe the bug

Wen i change the value of dropdown by Javascript,it does not work.in my video,first my choice is "test 01",I want to change the choice to "test 03".After my js code runing,the textarea of dropdown is "test 03",but when i click the dropdown,the seleted not change,it's still "test01".

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python code
```
yuzhi=["test 01","test 02","test 03","test 04"]
yuzhipeizhi=gr.Dropdown(label='预置组合选择',filterable=True, allow_custom_value=True, choices=yuzhi, variant="secondary",scale=3,elem_id="qqq")

'''javascript code
'''
function update(target) 
{
    let e = new Event("input", { bubbles: true })
    Object.defineProperty(e, "target", { value: target })
    target.dispatchEvent(e);
}
var text=gradioApp().querySelector("#qqq input");

text.value="test 03";
update(text);

### Screenshot

https://github.com/gradio-app/gradio/assets/134719612/5695efd0-090d-4fc7-a1ae-a13327cf1f25

### System Info

```shell
gradio: 4.19.2
```

### Severity

I can not work around it,somebody help please!

**Comment by uiyo** [comment]
same issue, but don't know how to work around it, hlp pls

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio
