### ISSUE TITLE
Image support in ChatInterface

### ISSUE THREAD

**Issue by recursionbane** [gradio-app/gradio#7546]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
The ChatInterface makes setting up a chatbot really quick and easy. It does not support image upload, and the fallback of switching to using individual Blocks is clunky, since we would have to recreate much of the ChatInterface's functionality with Blocks.

**Describe the solution you'd like**  
Support image upload natively in ChatInterface.

**Comment by abidlabs** [comment]
We're working on this! cc @dawoodkhan82

**Comment by dawoodkhan82** [comment]
Should be out soon! @recursionbane. You can keep track of progress on this [PR](https://github.com/gradio-app/gradio/pull/7420)

**Comment by recursionbane** [comment]
Testing now!

**Comment by dawoodkhan82** [comment]
@recursionbane The multimodal chat input [PR](https://github.com/gradio-app/gradio/pull/7420) has been merged. Test it out with `gr.ChatInterface(multimodal=True)`

**Comment by recursionbane** [comment]
Thanks, @dawoodkhan82!
