### ISSUE TITLE
Share function error

### ISSUE THREAD

**Issue by lidaming1** [gradio-app/gradio#7548]
### Describe the bug

When I use the function of share, and open the public URL，Gradio gives the message  No interface is running right now,such as :
![image](https://github.com/gradio-app/gradio/assets/65325238/cd14d230-34f6-4fa2-99f8-bef3803fb1c1)
 
and there has nothing wrong in the cmd:
![image](https://github.com/gradio-app/gradio/assets/65325238/4a47e39d-bcc3-4e07-97c7-9a94dbd28cc4)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
with gr.Blocks() as demo:
demo.launch(share=True)
```

### System Info

```shell
gradio version : 4.19.2
windows 10
python 3.10.12
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @lidaming1 we're going to take a look at all the share link issues soon. In the meantime, can you please use this issue to share any share link-related issues: https://github.com/gradio-app/gradio/issues/3677 -- it also includes some suggestions that may be helpful for you
