### ISSUE TITLE
Oauth Vulnerability

### ISSUE THREAD

**Issue by rook1337** [gradio-app/gradio#7550]
### Describe the bug

Hello team,
We have found vulnerability on Oauth,
 https://huntr.com/bounties/196678d1-cbaa-45f3-bbe9-f25aad63a31d/

This is another one:-
https://huntr.com/bounties/146855a4-6101-4647-ac97-5535459bae95

Please check both reports and accept it if they are valid because after 90 days it will be closed automatically

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

check on huntr.com

### System Info

```shell
Linux
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @rook1337 I'll respond on huntr
