### ISSUE TITLE
Invalid file_types breaks drag and drop in gr.File()

### ISSUE THREAD

**Issue by Gauntlet173** [gradio-app/gradio#7556]
### Describe the bug

If you create a File component with an invalid file_types value (e.g. `gr.File(file_types=["pdf"]`, noting the missing period in `.pdf`), drag and drop does not work, but selecting and uploading a file does work.

I'm not sure whether the bug is that drag and drop doesn't work, that the code runs at all, or that using the file upload interface does work with invalid files, but at the very least there is an inconsistency, there.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as app:
  gr.File(file_types=["pdf"]) # Can't drag and drop files, can select files.
  gr.File(file_types=[".pdf"]) # Can both drag and drop and select files.

app.launch()
```

### Logs

```shell
No errors.
```

### System Info

```shell
python 3.12, gradio 4.19.2, WSL (Ubuntu), Windows
```

### Severity

I can work around it

**Comment by dawoodkhan82** [comment]
@Gauntlet173 taking a look now.
