### ISSUE TITLE
Gradio slider not showing static values even with step size set correctly.

### ISSUE THREAD

**Issue by sdave-connexion** [gradio-app/gradio#7560]
### Describe the bug

Hi, when I use a slider with a step size of 0.1 the values shown are incorrect (instead of 0.2 it shows 0.19999996 etc). I could not find any solution to this. can someone support? Thank you

with gr.Row():
                # Sliders for adjusting model weights
                abc_weight = gr.Slider(minimum=0.0, maximum=1.0, step=0.1, value=0.2, label="abc Weight")
                xyz_weight = gr.Slider(minimum=0.0, maximum=1.0, step=0.1, value=0.8, label="xyz Weight")

                abc_weight.change(fn=update_weights, inputs=[abc_weight, xyz_weight], outputs=[abc_weight, xyz_weight])
                xyz_weight.change(fn=update_weights, inputs=[xyz_weight, abc_weight], outputs=[xyz_weight, abc_weight])

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

with gr.Row():
                # Sliders for adjusting model weights
                abc_weight = gr.Slider(minimum=0.0, maximum=1.0, step=0.1, value=0.2, label="abc Weight")
                xyz_weight = gr.Slider(minimum=0.0, maximum=1.0, step=0.1, value=0.8, label="xyz Weight")

                abc_weight.change(fn=update_weights, inputs=[abc_weight, xyz_weight], outputs=[abc_weight, xyz_weight])
                xyz_weight.change(fn=update_weights, inputs=[xyz_weight, abc_weight], outputs=[xyz_weight, abc_weight])

### Screenshot
![gradio issue](https://github.com/gradio-app/gradio/assets/54185486/63207cca-1f9d-4360-8c33-6b2b9b36f385)

### System Info

```shell
yes, latest version with !pip install gradio
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @sdave-connexion I can't repro this issue. What browser / OS are you on:

https://github.com/gradio-app/gradio/assets/1778297/bdca5621-ad08-4ea7-aaf4-7552ec35b717

**Comment by sdave-connexion** [comment]
Hi, please find attached the reproducible error setup. 

`import gradio as gr

def update_weights(canda_weight, _):
    # Ensure moodboard_weight is adjusted so that the sum of canda_weight and moodboard_weight is always 1.0
    moodboard_weight = 1.0 - canda_weight
    return canda_weight, moodboard_weight

with gr.Blocks() as demo:
    # Sliders for adjusting model weights
    canda_weight = gr.Slider(minimum=0.0, maximum=1.0, step=0.1, value=0.2, label="Canda Weight")
    moodboard_weight = gr.Slider(minimum=0.0, maximum=1.0, step=0.1, value=0.8, label="Moodboard Weight")

    canda_weight.change(fn=update_weights, inputs=[canda_weight, moodboard_weight], outputs=[canda_weight, moodboard_weight])
    moodboard_weight.change(fn=update_weights, inputs=[moodboard_weight, canda_weight], outputs=[moodboard_weight, canda_weight])

demo.launch(show_error=True, share=True)`

**Comment by sdave-connexion** [comment]
Hi @abidlabs , please find attached the reproducible error setup sir. 

```
import gradio as gr

def update_weights(abc_weight, _):
    # Ensure xyz_weight is adjusted so that the sum of abc_weight and xyz_weight is always 1.0
    xyz_weight = 1.0 - abc_weight
    return abc_weight, xyz_weight

with gr.Blocks() as demo:
    # Sliders for adjusting model weights
    abc_weight = gr.Slider(minimum=0.0, maximum=1.0, step=0.1, value=0.2, label="abc Weight")
    xyz_weight = gr.Slider(minimum=0.0, maximum=1.0, step=0.1, value=0.8, label="xyz Weight")

    abc_weight.change(fn=update_weights, inputs=[abc_weight, xyz_weight], outputs=[abc_weight, xyz_weight])
    xyz_weight.change(fn=update_weights, inputs=[xyz_weight, abc_weight], outputs=[xyz_weight, abc_weight])

demo.launch(show_error=True, share=True)
```

**Comment by abidlabs** [comment]
Hi @sdave-connexion oh I see, sometimes subtraction (and other arithmetic operations) in Python can lead to rounding errors. I'd suggest just adding round to your function:

```py
import gradio as gr

def update_weights(abc_weight, _):
    # Ensure xyz_weight is adjusted so that the sum of abc_weight and xyz_weight is always 1.0
    xyz_weight = 1.0 - abc_weight
    return round(abc_weight, 1), round(xyz_weight, 1)

with gr.Blocks() as demo:
    # Sliders for adjusting model weights
    abc_weight = gr.Slider(minimum=0.0, maximum=1.0, step=0.1, value=0.2, label="abc Weight")
    xyz_weight = gr.Slider(minimum=0.0, maximum=1.0, step=0.1, value=0.8, label="xyz Weight")

    abc_weight.change(fn=update_weights, inputs=[abc_weight, xyz_weight], outputs=[abc_weight, xyz_weight])
    xyz_weight.change(fn=update_weights, inputs=[xyz_weight, abc_weight], outputs=[xyz_weight, abc_weight])

demo.launch(show_error=True, share=True)

```
