### ISSUE TITLE
Image viewer isnt working for filepath

### ISSUE THREAD

**Issue by datavistics** [gradio-app/gradio#7566]
### Describe the bug

When using the image viewer it doesnt load the image.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as ui:
    with gr.Tab("Application"):
        gr.Image(str(pathlib_path), type='filepath')

```

### System Info

```shell
I am
```

### Severity

I can work around it

**Comment by datavistics** [comment]
cc @yvrjsharma

**Comment by abidlabs** [comment]
I can't reproduce this @datavistics:

<img width="835" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/245d0909-c9c0-4bb2-a958-2229d7058360">

Is it happening with a specific file, or is there something specific about your environment?

**Comment by yvrjsharma** [comment]
Actually, I am seeing this behavior, too, on Spaces. I have created a repro of the issue @datavistics was facing, and it is available over here - https://huggingface.co/spaces/ysharma/testing_image_display

**Comment by yvrjsharma** [comment]
My repro on Colab. Not sure what I am doing wrong here 🤒  :

![image](https://github.com/gradio-app/gradio/assets/48665385/2d379452-92f5-4c39-a0c5-331c7b94f7a5)
