### ISSUE TITLE
`gr.Markdown` is not updated properly when it has an image tag

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#7569]
### Describe the bug

The following works fine,
```py
import gradio as gr


def get_img_tag():
    return 'a'


def get_img_tag2():
    return 'b'


with gr.Blocks() as demo:
    md = gr.Markdown(value=get_img_tag())
    btn = gr.Button()
    btn.click(fn=get_img_tag2, outputs=md)
demo.queue().launch()
```
but the following doesn't.
```python
import gradio as gr


def get_img_tag():
    return '<img src="https://raw.githubusercontent.com/williamyang1991/DualStyleGAN/main/doc_images/cartoon_overview.jpg">'


def get_img_tag2():
    return '<img src="https://raw.githubusercontent.com/williamyang1991/DualStyleGAN/main/doc_images/Reconstruction_arcane_overview.jpg">'


with gr.Blocks() as demo:
    md = gr.Markdown(value=get_img_tag())
    btn = gr.Button()
    btn.click(fn=get_img_tag2, outputs=md)
demo.queue().launch()
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

[playground](https://www.gradio.app/playground?demo=Blank&code=aW1wb3J0IGdyYWRpbyBhcyBncgoKCmRlZiBnZXRfaW1nX3RhZygpOgogICAgcmV0dXJuICc8aW1nIHNyYz0iaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3dpbGxpYW15YW5nMTk5MS9EdWFsU3R5bGVHQU4vbWFpbi9kb2NfaW1hZ2VzL2NhcnRvb25fb3ZlcnZpZXcuanBnIj4nCgoKZGVmIGdldF9pbWdfdGFnMigpOgogICAgcmV0dXJuICc8aW1nIHNyYz0iaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3dpbGxpYW15YW5nMTk5MS9EdWFsU3R5bGVHQU4vbWFpbi9kb2NfaW1hZ2VzL1JlY29uc3RydWN0aW9uX2FyY2FuZV9vdmVydmlldy5qcGciPicKCgp3aXRoIGdyLkJsb2NrcygpIGFzIGRlbW86CiAgICBtZCA9IGdyLk1hcmtkb3duKHZhbHVlPWdldF9pbWdfdGFnKCkpCiAgICBidG4gPSBnci5CdXR0b24oKQogICAgYnRuLmNsaWNrKGZuPWdldF9pbWdfdGFnMiwgb3V0cHV0cz1tZCkKZGVtby5xdWV1ZSgpLmxhdW5jaCgpCg==)

### Screenshot

https://github.com/gradio-app/gradio/assets/25161192/d03c90e7-d94d-4b88-9d44-6d1f81d9e427

### System Info

```shell
gradio==4.19.2
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
That's really interesting.. seeing this in the logs:

<img width="887" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/4c6fd06b-fc02-4672-a8db-965131425f55">

**Comment by dawoodkhan82** [comment]
@hysts I'm working on a proper fix for this, but it seems like passing in empty list for `latext_delimiters` solves your bug for now.    

`md = gr.Markdown(value=get_img_tag(), latex_delimiters=[])
`

**Comment by hysts** [comment]
Oh, thanks for the workaround tips!
