### ISSUE TITLE
[Blocks] Brainstorming about Parallel and Series

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#757]
Regarding @chuachinhon's [comment](https://github.com/gradio-app/gradio/issues/690#issuecomment-1055118586), I think with blocks there is new opportunities with different designs and functionalities for `Parallel` and `Series`. 

Though it would be on low priority for now.

**Comment by abidlabs** [comment]
Removing from Blocks milestone since this is more of an open-ended brainstorming issue

**Comment by abidlabs** [comment]
Closing for now, feel free to reopen with more concrete suggestions in the future.
