### ISSUE TITLE
ImageEditor not functioning correctly

### ISSUE THREAD

**Issue by AUTOMATIC1111** [gradio-app/gradio#7591]
### Describe the bug

When using ImageEditor as input for events, it loses user's painted area and blinks.

This is blocking the update to gradio 4.

### Have you searched existing issues?  🔎

- [X] I have searched found existing issues similar to this one

### Reproduction

1. Load image into `A`.
2. Press `A->B` button.
3. Expected: `A` image doesn't blink because of `show_progress="hidden"`, observed: `A` image becomes white for few moments and then comes back (this is minor).
4. Draw on `B` image.
5. Press `A<-B` button.
6. Expected: your drawing on `B` is preserved, observed: your drawing on `B` is gone.

```python
import gradio as gr
import time


with gr.Blocks() as demo:
    with gr.Row():
        buttonAB = gr.Button('A -> B')
        buttonBA = gr.Button('A <- B')

    with gr.Row():
        imgA = gr.ImageEditor(label="A", type="pil", image_mode="RGBA")
        imgB = gr.ImageEditor(label="B", brush=gr.Brush(colors=['#ffffff'], color_mode="fixed"), type="pil", image_mode="RGBA")

    def copy_image(x):
        return x

    buttonAB.click(copy_image, inputs=[imgA], outputs=[imgB], show_progress="hidden")
    buttonBA.click(copy_image, inputs=[imgB], outputs=[imgA], show_progress="hidden")

demo.launch(debug=True)
```

### Screenshot

![firefox_uF29HuwDVv](https://github.com/gradio-app/gradio/assets/20920490/298acd96-610f-4393-8bbb-9cf4ee96161c)

### Logs

```
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

### System Info

```
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.19.2
gradio_client version: 0.10.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.1.0
altair: 5.0.0
fastapi: 0.104.1
ffmpy: 0.3.0
gradio-client==0.10.1 is not installed.
httpx: 0.24.1
huggingface-hub: 0.19.4
importlib-resources: 5.12.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.2
numpy: 1.26.2
orjson: 3.8.12
packaging: 23.1
pandas: 1.5.3
pillow: 9.5.0
pydantic: 2.6.3
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0
ruff: 0.3.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.22.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.24.1
huggingface-hub: 0.19.4
packaging: 23.1
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by MoonRide303** [comment]
@pngwn Could we ask for investigating and fixing this problem, on a bit higher priority? It's blocking upgrade of SD web UI to the new version of Gradio.

**Comment by pngwn** [comment]
Working on the image editor now. These issues should dealt with over the next week or so.
