### ISSUE TITLE
How to serve a user uploaded file within the browser? 

### ISSUE THREAD

**Issue by Solomin0** [gradio-app/gradio#7600]
- [ X] I have searched to see if a similar issue already exists.

With more PDF RAG bots being put out I think a clear way to redirect the user to the file would be useful. 
Ideally this would look like a button click to open in a new tab "file:///C:/clone_directory/text_files/constitution.pdf" within the browser somehow. I am not too sure if this is already possible I have tried using gr.Button's link parameter but it does not seem to do anything with the file URI. 

This would be different to the PDF Viewer custom widget as it would directly serve a cloned file back to the user instead of giving the gradio viewport. If this is already possible please let me know. 

Thanks yall. 

![image](https://github.com/gradio-app/gradio/assets/37559666/3fa8ea52-5af4-4cdb-9f45-ca12fbbd853b)

**Comment by abidlabs** [comment]
Hi @Solomin0 we just added a `gr.DownloadButton` that does exactly this! https://github.com/gradio-app/gradio/pull/7518

We'll release it on pypi this week probably but in the meantime, you can install from `main`: pip install https://gradio-builds.s3.amazonaws.com/fc4c2dbd994c49e37296978da1cb85e424080d1c/gradio-4.19.2-py3-none-any.whl

**Comment by Solomin0** [comment]
Yall are already on top of it, that is great! Thanks.
