### ISSUE TITLE
gr.Dataframe not sending sorted dataframe to callback

### ISSUE THREAD

**Issue by ross-mitchell** [gradio-app/gradio#7601]
### Describe the bug

The gr.Dataframe method allows the user to display and sort data tables. The user can sort the displayed data by clicking on the triangle in the column title cell. See attached screen shot. 

If the user sorts the data by a column then clicks on a data cell, then the data passed to the select call back function is incongruent.

The gr.SelectData event contains the correct row and column indices, and the correct value of the selected cell.

However, the unsorted dataframe is passed into the select callback function for the widget.

The value in the passed dataframe at the passed row and column indices does not match the passed value in the gr.SelectData event.

This means the callback can not access other data in a sorted dataframe, outside the selected cell, reliably. 

This issue is present in Gradio v4.19.2 but not in v3.36.1

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import pandas as pd

with gr.Blocks() as demo:

    sample_data = {
                    'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3']
                   }
    df = pd.DataFrame(sample_data)
    print(f"Dataframe as initialized:\n{df}")

    df_widget = gr.Dataframe(df, interactive=False)

    def df_select_callback(df: pd.DataFrame, evt: gr.SelectData):
        row_index = evt.index[0]
        col_index = evt.index[1]
        value = evt.value
        print(f"\n(Row, Column) = ({row_index}, {col_index}). Value = {value}")
        print(f"Dataframe in callback:\n{df}")
        return

    df_widget.select(df_select_callback, inputs=[df_widget])

if __name__ == "__main__":
    demo.launch()

```

### Screenshot

The user has sorted column A by descending value, then clicked on the cell containing "B0" in row 3, column 1.

![CleanShot 2024-03-04 at 17 42 28@2x](https://github.com/gradio-app/gradio/assets/13511772/1dd816e9-4479-4dbc-8e61-ea0f3a7b1397)

### Logs

```shell
Dataframe as initialized:
    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
Running on local URL:  [edited out]
To create a public link, set `share=True` in `launch()`.

(Row, Column) = (3, 1). Value = B0
Dataframe in callback:
    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
```

### System Info

```shell
$ uname -a
Linux **** 5.4.0-171-generic #189-Ubuntu SMP Fri Jan 5 14:23:02 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Gradio version 4.19.2
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Related: https://github.com/gradio-app/gradio/issues/7127

**Comment by recursix** [comment]
anyone found a workaround?

**Comment by dwipper** [comment]
Running into this problem too. @abidlabs It's a real show-stopper. Shouldn't the index be updated when the DF is sorted? While it accurately returns the .value of the cell that was clicked, the .index value returned is from the original order the data was loaded in the DF. There's no way that I have found to access data in other cells is that row. Any idea about a work around?

**Comment by abidlabs** [comment]
Working on a PR that should provide a solution for this: https://github.com/gradio-app/gradio/pull/9128 if anyone would like to give feedback (installation instructions are in the PR)

**Comment by shadow66603** [comment]
Interested also to have the solution, crazy it is not handled...
