### ISSUE TITLE
UI components not loading when running app on Kubeflow notebook

### ISSUE THREAD

**Issue by albusdemens** [gradio-app/gradio#7605]
### Describe the bug

I need to run [this app](https://huggingface.co/spaces/TencentARC/PhotoMaker) on Kubeflow. Once I launch the app and load it in the browser, some components are missing (see image attached). Do you have any suggestions on how to fix this? Below you can find the error messages I get using the Web Developer terminal interface. 

Error messages: 
```
TypeError: a.default.detectStore(...) is undefined 
TypeError: data.languages[0] is undefined 
The stylesheet https://onpremise-kubeflow.krafton-ml.net/assets/index-e657421a.css was not loaded because its MIME type, "text/html", is not "text/css". 
Unable to preload CSS for https://onpremise-kubeflow.krafton-ml.net/assets/index-e657421a.css 
Could not get api details: JSON.parse: unexpected character at line 1 column 1 of the JSON data 
The stylesheet https://onpremise-kubeflow.krafton-ml.net/theme.css was not loaded because its MIME type, "text/html", is not "text/css". Unable to preload CSS for https://onpremise-kubeflow.krafton-ml.net/theme.css
```

<img width="1919" alt="gradio_UI" src="https://github.com/gradio-app/gradio/assets/276459/705848dc-1cfd-4aaf-b441-6679299161f1">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
conda create -n Env python==3.10
conda activate Env
conda install pip
git clone https://huggingface.co/spaces/TencentARC/PhotoMaker
cd PhotoMaker
pip install -r requirements.txt
```

### Screenshot

<img width="1919" alt="gradio_UI" src="https://github.com/gradio-app/gradio/assets/276459/3d24835b-7da2-4fa4-9776-94430d32de75">

### System Info

```shell
Operating System: Linux
gradio version: 4.19.2
gradio_client version: 0.10.1
```

### Severity

Blocking usage of gradio

**Comment by pngwn** [comment]
Is there something in your config/ setup that could be overwriting the headers?
