### ISSUE TITLE
strange gap in custom footer

### ISSUE THREAD

**Issue by ai-marat** [gradio-app/gradio#7609]
### Describe the bug

I've been trying to create a custom footer, but I always encounter a strange gap on the left side. How can I get rid of it?

Here is the link with reproducible code in Colab:
https://colab.research.google.com/drive/170wJMqtbFc17z7_IW1V6_lh-JaWCiokc?usp=sharing

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
def func(text):
  return text

with gr.Blocks(css='''footer{display:none !important}

               .gradio-container {max-width: 100%!important;
               margin: 0; padding: 0; margin-top: 0px;
               margin-left: 0px;
               margin-right: 0px;}

               .container {max-width: 720px !important;
               margin: 0 auto;}


               .gallery {max-width: 1200px !important;
               margin: 0 auto;}

               .footer_main {position: fixed;
               bottom: 0;
               width: 100%;
               text-align:left;
               background-color: #253959;
               padding: 20px;
               margin-top: 0px;
               margin-left: 0px;
               margin-right: 0px;}
                           
'''
               #js = js_func
               ) as demo:
  



  gr.Markdown(
    """
    # Header

    """)
  
  gr.Markdown(
    """
    Footer, 2024
    """, elem_classes= 'footer_main')

  output = gr.Gallery(label="Result",
                      elem_classes = 'gallery')
  
  with gr.Group(elem_classes = 'container'):
    with gr.Column():
     input = gr.Textbox(lines = 3,label="", placeholder="enter")
     btn = gr.Button("RUN", variant="primary")
     btn.click(fn=func, inputs=input, outputs=output)


demo.launch(share = True)#, debug=True
```

### Screenshot

<img width="1069" alt="Screenshot 2024-03-05 at 20 55 22" src="https://github.com/gradio-app/gradio/assets/148277579/4b6fa081-c4b3-4ef9-b1ea-a6df187a9060">

### System Info

```shell
-
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @ai-marat this isn't really a core issue / feature request in the Gradio library, but rather a question of how to write custom CSS. For general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
