### ISSUE TITLE
How to use api in kotlin

### ISSUE THREAD

**Issue by byeolkady** [gradio-app/gradio#761]
Can I use gradio api in kotlin?! If there's a way, please let me know.

**Comment by abidlabs** [comment]
`gradio` works with any Python function. So while it would not be possible to use gradio directly in Kotlin, if you can call your kotlin script from the terminal, through python's `os.system()`, then you may be able to use it with Kotlin.

**Comment by abidlabs** [comment]
Closing for now, feel free to reopen if you run into any issues trying this.
