### ISSUE TITLE
Gradio is 1 feature away to be full APP - updating components from code 

### ISSUE THREAD

**Issue by FurkanGozukara** [gradio-app/gradio#7615]
I am developing a lot of APPs recently

E.g. SUPIR : 

It is amazing. What I am missing most is updating the elements of Gradio from code. 

Such as

`target_res = gr.Textbox()`

I want to set value of this text box from code like

`target_res.value = "new text"`

**Comment by abidlabs** [comment]
Can you provide more context about what you're trying to do @FurkanGozukara? I think you might be already able to do this, but I'm not totally sure what you mean. Specifically, what code should cause the value of the textbox should update?

**Comment by FurkanGozukara** [comment]
> Can you provide more context about what you're trying to do @FurkanGozukara? I think you might be already able to do this, but I'm not totally sure what you mean. Specifically, what code should cause the value of the textbox should update?

here sample example

modifying textbox value from method

`additional_text_box.value = max_num`

```
import gradio as gr

def loop_method(input_number, additional_text_box):
    if input_number.isdigit():
        max_num = min(int(input_number), 100)
        additional_text_box.value = max_num
        return ', '.join([str(i) for i in range(1, max_num + 1)])
    else:
        return "Please enter a valid number."

def create_app():
    input_box = gr.Textbox(label="Enter a number (1 to 100):")
    output_box = gr.Textbox(label="Output:", interactive=False)
    loop_button = gr.Button("Run Loop")
    additional_text_box = gr.Textbox(label="Additional Text Box:")

    loop_button.click(fn=loop_method, inputs=[input_box,additional_text_box], outputs=output_box)

    app_layout = gr.Row(
        gr.Column(input_box, loop_button, output_box),
        gr.Column(additional_text_box)
    )

    app = gr.Interface(fn=lambda: None, inputs=[], outputs=[], title="Simple Gradio App")
    app.layout = app_layout
    return app

app = create_app()
app.launch(inbrowser=True)
```

**Comment by abidlabs** [comment]
You can make `additional_text_box` an output of your function and update the value accordingly, like this:

```py
def loop_method(input_number, additional_text_box):
    if input_number.isdigit():
        max_num = min(int(input_number), 100)
=        return ', '.join([str(i) for i in range(1, max_num + 1)]), max_num
    else:
        return "Please enter a valid number.", additional_text_box

def create_app():
    input_box = gr.Textbox(label="Enter a number (1 to 100):")
    output_box = gr.Textbox(label="Output:", interactive=False)
    loop_button = gr.Button("Run Loop")
    additional_text_box = gr.Textbox(label="Additional Text Box:")

    loop_button.click(fn=loop_method, inputs=[input_box,additional_text_box], outputs=[output_box, additional_text_box])

```

**Comment by FurkanGozukara** [comment]
> You can make `additional_text_box` an output of your function and update the value accordingly, like this:
> 
> ```python
> def loop_method(input_number, additional_text_box):
>     if input_number.isdigit():
>         max_num = min(int(input_number), 100)
>         return ', '.join([str(i) for i in range(1, max_num + 1)]), max_num
>     else:
>         return "Please enter a valid number.", additional_text_box
> 
> def create_app():
>     input_box = gr.Textbox(label="Enter a number (1 to 100):")
>     output_box = gr.Textbox(label="Output:", interactive=False)
>     loop_button = gr.Button("Run Loop")
>     additional_text_box = gr.Textbox(label="Additional Text Box:")
> 
>     loop_button.click(fn=loop_method, inputs=[input_box,additional_text_box], outputs=[output_box, additional_text_box])
> ```

ye but that is annoying and you can't update any time as you wish. It is only updated from method return 

let's say i have a for loop inside method and each loop taking 30 seconds to complete and i will have 100 times loop
then i can't update elements as i wish
moreover when you press button, all return elements on Gradio shows loading :) 

here a for loop example

```
def loop_method(input_number, additional_text_box):
    for i in range(1, 111):
        additional_text_box.value = i 
```

it is missing this to be like a real time app

**Comment by abidlabs** [comment]
> ye but that is annoying and you can't update any time as you wish. It is only updated from method return
> 
> let's say i have a for loop inside method and each loop taking 30 seconds to complete and i will have 100 times loop
> then i can't update elements as i wish
> 

In that case, you can `yield` --> 

```py
def loop_method(input_number, additional_text_box):
    for i in range(1, 111):
        yield __, i  
```

**Comment by abidlabs** [comment]
https://www.gradio.app/guides/key-features#streaming-outputs

**Comment by FurkanGozukara** [comment]
> > ye but that is annoying and you can't update any time as you wish. It is only updated from method return
> > let's say i have a for loop inside method and each loop taking 30 seconds to complete and i will have 100 times loop
> > then i can't update elements as i wish
> 
> In that case, you can `yield` -->
> 
> ```python
> def loop_method(input_number, additional_text_box):
>     for i in range(1, 111):
>         yield __, i  
> ```

yield is still returning and and it is even harder to use :/

I wonder we can't make it auto update as in my example?

```
def loop_method(input_number, additional_text_box):
    for i in range(1, 111):
        additional_text_box.value = i 
```

This is what I would do lets say in a Windows C# APP. That would be updated in the Interface lets say WPF or Winforms

This way Gradio would become definitely more like a native full APP

**Comment by FurkanGozukara** [comment]
@abidlabs thanks

the progress bar is able to update progress though while inside code. so it uses a special mechanism i suppose

**Comment by abidlabs** [comment]
Ah yeah it makes a call to another function, which is something we could do but it wouldn't be as simple as updating a component attribute.

**Comment by FurkanGozukara** [comment]
> Ah yeah it makes a call to another function, which is something we could do but it wouldn't be as simple as updating a component attribute.

this kind of stuff would be amazing

`additional_text_box.value.update(i) `

if could be added

**Comment by abidlabs** [comment]
Btw you can already do `yield {additional_text_box: i}` in your function, I believe, which has the same effect

**Comment by abidlabs** [comment]
https://www.gradio.app/guides/blocks-and-event-listeners#function-return-list-vs-dict

**Comment by FurkanGozukara** [comment]
> Btw you can already do `yield {additional_text_box: i}` in your function, I believe, which has the same effect

I tried like below but didn't work

```
import gradio as gr
import time

def loop_method(input_number, additional_text_box, additional_text_box2):
    for i in range(1, 111):
        yield {additional_text_box: i}
        time.sleep(5)
        #lets assume some more code here
        yield {additional_text_box2: i*10}
        time.sleep(5)

block = gr.Blocks().queue()
with block:
    input_box = gr.Textbox(label="Enter a number (1 to 100):")
    output_box = gr.Textbox(label="Output:", interactive=False)
    loop_button = gr.Button("Run Loop")
    additional_text_box = gr.Textbox(label="Additional Text Box:", interactive=False)
    additional_text_box2 = gr.Textbox(label="Additional Text 2 Box:", interactive=False)

    loop_button.click(fn=loop_method, inputs=[input_box,additional_text_box, additional_text_box2], outputs=[additional_text_box, additional_text_box2])

block.launch(inbrowser=True)
```

**Comment by abidlabs** [comment]
In `loop_method`, the parameter names are shadowing the names of the components. Try this instead:

```py
import gradio as gr
import time

def loop_method(input_number, atb, atb2):
    for i in range(1, 111):
        yield {additional_text_box: i}
        time.sleep(0.5)
        #lets assume some more code here
        yield {additional_text_box2: i*10}
        time.sleep(0.5)

block = gr.Blocks().queue()
with block:
    input_box = gr.Textbox(label="Enter a number (1 to 100):")
    output_box = gr.Textbox(label="Output:", interactive=False)
    loop_button = gr.Button("Run Loop")
    additional_text_box = gr.Textbox(label="Additional Text Box:", interactive=False)
    additional_text_box2 = gr.Textbox(label="Additional Text 2 Box:", interactive=False)

    loop_button.click(fn=loop_method, inputs=[input_box, additional_text_box, additional_text_box2], outputs=[additional_text_box, additional_text_box2])

block.launch()
```

**Comment by FurkanGozukara** [comment]
@abidlabs this worked great ty so much
