### ISSUE TITLE
The shape argument in gr.Image(shape=(x,y)) is removed but included in some demos

### ISSUE THREAD

**Issue by benkoo** [gradio-app/gradio#7619]
### Describe the bug

I'm trying to use the gr.Interface().launch() function with an image input, but I'm getting a TypeError.  Here's the code:

Python
gr.Interface(
  fn=predict,
  inputs=gr.Image(shape=(28,28), imagemode='L', invertcolors=True, source='sketchpad'),
  outputs="label"
).launch()
Use code with caution.
I keep getting this error:

TypeError: Image.init() got an unexpected keyword argument 'shape'
I've tried looking at image demos in the Gradio documentation but none seem to be working for me. Is this a bug or am I missing something?
It also appears that many of demo apps on the documentation website are also broken for the same reason. Did any one notice that?
Additional Info:

Gradio version: 4.19.2

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

gr.Interface(
  fn=predict,
  inputs=gr.Image(shape=(28,28), imagemode='L', invertcolors=True, source='sketchpad'),
  outputs="label"
).launch()
Use code wit

```

### Screenshot

TypeError: Image.init() got an unexpected keyword argument 'shape'
I've tried looking at image demos in the Gradio documentation but none seem to be working for me. Is this a bug or am I missing something?
It also appears that many of demo apps on the documentation website are also broken for the same reason. Did any one notice that?
Additional Info:

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.19.2
gradio_client version: 0.10.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.110.0
ffmpy: 0.3.2
gradio-client==0.10.1 is not installed.
httpx: 0.27.0
huggingface-hub: 0.21.3
importlib-resources: 6.1.2
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.3
numpy: 1.26.4
orjson: 3.9.15
packaging: 23.2
pandas: 2.2.1
pillow: 10.2.0
pydantic: 2.6.3
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.10.0
uvicorn: 0.27.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.27.0
huggingface-hub: 0.21.3
packaging: 23.2
typing-extensions: 4.10.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @benkoo `shape` is not a valid argument for `gr.Image` in 4.x, see docs: https://www.gradio.app/docs/image

Which demos use this in the docs? We'll clean those up

**Comment by benkoo** [comment]
Thanks for the quick response.

The demo in the following link still uses "shape=(width,height)". It also fails to render in my browser. I also found many examples have the same problem.
 
https://www.gradio.app/guides/image-classification-in-tensorflow

**Comment by benkoo** [comment]
I changed the shape=(224, 224) parameter to width=224, height=224 in the example: https://www.gradio.app/guides/image-classification-in-tensorflow

I found that the gr.Image(width=224, height=224 ) did not actually resize the image to 224 x 224, if the image is not in this size, the demo will still fail. I had to rewrite a image resize function and include numpy to resize the image array get it to work:


```Python
import tensorflow as tf
import requests
import gradio as gr
import numpy as np
import cv2
import PIL.Image as Image

# Download human-readable labels for ImageNet.
response = requests.get("https://git.io/JJkYN")
labels = response.text.split("\n")

def resize_image(img, new_width, new_height):

    # Load image and convert to numpy array
    img_array = np.asarray(img)

    # Get original image size
    orig_height, orig_width = img_array.shape[:2]

    # Calculate scaling factor
    width_scale = new_width / orig_width
    height_scale = new_height / orig_height

    # Resize image
    resized = np.zeros((new_height, new_width, 3), dtype=np.uint8)
    for i in range(3):
        channel = img_array[:,:,i] 
        resized[:,:,i] = cv2.resize(channel, (new_width, new_height), interpolation=cv2.INTER_LINEAR)

    # Convert back to PIL image
    resized_img = Image.fromarray(resized)

    return resized_img

def classify_image(inp):
    inp = resize_image(inp, 224, 224)
    arr = np.array(inp)
    inp = arr.reshape((-1, 224, 224, 3))
    inp = tf.keras.applications.mobilenet_v2.preprocess_input(inp)
    prediction = inception_net.predict(inp).flatten()
    confidences = {labels[i]: float(prediction[i]) for i in range(1000)}
    return confidences

inception_net = tf.keras.applications.MobileNetV2()



gr.Interface(fn=classify_image,
             inputs=gr.Image(width=224, height=224),
             outputs=gr.Label(num_top_classes=3),
             examples=["images/lion.jpg", "images/truck.jpg"]).launch()
```

**Comment by hatikental99** [comment]
for updated version, replace replace 'Image.ANTIALIAS' with 'Image.Resampling.LANCZOS'
