### ISSUE TITLE
`gradio cc create` Command Fails Without Virtual Environment Due to pip Path Issue

### ISSUE THREAD

**Issue by MobisParkHeekang** [gradio-app/gradio#7621]
### Describe the bug

I encountered an issue with the `gradio cc create` command failing when executed in a global Python environment, rather than within a virtual environment. The root cause seems to be how Gradio locates the pip command.

In `gradio/cli/commands/components/install_component.py`, the `_install_command()` methods attempts to locate pip using `shutil.which("pip")`. For global python, pip is typically located at `/usr/bin/pip3`. `pip` usually refers to global python2's pip, unless you use virtual environment which override `pip` to refer to virtual environment python3. On my system, I don't use both global python2 and virtual environment, so `shutil.which("pip")` returns `None` as there's no executable named `pip`.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```bash
gradio cc create MyComponent
```
I'm using global python located at `/usr/bin/python3` and global pip located at `/usr/bin/pip3`. I make aliases `python="/usr/bin/python3"`, `pip="/usr/bin/pip3"` on `~/.bashrc`. Without those aliases, `which pip` command on bash shell fails as there's no executable named `pip` on my `PATH`.

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.19.2
gradio_client version: 0.10.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.110.0
ffmpy: 0.3.2
gradio-client==0.10.1 is not installed.
httpx: 0.27.0
huggingface-hub: 0.20.3
importlib-resources: 6.1.2
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.3
numpy: 1.26.4
orjson: 3.9.15
packaging: 23.1
pandas: 2.2.0
pillow: 10.2.0
pydantic: 2.6.1
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.2.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.27.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.27.0
huggingface-hub: 0.20.3
packaging: 23.1
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by pngwn** [comment]
`which` doesn't resolve aliases as `which` runs at a different level to shell alises.

To resolve this issue i think we do something like this:

```
- if shutil.which('pip/python')
   - use that path
- else check aliases for python/ pip  
   - use that path
- else check the `pip_path` / `python_path` cil arguments 
   - use that path
- fail noisily with a helpful message  
```

We'll need to add `--pip-path` and `--python-path` but i think this is reasonable considering clean installs will typically use `pip`, `python` but default macOS binaries are `pip3` and `python3`.

cc @freddyaboulton

**Comment by freddyaboulton** [comment]
We should probably do the same for `dev` command, e.g. add a --gradio-path for the gradio executable in case `shutil` picks up the wrong gradio executable.
