### ISSUE TITLE
accordion launches as open even when open = False since gradio 4.20

### ISSUE THREAD

**Issue by ngaudemet** [gradio-app/gradio#7633]
### Describe the bug

congrats for the work on gradio 4.20!!

a bug seems to have appeared: 
accordion launches as open even when open = False since gradio 4.20
parameter open = False seems not to work anymore

I didn't have the bug in gradio 4.17

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

 accordion = gr.Accordion(
            label="liste des fichiers",
            visible=True,
            open=False,
 )

### System Info

```shell
gradio 4.20

safari, chrome, iOS, mac : the bug is everywhere
```

### Severity

I can work around it

**Comment by pngwn** [comment]
I think #7564 should address this.
