### ISSUE TITLE
Do not support png image passing

### ISSUE THREAD

**Issue by Xiang-cd** [gradio-app/gradio#7636]
- [ x] I have searched to see if a similar issue already exists.

I ve tried using numpy, pil, filepath type to pass png images with alpha channel, but what i get in gradio was always RGB images, the information of alpha channel is loss, how can I do!
 thanks a lot !

**Comment by abidlabs** [comment]
Hi @Xiang-cd you need to set `image_mode="RGBA"` in gr.Image().

Here's an example:

```py
import gradio as gr

with gr.Blocks() as demo:
    i = gr.Image("https://image.similarpng.com/very-thumbnail/2021/06/Arabic-Calligraphy-of-Bismillah-Al-Rahman-Al-Rahim-on-transparent-background-PNG.png", image_mode="RGBA")
    t = gr.Textbox()
    demo.load(lambda x:x.shape, i, t)
    
demo.launch()
```
