### ISSUE TITLE
gr.Download Button Functionality Expansion

### ISSUE THREAD

**Issue by Solomin0** [gradio-app/gradio#7639]
- [ x] I have searched to see if a similar issue already exists.

The ability do serve files to users is great but this version is a bit rigid. This might be better as two separate FR but my main ideas would be allowing the document to be optionally downloaded as a parameter instead of forcing the download AND the file opening in browser. Being able to do either of these tasks on their own would be nice. 

The second thing that would be useful would being able to specify pdf page numbers to open to specifically.  [File URI's can support page number selection](https://stackoverflow.com/questions/75387882/is-it-possible-to-specify-a-uri-to-a-pdf-that-points-to-a-specific-page)  for pdfs so I think this combined with the ability to optionally just open the file in the browser would be very useful and make this component amazing. I see this functionality being asked for frequently with R.A.G Systems so native support would be awesome. 

If anything is unclear or I need to break this in to two feature requests lmk.

Thanks guys.

**Comment by abidlabs** [comment]
Hi @Solomin0 thanks for creating this issue.

> The ability do serve files to users is great but this version is a bit rigid. This might be better as two separate FR but my main ideas would be allowing the document to be optionally downloaded as a parameter instead of forcing the download AND the file opening in browser. Being able to do either of these tasks on their own would be nice.

This is actually not fully under Gradio's control -- it depends on the browser. We use the `download` attribute, so the intention is for the user to download the file, but if the file is a type that the browser can display (like an image or a PDF), the browser might open the file in a new tab instead of downloading it.

> The second thing that would be useful would being able to specify pdf page numbers to open to specifically. [File URI's can support page number selection](https://stackoverflow.com/questions/75387882/is-it-possible-to-specify-a-uri-to-a-pdf-that-points-to-a-specific-page) for pdfs so I think this combined with the ability to optionally just open the file in the browser would be very useful and make this component amazing. I see this functionality being asked for frequently with R.A.G Systems so native support would be awesome.

From the StackOverflow answer you provided, it seems that this only works with `file://` protocol and even then, the behavior is not very stable. Since we don't serve local files this way, I do not think that this is possible with Gradio. Instead, I'd suggest parsing the PDF in the backend, extracting the relevant page, and then displaying it, e.g using gr.Image() or `gr.DownloadButton()`.

I'll go ahead and close this issue as I do not see either of these as features we could add to the `gradio` library, but happy to continue discussing in this thread.

**Comment by Solomin0** [comment]
Using gr.Button I was able to get a desired interaction but this replaces the current gradio page. Is there any way to change this to open the link in a new tab?  
`new_feature = gr.Button("New Feature", visible = True, link = r"file\clone_directory\text_files\constitution.pdf#page=5")`

I think native support for document interaction would be interesting and the custom component for PDFs is almost there but could be built out a bit more for a full integration into native. Right now it is more of a preview tool than a true viewport for the file.

**Comment by abidlabs** [comment]
> Using gr.Button I was able to get a desired interaction but this replaces the current gradio page. Is there any way to change this to open the link in a new tab?

@Solomin0, yes you could do this with a bit of js:

```py
    btn = gr.Button("Login")
    _js_redirect = """
    () => {
        url = '/login' + window.location.search;
        window.open(url, '_blank');
    }
    """
    btn.click(None, js=_js_redirect)

```

> I think native support for document interaction would be interesting and the custom component for PDFs is almost there but could be built out a bit more for a full integration into native. Right now it is more of a preview tool than a true viewport for the file. Do you see any potential for something similar in the future?

Yes potentially. It will probably live outside of the core gradio library, but I can see that custom component being developed a bit more, or other users (maybe yourself!) creating other custom components for PDF display and manipulation.

**Comment by Solomin0** [comment]
@abidlabs I have looked at potentially modifying the component and publishing it but my JS skills are not quite up for it yet. 

In reference to this 
> @Solomin0, yes you could do this with a bit of js:
> 
> ```python
>     btn = gr.Button("Login")
>     _js_redirect = """
>     () => {
>         url = '/login' + window.location.search;
>         window.open(url, '_blank');
>     }
>     """
>     btn.click(None, js=_js_redirect)
> ```
Does rendering the raw string as code not open up to severe code injections? Correct me if i am wrong but if I want to open a variable file name I would do.
```
_js_redirect = f"""
>     () => {
>         url = '/login' + window.location.search;
>         window.open({file_name}, '_blank');
>     }
>     """
``` 
but if a user were to upload a filename that were valid js code would it not then be executed with the rest of the javascript?

**Comment by abidlabs** [comment]
It may, but I think it depends on the rest of your code, specifically how `file_name` is generated. An alternative would be to stick with gr.Button(link=), but then add some [custom js or css ](https://www.gradio.app/guides/custom-CSS-and-JS) to make links open in new tabs
