### ISSUE TITLE
Loading a Space Interface fails

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#764]
### Describe the bug

Using https://twitter.com/abidlabs/status/1447939086522757143, I tried to launch the existing interface but I got unclear error without anything actionable. Note that the original space seems to fail when running inference: https://huggingface.co/spaces/akhaliq/CLIP_prefix_captioning

### Reproduction

Run following cell

```
import gradio as gr
gr.Interface.load("spaces/akhaliq/CLIP_prefix_captioning").launch()
```

Error: ValueError: Could not load the Space: akhaliq/CLIP_prefix_captioning

### System Info

```shell
Colab
```

### Severity

critical

**Comment by FarukOzderim** [comment]
@osanseviero thanks for the report, actually this is a known issue due to the some changes in the spaces. #760 

@abidlabs @aliabid94 shall we make a new release to fix this error on the user side as well?

**Comment by abidlabs** [comment]
Yes, I will release 2.8.6 later today

**Comment by osanseviero** [comment]
FYI I tried to install from head at https://huggingface.co/spaces/osanseviero/clip_fork but still seems to have issues
