### ISSUE TITLE
[feature request] WebGL Canvas component

### ISSUE THREAD

**Issue by Vipitis** [gradio-app/gradio#7649]
- [x] I have searched to see if a similar issue already exists.
seems like Image Editor and Model3D component already use WebGL to some degree

**Describe the solution you'd like**  
I am working on a space that let's the user use language models to assist in coding fragment shaders. It would be great to have a component available that renders the result on the client.     
Currently I either render individual frames on the backend and use the image component, or some janky iFrame.
[example1](https://huggingface.co/spaces/Vipitis/ShaderCoder) [exmaple2](https://huggingface.co/spaces/Vipitis/shadermatch).
It would be lovely to have a component that simply takes valid glsl as a string. Optionally there could be controls like a pause/resume button, save screenshot, and maybe even something like mouse location.

I don't believe there is much use so it seems like a custom component to me. I got zero webdev experience myself, so it will be low priority. Perhaps you an still share any pointers if this is tagged as not planned in the end

**Comment by abidlabs** [comment]
Hi @Vipitis this is super interesting. I do agree that its quite niche and would probably serve best as a custom component at this point for maintainability reasons. I think this would be a great case for a custom component!

If you'd like to create your own, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help (I'll go ahead and close this issue, but still feel free to ask any questions here).
