### ISSUE TITLE
how to set system prompt in chatbot ?

### ISSUE THREAD

**Issue by zhidaoai** [gradio-app/gradio#7658]
hi,dear 
in the [script](https://github.com/gradio-app/gradio/blob/main/demo/chatbot_streaming/run.ipynb)
I want to insert system prompt , could you please help me?
only insert once time .
need help ,please.

**Comment by zhidaoai** [comment]
hello, dear 
could you help me ?

**Comment by freddyaboulton** [comment]
HI @zhidaoai ! Please take a look at this demo: https://huggingface.co/spaces/ysharma/Explore_llamav2_with_TGI/blob/main/app.py

 For general questions, please post in our discord https://discord.gg/hugging-face-879548962464493619
