### ISSUE TITLE
mount_gradio_app subpath mount with reverse proxy not working properly

### ISSUE THREAD

**Issue by koderx** [gradio-app/gradio#7659]
### Describe the bug

mount at `/subpath`
```python
app = gradio.mount_gradio_app(app, io, path="/subpath")
```

reverse proxy route `http://xxx.com/subpath` to `localhost:1234/subpath`
and set `x-forwarded-host` = `xxx.com`

The `/subpath` is lost in `route_util.get_root_url`
https://github.com/gradio-app/gradio/blob/6683ab2589f9d8658e1f51acc1b7526edce988d3/gradio/route_utils.py#L301
```python
# gradio.route_util.get_root_url
x_forwarded_host = request.headers.get("x-forwarded-host")
root_url = f"http://{x_forwarded_host}" if x_forwarded_host else str(request.url) 
# ^ only http://xxx.com, /subpath is missing
```

in frontend, `config.root` is `http://xxx.com` 
some route are 404
```ts
// dynamic import css
await mount_css$1(config.root + "/theme.css", document.head);
// client.ts /info
response = await fetch_implementation(`${config.root}/info`, {
```

and if `io` is `Blocks`,  `mount_gradio_app` is no way to set `root_path`, only from environment
```python
       # blocks.py  Blocks.__init__
       self.root_path = os.environ.get("GRADIO_ROOT_PATH", "")
       # routes.py App.configure_app
       self.root_path = blocks.root_path
```
or in trick
```python
with gr.Blocks() as io:
    # code

io.root_path = "/subpath" # set root_path here, but i think is so trick
app = gradio.mount_gradio_app(app, io, path="/subpath")
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
app = gr.mount_gradio_app(app, io, path="/subpath")
```
reverse proxy set `x-forwarded-host` = `xxx.com`
http://xxx.com/subpath ->  innerhost:1234/subpath

### System Info

```shell
gradio==4.21.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
I'll look into this. Just to clarify, is this a new bug in 4.21 or did you notice this in older versions of Gradio (such as 4.20.1) as well?

**Comment by abidlabs** [comment]
Hi @koderx I have a PR which exposes a `root_path` parameter in `gr.mount_gradio_app` which I think is the best way to solve this, providing maximal flexibility to the developer

If you'd like to try it, please install: https://github.com/gradio-app/gradio/pull/7667

```
pip install https://gradio-builds.s3.amazonaws.com/150999c561bc843a1b99c467265af867ecb6b9f5/gradio-4.21.0-py3-none-any.whl
```

**Comment by GitHub4LP** [comment]
Can remove the --subpath? the ComfyUI is work well.
