### ISSUE TITLE
Autostart if query parameters provided in URL

### ISSUE THREAD

**Issue by mirix** [gradio-app/gradio#7663]
- [ X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

My app outputs video. But processing is only done when a video with the same name does not already exist.

In order to enable the users to share the videos they have created, query_params can be passed in the URL:

http://server.domain:port/?ytid=h_dzbHTZHLw

If the user clicks the summit button and the input prompt is empty, the video from query_params is played.

However, I would like the video to autoplay without pressing the submit button. But only when query_params exists and is valid.

**Describe the solution you'd like**  

I would like that the videos are auto-played if query_params exists and is valid.

**Comment by abidlabs** [comment]
Hi @mirix you can do this already in Gradio:

* You can get query parameters in your prediction function by including an argument of type: `gr.Request`, see https://www.gradio.app/docs/request
* Then, in your function, you can check if query_params exists and are valid. If so, you can return a `gr.Video(/path/, autoplay=True)`. 

But note that many browsers (particularly Chromium-based ones) do not allow autoplaying videos in most cases.

**Comment by abidlabs** [comment]
By the way, for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)

**Comment by mirix** [comment]
Prior to posting here, I tried Discord, but tells me I am "suspicious" and asks my email, etc.

What you suggests is exactly what I am doing.

You still need to press the submit button, which is not what I want. 

What I want is that, if valid query parameters are present, there is no need to press the button.

**Comment by freddyaboulton** [comment]
Hi @mirix - I think you can use the `load` event to dispatch the event as soon as the page is open.
