### ISSUE TITLE
Webcam input flips after taking picture

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#767]
### Describe the bug

When I click the camera button, my image is flipped

### Reproduction

See https://huggingface.co/spaces/osanseviero/remove-bg-webcam

Code

```python
import os
os.system('pip install gradio===2.8.6')

import gradio as gr

gr.Interface.load(
  "spaces/eugenesiow/remove-bg", 
  inputs=[gr.inputs.Image(label="Input Image", source="webcam"),],
).launch()
```

### System Info

```shell
Spaces, Gradio 2.8.6
```

### Severity

annoyance

**Comment by abidlabs** [comment]
I thought this was fixed, can you take a look @dawoodkhan82?

**Comment by dawoodkhan82** [comment]
it should've been, I'll take a look

> I thought this was fixed, can you take a look @dawoodkhan82?

**Comment by pngwn** [comment]
Copying in a comment from slack.

> The mirroring issue with the webcam is kind of interesting. We are so used to seeing our webcam on meet or zoom that we think it is normal but in reality that is a mirrored view. They make this choice because people are used to seeing a mirrored view in selfies or mirrors. However, only the preview we see is mirrored, the image sent to other viewers on the call is not mirrored.

**Comment by missionfloyd** [comment]
This is happening for me on 3.16.2. `webcam_mirror` works as expected until the camera button is clicked, then it's always mirrored. It only seems to affect the displayed image; the output image is normal.
