### ISSUE TITLE
gradio.Files(file_count="multiple", type='file') not working for audios

### ISSUE THREAD

**Issue by ILG2021** [gradio-app/gradio#7671]
### Describe the bug

When I use gradio.Files to batch process audios, it gives wrong file.name which is a empty temp file, not the real file. When I upload text files, it is ok.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def process_files(files):
    output_paths = []
    for file in files:
        output_path = process_file(file)
        output_paths.append(output_path)
    return output_paths


def process_file(file):
    print("file", file.name)
    # file.name will be a empty file path when upload audios.
    return file.name


iface = gr.Interface(
    fn=process_files,
    inputs=gr.Files(file_count="multiple", type='file'),
    outputs=gr.Files(file_count="multiple", type='file'),
    title="Multi-File Processing",
    description="Upload multiple files for processing",
)

iface.launch()
```

### System Info

```shell
windows 11
python 3.10
Pycharm venv
```

### Severity

Blocking usage of gradio

**Comment by ILG2021** [comment]
I find that file.orig_name is ok.

**Comment by abidlabs** [comment]
Hi @ILG2021 which version of Gradio are you running? If you are running the latest version of Gradio (or anything 4.x), you should be able to use "file" directly (not "file.name") and it will point to the file path.

**Comment by ILG2021** [comment]
> Hi @ILG2021 which version of Gradio are you running? If you are running the latest version of Gradio (or anything 4.x), you should be able to use "file" directly (not "file.name") and it will point to the file path.

file is a tempfile object, I didn't find any way to save it or operate it.

**Comment by abidlabs** [comment]
> file is a tempfile object

This is the case in Gradio 3.x, but in 4.x, it has been changed to a string filepath. Should be easier to work with and less buggy.
