### ISSUE TITLE
Gradio Audio return None object when hosted on google colab or ec2 instance

### ISSUE THREAD

**Issue by fusesid** [gradio-app/gradio#7674]
### Describe the bug

I have a working code on my local system. But the code fails while hosting on ec2 or even trying on google colab. Gradio Audio Component return none value for both type i.e. filepath or numpy.

I am using gradio version 4.19.2.

My input is:

`audio_input = gr.Audio(sources=["microphone"],type="filepath", format="wav", show_download_button=True)
`
Also tried with:
`audio_input = gr.Audio(sources=["microphone"])
`

Function i have taken is from official Gradio Docs:

```
def transcribe(audio_input):
    print(audio_input)
    sr, y = audio_input
    y = y.astype(np.float32)
    y /= np.max(np.abs(y))

    return transcriber({"raw":y,"sampling_rate":sr},generate_kwargs={"language":"english"})["text"]
```
Also, if audio component has type = filepath

```
def transcribe(audio_input):
    print("*"*100)
    print(audio_input)
    return transcriber(audio, generate_kwargs={"language":"english"})
```

Note: if we play audio after recording than i am able to hear the audio but i am not sure why app is not taking that audio as input. It return None Type Object. I think this might be because it is not able to access filesystem or tmp directory from the server. 

What can be done for this issue? If anyone has previously faced this issue please guide me. Thank you.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
from transformers import pipeline

transcriber = pipeline("automatic-speech-recognition", model="openai/whisper-large-v3", device="cuda", torch_dtype=torch.float16)

def transcribe(audio_input):
    print("*"*100)
    print(audio_input)
    sr, y = audio_input
    y = y.astype(np.float32)
    y /= np.max(np.abs(y))

    return transcriber({"raw":y,"sampling_rate":sr},generate_kwargs={"language":"english"})["text"]

def same_auth(username, password):
    return username == password

def launch_demo(auth_fn):
    
    with gr.Blocks() as demo:
        with gr.Row():
            with gr.Column():
                audio_input = gr.Audio(sources=["microphone"], show_download_button=True)
                generated_transcript = gr.Textbox(label = "Generated Transcript", interactive=True)
                generate_transcript = gr.Button("Generate Transcript")

       generate_transcript.click(
              transcribe,
              inputs=[
                  audio_input
              ],
              outputs=[
                  generated_transcript
              ]
        )
    demo.launch(auth = auth_fn,
                  server_name= "0.0.0.0",
                  server_port = 8000
                  )  

if __name__ == "__main__":
    launch_demo(same_auth)
```

### Screenshot

![Screenshot from 2024-03-12 11-29-22](https://github.com/gradio-app/gradio/assets/138424720/90c777d8-b067-448c-8667-c44d3a218e67)
![Screenshot from 2024-03-12 11-29-48](https://github.com/gradio-app/gradio/assets/138424720/af17dfae-bec7-4174-959f-55eef173b6b9)

### Logs

```shell
****************************************************************************************************
None
Traceback (most recent call last):
  File "/home/ubuntu/asr/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/ubuntu/asr/lib/python3.10/site-packages/gradio/route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/ubuntu/asr/lib/python3.10/site-packages/gradio/blocks.py", line 1627, in process_api
    result = await self.call_function(
  File "/home/ubuntu/asr/lib/python3.10/site-packages/gradio/blocks.py", line 1173, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/ubuntu/asr/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/ubuntu/asr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/home/ubuntu/asr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/ubuntu/asr/lib/python3.10/site-packages/gradio/utils.py", line 690, in wrapper
    response = f(*args, **kwargs)
  File "/home/ubuntu/upacare-ml/clerkingservice/service/asr_clerking.py", line 23, in transcribe
    sr, y = audio_input
TypeError: cannot unpack non-iterable NoneType object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/asr/lib/python3.10/site-packages/gradio/queueing.py", line 467, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/home/ubuntu/asr/lib/python3.10/site-packages/gradio/queueing.py", line 431, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
```

### System Info

```shell
gradio==4.19.2
gradio_client==0.10.1
pydantic==2.6.3
pydantic_core==2.16.3
```

### Severity

Blocking usage of gradio

**Comment by fusesid** [comment]
Here, i had made a quick fix by utilizing audio.change(fn, inputs, outputs) method of audio component. 

And also .stop_recording(...) methods is also not working as it is also giving us None value.

While testing with change method, i found for longer audio gradio was taking time to generate event so i think this also might be the reason for getting None Object i.e. while transcribing function is hit gradio might still be processing audio and haven't completed it hence returning None Object. 

Note: I am not sure about this to be the exact reason. Just pointing this behaviour so that it might be helpful for debugging the issue. Thank you.

**Comment by abidlabs** [comment]
Thanks @fusesid for the detailed information. We'll look into this. But as this is a duplicate issue of #7582, let me close this issue and consolidate the discussion there.
