### ISSUE TITLE
Fix Security Vulnerability in Gradio App

### ISSUE THREAD

**Issue by llmwesee** [gradio-app/gradio#7676]
### Describe the bug

While attempting to run a Gradio app with or without a language model, I observed that the Gradio server makes requests to a random server IP on initial Internet connection, posing a potential vulnerability and security threat to the application. The server IP observed is something like 13.x.x.x.

This pull request addresses the security vulnerability observed while running a Gradio app with a language model. 
I need to close that external  request/connection  permanently.Please provide Solution urgently ! :')

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

# Define a simple function to process the input
def process_text(input_text):
    # In this example, the processing is just reversing the input text
    output_text = input_text[::-1]
    return output_text

# Create a Gradio interface
iface = gr.Interface(
    fn=process_text,  # Function to be called on user input
    inputs=gr.Textbox(),  # Textbox for user input
    outputs="text"  # Output display type (in this case, text)
)

# Launch the Gradio app
iface.launch()
```

### Screenshot

Eg. 13.229.31.209:443 in foreign ip in netstat command
The following ip was obeserved . 

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.14.0
gradio_client version: 0.8.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 22.1.0
altair: 5.0.1
fastapi: 0.103.0
ffmpy: 0.3.0
gradio-client==0.8.0 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.3
importlib-resources: 6.1.1
jinja2: 3.1.3
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.26.4
orjson: 3.9.10
packaging: 23.1
pandas: 2.2.1
pillow: 10.2.0
pydantic: 2.5.3
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
semantic-version: 2.8.5
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.20.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.26.0
huggingface-hub: 0.20.3
packaging: 23.1
typing-extensions: 4.8.0
websockets: 10.4
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @llmwesee - It is likely not a security vulnerability and instead it's the anonymous analytics that gradio collects so we can track usage. If you'd like to disable this, please use the `analytics_enabled=False` argument of `gr.Blocks`/`gr.Interface`/`gr.ChatInterface` or set `GRADIO_ANALYTICS_ENABLED=0` environment variable.

Going to close this for now but we can reopen if this doesn't fix your issue.

**Comment by llmwesee** [comment]
i have tried implementing this but after second run of that program it still exist . I have created a demo code to reproduce this  anonymous analytics connection. Can you recommend me how to adjust this code to resolve this issue
```
import gradio as gr

#Define a simple function to process the input
def process_text(input_text):
    # In this example, the processing is just reversing the input text
    output_text = input_text[::-1]
    return output_text

#Create a Gradio interface
iface = gr.Interface(
   analytics_enabled=False,
    fn=process_text,  # Function to be called on user input
    inputs=gr.Textbox(),  # Textbox for user input
    outputs="text"  # Output display type (in this case, text)
)

#Launch the Gradio app
iface.launch()
```
