### ISSUE TITLE
gradio Image shape None for width or height

### ISSUE THREAD

**Issue by AK391** [gradio-app/gradio#768]
As discussed the gradio Image shape tuple should be able to set (width, None) or (None, height) for setting only a width or height for resize and crop operations and scale accordingly

https://github.com/gradio-app/gradio/blob/c9298b38021323918037a5a39914a787e8517f60/gradio/processing_utils.py#L96-L113

**Comment by dawoodkhan82** [comment]
@AK391 Where is the discussion context for this issue?
