### ISSUE TITLE
Add `loop` parameter to `gr.Video()`

### ISSUE THREAD

**Issue by frances-dean** [gradio-app/gradio#7689]
Hi! 

I am loading video output using gr.PlayableVideo() and want this video to replay on loop for the demo user. It currently only plays once. Is there anyway this can be added as a feature for video components?

Thank you.

**Comment by abidlabs** [comment]
Hi @frances-dean yes we could add a parameter for this. If you're interested in opening a PR for this, we could happily review this.

**Comment by imsoumya18** [comment]
@abidlabs Can you please assign this to me? I would like to work on this.

**Comment by abidlabs** [comment]
Hi @imsoumya18 we don't formally assign issues to contributors, you are welcome to open a PR and we are happy to review it!

**Comment by hegdeadithyak** [comment]
@abidlabs As of my understand This parameter would be a boolean value named loop (with a default value of True), allowing control over looping behavior within the templates.Please let me know if this is wrong.

Thanks,
**Adithya Hegde Kota**

**Comment by qgallouedec** [comment]
Any workaround in the meantime? I've tried this, but it doesn't loop...

```python
def replay():
    return video_path

video = gr.PlayableVideo(video_path, autoplay=True, scale=1)
video.end(replay, outputs=video)
```

**Comment by rynmurdock** [comment]
I'm seeing the following work:

```
def replay(video):
    return video

video = gr.PlayableVideo(
        autoplay=True,
        include_audio=False
       )
    video.end(replay, inputs=video, outputs=video)

```
However! It looks like this causes a copy of the video (which already doesn't have audio) to be saved each loop with `muted_` appended to the filename. So I'd expect this workaround to save many, many extra files.

Cause seems to be on these lines: https://github.com/gradio-app/gradio/blob/568eeb26a90182519f491df34b1bc75ac67a7313/gradio/components/video.py#L210C9-L223C36

**Comment by rynmurdock** [comment]
Found a way to use JS to update the HTML element to loop -- will share a paired-down example.

**Comment by rynmurdock** [comment]
```
def l():
        return None

video.play(l, js='''document.querySelector('[data-testid="Lightning-player"]').loop = true''')`

**Comment by isaacyaf** [comment]
The same filename cann't be sent back immediately
Make one more copy of the file, 
for example output1.mp4 & output2.mp4

 ```
import gradio as gr

def replay(state):
    revid = "vid/output1.mp4" if state else "vid/output2.mp4"
    return revid, not state

with gr.Blocks() as demo:
    video = gr.Video(value="vid/output1.mp4", autoplay=True)
    state = gr.State(False)  

    video.end(replay, inputs=state, outputs=[video, state])

demo.launch()
```

**Comment by freddyaboulton** [comment]
Would anyone like to open a PR for this?
