### ISSUE TITLE
More Audio Playback Speeds

### ISSUE THREAD

**Issue by matmult** [gradio-app/gradio#7692]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I would like to request for more options for the gr.Audio playback speed settings. 

**Describe the solution you'd like**  
Should be pretty doable. Just expose https://github.com/gradio-app/gradio/blob/5d1e8dae5ac23f605c3b5f41dbe18751dff380a0/js/audio/shared/WaveformControls.svelte#L30

**Comment by abidlabs** [comment]
Since its a custom component you could implement it however you wish @matmult! I'll go ahead and close this, feel free to reopen @hannahblair if needed
