### ISSUE TITLE
Documentation mixup for ChatInterface and Chatbot in 4.21.0

### ISSUE THREAD

**Issue by frgfm** [gradio-app/gradio#7698]
### Describe the bug

Hello there :wave: 

I was using `ChatInterface` and customizing a few things. Checking the doc page of https://www.gradio.app/docs/chatinterface, I tried to use the `label` constructor argument which appears in the doc.
```python
import gradio as gr

gr.Chatbot(label="Test")
```
I got this error:
```
TypeError: __init__() got an unexpected keyword argument 'label'
```

I checked the doc and the documentation page of [ChatInterface](https://www.gradio.app/docs/chatinterface) is actually displaying the description and initialization of [ChatBot](https://github.com/gradio-app/gradio/blob/gradio%404.21.0/gradio/components/chatbot.py#L28) instead of [ChatInterface](https://github.com/gradio-app/gradio/blob/gradio%404.21.0/gradio/chat_interface.py#L35). 

I tried to find the problem in the docs to open a PR but I didn't manage to do it. Happy to help if you point out where it should be fixed!

Cheers

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Check out https://www.gradio.app/docs/chatinterface description and initialization on 4.21.0.
You'll notice it's actually the values of Chatbot

### Screenshot

ChatInterface
![image](https://github.com/gradio-app/gradio/assets/26927750/ac48cf7d-b398-4be5-9848-5e2f24a3a029)

Chatbot
![image](https://github.com/gradio-app/gradio/assets/26927750/2620bafc-9c80-48dc-972a-abef41e2de7d)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.21.0
gradio_client version: 0.12.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.110.0
ffmpy: 0.3.2
gradio-client==0.12.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.21.4
importlib-resources: 6.3.0
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.3
numpy: 1.26.4
orjson: 3.9.15
packaging: 24.0
pandas: 2.2.1
pillow: 10.2.0
pydantic: 2.6.4
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.10.0
uvicorn: 0.28.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.27.0
huggingface-hub: 0.21.4
packaging: 24.0
typing-extensions: 4.10.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @frgfm for reporting. This is actually the same issue as: https://github.com/gradio-app/gradio/issues/4922

@aliabd we should get this fixed asap.
