### ISSUE TITLE
Number field disabled when pushed to hugging face

### ISSUE THREAD

**Issue by heaversm** [gradio-app/gradio#7705]
### Describe the bug

If you use a number field:

`count1 = gr.Number(label="Player 1",value="0")` - you can interact with the buttons on local host. 
<img width="355" alt="image" src="https://github.com/gradio-app/gradio/assets/520541/a23f8f05-4477-4bce-b8e4-3430d6f0368e">

But when this gets pushed to a hugging face space, it sets a `disabled=""` on the field, which makes it non-interactive:

<img width="368" alt="image" src="https://github.com/gradio-app/gradio/assets/520541/634dad7d-13e5-4ee4-993d-81c1a7ebc849">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
count1 = gr.Number(label="Player 1",value="0")
```

To work around it, I have to set the property to false via javascript, which is not ideal.

### Screenshot

Attached above.

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.2.0
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.108.0
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.1
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.4
pillow: 10.2.0
pydantic: 2.5.3
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.25.0
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.26.0
huggingface-hub: 0.20.1
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @heaversm can you please provide a minimal code example (the complete Gradio app) that we can use to reproduce the issue above?

**Comment by abidlabs** [comment]
Will close for now until we have a suitable repro, but btw @heaversm you can also just add `interactive=True` instead of modifying css/js.

i.e. `gr.Number(label="Player 1",value="0", interactive=True)`

**Comment by heaversm** [comment]
Confirmed that this works. I think there was some other issue causing the disabling of these fields.
