### ISSUE TITLE
It's impossible to retrieve the 'selected_index' from 'gr.gallery' using an event listener (select)

### ISSUE THREAD

**Issue by ai-marat** [gradio-app/gradio#7708]
### Describe the bug

I have a gallery with a bunch of images, any images might be selected by cursor or pre selected by selected_index argument. But if I try take info about selected image (index) using something like 

`gallery.select(fn = show_warning, inputs = gallery)
...
def show_warning(selected_index):
    gr.Warning(f"You just choice is #{selected_index}!")
`
I 'm getting the list of all images from galley but not selected index, which looks like a bug. 

p.s. probably it's quite unique user case, but I wanted to use gallery as an gr.example component, because it has more flexibility with scale, row and columns components, if it's possible to customize gr.example I would very appreciate your help, otherwise I think there is only one option, is using a grid of gr.image which is kind of nasty and not scalable

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def show_warning(selected_index):
    gr.Warning(f"Your choice is #{selected_index}!")


with gr.Blocks() as demo:
  image_gallery = gr.Gallery(['https://unsplash.com/photos/4oaDBgVROGo/download?ixid=M3wxMjA3fDB8MXxhbGx8NHx8fHx8fDJ8fDE3MTA0NjI1MzZ8&force=true&w=640',
              'https://unsplash.com/photos/4oaDBgVROGo/download?ixid=M3wxMjA3fDB8MXxhbGx8NHx8fHx8fDJ8fDE3MTA0NjI1MzZ8&force=true&w=640',
              'https://unsplash.com/photos/4oaDBgVROGo/download?ixid=M3wxMjA3fDB8MXxhbGx8NHx8fHx8fDJ8fDE3MTA0NjI1MzZ8&force=true&w=640',
              'https://unsplash.com/photos/4oaDBgVROGo/download?ixid=M3wxMjA3fDB8MXxhbGx8NHx8fHx8fDJ8fDE3MTA0NjI1MzZ8&force=true&w=640'],
              allow_preview = False,
            preview = False, columns=[7], rows=[10])
  
  image_gallery.select(fn = show_warning, inputs = image_gallery)

demo.launch(debug = True, inline = False)

```

### System Info

```shell
latest
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @ai-marat you need to use the `gr.SelectData` object to get this data. Here's a working example of your code:

```py
import gradio as gr

def show_warning(selection: gr.SelectData):
    gr.Warning(f"Your choice is #{selection.index}, with image: {selection.value['image']['path']}!")


with gr.Blocks() as demo:
  image_gallery = gr.Gallery(['https://unsplash.com/photos/4oaDBgVROGo/download?ixid=M3wxMjA3fDB8MXxhbGx8NHx8fHx8fDJ8fDE3MTA0NjI1MzZ8&force=true&w=640',
              'https://unsplash.com/photos/4oaDBgVROGo/download?ixid=M3wxMjA3fDB8MXxhbGx8NHx8fHx8fDJ8fDE3MTA0NjI1MzZ8&force=true&w=640',
              'https://unsplash.com/photos/4oaDBgVROGo/download?ixid=M3wxMjA3fDB8MXxhbGx8NHx8fHx8fDJ8fDE3MTA0NjI1MzZ8&force=true&w=640',
              'https://unsplash.com/photos/4oaDBgVROGo/download?ixid=M3wxMjA3fDB8MXxhbGx8NHx8fHx8fDJ8fDE3MTA0NjI1MzZ8&force=true&w=640'],
              allow_preview = False,
            preview = False, columns=[7], rows=[10])
  
  image_gallery.select(fn = show_warning, inputs = None)

demo.launch()

```

**Comment by ai-marat** [comment]
@abidlabs Thank you so much for your solutions. It seems to me that I read everything in the documentation and didn't come across the 'gr.SelectData' parameter but I just found it in the guides.
