### ISSUE TITLE
Share links not working today Fri 15-Mar-24

### ISSUE THREAD

**Issue by GhostlyScript** [gradio-app/gradio#7711]
### Describe the bug

A script that previously ran fine on public URL is giving a 504 Gateway Time-out error today.

This is the public URL which Gradio is reporting that my UI is running on: edit: https://5e940ffa1ada28efd1.gradio.live/

However loading that page gives error 504 Gateway Time-out

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### Screenshot

![GradioTimeout](https://github.com/gradio-app/gradio/assets/139256353/48ffa65f-cee5-4fed-8792-faed5e37b123)

### System Info

```shell
Windows 10
Gradio installed and I was able to successfully share the same script a few days ago
Edit: Tested on both latest version of gradio 4.15.0 and on 4.13.0 and get same result.  504 Gateway timeout.
```

### Severity

Blocking usage of gradio

**Comment by dawoodkhan82** [comment]
@GhostlyScript Sorry, but our server was down for a couple hours. It should be back up and running now! Thanks for reporting the issue.

**Comment by GhostlyScript** [comment]
Yes it is working again now, thank you!
