### ISSUE TITLE
Document that `show_copy_button` in `gr.Textbox` is not visible when `show_label=False`

### ISSUE THREAD

**Issue by Solomin0** [gradio-app/gradio#7717]
### Describe the bug

Unable to use the copy button without the label also being enabled. 
Ideally if there is no room without a label the copy button would move inside of the text area of the Textbox

Not a huge deal but it does not seem like the intended functionality.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
   a = gr.Textbox(show_label = False, value = "abc",show_copy_button=True)
   b = gr.Textbox(show_label = True, value = "123",show_copy_button=True)


demo.launch()
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/37559666/e1958eae-ed12-45d0-8d1f-9f313ff259c1)

### System Info

```shell
Operating System: Windows
gradio version: 4.20.1
gradio_client version: 0.11.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.109.2
ffmpy: 0.3.2
gradio-client==0.11.0 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.3
importlib-resources: 6.1.1
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.3
numpy: 1.26.4
orjson: 3.9.14
packaging: 23.2
pandas: 2.2.0
pillow: 10.2.0
pydantic: 2.6.1
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.27.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.26.0
huggingface-hub: 0.20.3
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by shubhamofbce** [comment]
@Solomin0 This is not a bug, this is expected behavior in gradio. We don't show copy button if there are no labels in the textbox.
@abidlabs Do you think we should fix this ??

**Comment by abidlabs** [comment]
Yes I agree this is expected behavior. Getting it to work without a label seems like unnecessary effort. But we should clarify this in the docstring for the `show_label` parameter.

Let me recategorize this issue
