### ISSUE TITLE
Run gradio cc install everytime gradio cc dev is run

### ISSUE THREAD

**Issue by duerrsimon** [gradio-app/gradio#7720]
### Describe the bug

I noticed that if one has a duplicate name for a custom component one needs to install the component again using gradio cc install which is unintuitive and hard to debug. 

I think it would be best if everytime gradio cc dev is called the component is reinstalled. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

I was getting an error because I ran the component called `component_name` using gradio cc dev from `Dev/component_name` but it actually  used the python package derived from `Dev2/component_name` because I created this one afterwards (with the same name). 

### System Info

```shell
Gradio 4.21.0
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
I think this would introduce a lot of latency to the dev process. On a fresh component, it takes about 10 seconds to run which seems like a lot to avoid a corner case.

In this situation, I recommend using a virtual environment for each new component and passing the `python-path` argument to be the python executable for the env. That should keep everything isolated.

**Comment by freddyaboulton** [comment]
Closing for now but can revisit if a lot of people are running into this problem
