### ISSUE TITLE
Issue in Stopping response Streaming using Gradio Blocks and OpenAI chatbot

### ISSUE THREAD

**Issue by AniDD** [gradio-app/gradio#7723]
### Describe the bug

Using Gradio Blocks and OpenAI with streaming, attempting to stop streaming chat. 
While the chatbot with streaming functionality is working correctly, users are unable to stop the response streaming when needed.

# Define a stop flag
stop_flag = threading.Event()

# Define a callback function to set the stop flag when the button is clicked
def stop_streaming():
    stop_flag.set()

# Bot function contains:
def bot(messages):
    user_content = "Docs"
    for chunk in response:
        if stop_flag.is_set():
            # Reset the stop flag for the next search
            stop_flag.clear()                
            break            
        generated_text = chunk.choices[0].delta.content
        if history[-1][1] is None:
            history[-1][1] = ""  # Initialize with an empty string if None
        if generated_text is not None:
            history[-1][1] += generated_text
            answer += generated_text
        time.sleep(0.005)
        yield history, user_content

# Using Gradio blocks & OpenAI with streaming, Try to stop streaming chat
with gr.Blocks(theme=custom_theme, css=custom_css, title="AI Helper") as demo:
    with gr.Row():
        Prompt_Persona = gr.Textbox(label="Persona ")
    with gr.Row():
        chatbot = gr.components.Chatbot(label='Answer')
    with gr.Row():
        Prompt_Question = gr.Textbox(label='Question', autofocus=True)
        Prompt_Question.submit(user, [Prompt_Question, chatbot], [Prompt_Question, chatbot], queue=False).then(
            bot, [Prompt_Persona, Prompt_Question, chatbot], [chatbot, out_textbox_rd]
        ) 
    with gr.Row():  
        stop_btn = gr.Button("stop")
        stop_btn.click(stop_streaming, outputs=gr.Label(label="Streaming Stopped"))	
    with gr.Row(): 
        out_textbox_rd.render()

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
Windows Python 3.o
Gradio 4.21.0
```

### Severity

Blocking usage of gradio

**Comment by AniDD** [comment]
Please check on "stop streaming" as mention above.
Your assistance is highly appreciated. Thanks.

**Comment by freddyaboulton** [comment]
Hi @AniDD - this kind of question is better suited to our discord (https://discord.gg/hugging-face-879548962464493619). I think you need to pass the `threading.Event` argument to both the start and stop functions via `gr.State`. I think someone should be able to help you out better on the discord.

**Comment by AniDD** [comment]
sure, thanks.

**Comment by AniDD** [comment]
Not able to continue with link
https://discord.gg/hugging-face-879548962464493619
Giving error, invite invalid.

Thanks.
