### ISSUE TITLE
Remaining bug from #7317 - file path resolution wrong

### ISSUE THREAD

**Issue by skye0402** [gradio-app/gradio#7724]
### Describe the bug

With the correction of bug #7317 it's possible again from release 4.21.0 to work behind an application router. That's great. I recently discovered that the file path for pictures in a chatbot interface (at least that, maybe others as well) is not correct. Can you fix it?

Running local:
<img width="1580" alt="image" src="https://github.com/gradio-app/gradio/assets/36907475/753c89f4-eca8-421b-beb1-0a5c46e20d1f">
No issues. As you can see the path looks correct.

Running behind approuter:
<img width="1853" alt="image" src="https://github.com/gradio-app/gradio/assets/36907475/9846cebe-a8b8-46ef-addd-65c07aed16f4">

The issue is the URL. 

Used in the first reference:
`https://apachat.c-290ae5b.kyma.shoot.live.k8s-hana./file=/tmp/gradio/8002ab707d333733cb66b8e9241218143955df1d/20220922063344.jpeg`

Used in the second reference:
`https://apachat.c-290ae5b.kyma.shoot.live.k8s-hana.o/file=/tmp/gradio/8002ab707d333733cb66b8e9241218143955df1d/20220922063344.jpeg`

Correct:
`https://apachat.c-290ae5b.kyma.shoot.live.k8s-hana.ondemand.com/file=/tmp/gradio/8002ab707d333733cb66b8e9241218143955df1d/20220922063344.jpeg`

Somehow the last 2 parts of the domain name are cut off. Interesting is that the first is cut after the dot while the second shows the "o" of "ondemand". Can you check that please?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
Gradio 4.21.0 (upgraded from 4.16.0 where it still worked).
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Thanks @skye0402 that's super weird but I'll look into it. Can you share a quick code snippet sharing how you're supplying the images to the chatbot so that I can repro the same on my end?

**Comment by abidlabs** [comment]
I'm having a bit of a hard time reproducing this. Here's the code I tried:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Chatbot([
        ("abc", ("panda.jpg", )),
    ])


demo.launch(root_path="/8044")
```

Running behind a proxy here just fine: http://35.85.61.147/8044/

Let me know if you can share any more details that could help us repro!

**Comment by liangjs** [comment]
I ran into the same issue. The host name is somehow truncated.

> Running behind a proxy here just fine: http://35.85.61.147/8044/
> 
> Let me know if you can share any more details that could help us repro!

Can you try to run the service behind a reverse proxy with a host name?

**Comment by skye0402** [comment]
@abidlabs 

Just a code snippet - if this doesn't help I need to build a separate simple setup to show:

```
def user(state, user_message, imagebox, image_process_mode, history):
    """ Handle user interaction in the chat window """
    state["skip_llm"] = False
    state["imageBase64"] = []
    if len(user_message) <= 0 and imagebox is None:
        state["skip_llm"] = True
        return "", history, None
    if imagebox is not None:
        user_message = user_message[:1200]  # Hard cut-off for images
        state["imageBase64"] = get_image(image=imagebox, image_process_mode=image_process_mode)
        history = history + [((imagebox,), None)]
    rv =  "", history + [[user_message, None]], None
    return rv
```
`history + [[user_message, None]]` is passed back to the Chatbot. Let me know if that helps.

**Comment by rwb-truelime** [comment]
Running into this issue on Azure cloud (container instances). The output images get served with a corrupted url on the Azure domain of container instances (...azurecontainer.io --> ...azurec).

Gradio container is running on localhost serving to a Caddy reverse-proxy, [learn more about this config here.](https://learn.microsoft.com/en-us/azure/container-instances/container-instances-container-group-automatic-ssl)

You can check out the instance here:

https://tl-clipdemo.westeurope.azurecontainer.io/

Try searching for "A tiger walking", we are testing CPU based searching on CLIP embeddings. Results will take about 25 seconds. The output urls are truncated on the domain name (hostname), for example:

` ` `https://tl-clipdemo.westeurope.azurec/file=/root/cache/9aa0715d22dad0cdf6fd23123db59262368fb0e6/image.png` ` `

Should be:

` ` `https://tl-clipdemo.westeurope.azurecontainer.io/file=/root/cache/9aa0715d22dad0cdf6fd23123db59262368fb0e6/image.png` ` `

### Thanks for looking into this!

**Comment by rwb-truelime** [comment]
> I'm having a bit of a hard time reproducing this. Here's the code I tried:
> 
> ```python
> import gradio as gr
> 
> with gr.Blocks() as demo:
>     gr.Chatbot([
>         ("abc", ("panda.jpg", )),
>     ])
> 
> 
> demo.launch(root_path="/8044")
> ```
> 
> Running behind a proxy here just fine: http://35.85.61.147/8044/
> 
> Let me know if you can share any more details that could help us repro!

Please try this with a hostname, not an IP address.

**Comment by abidlabs** [comment]
Hi @liangjs @skye0402 @rwb-truelime I just added some logging to Gradio -- if you install this version of Gradio, it should print some stuff to your terminal. Would you be able to please install and let me know what is printed to your terminal?

`pip install https://gradio-builds.s3.amazonaws.com/a3b519f2e78b5ac8acd5b3b6c52f357eed59330e/gradio-4.22.0-py3-none-any.whl`

**Comment by liangjs** [comment]
> ```
> pip install https://gradio-builds.s3.amazonaws.com/ba3ac976918be4aec67b02baca37459e64537c33/gradio-4.22.0-py3-none-any.whl
> ```

I don't know why it prints nothing in my log, but with this patch the image url works fine for me.

**Comment by abidlabs** [comment]
Ok good to hear, we'll get the PR in soon!

**Comment by rwb-truelime** [comment]
Thanks! 🚀
