### ISSUE TITLE
Pasting images into Multimodal ChatInterface

### ISSUE THREAD

**Issue by recursionbane** [gradio-app/gradio#7751]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Multimodal/image support in `ChatInterface` just landed! Big thanks to @dawoodkhan82 for this.
Would it be possible to add clipboard paste support to ease common interactions like chatting with LLMs about screenshots?

**Describe the solution you'd like**  
Pasting an image into the text entry field when `multimodal=True` should transfer the clipboard content and store it exactly how an uploaded file would be stored in `/tmp/...` on the Gradio server host.

**Comment by dawoodkhan82** [comment]
Makes sense to add. Will look into it.
