### ISSUE TITLE
gradio private in colab

### ISSUE THREAD

**Issue by ReshefMaati** [gradio-app/gradio#7760]
i see some issue relate to this problem.
i write it in a comment to this close issue:
https://github.com/gradio-app/gradio/issues/414

private link not enable in colab, and i see that Phoenix implement this option, i mean the authentication for running on colab compute and i'd be happy if you do the same way

**Comment by ReshefMaati** [comment]
here an simple example in video

https://github.com/gradio-app/gradio/assets/105783111/7598dff2-8998-40a4-bd1d-99d5e99be067

**Comment by freddyaboulton** [comment]
HI @ReshefMaati ! I don't think I follow. Looks like Phoenix is also creating a public link so that the demo shows up in the colab.

**Comment by ReshefMaati** [comment]
look the url that created, its related to colab compute then i think it authenticate to colab user. 
when i open from another tab with no colab user log-on its show an error

https://github.com/gradio-app/gradio/assets/105783111/aa690812-9a69-46fc-8ef3-71fffffc9ef6

**Comment by freddyaboulton** [comment]
Ok interesting! Thanks for the pointer @ReshefMaati !

**Comment by abidlabs** [comment]
Sorry I don't understand the issue. @ReshefMaati would you be able to provide a minimal code example that we can use to reproduce the issue? And share what you expect vs. what you see?

**Comment by ReshefMaati** [comment]
I clarify my request.
in 2021 in this issue https://github.com/gradio-app/gradio/issues/414 someone suggested to enable shared=False in colab.
your answer - @abidlabs was:
"Is there a different way that you have in mind that would allow your demo on colab to be accessible to you but remain otherwise private? If so, we can implement it"

so i add some tool (Phoenix) that implement that exactly. you can see in the videos. you run the session and open it in new tab and it open privatly on your compute and i think that there is auth with colab user:

you can run the 3 first cells in this code for example:
https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/llama_index_tracing_tutorial.ipynb

**Comment by abidlabs** [comment]
Ah I see thanks @ReshefMaati. We actually used to do this approach (of using service workers to serve requests from localhost) on Google Colab. However, service workers do not support server-side events, which are used heavily in Gradio, so we no longer support this feature.
