### ISSUE TITLE
Multimodal Textbox appearance and spacing is different for different prebuilt themes

### ISSUE THREAD

**Issue by yvrjsharma** [gradio-app/gradio#7766]
### Describe the bug

For example (also please refer the attached screenshots): 
- In Monochrome, the 'add file' and 'send file' icons are slightly off from the vertical center. 
- In Soft, both the 'add file' and 'send file' icons are not highlighted like in the rest of the themes (a heavy colored circle). Not sure if this is the expected behavior. 

Noticed this and a few other things while demoing with @abidlabs. Will create a couple more issues. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Monochrome
```python
import gradio as gr
def dummy(mm):
  text = mm['text']
  img = mm['files'][0]['path']
  return text, img

with gr.Blocks(theme=gr.themes.Monochrome()) as demo:
  gr.HTML('<h1><center>Multimodal Textbox</center></h1>')
  mm_input = gr.MultimodalTextbox(interactive=True, file_types=["image"], placeholder="Enter message or upload file...", show_label=False)
  with gr.Row():
    ta = gr.TextArea(label='Multimodal text')
    img = gr.Image()
  mm_input.submit(dummy, mm_input, [ta, img])

demo.launch(debug=False)
```

Soft:
```python
import gradio as gr
def dummy(mm):
  text = mm['text']
  img = mm['files'][0]['path']
  return text, img

with gr.Blocks(theme=gr.themes.Soft()) as demo:
  gr.HTML('<h1><center>Multimodal Textbox</center></h1>')
  mm_input = gr.MultimodalTextbox(interactive=True, file_types=["image"], placeholder="Enter message or upload file...", show_label=False)
  with gr.Row():
    ta = gr.TextArea(label='Multimodal text')
    img = gr.Image()
  mm_input.submit(dummy, mm_input, [ta, img])

demo.launch(debug=False)
```

### Screenshot

Monochrome theme:

![image](https://github.com/gradio-app/gradio/assets/48665385/a53ea797-ffe2-44d2-a081-fd23b968739f)

Soft theme:

![image](https://github.com/gradio-app/gradio/assets/48665385/a42687f5-36e0-4419-9b4a-7e2912d87bd4)

### System Info

```shell
Google Colab
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
I agree the monochrome one needs to be fixed, cc @dawoodkhan82

**Comment by dawoodkhan82** [comment]
Ah good catch @yvrjsharma
