### ISSUE TITLE
Cannot disable queue for Blocks no matter how I specify it

### ISSUE THREAD

**Issue by asobh-ep** [gradio-app/gradio#7773]
### Describe the bug

No matter what I do, I cannot disable the queue functionality. I have tried:

```
demo = gr.Blocks()
demo.enable_queue = False
demo.config["enable_queue"] = False

with demo:
    ... interface code goes here
```

Of course, I can increase the concurrency limit to a high number. But it just seems odd / a bug that I can't disable the queue when the functionality is intended to be there.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

demo = gr.Blocks()
demo.enable_queue = False
demo.config["enable_queue"] = False

with demo:
    ... interface code goes here
```

### System Info

```shell
Gradio 4.22.0
```

### Severity

I can work around it

**Comment by LukeWarnut** [comment]
This should fix it:
```
demo.queue = False
demo.config["queue"] = False
```

**Comment by abidlabs** [comment]
Hi @asobh-ep, in Gradio 4.x, we actually require the queue for all events. If you need to disable for a specific event, you can set `queue=False` in that particular event trigger.

**Comment by zolero** [comment]
@abidlabs  Don't forget that quiet some cloud services need to support all those new messaging protocols as well, I'm having issues on [Modal](https://modal.com) where gradio doesn't work well on. EventStreams / Websockets etc etc. or other reverse proxy related issues.

**Comment by abidlabs** [comment]
@zolero as far as I’m aware, Modal has added support for websockets specifically citing Gradio 3.x. In Gradio 4.0, we switched to SSE specifically for this reason since SSE is just a type of HTTP request, which should be supported essentially everywhere
