### ISSUE TITLE
gradio-4.22.0 broken ngrok tunneling 

### ISSUE THREAD

**Issue by FurkanGozukara** [gradio-app/gradio#7774]
The images are not displayed in 4.21 or in 4.22

however in 4.19 they are working

first image is 4.22

![image](https://github.com/gradio-app/gradio/assets/19240467/2b638346-981a-4fb3-9858-03aedb674553)

second image is 4.19

![image](https://github.com/gradio-app/gradio/assets/19240467/2e35475f-e1bb-4f19-82a8-84b5c1990183)

**Comment by abidlabs** [comment]
@FurkanGozukara what errors do you see in the console log?

**Comment by FurkanGozukara** [comment]
@abidlabs this is the only error

![image](https://github.com/gradio-app/gradio/assets/19240467/5b286ce7-35ce-4d2d-9e45-4117122a2e86)

![image](https://github.com/gradio-app/gradio/assets/19240467/fa20f6c1-f0fd-48bd-9bb9-ad7129c6bdec)

**Comment by abidlabs** [comment]
Hi @FurkanGozukara I just added some logging to Gradio -- if you install this version of Gradio, it should print some stuff to your terminal. Would you be able to please install and let me know what is printed to your terminal when you run your app?

`pip install https://gradio-builds.s3.amazonaws.com/a3b519f2e78b5ac8acd5b3b6c52f357eed59330e/gradio-4.22.0-py3-none-any.whl`

**Comment by FurkanGozukara** [comment]
> Hi @FurkanGozukara I just [added some logging to Gradio](https://github.com/gradio-app/gradio/pull/7787) -- if you install this version of Gradio, it should print some stuff to your terminal. Would you be able to please install and let me know what is printed to your terminal when you run your app?
> 
> ```
> pip install https://gradio-builds.s3.amazonaws.com/ba3ac976918be4aec67b02baca37459e64537c33/gradio-4.22.0-py3-none-any.whl
> ```

hello worked no issues @abidlabs 

![image](https://github.com/gradio-app/gradio/assets/19240467/b0a91185-baf1-4222-9fed-8c6d5d88f07a)

**Comment by abidlabs** [comment]
Nice! Will get the PR out soon but for not you can keep using that version of Gradio
