### ISSUE TITLE
[Responsible AI] Give users the ability to opt for a spectrum of outputs, as opposed to a single inference.

### ISSUE THREAD

**Issue by dynamicwebpaige** [gradio-app/gradio#778]
## ✍️  Issue Description
**Is your feature request related to a problem? Please describe.**
Super-resolution models, which take low-res images as inputs and output images of a much higher resolution, are often fraught with bias; as are computer vision models, in general (please refer to the work of Meg Mitchell, Timnit Gebru, et al).

In a recent example showcased on Twitter, a low-res image of former President Barack Obama, when used as an input to Face Depixelizer, was "upscaled" as a Caucasian man:

![image](https://user-images.githubusercontent.com/3712347/156815404-508fe70c-e27d-4758-8d0b-32e512936c09.png)

## 🙏  Feature Request
**Describe the solution you'd like**

It would be *awesome* if Gradio gave users the option to output a spectrum of potential "upscaled" images for their GAN models, similar to the techniques detailed in [_Explorable Super Resolution_ (2020)](https://arxiv.org/pdf/1912.01839.pdf). Rather than seeing just one output, with the assumption that it is deterministic, users would be able to see the variance in potential outputs and select one for their use case.

<img width="421" alt="Screen Shot 2022-03-04 at 9 46 42 AM" src="https://user-images.githubusercontent.com/3712347/156815866-0cf43d0a-3a58-4bd8-be4a-ae34d1d92aca.png">

**Additional context**
[Tweet from 3 March.](https://tfhub.dev/captain-pool/esrgan-tf2/1)

**Comment by FarukOzderim** [comment]
Great suggestion, thanks we are looking into it 👍

**Comment by pngwn** [comment]
This is interesting, the current/in-flight blocks work will easily support multiple inputs to an output but we haven't really discussed multiple outputs from a single 'input'.

Thinking about it, I don't think the current blocks API would support this, so we would need some specific API for this (could be mistaken). This also feels like a useful enough usecase that we could create a 'flow' or shorthand abstraction (something we have discussed previously @abidlabs @aliabid94 @aliabd) to make it simpler for users without needing to use blocks directly, or maybe an extension of the interface class.

As far as I understand it, we need some way of breaking the output of a predict fn up and spreading it across multiple instances of the same component (maybe there are use-cases for spreading the processed output across _different_ types of component too?). I think we need to figure out how we might express this in terms of blocks and then we can build a simple abstraction for it either by expanding interface or some other 'flow' or abstraction.

**Comment by FarukOzderim** [comment]
We actually have multiple outputs in the api, we provide them as a list, but not sure about its functionality, @abidlabs and @aliabid94 could clarify it more.

But we could use multiple variables returned from the target function right?

**Comment by dynamicwebpaige** [comment]
@FarukOzderim That sounds like it could work! As another example of this kind of functionality, in the wild - GitHub's Copilot gives users the ability to view a subset of 10 potential source code completion results, accessible in VS Code through the command palette (`Ctrl + Shift + P`). Image below from IntelliJ:

![image](https://user-images.githubusercontent.com/3712347/156894130-4d8f8c53-c45e-41e9-ab43-ca9151a5238d.png)

**Comment by abidlabs** [comment]
Yes as @FarukOzderim pointed out, we do support a multiple outputs with `gradio.Interface`. If a function returns multiple values, those values can be assigned to multiple output components by providing the output components (of the same type or different types) as a list. As a quick example:

```python
import gradio as gr

def multiple_rotations(image):
      return image.rotate(45), image.rotate(90), image.rotate(180)

gr.Interface(multiple_rotations, gr.inputs.Image(type="pil"), ["image", "image", "image"]).launch()
```

![image](https://user-images.githubusercontent.com/1778297/156901038-f9bfd79c-59f7-4252-8854-5c65ef168071.png)

Does this address your use case @dynamicwebpaige and @pngwn? Or do you envision a nicer way to show multiple outputs?

For example, if the number of outputs is a lot, like the 6 images shown in Paige's original screenshot, then I think it can get a little unwieldy so we really should support an grid-of-images-type component as brought up in #750

**Comment by dynamicwebpaige** [comment]
@abidlabs Multiple outputs -- building on the concept of [_small multiples_](https://en.wikipedia.org/wiki/Small_multiple) -- would be ideal; similar to the image below, [which details a grid layout from Shiny](https://shiny.rstudio.com/articles/layout-guide.html):

![image](https://user-images.githubusercontent.com/3712347/156902147-fdb37fad-7478-4507-969c-3b24dc6e1101.png)

Plotly also supports grid outputs, though I believe it might only be for [interactive plots](https://plotly.com/python/plotly-express/):

<img width="460" alt="Screen Shot 2022-03-05 at 2 48 01 PM" src="https://user-images.githubusercontent.com/3712347/156902273-e0ff5c4e-fb78-46fc-b677-5b24bc7666cc.png">

**Comment by abidlabs** [comment]
Thanks for the suggestion and discussion folks. outputting a grid of images is very easy to do with the [Gallery component](https://gradio.app/docs/#gallery), so closing this issue. If there are other use cases that are not possible with the Gallery component, feel free to reopen
