### ISSUE TITLE
Error when using Gradio 4.18.0+ with docker and nginx

### ISSUE THREAD

**Issue by DiveGuillaume** [gradio-app/gradio#7792]
### Describe the bug

Gradio does not work with `nginx` and `Docker`, when I use version `4.18.0+`. There are CSS display problems, but the most blocking is that I cannot upload images, and therefore use the submit button to process these images. 

However, using version `4.17.0` fixes the issue **without changing anything else**. 

> I've seen some issues about how using `root_path=XXX` might be a good idea, but it doesn't change anything. 
> In the last screenshot it is possible to notice that the port (here 8080) is not in the request for `http://127.0.0.1/gradio_ui/theme.css`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

#### My Gradio interface 

The `processing_function` can be anything here, as long as it takes two images as input and provides two images and one text as output

```python
def run_server(self, url='127.0.0.1', port=8888):
    interface = gr.Interface(fn=processing_function,
                             inputs=[gr.Image(),
                                     gr.Image()],
                             outputs=[gr.Image(),
                                      gr.Image(),
                                      gr.Text()],
                             title="Gradio interface"
                             )

    interface.queue().launch(root_path="/gradio_ui/", server_port=port, server_name=url, share=False)
```

#### Nginx configuration  

```
events {
    worker_connections 1024;
}


http {
    server {
        listen 80 default_server;
        resolver 127.0.0.11;
        location ~ ^/gui/(.*)$ {
            set $upstream gui:8877;
            proxy_pass http://$upstream/$1$is_args$args;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_buffering off;
        }

        location ~ ^/gradio_ui/(.*)$ {
            proxy_pass http://gui:8877/gradio_ui/$1$is_args$args;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_buffering off;
        }
    }
}
```

#### docker-compose
```
version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gui

  gui:
    image: gradio_gui
    build:
      context: .
      dockerfile: Dockerfile
    command: python app.py gui --url=0.0.0.0 --port=8877 
```

#### Dockerfile
```
FROM python:3.12

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
```

#### Requirements 
```
werkzeug==3.0.1
flask==3.0.2
opencv-python==4.9.0.80
numpy==1.26.4
scikit-image==0.22.0
flask-restx==1.3.0
requests==2.31.0
gradio==4.17.0 # <- 4.18.0
```

### Screenshot

![Screen Shot 2024-03-22 at 15 29 45 PM](https://github.com/gradio-app/gradio/assets/76689313/6e1490c9-bfe4-4b1e-b63c-07c95f0ed4bf)

![Screen Shot 2024-03-22 at 15 29 54 PM](https://github.com/gradio-app/gradio/assets/76689313/641d8af7-f6f3-4f91-b6dd-bbb9cf5d5434)

![Screen Shot 2024-03-22 at 15 30 00 PM](https://github.com/gradio-app/gradio/assets/76689313/48d4f059-fe6d-434a-a7ac-e2f01ae8c2ed)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.17.0
gradio_client version: 0.9.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.110.0
ffmpy: 0.3.2
gradio-client==0.9.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.21.4
importlib-resources: 6.3.0
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.3
numpy: 1.26.4
orjson: 3.9.15
packaging: 24.0
pandas: 2.2.1
pillow: 10.2.0
pydantic: 2.6.4
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.3
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.10.0
uvicorn: 0.28.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.27.0
huggingface-hub: 0.21.4
packaging: 24.0
typing-extensions: 4.10.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @DiveGuillaume we've recently fixed some issues related to root_path. Can you try the latest version of `gradio` from `main`.

You can install gradio from main by following the instructions here: https://www.gradio.app/main/docs/interface

**Comment by DiveGuillaume** [comment]
Hi @abidlabs !

Thank you for the answer. I just tried by adding in my Dockerfile (and removing the corresponding mention from the requirement.txt):

```
RUN pip install https://gradio-builds.s3.amazonaws.com/781678b3ac0e44ea1401ff55af3e98b474cf36ec/gradio-4.22.0-py3-none-any.whl
```

**The error persists**. Here are the screenshots of the errors I get when uploading an image:
<img width="1695" alt="Screenshot 2024-03-23 at 00 21 13" src="https://github.com/gradio-app/gradio/assets/76689313/482a9939-3174-4377-891d-a9449f060d54">

> I have the impression that the fact that the port is not specified after `http://localhost` causes the problem

In addition, as stated in my first post, going back to version `4.17.0` fixes the problem.

**Comment by abidlabs** [comment]
Can you try changing:

            proxy_set_header Host $host;

to 


            proxy_set_header Host $http_host;

in your nginx configuration?

**Comment by DiveGuillaume** [comment]
The problem is **solved**, thank you very much for your answers and your help !

**Comment by abidlabs** [comment]
Great! I'll go ahead and close this issue.
