### ISSUE TITLE
minimum demo not working

### ISSUE THREAD

**Issue by xudong2019** [gradio-app/gradio#7793]
### Describe the bug

I have a minimum version  running on my ubuntu server,  and I am connecting to server through vscode with port forwarded . The code is very simple, but the browers gives no response at all. I suspect there is something to do with my browser, I tried both edge and chrome, including in-private mode, none of which works.  Anyone can give me a hand ?

import gradio as gr

def greet(name, intensity):
    return "Hello " * intensity + name + "!"

demo = gr.Interface(
    fn=greet,
    inputs=["text", "slider"],
    outputs=["text"],
)

demo.launch()

root@autodl-container-ab3148b991-9afd9637:~/autodl-tmp/LLaMA-Factory# python test.py
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

![image](https://github.com/gradio-app/gradio/assets/16278392/59096eae-6928-42eb-83d1-25077f70e6ec)
![image](https://github.com/gradio-app/gradio/assets/16278392/4277fa29-8d23-44ef-a9c2-9eb8362c7728)
![image](https://github.com/gradio-app/gradio/assets/16278392/0f1af6eb-236d-436c-96b1-368157516610)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def greet(name, intensity):
    return "Hello " * intensity + name + "!"

demo = gr.Interface(
    fn=greet,
    inputs=["text", "slider"],
    outputs=["text"],
)

demo.launch()

```

### System Info
gradio environment
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.22.0
gradio_client version: 0.13.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.110.0
ffmpy: 0.3.2
gradio-client==0.13.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.21.4
importlib-resources: 6.4.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.3
orjson: 3.9.15
packaging: 23.2
pandas: 2.2.1
pillow: 10.2.0
pydantic: 2.6.4
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.4
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.29.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.

gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.27.0
huggingface-hub: 0.21.4
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @xudong2019 if I understand correctly, gradio is running on your ubuntu server's localhost:7860. Have you port-forwarded that port to your local computer's localhost:7860?

**Comment by abidlabs** [comment]
Closing for now, but happy to answer follow up questions in the thread.
