### ISSUE TITLE
Unable to debug error

### ISSUE THREAD

**Issue by samarth70** [gradio-app/gradio#78]
I am trying to understand the error in my code (which was working fine a few days back), but not able to find the error. The function is returning image fine if used separately without Gradio.
So, if there is an error why is it not debugging?

![issue1](https://user-images.githubusercontent.com/44370096/99143270-47f96f80-2684-11eb-9194-7f5680ff2f0b.jpg)
![issue2](https://user-images.githubusercontent.com/44370096/99143271-4a5bc980-2684-11eb-9652-c8fa53ce665b.jpg)

**Comment by abidlabs** [comment]
Hi @samarth70 would you be able to share a link to your colab notebook or some code to help us reproduce the issue?

**Comment by samarth70** [comment]
Is there any alternative? I am not wishing to share code at the moment.
Pls, explain why is there no traceback for the error?

**Comment by samarth70** [comment]
If reason could be high latency in my code i.e it’s taking a long time to process.Can u give a solution to fix it?

>

**Comment by Zafershah24** [comment]
Yes there is a problem with High Latency, if your ML model takes too long to process, then gradio throws an error. 
Any Fix for that?

**Comment by abidlabs** [comment]
Hi @samarth70, it's hard for us to offer more information without knowing some more details. Can you share with us another example (without sensitive code) to help us reproduce this problem? Closing for now, but feel free to open with additional details.

**Comment by strickvl** [comment]
I'm having a similar issue. My gradio embed inside a Colab notebook isn't working and just gives me 'error'. Not really too useful for debugging.

**Comment by abidlabs** [comment]
Have you tried setting the parameter `debug=True` in `launch()`? Then it should print the traceback

**Comment by strickvl** [comment]
> Have you tried setting the parameter `debug=True` in `launch()`? Then it should print the traceback

Thank you that's a useful tip!

**Comment by scheung38** [comment]
Hi @here, I have:

if __name__ == "__main__":
    demo.queue()
    demo.launch(share=True, height=1500, debug=True)  
    
But
breakpoint is not observed
Height is the same as default 500?

Also could someone point out why return history, history instead of just once? Is this same the case of is this old syntax?

**Comment by ndvbd** [comment]
Is there a way to force Gradio to somehow run the logic on the main process so breakpoints will be caught?

**Comment by thiswillbeyourgithub** [comment]
> Is there a way to force Gradio to somehow run the logic on the main process so breakpoints will be caught?

I'm wondering the same thing, it's hard to debug at times
