### ISSUE TITLE
Gradio Client ignores `download_files` (and returns unattainable file path)

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#7804]
### Describe the bug

If I use a Gradio Client on a Hugging Face Space with a `gr.Gallery` or `gr.Image`, it ignores the `download_files` flag and returns me the file path on the remote machine.

More problematically, if I run the Gradio client from my own personal local machine, the filepath I obtain is of this structure:
`/private/var/folders/th/wdnzlf_j24x8jzc8mdlkmmdc0000gn/T/gradio/413057dffb9c186cc4be034e7ce7dfef5be92aea/image.png`

Which does not allow me retrieve the image:
`https://my-example-demo.hf.space/--replicas/dldwj/file=/private/var/folders/th/wdnzlf_j24x8jzc8mdlkmmdc0000gn/T/gradio/ba42be13d0fbe456bdd2c685d3de6460a75b1c95/image.png` - essentially locking me out the generated image, as I get unauthorised access to the `/private` folder.

If I run Gradio Client from a public URL (e.g.: Google Colab) I get the output in the structure of 
`/tmp/gradio/58c4e521692f4b704cd831f581b4ecc55a4c76ae/image.png` which dos allow me to obtain from my replica URL

But ideally, I'd want to avoid this entirely by having `download_files` available, or the return to be base64

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
replica_url = "https://multimodalart-ip-adapter-faceid.hf.space/--replicas/dldwj/"
client = Client(replica_url, download_files=True)
image_path = "me.jpg"
prompt = "a pirate"
output_image = client.predict([image_path],
         prompt,
         "",
         True,
         0.2,
         1.0,
         "",
         api_name="/generate_image")
```
(Here output image will be a list with 4 items with a path)

### System Info

```shell
gradio_client==0.13.0
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @apolinario the files you get from the client are on your local machine. I just verified with this space (very cool btw)!

**Comment by apolinario** [comment]
Ah 🤦, thank you!
