### ISSUE TITLE
Does Gradio support setting background images for websites based on it?

### ISSUE THREAD

**Issue by YueXingZe** [gradio-app/gradio#7805]
Does Gradio support setting background images for websites based on it? I tried adding CSS code but it didn't seem to work for achieving this functionality.

**Comment by shubhamofbce** [comment]
Yes Try custom themes. https://www.gradio.app/guides/theming-guide
Let me know if you face any issues in themes.

**Comment by abidlabs** [comment]
Thanks @shubhamofbce! Yes custom themes is the ideal solution. By the way, for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
