### ISSUE TITLE
private space not show on huggingface

### ISSUE THREAD

**Issue by Mon-ius** [gradio-app/gradio#7808]
### Describe the bug

private space not show on huggingface and could be solved ezly by making it public. 

Main thing I think is `space.hf.co/theme.css` can not be accessed from outside.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Just a demo.
```python
import gradio as gr

def greet(name):
    return "Hello " + name + "!!"

iface = gr.Interface(fn=greet, inputs="text", outputs="text")
iface.launch()

```

### System Info

```shell
Just a very simple huggingface starter, 


---
title: demo
emoji: 🏢
colorFrom: pink
colorTo: green
sdk: gradio
sdk_version: 4.22.0
app_file: app.py
pinned: false
license: apache-2.0
---
```

### Severity

Blocking usage of gradio

**Comment by Mon-ius** [comment]
It can be simply tested by turn a public space into private, then `hf.space/assets/index-ec890757.js`, `hf.space/theme.css` and etc will return 404 🤗

**Comment by freddyaboulton** [comment]
Hi @Mon-ius - maybe hard refresh and/or clear your cookies. I just tried this and it works for me. I will relay this internally but I will close as it's not an issue with the core gradio library.

**Comment by Mon-ius** [comment]
wait a minute plz, it was on the org private space, not personal one

**Comment by Mon-ius** [comment]
Hi @freddyaboulton

Thx for inspiration. 

I use `MS Edge` to test and it works. But on `Google Chrome`, not work so far.

And I found the root cause that, `https://xxxx.hf.space/assets/index-ec890757.js` that has no `spaces-jwt` inside the cookie. PS: not the main space domain, but `xxx.hf.space`.

I migrate the cookie from `MS Edge` to `Google Chrome`, and it shows correctly.

**Comment by Mon-ius** [comment]
Think might because some `cross origin policy` related setting was enabled in Chrome
