### ISSUE TITLE
Gradio REST API

### ISSUE THREAD

**Issue by bstraehle** [gradio-app/gradio#7809]
Greetings,

Thanks for supporting Gradio, I love it.

I'd like to request a new feature, a **REST API** in addition to the Python and JavaScript APIs.  REST APIs can be consumed from virtually any client.

For example, see Hugging Face space [bstraehle/openai-llm-rag](https://huggingface.co/spaces/bstraehle/openai-llm-rag) and click on "use via API" at the bottom.

Thanks,

Bernd

**Comment by gibiee** [comment]
@bstraehle 
I'm not sure if I understand your intention correctly, but isn't it possible to use REST API by integrating Gradio and FastAPI?

References:
- https://www.gradio.app/guides/fastapi-app-with-the-gradio-client
- https://www.gradio.app/docs/mount_gradio_app

**Comment by bstraehle** [comment]
Thanks for the quick response, @gibiee. Assume a client cannot use Python or JavaScript, perhaps Go, C#, C++ or some other language. How can they consume Gradio? They can't, at the moment. With a REST API, they could.

This Postman workspace has some examples of REST APIs: [bstraehle/workspace/generative-ai-llm-rest-apis](https://www.postman.com/bstraehle/workspace/generative-ai-llm-rest-apis/overview). REST APIs follow the OpenAPI Specification (OAS), formerly known as Swagger.  Some companies list it as "curl" or "shell" on their developer portal.

**Comment by gibiee** [comment]
Oh, I understand.
I'm also curious to see if REST API will be implemented in "use via API".

**Comment by freddyaboulton** [comment]
> perhaps Go, C#, C++ or some other language. How can they consume Gradio? They can't, at the moment. With a REST API, they could.

It is possible to write your own client in these languages but not straightforward. We're reworking the clients currently with this aim in mind. I don't think we can support api usage via a sample POST request in the general case due to the different parts needed to use gradio programmatically correctly, e.g. file uploads, sse stream

**Comment by bstraehle** [comment]
Thanks, @freddyaboulton and @gibiee.  File upload and streaming can be done with a POST request.  I'll keep an eye on new releases.  Again, love Gradio, thanks for supporting it!

**Comment by hichemfantar** [comment]
Actually the [curl example](https://www.gradio.app/guides/querying-gradio-apps-with-curl) can be used as a standalone api although it would be great if there was a generated OpenAPI schema.
