### ISSUE TITLE
[Docs] Consider annotating parameters in `gradio`'s API docs.

### ISSUE THREAD

**Issue by dynamicwebpaige** [gradio-app/gradio#781]
## 📊  Feature Request: Description
**Note**: *This would be low priority, and a nice-to-have.*

For users who do not necessarily have experience with crafting visualizations using JavaScript or Python, it would be meaningful to include descriptive annotations for Gradio's API parameters in the documentation, similar to this example from Plotly:

![image](https://user-images.githubusercontent.com/3712347/156902516-4c14f8ba-e445-48fe-9392-4ca92d4f2d77.png)

## 💻  Motivation
It can be a bit challenging to understand how making changes to the parameters might influence the appearance of an app, or alter its interactivity. It would be especially effective to include GIFs immediately underneath the annotations, or images; especially for APIs like [`Creating Interfaces`](https://gradio.app/docs/#interface).

<img width="807" alt="Screen Shot 2022-03-05 at 3 06 14 PM" src="https://user-images.githubusercontent.com/3712347/156902649-b2e010d3-3cce-439d-875c-c33ab8ba2a22.png">

**Comment by abidlabs** [comment]
Thanks @dynamicwebpaige, this is super helpful! @aliabd do you wanna look into this?

**Comment by dynamicwebpaige** [comment]
I'm also happy to help design the annotated code samples, if you'd like an extra hand @aliabd! 😄 

And it looks like there is a library [called `synercys`](https://github.com/synercys/annotated_latex_equations#examples) that might be able to support this use case, and to make the annotations a bit easier to maintain:

![](https://github.com/synercys/annotated_latex_equations/raw/main/example_output_figs/example_overlay.png)

**Comment by aliabd** [comment]
This looks so great @dynamicwebpaige thanks for the suggestion! Will definitely loop you in as we start to work on it :)

**Comment by pngwn** [comment]
The API docs are pretty difficult to parse for users right now and could do with some TLC, so I think this is a brilliant idea. I think something like this combined with an interactive playground preloaded with examples (a kind of fake, live coding environment) that people can play around with will make the library more accessible. 

Also related is the theme builder that I'd like to spend some time on when blocks are in a better place.

We will be redesigning the site/ docs soon, so I feel like this work could form an important part of that.

**Comment by aliabd** [comment]
We decided not to do this as a lot of our classes have many parameters, and it would make it too crowded visually to annotate them. We opted for parameter tables instead. We'll keep this in mind as we work on our playground section because it might make sense there.
