### ISSUE TITLE
Disabled slider is visually no different from enabled one

### ISSUE THREAD

**Issue by Pythongor** [gradio-app/gradio#7813]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Disabled slider is visually no different from enabled one. The only difference is cursor on hover (only for slider thumb, on slider track cursor is "pointer" and it is unconsistent).

**Describe the solution you'd like**  
Solve it using css for Slider component, of course

**Comment by shubhamofbce** [comment]
Can you please add a comparison screenshot after the fix here, so we can take a look without running the code.
