### ISSUE TITLE
URL of launch

### ISSUE THREAD

**Issue by Stephen-SMJ** [gradio-app/gradio#7821]
### Describe the bug

Dear Sir or Madam:
I have two confusing points about Gradio:
1. I want to confirm that if the generated URL of UploadButtion is never changed after launch. 
I try to launch the upload locally, but the link is always /private/var/folders/g1/yl1rj89d2rd1lj5vjsx43llh0000gn/T/gradio/cb48f2e2c12afbbce6f510c2739e454060365fd2/....
2. If I want to make a download link in the response of the chatbot. How can I move some local files to the according generated download link such as  /private/var/folders/g1/yl1rj89d2rd1lj5vjsx43llh0000gn/T/gradio/cb48f2e2c12afbbce6f510c2739e454060365fd2/....
3. I use markdown to activate the download link in response text. But when I open the link, I found it is a URL with HTTP instead of the file system(start with file:///private/var/folders/g1/...... Then how can I change the HTTP URL to a file protocol.

Thanks for the answers.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
Dear Sir or Madam:
I have two confusing points about Gradio:
1. I want to confirm that if the generated URL of UploadButtion is never changed after launch. 
I try to launch the upload locally, but the link is always /private/var/folders/g1/yl1rj89d2rd1lj5vjsx43llh0000gn/T/gradio/cb48f2e2c12afbbce6f510c2739e454060365fd2/....
2. If I want to make a download link in the response of the chatbot. How can I move some local files to the according generated download link such as  /private/var/folders/g1/yl1rj89d2rd1lj5vjsx43llh0000gn/T/gradio/cb48f2e2c12afbbce6f510c2739e454060365fd2/....
3. I use markdown to activate the download link in response text. But when I open the link, I found it is a URL with HTTP instead of the file system(start with file:///private/var/folders/g1/...... Then how can I change the HTTP URL to a file protocol.

Thanks for the answers.
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @Stephen-SMJ 

1. Gradio saves files to a cache on your machine. The path is determined by the contents of the file (to avoid saving duplicates). If the file doesn't change, the location won't change either.
2. Easiest for now is to embed the file as b64 and display with html in the markdown (`<img src=b64>` ). We're working on making this easier.
3. Not sure

**Comment by freddyaboulton** [comment]
Going to close as I think the actionable item here is to make it easier to embed media and other components in the chatbot which is tracked in other issues (like this one https://github.com/gradio-app/gradio/issues/4355).

For general questions (like how the cache works), please ask in the huggingface discord in the gradio channels https://discord.gg/hugging-face-879548962464493619
