### ISSUE TITLE
Move pypi releases to github actions triggered by releases

### ISSUE THREAD

**Issue by discdiver** [gradio-app/gradio#783]
### Describe the bug

Latest version on PyPI is 2.8.7. Latest release version listed on GitHub is 2.8.1 

### Reproduction

just take a look at GitHub :)

### Screenshot

![Screen Shot 2022-03-06 at 7 02 31 PM](https://user-images.githubusercontent.com/7703961/156948178-861ec44e-0045-47b8-8e42-3dfae8de192d.png)

### System Info

```shell
gradio                    2.8.7                    pypi_0    pypi
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Thanks @discdiver for pointing this out! 

cc @aliabd @FarukOzderim @aliabid94 it would be better if we managed everything through GitHub Releases. We can set up a GitHub action to automatically push to pypi when we create a new release [1]. What do you guys think?

[1] https://www.caktusgroup.com/blog/2021/02/11/automating-pypi-releases/

**Comment by FarukOzderim** [comment]
Agreed!

**Comment by FarukOzderim** [comment]
Now that I think about it, version file change trigger feels fragile to me. Because it will release a new pypi version immediately. I would prefer having a publish button instead of this.

**Comment by abidlabs** [comment]
This has been partially implemented as we now deploy to pypi using GitHub actions (#1517). We still need to implement releases, but this is documented more precisely in #1646
