### ISSUE TITLE
Let JS Client set custom headers on requests

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#7833]
Sometimes users need to be able to pass custom headers with requests originating from the clients. The Python client supports a `headers` argument for this. 

Tangent: the Python client also has an `ssl_verify` parameter, which allows it to work with Gradio apps that are self-signed. We may want to consider adding this to the JS client as well.

Somewhat related: https://github.com/gradio-app/gradio/issues/2266,

**Comment by pngwn** [comment]
This is problematic because you can't pass headers with an `EventSource`. So this would only apply to `fetch` requests. Going to open a new issue that would resolve this an other issues.
