### ISSUE TITLE
Issues in component tree construction // UI freezes (>=4.22.0)

### ISSUE THREAD

**Issue by sbarman-mi9** [gradio-app/gradio#7839]
### Describe the bug

In 4.22.0, there are issues in component construction logic introduced in PR (https://github.com/gradio-app/gradio/pull/7564). As soon as we load the app, it freezes and shows the status tracker timer on some components. I have attached a screenshot that might help. The issue persists in 4.23.0.

I would request to revert changes to that PR if possible.

@abidlabs @pngwn 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

As it's a private app, I can't share much details. It's a complicated app.

### Screenshot

<img width="785" alt="image" src="https://github.com/gradio-app/gradio/assets/14152255/493c5820-6a82-4435-be91-46529b870da4">

### System Info

```shell
python 3.10.12
gradio 4.22.0
```

### Severity

Blocking usage of gradio

**Comment by pngwn** [comment]
I'll fix this with a guard but we ideally would have a reproduction to understand the issue properly.

**Comment by sbarman-mi9** [comment]
@abidlabs @pngwn 

Patch --> https://github.com/gradio-app/gradio/pull/7865 fixed this issue. Closing.

**Comment by abidlabs** [comment]
Cool thanks @sbarman-mi9!
