### ISSUE TITLE
Gradio stopped recording microphone sound

### ISSUE THREAD

**Issue by Denis-Kazakov** [gradio-app/gradio#7843]
### Describe the bug

I started  using Gradio recently on a speech translation project and worked for some time until it suddenly stopped recording sound from a microphone. I provided a simple demo below. The code does not produce any error messages but the recorded sound amplitude is 0.
I tried two different microphones and was able to record sound using other python packages.
OS: Linux. I have two conda environmentss with Gradio versions 4.22 and 4.19.2.
I probably upgraded Gradio in the second environment because the older version of the script worked with ```source="microphone"``` , although not sure about the upgrade.
What could be the source of this bug and how can it be remedied?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import numpy as np
import gradio as gr

def reverse_audio(audio):
    sr, data = audio
    gr.Info(f"SR: {sr}, max sound: {data.max()}") 
    reversed_audio = (sr, np.flipud(data))
    return reversed_audio

mic = gr.Audio(sources=["microphone"], type="numpy", label="Speak here...")

gr.Interface(reverse_audio, mic, "audio").launch()

```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.19.2
gradio_client version: 0.10.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.109.2
ffmpy: 0.3.2
gradio-client==0.10.1 is not installed.
httpx: 0.27.0
huggingface-hub: 0.20.2
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.1
matplotlib: 3.8.0
numpy: 1.26.0
orjson: 3.9.15
packaging: 23.2
pandas: 2.1.1
pillow: 10.0.1
pydantic: 2.6.2
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.2.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.27.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.27.0
huggingface-hub: 0.20.2
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

P.S. Neither downgrading to version 3.50.2 nor upgrading to 4.23 solved the issue.
P.P.S. Installing Gradio in a new environment did not help either.

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio
