### ISSUE TITLE
Access to current routing path from withing the Block

### ISSUE THREAD

**Issue by arian81** [gradio-app/gradio#7847]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
No this is just a suggestion and I think it will be useful.

**Describe the solution you'd like**  
Fastapi allows you to pass the router information to the functions so I'm assuming it's fairly easy to allow Block level access to the current router path when multiple instances of gradio are running on different paths using the method mentioned here. https://www.gradio.app/guides/fastapi-app-with-the-gradio-client

**Comment by abidlabs** [comment]
Hi @arian81 this is already doable by accessing the request object from within gradio. Here's a quick example I put together:

```py
import gradio as gr
def echo(text, request: gr.Request):
    if request:
        print("Path:", request.url.path)
    return text
io = gr.Interface(echo, "textbox", "textbox").launch()
```

**Comment by arian81** [comment]
> Hi @arian81 this is already doable by accessing the request object from within gradio. Here's a quick example I put together:
> 
> 
> 
> ```py
> 
> import gradio as gr
> 
> def echo(text, request: gr.Request):
> 
>     if request:
> 
>         print("Path:", request.url.path)
> 
>     return text
> 
> io = gr.Interface(echo, "textbox", "textbox").launch()
> 
> ```
> 
> 

Oh nice. Maybe this should be added as an example to docs. I'm sure there are others who's appreciate this.

**Comment by abidlabs** [comment]
Feel free to open a PR @arian81! Relevant sections:

* https://www.gradio.app/guides/sharing-your-app#accessing-the-network-request-directly
* https://www.gradio.app/docs/request

**Comment by arian81** [comment]
> Feel free to open a PR @arian81! Relevant sections:
> 
> * https://www.gradio.app/guides/sharing-your-app#accessing-the-network-request-directly
> * https://www.gradio.app/docs/request

Would you be able to provide me with a gr.Blocks() version as well. I'll add it to the docs because that's the one I couldn't figure out and isn't mentioned. Accessing the requests in Blocks()

**Comment by abidlabs** [comment]
Sure the equivalent code might look like this:

```py
import gradio as gr
def echo(text, request: gr.Request):
    if request:
        print("Path:", request.url.path)
    return text

with gr.Blocks() as demo:
  t1 = gr.Textbox()
  t2 = gr.Textbox()
  t1.submit(echo, t1, t2)
demo.launch()
```

**Comment by arian81** [comment]
> ```python
> echo
> ```

Is there anyway to access the url from within gr.Blcoks() itself. Ig this is somewhat of an unorthodox use case but I'm trying to conditionally render different dropdowns based on what the current path is.

**Comment by abidlabs** [comment]
You can add it to the `gr.Blocks.load()` event -- this would be a good example to add to the docs!
