### ISSUE TITLE
Incorrect responsive behavior on lower resolutions of the docs

### ISSUE THREAD

**Issue by DoBestMan** [gradio-app/gradio#7857]
https://www.gradio.app/docs/interface

Due to my small screen size, the sidebar is always hidden for me. However, the button to open the sidebar overlaps with the content, which is somewhat inconvenient. Additionally, when I do open the sidebar, the fonts and spacing feel less comfortable compared to the rest of the interface. I've attached screenshots for reference.

**Additional context**
Low priority but useful

![Screenshot 2024-03-27 111221](https://github.com/gradio-app/gradio/assets/110788393/ff9756fd-80ef-4ac5-a53e-1182110677e7)
![Screenshot 2024-03-27 111206](https://github.com/gradio-app/gradio/assets/110788393/090f6374-f373-4a7b-ab7a-f776f1afdaf1)

**Comment by DoBestMan** [comment]
Hi @abidlabs, shall I work on this one and open a PR?

**Comment by abidlabs** [comment]
That'd be great! You can find details on setting up the website locally here: https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md#%EF%B8%8F-gradio-website

**Comment by DoBestMan** [comment]
Great, I'll set up the environment soon and keep you updated. Thank you.
________________________________

**Comment by Olyray** [comment]
> That'd be great! You can find details on setting up the website locally here: https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md#%EF%B8%8F-gradio-website

When I tried running `pnpm build:cdn-local` as per the instruction in the CONTRIBUTING.md, I get this error:

```bash
(gradio) olyray@MSI:~/gradio$ pnpm build:cdn-local
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "build:cdn-local" not found

Did you mean "pnpm preview:cdn-local"?
```

I also get a similar error if I try running the code from `/gradio/js/_website`:

```bash
(gradio) olyray@MSI:~/gradio/js/_website$ pnpm build:cdn-local
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "build:cdn-local" not found
 ```

**Comment by shafiqihtsham** [comment]
I have submitted a PR for this issue here https://github.com/gradio-app/gradio/pull/7945.
