### ISSUE TITLE
Allow suppressing "Running on local URL:" print statement

### ISSUE THREAD

**Issue by dnoliver** [gradio-app/gradio#7864]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

When you run Gradio in a Jupyter Lab environment that uses Jupyter Server Proxy (https://github.com/jupyterhub/jupyter-server-proxy), the `Running on local URL: https://127.0.0.1:XXXX` statement is misleading. You can't really use it.  

The screenshot below show this case:

![image](https://github.com/gradio-app/gradio/assets/7730267/a05a6f3c-b791-4526-8c17-76eb7fded11b)

To access Gradio through Jupyter Server Proxy, you need to use the `/hub/user-redirect/proxy/XXXX/`

The print statement is defined at https://github.com/gradio-app/gradio/blob/main/gradio/blocks.py#L2099-L2104, and it gets suppressed only when you are in WASM or Colab. Otherwise, it always gets printed

The workaround is: use `%%capture` magic to suppress the output of the cell that runs gradio.

**Describe the solution you'd like**  

Could we hide the print when quiet is passed? like:

```
            if not wasm_utils.IS_WASM and not self.is_colab and not quiet:
                print(
                    strings.en["RUNNING_LOCALLY_SEPARATED"].format(
                        self.protocol, self.server_name, self.server_port
                    )
                )

```

**Additional context**  

This is how it looks with the capture magic, but it will capture any other relevant output from the cell!

![image](https://github.com/gradio-app/gradio/assets/7730267/5174e005-d8ea-476c-87c7-c53b4e1b116b)

**Comment by freddyaboulton** [comment]
Would you like to open a PR for this @dnoliver
