### ISSUE TITLE
Async generators do not show intermediate results

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#7867]
### Describe the bug

Not sure if this is a regression or a long-standing issue, but async generators do not show the orange border while the output components are generating. They do not show the intermediate results either.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import time

async def test(x):
    time.sleep(2)
    yield x + x
    time.sleep(2)
    yield x + x + x

with gr.Blocks() as demo:
    gr.Interface(test, "textbox", "textbox", examples=["abc", "def"])
    
demo.launch()
```

### System Info

```shell
4.24
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
It works if you use `await asyncio.sleep`. The `time.sleep` is blocking the entire event loop so my guess is that the sse events can't send until the function finishes running. I don't think there's anything we can do about that.

**Comment by abidlabs** [comment]
Ah I see, then there's probably a better way to do what I'm attempting to do in #7863 (converting sync generators to async generators). Will look into it
