### ISSUE TITLE
Gradio Chatbot message with Typing effect like chatgpt response

### ISSUE THREAD

**Issue by byashwan** [gradio-app/gradio#7868]
I would like to know whether gradio supports a typing feature where the response is sent to the user like a real time as in chatgpt where we get the answer in typing fashion, word by word

**Comment by dawoodkhan82** [comment]
You can take a look at the `chatbot_streaming` demo [here](https://github.com/gradio-app/gradio/blob/main/demo/chatbot_streaming/run.py).

**Comment by byashwan** [comment]
Thanks @dawoodkhan82, its working for on my chatbot. Can we do it same on textbox, i tried to replicate this code but its not working
