### ISSUE TITLE
Dropdown panel cannot be styled independently

### ISSUE THREAD

**Issue by JohnDuncanScott** [gradio-app/gradio#7873]
### Describe the bug

It is not possible to style the dropdown panel that drops down when you click on it. The background of the panel that appears on clicking seems to be linked to background_fill_primary_dark, which means tweaking that changes everything. The issue is the background of the panel doesn't stand out very well against the app background, especially in dark mode. You also can't style the hover colour when mousing over the dropdown panel options. Screenshot included for clarity.

Ideally in dark mode, the dropdown should have a lighter background and the hover should probably act the same way that the table row hover works (e.g. primary bright colour like orange).

It's not a massive blocker, but it is impossible to work around as far as I can tell.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Use theme builder with Default and Dark mode. Try and style the dropdown panel independently.

### Screenshot

![Screenshot 2024-03-28 085952](https://github.com/gradio-app/gradio/assets/18740815/fbbda304-c5dd-4ec3-831e-5f72ef6ff367)

### System Info

```shell
gradio==4.21.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @JohnDuncanScott the theme builder is intentionally limited in the number of different attributes that it exposes. In this case, I'd suggest using custom css for this level of precise styling: https://www.gradio.app/guides/custom-CSS-and-JS
