### ISSUE TITLE
Gradio HighlightText feature has some bugs 

### ISSUE THREAD

**Issue by Akhil-VSSG** [gradio-app/gradio#7884]
when ever iam trying to create a tag and select the text i directly get the tag with label as "LABEL" and when i try to rewrite the tag its always in upper case even tho i type it in lower case , so i get confused in which case i had typed. So i want to see which case i have typed the text, so with this bug when i give a color map the cases are being a huge problem as i give red for "name" when i enter tag i dont know which case iam typing in so it becomes difficult
<img width="1520" alt="Screenshot 2024-03-29 at 3 20 47 PM" src="https://github.com/gradio-app/gradio/assets/142409208/b9c86eb8-68b7-468a-a250-d1c75abc1361">

That was one issue , the other issue is that when i remove the tag for few words if there is space present it is been removed
<img width="378" alt="Screenshot 2024-03-29 at 3 24 14 PM" src="https://github.com/gradio-app/gradio/assets/142409208/4a027a4b-7dd0-41c8-b450-ed8c11d055cc">
<img width="461" alt="Screenshot 2024-03-29 at 3 24 39 PM" src="https://github.com/gradio-app/gradio/assets/142409208/ceb814a9-94a9-4d53-984a-3565ace45cbe">
<img width="403" alt="Screenshot 2024-03-29 at 3 24 54 PM" src="https://github.com/gradio-app/gradio/assets/142409208/8ea257d2-14d3-4c39-8f74-4ed398262e9b">
From the above example you can see that the space between "in" and "palo alto" is being removed so please look at it

Some more features that i need so that if applied can make the HighlightedText feature more good and efficient
for giving the label if we have **a user defined dropdown of labels** it will be very helpful for annotation purposes, i think this feature would be very helpful for annotators

**Comment by SarthakNikhal** [comment]
Can I work on this issue? @abidlabs @Akhil-VSSG

**Comment by Akhil-VSSG** [comment]
if you have an idea about it and if you can solve it please do it

**Comment by Akhil-VSSG** [comment]
@abidlabs , till when will this issue be resolved , waiting for this issue to be resolved its very useful in my project

**Comment by abidlabs** [comment]
Hi @Akhil-VSSG we have a pretty busy roadmap over the next couple of months so it may take us sometime to get to this. In the meantime, we are happy to review PRs by yourself, @SarthakNikhal or others!

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio

**Comment by jsaluja** [comment]
@Akhil-VSSG Can you share the code snippet for select listener on HighlightedText ? It appears from your screenshot that select listener is working correctly. I tried few things, listener is called but event parameter is passed as None
