### ISSUE TITLE
Better error messages with the Python Client

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#7889]
If an invalid value is provided using the Python Client, then the error that is raised is not very informative. We should transmit the error from the server to the client to provide better error messages.

E.g.

```py
from gradio_client import Client, file

client = Client("abidlabs/whisper")

client.predict(
    audio="abc"
)
```

Here "abc" needs to be a file not a string, but the Client currently produces:

```
ValueError: None
```

**Comment by SrijanSahaySrivastava** [comment]
Hey, I was able to reproduce this and I was thinking of doing a check of all args passed with `isinstance()` but idk what should I be checking them against

eg.:-
(*if we wanna check if argument is int*)
  for arg in args:
        if not isinstance(arg, int):  
            raise ValueError(f"Invalid argument: {arg}. All arguments must be integers.")
