### ISSUE TITLE
Output Img on top and input img at bottom in vertical layout with blocks ?

### ISSUE THREAD

**Issue by Adeel-Intizar** [gradio-app/gradio#789]
Hi, how can we show output image on top and input image at bottom after model prediction in Vertical layout with blocks?

Thanks

**Comment by abidlabs** [comment]
This is currently possible with Blocks! Blocks simply reads the components that are defined in order. So if your code looks like this, the output image will be on top of the input image:

```python
import gradio as gr

block = gr.Blocks()

with block:
    im = gr.outputs.Image()
    im2 = gr.inputs.Image()
    btn = gr.static.Button(label="Run")

    btn.click(lambda x:x.rotate(45), im2, im)

block.launch()
```

**Comment by Adeel-Intizar** [comment]
It works perfectly fine, can I adjust width/height in browser for the interface ? @abidlabs 

Thanks
