### ISSUE TITLE
regression on 4.22.0 and following: .focus() doesn't work anymore inside an Accordion(open=False)

### ISSUE THREAD

**Issue by ngaudemet** [gradio-app/gradio#7895]
### Describe the bug

Thank you for the tremendous work on Gradio!

I use Accordion(open=False) to hide components (such as a Dropdown and some buttons) and show them only when the user need it.
I then use a .focus event on the Dropdown.
It worked perfectly with gradio 4.21.0 but since 4.22.0, 4.23.0 and 4.24.0, it doesn't work anymore : it is impossible to open the Dropdown when I listen to gr.Dropdown.focus() inside my Accordion (only when this Accordion is initially set to open=False), since the Accordion closes itself automatically

this prevents me from using 4.22.0 and newer versions

and another idea : it would be nice to have an open=True parameter for gr.Dropdown as in Accordions

Thanks a lot!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

    import gradio as gr
    
    with gr.Blocks() as demo:
    
        with gr.Accordion(open=False):
            zouzou = gr.Dropdown(
                choices=["zouzou", "zouzou2"],
                type="index",
            )
    
        zouzou.focus(
            fn=lambda x: print(x),
            inputs=[zouzou],
            outputs=[],
            queue=False,
        )
    
    demo.launch()

### Screenshot

before I click on the Dropdown
<img width="1298" alt="image" src="https://github.com/gradio-app/gradio/assets/126974970/03cca8cc-0660-4a5d-bd58-9e8d8c659977">

and then the Accordion closes itself when I click on the Dropdown, which disappears
<img width="1260" alt="image" src="https://github.com/gradio-app/gradio/assets/126974970/f8e026d9-2925-4763-83cc-1c5f8b6edaec">

### Logs

```shell
No logs
```

### System Info

```shell
gradio==4.22.0 (or 4.23.0 or 4.24.0)
Mac Safari or Chrome 
PC Chrome or Edge
iPhone Safari or Chrome
```

### Severity

I can work around it

**Comment by C0untFloyd** [comment]
Also, since 1.24.0 clicking onto a subcontrol inside an open accordion closes it.

**Comment by ngaudemet** [comment]
Sorry there was an error in my repro code (open=False needs to be in the gr.Accordion() to see the bug, not in the Blocks() of course)
I corrected it
