### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'Variable'

### ISSUE THREAD

**Issue by Jawadhaider055** [gradio-app/gradio#7896]
### Describe the bug

  exstyle = gr.Variable()
  ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-8-fefc2b0434f1>](https://localhost:8080/#) in <cell line: 38>()
     58                                                   ]
     59                                          )   
---> 60                     exstyle = gr.Variable()
     61                 with gr.Row():
     62                     loadmodel_button = gr.Button('Load Model')

AttributeError: module 'gradio' has no attribute 'Variable'

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
  exstyle = gr.Variable()
```

### Logs

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-fefc2b0434f1> in <cell line: 38>()
     58                                                   ]
     59                                          )   
---> 60                     exstyle = gr.Variable()
     61                 with gr.Row():
     62                     loadmodel_button = gr.Button('Load Model')

AttributeError: module 'gradio' has no attribute 'Variable'
```

### System Info

```shell
google chorome colab
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @Jawadhaider055 , `gr.Variable` is deprecated. Please use `gr.State`
