### ISSUE TITLE
Output image not auto fit long side

### ISSUE THREAD

**Issue by se7enXF** [gradio-app/gradio#7901]
### Describe the bug

Add two image components and set height to fixed number. Input image is auto fit long side but output not.  

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr


def sepia(input_img):
    return input_img


demo = gr.Interface(sepia, gr.Image(height=600), gr.Image(height=600))
if __name__ == "__main__":
    demo.launch()
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/33513042/f24f014b-54da-470d-84b8-bbe61ae9b2bf)

### System Info

```shell
Windows 11, python 3.8.18, gradio==4.21.0

Run `gradio environment` Error: 

"RuntimeError: Type not yet supported: typing_extensions.Annotated[typing.Union[str, NoneType], <typer.models.OptionInfo object at 0x000001DF82FDEE50>]"
```

### Severity

Blocking usage of gradio

**Comment by MidnightFiend** [comment]
gradio 3.50.2  the same problem，is there any solution?
