### ISSUE TITLE
gradio webcomponent src URL path after domain ignored

### ISSUE THREAD

**Issue by joachimt-git** [gradio-app/gradio#7902]
### Describe the bug

I want to share my gradio app using a webcomponent like this. 

```
<gradio-app src="http://www.mysite.de/gradio-demo/"></gradio-app>
```

I would expect that I can entirely move my app unter the path /gradio-app/ as src is described as an URL. 

But that does not work. The javascript app wants to load a config and it does ignore the path /gradio-demo.
From the index.js I see (line 326, version 3.46.0)

```
      try {
        config = await resolve_config(
          fetch_implementation,
          `${http_protocol}//${host}`,
          hf_token
        );
```
Only the ${host} is taken.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### Logs

```shell
Failed to load resource: the server responded with a status of 404 (Not Found)
index.js:362 Error: Could not get config.
    at Ar (index.js:958:11)
    at async index.js:357:52
(anonymous) @ index.js:362
/config:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
index.js:362 Error: Could not get config.
    at Ar (index.js:958:11)
    at async index.js:357:52
(anonymous) @ index.js:362
/favicon.ico:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
```

### System Info

```shell
Chrome Browser, nginx webserver
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
I believe this has been fixed in newer versions of gradio. Can you try with the latest gradio version?

**Comment by joachimt-git** [comment]
I have tried version 4.24.0. Unfortunately the 404 Error for /config still is present. The line of code where /config is being searched stays the same. In 4.24.0 now the line 471 in index.js.

```
      try {
        config = await resolve_config(
          fetch_implementation,
          `${http_protocol}//${host}`,
          hf_token
        );
        const _config = await config_success(config);
        res(_config);
      } catch (e) {
        console.error(e);
        if (space_id) {
          check_space_status(
            space_id,
            RE_SPACE_NAME.test(space_id) ? "space_name" : "subdomain",
            handle_space_sucess
          );
```
I see in the js console that the exception e is thrown and caught.

Best regards

Joachim

**Comment by SombreCode** [comment]
you can use this patch (via [patch-package](https://github.com/ds300/patch-package) )
[@gradio+client+0.15.1.patch](https://gist.github.com/SombreCode/38de7678835df2e6265d2c1399fe7b4a)

add dependencies `yarn add eventsource`
add code in you index.js: `global.EventSource = require('eventsource');`

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio
