### ISSUE TITLE
"ReferenceError: window is not defined" when using an Space API with @gradio/client in Node.js

### ISSUE THREAD

**Issue by Stefan-Kosker** [gradio-app/gradio#7906]
### Describe the bug

It was already there multiple times. So here it is again:

When using an API in node.js environment, gradio Client crashes because window is not defined (which is totally normal with node.js)

```
ReferenceError: window is not defined
    at config_success (file:///E:/projects/co-pilot/node_modules/@gradio/client/dist/index.js:417:9)
    at file:///E:/projects/co-pilot/node_modules/@gradio/client/dist/index.js:468:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Nothing magical is necessary, just copy the example on your page https://www.gradio.app/guides/getting-started-with-the-js-client

```javascript
import { client } from "@gradio/client";

const response = await fetch(
	"https://github.com/audio-samples/audio-samples.github.io/raw/master/samples/wav/ted_speakers/SalmanKhan/sample-1.wav"
);
const audio_file = await response.blob();

const app = await client("abidlabs/whisper");
const transcription = await app.predict("/predict", [audio_file]);

console.log(transcription.data);

```

### Logs

```shell
ReferenceError: window is not defined
    at config_success (file:///E:/projects/co-pilot/node_modules/@gradio/client/dist/index.js:417:9)
    at file:///E:/projects/co-pilot/node_modules/@gradio/client/dist/index.js:468:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```


### System Info

```shell
@gradio/client: 0.14.0
nodejs: v20.10.0

Thank you very much
```

### Severity

Blocking usage of gradio

**Comment by Waleed-abdullah** [comment]
Hey Stefan, were you able to find a workaround for this? It appears that gradio requires a browser window to function, but I want this code to use the gradio API on the backend where there is no window object, might need to switch to the python client

**Comment by marofernandez** [comment]
Any updates about this?

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by Waleed-abdullah** [comment]
It works now with v1.7.0 of gradio/client

**Comment by abidlabs** [comment]
Thanks for confirming @Waleed-abdullah! Will go ahead and close -- @Stefan-Kosker if you are still encountering any issues, please let me know and we can reopen or create a new issue as needed
