### ISSUE TITLE
Disable Submission but keep component interactive

### ISSUE THREAD

**Issue by Solomin0** [gradio-app/gradio#7907]
- [x ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I would like a way to allow the user to continue typing in a textbox while the chatbot is processing their first request.  Currently I must lock out the user until the predict function is complete

**Describe the solution you'd like**  
The second signal would be added on to the end of the queue instead of replacing the first signal.

**Comment by freddyaboulton** [comment]
We'd have to somehow disable the submit event from triggering while the chatbot responds and there isn't an API to do that right now.

**Comment by Solomin0** [comment]
@freddyaboulton for a workaround I could 

1. hide the actual textbox, 
2. create a dummy textbox not hooked up to any functions 
3. once the chatbot is done hide the dummy and copy it back to the real one.

This seems like a REALLY taped together solution though but all i can think of unless there is a way to change which function is called with a signal. 

The main functionality I care about is to be able to type during streaming so the user isnt just idle.

**Comment by abidlabs** [comment]
Hi @Solomin0 if you'd like this behavior:

> The second signal would be added on to the end of the queue instead of replacing the first signal.

you can just define an event whose `trigger_mode` is "multiple"
