### ISSUE TITLE
Allow editing of messages in Chatbot

### ISSUE THREAD

**Issue by fakerybakery** [gradio-app/gradio#7919]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
It would be nice if we could add an option to allow people to edit both their and a chatbot's message.

**Describe the solution you'd like**  
Add a `allow_assistant_edit=True` and `allow_user_edit=True` method, as well as an event (`chatbot.user_edit()` and `chatbot.assistant_edit()`) when a user or assistant message is edited.

**Comment by abidlabs** [comment]
Can you describe the use case for this a bit?

**Comment by fakerybakery** [comment]
Sure! Would be nice for data collection, data editing, data review, etc as well as steerable writing (ie to help write blog posts/essays/etc)

**Comment by abidlabs** [comment]
I see, wouldn't a `gr.Textbox` output be more useful for these use cases? It seems a bit cumbersome to edit an essay within a Chatbot message for example

**Comment by fakerybakery** [comment]
I mean for interactive editing, also it would be great for data collection (which is what I was thinking of doing), a textbox doesn’t support multi round conversations

**Comment by abidlabs** [comment]
Data collection meaning the chatbot generates something, and then you allow users to edit the generation e.g. to provide a better generation that you could use to finetune the model?

**Comment by fakerybakery** [comment]
Correct, to edit any mistakes the chatbot made

**Comment by sbarman-mi9** [comment]
Looking into the recent regressions and in the past, the current chatbot should be kept un-touched, so folks can use it as a baseline and create custom components the way they want. Something new would come up tomorrow and people would say we want this or that to be included in the bot. This screws up existing applications and they can't upgrade to newer version of gradio. 

If these features are added, they should be published as 'experimental' custom components (not part of main package). Then, after months of testing and acceptance, they may be merged into main package.

**Comment by fakerybakery** [comment]
I was thinking more of something like creating a new component based on Chatbot (ie `EditableChatbot`)

**Comment by abidlabs** [comment]
If we do implement this, the appropriate way would be to allow this behavior when `interactive=True` in the `gr.Chatbot` -- a parameter that currently has no effect.

But that might be a while off. In the meantime, I think this would be a great case for a custom component!  https://www.gradio.app/guides/five-minute-guide, and we're happy to help.

**Comment by aliabid94** [comment]
Right now, if you'd like to implement something liek this, you can use the Chatbot.select listener to allow users to select a message, in which case another gr.Textbox could become visible and allow for a user to edit the message. Something like:

```python
import gradio as gr

with gr.Blocks() as demo:
    chatbot = gr.Chatbot(value=[["Hello", "Hi"], ["How are you?", "I'm good, how are you?"]])
    edit_box = gr.Textbox(label="Edit Message", visible=False)
    selection = gr.State(None)

    def select_message(selection: gr.SelectData):
        return selection.index, gr.Textbox(visible=True)

    chatbot.select(select_message, None, [selection, edit_box])

    def submit_edit(edit_message, selection, chat):
        chat[selection[0]][selection[1]] = edit_message
        return gr.Textbox("", visible=False), None, chat
    
    edit_box.submit(submit_edit, [edit_box, selection, chatbot], [edit_box, selection, chatbot])

if __name__ == "__main__":
    demo.launch()
```

![Recording 2024-12-03 at 12 56 11](https://github.com/user-attachments/assets/bf304640-f03a-4b95-b5c9-0e2a3d2a7ad2)
