### ISSUE TITLE
Button name changes to undefined

### ISSUE THREAD

**Issue by kota-iizuka** [gradio-app/gradio#7921]
### Describe the bug

When you start the server with the script below, there is a button named `Run` at first, but if you click the `Run` button many times in a row, the name changes to `undefined`.

- The number of times it changes to `undefined` is approximately 2 to 10 times, and the number of times varies each time.
- In `debug=True` mode the console does not change and there are no error messages on the console.
- When I restart the browser it goes back to the `Run` button, but after a few clicks it becomes `undefined` again.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

enable_btn = gr.Button(interactive=True)
disable_btn = gr.Button(interactive=False)

def run():
    for _ in range(100):
        yield disable_btn
    yield enable_btn
    return

with gr.Blocks() as demo:
    btn = gr.Button()
    btn.click(run, None, [btn])

demo.launch()
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/64062831/1b735cdb-c687-42ba-b690-23291d64fbe9)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.22.0
gradio_client version: 0.13.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.3.0
fastapi: 0.110.1
ffmpy: 0.3.2
gradio-client==0.13.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.22.2
importlib-resources: 6.4.0
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.3
numpy: 1.26.4
orjson: 3.10.0
packaging: 24.0
pandas: 2.2.1
pillow: 10.3.0
pydantic: 2.6.4
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.5
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.0
typing-extensions: 4.10.0
uvicorn: 0.29.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.3.1
httpx: 0.27.0
huggingface-hub: 0.22.2
packaging: 24.0
typing-extensions: 4.10.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @kota-iizuka can you check to see if this is resolved on the latest version of `gradio` (currently 4.25)? I think this bug may have been fixed.

**Comment by kota-iizuka** [comment]
@abidlabs Yes, the same problem occurs even after `pip install --upgrade gradio`. The updated `gradio environment` is as follows.

```
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.25.0
gradio_client version: 0.15.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.3.0
fastapi: 0.110.1
ffmpy: 0.3.2
gradio-client==0.15.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.22.2
importlib-resources: 6.4.0
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.3
numpy: 1.26.4
orjson: 3.10.0
packaging: 24.0
pandas: 2.2.1
pillow: 10.3.0
pydantic: 2.6.4
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.5
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.0
typing-extensions: 4.10.0
uvicorn: 0.29.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.3.1
httpx: 0.27.0
huggingface-hub: 0.22.2
packaging: 24.0
typing-extensions: 4.10.0
websockets: 11.0.3
```

**Comment by yvrjsharma** [comment]
I can reproduce this issue. It is also visible on the latest [mPLU/DocOwl1.5](https://huggingface.co/spaces/mPLUG/DocOwl) demo. They are using the latest sdk (4.25.0) too. It comes up for me after using the Space for a while (~3 minutes) in multi-turn chat fashion. 

![image](https://github.com/gradio-app/gradio/assets/48665385/323159e1-d1ef-4bb7-8e22-9e330f5e2843)
