### ISSUE TITLE
Markdown doesn't support image render

### ISSUE THREAD

**Issue by guofei1989** [gradio-app/gradio#7922]
### Describe the bug

The `gr.MarkDown` fails to render local image link.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr


with gr.Blocks() as app:

    with gr.Row():
        gr.Markdown(
        """
        # Hello  ! 
        ![Alt text](html/pics/doss_icon.png)
        A powerful AI system connects humans and data.
        """
        )
        
app.queue()     
app.launch()

```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/36873095/2eac311c-e118-4179-9b52-2b94c4db52e4)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.25.0
gradio_client version: 0.15.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.1.0
altair: 5.0.1
fastapi: 0.106.0
ffmpy: 0.3.0
gradio-client==0.15.0 is not installed.
httpx: 0.25.2
huggingface-hub: 0.20.2
importlib-resources: 5.12.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.1
numpy: 1.25.0
orjson: 3.9.1
packaging: 23.2
pandas: 2.1.4
pillow: 9.5.0
pydantic: 2.6.4
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0
ruff: 0.3.5
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.25.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.25.2
huggingface-hub: 0.20.2
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @guofei1989 , by default gradio does not serve arbitrary files from your computer for security reasons. You need to set `allowed_paths` in launch to be the list of paths you would like to allow and then use the URL of the file ( `/file=<path>`)

This code works for me:

```python
import gradio as gr


with gr.Blocks() as app:

    with gr.Row():
        gr.Markdown(
        """
        # Hello  ! 
        ![Alt text](/file=img_0.png)
        A powerful AI system connects humans and data.
        """
        )
        
app.queue()     
app.launch(allowed_paths=["img_0.png"])
```

We'll think about ways to make this clearer but will close for now.

**Comment by zhilongjia** [comment]
I run `gradio ./test.py` and img_0.png is in the same directory as `test.py`.
It seems `allowed_paths=["img_0.png"]` and `![Alt text](/file=img_0.png)` in gr.Markdown does not work for gradio=5.9.1 as shown below. 
![2024-12-18_23-19](https://github.com/user-attachments/assets/88a8d286-5b4c-4ddc-b960-85b71acb3056)

Additionally, how to show a markdown  ( or html) file directly in gradio, instead of a string of markdown sentences in quote? Thank you.

**Comment by zhilongjia** [comment]
`/gradio_api/file=./logo.png`
ref https://github.com/gradio-app/gradio/issues/9844
