### ISSUE TITLE
can gradio be authorized with keycloak

### ISSUE THREAD

**Issue by jayita13** [gradio-app/gradio#7943]
something similar to what is done with Google OAuth
[Ext Client authorization](https://www.gradio.app/guides/sharing-your-app#o-auth-with-external-providers)

**Comment by abidlabs** [comment]
Hi @jayita13 its possible, but for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
