### ISSUE TITLE
When running docker image of Gradio app, it doesn't do anything. Upon pressing Ctrl+C, it shows the link.

### ISSUE THREAD

**Issue by PrashantSaikia** [gradio-app/gradio#7944]
### Describe the bug

I am sharing a screen recording of the issue here.

https://github.com/gradio-app/gradio/assets/39755678/59fd2974-746c-42fc-abb9-bcb4f7d625ab

As you can see, I have in an Amazon EC2 instance and I have built a docker image of my gradio app. When I run the docker image, it's not producing the link (http://127.0.0.1/7860). I press enter a few times, nothing happens. Then at the end, around the 0:24 mark in the video, I press Ctrl+C (to terminate the execution of the command), and that's when the link is first displayed and then the CLI is closed.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

`app.py`:

```python
import gradio as gr
chatbot = gr.ChatInterface("Hello!")
chatbot.queue().launch()
```

`Dockerfile`:

```
FROM python:3.11-slim

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

RUN curl -fsSL https://ollama.com/install.sh | sh

COPY . .

EXPOSE 8080

CMD ["python", "app.py"]
```

Build the docker image:

`docker build -t app .`

Run it:

`docker run -p 8080:8080 app`

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.25.0
gradio_client version: 0.15.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.3.0
fastapi: 0.110.1
ffmpy: 0.3.2
gradio-client==0.15.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.22.2
importlib-resources: 6.4.0
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.4
numpy: 1.26.4
orjson: 3.10.0
packaging: 24.0
pandas: 2.2.1
pillow: 10.3.0
pydantic: 2.6.4
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.5
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.0
typing-extensions: 4.10.0
uvicorn: 0.29.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.3.1
httpx: 0.27.0
huggingface-hub: 0.22.2
packaging: 24.0
typing-extensions: 4.10.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @PrashantSaikia the Gradio app you've provided is invalid, perhaps that's why you're seeing this issue? Can you try with a valid app?

Docs for ChatInterface: https://www.gradio.app/guides/creating-a-chatbot-fast

Docs for running Gradio with Docker: https://www.gradio.app/main/guides/deploying-gradio-with-docker

**Comment by AstraBert** [comment]
Hi @abidlabs!

I had the same exact issue that @PrashantSaikia is reporting here and my GradIO app is valid (when I run it with python3 it works). I solved the issue simply implementing the solution you proposed on issue #24 , i.e. specifying to the launch() the server_name as `0.0.0.0`. Now, if I do: 

```
docker run -p 7860:7860 everything-rag:latest -m microsoft/phi-2 -t text-generation
```

GradIO interface smoothly shows up on port 0.0.0.0:7860 when everything is loaded.

Check out [the python script](https://github.com/AstraBert/everything-rag/blob/main/docker/chat.py) and [the Dockerfile I used to build my image](https://github.com/AstraBert/everything-rag/blob/main/docker/Dockerfile) for reference :)

Cheers,
Astra

**Comment by abidlabs** [comment]
Yes thank you Astra! I had included this in the [Docker guide](https://www.gradio.app/main/guides/deploying-gradio-with-docker) but missed the fact that @PrashantSaikia's app was running on 127.0.0.1. @PrashantSaikia this should fix the bug that you're seeing, thanks.
