### ISSUE TITLE
query parameters not read properly - regression on Spaces 

### ISSUE THREAD

**Issue by mbotsi** [gradio-app/gradio#7948]
### Describe the bug

Hello! I am using the gradio.Request(···) function to fetch query parameters from an URL in different projects, inspired by some of the projects pasted below. https://www.gradio.app/docs/request

Since appx. 1-2 hour ago it does not work to fetch the query parameters from URLs, not in my projects, not in the other projects. I can 100% confirm it worked today in the afternoon and then stopped. 
For example here https://huggingface.co/spaces/osanseviero/gradio-url-params?test_parameters=987698769786
I would expect the query parameters to include at least test_parameters=987698769786. But instead, the results show only "object: object". This is the same issue for all the spaces I know that are trying to receive query params from the URL. 

Example spaces where the query parameters are suddenly wrong (but used to be fetched correctly): 
https://huggingface.co/spaces/botsi/original-queryparams-with-http-gradio?param=testtestttest
https://huggingface.co/spaces/botsi/gradio-url-params-sdk4?PARAM=12345
https://huggingface.co/spaces/botsi/gradio-url-params-sdk3?param=12345678 
https://huggingface.co/spaces/osanseviero/gradio-url-params?test_parameters=987698769786
<img width="1398" alt="Bildschirmfoto 2024-04-05 um 19 09 14" src="https://github.com/gradio-app/gradio/assets/77936023/9724a5c5-e77f-4e78-a046-79b1debbcc31">

When using other methods (not the gradio.Request()) it also does not work to get the correct query parameters, see here: https://huggingface.co/spaces/botsi/original-queryparams-with-js-static?urlparam=1234567890

I need the functionality currently for this project (where I also do not get the right parameters currently, but this afternoon I did): https://huggingface.co/spaces/botsi/trust-game-llama-2-7b-chat/blob/main/app.py 
Using gradio sdk_version: 4.20.0. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio as gr

def predict(text, request: gr.Request):
    query_params = request.query_params
    return {
        "query_params": query_params
    }

gr.Interface(predict, "text", "json").queue().launch()

### Screenshot

<img width="1398" alt="Bildschirmfoto 2024-04-05 um 19 09 14" src="https://github.com/gradio-app/gradio/assets/77936023/df41ae23-737d-4fcc-83a6-d18641c2bcde">
<img width="1131" alt="Bildschirmfoto 2024-04-05 um 19 21 33" src="https://github.com/gradio-app/gradio/assets/77936023/c7da5572-400c-4492-9cf6-346dac05793e">

### Logs

```shell
There is no error. The query parameters returned are not correct.
```

### System Info

```shell
sdk: gradio
sdk_version: 4.20.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @mbotsi can you try upgrading to the latest version of `gradio`?

**Comment by mbotsi** [comment]
Hey @abidlabs, thanks so much for the quick reply! 
So I did update to 4.25.0, and got the following error: Type is not JSON serializable: QueryParams

I adapted the code to this: 

import gradio as gr
def predict(text, request: gr.Request):
    query_params_dict = {
        key: value for key, value in request.query_params.items()
    }
    return {
        "query_params": query_params_dict
    }
gr.Interface(predict, "text", "json").queue().launch()

But now I still receive [object Object] as query parameter instead of param=12345678 as expected 
<img width="1511" alt="Bildschirmfoto 2024-04-06 um 00 19 57" src="https://github.com/gradio-app/gradio/assets/77936023/438d7add-1421-4033-afb4-3bc9b975eca0">

I have used the code snippet stated above in "Reproduction" for the last 3 weeks and it worked perfectly until today. 
It only stopped working in the middle of the afternoon April 5. Were there maybe some updates to the request function I was not aware of?

**Comment by abidlabs** [comment]
Interesting, there weren't any updates to `gradio` but there might have been some updates to HF Spaces. Can you see if your Gradio app works locally as you expect it to?

**Comment by mbotsi** [comment]
![image](https://github.com/gradio-app/gradio/assets/77936023/4b2d2f47-14e8-4b32-868a-b19adfd7d1d1)
it does - so it is a HF Spaces issue?

**Comment by abidlabs** [comment]
I confirmed internally that this is a HF Spaces issue, not a Gradio issue. The Spaces team is working on a fix, so I'll go ahead and close this issue.

**Comment by abidlabs** [comment]
We've deployed the fix, can you confirm that the Space is working for you now?

**Comment by mbotsi** [comment]
Works again! Thanks for your support!
