### ISSUE TITLE
How to use css to change the style of the label or info text in the gradio.textbox

### ISSUE THREAD

**Issue by robchenchen** [gradio-app/gradio#7956]
How to use css to change the style of the label or info text in the gradio.textbox?

For example, if I want the info text to be bold? Thank you very much for your support!

**Comment by abidlabs** [comment]
Hi @robchenchen please see: https://www.gradio.app/guides/custom-CSS-and-JS. By the way, for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
