### ISSUE TITLE
support custom pipelines in `gr.Interface.from_pipeline` 

### ISSUE THREAD

**Issue by not-lain** [gradio-app/gradio#7964]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I can't run any custom pipelines on the `gr.Interface.from_pipeline` 
**Describe the solution you'd like**  
check inheritence and support the custom pipelines
**Additional context**  
I made a custom pipeline in this repo that can be used as a reference : https://huggingface.co/not-lain/MyRepo
how to use : 
```python 
# download an image (should have a number in it because our model is trained on mnist in that repo)
!wget https://e7.pngegg.com/pngimages/414/624/png-clipart-brand-black-and-white-angle-number-2-text-monochrome.png -O 2.png
```
```python
from transformers import pipeline
pipe = pipeline("image-classification", model="not-lain/MyRepo", trust_remote_code=True)
pipe("2.png") 
```
a list of other repos that have custom pipelines : 
* https://huggingface.co/briaai/RMBG-1.4 (image segmentation is not a supported task yet in the gr.Interface.from_pipeline) 
* https://huggingface.co/p1atdev/siglip-tagger-test-3

**Comment by abidlabs** [comment]
Thanks @not-lain. Will look into your PR!

**Comment by abidlabs** [comment]
I don't think we'll implement this, see discussion on https://github.com/gradio-app/gradio/pull/7965
