### ISSUE TITLE
Document `.on` trigger

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#7976]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I could not find documentation on the `.on` trigger

**Describe the solution you'd like**  
Document the `.on` trigger as it's super helpful

**Comment by abidlabs** [comment]
Yes we need to do this. cc @aliabd 

Related: https://github.com/gradio-app/gradio/issues/5072
