### ISSUE TITLE
An environment variable to override the share=True/False option when launching

### ISSUE THREAD

**Issue by cocktailpeanut** [gradio-app/gradio#7985]
[o] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

There are many gradio apps, and some apps launch with the `share=True` option and some don't.

But sometimes we just want to force `share=True`, WITHOUT having to change the code. For example, even if the app launched with `app.launch()` (no `share=True`), if we can pass in an environment variable that forces the gradio.live link that would be very convenient.

**Describe the solution you'd like**  

An environment variable named `GRADIO_SHARE`:

1. `GRADIO_SHARE=1 python app.py`: will launch the gradio.live share link even if the `app.py` launched the server with `app.launch()`.
2. `GRADIO_SHARE=0 python app.py`: will launch WITHOUT the gradio.live share link even if the `app.py` launched with the server with `app.launch(share=True)`

**Additional context**  

This feature should be beneficial to huggingface and gradio adoption since even the users who run the projects 100% locally can easily start using the gradio proxy through the gradio.live links.

**Comment by abidlabs** [comment]
Closed via #7986
