### ISSUE TITLE
Markdown links are not opened in a new tab (target="_blank" missing) for locally served files

### ISSUE THREAD

**Issue by lucasalvarezlacasa** [gradio-app/gradio#7990]
### Describe the bug

I've built an application that references files locally exposed by Gradio.

For some reason, there is a check that forces those links to be opened as part of the same tab. I don't want that, as I lose the conversation previously had. 

I want the sources to be opened in a new tab when clicked, via "target=_blank". This is the default behavior by Gradio when the source points to an external link in the application.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

Simply have an application that returns a link pointing to a local file exposed by Gradio. The link will not contain the target="_blank" property.

### Logs

```shell
No logs are relevant for this issue.
```

### System Info

```shell
Gradio version -> 4.21.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Closing for lack of follow up, we can reopen once we have a repro
