### ISSUE TITLE
Issue with MultimodalTextbox

### ISSUE THREAD

**Issue by TALLEC-Scott** [gradio-app/gradio#7993]
### Describe the bug

Hey, I tried to customize the textbox using the multimodal textbox as suggested in this [guide](https://www.gradio.app/guides/creating-a-chatbot-fast). However, when I try running it I get the following : 

> Traceback (most recent call last):
  File "C:\Users\XXX\PycharmProjects\XXX\demo.py", line 26, in <module>
    gr.ChatInterface(
  File "C:\Users\XXX\PycharmProjects\XXX\.venv\lib\site-packages\gradio\chat_interface.py", line 306, in __init__
    self._setup_events()
  File "C:\Users\XXX\PycharmProjects\XXX\.venv\lib\site-packages\gradio\chat_interface.py", line 312, in _setup_events
    [self.textbox.submit, self.submit_btn.click]
AttributeError: 'str' object has no attribute 'click'

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr


def echo(message, history):
    return message

gr.ChatInterface(
    fn=echo,
    title="XXX",
    description="XXX",
    #chatbot=gr.Chatbot(height=300),
    textbox=gr.MultimodalTextbox(placeholder="Ask me a specific question / Pose moi une question precise ?"),
    multimodal=True
).launch()
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.26.0
gradio_client version: 0.15.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.3.0
fastapi: 0.110.1
ffmpy: 0.3.2
gradio-client==0.15.1 is not installed.
httpx: 0.27.0
huggingface-hub: 0.22.2
importlib-resources: 6.4.0
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.4
numpy: 1.26.4
orjson: 3.10.0
packaging: 24.0
pandas: 2.2.1
pillow: 10.3.0
pydantic: 2.6.4
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.5
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.0
typing-extensions: 4.10.0
uvicorn: 0.29.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.3.1
httpx: 0.27.0
huggingface-hub: 0.22.2
packaging: 24.0
typing-extensions: 4.10.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

Edit: I just removed some sensitive content

**Comment by abidlabs** [comment]
@dawoodkhan82  can you take a look at this?
