### ISSUE TITLE
Drag and Drop-able Canvas

### ISSUE THREAD

**Issue by coolkau** [gradio-app/gradio#7994]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
It is not related to a problem

**Describe the solution you'd like**  
I would love to be able to drag and drop elements in a canvas, potentially, between canvasses. I would need updates on the new position of the elements. The canvas can be a grid. 
A good example of what I want is implemented in the steamlit component https://github.com/okld/streamlit-elements. It is behind the scenes implementing react-grid-layout into streamlit. It would be fantastic if this could be implemented in gradio as well. 

Example use-case demonstrating what I am after: Build a simple kanban board. Cards can be dragged between different columns and can be reordered within their column.

**Comment by freddyaboulton** [comment]
This sounds like a fantastic case for custom components! 

https://www.gradio.app/guides/custom-components-in-five-minutes

**Comment by coolkau** [comment]
Can you display gradio elements within a custom component? Because you'd want to display standard gradio elements in the canvas. It would be more a custom container then an element. If this was possible it would actually be quite cool.

**Comment by freddyaboulton** [comment]
Yea you can create custom containers. In fact, this canvas component created by @hannahblair is a step towards what you want: https://huggingface.co/spaces/hmb/gradio_coolcanvas

![cool_canvas_demo](https://github.com/gradio-app/gradio/assets/41651716/d1b4d1ef-298b-441e-91f8-cdb5ef1d1b34)

**Comment by abidlabs** [comment]
Yes let’s close this issue for now since this is outside the scope of core Gradio
