### ISSUE TITLE
max_workers not working

### ISSUE THREAD

**Issue by peeter2** [gradio-app/gradio#8001]
### Describe the bug

Whenever I add max_workers=10 to the launch() then the console says:
TypeError: Blocks.launch() got an unexpected keyword argument 'max_workers'

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

demo.launch(max_workers=10)

### System Info

```shell
latest
```

### Severity

I can work around it

**Comment by pngwn** [comment]
There is no `max_workers` kwarg for launch. You probably want `max_threads`. 

https://www.gradio.app/docs/interface#interface-launch

**Comment by peeter2** [comment]
If you're saying there is no such thing then what is this max_workers parameter in launch() all about?
https://www.gradio.app/guides/setting-up-a-demo-for-maximum-performance#the-max-workers-parameter-in-launch

**Comment by freddyaboulton** [comment]
Hi @peeter2 , would you like to open a PR to update the guide?
