### ISSUE TITLE
how to update gr.Examples content?

### ISSUE THREAD

**Issue by sunnyan1989** [gradio-app/gradio#8005]
for example, when the url is localhost:7860?target=test_a, we have gr.Examples(
                label="body",
                inputs=garm_img_dc,
                examples=[
                     os.path.join(example_path, 'garment/test_a/1.jpg'),
                     os.path.join(example_path, 'garment/test_a/2.jpg'),
                ]
                )
when the url is localhost:7860?target=test_b,  we have gr.Examples(
                label="body",
                inputs=garm_img_dc,
                examples=[
                     os.path.join(example_path, 'garment/test_b/1.jpg'),
                     os.path.join(example_path, 'garment/test_b/2.jpg'),
                ]
                )
instead. Is it possible?

**Comment by abidlabs** [comment]
Hi @sunnyan1989 thanks for reporting. Currently, there isn't a good way to update examples, please follow this issue: https://github.com/gradio-app/gradio/issues/5042 (will close as this is a duplicate)
