### ISSUE TITLE
Download Just Output Image Instead of Screenshot ?

### ISSUE THREAD

**Issue by Adeel-Intizar** [gradio-app/gradio#801]
Hi, how do i download just the output image instead of the screenshot ?

Thanks

**Comment by abidlabs** [comment]
You should be able to just right-click on the image and save it. Let me know if that doesn't work on your browser/OS

**Comment by Adeel-Intizar** [comment]
yes, It works that way, but it would be better user experience if there is a button to download the image, can we implement that in gradio ?

**Comment by abidlabs** [comment]
I understand what you are saying, but we're careful about limiting additional buttons that take up real estate on the interface. I don't think we'll implement in the default `Interface`, and instead make it possible for a user to do this through the `Blocks` API.

**Comment by snknitin** [comment]
A download button could be a good signal to see if the user is satisfied with your model output. Functions as a feedback loop with labels that can help curate edge cases and retraining dataset . It could be an event listener to get metadata from the usage of the model. Is there a way to currently do this with the Blocks ? To create a download button or a clear button
