### ISSUE TITLE
Gallery selected_index parameter prevents selecting it using a function.

### ISSUE THREAD

**Issue by peeter2** [gradio-app/gradio#8015]
### Describe the bug

gr.Gallery(selected_index=1) prevents changing the index dynamically.

So if I want to change the selected gallery item using a function, it will not work anymore.
    def get_select_index(evt: gr.SelectData):
        return evt.index

Worked fine in gradio v 4.19.1

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
latest
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Can you please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by peeter2** [comment]
Sure here you go:

`
import random

import gradio as gr


def fake_gan():
    images = [
        (random.choice(
            [
                "http://www.marketingtool.online/en/face-generator/img/faces/avatar-1151ce9f4b2043de0d2e3b7826127998.jpg",
                "http://www.marketingtool.online/en/face-generator/img/faces/avatar-116b5e92936b766b7fdfc242649337f7.jpg",
                "http://www.marketingtool.online/en/face-generator/img/faces/avatar-1163530ca19b5cebe1b002b8ec67b6fc.jpg",
                "http://www.marketingtool.online/en/face-generator/img/faces/avatar-1116395d6e6a6581eef8b8038f4c8e55.jpg",
                "http://www.marketingtool.online/en/face-generator/img/faces/avatar-11319be65db395d0e8e6855d18ddcef0.jpg",
            ]
        ), f"label {i}")
        for i in range(3)
    ]
    return images


with gr.Blocks() as demo:
    gallery = gr.Gallery(
        label="Generated images", show_label=False, elem_id="gallery"
    , columns=[3], rows=[1], object_fit="contain", height="auto", allow_preview=False, selected_index=1)
    selected_item = gr.Number(precision=0, label="selected gallery item")
    btn = gr.Button("Generate images", scale=0)

    btn.click(fake_gan, None, gallery)

    # gradio v 4.19.1 selecting image from gallery works fine when gallery block has selected_index=1
    def get_select_index(evt: gr.SelectData):
        return evt.index+1
    gallery.select(get_select_index, None, selected_item)

if __name__ == "__main__":
    demo.launch()

	`


As you can see, when clicking the button that generates gallery items, the default selected should be number 1, but the border is around item 2. And when clicking on 1 or 3, the selected index will show 1 or 3 on the Number component but the border is still around item 2. And when clicking on item 2, it still shows that the selected index is 1.  Why can't I select item number 2?
It used to work fine with the old gradio version.

**Comment by peeter2** [comment]
```
import random

import gradio as gr
def fake_gan():
    images = [
        (random.choice(
            [
                "http://www.marketingtool.online/en/face-generator/img/faces/avatar-1151ce9f4b2043de0d2e3b7826127998.jpg",
                "http://www.marketingtool.online/en/face-generator/img/faces/avatar-116b5e92936b766b7fdfc242649337f7.jpg",
                "http://www.marketingtool.online/en/face-generator/img/faces/avatar-1163530ca19b5cebe1b002b8ec67b6fc.jpg",
                "http://www.marketingtool.online/en/face-generator/img/faces/avatar-1116395d6e6a6581eef8b8038f4c8e55.jpg",
                "http://www.marketingtool.online/en/face-generator/img/faces/avatar-11319be65db395d0e8e6855d18ddcef0.jpg",
            ]
        ), f"label {i}")
        for i in range(3)
    ]
    return images, gr.Number(value=1)

with gr.Blocks() as demo:
    gallery = gr.Gallery(label="Generated images", show_label=False, columns=[3], allow_preview=False, selected_index=1)
    selected_item = gr.Number(precision=0, label="selected gallery item")
    btn = gr.Button("Generate images", scale=0)

    btn.click(fake_gan, None, outputs=[gallery, selected_item])

    def get_select_index(evt: gr.SelectData):
        return evt.index
    gallery.select(get_select_index, None, selected_item)

if __name__ == "__main__":
    demo.launch()
```

As you can see, when the gallery has the parameter gr.Gallery(selected_index=1) then no matter which image I click on, the border highlight is still around the middle image. 
With the old version of Gradio the border changed fine to the correct image that was clicked on.

**Comment by peeter2** [comment]
Hello. Just a gentle reminder on this. Is there a fix or a work around for this?

**Comment by abidlabs** [comment]
Hi @peeter2 I took a look and I can't repro the issue you are describing. Are you sure you are running on the latest version of `gradio`? You can try installing gradio from `main` by following the instructions here: https://www.gradio.app/main/docs/interface

https://github.com/gradio-app/gradio/assets/1778297/2bd95c85-1c3e-4366-87da-f9689ec22c23

**Comment by peeter2** [comment]
You are right, sorry about that, seems like the issue is fixed as I just updated gradio.
