### ISSUE TITLE
Close Progress for the specified component

### ISSUE THREAD

**Issue by DuskXi** [gradio-app/gradio#8016]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

I need to update Plot information to gradient every epoch during the training process, but progress covers all outputs. At the same time, it seems that I also found in the experiment that gr.update() is not allowed to be used in click, and the call is invalid. This directly causes me to not be able to use progress if I want to update the chart. If I want to use progress, I have to endure the problem of the chart being overwritten.

**Describe the solution you'd like**  
Provide a show_progress parameter in Component to determine whether this component displays a progress bar on the web.

Or use a context manager similar to with ShowProgress():

Or directly provide a component named ProgressBar to separate the progress bar from the component box that needs to display data.

**Additional context**

**Comment by abidlabs** [comment]
Hi @DuskXi this show_progress parameter exists but it’s on the event itself e.g. click() rather than in the component!

**Comment by Josef-Ouano** [comment]
I concur with his proposal.
its kind of a bummer the progress bar covers all outputs, instead of being able to turn off individually by component.
Is it possible to put this on the component level?

**Comment by elismasilva** [comment]
@abidlabs could be possible for disable show_progress like show_progress = False by output compontent. 

If my event has outputs = [component1, component2]
we could have like this, show_progress=[True, False] it same component order.

**Comment by abidlabs** [comment]
Yeah tbh I think that's a good idea, I'll comment on a relevant issue
