### ISSUE TITLE
ImageEditor event response time too long, it seems to have been lost

### ISSUE THREAD

**Issue by Mr-Jin2** [gradio-app/gradio#8018]
### Describe the bug

When I use ImageEditor as input/output and upload a large image (1024x1024, 105k), the preprocessing time is particularly long, and there is a high probability that trigger events will be lost.
![image](https://github.com/gradio-app/gradio/assets/38421253/92b9db03-70cf-48cb-9fe4-758467bc69a7)

upload image:
![dog](https://github.com/gradio-app/gradio/assets/38421253/1632afc0-0b8d-4159-bcfa-bc47424abc24)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
with gr.Blocks() as demo:
    def image_process(image_dict):
        print("yes")
        time.sleep(5)
        image = image_dict["background"]
        image = np.array(image)[:, :, ::-1]
        image_dict["background"] = image
        return image_dict

    with gr.Row():
        image = gr.ImageEditor(label="brush",
                               type="pil",
                               sources="upload",
                               transforms=[],
                               interactive=True,

                               show_download_button=True,
                               )
        btn = gr.Button(
            "btn", size="sm")
        btn.click(image_process,
                  [image],
                  [image])

demo.queue().launch(
    share=True,
    server_port=8081,
    server_name="0.0.0.0",
)
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/38421253/cb3b7db6-9d5f-4e76-beab-4324ae87d770)

### System Info

```shell
system info:
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"

python:
Python 3.8.19

gradio:
Name: gradio
Version: 4.22.0
Summary: Python library for easily interacting with trained machine learning models
Home-page: 
Author: 
Author-email: Abubakar Abid <gradio-team@huggingface.co>, Ali Abid <gradio-team@huggingface.co>, Ali Abdalla <gradio-team@huggingface.co>, Dawood Khan <gradio-team@huggingface.co>, Ahsen Khaliq <gradio-team@huggingface.co>, Pete Allen <gradio-team@huggingface.co>, Ömer Faruk Özdemir <gradio-team@huggingface.co>, Freddy A Boulton <gradio-team@huggingface.co>, Hannah Blair <gradio-team@huggingface.co>
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio
