### ISSUE TITLE
Gradio docs linking in Huggingface Docs

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#802]
It could be better to link gradio docs inside the HuggingFace docs, WDYT @abidlabs , @aliabd ?

Thanks to @thomwolf for the feedback 😸

**Comment by abidlabs** [comment]
Yup that would be super nice to have a link. But this should be an issue on the repo for the hugging face docs?

**Comment by FarukOzderim** [comment]
Good idea!
