### ISSUE TITLE
Vertical Orientation for Tabs

### ISSUE THREAD

**Issue by Anyaj1** [gradio-app/gradio#8027]
- [X] I have searched to see if a similar issue already exists.

Requesting a feature update to vertically orient the tabs, like a sidebar.

**Comment by soumitsalman** [comment]
Requesting the same feature

**Comment by abidlabs** [comment]
Maybe something to consider for 5.0 @hannahblair

**Comment by soumitsalman** [comment]
My current use case is for a sidebar/side panel so that I can give a page
list like view

**Comment by abidlabs** [comment]
Going to close this issue in favor of https://github.com/gradio-app/gradio/issues/9117

**Comment by avylove** [comment]
I'm not sure how a sidebar is a good substitute for vertical tabs. [Vertical tabs](https://mui.com/material-ui/react-tabs/#vertical-tabs) are often used in mini-menus for example to toggle different views of categories.

**Comment by libokj** [comment]
Yea the current sidebar in gradio is not a good substitute for vertical tabs. The sidebar streamlit has now is ideal.

**Comment by abidlabs** [comment]
@libokj can you explain what you mean by navigation pane?
