### ISSUE TITLE
UI does not update with a new output

### ISSUE THREAD

**Issue by erogol** [gradio-app/gradio#803]
### Describe the bug

When the user runs a new model, the audio player does not update.

### Reproduction

Please try out on the UI https://huggingface.co/spaces/erogol/CoquiTTS

### System Info

```shell
The default on the HF Spaces.
```

### Severity

annoyance

**Comment by aliabid94** [comment]
Yikes, I thought we fixed this. Taking a look

**Comment by aliabid94** [comment]
Fixed in 2.8.10! Let me know if you have any issues still.
