### ISSUE TITLE
concurrency_limit bug

### ISSUE THREAD

**Issue by SnowWindDancing** [gradio-app/gradio#8034]
### Describe the bug

When I use gradio==3.50.2, the browser concurrency test can work normally;
When I use gradio==4.26.0, the following issues occur:
When the third tag is opened in the same browser, it cannot be streamed back;
The third tag can be streamed back, but the fourth tag cannot be opened.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

server.py
```python
from fastapi import FastAPI
from fastapi.responses import StreamingResponse
import asyncio
import time
from pydantic import BaseModel

app = FastAPI()



class Item(BaseModel):
    msg: str


@app.post("/stream")
async def stream(item: Item):

    async def event_stream():
        while True:

            yield '{} data: {}\n\n'.format(item.msg, time.ctime())

            await asyncio.sleep(2) 

    return StreamingResponse(event_stream(), media_type="text/event-stream")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)



```
demo.py
```python
import random
import gradio as gr
import requests
import json
from fastapi import FastAPI
from fastapi.responses import StreamingResponse
import asyncio
import time
from pydantic import BaseModel
import uvicorn


def random_response(message, history):
    time.sleep(10)
    return random.choice(["Yes", "No"])


def chat(message, history):
    # SSE URL
    url = 'http://localhost:8000/stream'

    # JSON payload
    payload = {'msg': '你好'}

    # Headers for SSE request
    headers = {
        'Content-Type': 'application/json',
        'Accept': 'text/event-stream'
    }

    # Send SSE request
    response = requests.post(url,
                             data=json.dumps(payload),
                             headers=headers,
                             stream=True)

    # Check if the request was successful
    if response.status_code == 200:
        # Process the SSE stream
        for line in response.iter_lines():
            if line:
                decoded_line = line.decode('utf-8')
                yield decoded_line
    else:
        print(f"Request failed with status code: {response.status_code}")

    # Close the connection
    response.close()

# pip install gradio==4.26.0 
#gr.ChatInterface(chat).queue(default_concurrency_limit=10).launch(server_name='0.0.0.0',server_port=8001)

# pip install gradio==3.50.2                                                 
gr.ChatInterface(chat).queue(concurrency_count=10).launch(server_name='0.0.0.0',server_port=8001)

```

### System Info

```shell
windows10
```

### Severity

I can work around it

**Comment by SnowWindDancing** [comment]
python3.8.0

aiofiles                  23.1.0
aiohttp                   3.8.4
aiosignal                 1.3.1
altair                    4.2.2
altgraph                  0.17.2
annotated-types           0.6.0
anyio                     3.6.2
APScheduler               3.10.1
argon2-cffi               21.3.0
argon2-cffi-bindings      21.2.0
asgiref                   3.4.1
asttokens                 2.0.5
async-generator           1.10
async-timeout             4.0.2
attrs                     21.2.0
audioread                 3.0.0
autopep8                  2.0.4
backcall                  0.2.0
backports.zoneinfo        0.2.1
beautifulsoup4            4.10.0
black                     21.12b0
bleach                    4.1.0
blinker                   1.6.2
bs4                       0.0.1
cachetools                5.3.1
certifi                   2019.11.28
cffi                      1.15.0
chardet                   3.0.4
charset-normalizer        3.1.0
click                     8.0.3
colorama                  0.4.3
comtypes                  1.1.14
cryptography              36.0.0
cycler                    0.10.0
debugpy                   1.5.1
decorator                 5.1.1
defusedxml                0.7.1
distro                    1.9.0
Django                    3.2.9
entrypoints               0.3
et-xmlfile                1.1.0
executing                 0.8.2
fastapi                   0.110.0
ffmpy                     0.3.0
filelock                  3.10.0
Flask                     2.2.2
frozenlist                1.3.3
fsspec                    2024.2.0
future                    0.18.2
gitdb                     4.0.10
GitPython                 3.1.31
gradio                    3.50.2
gradio_client             0.6.1
h11                       0.14.0
httpcore                  1.0.4
httpx                     0.27.0
huggingface-hub           0.21.3
idna                      2.10
importlib-metadata        7.0.1
importlib-resources       5.4.0
ipykernel                 6.7.0
ipython                   8.0.1
ipython-genutils          0.2.0
ipywidgets                7.6.5
itsdangerous              2.1.2
jedi                      0.18.1
Jinja2                    3.1.3
joblib                    1.1.0
jsonschema                4.4.0
jupyter                   1.0.0
jupyter-client            7.1.2
jupyter-console           6.4.0
jupyter-core              4.9.1
jupyterlab-pygments       0.1.2
jupyterlab-widgets        1.0.2
kiwisolver                1.3.1
lazy_loader               0.1
librosa                   0.10.0.post1
linkify-it-py             2.0.0
litellm                   1.29.1
llvmlite                  0.39.1
lxml                      4.6.4
markdown-it-py            2.2.0
MarkupSafe                2.1.1
matplotlib                3.3.3
matplotlib-inline         0.1.3
mdit-py-plugins           0.3.3
mdurl                     0.1.2
mistune                   0.8.4
mpmath                    1.3.0
msgpack                   1.0.5
multidict                 6.0.4
mypy-extensions           0.4.3
nbclient                  0.5.10
nbconvert                 6.4.1
nbformat                  5.1.3
neobolt                   1.7.16
neotime                   1.7.4
nest-asyncio              1.5.4
networkx                  3.0
neurolab                  0.3.5
notebook                  6.4.8
numba                     0.56.4
numpy                     1.22.4
openai                    1.13.3
openpyxl                  3.1.2
orjson                    3.8.10
outcome                   1.1.0
packaging                 21.3
pandas                    1.3.4
pandocfilters             1.5.0
parso                     0.8.3
pathspec                  0.9.0
pefile                    2021.9.3
pickleshare               0.7.5
Pillow                    8.1.0
pip                       21.3.1
platformdirs              3.1.1
pooch                     1.7.0
prometheus-client         0.13.0
prompt-toolkit            2.0.10
protobuf                  4.23.2
pure-eval                 0.2.2
pyarrow                   12.0.0
PyAudio                   0.2.13
pycodestyle               2.11.1
pycparser                 2.21
pydantic                  2.6.3
pydantic_core             2.16.3
pydeck                    0.8.1b0
pydub                     0.25.1
Pygments                  2.15.1
pyinstaller               4.7
pyinstaller-hooks-contrib 2021.3
Pympler                   1.0.1
pyOpenSSL                 21.0.0
pyparsing                 2.4.7
pypiwin32                 223
pyrsistent                0.18.1
python-dateutil           2.8.1
python-dotenv             1.0.1
python-multipart          0.0.9
python-pptx               0.6.21
pyttsx3                   2.90
pytz                      2019.3
pytz-deprecation-shim     0.1.0.post0
pywin32                   303
pywin32-ctypes            0.2.0
pywinpty                  2.0.1
PyYAML                    6.0
pyzmq                     19.0.2
qtconsole                 5.2.2
QtPy                      2.0.0
regex                     2023.5.5
requests                  2.31.0
rich                      13.4.1
ruff                      0.3.0
scikit-learn              1.0.2
scipy                     1.7.3
selenium                  4.1.0
semantic-version          2.8.5
Send2Trash                1.8.0
setuptools                59.2.0
setuptools-rust           1.0.0
shellingham               1.5.4
six                       1.13.0
smmap                     5.0.0
sniffio                   1.2.0
sortedcontainers          2.4.0
soundfile                 0.12.1
soupsieve                 2.3.1
soxr                      0.3.4
SpeechRecognition         3.9.0
sqlparse                  0.4.2
stack-data                0.1.4
starlette                 0.36.3
streamlit                 1.23.1
sympy                     1.11.1
tenacity                  8.2.2
terminado                 0.13.0
testpath                  0.5.0
threadpoolctl             3.0.0
tiktoken                  0.6.0
tokenizers                0.13.3
toml                      0.10.2
tomli                     1.2.2
tomlkit                   0.12.0
toolz                     0.12.0
torch                     2.0.0
torchaudio                2.0.1
torchvision               0.15.1
tornado                   6.1
tqdm                      4.65.0
traitlets                 5.1.1
transformers              4.29.1
trio                      0.19.0
trio-websocket            0.9.2
typer                     0.9.0
typing_extensions         4.10.0
tzdata                    2023.3
tzlocal                   4.3
uc-micro-py               1.0.1
urllib3                   1.26.7
uvicorn                   0.21.1
validators                0.20.0
watchdog                  3.0.0
wcwidth                   0.1.7
webencodings              0.5.1
websockets                11.0.1
Werkzeug                  2.2.2
widgetsnbextension        3.5.2
wsproto                   1.0.0
xlrd                      2.0.1
XlsxWriter                3.1.0
xlwt                      1.3.0
yarl                      1.8.2
zipp                      3.7.0

**Comment by SnowWindDancing** [comment]
same question in linux docker `from python:3.11`

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio

**Comment by SnowWindDancing** [comment]
Concurrent issues still exist

**Comment by SnowWindDancing** [comment]
Concurrent issues still exist
