### ISSUE TITLE
Uploaded event

### ISSUE THREAD

**Issue by marcoquin** [gradio-app/gradio#8035]
thanks for the tremendous work on gradio !

**Is your feature request related to a problem? Please describe.**  
I'm trying to use gr.components.Audio. I would like to use a button that transform an audio file into text. To do so, when I'm using it with a big file, I use the upload event to set the submit_button (interactive=False) but I can't use another event to know when the upload is finished.

**Describe the solution you'd like**  
Is there a way to do another event as upload (for exemple upload_finished) that is trigger when the upload is finished. 

Thanks again and if you have any idea of how to solve my pb without any feature, you would save me.

**Comment by freddyaboulton** [comment]
HI @marcoquin , it's my understanding the upload event is triggered after the upload finishes. I think you can have the submit button by disabled by default and enable it in the `upload` event.

**Comment by abidlabs** [comment]
Yes what @freddyaboulton described is indeed the case, as can be verified by a simple demo:

```py
import gradio as gr

with gr.Blocks() as demo:
    a = gr.Audio()
    b = gr.Button()
    a.upload(lambda : gr.Button(interactive=False), None, b)
    
demo.launch()
```

We're also working on a built-in solution in Gradio as described here: https://github.com/gradio-app/gradio/issues/3382, bu5 in the meantime, this should suffice
