### ISSUE TITLE
Using SCSS for Gradio Custom Components

### ISSUE THREAD

**Issue by MobisParkHeekang** [gradio-app/gradio#8044]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

Currently, it seems like only pure CSS is available for creating Gradio custom components; CSS preprocessors are not supported.

**Describe the solution you'd like**  

I hope to be able to use CSS preprocessors like SCSS/SASS for creating Gradio custom components.

**Comment by abidlabs** [comment]
cc @pngwn @freddyaboulton

**Comment by abidlabs** [comment]
Out of curiosity what kind of custom component(s) are you interested in building @MobisParkHeekang?

**Comment by MobisParkHeekang** [comment]
@abidlabs I am building a custom component for RAG system. I want to show both documents that LLM refered to generate answer and the generated answer.
