### ISSUE TITLE
I don't see a function to hide the "Process flag being generated" in the ChatInterface feature list.

### ISSUE THREAD

**Issue by a624090359** [gradio-app/gradio#8047]
- [x ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I don't want any changes to the interface before the big model returns, but want to simulate real conversations

**Describe the solution you'd like**  
Add Related Functions

**Comment by abidlabs** [comment]
Hi @a624090359 I don't understand this issue? Can you please provide more details on what code you are running, what output you are seeing, and what you'd like to see instead?

I'm going to close this issue since it is lacking critical details, but I can reopen once we have more information.

**Comment by a624090359** [comment]
> Hi @a624090359 I don't understand this issue? Can you please provide more details on what code you are running, what output you are seeing, and what you'd like to see instead?
> 
> I'm going to close this issue since it is lacking critical details, but I can reopen once we have more information.

I want to change the style of this,or set visible=False
![github](https://github.com/gradio-app/gradio/assets/76862174/8c2c82bb-0a03-45c1-937e-18550e0c37d9)

**Comment by abidlabs** [comment]
You can do this by setting `show_progress=False` in the event that populates the Chatbot component as output
