### ISSUE TITLE
ChatBot processing box doesn't autofit

### ISSUE THREAD

**Issue by Anyaj1** [gradio-app/gradio#8053]
### Describe the bug

When the height is more than the default value, the orange box doesn't autofit the chat box and text appears over it.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import os
import gradio as gr
from openai import AzureOpenAI

client = AzureOpenAI(
        ## model API
)

def create_output(prompt):
    response = client.chat.completions.create(
        model="xxxxx",
        messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": prompt},
    ],
        temperature=0.9,
        max_tokens=1200,
        top_p=1,
        stop=None,
        stream=True,
    )
    partial = ""
    for chunk in response:
        if chunk.choices:
            if (chunk.choices[0].delta.content is not None) and (
                len(chunk.choices[0].delta.content) > 0
            ):
                partial += chunk.choices[0].delta.content
                yield partial

def chat_clone(input,history):
    output = create_output(input)
    for partial in output:
        yield partial

block = gr.Blocks()

with block:
    chat_interface = gr.ChatInterface(
    fn=chat_clone,
    fill_height=True,
    chatbot=gr.Chatbot(height=1000,render=False),
    examples=['Write a 1000 word essay on Space'],
    )
block.launch()
```

### Screenshot

<img width="766" alt="image" src="https://github.com/gradio-app/gradio/assets/148311507/e6f3f636-48ae-4ffa-aad3-1f099ad860e1">

### System Info

```shell
Operating System: Windows
gradio version: 4.26.0
gradio_client version: 0.15.1
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hmm I believe it should autofit -- can you please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by abidlabs** [comment]
Closing for lack of follow up. We can reopen once we have a repro.

**Comment by Anyaj1** [comment]
Added code to reproduce the issue.

**Comment by abidlabs** [comment]
This should no longer be an issue in the latest version of gradio (4.38.1) -- if you're still seeing this, we can reopen
