### ISSUE TITLE
DuckDB SQL interface with Gradio and FastAPI

### ISSUE THREAD

**Issue by liquidcarbon** [gradio-app/gradio#8057]
Hello, I'd like to build a SQL interface with Gradio Code block that renders a [jQuery-powered Datatables](https://datatables.net/) in another div.  I would also like the SQL code form to be prepopulated by decoding base64-encoded URL path, which should change when I modify the query.

Overall functionality should be similar to [this tool from DuckDB devs](https://sql-workbench.com/#queries=v0,select-Symbol%2C-Number%2C-Mass%2C-Abundance-from-%27https%3A%2F%2Fraw.githubusercontent.com%2Fekwan%2Fcctk%2Fmaster%2Fcctk%2Fdata%2Fisotopes.csv%27~).

With guidance from #1608 and #2654 I got 80% of the way there, but I'm struggling with the last bit.
![image](https://github.com/gradio-app/gradio/assets/47034358/2f809490-701e-409e-a3f3-1d894b735328)

There are two main routes I tried:
1.  Use only gradio.  It was easy enough to get the basic functionality, but I found it difficult to modify the the `gr.HTML` to accommodate additional JS and CSS that I need to make the table look and work the way I need.  And I have no idea how to handle redirects and URL construction.

2.  Mount gradio into FastAPI.  The closest I got was using iframes.  However, the using `link` attribute in button, the modified query opens inside an iframe.  If I use `button.click(None, [], [], js=f"window.open(...)")`, I'm getting a new URL, but the modified query is not executed, and I'm getting huge tracebacks in the logs, probably because I'm unintentionally recursively modifying the main `app` instance.

And advice to get this to work?

Thanks in advance!

**Comment by liquidcarbon** [comment]
Code:

```

@app.get("/sql/{base64query}", response_class=HTMLResponse)
def query_db(base64query: str|None = None):
    decoded = Q.from_base64(base64query)
    q = Q(decoded.format(**TABLES))
    log.debug(q)
    try:
        if not q.is_safe:
            raise Exception("naughty!")
        df = q.df(_raise=True)
    except Exception as e:
        df = pd.DataFrame({"error": [e.__str__()]})

    # build_gradio_sql_interface(decoded)
    with gr.Blocks() as gradio_sql_interface:
        sql_code = gr.Code(value=decoded, language="sql", label="SQL Query", interactive=True)
        button = gr.Button("run") #, link=f"/sql/{Q(sql_code.value).base64}")
        button.click(None, [], [], js=f"window.open('/sql/{Q(sql_code.value).base64}', '_top')")
    gr.mount_gradio_app(app, gradio_sql_interface, path="/sqlgradio")
 
    query_result_html = Templates("table.html").render(
            header=df.columns,
            data=df.values,
            table_caption=f"Query results",
            table_classes="table table-bordered table-hover table-striped my-2 caption-top",
        )
    html = f"""
    <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    </head>
    <div class="container-fluid py-1 bg-light-subtle">
    <h3>QPRST!</h3>
    <div class="row m-3 bg-light-subtle">
        <div class="col-4">
            <iframe id="sql_iframe" src="/sqlgradio" width="100%" height="100%"></iframe>
        </div>
        <div class="col-8">
            {query_result_html}
        </div>
    </div>
    </div>

    """
    return html
```


where Q is:
```
import duckdb
class Q(str):
    """Convenient query string.
    
    Use for querying local files or remote SQL servers.


    Attributes
    ----------
    count : str
        Wraps original query into CTE and returns its row counts.    
    """

    UNSAFE = ["CREATE", "DELETE", "DROP", "INSERT", "UPDATE"]
    
    def __init__(self, query: str):
        self.is_safe = not any([cmd in query.upper() for cmd in self.UNSAFE])
        self.lines = query.split("\n")

    def run(self, sql_engine=None):    
        try:
            if sql_engine is None:
                return self.run_duckdb()
            else:
                return self.run_sql(sql_engine)
        except Exception as e:
        pass   
    def run_duckdb(self):
        return duckdb.sql(self)

    def df(self, sql_engine=None):
        result = self.run(sql_engine=sql_engine)
        if result is None: return
        result_df = result.df()
        return result_df
```

**Comment by abidlabs** [comment]
Hi @liquidcarbon, for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB) where we have a larger community that can help answer these questions. (I'll close this issue)

**Comment by liquidcarbon** [comment]
@abidlabs thanks for your message.  I saw that for general questions you're invited to go to Discord but I thought this could belong under new guide or feature request.

There is not a lot of examples in the docs on solutions related to FastAPI and gradio.  I'd be happy to contribute one if you find this use case interesting, but I need some help :)

Personally, I'm excited about gradio because it becomes much easier to integrate nascent ML projects into existing FastAPI infra.  It is my impression that though gradio mainly serves ML UI use cases, it is underappreciated as a general purpose tool for building interesting apps with (almost) pure python.  I think FastAPI backend is a huge advantage of gradio compared to, say, Streamlit (Tornado and no plans for supporting others per  https://github.com/streamlit/streamlit/issues/4567).

**Comment by abidlabs** [comment]
For sure, thanks @liquidcarbon! I think this is possible with Gradio currently, so it doesn't need to be feature request

**Comment by liquidcarbon** [comment]
Perhaps a guide request then?

**Comment by abidlabs** [comment]
Its a bit niche as a Guide, instead I would publish your app as a public Space on Hugging Face (which supports FastAPI apps) and then it would get good visibility and serve as an informal guide to other users.

**Comment by liquidcarbon** [comment]
ok I'm mostly there
I almost gave up, then ran into  https://github.com/gradio-app/gradio/issues/7464#issuecomment-1960161591

![image](https://github.com/gradio-app/gradio/assets/47034358/256a8b64-c0ce-4c5f-8ed7-1c75c9f50a47)


```
import gradio as gr
import pandas as pd
from fastapi import FastAPI
from fastapi.responses import HTMLResponse, RedirectResponse
from itables import to_html_datatable

from sql import Q

app = FastAPI()

def query_from_request(query, request: gr.Request):
    """Process query from input block or from initial request.

    https://github.com/gradio-app/gradio/issues/7464#issuecomment-1960161591
    """
    if not query:
        query_params = request.query_params
        base64query = dict(query_params).get("q")
    else:
        base64query = Q(query).base64
    if base64query in (None, "example"):
        decoded = Q("""SELECT 42 AS answer, 'LU & E' AS question""")
        base64query = decoded.base64
    else:
        decoded = Q.from_base64(base64query)
    href = format_href(base64query)
    result = f"""<iframe src="/q/{base64query}" width="90%" height="90%"></iframe>"""
    return (decoded, href, result)

def format_href(url: str):
    href=f"localhost:7860/sql/{url}"
    return f"""<a href="{href}">{href}</a>"""

@app.get("/q/{base64query}", response_class=HTMLResponse)
def query_db(base64query: str|None = None):
    decoded = Q.from_base64(base64query)
    df = decoded.df()
    html = to_html_datatable(df)
    return f"""
        <h3>{decoded}</h3>
        <div>{html}</div>
    """

with gr.Blocks() as gradio_sql_interface:
    with gr.Row():
        with gr.Column():
            header = gr.Markdown("# SQL Editor")
            sql_code = gr.Code(language="sql", label="SQL Query", interactive=True)
            copy_button = gr.HTML()
            button = gr.Button("run")
        with gr.Column():
            markdown = gr.Markdown("# RESULTS")
            results = gr.HTML()
    button.click(query_from_request, [sql_code], [sql_code, copy_button, results]) 
    gradio_sql_interface.load(query_from_request, [sql_code], [sql_code, copy_button, results], queue=True)

app = gr.mount_gradio_app(app, gradio_sql_interface, path="/sql")

@app.get("/")
@app.get("/sql")
@app.get("/sql/")
def redirect_to_example():
    return RedirectResponse("/sql/?q=example")
```

**Comment by abidlabs** [comment]
Awesome so is everything working now or did you run into any bugs / issues?
