### ISSUE TITLE
Lower typer requirements back to 0.9

### ISSUE THREAD

**Issue by Paillat-dev** [gradio-app/gradio#8072]
- [x] I have searched to see if a similar issue already exists.

Related PR: #8050 

**Is your feature request related to a problem? Please describe.**  
In the latest gradio update, the typer dependency requirements have been bumped to `0.12`, however, `0.12` is typer's latest release and such strict requirement make it hard to work with other libraries, like https://github.com/explosion/spaCy which in its latest releases requires `typer<0.10` and in older ones `typer<0.8`
https://github.com/gradio-app/gradio/blob/72f4ca88ab569aae47941b3fb0609e57f2e13a27/requirements.txt#L25

**Describe the solution you'd like**  
Going back to a lower requirement like version `0.9`, which is less than one year old.

**Comment by adamgogogo** [comment]
I fond the same problem:

gradio 4.28.2 requires typer<1.0,>=0.12; sys_platform != "emscripten", but you have typer 0.9.4 which is incompatible.

**Comment by Paillat-dev** [comment]
@adamgogogo spacy will upgrade in next update
