### ISSUE TITLE
Event handler .then not accepting multiple inputs

### ISSUE THREAD

**Issue by mberco-quandl** [gradio-app/gradio#8079]
### Describe the bug

When passing in the values of multiple gr.Text objects into a function triggered by .then() event handler using the `inputs` parameter I get the error:

```
2024-04-19 15:09:07 frontend-1  | ValueError: An event handler (action_two) didn't receive enough input values (needed: 2, got: 1).
2024-04-19 15:09:07 frontend-1  | Check if the event handler calls a Javascript function, and make sure its return value is correct.
2024-04-19 15:09:07 frontend-1  | Wanted inputs:
2024-04-19 15:09:07 frontend-1  |     [<gradio.components.textbox.Textbox object at 0x7f09cae6ff10>, <gradio.components.textbox.Textbox object at 0x7f09cae45cd0>]
2024-04-19 15:09:07 frontend-1  | Received inputs:
2024-04-19 15:09:07 frontend-1  |     ["B"]
```

However if I only pass in one or no inputs using the `inputs` parameter I and access the gr.Text objects using the local scope and their .value attribute, I get no errors. Seems like the input value attribute is what is actually being passed, and not the objects themselves? Is there something I am missing about the chaining of events - do inputs for subsequent events need to be outputs of previous ones?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Code that returns above error:
```python
import logging
import gradio as gr

LOGLEVEL = "INFO"
logging.basicConfig(level=LOGLEVEL)


def create_every_ui():
    with gr.Blocks(title="every") as interface:
        with gr.Tab("Inputs"):
            input_text_a = gr.Text(value="A")
            input_text_b = gr.Text(value="")
            input_text_c = gr.Text(value="C")
            output_text = gr.Text(value="")
            submit_button = gr.Button(value="Trigger actions")

            def action_one(input_text_a):
                return "B"

            def action_two(input_text_b, input_text_c):
                logging.info(input_text_b + input_text_c)
                return "OUTPUT"

            def dummy():
                return

            action_sequence = submit_button.click(
                action_one, inputs=input_text_a, outputs=input_text_b
            ).then(action_two, inputs=[input_text_b, input_text_c], outputs=output_text)

            output_text.change(dummy, cancels=action_sequence)

    return interface
```
Working code:
```python
import logging
import gradio as gr

LOGLEVEL = "INFO"
logging.basicConfig(level=LOGLEVEL)


def create_every_ui():
    with gr.Blocks(title="every") as interface:
        with gr.Tab("Inputs"):
            input_text_a = gr.Text(value="A")
            input_text_b = gr.Text(value="")
            input_text_c = gr.Text(value="C")
            output_text = gr.Text(value="")
            submit_button = gr.Button(value="Trigger actions")

            def action_one(input_text_a):
                return "B"

            def action_two(input_text_b):
                logging.info(input_text_b + input_text_c.value)
                return "OUTPUT"

            def dummy():
                return

            action_sequence = submit_button.click(
                action_one, inputs=input_text_a, outputs=input_text_b
            ).then(action_two, inputs=input_text_b, outputs=output_text)

            output_text.change(dummy, cancels=action_sequence)

    return interface

```

### System Info

```shell
I am funning a default FastAPI() app and using gr.mount_gradio_app to mount individual UI's such as the one above to new routes.
Dockerfile:
FROM python:3.11-slim as base

ARG WORKDIR
WORKDIR /app
ENV PYTHONPATH=/app
COPY requirements.txt requirements.txt
COPY src/ /app

docker-compose.yml:
version: '2.4'
services:
  frontend:
    build: .
    command:
      - uvicorn
      - --host
      - '0.0.0.0'
      - --port
      - '7860'
      - --reload
      - main:app
      - --ws-ping-timeout
      - '1'
    volumes:
     - ./src:/app
    ports:
      - "7860:7860"
    env_file:
      - .env

requirements.txt:
gradio
fastapi
uvicorn
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @mberco-quandl I can't repro this issue locally or in Colab. For example, see https://colab.research.google.com/drive/1gNNKC5PyK8kWjDLVAzJAoD_Aqe_v24ib?usp=sharing

Can you confirm that you are on the latest version of gradio? If you can share a repro such a a Colab notebook, that'd be helpful

**Comment by mberco-quandl** [comment]
Thank you very much @abidlabs . I assumed I was using the latest version of gradio, but upon rebuilding my docker image with the exact same source code I cannot replicate the behaviour. Guess you guys shipped some updates in the past week! Just want to take the opportunity to thank you and the team again for your responsiveness and hard work. Really love using Gradio!

**Comment by mberco-quandl** [comment]
Thank you very much @abidlabs . I assumed I was using the latest version of gradio from an image I built last week, but upon rebuilding my docker image as you suggested I cannot replicate the behaviour. Guess you guys shipped some updates in the past week during the time I was working on the event handlers. Just want to take the opportunity to thank you and the team again for your responsiveness and hard work. Really love using Gradio!
