### ISSUE TITLE
Add an optional checkbox toggle marker for chatbot entries similar to like/dislike

### ISSUE THREAD

**Issue by one-lithe-rune** [gradio-app/gradio#8089]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**

I want users to be able to select chatbot entries for further processing.

Like/dislike doesn't *quite* fit my use case, as I'm not asking them to express an opinion, and trying to use like and dislike for it, when the only way to unselect something they've previously selected by 'liking' it, being 'disliking' it, would be an horrible user experience.

**Describe the solution you'd like**  

Ideally the ability to show a separate toggle in the same area a like/dislike, shown as a filled or cleared checkbox.

However since I don't actually need the like/dislike functionality myself, something that allowed me to specify that I wanted checkbox toggles instead of like/dislike would also work for me.

Alternatively, and presumably much simpler, the ability for the user remove a like or an dislike toggling it off, rather setting the opposite might let me do something with CSS to hide 'dislike', and change the glyphs for 'like'.  Although I haven't verified that that would actually work.

Since I want to then clear any selections after processing, it would also be useful to have a way to toggle likes/dislikes/selection programmatically. However I'm pretty sure I can probably work around that in my case by clearing the Chatbox value and `.then` re-added it.

**Additional context**  

_No additional context_

**Comment by abidlabs** [comment]
Hi @one-lithe-rune you can use the `.select()` event to allow users to select individual messages, see https://github.com/gradio-app/gradio/issues/3813#issuecomment-1502888819 for an example

Its not quite the same UI that you've suggested, but if you'd like to create that, I'd recommend creating a custom Gradio component! If you'd like to create your own, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.
