### ISSUE TITLE
Trigger select event when the same image is selected in gallery

### ISSUE THREAD

**Issue by kexul** [gradio-app/gradio#8091]
- [x] I have searched to see if a similar issue already exists.

Hi, is it possible to trigger a select event when a gallery item is clicked? Even for same item, click multiple times and trigger multiple times.

**Comment by freddyaboulton** [comment]
Yes the `select` event is defined for the gallery but it will not trigger on repeated clicks.

**Comment by kexul** [comment]
> Yes the `select` event is defined for the gallery but it will not trigger on repeated clicks.

How can I trigger it on repeated clicks? It's is possible to to achieve that with custom javascript function? Many thanks!

**Comment by abidlabs** [comment]
Hi @kexul good question, we don't have a way of doing this right now. I don't think this is a bug as the semantics of `.select()` to me indicate selecting a different entry than the one that was previously selected. 

Couple of options:
* We could add a new event
* Or you could create a custom component that is a variant of `gr.Gallery` and has this behavior. I think this would be a great case for a custom component actually. If you'd like to create your own, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.

**Comment by kexul** [comment]
Hi @abidlabs, thanks for the information. I'm not familiar with javascript, creating a custom component is challenging for me. The reason that I need repeated click response is: 
There is situation in my use case that there is only one image in the gallery and the gallery is not responsive to user click when the image is updated.
```python
gallery.select(fn=image_process, ...)
```

I just find that I can bind another 'change' event listener to the handling function so that my problem is solved. 
```python
gallery.select(fn=image_process, ...)
gallery.change(fn=image_process, ...)
```
