### ISSUE TITLE
"Connection closed" Event listener

### ISSUE THREAD

**Issue by mberco-quandl** [gradio-app/gradio#8094]
- [Yes] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
No clear way to handle storage leaks that arise when a file exists in Gradio temp storage and a user closes the connection. If running Gradio UI on a docker container disk storage is limited and introducing this leak can cause issues quickly.

**Describe the solution you'd like**  
An event trigger for connection closed. This would allow the server to cleanup temp files associate with that specific connection that don't need to be preserved.

**Additional context**  
Thank you!

**Comment by freddyaboulton** [comment]
Hi @mberco-quandl ! There already is such an event! It is the `unload` event. It is triggered once a user closes their tab. See the docs [here](https://www.gradio.app/docs/blocks#blocks-unload)

However, gradio can already clean up files periodically for you with the `delete_cache` parameter of `Blocks`, `Interface`, `ChatInterface` 's init method

<img width="845" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/8fa377f9-9301-4da3-9d81-4bab4f9f884c">


Will close this in the meantime.

**Comment by mberco-quandl** [comment]
I love you guys for making life for frontend noobs a breeze.

**Comment by mberco-quandl** [comment]
@freddyaboulton Without inputs to the unload event listener how does one control which files to delete upon terminating the session?

**Comment by mberco-quandl** [comment]
@freddyaboulton for additional clarity I've tried referencing gr.File objects' path using the .value attribute but it always returns a None. I've tried adding nonlocal flags, other solutions, nothing works as intended yet.
