### ISSUE TITLE
How to achieve multiple outputs without displaying the results together？

### ISSUE THREAD

**Issue by goldwater668** [gradio-app/gradio#8101]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by freddyaboulton** [comment]
Hi @goldwater668 ? For general questions, please post in the "#gradio-questions" channel of the huggingface discord. Invite [link](https://discord.gg/r7nDFs3w).

But if you're using the Blocks api, you can place the output components wherever you'd like and return the data from your function!
