### ISSUE TITLE
more documentation about how to use http request

### ISSUE THREAD

**Issue by Marijsoft** [gradio-app/gradio#8104]
I hope someone can help me, my problem:

Time ago for use in another language the api of gradio you use 
post with json paypload now it's not possibile on huggingface.co

the problem don't have documentation for others language how to make post, for example i try for this one https://huggingface.co/spaces/tonyassi/fashion-try-on

before you make post on https://huggingface.co/spaces/tonyassi/fashion-try-on/api/predict with json payload
{"data": ["imagetobase64","imagetobase64"]} now it's not possible you have 
{"detail":"This API endpoint does not accept direct HTTP POST requests. Please join the queue to use this API."}

i try
https://huggingface.co/spaces/tonyassi/fashion-try-on/queue/join but have error session hash not found
i try this one 
https://huggingface.co/spaces/tonyassi/fashion-try-on/queue/join?data=&person=https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png&clothing=examplebus.png but nothing

what it is the correct way for make a post on https(like curl) for new gradio version??? i don't know i looking on google but nothing!
i hope someone can help me. thank you

**Comment by abidlabs** [comment]
Hi @Marijsoft yes this is something that we're working on, and have an existing issue here: https://github.com/gradio-app/gradio/issues/7331 so I'll go ahead and close
