### ISSUE TITLE
Add ability to disable Web sockets

### ISSUE THREAD

**Issue by ashishb** [gradio-app/gradio#8111]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Web sockets don't work with many PAAS solutions that do not support sticky sessions.

**Describe the solution you'd like**  
Provide an ability to explicitly disable web sockets

**Comment by pngwn** [comment]
Latest version don't actually use web sockets but use Server sent events instead. 

Could you provide more information on what platforms you have issues with and some example code/ an example application you have had difficulties with?

**Comment by ashishb** [comment]
Lots of https://github.com/gradio-app/gradio/issues/6920 when using Gradio on render.com

**Comment by freddyaboulton** [comment]
Hi @ashishb ! Gradio does not use websockets in versions 4 and above. We can't debug this issue unless you share a minimal reproducer.

**Comment by ashishb** [comment]
Happy to create a sample demo. render.com uses K8s underneath so I am not surprised that I am experiencing the same issue as mentioned in https://github.com/gradio-app/gradio/issues/6920

**Comment by abidlabs** [comment]
Goint to close this for now, but we can reopen with a repro
