### ISSUE TITLE
queue/join? 403 (Forbidden) Error for Cloud Run

### ISSUE THREAD

**Issue by lilsgit** [gradio-app/gradio#8112]
### Describe the bug

Hi there, 

I have a very simple Gradio app that display a data table (data from Bigquery), and the let users provide inputs and after submit it will update one row in that Bigquery table (using Gradio interface). 

The app works perfectly in my local. It was working in my cloud run instance as well, but 2 days ago I started to experience a bug that whenever I click submit button, it shows an error: `POST https://my-web/queue/join? 403 (Forbidden)`. Nothing has changed in the codebase and the app still works fine locally. I did not see any logs for this error either.

Tried to downgrade to Gradio 3.50 and 3.41, still have the same error.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
.......(code above)

                with gr.Row():
                    def submit_action(uuid_i, display_name_i, title_i, question_i, description_i, inputs_i,
                                      sql_query_i):

                        # Regular expressions for validating formats
                        uuid_regex = r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
                        inputs_regex = r'^\[[\s\S]*\]$'

                        if not all([uuid_i, display_name_i, title_i, question_i,
                                    description_i, inputs_i, sql_query_i]):
                            msg = gr.Warning("All fields must be filled out!")

                        if not re.match(uuid_regex, uuid_i):
                            msg = gr.Warning("Invalid UUID format!")

                        if not re.match(inputs_regex, inputs_i):
                            msg = gr.Warning("Invalid Inputs format!")

                        if 'SELECT' not in sql_query_i.upper() or 'FROM' not in sql_query_i.upper():
                            msg = gr.Warning("SQL query doesn't seem to be in Bigquery format!")

                        else:
                            msg = gr.Info("This approval is submitted!")

                            run_update = update_table(uuid_value=uuid_i, display_name=display_name_i,
                                                      title=title_i, question=question_i,
                                                      description=description_i, inputs=inputs_i,
                                                      sql_query=sql_query_i,
                                                      certify_value='vq')
                            if run_update == "Error!":
                                msg = gr.Warning("Something went wrong during submission, please contact your admin!")
                            else:
                                msg = gr.Info("This request is approved!")

                        return msg

                gr.Interface(fn=submit_action,
                             inputs=[uuid, displayName, title, question, description, inputs, sql_query],
                             outputs=gr.Info("Completed"))
demo.queue()

if __name__ == "__main__":
    demo.launch(share=False, server_name="0.0.0.0", server_port=8080, show_error=True)


```

### Screenshot

![Screenshot 2024-04-24 at 10 20 31](https://github.com/gradio-app/gradio/assets/48336265/2102a95f-d07a-4b73-bf6d-f3d6de65dc2b)
![Screenshot 2024-04-24 at 10 20 51](https://github.com/gradio-app/gradio/assets/48336265/d4e20119-d562-4659-b946-bb87adc0f1fe)

### Logs

```shell
No logs
```

### System Info

```shell
Gradio 4.27.0
```

### Severity

Blocking usage of gradio

**Comment by lilsgit** [comment]
Just found out what the issue is....

Somehow in the cloud run version the textArea does not like any special characters like *, \

**Comment by freddyaboulton** [comment]
Maybe it's blocking post requests with those characters out of fear of a sql injection attack? Maybe there is a way to disable that in cloud run.

**Comment by freddyaboulton** [comment]
In any event, this doesn't seem like a problem with gradio so I think we can close.

**Comment by lilsgit** [comment]
Thanks Freddy I am investigating the sql injection rules we have, seems like this. 

I would say though the debugging process is very very painful (took me 3 days to get here :( ) because the error message from Gradio is too generic and there is no logs to go about, if there is any chance to improve that it would be great. 

Thanks!

**Comment by freddyaboulton** [comment]
I think error reporting can be improved across the board but not sure if it would help in this case because if our hunch is right, cloud run is blocking the request in between the client and the server so not sure if there is away for gradio to know that.

Will close but thank you for filing and the feedback @lilsgit !
