### ISSUE TITLE
Update doc on max_workers

### ISSUE THREAD

**Issue by xianbaoqian** [gradio-app/gradio#8114]
### Describe the bug

<img width="697" alt="image" src="https://github.com/gradio-app/gradio/assets/38108242/1e7d7861-c97d-4dd4-ad7e-f62b25da3839">

max_workers seems to be deprecated by max_threads

https://github.com/gradio-app/gradio/blob/487db7b5d57e1a1350494efdf37c121cbf627780/gradio/blocks.py#L2037

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
n/a
```

### Severity

I can work around it

**Comment by mepc36** [comment]
+1, please merge/clarify when possible. Thanks!
