### ISSUE TITLE
[Custom Components] support custom components in gr.load

### ISSUE THREAD

**Issue by Col0ring** [gradio-app/gradio#8124]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I have a space with custom components, but `gr.load` is not working properly.

**Describe the solution you'd like**  
Support custom components in `gr.load`.

**Additional context**  
```
File "/Users/coloring/anaconda3/envs/gradio_4/lib/python3.12/site-packages/gradio/utils.py", line 525, in component_or_layout_class
    raise ValueError(f"No such component or layout: {cls_name}")
ValueError: No such component or layout: i18neditor
```
This error is caused by `gradio.utils.component_or_layout_class`, maybe `gradio` should expose some context or parameters of this method.

**Comment by abidlabs** [comment]
Makes sense — could you link to the Space you are trying to load or provide us a quick repro?

**Comment by Col0ring** [comment]
> Makes sense — could you link to the Space you are trying to load or provide us a quick repro?
Reproduce repo: https://huggingface.co/spaces/Coloring/gradio_load_test
