### ISSUE TITLE
'favicon_path' does not work with fastapi and mount_gradio_app 

### ISSUE THREAD

**Issue by tyc333** [gradio-app/gradio#8137]
### Describe the bug

I use favicon_path in blocks.launch() and it works, but it seems not work when I use the same path in  gradio.mount_gradio_app and fastapi.

Howerver, 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
from fastapi import FastAPI
from fastapi.responses import RedirectResponse
from fastapi.staticfiles import StaticFiles

import gradio as gr

app = FastAPI()

MAIN_ROUTE = "/main"

@app.get("/")
async def read_main():
    return RedirectResponse("/main")

app.mount("/static", StaticFiles(directory="static"), name="static")
gr.Markdown('''![logo](http://localhost:5000/static/logo.svg)''')  # This works

with gr.Blocks() as main_page:
    ......

# This path doesn't work, but I can get the image through localhost:5000/static/favicon.ico
app = gr.mount_gradio_app(app, main_page, path=MAIN_ROUTE, allowed_paths=["./"], favicon_path = "./static/favicon.ico") 

# not work either
# app = gr.mount_gradio_app(app, main_page, path=MAIN_ROUTE, allowed_paths=["./"], favicon_path = "http://localhost:5000/static/favicon.ico") 


```

### System Info

```shell
gradio==4.27.0
fastapi==0.1.0
```

### Severity

I can work around it

**Comment by Steveolas** [comment]
Getting the same issue, favicon_path works with blocks.launch() but not with mount_gradio_app. shows a "GET /favicon.ico HTTP/1.1" 404 Not Found error.

**Comment by freddyaboulton** [comment]
Browsers automatically send requests to `/favicon.ico`. Can you implement that in your top level FastAPI app? I think we have to remove the `favicon_path` parameter in `mount_gradio_app`.

**Comment by freddyaboulton** [comment]
I think we will print a warning when it's passed in and ask the user to instead add it to the parent application. Thanks @Steveolas

**Comment by freddyaboulton** [comment]
Do you want to open a PR for this @Steveolas ?

**Comment by Steveolas** [comment]
actually never looked at the gradio source code, I've just been using it lately and ran into this issue. If you can point me the the part of the source code that this is implemented i can open a PR to log a warning.

**Comment by freddyaboulton** [comment]
It would be here: https://github.com/gradio-app/gradio/blob/94a1143686733c7fe16e204764b9a3e7240ccf02/gradio/routes.py#L1222

We want to output a warning if `favicon_path` is not None and the `path` is not `/`

**Comment by yboussadia** [comment]
> Getting the same issue, favicon_path works with blocks.launch() but not with mount_gradio_app. shows a "GET /favicon.ico HTTP/1.1" 404 Not Found error.

please i used an endpoint fastapi /favicon.ico but still not working, i could see that you you were able to find a solution, may i know what was the issue for you ?
