### ISSUE TITLE
[Custom Components] run `gradio cc build` failed in 4.28.0

### ISSUE THREAD

**Issue by Col0ring** [gradio-app/gradio#8138]
### Describe the bug

I noticed `gradio` offers frontend customization options, well done! And I found some bugs in the new version:
1. Run `gradio cc build` failed because there is no entry file in `@gradio/preview`.
```text
ValueError: Could not find `@gradio/preview`. Run `npm i -D @gradio/preview` in your frontend folder.
```
![image](https://github.com/gradio-app/gradio/assets/47329987/da89416a-30c2-4a11-b078-0d8c609c2a50)
![image](https://github.com/gradio-app/gradio/assets/47329987/93122466-95a2-4eef-aa1c-9dbb6df84a3e)

2. Modifying `FRONTEND_DIR` will lead to compatibility problems, and get the same error.

`gradio/cli/commands/components/build.py`
![image](https://github.com/gradio-app/gradio/assets/47329987/ddd480ec-3cc4-4c0f-9a94-a3b37bde355f)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```sh
gradio cc create textbox  --template SimpleTextbox
gradio cc build
```

### System Info

```shell
gradio version: 4.28.0
gradio_client version: 0.16.0
```

### Severity

Blocking usage of gradio

**Comment by pngwn** [comment]
well shit

**Comment by duerrsimon** [comment]
@pngwn  I just installed 4.28.2. For me it still doesn't work. `@rollup/plugin-sucrase` and `@originjs/vite-plugin-commonjs` are still missing. After npm installing them it complains about the following:

```
Failed to resolve dependency: svelte/animate, present in 'optimizeDeps.include'

Failed to resolve dependency: svelte/easing, present in 'optimizeDeps.include'

Failed to resolve dependency: svelte/internal, present in 'optimizeDeps.include'

Failed to resolve dependency: svelte/internal/disclose-version, present in 'optimizeDeps.include'

Failed to resolve dependency: svelte/motion, present in 'optimizeDeps.include'

Failed to resolve dependency: svelte/store, present in 'optimizeDeps.include'

Failed to resolve dependency: svelte/transition, present in 'optimizeDeps.include'

Failed to resolve dependency: svelte, present in 'optimizeDeps.include'
```

Frontend dev server also displays an error. Backend seems to work.

**Comment by pngwn** [comment]
Yep. I'm fixing this now. Thanks for the update. 

Will be released within the hour.

**Comment by pngwn** [comment]
i lied

**Comment by pngwn** [comment]
@duerrsimon @Col0ring  R again now, should all be working!

**Comment by duerrsimon** [comment]
Seems to be working here! I also could load a common js package

**Comment by Col0ring** [comment]
@pngwn the second one of the issue list seems still exists in `gradio 4.28.3`, and I've opened a new issue #8162 to follow up on it.
