### ISSUE TITLE
This request content must be served over HTTPS

### ISSUE THREAD

**Issue by LeXwDeX** [gradio-app/gradio#8148]
### Describe the bug

I encountered a problem: I created an audio file player, but the URL generated in Gradio is in HTTP mode, causing the webpage to be unable to play the audio file properly.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

I checked the past issues and found some similar problems and partial solutions, such as adding the proxy_buffering off; configuration in Nginx, etc., but these were ineffective for the situation I encountered.

### Reproduction

Code snippet
```python
          with gr.Column():
                    audio_file_output = gr.File(label="Download Audio File")
                    audio_output = gr.Audio(label="Play")
            text_to_speech_btn.click(
                    text_to_speech,
                    inputs=[text_input],
                    outputs=[audio_file_output, response_text, audio_output]
            )
```

Nginx Conf
```conf
server {
	listen 80;
	server_name tts.domain.com;
	return 301 https://$server_name$request_uri;
}

server {
	listen 443 ssl http2;
	server_name tts.domain.com;
	ssl_certificate /data/ssl/domain.com.chained.crt;
	ssl_certificate_key /data/ssl/domain.com.key;
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
	ssl_prefer_server_ciphers on; 
	ssl_session_cache shared:SSL:10m;
	ssl_session_timeout 10m; 
	add_header X-Frame-Options "SAMEORIGIN" always;
	add_header X-Content-Type-Options "nosniff" always;
	add_header X-XSS-Protection "1; mode=block" always;
	add_header Referrer-Policy "no-referrer-when-downgrade" always;
	add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;
	add_header Permissions-Policy "interest-cohort=()";
	location / {
		proxy_pass http://localhost:7860;
		proxy_buffering off;
		proxy_redirect off;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_connect_timeout 4s; 
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Scheme $scheme;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}
```

### Logs

```shell
AudioPlayer.svelte:124 
 Mixed Content: The page at 'https://tts.domain.com/' was loaded over HTTPS, but requested an insecure resource 'http://tts.domain.com/file=/tmp/gradio/e08ded1…/2024_04_27-02_58_24_voice.wav'. This request has been blocked; the content must be served over HTTPS.
```

### System Info

Gradio Version:4.28.0

**Comment by freddyaboulton** [comment]
Hi @LeXwDeX , can you try setting the `x-forwarded-proto` header to `https`?

**Comment by LeXwDeX** [comment]
> Hi @LeXwDeX , can you try setting the `x-forwarded-proto` header to `https`?

Oh my God, After adding this header, it works.

conf snippet now:
```
location / {
                proxy_pass http://localhost:7860;
                proxy_set_header X-Forwarded-Proto $scheme;
```

**Comment by liquidcarbon** [comment]
I have something possibly related going on...
My app in  HF spaces it is complaining about insecure iframes.


index.js:1 Mixed Content: The page at 'https://huggingface.co/spaces/liquidcarbon/duckdb-fastapi-gradio' was loaded over HTTPS, but requested an insecure frame 'http://liquidcarbon-duckdb-fastapi-gradio.hf.space/sql/?alias=example1'. This request has been blocked; the content must be served over HTTPS.

It works locally, in container, and when started from
http://liquidcarbon-duckdb-fastapi-gradio.hf.space/sql/?alias=example1
but not from
https://huggingface.co/spaces/liquidcarbon/duckdb-fastapi-gradio

**Comment by freddyaboulton** [comment]
I think the issue is the iframe needs to be accessed over https here: https://huggingface.co/spaces/liquidcarbon/duckdb-fastapi-gradio/blob/89caffe982f0742877cc00729a925c1aa60a5ba7/main.py#L133

**Comment by liquidcarbon** [comment]
@freddyaboulton thanks for taking a look 
this line only populates the share editor blocks; the iframe was accessed through HTTPS
```
if hf_space_host: iframe_src = f"https://{hf_space_host}/q?query_id={query_id}"
```

The MixedContent problem was due to a RedirectResponse (commented out in the very end).  Initially the landing page (the `/` route) was redirecting to a `/sql` endpoint.  Looking through the dev tools / network panel, I could see that one of the calls during a redirect was over HTTP.  I did not save the screenshot, but it was happening during [this commit](https://huggingface.co/spaces/liquidcarbon/duckdb-fastapi-gradio/commit/8f06d793708d52bba032f6d19c0a6aa8cf13decc). 

I fixed it by mounting the gradio app to `/` and handling the absent query parameters to create a functional equivalent of a redirect.

**Comment by freddyaboulton** [comment]
Glad you found the issue! Seems like a bug with the `RedirectResponse` class then?

**Comment by liquidcarbon** [comment]
I'm not sure!  Starlette/FastAPI RedirectResponse doesn't concern itself with http/https directly.
I think something with HF spaces internals.  The app itself is served in an iframe, and something in there is not handling redirects properly.

If you do "view page source" on the app:

<html>
<body>

 
--
<iframe src="https://liquidcarbon-duckdb-fastapi-gradio.hf.space/" aria-label="Space app" class=" space-iframe flex-grow overflow-hidden bg-white p-0 outline-none dark:bg-white" allow="accelerometer; ambient-light-sensor; autoplay; battery; camera; clipboard-read; clipboard-write; display-capture; document-domain; encrypted-media; fullscreen; geolocation; gyroscope; layout-animations; legacy-image-formats; magnetometer; microphone; midi; oversized-images; payment; picture-in-picture; publickey-credentials-get; sync-xhr; usb; vr ; wake-lock; xr-spatial-tracking" sandbox="allow-downloads allow-forms allow-modals allow-pointer-lock allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-storage-access-by-user-activation" scrolling="no"></iframe>
  |  


</body>
</html>

![image](https://github.com/gradio-app/gradio/assets/47034358/9379651c-e2e6-44dc-a85d-61667df35988)
