### ISSUE TITLE
load data problem

### ISSUE THREAD

**Issue by littleping1987** [gradio-app/gradio#8161]
### Describe the bug

After upgrading to the latest version 4.28, the gradio load component is used to load the dataframe and dropdown data. After the data is successfully loaded, the table data cannot be scrolled to the right to access the dropdown data, and the dropdown box cannot be clicked to access the dropdown data

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### Screenshot

![be98c16349fb6f6390f1e12e7df95747](https://github.com/gradio-app/gradio/assets/30924042/6f8f718f-19ee-4f9c-85a8-0ce8dda4aa8c)

### System Info

```shell
the latest
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @littleping1987 can you please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by abidlabs** [comment]
Closing for lack of repro but we can reopen once we have a minimal repro.
