### ISSUE TITLE
Browsers can cache the results of the `/custom_component` route, leading to confusion when new versions are published

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#8168]
### Describe the bug

This happened to me while I was developing the leaderboard component last week. I don't have screenshots but what happened was the following:

* I had published v0.0.5 and it was on pypi and spaces
* Add a new feature
* Release v0.0.6 on pypi and install on spaces
* Space UI looks as if v0.0.5 is used even though space has 0.0.6 wheel installed. (I know because the feature I added in version 0.0.6 was not show in the UI). 
* Scratch head.
* I clear browser cache and everything looks as expected

We should set a `Cache-Control: no-cache`  header so that browsers don't use any cached requests. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

-

### System Info

```shell
gradio 4.27.0
```

### Severity

I can work around it

**Comment by pngwn** [comment]
I don't think we should set no cache but we could probably set a max age of 5 mins or so?

**Comment by pngwn** [comment]
We could also look into etags to allow more efficient revalidation.

**Comment by freddyaboulton** [comment]
Yea makes sense!
