### ISSUE TITLE
Unable to use the placeholder parameter with ChatInterface

### ISSUE THREAD

**Issue by yvrjsharma** [gradio-app/gradio#8175]
### Describe the bug

ChatInterface does not accept the `placeholder` parameter, although it is mentioned in the documentation. ChatInterface should ideally support the parameter.

`TypeError: ChatInterface.__init__() got an unexpected keyword argument 'placeholder'`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

This runs into error:

```python

import gradio as gr

def echo(message, history):
    return message

demo = gr.ChatInterface(fn=echo, 
                        examples=["hello", "hola", "merhaba"], 
                        title="Echo Bot",
                        placeholder="TESTING")
demo.launch()

```

Following code works fine:

```python

import gradio as gr

def echo(message, history):
    return message

chatbot = gr.Chatbot(placeholder="TESTING")
with gr.Blocks() as demo:
    gr.ChatInterface(fn=echo,
                     examples=["hello", "hola", "merhaba"], 
                     title="Echo Bot",
                     chatbot=chatbot
                     )
demo.launch()

```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/48665385/574bf800-189a-4b2f-b2e5-b5b02fd6bc89)

### System Info

```shell
- Testing with Gradio sdk - `4.28.3`
- Running on Google Colab
```

### Severity

I can work around it

**Comment by pngwn** [comment]
Looks like we didn't add this to ChatInterface when we added it to Chatbot. https://github.com/gradio-app/gradio/pull/7849

Should be a quick addition.

**Comment by abidlabs** [comment]
The idea is that for any customization related to the Chatbot, you should pass in a `Chatbot` object to the `chatbot` argument in `ChatInterface`

> ChatInterface does not accept the placeholder parameter, although it is mentioned in the documentation

I don't see it mentioned in the docs? https://www.gradio.app/docs/gradio/chatinterface

**Comment by yvrjsharma** [comment]
![Screenshot_20240430-194051__01](https://github.com/gradio-app/gradio/assets/48665385/6086d63e-1965-4eed-be57-e3ddd60484fe)

Thanks for quick response on this @abidlabs and @pngwn ! 
Ref to the attached image : This comes up in our docs for me, under the ChatInterface -> Initialisation subsection.

**Comment by abidlabs** [comment]
Sorry where in the screenshot does it refer to the `placeholder` argument?

**Comment by pngwn** [comment]
Yeah I don't see it there either. Only on `Chatbot`.

**Comment by yvrjsharma** [comment]
I understand the issue now, thanks for clarifying it in another related discussion @abidlabs. 
> Yuvi I think the confusion in this issue is stemming from the same persistent issue where the docs for some components / classes actually show the docs for a different class

I recall seeing a `placeholder` argument for ChatInterface when I was creating the issue, although the screenshot I provided in the ticket is of `fill_height`. Sorry about that confusion. 

Thank you for taking the time to follow up on this issue and for providing a clear explanation of the reasoning behind it.
>The idea is that for any customization related to the Chatbot, you should pass in a Chatbot object to the chatbot argument in ChatInterface

I am okay with closing the issue.
