### ISSUE TITLE
Adding Rear Camera Support for Mobile Phones

### ISSUE THREAD

**Issue by ArcaneSheep** [gradio-app/gradio#818]
Currently the source=webcam option to input images and videos defaults to the Front camera of the Mobile Phone, it would be great to have it supported for the Rear camera as well as it would be required in certain situations. Hope this gets added :)

**Comment by rremani1990** [comment]
Streamlit webrtc provides that option to select the device, would be cool if it can be added to gradio as well.

**Comment by Susensio** [comment]
@rizkidewanto how can i set the device? is it a chome setting? system?

**Comment by olmerg** [comment]
maybe it can help
[medium](https://itnext.io/building-a-camera-app-in-typescript-f1981f5ce960)
[change facing mode](https://github.com/kenreilly/typescript-photo-booth/blob/master/src/photobooth.ts#L44) in  [webcam front end](https://github.com/gradio-app/gradio/blob/main/ui/packages/image/src/Webcam.svelte#L5)

**Comment by abidlabs** [comment]
Closing in favor of #4252 as it is more general
