### ISSUE TITLE
Could not create share link

### ISSUE THREAD

**Issue by MaDHuPRi** [gradio-app/gradio#8186]
### Describe the bug

I've been trying to run my program since a week and I've noticed its the same error each time. 
My system antivirus is blocking the download of a file during the import of gradio.
<img width="548" alt="gradio error" src="https://github.com/gradio-app/gradio/assets/119328307/efd68ea7-cb41-4d48-bd77-305763f1421e">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
    
demo.launch(share=True)

### Screenshot

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()

Could not create share link. Missing file: /usr/local/lib/python3.10/dist-packages/gradio/frpc_linux_amd64_v0.2. 

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps: 

1. Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
2. Rename the downloaded file to: frpc_linux_amd64_v0.2
3. Move the file to this location: /usr/local/lib/python3.10/dist-packages/gradio
/usr/local/lib/python3.10/dist-packages/gradio/analytics.py:99: UserWarning: unable to parse version details from package URL.
  warnings.warn("unable to parse version details from package URL.")
Running on [https://localhost:7861/](https://mr8g6wbzlfo-496ff2e9c6d22116-7861-colab.googleusercontent.com/)

### System Info

```shell
yes, I'm running it on google colab
```

### Severity

Blocking usage of gradio

**Comment by caviarplays** [comment]
Same

**Comment by caviarplays** [comment]
<img width="804" alt="Screenshot 2024-05-01 at 15 40 02" src="https://github.com/gradio-app/gradio/assets/166448838/209b3b97-3d99-43ab-9fa9-5f11b73ba164">

Same here

**Comment by freddyaboulton** [comment]
Hello! We're having intermittent issues with our share link infrastructure. We're looking into it.

**Comment by roxas1212** [comment]
maybe down again now.

**Comment by tonylcb** [comment]
yes, down again

**Comment by mostafahazim** [comment]
Facing the same issue share link not working

**Comment by plutoniumm** [comment]
Yeah there working on it, you can keep an eye here [Status](https://status.gradio.app/793595965#logs)

**Comment by theWitchR** [comment]
Is there any work around in the meanwhile?

**Comment by freddyaboulton** [comment]
Yes, you can host your own share link server! https://github.com/huggingface/frp You can also the demo on a webserver of your own.

**Comment by abidlabs** [comment]
Going to close this as there have been many similar issues around the share link problems. If you are still facing issues related to share links, please use this issue to report: https://github.com/gradio-app/gradio/issues/3677

**Comment by kairin** [comment]
https://github.com/cocktailpeanut/fluxgym/issues/277#issue-2754463682

i am trying to run an app on google colab, but both testing locally and running on colab seems to create this issue as well.

Does that mean... something is down in gradio?

**Comment by abidlabs** [comment]
Can you try installing `gradio` like this:

```py
pip install https://gradio-pypi-previews.s3.amazonaws.com/4814351d6866e31cdff70ebd87823e6fa10dcf2b/gradio-5.23.3-py3-none-any.whl
```

and see if it resolves the issue for you?
