### ISSUE TITLE
Reload mode no longer able to update Interface title/description

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#8191]
### Describe the bug

If you update an Interface's title or description in reload mode, it won't be reflected in the UI. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
#from foo import BAR
#
def calculator(num1, operation, num2):
    if operation == "add":
        return num1 + num2
    elif operation == "subtract":
        return num1 - num2
    elif operation == "multiply":
        return num1 * num2
    elif operation == "divide":
        if num2 == 0:
            raise gr.Error("Cannot divide by zero!")
        return num1 / num2

demo = gr.Interface(
    calculator,
    [
        gr.Number(label="Number 1"), 
        gr.Radio(["add", "subtract", "multiply", "divide"]),
        "number"
    ],
    "number",
    examples=[
        [45, "add", 3],
        [3.14, "divide", 2],
        [144, "multiply", 2.5],
        [0, "subtract", 1.2],
    ],
    title="Toy Calculator!! 🧮",
    description="Heres a sample toy calculator. Allows you to calculate things like $2+2=4$",
)

if __name__ == "__main__":
    demo.launch()

```

### Screenshot

At the end I manually refresh to show the latest changes

![title_description_cant_update](https://github.com/gradio-app/gradio/assets/41651716/282ca261-ecb5-486d-9c3e-8ce4d080a811)

### System Info

```shell
main
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Is it a larger issue related to `gr.Markdown()`?

**Comment by freddyaboulton** [comment]
I think it's related to the recent changes around not updating components whose ids don't change but have not looked into the cause closely
