### ISSUE TITLE
Variable Name

### ISSUE THREAD

**Issue by Adilmar** [gradio-app/gradio#8195]
### Describe the bug

Variable name 

Guys in the client/dist/index.js file on line 1274 the correct one would be semiver$1.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

 if (semiver$1(config.version || "2.0.0", "3.6") < 0) {
            addEventListener(
              "open",
              () => websocket.send(JSON.stringify({ hash: session_hash }))
            );
          }

### Screenshot

![Captura de tela de 2024-05-02 08-42-43](https://github.com/gradio-app/gradio/assets/6667216/14622724-720a-4347-94a6-f1c00c63b6f2)

### Logs

```shell
ReferenceError: semiver is not defined
at /var/task/.next/server/app/api/conversation/route.js:1:18104
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.
Unknown application error occurred
```

### System Info

```shell
lasted
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @Adilmar its not clear from this issue what the bug you are describing is. Can you please provide a minimal code example that we can use to reproduce the error you are seeing? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by abidlabs** [comment]
Going to close for lack of follow up. We can reopen if we have a complete repro
