### ISSUE TITLE
The module gr.Sketchpad，ImageMask cannot obtain the binary image normally.

### ISSUE THREAD

**Issue by JunchuanYu** [gradio-app/gradio#8198]
### Describe the bug

I want to obtain a binarized mask file through handwriting (with background as 0 and foreground as 1). However, when using gr.Sketchpador gr.ImageMask , if the image mode is set to "L", the output is an array of all zeros.
when i change the color of the pencil to white, the output is correct, but i can't see what is draw. 
 I found that this is because the program defaults to a background of all zeros and the pen default value is also zero, so the handwritten content cannot be seen. This is different from the old version of sketchpad.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import numpy as np

def sleep(im):
    a=im["composite"]
    b=a.shape
    c=np.max(a)
    return a, f'the image size is {b},\n the max value is {c}'

with gr.Blocks() as demo:
    with gr.Group():
        with gr.Row():
            out=gr.Textbox() 
        with gr.Row():
            im = gr.Sketchpad(type="numpy",image_mode="L")
            im_out_1 = gr.Image(type="pil")
    im.change(sleep, outputs=[im_out_1, out], inputs=im)
    demo.launch()
```

### Screenshot

![111](https://github.com/gradio-app/gradio/assets/79159086/53051107-fe38-46db-a350-2d14fceac652)

### System Info

```shell
gradio==4.24.0
windows
```

### Severity

I can work around it

**Comment by Rickyyy-zh** [comment]
same question, also in 4.24.0 and 4.27.0

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio
