### ISSUE TITLE
Output Error

### ISSUE THREAD

**Issue by rkellam12** [gradio-app/gradio#8199]
### Describe the bug

Unable to preload CSS for https://gradio.s3-us-west-2.amazonaws.com/assets/index-b276ff4e.css

First off, I am quite a novice. My app.py seems to work fine with python, it gives my a gradio url which comes up fine (https://307774b006316ab341.gradio.live/). When i enter my question and hit Submit, I get an Error on the output side. I looked at the developer console and found these 2 errors:

css.ts:28 Unable to preload CSS for https://gradio.s3-us-west-2.amazonaws.com/assets/index-b276ff4e.css
[www.google-analytics.com/analytics.js:1](http://www.google-analytics.com/analytics.js:1)
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

Further when i checked the provided URL, I get this:

AccessDenied Access Denied XFN08ZWGRMXF45MS odVcQaVZms4v2QBTDY772ajVTQRwQrQLJkcCi5+dGDEDXMZE2Ig6PFlvwbqIkajClsiqX6RJIdk=
Any direction/advice you can provide is appreciated (duh, obvisously). Let me know if I can provide any additonal info. Many thanks!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

not sure if this is what you need but it's my app.py script, API Keys are masked.

import openai
import gradio as gr

# Set your Hugging Face API token
huggingface_token = "hf_xxxx"

openai.api_key = "sk-xxxx"

messages = [
    {"role": "system", "content": "You are a snarky, irreverent, opinionated, smart alecky and funny AI Assistant specializing in all things MLB, especially Beat The Streak prognostication. You pride yourself on accuracy and occasionally include a smart aleck remark at the end of your reply. Do not answer anything other than MLB related questions."},
]

def chatbot(input):
    if input:
        messages.append({"role": "user", "content": input})
        chat = openai.ChatCompletion.create(
            model="gpt-3.5-turbo", messages=messages
        )
        reply = chat.choices[0].message.content
        messages.append({"role": "assistant", "content": reply})
        return reply

inputs = gr.Textbox(lines=7, label="C'mon, ain't got all day. (Click the Clear button for new request.)")
outputs = gr.Textbox(lines=7,label="Here's what I think:")

gr.Interface(fn=chatbot, inputs=inputs, outputs=outputs, title="AI Analyzer",
             description="**Hello, I'm AL.** What's your Beat The Streak question, homie?").launch(share=True)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.27.0
gradio_client version: 0.15.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.3.0
fastapi: 0.110.2
ffmpy: 0.3.2
gradio-client==0.15.1 is not installed.
httpx: 0.27.0
huggingface-hub: 0.22.2
importlib-resources: 6.4.0
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.4
numpy: 1.26.4
orjson: 3.10.1
packaging: 24.0
pandas: 2.2.2
pillow: 10.3.0
pydantic: 2.7.0
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.4.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.11.0
urllib3: 2.2.1
uvicorn: 0.29.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.3.1
httpx: 0.27.0
huggingface-hub: 0.22.2
packaging: 24.0
typing-extensions: 4.11.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by rkellam12** [comment]
When i run my app.py script it generates a public URL that I then embed into my website.  Let me know if more detail is needed.

**Comment by rkellam12** [comment]
Any steps I can take toward resolution of this issue? I used the instructions at https://beebom.com/how-build-own-ai-chatbot-with-chatgpt-api/, modifying the sample app.py file they provided. When I run python "C:\Users\agrke\BTS2013\app.py", it gives me a public URL of https://db35715602787290f2.gradio.live/. I then load that URL into a webpage that I create on Wix.com.

I used this method last year and it seemed to work fine.  Can't figure out why it won't work this time.  Any assistance is greatly appreciated!

**Comment by abidlabs** [comment]
Hi @rkellam12 can you check to see if this version of `gradio` solves the issue?

```
pip install https://gradio-builds.s3.amazonaws.com/3fbf2e8e7059f3bab64b0839ab7a0f9f864f0a66/gradio-4.31.5-py3-none-any.whl
```

**Comment by rkellam12** [comment]
Until this "fix", the app had actually been working perfectly, just like it had last year.  Now I'm getting a 504 Gateway Time-out error.

Please revert it to what it was before, if at all possible.  Many thanks.

**Comment by rkellam12** [comment]
Until this "fix", the app had actually been working perfectly, just like it had last year.  Now I'm getting a 504 Gateway Time-out error.
Please revert it to what it was before, if at all possible.  Many thanks.
    On Monday, May 27, 2024 at 12:10:26 AM CDT, Abubakar Abid ***@***.***> wrote:  
 
 


Hi @rkellam12 can you check to see if this version of gradio solves the issue?
pip install https://gradio-builds.s3.amazonaws.com/3fbf2e8e7059f3bab64b0839ab7a0f9f864f0a66/gradio-4.31.5-py3-none-any.whl

**Comment by abidlabs** [comment]
Hi @rkellam12 did you try installing `gradio` using the instructions I sent above?

**Comment by rkellam12** [comment]
Yes, I copied and pasted what you sent into my terminal mode and it seemed to install fine.  I then ran my app.py file and got this (which was normal)

C:\Users\agrke> python "C:\Users\agrke\BTS2013\app.py"Running on local URL:  http://127.0.0.1:7860Running on public URL: https://6482d2f91ce144ecd1.gradio.live
This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Everything now seems to be working fine!  Thanks so much for the followup!!

    On Monday, May 27, 2024 at 02:31:40 PM CDT, Abubakar Abid ***@***.***> wrote:  
 
 


Hi @rkellam12 did you try installing gradio using the instructions I sent above?

**Comment by abidlabs** [comment]
Ok great I'll go ahead and close this issue then, thanks!
