### ISSUE TITLE
Allow Gradio apps to take up more (full screen?) width

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#8201]
A common request is to increase the width of Gradio apps so that there's more space for the components and less white space around the edges of the app. While this can be done with custom css, it'd be good to have a built-in parameter in Gradio for this:

Quoting @yvrjsharma:

> This is particularly relevant for arena-type demos, where multiple (>= two) chatbots are present in the UI, allowing for easy comparisons. These types of demos have become quite popular recently, with the success of lmsys-arena, and I think we might see an increase in their numbers in the near future. For example: https://huggingface.co/spaces/WildVision/vision-arena

**Comment by one-lithe-rune** [comment]
In case it's useful to anyone trying to do this, the code I'm currently using make things full width for Blocks is similar to this:

```Python
import gradio as gr

# Change the @media query to whatever min-width you need

head_style = """
<style>
@media (min-width: 1536px)
{
    .gradio-container {
        min-width: var(--size-full) !important;
    }
}
</style>
"""

# It has to go in head=

with gr.Blocks(
    title="A chat interface",
    head=head_style,
) as chat_interface:

# ...etc.

```

Note that it has to go in head, as putting it in CSS didn't work on the version of gradio I was working with at the time I was trying to do this, at least with the `@media` query.
