### ISSUE TITLE
Allow users to change arbitrary component inputs

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#821]
We chatted briefly about this offline, but how should we handle multiple inputs (and possibly outputs for a component). The work in #807 partially addresses this issue but this slide/dropdown example would not be possible currently as we do not have a way to have multiple inputs/ouputs and inconsistent inputs/outputs:

```py
from gradio.blocks import *

def dropdown_values(val):
    if val < 50:
       return ["fail", "repeat"]
    else:
       return ["succeed", "repeat"]
  
def fn(val, action):
     return "Your score is {} and you decided to {}".format(val, action)


with Blocks() as block:

  s = Slider(0, 100)
  d = Dropdown([]) 
  t = Textbox()

  s.select(fn=dropdown_values, outputs=d)
  d.select(fn=fn, inputs=[s, d], outputs=t)

  block.launch()
```

@aliabid94 Mentioned recreating a new config but I'm concerned about that approach for a number of reasons.

If we could gather our thoughts here and figure out how we should proceed.

**Comment by aliabid94** [comment]
I was thinking something the lines of this:
```python
from gradio.blocks import *

def dropdown_values(val):
    if val < 50:
       opts = ["fail", "repeat"]
    else:
       opts = ["succeed", "repeat"]
    return Dropdown.update(choices=opts)
  
def fn(val, action):
     return "Your score is {} and you decided to {}".format(val, action)


with Blocks() as block:

  s = Slider(0, 100)
  d = Dropdown(chocies=[]) 
  t = Textbox()

  s.change(fn=dropdown_values, outputs=d)
  drop.select(fn=fn, inputs=[s, d], outputs=t)

  block.launch()
```

So if you return normal values from a function, that becomes the new value represented by the Block. But if you return a Block.update(), the config of the Block gets updated instead. Block.update takes the same args as the constructor for the Block itself. 

It's possible to update both the config and the value of a component, e.g.

```python
from gradio.blocks import *

def dropdown_values(val):
    if val < 50:
       opts = ["fail", "repeat"]
    else:
       opts = ["succeed", "repeat"]
    return "repeat", Dropdown.update(choices=opts)
  
with Blocks() as block:

  s = Slider(0, 100)
  d = Dropdown(chocies=[]) 

  s.change(fn=dropdown_values, outputs=[d, d])

  block.launch()
```

**Comment by aliabid94** [comment]
Block.update being a class level method implemented for every Block/

**Comment by pngwn** [comment]
I'm not sure about this API. It doesnm't really make sense to me why we'd distinguish between the two types of value. Maybe if you return a single value then it is assigned to the primary input (which we can document) but you can alternatively return an update method and pass in the named args if you want to update secondary values:

```py
def fn(val):
  return something
``` 
or

```py
def fn(val): 
  if val < 50:
    opts = ["fail", "repeat"]
  else:
    opts = ["succeed", "repeat"]
  return Dropdown.update(value="fail", choices=opts)
```

Passing both back feels strange to me.

**Comment by abidlabs** [comment]
Yup agree with @pngwn. "value" (now called "default_value") is part of the constructor arguments so we don't need to return it separately. 

Also, what kind of object is `Dropdown.update`? It's basically just a wrapper over a dictionary, right? Whatever object it is, we should make sure it prints the dictionary values nicely so that users can test the `dropdown_values` function that they right.

**Comment by pngwn** [comment]
@abidlabs Yeah, `X.update` would just be a factory function/ method. I think might need a `type` key in the returned payload of the api request, so we can work out if the dict was generated via an `update` call or was explicitly defined. Because we need to know whether we should pass the dict as the `value` or pass each key from the dict as inividual props to the component (allowing us to update any of the individual component values).

So maybe update would look something like this (pseudo-ish, it won't actually be a function):

```py
def update(**kwargs):
  kwargs['__type__'] = 'update'
  return kwargs
```

dundered it to reduct chance of collisions.

**Comment by abidlabs** [comment]
@aliabid94 do you have thoughts on this API vs. the previous one?

Implementing the backend with this API should be very super straightforward. We just add this function to the `Component` parent class. @pngwn why do you say that "it won't actually be a function"? Why wouldn't it be a function?

In the frontend, you'd need to look at the returned value and if it is a dictionary with a key called `__type__`, then the update the relevant scenario.

The only thing that seems weird to me is why we need to include the name of the component we are updating. With this API, returning `Dropdown.update(value="fail", choices=opts)` has the same effect as returning, e.g., `Image.update(value="fail", choices=opts)`. Which means that we could go with a simpler API

**Comment by pngwn** [comment]
>  @pngwn why do you say that "it won't actually be a function"?

Because it will be a class method.

That said it could just be a function really, it isn't doing anything special.

**Comment by abidlabs** [comment]
Cool, then we are on the same page

**Comment by FarukOzderim** [comment]
I am not sure I am following the discussion throughly. Would it not be enough for us to update a component's fields with the `update` function?

```
def update(**kwargs):
  for key, value in kwargs.items():
    setattr(self, key, value)

```

**Comment by abidlabs** [comment]
The purpose of the `update()` method isn't to actually change the properties (since the updating needs to happens on the front end, *without* the page being refreshed). Instead, `update()` simply returns a response in a format (a json dictionary) that the frontend can use to know how to update the components.

**Comment by aliabid94** [comment]
Sounds good, will implement as @pngwn suggested. Thoughts on renaming `default_value` to just `value`? Seems strange to says `gr.Textbox.update(default_value="asdf")` to assign a new value. Also default_value is a long kwarg name.

**Comment by aliabid94** [comment]
The way update has been implemented in the backend, it assumes that the name for the class constructor argument is the same as the name passed to configuration json, and the value passed to the class constructor is the same value passed to the json configuration (no processing done). This may be fragile.

**Comment by aliabid94** [comment]
Also, if the update method in the backend is doing no checks to see if the arguments passed are valid, why not just use a generic `update(choices=opts)` instead of `Dropdown.update(choices=opts)`?

**Comment by abidlabs** [comment]
> Thoughts on renaming default_value to just value

Strong agree. Makes much more sense given how we are using it

**Comment by FarukOzderim** [comment]
>Thoughts on renaming default_value to just value
I don't really agree with this, because we are not updating the value inside the component, but we are updating the component itself. We could have `lines` `max_lines` inside the update function as well.

`default_value` is the initial value it has, and `value` does not represent this IMO.

**Comment by abidlabs** [comment]
I see what you're saying @FarukOzderim, but I think `value` is a more appropriate name, given that this parameter is actually used in a few different ways:
* for static components, it is used to denote the value that is displayed
* for output components, it is used to denote the value that is displayed before the function runs
* for input components, it is used to denote the value that is displayed before the user edits it

Even for input components, `value` is okay as a name (e.g. the HTML textbox [has the value property](https://www.geeksforgeeks.org/html-dom-input-text-value-property/#:~:text=The%20Input%20Text%20value%20property,value%20or%20the%20user%20types.) which is exactly the same as our Textbox's value parameter), but given all of these use cases, `value` definitely captures the meaning better

**Comment by FarukOzderim** [comment]
This issue's Backend part is done, could you complete the Frontend part as well @aliabid94?

**Comment by abidlabs** [comment]
Yes, just chatted with @aliabid94 -- he is working on this right now!

**Comment by abidlabs** [comment]
Done via #1089!
