### ISSUE TITLE
How to add audio output to Chatbot

### ISSUE THREAD

**Issue by fancyerii** [gradio-app/gradio#8210]
I have read [How to Create a Custom Chatbot with Gradio Blocks](https://www.gradio.app/guides/creating-a-custom-chatbot-with-blocks). But I want to add audio output to gr.Chatbot so that I can use tts model to read the text. How can I achieve this goal?

**Comment by abidlabs** [comment]
Hi @fancyerii, for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
