### ISSUE TITLE
Where is the gr.Image.edit() listener and the 'tool' args ?  

### ISSUE THREAD

**Issue by Yukun66** [gradio-app/gradio#8214]
Where is the gr.Image.edit() listener and the 'tool' args ?

**Comment by abidlabs** [comment]
Hi @Yukun66 in 4.x, the `tool` parameter of `Image` has been deprecated and instead you should use the `ImageEditor` component. Please see the docs for more details: https://www.gradio.app/docs/gradio/imageeditor
