### ISSUE TITLE
Client-side Image loads very slowly when Automatic1111 is deployed on Azure Kubernetes instance 

### ISSUE THREAD

**Issue by marcsyp** [gradio-app/gradio#8216]
### Describe the bug

I am deploying a containerized Automatic1111 on Azure using kubernetes, and most things work beautifully -- one big problem thouh, is that after a batch is finished, the loading of the image (512x512, 640x960) is very very slow.  There is a 4-10s delay after the end of the batch, and then the image loads in the UI as if it's on dialup with a 9600 baud modem.

The host machines are extremely capable with A100 GPUs and this is an issue regardless of whether the client is half way around the world from the hosting server or right next door.  

Any ideas on what might be happening, or what I should investigate? 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
N/A
```

### System Info

```shell
Gradio version 3.41.2
```

### Severity

I can work around it

**Comment by pngwn** [comment]
We will need some way to reproduce this, could you please provide a simple reproduction for this case?

**Comment by abidlabs** [comment]
Going to close this for now, can reopen with a repro
