### ISSUE TITLE
[Blocks] Recreate the original interface using Blocks

### ISSUE THREAD

**Issue by MohamedAliRashad** [gradio-app/gradio#823]
I want to make a multi-interface website but with the nice interface that comes as default with gradio.

Is there a tutorial on how to do the default interface with `Blocks()` ?

**Comment by abidlabs** [comment]
Great question @MohamedAliRashad! We are working towards this goal -- we should have something in the next few weeks!

**Comment by MohamedAliRashad** [comment]
@abidlabs I don't normally think of coincidences but it's interesting when i apply yesterday for Fatima's Fellowship and today have a response from one of it's organizers and phd students.

I am from Egypt and i was using Gradio for a simple demo project in our company.
Your work helped me a lot, Thanks :heart:

**Comment by abidlabs** [comment]
This is now possible. This work has been pushed to the `Blocks-Dev` branch.
