### ISSUE TITLE
CURL/requests documentation to swagger docs 

### ISSUE THREAD

**Issue by ryanshrott** [gradio-app/gradio#8237]
How do I call the API with CURL in postman or requests module? Can someone please provide an example with documentation?

If this isn't possible, why not?

I used to be able to do it a year ago.

from gradio_client import Client

client = Client("Property-ca/photos")
result = client.predict(
		mls_number="w5633330",
		photo_base_url="/public/images/listings/optimized/w5633330/mls/",
		number_of_images=5,
		version=2,
		api_name="/lambda"
)
print(result)

**Comment by pngwn** [comment]
We will be adding documentation around this shortly. Thank you for creating an issue.

It is still possibly but it is a little more complex now. We won't be adding the documentation to the swagger docs but we will be adding it to the "Use via API" page.

**Comment by ryanshrott** [comment]
@pngwn thank you. Adding to the "Use via API" docs is perfect. Do you know the timeline on that? Will it be in the next release?

**Comment by ryanshrott** [comment]
I was hoping it would be added to "View via API" button, just like we used to have these Python requests module, which is basically like curl requests.

**Comment by pngwn** [comment]
Yes, it will.

**Comment by pablovela5620** [comment]
> We will be adding documentation around this shortly. Thank you for creating an issue.
> 
> It is still possibly but it is a little more complex now. We won't be adding the documentation to the swagger docs but we will be adding it to the "Use via API" page.

any timeline as to when CURL documentation will be added? I have something working thanks to this blogpost https://www.freddyboulton.com/blog/gradio-curl from @freddyaboulton . But there's still some things missing that I would like to do (for example authentication either from a private space or a password protected gradio app). I'm trying to call the API from a swift app so the python/js wont work for my usecase

**Comment by ryanshrott** [comment]
I'm hoping soon as well! I miss curl requests :)
