### ISSUE TITLE
Colab Enterprise and Gradio Error: "There is no current event loop in thread"

### ISSUE THREAD

**Issue by vanessa-bonifaz** [gradio-app/gradio#8238]
### Describe the bug

When running this code on a GCP Colab Enterprise Python Notebook, I'm getting error "RuntimeError: There is no current event loop in thread 'Thread-606 (run)'."

![dasfdgsf](https://github.com/gradio-app/gradio/assets/71043719/8d8c23f0-decd-407b-bcc3-0e600939e253)

```
#! pip install --upgrade gradio

import time
import gradio as gr

def slow_echo(message, history):
    for i in range(len(message)):
        time.sleep(0.3)
        yield "You typed: " + message[: i+1]

gr.ChatInterface(slow_echo).launch()
```

The code works alright in Google Colab notebook: 
![fghjk](https://github.com/gradio-app/gradio/assets/71043719/b9c94532-2db2-4153-8cb2-39ff8f12e56c)

How can I solve this issue? 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
#! pip install --upgrade gradio

import time
import gradio as gr

def slow_echo(message, history):
    for i in range(len(message)):
        time.sleep(0.3)
        yield "You typed: " + message[: i+1]

gr.ChatInterface(slow_echo).launch()
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.29.0
gradio_client version: 0.16.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 4.2.2
fastapi: 0.111.0
ffmpy: 0.3.2
gradio-client==0.16.1 is not installed.
httpx: 0.27.0
huggingface-hub: 0.20.3
importlib-resources: 6.4.0
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.7.1
numpy: 1.25.2
orjson: 3.10.3
packaging: 24.0
pandas: 2.0.3
pillow: 9.4.0
pydantic: 2.7.1
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.4.3
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.11.0
urllib3: 2.0.7
uvicorn: 0.29.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.27.0
huggingface-hub: 0.20.3
packaging: 24.0
typing-extensions: 4.11.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @vanessa-bonifaz ! It seems to be an issue with the Colab Enterprise, not Gradio, since Gradio works fine in normal Colab. I would contact their support team.

**Comment by gogasca** [comment]
Facing the same issue in Colab Enterprise, works fine in free Colab.

```
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
demo.launch(share=True, debug=True)
```

```
Exception in thread Thread-17 (run):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 26, in run
    loop = asyncio.get_event_loop()
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 40, in _get_event_loop
    loop = events.get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-17 (run)'.
/usr/lib/python3.10/threading.py:1018: RuntimeWarning: coroutine 'Server.serve' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Exception in thread Thread-18 (run):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 26, in run
    loop = asyncio.get_event_loop()
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 40, in _get_event_loop
    loop = events.get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-18 (run)'.
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
[<ipython-input-4-624fbbb2da79>](https://localhost:8080/#) in <cell line: 7>()
      5 
      6 demo = gr.Interface(fn=greet, inputs="text", outputs="text")
----> 7 demo.launch(share=True, debug=True)

2 frames
[/usr/local/lib/python3.10/dist-packages/gradio/http_server.py](https://localhost:8080/#) in run_in_thread(self)
     55         start = time.time()
     56         while not self.started:
---> 57             time.sleep(1e-3)
     58             if time.time() - start > 5:
     59                 raise ServerFailedToStartError(
```

In my case an issue related to tunneling.

**Comment by gogasca** [comment]
When I try to run the same code in Colab Enterprise Terminal, it works fine. Just when running it inside Notebook.

```
/content# python
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gradio as gr
>>> 
>>> def greet(name):
...     return "Hello " + name + "!"
... 
>>> demo = gr.Interface(fn=greet, inputs="text", outputs="text")
>>> demo.launch(share=True)
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://e36ae94a0ed51f0f3d.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
```

This is the diff: https://www.diffchecker.com/J75IJCDz/

I tried Did a `pip freeze > requirements.txt` in Free Colab and then a `pip install -r requirements.txt` in Colab Enterprise and same error.

Seems related to https://stackoverflow.com/questions/46727787/runtimeerror-there-is-no-current-event-loop-in-thread-in-async-apscheduler but looking for any insights.

**Comment by gogasca** [comment]
Changed these lines in: `/usr/local/lib/python3.10/dist-packages/nest_asyncio.py` and now works.

![image](https://github.com/gradio-app/gradio/assets/30065079/568ad5b1-3425-41d0-8cf4-4844e6cc0c54)


def _patch_asyncio():
    """Patch asyncio module to use pure Python tasks and futures."""

    def run(main, *, debug=False):
        # loop = asyncio.get_event_loop()
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)

https://stackoverflow.com/a/46750562/260826

Not sure what may be the root cause.

**Comment by freddyaboulton** [comment]
Thanks for the thorough deep dive @gogasca ! I don't think this is a gradio issue since `nest-asyncio` is not a dependency of gradio, it's a dependency of jupyter notebook.

I am not sure what is different between enterprise and free colab based on the pip diff. 

I will contact someone at google colab to let them know of the problem and I suggest you do the same so they can look into it.

I will close in the meantime! Thank you again.

**Comment by gogasca** [comment]
Seems related:
https://github.com/gradio-app/gradio/issues/5941
If i do `pip unsintall uvloop` I can run sample code.

**Comment by freddyaboulton** [comment]
The minimal repro seems to be running uvicorn in a separate thread with uvloop installed

https://colab.research.google.com/drive/1fHjPNzOJwM9KtPbhHJsNUgJEwpy5rWQP?usp=sharing


<img width="791" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/5d5fd7f0-bc1c-495a-92ee-f29e67923c45">

**Comment by gogasca** [comment]
Now the previous example works fine in free Colab. Still fails in Colab Enterprise.

**Comment by gogasca** [comment]
@freddyaboulton opened a discussion here https://github.com/encode/uvicorn/discussions/2342
 
PS: I'm part of Colab Enterprise team

**Comment by freddyaboulton** [comment]
Thank you @gogasca ! Subscribed to the discussion

**Comment by gogasca** [comment]
Just to close on this thread, this will be fixed in the next Colab Enterprise image (expected to rollout next week)

**Comment by lambdaxai** [comment]
The cause of this problem may be that you're using nest-asyncio to patch python's asyncio lib, because gradio defaults to using loop='auto' in the class uvicorn.config.Config, with loop='auto', uvicorn replaces asyncio's event_loop_policy, causing get_event_loop to report an error.

Solution: Add the following code before app.lunch() to replace the original policy:
```
import uvicorn

uvicorn.config.LOOP_SETUPS = {
    "none": None,
    "auto": "uvicorn.loops.asyncio:asyncio_setup",
    "asyncio": "uvicorn.loops.asyncio:asyncio_setup",
    "uvloop": "uvicorn.loops.uvloop:uvloop_setup",
}
```
