### ISSUE TITLE
Vertical spacing issue of `gr.DuplicateButton`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#8239]
### Describe the bug

Not sure why, but when changing the aspect ratio of the browser, unnecessary vertical margin appears around `gr.DuplicateButon` in [this Space](https://huggingface.co/spaces/ysharma/Chat_with_Meta_llama3_8b).

https://github.com/gradio-app/gradio/assets/25161192/d05215e4-615c-4ccd-b2d3-df3a3c5112e0

([internal Slack](https://huggingface.slack.com/archives/C03JMRM52C9/p1713482965086409?thread_ts=1713459247.955419&cid=C03JMRM52C9))

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://huggingface.co/spaces/ysharma/Chat_with_Meta_llama3_8b

### System Info

```shell
gradio==4.26.0
```

### Severity

I can work around it

**Comment by pngwn** [comment]
Does this happen on the direct URL (rather than the hf spaces iframed version)?

**Comment by hysts** [comment]
Ah, interesting. It doesn't happen on the direct URL. https://ysharma-chat-with-meta-llama3-8b.hf.space/
So, it's more like the issue of Space embedding?

**Comment by pngwn** [comment]
Yeah. So it's an iframe resizer related issue that we have seen repeatedly.

**Comment by hysts** [comment]
I see. I'll close this issue, then. Thanks!
