### ISSUE TITLE
Allow users to change the chatbot area

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#8240]
- [x] I have searched to see if a similar issue already exists.

Sometimes, app authors specify the height of the `gr.Chatbot` component, but the height may be too small and it might be hard to take good screenshots, so I think it would be useful if users can drag and expand the chat area even when the height is specified.

For example, in [this Space](https://huggingface.co/spaces/HuggingFaceM4/idefics2_playground), the height is set to `450` [here](https://huggingface.co/spaces/HuggingFaceM4/idefics2_playground/blob/46de412870671e33d5c10791f3ed70d33d39a35c/app_dialogue.py#L416-L420), but it's definitely not enough for screenshots.

![](https://github.com/gradio-app/gradio/assets/25161192/e493bbcf-01eb-4a40-8a01-6c5cd7bd9ed0)

**Comment by abidlabs** [comment]
Maybe we could have the chatbot be able to pop out and take up the full screen as people have requested with Image and Gallery. It would also make the chatbot easier to use on mobile


cc @dawoodkhan82 @hannahblair

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/10149, thanks @aliabid94!
