### ISSUE TITLE
API recorder broken on several demos

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#8259]
### Describe the bug

The API recorder seems to work in simple cases but there are quite a few demos where it doesn't work.

Most notably it doesn't work with the `ChatInterface`.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

 https://huggingface.co/spaces/gradio/chatinterface_streaming_echo

https://huggingface.co/spaces/gradio/kitchen_sink

Do almost anything and record the requests, and it will break.

What isn't clear to me is how we are supposed to handle the API recorder if certain API requests are essentially 'hidden' from the client. What is more, we don't return info for unnamed routes from `/info`, so I'm not sure how we are supposed to get hold of this information. We somehow need to workaround these constraints for the API recorder to work.

### System Info

```shell
-
```

### Severity

I can work around it

**Comment by pngwn** [comment]
In terms of what is happening. I'm pretty sure the API recorder works fine but we don't have the information required to build the queries correctly due to the various client changes + how the information to make those changes only applies to certain routes.

**Comment by freddyaboulton** [comment]
Also see #8246 for another case
