### ISSUE TITLE
Add option to use default <audio> tag

### ISSUE THREAD

**Issue by fakerybakery** [gradio-app/gradio#8267]
Hi, in old versions of Gradio there was no custom audio component and it used the built-in HTML audio element. The new component is amazing most of the time but for certain use cases it would be nice to have the built-in audio element back. Is there any way to do that, besides downgrading? Thanks!

**Comment by pngwn** [comment]
What about the current audio element doesn't work for you? Is it the size?

**Comment by fakerybakery** [comment]
That, and I want the user to be able to skip to any part of the audio file without horizontal scrolling

**Comment by pngwn** [comment]
I see. Maybe we could create a minimal variant that better matches the old UX (but looks nicer). 

Cc @hannahblair

**Comment by abidlabs** [comment]
This should solve this, right? https://github.com/gradio-app/gradio/issues/6801

**Comment by fakerybakery** [comment]
I was more looking for a way to allow the user to skip anywhere in a longer audio file without having to horizontally scroll

**Comment by abidlabs** [comment]
Should be solved when https://github.com/gradio-app/gradio/issues/6801 is addressed
