### ISSUE TITLE
Have the possibility to output audio in gr.Dataframe

### ISSUE THREAD

**Issue by ylacombe** [gradio-app/gradio#8270]
- [x] I have searched to see if a similar issue already exists.

I currently want to create a demo where I associate some values to a wide range of audios, and it would be great if I could use gr.Dataframe with a column of audio samples, do you think it would be possible to have this ?

Many thanks!

**Comment by freddyaboulton** [comment]
Also related: https://github.com/gradio-app/gradio/issues/2678

**Comment by freddyaboulton** [comment]
And #8257 could be the patterned used to enable this I think

**Comment by abidlabs** [comment]
This is already possible actually, by setting the `datatype="markdown"` in `gr.DataFrame`!

Here's a representative example:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.DataFrame([["<audio src='/file=cantina.wav' controls></audio>"]], datatype="markdown")
    
demo.launch(allowed_paths=["cantina.wav"])
```

So I think we can close, but lmk if I'm missing anything!

**Comment by jerpint** [comment]
Is this still the supported syntax?

I'm getting a greyed out audio with the following, adding screenshot:

```python
file = "common_voice_en_100166.mp3"
assert os.path.exists(file)

with gr.Blocks() as demo:
    gr.DataFrame([["<audio src='/file={file}' controls></audio>"]], datatype="markdown")

demo.launch(allowed_paths=[file])
```

```pip freeze | grep gradio
gradio==5.4.0
gradio_client==1.4.2
```


![image](https://github.com/user-attachments/assets/f2b831a8-b89d-4712-b8b9-00a78761ae59)

**Comment by Yb2S3** [comment]
Hello @abidlabs ,
Is there anything possible way to embedded gr.Audio in one column of gr.Dataframe? If possible, how can I do that?
I have tried it with:
```python
df['Audio'] = df['Audio'].apply(
        lambda x: gr.Audio(value=audio_base_path + x))
gr.Dataframe(value=df, type="pandas", datatype='markdown', interactive=True, render=True)
```

**Comment by abidlabs** [comment]
Embed components is not supported right now but its something we're considering. In the meantime, you can try something like this to embed via markdown:

```py
file = "common_voice_en_100166.mp3"
assert os.path.exists(file)

with gr.Blocks() as demo:
    gr.DataFrame([[f"<audio src='/gradio_api/file={file}' controls></audio>"]], datatype="markdown")

demo.launch(allowed_paths=[file])
```

**Comment by Yb2S3** [comment]
Thank you @abidlabs for your quick reply.
Is there any restriction of the file? For example, the file should be in the path of the my app, or it can be somewhere else in my disk? Because as you know, the audio file will is encoded as html should be in the app's published folder.

> Embed components is not supported right now but its something we're considering. In the meantime, you can try something like this to embed via markdown:
> 
> file = "common_voice_en_100166.mp3"
> assert os.path.exists(file)
> 
> with gr.Blocks() as demo:
>     gr.DataFrame([[f"<audio src='/gradio_api/file={file}' controls></audio>"]], datatype="markdown")
> 
> demo.launch(allowed_paths=[file])

**Comment by abidlabs** [comment]
See https://www.gradio.app/guides/file-access

**Comment by freddyaboulton** [comment]
Hi @Yb2S3Man  - the URL should be `gradio_api/file=/work/aaa/common_voice...`

**Comment by Yb2S3Man** [comment]
Thank you @freddyaboulton, it works for me.
