### ISSUE TITLE
Client, is requests available ?

### ISSUE THREAD

**Issue by monkeycc** [gradio-app/gradio#8289]
`gradio_client`

I want to obtain the HTTP protocol interface
`python requests `

The client submits data through requests
Or submit through C++C #
But no examples were provided

**Comment by freddyaboulton** [comment]
Hi @monkeycc ! We're preparing some official documentation for this ahead of the 1.0 release of the clients. In the meantime, I've prepared a guide on how you can query a gradio app with curl which can then be adapted to your language of choice:

https://www.freddyboulton.com/blog/gradio-curl
