### ISSUE TITLE
Slider not set at default value at launch when used with chatbot

### ISSUE THREAD

**Issue by tareknaous** [gradio-app/gradio#829]
### Describe the bug

I was building a demo for a DialoGPT-based chatbot model and used the chatbot output component. As inputs I created sliders to set the probability and temperature values for nucleus sampling and set default values for them (0.9 and 1 respectively). However:

-  when the demo launches the first slider visually appears at 0.1 although it displays 0.9. 
- Playing with the slider then clicking clicks sets it at the default value (0.9) but when I refresh the page it reappears at 0.1.

![image](https://user-images.githubusercontent.com/59765813/158848880-cc18fb4b-2356-4c1f-838f-7a467726a0e5.png)

### Reproduction

The code used:
```python
iface = gr.Interface(
    chat,
    inputs =["text", "state",
             gr.inputs.Slider(0.1, 1, step=0.1, label='Top-p', default=0.9),
             gr.inputs.Slider(0.1, 3, step=0.1, label='Temperature', default=1)],
    outputs = ["chatbot", "state"],
    allow_screenshot=False,
    allow_flagging="never",
    title=title,
    description=description
)
iface.launch(debug=True)
```

### System Info

```shell
Gradio version: 2.8.10
Operating system: Windows 10
Browser: google chrome
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Hi @tareknaous I can confirm that this is now fixed. If you'd like, you can test it in our beta release: `pip install gradio==2.9b8`
