### ISSUE TITLE
Unable to reference TextBox when loading HF Space with gr.load.

### ISSUE THREAD

**Issue by s-chyi** [gradio-app/gradio#8295]
### Describe the bug

When I create an app based on chatinterface in HF Space, I can call it normally on HF. However, when I import it with gr.load("ch-yi/demo_chatinterface", src="spaces") in another HF Space or in any Python environment, errors occur. The biggest issue is that the TextBox always returns None.

https://huggingface.co/spaces/ch-yi/demo_chatinterface

- Invoke in that HF Space
![image](https://github.com/gradio-app/gradio/assets/132654632/3d53482e-f57f-4a87-a3e3-640f07af037a)

- Invoke using Python locally

```python
import gradio as gr
demo = gr.load("ch-yi/demo_chatinterface", src="spaces").launch()
```
![image](https://github.com/gradio-app/gradio/assets/132654632/3880acd7-d848-4e0d-9f9e-9b47829bd942)

Here is the code on HF Space.
```python
import gradio as gr

def slow_echo(message, history, additional_1, additional_2, additional_3, additional_4):
    for i in range(len(message)):
        yield "You typed: " + message[: i+1] + f"\nAdditional: {additional_1}, {additional_2}, {additional_3}, {additional_4}" 

with gr.Blocks() as app:
    number = gr.Number(100)
    text = gr.Textbox(value="test")
    gr.ChatInterface(fn=slow_echo, additional_inputs=[number, text]).queue()
    
app.launch()
```
The extra output is due to my discovery that the additional parameters after gr.load start displaying from the fifth index, rather than the original third index.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
demo = gr.load("ch-yi/demo_chatinterface", src="spaces").launch()
```

### System Info

```shell
gradio version: 4.29.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue yet, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio
