### ISSUE TITLE
Custom values are not supported when 'multiselect' is True ?

### ISSUE THREAD

**Issue by xudong2019** [gradio-app/gradio#8304]
### Describe the bug

I am running llama factory on a cluster, and encounter this issue:
ValueError: Custom values are not supported when 'multiselect' is True ?

Any one can give me suggestions on this issue?  thanks

<img width="936" alt="ec4a129d2c96a8a6be51c797dccd9a8" src="https://github.com/gradio-app/gradio/assets/16278392/434446fc-b542-434a-a837-1112bb3e7ec4">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
gradio version:3.38.0
gradio Dependencies:aiofiles:23.2.1
aiohttp: 3.9.3
altair: 5.3.0
fastapi: 0.110.1
ffmpy: 0.3.2
gradio-client: 0.16.3
httpx: 0.27.0huggingface-hub: 0.22.2
jinja2: 3.1.4
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @xudong2019 yes we've fixed this issue in recent releases of gradio, so please upgrade:

```
pip install --upgrade gradio
```
