### ISSUE TITLE
Speech to text output text box issue

### ISSUE THREAD

**Issue by monishreddye** [gradio-app/gradio#8307]
### Describe the bug

I am working on whisper speech to text, I have two option for user for converting speech to text, microphone and audio file. 
once audio or microphone is on when user speaks, output text box saying error same for when audio file uploaded and click on submit.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```
'''
import whisper

# You can choose your model from - see it on readme file and update the modelname
modelname = "base"
model = whisper.load_model(modelname)

import gradio as gr
import time

def transcribe(audio):

    # load audio and pad/trim it to fit 30 seconds
    audio = whisper.load_audio(audio)
    audio = whisper.pad_or_trim(audio)

    # make log-Mel spectrogram and move to the same device as the model
    mel = whisper.log_mel_spectrogram(audio).to(model.device)

    # detect the spoken language
    _, probs = model.detect_language(mel)
    print(f"Detected language: {max(probs, key=probs.get)}")

    # decode the audio
    options = whisper.DecodingOptions()
    result = whisper.decode(model, mel, options)
    return result.text

interface = gr.Interface(
    fn=transcribe,
    inputs=[gr.Audio(), gr.File()],  # Microphone and file options, no source argument
    outputs="text",
    description="Speech to Text for Medical Summarization"
)

interface.launch()

'''

### Screenshot

<img width="940" alt="gradio output textbox" src="https://github.com/gradio-app/gradio/assets/168388982/db9e0dac-c906-4136-9897-54e52fbe2b38">
<img width="940" alt="gradio output textbox" src="https://github.com/gradio-app/gradio/assets/168388982/1c4682c6-a488-4d8b-bfef-75efac7c82f7">

### System Info

```shell
Latest version 4.29.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @monishreddye can you please clarify what the error is, and provide formatted code?

**Comment by abidlabs** [comment]
Closing for now, we can reopen with more details
