### ISSUE TITLE
`gr.load()` does not work inside `gr.Blocks`

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#8310]
### Describe the bug

This does not work:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.load("abidlabs/en2fr", src="spaces")
    
demo.launch()
```

but this does:

```py
import gradio as gr

demo = gr.load("abidlabs/en2fr", src="spaces")
    
demo.launch()
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

See above

### System Info

```shell
gradio==4.31.3
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
I think this is a dupe of https://github.com/gradio-app/gradio/issues/7996

**Comment by abidlabs** [comment]
Ah thanks @freddyaboulton missed that one
