### ISSUE TITLE
Be able to generate random samples in `gr.Examples` or `examples` in `gr.ChatInterface`

### ISSUE THREAD

**Issue by djstrong** [gradio-app/gradio#8325]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I am using ChatInterface (https://huggingface.co/spaces/speakleash/Bielik-7B-Instruct-v0.1-test/blob/main/app.py) and want to sample examples with every page load.

**Describe the solution you'd like**  
Maybe add `sample_examples` parameter to the ChatInterface?

**Additional context**  
I tried `load` listener but without success.
Related issues: https://github.com/gradio-app/gradio/issues/5042 https://github.com/gradio-app/gradio/issues/8293

**Comment by abidlabs** [comment]
Hi @djstrong if I understand correctly, you want to change the examples randomly every time the page loads?

**Comment by djstrong** [comment]
Yes.

**Comment by abidlabs** [comment]
I am [working on a PR](https://github.com/gradio-app/gradio/pull/8745) that will allow this to happen. You can test it by doing:

```
pip install https://gradio-builds.s3.amazonaws.com/c2dc8a1bd9585c3170a116d12a465be9223f1310/gradio-4.37.2-py3-none-any.whl
```

and then doing something like this:

```py
import gradio as gr
import random

def update_examples():
    return gr.Dataset(samples=random.choice(
        [
            [["merhaba"], ["merhaba2"]],
            [["bonjour"], ["bonjour2"]]
        ]
    ))

with gr.Blocks() as demo:
    chat = gr.ChatInterface(lambda x,y:x, examples=[["hello"], ["hi"]])
    demo.load(update_examples, None, chat.examples_handler.dataset)
    
demo.launch()
```

**Comment by djstrong** [comment]
@abidlabs Thanks. But it doesn't work correctly. After clicking an example button different text is provided. You can check here: https://huggingface.co/spaces/speakleash/Bielik-7B-Instruct-v0.1
![image](https://github.com/user-attachments/assets/b3808edd-2102-48b0-9f8e-1116dc74436c)

**Comment by nettnikl** [comment]
@abidlabs Hey, the provided example does not work, for me there is always "hello"+"hi" in a updated 5.x Gradio.
