### ISSUE TITLE
How to support carriage return sending in the textbox component

### ISSUE THREAD

**Issue by nvliajia** [gradio-app/gradio#8333]
### Describe the bug

import gradio as gr

def greet(name):
    return "Hello " + name + "!"

with gr.Blocks() as demo:
    name = gr.Textbox(label="Name",render=True)
    output = gr.Textbox(label="Output Box")
    greet_btn = gr.Button("Greet")
    greet_btn.click(fn=greet, inputs=name, outputs=output, api_name="greet")

demo.launch()

How can I set up the Enter key to send messages with the above code？

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

def greet(name):
    return "Hello " + name + "!"

with gr.Blocks() as demo:
    name = gr.Textbox(label="Name",render=True)
    output = gr.Textbox(label="Output Box")
    greet_btn = gr.Button("Greet")
    greet_btn.click(fn=greet, inputs=name, outputs=output, api_name="greet")

demo.launch()

### Screenshot

How can I set up the Enter key to send messages with the above code?

### Logs

```shell
How can I set up the Enter key to send messages with the above code?
```

### System Info

```shell
How can I set up the Enter key to send messages with the above code?
```

### Severity

I can work around it

**Comment by crischeng** [comment]
I met the same problem, how did you solve it, please.

**Comment by crischeng** [comment]
set lines=1 can solve this problem.textbox = gr.Textbox(lines=1, label='Input')
