### ISSUE TITLE
How to access local image and css files in gradio.HTML

### ISSUE THREAD

**Issue by Jason-cs18** [gradio-app/gradio#8340]
- [x] I have searched to see if a similar issue already exists.
My task is to load local `style.css` and `assets/xxx.png` in gradio.HTML component. I searched all issues and found that added `allowed_path` to `block.launch` may work. However, my gradio app is mounted to my FastAPI app. Thus, I did not find any solutions.

```python
# app.py
with gr.Blocks(title="Demo") as demo1:
    gr.HTML("""
    <!DOCTYPE html>
    <html lang="cn">
        <head>
            <link href="css/styles.css" rel="stylesheet" />
        </head>
        <body>
            <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('assets/img/bg-showcase-1.jpg')"></div>
        </body>
"""

demo1.allowed_paths=["."]
app = gr.mount_gradio_app(app, demo1, path="/demo1")

```

Filestructure
```bash
- app.py
- css
   - styles.css
- assets
    - xxx.png
```

Environment:
- Ubuntu 20.04.6 LTS
- Gradio 4.31.4

404 Not Found 
![image](https://github.com/gradio-app/gradio/assets/10672549/35ddf00e-7a4f-4b5e-82b4-681f450c8d51)

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by Jason-cs18** [comment]
@freddyaboulton @abidlabs

**Comment by abidlabs** [comment]
Hi @Jason-cs18 the `mount_gradio_app()` function accepts the same `allowed_paths` parameter as well!

**Comment by Jason-cs18** [comment]
> Hi @Jason-cs18 the `mount_gradio_app()` function accepts the same `allowed_paths` parameter as well!

Thanks for your reply. I have tried to add `allowed_path` to `mount_gradio_app()` and still got a 404 error.

```python
# option 1
<link href="css/styles.css" rel="stylesheet" />
app = gr.mount_gradio_app(app, demo1, path="/demo1", allowed_paths=["."])
# option 2
<link href="styles.css" rel="stylesheet" />
app = gr.mount_gradio_app(app, demo1, path="/demo1", allowed_paths=["./css/styles.css"])

```
![image](https://github.com/gradio-app/gradio/assets/10672549/09dbeb81-5224-44e3-a7d6-5c1bbd1a156d)

**Comment by abidlabs** [comment]
What's the full code of the app so that I can reproduce?
