### ISSUE TITLE
support websockets 12.0

### ISSUE THREAD

**Issue by wyfSunflower** [gradio-app/gradio#8343]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
there is dependency conflict when other package need websockets 12.0
**Describe the solution you'd like**  

**Additional context**

**Comment by freddyaboulton** [comment]
HI @wyfSunflower ! Gradio no longer uses websockets as of version 4.0! If you're using an older version I recommend you upgrade.

**Comment by egeres** [comment]
Hey @freddyaboulton!

I'm not sure about this, but I it looks like gradio-client does indeed use `websockets>=10.0,<12.0` according to https://github.com/gradio-app/gradio/blob/main/client/python/requirements.txt, and gradio uses gradio-client, so by extension it's still dependent on websockets <= 12

**Comment by freddyaboulton** [comment]
Yes that is true.  Would you want to open a PR to include version 12 in the allowed range? Provided that it still works as expected
