### ISSUE TITLE
Gradio State objects hang the Gradio App

### ISSUE THREAD

**Issue by asobh-ep** [gradio-app/gradio#8346]
### Describe the bug

I launch my Gradio Blocks demo via localhost and open a bunch of tabs connecting to the app. After opening ~5 tabs, the app becomes unresponsive and when opening more tabs they do not load the Gradio interface. Once I close out of the first 5 tabs I opened, whatever is blocking Gradio gets freed up and I can use the app/load tabs again (until I load up to 5 tabs, which makes the Gradio app unresponsive again).

This is a new bug that I have experienced on newer versions of Gradio. If I downgrade to Gradio 4.21.0, this problem is not present.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
with gr.Blocks() as Demo:
    i = gr.State(0)

Demo.config["dev_mode"] = False
Demo.launch(server_name='0.0.0.0', server_port=3000)
```

### System Info

```shell
gradio==4.25.0 and newer have this bug.

I haven't tested all versions in between, but at least gradio==4.21.0 does NOT have this bug.
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Yes this is expected because the browser will only allow five concurrent requests at a time. See #8169

**Comment by asobh-ep** [comment]
Is this a limit per browser? I'm basically simulating multiple users hitting my app. So would this mean only 5 users can hit my app? or each user can have a max of 5 tabs of the app open?

**Comment by asobh-ep** [comment]
Ah, read the thread and tested w/Safari. Looks like it should be fine. Thanks @freddyaboulton for the quick response

**Comment by freddyaboulton** [comment]
> or each user can have a max of 5 tabs of the app open?

This ☝️ . Sorry, I worded that incorrectly.
