### ISSUE TITLE
Remove submit button when live is used

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#835]
**Is your feature request related to a problem? Please describe.**
If I'm using `launch(live=True)`, the submit button has no purpose.

**Describe the solution you'd like**
For the `Submit` button to be removed when `live=True`.

**Comment by FarukOzderim** [comment]
@aliabid94 while building Interface with blocks can we also add this?

**Comment by abidlabs** [comment]
This actually used to be the case! I don't know when this behavior was changed, but can confirm that the submit button now shows even with live=True. @aliabid94 do you know?

![image](https://user-images.githubusercontent.com/1778297/159037605-b1a070b9-b9dd-4190-ba33-92569ca26149.png)

**Comment by abidlabs** [comment]
This is now fixed in the latest beta release: 

![image](https://user-images.githubusercontent.com/1778297/164074761-0cb84095-78f0-4715-980e-472bc9242fe4.png)

**Comment by abidlabs** [comment]
Thanks for creating the issue @osanseviero!
