### ISSUE TITLE
How to custom footer of gradio app?

### ISSUE THREAD

**Issue by Jason-cs18** [gradio-app/gradio#8350]
- [x] I have searched to see if a similar issue already exists.

I want to present my custom footer in my gradio app. However, I just found materials about "hide/delete footer. Please give me a simple example (e.g., print "hello world" in footer) to illustrate this process.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by Jason-cs18** [comment]
@abidlabs

**Comment by abidlabs** [comment]
Hi @Jason-cs18 that isn't possible at the moment. I don't think we'll implement an API for customizing the text of the footer. You could potentially do something similar by using a `gr.HTML` or `gr.Markdown` -- if you have questions about this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
