### ISSUE TITLE
Add delete or remove event to `gr.File`

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#8354]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

We recently fixed an issue where removing a file from a file component would trigger a select event but some people require an event to trigger when a file is removed. 
 
**Describe the solution you'd like**  
A dedicated event, similar to clear, but just for deleting an individual file.

**Comment by ngaudemet** [comment]
thanks, it was missing ! it is not yet on gradio 31.5 but will be in a next version, right ?

**Comment by pngwn** [comment]
I'll make sure we get this out in the next release.

**Comment by ngaudemet** [comment]
Hi @pngwn 
thanks for your help
I still can't upgrade to newer gradio version (I'm still on 4.29.0) because it seems the introduction of the delete event for File components destroyed the select event for File components. But it is useful as well. Thus I open a new issue.
****
