### ISSUE TITLE
HTML Output Hyperlink Styling

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#837]
**Is your feature request related to a problem? Please describe.**
HTML outputs should underscore and style like hyperlinks.

![image](https://user-images.githubusercontent.com/44067394/159017844-5e0eab6b-9058-40c7-bb5d-7613527fc1d7.png)

We can style the hyperlinks in the description as well:
![image](https://user-images.githubusercontent.com/44067394/159020122-38761b44-cbad-4f56-b7b6-ae38394daf94.png)

Hyperlink example:
![image](https://user-images.githubusercontent.com/44067394/159019993-cda23181-5f87-4317-b8f4-375ce3eb0770.png)

**Comment by abidlabs** [comment]
Underlining the links by default is a good idea. We also have the same problem in the Markdown/HTML type of the Dataframe column, where links are not underlined by default and one has to write custom css to get the links to appear with underlines. cc @AK391

**Comment by jerpint** [comment]
any updates on this?

**Comment by abidlabs** [comment]
Not yet. You can fix this by applying your own css to links via the `css` parameter in `gr.Interface` or `gr.Blocks`

**Comment by amirtha17** [comment]
> Not yet. You can fix this by applying your own css to links via the `css` parameter in `gr.Interface` or `gr.Blocks`

how to do this? any heads up for displaying one of the output as hyperlink

**Comment by pngwn** [comment]
Fixed when theming was overhauled internally.
