### ISSUE TITLE
Why can't my images be displayed in gr.Gallery()

### ISSUE THREAD

**Issue by IcyMing** [gradio-app/gradio#8379]
### Describe the bug

I pre-set a set of images to display with gr.Gallery(), but it failed. And I can use gr.Image() to show my picture. Why？Thank you for everyone who reads this issue.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

pattern_images = [
    "http://localhost:8000/img1.png",
    "http://localhost:8000/img2.png",
    "http://localhost:8000/img3.png",
    "http://localhost:8000/img4.png",
]

def generate_style_images(text, img_width, img_height, style, num_images):
    selected_images = black_images[:num_images]
    return selected_images

(.........)

                        with gr.Column():
                            output_style_img = gr.Gallery(label="images")
                        generate_style_button.click(fn=generate_style_images,
                                                    inputs=[text_input,
                                                            style,
                                                            img_width,
                                                            img_height,
                                                            num_images,
                                                            ],
                                                    outputs=output_style_img)

### System Info

```shell
gradio-4.31.5
```

### Severity

I can work around it

**Comment by missionfloyd** [comment]
https://www.gradio.app/docs/gradio/gallery

> **As input component:** Passes the list of images as a list of (image, caption) tuples, or a list of (image, None) tuples if no captions are provided (which is usually the case). The image can be a `str` file path, a `numpy` array, or a `PIL.Image` object depending on `type`.

So that should be:
```python
pattern_images = [
    ("http://localhost:8000/img1.png", None),
    ("http://localhost:8000/img2.png", None),
    ("http://localhost:8000/img3.png", None),
    ("http://localhost:8000/img4.png", None),
]
```

**Comment by abidlabs** [comment]
Hi @IcyMing, you don't need to put localhost in the path to the images typically, e.g. you don't need to do: http://localhost:8000/img1.png. Instead, just put the path relative to the working directory where Gradio was launched from, e.g. ["img1.png", "img2.png", ...]
