### ISSUE TITLE
Fooocus NOT WORKING on Google Colab's Gradio Link

### ISSUE THREAD

**Issue by thakurtech** [gradio-app/gradio#8387]
### Describe the bug

Fooocus (an LLM) NOT WORKING on Google Colab's Gradio Link , this issue was even seen earlier on Feb 2024 and I am facing now on 24th May 2024

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Try to run Fooocus llm on Google Collab through Gradio link

### System Info

```shell
Yes latest
```

### Severity

Blocking usage of gradio

**Comment by Bzxork** [comment]
same problem

**Comment by abidlabs** [comment]
Sorry it should be fixed now folks! Our share servers were down: https://status.gradio.app/
