### ISSUE TITLE
text is hard to read in article and description when huggingface theme is dark mode

### ISSUE THREAD

**Issue by AK391** [gradio-app/gradio#839]
### Describe the bug

hard to read text in default style with huggingface dark mode

### Reproduction

for example see space: https://huggingface.co/spaces/tomofi/MMOCR

### Screenshot

<img width="1062" alt="Screen Shot 2022-03-18 at 11 14 02 AM" src="https://user-images.githubusercontent.com/81195143/159044621-39fb507d-e0f6-4998-9760-a1ed87f43bda.png">

theme is set to dark through huggingface main page
<img width="235" alt="Screen Shot 2022-03-18 at 12 53 23 PM" src="https://user-images.githubusercontent.com/81195143/159047638-daf6a095-af6d-4f23-9643-cad5964dc48b.png">

### System Info

```shell
Spaces, gradio 2.8.12
```

### Severity

annoyance

**Comment by AK391** [comment]
this is also a issue when using theme='dark-huggingface'

**Comment by ronvoluted** [comment]
This has been bugging me a little too, will change it to something sensible.

**Comment by abidlabs** [comment]
That'd be great!

**Comment by FarukOzderim** [comment]
Thank you @ronvoluted for taking care of it!

**Comment by abidlabs** [comment]
Looks like this fixed via #1049, thanks @ronvoluted!
