### ISSUE TITLE
Dataframe not showing all items

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#8394]
### Describe the bug

https://huggingface.co/spaces/ylacombe/speech-explorer
https://huggingface.co/spaces/lhoestq/presidio-dataset-scanner

You basically can't scroll through all items. Not sure if the data isn't being loaded or this is related to scroll.

This definitely seems related to yielding results to a dataframe though.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://huggingface.co/spaces/ylacombe/speech-explorer
https://huggingface.co/spaces/lhoestq/presidio-dataset-scanner

### System Info

```shell
-
```

### Severity

Blocking usage of gradio

**Comment by lhoestq** [comment]
To summarize the investigation in https://github.com/radames/gradio-custom-components/issues/1: it seems it's due to the `HuggingfaceHubSearch `custom component. A workaround is to use custom CSS, e.g.

```python
with gr.Blocks(css=".table {border-collapse: separate}") as demo:
```
