### ISSUE TITLE
Additional parameters in ChatInterface have incorrect names

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#8399]
### Describe the bug

If you launch a ChatInterface with `additional_inputs`, the view api page will show an incorrect name for the additional inputs.

For example, the `system_prompt` is called `request` here:

<img width="896" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/37315706-7622-4480-99a7-229e78845ff5">

You can repro this by running `demo/chatinterface_system_prompt`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import time


def echo(message, history, system_prompt, tokens):
    response = f"System prompt: {system_prompt}\n Message: {message}."
    for i in range(min(len(response), int(tokens))):
        time.sleep(0.05)
        yield response[: i + 1]


demo = gr.ChatInterface(
    echo,
    additional_inputs=[
        gr.Textbox("You are helpful AI.", label="System Prompt"),
        gr.Slider(10, 100),
    ],
)

if __name__ == "__main__":
    demo.queue().launch()
```

and go to view api page

### System Info

```shell
latest main
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
This actually happens anytime a `gr.Request` is present in the arguments of a function and it is not the last argument, e.g.

```py
import gradio as gr
import time


def echo(message, request: gr.Request, num):
    return message

demo = gr.Interface(
    echo,
    ["textbox", "slider"],
    ["textbox"],
)

demo.launch()
```
