### ISSUE TITLE
How can we load audio files into Gradio video element?

### ISSUE THREAD

**Issue by FurkanGozukara** [gradio-app/gradio#8414]
I want to get both audio and video input from user. And i want user provided file to be displayed to the user

When I use gradio.video it can't pick audio files

this below works but that time it doesn't display loaded media?

input_video = gr.File(label="Target Input (Video or Audio)", type="filepath", file_count="single", file_types=["video", "audio"], height=512)

**Comment by abidlabs** [comment]
You could trigger an event when the file is uploaded (using `gr.File`'s `.upload`) event and depending on the file, render a Video or Audio component to display the media.
