### ISSUE TITLE
[Custom Components] Option for build target 

### ISSUE THREAD

**Issue by radames** [gradio-app/gradio#8416]
Sorry if there is already an open issue for this, but here's a reminder to add the `target: 'esnext'` option when building custom components.

cc @pngwn 

The currently workaround is do edit `node_modules` 

```
go into your node modules/gradio/preview/dist/index.js
go into line ~278
add this in the build object: target: 'esnext',
then `gradio cc build ` again
```

**Comment by pngwn** [comment]
Thanks for this @radames, it did indeed slip my mind.

**Comment by freddyaboulton** [comment]
+1 just ran into this myself for the pdf component when trying to upgrade pdf.js
