### ISSUE TITLE
TabbedInterface Error: the 'clear' and 'submit' of the second tab will operate the first tab

### ISSUE THREAD

**Issue by emptystack1024** [gradio-app/gradio#8425]
### Describe the bug

![image](https://github.com/gradio-app/gradio/assets/104486691/607d5c0b-c505-4bb9-9b48-851b7a8d63f7)
in the first image, i input '1' in the first tab, and press the submit.It shows the tight answer
![image](https://github.com/gradio-app/gradio/assets/104486691/56ad20d0-49a1-4f59-aeb1-45e66f01637b)
in the second image, in the second tab, i press the 'clear' and 'submit' , and there is nothing in second tab, but the '1' in first tab is disappeared and the wrong answer is in the first tab.
![image](https://github.com/gradio-app/gradio/assets/104486691/6f244d94-6f25-4d24-b3d6-d50f9eca3d67)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

hello_world = gr.Interface(lambda name: "Hello " + name, "text", "text")
bye_world = gr.Interface(lambda name: "Bye " + name, "text", "text")

demo = gr.TabbedInterface([hello_world, bye_world], ["Hello World", "Bye World"])

if __name__ == "__main__":
    demo.launch()
```

### System Info

```shell
>>> gradio.__version__
'4.32.0'
```

### Severity

Blocking usage of gradio

**Comment by Phillweston** [comment]
I've seen the same result, but it has still not been fixed.

**Comment by Phillweston** [comment]
I've rolled back to 4.31.5 version, which behaves properly without this error, but when upgraded to the newer version, this TabbedInterface error occurred, maybe we can analyze the code changes from 4.13.5 to 4.32.1.
