### ISSUE TITLE
Issue with Mounting Multiple Gradio Interfaces using gr.mount_gradio_app

### ISSUE THREAD

**Issue by yjtan0819** [gradio-app/gradio#8428]
### Describe the bug

I am currently facing an issue when trying to mount two Gradio interfaces using the `gr.mount_gradio_app` function. 

Here's what I am experiencing:
- When I mount the first Gradio interface at the root path ('/'), it works as expected and I can access it without any problems.
- However, when I try to mount the second Gradio interface at the path '/gradio', I am unable to reach it.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
from fastapi import FastAPI
import uvicorn

app = FastAPI()

def check_login_state(is_logged_in):
    if is_logged_in:
        return "Login", "Logout"
    else:
        return "Logout", "Login"
 
io = gr.TabbedInterface([
    gr.Interface(fn=lambda x: x, inputs="text", outputs="text"),
    gr.Interface(fn=lambda x: x, inputs="text", outputs="text")
])

app = gr.mount_gradio_app(app, io, path='/gradio')

app = gr.mount_gradio_app(app, io, path='/', auth_dependency = check_login_state)

if __name__ == "__main__":
    uvicorn.run(app)

```

### Screenshot

<img width="260" alt="image" src="https://github.com/gradio-app/gradio/assets/94803216/c136fd37-385f-4853-8152-e0ef4200fcdb">

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.32.1
gradio_client version: 0.17.0

------------------------------------------------
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
I have not looked into it but I think this makes sense. When you mount gradio at the root `/`, the request to `/gradio` will be sent to the gradio app at the root, which does not have a way to fulfill that request. 

Does this problem happen if the first app is not mounted at `/`? Or if you switch the order of the mounting (first mount at `/gradio` then `/`)?

**Comment by yjtan0819** [comment]
The problem does not happend if the first app its not mounted at `/`, but it happens if I switch the order of the mounting.

**Comment by freddyaboulton** [comment]
This is the intended behavior of FastAPI so I will close. 

```python
from fastapi import FastAPI

parent = FastAPI()

root = FastAPI()
child = FastAPI()

@root.get("/")
def hello():
    return "Hello"

@child.get("/hi")
def hi():
    return "hi"

parent.mount("/", root)
parent.mount("/child", child)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(parent, port=7860)
```

I suggest you don't place either app at the root and redirect visitors of the home page to whichever child app you want.

```python
from fastapi import FastAPI
from fastapi.responses import RedirectResponse

parent = FastAPI()

root = FastAPI()
child = FastAPI()

@parent.get("/")
def go_to_root():
    return RedirectResponse("/root")

@root.get("/")
def hello():
    return "Hello"

@child.get("/")
def hi():
    return "hi"

parent.mount("/root", root)
parent.mount("/child", child)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(parent, port=7860)
```

**Comment by pievalentin** [comment]
Thank you, @freddyaboulton very helpful !
