### ISSUE TITLE
Add flagging features into ChatInterface same as interface

### ISSUE THREAD

**Issue by sajjadmosaheb** [gradio-app/gradio#8434]
I am using the new modern ChatInterface instead blocks or interface but I can't able to use flagging features.

**Comment by sajjadmosaheb** [comment]
Do you have any more updates?

**Comment by sajjadmosaheb** [comment]
any update for Chatinterface flagging?

**Comment by abidlabs** [comment]
Hi @sajjadmosaheb we are not really planning on adding flagging by default to gr.ChatInterface. If needed, you can add events to like/dislike individual messages in a custom chatbot, [as described here](https://www.gradio.app/guides/creating-a-chatbot-fast#customizing-your-chatbot), or construct your [own chat ui using the Blocks API](https://www.gradio.app/guides/creating-a-custom-chatbot-with-blocks), as described here.
