### ISSUE TITLE
How to modify State(list) to trigger State.change()

### ISSUE THREAD

**Issue by coolboyqu** [gradio-app/gradio#8436]
It seems that state.change() can only be triggered when variables' id changes, such as int, str, etc. For a list, if only the elements in the list are modified, state.change() cannot be triggered unless a new copy of the list is copied and returned. However, copying the list every time can waste a lot of time and resources. Is there any way to add elements to the list and trigger state.change() without copying the list?

**Comment by abidlabs** [comment]
We're looking into a solution for this! cc @aliabid94
