### ISSUE TITLE
Showing Mesh Wireframe in Model3D

### ISSUE THREAD

**Issue by buaacyw** [gradio-app/gradio#8447]
- [√] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Sometimes users need to view the wireframe of mesh

**Describe the solution you'd like**  
Provide an option to show wireframe of mesh in Model3D

**Additional context**  
Recently there are some works focus on generating better mesh wireframes. (https://nihalsid.github.io/mesh-gpt/). Personally, I'm trying to use gradio to show my new work but find it impossible to render mesh wireframe.

**Comment by abidlabs** [comment]
Hi @buaacyw is there a particular file format / file extension for mesh wireframes that you need support for?

**Comment by buaacyw** [comment]
Thanks for your quick reply!
Don't need to be a particular file format. Any mesh file format should be able to easily showing its wireframes.
The result should be like this (a figure from MeshGPT):
![image](https://github.com/gradio-app/gradio/assets/52091468/b86b5979-ea25-40e2-a26c-fa0e7606d24b)

**Comment by buaacyw** [comment]
I believe this is quite easy to implement since you only need to highlight the edges.

**Comment by abidlabs** [comment]
It looks like this is supported in babylonjs, so it should be quite doable: https://www.babylonjs-playground.com/#QCU8DJ#22

We don't have a lot of bandwidth at the moment, but if a community contributor wants to take this on, happy to review PRs
