### ISSUE TITLE
Sliders on Firefox look different than Chrome

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#8450]
### Describe the bug

The slider in firefox looks different than the chrome one

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Firefox
![firefox](https://github.com/gradio-app/gradio/assets/41651716/12eea65e-01ee-4228-b05c-f4279aec776b)

### Chrome
![chrome](https://github.com/gradio-app/gradio/assets/41651716/625b72e9-5e74-4168-af91-84f3386b2486)

### System Info

```shell
Latest
```

### Severity

I can work around it

**Comment by pngwn** [comment]
I don't think those images show up @freddyaboulton.

**Comment by freddyaboulton** [comment]
Fixed - thanks @pngwn

**Comment by abidlabs** [comment]
Fixed in `5.0-dev` branch, thanks @hannahblair!
