### ISSUE TITLE
How to use tool="sketch" in gradio 4.x?

### ISSUE THREAD

**Issue by XavierCHEN34** [gradio-app/gradio#8492]
### Describe the bug

How to realize the following function with gradio 4? I searched for the docs but did not find the solution
base = gr.Image(label="Background", source="upload", tool="sketch", type="pil", height=512, brush_color='#FFFFFF', mask_opacity=0.5, brush_radius = 100)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

How to realize the following function with gradio 4? I searched for the docs but did not find the solution
base = gr.Image(label="Background", source="upload", tool="sketch", type="pil", height=512, brush_color='#FFFFFF', mask_opacity=0.5, brush_radius = 100)

### System Info

```shell
/
```

### Severity

Blocking usage of gradio

**Comment by pngwn** [comment]
The `Image` component was split into `Image` and `ImageEditor` in 4.0. You can achieve the same result with:

```py
gr.ImageEditor(
  sources=['upload'], 
  type= 'pil'
)
```


Brush (both size and color) now has its own options that you can experiment with. Unfortunately this is not present on the docs but the brush kwarg take a class that looks like this:

```py
gr.Brush(
  default_size = "auto",
  colors = [
    "rgb(204, 50, 50)",
    "rgb(173, 204, 50)",
    "rgb(50, 204, 112)",
    "rgb(50, 112, 204)",
    "rgb(173, 50, 204)",
  ],
  default_color = "auto"
  color_mode = "defaults"
)
```

There are also a series of [shorthand presets](https://www.gradio.app/docs/gradio/imageeditor#shortcuts).

**Comment by pngwn** [comment]
We will update the docs.

**Comment by XavierCHEN34** [comment]
Thank you, but how to demonstrate the mask with opacity?
