### ISSUE TITLE
Running `gradio cc dev --host x.x.x.x`  on a remote machine does not work.

### ISSUE THREAD

**Issue by 0asa** [gradio-app/gradio#8493]
### Describe the bug

I'm trying to build a custom component. I want to develop on a remote machine. 
I thought I could use the `--host` option to change the default `localhost` for the public interface.
But: 
- in the terminal, the backend seems to be running on `127.0.0.1`
- in the terminal, the frontend link (after the (Go here):) is empty.
- in the web browser, the following error suggest appears in the console logs: `GET http://localhost:7863/config net::ERR_CONNECTION_REFUSED`

Looks like the given host is not properly propagated.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Run: 

```bash
gradio cc dev --host 0.0.0.0
```

Open the browser. 
Nothing is working as expected.

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.36.0
gradio_client version: 1.0.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.3.0
fastapi: 0.111.0
ffmpy: 0.3.2
gradio-client==1.0.1 is not installed.
httpx: 0.27.0
huggingface-hub: 0.23.2
importlib-resources: 6.1.3
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.9.0
numpy: 1.26.4
orjson: 3.10.3
packaging: 24.0
pandas: 2.2.2
pillow: 10.3.0
pydantic: 2.7.2
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.4.8
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.12.0
urllib3: 2.2.1
uvicorn: 0.28.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.5.0
httpx: 0.27.0
huggingface-hub: 0.23.2
packaging: 24.0
typing-extensions: 4.12.0
websockets: 11.0.3
```
```


### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue yet, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio
