### ISSUE TITLE
[Gradio Client] cannot pass keyword arguments

### ISSUE THREAD

**Issue by fakerybakery** [gradio-app/gradio#8498]
### Describe the bug

I'm getting `TypeError: Client.predict() got an unexpected keyword argument ...` when using the gradio_client library. This issue did not occur in the past.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

When using the Gradio client

### System Info

```shell
I tried multiple versions of gradio_client (0.19 and 1.0.1) but none worked
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
What is the space you're trying to use via Client? Can you share the code so we can reproduce please?

**Comment by fakerybakery** [comment]
```python
    return client.predict(
		seed=-1,
[...]
		api_name="/run"
    )[0]
```

**Comment by freddyaboulton** [comment]
What space are you connecting to? The keyword arguments work for the spaces I've tried so we need more information to be able to fix. Thanks!

**Comment by fakerybakery** [comment]
Hi, I fiddled around with the versions of the different spaces a bit and it seems to work now! Thanks!

**Comment by freddyaboulton** [comment]
Thanks @fakerybakery !

**Comment by twentyoneSven** [comment]
I have the same problem.
```
image_caption = client.predict(
TypeError: Client.predict() got an unexpected keyword argument 'image'
```

my code:
```
image = image path
client = Client("gokaygokay/paligemma-rich-captions")
image_caption = client.predict(
image=file(image),
api_name="/create_captions_moondream"
)
```
