### ISSUE TITLE
ChatBot API documentation does not use keyword argument syntyax

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#8500]
### Describe the bug

For some reason the `/chat` endpoints of the gradio documentation doesn't use the update 'keyword argument' object syntax.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://huggingface.co/spaces/gradio-templates/chatbot

### Screenshot

<img width="940" alt="Screenshot 2024-06-07 at 21 55 15" src="https://github.com/gradio-app/gradio/assets/12937446/72b53d1d-b903-4bab-919b-86295e84d972">

### System Info

```shell
latest
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
I believe fixed by https://github.com/gradio-app/gradio/pull/8400

**Comment by pngwn** [comment]
Ah. let me update and check.

**Comment by abidlabs** [comment]
Updated and confirmed:

<img width="936" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/16da7a4d-d97c-40fd-a86b-d781f45c8fe6">
