### ISSUE TITLE
Redirect to the specified URL

### ISSUE THREAD

**Issue by coolboyqu** [gradio-app/gradio#8509]
I have created a login interface (/login) using FastAPI to log in to Gradio, and I want to query a value every second in the Blocks.load of Gradio (/gradio), and then return to the login interface if the value changes. Is it currently supported to redirect to a certain page in Gradio?

**Comment by abidlabs** [comment]
By the way, for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
