### ISSUE TITLE
How to get uploaded image and if user draws a mask get it as a gray mask from ImageEditor

### ISSUE THREAD

**Issue by FurkanGozukara** [gradio-app/gradio#8514]
What I want is using a single component ImageEditor

So i want to get user uploaded image and also if user draw mask even in different colors i want to get that mask as gray mask

So I can use it in my new BIRD inpainting app

If I can get them as a input_img.png and gray_mask.png would be best

Or saving them as like that then i can also provide their saved path

thank you @abidlabs @aliabd @pngwn @freddyaboulton 

![image](https://github.com/gradio-app/gradio/assets/19240467/0b176245-be59-4840-9604-ce4a4ba68d71)

**Comment by pngwn** [comment]
Hello, this is possible today.

You can take the background image and save it to disk (or process it), then you can take the 'layers', combine them into a single image by overlaying the opaque pixels and convert them all to a uniform grey value.

I am created a space demonstrating this here:

https://huggingface.co/spaces/pngwn/gradio-imageeditor-combine-masks

Example:
<img width="832" alt="Screenshot 2024-06-10 at 12 40 48" src="https://github.com/gradio-app/gradio/assets/12937446/2fda344d-9101-4b35-9113-41ef345bf3eb">

This creates a single uniform grey mask, regardless of the colors used by the users and regardless of how many separate layers they use.

This example uses numpy but the same effect can be achieved (more simply) with PIL. The numpy variant is more performant though.
