### ISSUE TITLE
client <-> server function id mismatch when rendering within sub-blocks

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#8515]
### Describe the bug

~I don’t really understand it right now. But with a certain combination of settings, mostly around disabling the api, the app tries to post to the server instead of using the queue, which gets blocked causing it to fail.~

When i said I don't understand, it was clearly an understatement. The issue is totally different to my hunch.

Essentially when a block is rendered inside another block the ids on the client (inside `config.dependencies[number]`) don't match those on the server (inside `blocks_config.fns`). I'm not entirely sure what causes this but It seems that the function needs to have more than one input? I haven't tested extensively but reducing the inputs down to 1 did make the issue go away.

When i say "render within subblocks" i mean this:

```py
import gradio as gr

blocks = gr.Blocks()

with blocks:
  ...

with gr.Blocks() as demo:
  blocks.render()

demo.launch()
```

**Comment by freddyaboulton** [comment]
Adding more details in case they're relevant

- The request to load examples should never go on the queue
- Setting `api_open=False` and `queue=False` should not cause problems so the issue is in some other param in that demo I think.

**Comment by pngwn** [comment]
My guess was wrong, updating with new info.
