### ISSUE TITLE
OAuth (Sign In With Hugging Face) Not Working in Spaces (Too Many Redirects)

### ISSUE THREAD

**Issue by matdmiller** [gradio-app/gradio#8533]
### Describe the bug

The Login With Huggingface button and corresponding Oauth flow is not working. When I click the Sign In With Hugging Face button it takes me to a page to input my Hugging Face Username and Password. When I click Log In it asks for my MFA code. When I input that and click Verify in Safari it takes me back to the login screen again and in Chrome a grey box pops up and says Too Many Redirects. 

I tried to implement the Huggingface Login Button into my app by referencing the example in the docs. When I was unable to get that working I fell back to creating a new Space using the exact code from the [docs](https://www.gradio.app/guides/sharing-your-app#o-auth-login-via-hugging-face) and experienced the same result. I also tried the [Login With Huggingface Oauth template workspace](https://huggingface.co/spaces/templates/gradio-oauth) and experienced the same result. I've tried in Safari and Chrome on MacOS Sonoma including Incognito mode in Chrome. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Tested in HF Space: [https://huggingface.co/spaces/matdmiller/hf-oauth](https://huggingface.co/spaces/matdmiller/hf-oauth)
app.py -> from docs: [https://www.gradio.app/guides/sharing-your-app#o-auth-login-via-hugging-face](https://www.gradio.app/guides/sharing-your-app#o-auth-login-via-hugging-face)
```python
#Code is copied and pasted exactly from docs
import gradio as gr
from huggingface_hub import whoami

def hello(profile: gr.OAuthProfile | None) -> str:
    if profile is None:
        return "I don't know you."
    return f"Hello {profile.name}"

def list_organizations(oauth_token: gr.OAuthToken | None) -> str:
    if oauth_token is None:
        return "Please log in to list organizations."
    org_names = [org["name"] for org in whoami(oauth_token.token)["orgs"]]
    return f"You belong to {', '.join(org_names)}."

with gr.Blocks() as demo:
    gr.LoginButton()
    m1 = gr.Markdown()
    m2 = gr.Markdown()
    demo.load(hello, inputs=None, outputs=m1)
    demo.load(list_organizations, inputs=None, outputs=m2)

demo.launch()
```
Readme.md
```markdown
---
title: Hf Oauth
emoji: 🔥
colorFrom: red
colorTo: purple
sdk: gradio
sdk_version: 4.36.1
app_file: app.py
pinned: false
license: mit
hf_oauth: true
---

Check out the configuration reference at https://huggingface.co/docs/hub/spaces-config-reference
```

### Screenshot

<img width="1419" alt="Screenshot 2024-06-11 at 9 36 59 PM" src="https://github.com/gradio-app/gradio/assets/11518677/dafd15d6-f1da-4494-bf83-3ab2f3d1b7b8">
<img width="1421" alt="Screenshot 2024-06-11 at 9 37 14 PM" src="https://github.com/gradio-app/gradio/assets/11518677/a2dfcf69-28c1-4897-9628-9b0b1b18cb18">

<img width="1420" alt="Screenshot 2024-06-11 at 9 27 39 PM" src="https://github.com/gradio-app/gradio/assets/11518677/6eb61a9e-760b-46c4-b05d-ef619f6e2ca2">
<img width="1419" alt="Screenshot 2024-06-11 at 9 27 58 PM" src="https://github.com/gradio-app/gradio/assets/11518677/503d679f-84c5-46f1-adf9-066e68e5d166">
<img width="1662" alt="Screenshot 2024-06-11 at 9 28 36 PM" src="https://github.com/gradio-app/gradio/assets/11518677/5dabc03d-a76d-4490-9173-2d5507c317b4">
<img width="1661" alt="Screenshot 2024-06-11 at 9 28 56 PM" src="https://github.com/gradio-app/gradio/assets/11518677/0015e019-a238-445e-ae90-262948b0b5b0">
<img width="1660" alt="Screenshot 2024-06-11 at 9 29 13 PM" src="https://github.com/gradio-app/gradio/assets/11518677/903f842a-1d3f-4241-bb63-046fee76429b">
<img width="1662" alt="Screenshot 2024-06-11 at 9 29 32 PM" src="https://github.com/gradio-app/gradio/assets/11518677/e260b01e-a396-4cab-b031-bdd8dda83886">
<img width="1419" alt="Screenshot 2024-06-11 at 9 30 27 PM" src="https://github.com/gradio-app/gradio/assets/11518677/72cf4ddb-cf91-48da-9c1d-17283d44fbe2">

### Logs

```shell
Unrecognized feature: 'ambient-light-sensor'.Understand this warning
hf-oauth:211 Unrecognized feature: 'battery'.Understand this warning
hf-oauth:211 Unrecognized feature: 'document-domain'.Understand this warning
hf-oauth:211 Unrecognized feature: 'layout-animations'.Understand this warning
hf-oauth:211 Unrecognized feature: 'legacy-image-formats'.Understand this warning
hf-oauth:211 Unrecognized feature: 'oversized-images'.Understand this warning
hf-oauth:211 Unrecognized feature: 'vr'.Understand this warning
hf-oauth:211 Unrecognized feature: 'wake-lock'.Understand this warning
iframeResizer.contentWindow.min.js:9 [iFrameSizer][iFrameResizer0] No tagged elements (data-iframe-height) found on page
ae @ iframeResizer.contentWindow.js:177
be @ iframeResizer.contentWindow.js:930
taggedElement @ iframeResizer.contentWindow.js:994
Ee @ iframeResizer.contentWindow.js:1059
Se @ iframeResizer.contentWindow.js:1118
ue @ iframeResizer.contentWindow.js:196
init @ iframeResizer.contentWindow.js:1198
(anonymous) @ iframeResizer.contentWindow.js:1282Understand this warning
iframeResizer.contentWindow.min.js:9 [iFrameSizer][iFrameResizer0] No tagged elements (data-iframe-height) found on page

_______________

===== Application Startup at 2024-06-12 01:56:02 =====

Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
/usr/local/lib/python3.10/site-packages/gradio/components/login_button.py:74: UserWarning: LoginButton created outside of a Blocks context. May not work unless you call its `activate()` method manually.
  warnings.warn(
```

### System Info

```shell
Running in HF Spaces: https://huggingface.co/spaces/matdmiller/hf-oauth
Running on MacOS Sonoma
Chrome (Incognito) & Safari Browsers
```

### Severity

Blocking usage of gradio

**Comment by matdmiller** [comment]
I went through and tested previous versions of Gradio and it appears that 4.26 was the last version that worked and every version since 4.27 that I tested did not work including 4.36.1 which is the latest as of today.

When I was trying to latest version that did work it redirects the page to https://matdmiller-hf-oauth.hf.space/ instead of only redirecting the iframe. I then tried upgrading the version of gradio to 4.36.1 and starting out at https://matdmiller-hf-oauth.hf.space/ instead of https://huggingface.co/spaces/matdmiller/hf-oauth after the page reloaded and it worked. It seems like something with the default iframe spaces implementation is broken when using huggingface oauth, but not if you visit the second version of the URL.

**Comment by abidlabs** [comment]
Thank you for the detailed issue report @matdmiller! @Wauplin do you think you could take a look?

**Comment by abidlabs** [comment]
Hi @matdmiller could you check to see if https://github.com/gradio-app/gradio/pull/8951 fixes the issue for you?

You'll need to set the `sdk_version` to `4.39.0` in your Space README and then add `https://gradio-builds.s3.amazonaws.com/4485dd46a8e4b3f5b35e42d52f291b72fdc1a952/gradio-4.39.0-py3-none-any.whl` in your `requirements.txt` file
