### ISSUE TITLE
`Textbox` component not working in `Blocks`

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#854]
### Describe the bug

The `Textbox` component is not working in `Blocks`. It doesn't seem to send any data back.

### Reproduction

Try this on the `Blocks-Dev` branch

```py
import gradio as gr

gr.Interface(lambda x:x, "text", "text").launch()
```

### Screenshot

![image](https://user-images.githubusercontent.com/1778297/159592968-4a1bcb83-07e2-48ce-a2a9-e4de7de41efc.png)

### Logs

```shell
No console errors
```

### System Info

```shell
`Blocks-Dev` branch
```

### Severity

blocker

**Comment by pngwn** [comment]
Closed by #859.
