### ISSUE TITLE
Additional Authentication process.

### ISSUE THREAD

**Issue by Pilti** [gradio-app/gradio#8540]
- [x] I have searched to see if a similar issue already exists.

I need more security purpose for my application. In this way, after the ,login page authentication, I need one more authentication with some kind of OTP authentication. How to accomplish this?

**Comment by freddyaboulton** [comment]
You can have your own oauth instead of gradio's password authentication. See this guide: It’s interesting since Rerun doesn’t support any inputs from the UI
