### ISSUE TITLE
A Bug in Document

### ISSUE THREAD

**Issue by Marches7** [gradio-app/gradio#8551]
### Describe the bug

# Problems
When I read the Readme.md document, I found that this hyperlink "[30 built-in components](https://www.gradio.app/docs/gradio/components)" can't be opened. I got "404: NOT_FOUND" when visited it. It locates in the section "Understanding the Interface Class".
# **Solution**
I eventually find this site https://www.gradio.app/docs/gradio/introduction is correct. It give me the introduction of 30 built-in components of gradio. 

It is a good first issue for begginer and I can work around it:)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
document bug
```

### System Info

```shell
document bug
```

### Severity

I can work around it

**Comment by pngwn** [comment]
As you said that link should be changed to: `https://www.gradio.app/docs/gradio/introduction`

**Comment by Marches7** [comment]
> Thanks for flagging this @Marches7!
> 
> As you said that link should be changed to: `https://www.gradio.app/docs/gradio/introduction`

Thanks, I have create a PR https://github.com/gradio-app/gradio/pull/8553. Happy to make little contribution to gradio commnunity. :)

**Comment by pngwn** [comment]
Thank you!

Fixed by #8553!
