### ISSUE TITLE
website formatting bug - wandB integration page

### ISSUE THREAD

**Issue by robwsinnott** [gradio-app/gradio#8552]
### Describe the bug

On https://www.gradio.app/guides/Gradio-and-Wandb-Integration, 
there appears to be a bug on the website, where the text and code block formatting has gotten messed up. It is hard to read. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

see https://www.gradio.app/guides/Gradio-and-Wandb-Integration

### Screenshot

<img width="1101" alt="image" src="https://github.com/gradio-app/gradio/assets/38229894/74411842-839b-4822-8575-776f74b7b083">

### System Info

```shell
related to the website, not gradio directly.
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Fixed via https://github.com/gradio-app/gradio/pull/8585
