### ISSUE TITLE
Request to install PyCUDA in gradio Demo

### ISSUE THREAD

**Issue by iofu728** [gradio-app/gradio#8567]
- [x] I have searched to see if a similar issue already exists.

I am trying to build an efficient long-context LLMs inference demo in HF Demo using both ZeroGPU or general GPUs like L4. Unfortunately, I can't install PyCUDA, which is essential for my project. Is it possible to get support for this?

**Comment by abidlabs** [comment]
Hi @iofu728 this is not a question for the `gradio` library, the right place to ask about Spaces would be here: https://discuss.huggingface.co/c/spaces/24
