### ISSUE TITLE
Time out error while running gradio app

### ISSUE THREAD

**Issue by CharulataShelar** [gradio-app/gradio#8568]
### Describe the bug

Hi Team,

I have started getting error on gradio launch() function. which was working till last week. It has started giving timeout error now. Just to replicate the issue, I have tried the [demo code](https://www.gradio.app/guides/quickstart#building-your-first-demo) and I was able to replicate the issue.

FYI, installed gradio version : 4.36.1

```
import gradio as gr

def greet(name, intensity):
    return "Hello, " + name + "!" * int(intensity)

demo = gr.Interface(
    fn=greet,
    inputs=["text", "slider"],
    outputs=["text"],
)

demo.launch(share=True)
```
<img width="1505" alt="Screenshot 2024-06-17 at 11 48 15 AM" src="https://github.com/gradio-app/gradio/assets/33387365/bff9e29c-3a7f-4e7d-8c09-7b18b200f230">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def greet(name, intensity):
    return "Hello, " + name + "!" * int(intensity)

demo = gr.Interface(
    fn=greet,
    inputs=["text", "slider"],
    outputs=["text"],
)

demo.launch(share=True)
```

### System Info

```shell
Running above code in jupyter notebook from google colab.
```

### Severity

Blocking usage of gradio

**Comment by mzh045** [comment]
Maybe you should check if it works on the local interface, because the shareLink server is down again
https://status.gradio.app/793595809

**Comment by PrayushiFaldu** [comment]
Yes I am also facing similar issue.

**Comment by jostjerome** [comment]
hello, I have same issue in my side from this morning.

**Comment by universetao** [comment]
I have same issue too

**Comment by PrayushiFaldu** [comment]
Yes, resolved on my side as well.

**Comment by CharulataShelar** [comment]
It is working now for me as well. Thanks!
