### ISSUE TITLE
First time loading performance issue

### ISSUE THREAD

**Issue by baojianting** [gradio-app/gradio#8570]
When there are too many components on a page, the first loading can be time-consuming. For example:
![image](https://github.com/gradio-app/gradio/assets/7201302/86456b31-df6b-43e5-95df-7a82d14fea8b)
It cost about 2 seconds when first loading

**Comment by abidlabs** [comment]
Hi @baojianting do you have an example demo you can share? If so, please add to this issue: https://github.com/gradio-app/gradio/issues/2442

**Comment by abidlabs** [comment]
Ah ok just seeing your PR, let me reopen this
