### ISSUE TITLE
drop to replace for Image component

### ISSUE THREAD

**Issue by branaway** [gradio-app/gradio#8572]
currently I need to click the remove button to clear the space for me to drop a new image to an image component.  You will be much nicer if I can simply drop a new image on top of the current one and replace it.

Please consider this. Thanks

**Comment by abidlabs** [comment]
Hi @branaway, thanks but please do not create duplicate issues: https://github.com/gradio-app/gradio/issues/8535

**Comment by branaway** [comment]
Sorry I forgot I had already created one.
