### ISSUE TITLE
🔴 Real-Time Streaming like TextStreamer from Transformers

### ISSUE THREAD

**Issue by AnasLahmar** [gradio-app/gradio#8577]
I have searched to see if a similar issue already exists. Reference: **[#7868](https://github.com/gradio-app/gradio/issues/7868)**

### Problem:
When using TextStreamer from Transformers in a Google Colab notebook without a graphical interface, the generated text displays in real-time as it is processed, similar to platforms like ChatGPT or Hugging Face Chat.
`from transformers import TextStreamer`
`text_streamer = TextStreamer(tokenizer) `
`_ = model.generate(**inputs, streamer=text_streamer, max_new_tokens=588)`

**However, after implementing the solution from issue #7868, Gradio takes a significant amount of time for processing. The text is displayed in a streamed manner only after the complete text generation is finished.**

### Key Difference:

- Without Gradio (using only _TextStreamer_): Text is generated and displayed in real-time.
- With Gradio (#7868): Processing is delayed, and text is displayed in a streamed manner only after full generation.

### Code Example:

**Direct TextStreamer:**
![image](https://github.com/gradio-app/gradio/assets/99441751/dc158329-5b60-4181-b868-9265ae76c0b9)

**With Gradio and Issue #7868:**
![image](https://github.com/gradio-app/gradio/assets/99441751/fbda3f4e-aa45-4bc5-a21c-de396028828d)

### **Request:**
Could you provide guidance on how to adapt my code to ensure real-time text streaming with Gradio similar to the direct use of TextStreamer?

**Comment by abidlabs** [comment]
Hi @AnasLahmar thanks for your question. We ask that for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)

That being said, you might find this thread useful, which includes both an example demo and documentation: https://twitter.com/joao_gante/status/1643330507093196800
