### ISSUE TITLE
After upgrading from 3.45.1 to 4.36.1, fn in the button.click event cannot be fired

### ISSUE THREAD

**Issue by yangjun19950118** [gradio-app/gradio#8578]
### Describe the bug

import gradio as gr
def segment_everything(
    input,
    input_size=1024, 
    iou_threshold=0.7,
    conf_threshold=0.25,
    better_quality=False,
    withContours=True,
    use_retina=True,
    text="",
    wider=False,
    mask_random_color=True,
):
    print("print")
with gr.Blocks(title='fastSAM',theme=gr.themes.Soft()) as demo:
   segment_btn_e = gr.Button("run", variant='primary')
   segment_btn_e.click(
        fn=segment_everything,
        inputs=[
            cond_img_e,
            input_size_slider,
            iou_threshold_1,
            conf_threshold_1,
            mor_check_1,
            contour_check_1,
            retina_check_1,
        ],
        outputs=[segm_img_e]
    )
    
    #----------------------------------------------------
    Clicking the button does not trigger printing

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
python 3.9.19
gradio 4.36.1
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @yangjun19950118 can you please provide a complete, minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example.

**Comment by yangjun19950118** [comment]
> 你好@yangjun19950118您能否提供一个完整的、最小的代码示例，以便我们重现上述问题？请参阅：https://stackoverflow.com/help/minimal-reproducible-example。

https://huggingface.co/spaces/An-619/FastSAM/blob/main/README.md

**Comment by abidlabs** [comment]
Hi @yangjun19950118 that is not a [minimal example](https://stackoverflow.com/help/minimal-reproducible-example). I'm going to go ahead and close this until we have a suitable repro.

**Comment by yangjun19950118** [comment]
import gradio as gr
import torch

def everything():
    print("test")

with gr.Blocks(title='test',theme=gr.themes.Soft()) as demo:
    segment_btn_e = gr.Button("run", variant='primary')
    segment_btn_e.click(fn=everything)

if __name__ == "__main__":
    demo.queue(max_size=100).launch(share=True,debug=True,show_api=False,server_name='0.0.0.0')

**Comment by abidlabs** [comment]
Hi @yangjun19950118 this is working for me:

```py
import gradio as gr
import torch

def everything():
    print("test")

with gr.Blocks(title='test',theme=gr.themes.Soft()) as demo:
    segment_btn_e = gr.Button("run", variant='primary')
    segment_btn_e.click(fn=everything)

demo.queue(max_size=100).launch()
```

Can you test in an environment such as Colab notebook?

**Comment by yangjun19950118** [comment]
https://colab.research.google.com/drive/1FMOXsbuT12Z6CxUxFN7nQoXsA0pznY7t?usp=sharing

There is no problem in the Colab notebook environment, I virtualised the python3.9.19 environment through conda, if it is below gradio The 4.0.0 version is fine, but anything higher than 4.0.0 and above will not trigger methods,gradio, which is not compatible with other packages

**Comment by yangjun19950118** [comment]
gradio Whether python versions higher than 3.9 are required for versions higher than 4.0.0
