### ISSUE TITLE
Microphone in colab does not ask for permissions

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#858]
### Describe the bug

I have an interface with a microphone input, but it does not ask for permissions. I can click "Record" and then it stays in "Stop Recording". I cannot click it again, submit, clear or anything.

### Reproduction

Following code in a Google Colab

```
!pip install gradio pipeline transformers
import gradio as gr
from transformers import pipeline

pipe = pipeline("automatic-speech-recognition", "facebook/wav2vec2-base-960h")
def asr(mic_input):
  if "hello" in str(pipe(mic_input)): #convert to string so I can search inside
    reply = "hi"
    return reply
  else:
    return str(pipe(mic_input))
gr.Interface(fn=asr,
             inputs="mic",
             outputs="text",
             ).launch(debug=True)
```

### System Info

```shell
Colab
```

### Severity

annoyance

**Comment by FarukOzderim** [comment]
Thank you for reporting, there is a similar issue, closing this one.
#820

**Comment by shanky100** [comment]
Can someone help that how this issue was resolved for the mircophone stop recording functionality? 
Stop recording is not working when I deploy my gradio app in docker.
