### ISSUE TITLE
The Code component needs to support C source code.

### ISSUE THREAD

**Issue by luoxiangcai** [gradio-app/gradio#8584]
- [x] I have searched to see if a similar issue already exists.
I have searched and found no existing issues

**Is your feature request related to a problem? Please describe.**  
 I'm always frustrated when I have to import and read  C source code.

**Describe the solution you'd like**  
It would be great if the Code component could support C source code as seamlessly as it does for Python.

**Additional context**  
![捕获1](https://github.com/gradio-app/gradio/assets/64023870/d67ac2dc-e664-484c-9ba5-b98783262790)

**Comment by pngwn** [comment]
I agree, we should add this. Its pretty simple. I'll take care of it if no-one beats me to it.
