### ISSUE TITLE
Allow columns to be editable/uneditable independently in a single dataframe

### ISSUE THREAD

**Issue by sugam-nexusflow** [gradio-app/gradio#8614]
- [x] I have searched to see if a similar issue already exists.

**Describe the solution you'd like**  
Dataframe currently has an option to make it interactive using the `interactive` argument, making the entire table editable. Can we have an option to select what columns we want as editable? We can probably make `interactive` a list of boolean values instead of a single boolean.

**Comment by abidlabs** [comment]
Thanks @sugam-nexusflow — marking as duplicate of https://github.com/gradio-app/gradio/issues/2020
