### ISSUE TITLE
typo in doc

### ISSUE THREAD

**Issue by magical-l** [gradio-app/gradio#8621]
### Describe the bug

at page `https://www.gradio.app/guides/dynamic-apps-with-render-decorator#putting-it-together`, the example code of track-mix, line `trimmed_final = final_track[:min_shape[0], ...][:, :final_track[1], ...] if final_track.ndim > 1 else final_track[:min_shape[0]]`, 
the `[:, :final_track[1], ...]` would be `[:, :min_shape[1], ...]`?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

None

### System Info

```shell
None
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @magical-l, would you like to open a PR with the fix?

**Comment by magical-l** [comment]
@abidlabs my pleasure, but where is it? haha, I didn't spend time to find it :)

**Comment by aliabd** [comment]
@magical-l you can fix it here https://github.com/gradio-app/gradio/blob/main/demo/audio_mixer/run.py#L34 

the guide automatically references this demo
