### ISSUE TITLE
Add support `TokenClassificationPipeline` within `Interface.from_pipeline`

### ISSUE THREAD

**Issue by davidberenstein1957** [gradio-app/gradio#8628]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I wanted to use a easy out of the box pipeline for NER.

**Describe the solution you'd like**  
It seems a config like outlined here https://www.gradio.app/guides/named-entity-recognition should support this easily.

**Additional context**  
N.A.

**Comment by abidlabs** [comment]
Thanks @davidberenstein1957! Would you be interested in opening a PR for this?

**Comment by davidberenstein1957** [comment]
@abidlabs, I would but this will be in 2 weeks or so.
