### ISSUE TITLE
FileExplorer.height can be str type

### ISSUE THREAD

**Issue by magical-l** [gradio-app/gradio#8644]
### Describe the bug

`FileExplorer.height` can be str type in fact, but `str` is not in declarelation: `height: int | float | None = None`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

None

### System Info

```shell
None
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @magical-l would you like to open a PR to fix this?

**Comment by magical-l** [comment]
@abidlabs I created a pull request(edit from browser), but I cannot clone my forked repo to my local to execute the script(looks like some network issue, same with yesterday)😅
