### ISSUE TITLE
Chatbot bubble and show_copy disappeared on 4.37.1

### ISSUE THREAD

**Issue by surak** [gradio-app/gradio#8647]
### Describe the bug

The bubble around the system's answer and the copy button have disappeared between 4.36.1 and 4.37.1. See screenshots below:

This is 4.37.1

<img width="1310" alt="Screenshot 2024-06-27 at 18 33 10" src="https://github.com/gradio-app/gradio/assets/878399/65a6605c-fb4b-493c-9ca3-d24540b29d90">

And this is 4.36.1 - no other changes (other than the dependencies of gradio itself)

<img width="1319" alt="Screenshot 2024-06-27 at 18 35 20" src="https://github.com/gradio-app/gradio/assets/878399/8060edfc-e118-432c-87a4-3e890f3e9287">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
    chatbot = gr.Chatbot(
        elem_id="chatbot",
        label="This is what I have to say.... ",
        visible=True,
        height=300,
        scale=2,
        show_copy_button=True,
    )
```

### System Info

```shell
Python 3.11.8
Gradio 4.37.1 or 4.36.1 (works)
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Thanks @surak! We redesigned the `gr.Chatbot` to remove the bubble around the bot message to make longer bot messages easier to read but losing the copy buttons was not intentional! We'll work on getting this fixed

**Comment by abidlabs** [comment]
@hannahblair do you have bandwidth to take a look?

**Comment by surak** [comment]
Hi @abidlabs , removing the bubble by default is weird, as the questions are still within one. I made an a/b test with my users (30 people), and all of them either 

- complained that the website was not loading correctly (because it feels like it didn’t load the bubble), or
- It looked wrong having bubbles for questions but now answers. 

Every single one prefers the previous format.
