### ISSUE TITLE
The JS client's handle_file does not work properly in the browser

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#8650]
### Describe the bug

When accessing a file from a file input element in the browser, subsequent client predictions fail when wrapping the file with `handle_file`. If you don't wrap with `handle_file`, the prediction completes successfully.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Something like this

```js
        fileInput.addEventListener('change', function(e) {
            const file = e.target.files[0];        
            if (file) {
                const reader = new FileReader();
                reader.onload = function(event) {
                    headshot.src = event.target.result;
                    headshot.style.display = 'block';
                    generateCompliment(file);
                }
                reader.readAsDataURL(file);
            }
        });

        async function predict(file) {
            compliment.textContent = '';
            loader.style.display = 'block';

              const client_lib = await import("https://cdn.jsdelivr.net/npm/@gradio/client@1.2.0/dist/index.min.js");
              const Client = client_lib.Client;
              const handle_file = client_lib.handle_file;
              const captioning_space = await Client.connect("gokaygokay/SD3-Long-Captioner");
              const caption = await captioning_space.predict("/create_captions_rich", { image: file });

}

```

### System Info

```shell
gradio client 1.2.0
```

### Severity

I can work around it

**Comment by pngwn** [comment]
This may be semi intended as `handle_file` is node only iirc but it should at least be a no op rather than break.

**Comment by freddyaboulton** [comment]
Yes `handle_file` should not be the wrong thing to do. It's showing up everywhere (Api Docs/guides) so should work in all environments.

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/8649 (if I'm not mistaken @hannahblair)
