### ISSUE TITLE
gr.Chatbot cannot use gr.Markdown / gr.DataFrame while showing the results

### ISSUE THREAD

**Issue by sglbl** [gradio-app/gradio#8657]
- [y] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I want to use gr.DataFrame in output of chatbot.

**Describe the solution you'd like**  
Show the result of gr.DataFrame as a table inside chatbot result.

**Additional context**  
`gradio.__version__: '4.37.1'`
Code: 
```python
import gradio as gr
import time

def html_works():
   history = []
   history.append(["",None])
   text_to_show_in_chatbot = '**testing** normal md <br> <table border="1" style="width:100%"><tr><th>Label</th><th>Value</th></tr><tr><th>x</th><th>y</th></tr>'
   response = [(text_to_show_in_chatbot, None)]

   for letter in response[0][0]:
      history[-1][0] += letter
      time.sleep(0.01)
      yield history
   
   return response

def dataframe_does_not_work():
   history = []
   history.append(["",None])
   df_to_show_in_chatbot = gr.DataFrame( # gr.Markdown neither work
                              headers=["name", "age", "gender"],
                              datatype=["str", "number", "str"],
                              col_count=(3, "fixed"),
                              type='array' 
                              ## returning as an array / list of lists also okay, I can convert it to normal markdown but I also don't get any output as a list
                           )
   print(f'{type(df_to_show_in_chatbot) = }')
   response = [(df_to_show_in_chatbot, None)]
   
   for letter in response[0][0]:
      history[-1][0] += letter
      time.sleep(0.01)
      yield history
   
   return response

with gr.Blocks() as demo:
   button = gr.Button()
   chatbot = gr.Chatbot(render_markdown=True)
   # button.click(html_works, outputs = chatbot)   
   button.click(dataframe_does_not_work, outputs = chatbot)   
   
demo.queue(default_concurrency_limit=None)
demo.launch()
```

**Comment by abidlabs** [comment]
I believe `gr.Markdown` is supported but `gr.DataFrame` is not supported. @dawoodkhan82 can you confirm? Also we should have a helpful error if an unsupported component is used in the output.

**Comment by sglbl** [comment]
> I believe `gr.Markdown` is supported but `gr.DataFrame` is not supported. @dawoodkhan82 can you confirm? Also we should have a helpful error if an unsupported component is used in the output.

I get `TypeError: 'Markdown' object is not iterable`

**Comment by dawoodkhan82** [comment]
> Also we should have a helpful error if an unsupported component is used in the output.

I think we already have this, must not be working as expected.

**Comment by pngwn** [comment]
`gr.Markdown` does not work but all text is treated as markdown and should be parsed appropriately.
