### ISSUE TITLE
File file_types restricts the type of file uploaded but can be overridden

### ISSUE THREAD

**Issue by ecocarlisle** [gradio-app/gradio#8662]
- [Yes ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
When I set the file_types=['.md'] the dropdown filters out all other file types.  However, when uploading a file you can change the dropdown to include all files and this then allows you to upload any file type.

**Describe the solution you'd like**  
I'd like the file object to only allow the file type identified in the list of file_types.  User should not be able to switch to all file types as work around.

**Additional context**  
No additional context.

**Comment by abidlabs** [comment]
Will close in favor of #9098, since that has more context (cc @dawoodkhan82)
