### ISSUE TITLE
Chatbot AI message borders have disappeared as well as Like boxes

### ISSUE THREAD

**Issue by ngaudemet** [gradio-app/gradio#8666]
### Describe the bug

Thanks for the great work on gradio.

There seem to be a problem with gradio 4.37

Even if you go to the theme demo page, you can see that chatbot ai message borders have disappeared 

https://www.gradio.app/guides/theming-guide

<img width="473" alt="image" src="https://github.com/gradio-app/gradio/assets/126974970/99b03a4f-9a0d-4ad0-a795-807239fa10ba">

There is also a problem with the likes and copy buttons : 
AI likes + copy button borders are not visible
human message copy button are not visible at all

Here is an example with the basic base theme : 
<img width="1188" alt="image" src="https://github.com/gradio-app/gradio/assets/126974970/bb413349-7c45-414b-9bc2-fb5b11f427dd">
there should be borders around AI message and the AI message like box, and a like box under human message.

Also, I didn't find if any theme parameters could add the borders and the boxes back. It is very difficult to understand which theme parameters controls what in the chatbot. For instance, border_color_accent_subdued controls the color of human border messages, but where is it documented ? Which parameter to use to control the border color of AI messages ?

By the way, I think that the border of like/copy buttons should be of the same color of the messages they are under (thus different if it is a like/copy button under an AI message, or a copy button under a human message - up to now it seems it was not possible to differentiate).  

Thanks a lot

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://www.gradio.app/guides/theming-guide

you can also use the following ChatBot

gr.Chatbot(
        show_label=False,
        show_copy_button=True,
        bubble_full_width=False,
        likeable=True,
    )

### Screenshot

<img width="1188" alt="image" src="https://github.com/gradio-app/gradio/assets/126974970/e112044d-fc85-47cb-9f6f-2ba39ec47af5">

### System Info

```shell
gradio==4.37.2
```

### Severity

Blocking usage of gradio

**Comment by Stihotvor** [comment]
I have the same issue and other bugs (like `IsADirectoryError: [Errno 21] Is a directory: '/app'`)
![image](https://github.com/gradio-app/gradio/assets/22343775/309c2f57-1e1b-4d76-a5fe-e570d95e1613)

**Comment by learnasteve** [comment]
Same issue here. Would love for a fix to this! Is not usable at the moment.

**Comment by abidlabs** [comment]
Thanks folks, we are looking into it! Just to confirm, the styling change removing the borders was intentional but I believe the like buttons disappearing from under the user messages was not

**Comment by ngaudemet** [comment]
Thanks for you answer @abidlabs. 
But why would you remove the AI message bubble borders? Is it to copy chatGPT? It would be better if we could keep the borders if we want to. And without borders, it is weird to have a floating copy button or floating likes buttons.
Also : 
- the copy button disappeared from human messages (it is very useful, can you keep it?)
- it is not clear with which parameter you control the message radius and bubble size in the new styling?
- the Human message bubble size and radius size are not consistant anymore with the "in progress" bubble size and radius size (see image). 
Thanks for your help to keep the new style consistant:)

<img width="1265" alt="image" src="https://github.com/gradio-app/gradio/assets/126974970/19c93fb2-a776-449b-ad79-12459dd4e5f9">
