### ISSUE TITLE
Can you explain which library you use to read 'ply' files into a 3D model?

### ISSUE THREAD

**Issue by NTNPhim** [gradio-app/gradio#8668]
- [ ] I have searched to see if a similar issue already exists.

I couldn't find a library that helps display the 'ply' file as a 3D model like a demo. Some parameters, such as mesh or color, cannot be read. If you have any example code to read a 'ply' file, please share it. Thank you so much!

**Comment by abidlabs** [comment]
Hi @NTNPhim can you please provide a minimal code example that we can use to reproduce the issue above, including the file you are trying? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by NTNPhim** [comment]
This is my code:

'''
import open3d as o3d
import numpy as np

pcd = o3d.io.read_point_cloud("hand4.ply")
o3d.visualization.draw_geometries([pcd])
 '''
I attach picture of point cloud,
<img width="962" alt="Screenshot 2024-07-01 at 22 08 08" src="https://github.com/gradio-app/gradio/assets/104830358/8c2c024f-c8f0-4f4f-83d6-2def89f972e6">

This is link of ply file: https://drive.google.com/file/d/1bWCP87hFfWlbN3S1RdB-cxGA7W_5ANBq/view?usp=sharing
Thank you!
