### ISSUE TITLE
Host port lost on theme.css behind Nginx

### ISSUE THREAD

**Issue by ArkciaDragone** [gradio-app/gradio#8672]
### Describe the bug

# Description

When configuring the app behind Nginx, the `theme.css` file accessed in the browser does not include the port number. This results in abnormal UI loading.

![no port number](https://github.com/gradio-app/gradio/assets/41059242/628edf44-c652-43af-b3b4-38f56253412b)

> It seems the bug of missing subpaths has been fixed earlier.

# Possible workaround

Following [this suggestion](https://github.com/gradio-app/gradio/issues/8129#issuecomment-2112464483), I tried setting `proxy_set_header Host $http_host;`. Unfortunately, this only enabled version 4.20.1 to work as expected, not versions 4.21.0 or 4.37.2. However, changing both instances of `$host` to `$http_host` appeared to resolve the issue, like this:

```nginx
proxy_set_header Host $http_host;
proxy_set_header X-Forwarded-Host $http_host;
```

I'm not certain if this is the correct fix, but it worked for me. It might be helpful to update the guide with a proper configuration to save others' time. Thank you for your attention!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

## Gradio app

```python
import gradio as gr
import time

def test(x):
    time.sleep(1)
    return x

gr.Interface(test, "textbox", "textbox").queue().launch()
```

## Nginx config

The script is adapted from [the guide](https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx).

```nginx
server {
    listen 8080;

    location / {
        proxy_pass http://127.0.0.1:7860;
        proxy_buffering off;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

### System Info

```shell
- gradio 4.37.2
- nginx 1.26.1
```

### Severity

I can work around it

**Comment by Stihotvor** [comment]
I was fighting with it to fix and gave up. Right now I'm using pure guvicorn instead.

**Comment by abidlabs** [comment]
Thanks @ArkciaDragone -- we'll add this to the Guide
