### ISSUE TITLE
Error when passing in a custom chatbot to add like/dislike feature to Chatinterface

### ISSUE THREAD

**Issue by sajjadmosaheb** [gradio-app/gradio#8675]
how can I add a like/dislike function to Chatinterface?
this is possible with blocks but I can't add to a Chatinterface.

import gradio as gr

def greet(history, input):
return history + [(input, "Hello, " + input)]

def vote(data: gr.LikeData):
if data.liked:
print("You upvoted this response: " + data.value)
else:
print("You downvoted this response: " + data.value)

with gr.Blocks() as demo:
chatbot = gr.Chatbot()
textbox = gr.Textbox()
textbox.submit(greet, [chatbot, textbox], [chatbot])
chatbot.like(vote, None, None) # Adding this line causes the like/dislike icons to appear in your chatbot

demo.launch()

**Comment by abidlabs** [comment]
Hi @sajjadmosaheb to do this, you can pass in a custom `gr.Chatbot` object into the `chatbot` argument of `gr.ChatInterface` as described here: https://www.gradio.app/guides/creating-a-chatbot-fast#customizing-your-chatbot, and then attach a `.like` event to it.

**Comment by sajjadmosaheb** [comment]
Hi @abidlabs ,
but when I attach the .like() event like below I got this error:

**AttributeError: Cannot call like outside of a gradio.Blocks context.**

```
demo= gr.ChatInterface(main,
    title="test",
    css=css,
    fill_height=True,
    chatbot=gr.Chatbot(rtl=True,likeable=True).like(vote, None, None))

demo.launch() 
```

**Comment by abidlabs** [comment]
Hi @sajjadmosaheb, you'll need to put everything under a `gr.Blocks`:

```py
with gr.Blocks():
  chatbot = gr.Chatbot(rtl=True,likeable=True)
  chatbot.like(vote, None, None)
  demo= gr.ChatInterface(main,
      title="test",
      css=css,
      fill_height=True,
      chatbot=chatbot)

demo.launch() 
```

**Comment by sajjadmosaheb** [comment]
thanks @abidlabs and I appreciate your response,
now I got this error! (I even add the render=False in the first chatbot but not working)
**DuplicateBlockError: A block with id: 174 has already been rendered in the current Blocks.**

**Comment by abidlabs** [comment]
Hmm let me reopen and investigate this

**Comment by abidlabs** [comment]
For now, this should work, but looking into a better way of supporting this:

```py
import gradio as gr

with gr.Blocks() as demo:
    chatbot = gr.Chatbot(render=False)
    chatbot.like(lambda x:x, None, None)
    gr.ChatInterface(lambda x,y:x, chatbot=chatbot)

demo.launch() 
```
