### ISSUE TITLE
Improve usability of dataframe input

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#868]
**Is your feature request related to a problem? Please describe.**
See https://huggingface.co/spaces/osanseviero/accuracy_metric

Modifying the input of a cell requires double-clicking on it. I would love to be able to just click and add my input. There were also a couple of dev experience improvements I would love to see

**Describe the solution you'd like**

Three different things that would be great:
* Single click in dataframe
* Allow making the number of columns or rows fixed, since for some use cases you don't want users creating new rows.
* With using `datatype="number"`, I would love if users can only write numbers and not strings. I know this modifies what is passed to the interface, but modifying the user input type as well would be great

**Comment by abidlabs** [comment]
Thanks @osanseviero, we are discussing this as part of general discussions on making DataFrame better!
