### ISSUE TITLE
HTML component does not render in Chatbot

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#8682]
### Describe the bug

Trying out the HTML component in the chatbot with the `chatbot_core_components_simple` demo and the HTML does not render.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Run the `chatbot_core_components_simple/run.py` demo and select HTML from the radio.

All other components seem to work.

### Screenshot

<img width="1250" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/325b10cf-000f-4080-bcc1-6188165c5f21">

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.37.2
gradio_client version: 1.0.2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.110.0
ffmpy: 0.3.2
gradio-client==1.0.2 is not installed.
httpx: 0.27.0
huggingface-hub: 0.19.4
importlib-resources: 6.1.2
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.9.0
numpy: 1.26.4
orjson: 3.9.15
packaging: 23.2
pandas: 2.2.2
pillow: 10.2.0
pydantic: 2.7.1
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.10.0
urllib3: 2.0.7
uvicorn: 0.27.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.27.0
huggingface-hub: 0.19.4
packaging: 23.2
typing-extensions: 4.10.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
It does work in the `chatbot_core_components` demo so I think the problem is probably in my code for the `chatbot_core_components_simple` demo
