### ISSUE TITLE
Drop Python 3.8 and 3.9 support

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#8685]
Given that Python 3.8 is EOL-ing in October, we can drop support for this. We can also consider ending support for 3.9 but that may be too aggressive for the 5.0 release

**Comment by pngwn** [comment]
We should drop 3.9 unless there is an exceptional reason not to. 3.10 contains some really nice typing features that would allow us to clean quite a few things up.

**Comment by abidlabs** [comment]
I'm not sure if its a good idea to drop support for Python 3.9 if there's still a year left and it might make Gradio 5 unusuable for many developers without having to install a new version of Gradio. It looks like ~10% of our users currently use Python 3.9 -- which is about the same % as Python 3.8, but at least that is being EOL'd.

<img width="178" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/eedd129f-3c3e-4997-b522-bb1073d8c6d0">

As far as I can tell, there is only this place in the code place where we have to handle Python 3.9 or below explicitly is here: https://github.com/gradio-app/gradio/blob/94a1143686733c7fe16e204764b9a3e7240ccf02/gradio/route_utils.py#L823

**Comment by pngwn** [comment]
Hmm, i thought I responded to this.

While we don't explicitly handle versions elsewhere, there are definitely cases where we have multiple implementations to handle different versions. I definitely did this for the component docs. I didn't version sniff, but I did feature detection instead but it amounts to the same thing.

As an example, my `image_slider` component requires python 3.10, supporting lower version complicates the code without reason imo. I don't think asking people upgrade to a version of python that was released 3 years ago is a huge ask. As a comparison, we require node 18 in the client and that was released 1 year after python 3.10.

**Comment by abidlabs** [comment]
As a recent ex-Windows user, upgrading Python can be a major pain 😆 its not as simple as upgrading a library or even as simple as upgrading node versions. And it doesn't seem to be that rare either, a quick search on Spaces shows a decent number of Spaces that have set `python_version` to 3.9: https://huggingface.co/search/full-text?q=python_version&p=1

> As an example, my image_slider component requires python 3.10, supporting lower version complicates the code without reason imo.

If supporting Python 3.9 does indeed make the code more difficult to maintain, I'd be fine with dropping support. But I'm pretty surprised to hear that. What does Python 3.9 not support for the `image_slider` component? Does adding `from __future__ import annotations` fix it?

**Comment by pngwn** [comment]
> Does adding from __future__ import annotations fix it?

No, i've always had this in an dropped 3.9 support later. I'll double check what the issue was.

**Comment by abidlabs** [comment]
results from an informal twitter poll just for fun: https://x.com/abidlabs/status/1810321004939612295

**Comment by pngwn** [comment]
34 ppl, kill it til its dead.

**Comment by abidlabs** [comment]
Hi @pngwn I'm going to start working on this, let me know if you have examples where supporting Python 3.9 is cumbersome. If there are more than a handful, I'm okay with dropping it, but otherwise lets just keep it

**Comment by pngwn** [comment]
This code: https://github.com/pngwn/gradio-imageslider/blob/main/backend/gradio_imageslider/imageslider.py#L25-L31

Caused this error: https://github.com/pngwn/gradio-imageslider/issues/8

This comment explains that `from __future__ import annotations` doesn't fix it: https://github.com/pngwn/gradio-imageslider/issues/8#issuecomment-2190494786

**Comment by pngwn** [comment]
We also have this: https://github.com/gradio-app/gradio/blob/main/gradio/cli/commands/components/_docs_utils.py#L149-L156 which aside form being annoying, also results in less informative docs.

**Comment by abidlabs** [comment]
Ok sounds good, let's do it. We might have some users complain, but I confirmed that various cloud platforms like Spaces, Colab, Replit all use 3.10 or above by default
