### ISSUE TITLE
Is there no component specialized for inpainting in Gradio 4.x?

### ISSUE THREAD

**Issue by gibiee** [gradio-app/gradio#8692]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
- In gradio 3.x, I often used gr.Image(tool='sketch') for implementing inpainting features.
- However, it seems there is no component specialized for inpainting in Gradio 4.x.
- To implement inpainting features in Gradio 4.x, I have to use `gr.ImageEditor(brush=gr.Brush(~~~))`, which I find not very intuitive.
- Particularly, it's disappointing that I cannot see the brush area transparently.

**Describe the solution you'd like**  
- It would be great to have a component specialized for inpainting in Gradio 4.x.

**Additional context**  
- Below is a comparison between Gradio 3.x and 4.x regarding the functionality of converting mask area from RGB to BGR.
![compare](https://github.com/gradio-app/gradio/assets/37574274/242bb2f4-cb79-4986-9b9e-0908a1b83a62)

```py
# python 3.10.14 / gradio 3.50.2

import gradio as gr
from PIL import Image
import numpy as np

def rgb_to_bgr(paint) :
    image, mask = paint['image'], paint['mask'].convert('L')
    image, mask = np.array(image), np.array(mask)

    mask_bool = np.where(mask > 128, True, False)
    image[mask_bool] = image[mask_bool, ::-1]
    return Image.fromarray(image)

with gr.Blocks() as demo:
    with gr.Row():
        input_img = gr.Image(label='Input', type='pil', image_mode='RGB', source='upload', tool='sketch')

        output_img = gr.Image(label='Output', type='pil', image_mode='RGB')
    
    with gr.Row() :
        btn = gr.Button("Run", variant="primary")

    btn.click(fn=rgb_to_bgr, inputs=[input_img], outputs=[output_img])

demo.launch()
```

```py
# python 3.10.14 / gradio 4.37.2

import gradio as gr
from PIL import Image
import numpy as np

def rgb_to_bgr(paint) :
    image, mask = paint['background'], paint['layers'][0].convert('L')
    image, mask = np.array(image), np.array(mask)

    mask_bool = np.where(mask > 128, True, False)
    image[mask_bool] = image[mask_bool, ::-1]
    return Image.fromarray(image)

with gr.Blocks() as demo:
    with gr.Row():
        input_img = gr.ImageEditor(label='Input', type='pil', image_mode='RGB', sources=['upload'], layers=False,
                                   brush=gr.Brush(colors=["#AAAAAA"], color_mode="fixed"))

        output_img = gr.Image(label='Output', type='pil', image_mode='RGB')
    
    with gr.Row() :
        btn = gr.Button("Run", variant="primary")

    btn.click(fn=rgb_to_bgr, inputs=[input_img], outputs=[output_img])

demo.launch()
```

**Comment by pngwn** [comment]
Does `gr.ImageMask()` address this issue (if we fixed the opacity issue)?

**Comment by gibiee** [comment]
@pngwn 
`gr.ImageMask()` is essentially just `gr.ImageEditor(brush=Brush(colors=['#000000'], color_mode='fixed'))`, which is not the solution I am looking for. Since the brush color is black, it can be difficult to see the erased areas when inpainting dark images. Just as using a pink brush would encounter the same issue on pink images, using a fixed color brush has some risks.

**Comment by gibiee** [comment]
@pngwn 
`gr.ImageMask()` is essentially just `gr.ImageEditor(brush=Brush(colors=['#000000'], color_mode='fixed'))`, but if the opacity issue is resolved, it could be a useful component for inpainting. However, since the inpainting feature does not require layers and the mask image does not need to be RGB, I think it could be simplified further.

**Comment by pngwn** [comment]
`gr.ImageMask(layers=False)` would be pretty close i think.

**Comment by gibiee** [comment]
@pngwn 
Yes, that is currently the method I often use.
Come to think of it, if the opacity issue is resolved, controlling the brush color in RGB might be helpful. Using a bright brush color for dark images and a dark brush color for light images would make them more visible.

**Comment by abidlabs** [comment]
Since we have a dedicated issue for opacity (https://github.com/gradio-app/gradio/issues/5644), I'll go ahead and close this.
