### ISSUE TITLE
Allow radio buttons in `gr.Chatbot`

### ISSUE THREAD

**Issue by latinostats** [gradio-app/gradio#8698]
A very common pattern in chatbots is to present the user with specific options to choose from (this functionality is present in MS Copilot, see picture below)
<img src="https://github.com/gradio-app/gradio/assets/23467752/f66d48c6-3a01-499c-9d2f-2ecbcc280e63" alt="drawing" width="400"/>

Would it be possible to include a component that could include a text string and provide a group of selectable options that could be captured for backend processing within the Chatbot component?
FYI... this would help LLM RAG pipelines since these options can be very useful for metadata filtering of documents!

**Comment by abidlabs** [comment]
Related: #4763
