### ISSUE TITLE
API Docs do not support auth

### ISSUE THREAD

**Issue by omerXfaruq** [gradio-app/gradio#8700]
### Describe the bug

Hello, API docs are not aware of demo being authenticated.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr

def hello(msg):
    return f"{msg} hello"

with gr.Blocks() as app:
    txt1 = gr.Textbox()
    txt2 = gr.Textbox()
    txt1.change(hello, txt1, txt2)

app.launch(auth=("gradio", "gradio"))
```

### System Info

```shell
macos
gradio == 4.32.2
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Thanks @omerXfaruq just to confirm, you mean the Clients code needs to be updated to include `auth=`?

**Comment by omerXfaruq** [comment]
Yes, but not just for clients, also for curl. I couldn't generate curl documentation with this code snippet. But curl needs an update as well.
