### ISSUE TITLE
Add `.then` to `gr.Examples`

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#8710]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Sometimes the app requires some pre-processing tasks that happen during the interactive session with the user (e.g.: cropping an image when it's uploaded), however, when using `gr.Examples` with `cache_examples`, this should be expedited into running all the tasks that happen in the interactive session. 

**Describe the solution you'd like**  
I'd like to be able to do a `.then` or `.success` after `gr.Examples`, so that once the first `fn` runs, others run in sequence.

**Comment by abidlabs** [comment]
Thanks @apolinario agreed. I think we can just expose the caching event so that a developer could do .then, .success, cancellation, or anything else that they'd like with the event
