### ISSUE TITLE
Add imageslider component to core Gradio

### ISSUE THREAD

**Issue by innat-asj** [gradio-app/gradio#8711]
- [x] I have searched to see if a similar issue already exists. 

This was requested earlier, [here](https://github.com/gradio-app/gradio/issues/1382). However, the solutions was to use an open source implementation.

**Is your feature request related to a problem? Please describe.**  

To compare the input and transformed output image, sometimes it is better to use image-slider type component for better demonstration. 

![image](https://github.com/gradio-app/gradio/assets/81627860/e4ac890d-7f1f-440d-b165-75e68ab20476)

**Describe the solution you'd like**  

Someone has implemented this feature using gradio tools, [github-link](https://github.com/pngwn/gradio-imageslider), [demo-link](https://huggingface.co/spaces/pngwn/gradio_imageslider). However, **to keep align with ongoing gradio development, it would be better to have such feature directly from gradio.** 

**Additional context**  

Some additional request on this feature

- better UI

**Comment by pngwn** [comment]
The image slider is maintained by me, and i am also on the gradio team so I doubt this would make a big difference functionally. Although it would improve visibility.

**Comment by pngwn** [comment]
The image slider is maintained by me, and i am also on the gradio team so I doubt this would make a big difference functionally. Although it would improve visibility.

**Comment by innat-asj** [comment]
Uh, I see, didn't notice you're from core team. Would you please consider adding this component? Recently I faced this issue, and I think if having this component in core package might also open more community support/contribution.

**Comment by pngwn** [comment]
That's a fair point, I think the usecase for ImageSlider is common enough to warrant addition.

I will be going through all of the issues and fixing them up this week tho (side note).

**Comment by abidlabs** [comment]
As suggested here, it would be great to add the full screen icon for ImageSlider:
https://github.com/gradio-app/gradio/pull/8964#issuecomment-2270052604

**Comment by pngwn** [comment]
I don't think we actually want to do this really. Unless the is a really compelling reason to make it core it is better as a community component. 

There will be a new release over the next day or so and I'll try to stay on top of issues after that.
