### ISSUE TITLE
submit button for textbox just like the MultiModaltextbox.

### ISSUE THREAD

**Issue by sajjadmosaheb** [gradio-app/gradio#8727]
![button1](https://github.com/gradio-app/gradio/assets/44293911/e53acf50-f517-4841-bc02-2c17f72c1be7)

I am trying to add an icon just like this in the textbox, but I don't want to use a multimodal text box and the ability to upload files.

**Comment by freddyaboulton** [comment]
Have you tried `gr.Group` with `gr.Textbox` and `gr.Button`? The button has an `icon` parameter you can set.

**Comment by sajjadmosaheb** [comment]
Hi @freddyaboulton ,
it gives me somthing like this:
![image](https://github.com/gradio-app/gradio/assets/44293911/f810038f-ee32-4ad5-a1c7-e107b90efae2)

**Comment by freddyaboulton** [comment]
There is no way to recreate the exact multimodal textbox icon with a normal textbox. I don't think we'll implement this in core but this would be a perfect use case for custom components!

https://www.gradio.app/guides/custom-components-in-five-minutes

**Comment by sajjadmosaheb** [comment]
so what if I use a multimodal text box and the ability to hide the attachment?

**Comment by saaspeter** [comment]
> so what if I use a multimodal text box and the ability to hide the attachment?

agree, if there is a property will be great. but from the component duty, we should add a property in TextBox to show the submit button right TextBox
