### ISSUE TITLE
Gradio Client "Connection errored out" in Bun

### ISSUE THREAD

**Issue by Milkshiift** [gradio-app/gradio#8728]
### Describe the bug

Calling "predict" or "submit" functions when using bun runtime results in the "Connection errored out" error.
In Node.js, the same code behaves as expected.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```javascript
import { Client } from "@gradio/client";

const client = await Client.connect("osanseviero/mistral-super-fast");
const result = await client.predict("/chat", {
    prompt: "Hello!!",
    temperature: 0.9,
    max_new_tokens: 256,
    top_p: 0.9,
    repetition_penalty: 1.2,
});

console.log(result.data);
```

### Logs

```shell
Unexpected error Connection errored out. 
error: Connection errored out.
```

### System Info

```shell
Operating System: Linux
@gradio/client version: 1.2.1
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Since Bun aims for complete Node.js API compatibility, this sounds like an issue on Bun side? I don't think we can realistically check every JS runtime to check compatibility with gradio. wdyt @pngwn @hannahblair?

**Comment by pngwn** [comment]
Happy to accept PRs. I do think we should keep the issue open until we or someone else gets round to it. 

Bun usage is pretty low so this is a low priority issue and would be ideal for a contributor with bun experience to take on.

**Comment by Milkshiift** [comment]
Indeed, you are right.
Did some investigating and the error is thrown in [stream.ts](https://github.com/gradio-app/gradio/blob/main/client/js/src/utils/stream.ts#L78).  The full error is: `Can't find variable: TextDecoderStream`
Turns out fetch-event-stream already had an issue for the exact same error https://github.com/lukeed/fetch-event-stream/issues/5. Bun just doesn't have the API yet.
Bun's issue for TextDecoderStream https://github.com/oven-sh/bun/issues/5648

**Comment by Milkshiift** [comment]
Also, I think it would be great if errors were more verbose. This issue wouldn't even exist if the error included the easily googleable `Can't find variable: TextDecoderStream`

**Comment by pngwn** [comment]
Could you open a new issue for surfacing the correct error message? That is indeed something we are wanting to improve.

**Comment by Milkshiift** [comment]
Yup https://github.com/gradio-app/gradio/issues/8731

**Comment by abidlabs** [comment]
Thanks @Milkshiift for creating that issue, I'll go ahead and close this issue since its not actionable from our side. @pngwn feel free to reopen if you think its helpful for the js client to have it open

**Comment by Milkshiift** [comment]
As a temporary workaround, a polyfill can be used. [This one should work](https://github.com/oven-sh/bun/issues/5648#issuecomment-2143413569)

**Comment by ckq1987** [comment]
It happened in my project as well , with no hints except "Connection errored out". But now it's fixed.
In my project , I used the "mysql-connector-python==9.1.0" module to connect to MySQL , but failed to create a connection. 
And I downgraded the version of "mysql-connector-python" to 9.0.0 . Magically it workes.
