### ISSUE TITLE
Add background image for Canvas

### ISSUE THREAD

**Issue by Khoa-NT** [gradio-app/gradio#873]
**Is your feature request related to a problem? Please describe.**
When I draw a scribble on a canvas, It will be more convenient if I have a background image for reference.
The mask will be treated as a marker for running the segmentation task.

**Describe the solution you'd like**
I found the [code ](https://github.com/gradio-app/gradio/blob/f97cbbd0d7ed1d3a58b9b1ec647158a8aaf9e7c9/ui/packages/app/src/components/utils/Sketch.svelte#L280) filling the background for the canvas here. 
Can you add an option for the input background?

**Additional context**
![image](https://user-images.githubusercontent.com/12138158/160049137-658a12dd-fac5-471a-9c02-b3647415c264.png)

**Comment by abidlabs** [comment]
Hi @Khoa-NT, thanks for creating the issue! We will take a look at it soon

**Comment by abidlabs** [comment]
Yes, I definitely see the value of this! While we are super busy working on a few different issues right now, I'm hopeful we'll be able to work on this and I'll keep this issue open. In the meantime, contributions welcome!

**Comment by Khoa-NT** [comment]
I'm sorry. I didn't mean to push you guys.
I just saw the application, so I shared it in this post.
Thank you to all the team members for the hard work.

**Comment by abidlabs** [comment]
This is now possible @Khoa-NT thanks to #1621! We'll release a new version to pypi soon, here's a code snippet to get you started: https://github.com/gradio-app/gradio/blob/main/demo/blocks_mask/run.py

**Comment by ysig** [comment]
This is great! Is there however a way to store sketch information as a list so there is an ordered sequency of how input was entered rather than just being mask?
