### ISSUE TITLE
nest_asyncio causes failure to find empty port

### ISSUE THREAD

**Issue by aymeric-roucher** [gradio-app/gradio#8730]
### Describe the bug

```
import gradio as gr
import nest_asyncio
nest_asyncio.apply()

with gr.Blocks() as demo: 
    gr.Markdown("### Ok")

if __name__ == "__main__":
    demo.launch()
```

Creates error:
```
OSError: Cannot find empty port in range: 7860-7860. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.
```
The error happens with `4.29.0`, `4.33.0`, and `4.37.2`.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import nest_asyncio
nest_asyncio.apply()

with gr.Blocks() as demo: 
    gr.Markdown("### Ok")

if __name__ == "__main__":
    demo.launch()
```

### System Info

```shell
sdk_version: 4.37.2
```

### Severity

Blocking usage of gradio

**Comment by aymeric-roucher** [comment]
This error happens in Spaces, on a local setup I get `RuntimeError: There is no current event loop in thread 'Thread-14 (run)'.` instead.

**Comment by abidlabs** [comment]
Thanks @aymeric-roucher btw why do you need `nest_asyncio` on Spaces?

**Comment by aymeric-roucher** [comment]
I used it to run parallel API calls @abidlabs .
The exact same code in my Space used to work, but I don't remember the Gradio version with which it worked.

If there's a recommended alternative for parallel API calls I'd be glad to use it!

**Comment by abidlabs** [comment]
Thanks for the clarification, @aymeric-roucher! To avoid conflicts with Gradio's event loop, you could consider using the `asyncio.gather()` function for parallel API calls without nest_asyncio or use other libraries like `aiohttp` for asynchronous HTTP requests, which can help with parallelism in a more compatible way. If you have an example code snippet, happy to suggest something specific to your use case

**Comment by abidlabs** [comment]
But I also have another idea to fix this, let me try something
