### ISSUE TITLE
Demos for `gr.Plot` are broken

### ISSUE THREAD

**Issue by henryxparker** [gradio-app/gradio#8732]
### Describe the bug

Having a `matplotlib.pyplot.figure` as input to a `gr.Plot()` shows a blank plot. Even [the second example in the docs](https://www.gradio.app/docs/gradio/plot#:~:text=blocks_kinematics-,stock_forecast,-Open%20in%20%F0%9F%8E%A2%20%E2%86%97) is failing.
I believe this is related to this [old unresolved issue](https://github.com/gradio-app/gradio/issues/1871) that was closed due to inactivity

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import matplotlib.pyplot as plt
from sklearn import metrics
import numpy as np

import gradio as gr

def plot_conf_mat():
    confusion_matrix = np.array([[2, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 2, 0]])

    cm_display = metrics.ConfusionMatrixDisplay(confusion_matrix = confusion_matrix, display_labels=["Mr.", "Schmitty", "Warben", "Jaegar", "Man", "Jensen"])
    cm_display.plot(xticks_rotation=85, cmap=plt.cm.Oranges)
    figure = plt.figure()

    return figure


demo = gr.Interface(
    plot_conf_mat,
    [],
    gr.Plot(label="forecast"),
)

if __name__ == "__main__":
    demo.launch(show_error=True)

```

### Screenshot

![Screenshot 2024-07-09 at 1 42 01 PM](https://github.com/gradio-app/gradio/assets/15251412/b1e1125c-9360-4c98-a345-1ac2ede759d4)

### System Info

```shell
gradio ver 4.37.2
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @henryxparker, we'll take a look!

**Comment by abidlabs** [comment]
Hi @henryxparker I took a look at this, and I believe that `plt.figure()` is being used incorrectly here. By instantiating it after calling `cm_display.plot()`, you are generating an empty figure and returning it to gradio. If you look at the docs for https://scikit-learn.org/stable/modules/generated/sklearn.metrics.ConfusionMatrixDisplay.html, running `cm_display.plot()` binds the plot to the global `matplotlib.pyplot` module, which you can return to Gradio. So if you do this instead, your code should work:

```py
import matplotlib.pyplot as plt
from sklearn import metrics
import numpy as np

import gradio as gr

def plot_conf_mat():
    confusion_matrix = np.array([[2, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 2, 0]])

    cm_display = metrics.ConfusionMatrixDisplay(confusion_matrix = confusion_matrix, display_labels=["Mr.", "Schmitty", "Warben", "Jaegar", "Man", "Jensen"])
    cm_display.plot(xticks_rotation=85, cmap=plt.cm.Oranges)
    return plt


demo = gr.Interface(
    plot_conf_mat,
    [],
    gr.Plot(label="forecast"),
)

if __name__ == "__main__":
    demo.launch(show_error=True)

```

**Comment by henryxparker** [comment]
Thanks! I apologize for my ignorance

**Comment by henryxparker** [comment]
That demo is still broken though

**Comment by abidlabs** [comment]
cc @aliabd on the demo
