### ISSUE TITLE
About Gradio List

### ISSUE THREAD

**Issue by Siraj-Bhai** [gradio-app/gradio#8739]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Need to display list of Items with two columns. How to accomplish this ?

**Comment by abidlabs** [comment]
For general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
