### ISSUE TITLE
Exception in custom component templating from MultimodalTextbox

### ISSUE THREAD

**Issue by HwwwwwwwH** [gradio-app/gradio#8747]
### Describe the bug

I want to create a custom component from MultimodalTextbox. Following the guide, I ran:
```shell
gradio cc create MyComponent --template MultimodalTextbox
```
and I got an error of `No such file or directory` of `multimodaltextbox.py`. I checked the components directory under gradio packages, the name is `multimodal_textbox.py`. **So it seems that this file should be renamed to `multimodaltextbox.py`.**

After that, I can create a dev directory successfully. But When I ran
```shell
gradio cc dev
```
and open the web link. I got another error. The issue #8661 seems has the same problem with me...
![image](https://github.com/gradio-app/gradio/assets/52458637/aff003ed-c6ef-447a-a7c3-723f18b4ec6a)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```shell
gradio cc create MyComponent --template MultimodalTextbox

gradio cc dev
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.37.2
gradio_client version: 1.0.2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.3.0
fastapi: 0.110.1
ffmpy: 0.3.2
gradio-client==1.0.2 is not installed.
httpx: 0.27.0
huggingface-hub: 0.22.2
importlib-resources: 6.4.0
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.4
numpy: 1.26.4
orjson: 3.10.1
packaging: 24.0
pandas: 2.2.2
pillow: 10.1.0
pydantic: 2.7.0
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.5.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.10.0
urllib3: 2.2.1
uvicorn: 0.29.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.3.1
httpx: 0.27.0
huggingface-hub: 0.22.2
packaging: 24.0
typing-extensions: 4.10.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @HwwwwwwwH ! Yes the multimodal textbox issue has been fixed in #8719 and the issue with dev mode is tracked in #8661 so I will close this since it's a duplicate.

We'll have a fix soon 🤞
