### ISSUE TITLE
Add a way to more intuitively show and hide output cells

### ISSUE THREAD

**Issue by balaji-ramk** [gradio-app/gradio#8753]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Currently, there isn't an intuitive way to hide output cells before a button is pressed, but then show them after it is pressed for progress indication. So either have to choose having a cluttered UI (if showing all cells), no progress indication, or writing some messy code to do something similar.

Some code that I use to emulate what I want:
```py
import gradio as gr
import time

def add_two_numbers(num1, num2):
    time.sleep(5)
    return int(num1) + int(num2)

def show_outputs():
    return gr.update(visible=True)

with gr.Blocks() as demo:
    with gr.Row():
        num1 = gr.Textbox()
        num2 = gr.Textbox()
    
    result = gr.Textbox(visible=False, interactive=False)
    
    result_btn = gr.Button("Add")
    result_btn.click(
        fn=show_outputs,
        outputs=[result]
    )
    result_btn.click(
        fn=add_two_numbers,
        inputs=[num1, num2],
        outputs=[result]
    )
demo.launch()
```

**Describe the solution you'd like**  
Would love it if we could specify a parameter like output_cell=True for each object, and then within the gr.Blocks(), we could handle how to handle output_cells (show, hide, show_after_button_press).

**Additional context**  
None.

**Comment by abidlabs** [comment]
Hi @balaji-ramk thanks for the suggestion! We've recently added `gr.render`, which offers a way to build dynamic apps and is a more flexible API, please take a look here: https://www.gradio.app/guides/dynamic-apps-with-render-decorator

**Comment by balaji-ramk** [comment]
Hi, thanks a ton, this looks very useful, and I'll definitely try it out!
Also thanks for taking the time to reply!

**Comment by balaji-ramk** [comment]
Hi @abidlabs  I think I forgot to mention so don't know if you received a notification for this,

Sorry if this is spam, I'm not too sure how GitHub Issues work

**Comment by abidlabs** [comment]
Thanks for following up @balaji-ramk --

> PS after snooping throught the documentation and trying it out a bit, I've found that there isn't a way to store the outputs of this render block into a specific variable that can be used in future functions, see the below code:

It is possible to use the rendered components directly in event triggers, as long as the events are defined _inside_ of the render block. Here's an example:

```py
import gradio as gr

with gr.Blocks() as demo:
    text_count = gr.State(1)
    add_btn = gr.Button("Add Box")
    add_btn.click(lambda x: x + 1, text_count, text_count)

    @gr.render(inputs=text_count)
    def render_count(count):
        boxes = []
        for i in range(count):
            box = gr.Textbox(key=i, label=f"Box {i}")
            boxes.append(box)

        def merge(*args):
            return " ".join(args)
        
        merge_btn.click(merge, boxes, output)


    merge_btn = gr.Button("Merge")
    output = gr.Textbox(label="Merged Output")

demo.launch()
```
