### ISSUE TITLE
Forward custom authentication mechanism to httpx

### ISSUE THREAD

**Issue by valgai** [gradio-app/gradio#8754]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
We deployed a Gradio app behind a proxy which requires Kerberos authentication. When accessing the app from the browser, there is no problem, but the trouble begins when using the API with `gradio_client`. There is currently, AFAIK, no way to forward custom authentication mechanism to `httpx` such as [httpx_kerberos](https://github.com/hyprxa/httpx_kerberos) or [httpx-negotiate-sspi](https://github.com/rob-blackbourn/httpx-negotiate-sspi).

**Describe the solution you'd like**  
I wish the `gradio_client.client.Client` constructor would accept an authentication mechanism that would be forwarded to `httpx` calls.

**Additional context**
I wrote a minimal implementation here : c4622ea05. It works well for our usecases, but I don't know about the edge cases.

Thanks for your help !

**Comment by abidlabs** [comment]
Hi @valgai yes we could add this. Would you be able to open a PR with your work so far and we can review it and modify it as needed?

**Comment by valgai** [comment]
Of course, I just created one.
