### ISSUE TITLE
an image select component

### ISSUE THREAD

**Issue by wow-ww** [gradio-app/gradio#8760]
Hi!
I want to make an image select component.selected the image,also selected multiple images.
Like this project.This is an image select component with streamlit.
https://image-select.streamlit.app/
I don't know how to make it with sevelt.I learn Vue.Also I know html,css and js.
Other ideas?

**Comment by abidlabs** [comment]
Hi @wow-ww the Gradio `Gallery` component supports image selection. You can see an [example here](https://www.gradio.app/playground?demo=Hello_World&code=aW1wb3J0IGdyYWRpbyBhcyBncgppbXBvcnQgbnVtcHkgYXMgbnAKCndpdGggZ3IuQmxvY2tzKCkgYXMgZGVtbzoKICAgIGltZ3MgPSBnci5TdGF0ZSgpCiAgICBnYWxsZXJ5ID0gZ3IuR2FsbGVyeShhbGxvd19wcmV2aWV3PUZhbHNlKQoKICAgIGRlZiBkZXNlbGVjdF9pbWFnZXMoKToKICAgICAgICByZXR1cm4gZ3IuR2FsbGVyeShzZWxlY3RlZF9pbmRleD1Ob25lKQoKICAgIGRlZiBnZW5lcmF0ZV9pbWFnZXMoKToKICAgICAgICBpbWFnZXMgPSBbXQogICAgICAgIGZvciBfIGluIHJhbmdlKDkpOgogICAgICAgICAgICBpbWFnZSA9IG5wLm9uZXMoKDEwMCwgMTAwLCAzKSwgZHR5cGU9bnAudWludDgpICogbnAucmFuZG9tLnJhbmRpbnQoCiAgICAgICAgICAgICAgICAwLCAyNTUsIDMKICAgICAgICAgICAgKSAgIyBpbWFnZSBpcyBhIHNvbGlkIHNpbmdsZSBjb2xvcgogICAgICAgICAgICBpbWFnZXMuYXBwZW5kKGltYWdlKQogICAgICAgIHJldHVybiBpbWFnZXMsIGltYWdlcwoKICAgIGRlbW8ubG9hZChnZW5lcmF0ZV9pbWFnZXMsIE5vbmUsIFtnYWxsZXJ5LCBpbWdzXSkKCiAgICB3aXRoIGdyLlJvdygpOgogICAgICAgIHNlbGVjdGVkID0gZ3IuTnVtYmVyKHNob3dfbGFiZWw9RmFsc2UpCiAgICAgICAgZGFya2VuX2J0biA9IGdyLkJ1dHRvbigiRGFya2VuIHNlbGVjdGVkIikKICAgIGRlc2VsZWN0X2J1dHRvbiA9IGdyLkJ1dHRvbigiRGVzZWxlY3QiKQoKICAgIGRlc2VsZWN0X2J1dHRvbi5jbGljayhkZXNlbGVjdF9pbWFnZXMsIE5vbmUsIGdhbGxlcnkpCgogICAgZGVmIGdldF9zZWxlY3RfaW5kZXgoZXZ0OiBnci5TZWxlY3REYXRhKToKICAgICAgICByZXR1cm4gZXZ0LmluZGV4CgogICAgZ2FsbGVyeS5zZWxlY3QoZ2V0X3NlbGVjdF9pbmRleCwgTm9uZSwgc2VsZWN0ZWQpCgogICAgZGVmIGRhcmtlbl9pbWcoaW1ncywgaW5kZXgpOgogICAgICAgIGluZGV4ID0gaW50KGluZGV4KQogICAgICAgIGltZ3NbaW5kZXhdID0gbnAucm91bmQoaW1nc1tpbmRleF0gKiAwLjgpLmFzdHlwZShucC51aW50OCkKICAgICAgICByZXR1cm4gaW1ncywgaW1ncwoKICAgIGRhcmtlbl9idG4uY2xpY2soZGFya2VuX2ltZywgW2ltZ3MsIHNlbGVjdGVkXSwgW2ltZ3MsIGdhbGxlcnldKQoKaWYgX19uYW1lX18gPT0gIl9fbWFpbl9fIjoKICAgIGRlbW8ubGF1bmNoKCk=)
