### ISSUE TITLE
Unenable to use SadTalker Gradio WebUI on Kaggle

### ISSUE THREAD

**Issue by HebatullahHesham** [gradio-app/gradio#8765]
### Describe the bug

Please How to use SadTalker gradio WebUI on kaggle notebook by connecting it with Ngrok? Is Kaggle have banned using WebUIs directly?

Please, I need help. Here is the code I run on cells for using SadTalker on Kaggle that doesn't lead me to use the WebUI:

1. !git clone https://github.com/vinthony/SadTalker.git
2. %cd SadTalker
3. !pip install -r requirements.txt
4. !bash scripts/download_models.sh
5. !bash webui.sh

It always appears to be the same issue again and again, even if I try to install, upgrade, or downgrade a specific Gradio version.

File "app_sadtalker.py", line 35, in sadtalker_demo
with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

I have solved this issue on my local device by installing the required Python version, which was 3.10.6, uninstalling other versions on my device, and making sure to delete the remaining corrupted files from the older version so it can be fixed if there is a conflict with the other version.

I really appreciate your help because I have asked ChatGPT, and it was absolutely dumb.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

``File "app_sadtalker.py", line 35, in sadtalker_demo
with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'
```


### Screenshot

_No response_

### Logs

_No response_

### System Info

```shell
Kaggle
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @HebatullahHesham it looks like SadTalker was built using an older version of gradio. When you install gradio with the requirements.txt, it will use the newest version of Gradio, which no longer uses .style(). I would recommend installing an older version -- you can contact the author of that repo to ask which version of gradio is supported or try manually until you find one that works. I would suggest starting with 

```
!pip install gradio==3.50.2
```

**Comment by HebatullahHesham** [comment]
> Hi @HebatullahHesham it looks like SadTalker was built using an older version of gradio. When you install gradio with the requirements.txt, it will use the newest version of Gradio, which no longer uses .style(). I would recommend installing an older version -- you can contact the author of that repo to ask which version of gradio is supported or try manually until you find one that works. I would suggest starting with
> 
> ```
> !pip install gradio==3.50.2
> ```

Is this Specific will help to run the Gradio SadTalker Webui on kaggle?

**Comment by HebatullahHesham** [comment]
> Hi @HebatullahHesham it looks like SadTalker was built using an older version of gradio. When you install gradio with the requirements.txt, it will use the newest version of Gradio, which no longer uses .style(). I would recommend installing an older version -- you can contact the author of that repo to ask which version of gradio is supported or try manually until you find one that works. I would suggest starting with
> 
> ```
> !pip install gradio==3.50.2
> ```

Is this the list of gradio versions?

https://www.gradio.app/changelog
