### ISSUE TITLE
`Markdown` support in `Code` component

### ISSUE THREAD

**Issue by qgallouedec** [gradio-app/gradio#8768]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
When you use bibtex in a block of code, you can't have syntax highlighting.

**Describe the solution you'd like**  
Bibtex to be supported by the code component

exemple:

```bib
@book{sweig42,
	title        = {The impossible book},
	author       = {Stefa{n} Sweig},
	year         = 1942,
	month        = mar,
	publisher    = {Dead Poet Society}
}
@article{steward03,
	title        = {Cooking behind bars},
	author       = {Martha Steward},
	year         = 2003,
	publisher    = {Culinary Expert Series}
}
@book{impossible,
	title        = {The impossible book},
	author       = {Stefan Sweig},
	year         = 1942,
	month        = mar,
	publisher    = {Dead Poet Society}
}
```

**Comment by abidlabs** [comment]
Hi @qgallouedec is the BibTex part of a larger block of Markdown? Can you use the Markdown component for this or do you need to interactively edit the Markdown?

**Comment by qgallouedec** [comment]
It needs to be editable.

**Comment by abidlabs** [comment]
is the BibTex part of a larger block of Markdown?

**Comment by qgallouedec** [comment]
No, it's basically 

```python
import gradio as gr

with gr.Blocks() as demo:
    code = gr.Code()
    button = gr.Button("Clean BibTeX")
    button.click(clean_bibtex, code, code)
demo.launch()
```

**Comment by abidlabs** [comment]
Sure, ok BibTex isn't a language but we could add support for Markdown

**Comment by qgallouedec** [comment]
I might not have explained my point clearly, let me precise. Ideally, I'd like to be able to run this:

```python
import gradio as gr

with gr.Blocks() as demo:
    gr.Code(language="bib")

demo.launch()
```

and get something like this: (the image is a patchwork):

![Screenshot 2024-07-13 at 14 48 06](https://github.com/user-attachments/assets/f6b9e9e6-2c03-4e8b-b188-5d519a6ba23a)

**Comment by abidlabs** [comment]
Ah sorry I miswrote, I was thinking latex not markdown as bibtex is specifically latex syntax. Unfortunately, latex is not supported by codemirror (https://codemirror.net/6/mode/), which we use in our code component so this is something we will not be able to support with syntax highlighting

**Comment by qgallouedec** [comment]
Thanks for the answer. Reverting the title change for better reference
