### ISSUE TITLE
Add a `File.download()` event

### ISSUE THREAD

**Issue by ngaudemet** [gradio-app/gradio#8772]
### Describe the bug

Thanks for the great job on gradio. The new Chatbot experience of 4.38 seems great.

However I can't upgrade (I'm still on gradio 4.29) since File.select doesn't work anymore.

I believe the bug was introduced in gradio 4.34 when you introduces file.delete in "add delete event to File component #8417".

When you click on a file to download it, it shoud launch a select event as it did before.
It is sometimes crucial to know in the back end what file the user tries to download.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr

with gr.Blocks() as demo:
    file = gr.File(value="graph.png")
    files = gr.File(value=["graph.png", "graph.png"], file_count="multiple")
    statement = gr.Textbox(value="No file selected.")

    def on_select(value, evt: gr.EventData):
        return f"The {evt.target} component was selected, and its value was {value}."

    file.select(on_select, file, statement)
    files.select(on_select, file, statement)
demo.launch()
```

### Screenshot

in gradio 4.38.1 (not working)
<img width="1290" alt="image" src="https://github.com/user-attachments/assets/67c385de-ce38-4e4e-8bcb-7dd7cb6dbd3f">

in gradio 4.29.0 (working)
<img width="1297" alt="image" src="https://github.com/user-attachments/assets/03c3733c-60af-4e9c-822f-219f01a973fd">

### Logs

```shell
no logs
```

### System Info

```shell
doesn't work on gradio 4.38.1
worked very well on gradio 4.29.0, seems to be broken since gradio 4.34.0
```

### Severity

Blocking usage of gradio

**Comment by pngwn** [comment]
This was a bug sadly, so we can bring that behaviour back. 

Would an additional download event work?

**Comment by ngaudemet** [comment]
It was not a bug at all according me. And the select event is still documented in File docs. 
But yes, a download event or a select event would work. 
thanks!

**Comment by pngwn** [comment]
Actually ignore what I said. The select event should indeed fire. 

Will see what we can do!

**Comment by ngaudemet** [comment]
Hello @pngwn how are you? Have you any news about this issue? Thanks a lot !

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/9887
