### ISSUE TITLE
Incorrect LaTeX formula display in gr.chatbot and gr.ChatInterface

### ISSUE THREAD

**Issue by MrCool1981** [gradio-app/gradio#8780]
### Describe the bug

A valid KaTeX expression:

```a_w = \frac{\text{moles}_{\text{water}}}{\text{moles}_{\text{water}} + \text{moles}_{\text{solute}}}```

is successfully rendered using KaTeX tool: https://katex.org/

However, it is not displayed properly in gr.chatbot and gr.ChatInterface when wrapped in double $$:

```$$a_w = \frac{\text{moles}_{\text{water}}}{\text{moles}_{\text{water}} + \text{moles}{\text{solute}}}$$```

Once, the underscores are removed from denominator, the formula is displayed correctly:

```$$a_w = \frac{\text{moles}_{\text{water}}}{\text{moles}{\text{water}} + \text{moles}{\text{solute}}}$$```

The subscript text in the denominator is displayed correctly when "\text" tag is removed:

```$$aw = \frac{moles_{water}}{moles_{water} + moles_{solute}}$$```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import random
import gradio as gr

def random_response(message, history):
    return random.choice(["Yes", "No"])

demo = gr.ChatInterface(random_response)

if __name__ == "__main__":
    demo.launch()
```

### Screenshot

![image](https://github.com/user-attachments/assets/0c055501-8a58-4d8b-8cf9-b863b193494c)
![image](https://github.com/user-attachments/assets/a3d222ca-cfbe-4753-abf7-e5bab12c5fbb)

### System Info

```shell
gradio==4.31.5
Python 3.12.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks for opening this issue @MrCool1981! Cc @dawoodkhan82

**Comment by dawoodkhan82** [comment]
Must be an issue with how we are parsing markdown. Will take a look.
