### ISSUE TITLE
Ability to move tabs

### ISSUE THREAD

**Issue by Bebra777228** [gradio-app/gradio#8785]
How do you like the idea of making tabs movable? For example, you can place the main tabs where the main work is performed on the left, and the "Settings" tab on the right. It would also be convenient to be able to place tabs in the center instead of just on one edge. If this is possible now, then it would be interesting to know how it can be implemented.

**Comment by abidlabs** [comment]
Thanks @Bebra777228. We haven’t really considered this, could be interesting to provide support for this. We are actually in the process of redesigning our tabs — would you be able to add your suggestion to this issue instead? https://github.com/gradio-app/gradio/issues/8787
