### ISSUE TITLE
Remove use of emojis 👻 

### ISSUE THREAD

**Issue by hannahblair** [gradio-app/gradio#8786]
**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by freddyaboulton** [comment]
😨

**Comment by abidlabs** [comment]
We could expand the set of icons that are included in gradio, could be useful for custom components

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/9201
