### ISSUE TITLE
Dataframe refresh

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#8790]
- [x] I have searched to see if a similar issue already exists.

In order to address some of the limitations of the dataframe we need to tweak the design to accommodate certain features.

I did a picture.

![Drawing](https://github.com/user-attachments/assets/587b1b62-d0f3-4efb-93d8-3b40795f004b)

**Comment by pngwn** [comment]
Will add some more detail about the specific requests.

**Comment by abidlabs** [comment]
We should add support for deleting columns / rows in the context menus that pop up

**Comment by pngwn** [comment]
> 👍👍. Nit: we should add support for deleting columns / rows in the context menus that pop up

Yep! Forgot that one (and perhaps others) as I was working from memory. This general approach should provide us with some more space to those things.

**Comment by dwipper** [comment]
Here's an example of what my UI designer would like. It's pretty standard from a CRUD perspective. Ideally the menu options would pop open a modal to complete the action:
![image](https://github.com/user-attachments/assets/6e103e2d-82f7-4de6-99e4-c7cf97a07bae)

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/9575
