### ISSUE TITLE
Gradio Demo and FastAPI Docs are executed simultaneously despite having the queue set up.

### ISSUE THREAD

**Issue by gibiee** [gradio-app/gradio#8792]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
- When sending requests simultaneously from both the Gradio demo and FastAPI docs, the requests are executed concurrently without waiting in the queue.
- This can be problematic, especially when using deep learning models that utilize GPUs. In the code below, the deep learning model execution stopped with an error.
- If executed only from the demo or only from the docs, the requests are correctly queued.
- Are the demo and docs using separate queues?
- Is there a way to apply the `gradio.queue()` setting to the FastAPI docs as well? Or are there any plans for an update?

**Describe the solution you'd like**  
- A method to apply the `gradio.queue()` setting to FastAPI docs as well.

**Additional context**  
![demo_and_docs](https://github.com/user-attachments/assets/fe4e8b63-f4fd-45c4-9b55-30551ef92142)
```sh
Python 3.10.14
gradio==4.38.1
fastapi==0.111.1
uvicorn==0.30.1
```
```python
import gradio as gr
import torch
from diffusers import StableDiffusionXLPipeline
from fastapi import FastAPI
from fastapi.responses import Response
import uvicorn
import img64

app = FastAPI()

pipe = StableDiffusionXLPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16)
pipe = pipe.to("cuda")

def generate_by_sdxl(prompt) :
    image = pipe(prompt).images[0]
    return image

@app.get("/generate/{prompt}")
def api_generate_by_sdxl(prompt: str) :
    image = generate_by_sdxl(prompt)
    return Response(content=img64.image_to_bytes(image), media_type="image/png")

with gr.Blocks() as demo :
    with gr.Row():
        input_text = gr.Textbox(label='Input', placeholder="What you want to generate")
        output_img = gr.Image(label='Output')
    
    btn = gr.Button('Generate', variant='primary')
    btn.click(fn=generate_by_sdxl, inputs=input_text, outputs=output_img)

demo.queue(default_concurrency_limit=1)
app = gr.mount_gradio_app(app, demo, path="/gradio")
uvicorn.run(app, host='localhost', port=7777, workers=1)
```

**Comment by abidlabs** [comment]
Very interesting, thanks for pointing this out @gibiee. So the FastAPI docs call the API endpoints directly, which means they skip the Gradio queue altogether. There isn't really a way for us to set up a queue for the FastAPI docs, so I would suggest not using the FastAPI docs, and instead use the "view API" docs in the footer of your Gradio app. You'll notice that these docs use the Python (or JS) Client, which respect the Gradio queue, and so you won't see this error. Thanks!
