### ISSUE TITLE
gr.DateTime documentation issue <- duplicated TextBox, not DateTime. 

### ISSUE THREAD

**Issue by robwsinnott** [gradio-app/gradio#8793]
### Describe the bug

https://www.gradio.app/docs/gradio/datetime <- still appears to be the textBox documentation for the most part 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://www.gradio.app/docs/gradio/datetime

### Screenshot

https://www.gradio.app/docs/gradio/datetime

### System Info

```shell
Not Relevant - on Website gradio.app -> https://www.gradio.app/docs/gradio/datetime
```

### Severity

I can work around it

**Comment by aliabid94** [comment]
fixing, thanks for pointing it out!

**Comment by robwsinnott** [comment]
I’d love to help out with your upcoming pdf annotation component!  I’m
building one now, but assume you all have one in motion too?

**Comment by abidlabs** [comment]
> I’d love to help out with your upcoming pdf annotation component!  I’m building one now, but assume you all have one in motion too?

We don't have a specific component to annotate pdfs on the roadmap. Are you building a custom component? Happy to try it out and share it on our socials (if you are interested)
