### ISSUE TITLE
SSR

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#8795]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

It would be great if gradio were a viable option for full websites. At the minute many people are probably put off a little due to gradio being an SPA. 

**Describe the solution you'd like**  

SSR gradio. 

**Additional context**  

We have the technology.

**Steps**

- [x] Initial refactor to facilitate SSR, splitting `@gradio/app` up (will be nice for lite too).
- [x] Initial sveltekit boilerplate
- [x] #9111
- [x] #9112
- [ ] #9113
- [ ] #9114

**Comment by dwipper** [comment]
@pngwn Not that you asked :-) but I think the market is really going towards AI enabled applications. Whether that means SSA or SSR is maybe besides the point? Gradio has been great at allowing people to quickly creating chatbot and other AI first applications. Definitely cool stuff, but a majority of my Gradio development time has been creating non-chatbot UIs, layout design, and basic database CRUD functions. IMHO making that easier/faster would be a big win.

**Comment by pngwn** [comment]
> Definitely cool stuff, but a majority of my Gradio development time has been creating non-chatbot UIs, layout design, and basic database CRUD functions. IMHO making that easier/faster would be a big win.

This is definitely something we would like to do! But this is a different issue. One of the challenges with gradio is that it doesn't produce a web app or site that offers the same performance and SEO profile as a 'real' website. This feature would change that, meaning Gradio would be comes a valid platform on which to build a full product, without this capability people will be reluctant to build anything others than simple AI demo/ widgets, making the impact if more complex integrations much smaller.

If you have specific examples of things you wish were easier (DB integrations, Vector DBs, Auth, etc) then please open a new issue, we would love to discuss it further!

**Comment by dwipper** [comment]
@pngwn Totally agree. From an SEO perspective, I did open this issue around meta tags: https://github.com/gradio-app/gradio/issues/8891
