### ISSUE TITLE
Markdown latex bmatrix wrapped error

### ISSUE THREAD

**Issue by yz4322gly** [gradio-app/gradio#8800]
### Describe the bug

The matrix here cannot be correctly wrapped, 
look like: [0​1​0 1​−4​1 0​1​0​]

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
gr.Markdown("""
        ## 边缘检测:laplacian
        Laplacian算子是一种二阶微分算子，它通过对图像进行二次微分操作来检测边缘。  
        Laplacian算子能够捕捉到图像中灰度变化的二阶导数峰值，从而定位边缘。  
        然而，Laplacian算子对噪声敏感，因为它会增强图像中的高频部分，包括噪声。  
        $$
        \\begin{bmatrix}
        0 & 1 & 0 \\\\
        1 & -4 & 1 \\\\
        0 & 1 & 0
        \\end{bmatrix}
        $$
        """)
with gr.Row():
    x_alpha = gr.Slider(0, 1, step=0.01, value=0.5, label="x_alpha", info="x混合比例")
    y_alpha = gr.Slider(0, 1, step=0.01, value=0.5, label="y_alpha", info="y混合比例")
    laplacian_btn = gr.Button(scale=1, value="边缘检测:laplacian")
    laplacian_btn.click(fn=handle_wrapper(cv2_laplacian), inputs=[show_image, x_alpha, y_alpha], outputs=[show_image, his_textbox])

```

### Screenshot

![图片](https://github.com/user-attachments/assets/f7262687-9d78-4e39-bd8f-8b6cea3caa0c)

### System Info

```shell
gardio-4.37.2
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
This is now fixed in the latest version of `gradio==4.39`:

<img width="662" alt="image" src="https://github.com/user-attachments/assets/191a545e-b607-45ea-83ad-df0708470557">
