### ISSUE TITLE
MultimodalTextbox - file_types seems not to be working?

### ISSUE THREAD

**Issue by skye0402** [gradio-app/gradio#8801]
### Describe the bug

I'm using the `MultimodalTextbox` but found that users upload PDF files to it, which makes no sense for my case. The setting for `file_types=` is on "images" but seems to have no effect. I would expect that you can't upload such files, but e.g. `.pdf` or `.pptx` works. Similar behaviour like it is for the upload button and such would be appreciated.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
from gradio.blocks import Blocks


def test()->Blocks:
    with gr.Blocks() as test:
        with gr.Row(elem_id="input_row") as input_row:
            msg_box = gr.MultimodalTextbox(
                interactive=True, 
                file_types=["images"],
                file_count="multiple",
                scale=9,
                elem_id="msg_box",
                show_label=False,
                max_lines=5,
                placeholder="Enter text or images and text and press ENTER",
                container=False,
                info="This is just some info",
                autofocus=True
            )
    return test

blocks = test()
blocks.launch()
    

```

### System Info

```shell
Linux
Gradio Version: 4.38.1
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Cc @dawoodkhan82 i think it makes sense to refactor the logic in the frontend so it’s shared across all file components as we’ve heard various issues like this

**Comment by peilongchencc** [comment]
I encountered the same issue and look forward to a solution.🥹

**Comment by zm0n3** [comment]
This is still present in version 4.42.0.

**Comment by Rijgersberg** [comment]
Same problem when using the `MultimodalTextbox` in a `ChatInterface`

**Comment by freddyaboulton** [comment]
This sounds like the same problem as  https://github.com/gradio-app/gradio/issues/9098 ?

Are you all using windows?

**Comment by skye0402** [comment]
> This sounds like the same problem as #9098 ?
> 
> Are you all using windows?

Windows as OS to access Gradio, Linux running Gradio.

**Comment by abidlabs** [comment]
@freddyaboulton this is not the same as the windows issue. The windows issue prevented users from being able to remove the default file type filter (e.g. from "images" to "all files" -- which requires a fix in the backend to prevent users from being able to submit invalid files). In this case for MultimodalTextbox, the file type filter was not working at all, but its been fixed by @dawoodkhan82 in https://github.com/gradio-app/gradio/pull/9393

**Comment by dawoodkhan82** [comment]
@skye0402 Your example demo should work as expected now. Just note that you need to provide `image` not `images` in the `file_type`
