### ISSUE TITLE
Add option to loop audio component when it is played

### ISSUE THREAD

**Issue by nateraw** [gradio-app/gradio#8805]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
It would be nice to have an option for the audio component to loop when its played. I have audio that I need to listen carefully to, and it would help if it looped for me so I don't have to keep hitting play.

**Describe the solution you'd like**  
Perhaps by setting `loop=True` in the `Audio` constructor, it sets up the audio component to loop when played. When stopped, it'll either reset to start of sample or stop inplace (I don't have a preference).

**Additional context**  
it seems there's a similar issue for video here: https://github.com/gradio-app/gradio/issues/7689

**Comment by abidlabs** [comment]
Thanks @nateraw! Makes sense
