### ISSUE TITLE
Gradio embedded in Static HTML cannot cp to clipboard 

### ISSUE THREAD

**Issue by Muennighoff** [gradio-app/gradio#8811]
### Describe the bug

E.g. in this arena https://huggingface.co/spaces/WildVision/vision-arena if you hit a random sample and then try to cp the model response via the copy icon it does not work. However if you access the gradio space directly in the browser (link is in the index.html) then the copying works fine.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Enter some text on https://huggingface.co/spaces/WildVision/vision-arena & try to use the copy to clipboard button

### System Info

```shell
latest
```

### Severity

I can work around it

**Comment by pngwn** [comment]
Probably related to iFrame permissions.

**Comment by abidlabs** [comment]
Yes, this is not related to gradio per se, but rather to the permissions granted to the iframe. Something like this might help:

```
<iframe 
  src="..." 
  width="100%" 
  height="800" 
  allow="clipboard-write"
  sandbox="allow-scripts allow-same-origin allow-popups">
</iframe>
```
