### ISSUE TITLE
No response when using gr.image in chatinterface in second round

### ISSUE THREAD

**Issue by tyc333** [gradio-app/gradio#8812]
### Describe the bug

If I use gr.image or other components as chatbot response in chatinterface, it will just work at the first time, but not work any more then. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr


def echo(message, history):
    return gr.Image(
            "https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png"
        )


demo = gr.ChatInterface(
    fn=echo,
    title="Echo Bot",
)
demo.launch()
```

### Screenshot

![image](https://github.com/user-attachments/assets/f5bdec44-6d8e-48b6-a892-b62fa8547f9d)

### System Info

```shell
gradio 4.38
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @tyc333 I can repro. We'll take a look at this as soon as we can!
