### ISSUE TITLE
Uncaught (in promise) DOMException: Could not start video source

### ISSUE THREAD

**Issue by O-O1024** [gradio-app/gradio#8814]
### Describe the bug

This error disturbs me so long. I find the problem is from OBS virtural camera.
Why gradio choose OBS instand of WebCam as camera source ?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Install OBS virtual camera, and then use Image or Video component, access webcam

### System Info

```shell
windows 10
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @O-O1024, I think we use whatever source is set to default on your machine, but you can change the source of the webcam by selecting the appropriate source from the dropdown of the component:

<img width="757" alt="image" src="https://github.com/user-attachments/assets/982cfbf2-754b-4400-8842-63ba97ab6903">

Please let me know if this does not work for you
