### ISSUE TITLE
Dataframe change event not triggered for header modification

### ISSUE THREAD

**Issue by shreyanmitra** [gradio-app/gradio#8824]
### Describe the bug

Manually changing the header of the dataframe does not seem to trigger the change() event listener

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
#Minimum repro
import gradio as gr
def updateHeader(file):
    return gr.Dropdown(label="Feature", value = list(file.columns)[0], choices = list(file.columns), interactive = True, info="Choose a feature to visualize")
with gr.Blocks(theme=gr.themes.Soft()) as interface:
    with gr.Row():
        with gr.Column():
            Data = gr.Dataframe(value = None, interactive = True)
        with gr.Column():
            Feature = gr.Dropdown(label="Feature", value = "Upload file first", choices = ["Upload file first"], interactive = False)
            Data.change(updateHeader, inputs = [Data], outputs = [Feature])
            
interface.launch(debug = True, share = True)

```

### Screenshot

Original dataframe:
![Screen Shot 2024-07-17 at 3 47 55 PM](https://github.com/user-attachments/assets/9dce015f-cb0c-4911-a41d-0ff4e9d1a0de)

User changes header column "1" to "Hello", but event not triggered
![Screen Shot 2024-07-17 at 3 48 01 PM](https://github.com/user-attachments/assets/ecfae8b4-dcbe-4f10-802b-c0f61f0f307f)

Event only triggered and update occurs after user clicks "New Row"
![Screen Shot 2024-07-17 at 3 48 08 PM](https://github.com/user-attachments/assets/a7498280-d7b9-4cd7-a8f0-2a87ba880397)

### Logs

```shell
NA
```

### System Info

```shell
NA
```

### Severity

Blocking usage of gradio

**Comment by shreyanmitra** [comment]
@abidlabs Any update on this?

**Comment by abidlabs** [comment]
Not yet. I do agree that the `.change()` event should be triggered when the headers are changed, since the headers are part of the value of `gr.DataFrame`. 

It'll probably take us some time to get to this, since our team is working on other things at the moment. If you'd like, you can open a pull request (relevant section of code is here: https://github.com/gradio-app/gradio/blob/c1ecfde50e55902140aafc3551968e26c1bb4cd0/js/dataframe/shared/Table.svelte#L426) and we are hapy to review

**Comment by JoodithHermmina** [comment]
@shreyanmitra I would like to take up this issue.Can I proceed?

**Comment by Joodith** [comment]
@abidlabs  I would like to take up this issue.Can I proceed with it?

**Comment by abidlabs** [comment]
Hi @Joodith yes, go for it!

**Comment by abidlabs** [comment]
Hi @Joodith have you made progress on this? I was looking at this issue myself, so let me know if you need any guidance on this front.

**Comment by Joodith** [comment]
Thanks @abidlabs .Iam just getting started with it.Will reach out to you if i need help.

**Comment by abidlabs** [comment]
Sounds good, this is on my radar as well as it’s something we would like to get in for the launch of Gradio 5 so I’ll work on it next week unless you beat me to it!

**Comment by Joodith** [comment]
@abidlabs I resolved  the issue.Now while running tests,iam getting error that ws is not imported.I installed the frontend packages as per mentioned in the guidelines.Is that an expected error?Shall i go for creating a pull request?

**Comment by abidlabs** [comment]
Awesome thanks! Go ahead and create a pull request and we’ll see if we can help fix the tests. By the way it’d be great if you can target the 5.0-dev branch as your base branch

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/9469, thanks @Joodith!

**Comment by Joodith** [comment]
Thanks @abidlabs.
