### ISSUE TITLE
Can U remove the --subpath or rootpath? the ComfyUI works well without it.

### ISSUE THREAD

**Issue by GitHub4LP** [gradio-app/gradio#8828]
### Describe the bug

remove the --subpath or rootpath

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
any version
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Can you explain more what the issue is @GitHub4LP ? The `root_path` argument of `launch` is needed when running gradio behind a proxy like nginx so we can't remove it.

**Comment by GitHub4LP** [comment]
The root_path is useful for the front-end, ComfyUI builds the path through:		
```javascript
this.api_host = location.host; this.api_base = location.pathname.split('/').slice(0, -1)
this.api_base = location.pathname.split('/').slice(0, -1).join('/');
{protocol}://${this.api_host}${this.api_base}/path
```

**Comment by abidlabs** [comment]
Not sure what the request here is? As @freddyaboulton pointed out, the rootpath is needed when running gradio behind a proxy like nginx. If you do not need to use the rootpath, simply don't use that parameter?

**Comment by abidlabs** [comment]
Going to close for lack of follow up.
