### ISSUE TITLE
`.input()` is missing in `gr.Image` and `gr.Audio`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#8831]
### Describe the bug

[internal Slack](https://huggingface.slack.com/archives/C02QZLG8GMN/p1721291769074839)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
    image = gr.Image(interactive=True)
    image.input(fn=lambda: print("foo"))
demo.launch()
```

### Logs

```
Traceback (most recent call last):
  File "/tmp/app.py", line 5, in <module>
    image.input(fn=lambda: print("foo"))
AttributeError: 'Image' object has no attribute 'input'
```

### System Info

```shell
gradio==4.38.1
```

### Severity

Blocking usage of gradio

**Comment by ngaudemet** [comment]
Hi gradio Team :) 
what would be the difference between gr.Image.upload() dans gr.Image.input()?
I’ve seen you fixed the issue but not sure to understand what would the .input event add compared to an upload event ? the event documentation is not very clear to me, and I can’t read your internal slack where you seem to describe the issue . 
thanks !

**Comment by abidlabs** [comment]
Hi @ngaudemet! The `.input()` event is fired whenever the user changes the value of the `Image` component through the UI. This would mean, for example, if the user clears the image. However, `.upload()` is only fired when a new image is actually uploaded.

**Comment by ngaudemet** [comment]
thanks @abidlabs! It's clearer for me now. Concerning events, the gr.File.select() still doesn't work anymore, though it is very useful when you want to know in the back end that a user selected a file in the front end :) cf issue #8772
