### ISSUE TITLE
Chatbot Image examples sizing

### ISSUE THREAD

**Issue by dawoodkhan82** [gradio-app/gradio#8834]
### Describe the bug

When images and videos are supplied to examples for chatbot, the image size is very large.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://huggingface.co/spaces/merve/llava-interleave

### System Info

```shell
n/a
```

### Severity

I can work around it

**Comment by Luodian** [comment]
Looking forward to fix the sizing issue so that we can use latest gradio with support for `file_count` in multimodaltextbox.
