### ISSUE TITLE
Issues with embedding Gradio spaces in Sphinx documentation

### ISSUE THREAD

**Issue by lappemic** [gradio-app/gradio#8835]
### Describe the bug

I am trying to embed Gradio spaces in our Sphinx-generated documentation for Kornia, but i am encountering some problems. Here's what i've tried and the issues i am facing:

1. Global script loading:
   I've added this to the Sphinx `conf.py` file:
   ```python
   html_js_files = [
       ("https://gradio.s3-us-west-2.amazonaws.com/3.39.0/gradio.js", {"defer": "defer"})
   ]
   ```

2. Embedding in RST files:
   I am using the `gradio-app` tag in our RST files like this:
   ```html
   <gradio-app space="kornia/kornia-image-enhancement"></gradio-app>
   ```
   (Example: https://github.com/kornia/kornia/blob/e37aace0f6806ccf5a040f5cf863fe87720621af/docs/source/enhance.rst?plain=1#L31)

With this setup, we're encountering the following issues:
- Demo input images don't show up correctly
- Can't select options from dropdowns
- Buttons don't work when clicked

I've also tried the iframe embedding method:
```html
<iframe
	src="https://kornia-kornia-image-enhancement.hf.space"
	frameborder="0"
	width="850"
	height="450"
></iframe>
```
This works, but it's not ideal to have to specify fixed width and height values.

Could you please advise on the best way to embed Gradio spaces in Sphinx documentation? We're looking for a solution that:
1. Works reliably across different Gradio spaces
2. Is responsive to different screen sizes
3. Doesn't require manual width/height specifications for each embed

Any suggestions or guidance would be greatly appreciated. Thank you!

For Reference the draft PR: https://github.com/kornia/kornia/pull/2958

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

See above

### System Info

```shell
gradio sdk 4.37.2
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Thanks  @lappemic. It sounds like you are using a very old version of gradio here:

> https://gradio.s3-us-west-2.amazonaws.com/3.39.0/gradio.js

Can you try upgrading this to a more recent version (it should match the version of the gradio app) and let us know if you are still encountering any issues?

**Comment by lappemic** [comment]
My bad with the version! Sorry for this. I changed:
- the part in the `Sphinx` config file from 
```python
html_js_files = [
    "js/custom.js",
    ("https://gradio.s3-us-west-2.amazonaws.com/3.39.0/gradio.js", {"defer": "defer"}),
]
```
to
```python
html_js_files = [
    "js/custom.js",
    ("https://gradio.s3-us-west-2.amazonaws.com/4.38.1/gradio.js", {"defer": "defer", "type": "module"}),
]
```
- And i updated the `<gradio-app>` attributes from `space=` to `src=`

These changes resolved the issue. Will close this issue.

Thanks for the fast reply @abidlabs!
