### ISSUE TITLE
Mounting Gradio in an already running FastAPI application causes the queue to not work.

### ISSUE THREAD

**Issue by oubeichen** [gradio-app/gradio#8839]
### Describe the bug

My project is developed using FastAPI. I need to load some asynchronous operations (such as reading configuration and database) after FastAPI starts, specifically during the startup event of the lifespan. (Since the codes are synchronous when uvicorn starts the app, it’s inconvenient to use asyncio.) 

After these operations, I mount Gradio.
I managed to open the Gradio page, but found that the interactions get no response.

Later, I found these:
https://github.com/gradio-app/gradio/issues/6718
https://github.com/gradio-app/gradio/pull/6759

However, these only address the issues when FastAPI uses lifespan, not the problems arising when using mount_gradio_app while already in lifespan.

Does anyone have any good suggestions? Thanks.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

test.py

```python
import contextlib
from typing import Any, AsyncContextManager

import gradio as gr
import uvicorn
from fastapi import FastAPI


def sample_chat(*args: Any, **kwargs: Any) -> str:
    return "this is a example output"


async def mount_gradio(app: FastAPI) -> None:
    # do some asynchronous operations
    ...

    io = gr.ChatInterface(sample_chat)
    gr.mount_gradio_app(app, io, path="/gradio")


@contextlib.asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncContextManager[Any]:
    await mount_gradio(app)
    yield


def get_app() -> FastAPI:
    # do some configurations
    app = FastAPI(lifespan=lifespan)
    return app


def main() -> None:
    uvicorn.run(
        "test:get_app",  # base on the file name
        factory=True,
    )


if __name__ == "__main__":
    main()

```

### Screenshot

![image](https://github.com/user-attachments/assets/6dd8ed01-7391-49ed-8212-aa692f901df9)
![image](https://github.com/user-attachments/assets/8d9fecdd-250c-40b4-b5fb-dd24684b29ff)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.38.1
gradio_client version: 1.1.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.3.0
fastapi: 0.111.1
ffmpy: 0.3.2
gradio-client==1.1.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.23.5
importlib-resources: 6.4.0
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.9.1
numpy: 2.0.0
orjson: 3.10.6
packaging: 24.1
pandas: 2.2.2
pillow: 10.4.0
pydantic: 2.8.2
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.5.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.30.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.6.1
httpx: 0.27.0
huggingface-hub: 0.23.5
packaging: 24.1
typing-extensions: 4.12.2
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @oubeichen - does mounting gradio in `get_app` instead of in the context manager  fix the issue?

**Comment by oubeichen** [comment]
> Hi @oubeichen - does mounting gradio in `get_app` instead of in the context manager fix the issue?

Mounting a fixed interface of Gradio in `get_app` works. However, `get_app` is a synchronous method, but I need to use asynchronous methods in `mount_gradio` to read from the database and dynamically change the Gradio interface.

**Comment by ackinc** [comment]
@oubeichen This comment [here](https://github.com/gradio-app/gradio/issues/5228#issuecomment-1680829259) shows the fix

I managed to solve my issue with something like:

```
# ... your other code

async def mount_gradio(app: FastAPI) -> None:
    # do some asynchronous operations
    ...

    io = gr.ChatInterface(sample_chat)
    io.queue()
    io.startup_events()
    gr.mount_gradio_app(app, io, path="/gradio")

# ... your other code
```

**Comment by freddyaboulton** [comment]
This is really a FastAPI issue. FastAPI is not running the startup events of the app that are defined in the lifespan (presumably because the app has already started).

@oubeichen - as a workaround can you use `asyncio.run` to run the async code in a sync scope in `get_app`? Not sure what else we can do here - sorry!

**Comment by corte** [comment]
I have the same problem, but the solution doesn't work for me because neither `gr.Blocks` or `gr.ChatInterface` have the function `startup_events`.
```
AttributeError: 'Blocks' object has no attribute 'startup_events'
```
```
AttributeError: 'ChatInterface' object has no attribute 'startup_events'
```
