### ISSUE TITLE
stdio coming from the prediction function swallowed on ubuntu but not on macos

### ISSUE THREAD

**Issue by fakedrake** [gradio-app/gradio#8841]
### Describe the bug

I run the gradio http server and I want to be able to see the stderr and stdout that the function emits. On macos it works great. On ubuntu the website works fine but no stderr or stdout  are shown

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def greet(name):
    print("I am greeting!")
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="textbox", outputs="textbox")

if __name__ == "__main__":
    demo.launch()
```

Prints on macos

```
$ python ./gradio_test.py
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
I am greeting!
```

but on ubuntu

```
$ python ./gradio_test.py
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
macos and ubuntu. Ubuntu is


# uname -a
Linux srv564721 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
```


### Severity

Blocking usage of gradio

**Comment by fakedrake** [comment]
I forgot the `launch(server_name='0.0.0.0')` argument to launch and was not actually exposing the server to the network, I was seeing an older version of my app running. Stupid mistake.

**Comment by abidlabs** [comment]
Thanks @fakedrake for letting us know
