### ISSUE TITLE
Customize the syntax highlighting for gr.Code

### ISSUE THREAD

**Issue by ayoubachak** [gradio-app/gradio#8863]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I'm using the `gr.Code` in my interface, I want to use the syntax highlighting of [Gherkin Code](https://cucumber.io/docs/gherkin/), I want to know if it's already possible to write syntax customizations, because I couldn't find anything on the documentation related to the gr.Code component. The project I'm working on is involving a coding platform so this part is crucial. 

**Describe the solution you'd like**  
Maybe when we want to use the special syntax highlighting, we pass along a special json which has the Regex patterns to highlight the parts we want with the colors we want. 

**Additional context**  
If it's not planned, is there a way to make a custom gr.Code component where I can modify the syntax highlighting ?

**Comment by freddyaboulton** [comment]
> If it's not planned, is there a way to make a custom gr.Code component where I can modify the syntax highlighting ?

Hi @ayoubachak ! Yes it is possible to build custom components. Please see this guide: https://www.gradio.app/guides/custom-components-in-five-minutes

I think I will close because I don't think we'll build arbitrary code highlighting into the core Code components.
