### ISSUE TITLE
ValueError: Language diff not supported.

### ISSUE THREAD

**Issue by MAhmadUzair** [gradio-app/gradio#8868]
### Describe the bug

File "/Users/Uzair/Desktop/aider1/project/lib/python3.11/site-packages/gradio/components/code.py", line 118, in __init__
    raise ValueError(f"Language {language} not supported.")
ValueError: Language diff not supported.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
ValueError: Language diff not supported.
```

### System Info

```shell
Windows
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @MAhmadUzair what code are you running that leads to this issue? Please provide a minimal repro See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by MAhmadUzair** [comment]
I am trying to run a gradio endpoint in a project, When I try to get the response it generates the above-stated error.

**Comment by abidlabs** [comment]
We'll need a minimal code snippet to reproduce the issue, there's nothing here for us to investigate

**Comment by abidlabs** [comment]
Going to close this until we have a repro, thanks @MAhmadUzair
