### ISSUE TITLE
Update the choice of Radio component will lead interactive=False by default.

### ISSUE THREAD

**Issue by UYRONG** [gradio-app/gradio#8872]
### Describe the bug

I'd like to update the choices in a Radio component with a button click by using the function gr.update(choice=newlist). However, this action automatically sets the Radio component to interactive=False. I've tested this behavior with other components like the Dropdown, but it seems to only occur with the Radio component. I'm curious if this is intended behavior or a potential issue.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def update_radio_choice(name):
    f1 = [1,2,3,4,5]
    f2 = [6,7,8,9,10]
    return [gr.update(choices=f1), gr.update(choices=f2)]

with gr.Blocks() as demo:
        name = gr.Textbox(label="Name")
        with gr.Row():
            r1 = gr.Radio(choices=[], label="Radio 1")
            r2 = gr.Radio(choices=[], label="Radio 2")
            update_button = gr.Button("Update Radio")
        
        update_button.click(update_radio_choice, inputs=[name], outputs = [r1, r2])

demo.launch()

```

### Screenshot

![10861721725428_ pic](https://github.com/user-attachments/assets/42562278-746e-489f-a7ae-f991dacff530)
![10871721726245_ pic](https://github.com/user-attachments/assets/f5f1d776-d75c-4a6f-8d67-82263d6c1057)
Cannot screenshot the status of cursor so I take a photo and crop it.

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.36.1
gradio_client version: 1.0.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.0.1
fastapi: 0.111.0
ffmpy: 0.3.2
gradio-client==1.0.1 is not installed.
httpx: 0.26.0
huggingface-hub: 0.23.4
importlib-resources: 6.4.0
jinja2: 3.1.3
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.26.4
orjson: 3.10.5
packaging: 23.1
pandas: 2.1.4
pillow: 10.2.0
pydantic: 2.7.4
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.4.10
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.9.0
urllib3: 2.0.7
uvicorn: 0.30.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.26.0
huggingface-hub: 0.23.4
packaging: 23.1
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @UYRONG this is intended behavior. When a component is used _only_ as an output, it is rendered as `interactive=False` in Gradio. So if you were to continue building your app and use the `gr.Radio` buttons as inputs to other events, they will be rendered with `interactive=True`. The other alternative would be to explicitly pass in `interactive=True` in your update, e.g.

```py
import gradio as gr

def update_radio_choice(name):
    f1 = [1,2,3,4,5]
    f2 = [6,7,8,9,10]
    return [gr.update(choices=f1, interactive=True), gr.update(choices=f2, interactive=True)]

with gr.Blocks() as demo:
        name = gr.Textbox(label="Name")
        with gr.Row():
            r1 = gr.Radio(choices=[], label="Radio 1")
            r2 = gr.Radio(choices=[], label="Radio 2")
            update_button = gr.Button("Update Radio")
        
        update_button.click(update_radio_choice, inputs=[name], outputs = [r1, r2])

demo.launch()

```

**Comment by UYRONG** [comment]
> Hi @UYRONG this is intended behavior. When a component is used _only_ as an output, it is rendered as `interactive=False` in Gradio. So if you were to continue building your app and use the `gr.Radio` buttons as inputs to other events, they will be rendered with `interactive=True`. The other alternative would be to explicitly pass in `interactive=True` in your update, e.g.
> 
> ```python
> import gradio as gr
> 
> def update_radio_choice(name):
>     f1 = [1,2,3,4,5]
>     f2 = [6,7,8,9,10]
>     return [gr.update(choices=f1, interactive=True), gr.update(choices=f2, interactive=True)]
> 
> with gr.Blocks() as demo:
>         name = gr.Textbox(label="Name")
>         with gr.Row():
>             r1 = gr.Radio(choices=[], label="Radio 1")
>             r2 = gr.Radio(choices=[], label="Radio 2")
>             update_button = gr.Button("Update Radio")
>         
>         update_button.click(update_radio_choice, inputs=[name], outputs = [r1, r2])
> 
> demo.launch()
> ```

Understand. Thanks so much!
