### ISSUE TITLE
Enable file uploads from both local and/ or Google Drive in Gradio?

### ISSUE THREAD

**Issue by Tobsad** [gradio-app/gradio#8894]
### Describe the bug

Hello,

I'm using Gradio for a project and would like to enable users to upload documents either from their local computer or directly from Google Drive. Could  provide guidance or examples on how to implement this feature? 

Any tips on handling the authentication for Google Drive or managing the files once they're uploaded would be greatly appreciated!

I see that there is a gr.MultimodalTextbox component but it only takes local files.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python

import gradio as gr

with gr.Blocks() as bloque:
    show_btn = gr.Button("Show Modal")
    chatbot = gr.Chatbot(likeable=True,show_share_button=True)
    message_prompt = gr.MultimodalTextbox(interactive=True)

    def saludo(msg,chatbot):
        print(msg['text'])
        print(msg['files'])


        if msg['files'] == []:
            #Fn Response with doc...
            chatbot.append((msg['text'], "Response without doc"))
            return {"text": "", "files": msg['files']}, chatbot
        else:
            #Fn Response withoud doc...
            chatbot.append((msg['text'], "Response with doc"))
            return {"text": "", "files": msg['files']}, chatbot 
        
    message_prompt.submit(saludo,[message_prompt,chatbot],[message_prompt,chatbot])

bloque.launch()

```

### System Info

```shell
gradio                    4.39.0
gradio_client             1.1.1
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
I think this would be a great custom component ! Not sure we need to build this functionality directly into gradio core
