### ISSUE TITLE
[`blocks-dev`] Dataframe input and output both behave incorrectly

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#890]
### Describe the bug

Noticing some issues with the Dataframe component.

When used as an input, none of the rows show up by default. Even clicking "new row" only produces a tiny narrow row that can't really be used to input any data since it is so narrow. The column headers seem to be completely unaligned with the cells.

When used as an output, the "new column" and "new row" button still show up, though they should be disabled for an output component.

### Reproduction

demo\filter_records\run.py

### Screenshot

![image](https://user-images.githubusercontent.com/1778297/160428779-9d945384-f427-41d0-bb8b-372276095369.png)

### System Info

```shell
blocks-dev
```

### Severity

blocker

**Comment by abidlabs** [comment]
Some of these issue also happen with the `Timeseries` input and output.

See `demo\fraud_detector\run.py`

**Comment by abidlabs** [comment]
`demo\matrix_transpose\run.py` is not working for, I think, the same reason

**Comment by pngwn** [comment]
Closed by #981.
