### ISSUE TITLE
multimodal chatbot custom component broken; normalise_file used in multimodal chatbot gone

### ISSUE THREAD

**Issue by ajayarora1235** [gradio-app/gradio#8904]
### Describe the bug

making a custom chatbot component using multimodal chatbot and latest @gradio npm install, and the normalise_file function that is being used doesn't exist

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

gradio cc dev on clone of multimodal chatbot component

### System Info

```shell
Operating System: Darwin
gradio version: 4.26.0
gradio_client version: 0.15.1
```

### Severity

Blocking usage of gradio

**Comment by ajayarora1235** [comment]
oh wait i'm taking a look at the current default Chatbot in gradio, which re-defined normalize_messages. Is the chatbot now multimodal by default?

**Comment by abidlabs** [comment]
Hi @ajayarora1235 we can look into this, but I'd suggest using the built-in `gr.Chatbot` in Gradio instead, which now supports `gr.Image`, `gr.Video`, `gr.HTML` natively. Here's an example: https://github.com/gradio-app/gradio/blob/main/demo/chatbot_core_components_simple/run.py

Let us know if you have any questions. 

I noticed that we don't have any documentation about this. This would be good to add @dawoodkhan82?

**Comment by ajayarora1235** [comment]
Hey yes! So I managed to figure this out and naively add Buttons to the chatbot via defining a new MultimodalMessage that has "text", "files", and "buttons" as attributes and then printing the buttons via BaseButton:

```
{#each message.buttons as button, p}
										<BaseButton
											value={button.text}
											on:click={() => dispatch("click")}
										>
											{value ? button.text : ""}
										</BaseButton>
									{/each}
```

My only question is how would I be able to link these buttons to a function I define in app.py? Would I need to have an attribute of my ButtonMessage class be a callable?

Would appreciate any help @abidlabs @dawoodkhan82 , as I know this has been heavily requested! :)

**Comment by ajayarora1235** [comment]
if it's helpful, for my particular use case, all the button needs to trigger is the next response from the user, i.e. a "Make this better" button click will just send a custom prompt to the chatbot to make the thing in question better. So it should be straightforward, just need to get the name of the button that was clicked back to my app.py somehow.

**Comment by abidlabs** [comment]
I believe this should solve the original issue @ajayarora1235: https://github.com/gradio-app/gradio/pull/9989
