### ISSUE TITLE
Sharing in chatbot is broken

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#8909]
### Describe the bug

Not sure if this is a widespread issue, but as @osanseviero reported, sharing in https://huggingface.co/spaces/gokaygokay/Gemma-2-llamacpp is broken.

> I tried https://huggingface.co/spaces/gokaygokay/Gemma-2-llamacpp
> Wrote "hello", got an answer
> Clicked share button
> Ended up in https://huggingface.co/spaces/gokaygokay/Gemma-2-llamacpp/discussions/new?description=

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

See above

### System Info

```shell
sdk_version: 4.37.2
```

### Severity

I can work around it

**Comment by ps24601** [comment]
Space link: https://huggingface.co/spaces/huggingface-projects/gemma-2-2b-it
When you click on share:
![share failed](https://github.com/user-attachments/assets/7d033fcb-6e4b-46ef-9d85-9727d9ff11e7)

**Comment by kghamilton89** [comment]
Hi @abidlabs, I've raised a simple PR that populates the `Description` parameter with a default value to resolve this.

**Comment by abidlabs** [comment]
Also I'm seeing a double share icon:

![Image](https://github.com/user-attachments/assets/ad4e14c0-694b-478b-a017-8ecdce79e91d)
