### ISSUE TITLE
Displaying examples inside the chatbot window

### ISSUE THREAD

**Issue by yvrjsharma** [gradio-app/gradio#8912]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Improving the UI for displaying examples in Gradio's Chatbot and ChatInterface components. Currently, examples are shown outside (below) the chat window, which works but could be enhanced for a better user experience, especially for multimodal demos. This could help in below mentioned benefits imo:
- Improved UX, especially for multimodal demos (Audio, Video, Image, Docs)
- More screen space for chatbot window
- Closer alignment with common practices in chat interfaces

**Describe the solution you'd like**  
- Implement a way to display example conversations directly within the Chatbot window.
- Maybe creating a new parameter for Chatbot/ChatInterface to specify these in-chat examples.
- Would be great if we can ensure compatibility with the existing `placeholder` argument of the chatbot.
- If both placeholder and new examples are provided, we can consider overlaying examples on top of the placeholder (cc: @abidlabs, from Slack conversation)

**Additional context**  
- Consider an API that could potentially support both examples and custom buttons within the chat interface (Ref: #8698; from Slack discussion)

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/8966
