### ISSUE TITLE
In Chatbot component, how to close of the picture click to enlarge function

### ISSUE THREAD

**Issue by yaosheng216** [gradio-app/gradio#8913]
- Hi， I have question of Chatbot component, how to close of the picture click to enlarge function
   Looking forward to your reply.

  Thanks!

**Comment by dawoodkhan82** [comment]
@yaosheng216 Not sure I completely understand your question. But, there's a button "X" on the top right of the enlarged image to close the pop-up.

**Comment by yaosheng216** [comment]
@dawoodkhan82 Thanks for your answer, but my question is click image do not enlarge in chatbot, myself design a image edit function,i want close gradio's image click enlarge function,looking forward you solution.
