### ISSUE TITLE
how to got the login return user info in gradio to make a backend api command?

### ISSUE THREAD

**Issue by gonghuan2024** [gradio-app/gradio#8914]
### Describe the bug

I have this main.py which use fastAPI and gradio to do external LDAP auth, code is like following:
import os, uvicorn
from llmtuner import create_ui, create_history
from llmtuner.webui.components.smlflow_client import SMLFlowClient
import gradio as gr
from fastapi import FastAPI, Depends, status, Request
from fastapi.responses import RedirectResponse, HTMLResponse
from fastapi.security import OAuth2PasswordRequestForm
from starlette.middleware.sessions import SessionMiddleware

app = FastAPI()

# Add session middleware to FastAPI
app.add_middleware(SessionMiddleware, secret_key="your_secret_key")
client = SMLFlowClient()

def get_server_name_from_env():
    return os.getenv("POD_IP_ADDRESS", "localhost")

def cluster_information():
    return "集群信息"

def get_user(request: Request):
    user = request.cookies.get('user')
    return user if user else None

def authenticate_user(email: str, password: str):
    user_info = client.ldap_query(email, password)
    if user_info and 'user_info' in user_info:
        return user_info
    else:
        return None

@app.get("/login", response_class=HTMLResponse)
async def login_form(error: str = ""):
    error_message = f"<p style='color: red;'>{error}</p>" if error else ""
    return f"""
    <html>
    <head>
        <style>
            body {{
                font-family: Arial, sans-serif;
                background-color: #f4f4f4;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
            }}
            .container {{
                background: white;
                padding: 20px;
                border-radius: 8px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
                width: 100%;
                max-width: 400px;
                text-align: center;
            }}
            h1 {{
                font-size: 18px; /* 调整字体大小 */
                color: #003366; /* 深蓝色 */
                margin-bottom: 20px;
                font-family: 'Arial Black', Gadget, sans-serif; /* 粗体艺术字 */
                font-weight: bold;
                text-transform: uppercase; /* 大写字母 */
                letter-spacing: 1px; /* 字符间距 */
                white-space: nowrap; /* 保持在一行显示 */
            }}
            label {{
                display: block;
                font-size: 14px;
                color: #00aaff; /* 天蓝色 */
                font-weight: bold;
                margin-bottom: 8px;
                text-align: left;
            }}
            input[type="text"], input[type="password"] {{
                width: calc(100% - 22px);
                padding: 10px;
                border-radius: 4px;
                border: 1px solid #ccc;
                font-size: 14px;
                margin-bottom: 10px;
            }}
            input[type="submit"] {{
                width: 100%;
                padding: 10px;
                border-radius: 4px;
                border: none;
                background-color: #00aaff; /* 天蓝色 */
                color: white;
                font-size: 16px;
                cursor: pointer;
            }}
            input[type="submit"]:hover {{
                background-color: #0099cc; /* 深天蓝色 */
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>LOGIN TO TC COMPUTING PLATFORM</h1>
            {error_message}
            <form action="/token" method="post">
                <label for="username">Email:</label>
                <input type="text" id="username" name="username" required><br><br>
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required><br><br>
                <input type="submit" value="Login">
            </form>
        </div>
    </body>
    </html>
    """

@app.route('/logout')
async def logout(request: Request):
    response = RedirectResponse(url='/login')
    response.delete_cookie('user')
    return response

@app.post("/token")
async def login(request: Request, form_data: OAuth2PasswordRequestForm = Depends()):
    print(f"-------------------Login attempt with email------------------: {form_data.username}")
    access_token = authenticate_user(form_data.username, form_data.password)
    if not access_token:
        return RedirectResponse(url="/login?error=Invalid%20credentials", status_code=status.HTTP_303_SEE_OTHER)
    
    response = RedirectResponse(url="/smlflowui", status_code=status.HTTP_303_SEE_OTHER)
    response.set_cookie(key='user', value=str(dict(access_token)['user_info']))

    print(f"------------------------Cookie set--------------: {access_token}")
    return response

@app.get("/")
def public(user: dict = Depends(get_user)):
    print("------------------------/user is-----------------: ", user)
    if user:
        return RedirectResponse(url='/smlflowui')
    return RedirectResponse(url='/login')

@app.get("/check_session")
async def check_session(request: Request):
    return {"session": dict(request.session)}

def create_gradio_login_interface():
    with gr.Blocks() as login_demo:
        gr.Button("Login", link="/login")
        return login_demo

def create_gradio_interface():
    def greet(request: gr.Request):  
        user = request.cookies.get('user')      
        if not user:
            return "Please log in to access this page."
        print("---------------user_info is-------------------: ", eval(user))
        user = eval(user)
        return f"**Welcome to the TC Computing Resource Platform**, {user['account']}!"
    
    welcome_css = """
    .flex-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
        padding: 10px;
        background-color: #80d4ff; /* 背景色 */
    }
    #welcome-message {
        flex: 5; /* 5 parts of the available space */
        padding: 20px;
        color: #003366; /* 深蓝色 */
        font-weight: bold; /* 加粗 */
        font-family: 'Arial Black', sans-serif; /* 艺术字体 */
        font-size: 55px; /* 字体大小 */
        text-align: left; /* Align text to the left */
    }
    #logout-button {
        flex: 1; /* 1 part of the available space */
        padding: 10px;
        background-color: #003366; /* 天蓝色 */
        color: white;
        font-size: 16px;
        border-radius: 5px;
        text-align: center;
        border: none;
        cursor: pointer;
        transition: background-color 0.3s ease; /* 过渡效果 */
    }
    #logout-button:hover {
        background-color: #e6b800; /* 深黄色 */
    }
    """
    
    with gr.Blocks(css=welcome_css) as main_demo:
        with gr.Row(elem_classes="flex-container"):
            m = gr.Markdown("Welcome to the TC Computing Resource Platform!", elem_id="welcome-message", show_label=False)
            gr.Button("Logout", variant="primary", link="/logout", elem_id="logout-button")
        
        # Existing tabs
        with gr.Tab("Fine Tune"):
            create_ui()  # 传递用户信息给 create_ui 函数
        with gr.Tab("Cluster Information"):
            gr.Markdown(cluster_information())
        with gr.Tab("All Executions"):
            create_history()
        main_demo.load(greet, None, m)

    return main_demo

login_app = create_gradio_login_interface()
main_app = create_gradio_interface()
app = gr.mount_gradio_app(app, login_app, path="/login")
app = gr.mount_gradio_app(app, main_app, path="/smlflowui", auth_dependency=get_user)

if __name__ == '__main__':
    server = get_server_name_from_env()
    uvicorn.run(app, host="0.0.0.0", port=7860)

It's can login in successful now, and the ui can show the correct username with markdown, but I also need got the user info after create_ui() finished, I has a run.py need this user info to pass it to backend API interface, so could I do this?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
Version: 4.39.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @gonghuan2024 for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue). If indeed this is a bug or a feature request, can you please provide a minimal code example that we can use to reproduce the issue? See: https://stackoverflow.com/help/minimal-reproducible-example
