### ISSUE TITLE
Reload Mode not reloading changes from indirectly referenced modules

### ISSUE THREAD

**Issue by JackismyShephard** [gradio-app/gradio#8917]
### Describe the bug

I am using gradio for a larger project where my main `app.py` script is importing render functions from several frontend modules. These modules themselves import functionality from backend modules. When I make changes in the backend modules, those files are not reloaded by Reload Mode.  

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Here is a minimal example that reproduces the error on my system:

app.py:

```python
import gradio as gr

from frontend import render

with gr.Blocks(title="Ultimate RVC") as app:
    render()

if __name__ == "__main__":
    app.launch()

```

frontend.py:

```python
import gradio as gr

from backend import print_success


def render() -> None:
    button = gr.Button("Print", variant="primary")
    message = gr.Text(label="Output message", interactive=False)
    button.click(print_success, outputs=message)
```
backend.py:

```python
def print_success() -> str:
    return f"Sus!"
```
I run the app in reload mode by executing `gradio ./app.py --demo-name app`. 

When I change the string returned by `print_success` in `backend.py`, the output message displayed in the app is not updated accordingly

### System Info

```shell
Gradio 4.38.1

Python 3.11 (using miniconda)

Windows 11 (also tested on Ubuntu 22.04 and 24.04)
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
I can look into this but probably not until late next week or later so if you have bandwidth to propose and implement a fix @JackismyShephard , that would be much appreciated!

**Comment by JackismyShephard** [comment]
@freddyaboulton  I probably also won't have time for it before then. My plan is to try and look into https://github.com/gradio-app/gradio/issues/8928 tomorrow. If you have not gotten around to it before next weekend I might have a look at it then, although I don't really know where to start 😅

**Comment by relubwu** [comment]
Encountered the same here, worked around by mounting gradio app to fastapi & use their reload, albeit much slower than gradio's. Tried downgrading to previous versions but some other problems popped up, likely due to dependency conflicts. Looking forward to solutions to this!

**Comment by JackismyShephard** [comment]
@freddyaboulton Might be nice to escalate this a bit. I am not sure it is something I can solve

**Comment by freddyaboulton** [comment]
@JackismyShephard are the backend files tracked by reload mode? Do they show up in the `Watching: ` print statement?

<img width="555" alt="image" src="https://github.com/user-attachments/assets/117d4a04-2887-435b-952b-25de48bac69d">

I am testing this locally and I am seeing changes in modules under the "watched" directories being propagated to the reloaded app. You can add additional directories to watch with `--watch-dirs`

**Comment by JackismyShephard** [comment]
@freddyaboulton After having upgraded to gradio 5.6.0 reload mode is working again 😄

**Comment by freddyaboulton** [comment]
Woohoo!

**Comment by phoenixor** [comment]
same problem, i using Gradio 5.14.0 and ModelScope Studio components with reload mode(gradio main.py), but Gradio only watch changes from main.py

**Comment by JackismyShephard** [comment]
I am also experiencing this problem again @freddyaboulton
