### ISSUE TITLE
Multilingual on-screen Keyboard Component

### ISSUE THREAD

**Issue by mdsrqbl** [gradio-app/gradio#8920]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
To input texts of non-latin languages, I have to go to google translate or some web browser key mapping extensions. It is very inconvenient for the user and disrupts the efficiency and fluidity of the app usage.

**Describe the solution you'd like**  
A simple component with a dropdown to select language and some buttons to type unicode characters of non-latin languages in the linked text area. QWERTY layout with phoneme based mapping & physical keyboard binding or at least buttons in alphabetical order both will be fine.
A Python-based component would be highly preferable, as it would integrate seamlessly with existing Gradio workflows and eliminate the need for external JavaScript imports.

**Additional context** 
Such a feature would be incredibly beneficial for developers and users working with multilingual datasets and applications. Here’s an example of an online virtual keyboard that I use:
<img width="967" alt="multilingual keyboard" src="https://github.com/user-attachments/assets/187744c7-f2e5-4a2d-8724-7b71f98877cb">
<img width="654" alt="keyboard" src="https://github.com/user-attachments/assets/563a2de6-ee59-4fbf-9bf3-f93c13c3cec2">

**Comment by freddyaboulton** [comment]
This feels like a good use case for custom components! 

In fact, a huggingface user created a component that does something similar - https://huggingface.co/spaces/camilosegura/gradio_keyboardtextboxcomponent 

You should clone the space and tweak the component to your use case!

We've prepared guides on how to get started developing custom components here: https://www.gradio.app/guides/custom-components-in-five-minutes

**Comment by abidlabs** [comment]
Agreed, we are not likely to include this in the core `gr.Textbox`, but this would a be a great custom component
