### ISSUE TITLE
Improving design consistency of Color Pickers

### ISSUE THREAD

**Issue by gsbm** [gradio-app/gradio#8921]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Hi,
I understand that the `gradio.color` component is probably not much used, but I suggest simply reusing the color pick modal designed for selection in `gradio.imageEditor` to improve the global design consistency.

**Describe the solution you'd like**  
Instead of calling the native browser color picker, I suggest overwriting the color input by a custom one, more coherent to the design system, while using the existing color pick modal. In addition, it would be a good idea to refine slightly the input shape since it's still the native browser input.

To go deeper on the discussion, it seems that this custom color picker is not well displayed on mobile. Since the native one is well handled by different devices but is lacking of design constency, maybe trying to make the custom color picker bigger on smaller devices with an absolute positionning would improve the usage. Another possibility would be to trigger native color input event only on smaller devices.
Maybe it's not an important point now since Gradio seems more desktop-first oriented.

**Additional context**
Now (windows, firefox, probably the worst UI case)
![Frame 3](https://github.com/user-attachments/assets/6d32af35-4dbb-4314-b04f-f88da697bfa0)
Suggestion
![Frame 4](https://github.com/user-attachments/assets/456c1f22-a1c3-4551-a3f3-7c2df08d36c4)

**Comment by abidlabs** [comment]
Thanks @gsbm makes sense, we'll see if we can improve this as part of a larger ui refresh we are currently working on.

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/9570, thanks @hannahblair and thanks @gsbm for the suggestion!
