### ISSUE TITLE
Insufficient typing of event listener functions

### ISSUE THREAD

**Issue by JackismyShephard** [gradio-app/gradio#8928]
### Describe the bug

I am using pyright for type checking via pylance in visual studio code. I have been having problems with pyright not being able to resolve the type of, in particular, event listener functions. Usually, pyright will complain that certain parameters and/or return types are partially unknown.

By digging around a bit locally, I have been able to ascertain that the problem is mostly due to insufficient typing in the .pyi stub files for gradio. Two recurring problems are
* The type `Block` is not imported from `gradio.blocks`
* The type `Callable` is not quantified as `Callable[...,Any]`

More specifically, I have observed problems with event listener function defined in the following stub files
* `gradio/components/button.pyi` (click)
* `gradio/components/dataframe.pyi` (select)
* `gradio/components/textbox.pyi` (change)
* `gradio/components/checkboxgroup.pyi` (select, change)
* `gradio/components/dropdown.pyi` (input, change)
* `gradio/components/audio.pyi` (input)
* * Here there is also a problem with `Literal` not being imported from `typing`
* `gradio/blocks_events.pyi` (load)
* * Here there is also a problem with both `Literal` and `Callable` not being imported from `typing`

Additionally, I also observed some insufficient typing in some regular python files, namely
* `gradio/helpers.py`
* * return type for `update` function should be quantified as `dict[Any. Any]` not `dict`.
* * `kwargs` parameter should be typed, for example as `Any`
* `gradio/blocks.py
* * return type for `unload` event listener is missing (should be `None`)
* * parameter `fn` for `unload` should be qualified as `Callable[..., Any]`

I have successfully fixed the above problems locally. I was hoping to make a PR with a fix for gradio upstream, but the .pyi files seem to be generated automatically so that was not possible for me. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

1. Install python (any version on windows or ubuntu)
2. install latest version of gradio
3. set pyright mode to `strict` in visual studio code
4. use any of the above mentioned definitions in a python script, eg:
```python
import gradio as gr

with gr.Blocks(title="Ultimate RVC") as app:
    pass

if __name__ == "__main__":
    app.launch()

```
5. pyright will complain in visual studio code

### Screenshot

![image](https://github.com/user-attachments/assets/46e79abd-d728-4521-bc0a-02d469aca3ad)

### System Info

```shell
Windows 11 (also tested in ubuntu 22.04)
Python 3.11 (also tested with Python 3.10)
Gradio 4.39.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @JackismyShephard! A PR for this would be extremely appreciated. The `.pyi` files are generated based on the template provided in this file: `gradio/component_meta.py` so modifying the `INTERFACE_TEMPLATE` string (adding imports as needed, etc.) should resolve the issues you are seeing

**Comment by JackismyShephard** [comment]
@abidlabs I will try to have a look at it some time this week
