### ISSUE TITLE
`gr.Dataset` is rendered infinitely on the frontend 

### ISSUE THREAD

**Issue by Col0ring** [gradio-app/gradio#8936]
### Describe the bug

I'm creating a custom component, but I found a problem that the `afterUpdate` hook from `svelte` is always called when I have the `gr.Dataset` or `gr.Example` in my app.

https://github.com/gradio-app/gradio/blob/9b42ba8f1006c05d60a62450d3036ce0d6784f86/js/dataset/Index.svelte#L55-L66

The problem lies here: `samples = sample_labels ? sample_labels.map((e) => [e]) : samples || [];` , which makes `svelte` listen the changes of `samples` and run this code continuously, and then affect  the entire gradio application and other components.

To fix it, should change this line  to:
```js
if (sample_labels) {
	samples = sample_labels.map((e) => [e]);
} else if (!samples) {
	samples = [];
}
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
gradio cc create sample_input --template=SimpleTextbox
```
Mofify `frontend/Index.svelte`
```svelte
<svelte:options accessors={true} />

<script lang="ts">
  // sample code...
  $: console.log($$props)
</script>
```

demo.py
```py
import gradio as gr
from gradio_sample_input import sample_input

def fn(_input):
    return _input


with gr.Blocks() as demo:
    input = sample_input()
    text = gr.Text()
    gr.Examples(inputs=[text], examples=[['hello']])
    input.change(fn=fn, inputs=[input], outputs=[text])

if __name__ == "__main__":
    demo.launch()
```

### System Info

```shell
gradio version: 4.39.0
gradio_client version: 1.1.1
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Would you like to PR this @Col0ring ? @pngwn and I can take a look - we probably won't have bandwidth to do this ourselves until late next week or later
