### ISSUE TITLE
[`blocks-dev`] Add remaining Interface kwargs

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#895]
A tracking issue for all of the remaining `Interface` keyword arguments and `launch()` keyword arguments. From what I see, the remaining ones are:

- [x] interpretation
- [x] live (also mentioned in #855)
- [x] auth
- [x] cache_examples 
- [x] enable_queue

**Comment by FarukOzderim** [comment]
if queue is going to be reimplemented from strach it would be nice to handle this issue as well #572.

**Comment by abidlabs** [comment]
@aliabid94 did we close all of these?

**Comment by abidlabs** [comment]
Closed via #944
