### ISSUE TITLE
Gradio js client in React gives multiple errors

### ISSUE THREAD

**Issue by Deep13** [gradio-app/gradio#8953]
### Describe the bug

@gradio/client version: 1.4.0
running the react app with gradiojs client API gives multiple errors in ./node_modules/@gradio/client/dist/index.js and ./node_modules/@gradio/client/dist/wrapper-CviSselG.js

Module not found: Error: Can't resolve 'fs/promises' in '/Users/user1/React/react_app/node_modules/@gradio/client/dist'
ERROR in ./node_modules/@gradio/client/dist/index.js 882:23-44
Module not found: Error: Can't resolve 'fs/promises' in '/Users/user1/React/react_app/node_modules/@gradio/client/dist'

ERROR in ./node_modules/@gradio/client/dist/index.js 883:25-39
Module not found: Error: Can't resolve 'path' in '/Users/user1/React/react_app/node_modules/@gradio/client/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }

ERROR in ./node_modules/@gradio/client/dist/wrapper-CviSselG.js 1:0-32
Module not found: Error: Can't resolve 'stream' in '/Users/user1/React/react_app/node_modules/@gradio/client/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }

ERROR in ./node_modules/@gradio/client/dist/wrapper-CviSselG.js 2:0-32
Module not found: Error: Can't resolve 'zlib' in '/Users/user1/React/react_app/node_modules/@gradio/client/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "zlib": require.resolve("browserify-zlib") }'
        - install 'browserify-zlib'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "zlib": false }

ERROR in ./node_modules/@gradio/client/dist/wrapper-CviSselG.js 3:0-30
Module not found: Error: Can't resolve 'fs' in '/Users/user1/React/react_app/node_modules/@gradio/client/dist'

ERROR in ./node_modules/@gradio/client/dist/wrapper-CviSselG.js 4:0-32
Module not found: Error: Can't resolve 'path' in '/Users/user1/React/react_app/node_modules/@gradio/client/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }

ERROR in ./node_modules/@gradio/client/dist/wrapper-CviSselG.js 5:0-28
Module not found: Error: Can't resolve 'os' in '/Users/user1/React/react_app/node_modules/@gradio/client/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
        - install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "os": false }

ERROR in ./node_modules/@gradio/client/dist/wrapper-CviSselG.js 7:0-29
Module not found: Error: Can't resolve 'net' in '/Users/user1/React/react_app/node_modules/@gradio/client/dist'

ERROR in ./node_modules/@gradio/client/dist/wrapper-CviSselG.js 8:0-29
Module not found: Error: Can't resolve 'tls' in '/Users/user1/React/react_app/node_modules/@gradio/client/dist'

ERROR in ./node_modules/@gradio/client/dist/wrapper-CviSselG.js 9:0-32
Module not found: Error: Can't resolve 'crypto' in '/Users/user1/React/react_app/node_modules/@gradio/client/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }

ERROR in ./node_modules/@gradio/client/dist/wrapper-CviSselG.js 11:0-33
Module not found: Error: Can't resolve 'https' in '/Users/user1/React/react_app/node_modules/@gradio/client/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
        - install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "https": false }

ERROR in ./node_modules/@gradio/client/dist/wrapper-CviSselG.js 12:0-32
Module not found: Error: Can't resolve 'http' in '/Users/user1/React/react_app/node_modules/@gradio/client/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }

ERROR in ./node_modules/@gradio/client/dist/wrapper-CviSselG.js 13:0-29
Module not found: Error: Can't resolve 'url' in '/Users/user1/React/react_app/node_modules/@gradio/client/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
        - install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "url": false }

webpack compiled with 13 errors

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

npm i  @gradio/client

import { Client } from "@gradio/client";

### System Info

```shell
@gradio/client version 1.4.0
```

### Severity

Blocking usage of gradio

**Comment by 180ParkerLi** [comment]
解决了吗？我也遇到了同样的问题 @Deep13

**Comment by binarycombinatrix** [comment]
How is this marked as completed? The issue still persists and no solution is provided in this thread. And why is that reply in Chinese?
