### ISSUE TITLE
show_progress in ChatInterface

### ISSUE THREAD

**Issue by rmuhawieh** [gradio-app/gradio#8956]
### Describe the bug

I notice that in the ChatInterface for the show_progress in the top right corner, it sometimes shows "processing | 80.7s/50.2s" and other times shows "processing | 80.7s". I'd like my ChatInterface to only show the one time rather than two but I'm not understanding where the customization is for that?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```
import random
import gradio as gr

def random_response(message, history):
    return random.choice(["Yes", "No"])

demo = gr.ChatInterface(random_response)

if __name__ == "__main__":
    demo.launch()

### System Info

```shell
Yes
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @rmuhawieh the first time that you run a Gradio function, it only shows the running time of the function. In subsequent runs, we show the current running time and the expected runtime (based on the average of previous runs). This isn't something that can be modified in Gradio, but if you'd like to hide the time altogether, you can set `show_progress="hidden"` in `gr.ChatInterface`

**Comment by rmuhawieh** [comment]
> Hi @rmuhawieh the first time that you run a Gradio function, it only shows the running time of the function. In subsequent runs, we show the current running time and the expected runtime (based on the average of previous runs). This isn't something that can be modified in Gradio, but if you'd like to hide the time altogether, you can set `show_progress="hidden"` in `gr.ChatInterface`

Because I'm not able to use a fully update gradio, I am currently using version 4.10.0 where show_progress isn't yet a thing for ChatInterface. Is there still a way to hide the times in the top right corner?

**Comment by abidlabs** [comment]
Hmm I don't think so, unless you build the Chatbot UI using Blocks instead, though that is more involved, see https://www.gradio.app/guides/creating-a-custom-chatbot-with-blocks

why can't you upgrade to the latest version of gradio?

**Comment by sajjadmosaheb** [comment]
Hi @abidlabs, I'm encountering this problem now, I was using the latest version of gradio and everything was fine but when I tried to modify the theme of the chatbot, I noticed that the "background_fill_secondary" parameter was changed from the earlier versions, so I cannot change the color of the bubbles beside the whole background.
but in the version====4.31.5 
the "block-background-fill" is used for the block the "background_fill_secondary" is used for the chatbot answer and the "color-accent-soft" is used for user inputs(for both versions)
so I decided to down the version to 4.31.5 but now the "show_progress "ability is gone!
any solution??

**Comment by sajjadmosaheb** [comment]
now I can see this feature changes everything:
background: var(--background-fill-secondary);
but I can't change this value via theme!
