### ISSUE TITLE
Feedback on comparison doc between Gradio and Mesop

### ISSUE THREAD

**Issue by wwwillchen** [gradio-app/gradio#8969]
Hi -

I'm one of the maintainers of [Mesop](https://google.github.io/mesop/), a Python UI framework. I've been following Gradio's work for a while and appreciate its focus in simplifying UI development.

We often get asked how Mesop differs from other frameworks like Gradio. To address this, I put together a [comparison doc](https://github.com/google/mesop/pull/639/files?short_path=5b35040#diff-5b350409df0c62cb8e97e1300b20ae09a73e419d46831a6b05c8c28251ed3756) that compares Mesop with other frameworks like Gradio.

I've tried my best to represent both frameworks fairly, but I know there's always room for improvement. I'd really appreciate it if you could take a look at the document and share any feedback or corrections you might have. My goal is to ensure the information is as accurate and helpful as possible for our users.

Apologies if this wasn't the right channel to post this - I wasn't sure where this belonged.

Thanks,
Will

**Comment by abidlabs** [comment]
Thanks @wwwillchen for the nice guide. I've left a few comments on the PR and will ping a few others on the team to share any feedback directly on the PR as well.
