### ISSUE TITLE
[`blocks-dev`] Problems with Textbox input and output

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#897]
### Describe the bug

I was running this demo: `demo\gpt_j\run.py` and noticed some issues:
* The input textbox size does not get set by the `lines` parameter
* The output textbox size does not dynamically change size according the output (see screenshot)
* The examples don't show up at all (although clicking on them does work interestingly)

<img width="955" alt="image" src="https://user-images.githubusercontent.com/1778297/160487216-2701b973-103c-43bd-aff3-4c521a08200f.png">

### Reproduction

`demo\gpt_j\run.py`

### System Info

```shell
blocks-dev
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Also, as can be seen by this demo: `demo\hello_world_2\run.py`, the `placeholder` parameter doesn't work

**Comment by abidlabs** [comment]
These issues seem to be fixed, except for this @pngwn:

> The output textbox size does not dynamically change size according the output

**Comment by abidlabs** [comment]
One very small part of https://github.com/gradio-app/gradio/issues/897 is left:

* The output textbox size does not dynamically change size according the output as it used to (see screenshot)

Here are a couple of screenshots:

![image](https://user-images.githubusercontent.com/1778297/162132340-49af3bae-4671-4990-a1e0-6c775c666249.png)

<img width="745" alt="image" src="https://user-images.githubusercontent.com/1778297/162132517-87c1bf3e-36ef-48b1-8f69-03f4766fc766.png">

The behavior should be that the number of lines of the output textbox should increase automatically to accommodate the text. 

Everything else looks great

**Comment by pngwn** [comment]
Closed by #929.
