### ISSUE TITLE
Clear chat history when a new example is selected

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#8979]
- [x] I have searched to see if a similar issue already exists.

The history of `gr.ChatInterface` is not cleared when a new examples a clicked, but maybe it would be useful to have that option as a parameter of `gr.ChatInterface` or make this a default behavior.
There's a clear button and it's also easy to implement it like [this](https://huggingface.co/spaces/hysts-samples/clear-chat-history-when-an-example-is-selected), but I still feel it would be nice if it's supported by default because people usually don't intend to continue the existing chat when they click a new example.

**Comment by abidlabs** [comment]
Not quite relevant after the new chatbot design in 5.0 (correct me if I'm wrong @hysts)
