### ISSUE TITLE
MultimodalTextbox expects a dictionary with optional keys 'text' and 'files'. Received str

### ISSUE THREAD

**Issue by fearocanity** [gradio-app/gradio#8981]
### Describe the bug

Even if i supplied a dictionary, it still says treats as str.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
from gradio_client import Client
dict = {
    "text":"hello there",
    "files":[],
}

# needs to supply {"text":"txt", "files": []} in message
result = client.predict(
                message=dict,
                (...)
                api_name="/chat"
)
```

### Screenshot

n/a

### Logs

```shell
gradio_client.exceptions.AppError: The upstream Gradio app has raised an exception: MultimodalTextbox expects a dictionary with optional keys 'text' and 'files'. Received str
```

### System Info

```shell
gradio_client-1.2.0
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Does this happen with any multimodal chatinterface demo @fearocanity ? What does the upstream application look like?

**Comment by fearocanity** [comment]
> Does this happen with any multimodal chatinterface demo @fearocanity ? What does the upstream application look like?

On my end, yes... I'm trying to use this space:
```
https://huggingface.co/spaces/Quardo/gpt-4o-mini
```
When using the tool itself it works well. But when using the api, it always fails and giving that error.

**Comment by freddyaboulton** [comment]
I think I know what the issue is @fearocanity !

**Comment by fearocanity** [comment]
@freddyaboulton Thanks man!
