### ISSUE TITLE
Display number of tokens per second with ChatInference

### ISSUE THREAD

**Issue by xianbaoqian** [gradio-app/gradio#8985]
- [ x ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

I wonder what is the easiest way to show number of tokens per second with ChatInference. It currently doesn’t allow any additional output. Eagle 2 did so by re-implementing ChatInference. Curious if there is an easy shortcut.

**Describe the solution you'd like**  

Either have special support for tok/s or allow additional output.

**Additional context**

**Comment by abidlabs** [comment]
Related: https://github.com/gradio-app/gradio/issues/7933

**Comment by abidlabs** [comment]
We didn't end up including this as a built-in feature into `gr.ChatInterface` as the number of tokens depends on the tokenizer used and so can't be inferred directly from the resulting text returned to the chat function. However, we do now support additional outputs in `gr.ChatInterface` so you can display any additional information, including token/sec in a separate output component, see https://github.com/gradio-app/gradio/pull/10071
