### ISSUE TITLE
Deprecate (but do not remove) the `type="tuples"` in `gr.Chatbot` and `gr.ChatInterface`

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#9007]
As discussed [internally](https://huggingface.slack.com/archives/C02SPHC1KD1/p1722628790477919), we should deprecate the `type="tuples"` in `gr.Chatbot` and `gr.ChatInterface`. We won't remove it because it would too disruptive, but we'll throw up warnings and change our docs to focus on `type="messages"`, and make that the default in 6.0

Several reasons for this:

1. It will be much easier to educate users on how to use `gr.Chatbot` and `gr.ChatInterface` through our docs. Right now, its kind of a mess since the expected types for the values in `gr.Chatbot` and the predict function in `gr.ChatInterface` change depending on type and multimodal, which makes writing code error-prone
2. We'll be able to develop chat-related much faster going forward since we don't have to support so many development paths
3. Right now, many of our api endpoint types are actually wrong or hopelessly vague because arguments can take so many forms. For example, the /chat endpoint says that it returns a string, but it can actually return a variety of types. Having only the "messages" format will allow us to define a more standard interface for our api endpoints

**Comment by freddyaboulton** [comment]
Handing over to @dawoodkhan82 based on our discussion today

**Comment by abidlabs** [comment]
Closed via #9194

**Comment by A43380** [comment]
Unable to use type="messages" as it is showing ChatInterface.__init__() got an unexpected keyword argument 'type'
