### ISSUE TITLE
Guide 05_chatbots is inconsistent about whether it calls `demo.queue()`

### ISSUE THREAD

**Issue by malcolmsharpe** [gradio-app/gradio#9009]
### Describe the bug

In the guide "Chatbots", section "How to Create a Custom Chatbot with Gradio Blocks", subsection ["Add Streaming to your Chatbot"](https://www.gradio.app/guides/creating-a-custom-chatbot-with-blocks#add-streaming-to-your-chatbot), the example code is inconsistent with the text about whether `demo.queue()` is called:

* The text says "we enable queuing by running `demo.queue()`, which is required for streaming intermediate outputs".
* The example code does not call `demo.queue()`.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Since this is a documentation bug, reproduction is N/A. [Here is the applicable documentation source.](https://github.com/gradio-app/gradio/blob/main/guides/05_chatbots/02_creating-a-custom-chatbot-with-blocks.md)

### System Info

```shell
Since is a documentation bug, system info is N/A.
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
As of Gradio 4.0, queueing is enabled by default, so you no longer need to include it. We'll need to update the Guide. Would you like to open a PR @malcolmsharpe?

**Comment by malcolmsharpe** [comment]
> Would you like to open a PR @malcolmsharpe?

I am brand new to Gradio, so I would not feel confident writing documentation at this point.

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/9376
