### ISSUE TITLE
Live mode doesn't automatically generate output for examples

### ISSUE THREAD

**Issue by NimaBoscarino** [gradio-app/gradio#906]
### Describe the bug

When I have some examples and have set `live=True` for the interface, clicking on the examples doesn't automatically run the function and generate the output. Using inputs, such as sliders, does trigger the live reload properly.

### Reproduction

Here's a Hugging Face space with the described behaviour: https://huggingface.co/spaces/NimaBoscarino/kornia-image-enhancement

### Screenshot

https://www.loom.com/share/3fdf4588509e4cf5b005feeae8748f94

### System Info

```shell
Gradio version 2.9.0
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Thanks, we'll fix this!

**Comment by abidlabs** [comment]
This should be working now in the latest beta release of Gradio (`gradio==2.9.0b2`)

![image](https://user-images.githubusercontent.com/1778297/164075083-0ab94bc5-d302-4777-b71a-2f5999d3ee5c.png)

Thanks for creating the issue @NimaBoscarino!
