### ISSUE TITLE
Gradio Client use modern javascript that isn't always compatible

### ISSUE THREAD

**Issue by OperatoraDiablo** [gradio-app/gradio#9076]
### Describe the bug

I've hacked the API for many endpoints to be able to use it in a web apps because the client library is 1) Heavy and 2) Mostly uncompatible with my up-to-date browser, most of it's code should be compiled to javascript that is executable everywhere in the dist folder, for instance it uses modern operator in the compiled version, operators that are only used for test and experiments such as "??"... It is really annoying to update it, we can't it's not on GitHub...

I need to use [Face](https://huggingface.co/spaces/multimodalart/face-to-all) and I will duplicate the space once we can use the API without reverse-engineering.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
Linux
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @OperatoraDiablo, we are not likely to change the JS Client significantly. However, we also provide a way to query Gradio apps through cURL, which can be ported to other languages more easily. You can read more about this here: https://www.gradio.app/guides/querying-gradio-apps-with-curl

It should be pretty straightforward to convert these requests to the JS equivalent, though you may not have access to everything that the JS Client provides out-of-the-box (e.g. status updates, callbacks, etc.)

cc @hannahblair @pngwn
