### ISSUE TITLE
[`blocks-dev`] Confirm implementation features since divergence from `main`

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#908]
Since `blocks-dev` was created, we've implemented certain features / fixed certain bugs that might not get properly merged when we merge `blocks-dev` into `main`. Specifically, we should confirm that these work post merge:

- [ ] Livestream ASR (@aliabid94)
- [ ] "token-classification" pipeline in `external.py` (@dawoodkhan82)
- [ ] lower-cased labels (@abidlabs)
- [ ] fixed csv injection issue (@abidlabs)
- [ ] fixed webcam flip (@aliabid94)
- [ ] translations (@dawoodkhan82)
- [ ] dark mode (@pngwn)
- [ ] support for absolute filepaths (https://github.com/gradio-app/gradio/pull/1004)
- [x] Image3D component
- [x] Plot component
- [x] Audio output cache

**Comment by pngwn** [comment]
@abidlabs What about theming? This is technically a regression but I think we will only have one theme at launch, is this okay?

**Comment by abidlabs** [comment]
Ah yes I think that is okay! Let’s just make sure to print a helpful message explaining if people try to use a different theme

**Comment by abidlabs** [comment]
@aliabid94 did you verify these all?

**Comment by FarukOzderim** [comment]
@aliabid94 can we close this issue?
