### ISSUE TITLE
gr.HTML Not Supported in description Argument of gradio.Interface

### ISSUE THREAD

**Issue by rajavishah** [gradio-app/gradio#9090]
### Describe the bug

I encountered an issue with the `description` argument in `gradio.Interface`. According to the documentation, the description parameter is supposed to accept Markdown and HTML content. However, when attempting to use gr.HTML for the description, it results in an error because gr.HTML is not a valid type for this parameter.

## Steps to Reproduce
- Import gradio and create an HTML description using gr.HTML.
- Attempt to pass this gr.HTML object to the description argument in gradio.Interface

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

html_description = gr.HTML("<div style='text-align: center'>Centered Description</div>")

interface = gr.Interface(
    fn=my_function,
    inputs=my_inputs,
    outputs=my_outputs,
    description=html_description
)

interface.launch()
```

#### This is the error screenshot:

<img width="1179" alt="Screenshot 2024-08-12 at 12 25 37 PM" src="https://github.com/user-attachments/assets/77b6a7c6-6a84-4d70-a6a1-58b1443fe205">

### System Info

```shell
Gradio Version: 4.36.1
Python Version: 3.10
Operating System: MacOS Sonoma 14.1
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @rajavishah sorry for the confusion, but for this parameter, you simply pass in HTML as a regular Python string and it will be rendered appropriately. You should not be using `gr.HTML` at all.

**Comment by rajavishah** [comment]
> Hi @rajavishah sorry for the confusion, but for this parameter, you simply pass in HTML as a regular Python string and it will be rendered appropriately. You should not be using `gr.HTML` at all.

Thanks @abidlabs, it works fine if I pass it as regular python string :)
