### ISSUE TITLE
Add microphone input to `gr.MultimodalTextbox`

### ISSUE THREAD

**Issue by dawoodkhan82** [gradio-app/gradio#9094]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by abidlabs** [comment]
Perhaps a boolean parameter `mic_input` and then a mic icon shows up next to the file icon?

**Comment by freddyaboulton** [comment]
What about `sources` like we have for `gr.Audio` and `gr.Image` ?

**Comment by abidlabs** [comment]
Oh yeah that’s much better (and future proof)^
