### ISSUE TITLE
How do I prevent updating the inputs immediately after clicking on Examples component

### ISSUE THREAD

**Issue by wow-ww** [gradio-app/gradio#9099]
Upload the file in `gr.MultimodalTextbox` and then click an example in `gr.Examples`. `gr.MultimodalTextbox` will be updated and the previously uploaded file will be overwritten. When `click_example` function is executed, `mul_textbox` variable has its updated value.I want to get the previous value of `gr.MultimodalTextbox`(as inputs) by clicking on `gr.Examples` and (as outputs)the latest value to `gr.MultimodalTextbox`.Instead of immediately updating `gr.MultimodalTextbox`.
Is there any way to do that?
code:
```
import gradio as gr

prompt_list = [[{
    "text": "prompt1",
    "files": []
}], [{
    "text": "prompt2",
    "files": []
}], [{
    "text": "prompt3",
    "files": []
}]]


def click_example(mul_textbox):
    # mul_textbox is already up to date,I want to get the previous value.
    print(f"----clickmul{mul_textbox}")
    return mul_textbox


with gr.Blocks() as demo:
    with gr.Row():
        mul_textbox = gr.MultimodalTextbox(
            interactive=True,
            placeholder="Enter message or upload file...",
            show_label=False)
    with gr.Row():
        with gr.Accordion("Prompt Examples", open=True):
            prompt_examples = gr.Examples(examples=prompt_list,
                                          fn=click_example,
                                          run_on_click=True,
                                          inputs=[mul_textbox],
                                          outputs=[mul_textbox])

demo.launch()
```

**Comment by abidlabs** [comment]
Hi @wow-ww I'm not totally sure what the question is asking, but if you want to store component values and reference them later even after the component's value has changed, you could look into Gradio's sessions state: https://www.gradio.app/guides/state-in-blocks. Anyways, for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
