### ISSUE TITLE
Returning `{}` for a single output results in an update rather than no update

### ISSUE THREAD

**Issue by JohnDuncanScott** [gradio-app/gradio#9109]
### Describe the bug

This relates to https://github.com/gradio-app/gradio/issues/2725.

1. Set up a component so that it has a single output in an array
2. Attempt to not update that component (fast return) by returning `{}`
Expect: Output component is not updated
Actual: Output component is updated to the value "{}"

This bug has multiple parts:
- This type of problem isn't mentioned in https://www.gradio.app/guides/blocks-and-event-listeners#function-input-list-vs-dict and the next section. `inputs` can take a set but `outputs` doesn't support this. There's therefore no way of saying that `outputs` must be a dictionary, so you can't "clarify" to gradio that you definitely meant "no updates" vs "update to the dictionary"
- Returning something else like None, etc. can't be an option because that's a valid value (see the discussion in the linked issue)

The workaround is to return the component input value back to itself instead of using {}. This feels odd because it's a "special case" and is also a surface area for hard to find bugs.

The ask is:
- Allow {} to work when a single output component is specified - this then removes the special case and stops it being a foot gun
- Update the documentation linked above to explicitly mention that returning `{}` should result in no updates to concrete that (this isn't mentioned at all in the docs)

If there's a really good reason this can't be fixed, then at least the docs should be clarified to mention that a single output is a special case. I would suggest a new section on that page titled something like `Not updating any components (fast return)`. You can then use this section to clarify the `{}` and give an example.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Click the button in the below code. The change handler will fire infinitely because `{}` is treated as an update rather than no update. To workaround this, `yield {}` can be changed to `yield textbox_value` so the component's value is returned back to itself, stopping the change handler from firing. As discussed above, this is not intuitive and should be addressed.

```python
from time import sleep
import gradio as gr

with gr.Blocks() as model_test_harness:
    # region Create components
    with gr.Row(variant="panel"):
        textbox = gr.Textbox("Old textbox value")
        button = gr.Button("Click me")

    # endregion

    # region Define handlers
    def textbox_change_handler(textbox_value: str):  # type: ignore
        print("Textbox was changed to: " + textbox_value)
        yield {}

        sleep(2)
        print("Textbox is sentient and decides on a different better value")
        yield "You don't control me!"

    def button_click_handler(textbox_value: str):
        print("Button clicked, old textbox value: " + textbox_value)
        return "Button was clicked"

    # endregion

    # region Register handlers
    textbox.change(textbox_change_handler, inputs=[textbox], outputs=[textbox])
    button.click(button_click_handler, inputs=[textbox], outputs=[textbox])

    # endregion

model_test_harness.launch()  # type: ignore
```

### System Info

```shell
gradio==4.41.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Interesting... the problem here is that `{}` can be a valid value for certain components as well (e.g. `gr.JSON`).

What if we allowed returning a single `gr.skip()` that had this effect instead?

**Comment by abidlabs** [comment]
> If there's a really good reason this can't be fixed, then at least the docs should be clarified to mention that a single output is a special case. I would suggest a new section on that page titled something like Not updating any components (fast return). You can then use this section to clarify the {} and give an example.

I agree with this!

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/9406
