### ISSUE TITLE
Add necessary code to new `@gradio/app` to make it all work (adapt SPA code)

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#9113]
We need to adapt the SPA code for the current gradio app and add it to the full SSR version.

This should be pretty straightforward but we'll want to do the following:

- Load the config + render on the server to make sure everything is actually SSRed.
- Shift any DOM logic to a mounted hook.

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/9412
