### ISSUE TITLE
Add python logic, to use the new SPA when node is available

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#9114]
SHould be the final part of the SSR work:

- Build the SPA and SSR/CSR into the gradio/templates directory for publishing
- Check if node exists + start up a node server running the gradio frontend app
- If no node server the templates as we are now.
- If node, add a proxy to the python server to forward unhandled requests to the node server

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/9412
