### ISSUE TITLE
gr.Audio(sources=["microphone"], streaming=True)    has a big bug

### ISSUE THREAD

**Issue by cjl628-cjl** [gradio-app/gradio#9123]
### Describe the bug

First, I used version 4.15, the function of recording is ok. 
I want to use the "show_progress : 'hidden'" 
I upgrade the version to 4.41.
I found the recording  is wrong. please look at the picture

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

demo = gr.Interface(
    transcribe,
    ["state", gr.Audio(sources=["microphone"],streaming=True)],
    ["state", gr.Text()],
    #["state", "text"],
    #show_progress='hidden',
    live=True,
    )

### Screenshot

![image](https://github.com/user-attachments/assets/82dc7464-79d1-4a3d-921d-8e74d8b23e79)

no sound,but the wave is chaotic

### System Info

```shell
WSL2
Ubuntu-22.04
gradio 4.41
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @cjl628-cjl we've made major changes to streaming in this PR here: https://github.com/gradio-app/gradio/pull/8843

Would you be able to install Gradio from that PR (instructions are in the link) and see if it resolves the issue for you? Otherwise, we'll need more details on what the bug is

**Comment by abidlabs** [comment]
Closing for lack of follow up
