### ISSUE TITLE
UI Error message when passing specific inputs to Spaces app

### ISSUE THREAD

**Issue by rockdrigoma** [gradio-app/gradio#913]
### Describe the bug

We are deploying a automatic translation model with the help of interface.load() method from Gradio at HuggingFace Spaces:

```
import gradio as gr
       
gr.Interface.load(
    "huggingface/hackathon-pln-es/t5-small-spanish-nahuatl",
    inputs=gr.inputs.Textbox(lines=1, label="Input Text"),
    theme="grass",
    title='Spanish to Nahuatl Translation'
    ).launch()
```

## **❌  Error Case**
When giving an input like "mi abuelo se llama Juan", in the Spaces UI instance, it shows an Error message in HuggingFace Spaces instead of expected translated output.

## **✅  1st Success Case**
When trying to reproduce the error by using directly the model from HuggingFace model page, it correctly translates the sentence:

[https://huggingface.co/hackathon-pln-es/t5-small-spanish-nahuatl](https://huggingface.co/hackathon-pln-es/t5-small-spanish-nahuatl)

## **✅  2nd Success Case**
When changing the code to use interface() and passing a function alone called _predict_ instead of load() with Gradio, it correctly translates the sentence.

```
import gradio as gr
from transformers import AutoModelForSeq2SeqLM
from transformers import AutoTokenizer

model = AutoModelForSeq2SeqLM.from_pretrained('hackathon-pln-es/t5-small-spanish-nahuatl')
tokenizer = AutoTokenizer.from_pretrained('hackathon-pln-es/t5-small-spanish-nahuatl')

def predict(input):
  input_ids = tokenizer('translate Spanish to Nahuatl: ' + input, return_tensors='pt').input_ids
  outputs = model.generate(input_ids)
  outputs = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
  return outputs

gr.Interface(
   fn=predict,
   inputs=gr.inputs.Textbox(lines=1, label="Input Text in Spanish"),
   outputs=[
     gr.outputs.Textbox(label="Translated text in Nahuatl"),
     ],
   theme="peach",
   title='🌽 Spanish to Nahuatl Automatic Translation',
   description='This model is a T5 Transformer (t5-small) fine-tuned on 29,007 spanish and nahuatl sentences using 12,890 samples collected from the web and 16,117 samples from the Axolotl dataset. The dataset is normalized using "sep" normalization from py-elotl. For more details visit https://huggingface.co/hackathon-pln-es/t5-small-spanish-nahuatl',
   examples=[
     'hola',
     'conejo',
     'estrella',
     'te quiero mucho',
     'te amo',
     'quiero comer',
     'esto se llama agua',
     'mi abuelo se llama Juan',
     'te amo con todo mi corazón'],
   allow_flagging="manual",
   flagging_options=["right translation", "wrong translation", "error", "other"],
   flagging_dir="logs"
   ).launch(enable_queue=True)

```

### Reproduction

```
import gradio as gr
       
gr.Interface.load("huggingface/hackathon-pln-es/t5-small-spanish-nahuatl", inputs=gr.inputs.Textbox(lines=1, label="Input Text"), theme="grass", title='Spanish to Nahuatl Translation').launch()
```

### Screenshot

# ERROR Case
![gra](https://user-images.githubusercontent.com/5482256/161131413-271ee473-a129-4b49-8b44-96ef7c8ea02b.png)

# SUCCESSFUL Case
![Captura_de_Pantalla_2022-03-31_a_las_10 36 34](https://user-images.githubusercontent.com/5482256/161131479-86125f38-e9ff-4662-bae5-dd9bd4f8ce2b.png)

### System Info

```shell
2.9.0
```

### Severity

critical

**Comment by abidlabs** [comment]
Thank you for the detailed error message @rockdrigoma. I'm looking into this right now.

**Comment by abidlabs** [comment]
Hi @rockdrigoma, I've confirmed that this issue has been fixed in the latest pre-release of Gradio.

![image](https://user-images.githubusercontent.com/1778297/165175931-b61e9526-2a7d-4dc0-b379-6628f193f8cf.png)

If you'd like to try it out, you can wait until Gradio 3.0 comes out in a few weeks, or use the prerelease by installing `pip install gradio==2.9.0b8`.

Working example: https://colab.research.google.com/drive/137D3Kioq6HjcQsuEfrc1f7N6l_Ep5Fcf?usp=sharing

**Comment by rockdrigoma** [comment]
Thank you a lot again @abidlabs. You are really working hard!! Keep that great job!
