### ISSUE TITLE
Scrollbar in gradio chatbot not automatically moving to the bottom after update

### ISSUE THREAD

**Issue by alvelvis** [gradio-app/gradio#9134]
### Describe the bug

I was using version 4.37.1, where the chatbot scrollbar would automatically go to the bottom whenever there's new interaction.

But then I looked for the bugfix you did here #8865, so I updated to 4.39.0, and now the scroll bar won't move to the bottom of the chatbot automatically anymore. I tried the latest release as well. Code for reproduction below.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
with gr.Blocks() as demo:
    chatbot = gr.Chatbot(
                    value=[[None, f"Olá"]],
                    show_label=False,
                    avatar_images=[None, "https://st5.depositphotos.com/72897924/62255/v/450/depositphotos_622556394-stock-illustration-robot-web-icon-vector-illustration.jpg"],
                    likeable=True,
                    )
                
    chatbot.like(lambda x: x, inputs=[chatbot], outputs=None)
    query_input = gr.Textbox(label="Pergunta", placeholder="Digite aqui sua pergunta e então pressione Enter", elem_id="query_input")

    on_submit = lambda y, x: x + [["Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."]]

    submit = {'fn': on_submit, 'inputs':[query_input, chatbot], 'outputs':[chatbot]}
    query_input.submit(**submit)

    gr.Examples(examples=[
        ["a"],
        ["b"],
        ["c"],
        ["d"]], 
    **submit, run_on_click=True, label="Exemplos")

    submit_btn = gr.Button('Try')
    submit_btn.click(**submit)

demo.launch()
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.39.0
gradio_client version: 1.1.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.4.0
fastapi: 0.111.0
ffmpy: 0.3.2
gradio-client==1.1.1 is not installed.
httpx: 0.27.0
huggingface-hub: 0.23.4
importlib-resources: 6.4.0
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.9.1
numpy: 1.26.4
orjson: 3.10.6
packaging: 24.1
pandas: 2.2.2
pillow: 10.4.0
pydantic: 2.8.2
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.5.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.30.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.6.1
httpx: 0.27.0
huggingface-hub: 0.23.4
packaging: 24.1
typing-extensions: 4.12.2
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
cc @dawoodkhan82

**Comment by savvaki** [comment]
I can confirm this is an issue

**Comment by letmaik** [comment]
Confirmed as well. Worked in 4.37.1 and broke with 4.37.2.

**Comment by aliabid94** [comment]
Couldn't reproduce in 5.7.1, can you guys confirm whether or not it still exists as an issue?

What I get:
![Recording 2024-12-03 at 15 56 01](https://github.com/user-attachments/assets/829ec505-0970-4e54-bc3a-b9f7d9013ed2)

Code:
```python
import gradio as gr
with gr.Blocks() as demo:
    chatbot = gr.Chatbot(
                    value=[[None, f"Olá"]],
                    show_label=False,
                    avatar_images=[None, "https://st5.depositphotos.com/72897924/62255/v/450/depositphotos_622556394-stock-illustration-robot-web-icon-vector-illustration.jpg"],
                    likeable=True,
                    )
                
    chatbot.like(lambda x: x, inputs=[chatbot], outputs=None)
    query_input = gr.Textbox(label="Pergunta", placeholder="Digite aqui sua pergunta e então pressione Enter", elem_id="query_input")

    on_submit = lambda y, x: x + [["Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."]]

    submit = {'fn': on_submit, 'inputs':[query_input, chatbot], 'outputs':[chatbot]}
    query_input.submit(**submit)

    gr.Examples(examples=[
        ["a"],
        ["b"],
        ["c"],
        ["d"]], 
    **submit, run_on_click=True, label="Exemplos")

    submit_btn = gr.Button('Try')
    submit_btn.click(**submit)

demo.launch()
```

**Comment by alvelvis** [comment]
> Couldn't reproduce in 5.7.1, can you guys confirm whether or not it still exists as an issue?
> 
> What I get: ![Recording 2024-12-03 at 15 56 01](https://private-user-images.githubusercontent.com/7870876/392174569-829ec505-0970-4e54-bc3a-b9f7d9013ed2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMTc4MDgsIm5iZiI6MTczMzMxNzUwOCwicGF0aCI6Ii83ODcwODc2LzM5MjE3NDU2OS04MjllYzUwNS0wOTcwLTRlNTQtYmMzYS1iOWY3ZDkwMTNlZDIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMTMwNTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTBiNmJmMGE1ZmY1NGVjNjQwZTIwOTIyODEwODRiNjM3OGMyMjFhNTM5ZDFkMjEyNTIxNzAxN2RkZWViMTcwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bqYnsKIVl_vlviHDuu0Ua2Zq5RcBkggKrl4-7zKzdHU) [ ](https://private-user-images.githubusercontent.com/7870876/392174569-829ec505-0970-4e54-bc3a-b9f7d9013ed2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMTc4MDgsIm5iZiI6MTczMzMxNzUwOCwicGF0aCI6Ii83ODcwODc2LzM5MjE3NDU2OS04MjllYzUwNS0wOTcwLTRlNTQtYmMzYS1iOWY3ZDkwMTNlZDIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMTMwNTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTBiNmJmMGE1ZmY1NGVjNjQwZTIwOTIyODEwODRiNjM3OGMyMjFhNTM5ZDFkMjEyNTIxNzAxN2RkZWViMTcwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bqYnsKIVl_vlviHDuu0Ua2Zq5RcBkggKrl4-7zKzdHU) ![Recording 2024-12-03 at 15 56 01](https://private-user-images.githubusercontent.com/7870876/392174569-829ec505-0970-4e54-bc3a-b9f7d9013ed2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMTc4MDgsIm5iZiI6MTczMzMxNzUwOCwicGF0aCI6Ii83ODcwODc2LzM5MjE3NDU2OS04MjllYzUwNS0wOTcwLTRlNTQtYmMzYS1iOWY3ZDkwMTNlZDIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMTMwNTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTBiNmJmMGE1ZmY1NGVjNjQwZTIwOTIyODEwODRiNjM3OGMyMjFhNTM5ZDFkMjEyNTIxNzAxN2RkZWViMTcwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bqYnsKIVl_vlviHDuu0Ua2Zq5RcBkggKrl4-7zKzdHU) [ ](https://private-user-images.githubusercontent.com/7870876/392174569-829ec505-0970-4e54-bc3a-b9f7d9013ed2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMTc4MDgsIm5iZiI6MTczMzMxNzUwOCwicGF0aCI6Ii83ODcwODc2LzM5MjE3NDU2OS04MjllYzUwNS0wOTcwLTRlNTQtYmMzYS1iOWY3ZDkwMTNlZDIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMTMwNTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTBiNmJmMGE1ZmY1NGVjNjQwZTIwOTIyODEwODRiNjM3OGMyMjFhNTM5ZDFkMjEyNTIxNzAxN2RkZWViMTcwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bqYnsKIVl_vlviHDuu0Ua2Zq5RcBkggKrl4-7zKzdHU)
> 
> Code:
> 
> ```python
> import gradio as gr
> with gr.Blocks() as demo:
>     chatbot = gr.Chatbot(
>                     value=[[None, f"Olá"]],
>                     show_label=False,
>                     avatar_images=[None, "https://st5.depositphotos.com/72897924/62255/v/450/depositphotos_622556394-stock-illustration-robot-web-icon-vector-illustration.jpg"],
>                     likeable=True,
>                     )
>                 
>     chatbot.like(lambda x: x, inputs=[chatbot], outputs=None)
>     query_input = gr.Textbox(label="Pergunta", placeholder="Digite aqui sua pergunta e então pressione Enter", elem_id="query_input")
> 
>     on_submit = lambda y, x: x + [["Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."]]
> 
>     submit = {'fn': on_submit, 'inputs':[query_input, chatbot], 'outputs':[chatbot]}
>     query_input.submit(**submit)
> 
>     gr.Examples(examples=[
>         ["a"],
>         ["b"],
>         ["c"],
>         ["d"]], 
>     **submit, run_on_click=True, label="Exemplos")
> 
>     submit_btn = gr.Button('Try')
>     submit_btn.click(**submit)
> 
> demo.launch()
> ```

Hi! In version 5.7.1 now it works fine! I'll be updating to this one.

Thanks a lot.

**Comment by git-hamza** [comment]
@aliabid94 Don't you think that itself is a bug what you posted, why do we have two scroll bars. I am having that issue with gradio 5.9.1 where when something is processing in chatbot, suddenly two scroll bar appears.

**Comment by PauloCraveiro** [comment]
> [@aliabid94](https://github.com/aliabid94) Don't you think that itself is a bug what you posted, why do we have two scroll bars. I am having that issue with gradio 5.9.1 where when something is processing in chatbot, suddenly two scroll bar appears.

i am having this issue atm. can't figure a way to go around it.

**Comment by dawoodkhan82** [comment]
@PauloCraveiro Should be fixed by this PR (https://github.com/gradio-app/gradio/pull/11229). You can pip install from instruction in the PR or wait for the next release, which will be soon.
