### ISSUE TITLE
Replace buttons in `gr.ChatInterface` with icons on the messages instead

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#9141]
Remove the buttons and instead replace them with the retry/delete icons next to individual messages that appear when you over the message  for a cleaner, more standard UI.

[internal discussion](https://huggingface.slack.com/archives/C03BHNJCBC4/p1723763151696169)

**Comment by Kathanaboina** [comment]
![123](https://github.com/user-attachments/assets/a2ab9887-27c5-4e56-ab63-e96dda3dc580)
how to remove that share icon

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/9201
