### ISSUE TITLE
Several bugs/questions related to `gr.Video`

### ISSUE THREAD

**Issue by juntaosun** [gradio-app/gradio#9143]
### Describe the bug

Thanks for such a wonderful project.
But I encountered some confusion when using gr.Video. It didn't work properly.
(1) Question 1: When I dragged a video mp4 file into the gr.Video component, I found that it was uploaded to a cache location of gradio before it started to display. If the mp4 file is large (such as 2G), this waiting process usually takes a long time. Is there a faster way?
```
C:\Users\...\AppData\Local\Temp\gradio\........mp4
```
![temp](https://github.com/user-attachments/assets/021ca99b-d8e7-4658-9051-dc9739614272)
It will keep occupying the cache. When will the cache be cleared?

(2) Question 2: Sometimes it doesn't play after dragging it in successfully.（NaN）， I have to refresh the page and drag it in again. This happens frequently, which makes me confused when using it.
![gr Video](https://github.com/user-attachments/assets/09e8ebd3-efaf-411c-9493-ff881da16098)

(3) Question 3: Usually you need to process each frame of the picture, which means you need to use cv2 to read the video address again. Can this gr.Video component return real-time picture Image data? Without the need to use cv2 to read the mp4 video file again to render the picture.

(4) Question 4: gradio often displays a disconnection prompt in the console. Can I set it to block these messages? It actually does not affect the function.
```
\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host.
```

Is there a plan to solve the above problems? Thank you again~

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

gr.Video()
```

### System Info

```shell
win11,python 3.8 , INSTALLED: 4.41.0
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @juntaosun !

> (3) Question 3: Usually you need to process each frame of the picture, which means you need to use cv2 to read the video address again. Can this gr.Video component return real-time picture Image data? Without the need to use cv2 to read the mp4 video file again to render the picture.

What do you mean by this? I don't think it makes sense for gradio to send video frames as separate images because sound will be lost. 

> For the display mechanism of the same gr.Image component, the cache file name it obtains should be unique.

The hash is based on the contents of the file. It wouldn't make sense to overwrite the same file in the general case but I think there should be a way for the developer to willingly overwrite the same filename or skip saving to file by using base64 or something.

**Comment by abidlabs** [comment]
Hi @juntaosun, for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue). If you have specific feature requests, please create separate issues for each feature request, clearly explaining the motivation and providing example code. Thanks!

**Comment by lolpa1n** [comment]
Was the 2nd question resolved? My video either doesn't start loading or NaN appears
