### ISSUE TITLE
Adding `max_length` parameter to `gr.TextBox()`

### ISSUE THREAD

**Issue by WH-Yoshi** [gradio-app/gradio#9145]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
No problem related, just a useful feature in my opinion.

**Describe the solution you'd like**  
The "solution" could be useful for some people, such as me :)
My request is a parameter that applies a maximum of characters we can put into an interactive textbox.
I tried with event listeners but the component refreshes at every character we put so it becomes quite a mess.
I know that HTML as a built-in maxlenght attribute, maybe add this one to the textarea if we ask for the parameter?

**Additional context**  
Can't type 10 here thanks to `maxlenght="20"` in `<textarea>`
![image](https://github.com/user-attachments/assets/5d16c68a-1836-46e1-b428-3ff9ab869434)

**Comment by abidlabs** [comment]
Hi @WH-Yoshi makes sense. We could add this to our roadmap, though it'll likely take time as we are focused on other things at the moment. Would like to open a PR for this? If so, we are happy to review and provide feedback

**Comment by WH-Yoshi** [comment]
I'm happy to help

**Comment by WH-Yoshi** [comment]
HI @abidlabs, I'm reading the source code and I'm trying to figure out how everything works. I found the svelte file and modified it to try it, but I might need a "first steps" to test it locally. Thanks !

**Comment by abidlabs** [comment]
To test it locally, you can run `pnpm dev` to run the frontend server in reload mode. See here: https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md#-run-a-gradio-app -- lmk if you have any questions!

**Comment by WH-Yoshi** [comment]
Sorry to come again, I found how to change the web page thanks to a svelte parameter, if I put a default value on Textbox.svelte it works. Now, I was searching to understand how the python textbox component would communicate its values with the svelte component, I couldn't find anything besides a certain `api_info` in the many Typescripts, that seems to work as an intermediary between the two languages. Do you have any clues to give?

**Comment by abidlabs** [comment]
Great question @WH-Yoshi -- if you add a parameter in the component's Python `gr.Textbox` constructor, then it will automatically be passed into the Svelte component as a prop
