### ISSUE TITLE
Image size fills the entire chatbot UI

### ISSUE THREAD

**Issue by BabyChouSr** [gradio-app/gradio#9159]
### Describe the bug

![image](https://github.com/user-attachments/assets/e88f4298-25cc-4481-bd2c-273ab69413df)
The image in the chatbot tab fills the entire space. The left one is the previous UI `gradio==4.36.1` and the right one is the new one `gradio==4.41.0`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

n/a

### System Info

```shell
`gradio==4.41.0`
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @BabyChouSr! And you're also seeing an issue around indentations of list items?

**Comment by abidlabs** [comment]
Would you be able to provide us a minimal code snippet for us to reproduce the issue? We are having a hard time reproing on our end (cc @hannahblair)

**Comment by dawoodkhan82** [comment]
@BabyChouSr @abidlabs I was able to reproduce this issue, when supplying an image to the chatbot via markdown. I'm assuming that's what's being shown in the screenshot.
