### ISSUE TITLE
Update gr.Dataframe docs to mention that a gr.Dataframe instance retains it's original index order even if the dataframe is sorted in the UI

### ISSUE THREAD

**Issue by dwipper** [gradio-app/gradio#9179]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Please update the https://www.gradio.app/docs/gradio/dataframe

**Describe the solution you'd like**  
The docs should clarify that if the dataframe is sorted in the UI using the Column Header arrows, that this doesn't change the original order of the data in the dataframe instance. When the DF instance is passed to a function, functions like df.ait(index_num) will return data in the original order, not the sorted order shown in the UI.

If the dataframe is programmatically sorted, and that instance is passede to the function, then the sort order/index would be based on that, and not the original order.

**Additional context**  
[Add any other context or screenshots about the feature request here.](https://github.com/gradio-app/gradio/pull/9128)

**Comment by abidlabs** [comment]
Thanks @dwipper I do agree -- would you like to open a PR and make a comment here? https://github.com/gradio-app/gradio/blob/d1f044145ae93e5838042d9fb25f4f17def9c774/gradio/components/dataframe.py#L199

**Comment by dwipper** [comment]
@abidlabs Glad to help, but I don't know how to open a PR. I've read some of the docs on it, but it's still not clear what/how/where to do it.....

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/9376
