### ISSUE TITLE
Set the max_threads=1,but when I run the webui,it comes out more than 3 thread:"MainThread","Thread-4 (run)","AnyIO worker thread".

### ISSUE THREAD

**Issue by HarlieGirl** [gradio-app/gradio#9183]
### Describe the bug

define demo.launch(server_port=7861, debug=True, **max_threads=1**)
I observe that every time run into my functions, the current thread usually be the "**AnyIO worker thread**",it will cause following ERRORs:
1. raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'AnyIO worker thread'
2. ValueError: signal only works in main thread of the main interpreter

I want to limit only MainThread, so the above errors can be resolved. Why the max_threads not work and the other threads can be created. And if I want to prcess my function in MainThread,how can i modify the code？

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

if __name__ == "__main__":
    demo.launch(server_port=7861, debug=True, max_threads=1)

### Logs

```shell
ic| f"Before launch: Active Threads - {threading.active_count()}": 'Before launch: Active Threads - 3'
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
ic| threading.current_thread(): <WorkerThread(AnyIO worker thread, started daemon 13868)>
ic| threading.active_count(): 3
ic| thread.name: 'MainThread'
ic| thread.name: 'Thread-4 (run)'
ic| thread.name: 'AnyIO worker thread'
```

### System Info

```shell
Windows 11
Python 3.11.9
gradio 4.42.0
```

### Severity

My project blocked by this issue

**Comment by abidlabs** [comment]
Hi @HarlieGirl there is not enough information in this thread to reproduce. I'm not sure if you are running a specific webui or this error affects all Gradio apps. If its the former, please open this issue on that webui, if its the latter, please provide a minimal Gradio app to reproduce. Thanks! I'll close until we have a suitable repro

**Comment by lambdaxai** [comment]
The cause of this problem may be that you're using nest-asyncio to patch python's asyncio lib, because gradio defaults to using loop='auto' in the class uvicorn.config.Config, with loop='auto', uvicorn replaces asyncio's event_loop_policy, causing get_event_loop to report an error.

Solution: Add the following code before app.lunch() to replace the original policy:
```
import uvicorn

uvicorn.config.LOOP_SETUPS = {
    “none": None,
    “auto": ‘uvicorn.loops.asyncio:asyncio_setup’,
    “asyncio": ‘uvicorn.loops.asyncio:asyncio_setup’,
    “uvloop": ‘uvicorn.loops.uvloop:uvloop_setup’,
}
```
