### ISSUE TITLE
Allow for markdown in `info=`

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#9193]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I would like to include link/references in `info=`

**Describe the solution you'd like**  
Let `info=` render markdown

**Additional context**  
Can't think of a downside here

Currently this is what happens:
<img width="522" alt="image" src="https://github.com/user-attachments/assets/fdca4bdc-949c-47e7-b171-b180271331f6">

An alternative would be using `gr.Group`, but check out how it renders: 
<img width="531" alt="image" src="https://github.com/user-attachments/assets/1aa6ab39-8bac-446a-b91f-d8afe1bd0bab">
```py
with gr.Group():
  custom_lora = gr.Textbox(label="Custom LoRA", info="Insert a Hugging Face path for your custom LoRA", placeholder="multimodalart/vintage-ads-flux")
  gr.Markdown("[Check the list of FLUX LoRas](https://huggingface.co/models?other=base_model:adapter:black-forest-labs/FLUX.1-dev)")
```

**Comment by abidlabs** [comment]
Closed via #9521
