### ISSUE TITLE
PDF Component change Event Fires Twice

### ISSUE THREAD

**Issue by Jocelyne-Smith** [gradio-app/gradio#9195]
### Describe the bug

The change event listener for the PDF component in Gradio appears to be firing twice when a file is uploaded. 

I tried the same code with the File component and it only fires once. Please see attached video.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python

import gradio as gr
from gradio_pdf import PDF

state = gr.State(False)

with gr.Blocks() as app:
    btn = gr.Button("Button", interactive=False)

    def file_change():
        print(state.value)
        state.value = not state.value
        print(state.value)
        return gr.update(interactive=state.value)

    file = PDF(label="Specifications (.pdf)", interactive=True)
    
    file.change(fn=file_change, outputs=btn)

if __name__ == "__main__":
    app.launch()

```

### Screenshot

https://github.com/user-attachments/assets/e581c8dc-dce8-4daa-b815-e7430c83eb22

### System Info

```shell
'Gradio: 4.42.0'
'gradio-pdf: 0.0.13'
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @Jocelyne-Smith  - I can take a look but please file the issue in this repo instead!

https://github.com/freddyaboulton/gradio-pdf/issues
