### ISSUE TITLE
Add flagging functionalities to ChatInterface

### ISSUE THREAD

**Issue by lopozz** [gradio-app/gradio#9198]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I've been experimenting with various LLMs using gradio as interface. Frequently I need to write down notes about what the model is doing well and what not. To speed up the analysis it would be handy to be able to save the conversation into a csv using a Flag button (similarly to the Interface class https://github.com/gradio-app/gradio/blob/4a8555921980a30d2621c5eb7d6700704f2561ab/gradio/interface.py#L41) 

**Describe the solution you'd like**  
I've been working on such an interface and created a new interface that inherits from ChatInterface but with these additional parameters:
```
allow_flagging: one of "never", "auto", or "manual". If "never" or "auto", users will not see a button to flag an input and output. If "manual", users will see a button to flag. If "auto", every input the user submits will be automatically flagged, along with the generated output. If "manual", both the input and outputs are flagged when the user clicks flag button. This parameter can be set with environmental variable GRADIO_ALLOW_FLAGGING; otherwise defaults to "manual".
flagging_options: if provided, allows user to select from the list of options when flagging. Only applies if allow_flagging is "manual". Can either be a list of tuples of the form (label, value), where label is the string that will be displayed on the button and value is the string that will be stored in the flagging CSV; or it can be a list of strings ["X", "Y"], in which case the values will be the list of strings and the labels will ["Flag as X", "Flag as Y"], etc.
flagging_dir: what to name the directory where flagged data is stored.
flagging_callback: either None or an instance of a subclass of FlaggingCallback which will be called when a sample is flagged. If set to None, an instance of gradio.flagging.CSVLogger will be created and logs will be saved to a local CSV file in flagging_dir. Default to None.
``` 
This is what it would look like:
![Screenshot from 2024-08-27 14-48-10](https://github.com/user-attachments/assets/17cb6db3-0979-43f1-b31c-d9e0d75ba672)

The solution would then allow to save the whole conversation visible on screen and attach an optional comment to it. Using the CSVLogger out-of-the-box everything would then be stored into a csv. The only limitation is that ```auto``` of the ```allow_flagging``` parameter has not been implemented yet. All other functionalities are supported. For reference I leave the link to the documentation dealing with Flagging (https://www.gradio.app/guides/using-flagging)

If this is helpful, I could open a PR and share the code.

**Comment by abidlabs** [comment]
Thanks @lopozz! This is pretty cool but we’ve intentionally streamlined the UI for Gradio 5.0 and have removed all of the buttons so I don’t think this makes sense any longer. Appreciate the offer though and I hope you will continue contributing in other ways
