### ISSUE TITLE
Remove Deprecated Parameters

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#920]
We shall remove deprecated function parameters with 3.0 release.

**Comment by FarukOzderim** [comment]
Now that we are getting close to the 3.0 release, It would be nice to clean deprecated parameters from function parameters and signatures.

Do we still want to give deprecation warnings to users? Could we get rid of them without further deprecation notice? I suppose not :D

If that the case we could create a deprecation map like this to make code cleaner, WDYT guys?
```
DEPRECATED_FIELD_MAP = {
    "interface": {
        "init": {
            "verbose": "Warning! verbose parameter is deprecated.",
            "capture_session": "",
            "allow_screenshot": "",
            "encrypt": "",
            "show_tips": "",
            "enable_queue": "Warning! enable_queue parameter is deprecated, please use it inside launch() instead",
            "api_mode": "",
        }
    }
}
```

```
for kwarg in kwargs:
  if kwarg in DEPRECATED_FIELD_MAP["interface"]["init"]:
    raise DeprecationWarning(DEPRECATED_FIELD_MAP["interface"]["init"][kwarg])
```

**Comment by FarukOzderim** [comment]
This is the current version of the codebase, which is quite dirty and long.

https://github.com/gradio-app/gradio/blob/main/gradio/interface.py#L105-L619

**Comment by abidlabs** [comment]
> Do we still want to give deprecation warnings to users? Could we get rid of them without further deprecation notice? I suppose not :D

I think we can finally remove them without further warnings, as we have been warning about deprecation for several months now (not to mention that 3.0 represents a whole new version). cc @aliabid94 to get your thoughts as well

**Comment by aliabid94** [comment]
This is nice. I think a DeprecationWarning error is good, and needed especially for parameters that have moved back and forth between Interface constructor and launch methods, like enable_queue

**Comment by FarukOzderim** [comment]
We could use Abubakar's suggestion of using `kwargs.pop` for deprecation notice as well.
We would just drop a warning for unused kwarg arguments. It would help both to
- having typos in kwargs arguments
- warning notice to unused arguments(user would understand the argument is not working like that)

>It looks one approach is to "pop kwargs" as you use them and before passing them into the parent class.
And in the ultimate parent class make sure kwargs is of length 0, meaning that there are no unused parameters
Here's an example: https://github.com/kevinjqiu/btsync.py/issues/10#issuecomment-40255093

If we want to we would print out info using a dictionary like this as well
```
DEPRECATED_FIELD_MAP = {
  "enable_queue": "enable_queue is expected to be used within launch()"
} 
```

**Comment by abidlabs** [comment]
Also, removing deprecated tests: I think we can safely remove `test_inputs.py` and `test_outputs.py` before launch

**Comment by FarukOzderim** [comment]
> Also, removing deprecated tests: I think we can safely remove `test_inputs.py` and `test_outputs.py` before launch

Do you think the input and output components are tested enough by users. Will remove if it is.
