### ISSUE TITLE
Add autofocus for gr.Chatbot

### ISSUE THREAD

**Issue by jhpark-upstage** [gradio-app/gradio#9211]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Currently, both gr.Textbox and gr.ChatInterface components have an autofocus option. However, the gr.Chatbot component does not have this option.

**Describe the solution you'd like**  
I would like the gr.Chatbot component to support an autofocus option, similar to the existing functionality in gr.Textbox and gr.ChatInterface.

**Screenshot**
<img width="984" alt="image" src="https://github.com/user-attachments/assets/edf2aa31-92e3-4ee2-83c5-765a9b037528">
<img width="966" alt="image" src="https://github.com/user-attachments/assets/1d4daac7-ab71-44aa-8d54-b467484de908">

**Comment by abidlabs** [comment]
Hi @jhpark-upstage what do you mean by adding autofocus to gr.Chatbot? The gr.Chatbot component does not accept input, so it can't be focused. Can you clarify what you mean?

**Comment by jhpark-upstage** [comment]
The gr.Chatbot component does not accept input directly, but it can be modified by other components, such as gr.Textbox. When the change causes new text to go out of the chatbot's viewable range, I need to autofocus on the new user or assistant text. If I use gr.ChatInterface, I can simply set autofocus=True in the parameters, but for gr.Chatbot, I can't."

**Comment by abidlabs** [comment]
Oh I see, you mean scroll to the bottom when new messages arrive. Yes, that's something we can do, its been requested here: https://github.com/gradio-app/gradio/issues/8253, so I'll mark this as a duplicate
