### ISSUE TITLE
Running local URL, but not responding to Chrome browser

### ISSUE THREAD

**Issue by zydjohnHotmail** [gradio-app/gradio#922]
### Describe the bug

Hello:
I am using Windows 10 (Version 21H2), my python version is: 3.9.7 (x64), I installed Gradio (version 2.9.1), but I can't use GPU, as my Graphic card (Nvidia Gefore GT1030) is too weak to run any CUDA operations.
I write a simple python code: hello.py as the following:
import gradio as gr
def greet(name):
    return "Hello " + name + "!!"

iface = gr.Interface(fn=greet, inputs="text", outputs="text")
iface.launch()

When I run it, it show:
F:\Python\GAN3\gradio>python hello.py
Running on local URL:  http://127.0.0.1:7860/

To create a public link, set `share=True` in `launch()`.

But when I use Google Chome (Version 100.0.4896.60 (Official Build) (64-bit)) to visit http://127.0.0.1:7860/, nothing has shown.

### Reproduction

C:\WINDOWS\system32>python --version
Python 3.9.7

C:\WINDOWS\system32>pip show gradio
WARNING: Package(s) not found: gradio

C:\WINDOWS\system32>pip install gradio
Collecting gradio
........
C:\WINDOWS\system32>pip show gradio
Name: gradio
Version: 2.9.1
Summary: Python library for easily interacting with trained machine learning models
Home-page: https://github.com/gradio-app/gradio-UI
Author: Abubakar Abid, Ali Abid, Ali Abdalla, Dawood Khan, Ahsen Khaliq
Author-email: team@gradio.app
License: Apache License 2.0
Location: c:\program files\python39\lib\site-packages
Requires: aiohttp, analytics-python, fastapi, ffmpy, markdown-it-py, matplotlib, numpy, orjson, pandas, paramiko, pillow, pycryptodome, pydub, python-multipart, requests, uvicorn
Required-by:

F:\Python\GAN3\gradio>type hello.py
import gradio as gr
def greet(name):
    return "Hello " + name + "!!"

iface = gr.Interface(fn=greet, inputs="text", outputs="text")
iface.launch()
F:\Python\GAN3\gradio>

F:\Python\GAN3\gradio>python hello.py
Running on local URL:  http://127.0.0.1:7860/

To create a public link, set `share=True` in `launch()`.

### Screenshot

![GradioNOK](https://user-images.githubusercontent.com/45263518/161519337-82cd9476-ebe4-49de-9c05-99f85e020ac3.png)

### System Info

```shell
Gradio: 2.9.1
OS: Windows 10
Browser: Google Chrome Version 100.0.4896.60 (Official Build) (64-bit)
```

### Severity

annoyance

**Comment by cgsaxner** [comment]
Hi, did you manage to solve this? 
I'm running into the same issue using Gradio 2.9.1, Python 3.9.7 and Windows 10. 
I tested visiting [http://127.0.0.1:7860/](http://127.0.0.1:7860/) or [http://localhost:7860/](http://localhost:7860/) using Chrome, Firefox and Microsoft Edge, but the page keeps coming up empty.

**Comment by abidlabs** [comment]
Hmm this is weird. Do you notice any logs in the Python terminal or in the Chrome inspector console?

**Comment by zydjohnHotmail** [comment]
Hello:
I am using Python 3.9.7 on Windows 10 (Version 21H2).  After you publich new version, please give me the link, I can try again!

**Comment by zydjohnHotmail** [comment]
Hello:
I forget to mention that I don't have GPU, or my Graphic card Nvidia Gefore GT1030 is too weak to run any CUDA stuff.  It is better to make sure that I can run the program on CPU only.
Thanks,

**Comment by cgsaxner** [comment]
> Hmm this is weird. Do you notice any logs in the Python terminal or in the Chrome inspector console?

Hello, I got the following error in the Chrome console when loading the page:

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

Firefox shows a similar message:
`Loading module from “http://127.0.0.1:7860/assets/index.f609cd21.js” was blocked because of a disallowed MIME type (“text/plain”).`

(see also screenshots below)

Unfortunately, I know nothing about web development so I don't really understand what's wrong and whether it has to do with my local settings or is a bug.

Chrome:
![image](https://user-images.githubusercontent.com/29651139/163119495-1d14780a-cf09-479d-8300-f6b67b7e3ba5.png)

Firefox:
![image](https://user-images.githubusercontent.com/29651139/163120817-33997b51-10d6-492d-af76-a9caeed1e56a.png)

**Comment by abidlabs** [comment]
Hi @zydjohnHotmail @cgsaxner can you guys try installing a beta release of Gradio: `pip install gradio==2.9b8` and see if this works for you?

**Comment by zydjohnHotmail** [comment]
Hello:
I can install the beta release of Gradio, and when I use Google Chrome (Version 100) to browse http://127.0.0.1:7860/
I can submit some text, like: "World", I can see the output is: "Hello World".
But let me know how to generate some images.  
The following is the command line output:
F:\Python\GAN3\gradio>pip show gradio
Name: gradio
Version: 2.9.0b8
Summary: Python library for easily interacting with trained machine learning models
Home-page: https://github.com/gradio-app/gradio-UI
Author: Abubakar Abid, Ali Abid, Ali Abdalla, Dawood Khan, Ahsen Khaliq, Pete Allen, Ömer Faruk Özdemir
Author-email: team@gradio.app
License: Apache License 2.0
Location: c:\program files\python39\lib\site-packages
Requires: aiohttp, analytics-python, fastapi, ffmpy, Jinja2, markdown-it-py, matplotlib, numpy, orjson, pandas, paramiko, pillow, pycryptodome, pydub, python-multipart, requests, uvicorn
Required-by:

F:\Python\GAN3\gradio>dir
 Volume in drive F is Disk8T
 Volume Serial Number is 5030-0BF0

 Directory of F:\Python\GAN3\gradio

04/04/2022  11:38 AM    <DIR>          .
04/04/2022  11:38 AM    <DIR>          ..
04/04/2022  11:38 AM    <DIR>          flagged
04/04/2022  11:38 AM               153 hello.py
               1 File(s)            153 bytes
               3 Dir(s)  5,033,110,925,312 bytes free

F:\Python\GAN3\gradio>python hello.py
Running on local URL:  http://127.0.0.1:7860/
Is there still some bug?
Refer to attached image for output.
![GradioBeta](https://user-images.githubusercontent.com/45263518/164531006-c2e9970c-9913-4c31-898a-93ed3c03f9e4.png)

**Comment by abidlabs** [comment]
Great, it looks like the issue has been solved. We are working on an official release, which will happen in the next few weeks. In the meantime, you can use this beta release, but keep in mind that things may continue to change.

For your questions, please check out our Getting Started: https://gradio.app/getting_started/
