### ISSUE TITLE
gradio imageeditor to generate output in 'background', 'layers', 'composite'

### ISSUE THREAD

**Issue by jeevitesh** [gradio-app/gradio#9220]
Hi,
Need standalone gradio imageeditor program output in the following format 
Output 1 format

`{  'background': <PIL.Image.Image image mode=RGBA size=768x1024 at 0x7FE8A97D9D80>,   'layers': [<PIL.Image.Image image mode=RGBA size=768x1024 at 0x7FE8A97D8A90>],  'composite': <PIL.Image.Image image mode=RGBA size=768x1024 at 0x7FE8A97D8C40>}.`

Program which we have tried

>  from image_editor import ImageEditor

>  img=ImageEditor(value='00260_00.jpg', type="filepath", label='Human Images select/Upload', interactive=False,min_width = 250 )

>   print(img)

 

OutPut 2 Format but above program returning result in the below format.
`<image_editor.ImageEditor object at 0x7f6dd494cbe0>`

But we need output in output1 format, kindly let us know how to achieve the below output in the format 
`{  'background': <PIL.Image.Image image mode=RGBA size=768x1024 at 0x7FE8A97D9D80>,   'layers': [<PIL.Image.Image image mode=RGBA size=768x1024 at 0x7FE8A97D8A90>],  'composite': <PIL.Image.Image image mode=RGBA size=768x1024 at 0x7FE8A97D8C40>}.`

**Comment by missionfloyd** [comment]
See here:
https://www.gradio.app/guides/quickstart#building-your-first-demo

```python
import gradio as gr

def process(img):
    print(img)

demo = gr.Interface(
    fn=process,
    inputs=[gr.ImageEditor(type="pil")],
    outputs=None
)

demo.launch()
```

**Comment by jeevitesh** [comment]
Hi sir,
Thanks for the helping hand. Read the link and modified the program to use interface. but still not able to generate the file in the following format 
`{  'background': <PIL.Image.Image image mode=RGBA size=768x1024 at 0x7FE8A97D9D80>,   'layers': [<PIL.Image.Image image mode=RGBA size=768x1024 at 0x7FE8A97D8A90>],  'composite': <PIL.Image.Image image mode=RGBA size=768x1024 at 0x7FE8A97D8C40>}`

Please help me to achieve the format as mentioned above for a given image. 

Modified Program is as follows

`
from image_editor import ImageEditor
import gradio as gr

img=ImageEditor(value='00260_00.jpg', type="pil")

image_list = []
ex_dict= {}
ex_dict['background'] = img
ex_dict['layers'] = None
ex_dict['composite'] = None
image_list.append(ex_dict)


example = gr.Examples(
                inputs=img,
                examples_per_page=1,
                examples=image_list
            )
print("example ", example)

print("IMAGE ", img)

`
Getting error ValueError: Cannot process this value as an Image

**Comment by missionfloyd** [comment]
You can't read `img` directly like that; it's the image input itself, not the uploaded image.

It has to be passed to a function. See the example I posted above.

**Comment by abidlabs** [comment]
Thanks @missionfloyd for addressing this question!
