### ISSUE TITLE
I don't want to convert uploaded image to image_mode forcedly when using Gradio.Image

### ISSUE THREAD

**Issue by GeeMoose** [gradio-app/gradio#9222]
Gradio.Image component has image_mode parameters to force uploaded image to convert RGB\RGBA and etc, if I want to keep raw image mode, how should I do? if image_mode can add a option, I think it is useful.

**Comment by abidlabs** [comment]
Thanks @GeeMoose, this makes sense to me. We could allow `image_mode` to take a `None` value in which case its inferred from the file itself. Would you like to open a PR for this?

**Comment by GeeMoose** [comment]
if gradio organization allows, I am glad to do it.

**Comment by abidlabs** [comment]
Yes, please go for it! Happy to review once the PR is open

**Comment by abidlabs** [comment]
The main file to edit would be: https://github.com/gradio-app/gradio/blob/41d5ab987ba9728753be4509490c79041655809b/gradio/components/image.py

**Comment by GeeMoose** [comment]
I found that the change did not pass the rule check.
