### ISSUE TITLE
[Theme Builder] - Change 'Tab item' background colour

### ISSUE THREAD

**Issue by elismasilva** [gradio-app/gradio#9226]
- [yes] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I want to be able to change the background color of the tab item element. It is taking on the background color that I assigned to the main background. I painted the desired area in green in the image to illustrate.

**Additional context**  
![image](https://github.com/user-attachments/assets/ed54dd42-990f-4504-b80a-20a4105b8c7a)

**Comment by abidlabs** [comment]
Hi @elismasilva if there's a particular element that cannot be styled using the theme editor, you can target it with custom css and javscript, see: https://www.gradio.app/guides/custom-CSS-and-JS

**Comment by elismasilva** [comment]
> Hi @elismasilva if there's a particular element that cannot be styled using the theme editor, you can target it with custom css and javscript, see: https://www.gradio.app/guides/custom-CSS-and-JS

Yes, I solved it using CSS. Since I built the theme in the theme builder, I didn't see a property to change there. If this functionality hasn't been discontinued, I thought it would be interesting to have this property there, because if I publish my theme it will be incomplete since I needed to add many things to the local CSS.
