### ISSUE TITLE
Fix ChatInterface Cached Examples

### ISSUE THREAD

**Issue by dawoodkhan82** [gradio-app/gradio#9231]
### Describe the bug

Since using `suggestions` in chat interface. Cached examples was not implemented.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
n/a
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/8966
