### ISSUE TITLE
Model3D uses a really old version of Babylon.js

### ISSUE THREAD

**Issue by freealise** [gradio-app/gradio#9238]
The version displayed is [4.2.1](https://github.com/search?q=repo%3Agradio-app%2Fgradio%20babylon&type=code) and the latest is currently 7.
This produces results different from those when developing with Babylon.js locally.

Please update!

**Comment by abidlabs** [comment]
Seems like we could do this in 5.0 @hannahblair @dawoodkhan82?

**Comment by abidlabs** [comment]
@freealise can you give an example of what different results are produced?

**Comment by freealise** [comment]
When I load a skydome from the client (with Javascript), its texture is reversed.

**Comment by abidlabs** [comment]
Would you like to open a PR updating the version of babylon.js @freealise?

**Comment by abidlabs** [comment]
Closed via #9377
