### ISSUE TITLE
Strange UI Design?

### ISSUE THREAD

**Issue by phemw** [gradio-app/gradio#9239]
### Describe the bug

Context: I have just come back to using gradio (awesome library, so much has changed!) after a roughly 1 year hiatus.

This post is regarding one of the UI changes that introduced a padded bar to the right-side of each component. I am not sure what the reason behind this design choice is, but it looks a bit strange, especially with nested components. It also looks off in dark mode since the padded bar is a white color.

I have isolated the problem to

```css
.block {
    overflow-y: scroll!important
}
```

in `Index-DXhISdnP.css`. How can I override the css so I can remove the `!important` keyword?

Are there any easy workarounds to remove these padded bars? Thanks in advance!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Code snippet from: [Toy Calculator](https://www.gradio.app/playground?demo=Blank&code=ZnJvbSB6aXBmaWxlIGltcG9ydCBaaXBGaWxlCgppbXBvcnQgZ3JhZGlvIGFzIGdyCgpkZWYgemlwX3RvX2pzb24oZmlsZV9vYmopOgogICAgZmlsZXMgPSBbXQogICAgd2l0aCBaaXBGaWxlKGZpbGVfb2JqLm5hbWUpIGFzIHpmaWxlOgogICAgICAgIGZvciB6aW5mbyBpbiB6ZmlsZS5pbmZvbGlzdCgpOgogICAgICAgICAgICBmaWxlcy5hcHBlbmQoCiAgICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgIm5hbWUiOiB6aW5mby5maWxlbmFtZSwKICAgICAgICAgICAgICAgICAgICAiZmlsZV9zaXplIjogemluZm8uZmlsZV9zaXplLAogICAgICAgICAgICAgICAgICAgICJjb21wcmVzc2VkX3NpemUiOiB6aW5mby5jb21wcmVzc19zaXplLAogICAgICAgICAgICAgICAgfQogICAgICAgICAgICApCiAgICByZXR1cm4gZmlsZXMKCmRlbW8gPSBnci5JbnRlcmZhY2UoemlwX3RvX2pzb24sICJmaWxlIiwgImpzb24iKQoKaWYgX19uYW1lX18gPT0gIl9fbWFpbl9fIjoKICAgIGRlbW8ubGF1bmNoKCkK) demo.

```python
import gradio as gr

def calculator(num1, operation, num2):
    if operation == "add":
        return num1 + num2
    elif operation == "subtract":
        return num1 - num2
    elif operation == "multiply":
        return num1 * num2
    elif operation == "divide":
        if num2 == 0:
            raise gr.Error("Cannot divide by zero!")
        return num1 / num2

demo = gr.Interface(
    calculator,
    [
        "number",
        gr.Radio(["add", "subtract", "multiply", "divide"]),
        "number"
    ],
    "number",
    examples=[
        [45, "add", 3],
        [3.14, "divide", 2],
        [144, "multiply", 2.5],
        [0, "subtract", 1.2],
    ],
    title="Toy Calculator",
    description="Here's a sample toy calculator.",
)

if __name__ == "__main__":
    demo.launch()
```

### Screenshot

<img width="732" alt="Screen Shot 2024-09-01 at 9 41 51 AM" src="https://github.com/user-attachments/assets/cc28215a-4d9b-41c8-8387-1de662de2898">

### System Info

```shell
`gr.__version__ == '4.42.0'`
```

### Severity

I can work around it

**Comment by phemw** [comment]
Thanks for the quick response @hannahblair, that does fix the UI. 

I assume that scroll bars shouldn't be attached to components, but this option hides them which is fine. 
Here is the dark mode for reference.

| __Always__                                                                        | __When scrolling__                                                                                                  |
| ------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------- |
| <img width="724" alt="image" src="https://github.com/user-attachments/assets/8002f33f-7c9a-4642-bac4-de6c49191c7c"> | <img width="709" alt="image" src="https://github.com/user-attachments/assets/ea6b2b7c-1840-4515-86f2-8665f9a8bb7d"> |

**Comment by abidlabs** [comment]
Thanks @hannahblair and @phemw for confirming!
