### ISSUE TITLE
'return'ing a value after 'yield' doesn't work

### ISSUE THREAD

**Issue by dwipper** [gradio-app/gradio#9247]
### Describe the bug

In the following code, after the for loop finishes 'yield'ing the 'result', the 'final_text' should be returned to the 'final_text_tbox' gr.Textbox, but the text box doesn't get updated with the value. No errors get thrown.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr
import time

def stream_numbers():
    result = ""
    final_text = ""
    for i in range(0, 10):
        result += str(i) + " "
        yield {stream_tbox: result}
        time.sleep(1)
    final_text = result
    return {final_text_tbox: final_text}

with gr.Blocks()as demo:
    with gr.Column():
        stream_tbox = gr.Textbox(label='Streaming')
        final_text_tbox = gr.Text(label='Final Text')
        stream_btn = gr.Button(value='Stream')
        stream_btn.click(fn=stream_numbers, inputs=None, outputs=[stream_tbox, final_text_tbox])

if __name__ == "__main__":
     demo.launch()
```

### Logs

```shell
NA
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.42.0
gradio_client version: 1.3.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 3.7.1
fastapi: 0.109.2
ffmpy: 0.3.1
gradio-client==1.3.0 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.3
importlib-resources: 6.1.1
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.2
numpy: 1.26.4
orjson: 3.9.13
packaging: 23.2
pandas: 2.2.2
pillow: 10.2.0
pydantic: 2.6.1
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.2.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.9.0
urllib3: 2.2.0
uvicorn: 0.27.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.26.0
huggingface-hub: 0.20.3
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @dwipper, this is actually a Python issue, not a Gradio issue. In Python, when you use `yield` in a function, it turns the function into a generator. When the generator is exhausted, the function ends, and any return statement is ignored unless it's returning None.

In your `stream_numbers()` function, `return {final_text_tbox: final_text}` appears after all values are yielded. However, in Python, returning a value from a generator (other than None) results in a StopIteration exception, and that value is not available through the usual iteration.

You can test this with an example like this:

```py
def stream_numbers():
    for i in range(0, 10):
        yield i
    return "final"

for number in stream_numbers():
    print(number)
```

In your case, changing `return {final_text_tbox: final_text}` to `yield {final_text_tbox: final_text}` should fix the issue

**Comment by dwipper** [comment]
@abidlabs My apologies for the confusion. I had seen somewhere that the return after yield should work, but I must have been mistaken. Works great now with the yield!
