### ISSUE TITLE
Improve consistency of Icon Buttons

### ISSUE THREAD

**Issue by hannahblair** [gradio-app/gradio#9249]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
We have some icon buttons which are floating in the top right, one or two buttons attached to the component border. It would be nice if these could all be kept consistent. 

Thanks @abidlabs for the suggestion! 

<img width="50" alt="Screenshot 2024-09-03 at 16 50 16" src="https://github.com/user-attachments/assets/b0fa54e5-f3e2-4321-94d3-47a4c7406fa6">

<img width="105" alt="Screenshot 2024-09-03 at 16 50 01" src="https://github.com/user-attachments/assets/04f52ad7-2af8-4084-a796-dadd4134a6d2">

**Describe the solution you'd like**  

**Additional context**

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/9250, thanks @hannahblair!
