### ISSUE TITLE
Adding an `interactive` parameter so that `Interface` outputs are not treated as inputs

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#925]
### Describe the bug

As discussed previously, output components in an `Interface` are treated like `inputs`, presumably because they are actually an input to the flagging button.

In this case, @pngwn suggested adding a parameter such as `interactive`, which can be `None`, `True`, or `False`. If `True` or `False`, it overrides the frontend's determination of what is an input and what is an output.

cc @aliabid94 

### Reproduction

Any of the Interface demos

### System Info

```shell
blocks-dev
```

### Severity

critical

**Comment by pngwn** [comment]
Closed by #992.
