### ISSUE TITLE
Gradio Dropdown UI not updating

### ISSUE THREAD

**Issue by rmuhawieh** [gradio-app/gradio#9255]
### Describe the bug

I have a gradio dropdown set as the following:

def _selected_department(select_data:gr.SelectData):
     _department=select_data.value
     print(_department)
     return [gr.Dropdown(['General', 'Production', 'Sales'],label='Department',value=_department, interactive=True)]

department=gr.Dropdown(
['General', 'Production', 'Sales'],
label='Department',
value='General',
interactive=True,
)

department.select(selected_department, outputs=department)

I know the dropdown is working internally because it prints the selected value, as written in the function, and properly uses that updated variable elsewhere for other functions. But, when the choice is selected in the UI, the 'value' appears blank in the UI, making it looks as if no value has been selected.

Why is this happening?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def _selected_department(select_data:gr.SelectData):
     _department=select_data.value
     print(_department)
     return [gr.Dropdown(['General', 'Production', 'Sales'],label='Department',value=_department, interactive=True)]

department=gr.Dropdown(
['General', 'Production', 'Sales'],
label='Department',
value='General',
interactive=True,
)

department.select(selected_department, outputs=department)
```

### System Info

```shell
4.10.0 (can't upgrade for project specific reasons)
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @rmuhawieh the reason this is happening is because you are returning a new value from your function to the Dropdown component. You shouldn't do this. Here's a minimal example that works correctly:

```py
import gradio as gr

with gr.Blocks() as demo:
    def _selected_department(select_data:gr.SelectData):
         print(select_data.value)

    department=gr.Dropdown(
        ['General', 'Production', 'Sales'],
        label='Department',
        value='General',
        interactive=True,
    )

    department.select(_selected_department)
    
demo.launch()
```

**Comment by rmuhawieh** [comment]
> Hi @rmuhawieh the reason this is happening is because you are returning a new value from your function to the Dropdown component. You shouldn't do this. Here's a minimal example that works correctly:
> 
> ```python
> import gradio as gr
> 
> with gr.Blocks() as demo:
>     def _selected_department(select_data:gr.SelectData):
>          print(select_data.value)
> 
>     department=gr.Dropdown(
>         ['General', 'Production', 'Sales'],
>         label='Department',
>         value='General',
>         interactive=True,
>     )
> 
>     department.select(_selected_department)
>     
> demo.launch()
> ```

I see, I believe this makes sense. And say I used multiselect for the Dropdown, which is just setting multiselect=True. But in regards to the event listener (gr.SelectData) and the function _selected department, how would I account for mutliple choices being selected or if an option is deselected?
