### ISSUE TITLE
The gradio chatbot exposed files when entering a source code filename

### ISSUE THREAD

**Issue by huni0103** [gradio-app/gradio#9272]
### Describe the bug

The gradio chatbot exposes the file when you enter the source code filename.

If you enter the gradio development code filename verbatim into Chatbot, it will generate an additional URL to the /tmp/gradio subfolder path.

The messages within the chatbot are being added in the following structure.
from gradio import ChatMessage
chatbot.append(ChatMessage(role=“user”, content=message))

![image](https://github.com/user-attachments/assets/7a6feff6-fd5e-4d5f-b913-1241caf9e27f)

I've blocked the /tmp/gradio path via blocked_paths in launch() to prevent actual downloads, but the problem is that users are getting URLs to unnecessary source files.

Is there any way to solve this?
Even if I clear the value when I return it to the chatbot, it's still exposed.
When we checked the data in the gpt_chat_completions return, there was no mention of /tmp/gradio/..., but if we check the chatbot in the .success() function immediately after, save_chat_message, we can see that the mention of /tmp/gradio/... was added. 
![image](https://github.com/user-attachments/assets/c9af60a4-f669-4693-99f9-b570e25d0d5c)

The code I shared below reproduces the same behavior. If you enter the source code filename verbatim, it will display the URL to download the file.
![image](https://github.com/user-attachments/assets/a0fd638a-53d3-4ed9-abba-b0901457fe4a)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction
SourceCode Filename: test.py
```
import gradio as gr
from gradio import ChatMessage


def load():
    return [
        ChatMessage(
            role="user",
            content="test.py",
        ),
        ChatMessage(
            role="assistant",
            content="hihi test.py",
        ),
    ]


with gr.Blocks() as demo:
    chatbot = gr.Chatbot(type="messages")
    button = gr.Button("Load audio and video")
    button.click(load, None, chatbot)

demo.launch()
```

### System Info

```shell
gradio==4.42.0
ubuntu 20.04
```

### Severity

Blocking usage of gradio

**Comment by huni0103** [comment]
We believe this issue is very security-critical because the files in the directory where the code is executed can be downloaded if you know the name of the file.

(Obviously, setting blocked_paths will prevent downloads).

**Comment by freddyaboulton** [comment]
Will fix in version 5 since this is technically a breaking change

**Comment by huni0103** [comment]
@freddyaboulton hello.
Thank you for your quick confirmation.

This issue is currently causing intermittent issues when using Gradio internally.

Do you have any idea when we can expect a major update to Gradio 5?
