### ISSUE TITLE
I got redundant progress bar 

### ISSUE THREAD

**Issue by Mit17092001** [gradio-app/gradio#9281]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I have used two gradio component 
status = gr.HTML and 
File = gr.File 
with gr.Button,
I can one function process when button is clicked, 
That function gives me output of STATUS, FILENAME

I am using gr.progress in process function die to that i am getting two redundant progress bar in place of this two components.

I only want one progress bar not two progress bars.

This is my code snippet

```
       process_btn = gr.Button("Create Note")
        
        status = gr.HTML(label="Status")
        download = gr.File(label="Download Your Note",interactive=False)

    def update_download_link(file_path):
        return gr.File.update(value=file_path, visible=True)

    process_btn.click(
        fn=process,
        inputs=[agree, doc_type, audio, file, session_state],
        outputs=[status, download]
    )
```

Here is process function defination

`  def process(agreement, document_type, microphone_input: np.ndarray, transcript_files,     session_state: dict, progress=gr.Progress()):`

![1pRuKo3L](https://github.com/user-attachments/assets/96456e34-641d-48ba-ae74-2e69553022e3)

**Comment by abidlabs** [comment]
Hi @Mit17092001 can you please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by abidlabs** [comment]
Going to close for lack of repro, but we can reopen if we receive one
