### ISSUE TITLE
Reuse of events

### ISSUE THREAD

**Issue by elismasilva** [gradio-app/gradio#9284]
- [yes] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

I often need to trigger events that deal with the behavior of the component on the screen, such as visibility, interactivity, and default values. Sometimes, some components have dependencies on values ​​that are defined in other components, and I don't want to have to reference all the dependent components again in the event of the component I'm manipulating to reach a state. I've been using the .then() function for this, but whenever I need to call an event that already exists, I need to repeat all the function parameters, input, and output again.

**Describe the solution you'd like**  

Is it possible to assign the call of an event already defined in a component to a variable so that it can be passed to the .then() function? Below is an example of the behavior. In this small example, the first checkbox handles the state of all the other components except for the "Scale X" parameter. For this, I want the second checkbox, "Enable x factor", to handle the state of the "Scale X" parameter. When I change the first checkbox, I want it to also trigger the event of the second checkbox to reset the state of the last parameter. This way, I always keep the screen consistent. You could say, "Why don't you already handle all this in the first checkbox?" Well, for this simple example, this may make sense, but when I'm working on a complex UI, like the one I'm developing now, I want to be able to reuse events at certain times. I left a commented part of the code showing how I imagined it could be. If there is a resource that does something similar, I would really like to know.

```python
import gradio as gr

with gr.Blocks() as demo:    
    enable_function = gr.Checkbox(label="Enable this function", value=False)
    param = gr.Slider(interactive=False, 
                    label="Scale Y", 
                    minimum=1, 
                    maximum=50, 
                    step=1,
                    value=1)
    enable_function_2 = gr.Checkbox(label="Enable x factor", value=False)
    param_x_factor = gr.Slider(interactive=False, 
                    label="Scale X", 
                    minimum=1, 
                    maximum=50, 
                    step=1,
                    value=1)

    def change_enable_function(enable_function):            
        return [gr.update(interactive=enable_function), gr.update(interactive=enable_function, value=False)]
        
    def change_enable_function_2(enable_function_2):
        return gr.update(interactive=enable_function_2)
    
    #How i am doing:
    enable_function_2.select(fn=change_enable_function_2, inputs=enable_function_2, outputs=[param_x_factor])
    enable_function.select(fn=change_enable_function, inputs=enable_function, outputs=[param, enable_function_2]).then(
        fn=change_enable_function_2, inputs=enable_function_2, outputs=[param_x_factor] # i need to repeat here all params passed in enable_function_2
    )
    
 #  How i desired it to work
 #  event_2 = enable_function_2.select(fn=change_enable_function_2, inputs=enable_function_2, outputs=[param_x_factor]) # i want set a variable with this event so i will resue it on other events
 #  enable_function.select(fn=change_enable_function, inputs=enable_function, outputs=[param, enable_function_2]).then(
 #       event_2 # like this.
 #  )
demo.launch(inbrowser=True)
```

**Comment by missionfloyd** [comment]
You could use dicts.
```python
event_2 = {"fn": change_enable_function_2, "inputs": enable_function_2, "outputs": [param_x_factor]}
enable_function_2.select(**event_2)
enable_function.select(fn=change_enable_function, inputs=enable_function, outputs=[param, enable_function_2]).then(**event_2)
```

**Comment by elismasilva** [comment]
> You could define the event parameters in a dict, then unpack it with `**`.
> 
> ```python
> event_2 = {"fn": change_enable_function_2, "inputs": enable_function_2, "outputs": [param_x_factor]}
> enable_function_2.select(**event_2)
> enable_function.select(fn=change_enable_function, inputs=enable_function, outputs=[param, enable_function_2]).then(**event_2)
> ```
Great, this works! Interestingly, I've used this technique in other situations but I didn't remember it haha. I'm getting old. Thank you!
