### ISSUE TITLE
Disable and Enable Button when task begins and done

### ISSUE THREAD

**Issue by MrLju** [gradio-app/gradio#9286]
My gradio version is: 3.32.0
and client version is: gradio_client
I have a time consumed task need to run when I click the button. I'm wondering if the grButton can provide this mechanism:
when the button is clicked, it's disabled and return to enable again when the the work has done.

Thank you.

**Comment by missionfloyd** [comment]
This can be done with [`then()`](https://www.gradio.app/guides/blocks-and-event-listeners#running-events-consecutively). 

Disable the button, do your stuff, then enable the button.
```python
import time
import gradio as gr

def do_stuff():
    time.sleep(3)
    return "OK"

with gr.Blocks() as demo:
    textbox = gr.Textbox()
    btn = gr.Button("Go", variant="primary")

    btn.click(fn=lambda: gr.update(interactive=False), inputs=None, outputs=btn).then(fn=do_stuff, inputs=None, outputs=textbox).then(fn=lambda: gr.update(interactive=True), inputs=None, outputs=btn)

demo.launch()
```

**Comment by MrLju** [comment]
That's cool, thank you!!!
