### ISSUE TITLE
Scrolling large Dataframe increases visible row size

### ISSUE THREAD

**Issue by bilzard** [gradio-app/gradio#9288]
### Describe the bug

In my environment, scrolling long dataframe increasing visible row size.
I think it should be static size even scrolling.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import pandas as pd
import numpy as np

with gr.Blocks() as demo:
    x = np.arange(1000)
    y = x**2

    metadata = pd.DataFrame(dict(x=x, y=y))
    df_display = gr.DataFrame(metadata, height=200, interactive=False)

demo.launch()
```

### Screenshot

https://github.com/user-attachments/assets/2fb352e3-aa83-42e0-b928-926095b1ff65

### Logs

```shell
No js/python error printed (since its UI's malfunctioning)
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.43.0
gradio_client version: 1.3.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.4.0
fastapi: 0.112.4
ffmpy: 0.4.0
gradio-client==1.3.0 is not installed.
httpx: 0.27.2
huggingface-hub: 0.24.6
importlib-resources: 6.4.4
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.9.2
numpy: 2.1.1
orjson: 3.10.7
packaging: 24.1
pandas: 2.2.2
pillow: 10.4.0
pydantic: 2.9.0
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.2
ruff: 0.6.4
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.5
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.30.6
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.9.0
httpx: 0.27.2
huggingface-hub: 0.24.6
packaging: 24.1
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

I can work around it

**Comment by SwannLanthan** [comment]
I just had the same problem here!

**Comment by abidlabs** [comment]
Which browser are y'all using?

**Comment by bilzard** [comment]
@abidlabs I tested this issue reproduced in all of these thee environments. It seems not browser-specific issue.

* Firefox: 129.0.2 (64-bit)
* Chrome Version 128.0.6613.120 (Official Build) (arm64)
* VSCode + Jupyter Extention

**Comment by abidlabs** [comment]
You're right, I can reproduce this, thanks @bilzard, we'll take a look at this!

**Comment by pngwn** [comment]
This is definitely bad and wrong. Will fix when I tackle the data frame shortly.

**Comment by cornzz** [comment]
I'm also having this issue after upgrading from `4.40.0` to `4.44.0`, see also this [playground link](https://www.gradio.app/playground?demo=Hello_World&code=aW1wb3J0IGdyYWRpbyBhcyBncgoKZGF0YSA9IFsKICAgIFsKICAgICAgICAiV2hhdCBpcyB0aGUgYWdlbmRhIGl0ZW0gdGhyZWUgcmVzb2x1dGlvbiAzMTY2OSBhYm91dD8iLAogICAgICAgICJFbmNvdXJhZ2luZyBpbmRpdmlkdWFsaXplZCB0ZW5hbnQgYXNzZXNzbWVudC4iCiAgICBdLAogICAgWwogICAgICAgICJXaGF0IGlzIHRoZSBhbWVuZG1lbnQgcHJvcG9zZWQgYnkgQ291bmNpbG1lbWJlciBCYWdzaGF3PyIsCiAgICAgICAgIkFkZGl0aW9uIGluIHRoZSBcIndoZXJlYXNcIiBzZWN0aW9uLiIKICAgIF0sCiAgICBbCiAgICAgICAgIldoYXQgYXJlIHRoZSBwcmltYXJ5IGNoYW5nZXMgaW4gdGhlIHJlc29sdXRpb24gc2luY2UgdGhlIGxhc3QgY29tbWl0dGVlIG1lZXRpbmc/IiwKICAgICAgICAiQ2hhbmdlcyBpbiB0d28gcmVjaXRhbHMgYW5kIHNlY3Rpb25zIG9uZSBhbmQgZml2ZS4iCiAgICBdLAogICAgWwogICAgICAgICJXaGF0IGRvZXMgdGhlIEhVRCBndWlkYW5jZSBlbXBoYXNpemU/IiwKICAgICAgICAiRGlzdGluZ3Vpc2hpbmcgYmV0d2VlbiBjcmltaW5hbCBjb25kdWN0IHRoYXQgaW5kaWNhdGVzIGEgcmlzayB0byByZXNpZGVudHMgc2FmZXR5IGFuZCBjb25kdWN0IHRoYXQgZG9lcyBub3QuIgogICAgXSwKICAgIFsKICAgICAgICAiV2hhdCBkb2VzIG9uZSBvZiB0aGUgc2VjdGlvbnMgb2YgdGhlIHJlc29sdXRpb24gZW5kb3JzZT8iLAogICAgICAgICJMYW5kbG9yZHMgc2hvdWxkIG5vdCBhdXRvbWF0aWNhbGx5IGV4Y2x1ZGUgaW5kaXZpZHVhbHMgZm9yIGhvdXNpbmcgb24gdGhlIGJhc2lzIG9mIHByaW9yIGV2ZW50IGFycmVzdHMuIgogICAgXSwKICAgIFsKICAgICAgICAiV2hhdCBkb2VzIHRoZSBmaW5hbCBzZWN0aW9uIHJlcXVlc3QgZnJvbSB0aGUgT0NSPyIsCiAgICAgICAgIlRvIGRldGVybWluZSB3aGV0aGVyIHRoZXJlJ3MgYSBkaXNwYXJhdGUgaW1wYWN0IGluIGNvbXBsYWludHMgb2YgaG91c2luZyBkaXNjcmltaW5hdGlvbiBiYXNlZCBvbiB0aGUgdXNlIG9mIGNyaW1pbmFsIGhpc3RvcnkuIgogICAgXSwKICAgIFsKICAgICAgICAiV2hhdCBpcyB0aGUgQ2VydGlmaWNhdGUgb2YgUmVzdG9yYXRpb24gb2YgT3Bwb3J0dW5pdHkgKENST1ApPyIsCiAgICAgICAgIkEgY2VydGlmaWNhdGUgcHJvdmlkaW5nIGNvbmNyZXRlIGFuZCBvYmplY3RpdmUgaW5mb3JtYXRpb24gYWJvdXQgYW4gaW5kaXZpZHVhbCB3aG8gaGFzIHNlcnZlZCBoaXMgb3IgaGVyIHRpbWUgaW4gcHJpc29uLiIKICAgIF0sCiAgICBbCiAgICAgICAgIldoYXQgaXMgdGhlIHB1cnBvc2Ugb2YgQ1JPUD8iLAogICAgICAgICJUbyBmYWNpbGl0YXRlIHRoZSBzdWNjZXNzZnVsIHNvY2lldGFsIHJlaW50ZWdyYXRpb24gb2YgaW5kaXZpZHVhbHMgd2l0aCBhIGNyaW1pbmFsIGhpc3RvcnkuIgogICAgXSwKICAgIFsKICAgICAgICAiV2hhdCBpcyB0aGUgcmVzb2x1dGlvbidzIGZvY3VzPyIsCiAgICAgICAgIkVuY291cmFnaW5nIGxhbmRsb3JkcyB0byBmb2xsb3cgSFVEIGd1aWRhbmNlIHJlZ2FyZGluZyBjcmltaW5hbCByZWNvcmRzLiIKICAgIF0sCiAgICBbCiAgICAgICAgIldoYXQgaXMgdGhlIG91dGNvbWUgb2YgdGhlIHZvdGUgb24gdGhlIHJlc29sdXRpb24/IiwKICAgICAgICAiVGhlIHJlc29sdXRpb24gaXMgYWRvcHRlZC4iCiAgICBdCl0KCndpdGggZ3IuQmxvY2tzKCkgYXMgZGVtbzoKICBnci5EYXRhRnJhbWUoZGF0YSwgaGVpZ2h0PTIwMCkKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICBkZW1vLmxhdW5jaCgpCg==).

It seems to be [this line](https://github.com/gradio-app/gradio/blame/main/js/dataframe/shared/VirtualTable.svelte#L251) that was added in the SSR update which causes this behaviour, commenting it out fixes it.

**Comment by abidlabs** [comment]
Thanks @cornzz for isolating the issue. We'll fix this shortly

**Comment by Asianfleet** [comment]
the bug haven't been fixed yet.

**Comment by abidlabs** [comment]
Another manifestation of this bug is happening on this Space: https://huggingface.co/spaces/lhoestq/Common-Crawl-Pipeline-Creator

**Comment by recursix** [comment]
For me, the workaround doesn't work. It fixes a viewport for the table, but the table grows inside the viewport and we cannot see the end of the table. (radio 5.3.0
)

**Comment by pambram** [comment]
@abidlabs it seems to me another symptom of this bug (I happened to come across this as I'm working with Dataframe components today) is that the header row also changes size when scrolling, which doesn't seem to be something that should be intended.

I came across the bug on this issue, and by using the workaround described: 
```
{
    min-height: 170px;
    max-height: 170px;
}
```

I was able to work fine. But the first row's height is also being increased and I'm not sure if this is FAD. 

Repro code:

```python
import gradio as gr

with gr.Blocks(
        css="#test_dataframe {min-height: 400px; max-height: 400px;}" # this is the workaround, working
) as demo:
    gr.Markdown("## Testing Dataframe ##")
    # Example dataset with 20 rows and 5 columns, each cell containing more than 200 characters
    example_data = [
        [
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. " * 4,
            "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. " * 4,
            "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris " * 4,
            "Nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in " * 4,
            "Reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. " * 4
        ]
        for _ in range(200)
    ]
    documents_list = gr.DataFrame(
        value=example_data,
        headers=["Column 1", "Column 2", "Column 3", "Column 4", "Column 5"],
        elem_id="test_dataframe"
        #wrap=True,  # this just makes it 10x worse
    )
    gr.Button("Mock Button to a component after DataFrame")

demo.launch(debug=True)
```

this results in this test case:
![Kapture 2024-10-22 at 22 15 17](https://github.com/user-attachments/assets/5bd03bc4-c6de-452a-8f03-6849a82fadf7)


In my real dataset it's much worse and more noticeable, because I also use wrap = True here:
![Kapture 2024-10-22 at 22 16 49](https://github.com/user-attachments/assets/216f7775-a1ff-478f-9e20-6479d36e74cc)

**Comment by dtamien** [comment]
I've encountered a similar problem to what's described in #9288, but with an additional behavior: when the horizontal scrollbar is positioned at the far right and I scroll upward, the dataframe shrinks vertically, eventually flattening completely. This was observed while developing on Linux Mint 22.04 with the latest version of Chrome at this time, using both `gradio`and `python`CLI on my `app.py` with the `gr.Dataframe` component. It seems to further support the notion that this issue is not browser-specific, as it replicates across different environments.
