### ISSUE TITLE
Increasing Default App Max Width is not Working from 4.39.0 Release-  svelte max-width property not working

### ISSUE THREAD

**Issue by skparticles** [gradio-app/gradio#9293]
### Describe the bug

custom_css = """
        .app.svelte-182fdeq.svelte-182fdeq {
            max-width: 1900px;
            max-height: 900px;     
        }
        '''
        
 Setting Width and Height of the app is not working anymore. I need to set app for a specific width and height.    
 
 Working : 4.38.0
 Not working >= 4.49.0    
        

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

custom_css = """
        .app.svelte-182fdeq.svelte-182fdeq {
            max-width: 1900px;
            max-height: 900px;     
        }
        '''

### System Info

```shell
yes
```

### Severity

I can work around it. by using previous version 4.38.0 but i am missing image max/min view from the latest code.

**Comment by abidlabs** [comment]
Hi @skparticles, you should not include the hashes `182fdeq`, like this as they can change from Gradio version to version. Can you try targeting a more general class instead? See also: https://www.gradio.app/guides/custom-CSS-and-JS

**Comment by skparticles** [comment]
Hi @abidlabs 
Thanks  for the suggestion,
 I tried to add max-width and max-height in the gradio-container, it doesn't works, only color works. It doesnt extend default app size.   
.gradio-container {
            max-width: 1900px;
            max-height: 900px;   
 }
 
 Please suggest me any other method.

**Comment by abidlabs** [comment]
Hmm btw would the `fill_width` parameter in `Blocks` work?

**Comment by skparticles** [comment]
fill_width block works but that fills entire width of the screen, but i need specific width and height.

**Comment by abidlabs** [comment]
Hi @skparticles ok, for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB).

**Comment by skparticles** [comment]
Hi @abidlabs,
 
If i cannot customize an app width and height. looks like it's a bug, which i can able to do it with previous version.
  
If i need to use  .gradiocontainer , max-width and max-height is not working then i think it's a bug to fix at .gradiocontainer level.

If i am wrong, please correct me.

**Comment by abidlabs** [comment]
Can you try something like:

```py
import gradio as gr

css = """
.gradio-container {
  max-width:1000px !important;
}
"""

with gr.Blocks() as demo:
    gr.Textbox()
    gr.Image()

demo.launch()
```

**Comment by skparticles** [comment]
Hi @abidlabs ,
   Thats a great suggestion, important is the key word, it's working perfect.
   
   css = """
    .gradio-container {
      max-width:1000px !important;
     max-height:900px !important;
    }
    """
