### ISSUE TITLE
Dropdown allow_custom_value=True  key_up update Incomplete options

### ISSUE THREAD

**Issue by inewlife** [gradio-app/gradio#9307]
### Describe the bug

When I type test, only test appears as an option, but the other one does not appear.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def update_dropdown_test(value, key_up_data: gr.KeyUpData):
    if key_up_data.input_value=="test":
        return gr.update(choices=["test","start"], visible=True)

with gr.Blocks() as demo:
    model_dropdown = gr.Dropdown(label="Models Auto-Complete",interactive=True,  choices=[""], allow_custom_value=True) 
    model_dropdown.key_up(fn=update_dropdown_test,queue=False, inputs=[model_dropdown], outputs=model_dropdown, show_progress="hidden", trigger_mode="always_last")  
    
demo.launch()
```

### Screenshot

![20240910141753](https://github.com/user-attachments/assets/94f39797-1c82-467e-b646-220ab37b9106)

### System Info

```shell
gradio 4.39.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @inewlife this behavior is happening because the `gr.Dropdown` filters choices based on what you have typed already. In this case, "test" only matches "test" so "start" is not shown. If you were to hit backspace a few times, you'll see "start" as well. 

One option you have is to reset the value when "test" is typed, e.g.

```py
import gradio as gr

def update_dropdown_test(value, key_up_data: gr.KeyUpData):
    if key_up_data.input_value=="test":
        return gr.update(value="", choices=["test","start"], visible=True)

with gr.Blocks() as demo:
    model_dropdown = gr.Dropdown(label="Models Auto-Complete",interactive=True,  choices=[""], allow_custom_value=True) 
    model_dropdown.key_up(fn=update_dropdown_test,queue=False, inputs=[model_dropdown], outputs=model_dropdown, show_progress="hidden", trigger_mode="always_last")  
    
demo.launch()
```

**Comment by inewlife** [comment]
> Hi @inewlife this behavior is happening because the `gr.Dropdown` filters choices based on what you have typed already. In this case, "test" only matches "test" so "start" is not shown. If you were to hit backspace a few times, you'll see "start" as well.
> 
> One option you have is to reset the value when "test" is typed, e.g.
> 
> ```python
> import gradio as gr
> 
> def update_dropdown_test(value, key_up_data: gr.KeyUpData):
>     if key_up_data.input_value=="test":
>         return gr.update(value="", choices=["test","start"], visible=True)
> 
> with gr.Blocks() as demo:
>     model_dropdown = gr.Dropdown(label="Models Auto-Complete",interactive=True,  choices=[""], allow_custom_value=True) 
>     model_dropdown.key_up(fn=update_dropdown_test,queue=False, inputs=[model_dropdown], outputs=model_dropdown, show_progress="hidden", trigger_mode="always_last")  
>     
> demo.launch()
> ```


Thanks for the reply, but my usage scenario is associated words. How can I prevent the modified options from being filtered by input words?

**Comment by inewlife** [comment]
> Hi @inewlife this behavior is happening because the `gr.Dropdown` filters choices based on what you have typed already. In this case, "test" only matches "test" so "start" is not shown. If you were to hit backspace a few times, you'll see "start" as well.
> 
> One option you have is to reset the value when "test" is typed, e.g.
> 
> ```python
> import gradio as gr
> 
> def update_dropdown_test(value, key_up_data: gr.KeyUpData):
>     if key_up_data.input_value=="test":
>         return gr.update(value="", choices=["test","start"], visible=True)
> 
> with gr.Blocks() as demo:
>     model_dropdown = gr.Dropdown(label="Models Auto-Complete",interactive=True,  choices=[""], allow_custom_value=True) 
>     model_dropdown.key_up(fn=update_dropdown_test,queue=False, inputs=[model_dropdown], outputs=model_dropdown, show_progress="hidden", trigger_mode="always_last")  
>     
> demo.launch()
> ```

@abidlabs Thanks for the reply, but my usage scenario is associated words. How can I prevent the modified options from being filtered by input words?

**Comment by abidlabs** [comment]
I'm not sure I understand, the common behavior in dropdowns is to filter the choices based on what is typed. If you do not want that behavior, perhaps it would make sense to have a separate input `gr.Textbox` component that you are typing into, and then keep the dropdown options in a separate `gr.Dropdown` component?
