### ISSUE TITLE
Unable to launch demo because of PIL.Image issue

### ISSUE THREAD

**Issue by imaspol** [gradio-app/gradio#9309]
### Describe the bug

Unable to launch app.py from the terminal. `File "C:\Users\...\prod-env\Lib\site-packages\gradio\components\__init__.py", line 1, in <module>      
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\Users\...\anaconda3\envs\prod-env\Lib\site-packages\gradio\components\annotated_image.py", line 9, in <module>
    import PIL.Image
  File "C:\Users\...\anaconda3\envs\prod-env\Lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: Le module spécifié est introuvable.`

Impossible to downgrade pillow package as it 
I've tried to downgrade pillow to the version 9.00 but it is not compatible with python 3.12

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python app.py

```

### System Info

```shell
Windows 11 Professionnel
python 3.12.1
gradio 4.42
pillow 10.4.0
```

### Severity

I can not work around it

**Comment by abidlabs** [comment]
Hi @imaspol can try uninstalling and reinstalling `pillow`? This error usually indicates that PIL or one of its dependencies did not get installed correctly. You can also try installing `gradio` in a clean virtual environment b/c it may be related to conflicts with other libraries.

**Comment by abidlabs** [comment]
Going to close for lack of repro, but we can reopen if we receive one

**Comment by imaspol** [comment]
> Hi @imaspol can try uninstalling and reinstalling `pillow`? This error usually indicates that PIL or one of its dependencies did not get installed correctly. You can also try installing `gradio` in a clean virtual environment b/c it may be related to conflicts with other libraries.

Thank you @abidlabs. I tried your solutions and it works! First, I installed gradio in the new environment and I didn't encount any problem. Then, I reinstalled the same libraries as in the original environment using requirements.txt: no problem!
