### ISSUE TITLE
Hugginface Theme Gallery Not Working

### ISSUE THREAD

**Issue by varungupta31** [gradio-app/gradio#9319]
### Describe the bug

The [Theme Gallery](https://huggingface.co/spaces/gradio/theme-gallery) to browse various Gradio themes is not working for a while.

The Error reads

```
Your space is in error, check its status on hf.co
```

Someone mentioned this in the [HF repo's community](https://huggingface.co/spaces/gradio/theme-gallery/discussions/2) 2 months ago, so the problem seems to have persisted.
Can someone fix this please?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Visit Gradio's Theme Gallery HF Space (Link: https://huggingface.co/spaces/gradio/theme-gallery)

### Screenshot

<img width="1800" alt="Screenshot 2024-09-11 at 2 02 10 PM" src="https://github.com/user-attachments/assets/45b2f1a6-60a4-4bea-b504-c7eb8f1ec1dc">

### Logs

```shell
NA
```

### System Info

```shell
NA Running on Browser (Brave) + Doesn't work on Other Browser as well (Safari)
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Yes the issue is that spaces go down sometimes and we don't have permission to restart them. We'll be re-designing this in the coming weeks/months.

**Comment by varungupta31** [comment]
Ah, I see.

Feel free to close this issue or close when this is resolved, any way works.

Thanks.

**Comment by abidlabs** [comment]
Most of the Spaces should be restarted now!
