### ISSUE TITLE
Gradio button function in achieving the output format like {'background': PIL, 'layers''composite':}

### ISSUE THREAD

**Issue by jeevitesh** [gradio-app/gradio#9324]
The output of the program is dictionary is of type 

`Array Dict {'background': <PIL.Image.Image image mode=RGBA size=768x1024 at 0x7F61BD8B6EF0>, 'layers': [<PIL.Image.Image image mode=RGBA size=768x1024 at 0x7F61BD8B6EC0>], 'composite': <PIL.Image.Image image mode=RGBA size=768x1024 at 0x7F61BD8B6E60>} ` 

```
import gradio as gr
from PIL import Image

def process_input_file(dict):
    print("Array Dict",dict)

image_blocks = gr.Blocks().queue()
with image_blocks as demo:
    gr.Markdown("image")
    ex_dict= {}
    ex_dict['background'] = '/codeBackup/00260_00.jpg'
    ex_dict['layers'] = None
    ex_dict['composite'] = None    
    with gr.Row():
        with gr.Column():
            humanimg=gr.ImageEditor(value=ex_dict, type="pil" )
           
            with gr.Column():
                with gr.Row(elem_id="prompt-container"):
                    with gr.Row():
                        image_out = gr.Image(label="Output", elem_id="output-img",show_share_button=False, min_width = 250)
        with gr.Column():
            with gr.Row():
                try_button = gr.Button(value="image upload")                
            print("IMAGE ", humanimg)
        try_button.click(fn=process_input_file, inputs=[humanimg], outputs=[image_out], api_name='tryon')
image_blocks.launch(share=True)
```

whereas same program without button is returning the output 

`Array Dict <gradio.components.image_editor.ImageEditor object at 0x7f5ad49d30d0>`

Program without button direct function call 

```
import gradio as gr
from PIL import Image

def process_input_file(dict):
    print("Array Dict",dict)
ex_dict= {}
ex_dict['background'] = '/codeBackup/00260_00.jpg'
ex_dict['layers'] = None
ex_dict['composite'] = None
humanimg=gr.ImageEditor(value=ex_dict, type="pil" )
print("IMAGE ", humanimg)
process_input_file(humanimg)
```

Now question is what is the data transformation try_button.click is doing to get the data in the format ? 

`Array Dict {'background': <PIL.Image.Image image mode=RGBA size=768x1024 at 0x7F61BD8B6EF0>, 'layers': [<PIL.Image.Image image mode=RGBA size=768x1024 at 0x7F61BD8B6EC0>], 'composite': <PIL.Image.Image image mode=RGBA size=768x1024 at 0x7F61BD8B6E60>} `

But direct function call is giving the following format 

`Array Dict <gradio.components.image_editor.ImageEditor object at 0x7f5ad49d30d0>`

How to achieve the data transformation like 

`Array Dict {'background': <PIL.Image.Image image mode=RGBA size=768x1024 at 0x7F61BD8B6EF0>, 'layers': [<PIL.Image.Image image mode=RGBA size=768x1024 at 0x7F61BD8B6EC0>], 'composite': <PIL.Image.Image image mode=RGBA size=768x1024 at 0x7F61BD8B6E60>}`

I have tried 

```dict.value``` getting the format like

`Array Dict {'background': {'path': '/tmp/gradio/50d3d052a1b24ba678e68e14073875528ea29a4b/00260_00.jpg', 'url': '/file=/tmp/gradio/50d3d052a1b24ba678e68e14073875528ea29a4b/00260_00.jpg', 'size': None, 'orig_name': None, 'mime_type': None, 'is_stream': False, 'meta': {'_type': 'gradio.FileData'}}, 'layers': [], 'composite': None, 'id': None}`

I did try to post the question in discord and i'm facing permission issue while posting the question.

**Comment by abidlabs** [comment]
Hi @jeevitesh I'm sorry but the issue is very unclear to me. Can you please explain the issue you are facing more clearly? It sounds like you have some questions, which are indeed better suited for our Discord.

**Comment by jeevitesh** [comment]
I have simplified the question
I have simple problem, I'm reading the image using image editor and passing the image object to button function and getting image as mentioned in the format 1. But i need to how the transformation is happening in the button function. I need to achieve the same format without button function.

Program 1 with gradio button
def process_input_file(dict):
    print("Array Dict",dict)

image_blocks = gr.Blocks().queue()
with image_blocks as demo:
    gr.Markdown("image")
    ex_dict= {}
    ex_dict['background'] = '2.jpg'
    ex_dict['layers'] = None
    ex_dict['composite'] = None    
    with gr.Row():
        with gr.Column():
            humanimg=gr.ImageEditor(value=ex_dict, type="pil" )
            with gr.Column():
                with gr.Row(elem_id="prompt-container"):
                    with gr.Row():
                        image_out = gr.Image(label="Output", elem_id="output-img",show_share_button=False, min_width = 250)
        with gr.Column():
            with gr.Row():
                try_button = gr.Button(value="image upload")                
            print("IMAGE ", humanimg)
        try_button.click(fn=process_input_file, inputs=[humanimg], outputs=[image_out], api_name='tryon')
image_blocks.launch(share=True)

Format 1
Array Dict {'background': <PIL.Image.Image image mode=RGBA size=768x1024 at 0x7F1>, 'layers': [<PIL.Image.Image image mode=RGBA size=768x1024 at 0x7>], 'composite': <PIL.Image.Image image mode=RGBA size=768x1024 at 0x7>} 

Program 2 without button direct function call 

def process_input_file(dict):
    print("Array Dict",dict)
ex_dict= {}
ex_dict['background'] = '2.jpg'
ex_dict['layers'] = None
ex_dict['composite'] = None
humanimg=gr.ImageEditor(value=ex_dict, type="pil" )
print("IMAGE ", humanimg)
process_input_file(humanimg)

Format 2
Array Dict <gradio.components.image_editor.ImageEditor object at 0x7>

what is the data transformation try_button.click is doing inorder to get the format 1,  how to achieve format1 without button
