### ISSUE TITLE
updating the “How to Make a Gradio Custom Component” page on Wiki

### ISSUE THREAD

**Issue by Bebra777228** [gradio-app/gradio#9329]
I'm doing exactly as described on the page, but I'm getting nowhere, the last change was Oct. 24, 2023., Maybe it's time to update the manual? =)

The problems start at the `dev` step, many different errors appear.

**Comment by abidlabs** [comment]
Please use this instead: https://www.gradio.app/guides/custom-components-in-five-minutes (I'll delete the wiki page!)

**Comment by Bebra777228** [comment]
## I'm getting the following error when I run "gradio cc dev". I checked the folder, the package is installed.
![image](https://github.com/user-attachments/assets/806ae22b-5adc-468d-bc0a-a0f79599bb2c)
## When I run `npm i -D @gradio/preview`, it says the following:
![image](https://github.com/user-attachments/assets/0bcb0328-0d47-4e84-9acf-ca4fc72f923c)
## But when I run "gradio cc dev" again, I get the same error as in the first screenshot.

The following package versions are installed:
- `python` - 3.10.0
- `pip` - 24.2
- `Node.js` - v20.17.0
- `npm` - 10.8.3
- `gradio` - 4.44.0
- @gradio/preview@0.11.1

## What am I doing wrong?
