### ISSUE TITLE
delete_cache not working

### ISSUE THREAD

**Issue by peeter2** [gradio-app/gradio#9334]
### Describe the bug

delete_cache is not working, what am I doing wrong?
no matter how long I wait, no matter if I close the tab or not, no matter if I kill the terminal or not. The temp files are all still there.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr
with gr.Blocks(delete_cache=(30, 30)) as demo:

```

### System Info

```shell
latest
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @peeter2 ! I can't repro on version 4.44 (the latest). The uploaded/modified images are deleted

```python
import gradio as gr
import os

def image_mod(image):
    return image.rotate(45)

cheetah = os.path.join(os.path.dirname(__file__), "images/cheetah1.jpg")

demo = gr.Interface(image_mod, gr.Image(type="pil", value=cheetah), "image",
    flagging_options=["blurry", "incorrect", "other"], examples=[
        os.path.join(os.path.dirname(__file__), "images/lion.jpg"),
        os.path.join(os.path.dirname(__file__), "images/logo.png")
        ], delete_cache=(5, 5))

if __name__ == "__main__":
    demo.launch()
```

https://github.com/user-attachments/assets/b90872c1-8b24-403b-afb1-92fe2b3b0a5e

**Comment by peeter2** [comment]
Oh I see. I didn't check inside the folders. I just thought that all the files were still there as the directories were not deleted.

That explains it, thanks.
