### ISSUE TITLE
Implement minimum and maximum to the number input

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#934]
**Is your feature request related to a problem? Please describe.**
It is not always I need a number slider, however I am forced to use it because I want to constraint the user to a certain range of values

**Describe the solution you'd like**
Maximum and minimum values could take many forms:
- If the user types a lower or higher value, the value could "snap" to the highest or lowest allowed value
- If the user went lower or higher, it could show that this is an invalid field and gray out the submit button

Edit: Step and Randomize functions could be added as well

**Comment by abidlabs** [comment]
This is a good suggestion! We would want to communicate the range clearly to the user as well. Do you have thoughts on how that might be communicated?

**Comment by apolinario** [comment]
A few ideas: 
- Have the allowed value range on the placeholder
- Have the allowed value range with some other color next or below the label
- Have the allowed value range below the input field itself

**Comment by pngwn** [comment]
A common pattern is to use labelled 'pips'. Little lines underneath the range input. Sometimes they are used to show 'steps' but they are commonly used to show min + max values.

This kind of thing.

![pips](https://user-images.githubusercontent.com/12937446/162259126-fe908367-2540-49ba-a0cf-6c77e94cd0c5.png)

**Comment by apolinario** [comment]
Hi @pngwn! I love your suggestion and I think it could make a lot of sense to the Slider input

But just a a clarification, this feature request actually referred to the possibility of enabling maximum and minimum values to the `gradio.inputs.Number` field

**Comment by apolinario** [comment]
Also for the way to inform the user @abidlabs , I don't love this one only happens after they inputed something wrong, but could be a food for thought.

(PS: This example contains a way to add the "Steps" option to the `inputs.Number`, I didn't open an issue for it but I would love this as a feature too) 

https://user-images.githubusercontent.com/788417/162432035-f9e1671c-7e51-49f4-a35f-54f0e9f0d592.mov
