### ISSUE TITLE
`.svg` files cannot be used as avatar_images

### ISSUE THREAD

**Issue by letmaik** [gradio-app/gradio#9342]
### Describe the bug

WIth 4.37.1 (and possibly some later versions), I was able to use a local image file path in `avatar_images=(None, avatar_path),`. With the latest version, this breaks as the image is sent as an attachment file, meaning the HTTP headers are wrong.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

chatbot = gr.Chatbot(
            avatar_images=(None, "avatar.svg"),
        )
```

### Screenshot

![image](https://github.com/user-attachments/assets/d1d7a514-9584-4b4d-8d79-0904d224b643)

![image](https://github.com/user-attachments/assets/e478564c-30bc-43f2-8560-3f30e6f7709b)

### System Info

```shell
4.44.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @letmaik we no longer serve SVG files inline for security reasons. Please try with a different file image format, and it should work for you. We'll update the docs to clarify this

**Comment by letmaik** [comment]
It might be worth raising an error or printing a warning when a `.svg` file extension is used. Is there a flag to override the restriction? A local svg file that is known to be safe won't present a security risk.

**Comment by abidlabs** [comment]
Yes that's a good point, let us think about this

**Comment by abidlabs** [comment]
Ok so you can try installing `gradio` this PR: https://github.com/gradio-app/gradio/pull/9348#pullrequestreview-2303495636

It should now work! Caveat: this is our `5.0-dev` branch, so you can expect to see some UI changes, etc. Let us know if you have any issues

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/9348
