### ISSUE TITLE
<!-- tag=changesets_gradio -->

### ISSUE THREAD

**Issue by RTapio9912** [gradio-app/gradio#9344]
#### This Pull Request includes changes to the following packages. 

| Package | Version |
|--------|--------|
|`@gradio/wasm` | `minor` |
|`gradio` | `minor` |

- [ ] Maintainers can  select this checkbox to manually select packages to update.

#### With the following changelog entry.

> Proposal: remove `gr.make_waveform` and remove `matplotlib` as a dependency

_Maintainers or the PR author can modify the PR title to modify this entry._
<details><summary>

#### Something isn't right?</summary>

- Maintainers can change the version label to modify the version bump. 
- If the bot has failed to detect any changes, or if this pull request needs to update multiple packages to different versions or requires a more comprehensive changelog entry, maintainers can [update the changelog file directly](https://github.com/gradio-app/gradio/edit/remove-plt/.changeset/proud-memes-fold.md).

</details>

_Originally posted by @gradio-pr-bot in https://github.com/gradio-app/gradio/issues/9312#issuecomment-2341791369_

**Comment by abidlabs** [comment]
Hi it looks like this issue has been opened in error
