### ISSUE TITLE
Disable telemetry

### ISSUE THREAD

**Issue by Bikatr7** [gradio-app/gradio#9353]
[ x ] I have searched to see if a similar issue already exists.
Yes

**Is your feature request related to a problem? Please describe.**  

I should not be having my ip checked when running locally. There is no reason for this to be on by default.

**Describe the solution you'd like**  

I want this to be toggleable. I am not seeing a way to do this.

****Additional context****  
![image](https://github.com/user-attachments/assets/c6660f68-6607-4553-9fac-308da54cd8c0)

**Comment by missionfloyd** [comment]
> `analytics_enabled: bool | None`
default = `None`
Whether to allow basic telemetry. If None, will use GRADIO_ANALYTICS_ENABLED environment variable or default to True.

https://www.gradio.app/docs/gradio/blocks#initialization

**Comment by Bikatr7** [comment]
> > `analytics_enabled: bool | None`
> > default = `None`
> > Whether to allow basic telemetry. If None, will use GRADIO_ANALYTICS_ENABLED environment variable or default to True.
> 
> https://www.gradio.app/docs/gradio/blocks#initialization

Thanks. I figured it would be in launch() not the actual component declaration. Appreciated
