### ISSUE TITLE
Audio streaming not working for large files

### ISSUE THREAD

**Issue by thewh1teagle** [gradio-app/gradio#9355]
### Describe the bug

I have gr demo with audio and it send 1MB of audio. the audio can be played only when the whole data loaded which take some time on mobile devices / slow networks.
The problem is that the audio compoent doesn't even display loading when it's not fully loaded and playable. 
I tried to implement streaming but it doesn't work either. I yield the samples and it simply not display or play them.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://github.com/thewh1teagle/israwave/blob/main/ui/app.py

### System Info

```shell
hugginface / local
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @thewh1teagle ! Thanks for sharing the code. You need to set `streaming=True` in the output component (https://github.com/thewh1teagle/israwave/blob/0c8f42f2e231b41bdd5c04c4c890f89d382b3b4c/ui/app.py#L52) to use streaming and you also have to change the `create` function to be an iterator. 

> The problem is that the audio compoent doesn't even display loading when it's not fully loaded and playable.

Hmm there should be an upload progress indicator when you upload the audio file

**Comment by thewh1teagle** [comment]
> Hmm there should be an upload progress indicator when you upload the audio file

It's not uploader. it shows the audio after we click create.
I don't use `streaming=True` because it doesn't work. when changing to `streaming=True` and returning iterator it doesnt load

**Comment by freddyaboulton** [comment]
@thewh1teagle I opened a PR in your repo to fix the demo. It works now

BTW this model's speed is so impressive. Please share how you built it. I've struggled with TTS in python in the past and whatever you did would be really beneficial for the community!


https://github.com/user-attachments/assets/b12366c1-534d-4189-83bf-60eeb20846b0
