### ISSUE TITLE
Typeable value on gradio.Slider

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#936]
**Is your feature request related to a problem? Please describe.**
Currently the only way to move it is actually moving the slider. 

**Describe the solution you'd like**
The input slider could have a typeable element so the user could type the value and snap to it

**Comment by abidlabs** [comment]
We can think about this and see if we can find a UI that isn't too complex. Thanks for creating these issues @apolinario!

**Comment by apolinario** [comment]
I would say that the UI could look exactly the same, maybe with some small visual indication that the field is typeable. Maybe worth on user testing seeing if people already *try* to click there thinking it is typeable. I did it and it may be the case many more users do

**Comment by apolinario** [comment]
Another usecase for this is fine adjustments. My model has a 0.1 step on 0 to 100. If is very painful to get to the right place. 
![image](https://user-images.githubusercontent.com/788417/162067106-8d25aa21-39f4-44cc-8557-ccf2a6abc45c.png)
If I could just click on 29.3 and adjust, I don't think it would add complexity (on the backend yeah, but on the frotn-end no) and it would be a potential huge win

**Comment by abidlabs** [comment]
A related feedback is "increment buttons as an option for sliders, currently on 4k displays where there's a large slider max value and a small step value it's pretty hard to get the exact value you want"

**Comment by NimaBoscarino** [comment]
Just bumping this to link a forum post with this request: https://discuss.huggingface.co/t/stable-diffusion-seed-selection-in-webpage-app/

**Comment by abidlabs** [comment]
Thanks @NimaBoscarino! I agree we should get this out soon -- @pngwn or @dawoodkhan82 do you have bandwidth for this?

**Comment by dawoodkhan82** [comment]
Sure I can work on it. I think Typeable makes sense. Not sure we need the increment button if it's typeable.

**Comment by abidlabs** [comment]
Agreed, I think one or the other is sufficient
