### ISSUE TITLE
Implementation of a collapsible accordion (for advanced options for e.g.)

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#938]
**Is your feature request related to a problem? Please describe.**
Sometimes way too many options and parameters are exposed to the user and the UI gets cluttered.

**Describe the solution you'd like**
There could be an accordion component, similar to Streamlit's `st.expander` https://docs.streamlit.io/library/api-reference/layout/st.expander that enables you to hide certain options inside of it

**Comment by abidlabs** [comment]
Agreed, this could be helpful for UIs with many inputs and parameters. cc @aliabid94 @pngwn @AK391

**Comment by abidlabs** [comment]
This would also be useful for general Blocks to collapse certain sections of a long Block. For example, I'm trying to implement this in Blocks:

![image](https://user-images.githubusercontent.com/1778297/162820290-18caaa18-1c64-447e-abed-5d2aee346030.png)
