### ISSUE TITLE
inputs attribute 

### ISSUE THREAD

**Issue by anilkilickaplan** [gradio-app/gradio#939]
### Describe the bug

AttributeError: module 'gradio' has no attribute 'inputs'

### Reproduction

Please check VQGAN CLIP text-to-image work by 
https://colab.research.google.com/drive/1Foi0mCSE6NrW9oI3Fhni7158Krz4ZXdH?usp=sharing#scrollTo=TkUfzT60ZZ9q

It generates 
"AttributeError: module 'gradio' has no attribute 'inputs'" error message.

### System Info

```shell
Firefox, python 3.7.13
```

### Severity

blocker

**Comment by abidlabs** [comment]
Hi @anilkilickaplan, thanks for creating this issue. This usually just means that gradio wasn't installed successfully. Try pip uninstall gradio and pip install gradio to reinstall Gradio.

Closing as this has already been addressed in #613 and #195
