### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by romagedn** [gradio-app/gradio#9410]
### Describe the bug

Hello, I often get this error stack when I use gradio to draw a complex page, include tab, button, dynamic items create by @render, and etc. It totally has ~1000 components in one page.

I dont find this error on any simple page ever. So I guess it caused by some asynchronization mechanism inside Gradio when render a huge page. Then I move all buttons out of the @render functions, and only keep textbox, labels, markdown and  insode the @render. This method reduce the error occurs, expecially when keep clicking one button may trigger rerender event by change a gradio.Stste(). But the error still happens every minutes.

Can you guys help to solve the problem, or give me some advice how to avoid this error, thanks

---------------------------------

Traceback (most recent call last):
  File "/home/centurygame/Downloads/miniconda3/envs/gpt_backend/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/centurygame/Downloads/miniconda3/envs/gpt_backend/lib/python3.10/site-packages/gradio/route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/centurygame/Downloads/miniconda3/envs/gpt_backend/lib/python3.10/site-packages/gradio/blocks.py", line 1986, in process_api
    output["render_config"] = state.blocks_config.get_config(
  File "/home/centurygame/Downloads/miniconda3/envs/gpt_backend/lib/python3.10/site-packages/gradio/blocks.py", line 869, in get_config
    for _id, block in self.blocks.items():
RuntimeError: dictionary changed size during iteration

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### Logs

```shell
Traceback (most recent call last):
  File "/home/centurygame/Downloads/miniconda3/envs/gpt_backend/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/centurygame/Downloads/miniconda3/envs/gpt_backend/lib/python3.10/site-packages/gradio/route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/centurygame/Downloads/miniconda3/envs/gpt_backend/lib/python3.10/site-packages/gradio/blocks.py", line 1986, in process_api
    output["render_config"] = state.blocks_config.get_config(
  File "/home/centurygame/Downloads/miniconda3/envs/gpt_backend/lib/python3.10/site-packages/gradio/blocks.py", line 869, in get_config
    for _id, block in self.blocks.items():
RuntimeError: dictionary changed size during iteration
```

### System Info

```shell
4.42.0
```

### Severity

I can work around it

**Comment by pngwn** [comment]
Please provide a minimal reproduction of this issue so we can look into it. 

Closing until we have a repro.

**Comment by romagedn** [comment]
thanks for your response

~ I can't give you a minimal reproduction. I can post my page code here. May be you can have a look, and find out if something is not suitable to the best practise.

I an sorry, the code is a bit long.


------------------------------------------------------------------------------------------------------------

import json
import socket
import gradio

from helper import helper
from puzzle.structure.puzzle_operate import puzzle_operate, puzzle_operate_type
from puzzle.structure.puzzle_instances import puzzle_instance, puzzle_action, puzzle_action_condition, puzzle_action_possible, puzzle_player_action
from puzzle.structure.puzzle_object import puzzle_object
from puzzle.structure.puzzle_heap import puzzle_heap, puzzle_heap_event, puzzle_heap_status
from puzzle.structure.puzzle_plan import puzzle_condition_api
from puzzle.puzzle_simulate import puzzle_simulate, languages
from puzzle.prompt.prompt_helper import prompt_helper
from puzzle.structure.puzzle_process import puzzle_role
from utils.utilsFile import UtilsFile


def create_page_readme(simulate_state):
    with gradio.Tab('readme') as page:
        refresh_state = gradio.State(0)

        gradio.Markdown(f'------------------------------------------------------------')
        gradio.Markdown('## condition')
        for item in puzzle_condition_api:
            with gradio.Row():
                gradio.Textbox(label="api", placeholder='', value=item.name, show_label=False)
                gradio.Textbox(label="usage", placeholder='', value=item.value, show_label=False, scale=2)

        gradio.Markdown(f'------------------------------------------------------------')
        gradio.Markdown('## events')
        for item in puzzle_heap_event:
            with gradio.Row():
                if '@' not in item.value:
                    gradio.Textbox(label="event", placeholder='', value=item.value, show_label=False, scale=2)

        gradio.Markdown(f'------------------------------------------------------------')
        gradio.Markdown('## dragon status')
        for item in puzzle_heap_status:
            with gradio.Row():
                gradio.Textbox(label="status", placeholder='', value=item.value, show_label=False, scale=2)

        gradio.Markdown(f'------------------------------------------------------------')
        gradio.Markdown('## operates')
        for item in puzzle_operate_type:
            with gradio.Row():
                gradio.Textbox(label="name", placeholder='', value=item.name, show_label=False)
                gradio.Textbox(label="usage", placeholder='', value=item.value, show_label=False, scale=2)

def create_page_stacks(simulate_state):
    with gradio.Tab('stacks') as page:
        refresh_state = gradio.State(0)

        def on_refresh(refresh):
            refresh += 1
            return refresh

        c_refresh = gradio.Button("refresh")
        c_refresh.click(
            fn=on_refresh,
            inputs=[refresh_state],
            outputs=[refresh_state]
        )

        @gradio.render(inputs=[refresh_state, simulate_state])
        def refresh(refresh, simulate: puzzle_simulate):
            for log in reversed(simulate.system_log.logs):
                e = log.msg
                n_lines = e.count('\n') + 1
                c_stack = gradio.Textbox(label="stack", placeholder='', value=e, lines=n_lines)

def create_page_prompts(simulate_state):
    with gradio.Tab('prompts') as page:
        refresh_state = gradio.State(0)

        def on_refresh(refresh):
            refresh += 1
            return refresh

        c_refresh = gradio.Button("refresh")
        c_refresh.click(
            fn=on_refresh,
            inputs=[refresh_state],
            outputs=[refresh_state]
        )

        @gradio.render(inputs=[refresh_state, simulate_state])
        def refresh(refresh, simulate: puzzle_simulate):
            for event in reversed(simulate.scene.process.steps):
                if not event.prompt:
                    continue

                def on_regenerate(c_modelId, c_temperature, c_max_tokens, c_json, c_prompt, c_output):
                    output = prompt_helper.re_generate(c_modelId, c_temperature, c_max_tokens, c_json, c_prompt, False)
                    return output

                def on_analyze(c_modelId, c_temperature, c_max_tokens, c_json, c_prompt, c_output):
                    output = prompt_helper.re_generate(c_modelId, c_temperature, c_max_tokens, c_json, c_prompt, True)
                    return output

                gradio.Textbox(label="message", placeholder='', value=event.source_message)
                with gradio.Row():
                    c_modelId = gradio.Textbox(label="modelId", placeholder='', value=event.modelId, interactive=False)
                    c_temperature = gradio.Textbox(label="temperature", placeholder='', value=event.temperature, interactive=False)
                    c_max_tokens = gradio.Textbox(label="max_tokens", placeholder='', value=event.max_tokens, interactive=False)
                    c_json = gradio.Textbox(label="json_mode", placeholder='', value=event.json_mode, interactive=False)
                with gradio.Row():
                    c_prompt = gradio.Textbox(label="prompt", placeholder='', value=event.prompt, interactive=True, lines=10)
                    c_output = gradio.Textbox(label="output", placeholder='', value='', interactive=False)

                with gradio.Row():
                    c_regenerate = gradio.Button("re-generate")
                    c_regenerate.click(
                        fn=on_regenerate,
                        inputs=[c_modelId, c_temperature, c_max_tokens, c_json, c_prompt, c_output],
                        outputs=[c_output]
                    )

                    c_analyze = gradio.Button("analyze")
                    c_analyze.click(
                        fn=on_analyze,
                        inputs=[c_modelId, c_temperature, c_max_tokens, c_json, c_prompt, c_output],
                        outputs=[c_output]
                    )


def create_page_scene(simulate_state):
    with gradio.Tab('scene') as page:
        refresh_state = gradio.State(0)

        with gradio.Row():
            c_load_excel = gradio.UploadButton("load_excel", file_count="single", file_types=['.xlsx'], scale=0)
            c_load_json = gradio.UploadButton("load_json", file_count="single", file_types=['.json', '.txt', '.bytes'], scale=0)
        c_errors = gradio.Textbox(label="errors", placeholder='', value='')

        def on_load_excel(filename, refresh, simulate: puzzle_simulate):
            try:
                errors = simulate.load_scene(filename)
                errors = '\n'.join(errors)

                # simulate.start_test()
                msg = 'success to load: ' + filename
                gradio.Info(msg, duration=3)
                print(msg)
                simulate.system_log.add_log(msg)

                content = simulate.scene.export_to_json()
                temp_filename = helper.get_temp_file() + '.json'
                UtilsFile.writeFileLines(temp_filename, [content], encoding='utf-8')

            except Exception as e:
                import traceback
                msg = 'fail to load excel: ' + filename + '\n' + traceback.format_exc()
                gradio.Warning(msg)
                print(msg)
                simulate.system_log.add_log(msg)
                errors = 'load scene crashed, see stacks for more information'

            refresh += 1
            return errors, refresh

        c_load_excel.upload(
            fn=on_load_excel,
            inputs=[c_load_excel, refresh_state, simulate_state],
            outputs=[c_errors, refresh_state]
        )

        def on_load_json(filename, refresh, simulate: puzzle_simulate):
            try:
                errors = simulate.load_scene_json(filename)
                errors = '\n'.join(errors)

                # simulate.start_test()
                msg = 'success to load json: ' + filename
                gradio.Info(msg, duration=3)
                print(msg)
                simulate.system_log.add_log(msg)

                # content = simulate.scene.export_to_json()
                # temp_filename = helper.get_temp_file() + '.json'
                # UtilsFile.writeFileLines(temp_filename, [content], encoding='utf-8')

            except Exception as e:
                import traceback
                msg = 'fail to load: ' + filename + '\n' + traceback.format_exc()
                gradio.Warning(msg)
                print(msg)
                simulate.system_log.add_log(msg)
                errors = 'load scene crashed, see stacks for more information'

            refresh += 1
            return errors, refresh

        c_load_json.upload(
            fn=on_load_json,
            inputs=[c_load_json, refresh_state, simulate_state],
            outputs=[c_errors, refresh_state]
        )

        @gradio.render(inputs=[refresh_state, simulate_state])
        def refresh(refresh, simulate: puzzle_simulate):

            gradio.Markdown(f'------------------------------------------------------------')
            gradio.Markdown('## scene')
            gradio.Textbox(label="desc", placeholder='', value=simulate.scene.desc)
            gradio.Textbox(label="desc", placeholder='', value=simulate.scene.goal)

            gradio.Markdown(f'------------------------------------------------------------')
            gradio.Markdown('## object')
            gradio.Textbox(label="object", placeholder='', value=str(len(simulate.scene.objects)))
            for object in simulate.scene.objects:
                object: puzzle_object = object

                gradio.Markdown(f'------------------------------------------------------------')
                gradio.Markdown('#### ' + object.name)
                with gradio.Row():
                    gradio.Textbox(label="prototype_name", placeholder='', value=object.name)
                    gradio.Textbox(label="appearance", placeholder='', value=object.appearance, scale=2)
                    gradio.Textbox(label='desc', placeholder='', value=object.desc, scale=2)


            gradio.Markdown(f'------------------------------------------------------------')
            gradio.Markdown('## instance')
            gradio.Textbox(label="instance_count", placeholder='', value=str(len(simulate.scene.instances)))
            for instance in simulate.scene.instances:
                instance: puzzle_instance = instance

                gradio.Markdown(f'------------------------------------------------------------')
                gradio.Markdown('#### ' + instance.instance_id)
                with gradio.Row():
                    gradio.Textbox(label="prototype_name", placeholder='', value=instance.object_name)
                    gradio.Textbox(label="name", placeholder='', value=instance.instance_id)
                    gradio.Textbox(label="location", placeholder='', value=instance.location)
                    gradio.Textbox(label="attribute", placeholder='', value=instance.attribute)
                    gradio.Textbox(label='visible', placeholder='', value=instance.visible, scale=0)

                gradio.Markdown('##### << dragon actions >>')
                for action in instance.actions_operates:
                    action: puzzle_action = action
                    gradio.Markdown('###### ')

                    with gradio.Row():
                        with gradio.Column():
                            gradio.Textbox(label="operate_type", placeholder='', value=action.name)
                            gradio.Textbox(label="enabled", placeholder='', value=action.enabled)

                        with gradio.Column(scale=3):
                            for condition in action.conditions:
                                condition: puzzle_action_condition = condition

                                with gradio.Row():
                                    gradio.Textbox(label="condition", placeholder='', value=condition.condition, scale=0)

                                    with gradio.Column():
                                        for possible in condition.possibles:
                                            possible: puzzle_action_possible = possible

                                            with gradio.Row():
                                                gradio.Textbox(label="possible", placeholder='', value=str(possible.possible), scale=0)

                                                with gradio.Column():
                                                    operates: list[puzzle_operate] = possible.operates
                                                    for operate in operates:
                                                        operate: puzzle_operate = operate

                                                        with gradio.Row():
                                                            c_type = gradio.Textbox(label="type", placeholder='', value=operate.type.name, show_label=False)
                                                            c_target = gradio.Textbox(label="target", placeholder='', value=operate.target, show_label=False, scale=2)


                gradio.Markdown('##### << player actions >>')
                for player_action in instance.player_actions_operates:
                    player_action: puzzle_player_action = player_action
                    gradio.Markdown('###### ')
                    with gradio.Row():
                        gradio.Textbox(label="operate_type", placeholder='', value=player_action.name)
                        gradio.Textbox(label="enabled", placeholder='', value=player_action.enabled, scale=0)

                        with gradio.Column(scale=2):
                            operates: list[puzzle_operate] = player_action.operates
                            for operate in operates:
                                operate: puzzle_operate = operate
                                with gradio.Row():
                                    c_type = gradio.Textbox(label="type", placeholder='', value=operate.type.name, show_label=False)
                                    c_target = gradio.Textbox(label="target", placeholder='', value=operate.target, show_label=False, scale=2)


            gradio.Markdown(f'------------------------------------------------------------')
            gradio.Markdown('## plans')
            for plan in simulate.scene.plans:
                with gradio.Row():
                    gradio.Textbox(label="id", placeholder='', value=plan.id, show_label=False, scale=0)
                    gradio.Textbox(label="condition", placeholder='', value=plan.condition, show_label=False)
                    gradio.Textbox(label="type", placeholder='', value=plan.operate.type.name, show_label=False)
                    gradio.Textbox(label="target", placeholder='', value=plan.operate.target, show_label=False, scale=2)

            gradio.Markdown(f'------------------------------------------------------------')
            gradio.Markdown('## actions')
            for action_name in simulate.scene.actions_mapping:
                action_define = simulate.scene.actions_mapping[action_name]
                with gradio.Row():
                    gradio.Textbox(label="name", placeholder='', value=action_name, show_label=False)
                    gradio.Textbox(label="instruction", placeholder='', value=action_define.action_name, show_label=False)
                    gradio.Textbox(label="parameters", placeholder='', value=json.dumps(action_define.parameters), show_label=False)


def create_page_test(simulate_state):
    with gradio.Tab('test') as page:
        refresh_state = gradio.State(0)

        # llm
        with gradio.Row():
            c_temperature = gradio.Textbox(label="temperature", placeholder='', value="0.1", interactive=True)
            c_model = gradio.Dropdown(
                helper.get_model_optionals(),
                value='gpt4',
                label="model",
                interactive=True
            )
            c_language = gradio.Dropdown(
                languages.get_all_languages(),
                value=languages.get_all_languages()[0], # simulate.language.value,
                label="language",
            )

            def on_change_language(language, simulate: puzzle_simulate):
                simulate.set_language(language)
                return

            c_language.change(
                fn=on_change_language,
                inputs=[c_language, simulate_state],
                outputs=[],
            )

        # header
        with gradio.Row():

            def on_reset(refresh, simulate: puzzle_simulate):
                try:
                    success = simulate.start_test()
                    if not success:
                        gradio.Info("reload game file before restart !")
                except Exception as e:
                    import traceback
                    msg = 'fail to run next_step\n' + traceback.format_exc()
                    gradio.Warning(msg)
                    print(msg)
                    simulate.system_log.add_log(msg)

                refresh += 1
                return refresh

            c_reset = gradio.Button("restart game test", scale=0)
            c_reset.click(
                fn=on_reset,
                inputs=[refresh_state, simulate_state],
                outputs=[refresh_state],
            )

            def on_refresh(refresh, simulate: puzzle_simulate):
                refresh += 1
                return refresh

            c_refresh = gradio.Button("refresh page", scale=0)
            c_refresh.click(
                fn=on_refresh,
                inputs=[refresh_state, simulate_state],
                outputs=[refresh_state],
            )

        @gradio.render(inputs=[refresh_state, simulate_state])
        def refresh_instance(refresh, simulate: puzzle_simulate):
            gradio.Markdown(f'------------------------------------------------------------')
            gradio.Markdown(f'## living objects: {simulate.get_living_instances_count()}')
            for instance in simulate.scene.instances:
                if instance.visible:
                    with gradio.Row():
                        gradio.Textbox(label="name", placeholder='', value=instance.instance_id, show_label=False)
                        gradio.Textbox(label="location", placeholder='', value=instance.location, show_label=False, scale=2)
                        gradio.Textbox(label="attribute", placeholder='', value=instance.attribute, show_label=False, scale=2)

                        with gradio.Column():
                            for action in instance.player_actions_operates:
                                if simulate.is_player_action_runnable(action):

                                    def on_player_action(action):
                                        def fun(temperature, model, refresh, simulate: puzzle_simulate):
                                            if simulate.has_action():
                                                gradio.Info('complete padding actions firstly', duration=3)
                                                refresh += 1
                                                return refresh

                                            if not simulate.is_player_action_runnable(action):
                                                gradio.Info('do player action fail', duration=3)
                                                refresh += 1
                                                return refresh

                                            gradio.Info('running player action', duration=3)
                                            llm_params = puzzle_simulate.build_llm_params(temperature, 4096, model)
                                            simulate.do_player_action(action, llm_params)

                                            refresh += 1
                                            return refresh
                                        return fun

                                    c_play_action = gradio.Button(action.name, interactive=True, scale=0)
                                    c_play_action.click(
                                        fn=on_player_action(action),
                                        inputs=[c_temperature, c_model, refresh_state, simulate_state],
                                        outputs=[refresh_state],
                                    )

            with gradio.Row():
                with gradio.Column():
                    gradio.Markdown(f'------------------------------------------------------------')
                    gradio.Markdown(f'## padding actions: {len(simulate.padding_actions)}')
                    for action in simulate.padding_actions:
                        with gradio.Row():
                            gradio.Textbox(label="reason", placeholder='', value=action.reason, show_label=False)
                            gradio.Textbox(label="type", placeholder='', value=action.type.name, show_label=False)
                            gradio.Textbox(label="target", placeholder='', value=action.target, show_label=False, scale=2)

                with gradio.Column():
                    gradio.Markdown(f'------------------------------------------------------------')
                    gradio.Markdown(f'## heap: {len(simulate.scene.heap.heap)}')
                    for key, value in simulate.scene.heap.heap.items():
                        with gradio.Row():
                            gradio.Textbox(label="key", placeholder='', value=key, show_label=False)
                            gradio.Textbox(label="value", placeholder='', value=value, show_label=False)

        @gradio.render(inputs=[refresh_state, simulate_state])
        def refresh_monitor(refresh, simulate: puzzle_simulate):

            gradio.Markdown(f'------------------------------------------------------------')
            with gradio.Row():
                with gradio.Column():
                    gradio.Markdown(f'## monitor')
                    gradio.Markdown(f'#### {simulate.get_game_status()}')

                # pading actions
                gradio.Textbox(label="n_instances", placeholder='', value=simulate.get_living_instances_count())
                gradio.Textbox(label="n_padding_actions", placeholder='', value=simulate.get_actions_count())

        @gradio.render(inputs=[refresh_state, simulate_state], triggers=[c_reset.click])
        def refresh_console(refresh, simulate: puzzle_simulate):
            with gradio.Row():
                input_label = "input ( unavailable when has padding actions )"
                c_input = gradio.Textbox(label=input_label, placeholder='input here', value='', interactive=True, scale=3)
                c_next_step = gradio.Button("next_one_step", interactive=True, scale=0)
                c_next_turn = gradio.Button("next_all_steps", interactive=True, scale=0)

                def on_next_turn(temperature, model, refresh, simulate: puzzle_simulate):
                    try:
                        gradio.Info('running all actions', duration=3)
                        llm_params = puzzle_simulate.build_llm_params(temperature, 4096, model)
                        info = simulate.run_next_turn(llm_params)
                        if info:
                            gradio.Info(info, duration=3)
                        else:
                            gradio.Info('complete running all actions', duration=3)
                    except Exception as e:
                        import traceback
                        msg = 'fail to run next_step\n' + traceback.format_exc()
                        gradio.Warning(msg)
                        print(msg)
                        simulate.system_log.add_log(msg)

                    refresh += 1
                    return refresh

                def on_next_step(temperature, model, refresh, simulate: puzzle_simulate):
                    try:
                        gradio.Info('running action', duration=3)
                        llm_params = puzzle_simulate.build_llm_params(temperature, 4096, model)
                        info = simulate.run_next_step(llm_params)
                        if info:
                            gradio.Info(info, duration=3)
                    except Exception as e:
                        import traceback
                        msg = 'fail to run next_step\n' + traceback.format_exc()
                        gradio.Warning(msg)
                        print(msg)
                        simulate.system_log.add_log(msg)

                    refresh += 1
                    return refresh

                def on_input(textfield, temperature, model, refresh, simulate: puzzle_simulate):
                    if simulate.has_action():
                        gradio.Info('complete padding actions firstly', duration=3)
                        refresh += 1
                        return textfield, refresh

                    try:
                        llm_params = puzzle_simulate.build_llm_params(temperature, 4096, model)
                        info = simulate.generate_response(textfield, llm_params)
                        if info:
                            gradio.Info(info, duration=3)
                    except Exception as e:
                        import traceback
                        msg = 'fail to response\n' + traceback.format_exc()
                        gradio.Warning(msg)
                        print(msg)
                        simulate.system_log.add_log(msg)

                    refresh += 1
                    return '', refresh

                c_next_step.click(
                    fn=on_next_step,
                    inputs=[c_temperature, c_model, refresh_state, simulate_state],
                    outputs=[refresh_state],
                )
                c_next_turn.click(
                    fn=on_next_turn,
                    inputs=[c_temperature, c_model, refresh_state, simulate_state],
                    outputs=[refresh_state],
                )
                c_input.submit(
                    fn=on_input,
                    inputs=[c_input, c_temperature, c_model, refresh_state, simulate_state],
                    outputs=[c_input, refresh_state],
                )

        @gradio.render(inputs=[refresh_state, simulate_state], triggers=[c_reset.click])
        def refresh_trigger(refresh, simulate: puzzle_simulate):

            # triggers
            all_triggers = simulate.scene.get_all_triggers()
            for trigger in all_triggers:
                with gradio.Row():
                    gradio.Textbox(label="id", placeholder='', value=trigger.id, show_label=False, scale=0)
                    gradio.Textbox(label="type", placeholder='', value=trigger.operate.type.name, show_label=False)
                    gradio.Textbox(label="target", placeholder='', value=trigger.operate.target, show_label=False, scale=2)
                    c_do_trigger = gradio.Button(trigger.condition, interactive=True, scale=0)
                    c_do_trigger10 = gradio.Button('run 3 times', interactive=True, scale=0)

                    def on_do_trigger(trigger):
                        def fun(temperature, model, refresh, simulate: puzzle_simulate):
                            if simulate.has_action():
                                gradio.Info('complete padding actions firstly', duration=3)
                                refresh += 1
                                return refresh

                            gradio.Info('running trigger', duration=3)
                            llm_params = puzzle_simulate.build_llm_params(temperature, 4096, model)
                            trigger.execute(simulate, llm_params)

                            refresh += 1
                            return refresh
                        return fun

                    def on_do_trigger10(trigger):
                        def fun(temperature, model, refresh, simulate: puzzle_simulate):
                            for i in range(3):
                                if simulate.has_action():
                                    gradio.Info('complete padding actions firstly', duration=3)
                                    refresh += 1
                                    return refresh

                                gradio.Info('running trigger', duration=3)
                                llm_params = puzzle_simulate.build_llm_params(temperature, 4096, model)
                                trigger.execute(simulate, llm_params)
                            gradio.Info('complete running triggers', duration=3)

                            refresh += 1
                            return refresh
                        return fun

                    c_do_trigger.click(
                        fn=on_do_trigger(trigger),
                        inputs=[c_temperature, c_model, refresh_state, simulate_state],
                        outputs=[refresh_state],
                    )
                    c_do_trigger10.click(
                        fn=on_do_trigger10(trigger),
                        inputs=[c_temperature, c_model, refresh_state, simulate_state],
                        outputs=[refresh_state],
                    )

        @gradio.render(inputs=[refresh_state, simulate_state])
        def refresh_dialog(refresh, simulate: puzzle_simulate):

            # dialog
            dialogs = []
            for event in simulate.scene.process.steps:
                if event.speaker != puzzle_role.background:
                    dialogs.append(f'[{event.speaker.name}]: {event.source_message}')
            with gradio.Row():
                gradio.Textbox(label="dialogs (new -> old)", placeholder='', value='\n\n'.join(reversed(dialogs)), lines=30)
                gradio.Textbox(label="logs (new -> old)", placeholder='', value=simulate.logs.get_logs_str(True), lines=30)

        @gradio.render(inputs=[refresh_state, simulate_state], triggers=[c_reset.click])
        def refresh_memory(refresh, simulate: puzzle_simulate):

            # memory
            gradio.Markdown(f'------------------------------------------------------------')
            with gradio.Row():
                gradio.Markdown('## memory')
                c_user_name = gradio.Textbox(label="user_name", placeholder='', value=simulate.knowledge.uid, interactive=True)
                c_load_mem = gradio.Button('load memory', interactive=True, scale=0)
                c_generate_mem = gradio.Button('generate memory', interactive=True, scale=0)
                c_upload_mem = gradio.Button('upload memory', interactive=True, scale=0)
            c_mem = gradio.Textbox(label="memory", placeholder='', value=simulate.knowledge.knowledge, show_label=False)

            def on_change_mem(c_user_name, c_mem, refresh, simulate: puzzle_simulate):
                simulate.knowledge.set(c_user_name, c_mem)
                return
            c_user_name.change(
                fn=on_change_mem,
                inputs=[c_user_name, c_mem, refresh_state, simulate_state],
                outputs=[],
            )
            c_mem.change(
                fn=on_change_mem,
                inputs=[c_user_name, c_mem, refresh_state, simulate_state],
                outputs=[],
            )

            def on_load_mem(refresh, simulate: puzzle_simulate):
                if simulate.knowledge.uid == '':
                    gradio.Info('set user name firstly', duration=3)
                    refresh += 1
                    return refresh

                gradio.Info('downloading memory', duration=3)
                simulate.knowledge.download()

                refresh += 1
                return simulate.knowledge.knowledge, refresh

            def on_generate_mem(temperature, model, refresh, simulate: puzzle_simulate):
                llm_params = puzzle_simulate.build_llm_params(temperature, 4096, model)
                simulate.generate_memory(llm_params)

                refresh += 1
                return simulate.knowledge.knowledge, refresh

            def on_upload_mem(refresh, simulate: puzzle_simulate):
                gradio.Info('uploading memory', duration=3)
                simulate.knowledge.upload()

                refresh += 1
                return refresh

            c_load_mem.click(
                fn=on_load_mem,
                inputs=[refresh_state, simulate_state],
                outputs=[c_mem, refresh_state],
            )
            c_generate_mem.click(
                fn=on_generate_mem,
                inputs=[c_temperature, c_model, refresh_state, simulate_state],
                outputs=[c_mem, refresh_state],
            )
            c_upload_mem.click(
                fn=on_upload_mem,
                inputs=[refresh_state, simulate_state],
                outputs=[refresh_state],
            )


# main
if __name__ == '__main__':
    with gradio.Blocks() as demo:
        _simulate_state = gradio.State(puzzle_simulate())
        create_page_readme(_simulate_state)
        create_page_scene(_simulate_state)
        create_page_test(_simulate_state)
        create_page_prompts(_simulate_state)
        create_page_stacks(_simulate_state)

    host_ip = socket.gethostbyname(socket.gethostname())
    demo.launch(show_error=True, server_name='0.0.0.0', server_port=helper.PORT_PUZZLE)
