### ISSUE TITLE
Fix Plotly and Altair plots in `5.0-dev` branch

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#9418]

**Comment by whitphx** [comment]
hmm it's a general bug on `gr.Plot`, not a Lite specific?

```python
import gradio as gr
import numpy as np
import plotly.express as px
import pandas as pd

countries = ["USA", "Canada", "Mexico", "UK"]

def fn():
    df = pd.DataFrame({
        "day": np.arange(0, 100)
    })

    fig = px.line(df)

    return fig


demo = gr.Interface(
    fn=fn,
    inputs=None,
    outputs=gr.Plot()
)

demo.launch()
```

![CleanShot 2024-09-24 at 14 05 36@2x](https://github.com/user-attachments/assets/d6e8744b-c598-4c77-8f82-8912bf38ebcb)

![CleanShot 2024-09-24 at 14 06 12@2x](https://github.com/user-attachments/assets/dc132038-58f6-4193-9a76-b6371c4bc397)

I'm investigating this problem in #9422

**Comment by whitphx** [comment]
* This error is not Lite specific.
    * I wonder why the normal E2E tests are passing.
* It was introduced in #9339 as described below.

---
### Reproduce the error

```python
import gradio as gr
import numpy as np
import pandas as pd
import plotly.express as px
from matplotlib import pyplot as plt


df = pd.DataFrame({
    "data": np.random.rand(100)
})

# Matplotlib plot works.
# fig = plt.figure()
# plt.plot(df["data"])

# Plotly plot causes error.
fig = px.line(df)

demo = gr.Interface(
    fn=lambda: None,
    inputs=gr.Plot(value=fig),
    outputs=None,
)

demo.launch()
```

---
8e52b6a3e75957462bc7fdbf6ff9c280084d5f08  (`4c8c6f2^`): It was working.
![CleanShot 2024-09-24 at 17 01 58@2x](https://github.com/user-attachments/assets/1ffdd876-b15d-4169-b09d-d80a494f9ad8)

---
4c8c6f2fe603081941c5fdc43f48a0632b9f31ad: It started to fail.

![CleanShot 2024-09-24 at 17 06 55@2x](https://github.com/user-attachments/assets/3af8f133-07f4-45d0-abd1-a0d3c1ecfb65)
![CleanShot 2024-09-24 at 17 07 15@2x](https://github.com/user-attachments/assets/702ad4a5-a31f-4d7b-9837-44df4ad58921)

This rev had another SSR error below, which is now fixed, btw.
```
ReferenceError: self is not defined
    at file:///Users/whitphx/ghq/github.com/gradio-app/gradio/gradio/templates/node/build/server/chunks/PlotlyPlot-BCAN8zg5.js:19:39
    at requirePlotly_min (file:///Users/whitphx/ghq/github.com/gradio-app/gradio/gradio/templates/node/build/server/chunks/PlotlyPlot-BCAN8zg5.js:20:4)
    at file:///Users/whitphx/ghq/github.com/gradio-app/gradio/gradio/templates/node/build/server/chunks/PlotlyPlot-BCAN8zg5.js:24:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
```

---
Current HEAD of `5.0-dev`, 74f3b9d: It's still failing.
![CleanShot 2024-09-24 at 17 10 09@2x](https://github.com/user-attachments/assets/ebb746ac-98fd-4a57-8d76-2f4f063556fb)
![CleanShot 2024-09-24 at 17 10 25@2x](https://github.com/user-attachments/assets/4f9dc952-aac5-458c-8a4e-830c8b73f102)
