### ISSUE TITLE
gr.Blocks: allow filepath for "head" argument

### ISSUE THREAD

**Issue by dechantoine** [gradio-app/gradio#9444]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Hello, is there any drawbacks for allowing filepath to the "head" parameter of gr.Blocks ? 
https://github.com/gradio-app/gradio/blob/98cbcaef827de7267462ccba180c7b2ffb1e825d/gradio/blocks.py#L1001
Shouldn't it be consistent with css and js ?
I have little knowledge about web development, sorry if this is completly irrelevant.

**Describe the solution you'd like**  
```        if head is not None and os.path.exists(head):
            with open(head, encoding="utf-8") as head_file:
                self.head = head_file.read()
        else:
            self.head = head
```

**Comment by abidlabs** [comment]
Hi @dechantoine we are actually making a change in Gradio 5.0 to treat strings as only code, and to require developers to pass in a `pathlib.Path` object when they are referring to a filepath. This is to avoid potential ambiguity and unexpected behavior. I've extended this logic to the `head` parameter as well here: https://github.com/gradio-app/gradio/pull/9448

**Comment by dechantoine** [comment]
Hello @abidlabs , thank you this will be much clearer that way 👍
