### ISSUE TITLE
stop_btn not working on gr.ChatInterface or with custom chat bot after retry_btn click - connection errored out error

### ISSUE THREAD

**Issue by goudakrishna** [gradio-app/gradio#9449]
### Describe the bug

Clicking on the stop_btn during response stream generation incase of retry_btn click, getting Connection errored out error. 
stop_btn cancelling the response stream in start_btn case without any errors.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import time
import gradio as gr

def slow_echo(message, history):
    for i in range(len(message)):
        time.sleep(0.5)
        yield "You typed: " + message[: i+1]

demo = gr.ChatInterface(slow_echo).queue()

if __name__ == "__main__":
    demo.launch()

```

### Screenshot

![image](https://github.com/user-attachments/assets/2b4bcd34-41f0-40eb-927d-9076260255cc)

### Logs

```shell
No errors in python.
Unexpected error Connection errored out. index.js:2036:28
   $e index.js:2036
    onerror index.js:1371
    onerror index.js:1370
    Qt index.js:1478
    Qt index.js:1470
    stream index.js:2251
    Vt index.js:1331
    Xt index.js:2135
    (Async: promise callback)
    Xt index.js:1993
```

### System Info

```shell
Gradio Version 4.37.2
```

### Severity

Blocking usage of gradio

**Comment by dawoodkhan82** [comment]
@goudakrishna Can you test to see if this is still an issue in the latest version of Gradio? We've fixed a lot of bugs with chat interface, and I can't seem to reproduce the error you're seeing.
