### ISSUE TITLE
DataFrame support from Files

### ISSUE THREAD

**Issue by merveenoyan** [gradio-app/gradio#945]
Gradio's file input takes file and doesn't do any preview of the file, and [DataFrame](https://gradio.app/docs/#i_dataframe) input doesn't really support any dataframe creation from files like a regular data science workflow with `pandas_dataframe.head()` would have in a colab. It would be better UX for data scientists to input a CSV/excel and have a head or tail of a dataset with as much columns/rows that they choose like you do with `df.head(5)` or `df.tail(5)` in pandas. A workaround we did with Keras working group is below and it's too much hassle. 
<img width="599" alt="Ekran Resmi 2022-04-07 16 40 27" src="https://user-images.githubusercontent.com/53175384/162248762-7296b848-1d2e-44ca-af37-1830f1dc4d24.png">
If you upload a file directly it looks like this which applies for CSV files as well, nothing informative about what model does, the features etc. 
![unknown](https://user-images.githubusercontent.com/53175384/162249528-1f486712-d0bb-4641-a0c9-5de276b4f25c.png)

Pinging @aliabid94 and @abidlabs here 🙌🏻

**Comment by abidlabs** [comment]
This would be super nice!! cc @pngwn as well -- it looks like the DataFrame component could be its own sprint!

**Comment by pngwn** [comment]
We have lots of Dataframe issues (both bugs and feature requests), and there will also be some design changes. I'm going to create a tracking issue for dataframe to collate feedback and discuss a path forwards.
