### ISSUE TITLE
Can we make use of component in Gallery?

### ISSUE THREAD

**Issue by TrieuDinhHo** [gradio-app/gradio#9455]
My app is outputing a bunch of images, and I need to use the gallery to visualize it. But I need to do 1 one step, I want to take the image information of each image I clicked. Is it possible?

**Comment by abidlabs** [comment]
Hi @TrieuDinhHo if I understand correctly that you'd like to run some code whenever you click on an image in the Gallery, yes that is possible, please see this example as a demo: https://github.com/gradio-app/gradio/blob/0f3d3e136a01e5290742dbd5a1e2f596ef871afd/demo/gallery_selections/run.py

By the way, for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
