### ISSUE TITLE
Gradio_client for LLama 3.2 vision model

### ISSUE THREAD

**Issue by chengchu88** [gradio-app/gradio#9465]
- [ x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I'd like to be able to use gradio_client to send image/text prompt to a hosted LLama3.2 vision model.

**Describe the solution you'd like**  
I'd like to see a code example how to assemble a prompt or request, api_name, etc.

**Additional context**

**Comment by abidlabs** [comment]
Hi @chengchu88, for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)
