### ISSUE TITLE
TensorBoard inside Gradio

### ISSUE THREAD

**Issue by Bebra777228** [gradio-app/gradio#9489]
- [x] I have searched to see if a similar issue already exists.

Some Gradio interfaces are used for training machine learning models. During this process, it is necessary to monitor TensorBoard graphs, which requires opening it in a separate browser tab. In some cases, this is not very convenient.

Is there a way to add support for individual graphs or the full TensorBoard interface in Gradio? This would simplify the use of the interface for training machine learning models.

**Comment by freddyaboulton** [comment]
Can you display tensorboard in an iframe in a gr.HTML component?

**Comment by Bebra777228** [comment]
Unfortunately, I'm not very knowledgeable in this area, so I suggest adding TensorBoard support to Gradio. I think this will simplify the process of integrating graphs into the interface.

I found some code that adds graphs to the interface, but it was too cumbersome, located in a separate file, and its functionality was limited. As far as I remember, it simply copied the image of the graph rather than the graph itself, and it couldn't be interacted with.

**Comment by freddyaboulton** [comment]
I think a `gr.Tensorboard` component would not belong in core. This would be a great custom component to develop however! 

https://www.gradio.app/guides/custom-components-in-five-minutes

**Comment by abidlabs** [comment]
Agreed!
