### ISSUE TITLE
[DOCS] Embedding demos for each component

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#949]
Our docs currently have demos linked to components, but the only way to see and use them is opening them in colab. The suggestion here is directly embedding the interfaces and the code side by side so that its a faster experience for the user. Links to colab will stay.

**Comment by aliabd** [comment]
Example:

This is currently only showing a screenshot of the interface, will be replaced with an embedded interface. Styling will also change.

https://user-images.githubusercontent.com/9021060/162326344-61fe64b3-2bc8-42ee-95ee-ebba131535c2.mov

**Comment by abidlabs** [comment]
Nice! Small suggestions: 
* Change "view" to "view code" and show the code tab first
* There seem to be too many buttons on the popup - view on GitHub, - Open in Colab, - the 2 tabs. Simplify the popup if possible

**Comment by aliabd** [comment]
Thanks @abidlabs I made some changes

* Changed 'view' to 'view code'
* Removed the tabs and now just showing the code and screenshot side-by-side
* Removed the github button. Not sure its super useful given the code is right there and you can open in colab. 

Still working on replacing the screenshot with an embedded interface

https://user-images.githubusercontent.com/9021060/162985727-cf68df20-6848-4fb8-9c78-7aa83fd99fdc.mov
