### ISSUE TITLE
Add microphone to `gr.MultimodalTextbox`

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#9494]
To support voice-in, text-out demos 

We could add a parameter `sources: list[str]` to `gr.MultimodalTextbox`, which is `["file"]` by default, but can be expanded to include `["file", "microphone"]`

**Comment by WizKnight** [comment]
Hi @abidlabs 🤗, I'm excited about the idea of adding voice input to `gr.MultimodalTextbox` !
I'd like to contribute and work on this. Do you have any specific points to consider before I start?

**Comment by WizKnight** [comment]
> Hi @WizKnight thanks for the interest in contributing. This is a relatively complex issue since it requires modifying both the frontend and backend of `gradio` in a manner that is consistent with the existing `gr.MultimodalTextbox`. Are you somewhat familiar with the `gradio` codebase already?

Thanks for the heads up! I'm eager to dive deeper and learn more while working on this.  I'm comfortable with both frontend and backend development.  Are there any specific resources or areas of the code you'd recommend I focus on to get started?

**Comment by abidlabs** [comment]
Sure, in that case please take a look at these two files
* gradio/components/multimodal_textbox.py
* js/multimodaltextbox/shared/MultimodalTextbox.svelte

**Comment by WizKnight** [comment]
> Sure, in that case please take a look at these two files
> 
> * gradio/components/multimodal_textbox.py
> * js/multimodaltextbox/shared/MultimodalTextbox.svelte

Alright! I'm on it👍

**Comment by WizKnight** [comment]
Hey @abidlabs , which speech-to-text engine should I use??

**Comment by abidlabs** [comment]
Hi @WizKnight you shouldn't convert to text, you should save the audio file as is (similarly to how it would be if you uploaded an audio file)

**Comment by abidlabs** [comment]
This is now complete, thanks folks!
