### ISSUE TITLE
[DOCS] Intro page with navigation to getting started, guides, or technical reference

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#952]
Originally suggested by @abidlabs, the idea is to have a landing page for docs that directs users where they want to go. The main motivation is that users with different levels of familiarity with gradio are going to want different things. For example someone who has never used gradio should be directed to getting started. 

In the future we can expand this to include all the other cool ideas we want to implement like the theme builder, playground, spaces search by gradio component, etc

**Comment by abidlabs** [comment]
Some websites that do this:
* https://docs.bokeh.org/en/latest/
* https://docs.streamlit.io/

Tbh I don't love either one of them, they're both very text heavy. We can do better

**Comment by aliabd** [comment]
Made a v1 of the page, thoughts @abidlabs? Agree on all fronts. 

Right now the bottom cards are placeholders until we build those pages!

**Comment by aliabd** [comment]
<img width="767" alt="Screen Shot 2022-04-12 at 12 40 45 AM" src="https://user-images.githubusercontent.com/9021060/162845262-1dcd723b-8fb0-41ea-9262-b7fd426198db.png">

**Comment by abidlabs** [comment]
Ooh I like this learn/play idea a lot! Can you share in a #gradio-technical to get other feedback as well?

Agreed, for "spaces gallery" and "theme builder", we can put a "coming soon" while we work on them.

**Comment by abidlabs** [comment]
Closing as we've decided we won't do this for now.
