### ISSUE TITLE
reads the avatar images from the temporary folder, not the related folder!

### ISSUE THREAD

**Issue by sajjadmosaheb** [gradio-app/gradio#9538]
### Describe the bug

As it is clear from the picture, the top right image is read from the static folder. But the avatar image and submit button image are read from a temporary folder. which sometimes does not exist like now and I have to reset and run the code again.
how can I set those to read from the relative folder too!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
with gr.Blocks(title="Coworker",css=css,fill_height=True,theme=theme) as sg:
    with gr.Row():
        with gr.Column(scale=1):
            logout_button = gr.Button("خروج",icon=None,variant='secondary',size='sm', link="/logout",scale=0)   
        with gr.Column(scale=9):
            gr.Markdown("<h1>Coworker(Beta)</h1>",rtl=True)
        with gr.Column(scale=10):
            gr.Markdown("<p><img src='/file=../static/sglogo-circle.png' width='50' height='50'></p>",rtl=True)
    with gr.Row():
        with gr.Group():
            textbox=gr.Textbox(rtl=True,placeholder="از من بپرس ...", container=False, scale=10,render=False)
            submit_btn=gr.Button(value="",icon="../static/sent.png",variant='primary',render=False,size='sm',scale=0)
            stop_btn=gr.Button(value="",icon="../static/stop.png",variant='stop',render=False,size='sm',scale=0)
            clear_btn= gr.ClearButton(value="🗑️",icon=None,variant='secondary',size='sm',render=False,scale=0)
            clear_btn.click(lambda :None, None)
    chatbot=gr.Chatbot(render=False,rtl=True,bubble_full_width=False,show_share_button=False,label='Coworker',show_label=False,render_markdown=True,show_copy_button=True,avatar_images=[None,"../static/coworkerlogo.png"],likeable=True,scale=7)
    chatbot.like(vote, None, None)
    gr.ChatInterface(main,
                        chatbot=chatbot,
                        textbox=textbox,
                        retry_btn=None,
                        analytics_enabled=False,               
                        undo_btn=None,
                        submit_btn=submit_btn,
                        stop_btn=stop_btn,
                        clear_btn=clear_btn)
sg.queue(default_concurrency_limit =None)
 sg.launch(favicon_path="../static/coworkerlogo.png", inline=False, inbrowser=True, allowed_paths=["../static/back.png", "../static/sglogo-circle.png", "../static/coworkerlogo.png"])
```

### Screenshot

![image](https://github.com/user-attachments/assets/618f9b24-2114-4191-8511-4a7c30ffb9d0)
![image](https://github.com/user-attachments/assets/400bf2a8-a0e2-4dea-ac68-05de3eea88d4)
![image](https://github.com/user-attachments/assets/9eddc2e8-7d74-4dfc-a453-aea9f068f9a8)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.31.5
gradio_client version: 0.16.4

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.3.0
fastapi: 0.110.1
ffmpy: 0.3.2
gradio-client==0.16.4 is not installed.
httpx: 0.27.2
huggingface-hub: 0.25.0
importlib-resources: 6.4.0
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.5.2
numpy: 1.26.4
orjson: 3.10.1
packaging: 23.2
pandas: 1.4.4
pillow: 9.2.0
pydantic: 2.9.2
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0
ruff: 0.3.7
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.11.0
urllib3: 2.2.1
uvicorn: 0.29.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.27.2
huggingface-hub: 0.25.0
packaging: 23.2
typing-extensions: 4.11.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by sajjadmosaheb** [comment]
Hi @abidlabs ,
can you check this please

**Comment by freddyaboulton** [comment]
Hi @sajjadmosaheb This is expected. For security reasons, Gradio will move files to the cache for icons and avatar images. That is currently not being done for any links in HTML/Markdown content. But starting in Gradio 5, only files in the cache or the current working directory will be served.

So `src='/file=../static/sglogo-circle.png'` will not work unless you add `../static/sglogo-circle.png` to `allowed_paths` parameter of Blocks.

Can you explain what you mean by the cache "sometimes not existing?

**Comment by sajjadmosaheb** [comment]
Hi @freddyaboulton thanks for your reply, 
I think I explained it wrong. see, this is exactly what I mean. I want the address of the avatars and the submit button to be in the same HTML format for security reasons.
This example you gave about file=../static/sglogo-circle.png is correct, by the way, there is a problem with the avatar, which gives the address like this, and I don't want the user information and the 
address of my system to be shown. look how show the adress of the avatar when open image in new tab!!
/file=C:/Users/sajjadm/AppData/Local/Temp/gradio/8ff9f47a04a7053412fba967d9d18a7fcae80550/coworkerlogo.png
And by "sometimes not existing," I mean that one time, it has the avatar, and sometimes, it doesn't! I checked the Temp folder, and it is empty! 
but when an image loads from the static folder in the working directory like the html image it will always be shown.
![bot-avatar2](https://github.com/user-attachments/assets/3283dad6-c642-4068-97c3-42a6d8ba7560)
![bot-avatar](https://github.com/user-attachments/assets/c1847fde-265a-4edc-9a17-eadd33d20df1)

**Comment by sajjadmosaheb** [comment]
Hi @freddyaboulton, any updates?

**Comment by sajjadmosaheb** [comment]
Hi @freddyaboulton @abidlabs ,
can you check this please.

**Comment by freddyaboulton** [comment]
Hi @sajjadmosaheb - can you set the images your want as static paths?

```python
import gradio as gr

gr.set_static_paths(paths=[...])
with gr.Blocks() as demo:
    ...
demo.launch()
```

Whatever you set as static won't be moved to the cache.

**Comment by sajjadmosaheb** [comment]
Hi @freddyaboulton, it is gonna be launched on the server so I can't set the static path for security reasons. And now I'm encounter new problem, when I try to set an image for background, sometimes the image will be ignored and just show the color and sometimes works fine randomly!!
theme = gr.themes.Default(),).set(
    background_fill_secondary_dark=  "url('/file=../static/back.png') no-repeat center / auto 150svh padding-box fixed",
    body_background_fill_dark= "url('/file=../static/back.png') no-repeat center / auto 150svh padding-box fixed",)
![image](https://github.com/user-attachments/assets/a6cc5ca6-e20f-43c4-bc26-f40df0ecabaf)
![image](https://github.com/user-attachments/assets/1d170366-b2f9-4877-9cb6-6484f7eea027)

**Comment by freddyaboulton** [comment]
The issue about the icon being moved to the cache will be fixed in #9765

**Comment by sajjadmosaheb** [comment]
I don't follow @freddyaboulton I want all images even avatar and background address look like this :
http://127.0.0.1:7871/file=../static/sglogo-circle.png
only the image in gr markdown looks right:
gr.Markdown("<p><img src='/file=../static/sglogo-circle.png' width='50' height='50'></p>",rtl=True)
others are wrong.

**Comment by abidlabs** [comment]
Hi @sajjadmosaheb we copy icon and avatar images to the cache because it ensures that the original images are not modified in any way on your local filesystem. We previously had a bug where these files in the cache were not being displayed correctly, but now (in `gradio==5.3.0`), they should be working fine.
