### ISSUE TITLE
Add the hover effect

### ISSUE THREAD

**Issue by SaumyaSubham** [gradio-app/gradio#9542]
- [x] I have searched to see if a similar issue already exists.
Yes, I have searched but no similar issue exists.

**Is your feature request related to a problem? Please describe.**  
On navbar you can see, There is no hover effect on community option and also no hover effect in companies even they are not highlighting.

**Describe the solution you'd like**  
I want to add the hover effect in the community option on the navbar and add a hover effect or at least highlight the companies so that the user can get the values from this company or the product offers.
Kindly assign this to me under hacktoberfest 2024.

![Screenshot 2024-10-05 165736](https://github.com/user-attachments/assets/a852e6dc-ba3a-42b1-b485-fd23406be151)

**Comment by pngwn** [comment]
We don’t want this to be an advert for the organisations mentioned nor do we want the logos to be too obtrusive. 

We don’t want to make this change but thank you for the suggestion.
