### ISSUE TITLE
Give Descriptive Error Messages

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#956]
We need to give more descriptive error messages to users, and maybe give out a try again message to let them try again.

Context, a question coming from @ronvoluted:

> When the output gives an error due to backend issues (as opposed to bad input), how often is it that submitting a second time is enough to make it work? If it's very often, changing "ERROR" to "Try again" could prevent some users from bouncing

**Comment by radames** [comment]
I came across this. What's the best way to validate inputs? and/or to avoid running the prediction function without triggering queuing and loading, raising errors that communicate to the UI

```python

def speech_to_text(audio_file_path):
    if(audio_file_path == None):
        raise Exception("No file path provided")


...
        btn.click(speech_to_text, audio, text)
```

**Comment by FarukOzderim** [comment]
Well you could direct it to your outputs. I don't think there currently is a method for raising errors in UI. But thx for sharing we shall consider user made errors within UI as well.

**Comment by abidlabs** [comment]
It would be awesome if people can provide their own custom error messages for events. We could accept an optional (str) "error_message" parameter in an event listener that would be displayed instead of the default error.

**Comment by abidlabs** [comment]
Feedback from @apolinario on this issue: a global replacement for ERROR doesn't always work. You might want to throw different errors depending on what happened (OOM vs. NSFW image generated)

> I would like to specify my own error message if the error is thrown by me - in this case would be "Error: no avaliable GPUs, try again!"

> An advanced version of this would allow people to specificy text messages from different potential errors that can happen "internally" on their models

**Comment by FarukOzderim** [comment]
A bit Related: We have exception types in our Request [class](https://github.com/gradio-app/gradio/blob/main/gradio/utils.py#L418). And can define error types similarly and use them. Also we can set event-exception type while we are sending a Request from Queue to fastapi server and make use of it.

**Comment by FarukOzderim** [comment]
I think this issue should stay open since it is not just User defined errors, but we should also give proper errors for the errors happened in frontend or backend.

**Comment by abidlabs** [comment]
> I think this issue should stay open since it is not just User defined errors, but we should also give proper errors for the errors happened in frontend or backend.

I think we can close this issue actually because the best place for such errors would be the logs (on Spaces) or your Python console (if you're running locally). A typical end user shouldn't see Python errors by default. If a model creator wants to show particular errors to the end user, they can use `gr.Error()` via #2047

**Comment by FarukOzderim** [comment]
OK, though let me remind the original question
```
Context, a question coming from @ronvoluted:

    When the output gives an error due to backend issues (as opposed to bad input), how often is it that submitting a second time is enough to make it work? If it's very often, changing "ERROR" to "Try again" could prevent some users from bouncing

```

**Comment by millermuttu** [comment]
can anyone give an example of how to handle errors and show it in the UI?

**Comment by abidlabs** [comment]
Sure, take a look here for an example: https://github.com/gradio-app/gradio/blob/4a1321ce8a46bd31f34c6c3c70840f4d456bb1a6/demo/calculator/run.py#L12

Quick docs: https://gradio.app/key_features/#errors
