### ISSUE TITLE
Add context or further explanation to any input field

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#959]
**Is your feature request related to a problem? Please describe.**
Sometimes the users may not know what a field or parameter does to the model or to the demo. There can be case that the name or label can't fully capture what it does and further explanation is needed

**Describe the solution you'd like**
A suggestion would be to take inspiration from Streamlit add a 'help' option to all inputs, the help would then show on the front-end as a question mark icon on the top right of the input.
Here's a Streamlit example with the tooltip hovered
<img width="689" alt="image" src="https://user-images.githubusercontent.com/788417/162425204-a2afaae6-8e45-42f3-9e7d-7f3a7369142c.png">

**Comment by pngwn** [comment]
I think a mechanism to provide additional context for certain input would be great. We would need to be careful about how we do that, tooltips are problematic, especially on mobile:
- https://www.nngroup.com/articles/tooltip-guidelines/
- https://adamsilver.io/blog/the-problem-with-tooltips-and-what-to-do-instead/

cc @gary149

**Comment by abidlabs** [comment]
I wonder if we can just use grayed out or slightly smaller text, something like this:

<img width="515" alt="image" src="https://user-images.githubusercontent.com/1778297/163043683-afc688fa-597b-408c-bb98-4cced02f7692.png">

**Comment by pngwn** [comment]
This is preferable, as it is always on the page. A toggle (like  the `details` html element) would work well for descriptions that are too long.

**Comment by gary149** [comment]
> I wonder if we can just use grayed out or slightly smaller text, something like this:

I agree that this is the right way of doing it 👍

**Comment by abidlabs** [comment]
That’s a good suggestion @vzakharov, what do you think about that @pngwn @gary149 to avoid cluttering the UI?

**Comment by pngwn** [comment]
Strongly against tooltips for the reasons stated above: https://github.com/gradio-app/gradio/issues/959#issuecomment-1092765007

They are an accessibility nightmare and almost unusable on mobile which accounts for lots of our usage. We should opt for collapsible text similar to accordions. I'll take a look at this an come up with a proposal soon.

**Comment by abidlabs** [comment]
It would be great if this context field could support Markdown, for reasons suggested by @apolinario in #3143
