### ISSUE TITLE
Add Conditional Inputs

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#961]
**Feature request**
An input that only shows up if another input has a certain value.

**Describe the solution you'd like**
For example, only show further options related to a "mode", if a checkbox that activates that mode is checked.

https://user-images.githubusercontent.com/788417/162430795-b9599c79-2127-4b2d-944e-0ee184bc0592.mov

**Comment by abidlabs** [comment]
Thanks @apolinario! We are working on this using the new `Blocks` class, see #784 for example. 

Will keep this open until we have a good solution out.

**Comment by abidlabs** [comment]
This is now possible! With #1089
