### ISSUE TITLE
When starting more than 5 Gradio pages at the same time, there are problems with the front-end rendering.  

### ISSUE THREAD

**Issue by Weishaoya** [gradio-app/gradio#9618]
### Describe the bug

Use demo.launch() to start the service. When starting more than 5 Gradio pages at the same time, there are problems with the front-end rendering.  

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

![image](https://github.com/user-attachments/assets/7209b603-24ac-46c7-b401-bad7223d107d)
![image](https://github.com/user-attachments/assets/5afe2efb-9bf5-4e59-8682-33ab478dc5e0)

### System Info

```shell
ubuntu22.04
python 3.11.0
gradio==4.44.1
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @Weishaoya - yes this is expected. See https://github.com/gradio-app/gradio/issues/8022
