### ISSUE TITLE
The documentation is hard to read in dark mode

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#9638]
### Describe the bug

The documentation is rendered like this in dark mode.

![](https://github.com/user-attachments/assets/68967118-3752-42b2-a5a6-5b1e75ef5d57)

https://www.gradio.app/docs/gradio/chatinterface

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

-

### System Info

```shell
-
```

### Severity

I can work around it

**Comment by zilto** [comment]
I would raise this as severity "Block usage of Gradio". It makes the library totally unusable in my case. (I was about to file the same issue).

I imagine this will be fixed with other Dark-theme related issue. Linking #9695 for searchability

**Comment by abidlabs** [comment]
@aliabd this should be fixed on `main`, but I don't think the website has rebuilt successfully

**Comment by abidlabs** [comment]
Should be fixed now!
