### ISSUE TITLE
Component info font size not smaller in v5

### ISSUE THREAD

**Issue by tbitai** [gradio-app/gradio#9642]
### Describe the bug

Component info should be displayed in smaller font – see e.g. the [`Textbox` docs](https://www.gradio.app/docs/gradio/textbox#initialization):

> `info: str | None`
> 
> `default = None`
>
> additional component description, appears below the label in smaller font. Supports markdown / HTML syntax.

In v5, that's not the behavior anymore.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

demo = gr.Interface(
    fn=lambda text: text,
    inputs=[gr.Textbox(label="Text", 
                       info="Text to ouput. Should be in smaller font.")],
    outputs=["text"],
)
demo.launch()
```

### Screenshot

![image](https://github.com/user-attachments/assets/f132f5a1-9b03-42f7-a92e-49c43d71bb12)

### System Info

```python
>>> gr.__version__
'5.0.1'
```

### Severity

I can work around it

**Comment by tbitai** [comment]
The workaround I used is to wrap my info strings in a `<small>` element, leveraging the new HTML support.

**Comment by dawoodkhan82** [comment]
Will fix, thanks for reporting.
