### ISSUE TITLE
The web UI page is displaying incorrectly. What is the reason for this？

### ISSUE THREAD

**Issue by dd3389** [gradio-app/gradio#9644]
This is displaying the correct page
![a4c17de8ec2645e1b8a266099f926d4f](https://github.com/user-attachments/assets/b596899b-673a-49cf-98a4-80165b433998)
This is a page that displays abnormalities on some computers
![2](https://github.com/user-attachments/assets/e5fb07d2-5aa3-4011-a0ca-61d048976808)

**Comment by abidlabs** [comment]
Hi @dd3389 please provide more context to help us understand what environments this issue happens on as well as a minimal code repro for the issue above. See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by yvrjsharma** [comment]
Also, can you try the app with `demo.launch(ssr_mode=False)` and let us know how it goes for you?

**Comment by pngwn** [comment]
We need:

- full code reproduction
- system information: browser, browser version, operating system
- python information: python version, gradio version, node version if SSR is being used

**Comment by abidlabs** [comment]
Will go ahead and close this for now. Happy to reopen if we have a repro.
