### ISSUE TITLE
Show history conversations in Chatbot

### ISSUE THREAD

**Issue by Castolus** [gradio-app/gradio#9645]
Hello. I know it may be out of context, but i don´t get an answer on Discord, so I´ll try here. I´m implementing a conversations history for the chatbot, where questions and answers are registerded in JSON as a Tuple. So far i´ve achieved it, but i can´t find the way to show the conversation on the chatbot. Could you give me a hint? here the code:

                chatbot = gr.Chatbot(
                    label=label_text,
                    show_copy_button=True,
                    elem_id="chatbot",
                    render=False,
                    avatar_images=(None, AVATAR_BOT),
                )

                additional_inputs = [mode, upload_button, run_mode, cancel_auto, question_button]
                if settings().ui.show_system_prompt:
                    additional_inputs.insert(2, system_prompt_input)

                _ = gr.ChatInterface(
                    self._chat,
                    chatbot=chatbot,
                    additional_inputs=additional_inputs,
                )
That "question_button" on additional_inputs is the click to any of the questions of the history bar, which is so defined:

       ) as blocks:
        with gr.Row():
            gr.HTML(f"<div class='logo'/><img src={logo_svg} alt=cimGPT></div")

        with gr.Row(equal_height=False):
            with gr.Column(scale=3):
                with gr.Column(elem_classes="history-scroll"):
                    chat_history = self.load_history_from_file()
                    for i, conv in enumerate(chat_history):
                        question_button = gr.components.Button(
                            f"{conv[0]}",
                            visible=True
                        )
                        question_button.click(
                            self.show_conversation,
                            inputs=gr.State(i)
                        )
For now, i have "manual" solution which is not nice. I click on the conversation, then i click on "submit" and it shows the answer on the chatbot. The question is not shown because the Message bar is empty when i click on "submit". I know i´m close, but also a bit desperate since i cannot find a way to achieve it. If you have an idea, i´d be more than thankfull.

KR,
Javier

**Comment by Clay-Ferguson** [comment]
This folder has several examples of a chatbot, which might help:

https://github.com/Clay-Ferguson/quantizr/tree/main/QuantaGradio

It took me two days to create all those, because the Gradio documentation, although being great, just doesn't have enough fully working examples. They have snippets, but not enough full examples like in this folder above. Good luck, hope it helps.

**Comment by Castolus** [comment]
> This folder has several examples of a chatbot, which might help:
> 
> https://github.com/Clay-Ferguson/quantizr/tree/main/QuantaGradio
> 
> It took me two days to create all those, because the Gradio documentation, although being great, just doesn't have enough fully working examples. They have snippets, but not enough full examples like in this folder above. Good luck, hope it helps.

Thanks a lot man. It really helped me understand how can I create my own submit and clear buttons and also disable the default ones from gr.ChatInterface. Many thanks again!

**Comment by Castolus** [comment]
> This folder has several examples of a chatbot, which might help:
> 
> https://github.com/Clay-Ferguson/quantizr/tree/main/QuantaGradio
> 
> It took me two days to create all those, because the Gradio documentation, although being great, just doesn't have enough fully working examples. They have snippets, but not enough full examples like in this folder above. Good luck, hope it helps.

Hey Clay,
just found out that even when i create a new "submit" button and new Textbox to input the message like you did on "Quanta_Gradio_Agent.py", when you write something in the textbox and press enter you submit a question by using the intern integrated "Submit" button and not the new one. Is it correct behaviour or should i disabel it somewhere else?


                    _ = gr.ChatInterface(
                        self._chat,
                        chatbot=chatbot,
                        additional_inputs=additional_inputs,
                        submit_btn=self.submit_button,
                        clear_btn=self.clear_button,
                        retry_btn=None,
                        undo_btn=None,
                        textbox=self.textbox,
                    )

                    with gr.Row():
                        self.submit_button = gr.Button("Submit")
                        self.clear_button = gr.Button("Clear")

**Comment by abidlabs** [comment]
Hi as this is not a feature request or a bug report I’ll go ahead close this issue, as Discord is the beta place to have these discussions

**Comment by Clay-Ferguson** [comment]
Sorry, I didn't notice there was a question on this thread for me until now. Anyway Castolus my Textbox and Submit button were created manually outside the context of anything else, so that's probably why they behave differently without an automatic submit hooked onto the enter key.
