### ISSUE TITLE
`gr.LoginButton` not working with Gradio 5 on HF Spaces

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#9650]
### Describe the bug

`gr.LoginButton` redirects to the same internal URL that the user is at instead of the actual login

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://huggingface.co/spaces/multimodalart/stable-cascade

### System Info

```shell
gradio==5.0.1
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @apolinario for creating the issue. Looking into it, its a weird one
