### ISSUE TITLE
Pagination for `gr.Dataframe`

### ISSUE THREAD

**Issue by micpst** [gradio-app/gradio#9658]
- [x] I have searched to see if a similar issue already exists.
    (It's possible that I didn't search correctly, but I couldn't find a similar request)

Hey, I've been working with the `Dataframe` component lately and I'm missing the option to paginate rows. It'd be awesome to have a `rows_per_page` parameter and render a page selector at the bottom of the component. There's a similar feature available for the `Examples` component under the `examples_per_page` argument.

I can work on this feature, just let me know what you think.

**Comment by pngwn** [comment]
The Dataframe has infinite scrolling and only renders what is in view, so we don't really need this parameter.

What problem would it solve that the current Dataframe does not?

**Comment by alyrazik** [comment]
I second that. pagination is more elegant and user friendly

**Comment by micpst** [comment]
@pngwn Infinite scrolling is fine for small data frames. If you have a few rows that make the whole component too big, you can hide them and let the user scroll. For larger frames (>1000 rows) this is cumbersome and we render too many elements. Also, navigating the data frame would be easier with pagination.

**Comment by pngwn** [comment]
For large dataframes we only render what is in view and the data frame has a maximum height of the page height so we shouldnt be rendering rendering much at all.

**Comment by abidlabs** [comment]
Closing. As @pngwn pointed out, the Dataframe component uses virtual scrolling, only rendering the values that are in the view, which means that it should scale to arbitrarily large datasets. If you still want pagination, you could create something to that effect using a standalone `gr.Slider` or `gr.Number` and display only that part of the dataframe that you want.
