### ISSUE TITLE
Allow setting title in gr.Info/Warning/Error

### ISSUE THREAD

**Issue by fakerybakery** [gradio-app/gradio#9670]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Hi,
Currently, I'm unable to manually set the title for gr.Info/Warning/Error alerts.

**Describe the solution you'd like**  
Would it be possible to allow users to manually set the title (i.e. through `gr.Info("Message", title="Title")`?

**Additional context**  
N/A

**Comment by adi776borate** [comment]
Hi!
I'm planning to work on this for Hacktoberfest 2024 and hope to have it fixed.
