### ISSUE TITLE
Gradio 5.0.1 - Streaming Chatbot removes new lines (and maybe more)

### ISSUE THREAD

**Issue by skye0402** [gradio-app/gradio#9679]
### Describe the bug

When using Gradio.Chatbot with "messages" I found the streaming has a flaw in it. It removes the "\n" from a stream which makes it formatting the message incorrect. Can you look into it?

You can use your own examples that you published for chatbot_simple and chatbot_streaming: https://www.gradio.app/docs/gradio/chatbot

You just have to add a `\n` into the sample response text. Simple works, Streaming doesn't. Please check if that is the only escaped character that has issues. I tried `\\` and `\r` which seem to work.

**Working:**
![image](https://github.com/user-attachments/assets/7e1dfe52-cf82-4616-bfbc-7d9da261a291)

**Not working:**
![image](https://github.com/user-attachments/assets/02120f2f-6e5f-480b-95c1-1780c358980d)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot(type="messages")
    msg = gr.Textbox()
    clear = gr.Button("Clear")

    def user(user_message, history: list):
        return "", history + [{"role": "user", "content": user_message}]

    def bot(history: list):
        bot_message = random.choice(["How are\n\n you?", "I\n\n love\n\n you", "I'm\n\n very\n\n hungry"])
        history.append({"role": "assistant", "content": ""})
        for character in bot_message:
            history[-1]['content'] += character
            time.sleep(0.05)
            yield history

    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        bot, chatbot, chatbot
    )
    clear.click(lambda: None, None, chatbot, queue=False)

if __name__ == "__main__":
    demo.launch()

```

### Screenshot

See message above.

### Logs

```shell
No errors.
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 5.0.1
gradio_client version: 1.4.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.4.0
fastapi: 0.112.2
ffmpy: 0.4.0
gradio-client==1.4.0 is not installed.
httpx: 0.27.2
huggingface-hub: 0.25.2
jinja2: 3.1.4
markupsafe: 2.1.5
numpy: 1.26.4
orjson: 3.10.7
packaging: 23.2
pandas: 2.2.2
pillow: 10.4.0
pydantic: 2.8.2
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.2
ruff: 0.6.3
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.5
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.30.6
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.6.1
httpx: 0.27.2
huggingface-hub: 0.25.2
packaging: 23.2
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
The issue is the call to `inspect.cleandoc` in post process. It removes all trailing white space. I think we can remove @dawoodkhan82 ?

**Comment by dawoodkhan82** [comment]
@freddyaboulton I think we can remove. I'll check and make sure there's no regressions especially with markdown messages.

**Comment by dawoodkhan82** [comment]
@freddyaboulton I'm not sure if `inspect.cleandoc` was the issue. Seems to be specific to streaming. Looking into it.

**Comment by dawoodkhan82** [comment]
@freddyaboulton Double checked and it would lead to breaking markdown messages. `inspect.cleandoc` maintains proper indentation, handles line endings and spacing that's necessary for the markdown messages. We can change the functionality to _only_ use `inspect.cleandoc` when `render_markdown` is true. thoughts @freddyaboulton?

**Comment by dawoodkhan82** [comment]
Actually the better solution here is to probably implement a custom `inspect.cleandoc` function that preserves empty new lines, but handles all other cases the same.

**Comment by skye0402** [comment]
Not an expert for your code but I removed the `inspect.cleandoc` and all worked as it should in the streaming. Actually I discovered it because markdown from the LLM was broken (e.g. a ** without a newline next to the word wasn't rendered). So my main problem was broken markdown in streaming before.

**Comment by dawoodkhan82** [comment]
It will break in this case for example:
But only for streaming, since the `\n` characters are treated as leading white space since the characters are streamed through postprocess.

```
markdown_text = """
    # Heading

    - List item 1
    - List item 2
        - Nested item
            ```python
            def example():
                pass
            ```

    > Blockquote
        > Nested blockquote
"""
```

**Comment by dawoodkhan82** [comment]
@skye0402 Will push a fix soon.
