### ISSUE TITLE
Chat interface cannot correctly show markdown image from local disk after upgrading to 5.0

### ISSUE THREAD

**Issue by FitzWang** [gradio-app/gradio#9680]
### Describe the bug

before the version of 5.0, I can correctly inject markdown string to the chat interface to show the image correctly.
The string lookslike: ![](file=images/xxx.png)
The .launch() cmd includes the image storage path and look like: demo.launch(allowed_paths=["/xx/xx/xx/"])
However, after upgrading to version 5.0.2, the image cannot been shown and only white space.
The markdown image display comparison between 4.44 and 5.0.2:
<img width="1538" alt="Screenshot 2024-10-12 at 12 59 02" src="https://github.com/user-attachments/assets/dcaafc51-9d06-4ace-9f64-5bc53649f103">
<img width="1531" alt="Screenshot 2024-10-12 at 13 06 26" src="https://github.com/user-attachments/assets/eea0ea74-1762-4f00-aa8e-267d629e9f32">
However, for very rare situation in version 5.0.2, it will correctly display certain image.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import time
import gradio as gr

def slow_echo(message, history):
    for i in range(len(message)):
        # time.sleep(0.05)
        yield "You typed: " + message[: i + 1]

demo = gr.ChatInterface(slow_echo, type="messages")

if __name__ == "__main__":
    demo.launch(allowed_paths=["/xxx/xx0", "/xxx/xx1"])

```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 5.0.2
gradio_client version: 1.4.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.4.0
fastapi: 0.111.0
ffmpy: 0.3.2
gradio-client==1.4.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.25.2
jinja2: 3.1.4
markupsafe: 2.1.5
numpy: 1.26.4
orjson: 3.10.5
packaging: 24.1
pandas: 2.2.2
pillow: 10.3.0
pydantic: 2.7.4
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.4.10
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.30.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.6.0
httpx: 0.27.0
huggingface-hub: 0.25.2
packaging: 24.1
typing-extensions: 4.12.2
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by amirabdullah19852020** [comment]
Yes, I can confirm seeing similar behavior when upgrading to 5.0.2.

**Comment by hzxie** [comment]
The same for 5.0.x and 5.1.0 (the latest version).

**Comment by freddyaboulton** [comment]
Hi all! You need to use put a `!` before the markdown (`![](...)`) and the url now begins with `/gradio_api/`.

**Comment by freddyaboulton** [comment]
Just verified that works for me so will close

**Comment by FitzWang** [comment]
> Hi all! You need to use put a `!` before the markdown (`![](...)`) and the url now begins with `/gradio_api/`.

Hi, I'm still not very clear.
1. I'v already put a '!' before the markdown string. see the image in the issue description.
<img width="414" alt="image" src="https://github.com/user-attachments/assets/b3be6d31-2033-482a-b7c3-066a35eeecad">

2. "the url begins with '/gradio_api/'" means the markdown url should be ![](file=/gradio_api/my/path/to/the/image) ?

**Comment by freddyaboulton** [comment]
Should be `![](gradio_api/file=/my/path/to/the/image/)`
