### ISSUE TITLE
Gradio chat UI: Have 2 levels of examples 

### ISSUE THREAD

**Issue by david-thrower** [gradio-app/gradio#9689]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  Yes

In legacy versions of the Gradio chat UI, example buttons were displayed below the chat prompt field. These buttons were persistent and could be clicked multiple times during a conversation. However, in the current version of the chat UI, example buttons are displayed above the chat prompt field and are not practical to use you have started the conversation.

While the current implementation is suitable for some use cases, it is not ideal for others. For example, in our use case, we have a robot that guides users through a complex process by asking a series of 20 or so mostly closed-ended questions. The persistent example buttons in the legacy chat UI were helpful for quickly selecting the appropriate response without writing "No" | "Yes" repeatedly, and facilitating consistency in how answers were worded so we can eliminate that variable from the list of insults to accuracy.

**Describe the solution you'd like**  

To address this issue, I propose keeping the "examples" as it is in the newer version and adding a new parameter to the `gr.ChatInterface` constructor, called `answers`. This parameter would allow users to specify a list of template responses that can be used [repeatedly] at any point during the conversation. These template responses would be displayed as persistent buttons below the chat prompt field, similar to the example buttons in the legacy versions of the chat UI.

Here is an example of how the `answers` parameter could be used:
```
gr.ChatInterface(
    ...
    answers=["No", "Yes mild issue", "Yes serious issue",  "I'm nor sure"]
)
```

This would display four persistent buttons below the chat prompt field, labeled"No", "Yes mild issue", "Yes serious issue",  and  "I'm nor sure" Users could click these buttons at any point during the conversation to quickly insert the corresponding template response into the chat prompt field.

**Comment by abidlabs** [comment]
Hi @david-thrower thanks for creating this issue. That's an interesting use of examples for sure, but one that was "unintentionally supported in 4.x". We've intentionally redesigned examples to follow this format, and instead will try to support the use case you are describing via https://github.com/gradio-app/gradio/issues/4763
