### ISSUE TITLE
can't update value of CheckboxGroup

### ISSUE THREAD

**Issue by bluelovers** [gradio-app/gradio#9690]
### Describe the bug

i see the https://github.com/gradio-app/gradio/pull/5254

but... i still can't update value of CheckboxGroup

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr 

choices = ["First Choice", "Second Choice", "Third Choice"]
with gr.Blocks() as demo:
    chx = gr.CheckboxGroup(choices=choices, interactive=True)
    btn = gr.Button(value="Select All")
    btn.click(lambda: chx.update(value=["Third Choice"]))

demo.launch()

if __name__ == "__main__":
    demo.launch()
```

### Screenshot

![image](https://github.com/user-attachments/assets/78eaa5a2-837e-4243-8b52-0a4411b305e0)

### System Info

```shell
https://www.gradio.app/playground
```

### Severity

Blocking usage of gradio

**Comment by lazarusking** [comment]
```py
btn.click(lambda: gr.update(value=["Third Choice"]),[],[chx])
```
or 
```py
btn.click(lambda: gr.CheckboxGroup(value=["Third Choice"]),[],[chx])
```
That should do it
