### ISSUE TITLE
Incompatibility with Python 3.13.0 while using gradio library

### ISSUE THREAD

**Issue by samy-FERGUI** [gradio-app/gradio#9696]
- [x] I have searched to see if a similar issue already exists.

---

**Is your feature request related to a problem? Please describe.**  

Yes, the problem is related to **Gradio's** compatibility with Python 3.13.0. While the documentation mentions that Gradio supports Python versions **>= 3.10**, it seems that Python 3.13.0, the most recent python release, is not fully compatible due to issues with some dependencies, such as **pydub** and **audioop**. Specifically, **audioop** is not found in Python 3.13.0, which causes a `ModuleNotFoundError` when running Gradio.

Steps to reproduce:
1. Install Python 3.13.0.
2. Create a virtual environment and install Gradio.
3. Run a basic Gradio app (the exemple given in readme.
4. Observe the error:
   ```bash
   ModuleNotFoundError: No module named 'audioop'

**Describe the solution you'd like**  

For the moment, i would like to update the readme to clearly state this issue.

**Comment by aliabid94** [comment]
Thanks @samy-FERGUI !
