### ISSUE TITLE
How to use SSR with .mount method app

### ISSUE THREAD

**Issue by marcoquin** [gradio-app/gradio#9706]
- [x] I have searched to see if a similar issue already exists.

First, thank you so much for the work on gradio and the gradio 5 release. I have an app that use gradio mount method, I wanted to know how to use SSR with it. A doc is actually explaining how to do SSR with .launch method. But nothing on .mount, Has someone any infos please? Or any docs about it? 

Thanks for the help.

**Comment by abidlabs** [comment]
Hi @marcoquin, for general questions like this (that are not feature requests or bug reports), please ask in [our Discord server](http://discord.gg/feTf9x3ZSB). (I'll close this issue)

**Comment by freddyaboulton** [comment]
Use `GRADIO_SSR_MODE=True uvicorn <module-name>:<app-name>`
