### ISSUE TITLE
`gr.FileExplorer` raises InvalidPathError() gradio.exceptions.InvalidPathError on Windows

### ISSUE THREAD

**Issue by russosalv** [gradio-app/gradio#9715]
### Describe the bug

Using Gradio File in Windows, if you try to go down in folder (more then 1 step) receive 
    raise InvalidPathError()
gradio.exceptions.InvalidPathError

filesystem is:
Folder1 -> Folder2 -> Folder3 -> File

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

        with gr.Blocks() as suggester_ui:
            with gr.Row(): 
                file_explorer = gr.FileExplorer(
                        interactive=True,
                        glob="*",
                    )


```

### System Info

```shell
gradio 5.1.0
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @russosalv - this is expected with gradio 5. We won't serve files located outside your current working directory unless you specify them in `allowed_paths`

**Comment by russosalv** [comment]
Hi @freddyaboulton thx for reply
how to declare that it's allowed to go down in the directory?

**Comment by freddyaboulton** [comment]
Can you try something like

```python
with gr.Blocks() as demo:
    ...
demo.launch(allowed_paths=["Folder1/"])
```

**Comment by russosalv** [comment]
@freddyaboulton 
alo adding 
```python
current_path = os.path.dirname(os.path.abspath(__file__))
...
ui.launch(allowed_paths=[current_path])
```

still ahve same error
![image](https://github.com/user-attachments/assets/8d3b722e-0aa1-4a27-8527-e8ae76ac5dd1)

**Comment by freddyaboulton** [comment]
I can't repro this actually @russosalv . I just tried with the `file_explorer` demo in the repo
```python
import gradio as gr
from pathlib import Path

current_file_path = Path(__file__).resolve()
absolute_path = (current_file_path.parent / ".." / ".." / "gradio").resolve()

with gr.Blocks() as demo:
    gr.Markdown('### `FileExplorer` to `FileExplorer` -- `file_count="multiple"`')
    submit_btn = gr.Button("Select")
    with gr.Row():
        file = gr.FileExplorer(
            glob="**/components/*.py",
            # value=["themes/utils"],
            root_dir=absolute_path,
            ignore_glob="**/__init__.py",
        )

        file2 = gr.File()
    submit_btn.click(lambda x: x, file, file2)

if __name__ == "__main__":
    demo.launch(allowed_paths=[str(absolute_path)])
```

If the `playgrounds` directory is in `allowed_paths` then you should be able to process those files.

**Comment by russosalv** [comment]
@freddyaboulton 
try to execute this code and inspect Folder 2

```python
import gradio as gr
from pathlib import Path

current_file_path = Path(__file__).resolve()
absolute_path = (current_file_path.parent).resolve()

# create a Folder called Folder1 in the same directory as this file
new_folder = absolute_path / "Folder1"
new_folder.mkdir(exist_ok=True)

# insert a fake txt file into the new folder
fake_txt = new_folder / "fake.txt"
fake_txt.write_text("Hello World")

# create a Folder called Folder2 in the directory new_folder
new_folder2 = new_folder / "Folder2"
new_folder2.mkdir(exist_ok=True)

# insert a fake txt file into the new folder
fake_txt2 = new_folder2 / "fake2.txt"
fake_txt2.write_text("Hello World 2")

with gr.Blocks() as demo:
    gr.Markdown('### `FileExplorer` to `FileExplorer` -- `file_count="multiple"`')
    submit_btn = gr.Button("Select")
    with gr.Row():
        file = gr.FileExplorer(
            glob="**/components/*.py",
            # value=["themes/utils"],
            root_dir=absolute_path,
            ignore_glob="**/__init__.py",
        )

        file2 = gr.File()
    submit_btn.click(lambda x: x, file, file2)

if __name__ == "__main__":
    demo.launch(allowed_paths=[str(absolute_path)])
```

![image](https://github.com/user-attachments/assets/3d2c889c-0299-4bef-956a-4e33f0a5b873)

**Comment by freddyaboulton** [comment]
https://github.com/user-attachments/assets/0030c170-a7f0-4e83-84af-c34ab2003133

I do not get the error @russosalv !

**Comment by russosalv** [comment]
ok but of if i need other folder inside folder2 i need to explicit indicate
it? can be annoying.
there is a method to allow all root?


*Salvatore Alessandro Russo*
***@***.***



Il giorno ven 18 ott 2024 alle 20:47 Freddy Boulton <
***@***.***> ha scritto:

**Comment by freddyaboulton** [comment]
You don't need to explicitly add folder 2's children to allowed paths. Since Folder1, Folder2 etc are children of `absolute_path`, they will all be allowed. Since all folders are in your current working directory, you also don't need to explicitly add them. Only folders outside of your current working directory.

**Comment by russosalv** [comment]
Anyway i tried on mac and works but on windows still have the problem

**Comment by abidlabs** [comment]
ok reopening in light of the Windows-specific issue

**Comment by russosalv** [comment]
any update about it?

**Comment by PatZer0** [comment]
same issue...
