### ISSUE TITLE
Can't have a listener for Chatbot clear button.

### ISSUE THREAD

**Issue by Steveolas** [gradio-app/gradio#9722]
### Describe the bug

In older gradio versions. the gr.ChatInterface had a default .clear_btn component. When I wanted to tun a function whenever the user used the clear button I cout use the chatinterface.clear_btr.click() event listener.
In new version of gradio 5.1.0 the clear, undo and retry button no longer exist as buttons but are now built into the chatbot. I see there are .undo() and .retry() event listener on the chatbot, but no event listener for clearing the chatbot.. A .clear() event listener on gr.Chatbot would solve my problem but from my understanding it does not exist.

Is there a way to achieve running a custom function every time a user uses the clear button on a chatbot?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def messaging_fn(message, history):
    pass

def reset_conversation_id():
    pass


with gr.Blocks(title="", css=css, theme=gr.themes.Default(text_size='sm',)) as main_app:

    conversation_id = gr.Textbox(interactive=False, value=uuid.uuid4, visible=False)
    
    ci = gr.ChatInterface(
            messaging_fn,
            additional_inputs=[dropdown, conversation_id],
            concurrency_limit=5,
            multimodal=True
    )
    # ci.clear_btn.click(reset_conversation_id, outputs=[conversation_id]) # Used to work in gradio 4.44.1, has no possible implementation now

```

### System Info

```shell
Gradio 5.1.0
Worked previously on gradio 4.44.1
```

### Severity

Blocking usage of gradio

**Comment by spmkone** [comment]
Stumbled upon this issue, as I was looking for the same thing. The chatbot component comes with a nice clear button (trashcan icon) - but I don't know how to listen to it. It doesn't seem to be listed among the [event listeners](https://www.gradio.app/docs/gradio/chatbot#event-listeners) in the 5.1.0 docs.

**Comment by freddyaboulton** [comment]
As a workaround you can listen for a change event and then if the history is empty the clear button was clicked. But seems reasonable to add a `clear` event on the chatbot. Contributions welcome.

**Comment by dimeneman** [comment]
I want to contribute to this issue.

**Comment by brycepg** [comment]
For anyone here from google, here's how to clear state:

This example shows the clearing of session state, a uuid which could be used to track conversation.

```python
from uuid import uuid4
import gradio as gr


def clear():
    print("Cleared uuid")
    return uuid4()


def chat_fn(user_input, history, uuid):
    return f"{user_input} with uuid {uuid}"


with gr.Blocks() as demo:
    uuid_state = gr.State(
        uuid4
    )
    c = gr.Chatbot(type="messages")
    c.clear(clear, outputs=[uuid_state])

    gr.ChatInterface(
        chat_fn,
        additional_inputs=[uuid_state],
        chatbot=c,
        type="messages"
    )

demo.launch()
```
