### ISSUE TITLE
Web PLayground shows error log instead of Gradio preview

### ISSUE THREAD

**Issue by MrDasix** [gradio-app/gradio#9727]
### Describe the bug

If i go to the website: [Gradio Playground](https://www.gradio.app/playground) as a preview it shows an error log

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

If i go to the website: [Gradio Playground](https://www.gradio.app/playground) as a preview it shows an error log

![image](https://github.com/user-attachments/assets/78eacc37-6846-48d0-ae12-ba5da955ddc6)

### System Info

```shell
Google Chrome
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
We're looking into it!

**Comment by abidlabs** [comment]
Should be fixed now, please do a hard refresh (ctrl/cmd+r) if you are still seeing this.

**Comment by MrDasix** [comment]
Now even the editor isn't loading :(

![image](https://github.com/user-attachments/assets/905392c5-38d0-45cd-ba94-7edb0913a53c)

**Comment by abidlabs** [comment]
Sorry, we're in the process of fixing this!
