### ISSUE TITLE
VirtualScroll of DataFrame seems broken

### ISSUE THREAD

**Issue by nolan-prescott** [gradio-app/gradio#9729]
### Describe the bug

Once the DataFrame is populated with a large amount of data, it expands in size when scrolling, rather than utilizing virtual scrolling. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import pandas as pd
import numpy as np

num_entries = 1000
data = {
    "Column1": np.random.randint(1, 100, num_entries),
    "Column2": np.random.choice(['A', 'B', 'C', 'D'], num_entries),
    "Column3": np.random.randn(num_entries),
    "Column4": np.random.choice(pd.date_range("2020-01-01", periods=100), num_entries),
    "Column5": np.random.random(num_entries),
    "Column6": np.random.choice([True, False], num_entries)
}


def display_dataframe():
    return pd.DataFrame(data)


iface = gr.Interface(
    fn=display_dataframe,
    inputs=[],
    outputs="dataframe",
    title="Sample DataFrame",
    description="This is a sample DataFrame with 1000 entries and 6 columns."
)

iface.launch()

```

### Screenshot

[demo.webm](https://github.com/user-attachments/assets/a741971b-9be1-4e24-84f0-c1f4347e2a6e)

### System Info

```shell
- Tested in Chrome and FireFox
- Gradio Version: 4.44.0
- Ubuntu 24
```

### Severity

Blocking usage of gradio

**Comment by pngwn** [comment]
Broken is a strong word. 

I prefer working counter to my expectations.

**Comment by pngwn** [comment]
That said we are aware of this and are tracking the issue in https://github.com/gradio-app/gradio/issues/9288

I'll close this as a duplicate. Thank you for the report!
