### ISSUE TITLE
Do not show Gradio 5 upgrade user warning by default

### ISSUE THREAD

**Issue by lllyasviel** [gradio-app/gradio#9736]
All previous Gradio applications are now showing `UserWarning: IMPORTANT: You are using gradio version 4.x, however version 5.0.1 is available, please upgrade. ` and then they are all broken after users really following this "IMPORTANT" warning.

We can understand this for Gradio 4 after 6 or 7 months of maturing, but this for Gradio 5 at this moment is still a bit too aggressive. 

In my memory, most users use newer Gradio mainly when building new spaces. For old code bases, user demands are mostly keeping things functional. In this regard, having this warning does not bring much benefit to the former, but trouble the later a lot. So maybe this needs a bit more consideration.

**Comment by pngwn** [comment]
Yeah I think this makes sense. We should make this warning if the user is on the same major version only.

**Comment by pngwn** [comment]
Although now that I think about it, we don't actually have a way of changing this now. We don't backport changes and this message lives in their installed gradio version as far as I'm aware.

**Comment by lllyasviel** [comment]
> Although now that I think about it, we don't actually have a way of changing this now. We don't backport changes and this message lives in their installed gradio version as far as I'm aware.

😹 I cannot imagine what React or Vue users will be like if they send a same warning to billions of devices

**Comment by abidlabs** [comment]
We can disable it for now, although I highly recommend [upgrading to Gradio 5 for security reasons](https://huggingface.co/blog/gradio-5-security)!

**Comment by lllyasviel** [comment]
@abidlabs wait what is `Several components’ post-process functions could allow attackers to leak arbitrary files in very simple Gradio server configurations.` what gradio 4 components will have this and how to trigger it?

**Comment by abidlabs** [comment]
Hi @lllyasviel, this happens if you allow users to provide arbitrary string inputs (e.g. via a `gr.Textbox` or `gr.Dropdown`) and then pass that input directly or without sanitization into a component that returns files, like `gr.File` or even `gr.Image`. 

Here's an example susceptible Gradio app:

```py
import gradio as gr

with gr.Blocks() as demo:
  def select_file(filename):
    return filename
  drop = gr.Dropdown(
    choices=["1.png", "2.png", "3.png"],
    value="1.png",
    interactive=True,
    label="Select a file"
  )
  download_button = gr.DownloadButton(
    label="Download Scene", scale=3,
    value="1.png",
  )
  drop.change(
  fn=select_file,
  inputs=[drop],
  outputs=[download_button],
  )

demo.launch()
```

We include more details in the [full security report](https://github.com/trailofbits/publications/blob/master/reviews/2024-10-huggingface-gradio-securityreview.pdf).

**Comment by abidlabs** [comment]
Fixed now, you'll only get a message to upgrade to 4.41.1 (if you are using an older version than 4.41.1). 

[Internal PR for reference](https://github.com/gradio-app/gradio-api-server/pull/16/files)
