### ISSUE TITLE
SSR not working with safari

### ISSUE THREAD

**Issue by ngaudemet** [gradio-app/gradio#9748]
### Describe the bug

safari :
<img width="1393" alt="image" src="https://github.com/user-attachments/assets/fde92d72-b727-4841-909a-d2694885f9de">

chrome : 
<img width="1300" alt="image" src="https://github.com/user-attachments/assets/05478ab2-7761-4971-ad38-93485bb6c4f1">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
    gr.Textbox(value="Input Text", label="Enter your text here")

demo.launch()
```

### System Info

gradio==5.1

### Severity

I can work around it

**Comment by dawoodkhan82** [comment]
Cannot reproduce the bug. Atleast the demo provided seems to work fine for me on safari (with JS disabled).

<img width="1506" alt="Screenshot 2024-10-28 at 11 09 03 PM" src="https://github.com/user-attachments/assets/db24e644-12af-40bd-8def-594dc2ac9cd0">

**Comment by ngaudemet** [comment]
Hey thanks for checking. I confirm it doesn't work at all on Safari (with ou without JS activate) on my side. Icons are weird and huge with SSR.

my safari version is : Version 18.0 (19619.1.26.111.10, 19619)
my gradio version is 5.4

Also, I can't launch SSR with custom components on Chrome or Edge. It works on Chrome and Edge but without custom components. (and it all works well without SSR). I will write a specific issue on this one unless you have a quick fix.

Thanks a lot for your help!

**Comment by dawoodkhan82** [comment]
Spent a lot of time trying to dig into this issue with no solution yet. Seems like it might be a cors issue specifically affecting safari. Maybe @abidlabs or @freddyaboulton who know more about cors can take a look.

Reproduction: Run a demo in ssr mode using the built version of the frontend (port 7860)

**Comment by abidlabs** [comment]
Will try to take a look as I assume this breaks Spaces on Safari completely. What errors do you see in the terminal @dawoodkhan82?
