### ISSUE TITLE
upload button / files bugs with multiple file_types

### ISSUE THREAD

**Issue by ngaudemet** [gradio-app/gradio#9749]
### Describe the bug

bugs when I try to load a allowed type when multiple types are allowed, and you don't upload the first type allowed (here when you upload docx, which is the second type)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
    button = gr.UploadButton(
        "Upload", file_types=[".pdf", ".docx"], file_count="multiple"
    )
    files = gr.File(file_count="multiple", file_types=[".pdf", ".docx"])
    button.upload(fn=lambda x: x, inputs=button, outputs=files)

demo.launch()

```

### Screenshot

<img width="1355" alt="image" src="https://github.com/user-attachments/assets/d8a79ad8-4544-48e5-baba-a1d89ce0036c">

### Logs

```shell
python3.11/site-packages/gradio/components/upload_button.py", line 153, in _process_single_file
    raise Error(
gradio.exceptions.Error: "Invalid file type. Please upload a file that is one of these formats: ['.pdf', '.docx']"
```

### System Info

```shell
gradio==5.1
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
This was fixed in https://github.com/gradio-app/gradio/pull/9678 - will be out in the next release.
