### ISSUE TITLE
stroke and mouse cursor do not match

### ISSUE THREAD

**Issue by thuc248997** [gradio-app/gradio#9753]
### Describe the bug

In the version 4.29.0, I use func image editor perfect; there is not good when I update new version. I see in the changelog a noted fix to cut off images in the version 5.0.0-beta2, but I see a new issue that stroke and mouse cursor do not match.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### Screenshot

![image](https://github.com/user-attachments/assets/f6e836ed-f075-4a05-8d47-9b46397f51cd)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 5.0.0b4
gradio_client version: 1.4.0b2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.6.0
fastapi: 0.115.0
ffmpy: 0.4.0
gradio-client==1.4.0-beta.2 is not installed.
httpx: 0.27.2
huggingface-hub: 0.25.2
jinja2: 3.1.4
markupsafe: 2.1.5
numpy: 1.26.4
orjson: 3.10.7
packaging: 24.1
pandas: 2.2.3
pillow: 10.3.0
pydantic: 2.9.2
pydub: 0.25.1
python-multipart: 0.0.12
pyyaml: 6.0.1
ruff: 0.6.9
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.5
typing-extensions: 4.12.2
urllib3: 2.2.3
uvicorn: 0.31.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.9.0
httpx: 0.27.2
huggingface-hub: 0.25.2
packaging: 24.1
typing-extensions: 4.12.2
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @thuc248997 I believe this is fixed in `gradio==5.1.0`, can you confirm?

**Comment by thuc248997** [comment]
@abidlabs Nice! Thanks, it worked for me

**Comment by abidlabs** [comment]
Yes, that is a separate issue that we are looking into! https://github.com/gradio-app/gradio/issues/9810
