### ISSUE TITLE
Authentication Error in GRADIO 5

### ISSUE THREAD

**Issue by sajjadmosaheb** [gradio-app/gradio#9772]
### Describe the bug

The Authentication is not pass and return incorrect credential while it is working in gradio 4!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
gradio 5
python 3.12.7
```

### Severity

I can work around it

**Comment by pngwn** [comment]
Please provide a minimal reproduction.

**Comment by abidlabs** [comment]
Will go ahead and close this for now. Happy to reopen if we have a repro.

**Comment by sajjadmosaheb** [comment]
Hi @abidlabs ,
I found the answer, and gradio 5 is okay. The problem occurs because the ldap3 library missed the pycryptodome function, and I have to install it in the new environment!
I forgot to close this issue.

I have another question, is it possible to display a warning with a desired message when a user enters the wrong password several times?
Does this matter not exist in the authentication page?

**Comment by abidlabs** [comment]
Hi @sajjadmosaheb that is out of scope of the built-in login page
