### ISSUE TITLE
Styling on mobile Edge

### ISSUE THREAD

**Issue by BramVanroy** [gradio-app/gradio#9784]
### Describe the bug

On Edge the styling of API documentation is not rendered as expected. It may have to do with the fact that on my phone dark mode is enable on a system level and that Edge is trying to use that in some way to set some elements to Dark mode. Just a guess. Screenshot attached shows the issue.

Mobile Firefox and Chrome do not show the issue for me.

(Running Android on Pixel 8 Pro.) 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://www.gradio.app/main/docs/gradio/image

### Screenshot

![Screenshot_20241022-085250](https://github.com/user-attachments/assets/5f35e84f-75c3-48b5-b590-3691e81c2373)

### System Info

```shell
NA
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @BramVanroy we just pushed a fix for dark mode -- can you check if this is still an issue for you?
