### ISSUE TITLE
Buttons of type 'huggingface' appear Black

### ISSUE THREAD

**Issue by Steveolas** [gradio-app/gradio#9787]
### Describe the bug

When not in darkmode, 'huggingface buttons appear black with white text. When in darkmode they appear white. This is in contrary to the documentation. And in contrary to how they worked in gradio 5.1.0.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import numpy as np
import gradio as gr

with gr.Blocks() as demo:
    text_button = gr.Button("I Am a Button", variant='huggingface')


if __name__ == "__main__":
    demo.launch()
```

### Screenshot

![image](https://github.com/user-attachments/assets/f714fe62-ce7d-4a5c-a608-bc7ebf918dc3)

### System Info

```shell
gradio 5.3.0
```

### Severity

I can work around it

**Comment by fadingNA** [comment]
Can I fix the docstring and make a PR ? 
@abidlabs

**Comment by abidlabs** [comment]
That'd be great @fadingNA!

**Comment by fadingNA** [comment]
Thank you so much I will assign on this task

**Comment by fadingNA** [comment]
@abidlabs  just to confirm the button component change docstring on component/button.py is that correct? @abidlabs

**Comment by abidlabs** [comment]
Yes that's correct and I believe that's the only place this parameter is referenced

**Comment by fadingNA** [comment]
@abidlabs  https://github.com/gradio-app/gradio/pull/9806

I have make a PR for you to review
