### ISSUE TITLE
Select a directory in `gr.FileExplorer` in gradio@5.1.0

### ISSUE THREAD

**Issue by xorangezq** [gradio-app/gradio#9812]
### Describe the bug

I've noticed #9354 and #6689, selecting a directory in `gr.FileExplorer` should be ok at gradio@4.9.0 (#6670)

I'm using gradio 5.1.0 and when I tried examples from #6689, things does not work as expected.

- Am I using it wrong ? since #9354, I would like to know the correct way of using it
- If not, are anything broken and pending for fix ?

Thanks.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Reproduction code is from #6689, near the most end of discussion.

```python
import gradio as gr

demo = gr.Interface(lambda x:x, gr.FileExplorer(file_count="single", root_dir="..", glob="**/*"), "textbox")

demo.launch(
    allowed_paths=[
        '..',
    ],
    ssl_verify=False,
    server_name='0.0.0.0',
)
```

PS: The original code contains `gr.FileExplorer(..., root=)`, which is broken at gradio@5.1.0.

### Screenshot

![IMG_8050](https://github.com/user-attachments/assets/e11eb90b-f8ad-4c8b-8eac-20423dba37ca)

### System Info

```shell
(ai) root@appmediatool:~/workspace/app/mediatool# pip list | grep gradio
gradio                  5.1.0
gradio_client           1.4.0

Python 3.10.14
```
```


### Severity

Blocking usage of gradio

**Comment by aliabid94** [comment]
FileExplorer allows for the selection of files. If you would like to select a directory, set `file_count="multiple"` and you can then select a directory. This will return a list of all files in the directory as well. This would also allow the selection of multiple directories. I believe this has been the expected behaviour since this component was implemented. Is your request that we support a way of only allowing selection of directories, not the files inside?

**Comment by xorangezq** [comment]
Thanks for replying.


> Is your request that we support a way of only allowing selection of directories, not the files inside?

Yes. 

I think I'm able to make things work for me with your suggestion of setting `file_count="multiple"`. 

Selecting all files under a directory means a similar thing but it's not always suitable, for example "select a directory no matter how many files are in it, and there're actually thousands of files", selecting a directory is more intuitive and efficient.

---

As in #6689, [abidlabs](https://github.com/abidlabs) commented at 23Dec8 that

> Hmm that behavior doesn't make sense to me -- so single doesn't allow you to select directories, but multiple does?

and PR author supported it that

> i think this is finally working as intended. If file_count=single, clicking on a directory won't automatically select all its children.

**Comment by aliabid94** [comment]
I see. I'll add support for selecting single directories then!
