### ISSUE TITLE
when "share=True", the modified and built gradio source code does not work as modified 

### ISSUE THREAD

**Issue by yangquanbiubiu** [gradio-app/gradio#9841]
### Describe the bug

I hope that the image generation does not show the time, but to show the "processing" , gradio provides parameter modification but can not directly achieve this effect, so I downloaded the gradio source code, modified the part about progress status displayin the front-end code(~/miniconda3/envs/comfyui/lib/python3.11/site-packages/gradio/_frontend_code/statustracker/static/index.svelte). I modified the source code and compiled and installed gradio, then ran my script and the result was，when "share=True", the modified and built gradio source code does not work as modified，but without "share=True", the modified and built gradio source code work as modified
![微信截图_20241025113111](https://github.com/user-attachments/assets/74536be8-b384-4c0d-9bed-bfe2e0228e14)
![微信截图_20241025112149](https://github.com/user-attachments/assets/61459a94-28cc-4fb6-88aa-fcfb2662f30a)

![微信截图_20241025112449](https://github.com/user-attachments/assets/e6c4065b-8fee-48dc-af45-0fbecee7627f)

![微信图片_20241025112629](https://github.com/user-attachments/assets/86ebd868-afba-4ed3-b442-7f2946795056)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
......
demo.launch(server_name="127.0.0.1", share=True)
```

### System Info

```shell
gradio                         5.1.0
gradio_client                  1.4.0
```

### Severity

I can work around it

**Comment by Keerthi54654** [comment]
Can u Plz assign this to me so that i can fix this

**Comment by abidlabs** [comment]
This is expected! When you share a Gradio repo with share=True, the library is loaded from a cdn instead of through the tunnel as it’s significantly faster that way. If you need to make changes to the source code, consider opening a pull request to upstream them into Gradio
