### ISSUE TITLE
gradio reload mode can`t find module demo

### ISSUE THREAD

**Issue by phoenixor** [gradio-app/gradio#9843]
### Describe the bug

i am using a demo by open source project ['Qwen2-Audio'](https://github.com/QwenLM/Qwen2-Audio) with Gradio 4.44.1, i run the demo with reload mode by typing `gradio qwen2_audio.py`, every time it reload cause a error below.
`Changes detected in: /app/models/flux/Qwen2-Audio/qwen2_audio.py
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/home/sdkx/anaconda3/envs/venv_qwen2audio/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/sdkx/anaconda3/envs/venv_qwen2audio/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sdkx/anaconda3/envs/venv_qwen2audio/lib/python3.10/site-packages/gradio/utils.py", line 298, in watchfn
    demo = getattr(module, reloader.demo_name)
AttributeError: module 'qwen2_audio' has no attribute 'demo'`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.44.1
gradio_client version: 1.3.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.6.2.post1
fastapi: 0.115.3
ffmpy: 0.4.0
gradio-client==1.3.0 is not installed.
httpx: 0.27.2
huggingface-hub: 0.26.1
importlib-resources: 6.4.5
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.9.2
numpy: 2.0.2
orjson: 3.10.10
packaging: 24.1
pandas: 2.2.3
pillow: 10.4.0
pydantic: 2.9.2
pydub: 0.25.1
python-multipart: 0.0.12
pyyaml: 6.0.2
ruff: 0.7.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.5
typing-extensions: 4.12.2
urllib3: 2.2.3
uvicorn: 0.32.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.10.0
httpx: 0.27.2
huggingface-hub: 0.26.1
packaging: 24.1
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @phoenixor - the demo has to be defined outside of the `if __name__ == "__main__"` clause! Otherwise gradio won't be able to find your demo by importing the file.

**Comment by phoenixor** [comment]
> Hi @phoenixor - the demo has to be defined outside of the `if __name__ == "__main__"` clause! Otherwise gradio won't be able to find your demo by importing the file.

sorry to ask why `gradio xxx.py` run the code outside main twice, therefore it load qwen2-audio model twice and cause OOM error. i have a demo to show this situation.
![image](https://github.com/user-attachments/assets/71c6bb62-e762-4616-963d-e660f8837332)
![image](https://github.com/user-attachments/assets/c417ba3c-4457-41b4-a71b-afd4aec5b2bd)
