### ISSUE TITLE
Markdown Image doesn't show anymore

### ISSUE THREAD

**Issue by sglbl** [gradio-app/gradio#9844]
### Describe the bug

In the previous versions, I was adding an image using `gr.Markdown()`. After I upgraded to gradio 5 it still worked. But today when I check it doesn't work anymore. I upgraded to the last version but it's still the same.
(I can work around it using base64 image instead of html)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

logo_without_title = """
    <img src="/file=./logo.png" width="300" style='display:block; margin-left: auto; 
    margin-right: auto; padding-top: 1ch; align-items: center; justify-content: center;'>
"""

if __name__ == "__main__": 
    # Run the app
    with gr.Blocks() as demo:        
        # Header with logo
        gr.Markdown(logo_without_title)

    demo.launch(
        allowed_paths=["./", ".", "logo.png"],
        show_error=True   
    )


```

### Screenshot

![image](https://github.com/user-attachments/assets/b042def1-94b7-4860-b6ff-1a85f2a80667)

### System Info

```shell
Operating System: Linux
user@pc:test$ pip list | grep gradio
gradio             5.3.0
gradio_client      1.4.2
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
HI @sglbl ! It's the file route is now `/gradio_api/file=./logo.png`! Going to close as we've seen this question before #9680

**Comment by zhilongjia** [comment]
> HI @sglbl ! It's the file route is now `/gradio_api/file=./logo.png`! Going to close as we've seen this question before #9680

should in the docs.

**Comment by freddyaboulton** [comment]
Please open a PR @zhilongjia !

**Comment by zhilongjia** [comment]
> Please open a PR @zhilongjia !

Sorry, I can not make it as there are several problems when `pmpn install and pmpn dev` locally. 

It seems the changes should in .../gradio/gradio/components/markdown.py`

The original description of value is "value: Value to show in Markdown component. If callable, the function will be called whenever the app loads to set the initial value of the component. " and it could be changed to "The link of a local figure in markdown should be prefixed with '/gradio_api/file='. For example, '![figure](/gradio_api/file=xx.xx)'."
