### ISSUE TITLE
No way of keeping upload functionality for File component once files are added

### ISSUE THREAD

**Issue by JohnDuncanScott** [gradio-app/gradio#9860]
### Describe the bug

1. Have an empty File component - this shows the Upload dialog
2. Upload some files - files are uploaded
3. Want to upload some more files:
Expect: Can still upload files via an Upload button
Actual: Uploading files is a one off action. You have to clear all uploaded files just to upload an additional one

I deliberately didn't class this as an Enhancement / Feature request because not being able to upload more files severely limits this component and makes it frustrating to use.

I hoped this was fixed in v5 so upgraded to that, but no luck. There are also no options on the component to keep the upload functionality.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

gr.File(file_count="multiple")
```

### System Info

```shell
gradio==5.4.0
```

### Severity

Blocking usage of gradio

**Comment by pngwn** [comment]
Yeah I think we should add a plus button and still allow files to be dropped in the box to add to them.
