### ISSUE TITLE
why gradio reload mode runs twice

### ISSUE THREAD

**Issue by phoenixor** [gradio-app/gradio#9865]
### Describe the bug

recently i used project [qwen2-audio](https://github.com/QwenLM/Qwen2-Audio)，when i run it with reload mode, i found it load model twice and cause OOM error.
after testing, i found when run the code with `gradio xxx.py` reload mode, the code outside main will run twice, i have a demo from office docs to show this situation.
![image](https://github.com/user-attachments/assets/a4968e39-e4bc-47c1-9402-f21cc5d36f8a)
![image](https://github.com/user-attachments/assets/f7e116c1-623d-429d-9dda-4a978fadc7f0)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

print("outside demo********************")
with gr.Blocks() as demo:
    print("inside demo********************")
    gr.Markdown("# Greetings from Gradio!")
    inp = gr.Textbox(placeholder="What is your name?")
    out = gr.Textbox()

    inp.change(fn=lambda x: f"Welcome, {x}!", inputs=inp, outputs=out)

if __name__ == "__main__":
    print("inside main********************")
    demo.launch()
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.44.1
gradio_client version: 1.3.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.6.2.post1
fastapi: 0.115.3
ffmpy: 0.4.0
gradio-client==1.3.0 is not installed.
httpx: 0.27.2
huggingface-hub: 0.26.1
importlib-resources: 6.4.5
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.9.2
numpy: 2.0.2
orjson: 3.10.10
packaging: 24.1
pandas: 2.2.3
pillow: 10.4.0
pydantic: 2.9.2
pydub: 0.25.1
python-multipart: 0.0.12
pyyaml: 6.0.2
ruff: 0.7.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.5
typing-extensions: 4.12.2
urllib3: 2.2.3
uvicorn: 0.32.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.10.0
httpx: 0.27.2
huggingface-hub: 0.26.1
packaging: 24.1
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @phoenixor ! We need to import in a background thread so we can access the latest state of the variables and then hot swap them with the running version. You can place code inside `gr.NO_RELOAD` and it won't get re-loaded. Does that fix the problem?

```python
if gr.NO_RELOAD:
    model = ...

...
```

**Comment by phoenixor** [comment]
> Hi @phoenixor ! We need to import in a background thread so we can access the latest state of the variables and then hot swap them with the running version. You can place code inside `gr.NO_RELOAD` and it won't get re-loaded. Does that fix the problem?
> 
> ```python
> if gr.NO_RELOAD:
>     model = ...
> 
> ...
> ```

i mean when run the code with `gradio xxx.py` for the first time, not when reloading, any code outside main block will run twice. currently i need to put the model loading code inside main block to solve this problem, thus all codes are inside main block

**Comment by freddyaboulton** [comment]
Ok I think we can make it so that code in `NO_RELOAD` is never loaded in the watching thread
