### ISSUE TITLE
Using arbitrary paths for `gr.Audio` element

### ISSUE THREAD

**Issue by Josef-Haupt** [gradio-app/gradio#9867]
### Describe the bug

I am building an app with gradio that runs locally using pywebview. Until now, the user would select a directory and I'd collect all audio files inside and then feed them to the `gr.Audio` element, which worked perfectly before updating to Gradio `5.4.0`.

I've read the [Migration Guide](https://github.com/gradio-app/gradio/issues/9463) and the post about [File Access and Security](https://307f1325.gradio-website.pages.dev/main/guides/file-access) and I do get it in the context of a web app. But since my app runs locally I do not care for the files selected by the user. If I run the app now with Gradio 5, I'll get this error:

```
gradio.exceptions.InvalidPathError: Cannot move some_path\XC525205_37.flac to the gradio cache 
dir because it was not created by the application or it is not located in either the current working 
directory or your system's temp directory. To fix this error, please ensure your function returns files 
located in either the current working directory, your system's temp directory or add parent_directory 
to the allowed_paths parameter of launch().
```

So to get the behaviour I used in Gradio 4, I would have to add all possible paths (C, D, ...) to `allowed_paths` which would defeat the purpose of the feature. Or I could move the file to the specified locations, basically cache it, for gradio to cache it again, which is also pretty roundabout way of doing things.

Is there a way to get the behavior of gradio 4 or disable the caching in general? If not, I'll probably go back to Gradio 4, for the time being.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```py
import webview
import gradio as gr

_WINDOW: webview.Window

def user_select_directory():
    dirname = _WINDOW.create_file_dialog()

    return gr.Audio(value=dirname[0], visible=True) if dirname else None

with gr.Blocks(analytics_enabled=False) as demo:
    selection_btn = gr.Button("Select file")
    audio_element = gr.Audio(visible=False)

    selection_btn.click(user_select_directory, outputs=audio_element)

url = demo.queue(api_open=False).launch(prevent_thread_lock=True, quiet=True, show_api=False)[1]
_WINDOW = webview.create_window("Gradio-App", url)

webview.start(private_mode=False)
```

### System Info

```shell
Python: 3.11
Gradio: 5.4.0
Win 11
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
> to get the behaviour I used in Gradio 4, I would have to add all possible paths (C, D, ...) to allowed_paths which would defeat the purpose of the feature

Yes if you wanted to be able to process any possible file I think this is what you would have to do

**Comment by Josef-Haupt** [comment]
That is easier said than done unfortunately, as paths to drives differ in Win and Mac/Linux. But if that's how it's supposed to be then I'll come up with something. Thanks for the feedback

**Comment by freddyaboulton** [comment]
Thank you for the patience @Josef-Haupt .

**Comment by Josef-Haupt** [comment]
This is what I came up with. Should work on win, darwin and linux.
I just blindly add all possible drives on windows and the root `/` on non-win machines, which should account for drives mounted during execution. Seems to be working so far.
```py
import os
import sys

import webview
import gradio as gr

_WINDOW: webview.Window


def user_select_directory():
    filename = _WINDOW.create_file_dialog()

    if filename:
        return gr.Audio(value=filename[0], visible=True)

    return None


def get_win_drives():
    from string import ascii_uppercase as UPPER_CASE

    return [f"{drive}:\\" for drive in UPPER_CASE]


with gr.Blocks(analytics_enabled=False) as demo:
    selection_btn = gr.Button("Select file")
    audio_element = gr.Audio(visible=False)

    selection_btn.click(user_select_directory, outputs=audio_element)

allwowed_drives = get_win_drives() if sys.platform == "win32" else ["/"]
url = demo.queue(api_open=False).launch(
    prevent_thread_lock=True,
    quiet=True,
    show_api=False,
    allowed_paths=allwowed_drives
)[1]
_WINDOW = webview.create_window("Gradio-App", url)

webview.start(private_mode=False)
```

**Comment by Josef-Haupt** [comment]
Actually, the docs could probably benefit from a note, concerning this behaviour and how to work around it, just a suggestion though.
