### ISSUE TITLE
Problem for image examples when using absolute path.

### ISSUE THREAD

**Issue by JefferyChiang** [gradio-app/gradio#988]
### Describe the bug

My code is work in 2.4.6 version. Recently I updated to 2.7.5.2, and found that the images didnt show in the examples.
After a while, I figure out that is the issue about the absolute path.
In gradio/ app.py, it will force to join the app.cwd and path, so the final path is wrong.
`@app.get("/file/{path:path}", dependencies=[Depends(login_check)])
def file(path):
    print(app.cwd, path)
    config.app = app
    if app.interface.encrypt and isinstance(
        app.interface.examples, str) and path.startswith(
            app.interface.examples):
        with open(safe_join(app.cwd, path), "rb") as encrypted_file:
            encrypted_data = encrypted_file.read()
        file_data = encryptor.decrypt(
            app.interface.encryption_key, encrypted_data)
        return FileResponse(
            io.BytesIO(file_data), attachment_filename=os.path.basename(path))
    else:
        return FileResponse(safe_join(app.cwd, path))`

After modifying the `return FileResponse(safe_join(app.cwd, path))` to` return FileResponse(path))`, it works properly.
Is the images path in examples are strict to use relative path? Because I didnt find any description of this in the Gradio Docs.

### Reproduction

Below is my code for gr.interface:
`iface = gr.Interface(fn = AD_UI,
                     inputs=[
                             gr.inputs.Radio(["Predict"], default = 'Predict'),
                             gr.inputs.Image(shape=(config.load_size, config.load_size), optional=True, type='numpy'),
                             ],
                     outputs=[
                              gr.outputs.Image(type="auto", label='Result'),
                              ],
                     examples=[['Predict','D:\\AnomalyDetection\\AD_toolbox\\datasets\\tile\\test\\good\\000.png'],
                               ['Predict','D:\\AnomalyDetection\\AD_toolbox\\datasets\\bottle\\test\\good\\000.png'],
                               ],
                     examples_per_page = 5,
                     layout = 'vertical',
                     theme = 'default',
                     css=css,
                     allow_flagging = 'never',
                     live = False,
                     )`

### System Info

```shell
python 3.7.7
gradio 2.7.5.2
chrome
windows 7
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Thanks for catching this @JefferyChiang, would you like to open a PR so that we can credit you for the fix?
