### ISSUE TITLE
`Model3D` component does not work well on mobile

### ISSUE THREAD

**Issue by dawoodkhan82** [gradio-app/gradio#989]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by pngwn** [comment]
It would be good to tweak the scroll-zoom a little if possible too, it zooms quite aggressively.

**Comment by pngwn** [comment]
cc @gary149 for design guidance.

**Comment by radames** [comment]
Possibly related to this issue. The Model3D viewer currently doesn't work well on mobile specially the pinch multi-touch gestures. Here is a playground example I've found that seems to work well on mobile https://playground.babylonjs.com/#4U6TVQ#3

**Comment by gary149** [comment]
> Possibly related to this issue. The Model3D viewer currently doesn't work well on mobile specially the pinch multi-touch gestures. Here is a playground example I've found that seems to work well on mobile https://playground.babylonjs.com/#4U6TVQ#3

Nice find, just tried it on an iPhone and it works very well. Maybe let's try to get the exact same behavior for our 3d viewer @radames?

**Comment by abidlabs** [comment]
I think the most important thing here is to make sure the Model3D component works well on mobile -- everything else can be part of a custom component (or if heavily requested, can be added to our Model3D component) after 4.0.

I'll rename the issue to focus on the mobile issue.
