### ISSUE TITLE
dropdown Unable to render correctly

### ISSUE THREAD

**Issue by zd1990** [gradio-app/gradio#9894]
### Describe the bug

There are three dropdown components. The second component listens to the select event of the first component, and the third component listens to the select event of the second component. The first two components can be rendered correctly, but the third component renders incorrectly.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr


def greet(name):
    return "Hello " + name + "!"


with gr.Blocks() as demo:
    datasource_name = gr.Dropdown(label="ds", choices=[], value="test")
    database_name = gr.Dropdown(label="dn", choices=[])
    table = gr.Dropdown(label="tb", choices=[], allow_custom_value=True)
  
    @datasource_name.select(inputs=[datasource_name], outputs=[database_name]) # pylint: disable=E1101
    def get_database(d_name):
        datasource_model = datasource_controller.get(d_name)
        datasource = get_datasource(datasource_model)
        return gr.Dropdown(label="dn", choices=datasource.get_database_list())
    
    @database_name.select(inputs=[datasource_name,database_name], outputs=table) # pylint: disable=E1101
    def get_table(databsource, db):
        datasource_model = datasource_controller.get(databsource)
        datasource = get_datasource(datasource_model)
        tables = datasource.get_table_list(db)
        return gr.Dropdown(label="tb", choices=tables)
    

if __name__ == "__main__":
    demo.launch()


```

### Screenshot

<img width="1726" alt="image" src="https://github.com/user-attachments/assets/2dda3274-998c-4347-8fe4-ecd9b76beeec">

### System Info

```shell
gradio==5.4.0
```

### Severity

I can't work around it

**Comment by abidlabs** [comment]
Hi @zd1990 the reason you are seeing this behavior is that Gradio automatically renders any component which is used as an input _anywhere_ in your code in _interactive_ mode, whereas components that are only have a fixed value are rendered non-interactively. If you'd like to change that, you can set `interactive=True` or `interactive=False` in your component.

**Comment by zd1990** [comment]
@abidlabs Thank you for your reply. I understand that this approach is similar to compiler optimization.
