### ISSUE TITLE
Dropdown's preprocessing error when using a dropdown in a function without refreshing the frontend after starting the backend

### ISSUE THREAD

**Issue by GuizMeuh** [gradio-app/gradio#9896]
### Describe the bug

An error occurs when attempting to use a dropdown in a function. This issue specifically arises if the backend is started without refreshing the frontend. 
Here is the error:
`\Lib\site-packages\gradio\components\dropdown.py", line 202, in preprocess
    raise Error(
gradio.exceptions.Error: 'Value: Value 1 is not in the list of choices: []'
Keyboard interruption in main thread... closing server.`
This was not happening before in gradio4.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

I've created a small Gradio app to reproduce the dropdown issue when the backend is restarted without refreshing the frontend.

```python
import gradio as gr 

def set_interface():
    dropdown_choices = ["Option 1", "Option 2", "Option 3"]
    dropdown = gr.Dropdown(choices=dropdown_choices, label="Select an option", visible=True, allow_custom_value=True)
    textbox = gr.Textbox(label="Selected option", visible= True)
    button = gr.Button("Submit", visible=True)
                
    return (dropdown, textbox, button)
```

```python
import gradio as gr
from set_front import set_interface
def update_textbox(choice):
    return f"You selected: {choice}"


with gr.Blocks() as demo:
    dropdown = gr.Dropdown(visible=False)
    textbox = gr.Textbox(visible=False)
    button=gr.Button(visible=False)
    button.click(
        fn=lambda : gr.update(choices=["Value 1", "Value 2", "Value 3"]),
        outputs=dropdown,
    )
    dropdown.change(fn=update_textbox, inputs=dropdown, outputs=textbox)

    demo.load(
        fn=set_interface,
        outputs=[dropdown, textbox, button]
    )
gr.close_all()
demo.launch()
```

### Screenshot

Initially :
![image](https://github.com/user-attachments/assets/59f632ab-f713-43d0-962e-dc133beaf1be)

Then if I click on my button it changes the dropdown.
![image](https://github.com/user-attachments/assets/9fce1759-7048-4bfc-b146-53006f7439c3)

Until there everything is going well.
But now if I restart my backend and I choose an input it raises an error:
![image](https://github.com/user-attachments/assets/8a77f75c-5e72-4b4b-861c-420accd049b0)

Steps to Reproduce:

Start the application and observe the initial state of the dropdown.
Click the button to change the dropdown.
Restart the backend.
Attempt to select an input from the dropdown.
Expected Behavior: The dropdown should function correctly without errors after the backend is restarted.

Actual Behavior: An error is raised when selecting an input from the dropdown after restarting the backend.

### Logs

```shell
`\Lib\site-packages\gradio\components\dropdown.py", line 202, in preprocess
    raise Error(
gradio.exceptions.Error: 'Value: Value 1 is not in the list of choices: []'
Keyboard interruption in main thread... closing server.`
```

### System Info

```shell
gradio version: 5.4.0
gradio_client version: 1.4.2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.6.2.post1
audioop-lts is not installed.
fastapi: 0.115.4
ffmpy: 0.4.0
gradio-client==1.4.2 is not installed.
httpx: 0.27.2
huggingface-hub: 0.26.2
jinja2: 3.1.4
markupsafe: 2.1.5
numpy: 2.1.3
orjson: 3.10.11
packaging: 24.1
pandas: 2.2.3
pillow: 11.0.0
pydantic: 2.9.2
pydub: 0.25.1
python-multipart==0.0.12 is not installed.
pyyaml: 6.0.2
ruff: 0.7.2
safehttpx: 0.1.1
semantic-version: 2.10.0
starlette: 0.41.2
tomlkit==0.12.0 is not installed.
typer: 0.12.5
typing-extensions: 4.12.2
urllib3: 2.2.3
uvicorn: 0.32.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.10.0
httpx: 0.27.2
huggingface-hub: 0.26.2
packaging: 24.1
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @GuizMeuh unless I'm misunderstanding, this is exactly expected behavior. When you restart the Gradio application, the app resets to its initial state, in which the only valid dropdown choices are listed here:

> dropdown_choices = ["Option 1", "Option 2", "Option 3"]

So selecting `Value 1` results in an error, which is displayed to you in the frontend.
