### ISSUE TITLE
All buttons in my interface became flat after switching to Gradio 5

### ISSUE THREAD

**Issue by Bebra777228** [gradio-app/gradio#9899]
### Describe the bug

I think the title makes it clear what my problem is.
After switching to Gradio 5, all the buttons in my interface became flat. This is visible in the "Screenshot" section, where I've attached screenshots from Gradio 4.44.1 and Gradio 5.5.0.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Group():
    with gr.Row():
        generate_btn = gr.Button("Generate", variant="primary", scale=2)
        converted_voice = gr.Audio(label='Converted Voice', interactive=False, scale=9)
        output_format = gr.Dropdown(['mp3', 'flac', 'wav'], value='mp3', label='File Format', scale=1)

```

### Screenshot

Gradio 4.44.1:
![Скриншот 05-11-2024 132751](https://github.com/user-attachments/assets/20f7deb8-bade-4791-88c5-5b6394bebdf4)
Gradio 5.5.0:
![Скриншот 05-11-2024 132534](https://github.com/user-attachments/assets/a590a9c8-2474-40b8-8ec9-a6a7221c335f)

### System Info

```shell
The interface runs on HuggingFace, I don't know what system is there :)
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @Bebra777228, set `equal_height=True` in the `gr.Row()` please!

**Comment by Bebra777228** [comment]
Yes, this solved my problem, thanks!
