### ISSUE TITLE
Improve error reporting and exception message for `gradio.components.checkboxgroup.CheckboxGroup`

### ISSUE THREAD

**Issue by muhammadyaseen** [gradio-app/gradio#9902]
- [x] I have searched to see if a similar issue already exists.

My Gradio version: `5.1.0`

In `gradio.components.checkboxgroup.CheckboxGroup` class there is a function called `preprocess(self, payload)`. In this function, gradio checks if the values passed via the `payload` argument are actually valid choices by comparing them against `self.choices`. This is all good, but there can be some surprising and hard to debug error messages because of how the data is represented in the f-string used by the error message.

**Is your feature request related to a problem? Please describe.**  

**For example:**

if the `payload =  ["1", "2", "3", "4", "5"]` and `choices = [1, 2, 3, 4, 5]`, the error message presented to the user would be: `gradio.exceptions.Error: 'Value: 1 is not in the list of choices: [1, 2, 3, 4, 5]'`, which is surprising / unexpected / misleading.

**Describe the solution you'd like**  
The error message should indicate more clearly why exactly is the check failing.

**Additional context**  

I added the following print statements in the `preprocess` function to clearly show the issue while debugging:
```
for cv in choice_values:
    print("Type Choice: ", type(cv))

for v in payload:
    print("Type Payload: ", type(v))
```
![grafik](https://github.com/user-attachments/assets/8225495b-0646-4a5b-934a-171a99a653a3)

I will be happy to contribute a fix to this. My current idea is to simply use `repr` in the error message f-string, optionally with `type` info:

<img width="1314" alt="Bildschirmfoto 2024-11-05 um 15 04 46" src="https://github.com/user-attachments/assets/71b516ce-7a15-4932-b45b-4406b36e686f">

... or even clearer with type info

<img width="1368" alt="Bildschirmfoto 2024-11-05 um 15 04 33" src="https://github.com/user-attachments/assets/e4c31d7b-690a-4246-8355-a16107304205">

**Comment by abidlabs** [comment]
Thanks @muhammadyaseen sure, I think adding the type information could be informative to users. Please open a PR with the fix and we'd be happy to review

**Comment by muhammadyaseen** [comment]
Sure, will get to it and make a PR soon-ish.
