### ISSUE TITLE
Import front end to back end 

### ISSUE THREAD

**Issue by ZoRaFa** [gradio-app/gradio#991]
Hello, 
i'm using Gradio for a demo of trash detection AI called Surfnet (https://huggingface.co/spaces/Surfrider/surfnet). 
I'm trying to create a pop up in HTML/CSS to show informations to users about the project (exemple below)

![Surfnet_popup](https://user-images.githubusercontent.com/78821052/163194178-57f5369a-4cb0-460f-a604-31ee544e2f23.PNG)

Do you think is it possible to add a feature which allows to use HTML/CSS or other front-dev language with Gradio ? 

Thank you,

Best regards,

**Comment by abidlabs** [comment]
Thanks for the question @ZoRaFa. Let me ask the team about this and get back to you. We might be able to repurpose our login functionality to allow arbitrary messages. cc @aliabid94

**Comment by abidlabs** [comment]
Hi @ZoRaFa you can now do this using the new Blocks API. The Blocks API allows you to have much more control over the API, as well as hide or show different components. Take a look at this guide for more info: https://www.gradio.app/introduction_to_blocks/

**Comment by ZoRaFa** [comment]
Thank you !
