### ISSUE TITLE
`allow_preview=False` not working as expected in custom Gallery class  

### ISSUE THREAD

**Issue by zhristophe** [gradio-app/gradio#9910]
### Describe the bug

I'm using a custom `Gallery` class that inherits from `gr.Gallery` in my Gradio application. I've set the `allow_preview` parameter to `False` when creating the `Gallery` instance, but the preview functionality is still being triggered when I click on the images. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

1. Create a Gradio application with the following code:  
```python
if __name__ == "__main__":  
    class Gallery(gr.Gallery):  
        def __init__(self, **kwargs):  
            super().__init__(**kwargs)  

    with gr.Blocks() as demo:  
        gallery = Gallery(allow_preview=False)  
        imgs = gr.State()  
        print(gallery.allow_preview) 

        demo.load(lambda: ["hello.png"], None, gallery)
   
    demo.launch()
```
2. Run it, and observe that the `print(gallery.allow_preview)` statement outputs `False`, indicating that the `allow_preview` parameter is being set correctly.
3. Click on one of the images in the gallery.
4. Observe that the image is still being previewed, despite the `allow_preview=False` setting.

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 5.5.0
gradio_client version: 1.4.2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.6.2.post1
audioop-lts is not installed.
fastapi: 0.115.4
ffmpy: 0.4.0
gradio-client==1.4.2 is not installed.
httpx: 0.27.2
huggingface-hub: 0.26.2
jinja2: 3.1.4
markupsafe: 2.1.5
numpy: 2.1.3
orjson: 3.10.11
packaging: 24.1
pandas: 2.2.3
pillow: 10.4.0
pydantic: 2.9.2
pydub: 0.25.1
python-multipart==0.0.12 is not installed.
pyyaml: 6.0.2
ruff: 0.7.2
safehttpx: 0.1.1
semantic-version: 2.10.0
starlette: 0.41.2
tomlkit==0.12.0 is not installed.
typer: 0.12.5
typing-extensions: 4.12.2
urllib3: 2.2.3
uvicorn: 0.32.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.10.0
httpx: 0.27.2
huggingface-hub: 0.26.2
packaging: 24.1
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @zhristophe can you explain why are you creating a custom subclass? We don't really support that usage.

**Comment by zhristophe** [comment]
> Hi @zhristophe can you explain why are you creating a custom subclass? We don't really support that usage.

This was just an attempt. I have already completed the original task using a combination approach, and by reading the source code, I have a general understanding of the underlying reasons. However, I must say that I haven't read anywhere in the documentation or online that inheriting Gradio components is prohibited. Moreover, in my initial attempts, some functionalities were working as expected.

**Comment by abidlabs** [comment]
Hmm I'll go ahead and close this if there's no need for this feature. Inheriting Gradio components e.g. for the purpose of adding attributes will not work since attributes need to be added in the frontend as well.
