### ISSUE TITLE
guides with examples is fault

### ISSUE THREAD

**Issue by fishANDdog** [gradio-app/gradio#9914]
### Describe the bug

https://www.gradio.app/guides/creating-a-chatbot-fast

in above tutorial，the example in gradio version 5.5.0 is fault，suggested update examples

### System Info

```shell
python 3.10.5
gradio 5.5.0
```

**Comment by abidlabs** [comment]
Hi we'll be updating the Chatbot docs, but as this issue doesn't have any specific details, I'll close this
