### ISSUE TITLE
ChatInterface don't have 'retry_btn', 'undo_btn' and 'clear_btn' arguments

### ISSUE THREAD

**Issue by nmtan2001** [gradio-app/gradio#9917]
### Describe the bug

I tried the code example in 
https://www.gradio.app/guides/creating-a-chatbot-fast#customizing-your-chatbot

which have 
```
try_btn=None,
undo_btn="Delete Previous",
clear_btn="Clear",
```

all of these got error:
TypeError: ChatInterface.__init__() got an unexpected keyword argument 'retry_btn'

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def yes_man(message, history):
    if message.endswith("?"):
        return "Yes"
    else:
        return "Ask me anything!"

gr.ChatInterface(
    yes_man,
    type="messages",
    chatbot=gr.Chatbot(height=300),
    textbox=gr.Textbox(placeholder="Ask me a yes or no question", container=False, scale=7),
    title="Yes Man",
    description="Ask Yes Man any question",
    theme="soft",
    examples=[{"text": "Hello"}, {"text": "Am I cool?"}, {"text": "Are tomatoes vegetables?"}],
    cache_examples=True,
    retry_btn=None,
    # undo_btn="Delete Previous",
    # clear_btn="Clear",
).launch()
```

### Screenshot

![image](https://github.com/user-attachments/assets/d2ab762b-94d3-4d09-9fe6-ab6516c9c372)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 5.3.0
gradio_client version: 1.4.2
```

### Severity

I can work around it

**Comment by pabl-o-ce** [comment]
The new version docs it seems that there is no more this options and buttons in the UI.
They choose more minimalist style

**Comment by kebiyoon** [comment]
I faced the same problem....😂

**Comment by burtenshaw** [comment]
I also found this error. 

@abidlabs I have some time to tackle it, if you think it's a good first issue.
