### ISSUE TITLE
Specify alternative style of image to render for dark/light themes

### ISSUE THREAD

**Issue by flacomalone** [gradio-app/gradio#9936]
- [X] I have searched to see if a similar issue already exists.

Hello! I thougt it would be nice to have an option for images (maybe for some other components, such as the css of a block), to specify an alternative resource or definition for the black/light mode, so that when the accessibility of the image depends on the background of the app, this can be automatically set depending on the chosen theme.

For example, in this image, I'd be nice to have an alternative white version of the image so this could be done automatically
![image](https://github.com/user-attachments/assets/7bfb0684-4269-4791-a970-4d77d34793d6)

Cheers!

**Comment by abidlabs** [comment]
Hi @flacomalone you can do this by reading the query parameter (`?__theme=dark`) and changing the value appopriately. See here for how to read query parameters in Gradio: https://github.com/gradio-app/gradio/pull/5681
