### ISSUE TITLE
gr.Dropdown has a fake initial value when using value=None

### ISSUE THREAD

**Issue by rsxdalv** [gradio-app/gradio#9948]
### Describe the bug

The dropdown appears to have a value but the function does not receive a value. Also when trying to use the value of a dropdown, it suddenly shows correctly that it is empty. But whenever the page is opened/refreshed it shows the 'mirage' of a value.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python

import gradio as gr

with gr.Blocks() as demo:
    gr.Dropdown(
        choices=["a", "b", "c"],
        value=None,
    )

```

### Screenshot

![image](https://github.com/user-attachments/assets/f7551158-18b1-4155-b0d5-586e4dd8a784)

### System Info

```shell
gradio==5.1.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @rsxdalv this has been fixed in the latest version of `gradio`, please upgrade to 5.5.0 or later!

**Comment by rsxdalv** [comment]
Thanks for the info. FYI 5.5.0 is completely broken (UI does not respond) due to a bug I reported elsewhere, but hopefully 5.6.0 or a later version is going to work again.
