### ISSUE TITLE
`example_labels` does not work for ChatInterface

### ISSUE THREAD

**Issue by jamie0725** [gradio-app/gradio#9951]
### Describe the bug

Based on the screenshot, when using `additional_inputs` in ChatInterface and providing example prompts, you must manually include default values for these additional inputs in the examples; otherwise, they will be set to `None`. However, I dislike the examples being displayed beneath the chatbot and the visibility of the additional input values. After reviewing the documentation, I believe `example_labels` could replace the example display, showing only the example text within the chatbot. Unfortunately, the variable appears to have no effect.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr



def get_chat_response(
    req: gr.Request,
    message: str,
    history: list,
    var_a: bool,
    var_b: list[str],
    var_c: bool,
):

    print(var_a, var_b, var_c)
    return "Hello, World!"


def get_blocks():

    with gr.Blocks(title="Test", theme=gr.themes.Default()) as demo:
        gr.Markdown("# Test")
        with gr.Tab("Test"):
            with gr.Row():
                with gr.Row():
                    var_a = gr.Checkbox(
                        label="A1",
                        value=True,
                    )
                    var_c = gr.Checkbox(
                        label="A2",
                        value=True,
                    )
                var_b = gr.CheckboxGroup(
                    label="A3",
                    choices=["1", "2", "3", "4"],
                    value=None,
                )
            chatbot = gr.Chatbot(
                type="messages",
                height=300,
                render=False,
                show_copy_button=True,
            )
            gr.ChatInterface(
                get_chat_response,
                type="messages",
                chatbot=chatbot,
                additional_inputs=[var_a, var_b, var_c],
                examples=[["hello", True, [], True], ["thisisatest", True, [], True], ["totestthetest", True, [], True]],
                example_labels=["A", "B", "C"],
                autofocus=False,
                show_progress="full",
            )
    demo.queue()

    return demo


demo = get_blocks()
demo.launch()

```

### Screenshot

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/30b1de44-6bb9-4d72-892c-2b13a4579025">

### System Info

```shell
gradio=5.5.0
```

### Severity

Blocking usage of gradio

**Comment by jamie0725** [comment]
What I want is one of these behaviors:
1. Not required to set the values for `additional_inputs` in examples, but still use the inputs' default values.
2. Setting the values for `additional_inputs` in examples is also fine, but don't show their values on the webpage; instead, only show the text part to the user as an example prompt inside the chatbot.

In the end, I want the examples to use the same default values for `additional_inputs`, and at the same time want the examples to be shown like this:
<img width="804" alt="image" src="https://github.com/user-attachments/assets/c0e9cab0-4709-4706-87f0-11970d8fa20d">

**Comment by abidlabs** [comment]
Hi @jamie0725 you can achieve this by setting a default value for the additional inputs in your chat input function, and then passing `None` in the examples list. Here's an example that illustrates this:

```py
import gradio as gr


def fn(message, history, seed=5):
    return str(seed)


gr.ChatInterface(fn=fn, examples=[["hey", None], ["hello", None]], additional_inputs=[gr.Slider(value=5)], type="messages").launch()
```

I'll update the docstrings to be clearer about this

**Comment by jamie0725** [comment]
Hi @abidlabs, I tried this as well in `gradio 5.5.0`, actually this was my first attempt, but it had no effect, the default values will be `none` instead of the real default values. Is this fixed in later versions?

**Comment by abidlabs** [comment]
Did you set a default value in your function (e.g. `seed=5`)? Because indeed `None` gets passed into the function, but it will be replaced by the default value. Try the example above and let me know if it works for you -- I just tested in 5.6.0 and it works for me, although I think it will work on 5.5.0 as well.
