### ISSUE TITLE
`gr. Datetime` is missing a param `interactive: bool`

### ISSUE THREAD

**Issue by Isuxiz** [gradio-app/gradio#9957]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As the title says, some components do not have a boolean parameter like other components (`gr.TextBox`, `gr.Dropdown`, `gr.Radio`, `gr.Checkbox`, etc.) to control whether the user can edit its value. I have only found two such components as mentioned in title so far, but there may be more components that have this problem.

**Describe the solution you'd like**  
Add an `interactive: bool` parameter to these components to explicitly control whether the component can be edited.

**Additional context**  
My motivation is as follows. Consider these two scenarios:
1. Your application requires multiple phased steps, and you only want the parameter input controls of the subsequent steps to become interactive after the previous step is successfully completed.
2. You are very clear that a component is only used to display output, and you don't want users to modify (perhaps accidentally) its displayed value.

**Comment by abidlabs** [comment]
Hi @Isuxiz the `gr.JSON` component doesn't support any interactivity (you can't edit the value), so I don't think an `interactive` parameter is needed for that component. But I do agree that `gr.Datetime` should have this parameter
