### ISSUE TITLE
It isn't possible to disable the heading of a Label

### ISSUE THREAD

**Issue by umarbutler** [gradio-app/gradio#9975]
### Describe the bug

By default, `gr.Label` will always show the top class in a `h2` tag, even if the confidence for that class is <0.5. There doesn't seem to be any way to disable this.

See also https://discuss.huggingface.co/t/how-to-hide-first-label-in-label-component/58036

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

See above.

### System Info

```shell
N/A
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Yes, I think this makes sense for the multilabel setting, related: https://github.com/gradio-app/gradio/issues/1051
