### ISSUE TITLE
Conda-forge: upload latest versions

### ISSUE THREAD

**Issue by stefansimik** [gradio-app/gradio#9976]
I would like to ask,
if it would be possible to ensure, that latest gradio versions are uploaded on conda-forge.

Right now 17. November  - the latest uploaded version of gradio is v5.1.0 despite there v5.6.0 available on Pypi.

Having latest versions available is really important feature of any library. 

![CleanShot 2024-11-17 at 22 05 10@2x](https://github.com/user-attachments/assets/d6dabe49-c5a0-419e-a480-393eedddc8aa)

**Comment by abidlabs** [comment]
Hi @stefansimik we do not maintain the conda forge for Gradio, its maintained by volunteers, please reach out to the conda forge community to update the package version: https://conda-forge.org/docs/maintainer/adding_pkgs/
