### ISSUE TITLE
Queuing related guides contain outdated information about `concurrency_count`

### ISSUE THREAD

**Issue by the-eddie** [gradio-app/gradio#9977]
### Describe the bug

These guides related to queuing still refer to `concurrency_count`:
- [Queuing](https://www.gradio.app/guides/queuing)
- [Setting Up a Demo for Maximum Performance](https://www.gradio.app/guides/setting-up-a-demo-for-maximum-performance)

However, as confirmed in #9463:
> The `concurrency_count` parameter has been removed from `.queue()`. In Gradio 4, this parameter was already deprecated and had no effect. In Gradio 5, this parameter has been removed altogether.

Running the code from [Queuing](https://www.gradio.app/guides/queuing) guide results in the error below:
```
Exception has occurred: TypeError
EventListener._setup.<locals>.event_trigger() got an unexpected keyword argument 'concurrency_count'
  File "./test_gradio.py", line 23, in <module>
    greet_btn.click(fn=greet, inputs=[tag, output], outputs=[
TypeError: EventListener._setup.<locals>.event_trigger() got an unexpected keyword argument 'concurrency_count'
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
# Sample code from https://www.gradio.app/guides/queuing

import gradio as gr

with gr.Blocks() as demo:
    prompt = gr.Textbox()
    image = gr.Image()
    generate_btn = gr.Button("Generate Image")
    generate_btn.click(image_gen, prompt, image, concurrency_count=5)
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 5.6.0
gradio_client version: 1.4.3
```

### Severity

I can work around it

**Comment by yinsumirage** [comment]
I've also noticed that `concurrency_limit` parameter isn't mentioned in the documentation, what do you think about adding it to the documentation? @freddyaboulton
