### ISSUE TITLE
Cannot set show_api to False in mount_gradio_app

### ISSUE THREAD

**Issue by canytam-krystal** [gradio-app/gradio#9980]
### Describe the bug

I create a gradio app using mount_gradio_app so I don't need to user the launch function call. I want to hide the "Use via API" on the footer. I try to add app_kwargs={"show_api": False} when calling the mount_gradio_app() and the "Use via API" message still shown on the footer.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
5.5.0
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Would you like to submit a PR for this @canytam-krystal ?
