### ISSUE TITLE
Multi-user session state conflict using gr.State (and gr.BrowserState)

### ISSUE THREAD

**Issue by anirbanbasu** [gradio-app/gradio#9983]
### Describe the bug

I have a Gradio app with a complex Blocks UI, which has a set of variables (including dictionaries, lists, and even other class instances) that I encapsulate in a `deepcopy`-able class and maintain an instance of that class as a `gr.State` object. I need to support simultaneous multi-user access through the browser such that the changes to those variables made by one user do not conflict with that from another user.

However, I notice state conflicts. The data from one user overrides the data of the other user. Either this is a bug or I am doing something wrong. There are others who have brought this up (e.g., #4920 #3541) but I do not see the solution.

My code is too big to explain the point, so I will write below sort-of-a-pseudocode to illustrate the situation. I am guessing that there is only ever one copy of the `user_state` that is being passed along. What can I do to make sure that for every independent user access, a new `user_state` is created?

Slightly related, `gr.BrowserState` (as described at https://www.gradio.app/guides/state-in-blocks) is not available in my version of Gradio (5.5.0).

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

class StateData:
    def __init__(self, create_uninitialised: bool = False):
        if not create_uninitialised:
            self.state_var1: List[SomeType] = []
            self.state_var2 = SomeObject()
            # And so on

    def __deepcopy__(self, memo):
        newone = type(self)(create_uninitialised=True)
        newone.__dict__.update(self.__dict__)
        return newone

class GradioApp:
        def some_sub_component(self, user_state: gr.State):
            # Build this component using information from the user_state by accessing it as user_state.value.
            # This sub component can call other functions including those for user interactions, which are omitted for brevity.

        def create_ui(self) -> gr.Blocks:
            user_state = gr.State(StateData())
            gr.Markdown("Some text")
            self.some_sub_component(user_state)

if __name__ == "__main__":
    app = GradioApp()
    ui = app.create_ui()
    ui.queue().launch()
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 5.5.0
gradio_client version: 1.4.2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.6.2.post1
audioop-lts is not installed.
fastapi: 0.115.4
ffmpy: 0.4.0
gradio-client==1.4.2 is not installed.
httpx: 0.27.2
huggingface-hub: 0.26.2
jinja2: 3.1.4
markupsafe: 2.1.5
numpy: 1.26.4
orjson: 3.10.11
packaging: 24.2
pandas: 2.2.3
pillow: 11.0.0
pydantic: 2.9.2
pydub: 0.25.1
python-multipart==0.0.12 is not installed.
pyyaml: 6.0.2
ruff: 0.7.3
safehttpx: 0.1.1
semantic-version: 2.10.0
starlette: 0.41.2
tomlkit==0.12.0 is not installed.
typer: 0.13.0
typing-extensions: 4.12.2
urllib3: 2.2.3
uvicorn: 0.32.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.9.0
httpx: 0.27.2
huggingface-hub: 0.26.2
packaging: 24.2
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

Blocking usage of gradio

**Comment by anirbanbasu** [comment]
Thinking about it further, is the problem in my `__deepcopy__` method, which assigns references to an existing list or dictionary, perhaps, to the newly created instances instead of creating new lists and dictionaries?

**Comment by abidlabs** [comment]
Hi @anirbanbasu I believe that's correct, deepcopy needs to be completely separate lists/dicts, otherwise, they'll be overwritten between sessions

> Slightly related, gr.BrowserState (as described at https://www.gradio.app/guides/state-in-blocks) is not available in my version of Gradio (5.5.0).

Can you upgrade to 5.6.0? It was introduced in that version

**Comment by anirbanbasu** [comment]
Hi @abidlabs, I have now upgraded to version 5.6.0 and changed my `__deepcopy__` implementation slightly to create new lists and dictionaries instead of copying them over.

Using `gr.State`, I run into the same problem of state conflicts. For example, `state_var1` for some user contains a list of 10 items and then another user has 5 items for `state_var1`, it is the one single copy of `state_var1` that is being modified. Thus, the first user attempting to access item index 6 on the list will be met with `IndexError: list index out of range`.

I will try to use `gr.BrowserState` and report back on this thread. However, is this above behaviour of `gr.State` expected? If yes, then why is it even there because I could achieve the same result by having the `state_var1` as a variable of my `GradioApp` and access it as `self.state_var1`? Does `gr.State` deal with concurrent access nicely or is it just a convenient way of setting a global variable using the same interface that one can use for components and their event handlers?

**Comment by abidlabs** [comment]
@anirbanbasu can you share a repro with your updated `__deepcopy__` implementation?

**Comment by anirbanbasu** [comment]
@abidlabs, for confidentiality reasons, I cannot. However, I can make a new public repository with a minimal code to illustrate the problem. Will that be okay?

**Comment by abidlabs** [comment]
A minimal repro that illustrates the problem is fine -- you can just share the code here like you did above

**Comment by anirbanbasu** [comment]
Sure @abidlabs, here you go: https://github.com/anirbanbasu/gradio-experiments (specifically, `src/app.py`) and its deployment at https://huggingface.co/spaces/anirbanbasu/gradio-experiments.

The global state variable (encapsulated in `gr.State`) is working as I expect -- shared state between different browser sessions. However, the user state variable (encapsulated in `gr.BrowserState`) is expected to be specific to a browser session but it isn't. It is also shared between multiple browser sessions.

What am I doing wrong? Or, is this a bug?

**Comment by anirbanbasu** [comment]
I have updated my `__deepcopy__` implementation to the following, which is more in line with what I wanted it to be. However, the user state is still being shared across browser sessions. Besides, I do not see any storage key in local storage of the browser.

```python
class StateData:
    """A class to hold the state data for the application."""

    def __init__(self, create_uninitialised: bool = False, an_object: SomeTask = None):
        """
        Create a new instance of the StateData class.

        Args:
            create_uninitialised (bool): Whether to create the object with uninitialised values. Defaults to False.
            an_object (SomeTask): An instance of the SomeTask class. Defaults to None. Specifying this has no effect if create_uninitialised is True.
        """
        if not create_uninitialised:
            self.a_pydantic_object = SomePydanticModel(a=1, b="default", c=[1, 2, 3, 4])
            self.an_object = SomeTask() if an_object is None else an_object
            self.a_list: List[SomePydanticModel] = []
            self.a_dict: Dict[str, SomePydanticModel] = {}
        else:
            self.a_list: List[SomePydanticModel] = None
            self.a_dict: Dict[str, SomePydanticModel] = None
            self.a_pydantic_object = None
            self.an_object = None

    def __deepcopy__(self, memo):
        cls = self.__class__
        newone = cls.__new__(cls)
        newone.a_pydantic_object = copy.deepcopy(self.a_pydantic_object, memo=memo)
        newone.a_list = copy.deepcopy(self.a_list, memo=memo)
        newone.a_dict = copy.deepcopy(self.a_dict, memo=memo)
        # Notice that newone.an_object is not created again and is shared between the original and the new object.
        newone.an_object = self.an_object
        return newone
```

**Comment by anirbanbasu** [comment]
I have further updated my demo at https://huggingface.co/spaces/anirbanbasu/gradio-experiments, which now shows global state, session state and browser state.

Unfortunately, they all behave the same: shared across different browser sessions. Session state is not session dependent. Browser state cannot be saved to the browser's `localStorage` although the local storage problem is most likely due to the fact that my `StateData` class is not JSON serializable.

**Comment by anirbanbasu** [comment]
@abidlabs I may have managed to implement the state management correctly. My deployment at https://huggingface.co/spaces/anirbanbasu/gradio-experiments seems to work as I would expect.

I shall close this issue for now and re-open only if this state conflict appears again.

For anyone else who may face this, see the minimal example code that seems to be working at https://github.com/anirbanbasu/gradio-experiments.

**Comment by anirbanbasu** [comment]
@abidlabs one related question is: does `gr.BrowserState` not have a `change` event? I can see that `gr.State` does.

**Comment by abidlabs** [comment]
Ok great to hear that you solved it! Feel free to open a new issue for the change event and I can implement it

**Comment by anirbanbasu** [comment]
@abidlabs okay, thanks. Meanwhile, regarding `gr.BrowserState`, I am beginning to see that the value is passed along as a JSON-string representation of the underlying object. Isn't it better to have the underlying object, for a `gr.BrowserState`,  sub-class Pydantic's `BaseModel` so that one can use Pydantic's serialisation and deserialisation instead writing one's own code to parse the string of the JSON into an object?

**Comment by anirbanbasu** [comment]
@abidlabs, my observations with a sub-class of a Pydantic `BaseModel`:

 1. Tried it for the underlying value of the `gr.State`. It fails to update properly because the sub-class implementation of `__hash__()` is ignored unless the model is set to be `frozen=True`, which makes it immutable.
 2. Parsing the JSON string value of `gr.BrowserState` seems to cause problems with the `.model_validate_json` method. An interesting error `NotImplementedError: Cannot check isinstance when validating from json, use a JsonOrPython validator instead.` is raised.
 
 Maybe, Pydantic is a bit unnecessary for what I am trying to achieve here.
